### ISSUE TITLE
Kerning on campaign sector defeat screen

### ISSUE THREAD

**Issue by Comodo17** [Anuken/Mindustry#10006]
### Platforms

iOS

### Build

v146

### Issue

On the level defeat screen for erekir karst, the letters in “deconstruct” are improperly arranged
![IMG_0849](https://github.com/Anuken/Mindustry/assets/106919547/7ff92941-050b-4ef4-bad1-c53b64b81a08)

### Steps to reproduce

Lose on erekir karst

### Mods used

None

### Save file

[mindustry-data-export 2.zip](https://github.com/user-attachments/files/16114878/mindustry-data-export.2.zip)

### (Crash) logs

n/a

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/f0174c3c-0997-4f16-bd6d-3db351cf8743)

Unable to reproduce the issue.

**Comment by Comodo17** [comment]
![image](https://github.com/user-attachments/assets/a06ec9b7-c066-4c7d-b238-1bf8b04f0483)
Got it again on a different map, another person say it’s happened to them as well

**Comment by mahdoosh1** [comment]
can you please provide logs for any warnings or errors? it would be helpful (im not a professional)

**Comment by Anuken** [comment]
This is not something that would produce logs.
