### ISSUE TITLE
Request for Arabic language support

### ISSUE THREAD

**Issue by Body2006** [Anuken/Mindustry#10003]
### Platforms

Android

### Build

7-official-146

### Issue

Request for Arabic language support

### Steps to reproduce

مرحبًا فريق تطوير Mindustry،

أود أن أشكركم على الجهود الرائعة التي تبذلونها في تطوير لعبة Mindustry. إنها واحدة من ألعابي المفضلة بسبب ميزاتها الممتازة وخلوها من عمليات الشراء داخل اللعبة.

أود أن أقترح إضافة دعم للغة العربية في اللعبة. أنا على دراية بالتحديات التقنية المرتبطة بدعم النصوص من اليمين إلى اليسار، لكنني أعتقد أنه يمكن تحقيق ذلك دون تغيير واجهة المستخدم بالكامل. يمكن ببساطة ترجمة النصوص وجعلها تُعرض من اليمين إلى اليسار، مما سيعزز تجربة اللاعبين الناطقين بالعربية بشكل كبير.

أنا واثق أن هذا التغيير سيجذب المزيد من اللاعبين من المجتمع العربي، وسيجعل اللعبة أكثر شمولية وانتشارًا.

أشكركم على اهتمامكم وآمل أن ينال اقتراحي اهتمامكم.

مع تحياتي،
[عبدالرحمن]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
the engine literally does not support RTL languages and this is not a bug

**Comment by Body2006** [comment]
> المحرك لا يدعم حرفيًا لغات RTL وهذا ليس خطأً

اسف انا لا اعرف
هل اقوم بالغاء المشكله ام ماذا

**Comment by Body2006** [comment]
فريق Mindustry حقا انا اسف انا كنت لا اعرف ان المحرك لا يدعم لغات RTL وايضا لا اعرف ان اللغة العربية من ضمن لغات RTL.
 اريد ان اساعدكم في حل مشكله ان المحرك لا يدعم لغات RTL كيف اساعدكم.

**Comment by mahdoosh1** [comment]
>  اريد ان اساعدكم في حل مشكله ان المحرك لا يدعم لغات RTL كيف اساعدكم.

If you are a programmer or a developer, you can fork the repository for the engine and make any modifications to support RTL. then you can make a pull request for that repository. You can also contribute by translating game's content or adjusting the font.

**Comment by Anuken** [comment]
RTL language are not supported and I have no plans to add support for them.

**Comment by Body2006** [comment]
اسف اذا سببت مشكلة يوما من الايام اذا دعمة اللعبه اللغه العربيه ساكون هنا للمساعده.
شكرا واسف على اي اخطاء.
شكرا متطورين لعبة mindustry.
و شكرا انكوين.
