### ISSUE TITLE
Self Compiled Version is not Running

### ISSUE THREAD

**Issue by MANKMORE** [Anuken/Mindustry#10005]
### Platforms

Windows

### Build

V7 Source

### Issue

I had compiled my download of v7 source, I actually had 2, the first one I used to compile my current one, and the second I had not changed in any way at all, however the compiled build for did not run, even though the first one worked completely fine.

### Steps to reproduce

I guess you just download V7 source and compile it.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
idk i compiled mindustry plenty of times

**Comment by mahdoosh1** [comment]
Youre right, the source code for v146 has a problem for me that archash is wrong somehow
