### ISSUE TITLE
Dropping blocks on ghost blocks via payload doesnt remove the ghost blocks

### ISSUE THREAD

**Issue by coaldeficit** [Anuken/Mindustry#10010]
### Platforms

Windows

### Build

bleeding-edge build 25109

### Issue

Using a payload unit to place a block on top of the ghost block of a destroyed block does not get rid of the ghost block that the payload placed block was put on
![Screenshot_3761](https://github.com/Anuken/Mindustry/assets/159595900/5bdd1695-1e2e-459f-b87e-0107ef356efa)

### Steps to reproduce

1. Place down any block and destroy it
2. Use a payload unit (i used evoke) to grab a different block and place it down on the ghost block of the block destroyed in step 1
3. Select any block from the build menu on the bottom right to view ghost blocks

### Mods used

coaldeficit/mdv3-beta
meepoffaith/bottom-left-ui
meepoffaith/testing-utilities-java
apszoldat/mindustry-mapping-utilities

### Save file

[payload-blocks-on-ghost-blocks.zip](https://github.com/user-attachments/files/16120368/payload-blocks-on-ghost-blocks.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Note that the repair overly will appear but never disappear unless rebuit in that spot
![IMG_20240707_233907.jpg](https://github.com/Anuken/Mindustry/assets/155455608/3f93ebe7-9121-414d-bb47-26b8b4fef4fc)
