### ISSUE TITLE
I can't  go to another sector

### ISSUE THREAD

**Issue by Mextr5ag58** [Anuken/Mindustry#10012]
### Platforms

Android

### Build

146

### Issue

when I want to land on the sector ravine, I can't because "I don't have enough tungsten in the core"
but I have **17K**
![Screenshot_20240708_073355_Mindustry](https://github.com/Anuken/Mindustry/assets/174985734/8fafc0c5-488b-4680-9920-e9956fb26025)
![Screenshot_20240708_073428_Mindustry](https://github.com/Anuken/Mindustry/assets/174985734/71fe23c0-a39f-4318-9e1e-f631baf47556)

### Steps to reproduce

I did nothing. The bug just existed.

### Mods used

no mods

### Save file

[Mindustry.zip](https://github.com/user-attachments/files/16122765/Mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
It has to be your current core in the sector you are in

**Comment by Novanox4** [comment]
The 17K is from other sectors. The core from your current sector needs to have the tungsten.

**Comment by DX-36** [comment]
enter one of your sectors with tungsten
use the planet map 🗺️ to launch to ravine

**Comment by Mextr5ag58** [comment]
thanks guys

**Comment by Matita008** [comment]
> thanks guys

Close the issue to keep the bug list clear, please

**Comment by SMOLKEYS** [comment]
bluh

**Comment by Otamamori917** [comment]
The amount of issue reports for this is Hilarious 
Add an message to combat this in a pr frfr

**Comment by mahdoosh1** [comment]
> The amount of issue reports for this is Hilarious 
> Add an message to combat this in a pr frfr

the reason for these is low knowledge
and the reason for low knowledge is low experience and low experiment.
