### ISSUE TITLE
Number parsing breaks for large values

### ISSUE THREAD

**Issue by JeanJPNM** [Anuken/Mindustry#10016]
### Platforms

Windows

### Build

BE 25113

### Issue

Numbers near 2 ^ 63 have their sign flipped when being parsed in logic code. Attempting to print `9223372036854776000` (2 ^ 63, limited by floating point precision) results in `-9223372036854775808`, which does not have correct sign. Similarly, parsing `-9223372036854776000` results in `9223372036854775807`
### Steps to reproduce

- Create a processor and link it to a message block
- Paste this code:
  ```
  op shl expected_negative 1 63
  op pow pow_positive 2 63
  op mul pow_negative pow_positive -1
  op mul expected_positive expected_negative -1
  set parsed_positive 9223372036854776000
  set parsed_negative -9223372036854776000
  print "--- negative\n"
  print "shift:\n{0}\n"
  print "pow:\n{1}\n"
  print "literal:\n{2}\n\n\n"
  print "--- positive:\n"
  print "shift:\n{3}\n"
  print "pow:\n{4}\n"
  print "literal:\n{5}\n"
  format expected_negative
  format pow_negative
  format parsed_negative
  format expected_positive
  format pow_positive
  format parsed_positive
  printflush message1
  ```
- Compare the results in the message block

### Save file

[number_parsing_bug_demo.zip](https://github.com/user-attachments/files/16131838/number_parsing_bug_demo.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
opinion rejected(2^63 as long(which is what shl uses))
![image](https://github.com/Anuken/Mindustry/assets/124447863/a3e0f24f-2c7c-49fa-a157-847750bf664f)

**Comment by JeanJPNM** [comment]
The point of the issue is to point out the disparity between the ways of getting to 2 ^63. Regardless of the operation, it will always be converted back into a double before being consumed.

![image](https://github.com/Anuken/Mindustry/assets/61994401/f3ce8c4c-54bc-4493-b7b7-fdf6df83b94f)

**Comment by broganeuquoixe** [comment]
[it's intended behavior](https://mindustrygame.github.io/wiki/logic/1-glossary/#number)

**Comment by JeanJPNM** [comment]
Rephrasing, number parsing breaks down when the values are above the long integer limit.

`1e+21` is parsed correctly in mlog, but `1000000000000000000000` is parsed as `3875820019684212736`.

In comparison, javascript (another language where numbers are stored as doubles) parses both values correctly so that:
![image](https://github.com/Anuken/Mindustry/assets/61994401/efa9f5eb-9984-43ae-bf96-94030a8192b9)

**Comment by Anuken** [comment]
> number parsing breaks down when the values are above the long integer limit.

Numbers that big are not supported, and I have no interest in supporting them.
