### ISSUE TITLE
Force projector power usage question

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1001]
what exactly does the `12 power units/second` & `Power/damage` mean? in the code i can only see it being used for the stats, it appears to not influence power in any way or form, but i might be mistaken, of course.

![Screen Shot 2019-11-05 at 15 44 14](https://user-images.githubusercontent.com/3179271/68217780-7e1d0180-ffe3-11e9-81d6-7b01d62ddabf.png)

**Comment by Anuken** [comment]
That's leftover code from back when everything had power buffers. I'll remove it.

**Comment by Quezler** [comment]
@Anuken
