### ISSUE TITLE
Had captured a sector but it was un captured when I opened the game again

### ISSUE THREAD

**Issue by Idkmanwastaken** [Anuken/Mindustry#10022]
### Platforms

Android

### Build

Release build 146

### Issue

I was playing on erekir and i had captured stronghold but when I opened the game the next day it was not captured but I still completed it once again and the same issue happened again.

### Steps to reproduce

I didn't do anything out of the ordinary I just played the sector

### Mods used

Scheme size was installed but it was not in use at that time 

### Save file

[mindustry save.zip](https://github.com/user-attachments/files/16192052/mindustry.save.zip)

### (Crash) logs

No

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Idkmanwastaken** [comment]
The research is still there

**Comment by Anuken** [comment]
Your data was corrupted for whatever reason.

**Comment by Idkmanwastaken** [comment]
> Your data was corrupted for whatever reason.

What can I do to prevent it it happened again. Delete and install the game ?
