### ISSUE TITLE
Stuck somewhere on map with no way to reset or return

### ISSUE THREAD

**Issue by busssard** [Anuken/Mindustry#10023]
### Platforms

Android

### Build

146

### Issue

After returning to the lake mission on erekir i was in the middle of redgray fog. i could scroll endless in any direction without any chance of finding the base.

i cannot reset the mission, i cannot restart the save, i have to uninstall and reinstall the game to play the mission.
so even though it might be almost a feature request i think it somehow belongs here.
A button, return to base, or at least a focus on the base whenever you exit the game might be helpful. you can pause the game, so the player has enough time to return to the location they were at, before they press resume. but this ensures that nobody gets lost.

### Steps to reproduce

Play the game, put the phone unlocked in your pocket, wait until the map is moved for long enogh, tkae the phone out of your pocket, despair

### Mods used

no mods

### Save file

[mindustry_bug.zip](https://github.com/user-attachments/files/16195676/mindustry_bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
This is not a bug, you intentionally looked deep into the void part of the map, and that is a you problem.

I can agree tho a nice "fix" would be a button to return the camera to your unit

**Comment by busssard** [comment]
> Just leave the sector and go back in it

this is not possible, you cannot enter another sector "you may not switch sectors while an existing sector is under attack"

Saying it is a you problem is a bit far. I didnt do anything intentionally... Why am i even allowed to look there, why is the map not circling around on the edges?
if anything its malicious compliance of the app. "if the user wants to get lost, we let it happen." and break the game this way 
Thats why i made a bug report, the only way to continue playing it to uninstall the game or possibly load a save file from someone else.

**Comment by Anuken** [comment]
Duplicate.

**Comment by mahdoosh1** [comment]
> This is not a bug, you intentionally looked deep into the void part of the map, and that is a you problem.
> 
> I can agree tho a nice "fix" would be a button to return the camera to your unit

just respawn

**Comment by busssard** [comment]
> just respawn

If Respawning means summoning a new builder ship, this does not reset the camera...

**Comment by Matita008** [comment]
> 
> > just respawn
> 
> If Respawning means summoning a new builder ship, this does not reset the camera...

If you are on mobile pause -> respawn -> exit and re-enter to reset the cam

**Comment by busssard** [comment]
> If you are on mobile pause -> respawn -> exit and re-enter to reset the cam

This worked.
However i am still convinced there is a bug that continously flings me out into nowhere everytime i paused the game for long time.
I just happened again and i definitely did not do it manually or accidentally this time.

But @Anuken seems to be aware of the issue, so i am happy now as i have a workaround. 
Cheers :)
