### ISSUE TITLE
map moved after closing and opening mission on erekir

### ISSUE THREAD

**Issue by busssard** [Anuken/Mindustry#10028]
### Platforms

Android

### Build

146

### Issue

Thanks anuken for your time and effort!
with the danger that it is flagged as duplicate again:

This time i observed the same issue of being moved deep into the fog of war as last time but i observed it better.

I paused the 4. mission on erekir directly after arrival.
I then had the game open in the background for 40min. And then returned to the game. I was back on the world map.
On opening the mission i was again in the fog of war. But when i had paused the game and exited i was on top of the core. 
This time i found the core by spiraling outwards. I was pushed down and left by 3 screen lenths each.

Somthing is fishy here.

### Steps to reproduce

I have not managed controlled reproduction. But it happened twice on my phone. Samsung Galaxy s20fe

Having the game open and active (paused or not) in the background for a while while using the phone otherwise, upon reopening the app the map might have moved.

(Maybe the app still takes screen input during this time which koves the map?)

### Mods used

No mods

### Save file

[mindustry_bug.zip](https://github.com/user-attachments/files/16228742/mindustry_bug.zip)

### (Crash) logs

Not crashed

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
>(Maybe the app still takes screen input during this time which koves the map?)

On PC it does

**Comment by 1dime** [comment]
Hello Matita008, I'm just letting you know that myself and a group I belong to will be taking a look at your issue, attempt to replicate, then attempt to solve it.

**Comment by Anuken** [comment]
I closed the previous issue for a reason - it's already been reported. It's no longer possible to move your camera deep into the fog of war in the latest commit.
