### ISSUE TITLE
Crash upon map save in the Bleeding Edge version

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#10026]
### Platforms

Mac

### Build

25121

### Issue

<img width="278" alt="image" src="https://github.com/user-attachments/assets/bd986e39-e6ca-428c-b81b-1a9c2bae688f">

When I attempt to save a map, be it a modded or vanilla one, the game crashes, stating that mindustry.gen.Player.unit() is null.

### Steps to reproduce

1. Create a new map.
2. Make some changes to the map, i.e. placing blocks.
3. Save the map in the escape menu.

### Mods used

liplum/MultiCrafterLib
overdramaticpanromantic/abyssus
xzxadixzx/scheme-size

Note that I was able to replicate the issue in vanilla, too.

### Save file

The crash happens in the editor, rather than in-game. Thus, I don't have a save file, but I can send the map file.

[Derelict Alloymaking Complex.msav.zip](https://github.com/user-attachments/files/16202801/Derelict.Alloymaking.Complex.msav.zip)

### (Crash) logs

[crash-report-07_13_2024_11_50_04.txt](https://github.com/user-attachments/files/16202792/crash-report-07_13_2024_11_50_04.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
disable scheme size

**Comment by camelStyleUser** [comment]
you have it on

**Comment by overdramaticpanromantic** [comment]
I said in the post that I could also replicate the issue in vanilla.

**Comment by camelStyleUser** [comment]
> I said in the post that I could also replicate the issue in vanilla.

why are you posting a modded crash log then

**Comment by camelStyleUser** [comment]
and it works for me

**Comment by Slotterleet** [comment]
> I said in the post that I could also replicate the issue in vanilla.

Your stack trace contains a Scheme Size reference.

**Comment by overdramaticpanromantic** [comment]
> > I said in the post that I could also replicate the issue in vanilla.
> 
> Your stack trace contains a Scheme Size reference.

Huh, weird. Maybe it didn't disable properly - let me try disabling it and restarting the game twice.

**Comment by overdramaticpanromantic** [comment]
> > > I said in the post that I could also replicate the issue in vanilla.
> > 
> > 
> > Your stack trace contains a Scheme Size reference.
> 
> Huh, weird. Maybe it didn't disable properly - let me try disabling it and restarting the game twice.

Two restarts fixes the issue, so it looks like Scheme Size isn't disabling properly.
