### ISSUE TITLE
game seemingly crashes on coastline land attempt

### ISSUE THREAD

**Issue by GamerPlayz200** [Anuken/Mindustry#10027]
### Platforms

Windows

### Build

Release Build 146 

### Issue

Due to me being on vacation, I've had to bring a preety old Acer laptop that uses windows 10. **Its got a Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz   2.00 GHzand 6GB's of RAM**. When I'd try to land on coastline, the game hits me with a "`Index 160000 out of bounds for length 160000`". On any other sector, it works perfectly fine, probably some initial lag due to the loading but nothing else really.

### Steps to reproduce

Zip file has the steps I did. [action.zip](https://github.com/user-attachments/files/16228397/action.zip)

### Mods used

way too many mods, I know.
[slotterleetdistributor.zip](https://github.com/user-attachments/files/16228306/slotterleetdistributor.zip)
[teamviscottmodprojectviscott.zip](https://github.com/user-attachments/files/16228307/teamviscottmodprojectviscott.zip)
[meepoffaithblack-holes-library.zip](https://github.com/user-attachments/files/16228300/meepoffaithblack-holes-library.zip)
[meepoffaithbottom-left-ui.zip](https://github.com/user-attachments/files/16228301/meepoffaithbottom-left-ui.zip)
[pseudocoffeemore-conveyors.zip](https://github.com/user-attachments/files/16228302/pseudocoffeemore-conveyors.zip)
[racti2037real-military-techic-mod.zip](https://github.com/user-attachments/files/16228303/racti2037real-military-techic-mod.zip)
[routerxdderekir-extended.zip](https://github.com/user-attachments/files/16228304/routerxdderekir-extended.zip)
[slotterleeta-lot-of-damage.zip](https://github.com/user-attachments/files/16228305/slotterleeta-lot-of-damage.zip)
[the4codeblockstogglegate.zip](https://github.com/user-attachments/files/16228308/the4codeblockstogglegate.zip)
[the4codeblockstogglegate1.zip](https://github.com/user-attachments/files/16228310/the4codeblockstogglegate1.zip)
[unionofsovietsocialistrepublicssporebiomethane.zip](https://github.com/user-attachments/files/16228311/unionofsovietsocialistrepublicssporebiomethane.zip)

[vdgasterupgraded-blocks.zip](https://github.com/user-attachments/files/16228312/vdgasterupgraded-blocks.zip)
[zuoranartemwingmindustryexpansion.zip](https://github.com/user-attachments/files/16228313/zuoranartemwingmindustryexpansion.zip)
[abe-ischarlieop-mod.zip](https://github.com/user-attachments/files/16228314/abe-ischarlieop-mod.zip)
[abomb4super-cheat.zip](https://github.com/user-attachments/files/16228315/abomb4super-cheat.zip)
[antlrrcoolturrets.zip](https://github.com/user-attachments/files/16228317/antlrrcoolturrets.zip)
[avitran0vanillaenhanced.zip](https://github.com/user-attachments/files/16228318/avitran0vanillaenhanced.zip)
[deltanedasui-lib.zip](https://github.com/user-attachments/files/16228319/deltanedasui-lib.zip)
[dong-wo-longenhancementturrets.zip](https://github.com/user-attachments/files/16228320/dong-wo-longenhancementturrets.zip)
[dong-wo-longenhancementunits.zip](https://github.com/user-attachments/files/16228321/dong-wo-longenhancementunits.zip)
[dong-wo-longhigh-leveldivisions.zip](https://github.com/user-attachments/files/16228322/dong-wo-longhigh-leveldivisions.zip)
[echovespysimplistic.zip](https://github.com/user-attachments/files/16228323/echovespysimplistic.zip)
[evo04tasersuper-cheat.zip](https://github.com/user-attachments/files/16228324/evo04tasersuper-cheat.zip)
[hao-1337mindustry-better-vanilla.zip](https://github.com/user-attachments/files/16228325/hao-1337mindustry-better-vanilla.zip)
[lethiferalsound-overhaul1.zip](https://github.com/user-attachments/files/16228326/lethiferalsound-overhaul1.zip)
[leyn-plcoreunitregen.zip](https://github.com/user-attachments/files/16228328/leyn-plcoreunitregen.zip)
[leyn-plshowallsecrets.zip](https://github.com/user-attachments/files/16228329/leyn-plshowallsecrets.zip)
[lord-gravitywavesinfinite-resources.zip](https://github.com/user-attachments/files/16228330/lord-gravitywavesinfinite-resources.zip)

### Save file

Due to the 25 MB limit and it being 29MB, I have it in my drive. https://drive.google.com/drive/folders/1HsGtjlBUZpb9PxfYrteSN6Q9q2sGIzk7

### (Crash) logs

Had to do this way or else it would not show as one singular txt. file.
[crash-report-07_14_2024_09_16_19.txt](https://github.com/user-attachments/files/16230702/crash-report-07_14_2024_09_16_19.txt)
[crash-report-07_14_2024_09_18_06.txt](https://github.com/user-attachments/files/16230703/crash-report-07_14_2024_09_18_06.txt)
[crash-report-07_14_2024_09_19_39.txt](https://github.com/user-attachments/files/16230704/crash-report-07_14_2024_09_19_39.txt)
[crash-report-07_14_2024_10_28_58.txt](https://github.com/user-attachments/files/16230705/crash-report-07_14_2024_10_28_58.txt)
[crash-report-07_14_2024_10_51_57.txt](https://github.com/user-attachments/files/16230706/crash-report-07_14_2024_10_51_57.txt)
[crash-report-07_14_2024_12_26_45.txt](https://github.com/user-attachments/files/16230707/crash-report-07_14_2024_12_26_45.txt)
[crash-report-07_14_2024_12_33_42.txt](https://github.com/user-attachments/files/16230708/crash-report-07_14_2024_12_33_42.txt)
[crash-report-07_14_2024_15_10_16.txt](https://github.com/user-attachments/files/16230709/crash-report-07_14_2024_15_10_16.txt)
[crash-report-07_14_2024_19_41_58.txt](https://github.com/user-attachments/files/16230710/crash-report-07_14_2024_19_41_58.txt)
[crash-report-07_14_2024_19_49_56.txt](https://github.com/user-attachments/files/16230711/crash-report-07_14_2024_19_49_56.txt)
[crash-report-07_14_2024_19_57_17.txt](https://github.com/user-attachments/files/16230712/crash-report-07_14_2024_19_57_17.txt)
[crash-report-07_14_2024_20_15_42.txt](https://github.com/user-attachments/files/16230713/crash-report-07_14_2024_20_15_42.txt)
[crash-report-07_14_2024_20_17_26.txt](https://github.com/user-attachments/files/16230714/crash-report-07_14_2024_20_17_26.txt)
[crash-report-07_14_2024_20_32_39.txt](https://github.com/user-attachments/files/16230715/crash-report-07_14_2024_20_32_39.txt)
[crash-report-07_11_2024_17_22_04.txt](https://github.com/user-attachments/files/16230716/crash-report-07_11_2024_17_22_04.txt)
[crash-report-07_12_2024_08_52_59.txt](https://github.com/user-attachments/files/16230717/crash-report-07_12_2024_08_52_59.txt)
[crash-report-07_12_2024_08_53_37.txt](https://github.com/user-attachments/files/16230718/crash-report-07_12_2024_08_53_37.txt)

[crash.logs.txt](https://githu
[crash-report-07_13_2024_10_30_18.txt](https://github.com/user-attachments/files/16230697/crash-report-07_13_2024_10_30_18.txt)
[crash-report-07_13_2024_10_38_59.txt](https://github.com/user-attachments/files/16230698/crash-report-07_13_2024_10_38_59.txt)
[crash-report-07_13_2024_23_11_54.txt](https://github.com/user-attachments/files/16230699/crash-report-07_13_2024_23_11_54.txt)
[crash-report-07_13_2024_23_13_21.txt](https://github.com/user-attachments/files/16230700/crash-report-07_13_2024_23_13_21.txt)
[crash-report-07_14_2024_08_59_21.txt](https://github.com/user-attachments/files/16230701/crash-report-07_14_2024_08_59_21.txt)
b.com/user-attachments/files/16230692/crash.logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by GamerPlayz200** [comment]
made a lil oopsie with the platform

**Comment by Matita008** [comment]
>  I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.
No you are not

**Comment by Slotterleet** [comment]
"Crash logs" file is empty. Maybe try to re-upload it?

**Comment by GamerPlayz200** [comment]
forgot to add the reason, but i can land now, had to disable a broken mod.

**Comment by camelStyleUser** [comment]
> forgot to add the reason, but i can land now, had to disable a broken mod.

"yeah man lets mark that i checked that it works without mods even though i didnt"
like whar???????

**Comment by GamerPlayz200** [comment]
i installed other mods...
