### ISSUE TITLE
BE startup crash

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry#10020]
### Platforms

Windows

### Build

BE 25116

### Issue

crashes on startup

### Steps to reproduce

open the game

### Save file

startup crash so no save

### (Crash) logs

[crash-report-07_11_2024_00_14_34.txt](https://github.com/user-attachments/files/16169015/crash-report-07_11_2024_00_14_34.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by denegny** [comment]
use linux, same problem after update

`Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 25116
OS: Linux x64 (amd64)
Java Version: 17.0.11
Runtime Available Memory: 3972mb
Cores: 8
Mods: none (vanilla)

java.lang.NullPointerException: Cannot invoke "mindustry.gen.Unit.isBuilding()" because the return value of "mindustry.gen.Player.unit()" is null
	at mindustry.input.DesktopInput.showHint(DesktopInput.java:61)
	at mindustry.input.DesktopInput.lambda$buildUI$1(DesktopInput.java:75)
	at arc.scene.ui.Label.lambda$setText$0(Label.java:86)
	at arc.scene.Element.act(Element.java:79)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Scene.act(Scene.java:198)
	at arc.scene.Scene.act(Scene.java:143)
	at mindustry.core.UI.update(UI.java:157)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:242)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)`

**Comment by dbax2600** [comment]
Also crashes on openjdk java version 22.0.1

**Comment by overdramaticpanromantic** [comment]
I'm also having this issue.
[crash-report-07_12_2024_10_14_29.txt](https://github.com/user-attachments/files/16195361/crash-report-07_12_2024_10_14_29.txt)

**Comment by camelStyleUser** [comment]
millions must nullcheck

**Comment by camelStyleUser** [comment]
(git patch incoming)
```
diff --git a/core/src/mindustry/input/DesktopInput.java b/core/src/mindustry/input/DesktopInput.java
index 7077a1dfb..deffb81ce 100644
--- a/core/src/mindustry/input/DesktopInput.java
+++ b/core/src/mindustry/input/DesktopInput.java
@@ -57,8 +57,8 @@ public class DesktopInput extends InputHandler{
     public long lastCtrlGroupSelectMillis;
 
     boolean showHint(){
-        return ui.hudfrag.shown && Core.settings.getBool("hints") && selectPlans.isEmpty() &&
-            (!isBuilding && !Core.settings.getBool("buildautopause") || player.unit().isBuilding() || !player.dead() && !player.unit().spawnedByCore());
+        return ui.hudfrag.shown && Core.settings.getBool("hints") && selectPlans.isEmpty()
+        && (!isBuilding && !Core.settings.getBool("buildautopause") || (player.unit() != null && player.unit().isBuilding()) || !player.dead() && (player.unit() != null && !player.unit().spawnedByCore()));
     }
 
     @Override
```
fixes this particular crash though many more might happen due to presumably missing nullchecks

**Comment by camelStyleUser** [comment]
i will check on mobile later

**Comment by camelStyleUser** [comment]
seems to work fine with -testMobile
