### ISSUE TITLE
Se me cierra el juego solo

### ISSUE THREAD

**Issue by Matijoestar91** [Anuken/Mindustry#10031]
### Platforms

Android

### Build

146

### Issue

Entro al juego y luego de un cierto tiempo se me cierra 

### Steps to reproduce

Desde ayer me a pasado lo mismo aparte de este problema de que se me cierra solo el juego hay un sector del planeta en donde no veo nada 
![Screenshot_20240715_045407_Mindustry](https://github.com/user-attachments/assets/cab14dbd-6ff5-4cc0-af2f-a000427fa7d4)

### Mods used

No he ocupado ningún mod 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Can you please add the save file and if it's crashing the crash report?
