### ISSUE TITLE
core not deleting items 

### ISSUE THREAD

**Issue by yaxhochupizzu** [Anuken/Mindustry#10035]
### Platforms

Android

### Build

146

### Issue

sometimes core does not delete items properly, i once had like 40k copper, but i could not do that again. i think this happens when units are dropping ores not in thr core directly but in the storage connected to core
did it again, but now it just goes 22k-21k
![Screenshot_20240716-084937_Mindustry](https://github.com/user-attachments/assets/261510d5-c087-4648-877b-ccabe5677850)

### Steps to reproduce

did it once with quasars mining copper in storage attached to the core

### Mods used

scheme size, time control (however was set up to 1x when bug happened)

### Save file

salt flats
[ core issue.zip](https://github.com/user-attachments/files/16278389/core.issue.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
I don't see any issue upon loading the save. Without a reliable way to reproduce this that doesn't involve mods, I can't help you.
