### ISSUE TITLE
No sound IOS iPhone 12

### ISSUE THREAD

**Issue by dominicfury** [Anuken/Mindustry#10043]
### Platforms

iOS

### Build

146

### Issue

There is no sound iOS 17.5.1 iPhone 12

### Steps to reproduce

Na

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Have you tried restarting mindustry or raising the volume (both of the phone and of the app, if there is a setting)?

**Comment by Matita008** [comment]
Also please include the log

**Comment by 1dime** [comment]
My group and I will try and resolve this issue

**Comment by Matita008** [comment]
> My group and I will try and resolve this issue

Who are you?

**Comment by 1dime** [comment]
I'm Ibrahim. My group is just a group for a CS open source course. We have to contribute to an open source project for an assignment and we chose this project.

**Comment by Matita008** [comment]
> I'm Ibrahim. My group is just a group for a CS open source course. We have to contribute to an open source project for an assignment and we chose this project.

In this case I'll suggest trying to get a new feature implemented via a pr instead of trying to fix bugs bc most of the issues are either unresolvable with the info we get, aren't an issue at all or are resolved within a short window of time (normally within a day) by anuke himself bc he is one of the few ppl who knows all about the scr

**Comment by Matita008** [comment]
>I have reinstalled, restarted my phone, done all of the obvious steps to fix this.

Can you please send the log and if you used any mod the list of said mod?

**Comment by Matita008** [comment]
>I have reinstalled, restarted my phone, done all of the obvious steps to fix this.

Can you please send the log and if you used any mod the list of said mod?

**Comment by Matita008** [comment]
And are you sure it's not a device issue?

**Comment by Matita008** [comment]
What have you done the last time the audio worked?

**Comment by Matita008** [comment]
What have you done the last time the audio worked?

**Comment by Matita008** [comment]
@dominicfury can you please compile all the required fields  and add more so we can understand better the issue?

**Comment by dominicfury** [comment]
No mods, and I just downloaded the game a few days ago, have not played
very much yet. But sound works on all my other games, sound is up in the
settings.

**Comment by dominicfury** [comment]
To clarify there is no sound anywhere, no music, so main menu sound, etc

**Comment by Matita008** [comment]
@dominicfury CAN YOU SEND THE LOG PLEASE and what have you done the last time the audio was working?

**Comment by dominiccfury** [comment]
[logs.txt](https://github.com/user-attachments/files/16350774/logs.txt)
There is no sound on any Bluetooth speaker or AirPods also. Thank you for trying.

**Comment by Matita008** [comment]
> [logs.txt](https://github.com/user-attachments/files/16350774/logs.txt)
> There is no sound on any Bluetooth speaker or AirPods also. Thank you for trying. 

1) is this an alt?
2) have you tried to disable the shaders?

**Comment by Anuken** [comment]
> have you tried to disable the shaders?

You cannot "disable" shaders, all modern OpenGL programs require them to render anything. Those warnings can be ignored.
