### ISSUE TITLE
No campaign maps? NOT FUNNY!!!

### ISSUE THREAD

**Issue by IOKAA** [Anuken/Mindustry#10041]
### Platforms

Android

### Build

Release build 146

### Issue

The're not campaign maps as vanilla, and we dont want install 20 malwares as mods, so yu should add campaign maps as vanilla

### Steps to reproduce

1 -  beat the game
2 - capture all the sectors
3 - send 4 nukes to serpulo, erekir, tantros and sol-3
4 - erase all game files
5 - not funny

### Mods used

Idk its just campaign maps at editor

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
"campaign maps are not vanilla"??? most sane mindustry player

**Comment by camelStyleUser** [comment]
also just download them from source if you really want to edit them

**Comment by SITUVNgcd** [comment]
WTF! If you want to edit them, download them from this repo.
Is this a bug?

**Comment by Anuken** [comment]
No

**Comment by IOKAA** [comment]
I cang import map file to my game, WHY?
