### ISSUE TITLE
Buggy enemy unit pathfinding/behaviour in Erekir

### ISSUE THREAD

**Issue by rowandwhelan** [Anuken/Mindustry#10046]
### Platforms

Windows

### Build

Release Build 146

### Issue

This appears to be unintended behavior and it affects all sectors. For example, on origin when the last base left is the one with powerful air units (i think its the one on the left side upper-middle, though this is just an example and still happens when there is more than one base, though more rarely) there are periods where there are no enemies attacking but I still hear the "new wave" sound which implies there are still units being created. When I built outside of my base or attack them, that seemed to cause them to realize they should attack me and because their forces have amassed to ludicrous numbers I nearly always die. Otherwise if I build inside of my base and don't provoke them then they don't attack which is actually bad since its easier to deal with a constant stream of enemies than a whole horde. I've also seen times where after defeating most of the horde there would be a couple stragglers in and around my base and sometimes they would attack and other times they would just idle there and do nothing. I don't have the technical savvy to diagnose the cause of this behavior but I'll do my best to help.

Possible copy of https://github.com/Anuken/Mindustry/issues/9871

### Steps to reproduce

Play through the campaign as normal. For no apparent reason enemies cease attacking and build up inside enemy base instead (happens with air units and likely also tank and mechs), once I build outside of my base or attack their base (moving units close to their base doesn't trigger an attack as long as im not in range of turrets or units), they attack in one massive horde which results in the destruction of my base.

### Save file

[MindustrySave.zip](https://github.com/user-attachments/files/16338366/MindustrySave.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
I think it's a known issue in the enemy AI

**Comment by Anuken** [comment]
Does your game save contain maps where the AI is **currently** exhibiting the massing behavior?

**Comment by rowandwhelan** [comment]
No, however I can try to replicate it and post one where the issue appears to be happening

**Comment by rowandwhelan** [comment]
[MindustryExport2.zip](https://github.com/user-attachments/files/16368681/MindustryExport2.zip)

@Anuken 
I've just been developing my base for around a half hour, no attacks. This is likely a good example of the enemy behavior (I haven't provoked them yet).

**Comment by Anuken** [comment]
A couple notes:

1. This isn't entirely a bug. The enemy won't attack unless it thinks it percieves an advantage in certain areas. If you build turrets faster than they build units, **they will never attack** and mass units forever.
2. The algorithm for checking advantage was flawed, and this has been fixed, but you'll still see them massing units quite often. In your save, they do end up attacking after the fix, but don't expect this to always be the case.

> there would be a couple stragglers in and around my base and sometimes they would attack and other times they would just idle there and do nothing. 

This is expected behavior, there is no AI for them to lead an attack individually **if** they have lost their group.

**Comment by rowandwhelan** [comment]
I see, was the algorithm fixed before I made this report?

**Comment by rowandwhelan** [comment]
Thanks Anuke!
