### ISSUE TITLE
No me deja entrar en el nivel "precipicio" 

### ISSUE THREAD

**Issue by EDUhub6** [Anuken/Mindustry#10044]
### Platforms

Android

### Build

146

### Issue

No me deja ingresar al nivel "precipicio" debido a que me falta 400 de tungsteno, pero eso no es verdad, tengo específicamente 39K y todos los niveles anteriores estan generando tungsteno, siento que es un bug del juego 
![Screenshot_2024-07-21-21-35-39-714_io anuke mindustry](https://github.com/user-attachments/assets/ff013e69-44c8-48fa-8fcb-f1518232f02f)

### Steps to reproduce

Me pase el anterior nivel "cumbres", perdí solo una ves y después gane agarrando el tungsteno y moviendolo manualmente al núcleo bastión, y antes de terminar las misiones que eran "guardar 50 de tungsteno, geberar óxido y de último construir dos torres de transmisión de energía, ya las tenia y de último, hice el los conductos para guardar el tungsteno de forma automática y todas lad misiones se completaron de golpe y destrui ambos núcleos enemigos y guarde mucjo tungsteno, pero no me lo cuenta o no se que pasa que me dice que tengo 0/400
![Screenshot_2024-07-21-21-35-39-714_io anuke mindustry](https://github.com/user-attachments/assets/e3a4d3e3-78ef-4f8b-b8d2-1a515335a02d)

### Mods used

Ninguno

### Save file

EREKIR SECTOR "PRECIPICIO" 

[jueguito mindustry 3.zip](https://github.com/user-attachments/files/16327655/jueguito.mindustry.3.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
DONT LAUNCH FROM LAKE.SWITCH TO ANOTHER SECTOR, PLAY IT AND LAUNCH FROM THAT SECTOR.

**Comment by Matita008** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.
No you haven't
