### ISSUE TITLE
Problem when building a map with conveyors

### ISSUE THREAD

**Issue by Friastupro** [Anuken/Mindustry#10054]
### Platforms

Windows

### Build

Steam Build 146

### Issue

When building the map, I encountered a disconnection of pipelines. I use world processors in the map to do something like a plot, but when I change the size of the available map using (Set Rule - Map Area), my pipelines of other teams stop working, including red. I'm making a map in attack mode and I need their work. Without the mod, I could not disable the function of disabling blocks outside the map. Although I fixed the problem with the help of a mod, even if the function is enabled, complete chaos occurs. When there is a change in the accessible area behind it, all the elements are turned off and when they enter the accessible area they do not turn on, but after the 2nd change in the accessible area, for some reason the conveyors begin to work, but only next to the drills.

### Steps to reproduce

I will attach the map file only it is in Russian. Just wait until the end of the first castscene and you will see what I was talking about, then open the wall to zone B using copper and lead and to zone D using graphite and silicon and you will see that some conveyors have started working, but only near the drills and not everywhere.

### Save file

[bugInMap.zip](https://github.com/user-attachments/files/16372658/bugInMap.zip)

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Friastupro** [comment]
![image](https://github.com/user-attachments/assets/effc375f-9a94-476a-8a4a-d549f667bfd6)

**Comment by Friastupro** [comment]
I use Google translator

pipelines - conveyors

**Comment by JasonP01** [comment]
not a bug, all blocks are disabled outside map area

**Comment by Anuken** [comment]
This is difficult to understand, but either you're reporting a duplicate bug related to disabled blocks after expanding map area or it's not a bug at all.
