### ISSUE TITLE
Проблема игры

### ISSUE THREAD

**Issue by RSBLITSI** [Anuken/Mindustry#10052]
### Platforms

Android

### Build

release build 146

### Issue

Не могу скачать схемы зайти в мультиплеер скачать модификации и вообще посмотреть их выдаёт эту ошибку
![Screenshot_20240725-005219](https://github.com/user-attachments/assets/faeb68e7-0988-4a43-8c4e-cd5745348900)

### Steps to reproduce

Проблема появилась из ниоткуда 

### Mods used

Единственный используемый мод это "byte logic mod"

### (Crash) logs

![Screenshot_20240725-005219](https://github.com/user-attachments/assets/ad91f4cb-d876-4a2d-95b3-6fa1ea68e888)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Mindustry hasn't access to internet

**Comment by Matita008** [comment]
Probably you have your connection turned off

**Comment by Slotterleet** [comment]
Проблема с твоим интернетом, или же провайдером. Попробуй зайти туда же, но уже с каким-нибудь VPN.

**Comment by Friastupro** [comment]
у меня такая ошибка была очень много раз 2 самых рабочих метода не скачивать какие попало моды(оно иногда ламают интернет для минды) и просто сбрось прогресс или переустанови минду

**Comment by RSBLITSI** [comment]
> Вероятно, у вас отключено соединение.

Нет интернет в рабочем состоянии

**Comment by RSBLITSI** [comment]
> Проблема с твоим интернетом или тем же провайдером. Попробуй зайти туда же, но уже с каким-нибудь VPN.

С интернетом всё нормально поверь на слово хотя вопрос тогда видит ли его минда так как инет работает

**Comment by RSBLITSI** [comment]
> у меня такая ошибка была очень много раз 2 самых рабочих метода не скачать какие попало моды(но иногда ламатят интернет для минды) и просто сбросить прогресс или переустановить минду

Этот вариант не подходит

**Comment by RSBLITSI** [comment]
> у меня такая ошибка была очень много раз 2 самых рабочих метода не скачать какие попало моды(но иногда ламатят интернет для минды) и просто с прогрессбросить или переустановить минду

А что по поводу модов я использую только. 1 мод и это не из за него точно

**Comment by Slotterleet** [comment]
> > Проблема с твоим интернетом или тем же провайдером. Попробуй зайти туда же, но уже с каким-нибудь VPN.
> 
> С интернетом всё нормально поверь на слово хотя вопрос тогда видит ли его минда так как инет работает

Я сказал включить VPN. Говорю же, провайдер может блокировать домены гитхаба.
