### ISSUE TITLE
Odd visual bug when trying to type on a payload source whilst paused

### ISSUE THREAD

**Issue by Twcash** [Anuken/Mindustry#10058]
### Platforms

Windows

### Build

25138 BE

### Issue

https://github.com/user-attachments/assets/0fbfef47-58cd-4f42-862b-6c614721c5fe

Payload sources have a weird visual bug when trying to type when paused

### Steps to reproduce

1: build a payload source
2: pause game
3: move camera from player
4: click on payload source search bar

### Mods used

noe

### Save file

[payloadSourceBug.zip](https://github.com/user-attachments/files/16385454/payloadSourceBug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Twcash** [comment]
Yes this is done on one of my branches but this also happens on the newest BE

**Comment by Twcash** [comment]
https://github.com/user-attachments/assets/42aece27-1d64-4bcd-8031-09fc0c9d5078

**Comment by JasonP01** [comment]
Its tryna go back to your unit

**Comment by JasonP01** [comment]
Does this happen in 146? It would be weird if this got introduced in after

**Comment by Twcash** [comment]
I looked at the source code and I could'nt find what was causing it. It's pretty annoying for me

**Comment by Twcash** [comment]
annd it happens on 146 and BE

**Comment by Anuken** [comment]
Doesn't happen to me. Do you have left-click bound to panning the camera, maybe? If so, that's your issue - it tries to pan to the camera for a split second until the field is focused.
