### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by Bobl-ux** [Anuken/Mindustry#10050]
### Platforms

Android

### Build

147

### Issue

Я не могу попасть на сектор ущелье

### Steps to reproduce

Я покинул ущелье из-за проигрыша и моё ядро почему-то появилось на секторе озеро и чтобы попасть на ущелье нужен вольфрам которого не на озере

### Save file

Сектор ущелье и озеро
[поп.zip](https://github.com/user-attachments/files/16357045/default.zip)

### (Crash) logs

[проб.zip](https://github.com/user-attachments/files/16357063/default.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Not an issue, change the sector you are launching from

**Comment by Bobl-ux** [comment]
> > Я просмотрел закрытые и открытые вопросы, чтобы убедиться, что об этой проблеме еще не сообщалось.
> 
> НЕТ, ТЫ НЕ ПОТРОГАЛ НИЧЕГО ИСКАТЬ, ЭТО БЫЛО СКАЗАНО ТАК МНОГО РАЗ

how to change the sector?
(sorry,I'm using translator)

**Comment by Matita008** [comment]
> > > Я просмотрел закрытые и открытые вопросы, чтобы убедиться, что об этой проблеме еще не сообщалось.
> > 
> > НЕТ, ТЫ НЕ ПОТРОГАЛ НИЧЕГО ИСКАТЬ, ЭТО БЫЛО СКАЗАНО ТАК МНОГО РАЗ
> 
> how to change the sector?
> (sorry,I'm using translator) 

Search for other issues like this and you will be answered

**Comment by Matita008** [comment]
And close this issue

**Comment by Friastupro** [comment]
зайди на сектор с которого хочешь запустится и запускайся куда нада

проблема только если сектора стоят в плотную но вы вроде говорите про эрекир и такого там не будет
