### ISSUE TITLE
"Always" weather not showing up in corresponding campaign maps

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry#10064]
### Platforms

Windows

### Build

V146

### Issue

Run into the issue of "Always" weather not showing up in campaign
Made a modded map with a custom weather set to "Always", and in a custom game it shows up, but a the campaign sector it will not
![image](https://github.com/user-attachments/assets/cf7e163b-e2fb-4a32-82b9-45ceb5b0a9c0)

(Campaign)
![image](https://github.com/user-attachments/assets/b84799ab-f2f9-4013-b506-d6f78cab6daa)

(Custom Game)
![image](https://github.com/user-attachments/assets/ae7b0313-4f95-4658-988c-db32d286bc30)

### Steps to reproduce

Step 1: Land on any sector in Ikaru
Step 2: There is no weather
Step 3: Go into the corosponding map in a custom game
Step 4: There's weather?

Happens on all four sectors on Ikaru

### Mods used

[meld-master.zip](https://github.com/user-attachments/files/16400592/meld-master.zip)
[meepoffaithtesting-utilities-java.zip](https://github.com/user-attachments/files/16400587/meepoffaithtesting-utilities-java.zip)
[sk7725timecontrol.zip](https://github.com/user-attachments/files/16400588/sk7725timecontrol.zip)
[meepoffaithbottom-left-ui.zip](https://github.com/user-attachments/files/16400590/meepoffaithbottom-left-ui.zip)

### Save file

[first four sector saves.zip](https://github.com/user-attachments/files/16400583/first.four.sector.saves.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Weather is set by the sector generator, anything you set it in the editor does not affect it.
