### ISSUE TITLE
Баг со песком

### ISSUE THREAD

**Issue by Aboglabo** [Anuken/Mindustry#10077]
### Platforms

Android

### Build

7-official-146

### Issue

Если в сортировщике выбрать стекло то через него будут идти стекло и песок незнаю это баг или фича

### Steps to reproduce

сортировщике выбрать стекло то через него будут идти стекло и песок 

### Mods used

Нету

### Save file

Немогу

### (Crash) logs

Нету

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Save files are required.
