### ISSUE TITLE
Random materials out of nowhere and junctions dont work

### ISSUE THREAD

**Issue by ZaharitIngot** [Anuken/Mindustry#10070]
### Platforms

Windows

### Build

25150

### Issue

i have mods enabled and when im playing example asthosus it just pops out of nowhere not researched items from the mod and copper on the conveyors stopping factories. junctions dont work too

### Steps to reproduce

1.Go on any modded planet sector
2.Conveyors have copper(no copper on modded planet)
3.Junctions dont work

### Mods used

Allure, Asteroidgen, Asthosus, Asthosus  OST, Black holes library, Random Planet Generator, Exogenesis, Gloomistry, Buried In Ice, Intermod, Fading revelations, Fading revelations OST, Frozen Farlands, Multicrafter LIB, Nightscape, Psammos mod, Sapphirium, Scheme size lite, Unlimited Armament works

### Save file

[report zip.zip](https://github.com/user-attachments/files/16424777/report.zip.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Catana791** [comment]
It's a known issue that (save file) corruption can happen when you use multiple planet mods together.

I am guessing the same thing is happening here.
Perhaps some of the mods have files that have the same file names which causes conflicts.

**Comment by Mythril382** [comment]
> I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

Have you actually checked? One-by-one?

**Comment by ZaharitIngot** [comment]
its like when there more than 5 mods random items pops out of nowhere on planets and what if i have bug caused by mods?

**Comment by Anuken** [comment]
> and have made sure the bug is not caused by mods I have installed.

This is not a vanilla issue, so I will not be investigating further.

**Comment by Mythril382** [comment]
> its like when there more than 5 mods random items pops out of nowhere on planets and what if i have bug caused by mods?

Considering reading. The last checkbox also needs you to check if your issue isn't caused by mods. When you make an issue next time with mods, make sure to try checking.

**Comment by SITUVNgcd** [comment]
Wow! You have a ton of mods. Make sure they're not conflicted.
