### ISSUE TITLE
Можно играть за маршрутизатор

### ISSUE THREAD

**Issue by Aboglabo** [Anuken/Mindustry#10076]
### Platforms

Android

### Build

7-official-146

### Issue

я строил завод по стеклу и тут я случайно нажал два раза по маршутизатуру ну и как стрелять нельзя думаю это баг

### Steps to reproduce

Кликнуть два раза по маршрутизатору

### Mods used

Нету

### Save file

Я не могу 😭😭😭😭😭

### (Crash) logs

Нету такова 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Kirill4Smirnov** [comment]
Это не баг...
Это была одна из киллер-фич V6 - возможность играть за роутер (и выбирать, в какую сторону поедут ресурсы)

**Comment by camelStyleUser** [comment]
whar

**Comment by camelStyleUser** [comment]
you can control a router

**Comment by Krita-Burstflakes** [comment]
Low iq moment
