### ISSUE TITLE
i cant see a suggestion so i commut as a bug any drill on different source on serpulo take most of the source input

### ISSUE THREAD

**Issue by quanium** [Anuken/Mindustry#10082]
### Platforms

Windows

### Build

25162

### Issue

any drill on any source on serpulo take most of the source input

i expected to drill anything and later filter output

### Steps to reproduce

place any drill on mixed ore

### Mods used

NO

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
It's intended behavior

**Comment by Matita008** [comment]
And there is a suggestion repo

**Comment by Cookies7aaaaaaa** [comment]
it's supposed to drill the resource that it has more of its size on.
