### ISSUE TITLE
Accurate power generation and consumption cannot be obtained by using a diode

### ISSUE THREAD

**Issue by RGBaaa** [Anuken/Mindustry#10081]
### Platforms

Android

### Build

25162

### Issue

On both sides of the diode,using logic to sense @powerNetIn and @powerNetOut values is inaccuracy,even negative numbers.

### Steps to reproduce

1. Build a diode and build the battery and the node on both sides.
2. Use logic to sense the values of the @powerNetIn and @powerNetOut on both sides. 
3. These values will be Inaccuracy.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
A diode divides a network into 2

**Comment by Anuken** [comment]
Diodes transfer battery power, they don't affect those values.

**Comment by BasedUser** [comment]
i am having intrusive thoughts about this issue
