### ISSUE TITLE
Heat Redirector Visual Glitch

### ISSUE THREAD

**Issue by endcr** [Anuken/Mindustry#10098]
### Platforms

Windows

### Build

25170

### Issue

Heat redirector flashing after being heated.

### Steps to reproduce

Place a heat redirector and heat it up.

### Save file

[1.zip](https://github.com/user-attachments/files/16517094/1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Fixed in Arc.
