### ISSUE TITLE
Game constantly crashes and I don't know how to fix it/what happened

### ISSUE THREAD

**Issue by chartreuse-af** [Anuken/Mindustry#10097]
### Platforms

Windows

### Build

release build 146

### Issue

I open the game and play for a few minutes and then it just randomly exits out of the game and back to my desktop. I have three error files but a Windows error message did not appear. 

(my windows is unactivated as of writing this, i dont know if it could have anything to do with this, but i am mentioning this just in case)

### Steps to reproduce

Just regularly playing for a few minutes.

### Save file

[save.zip](https://github.com/user-attachments/files/16516574/save.zip)

### (Crash) logs

[crash.txt](https://github.com/user-attachments/files/16516575/crash.txt)

this is also what appeared in my folder where i unzipped the game files:
[hs_err_pid10692.log](https://github.com/user-attachments/files/16516576/hs_err_pid10692.log)
[hs_err_pid8000.log](https://github.com/user-attachments/files/16516577/hs_err_pid8000.log)
[hs_err_pid10292.log](https://github.com/user-attachments/files/16516578/hs_err_pid10292.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
The crashes linked look like JVM-level bugs. I've never seen this before and it's not something I can fix. Might be something related to your Windows version or another program messing with Java.

**Comment by SITUVNgcd** [comment]
Another bug related to JVM of OpenJDK.
