### ISSUE TITLE
Broken shield texture

### ISSUE THREAD

**Issue by HexShales** [Anuken/Mindustry#10104]
### Platforms

Android

### Build

release build 146

### Issue

![Screenshot_20240809_085549_Mindustry](https://github.com/user-attachments/assets/ee71f35f-f469-4deb-bb17-aa582c0af361)

Shield texture has lines similar to when building and is unclear. Happens when no other animated surfaces are visible

### Steps to reproduce

Place Shield projector away from any animated surface (such as water or oil)

### Mods used

None

### Save file

[Shield bug.zip](https://github.com/user-attachments/files/16555974/Shield.bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
![image](https://github.com/user-attachments/assets/f3d9f7e2-f31b-4b8e-9b0b-772ab75b1ce2)

Cannot reproduce the issue, and I've never seen anyone report something like this before.
