### ISSUE TITLE
kotlin-related build failure

### ISSUE THREAD

**Issue by mwoehlke** [Anuken/Mindustry#10103]
### Platforms

Linux

### Build

9063fca2b5d0782900d392c7d50a88104f3cdf67

### Issue

Trying to build on Fedora 40 fails with:
```
file or directory '.../mindustry/core/build/generated/source/kapt/main', not found
file or directory '.../mindustry/core/build/generated/source/kaptKotlin/main', not found
Build cache key for task ':core:kaptKotlin' is <hash>
Task ':core:kaptKotlin' is not up-to-date because:
  No history is available.
The input changes require a full rebuild for incremental task ':core:kaptKotlin'.
Running kapt annotation processing using the Gradle Worker API
Using workers NONE isolation mode to run kapt

...

> Task :core:kaptKotlin FAILED
```

### Steps to reproduce

On Fedora 40 (using `java-21-openjdk[-devel]`):
```
$ cd mindustry
$ ./gradlew --info desktop:dist
```

### Mods used

n/a

### Save file

n/a

### (Crash) logs

n/a

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mwoehlke** [comment]
With `java-17-openjdk-devel`:
```
file or directory '.../mindustry/core/build/generated/source/kapt/main', not found
file or directory '.../mindustry/core/build/generated/source/kaptKotlin/main', not found
file or directory '.../mindustry/core/build/tmp/kapt3/stubs/main', not found
```

...although I'm pretty sure I've seen the missing `tmp/kapt3/stubs/main` before also, so there doesn't seem to be any difference between 17 and 21.

**Comment by Anuken** [comment]
Kotlin code isn't even used in this repository, so I'm not sure why those messages should affect whether the build fails or not.

Frankly, I've never had this issue, or anything remotely similar, so the most I can suggest is "try googling it", which you have probably tried already. Maybe you're looking at the wrong logs.

**Comment by Kieaer** [comment]
It may generated from android build.
You must use Java 16.
Java 17 isn't supported because some library has only java 16 support.

**Comment by mahdoosh1** [comment]
> Kotlin code isn't even used in this repository, so I'm not sure why those messages should affect whether the build fails or not.
> 
> Frankly, I've never had this issue, or anything remotely similar, so the most I can suggest is "try googling it", which you have probably tried already. Maybe you're looking at the wrong logs. I can't help you.

You didnt but i did

**Comment by mwoehlke** [comment]
> Kotlin code isn't even used in this repository

There are quite a few references in `build.gradle` for something that "isn't even used"...

If I remove them, I don't get the error, but I get quite a few "cannot find symbol" for e.g. `Player` and `Teamc` (and maybe others). Which... where *do* those come from?

**Comment by mwoehlke** [comment]
Anyway, the problem seems to come from `kapt project(":annotations")`. If I comment that out, I don't get this specific issue. (But I do get a mess of "cannot find symbol", as noted.)

**Comment by mwoehlke** [comment]
Ugh. Okay, it *does* work with JDK 17, but only after using `alternatives --config java` to force `java` to be 17. Maybe when I *thought* I was trying 17 before, I still had either 21 or 22 still installed?

**Comment by mahdoosh1** [comment]
> Anyway, the problem seems to come from `kapt project(":annotations")`. If I comment that out, I don't get this specific issue. (But I do get a mess of "cannot find symbol", as noted.)

Thank you. I assume those are some warnings and can be safely ignored.

i will try that as well and see if it works. i am trying to compile Mindustry in Android which is very unsupported and no one even is trying to support and help me (even anuke himself) i appreciate the fix for that problem.

**Comment by gabriel-tandil** [comment]
> Ugh. Okay, it _does_ work with JDK 17, but only after using `alternatives --config java` to force `java` to be 17. Maybe when I _thought_ I was trying 17 before, I still had either 21 or 22 still installed?

Same problem, thanks for your comment
