### ISSUE TITLE
multiplayer dont work

### ISSUE THREAD

**Issue by IlyaYDen** [Anuken/Mindustry#10106]
### Platforms

Mac

### Build

146

### Issue

I can join to the server with players but i dont see anyone and my character dont spawn. But chat is working. /sync dont do anything
![image](https://github.com/user-attachments/assets/c7f66414-33ce-431e-91de-830000abbe05)

### Steps to reproduce

1. open game (steam or jar doesnt meter)
2. go to server list
3. join to any server

### Mods used

no mods

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This is a known problem, but I cannot reproduce it, it's likely related to certain network conditions. This may be investigated more in the future, but I cannot do anything with the information given.

**Comment by IlyaYDen** [comment]
it strange because from android or windows with same internet it works normal

**Comment by NoSanityHere** [comment]
im on an intel macbook and it works, what specific model of mac are u on

**Comment by Matita008** [comment]
> it strange because from android or windows with same internet it works normal. But if i run mindustry with windows emulator in mac it dont work too. Mb it depends on hardware
> And if i connect mac to mobile network it dont work too


I think it's due to a loss of packet, so a network issue rather than a device issue 
This issue happened to me a couple of times when I had a bad connection and never when the internet connection was good

**Comment by Kieaer** [comment]
It caused by both protocol not opened.
You must open UDP/TCP protocol.

if udp only -> can see server info from server list, can't chat, can't build, can't real time sync.
if tcp only -> can't see server info, can chat, can build, can real time sync.

**Comment by IlyaYDen** [comment]
it was problem with firewall, ty
