### ISSUE TITLE
Crux(red) team in sandbox and attack mode has unlimited number of units independently from core type or amount

### ISSUE THREAD

**Issue by Jlucu4ka228** [Anuken/Mindustry#10113]
### Platforms

Linux

### Build

release build 146

### Issue

Red team has unlimited unit amount regardless rules or core amount/type. Perhaps they has no limit even in PvP, but I did't test that.

### Steps to reproduce

Go into map redactor, create a simple map with 2 cores: red one and any other. Every faction must have at least one working unit factory or payload source. As the result, red will be making infinite amount of units, whereas other factions have a certain limit, tied to the core(s) characteristics

### Mods used

No mods were used

### Save file

[anuken_hi.msav.zip](https://github.com/user-attachments/files/16599927/anuken_hi.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by alphy228** [comment]
If a team is selected as "enemy team" it will have no unit cap and use enemy ai

**Comment by Jlucu4ka228** [comment]
> If a team is selected as "enemy team" it will have no unit cap and use enemy ai

Anyways I think it's a bug. But perhaps was made so attack maps would work normally and send a lot of uints /shrug

**Comment by alphy228** [comment]
Its intended behaviour

**Comment by Jlucu4ka228** [comment]
ok

**Comment by Jlucu4ka228** [comment]
> close issue ⛈️

I want to wait Anuken's reply.

**Comment by Anuken** [comment]
Intentional.
