### ISSUE TITLE
WProc-only variables accessable by regular processors.

### ISSUE THREAD

**Issue by Kokice5** [Anuken/Mindustry#10125]
### Platforms

Windows

### Build

25182

### Issue

Built-in variables that are world processor-only can be read by regular processors.

![image](https://github.com/user-attachments/assets/ea457b9c-12dc-4e3c-b9e8-c07536d0337b)

### Steps to reproduce

In a non-world processor, paste this code:
```
print "@server: "
print @server
print "\n@client: "
print @client
print "\n@clientLocale: "
print @clientLocale
print "\n@clientUnit: "
print @clientUnit
print "\n@clientName: "
print @clientName
print "[white]\n@clientTeam: "
print @clientTeam
print "[white]\n@clientMobile: "
print @clientMobile
printflush message1
```
Then connect that processor to a message block.
The processor will be able to read the variables and output their values.

### Save file

[bug.zip](https://github.com/user-attachments/files/16639640/bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
#10126
