### ISSUE TITLE
Game crashes after I play for a while 

### ISSUE THREAD

**Issue by I-AM-MAN** [Anuken/Mindustry#10124]
### Platforms

Android

### Build

7-official-146

### Issue

When I play for 5 minutes or so the game suddenly  crashes and I'm kicked to my home screen. I'm using a Samsung A03 if that helps

### Steps to reproduce

Open the game.
Play on the purple planet in career 
Play for a while 
He game suddenly crashes

### (Crash) logs

[crash log](https://github.com/user-attachments/files/16639538/crash.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
The log contains no crashes.

**Comment by I-AM-MAN** [comment]
Hi

The game still does crash should I send a screen recording of what happens?

**Comment by Anuken** [comment]
No, that won't help either. I can't help you.

**Comment by I-AM-MAN** [comment]
Ok, thanks anyway.
