### ISSUE TITLE
Game crashes... and i don't know why

### ISSUE THREAD

**Issue by AVeryCoolSpider-PL** [Anuken/Mindustry#10122]
### Platforms

Android

### Build

Any

### Issue

No matter what i do, after a certain amount of time, the game crashes. It started three days ago, i didn't do anything special with my device. I use a Samsung Galaxy A34 5G phone.
...I don't know if this matters, but each time when the crash happens, it takes less time from entering the app until the crash. Clearing my save didn't help, same with re-installing.

### Steps to reproduce

I just turn the app on and wait.

### Mods used

Frozen Farlands and Scheme Size Lite; however i installed them a day after the game started crashing. I used both of these before, and at that time they were fine.

### Save file

I have lost access to it when i tried to fix the problem.

### (Crash) logs

I can't access the crash logs; nothing tells me what can be the problem caused by.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
- Crash logs are required when reporting crashes. I cannot help you without them.
- You have mods installed, and the issue template specifically asks to report problems that cannot be caused by mods.

**Comment by SITUVNgcd** [comment]
From Android 12, we can't access app's data (Android/data/) outside the app.

**Comment by Mavment** [comment]
If you have pc use android usb debug function located in dev settings (google how to turn it on) then go to android/data/(some folder with word "mindustry" in it, will look like "io.anuke.mindustry")/files/ and try searching there to find crashlogs, if you have no pc find some adb app (for example iadb) and file explorer, use adb to bypass android data folder security using android wifi debug, then try to access folder that i told about earlier and find crashlog

**Comment by Slotterleet** [comment]
> From Android 12, we can't access app's data (Android/data/) outside the app.

You can extract all the crash logs from in-game settings though...

**Comment by Mavment** [comment]
I forgor about that function entirely💀, anyways he need to get logs

**Comment by SITUVNgcd** [comment]
> > From Android 12, we can't access app's data (Android/data/) outside the app.
> 
> You can extract all the crash logs from in-game settings though...

I fogot it! My shitty brain.

**Comment by Matita008** [comment]
> From Android 12, we can't access app's data (Android/data/) outside the app.

The internal file manager can only read /android/data & /android/obb

So with that you can copy it

**Comment by mahdoosh1** [comment]
> The internal file manager can only read /android/data & /android/obb

Untill android 14 (in which i regret updating to)

**Comment by SITUVNgcd** [comment]
After updated, system apps (like built-in android file) has been blocked from accessing any directories in __Android/data/__

**Comment by mahdoosh1** [comment]
> After updated, system apps (like built-in android file) has been blocked from accessing any directories in __Android/data/__

If your android isn't 14 then you can install am file browser app that asks for access to android data folder.

if your android is 14 then the only way is connecting your phone to a PC or using adb with an app called LADB (You have to understand bash commands in order to work with it)
