### ISSUE TITLE
Полный сброс Дегтярные поля 

### ISSUE THREAD

**Issue by Markov2033** [Anuken/Mindustry#10128]
### Platforms

Android

### Build

146

### Issue

В секторе Дегтярные поля моя основная база в очередной раз зашёл туда чтобы переправить ресурсы на другой сектор долго грузилось но в итоге вылетела ошибка зашёл но моей базы больше не существует сектор просто сбросился будто я его и не проходил 

### Steps to reproduce

Зашёл на сектор чтобы перекинуть ресурсы на другой вылетела ошибка после этого зашёл на сектор и всё заново

### Mods used

Не использую моды 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
No crash log attached.
