### ISSUE TITLE
Enemy units survive sector capture if in payload form

### ISSUE THREAD

**Issue by BigWingBeat** [Anuken/Mindustry#10135]
### Platforms

Linux

### Build

146 and current git master

### Issue

Normally, when an attack-mode sector is captured in the campaign, all enemy units that are still alive will self-destruct. However, if a unit is in payload form, such as from being on a payload conveyor, they will not be destroyed, and can be taken out of payload form, at which point they will begin attacking like normal.

https://github.com/user-attachments/assets/db59842f-4dc2-44ff-9fd3-cb139925b6d9

### Steps to reproduce

- Capture an attack-mode sector that has enemy units which remain in payload form
- Locate payload conveyors or other payload-carrying blocks that still carry enemy units
- Destroy said blocks
- Enemy units are taken out of payload form and begin attacking

### Mods used

- New Console (Only for build 146, testing on git master had no mods)

### Save file

[save.zip](https://github.com/user-attachments/files/16702373/save.zip)
- Sector: Origin on Erekir (Note that all the enemy locuses featured in the above video are destroyed in this save)

-----

[onset.msav.gz](https://github.com/user-attachments/files/16702381/onset.msav.gz)
- The test map I used to confirm that the bug is still present on Git master ([d8edf23](https://github.com/Anuken/Mindustry/commit/d8edf2334977af479c87ecdce29f7707fddf1d44) as of writing)
  - Use Obviates to go north and destroy the two cores, then test with the payload conveyor of Locuses above the second core

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

No you haven't and I think it's intended behavior

**Comment by Matita008** [comment]
Literally the issue before this talk about this

**Comment by Anuken** [comment]
This has been reported before at least twice.
