### ISSUE TITLE
Restricted area can remove build

### ISSUE THREAD

**Issue by bviibvii** [Anuken/Mindustry#10136]
### Platforms

Android

### Build

146

### Issue

After setting the Limit Map Area, you can remove the blocks outside the map.Comprise a server and a single person.I think it's a bug.

### Steps to reproduce

When I was playing with the server, I accidentally removed the Memory bank outside the map, which led to problems in world logic.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This is why world cells were introduced. Use them when they are released instead.
