### ISSUE TITLE
Mindustry setting item ”pixelate“ affects text from worldProcessor

### ISSUE THREAD

**Issue by mctheend** [Anuken/Mindustry#10145]
### Platforms

Windows

### Build

v146

### Issue

![image](https://github.com/user-attachments/assets/7ab447e1-5093-4af5-b914-4067659e223f)

### Steps to reproduce

1.Open 'pixelate'
2.Use command ‘flush message'
3.You can't see the text clear because the text are also pixelate!

### Mods used

I wasn't use any mod.

### Save file

Ground Zero.But it also can happen in other saves

### (Crash) logs

It didn't crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by ApsZoldat** [comment]
https://github.com/Anuken/Mindustry/issues/7278#issuecomment-1203887020

Shhh please be quiet

**Comment by mctheend** [comment]
o
