### ISSUE TITLE
[BUG] about blueprint

### ISSUE THREAD

**Issue by Goto-Namj** [Anuken/Mindustry#1014]
**Platform**: *Windows*

**Build**: *steam build 99.11*

**Issue**: *blueprint error*

**Steps to reproduce**:
*The factory on the left is made from a blueprint.
On the right is the source of the blueprint.
The output of the right and left is different.*

![mindustryscreen](https://user-images.githubusercontent.com/45956673/68387399-90449e80-01a1-11ea-8bd2-eecf73202d2f.png)

**Comment by Anuken** [comment]
Not a bug. Your design looks like it depends on block placement order, which gives undefined results. If you were to place it again, the result would probably be the same.

**Comment by Goto-Namj** [comment]
When I checked the tunnel, I thought it was a bug because there was no difference between the two.
Of course, as you mentioned, relocating the tunnel solves the problem.
