### ISSUE TITLE
`@stone-wall` still prints as `solid` even after `@solid` was removed

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry#10148]
### Platforms

Linux

### Build

25169

### Issue

printing `@stone-wall` prints the text `solid` rather than `stone-wall`

### Steps to reproduce

put this code into a processor, and see what it prints.
```
print @stone-wall
printflush message1
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Mavment** [comment]
Stone wall is so solid that processor can't stand mentioning it

**Comment by Anuken** [comment]
Fixed
