### ISSUE TITLE
Chinese input method typing problem 中文输入法打字问题

### ISSUE THREAD

**Issue by yyx-i** [Anuken/Mindustry#10150]
### Platforms

Windows

### Build

30844

### Issue

When using some Chinese input methods, I want to delete a pinyin, but MDT also deletes a word that I have typed, making it difficult to enter Chinese.

Used Microsoft Translator
使用微软翻译

_Original 原文:
在使用某些中文输入法时,想删除一个拼音,MDT却也删除了一个我已经打好的字,导致难以输入中文_

### Steps to reproduce

In any place where you enter
在任何输入的地方

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
I'm not sure what you mean at all or how to reproduce this, this is something that would need to be handled/fixed by someone who knows Chinese.

**Comment by yyx-i** [comment]
e.......,okay.
