### ISSUE TITLE
Behaviour of Flying Support Drones will cause them to seek destruction

### ISSUE THREAD

**Issue by betalars** [Anuken/Mindustry#10158]
### Platforms

Linux

### Build

Steam Build 146

### Issue

Flying drones set to repair, assist player or rebuild will not avoid paths with heavy enemy fire. They will actually fly right trough enemies, even when there is a safe path trough shields and even if there is no apparent reason to move.

### Steps to reproduce

1. Go open the map.
2. Trigger an Enemy wave  
Observed:
When the Enemies destroy a bit of the first defense line, Support Drones will take a direct path to the Zone where buildings were destructed, right through enemy fire. When the rebuilding is done, they will fly back right over the enemy units back to a pretty consistent rally spot, being destroyed. Units set to support the player will also engage enemies far outside the player reach once I got damaged once.
This causes a ton of units being destroyed.

### Mods used

none

### Save file

MSAV FILES ARE NOT SUPPORTED BY GITHUB PLEASE DO NOT SCREAM AT ME. GO FIX THAT. THANK YOU.
[sector-serpulo-70.msav.zip](https://github.com/user-attachments/files/16787937/sector-serpulo-70.msav.zip)
![mindustry-bug](https://github.com/user-attachments/assets/f4ab9b5d-6898-42ff-8220-f8a1e45fbe8a)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by betalars** [comment]
ADDITIONAL INFORMATION/THOUGHTS:
1. I do not understand why they rally at this particular spot. But it is kind of consistent.
2. I think units should prioritize moving trough shields.
3. Units should seek health turrets when damaged and not having anything else to do.
4. Units should avoid enemies when damaged unless they have a job to do.
5. I will go make some feature proposals to deal with this bug.

**Comment by betalars** [comment]
This is btw a bug where I am aware it is pretty on the line of Feature Request vs Bug.

I think this qualifies as unexpected behavior. Especially the units flying back to a implicit rallying point I don't really understand seems like a bug to me.

But a lot of remedies for this are features.

**Comment by betalars** [comment]
Hm, I think I understand the rally spot.

It is on line of sight between the Building Destruction Zone and their spawn point. I - without having any knowledge about the actual state machine - could imagine something along the lines of:

Better seek cover behind the first shield I passed trough on my way to the front line.

**Comment by Anuken** [comment]
> MSAV FILES ARE NOT SUPPORTED BY GITHUB PLEASE DO NOT SCREAM AT ME. GO FIX THAT. THANK YOU.

That is why the template asks you to **zip** individual files, **or attach the entire campaign zip if the issue is in the campaign.** You sent a save file that cannot be properly used, as it does not have all the campaign state.

I do not control which file formats Github supports in issues.

---

This is not a bug. Support units do not have any kind of pathfinding and do not avoid enemy units when flying to rebuild/repair something. I have no plans to add this functionality. I do not see them moving for no reason when testing the save.

**Comment by betalars** [comment]
> I do not see them moving for no reason when testing the save.

Are you really sure you cannot replicate them moving to that implicit rally point when they would have nothing to repair there once they are done repairing in the zone that is being destroyed?

Because this is happening really consistently for me.

**Comment by mahdoosh1** [comment]
> I have no plans to add this functionality.

Anuken being lazy/busy is the one thing every bug report / feature request / push request should be prepared for.
