### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by seagull-destroyer** [Anuken/Mindustry#10175]
### Platforms

Android

### Build

146

### Issue

I recently downloaded the game again and whilst trying to complete Ground Zero tutorial, game crashes "because it has a bug". No settings changed. 
I am in the beta testing. My device is A32 5G.

### Steps to reproduce

Just stay on Mindustry, on level select or in a level and after a few minutes, game closes and gives error message.

### Save file

[(invalid).zip](https://github.com/user-attachments/files/16873542/invalid.zip)

### (Crash) logs

[crash log](https://github.com/user-attachments/files/16873563/crash.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
there is no crash so this could be an OOM error which is impossible to really fix

**Comment by camelStyleUser** [comment]
and not the crash

**Comment by Anuken** [comment]
There is no crash in that log.
