### ISSUE TITLE
Language translation problems

### ISSUE THREAD

**Issue by DaniloLavuri000000** [Anuken/Mindustry#10171]
### Platforms

Android

### Build

It's not a build.

### Issue

The Italian tutorial is in English. I tried on my phone and my brother's phone, both had the language setted on Italian and both gave the same problem.
I'm using the last Google Play Store's version.

### Steps to reproduce

Set the game language in Italian, then start the first time the campaign, the tutorial will be showed in English.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
the only time you can really file a report about translation is if theres an untranslatable string on BE(because of latest bugfixes), else translate it yourself

**Comment by broganeuquoixe** [comment]
Ciao Danilo, qui parla un membro della Comunità Italiana di Mindustry. Siamo a conoscenza del fatto che la traduzione italiana non è aggiornata ed è molto indietro. Stiamo lavorando a una nuova traduzione da un po' di tempo ormai e pensiamo di riuscire a pubblicarla entro il rilascio della prossima grande versione del gioco. Nel frattempo, puoi utilizzare questa mod per avere una traduzione "beta" non ancora revisionata, ma dovrebbe andare bene lo stesso.

[bundle-it.zip](https://github.com/user-attachments/files/16849808/bundle-it.zip)

Per favore, rivolgiti al nostro Discord per feedback o altre informazioni. Puoi trovarlo andando nel Discord ufficiale di Mindustry, nel canale #italiano, e unendoti al server.

Per importare la mod nel gioco vai in Mods > Import > Import from File e seleziona lo zip.
La traduzione è fatta per la versione Bleeding Edge del gioco quindi ci potrebbero essere alcune cose che risultano mal formattate, se il problema rende il gioco problematico consiglio di installare la versione bleeding edge da [qui](https://github.com/Anuken/MindustryBuilds/releases/latest)

Grazie

**Comment by Anuken** [comment]
If you have an issue with the translation, submit a PR to fix it. This issue tracker is for bugs only.

**Comment by DaniloLavuri000000** [comment]
Grazie mille
