### ISSUE TITLE
Strange input

### ISSUE THREAD

**Issue by ZeleniyKustik** [Anuken/Mindustry#10173]
### Platforms

Android

### Build

25244

### Issue

Typing on the phone in the code editor works strangely. Quite often you can't enter something the first time

https://github.com/user-attachments/assets/4153f969-acbb-494b-8ef4-192f9d6f1d41

### Steps to reproduce

Go to the code editor in the processor from your phone and try to change a few values like the name of a variable or a number in it

### Save file

[error.zip](https://github.com/user-attachments/files/16859899/error.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
Can you give more specs of the phone?

**Comment by ZeleniyKustik** [comment]
Model: AQM-LX1 / Huawei Y8p

**Comment by ZeleniyKustik** [comment]
If anything, everything is entered normally in the 146 version

**Comment by ZeleniyKustik** [comment]
The last version in which I don't have this bug is 25183. In 25185 the input is already weird

**Comment by 000x91** [comment]
Build 25185: 0b19379b8c982f752ae3e4a4f8d2ee6141716e28
Build 25183: f347dc4c84a44dff6f26aaf170d6e3f355eff22f

Commit 8e8b99d42195bf66c1396e4559c6c75e661e2271 shows a change on LCanvas.java. The change from Hit() might not be fully duplicating behavior

**Comment by ZeleniyKustik** [comment]
[Video with input in 25185.zip](https://github.com/user-attachments/files/16882222/Video.with.input.in.25185.zip)
[Video with input in 25183.zip](https://github.com/user-attachments/files/16882224/Video.with.input.in.25183.zip)
