### ISSUE TITLE
Type Casting bug crash

### ISSUE THREAD

**Issue by 70178637** [Anuken/Mindustry#10183]
### Platforms

Android

### Build

bleeding-edge 25252

### Issue

Map Info:Locale Bundles will cause the game to crash

### Steps to reproduce

1.MapEditor->Map Info->Locale Bundles
2.Add
A = "11"
B = 12
3.Play game
4.World Processor
add
localeprint "B"
printflush message1

https://github.com/user-attachments/assets/88a485d9-5346-4054-8bb0-1f9ac6c2c831

### (Crash) logs

[crash_1725612037393.txt](https://github.com/user-attachments/files/16905511/crash_1725612037393.txt)
[crash_1725612117512.txt](https://github.com/user-attachments/files/16905513/crash_1725612117512.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
I think numbers aren't supposed to be entered l

**Comment by Mythril382** [comment]
Those are bundles, not constant variables. They are used for easily translatable text. You aren't supposed to put numbers in bundles.

**Comment by way-zer** [comment]
May be the bundles always be  string, not need wrap with ' " '?

**Comment by camelStyleUser** [comment]
wait a minute

**Comment by camelStyleUser** [comment]
did they need "" before
