### ISSUE TITLE
environment sprites not rendered correctly when overriden with a texture pack

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry#10187]
### Platforms

Windows

### Build

25254

### Issue

the game doesnt pack correctly the atlas when using a texture pack that overrides the environment textures
every time you disable and re-enable the mod, a different result happens (see images)
### please note that this only happens when the textures are above a certain size
the larger the textures, the more intense are the bugs (at 2x the game resolution, it looks like everything works perfectly, but more and things start to break)
since some sprites are still drawn correctly, this is not a rendering issue, i believe this is due to the Atlas?

i also think this might be related to the amount of large sprites in the mod, maybe with just a few sprites you wouldnt run into the bug (hypothesis, i didnt test that)

![image](https://github.com/user-attachments/assets/2fb9a364-3068-4ad1-95f0-5e173094e9ee)
![image](https://github.com/user-attachments/assets/c1d4971e-043e-4335-bc20-e88275033833)
![image](https://github.com/user-attachments/assets/2b566fc0-c3bf-442b-97a3-1f0828b921c5)
![image](https://github.com/user-attachments/assets/076f3f95-b2eb-47ec-9821-6a3454cb6731)
![image](https://github.com/user-attachments/assets/1d58eed1-db04-4d6f-99ad-334ae9a2893c)
![image](https://github.com/user-attachments/assets/6f4da077-aa48-4a95-b8b9-b644369d1ec6)
![image](https://github.com/user-attachments/assets/a92f935a-eb06-4cb5-a716-d668ab7ca754)

### Steps to reproduce

just install the mod i linked and load any map (one that has multiple floor textures would obviously be better)

### Mods used

[hortiDefinition_x4.zip](https://github.com/user-attachments/files/16914117/hortiDefinition_x4.zip)

### (Crash) logs

no crash, it runs perfectly

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mahdoosh1** [comment]
i love glitches

**Comment by hortiSquash** [comment]
@Anuken the same issue is still present if i increase the environment resolution very slightly more than the test mod i provided

i dont understand why is that, because the blocks and units textures work perfectly, only the environment are bugged like this
well anyway, thanks for fixing the 4x 🥳

**Comment by Anuken** [comment]
All environment regions must be on the same texture for technical reasons. 4k is the maximum safe size. I will not be increasing it further.
