### ISSUE TITLE
Debug select not working properly 

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10180]
### Platforms

Android

### Build

146

### Issue

When using `PlanetDialog.debugSelect = true` it wont let you go to sectors in which you havent unlocked the research for, which defeats the purpose of the debug tool

### Steps to reproduce

Try go to any erekir sector except the starting one with a new erekir campaign with the debug on
(I tried to go immediately to siege)

### Mods used

Vanilla

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> When using PlanetDialog.debugSelect = true

I'll stop you right there. That's not something you can access without the console, and as such I provide no support for it. You're on your own.
