### ISSUE TITLE
map editor bug

### ISSUE THREAD

**Issue by motorhce** [Anuken/Mindustry#10195]
### Platforms

Windows

### Build

release 146

### Issue

when i am placing ores in map editor then going in playtest in the ores i placed there apears random ores that im not placed

### Steps to reproduce

1. place any ore like coal
2. go in edit in game place on coal drills
3. exit this editor
4. place copper near the coal
5. go in edit in game place on copper drills
6. exit this editor
7. go in playtest and see that there in coal or copper are apeard some random ores
in saved game on top drills shood be only copper
on down drills only coal I didnt placed any other things

### Mods used

it appears with and without mods

### Save file

[bug report save.zip](https://github.com/user-attachments/files/16931026/bug.report.save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
did you remove **all** ore generation

**Comment by camelStyleUser** [comment]
theres two places for oe generation

**Comment by motorhce** [comment]
> did you remove **all** ore generation

yes

**Comment by motorhce** [comment]
I find second generation
