### ISSUE TITLE
building, mining, etc. not working, can't progress at all.

### ISSUE THREAD

**Issue by PersonalPythonProgrammer** [Anuken/Mindustry#10202]
### Platforms

Windows

### Build

146

### Issue

clicking for anything to happen works in some circumstances:
- settings
- start screen
- selecting a building in the bottom right menu
- playing the next wave in the top left window

but does not work in some (very important) others:
- building anything ba clicking on the map
- mining the first copper in the first campaign step on serpulo

in conclusion: anything that is not the game map, is clickable and works perfectly, clicking on the game map never works, neither mining nor building.

I only tried this in the campaign on serpulo yet, i don't know what happens in other cases
Apparently this issue isn't new, but none of the comments on the other similar issues helped me fix it.

I tried already, and it did not help:
- importing a game where i already have some copper and mines built from my phone (not being able to mine was not a problem, but i still could not build anything new)
- removing the folder (downloaded from the mindustry website) and its .zip version, and all other files, and downloading from scratch
- asking a friend adept in java and github to download the .jar version from github for me (it has the same issue)
- clearing all save files, and restarting the campaign again
- restarting my PC

thanks for reading, please help
suggestion: if possible, maybe making mindustry be a true "app" and not just some folders and files might help, also installation and deinstalltion would be massively improved by that

### Steps to reproduce

just open the campaign, click on serpulo, and select the starting tile

### Mods used

none

### Save file

there is no data in any generated file, because one can't do anything to truly start the games progress

### (Crash) logs

nope

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
if you don't add any save file and/or logs we can't resolve it

**Comment by Matita008** [comment]
and also you didn't include what you have done before the issue appeared

**Comment by PersonalPythonProgrammer** [comment]
there are no save files to add, because this bug happens at the very start
of the campaign, and it disabled the ability to change the games state in
any way, except changing settings
what I did to cause the bug was:
download the game
open the game
start the campaign
select serpulo
select the only available tile on serpulo
try to mine the copper, and fail at that

~ Michael Valler

**Comment by Matita008** [comment]
> there are no save files to add, because this bug happens at the very start
> of the campaign, and it disabled the ability to change the games state in
> any way, except changing settings
> what I did to cause the bug was:
> download the game
> open the game
> start the campaign
> select serpulo
> select the only available tile on serpulo
> try to mine the copper, and fail at that
> 
> ~ Michael Valler

can you at least add the logs and a video

**Comment by Matita008** [comment]
bc saying I changed some config and started ground zero is saying nothing

**Comment by Matita008** [comment]
bc saying I changed some config and started ground zero is saying nothing

**Comment by Mavment** [comment]
Uuuuuuhhh sounds like you broke tutorial by some cursed way, like man there's no way to fix all bugs that accure when your mum smashes your face at keybord and you do some crazy combination that somehow breaks it, just reinstall game and complete it like normal human (and also anuke will most likely say something like "Couldn't reproduce" or "No save file")

**Comment by Mavment** [comment]
And also if reinstalling game not helping, and you have a save file of your schemes maps and whatever other things delete %appdata%\mindustry, it should help

**Comment by Matita008** [comment]
> Uuuuuuhhh sounds like you broke tutorial by some cursed way, like man there's no way to fix all bugs that accure when your mum smashes your face at keybord and you do some crazy combination that somehow breaks it, just reinstall game and complete it like normal human (and also anuke will most likely say something like "Couldn't reproduce" or "No save file")


the real thing is that without any detailed procedure or log or save file we can't reproduce the bug nor check what caused it

**Comment by PersonalPythonProgrammer** [comment]
> ### Platforms
> Windows
> 
> ### Build
> 146
> 
> ### Issue
> clicking for anything to happen works in some circumstances:
> 
> * settings
> * start screen
> * selecting a building in the bottom right menu
> * playing the next wave in the top left window
> 
> but does not work in some (very important) others:
> 
> * building anything ba clicking on the map
> * mining the first copper in the first campaign step on serpulo
> 
> in conclusion: anything that is not the game map, is clickable and works perfectly, clicking on the game map never works, neither mining nor building.
> 
> I only tried this in the campaign on serpulo yet, i don't know what happens in other cases Apparently this issue isn't new, but none of the comments on the other similar issues helped me fix it.
> 
> I tried already, and it did not help:
> 
> * importing a game where i already have some copper and mines built from my phone (not being able to mine was not a problem, but i still could not build anything new)
> * removing the folder (downloaded from the mindustry website) and its .zip version, and all other files, and downloading from scratch
> * asking a friend adept in java and github to download the .jar version from github for me (it has the same issue)
> * clearing all save files, and restarting the campaign again
> * restarting my PC
> 
> thanks for reading, please help suggestion: if possible, maybe making mindustry be a true "app" and not just some folders and files might help, also installation and deinstalltion would be massively improved by that
> 
> ### Steps to reproduce
> just open the campaign, click on serpulo, and select the starting tile
> 
> ### Mods used
> none
> 
> ### Save file
> there is no data in any generated file, because one can't do anything to truly start the games progress
> 
> ### (Crash) logs
> nope
> 
> ### Submission
> * [x]  I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
> * [x]  I have searched the closed and open issues to make sure that this problem has not already been reported.
> * [x]  I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

this bug has somehow just disappeared, please remove or resolve this issue, I don't know how to.
