### ISSUE TITLE
multiplayer campaign coop stopped working with only 1 other person

### ISSUE THREAD

**Issue by kohvik** [Anuken/Mindustry#10201]
### Platforms

Windows

### Build

STEAM 146

### Issue

hi!

me and my friend have been playing serpulo (about 40 hrs or so) using coop campaign. i enjoyed it so much that i wanted to show another friend and so i saved my data and reset to have the same unlocks as him.

unfortunately i didn't realize that the save was actually an empty zip (likely because i tried saving the data in program files directory lol), so me and the first friend decided to try playing a mod together instead. however, even after uninstalling the mod we can no longer join each others campaigns!

the weird thing is we can both join the 3rd friends campaign and he can join ours, but we just cant join each others (via steam)
we have tried reinstalling the game, clearing all data, clearing all mindustry related files, turning off steam cloud saving, and nothing seems to work. i have the last logs of trying to join his server and him trying to join mine if that is helpful:

### Steps to reproduce

played campaign on coop mode
clear game data on the person who hosted the campaign
install "exogenesis" mod
enter amy sector alone (researches something in mod tree i believe)
uninstall "exogenesis" mod
try playing coop with same user

### Mods used

exogenesis

### Save file

[save.zip](https://github.com/user-attachments/files/16988326/save.zip)

### LAST LOGS:

**FROM USER KOHVIK (ME)**

[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 3.8 GB
[I] [Mindustry] Version: 146
[I] Total time to load: 2751ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Received steam stats.
[I] Fetched 84 community servers.
[I] onLobbyInvite -1486947194 410711374 0
[I] onGameLobbyJoinRequested 1860000a75efc86 1100001187af54e
[I] onLobbyEnter -1486947194 Success
[I] Connect to owner 410711374: richhe015
[I] Connecting to server: steam:410711374
[I] Server: false
Client: true
Active: true
[I] Disconnected! 410711374: Timeout
[I] Disconnecting.

**FROM USER RICHHE015 (FRIEND)**

[I] Activating overlay dialog
[I] lobby -1486947194: 1104413203 caused 1104413203's change: Entered
[I] Connection request: 1104413203
[I] Am server, accepting request from 1104413203
[I] 1104413203 has disconnected: Timeout
[I] lobby -1486947194: 1104413203 caused 1104413203's change: Left
[I] Activating overlay dialog
[I] onLobbyInvite -1486759979 1104413203 0
[I] onGameLobbyJoinRequested 1860000a761d7d5 110000141d40213
[I] onLobbyEnter -1486759979 Success
[I] Connect to owner 1104413203: kohvik
[I] Connecting to server: steam:1104413203
[I] Server: false
Client: true
Active: true
[I] Disconnected! 1104413203: Timeout
[I] Disconnecting.
[I] Stored stats: OK

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
can the 3rd friend join your campaign?

**Comment by kohvik** [comment]
> can the 3rd friend join your campaign?

yes; the only cases that dont work is me joining 1st friend and 1st friend joining me

**Comment by kohvik** [comment]
after installing "scheme size" mod we were able to join each other

and then we uninstalled "scheme size" and the ability to join has remained

**Comment by camelStyleUser** [comment]
was the issue resolved or not

**Comment by kohvik** [comment]
resolved
