### ISSUE TITLE
Risso pathing broken on generated sector 37

### ISSUE THREAD

**Issue by deepspacerunner** [Anuken/Mindustry#10218]
### Platforms

Windows

### Build

146

### Issue

Rissos appear to think they can move through walls, even when there is a viable water path to my core.
Also I have deleted the mods from my save file, they were too big.

### Steps to reproduce

Go to sector 37 and spawn a wave. In the save file, there are some waves currently in progress that show this bug.

### Mods used

Mods active during initial incident:
Time Control
AutoDrill
I then disabled all mods and verified that the bug was still occurring.

### Save file

[mindustry-data-deepspacerunner_13-21-53-UTC_9-19-24-date.zip](https://github.com/user-attachments/files/17060930/mindustry-data-deepspacerunner_13-21-53-UTC_9-19-24-date.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by deepspacerunner** [comment]
> already reported

I do not have RTS AI enabled.

**Comment by Anuken** [comment]
Duplicate.
