### ISSUE TITLE
Bad mineral indication

### ISSUE THREAD

**Issue by Cuchidrilo** [Anuken/Mindustry#10219]
### Platforms

Android

### Build

146

### Issue

In Serpulo, the sector 64 has the sand icon in the planet menu, but the map doesn't have sand.

### Steps to reproduce

I enter for first time in sector 64, then I noticed really there's no sand to make things.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
numbered sectors maps are generated randomly while the resources are predefined iirc

**Comment by Matita008** [comment]
also please include save file

**Comment by Matita008** [comment]
[also it's duplicated](https://github.com/Anuken/Mindustry/issues/8042)

**Comment by Anuken** [comment]
Not relevant in BE.
