### ISSUE TITLE
RTS AI Commands ground units to unaccessible locations on the map

### ISSUE THREAD

**Issue by JianhuiDong9999** [Anuken/Mindustry#10217]
### Platforms

Mac

### Build

bleeding-edge build 25292

### Issue

RTS AI issues move/target commands ground units to attack inaccessible locations, such as bores within a space confined by terrain walls and islands surrounded by liquids capable of drowning said units.

https://github.com/user-attachments/assets/66bfba7d-dc2b-4518-a855-4cc9e4836d11

### Steps to reproduce

Make a map with ground-inaccessible tiles and turn on RTS AI. Put buildings that RTS AI attacks (bores, cliff crushers, turbine condensers, etc.) within the inaccessible terrain pocket(s) and spawn enemy ground units. Switch to enemy team to see where they are being commanded to attack. Some of them will be stuck trying to attack buildings within the pocket.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
Is your vid supposed to be 1 second long?

**Comment by jehosula** [comment]
https://github.com/user-attachments/assets/d2f0b827-43c9-4a41-bd17-20f848f3edbf
[bug showcase.zip](https://github.com/user-attachments/files/17054349/bug.showcase.zip)

the bug is easy to replicate

**Comment by Anuken** [comment]
As the template says, a save file is **required**. I can't reproduce this issue in a test map.
