### ISSUE TITLE
Router do not output items to input overflow gate (and only that)

### ISSUE THREAD

**Issue by ZeroRin** [Anuken/Mindustry#10215]
### Platforms

Windows

### Build

146

### Issue

When an item is input to a router from an overflow gate, the router will not output it back to that overflow gate.
This only apply to overflow gate and it will try to output back to underflow gate.

This is caused by the following line of code
https://github.com/Anuken/Mindustry/blame/cd7f2459b9968d00b74a4223c7b4f93ae0ed83a9/core/src/mindustry/world/blocks/distribution/Router.java#L121

Whichever behavior is intended i believe the two should behave the same way

### Steps to reproduce

minimum examples as shown in the picture
![image](https://github.com/user-attachments/assets/5243797a-a87b-4b15-821d-b2acdc466cec)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This is intentional and I will not be changing the behavior of core transport blocks.
