### ISSUE TITLE
Game doesn't launch if path to game contains accents

### ISSUE THREAD

**Issue by Slinky5880** [Anuken/Mindustry#10228]
### Platforms

Windows

### Build

v146

### Issue

When I try to launch the game and my C:/Users folder has an accent in it (ex. "é"), the game doesn't launch.
I have tried with another windows account which did not have an accent in its C:/Users Folder and it launched just fine.

### Steps to reproduce

1 make a new windows account, with an accent ( é,  é, û, ect) in its name.
2 install the game (I used itch.io)
3 launch the game
The game doesn't launch.

### Save file

---

### (Crash) logs

no crash reports where created

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
I don't think it's a mindustry bug

**Comment by Matita008** [comment]
[see here](https://github.com/Anuken/Mindustry/blob/master/core%2Fsrc%2Fmindustry%2Fcontent%2FSerpuloTechTree.java#L24)

**Comment by Matita008** [comment]
[see here](https://github.com/Anuken/Mindustry/blob/master/core%2Fsrc%2Fmindustry%2Fcontent%2FSerpuloTechTree.java#L24)

**Comment by Anuken** [comment]
I believe this is a [Java bug](https://bugs.openjdk.org/browse/JDK-8195129), and as such I can't fix it.

Any kind of logs would help, but you have not attached any.
