### ISSUE TITLE
Coreless ladbing

### ISSUE THREAD

**Issue by JuiseeMw** [Anuken/Mindustry#10233]
### Platforms

Android

### Build

Release build 146

### Issue

Landing on a numbered sector without a core in campaign.
The sector map exists and core unit exists, but the core of the player didnt spawn.
Because of that the unit cant build anything and get materials for that.
The wave timer is frozen at the 2:10 and if the wave starts , the enemy go to the point core belongs to , but since its not there they just stand on the point itself.
Sector cannot be captured or lost.
Core unit has 1 life and can shoot down the enemy, but vannot respawn.

The video is bigger than 10MB and unable to upload

### Steps to reproduce

My friend stumbled across this issue , and in how own words , he doesnt know at all how did that happen. 
He is a newbie.

### Mods used

None

### Save file

https://discord.com/channels/391020510269669376/391020510269669378/1288881962421063720

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
probably it has happened bc he has abbandoned the sector while he was in, in this case not a bug(since it does't remove shard units nor kick you off the campaign), else add how to replicate

**Comment by Matita008** [comment]
also the video you have linked is showing a sector with some mods or some console modification (infinite resource enabled (the '*' represent infinity))

**Comment by Matita008** [comment]
it's intended behavior (your friend has simply abbandoned the sector while he vas in and then when the planet map has shown up he has pressed back

**Comment by Matita008** [comment]
> ### Save file
> https://discord.com/channels/391020510269669376/391020510269669378/1288881962421063720
this is not a save file, it's just a video showing the presupponed bug
