### ISSUE TITLE
Derelict repair does not retain former block's contents

### ISSUE THREAD

**Issue by JianhuiDong9999** [Anuken/Mindustry#10230]
### Platforms

Mac

### Build

bleeding edge build 25311

### Issue

When I repair derelict blocks (from fallen enemy bases) they don't retain their inventory.

### Steps to reproduce

Capture an attack sector, find an intact derelict container/conveyor which is supposed to have items in them, repair it --> no items are left in the block.
<img width="782" alt="Screenshot 2024-09-25 at 7 30 07 PM" src="https://github.com/user-attachments/assets/92d3d185-d5ea-4e51-8662-d5de089be981">

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Mavment** [comment]
Bro is more money(resources) obsessed than Scrooge McDuck😭

**Comment by Anuken** [comment]
Intentional, block state is not preserved.
