### ISSUE TITLE
bullets can't have a hitbox size of above 1 tile against blocks

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#10237]
### Platforms

Linux

### Build

b146

### Issue

title, i've checked and this seems to be caused by HitboxComp `Math.min`-ning hitsize against blocks as a countermeasure for units getting stuck, except this also applies to bullets, it should probably only actually do that for units

### Steps to reproduce

1. make bullet with 80 hitsize
2. watch it work normally against units
3. observe it have to melee blocks to detonate

### Save file

wouldn't help

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Intentional, won't fix.
