### ISSUE TITLE
Huge delays when opening file browser. Arch Linux.

### ISSUE THREAD

**Issue by mrhoomanwastaken** [Anuken/Mindustry#10246]
### Platforms

Linux

### Build

146

### Issue

when trying to open the file browser (to import/export stuff) there is a 10+ sec delay before it opens.
During this time some odd things happen:
an app called "open" pops up on my toolbar.
a zenity instance is made (right away)
my computer becomes unbearably laggy despite still having plenty of resources.

### Steps to reproduce

have an arch installation with gnome as the desktop enviroment.
install Mindustry and try to import a map.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Cannot reproduce the issue with gnome, sounds like a system-specific bug. Mindustry does not do anything special beyond calling zenity and waiting for a result.

**Comment by mrhoomanwastaken** [comment]
all other apps that use zenity do not have this issue.
running zenity in the terminal does not have this issue.

are you on GNOME Shell 47.0?
it may be a bug with the aur package https://aur.archlinux.org/packages/mindustry-bin 
it does not enforce usage of the correct java version so that may be an issue.
im bad with java code but at first glance everything seems to be fine execpt the usage of "--confirm-overwrite" but that should not cause any issues.

**Comment by mrhoomanwastaken** [comment]
it happened with the .jar version as well.
