### ISSUE TITLE
Unable exploring the Interplanetary Accelerator

### ISSUE THREAD

**Issue by nepumuk-fs** [Anuken/Mindustry#10241]
### Platforms

Android

### Build

146

### Issue

I finished the named sectors on Serpulo (but lost one during my campaign). In the meantime I also conquered several numbered sectors and only Impact 0078 is at risk of being attacked. **After conquering the Planetary Terminal (I needed about four or five tries), I should be able exploring the Interplanetary Accelerator, but the icon/field for the expLoration isn't in my ”Forschung“ (exploration) screen.**

### Steps to reproduce

* start on Serpulo
* play about 4 sectors there
* start playing on Erekir
* play about 2 sectors there
* go on playing on Serpulo and Erekir, but both not to the end
* start playing in numbered sectors on Serpulo
* continue on Erekir and Serpulo
* lose some sectors and give up the first one on Serpulo
* play Ground zero again
* conquer every sector on Serpulo but the Nuclear production site (?) [the northest sector with a name not being Impact 0078]
* search the Interplanetary Accelerator in the exploring screen

### Mods used

none/default (if any)

### Save file

[mindustrybug.zip](https://github.com/user-attachments/files/17202867/mindustrybug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
not a bug, it's intended to be hidden since it's a WIP like another block in erekir

**Comment by nepumuk-fs** [comment]
What does ”WIP“ mean?
Do you mean ”not unlocked yet“ by ”hidden“?

**Comment by Matita008** [comment]
> What does ”WIP“ mean? ”Work in progress“?
> Do you mean ”not unlocked yet“ by ”hidden“?
> 
> Do I get you right that I can/am supposed to close this issue?


[yup, WIP is Work In Progress](https://github.com/Anuken/Mindustry/blob/master/core%2Fsrc%2Fmindustry%2Fcontent%2FSerpuloTechTree.java#L24)
no, I mean you aren't meant to unlock it nor use it,  only when in the editor is possible to place it but it won't work

yes, this issue can be closed

**Comment by nepumuk-fs** [comment]
As far as I understand it, the Interplanetary Accelerator is/was supposed to place a new base/kernel in an unconquered sector regardless the starting and aiming planet. What about using the Interplanetary Accelerator as an interplanetary Launch Pad (in the first place)? Would this need a lot of effort to implement? (Is this even the right place for this question?)

**Comment by camelStyleUser** [comment]
you tell me
![image](https://github.com/user-attachments/assets/1ba40357-811f-4bda-af7d-02f37be91520)

**Comment by nepumuk-fs** [comment]
While I started writing a feature request, I wondered whether this would be a [Teleporter](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md#a-few-things-you-shouldnt-suggest). On the other hand, a Launch Pad can be understood as one, can't it?

**Comment by Anuken** [comment]
This is the wrong place for suggestions, and launch pad functionality across planets does not make any sense.
