### ISSUE TITLE
Movement is slow to respond

### ISSUE THREAD

**Issue by Edwardl256** [Anuken/Mindustry#10242]
### Platforms

Linux

### Build

BE 25325

### Issue

Just downloaded the latest from Check Updates and sometimes on large maps the unit you control has problems moving. On one map as an Alpha, I can only move left or right, while it is near impossible to move up or down. Either I hold up for very long or I need to get going left before I get some up. On another as a Gamma I get some more control, but from a standstill it is much like the above but opposite. Up and down are ok while left and right struggle.

### Steps to reproduce

- Pick up [Enigma](https://cdn.discordapp.com/attachments/416719902641225732/1225091174738690158/Enigma.msav?ex=66fe02d1&is=66fcb151&hm=6e55e1b39174b154c3f550782293e96ac007485bfd4eee2bd4542f17fc0794cc&) and [ULTRA BOSS FIGHT](https://cdn.discordapp.com/attachments/416719902641225732/1289171731654905877/Boss_fight_map_mindustry.msav?ex=66fdc8fc&is=66fc777c&hm=bdc94bf1b96141b12718d521c44116fd819647428e3aaf8bd4db29397c5cefb0&).
- Open the game.
- Play -> Custom Game.
- Choose Enigma and play as Attack.
- Wait a few seconds after landing and try left. Then at a standstill try right. Then try an up or down. Feel a bit.
- Exit, then choose ULTRA and play as Attack.
- Wait a few seconds after landing and try up. Then at a standstill try down. Then try left or right. Feel a bit.

### Mods used

None.

### Save file

Happens at startup, but I'll give a save after moving around a bit.
[saves.zip](https://github.com/user-attachments/files/17226816/saves.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
mine Is working fine

**Comment by Edwardl256** [comment]
Update to 25328, still the same.
```java --version
java 21.0.4 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)
```
Ubuntu 12 bookworm

**Comment by Anuken** [comment]
1. I don't have this issue on either save, and the map links are dead.
2. These maps are far above the max editor size, and I provide no support for such hacked maps.
