### ISSUE TITLE
Target function doesn't work correctly

### ISSUE THREAD

**Issue by omarfrinjary** [Anuken/Mindustry#10254]
### Platforms

Windows

### Build

146 64bit

### Issue

I want to make the units that I have follow me and shoot where I shoot but in the code of the processor it has the target function that have the shoot command so when I put it to 1 isn't working

### Steps to reproduce

Everything that in check is checked correctly only the foo's client I didn't understand it . But even I don't think that is wrong.

### Mods used

No mod

### Save file

[Game_Data.zip](https://github.com/user-attachments/files/17277544/Game_Data.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
This isn't a bugs, it is skill issue.

> Everything that in check is checked correctly only the foo's client I didn't understand it . But even I don't think that is wrong.
Foo's client is custom build of Mindustry, any bugs from this client can't report to vanilla Mindustry.

**Comment by camelStyleUser** [comment]
man really said foo client and checked the check saying you do not use foo client
seems right(wrong) to me

**Comment by JasonP01** [comment]
> man really said foo client and checked the check saying you do not use foo client seems right(wrong) to me

Judging by how they were confused by it, it shows they dont use the client. How can you use something you have no knowledge about

**Comment by JasonP01** [comment]
Anyway this seems like a logic related problem not a bug in the game, they likely have bad logic and should ask for help in the logic channel instead

**Comment by omarfrinjary** [comment]
> Anyway this seems like a logic related problem not a bug in the game, they likely have bad logic and should ask for help in the logic channel instead I know some programming languages and I debugged it and even check it in sandbox to see the is shooting or not it isn't shooting so the problem is from the game

**Comment by omarfrinjary** [comment]
> This isn't a bugs, it is skill issue.
> 
> > Everything that in check is checked correctly only the foo's client I didn't understand it . But even I don't think that is wrong.
> 
> Foo's client is custom build of Mindustry, any bugs from this client can't report to vanilla Mindustry.

So it isn't from the foos client

**Comment by omarfrinjary** [comment]
> Anyway this seems like a logic related problem not a bug in the game, they likely have bad logic and should ask for help in the logic channel instead

But why you closed it this fast?

**Comment by omarfrinjary** [comment]
https://github.com/user-attachments/assets/e6aada40-8a3d-464e-b1b1-177bc2dcdc17

**Comment by mahdoosh1** [comment]
> 
> https://github.com/user-attachments/assets/e6aada40-8a3d-464e-b1b1-177bc2dcdc17
> 
> 

it is out of their reach.

**Comment by mahdoosh1** [comment]
also "End" at the end of the program does nothing, it is only useful if you want to jump to the top of the code from the middle of the code

**Comment by Matita008** [comment]
> > 
> > Video
> > 
> 
> it is out of their reach.

it will shoot anyway

**Comment by mahdoosh1** [comment]
> > > 
> > > Video
> > > 
> > 
> > it is out of their reach.
> 
> it will shoot anyway 
> 

as you can see it wont. if you dont beleive me, put
@x and @y to the respective coordinates.
now they will shout the processor.
