### ISSUE TITLE
Audio mutes when receiving call

### ISSUE THREAD

**Issue by Fischy-lab** [Anuken/Mindustry#10256]
### Platforms

iOS

### Build

Release build 146

### Issue

When receiving a call notification on device, the game audio mutes and does not recover until game is exited, closed from background apps, and relaunched.

Honestly not sure if this is something on the developers side or on apple/ios side, but figured I’d let you know just in case there is something you can do. It’s only annoying because the game audio and soundtrack are great!

### Steps to reproduce

Call came in, notification was displayed, phone rang, and call was dismissed by swiping away (some ‘scam likely’ call so not answered) all while still in game. Audio muted as soon as notification came. Tried:
Turning up the volume in case audio was just lowered
Waiting for call to go to voicemail and finish
Exiting app to home-screen then re-opening

Audio restored after exiting *and* closing app, then relaunching. 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Duplicate; this has already been reported.
