### ISSUE TITLE
Strange lines visual glitch with anything involving lightning-like effects (chainEmp, lightningBulletType, etc.)

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry#10253]
### Platforms

Windows

### Build

146

### Issue

![image](https://github.com/user-attachments/assets/738c8a54-910c-4a0e-92c1-cf2e74b3e1fe)
it was very hard to catch because these lines last mere fractions of a second but i managed to do it. This kind of visual glitch happens anytime there's a lot of chaining of lightning effects like arc's electric arcs, chainlightning, energy fields, you name it.

### Steps to reproduce

1: Open mindustry build 146 (i think it also happened in previous builds)
2: Get a unit with an electric field, a bunch of arcs, or a navannax and power blocks
3: Put a bunch of stuff in range of the unit electric field, in the middle of the arcs circle so they start shooting at it, or make the navannax shoot the power blocks repeatedly
4: Occasionally (this increases with the amount of lightning effects) a big line will pop up for what doesn't even seem like more than a tick.

### Mods used

Haznobrain/Erekir-liquefied
testing utilities

### Save file

[save.zip](https://github.com/user-attachments/files/17270699/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Haznobrain** [comment]
caught a few more throught space bar torture
![Capture d'écran 2024-10-06 220107](https://github.com/user-attachments/assets/97e64a22-cc47-47e9-9ab7-1a947c96f08f)
![Capture d'écran 2024-10-06 220252](https://github.com/user-attachments/assets/5ff1fb87-1fb6-463e-b956-61c724e3a8dd)
![Capture d'écran 2024-10-06 220448](https://github.com/user-attachments/assets/ac6b95c1-a3b2-4c37-aaf2-c83d7584aadc)
![Capture d'écran 2024-10-06 220543](https://github.com/user-attachments/assets/3bee5002-dece-4acf-9d98-e1f7b84befdf)

![Capture d'écran 2024-10-06 215002](https://github.com/user-attachments/assets/2740f094-0169-4182-b84d-600c9d96a813)

![Capture d'écran 2024-10-06 214642](https://github.com/user-attachments/assets/260487d0-74ab-49ed-9d91-62eb53de4dcb)

**Comment by mahdoosh1** [comment]
bro that is caused by mods

**Comment by mahdoosh1** [comment]
>  I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

are tou sure?

**Comment by Haznobrain** [comment]
> > I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.
> 
> are you sure?

i am sure as i think i've seen it happen sometimes in just plain vanilla (it's been multiple months since i've last played vanilla) and even if it is caused by mods erekir liquefied is json and shouldn't be causing that, and i don't think testing utils changes anything as to how the game's graphic engine does lightning.

**Comment by Haznobrain** [comment]
sorry if misunderstood i mean none of the mods i have could be causing such a bug

**Comment by mahdoosh1** [comment]
> sorry if misunderstood i mean none of the mods i have could be causing such a bug

no, i should be sorry.

**Comment by Haznobrain** [comment]
> > sorry if misunderstood i mean none of the mods i have could be causing such a bug
> 
> no, i should be sorry.

ok
