### ISSUE TITLE
Game keeps crashing every like 5 minutes or so

### ISSUE THREAD

**Issue by Mackinnon9000** [Anuken/Mindustry#10269]
### Platforms

Android

### Build

Release build 146

### Issue

The game just randomly got crashes 

### Steps to reproduce

Just happens every few minutes like randomly usually before something happens

### Mods used

N/A

### Save file

[game data bugged .zip](https://github.com/user-attachments/files/17368031/game.data.bugged.zip)

### (Crash) logs

[industry crash log](https://github.com/user-attachments/files/17368029/industry.crash.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
no crashes in the log but with only 256MB allocated to mindustry no wonder it can crash from an OOM or something

**Comment by Anuken** [comment]
The log doesn't contain any crashes, could be OOM from the old pathfinder.
