### ISSUE TITLE
Megas and polys despawning

### ISSUE THREAD

**Issue by Eliteyager343** [Anuken/Mindustry#10266]
### Platforms

Android

### Build

146

### Issue

It seems after awhile for some reason my megas and polys despawn on salt flats and I'm not sure why. 

### Steps to reproduce

After playing for a while I eventually go back to salt falts and they are gone. 

### Mods used

Time Control

### Save file

[data.zip](https://github.com/user-attachments/files/17356307/data.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
Time Control mod? If you change time delta to very large (super peed up), units (especial flying units) maybe despawn from the game, cuz they go outside map bound.

**Comment by Eliteyager343** [comment]
That could be the case 🤔, I usually only use x4 speed.
The mod Time Control by sk7725

________________________________

**Comment by Anuken** [comment]
> and have made sure the bug **is not caused by mods I have installed.**
