### ISSUE TITLE
go out on your own 

### ISSUE THREAD

**Issue by EXOBEAR** [Anuken/Mindustry#10262]
### Platforms

Android

### Build

146

### Issue

exit the application 

### Steps to reproduce

when playing 

### Mods used

No mod

### (Crash) logs

last log:
[I] [GL] Version: GLES 3.2.0 / Imagination Technologies / PowerVR Rogue GE8320
[I] [GL] Max texture size: 8192
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 34
[I] [RAM] Available: 192.0 MB
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
Success.
Fragment shader:
Success.
WARNING: 0:34: Calls to any function that may require a gradient calculation inside a conditional block may return undefined results
1 compilation warnings.

[W] Shader shaders/default.vert | shaders/fog.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/unitarmor.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/caustics.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/clouds.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
Success.
Fragment shader:
Success.

[I] [Mindustry] Version: 146
[I] Total time to load: 7168ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_bloom.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_threshold.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader bloomshaders/blurspace.vert | bloomshaders/alpha_gaussian.frag:
Vertex shader
Success.
Fragment shader:
Success.

[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 85 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Incomprehensible.

**Comment by EXOBEAR** [comment]
![Screenshot_20241013_182444_Device care](https://github.com/user-attachments/assets/041c5fac-3657-4487-9312-08eaf6b09e86) Note: why is this?

**Comment by mahdoosh1** [comment]
> 
> ![Screenshot_20241013_182444_Device care](https://github.com/user-attachments/assets/041c5fac-3657-4487-9312-08eaf6b09e86) Note: why is this? 

translate it for us

**Comment by EXOBEAR** [comment]
![Uploading Screenshot_20241013_213732_Gallery.jpg…]()
