### ISSUE TITLE
Mindustry arc.backend.sdl.SdlApplication$SdlError: wayland not available

### ISSUE THREAD

**Issue by MiX-4401** [Anuken/Mindustry#10278]
### Platforms

Linux

### Build

Version: release build 146

### Issue

Downloading the Mindustry linux build from itch.io and running it crashes with following log:

arc.backend.sdl.SdlApplication$SdlError: wayland not available
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:226)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:111)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

Seeing other issues regarding this, I found no post with a clean solution. However I believe I found a nice fix and would like to contribute. Apologies if this is the wrong place to post.

Instead of using the Linux I build I downloaded the Windows build. I used steam's "add-non steam game" and edited the launch properties w/ `gamescope -W 1920 -H 1080 --force-grab-cursor %command%`.

Ensure gamescope is installed on your machine. On arch-based distros use `sudo pacman -S gamescope` 

### Steps to reproduce

./Mindustry

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Linux x64 (amd64)
Java Version: 16
Runtime Available Memory: 8008mb
Cores: 16
<no mod init>

arc.backend.sdl.SdlApplication$SdlError: wayland not available
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:226)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:111)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
so use X11

**Comment by camelStyleUser** [comment]
or at least xwayland

**Comment by Anuken** [comment]
Duplicate issue. Wayland is currently not supported.
