### ISSUE TITLE
Unnamed/unmapped keys

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#1027]
**Platform**: Windows

**Build**: 99.12

**Issue**: The following keys work but display as "Unknown" when bound in control settings:
- Caps Lock
- [
- ]
- ' (apostrophe)
- Scroll Lock
- Pause/Break
- Menu key (next to R-Ctrl)
- Page Up
- Page Down
- Numpad .
- Numpad /
- Numpad *

Displays as "Unknown" and doesn't work:
- Print Screen

Cannot be detected when attempting to bind, and don't work when hardcoded as default:
- Mouse 4 (mouse back)
- Mouse 5 (mouse forward)

**Comment by Anuken** [comment]
These keys are simply not supported. If you really need them for some reason, submit a PR for the SDL scancode table [here](https://github.com/Anuken/Arc/blob/master/backends/backend-sdl/src/main/java/io/anuke/arc/backends/sdl/SdlScanmap.java#L7).
