### ISSUE TITLE
Build while repairing glitch 

### ISSUE THREAD

**Issue by JackAtak1103** [Anuken/Mindustry#10271]
### Platforms

Android

### Build

Build 146

### Issue

When you click copy, the repair symbol appears in the same place as the confirm build button. If you are actively repairing something, and then fly away or pause the game and then try to build the confirm build button won't show up. If you could click the repair button, then that confirms the build anyway. The glitch is just graphical, there either needs to be separate spot for the wrench and the chack mark, or the confirm build check mark needs to replace the repair symbol if you start building while already repairing.

### Steps to reproduce

If my explanation above was to complicated, you can ask me questions through GitHub. Thx!

### Mods used

No mods, just vanilla on Build 146 v7.

### Save file

This issue of has occured on multiple sectors named and numbered on Serpulo. Also occured on custom games.

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
#9535 duplicate

**Comment by Matita008** [comment]
it's fixed in the last BE build
