### ISSUE TITLE
unit keeps unbinding for unknown reason

### ISSUE THREAD

**Issue by swrvy71** [Anuken/Mindustry#10280]
### Platforms

Windows

### Build

25395

### Issue

the unit binded keeps unbinding in BE, the unit mostly just stays idle once arrived at the destination (tarX, tarY) and doesn't drop the payload, and gets unbinded.... 

according to someone (yruei): "@unit variable reset to null when linked block were modified (linking new block / unlinking blocks / in this case linked block gets taken by a unit)"  

the logic runs prefectly fine in mindustry pre-alpha 146 which is shown in the video
(for the video of it not working in BE the link is below)

https://github.com/user-attachments/assets/79151323-6e72-47c9-bfc3-3143e9a16f0c

+ same issue with another code on mega version 

the issue is the mega keeps unbinding and i don't know why. Once the payload is picked up, it doesn't move on to the next command which is to go to the destination, and then gets unbinded.   ( the very same code works at build 146 )

note:  both issue persisted in windows 11 and android 14 BE build 

---- same code was used ---------
https://github.com/user-attachments/assets/05980cd6-d266-4a59-b3f8-505efd5120e8
proof(in BE not working) 

https://github.com/user-attachments/assets/943812d5-737e-4ecf-9dd7-c5f8b3dee7a5
(proof in 146 working
------------------------------------

### Steps to reproduce

build a logic processor, put a vault under it (no space) and make sure the vault is linked as vault1
make this logic (either costum or campaign)
and bind a quad, or an oct. 
if unit doesnt bind instantly, try switching from binding any unit and switch back to quad once quad is spawned.

(quad and vault version)
code:

ubind @quad
set TarX 125
set TarY 78
sensor total vault1 @totalItems
sensor originY vault1 @y
sensor originX vault1 @x
jump 0 equal @unit null
jump 3 lessThanEq total 900
ucontrol move originX originY 0 0 0
ucontrol within originX originY 0.5 inside 0
jump 8 equal inside false
ucontrol payTake 0 0 0 0 0
sensor load @unit @payloadCount
jump 8 equal load false
ucontrol move TarX TarY 0 0 0
ucontrol within TarX TarY 0.25 insidee 0
jump 14 equal insidee false
ucontrol payDrop TarX TarY tt bb 0
ucontrol getBlock TarX TarY tt bb 0
sensor dropped @unit @payloadCount
jump 14 equal tt null
jump 14 equal bb null
sensor unloaded bb @totalItems
jump 25 equal unloaded 0
jump 18 greaterThanEq unloaded 0
ucontrol payTake 0 0 0 0 0
ucontrol move originX originY 0 0 0
ucontrol within originX originY 0.25 done 0
jump 26 equal done false
ucontrol payDrop 0 0 0 0 0
sensor unl @unit @payloadCount
jump 29 greaterThan unl 0
jump 1 always x false

to stumble to the same issue with the other code
(mega, container version):

build a container, and put this code inside a microprocessor (container should be beside the processor 'noSPACE') and should be linked as container1
spawn a mega and make sure it is binded, if it wont bind, set the unit-dead as 1, close the edit, and edit it again back to 0

set targetX 200
set targetY 200
set unitType @mega
jump 7 notEqual originX null
jump 4 strictEqual container1 null
sensor originX container1 @x
sensor originY container1 @y
op mul tflag @thisy @mapw
op add tflag @thisx tflag
sensor ded @unit @dead
jump 15 equal ded 0
ubind @mega
sensor uflag @unit @flag
jump 15 equal uflag 0
jump 11 notEqual uflag tflag
ucontrol flag tflag 0 0 0 0
ucontrol move originX originY 0 0 0
ucontrol within originX originY 0.5 await 0
jump 16 equal await 0
sensor ti container1 @totalItems
jump 16 lessThan ti 300
ucontrol move originX originY 0 0 0
ucontrol payTake 0 0 0 0 0
sensor pC @unit @payloadCount
jump 21 equal pC 0
ucontrol move targetX targetY 0 0 0
ucontrol within targetX targetY 0.25 await 0
jump 25 equal await 0
ucontrol payDrop 0 0 0 0 0
ucontrol getBlock targetX targetY t b 0
jump 25 strictEqual t null
jump 25 strictEqual b null
sensor ti b @totalItems
jump 32 greaterThan ti 0
ucontrol move targetX targetY 0 0 0
ucontrol within targetX targetY 0.5 await 0
jump 34 equal await 0
ucontrol payTake 0 0 0 0 0
sensor pC @unit @payloadCount
jump 34 equal pC 0
ucontrol move originX originY 0 0 0
ucontrol within originX originY 0.25 await 0
jump 40 equal await 0
ucontrol payDrop 0 0 0 0 0
jump 43 strictEqual container1 null

### Mods used

no mods active

### Save file

[saves.zip](https://github.com/user-attachments/files/17455000/saves.zip)

the bug happens in both costume game and campaign

the file where the bug occurs is the only custom game saved (5.msav)
(the mega version's code might not be included IN the save file)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
why you're sending the same code 4 times?

**Comment by Matita008** [comment]
why you're sending the same code 4 times?

**Comment by Matita008** [comment]
also you have miswritten some variables
(ex.: you wrote @Thisx instead of @thisx, it's case-sensitive

**Comment by Yrueii** [comment]
to summarize : 
`@unit` variable reset to null when linked block were modified (linking new block / unlinking blocks / in this case linked block gets taken by a unit)

**Comment by swrvy71** [comment]
> also you have miswritten some variables (ex.: you wrote `@Thisx` instead of `@thisx`, it's case-sensitive

but its working just fine in build 146 T^T, let me try it

**Comment by Mavment** [comment]
Well, first of all you have no within check so unit will take trash when travelling, second, check if unit doesn't get new command for more than 10 seconds, else its unbinds, third, check if no other processors force binds this exact unit and gives it command

**Comment by swrvy71** [comment]
> Well, first, check if unit doesn't get new command for more than 10 seconds, else its unbinds, second, check if no other processors force binds this exact unit and gives it command

it was unbinded,  i guess there weren't any new commands, and its the only processor in this custom game
![Screenshot 2024-10-21 142131](https://github.com/user-attachments/assets/e1d5d055-f8fc-4912-abe7-2bdec2b0cd5c)

same scenario in 146 but it worked fine, the mega was going back and forth.
