### ISSUE TITLE
Logic jump arrows become hardly visible in large codeblocks

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10282]
### Platforms

Android

### Build

25396

### Issue

When the jump arrow has to travel far it becomes really hard to see, if not invisible at some portions
![Screenshot_20241021_214805_Mindustry BE](https://github.com/user-attachments/assets/616113e3-a5fe-4d12-91a6-7a1ebd8fe159)

### Steps to reproduce

Make logic where it has to jump over 2 or more instructions
Eg:
```
jump 3 always
set 0 0
set 0 0
wait 0
```
^ The above logic begins to deteriorate the jump arrow and becomes worse the more it goes over

### Mods used

Vanilla

### Save file

Reproducable in all logic procs

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
In progress at https://github.com/Anuken/Mindustry/pull/10108

**Comment by JasonP01** [comment]
That hasnt had progress in a month, seems like nothing is happening commit-wise. This issue doesnt happen in 146 however

**Comment by JasonP01** [comment]
That pr author hasnt had any activity since August according to github's insights thingy
