### ISSUE TITLE
Too many enemies spawn at sector 114

### ISSUE THREAD

**Issue by ThinkingFace42** [Anuken/Mindustry#10285]
### Platforms

Android

### Build

release build 146

### Issue

![Screenshot_20241022_203315_io anuke mindustry](https://github.com/user-attachments/assets/ecd1288c-229c-4ce1-a7d6-f14c24f01370)
Besides, somehow an enemy Zenith survived a foreshadow hit too in one test

### Steps to reproduce

Just load game data enter sector 114 and call in 1st wave

### Mods used

None

### Save file

[gamedata.zip](https://github.com/user-attachments/files/17476627/gamedata.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
I think it's duplicated

**Comment by Anuken** [comment]
Duplicate.
