### ISSUE TITLE
Error exporting data 

### ISSUE THREAD

**Issue by Ironftt** [Anuken/Mindustry#10281]
### Platforms

Android

### Build

7-official-146

### Issue

Error logs and game data when exported, files always weigh 0 bytes. It used to work, and without doing anything, it stopped working forever.

### Steps to reproduce

Export data.

### Mods used

I don't think they have intervened, but they are:
-Time control
-Speed control
-Multiplayer pause

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
I can't do anything without error logs.
