### ISSUE TITLE
Non-working Server-release.jar program

### ISSUE THREAD

**Issue by Blakeplayz19372** [Anuken/Mindustry#10286]
### Screenshot
![MindustryError](https://github.com/user-attachments/assets/5a4f7f00-5874-49af-9f81-935ef4bd0836)
### Platforms

Windows

### Build

146

### Issue

When I run the server-release.jar file in File Explorer, it doesn't do anything, but when I run it in the command prompt it gives me a error on lines 16, 21, and some other lines. Is this because I am trying to run the wrong file to make my server, or is it something in the code?

### Steps to reproduce

I wanted to make my own public server, and when I looked it up, it said to run the server-release.jar file, but I got a error in the command prompt.

### Mods used

None

### Save file

None

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
java version?

**Comment by Blakeplayz19372** [comment]
It works in my OneDrive directory (the game), but it gives me a MethodNotFound error when I run the server.jar file. I put it in my OneDrive so I can play it at school

**Comment by Blakeplayz19372** [comment]
My java version that my admin said I could install is Java JRE 8u371 with JDK 21

**Comment by Blakeplayz19372** [comment]
Solved: I tried downgrading the server-release.jar file to build 145.1 and it worked. Perhaps one of the coders made a mistake?

**Comment by camelStyleUser** [comment]
did you install jre 16 or higher

**Comment by camelStyleUser** [comment]
the game is made in jdk 16-17
babel should downgrade it but sometimes it doesnt work

**Comment by Blakeplayz19372** [comment]
I could try running it on a non-school computer
My school computer is admin managed, and I don't have authorization to upgrade my version of java

**Comment by Blakeplayz19372** [comment]
Ok

**Comment by Blakeplayz19372** [comment]
I'll try hosting it off of my Raspberry Pi instead of my school computer, Raspberry Pis are also good for hosting free VPNs
