### ISSUE TITLE
Stormtrooper aim implementation: Cannot hit immobile 1x1 target

### ISSUE THREAD

**Issue by AtomicStryker** [Anuken/Mindustry#1028]
**Platform**: Windows

**Build**: 99.12

**Issue**: I suspect there is a problem around https://github.com/Anuken/Mindustry/blob/4c0607aba8fb94725b5a7a4216fa99ae57c0219f/core/src/io/anuke/mindustry/entities/type/base/GroundUnit.java#L169 Groundunit.behaviour which governs targeting. Without knowing much about your implementation, it looks like "firing when within a certain targeting angle" and "predict enemy movement, even if it is not moving" combined cause the problem.

**Steps to reproduce**: Have an enemy Dagger try to kill a 1x1 target that is mid-to-max range orthogonal to its movement direction. Its aim will always be off by about one tile. See screenshot:

![stormtrooper](https://user-images.githubusercontent.com/1858566/68546074-4f33d080-03d3-11ea-96d7-f6f7f704eebf.PNG)

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/68546275-93f34380-03a2-11ea-8d5c-5414926c5f39.png)

![image](https://user-images.githubusercontent.com/10100000/68546217-47a80380-03a2-11ea-8935-288d8a0e9c38.png)

No problems here, across varying distances and different unit movement formations.
I've "fixed" this problem so many times now that I don't really care about it anymore. 

What you're probably experiencing is some side effect of the bullets inheriting unit velocity and delta time calculations not taking that into exact consideration. It may be fixed if I decide to make bullets stop inheriting velocity, but until that time comes this won't be fixed for your edge case.

**Comment by AtomicStryker** [comment]
Out of interest i debug stepped through that targeting algorithm and found immobile targets have a nonzero target velocity. That does not seem correct, unless it means something different in your codebase.

Forcing that to zero for immobile entities did not fix the issue, however.

Personally i wouldn't call something that happens in every map in which you send out drones an edge case but ... well if you fixed it so many times to be sick of it :) certainly know that feeling

**Comment by AtomicStryker** [comment]
To clarify: I noticed the issue because on the Salt Flats level my entire Dagger army ran past Hail turrets taking pot shots multiple times, and all of them failed to hit them.

**Comment by AtomicStryker** [comment]
Bwahahaa i found the crux of the issue: It's related to FPS. If i set the frame limit to a cinematic 30, the same issue happens ... IN THE OPPSITE direction.

So i gues your targeting works perfectly ... at exactly 60 FPS.
