### ISSUE TITLE
Crash when keyboard is plugged/unplugged

### ISSUE THREAD

**Issue by alexytomi** [Anuken/Mindustry#10284]
### Platforms

Android

### Build

Version 7-official-146

### Issue

Crashes when I plug/unplug a keyboard. Does not happen with a mouse.

https://github.com/user-attachments/assets/4dba5d3a-5892-4921-be4e-4b3a24c32383

### Steps to reproduce

Plug in a keyboard using a usb hub

### Save file

[(invalid).zip](https://github.com/user-attachments/files/17474761/invalid.zip)

### (Crash) logs

[(invalid).txt](https://github.com/user-attachments/files/17474783/invalid.txt)

logcat I got from adb since this didn't generate a crashlog from when I read it.
[mindustrylogcat.txt](https://github.com/user-attachments/files/17475067/mindustrylogcat.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
No crash log?

**Comment by Matita008** [comment]
from what I can see in the txt file you uploaded there are many logs, and in each one you're using some mods.
try disabling them

**Comment by alexytomi** [comment]
> from what I can see in the txt file you uploaded there are many logs, and in each one you're using some mods. try disabling them

They're all disabled

**Comment by alexytomi** [comment]
Since the log seems to contain nothing afaik, here's a logcat I got. This one is for unplugging.
[Uploading mindustrylogcat.txt…]()

**Comment by Matita008** [comment]
have you tried using the BE version?

**Comment by alexytomi** [comment]
> have you tried using the BE version?

I have no clue w

> have you tried using the BE version?

I've no clue what that is

**Comment by alexytomi** [comment]
> have you tried using the BE version?

Tried it. Same result.

**Comment by SITUVNgcd** [comment]
Shit! I saw my mod in these crash. Last crash from my mod.

**Comment by alexytomi** [comment]
> Shit! I saw my mod in these crashes. Last crash from my mod.

Don't worry, I was messing around with mods that add sandbox features for testing. It was a mod incompatibility.

The bug does not generate a proper crash log hence the logcat I sent for an actually helpful something

**Comment by Anuken** [comment]
The logcat doesn't actually appear to contain any crash aside from the mod-related one, and I don't really provide support for keyboards on Android. Mouse/keyboard input has historically been very buggy on various devices, and it is not a feature I am interested in maintaining.

**Comment by alexytomi** [comment]
> The logcat doesn't actually appear to contain any crash aside from the mod-related one, and I don't really provide support for keyboards on Android. Mouse/keyboard input has historically been very buggy on various devices, and it is not a feature I am interested in maintaining.

The thing is, I wasn't running mods during the logcat. Regardless thanks for the response, I won't push further.
