### ISSUE TITLE
Game crashed on launch

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10288]
### Platforms

Android

### Build

146

### Issue

Game crashed on launch

Previous instance (closed completely by removing from recent apps), was in mod browser, closed app, re-opened to crash

### Steps to reproduce

Honestly no idea

### Mods used

In crash report

### (Crash) logs

[crash_1729723274523.txt](https://github.com/user-attachments/files/17499312/crash_1729723274523.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
I couldnt recreate this even if i tried

**Comment by Anuken** [comment]
This is caused by mods.

**Comment by JasonP01** [comment]
Crash log didnt tell me it was mods so i didnt know :/
