### ISSUE TITLE
Bug with container 

### ISSUE THREAD

**Issue by GodWarrior22** [Anuken/Mindustry#10291]
### Platforms

Windows

### Build

bleeding-edge build 25402

### Issue

I have a plastic production of plastic on painted mountains, but all the plastic is unloaded into a container (not connected to the core), but when I am not in the sector, this plastic is counted into the core. 
P.S sorry for my english, I use translator.

### Steps to reproduce

I built a plastic production facility and started unloading it into a container without sending it to the core. however, when I switched to another sector and returned back after a while, I had 1.2 thousand plastic in my core

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Sector simulation doesn't actually update the map when you are away.
