### ISSUE TITLE
Erekir map Crossroads pathfinding gets stuck

### ISSUE THREAD

**Issue by MissPotato** [Anuken/Mindustry#10293]
### Platforms

Linux

### Build

Steam build 146

### Issue

I had noticed that the AI had stopped sending Vanquishers, I just presumed my turrets were killing them so quick I wasn't noticing, however upon moving out to kill their final citadel I figured out where they all were. 
![Screenshot from 2024-10-26 15-06-06](https://github.com/user-attachments/assets/16fe413b-1bab-4ed5-8264-f59a1c8ccb5a)

### Steps to reproduce

Play on Crossroads, have AI collide into each other unable to squeeze through the tight gap.

### Mods used

The only mod I have is Time Control, and I only use it when a sector is clear.

### Save file

There seems to be a bug with exporting saves, I believe it is a bug in Nemo file browser and not a bug in Mindustry but I'll write it here in case: clicking export opens up the nemo window and typing anything into the file name completly freezes the export. Instead I have manually zipped up my saves folder and attached it, sorry. 
[saves.zip](https://github.com/user-attachments/files/17531705/saves.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
There have been major changes to pathfinding since v146, so this is likely irrelevant now.
