### ISSUE TITLE
Liquid throughput rate and overflow/underflow/router throughput being frames based and not tick based.

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry#10301]
### Platforms

Windows

### Build

146

### Issue

When using pipes and logistics block throughput (non-conveyors) is framerate dependent and not tick rate dependent. This is most noticeable when using the time control mod to speed up the game, or when moving large amounts of liquids or merging conveyors with routers.

### Steps to reproduce

1: Launch mindustry build 146
2: install time control
3: put down a bunch of pumps on oil to fuel plastanium factories (exemple)
4: enable vsync
5: At higher speed mutlipliers, the same amount of liquid goes through pipes and routers and stuff start slowing down, not following the higher speed.
6: disable vsync
7: If your framerate is higher without vsync, more liquid will go through pipes and routers will be fixed.

### Mods used

MEEPofFaith/bottom-left-ui
MEEPofFaith/testing-utilities-java
sk7725/time-control

### Save file

[save.zip](https://github.com/user-attachments/files/17561296/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
ticks **are** frames

**Comment by camelStyleUser** [comment]
time control multiplies Time.delta

**Comment by Anuken** [comment]
This is known and not fixable with the current liquid system.

**Comment by camelStyleUser** [comment]
> > ticks **are** frames
> 
> as a modder i can tell you, they aren't really.There's 60 ticks in a second, however it's a constant rate and is not related to framerate, just like in minecraft. If it was, turrets would shoot faster the higher framerate you have.

as a modder and contributor i can tell you turrets use deltatime so they dont shoot faster

**Comment by camelStyleUser** [comment]
and TPS is just server FPS

**Comment by mahdoosh1** [comment]
> and TPS is just server FPS

Yes I've noticee it when I hosted and played with my friends.
