### ISSUE TITLE
direction reversal using frags

### ISSUE THREAD

**Issue by Angel0doom** [Anuken/Mindustry#10303]
### Platforms

Android

### Build

146 and most likely all others

### Issue

when using drag on a reverse firing bullet then fragging of that bullet in the opposite direction with minimal speed and a negative drag and possibly more situations sometimes it goes the complete opposite direction. and this chance seems to scale with how low the fps

### Steps to reproduce

weapons: [
  {
    reload: 100
    shootCone: 360
    mirror: true
    x: 14
    y: 9
    bullet: {
      keepVelocity: false
      drag: 0.09
      lifetime: 60
      speed: -8.3
      width: 8
      height: 8
      pierce: true
      pierceBuilding: true
      fragBullets: 1
      fragRandomSpread: 0
      fragVelocityMin: 1
      fragVelocityMax: 1
      despawnEffect: none
      hitEffect: none
      fragAngle: 180
      fragBullet: {
        height: 8
        width: 8
        keepVelocity: false
        speed: 0.1
        drag: -0.09
        lifetime: 130
      }
    }
  }
]

use any weapon like this and mess with the max FPS while shooting, pretty simple

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Negative speed is not supported.
