### ISSUE TITLE
Oct movement

### ISSUE THREAD

**Issue by jacobe0100** [Anuken/Mindustry#10309]
### Platforms

Windows

### Build

25417 Bleeding Edge

### Issue

Oct could not turn

### Steps to reproduce

 I filled a oct with 2 toxopids

### Save file

[New folder (3).zip](https://github.com/user-attachments/files/17606358/New.folder.3.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
It turns fine for me.
