### ISSUE TITLE
Displays can draw to non linked processors 

### ISSUE THREAD

**Issue by NoSanityHere** [Anuken/Mindustry#10300]
### Platforms

Android

### Build

146

### Issue

Control needs the block to be linked if not privelidged, wheras draw flush doesn't.
Fixed by #10299

### Steps to reproduce

Use the code
```
jump 3 notEqual player null
radar player ally flying distance @this 1 player
jump 1 equal player null
jump 6 notEqual @unit null
ubind @poly
jump 3 equal @unit null
sensor x player @x
sensor y player @y
ucontrol approach x y 3 0 0
ucontrol getBlock x y type building 0
jump 13 equal type @logic-display
jump 13 equal type @large-logic-display
end
set display building
sensor type display @type
set displayWidth 176
jump 18 equal type @large-logic-display
set displayWidth 80
op idiv pos displayWidth 2
draw image pos pos @router displayWidth 0 0
drawflush display
```
This makes a poly follow the player and get displays at the coords of the player.
To use, fly over a display, and a router will get drawn to it.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
This seems more like a feature than a bug and affects nothing, its literally just a nice thing to have and if it was a bug it should be a feature

Many many logic users would not be happy if this got changed :(

**Comment by NoSanityHere** [comment]
Should control be changed to allow longer range then

**Comment by JasonP01** [comment]
Plus it only works for drawing on displays and for cells, stuff that is unneeded to fix as it only provides qol stuff, its not like it can be used to grief like regular control can
