### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by zesty51** [Anuken/Mindustry#10317]
### Platforms

Windows

### Build

I can't get to the main menu

### Issue

Game instant crashes upon launching. I bought it through steam, but I also downloaded it off the website and both verisons crash. For the steam verison i tried resintalling multiple times and on different drives. I also verifed files multiples also on different drives. failed on current drivers and drivers rolled back to april 2024 (was trying that for another game anways) 
![Screenshot_17](https://github.com/user-attachments/assets/d79ecd06-9af3-46f5-8d6e-b7e1444de218)

### Steps to reproduce

launch game in anyway even administrator

### Mods used

none

### (Crash) logs

[crash-report-11_09_2024_16_09_08.txt](https://github.com/user-attachments/files/17689654/crash-report-11_09_2024_16_09_08.txt)
[crash-report-11_09_2024_16_29_06.txt](https://github.com/user-attachments/files/17689655/crash-report-11_09_2024_16_29_06.txt)
[crash-report-11_09_2024_16_39_33.txt](https://github.com/user-attachments/files/17689656/crash-report-11_09_2024_16_39_33.txt)
[crash-report-11_09_2024_16_41_54.txt](https://github.com/user-attachments/files/17689657/crash-report-11_09_2024_16_41_54.txt)
[crash-report-11_09_2024_16_42_10.txt](https://github.com/user-attachments/files/17689658/crash-report-11_09_2024_16_42_10.txt)
[crash-report-11_09_2024_16_45_42.txt](https://github.com/user-attachments/files/17689659/crash-report-11_09_2024_16_45_42.txt)
[crash-report-11_09_2024_17_09_31.txt](https://github.com/user-attachments/files/17689660/crash-report-11_09_2024_17_09_31.txt)
[crash-report-11_09_2024_17_10_20.txt](https://github.com/user-attachments/files/17689661/crash-report-11_09_2024_17_10_20.txt)
[crash-report-11_09_2024_17_11_18.txt](https://github.com/user-attachments/files/17689662/crash-report-11_09_2024_17_11_18.txt)
[crash-report-11_09_2024_17_11_40.txt](https://github.com/user-attachments/files/17689663/crash-report-11_09_2024_17_11_40.txt)
[crash-report-11_09_2024_17_18_05.txt](https://github.com/user-attachments/files/17689664/crash-report-11_09_2024_17_18_05.txt)
[crash-report-11_09_2024_17_19_02.txt](https://github.com/user-attachments/files/17689665/crash-report-11_09_2024_17_19_02.txt)
[crash-report-11_09_2024_16_05_28.txt](https://github.com/user-attachments/files/17689666/crash-report-11_09_2024_16_05_28.txt)
[crash-report-11_09_2024_16_07_18.txt](https://github.com/user-attachments/files/17689667/crash-report-11_09_2024_16_07_18.txt)
[crash-report-11_09_2024_16_07_56.txt](https://github.com/user-attachments/files/17689668/crash-report-11_09_2024_16_07_56.txt)
[crash-report-11_09_2024_16_08_08.txt](https://github.com/user-attachments/files/17689669/crash-report-11_09_2024_16_08_08.txt)
[crash-report-11_09_2024_16_08_34.txt](https://github.com/user-attachments/files/17689670/crash-report-11_09_2024_16_08_34.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Your graphics drivers are broken and cannot initialize OpenGL properly; I can't fix this.

**Comment by zesty51** [comment]
Can you suggest a way to fix this? Or direct me to resources?

**Comment by Anuken** [comment]
No, this is my first time seeing that particular error message, and I don't use Windows myself. I don't have any specific advice.

**Comment by zesty51** [comment]
All good, I’ve got a couple ideas now that Ik for sure it’s related to
OpenGL. I just wanted to see if you had any extra advice! Thank you very
much. Should I inform you if I fix it?

**Comment by Anuken** [comment]
It might help if someone else has the same issue in the future, but as mentioned above, I have never seen that exact error despite the game being around for years, so that may be unlikely.

**Comment by zesty51** [comment]
Lol an unfortunate time to be unique. I’ll let you know how it goes.

**Comment by SITUVNgcd** [comment]
AMD issue, maybe.
https://community.amd.com/t5/pc-drivers-software/some-opengl-games-crash-on-before-startup-on-23-7-2-and-higher/m-p/680365/highlight/true
