### ISSUE TITLE
liquid junctions not working properly

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#1031]
**Platform**: Windows 10 1903 x64

**Build**: steam build 99.12

**Issue**: Liquid junctions do not always pass fluids the way they're supposed to.  They pass water N/S but not cryofluid E/W.

**Steps to reproduce**: Create a cryofluid setup as pictured here:

![image](https://user-images.githubusercontent.com/13720625/68550186-2b1dc280-03c6-11ea-89ce-ace97155987e.png)

**Comment by willis936** [comment]
Apparently the issue is only with cascaded fluid junctions.

![image](https://user-images.githubusercontent.com/13720625/68550219-746e1200-03c6-11ea-84dc-68dcbb43a5af.png)

**Comment by Anuken** [comment]
Already fixed.
