### ISSUE TITLE
Survival Server loads pvp map.

### ISSUE THREAD

**Issue by Peter-Crawley** [Anuken/Mindustry#1032]
**Platform**: *Server*

**Build**: *99*

**Issue**: *When hosting a survival server, the server occasionally becomes a pvp one*

**Steps to reproduce**: *Start a survival server, skip a few rounds, a map will load in pvp mode*

**Comment by Anuken** [comment]
The server doesn't "know" which maps are PvP or not, and doesn't filter out any maps based on it. I am aware of this, but it's not a bug. Use custom maps until a better auto-shuffle system is implemented.
