### ISSUE TITLE
Save isn't loading on latest build

### ISSUE THREAD

**Issue by NovaGithubber** [Anuken/Mindustry#10324]
### Platforms

Android

### Build

25429

### Issue

I made save in v146, and tried to migrate to BE. I tried to import the save to BE, but it says it couldn't load the save because of a mod named CMD Scheme Pack, which i don't even have downloaded. 

### Steps to reproduce

I also tried loading my save in build 25421, to no avail. I was able to load it up last time, but not now.

### Mods used

CMD Scheme Pack by foxitus (or that's what the error says)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
You haven't attached the save.

**Comment by NovaGithubber** [comment]
It says the save is too big, i'm sorry (70mb but the limit is 25mb)
