### ISSUE TITLE
No enemies on an attack sector (36)

### ISSUE THREAD

**Issue by Aron-Buler** [Anuken/Mindustry#10325]
### Platforms

Android

### Build

Release build 146

### Issue

I was in sector 36 on serpulo in release build 146 and the enemy spawned zero enemies until wave 60 where it spawned a guardian and a flare. Sadly I accidentally beat the sector before I could see what happened later.

### Steps to reproduce

I didnt do anything but place and build schematics and build units.

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Waves have changed since build 146.
