### ISSUE TITLE
Shields flashing and changing styles.

### ISSUE THREAD

**Issue by Popo9898** [Anuken/Mindustry#10320]
### Platforms

Android

### Build

7-official-146

### Issue

https://github.com/user-attachments/assets/8a0c4ae7-02ba-4f9c-8c0d-9046a3941b13

Force projector Shields are flashing and changing styles whenever the building ray comes into action.
Animated Shields are on.

### Steps to reproduce

I just used the force projector for the first time, it kept flashing when I moved the player ship, whenever I try to build something they change styles

### Mods used

None

### Save file

[mindustrysave4.zip](https://github.com/user-attachments/files/17700798/mindustrysave4.zip)

### (Crash) logs

[crash1.zip](https://github.com/user-attachments/files/17700833/crash1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
The state when you are building is what its supposed to be like...

**Comment by Anuken** [comment]
Cannot reproduce the issue.
