### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by salt36** [Anuken/Mindustry#10321]
### Platforms

Android

### Build

146

### Issue

when I open the game it just crashes, the game closes itself every time, this happens in the first 2 minutes, it happens randomly and it doesn't matter if you are in the campaign or the main menu.

### Steps to reproduce

open the game
try to do anything

### Mods used

i dont use mods

### Save file

[mindustrusty 1.zip](https://github.com/user-attachments/files/17708567/mindustrusty.1.zip)

### (Crash) logs

[mindustry crash logs (1).zip](https://github.com/user-attachments/files/17708568/mindustry.crash.logs.1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
last log:
[I] [GL] Version: GLES 3.2.0 / ARM / Mali-G57
[I] [GL] Max texture size: 16383
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 33
[I] [RAM] Available: 192.0 MB
[I] [Mindustry] Version: 146
[I] Total time to load: 4129ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 85 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

**Comment by Anuken** [comment]
There is no crash in the logs; I cannot help you.
