### ISSUE TITLE
Extensive CPU usage (in menu, tutorial, campaign beginning)

### ISSUE THREAD

**Issue by marekvlasak** [Anuken/Mindustry#10334]
### Platforms

Linux

### Build

146

## Computer 
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: B650 AORUS ELITE AX 
Kernel: 6.1.0-27-amd64 
Shell: bash 5.2.15 
Resolution: 1920x1080, 1080x1920 
DE: GNOME 43.9 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 7950X3D (32) @ 4.200GHz 
GPU: AMD ATI 11:00.0 Raphael 
GPU: NVIDIA GeForce RTX 3060 
Memory: 4478MiB / 127912MiB 

## Issue Description

Immediately after launching Mindustry a "java" process emerges with whopping 20% CPU usage, after getting into campaign map CPU usage increases up to 33%, no mods, few built drills and belts. After killing "java" or quiting Mindustry CPU usage is back to normal. I also noticed that it is using 10 times more memory than displayed in game. No extensive network usage was found. 33% CPU usage is more like 66% usage considering SMT.

## comment

As I remember running Mindustry years back on my low end android phone I don't understand why it should take so many resources, therefore I opened this as issue. Why noone has the same issue (excluding old setups or extremely loaded maps or mods)? From what I know snap should act as a sandbox and I don't have to worry about security, right? Should I buy it on Steam, so I don't have to pay it double in electricity for crypto? Should I run it on machine with less resources? Will it lag at 100% CPU usage or will it use again 2/3 cores and run smoothly? I will try next time.  

## Screenshots 

![javaProcess](https://github.com/user-attachments/assets/f2c3a5ee-d1bc-498f-a8ab-270953be579b)

![launch](https://github.com/user-attachments/assets/3713b65f-e4a1-4ec6-b815-8a6e35e3baeb)

![moreCPUusageInMap](https://github.com/user-attachments/assets/e64d8015-c162-456c-b03b-3231c4932716)

## terminal output

[out.txt](https://github.com/user-attachments/files/17793957/out.txt)

### Steps to reproduce

1. install mindustry
2. run mindustry
3. CPU goes nuts

### Mods used

no mods

### Save file

[data_for_bug_report.zip](https://github.com/user-attachments/files/17793556/data_for_bug_report.zip)

### (Crash) logs

[crash_logs_123.txt](https://github.com/user-attachments/files/17793563/crash_logs_123.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> I also noticed that it is using 10 times more memory than displayed in game. 

The displayed memory usage is the occupied Java heap, *not* total memory usage of the process, or native memory. Java reserves significant space even if it is not currently being used; that's how the GC works.

> whopping 20% CPU usage

I do not consider a game using 20% of your CPU to be remotely significant, and I have no interest in "fixing" this. Unless you can consistently reproduce the game maxing out CPU cores in an empty map (or some other anomalous scenario), this is not a bug.
