### ISSUE TITLE
Game is crashed more easily by large mods

### ISSUE THREAD

**Issue by Jssekekekrr** [Anuken/Mindustry#10340]
### Platforms

Android

### Build

146

### Issue

Large mods (especially ExoGenesis, but also New Horizon) crash the game within seconds or immediately. I have a Google Octopus Chromebook at my home, prior to the update it ran ExoGenesis without issue or lag, but now it insta-crashes. New Horizon does load but going to the campaign or loading ANY map crashes the game

Please Anuken, please find a way to fix this, please.

### Steps to reproduce

Just add New Horizon, or any large mod. This may be inconsistent between devices, like how my phone can't load ExoGenesis period, even in before 146.

### Save file

All of them

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
the fix is getting a device with more ram that has a higher max heap size

**Comment by 50275** [comment]
You are missing:
Specific set of mods that cause the issue
Save File
(Crash) logs

your post is meaningless

**Comment by alexytomi** [comment]
I suspect this may help if the crashes truly seem random on startup

https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#how-to-disable-the-phantom-processes-killing
