### ISSUE TITLE
Dpad and joystick? Don't know them

### ISSUE THREAD

**Issue by Zahar2loshara** [Anuken/Mindustry#10349]
### Platforms

Android

### Build

Tried on 146 release and 7-bleeding-edge-25445 BE

### Issue

The game doesn't see the movement of joystick at all with dpad, and even if i want to rebind them, i can't, because it doesn't see it (the clicks on joystick sees (Left Thumb / Centre))

### Steps to reproduce

1. Have a controller (i have a GameSir-Nova Lite T7n)
2. Go to Settings/Controls/Movement on 'X or Y'
3. Try to rebind them...
4. Congrats, the joystick movement and dpad is ignored.

### Mods used

They dont necessary need because it doesn't work without the mods but on release save i use a lot soooo...

### Save file

The BE save [here](https://www.mediafire.com/file/76k0tnu2t0tpoa5/save.zip/file)
And the release save [here](https://www.mediafire.com/file/ebfo9up9xnx9rut/save+2.zip/file) (the files are bigger than allowed 25 mb)

### (Crash) logs

No need

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
> have a controller

you know mindustry doesnt have controller support, right?

**Comment by JasonP01** [comment]
This is not a bug, mindustry has never and will never have controller support

**Comment by Zahar2loshara** [comment]
Why?

**Comment by SITUVNgcd** [comment]
> Why?

https://github.com/Anuken/Mindustry-Suggestions?tab=readme-ov-file#a-few-things-you-shouldnt-suggest

**Comment by Zahar2loshara** [comment]
... Doesn't really answered my question but ok
