### ISSUE TITLE
Mod can't load ShallowLiquid class texture overrides

### ISSUE THREAD

**Issue by mariocvj** [Anuken/Mindustry#10343]
### Platforms

Windows

### Build

steam build 146

### Issue

When I tried to make a texture mod which replaces vanilla floor tiles I couldn't get the game to load my textures for sand-water, darksand-water and darksand-tainted-water. My other textures loaded successfully.

The only mod that I have enabled is my example mod which I attached bellow.
 
Here I attached screenshots of said mod's /sprites-override/blocks/environment folder and of how that renders in game.

![image](https://github.com/user-attachments/assets/e3a8f88f-d25d-48b2-a817-305c688c2b18)
![image](https://github.com/user-attachments/assets/50bc0429-078c-42f9-9436-a2076bebfbc0)

### Steps to reproduce

1. I loaded my example mod by clicking Import Mod -> Import File inside the game.
2. The game automatically closes to reload mods, then Steam does some syncing for a few seconds and then I run the game again.
3. I play on any map or mode and textures render like in screenshot above.

### Mods used

[texture-mod.zip](https://github.com/user-attachments/files/17852425/texture-mod.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
<img width="371" alt="image" src="https://github.com/user-attachments/assets/be16af89-6599-4914-9b4b-13161ab9c664">

Your naming convention is incorrect.
