### ISSUE TITLE
Play option in main menu obscured by logo in default small window resolution

### ISSUE THREAD

**Issue by EL-ITIAGO** [Anuken/Mindustry#1034]
**Platform**: *Windows*

**Build**: *Steam build 99.12*

**Issue**: *When playing in windowed mode, minimizing the window will cause the main menu to shrink in a way which obscures the Play option with the game's logo. This began after the Mods option was added to the menu.*

**Steps to reproduce**: *Change to windowed mode, press the Maximize/Restore button on the window's control box.*

![example](https://user-images.githubusercontent.com/45916874/68551451-5d064780-040d-11ea-8322-0da366ab8621.png)

**Comment by Anuken** [comment]
Use a bigger window, or wait until next release.
