### ISSUE TITLE
Resource dupe

### ISSUE THREAD

**Issue by DEpObORnik** [Anuken/Mindustry#10344]
### Platforms

Windows

### Build

steam 146

### Issue

resources get duped by placing container/vault next to core and remove the core(resoucres remain in container/vault and can be unloaded then)

![image](https://github.com/user-attachments/assets/5e11dec9-5c80-4a39-80c5-171ed989a6da)
![image](https://github.com/user-attachments/assets/a1263804-ddc7-4759-94ba-4da951bba1e7)
![image](https://github.com/user-attachments/assets/455b5185-a16a-441d-98fa-376b348a76b9)
![image](https://github.com/user-attachments/assets/234a0dc2-58ba-48cb-beaa-13792c99fe2a)
![image](https://github.com/user-attachments/assets/27da4e8b-657c-4704-8d4a-d7213bc1767d)

### Steps to reproduce

place a container/vault next to core and make core dissapear/captured by another team

### Mods used

none

### Save file

[resource_duping.zip](https://github.com/user-attachments/files/17853450/resource_duping.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by DEpObORnik** [comment]
> I suspect it's a issue of the plugin. Can you share the key code of the plugin?

it was done in sandbox too. no plugins. save file has the map

**Comment by way-zer** [comment]
Reproduced the problem, both in v146 and BE
