### ISSUE TITLE
Retusa cant aim correctly, and incorrect description

### ISSUE THREAD

**Issue by Juni-0220** [Anuken/Mindustry#10356]
### Platforms

Windows

### Build

BE 2546 (a3110fd)

### Issue

Retusa cant aim at small targets.
The description says it does not target air, but it does.

### Steps to reproduce

An immobile retusa cannot hit anything.

### Mods used

None

### Save file

[retusa cant aim for shit.zip](https://github.com/user-attachments/files/17963254/retusa.cant.aim.for.shit.zip)
![Capture](https://github.com/user-attachments/assets/7c7f133e-d1c8-44a4-9c19-cfe63b6a8113)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
It's being pushed by the top two units, which throws off its aim. Won't fix.
