### ISSUE TITLE
Steam workshow, map is getting mislabeled

### ISSUE THREAD

**Issue by mayli** [Anuken/Mindustry#1035]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Steam
**Build**: *The build number under the title in the main menu. Required.*
latest
**Issue**: *Explain your issue in detail.*
I am looking for attack maps, but somehow there are PvP maps, since there are many PvP maps in attack section, I am assuming this might be a bug in the map uploader.
![image](https://user-images.githubusercontent.com/822628/68562867-60df9d00-0400-11ea-90f2-6b27d020d4e6.png)

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

https://steamcommunity.com/workshop/browse/?appid=1127400&requiredtags[]=attack

**Comment by Anuken** [comment]
All PvP maps are valid attack maps, and vice versa. They are not distinguished.
