### ISSUE TITLE
Warn if any core is under attack

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1036]
[`core is under attack!`](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/ui/fragments/HudFragment.java#L301) only takes the first core into account, it would make sense if it would warn about all allied cores a map might have.

**Comment by itskatt** [comment]
With an indicator pointing towards the attacked core.

**Comment by Anuken** [comment]
Should be posted in the feature request page.

**Comment by Quezler** [comment]
on*

**Comment by ZkyLB** [comment]
nice
