### ISSUE TITLE
Automatic pathing; bridge placement replacing conveyor after terrain

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#10368]
### Platforms

Windows

### Build

146

### Issue

If I drag the uncompleted conveyor from left to right to left in the attached screenshot, it will automatically create a bridge to go over the terrain, but replace the existing conveyor immediately behind it.

I expect it to build a 2 length bridge like the one above it.

(Excellent job on the game btw!)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/554bb4fa-1e48-4d8d-8bc0-9bd7a8426309)

![image](https://github.com/user-attachments/assets/1d6da3cb-1649-4a04-b03c-325a8719b6ef)

### Mods used

None

### Save file

[sector-serpulo-227.zip](https://github.com/user-attachments/files/18111104/sector-serpulo-227.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
Wasnt this fixed in BE to where bridges now opt for the longest distance over shorter?
