### ISSUE TITLE
Markers gain bloom on bullet layers

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10364]
### Platforms

Android

### Build

25465

### Issue

Between layer 100-110 all markers gain bloom

### Steps to reproduce

Make a marker and set its drawLayer to between 100 and 110, can be any type 
```
makemarker shape 70 3 3 false
setmarker drawLayer 70 100.0 0 0
```

### Mods used

vanilla

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
The layers are provided in the instruction and this one doesnt specify its meant to have bloom, unintended side-effect

**Comment by Anuken** [comment]
That's the bloom layer, not a bug.

**Comment by camelStyleUser** [comment]
> There is still an issue with it being labelled the bullet layer then :/

bullets literally bloom

**Comment by Anuken** [comment]
The layer is called "bullet", and bullets bloom, it's even mentioned as such [in the comments](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/graphics/Layer.java#L71). I don't see the issue.

**Comment by JasonP01** [comment]
> it's even mentioned as such in the comments.

Not labelled as such ingame, you shouldnt expect every user to view github to know why that one makes their marker appear differently where its not specified anywhere else.

Markers are official content so they have to explain why something does something different for various reasons, ingame

Nevertheless this conversation is pointless as unlikely for anything to change
