### ISSUE TITLE
Starting the game issue

### ISSUE THREAD

**Issue by BoomKofe** [Anuken/Mindustry#10369]
### Platforms

Windows

### Build

146

### Issue

When i try to start Mindustry, the game is opened for a while and then crashes with a message: "A crash has occured. It has been saved in: C:\Users\ [user]\AppData\Roaming\Mindustry\crashes\crash-report-12_12_2024_18_29_56.txt FileNotFound: locales (Acces denied)". Although I have the locales folder on my desktop, it still appears/

### Steps to reproduce

I double-clicked the Mindustry, it opened for a second and then crased with the report.

### Mods used

No mods used (vanilla)

### (Crash) logs

[crash-report-12_12_2024_18_29_56.txt](https://github.com/user-attachments/files/18113909/crash-report-12_12_2024_18_29_56.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> Although I have the locales folder on my desktop, it still appears/

Delete the folder, it must not exist. Don't keep Mindustry files on the desktop either.

**Comment by BoomKofe** [comment]
Thank you!
