### ISSUE TITLE
Time of effect is gone

### ISSUE THREAD

**Issue by Doublelol48** [Anuken/Mindustry#10362]
### Platforms

iOS

### Build

146

### Issue

Duration of the effect gone
![834ED0C3-3057-47E8-8EBB-79F4C584FBFC](https://github.com/user-attachments/assets/7172b36e-6fd3-4345-b720-c90db54d3d2f)

### Steps to reproduce

On a world processor, when you enter the command: apply status, you select overdrive, you go to remove status and back to apply, the duration of the effect is gone

### Save file

[bug.zip](https://github.com/user-attachments/files/18052258/bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by coaldeficit** [comment]
overdrive is a permanent effect that never wears off

**Comment by Doublelol48** [comment]
> not a bug, overdrive is a permanent effect that never wears off

But then why does the time show here
![5571637D-98FC-4AEE-A747-78F525C3346E](https://github.com/user-attachments/assets/52fd0a20-8dd3-4cd8-9a41-9c5e52cbd678)
