### ISSUE TITLE
Mindustry

### ISSUE THREAD

**Issue by Firasazman** [Anuken/Mindustry#10371]
### Platforms

Android

### Build

Build 146

### Issue

Dear mindustry 
I was play with my friend but my friend Said there have bug i was look at him game and the her robot not load but if i see mine  him load i think that bug
BYE
FROM
FIRASAZMAN

### Steps to reproduce

Load

### Mods used

Nothing

### Save file

Only bug

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by jehosula** [comment]
not enough steps to reporduce or save file, meaningless post
