### ISSUE TITLE
Can't fully rebind Esc key functionality

### ISSUE THREAD

**Issue by sinder38** [Anuken/Mindustry#10377]
### Platforms

Linux

### Build

steam build 146

### Issue

Pressing `Esc` key makes you `open Menu`, `close` any menu and `go back` in any menu. I able to rebind opening menu to some other button but not other behaviors.

For example, I would like to rebind `go back` and `close` menu functionality to Caps Lock

### Steps to reproduce

1. Rebind `open Menu` action to some other key
2. Try to exist from  or go back in menus using said key
3. Fail trying

### Mods used

None

### Save file

I am sure this is not needed but, fine:
[mind_save1.zip](https://github.com/user-attachments/files/18149392/mind_save1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Intentional, won't fix.
