### ISSUE TITLE
Very heavy bug

### ISSUE THREAD

**Issue by Sarna122** [Anuken/Mindustry#10376]
### Platforms

Android

### Build

Every

### Issue

This game is unplayable, I can't find a vodka mod

### Steps to reproduce

Go to mod menu

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by jehosula** [comment]
no specific build, not enough detail about the issue or steps to reproduce, no response on mods used or save file, your post is meaningless as it could very well have been an issue not regarding the actual game

**Comment by grelylrz** [comment]
I have this bug too.

**Comment by SITUVNgcd** [comment]
You even not playing this game.
