### ISSUE TITLE
Meltdown doesn't fire its laser

### ISSUE THREAD

**Issue by codiophile** [Anuken/Mindustry#1038]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required.*
99.11

**Issue**: *Explain your issue in detail.*
Meltdown doesn't fire its laser.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
I had some time to kill on a flight and started a game of Mindustry. I noticed that the performance was much better and decided to check one of my old saved games. On wave 280 I had 11 FPS compared to less than 1 FPS. So that's a big and much appreciated improvement. However, the enemies were getting much further than they used to and even destroyed a few of my walls. At first I thought it was just an unusually strong wave, but after a few more waves, I realised that my Meltdown's weren't actually firing their lasers. They kept aiming and changing targets, but they didn't actually fire, so the enemies were left to the rest of my turrets.

My frontline Meltdowns did eventually fire their lasers, but not until most of the enemies had been killed by other turrets. My backup Meltdowns actually fired before my frontline Meltdowns, which doesn't make any sense, since they see the enemies later. My theory is that the "warm up" keeps reseting every time it changes target and my frontline Meltdowns keep changing targets, because as the enemies are passing by, the enemy who is closest to the turret keeps changing. It's not until the very end that they are targeting the same enemy for long enough to fire the laser. My backup Meltdowns fire earlier, because the enemies aren't passing them and they are able to lock on a target for long enough to fire the laser. 

Hopefully, the solution is as simple as not reseting the warm up timer when the target changes.

**Comment by Anuken** [comment]
Did you have enough power for the meltdowns to fire quickly?

**Comment by joshuaptfan** [comment]
Meltdowns consume cryofluid rapidly. Even if they are full of cryofluid between waves, if there are only a small number of cryofluid mixers, they will refill slowly and be unable to fire again until they have a minimum amount of cryofluid.

**Comment by codiophile** [comment]
@Anuken I have 412k of power stored in batteries and a surplus of about +500/s power production. 

@joshuaptfan They are water cooled. I have a thermal pump and a rotary pump, to cool 3 Meltdowns. I also have a liquid tank before the Meltdowns in case my pumps are ever taken out or offline, because of lack of power. They definitely have enough coolant.

Please note that my defence was working perfectly in previous versions. Not sure exactly which version that was, but one from early October I think.

**Comment by Anuken** [comment]
Water was changed to be a much less effective coolant than cryofluid. If you're using water, your fire rate will be much lower than usual.

**Comment by codiophile** [comment]
![Screenshot_20191111-161104](https://user-images.githubusercontent.com/1095879/68602268-efeec280-049d-11ea-864e-841e10af482f.png)


The Meltdowns in the bottom right corner are firing before the Meltdowns on the top. I really don't see how that can be anything other than a bug. They are all fully supplied. 

In which file is the warm up for the Meltdowns implemented?

**Comment by Anuken** [comment]
I see that both of the side meltdowns are supplied with bridges, while the one at the back uses direct input, which is probably why they're slower. Bridges don't transfer as quickly when the FPS is low.

Code: https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/world/blocks/defense/turrets/LaserTurret.java#L60

I haven't touched this in a while, but I'm fairly sure reloading does not get reset when the target change.

**Comment by codiophile** [comment]
![Screenshot_20191111-170208](https://user-images.githubusercontent.com/1095879/68605863-1b28e000-04a5-11ea-84fe-b3a435d37ff7.png)

I managed to catch the bug in action. The enemies are coming from the north, but the closer Meltdowns don't fire until after the Meltdowns that are further away. The delay is quite significant and has significant impact on the game, since I now have to rebuild my walls after every wave.

**Comment by Anuken** [comment]
Add more bridges and see if the fire rate increases. If it does, then it's a framerate issue - the game is not designed to run at ~8 FPS, as the bridges have to push more than 6x the fluid content per frame, and they don't have the fluid capacity to do so.

**Comment by codiophile** [comment]
@Anuken the FPS was much lower before, but the lasers fired much quicker. Did you change anything in the bridge code recently?

**Comment by Anuken** [comment]
No, meltdowns previously had different (smaller) water requirements and fired faster when water was supplied.

**Comment by codiophile** [comment]
@Anuken As soon as it fires, it doesn't stop until the last enemy is dead, so to me it doesn't look like it is running out of water. Also to me, it looks like when the enemies are "slow", it fires quickly and continues until they are dead.

**Comment by Anuken** [comment]
> it doesn't stop until the last enemy is dead,

It doesn't use any water to keep the actual laser around, so that would be expected. The firing duration does not depend on coolant input.

> Also to me, it looks like when the enemies are "slow", it fires quickly

When are the enemies slow?

Maybe your issue is

**Comment by codiophile** [comment]
![Screenshot_20191111-173900](https://user-images.githubusercontent.com/1095879/68608315-74dfd900-04aa-11ea-8447-b1aef8cf1970.png)

It looks to me like it has water, but it doesn't fire.

**Comment by codiophile** [comment]
> > it doesn't stop until the last enemy is dead,
> 
> It doesn't use any water to keep the actual laser around, so that would be expected. The firing duration does not depend on coolant input.

Really? That seems weird. I thought it was getting hotter while it was firing and it was using coolant to keep it from overheating.

> 
> > Also to me, it looks like when the enemies are "slow", it fires quickly
> 
> When are the enemies slow?

There are different units that travel at different speeds and different waves contain different units. It seems like some waves it actually fires as expected. It seems weird to me that for some waves it has enough coolant and for others it doesn't.

It is using coolant before it fires the laser, but I don't understand what it needs the coolant for if the laser isn't switched on. Logically the delay is the time it takes to heat up the laser to operating temperature and then it uses coolant to keep it at that temperature and if it runs out of coolant it has to shut down the laser to not overheat it. More efficient coolant should mean that it can run at higher wattage, but then the power consumption should also go up.

I was reading the code, but I don't understand how the delay is calculated. Maybe you could explain?

**Comment by Anuken** [comment]
> That seems weird. I thought it was getting hotter while it was firing and it was using coolant to keep it from overheating.

No, the way it works is that it builds up heat upon firing, then takes a variable amount of time to cool down after firing. The duration of the laser is constant, but cooldown is not.

I just tried capping my FPS to 15 and spawning loads of wraiths to attack a meltdown. Even though the turret was twitching constantly, it fired at a (albeit slow, due to the subpar coolant) constant rate, 7+ seconds between laser end and next laser begin.

How slow are yours firing?

**Comment by beaurepair** [comment]
@Anuken I'm getting a similar issue whenever resuming a saved game. Most meltdowns won't fire for a minute or so Keven if they were before the save).
Here's a video showing the meltdown not working, then working for a few rounds. I click save and quit, then resume the game and they don't work again.
They are all reporting sufficient water being supplied.

Again, this has only been for 99.x builds (current 99.11).

https://photos.app.goo.gl/DoXbVyQedomMEina9

**Comment by Anuken** [comment]
I don't see an issue in that video. Meltdowns take up about 8ish seconds to reload before firing w/ water, and the reloading only occurs when a target is around. In your video, the first few rounds do not last more than 8 seconds, so when enough time has passed they eventually start shooting.

**Comment by beaurepair** [comment]
The centre Meltdown does not fire until after 3 rounds, at which point it has had targets within range for an accumulated 20 seconds.

It might just be the change that dropped usefulness of using water to cool Meltdowns.
Will switch to cryofluid and see how I go.

**Comment by codiophile** [comment]
> reloading only occurs when a target is around

@Anuken What's the reasoning behind that? To me it doesn't seem like reloading should have anything to do with wether a target is around or not. To me it seems like reloading is something that should happen any time it isn't loaded.

> Meltdowns take up about 8ish seconds to reload before firing w/ water

Does that mean that the cooling is used for loading and not for firing?

**Comment by Kharnellius** [comment]
I'm having the same issue.  Quite a few of my Meltdowns appear to just refuse to fire.  I noticed it is much worse on faster enemies as they "appear" to keep changing targets.  I don't have the proof yet, but I'm wondering if the Meltdown is having "target selection overload" where it can't decide on a target and just keeps switching targets, never actually firing.

**Comment by samoen** [comment]
could it have something to do with whether the enemy is cheating? this line in LaserTurret class, it consumes maxUsed if cheating, but shouldn't it consume maxUsed * Time.delta()?

float used = tile.isEnemyCheat() ? maxUsed : Math.min(entity.liquids.get(liquid), maxUsed * Time.delta());

**Comment by TheMeltdown201** [comment]
I guess using overdrive projectors can increase the firing rate, but i don't know if you got any plastanium in Ground Zero...

**Comment by mRebornM** [comment]
Actually, idk what causes this but i had this issues too. Just replaced the meltdowns and it fixed itself

**Comment by Anuken** [comment]
No longer valid, and unlikely to occur with significant changes done to turret code in 6.0.
