### ISSUE TITLE
error in achievement

### ISSUE THREAD

**Issue by GRaf-NEET** [Anuken/Mindustry#10381]
### Platforms

Windows

### Build

steam 146

### Issue

The number specified to obtain the achievement is incorrect.
![изображение](https://github.com/user-attachments/assets/791dd6b4-c95a-4ad4-bfc6-d172542bb58b)
 if the image is not displayed, then in short, in the achievement where you need to launch 1 million items, to complete it you need to launch only 100 thousand

### Steps to reproduce

no steps

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This looks like a translation error, which is not a bug - submit an updated translation if you would like to fix it.

**Comment by GRaf-NEET** [comment]
here is the corrected version "Запустите 100,000 предметов"
