### ISSUE TITLE
bug with resources in core

### ISSUE THREAD

**Issue by q1edj** [Anuken/Mindustry#10382]
### Platforms

Windows

### Build

146

### Issue

While I was making the map, I encountered a bug: somehow, when I land, I receive 260k resources of all types, including some that don’t even exist in the game (they’re not in the core database). I don’t have any mods installed.(i can send a video if needed)

### Steps to reproduce

I’m not sure how it happened. I simply switched my team to the enemy team for convenience, and the issue I mentioned above occurred.

### Mods used

no mods

### Save file

[map.zip](https://github.com/user-attachments/files/18201228/map.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by jehosula** [comment]
having a full core of resources is not a bug, you have base builder ai toggled for the enemy team which does this normally, however for some reason it is 20x the core's capacity which IS in fact unusual

**Comment by q1edj** [comment]
thanks, but i have a question. Why doesn't the AI build bases even when this feature is enabled?

**Comment by camelStyleUser** [comment]
> thanks, but i have a question. Why doesn't the AI build bases even when this feature is enabled?

if you have RTS ai on it will conflict with base builder ai

**Comment by q1edj** [comment]
i tried to disable it but units just trying to attack each others core
![Screenshot_13](https://github.com/user-attachments/assets/78365cf7-17b3-4be8-a084-c5d11a0b4ccd)
