### ISSUE TITLE
All sectors under attack

### ISSUE THREAD

**Issue by Wndering-Coder** [Anuken/Mindustry#10383]
### Platforms

Android

### Build

BE 25463 f(57044c)

### Issue

When playing bleeding edge, some times the game crashes when trying to enter an attack map, when you return almost all sectors are under attack even those which were not vulnerable 
![Screenshot_20241216_092650](https://github.com/user-attachments/assets/6705cc82-a05e-4445-a80b-0a5c20e444d6)

### Steps to reproduce

Just the game crashes when trying to attack a vulnerable server.

### Mods used

Mapping Utilities

### Save file

[Bugged.zip](https://github.com/user-attachments/files/18213336/Bugged.zip)

### (Crash) logs

[crash report.txt](https://github.com/user-attachments/files/18213368/crash.report.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
seems to be likely caused by mapping utilities

**Comment by Wndering-Coder** [comment]
By mapping utilities? Weird. Could be possible. But i did disable mods a while after I started using Bleeding edge

**Comment by Matita008** [comment]
the logs says that at the moment of the crash you had it enabled

**Comment by Wndering-Coder** [comment]
well my bad then. The picture is a decent bit old. sorry about that

**Comment by Anuken** [comment]
What likely happened is your data was corrupted, and the sector data was reverted to a much older backup. Unless I have a log of the crash, I can't fix this. The only log you attached is caused by a mod, and is not relevant to this issue.
