### ISSUE TITLE
Can't open mindusry after leaving the window

### ISSUE THREAD

**Issue by ZeleniyKustik** [Anuken/Mindustry#10384]
### Platforms

Windows

### Build

25475

### Issue

If you exit the mindustry window and then try to reopen it, it will not reopen.

### Steps to reproduce

https://github.com/user-attachments/assets/f1b36e24-f205-41c6-a0f7-8e8aec7d6c00

Enter Mindustry.
Exit the Mindustry window
Try to return to the window

OS: Windows 11
CPU: AMD Ryzen 5 3500U
GPU: AMD Radeon(TM) Vega 8 Graphics
RAM: 20 GB 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Ampter** [comment]
Might be a OS error, try rebooting

**Comment by ZeleniyKustik** [comment]
Rebooting doesn't help. It's still the same

**Comment by Anuken** [comment]
Unable to reproduce the issue.

**Comment by ZeleniyKustik** [comment]
I checked the 146 release version. And it has the same problem. It wasn't there before. I'll figure out what's wrong.

**Comment by ZeleniyKustik** [comment]
Reinstalling the graphics drivers fixed it.

**Comment by ZeleniyKustik** [comment]
What's strange is that this error only occurred with mindustry
