### ISSUE TITLE
create subdirectories in releases zip files

### ISSUE THREAD

**Issue by filippog** [Anuken/Mindustry#1039]
**Platform**: *Linux*

**Build**: *N/A*

**Issue**: downloaded `mindustry-linux-64-bit.zip` and at time of unpack the wasn't a corresponding directory with all files included, e.g. `mindustry-linux-64-bit`. All files were instead extracted in whichever directory the browser downloaded the file into e.g. `~/Downloads`. IMHO it would be better to decompress all files in a separate directory, what do you think?

**Comment by Anuken** [comment]
My archive manager (standard on Mint, Ubuntu) has always extracted files into a separate directory automatically. What are you using?

**Comment by matheod** [comment]
I hate when people put a folder in a zip file. I don't find it logical.

With 7zip, i can choose between uncompressing here on in the subfolder.

**Comment by Anuken** [comment]
Yeah, I prefer non-directoried zip files as well. Use a better archive tool.

**Comment by filippog** [comment]
@Anuken I'm using `unzip` on command line on Debian, specifically `unzip mindustry-linux-64-bit.zip`. I'm failing to see how this is the tool's fault, anyways overall a minor point and ultimately users preference/expectations, thanks anyways!
