### ISSUE TITLE
the controls changed from mobile to desktop 

### ISSUE THREAD

**Issue by metemeto** [Anuken/Mindustry#10391]
### Platforms

Android

### Build

release build 146

### Issue

i downloaded a mod called mobile controls and deleted it because it wasnt needed, after restarting the game a tab called controls appeared in setting and turned the games controls the desktop ones, it was playable with a keyboard. i tried to fix it by first deleting all mods , then exporting the data-resetting the data and importing but the save was "invalid game data", the file works on the BE build 25473 but the bug is not gone, it also isnt caused by the mod, tried it in the release build 146, the bug didnt occur idk what todo

### Steps to reproduce

downloaded a mod called mobile controls, deleted it and restarted the game

### Mods used

none

### Save file

[broken save file.zip](https://github.com/user-attachments/files/18266259/broken.save.file.zip)

### (Crash) logs

not a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by 50275** [comment]
have you tried Settings -> Game -> Mouse+Keyboard Controls (turn off)

**Comment by metemeto** [comment]
it worked, thanks for sparing your time
