### ISSUE TITLE
Research tree bug

### ISSUE THREAD

**Issue by bokunodev** [Anuken/Mindustry#10393]
### Platforms

Linux

### Build

146

### Issue

when the player don't have enough resource to unlock a tech tree branch. but decided to click on the branch regardless, player's resources that required to unlock that branch will reset to 0 and the branch still locked.

in my case it happen with Thorium in Stronghold.
![image](https://github.com/user-attachments/assets/10155ebd-7edc-41be-9116-9be344af5dbc)

### Steps to reproduce

1. collect a little thorium
2. open tech tree
3. click on one of the branch that require a large amount of thorium to unlock
4. close tech tree and back to game
5. thorium reset to 0 and the branch still locked

### Save file

[out.zip](https://github.com/user-attachments/files/18269075/out.zip)

i abandoned the base before submitting this bug report.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
this is intended behaviour, it is not a bug

**Comment by jehosula** [comment]
if it partially researched then that's 100% intended behaviour

**Comment by jehosula** [comment]
> @jehosula it happened multiple times. will the branch unlocked at some point? or the resources actually just gone.

oh doing this just puts all your current items to the research if you don't have enough of them, so if you keep going then you will get the research

**Comment by JasonP01** [comment]
1 dev, anuken.
Im a contributor (barely)
And the rest are just commentators who help sometimes
