### ISSUE TITLE
Guns disappear after loading saved game

### ISSUE THREAD

**Issue by noby256** [Anuken/Mindustry#105]

**Comment by noby256** [comment]
Hi Anuken,
We were playing multiplayer mode.
After we load a saved game all our bought guns were disappear.
I guess guns are not saved in file.

**Comment by Anuken** [comment]
This is intentional: only the host's guns are saved in multiplayer. This is due to compatibility problems with singleplayer. I can't add this to the save file format easily without the possibility of breaking old saves.
