### ISSUE TITLE
Import of mod doesn't work

### ISSUE THREAD

**Issue by idk-idk-idkfhdhfhfh** [Anuken/Mindustry#1055]
**Platform**: *Android/iOS I'm not sure which,I'm on mobile,Google pixel 2

**Build**: *99.11

**Issue** every time I try to import a mod it appears,boy when I reload it is gone,and not enabled

**Steps to reproduce**: imported the mod,reloaded,and reentered the mods menu

**Comment by owenboe** [comment]
Same but I'm on pixel 4

**Comment by Anuken** [comment]
Which mod is this?

**Comment by BadRyuner** [comment]
> Which mod is this?

All mods (Test on build 101.1)

**Comment by RogueRedHawk** [comment]
I've been having some issues with this as well but I haven't been able to reproduce it consistently.

**Comment by Mosrod** [comment]
Same for all mods - Pixel 3 Build 101.1

**Comment by Anuken** [comment]
This works correctly on my emulators and devices, so I won't be able to fix this issue, even if it still occurs.

**Comment by BadRyuner** [comment]
Tests on all android 10 customs (+clear version) app cant extract mods, he creates mfs:10XX and cant open directory with mods. Mods works on 10Q only then, when I manually extract mods. 
On android 9 (Customs+AOSP clear) app can extract mods.

**Comment by Anuken** [comment]
I have no issues with opening of mods on an Android 10 (API 29), either through import from the home folder or from Github. Mods persist after app restart.

**Comment by Martinocom** [comment]
I'm currently running on Mi A2, custom ROM (Pixel Experience, Android 10) + root. All is working, except:
 - loading mods (same issue as described above)
 - opening the mod folder (unable to open folder .... Missing valid file manager).

Mods are loaded, but after restart they are gone. When I try to reload then, it says that mod is already installed.

And when pressing the open mod folder, only the toast appears. I have not one, but two file explorers, one stock and FX File Explorer.

Indeed, I can go into the mod folder, and there are folders of mods "applied". Deleting those folders, I'm again able to load them in game, but then, as described before, they disappear after restart.

Yes, storage permission is granted.

![Screenshot_20200429-092310](https://user-images.githubusercontent.com/17514549/80570454-15936800-89fb-11ea-8dd3-86467a2e35c1.png)
![Screenshot_20200429-092254](https://user-images.githubusercontent.com/17514549/80570459-16c49500-89fb-11ea-9359-4a1dd178c1be.png)
![Screenshot_20200429-092242](https://user-images.githubusercontent.com/17514549/80570461-175d2b80-89fb-11ea-9878-450266c9584c.png)
