### ISSUE TITLE
Sound issues crackling sound/ 5.1 Sound mainly out of rear speakers

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#1062]
WIndows 10
Build 5899

When big attacks are happening or if I just use the Trident bomber the sound cracks and overlaps very annoying. 
Bonus Issue: My 5.1 Surround System outputs the majority of sounds from the rear speakers. I have to switch to Stereo Sound to solve the Issue.
All other games work fine. So I think its an issue of the game.

Creative Soundblaster Omni Surround 5.1 is my Soundcard.

Amazing game btw. I love it.

**Comment by Anuken** [comment]
This is a fundamental issue with how sound works; if there's too much stuff happening, you'll get cracking and/or cutoff. It won't be fixed unless I switch to a different sound system, which probably will not be happening anytime soon.

**Comment by CaptainCosmotic** [comment]
maybe forced Stereo would help to solve the 5.1 Problems
