### ISSUE TITLE
Server Crasher

### ISSUE THREAD

**Issue by blackassasin1234** [Anuken/Mindustry#1079]
**Platform**: Server

**Build**: ~b99

**Issue**: 
My friend have made a "Server Crasher" client by modifying the UUID on the client side, but probably affects the server side. should probably take a look at this... DM TutorialGaming#4991 for the github repository

**Steps to reproduce**: Join a server with the custom client, crashes the server most of the time.

**Comment by iczero** [comment]
fixed by 2593e96
