### ISSUE TITLE
[compatibility] Game jar won't start without Mindustry.exe package in older device (OpenGL 1.1)

### ISSUE THREAD

**Issue by yfdyh000** [Anuken/Mindustry#1082]
**Platform**: Windows 10.

**Build**: 5.0 Build 98 - Nightly (bleeding-edge).

**Issue** & **Steps to reproduce**:
The game (`mindustry-windows-64-bit`) looks work fine in an older device (graphic without OpenGL 2.0).
After I has run `gradlew desktop:run`, it says `Your graphics card does not support OpenGL 2.0!` and exited.
If I run `gradlew desktop:dist` and then copy the `Mindustry\desktop\build\libs\Mindustry.jar` file to `mindustry-windows-64-bit\jre\desktop.jar`, it starts and work.
So, why is it not allowed to run from this .jar file directly?

**Comment by Anuken** [comment]
I don't support devices without OpenGL 2 at all, so you'll have to debug this yourself.
