### ISSUE TITLE
Inconsistent Esc key behavior for Esc - Settings menus

### ISSUE THREAD

**Issue by yfdyh000** [Anuken/Mindustry#1083]
**Platform**: Windows 10.

**Build**: 5.0 Build 99

**Issue**: Esc menu in gaming - Settings - Controls compared to other settings menus have different (but better) response for press Esc key. It close the interface itself, but does not close the Settings menu.

**Steps to reproduce**:
Start a game.
Press Esc key.
Click the Settings button.
Respectively try click the Graphics, the Game menu and then press Esc key to close it, comparing them to the Controls menu.

**Comment by Anuken** [comment]
Duplicate, already solved.
