### ISSUE TITLE
Phantom drones and bridges

### ISSUE THREAD

**Issue by LinuxLust** [Anuken/Mindustry#1089]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10

**Build**: *The build number under the title in the main menu. Required.*
99.12

**Issue**: *Explain your issue in detail.*
Anything that has to deal with bridges, whether conveyor or conduit there seems to be an issue with Phantom builder drones. Whether it's placing down a schematic or having the drones rebuild something that was destroyed, 9 out of 10 times the bridges they place do not connect.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

This happens almost every time I place down a schematic with bridges or have the drones rebuild destroyed bridges. I noticed it when some schematics I use that contain 4 or more bridges and usually at least 1 if not more of the bridges do not connect.

**Comment by Anuken** [comment]
Should have been fixed some commits ago.
