### ISSUE TITLE
Router or Coal Extractor bug

### ISSUE THREAD

**Issue by Malmik** [Anuken/Mindustry#109]

**Comment by TheChosenEvilOne** [comment]
Needs an explanation

**Comment by Malmik** [comment]
In specific configuration, where stone is lead to two coal extractors by router and with liquid router, coal extractor stops working after ~ 2 minutes or more. I have android version of industry, latest. I can send you a save file or screenshot when i will be on pc. Killing and reopening app and reloading the map don't fix that either so probably bug is easy to reproduce.

**Comment by Malmik** [comment]
@TheChosenEvilOne sory, i didn't filled the description field accidentallly

**Comment by Malmik** [comment]
![screenshot_2018-03-27-09-13-20](https://user-images.githubusercontent.com/30472695/37952147-6490eca6-318e-11e8-97e5-15b0bf784fb6.png)
![screenshot_2018-03-27-09-13-17](https://user-images.githubusercontent.com/30472695/37952159-6df2f88e-318e-11e8-8f05-69f73e4cb7ae.png)

**Comment by Malmik** [comment]
Found the way to send photo on mobile :D

**Comment by TheChosenEvilOne** [comment]
The routers fill up with coal, not a bug

**Comment by Malmik** [comment]
Hmm you are right. But in my opinion they should allow to transport stone independly of they state (if thay are full or not). This would make game more enjoyable. What do you think?

**Comment by TheChosenEvilOne** [comment]
I don't think so

**Comment by Anuken** [comment]
That wouldn't make any sense. Why should routers accept more items when they are full? This is a problem with your design, not the game.

**Comment by Malmik** [comment]
So why they are working, and after a while they are stoping. It just iritates that liquid routers work and usual not. Explain me this and I will don't have any questions more.

**Comment by Anuken** [comment]
As @TheChosenEvilOne explained, you have coal extractors right next to the routers. The extractors sometimes output coal into the routers (about 50% of the time, in this case, assuming there's space) and the router **can't output the coal back into the extractor**, as they only accept stone. Eventually, it gets completely filled with coal and stops accepting stone.

**Comment by Malmik** [comment]
Thank you very much and sorry for a problem

**Comment by TheChosenEvilOne** [comment]
(Probably need to explain better)
