### ISSUE TITLE
Missing license notices

### ISSUE THREAD

**Issue by donaldr3** [Anuken/Mindustry#1098]
**Platform**: Source

**Build**: Did not build yet.

**Issue**: It seems that the project is lacking proper license notices. License notices at the top of source files let users know whether they may use the work under the current license or any later version. You can learn how to use GNU licenses at https://www.gnu.org/licenses/gpl-howto.en.html. 

**Steps to reproduce**: grep through source files for license notices. They don't seem to be present.

**Comment by Anuken** [comment]
I don't like the idea of license notices, they add a lot of unnecessary lines to the codebase and make viewing files more difficult.
