### ISSUE TITLE
Mod doesn't work

### ISSUE THREAD

**Issue by gabrielbr1802gcc** [Anuken/Mindustry#1101]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

The mod "better_blocks" doesn't work in this version(build 100)

**Comment by Anuken** [comment]
Not a bug. The better blocks mod has broken JSON.
