### ISSUE TITLE
Overlapping of Items in Tech Tree

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Mindustry#1107]
**Platform**: *Android and Windows 10*

**Build**: *100*

**Issue**: *I have noticed with large amounts of mods, items overlap in the tech tree, to the point of may items being unobtainable*

**Steps to reproduce**: 
1. download ~5-10 mods 
2. open tech tree 

**Mod List**:
- Maxwelllondon/AdvancedLogistics
- AeronGreva/AeroMindustry
- Miner28/Bronze-Mod
- ZkyLB/Canvas
- Anuken/ExampleMod
- Vortetty/Mindustryalization
- TheBestBot/The-End-Is-Nigh

**Comment by Anuken** [comment]
This is known, it's a limitation of the tech tree layout algorithm. It is not designed to handle many different non-stacking leaf nodes in one spot. A temporary solution would be to spread out mod research more evenly.

**Comment by Vortetty** [comment]
Ok! Is it by any chance possible to add a checker that will see if items overlap, and adjust accordingly? Possibly even just by allowing a wider angle for nodes to sprouts off of it's parent?

**Comment by Anuken** [comment]
Not easily. Changing one part would mess up the whole layout.

**Comment by Vortetty** [comment]
ok, is there any way to see what mod an item came from without going through each mod? that way we can at least easily make compatibility patches?

**Comment by Vortetty** [comment]
or possibly a separate tech tree for mods, each mod shows on the mod tech tree map after the item has met it's requirement. or giving each mod its own tab in the tech tree that unlocks when the first item in that tree has it's prerequisites met?
