### ISSUE TITLE
graphite press regurgitating back into routers and distributers

### ISSUE THREAD

**Issue by frm5993** [Anuken/Mindustry#1110]
android version.

build 96

when i have a router or distributer feeding into a graphite press (i think with silicon smelter, too), when traffic becomes high, graphite will be ejected back into the router or distributer. and since graphite cant enter the graphite press, it clogs the whole thing, preventing coal from entering.

to reproduce, just have a distributer or router feed directly to a graphite press. it does not happen if you put a conveyer between them.

**Comment by Quezler** [comment]
Its intended behavior. router even warns about not placing it next to a machine that outputs.

**Comment by willis936** [comment]
Try using sorters.
