### ISSUE TITLE
'unloader' -  problem with priority

### ISSUE THREAD

**Issue by MrTomek** [Anuken/Mindustry#1120]
**Platform**: *ALL* 

**Build**: *Version 100.1*

When we bring 'items' to 'vault' on a regular basis.
And we will add two 'unloader' next to 'vault', one with filter eg 'coal' and we will leave the road unset.
Despite this, 'coal' flies out of 'unloader' not set

I am sending the save showing the problem
https://we.tl/t-a6rDY4Z1Ae
or
https://mrtomek.pl/unlockerproblem.msav

**Comment by Anuken** [comment]
This is not a bug. Unloader order is not deterministic or guaranteed.

**Comment by MrTomek** [comment]
Thanks for the info.

In that case, could you add new functionality, consisting in the possibility of selecting multiple filters at once in one 'unloader'
