### ISSUE TITLE
Server Sync issue

### ISSUE THREAD

**Issue by loper12** [Anuken/Mindustry#1121]
**Platform**: *Host Player is on Arch Linux, using the normal release aur package, players are on iOS/Android/Windows*

**Build**: *Release Build 100*

**Issue**: *All moving entities(enemies, players, bots) are invisible to the non-host players. The wave # also desyncs*

**Steps to reproduce**: *Join a game hosted on Arch Linux.* 

**Settings**: [gist](https://gist.github.com/loper12/841071302ec96aa63a2f52b33ddd1df2)

**Comment by Anuken** [comment]
This looks exactly like an issue with the host-client UDP connection, probably related to the network configuration. I haven't seen this happen in a very long time.

I don't have Arch Linux and am very unlikely to install it, so unless additional information is provided, this will not be fixed.

**Comment by loper12** [comment]
Am I also supposed to forward a UDP port?

**Comment by Anuken** [comment]
Yes, but I've seen what happens when people don't forward it - they aren't able to connect since UDP registration doesn't go through. I don't know what's going on with your setup that allows connection without proper UDP registration.

**Comment by loper12** [comment]
I forwarded it as a TCP/UDP port.
