### ISSUE TITLE
Failed to initialize Steam services (zero-byte libsteam_api.dylib)

### ISSUE THREAD

**Issue by tsal** [Anuken/Mindustry#1123]
**Platform**: Mac (Mojave)

**Build**: steam build 100.1

**Issue**: It is more an annoyance, but it seems dynamically-downloaded file is getting pulled as zero-bytes and generates an error pop-up at game start.  this started with 100.1.

**Steps to reproduce**:  Started up 100.1, got error to the effect of:

```text
Failed to initialize Steam services.
Error: SteamException: java.langUnsatisfiedLinkError: /private/var/folders/jz/{hash}/T/steamworks4j_1.0-Anuken/libsteam_api.dylib: dlopen({same path}): no suitable image found. Did find:

{same path}: file too short
{same path}: file too short
```

I'm not too great with Java, and I tried to dig, but I'm not sure how you're including the steamworks dependency, other than the version sha1 that got updated a couple of weeks ago. was that included in 100.0 ?

**Comment by tsal** [comment]
Note: the main annoyance is the error and the loss of workshop schematics, but I wasn't using very many.

**Comment by Anuken** [comment]
Will be fixed next Steam release.

**Comment by tsal** [comment]
Thanks @Anuken - I can confirm this is fixed.
