### ISSUE TITLE
Adding an overflow gate

### ISSUE THREAD

**Issue by acul2012** [Anuken/Mindustry#113]
I would suggest adding and really appreciate seeing a type of overflow gate/block in the game.
It would check if the block in front of it is completely filled with items and if then transport new arriving items to the sides. Kind of like the sorter. 
I don't know if this block would have to have a clear orientation or if it would be dependent on the direction the items come from,
I also don't know if there is room in the transport menu or if it would have to be a sorter option.

**Comment by Anuken** [comment]
This can already be done with tunnels.  
![recording1523154568](https://user-images.githubusercontent.com/10100000/38462326-315b722e-3ab3-11e8-8306-63a373ff7d3c.gif)
