### ISSUE TITLE
Server Sync Build Cancels

### ISSUE THREAD

**Issue by luketheduke492** [Anuken/Mindustry#1134]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
100
**Issue**: *Explain your issue in detail.*
When building anything while the server syncs, makes its progress get set back. This isnt too bad, but when your building something giant, it kinda sucks.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.* Just start building while the server syncs, and you should run into the bug.

**Comment by Anuken** [comment]
Not a bug. The building progress is saved on the server, and if it's lower, that means the server is running under different conditions than the client. The change is purely visual.
