### ISSUE TITLE
Player Character Bullet Velocity Issue

### ISSUE THREAD

**Issue by NickLalo** [Anuken/Mindustry#1135]
**Platform**: *Windows*

**Build**: *5.0*

**Issue**: *player character bullet velocity is affected by ship movement velocity.  If you are moving forward and shooting forward your bullets move very fast.  If you are moving backward and shooting forward your bullets are very slow.  If you are flying left fast and attempt to shoot right your first couple of bullets will continue moving left in the direction you were moving.*

**Steps to reproduce**: *Fly left for a bit and then start shooting right.*

![weirdShooting](https://user-images.githubusercontent.com/36871227/69688894-fd56a000-108c-11ea-89d9-94725839e633.gif)

**Comment by Anuken** [comment]
This is intentional. That's how physics works in real life.

**Comment by MEEPofFaith** [comment]
how did someone possibly consider this a bug

**Comment by NickLalo** [comment]
Physics is hard and I had a brain fart.  I think the quick turning around of the ship and change in speed in such a way that a bullet fired could hit yourself made me think something was wrong.

**Comment by MEEPofFaith** [comment]
but you can't actually hit yourself 🤔
