### ISSUE TITLE
Liquid and Item Bridges/Phase Conveyors can't output in a direction they are taking input from

### ISSUE THREAD

**Issue by Deliphin** [Anuken/Mindustry#1143]
**Platform**: *Windows 10*

**Build**: *steam build 100.1*

**Issue**: *In the below example, I want to be able to output in the direction of up, while the bridge also takes input from up.*
![1](https://user-images.githubusercontent.com/14265753/69880400-3024b200-12a0-11ea-9b4e-7f2fdf113544.png)
*But if I enable the bridge, all output is cut off.
![2](https://user-images.githubusercontent.com/14265753/69880439-4af72680-12a0-11ea-9c2f-92c535a4e832.png)

**Steps to reproduce**: *1. Build a bridge. 2. Connect to the bridge. 3. Place output conveyor in the the direction of the bridge's entry, from the bridge's exit.*

I want this to work so that I can have the exit output in all four directions.

I've tested with bridge conveyors, phase conveyors, bridge conduits, and phase conduits. They all exhibit identical behavior.

**Comment by Anuken** [comment]
This is intentional. Bridges are designed to cross conveyors and other structures without outputting to them; unnecessary dumping would make them contaminate everything.
