### ISSUE TITLE
Wrong displayed keys for AZERTY keyboard

### ISSUE THREAD

**Issue by DarkEyeDragon** [Anuken/Mindustry#1151]
**Platform**: *Windows*

**Build**: *100.1*

**Issue**: *Invalid displayed keys for AZERTY keyboards.*
![image](https://user-images.githubusercontent.com/6131099/69989931-02ac6280-1545-11ea-9eff-2891a2b89d88.png)
Move X should be Q (left) and D (right)
Move Y should be Z (up) and S (down)
The controls somehow still function correctly. Just displayed wrong.

![image](https://user-images.githubusercontent.com/6131099/69989748-a34e5280-1544-11ea-9da8-0c22968f4148.png)
Q should be A (need to actually press A to cancel)

**Steps to reproduce**: *Play any level on survival.*

**Comment by DeltaNedas** [comment]
your keyboard is the same as qwerty
if its scancodes are different and not just letters printed, it will send "A" instead of "Q"

**Comment by DarkEyeDragon** [comment]
> your keyboard is the same as qwerty
> if its scancodes are different and not just letters printed, it will send "A" instead of "Q"

That's not the case however. The right keys get typed in chat. If it was the same as QUERTY it would type QUERTY instead of AZERTY in chat. 

I'm not sure how the Move X and Move Y aren't affected by this though.
However when rebinding keys it'll still give their values as if it were QUERTY.

**Comment by joshuaptfan** [comment]
This is possibly because scancodes ≠ keycodes, because operating systems let you [choose your keyboard layout](https://support.microsoft.com/en-us/help/258824/how-to-change-your-keyboard-layout) without requiring different hardware. The game polls for scancodes and has a map of names for them.

[SDL scancodes used by the game](https://www.libsdl.org/tmp/SDL/include/SDL_scancode.h)

**Comment by Anuken** [comment]
Intentional behavior. As scancodes are used, and there is no platform-agnostic way to get mapped key names, you will be seeing QUERTY key names instead of the ones for your layout.
