### ISSUE TITLE
Sync issues in multiplayer

### ISSUE THREAD

**Issue by icosamuel** [Anuken/Mindustry#1152]
**Platform**: *Windows*

**Build**: *100.1*

**Issue**: *Sync issues in multiplayer*
There are a few things that we noticed were different ingame when in multiplayer. One of those is the power generation, which can be a totally different value in each client. This first issue can have consequences such as buildings crafting in one client and idling in the other, or progress bars with different values in say, a drone factory.

Of course this caused a lot of confusion at first, but it seems like the server still has the source of truth for things such as drone spawning and resource gathered in the core.

**Steps to reproduce**: *Playing the campain with a friend*
It happened to us at two occasions in the campain on different maps, though I can't remember which ones. Its also hard to tell which specific action led to these discrepancies, but it looks like power is the cause of other problems.

**Comment by Anuken** [comment]
Intentional behavior. Use /sync to make sure state is correct on clients.

**Comment by icosamuel** [comment]
I'm curious as to why this behavior is *intentional*

**Comment by Kieaer** [comment]
A bug

**Comment by Anuken** [comment]
It's *intentional* as in there's nothing to prevent it from happening and I'm surprised multiplayer works at all. Some day, that might change.

**Comment by icosamuel** [comment]
thanks for the clarification. awesome game btw! keep it going
