### ISSUE TITLE
Map lighting crash

### ISSUE THREAD

**Issue by pyronie** [Anuken/Mindustry#1153]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows

**Build**: *The build number under the title in the main menu. Required.*
version 100
**Issue**: *Explain your issue in detail.*
an error with lighting that I don't exactly know why happened
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
playing on ripoffourway when several players crashed repeatedly because of some error with lighting as far as I can tell. in order are the crash log and the map

[crash-report-12_02_2019_17_43_21.txt](https://github.com/Anuken/Mindustry/files/3913901/crash-report-12_02_2019_17_43_21.txt)
https://filebin.net/buprq0nnqvjhbe9y

**Comment by Anuken** [comment]
Already fixed.
