### ISSUE TITLE
Mindustry

### ISSUE THREAD

**Issue by genii11** [Anuken/Mindustry#1154]
Hi. 
![Screenshot_20191203_123737](https://user-images.githubusercontent.com/58465930/70038960-2a91d980-15ca-11ea-8764-50c76c318c13.jpg)
The game falls if you put this item next to the bridge

**Comment by Quezler** [comment]
The bridge above it is an item bridge and not a liquid bridge, and the turret on the right will not receive any liquid, replace the bridge with a liquid bridge and the junction with a router, then it should work 🤔

**Comment by genii11** [comment]
Here I am stupid))) Thank you for your help)
--
Отправлено из Mail.ru для Android вторник, 03 декабря 2019г., 13:34 +03:00 от Quezler  notifications@github.com :

**Comment by ZkyLB** [comment]
now end this issue

**Comment by Quezler** [comment]
close*
