### ISSUE TITLE
sending commands via socket

### ISSUE THREAD

**Issue by ebess** [Anuken/Mindustry#1155]
Hey, first of all, nice work.
I'm running a game server and trying to sending commands via sockets, but it does not work out for me. I already tried to more highlevel client.

Server:
```bash
java -jar /app/server-release.jar name test,socketinput on,logging on,host
```

Command:
```
echo "exit" | nc 127.0.0.1 6859
```

It connects to the socket, but not executes the command and can not see any errors. Also I can not read from the socket. I'm not that advanced regarding sockets but a small example in docs would be really nice.

**Comment by Quezler** [comment]
+1 (subscribing to this thread)

**Comment by DeltaNedas** [comment]
+2 because ssh like thing (or maybe just ssh?) to act as an extra mindustry server console

**Comment by Anuken** [comment]
I don't know how exactly it would work through a terminal without Java, but I used it by setting up a PrintWriter and writing a line to it. See this code: https://github.com/Anuken/CoreBot/blob/master/src/io/anuke/corebot/ServerBridge.java#L21

**Comment by indielm** [comment]
using PuTTy on Raw works

**Comment by ebess** [comment]
@Anuken I'm not into java at all, but there should be a way to run commands without any human interactions and get the output. Maybe I'm wrong here, but you should be able to send commands and read the output from the buffer to react to this. I exposed the socket port to the "outside world" but as mentioned above the socket does not work properly dispite the connection is established. So maybe someone else can help.

@indielm Can you go more into detail, what are you sending and what do you receive back? And how?

**Comment by Anuken** [comment]
@ebess 
> you should be able to send commands and read the output from the buffer to react to this

That's exactly what the code I linked to does.

**Comment by ebess** [comment]
@Anuken ah, I see. I got it to work but only if the script and server is running on the same host.
https://github.com/Anuken/Mindustry/blob/master/server/src/io/anuke/mindustry/server/ServerControl.java#L976
Does this line restrict the socket only for the `localhost` host? I'm trying to run the server in docker. That's why I struggled to connect to the socket.

@Quezler In node this worked out for me, but as I pointed out, the server and script should run on the same host:
```js

  const net = require('net');
  const client = new net.Socket();
  client.connect(6859, 'localhost', () => console.log('Connected'));
  client.on('data', data => console.log('Received: ' + data));
  client.on('close', () => console.log('Connection closed'));
  setTimeout(() => client.write('status'), 2000);
```

**Comment by Shawak** [comment]
I ran into the same problem and ended up writing to /dev/tcp/6859/127.0.0.1

My bash scripts look like this:
```bash
function server {
	echo "$1" > /dev/tcp/$IP/$PORT
}

function server_say {
	local msg="$1"
	server "say $msg"
	sleep 1
}

function server_save {
	server "save 1"
	sleep 3
}

[...]
```

You can't read that way, but for anything more complex I wouldn't use bash anyways.

Also in case you user docker, don't forget to open 6567 tcp AND udp.

`docker run -i -p "6567:6567" -p "6567:6567/udp" ...`

or using compose:

```
    ports:
      - "6567:6567" # server port
      - "6567:6567/udp" # server port udp
```

**Comment by Anuken** [comment]
> Does this line restrict the socket only for the localhost host

Yes. It's meant for communication with local applications. Since there's no security checks for the socket, having an open port there would allow anyone to control your server remotely given its address.

**Comment by ebess** [comment]
Ok, I see the point. Is there a way to pass an argument for allowing `0.0.0.0`? You open the port on your private network and block for public using a firewall. Another approach would be to setup a small web server with rest api in the same docker image as the game server.

**Comment by Quezler** [comment]
@ebess perhaps an ssh tunnel would be a more lightweight approach compared to a web api, while sacrificing no security 🤔

**Comment by Anuken** [comment]
No, the socket system is currently not configurable.

**Comment by Shawak** [comment]
Just replace localhost with 0.0.0.0? Could be a start parameter which name explicit states it is unsafe to use and is turned off by default.

**Comment by Anuken** [comment]
Why should I change its existing behavior and break security for existing users? If you need it to be non-localhost for your purposes, use any of the methods listed above.

**Comment by Shawak** [comment]
You asked how to allow 0.0.0.0 and I am just giving advice, I personally don't need that change since I use docker for this anyways.

**Comment by ebess** [comment]
`socketinput on <host>` would be really nice. host would be `localhost` by default. much easier to create a UI to host mindustry servers. was thinking of creating a page to host your own server for free. but for now, it's kind of a hustle

**Comment by Anuken** [comment]
That could be added in the future, but since the original question has been answered I'm going to close this issue.
