### ISSUE TITLE
There's only one mod. Could you please tell me a new industry mod that I can type in to the github mods? Thanks.

### ISSUE THREAD

**Issue by owenboe** [Anuken/Mindustry#1159]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
Join the Mindustry discord linked in the readme (discord.gg/mindustry) for a list of mods.

**Comment by owenboe** [comment]
Alright so I clicked on one and it said connection error NOT_FOUND. What do I do?

**Comment by Anuken** [comment]
It means you didn't input the name properly.
