### ISSUE TITLE
Another thing I found is that when I downloaded a mod I liked it said reload required. What does that mean?

### ISSUE THREAD

**Issue by owenboe** [Anuken/Mindustry#1160]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
The issue tracker is not for asking questions. Join the Discord and ask there.
