### ISSUE TITLE
Unable to export schematic

### ISSUE THREAD

**Issue by ZacBytes** [Anuken/Mindustry#1169]
**Platform**: 
*iOS*

**Build**: *100.1*

**Issue**: *When I press Export File and press create document, the schematic file is not created.*

**Comment by Arkanic** [comment]
there could be a lot of reasons for this

**Comment by Minecrafter69** [comment]
What are some of the main reasons for this cause?

**Comment by deviant2104** [comment]
Well it seems because the iOS doesn’t recognise the file and the file appear faded or selected 
Export and importing doesn’t work

**Comment by Anuken** [comment]
Should be fixed next release.
