### ISSUE TITLE
Player layer is underneath structures queued to be built

### ISSUE THREAD

**Issue by TechnologyClassroom** [Anuken/Mindustry#1173]
Version 5-fdroid-99

Great game!  Bought it on steam to show gratitude.

The building process looks odd as the player is underneath structures that are queued to be built.  I noticed this specifically with large copper walls.

**Comment by DeltaNedas** [comment]
happens for enemies, turret projectiles, etc. too
can reproduce on latest nashornjs build

**Comment by Anuken** [comment]
This is intentional behavior.
