### ISSUE TITLE
Large power nodes not connecting when clicking and dragging

### ISSUE THREAD

**Issue by torwesterlund** [Anuken/Mindustry#1176]
**Platform**: Windows

**Build**: Steam 100.1

**Issue**: Large power nodes' range seems to be too short to automatically connect when clicking and dragging to place multiple nodes.

**Steps to reproduce**: Click and drag multiple large power nodes.

**Comment by TsjipTsjip** [comment]
Cannot reproduce this. Release build 100.1

**Comment by Anuken** [comment]
Can't reproduce this either, regardless of drag direction.

**Comment by hiroshi-tea** [comment]
I also have this issue (the most recent Steam build if that matters) and recorded it [here]( https://www.youtube.com/watch?v=L7daOuB4RFs).
