### ISSUE TITLE
Power network not recalculating when a node is removed

### ISSUE THREAD

**Issue by torwesterlund** [Anuken/Mindustry#1177]
**Platform**: Windows

**Build**: Steam 100.1

**Issue**: A power network should be expected to recalculate its connections when a connected node is either removed or destroyed. It is instead ignoring the next best available node in range until that is removed and rebuilt.

**Steps to reproduce**: Place three nodes in range of each other. Remove the middle node. The remaining two are not connecting.

**Comment by itcannotbe** [comment]
Power nodes only auto connect upon placement.

**Comment by torwesterlund** [comment]
Yes, but I'm saying that it would make more sense that nodes which lose a connection should trigger a new auto connect check.

**Comment by TsjipTsjip** [comment]
Can reproduce, but this isn't necessarily a bug. If you want an area to have redundant power supply either move the power generators closer or connect the area to the power generator via multiple node lines. (Will require manually connecting them.)

**Comment by Anuken** [comment]
This is intentional behavior.
