### ISSUE TITLE
Overflow gates not working properly when places after each other

### ISSUE THREAD

**Issue by Chiel92** [Anuken/Mindustry#1178]
**Platform**: *Windows*

**Build**: *steam build 100.1*

**Issue**: *When placing overflow gates right after each other, they somehow perceive the overflow gate in front of them as blocking.*

**Steps to reproduce**: 
![image](https://user-images.githubusercontent.com/1030961/70372365-26bdca00-18de-11ea-85a8-8eeb7483cf09.png)

This issue makes it impossible to use overflow gates for resource distribution in a small space, because you always need to place one tile of conveyor belt in between them.

**Comment by itcannotbe** [comment]
Overflows will not send items to another overflow as intended.

**Comment by Chiel92** [comment]
That seems very odd to me. What is the reasoning behind this?

**Comment by ZkyLB** [comment]
i think """passback"""

**Comment by ph3rr3t** [comment]
Snek behavior avoidance.  Same reason u can only pass items through 2 sorters or 2 inverted.

**Comment by Chiel92** [comment]
> i think """passback"""

It's not immediately clear how being able passing items to an overflow gate *in front* of you results in passing the items back. Can you elaborate?

**Comment by Anuken** [comment]
Overflows transfer items forward instantly, and instant transfer blocks cannot be chained. The same applies to sorters.

**Comment by Chiel92** [comment]
Allright, that makes sense. Thanks for the explanation! Cool game btw.

I guess I'll have to get over my habit of using overflow gates by default for resource distribution. It's a shame, because they have the advantage that they do not balance their loads evenly across the outputs, but instead create the maximal imbalance possible. This allows you to more easily eyeball which parts of the production chain are underutilized.

**Comment by Chiel92** [comment]
Out of curiosity, is there a specific reason that sorters and overflows are instant?

**Comment by Anuken** [comment]
Adding a delay makes things very complicated in terms of buffers and designs. An attempt to make them non-instant lead to a lot of designs breaking during the beta.

**Comment by Chiel92** [comment]
@Anuken Do you have (or can you point to) any examples of a delay being a problem for sorters and overflows? I want to work on a proposal/mod to change some of these behaviors, and this design decision is one I still don't quite understand.
