### ISSUE TITLE
Game crash due to missing locale keys.

### ISSUE THREAD

**Issue by TsjipTsjip** [Anuken/Mindustry#1179]
**Platform**: *Windows*

**Build**: *Release build 100.1*

**Issue**: *Somewhere in the code responsible for loading translations an error occurs when an expected locale key is not present in the current bundle, causing the process to exit completely. I'm not a java developer and as such cannot point to the exact issue. (This might be something relating to a `.getNotNull` instead of a `.get` in the code according to some helpful people on discord.)*

**Steps to reproduce**: *Remove any key from the active locale bundle and navigate to a screen where this key is supposed to appear. (The current bundle_nl_BE.properties is missing link.f-droid.description, which is displayed on the About section of the main menu. You can use this to reproduce.)*
[crash-report-12_07_2019_14_35_27.txt](https://github.com/Anuken/Mindustry/files/3935122/crash-report-12_07_2019_14_35_27.txt)

**Comment by TsjipTsjip** [comment]
I am going to create a PR for the bundle_nl_BE.properties file later today which will have the link.f-droid.description key where it is supposed to be, resolving the issue as mentioned in the steps to reproduce. You can still manually remove any key to reproduce.

**Comment by TsjipTsjip** [comment]
Small and extremely quick update: This issue __does not__ occur when using a locale bundle via Settings > Languages, it only occurs when using an external translation bundle and as such is low priority. (Regular users who don't translate, ... won't run into this issue.)

**Comment by Anuken** [comment]
This is intentional behavior. It will not occur in the normal game, and it is designed to make sure that all the correct bundle keys are there.
