### ISSUE TITLE
[Android UI] Confirmation on line placement

### ISSUE THREAD

**Issue by willhansen** [Anuken/Mindustry#118]
Touch controls are inherently less precise than mouse controls.  On a phone, it is extremely easy to try to press a block, and accidentally press a block one to the left instead.  This is frustrating when attempting to place a line of blocks and suddenly finding that the whole line is slightly offset from where it should be, with no way to immediately prevent or undo the placement.

Applying the confirmation dialogue from group removals to group placements as well would go a long way in reducing frustration from fat-finger related mistakes.

**Comment by Commodore64x** [comment]
I would agree to this if there was a setting where you could toggle this on or off. At the moment I like the system that is in place, but a toggle would certainly be the best of both worlds.

**Comment by Gabgab2003** [comment]
+1

**Comment by Anuken** [comment]
![recording1527650227](https://user-images.githubusercontent.com/10100000/40741938-ded13ade-641a-11e8-90c7-2ddf5e278245.gif)

Implemented as part of the new build system on the 4.0 branch.
