### ISSUE TITLE
Software crash（by google translation ）

### ISSUE THREAD

**Issue by please82** [Anuken/Mindustry#1182]
**Platform**: *Android*

**Build**: *100.1*

**Issue**: **At half the level, the software crashed and the module was installed**

**Steps to reproduce**: ***After using up copper, collect the tin of the module, and in the middle (exit then enter), it will show “Archive corruption and loss”which makes me a bit ...***

**Comment by Anuken** [comment]
Post crash logs with your issue reports. Even if I knew what you were trying to say here, I can't fix it without a log.

**Comment by sjps940604** [comment]
Wait for my - log.

**Comment by sjps940604** [comment]
I have two accounts, let you know first.

**Comment by please82** [comment]
![Screenshot_2019-12-10-17-55-13](https://user-images.githubusercontent.com/32010728/70519626-360b7480-1b77-11ea-8f4f-f70b1994aed7.png)
but... I don't have a log.
Can you translate it yourself?
Thank you
