### ISSUE TITLE
Can't start map because of blocked loadout

### ISSUE THREAD

**Issue by SabreRunner** [Anuken/Mindustry#1185]
**Platform**: *Android*

**Build**: 100.1

**Issue**: I had a map -- Overgrowth -- in the campaign which I already finished and had a preset max loadout. In some recent version, I guess, maps were updated and now that map is marked as unfinished but my loadout is there and I can't start it.

**Steps to reproduce**: Just a guess, really: install an early 90s version. Finish Overgrowth as quickly as possible. Configure a max loadout. Upgrade to latest version. Overgrowth should be blocked.

**Comment by Anuken** [comment]
Why can't you start it? Are you lacking resources?

**Comment by SabreRunner** [comment]
![Screenshot_20191209-061439_Mindustry](https://user-images.githubusercontent.com/10673434/70407480-2bed5700-1a4d-11ea-9055-fc3167ccfc94.jpg)
This is how it looks like.

**Comment by SabreRunner** [comment]
It's a specific loadout but I can't use it because it says I haven't finished the map yet, but I also can't change it.

**Comment by Anuken** [comment]
I don't see why this is a bug. You can still play the map once you get the required resources for it. Yes, the objectives were reset, but that was intentional and caused by a change in the objective condition code.

**Comment by SabreRunner** [comment]
I see. I do, indeed, lack some surge alloy for that loadout. But, can't I change the loadout so I would be able to play it?

**Comment by Anuken** [comment]
If you made a loadout with those resources, you should still be able to get those resources from other maps.

**Comment by SabreRunner** [comment]
But I can't change the loadout to make it consistent with the resources I do have?

**Comment by Anuken** [comment]
Yes, but you can still get those resources from other maps.
