### ISSUE TITLE
Unable to import schematics

### ISSUE THREAD

**Issue by ZacBytes** [Anuken/Mindustry#1186]
**Platform**:
 *iOS*

**Build**: *100.1*

**Issue**: *When i try to import schematic, the file is greyed out and doesn’t work*

**Steps to reproduce**:
*1. Go to apple store
2. Buy an iPhone 📱 
3. Set up the phone and add payment method to app store so you can pay $0.99 for an app thats not fullscreen
3. Import schematic*

**Comment by Quezler** [comment]
> 3 

🤭 :ohno: 😂

**Comment by Anuken** [comment]
Already fixed.
