### ISSUE TITLE
Previous error report of s1182

### ISSUE THREAD

**Issue by please82** [Anuken/Mindustry#1188]
**Platform**: *Android*

**Build**: *100.1*

**Issue**: *False report
![Screenshot_2019-12-10-17-55-13](https://user-images.githubusercontent.com/32010728/70520918-4ae90780-1b79-11ea-9a78-11062b14109b.png)
*

by al translate app
Photos need to be translated

**Comment by Anuken** [comment]
1. Map corruptions can happen due to varying circumstances. I can't fix them without more information.
2. I don't actually know what the text says. If you're reporting the issue, it's up to you to translate it.
