### ISSUE TITLE
Cant aim with XBOX controller

### ISSUE THREAD

**Issue by Gabgab2003** [Anuken/Mindustry#120]
The Controller Cursor shows up and i can place blocks, but the mouse cursor doesnt dissapear => when i shoot, i shoot to mouse cursor, tried unplugging mouse before starting game, still uses mouse position of before unplug

OS: Win 7
Mindustry : 3.5-38
Xbox One wired controller (first party, bluetooth or usb)

Video (Terrible Lag in the Video):
https://drive.google.com/open?id=1xfI2wIGbeQ-oPWFHZK_OyBGJnyot4xua

**Comment by TheChosenEvilOne** [comment]
as far as I know xbox controllers are not supported

**Comment by Gabgab2003** [comment]
Why is there a Xbox mode in control settings then?

**Comment by TheChosenEvilOne** [comment]
yeah a derp on my part, sorry

**Comment by Gabgab2003** [comment]
Do you have an Xbox controller.? If so then please try to reproduce it yourself

**Comment by TheChosenEvilOne** [comment]
yeah, will try

**Comment by TheChosenEvilOne** [comment]
can confirm with my bad Chinese xbox controller

**Comment by Anuken** [comment]
Fixed as of 16c243d2709de0323410a8f8d0ed45301c940daf.
