### ISSUE TITLE
Launched items in launchpad issue

### ISSUE THREAD

**Issue by TsjipTsjip** [Anuken/Mindustry#1203]
**Platform**: *Windows*

**Build**: *Release build 100.1*

**Issue**: *When a launchpad launches items, these launched items are not saved when you "Save & Quit" from the menu, resulting in the loss of all previously launched items.*

**Steps to reproduce**: *This is a more elaborate setup, I was able to reproduce this the best on "The Craters". Defend until you get silicon running, then proceed to fill up the core with any material you don't use that often on this map. (This was metaglass for me, as it is very easily produced.) Once your core is filled up with the material, fill up an unpowered launchpad with the material. Disconnect the conveyor leading into the launchpad and power it. This totals the material amount you gain to the core capacity+100. Save and quit the map, then reload it. Make sure the launchpad is no longer operational after you loaded the game again, and launch the core at the next opportunity. You will see your selected material's gained amount is the core's capacity, without the previously launched set of items.*

**Comment by Quezler** [comment]
_subscribing_

**Comment by Anuken** [comment]
This was already fixed.
