### ISSUE TITLE
Changing mod name changes mod registry name

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Mindustry#1212]
**Platform**: *All*

**Build**: *All mod supported versions*

**Issue**: *when changing the mod name, block and item registry names change causing data loss.*

**Steps to reproduce**: *Rename any mod in mod.json or mod.hjson*

**Solution**: *add an ID parameter to mod.json and content files so you can change mod name or file names so names can be freely changed if you need to change it while preventing data loss.*

**Comment by Anuken** [comment]
This already exists; not a bug. Use `name` for the registry name and `displayName` to change the one users see.
