### ISSUE TITLE
Large health items have improper health detection

### ISSUE THREAD

**Issue by WilsontheWolf** [Anuken/Mindustry#1214]
**Platform**: *Windows*

**Build**: *100.1.*

**Issue**: *If an item has alot of health, then the game will show improper health on the bar, and even heal it.*
https://youtu.be/nW2Y2tXNFLs
**Steps to reproduce**: *Make a modded item with alot of health.
E.G:*
```json
name: Power Wall
description: An op wall.
type: Wall
health: 9999999999999999999999999999
size: 2
requirements: [
  copper/1
]
category: defense
```
*Then save and exit then reload. 
The walls will have no health on the health bar, have damaged sprites and will even be healed by mend projectors, but can still take a lot of damage!
The video shows it all.*

**Comment by Anuken** [comment]
Not a bug. The maximum health anything can have is 32,767.

**Comment by WilsontheWolf** [comment]
ok will do
