### ISSUE TITLE
Dedicated Multiplayer bug

### ISSUE THREAD

**Issue by jgonyea** [Anuken/Mindustry#1224]
**Platform**: Windows

**Build**: 101

**Issue**:  Survival mode in a dedicated server stops spawning bots at some point.

**Steps to reproduce**: 

-  Started server
- Started map Maze
- Map was playing correctly.
- Returned to game hours later, now on map Veins
- Game mode is still set to "survival", but no waves are spawned.  Current "wave" is over 475 and no bots are spawned when the countdown reaches 0.  I can type 
`stop` 
`host MAPNAME survival` 
followed by `gameover` and the next map will proceed correctly as expected.

**Comment by Anuken** [comment]
As it is meant for PvP, Veins doesn't have any enemy spawn points or units to spawn. The shuffling system currently doesn't check whether a map is "appropriate" for use with the gamemode it is set to.

**Comment by jgonyea** [comment]
Is there a way I can prevent such a map from autoloading?

**Comment by Anuken** [comment]
At the moment, no. The only option is to use custom maps that are all survival-appropriate.
