### ISSUE TITLE
blacklist support on steam

### ISSUE THREAD

**Issue by RageCooky** [Anuken/Mindustry#1230]
some psychosis just join your server in same team and remove your building and say fxxk you for no reason
I want to put these shit in blacklist,
but no infomation in steam menu "view -> player -> recently played with"

I know I shouldn' t report here,
but it is terrible impact on multiplayer mode.

**Comment by DeltaNedas** [comment]
just whitelist your friends?

**Comment by RageCooky** [comment]
> just whitelist your friends?

no, just ban these shit, so they can't join my server

**Comment by Anuken** [comment]
Just ban these people in the player menu (TAB -> hammer), or set the server to private.

**Comment by RageCooky** [comment]
> Just ban these people in the player menu (TAB -> hammer), or set the server to private.

Is "hammer" a one-time blacklist method ? Just hope to block them forever ...

**Comment by Anuken** [comment]
It's permanent.
