### ISSUE TITLE
Tau Mech doesn't fire repair laser

### ISSUE THREAD

**Issue by codiophile** [Anuken/Mindustry#1231]
**Platform**: Android

**Build**: 101.1

**Issue**: Tau Mech doesn't fire its repair laser. When a building gets damaged, the crosshairs shows up on top of it, but the Tau Mech doesn't fire. I've been able to get it to fire by moving it around, but I don't understand why it doesn't fire as soon as it's within range of a valid target. Tapping on the target or another target also doesn't help.

**Steps to reproduce**: I don't know if you have to do anything special for this to happen. The Tau Mech has never worked properly for me. Just upgrade to the Tau Mech, move it within range of a damaged building, and watch it do nothing.

**Comment by Anuken** [comment]
Are you trying to repair it whole flying over a block?

**Comment by codiophile** [comment]
Repairing while flying over a block? What does that have to do with anything? When shooting at enemies, I can be anywhere as long as I am within range. Why wouldn't it be the same while shooting repair lasers? Also repair bots seem to be able to fly over anything while they are repairing, why would it be different for the Tau Mech?

**Comment by Anuken** [comment]
You didn't answer the question. Ground mechs, as opposed to ships, cannot shoot while flying.

**Comment by codiophile** [comment]
@Anuken You are right, it wasn't shooting, because it was flying. I didn't have any clue about that. It's not explained anywhere in the game and it's not intuitive. Quite frankly I don't think it makes much sense. The difference between ground mechs and ships should be their ability to fly and not their ability to shoot while flying. For the NPCs this is implemented appropriately, but because of the way the player moves, the player has to be able to fly or the game would be unplayable.

I would say that the solution to this isn't to make the ground mechs fly when controlled by the player, but to only have ships controllable by the player. That would be intuitive and logical. Shouldn't be to difficult to change. Just rename the mechs to ships, use the flying animation all the time, and allow them to shoot while flying. ;)

In the case of the Tau Mech, it's very hard to use, since your buildings only take damage on the front lines and the front lines are very crowded. The only place I can put it is on conveyors and pipes, and it's very fiddly to get it in the right position. For defence with 1x1 turrets, it's all routers and there's nowhere to stand. You'll have to wait until after the wave and go on the other side of the wall to do the repairs. It would be so much easier if it was a Tau Ship. :)

**Comment by Anuken** [comment]
I don't agree with your points, and either way, the Tau mech probably won't exist once I finish the rework of mechs. Ground mechs are designed for PC, where flying is manually controlled; I'm not going to be changing their mechanics for mobile (which isn't a platform I care much for anyway).

**Comment by codiophile** [comment]
@Anuken I tried the desktop version and you are right, it makes a lot more sense there. I definitely got the feeling that the game has been designed for desktop and ported to mobile. A lot of other things that are annoying and tedious on mobile are much nicer and easier on the desktop version.

Why are you removing the Tau Mech? I like it. I just thought it was broken. I didn't understand why it wasn't repairing anything, but now I do.
