### ISSUE TITLE
Modded Walls do not stop bullets or enemy pathing

### ISSUE THREAD

**Issue by Angular-Angel** [Anuken/Mindustry#1233]
**Platform**: Linux 

**Build**: 100.1

**Issue**: Modded walls do not stop enemy bullets or pathfinding.

**Steps to reproduce**: Install mod: [3x3-and-4x4-walls](https://github.com/ZkyLB/3x3-and-4x4-walls)

Go to sandbox map. I chose caldera, but I had the same thing in a campaign map, so I don't think it matters.

Build walls around spawn point using modded 3x3 and 4x4 copper walls. Spawn enemies. Stay out of range as they shoot at you, their bullets will pass through the walls. Continue to stay out of range, they will walk over the walls as well. I tested with some other modded buildings from the [Vanilla Enhanced](https://github.com/HolyHades/VanillaEnhanced) mod, and those work normally.

**Comment by Anuken** [comment]
The walls in that mod are not walls, they're just non-solid blocks. Their type should be `Wall`, or at the very least they should be marked solid and destructible.

**Comment by Angular-Angel** [comment]
Yeah, I just found the pull request to fix that. Whoops, my mistake. -_-
