### ISSUE TITLE
Turning off socketinput does not stop listening to socketinput port.

### ISSUE THREAD

**Issue by moonheart08** [Anuken/Mindustry#1237]
**Platform**: *Linux server*

**Build**: *v100 Bytelogic*

**Issue**: *If the server has socketinput on, and you disable it, it does not stop listening on the socketinput port, meaning another server cannot try and use it.*

**Steps to reproduce**: *Enable socketinput, then disable it, and check what programs are listening on 6859*

EDIT: one moment enter key just decided to push issue early

**Comment by DeltaNedas** [comment]
thats TCP for you
does it still listen after ~a minute?
