### ISSUE TITLE
ICBM System?

### ISSUE THREAD

**Issue by anar4732** [Anuken/Mindustry#1238]
- Missle Lauıncher 
  -  Launches missiles to a location defined by player.
  - Player needs to select a Ground hit position for missiles. (useily enemy base)
  - Launch invertal: 60sec
  - Needs energy and fuel for launch.
  - Needs missile as item to launch it.
- Missle Builder
  - Builds missiles, The missile type will selected by player (like selection item type of filters)
   - Needs missile parts as item.
- Missile Part Factory
  - Makes missile parts from slicon, titanium, thorium etc.
- Refinery
  - Converts oil to fuel to use in missile launcher.
- EMP
  - Needs gaint ammount of energy for operate.
  - The gaeme needs logic system for this idea.
  - When its charged fully and recives logic signal sends EMP (Electro mahnetic pulse) to its area, removes all energy from all devices in its area, disables generator for x seconds and disables incoming or outcoming missiles in its area.
- Plated battaeys
  - EMP Proof
- Missile Antena
  - sends a logic signal when sees a missile in its area.
  - connect it to a EMP or anti-missile missile launcher for basic anti-missile system. 
- Missile
  - Builds in missile builder and needs carying to missile launcher to launch.
  - Makes medium sisze exploation on hit to gorund.
  - Baseic missile.
  - Needs 2000 energy and 200 fuel to launch.
- Radioactive Missile
  - When exploade the exploation area become radioactive for 80sec, every entity in this area takes damage.
  - Needs 2000 energy, and 200 fuel for launch.
  - Needs thorium for build.
- EMP missile
  - acts like an activated emp when git the gorund.
  - needs gaint energy (same as EMP) and 200 fuel to launch.
- Anti-missile missile
  - player can not select a hit position for this, this is just hits guided to other incoming missile and explode it (and itsself) without damaging world.
  - needs 1000 energy and 300 fueld to launch.
- Fire missile
  - starts gaint fire when explode.

**Comment by Anuken** [comment]
The issue tracker is not for feature requests.
~~this also sounds a whole lot like the Minecraft ICBM mod~~

**Comment by CA6** [comment]
Also ummm *cough*Oh No missile mod*cough*

**Comment by ZkyLB** [comment]
egg
