### ISSUE TITLE
Map names with spaces can't be hosted

### ISSUE THREAD

**Issue by jgonyea** [Anuken/Mindustry#1247]
**Platform**: 
Windows

**Build**: 
101.1

**Issue**: 
I'm unable to load a map with a space in its name (i.e. Ancient Caldera, lunar map 1, etc.)

**Steps to reproduce**:
- Run the bat file `run_server` (java -jar server.jar)
- Type `reload maps`
- Type `host Ancient Caldera`

** Expected result**:
Map is loaded 

** Actual result**:
`No map with name 'Ancient' found.
![image](https://user-images.githubusercontent.com/1057441/71309984-61def380-23dc-11ea-9408-5bbaee7b83a5.png)

**Comment by jgonyea** [comment]
I've also tried using single quotes, double quotes, backslashes and forward slashes, as well as attempting to put the arguments into the bat file on initial loading.

**Comment by Anuken** [comment]
Use underscores to replace spaces.

**Comment by jgonyea** [comment]
Does this only work on the included maps?  Underscores do not seem to work with custom maps.

**Comment by jgonyea** [comment]
Nevermind, I must have fat fingered something with the custom name.  Underscores are working.
