### ISSUE TITLE
Can't research mechanic pump in "the craters"

### ISSUE THREAD

**Issue by sulai** [Anuken/Mindustry#1254]
**Platform**: *Android*

**Build**: *101.1*

**Issue**: in the campaign, when playing "the craters" the description says "produce metaglass and cool towers and drills". Cool because coal is rare it's a great idea to venture to the lake and cool everything. I started to produce metaglass, but couldn't research pumps (which requires metaglass), because metaglass is not yet exported/launched, but only in the core. I'm not sure if this works as intended, but I think not because the description teases to try water-cooling. Maybe add "pumps" as a requirement to start that szenario? I'm not sure if it's possible to produce metaglass before that.

**Steps to reproduce**:
- start "the craters" without pumps being researched
- while in the szenario, it's possible to produce metaglass, but it's not possible to research/use pumps, because metaglass is not exported yet.

**Comment by DeltaNedas** [comment]
you need to launch then come back
you dont need water to play craters...

**Comment by Anuken** [comment]
You're supposed to try water cooling after you launch and research the pumps.
