### ISSUE TITLE
New units command 

### ISSUE THREAD

**Issue by grimsoul7** [Anuken/Mindustry#1259]
The purpose of the new units command is a new command for the unit in a way such as removing a block in the mind industry, so we can choose the building we want to attack. actually I want to make the mod command, I just don't know how to make java script

**Comment by Anuken** [comment]
The issue tracker is for reporting bugs, not asking for help. If you want modding help, join the Mindustry Discord linked to in the game or the README.

**Comment by grimsoul7** [comment]
I have joined

**Comment by DeltaNedas** [comment]
put it on feathub dont waste issue numbers

**Comment by DeltaNedas** [comment]
or ideally keep it to yourself

**Comment by ZkyLB** [comment]
pretty sure feathub is down
