### ISSUE TITLE
UI not scaling with HiDPI displays

### ISSUE THREAD

**Issue by Beefy-Swain** [Anuken/Mindustry#126]
I am using Debian and playing the HTML5 Version of the game works great, but playing the itch.io version results in an extremely zoomed out UI.

**Comment by Anuken** [comment]
Hi-DPI desktop monitors are currently completely unsupported. While it could be implemented, I don't have any such monitors to test it on.

**Comment by Beefy-Swain** [comment]
A UI scaling feature shouldn't be too hard to implement, I think.

I could be quite ignorant though.

**Comment by arnesacnussem** [comment]
tried to set this in
` uCore ((ScreenViewport) this.viewport).setUnitsPerPixel(0.6f); `
and
` fontScale = Math.max(Unit.dp.scl(1f) / 2f, 0.5f)*1.2f;`

on my laptop(1920*1080 15.6 inch) with maxed window
results're fine

but only one problem:
the "sectors" map are messed,and the position mapping are completely wrong(as pic ,the boder of region become red and my mouse not on it)
(also tried fullscreen,same problem)
![image](https://user-images.githubusercontent.com/9441546/47288376-708b1880-d628-11e8-85a2-139e90a8bd1d.png)

i'm not deeply check how all thing works,but the  in game UI scaled to an acceptable size.

**Comment by arnesacnussem** [comment]
> additional:lots thing broken: inventory and map editormaybe use "ScalingViewport" will better

seems a little re-position work,which should easy to you :)

**Comment by Anuken** [comment]
The UI system is not designed to work with different viewport pixel scales. 
To make this work properly, you'll need to change how UI scaled by the DP unit in uCore [here](https://github.com/Anuken/uCore/blob/master/src/io/anuke/ucore/scene/ui/layout/Unit.java#L22). This is what the mobile versions use for scaling.

**Comment by arnesacnussem** [comment]
now it's fine,great,excellent.(i'm back to gaming now
btw ,in Chinese(s) (both S and T),need a more bigger font scale.
maybe other language too,otherwise,the font are little bit hard to read.

what i'm using is(monitor properties above)
```
fontScale = Math.max(Unit.dp.scl(1f) / 2f, 0.5f)*1.6f;
baseCameraScale = Math.round(Unit.dp.scl(2));
```
and `scl = 1.6f;`

maybe there's 3 more slide bars in need

**Comment by arnesacnussem** [comment]
I added the settings maybe not graceful,but works (only tested on desktop).
pr link below:
[https://github.com/Anuken/Mindustry/pull/264](url)
[https://github.com/Anuken/uCore/pull/16](url)

**Comment by sparr** [comment]
@arnesacnussem your links came through malformed, the text is good but the hyperlink goes to https://github.com/Anuken/Mindustry/issues/url for both of them

**Comment by Anuken** [comment]
A UI scaling option has been added as of the latest commit. While the scale does not apply automatically, it should be enough for HiDPI users to get by. I still don't have anything to test automatic scaling on, so unless I get my hands on the right monitor I don't think this will ever fully be implemented.

**Comment by Luxray5474** [comment]
Will the android builds also have a scaling setting? I was one of the first people to complain about this as I am using a Chromebook KEVIN (1600p 235PPI). I would be more than happy to test it out once I buy a new stylus for this.

**Comment by Anuken** [comment]
Yes, there is an option for all platforms.
