### ISSUE TITLE
Water Extractor doesn't indicate boost effect.

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#1266]
**Platform**: *Linux*

**Build**: *5.0 Build 101.1*

**Issue**: *Water Extractor doesn't show boost effect.*

**Steps to reproduce**: 
When placing an overdrive projector next to a water extractor the water output is boosted, but it doesn't show. Instead the efficiency is still shown with 100 %.

This is crucial for example if you boost your steam gens and you can't quite see if the water extractor is within range of the overdrive or not.

Btw. I find the term "efficiency" misleading. Why not give us the real number like with drills - in form of _Extraction Speed_ or just _Extraction_?

**Comment by Quezler** [comment]
> subscribing
