### ISSUE TITLE
Unable to launch Mindustry on macOS Catalina

### ISSUE THREAD

**Issue by eyehol3** [Anuken/Mindustry#1268]
**Platform**: Mac

**Build**: 101.1

**Issue**: can't launch executable from itch.io, finder tells me that "The application “Mindustry” can’t be opened." I tried to fix the permissions but this did nothing. 
Building master myself and trying to launch it gives me an error message
[launch error.txt](https://github.com/Anuken/Mindustry/files/4007608/launch.error.txt)

**Steps to reproduce**: install latest java 8 + jdk and build a master

**Comment by DeltaNedas** [comment]
you launched it with `./gradlew desktop:run --no-daemon`???

**Comment by DeltaNedas** [comment]
also just a note, he is on Catalina and ive heard it broke lots of stuff

**Comment by Anuken** [comment]
Mindustry isn't signed and therefore does not support Catalina. I won't be fixing this anytime soon, as setting up automatic notarization is a very time expensive process that won't work well with my build system.

**Comment by DeltaNedas** [comment]
"cant be opened" is the most bs error instead of "its not signed oh no youll get HACKED"
