### ISSUE TITLE
how about that as a design?

### ISSUE THREAD

**Issue by laurentopia** [Anuken/Mindustry#1269]
I get confused between meltdown and spectre so I fired up photoshop...
![glowy](https://user-images.githubusercontent.com/26075468/71552751-73fdfa80-29b7-11ea-85cc-b48d52c0209c.jpg)
if someone wants it, here is the sprite sheet
![sprites](https://user-images.githubusercontent.com/26075468/71552777-c0493a80-29b7-11ea-8ff5-469ec0922f01.png)

**Comment by Anuken** [comment]
I prefer the older version, sorry.
