### ISSUE TITLE
Can't zoom while holding a belt, even though the rotate control has been remapped.

### ISSUE THREAD

**Issue by bcmpinc** [Anuken/Mindustry#1274]
**Platform**: Linux

**Build**: Steam build 101.1

**Issue**: The scroll wheel should allow the user to zoom in and out when the scroll wheel isn't mapped to anything else (by default the scroll wheel is also mapped to rotate).

**Steps to reproduce**: 
1. Start the game, reset the controls.
2. Start a new game. 
3. Notice that you can zoom in/out using the scroll wheel.
4. Select the conveyor belt.
5. Notice that scroll wheel does not zoom in/out, but rotates the belt instead.
6. Go to the menu and reconfigure rotation to be mapped to something other than the scrollwheel, for example U / J.
7. Select the conveyor belt again.
8. Notice that the scroll wheel does nothing.

**Desired result**:
At step 8 the game should zoom like it does in step 3.

**Comment by DeltaNedas** [comment]
hold ctrl and try again
[worksforme]

**Comment by Anuken** [comment]
Hold CTRL to zoom while holding a belt.
