### ISSUE TITLE
Moire-Like Patterns in Editor Mode

### ISSUE THREAD

**Issue by misterperson** [Anuken/Mindustry#1278]
**Platform**: Windows 10 64-bit (Desktop)

**Build**: 102.2

**Issue**: Moire-like patterns when zoomed out in editor mode. 

**Steps to reproduce**: Fill the grid with "Metal Floor 2" then use the scroll wheel to zoom out. Various rendering artifacts at different zoom levels
https://imgur.com/a/TDbGG2g

**Comment by RogueRedHawk** [comment]
Pretty sure this is intentional. It's basically rendering large sprites instead every little individual sprite to save resources, and only happens in this mode at extremely small zoom. Happens with wall too. Basically, this isn't an issue afaik.

**Comment by Anuken** [comment]
Happens due to the texture filtering. Not a bug.
