### ISSUE TITLE
Three sorter blocks cause jam

### ISSUE THREAD

**Issue by dkyleward** [Anuken/Mindustry#1287]
**Platform**: Windows

**Build**: steam build 102.3

**Issue**: Three sorter blocks in a row clog up the line.

**Steps to reproduce**: 

The image below is probably the easiest to understand. Two sorters work fine. The third jams up. Not sure if this is by design, but I certainly didn't expect it.

![error](https://user-images.githubusercontent.com/10221750/71605876-6fae1a80-2b3a-11ea-9545-9d076c2ebe59.png)

**Comment by ph3rr3t** [comment]
It is by design.  Limited to stop abuse of Sorter/Inverted mechanics.

**Comment by Anuken** [comment]
Not a bug for the reason listed above.
