### ISSUE TITLE
"Reset" button too short

### ISSUE THREAD

**Issue by GioIacca9** [Anuken/Mindustry#1289]
**Platform**: *PC*

**Build**: *102*

**Issue**: *With the italian translations, the "Reset" button in the "Controls" menu is too small.*
![immagine](https://user-images.githubusercontent.com/39232448/71617424-471a3500-2bbb-11ea-9d77-97154f001f60.png)

**Comment by DeltaNedas** [comment]
anuke shouldnt buttons resize themselves based on text width + padding
if not it may be something i could try in the future

**Comment by Anuken** [comment]
no, because every single UI element and button has size specified manually
