### ISSUE TITLE
gradlew.bat, "Could not determine the dependencies of task ':desktop:dist' " 

### ISSUE THREAD

**Issue by CKHammer** [Anuken/Mindustry#129]
So, I am making some modifications to the game, but I kept getting an issue, telling me "Could not determine the dependencies of task ':desktop:dist' ", I don't know if this is my problem, what causes it?

Edit: I typed in **.\gradlew.bat desktop:dist --scan**, it normally works fine.

The Full Console Log is here:
Compiling DEBUG build.
Download https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\Owner\Desktop\Mindustry\Mindustry-Master\Mindustry-master idk\desktop\build.gradle' line: 61
* What went wrong:
Could not determine the dependencies of task ':desktop:dist'.
> Could not resolve all files for configuration ':desktop:compile'.
   > Could not find com.github.MinnDevelopment:discord-rpc-release:-SNAPSHOT.
     Searched in the following locations:
         file:/C:/Users/Owner/.m2/repository/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/Owner/.m2/repository/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         file:/C:/Users/Owner/.m2/repository/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://repo.maven.apache.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://repo.maven.apache.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://repo.maven.apache.org/maven2/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://oss.sonatype.org/content/repositories/snapshots/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://oss.sonatype.org/content/repositories/snapshots/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://oss.sonatype.org/content/repositories/snapshots/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://oss.sonatype.org/content/repositories/releases/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://oss.sonatype.org/content/repositories/releases/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.pom
         https://oss.sonatype.org/content/repositories/releases/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--SNAPSHOT.jar
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/maven-metadata.xml
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--v3.3.0-gdb2ee1d-1.pom
         https://jitpack.io/com/github/MinnDevelopment/discord-rpc-release/-SNAPSHOT/discord-rpc-release--v3.3.0-gdb2ee1d-1.jar
     Required by:
         project :desktop > com.github.MinnDevelopment:java-discord-rpc:v1.3.2
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 13s

Thanks for reading this issue, I hope the issue can be solved in the soon. Cheers.

Edit again: seems like problem solved by changing the orginal to"v2.0.0" in the line"compile 'com.github.MinnDevelopment:java-discord-rpc:v2.0.0' ", but I still want to know why it solved the problem.

**Comment by Anuken** [comment]
Looking at the JITPack page, looks like the `1.3.2` build was simply too old and was removed. I've fixed the issue now.
