### ISSUE TITLE
please upgrade gradle to 6.0.1

### ISSUE THREAD

**Issue by vgaming** [Anuken/Mindustry#1291]
Is it possible to upgrade gradle to version 6.0.1? https://github.com/gradle/gradle/releases

Doing so would make the project build-able on openjdk 13.

**Comment by Anuken** [comment]
I recently downgraded to Gradle 5.0, as 6.0 causes project-wide warnings due to issues I can't fix, breaks F-Droid builds, and doesn't add any features I need. Java 13 support doesn't matter, since I use Java 8 for this project, and you should too.

**Comment by vgaming** [comment]
Understood, thanks for explaining.
