### ISSUE TITLE
 Campaign Fungal Pass: destroy all ennemy dosn't work 

### ISSUE THREAD

**Issue by mattpatt59** [Anuken/Mindustry#1292]
Hello , I have Mindustry Build 102 ( French version )

I destroy all enemy ( It's the objective for this mission) 

My mission continue . It's impossible to validate this mission. When I click to new wave I doesn't have any enemy.( I chose to click few time and I'm in wave 100 ) 

I chose to click to save and leave this mission , I can try again and check if I still have this problem . 

Thanks for the game
Matthieu

**Comment by mattpatt59** [comment]
I just try a second time I still have the problem 

<a href="https://zupimages.net/viewer.php?id=19/01/zndn.png"><img src="https://zupimages.net/up/19/01/zndn.png" alt="" /></a>

**Comment by mattpatt59** [comment]
My base 

<a href="https://zupimages.net/viewer.php?id=19/01/h94z.png"><img src="https://zupimages.net/up/19/01/h94z.png" alt="" /></a>

**Comment by Anuken** [comment]
Upgrade to build 102.1/102.3.

**Comment by mattpatt59** [comment]
Thanks it's works
