### ISSUE TITLE
Naming Bug

### ISSUE THREAD

**Issue by Gabgab2003** [Anuken/Mindustry#130]
You can make your Username 127 chars long and still join servers(128 throws an error) by editing C:\Users\\%username%\\.prefs\\io.anuke.moment. Furthermore you can make your name invisible by setting the color value to -0000000000.
![image](https://user-images.githubusercontent.com/33293877/41059731-ad1061ba-69cd-11e8-9a09-4fdeda5b508d.png)

**Comment by Anuken** [comment]
As of the latest current 4.0 commit, the server now strictly validates length of usernames, chat messages and clear tags in names. Closing.
