### ISSUE TITLE
Scripted blocks are missing theirs descriptions and names

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#1304]
**Platform**: *All*

**Build**: *102.3*

**Issue**: *Scripted blocks are missing theirs descriptions and names*

**Steps to reproduce**: *Import a mod with a scripted block.*

**Comment by DeltaNedas** [comment]
?????? works on my machine
steps to prove you wrong
1. put localisation in bundles
2. look it works

**Comment by DeltaNedas** [comment]
if you want to use custom name/description for scripts use localizedName and description = Core.bundle.format/get
