### ISSUE TITLE
F-Droid Build Fails

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#1308]
Looks like the F-Droid [build](https://f-droid.org/wiki/page/io.anuke.mindustry/lastbuild) fails because of my addition of `DexClassLoader`-based JS scripting, among other things.

**Comment by DeltaNedas** [comment]
works on my machine (at least)

**Comment by DeltaNedas** [comment]
![Screenshot_03:34:25](https://user-images.githubusercontent.com/39013340/71705952-f2a0d080-2dd9-11ea-982d-b1b89548c14d.png)
wait a second

**Comment by Quezler** [comment]
:ohno:

**Comment by rnauber** [comment]
Hi,
in order to get Mindustry to build again on F-Droid ( https://f-droid.org/wiki/page/io.anuke.mindustry/lastbuild_102 ), I opened https://gitlab.com/fdroid/fdroiddata/merge_requests/6172 and 
#1359 .

**Comment by DeltaNedas** [comment]
your pr was already stupidly attempted by me, DS_Store is there for a reason

**Comment by DeltaNedas** [comment]
![man just give up](https://user-images.githubusercontent.com/39013340/72208587-17610c00-349c-11ea-8654-ac7f93f29ff7.png)

**Comment by rnauber** [comment]
Oh, I did not know that :) Then I will tell F-Droid to just ignore this file...

**Comment by rnauber** [comment]
> ![man just give up](https://user-images.githubusercontent.com/39013340/72208587-17610c00-349c-11ea-8654-ac7f93f29ff7.png)

there was some LINT in the machinery ...

**Comment by Anuken** [comment]
Removed `DS_Store`.

**Comment by rnauber** [comment]
Progress!
The scan of the sources pass and the build server has an up to date gradle now. 
The current error is:
https://f-droid.org/wiki/page/io.anuke.mindustry/lastbuild

```
/home/vagrant/build/io.anuke.mindustry/core/src/mindustry/world/blocks/storage/CoreBlock.java:15: error: package mindustry.gen does not exist
import mindustry.gen.*;

```

@Anuken Do you know what is going on there?

**Comment by Quezler** [comment]
@rnauber probably fixed by #1397, we'd have to await the results of the next fdroid lastbuild output

**Comment by Anuken** [comment]
@rnauber Is there a full log somewhere? The real error is truncated.

**Comment by rnauber** [comment]
Here are my local build logs:
https://hastebin.com/oqeliteyoq.py

**Comment by rnauber** [comment]
Well, i think I know how to fix it:
https://gitlab.com/fdroid/fdroiddata/merge_requests/6214

**Comment by Anuken** [comment]
The DS_Store file should be completely gone from the repository by now. Does your change really fix the error?

**Comment by rnauber** [comment]
Yes, but v102 still includes the DS_Store and the build fails when it is removed...

**Comment by Quezler** [comment]
~~time to release v103 then~~ 🤔

**Comment by licaon-kter** [comment]
/close this

https://gitlab.com/fdroid/fdroiddata/merge_requests/6236

**Comment by rnauber** [comment]
@licaon-kter thanks, that looks better! 
Hopefully, we will have an up to date Mindustry on F-Droid soon!

**Comment by rnauber** [comment]
Finally!
https://f-droid.org/wiki/page/io.anuke.mindustry/lastbuild_103

> Build Log
> Build succeeded

**Comment by DeltaNedas** [comment]
OBAMA is BACK
:crab:crab::crab:
