### ISSUE TITLE
Audio Clicking when Too Many Sounds Are Playing

### ISSUE THREAD

**Issue by misterperson** [Anuken/Mindustry#1310]
**Platform**: *Windows 10 (64-bit)*

**Processor**: Intel Core i5-4670k @3.40GHz (4 cores)

**Build**: *102.3*

**Issue**: When too many sounds are played at the same time, a constant loud clicking occurs, possibly due to low-level audio engine.

**Steps to reproduce**: Have a few dozen dagger mechs fire at the same time. (e.g. a swarm of them during a late-game wave)

**Comment by ZkyLB** [comment]
this has never happened to me before.
its probably your speaker or your audio

**Comment by misterperson** [comment]
[audio_bug_shown_and_audiolized.zip](https://github.com/Anuken/Mindustry/files/4018586/audio_bug_shown_and_audiolized.zip)
![clipping](https://user-images.githubusercontent.com/1425135/71715463-4e615e80-2dc6-11ea-9dbd-dca819751d07.png)

The audio graph image shows the clipping occuring from recorded audio via Windows WASAPI. The ZIP contains the raw audio and some recording from OBS to show what is on-screen generating the sound.

**Comment by Anuken** [comment]
When many sounds are played at once, some others have to be interrupted and some have to be stopped. Won't fix.

**Comment by misterperson** [comment]
Idea:
have two active sound lists.
The first list is the normal sound list. When it gets full, start popping the sounds with the least lifetime and placing them in the second list. In the second list, the sound is given a fade out effect over either the remaining lifetime of the sound or some smaller time increment.

When the second list has entries, apply a very short fade-in effect to sounds that are added to the main list.

When the second list is full, start interrupting sounds from the most faded out in that list.

The fade effect is exponential. Sounds entering the list should slowly ramp up and sounds leaving the list should quickly decay away.

These mitigations would reduce the amount of clicking caused.

Alternatively, if too many of the same sound is being generated, maybe don't play any more when the list is full.

**Comment by misterperson** [comment]
I poked around in ALAudio and the `simultaneousSources` needs to be exposed to the engine somehow ( I couldn't find where ALAudio gets initialized). If someone can point this out to me, I can tinker with the code just above the middleware.
