### ISSUE TITLE
Clicking Workshop from Main Menu doesn't do anything

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#1318]
**Platform**: *Linux*

**Build**: *steam build 102.3*

**Issue**: *When I click on the Workshop entry on the main menu nothing happens. I suppose the steam workshop should open then?*

**Comment by DeltaNedas** [comment]
does shift tab work, is steam api loaded?

**Comment by Anuken** [comment]
Works fine for me on Linux; if it doesn't for you, your Steam overlay must be disabled or broken on Linux. If Steam API wasn't enabled, the workshop button wouldn't show up at all.

**Comment by famo** [comment]
Ah, thank you!
You are right steam overlay wasn't enabled, works now.
