### ISSUE TITLE
PvP: New Players are assigned to defeated Team

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#1320]
**Platform**: *Linux*

**Build**: *steam build 102.3*

**Issue**:
*When a team got his core destroyed, new players who join the match are still assigned to this team.*
In this case red:
![Screenshot_20200104_193850](https://user-images.githubusercontent.com/692646/71771021-fac15300-2f34-11ea-9568-0d4530b017d0.png)

**Steps to reproduce**:
*Attached is a savegame from the game of the screenshot. I didn't host this game and don't know the platform from the host. However it also happened in games hosted by me, where the core where destroyed by griefers with reactor explosions (might be here also the case?).*

[Bug.msav.zip](https://github.com/Anuken/Mindustry/files/4022363/Bug.msav.zip)

**Comment by famo** [comment]
@Anuken 
This Issue is still in 5.0 Build 103.

![Screenshot_20200126_184955](https://user-images.githubusercontent.com/692646/73139631-36e95e80-4070-11ea-95ef-27f56c7f4217.png)

[bug2.msav.zip](https://github.com/Anuken/Mindustry/files/4113993/bug2.msav.zip)

**Comment by Anuken** [comment]
*Actually* fixed and tested now.

**Comment by linglan512572354** [comment]
It is still in v104.1.
The default TeamAssigner will assign player to an active team which has the least player. But the crux team is always active.  
![QQ截图20200212183608](https://user-images.githubusercontent.com/9363761/74327138-98c2fb80-4dc6-11ea-94db-57a537fc44cd.png)

**Comment by Anuken** [comment]
No, after killing the red team's core, it's no longer displayed as active.
![image](https://user-images.githubusercontent.com/10100000/74352366-62658c00-4d86-11ea-80ab-c1de169c979f.png)

In the screenshot, I kill the crux team's core, and then check whether it's active. This returns `false`, and the team isn't displayed in the active list.

**Comment by linglan512572354** [comment]
You are right, the red team will become inactive when its core was destroyed, and the game will end correctly. 

But in some PVP maps which didn`t have any red tile or unit, the assigner also put players to the crux team. That is the case I mentioned.
( Because a map without a red core can be host by the server although attack mode is true . )

Famo`s situation is another case.
In function updateEnemies (core/game/Teams.java) active red team if waves on. That means the game can reactive the red team sometimes. I think that maybe fixed.

**Comment by linglan512572354** [comment]
The crux team is active when other teams register their core in word initialization.  It does not make sense as no red core on the map. And some players can`t join the game.

**Comment by Anuken** [comment]
That's a different issue than described in the original post.
