### ISSUE TITLE
The game always crashes after a few minutes to desktop.

### ISSUE THREAD

**Issue by Lau996** [Anuken/Mindustry#1321]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required.*
102.3

**Issue**: *Explain your issue in detail.*
I can play the game but after a few minutes it always crashes to my desktop. When i downloaded the version from the website it worked fine but the steam version keeps crashing.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
[hs_err_pid11720.log](https://github.com/Anuken/Mindustry/files/4022511/hs_err_pid11720.log)
[hs_err_pid6248.log](https://github.com/Anuken/Mindustry/files/4022512/hs_err_pid6248.log)
[hs_err_pid13332.log](https://github.com/Anuken/Mindustry/files/4022513/hs_err_pid13332.log)
[hs_err_pid11208.log](https://github.com/Anuken/Mindustry/files/4022514/hs_err_pid11208.log)
[hs_err_pid13676.log](https://github.com/Anuken/Mindustry/files/4022515/hs_err_pid13676.log)
[hs_err_pid8428.log](https://github.com/Anuken/Mindustry/files/4022516/hs_err_pid8428.log)
[hs_err_pid4504.log](https://github.com/Anuken/Mindustry/files/4022517/hs_err_pid4504.log)
[hs_err_pid9644.log](https://github.com/Anuken/Mindustry/files/4022518/hs_err_pid9644.log)
[hs_err_pid12056.log](https://github.com/Anuken/Mindustry/files/4022519/hs_err_pid12056.log)
[hs_err_pid11044.log](https://github.com/Anuken/Mindustry/files/4022520/hs_err_pid11044.log)

**Comment by Lau996** [comment]
I also already reinstalled the game and java multiple times and Java is also installed at C:\Program Files\Java

**Comment by DeltaNedas** [comment]
> windows-amd64 compressed oops
?

**Comment by Anuken** [comment]
All these crashes seem completely unrelated; I would guess that Steam is interfering with the game in such a way as to mess up the Java process. I can't fix this.

**Comment by DeltaNedas** [comment]
yea it works on my machine
