### ISSUE TITLE
Multiplayer desync issue with manually pickups from conveyer belt

### ISSUE THREAD

**Issue by Kaesemuffin** [Anuken/Mindustry#1322]
**Platform**: Windows

**Build**: 102.3

**Issue**: If someone picks up ores from belt while for example a machine clogged not all clients are "getting the update". This leads for example for incorrect recource counts for all clients or even someone still sees a clogged conveyer belt while the host sees it running smoothly.

**Steps to reproduce**: Play Multiplayer/Coop, clogg a lane with coal and copper to core. Let the client pick up coal in order to get the lane running again.

We mostly encountered this bug in mid/late game in a session. Somnetimes a client had crash to menu.

** Just read in https://feathub.com/Anuken/Mindustry that there is a /sync command. But idk if this should be used all the time.

**Comment by Anuken** [comment]
Conveyors are not synced across the network; use the /sync command to update their items.

**Comment by Kaesemuffin** [comment]
Hey Anuken,

please enlighten me. Why is this not an issue?
Forcing players to use a "sync" command seems to be a "work arround" and not a valid solution.

Thanks and have a nice day.

**Comment by Anuken** [comment]
There is no good solution. Conveyors cannot be made deterministic, and periodic syncing was already attempted, with disastrous results.

**Comment by ZkyLB** [comment]
maybe like only sync blocks that are visible to the player?

**Comment by Anuken** [comment]
That's exactly how it used to work, and it lead high network usage, lag, and items jumping around on conveyors and/or disappearing due to desyncs elsewhere.
