### ISSUE TITLE
No scrap in custom games

### ISSUE THREAD

**Issue by dkyleward** [Anuken/Mindustry#1328]
**Platform**: Windows 10

**Build**: Steam 102.3

**Issue**: No scrap metal in custom games

**Steps to reproduce**: I've started a few custom games on various maps, but none of them have scrap. I like to use custom games to create/test designs, and being able to balance using an actual scrap drill would be great.

**Comment by Anuken** [comment]
Scrap isn't considered an essential resources like the others, so you'll have to add it to the maps yourself or play on a custom game. I don't think it should be generated by default.
