### ISSUE TITLE
Ressource Display blocks building stuff

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#1332]
**Platform**: *Windows 10*

**Build**: *102*

**Issue**: *Every Overlay displaying resources blocks building stuff.*

**Steps to reproduce**: *Klick on your core to show the resources then try to build something on the space where the overlay is*
greetings from Sir Silicon

**Comment by Anuken** [comment]
You're not supposed to be able to build or tap over UI elements. This is intentional.
