### ISSUE TITLE
Technologies are incomprehensibly cheap (phantom drones - lead part of price requires only 420 of it)

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#1342]
**Platform**: Linux

**Build**: 102.3

**Issue**: In the campaign technologies are basically free. Once you produce some resource you have so huge amounts of it that technologies are basically free. For example I have 56k copper, 30k lead. Phantom Builder Drone Factory unlock requires 420 lead.

Balance is so weird (I either never have even seen the resource, or I have enough to not worry about the price) and I research technologies so quickly that I suspect that 10x multiplier went missing or something else weird happened.

I hope that it is not a feature request, sorry if it counts as one.

**Steps to reproduce**: I started campaign and played levels as long as required to unlock new parts of the campaign,

**Comment by DeltaNedas** [comment]
its 6(cost) + 30 not 10x
drone factory costs 35 lead, so it takes 6x35 + 30 lead to research

**Comment by Anuken** [comment]
All the costs are automatically calculated based on item cost; nothing strange happened here. I could improve prices by apply a slightly curve to the price by adding a power to the amount, but that won't really fix this issue. In the future, costs could be take into account tree depth and item rarity, but that's something for 6.0 and above.

**Comment by matkoniecz** [comment]
Sorry for opening this here, I thought that it is bug. I opened https://feathub.com/Anuken/Mindustry/+604 instead
