### ISSUE TITLE
Tech tree cluttered when using mods.

### ISSUE THREAD

**Issue by xzarfs** [Anuken/Mindustry#1348]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *102.3*

**Issue**: Mods that add new content to the campaing tech tree makes it very cluttered. 
This makes it hard to see and operate with the upgrades.

 ![mindustry](https://user-images.githubusercontent.com/59253058/72167736-65124180-33d4-11ea-937e-1075bb011cc3.png)

**To fix it move the upgrade buttons further from the parent upgrade making there more space.**

**Comment by Eldeston** [comment]
What mod is that btw? I'm interested 0.o

**Comment by CA6** [comment]
many. like more than three good ones

**Comment by Anuken** [comment]
Fixed.

**Comment by DeltaNedas** [comment]
opore mod is gone
