### ISSUE TITLE
Problem with Scatters

### ISSUE THREAD

**Issue by Vtas1** [Anuken/Mindustry#1349]
**Platform:** Android 5.1.0
**Build:** 102.3
**Issue:** In enemy core destroying Campaign maps (Fungal Pass, Salt Flats, Overgrowth), Scatters fire both at ground and air units (including your  control ship too), making the 2 last maps (SF, OG) insanely hard to beat. 
**Steps to reproduce:** Go to a core destroying Campaign map, then first go with a ground mech (e.g. Alpha) near a Scatter turret. It will fire at you. Same happens if you build ground units as Crawlers, Titans, Fortresses, etc.; and when they try to attack Scatters, Scatters fire at them. In Fungal Pass, a few Scatters were not a big issue, but it is really annoying and makes things too difficult in Salt Flats and Overgrowth. As I know, this issue is not present in PC versions or a few months ago it wasn't. (Watch the end of this: https://m.youtube.com/watch?v=jRmjI3dyZ_4.)

**Comment by Anuken** [comment]
![recording1578673931](https://user-images.githubusercontent.com/10100000/72169345-efd74a00-339c-11ea-818f-7d0093e85076.gif)
![recording1578673942](https://user-images.githubusercontent.com/10100000/72169347-efd74a00-339c-11ea-81de-269e0e02ed82.gif)
![recording1578674001](https://user-images.githubusercontent.com/10100000/72169385-0382b080-339d-11ea-8241-53357a9750d0.gif)

Nope. This doesn't happen to me.

**Comment by Vtas1** [comment]
>
> Nope. This doesn't happen to me.
>
Could you please explain what is the second gif is about? It seems when the
mech is moving, Scatters fire at it. Have you also tested the units?

**Comment by DeltaNedas** [comment]
when a mech boosts it is treated like an air unit

**Comment by DeltaNedas** [comment]
in the third one, anuke doesnt boost so scatter doesnt shoot at it

**Comment by Anuken** [comment]
> Could you please explain what is the second gif is about? It seems when the
mech is moving, Scatters fire at it.

It's not just *moving*, it's flying in the air, which makes it an air target. As soon as I land, the scatters stop firing.

> Have you also tested the units?

The last gif shows scatters ignoring several units that walk right past it.

**Comment by Vtas1** [comment]
Sometimes they do and sometimes they do not.

**Comment by Vtas1** [comment]
Then I understand the case. Some time ago the ground mechs could not fly.
Thank you!

**Comment by Vtas1** [comment]
When I was in one place, it was easy to remove a Scatter. I will try to
beat these maps then.
