### ISSUE TITLE
Swarmers vs sorters. Sorters won

### ISSUE THREAD

**Issue by Lolicon-Mindustry** [Anuken/Mindustry#1353]
**Platform**: Android 8.0

**Build**: 102.3

**Issue**: on the screenshot

**Steps to reproduce**: built pixel art in front of enemy swarmers on the server - they attack my cat - cat, made by sorters is safe
![Screenshot_20200110-163525](https://user-images.githubusercontent.com/59752736/72196429-b811e600-3420-11ea-8450-79dadf323218.jpg)

**Comment by Lolicon-Mindustry** [comment]
My first bug report

**Comment by Anuken** [comment]
This is (most likely) caused by the server running an older version where enemy turrets don't target blocks. Will reopen if it still happens next build.
