### ISSUE TITLE
Blue and purple belts speed is actually 10 instead of 12

### ISSUE THREAD

**Issue by imTheSupremeOne** [Anuken/Mindustry#1355]
**Platform**: Windows 10

**Build**: 102.3 steam

**Issue**: I had a very bad time with things not feeding enough and I ended up testing blue and purple belts with actual stopwatch. So to fill box with 300 items it took 31.09 and 30.39 retard seconds to fill in feeding from blue and purple belts, which is ~30 sec for 300 items, and if the speed was 12 i/s it should only take 25 seconds to fill. I also did a test with 2 resource spawners per belt and it still took 30.62 seconds, so the problem is in belts.

**Steps to reproduce**: Stopwatch ^^;

**Comment by DeltaNedas** [comment]
stop watch is not reliable
use that older pr that shows resource speed on a conveyor

**Comment by matkoniecz** [comment]
What is your FPS?

**Comment by ph3rr3t** [comment]
he's not wrong, titanium & armored belts do only pass about 10 items/s instead of the 12 shown on their info cards.  This is one of those things that gets tested over and over as new people play the game.

**Comment by imTheSupremeOne** [comment]
> stop watch is not reliable
> use that older pr that shows resource speed on a conveyor
> What is your FPS?
I had 59-60 FPS during all tests. And what is pr?

**Comment by DeltaNedas** [comment]
pull request, anyways its fixed now
