### ISSUE TITLE
BE testing server

### ISSUE THREAD

**Issue by geoffrey1900** [Anuken/Mindustry#1357]
**Platform**: android

**Build**: BE-6731

**Issue**: the BE testing server doesnt pop up in join game

**Steps to reproduce**: open join game

**Comment by Quezler** [comment]
it won't show up when its offline, compared to server(s) you add to the list by hand:
<img width="269" alt="Screen Shot 2020-01-11 at 14 46 42" src="https://user-images.githubusercontent.com/3179271/72205259-31d9bc00-3481-11ea-80e8-dc93ea559348.png">

**Comment by Anuken** [comment]
It's offline now.

**Comment by geoffrey1900** [comment]
> **  _ `mkay` _ **
