### ISSUE TITLE
SPEEEEEEEEEN glaive

### ISSUE THREAD

**Issue by FLuuuuFYNES** [Anuken/Mindustry#1361]
**Platform**: *Android.*

**Build**: *102.3.*

**Issue**: *it took 10 whole seconds to start the glaive ship pad,.*

**Steps to reproduce**: *Sandbox server mindustry . ddns . net : 2000, 11:02pm HST/-10gmt, using random glaive pad after spawning.*

**Image**:*"SPEEEEEENFox64".*
![Screenshot_20200111-230607](https://user-images.githubusercontent.com/59790524/72216659-252c8680-34c8-11ea-83c2-e8896b942d8c.png)

**Comment by Quezler** [comment]
define "start"

**Comment by Anuken** [comment]
I can't reproduce this, and it seems to only be happening to people at extremely low FPS. I won't be wasting time fixing this when a movement rework is going to be implemented in 6.0 anyway.

**Comment by ado1928** [comment]
Add deltatime to these things?

**Comment by Anuken** [comment]
It already uses delta time, and works fine for me at 15 FPS.
