### ISSUE TITLE
[Android A50] Screen glitch makes game unplayable

### ISSUE THREAD

**Issue by ILuvMazes** [Anuken/Mindustry#1362]
**Platform**: Android A50

**Build**: 102.3

**Issue**: The fullscreen mode keeps toggling on and off while launching and using the app.

**Steps to reproduce**: I just got this phone new and decided to play some Minindustry, when I happened upon this glitch. Changing the settings in the phone to force fullscreen and auto mode does not help at all. The constant moving of side to side on the app makes the game unplayable.

**Files**: 
![ezgif-2-5f23c36110b0](https://user-images.githubusercontent.com/13723077/72220789-32756e00-35b9-11ea-8518-04f780ea8fa3.gif)

**Comment by DeltaNedas** [comment]
works on my machine, not mindustrys fault probably

**Comment by Anuken** [comment]
This is an Android bug. Won't fix.
