### ISSUE TITLE
Turret orientations are desynchronized from the server

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#1366]
**Platform**: Android

**Build**: 102.3

**Issue**: Turrets don't shoot in the same direction on the client, ghost bullets destroy enemy walls as seen here:
![oh no](https://user-images.githubusercontent.com/21104932/72233677-cfe09a00-35d9-11ea-8f3d-e4e8191ffe92.png)

**Steps to reproduce**: Two or more potential targets on a turret.

**Comment by Anuken** [comment]
Most likely caused by combinations of #1372 / #1353
