### ISSUE TITLE
Ez win on Fungal pass

### ISSUE THREAD

**Issue by ImBadAtMakingNames** [Anuken/Mindustry#1367]
102.3 Build on mac downloaded from owner's website. 

You can go over walls and defeat the opponent by destroying the drills that provide ammunition and draining the scatters of said ammo. Then you destroy the cores

**Comment by ZkyLB** [comment]
ok

**Comment by DeltaNedas** [comment]
fuck man i had no idea you could cheese the cheesable attack map

**Comment by Anuken** [comment]
Not a bug.
