### ISSUE TITLE
Players are assigned to red team without core.

### ISSUE THREAD

**Issue by linglan512572354** [Anuken/Mindustry#1371]
**Platform**: Android

**Build**: v102.3

**Issue**: In some old PVP map. The red team act as wild defenses. It doesn\`t have any core. But in the newest version, because the wave team is always active, players will be assigned to the red team, although this team doesn\`t have any core.

**Steps to reproduce**: In these maps, players will be assigned to the red team, but they can`t respawn.

I add some code in Mindustry\core\src\mindustry\core\NetServer.java:56 in the definition of  "TeamAssigner assigner"
like this 
‘’‘java
                if(!data.hasCore())
                {
                    count = Integer.MAX_VALUE;
                }
'''
It works, but I worried it not the right way to resolve this problem.

**Comment by Anuken** [comment]
Duplicate.
