### ISSUE TITLE
I killed enemy core and game hasn't finished

### ISSUE THREAD

**Issue by imTheSupremeOne** [Anuken/Mindustry#1373]
**Platform**: Windows 10

**Build**: 102.3 steam

**Issue**: My explosive bots killed enemy core, but game didn't finished. I wasn't watching them exploding core, I was building the base, and some time later I decided to check how enemy defence doing, and the place where core supposed to be was destroyed square.

Explosive bots are pathfinding to that spot where was enemy's core and if they reach it they stuck there even though there are enemy structures and some turrets nearby.

It's a game campaign, map "Salt Flats".

![image](https://user-images.githubusercontent.com/13508453/72259961-5917c100-361a-11ea-8164-1a4e1441d1f7.png)

**Comment by imTheSupremeOne** [comment]
Also, after relaunching game, enemy units aren't spawning at new waves, and my units are now completely freezed.

**Comment by Anuken** [comment]
Duplicate.
