### ISSUE TITLE
Middle mouse is not detected

### ISSUE THREAD

**Issue by Zzombiee2361** [Anuken/Mindustry#1374]
**Platform**: Linux

**Build**: 102.3

**Issue**: Clicking middle mouse won't trigger its action (default: pick block)

**Steps to reproduce**:
1. Try to pick block (which is middle mouse by default) and realize it doesn't work
2. Change other control to middle mouse, and the changed control won't work

PS: My mouse middle click is definitely working

**Comment by gm907** [comment]
Small thought, confirm the blocks you're trying to pick are unlocked in the tech tree

**Comment by Anuken** [comment]
Works for me on Linux. How do you know your middle mouse button works?

**Comment by Zzombiee2361** [comment]
Cause I can rebind middle mouse to other control? Pick block is definitely not the problem. I rebind it to other key and it works.

**Comment by DeltaNedas** [comment]
yea works on my machine man
use x not wayland hat could cause it, wayland is unstable

**Comment by Anuken** [comment]
Unless you can identify what causes it to be ignored in certain scenarios, this is very likely an issue with your OS or configuration. Even if you can verify that middle clicking *down* is functional, that doesn't mean that the game is getting events for it being released. 

This is the first time I've heard of middle clicking being an issue, after thousands of bug reports and different systems. With no way to reproduce it, there's nothing I can do.

**Comment by DeltaNedas** [comment]
use `xev`?

**Comment by Zzombiee2361** [comment]
This is the bug in action
![output](https://user-images.githubusercontent.com/37852137/72344844-d1f34780-3704-11ea-92df-8051b642c482.gif)
As you can see, middle click is the problem and the game detect it (in control settings anyway). How can I debug this? I tried wiping game data and using older (build 100) version and it still not working. I'm using KDE Neon 5.17 on Xorg. And yes, xev does detect my mouse middle click.
