### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CalenLoki** [Anuken/Mindustry#138]
Hope it's not the worst place to drop it ;)
![crashreport](https://user-images.githubusercontent.com/41125046/42589602-d387d94c-8541-11e8-8b2e-de0c9591c3e3.jpg)

**Comment by TheChosenEvilOne** [comment]
is this the latest bleeding edge?
if yes: please do not report any bugs or crashes it is broken
if no: probably fixed already

**Comment by CalenLoki** [comment]
Thanks for reply.
Latest. So I won't send any more, even though game is asking so nicely.

BTW it was after building overflow gate without alternative exit. With conveyor on the side it doesn't crash.

**Comment by Anuken** [comment]
Fixed.
