### ISSUE TITLE
Custom Sounds (and normal sounds) not playing

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1386]
**Platform**: *Android and Windows 10*

**Build**: *102.3*

**Issue**: *Commonly, sounds tend to become mute. It's probably a device limitation of just not playing the sound if lots are playing at once, but at the same time, I don't think so. If the muteness is from tons of sounds playing, why would the missile launch sound in my mod not play if it's the only sound playing.*

**Steps to reproduce**: *This seems to happen more often with custom sounds. I should probably check my code just in case, so I'll do that after commenting.*

**Comment by MEEPofFaith** [comment]
Ok, so the code is correct as far as I'm concerned (unless there was a syntax change with sounds I'm unaware of).

**Comment by MEEPofFaith** [comment]
Maybe the sounds are too long? I mean, the missile launch sound is 4 seconds long...

**Comment by Anuken** [comment]
There is a limit of 16 sounds playing at once; even if the sound itself is silent, any sound being played after the limit is reached will cause interruptions and lack of sound.

**Comment by sk7725** [comment]
Sometimes sounds just refuse to play. When i destor a single block or click on a node, it doesnt play the *bok* or *click*. But when I retry it(noticing the silence and breaking another block or clicking in another node) the sound plays.
I am almost certain less that 16 sounds were playing at that time...

**Comment by Anuken** [comment]
Keep in mind that the 16 sound limit applies regardless of volume. Even if you have a few blocks emitting ambient noise at 0.001% volume, that still counts as a sound. The same applies to, say, a sound that's just 30 seconds of silence. With mods, it's hard to tell.

**Comment by CA6** [comment]
Yeah 16 sounds if more is requested to play you get ear rape static or nothing at all

**Comment by Anuken** [comment]
Closing this, as it won't be changed until a new sound system is implemented.

**Comment by MEEPofFaith** [comment]
if 16 sounds are the limit...
then 16 conveyer belts break the limit.
