### ISSUE TITLE
Free boost mender, bug

### ISSUE THREAD

**Issue by TotalFoc** [Anuken/Mindustry#1389]
Platform: android 
Build: 102.3
Issue: in the hex server i had a boost mender without having to pay for it it was free
![Screenshot_20200115-223015_Mindustry](https://user-images.githubusercontent.com/57732282/72470676-d7768d80-37e9-11ea-86c6-291d416a31a9.jpg) and is not useful, at least for me

**Comment by DeltaNedas** [comment]
no it just means packet loss probably, server didnt build it

**Comment by Anuken** [comment]
I'm going to need specific circumstances and reproduction steps. A random occurrence on a public server could have happened for any number of reasons.

**Comment by Quezler** [comment]
i'm just going to make the assumption that he did place the mender himself, but that he is surprised as to why its glowing as if it were phased without any phase fabric supplied, not knowing that small menders use silicon to boost with, which is fed by the rev pad 🤔

**Comment by ado1928** [comment]
Its boosted by silicon from that unloader

**Comment by TotalFoc** [comment]
I do not use  boost mender for anything, i use so much mender projector that i forgot about it
