### ISSUE TITLE
Meltdown Laser Mechs not firing in Mobile Controls

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#1391]
**Platform**: *Android*

**Build**: *102.3*

**Issue**: *Laser(Meltdown lasers, not the Lanser lasers) Weapons for Mechs do not fire in mobile controls.*

**Steps to Reproduce**: *Downlode a mod that has a custom Mech using laser type weapons. Unless you turn on 'Mouse and Keybord controls', the Mech will refuse to autoaim or shoot.*

**Comment by GeneralsDuty** [comment]
I've also experienced this, Opore has a ship called "impending doom" which fires meltdown beams.
![Screenshot_20200116-200331185 (1)](https://user-images.githubusercontent.com/57879662/72515315-68f20800-389b-11ea-9265-7e3a52837a03.jpg)
[https://youtu.be/4qmSSwm7BzA - Video of events.](https://youtu.be/4qmSSwm7BzA)
While I'm here, is the aiming with laser weapons still affected by ship sway movement?

**Comment by Anuken** [comment]
Laser bullets aren't supposed to be used as mech weapons. They don't have proper range configuration.
