### ISSUE TITLE
Modded Items recognition error

### ISSUE THREAD

**Issue by itrynoxl** [Anuken/Mindustry#1394]
**Platform**: Android

**Build**: 102.3

**Issue**: I was trying out mods for the first time (starting about a week ago) using Modustry Modpack by ZoMadeStuff which is fun and generally worked great. Eventually I ran into an issue where when I would discover a new material/item that was not launchable in the core, it failed to register that I had discovered the material; this meant that it didn't show up in the item list, but more importantly, it meant that the item can't be sorted or emptied.

**Steps to reproduce**: This first occurred on the Evosaki Islands map, after I built a deep digger, which produced the the problem with raw ore, and other items. This non-recognition problem was repeated with gold powder and the various oil bottles (non-launchable raw reverie crystals were recognized, as was the launchable pure gold and plastic discovered later). This was repeated on different maps (the craters and goldsand valley), after un- and. re-installed the mod, and with the oil barrels using only What42Pizza's Production mod. It can be noted that in custom game mode the unrecognized items are part of the full complement of items and can be properly sorted, this issue only seems to occur in campaign mode.

**Comment by Anuken** [comment]
Testing with some gold sand, gold powder and a mechanical drill, I don't have this issue. Once the item is mined, it correctly displays an item unlock dialog.

**Comment by Anuken** [comment]
As this doesn't happen in my tests, I need steps for making this happen with a specific mod, map, block and item, where an item doesn't unlock after it is mined. It's unclear if this even still happens with the latest versions. Closing until further notice.

**Comment by DeltaNedas** [comment]
actually ive been able to reproduce it with mindustry production mod by what42pizza (with a crafter, not a drill)
1. add oil block that converts oil into different types
2. add liquid source for oil and conduits for output
3. add a liquid filter and infinite power source
4. save map and replace its iron mountains map
5. start it
6. see you cant set light oil as filter
sorry thats its very long but i dont remember it perfectly

**Comment by Anuken** [comment]
This all depends on the **exact** block you were using, so you'll need to be more specific.

**Comment by DeltaNedas** [comment]
yea ik :/
