### ISSUE TITLE
Crash when trying to edit a custom map

### ISSUE THREAD

**Issue by xzarfs** [Anuken/Mindustry#1395]
**Platform**: *Windows*

**Build**: *102.3*

**Issue**: *Game crashes when trying to **edit** a custom map.*

Error message box: 
![image](https://user-images.githubusercontent.com/59253058/72623339-9eefc480-394d-11ea-83b3-536143c5e78f.png)
---

**Crash log:** https://pastebin.com/Ewry2uTj
**Map download:** https://cdn.discordapp.com/attachments/477494303061442571/667747854437056564/map_12.msav

**Steps to reproduce**: *trying to edit the custom map linked*

**Comment by Anuken** [comment]
Fixed.
