### ISSUE TITLE
Weird core storage glitchiness

### ISSUE THREAD

**Issue by Famous5000** [Anuken/Mindustry#1401]
**Platform**: Windows

**Build**: 102.3

**Issue**: Multiple core storages do not add up as they should.

**Steps to reproduce**: Have multiple cores with different storage options on the map, and try to modify one. You'll notice that the storage will drop if you had one with a large amount of storage.

Copy of #665 but that was very old, so I'm re-opening this as a new issue.

**Comment by Anuken** [comment]
What exactly are you observing? What is "as they should"? Be more specific about the behavior you see, the numbers that appear, what is actually happening and what *should* be happening.

**Comment by Famous5000** [comment]
I'm observing that if you have a core with more storage than another core, and you modify the other core to have more storage or put down a conveyor next to it, you'll see the total capacity of the cores drop. It should instead add on to the capacity of the cores.
