### ISSUE TITLE
Decrease long press duration to 0.3f on mobile

### ISSUE THREAD

**Issue by FunnyGameNS** [Anuken/Mindustry#1402]
**Platform**: *Android/iOS*

**Build**: *102*

**Issue**: *Building on mobile is much slower than on PC. This will slightly speed it up. (i already tested 0.3f duration on my phone)*

**Comment by Quezler** [comment]
maybe make it a pull instead of an issue?

**Comment by FunnyGameNS** [comment]
I could do it, but i have very modified sources and i don't want to make a fork and setup a new clean environment just to make a pull request for changing one value (currently i am working without git)
