### ISSUE TITLE
Mech Pad Malfunction

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1405]
**Platform**: *Windows 10*

**Build**: *102.3*

**Issue**: *Rapid teleportation between 0,0 and the mech pad. Also rapid sounds of exiting a mech pad.*

**Steps to reproduce**: *I was testing a custom mech for my mod, and I think the issue is either because the pad is 1x1 or because the transformation time is 0 (instantaneous). Probably the transformation time.*

**Comment by MEEPofFaith** [comment]
I definitely did something wrong with the code. Still does this with buildTime: 60

![healp](https://user-images.githubusercontent.com/54301439/72755996-c7abd000-3b80-11ea-9699-3f88279acf1c.gif)

**Comment by MEEPofFaith** [comment]
Setting it to hasPower doesn't fix. I'll add the consume code and try again.

**Comment by MEEPofFaith** [comment]
Added consume power. I have to supply power for it to work, but it still glitches.

**Comment by Anuken** [comment]
Show me your json for the mech and the pad.

**Comment by MEEPofFaith** [comment]
Ok I'll quickly fetch my code.

**Comment by MEEPofFaith** [comment]
Mech pad (the code at the time of testing.)

type: MechPad	
mech: overseer	
localizedName: Overseer Mech Pad
description: Transforms you into the sandbox ship,the Overseer.
size: 2
hasPower: true
buildTime: 60
category: upgrade
buildVisibility: sandboxOnly
alwaysUnlocked: true 
consumes: {	
  power: 1	
}	
requirements: [	
  copper/1	
]

**Comment by MEEPofFaith** [comment]
Mech (code at time of testing)

localizedName: Overseer
description: A powerful sandbox only ship for complete obliteration.
type: Mech
drillPower: 69
mineSpeed: 69
speed: 10
drag: 0
mass: 0
health: 20000
itemCapacity: 69420
engineColor: f3b380
buildPower: 69420
cellTrnsY: 0.75
weapon: {
  length: 3.125
  width: 0
  alternate: true
  reload: 1
  inaccuracy: 2
  shake: 2
  nimPlayerDist: 0
  bullet: lancerLaser
  shootSound: laser
}

**Comment by MEEPofFaith** [comment]
[Might as well link my repo.](https://github.com/MEEPofFaith/Extra-Sand-For-The-Sandbox-Mod)

**Comment by MEEPofFaith** [comment]
I did make some untested changes after those versions of code though. I can guess that maybe having movement speed greaterer than max speed may have caused issues.

**Comment by Anuken** [comment]
You set it to have 0 mass; *objects cannot have 0 mass*. Attempting to apply any force to an object of 0 mass will make it go infinitely fast and simply warp out of bounds, dying instantly. Many other side effects may happen as well. 

Not a bug.

**Comment by MEEPofFaith** [comment]
ok thanks
