### ISSUE TITLE
"Underflow" gate name

### ISSUE THREAD

**Issue by Hypoon** [Anuken/Mindustry#1409]
I saw the new underflow gates in the recent commits, and it's very exciting. It will be a very useful gate.

I have a minor comment regarding the name, though. The word "underflow" does have meaning in computer science, and it doesn't match the behavior of this gate. The term is used when a fraction gets too small for a computer to store it.

If the mismatch doesn't bother anyone, then please close this issue. Thanks!

**Comment by Anuken** [comment]
"Underflow" can mean any number of things, both inside and outside of computer science. Fractions don't have to be involved.

I don't see how that specific meaning is relevant to this block, since Mindustry is a game and the gate doesn't have anything to do with computer science.

**Comment by Hypoon** [comment]
> "Underflow" can mean any number of things, both inside and outside of computer science. Fractions don't have to be involved.

I'm not aware of any other definitions, I'm sorry for the error!

> I don't see how that specific meaning is relevant to this block, since Mindustry is a game and the gate doesn't have anything to do with computer science.

I agree completely, that's why I posted this issue. Unaware of any other meanings, it seemed strange to me to borrow the term when that meaning is not relevant.

Thank you for the quick response!
