### ISSUE TITLE
sometime when deconstructing multiple blocks the game breaks

### ISSUE THREAD

**Issue by bvcbvc** [Anuken/Mindustry#1411]
**Platform**: *Chromebook*
 
**Build**: *102.3*

**Issue**: *what happens depends on if im online or not, if online instant disconnect.offline is instant crash.*

**Steps to reproduce**: *im not sure if its because im on chromebook but try to go on a server and mass deconstruct or something, also error message upon disconnection
![Screenshot 2020-01-21 at 9 27 56 AM](https://user-images.githubusercontent.com/42185819/72818539-42ccbf00-3c31-11ea-9bf4-80ff2d05e5c6.png)
 .*

**Comment by Anuken** [comment]
This doesn't happen on mobile or on desktop for me, so it's most likely Chromebook-specific.. and as I don't have a Chromebook, this can't be tested and won't be fixed.
