### ISSUE TITLE
when i try to load the mod, it keeps crashing. I end up having to uninstall and reinstall the game (don't worry, i backed up my saves)

### ISSUE THREAD

**Issue by Fodicon** [Anuken/Mindustry#1414]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Avevad** [comment]
Please tell us which platform and build of mindustry do you have and describe the steps to reproducing the bug. Idk why do you ignored the issue template and submitted the issue without most of useful information

**Comment by Avevad** [comment]
Also, it will be fine If you add some logs (logcat on android, stdout on windows an linux, etc.)

**Comment by Anuken** [comment]
Use the issue template.
