### ISSUE TITLE
Windows idk what is the build of the itch.io page it downloads me the wrong version of the game, the 100 instead of 102.3 i already had that issue earlier, but someone (i forgot who ) sent me a link to an other site where i could download the 101

### ISSUE THREAD

**Issue by gulmorte** [Anuken/Mindustry#1415]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by DeltaNedas** [comment]
please fill in the template so its easier to read information

**Comment by gulmorte** [comment]
Windows
idk what is the build of the itch.io page
it downloads me the wrong version of the game, the 100 instead of 102.3
i already had that issue earlier, but someone (i forgot who ) sent me a link to an other site where i could download the 101

**Comment by DeltaNedas** [comment]
do not download mindustry from unofficial sites, you may get viruses.
only download from steam, app store, play store (if its from anuken), itch, Anuken/MindustryBuilds on github

**Comment by Anuken** [comment]
Use a reputable source. I have no idea what you're doing here.
