### ISSUE TITLE
Сохранение

### ISSUE THREAD

**Issue by Flashvlad** [Anuken/Mindustry#1418]
**Platform**: *Android*

Я попытался импортировать сохранение, но оно не импортируется, перепрошивки или смены устройства не было.

**Comment by Quezler** [comment]
> I tried to import the save, but it is not imported, there was no flashing or changing the device.

**Comment by XEN0PHIL** [comment]
Недостаточно данных. В точности опиши свои действия и возможные ошибки, если они отображались на экране.

**Comment by Anuken** [comment]
Use the issue template and fill in *all* the details. If you can't provide the information needed, I can't look into your issue.

**Comment by Sneg21** [comment]
Такая самая проблема
