### ISSUE TITLE
Game not ending after destroying enemy core (Salt Flats)

### ISSUE THREAD

**Issue by rafket** [Anuken/Mindustry#1419]
**Platform**: Linux

**Build**: release build 102

**Issue**: After destroying the enemy core, the game does not end. The ground units are just flocking in the location the core used to be.

**Steps to reproduce**: Destroy the enemy core in the Salt Flats map. I think the issue remains even if the player's own core is destroyed, but when I came across that I thought it was a feature.

**Comment by Anuken** [comment]
Duplicate.
