### ISSUE TITLE
Amplified touch sensitivity

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#1420]
**Platform**: Android

**Build**: 102.3

**Issue**: Touch sensitivity increased to obscene level, amplified camera movement, configurable blocks like sorters and power nodes break entirely (this does not happen, however, when deconstruct planning is enabled.) See [this video](https://cdn.discordapp.com/attachments/553071673587400705/669768979409141781/Screenrecorder-2020-01-23-07-50-36-407.mp4).

**Steps to reproduce**: Time out of a server while Mindustry is not in the foreground and rejoin (INCONSISTENT). This creates(?) another MobileInput instance which causes the issue.

**Comment by Anuken** [comment]
Closing for same reason as #1336
