### ISSUE TITLE
Scaling is broken

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1422]
**Platform**: *Android/iOS/Mac/Windows/Linux*
GNU/Linux
**Build**: *The build number under the title in the main menu. Required.*
master from yesterday ish
**Issue**: *Explain your issue in detail.*
When scale is over 100% (weird stuff may happen under too) everything is broken.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
1. set scale to 150%
2. restart
3. look at loading screen and main menu
4. if its possible, try to play a game and look at your block inventory
![Main menu](https://user-images.githubusercontent.com/39013340/73016979-dc08fa80-3e16-11ea-9e73-f7d9575b0d40.png)
![Loading screen](https://user-images.githubusercontent.com/39013340/73016984-ddd2be00-3e16-11ea-9dd1-4564242f72d6.png) (notice how the letters are **individually scaled** and not as a whole string)

**Comment by Anuken** [comment]
This was already fixed yesterday.

**Comment by DeltaNedas** [comment]
damn
