### ISSUE TITLE
Lost base fails to end scenario

### ISSUE THREAD

**Issue by fotocyte** [Anuken/Mindustry#1424]
**Platform**: *Windows*

**Build**: *Release 102*

**Issue**: *An endgame condition (losing base and/or dying) does not end the game*

**Steps to reproduce**: *I was in the campaign playing around with copper walls and guns. Enemies made it to my core. They destroyed my core but the game was still active. Tried various times to replicate and it does fail every time. Also, the ship can be destroyed before or after the destruction of the base, and the game will still just sit there like it's still an active round. Save attached.
[-1.zip](https://github.com/Anuken/Mindustry/files/4106317/-1.zip)

*

**Comment by Anuken** [comment]
Duplicate.

**Comment by fotocyte** [comment]
Hi, duplicate of which issue please? I checked and did not see a similar one.

**Comment by Anuken** [comment]
#1419
#1373
#1292

**Comment by fotocyte** [comment]
Thank you! Didn't see a related issue with PR like usual.
