### ISSUE TITLE
Wave number is exceptional in custom game.

### ISSUE THREAD

**Issue by linglan512572354** [Anuken/Mindustry#1426]
**Platform**: Windows

**Build**: v102.3

**Issue**: I import a map from a saved game, but I can`t reset the wave num to the first. each time I begin a new game will continue the wave num when I saved.

**Steps to reproduce**: Export a save to disk then import it to the map editor. When we play this map in a custom game, the wavenumber is equal to the saved game, not first.

I try to re-export and import map, reset waves to default, reset rules to default, begin the custom map in different modes, etc. All of these above actions can`t reset the wave num.

Furthermore, the state of blocks also hard to set. I can remove it and put it again to reset the blocks state, but I can`t change block state in the map editor. If I need a fulfilled battery, I need to begin a new game, fill the battery, save it, then import it into the map editor.

**Comment by Anuken** [comment]
You're not supposed to be able to reset the wave number or the block state; those are parts of save data that you simply can't modify. Saves are not intended to be played as maps.

**Comment by linglan512572354** [comment]
Sure. Many thanks.
