### ISSUE TITLE
Mod dissapear

### ISSUE THREAD

**Issue by abuko1** [Anuken/Mindustry#1427]
![20200124_143619](https://user-images.githubusercontent.com/60253826/73055669-87698c00-3eb7-11ea-8e06-0cef2a015f9a.gif)
**Platform**: *Android*

**Build**: *102.3*

**Issue**: Adding some mod,that mod dissapear,but can't add this mod again because can't add mod with same name but I don't see that mod

**Comment by DeltaNedas** [comment]
wait for 103 to come out
it will let you modify files directly in folder `Android/data/io.anuke.mindustry/files/mods/`
you just remove all mods in there and it will work

**Comment by Anuken** [comment]
Duplicate.
