### ISSUE TITLE
Reloading mods wastes RAM

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#1430]
**Platform**: Windows

**Build**: 103

**Issue**: Reloading mods wastes memory. This can be very crippling for platforms with limited RAM, such as phones.
After loading up the game:
![freshload](https://user-images.githubusercontent.com/19158169/73095141-f3e08d00-3eaf-11ea-9ac3-6086319b05bd.PNG)
After reloading mods:
![fewreloadslater](https://user-images.githubusercontent.com/19158169/73095146-f6db7d80-3eaf-11ea-85b9-9f8d28a050dd.PNG)
**Steps to reproduce**: Check the memory usage of the game after starting it using a program such as Task Manager. Reload the mods by disabling and reenabling a mod. Now check the game's memory usage. Repeat for more clear results.

**Comment by DeltaNedas** [comment]
thats because it doesnt know how to free the atlas i think
just restart it only takes a few seconds
also
>windows 10
>complain about ram usage
lol

**Comment by Anuken** [comment]
This is a known problem, but I won't be fixing it anytime soon. Mod reloading may be removed entirely.
