### ISSUE TITLE
[MAC]Game stops reacting after initial click and does not fully fullscreen

### ISSUE THREAD

**Issue by MadhuizenT** [Anuken/Mindustry#1433]
**Platform**: Mac

**Build**: 103

**Issue**: When I open the game I can click _once_ and after which the window become's "transparent" but not see through it all the programs behind it you can click on. 

**Steps to reproduce**: This happened after I updated and deleted my game data. 
When I open the game it first opens normal and then it shrinks and expands in the same window. unlike before it does not open in a separate fullscreen window (I can see the menu bar on top).
To fix this I had to drag the game window into a separate fullscreen window within mission control.

**Comment by Anuken** [comment]
This doesn't happen on my Mac. I did not change any window management code whatsoever, so what you're experiencing is something to do with your OS. Without any way to reproduce it, this won't be fixed.
