### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by KyleTheJudge** [Anuken/Mindustry#1435]
Android
Build 103
When updating all schems and saved games deleted
I was updating the game and then my saves were kill.

**Comment by Anuken** [comment]
Fixed.

**Comment by kfeaginsiii** [comment]
Android: What build is the fix in? My games show saved. When I close the app and reenter, it defauls to the tutorial.

**Comment by MetalTwoThree** [comment]
Same issue. It appears that it has something to do with the file manager. When I try to open the game data folder, I get this error:
Unable to open folder (missing valid file manager?) /storage/emulated/0/Android/data/io.anuke.mindustry/files

I went to that address and I dont see anything there that looks like game data. I dont have a "correct" filesystem to compare to, but imexpecting somethingt hat is labeled "saves" or "game data" 

Running Android 10
Hardware is Pixel 2 using the default file manager

**Comment by kfeaginsiii** [comment]
I opened a new issue since this seems a little different.

https://github.com/Anuken/Mindustry/issues/1483#issue-557906108
