### ISSUE TITLE
Connection refused: connect

### ISSUE THREAD

**Issue by alexsisson** [Anuken/Mindustry#1441]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by ZkyLB** [comment]
what the fuck was this

**Comment by alexsisson** [comment]
That was me typeing in an error message from the crash log thinking it was
a search box.
