### ISSUE TITLE
armored conveyor bug

### ISSUE THREAD

**Issue by SugarTheSug** [Anuken/Mindustry#1446]
**Platform**: Windows

**Build**: 103.3

**Issue**: this bug work same with other factory structures and some roads
![1](https://user-images.githubusercontent.com/60311526/73133246-033e1280-4037-11ea-9b93-382479d3ae2e.png)
![2](https://user-images.githubusercontent.com/60311526/73133259-22d53b00-4037-11ea-966f-984a55e0817a.png)
**Steps to reproduce**: just follow the screenshots

**Comment by Itzbenz** [comment]
bruh armored conveyor don't accept any input, conveyor is exception

**Comment by ZkyLB** [comment]
This is intentional. Please close this issue.

**Comment by ado1928** [comment]
it literally says in the description of the armored conveyor: "doesn't accept items from the side"

**Comment by SugarTheSug** [comment]
oh. I'm don't read description). Sorry

**Comment by Quezler** [comment]
please close the issue then 🙂
