### ISSUE TITLE
Infinite item storage in a conveyor

### ISSUE THREAD

**Issue by ado1928** [Anuken/Mindustry#1447]
**Platform**: Windows

**Build**: 103

**Issue**: See recording below. The conveyor can take infinite amount of items, but there's no way to retrieve those items. 

**Steps to reproduce**: Was just messing around with item logic, and then i noticed if i placed an item inside the conveyor, it would disappear. I tried putting more items in, and it surpassed the conveyor item limit.

![bug](https://user-images.githubusercontent.com/47899778/73134427-b1958800-4036-11ea-9efd-44dbde367a7a.gif)

**Comment by ZkyLB** [comment]
absolute magic

**Comment by way-zer** [comment]
It's problom of sorter

**Comment by Raoul1808** [comment]
have you tried with the unloader? I'm curious

**Comment by ado1928** [comment]
> have you tried with the unloader? I'm curious

Tested everything, even tried to fill it with an insane number of blast, but it exploded like it was empty. There's really no way to take the items out.

**Comment by pyronie** [comment]
unpowered item incinerator i guess

**Comment by Quezler** [comment]
> have you tried with the unloader? I'm curious

[conveyor's cannot be unloaded](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/Conveyor.java#L50)

**Comment by itcannotbe** [comment]
Probably r
![Screenshot_20200127_205843_io anuke mindustry](https://user-images.githubusercontent.com/45280919/73176703-0c6ad480-4148-11ea-9be5-7e24b757dafe.jpg)
elated

**Comment by itcannotbe** [comment]
Update: Simplest Bug Set-up
![Screenshot_20200127_233428_io anuke mindustry](https://user-images.githubusercontent.com/45280919/73188362-b9038100-415d-11ea-8b7e-768af098660c.jpg)

**Comment by itcannotbe** [comment]
@Anuken It's back

**Comment by Anuken** [comment]
It's an issue relating to instant overflow gates; I'll make them slower to fix it.

**Comment by zethnest** [comment]
Seems to be an issue with fps. I can't reproduce with FPS above 50. Reproducible with FPS more than 20. Not more than, idk but less than 50.
