### ISSUE TITLE
Documentation: gameplay settings

### ISSUE THREAD

**Issue by thw0rted** [Anuken/Mindustry#1450]
**Platform**: Android

**Build**: 103.4

**Issue**: The "game" portion of the settings menu includes a number of items that have cryptic names or do not behave as expected. These settings should be documented with in-game tooltips, or at least a page on the wiki.

Examples: auto-create saves (when does this apply? I can't load saves in campaign), automatic block suggestions (where? How?), conveyor placement pathfinding (it only seems to make straight lines?).

**Steps to reproduce**: Open the game, Settings -> Game

**Comment by DeltaNedas** [comment]
i 100% agree with tooltips but dont know how it would be implemented
how it could be for the user:
- with mouse, if it is hovering over it for 500ms or so show it
- with touch screen, if it is held for 500ms or so show it until screen is tapped again

just for reference autosave is for custom games, pathfinding automatically turns around corners

**Comment by Anuken** [comment]
This is a feature suggestion. Use Feathub for that.

**Comment by thw0rted** [comment]
I don't see any other suggestions on Feathub about settings or documentation.  On other open-source projects I contribute to, I treat missing or incomplete documentation as an issue with existing code, rather than a feature request, which is why I asked here.

I expect Feathub to be a poor fit for issues that mostly impact newbies -- if I've played the game for an hour or two total and something is confusing, am I really likely to go sign up for Feathub, then find and upvote an issue about improving user experience?
