### ISSUE TITLE
[server] freezing units

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1460]
**Platform**: `ubuntu`

**Build**: `latest commit`

**Issue**: it appears as though units freeze if the last person online leaves the server, when someone rejoins they don't move a muscle.

**Steps to reproduce**: playing on some of the/my nydus servers.

**Comment by Anuken** [comment]
This is almost certainly something to do with your plugins or modifications, because I've never had this happen to me and it's not reproducible on a test server.

**Comment by Quezler** [comment]
both servers which showed said symptoms have/had no shared custom code between them though 🤔

**Comment by Quezler** [comment]
i have now tested it on **BE 6992**:

- download server & desktop jar
- placed into brand new folder
- start server & host
- start client & join
- run the wave
- units not moving

with what version/setup did you try @Anuken ?

**Comment by Anuken** [comment]
Just tried what you described.
- Downloaded server and client, placed into a new folder, ran them both.
- Ran `host maze survival`
- Connected
- Ran `runwave`, units are moving
- Reconnected, units have moved since my reconnect and are still moving

**Comment by Quezler** [comment]
Just had `carribeanmax` do it as well, worked fine for him, strangely enough 🤔
