### ISSUE TITLE
Velocity transfer from mech to frag bullets.

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1469]
**Platform**: *Windows*

**Build**: *103.4*

**Issue**: *Frag bullets with keepVelocity: true adopt the movement of the mech, which is weird because the bullets don't come from the mech. You can clearly tell in [my video](https://youtu.be/WZldRx6SzHM?t=15).*

**Steps to reproduce**: *Well, it's just a mech with fragging bullets that have keepVelocity set to true... Also, can you make lancer beams have keepVelocity false by default?*

**Comment by Anuken** [comment]
But the bullets do come from the mech, indirectly. Since the bullet inherits the player velocity and the frag explodes from the bullet, it should keep that velocity. If you don't want it, don't enable velocity keeping.
