### ISSUE TITLE
Can't send the same message that got filtered by antispam

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#1470]
**Platform**: Windows

**Build**: 103.4 (Steam)

**Issue**: You can't send the same message that got blocked by messageRateLimit, even after waiting.

**Steps to reproduce**: See the list and .gif below:
1. Join a server with **messageRateLimit** enabled.
2. Write *first message*.
3. Write *second message* faster than **messageRateLimit** allows to.
4. Wait the time required before writing it again.
5. Try to write exactly the same *second message*, it will get blocked even if it was not sent before.
![anti_spam_bug](https://user-images.githubusercontent.com/55051135/73364900-655b7980-42bc-11ea-8cd1-e2259c91205f.gif)

**Comment by XEN0PHIL** [comment]
https://i.imgur.com/jMfFkaI.mp4

**Comment by Anuken** [comment]
Don't create separate issues for pull requests.
