### ISSUE TITLE
conveyor vault a-like bug

### ISSUE THREAD

**Issue by OverChock** [Anuken/Mindustry#1474]
**Platform**: *Android*

**Build**: *103.4*

**Issue**: *The "chain" are making the conveyor with a infinity storage*

**Steps to reproduce**: *Ok so, i think the 2 underflow gate and the sorter are transporting items too fast for the conveyor so the conveyor can't output the items*
![Screenshot_20200129-015833_Mindustry](https://user-images.githubusercontent.com/54481508/73402169-69db5e80-42cb-11ea-95cb-9302b78c4fce.jpg)
![Screenshot_2020-01-29-19-59-06](https://user-images.githubusercontent.com/54481508/73402194-7b246b00-42cb-11ea-8c4b-71a9f5be85eb.png)

**Comment by Anuken** [comment]
Duplicate.
