### ISSUE TITLE
Android navigation and lines

### ISSUE THREAD

**Issue by TundrumMax** [Anuken/Mindustry#1478]
**Platform**: *Android*

**Build**: *103.4*

**Issue**: *Navigation is occasionally doubled, and its impossible to drag to make lines when this happens, because for some reason you still navigate when attempting to make lines. Also launch bug?*

**Steps to reproduce**: *Not really sure, I installed the game on my tablet, I played the tutorial, went into the first world, launched, then played it again for a bit. For some reason, my game didnt save so I had to do it all over again. This time I skipped the tutorial, I went into the main game, but the "Launch" button wouldn't appear. I closed, got some upgrades, and reopened the game, when the bug mentioned in the "issue" part started happening. It was completely impossible to make lines, because the screen kept moving. Reopening the game wouldn't fix anything after this.

EDIT: after playing the PC version, I found out that you launch every 5 rounds, ignore the "launch bug" claimed.*

**Comment by Anuken** [comment]
Duplicate.
