### ISSUE TITLE
Game cant start because of an invalid mod

### ISSUE THREAD

**Issue by valtsu41** [Anuken/Mindustry#1479]
**Platform**: *Android*

**Build**: *103*

**Issue**: *I imported a mod with invalid sprites-override -sprites and it crashed the game and now every time I try to start Mindustry it crashes.*

**Steps to reproduce**:  *Import a mod with invalid `sprites-override` sprites. 
*

**Note**: *I imported the mod while using an earlier build and updated the game to 103 to see if it would help. (It did not)*

**Comment by Anuken** [comment]
Delete the mod from your mod folder. Situations like these are the reason why data has been moved to an external directory.

**Comment by valtsu41** [comment]
The problem is, I imported the mod before updating...

**Comment by Quezler** [comment]
is updating first an option?

**Comment by valtsu41** [comment]
Not anymore since it already happened.

**Comment by valtsu41** [comment]
RIP my save

**Comment by Anuken** [comment]
It doesn't matter when you updated; as long as you're running 103.4, you should be able to delete the mod.

**Comment by valtsu41** [comment]
What is the path to the data then?

**Comment by DeltaNedas** [comment]
Android/data/io.anuke.mindustry/files/mods/

**Comment by valtsu41** [comment]
Ok thanks! Samsung file search did not find it :roll_eyes:

**Comment by DeltaNedas** [comment]
samsung stock apps are terrible, get https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/

**Comment by valtsu41** [comment]
Wait what, why are there mods I have not installed in the game files?
