### ISSUE TITLE
Game not saving

### ISSUE THREAD

**Issue by kfeaginsiii** [Anuken/Mindustry#1483]
**Platform**: Android

**Build**: 103.4 (and the main release)

**Issue**: Game resets after exiting application. Saved data does not persist.

Exporting the game to a new location works and seems to persist the save data at that point.

**Steps to reproduce**: play game, exit app (actually end the task). Re-enter game. You will find yourself in a new game.

Export game, then import, then it will persist the saved game.

Interesting to note that when clicking the open data folder under Settings>Game Data, an error is displayed 'unable to open folder (missing file manager?)' <Path to game data folder>. When I navigate the file path, it exists.

**Comment by DeltaNedas** [comment]
womm

**Comment by Anuken** [comment]
Works on my Android devices.

> Interesting to note that when clicking the open data folder under Settings>Game Data, an error is displayed 'unable to open folder (missing file manager?)'

This means that you don't have a file manager than can handle folder opening from an external application.

**Comment by kfeaginsiii** [comment]
Wouldn't that impact it after I've created the export? Once I manually create and export, then import it, everything works as expected.

**Comment by Rasip** [comment]
Same issue here. 2 more people posted about having the same issue on the reddit too.

**Comment by kfeaginsiii** [comment]
Linking another report if this issue.

https://github.com/Anuken/Mindustry/issues/1435#issuecomment-580638204

**Comment by chitalian** [comment]
Im having the same issue, is there another release with a patch?

**Comment by kfeaginsiii** [comment]
I've found as a temp fix to manually export, then import, then the game is saving fine for me.

**Comment by Fableton** [comment]
Export works but when I try to load it it crash

**Comment by Anuken** [comment]
Should be fixed with 104; reopen if it isn't.

**Comment by Jonny007-MKD** [comment]
#1660
