### ISSUE TITLE
Conveyor belt griefing ?

### ISSUE THREAD

**Issue by DerpFace00** [Anuken/Mindustry#1486]
Platform : Windows

Build : 103

Issue : Player joined , talked a bit , then belts started acting possessed , switching directions all over , individually.

Steps to reproduce : Dunno , ask ":(" , the most likely responsible. Fairly important , said he had "a button to reverse the belts to how they were".
![New Bitmap Image (2)](https://user-images.githubusercontent.com/34234985/73580550-9db2b180-448e-11ea-9757-91a1435674d5.png)

**Comment by Anuken** [comment]
Yes, one can write scripts to rotate all the conveyors. This isn't really a bug, and I can't do anything about it at the moment.

**Comment by KK6DOC** [comment]
Probably a thing that automatically uses R+scroll

**Comment by L0615T1C5-216AC-9437** [comment]
yep, had this happen on my server too.

**Comment by ado1928** [comment]
If a player makes n> changes per seconds, kick them.

**Comment by L0615T1C5-216AC-9437** [comment]
Or limit to 1 block /s. Almost no one has fast enough reflexes to do accurately more than 1 block/s

**Comment by Quezler** [comment]
only one action in an entire second is to restrictive imo

**Comment by KK6DOC** [comment]
Maybe make it so you could do R+Scroll a certain amount of times in for say: 10times in 5s this would prevent people doing it everywhere but allow people.who are making adjustments to have enough uses

**Comment by KK6DOC** [comment]
Kinda like when trying.to unlock a phone and each time you do it 20 times in 5 sec then you will have a cool down if like 5s and this doubles everytime
