### ISSUE TITLE
Save game doesn't exist.

### ISSUE THREAD

**Issue by Rasip** [Anuken/Mindustry#1487]
**Platform**: *Android*

**Build**: *103.4*

**Issue**: *downloaded and played a couple hours this evening. About an hour later when i came back to play again the settings were reset and it kicked me back to the tutorial. I tried going to settings and hitting the button to open the save folder but got an error saying "unable to open folder (missing valid file manager?)*

**Steps to reproduce**: *played on a fresh install. Watched a video. Came back to play more but the save didn't exist.*

**Comment by Rasip** [comment]
![Screenshot_2020-01-31-20-38-57](https://user-images.githubusercontent.com/13563936/73585912-a3e36680-446b-11ea-81f2-b16009e22d12.png)
![Screenshot_2020-01-31-20-52-20](https://user-images.githubusercontent.com/13563936/73585918-a9d94780-446b-11ea-8985-84b471f52a32.png)

**Comment by Anuken** [comment]
Duplicate.

**Comment by Jonny007-MKD** [comment]
#1660
