### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by K103908** [Anuken/Mindustry#1489]
**Platform**: *Android/iOS/Mac/Windows/Linux* Android, but I'm on a Dell Chromebook

**Build**: *The build number under the title in the main menu. Required.* 103.4

**Issue**: *Explain your issue in detail.* I entered the Mod menu, clicked import from GitHub, I entered the Mod URL as I've done before, and it gave me a message saying "Trust Anchor for Certification Path not found"

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
I closed Mindustry yesterday and went to sleep, I opened it this morning and it gave me the message, "Trust Anchor for Certification Path not found". I've even tried uninstalling and reinstalling and it did the same thing
![Screenshot 2020-02-01 at 3 25 36 PM](https://user-images.githubusercontent.com/60554123/73598783-86b1a500-450a-11ea-8e8c-a81f0a452ff2.png)

**Comment by Anuken** [comment]
Your Android version isn't properly compatible with HTTPS for whatever reason. Won't fix.

**Comment by PetrGasparik** [comment]
Maye your chromebook stop trusting DigiCert CA eventually. See help here: https://support.google.com/chromebook/forum/AAAAmKCdEusG7RKLbjqVik/?hl=uk
