### ISSUE TITLE
[status effects] boss on a player mech

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1493]
**Platform**: `mac (client)` / `ubuntu (server)`

**Build**: `103/master`

**Issue**: when you apply the `boss` status effects to a (flying) player mech (on a multiplayer server) and he moves, he will fly glichery and uncontrollably everywhere, i am not entirely sure where its going wrong, so i'm turning this into an issue for the time being 🤔 

        boss = new StatusEffect("boss"){{
            armorMultiplier = 3f;
            damageMultiplier = 3f;
            speedMultiplier = 1.1f;
        }};

**Steps to reproduce**: wanting to give a specific player a boost instead of everyone via rules.

[video](https://discordapp.com/channels/391020510269669376/414179246693679124/673528956732964875) (moves on its own once in motion, not holding down any keys)

**Comment by Anuken** [comment]
> when you apply the boss status effects to a (flying) player mech
Don't. This isn't done in the game for a reason.

**Comment by Quezler** [comment]
:ohno:

**Comment by Anuken** [comment]
Players don't handle status effects with speed multipliers.
