### ISSUE TITLE
[minor bugs] bad core texture + weapons arent prefixed with mod name

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1496]
**Platform**: GNU/Linux
**Build**: latest master, with my patch-5 (weapon.java untouched)

**Issue 1**: the big core texture violates laws of physics -> ![snip](https://user-images.githubusercontent.com/39013340/73656358-dc5f8c00-4687-11ea-886f-333b3e0658be.png)
**Steps to reproduce**: look at bottom thing of core

**Issue 2**: weapon `name`s are not prefixed with `modname-`.
this contradicts mechs, blocks, etc. being prefixed.
**Steps to reproduce**:

```
const cannon = extendContent(Weapon, "cannon", {});
print(cannon.name); // just cannon
const mech = extendContent(Mech, "mech", {});
print(mech.name); // modname-mech
```

**Comment by Quezler** [comment]
interesting, that yellow part always grabbed my attention, but never noticed why until now 🤔

**Comment by Anuken** [comment]
> weapon names are not prefixed with modname-.
this contradicts mechs, blocks, etc. being prefixed.

Unlike mechs or blocks, weapons are **not** content. When you specify a name, you're only specifying the raw texture name.

**Comment by DeltaNedas** [comment]
ooooh i get it then
thats why weapons arent in content/
