### ISSUE TITLE
help im invaded

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#1500]
i only have reapers and revenants for dinner
![newyear](https://user-images.githubusercontent.com/21104932/73679299-2b7ae080-46cb-11ea-9aff-ef08ba0af1ae.png)

**Comment by Quezler** [comment]
:ohno:

**Comment by Ilya246** [comment]
:ohno:

**Comment by DeltaNedas** [comment]
i wasnt going to snipe it, i thought someone would make an actual pr but no
never doubt the route
#1500

**Comment by ZkyLB** [comment]
wait where is the revenant

**Comment by BasedUser** [comment]
@ZkyLB further plate

**Comment by ZkyLB** [comment]
> @ZkyLB further plate

oh ok thanks

**Comment by Anuken** [comment]
perish

**Comment by BasedUser** [comment]
one goes down another will follow

**Comment by macdowntwo** [comment]
revisiting this because why not
