### ISSUE TITLE
Music randomly starts playing

### ISSUE THREAD

**Issue by EmberHeartshine** [Anuken/Mindustry#1504]
**Platform**: Android

**Build**: "custom build" (5-fdroid-103)

**Issue**: I have the music volume turned all the way down (see [screenshot](https://user-images.githubusercontent.com/50666308/73691275-0cb32480-46a0-11ea-88e0-f7d2cf6b02df.png)) because I play Mindustry while listening to podcasts. However, randomly the game music will start playing. It seems to *usually* coincide with the starting of a wave, but it's never the same wave so it's hard to tell.

**Steps to reproduce**
1. Play game extensively
2. Wait for the music to start playing

**Comment by MEEPofFaith** [comment]
I play with music, but switching to a different app (like discord) and then back will commonly make the music play immediately. (Android)

**Comment by FadilSmajilbasic** [comment]
Music playing while on 0% volume

**Platform**: *Windows*

**Build**: *104.5*

**Issue**: *When setting the volume on 0% it is still audible in the menu*

**Steps to reproduce**: 
- *open the exe*
- *go to settings>sound*
- *set music to 0%*
- *go back to main menu*
- *music is still audible*

[Video](https://streamable.com/h7wq4)
