### ISSUE TITLE
[zones] wrong name & thumbnail got loaded

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1510]
> issue made on behalf of another user

**Platform**: `android` & `steam`

**Build**: `possibly 103.4`

**Issue**: https://discordapp.com/channels/391020510269669376/477494303061442571/674329582635319325

**Steps to reproduce**: noticed the issue in one of my periodic visits to the `#help` channel

**Comment by Anuken** [comment]
The name is correct. This happens because the map image is cached, and cache isn't overwritten/transferred between saves. Playing on the map again refreshes it. I won't be changing this.
