### ISSUE TITLE
I used (some of) your assets for the Global Game Jam

### ISSUE THREAD

**Issue by ThibaultLemaire** [Anuken/Mindustry#1511]
So I participated in my first game jam last weekend and I used some of your assets for my game.

[Here is my submission.](https://globalgamejam.org/2020/games/repair-yourself-army-7) [You can try it live!](https://thibaultlemaire.gitlab.io/repairyourselfanarmy/)

The game is licensed under the GPLv3 to be compatible with your assets.

I just thought I'd stop by to let you know and say a big thank you (I wouldn't have thought of using your assets if I didn't liked your game :wink:)

[Not an issue, close at will]

**Comment by Quezler** [comment]
no idea how to find "broken robots" 🤔

**Comment by Anuken** [comment]
Nice! I never thought my assets would eventually be acceptable enough for people to use them in their games.

**Comment by ThibaultLemaire** [comment]
> acceptable enough

Haha, for a one-guy-26-hours game they were more than enough! (especially since I have very little skill in graphic design)

I plan to keep working on that game as well, and I'd like to add more bots at some point. So, expect if find a graphic designer willing to make original assets for my game, I think I'll stick to your sprites :stuck_out_tongue:
