### ISSUE TITLE
Collision issue on Ruinous Shores

### ISSUE THREAD

**Issue by fotocyte** [Anuken/Mindustry#1513]
**Platform**: *Windows*

**Build**: *6893+*

**Issue**: *I had a bot collide with a tile and get stuck in the alien base. Happened at or near wave 100 and he's still stuck there. New waves come without issue, but he doesn't get unstuck. Also tried going in and out of their base to shoot and he spins and shoots back, but can't unstick.*

**Steps to reproduce**: *Unsure.
![stuck_bot](https://user-images.githubusercontent.com/2953226/73865556-ad205a80-4800-11ea-9396-d1e343215534.png)
*

**Comment by Anuken** [comment]
The unit is stuck in the water due to random map distortion affecting the spawn position. This is easy to fix, but I won't be touching maps as they'll be reworked in 6.0 anyway.

**Comment by edent** [comment]
I've just had this exact bug on Android. 5-fdroid-104.  This game is amazingly fun :-)

![Screenshot_20200313-111334](https://user-images.githubusercontent.com/837136/76638440-5b2bcc80-6544-11ea-8ccf-c752fc79b0d0.jpg)
