### ISSUE TITLE
Platform: android,   build: 103.4,  issue: *"targetGround": false,* don't work in mod's units

### ISSUE THREAD

**Issue by 228722** [Anuken/Mindustry#1515]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
Unit don't even have a `targetGround` property. [Check the source code.](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/type/UnitType.java)
