### ISSUE TITLE
When many items are burnable, generators info tends to go off screen

### ISSUE THREAD

**Issue by Famous5000** [Anuken/Mindustry#1516]
**Platform**: Windows

**Build**: 103.4

**Issue**: Title says it all.
![image](https://user-images.githubusercontent.com/9399230/73897400-d2ca5580-483a-11ea-9e01-77b101e80b22.png)

**Steps to reproduce**: Add a mod that includes a bunch of fuels, then inspect a generator's info page.

**Comment by ZkyLB** [comment]
amazing

**Comment by Anuken** [comment]
There's a scrollpane for that. Scroll to the right.

**Comment by ZkyLB** [comment]
it does look weird tho. :shrug:
