### ISSUE TITLE
Version 4.0 possible bugs

### ISSUE THREAD

**Issue by Malmik** [Anuken/Mindustry#152]
Hi, on android version of game:

1. Drone factory stops working after creating one drone. 
         Destructing the factory and making new in the same place does not destroy previous drone and allow to make new, but problem repeats

2. Maby i do not know how to use biomas compressor, but when i give it this green thing, water and power, output is water, not oil

**Comment by Sonnicon** [comment]
The first point is not a bug, but a feature. One drone per factory.
As to the second point, I'm not sure what's going on if you're outputting water. Possibly a bug.

**Comment by Malmik** [comment]
So drone shouldn't broke or dissapear, if "his" factory is destroyed?

**Comment by Anuken** [comment]
No. It's intentional.

For 2), Biomass compressors **don't need water**. Read the block description. If you're going to dump water in, it's just going to be dumped out.

**Comment by Malmik** [comment]
Tried again witouth water, and it is still not producing oil

**Comment by Anuken** [comment]
Have you created a new biomatter compressor, made sure all the correct inputs are there, and waited a few minutes for it to produce a visible amount of oil?

**Comment by Malmik** [comment]
Wow sorry, yes, i just had to wait for oil to produce. Don't you think production of it is too slow? I tried to make autonomic power generator using two cultivators, two biomatter compressors and turbine generator, and it couldn't get working witouth aditional power source.

**Comment by Anuken** [comment]
It *is* slow, which is why oil production has been increased ~5x in the latest commit.

**Comment by Malmik** [comment]
Ok, i give up. Tryhard to be a bugtracker, but i don't track trello/commits so this is useless xD
