### ISSUE TITLE
[petition] github instead of feathub

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1520]
> petition set in motion by @Quezler and @CaribbeanMax

feathub has a fair amount of shortcomings:
- poor text formatting
- nonexistent notifications
- state changes are not listed (e.g. when something was closed)
- pasting a github link to an issue/pull is a one way reference (github has "got referenced" alerts)
- ssl breaks every so often
- only anuke is allpowerful there 

i propose moving the suggestions to e.g. `Anuken/MindustrySuggestions` (aka: not main repo):
- so we can have proper markdown support
- we can watch the repo and its notifications 
- its more easy to notice when something got closed
- references to issues/pulls/code on this repo nicely link two ways
- ssl barely breaks
- you can give a handful of contributors write access to moderate the place (closing duplicates, labeling appropriately, closing things that have been merged or are known to never be implemented, etc)

the only real downside would be that you lose the current pool of suggestions & votes, but since everyone already has a github account nothing will stop them from making any in the future.

also you'd lose the png list at the bottom of the readme, but one can still sort through github based on thumbs up and down, so its only mildly gone.

🥔

**Comment by ZkyLB** [comment]
YES

**Comment by Anuken** [comment]
> one can still sort through github based on thumbs up and down

I forgot that this was a thing. This seems reasonable; I'll start the migration soon.

**Comment by egg-chad** [comment]
egg approve :egg:

**Comment by DeltaNedas** [comment]
i also approve

**Comment by QmelZ** [comment]
i also also approve

**Comment by Anuken** [comment]
[Implemented.](https://github.com/Anuken/Mindustry-Suggestions)
