### ISSUE TITLE
Migration of save file from Steam to Android

### ISSUE THREAD

**Issue by Akxe** [Anuken/Mindustry#1521]
**Platform**: *Android/~~iOS~~/~~Mac~~/~~Windows~~/~~Linux~~/Windows Steam*

**Build**: *The build number under the title in the main menu. Required.*
PC (Steam) 103.4
Android: 103.4

**Issue**: *Explain your issue in detail.*
Cannot open save dump from PC on android phone. It stays grayed out as an unsupported file. I can, however, import exported save file from android in it.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
1. Export game data on PC (Steam in my case)
2. Save it to google drive, or move it in any other means to a location accessible by phone (ex. download it into storage)
3. (Try to) import save & settings into the phone
  a) You'll see the file, but it will stay grayed out.

----------

Few things I tried:
* Export from phone and copy paste data from PC dump to Phone dump.
* Opening the zip in windows explorer shows empty folder (WinRar can open it, though it might interest you too)

--------

Can we have some buttons to migrate saves only? I would love to play it on both but I don't want it to migrate settings and would love it to be 1 button thing. Even if both would be required to run at that point :)

**Comment by Anuken** [comment]
Where is the file "grayed out"? What is its extension? Send a screenshot of what it looks like on Android.

**Comment by Akxe** [comment]
![Screenshot_20200206-143243](https://user-images.githubusercontent.com/2001798/73941538-c05d2400-48ed-11ea-9425-f39074527f0f.png)

**Comment by Anuken** [comment]
It looks like the Android file browser doesn't like the Steam save because it doesn't think it's a zip, despite the fact that it obviously has a zip extension and the accepting file type is set to `application/zip`.

**Comment by Akxe** [comment]
Indeed. And I would like to point out, that neither of these "zip" files can't be opened by windows explorer. (Only shows empty folder)

Yet, google drive & WinRAR can show insides and their content have same folder structure (even names are the same)

**Comment by Anuken** [comment]
I'll make the file browser accept any type of file. Not a very good fix, but since this is really an issue with Android there's not much more I can do.

**Comment by Akxe** [comment]
It is problem with the file. It ain't fully spec zip file. Maybe try different to making library?

**Comment by DeltaNedas** [comment]
also ill just chirp in and say that exported zips open fine in ark

**Comment by Akxe** [comment]
@DeltaNedas what is ark?
