### ISSUE TITLE
Armor is almost irrelevant

### ISSUE THREAD

**Issue by CaribbeanMax** [Anuken/Mindustry#1523]
**Platform**: all

**Build**: v103.4

**Issue**: The maths behind the `calculateDamage` function in both `Player.java` and `Unit.java` makes the value of `status.getArmorMultiplier()` close to irrelevant towards the damage taken.

**A few examples**
![table](https://user-images.githubusercontent.com/23070598/73937789-22199000-48e6-11ea-9034-afa878a943d4.png)
(Note that you can't even spawn shielded bosses with the normal map editor. That line is just to show that the technically highest possible armor multiplier on units still only results in a mere 8% damage reduction.)

As shown the only part that has a major impact on damage taken is the special case that `mech.getExtraArmor` provides for Omegas due to its high range from 0f-30f.

Now i obviously don't know how impactful you want armor to be, but if noticeably more durable bosses and incorporating Cryofluid Waves as a DpS booster are something you want in the game then changing the Omega bonus to a multiplier by shifting its range from 0f - 30f to something like 1f - 1.45f (which would keep the current maximum damage reduction intact) and then using something like
`amount / (status.getArmorMultiplier() * mech.getExtraArmor(this));`
could make more sense. Now this would result in tripling the effective HP from bosses which might upset current balance a bit.
So if thats too much of a change you could alternatively either add a root for reduced scaling like
`amount / (Mathf.sqrt(status.getArmorMultiplier()) * mech.getExtraArmor(this));`
(at the cost of a really frequently called function now having to compute a root every time ...)
or just tweak some of the bigger armor multiplier values from status effects.

**Comment by Anuken** [comment]
Noted, but this won't be too relevant in 6.0, as most of the entity code (including mechs, armor and status effects) will be scrapped.
