### ISSUE TITLE
Type Support for mods' script

### ISSUE THREAD

**Issue by Himself65** [Anuken/Mindustry#1524]
using some library (like [typescript-generator](https://github.com/vojtechhabarta/typescript-generator)) to generate Type for JavaScript/TypeScript. It will be **very** friendly for coding script on mods.

**Comment by Anuken** [comment]
Someone has already done this and published the type definitions. I won't be doing anything official for typing until scripting is stable.

**Comment by Quezler** [comment]
pinging @KSean222
