### ISSUE TITLE
Bridges not storing item orders correctly.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#1527]
**Platform**: Windows 64 bit (works on all platforms)

**Build**: 103.4 (works on previous versions as well)

**Issue**: when you input items into a bridge and don't output them right away the order you put them in doesn't save.

**Steps to reproduce**: Put down 2 bridge conveyors connected but don't have them outputting anywhere, then put some random items in, then put an output conveyor and the items come out in the wrong order.

**Comment by Quezler** [comment]
this is normal 😗

**Comment by Legomonster33** [comment]
> this is normal 😗

but junctions store item orders so why cant bridges.

**Comment by Quezler** [comment]
> but junctions store item orders so why cant bridges.

because bridges do not remember which order the items came from.

iirc they output their items by going through the resources in the order that they appear in sorters, but in `104` they will loop though all the items they have so nothing lets left behind, but not in order.

**Comment by Quezler** [comment]
see #1495 for more details regarding how unloaders/bridges will act in the next release 🔬

**Comment by Legomonster33** [comment]
oh
ok

**Comment by Legomonster33** [comment]
it would be useful if they stored item orders similar to junctions but ok

**Comment by Quezler** [comment]
its best practice* for bridges/conveyors to only contain a single item regardless, and if your bridge clogs with different items that get stuck it means your line is over its capacity anyways 🤔
> \* [citation needed]

**Comment by Legomonster33** [comment]
it still would be very useful to the technical community if they could store the order of items
jus sayin
