### ISSUE TITLE
[MOD] When ore toughness is too high, no mechs can mine it properly, regardless of their drill strength

### ISSUE THREAD

**Issue by Famous5000** [Anuken/Mindustry#1529]
**Platform**: Windows

**Build**: Steam 103.4

**Issue**: cpt_waterbubble and I were working on a few mods, and we ran into a problem. He wants high-end drills to mine his tungsten, and I wanted my mech to mine its tungsten. 

**Steps to reproduce**: Set the toughness of the item to anything higher than 7. Set the mech drill strength to the same. You will get the same result.

I tagged this with [MOD] because I'm pretty sure it's an issue with the HJSON modding API. I'm betting this may not be an easy fix, but I'd appreciate it if you'd fix it.

**Comment by Quezler** [comment]
then set the hardness for the mech higher as well?

**Comment by Famous5000** [comment]
You can see that the unit is able to drill it, but no items appear on the back. See the following screenshot. https://steamuserimages-a.akamaihd.net/ugc/773992883139878819/94D2A93C4B7BC1CB640F8704FE6FB080C0580900/

**Comment by Quezler** [comment]
~no mechs can mine it~ no items returned from/while mining

**Comment by Famous5000** [comment]
I should clarify that.

**Comment by Quezler** [comment]
looks like this [line](https://github.com/Anuken/Mindustry/blob/44ef5148b477756d4c5ae39ff006126b979adb24/core/src/mindustry/entities/traits/MinerTrait.java) is the culprit 🤔

**Comment by Famous5000** [comment]
Yeah, that does seem like it. Thanks for looking into this, @Quezler!

**Comment by Anuken** [comment]
Fixed in the 6.0 branch(es) due to slightly different mining mechanics; the change won't be in 5.0.

**Comment by Quezler** [comment]
for (future) reference: 8a9c92227d80d4407f6eb78b4e3b016fe072fd55
