### ISSUE TITLE
Multiplayer feature request!!!

### ISSUE THREAD

**Issue by Malmik** [Anuken/Mindustry#153]
Hello, i was wondering about adding skirmish option for Mindustry 4.0, esspecially there is fog of war now. Here is my concept:

1. If map is created by someone, player positions are set by creator, but in random map mode, players start near opposite corners.

2. Every player can build only inside his "zone" that could be marked by dotted line.

3. Every some period of time (for example every 5, 7, 10 seconds based on game speed setting) zone will increase in size (For example if zones would be circles, their diameter could incrase by one square or more, and if zone would be square, it could increase in widht and height)

4. Naturally over time, player zones will overlap. They could build in overlaped places together. Now, when player 1 builds a turret, it could automatically damage player 2 structures. Same thing with drones. This, combined with mindustry nature, could create most space efficent strategy ever! Quick reaction time will be also key to victory.

5. First player that will destroy others main base is the winner!

**Comment by TheMarksman-ES** [comment]
Question: have you even seen the discord?

**Comment by TheMarksman-ES** [comment]
I'm gonna address only two thing. And that is that a) you need to read the damn Trello.
b) PvP will only come in 5.0.
So before you even suggest anything. You better read before you type.

**Comment by TheMarksman-ES** [comment]
Also, why the f-ck is this in issues? It should go to PR

**Comment by Anuken** [comment]
@TheMarksman-ES Please don't post multiple times in a row when one message can suffice; this isn't Discord. There's no need to be that rude.

@Malmik PvP is only planned for versions past 4.0, and I have my own ideas for its implementation. [See the trello.](https://trello.com/b/aE2tcUwF/mindustry-trello)

**Comment by Malmik** [comment]
Thanks and sorry for my stupidism.
