### ISSUE TITLE
Junctions and sorters don't work around corners

### ISSUE THREAD

**Issue by Eldoofus** [Anuken/Mindustry#1530]
**Platform**: *Windows (Not tested on other platforms but probably applies too)*

**Build**: *103.4*

**Issue**: *Sorters and junctions don't work around corners but work in a straight line. Is this intended behavior?*

**Steps to reproduce**: Create the structures in the picture
![Screenshot (36)](https://user-images.githubusercontent.com/49511921/74074903-2e6b2d80-4a4b-11ea-8a85-1e218e242c3b.png)

**Comment by Anuken** [comment]
This is intended. 3 transportation blocks with an 'instant' component can't transfer to each other in a row, to prevent infinite loops.

**Comment by Anuken** [comment]
Honestly, the code for those blocks has been changed so many times that I don't remember the reasoning, or whether that reasoning is still valid.

**Comment by Eldoofus** [comment]
lol ok

**Comment by geoffrey1900** [comment]
he doesnt mean that he means a l of junction sorter junction

**Comment by geoffrey1900** [comment]
vs a line of junction sorter junction stright works but l clogs

**Comment by geoffrey1900** [comment]
with a overflow it works because ???
