### ISSUE TITLE
Multiplayer bug

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry#1531]
Platform:Android

Build : 103.4

Issue : in multiplayer at random times (mostly near a enemy's base) I will die without any warning,shot, or sound.

Steps to reproduce : randomly in multiplayer;mostly in laggy servers.

**Comment by Anuken** [comment]
Probably caused by clusters of turrets or enemies reacting slower clientside and killing the player before they notice. Won't fix.

**Comment by indielm** [comment]
use /sync 
frequently
you likely were desynced from seeing the bullets
