### ISSUE TITLE
Game Reset

### ISSUE THREAD

**Issue by atiedebee** [Anuken/Mindustry#1536]
Platform: Android
Build: 103.4

Issue:
The game decides to reset itself for some odd reason. 

Steps:
I don't know any detailed steps. I finished the tutorial level. Went to the tech tree, unlocked some new builds and played the second level.
Halfway in the level I quit the game. I believe I did save the game before closing it. (I did play the game offline. when I came back I had my data turned on. I don't know if this could cause it but I noted it anyway.) When I came back an hour later and reopened the game I got send back to the tutorial level and my progress was lost.
It wasn't a lot of progress but the game isn't very replayable after it happens.

**Comment by Anuken** [comment]
Duplicate.

**Comment by Jonny007-MKD** [comment]
#1660
