### ISSUE TITLE
Shuffling setting ignored when hosting first map

### ISSUE THREAD

**Issue by Milinai** [Anuken/Mindustry#1538]
**Platform**: *Linux*

**Build**: *103*

**Issue**: *The server hosts a custom map when shuffle builtin is set.*

**Steps to reproduce**:
- add a custom map to a server in the custom map directory (in my case named `blank`).
- set shuffle mode `shuffle builtin`.
- start the server `host`.
- `blank` may now be hosted.

**Comment by Anuken** [comment]
`host` doesn't use the shuffle mode, as shuffling only happens after ends of games. The command description says `Will default to survival and a random map if not specified`. Specify a valid map if you want something specific.
