### ISSUE TITLE
[Modding] Texture doesn't feat with 2*2 bridges

### ISSUE THREAD

**Issue by galyfray** [Anuken/Mindustry#1542]
**Platform**: *Windows*

**Build**: *103.4*

**Issue**: the texture of the link doesn't feat with size 2 bridges even when making 64\*64 or 64\*32 textures.

**Steps to reproduce**:  create a bridge with size 2 and place it in game.

[here](https://cdn.discordapp.com/attachments/666297940960346189/676205275702624258/Capture.PNG) is an exemple (with bad textures but an exemple)

**Comment by Anuken** [comment]
Bridges aren't supposed to work with 2x2 blocks. Even if the texture was functional, you would run into all sorts of issues.

**Comment by galyfray** [comment]
Well even if bridges aren't supposed to work with 2x2 block they work fine I uses them in a Map for hours without any trouble except with the textures.
