### ISSUE TITLE
Destroyed block ghosts not appearing in b103

### ISSUE THREAD

**Issue by gm907** [Anuken/Mindustry#1543]
Windows
Build 103.4

`Graphics` > `Display Destroyed Blocks` Enabled, or Disabled
Blocks broken by enemies, fire or explosions don't show.

**Comment by Anuken** [comment]
Ghost blocks only appear on singleplayer worlds when a block is selected.

**Comment by gm907** [comment]
Why the change from previous builds?

**Comment by Anuken** [comment]
Those blocks were not actually interactable. Removing them did not affect drones.

**Comment by gm907** [comment]
Then I understand.. but it was particularly useful for rebuilding other's designs faithfully after enemies destroyed them.
