### ISSUE TITLE
Minor Issue - Text is cut off in the Core Database screen

### ISSUE THREAD

**Issue by CalculusMaster** [Anuken/Mindustry#1545]
**Platform**: *Mac*

**Build**: *Steam build 103.4*

**Issue**: *Titles of each section in the core database have the first letter either entirely clipped off or partially (see screenshot below)
![Screen Shot 2020-02-10 at 07 52 00](https://user-images.githubusercontent.com/31602102/74160365-82584c80-4bda-11ea-88c9-96fde17eb7bf.png)
*

**Steps to reproduce**: *Open the core database screen*

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/74160843-06ff9680-4bec-11ea-99c2-5c2f875c2976.png)

I don't have this problem, even when resizing the window to different resolutions. The only way I can make this happen is if I open the window a very specific size and intentionally pan over to the left to hide the first letter.

Either way, the unlock dialog will be changing in 6.0, so I won't be fixing this.
