### ISSUE TITLE
P

### ISSUE THREAD

**Issue by Ciaran876** [Anuken/Mindustry#1547]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Quezler** [comment]
0,o

**Comment by Anuken** [comment]
ok

**Comment by QmelZ** [comment]
Hi
