### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by sourleemon** [Anuken/Mindustry#1552]
**Platform**: Windows (Steam)

**Build**: Steam Build 104

**Issue**: When being invited to join an online multiplayer game with my friends, while connecting the game crashes. According to the GUI labeled "oh no" that shows up, it lists "BufferUnderflow" under the crash log save location, which I assume is the problem. I have tried both reinstalling the game and restarting my computer, but neither worked.

**Steps to reproduce**: In a Discord voice chat with the friends I was to attempt playing with, and with various Google Chrome tabs open. Other than that, I was simply invited invited to join their game through Steam whereupon the crash occurred.

I have attached the latest crash log and the file labeled "last_log", according to which says "[I] Server: false". Whatever causes that may be the problem.

[crash-report-02_11_2020_19_26_47.txt](https://github.com/Anuken/Mindustry/files/4189272/crash-report-02_11_2020_19_26_47.txt)
[last_log.txt](https://github.com/Anuken/Mindustry/files/4189275/last_log.txt)

**Comment by Anuken** [comment]
Was everyone involved running build 104 at the time?

**Comment by sourleemon** [comment]
They weren't, so they updated just now and that fixed the problem
