### ISSUE TITLE
Changing sorter item does not change color in minimap

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry#1556]
**Platform**: *Windows*

**Build**: *104.1*

**Issue**: *Changing the sorter/inverted sorter item does not change color on minimap (it only has the color of when it was placed)*

**Steps to reproduce**: *Place a sorter/inverted sorter and change the item*

**Comment by Quezler** [comment]
Because the color for a block gets calculated when its first placed (or loaded after a e.g. `/sync`) 😗 
After that it just stays cached for as long the world is loaded, if you want to build pixel art, sync periodically to see your result 🙂
