### ISSUE TITLE
Android Build BE:7290 Vanilla:14.1 Silver bars crash whenever ther attempt to cross a junction they try to go through a junction. Example mod and vault mod game me 2 silver crags, and the bug happens in both, BE version corrupts save while Vanilla resets progress. To test: Go so silver crags, run a silver line and cross another material line through it

### ISSUE THREAD

**Issue by MexicanBoi2002** [Anuken/Mindustry#1559]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
I can't reproduce this problem at all, and you haven't filled out the issue template correctly.
