### ISSUE TITLE
Game crashed starting a map (possible save file existed) (nightly build)

### ISSUE THREAD

**Issue by ziggystar** [Anuken/Mindustry#156]
[crash-report-28-07-18 3.54.30.txt](https://github.com/Anuken/Mindustry/files/2238028/crash-report-28-07-18.3.54.30.txt)

**Comment by Sonnicon** [comment]
The bleeding edge builds are unstable, and the developer does not wish to have bug reports about them as they usually contain unfinished content. I suggest sticking to the official alphas. As to your problem, try deleting/moving your save file data.

**Comment by Anuken** [comment]
This is indeed an issue with previous bleeding edge saves being incompatible with the latest ones. Still, crashing is probably not the right behavior here.
