### ISSUE TITLE
16 bit rgba sprites cause mindustry to crash

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1560]
**Platform**: GNU/Linux

**Build**: 104.1, latest master

**Issue**: 4 mask sprites in my mod cause the game to crash

**Steps to reproduce**:
1. import mod
2. start mindustry
3. look at logs

my mod: [zip](https://github.com/Anuken/Mindustry/files/4192252/resources.zip)
log: https://paste.ee/p/P3ZLm

**Comment by DeltaNedas** [comment]
it seems it is caused by ingot-alloy.png

**Comment by DeltaNedas** [comment]
ok the problem is that mindustry doesnt support 8 bit rgba???

**Comment by DeltaNedas** [comment]
```
ingot-alloy.png: PNG image data, 32 x 32, 16-bit/color RGBA, non-interlaced
ingot-dull.png:  PNG image data, 32 x 32, 16-bit/color RGBA, non-interlaced
ingot-rare.png:  PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
ingot-shiny.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
```

**Comment by Anuken** [comment]
I'm not going to be messing with the PNG decoder. Use normal PNGs; people have been making sprites perfectly fine until now.

**Comment by DeltaNedas** [comment]
will do
