### ISSUE TITLE
[severe]

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1561]
**Platform**: GNU/Linux

**Build**: 104.1, latest master

**Issue**: const variables can be modified without any exception.

**Steps to reproduce**: 
```js
const x = 2;
x = 4;
print("x is " + x  +" lol (also means no exception thrown!)");
```
see below ![here](https://user-images.githubusercontent.com/39013340/74340003-0b1ee600-4d9d-11ea-9a93-63fe1a7db0e8.png)
also made https://github.com/mozilla/rhino/issues/647 but theres another 2 year old const scope bug open so i doubt mozilla will fix it, too busy laying off employees who actually work on stuff

**Comment by Anuken** [comment]
I don't see Mozilla being able to do much without a reproducible code example. 
This seems to do it.
```java
        Context c = Context.enter();
        Scriptable scope = new ImporterTopLevel(c);
        c.evaluateString(scope, "const x = 2; x = 55; java.lang.System.out.println(x)", "test.js", 1, null);
```
This is Rhino bug, not a Mindustry bug, so there's nothing I can do. Closing.
