### ISSUE TITLE
Server listing duplicates when leaving app in background and coming back

### ISSUE THREAD

**Issue by azekillDIABLO** [Anuken/Mindustry#1565]
**Platform**: *Android*

**Build**: *release*

**Issue**: *When the global servers are listed I left the app and went back on it a second later and all servers where listed twice. It can be reproduced again and again.*

**Steps to reproduce**: *go to server list, leave app in background, come back, servers are listed twice or more.*

**Comment by Quezler** [comment]
i've had this happen before as well, also on android 👍

**Comment by azekillDIABLO** [comment]
So fast! Thank you!
