### ISSUE TITLE
apks are available in mindustrybuilds/releases but not mindustry/releases

### ISSUE THREAD

**Issue by egg-chad** [Anuken/Mindustry#1576]
**Platform**: android/web

**Build**: 104.1

**Issue**: apks are not on mindustry/releases
but they are on mindustrybuilds/releases
🤔 

**Steps to reproduce**: https://github.com/Anuken/Mindustry/releases
https://github.com/Anuken/MindustryBuilds/releases

**Comment by Anuken** [comment]
Use itch.io for Android releases.
