### ISSUE TITLE
Game Frozed

### ISSUE THREAD

**Issue by 7yp0d47416** [Anuken/Mindustry#1580]
![I BROKE IT](https://user-images.githubusercontent.com/61036949/74498409-2c094780-4f13-11ea-8c42-bb3931a81fe8.png)
**Platform**: *Windows*

**Build**: *104*

**Issue**: *Well yes, I was middle playing game for few hour, but suddenly Game Frozed*

**Steps to reproduce**: *Play for few hour, put computer sleep, open computer Play for few hour again and it frozed.*

**Comment by Anuken** [comment]
I can't fix freezes unless they're reproducible with a very specific action or you have a crash log. This could have been caused by absolutely anything.
