### ISSUE TITLE
MASSIVE fps drop with modded floor

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1587]
**Platform**: GNU/Linux
**Build**: 104.1, latest (like a day old at most) master
**Issue**: Modded tile, "snad" in my example, creates a massive fps drop when a map is filled with it.
**Steps to reproduce**:
1. import my minimal example [here](https://github.com/Anuken/Mindustry/files/4205313/snad.zip)
2. make a map, fill floor with blue snad, add a core
3. load it up
4. look at framerate
5. repeat with stone/shale/etc/example mod gold sand
6. look at much better framerate

i dont know if its cpu or gpu lag
i believe its because snad is in json, not hjson???
i replicated issue reported by iow#5648 on the discord server

as in mod description, i go from 300 to 57 fps on my i3 5005-u, hd 5500

**Comment by Anuken** [comment]
**Follow the Mindustry sprite directory structure.** When packing sprites, Mindustry uses the folders to figure out which atlas page to put sprites into. In your case, sprites aren't placed into the `environment` folder, which puts them in a different page and causes massive amounts of texture switching.
