### ISSUE TITLE
/sync resets spawning progress bar

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry#1589]
**Platform**: *Windows*

**Build**: *104.3*

**Issue**: *Doing `/sync` while respawning causes the progress bar to reset its value to 0 (the respawn time is unaffected)*

**Steps to reproduce**: *Do `/sync` while respawning*

![Mindustry 2020-02-14 21-44-02](https://user-images.githubusercontent.com/58778985/74580669-9e5e4400-4f74-11ea-8505-afc28ae69864.gif)

**Comment by Anuken** [comment]
Spawn time isn't synced. It's supposed to reset.
