### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by Galaxy-boop** [Anuken/Mindustry#1590]
**Platform**: 
*Android*

**Build**: *Frozen Forest.*
**Issue.**
I had a copper wall diagonally next to a map tile and it made 2 dangers try to pass through. 

**Steps to reproduce**: 
*I was just building my based trying to survive and noticed it,i dont know how long it had been happening *

**Comment by Quezler** [comment]
do you have a map save / screenshot?

**Comment by Galaxy-boop** [comment]
No sorry

**Comment by Anuken** [comment]
Without reliable pictures or steps to reproduce this, I can't fix anything.
