### ISSUE TITLE
Unloader selection page not showing/ random armoured conveyors changed to veryical

### ISSUE THREAD

**Issue by rednax360** [Anuken/Mindustry#1591]
**Platform**: *Android/iOS/Mac/Windows/Linux*

104.4**Build**: *The build number under the title in the main menu. Required.* 

**Issue**: *Explain your issue in detail.*
The unloader popup only displays the top two rows fully, and half the third. The rest is invisible and inaccessible.
And approximately 50 armoured conveyors switched positions to vertical, (north facing) this resulted in a lot of chaos. Reverted to a 103 game save, and the same problem arouse. Despite the problem not being present when the save was created
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Loaded up a game save, also have reset the app, and restarted the device.

**Comment by Anuken** [comment]
The first issue is a duplicate, and the second is most likely a save corruption.
