### ISSUE TITLE
Modding tech tree issue

### ISSUE THREAD

**Issue by GaviTSRA** [Anuken/Mindustry#1598]
Windows

104

I'm making a hardcore mod for mindustry and i tried to change the tech tree. When i write: "research: conveyor" in my router.hjson file it just duplicates the router in the tech tree. Maybe i'm doing something wrong but i don't know what.

Make a router.hjson file and put "research:conveyor" in it to reproduce.

**Comment by Anuken** [comment]
You can't change research of existing blocks.
