### ISSUE TITLE
Map modding issue

### ISSUE THREAD

**Issue by GaviTSRA** [Anuken/Mindustry#1599]
Windows

104

I'm making a hardcore mod for mindustry. I edit the build-in maps as well as the blocks.
I edited Ground zero and frozen forest without issues. The i tried to edit desert wasteland and (after some time that i needed to realise that it's called desertWaste) i did it. You have to beat frozen forest wave 40 to unlock it, BUT it is still at the same spot in the campaign map view. Also its not connected to frozen forest but it is to ground zero(but you dont need to do anything in ground zero to unlcok so thats weird). Pls fix!

See above

**Comment by Anuken** [comment]
I don't know what your exact issue is, but 6.0 is throwing out the concept of zone 'connections', so I won't be making any fixes to that system, as all of it will be deleted anyway.
