### ISSUE TITLE
License

### ISSUE THREAD

**Issue by est31** [Anuken/Mindustry#16]
Hi, the project seems to be missing a license. I recommend the [MIT license](https://choosealicense.com/licenses/mit/).

**Comment by Luxray5474** [comment]
Thought that too. Although it's ultimately up to Anuken to get one.

**Comment by Anuken** [comment]
Fair enough. Added one just now.

**Comment by est31** [comment]
@Anuken thank you! @Luxray5474 you seem the only other contributor, I assume you agree?
