### ISSUE TITLE
Attack units do not seek out enemy units on attack mode

### ISSUE THREAD

**Issue by darklordabc** [Anuken/Mindustry#1600]
It seems like a big oversight that attack units will hover around the spawn area as units slip past them, very close. Attack units should actively seek out the nearest alive enemy unit when on attack mode, would make them much more fun and useful.

**Comment by micoplasma** [comment]
whatever blocks or units inside the spawn area gets destroyed when the wave starts
they hover near it to avoid this
and their target priority is not units to begin with

**Comment by darklordabc** [comment]
I have been playing campaign for a while now and I dont see what else there is to target, I figure that later there are enemy buildings but a lot of new players are going to build these units without knowledge of buildings and be confused why their units arent attacking the enemies, I get it may be a feature, but for lots of the campaign it will seem like just a bug.

**Comment by Anuken** [comment]
This isn't a bug or an oversight.

**Comment by darklordabc** [comment]
How is this intended behavior? Building units while the majority of them stand idly by near the edge of the enemy spawn and do nothing? That is dumb as hell.

**Comment by Anuken** [comment]
Yes, building units in survival maps is a very dumb idea. They're not supposed to be used in that mode at all. Many updates ago, you weren't even *allowed* to build unit pads in survival to prevent these sort of complaints.

**Comment by darklordabc** [comment]
You do realize this is pretty bad user experience? Im playing campaign and I was excited to unlock these technologies now I'm hearing that they are practically useless. I'm disappointed to now know that some technology will be pointless for me to upgrade, poor user experience. Id recommend removing the useless technology from campaign or modifying it so it becomes useful.

**Comment by micoplasma** [comment]
these units are not intended for survival modes, rather use them for their intended purpose, attack modes and pvp.
they are rather supplementary in survival if you really plan on using them, use the command center for better controls.
survival maps are mostly based on turret defence.
