### ISSUE TITLE
Block status change

### ISSUE THREAD

**Issue by GoldAndRedstone** [Anuken/Mindustry#1601]
**Platform**: *Android*

**Build**: *104.1*

**Issue**: *Block status of flowgates change depending on the direction of in- and output*

**Steps to reproduce**: *Scidustry member, i stumbled upon this Bug during testing of ingame mechanics. If you place what we call "item-lock", it will break the behavior of flowgates depending on its in-and output direction. To create an Item Lock, you need to place any item-source, right below an overflowgate, left to the gate an inverted sorter, colored like the item-source, and a incinerator left to the source. Now it should be 2×2 in diameter. Powering the incinerator let items pass that are transported into the gate (and are differend to the source-item) on the source Side, and it will go straight trough the sorter on the incinerator Side. If you reload the map while an Item is staying in front of the flowgate on a conveyor belt, it will pass through (we call this "item-slip", and its probably Like that because of the time and priority the game uses to load objects on the map) If the whole structure is rotated two times so the sorter faces the right Side, conveyors loaded with items and standing in front of the flowgate add one Item each time reloading the map, counted it to 80 items before stoping the experiment. In more complex item-lock designs, the behavior of flowgates is even stranger, some of them lead to whole new propertys. I dont expect this bug to be fixed soon since its unlikely to be reproduced during normal gameplay, but it concernes us because if flowgates would work as intendet, it would lead to very Special applications in constructing computing logic within the Game. *

**Comment by Anuken** [comment]
This is caused by overflow gates simply not saving their items on a save reload.
