### ISSUE TITLE
Strange class name

### ISSUE THREAD

**Issue by militaryCoder** [Anuken/Mindustry#1602]
Don't know for sure is it a mistake or not, but it seems like typo in here (I mean strange class name that represents a file-access class).
[Here is an error.](https://github.com/Anuken/Mindustry/blob/b96d5c417f4f9811b14351053dd66467b42ef36b/core/src/mindustry/ctype/Content.java#L57)

**Comment by DeltaNedas** [comment]
FileHandler was its old clumsy name
its now Fi, it cant be File because internal java name
