### ISSUE TITLE
Duplicate schematic names

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry#1604]
**Platform**: *Windows*

**Build**: *104.3*

**Issue**: *Schematics can be renamed to an existing schematic. When attempting to overwrite a schematic it will use the one created first.*

**Steps to reproduce**: *Rename a schematic to one that already exists.*

**Comment by DeltaNedas** [comment]
schematics are stored as unix timestamps

**Comment by Katsute** [comment]
Since creating a schematic with the same name forces you to overwrite an existing, I assumed that having multiple schematics with the same name is something that isn't supposed to happen.

**Comment by Anuken** [comment]
There isn't really any reason for duplicate schematic names to be prevented, so I could remove that dialog.

**Comment by Anuken** [comment]
2038409283a45c604ac4d38898e50152084bad3e
