### ISSUE TITLE
Negative drag

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1606]
**Platform**: *Windows*

**Build**: *104.2*

**Issue**: *The built in bullets _missileSwarm_, _missileJavelin_, and _missileRevenant_ have negative drag. But soon some further investigation, negative drag actually does nothing. I made something with bullets that have -10 drag, but they don't accelerate.*

**Steps to reproduce**: *Well, I was kidding a turret and wanted its bullets to accelerate, but then negative drag ended up having no effect. If I wasn't typing on mobile, I would send a link.*

**Comment by MEEPofFaith** [comment]
Note to self: modding autocorrects to kidding.

**Comment by MEEPofFaith** [comment]
[Ok, here's a link to the file.](https://github.com/K103908/Exotic-Mod/blob/master/content/blocks/bakesale-barrage.hjson)

**Comment by ZkyLB** [comment]
~~i would also like if it is possible to do negative knockback~~

**Comment by Anuken** [comment]
I don't think this is a problem.

**Comment by ZkyLB** [comment]
eat pant

**Comment by MEEPofFaith** [comment]
IS JEANS FOOD?
