### ISSUE TITLE
Pressing F on a single item should not go into schematic mode.

### ISSUE THREAD

**Issue by darklordabc** [Anuken/Mindustry#1609]
**Platform**:  Windows

**Build**: Steam 104.3

**Issue**: I frequently use the F key to get the blueprint for an individual item, like to place more conveoy belts, but when you press F on a single conveyor belt it goes into schematic mode (as if I would want to save a schematic of a single item??), it shouldnt do this, it should select the item as if I selected it from the build menu so that I can drag build like usual. 

**Steps to reproduce**: Press F on a conveyor belt and then try to drag, it won't work. It will be instead stuck on schematic mode with the option to save the schematic.

**Comment by Quezler** [comment]
iirc middle mouse button acts as a pipette

**Comment by darklordabc** [comment]
Oh thats good to know, I would still recommend that pressing f and only selecting one item should act the same as the middle mouse button. I spent the whole game pressing F when I should of been pressing middle mouse and I expect lots of other players will too.

**Comment by Quezler** [comment]
![workflow](https://user-images.githubusercontent.com/3179271/74912386-e939ea80-53be-11ea-978d-8219afc5d3ed.png)

**Comment by darklordabc** [comment]
Okay but is there any situation where pressing F and selecting ONE item should enter a schematic view? That could literally never be useful, but it could very often be annoying, such as it was for me.

**Comment by Quezler** [comment]
i agree, its annoying if a single block schematic doesn't enter normal build mode, but there will always be people using it that way, who will probably get mad that it does not work anymore

**Comment by darklordabc** [comment]
`but there will always be people using it that way, who will probably get mad that it does not work anymore`
How is that possible? The change I'm suggesting would still allow people to use it to clone items but it would enable extra funciton like draging.  The only people that could be upset are the people that are using it to save individual items as schematics, which I don't think exist.

**Comment by Quezler** [comment]
because dragging is (currently) unique to normal build mode, so the easiest way to make one block schematics with it without writing a ton of extra code is to just always cast those schematics to a normal build request

**Comment by darklordabc** [comment]
I dont understand you. Are you saying it would take a lot of code to make the game detect when the player has only selected one item by the F button and switching to regular build mode?

**Comment by Quezler** [comment]
no, that would literally be the best approach, but that would effectively override 1 block schematics, but having them coexist is the tricky part

**Comment by darklordabc** [comment]
1 block schematics? What are those? Is'nt the build menu already a list of all the one block schematics?
![image](https://user-images.githubusercontent.com/16277198/74913607-1c0ecd80-5415-11ea-82d9-3f4ae2a805e2.png)

**Comment by Quezler** [comment]
well technically schematics also hold block configuration values (sorters/bridges/etc)

**Comment by darklordabc** [comment]
I kind of doubt people do that but I could be wrong, if we wanted to save this function only switch to build mode when you are selecting an item that has no configuration options.

**Comment by Quezler** [comment]
that would cause inconsistencies

**Comment by darklordabc** [comment]
If you are worried about inconsistencies it would be better to just disable one unit schematics, as I still think that nobody really does that and have it always default to build mode or make the F button not work on single items that have no configuration options and give a message to the player to use MIDDLE mouse instead.

The problem for me was that the game shows you how to copy via the F key so that's what I learnt and used most often, it never tells you about the middle key afaik.

**Comment by Quezler** [comment]
hmm, true, i get your point 🤔

**Comment by LeoSko** [comment]
I would also prefer F button to act like middle mouse button in case there is only 1 item under selection. For me keyboard keys are always easier to reach than mouse buttons, so I would definitely make use of F more often.
OR
Allow to drag schematics in directions like normal blocks, which would make 2x2 and 3x3 ziplines so much more easier to copy.

**Comment by Anuken** [comment]
> For me keyboard keys are always easier to reach than mouse buttons

If that is the case, rebind the block selection key to something on your keyboard.

I don't see why one unit schematics should be disabled. If you don't want them, don't use them. There may be valid uses cases when someone wants to copy configuration of a block. Either way, this isn't a bug, and shouldn't be reported here.

**Comment by darklordabc** [comment]
Can I just say that this doesn't solve the problem. I've started using the middle mouse button to quickly copy and paste, BUT, the problem is that the schematic tool is the only tool that can copy and paste multiple units, so it results in being forced to use the middle mouse and f button interchangeably, so its no longer just a situation of using the middle mouse button instead.

Maybe if you made the middle mouse button be able to drag and select multiple units than it would completely remove the need for schematic key, but currently, users are forced to switch between two diffrent tools for the same purpose but having different behaviour when using it, its just not good design.

**Comment by LeoSko** [comment]
@darklordabc, that is still not a bug as Anuken told. Let's make a suggestion on feathub (or whatever new platform suggestions will migrate to) and see others reaction.

**Comment by darklordabc** [comment]
Pfft I aint going to feathub that graveyard.

**Comment by KSean222** [comment]
I frequently use single block schematics for things with configurations on them, like sorters.
