### ISSUE TITLE
Phantom Builder Bots Fail sometimes

### ISSUE THREAD

**Issue by darklordabc** [Anuken/Mindustry#1610]
**Platform**:  Windows

**Build**: Steam 104.3

**Issue**: The phantom builder bots will fail to rebuild a structure if a unit is in the position of the structure, furthermore it will never re-attempt to build it, resulting in gradually multiple structures missing. A solution would be to task builder bots to keep re-attempting to build if they fail the first time. 

**Steps to reproduce**: When a unit goes to build a building, if there is a unit already in that position, the build order will cancel. I think this affects phantom bots too. For example, imagine wall defenses, they get destroyed and as they do two things happen, enemy units run into the position where the wall was, and the builder bots run to try to rebuild the wall. The builder bots will fail because there is a unit already in that position. When this occurs the builder bot will never re-attempt to build that wall.
This happened to me in the image below. It has happened frequently before but only recently have I figured out (I think) what is triggering the bug. 
![image](https://user-images.githubusercontent.com/16277198/74913137-2ed4d280-5414-11ea-907a-0a8b4dd37aa4.png)

**Comment by darklordabc** [comment]
I'll assume this is an intended behavior, all poor AI by the units seems to be intended behavour, shame, game would be funner if AI acted with little bit of intelligence.

**Comment by Anuken** [comment]
This specific problem isn't intentional behavior, but in general, many parts of the AI are being thrown out in 6.0. The command center doesn't feel like a very good mechanic for unit control, and making units do everything you want them to do automatically (e.g. patrolling or attacking) isn't working out very well.

**Comment by deee167** [comment]
I have this behavior too and it makes builder drones almost useless as they are unreliable.  Good to know it's not intended behavior.

Are you saying that this issue will be fixed in 6.0 and units will auto-rebuild properly?

**Comment by itcannotbe** [comment]
He's saying that the AI that causes the issue won't be a part of 6.0
