### ISSUE TITLE
Inconsistent behavior when rotating

### ISSUE THREAD

**Issue by Eldoofus** [Anuken/Mindustry#1614]
**Platform**: *iOS (But should work on all)*

**Build**: *104 (But happened in 103 too)*

**Issue**: *The bahavior of certain structures changes when rotated or flipped.*

**Steps to reproduce**: *Recreate the structure in the image and power on and off multiple times. The number of items outputted should be inconsistent.*
![65477011-F682-41F3-85BE-36632BA2674F](https://user-images.githubusercontent.com/49511921/75011424-93e30380-54ba-11ea-8096-400e787fd687.png)

**Comment by Anuken** [comment]
Not a bug. Structures start by outputting to the right regardless or rotation, and some have nondeterministic input.
