### ISSUE TITLE
Units try to get healed by healing points that have no power

### ISSUE THREAD

**Issue by darklordabc** [Anuken/Mindustry#1616]
Its hard to tell by the picture but its several phantom bots flying around a healing point with no power. They do this forever. 
![image](https://user-images.githubusercontent.com/16277198/75030606-93695d80-54f8-11ea-9e46-a23d42df3ee4.png)

**Comment by Anuken** [comment]
This is intentional behavior. The block indexer doesn't keep track of what points have power. Don't keep inactive repair points around.

**Comment by darklordabc** [comment]
Well okay but it makes repair points traps for mechs as it's very easy to lose a power node and then your mechs get stuck because of bad AI, sort of makes them more of a disadvantage than an advantage. Not very user friendly which is odd because this game seems built up from the ground to be a more user friendly version of factorio.

**Comment by KSean222** [comment]
I think it's great, actually. It's an interesting tactic, since lots of attack maps have repair points, so it's possible to strategically attack certain points to trick units.
