### ISSUE TITLE
failed to read "onDeconstructFinish"

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#1618]
**Platform**: Windows 8.1

**Build**: 104.3

**Issue**: when i break any block on the server it gives me "failed to read remote method 'onDeconstructFinish'"

**Steps to reproduce**: my friend restarted the server and i was making a drill array. when i broke a conveyor i got this issue. i get it whenever i break any blocks.

![Mindustry_BqyXVLydRn](https://user-images.githubusercontent.com/59574967/75063563-3f5d7980-54f6-11ea-81d0-f777c6c23c51.png)

**Comment by KK6DOC** [comment]
If you hit details it may help anuke fix it?
But I'm not sure

**Comment by Anuken** [comment]
Already reported.
