### ISSUE TITLE
Spectre 120/sec liquid consumption?

### ISSUE THREAD

**Issue by GrandTeki** [Anuken/Mindustry#1620]
**Platform**: Windows 10

**Build**: 104.3

**Issue**: Contrary to all other turrets, the Spectre needs 10x as much liquid as any other turret (with exceptions like the Meltdown). Since issues like this can arise by misplacing a period/comma while coding, I figured I'd report it.
![image](https://user-images.githubusercontent.com/50800712/75093594-6e6dfc80-5583-11ea-828c-33f8eb6a3eef.png)

**Steps to reproduce**: Check the info menu of the Spectre.

**Comment by Quezler** [comment]
pretty sure this is intentional (its a late game turret after all), so you need thought liquid tank delivery logistics, if this were a bug anuke would probably have already noticed 🤔

**Comment by GrandTeki** [comment]
I understand your point completely. The flat 10x multiplication was just a bit too suspicious, and I figured I'll make sure it is intentional :)

**Comment by Anuken** [comment]
Yes, this was added a long time ago to prevent people from boosting their turrets to ridiculous fire rates too easily.
