### ISSUE TITLE
UUID Bug

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [Anuken/Mindustry#1622]
**Platform**: All ( server ) 

**Build**: 104.3

**Issue**:  UUID bug. Everyone who tries to come in writes to them that "you're already connected" 

**Steps to reproduce**: There was this bug all the time. I don't know what really influenced his appearance.

**Comment by Anuken** [comment]
Already fixed in `master`.

**Comment by MrMasrozYTLIVE** [comment]
Where is it?

**Comment by Anuken** [comment]
The master branch here on GitHub. Not released.

**Comment by MrMasrozYTLIVE** [comment]
I don't understand you. But I'll say this to me the core of the server is: "Server-release"

**Comment by MrMasrozYTLIVE** [comment]
I use server core "Server-release"*

**Comment by valtsu41** [comment]
The update is not out yet.
