### ISSUE TITLE
Infinite Mod Reloading

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#1623]
**Platform**: *Android*

**Build**: *104.2*

**Issue**: *If I 1.import my mod via Github or 2.download a zip file of my mod and import it, Mindustry loads infinitely and crashes. After the crash, game loading is halter at 14%~16%(Sounds).*

**Steps to reproduce**: The mod in question is https://github.com/sk7725/Immundustry , but if there was a problem with my mod, shouldn't a error report occur?*

**Comment by Anuken** [comment]
Fixed; the JSON parser has a bug with an infinite loop that occurs when you have a string with an extra quote at the end. The issue is in cell-fiber:

![image](https://user-images.githubusercontent.com/10100000/75103157-07713780-55c5-11ea-83f1-4db2d571f8c7.png)
