### ISSUE TITLE
Screen 

### ISSUE THREAD

**Issue by evornell08** [Anuken/Mindustry#1634]
**Platform**: *Android/iOS/Mac/Windows/Linux*
iOS 
**Build**: *The build number under the title in the main menu. Required.*
The newest
**Issue**: *Explain your issue in detail.*
Whenever I go to play your amazing game it does not fit my whole iPhone XS Max screen
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
I was just playing

**Comment by DeltaNedas** [comment]
not an issue
do you want it to cut off block selection and minimap?

**Comment by Anuken** [comment]
It's not supposed to.
