### ISSUE TITLE
[Modding] EntityType cannot be set.

### ISSUE THREAD

**Issue by galyfray** [Anuken/Mindustry#1635]
**Platform**: *Windows/All?*

**Build**: *104.1*

**Issue**: we can't set the EntityType field by modding for adding data to the entity it seems that it's rhino's fault who seems to think that protected mean private?

**Steps to reproduce**: 
```js
const things=extendContent(Block, "will-crash-your-game"  , {
    update(tile){
        tile.entity.setHeat(1); 
    },
   entityType: prov(() => {
		return extend(TileEntity, {
			setHeat(heat){
				this._heat=heat;
			},
			getHeat(){
				return this._heat || 0;
			},
			_heat : 0
                });
	})
});
```
 a possible solution would be to add a field inside the TileEntity or BaseEntity definition wich would be an object for allowing modders to store data there but it would only be sidestepping as notice DeltaNedas on discord.

**Comment by Anuken** [comment]
You can:
```js
theblock.entityType = prov(() => extend(TileEntity, {
    //you may only override existing functions here
    config(){
        return 12345;
    }
}))

//calling tile.entity.config() elsewhere gives the expected result: "12345"
```

I don't think you understand the class extending syntax. `entityType` is not a function, it is a field; you cannot place its definition in the braces that are passed when you extend blocks. The **only** thing you may place there is overrides of existing functions. `setHeat`, `getHeat` and `_heat` won't work for this reason.

I'm not sure if adding fields to an extended class is possible at all. Check the Rhino documentation.

**Comment by galyfray** [comment]
well i know we can add new field and function using the extendContent function (wich use the same func in the code as i see) i've never tried overrriding existeing field but i've already tried to set the entity like you did do you have a link to the rhino doc ??

**Comment by DeltaNedas** [comment]
anuke i myself have tried that, entityType, a private field, cannot be set by a mod
i added a setEntity func that does it from java and it worked fine.
the _heat and stuff still worked too, its just protected is seen as private

**Comment by DeltaNedas** [comment]
anuke i myself have tried that, entityType, a protected field, cannot be set by a mod
i added a setEntity func that does it from java and it worked fine.
the _heat and stuff still worked too, its just protected is seen as private

**Comment by DeltaNedas** [comment]
anuke i myself have tried that, entityType, a protected field, cannot be set by a mod
i added a setEntity func that does it from java and it worked fine.
the _heat and stuff still worked too, its just protected is seen as private

**Comment by DeltaNedas** [comment]
im assuming its an internal rhino bug and not an option like boxed types

**Comment by DeltaNedas** [comment]
ok it work
