### ISSUE TITLE
Broken 'rotate' for unloaders

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#1637]
**Platform**: *Android*

**Build**: *104.2*

**Issue**: *If an Unloader block has `rotate: true`, it will start behaving very wierdly. It 1.Only unloads items if the block is updated 2.Orients its rotation near storages, but only 'sometimes' 3.Flickers its rotation while spitting items out and even worse, does 1, 2 or 3 in a random and unpredictable way(this placed unloader does 1&2, that one does 3...). I expected the unloader to either just ignore the rotation at all or unloads from storages that it was pointing to, but...*

**Steps to reproduce**: *Create a Block with `type:Unloader` and `rotate:true`*

**Comment by QmelZ** [comment]
why would you add rotation to unloaders?

**Comment by Quezler** [comment]
related discussion on discord: [link](https://discordapp.com/channels/391020510269669376/663853133587546138/681885040392536079)

**Comment by Anuken** [comment]
Unloaders, routers and other blocks with omnidirectional output use rotation as output direction. Don't set `rotate` to true; these blocks don't support it.
