### ISSUE TITLE
Campaign map being overwritten

### ISSUE THREAD

**Issue by markozajc** [Anuken/Mindustry#1642]
**Platform**: *Linux*

**Build**: *104.2*

**Issue**: *The issue affected the -1st (campaign) save file. It (along with the backup file) was overwritten by the map of a server I have joined shortly after leaving the campaign map. I have unfortunately not been able to reproduce this behavior since then, and am thus unable to provide precise details on how to reproduce it, however it did occur shortly after updating to 104.2 (from 104.1). I still opened the issue as it seems very severe.*

**Steps to reproduce**: 
*1. Exit out of the campaign map
2. Join a server from the global server list*

**Comment by Anuken** [comment]
6.0 doesn't handle/save the campaign in the same way, so this won't be fixed in 5.x.
