### ISSUE TITLE
What about adding some kind of logic power

### ISSUE THREAD

**Issue by mmm1245** [Anuken/Mindustry#1651]
I would be very happy to see something like signals(from factorio) or redstone(from minecraft, project red) and logic gates, maybe computers(from computercraft)

**Comment by DeltaNedas** [comment]
see:
- byte-logic
- byte-logic
- surprise, its byte-logic
- make a mod

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/75616466-389abc00-5b1f-11ea-9367-646c463ac52b.png)

**Comment by mRebornM** [comment]
Roasted lmao
