### ISSUE TITLE
Plastanium Compressor Sprite

### ISSUE THREAD

**Issue by HappyGingerWolf** [Anuken/Mindustry#1652]
**Platform**: Android, but probably all.

**Build**: 104.

**Issue**: The top and bottom arrows on the plastanium compressor are further from the middle and thinner than the other 2.

**Steps to reproduce**: Look at the sprite.

**Comment by KK6DOC** [comment]
Hm it looks correct :L

**Comment by Anuken** [comment]
Not a bug. If you're really annoyed by it, submit a pull request.
