### ISSUE TITLE
Launchpad functionality in multiplayer is broken

### ISSUE THREAD

**Issue by TheFuryBumblebee** [Anuken/Mindustry#1654]
**Platform**: *All*

**Build**: *steam build 104.3*

**Issue**: *Launching items in a campaign zone in multiplayer using a launchpad gives contents to every connected player. This can be game breaking as very new players can get very advanced blocks and items very quickly.*

**Steps to reproduce**: *1. Launch to a campaign zone with enough for a launchpad to work. 2. Host to multiplayer. 3. Have players join. 4. Place and use a launchpad. 5. Have players check tech tree under Launched Items and see that they got the items.*

**Comment by Anuken** [comment]
This is intentional. Why should only the host get the items? If you're playing on advanced maps with advanced resources, then you'll be experiencing high-level content either way.
