### ISSUE TITLE
Alpha mech can fly through walls a few moments after spawning

### ISSUE THREAD

**Issue by mkhan45** [Anuken/Mindustry#1659]
**Platform**: Linux 

**Build**: 104.4

**Issue**: If I hold a direction button while transforming into an alpha mech, at the end I'll fly over walls before completely transforming. If on top of a wall, I can move as an alpha mech as if flying, but once I come down behavior is as normal.

**Steps to reproduce**: Make an alpha mech pad near a wall and hold a direction key towards the wall while transforming.

**Comment by Quezler** [comment]
how is this bad though?

**Comment by mkhan45** [comment]
I mean it's nice as a player, but I don't think it's intended? It's pretty easy to get stuck somewhere with it too.

**Comment by DeltaNedas** [comment]
hold shift to boost as any ground mech

**Comment by mkhan45** [comment]
ah sorry I didn't realize that alpha mechs already have the ability to fly
