### ISSUE TITLE
Campaign progress lost when restarting app

### ISSUE THREAD

**Issue by Jonny007-MKD** [Anuken/Mindustry#1660]
**Platform**: *Android*
**Build**: *5-fdroid-103*

**Issue**: *I was playing Winterforest for 20 hours and had survived over 200 waves, when Android figured that it should close Mindustry which was paused in the background. So I lasted started the app and was spawned right in the tutorial. All my progress is lost.

**Steps to reproduce**: make some progress, exit the app in the menu and start it again.

**Comment by DeltaNedas** [comment]
1. latest version is 104 get it on itch.io or build yourself fdroid takes forever aaaa
2. have never been able to replicate on android 9, app installed to internal storage

**Comment by DeltaNedas** [comment]
also yea go in dev options and stop it from killing background tasks
OR
exit it when you are done playing
thats like complaining you `killall java -9` and it didnt save your data to settings.bin

**Comment by Anuken** [comment]
Duplicate.

**Comment by Jonny007-MKD** [comment]
Thank you for your response!
I have "exit and save"d the map several times and continued from the campaign menu. But it seems like the app never was killed completely.
If I exit the app from the menu, my progress is lost, too.
I'm not expecting the map to continue at the very same second, but as I can configure an auto save interval in the settings, I expect the resume point to be at most this old.

I am running Android 9 (LineageOS) and installed it on the internal storage, too.

**Comment by Jonny007-MKD** [comment]
It works with 104. Thanks!
