### ISSUE TITLE
Unable to update schematic (oops #1604)

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry#1672]
**Platform**: *Android/iOS/Mac/Windows/Linux* 
Windows

**Build**: *The build number under the title in the main menu. Required.* 
Steam 104.5

**Issue**: *Explain your issue in detail.*
My old issue ( #1604 ) has unintentionally made it impossible to update a schematic for the steam workshop since naming a duplicate schematic creates a new one each time.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Create a duplicate schematic with the same name. (workshop item is linked to the first schematic *only*)

**Comment by Anuken** [comment]
I don't think schematics should be updated by saving something with the same name; that seems like a very roundabout way to do it. In fact, schematics don't really seem like something that should be updated at all.

**Comment by Katsute** [comment]
On the schematics page the selecting a workshop schematic allows you to update it; should it be removed then? The only thing that could change is the name.

**Comment by DeltaNedas** [comment]
1. delete old
2. name new
3. upload
probably works

**Comment by Katsute** [comment]
Upload always creates a new listing, which goes by a steam id; so the name is irrelevant to the actual workshop listing.

**Comment by Anuken** [comment]
> The only thing that could change is the name.

I don't see a problem with that.

**Comment by serdarakkilic** [comment]
@Katsute @Anuken 
What is the point of having schematics on steam workshop if you cannot fix/update them and people auto download this schematics when you edit them?
Game is still actively developing. Some schematics may not work after a possible update.
You are just killing all the statistics on the workshop items which is making people doing more of these stuff. Steam also gives you a better UI and search options than a discord channel.

**Comment by claw4oo** [comment]
I agree with serdarakkilic here, it really pushes against usage of the steam workshop, if you're facing a strong likelihood of just encountering an inferior version of an item, ontop of discouraging complicated blueprints, that had a large flaw that was overlooked, from even being shared on the workshop.

**Comment by QmelZ** [comment]
I agree with @serdarakkilic too, and if i am not mistaken, this does not work with maps either.
