### ISSUE TITLE
[modding] DoubleTurrets don't have heat

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1673]
**Platform**: *Windows*

**Build**: *104.1*

**Issue**: *For some reason, DoubleTurrets don't show heat.*

**Steps to reproduce**: *After changing a modded turret from ItemTurret to DoubleTurret, the heat sprite stopped showing. By testing with changing a different turret from ItemTurret to DoubleTurret, I was able to find that it was indeed changing from ItemTurret to DoubleTurret that broke the heat sprite. I'll count this as a bug unless there's a special feature for 2 heat sprites with the 2 barrels that isn't noted in the Modding Guide*

**Comment by MEEPofFaith** [comment]
![Image](https://cdn.discordapp.com/attachments/532364144196976694/684996134426378246/unknown.png)

**Comment by MEEPofFaith** [comment]
Also, it seems as if xRand doesn't work on DoubleTurrets.
Like, having shotWidth to space to the sides and then add xRand to increase randomness makes sense, but xRand doesn't actually work.

**Comment by Anuken** [comment]
> xRand doesn't actually work

That's because double turrets specifically override turret behavior to shoot at two specific positions, ignoring randomness.
