### ISSUE TITLE
need help finding where ui.picker.show comes from

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Mindustry#1675]
in [lightblock.java](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/power/LightBlock.java) there is ui.picker.show, what file does this come from? (asking so i can figure out how to make a custom dialogue that is similar with scripting)

**Comment by Anuken** [comment]
See 
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/Vars.java#L177 -> 
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/core/UI.java#L71 ->
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/dialogs/ColorPicker.java

**Comment by DeltaNedas** [comment]
1. install idea
2. ctrl b (lifesaver)
