### ISSUE TITLE
Item sources 

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry#1676]
**Platform**: *Android

**Build**: 104.4

**Issue**: if you copy something with a item source, randomly it will chang what the item source outputs and sucks especially with mods

**Steps to reproduce**: just copy any scematic

**Comment by Anuken** [comment]
When does it change the item - during placement or right after selection? Which item does it change it to, and which item is displayed originally? Provide screenshots.

**Comment by DeltaNedas** [comment]
if you add or remove items it will mess with ids so it will break it until you use the same mods

**Comment by Anuken** [comment]
Mod item ID changes are most likely what's happening here, but there isn't enough evidence provided to tell.

**Comment by Anuken** [comment]
Closing due to lack of response. This was probably caused by mod ID changes, anyway.
