### ISSUE TITLE
Dosen't run plugin commands

### ISSUE THREAD

**Issue by MiguelEXE** [Anuken/Mindustry#1679]
**Platform**: *Windows*

**Build**: *104.5*

**Issue**: *Dosen't run a plugin*

**Steps to reproduce**: *I'm following all the tutorial of ExamplePlguin to install https://github.com/Kieaer/Essentials, I installed with succefull but in Admin Console of the server, the commands need to be running, but its not running (it says: unknown command)*

**Comment by Quezler** [comment]
send a screenshot of the `config/mods` folder contents 👀

**Comment by Kieaer** [comment]
and any error logs :eyes:

**Comment by Anuken** [comment]
If you have problems with installation, ask on the Discord or the plugin repository. The issue tracker is for reporting bugs, not help.
