### ISSUE TITLE
doubleTurret has no heat

### ISSUE THREAD

**Issue by BlueWolfGaming** [Anuken/Mindustry#1682]
**Platform**: *Android*

**Build**: *104.2*

**Issue**: *So, while modding and playing the game, I encountered an issue of turrets with doubleTurret as their type cannot have heat sprites.*

**Steps to reproduce**: *Place a Duo or Spectre and watch it as you spawn a wave and the turret starts firing, or make a modded doubleTurret and give it a heat sprite, then repeat the placing and wave spawning.*

**Comment by Quezler** [comment]
#1673

**Comment by Anuken** [comment]
Duplicate.
