### ISSUE TITLE
Bullet casings fall under buildings

### ISSUE THREAD

**Issue by BelTol3011** [Anuken/Mindustry#1685]
Tested in 104.5 sandbox mode.
If you shoot somewhere, the bullet casings wich fall down aren't visible if they fall on a building. I think it would be more logical if they fell on top of the buildings.
![bug2](https://user-images.githubusercontent.com/37810842/76163126-dc015780-6143-11ea-8b1e-db46642dabb6.png)
![bug](https://user-images.githubusercontent.com/37810842/76163127-de63b180-6143-11ea-8264-d241ecd5ff8b.png)
They also fall under stones.

**Comment by Quezler** [comment]
then you'd get the problem of them having to "roll off", since the textures contain depth. 👀

**Comment by Anuken** [comment]
Realistic bullet casing physics would be nice, but that's not something that can easily be implemented.
