### ISSUE TITLE
Pump keeps drop health on oil surface

### ISSUE THREAD

**Issue by DCinAC** [Anuken/Mindustry#1688]
**Platform**: Android

**Build**: 104.2

**Issue**: All kinds of pump constantly drops health on *that specific* oil surface. Pumps built outside of the place where the thermal pump was was not affected.

Destroyed while rebuilding, repair bots shooting at where the pump was located but nothing there
Problem still present after restarting the game

**Steps to reproduce**: thermal pump destroyed (by Lich), was building construction bots at the time. So I was doing nothing with the pump except letting the bots do their jobs.
Then I've found that the oil pump was constantly built and destroyed(NOT deconstructed)
Then I manually deconstructed the plan, saw the repair bots still shooting at where the pump was even nothing there.

**Comment by DCinAC** [comment]
I have rebuilt all kinds of punps on where the thermal pump was and all of them drops health constantly, therefore i just give up and deconstruct all the pump on that oil surface.
And the bot still shooting at the air XD

**Comment by DeltaNedas** [comment]
put out the fire

**Comment by Anuken** [comment]
I don't have enough information to reproduce this problem, and either way, AI and entities are being rewritten, so this is unlikely to be reproducible or continue occurring (if it is indeed a bug).
