### ISSUE TITLE
Setting player.name on server side carries over to other servers for the rest of the session

### ISSUE THREAD

**Issue by Recessive** [Anuken/Mindustry#1689]
**Platform**: *Linux*

**Build**: *104.2*

**Issue**: In setting `mindustry.entities.type.Player.name` on server side or `.color`, when the player disconnects the settings remain changed outside of the server and on other servers

**Steps to reproduce**: Edit `mindustry.entities.type.Player.name` or `mindustry.entities.type.Player.color` to anything. Strangely, trying to set these values back to their original value in `EventType.PlayerLeave.class` will have no effect and the issue will remain.

**Comment by Kieaer** [comment]
Already fixed. use build 104.6

**Comment by itcannotbe** [comment]
https://github.com/Anuken/Mindustry/pull/1607
