### ISSUE TITLE
It is possible to create schematics with the same name

### ISSUE THREAD

**Issue by serdarakkilic** [Anuken/Mindustry#1690]
**Platform**: *Mac*

**Build**: *104.6 steam*

**Issue**: *It is possible to create schematics with the same name*

**Steps to reproduce**: *Just create schematics with the same name*

This issue breaks down updating options on steam workshop. Because it is not possible to update/fix your already shared workshop items. re uploading breaks the point of having this stuff on steam workshop. It removes auto updates.

**Comment by serdarakkilic** [comment]
Dublicated issue closing it

**Comment by mRebornM** [comment]
👍

**Comment by Katsute** [comment]
#1604 #1672
