### ISSUE TITLE
Drill mining speed hard capped at 60 items per second?

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#1697]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Steam 104.6

**Issue**: A modded drill that can drill over 60 items a second is capped at 60 items per second, even though the UI says otherwise.

**Steps to reproduce**: Mod in a drill that mines over 60 items per second (such as sand), using a very low drillTime
Screenshots:
![20200310183056_1](https://user-images.githubusercontent.com/19158169/76365516-de0f1600-62fd-11ea-8ee6-bde888607f66.jpg)
![20200310183353_1](https://user-images.githubusercontent.com/19158169/76365518-dea7ac80-62fd-11ea-824f-c593a5eebe32.jpg)
![20200310183359_1](https://user-images.githubusercontent.com/19158169/76365523-df404300-62fd-11ea-875d-d2bb1c3724f4.jpg)
![20200310183403_1](https://user-images.githubusercontent.com/19158169/76365525-df404300-62fd-11ea-8c15-51ac573ef126.jpg)
![20200310183404_1](https://user-images.githubusercontent.com/19158169/76365527-dfd8d980-62fd-11ea-8990-41d88cd9368d.jpg)
![20200310183404_2](https://user-images.githubusercontent.com/19158169/76365530-dfd8d980-62fd-11ea-951c-feb70781a129.jpg)
![20200310183405_1](https://user-images.githubusercontent.com/19158169/76365531-e0717000-62fd-11ea-8c20-b8f0c0456ec3.jpg)
![20200310183405_2](https://user-images.githubusercontent.com/19158169/76365532-e0717000-62fd-11ea-9897-c4ac7257b2da.jpg)
![20200310183406_1](https://user-images.githubusercontent.com/19158169/76365533-e10a0680-62fd-11ea-8d1f-f3c599d07a56.jpg)

The conveyor with coal illustrates the timing

.

**Comment by Anuken** [comment]
Yes, because the game runs at 60 frames per second. Drills can't (and really shouldn't) output more than one item per frame.
