### ISSUE TITLE
Can’t build Mindustry on Linux on AArch64

### ISSUE THREAD

**Issue by linkmauve** [Anuken/Mindustry#1704]
**Platform**: *Linux* Ubuntu AArch64 on a Nintendo Switch.

**Build**: 8550995c4e9f886e702aad35c0689cf268b20fd1 is the commit number.

**Issue**: I want to build Mindustry to play it on my Nintendo Switch, that is on Linux AArch64.

**Steps to reproduce**: I first did a `./gradlew build`, it built fine but when I tried to run the generated jar it contained only the amd64 version of various JNI libraries, such as libopenal.so, libgdx64.so, or libsdl-arc64.so.  For the first one, I could just replace it with my system’s version. For the second one I wrote a [super ugly patch](https://github.com/Anuken/Mindustry/files/4332922/0001-DON-T-PUSH-Allow-building-on-AArch64.patch.txt) which let [libgdx](https://github.com/Anuken/libgdx) generate a libgdxarm64.so. But for sdl-arc I couldn’t find the sources anywhere, do you know where they are?

**Comment by QmelZ** [comment]
`./gradlew desktop:dist`

**Comment by DeltaNedas** [comment]
Anuken/Arc

**Comment by Anuken** [comment]
The native build for Arc+SDL is [here](https://github.com/Anuken/Arc/blob/master/backends/backend-sdl/src/test/java/NativesBuild.java).

**Comment by linkmauve** [comment]
Thanks for the quick answers!

Sadly, I’ve been unable to figure out how to tell gradlew to build such a libsdl-arcarm64.so from the Arc repository. I tried `./gradlew :backends:backend-sdl:test`, as well as running `java NativesBuild.java`, to no avail.

I also couldn’t find where to execute `./gradlew desktop:dist`, if I do it in the Mindustry repository it says “No local.properties found. Not loading Android module.” and then nothing for quite a while, I aborted the process after a quarter of hour.

**Comment by Anuken** [comment]
> how to tell gradlew to build such a libsdl-arcarm64.so

You can't. Arm64 is not supported; unless you have good knowledge of JNIGen and are willing to put in the time and effort to modify the file I linked, it's not possible. The command to build is `./gradlew sdlnatives`.


> then nothing for quite a while, I aborted the process after a quarter of hour.

I've never had that happen to me across 4+ different installations/operating systems, so there's most likely something wrong with your system.

**Comment by QmelZ** [comment]
> it says “No local.properties found. Not loading Android module.” and then nothing for quite a while

Strange, never happened to me.
