### ISSUE TITLE
Scripting doesn't work on ios

### ISSUE THREAD

**Issue by Eldoofus** [Anuken/Mindustry#1706]
**Platform**: *iOS*

**Build**: *104.4*

**Issue**: *I have a script for a mod where item sources consider the consumes field, but it only works on my windows laptop.*

**Steps to reproduce**: *Import Eldoofus/scidustrymod and try to use Item Generator. If on iOS, no configuration menu will appear. On windows, the block works fine. Not tested on other platforms.*

**Comment by Anuken** [comment]
iOS inherently does not support scripting.

**Comment by Eldoofus** [comment]
Is there any way to fix it

**Comment by Anuken** [comment]
No. iOS will never support scripting.

**Comment by Eldoofus** [comment]
Ouch
