### ISSUE TITLE
block.consumes.remove(ConsumeType.~) doesn't work

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#1707]
**Platform**: *Windows*

**Build**: *104.4*

**Issue**: *block.consumes.remove doesn't work*

**Steps to reproduce**: *I made script that extend PowerTurret, and I tried to remove consumes of liquid(for booster). I typed block.consumes.remove(ConsumeType.liquid); and this error occured
![제목 없음24](https://user-images.githubusercontent.com/61054554/76696219-5d209780-66cc-11ea-993a-f5e7858b45c8.png)

so I tried 
block.consumes.liquid(Liquids.slag,1);
block.consumes.remove(ConsumeType.liquid);
no error occured(both in-game and last-log.txt)  but removing consumes didn't apply 
*

**Comment by Anuken** [comment]
`PowerTurret`s extend `CooledTurret`, which means they **require** liquid coolant. Removing it will lead to an error. If you want a turret that doesn't require coolant, you need to make your own subclass of turret that extends off of the base turret and uses power.

**Comment by younggam** [comment]
thank you for answer

**Comment by younggam** [comment]
tile.entity.bullet.set(tile.drawx()+this.tr.x,tile.drawy()+this.tr.y)
causes blackout(i can't see anything except ui)
