### ISSUE TITLE
Wrong control button with modified xkb files

### ISSUE THREAD

**Issue by catsAND** [Anuken/Mindustry#1708]
**Platform**: *Linux. Fedora 31 with X11 Gnome*

**Build**: *104.5*

**Issue**: *Wrong keyboard layout if modified xkb files.*

*I have notebook with pegatron keyboard that have wrong keyboard layout. Key w replaced with key 3. To work properly need modify X11 keyboard layout files. In chat all keyboard work properly, but button w for movement didnt work. In settings -> control all by default.*

**Comment by DeltaNedas** [comment]
gnome is for tablets, install a de that doesnt break your keyboard

**Comment by Anuken** [comment]
I don't have the means or device to test or fix this; if you have a solution that doesn't break input for other people on international keyboards, submit a PR.

**Comment by catsAND** [comment]
> gnome is for tablets, install a de that doesnt break your keyboard
Problem in keyboard. Not in gnome.

> I don't have the means or device to test or fix this; if you have a solution that doesn't break input for other people on international keyboards, submit a PR.
If u say what file responsible for this i can try to fix.
