### ISSUE TITLE
Local doesnt work

### ISSUE THREAD

**Issue by SwaggerCat** [Anuken/Mindustry#1712]
**Platform**: *Android/iOS/Mac/Windows/Linux*
IOS
**Build**: *The build number under the title in the main menu. Required.*
104.4
**Issue**: *Explain your issue in detail.*
My brother and i keep trying to make a local game on the same wifi, it won’t work on other wifi networks either. It hosts, but isn’t visible on join game. Refreshing wont work either.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Host local server.
Join game.
“No local games found!”
Refreshing doesn’t work.

**Comment by Anuken** [comment]
Some routers/devices block local game discovery, and there's really nothing the game can do about it.
