### ISSUE TITLE
[modding script] tr.x, tr.y  causes black screen

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#1714]
**Platform**: *Windows*

**Build**: *104.4*

**Issue**: *when turret is active, I can't see everything except ui.*

**Steps to reproduce**: *added custom entity porperties, and used tile.entity.getBullet().set(tile.drawx()+this.tr.x, tile.drawy()+this.tr.y)
![제목 없음25](https://user-images.githubusercontent.com/61054554/76720731-f5785400-6780-11ea-9adf-da68a33ea754.png)
this is code and below is gif
![GIF1](https://user-images.githubusercontent.com/61054554/76721107-39b82400-6782-11ea-8a8a-a8be6a3862f7.gif)

comparison (without this.tr.x and this.tr.y)

![GIF2](https://user-images.githubusercontent.com/61054554/76722123-ac76ce80-6785-11ea-8936-b05524ab2b28.gif)

It doesn't cause black out but bullet starts center of turret
*

**Comment by Anuken** [comment]
Not a bug. `this.tr` is null, and cannot be used. `tr` cannot be used in extension either, as it is not bound to an instance of a block. `theBlockVariable.tr` should be used.

`this` does not work in Javascript extensions the same way it does in Java; don't use it unless you know exactly what you are doing.

**Comment by younggam** [comment]
thanks
