### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry#1715]
**Platform**: Windows 10 x64

**Build**: 104.6

**Issue**: I can hear the music even if I completely turn it off.

**Steps to reproduce**: Turn on&off music.
![image](https://user-images.githubusercontent.com/31485341/76740868-38352e80-6777-11ea-8f41-3ff55d2ac61b.png)

**Comment by Anuken** [comment]
Duplicate.
