### ISSUE TITLE
Mindustry not opening on Mac OS

### ISSUE THREAD

**Issue by BRUL** [Anuken/Mindustry#1717]
<img width="532" alt="Screenshot 2020-03-16 at 23 31 23" src="https://user-images.githubusercontent.com/97167/76805208-82052f80-67de-11ea-997c-af7d87ce92f5.png">

**Platform**: 
Mac

**Build**: 
104.5

**Issue**:
When downloading a newer version of Mindustry, it won't open anymore. The most recent version that did work is 101.1

**Steps to reproduce**:
Install any version newer than 101.1 on Mac OS Catalina 10.15.3

**Comment by Anuken** [comment]
That warning is incorrect; Mindustry is not damaged, but your OS doesn't like the lack of an application signature. 

Catalina is not supported as an OS, and will likely never be.

**Comment by QmelZ** [comment]
↑ praise big cat and update your os

**Comment by BRUL** [comment]
Thank you @Anuken for the reply.
I managed to get around it with the method described in this video: https://www.youtube.com/watch?v=bvqkfUwy9d8

using
`$ xattr -cr Mindustry.app`

**Comment by idomizrachi** [comment]
I bought the game from the AppStore and it didn't lunch on Catalina.
Managed to run it from command line by one time run of:
`sudo xattr -cr /Applications/Mindustry.app`
And to lunch the game:
`java -XstartOnFirstThread -jar /Applications/Mindustry.app/Contents/Resources/desktop-release.jar`
Not ideal but good enough

**Comment by Quezler** [comment]
the 2nd command should word regardless of wether or not the first one is used iirc 🤔
