### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by FennxDZN** [Anuken/Mindustry#1721]
**Platform**: Windows 7

**Build**: 5.0 Build 104.1

**Issue**: When entering the game the screen is black and does not allow me to do anything and when I close it, a notepad appears with the details of the error in the game folder and has the headline: "A fatal error has been detected by the Java Runtime Environment"

**Steps to reproduce**: It was the first time I downloaded it on pc so I had no experience before

[hs_err_pid2004.log](https://github.com/Anuken/Mindustry/files/4345362/hs_err_pid2004.log)

**Comment by Anuken** [comment]
Your graphics drivers don't supported the necessary OpenGL functions to run Mindustry.

**Comment by DeltaNedas** [comment]
`apt install libgl1-mesa-glx` on debian to install latest mesa drivers
