### ISSUE TITLE
Uuid dupe

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry#1723]
**Platform**: Android

**Build**: 104.5

**Issue**: I have a duplicate uuid with someone which has gotten me banned from all .io servers

**Steps to reproduce**: how do you reproduce a uuid dupe

**Comment by QmelZ** [comment]
Same, and yes, specifically .io servers

**Comment by Anuken** [comment]
This is known, but won't be fixed anytime soon due to the fact that there are few other reliable methods of producing IDs that can't be spoofed on Android. For now, use a PC or a different device.
