### ISSUE TITLE
Mindustry does not listen on IPv6 addresses

### ISSUE THREAD

**Issue by lluchs** [Anuken/Mindustry#1725]
**Platform**: Linux

**Build**: 104.5

**Issue**:

Mindustry listens on IPv4 addresses only, making it impossible to host a server from an IPv6-only network. Such networks are increasingly common on home ISPs due to the IPv4 shortage. ISPs usually pair the IPv6-only network with a carrier-grade NAT technology such as DS-Lite that does not allow forwarding IPv4 ports.

**Steps to reproduce**:

1. Host a game in Mindustry
2. Check the local listening ports:

```
$ ss -tlepn
State               Recv-Q              Send-Q                           Local Address:Port                             Peer Address:Port
Process
LISTEN              0                   50                                     0.0.0.0:6567                                  0.0.0.0:*
 users:(("Mindustry",pid=355160,fd=76)) uid:1000 ino:71194900 sk:49 <->
```

Note that Mindustry binds to 0.0.0.0, but not [::].

**Comment by Anuken** [comment]
71f20f928af20fffd06e29ab8db0179078b85147
