### ISSUE TITLE
Ctrl+v to paste server address disregards keyboard layout

### ISSUE THREAD

**Issue by Nachtschatten** [Anuken/Mindustry#1726]
**Platform**: *Windows*

**Build**: *104.5*

**Issue**: *Pasting clipboard content doesn't work with the 'v' key on Dvorak or other keyboard layouts that put the 'v' in a different position*

**Steps to reproduce**:

- Use a non-Qwerty layout, like Dvorak. With Dvorak, the 'v' key is in the lower right section of the keyboard, see [this image of Dvorak on Wikipedia](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout#/media/File:KB_United_States_Dvorak.svg). For comparison: '.' (the full stop) is in this location with Qwerty.
- Copy a server address.
- Try to add a server: In the "IP" text field, press Ctrl+v.
- Result: Nothing happens.
- Press Ctrl + the key in the _physical location_ of 'v' with Qwerty (this is 'k' with Dvorak)
- Result: Now the server address is pasted.
- Expected result: Ctrl+v works with the 'v' key on Dvorak, not with Ctrl+k.

**Comment by Anuken** [comment]
Mindustry uses scancodes, so keyboard layout is ignored. This is intentional; the alternative (keycodes) would involve breaking international keyboards layouts and various bugs with different languages.

**Comment by Nachtschatten** [comment]
Thanks for the quick reply!

I don't understand, so I hope this isn't a stupid question:
As it is, typing 'v' in said text field actually yields a 'v' - but when pressing Ctrl+v, I'm not getting its functionality (pasting). How is that not broken right now?

**Comment by Anuken** [comment]
Fields use [text edit data](https://wiki.libsdl.org/SDL_TextEditingEvent), which is not related to the scancodes used for controls.
