### ISSUE TITLE
[mods] cannot extend LightBlock$LightEntity

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1728]
**Platform**: GNU/Linux

**Build**: master from ~2 days ago

**Issue**: Mods cannot extend LightEntity in scripts

**Steps to reproduce**: 1. F8
2. `extend(LightBlock.LightEntity, {});`

![image](https://user-images.githubusercontent.com/39013340/76990055-3fa73400-693f-11ea-8728-302a3192cf17.png)
works fine for TileEntity and GenericCrafterEntity (not shown)

**Comment by Anuken** [comment]
`LightEntity` is not a static class, so `extend()` isn't applicable. `new JavaAdapter(LightBlock.LightEntity, theLightBlockInstance, {})`
