### ISSUE TITLE
More information on issues #1730 and #1304

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry#1731]
**Platform**: *Android and Windows*

**Build**: 104.5

**Issue**: Current track persists when music volume is set to 0 and continues instead of appropriate track

**Steps to reproduce**: Wait for any music to start playing, then set music volume to 0%. The music will continue to play even when the game should be selecting a different track

**Suggested fix**: Call a proper track stop when music is set to 0%, since that only halts the start of a new track

**Comment by Anuken** [comment]
This has already been reported several times and fixed.

**Comment by Austin5003** [comment]
> and fixed.

(X) Doubt

**Comment by Anuken** [comment]
> (X) Doubt

And by that, you mean that you've already compiled the latest commit yourself and reproduced the issue, and not simply assumed that a lack of an update in the client you're running means that the issue hasn't been fixed, right?

**Comment by Austin5003** [comment]
> current.setLooping(false);
I see it now
