### ISSUE TITLE
Flatpak distribution for Linux

### ISSUE THREAD

**Issue by flyingpimonster** [Anuken/Mindustry#1732]
[Flatpak](http://flatpak.org/) is a popular way of distributing sandboxed, distribution-agnostic apps on Linux. It would be great to have a Flatpak package for Mindustry, to make it easier to download and play.

Is this something you're interested in? I'd be willing to contribute the work to make this happen.

**Comment by DeltaNedas** [comment]
1. **appimage** > flatpak >>>>> snap
2. mindustry is a jar so just play it with java, doesnt have many dependencies that need to be installed
appimage is the superior "portable package" format, it just works (`./Mindustry.appimage` to start, no bs and not being forced to rely on a certain package manager)

**Comment by Anuken** [comment]
There are currently many ways to install Mindustry:
1. Download a jar build from Github, and run it with Java. This requires a pre-existing Java installation (which makes it not quite a one-click run), but most people who download it from there probably already have Java anyway.
2. Download the game from itch.io with Java pre-packaged, and run the executable. This doesn't require any dependencies and should run on every distribution without any hassle (just unzip and run the executable). It doesn't automatically update, but can be set up to do so if you have the itch.io app installed.
3. Download Mindustry from [snap](https://snapcraft.io/mindustry). This was not set up by me, but it should provide a package that can be updated easily and works on most distros without any hassle.
4. Get Mindustry on Steam. This would give you automatic updates and a 1-click launch on (*as far as I know*) all distros.

I think adding another method of installation would be redundant. Even an appimage shouldn't be necessary, as all it saves you is a single unzip step if downloading from itch.io.

**Comment by isidrorg** [comment]
@flyingpimonster I'm sure that you're suggesting that in order to have a standard installation with a launcher, etc. Just think about that as a way to play it as a portable game otherwise just install the snap version or support developer through Steam

**Comment by muelli** [comment]
It'd be nice if the [desktop file](https://github.com/flathub/com.github.Anuken.Mindustry/blob/master/com.github.Anuken.Mindustry.desktop) and the [appdata file](https://github.com/flathub/com.github.Anuken.Mindustry/blob/master/com.github.Anuken.Mindustry.metainfo.xml) could be shipped (and maintained).
