### ISSUE TITLE
pause bug

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#1734]
**Platform**: *Windows*

**Build**: *104.4*

**Issue**: *configurable something's button active in pause*

**Steps to reproduce**: *press space and click button many times and press space
![GIF3](https://user-images.githubusercontent.com/61054554/77248981-38569200-6c81-11ea-985d-16ec6cef31b6.gif)

*

**Comment by Anuken** [comment]
This isn't a bug. There's no reason to prevent you from using that button while paused.
