### ISSUE TITLE
I got banned by the system!!!!

### ISSUE THREAD

**Issue by daniel29348679** [Anuken/Mindustry#1737]
On time I got banned by system when I'm fixing electric problem. It verifys that I'm disconecting power mode.
And I have already been banned for three days,please someone teach me how to solve it.(Ban ID BRPm)

**Comment by Quezler** [comment]
contact the owner/admins/discord of that server, this is for issues with the game itself. 😗

**Comment by ado1928** [comment]
Considering he has a ban ID, I'm going to assume its mindustry.io, but please join http://discord.mindustry.io, and close this issue

**Comment by itcannotbe** [comment]
When did people think that the io group of servers are the responsibility of the dev?

**Comment by Anuken** [comment]
This is either a duplicate issue relating to Android IDs or a legitimate ban that has nothing to do with me. Either way, closing.

**Comment by DeltaNedas** [comment]
inb4 negative review on google play because you were banned on a server
