### ISSUE TITLE
Tech Tree message "Item researched" fades away too quickly

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#1739]
**Platform**: Windows

**Build**: 104.6

**Issue**: Tech Tree message "Item researched" fades away too quickly, it's hard to read or even notice it.

**Steps to reproduce**:
1. Launch the game;
2. Click "Play";
3. Click "Campaign";
4. Click "Tech Tree";
5. Research an item, try to notice the message at the top.

**Comment by Anuken** [comment]
I don't agree. The text isn't particularly important, and as many blocks can be researched in quick succession, longer duration would lead to overlapping or excessively stacked text. It's readable enough for me.
