### ISSUE TITLE
Crash on launch. Error EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Carbadox** [Anuken/Mindustry#1751]
**Platform**: Windows

**Build**: No clue, probably 104.5

**Issue**: Trying to launch the game, crashes as soon as the window opens, java log shows the error EXCEPTION_ACCESS_VIOLATION (0xc0000005)

**Steps to reproduce**: Launch the game. Crash.

paste bin for the log incase its useful
https://pastebin.com/4rwhuAHf

**Comment by DeltaNedas** [comment]
your jvm is broken
this isnt mindustrys fault

**Comment by Carbadox** [comment]
alright then

**Comment by Kieaer** [comment]
your jvm path is ``C:\ade\jenkins\workspace``
