### ISSUE TITLE
Non-obvious behaviour of launch pads adjacent to core

### ISSUE THREAD

**Issue by lheckemann** [Anuken/Mindustry#1753]
(Didn't use a template because this isn't really a bug report, nor a real feature request — maybe a request for documentation as a feature..?)

When I place a launch pad or large launch pad adjacent to my core, the capacity displayed for the core increases by the launch pad's capacity, and the launch pad seems to start launching items from the core. Feeding items into the launch pad doesn't seem to send them into the core, however, even though their inventories seem to be consolidated. Could what happens here be made clearer?

**Comment by Anuken** [comment]
Linked launch pads behave exactly like vaults in terms of storage, except that they can't accept excess items and hence cannot be used to increase the input area of the core.
