### ISSUE TITLE
Bug with Tech Tree

### ISSUE THREAD

**Issue by KeviTV** [Anuken/Mindustry#1756]
**Platform**: *Windows*

**Build**: *104.5*

**Issue**: *Textures climb on top of each other if there are not enough blocks in the branch.*

**Steps to reproduce**: *Updated tech tree.*
![image](https://user-images.githubusercontent.com/56699208/77667964-e4ef8700-6f93-11ea-937b-45b34e4157d4.png)
![image](https://user-images.githubusercontent.com/56699208/77668396-6a733700-6f94-11ea-8786-2d9f4c82a3c9.png)

**Comment by Anuken** [comment]
You're running modified code that could never appear in a vanilla client; I don't provide support for that.

**Comment by MEEPofFaith** [comment]
nice
