### ISSUE TITLE
Dont starts

### ISSUE THREAD

**Issue by LukkyLK** [Anuken/Mindustry#1757]
**Platform**: *Windows*

**Build**: *104.1*

**Issue**: *Cant start the game or the game opens in a black screen and closes*

**Steps to reproduce**: *Just click on Mindustry.exe*

probabily a error with java
but i reinstalled and nothing changes

Windows 7 64 bits
Java 8

[hs_err_pid5456.log](https://github.com/Anuken/Mindustry/files/4389147/hs_err_pid5456.log)

**Comment by Anuken** [comment]
See #1588

**Comment by LukkyLK** [comment]
Thanks Nuky ^^

**Comment by LukkyLK** [comment]
can i use DirectX to open the game?

**Comment by LukkyLK** [comment]
i think the error is on the graphic drivers but i dont have new updates

maybe opengl

2.1.0 OpenGL

**Comment by Anuken** [comment]
Your computer can't run Mindustry, then.

**Comment by LukkyLK** [comment]
Was a problem with OpenGL

Cause when i changed the Dll
The game opens :D

Em qui, 26 de mar de 2020 16:16, Anuken <notifications@github.com> escreveu:
