### ISSUE TITLE
Game crash by repeatedly pausing and dragging resource into a conveyor

### ISSUE THREAD

**Issue by kubapolish** [Anuken/Mindustry#1758]
**Platform**: *Windows*

**Build**: *104.1*

**Issue**: *Game crashes when placing too much resources on a conveyor.*

**Steps to reproduce**: *Pick up ~15 of resource. Find an empty conveyor. Pause the game. Quickly unpause, drag your resource into the conveyor and pause again. Repeat 5-6 times then unpause. Game crashes*

[Video how to reproduce](https://files.catbox.moe/1s7wxg.mp4)
[Crash report](https://github.com/Anuken/Mindustry/files/4389598/crash-report-03_26_2020_20_38_36.txt)

**Comment by Quezler** [comment]
i'd like to mention that i've seen this exception happen somewhat regularly on my server as well, like every few days or so it just happens, with no real clue as to why that was reproducable 🤔

**Comment by Anuken** [comment]
Update to the latest version.
