### ISSUE TITLE
Core Launch - Mindustry 6.0

### ISSUE THREAD

**Issue by bot196** [Anuken/Mindustry#1762]
**Platform**: Windows

**Build**: Mindsutry 6.0

**Issue**: How to launch the core in campaign? 

**Steps to reproduce**: Can't launch the core

**Comment by Dexapnow** [comment]
Your stupidity isn't game's issue. (sorry for being toxic ;-;)

**Comment by Quezler** [comment]
^

**Comment by Anuken** [comment]
Do the tutorial.

**Comment by iDenis124** [comment]
amazing issues right here

**Comment by ZkyLB** [comment]
And go back to 5.0.
You're too far from your homeland.

**Comment by Quezler** [comment]
technically this is 5.0 👀
