### ISSUE TITLE
Anti-feature: internet mod import only allows Github

### ISSUE THREAD

**Issue by Wilker-a** [Anuken/Mindustry#1764]
Build 5-fdroid-104

currently, the mod imports using URLs only allows mods from Github to be downloaded, which not only limits the places where you can conveniently download directly via the game, but it also promotes a nonfree service as if it were the only place to host repositories on the internet (and by extension, the game mods).

the solution that i propose, is that instead of only having the repository address in the text box, the game should always ask for the entire repository URL address by default, regardless of the domain where it's hosted (with the box starting off as empty, with the ExampleMod's whole address being the ghost text), allowing the player to know more easily that they can get mods from places other than Github, and the "Import Github mod" should change to something in the lines of simply "Download mod", "URL import" or maybe "Git import" (as Git and Github are different things, and if it's the case that the game uses Git to download, too)

thank you for reading \^\^

**Comment by Anuken** [comment]
(duplicate)

**Comment by Wilker-a** [comment]
(sorry i had issues with my connection)
