### ISSUE TITLE
Menu Music

### ISSUE THREAD

**Issue by Nexity** [Anuken/Mindustry#1765]
**Platform**: Windows

**Build**: 104. Or the current build

**Issue**: The menu music can still be heard when music volume is at 0%

**Steps to reproduce**: Was testing a mod where it changes the menu music. Mod did not work. To recreate, open mindustry and the menu musc would start. Music volume was at 0% when I opened mindustry. Then put at 100% if havent. Turn the volume to 0% and you can still hear the menu music faintly.

**Comment by Anuken** [comment]
Duplicate.
