### ISSUE TITLE
Dragging the music down to 0% very quickly still plays it

### ISSUE THREAD

**Issue by Raoul1808** [Anuken/Mindustry#1773]
**Platform**: Windows

**Build**: 104.6 Steam

**Issue**: When you drag very quickly the music bar down to 0, the music still plays, but the volume depends on how quickly you reduced the music volume to 0%

**Steps to reproduce**: 
1. Go to Settings Menu -> Sound
2. Set music to 0% quickly. You should still hear the music even though it's at 0%.

**Video**: https://youtu.be/32KLpdv46Zo

Additionnal Note: After trying to replicate the bug again, I went on a map to check if the music would still play normally (campaign map selection, in-game random musics, etc...). Turns out the main menu music still plays and even loops in-game. I guess this is due to the game not sending/receiving any instructions to stop the main menu music and play another one as the music volume was set to 0%.

**Comment by QmelZ** [comment]
1. Duplicate.
2. Happens on itch version too.
3. Happens if you do it slowly too.

**Comment by Anuken** [comment]
Duplicate.
