### ISSUE TITLE
My game no unlock

### ISSUE THREAD

**Issue by nikara** [Anuken/Mindustry#1783]
**Platform**: */Windows 10

**Build**: *Build 104
**Issue**: *I bought the game by steam more when I went to open the game did not open. Before buying the game, try it for free, when I tested it, download both 64 bit versions and 32 only 32 functional versions, the other one gave the same problem as the purchased version.

---

*Place an X (X) between the brackets to confirm that you have read the line below.*  
[ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your game is likely failing to load DLLs properly or having issues with OpenGL. You haven't posted any logs, and I can't help you; the best option is to refund the Steam version.

**Comment by DeltaNedas** [comment]
install debian and `apt isntall libgl1-mesa-glx` to instantly update opengl to 4.X (4.5 on my hd graphics)
