### ISSUE TITLE
iOS Mindustry cannot read js in mods

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry#1784]
**Platform**: *iOS*

**Build**: *Release build v104.4*

**Issue**: *iOS Mindustry just cannot read js in mods.The other parts in the mod runs correctly.*

**Steps to reproduce**: *Just import a mod with js*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
[X
![64F4395F-0E02-4F46-B0C4-303001B0B62E](https://user-images.githubusercontent.com/62016462/77868882-44d57e80-726f-11ea-8c3a-34cf8c7342c7.jpeg)
![Uploading B6F78F8C-B908-44E8-9C7B-A6791BBDBBE3.png…]()

] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
iOS doesn't support scripting.

> I have searched the closed and open issues to make sure that this problem has not already been reported.

You clearly haven't, because this has already been reported.
