### ISSUE TITLE
NVidia driver blanks some blocks

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry#1788]
**Platform**: *Linux*

**Build**: *release 104.6*

**Issue**: *I used Nouveau driver with no problem. But the FPS was low, so I changed the driver to NVidia. It fixed the FPS issue, but sometimes it blanks the background and some tiles, and I have to reload the level to fix. Sometimes the walls disappear also, and they become invisible. NVidia NVS 5200M with 340 driver on Ubuntu, installed from the software&updates window.*
![Screenshot from 2020-03-30 22-06-01](https://user-images.githubusercontent.com/53530661/77956847-db875700-72d2-11ea-99d7-5db66a6a9e62.png)

**Steps to reproduce**: *Close laptop lid and open again, some blocks get blank.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
[X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Considering rendering works correctly on every mobile device, OS and VM I've tested, you're most likely seeing a driver bug. I won't be fixing this. Use a different driver.
