### ISSUE TITLE
Steam version crash

### ISSUE THREAD

**Issue by wirke** [Anuken/Mindustry#1798]
**Platform**: *Windows*

**Build**: *steam build 104.7*

**Issue**: *Mindustry crashes when I want to play multiplayer(pvp)*

**Steps to reproduce**: **

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[crash-report-04_01_2020_10_40_47.txt](https://github.com/Anuken/Mindustry/files/4413624/crash-report-04_01_2020_10_40_47.txt)
[crash-report-04_01_2020_10_43_39.txt](https://github.com/Anuken/Mindustry/files/4413625/crash-report-04_01_2020_10_43_39.txt)
[crash-report-04_01_2020_10_44_35.txt](https://github.com/Anuken/Mindustry/files/4413626/crash-report-04_01_2020_10_44_35.txt)
[crash-report-04_01_2020_10_52_16.txt](https://github.com/Anuken/Mindustry/files/4413627/crash-report-04_01_2020_10_52_16.txt)

**Comment by Quezler** [comment]
Anuke is sleeping right now, i would suggest you downgrade back to `104.6` unless you plan on trying a custom game on a certain map... 😗

**Comment by wirke** [comment]
I'm downloading 104.6 from github now

**Comment by ZkyLB** [comment]
*tHiS iS iNtEnSiOnAl*

**Comment by Quezler** [comment]
the crash not ^

**Comment by max2007-69** [comment]
Same(crush on 104.7), but on android.

**Comment by junkboy350** [comment]
+1, crashing on Windows 10 on server join. Throwing logs in the pot in case it helps.


[crash-report-04_01_2020_02_01_42.txt](https://github.com/Anuken/Mindustry/files/4414003/crash-report-04_01_2020_02_01_42.txt)

**Comment by wirke** [comment]
Interesting way to reduce online ;)

**Comment by Anuken** [comment]
Fixed.
