### ISSUE TITLE
no multyplayer for me 

### ISSUE THREAD

**Issue by skiv4a** [Anuken/Mindustry#1799]
Platform: Windows

Build: 104.7

Issue: I lode the launcher for the game itch, I click the launch button and the game lodes, I go to the multiplayer section and I click server but it gives me a message:
 a crash has occurred. it has been saved in : the directions of the bug file. null pointer
I tried reinstalling the game but it doesn't work, singleplayer is fine tho I can play normally

**Comment by Quezler** [comment]
duplicate of #1798 🔋
