### ISSUE TITLE
Messages on server side

### ISSUE THREAD

**Issue by wirke** [Anuken/Mindustry#1800]
**Platform**: *On server side*

**Build**: *On server side(probably 104.7)*

**Issue**: *Two messages(from different players) in the chat are connected, keeping the style of the previous one(Capital letters) and only the nickname of the first player is shown.*

**Steps to reproduce**: *It came out randomly, but twice from two different devices.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by wirke** [comment]
It looks like: [kitlhut0r]WHAT? HELLO ALL, WIRKE HERE

**Comment by wirke** [comment]
Maybe this is not a bug but a feature?

**Comment by wirke** [comment]
I write: yes
It shown:yes because, i'm a ninja

**Comment by Quezler** [comment]
screenshot for scale? 🍌

**Comment by not-purple** [comment]
A. There’s a chat filter B. Enemies now attack. C. You can build on track
And D. Draugs are all drunk
It April fool on .io server

**Comment by not-purple** [comment]
> yes because, i'm a ninja
That chat filter on .io
