### ISSUE TITLE
Sorters

### ISSUE THREAD

**Issue by wirke** [Anuken/Mindustry#1801]
**Platform**: *Server side*

**Build**: *probably 104.7 on server*

**Issue**: *When you build a (inverted)sorter, you build a router.*

**Steps to reproduce**: *Try to build sorter on pvp server...*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
probably not a bug but a feature ⭐️

**Comment by wirke** [comment]
Ahah, I do not think so.

**Comment by not-purple** [comment]
A. There’s a chat filter B. Enemies now attack. C. You can build on track
And D. Draugs are all drunk
It April fool on .io server

**Comment by not-purple** [comment]
@wirke check .io discord announcement
