### ISSUE TITLE
rollback to the previous version of the server!!!!!!!!

### ISSUE THREAD

**Issue by wirke** [Anuken/Mindustry#1802]
**Platform**: *Official server*

**Build**: *104.7*

**Issue**: *Too many bugs!!!! Mine Drones dont mine anything; sorters, junctions not put; Server works very slow and lag...*

**Steps to reproduce**: *Try to play :)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by not-purple** [comment]
A. There’s a chat filter B. Enemies now attack. C. You can build on track
And D. Draugs are all drunk
It April fool on .io server

**Comment by not-purple** [comment]
stop complaining

**Comment by wirke** [comment]
Oh....
