### ISSUE TITLE
Array out of bounds

### ISSUE THREAD

**Issue by rafaelandrepedro** [Anuken/Mindustry#1803]
**Platform**: windows

**Build**: 104.1

**Issue**: array out of bounds

**Steps to reproduce**: 1st time was building, 2nd time was shooting

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[crash-report-04_01_2020_12_52_51.txt](https://github.com/Anuken/Mindustry/files/4414905/crash-report-04_01_2020_12_52_51.txt)
[crash-report-04_01_2020_12_48_44.txt](https://github.com/Anuken/Mindustry/files/4414906/crash-report-04_01_2020_12_48_44.txt)

**Comment by Quezler** [comment]
please update to 104.6, you are 5 versions behind.
