### ISSUE TITLE
Resources flowing into core do not increase count

### ISSUE THREAD

**Issue by Rammschnev** [Anuken/Mindustry#1805]
**Platform**: Linux/Windows Multiplayer (server hosted on Linux)

**Build**: Linux: Steam build 104.10; Windows: 104.6; Server: 104.6

**Issue**: On multiplayer PvP, one resource at a time (no clear pattern, can be any resource, so far has affected lead, silicon, and surge alloy) can clearly be seen flowing into the core but does not increase the count. Only affects one resource at a time, for one player at a time. Tried rerouting the resource to different slot along the core, no effect. Can occur at any stage of the game, usually near reaching 75-85 units of the resource.

Happened before the Steam update but could be fixed by rerouting before. Has happened consistently every multiplayer game since the Steam update.

Most similar issue is this ([https://github.com/Anuken/Mindustry/issues/789](https://github.com/Anuken/Mindustry/issues/789)), but distance does not seem to be a factor.

**Steps to reproduce**: Host multiplayer using the server jar, two players, and play as normal. Issue occurs as soon as 10 minutes in, as late as 2 hours.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.** A similar issue has been, but it has been closed a long time ago for a different version of the game, and it is not exactly the same.

**Comment by indielm** [comment]
you are desynced, use /sync in chat

**Comment by Anuken** [comment]
See message above.

**Comment by cbetti** [comment]
For those curious how to enter chat and sync

1. press Enter
2. type /sync
3. press enter
