### ISSUE TITLE
Armored conduit will not flow with junctions

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#1806]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows/Steam 

**Build**: *The build number under the title in the main menu. Required.*
104.10

**Issue**: *Explain your issue in detail.*

 Armored conduits do not allow fluid to pass through them if they are connected to a liquid junction  that has a bridge conduit going into it. You are required to have either titan or regular conduit coming out of the junction in order for you to go back to armored. Conveyors do not have this issue.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

Have a bridge conduit going into a liquid junction, and out the other side of it put an armored conduit, you will not get liquid flow. Found this by replacing all my conduit lines for cryo with armored as if one broke i dont lose all that is in my tanks.

![Screenshot_16](https://user-images.githubusercontent.com/31638088/78311409-ff82ac80-750d-11ea-8c18-29e2a5ad8da4.png)
![Screenshot_17](https://user-images.githubusercontent.com/31638088/78311412-00b3d980-750e-11ea-918a-8e2061e21a46.png)

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 6.0.
