### ISSUE TITLE
[modding] No Way to Change Conduit Bottom/Liquid sprite

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1807]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required.*
104.9 ~~Classical KDFC~~

**Issue**: *Explain your issue in detail.*
After making -bottom-# sprites for conduits and testing, it didn't change the gray under the conduits or where the liquid visibly appears.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Make a modded conduit that isn't shaped like a normal conduit, and test in game. The bottom/liquid won't be correct.
Mod with this issue: [K103908/Exotic-Mod](https://github.com/K103908/Exotic-Mod)
Item: bluewolframite-conduit

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Conduits don't have specialized bottom regions. If you look in the game's sprites, you'll see that there are no `{name}-bottom` sprites, only `conduit-bottom`s, as it would only lead to a lot of duplicated assets. If you need custom bottom sprites, override the draw() method with a script.
