### ISSUE TITLE
Finished campaign server still appears in server list (also duplicate server listing)

### ISSUE THREAD

**Issue by Katsute** [Anuken/Mindustry#1814]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10

**Build**: *The build number under the title in the main menu. Required.*
Steam 104.10

**Issue**: *Explain your issue in detail.*
A few servers have remained on the local list for several days now and are unjoinable.
I have also noticed that campaign servers that have just finished are still listed on the server list until the host closes the summary screen on their end (The server listing should be hidden as soon as the campaign ends, instead of when the host closes the summary).

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
These two servers have been on the local list for several days and are unjoinable. The console outputs this when attempting to join one of the broken local servers.

![20200403225406_1](https://user-images.githubusercontent.com/58778985/78417256-5bc4f980-75fe-11ea-8b9a-5c7634311372.jpg)
```txt
[I] Total time to load: 3115
[I] Time to generate menu: 29.6362
[I] Recieved steam stats.
[I] Fetched 13 global servers.
[I] found 5 matches mindustry.ui.dialogs.JoinDialog$$Lambda$1117/1193471756@4b8d604b
[I] enter lobby 106024717 Success
[I] Connect to owner 45023778: RealTimeGamer
[I] Connecting to server: steam:45023778
[I] Server: false
Client: true
Active: true
[I] Disconnected! NotRunningApp: 45023778
[I] found 5 matches mindustry.ui.dialogs.JoinDialog$$Lambda$1117/1193471756@7dfd3c81
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That seems like a Steam bug. Lobbies of users who aren't playing the game should not be valid or discoverable.

> I have also noticed that campaign servers that have just finished are still listed on the server list until the host closes the summary screen on their end

Since the world still exists and the player isn't in the menu, the game is still considered active.

**Comment by Anuken** [comment]
Steam seems to have removed the invalid lobbies now.
