### ISSUE TITLE
After the Bridge Conduit is connected and then disconnected, their inside can not output

### ISSUE THREAD

**Issue by JohnTing** [Anuken/Mindustry#1816]
**Platform**: *Android/Windows*

**Build**: *104.10*

**Issue**: 
*At Bridge Conduit (or Phrase Conduit) connect one side, then disconnect.
Their inside will not be able to output liquid. 

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

Build two Bridge Conduit (hereinafter referred to as A Bridge and B Bridge)
Connect the output of A Bridge to the output of B Bridge
disconnect
Use Conduit to output from the side of B Bridge (just connected side).

Like the following gif.
https://i.imgur.com/H23ODjk.gif 

I only have Android and Windows, not sure about the status of other platforms

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 6.0.
