### ISSUE TITLE
Game locked to 60FPS regardless of Max FPS setting

### ISSUE THREAD

**Issue by RubberDuckShobe** [Anuken/Mindustry#1818]
**Platform**: *Android 10 (OnePlus 7T)*

**Build**: *Release build 104.6*

**Issue**: *My phone has a refresh rate of 90Hz, and all other apps make use of that, but regardless of the game's Max FPS setting, it's always capped at 60FPS.*

**Steps to reproduce**: *Open Mindustry, set the FPS cap to anything higher than 60, activate the game's FPS counter and then start a game. The FPS counter will always show 60.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
iirc ftps in the terms of mindustry isn't just graphical, but it dictates the speed at which the game runs on, which is supposed to be 60 update loops per second across all clients, having a higher/lower value than anyone else would cause the game to desync

**Comment by GeneralsDuty** [comment]
![Screenshot_20200405-192829359 (1)](https://user-images.githubusercontent.com/57879662/78471316-b0d64c00-7773-11ea-95b3-ad62889d61c6.jpg)
I have no issue Build 104.6

**Comment by Quezler** [comment]
it appears i was slightly mistaken then 😮

**Comment by Anuken** [comment]
The Android version does not support higher frame rates.
