### ISSUE TITLE
Tutorial does not proceed if copper in core is full

### ISSUE THREAD

**Issue by Nerahikada** [Anuken/Mindustry#1819]
**Platform**: Windows

**Build**: steam build 104.10

**Issue**: When depositing copper to the core, if the core resources are full, the copper cannot be deposited and the tutorial will not proceed.

**Steps to reproduce**: 
1: Start tutorial.
2: Mining copper until the copper in the core is full.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
makes sense, i bet anuke didn't anticipate people afking in the tutorial 🤔

**Comment by Anuken** [comment]
Don't fill the core then. It's quite difficult to do unintentionally.

**Comment by Nerahikada** [comment]
Certainly, this is a bug that does not occur unless the player intentionally performs it.
But in fact, I accidentally encountered this problem.
Hopefully this will be fixed as much as possible.
