### ISSUE TITLE
Saves compatibility.

### ISSUE THREAD

**Issue by pimikiel** [Anuken/Mindustry#1820]
**Platform**: *Android/Windows*

**Build**: *104.10*

**Issue**: *I am playing on both Android and PC, and sent Thorium amout is different on both devices regardless same build number. I can "transfer" Thorium between devices sending it down, and loading save game on another device and sending it back up but they are devided between PC and Android.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by pimikiel** [comment]
I am playing on both Android and PC, and sent Thorium amout is different on both devices regardless same build number. I can "transfer" Thorium between devices sending it down, and loading save game on another device and sending it back up but they are devided between PC and Android

**Comment by Anuken** [comment]
I don't see what the problem is. Android and PC don't sync resources, or any save data at all. Launching resources on a server will make everyone connected get the resources, but it's completely unrelated to their total resource count.

**Comment by pimikiel** [comment]
I am using OneDrive to sync save games between pc and android and its working well up untill I got thorium.

**Comment by Anuken** [comment]
I don't know how OneDrive implements syncing, so there's any number of things that could be going wrong with that approach. Syncing is not something Mindustry handles, so unless you can provide a report that clearly shows Mindustry doesn't import specific saves/data (*through Import Data*) properly, it's outside of my control.

**Comment by pimikiel** [comment]
I only open one app at a time, so It only copies files between. Should I sent a screenshot or a savegame file to be checked up?

**Comment by Anuken** [comment]
No. Without using OneDrive or any other sync service, provide an example of data being exported on one device with thorium, then the file being transferred to another device and imported without the thorium being present.

**Comment by pimikiel** [comment]
So exporting and importing saves via zips syncs gathered thorium between devices.

**Comment by Anuken** [comment]
Then it's a problem with the method of syncing you're using (OneDrive).

**Comment by pimikiel** [comment]
Looks like you're right, but isn't zip content the same as appdata/roaming or android/data/* ? looks like it is.

**Comment by Anuken** [comment]
It is; if it were being synced correctly, you would have the same data on both ends.

**Comment by pimikiel** [comment]
Ok, so I changed syncing folder from only saves to whole Mindustry folder, and It solved an issue completly.
