### ISSUE TITLE
Save compatibility

### ISSUE THREAD

**Issue by pimikiel** [Anuken/Mindustry#1821]
**Platform**: *Android/Windows*

**Build**: *104.10*

**Issue**: *I am playing on both Android and PC, and sent Thorium amout is different on both devices regardless same build number. I can "transfer" Thorium between devices sending it down, and loading save game on another device and sending it back up but they are devided between PC and Android.

I know than saves dont sync or share, but I am using OneDrive or import/export option to copy capaign save game between PC and android. Saves were the same, up untill thorium came up. I gathered and sent thorium on PC and reloaded save on android, and collected thorium stated as 0

It looks like thorium is misspelled in a code between platforms.
*

**Steps to reproduce**: Gather and send thorium on PC, export save and import on android, Look at collected thorium amout and vice versa.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ritzip** [comment]
No

**Comment by Quezler** [comment]
![Screen Shot 2020-04-05 at 19 17 02](https://user-images.githubusercontent.com/3179271/78505191-132e4d00-7772-11ea-89a0-fa2bc1511461.png)

**Comment by pimikiel** [comment]
Yes, I would like to delete this
