### ISSUE TITLE
Lasers cause Surge Wall retaliation attacks at the wrong coordinates

### ISSUE THREAD

**Issue by CaribbeanMax** [Anuken/Mindustry#1823]
**Platform**: *all*

**Build**: *v104.10*

**Issue**: *Explain your issue in detail.*
To save a lot of text, here first 2 pictures:
Example A:
![meltdown](https://user-images.githubusercontent.com/23070598/78511608-4ab2ee80-779e-11ea-96bf-2af3cb96e98e.png)
Example B:
![lancer](https://user-images.githubusercontent.com/23070598/78511609-543c5680-779e-11ea-8170-f47f7a0fcaf4.png)
One can clearly see that the lightning arc counter attack from the surge walls begins at the origin of the laser and not at the wall itself.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Just fire a laser at a surge wall and wait for the retaliation attack to trigger.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 6.0.
