### ISSUE TITLE
mod sound load bug

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#1825]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *Custom sound file doesn't load when mod refreshed or restarted mindustry(so excute mod refresh). To load custom sound again, I have to change every sound-name ONE BY ONE ALSO IN JSON*

**Steps to reproduce**just load mod, inactive mod, and active mod=refresh mod
every mod that has custom sound can reproduce this bug. even Anuken/exampleMod*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> sound file doesn't load

What do you mean, "doesn't load"? Does it display an error in the console? Does it crash? Do the sounds not play?

> I have to change every sound-name ONE BY ONE ALSO IN JSON

Change the name to what? What specific actions are you performing?

> every mod that has custom sound can reproduce this bug. even Anuken/exampleMod

What actually happens? How are you testing this with ExampleMod? Can you provide a **specific** example of a mod having a custom sound, and that sound not playing when it is supposed to be triggered? Loading ExampleMod, enabling it and playing the included duo shoot sound functions correctly on my setup.

**Comment by younggam** [comment]
desktop window steam


1. no error in console, no crash, and yes custom sound doesn't play 

2.ex) fire.ogg->fire1.ogg      ,   in json:      shoutSound:fire -> shotSound:fire1
3. just load mod, inactive mod, and active mod=refresh mod    

if mod is refreshed more than once, coustom sounds don't play. that's it I have nothing more to say.

**Comment by Anuken** [comment]
Fixed in 6.0.
