### ISSUE TITLE
Broken sound settings

### ISSUE THREAD

**Issue by eBled** [Anuken/Mindustry#1829]
**Platform**: *Windows*

**Build**: *steam build 104.10*

**Issue**: *0% volume music continue playing*

**Steps to reproduce**: *This isn't hard i think*

---
 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
duplicate

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

You really haven't.
