### ISSUE TITLE
Text dialogs can't be closed when screen rotates

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1832]
**Platform**: Android 9

**Build**: 104.10

**Issue**: Text box things can't be closed when screen rotates

**Steps to reproduce**:
1. join a .io server
2. rotate screen
3. try to click ok
4. rotate it back
5. try to click ok, it works

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in Arc.
