### ISSUE TITLE
Launch Pad keeps working when connected to an empty battery

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#1834]
**Platform**: Android, Windows

**Build**: 104.6; 104.10

**Issue**: Launch Pad keeps working when connected to an empty battery

**Steps to reproduce**: In a campaign map I placed a launch pad next to core to automatically launch resources when it's necessary. But later, I placed a dioded battery next to it, charged and then disconnected input battery from power node and waited until the pad drains all energy. But even so, it still works, draining all my resources from core!
To make sure this was a real bug, I was testing the same issue in my Android device.
![Screenshot_20200410-090001](https://user-images.githubusercontent.com/62336673/78969547-d8306e80-7b0f-11ea-92eb-2a2d3008d243.png)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Interestingly, launch pads don't seem to require any minimum amount of power at all. You can run them on practically nothing.

This *is* an oversight, but since launch pads will be reworked in 6.0 anyway I'm not going to fix this in the main branch.
