### ISSUE TITLE
Modded Units Breaking

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1840]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows. Also observed on Android.

**Build**: *The build number under the title in the main menu. Required.*
104.9

**Issue**: *Explain your issue in detail.*
Modded units would constantly face right randomly. [Video as shown.](https://youtu.be/lilb9w8aEzA)
I haven't tested it on ground units, but with the way they full rotate, I believe that it'll only happen with air units. I haven't seen this on normal units.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Nothing specific, just adding sprites to a unit that didn't have sprites in K103908/Exotic-Mod. Just noticed it. On Windows, it happened all the time unless they are set to Retreat or Rally. Same case on Android, but it would also happen if it starts lagging.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Post the entire JSON file for the units. I suspect you're setting something to an invalid value.

**Comment by MEEPofFaith** [comment]
name: Shadow Kind
type: FlyingUnit
description: A unit made from the mysterious shadow ore.. it fires a powerful laser.
speed: 6
drag: 0.6
engineColor: 000000
flying: true
health: 6000
weaponOffsetY: 2
engineOffset: 8
engineSize: 1.7
shootCone: 60
attackLength: 155
weapon: {
  name: shadow-laser
  length: 4
  width: 0
  recoil: 3
  alternate: false
  bullet: lancerLaser
  reload: 8
  shootSound: laser
}

**Comment by MEEPofFaith** [comment]
Also occurs to:

type: flyingUnit
name: Hellfire
description:
  '''
  The most powerful ship ever to fly in an atmosphere. Can take down the most advanced bases if not prepared for.

  WARNING: THIS SHIP IS EXTREMELY DANGEROUS. LAUNCHING BEFORE AN ATTACK FROM THE HELLFIRE IS STRONGLY SUGGESTED.
  '''
flying: true
maxVelocity: 1
speed: 0.1
drag: 0.5
range: 240
attackLength: 280
mass: 10000
hitsize: 45
health: 250000000
retreatPercent: 0
weaponOffsetY: 13
engineOffset: 36
engineSize: 7
weapon: {
  name: shipboard-railgun
  width: 0
  length: 9
  reload: 30
  recoil: 0.1
  inaccuracy: 0
  shots: 1
  spacing: 0
  shotDelay: 30
  shootSound: shootBig
  ejectEffect: shellEjectBig
  alternate: false
  bullet: {
    bulletSprite: exotic-mod-railbolt
    damage: 100000
    frontColor: 234dad
    backColor: 0a2666
    speed: 16
    knockback: 1500
    bulletWidth: 16
    bulletHeight: 50
    splashDamageRadius: 100
    splashDamage: 25000
    shootEffect: shootBig
    lifetime: 200
    hitTiles: true
    collidesTiles: true
  }
}

**Comment by MEEPofFaith** [comment]
Evidently github doesn't like tabs

**Comment by Anuken** [comment]
Both of those units have ridiculous stats.

The first has:
`speed: 6`

...which is far too much for any unit; wraiths have just a fraction of that speed at 0.3, and they're still very fast.

The second has:
`mass: 10000` (which is bound to cause problems with collisions and movement)
and
`health: 250000000` (which just isn't supported)

It doesn't really matter whether this is a bug or not, because 6.0 has completely different AI and physics.
