### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#1841]
**Platform**: Windows

**Build**: release 104.10

**Issue**: Connect global server issue

**Steps to reproduce**: Invalid

![](https://cdn.discordapp.com/attachments/698748944238248017/698760776030093352/Untitled.png)

Report by @IronReaper0

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works on my machine. This is most likely a problem with the user's internet connection; I can't fix it.

> Invalid

Couldn't you just say that connecting to `mindustry.me` causes the issue?
