### ISSUE TITLE
Server/Multiplayer: Resources stop accumulating

### ISSUE THREAD

**Issue by alsonkemp** [Anuken/Mindustry#1852]
**Platform**:Linux

**Build**:  104.1

**Issue**: After some unknown period of time (5m?  50m?  2 hours), resources stop accumulating in the core/base.  We only know it happens because we are not able to build structures because resources are low/exhausted so we check the core and some particular resource is no longer accumulating even though the resource is still flowing into the core.

**Steps to reproduce**: Playing a new or loaded multiplayer game.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This has been reported many times already. You haven't searched.

**Comment by DeltaNedas** [comment]
s to the y to the n to the c
/sync
