### ISSUE TITLE
Left Control key not recognised

### ISSUE THREAD

**Issue by Spicy0903** [Anuken/Mindustry#1857]
**Platform**: *Solus Budgie 4.1(Linux)*

**Build**: *104.10 Steam*

**Issue**: *When in Mindustry Left Ctrl is ignored, in keybinds if you try to rebind something to L Ctrl nothing happens. It doesnt register a key being pressed same with ingame. I know the key works as ctrl+alt+del still works (which is restart on this distro)*

**Steps to reproduce**: *Noticed it wouldnt let me diagonally place blocks this happened after the last update as it has worked since then. I am using standard QWERTY*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
I think this is a you problem. Have you tried other distro? Other Desktop Environment? Or just a Window Manager? Have checked whether you have configured L_Ctrl to something else on your distro yet?

**Comment by Anuken** [comment]
Something is wrong with your system; the key works correctly on all the platforms I've tested, and nobody else seems to have reported any issues with Ctrl across thousands of installations. I can't reproduce or fix this.

**Comment by DeltaNedas** [comment]
womm too, debian buster + kde
