### ISSUE TITLE
Should global servers that require a sign-up process to place/interact with the game be removed?

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#1860]
There are a couple of global servers that require a "sign-up process" (through discord and such) in order to start placing/interacting with the game, and i'm just curious as to whether or not they should actually be there? It doesn't seem right that a server that requires vetting/signing up/VIP should be on a global leaderboard, seeing as the point of the leaderboard is for *global* servers that *everyone* can play, without any extra steps.
Furthermore it seems kind of counterintuitive to make them globally available while restricting them to certain players, all it really does is clog up the global server list.

**Comment by Katsute** [comment]
This sounds more like a [suggestion](https://github.com/Anuken/Mindustry-Suggestions) than an issue.

**Comment by Arkanic** [comment]
@Katsute it's an opinion topic


~~since when i was offline did this repo get mini-modders~~

**Comment by Arkanic** [comment]
ight closing because already discussed on discord
