### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kokolyb** [Anuken/Mindustry#1864]
**Platform**: Windows 10

**Build**: 104.10

**Issue**: When I open Mindustry it first loads to 71% and then crashes with a message: error loading pixmap: decoder init failed for stream. 

**Steps to reproduce**: Trying to play Mindustry

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
Have you downloaded any mods by any chance? Maps perhaps?

**Comment by Kokolyb** [comment]
Yes, I did try to make a mod myself, but when this crash occurred i deleted
all Mindustry related things and downloaded it again. Nothing worked.

**Comment by zethnest** [comment]
Have you tried cleaning your cache before? The folder where it stores data for Mindustry? Try searching at %appdata%/Mindustry. Open your Run Program, and type in that. It should be WinKey + R and

> %appdata%/Mindustry

**Comment by Kokolyb** [comment]
Thank you, it worked! Have a nice day!

**Comment by zethnest** [comment]
Nice. You might want to close the issue.

**Comment by DeltaNedas** [comment]
thats not the fix at all
your png isnt 8 bit int rgba, so it cant decode properly
