### ISSUE TITLE
Unable to view home folder when trying to import/export

### ISSUE THREAD

**Issue by Firgen** [Anuken/Mindustry#1872]
**Platform**: *Linux*

**Build**: *104.1 in the Package Manager in Linux Mint 19.3*

**Issue**: *When trying to import or export game data, it doesn't display contents of the home folder (/home/name) and it appears completely empty. When the game is run as root this doesn't happen, making it seem like it needs root privileges to access those folders.
Root is of course a separate user with separate game data so I can't/don't want to use this option.
I already imported the save file manually so it isn't really that much of a problem, but it still is one.*

**Steps to reproduce**: *This seems to happen only in the build from the package manager in Linux Mint 19.3 (I haven't tested other distros or releases of Linux Mint). The build there is 104.1 so I don't know if it is fixed in 104.6. 
It doesn't happen in builds downloaded separately from github or itch.io (both 104.1 and 104.6)*

---
 
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't have anything to do with Mindustry itself; your package manager is preventing the application from viewing the home folder.

**Comment by DeltaNedas** [comment]
im fairly sure its because you use the (terrible and also unofficial) snap which sets xdg_data_home to be in ~/.snap and break stuff
works fine with normal mindustry

**Comment by Firgen** [comment]
Oh I didn't know that, it says that the package is com.github.Anuken.Mindustry so I thought that it will be the same as this one. I'm fairly new to linux so I might not completely understand how that works.
