### ISSUE TITLE
label bug

### ISSUE THREAD

**Issue by jakubDoka** [Anuken/Mindustry#1885]
**Platform**: *Windows*

**Build**: *104.9*

**Issue**: *Label is probabli instanciated on players position and visible for short amount of time then it snaps to the tile where it supose to be.*

**Steps to reproduce**: *make label (Call.onLabel()) to apear on ewery coreblock eweri second with duration of one second.The issue happend on server.*

**Comment by Anuken** [comment]
Fixed in 6.0.
