### ISSUE TITLE
Schematic Menu Crash

### ISSUE THREAD

**Issue by KK6DOC** [Anuken/Mindustry#1886]
**Platform**: *Windows 7*

**Build**: *Latest Steam Version. (104.10)*

**Issue**: *Scrolled to the bottom of the schematic menu and the game crashed.*

**Steps to reproduce**: *Open You schematic Menu and scroll to the bottom. once hitting it the game will instantly crash*

**Link to mod(s) used, if applicable**: *No Mods*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Crash Report is Below
[crash-report-04_17_2020_15_21_41.txt](https://github.com/Anuken/Mindustry/files/4495529/crash-report-04_17_2020_15_21_41.txt)

**Comment by ado1928** [comment]
I'm fairly sure this is caused by a oversized/corrupt schematic. It happened to me multiple times dealing with huge (I'm talking above 500x500) schematics. What schematics have you last imported before this happened, or just out of the sudden?

**Comment by ado1928** [comment]
Also could've been a deflater bomb someone sent you over clipboard

**Comment by Anuken** [comment]
Invalid previews replaced with the error texture in 6.0.
