### ISSUE TITLE
Omega Mech of other players does not have the "armor" effect while firing

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#1888]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Steam

**Build**: *The build number under the title in the main menu. Required.*
104.10

**Issue**: *Explain your issue in detail.*
When in a multiplayer server, your comrades who are the omega mech do not have the fancy "armor" effect and do not widen their bots while firing

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

Join a multiplayer server and have someone else become omega and fire their weapon.

![image](https://user-images.githubusercontent.com/31638088/79629162-293df500-8104-11ea-864d-b5da95315343.png)
![image](https://user-images.githubusercontent.com/31638088/79629213-c26d0b80-8104-11ea-97b5-92ad4c7b4d8a.png)

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mechs don't exist in 6.0, so this is no longer relevant.

**Comment by MEEPofFaith** [comment]
oh no
