### ISSUE TITLE
Scroll reset when keybind is changed

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1890]
**Platform**: GNU/Linux

**Build**: Last tested ~103, may still happen

**Issue**: Scrolling is reset when a keybind is changed. This is annoying as it means constantly scrolling back down to change more keys.

**Steps to reproduce**:
1. Open controls menu
2. Scroll down a bit
3. Change a key

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

(Probably fixed already but I'm reporting it just incase)

**Comment by Anuken** [comment]
Not a bug. The dialog contents are rebuilt.

**Comment by DeltaNedas** [comment]
cant you still save the scroll position then set it once its rebuilt
