### ISSUE TITLE
Opening browser from game menu results in game lock on Solus Linux

### ISSUE THREAD

**Issue by comaldave** [Anuken/Mindustry#1891]
**Platform**: *Solus Linux*

**Build**: *steam build 104.10*

**Issue**: *Gamelock*

**Steps to reproduce**: *From the main menu, select an option that opens the browser, the game is now locked, closing the browser does not return control of the game, work around is CtrlAltBackspace to reset X windows.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by comaldave** [comment]
The problem has been resolved. Using the Software Update may result in Qt having an old so in memory and that is what caused the lock-up, not the game.

Nevermind!

**Comment by DeltaNedas** [comment]
>browser doesnt use gtk
where can i get this
