### ISSUE TITLE
Cant return to campaign map after leaving the game

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#1893]
**Platform**: *Windows 10*

**Build**: *104.6*

**Issue**: *Yesterday I played a single player on Tar Pits.  When I came back today I could not go back to the map via the campaign menu. (it just showed all maps I could play)  I had to load the game but there was no wave counter as you can see in the screenshot. Maybe I played a multiplayer map in the meantime. I'm not 100% sure*

**Steps to reproduce**: *I don't know how to reproduce it**
![Anmerkung 2020-04-20 164618](https://user-images.githubusercontent.com/57239116/79765103-7c8f8d80-8326-11ea-8248-86ae61ba5c8c.jpg)

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
6.0 has a different campaign system, so this is no longer relevant.
