### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by carlymx** [Anuken/Mindustry#1894]
**Platform**: *Linux Mind 19.3*

**Build**. * Branch: Mindustry-6.0*

**Issue**: *Explain your issue in detail.*
I use Linux Mint 19.3 with Open JDK 11.0.6 and compile the 'Master Branch v104.xx' (Desktop) without problems with:

When trying to compile the 'Branch Mindustry-6.0' this message happens:

```
machine@machine:~/Git/Mindustry-6.0$ sudo ./gradlew desktop:dist

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/carly/Git/Mindustry-6.0/settings.gradle' line: 2

* What went wrong:
A problem occurred evaluating settings 'Mindustry-6.0'.
> !!! YOU MUST USE JAVA 8 TO COMPILE AND RUN MINDUSTRY !!! Read the README. Your version: 11.0.6

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 562ms
```
Do you know anything about it?

**Steps to reproduce**: *
1. Clone Branch: Mindustry-6.0*
2. cd Mindustry-6.0
3. sudo ./gradlew desktop:dist
--

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
use java 8? 🙃

**Comment by DeltaNedas** [comment]
`apt install openjdk-8-jdk`; java 8 is the only supported java version

**Comment by DeltaNedas** [comment]
why did you run gradlew as root

**Comment by Anuken** [comment]
It does say:
> !!! YOU MUST USE JAVA 8 TO COMPILE AND RUN MINDUSTRY !!! Read the README. Your version: 11.0.6

I don't see how the problem can get any clearer than that.

**Comment by carlymx** [comment]
Ok Tnk, 

I already got it, in linux Mint tube to install JDK v8 packages (openjdk-8-jdk) from Synaptic and it worked fine.
The funny thing is that it starts the game correctly, but when you enter a campaign map or a skirmish and once inside, launching the server suddenly closes the game.

I have to open the game with OpenJDK11 so that does not happen.

I do not find it problematic and I do not know why it may be, but I would like to know if I am the only one that happens to you.

Thanks again.
