### ISSUE TITLE
Android, BE crash 8009-8013

### ISSUE THREAD

**Issue by GeneralsDuty** [Anuken/Mindustry#1904]
**Platform**: *Android*

**Build**: *8009,8011,8012,8013*

**Issue**: *Crash, sorry i can't figure out how to post the .txt in here, crash_1587671105526.txt:
> NullPointer: 'Attempt to read from field 'short mindustry.world.Tile.x' on a null object reference'
BlockIndexer.process: 327
BlockIndexer.lambda$new$0$BlockIndexer: 60
-$$Lambda$BlockIndexer$qjhNVW4vTFu0DWedclE0_DlIp2g.get: 4
Events.lambda$fire$2: 26
-$$Lambda$Events$kEWEoJJ7iuVpyOJB9UfewcihGzY.get: 4
Array.each: 181
Events.fire: 26
Events.fire: 21
World.lambda$notifyChanged$3: 263
-$$Lambda$World$KWGF5jIwmpLS7ay378zAPh8Ln4Q.run: 2
AndroidGraphics.lambda$onDrawFrame$0$AndroidGraphics: 426
-$$Lambda$AndroidGraphics$E5Jhq3pDs174QxCFAWFeVbXthOc.run: 2
AndroidGraphics.runProtected: 479
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1575
GLSurfaceView$GLThread.run: 1270*

**Steps to reproduce**: *download .apk, install, watch progress bar finish, and crash*

**Link to mod(s) used, if applicable**: *NA*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't report bugs from bleeding edge builds.
