### ISSUE TITLE
 a question about chatting

### ISSUE THREAD

**Issue by 2680409985** [Anuken/Mindustry#1905]
System:Windows
version:104.10(may be it's Obsolete)
when I was palying with my friend and chat to him,the chat box always send some previous operations.
For example.I want say "HELLO" to my friend.The operation sequence is press ENTER→in put what I want say.But before I perss ENTER,some inputs are recorded.So it may send "wasdHELLO"That "wasd"is my operation on mecha.

**Comment by Anuken** [comment]
It is extremely unlikely that you have discovered a bug, as this would be a very easy problem to notice - yet, nobody has reported anything like it.

Send a video of the problem occurring.
