### ISSUE TITLE
Big mod causes Mindustry (Even after cleaning and redownloading) to be stuck on loading screen

### ISSUE THREAD

**Issue by Lemonislol** [Anuken/Mindustry#1907]
**Platform**: *Windows*

**Build**: *5.0 Build 104.6*

**Issue**: *Mod caused mindustry to stop opening. Problem persists even after deleting all files and redownloading mindustry zip file*

**Steps to reproduce**: *[2 mods were imported first with no problems: (rl_mindustry) & (Better-Blocks-mod)] After download a large mod (Name: The-Biggest-Mod), I started importing (The ZIP file) the mod. The application started to stop responding (White screen) so I decided to close mindustry instead of waiting for it to respond. Reopening the game, the **loading bar** didn't move, so I opened my mod folder and deleted the zip files (While game was frozen). It didn't do anything so I closed mindustry. Now even after clearing all files and downloading mindustry, the progress bar doesn't move when prior to this incident, it opens pretty quickly, like a couple of seconds.*

**Link to mod(s) used, if applicable**: *[Main mod that caused issue] https://github.com/Vladislav117/The-Biggest-Mod] [Other two mods - https://github.com/w1-BeyeK/rl_mindustry & https://github.com/MemFaceGo/Better-Blocks-Mod]*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Update your game, the latest version is 104.10.

**Comment by Lemonislol** [comment]
It still doesn't load. I can't verify the version from the game (Since it's still stuck on loading screen) but I redownloaded mindustry from itch.io, and the problem still occurs

**Comment by Anuken** [comment]
The mod states:

> You must wait before the game starts. (It took about **20 minutes** on normal PC)

...so "freezing" is expected.

If you want to make sure no cache is left over, delete all your game files and try again.

**Comment by Lemonislol** [comment]
**[Problem Solved]**

After restarting my computer and waiting a bit, it did open. I disabled the mod which solved the problem.

**Comment by DeltaNedas** [comment]
you didnt delete the files
%AppData%/Mindustry/mods/ is where the zip is
