### ISSUE TITLE
Nuclear reactor map glitched

### ISSUE THREAD

**Issue by jjlearbo** [Anuken/Mindustry#1914]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

So I want to start out by saying my apologies if this isn't done right is my first time ever posting and using this website. So essentially the bug I came across was during my campaign play through and I eventually unlocked the nuclear reactor map. This is the map that has large quantities of thorium and has thorium reactors pre-built in the map. The issue I came across was while playing I eventually reached wave 99. Now previous to this I had been collecting resources exponentially to the point where my base surrounded by vaults was completely filled up with all the basic resources except for two and I was having to use launch pads to filter off the rest and I had been doing this for at least Thirty waves up to this point. So I figure I had collected at least 20,000 of the basic resources copper, lead, meta glass, graphite ,silicone, and titanium. All the enemies of wave 98 were completely dead and I had 30 seconds until they've 99 hit. I just finished building my alloy smelting plant when all the sudden the game ended. Now I have had the game end where I had my core blown up so I do know what the game end screen looks like for if you get killed and I also know what the game over screen looks like when you launched successfully. I did not get either of these screens at the end. It simply said that my game was over with no extra details and according to it it said I collected 0 resources. So I was forced launched out of the map with zero resources that I collected. Even the resources that I used launch pads to collect we're not there. I had launched over 5000 silicone and when I went back to my main menu I had a under 500. So I don't know what kind of bug or glitch this was or if it was just the game happened to crash but I'm kind of pissed off as you can understand. Maybe this will help you figure something out. Also I don't know if it's a bug but a few of the bosses on that level from previous playthroughs won't go for my core and attack it they seem to avoid attacking my core and just fly around the map aimlessly. I don't know if this is on purpose or not but it makes no sense that the boss wouldn't try to kill my core and just randomly fly around. I watched him fly around in an area with none of my buildings in it for almost 3 minutes doing nothing but going in circles. That map seems really buggy.

**Comment by DeltaNedas** [comment]
fill the template, womm

**Comment by Anuken** [comment]
1. Any bugs related to the campaign are no longer relevant in 6.0.
2. **Use the template.**
