### ISSUE TITLE
Storage permission denied has no effect

### ISSUE THREAD

**Issue by AbuuMonkey** [Anuken/Mindustry#1918]
**Platform**:  Android

**Build**: 5-official-104.6

**Issue**: I tried to deny storage permission on Android, but this seems to don't have any effect on the app: if i try to  import a save the app show me all files located in my phone.

**Steps to reproduce**: Install app. Setting -> mindustry -> permission -> storage -> deny. Open app, Load -> import save  (i think Mod -> import mod has the same issue but i didn't try It).

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
now try to export one

**Comment by AbuuMonkey** [comment]
I tried, it save on the download folder without asking anything

**Comment by Anuken** [comment]
If Android lets Mindustry view files with the storage permission denied, that is not a problem with Mindustry, it's a problem with Android (if a problem at all).
