### ISSUE TITLE
Mute doesn't fully work

### ISSUE THREAD

**Issue by 3thanguy7** [Anuken/Mindustry#1926]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *Muting music doesn't fully mute music. *

**Steps to reproduce**: *I was changing settings, dragged the music slider all the way down, but realized it wasn't fully muted. *

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I have searched the closed and open issues

![image](https://user-images.githubusercontent.com/10100000/80331109-2a160b80-8815-11ea-8aa5-15b9db1846a4.png)

No.
