### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by faithful235** [Anuken/Mindustry#193]
Ai will start to using conveyors as a possibly path on water and get stuck once they destroy the conveyor 

Really sucks when you get to wave 60+ and out of no where you lose all of your defences because the ai thought there was a path right to your base.

**Comment by Anuken** [comment]
This is not a bug. Conveyors are perfectly valid blocks to walk on. If you don't want your base destroyed, don't create direct walkable conveyor paths to it.

**Comment by faithful235** [comment]
Then why aloe the ai to destroy the path they or tacking and get stuck?

**Comment by TheMarksman-ES** [comment]
We've been using the conveyor strat since 3.4, so it works in our favor.
And anyway, you aren't supposed to report 3.5 bugs if you've read the pins in discord.
