### ISSUE TITLE
unable to load older maps due to image mismach

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry#1934]
**Platform**: Windows

**Build**:104.10

**Issue**:unable to load older maps that are in msav format

**Steps to reproduce**: loaded map from discord [attack] aerial command cruiser

**Link to mod(s) used, if applicable**: mods active
![image](https://user-images.githubusercontent.com/47339836/80436846-f094dd00-88b4-11ea-901f-69d656d13358.png
![image](https://user-images.githubusercontent.com/47339836/80436885-086c6100-88b5-11ea-9f73-d73bf3ea64a0.png)
![image](https://user-images.githubusercontent.com/47339836/80436899-11f5c900-88b5-11ea-893d-dce90ff58d48.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Changing any mods or mod versions can and will break older saves. With this many mods, it's impossible to tell what changes have taken place; this is very unlikely to be a bug with the game.
