### ISSUE TITLE
modded conveyors display wrong speed

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry#1938]
**Platform**: *Linux*

**Build**: *104.6*

**Issue**: When using any mods with conveyors, the move speed alvays resets to 0, even though they work normal in game
![Screenshot from 2020-04-18 21-55-18](https://user-images.githubusercontent.com/53530661/80518749-315d2680-8987-11ea-963c-1fa8dc1a257d.png)

**Steps to reproduce**: play latest stable version?

**Link to mod(s) used, if applicable**: [example mod](https://github.com/Anuken/ExampleMod)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Modded conveyor speed needs to be defined in the JSON file manually.

**Comment by bluet-it** [comment]
How to define it?

**Comment by bluet-it** [comment]
the HJSON file (unchanged) is:
`type: Conveyor
name: Electrum conveyor
description: Example conveyor.
requirements: [
  titanium/3
  copper/3
  lead/3
  electrum/3
]
category: distribution
speed: 0.12
research: titanium-conveyor`

**Comment by Anuken** [comment]
`displayedSpeed` needs to be set.
