### ISSUE TITLE
too big multiplier for overdriver causes its effect area behave erratically

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry#1939]
**Platform**: *Linux*

**Build**: *104.6*

**Issue**: when using an overdriver with too high multiplier, everything near it instead of overdriving, behave erratically, the drill tops disappear, conveyor animations stop... Standing on an overdriven conveyor teleports to the end, or worse, if something blocks its way, crashes. I know that the overdriver's multiplier should not exceed a value, and this is not a common bug, at least in normal gameplay, so this can even be closed immediately. Just thought to tell.
![Screenshot from 2020-04-28 19-44-15](https://user-images.githubusercontent.com/53530661/80519685-a9781c00-8988-11ea-863e-8b20f5eedb38.png)

**Steps to reproduce**: use an overdriver with multiplier over the integer maximum value

**Link to mod(s) used, if applicable**: no link, this is the example mod with a heavy overdrive projector added

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't make it too high, then. Floating point precision is limited.
