### ISSUE TITLE
General Performance Issues

### ISSUE THREAD

**Issue by BlueWolfGaming** [Anuken/Mindustry#1942]
**Platform**: *Android*

**Build**: *104.10*

**Issue**: *Overall performance issues, lagspikes, suddenly eating device CPU and RAM*
**Steps To Reproduce:** *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is incredibly vague and not something that can simply be fixed. Your problem could be anything from a slow device to an overpopulated server to bad Android graphics drivers to a specific block that causes lag.
