### ISSUE TITLE
Plastanium conveyor unload broken

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1947]
**Platform**: *mac*

**Build**: *master*

**Issue**: *A crater/roomba unloading dock gets locked to one item.*

**Steps to reproduce**: *send several items down the line.*

**Technical**:

the [`lastItem`](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/StackConveyor.java#L179) does not get reset after usage.

several proposed solutions: (wasn't sure which which one you liked, so issue instead of pull)
- turn it into a local variable instead of saving it on the entity (only gets used twice)
- revert back to calling `items.first()` directly (possibly a no due to performace?)
- clear the `lastItem` on every place where items can get removed or the roomba poofs out or transfers (the most logical but also the most messy, so i came here to debate it)

(and yes, its perfectly fine for plastanium conveyors to merge lanes with different items, its only the loading docks that have the restriction, but i'm fairly sure this was a bug/oversight instead of an intended nerf/lock*)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by walksanatora** [comment]
[13_33_29_PM.zip](https://github.com/Anuken/Mindustry/files/4561005/13_33_29_PM.zip)
zipped video of glitch in effect
