### ISSUE TITLE
Mech Override Issues

### ISSUE THREAD

**Issue by BlueWolfGaming** [Anuken/Mindustry#1949]
**Platform**: *All*

**Build**: *104.10*

**Issue**: *Player mechs aren't being overriden by sprite overrides, have tried sprites-override/mechs/, /units/, /unitsmechs/ /units/mechs/, cannot get it to work*

**Steps To Reproduce**: *Make a mod and try to sprite override a player mech.*

**Link to mod(s) used, if applicable**: *Unavailable currently, repository is private. Will move into a public repository when completed.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Player mech sprites have two separate sprites: icons and in-game counterparts. Make sure you're looking at the right ones.

6.0 doesn't have mechs, so even if this is an issue, it will never be fixed.

**Comment by BlueWolfGaming** [comment]
then explain why the vanguard exists?

**Comment by Anuken** [comment]
What does the vanguard unit have to do with this?

**Comment by MEEPofFaith** [comment]
_*You are no longer the Mech. You are the unit now.*_
