### ISSUE TITLE
It scares me

### ISSUE THREAD

**Issue by BlueWolfGaming** [Anuken/Mindustry#1952]
**Platform**: *Android*

**Build**: *104.10*

**Issue**: *I went to edit the "plated-conduit" sprites in Novix and the file seems to be corrupted, another android user has had the same issue after testing. Picture provided below.*

**Steps to reproduce**: *Download any of the "plated-conduit" top sprites and run on Novix.*

**Link to mod(s) used, if applicable**: *None, strictly vanilla.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_2020-04-30-22-44-10](https://user-images.githubusercontent.com/61173114/80783477-2d700680-8b37-11ea-80d0-7c4469edd144.png)

**Comment by MEEPofFaith** [comment]
#1953 

This might be the fix.

**Comment by DeltaNedas** [comment]
PNG image data, 32 x 32, 4-bit colormap, non-interlaced

**Comment by Anuken** [comment]
This isn't a bug; the image renders fine in-game, and Novix is a completely different application.
