### ISSUE TITLE
door with controller can close with enemies on it in byte-logic

### ISSUE THREAD

**Issue by bluet-it** [Anuken/Mindustry#1966]
**Platform**: *Linux*

**Build**: *custom build (byte-logic branch latest)*

**Issue**: *When closing a door using a controller, enemies on it will immediately "explode", while the door does not get damaged. Even an eradicator (not tested yet) can be beaten with this.
![output](https://user-images.githubusercontent.com/53530661/80864190-703df580-8c81-11ea-9274-4c562c886bb0.gif)
While making this screencast, I did not even shoot, turrets were turned off, just switched that block in the top.*

**Steps to reproduce**: *Built this:
![Screenshot from 2020-05-02 14-35-18](https://user-images.githubusercontent.com/53530661/80864316-2b668e80-8c82-11ea-828d-715542c83634.png)
and switched the button when enemy was standing on it.*

**Link to mod(s) used, if applicable**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
trash compactor

**Comment by bluet-it** [comment]
And it could be automated if my suggestion (in anuken/mindustry-suggestions) of radars will be created

**Comment by Quezler** [comment]
(this branch is beyond dead though)

**Comment by bluet-it** [comment]
Yes, I know. But thought to tell about this.

**Comment by bluet-it** [comment]
Also, will pull requests accepted for old branches?

**Comment by Quezler** [comment]
well you can try, anuke has patched byte logic before, any idea how many people still use it?

**Comment by Anuken** [comment]
Byte logic is dead, and I won't be updating it or accepting pull requests for it.
