### ISSUE TITLE
Font overlaps (smail bug)

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#1968]
**Platform**: Windows

**Build**: 104.10

**Issue**: Font overlaps

**Steps to reproduce**: Look at screenshot
![font](https://user-images.githubusercontent.com/44261958/80894646-bf366a00-8d17-11ea-9ae3-7d3c3d59d9f0.png)

**Link to mod(s) used, if applicable**: vanilla

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix. Making the line height higher will take up more space and look bad.
