### ISSUE TITLE
The mods issue

### ISSUE THREAD

**Issue by mlggaimer** [Anuken/Mindustry#1969]
So the mods like everyone knows hates old phones / Tablets. I akivate 1 mod crash. I go on my mothers pc and ut perfectly fine.

BTW I have a Samsung Galaxy S3.

**Comment by mlggaimer** [comment]
Do someone have the same issue??

**Comment by zethnest** [comment]
What mod? Does it happen with any other mod? State what mod you used.

**Comment by mlggaimer** [comment]
Its every single one I use

**Comment by Gdeft** [comment]
Your phone, which is 7 years old, is probably not compatible with the mods that you used. Also, you should mention which mod you were using because that could help.

**Comment by mlggaimer** [comment]
We'll with hard work I can get in hub then a few seconds later it crashes again or just can go on a map play for fife minutes crases again.

I have many mods on my phone butt only use 1 or 2. I have like over 15 mods.

**Comment by Gdeft** [comment]
Again, would you please mention which mod crashes it?

**Comment by Gdeft** [comment]
The problem with old phones is that it sometimes can't load some features in mods such as scripts because reasons. Which is the reason why your mother's PC can open it because computers are able (and supposed to) load scripts in _that_ mod.

**Comment by mlggaimer** [comment]
![Screenshot_2020-05-03-09-55-18](https://user-images.githubusercontent.com/61418118/80909021-10008f80-8d25-11ea-994c-0b55d6934a34.png)
![Screenshot_2020-05-03-09-55-42](https://user-images.githubusercontent.com/61418118/80909029-227ac900-8d25-11ea-935a-f06ca4ee7467.png)
![Screenshot_2020-05-03-09-55-33](https://user-images.githubusercontent.com/61418118/80909037-34f50280-8d25-11ea-9792-76d9cfbe4f7c.png)
![Screenshot_2020-05-03-09-55-18](https://user-images.githubusercontent.com/61418118/80909041-3f170100-8d25-11ea-89f4-b01e41212a94.png)
There I made sceen shots

**Comment by Gdeft** [comment]
> The problem with old phones is that it sometimes can't load some features in mods such as scripts because reasons. Which is the reason why your mother's PC can open it because computers are able (and supposed to) load scripts in _that_ mod.

^ Apparently that could be the issue.
#### Note
 Some of the .zip file in the screenshot are **plugins and server jar**, they cannot be used on **Mods**

**Comment by mlggaimer** [comment]
I know that there are jar and plugins are!

The pc is like 5 years old and the hardware is slowly dying the pc couldn't stand that much at 1 second

**Comment by DeltaNedas** [comment]
post the crash log and **use the template** jfc

**Comment by Anuken** [comment]
Use the template.

**Comment by Gdeft** [comment]
I forgot to mention that too apparently.
