### ISSUE TITLE
Bug with nickname on server

### ISSUE THREAD

**Issue by Alduin4ik** [Anuken/Mindustry#1975]
Platform: Windows/IOS/Android

Build: 104.10 

Issue: Мой никнейм наложился под ресурс, когда я использовал реконструктор

Steps to reproduce: 1. Зайти на сервер 2. Построить реконструктор впритык с конвеерами, где есть ресурсы (делать всё как на скриншоте). 3. Использовать его. Ваш никнейм наложится под ресурс

Link to mod(s) used, if applicable: Vanilla
![изображение](https://user-images.githubusercontent.com/55048088/80955252-41e62480-8dff-11ea-9bcd-a098fe90e13a.png)

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
i'm guessing anuke will close this with a message somewhere along the lines of:
- there are no more mechpads in 6.0
- 6.0 renders units different so this cannot occur anymore
- its rendered from the block and those layers got an overhail

**Comment by Anuken** [comment]
yep
