### ISSUE TITLE
Rotating schematics to fast causes problems

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1976]
**Platform**: `mac`

**Build**: 474ddcf9 (5.0) & 07a4b64b (6.0)

**Issue**: `rotating a schematic (with (my) scroll wheel) to fast causes rotation to mess up`

**Steps to reproduce**: `make a schematic of blocks with a rotation, then rotate at high speed`

![May-04-2020 12-44-11](https://user-images.githubusercontent.com/3179271/80958516-72c95800-8e05-11ea-992c-270e1fb16427.gif)

> gif taken on 6.0, but also tested it on 5.0 with their conveyors, appears to do the same ^

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen to me, no matter how hard I scroll or spam the flip buttons.

![recording1588596444](https://user-images.githubusercontent.com/10100000/80967151-e78b9a80-8de3-11ea-9af7-3e536c7bb93c.gif)

**Comment by Quezler** [comment]
hmm, strange, have you scrolled repeatedly in opposite directions as well?

**Comment by Anuken** [comment]
Yes. Going back and forth very quickly doesn't change things.

This was reported months ago, back when schematics were first introduced, but I couldn't reproduce it then either.

**Comment by Quezler** [comment]
then i suppose i better close it until more is known about it

**Comment by Anuken** [comment]
It could be something to do with how scrolling is implemented on Mac, or sensitivity.

**Comment by Quezler** [comment]
(my wild guess for now will be that some mouses can scroll so fast that one physical click of the scroll wheel registers several scroll requests exactly at once or something, i have a logitech mouse)

**Comment by Anuken** [comment]
The specific problem could be related to the scroll input event outputting `2 / -2` instead of `1 / -1` sometimes. It could be fixed now.

**Comment by Quezler** [comment]
confirmed, 23cb249c1947be6c3dfd603084ff1208540da5a8 fixed it:

![Screen Shot 2020-05-04 at 15 05 12](https://user-images.githubusercontent.com/3179271/80968685-afeb1580-8e18-11ea-994b-1bf07c89054b.png)
