### ISSUE TITLE
WorldLoadEvent bug in scripting

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#1983]
**Platform**: *Windows*

**Build**: *104.6*

**Issue**: *When I use Events.on(EventType.WorldLoadEvent,cons(event=>{})), It loads current mod and ghost mod.*

**Steps to reproduce**: *
exclude target mod.==all mod reloaded.

include target mod.==all mod reloaded.

![제목 없음81](https://user-images.githubusercontent.com/61054554/80978060-8655dc80-8e60-11ea-9112-b73dc26364ae.png)
results

![제목 없음80](https://user-images.githubusercontent.com/61054554/80978043-805ffb80-8e60-11ea-8ade-61725b7d7a96.png)
code in main.js

*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Do not use `Event.*` methods in mods. Their listeners are not cleared when mods are reloaded.
