### ISSUE TITLE
Units getting stuck in corners.

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#1987]
Platform: Android/iOS/Mac/Windows/Linux

Build: 104.10

Issue: While path finding, the ground units want to go somewhere and get blocked by 2 wall blocks which are placed like / or like \ like a X, the ai of the ground units seem to try and go through the middle of the X and walk there when they are sposed to stop path finiding or path find around the X. This is a problem while making too much bots, they all push each other to a X shaled wall and get stuck there until someone breaks the wall.

Step to reproduce: I first came across the bug while in multiplayer where there was a 100 bot army and they all went for a X shaped wall and stuck there while there was a door block literally 3 blocks left which is open.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce; placing an X-shaped barrier makes the AI go around it. Without detailed screenshots and a save file, I can't fix this.
