### ISSUE TITLE
Unit teleporter

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#1988]
It would be great if there was a unit teleportation device. It would be great for gşgantşc maps because it takes a long time to go from one end to another. I would really like to see it in V6.
It need power and linking to another teleporter to tp. You click on the telepad to transfer in to the other telepad.

Here is an example mod: https://github.com/sodii/mindustry-teleporter

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry-Suggestions <-- we have a place for that 😗
