### ISSUE TITLE
Camera movement still linked to keybinds while naming schematics, if game is paused.

### ISSUE THREAD

**Issue by FiniteInfinity0** [Anuken/Mindustry#1991]
**Platform**: Windows

**Build**: release build 104.10

**Issue**: Typing any key bound to X or Y movement while initially naming a schematic will move the camera if the game is paused.

**Steps to reproduce**: Press Space (or whatever key is bound to pause) and create a schematic. (Note that the order of these doesn't matter, just that the "Save Schematic..." button must be pressed while the game is paused) Press any key linked to camera movement (WASD). The camera should move.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
