### ISSUE TITLE
Cursor doesn't respect UI scale

### ISSUE THREAD

**Issue by kdrag0n** [Anuken/Mindustry#1994]
**Platform**: Linux

**Build**: release build 104.6

**Issue**: When the UI scale is changed, the game's custom mouse cursor doesn't resize accordingly. This makes the cursor hard to see on HiDPI screens because it's so small while the rest of the UI is correctly sized.

Screenshot (the cursor is under the "Quit" button):
![image](https://user-images.githubusercontent.com/7930239/81139731-a8606500-8f1b-11ea-9f06-3e4bec4d0609.png)

**Steps to reproduce**: Change the UI scale in Settings and restart the game.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
did you try to set mouse size in de to 64x64 or something
in kde its in pointer settings iirc

**Comment by kdrag0n** [comment]
My cursor size is fine everywhere else, it's only too small in Mindustry. It's set to 24x24 dp (48x48 physical pixels for 200% scale). You should be able to reproduce it easily even on a low-DPI display by bumping the UI scale significantly (200-300%) and looking at how the cursor doesn't change size even though the rest of the UI is too big.

**Comment by Anuken** [comment]
Fixed.
