### ISSUE TITLE
Ores Generating in Enemy Drop Point

### ISSUE THREAD

**Issue by vizthex123** [Anuken/Mindustry#1996]
**Platform**: Windows (Steam)

**Build**: Steam build 104.10

**Issue**: Ores generate in the enemy drop point, rendering them unobtainable

**Steps to reproduce**: Start a map and explore

**Link to mod(s) used, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You don't need to collect them. Removing them doesn't change the outcome.
