### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1998]
**Platform**: Android, GNU/Linux

**Build**: 104.10

**Issue**: Game works as intended

**Steps to reproduce**: java -jar Mindustry.jar

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
delet this

**Comment by DeltaNedas** [comment]
i did
