### ISSUE TITLE
Can't change weapons?

### ISSUE THREAD

**Issue by LegusX** [Anuken/Mindustry#2]
I bought the upgrades for the new weapons, however I cannot seem to be able to change to them. Is there some set of keys that I need to use, or is it just buggy?

**Comment by Anuken** [comment]
You _should_ be able to use the scrollwheel to switch weapons. However, I haven't tested this in the HTML5 version, so most likely there's a problem with it not handling the scroll wheel event. I'll look into this when I get back.

**Comment by LegusX** [comment]
Ah, it was the mouse scrolling. I was able to switch it by scrolling, without any major issues. (All of which I believe have to do with the fact that I am currently using a laptop). Sorry about that then.
