### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by ritzip** [Anuken/Mindustry#2000]
![Screenshot_20200430-144152~3](https://user-images.githubusercontent.com/49394064/81300450-441fdb80-90aa-11ea-8ad7-6a557d759ff5.png)

**Comment by DeltaNedas** [comment]
2k

**Comment by BasedUser** [comment]
router

**Comment by laok233** [comment]
how useless

**Comment by ritzip** [comment]
what now

**Comment by Davizun** [comment]
no
