### ISSUE TITLE
No "5.0 Build 104.10" in the Releases page?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Anuken/Mindustry#2009]
Hello, so I looked at the [GitHub Releases page of Mindustry](https://github.com/Anuken/Mindustry/releases), and it says 104.6. When I check in [Mindustry's itch.io's page](https://anuke.itch.io/mindustry/download/eyJleHBpcmVzIjoxNTg4OTUwMjM2LCJpZCI6MTQwMTY5fQ%3d%3d.SVG6JQP0A2Q5oZo9Q3Is8FrjWNc%3d), it says 104.10. I might lack some clarity on this, but can you explain why it is like this?

**Comment by Anuken** [comment]
104.10 was released as an "undo" patch of the April Fool's version, which was only released on desktop platforms. No Github release was made.

**Comment by TheEvilSkeleton** [comment]
Okay, thank you
