### ISSUE TITLE
Graphic glitch/bug

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2012]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *Black bars appearing after a unit dies.*

**Steps to reproduce**: *Played around with the mod sk7725/Commandblocks to fix stuff, and suddenly i noteced when a unit dies, these black bars are left. Even after disabling the mod or restarting the app, these bars are still there.*

**Link to mod(s) used, if applicable**: *sk7725/Commandblocks was present, but the bug persisted even after disabling that mod.*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
![Screenshot_20200509-173157_Mindustry](https://user-images.githubusercontent.com/58885089/81468758-7c472b80-921c-11ea-89c3-af03176e602d.jpg)

**Comment by sk7725** [comment]
Also, I dunno what happened with the format but cannot un-uglify it for some reason

**Comment by sk7725** [comment]
I found the reason, my mod overused print(i forgot to remove that after debugging)and made the last_log.txt a whopping 6 MB which resulted in performance issues, it was fixed when I deleted last_log.txt. However, I still believe this is not working as intended and should be fixed(malicious mods?).

**Comment by Anuken** [comment]
The sprite that's becoming black here doesn't exist in 6.0, so this isn't relevant anymore.

> malicious mods

There's nothing I can do about mods allocating too much memory.

**Comment by sk7725** [comment]
Correction: this problem recurred, independant of the size of the last_log.txt.

**Comment by sk7725** [comment]
It is quite annoying, any idea how to fix it?

**Comment by Anuken** [comment]
Swipe out of the app completely when restarting (as opposed to pressing 'quit').
