### ISSUE TITLE
Beta Tester

### ISSUE THREAD

**Issue by Bot420L** [Anuken/Mindustry#2015]
![Screenshot_2020-05-10-09-17-49-63](https://user-images.githubusercontent.com/64875195/81488929-36cd4180-92a2-11ea-85ce-ccca9ac1d443.jpg)
Platform: Android

Build: 104.6

Issue: When i unlocked Plastanium there were two images. There's also black things in schematics

Steps to reproduce: I was playing mindustry. Then i looked at schematics

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
i can reproduce black schematics issue (which is almost definitely reported) but i have no idea what title or the other issue is

**Comment by Bot420L** [comment]
There were two images of plastanium when i unlocked it

**Comment by Anuken** [comment]
> i can reproduce black schematics issue

I can't. What are the criteria for it happening?
