### ISSUE TITLE
Enemy drop points deleted by random generated rivers.

### ISSUE THREAD

**Issue by rjb25** [Anuken/Mindustry#2016]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *If you have a randomly generated river, and the water tile lands under a spawn, the spawn is deleted. Annoying bug for river custom games like TheGreatChallenge*

**Steps to reproduce**: *Add a drop point. Set a runtime river generation to no threshold so it covers whole map for testing purpose. See that you now have no drop point when you play game.*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Overlays like spawn points can't spawn on water blocks, and ground enemies would drown in water anyway.

**Comment by rjb25** [comment]
*Shallow water* They can still walk over it.

**Comment by rjb25** [comment]
Why can't spawn points be on shallow water?

**Comment by Anuken** [comment]
No overlay blocks can be on any type of water. The game does not differentiate between types of fluids.

**Comment by rjb25** [comment]
How then might I resolve the issue of some games with random rivers turning into sandbox?

**Comment by rjb25** [comment]
One possibility would be to add an ignore feature? Add a third terrain trait that ignores certain blocks during random generation?

**Comment by v6** [comment]
Why is this closed? Had same issue

**Comment by v6** [comment]
MY steps to reproduce: 

Add a drop point. Use runtime river generation *at all*. Percentage of games have a chance that the river overlay will overwrite the drop point overlay when I actually try to play the map.

**Comment by Anuken** [comment]
> How then might I resolve the issue of some games with random rivers turning into sandbox?

You can't. There are many issues that can occur with random terrain, including impassable regions and completely blocked-off spawnpoints. The map filter system was only ever designed for random ores and symmetry. If you're really bothered by this, don't use any other filters.

> Why is this closed?

Scroll up.
