### ISSUE TITLE
Schematic with filters crashes game.

### ISSUE THREAD

**Issue by GamyGamer** [Anuken/Mindustry#2017]
**Platform**: *Windows*

**Build**: *8257*

**Issue**: *When trying to create schematic game crashes.*

**Steps to reproduce**: *I was trying to create schematic, it looks like crash occure when filter/infinity item creator thing is being used*

**Link to mod(s) used, if applicable**: *None*

**Crash report**:

[crash-report-05_10_2020_10_58_42.txt](https://github.com/Anuken/Mindustry/files/4605409/crash-report-05_10_2020_10_58_42.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
