### ISSUE TITLE
Editor undo problem

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#2018]
**Platform**: Windows 10

**Build**: Build 104.10

**Issue**: Undo bug

**Steps to reproduce**: See animated gif
![녹화_2020_05_10_19_19_32_714](https://user-images.githubusercontent.com/44261958/81496532-3d37d980-92f3-11ea-97f9-22348ad2da2c.gif)

**Link to mod(s) used, if applicable**: vanilla

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not relevant in 6.0.
