### ISSUE TITLE
Phantom Builder Drones moving at Slow "Building" Speed when not Building

### ISSUE THREAD

**Issue by TickTakashi** [Anuken/Mindustry#2022]
**Platform**: Windows

**Build**: 104.10

**Issue**: Phantom builder drones lag very very far behind the player, and move at the slow speed that they usually only move at when building something, whenever the player is building (even if they are not building themselves). This causes them to very rarely ever help during building, and a strange behaviour where they will stutter-step (move very slowly, then speed up hugely, then move slowly again) when the player is building multiple structures - because the drones speed up in the split second that it takes for the player build laser to switch to a new target - as they are completed. 

At the moment, one workaround is to build a large number of cheap structures (like conveyor belts) and immediately destroy them, so that the builder drones can use this rapid stutter step to catch up to the player before starting the real building. This bug can also be avoided by restarting the game a few times.

**Steps to reproduce**: This happened on desolate rift,right from the start of the game. I manually loaded 8 phantom builder drone factories with resources from the core, and the spawned builders behaved this way. I am unsure if this is related though.

**Link to mod(s) used, if applicable**: None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not relevant in 6.0.

**Comment by TickTakashi** [comment]
Is there something new in 6.0 that makes this irrelevant?

**Comment by Anuken** [comment]
Phantom drones in 6.0 don't even have any AI right now.

**Comment by MEEPofFaith** [comment]
n i c e
