### ISSUE TITLE
0% Music control is not actually 0%

### ISSUE THREAD

**Issue by superb0y03** [Anuken/Mindustry#2031]
Setting music control to 0% will not actually mute the music, merely make it quieter

**Comment by Gdeft** [comment]
1. Use the template
2. There was an issue for this, it's already closed
3. You didn't check the closed issue
4. Use the template
5. No 1.

**Comment by itcannotbe** [comment]
Is this another one of this #1926 ?

**Comment by Gdeft** [comment]
#1507

**Comment by superb0y03** [comment]
Yes, this one's on PC

**Comment by superb0y03** [comment]
The issue isn't resolved yet however and should probably have at least one of these open to show that

**Comment by Anuken** [comment]
It's been resolved a very long time ago in the master branch.

**Comment by superb0y03** [comment]
I got this on the latest steam release. Has the fix not deployed there?

**Comment by Anuken** [comment]
Yes.

**Comment by Zephrnos** [comment]
the fix clearly hasn't it still persists

**Comment by Arrcival** [comment]
It also depends on "how" you move the slider. If you flick it to 0%, the fact that it doesn't get muted is really noticeable

[Here's an example of tests on the music slider](https://streamable.com/2y6b1b) done on 104.10
