### ISSUE TITLE
Unable to use resoures tab after a while.

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2035]
**Platform**: *Windows 10*

**Build**: *8291*

**Issue**: *If I play on a campaign map after a while the resource dropout tab doesn't open anymore on drills and core. I can see it open but it closes so fast I cant pick up resources from it*

**Steps to reproduce**: *Hard to tell. I build some drills and collected manually from them after a while the issue appeared*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
the only thing in the code that's mildly related to it that changed recently afaik is the throughput change so plastanium conveyors correctly showed up, maybe that somehow broke inventory? 🤔
