### ISSUE TITLE
6.0/multiForge 

### ISSUE THREAD

**Issue by SnakkiZXZ** [Anuken/Mindustry#2042]
What if we put two factories on? I propose to unite a large silicon smelter and a large metaglass forge. 
![miniGif_20200512205627](https://user-images.githubusercontent.com/62109325/81721190-eec43f80-9498-11ea-84ba-a2d7dc2fff7d.gif)
my code is not perfect and requires refinement, but it was created to show the principle of work

P.s. hope this time correctly)

**Comment by itcannotbe** [comment]
Still the wrong repo.

**Comment by SnakkiZXZ** [comment]
I'm at gitHab for the first time, I don't know how it works here.

**Comment by DeltaNedas** [comment]
use a mod
