### ISSUE TITLE
Icons are broken with UI scales above 100% on Android

### ISSUE THREAD

**Issue by kdrag0n** [Anuken/Mindustry#2047]
**Platform**: Android

**Build**: release build 104.6 and current master (c432639dfae862e4fb46e81b3a376cfb363031b7)

**Issue**: When the UI scale is increased above 100% on Android, some icons are replaced with random content from the texture atlas. Even small increments like 125% trigger the issue, but higher increments (e.g. 200%) make the problem much easier to see. It looks like all icons are affected, but in-game textures are not.

125% scale:
![image](https://user-images.githubusercontent.com/7930239/81780386-4c618780-94ab-11ea-81bc-bdfbfdbd9eee.png)

200% scale:
![image](https://user-images.githubusercontent.com/7930239/81780354-4075c580-94ab-11ea-8fb9-9c45fa26703e.png)

I am not sure if this issue also affects macOS or Windows, but it doesn't appear to affect desktop Linux.

**Steps to reproduce**:

1. Set UI scale to 200% to make it very apparent
2. Restart the game
3. Look at the main menu icons

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is because the game can't fit textures above a certain size into the atlas. Won't fix.
