### ISSUE TITLE
Modding: Sprites-Override folder not overriding items and Terrain boundaries

### ISSUE THREAD

**Issue by DarkWyvren** [Anuken/Mindustry#2048]
**Platform**: *Windows*

**Build**: *release build 104.4*

**Issue**: *Modding: Sprites Override folder not overriding items and terrain boundaries*

**Steps to reproduce**: 

Items:
*Making a texture pack mod with new item sprites within the ...project\sprites-override\items directory with the naming format 'item-<name>.png (e.g. item-coal.png) does not override any of the in-game item sprites. Naming the file <name>.png (e.g. coal.png) has been tried with no success as well.*

textures that i want changed:
![image](https://user-images.githubusercontent.com/13158938/81789099-d90d5380-9546-11ea-9801-ffe500a909c1.png)

in game:
![image](https://user-images.githubusercontent.com/13158938/81789158-eaeef680-9546-11ea-964a-61554366fe16.png)

inside mod zip itself:
![image](https://user-images.githubusercontent.com/13158938/81788956-a9f6e200-9546-11ea-96a9-d3021d2fc8be.png)

Terrain boundaries:
base texture is overridden but the boundaries still use vanilla texture.
![image](https://user-images.githubusercontent.com/13158938/81789675-aa43ad00-9547-11ea-91e7-dba33489140c.png)

**Mods**: https://github.com/DarkWyvren/Pixel_Texturepack_Mindustry

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DarkWyvren** [comment]
Bug persists in the current custom build as of today.
Looking into the code and writing temporary Debug info prints, the sprites are sent for packing so the files are definitely there.

debug print of files retrieved from the sprite-override folder
![image](https://user-images.githubusercontent.com/13158938/81812823-028ba680-956a-11ea-8259-1bc698754a19.png)

Printing out the raw bytebuffer inside the temp Pixmap
![image](https://user-images.githubusercontent.com/13158938/81815863-e2f67d00-956d-11ea-9687-58d9c51c9703.png)

Decoded from bytearray in processing:
![image](https://user-images.githubusercontent.com/13158938/81815789-c8bc9f00-956d-11ea-9efb-98f803245e60.png)
(shows the retextured coal)

So it doesn't look like its a problem with loading itself at least, ill keep looking.

**Comment by Anuken** [comment]
This isn't a bug:
- Item sprites are not just one sprite. Each item is rescaled to several different sizes and saved with names `item-<name>-small`, `item-<name>-large`, etc. You have to override those instead.
- Terrain blending works similarly. The base texture **is never used in the game**; it is a template that is used to generate derivative textures when the vanilla atlas is re-packed. If you want to override them, you'll have to use the name `<name>-edge`.
