### ISSUE TITLE
Crawler mech doesn't attack

### ISSUE THREAD

**Issue by MrWho012321** [Anuken/Mindustry#2049]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
invalid use of the format ^

**Comment by Gdeft** [comment]
I like on how you did everything correctly. But it can be better if you actually fill out the thing so Anuke (and/or others) can help you.
