### ISSUE TITLE
Crawler mech doesn't attack

### ISSUE THREAD

**Issue by MrWho012321** [Anuken/Mindustry#2050]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *when the crawler mech attack it only stands their and doesn't move if enemy goes across them they explode like normal but the crawler mech doesn't run to suicide bomb it will only go if the command tell but not if attacking enemy attack*

**Steps to reproduce**: * I was testing all the mech on how they can help me to defend and if it is useful*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
Your `Steps to reproduce` isn't exactly *steps to produce*. You just told us that you were testing all the mech. **How** did you test all the mech is a more precise and correct info.

**Comment by Gdeft** [comment]
He tried.

**Comment by Gdeft** [comment]
He is saying that the crawler mech just stands there (idle) when it's supposed to attack/approach an enemy unit. But it'll still explode if the enemy unit touched/is close to that crawler mech.

**Comment by Gdeft** [comment]
The crawler mech doesn't approach the enemy unit unless it was told to do so (by commanding them using command center, I guess).

**Comment by Anuken** [comment]
> doesn't run to suicide bomb it will only go if the command tell but not if attacking enemy attack

It's not supposed to walk toward enemy units or blocks. No unit does that. Units can only move toward one specific location, like the enemy core or a rally point.

**Comment by Gdeft** [comment]
![2050](https://user-images.githubusercontent.com/63198340/81829491-24cef580-9565-11ea-92d6-2eab59f93eae.gif)
I think this is what he meant. If it does, then it's because units aren't supposed to cross the wave range/radius thing. But when the crawlers are making their way to wave spawn, they ignored the enemy units, they walked past them.
