### ISSUE TITLE
phase walls don't take any damage from fortress  (video file include)

### ISSUE THREAD

**Issue by VasianDuban** [Anuken/Mindustry#2051]
**Platform**: *Windows*

**Build**: *v104.10*

**Issue**: *phase walls don't take any damage from fortress  https://youtu.be/C_pz_pV2pxs pretty old bug*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Those artillery shells deal 0 contact damage; phase walls don't detonate them, so no splash damage is dealt.
