### ISSUE TITLE
Mindustry client does not check for AAAA records

### ISSUE THREAD

**Issue by kbeflo** [Anuken/Mindustry#2055]
**Platform**: Linux

**Build**: 104.6

**Issue**:

In regards to https://github.com/Anuken/Mindustry/issues/1725. Mindustry client does not check for AAAA records. To add, client does not accept IPv6 addresses on add server.

**Steps to reproduce**: 

1. Host server at a domain with only AAAA record
2. Add server using domain
3. Add server using IPv6 address

**Comment by Anuken** [comment]
My ISP doesn't support IPV6, and I don't have much interest in implementing this feature myself. If you want this fixed, submit a pull request.
