### ISSUE TITLE
Pause building does not pause building

### ISSUE THREAD

**Issue by zethnest** [Anuken/Mindustry#2061]
**Platform**: *Linux*

**Build**: Commit 603cb4295

**Issue**: When toggle the building mode (build/pause), it just keep building.

**Steps to reproduce**: Build like normal, then press the pause building button. Toggling on the `Auto-pause building` doesn't work too. This is both in sandbox and campaign.

---

- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Pausing building isn't implemented.

**Comment by zethnest** [comment]
Ah I see. I thought It wasn't intended.
