### ISSUE TITLE
Sound effect has stopped when other building starting sound effect

### ISSUE THREAD

**Issue by grimsoul7** [Anuken/Mindustry#2063]
**Platform**: *Android*

**Build**: *104.6.*

**Issue**: *sound effect has stopped when other Building starting sound effect.*

**Steps to reproduce**: *just build a building on near other building when play sound effect, it will overwrite other building sound effect, example 
When meltdown shoot enemy and also other turret fire on enemy. Meltdown sound effect will stop .*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Android has a very low sound effect limit; this is just how the system works.

**Comment by grimsoul7** [comment]
Oh no
