### ISSUE TITLE
Factories input in bridges from wrong angle

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2066]
**Platform**: *Windows 10*

**Build**: *8343*

**Issue**: *Factories input in bridges from wrong angle dependent on orientation*

**Steps to reproduce**: *look at screenshot - if I should stop looking for bugs like this just tell me*
![333](https://user-images.githubusercontent.com/57239116/82103548-baa88300-9713-11ea-89a7-4d23d7da5ee5.jpg)

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
im almost certain that it was reported already
dont play 6.0

**Comment by ado1928** [comment]
![image](https://user-images.githubusercontent.com/47899778/82122939-ec166280-9796-11ea-831f-ab96c323ec6e.png)
