### ISSUE TITLE
Cores can use the same vaults/containers as expansion more than once

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry#2067]
**Platform**: Android

**Build**: 104.6

**Issue**: *Cores can use the same vaults/containers as expansion more than once.*

**Steps to reproduce**: Surround a vault or container with cores

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by braainsiogame** [comment]
ok
