### ISSUE TITLE
Yellow Box Visual Glitch

### ISSUE THREAD

**Issue by Agent-coulson** [Anuken/Mindustry#2076]
**Platform**: *Windows 7*

**Build**: *steam build 104.10*

**Issue**: *The map/screen fills with a yellow box in the bottom left of what ever I build*

**Steps to reproduce**: *there are no steps. this just happens when ever there is delay on building something.*

![mindustry graphic glitch](https://user-images.githubusercontent.com/43828062/82166668-6833a780-9876-11ea-9f3f-619b9879d976.PNG)

**Link to mod(s) used, if applicable**: *NA*

**Crash report, if applicable**: *NA*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
whats your:
- gpu
- gpu driver version

**Comment by Anuken** [comment]
This is most definitely a GPU/driver bug; I haven't seen anyone else have this problem across countless devices and platforms. Can't fix.
