### ISSUE TITLE
Issue with crashing

### ISSUE THREAD

**Issue by Spartanq** [Anuken/Mindustry#2086]
**Platform**: *Android*

**Build**: * 104.6*

**Issue**: *Everytime I reload (remove or add) a mod, it crashes out to my home screen.*

**Steps to reproduce**: * Add or remove a mod from active mods*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
could you supply the crash report / latest log from its android application directory?

**Comment by Anuken** [comment]
The Android version doesn't save crash reports, and without a log, I can't help you.

**Comment by Quezler** [comment]
weird, when i debugged a mod once for someone on android that log file contained what i was looking for 🤔

**Comment by Spartanq** [comment]
All I know, is that I have Mindustry Green, Lead Factory (ies?) and Opour
Mod.
