### ISSUE TITLE
Connection stability. 

### ISSUE THREAD

**Issue by ETmecka-06** [Anuken/Mindustry#2091]
**Android**

**Motorola Z3**
PDX29.84-51-11

Hello. I hope this will an easy fix.

Scenario:
I have 2 phones. 1 has a data plan. And both get connected to the same wifi.
  1. So a **couch co-op** should be ok over the same wifi. Well, so far its a hit and miss even on the same wifi.
  2. Then I use a **tethering app** to use my data and others link in with their data or wifi. Thus using a local server has given us the same affect as a couch co-op. (Line 1.)
  3. When I'm on a **public server** (official or not), its less frequent that I loose connection, but it still happens. When it happens i can jump right back in the server. And "Loading world Data" happens a lot.
  4a. **Join Hosted.** When I join a hosed game over a local sever (tethering app) it seams to be half of the time I get the (unknown network error) and can't get in. But for the rest of the time, I can go in ok. Then a few seconds goes by, and the connection is lost. Then I repeat the first part of Line 4a. Eventually it let's me in, then it losses it again later.
  4b. **Hosting.** Then the same thing happens to my friend if they join the game I'm hosting over a local sever (read 4a). But I'm flying ok.
  5. So **could it be the tethering app.** Nope. For I "Force Stop" the app from operating. And just use just the wifi on my 2 devices. (Also turning my Data off.) Then over wifi, Lines 4a and 4b - depending which device hosing - happens again. (Tho without the local sever)

Yeah im sorry if its a pain.
Thanks for the hard work.

**Link to mod(s) used, if applicable**: 
None

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Probably your phone couldn't keep up with the game.

**Comment by Anuken** [comment]
This doesn't happen on any of my devices, nor does it happen for most other people. There are far too many variables here that could be affecting your connection; I can't fix this.

**Comment by ETmecka-06** [comment]
Yeah i wasn't sure what to think about it.
  Just wanted to see what you guys thought.
Its probably a bunch of stuff.
Thanks for your help.
