### ISSUE TITLE
Language menu show "Tiếng Việt" as "Ting Vit"

### ISSUE THREAD

**Issue by braainsiogame** [Anuken/Mindustry#2095]
**Platform**: *Windows*

**Build**: *8420*

**Issue**: *In language menu, "Tiếng Việt" is shown as Ting Vit. Will probably affect other stuff too.*

**Steps to reproduce**: *Inside the bundle folder, put in bundle_vi.properties, boot up the game, go to the language menu  *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Those characters are not supported in the font.

**Comment by braainsiogame** [comment]
make a font with the character then
