### ISSUE TITLE
Wrong translate in Turkish

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#2098]
Platform: Android

Build: 104.10

Issue: When joining a server and it doesnt, the text that appear in Turkish translate says (Adrwsin) is must say (Adresin)

Steps to reproduce: Make your game Tr and try to join a closed server.

Link to mod(s) used, if applicable: No Mods

Crash report, if applicable: No Crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
To correct the translations yourself see: https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md
