### ISSUE TITLE
can't import ground zero from assets/maps to the game/editor (throws an error)

### ISSUE THREAD

**Issue by kldashjfhasdf** [Anuken/Mindustry#2099]
**Platform**: win10

**Build**:  104.10 (steam)

**Issue**: can't import ground zero from assets/maps to the game/editor (throws an error)

**Steps to reproduce**: NA

**Link to mod(s) used, if applicable**: no mods/clean install

**Crash report, if applicable**: NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X
![groundZero_import_error](https://user-images.githubusercontent.com/65813700/82729960-6e090d00-9cfc-11ea-8acf-52245a3f9967.png)
 ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're not supposed to be able to. The groundZero map in the master branch uses a completely different format.
