### ISSUE TITLE
Linear Filtering rendering very messed up on mod blocks

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2101]
**Platform**: Windows

**Build**: 104.6

**Issue**: When using mod blocks, as a main example, unit factories, linear filtering makes very sharp lines that don't blend very well compared to what it does for normal blocks (which makes them look much smoother). 
![image](https://user-images.githubusercontent.com/34169172/82736630-83743c00-9ce8-11ea-8607-a4a31e2cc1fc.png) This is what a normal factory looks like (on the top), versus what a mod block factory looks like (on the bottom), the only difference between the two textures is coloring, and yet the lines still make it look messed up. I have tested this on multiple mods (the one in the photo is my own), and results like these happen on any of them to unit factories as well as drills.

**Steps to reproduce**: Install a mod with unit factories and drills, and place one of those items down with linear filtering enabled.

**Link to mod(s) used, if applicable**: Appears to affect almost all mods, definitely not related to mods themselves.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> the only difference between the two textures is coloring

This is false. The bottom texture does not have any antialising applied, while the bottom one does. This causes linear filtering to blend the edges with black pixels. All the sprites present in Mindustry have antialising applied with a filter before being packed; this isn't done with mod sprites due to the performance implications of running a filter on every single sprite at load time.

**Comment by Syncinus** [comment]
Ah okay. I hope some way to do that for mods is found in the future that won't break game performance.

**Comment by Anuken** [comment]
I won't be adding loading-time antialising, even if the costs are neglible. It's not applicable to all sprites; you'll need to do it yourself.
