### ISSUE TITLE
Borderless window mode hides corners, doesn't use current resolution

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#2110]
**Platform**: *Windows*

**Build**: *5.104.10*

**Issue**: *Parts of the game interface are hidden when using "borderless" mode. My screen resolution is 1920x1080, which is very common. When I select "fullscreen" mode I can see parts of the interface which are hidden when "borderless" is selected. It doesn't seem to be a huge issue, but fixing would make the game more stable for capture in OBS and video auto splitting that I make and use for speedrunning.*

**Steps to reproduce**: *You can see this if you take a screenshot inside those two modes, here is how it looks:*

Fullscreen:
![image](https://user-images.githubusercontent.com/4199082/82853922-afbdd180-9f0f-11ea-89d4-6957d0046654.png)
Borderless:
![image](https://user-images.githubusercontent.com/4199082/82853953-c401ce80-9f0f-11ea-8445-d606bd2209da.png)
Difference from photoshop (UI elements move outwards):
![image](https://user-images.githubusercontent.com/4199082/82854138-32469100-9f10-11ea-8a87-acaa6f94545d.png)

Difference is even more noticable once you enter the game:
Fullscreen:
![image](https://user-images.githubusercontent.com/4199082/82854255-936e6480-9f10-11ea-861d-7aa6bdf5ebb0.png)
Borderless:
![image](https://user-images.githubusercontent.com/4199082/82854280-a08b5380-9f10-11ea-9034-948d81302f60.png)
Difference:
![image](https://user-images.githubusercontent.com/4199082/82854316-bf89e580-9f10-11ea-9e8b-4037ca5b25a2.png)

What I also noticed is that when you select game source in OBS while using borderless window, it autodetects window size as of 1934x1094, which is not expected:
![image](https://user-images.githubusercontent.com/4199082/82854438-17285100-9f11-11ea-99e0-7e51b3d5447a.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I haven't had this problem across several OSs and monitors - since I can't reproduce it, I can't fix it unless someone else submits a pull request. This could be a bug with SDL, or something wrong with window positioning.

Use fullscreen or windowed mode when recording instead.

**Comment by LeoVen** [comment]
I'm also having this issue. Windows, build 5.104.10 (on steam). The logo on the main menu gets very close to the top and the mechs menu is actually touching (if not cropped off) the screen. I was also able to notice another bug when changing between Fullscreen and Borderless Window:

The game is initially not on Fullscreen and not on Borderless Window. Then you click: Borderless Window -> Fullscreen -> Fullscreen. At this point, I can actually see the missing pixels at the bottom and right side of the screen (with vscode opened at the background):

![image](https://user-images.githubusercontent.com/26551037/82858543-8d658d00-9eea-11ea-96ec-03d1a0b50f8a.png)

**Comment by LeoSko** [comment]
Just another note, may help: previously (I guess, before 5.104.8) OBS auto-detected size of 193**6**x1094.

**Comment by LeoSko** [comment]
I would use windowed option if mindustry could capture cursor and not let it go away from the game window unless I Alt+Tab from it, but it doesn't, which makes it really easy to misclick somewhere out of game window and/or misclick "next wave" button.
When the game is in fullscreen and minimized, it is not being captured by OBS, cuz game is not being rendered and the image is displayed static - not a nice idea for streaming.
