### ISSUE TITLE
Phase conduit not outputting forward

### ISSUE THREAD

**Issue by AayushSabharwal** [Anuken/Mindustry#2113]
**Platform**: *Windows*

**Build**: *104.3

[saves.zip](https://github.com/Anuken/Mindustry/files/4682714/saves.zip)

*

**Issue**: *I have a phase conduit that only seems to output to the sides and not forward. Up the line, closer to production it outputs everywhere but where I have it, it doesn't. Map is tar fields, near the enemy spawn, right below the bottom-most Illusion turret. Git wont let me attach the entire data folder, and I have no idea which save is the active one so I just attached the entire saves folder*

**Steps to reproduce**: *Was supplying cryo to defences*

**Link to mod(s) used, if applicable**: *EyeOfDarkness/AdvancedContent was the only mod active*

**Crash report, if applicable**: *Nope, no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. This is not relevant in 6.0; conduit code has changed quite a lot.
2. Update your game.
