### ISSUE TITLE
Cant move.

### ISSUE THREAD

**Issue by KyleTheJudge** [Anuken/Mindustry#2115]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't.

**Comment by KK6DOC** [comment]
hah

**Comment by KyleTheJudge** [comment]
I didnt know it would submit a report if I hit the button, I thought it would take me to the editing screen when hitting the button.
