### ISSUE TITLE
all game data erased after BSOD

### ISSUE THREAD

**Issue by 3thanguy7** [Anuken/Mindustry#2118]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *first, I have to note that my device has been having BSOD issues, so the BSOD itself is likely not the fault of your game. however, what happened is that a random BSOD occured mid-game (THREAD_STUCK_IN_DEVICE_DRIVER, I think), and upon my computer rebooting, all of my save data was cleared. the game put me in the tutorial, i had no launched resources, nothing in the tech tree, etc. additionally, my save in the steam cloud (which I tried to download and import) gives me an "invalid save" error. *

**Steps to reproduce**: *I was in ruinous shores, just after the boss wave. the BSOD occured when i clicked the "show desktop" button mid-game*

**Link to mod(s) used, if applicable**: *None*

**Crash report, if applicable**: *debug.log is attached*
[debug.log](https://github.com/Anuken/Mindustry/files/4686200/debug.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this. The game attempts to make backups, which evidently have failed here.

**Comment by DeltaNedas** [comment]
install debian
