### ISSUE TITLE
[Bug] Waves randomly became very easy on Frozen Desert 

### ISSUE THREAD

**Issue by leumasme** [Anuken/Mindustry#2121]
**Platform**: *Windows (Steam)*

**Build**: *104.10 (Steam)*

**Issue**: I was playing Multiplayer via Steams with 2 friends on Frozen Desert, when from wave 14 or 15 on, the waves started becoming incredibly easy. 2-3 of the generic default ranged enemies started spawning per round, when there were ~10+ in the previous waves. We then just decided to launch at wave 20 with 3 enemies spawning, as this was clearly not intended and we had full resources anyway.

**Steps to reproduce**: I am not sure how to reproduce this issue, and sadly didnt think about saving the gamestate before launching. i will let you know if i experience it again. 

**Link to mod(s) used, if applicable**: *none*

**Crash report, if applicable**: *-*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by leumasme** [comment]
![0007307](https://user-images.githubusercontent.com/29953391/83060094-38955400-a05b-11ea-97d6-43f73c8c9fbe.png)

**Comment by Anuken** [comment]
This isn't relevant in 6.0.

**Comment by leumasme** [comment]
Please explain. I am on the latest steam release, what is 6.0 and why a different versioning system?

**Comment by Anuken** [comment]
6.0 is the release that will be coming after 5.0 (*the current release on Steam*).
