### ISSUE TITLE
Entities region reads the wrong amount of bytes on map load (into editor)

### ISSUE THREAD

**Issue by JuhaJGamer** [Anuken/Mindustry#2126]
**Platform**: Windows

**Build**: Assume 103 as it's through steam. However, I ran this on a friend's pc (to be honest here I do not have Mindustry downloaded and was having another developer run my files, so I am not sure of the exact build)

**Issue**: The entity reading code throws an error when loading a seemingly correct file. An entity region with no entities, that is, `00 00 00 08 00 00 00 00 00 00 00 00`, *should* be loaded as two integers as per [SaveVersion.java](https://github.com/Anuken/Mindustry/blob/42252fa217c7f4025072c4779a9df477da5be7af/core/src/mindustry/io/SaveVersion.java#L277). However, it reads 5, and errors out as the length set in the file is 8. I'm not sure if this is actually a bug or whether I am just really stupid and don't understand the reading code at all.

**Steps to reproduce**: Long story short, was making a python module to do some neat map manipulation for procedurally generated terrain as a base. The resulting file ([out.msav](https://cdn.discordapp.com/attachments/624581350741245953/716068315340079104/out.msav)) gave me this ![this](https://cdn.discordapp.com/attachments/624581350741245953/716068481270808718/unknown.png) error which I then fixed by changing the region length to 5 as it for some reason only read 5 bytes. 

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're looking at the 6.0 entity IO code, which is very different from the build 104 IO code. They're not compatible.

Unless you can prove that the game is producing invalid data that can't be loaded properly by itself, errors in scripts should be discussed in the Discord and not reported as issues.
