### ISSUE TITLE
Anti-virus program was blocking game

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#2135]
**Platform**: Windows 10

**Build**: 104.10

**Issue**: See screenshot
![image](https://user-images.githubusercontent.com/44261958/83630982-b5827980-a5d7-11ea-8776-37f92c35799a.png)
Download from itch.io

**Steps to reproduce**: Run Mindustry.exe

**Link to mod(s) used, if applicable**: vanilla

**Crash report, if applicable**: nothing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
OMG steam version too

**Comment by itcannotbe** [comment]
Probably a false positive.

**Comment by DeltaNedas** [comment]
this is an issue with your antivirus
read and compile the source then
```sh
#!/bin/sh
java -jar Mindustry.jar
```

**Comment by itcannotbe** [comment]
It's not the .jar that getting flagged @DeltaNedas it's the Executable.

**Comment by Anuken** [comment]
I've never seen anyone else report AV issues recently, so unless it's a widespread problem this isn't worth looking into. They probably don't like the EXE icon.

**Comment by DeltaNedas** [comment]
if the launcher is the problem use the simple script, chmod +x and use

**Comment by Anuken** [comment]
> chmod +x

If you were running this on Linux, you wouldn't have a problem with antiviruses in the first place.
