### ISSUE TITLE
Game crashes with a nonexistent item name in the itemDrop key in an ore.

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#2137]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux
**Build**: *The build number under the title in the main menu. Required.*
104.10
**Issue**: *Explain your issue in detail.*

My bug report isn't really a bug, but it causes the game to crash every time you open it until you delete it out of your mod folder. The bug is that if you have an ore which has the code:
`type: OreBlock`
`itemDrop: (put a nonexistent item name here)`

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

Create a basic mod, with only a mod.json and content folder, then create a blocks folder in the content folder and 

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the 
issue.*

nichrosia/BugTest

**Crash report, if applicable**: *The contents of relevant crash report files.**

crash report is in the repository

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
It's a NullPointer Exception. Of course it does that.

**Comment by nichrosia** [comment]
I am sorry. I will close the issue. I do not know much about JavaScript currently so, forgive me for this.

**Comment by zethnest** [comment]
I've been thinking to implement if it errored in loading non-existant objects, then just skip it.

**Comment by Gdeft** [comment]
It shouldn't skip it or else the author doesn't know something is wrong and the mod user will use the thing, and it'll crash too.
