### ISSUE TITLE
Multiplayer incompatibilities due to mismatched versions posted on different platforms

### ISSUE THREAD

**Issue by Famous5000** [Anuken/Mindustry#2145]
**Platform**: *Android/iOS/Steam*

**Build**: Android: 104.6, iOS: 104.4, Steam: 104.10

**Issue**: Trying to play multiplayer cross-platform with my friend is impossible due to the build mismatches explained above.

**Steps to reproduce**: Download the app from iOS and get the version stated directly from the App Store. Download the Steam version and get the version stated directly from Steam. *optional* Download the Android version and get the version stated directly from Android. Attempt to play multiplayer with the other platforms, locally or not.

**Link to mod(s) used, if applicable**: This is not a mod issue.

**Crash report, if applicable**: There are no logs; this is an issue with a version mismatch.

edit: removed an extra / on the platform section.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported for the current version(s).**

**Comment by Kieaer** [comment]
104.0 ~ 104.5 ≠ 104.6 ~ 104.10

**Comment by DeltaNedas** [comment]
This is Tim Cook's problem.
104.10 removed April fools stuff.
104.6 is fully compatible with 104.10.
Compile it yourself if you want a newer version ahead of Tim's strange schedule.

**Comment by markozajc** [comment]
You can:
* Jailbreak the phone and sideload newer Mindustry
* Either buy more apple hardware or get it virtualized somehow, then compile and install Mindustry using xcode. Not sure if you need a developer license for that as well, pretty sure you don't.
* Downgrade the version on the phone and computer by manually compiling build 104.5
* Tell the person using an iphone to use something else for Mindustry
* Wait until apple decides to release the update

**Comment by Anuken** [comment]
You haven't described exactly what happens when you try to play cross-platform. Sub-versions like .6 and .10 are compatible - how do you explain all the Android users (104.6) playing on 104.10 servers right now?

> Trying to play multiplayer cross-platform with my friend is impossible 

It's not.

**Comment by itcannotbe** [comment]
He was pointing out that 104.4 (iOS) cannot play with 104.6/.10

**Comment by Anuken** [comment]
No, he claims that it doesn't work even with Android:
> optional Download the Android version and get the version stated directly from Android. Attempt to play multiplayer with *the other platforms* [including Steam, presumably], locally or not.

**Comment by Anuken** [comment]
In any case:
- You haven't provided enough information about the problem for me to take action
- Cross-platform play works fine for other people
- Even if there is an issue with cross-platform play on iOS, I won't be fixing it until the 6.0 release
