### ISSUE TITLE
Nuclear reactors lose inventory

### ISSUE THREAD

**Issue by mvrak** [Anuken/Mindustry#2154]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Seen on mobile and Windows.  Hosted on Windows.

**Build**: *The build number under the title in the main menu. Required.*
104.10, noticed since 102+

**Issue**: *Explain your issue in detail.*
I've seen this with Impact Reactors and Thorium reactors.  Once it starts on a particular reactor it doesn't seem to stop ever.
Impact Reactors:  Their normal consumption rate is something like 1 blast every 2 seconds.  I've seen them, at random intervals, suddenly lose all 10 blast.  Even watching them, and watching the blast disappear, I could not figure out how frequently this happens.  It seems to be one every 10+ seconds.  Once a reactor starts doing this, I could not get it to stop, even if I delete and rebuild the reactor in the same place.  I've usually seen this happen to just one reactor at a time.  
I'll notice the popular scrap driven impact schematic mysteriously stop working.  Normally, it is RNG on the titanium input, but something it is this.  I have no choice but to just delete the whole schematic and try again elsewhere.  
Thorium Reactors: Today I noticed this on Nuclear Production complex.
Had an array of 6 thorium reactors connected to tanks of cryofluid.
All 6 thorium reactors started dropping from 30 to 15 thorium.    When it happened it all happened at once.  It started repeating ~every minute, quickly depleting the supply of thorium, since that consumption was more than 1 belt could supply.  If they started below 30 I think they were dropping by 15 still, as they were quickly reached 0, despite the full belt of incoming thorium.  I don't have an easy way to watch more than 1 reactor at a time.
All of the reactors had been running fine for ~80 waves before this happened.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Normal gameplay.  I always play multiplayer and usually via Steam, and I don't recall ever seeing it on the official servers.  It might only affect Windows hosting.

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*
No mods used.

**Crash report, if applicable**: *The contents of relevant crash report files.*
No crashes.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by azekillDIABLO** [comment]
Can confirm absolutly random blast comsumption on my scrapacts. On the smallest one, with very low margin, the blast stocked in the container to varies from 60 to 300 at random. Because the impact seems to consume way too much from time to time.

**Comment by Anuken** [comment]
> suddenly lose all 10 blast

This isn't a bug; you're experiencing jumping amounts of items due to periodic syncing from the server. Conveyors aren't synced, so you wouldn't see the cause of the clog. See the numerous reported issues already reported about syncing.

**Comment by mvrak** [comment]
I don't understand.  If I'm constantly dumping mats from the core into the reactor, and the reactor is constantly losing the mats, how could that be a sync issue?  There is nothing that can "unload" the mats.   The numerical drop is consistent, which also makes it unlikely to be a sync issue.

**Comment by Anuken** [comment]
It can't *not* be a sync issue:

> It seems to be one every 10+ seconds.

This is consistent with the fact that syncing happens every ~10 seconds.

I don't know the exact circumstances of your problem, but next time it happens, run `/sync` and see what changes.

**Comment by mvrak** [comment]
Took a video of it.  If it is a sync issue, the reactor should be able to start up eventually.
https://www.youtube.com/watch?v=m4mTC6OZyy4

Started with something like 40 blast available in queue next to the reactor.  If this is a sync issue, how could it become desync, and how does the reactor never start?

**Comment by mvrak** [comment]
Ok, so if we stage the fuel in a vault, do /sync, check the vault, and then start.  If I have all of that on video, will that qualify it as a bug?

**Comment by Anuken** [comment]
If you can show that fuel disappears unpredictably from reactors *in singleplayer* without any syncing involved, then yes, that would qualify as a separate issue.
