### ISSUE TITLE
Can't see multiplayer chat

### ISSUE THREAD

**Issue by Gwynbade** [Anuken/Mindustry#2168]
Win10 

Steam build 104.10

**Issue**Issue: Multiplayer chat does not work properly for me. I can type and send messages, and my friend will see them (it also appears in the log). However, the speech bubble does not appear above my head.

And I can see my friend typing, but when they send the message, no message appears above their head - and most importantly of all, it does not show in the chat log, either, meaning I have no way to see their messages and am flat unable to communicate with my friend ingame unless I use an external service like Steam messaging.

**Steps to reproduce**: I open a map and invite a friend via Steam's friend invite service

Things I've tried to fix it that didn't work: Restarting the game, validating the game files, unticking and ticking the speech bubbles option in menu

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
are you on a normal server or steam server?

**Comment by Gwynbade** [comment]
What do you mean by normal and steam servers?

I am on a steam version and the problem is on all local and community servers

**Comment by Anuken** [comment]
This looks like a near-exact copy-paste of #1445, which doesn't make much sense. Have you really tried doing the things the original issue mentions, and have those reproduction steps been attempted, or are they only copied from the older issue?

I can't reproduce this problem, and as far as I know, nobody else on Steam can either. Either it's an extremely uncommon bug, or this issue report isn't accurate. Either way, I can't fix this.
