### ISSUE TITLE
Bridge conveyor has inconsistent behavior

### ISSUE THREAD

**Issue by WWOLGA** [Anuken/Mindustry#2169]
**Platform**: *Windows*

**Build**: *Release Build 104.10*

**Issue**: The bridge conveyor inconsistently accepts items from the back. See https://gfycat.com/difficultdecisiveduck . Because the blocks are the same, I suspect the issue is due to placement order.

**Steps to reproduce**: 

This schem results in the bridge conveyor accepting items from behind: bXNjaAB4nE2OCQ6DIBBFv6io3Yw36AU8RI9iddKSRjG4pafuESwC0s5PyJsXZgAHJAGirmoJWSNpuC5SvRIcxUhtOchJ1YS0lt1Mb6lQjGKsOjG1pVf5XYnmQT9x6Z/V8NefermQ2ndlZvEsRQOggKuzObmhQMfWRtwQ04Gn3YXehd5FzoWauEmEWPexI+u2+3y9rR89kbjZGKl9hTFN3P0os8S+yJUtAQ==

This schem results in the bridge conveyor not accepting items from behind:
bXNjaAB4nE2ObQ6CMAyGy4ABfoYb+M9fHMKjIDS6GFYyBsQDeh6PMOcY077J8vTJ2g02kEWQyLpD2LaEg9SnmdQjg63Q2FUDjapByBuSEz5JQamFrqUYuyqo41WJ9oY/cejv9fDX73qaUa27Crd4ItECQAm+9u7kjiKbpb7EHTEbCLS6OLg4uMS72BJ3SSC1feqJm7N5ufvcXMzbTmR+NoV8eYUxS9z/qFiIfQBjnzDD

**Link to mod(s) used, if applicable**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stuffyAI** [comment]
did you confirm whether the sending conveyor accepts items from the front or its the receiving conveyor relaying them?

**Comment by WWOLGA** [comment]
I did not confirm it when making the report, but I did just now. It does indeed seem to be the case that the final conveyor accepts items from the back: https://gfycat.com/exemplarycostlyibadanmalimbe

Schem for this: bXNjaAB4nE2OWw6CMBBFL6UUEJ87YAP8uAOXgtBoY2BIecVVuwQspaBzk8npyeSm2CH0wOu8kkhKkm06kn6l1xCJ6mSVtdTrQiIqqB7kmzQuneryWvVVtqnTXavyIX/i2Dzz9u+9b2iUeu2KbfFAqgRwhpuD3cKSZ7LMTMISM8FGq/Od802EDQN3jiMwOzCO2z3HXk236WPuQtcSIFq6GTMk3D/ihdgXitEtSA==
