### ISSUE TITLE
Cryofluid anomaly

### ISSUE THREAD

**Issue by GlasskyVL** [Anuken/Mindustry#2171]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *cryogenic factory consumes too many resources (titanium and water)*

**Steps to reproduce**: *I was building a impact reactor and noticed that one of the four reactors was running out of cryofluid.*

*P. S. - I'm worked on server (CN - Chaotic Neutral,  survive).*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
Have you done `/sync`?

**Comment by GlasskyVL** [comment]
what is the /syns ?

**Comment by Gdeft** [comment]
It's `/sync` not `/syns`, it does as what you expect.

**Comment by GlasskyVL** [comment]
I did not use this command. There was another player on the server who confirmed that it wasn't my problem.

**Comment by itcannotbe** [comment]
Screenshot the layout on the map together with the fps you are running at as well as a screenshot of the minimap or a mapwide screenshot.

**Comment by GlasskyVL** [comment]
I can't pin screenshots from my phone

**Comment by WWOLGA** [comment]
You haven't explained how to reproduce the issue

**Comment by DeltaNedas** [comment]
You can't really reproduce it but I've had it happen before. Sync didn't work and other players saw it too, my fix is to replace the cryo mixers and conveyors.

**Comment by itcannotbe** [comment]
I think sync does work but quickly desyncs due to low device fps or low server tps.

**Comment by Anuken** [comment]
There's nothing I can do with this information.
