### ISSUE TITLE
Sound never truly goes away

### ISSUE THREAD

**Issue by Zephrnos** [Anuken/Mindustry#2172]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windoiws
**Build**: *The build number under the title in the main menu. Required.*
steam 104.10
**Issue**: *Explain your issue in detail.*
Even with all sounds set to 0, there's still very light music sounds. Not game breaking, just annoying.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Set all sounds to 0 and listen closely
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

Think about this statement.

**Comment by Zephrnos** [comment]
ye i looked it up and it says you already deployed a patch for steam even though the issue clearly still persits

**Comment by Anuken** [comment]
Show me the post where I say that I have deployed it as a patch to Steam.

**Comment by zethnest** [comment]
This is getting old

**Comment by Anuken** [comment]
i n d e e d

**Comment by Zephrnos** [comment]
https://github.com/Anuken/Mindustry/issues/2031 there ya go

**Comment by zethnest** [comment]
![Screenshot_20200618_095127](https://user-images.githubusercontent.com/16971676/84968534-4c5b4400-b149-11ea-8d4f-167a1b167dfd.png)

**Comment by Zephrnos** [comment]
i just read it wrong oops never pick a fight on the internet

**Comment by ado1928** [comment]
It's a slider issue anyways. On low fps if you drag the sound slider to 0 quickly, the music will still play
