### ISSUE TITLE
Item with Content ID over 128 corrupts the save

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2173]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *I noticed some items are not saving(failing while saving)/corrupting the save file(failing while loading). All items were auto-generated by events(yes, I know I am not supposed to do that in the first place), but only items with ID over 127(127 works fine, 128 does not) are not working. Some questions: 1.Does normal mods with more than 127 items show this behavior? 2.Is there any recommended way to do what I did with my mod(I am aware of the events not clearing)? 3.Any way to prevent this behavior?*

**Steps to reproduce**: *Install sk7725/MoreItems and then use the modded items(place them on a conveyor belt).*

**Link to mod(s) used, if applicable**: *[https://github.com/sk7725/MoreItems](https://github.com/sk7725/MoreItems)*

**Crash report, if applicable**: *No crashes, but the log has something to say: ```
[E] Failed to generate preview!: java.io.IOException: Error reading region "preview_map". 	at mindustry.io.SaveFileReader.region(SaveFileReader.java:25) 	at mindustry.io.MapIO.generatePreview(MapIO.java:101) 	at mindustry.maps.Maps.createNewPreview(Maps.java:410) 	at mindustry.maps.Maps.lambda$createAllPreviews$13$Maps(Maps.java:396) 	at mindustry.maps.-$$Lambda$Maps$xakoXGWzDtWrO2azb6OIoB-GRtM.run(Unknown Source:2) 	at arc.backend.android.AndroidGraphics.lambda$onDrawFrame$0$AndroidGraphics(AndroidGraphics.java:426) 	at arc.backend.android.-$$Lambda$AndroidGraphics$E5Jhq3pDs174QxCFAWFeVbXthOc.run(Unknown Source:2) 	at arc.backend.android.AndroidGraphics.runProtected(AndroidGraphics.java:479) 	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424) 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571) 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270) Caused by: java.io.IOException: Failed to read tile entity of block: steam-power-electric-conveyor 	at mindustry.io.SaveVersion.readMap(SaveVersion.java:197) 	at mindustry.io.MapIO.lambda$generatePreview$1(MapIO.java:101) 	at mindustry.io.-$$Lambda$MapIO$uI64QpIyM92bDQ60wrzrHG6QCfk.accept(Unknown Source:10) 	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72) 	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:66) 	at mindustry.io.SaveFileReader.region(SaveFileReader.java:23) 	... 10 more Caused by: java.io.EOFException 	at java.io.DataInputStream.readFully(DataInputStream.java:200) 	at java.io.DataInputStream.readInt(DataInputStream.java:389) 	at mindustry.world.blocks.distribution.Conveyor$ConveyorEntity.read(Conveyor.java:371) 	at mindustry.io.SaveVersion.lambda$readMap$3(SaveVersion.java:194) 	at mindustry.io.-$$Lambda$SaveVersion$rS-GIx1N670CbLVsyjXicgFQPU4.accept(Unknown Source:4) 	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:72) 	at mindustry.io.SaveVersion.readMap(SaveVersion.java:192) 	... 15 more```
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
Test result 1:The number of other mods does not affect it. No matter how many mods are there, 128 is the limit; however, less mods means less other content eating up the IDs so more of my mod's items mak it in.

**Comment by sk7725** [comment]
Test result 2:Desktop(Steam) 104.10 gets the same results.

**Comment by DeltaNedas** [comment]
127 is max signed char.
128 is -1 which means null, used for sorter filters and what not
for some reason randustry hasn't given me issues with IDs, only horrible lag with blocks.

**Comment by sk7725** [comment]
Update: the upper limit is indeed 127, not 128. I think I misread the logs...

**Comment by sk7725** [comment]
> 127 is max signed char.
> 128 is -1 which means null, used for sorter filters and what not
> for some reason randustry hasn't given me issues with IDs, only horrible lag with blocks.

No issues even when saving/loading the world(with the item in the world)?

**Comment by Anuken** [comment]
Due to some legacy code in the conveyor, all item IDs in that class are limited to 1 signed byte, 0-127. I can change that limit to 0-255, but it would only delay the problem.

> 1.Does normal mods with more than 127 items show this behavior? 

Yes, but I don't see this being a real problem, as no sane mod adds that many items.

> 2.Is there any recommended way to do what I did with my mod(I am aware of the events not clearing)? 

You haven't explained what exactly you're doing or why, so I can't answer that question.

> 3.Any way to prevent this behavior?

Don't create so many item objects.

**Comment by sk7725** [comment]
> Due to some legacy code in the conveyor, all item IDs in that class are limited to 1 signed byte, 0-127. I can change that limit to 0-255, but it would only delay the problem.
Will this change in 6.0?
> You haven't explained what exactly you're doing or why, so I can't answer that question.
Basically iterating over all loaded items and adding more items for each item, achieved via ContentReload and ClientLoad events. Also does the piximap magic to generate item icons.

**Comment by Anuken** [comment]
> Will this change in 6.0?

No.

> Basically iterating over all loaded items and adding more items for each item

The solution here would still be to create less items. Due to the way items are stored and handled, creating more than 127 is a *very* bad idea anyway.
