### ISSUE TITLE
I think this is a bug

### ISSUE THREAD

**Issue by Droideka-cis** [Anuken/Mindustry#2176]
**android**: *Android/iOS/Mac/Windows/Linux*

**104.6**: *The build number under the title in the main menu. Required.*

**me and a friend were making surge alloy and the core wasn't accepting them and was trowing them away**: *Explain your issue in detail.*

**we made a surge alloy smelter and after connecting the right ammount of items when we connected it to the core it was getting stuck at 13/14**: *How you happened across the issue, and what you were doing at the time.*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
you managed to use the opposite of the template... fascinating.

**Comment by DeltaNedas** [comment]
the core is full thats not a bug

**Comment by Quezler** [comment]
sounds like you need to `/sync`
