### ISSUE TITLE
All mod scripts share the same scope

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2178]
**Platform**: Android

**Build**: 104.10

**Issue**: All mods share the same scope.

**Steps to reproduce**:
In two mods:
```js
const x = 5;
print(x);
```
Then wrap them in `(() => {...})()` and the redeclaration error goes away.
Mods should not share their scope, instead this.global should be used for globals, or a variable with no modifier like `myglobal = 'h'`.

**Link to mod(s) used**: skeleton mods with the first code block as scripts/main.js
- 

**Error line**: `[E] [mod2/main.js]: EcmaError: TypeError: TypeError: redeclaration of const x.`
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
linking the way nydus does it for reference: https://github.com/Quezler/mindustry__nydus--script-pool/blob/master/README.md (contributed from within the community, not written by me*)
