### ISSUE TITLE
achievement problem when went from Android to Steam version

### ISSUE THREAD

**Issue by L404-Venik** [Anuken/Mindustry#2180]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android, windows
**Build**: *The build number under the title in the main menu. Required.*
104.10
**Issue**: *Explain your issue in detail.*
I played Mindustry on Android. Then I transferred this save to the Steam version of the game. It worked perfectly but I can't get achievements "Material I" and "Material II" because i unlocked titanium and thorium on phone. Didn't find solution in the net.
![achievements](https://user-images.githubusercontent.com/67225529/85223247-3f00bc80-b3ca-11ea-8e05-66dce604fdc2.png)
![main screen](https://user-images.githubusercontent.com/67225529/85223248-4031e980-b3ca-11ea-9a79-5b66255e42fb.png)
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Didn't try anything. I know that I can clear game data and start new game to achieve ores second time but if there are other way?
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*
Didn't use any mods.
**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
achievements dont transfer, not a bug

**Comment by Anuken** [comment]
This isn't a bug. You have to actually perform the action to get the achievement; otherwise people could just easily import other people's complete saves and get all the achievements.
