### ISSUE TITLE
Diagonal placement of conveyors is not working as expected

### ISSUE THREAD

**Issue by nikmartin** [Anuken/Mindustry#2182]
**Platform**: Linux

**Build**: running git tag v104.1 using command `./gradlew desktop:run`
**Issue**: 
When trying to place a conveyor diagonally using left CTRL, the 'granularity' is very low. In other videos of mindustry, diagonals look very precise, when I try to place conveyor, the 'steps' are very large. It gets even worse when trying to navigate around obstacles while placing a conveyor.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
select a conveyor, hold L+CTRL, and try to place the conveyor

I have attached a video to demonstrate.

---

[diag-2020-06-22_10.03.00.mp4.zip](https://github.com/Anuken/Mindustry/files/4814123/diag-2020-06-22_10.03.00.mp4.zip)

 ---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
its intended for it not to bend a lot iirc

**Comment by DeltaNedas** [comment]
thats intended, its to make getting from point A to B easy and clean

**Comment by Anuken** [comment]
That's not "diagonal placement", it's pathfinding. Actual diagonal pathfinding makes a horrible mess with conveyors.
