### ISSUE TITLE
Changing The Map Editor Map Size... Majorly...

### ISSUE THREAD

**Issue by natsudragneelthefiredragon** [Anuken/Mindustry#2184]
**Platform**: *Windows*

**Build**: *Release Build 104.10.*

**Issue**: *Umm... I realize this may be an almost unavoidable way to change how the game works but while lying around I thought man what if Mindustry maps were bigger? Then I remembered I had Cheat Engine (Pretty sure you know what it is) Well anyway I went and changed the map size value to 99999999 something then the game crashed (Expected) Then I tried again with only 700, viola! It actually worked (Well at least with the edit in game feature, haven't tried anything else yet) it lagged for a second but it worked and functions perfectly, however when changing the value it goes back to 500 and stays until changed again with Cheat Engine. Just thought this was interesting is all, I don't know how to report it as a bug or a suggestion... This allows for bigger maps.*

**Steps to reproduce**: *Open Mindustry, Open Cheat Engine, select Mindustry from the processes button in Cheat Engine, Then make sure you have the map editor open in Mindustry with the Resize option visible, then on Cheat Engine enter 200 (Or whatever value a size is) then press first scan, it will show around 1000 something results, then in Mindustry change the size value by selecting a different number then go back to Cheat Engine and type the new value in and press Next Scan, this should narrow down the results, do as many times as necessary (I only needed one Next Scan) then double click the one value you see and in the section below it will appear, there simply change the number to whatever (Make sure you keep both programs open of course don't close them out).*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
Not a bug. The way Mindustry handles data will not support bigger maps. The bigger the map, the bigger the lag.

**Comment by Anuken** [comment]
> Then I tried again with only 700, viola! It actually worked

Sure, changing the map size to something above 500 won't instantly make it explode, but it's still not allowed for performance reasons.

> I don't know how to report it as a bug or a suggestion

I'm not sure how you could *not* now this, as the "new issue" button explicitly tells you how to do this if you just read the page that shows up after you lick it.
