### ISSUE TITLE
inconsistant zooming keybind

### ISSUE THREAD

**Issue by InfernoSuperNova** [Anuken/Mindustry#2198]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows/steam
**Build**: *The build number under the title in the main menu. Required.*
104.10
**Issue**: *Explain your issue in detail.*
scrolling to zoom and scrolling to rotate are unintuitive, causing confusion
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
if nothing is selected: scrolling normally zooms in and out
if schematic/rotateable block selected: scrolling rotates the schematic/block, and ctrl+scrolling zooms in and out
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Confusion is not a bug.
