### ISSUE TITLE
Windows version sometimes cannot attack

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry#2199]
**Platform**: *Windows*

**Build**: *v104.6*

**Issue**: *Sometimes I just press mouse left and my mech just do not attack.When I quit to menu and connect the server again,I can attack again.This is a bit annoying.*

**Steps to reproduce**: *I think it happens by chance,usually happen when I’m back from toilet.*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X
![B61012BA-F972-42B9-AD95-C35F7B1C6612](https://user-images.githubusercontent.com/62016462/86098014-1ecaaf00-bae8-11ea-9c44-da3213db3362.png)
 ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
press E

**Comment by Anuken** [comment]
You can't shoot with a building queue.
