### ISSUE TITLE
Conduits are not affected by the overdrive projector

### ISSUE THREAD

**Issue by a-j-smith** [Anuken/Mindustry#2202]
Pulse conduits can feed 11 impact reactors when not overdriven but when the entire setup is overdriven the last reactor does not have enough cryofluid consistently.

**Comment by Anuken** [comment]
Conduits aren't supposed to be overdriven.

**Comment by 348joey** [comment]
> Conduits aren't supposed to be overdriven.

The highlight they get along with all the other buildings when showing the Overdrive's range led me to believe otherwise, but okay. Glad I searched for this one.
