### ISSUE TITLE
My mods won't work

### ISSUE THREAD

**Issue by itzagoose** [Anuken/Mindustry#2203]
Platform android phone samsung galaxy a50

Build 104.10

Issue when I try to use a mod they first show it then when I reload the are gone then when I use the github version it works but when I do it with my files it doesn't work I did it on some older versions before and it worked

Steps to reproduce I was trying to active mods

Link to mod(s) used there is like 16 and I tested with different to

Crash report, if applicable (mod with the same file does aready exist)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
Use the correct template. 

> mod with the same file already exists!
This means that you have two mod files that have the same `name` in their `mod.json`. Either remove one of them.

You cannot put mods with the same name in the `mods` directory at once.
