### ISSUE TITLE
Some kind of power source bug

### ISSUE THREAD

**Issue by Lenuto** [Anuken/Mindustry#2204]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *I was just playing on kampane mode and suddently all of the "wire" from the power points just disappear ( i apologise if i used the wrong names from the buildings. I looked if they have power and yes all worked but the wire had disapeared, also all next wires i placed / connected. I reloaded my game and the issue was no longer there.
![screenshot-1593761123951](https://user-images.githubusercontent.com/67779163/86444121-94b15f00-bd10-11ea-880d-e7e604824815.png) this image could help*

**Steps to reproduce**: *I have no clue what happend, it just happen, maybe while i was building something i´m not sure*

**Link to mod(s) used, if applicable**: *no mods used*

**Crash report, if applicable**: *No crash report, Sorry*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Lenuto** [comment]
Sorry i think the save is also corrupted i tried to restart the game and reload the map the issue is still there 


[-1.zip](https://github.com/Anuken/Mindustry/files/4868410/-1.zip)
Here is the save file

**Comment by Lenuto** [comment]
another addition i finished the game and started a new one, i started on the same map again because i needed some resources, anyway. I placed some energy generator and connected them to my system the wire wasn´t there. from the beginning of the game to the end i didn´t saw any wire. I hope it´s the version and not my game which is corrupted xD.

**Comment by Gdeft** [comment]
Try to check the power laser opacity in Settings > Graphics. It seems that your power laser opacity is 0%.

**Comment by Anuken** [comment]
Not a bug, enable power nodes in your settings. You probably pressed the hotkey by accident.

**Comment by Lenuto** [comment]
xD sry
