### ISSUE TITLE
Phantom Builders will sometimes build up enemy base 

### ISSUE THREAD

**Issue by goaran** [Anuken/Mindustry#2205]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux (Debian)

**Build**: *The build number under the title in the main menu. Required.*
104.10

**Issue**: *Explain your issue in detail.*
When playing in Hexed-PvP and you have Phantom-Builder​-Drones sometimes they start to build up an enemy base that got destroyed earlier in the game. 

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Play Hexed PVP and have Phantom Builder drones. It is not always the case that they will build up other bases, but something like a 50% chance. 

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug in Mindustry. The other base was *on your team* (since teams are reused), so its blocks are marked to be rebuilt.

**Comment by goaran** [comment]
On Hexed-PvP everyone fights everyone, so what is the meaning of the "team"-category there?

The problem is, that it kind of makes the Phantoms useless since they will spend all the time wasting resources on building up random bases? What would be the soultion to still be able to use them?

E.g. when another player joins and then leaves again his base explodes. Now my drones go where he left and try to build up the base and i cannot do anything about it except for filling the whole space where the base was with conveyors or something so the drones get blocked from building?

**Comment by Anuken** [comment]
> So what is the meaning of the "team"-category there?

The same meaning as teams do in normal games. Each different person is on a team.

> What would be the soultion to still be able to use them?

The plugin could manually clear the broken blocks between team landings to make the phantom drones ignore them. However, I'm not working on Hexed right now, and the plugin would need a rewrite to be compatible with 6.0 anyway.

**Comment by goaran** [comment]
Ok, now I get it. Thanks for the quick answer. 
What also would be great (and solve the problem as well): If the PhantomDrones build plans could be cleared manually somehow, since when e.g. some area gets lost to the enemy they will try to rebuild there and probably die and you can only stop them by destroying them.

**Comment by DeltaNedas** [comment]
drones should give up if they failed to rebuild a block, maybe even clear the plan in an area to save more time
