### ISSUE TITLE
spirit repair drones sometimes ignore damaged building

### ISSUE THREAD

**Issue by JuicyJuuce** [Anuken/Mindustry#2206]
**Platform**:
Windows

**Build**:
steam build 104.10

**Issue**: 
During a wave of enemies, my spirit repair drones were repairing stuff on the front lines. After the wave was defeated, this one wall block remained unrepaired and the repair drones sat idle at their spawn point. This has happened a few times with different blocks.
But a video is worth a thousand words:
https://gfycat.com/defenselessmassiveindianelephant

**Steps to reproduce**:
nothing out of the ordinary. that block and others near it are normally repaired no problem.

**Link to mod(s) used, if applicable**:
no mods

**Crash report, if applicable**:
no crash

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce this problem and the spirit AI no longer exists in 6.0.

**Comment by JuicyJuuce** [comment]
@Anuken I mean, I provided video evidence that the bug is indeed occurring. Since you've said 6.0 might be a year away, maybe it would be useful to keep the issue open so that people can collaborate on narrowing down when and why it occurs?

**Comment by Anuken** [comment]
How would that be of any help when 5.0 won't be getting any more updates and 6.0 doesn't have any of the relevant code still around?

**Comment by JuicyJuuce** [comment]
5.0 won't be getting any updates until 6.0 is released? I didn't realize that. Seems strange to not do bug fixes for up to a year but 🤷‍♂️

**Comment by itcannotbe** [comment]
v5 b104.6/10 won't be getting updates because the next update is v6.

**Comment by JuicyJuuce** [comment]
@itcannotbe the [announcement](https://steamcommunity.com/games/1127400/announcements/detail/2209520752605604724) from a few days ago says:
> There is no deadline set for release - with the amount of features to be added, final release of 6.0 may take up to a year.

Should Steam users not expect 6.0 for a year? Or did I misinterpret that statement?
