### ISSUE TITLE
Error when connecting to attack LAN server

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry#2207]
**Platform**: *Android/iOS/Mac/Windows/Linux* Android

**Build**: *The build number under the title in the main menu. Required.* BE build 8871

**Issue**: *Explain your issue in detail.*
Error "Unknown network error (Attempt to invoke virtual method 'float mindustry.gen.Building.healthf()' on a null object reference)" when connecting to an attack LAN server 

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
1) Play an attack map
2) Open to LAN
3) Join server on another device

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.* none

**Crash report, if applicable**: *The contents of relevant crash report files.*
I don't know how to copy the error when you press "Details..." but I do have these screenshots
 https://cdn.discordapp.com/attachments/627841590869753886/728730556430286918/Screenshot_20200703-225324_Mindustry_BE.png 

https://cdn.discordapp.com/attachments/627841590869753886/728730554572472340/Screenshot_20200703-225328_Mindustry_BE.png

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't play 6.0.

**Comment by ILiekMelons** [comment]
😔
