### ISSUE TITLE
Mindustry keeps crashing

### ISSUE THREAD

**Issue by zeronineseven** [Anuken/Mindustry#2216]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *104.10*

**Issue**: *Mindustry loads up to 64% then crashes I have reinstalled it multiple times and it still doesn't work*

**Steps to reproduce**: *I was loading in a mod that i made to test it*

**Link to mod(s) used, if applicable**: *

The mod repositories or zip files that are related to the issue.*[tester zip.zip](https://github.com/Anuken/Mindustry/files/4893961/tester.zip.zip)*

**Crash report, if applicable**: *There is a crash report  but there is nothing in it *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
If the crash is caused by your mod, then figure out what's wrong with it and fix it, or just don't use the mod. I definitely can't help you without a crash report.

**Comment by Gdeft** [comment]
Your mod is just a "failed copy" of AdvanceContent. You didn't declare the content type, that's why it crashed.
