### ISSUE TITLE
Force projector ignores player damage multiplier

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2220]
**Platform**: Android

**Build**: 104.10 and *maybe* latest master

**Issue**: When the player damage multiplier rule is set to 0, force projectors are still damaged by players.
From a glance at the 6.0 damage consumer function, it doesn't touch playerDamageMultiplier though I may be wrong.

**Steps to reproduce**:
1. Disable player damage
2. Attack an enemy shield with a trident
3. It works

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Player damage multipliers don't even exist in 6.0.
