### ISSUE TITLE
Mindustry crashes without opening

### ISSUE THREAD

**Issue by Pyrotex2** [Anuken/Mindustry#2228]
**Platform**: Mac

**Build**: 104

**Issue**: Whenever I open mindustry it loads up to 80% and then closes. It started when I had downloaded some mods but it's still there even after deleting all mods and redownloading the game

**Steps to reproduce**: I just opened the game

**Link to mod(s) used, if applicable**: No mods

**Crash report, if applicable**: I can't find any crash report

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I can't find any crash report

Then I can't help you.
