### ISSUE TITLE
Translation: Persian/Arabic charachters are not visible

### ISSUE THREAD

**Issue by HKalbasi** [Anuken/Mindustry#2248]
**Platform**: Linux

**Build**: 104

**Issue**: When I tried to translate game to Persian, I found that Persian characters like سلام are not visible in the game.

**Steps to reproduce**: 
* Change "back" to "بازگشت" in bundle.properties
* Open the game
* See there is nothing in the back button 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
These characters are not supported by the font, and are completely unsupported by the font system as a whole. An Arabic/Persian translation isn't possible.

**Comment by HKalbasi** [comment]
What is problem with this languages? Is it for right-to-left or for joined characters? How many languages are affected? How I can help to solve problem?

**Comment by Anuken** [comment]
The issue is related to right-to-left characters *and* ligatures. Ever RTL language is affected, as far as I know, and unless you want to write your own font renderer and layout system, you can't help.
