### ISSUE TITLE
Sorter deaful selection dose not sync in multiplayer

### ISSUE THREAD

**Issue by kfreimanis** [Anuken/Mindustry#2252]
**Platform**: *Windows*

**Build**: 104.10

**Issue**: Sorter deaful selection dose not sync in multiplayer

**Steps to reproduce**: Start multiplayer game place a sorter select any resource, place another sorter (last selected resource wil be selected on second sorter), other player sees this sorter as empty.

**Comment by Anuken** [comment]
I can't reproduce this issue, it doesn't happen to any other player and it's not relevant in v6 as the configuration system has changed.
