### ISSUE TITLE
Tetrative Reconstructor doesnt support Overdrivers

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry#2256]
Platform: Android

Build: any build of bleeding-edge

Issue: Tetrative reconstructor stops working if you use Overdrive Projector or Large Overdrive Projector.

Steps to reproduce: Construct something in tetrative reconstructor, get it to work. Use a combination of overdrivers and it stops working.

I think this is because liquid capacity isnt enough for required liquids per second when you boost it because it will want more than it shows. Even if you cover the entire block with liquid sources, it won't work. Either the liquid capacity should be increased or it should require less liquid per sec

Try:

Overdrive Projector
Overdrive Projector + Boost
Large Overdrive Projector
Large Overdrive Projector + Boost

After you think you fixed the issue and if everything works correctly with all these combinations then the issue is fixed. By the way I also suggest that you also try with exponential reconstructor because its requirements are close to tetrative reconstructor.

---

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Yoroppa** [comment]
Don't report 6.0 bugs >.>

**Comment by Zenith-LY** [comment]
> Don't report 6.0 bugs >.>

what about pull request?

**Comment by Yoroppa** [comment]
Not sure, Anuke will probably get round to doing it.

**Comment by BlueWolfGaming** [comment]
this was fixed, and the reason was something something liquid/tick req mwas more than capacity
