### ISSUE TITLE
Bridges can't send items back the way they came from.

### ISSUE THREAD

**Issue by Cyberman-42** [Anuken/Mindustry#2258]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *Bridges and phase conveyors (don't know about liquids) cant send items in the opposite directions that they entered from.*

**Steps to reproduce**: *Make a conveyor go left and lead it into a bridge from the bottom (with a corner), now let the bridge connect with another bridge under it (so it goes over the conveyor that leads items into it. You can now see that the items are not flowing through. I came across this while creating a complex system for my impact reactors. This also works with phase conveyors, although I haven't checked liquids.*

**Link to mod(s) used, if applicable**: *No mods used.*

**Crash report, if applicable**: *No crash report.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
Sorry I havent, I wrote this in a hurry.

**Comment by Anuken** [comment]
This is intentional. If bridges accepted items from the back, you would have a mess.

**Comment by MEEPofFaith** [comment]
The best way to stop morons is to just casually drop a router style warning in descriptions,
