### ISSUE TITLE
Cant be played on Windows without hardware keyboard

### ISSUE THREAD

**Issue by rozza-m** [Anuken/Mindustry#2259]
**Platform**: Windows

**Build**: 104.10

**Issue**: Touchscreen support missing for windows

**Steps to reproduce**: Use a windows device without a hardware keyboard (surface, or other windows tablet)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Windows spans a great number of devices, including those without hardware keyboards and, in the past few years, many many 2-in-1s where the keyboards are stowable, supporting use in a variety of scenarios and positions that are not on a desk or lap. Mindustry has great touchscreen controls on iOS and Android. The very beginning of Mindustry tutorial on Windows says to use WASD to move, immediately making it impossible without a hardware keyboard available. I kindly request that Windows is considered a platform where touch is supported as a primary / only input too, and provide a means to use Mindustry's awesome touch controls. One method would be a switch in settings and a button at the beginning if the tutorial. Another (not as elegant) would be through editing a config file.

Mindustry is awesome, I've completed the campaign on Android, please allow me to play it on Windows 😊

**Comment by Anuken** [comment]
The reason Mindustry doesn't have touch controls for desktop is that:
- I don't have any desktop touch devices to test on
- The desktop backend doesn't support handling things like multi-touch or gestures

Unless someone submits a pull request, it is very unlikely that touch support will be added.

Note that the issue tracker is for bugs, not feature requests.

**Comment by rozza-m** [comment]
@Anuken thanks for your fast response.

I'm not sure I'd touch control a "feature" as Windows 8 onwards have supported touch as the sole input for the OS. Is it really a "feature" to support a class of devices that the OS already supports? Is there a clear user expectation that support of these devices should not be assumed?

On launching Mindustry on such a device, they're dropped into an inoperable tutorial that just feels broken - particularly as on other platforms Mindustry works awesomely with touch which may well lead people to try it on Windows.

I'm aware that I probably sound stubborn and difficult for pushing with this. Sorry. Thank you so much for Mindustry. I **do not** feel that you owe me anything and if you don't have the time, resources or inclination to support touch then, although I think it's huge shame and potentially a missed opportunity, it's your call - but it would be better for all users to make that clear from the outset. Hence I've raised #2266 to cover the (possibly? probably?) unexpected and seemingly broken condition where touch isn't supported on Windows.

**Comment by rozza-m** [comment]
(some discussion continues over at https://github.com/Anuken/Mindustry/issues/2266#issuecomment-663907234)
