### ISSUE TITLE
Mindustry does not fail gracefully on Windows devices when a hardware keyboard is inaccessible

### ISSUE THREAD

**Issue by rozza-m** [Anuken/Mindustry#2266]
**Platform**: Windows

**Build**: 104.10

**THIS ISSUE IS NOT REQUESTING TOUCHSCREEN SUPPORT**

**Issue**: Windows supports many devices where hardware keyboards are stowable or not present. Issue #2259 makes clear that, on Windows, touch controls are not supported. When trying to launch Mindustry on such a device, the following is experienced:

- No information that touch controls are not available on windows before download/install
- Program can be downloaded and launched from native, touch-supporting interface with touch only
- The first instruction is a touchscreen friendly instruction ("Tap to continue", NOT "click to continue")
- The second instruction is impossible ("Use WASD to move") leaving no option but to quit and no information to the user.

As windows 8 and 10 are OSs where touch is supported as the only input, the above condition feels broken.

Suggested solutions:
- Change "Tap to continue" to "Click to continue" on desktop platforms, and
- Add a line to the second tutorial box saying "touch controls aren't supported on desktop platforms", and
- Make the same clear in documentation.
At least then the user doesn't think they've done something wrong, or need to configure a setting, or that they have downloaded the wrong version.

**Comment by ILiekMelons** [comment]
this has already been complained about

**Comment by rozza-m** [comment]
Again, I'm sorry for probably seeming difficult, pushy and probably ungrateful for seeming to take the attitude that Mindustry as it is is somehow not good enough, when it's an incredible piece of work that's distributed for free. I feel that the experience offered on a Windows touch-first device is broken.

I'm not much of a coder, but I'll start trying to understand  how I can submit a pull request to make the changes I've suggested.

**Comment by rozza-m** [comment]
Looks like point 2 is resolved by changing line 1086 in bundle.properties

**Comment by Anuken** [comment]
> The second instruction is impossible ("Use WASD to move") leaving no option but to quit and no information to the user.

> Add a line to the second tutorial box saying "touch controls aren't supported on desktop platforms"

I think saying "WASD to move" makes it clear that a hardware keyboard is needed to play the game, and that touch is not supported. Adding an extra line to address touch seems redundant and wastes valuable space.

> The first instruction is a touchscreen friendly instruction ("Tap to continue", NOT "click to continue")

This is true, but the tutorial will be implemented with different dialogs/text in v6, so this text (or any text in the tutorial right now) won't be around at all.

> Make the same clear in documentation.

I'm not sure why this is necessary. There is no option for touchscreen controls in Mindustry, and there is no indication (aside from the "tap" wording) that touch support is supposed to be functional anywhere.

From your previous comment:

> Is it really a "feature" to support a class of devices that the OS already supports?

Yes, it is. There is no requirement for me to support every variant of Windows/Mac/Linux/Android device out there. Touch support is not a reasonable expectation for games; of all the ones I've played, I only Minecraft mentioned anything related to touch input.

**Comment by rozza-m** [comment]
> I think saying "WASD to move" makes it clear that a hardware keyboard is needed to play the game, and that touch is not supported. Adding an extra line to address touch seems redundant and wastes valuable space.

I disagree - my personal experience was to try to find a way to fudge through the tutorial by getting the onscreen keyboard up, enough that I could get to the main menu and go through the options to see if there was a box to get touch controls. Then I looked back at the website - there's a couple of Windows versions and I thought maybe I downloaded the wrong one. Some indication that touch controls aren't supported would have helped me.

>Touch support is not a reasonable expectation for games; of all the ones I've played, only Minecraft mentioned anything related to touch input.

Fair point - for most games. Although Civ 6 can be played only on a touchscreen apparently.
When your app has 1,000,000 downloads on Android, though, most people who discover it probably discover the touch version...and a fair proportion of other platform users are probably people who first discovered it on Android and first experienced the touch controls.
It also feels wrong from an accessibility point of view to effectively limit what input methods are supported on which hardware - and to leave it to people downloading, installing, launching and having to land at an impossible command to surmise that it was never designed to work this way.

>There is no requirement for me to support every variant of Windows/Mac/Linux/Android device out there.
Totally agree. There's no requirement that you create any of this at all - thank you for all your hard work.

It's clear how you feel about this and that's your prerogative. I don't think I will change your mind, touchscreen users will have to look for other games instead. Thanks for your fast and considered feedback. I'll not take up any more of your time with this - I'll leave it for you to close.

**Comment by stuffyAI** [comment]
If you are insistend on touch you can use android studio to emulate an android phone and play it there, you even get the same experience with lag.

As Anuken hinted this game was not designed for touch, it's just an extra that it works on some mobile devices, and that his game is so popular doesn't mean he has to expand it to all.

**Comment by Anuken** [comment]
> It also feels wrong from an accessibility point of view to effectively limit what input methods are supported on which hardware

It would be *nice* for touch input to be a feature, but as I've said before, I don't have the means to implement it.
