### ISSUE TITLE
Enemys spawn where they are not supposed to

### ISSUE THREAD

**Issue by MrWunz** [Anuken/Mindustry#2267]
Platform: Android

**Build**: 104.6

**Issue**: 
Enemys started spawning somewhere where they are not supposed to. It started after wave 70 and some still spawn normal but 70% spawn outside.
![20200726_110459](https://user-images.githubusercontent.com/48923653/88475574-8df1c280-cf31-11ea-90b4-5e7c7a67962a.jpg)

![Screenshot_20200726-112156_Mindustry](https://user-images.githubusercontent.com/48923653/88475652-47e92e80-cf32-11ea-9d0e-1494dd9be39b.jpg)
 The spawning range is set to 2.5 

Sorry for my bad english
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Flying units do not spawn in the same place as ground units. This is not a bug.

**Comment by Neba-MD** [comment]
This might help you understand about air spawn.
https://discordapp.com/channels/391020510269669376/422855426242248725/699616534682927174
