### ISSUE TITLE
UI bug on resize browser window

### ISSUE THREAD

**Issue by alzurken** [Anuken/Mindustry#227]
On resizing browser window to certain size in-game menu disappears. I've tested this in Chrome only.
![bug_report](https://user-images.githubusercontent.com/3081615/46015034-e2c81600-c0d9-11e8-8aa6-b4dcafd94370.PNG)

**Comment by Anuken** [comment]
itch.io automatically cuts off the game canvas once it gets small enough. When testing with a local file without an iframe, this does not happen (e.g. the game canvas gets scaled down).
I've tested other web games on itch, and it seems nearly all of them have the same problem. 

All I can say is _don't resize your window._
