### ISSUE TITLE
Unloader rebuilt by Phantom loses material settings

### ISSUE THREAD

**Issue by mostevil** [Anuken/Mindustry#2270]
**Platform**: Windows

**Build**: 104.10

**Issue**: After unloaders are destroyed, phantoms come to rebuild them.  
If it's destroyed again while being rebuild *edit*
The rebuilt unloader doesn't have the unload setting of the original, reverting to copper.

**Steps to reproduce**: 
Have some phantom drones on the field.
Build a  container with an unloader somewhere in front where it will get killed by an attack.  
Set it to unload something interesting.  
 -  I had mine setup to feed Plastanium into cyclone turrets.
Wait until it's destroyed and rebuilt.  
It's forgotten what it's supposed to unload.

**Link to mod(s) used, if applicable**: none
**Crash report, if applicable**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by mostevil** [comment]
It's slightly more complicated than I first thought.
It's if they're destroyed again while they're partially rebuilt.  (I'm seeing it around wave 1500 on thorium, so the waves are pretty big)
![image](https://user-images.githubusercontent.com/7564895/88513736-c00e2d80-cfe0-11ea-9c10-09998a8805cd.png)
![image](https://user-images.githubusercontent.com/7564895/88513742-c6040e80-cfe0-11ea-8388-b6b602426e6e.png)

**Comment by Anuken** [comment]
Not relevant in v6 - phantoms and building AI don't exist.
