### ISSUE TITLE
Blocks like sorters and router take too long when used with plastanium conveyors

### ISSUE THREAD

**Issue by BaseModMaker** [Anuken/Mindustry#2272]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required.*
Its a custom build of the latest code
**Issue**: *Explain your issue in detail.*
When distribution blocks like sorters, overflowgates, junctions, etc. are used with a plastanium conveyor they reduce it's output speed significantly. A plastanium conveyor maxes out at 2 loading zones that take input from an item source. When a sorter is placed on the conveyor, the efficiency is reduced by 2. These block don't impact the speed of any other maxed out conveyor so this shouldn't happen with the plastanium one either. Item bridges are unfortunally completly broken with these conveyors.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Max out a plastanium conveyor (an item source with 2 plastanium conveyor loading bays next to it lead into the same conveyor) and place a sorter.
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> These block don't impact the speed of any other maxed out conveyor so this shouldn't happen with the plastanium one either

That's incorrect. The point of plastanium conveyors is to have high throughput when used in a continuous line.
