### ISSUE TITLE
Scene related exceptions don't create a crash log

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2279]
**Platform**: GNU/Linux, Android 9

**Build**: 104.10 firsthand, maybe master (#2278)

**Issue**: When Mindustry crashes in a UI related function like a button click callback, the stack trace is only shown in stdout, not a crash log.

**Steps to reproduce**: See #2278 

**Crash report, if applicable**: That's the issue

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in Arc.
