### ISSUE TITLE
infinite tech tree global items bug

### ISSUE THREAD

**Issue by RanPix** [Anuken/Mindustry#2282]
**Platform**: Windows 10

**Build**: BE 9101

**Issue**: global items come back when im re-enter in tech tree 

**Steps to reproduce**: entering on any sector and click on a tech tree then click on any available block then re-enter in tech tree  and global items come back . https://youtu.be/rm28VhSS5BA

**Link to mod(s) used, if applicable**: none

**Crash report, if applicable**: *no crashes that's a bug*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ILiekMelons** [comment]
what do you mean "global items"

**Comment by RanPix** [comment]
> what do you mean "global items"

![image](https://user-images.githubusercontent.com/68966087/88836468-6889e080-d1df-11ea-92f4-85fbd37ad1f6.png)
