### ISSUE TITLE
Factories do not forget lacking resources for a previously selected unit for building when switching over to a new unit to be built

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry#2289]
**Platform**: *Linux*

**Build**: *PA 9136*

**Issue**: *See title*

**Steps to reproduce**: *Select a new plan from the factory and see the list of missing requirments get longer.*

**Link to mod(s) used, if applicable**: *None*

**Crash report, if applicable**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
