### ISSUE TITLE
yet another plastanium conveyor bug thing

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry#2291]
**Platform**: *Android/iOS/Mac/Windows/Linux* Android

**Build**: *The build number under the title in the main menu. Required.* BE 9143

**Issue**: *Explain your issue in detail.*

Plastanium conveyors incorrectly connect to armored conveyors.
![Screenshot_20200801-015554_Mindustry BE.jpg](https://user-images.githubusercontent.com/49169907/89090353-57d19a00-d39a-11ea-9f72-fb32483e4fd6.jpg)

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

see above

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

no

**Crash report, if applicable**: *The contents of relevant crash report files.*

no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There's no clean way to fix this. I'm not going to bother.
