### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Hf1b** [Anuken/Mindustry#2292]
**Platform**: *Android*

**Build**: *Bleeding Edge 9146.*

**Issue**: *Some tiles has line on the side.*

**Steps to reproduce**: *Just open the first map in campaign.*

**Link to mod(s) used, if applicable**: *None.*

**Crash report, if applicable**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_20200801-105408_Mindustry BE](https://user-images.githubusercontent.com/62131780/89095367-a016a980-d3e6-11ea-93c2-4042b3c3e04e.jpg)

**Comment by itcannotbe** [comment]
Disable linear filtering.

Settings -> Graphics

**Comment by Hf1b** [comment]
Thanks a lot.
