### ISSUE TITLE
WIth pixelated graphics, number of manually mined / held items is unreadable

### ISSUE THREAD

**Issue by nihillum** [Anuken/Mindustry#2294]
**Platforms**: 
- Android (8.1.0)
- Linux (Ubuntu 20.04)

(these are the only platforms I could test)

**Build**: 
- Android: 104.6
- Linux: 104.6 (snap)

**Issue**: After activating the pixelated graphics option, the number of manually mined items is unreadable.
![screenshot](https://user-images.githubusercontent.com/55314691/89104088-f26fbe80-d416-11ea-9b73-a09d469f86dc.png)

**Steps to reproduce**: 
1. Go to Settings->Graphics
2. Activate "Pixelate" option
3. Manually mine anything or take items from a block
4. Number of items held is unreadable

**Link to mod(s) used, if applicable**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
1. install https://github.com/BasedUser/MindustryClassicified
(texture pack rather than pixelator, preserves text and such)
2. don't use snap

**Comment by nihillum** [comment]
Ok thank you for your answer. 
Why shouldn't I use snap? Is it because it has an older version?
