### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Yoroppa** [Anuken/Mindustry#2297]
**Platform**: *Android*

**Build**: *bleeding edge 9162*

**Issue**: *When items are taken out of a router, The amount of items in the router are displayed as '0'*

**Steps to reproduce**: *I was messing around with the routers surrounding junction storage thing, And I noticed the router kept going from 1 resource to 0 Resource when outputting, I don't think this is meant to happen*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Yoroppa** [comment]
![Screenshot_20200802_105508_io anuke mindustry be](https://user-images.githubusercontent.com/68686349/89120627-b3da1280-d4af-11ea-900e-1fdc0a3be753.jpg) Picture for reference

**Comment by ritzip** [comment]
This is intended
