### ISSUE TITLE
Factory unit's bug

### ISSUE THREAD

**Issue by grimsoul10** [Anuken/Mindustry#2298]
**Platform**: *Android*

**Build**: *Bleeding Edge 9162.*

**Issue**: *when you change all unit factory to be a new unit factory (I change air unit factory to ground unit factory) the power automatically connect to a new factory, but the factory can't produce any unit .*

**Steps to reproduce**: *just change ground,air unit factory with new one or load schematic with infinite power node, u can repair it with re connect factory to power node, actually I try just with one map.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul7** [comment]
![Screenshot_2020-08-02-18-36-49-797_io anuke mindustry be](https://user-images.githubusercontent.com/57223926/89122438-4cdd4d80-d4f1-11ea-8b5e-e7f876cb41de.jpg)
![Screenshot_2020-08-02-18-36-39-128_io anuke mindustry be](https://user-images.githubusercontent.com/57223926/89122439-523a9800-d4f1-11ea-8bbf-5ffa3acd66c3.jpg)


That's for proof

**Comment by Anuken** [comment]
In the screenshot, you're not providing the correct resources to the factory, so it definitely wouldn't work. You also haven't specified whether the unit cap is reached.

**Comment by grimsoul10** [comment]
No, I was change the item before I place it... So, it should be work... But, Yes u not see that so no problem
