### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#23]
![image](https://user-images.githubusercontent.com/30189017/34160848-9097cf16-e49c-11e7-8633-0df17c3d1be5.png)
I tried running the latest build of Mindustry but this happened..

**Comment by Anuken** [comment]
This looks like Gradle or the Java compiler being stupid. I'll see if I can "fix" it soon.

**Comment by Anuken** [comment]
Should be fixed now.
