### ISSUE TITLE
perhaps

### ISSUE THREAD

**Issue by ILiekMelons** [Anuken/Mindustry#2300]
**Platform**: *Android/iOS/Mac/Windows/Linux* Android 10

**Build**: *The build number under the title in the main menu. Required.* BE 9162

**Issue**: *Explain your issue in detail.*
Conveyors don't connect to plast conveyors as they should. 

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Place a single plastanium conveyor and a non-armoured conveyor beside it and note how it doesn't connect, as it should.
![Screenshot_20200802-145849_Mindustry BE.jpg](https://user-images.githubusercontent.com/49169907/89124704-e21c1a00-d4d0-11ea-8d4e-3141c2a2a5a4.jpg)

Add plastanium conveyors and see how the conveyors don't connect.
![Screenshot_20200802-145903_Mindustry BE.jpg](https://user-images.githubusercontent.com/49169907/89124737-3626fe80-d4d1-11ea-9a3e-8591ef89d63f.jpg)

(Should I not make bug reports like this?)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Zenith-LY** [comment]
this say reported before and anuke said he cant fix it

**Comment by itcannotbe** [comment]
Related Issue: #2291

**Comment by itcannotbe** [comment]
It's not actually broken. See image.
![Screenshot_20200802_223429](https://user-images.githubusercontent.com/45280919/89125362-7194ed80-d510-11ea-8817-90d96ed72eaa.jpg)

**Comment by ILiekMelons** [comment]
> this was reported before and anuke said he cant fix it

no, that was a different issue with armored conveyors.

**Comment by ILiekMelons** [comment]
> It's not actually broken. See image.
> ![Screenshot_20200802_223429](https://user-images.githubusercontent.com/45280919/89125362-7194ed80-d510-11ea-8817-90d96ed72eaa.jpg)
> 

see the image that I put in the bug report and note how I never put the conveyors in the front

**Comment by stuffyAI** [comment]
> see the image that I put in the bug report and note how I never put the conveyors in the front

I mean plast conveyors need both loading and unloading point, this seems intented as they are not a direct upgrade to normal conveyors but a special variant for transporting masses?
