### ISSUE TITLE
bug with the server

### ISSUE THREAD

**Issue by Mr-Optimus** [Anuken/Mindustry#2301]
windows

version 6.1 assembly 7601

when I launch the map and want to open a multi-user server, "server creation Error occurs. (Address already in use: bind")
![Screenshot_1](https://user-images.githubusercontent.com/58262435/89159203-db94ad80-d577-11ea-9d33-6937041d20df.png)

I opened port 6567 in the windows firewall, then went to the router settings, opened the firewall tab, went to the virtual servers tab, added port 6567. Next, I added port 6567 in the torrent and started the "server" command line. I wanted to start a multi-user server and an error popped up.

mods were not used

![Screenshot_1](https://user-images.githubusercontent.com/58262435/89159203-db94ad80-d577-11ea-9d33-6937041d20df.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
You can't have 2 applications listening to the same port.

Choose one. Either stop using the other app for the mean time or change the port of the other app.

I see you meantioned using a torrent client. Change that app's listening port to something not 6567.

**Comment by Mr-Optimus** [comment]
сбасибо помогло)
