### ISSUE TITLE
Visual Glitch, Mechanical Drill

### ISSUE THREAD

**Issue by Hellblazer911** [Anuken/Mindustry#2303]
**Platform**: Windows

**Build**: 104.10

**Issue**: A minor visual Glitch, A mechanical drill that  was "producing" Thorium. I can click the thorium and it gets transfered to my ships inventory then imedietely goes from 1 to 0. The Thorium does not stop at 10 and if the Thorium exceeds 10 the drill mining animation stops.

**Steps to reproduce**: i had a mechanical drill on copper ore, a bridge connecting it from the left(I tried it with a titanium conveyer belt and it still showed up), i looked at the other drills and it did not have this issue, I saw this at 163,25 coordinate on the "Walls are Flood /Attack" map, i deleted the drill and rebuilt it at the same spot and it still "produced" thorium. 
![Glitch](https://user-images.githubusercontent.com/69161607/89206833-1e777500-d5ba-11ea-9961-92bc1e14af47.PNG)

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This can't be reproduced, and it's unlikely to continue occurring in v6.

**Comment by pyronie** [comment]
uh this is caused the the plugin
