### ISSUE TITLE
Mods can't use Mathf.random

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2307]
**Platform**: Android

**Build**: BE 9171

**Issue**: Using `Mathf.random(1)` causes a crash

**Steps to reproduce**:
1. `Mathf.random(1)`

**Link to mod(s) used, if applicable**: F8

**Crash report, if applicable**: `Java class "arc.math.Mathf" has no public instance field or method named "__noSuchMethod__".`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
Also can't use `Time.delta()` if it helps, same error.

**Comment by Anuken** [comment]
Note that `Time.delta` is not a method, it's a field, so that error is correct.
