### ISSUE TITLE
Block Info | Required Tiles

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry#2308]
**Platform**: Android/Linux

**Build**: PA 9183

**Issue**: 
![Screenshot_20200804_232248_io anuke mindustry be](https://user-images.githubusercontent.com/45280919/89314227-f2d4b780-d6ab-11ea-8979-c515811d0386.jpg)

Required tiles are not affinities, so that + doesn't make sense and leads to confusion.

**Steps to reproduce**: N/A

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I think it does make sense. Each tile gives +70% efficiency, where the base efficiency is displayed as 0%.

**Comment by itcannotbe** [comment]
Base efficiency is not displayed in the block info.

**Comment by Anuken** [comment]
That's because there *is* no base efficiency. It doesn't work without those tiles.

**Comment by itcannotbe** [comment]
Alright. I will just reference this issue when someone complains why he can't plop down oil extractors anywhere.

**Comment by Anuken** [comment]
When you're placing an extractor, it displays the efficiency as "0%" above the block, and in the stats it lists the **required** tiles that increase efficiency. Most players should be able to put the two together.
