### ISSUE TITLE
It cant get past the loading screen, hope you can help.

### ISSUE THREAD

**Issue by Gundam627** [Anuken/Mindustry#2309]
Windows 10
104.6

The game gets to the loading screen, then shuts down, I don't understand why.

Start the game

None

Crash Report Below...

[hs_err_pid620.log](https://github.com/Anuken/Mindustry/files/5023254/hs_err_pid620.log)
[hs_err_pid3256.log](https://github.com/Anuken/Mindustry/files/5023258/hs_err_pid3256.log)
[hs_err_pid4052.log](https://github.com/Anuken/Mindustry/files/5023259/hs_err_pid4052.log)
[hs_err_pid4196.log](https://github.com/Anuken/Mindustry/files/5023260/hs_err_pid4196.log)
[hs_err_pid824.log](https://github.com/Anuken/Mindustry/files/5023261/hs_err_pid824.log)

**Comment by Anuken** [comment]
Something is wrong with your Java installation. I can't help you.
