### ISSUE TITLE
[rhino] Regex is broken

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2310]
**Platform**: Android 9

**Build**: BE 9171

**Issue**: Rhino regex in 6.0 will happily match nothing for [class]+

**Steps to reproduce**: 
1. `print(typeof("egg".match(/h+/)));`
2. It is `object` not `null`, + should match 1 or more not 0 or more like *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Too bad. Don't use regex.
