### ISSUE TITLE
Visual Water Unit Glitch

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry#2311]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Running on Chromebook, so Linux
**Build**: *The build number under the title in the main menu. Required.*
BE 9185
**Issue**: *Explain your issue in detail.*
Visual glitch with water units: water trails instantaneously appear across map upon pickup and dropoff by a payload-carrying unit.
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
Use the Mega, pick up any water unit (I happened to use a Bryde), plop it down in another body of water some distance away. 
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
technically speaking it's the android version, unless you cross compiled arm versions of sdl and what not.
