### ISSUE TITLE
power nodes dont auto reconnect after being put down

### ISSUE THREAD

**Issue by Electro9899** [Anuken/Mindustry#2313]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: power nodes done reconnect after being put down by the mega 

**Steps to reproduce**: Pickup a powernode and then put it somewhere where it should connect to other powernodes 

**Link to mod(s) used, if applicable**: none

**Crash report, if applicable**: none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.
