### ISSUE TITLE
Audio randomly changes volume constantly

### ISSUE THREAD

**Issue by Elick320** [Anuken/Mindustry#2314]
**Platform**: Windows

**Build**: 104.10

**Issue**: During seemingly random times, the audio will shift from being loud, to being quiet, and then back to being loud again, repeated indefinitely. [This streamable shows what I'm talking about (I'm constantly entering and exiting the escape menu because it creates a consistent sound)](https://streamable.com/1x3hq9). This doesn't happen with any other game, only Mindustry. It only seems to happen when I move about the area of the map.

**Steps to reproduce**: It started happening when I first installed the game. Has been happening to me since through the campaign, and coop with my friend. Haven't noticed it in the title screen so far. I can't really get more specific than that because I don't actually know what I did other than install the game for the first time.

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't happen to me, or, as far as I know, any other user. Could be a bug with OpenAL, or a hyper-specific problem with my audio system. Either way, I can't fix this.
