### ISSUE TITLE
9189 may be bug with location

### ISSUE THREAD

**Issue by Wencelsav** [Anuken/Mindustry#2315]
**Platform**: *Windows 10*

**Build**: *9189.*

**Issue**: *ice forest inctead start point. and I can not launch core*

**Steps to reproduce**: *may be one reason is that I captured 3rd location without any fight. or after reinstalling to 9189*

**Link to mod(s) used, if applicable**: *without any mods*

**Crash report, if applicable**: *
[crash-report-08_02_2020_22_18_49.txt](https://github.com/Anuken/Mindustry/files/5027637/crash-report-08_02_2020_22_18_49.txt)
[crash-report-07_31_2020_14_47_49.txt](https://github.com/Anuken/Mindustry/files/5027638/crash-report-07_31_2020_14_47_49.txt)
[crash-report-07_31_2020_14_49_35.txt](https://github.com/Anuken/Mindustry/files/5027639/crash-report-07_31_2020_14_49_35.txt)
[crash-report-07_31_2020_14_49_59.txt](https://github.com/Anuken/Mindustry/files/5027640/crash-report-07_31_2020_14_49_59.txt)
[crash-report-08_02_2020_22_17_59.txt](https://github.com/Anuken/Mindustry/files/5027641/crash-report-08_02_2020_22_17_59.txt)

do need saves?

 *

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> without any mods

These crash reports say otherwise. Disable your mods.
