### ISSUE TITLE
Sometimes people get stuck in the transformation mech pads.

### ISSUE THREAD

**Issue by ajd07** [Anuken/Mindustry#2316]
**Platform**: Windows

**Build**: Steam build 104.10

**Issue**: I was normally playing, then I died and ended up getting trapped in the transformation mech pad.

**Steps to reproduce**: I was playing like normal, nothing unusual and doing defence stuff, then I died and I couldn't escape unless I rejoined, got into another mech pad, or someone saves me. This bug seems to happen when you are suffering in decently high ping. If it does happen then you can't escape afterwards even with 1 ping.
Sadly this is pretty hard to reproduce due to be being ping based and I cannot provide a screenshot.

**Link to mod(s) used, if applicable**: None, although mods that do have transformation mech pads suffer from this too.

**Crash report, if applicable**: This isn't a crashing bug.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
These pads no longer exist.

**Comment by ajd07** [comment]
I meant stuff like the alpha mech pad, glave, stuff like that. Sorry for the confusion, just didn't know what to call them

**Comment by Anuken** [comment]
Yes, and those no longer exist.

**Comment by DeltaNedas** [comment]
click the pad again, then again to get back into the mech you used
