### ISSUE TITLE
Invincible monster

### ISSUE THREAD

**Issue by xiaomuhun** [Anuken/Mindustry#2317]
Sometimes monsters are invincible,But that's very rare.We can't destroy him with a fort。

**Comment by ILiekMelons** [comment]
Please use the template

**Comment by xiaomuhun** [comment]
I'm just a gamer

**Comment by Gdeft** [comment]
What is the connection between "I'm just a gamer" and "Please use the template", if you're saying that gamers don't read then h. 

Please use the template.

**Comment by Anuken** [comment]
Mindustry doesn't even have monsters.
