### ISSUE TITLE
New iOS client, new issue

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#2319]
![image0](https://user-images.githubusercontent.com/61173114/89650885-544d7f80-d880-11ea-9fdc-4a81fc68847c.png)
**Platform**: iOS

**Build**: 104.4

**Issue**: Construction animation sometimes does not render.

**Steps to reproduce**: Play the game normally for a few hours. I am not sure what specifically causes this issue, as it seems to appear randomly.

**Link to mod(s) used, if applicable**: None

**Crash report, if applicable**: Issue does not cause crashes.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
I am not sure if iOS can send files correctly to GitHub so I am not sure if the screenshot I have will show. If not, I'll edit it in with my Android client.

**Comment by Anuken** [comment]
Won't fix - restart the game if shaders start to look weird. This is an issue with precision on iOS/Android.
