### ISSUE TITLE
Xbox Game Bar overlay does not support fullscreen for Mindustry, even on borderless windows.

### ISSUE THREAD

**Issue by BTomato47** [Anuken/Mindustry#2320]
The Xbox Game bar says Mindustry in fullscreen does not support the Xbox Game Bar overlay, and it does not even work when Borderless Display is on.

**Comment by stuffyAI** [comment]
> The Xbox Game bar says Mindustry in fullscreen does not support the Xbox Game Bar overlay, and it does not even work when Borderless Display is on.

Yes, because Xbox Game Bar is shit.
This is not the format for issues

**Comment by Anuken** [comment]
> Xbox Game Bar overlay does not support fullscreen

If other software doesn't support Mindustry, that's a problem with that software, not with Mindustry.

**Comment by ILiekMelons** [comment]
oof
