### ISSUE TITLE
Bug with lighting

### ISSUE THREAD

**Issue by stormtrooper145** [Anuken/Mindustry#2321]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: 104.6

**Issue**: Light source and mech's lighting strangely interact with each other, forming a barely noticeable dark line in the middle.

**Steps to reproduce**: 
1. Go to the dark map
2. Place block, that emits light and power it
3. Go to this block at some distance and you will see a barely noticeable dark line between the mech and the light source.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.

**Comment by ThePythonGuy3** [comment]
How can this not be a bug

**Comment by Anuken** [comment]
> How can this not be a bug

The line **isn't actually darker**; I know what this issue is referring to, and I've examined it with an image editor with several different setups. That's just how the lighting works.

**Comment by ThePythonGuy3** [comment]
oh
