### ISSUE TITLE
I have ascended to the astal plane

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#2322]
**Platform**: *iOS*

**Build**: *104.4*

**Issue**: *Max UI scale breaks icons.*

**Steps to reproduce**: *Slide the UI scaling slider to 300% and restart the game.*

**Link to mod(s) used, if applicable**: no

**Crash report, if applicable**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image0-1](https://user-images.githubusercontent.com/61173114/89716150-dcf31b00-d967-11ea-86d8-7602c92f7f3f.png)

**Comment by Anuken** [comment]
You're out of texture space. Won't fix.
