### ISSUE TITLE
The mouse cursor is shifted with the block selected

### ISSUE THREAD

**Issue by axys16** [Anuken/Mindustry#2328]
**Platform**: Linux - Ubuntu 20.04

**Build**: 104.10

**Issue**: 
The mouse cursor is shifted with the block selected.
The offset is about half a block at the bottom right of the cursor.
This is valid in the whole game (menus, map).

**Steps to reproduce**: 
Just start a game, campaign or custom.

My setup is : a laptop (4k screen, GeForce GTX 1650 - 440.100) + an external 4k screen + another external QHD screen.
I tried playing on the main screen and on one of the external monitors, fullscreen and windowed.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
What do you mean, it's "shifted"? Which block is selected? What is it shifted relative to? What does this look like?

> Just start a game, campaign or custom.

Simply starting a game does not reproduce the issue.

**Comment by axys16** [comment]
Sorry about my bad English, it's not my native language.

I took a picture, maybe it'll make it clearer. I'm right-clicking on the copper: 
![20200809_185115](https://user-images.githubusercontent.com/12911605/89737650-c5548900-da72-11ea-897c-f2b59c90ea4a.jpg)

> > Just start a game, campaign or custom.
> 
> Simply starting a game does not reproduce the issue.

On my computer it is. :confused: 

On my previous laptop, the game run very well. Also, it's probably something to do with my multi-screen configuration. In the week I'll try to do more testing, removing screens for example.

**Comment by Anuken** [comment]
That looks like a system related bug - it doesn't happen on any computer or phone I've tested, and it doesn't seem to happen to anyone else, so the problem is likely to be with your setup. Since I can't reproduce it, I can't fix it.
