### ISSUE TITLE
Names not disappearing when log out.

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#2335]
**Platform**: Windows

**Build**: 9228

**Issue**: When, in a server or LAN world, a player joins then becomes another mech and then lefts the game or gets kicked, the name of the player stays on the mech.
Here is a picture of the bug.
(https://media.discordapp.net/attachments/396416151032299521/742435575285547088/unknown.png)

**Steps to reproduce**: I was testing some units while being on my server. Qmelz and some other people joined and we tested some logic gates and stuff. Then, when Qmelz tried riding a Lich, he disconnected. However, his name tag was still on the unit. Then, i used the unit he was using before and moved a bit. After that, Qmelz rejoined and he spawned normaly as a Gamma but, the name on the unit was still not gone. Thus, his name was cloned and no way of getting destroyed unless the unit dies.

**Link to mod(s) used, if applicable**: No mods used.

**Crash report, if applicable**: no crash report

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheSlaylord** [comment]
6.0 has no mechs, these are now regular units
