### ISSUE TITLE
Bug with bridge conveyors.

### ISSUE THREAD

**Issue by shiftdevy** [Anuken/Mindustry#2337]
**Platform**: *Windows*

**Build**: *104.10*

**Issue**: *So, I am using bridge conveyor. If it takes something from one side and transports back to it, it does not work.*

**Steps to reproduce**: *Here is a screenshot of problem: 
![image](https://user-images.githubusercontent.com/53366878/89887760-8d1a8b00-dbd7-11ea-9ea6-5c60a42e0d86.png)
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
bridges do not accept items from the side that it is outputting to, probably not a bug.

**Comment by GlennFolker** [comment]
I'm sure bridge conveyor doesn't accept items from the front
