### ISSUE TITLE
BaseDialog breaks when adding a button

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2339]
**Platform**: Android 9

**Build**: 9226

**Issue**: BaseDialog breaks and everything is put in the top left corner when adding a button.
See [screenshot](https://cdn.discordapp.com/attachments/663854113418641429/742767198879350804/egg.jpg) 

**Steps to reproduce**: 
Script:
```
const dialog = new BaseDialog("$block.router.name");
dialog.addCloseButton();
dialog.buttons.button(Icon.warning, "egg", () => print("click"))
dialog.show()
```

**Link to mod(s) used, if applicable**:
`git clone https://github.com/deltanedas/modding-toolbox -b 6.0`
(Also occurs in the UI editor if the export button is uncommented, and on another mod)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This works fine throughout the Mindustry codebase; your mod is probably at fault here.

**Comment by DeltaNedas** [comment]
But why is it wrong? Shouldn't it be small label, line, close and egg button?
Instead it has a stroke probably for some rhino related reason.

**Comment by Anuken** [comment]
> But why is it wrong?

Just tried running the code, and your parameters are in the wrong order. Fix your `button` call.

I imagine rhino coerces the arguments to something invalid.
