### ISSUE TITLE
log all over title screen

### ISSUE THREAD

**Issue by maarten2007** [Anuken/Mindustry#2340]
**Platform**: Windows 8.1

**Build**: 104.10.

**Issue**: after i left a server this appeart.

**Steps to reproduce**: i left a server

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Schermopname (16)](https://user-images.githubusercontent.com/69542912/89949892-e19a2680-dc28-11ea-8437-eb4a3a98a806.png)

**Comment by Quezler** [comment]
you've just pressed a keybind to open the log console, nothing to worry 🙂

**Comment by summetdev** [comment]
Press F9 to disable it. This is developer console.

**Comment by ThePythonGuy3** [comment]
It is f8, not f9

**Comment by DeltaNedas** [comment]
>press console button
>console opens
>this is bad

**Comment by ILiekMelons** [comment]
g
