### ISSUE TITLE
tiny tiny typo

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#2341]
![제목 없음125](https://user-images.githubusercontent.com/61054554/89987893-b875a680-dcb9-11ea-9998-52d4c4d941b2.png)

temperatire
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not going to fix this because that icon isn't used anyway.
