### ISSUE TITLE
Android 11 Mod Support

### ISSUE THREAD

**Issue by pitust** [Anuken/Mindustry#2345]
**Platform**: *Android 11 RPB2.200611.009*

**Build**: *104.6*

**Issue**: No modding features work (since /sdcard/Android is app-private now)

**Steps to reproduce**:
1. Flash android 11
2. Try to add a mod. 
3. fail. 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
android 11 **mod** support.
or don't use android 11, if you really want to then go balls deep and use ios

**Comment by pitust** [comment]
I got an ipad i can mod on; i got a server i can probably mod on. It's just that i don't want to get termius and termux every time I want to mod.

**Comment by ThePythonGuy3** [comment]
Ehhh

**Comment by pitust** [comment]
> Ehhh, you shall better close this 

The reason it doesn't work is because the mods directory is app private. This will be the case to all future Android versions.

**Comment by Anuken** [comment]
> fail

Show the detailed error message and stack trace.

**Comment by DeltaNedas** [comment]
this is an android issue, no?

**Comment by pitust** [comment]
> > fail
> 
> Show the detailed error message and stack trace.

As far as I can tell, it fail silently. Where to get the error from? [I don't have a computer ATM]

**Comment by pitust** [comment]
> this is an android issue, no?

This is an issue with where mindustry saves its mods

**Comment by Anuken** [comment]
> As far as I can tell, it fail silently. 

What do you mean by "fails", then? What actually happens? You have not described what the problem is. If writing to the mod directory were not allowed, it would display an error message when attempting to do so.

**Comment by pitust** [comment]
I can't describe what happens, because nothing happens. There is literally
no change.

**Comment by pitust** [comment]
Huh... I tried to reproduce it and failed. I'll do some more testing.

**Comment by pitust** [comment]
But loading a mod from zip fails.

**Comment by pitust** [comment]
I can load a mod from githuv but not from a zip

**Comment by Anuken** [comment]
> What do you mean by "fails"?

**Comment by pitust** [comment]
> > What do you mean by "fails"?

I can't figure out how tp send a screen capture.

**Comment by Anuken** [comment]
Is it identical to [this issue](https://github.com/Anuken/Mindustry/issues/2001)?

**Comment by Anuken** [comment]
Tried this out on an emulator with Android 11, and everything works fine.

Since you still haven't told me what actually happens, I'm going to assume it's the same Android 10+ issue that's been reported many times before with mods disappearing after reload. Since I can't reproduce it, I can't fix it.
