### ISSUE TITLE
Crash when trying to insert more than 3500 lines from the buffer into microprocessor and logic processor

### ISSUE THREAD

**Issue by owler0954** [Anuken/Mindustry#2347]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
9241
**Issue**: *Explain your issue in detail.*
I try draw image on display
**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
X
**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*
X
**Crash report, if applicable**: *The contents of relevant crash report files.*
X
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
How is the crash report not applicable if you are trying to report a crash?
