### ISSUE TITLE
release bug

### ISSUE THREAD

**Issue by jojoblackFr** [Anuken/Mindustry#2350]
**Platform**: Windows

**Build**: bleeding-edge build 9267

**Issue**: all item can enter like coal and sand
**Steps to reproduce**: enter the item in core with a conveyor

**Crash report, if applicable**: no crash report, only what i see

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by imreallybadatnames** [comment]
How is it a bug?
Do you mean that all items can get to the core?
Coal and sand are allowed to be in the core.

**Comment by imreallybadatnames** [comment]
Say some item that couldn't get to the core normally in previous releases as an example.

**Comment by jojoblackFr** [comment]
all item can go in core now 
sand, coal, pyratite, blast-compound, spore ...

**Comment by imreallybadatnames** [comment]
The items you specified can be inserted into the core in 5.0.
They all have a use in the core.

**Comment by jojoblackFr** [comment]
all ? spore too ?

**Comment by imreallybadatnames** [comment]
Yes.
+ If there really was a change to allow all items, then it's really not a bug.
Some items may not have a use, except when unloading from the core for further processing.

**Comment by imreallybadatnames** [comment]
But still, easier to transport.
In 5.0, all items are allowed in the core.

**Comment by imreallybadatnames** [comment]
Because the only items that are available in the game are resources.
All resources can be processed obviously.

**Comment by imreallybadatnames** [comment]
Coal can be burned for electricity or compressed into graphite, spores can be converted into oil....

**Comment by jojoblackFr** [comment]
oh
so is not a bug ?

**Comment by jojoblackFr** [comment]
![Capture](https://user-images.githubusercontent.com/57195692/90179084-35ce1380-ddad-11ea-92af-28e06532474e.PNG)

**Comment by DeltaNedas** [comment]
its an intended feature, how else would you research graphite?

**Comment by jojoblackFr** [comment]
oooooooooooh i didn't see the research again so yes maybe

**Comment by jojoblackFr** [comment]
is that ! ok thx

**Comment by Zenith-LY** [comment]
> But still, easier to transport.
> In 5.0, all items are allowed in the core.

not all items can be stored in the core.
