### ISSUE TITLE
Server error (Message block)

### ISSUE THREAD

**Issue by Vladislav117** [Anuken/Mindustry#2352]
**Platform**: *Linux (server)* 

**Build**: *release build 104.10*

**Issue**: *When someone puts a message block, the server crashes. But this does not always happen. That is, if I put or delete a message block, the server may crash, or it may not crash. I have attached a screenshot of the console.*
![image](https://user-images.githubusercontent.com/58992285/90247950-52675b80-de40-11ea-9d65-cc4df252b5b7.png)

**Link to mod(s) used, if applicable**: 
Plugin: https://github.com/Kieaer/Essentials 
Mod (Without scripts): https://github.com/Vladislav117/RPW 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a crash caused by Essentials, not Mindustry.
