### ISSUE TITLE
conduits not working correctly 

### ISSUE THREAD

**Issue by bishbosh69420** [Anuken/Mindustry#2354]
**Platform**: Windows 

**Build**: 104.4

**Issue**: conduits aren't filling with the liquid they are being given, I will attach screenshots if I can further on in this but if I can't I'll explain it here. mechanical pumps were placed on water tiles and then bridged over part of the map, it was bridged over a 3 tile gap, the bridge was full of water but the conduit coming out of it was maybe 5% full, there were over 10+ pumps pumping into it and I synced multiple times to the server.

**Steps to reproduce**. I've seen it happen a few times on CN's servers but I never thought about it and I've not tried to recreate it myself but I have grabbed 2 screenshots of it to try and help.

**Link to mod(s) used, if applicable**: n/a

**Crash report, if applicable**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bishbosh69420** [comment]
![Snapchat-1574559812](https://user-images.githubusercontent.com/66426802/90279744-ac2c4d80-de61-11ea-89b0-d260987d2547.jpg)
^ screenshots of the bug

**Comment by bishbosh69420** [comment]
![Snapchat-1000383471](https://user-images.githubusercontent.com/66426802/90279815-c82fef00-de61-11ea-9ba3-f65a28c02ff3.jpg)

**Comment by Anuken** [comment]
Probably related to an old bridge conduit bug. Bridges have changed several times in v6 so this is unlikely to continue happening.
