### ISSUE TITLE
Local servers port

### ISSUE THREAD

**Issue by Redstonneur1256** [Anuken/Mindustry#2356]
**Platform**: Windows

**Build**: 104.10

**Issue**: On the join game menu, on the local servers list when a local server is hosting using another port than 6567, when trying to join the server, the connection fail because it tries to connect to default port.

**Steps to reproduce**: Create a mindustry server on an other port than 6567, host a game, try to join the game with the local servers list.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix. The client discovery handler has no straightforward way of knowing what the server port is during discovery. Connect directly instead.
