### ISSUE TITLE
Mouse problem

### ISSUE THREAD

**Issue by Makeapro** [Anuken/Mindustry#2359]
**Platform**: Windows

**Issue**: I have to press the left click too hard to click on something 
**Steps to reproduce**: I opened Mindustry on my pc, then I tried to click Play but it didn´t recognize it so I pressed it hard as possible and it worked but I can't play like this, it's too uncomfortable 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Either your system is broken, or you need a new mouse. Mindustry doesn't have a concept of "click strength".
