### ISSUE TITLE
Further progress impossible after unlocking 1 new map

### ISSUE THREAD

**Issue by SteelBlue8** [Anuken/Mindustry#2361]
**Platform**: Desktop

**Build**: 9299

**Issue**: Unlocking frozen forest location in tech tree revealed 6 new sectors to launch to in the planet menu. The location I launched to stated that it contained sand in the resource detected section, however, on arriving there were no enemies in any wave, and no sand on the map. Additionally, launching to any sector other than this one and ground zero became impossible, and evidently this sector is not frozen forest as any locations that require the capturing of frozen forest are still locked, meaning that there is no way to progress any further. 

**Steps to reproduce**:  As described above.

No mods or crash report

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
As far as I know, campaign isn't completed yet.
