### ISSUE TITLE
Naval units dont die on land

### ISSUE THREAD

**Issue by Electro9899** [Anuken/Mindustry#2364]
**Platform**: Windows

**Build**: BE-9302

**Issue**: Naval units when put on land by the mega dont die

**Steps to reproduce**: While on the 6.0 sever orange got the Mega and used it to put Naval units on land

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Why would a boat on land spontaneously die? Do you see real ships exploding simply because they're out of the water?

**Comment by Electro9899** [comment]
no they dont but thats real life and this is mindustry an i think they should

**Comment by Anuken** [comment]
That doesn't make it a bug.

**Comment by TacticalAlpha** [comment]
lmao
