### ISSUE TITLE
Platform: windows,Build: v0.84j Issue: there is a yellow car on the street that drives in circles, I don't know what caused the issue.

### ISSUE THREAD

**Issue by Hawrylakhl** [Anuken/Mindustry#2365]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by walksanatora** [comment]
umm send a screen shot so that it can actuallt be seen what you mean

**Comment by Hawrylakhl** [comment]
I just realized that I am on the wrong gethub page sorry

>
>
>

**Comment by TacticalAlpha** [comment]
Oh lmao.

**Comment by Hawrylakhl** [comment]
I didn’t rtfm

**Comment by Txar** [comment]
lmao

**Comment by Yoroppa** [comment]
bruh

**Comment by ThePythonGuy3** [comment]
Okay this made my day. At least he followed the template
