### ISSUE TITLE
Router snek

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2366]
**Platform**: All

**Build**: 9310

**Issue**: Router overflow snek

**Steps to reproduce**:
1. overflow with items
2. router
3. overflow
4. 2,3
5. output

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
ok

**Comment by BlueWolf3682** [comment]
however, if this is to be removed then I must request that an efficient means of distributing to a chain of 1x1 blocks be added, as routerchaining is heresy to the next level

**Comment by BlueWolf3682** [comment]
however, if this is to be removed then I must request that an efficient means of distributing to a chain of 1x1 blocks be added, as routerchaining is heresy to the next level

**Comment by BlueWolf3682** [comment]
however, if this is to be removed then I must request that an efficient means of distributing to a chain of 1x1 blocks be added, as routerchaining is heresy to the next level

**Comment by DeltaNedas** [comment]
routorio phase router does just that
