### ISSUE TITLE
Modded unit crash

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2367]
**Platform**: Android 

**Build**: 9310

**Issue**: Modded MechUnit crashes

**Steps to reproduce**: 
1. install testcase.zip
2. place factory ,select oh no and give it copper
3. crash

**Link to mod used**: [testcase.zip](https://github.com/Anuken/Mindustry/files/5092065/testcase.zip)

**Crash report**: [crash_1597729774127.txt](https://github.com/Anuken/Mindustry/files/5088451/crash_1597729774127.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/90518301-92765900-e134-11ea-9f5c-bc938dcab362.png)

This mod is empty.

**Comment by DeltaNedas** [comment]
oops

**Comment by Anuken** [comment]
Fixed in Arc.
