### ISSUE TITLE
Found a way to add resources indefinitely

### ISSUE THREAD

**Issue by gilad905** [Anuken/Mindustry#2370]
**Platform**: Windows

**Build**: steam build 104.10

**Issue**: Found a pretty simple way to trick the game into re-playing the same zone launch over and over, thus adding resources to the total count.
This was found following a naive attempt to save zone states to be re-loaded later on (which is crucial to be added as a feature imho).

**Steps to reproduce**:
1. Under campaign mode, enter a zone and mine some resources.
2. Just a bit before launching, save & quit the zone.
3. A file with the zone state will be generated at (on my Windows machine):
C:\Program Files (x86)\Steam\steamapps\common\Mindustry\saves\saves\-1.msav
Make a backup of that file.
4. Return to the zone and launch, adding the resources in the core to your total count.
5. Save & quit the zone again, then close the game.
7. Empty the 'saves' folder (see #3) and copy the zone backup file back into that folder.
8. Open the game, enter campaign mode, enter the zone again and launch again.
Although the zone was re-loaded, the total resource count (and the tech tree) isn't affected by this, so it will rise again.

Just to be clear, I'm not posting this to notify other players of a way of "hacking" the game, only to notify the developer/s of this issue.

**Comment by DeltaNedas** [comment]
you can also make a sandbox map with all the diamond blocks and gold you want then move it to -1.msav, load it and launch
just dont reload the save
you can also Core.settings.putSave("item.routorio-liquid-router", 10000000)

**Comment by Anuken** [comment]
You can also simply:
- Download a 100% save file from someone with all the resources
- Download a cheat mod and get infinite resources
- Use cheat engine
- Enable the console with a mod and spawn in infinite resources

This isn't a real issue. There will always be easy ways to ruin the game and get infinite resources for yourself, and I'm not interested in "fixing" them.

**Comment by markozajc** [comment]
me when when `Game.RuinTheFun()`
