### ISSUE TITLE
You cant upgrade units to multiplicative to exponentiol reconstructor

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2371]
**Platform**: *Android (check others platforms)

**Build**: *bleeding-edge build 9259

**Issue**: You cant upgrade units to multiplicative to exponentiol reconstructor

**Steps to reproduce**: try to upgrade units to exponentiol 
reconstructor

**Link to mod(s) used, if applicable**: no mod

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Good.

**Comment by michas2** [comment]
Why is this closed? Looks like that kind of bug is still existing...

**Comment by michas2** [comment]
Oh, I needed to research that unit first... - Maybe a hint would be nice. Otherwise it really looks like something is broken.

**Comment by fsmorygo** [comment]
I got same error with steam version today.

**Comment by Anuken** [comment]
Read:

> Oh, I needed to research that unit first
