### ISSUE TITLE
not let play saying waiting for more players then kick 

### ISSUE THREAD

**Issue by rabit232** [Anuken/Mindustry#2376]
![Screenshot_20200819-110237_Mindustry BE](https://user-images.githubusercontent.com/69896899/90615902-02581280-e20d-11ea-98f6-a77a4002475d.jpg)
**Platform** android

**Build**: *The build number under the title in the main menu. Required.*9337

**Issue**: *Explain your issue in detail.* i join and no let me play it say waiting for more players then it say IM
![Screenshot_20200819-110835_Mindustry BE](https://user-images.githubusercontent.com/69896899/90616068-3df2dc80-e20d-11ea-80f8-e2a792bcb12d.jpg)
 been kick 

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.* i just join server

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*null

**Crash report, if applicable**: *The contents of relevant crash report files.*as
null not crash it online server
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.** it new  bug

**Comment by Anuken** [comment]
There's not enough information in this issue for me to tell what's going on here.
