### ISSUE TITLE
Rejoining with mega crashes other people

### ISSUE THREAD

**Issue by bsjohnson20** [Anuken/Mindustry#2377]
**Platform**: Windows

**Build**: 9337

**Issue**: Quitting as mega then immediately rejoining kicks everyone with a high chance of being successful at crashing everyone.
Video evidence:
https://cdn-cf-east.streamable.com/video/mp4/itrad7.mp4?Expires=1598096040&Signature=UEfUg5O3y-mfeUThVpl2vcPuFPKLxw7~3ERkIZpaol2iFSKzdNlGs2V8UGa1QIr3CKaAS~YTv1UMVZHGBHlTxrp98HtVa0FdZCAAe9cm6aNPUG4wuofUUFsIpvGkeb1ugRkFK2UDc0wyG1bU5KIhx7jBbZz28yxI8Y4OXlLwt4KH54TQ02ngFHOXGerDeos0ctCZK-jbhd6JI3T0iJGqq9khknUCRmJJixWTiYxejUobViKv4slxem46cl3Fj0Q~-BH20eDATR8A9adfu3BvsDboU6E4fr51qku2d-ZLN-c~faBrt59-g8hhMWwRhdsD1soRZ3D79RRgwXbCTKZCMA__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ

**Steps to reproduce**: 1. Equip mega, 2. rejoin server.

**Link to mod(s) used, if applicable**: Null

**Crash report, if applicable**: No crash report, just kicked people

---

 
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> with a high chance of being successful at crashing everyone

> No crash report, just kicked people

How can it crash and/or kick everyone without an error or crash report? I need the error message.

**Comment by Anuken** [comment]
Could be fixed by now, but without an error log it's not possible to tell.
