### ISSUE TITLE
Mass Item Duplication Glitch

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#2378]
Platform: Windows

Build: 9337

Issue: When you pick up a Container connected to a core, the Container you pick up contains every item wich was in the core. However, the items in the core stays while you still have a Container with thousands of items that you can place anywhere. Thus, duplicating items.

Steps to reproduce: Me and some others were testinf stuff in a sandbox server. Then, when i tried to pick up a Container connected to a Core and placed it down, we saw that items get duplicated.

Link to mod(s) used, if applicable: No mods used.

Crash report, if applicable: No crash.

-X-

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dexapnow** [comment]
It doesn't duplicate items, it just takes them from core, use /sync to see what accualy happends.

**Comment by RebornTrack970** [comment]
It doesnt dupe when you take one, but does if you make multiple containers and output them to another one.
Anyways, hope it gets fixed.
