### ISSUE TITLE
Water drill doesn't work

### ISSUE THREAD

**Issue by omgaXD** [Anuken/Mindustry#2379]
**Platform**: *Windows 10*

**Build**: *BE 9341*

**Issue**: *Water drill doesn't mine water, even with energy source anywhere in new BE*

**Steps to reproduce**: *Place water drill, connect to energy, it won't work for some reason*

**Link to mod(s) used, if applicable**: *Vanilla*

**Crash report, if applicable**: *No crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ILiekMelons** [comment]
water drill
