### ISSUE TITLE
Campaign map glitches

### ISSUE THREAD

**Issue by omgaXD** [Anuken/Mindustry#2380]
**Platform**: *Windows 10*

**Build**: *BE 9344*

**Issue**: *Every time I spawn on any campaign map, that I must explore before launching core to it, there are all possible positions of core are using for spawning core (around 3-5 cores per map), and I get 2k of every item that I can use in building at start, also every enemy spawning pos is using.*

**Steps to reproduce**: *Capture any map, discover map in tech tree, launch to this map*

**Link to mod(s) used, if applicable**: *Vanilla*

**Crash report, if applicable**: *No crashes*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't play the campaign.
