### ISSUE TITLE
Range of processors doesn't appear before building them anymore

### ISSUE THREAD

**Issue by omgaXD** [Anuken/Mindustry#2384]
**Platform**: *Windows 10*

**Build**: *9350*

**Issue**: *In other BE, there was a feature, that showed range of processor connections possible even before building, but now it doesn't show anymore, so it's harder to find optimal position for processor.*

**Steps to reproduce**: *Select any processor in logic category, drag mouse onto land.*

**Link to mod(s) used, if applicable**: *Vanilla.*

**Crash report, if applicable**: *No crashes.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> In other BE, there was a feature, that showed range of processor connections possible even before building

This was never a feature. You're misremembering.
