### ISSUE TITLE
Nodes doesn't reconnect after picking with Mega

### ISSUE THREAD

**Issue by omgaXD** [Anuken/Mindustry#2385]
**Platform**: *Windows 10*

**Build**: *BE 9350*

**Issue**: *When I place three nodes and connect them, and pick middle node with mega, then place it there again, it connects only to first of nodes*

**Steps to reproduce**: *Place three nodes in order, get into Mega, pick one of the nodes, place it back*

**Link to mod(s) used, if applicable**: *Vanilla*

**Crash report, if applicable**: *No crashes*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to. You're not *placing* a node, you're just putting it down.

**Comment by omgaXD** [comment]
I thought it has to have a "memory" of connection, because it does to half of connected items.  So I think you could delete any memory
