### ISSUE TITLE
Cores can be used as teleporters

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry#2413]
**Platform**: Windows

**Build**: Both bleeding edge 9408 and release 104.10

**Issue**: You can teleport items with multiple cores.
<img width="494" alt="Teleport" src="https://user-images.githubusercontent.com/56274831/91072442-62c0c880-e5ee-11ea-86b1-4d466d2590bd.png">

I'm not sure this is that big of a problem, since most maps only have one core.

**Steps to reproduce**: Make a map with two cores, put any material in one of them, and you can unload from anything

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
this is normal/intended, entirely up to the discretion of the map author, and not under normal circumstances 😗
