### ISSUE TITLE
Command center has no description

### ISSUE THREAD

**Issue by SuperStormer** [Anuken/Mindustry#2415]
**Platform**: *Android*

**Build**: *9420*

**Issue**: The command center doesn't have a description in the info popup, unlike in v5.

**Steps to reproduce**: Open the info popup on the command center.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul10** [comment]
There is still bleeding edgeeeeeeee

**Comment by itcannotbe** [comment]
Ah yes. Another one not reading the startup screen again.....

**Comment by Anuken** [comment]
It shouldn't have one.
