### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2421]
**Platform**: android (check other platforms)

**Build**: 9424

**Issue**: clicking in the core oftentimes crash the game.

**Steps to reproduce**: click and hold the core oftentimes.

**Link to mod(s) used, if applicable**: no mod.

**Crash report, if applicable**: 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
Idk if i use oftentimes or many times, sorry about my English

**Comment by Anuken** [comment]
You didn't post a crash log. I can't help you without a log.

**Comment by rodrigolitzius** [comment]
How can i see the crash report?

**Comment by rodrigolitzius** [comment]
And send to you

**Comment by Anuken** [comment]
Find the latest file in `<home folder>/Android/data/io.anuke.mindustry/files/crashes` and send the contents here.

**Comment by rodrigolitzius** [comment]
I dont see the crashes folder

**Comment by Anuken** [comment]
Then I can't help you.

**Comment by rodrigolitzius** [comment]
Is the last log.txt?

**Comment by Quezler** [comment]
probably ^

**Comment by rodrigolitzius** [comment]
[crash_1598373010668.txt](https://github.com/Anuken/Mindustry/files/5125263/crash_1598373010668.txt)
I FIND IT

**Comment by rodrigolitzius** [comment]
FIKS

**Comment by Quezler** [comment]
> NullPointer: 'Attempt to read from field 'boolean mindustry.type.UnitType.canHeal' on a null object reference'

**Comment by rodrigolitzius** [comment]
?

**Comment by Quezler** [comment]
please update to 8143b8d80adf6cc351328516b9ebb4cda14e5600 and verify if this has fixed your crash issue ^ (download the latest be build)

**Comment by rodrigolitzius** [comment]
👍

**Comment by Quezler** [comment]
(and if there is no new download available yet you need to wait, it takes some time for a new bleeding edge to build)

**Comment by rodrigolitzius** [comment]
In the 9430 this bug are fixed?

**Comment by Quezler** [comment]
why don't you give it a try?

**Comment by rodrigolitzius** [comment]
You're right

**Comment by rodrigolitzius** [comment]
Isn't crashing

**Comment by Quezler** [comment]
good, case closed 🚧
