### ISSUE TITLE
Oil bomb ending in sandbox.

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#2422]
**Platform**: Windows*

**Build**: *All builds after 9425*

**Issue**: * On the latest updates, the ability to blow up oil liquid voids and basically anything was removed. Now, I can understand, but this RUINED an amazing sandbox funsie. It was also the only way to change maps. Please revert the explosion-ruining commit, I beg you.*

**Steps to reproduce**: *Atempt to blow up anything.*

**Link to mod(s) used, if applicable**: *None.*

**Crash report, if applicable**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
iirc its just a new `rule` , totally up to the discretion of the map author and/or server owner 🤔

**Comment by Erisfiregamer1** [comment]
Huh. Ill see if I can contact the guy, but hopefully this new rule gets removed before then.
By the way the specific commit was: 
da360f5 Block explosion damage rule - Anuken

**Comment by Quezler** [comment]
that is also a rule, can also be turned on or off by whomever controls the map 🙂

**Comment by Anuken** [comment]
I intentionally added this rule after observing multiple people having "fun" by repeatedly blowing up the core (and everything around it), as well as creating massive infinite explosion chains with builders. No thanks.

**Comment by ayangd** [comment]
And that makes my game lag at the point of the game not responding. Maybe you should try to limit the particle or something?

**Comment by BasedUser** [comment]
Disable them.
