### ISSUE TITLE
wrong sprites

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2423]
**Platform**: *Android*

**Build**: *9430*

**Issue**: when putting items on the floor they get a little crooked

Like this
![Uploading Screenshot_2020-08-25-15-46-47.png …]()

**Steps to reproduce**: *put the screenshot items in a map*

**Link to mod(s) used, if applicable**: *no mod*

**Crash report, if applicable**: *not this time*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
![Screenshot_2020-08-25-15-46-47.png](https://user-images.githubusercontent.com/60452545/91216002-a3523c00-e6eb-11ea-94de-9adb07c65366.png)

The photo

**Comment by Anuken** [comment]
This doesn't happen to me.

**Comment by rodrigolitzius** [comment]
Hmm...

**Comment by rodrigolitzius** [comment]
To me this is very old

**Comment by Anuken** [comment]
If it's been happening for a long time, then it's probably device specific. It doesn't happen anywhere else, as far as I can see, and I won't be fixing it.
