### ISSUE TITLE
Arkyid can build a block 

### ISSUE THREAD

**Issue by grimsoul7** [Anuken/Mindustry#2426]
**Platform**: *Android*

**Build**: *9436.*

**Issue**: *arkyid can build a block like support unit do.*

**Steps to reproduce**: *just place some block and let's build.*

**Link to mod(s) used, if applicable**: *nope.*

**Crash report, if applicable**: *i think no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul7** [comment]
![Screenshot_2020-08-26-10-08-40-374_io anuke mindustry be](https://user-images.githubusercontent.com/57223926/91251365-7bafb200-e785-11ea-830d-6adaeeee8bae.jpg)
This is what i can take

**Comment by itcannotbe** [comment]
But it should actually build blocks right. So not a bug.

**Comment by grimsoul10** [comment]
Actually yes but, he's will too OP, he can't beat antumbra alone lol

**Comment by itcannotbe** [comment]
But still, it's not a bug.

**Comment by grimsoul10** [comment]
Yes it should be end
