### ISSUE TITLE
Item sources can't be disable

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2427]
**Platform**: *Android*

**Build**: *9434.*

**Issue**: *when disable with processors, item sources continue creating items.*

**Steps to reproduce**: *make a source and one processor, disable the source with the processor*

**Link to mod(s) used, if applicable**: *nothing...*

**Crash report, if applicable**: *nothing too...*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
Oh i forgot the brackets

**Comment by rodrigolitzius** [comment]
👍

**Comment by rodrigolitzius** [comment]
👍

**Comment by itcannotbe** [comment]
Item sources are a dumb block. The don't have any condition in them that stops it from outputing items as items instantly made in them so to speak. (They always have an item in them)

**Comment by braainsiogame** [comment]
conveyor

**Comment by ayangd** [comment]
Just disable the conveyor.

**Comment by rodrigolitzius** [comment]
> Item sources are a "dumb" block. The don't have any condition in them that stops it from outputing items as items instantly made in them so to speak. (They always have an item in them)

Anuke fix...

**Comment by rodrigolitzius** [comment]
> Item sources are a "dumb" block. The don't have any condition in them that stops it from outputing items as items instantly made in them so to speak. (They always have an item in them)

Anuke fix...
