### ISSUE TITLE
speedhack

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2431]
**Platform**: Android 9

**Build**: 9442

**Issue**: 
Speedhack on multiplayer works

**Steps to reproduce**: 
`UnitTypes.arkyid.speed = 1000`
`UnitTypes.alpha.speed = 10000`
`UnitTypes.alpha.speed = 0 / 0` <--- nan bug really caused here

**Link to mod(s) used, if applicable**: deltanedas/dev-mode

**Crash report, if applicable**: nobody crashed until nan, which crashed everyone except a few people

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I was there when it happened, and the NaN bug is already fixed.

> Speedhack on multiplayer works

Of course it does, I've been speedhacking on my server since it was created. Strict validation mode is off.

**Comment by DeltaNedas** [comment]
ah

**Comment by braainsiogame** [comment]
yo wtf

**Comment by ASFRedstone** [comment]
Well, anuke saves the day again
