### ISSUE TITLE
Language change error

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2432]
**Platform**: *Android*

**Build**: *9442.*

**Issue**: *you can't change the language of the game by selecting it in language.*

**Steps to reproduce**: *try to change your language :).*

**Link to mod(s) used, if applicable**: *no.*

**Crash report, if applicable**: *no too*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Yes, you can. Restart your game.

**Comment by rodrigolitzius** [comment]
What's wrong with my device? I restart the game end back to the default language

**Comment by rodrigolitzius** [comment]
What's wrong with my device? I restart the game end back to the default language, and it is old too, so i think it's my device ):

**Comment by rodrigolitzius** [comment]
But in 104.6 this isn't happen, wtf
