### ISSUE TITLE
All items that can't be disable with a processor

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2434]
**Platform**: *Android*

**Build**: *9442.*

**Issue**: *i made a list of ALL items that can't be disable with a processor.

![Screenshot_2020-08-26-16-24-54.png](https://user-images.githubusercontent.com/60452545/91347709-27bec080-e7b9-11ea-8057-4f8015ae5753.png)*

I recommend make a disable version of:
Nodes, all transportation items, solar panels, command center, memory cell, display, vault, container, liquid tank

but i think that the transportation items is the most important here
_____________________________________________
I forgot diode on the screenshot, Don't forget diode :)
_____________________________________________
Ye i know that the most part of the issue isn't a bug, but i don't want to spam you with issues/pull requests, talking about all these blocks individually, so i put everything in one issue to help you :D
_____________________________________________
It's YOUR game, you add a disable version of what you want
_____________________________________________
**Steps to reproduce**:

**Link to mod(s) used, if applicable**: 

**Crash report, if applicable**: 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
Press f to pay respects to anuke

**Comment by itcannotbe** [comment]
How on earth would you expect disabled power nodes to work?

**Comment by rodrigolitzius** [comment]
Oh man i forgot diode

**Comment by rodrigolitzius** [comment]
> How on earth would you expect disabled power nodes, command center, amd liquid junctions even work?
> 
> Also why would you want a memory cell disabled in the first place?

THIS IS THE ITEMS THAT DONT HAVE A DISABLED VERSION

**Comment by itcannotbe** [comment]
> > How on earth would you expect disabled power nodes, command center, amd liquid junctions even work?
> > Also why would you want a memory cell disabled in the first place?
> 
> THIS IS THE ITEMS THAT DONT HAVE A DISABLED VERSION

Answer my question.

**Comment by itcannotbe** [comment]
I don't see a logical explanation why you want logoc related stuff to be disabled.

**Comment by rodrigolitzius** [comment]
> I don't see a logical explanation why you want the memory cell to be disabled..

I just make list of items that don't have a disabled version only

**Comment by rodrigolitzius** [comment]
I don't want nothing

**Comment by rodrigolitzius** [comment]
**DON'T FORGET DIODE ANUKE**

**Comment by ILiekMelons** [comment]
> How on earth would you expect disabled power nodes, command center, vaults, containers, and liquid junctions, even work?
> 
> Also why would you want a memory cell disabled in the first place?

disabled power nodes simply don't transfer power
command center doesn't even exist
vaults and containers stop accepting/unloading
liquid junctions just stop working

i'm sure there's some niche use case for disabling a memory cell

**Comment by rodrigolitzius** [comment]
**I recommend make a disable version of:
Nodes, all transportation items, solar panels, command center, display, vault, container, liquid tank**

**Comment by ILiekMelons** [comment]
i feel like this should be a feature request and not a bug, because there's no unintended bugs here

**Comment by rodrigolitzius** [comment]
**_i recommend_** anuke so what he want with his game

**Comment by rodrigolitzius** [comment]
Again, dont forget diode anuke

**Comment by itcannotbe** [comment]
@ILiekMelons Command Centers Exist. Again.

**Comment by rodrigolitzius** [comment]
> @ILiekMelons Command Centers Exist. Again_.
> 
> Also I don't really see a point in disabling memory cells.
> You can store a lot in them. And what would happen if a processor access a disabled memory cell....

> happen if a processor access a disabled - memory cell...

Nothing

**Comment by rodrigolitzius** [comment]
Probably the game will crash but this is fixeable

**Comment by rodrigolitzius** [comment]
> i feel like this should be a feature request and not a bug, because there's no unintended bugs here

Ites a bug, because all liquid transportation items isn't... Disable, able? And it is a bug

**Comment by rodrigolitzius** [comment]
A make this to not spam anuke of millions of issues

**Comment by rodrigolitzius** [comment]
> A make this to not spam anuke of millions of issues

...talkink about all these blocks, i think it's better put everything in one issue

**Comment by Anuken** [comment]
Some things that won't be changed:

- Vault/container: They don't do anything on their own. Disabling doesn't make any sense.
- Display/message/memory: Same as above.
- Power nodes: These aren't counted as being part of the network and will not be disable-able. They do not 'conduct' power.
- Batteries: No intuitive way for them to get disabled.
- Command center: Doesn't actively do anything.

**Comment by rodrigolitzius** [comment]
> Some things that won't be changed:
> 
> - Vault/container: They don't do anything on their own. Disabling doesn't make any sense.
> - Display/message/memory: Same as above.
> - Power nodes: These aren't counted as being part of the network and will not be disable-able. They do not 'conduct' power.
> - Batteries: No intuitive way for them to get disabled.
> - Command center: Doesn't actively do anything. 
> 

The nodes is for we can make a logic that disable cut off the energy of something, if you dont want to make a disabled version of nodes, you can make a disabled version of batteries, with this will be possible a lot of things, please reconsider

@Anuken ;D

**Comment by Anuken** [comment]
I will do neither. If you want isolated networks, use disabled diodes.

**Comment by rodrigolitzius** [comment]
> I will do neither. If you want isolated networks, use disabled diodes.

Ok ;D

**Comment by andrei1690** [comment]
> 
> 
> Some things that won't be changed:
> 
>     * Vault/container: They don't do anything on their own. Disabling doesn't make any sense.
> 
>     * Display/message/memory: Same as above.
> 
>     * Power nodes: These aren't counted as being part of the network and will not be disable-able. They do not 'conduct' power.
> 
>     * Batteries: No intuitive way for them to get disabled.
> 
>     * Command center: Doesn't actively do anything.

I think memory cells could be disabled. When processors try to access anything from a disabled memory cell then it will return null. Also when can memory cells store strings? Because there's so much more potential for logic by being able to store strings. Vaults and containers could also be disabled, they wouldn't output anything from unloaders, so we don't have to "logically" (as in a mindustry term) disable unloaders 1 by 1. Disabled command centers wouldn't command any units, and disabled batteries wouldn't input power. Cutting off power using power nodes is also essencial,

**Comment by Anuken** [comment]
No. I've already explained my reasoning several times, and I won't be repeating myself. Don't bring up dead topics.
