### ISSUE TITLE
Useless scatter turret

### ISSUE THREAD

**Issue by VBismuth** [Anuken/Mindustry#2437]
**Platform**: Android 9 *PKQ1.190414.001*

**Build**: 104.6

**Issue**: Scatters don't attack enemies at any conditions. *Tetsed ammo: scrap, lead*

**Steps to reproduce**: Choose the first map, build a scatter, connect it with any ammo source (e.g. lead), wait until enemy's drones destroy your scatter with no problem.

**Link to mod(s) used, if applicable**: -

**Crash report, if applicable**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by the-red-soul** [comment]
You are using scatter against air units correct? As it is an Anti Air turret.

**Comment by VBismuth** [comment]
> You are using scatter against air units correct? As it is an Anti Air turret.

Well, I've read in-game wiki closely. Now I understand that visibly flying units that go through the buildings easily is ground units. That was just a mistake, my bad
