### ISSUE TITLE
Server doesn't preserve gamemodes

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#2439]
**Platform**: Windows

**Build**: MindustryBuilds/9457

**Issue**: Server doesn't preserve gamemodes after BE updates

**Steps to reproduce**: Host a server, have BE update, end current map. Tested with `host map pvp`.

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to. When you `host` and shuffle, it will use the specified mode, but when a map is loaded there is no gamemode specified anywhere.
