### ISSUE TITLE
Players can interact things while "Waiting for players..." is on middle of the screen in PvP game/server

### ISSUE THREAD

**Issue by TheMrAlbert** [Anuken/Mindustry#2441]
**Platform**: Windows

**Build**:  9461

**Issue**: Players can do anything while waiting for players in PvP even if there is one player in a server/game. (Close this if intended)

**Steps to reproduce**: 
1. Create PvP game (you can also make it locally)
2. Upon in game, you will see that you can move everywhere even if "waiting for players..." is on the middle of the screen. You can drill/build/shoot as one player in game.

**Link to mod(s) used, if applicable**: No mods used

**Crash report, if applicable**: No Crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheMrAlbert** [comment]
Additional, I would suggest that by freezing the game until new players has joined.

**Comment by Anuken** [comment]
Not a bug. The game was never supposed to be paused while that message was shown.
