### ISSUE TITLE
Community Servers Tab Bug

### ISSUE THREAD

**Issue by LiamDonohue** [Anuken/Mindustry#2442]
**Platform**: *Android*

**Build**: *104.6*

**Issue**: *The "Community Servers" tab is showing up empty.*

**Steps to reproduce**: *I clicked the tab*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

EDIT: I cannot connect to any servers

**Comment by Anuken** [comment]
> I clicked the tab

Assuming you *did not* mean that you collapsed the menu with all the servers (which would make it empty for obvious reasons): Some Android devices have issues with HTTP requests due to an Android bug. This won't be fixed.
