### ISSUE TITLE
Save message

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2443]
**Platform**: *Android*

**Build**: *9465.*

**Issue**: *when you save the map and leave, the message that appears says that you didn't save the map*

**Steps to reproduce**: 
*1 make or edit a map.
2 Save the map
3 exit the map*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It does **not** say that. It simply says, *any unsaved changes will be lost*, which is true regardless of whether you saved.

**Comment by rodrigolitzius** [comment]
@Anuken no, it says 
you have unsaved changes
![Screenshot_2020-08-27-16-58-54.png](https://user-images.githubusercontent.com/60452545/91489300-fd3b3900-e886-11ea-99f4-fa6259714640.png)

you have unsaved changes

**Comment by rodrigolitzius** [comment]
@Anuken no, it says 
you have unsaved changes
![Screenshot_2020-08-27-16-58-54.png](https://user-images.githubusercontent.com/60452545/91489300-fd3b3900-e886-11ea-99f4-fa6259714640.png)

you have unsaved changes

**Comment by rodrigolitzius** [comment]
I can't change the language to you understand, because i can't, idk why, i restart the game too

**Comment by rodrigolitzius** [comment]
I'm sorry, I got to change the language, and it really appears, but in my language is what I said

**Comment by rodrigolitzius** [comment]
It's a translation error

**Comment by Anuken** [comment]
It's because the translation has not caught up yet.
