### ISSUE TITLE
indistructable menders

### ISSUE THREAD

**Issue by DockedSiamang22** [Anuken/Mindustry#2446]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows

**Build**: *The build number under the title in the main menu. Required.* BE 9468

Issue- Indestructible menders

reproduction- campaign sector 36 has indistructable menders

mods- none used at time, had been using https://github.com/TheTerrarian101/OP-EX-Mindustry-Mod on a dfferent sector, then unloaded mod when moving sectors

crash report- na

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported._

**Comment by Quezler** [comment]
please reformat your issue to not use big black cursive text as the answer to each question, it blends confusingly 🤔

**Comment by Anuken** [comment]
The mod you linked explicitly says it changes how menders work.

**Comment by DockedSiamang22** [comment]
Mod was disabled at the time,

**Comment by Quezler** [comment]
but was the save ever saved with that mod enabled at the time?
