### ISSUE TITLE
Sound sliders never go 0% completely

### ISSUE THREAD

**Issue by fbarda** [Anuken/Mindustry#2448]
**Platform**: *Windows*, however other platforms should be tested too.

**Build**: *104.10 itch.io*

**Issue**: *Volume sliders ignore the 0%, instead keeps the last value it had.*

**Steps to reproduce**: 
* Open the Sound settings,
* Pull any slider to the very left of the screen (music is the most easiest one to detect)
* Close the settings menu
* Listen, you may need to increase the computer volume if your ears are not that sensitive. You should be able to hear the music

**Link to mod(s) used, if applicable**: *None.*
---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

_If you also have this bug on a different platform, please comment it so I can add it to here_

**Comment by itcannotbe** [comment]
You lied.

 > I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by fbarda** [comment]
> You lied.
I searched "slider" instead of volume since I thought it was slider related bug. Sorry.

**Comment by Anuken** [comment]
> that doesn't change the fact bug still exists.

No, it does *not* exist. Every comment stating otherwise is incorrect and referring to an older build.

**Comment by Arrcival** [comment]
> > that doesn't change the fact bug still exists.
> 
> No, it does _not_ exist. Every comment stating otherwise is incorrect and referring to an older build.

Is 104.10, the current build downloaded from itch.io an old build ? [Cause it is still reproducable in 104.10](https://github.com/Anuken/Mindustry/issues/2031#issuecomment-683160393)

Also, all the PRs you quoted are all closed @itcannotbe as if there were fixed or all dupes of an opened one, while it's still reproducable, or the bug added again

**Comment by itcannotbe** [comment]
You know when the dev said it's fixed he means he already fixed in the code for release in the next version.

**Comment by Anuken** [comment]
I'm tired of repeating myself. Just read the issues, I've had this discussion several times before.
