### ISSUE TITLE
Modded turret crash oh no

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#2450]
**Platform**: *Android*

**Build**: *The build number under the title in the main menu. Required.* 9468

**Issue**: *Explain your issue in detail.* While porting my mod to 6.0, I wanted to test how modded turrets will work, but... they don't work, moreover, they crash the whole game.
*I know that the game's whole source code had changed, but I don't think this should happen with `health` field. If this is not an in-game bug, please tell me how to fix this myself.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.* Just attempt to build the Gold Meltdown or similar modded turret. Link to a mod is below.

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.* https://github.com/TheSlaylord/GoldMod/tree/mindustry-v6

**Crash report, if applicable**: *The contents of relevant crash report files.* 
```
> NullPointer: 'Attempt to write to field 'float mindustry.gen.Building.health' on a null object reference'
BuildBlock.constructFinish: 64
Call.constructFinish: 242
BuildBlock.constructed: 99
BuildBlock$BuildEntity.construct: 217
BuilderMinerPayloadUnit.update: 1020
-$$Lambda$YLG6AvmE6BBi-QxdrWn0CEMuwAo.get: 2
EntityGroup.each: 66
EntityGroup.update: 57
Groups.update: 52
Logic.update: 377
ApplicationCore.update: 36
ClientLauncher.update: 151
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1281
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
modded turrets do work, your mod is broken
that has nothing to do with health, building was null (hasEntity() is false)

**Comment by DeltaNedas** [comment]
also you should use the "6.0" branch for 6.0 mods

**Comment by Anuken** [comment]
Your turret is broken.
