### ISSUE TITLE
Some blocks cannot be placed on the border of the map.

### ISSUE THREAD

**Issue by Gdeft** [Anuken/Mindustry#2453]
**Platform**: *Windows 10*

**Build**: *BE 9475*

**Issue**: Blocks cannot be placed at the dark parts of the map or at the "border" of the map. But, this works for blocks that have a size larger than 1 for the top and left border part since they are a multiblock type. However, this does not happen to the left or the bottom unless the block size is larger than 2 because of the positions. This issue is caused mainly by the block's size.

**Steps to reproduce**: Open any map. Place a block with different sizes in every border of the map. From block sized one to three, it should look like this:

![image](https://user-images.githubusercontent.com/63198340/91627358-093b0e00-e9e1-11ea-8500-9e0285f06ff4.png)
![image](https://user-images.githubusercontent.com/63198340/91627381-2c65bd80-e9e1-11ea-85c1-da58a94a23d7.png)
![image](https://user-images.githubusercontent.com/63198340/91627444-8f575480-e9e1-11ea-9ad6-f984cc37f3dc.png)
![image](https://user-images.githubusercontent.com/63198340/91627428-6f279580-e9e1-11ea-9d50-926e5814cbbc.png)

The red cross indicates that the block cannot be placed on the border of the map, meanwhile the green check indicates that the block can be placed on the border of the map.

**Link to mod(s) used, if applicable**: *None.*

**Crash report, if applicable**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
because in multiblocks the primary block tends to sit somewhere along the line of the center to the bottom left corner, which perfectly explains why the different size blocks act differently for each of the 4 map edges 🙂 (mappers tend to recommend a 3 wide border of unbreakable blocks around map edges at all times to help with the black "fog of war" blending, and it will also prevent players from being able to even try to place blocks on the border)

**Comment by Anuken** [comment]
The *center* of a block cannot be in darkness. With 2x2 blocks, the center can't be an exact grid coordinate, so the bottom left corner is used instead.

**Comment by Liftyee** [comment]
> The _center_ of a block cannot be in darkness. With 2x2 blocks, the center can't be an exact grid coordinate, so the bottom left corner is used instead.

Would it be possible to remove this? What is its purpose?
