### ISSUE TITLE
ghost bullets bug

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#2454]
**Platform**: *Windows*

**Build**: *104.6*

**Issue**: *1. Shield absorbed Meltdown laser (this is not the problem) 2. Another shield absorbed daggers' bullets 3. Shield that absorbed laser before takes damage too.*

**Steps to reproduce**: *
![GIF13](https://user-images.githubusercontent.com/61054554/91629948-4cf53e00-ea08-11ea-99e3-2716e1dd2e64.gif)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by younggam** [comment]
with some experiment purpose mod, owner of each ghost bullets was normal dagger. And meltdownLaser was only last one tick.

**Comment by Anuken** [comment]
Duplicate, this was already fixed.
