### ISSUE TITLE
something about bugs 

### ISSUE THREAD

**Issue by 0SomeOneRandom0** [Anuken/Mindustry#2457]
**Platform**: *Windows*

**Build**: *9475*

**Issue**: *Basically you can select any last block of categories just by:*

**Steps to reproduce**: *1. selecting duo 2. going to planet map 3. going back and pressing left arrow*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by imreallybadatnames** [comment]
anuken is on vacation

**Comment by imreallybadatnames** [comment]
he wont do anything

**Comment by 0SomeOneRandom0** [comment]
I know

**Comment by Anuken** [comment]
Not a bug.
