### ISSUE TITLE
no water in map

### ISSUE THREAD

**Issue by islq** [Anuken/Mindustry#246]
There is no water in many sectore map.
The '**elevation**' in **generateTile**() is too big to create water block:

```java
       if(elevation < 0.7){
            floor = Blocks.deepwater;
        }else if(elevation < 0.79){
            floor = Blocks.water;
        }else if(elevation < 0.85){
            floor = Blocks.sand;
```

**Comment by Anuken** [comment]
I don't see the problem. Many sectors are at high elevations, and thus do not have water. 

![screenshot from 2018-10-15 22-52-46](https://user-images.githubusercontent.com/10100000/46989994-594ea700-d0cd-11e8-80c4-1b904103bf1a.png)

Lower-elevation areas of the map have large lakes.

**Comment by islq** [comment]
But the random Missions.blockRecipe in those high elevations maybe need water to finish.

**Comment by Anuken** [comment]
Water can be obtained with a water extractors in sectors without water.
