### ISSUE TITLE
Weird overlap in the top left menu on mobile

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2465]
**Platform**: Android 9
Screen size from Core.graphics: 1406x720
uiscale: 100

**Build**: 9475

**Issue**:
In the top left menu there are some overlapping parts.
I believe arc is not using floats for some reason
![screenshot](https://user-images.githubusercontent.com/39013340/91653758-00a31000-ea93-11ea-8c23-a6304282f625.jpg)

**Steps to reproduce**:
1. Start a game
2. Look closely

**Link to mod(s) used, if applicable**:
None, but with deltanedas/ui-lib installed its menu has some overlap too.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There are no overlapping parts on my device or emulator. Increasing spacing leads to random gaps instead. You probably have some pixel imprecision due to the strange screen width - won't fix.

**Comment by DeltaNedas** [comment]
in case someone else has this problem, quick mod's main.js that fixes it:
```js
Events.on(ClientLoadEvent, () => {
	const root = Vars.ui.hudGroup.find("overlaymarker");
	const buttons = root.cells.get(0).get().cells;
	buttons.get(1).padRight(0.4);
	buttons.get(3).padRight(0.4);
});
```
