### ISSUE TITLE
(basically) all empty fluid blocks show water throughput on hover

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#2466]
**Platform**: `mac`

**Build**: `9478`

**Issue**: `place any fresh liquid block & hover over it:`

![Screen Shot 2020-08-30 at 13 07 22](https://user-images.githubusercontent.com/3179271/91657533-f9dfc180-eac1-11ea-84a2-96c3364c4206.png)

**Steps to reproduce**: `was taking a look at the liquid source block for this suggestion:`
https://github.com/Anuken/Mindustry-Suggestions/issues/437

**Link to mod(s) used, if applicable**: `null`

**Crash report, if applicable**: `null`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
(also, a liquid source block set to a fluid shows a flow of thousands per second, though its not literally outputting that)

**Comment by braainsiogame** [comment]
![image](https://user-images.githubusercontent.com/59963353/91661345-a4c59f00-eb05-11ea-8575-c9a686951597.png)
BRUH
