### ISSUE TITLE
Coreblock ? : doesn't display bar.corereq

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#2467]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: `9478`

**Issue**: [this](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/storage/CoreBlock.java#L147) text never shows, its always this or nothing: (pic made in sandbox mode)

![Screen Shot 2020-08-30 at 13 11 21](https://user-images.githubusercontent.com/3179271/91657606-93a76e80-eac2-11ea-891b-6ad585aa22cd.png)

**Steps to reproduce**: `trying to place a core in sandbox mode`

**Link to mod(s) used, if applicable**: `null`

**Crash report, if applicable**: `null`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ritzip** [comment]
the roomba left the plast conveyor
