### ISSUE TITLE
Light does'nt blink before death

### ISSUE THREAD

**Issue by ethandudu** [Anuken/Mindustry#2468]
**Platform**: *Windows (i think it's on all platform)*

**Build**: *104.6*

**Issue**: *the player light doesn't blinks at the last step before death*

**Steps to reproduce**: *Join a pvp map or survival and take damage from another player/entity. the last shoot you recevied before your death the light from your player doesn't blinks. Link to the video : https://ethandudu.tk/light-mind.mkv*

**Link to mod(s) used, if applicable**: *No mod.*

**Crash report, if applicable**: * No crash.*

I'm sorry if it's not understandable, i'm a french player.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The frequency is too high too display, so it just turns dark.

**Comment by ethandudu** [comment]
Ok
