### ISSUE TITLE
Crash with mods

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2470]
**Platform**: *Android*

**Build**: *9488.*

**Issue**: *when you place a turet in the floor, the game crashes.*

**Steps to reproduce**: *download the mod, and place a turret in the floor (:
(open the .zip and remove all items that aren't working.*

**Link(s) to mod(s) used**: *eyeofdarkness/advancecontent*

**Save file**: *nothing here (: .*

**Crash report**: *
I cant upload the file, so here's the text

> NullPointer: 'Attempt to invoke virtual method 'void mindustry.gen.Building.placed()' on a null object reference'
BuildBlock.constructed: 100
BuildBlock$BuildEntity.construct: 217
BuilderMinerUnit.update: 1024
-$$Lambda$YLG6AvmE6BBi-QxdrWn0CEMuwAo.get: -1
EntityGroup.each: 66
EntityGroup.update: 57
Groups.update: 52
Logic.update: 377
ApplicationCore.update: 36
ClientLauncher.update: 151
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Txar** [comment]
Mods for 5.0 don't work on 6.0

**Comment by TheSlaylord** [comment]
Turrets are broken. See #2450

**Comment by DeltaNedas** [comment]
no, ac is for 5.0
your turret is broken

**Comment by Txar** [comment]
@rodrigolitzius just don't play 6.0 with mods for 5.0

**Comment by ThePythonGuy3** [comment]
ohno, why are these reports even a thing

**Comment by Txar** [comment]
yes, why are people so dumb

**Comment by Quezler** [comment]
anuke should probably add a "mindustry-version" tag (or array) or something to [mod.json](https://github.com/EyeOfDarkness/AdvanceContent/blob/master/mod.json)'s and only load mods when the version number equals, should be perfectly backwards compatible but not so future proof since anuke wanted to get rid of the 5/6 numbers iirc 🤔
