### ISSUE TITLE
reload wont reload sounds

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Anuken/Mindustry#2471]
**Platform**: Windows Embedded 8.1 Industry Pro 

**Build**: 104.10

**Issue**: Reloading Mods Won't Load Sound.

**Steps to reproduce**: Just Reload The Mod And Play Custom Sound. If Plays Sound, I Think It Only Happens on Certain Devices. If Didn't Play Sound, That's What we got.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
reloading mods is deprecated, restart the game.

**Comment by DeltaNedas** [comment]
oh so you didn't use any mods and it still happened? use the template pls

**Comment by GlennFolker** [comment]
I think this is why you have to restart the gane everytime you import a mod
