### ISSUE TITLE
Turret controller desync

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2472]
**Platform**: Android 9

**Build**: 9492

**Issue**: On multiplayer when switching turrets, other players often get "stuck" in the old turrets (you can still control them though)
Fixed by /sync.
Unsure of the real cause.

**Steps to reproduce**: 
Several players try to jump around in a line of duos.
First seen when rotating in connect 4.

**Save file**: Very large save due to many processors on the map, routerchain.ddns.net

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen to me when I rapidly switch turrets with two players on a local server.

**Comment by DeltaNedas** [comment]
Not rapidly though, and the framerate is below 60
