### ISSUE TITLE
Desync with player controller turret's @shooting

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2473]
**Platform**: Android 9

**Build**: 9494 :o

**Issue**:
In my 3 player connect 4 game, you essentially need to /sync after every move.
For some reason the players' shooting desyncs with the server and everyone has a wrong board, waiting on someone else to finish *their* turn.

May be related to previous issue with turret controlling desync.

**Steps to reproduce**:
1. Join server
2. Place schematic
3. Try to play without /sync every 3 seconds
4. /sync
5. See that the board is completely different with the last few turns

**Schematic file (rename because github is braindead)**: [connect3.txt](https://github.com/Anuken/Mindustry/files/5154395/connect3.txt)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not going to be fixed. Player shooting positions can vary significantly across clients due to snapshot frequency, and attempting to do anything as precise as selecting a display with them is not going to work, especially when a logic processor is only polling it at a sizable interval.
