### ISSUE TITLE
Attempt to update immediately closes and empties the current game jar, not even making a new one.

### ISSUE THREAD

**Issue by imreallybadatnames** [Anuken/Mindustry#2476]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
bleeding-edge 9495
**Issue**: *Explain your issue in detail.*
Attempting to update to the latest build using the in-game button on recent builds will cause the game to close almost immediately, leaving behind the empty jar file(the game jar you were using to update from).
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Try using in-game check update button or wait for it to detect the update itself.
2. If you agree to update, it will start downloading but as soon as the download bar (0/54 MB) shows up, the game closes and leaves behind the empty jar file(the game jar you were using to update from).
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
N/A
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
None
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Zenith-LY** [comment]
where is that in game update button?

**Comment by Anuken** [comment]
Works fine on my machine.

**Comment by Anuken** [comment]
I'll just assume Windows is being stupid and doesn't like self-writing JARs.

**Comment by Shawak** [comment]
Do you use some kind of antivirus software? If so, did you try disabling it?

**Comment by DeltaNedas** [comment]
ah yes NT, the only kernel with "Error: file in use"
