### ISSUE TITLE
Median option in map editor crashes the game

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#2478]
**Platform**: *Windows*

**Build**: *9503*

**Issue**: *median setting in the map editor crashes the game when added, not even showing the box for it and the map preview is greyed out with a reload symbol, for about a minute until it says its not responding*

**Steps to reproduce**: *go to map editor, esc > generate > add > median, the game then crashes instantly*

**Save file**: *never saved it once since it was just me starting ore generation so i dont have a save file*

**Crash report**: *where do i find these? ill edit in the contents of them after i find them*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by mse-k** [comment]
it seems it just does a fuckton of cpu work or lots of ram since i actually did it on a empty map and it frose for a sec but it started running again after about 30 secs with low af frame rates and then i changed radius higher and it crashed

**Comment by mse-k** [comment]
oh wow i make a new save and add some lines of ice tiles in it and open it and then it ACTUALLY crashes (not just stops responding) with the `Java heap space` error

**Comment by mse-k** [comment]
i think theres a memory leak with it or it uses a fuckton of memory to work

**Comment by mse-k** [comment]
[crash-report-09_02_2020_21_13_28.txt](https://github.com/Anuken/Mindustry/files/5165589/crash-report-09_02_2020_21_13_28.txt)

**Comment by Anuken** [comment]
Fixed.
