### ISSUE TITLE
Bloom flickers WAY too much

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2480]
**Platform**: *Windows*

**Build**: *9497*

**Issue**: *The bloom, especially on lines, even more so on horizontal and vertical lines, flicker way too much when its position changes on the screen.*

**Steps to reproduce**: *Make a bloomed effect with lines appear on screen, and pause and move the screen or zoom in and out. The image below demonstrates this with the unit possess effect, with some custom lines drawn on Layer.effect.*   

   
![image](https://user-images.githubusercontent.com/58885089/92073491-bf8e6100-edee-11ea-8433-53fd26040f13.png)

**Link(s) to mod(s) used**: *Mod irrelevant, vanilla bloom effects have the same problem.*

**Save file**: *null*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Bloom samples from a smaller screen buffer. Don't draw thin lines with bloom.
