### ISSUE TITLE
Cat image processor schematic causes lots of lag

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2482]
**Platform**: Android 9
2.8GB of ram

**Build**: 9507

**Issue**:
A single display and 9 processors almost filled with drawing instructions cause immense lag every few seconds.
I believe it's GC related.
Schematic: (rename to msch, github is very silly) [cat.txt](https://github.com/Anuken/Mindustry/files/5169106/anuk.txt)

**Steps to reproduce**:
1. place schematic
2. lag every few seconds

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No idle lag on my Android 7 phone with 3GB RAM, and a profiler on my PC doesn't even register any logic-related time. Run your own profiling and find out what the problem is.
