### ISSUE TITLE
Unit's health doesn't save correctly

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#2484]
**Platform**: *Windows*

**Build**: *104.6*

**Issue**: *I set UnitHealthMultiplier to 1000. I spawned draug and Save and exit and load game. Then unit's health was not full. With some experiment mode, when It spawned, Its health was 80000. After save and load, Its  health was 14464
![제목 없음158](https://user-images.githubusercontent.com/61054554/92299788-8a217900-ef90-11ea-8871-7b3a2cee9c72.png)
*

**Steps to reproduce**: *Set map's UnitHealthMultiplier to 1000*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Unit health has a limit of around 16k in 104, because it's written as a short.
