### ISSUE TITLE
Bugged block placement

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#2491]
**Platform**: Android

**Build**: bleeding-edge build 9525

**Issue**: Bugged block placement
![Screenshot_2020-09-05-19-49-18-37](https://user-images.githubusercontent.com/70744599/92306012-58bba400-efb6-11ea-9db5-14be328048c9.png)

**Steps to reproduce**: I honestly don't know how this happened, but probably, 
1) Enter map 174.
2) Go offscreen for a second.
3) And then re-enter

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
what even happened here?

**Comment by Anuken** [comment]
The inverse flood fill algorithm messed up some tile data.
