### ISSUE TITLE
Spiders can walk in dark areas

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#2494]
**Platform**: *Windows, but it happens server side too so all platforms*

**Build**: *9541*

**Issue**: *Spider units can walk into dark areas if not directly controlled by players (commanded units can, any ones being controlled by command center can, idle ones can, and ones sent in waves can)*

**Steps to reproduce**: *many things can cause it depending on what state the unit was in*

- if you want to make the commanded ones go into the dark area, just press g and move in a way that makes them think going through the wall is faster then going around

- waves that have spiders will just go through them like theres nothing there to go to your core

- same thing the other way around if they are idle and see a enemy unit they will walk through the dark areas and will walk through them to get to the drop zone if set to attack

**Link(s) to mod(s) used**: *none*

**Save file**: *it has happened in campaign, and on servers, the campaign one i died in because i didnt expect them to be able to walk through it so they evaded all my defences*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
