### ISSUE TITLE
why does this label even exist because every issue with it was given to the issue by the person who made it

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#2495]
no
![image](https://user-images.githubusercontent.com/37938606/92311113-27c17c00-ef82-11ea-90d4-3a43b8c79d18.png)

**Comment by mse-k** [comment]
how do i even add the label anyways

**Comment by Anuken** [comment]
*you* can't, it was added automatically by github as part of an old issue template, which isn't around anymore
