### ISSUE TITLE
rotateBlock

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry#2500]
**Platform**: *Windows*

**Build**: *9547*

**Issue**: *Crashed&kicked on the global 6.0 server.*

**Steps to reproduce**: *.*

**Crash report**: *
![image](https://user-images.githubusercontent.com/31485341/92322298-2010de80-f039-11ea-885a-430429a6ce8e.png)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
> the

there are several 😗

**Comment by Prosta4okua** [comment]
mindustry.pl:6000
