### ISSUE TITLE
BE downgrades after restart

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#2504]
**Platform**: *Windows*

**Build**: *9562*

**Issue**: *every time the game is opened it reverts back to the version it was first downloaded in (for me its 9503) and you have to update it every time it starts up*

**Steps to reproduce**: *update game since you downloaded it, exit, start back up, reverted to original version*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ilya246** [comment]
it does not downgrade - it's just that it downloads the new version into /appdata/roaming/mindustry/be_builds and launches it, not changing the initial one
