### ISSUE TITLE
Script errors do not show up as a mod error

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2505]
**Platform**: Android

**Build**: 9560

**Issue**:
Typos or script-load time errors do not show up as a mod error like JSON errors.

**Steps to reproduce**:
1 Have a typo or throw an error

**Link(s) to mod(s) used**:
main.js #1
`(`
main.js #2
`h()`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not supposed to.
