### ISSUE TITLE
Mindustry/Mindustry BE doesn't launch in Mac.

### ISSUE THREAD

**Issue by pixaxeofpixie** [Anuken/Mindustry#2506]
**Platform**: *Mac*

**Build**: *9525.*

**Issue**: *After i launch the Mindustry BE .jar file and she just stay in Dock and doesnt open and after that she disappears from Dock.It happens at every laucnh attempt.BUT,from steam version all is nice.Also this bug happens with usually mindustry NOT from Steam.*

**Steps to reproduce**: *Just open the Mindustry.jar file.*

**Link(s) to mod(s) used**: *None.*

**Save file**: *None.*

**Crash report**: *None.I dont know were is can be.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
On Mac, run with `java -XstartOnFirstThread -jar file.jar`.
