### ISSUE TITLE
Genearte Tool Doesn't Work

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry#2515]
Platform: Android

Build: bleeding-edge build 9552

Issue: When making a map using the generate tool, after applying, the game crashes

Steps to reproduce: Create a map using generate tool, add a few things with it, apply and then the game crashes. I was making a 500x500 map so it may be bevause of size but I don't think so.

Link(s) to mod(s) used: None

Save file: None

Crash report: (In the comments)

---

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I can't fix this without a crash report. Check the game's crash folder in `Android/data/io.anuke.mindustry`.

**Comment by Zenith-LY** [comment]
> I can't fix this without a crash report. Check the game's crash folder in `Android/data/io.anuke.mindustry`.

it says > OutOfMemoryError: 'Failed to allocate a 4571352 byte allocation with 2433808 free bytes and 2MB until OOM'
Seq.resize: 757
Seq.add: 365
BlockRenderer.lambda$new$1$BlockRenderer: 86
-$$Lambda$BlockRenderer$-CsZnLKIG9pR_byRgxAwkFsfZ6E.get: -1
Events.lambda$fire$2: 30
-$$Lambda$Events$kEWEoJJ7iuVpyOJB9UfewcihGzY.get: -1
Seq.each: 200
Events.fire: 30
Events.fire: 25
World.lambda$notifyChanged$3: 318
-$$Lambda$World$KWGF5jIwmpLS7ay378zAPh8Ln4Q.run: -1
AndroidGraphics.onDrawFrame: 414
GLSurfaceView$GLThread.guardedRun: 1557
GLSurfaceView$GLThread.run: 1268
