### ISSUE TITLE
It's me again.Mac dont launch.

### ISSUE THREAD

**Issue by pixaxeofpixie** [Anuken/Mindustry#2520]
**Platform**: *Mac*

**Build**: *9525*

**Issue**: *
Yeaah, I know that you are already bored with my problems, but still i have this problem.I'm reinstal the Java a two times again and nothing happen.This error is still in Terminal.If you ask im download the LATEST Java version.Now i think its can be not Java version problem.Maybe something.Maybe something was wrong initially in the jar version itself?Because this problem also exists with the version downloaded from itch.io.But with Steam all is good.If you need some screenshots i can add him.*

**Steps to reproduce**: *I say this in previous issues.Just launch mindustry be from terminal*

**Link(s) to mod(s) used**: *None.*

**Save file**: *None.*

**Crash report**: *None.Error report still like in previous issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
screenshot your output of `java --version` in the mac `terminal` app 🍿

**Comment by pixaxeofpixie** [comment]
![Снимок экрана 2020-09-08 в 22 40 24](https://user-images.githubusercontent.com/63517945/92520522-67a78e00-f224-11ea-81bd-3b962a9d3d9c.png)

**Comment by Quezler** [comment]
according to google this command lists all the installed versions, of which one or more may be problematic: `/usr/libexec/java_home -V`

**Comment by pixaxeofpixie** [comment]
iMac-Mac:~ mac$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
iMac-Mac:~ mac$

**Comment by pixaxeofpixie** [comment]
okay i find java unistal tool.Im downloading him and after this i check

**Comment by Quezler** [comment]
and `ls /Library/Java/JavaVirtualMachines/` is there anything in there with an 8 in in the filename?

**Comment by pixaxeofpixie** [comment]
i find the 1.6.0 jdk.It will be deleted?Right?

**Comment by pixaxeofpixie** [comment]
no in this folder only 1.6.0

**Comment by pixaxeofpixie** [comment]
because im right now use the java unistall tool and him delete the 1.8.0.I think i just need delete 1.6.0 jdk and download 1.8.0 jdk

**Comment by Quezler** [comment]
that might work yes

**Comment by pixaxeofpixie** [comment]
okay im trying now.

**Comment by Quezler** [comment]
are you in the mindustry discord? it might be better to discuss it in `#general-programming` instead of here since this spams emails to anyone subscribed to the repo :|

**Comment by pixaxeofpixie** [comment]
oh yeah,im going to discord
