### ISSUE TITLE
Mindustrty 6.0 launch error

### ISSUE THREAD

**Issue by Danil006** [Anuken/Mindustry#2525]
sum problems
![изображение](https://user-images.githubusercontent.com/62474108/92641144-f8df3900-f2e6-11ea-8db2-226c1c1dfc2b.png)
[crash-report-09_09_2020_21_30_30.txt](https://github.com/Anuken/Mindustry/files/5197426/crash-report-09_09_2020_21_30_30.txt)

OpenGL ver 2.1 DirectX 11

**Comment by Anuken** [comment]
Your computer's graphics drivers / GPU are too old to support Mindustry.

**Comment by DeltaNedas** [comment]
install debian
`apt install libgl1-mesa-glx`
