### ISSUE TITLE
crashes when you put a block from the mod

### ISSUE THREAD

**Issue by Kirusha28** [Anuken/Mindustry#2526]
**Platform**: Android

**version** 9583

**Issue**: *mod for 5.0 is launched when trying to place a turret or a container crashes.*

**Steps to reproduce**: *I use mod for mindustry 5.0.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable![Screenshot_2020-09-09-22-40-19.png](https://user-images.githubusercontent.com/62811727/92647122-0cdb6880-f2f0-11ea-9f37-7f7504cc1e43.png).*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I use mod for mindustry 5.0.

5.0 mods are not compatible with 6.0.

> 9583

This is an old build.

**Comment by DeltaNedas** [comment]
how does this guy manage to breathe

**Comment by mse-k** [comment]
yea im getting the same issue but its strange because most of the stuff works BUT just like a 1x1 vault block and a silver turret that came with example mod crash, and some stupid thing i was scripting. the rest works fine
