### ISSUE TITLE
2 Logic Blocks Can't Select A Block Under Them

### ISSUE THREAD

**Issue by Zenith-LY** [Anuken/Mindustry#2527]
Platform: Android (Probably also applies on other platforms)

Build: bleeding-edge build 9608, also applies on all previous buildings with micro and/or hyper processor blocks.

Issue: I can't select a block under a micro and/or hyper processor block (For hyper processors, the block in the middle is the one that can't be selected) . It clicks the edit button instead. It is also a bit hard on Logic Block.

Steps to reproduce: Place a micro and/or hyper processor block, place a block under them, try to click the block.

Link(s) to mod(s) used: None (Mods wouldn't affect it anyway.)

Save file: None (It isn't an issue that only happens in a specific map/save file.)

Crash report: None (No crashes)

---

- [ ] I haven't searched the closed and open issues to make sure that this problem has not already been reported because It's too long.

**Comment by Anuken** [comment]
Not a bug.

**Comment by Zenith-LY** [comment]
> Not a bug.

how are we supposed to select it?

**Comment by Gdeft** [comment]
You can just move it by one tile, you know. The reason you can't click it is because of the configuration button blocking it.

**Comment by mse-k** [comment]
theres like a 3 pixel gap between the edit button and the next block so you can actually select it

**Comment by rodrigolitzius** [comment]
> > Not a bug.
> 
> how are we supposed to select it?

anuke is right, maybe making a suggestion is a best way, make issues is only for V6 bugs

**Comment by DeltaNedas** [comment]
additionally search means the search feature not looking through 2 and a half thousand issues/prs
