### ISSUE TITLE
V6 mods don't load

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#2529]
**Platform**: *Android*

**Build**: *The build number under the title in the main menu. Required.* BE 9623

**Issue**: *Explain your issue in detail.* Mod(s) with `minGameVersion: 105` don't load

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* 
1) I changed the `minGameVersion` in my mod.hjson to 105.
2) Updated my BE client to 9623.
![Screenshot_20200910_075453](https://user-images.githubusercontent.com/62336673/92683382-67e67d00-f33b-11ea-8683-fa8c70fbd471.jpg)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* https://github.com/TheSlaylord/GoldMod/tree/6.0

**Save file**: *The save file you were playing on when the bug happened, if applicable.* None

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* This isn't a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by C0D3Giant** [comment]
> **Platform**: _Android_
> 
> **Build**: _The build number under the title in the main menu. Required._ BE 9623
> 
> **Issue**: _Explain your issue in detail._ Mod(s) with `minGameVersion: 105` don't load
> 
> **Steps to reproduce**: _How you happened across the issue, and what exactly you did to make the bug happen._
> 
> 1. I changed the `minGameVersion` in my mod.hjson to 105.
> 2. Updated my BE client to 9623.
>    ![Screenshot_20200910_075453](https://user-images.githubusercontent.com/62336673/92683382-67e67d00-f33b-11ea-8683-fa8c70fbd471.jpg)
> 
> **Link(s) to mod(s) used**: _The mod repositories or zip files that are related to the issue, if applicable._ https://github.com/TheSlaylord/GoldMod/tree/6.0
> 
> **Save file**: _The save file you were playing on when the bug happened, if applicable._ None
> 
> **Crash report**: _The contents of relevant crash report files. REQUIRED if you are reporting a crash._ This isn't a crash
> 
> _Place an X (no spaces) between the brackets to confirm that you have read the line below._
> 
> * [x]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

there isn't any mod for v6... yet

**Comment by TheSlaylord** [comment]
> > **Platform**: _Android_
> > **Build**: _The build number under the title in the main menu. Required._ BE 9623
> > **Issue**: _Explain your issue in detail._ Mod(s) with `minGameVersion: 105` don't load
> > **Steps to reproduce**: _How you happened across the issue, and what exactly you did to make the bug happen._
> > 
> > 1. I changed the `minGameVersion` in my mod.hjson to 105.
> > 2. Updated my BE client to 9623.
> >    ![Screenshot_20200910_075453](https://user-images.githubusercontent.com/62336673/92683382-67e67d00-f33b-11ea-8683-fa8c70fbd471.jpg)
> > 
> > **Link(s) to mod(s) used**: _The mod repositories or zip files that are related to the issue, if applicable._ https://github.com/TheSlaylord/GoldMod/tree/6.0
> > **Save file**: _The save file you were playing on when the bug happened, if applicable._ None
> > **Crash report**: _The contents of relevant crash report files. REQUIRED if you are reporting a crash._ This isn't a crash
> > _Place an X (no spaces) between the brackets to confirm that you have read the line below._
> > 
> > * [x]   **I have searched the closed and open issues to make sure that this problem has not already been reported.**
> 
> there isn't any mod for v6... yet
> 
> v6 build is 108
> the mods your using is for 105
> edit: the game files on v6 is different than v5 and your mods are for v5

@C0D3Giant, please note that this was posted on the 10th September! Build 108 did not exist that time!
