### ISSUE TITLE
Plastanium Conveyor Graphical Bug

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2530]
**Platform**: *Windows*

**Build**: *9623*

**Issue**: *Build a line of plast conveyors and fill it up to the brim, and remove one block at the end. Now the filled conveyor right in front of the removed conveyor becomes empty(graphically), but still preserves the items.*

![image](https://user-images.githubusercontent.com/58885089/92694434-01d11880-f382-11ea-8030-c9aae19d5b30.png)
(Before Removal:)
![image](https://user-images.githubusercontent.com/58885089/92694492-18776f80-f382-11ea-8fb9-c762152b024f.png)

**Steps to reproduce**: *Shown above.*

**Link(s) to mod(s) used**: *null*

**Save file**: *Irrelevant*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
is there still a roomba under the popup?

**Comment by Quezler** [comment]
i'm guessing this line is to blame: (specifically the if right below it)
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/StackConveyor.java#L118

looks like anuke added that check in: 8729410cd8e9c75ca17a34f375eb18d2d6cfff11 
which checks for the existance of a building while it should only look for the existance of a tile to interpolate from 🤔 

though the check below it does used the rotation of what is there, so only using the tile will be impractical at best 😗 

i would recommend a fallback that `from` get set to the current tile if null, which is a [normal](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/StackConveyor.java#L207) thing to happen 😇 

```
            Building from = world.build(link);

            if(from == null) from = <this>;

            if(link == -1 || from == null) return;
``` 

> example code snippet, untested ^
