### ISSUE TITLE
Reaserch bug on 9630

### ISSUE THREAD

**Issue by Crewm8** [Anuken/Mindustry#2533]
There is no crash or something like that. But when I wanted to transfer a data from PC(windows) to Android my research reset to zero. I found this bug on build 9630 if it`s repaired, sorry for bothering you. 

P.S. If there is some mistakes in the message above, sorry. I`m not good at speaking or writing on English.

**Comment by Anuken** [comment]
1. Follow the template.
2. I won't be looking into campaign issues until it's done. You haven't provided enough information for me to able to diagnose this.
