### ISSUE TITLE
No limit on when you can launch in the latest build

### ISSUE THREAD

**Issue by ASFRedstone** [Anuken/Mindustry#2536]
**Platform**: *Android*

**Build**: *Bleeding Edge Build 9635*

**Issue**: *When launching the campaign mode, I am able to launch the core when I have 0 materials in the core, which allows me to get to desolate rift without any research, The only need is 26 copper for core creation.*

**Steps to reproduce**: *Launch game, Launch Campaign, pause, click "Launch Core"*

**Link(s) to mod(s) used**: *None*

**Save file**: *Brand new*

**Crash Report**: *No crash*

Screenshots
![Screenshot_20200910-181139](https://user-images.githubusercontent.com/70297524/92816285-4618e480-f393-11ea-9ded-f9fc6e633bbd.jpg)
![Screenshot_20200910-181123](https://user-images.githubusercontent.com/70297524/92816289-4c0ec580-f393-11ea-8c66-bb2b5ca39315.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
**desolate rift**
