### ISSUE TITLE
Ground units walking looks visually messed up.

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2545]
**Platform**: Windows 10

**Build**:  bleeding-edge 9664

**Issue**: When using ground units (though the most notable is with the reign), the walking on the legs looks off as it seems they go faster then the unit is actually moving, and they go forward and backward a bit too much. The legs also have yet another weird problem where if you are walking forwards into a wall, the leg animation will still continue and it will cause the leg to have the foot appearing on top of the wall, which looks weird (example: 
![image](https://user-images.githubusercontent.com/34169172/93003378-6f548480-f4fb-11ea-8618-77328da66051.png)).

**Steps to reproduce**: Make a ground unit (not a legs unit like toxopid), preferrable a big one like reign, walk, which is easiest by just taking control of the unit and moving around.

**Link(s) to mod(s) used**: No mods used.

**Save file**: Not really required, as this is replicatable on any map.

**Crash report**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
None of these are bugs.

**Comment by Syncinus** [comment]
What should it qualify as then? it looks visually bad, and I don't believe this should be a suggestion as it would end up just being "Change the way that walking looks".

**Comment by Anuken** [comment]
It's a suggestion, because "this doesn't look good" is generally not a bug unless something is clearly not being rendered correctly. Mindustry has had walking like this (heck, *much worse than this*) for a very long time.

**Comment by Syncinus** [comment]
The walking in 5.0 looks better then it does on 6.0, specifically for eradicator/reign, as the reign legs move back/forth a lot more and move faster, versus the walking on the 5.0 eradicator looks proportionate to it's speed.

**Comment by Anuken** [comment]
> The walking in 5.0 looks better then it does on 6.0,

Not in my opinion. I fired up a v5 client before making my comment, and it looks *terrible* on eradicators, just blobs waving around, really.

**Comment by Syncinus** [comment]
I guess it could be taken that way, I just think that in general now that we have legs units with procedural animation walking we can have something like that on normal units, but I will put it as a suggestion instead of an issue.
