### ISSUE TITLE
Workshop description bug

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#2546]
**Platform**: Windows

**Build**: 104.10

**Issue**: When uploading an map to the workshop, newlines are not displayed correctly.

**Steps to reproduce**: Upload a map to the workshop with a description containing newlines.

**Link(s) to mod(s) used**: None

**Save file**: None

**Crash report**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Edit: I am not sure if this has been fixed in V6 already also I couldn't find any related issue, so I am reporting it.

**Comment by Anuken** [comment]
Not relevant in v6.
