### ISSUE TITLE
Dark areas hide power node connections

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry#2550]
**Platform**: Windows 10

**Build**: Bleeding edge 9686

**Issue**: The dark areas hide power node connections

![image](https://user-images.githubusercontent.com/56274831/93032509-d733c980-f5e6-11ea-9813-d3870feb1812.png)

**Steps to reproduce**: make a map with cliffs, and connect power nodes across the dark areas

**Link(s) to mod(s) used**: none

**Save file**: none

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're supposed to.
