### ISSUE TITLE
After beating a sector, the skip wave part stays?

### ISSUE THREAD

**Issue by genNAowl** [Anuken/Mindustry#2551]
**Platform**: Windows

**Build**: 9692

**Issue**: 
This: (see top-middlish side)
![bug](https://user-images.githubusercontent.com/68400583/93043719-8b454c80-f607-11ea-946a-519ba1ede9f4.jpg)

**Steps to reproduce**: 

1. Clear ground zero

**Link(s) to mod(s) used**: 

None

**Save file**: 

None; It was a new game

**Crash report**: 

None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

I expect this to be closed very quickly

**Comment by GlennFolker** [comment]
> I expect this to be closed very quickly

I expect Anuke to say "don't play campaign"

**Comment by genNAowl** [comment]
> I expect Anuke to say "don't play campaign"

That's what I expected too.
