### ISSUE TITLE
Phase fabric wall

### ISSUE THREAD

**Issue by Plagueboi** [Anuken/Mindustry#2555]
**Platform**:Windows

**Build**: steam build 104.10

**Issue**: unable to build phase walls onto other walls (like what you can do with most walls)

**Steps to reproduce**: i was inside nuclear complex making my defences, it was an hour into it and i tried to build a phase wall onto a plastanium one when it would not let me

**Link(s) to mod(s) used**:  none

**Save file**:  6.msav

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You can only upgrade walls directly when the newer wall has more health.
