### ISSUE TITLE
Using undo and redo in editor

### ISSUE THREAD

**Issue by Excavator987** [Anuken/Mindustry#2566]
**Platform**: Windows

**Build**: 9752

**Issue**: When you place a block in editor, undo that action and then redo it, the block will be placed 1 tile to the right and up, and the block would be in derelict team

**Steps to reproduce**: Place a block in editor, press undo and then redo.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
