### ISSUE TITLE
Campaign Co-op client building bug.

### ISSUE THREAD

**Issue by djradnad** [Anuken/Mindustry#2573]
**Platform**: *Windows*

**Build**: *The build number under the title in the main menu. Required.*
105
**Issue**: *Explain your issue in detail.*
As client, my building selections are the sandbox options even though I am in campaign.  Also, launchpads have no animation for me and they just appear full.
![image](https://user-images.githubusercontent.com/3418158/93460680-98856400-f8b1-11ea-8d25-26e2c14f3554.png)
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just join a friends campaign in the steam alpha build.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
> my building selections are the sandbox options

you mean because you can build all 3 cores?

**yes**: that is now normal, if you have enough resources you can upgrade your current core by placing a larger one on top.
**no**: then your screenshot & explanation failed to explain the issue you're having so you'll need to explain it better.

**Comment by Anuken** [comment]
1. my building selections are the sandbox options even though I am in campaign

That's intentional. Connecting to clients in the campaign does not function as if *you* are in campaign, because that would break everything.

2. launchpads have no animation for me and they just appear full.

...because you're not actually in the campaign, only the other player is.

**Comment by RogueRedHawk** [comment]
Does this mean there's no plans to support multiple players playing the campaign? On thing I really liked to do on 5.0 was play the campaign with my friends and level up all of our stuff together. It sounds like this isn't gonna be possible on 6.0 :/

**Comment by RogueRedHawk** [comment]
By "Support" I don't mean just being able to build at the same time, but also level up the tech tree and unlock sectors together.

**Comment by Anuken** [comment]
> but also level up the tech tree and unlock sectors together.

Yes, because items are stored on sectors now. Since *your* saves are different from those of your friend, you can't gain items anywhere. Launch pads don't work either - where would the items go?

**Comment by RogueRedHawk** [comment]
Perhaps technology could still be restricted to what the host has unlocked? And make a permission that allows players who join to research?

I will post in Mindustry-Suggestions with this idea.

**Comment by Anuken** [comment]
1) is already on the Trello, while 2), I think, is unnecessary. Asking the host to research what they want is easier than coordinating some permission system.

**Comment by djradnad** [comment]
I didn't realize it was intended, as it felt very broken. I suppose that I much preferred 5.0 as well.  Is it also intended that I can see parts of the map that the host cannot? despite those areas being off-limits to build in? referring to some areas that look like large wetlands.

**Comment by Anuken** [comment]
Yes, because those area limits depend on the sector.
