### ISSUE TITLE
Irregular Tech tree connection

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry#2574]
**Platform**: Windows

**Build**: Bleeding Edge - 9771

**Issue**: So I was playing the Forbidden Campaign, and the tech tree branching from Silicone Smelter to Metglass, Oil and Processor was irregularly connected to other cells.

**Steps to reproduce**:

- Exist
- Open Mindustry - v6 unstable builds
- Play the campaign
- Procrastinate until you get to the point in the bugged tech tree
- Enjoy one of the few bugs in Anuke's masterpiece

**Link(s) to mod(s) used**: No mods.

**Save file**: Idk if i can share a campaign save file, so...

**Crash report**: Not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Image in case you don't believe me or just wanna confirm:

![image](https://user-images.githubusercontent.com/65382389/93466938-a74c3500-f90a-11ea-8210-71a9320eeb10.png)

**Comment by Anuken** [comment]
That's how the layout works.

**Comment by iLagSoUhax** [comment]
Hold up, the one from Silicone Smelter to Metaglass? You sure?

**Comment by Anuken** [comment]
Yes. I don't see a problem there. That's the optimal layout.

**Comment by iLagSoUhax** [comment]
uh... okay? It's still a bit weird though, not at all like all other branches.

**Comment by Anuken** [comment]
That doesn't make it a bug.

**Comment by iLagSoUhax** [comment]
fair.
