### ISSUE TITLE
android game input schematic BUG

### ISSUE THREAD

**Issue by neil11008** [Anuken/Mindustry#2578]
**Platform**: *Android*

**Build**: *9771*

**Issue**: 
I make a schematic on PC client
the  ">>" operator  will change to "<<"
when I input schematic to android client

**Link(s) to mod(s) used:**
no mod

**Save file: **
this is my schematic :
https://cdn.discordapp.com/attachments/534597477085478912/756153812158513262/numberdisplayer.msch

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Update your game.
