### ISSUE TITLE
Building shortcut info hide map exit button

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2581]
**Platform**: *Windows*

**Build**: *9771*

**Issue**: *If I open the map while I build something the building shortcut info is on top of the map exit button. 
![Screenshot 2020-09-17 170144](https://user-images.githubusercontent.com/57239116/93508995-6a3e6d80-f91f-11ea-902a-12022dab9dbd.png)
*

**Steps to reproduce**: *Start any game type, build something, and while building click on the map*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
