### ISSUE TITLE
Unhittable units

### ISSUE THREAD

**Issue by ninjassifi** [Anuken/Mindustry#2582]
**Platform**: Windows

**Build**: Steam version 105

**Issue**: Me and my friend have been playing the campaign, And discovered an issue. After wave six (ground zero), The units are invincible. Turrets do no damage and players do no damage.

**Steps to reproduce**: *Me and my friend were playing, until wave six. They came invincible. Just load up the campaign and be in ground zero, no other campaign levels. Get to wave six and place any type of gun or shoot them with your gun. We have come across this issue 2 times, and still counting. *

**Link(s) to mod(s) used**: Had no mods, But did take several screenshots:
![20200917114407_1](https://user-images.githubusercontent.com/71397710/93515603-b963ae80-f8dd-11ea-99b5-fc84b8b4070a.jpg)
![20200917114441_1](https://user-images.githubusercontent.com/71397710/93515616-be286280-f8dd-11ea-9cac-16b25ebe23c6.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
*I* can kill units with turrets and my ship at waves 6 and above. 

I don't think invincibility is the problem. In your screenshot, the turret seems to be in range, but nothing is being shot.

**Comment by ninjassifi** [comment]
I don't know what the problem is. I used my player gun for shooting. I did host a game, that might be the problem.

**Comment by Daniel-Chin** [comment]
May be related: on a hosted game, sometimes turrets constructed by guest players appears to be not firing on the host's screen. On the guest's screen, the enemies appear to be taking bullets but not dying.

**Comment by ninjassifi** [comment]
I placed that turret. Something happened.

**Comment by Anuken** [comment]
> Something happened.

*What* happened?

**Comment by ninjassifi** [comment]
When I placed that turret it had no AI towards the enemy. Maybe it wasn't there. Maybe the enemy units weren't in the game. They destroyed my core, that is for sure. But all I know is that it is a bug.

**Comment by Shaneilenin** [comment]
Seems we had similar problem today, we played in coop on Shattered map (3 players), and at some point turrets and bots stopped firing at the enemies and they didn't receive any damage even when we try to fire at it from bots and turrets through manual control. After a while everything went back to normal by self, but then broke again.  It happened multiple times in one game, but we didn't notice any pattern that can cause it yet. (v6 alpha build 105)

**Comment by Draco18s** [comment]
Commenting that I have now also seen this issue.

Here you can see turrets (preexisting) not firing at the enemy:
![20200919193631_1](https://user-images.githubusercontent.com/1750680/93691805-2e86dd80-fab0-11ea-82dc-591f1ae9af3c.jpg)

Here you can see my bullets phrasing right through an enemy:
![20200919193741_1](https://user-images.githubusercontent.com/1750680/93691797-1911b380-fab0-11ea-8e25-7f0269443614.jpg)

The walker appears to have been the last enemy from one wave, the boss flier was its own wave (my bullets did appear to hit it, but one lone player drone can't really do that much against it).
Also, really? A boss on wave 7?

**Comment by Anuken** [comment]
@Draco18s Did you at any point try reloading the save to see if it fixed things?

**Comment by Draco18s** [comment]
@Anuken Actually I did! It was too late to actually *do* anything about it, but the walker was Just Gone (it *had* been destroying things, and I had no turrets that far south, so I have no idea). The boss unit was too close to my core for me to do anything more than insult its mother before I lost.

**Comment by Shaneilenin** [comment]
@Anuken We tried to reload the save when this issue happened again on another game, and it seems that this fix it, the turrets started firing at the enemies again and they lost their invulnerability

**Comment by Anuken** [comment]
That's about what I expected, but it's unfortunate.

@Draco18s

> I had no turrets that far south, so I have no idea

Well, you have a lancer close to your core in the screenshot...

**Comment by Draco18s** [comment]
> Well, you have a lancer close to your core in the screenshot...

Ah I forgot about that one. I didn't see it fire, but it might've been responsible.

**Comment by ninjassifi** [comment]
No pattern. Might need some testing volunteers. I am not really up to it.. But If it is necessary I will be able to take some time.

**Comment by ninjassifi** [comment]
Also, Is this a campaign bug or does this also happen in custom games? I think that one of the bugfixes might have caused this problem.

**Comment by Anuken** [comment]
Previous reports show that it happens in custom games as well.

*Changed the title to indicate the fact that units are never actually invincible.*

**Comment by CornStarXL** [comment]
So what is the solution if this is happening in single player?

**Comment by Anuken** [comment]
If it's not going away after reload, then it's probably not this bug, and your turrets simply are not equipped to handle bosses. Scatters are not effective on boss armor, and parallax turrets deal practically no damage even to T1 units.

**Comment by 50275** [comment]
When units become impossible to hit (bullet phases through), they are still vulnerable to explosions.

**Comment by Shaneilenin** [comment]
Noticed that this bug occurs when the label "Out of sector time" appears in campaign, and lasts until "skip" button not pressed (alpha v106). But then it's still a question of why this happens in custom games.
 
![20200925173333_1](https://user-images.githubusercontent.com/60701433/94338475-ab6c0700-001c-11eb-9ff9-2071175fffbf.jpg)
![20200925173337_1](https://user-images.githubusercontent.com/60701433/94338477-b030bb00-001c-11eb-838d-ad2df8b250d3.jpg)

**Comment by ThaDaVos** [comment]
I've run into the issue multiple times today too - until know not been able to get further than ground zero as I keep running into the green walker units with lightning guns not being able to be killed - someone in discord pointed out that it may be because they have shields/force fields?

**Comment by Anuken** [comment]
> when the out of sector time thing happens

The thing is, that message should pause your game, and it does in every singleplayer scenario I've tested. Were you connected someone, or hosting?

**Comment by Shaneilenin** [comment]
> 
> Were you connected someone, or hosting?

I was hosting, when this happens to us.

**Comment by ThaDaVos** [comment]
I was hosting during the "end of sector time" thing, in the other cases a friend of mine hosted as I though my campaign was broken because everything except Ground Zero was locked

**Comment by Suggestedone9** [comment]
I had a similar issue when i was playing multiplayer with 3 teams, when the third team quit, their units could continue attacking but couldn't be killed

**Comment by notrealn** [comment]
I had a similar problem, but doing /sync fixed it. Me and my friend's bullets would suddenly start piercing through enemies and turrets would stop shooting, but only for one of us.

**Comment by Andre45450** [comment]
I also have a problem with units, when several waves pass, enemies appear and stand still, they can shoot but do not move.  Everything was solved by building a building near them.  I encountered such a problem on the mobile version
![Screenshot_2020-10-16-16-04-35-011_io anuke mindustry](https://user-images.githubusercontent.com/66055652/96261918-b980c800-0fc9-11eb-900f-47fadfe123c1.jpg)

![Screenshot_2020-10-16-16-03-59-922_io anuke mindustry](https://user-images.githubusercontent.com/66055652/96261993-d3baa600-0fc9-11eb-8c40-172029525ffd.jpg)

**Comment by Anuken** [comment]
> I also have a problem with units, when several waves pass, enemies appear and stand still, they can shoot but do not move. Everything was solved by building a building near them. I encountered such a problem on the mobile version

That's unrelated, and was already reported/fixed.

**Comment by abomb4** [comment]
I have encountered this problem in steam v105 before. The enemy cannot be attacked, the tower will not shoot, and the player's bullet will not hit the enemy.

This problem seems to be related to pausing; using v105, open a server, press space, and then this problem will occur; on the contrary, if we find a problem, let the host press space can solve the problem.

In the current version 108, this problem seems fixed, but if the host presses the space, there are still other problems.
as shown in the image below, the units will be stacked together.

After space pressed:
![图片](https://user-images.githubusercontent.com/6198193/96349831-b75f5c00-10e4-11eb-96c1-0d0af298cc85.png)

press again:
![图片](https://user-images.githubusercontent.com/6198193/96349833-b8908900-10e4-11eb-8de3-3a29e19b8e73.png)

**Comment by Anuken** [comment]
@abomb4 Thanks for finding that out! It appeared that pausing was indeed the cause of all these problems; one of the checks for pause state wasn't implemented properly, and incorrectly turned off certain game processes during multiplayer.
