### ISSUE TITLE
Campaign, first map behaving weird.

### ISSUE THREAD

**Issue by unknownzzzz** [Anuken/Mindustry#2584]
After 10 waves the waves stop coming and the top left indicator disappears.  no more waves or launch option.
![image](https://user-images.githubusercontent.com/71476513/93546741-79c6b200-f931-11ea-9a51-67fc15917b51.png)

I do see the launch option in the bottom right corner, but I had to go digging for it.  I first thought the game was broken.
![image](https://user-images.githubusercontent.com/71476513/93546832-b5617c00-f931-11ea-93a3-7231309dcf1d.png)
Should at least make it flash red, or turn red when able to launch.

**Comment by Anuken** [comment]
None of this is unintentional behavior.
