### ISSUE TITLE
Menu tiles not fixed.

### ISSUE THREAD

**Issue by unknownzzzz** [Anuken/Mindustry#2586]
When playing campaign the menu tiles are not fixed in place. 
Every time a new item and thus menu is unlocked the tiles shuffle.  This causes many miss clicks and greatly messes with the new-player learning curve and experience.
(The electric is where the water is, etc.)
(The Number shortcuts still work correctly and do not shuffle.)

![image](https://user-images.githubusercontent.com/71476513/93552542-a7662800-f93e-11ea-883b-87efc5d3b2ef.png)

VS

![image](https://user-images.githubusercontent.com/71476513/93552567-c2d13300-f93e-11ea-8bf5-01e1731bb102.png)

**Comment by Anuken** [comment]
Not a bug.
