### ISSUE TITLE
Error loading pixmap: Corrupt JPEG

### ISSUE THREAD

**Issue by Lazaro797** [Anuken/Mindustry#2588]
**Platform**: windows 7 32 bits

**Build**: Steam 105 v6.0 alpha.

**Issue**: loading screen gets glitchy and appears all black except the loading at the bottom, it shows all in red some words.

**Steps to reproduce**: i just downloaded the v6.0 alpha on steam i tried reinstalling it.

**Link(s) to mod(s) used**: no mods.

**Save file**: can't get past the loading screen.

**Crash report**: 
[crash-report-09_17_2020_21_53_11.txt](https://github.com/Anuken/Mindustry/files/5243599/crash-report-09_17_2020_21_53_11.txt)

[X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
could you supply a screenshot?

**Comment by Lazaro797** [comment]
> could you supply a screenshot?

![image](https://user-images.githubusercontent.com/63139345/93560277-06c43800-f93f-11ea-9405-dab5353b05c4.png)

**Comment by DeltaNedas** [comment]
>JPEG
did someone convert the atlas? Check that it's a PNG with file(1)

**Comment by Anuken** [comment]
This won't be fixed. I have no issues running the 32-bit windows version with WINE, and the error message doesn't make any sense. Either your data is corrupt or there's something unknown wrong with the version you have.
