### ISSUE TITLE
clearing game data clears tech tree but keeps all other campaign data

### ISSUE THREAD

**Issue by BassBro** [Anuken/Mindustry#2590]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
BE-9783
**Issue**: *Explain your issue in detail.*
i deleted my game data to try and redo campaign (i did save first) and when i entered campaign everything but my tech tree was the same
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
ran the game went into settings clicked on game data clicked 'save game data' and once my data was saved i clicked 'clear game data' it exited me out of the game, once i came back to play the campaign from scratch i entered campaign and saw that all my zones were still there and upon further investigation noticed that the only different thing was my empty tech tree.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none
**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is definitely Windows being stupid about save files "in use". Might be fixed with the next commit, might not.
