### ISSUE TITLE
Core sprite appears incorrectly when resizeing maps in the editor

### ISSUE THREAD

**Issue by DarkBrick** [Anuken/Mindustry#2591]
**Platform**: *Windows*

**Build**: *Alpha Build 105.*

**Issue**: *When you resize a map that has a core in it and then open the map in game, the core appears misplaced. It is technicaly in the same space but the sprite is in a wrong spot and only the shadow appears where it originaly was*

**Steps to reproduce**: *Create a map, Place a core, Resize the map, Edit in game*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/63005558/93597975-41b88100-f9bc-11ea-9b0e-aca589aceb57.png)

**Comment by Quezler** [comment]
does it occur only for core blocks, or every block that is larger than 1?
