### ISSUE TITLE
Visual glitches in star-system menu

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry#2592]
**Platform**: Windows

**Build**: v6.0+b.105.0 *(as well as several hundred previous BE builds)*

**Issue**: *Visual glitches in star-system menu.*

![изображение](https://user-images.githubusercontent.com/13190430/93612494-3d01c600-f9d8-11ea-8232-fb3c2841f8be.png)  
*Open picture in Full Screen*

**Steps to reproduce**: Just join into star-system menu and/not move the camera.

**Link(s) to mod(s) used**: *No mods.*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Remint32** [comment]
The problem is definitely not in my system/video card, because during this time I managed to change the laptop to a completely new desktop computer.

**Comment by Anuken** [comment]
Regardless of whether this is a problem with your system or not, it doesn't happen:
- on my PC
- on my phone
- on my other ancient phone

It won't be fixed.

**Comment by Remint32** [comment]
*understandable*

**Comment by Remint32** [comment]
### Recorded video
[2020-09-18 18-27-29.zip](https://github.com/Anuken/Mindustry/files/5246527/2020-09-18.18-27-29.zip)

**Comment by SummetDev** [comment]
I have similiar issues.
![image](https://user-images.githubusercontent.com/55251897/93634555-7bf44380-f9f9-11ea-85ef-04a3972df540.png)

**Comment by TheSlaylord** [comment]
Despite this is _not_ my screenshot, I regularly see those lines too both in my PC and phone
![unknown-34](https://user-images.githubusercontent.com/62336673/93634634-962e2180-f9f9-11ea-9f2c-4febddbb1c5e.png)

**Comment by Remint32** [comment]
![изображение](https://user-images.githubusercontent.com/13190430/93768578-42eae780-fc22-11ea-9b36-976b6f868b52.png)

**Comment by Remint32** [comment]
![изображение](https://user-images.githubusercontent.com/13190430/94307046-b40d0080-ff7c-11ea-8ec9-fc14f0c8f5f3.png)

**Comment by Anuken** [comment]
*still hasn't happened to me on any device by the way*

**Comment by Remint32** [comment]
![изображение](https://user-images.githubusercontent.com/13190430/95926607-5d4d5680-0dc5-11eb-90ee-df7824098c32.png)

**Comment by Remint32** [comment]
at the moment the problem is not observed

**Comment by Remint32** [comment]
and other players who reported it - too

**Comment by Anuken** [comment]
Yes, I found a certain setup that could reproduce it consistently and fixed it. The line overlay mesh was using uninitialized memory.
