### ISSUE TITLE
You can't upgrade T3 units to T4 units (naval units at least)

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2596]
**Platform**: *Android*

**Build**: *9784.*

**Issue**: *You can't upgrade T3 units to T4 units.

![Screenshot_2020-09-18-20-30-42.png](https://user-images.githubusercontent.com/60452545/93653601-fcae4200-f9ef-11ea-983e-6ff302a866c7.png)*

**Steps to reproduce**: *try to upgrade a naval unit to a T4 naval unit.*

**Link(s) to mod(s) used**: *none.*

**Save file**: not important but ill try to put it in the comments.

**Crash report**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Because they don't exist in your build.

**Comment by rodrigolitzius** [comment]
http://www.mediafire.com/file/bs5b5xyulizfqm8/0.msav-backup/file

**Comment by rodrigolitzius** [comment]
So what is this unit?
[]()http://www.mediafire.com/file/mbnujhhvq5jq16k/Screenshot_2020-09-18-21-02-37.png/file
