### ISSUE TITLE
Logic displays break at high fps

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2597]
**Platform**: Windows

**Build**: v6 alpha 105

**Issue**: when drawing things on a logic display with multiple processors it works fine at lower fps but when your fps is above 300ish they flicker and do other odd things.

**Steps to reproduce**: have a logic display hooked into more than one processor each drawing their own thing (in seperate colours) at high fps 

**Link(s) to mod(s) used**:no mods

**Save file**: not necessary

**Crash report**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> not necessary

It is **very much** necessary in this situation. How am I supposed to test this? I'm not going to waste my time making something that *sounds* like it's doing what you describe.
