### ISSUE TITLE
[Reupload] Logic displays break at high fps (This time with a save file)

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2598]
Platform: Windows

Build: v6 alpha 105

Issue: when drawing things on a logic display with multiple processors it works fine at lower fps but when your fps is above 300ish they flicker and do other odd things.

Steps to reproduce: have a logic display hooked into more than one processor each drawing their own thing (in separate colours) at high fps

Link(s) to mod(s) used:no mods

Save file: A mouse that you can move and click along with a box that you can drag

[ClickableMouseWithDragableBox.zip](https://github.com/Anuken/Mindustry/files/5248885/ClickableMouseWithDragableBox.zip)

Crash report: not a crash

**Comment by Anuken** [comment]
You have two processors clearing the display and flushing to it. With high FPS, the display is going to draw faster, so it won't wait for the commands of all CPU to finish before drawing, and thus it flickers. **Never drawflush from multiple CPUs**.

**Comment by Legomonster33** [comment]
without drawing from multiple cpus how do you draw separate objects on the same screen with different colours for each one?

**Comment by Anuken** [comment]
color r,g,b
draw object 1
color r2,g2,b2
draw object 2
