### ISSUE TITLE
Legs units legs go through the black area, but the unit can't move over it

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2599]
**Platform**: Windows

**Build**: Custom build, latest commit (8dd1c5f1f817329635cb6b3a8aa69003abc10d09)

**Issue**: Long legs units's legs go overtop of the black area which they can't go over, image: 
![image](https://user-images.githubusercontent.com/34169172/93655577-899dcf00-f9e1-11ea-999d-ec879160c2c1.png) If the it's supposed to be "super tall terrain" then the leg would literally be going through the terrain, if it is more like a "super deep pit" then the unit should have some method of being able to move over smaller gaps like this, though currently the unit is just blocked.

**Steps to reproduce**: Become toxopid, and walk into a smaller black zone on the map

**Link(s) to mod(s) used**: No mods used

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The leg movement is completely unrelated to the solidity of terrain. I'm not going to be doing physics simulations along with the IK to figure out where a leg should go.
