### ISSUE TITLE
[TODO] Warn player in Editor if enemy path is invalid

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#26]
![image](https://user-images.githubusercontent.com/30189017/34219625-d58a02ae-e57f-11e7-8889-61a460a91527.png)

**Comment by Anuken** [comment]
Your map has no way for the enemies to reach the spawnpoint, so it crashes. I should probably fix that.

**Comment by Luxray5474** [comment]
I see. I corrected the map now and it should work just fine :P

**Comment by Anuken** [comment]
How about if I just make enemies not move at all? Warning the player in the editor would be very resource- intensive, as I would need to load the world and set up pathfinding context.
