### ISSUE TITLE
T5 naval unit fills whole air build limit

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#2601]
**Platform**: Windows

**Build**: BE 9795

**Issue**: T5 naval unit builds Flares up to the 8/8 limit, blocking air production entirely.

**Steps to reproduce**: 
1. Build T5 naval unit;
2. Wait for it to build 8 Flares;
3. Try to build another Flare in air factory.

**Save file**: (file sent in #bots) https://discordapp.com/channels/391020510269669376/414179246693679124/756699263089770617
![image](https://user-images.githubusercontent.com/55051135/93656880-7a953c00-fa36-11ea-97ec-ef88cbab217c.png)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug.
