### ISSUE TITLE
Overlapping cached blocks graphical bug

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2602]
**Platform**: *Windows*

**Build**: *9783*

**Issue**: *See for yourself.*

![image](https://user-images.githubusercontent.com/58885089/93657135-ded1f300-fa6a-11ea-9928-a1194126f17d.png)

**Steps to reproduce**: *Place shhader floors next to each other.*

**Link(s) to mod(s) used**: *null*

**Save file**: *Unrelated.*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
