### ISSUE TITLE
Units inside Mega do not count towards unit limit

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#2603]
**Platform**: Windows

**Build**: BE 9796

**Issue**: Units picked up by Mega do not count towards unit limit. Attempting to drop units over the limit will mark them with a warning sign. Multiple Megas can hold units, as shown on a screenshot.

**Steps to reproduce**:
1. Build Mega and low tier ground units;
2. Control Mega and pick up those units;
3. Wait for ground factory to produce units and hit unit limit;
4. Drop units from the Mega.

**Video demo file**: https://cdn.discordapp.com/attachments/414179246693679124/756731493694308421/mega-unit-cap-cargo.mp4
![image](https://user-images.githubusercontent.com/55051135/93658935-cd77ef00-fa48-11ea-87b2-efd684cf1a8f.png)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Units picked up by Mega do not count towards unit limit.

Why would they? It's the same as being in a payload conveyor.

**Comment by XEN0PHIL** [comment]
> Why would they? It's the same as being in a payload conveyor.

Because those were built and they stepped on the ground as an active unit. They should remain active in game's eyes when put in Mega.
Imagine if you carry a unit somewhere and it becomes inactive when you drop it.

**Comment by Anuken** [comment]
> and they stepped on the ground as an active unit

And the moment they get put back on a conveyor or in a mega, they cease to count. I don't see your logic. The units do not move or shoot, just like they don't move or shoot on conveyors - therefore, they do not count.

**Comment by XEN0PHIL** [comment]
> and the moment they get put back on a conveyor or in a mega

You are missing my point. Carrying units somewhere as an **attack tactic** does not work because of this system, you will just **drop an idle dummy** for enemies to shoot.
What's the problem in counting units in Mega as active ones? It will not affect throwing units back on conveyor in any way as they will cease to count.

**Comment by Anuken** [comment]
> Carrying units somewhere as an attack tactic does not work because of this system, you will just drop an idle dummy for enemies to shoot.
> What's the problem in counting units in Mega as active ones?

Balance problems such as this are irrelevant. The issue tracker is for reporting **bugs**, which this is not.

**Comment by iccor56** [comment]
what is the unit limit? how many of a  unit can i build?

**Comment by Quezler** [comment]
> what is the unit limit? how many of a unit can i build?

its based on the amount of cores you have and what size they are

**Comment by iccor56** [comment]
Where can I find the numbers?
