### ISSUE TITLE
Ships leave water trail on land.

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry#2606]
**Platform**: Windows

**Build**: Bleeding Edge 9796

**Issue**: Sailing at the edge of land with larger ships, most noticeably, the tier 5 one, leaves a water trail on land. In this image, it's sand, but it applies to all land types.

**Steps to reproduce**: 

- exist
- open a game with water next to land
- procrastinate for tier 5 ship
- sail it next to land, then sharply turn away from the land.
- voila.

**Link(s) to mod(s) used**: No mods.

**Save file**: GitHub doesn't support .msav file types

**Crash report**: Not a crash.

**Image thing**

![image](https://user-images.githubusercontent.com/65382389/93662397-5f99ea80-fa7d-11ea-8260-38d556daa251.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no good fix for this.

**Comment by iLagSoUhax** [comment]
So you're just going to leave it there?

**Comment by Anuken** [comment]
yes

**Comment by iLagSoUhax** [comment]
bit odd, but okay.
