### ISSUE TITLE
Armored Conduit refuses to conform to its identity of being a conduit

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#2607]
**Platform**: *Windows*

**Build**: *9795*

**Issue**: *When connected to even-sized blocks, armored conduits refuse to work, unless directly connected to its Building. See below:*

![image](https://user-images.githubusercontent.com/58885089/93662793-aac3f580-fa9d-11ea-8c48-b7c0e4deb6ea.png)

**Steps to reproduce**: *See above; Working conduits are marked with plastanium walls, others with copper.*

**Link(s) to mod(s) used**: *null*

**Save file**: *Irrelevant, any save file does that.*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XEN0PHIL** [comment]
Did you try connecting those armored conduits to anythig? They are leaking less than pulse conduits.
