### ISSUE TITLE
Misc bugs involving undoing deleting blocks in the editor

### ISSUE THREAD

**Issue by DarkBrick** [Anuken/Mindustry#2608]
**Platform**: *Windows*

**Build**: *Alpha 105*

**Issue**: *When you delete a block in the editor and then undo the action the block either appears in the black team or not at all*

**Steps to reproduce**: *Place blocks in the editor, remove them with right click, press undo*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Excavator987** [comment]
this is linked with #2566 - the redo function does not work as intended it seems

**Comment by Anuken** [comment]
Duplicate.
