### ISSUE TITLE
Much robots

### ISSUE THREAD

**Issue by PaintedCat** [Anuken/Mindustry#2611]
**Platform**: *Linux*

**Build**: *alpha build 105*

**Issue**: *Much robots when you lost the base*

**Steps to reproduce**: *1)go to the uncaptured place. 2) lost base on this place. 3)go to step 1.*

**Steps to repair**:*1)lost base. 2)exit the game. 3)start game again*

**Link(s) to mod(s) used**: *No mods.*
![Screenshot_20200919_121516](https://user-images.githubusercontent.com/48541405/93664331-ba7c1380-fa76-11ea-91df-3960a9b2c553.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
what

**Comment by XEN0PHIL** [comment]
Translation: there's A LOT of units in waves when coming back to a zone where you've lost your core.
Note 165 enemies at Wave 2.

**Comment by PaintedCat** [comment]
XEN0PHIL,thanks.

**Comment by Anuken** [comment]
Not a bug.
