### ISSUE TITLE
Multipalayer server crash when someone break a block

### ISSUE THREAD

**Issue by ethandudu** [Anuken/Mindustry#2613]
**Platform**: *Windows*

**Build**: *105*

**Issue**: *When someone break a block in multiplayer the server crash*

**Steps to reproduce**: *break a block*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *No save*

**Crash report**: *[log-0.txt](https://github.com/Anuken/Mindustry/files/5249951/log-0.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This has nothing to do with breaking blocks. You are running a server on a pi or other ARM device, which is not supported.
