### ISSUE TITLE
Invornable units

### ISSUE THREAD

**Issue by bartox1** [Anuken/Mindustry#2614]
**Platform**:Windows

**Build**: Steam Build 105

**Issue**: Enemies become invornable after  6-8 waves (idk witch wave exacly becouse it was a large custom map "BoxFort").
I also noticed that they (enemy robots "Dagger") lost collision between them and turrets ("Hail","Salvo","Arc") stop targeting them. Also i was using "Gamma" and the projectiles where homing on them but not doing any damage. Beside that enemies preserve normal behavior , damaging blocks and shields.
**Steps to reproduce**: This bug is random. It happend on hosted private server at 6-8 waves
**Mods**:Map "BoxFort" https://steamcommunity.com/sharedfiles/filedetails/?id=1876602615&searchtext=box
I know that issue happend allredy but i wanted to clarify that bug is not related to "Ground zero" in campain.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bartox1** [comment]
I just recreated th bug scond time ia a row this time on wave 4. map"BoxFort"

**Comment by bartox1** [comment]
I was able to recreate that bug with my units in sandbox.
![20200919180757_1](https://user-images.githubusercontent.com/66919173/93671561-507a6300-faa4-11ea-95b8-2d3db9a6bc52.jpg)
![20200919181032_1](https://user-images.githubusercontent.com/66919173/93671567-5bcd8e80-faa4-11ea-8c28-e25d7ec47ccc.jpg)

**Comment by Anuken** [comment]
Discuss in #2582
