### ISSUE TITLE
Mega dont drops block when dies

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry#2617]
**Platform**: Windows

**Build**: 9810

**Issue**: Mega with block, when gets killed, dont drops block making lose stuff if you have cointainer

**Steps to reproduce**: take block with mega, die

**Link(s) to mod(s) used**: none

**Save file**: possible everywhere

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Esnardo** [comment]
The same thing happens if you carry items like from a container. I don't think it's a bug, I think of it more like the enemies destroy the block along with you.
