### ISSUE TITLE
Auto update not working on Android BE build.

### ISSUE THREAD

**Issue by Ignacy-s** [Anuken/Mindustry#2618]
**Platform**: *Android*

**Build**: *android bleeding-edge 9810*

**Issue**: *Auto update not working on Android.*
The desktop BE build has both auto-updates and a menu button to check for updates.
Please implement at least the *check for updates* button if it's possible.
NewPipe (FOSS youtube client) does a pop-up with info about a new update and when update button is clicked it opens a link to the latest .apk in the browser (which downloads the latest .apk).
Maybe that's doable?

**Steps to reproduce**: *Played on a BE server from android phone. Server restarted to update and didn't let me in again. The client didn't update and there is no option to check for updates.*

P.S. Love the game 😁 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a feature request.

**Comment by bafudus** [comment]
Yey
