### ISSUE TITLE
200 enemies at round 3

### ISSUE THREAD

**Issue by Medicinexs** [Anuken/Mindustry#2619]
**Platform**: *windows*

**Build**: alpha v6 105

**Issue**: *200 enemies at round 3*

**Steps to reproduce**: *go to campaign, get graphite and hail as fast as you can, skip first round.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---
![unknown](https://user-images.githubusercontent.com/67633347/93686853-57749600-fae3-11ea-8295-a783abdea328.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DarkBrick** [comment]
Maybe specify the tile location of where this happened?

**Comment by Anuken** [comment]
Not a bug.

**Comment by Esnardo** [comment]
> Not a bug.

Damn. Savage.

**Comment by EarthasaurusRex** [comment]
This isn't a bug. If you explore another area, save and quit, then go into another area, that previous area is still explored and enemies will still "spawn". Once the core in that area is destroyed, the enemies start spawning in the area you are currently in. If you explored a TON of areas, you will get a ton of enemies.

I learned this the hard way.
