### ISSUE TITLE
build is something wrong

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#2625]
**Platform**: "/Windows/*

**Build**: *105*

**Issue**: *
![제목 없음179](https://user-images.githubusercontent.com/61054554/93694888-2ed4b680-fb4c-11ea-8e2e-06768aca4b81.png)

![제목 없음180](https://user-images.githubusercontent.com/61054554/93694902-53309300-fb4c-11ea-8afc-ae98492f7d2f.png)
there was core-release.jar instead mindustry.jar in folder "libs".
core-release.jar doesn't act as mindustry
*

**Steps to reproduce**: *little code modified such as adding new button in dialog*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Blockzilla101** [comment]
look in desktop/build/libs instead of core/build/libs

**Comment by imreallybadatnames** [comment]
bruh
