### ISSUE TITLE
Mega AI

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#2631]
**Platform**: Android

**Build**: alpha 105

**Issue**: Megas shooting air, air units out of control and flying too fast, enemies deal no damage

**Steps to reproduce**: 
1. Make Mega,
2. Make more air units
3. Make more buildings
4. Make lags
The bug will start when the Mega starts shooting air
5. Control the Mega to stop the bug

![Screenshot_2020-09-20-23-59-49-45](https://user-images.githubusercontent.com/70744599/93717926-fe6c3700-fba2-11ea-8a26-c03993f96f8b.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
All of these are already fixed.

**Comment by D-player1** [comment]
Does that mean i need to update the alpha?

**Comment by Anuken** [comment]
There is no update in the alpha, only in BE.
