### ISSUE TITLE
Turret ammo counter don't fill completly

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2640]
**Platform**: *Windows*

**Build**: *9834*

**Issue**: *The ammo counter on some turrets is not completely full even if the turret is fully supllied*
![Screenshot 2020-09-17 211025](https://user-images.githubusercontent.com/57239116/93753148-f989a080-fbff-11ea-8ef4-99f991564006.png)

**Steps to reproduce**: *Build a turret next to a drill in Sandbox and wait a bit.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XEN0PHIL** [comment]
Not a bug, it's related to max ammo and ammo multiplier. For example 48/50 ammo with 4x ammo multiplier

**Comment by CaptainCosmotic** [comment]
Since you can't mix resources in turrets, I think the bar should be calculated 48/48 and be full.

**Comment by Shawak** [comment]
Absolutely not, this is as good as it gets.

**Comment by Anuken** [comment]
> you can't mix resources in turrets

You can.
