### ISSUE TITLE
Campaign multiplayer is not fixed

### ISSUE THREAD

**Issue by Shaneilenin** [Anuken/Mindustry#2641]
**Platform**: Android/Windows

**Build**: BE 9834

**Issue**: Campaign tech unlocks is not synced between players in multiplayer. When you join another player in campaign mode, you can only build things that correspond to the progress of **your** campaign(not hosts). 

**Steps to reproduce**: Join to another player's campaign, who has progress in tech tree different than yours. You will be able to build things than isn't researched by host yet if you researched it in your campaign, and the opposite goes too. (I used 2 different
 copies of game on pc and phone)

**Link(s) to mod(s) used**: No mods.

**Save file**: ---

**Crash report**: ---

![Скриншот 21-09-2020 153718](https://user-images.githubusercontent.com/60701433/93766852-493c8c00-fc41-11ea-8c73-f406fac71db3.jpg)
![bCUvb0SoAqc](https://user-images.githubusercontent.com/60701433/93767457-41c9b280-fc42-11ea-828a-36f4a3fbac4d.jpg)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Campaign tech unlocks is not synced between players in multiplayer. 

It wasn't supposed to be. I may have briefly considered it in Trello, but instead opted for the simpler option of doing unlocks the same way 5.0 had.

**Comment by Shaneilenin** [comment]
> doing unlocks the same way 5.0 had.
>
Ok. I made some more tests and now seems I understand how it should work at 6.0(and it works). But one problem remained - in the campaign on Android, when player is connect to someone or host game, there is no button to access the technology tree anywhere.

**Comment by Anuken** [comment]
> [when joining a server] there is no button to access the technology tree anywhere

There is when *I* try it.

**Comment by Shaneilenin** [comment]
Umm.. Ok. Just updated to lastest BE. Checked it again. Maybe it just me, but I dont see it anywhere. :D
![3cSUNoPS4-Y](https://user-images.githubusercontent.com/60701433/93794192-fd4e0f00-fc61-11ea-816f-205ef398421f.jpg)
![fG_mTbf6OY8](https://user-images.githubusercontent.com/60701433/93794204-0048ff80-fc62-11ea-822f-c74de78ca737.jpg)
But in SP it in its place.
![o7JSCIMMiYo](https://user-images.githubusercontent.com/60701433/93794619-8107fb80-fc62-11ea-8b32-14b18fb74d58.jpg)

**Comment by Anuken** [comment]
That's because, on mobile, you have a chat button instead. Play on desktop.
