### ISSUE TITLE
Fungal Pass mech factory missing

### ISSUE THREAD

**Issue by Lukas0374** [Anuken/Mindustry#2642]
**Platform**: Windows

**Build**: Bleeding-edge build 9834

**Issue**: Old unit factory isn't replaced with new factory on Fungal Pass map in campaign, so there is no factory.

**Steps to reproduce**: I just launched to Fungal Pass and there was missing mech factory.

**Link(s) to mod(s) used**: No mods.

**Save file**:  [21.9.zip](https://github.com/Anuken/Mindustry/files/5255595/21.9.zip)

![screenshot-1600693857574](https://user-images.githubusercontent.com/71627470/93772493-2ac59900-fc1f-11ea-8034-efa9e2709efd.png)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There isn't suppose to be. None of the preset maps are done.
