### ISSUE TITLE
Air support units resupply point bug

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry#2644]
**Platform**: */Windows/*

**Build**: *9846 alpha*

**Issue**: *Use unit that picks up blocks, take point, and its gone. This also resets other blocks/unit you have.

**Steps to reproduce**: *Have a map, ammo disbabled, and with resupply points on map placed by editor.
Take unit that picks blocks.
You can take other things before taking point
Take point
You drop nothing after pressing button*

**Link(s) to mod(s) used**: *none*

**Save file**: *No need*

**Crash report**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. You can't place resupply points, so you can't drop them either.
