### ISSUE TITLE
impossible to apply a litle mods

### ISSUE THREAD

**Issue by davlucas** [Anuken/Mindustry#2645]
**Platform**: Linux Manjaro

**Build**: 6.0 Build 105 - Alpha

**Issue**: Old mods does not load, so I created a new one :+1: 

mod.hjson

> name: "david-mod"
> displayName: "[orange]David[gold] Mod" //what displays in the mod selection menu
> author: "Anuke"
> description: "A simple mod."
> version: "0.1"
> minGameVersion: "105"

With a simple turret :+1: 

> type: DoubleTurret
> name: Lethal Turret
> description: LethalTurret
> health: 200
> size: 1
> reload: 1
> range: 5000
> ammoUseEffect: shellEjectSmall
> inaccuracy: 30
> rotatespeed: 12
> 
> ammo: {
>   copper: {
>     speed: 5000
>     damage: 9999
>     bulletWidth: 20
>     bulletHeight: 30
>     ammoMultiplier: 15
>   }
> }
> requirements: [
>   copper/1
> ]
> category: turret
> research: duo
> 

Loading mod works fine, issue when trying to use it with a NPE:

> AL lib: (WW) FreeDevice: (0x7f1e20b6ef80) Deleting 4 Buffer(s)
> java.lang.NullPointerException
>         at mindustry.world.blocks.ConstructBlock.constructed(ConstructBlock.java:110)
>         at mindustry.world.blocks.ConstructBlock$ConstructBuild.construct(ConstructBlock.java:228)
>         at mindustry.gen.BuilderMinerUnit.update(BuilderMinerUnit.java:1089)
>         at mindustry.entities.EntityGroup.each(EntityGroup.java:66)
>         at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
>         at mindustry.gen.Groups.update(Groups.java:52)
>         at mindustry.core.Logic.update(Logic.java:378)
>         at arc.ApplicationCore.update(ApplicationCore.java:36)
>         at mindustry.ClientLauncher.update(ClientLauncher.java:151)
>         at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
>         at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
>         at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
>         at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Steps to reproduce**: *create a simple mod, Load the mod, try to use it*

**Link(s) to mod(s) used**: *check attachment*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *java.lang.NullPointerException
	at mindustry.world.blocks.ConstructBlock.constructed(ConstructBlock.java:110)
	at mindustry.world.blocks.ConstructBlock$ConstructBuild.construct(ConstructBlock.java:228)
	at mindustry.gen.BuilderMinerUnit.update(BuilderMinerUnit.java:1089)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:66)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:57)
	at mindustry.gen.Groups.update(Groups.java:52)
	at mindustry.core.Logic.update(Logic.java:378)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
[David-master_1.zip](https://github.com/Anuken/Mindustry/files/5257449/David-master_1.zip)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
`DoubleTurret` is not a block type that exists.

**Comment by davlucas** [comment]
Hello ,thanks for quick reply, well it was ok in the previous release. I cannot find mod for this release, the famouse Example one 
Well, After some modification, I cn't load it, i'll try to set the actual error (instantation error) and keep you posted

**Comment by Anuken** [comment]
Don't try to make mods in 105 yet. Wait for documentation.

**Comment by GlennFolker** [comment]
You could try modding in 105 only if you really know what you're doing and pretty much understand Mindustry's codes

**Comment by davlucas** [comment]
ok, thanks for your quick reply, i alwys apprecite it. So I'll wait
