### ISSUE TITLE
Corvus legs appear through the blank part in it's body

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2650]
**Platform**: Windows 10

**Build**: Custom build, latest commit

**Issue**: The legs on the corvus show through the blank part, image: 
![image](https://user-images.githubusercontent.com/34169172/93843291-aabb2580-fc56-11ea-9149-babda8a25e46.png) 
It looks kind of messed up, especially since the middle of it is empty, so it looks as if it's mounted on nothing, and just sitting there somehow.

**Steps to reproduce**: Spawn a corvus and look at it

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by imreallybadatnames** [comment]
enterprise secrets

**Comment by Voz-Duh** [comment]
@Syncinus this not bug /-/

**Comment by Anuken** [comment]
They're supposed to.

**Comment by Syncinus** [comment]
![image](https://user-images.githubusercontent.com/34169172/93888487-4c696380-fca5-11ea-87a5-a4feff4bb7c7.png)
This looks really bad though, shouldn't it have some kind of base?

**Comment by Anuken** [comment]
"it looks bad" is not a bug.
