### ISSUE TITLE
6.0

### ISSUE THREAD

**Issue by Wencelsav** [Anuken/Mindustry#2652]
**Platform**: *Windows*

**Build**: *9844.*

**Issue**: *launch pad launches items but in other locations they not appear *

**Steps to reproduce**: *build launch pad and full load resources*
**Link(s) to mod(s) used**: *without any mods*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not really supposed to.
