### ISSUE TITLE
Weird behavior of T4 support mech

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2653]
**Platform**: I tried it on PC, Windows, and I assume it exists everywhere.

**Build**: 9857

**Issue**: Acquire a Tier 4 support mech. Fire the beam at something. Press shift to fly. The beam will still exist, and will wobble a lot. You can't turn around then. If you normally fly, and try to shoot, nothing happens.

**Steps to reproduce**: As said before, fire the beam with T 4 support mech and try to fly.

**Link(s) to mod(s) used**: No mods

**Save file**: Any file

**Crash report**: 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I see nothing strange here.

> The beam will still exist, and will wobble a lot.

It always wobbles a lot?

> You can't turn around then.

You can barely turn around when firing regardless of whether you are flying or not.

>  If you normally fly, and try to shoot, nothing happens.

This is how every flying mech works.

**Comment by Highfire1** [comment]
Here's a gif of it happening, seems the closer your cursor is to the mech the worse the wobble gets
![ezgif-7-e16b559576b1](https://user-images.githubusercontent.com/45698812/93950472-6d0ed900-fcf8-11ea-96d6-3a725ab038e8.gif)
