### ISSUE TITLE
Super fast bulets

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2654]
![Bug](https://user-images.githubusercontent.com/53085797/93889078-11891f00-fce9-11ea-8fa9-71ed6338a74d.png)

**Platform**: Windows, and any other where you control shooting

**Build**: 9857

**Issue**: When you fly and fire at the same time, some bullets fly at the normal speed of a bullet + speed of the ship. Some bullets will go like 5 times faster. It will work only in Stained Mountains for some reason. It won't work on custom maps.

**Steps to reproduce**: Get an alpha ship. Stop completly. Accelerate in any direction. Once you get top speed, start shooting in the same direction you go. It might not work every time though, it takes a few attempts. The speedy shot at the picture is fired *before* the lower range shots.

**Link(s) to mod(s) used**: No mods

**Save file**: Any file

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheSlaylord** [comment]
bullets inherit shooter's speed normally, so i can't call it a bug

**Comment by BorisA11** [comment]
Normaly, it's bullet speed = base bullet speed + speed in that direction. The bug is when the bullet goes 10 times faster than the shooter speed + bullet speed, resulting it flying out of screen in a tenth of a second.

**Comment by BorisA11** [comment]
Aparently, it only happens in Stained Mountains

**Comment by TheSlaylord** [comment]
> Aparently, it only happens in Stained Mountains

it can't happen only in a single sector
