### ISSUE TITLE
Unloader on turret didn't works

### ISSUE THREAD

**Issue by zyropz** [Anuken/Mindustry#2655]
**Platform**: Android

**Build**: BE 9857

**Issue**: unloader didn't unload

**Steps to reproduce**: uhh when I'm trying to unload from turrets because no space to put conveyor/when unload weapons(only in weapons)

**Save file**: idk how to share it

---

[X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![Uploading Screenshot_2020-09-22-16-40-23-639_io.anuke.mindustry.be.jpg…]()
![Uploading Screenshot_2020-09-22-17-40-46-494_io.anuke.mindustry.be.jpg…]()

**Comment by D-player1** [comment]
You can't
