### ISSUE TITLE
Mega AI

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry#2656]
**Platform**: *Android/iOS/Mac/Windows/*
Seen on Linux, I don't know if it could happen on another platform, but I suspect it will.
**Build**: *The build number under the title in the main menu. Required.*
Alpha build 105
**Issue**: *Explain your issue in detail.*
If you build a Mega on an online server, (I think) It's AI bugs out and lags the server
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Build a Mega in an online server. The more Megas, the worse the lag.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
Online server, no save file.
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rmperkow** [comment]
How do I make it smaller?

**Comment by Anuken** [comment]
duplicate
