### ISSUE TITLE
Buggy audio

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry#2657]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux (Debian)
**Build**: *The build number under the title in the main menu. Required.*
105, may happen in older
**Issue**: *Explain your issue in detail.*
Mindustry didn't switch to the right audio device, and it took a bunch of terminal commands to make it work
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Launched Mindustry on Linux with multiple audio devices and it chose the wrong one.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Program issue, no mods
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
Program issue, no save file
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rmperkow** [comment]
I searched this time.

**Comment by rmperkow** [comment]
I can't remember the terminal commands, but it took quite a few.

**Comment by Anuken** [comment]
Won't fix.
