### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Surviavlist** [Anuken/Mindustry#2658]
**Platform**: *Android*

**Build**: *Alpha 105*

**Issue**: *T1 Air units and enemies are very speed*

**Steps to reproduce**: *Play*

**Link(s) to mod(s) used**: *-*

**Save file**: *-*

**Crash report**: *-*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DarkBrick** [comment]
They are weak and mobile units, they are meant to be speedy. Also this is a suggestion to change their speed, how fast they are currently is not a bug but an intended feature

**Comment by Anuken** [comment]
Duplicate.
