### ISSUE TITLE
Multiplayer crashing me and my friends game

### ISSUE THREAD

**Issue by Star98Blazer** [Anuken/Mindustry#2659]
**Platform**: *Windows 10*

**Build**: *steam build 105.*

**Issue**: *When i try to join my friend it gives a crash with EOFException also if I create a game and my friend attempts to join me he gets a bufferunderflow error.*

**Steps to reproduce**: *Get a steam invite from a friend then join then crash.*

**Crash report**: *[crash-report-09_21_2020_15_05_27.txt](https://github.com/Anuken/Mindustry/files/5262444/crash-report-09_21_2020_15_05_27.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X]
**I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Is your friend running 105 as well?

**Comment by Star98Blazer** [comment]
yep he is

**Comment by Anuken** [comment]
Send me screenshots of both your main menus, and his crash log.

**Comment by Star98Blazer** [comment]
Will do when he gets back online

**Comment by Star98Blazer** [comment]
well I discovered that my friend had the wrong version so yea

**Comment by Anuken** [comment]
~~yep, that's why I asked~~
