### ISSUE TITLE
Mega AI Lags

### ISSUE THREAD

**Issue by A5TR0spud** [Anuken/Mindustry#2661]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required.*
Steam Build 105
**Issue**: *Explain your issue in detail.*
Whenever the Mega is present and not controlled by a player in multiplayer, the game starts to lag. The player gets teleported back and forth, and it becomes a laggy mess.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just build a Mega in multiplayer. It's that easy.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
N/A
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
duplicate

**Comment by A5TR0spud** [comment]
Really? huh.. I didn't find any..

**Comment by RogueRedHawk** [comment]
Duplicate of #2631
