### ISSUE TITLE
build: 9871

### ISSUE THREAD

**Issue by Perrito317** [Anuken/Mindustry#2663]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
h

**Comment by Perrito317** [comment]
hm

**Comment by summetdev** [comment]
h

**Comment by Perrito317** [comment]
ray

**Comment by Perrito317** [comment]
sorry
