### ISSUE TITLE
Collection of Issues in V6 

### ISSUE THREAD

**Issue by CornStarXL** [Anuken/Mindustry#2666]
**I accidentally posted before writing and it was closed before I finished editing. I do apologize for that, I'm new to github.**

**Platform**: *Windows*

**Build**: *V6.105*

**Issue**: *The one that made me make this, on desolate rift, the first lich is immortal. It stayed at my front line for minimum of 5 waves taking direct fire from more than 10 scatters and 10 of the paralax. 
Next, resources going into the core are not being counted; blast compound was counting between 1 in 10 and 1 in 20, I had very little production of this so I was able to notice and count, can not verify any others. 
The resource pool seems the be broken. I open the research and it gives me the values that are currently in the core, I use this amount in its entirety, then close and reopen, then the values are full again ignoring what's in the core. It's not infinite, I let it run for a few hours (using launchers) to try and get tech. I saw the notes on the point of it is not to have some massive pool to pull from, but if that's the case then I'm not sure on the usefulness of the launchers. With these values, 1 mil in the case of the core, personally, I don't like it. I would rather have the large pool.
Lastly, I couldn't find a research tree for v6 to verify where it actually is, but I don't know why you can unlock any of the reactors before cryo fluid, I don't know where it is in the tree but I have almost everything that doesn't require alloy and still don't see it.In fact, I don't know why we aren't able to see what the tree is (I know in the development phase that this may be prohibitive, but with these larger research costs, attempting to guess really reduces the game play experience.
I was wrong about that being last, I don't think that the parallax is actually damaging units. Additonally, most flyers tended to sit at the current edge of this weapons range to fire on the defensive line so they rarely had the opportunity to engage *

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *I can give the file if needed, but I'm not sure which is the correct one in the new state as I think V5 files are there too.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [XX] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Actually, I don't see the closed section so I may have only seen open issues, if so, my bad.

**Comment by CornStarXL** [comment]
There is also a resource issue where launching the core only counts toward what you have currently, and some resource values are not actually set at ), ie, I might have to ask for 7213 copper to get 9000.

**Comment by Anuken** [comment]
1. Duplicate issue.
2. Desync, use /sync (if you're in singleplayer, that doesn't make any sense and nobody has been able to reproduce anything like it)
3. Honestly I can't tell what you're trying to describe, and without knowing your game state it's impossible to tell if you're misunderstanding the mechanics or not. If it were an obvious issue, I would have seen it during testing of the tech tree.
4. Parallaxes do deal damage, just not a lot. Damage is not their purpose.
5. The cost displayed include **cost of your core**, not just what you're launching with.

**Comment by CornStarXL** [comment]
It is a single unit rather than all.

This is single player.

To rephrase, I am unsure as to why you don't unlock cryo fluid before the reactors.

I misinterpreted the damage.

That's not clear, nor an intuitive way of doing it.
