### ISSUE TITLE
Bricked multiplayer server Via Mega unit

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#2667]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows, multiplayer

**Build**: *The build number under the title in the main menu. Required.*

BE-9873

**Issue**: *Explain your issue in detail.*

Whatever this jumbled mess is. Was on the ECAN pvp server running the BE builds. I made a mega and then tried to pickup a T2 spider (im sorry i dont know its name) that was currently standing ontop of walls. The server had to be manually gameovered. once gameover occured the server was fine.

My teammate and i were both controlling the spider every so often to move it into a better position to break scrap walls, with a command center on idle. I picked it up intending to upgrade it.

![Screenshot_1](https://user-images.githubusercontent.com/31638088/93951316-35595e80-fd03-11ea-9422-77ea393ee502.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Be on a multiplayer server. unsure if a local game will do the same thing, make a Mega, and make a T2 spider, pickup the spider when it is ontop of an opponents teams walls.

_why do i keep finding bugs with mega?_

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Esnardo** [comment]
> why do i keep finding bugs with mega?
because mega be buggy

**Comment by Anuken** [comment]
I have no such problem, multiplayer or not.

**Comment by potatoisagender** [comment]
red is a griefer

**Comment by Anuken** [comment]
Problem seems to have been caused by a different environment on Travis CI building a server and client that differ in generated code for whatever reason. Update.
