### ISSUE TITLE
Phase conduits do not show the correct speed of items flowing through them

### ISSUE THREAD

**Issue by Cyastis** [Anuken/Mindustry#2671]
**Platform**: *Windows*

**Build**: *105 (steam)*

**Issue**: *Phase conduits do not show the correct speed of items flowing through them.*

**Steps to reproduce**: Step 1: place two phase conduit blocks and link them and power them.
Step 2: Place a conveyor, then an item source on the input side (and select some item)
Step 3: Click the first phase conduit block and observe that it says 25 to 30 of the item are flowing through when in fact 0 are flowing through since it is stopped (in fact, it seems impossible for it to display any number besides 25 to 30)

**Expected behavior:** I expect it to display 0 per second, just like a stopped/blocked conveyor

**Link(s) to mod(s) used**: *N/A*

**Save file**: *Works on any*

**Crash report**: *N/A*
![image](https://user-images.githubusercontent.com/32472410/93956934-85f8a800-fd53-11ea-8c81-fdb133b5713f.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by potatoisagender** [comment]
bridge
