### ISSUE TITLE
Pathfinding doesn't consider slag as dangerous liquid

### ISSUE THREAD

**Issue by TriPartiedLand** [Anuken/Mindustry#2672]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *BE 9885*

**Issue**: 
Pathfinding doesn't consider slag as dangerous liquid despite its burning & killing the naval units in mere second
![cursed](https://user-images.githubusercontent.com/71248702/93959500-1a193e00-fd59-11ea-8654-bc9869c22f5f.png)

**Steps to reproduce**: 
- make attack map with many liquid
![messymap](https://user-images.githubusercontent.com/71248702/93959671-6f554f80-fd59-11ea-87a3-f01bd6200111.png)
- make naval factory
- wait until its start using slag as a path

**Save file**: [map.zip](https://github.com/Anuken/Mindustry/files/5265321/map.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by here-be-username** [comment]
As far as think, this issue isn't just limited to naval units (may be fixed already though; IDK). I've seen (in the past) ground units walking into slag and dying.
