### ISSUE TITLE
Factory blocks have low health on campaign maps

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2674]
**Platform**: Any

**Build**: All bleeding-edge v6 builds

**Issue**: On maps that have factory blocks already built when you land, their HP is lower than normal, they are damaged. This happens both to your factory blocks, as well as enemy's. The procedually generated sectors do not have such issues. The maps that have this are Ruinous shores (the kiln next to solar battery), Fungal pass (all graphite presses), probably any other attack sector that existed in old v5 campaign.

**Steps to reproduce**: Land in Fungal pass, since it's the first sector to have this bug. See the graphite press under the core. It will have around 1/3 of normal HP. Same for enemy presses, kilns and probably other things.

**Link(s) to mod(s) used**: No mods

**Save file**: Any campaign

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Their max health was increased, so old ones appear damaged.
