### ISSUE TITLE
Container is uncoloured when building

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2677]
**Platform**: Android 

**Build**: 9864

**Issue**:

Container doesn't have team colour when building.
Probably happens for cores as well.

**Steps to reproduce**:
1. Start non-sandbox game
2. Place container and see the edges arent colored

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.
