### ISSUE TITLE
Savegame corrupting certain sectors

### ISSUE THREAD

**Issue by rawchords** [Anuken/Mindustry#2681]
**Platform**: *Android*

**Build**: *9980*
**Issue**: * certain sectors(npc, tar fields) maps resetting after resorting game data. 
**Steps to reproduce**: *Before going down to sector, all stats are there, but when i hit resume and beam down, it says save game corrupt and map and sector stats resets. Tried 9981 through 90 and 9998. Nothing works.

**Link(s) to mod(s) used**: *none,.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an (X) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[be 9880.zip](https://github.com/Anuken/Mindustry/files/5269476/be.9880.zip)

**Comment by quanium** [comment]
is on this saves has a factory with robots?

on client-be-9873.jar everything was good

**Comment by rawchords** [comment]
Yes. Could also be because of core nucleus. Only difference i think.

**Comment by quanium** [comment]
in last_log.txt i see this
...
Caused by: java.lang.IllegalArgumentException: Unknown revision '2' for entity type 'poly'

**Comment by Anuken** [comment]
Duplicate.

**Comment by rawchords** [comment]
Still saying corrupt on same sectors. tried BE 9898 savefile from 9880

**Comment by Anuken** [comment]
It will always be corrupt, as the build that made the file is defective. That save is gone, and you can't it back.

**Comment by rawchords** [comment]
But i am able to use it in build 9880.
