### ISSUE TITLE
Scatter not accepting ammo

### ISSUE THREAD

**Issue by rix117** [Anuken/Mindustry#2682]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required.*
Steam build 105

**Issue**: *Explain your issue in detail.*

 on the very first level ground zero
The scatter just won't accept any ammo no matter how you try to input it
i've tried using lead/scrap
Putting ammo in directly via placing them next to mines
putting ammo in through conveyor directly by just ending the conveyor into it
putting ammo in through any sorta router/gates.
taking ammo directly from the ship and trying to place it into the scatter it works with other turrets but the scatter is not selectable.

it is not important since it's not needed but it is broken.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

idk i just completed the regular game up to wave like 400+ on nuclear complex then opted into the beta.
then i just played through the first level.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

this is the only mod that changes files but it says its not compatable i removed it and it's still not accepting ammo.
Real life mod - https://steamcommunity.com/sharedfiles/filedetails/?id=1993262831 - Not installed anymore

the rest of the workshop stuff is just schematics i can list them as well if needed.

**Save file**: *The save file you were playing on when the bug happened, if applicable.*

[sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/5269612/sector-serpulo-15.zip)
i hope this is it it is the latest save i loaded to check and see if removing that mod was the cause.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
noob scatter uses lead

**Comment by rix117** [comment]
forgot to mention that i've tried both lead and scrap...

**Comment by DeltaNedas** [comment]
ok

**Comment by rix117** [comment]
also this only occurs on the first level everything else afterwards works fine.

**Comment by Anuken** [comment]
Every single scatter in that save has ammo when I load it, and when I try to use conveyors for loading it works just fine. Considering this is a very basic problem that should be obvious to other players, you're probably looking at the wrong place or doing something wrong.

**Comment by rix117** [comment]
odd i just loaded it back up and it wasn't like that before it kept cycling through the ammo types with a line through them like it had nothing in it. i guess sorry to use up your time everyone.
