### ISSUE TITLE
Poly (builder drones) bug

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2683]
**Platform**: Any

**Build**: Latest bleeding-edge build

**Issue**: The builder drones will not come to assist in construction, unless a player can see them. This means that they need the  screen to be updated to work. I stumbled accross it when I was building a pump at the shore (Ruinous shores), while Polys were at the Core. They didn't come. I came to see what's wrong, and they immideately started going to the pump and finishing it.

**Steps to reproduce**: Build something far away from Polys. Then come to them. They will move to the sctructure under construction as soon as you see them.

**Link(s) to mod(s) used**: /

**Save file**: Any file

**Crash report**: /

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XEN0PHIL** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/552
Earlier I've posted the same thing in suggestions because thought it's a balance issue (low range) :eyes:

**Comment by BorisA11** [comment]
Well, if it's about range, why they start building once I come close?

**Comment by Anuken** [comment]
> The builder drones will not come to assist in construction, unless a player can see them

Intentional.
