### ISSUE TITLE
Launchpads bug

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2686]
**Platform**: Any

**Build**: Any bleeding-edge build

**Issue**: Simple: Launchpad production does not add to sector production. They only work when you are in the sector with the lauchpad. If I remember the earlier builds, this was not a problem before. Now it is. Please fix it.

**Steps to reproduce**: Build a launchpad. Attach it to a conveyor to launch resources. It will work as long as you are in the sector with the launchpad. Leave the sector then. Enjoy the uselessness.

**Link(s) to mod(s) used**: /

**Save file**: Any

**Crash report**: /

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Launchpad production does not add to sector production

It's not supposed to.
