### ISSUE TITLE
Router+Sorter reduces throughput

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#2688]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10

**Build**: *The build number under the title in the main menu. Required.*
9905

**Issue**: *Explain your issue in detail.*
Putting either kind of sorter next to a router/distributer significantly slows down throughput
![ezgif-3-d5a0b9b6367f](https://user-images.githubusercontent.com/45698812/94067834-45287f80-fda3-11ea-9d1e-d11861b544f7.gif)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
See gif, or place an item source, conveyor, router, sorter and item void and look at the routers throughput

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None

**Save file**: *The save file you were playing on when the bug happened, if applicable.*
Doesn't matter

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
None
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.
