### ISSUE TITLE
Crawler leg glitch

### ISSUE THREAD

**Issue by RedRanger5577** [Anuken/Mindustry#2689]
**Platform** *Linux*

**Build**: *105*

**Issue**: *The legs of the tier 2 crawler stretched across the screen at wave 45 and they became un-killable*

**Crash report**: *There was no crash*
![Screenshot from 2020-09-20 13-00-52 - 2](https://user-images.githubusercontent.com/71792358/94072413-9b0d1f80-fdc3-11ea-9a0b-cefdb3601266.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save or specific circumstances provided.
