### ISSUE TITLE
i cant find how to mine thorium somehow

### ISSUE THREAD

**Issue by DarkAnturian** [Anuken/Mindustry#269]

**Comment by DarkAnturian** [comment]
i cant find blast or laser drill

**Comment by Prosta4okua** [comment]
see screenshot https://is.gd/sQ1hj8

**Comment by DarkAnturian** [comment]
i dont have that
D:

**Comment by Anuken** [comment]
@DarkAnturian, if you have questions about how to play the game, ask in the Discord. Github issues are for reporting code structure issues.

**Comment by DarkAnturian** [comment]
oh thx
