### ISSUE TITLE
Force close at sector 173

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#2695]
**Platform**: Android

**Build**: 106

**Issue**: Game force closed after launching core to sector 173

**Steps to reproduce**: Just launch it

**Save file**: 
[Mindustry.zip](https://github.com/Anuken/Mindustry/files/5274130/Mindustry.zip) Imported from 105

**Crash report**: Force close, no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
-  [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Force close, no crash

I cannot debug or diagnose this without a crash log.
