### ISSUE TITLE
Flares AI when attacking small blocks

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2697]
**Platform**: Any

**Build**: Latest bleeding-edge

**Issue**: Flares are behaving *not very smart* when targeting 1x1 blocks, like conduits or conveyors. They make very short attack runs, firing only 1-2 bullets. If they made longer runs, the damage will be a lot greater. This means that you can leave 6 flares for 1 minute, and they will break only 3 titanium conveyors, instead of the entire line. When attacking larger blocks they deal a lot more damage.

**Steps to reproduce**: Put a conveyor line, or a conduit. Get a flare to target it. They will move only 1-3 tiles away, and fire only a few bullets before turning and trying again.

**Link(s) to mod(s) used**: /

**Save file**: /

**Crash report**: /

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
