### ISSUE TITLE
Shadows?

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2698]
**Platform**: Any

**Build**: Latest alpha build, 104 v5 build, any version with any shadows

**Issue**: Shadows do not move as planet orbits around the sun. This leads to shadows being in the same position relative to object all the time, no matter what time is it. The issue is even more obvious with turret shadows. Please fix.

**Steps to reproduce**: Really simple: Put your ship on any position. Wait 5 minutes. See the shadow not moving. The shadow will even exist in **night**.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
Exactly why I am against turret shadows...

**Comment by Anuken** [comment]
They're not supposed to.
