### ISSUE TITLE
Sector time reset

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2699]
**Platform**: Any

**Build**: Any alpha build

**Issue**: When opening campaign, land on one sector. All "sector times" of other sectors will be set to 20:00. I remember playing on sector 172, reaching 5 minutes left. I exited, opened again and landed on Tar fields. The sector timer of 172 was set to 20 minutes again. 

**Steps to reproduce**: Here are the steps:
Land in a sector. Spend some time in it.
Leave the game, not just the campaign, the whole game.
Re-open the game
Land in an other sector.
When you land, check the sector you were previously in. It's timer will be 20 minutes when you land.

This way you can get infinite time, while keeping attacked sectors safe!

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't happen to me when I follow your exact steps.

Even if it did, I won't be fixing any campaign bugs, as it is unfinished and "fixing" mechanics that may be removed later is a waste of time.
