### ISSUE TITLE
Okay... WHAT NOW?? (infinite explosions that don't deal damage?!?)

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#27]
![bug4](https://user-images.githubusercontent.com/30189017/34258794-8ee20e38-e62d-11e7-81e0-8f706d8a02ad.gif)

**Comment by Anuken** [comment]
Looks like the tile entity somehow isn't being removed, and exploding indefinitely. Not sure what causes it, but it (might?) be fixed now. We'll see.
