### ISSUE TITLE
The "Core is under attack!" warning draws over the displayed core resources.

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry#2700]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux, may happen on other
**Build**: *The build number under the title in the main menu. Required.*
105
**Issue**: *Explain your issue in detail.*
The "Core is under attack!" warning draws over the displayed core resources.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Enable Display Core resources and let enemy units attack the core.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
X
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
X
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
X
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It should be.
