### ISSUE TITLE
tier 4/5 support ground not in tech tree for campaign

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry#2703]
**Platform**: *Android/iOS/Mac/Windows/Linux*
linux mint 
**Build**: *The build number under the title in the main menu. Required.*
9932
**Issue**: *Explain your issue in detail.*
the tier 4 and tier 5 units coming after quasar are not on the tech tree
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
(i used ite sourced to unlock everything) after unlocking the exponetial reconstructer no unit appears after the quasar
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
(na)
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
[link to github repositry with campaign save game](https://github.com/walksanatora/minsave)
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
(not a crash)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
already fixed internally
