### ISSUE TITLE
Game suddenly refuses to load

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#2705]
**Platform**: Windows

**Build**: Steam build 106

**Issue**: As I started up the game today, I found that the exe froze completely. The game doesn't even reach the loading screen.

![image](https://user-images.githubusercontent.com/19158169/94169749-2edefa00-fe5d-11ea-87c0-d29ef3605a94.png)

**Steps to reproduce**: ?

**Link(s) to mod(s) used**: ***No mods enabled***

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5277472/saves.zip)

**Crash report**: doesn't even reach that point

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot fix without a log.

**Comment by z0mbiesrock** [comment]
The game doesn't even _reach_ the point to make a log

**Comment by Anuken** [comment]
Therefore, I can do nothing.

**Comment by z0mbiesrock** [comment]
RIP; restarting the computer fixed it
_dame da ne
dame yo dame na no yo
anta ga suki de suki sugite
dore dake tsuyoi osake de mo
yugamanai omoide ga
baka mitai_

**Comment by Anuken** [comment]
incredible
