### ISSUE TITLE
Servers showing up twice in servers list

### ISSUE THREAD

**Issue by TheUzbek** [Anuken/Mindustry#2709]
**Platform**: Android 10 (EMUI 10.1.0)
**Build**: 104.6
**Issue**: servers are showing up twice in the list, as seen in screenshot below (look at tws servers, also works for every server) 
**Steps to reproduce**: 
1. Open community servers list
2. Turn off the phone
3. Turn on the phone 
**Link(s) to mod(s) used**: no mods used
**Save file**: --- 
**Crash report**: not a crash
**Screenshot**:
![Screenshot_20200924_193502_io anuke mindustry](https://user-images.githubusercontent.com/68436279/94174306-c8c69700-fe9d-11ea-82ca-ee1307960ec1.jpg)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
