### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by ItsJonyBoi** [Anuken/Mindustry#2711]
Platform: Windows

Build: Build 106

Issue: When I start Mindustry it would look like it is loaded, but it would never show me the main menu and the music would be playing in the background as if I loaded the game.

Steps to reproduce: Start the game it would look like it is loaded.

Screenshot: 
![What I see](https://user-images.githubusercontent.com/68873146/94178035-2805b680-fe60-11ea-9281-88172dbc7bd0.PNG)

Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not enough information to reproduce. You have not posted any relevant logs, mods used, or game data.
