### ISSUE TITLE
Oct commanding issue

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2713]
**Platform**: Windows

**Build**: Latest beta

**Issue**: When you command units with Oct ship, they are all outside the shield. This should be fixed, otherwise the shield is very pointless. And when commanding 20 units, they are so far apart you can't see them all. Yeah, fix this

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No. That's how the formation pattern works, and until a better solution is found this won't be changed.

**Comment by DeltaNedas** [comment]
also
1. there is no beta yet
2. what does latest mean
