### ISSUE TITLE
The Multiplayer in Campaign [SYNC PROBLEM]

### ISSUE THREAD

**Issue by FoxyFoxy67** [Anuken/Mindustry#2716]
**Platform**: *Windows*

**Build**: *Mindustry v6*

**Issue**: *The Multiplayer in the campaign not sync the ressources for others players*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *No Mods*

**Save file**: *New*

**Crash report**: *No Crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.
