### ISSUE TITLE
Ingame Map Editor has units running around

### ISSUE THREAD

**Issue by jaygamer81** [Anuken/Mindustry#2717]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
Bleeding Edge Build 9850
**Issue**: *Explain your issue in detail.*
The issue is that i was in ingame map editor and the factories began activating (which means they mustve been inputted too by the item sources i put). After a while, some Zeniths began to spawn and they began trying to kill me and my build, i switched to their team and they stopped but kept destroying the build. 
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
I dident use any
**Save file**: *The save file you were playing on when the bug happened, if applicable.*
NA
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---NA

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
https://www.reddit.com/r/Mindustry/comments/iz73hb/hmmmmm/?utm_medium=android_app&utm_source=share

**Comment by Anuken** [comment]
You are more than 100 builds behind.
