### ISSUE TITLE
Campaign Sector "Serpulo" Immediately Captured After Second Player Joins

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry#2721]
**Platform**: *Windows, both computers*

**Build**: *bleeding-edge build 9960*

**Issue**: *Wave timer stopped, sector was immediately captured without reaching wave requirements or prompting anyone that the sector was captured. Edit: Turn timer is stopping for me, and opening my tech tree will prompt me with Campaign.multiplayer*

**Steps to reproduce**: *My friend hosted a server, and was playing normally - the issue happened immediately after I joined. I already captured Ground Zero, but my friend hadn't. Update: I did this again with my friend in frozen forest and this didn't happen* 

**Link(s) to mod(s) used**: *No mods.*

**Save file**: *The save file you were playing on when the bug happened, if applicable.*
[Maps.zip](https://github.com/Anuken/Mindustry/files/5279877/Maps.zip) This should include 3 save files, because I copied every single save I saw in the save folder.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* No crashes.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not fixing any campaign bugs until it's ready.
