### ISSUE TITLE
Deep water placement bug

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#2729]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: Latest Alpha (106)

**Issue**: I am able to place serveral buildings on deep water. For example mass drivers, distributors, payload conveyers and routers, big walls (but not small ones), etc.. basically everything which is larger than 1x1

**Steps to reproduce**: Start a game and place something larger than 1x1 on deep water.

**Link(s) to mod(s) used**: None

**Save file**: Not needed

**Crash report**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
This bug came from [this commit](https://github.com/Anuken/Mindustry/commit/401384ae5bef0061031882e2acf55e25fd795c83) as far as I can tell. The same commit also allows you to build naval units on land now..
