### ISSUE TITLE
Naval factory cannot be placed in deep water

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#2730]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: Latest BE

**Issue**: Naval factories can no longer be placed in deep water due to [this commit](https://github.com/Anuken/Mindustry/commit/dc3099389855ad54246864779aad2c1a363c1c87).

**Steps to reproduce**: Attempt to place a naval factory in deep water.

**Link(s) to mod(s) used**: NA

**Save file**: NA

**Crash report**: NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That is actually intentional; it no longer requires water for placement and no longer can be no longer be placed in deep water *(because those are tied to the same variable)*.

**Comment by buthed010203** [comment]
Fair enough
