### ISSUE TITLE
AL build can't build-bug

### ISSUE THREAD

**Issue by UnionofSovietSocialistRepublics** [Anuken/Mindustry#2734]
Plat from: Window 10

Build: Alpha Build 106

Issue: AL builder in red can't build

Steps to reproduce: go to editor and Edit-in-game, you can see AL in red team can build normal but if you press quit and delete all AL in red team's build, and you play that map, you will see AL builder stay in one place 

Link to mod used:6.0 don't have any mod that it

Save file: idk I can't post .msav file but i have this
![image](https://user-images.githubusercontent.com/71920146/94335170-f62d5500-0003-11eb-93ec-be787b7bae54.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported

**Comment by Anuken** [comment]
Because it has no resources.

**Comment by DeltaNedas** [comment]
6.0 does have mods
