### ISSUE TITLE
Buildings working while in the editor

### ISSUE THREAD

**Issue by DarkBrick** [Anuken/Mindustry#2737]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *106*

**Issue**: *When you create a factory in the editor, close it, reopen it and edit in game, the factories seem to run like they would in a regular game*

**Steps to reproduce**: *Create a factory in the editor (For example, a mech factory supplied with item infinites), close the editor, open the map in the editor, click edit in game, the mech factory should be producing units despite being in the editor*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
*Wait, so it wasn't intentional?*
