### ISSUE TITLE
Scepter shooting

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2746]
**Note**: This isn't about campaign

**Platform**: Windowss

**Build**: 10016

**Issue**: Scepters can shoot at very strange angles. They are the tier 4 land units, chaoss array in v5. So, here is how you do it: 
1) Take control over scepter. 
2) Start firing
3) Move cursor very close to the scepter, while still firing.
4) The bullets will go to the cursor, at like 70 degrees to the gun. This looks really stupid. 

Try to make guns be able to move around or something else.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
