### ISSUE TITLE
Disable factory bug in 6.0 logic

### ISSUE THREAD

**Issue by stikonas** [Anuken/Mindustry#2750]
**Platform**: Linux

**Build**: ff84d72e20f4b2f313ed968252f7271a1c42975d (tip of `master` branch at the time of bug report).

**Issue**: When you disable buildings using microprocessor, it only last for just over 100 iterations.

**Steps to reproduce**:

This is a small reproducer. It consists of drill, microprocessor, message and memory cell. Microprocessor is programmed to disable drill on iteration number 250 using the following code:

```
read result cell1 10
print result
printflush message1
op add result result 1
write result cell1 10
jump 7 notEqual result 250
control enabled drill1 0 0 0 0
end
```
Soon after message hits 350 the drill reenables itself.

The whole schematic is here:
```
bXNjaAF4nGNgYWBhZGDJS8xNZWBJKk23Z2Hgzk3NzS+q1E1OzclhYM9NLS5OTE9l4C/ISy3NTSzJTNZNKcoEyvDnZiYX5esWFOUnA5XkFzEwMLAwgAEzI5BgAhrLbGxqyczEAILMzAzMDAx8QIkJFXNS+2K5DhkItFzvUrI8KqcoeES4YsKWSNNNvll1H2zkQpJM1upv4j995jjPZqaGdIVcg4AzcwoU0lq9ujQjpqdt7zR+XnF0YtIV8aBD/ivO6pvbq8odVPuVvftp4SFlq/l+39dUPvzdLNJcrlnhVrQr3Sij6W9LirXjuQ6rIt7bbF6NfGb3H31albCdZ9Wqamb9Ny4NzAB3Tll6
```

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Blocks will automatically enable themselves if they are not controlled for a period of time.

**Comment by stikonas** [comment]
> Blocks will automatically enable themselves if they are not controlled for a period of time.

Oh ok, so this was intentional. That's fine. It is always possible to store their state in a memory cell. It's just that this was undocumented, so caught me off guard.
