### ISSUE TITLE
Strange behavior with repair drones

### ISSUE THREAD

**Issue by Tazshelby2016** [Anuken/Mindustry#2751]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows (Through Itch.io app)*

**Build**: *Alpha Build 106*

**Issue**: *After a considerable number of waves (30+), repair drones begin to behave erratically, shooting a random position and causing the FPS to drop below 10. Seemed to occur when enemy aerial units from a wave attacked the core or other building*

**Steps to reproduce**: *Hard to reproduce – set up a custom sandbox game with default wave set up. Set up 6 repair drones and fend off waves. It may occur after wave 30, but no guarantees.*

**Link(s) to mod(s) used**: *Not applicable.*

**Save file**: *Do not know how to locate. One was deleted.*

**Crash report**: *I quit before it could crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.

**Comment by Tazshelby2016** [comment]
What is it a duplicate of? I had not seen that issue when searching.
