### ISSUE TITLE
Picking up scrap walls... forever

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2754]
**Platform**: Windows

**Build**: 10016

**Issue**: When picking up blocks un-placable in survival with Mega, Quad or Oct, they can not be placed again, so you have cargo space clogged forever. 

**Steps to reproduce**: I was in Nuclear Zone, capmaign and picked up a medium scrap wall around the conveyors. I couldn't place it at all again. So I got 4 cargo space clogged in Mega ship. Forever. Yay!

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
F

**Comment by Anuken** [comment]
Scrap walls can't be built, so they can't be placed.

**Comment by RogueRedHawk** [comment]
If it can't be placed, _you shouldn't be able to pick it up_.
