### ISSUE TITLE
green bars

### ISSUE THREAD

**Issue by bossSHREADER210** [Anuken/Mindustry#2758]
**Platform**: Windows

**Build**: I literally cant read it.. its jumbles grey lines

**Issue**: so i found out that i could play V6 and i followed the instructions.. RMB mindustry in your steam library > properties > betas > v6.... i did that and after waiting for the download to finish i booted up the game... now all i see is about 2mm thick green lines going left to right on my screen.. and they aren't stationary they teleport up and down rapidly... it could risk someone having a seizure or an epileptic attack... i cant read anything whatsoever i purely navigate the game due the memory of what everything does 

**Steps to reproduce**: followed the steps to make me able to play v6 on steam.. upon starting it happens.. i closed and re-opened but it happened again

**Link(s) to mod(s) used**: no mods used

**Save file**: I don't really have a save file if it happened immediately 

**Crash report**: no crashes whatsoever
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your GPU or drivers are broken.

**Comment by bossSHREADER210** [comment]
> Your GPU or drivers are broken.

everything is fine when i do anything else... it's only on Mindustry... so i don't understand...

**Comment by RedDragonMZ** [comment]
Go to nvidia control panel and click "Manage 3D setting" and set default graphics card to nvidia.
