### ISSUE TITLE
Audio problems when mapping into new sector.

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry#2761]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
Sorry, but this is kinda similar
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
Steam 106
**Issue**: *Explain your issue in detail.*
When moving from sector to sector, the audio (drills, conveyors, duos, etc.) won't play unless you go to something like the tech tree and exit.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
go to a different sector. Listen for audio over drills. Go to tech tree. Exit tech tree. Listen again
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none
**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not going to be fixing any audio issues, because the ambience and sound system will be changed before release anyway.
