### ISSUE TITLE
Scrap walls getting changed when re-placed

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2762]
**Platform**: Windows

**Build**: Latest alpha

**Issue**: When picking up a scrap wall with support ship and placing it again, it gets a new variant of itself. For example, I picked up one with scratches in bottom left, and placed on with no damage at all. It's the same block all the time though.

**Steps to reproduce**: Pick up a scrap wall. Place it. Repeat. It will get different every time.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's how variants work.
