### ISSUE TITLE
Ore are being generated in water

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#2763]
**Platform**: Windows

**Build**: Latest alpha (107)

**Issue**: Ores are being generated in (deep) water. Happens for manual generation aswell as generation rules.

**Steps to reproduce**: Create a map, place deep water and generate ores.

**Link(s) to mod(s) used**: None

**Save file**: None

**Crash report**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Edit: Also happens on slag.

**Comment by Shawak** [comment]
@Anuken Didn't mention it because i am not sure if it's a bug or not, but ores are also being generated below walls.

**Comment by Anuken** [comment]
That's not a bug. No reason for ores not to be there.
