### ISSUE TITLE
Crash on clicking button 'Skip' campaign 6

### ISSUE THREAD

**Issue by FeyFre** [Anuken/Mindustry#2766]
**Platform**: *Windows*

**Build**: *alpha build 106*

**Issue**: Game crashes in campaign on pressing button  'Skip' when sector time is out/or another sector is attacked.
java.lang.NullPointerException
	at mindustry.game.Universe.runTurn(Universe.java:175)
	at mindustry.ui.fragments.HudFragment.lambda$build$53(HudFragment.java:294)

**Steps to reproduce**: Play until condition to switch sector appears with 2 buttons: 'skip' and 'switch sector'. Press skip.

**Link(s) to mod(s) used**: No mods.

**Save file**: [sector-serpulo-6.msav-backup.zip](https://github.com/Anuken/Mindustry/files/5302244/sector-serpulo-6.msav-backup.zip)

**Crash report**: [crash-report-09_30_2020_01_37_21.txt](https://github.com/Anuken/Mindustry/files/5302236/crash-report-09_30_2020_01_37_21.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already reported.
