### ISSUE TITLE
broken/uncontrollable units 

### ISSUE THREAD

**Issue by Suggestedone9** [Anuken/Mindustry#2767]
**Platform**: *Windows*

**Build**: *Alpha build 107*

**Issue**: *After exiting a unit in a private server, the unit could not be controlled, nor could its AI do anything. Its information hub also did not appear(hp, ammo, name). The unit was a lightly damaged corvus and was the only one alive. If it helps, There were other units, naval ones through tiers 1-5 alive, with most of them at their unit production cap.*

**Steps to reproduce**: *I'm not exactly sure what happened, because I've done the same with the unit before several times without the issue occurring. Exit a unit in a local server with a command centre on rally. There is a small chance that it will do what I stated earlier.*

**Link(s) to mod(s) used**: *N/A.*

**Save file**: *The save file can not be uploaded here because its not supported(I can DM you it on discord though).*

**Crash report**: *N/A.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Suggestedone9** [comment]
I can should be able to send you the file through discord(it should come from the user suggestedone9#2140)

**Comment by Suggestedone9** [comment]
As an extra note, it wouldn't heal either, but by reloading the save it appears to be working, but it could still be a issue

**Comment by Anuken** [comment]
Sounds like the same as #2582. If a unit can't be found, viewed or controlled, the problem is likely that it's "invisible" like the other units in the issue.
