### ISSUE TITLE
Conduit And Liquid Tank

### ISSUE THREAD

**Issue by Voz-Duh** [Anuken/Mindustry#2774]
**Platform**: *Windows 10*

**Build**: *10080*

![image](https://user-images.githubusercontent.com/61590217/94712120-b2af4f80-0351-11eb-8ad2-43e2c3dee72d.png)

---

- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your commit is the culprit here. Reverting.

**Comment by Voz-Duh** [comment]
?

**Comment by Anuken** [comment]
This was broken by your pr (https://github.com/Anuken/Mindustry/pull/2769)

**Comment by Voz-Duh** [comment]
![image](https://user-images.githubusercontent.com/61590217/94714344-b1cbed00-0354-11eb-924e-f470a526cade.png)
My commit don't touching the topRegion
![image](https://user-images.githubusercontent.com/61590217/94714620-0cfddf80-0355-11eb-810a-582bd8c90b4b.png)

**Comment by Anuken** [comment]
It's still the code that breaks everything. Test it out for yourself; I tried it a few times to be sure.

**Comment by LeoDog896** [comment]
Voz kinda sus

**Comment by Voz-Duh** [comment]
> It's still the code that breaks everything. Test it out for yourself; I tried it a few times to be sure.

Why bot region normal?

**Comment by Voz-Duh** [comment]
Oh ok
