### ISSUE TITLE
All units with green projectiles are unable to heal stuff with said projectiles. Accept for the nova and the mega.

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry#2780]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Bleeding edge 10110(though i remember it in earlier builds of v6)
**Issue**: Units with green projectiles accept for the nova and mega cannot heal stuff. Dispite there projectiles being green and there being references to healing in the games code with these units
**Steps to reproduce**: 1. Get a damaged block that is on your team.
2. Get a support unit that isn't the oct, nova, mono or mega
3. Try to heal the block with your projectiles.

**Save file**: This has happened to me on mutable saves every time i try to heal something with these units

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Who said those units are supposed to heal anything?

**Comment by Colonizor48** [comment]
> 
> 
> Who said those units are supposed to heal anything?

The projectiles were green. And because green bullets can heal why not green lasers. Also i saw the projectiles for these units internally be called healing lasers or something like that

**Comment by Anuken** [comment]
> why not green lasers

Because lasers would be bad at that and their code is fundamentally different.

> having healing in the name

Legacy names are irrelevant and not displayed anywhere in the game itself.

**Comment by Colonizor48** [comment]
> 
> 
> > why not green lasers
> 
> Because lasers would be bad at that and their code is fundamentally different.
> 
> > having healing in the name
> 
> Legacy names are irrelevant and not displayed anywhere in the game itself.

Understandable. I will move this to suggestions then
