### ISSUE TITLE
Crawlers from wave go afk

### ISSUE THREAD

**Issue by djradnad** [Anuken/Mindustry#2787]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required.*
Steam alpha. 106 iirc (currently still ingame)
**Issue**: *Explain your issue in detail.*
After just over 400 waves in a custom map, the crawlers end up just standing around just outside of their spawn, cause unknown, perhaps a persistent belt that is nonexistent that they are trying to get to, or perhaps no optimal path detected by them? They do however go to new things that are placed near enough to them.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Lots of belt spam, while my friend was building walls and some factory related stuff the crawlers suddenly broke.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None.
**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*
not entirely sure how to share the file...
[crawlersbugged.zip](https://github.com/Anuken/Mindustry/files/5311155/crawlersbugged.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't happen on the save you sent me, and no problems occur when I spam walls/conveyors and waves. Considering it took you 400 waves to get any results, this is unlikely to happen frequently enough for me to see it or fix anything.

**Comment by djradnad** [comment]
darn, in hindsight i shoulda just made a gif. it happened every wave for me, i think most likely was due to some persistent belt, just one of those things thatll happen from tons of spam basically impossible to prevent... although there was another bug that happened frequently for me at the start where a flare would be unkillable, but usually would just sit in place and uhh, well yea ill just try to record gifs from now on.
