### ISSUE TITLE
Poly building bug

### ISSUE THREAD

**Issue by ZuZu84** [Anuken/Mindustry#2788]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
107
**Issue**: *Explain your issue in detail.*
Enemy poly building air
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
while playing attack on a server, there was enemy poly that was respawning from enemy core and was flying to destroyed ripple trying to fix it. After it died again, i put conveyor on ripple's place, and it began fixing air below without bilding anything.
![dsads](https://user-images.githubusercontent.com/72205010/94810904-7db90080-0416-11eb-89e2-46766bdaf5f5.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods used
**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*
I did'nt saved cause i didn't knew it was requred before map changed
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
In the screenshot, it's not building on the ripple, but below it. If the placement location were invalid, it would do nothing; what you're seeing is a lack of resources for the AI.
