### ISSUE TITLE
Land T4 & 5 wrong laser sound

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry#2789]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux, may happen on other
**Build**: *The build number under the title in the main menu. Required.*
107
**Issue**: *Explain your issue in detail.*
The T4 and T5 ground support units have a standard laser cannon sound.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Build a T4 or T5 ground support unit from Nova and fire its laser.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
X
**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*
Will happen on any save file
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
X
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
Because there are no sounds for them, yet.

**Comment by rmperkow** [comment]
I thought it would use meltdown sound for placeholder
