### ISSUE TITLE
Tsunami sound

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2791]
**Platform**: Windows

**Build**: 10135

**Issue**: Tsunami makes sounds all the time, not only when shooting, if you control it when it is already firing.

**Steps to reproduce**: Construct a Tsunami. Make it shoot at something. Take control over it. It will make its noise even if you dont fire.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have not provided a save despite it being **required**, and you have not specified exactly how to make this happen. The tsunami has nothing notable about it in terms of sound, so either you're mishearing something or you're just omitting critical information. This does not happen to me.
