### ISSUE TITLE
Meltdown does not have its laser when enclosed by shield, steals other bullets

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#2797]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required.*

BE-10149

**Issue**: *Explain your issue in detail.*

The laser of meltdown will fire for a split second when under the shield of the T5 support aircraft with no weapons (im sorry i dont know the names) Furthermore when the beam is deleted it seems that the meltdown will steal the projectiles of other firing turrets at random that DO damage the shield. I have tested with spectre, fuse, salvo and ripple. it stole projectiles from all guns except ripple.

On a whim i decided to test to see if the same thing happened with the T4 Ground support mech since it is essentially a meltdown laser but shorter and green. The same thing happens to it

 *on further testing of bullets the meltdown is also stealing projectiles fired from dagger units as well as my nova being used to control said dagger units. Fortress seems unaffected however i have not tried a larger group. ~but based on it not stealing ripple fire it seems to just ignore artillery type bullets completely~ Edit: i lied, it is stealing the explosion effect of the artillery bullets not the bullet firing. When the bullet explodes on the ground or whatever the effect happens at meltdown tip like everything else

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

https://youtu.be/KYtLU0zDfjQ

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Suggestedone9** [comment]
oct is the unit name btw
