### ISSUE TITLE
Bryde

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#2798]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Android

**Build**: 107

**Issue**: Brydes can only move forward if controlled

**Steps to reproduce**:
Build a Bryde, Control it

**Link(s) to mod(s) used**: h nah

**Save file**: This happens in multiplayer,  so no save file, never tested it in singleplayer tho

**Crash report**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's how they're supposed to work.

**Comment by D-player1** [comment]
Oh, i explained it wrong, what i mean is that they can't turn left and right when they're controlled, it just freezes and move forward non stop

**Comment by Anuken** [comment]
That works fine for me on Android.
