### ISSUE TITLE
Logic Processors and Diodes

### ISSUE THREAD

**Issue by Draco18s** [Anuken/Mindustry#2804]
**Platform**: Windows

**Build**: 107

**Issue**: Logic processors do not correctly read a diode's enabled state (will always return 0 regardless of if the diode is allowing power to pass through or not).

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's not what reading the enabled state is supposed to do.

**Comment by Draco18s** [comment]
It also reads a zero if I use a second logic processor to write a 1 to the diode's enabled state.
