### ISSUE TITLE
Big conveyor not joining with another conveyor

### ISSUE THREAD

**Issue by Murdyxd** [Anuken/Mindustry#2811]
**Platform**: *Windows*

**Build**: *107*

**Issue**: *Big conveyor not joining with another conveyor*

**Steps to reproduce**: *I just make mod with conveyor with size 3*

**Link(s) to mod(s) used**: 
[mod.zip](https://github.com/Anuken/Mindustry/files/5321748/mod.zip)
Also have screenshots 
![image](https://user-images.githubusercontent.com/72306529/94992889-55b4d300-05b7-11eb-81c8-d9c52414418d.png)
![image](https://user-images.githubusercontent.com/72306529/94992893-5baab400-05b7-11eb-9d1c-cc0102b0502c.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
the (stack) conveyor is not designed to work with any size other than `1` (only the payload conveyor can) this isn't a bug 🤔

**Comment by Murdyxd** [comment]
> the (stack) conveyor is not designed to work with any size other than `1` (only the payload conveyor can) this isn't a bug 🤔

anyone variant to design it?

**Comment by Quezler** [comment]
> anyone variant to design it?
variant?

**Comment by Murdyxd** [comment]
yes
