### ISSUE TITLE
can place thor walls on surge walls

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#2823]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows
**Build**: *The build number under the title in the main menu. Required.*
10200
**Issue**: *Explain your issue in detail.*
Can place 1x1 thorium walls over 1x1 surge walls
![image](https://user-images.githubusercontent.com/45698812/95002769-8895a180-058c-11eb-8d7f-2d58d6aeeed3.png)
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
see issue
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none
**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*
doesn't matter

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by l-Luna** [comment]
why is this a problem?

**Comment by Anuken** [comment]
It's not.
