### ISSUE TITLE
Processors remember all connected blocks

### ISSUE THREAD

**Issue by Kristallito** [Anuken/Mindustry#2830]
**Platform**: *Android*

**Build**: *10117*

**Issue**: *Processors remember connected blocks forever, even after deleting these blocks*

**Steps to reproduce**: *Just connect something to processor disconnect (or destroy) block and connect processor
 to the similar block (swarmer1-swarmer2)*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *This works on any save files*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
intentional

**Comment by Kristallito** [comment]
![Screenshot_20201004-195050_Mindustry BE](https://user-images.githubusercontent.com/72344984/95017465-48f9b300-067b-11eb-83b1-9ada9821c47a.jpg)
![Screenshot_20201004-195055_Mindustry BE](https://user-images.githubusercontent.com/72344984/95017470-4dbe6700-067b-11eb-9815-58cc78b10792.jpg)
![Screenshot_20201004-195125_Mindustry BE](https://user-images.githubusercontent.com/72344984/95017474-51ea8480-067b-11eb-9454-6a02fda71d7d.jpg)
![Screenshot_20201004-195204_Mindustry BE](https://user-images.githubusercontent.com/72344984/95017475-5747cf00-067b-11eb-9ad7-245aaeb93368.jpg)

**Comment by Kristallito** [comment]
Why is it intentional?

**Comment by Anuken** [comment]
Because *they're different blocks*. If you accidentally disconnect something and reconnect it later, your numbers would change and cause a mess.
