### ISSUE TITLE
Plastanium conveyor broken item batches

### ISSUE THREAD

**Issue by Kristallito** [Anuken/Mindustry#2832]
**Platform**: *Android*

**Build**: *10117*

**Issue**: *After replacing titanium conveyor with plastanium conveyor happens this(screenshots)*
![Screenshot_20201004-210645_Mindustry BE](https://user-images.githubusercontent.com/72344984/95019585-01c5ef00-0688-11eb-8c72-3b48646a7df4.jpg)
![Screenshot_20201004-210655_Mindustry BE](https://user-images.githubusercontent.com/72344984/95019589-07233980-0688-11eb-883b-ca52511a1f41.jpg)
![Screenshot_20201004-211823_Mindustry BE](https://user-images.githubusercontent.com/72344984/95019593-0b4f5700-0688-11eb-98f5-38ef75b20221.jpg)
At next loading of game little stacks of items became invisible
![Screenshot_20201004-211752_Mindustry BE](https://user-images.githubusercontent.com/72344984/95019642-549fa680-0688-11eb-89fa-4be1c8bfc3ac.jpg)
I can't grab them or destroy in item void or incinerator, only destroying conveyors helps

**Steps to reproduce**: *Shown above*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *Works on any saves. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
and you're sure they became invisible, or did they enter the void while you weren't looking?

**Comment by Kristallito** [comment]
Sure, you can see on last screenshot that conveyor is not working  as if there were visible items

**Comment by Quezler** [comment]
i've tried to replicate what you have in your screenshots above, and for me they never turn invisible 🤔

**Comment by Quezler** [comment]
could you perhaps share a world save, or record you doing it in a video? 😗

**Comment by Kristallito** [comment]
Ok (to make them invisible i load game)

**Comment by Anuken** [comment]
> Works on any saves. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

oh my god

**Comment by Kristallito** [comment]
Hmm i cant send save file or video here

**Comment by Quezler** [comment]
then zip it 🤐

**Comment by Kristallito** [comment]
[Uploading Bug world and vid.zip…]()

how i didn’t think about this

**Comment by Kristallito** [comment]
> 
[Only buggy world.zip](https://github.com/Anuken/Mindustry/files/5323642/Only.buggy.world.zip)

**Comment by Anuken** [comment]
(fixed)
