### ISSUE TITLE
Commanded units are not pushed out by drop zone

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2833]
**Platform**: Windows

**Build**: 10230

**Issue**: Units you command by G key are not affected by drop zone's pushing, so they do not move out of it as all units do.

**Steps to reproduce**: Here is how I stumbled accross it:
I was in a watery sector, in campaign. I commanded a fleet of maximum number of ships (naval ships) you could, 25 I guess. I went to drop point, and the commanded units in front of me did not get pushed out. I suppose it works for air units as well, but I tested only water units.

**Link(s) to mod(s) used**: No mods

**Save file**: Apologies, limit for file size is 10MB, my save exceeds that. It can happen on any save, I suppose.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They *are* pushed out, it's just not very noticeable due to how they move. I tested this.
