### ISSUE TITLE
Liquid source problems

### ISSUE THREAD

**Issue by Violet-Scarelli** [Anuken/Mindustry#2834]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
10227
**Issue**: *Explain your issue in detail.*
Liquid sources straight up don't output. EDIT: no piping or fluid transfer seems to work. 
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Place a liquid source, try to attach pipes to it. EDIT: try to transfer fluid anywhere, using pipes. You'll see that the pipes don't even transfer to each other.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[33.zip](https://github.com/Anuken/Mindustry/files/5324074/33.zip)
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Did you choose a liquid in the liquid source?
And making sure that the pipe isn't reversed.

**Comment by Violet-Scarelli** [comment]
> Did you choose a liquid in the liquid source?
> And making sure that the pipe isn't reversed.

Yes, and yes.
