### ISSUE TITLE
Routers don't save items

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2837]
**Platform**: Android 9

**Build**: 10200

**Issue**:
Routers do not save their routed item.

**Steps to reproduce**:
1. Place any kind of router
2. fill it with an item
3. save and reload

**Link(s) to mod(s) used**: deltanedas/routorio, solar and clear router, how i found the issue and demonstrated it easily

**Save file**: *That's the issue, it won't save the items*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
similar to https://github.com/Anuken/Mindustry/issues/1601

**Comment by Anuken** [comment]
fixed
