### ISSUE TITLE
Graphite press has wrong status

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2838]
**Platform**: Android 9

**Build**: 10200

**Issue**:
The block status color is wrong for the graphite press.

Graphite presses backed up:
![graph](https://user-images.githubusercontent.com/39013340/95099806-e6a6be00-071f-11eb-83a6-b57b54b5157c.jpg)

Pyratite mixers backed up (correct, orange):
![pyra](https://user-images.githubusercontent.com/39013340/95099726-caa31c80-071f-11eb-9cf8-6b32912072b1.jpg)

**Steps to reproduce**:
1. Coal source, graphite press in sector
2. Wait for status to turn from green to red (instead of orange, red should mean input starved)

**I could not replicate on sandbox, only on my campaign sector 65**

**Save file**: 
[h.msav.txt](https://github.com/Anuken/Mindustry/files/5328363/h.msav.txt)

**Mods used**: deltanedas/routorio

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/95100981-acc5bf80-06ff-11eb-9c32-5e6d64b30040.png)

![image](https://user-images.githubusercontent.com/10100000/95100997-b18a7380-06ff-11eb-99b3-2fcb7f3709bc.png)

**Comment by D-player1** [comment]
Maybe the flowgate has a graphite?

**Comment by DeltaNedas** [comment]
ah i see thats why it didnt happen on sandbox
silly me
