### ISSUE TITLE
Sorters cant filter modded items

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2839]
**Platform**: Android 9

**Build**: 10200

**Issue**:
Sorters will not sort a modded item (routorio beryllium) when configured manually or clicked.

**Steps to reproduce**:
1. load save
2. In F8: `Vars.world.build(85, 101).configure(this.global.routorio.items.beryllium)`
3. See how it does nothing
4. Repeat for the one on the right by clicking in the UI

**Link(s) to mod(s) used** deltanedas/routorio

**Save file**: 
[test.msav.txt](https://github.com/Anuken/Mindustry/files/5328420/test.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
won't fix, wait until docs
