### ISSUE TITLE
Bad command mode pathfinding

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2840]
**Platform**: Windows

**Build**: Bleeding edge build, any with commanding

**Issue**: When you command units, they follow you. If they find an obstacle, they'll just stupidly walk _into_ it, not around it. 

**Steps to reproduce**: Here:
Get any support mech
Souround yourself with units
Hit G key
Fly around a wall so you get there faster than commanded units
They will bump into that wall as they try to follow you, and keep walking into it. 
Wall is not necessary, any block will do, same for higher ground sections.

**Save file**: Any file. My friend tried it as well, and it was still same.

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There *is* no command mode pathfinding, and there shouldn't be.
