### ISSUE TITLE
Units move to 0, 0 when controled by processor. Reguardless of command coords

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry#2842]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *BE 10244

**Issue**: Units move to 0, 0 when controled by processor. Reguardless of command coords

**Steps to reproduce**: 1 go into a processor
                                     2. Use the unit bind command to bind a type of unit
                                     3. Try to send the units somewhere via the processor
                                     4. They go to 0, 0
*Save file**: [30.zip](https://github.com/Anuken/Mindustry/files/5329846/30.zip)

                                   

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Colonizor48** [comment]
This might only happen for certain units. Particularly the zenith and the crawler. I'm not 100% sure however.

**Comment by WarmWooly** [comment]
This is a v6 bug, and as stated in the note at the very top, it will not be considered nor fixed at this time. :/

**Comment by RogueRedHawk** [comment]
@WarmWooly v6 bogs are allowed. v6 _campaign_ bugs are not.

**Comment by Anuken** [comment]
There is no bug. You're confusing world coordinates and tile coordinates.

**Comment by Colonizor48** [comment]
This is a bug tho. Changing the processor coordinats doesn't change where the units are going to. Reguardless of what i do. This might be caused by the command not properly saving coord data and instead just saving 0, 0 and not overwriting it later

**Comment by Colonizor48** [comment]
Update i got it to change but it still really isnt working right in ways i need a while to think of words for.

**Comment by Colonizor48** [comment]
The units are just randomly moving reguardless of what i put in for coordinates

**Comment by Colonizor48** [comment]
oh my bad

**Comment by Anuken** [comment]
**You're confusing world coordinates and tile coordinates.** Put in correct world coordinates and *they will move there*, I've tested it in your map. If there were some obvious problem with movement, I would have caught it when making my follow AI example.
