### ISSUE TITLE
Units still act as if they were controled by a processor dispite said processor no longer existing

### ISSUE THREAD

**Issue by Colonizor48** [Anuken/Mindustry#2843]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: *BE 10427

**Issue**: *If you control units using a processor and then break the processor. The units still will say they are processor controlled. And they cannot be controlled by a command center. However the issue goes away after a bit for some reason.*

**Steps to reproduce**: 1. Put down a processeor
2. Bind the processor to a unit type that exists in the world
3. Control the units using the processor to go somewhere and close the processor
4. Wait for the units to go where you commanded them to. Then delete the processor.
5. See the units are still being controlled by a non existent processor

**Save file**: 
[20.zip](https://github.com/Anuken/Mindustry/files/5330039/20.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional. Units will follow processor the last instructions until they time out.
