### ISSUE TITLE
Naval Ships uncontrollable

### ISSUE THREAD

**Issue by MagicalWiz** [Anuken/Mindustry#2849]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheMrAlbert** [comment]
Hello there. I would like to point out that your information is not complete which your bug report may not be accepted by the time I send this comment. Please include additional information where relevant. Thanks.

Disclaimer: This message is not affiliated with Anuke.

**Comment by nzuzorenene** [comment]
Hello, I may have unintentionally pressed on the wrong buttons, Apologies for any inconvenience that have resulted in my actions, I’ll be more careful with what I do in the platform going forwards. I am new at GitHub. My goal is to learn and develop my skills in coding and more.

Kind Regards

Nzuzo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MagicalWiz** [comment]
I apologise for the inconvenience I have caused I'm am very new to the Github,
Platform:Android
As stated in the title the Naval Ships are uncontrollable, when controlling the Naval ship I am unable to change direction or stop any movement.
If anymore information is required please tell me
