### ISSUE TITLE
adding mods and they disappear 

### ISSUE THREAD

**Issue by FireBurns3090** [Anuken/Mindustry#2850]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*
android

**Build**: *The build number under the title in the main menu. Required.*

104.6
**Issue**: *Explain your issue in detail.*
i am importing mods and when i reload the page the mod just disappears 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
imported a mod, reloaded mod page, mod gone 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
10 different mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by FireBurns3090** [comment]
![Screenshot_20201006_224941_io anuke mindustry](https://user-images.githubusercontent.com/72473891/95263797-44bdc900-0826-11eb-9782-a700234e10c2.jpg)
![Uploading Screenshot_20201006_224937_io.anuke.mindustry.jpg…]()

**Comment by FireBurns3090** [comment]
add mod
![Uploading Screenshot_20201006_224932_io.anuke.mindustry.jpg…]()

**Comment by FireBurns3090** [comment]
reload
![Uploading Screenshot_20201006_224937_io.anuke.mindustry.jpg…]()

**Comment by FireBurns3090** [comment]
and it is gone
![Uploading Screenshot_20201006_224941_io.anuke.mindustry.jpg…]()

**Comment by Anuken** [comment]
duplicate
