### ISSUE TITLE
version_fdroid.txt: 5-fdroid-107 vs 6-fdroid-107

### ISSUE THREAD

**Issue by relan** [Anuken/Mindustry#2853]
versionName in https://raw.githubusercontent.com/Anuken/MindustryBuilds/master/version_fdroid.txt says 5-fdroid-107, while actual versionName in the APK built from v107 tag is 6-fdroid-107. This mismatch causes F-Droid build failure:

```
ERROR: Could not build app io.anuke.mindustry: Unexpected version/version code in output; APK: '6-fdroid-107' / '107',  Expected: '5-fdroid-107' / '107'
```

**Comment by DeltaNedas** [comment]
h

**Comment by Anuken** [comment]
I'll fix it in the build scripts at release (*or beta*), but for now I think it's best that the builds keep failing; V6 is still in alpha.

**Comment by relan** [comment]
Thanks.

**Comment by mimi89999** [comment]
Hello,
Please don't publish failing builds. If you do not want a version to be added to F-Droid, then don't add it to the version file.
The build server will soon be flooded with failing Mindustry builds as it tries to build an app several times before giving up.

**Comment by Anuken** [comment]
In that case, I might as well change it.
