### ISSUE TITLE
Drop points staying after capturing sector

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#2857]
**Not really a bug, but a problem**

**Platform**: Windows

**Build**: Latest alpha

**Issue**: When you capture a sector, a perfectly useless drop point remains. This should be removed, as it does nothing, only pushes out units. You can even build in it without any consequences. It would make the game better and more realistic if it dissapeared after capture, since if no enemies come, the drop point is useless.

**Steps to reproduce**: I captured a sector, and drop point remained

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: Any file, 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. Not a bug.
2. You **deliberately** deleted the notice that tells you *not to report bugs related to the campaign*.
3. "Latest alpha" is not a version.

**Comment by Esnardo** [comment]
You do realize you can in fact get enemies to drop in a captured sector? just explore a sector and leave it for 3 turns

**Comment by BlueWolf3682** [comment]
oh no
