### ISSUE TITLE
Enemy attack AI builds in the editor when you choose to edit in game

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry#2858]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *Steam build 107.*

**Issue**: *the enemy attack AI ship will build in the editor if you have AI building on, this will save when you exit editing in game.*

**Steps to reproduce**: *I was working on an attack map, and then I noticed that the enemy was building, while I was in edit in game mode.*

**Link(s) to mod(s) used**: *(none)*

**Save file**: *Tested multiple times on various saves,(I had trouble uploading a save file so I went ahead and tested on different saves instead. I hope that is fine, I can keep trying to upload a if you need me to, just it was not working as of making this report.)*
![attackAIbug](https://user-images.githubusercontent.com/67780148/95380505-d70cae00-08b4-11eb-9ccc-da10f3159411.PNG)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
