### ISSUE TITLE
Ship wont shoot after exiting build mode

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry#2869]
**Platform**: *Linux*

**Build**: 104.6

**Issue**: The stupid ship wont shoot after exiting build mode. I lost 3 hours of progress. thanks.

**Steps to reproduce**: Enter build mode, right click, press shoot, nothing happens

**Save file**: Progress gone.

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
did you have anything in your build queue? if so you won't be able to shoot. the default key to clear it is q.

**Comment by UltraBlackLinux** [comment]
I didnt... Sadly.

**Comment by Anuken** [comment]
Too outdated a version to have any relevance in 6.0.
