### ISSUE TITLE
Conveyors not being able to be selected after being built over

### ISSUE THREAD

**Issue by Excavator987** [Anuken/Mindustry#2870]
**Platform**: Windows

**Build**: 10302

**Issue**: When built over, conveyors with items on them can no longer be selected, as if you were trying to remove an item from the conveyor

**Steps to reproduce**: Have a conveyor with resources on it and build over the conveyor with an upgraded version. You will no longer be able to select that conveyor.

**Save file**: 
[Save file.zip](https://github.com/Anuken/Mindustry/files/5348639/Save.file.zip)

![image](https://user-images.githubusercontent.com/58992170/95474534-1dc5db00-097d-11eb-9448-c25654af42f6.png)
*Clicking on the conveyor does not open up its "inventory"*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Goncalves221** [comment]
Ok
Enviado do Yahoo Mail para Android 
 
  Em quinta, 8 out, 2020 às 19:00, Anuken<notifications@github.com> escreveu:   



Closed #2870 via eb0ab3b.
