### ISSUE TITLE
you can't change your unit after controlling a turrret

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#2871]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android.*

**Build**: *10305.*

**Issue**: *when controlling a turret (or probably with a unit too, i didn't test) you can't change to units, like alpha, beta and gamma, because the new mobile aim system.*

**Steps to reproduce**: *control a unit and try to hold on the core to change to a unit.*

**Link(s) to mod(s) used**: *none.*

**Save file**: *http://www.mediafire.com/file/5np7s6axy3gg1uf/h1iwg72ywgx1j3oafia52tususg2w7.msav/file*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> try to hold on the core to change to a unit.

You do not hold the core, you tap it twice.
