### ISSUE TITLE
json "research" string doesnt get parsed

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2872]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
h

**Platform**: Android 9

**Build**: 10305

**Issue**:
you broke routorio
Every content's `research` field is ignored.
Warnings: ![a](https://user-images.githubusercontent.com/39013340/95507876-a2c2eb80-09a1-11eb-9fcf-bee3760eb68a.jpg)

Tech tree is empty of routorio stuff, big sad. 

**Steps to reproduce**:
1. Load routorio (ignore errors they're fixed)
2. F8

**Link(s) to mod(s) used**: deltanedas/routorio

**log**: [last_log.txt](https://github.com/Anuken/Mindustry/files/5351076/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not done, and it won't be until I start working on modding. You have two options:
1. Wait until after beta for it to be tested and fixed
2. [Fix it yourself and submit a PR](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/mod/ContentParser.java#L558)

**Comment by DeltaNedas** [comment]
why doesn't it work, so i can fix it

**Comment by DeltaNedas** [comment]
@Anuken

**Comment by Anuken** [comment]
find out.
