### ISSUE TITLE
Vela Units sometimes appear to be firing mass drive projectiles after shooting

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2873]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows 10, 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Bleeding edge release 10305

**Issue**: *Explain your issue in detail.*
whilst controlling a vela (ctrl+click) and commanding multiple other velas they will occasionally appear to be firing mass driver projectiles.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
step 1: get a bunch of velas
step 2: control one
step:3 command the other
step 4:(might be necessary?) be on a map with a large amount of mass drivers shooting.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[MindustryV6Save.zip](https://github.com/Anuken/Mindustry/files/5351445/MindustryV6Save.zip)
Import this save file and go onto "tar fields" in campaign mode.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/54417042/95517726-8f0e8980-098f-11eb-9af0-e99b54d3a339.png)

**Comment by Anuken** [comment]
fixed
