### ISSUE TITLE
Legs units can travel overtop of space

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2875]
**Platform**: Windows 10

**Build**: Custom build, from the latest commit, no modifications

**Issue**: This really shouldn't happen, I get this is more of a missing thing then a bug, but I feel like it classifies as a "bug".
![image](https://user-images.githubusercontent.com/34169172/95527075-08a77700-0992-11eb-9fe7-ccdc782d6cad.png)
Basically, legs units are able to walk over space like they are any other tile. Space should probably be treated like the black area on normal maps.

**Steps to reproduce**: Become a legs unit (atrax, spiroct, arkyid, toxopid), and walk overtop of a space tilea

**Link(s) to mod(s) used**: No mods used

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
> Space should probably be treated like the black area on normal maps.

more than just that, legs should also not pass/land on the space

**Comment by itcannotbe** [comment]
The real issue here is why is that plastanium wall block floating in space. XD.

**Comment by bvcbvc** [comment]
floating trash
thats why

**Comment by unjown** [comment]
> The real issue here is why is that plastanium wall block floating in space. XD.

make sense

**Comment by Quezler** [comment]
artificial asteroid, clearly

**Comment by Anuken** [comment]
Fixed.
