### ISSUE TITLE
Some mindustry BE bug I found

### ISSUE THREAD

**Issue by wolfy9011** [Anuken/Mindustry#2883]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux* android 

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 10313

**Issue**: *Explain your issue in detail.* when I open mindustry BE 10313 it just closes 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* I opened it

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* no mods

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* for some reason it doesn't give me the logs 
![Screenshot_2020-10-09-09-47-10](https://user-images.githubusercontent.com/72601626/95564009-10106400-0a16-11eb-8cbc-977bf5beb67a.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by wolfy9011** [comment]
![Screenshot_2020-10-09-10-11-10](https://user-images.githubusercontent.com/72601626/95565244-cd4f8b80-0a17-11eb-9b1f-29ff777b834f.png)

**Comment by Quezler** [comment]
same bug as 3 other issues today

**Comment by Gdeft** [comment]
readn't
