### ISSUE TITLE
When I open the game its suddenly close and show error

### ISSUE THREAD

**Issue by Maxfox1387** [Anuken/Mindustry#2884]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: *When I open the game(realese 10313) its suddenly close and show error(Version of phone - 5.1.5).*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ idk] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Gdeft** [comment]
Duplicate, please read #2883, #2880, #2878.

**Comment by Quezler** [comment]
404, crash report not found, but probably a duplicate like @Gdeft mentioned ^
