### ISSUE TITLE
ripple with silicon ammo stuck after switching to blast compound

### ISSUE THREAD

**Issue by TimofeiKH** [Anuken/Mindustry#2886]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: 10313

**Issue**: Ripple turrets cant shoot or turn after switching from silicon ammo to blast compound. Works only with cryofluid and stops working after any turret is loaded with a conveyor.

**Steps to reproduce**:
1.Place a ripple with cryofluid source and silicon source.
2.Change silicon source to blast compound.
3.Shoot remaining silicon.

**Link(s) to mod(s) used**: None

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/5354717/bug.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
