### ISSUE TITLE
Getting kicked from a server by moving items to the core

### ISSUE THREAD

**Issue by theredstone496** [Anuken/Mindustry#2887]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: 10329

**Issue**: When moving an item to the core on a server, it sometimes kicks me.

**Steps to reproduce**: I was moving items to the core and wanted to respawn quickly, but I got kicked. To reproduce:
1. Move the item
2. Respawn after a short delay.

**Link(s) to mod(s) used**: Vanilla

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
do you have a screenshot of the kick screen? (specifically the message/reason it kicks you with)

**Comment by Anuken** [comment]
Missing save.
