### ISSUE TITLE
Conveyor blending is wrong sometimes

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2891]
**Platform**: Android 9

**Build**: 10353

**Issue**:
Sometimes when placing conveyors and plast conveyors the roomba blendbits are wrong.
Example 1: was building plast conveyor line, titanium belt stayed blended.
![1](https://user-images.githubusercontent.com/39013340/95650133-0f88d380-0ad1-11eb-9661-5cda9b03918d.jpg)

Example 2: Thorium conveyor is blending very wrong
![2](https://user-images.githubusercontent.com/39013340/95650145-24fdfd80-0ad1-11eb-8c53-e47700d92535.jpg)

**Steps to reproduce**: *Can't reproduce in lab conditions*
1. Place line of titanium conveyors
2. Place line of plast conveyors ending at one, blending correctly changes.
3. Continue past it, should incorrectly stay blended.

**Save file**: [game.msav.txt](https://github.com/Anuken/Mindustry/files/5358649/game.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
*.msav.txt*
you pulled a tricky
genius

**Comment by DeltaNedas** [comment]
oh the file name ends in txt therefore its content must be ascii text

**Comment by Anuken** [comment]
This is **exactly** the problem I was talking about in https://github.com/Anuken/Mindustry/issues/2885#issuecomment-706205678. Reverting.

> Thorium conveyor is blending very wrong

I'm not fixing this one.
