### ISSUE TITLE
Import github mod

### ISSUE THREAD

**Issue by oguh43** [Anuken/Mindustry#2895]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *All*

**Build**: *104.6*

**Issue**: *Import GitHub mods doesn't work on newly created mods, due to GitHub changing "master" to "main", thus resulting in "NOT_FOUND" errors*

**Steps to reproduce**: *Try to import any mods uploaded on a new repo, with default branch "main"*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
haha fellow black people, whose lives matter to microsoft corporation, we have ended slavery!

**Comment by oguh43** [comment]
I respect every race but I am not using main over master

**Comment by Anuken** [comment]
Disregarding politics, I think "main" is a better name for, you know, *the main branch*.

However, it's a bit late to change it, considering `master` has been in use for years (decades?) and that's what tools expect to be the main branch.

**Comment by potatoisagender** [comment]
I like main branch, though I think master comes from early electronics and circuits. You have master and slave relays, and master switch and main switch (actually a thing, one cuts off all power, one shuts down things [I think], kind of like the power switch on the power supply unit and the power switch on your computer, they do different things). 
It also might come from plumbing, like master valves and slave valves

**Comment by oguh43** [comment]
The only thing I don't like is "slave" branches. But to change a decade-old system just because you became a policeman in America with 6 months of training is stupid
