### ISSUE TITLE
votekick trolls

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2897]
**Platform**: Server

**Build**: 107

**Issue**:
Votekick trolls run rampant with anonymous voting.
A group of 3 can kill an entire server and nobody will know who until it's too late

**Steps to reproduce**:
1. server
2. votekick troll
3. big sad`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
h

**Comment by Anuken** [comment]
not a bug

**Comment by DeltaNedas** [comment]
discussion

**Comment by Anuken** [comment]
we do not need discussion here
