### ISSUE TITLE
It is possible to get stuck in a lake if you delete a block under yourself

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#29]
![bug5](https://user-images.githubusercontent.com/30189017/34280006-b354e20e-e682-11e7-8e7a-a27e8b29e4e3.gif)

^^ The characters on the bottom of the screen are my keystrokes

![bug6](https://user-images.githubusercontent.com/30189017/34280158-bcfd2090-e683-11e7-86a3-f85296949632.gif)

^^how to get the bug

**Comment by Anuken** [comment]
Fixed as of 295ddc42aac0f144353e3de50b6b310c3dc112ed.

![](https://i.imgur.com/He8eZU7.gif)
