### ISSUE TITLE
@itemCapacity on core does not add attached vaults

### ISSUE THREAD

**Issue by Charlignon** [Anuken/Mindustry#2903]
**Platform**: Linux

**Build**: alpha build 107

**Issue**: On a processor, when reading the @itemCapacity property from a core with vault attached, the value is the capacity of the core itself, even though when you hover it, it display the correct capacity. 

**Steps to reproduce**: Read @itemCapacity of a core with vault with a Sensor block on a processor, then print it.

**Link(s) to mod(s) used**: None.

**Save file**: [itemCapacity issue.zip](https://github.com/Anuken/Mindustry/files/5360949/itemCapacity.issue.zip)

**Crash report**: None.

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
technically not a bug, but it would be a nice feature if it displayed the connected total 🤔
