### ISSUE TITLE
Dagger pile up ball of death

### ISSUE THREAD

**Issue by dinomendino** [Anuken/Mindustry#2909]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows

**Build**: steam build 107

**Issue**: Playing normally (2 players) then a couple daggers are stacked on top of each other and instakill everything, while also being invincible. running into them and dying seems to split them apart, like 4-6 of them. see pics
![20201010165850_1](https://user-images.githubusercontent.com/31171866/95683186-a334cf80-0bb7-11eb-8878-04d3249d2f9e.jpg) 
![20201010165850_1](https://user-images.githubusercontent.com/31171866/95683188-a465fc80-0bb7-11eb-8c39-a8428ec24aa1.jpg) 
![20201010165848_1](https://user-images.githubusercontent.com/31171866/95683189-a5972980-0bb7-11eb-8695-a4c6c896ecb0.jpg)

**Steps to reproduce**: Normal play in campaign maps

**Link(s) to mod(s) used**: N/A

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5361295/saves.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
