### ISSUE TITLE
Need a loading UI

### ISSUE THREAD

**Issue by islq** [Anuken/Mindustry#291]
There is only black screen for more than 5 ~ 10 seconds before menu display on android.

**Comment by Anuken** [comment]
This is difficult to implement, as it requires an [AssetManager](https://github.com/libgdx/libgdx/wiki/Managing-your-assets) and major asset-loading refactoring.

It'll be added with the UI remake, which is not in the near future.

**Comment by Luxray5474** [comment]
That is not considered an issue. And even if it is, it is quite low of a priority, as our main focus is the actual content *inside the game*.

**Comment by islq** [comment]
I think a simple splash screen is better than black only when lunch.
Can we change to game/screen mode and add a splash screen?
I have modified ModuleCore to implement screen interface of libgdx, and send a pull request too.
Please check it. Thanks
