### ISSUE TITLE
Item Limit on cores is ignored, infinite resource storage

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2910]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows 10, 64 bit

**Build**: BE Build 10389

**Issue**: When Inputting items to the core it can store more than should be possible

**Steps to reproduce**: put items into the core, as-well as have offsite locations launching items to the sector. however if you leave the sector and come back they return to the capacity limits.

**Link(s) to mod(s) used**: none

**Save file**: 
[MindustryV6Save.zip](https://github.com/Anuken/Mindustry/files/5361355/MindustryV6Save.zip)
the issue occurs on sector 6, it may happen elsewhere.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/54417042/95683258-10e0fb80-0bb8-11eb-9fb5-0343a66ae738.png)

**Comment by Legomonster33** [comment]
Also somewhat relating to this, sector 6 doesn't have an enemy drop point.

**Comment by MattMills** [comment]
Trying v6 and seems like there is a bug related to f12379e in that the core now continues to accept items from belts, but the item count is capped at the max, the belts don't block when the core reaches capacity.

**Comment by Anuken** [comment]
That's not a bug. There's even a special incineration effect for that.
