### ISSUE TITLE
Alpha, Beta and Gamma can be selected as wave enemies in the map editor

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry#2912]
**Note**: Not campaign related.
**Platform**: Android/iOS/Mac/Windows/Linux

**Build**: 10401

**Issue**: Alpha, Beta and Gamma can be selected as wave enemies in the map editor, even though they have no attack AI.
**Steps to reproduce**: 
1. Open the map editor.
2. Add Alpha, Beta or Gamma on a new wave enemies designation.
3. Load the map in-game and watch your 'enemies' simply sit pointlessly at the spawn point.

Possible solutions: Don't allow units which can't attack or lack an attack AI (Mono, Alpha, Beta, Gamma) to be selected as wave enemies or give Alpha, Beta and Gamma proper attack AI (Mono's still gonna be an awkward enemy though).

**Link(s) to mod(s) used**: None.
**Save file**: [Asteroids.zip](https://github.com/Anuken/Mindustry/files/5361971/Asteroids.zip)
**Crash report**: None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Spfwniw** [comment]
not a bug

**Comment by YellOw139** [comment]
So it's intended that people can make waves which won't work? Kinda hard for me to believe...

**Comment by Anuken** [comment]
This is nothing new. Not a bug.
