### ISSUE TITLE
payload go bonk over space

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2913]
**Platform**: Android 9

**Build**: 10391

**Issue**:
![bonk](https://user-images.githubusercontent.com/39013340/95690676-e53a3180-0c08-11eb-95a9-c344bd73f1f5.jpg)

**Steps to reproduce**:
1. Lead payload conveyor into space
2. Unit bonk on "wall" instead of drifting out into the cosmos

**Save file**: 
[bonk.msav.txt](https://github.com/Anuken/Mindustry/files/5362142/bonk.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
What else were you expecting to happen?

**Comment by DeltaNedas** [comment]
for the unit to be incinerated
