### ISSUE TITLE
I want to use 6.0 but it says its missing a mod.jason file. help me im a dummy

### ISSUE THREAD

**Issue by mindustrybeta** [Anuken/Mindustry#2916]

**Comment by Gdeft** [comment]
**Who's jason?** Also, use the template provided and this "issue" is **not** the game's fault, it's yours. There is a mod in your `mods/` directory that has no mod.json inside it, remove the mod and close this issue.

**Comment by imreallybadatnames** [comment]
y'know that one Jason

**Comment by DeltaNedas** [comment]
please never make a "bug report" again
