### ISSUE TITLE
Cant research core nucleus

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2917]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: windows 10 64 bit

**Build**: bleeding edge build 10405

**Issue**: *Explain your issue in detail.*
I cant research the core nucleus, it says its 1009% completed,

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Try to research core nucleus

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[MindustryV6Save.zip](https://github.com/Anuken/Mindustry/files/5362685/MindustryV6Save.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image](https://user-images.githubusercontent.com/54417042/95700585-68618480-0c15-11eb-886f-6a46c09426fa.png)
![image](https://user-images.githubusercontent.com/54417042/95700595-71525600-0c15-11eb-8528-4ed1f20e5242.png)

**Comment by Quezler** [comment]
anuke did change the research cost multiplier for it in a recent commit, i guess it broke everything that was in progress thats now already over the threshold

**Comment by Legomonster33** [comment]
> anuke did change the research cost multiplier for it in a recent commit, i guess it broke everything that was in progress thats now already over the threshold

would be pretty epic if it became unbroken
