### ISSUE TITLE
Enemies skip

### ISSUE THREAD

**Issue by danypand** [Anuken/Mindustry#2922]
**Platform**: *Android*

**Build**: *v5 104.6 - v6 10405*

**Issue**: *I'm just playing game when someone calls me. I paused and quit the game when wave is started and when I enter sector again enemies didn't spawned *

**Steps to reproduce**: *save and quit when wave is started and load sector*

**Link(s) to mod(s) used**: *none*

**Save file**: ###

**Comment by Quezler** [comment]
aside from failing to supply a world save, you listed 2 versions, did the same issue happen at least once in either?

**Comment by D-player1** [comment]
Good luck with the save file

**Comment by Anuken** [comment]
> Save file: ###
