### ISSUE TITLE
AI Building turned on. AI doesn't build on attack map.

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry#2925]
**Note**: Not campaign related.
**Platform**: Windows

**Build**: 10416 and 10427

**Issue**: On attack maps, with the 'AI Building' option enabled, the AI doesn't build. Also, the AI doesn't automatically spawn a basic building ship from the core. I even tried spawning the ships myself. They just stood there.

**Steps to reproduce**: Custom Game > Click an attack map > Set it to Attack gamemode > Customize Rules > Enemies > AI Building > Back > Play

**Link(s) to mod(s) used**: None
**Save file**: [TEST.zip](https://github.com/Anuken/Mindustry/files/5366923/TEST.zip)

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
AI building is not actually turned on for that save. There's an issue with maps having team-specific settings that overwrite custom rule settings.
