### ISSUE TITLE
Item source broken

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry#2926]
**Platform**: Linux

**Build**: 104.6

**Issue**: The item source doesnt output any items, nomatter what. The source is set to an item, I have no mods, and the game is unpaused

**Steps to reproduce**: https://imgur.com/a/8Dc2MuI

**Save file**: [I cant upload any files thanks.] https://anonymousfiles.io/wxaoZQFv/

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
`104.6` is quite old at this point, issue likely doesn't exist anymore in `bleeding edge` + i've never heard about it before 🤔

**Comment by Anuken** [comment]
The two save files you sent have nothing to do with the issue. This bug doesn't make any sense either.

**Comment by UltraBlackLinux** [comment]
I dont know how saves work so I just uploaded my whole folder. it said it was importand so I did it. I dont know what you can read outta them

**Comment by DeltaNedas** [comment]
press space to unpause

**Comment by UltraBlackLinux** [comment]
How cool that you didnt read the issue.

**Comment by Quezler** [comment]
@UltraBlackLinux were you in the editor mode by any chance?
> https://discord.com/channels/391020510269669376/477494303061442571/767306588813393950
