### ISSUE TITLE
Invincible Player after destroyed core in online PVP

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry#2929]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux* any i guess

**Build**: *V107 - Server*

**Issue**:
*PVP match with multiple teams.
After a teams core is destroyed the remaining players wont get killed but become invincible instead.
They can still attack other teams but wont get shot by any turrets.
In this picture I'm in Team Blue and our core got destroyed. I'm sitting next to Team Yellow Scatters and they dont shot me at all.
Bullets from other Players just went right through me and doesn't deal any damage.*

![image](https://user-images.githubusercontent.com/66265700/95880114-716a6700-0d77-11eb-98f5-6aaff57fb4a7.png)

**Steps to reproduce**: 
*PVP match with at least 3 teams - Own core got destroyed*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Well. Ecan PVP Server - no safe file available

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Hmm, i'm pretty sure when a core is destroyed and your ship is still alive, enemy can't target you

**Comment by Absolute359** [comment]
yes thats it
but this player is still able to damage other teams bases

**Comment by 50275** [comment]
I'm sure that the player can still be damaged by things that aren't projectiles e.g. thorium reactor explosions, and that it also applies to the same team's units.
Also, to get the save file press ESC and Save Game. I think this still works. Then you'll need to Export the file. Go to the menu (as if you just opened the game) and press Load Game. Then you'll need to find the game you saved. Then you'll want to find this button. 
![image](https://user-images.githubusercontent.com/68676339/95893731-0f4d3a00-0d56-11eb-99b1-6d73fa0b8b80.png)

**Comment by Absolute359** [comment]
I'm very aware how to export a safe file.
But like i mentioned its a PVP server and map changes like every hour.
And a little side note, I'm not the admin of this server.

**Comment by Anuken** [comment]
It doesn't matter if you're the owner or not. Games can be saved for local use in multiplayer.
