### ISSUE TITLE
Launching Core before Wave 10 on Ground Zero

### ISSUE THREAD

**Issue by jwiechers** [Anuken/Mindustry#2935]
**Platform:** Windows, reproduced on Android.
**Build:** 10465 Bleeding Edge
**Issue:** The most minor of issues or may even be intended behaviour, just thought I'd note it down: launching a core before wave 10 on Ground Zero immediately allows research of Frozen Forest in other sector while still blocking it in Ground Zero.
**Link(s) to mod(s) used:** none
**Save file:** [CoreLaunchBeforeW10GZ.zip](https://github.com/Anuken/Mindustry/files/5374768/CoreLaunchBeforeW10GZ.zip)
Note: sadly, I accidentally researched it before exporting the save, so not sure if it's helpful; then again, this is likely a pretty simple bug, if it is one at all. :-)

**Crash report:** N/A

**Comment by Anuken** [comment]
The objectives are supposed to require "capturing" of a sector, but since that (currently) isn't a thing it won't always work properly.
