### ISSUE TITLE
enemy doesn't attack

### ISSUE THREAD

**Issue by azureblue** [Anuken/Mindustry#2936]
Platform: Linux

Build: beta 108

Issue: The starting sector in the camping. Enemies don't attack and don't move from the spawn point. It happened at wave 21. As far as I remember it happened when I saved and quit while I was awaiting the 21st wave, and load the game again. But I was also able to reproduce it in the first wave.

![wave21](https://user-images.githubusercontent.com/4013688/95930149-157aff00-0dc6-11eb-82f3-6fb7ebc2c436.png)
![wave1](https://user-images.githubusercontent.com/4013688/95930180-26c40b80-0dc6-11eb-955c-71deb38e38aa.png)

Steps to reproduce: Just after game start go to the top of the map and hit wave button. 

[saves_1.tar.gz](https://github.com/Anuken/Mindustry/files/5374859/saves_1.tar.gz)
[saves21.tar.gz](https://github.com/Anuken/Mindustry/files/5374865/saves21.tar.gz)

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by azureblue** [comment]
Ok, they started attacking again after I placed a new block (turret and conveyor worked) ...

**Comment by potatoisagender** [comment]
Probably an error with the updating of enemies from anuke removing sectore capturing.
