### ISSUE TITLE
unit processor control

### ISSUE THREAD

**Issue by Suggestedone9** [Anuken/Mindustry#2941]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *windows*

**Build**: *beta build 108*

**Issue**: *when given the `move` command units go to 0, 0 instead of the given location*

**Steps to reproduce**: *get a processor to control a unit (i used a mono) and give it the move command. the unit will then go to the location 0, 0 instead of the given values*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *
[processor bug map.zip](https://github.com/Anuken/Mindustry/files/5376438/processor.bug.map.zip)

*. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *N/A.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
duplicate of #2842?

**Comment by SirMachinegun** [comment]
Not a bug

**Comment by Suggestedone9** [comment]
ok then, ill close it
