### ISSUE TITLE
v108 jar mod cannot find dependency

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#2945]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *108*

**Issue**: *jitpack build error  https://www.jitpack.io/#com.github.Anuken.Mindustry/core*

![제목 없음212](https://user-images.githubusercontent.com/61054554/95987348-43ae1c80-0e62-11eb-8052-e34976f9ad34.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This can't be fixed for older versions.
