### ISSUE TITLE
Anti-aliasing flicker with S-Pen

### ISSUE THREAD

**Issue by MrPelucaa** [Anuken/Mindustry#2949]
**Platform**: *Android - Galaxy tab A (P580)*

**Build**: beta build 108
**Issue**: Anti alias seems to flicker (on/off) if the S-Pen is close enough to trigger the pointer

**Steps to reproduce**: With the S-Pen taken out, if close enough, the anti-aliasing while flicker between on and off rapidly. This stops when the S-Pen makes contact with the screen. This happens both in game and in menus.

**Save file**: https://drive.google.com/file/d/1BkdclMS0Uq42F1KgPecfsjCaIcuaWRFC/view?usp=sharing
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
> **Build:** beta build 108
The build number under the title in the main menu.

**Comment by Anuken** [comment]
This seems like a problem with your specific device, and since I don't have anything similar this won't be fixed.

**Comment by MrPelucaa** [comment]
> 
> 
> > **Build:** beta build 108
> 
> "The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME."

![SmartSelect_20201014-122657_Mindustry](https://user-images.githubusercontent.com/29217412/96010896-b1cdf180-0e18-11eb-8a03-e4d099006024.jpg)

Anyway, just fixed it, if anyone is having trouble deactivate the superposition of hardware layers (use always the GPU for the composition of the screen)
