### ISSUE TITLE
Crashing when attempting to host a lan server

### ISSUE THREAD

**Issue by SumNutz** [Anuken/Mindustry#2950]
Build: Alpha 6, 108
Platform: Windows
[crash-report-10_14_2020_12_15_23.txt](https://github.com/Anuken/Mindustry/files/5379178/crash-report-10_14_2020_12_15_23.txt)
steps to recreate: 
- load up a sector in campaign mode
- press host lan server button
- close port forwarding info box

**Comment by Anuken** [comment]
Duplicate.
