### ISSUE TITLE
Restore support for Java versions older than 14

### ISSUE THREAD

**Issue by ProgVal** [Anuken/Mindustry#2951]
**Platform**: *Linux*

**Build**: v108

**Issue**: Starting with build 108, Mindustry requires Java 14 to build (and run?), which is a very recent version, so is not yet available in Debian stable, the current Ubuntu LTS, and possibly others. It's a surprising change, as v107 supported Java 8 (and possibly older ones).
Could you consider restoring support older version, eg. 11 (the latest LTS)?

Thanks!
(And thanks for making Mindustry btw)

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by walksanatora** [comment]
it came with my os (linux mint 20) and it is in the apt respoitory

**Comment by walksanatora** [comment]
try running 
sudo apt install openjdk-14-jdk

**Comment by ProgVal** [comment]
It's not in Debian stable. Look here: https://packages.debian.org/search?searchon=names&keywords=openjdk-14-jdk

It shows only bullseye (aka Debian testing) and sid (aka. Debian unstable).

openjdk-11-jdk, on the other hand, is also available in buster (Debian stable): https://packages.debian.org/search?searchon=names&keywords=openjdk-11-jdk

**Comment by walksanatora** [comment]
then manually install it https://adoptopenjdk.net/archive.html?variant=openjdk14&jvmVariant=hotspot

**Comment by walksanatora** [comment]
or just dont play till it gets updated

**Comment by Anuken** [comment]
This isn't happening. Mindustry uses many Java 14 features already.

**Comment by ProgVal** [comment]
Okay

I managed to fork Mindustry to restore Java 11 support; if anyone else is interested, you can find it here: https://github.com/ProgVal/Mindustry/tree/v108-java11
For now I only fixed the desktop builds.

**Comment by BlueWolf3682** [comment]
i dont see why mobile would need a fix, as my six year old tablet runs rb108 just fine. i dont know if java 14 is *that* new as something that old runs it just fine. if your os is that outdated i suggest either getting a device new enough to support the new updates to it or requesting updates to your operating system.

**Comment by Anuken** [comment]
You don't need Java 14 to run it, only to compile.

**Comment by carlwgeorge** [comment]
What is the minimum java version needed to run it?

**Comment by Anuken** [comment]
8
