### ISSUE TITLE
Waves do not count Poly air units as enemies

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#2952]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

 BE-10484

**Issue**: *Explain your issue in detail.*

The waves indicator does not consider the support air unit as an enemy even tho it flies and actively attacks in a survival setting. If all units are destroyed except for polly you are still able to skip to the next wave.

In the screen the wave spawned 4 poly and 4 crawlers. the wave timer/counter only counts the crawlers as enemies.

![bug1](https://user-images.githubusercontent.com/31638088/96058950-d7bfba00-0e49-11eb-87c4-090680e056cd.png)
![bug2](https://user-images.githubusercontent.com/31638088/96058957-db534100-0e49-11eb-9cd3-0f032bec9019.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Play a survival map. Have poly as the enemy unit with or without some other units, notice the enemy count is not including however many polys you have in the wave.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[save1.zip](https://github.com/Anuken/Mindustry/files/5381665/save1.zip)

_i got two more bug reports coming so yay_
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional. Polys are considered support, and therefore do not count as waves.
