### ISSUE TITLE
Mega unit yet again 

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#2953]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

BE-10484

**Issue**: *Explain your issue in detail.*

Mega stutters? sure. . . .

[https://youtu.be/q7qxAIW9GQ8](url)

(prob unrelated but they do not even try to move towards your core/defences/whatever. Oct is the same. AI is not fin I know)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Have mega unit in a wave and spawn. then head near them or ensure they are within range of something to shoot

why is it always mega that I find issues with?

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[mega1.zip](https://github.com/Anuken/Mindustry/files/5381865/mega1.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
