### ISSUE TITLE
fast (sandbox) building in camping in The Craters

### ISSUE THREAD

**Issue by azureblue** [Anuken/Mindustry#2954]
Platform: Linux
Build: beta 108
Issue: I'm able to build block fast just like in the sandbox mode. I think I shouldn't be able to do that in camping.

Steps to reproduce: Not sure, I think I just started playing in that sector and noticed it after a while.

[saves.tar.gz](https://github.com/Anuken/Mindustry/files/5381870/saves.tar.gz)

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
fixed
