### ISSUE TITLE
Supplying NaN to unit controls causes units to 'softlock' disappear.

### ISSUE THREAD

**Issue by Xeloboyo** [Anuken/Mindustry#2956]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *steam build 108.*

**Issue**: Supplying NaN to unit control commands causes units to 'softlock' disappear. The unit count will remain the same after the unit is gone preventing further production. This is probably unintended behaviour. Some units (e.g. corvus) will cause the screen to blackout for everyone on the server(if multiplayer) when they disappear.

**Steps to reproduce**: The issue was discovered by writing a bugged logic program that inadvertently divided 0 by 0, and controlled units. The issue was isolated by https://github.com/imreallybadatnames  (Пицца кальцоне (pizza calzone)) on discord from my initial program.
His isolated schematic, 'deletes' polys
`bXNjaAF4nGNgZGBkYmDJS8xNZRApyM9PUyjOyC8qSS1SKEstKs7Mz2PgTkktTi7KLCgBcRgYGfhzM5OL8nULivKTU4uL84sYQIIgwAfEVhVzklMSEgy0fE+d8Q4s0DhxfuWTU/oBHid1gj18Qg0CDB5o+Z47r6156nzgibP63qycTkcbd0kw/JAR4GQGAG4oLWk=`
My original buggy schematic, also 'deletes' polys
`bXNjaAF4nAHaASX+AAMAAQIABG5hbWUAC3VuaXQgZGVsZXRlAAtkZXNjcmlwdGlvbgAAAwALY29wcGVyLXdhbGwAD21pY3JvLXByb2Nlc3NvcgAHbWVzc2FnZQAAAAMAAAAAAAADAQABAAAOAAABYXicbZFbbsMgEEWdflVexSjfTZS4rRT1y6rUHXQDOGBDi8HlkcBGu56CebSVYiGLOQzMnbmbprn71kRoqWBw0BvKNPSuLcgX5AMycGWYwGndUsImaqB7auUCs+WAFEEpIR1FzjC7wLVLuKuEdvV6ZAjjULyLAnandlFMGNiOTGAmpv1+v01o5FZTmInWaCLH1g4hAfpFcl/UjhxN0FvBDPRx337YeYEOhDRvXxbxlHBo7VkKoySHiZhXLs+fqboHRXQ4zgIGy3hVkFWGksTl/3FtXP6HcQiFuznD0L2hkWo7RBrWtStjS/GpVEjh4Oqs/M1XAg2L1ldSXF9J4eB/W53lhcSXAz6EHvPErCvzqpZbX5Avk9iF7yW7EK4U/FCRv+lQlopdLOPmGvtYw68x1gZGpGIO9sUusnqVRAjLeebPMIXhGqLeKRLrrcc/Vq5u5QaTjU3TbJr7oibsmx9X+/diAQIAAgAABAEACmZpbmRpbmcuLi4BtQ7PBQ==`

**Link(s) to mod(s) used**: N/A

**Save file**: This was discovered to work on multiplayer as well as singleplayer, and tested on multiple servers, and a variety of unit types, all succeeded in being deleted.
The single player world I was testing unit logic in when the bug happened:
[h.zip](https://github.com/Anuken/Mindustry/files/5382535/h.zip)
A demonstration of the schematic:
![d109](https://user-images.githubusercontent.com/13158938/96079399-642cb400-0f00-11eb-94a2-45c5a4149e98.gif)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Xeloboyo** [comment]
this is the cause of issue:
https://github.com/Anuken/Mindustry/issues/2957

**Comment by imreallybadatnames** [comment]
hi xelo
its me Пицца кальцоне

**Comment by Anuken** [comment]
Fixed.
