### ISSUE TITLE
deletion of units but not for unit cap

### ISSUE THREAD

**Issue by 1010cool** [Anuken/Mindustry#2957]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows

**Build**:  108 beta release

**Issue**: *units being deleted

**Steps to reproduce**: *we were using sandbox mode to create a bunch of t5 units and then they started randomly disapearing
https://drive.google.com/file/d/1K6Y2TqUdxe_-p9VFQmoiZssUh3f2nIYq/view?usp=sharing
here is a video of what happened

[mind saves.zip](https://github.com/Anuken/Mindustry/files/5382566/mind.saves.zip)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by imreallybadatnames** [comment]
basically moving units to NaN makes them go poof

**Comment by Anuken** [comment]
See other issue.
