### ISSUE TITLE
Build Speed Bug

### ISSUE THREAD

**Issue by HumanBean06** [Anuken/Mindustry#2962]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam 108
**Issue**: *Explain your issue in detail.*
When you turn the building speed up really, really high, like 9999999+, everything costs one resource to build. For example: If you're building something that costs like 9k silicon, and you only have 8k, it'll build it. After that, you still can build that 9k sili cost with one silicon.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Well, I made a Custom game on the Tug of War 3 PvP map, raised the building speed really, really high (again upwards of 999k), and It happened, and what happened is explained above.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://file.io/uCO7OTEZXsZE
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No Crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't. `9999999+` approaches float precision limits.

**Comment by Legomonster33** [comment]
> Don't. `9999999+` approaches float precision limits.

should add a built in limit similar to how you can only launch with up to 9000 of a resource, when you enter a higher number it has a little prompt and snaps back down.
