### ISSUE TITLE
screen unreadable and discolored.

### ISSUE THREAD

**Issue by MaxBuelens** [Anuken/Mindustry#2965]
**Platform**: *Windows*

**Build**: *108 beta*

**Issue**: *discoloration and screen refresh issues
screen resolution 1920-1080 60p*

**Steps to reproduce**: *i just downloaded the 6.0 beta version*

**Link(s) to mod(s) used**: /

**Save file**: *dont have save game*

**Crash report**: */

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![Schermopname (6)](https://user-images.githubusercontent.com/42475109/96159096-8cbea900-0f14-11eb-8650-0b4031162e50.png)

**Comment by Anuken** [comment]
Can't reproduce, fix your graphics drivers/GPU.
