### ISSUE TITLE
Not working processor

### ISSUE THREAD

**Issue by Karo4eKY** [Anuken/Mindustry#2967]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *Mindustry BE v10517*

**Issue**: *Processor not working. Not react of jump or end. Any end. Blocks or end with last block of code.*

**Steps to reproduce**: *Update with new version*

**Link(s) to mod(s) used**: *No*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME
[asdasd.zip](https://github.com/Anuken/Mindustry/files/5387597/asdasd.zip).*

**Crash report**: *Not have crash report*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
missing save file.

**Comment by Karo4eKY** [comment]
Save file what?

**Comment by Karo4eKY** [comment]
Its not with save file. Its was game. Save file not play. i create new sandbox - not working. in server - not working.

**Comment by Karo4eKY** [comment]
save file not play - save file not have priority, its not with save file

**Comment by Karo4eKY** [comment]
Op, update

**Comment by Legomonster33** [comment]
If your reporting an issue you need to fill out all fields, including the one that says what your issue is. attaching photos also helps.

**Comment by Karo4eKY** [comment]
my problem - not working processor to any map or server. It just all. If more goodnes - processor go to first loop and not go to arrow jump or any end, f his stay or if loop end.

**Comment by DeltaNedas** [comment]
did you have a stroke go to brazil or both
