### ISSUE TITLE
Mindustry crashes on hosting a multiplayer game

### ISSUE THREAD

**Issue by timhorn1** [Anuken/Mindustry#2973]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux 64-bit or Windows 64-bit (both tested)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Version: beta build 108

**Issue**: *Explain your issue in detail.*
**Mindustry** **crashes** every time on hosting a Multiplayer game. I tested it **several times** with **different maps and scores**, but _always_ a window opened with the crash information while the game was closed. This bug is the same on both platforms (Windows and Linux).

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I can reproduce the bug every time I click on the multiplayer button, no matter which map or score I use.
The bug even exists after restarting the whole game.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
I used no mods.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 108
OS: Linux x64
Java Version: 1.8.0_131
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.desktop.DesktopLauncher.updateLobby(DesktopLauncher.java:230)
	at mindustry.ui.dialogs.HostDialog.lambda$runHost$15(HostDialog.java:83)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
wait for `109` or use `bleeding edge` (and close this issue)

**Comment by timhorn1** [comment]
Okay, I'm waiting.
I'm excited to test the newer version
