### ISSUE TITLE
Game doesn't restart to enable mods

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry#2976]
**Note**: Not related to campaign.

**Platform**: Windows

**Build**: BE 10528

**Issue**: After you import a mod, the game tells you that it will restart to load the new mods. It closes, but it never restarts.

**Steps to reproduce**: Import a new mod. Enable it. The game will tell you that it will restart to load the new mods. Once you press ok, the game closes and doesn't open again.

**Link(s) to mod(s) used**: [Redacted-Mod.zip](https://github.com/Anuken/Mindustry/files/5393315/Redacted-Mod.zip)

**Save file**: The issue happens in the main menu, not in-game.

**Crash report**: None. The game properly exits.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by YellOw139** [comment]
Nope. Cannot reproduce consistently. Will reopen if it proves to not be my fault.

**Comment by Anuken** [comment]
> After you import a mod, the game tells you that it will restart to load the new mods.

It's not supposed to restart itself.

The text reads:

> The game will now **exit**, to reload mods.

Restarting is not mentioned anywhere.

**Comment by YellOw139** [comment]
Ok. Thanks for bothering to check a closed issue though.
