### ISSUE TITLE
Launching with resources doesnt work

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#2977]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
(sorry)
**Platform**: windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 10539

**Issue**: *Explain your issue in detail.*
attempting to launch that you have previously lost with resources doesn't work, you just launch and have no resources

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
try to launch to a sector that has been previously lost.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[MindustryV6Save.zip](https://github.com/Anuken/Mindustry/files/5393446/MindustryV6Save.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed

**Comment by Legomonster33** [comment]
Now happens in beta 112 :o
