### ISSUE TITLE
Проблемы с компанией

### ISSUE THREAD

**Issue by Maxter-1** [Anuken/Mindustry#2980]
Баги связанные с компанией в игре Mindystry

**Comment by RanPix** [comment]
1 что за баг? 2 тут нужно писать только на английском что бы все тебя понимали

**Comment by Maxter-1** [comment]
Когда выходишь из компании на первой карте и придëшь обратно, то враги стоят на точке появления. 
![Screenshot_2020-10-16-22-04-38-542_io anuke mindustry](https://user-images.githubusercontent.com/69448791/96298763-b0105380-0ffb-11eb-8282-e3c46ce4950f.jpg)

**Comment by RanPix** [comment]
пиши на английском разработчик не будет переводить текст!!!

**Comment by Maxter-1** [comment]
Sorry

**Comment by Maxter-1** [comment]
Sorry, I will continue to write in English

**Comment by Maxter-1** [comment]
I left the first company map, but when I go back, the enemies from the next waves do not move from the point of appearance
![Uploading Screenshot_2020-10-16-22-04-38-542_io.anuke.mindustry.jpg…]()

**Comment by Maxter-1** [comment]
![Uploading Screenshot_2020-10-16-22-29-39-862_io.anuke.mindustry.jpg…]()

**Comment by Maxter-1** [comment]
Here is a photo with a problem
![Uploading Screenshot_2020-10-16-22-29-39-862_io.anuke.mindustry.jpg…]()
