### ISSUE TITLE
editor ui is squished on phone

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2981]
**Platform**: Android 9, Samsung A20e

**Build**: 10518

**Issue**:
ScrollPanes should be used for tools, they are causing the blocks to be partially obscured (name, bottom row)
![Screenshot_20201016-182925_Mindustry BE](https://user-images.githubusercontent.com/39013340/96299491-ab3fa580-0fe3-11eb-8486-532462975be7.jpg)

**Steps to reproduce**:
Open editor.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, it's the editor center button taking up too much space. I'll remove it on mobile.
