### ISSUE TITLE
Company problems

### ISSUE THREAD

**Issue by Maxter-1** [Anuken/Mindustry#2982]
Bugs related to the company in the game Mindustry.

**Comment by Maxter-1** [comment]
Came out and saved from the first company map, but when I go back, the enemies from the next waves do not move from the point of appearanceI 
![Uploading Screenshot_2020-10-16-22-29-39-862_io.anuke.mindustry.jpg…]()

**Comment by DeltaNedas** [comment]
1. template
2. use https;//translate.yandex.ru

**Comment by Maxter-1** [comment]
If you are faced with this problem, then put any building in the area of attack of the vrog. Enemies will immediately attack the building and go to the base as expected.

**Comment by Maxter-1** [comment]
Thanks, #DeltaNedas

**Comment by Legomonster33** [comment]
duplicate
