### ISSUE TITLE
atmosphere occludes other planets and orbit rings

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2984]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
h

**Platform**: Android 9

**Build**: 10518

**Issue**:
Atmosphere shader bit of planet occludes other planets and orbit rings.
![1](https://user-images.githubusercontent.com/39013340/96306780-dfb95e80-0fef-11eb-9ffa-383ab0dc3238.jpg)
![2](https://user-images.githubusercontent.com/39013340/96306791-e3e57c00-0fef-11eb-9d3e-a2ae8a5f75ae.jpg)

**Steps to reproduce**:
Cover thing with the atmosphere of serpulo, should still be visible but just disappears.
Atmosphere shaders + bloom are on.

**Link(s) to mod(s) used**: wip routorio version, you can still see it with orbit rings

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix.
