### ISSUE TITLE
Light blending bug

### ISSUE THREAD

**Issue by DeSpecTDr** [Anuken/Mindustry#2985]
**Platform**: Windows
**Build**: 10287
**Issue**: 
If several light sources (color doesn't matter) are placed close to each other, wierd darker area appears where the light intersects
![light_blending](https://user-images.githubusercontent.com/73001251/96311091-6599d180-1011-11eb-931f-f6b864a2497a.PNG)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
