### ISSUE TITLE
Combustion/Steam generator no longer explode

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#2986]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

BE-10552

**Issue**: *Explain your issue in detail.*

When a combust/steam generator is given blast compound it no longer takes damage and explodes

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Feed a combust/steam generator with blast compound

**Save file**: *The (zipped) save file you were playing on when the bug happened. 

[combust.zip](https://github.com/Anuken/Mindustry/files/5394791/combust.zip)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul10** [comment]
I think its wasn't bug

**Comment by Anuken** [comment]
Your save has reactor explosions disabled. This affects combustion generators as well.
