### ISSUE TITLE
Some draug miner drones keep mining

### ISSUE THREAD

**Issue by iuriguilherme** [Anuken/Mindustry#2987]
**Platform**: *Windows*

**Build**: *104.6*

**Issue**: *Some draug miner drones keep mining when they shouldn't - core is already full. They seem to mine endlessly. They are not taking resources to the core, they just mine. Forcing them to move by come close seem to make them stop. A screenshot is attached.*

**Steps to reproduce**: *Fill the core with lead and copper, while still filling with graphite. The map is frozen desert and it's the first time playing it after two plays at ground zero.*

**Save file**: [2987.zip](https://github.com/Anuken/Mindustry/files/5395029/2987.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

**Screenshot**: ![screenshot 108](https://user-images.githubusercontent.com/2027447/96329035-7b15f800-101f-11eb-8c7e-4ce7bf92e8ac.jpg)

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by QuarterEighth** [comment]
This happens still as of v108 I believe.

**Comment by Anuken** [comment]
Haven't seen it happen in the BE builds.
