### ISSUE TITLE
Not able to host game

### ISSUE THREAD

**Issue by BRUL** [Anuken/Mindustry#2991]
**Platform**: *Mac*

**Build**: Beta 108

**Issue**: Program crashes when trying to host a game

**Steps to reproduce**: Start a game or campaign map. Pause. Host.

**Link(s) to mod(s) used**: none

**Save file**: any save produced the bug

**Crash report**: 
<img width="532" alt="Screenshot 2020-10-17 at 12 48 35" src="https://user-images.githubusercontent.com/97167/96335246-a75d6300-1077-11eb-9b31-293dc45b61d5.png">

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
the crash log is the contents of that file, no the path. ^

also, this bug (from what i can tell) has been fixed, wait for `109` or use `bleeding edge`.

(and close this issue)

**Comment by DeltaNedas** [comment]
>   [ X] I have searched the closed and open issues to make sure that this problem has not already been reported.
