### ISSUE TITLE
orbit ring for moon is wrong from serpulo's PoV

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2993]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.
h

**Platform**: Android 9

**Build**: 10552

**Issue**:
When looking from the moon's PoV, everything is normal.
When looking from Serpulo's, the orbit ring of the moon is wrong while the moon itself is positioned correctly.
I'm guessing the orbit ring code mistakenly adds the parent position to the already transformed moon position, sun is 0, 0, 0 so Serpulo isn't affected.
Serpulo PoV: ![1](https://user-images.githubusercontent.com/39013340/96335881-3c0d9400-106b-11eb-8238-c722921bbfc8.jpg)
Moon PoV: ![2](https://user-images.githubusercontent.com/39013340/96335884-3fa11b00-106b-11eb-9127-d8f9b460c0c3.jpg)

**Steps to reproduce**:
1. load mod
2. look at orbit ring
3. switch to moon
4. look again

**Link(s) to mod(s) used**: [testcase.zip](https://github.com/Anuken/Mindustry/files/5395542/testcase.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix.

**Comment by DeltaNedas** [comment]
why not
