### ISSUE TITLE
Pathfinding doesn't work

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#2994]
**Platform**: Windows

**Build**: Latest beta release

**Issue**: Units are standing still at the spawn not moving to the core

**Steps to reproduce**: Load the save file

**Link(s) to mod(s) used**: None

**Save file**: 
[pathfinding.zip](https://github.com/Anuken/Mindustry/files/5395656/pathfinding.zip)

**Crash report**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
possibly already fixed, check the `bleeding edge` build to see if the issue persists, or not. 🙃

**Comment by XEN0PHIL** [comment]
Already [reported](https://github.com/Anuken/Mindustry/issues/2936) and [fixed](https://github.com/Anuken/Mindustry/commit/6b4a7d025b20f6d2cb7b8722204fa7b9a316fdfa) (not released). Also:
> "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Comment by Khanx** [comment]
> Already [reported](https://github.com/Anuken/Mindustry/issues/2936) and [fixed](https://github.com/Anuken/Mindustry/commit/6b4a7d025b20f6d2cb7b8722204fa7b9a316fdfa) (not released). Also:
> 
> > "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

I've had the same problem with the build 108

**Comment by Shawak** [comment]
Probably "latest"isn't, but since I said latest beta release it should be kinda obvious. Also sorry for the duplicate, couldn't find the issue searching for "pathfinding".

**Comment by DeltaNedas** [comment]
latest beta release also means a beta release from 2 nights ago
how hard is it to type 5 digits
