### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SwiatoslaW64** [Anuken/Mindustry#2997]
**Platform**: *Android

**Issue**: *new wave just started and the enemy just stay in  circle  .*
https://photos.app.goo.gl/oEai6SWGs17246iT7
That screenshot of bug

**Comment by XEN0PHIL** [comment]
Already [reported](https://github.com/Anuken/Mindustry/issues/2936) and [fixed](https://github.com/Anuken/Mindustry/commit/6b4a7d025b20f6d2cb7b8722204fa7b9a316fdfa) (not released).
Also do not delete important lines like **Build:**
