### ISSUE TITLE
bleleding beta suck

### ISSUE THREAD

**Issue by TheChosenEvilOne** [Anuken/Mindustry#300]
pls help, I have problem

when I go too block in beta I cna't prse tinghs wihh anthing and ther no nosie and it suck pls fix
and I cna built in custom the blocks not in sector
and power node not work ![image](https://user-images.githubusercontent.com/34602646/47955680-2f89f100-dfa4-11e8-863c-5aff92d0404f.png)
and whne mltiplayer be added and port frowrading is to complicate
amd when I go too mindustry.indielm.com it say 404
bleleding edg feel werid and unifnishd
WHRE TELEPROMPTER AND PULES CONVEOR
ps. how conveor tunnl work?

> I am sorry

**Comment by TheChosenEvilOne** [comment]
I am sorry

**Comment by Luxray5474** [comment]
also how host iP or IP      or Ip (sry am not a programmr xddd) servre? i want to play with m yfriend thx

p.s. who has sandbox server/ thx cxxxx

**Comment by Sonnicon** [comment]
_**ah**_

**Comment by Luxray5474** [comment]
how to that

**Comment by Kostia4381** [comment]
sudo rm -rf / --no-preserve-root

workde pefectrly :D

**Comment by Anuken** [comment]
![0](https://user-images.githubusercontent.com/10100000/47956679-a9a77f00-df7e-11e8-8a90-2981df25a6f9.png)

**Comment by Milinai** [comment]
Mass driever not woeks plz someone help i hav problems
also why is no sound is it bug
i mech on android phone i cant connect powernod and i cnat be alpha help
4.0 suxx

**Comment by Luxray5474** [comment]
HALP I CNAT GET OUT OF MWCH ON MOBLE I CAN TBETSA SUCK >:(

**Comment by Anuken** [comment]
a
