### ISSUE TITLE
Green lines and other visual artifacts cover the whole window

### ISSUE THREAD

**Issue by JornVeken** [Anuken/Mindustry#3001]
**Platform**: *Windows*

**Build**: *steam build 108*

**Issue**: *Green lines covering the entire screen and other visual artifacts*

**Steps to reproduce**: *Launched the game*

**Link(s) to mod(s) used**: *None*

**Save file**: *It happens even in the title screen. No doubt this changes anything.*

**Screenshot**:
![Capture](https://user-images.githubusercontent.com/51487819/96350977-e4961500-10b8-11eb-808e-858719d60173.PNG)

On a laptop, GTX 960M
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> [X ] I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you haven't.
