### ISSUE TITLE
rhino crash with eval

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3002]
**Platform**: Android 9

**Build**: 10570

**Issue**:
Eval'ing a called lambda that prints an assigned variable crashes rhino (no exception is caught)

**Steps to reproduce**:
```js
const code = "const r = Vars.renderer.planets; print('alive - its not the assignment'); print(r); print('what?')"

try {
	print("try run " + ["(() => {", code, "})();"].join("\n"));
	eval(["(() => {", code, "})();"].join("\n"));
	Log.warn("No exception thrown?")
} catch (e) {
	Log.warn("Caught exception")
}
```
Read f8, Warn = good, Error = bad

**Link to mod used**: [testcase.zip](https://github.com/Anuken/Mindustry/files/5396411/testcase.zip)

**Log**:
```
[I] [test/main.js]: try run (() => {
const r = Vars.renderer.planets; print('alive - its not the assignment'); print(r); print('what?')
})();
[I] [test/main.js]: alive - its not the assignment

[E] [test/main.js]: NullPointerException: Attempt to invoke interface method 'java.lang.Object rhino.Callable.call(rhino.Context, rhino.Scriptable, rhino.Scriptable, java.lang.Object[])' on a null object reference
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not fixing any more Rhino bugs. Use Java, or find a better alternative.

**Comment by sk7725** [comment]
Nooooooooooo...
