### ISSUE TITLE
Oil extractor visual glitch?

### ISSUE THREAD

**Issue by potatoisagender** [Anuken/Mindustry#3016]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Build 109
**Issue**: *Explain your issue in detail.*
Oil extractor looks like it has oil in it when fed water, even with no power or sand
![image](https://user-images.githubusercontent.com/63363206/96386255-a64f3300-1156-11eb-8cfc-fd5a557368b6.png)
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just fed water to an oil extractor
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
I have no idea how to and am too lazy to find which save it is. Image is self explanatory, anyway
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
