### ISSUE TITLE
Ammo sensible in logic returns max ammo in certain maps

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#3018]
**Platform**: Windows 10

**Build**: 109

**Issue**: Attempting to use logic to get the current ammo of certain maps, return the max ammo capacity instead of the current ammo capacity. Appears to occur on maps with rule for ammo modified.

EDIT: Entering the map without changing the rules, seem to have the ammo sensible working, despite the map needing ammo.

**Steps to reproduce**: Set up a custom game and open a map, adjust the rule to include ammo, and test it with a basic program to print the current ammo.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[ammotest.zip](https://github.com/Anuken/Mindustry/files/5398913/ammotest.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by claw4oo** [comment]
Opening the editor and editing the map rules to have ammo enabled, seem to still have issues.
I'm unsure of the direction on how to reliably replicate this on any map

**Comment by Anuken** [comment]
fixed
