### ISSUE TITLE
There is a hug were bridges don't work idk why

### ISSUE THREAD

**Issue by ricardo1003** [Anuken/Mindustry#3019]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Bleeding-edge build 10613

So I was trying to put surge alloy into core and I make a phase bridge, only 1 surge passed and the anothers wont

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Idk just place a phase bridge
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Nothin
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
F I don't have one, I was on public server, there is image:
![IMG_20201018_222637](https://user-images.githubusercontent.com/67872140/96398929-aa00ab00-1192-11eb-85cb-417f03c24663.jpg)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ricardo1003** [comment]
Btw there was energy but enemyes destroyed energy

**Comment by claw4oo** [comment]
You need full energy to use a phase bridge

**Comment by ricardo1003** [comment]
Yea ik it had energy but when I take the foto enemyes destroyed energy

**Comment by GlennFolker** [comment]
then take another screenshot. we need an exact proof

**Comment by ricardo1003** [comment]
Wait do u said full energy?

**Comment by ricardo1003** [comment]
Aaaa

**Comment by ricardo1003** [comment]
that's why not worked ty
