### ISSUE TITLE
Bridges do not return/cross from 180 degrees

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#3020]
**Platform**: Windows 10

**Build**: 109

**Issue**: Liquid and item bridges do not return or even accept items if they are in a 180 turn around/cross. Happened in build 108 as well, worked in 106, version before the major alpha update.

**Steps to reproduce**: Place two bridges at their max range, connect them, then place a third bridge under both of them.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[bridgeandturretaimbug.zip](https://github.com/Anuken/Mindustry/files/5398957/bridgeandturretaimbug.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GlennFolker** [comment]
pretty sure bridge conveyors can't transfer to a direction where it accepts the content

**Comment by claw4oo** [comment]
Each bridge is spaced out by one block, 3 bridges in total
The behaviour worked before in the previous version too
