### ISSUE TITLE
Turret shoot position appears to be using a different coordinate system

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#3021]
**Platform**: Windows 10

**Build**: 109

**Issue**: It appears turrets shootx and shooty are still using the previous coordinate system(unsure if just arbitary coordinates). Old logic processors using shootx and shooty of one turret no longer seem to work.

**Steps to reproduce**: Create a logic processor with this code.

sensor x lancer1 @shootX
sensor y lancer1 @shootY
sensor shoot lancer1 @shooting
control shoot lancer2 x y shoot 0
print x
print "\n"
print y
printflush message1

Used messages to better identify where it was aiming.
Save file has this setup, as well as a system that uses a player's shoot position to aim instead.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[bridgeandturretaimbug.zip](https://github.com/Anuken/Mindustry/files/5398976/bridgeandturretaimbug.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by claw4oo** [comment]
Looks like a couple of people got mentioned, sorry about that.

**Comment by shadmansaleh** [comment]
Unsure What you mean. But I think The quardinate system was changed 2 days ago by commit @ 8043c09e2b70971ca1a650ef3d1fd34963d3f4cd

The message said it now uses tile based quardinates.

**Comment by itcannotbe** [comment]
@claw4oo Read the change-log.

**Comment by Anuken** [comment]
fixed
