### ISSUE TITLE
Units can build walls and other things, trapping their allied ground units

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3031]
**Platform**: windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* bleeding edge 10613

**Issue**: *Explain your issue in detail.* enemy units can build and trap their own ground units

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
play the game on a map where polys spawn

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[MindustryV6Save.zip](https://github.com/Anuken/Mindustry/files/5403742/MindustryV6Save.zip)
Go to the sector named "ISSUE HERE ANUKE" south west of ground zero

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/54417042/96492179-42d60b80-1211-11eb-8c4b-af115c014ab6.png)

**Comment by Anuken** [comment]
I'm aware of this, and there isn't really any good solution that can cover all cases.

**Comment by Legomonster33** [comment]
> I'm aware of this, and there isn't really any good solution that can cover all cases.

maybe have the builder units run a pathfind to the players core and avoid blocking it?

**Comment by Anuken** [comment]
That's very expensive.

**Comment by Legomonster33** [comment]
> That's very expensive.

have a heatmap thats generated upon world load that builder units compare against as to where to build?
