### ISSUE TITLE
Campaign Rollback Bug

### ISSUE THREAD

**Issue by jojoblackFr** [Anuken/Mindustry#3032]
**Platform**: *Windows*

**Build**: *109 [Beta]*

**Issue**: *when i save and quit the game in campaign and close the window, i got a BIG rollback in the research menu when i restart the game (all building is on the map but i dont have the research)*

**Steps to reproduce**: *save and quit an campaign and reload the game*

**Link(s) to mod(s) used**: *none*

**Save file**: *my export data
[fdzgweyhsereyhwy6d2y2q4yda4wxr3w5adqx4yw4yq.zip](https://github.com/Anuken/Mindustry/files/5403973/fdzgweyhsereyhwy6d2y2q4yda4wxr3w5adqx4yw4yq.zip)
.*

**Crash report**: *no crash for time*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by jojoblackFr** [comment]
sorry for the zip name xD

**Comment by notrealn** [comment]
![image](https://user-images.githubusercontent.com/56411504/96497764-29d15880-1219-11eb-91cb-a829f5e9297a.png)
uhh

**Comment by Anuken** [comment]
Can't reproduce this.
