### ISSUE TITLE
Salt Flats map edit

### ISSUE THREAD

**Issue by MacBookAir2018** [Anuken/Mindustry#3035]
This is an issue in the build-in attack map called "Salt Flats". Since the unit mechs are now compressed into one, when I got into the map, what I see is basically 6 empty space that are supposed to have the factories. The water system is also weakened (due to the affinities of white titles) and they aren't enough to support the drills. The silicon smelter also aren't enough to produce the daggers as well since now they also requires leads to produce.
Please fix this. Thanks

**Comment by DockedSiamang22** [comment]
No
