### ISSUE TITLE
ExtendContented items do not get configured in sorters and sources

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3036]
**Platform**: *Windows*

**Build**: *10623*

**Issue**: *items made with extendContent(Item, name, {some code}) does not get saved in item sorters, sources, etc. that uses Item class configure. This is probably because such items are extended from items but are not exact items(so the configure of Item calss does not work). To make items with overriden functions(especially icon()) work, what should be done? (Hopeful approach: make the configure() receiving end catch things that are instanceof Item, not just item)*

**Steps to reproduce**: *Install mod sk7725/Immundustry and try setting an item source to any of the auto-generated items.*
Related code 1:
```js
function createItem(from, name, color){
  var item = extendContent(Item, name, {});
  print("Add Item ID: "+item.id);
  try{
    item.color = color;
  }
  catch(versionTooLowIHope){
    print(versionTooLowIHope);
  }
  item.explosiveness = from.explosiveness;
  item.flammability = from.flammability;
  item.radioactivity = from.radioactivity;
  item.hardness = from.hardness;
  item.cost = from.cost;
  return item;
}
```
Related code 2:
```js
function newProtein(unit){
  var clr = getColor(unit);
  print("[#"+clr.toString()+"]"+"Color[]");
  var itemIcon = makeTextureRegion(clr, "marker-"+unit.name);
  print("Item Icon: "+itemIcon);
  var item = extendContent(Item, "marker-"+unit.name, {
    color: clr,
    icon(cicon){
      return itemIcon;
    }
  });
  print("Item: "+item.name+" "+item.id);
  return item;
}
```

**Link(s) to mod(s) used**: *sk7725/Immundustry*

**Save file**: *Codewise issue.*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
duplicate, see my issue

**Comment by sk7725** [comment]
Alternative solution: return to using the id as configuration, like in 5.0(no problems that I can think of...for now)!

> duplicate, see my issue

The approach and information provided is different.

**Comment by Anuken** [comment]
> Alternative solution: return to using the id as configuration

This isn't happening. That's a bad solution for many reasons.

> The approach and information provided is different.

That may be the case, but this issue is still the same. I won't be fixing this anytime soon.
