### ISSUE TITLE
Going back from panoramic views creates bizzare formatting

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry#3040]
**Platform**: *Android*

**Build**: *109 and older*

**Issue**: *Going back from panoramic to portrait orientation maintains the menu panoramic format, so down part of screen is black. Most noticeable when closing the editor.*

**Steps to reproduce**: *Any change from panoramic to portrait mode will trigger the effect.(afaik)*

**Save file**: *happens in menu, no save required.*

**Crash report**: *Game do not crash. Only rotation is bizzare (panoramic format in portrait mode).*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kubek0212** [comment]
https://cdn.discordapp.com/attachments/464567579747287040/768038772712538142/YouCut_20201020_110928779.mp4
That's how it looks

**Comment by Anuken** [comment]
This doesn't happen on my phone, or in an emulator. Won't fix.

**Comment by DeltaNedas** [comment]
replicated. Roughly, what i did was:
1. be in landscape
2. lock screen
3. unlock it (samsung very smart and dont waste 1 byte of memory to save screen rotation yes) now in portrait
4. weird thing happen
![Screenshot_20201021-185025_Mindustry BE](https://user-images.githubusercontent.com/39013340/96758390-3fd04c00-13c6-11eb-9a51-dbccf0daaf20.jpg)

On BE from ~30 mins ago

**Comment by Anuken** [comment]
Nope, that doesn't happen on my phone either.

**Comment by DeltaNedas** [comment]
i love apache license which allows me to rtfsc and figure out why my shitty oem is doing something that anukes phones shitty oem doesnt yes
