### ISSUE TITLE
Delete key doesn't work in input boxes

### ISSUE THREAD

**Issue by l29ah** [Anuken/Mindustry#3044]
**Platform**: Linux

**Build**: v109

**Issue**: It should remove a character after the cursor, but does nothing.

**Steps to reproduce**: Try to adjust the amount of resources sent with the core to a new base in the campaign.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
