### ISSUE TITLE
Screen to zoomed in; can't change

### ISSUE THREAD

**Issue by ReinFuentes** [Anuken/Mindustry#3046]
Platform: mobile 

Build: v6

Issue: Whenever I open The mindustry app on v6, it appears to have zoomed in quite a bit, and I cannot click past the "you are playing mindustry v6: it is currently in beta, so there may be issues" thing.

This happened  this morning, when I had opened the app. I had not done anything our of the ordinary

I have not used any mods

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_20201020-120236_Mindustry](https://user-images.githubusercontent.com/73193072/96627410-0ddbbe80-12ce-11eb-92bc-6494091dba8b.jpg)

**Comment by Anuken** [comment]
You accidentally set the UI scale too high. Not a bug.

**Comment by DeltaNedas** [comment]
look for uiscale\0\x01 and set the 1 to 0 in a hex editor
