### ISSUE TITLE
yeah.....

### ISSUE THREAD

**Issue by Elactic** [Anuken/Mindustry#3047]
**Platform**:  *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
109 beta
**Issue**: *Explain your issue in detail.*
you know i cant place 1x1 and 2x2 blocks on any side of the edge of the map
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
since 107 beta, not sure if it is bug or not
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods used
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
![bug 2](https://user-images.githubusercontent.com/73202064/96651932-7725f680-12fb-11eb-9e90-2a740423a5cd.jpg)
![bug](https://user-images.githubusercontent.com/73202064/96651934-7725f680-12fb-11eb-871d-b11a7c76f9c4.jpg)
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
**Other**
if your dont understand what am I talking about, DM me on discord 
Elactic#9820
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're not supposed to be able to.
