### ISSUE TITLE
Measuring item capacity via logic of blocks that dont hold items yields 10

### ISSUE THREAD

**Issue by Xeloboyo** [Anuken/Mindustry#3048]
**Platform**: *Windows*

**Build**: *steam build 109*

**Issue**: *See title*

**Steps to reproduce**: 
bXNjaAF4nGNgZmBmYmDJS8xNZRDMLEnNVUhOLEhMziypVCjPqGTgTkktTi7KLCjJzM9jYGBjYCsuzyxJzgDS+UUlqUUM3MX5OYlFugWJeak5DPy5mclF+boFRfnJqcVABQzcuam5+UWVusmpOTkM7LlAwcT0VAaQOSDAxcjICKQYWRkYWIFuYGBgYmBkZmBkYOQDsqdVzKnt9+U6ZCDQqt696ouI8/W8X8UMBye3GNxykHJWc7XZtdrixg6NS+ey7lXfP2DDypCvdr6/Y2JFGWeqr0j0nhsul0PZc3Oqrmovc667lXIsdoW787m3Ssxsb1/2c178FTJBaVbx5k27efff/9DuevfOGWW/I2veX7kWtK8pWXPO5hOX9ZlVX23Yo97Z9Oq2m4+quPdvnc+MWwPysxhZgA5kArkZSLAwMnAbGujAECMAm9pxPg==

scheme measures item capacity of a few blocks.
![image](https://user-images.githubusercontent.com/13158938/96682644-d7cd3600-13c4-11eb-998c-30e4c2c53cd5.png)

**Link(s) to mod(s) used**: *N/A

*

**Save file**:
[fdko.zip](https://github.com/Anuken/Mindustry/files/5413768/fdko.zip)

**Crash report**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
iirc the *default* itemCapacity for every block is 10, even for those that don't actually use it.

**Comment by Anuken** [comment]
That's technically correct. They can hold 10 items, but they don't accept any.
