### ISSUE TITLE
block status for turrets should be red in this case

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3049]
**Platform**: `mac`

**Build**: `10655`

**Issue**: `the block status indicator for turrets is green even when there is no ammo inside it at all`

![Screen Shot 2020-10-21 at 08 43 16](https://user-images.githubusercontent.com/3179271/96682694-7c298b00-1379-11eb-931f-ba7de72f1399.png)

**Steps to reproduce**: `build a turret`

**Link(s) to mod(s) used**: `null`

**Save file**: [turret.msav.zip](https://github.com/Anuken/Mindustry/files/5413811/turret.msav.zip)

**Crash report**: `null`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this pwoblem has not already been reported.**

**Comment by BlueWolf3682** [comment]
"**pwoblem**"

**Comment by XEN0PHIL** [comment]
> "**pwoblem**"

Anuke did an oopsie-woopsie
