### ISSUE TITLE
Flares use a Bomber unit esq ai, making them practically useless

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3050]
**Platform**: windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Bleeding edge 10655

**Issue**: *Explain your issue in detail.*
flares use the same ai that horizons do (bomber type ai), darting across enemy bases shooting while above them, causing them to only be dealing damage about 5-10% of the time,

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
have a flare attacking something.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: N/A

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional. They've *always* had this AI.
