### ISSUE TITLE
Found many problems

### ISSUE THREAD

**Issue by Nanosuitwitdaboomboxwhatsongwillhepla** [Anuken/Mindustry#3057]
I am playing on a Google pixel a3 if that matters or not and while I was playing I had encountered 3 major bugs

1. Frozen forest is in sandbox mode (I'm able to build instantly and I only require 1 resource (I'm not sure of each or by itself) to build)

2. When I had captured stained mountains and then went to a previous location (the places I went to were 171 and 215) they had then became captured

3. When moving from one zone to another the enemy's in the new zone will stay in the drop point and not move unless the player begins to build or decondtruct

**Comment by D-player1** [comment]
Bruh, you killed the template

**Comment by Anuken** [comment]
No template.
