### ISSUE TITLE
Power Insufficiency but i have 75 generators????

### ISSUE THREAD

**Issue by ChrisThePersonWithoutSanity** [Anuken/Mindustry#3059]
**Platform**: Windows

**Build**: Release Build 104.0

**Issue**: I have 50 Thermal generators on a hot surface and have 750k power but it wont power my factories plus another 750k because of generators and still no change

**Steps to reproduce**: I got the bug because i think i had too many nodes
**Link(s) to mod(s) used**: No mods were included in the process
**Save file**: I Github does not support Msav files so cant really answer this one

**Crash report**: No crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Bruh, save file is a zip, not a msav file

**Comment by Anuken** [comment]
No save.

**Comment by DeltaNedas** [comment]
zip the save or rename it to .txt or something

**Comment by Esnardo** [comment]
Please try again with a save, I really want to see it. I'm gonna be honest, you're probably doing something wrong.
