### ISSUE TITLE
Game Data import from iPhone to iPad crashes app

### ISSUE THREAD

**Issue by maurice-schleussinger** [Anuken/Mindustry#3060]
**Platform**: *iOS*

**Build**: 104.4 (both)

**Issue**: After playing on iPhone for a while I wanted to export to iPad but it crashes immediately. **Update:** I misinterpreted the ongoing campaign game on iPad to be the tutorial I started then I first launched the app, but it was the successfully imported game file after all. The only issue is the crashing of the iPad app upon import.

**Steps to reproduce**: 

1. Play game on iPhone
2. Export Game Data via iCloud/AirDrop to blank iPad App

**Link(s) to mod(s) used**: None

**Save file**: 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5421720/mindustry-data-export.zip)

**Crash report**: Where would I find this on iOS?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's supposed to close the game upon import. It even tells you that will happen.
