### ISSUE TITLE
Incorrect tech tree/research relationship

### ISSUE THREAD

**Issue by Khanx** [Anuken/Mindustry#3065]
**Platform**: Windows

**Build**: Steam build *109*

**Issue**: There is a map research that requires capturing a map from a different research branch. *(SEE PICTURE)*

![Research](https://user-images.githubusercontent.com/2260108/96874921-f0962400-1476-11eb-883d-8091f757c3c7.png)

**Save file**: *[saves.zip](https://github.com/Anuken/Mindustry/files/5422857/saves.zip)*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DayTimer** [comment]
That is not a bug... In the v5 campaign, you can only unlock this zone after capturing FP

**Comment by Legomonster33** [comment]
> That is not a bug... In the v5 campaign, you can only unlock this zone after capturing FP

Then this is a bug as the tech tree should have an additional branch to indicate that

**Comment by Legomonster33** [comment]
> Not a bug.

not a "bug" but still a *graphical* "error" (and an informational error)

**Comment by Anuken** [comment]
It is neither. A sector with two dependencies cannot be represented in a tree with an "additional branch".

**Comment by Legomonster33** [comment]
> It is neither. A sector with two dependencies cannot be represented in a tree with an "additional branch".

If the "research item" in this case sector "???" Is moved to the layer beyond its most (advanced?) Requirement, it could have a line to join the multiple requirements together.

**Comment by Anuken** [comment]
> it could have a line to join the multiple requirements together.

That:
1. is a mess
2. make the tree not a tree, but a DAG
3. will break in all sorts of funny ways

This is not new behavior. Items all over the tech tree depend on things from different branches. I don't see why you care about this so much.
