### ISSUE TITLE
Unit factory

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#3066]
**Platform**: Android

**Build**: Beta 109

**Issue**: Unit factory build an unit without resources

**Steps to reproduce**: Set unit production speed to 999, and choose the unit you want to build

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* 
[Kek.zip](https://github.com/Anuken/Mindustry/files/5423625/Kek.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't set it to 999. The factory completes construction in a single frame, and doesn't have time to refresh required resources.
