### ISSUE TITLE
Disabled Conveyors Still Drag Units

### ISSUE THREAD

**Issue by motaywo** [Anuken/Mindustry#3067]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows64

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
B109 -> be10687

**Issue**: *Explain your issue in detail.*
When disabled using logic processors, conveyor belts still drag units that step on them, even though they can't move items, and are no longer animated as moving. This occurs on **all** types of 1x1 conveyors (normal, titanium, and armoured), Conveyors that have stopped naturally due to clogging do **not** drag units, however.
[Link to video: https://imgur.com/a/UkVPaXO](https://imgur.com/a/UkVPaXO)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Place a conveyor; disable that conveyor using logic blocks; control, direct, or otherwise cause a ground unit to walk over the conveyor; unit will be dragged by the conveyor, in the direction and normal speed of that conveyor, as if it were still enabled.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A - No mods involved
_(DeltaNedas' cliff mod and RTFM in use upon first discovery - however, game was then reloaded with all mods disabled; issue persisted)_

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[conveyorBug.zip](https://github.com/Anuken/Mindustry/files/5425067/conveyorBug.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
N/A - No crash reported

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
