### ISSUE TITLE
Wave made entirely of polys very annoying

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3069]
**Platform**: Android 9

**Build**: 10687

**Issue**:
Shit wave is made entirely of polys, crawlers too if I'm lucky.
I should not need a massive array of plast cyclones on wave ~3 of an unoccupied map, just to exterminate annoying little fuckers.

**Steps to reproduce**:
1. Play sector 82
2. hhhhhhhh

**Link(s) to mod(s) used**: deltanedas/routorio probably used in the save

**Save file**: 
[bad.msav.txt](https://github.com/Anuken/Mindustry/files/5425615/bad.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Poly and Mega should be limited based on enemy core, otherwise it'll be a complete nightmare

**Comment by D-player1** [comment]
~~Also, you can coal bomb~~

**Comment by DeltaNedas** [comment]
there is no enemy core, as I said its unoccupied

**Comment by DeltaNedas** [comment]
also i think this has been fixed ill try on latest be

**Comment by Anuken** [comment]
"it's annoying" is not a bug.

**Comment by z0mbiesrock** [comment]
> "it's annoying" is not a bug.

[still did something about it anyway](https://github.com/Anuken/Mindustry/commit/a773edd8385fcec5d76301b18575bd118c0a65c8)

**Comment by Anuken** [comment]
> still did something about it anyway

Yes, and that's completely unrelated to whether it's a bug or not. I closed it *here* because this tracker is for **bug** reports, not feedback.
