### ISSUE TITLE
F-Droid is currently publishing 6.0 alphas as stable

### ISSUE THREAD

**Issue by strugee** [Anuken/Mindustry#3070]
**Platform**: Android

**Build**: 107

(Omitting the rest of the issue template since it's not relevant.)

Basically, what the title says. This caused me to lose game progress on my device, although it appears that the 5.0 data is still present since downgrading via adb got me my progress back.

Possibly related: #2853

Downstream ticket: https://gitlab.com/fdroid/fdroiddata/-/issues/2201

I suggest publishing a copy of build 104.6 with the version number bumped so that any F-Droid users who have already received the 6.0 alpha upgrade will be "upgraded" back to a stable build while whatever misconfiguration caused this in the first place is worked out.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This wasn't a misconfiguration; the current 6.0 version is now in beta, so I decided to fix the F-Droid release script for compatibility with 6.0.

**Comment by licaon-kter** [comment]
@strugee There is git differentiator between stable and unstable, Github labels can't be used (remeber that Github is not FOSS anyway).

`v104` vs `v107` they look the same. But @Anuken could tag as `v107-beta` and we could avoid pulling unstable.

Anyway in the mean time no more updates since we don1t yet have Java14 readily available.

**Comment by emorrp1** [comment]
I can see this has now been fixed in F-Droid, so suggest closing this issue. I don't think you need to change your tag names, because the client clearly supports a "Suggested" version for auto updates, while still building and making available the beta releases.

**Comment by licaon-kter** [comment]
@emorrp1 yes, but how does the checkupdate CI know which one is which exactly?

**Comment by emorrp1** [comment]
@licaon-kter I had a look at how [K-9 Mail] handles it with a `UpdateCheckMode: RepoManifest/5.6-MAINT`, now I don't know what that means, but it looks like you can put some metadata in the manifest file to say whether a build should be considered suggested. Alternatively, according to the blame, they may just be updating manually, which might not work for Mindustry's fast-paced development.

[K-9 Mail]: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.fsck.k9.yml#L692

**Comment by licaon-kter** [comment]
K9 pushes MRs manually,
