### ISSUE TITLE
Mass driver output doesn't speed up when affected by overdrive projector/dome

### ISSUE THREAD

**Issue by Zagrox11** [Anuken/Mindustry#3071]
**Platform**: Android

**Build**: be 10701

**Issue**: Mass driver affected by overdrive has increased fire rate but it's output speed is the same

**Steps to reproduce**: Connect 2 mass drivers and put item source besides first one. Then place and overdrive dome. First mass driver fire rate changes but second outputs items at the same speed as before.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
technically not a bug since it already output one item per tick, but it would be a welcome feature 🤔

**Comment by Anuken** [comment]
Output rate is not supposed to increase.
