### ISSUE TITLE
Too many polys spawn on attack missions when they start building base, there is around 1000

### ISSUE THREAD

**Issue by Auseawesome** [Anuken/Mindustry#3074]
Windows (Itch)

Beta 109

When 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---
Too many units spawn, around 1000 polys on attack missions, they are almost impossible to destroy and remain once the sector is captured! (https://user-images.githubusercontent.com/70506988/97017318-a9c32f80-1545-11eb-9574-260dc134ccb0.jpg)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate + no save.

**Comment by Auseawesome** [comment]
> Duplicate + no save.

Sorry typed in 'polys too many' in search bar and got no results, didnt realise there were others
