### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by logansterMan** [Anuken/Mindustry#3076]
**Platform*: Windows/iOS/phone
build 110/109 version 6 Bata 

when playing on campaign I got to wave 30 and cleared the sector. a bit later I was attacked again, then again{now on wave 75}. but when playing on a phone I cleared stained mountains {wave 30} and haven't been attacked for over 11 hours. I got so much loot really a game changing glitch  
should fix in next patch

**Comment by logansterMan** [comment]
look important

**Comment by Anuken** [comment]
Not a bug, only sectors near bases get attacked.
