### ISSUE TITLE
Item Capacity = Health?

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3079]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Steam Build 110 

**Issue**: 
Clearly the Reign doesn't actually have a 24k item capacity.
![image](https://user-images.githubusercontent.com/19158169/97048253-1f2fff80-1548-11eb-901e-8e647049fe1e.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
duplicate

**Comment by z0mbiesrock** [comment]
> duplicate

_BRUGH_ who got to it first?
