### ISSUE TITLE
Start position view. 

### ISSUE THREAD

**Issue by PraNor** [Anuken/Mindustry#3080]
**Platform**: Android

**Build**: beta build 109

**Issue**: When initial load of a new map/zone, the view follows the core to its start location. But tge moment it lands, the camera view jumps to a random location, sometimes impossible for me to find the start location. 

**Steps to reproduce**: clicking on the first hexigo. In world view and launching results in starting the level but then cannot find the core location, following the initial load screen. This happens on all new core launches. 

**Link(s) to mod(s) used**: no mods used

**Save file**: i cannot find the save file on the phone. 

**Crash report**:

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
> i cannot find the save file on the phone.

Make one bruh

**Comment by DeltaNedas** [comment]
/sdcard/Android/data/io.anuke.mindustry/files/saves

**Comment by Anuken** [comment]
> But tge moment it lands, the camera view jumps to a random location

This only happens if you start panning before the core lands.

**Comment by DeltaNedas** [comment]
good

**Comment by PraNor** [comment]
> > i cannot find the save file on the phone.
> 
> Make one bruh

I did. The zip file does not show up on the phone. I have been unable to load ANY saved game files
