### ISSUE TITLE
Launching with Core Upgrades Bugged

### ISSUE THREAD

**Issue by Skylercr** [Anuken/Mindustry#3082]
**Platform**: Windows

**Build**: beta build 110

**Issue**: I've lost all my bases except ground zero. Unfortunately i haven't researched any tech to allow making silicon and i've upgraded my base to Core:Foundation. However, it requires 2000 to launch. So now that all my other bases are destroyed, I have to start from Ground Zero, but I have no way to produce coal, so I cannot produce silicon to get the 2000 to launch to any outter planet. IE i'm stuck and have to start completely over. 
![image](https://user-images.githubusercontent.com/70347816/97058366-da599800-154a-11eb-9097-fb44f9eb05f4.png)
![image](https://user-images.githubusercontent.com/70347816/97058418-0412bf00-154b-11eb-80b7-617a064ba07f.png)
![image](https://user-images.githubusercontent.com/70347816/97058383-ea717780-154a-11eb-93eb-6c4d7b24049f.png)
![image](https://user-images.githubusercontent.com/70347816/97058396-f2c9b280-154a-11eb-9051-bd97db8ee097.png)

**Steps to reproduce**: Passed ground zero, launched to outer zones, researched tech Core:Foundation, base got destroyed on outer zones had to go and resume on ground zero. No way to produce silicon, can't launch anywhere because it requires 2000 silicon. 

**Save file**: *
[Savefile.zip](https://github.com/Anuken/Mindustry/files/5431967/Savefile.zip)
![image](https://user-images.githubusercontent.com/70347816/97058383-ea717780-154a-11eb-93eb-6c4d7b24049f.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Esnardo** [comment]
I literally could not come up with a bug like this if I tried.
