### ISSUE TITLE
Enemy spawners not working on water

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry#3084]
**Platform**: Windows

**Build**: BE 10742

**Issue**: The enemy spawners do nothing when placed on water.

**Steps to reproduce**: Play on the new archipelago map. Even if the map editor does prove that there is a spawn point there, there is no spawn point in sight during gameplay, and enemies don't spawn.

**Link(s) to mod(s) used**: None
**Save file**: [Archipelago.zip](https://github.com/Anuken/Mindustry/files/5432773/Archipelago.zip)

**Crash report**: Not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
