### ISSUE TITLE
User interface for logic processor getting out of the screen

### ISSUE THREAD

**Issue by nodevlfrb** [Anuken/Mindustry#3085]
**Platform**: *Android*

**Build**: Bleeding-edge build 10701

**Issue**: Error of display/scale of the logic menu

**Steps to reproduce**: I opened the menu of a logic processor and created a "Unit Locate" module. When I wanted to modify the values inside, not all were displayed in the screen and it looked like my screen was too small to display the entire menu.

**Link(s) to mod(s) used**: N/A

**Save file**: It can look very dumb but I just deleted the file instead of saving it, because I didn't know the new interface of v6...I have a screenshot thought.
It's a blank world with only sand and the standard ore generation, with a core in the top right hand corner.
![Screenshot_20201024-125426_Mindustry BE](https://user-images.githubusercontent.com/67834068/97080561-945d0c80-15fc-11eb-849a-81a57edde81e.jpg)

**Crash report**: It's not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
