### ISSUE TITLE
Server's socket input vulnerability.

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#3087]
**Platform**: Any platform. (server-side)

**Build**: 109 (beta)

**Issue**:
Right now, in order to connect and control the server through a socket input, we just need to know the socket input port number, which is not secure because anyone can just ping each port and hack the server.

**Steps to reproduce**:
- Start server and open socket input.
- Connect any third party app.
- Tada, got access only with port.

**Link(s) to mod(s) used**: None.

[#899](https://github.com/Anuken/Mindustry-Suggestions/issues/899)
  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
then dont forward that port
use ssh

**Comment by Quezler** [comment]
the socket port is bound to localhost ^

**Comment by Anuken** [comment]
Have you actually tried this? The socket binds to `localhost`, it isn't exposed to the network. Even if it were, you could either (1) not enable it or (2) not forward the port.
