### ISSUE TITLE
Launch Pads continue to send resources forever.

### ISSUE THREAD

**Issue by iansmith42** [Anuken/Mindustry#3089]
**Platform**: Windows 10

**Build**: steam build 110

**Issue**: I built a Launch Pad to send Thorium to Ground Zero.  I let it launch twice, then deleted the belt so it was no longer being fed materials. However, it continued to send Thorium to Ground Zero and soon I had 4000 of it.  I even deleted the Launch Pad and continue to get resources.  There seems to be no way to stop it now.  I tested sending Silicon from another map, same bug.

**Steps to reproduce**: Create a Launch Pad.  Let it launch once. Remove feeder belts. Materials continue to be sent. Remove Launch Pad, resources continue to be sent.

**Link(s) to mod(s) used**: None

**Save file**: 

[launch pad bug saves.zip](https://github.com/Anuken/Mindustry/files/5432942/launch.pad.bug.saves.zip)

**Crash report**: NA

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Doesn't happen to me. How do you know the resources continue to be sent? Are you leaving out any steps? What is the production rate on the sectors you are sending to? I can't use your saves, because they're not enough to test the problem; sector production rates are in your main settings file.

**Comment by Legomonster33** [comment]
@iansmith42 would need to go to settings>data>export data, in order to export sector production rates correct? (in which case you could see the issue for yourself)

**Comment by Anuken** [comment]
Closing until more information is provided; I suspect you left out the fact that you switched sectors right after breaking/disconnecting the launch pad (which would definitely leave you with a small export rate, because export rates use the average over several minutes). I don't see another good explanation for this.
