### ISSUE TITLE
problem with code block "unit radar"

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry#3091]
**Platform**: *Android*

**Build**: *10752*

**Issue**: *unit radar cannot get a player, even if before that bind gamma unit.*

**Steps to reproduce**: *Put processor and message. Connect message to processor. Put this code into processor:
ubind @gamma
uradar player any ally distance turret1 1 result
sensor x result @x
print x
printflush message1*

**Link(s) to mod(s) used**: *no mods used*

 **Save file**: *unreal to past file*

**Crash report**: *No crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You don't understand how `ubind` works. You cannot bind to player-controlled units.

**Comment by hshsxhsb** [comment]
> You don't understand how `ubind` works. You cannot bind to player-controlled units.

if I can't bind players, then I can't use unit radar with "player" options.

**Comment by DeltaNedas** [comment]
I think that the player check should occur in `ucontrol`, not `ubind` as using players for radar would be quite useful.

**Comment by Anuken** [comment]
> if I can't bind players, then I can't use unit radar with "player" options.

Yes you can. Bind any unit not controlled by a player, and it can detect players near it.
