### ISSUE TITLE
Illuminator menu bug?

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3097]
**Platform**: Windows 10

**Build**: Steam Build 110

**Issue**: 

In campaign, the iluminator sometimes disappears from the build menu, or is greyed out with the message ???unplaceable.always???
example:
![image](https://user-images.githubusercontent.com/19158169/97088063-71caf380-15fc-11eb-82ee-7c3abf367622.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> example:

What are you trying to show here?

**Comment by Anuken** [comment]
...and this issue clearly occurs in-game, yet you've still deleted the entire section about saves.

**Comment by z0mbiesrock** [comment]
h

**Comment by Clocks-in-a-Cooler** [comment]
it seems to happen if you load a campaign map, such as switching to another sector in the campaign, or loading the campaign from the main menu.
try starting the campaign and unlocking the illuminator. then switch to another sector, and build an illuminator.
