### ISSUE TITLE
Flying Units Leave Shadows on the Space Background

### ISSUE THREAD

**Issue by Cpppppppppplus** [Anuken/Mindustry#3101]
Platform: Linux
Version: Beta 110

Issue: Flying units leave shadows on the space background.

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
butchered the template wow

**Comment by DeltaNedas** [comment]
properly fixing this would mean using a framebuffer for accurate shadows, including:
- adding masks to cut out shadows, see here
- not "adding" shadows together
but would probably hurt performance on phones so anuke would never add it ever

**Comment by Anuken** [comment]
they're supposed to.

**Comment by Cpppppppppplus** [comment]
@DeltaNedas You could also just switch on a uniform in the shader.

**Comment by Cpppppppppplus** [comment]
@DeltaNedas 

"butchered the template wow" Are you saying I need to post the entire save file to explain this?

**Comment by DeltaNedas** [comment]
yes

**Comment by sk7725** [comment]
> properly fixing this would mean using a framebuffer for accurate shadows, including:
> 
> * adding masks to cut out shadows, see here
> * not "adding" shadows together
>   but would probably hurt performance on phones so anuke would never add it ever

Anuke said no, I suggested this before.
But what about using a framebuffer *for the space background* so in that area the buffer selectively chooses which object to be drawn?

**Comment by Anuken** [comment]
I'm not going to discuss what's easy and what's performant. If you think it's doable without any performance loss or spaghetti, make a PR; otherwise, I'm not interested. Shadows are barely visible above space as-is; it's an inconsequential detail that's not worth wasting time on.
