### ISSUE TITLE
Everything floats on liquid now

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3102]
**Platform**: Windows

**Build**: Steam Build 110

**Issue**: 
Remember Issue #2729 , the "Deep water placement bug"?

Well...

This is that, but turned up to _twelve_.

![image](https://user-images.githubusercontent.com/19158169/97094091-9389a200-161f-11eb-9fee-f4388ef3830a.png)
_Anything_ can be placed on deep liquid, even 1x1 blocks!

Units that _should_ drown (like this dagger) don't drown.
![image](https://user-images.githubusercontent.com/19158169/97093906-d0549980-161d-11eb-9bf9-9b771afe7a2a.png)

**Steps to reproduce**: Place a block on deep liquid; any deep liquid

**Link(s) to mod(s) used**: none used

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/5433813/saves.zip)

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. That's not deep water in the screenshot.

*shallow water, my screenshot*
![image](https://user-images.githubusercontent.com/10100000/97095260-427fab00-162b-11eb-8c53-28da4c038451.png)
*your screenshot*
![image](https://user-images.githubusercontent.com/10100000/97095261-44e20500-162b-11eb-986f-0fd021784250.png)
*deep water, my screenshot*
![image](https://user-images.githubusercontent.com/10100000/97095264-4a3f4f80-162b-11eb-8abd-965167a8563f.png)

2. Why did you attach 8MB of save files? The template doesn't ask for that. Do you think I'll be able to go through ~74 saves just to find the map you were playing on?

**Comment by z0mbiesrock** [comment]
oh. okay
