### ISSUE TITLE
display bug

### ISSUE THREAD

**Issue by Karo4eKY** [Anuken/Mindustry#3105]
**Platform**: Windows 10

**Build**: build v10779

**Issue**:  На дисплее, при толщине линии 1 при неизвестных мне условиях пропадает часть линии (а мне важна толщина линии 1). Прости что не на английском, как мог пытался.

**Steps to reproduce**: Don't know

**Link(s) to mod(s) used**: Not have mods

**Save file**: 
[bug.zip](https://github.com/Anuken/Mindustry/files/5433956/bug.zip)

**Crash report**: Not have crush

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [Х] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Karo4eKY** [comment]
I say srry to i not write problem with english, my english bad)

**Comment by Anuken** [comment]
Use a thickness of a line slightly above 1, or round your coordinates.

> Save file:
bug.zip

You just sent me the entire contents of your save folder. I can't do anything with this.
