### ISSUE TITLE
Display bugs "Fixed Version"

### ISSUE THREAD

**Issue by Karo4eKY** [Anuken/Mindustry#3106]
**Platform**: Windows 10

**Build**: build v10779

**Issue**: Y oxis display anomaly (storke 2 or 0 if y=x pixels (x its not all, just schematic see)) (sorry to my bug reports) (просто просмотри схему)

**Steps to reproduce**: display bug

**Link(s) to mod(s) used**: -

**Save file**: 
[bug report display.zip](https://github.com/Anuken/Mindustry/files/5433974/bug.report.display.zip)

**Crash report**: No

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Karo4eKY** [comment]
With lo<3e))

**Comment by Karo4eKY** [comment]
If more slowly add in code opertion x=x+0.1 and jump if x<=+-1 then go to sting up (operation x=x+0.1)

**Comment by Anuken** [comment]
I see no issues with the line in your schematic (even with 0.1 movement), and as I said in the previous issue, I won't fix this.
