### ISSUE TITLE
Capturing bug 

### ISSUE THREAD

**Issue by Nanosuitwitdaboomboxwhatsongwillhepla** [Anuken/Mindustry#3107]
**Platform**: *Android(pixel A3)*

**Build**: *Beta Build 110*

**Issue**: *I had started stained mountains captured at wave 55 felt accomplished went to another sector (at the time being 171 and 215) and as soon as it loaded the sector became captured. I have later checked other previous sectors which had then become captured (happens to all sectors) captured but if I launch a new core to a new sector it does not become captured as soon as it loads *

**Steps to reproduce**: *1. Capture sector (the one I captured was stained mountains because only sector I knew that could have been captured)
2. Open planet map
3. Pick sector (does not matter if named or not) with core set before the capture happened 
4. Non profit*

**Link(s) to mod(s) used**: *Hackustry 3.1 by QmelZ.*

**Save file**: *
[mv6 beta build 110.zip](https://github.com/Anuken/Mindustry/files/5433994/mv6.beta.build.110.zip)
 *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X]**I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
somewhat related, when a captured attack map is attacked, it is immediately recaptured when entered or after a minute.

**Comment by Anuken** [comment]
Might be fixed now; there are so many moving parts in the sector system that it's hard to tell for sure.
