### ISSUE TITLE
stupid poly not putting item in reconstructor in campaign

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3114]
**Platform**: Android 9

**Build**: 10779

**Issue**:
Poly not putting graphite into reconstructor

**Steps to reproduce**:
1. look at poly take items but not put them in reconstructor
**This only happens on campaign, it works fine on sandbox**

**Link(s) to mod(s) used**: deltanedas/routorio used in the save

**Save file**: Sector 10 of serpulo
[bug.msav.txt](https://github.com/Anuken/Mindustry/files/5434847/bug.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your save has no logic-controlled poly units and no mention of putting items into reconstructors in the logic. When I control the unit manually, I have no issues inserting/removing graphite or silicon.

**Comment by DeltaNedas** [comment]
```
ubind @poly
sensor flag @unit @flag
jump 0 notEqual flag 1
ucontrol move @thisx @thisy 0 0 
ucontrol itemTake nucleus1 @silicon 30 0 
sensor silicon @unit @silicon
jump 4 notEqual silicon 30
ucontrol itemDrop reconstructor1 30 30 0 
sensor silicon @unit @silicon
print silicon
printflush message1
jump 7 equal silicon 30
```
how is this not supposed to move items into the reconstructor?

**Comment by DeltaNedas** [comment]
@Anuken there is a ton of solar panels around the core on that save yes

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/97109851-fc1e6080-16ab-11eb-91a2-7268bbad1d22.png)

![image](https://user-images.githubusercontent.com/10100000/97109855-0a6c7c80-16ac-11eb-8f36-7444f4c81616.png)

Your save does not have that code, and there are no logic-controlled polys.

**Comment by DeltaNedas** [comment]
the one below that has a processor with mentioned code, the poly is over it doing nothing

**Comment by Anuken** [comment]
Okay, I didn't see the one at the bottom. In your case, it's too far away from the block to transfer items.
