### ISSUE TITLE
enemies have huge amounts of shield on first wave

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3116]
**Platform**: Android 9

**Build**: 10779

**Issue**:
![h](https://user-images.githubusercontent.com/39013340/97111835-e07d7f00-16d8-11eb-8aa8-d84929b774ea.jpg)
Flares have ~250 shield **on the first wave**.
IIRC they're supposed to build shield over time instead of starting with lots.

**Steps to reproduce**:
1. Start sector 124
2. Look at flare's shield on first wave

**Link(s) to mod(s) used**: routorio in save

**Save file**: serpulo sector 214
[bug.msav.txt](https://github.com/Anuken/Mindustry/files/5434986/bug.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, it depends on the difficulty.
