### ISSUE TITLE
Issue loading floors

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3117]
**Platform**: *Android*

**Build**: *110 Beta*

**Issue**: *Went to mod test and got an error when loading. No issues, i went and added what it wanted. Reloaded and same thing.*

**Steps to reproduce**: *Load up a mod with a floor.*

**Link(s) to mod(s) used**: *https://github.com/K103908/Exotic-Mod*

**Save file**: *none*

**Crash report**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**
Note: error is *"wall" in  is missing!* and the screenshot failed to save due to a lack of RAM.

**Comment by Anuken** [comment]
fixed
