### ISSUE TITLE
Player's First Unit Disappear

### ISSUE THREAD

**Issue by DFAltmann** [Anuken/Mindustry#3122]
I don't know and don't haver experience with game codes, but on the level "The Craters", the main and initial building unit disappeared, i lanched in other "region" of the map (i'm playing on the Alpha btw), and the unit works normally, but when i got back in The Craters, it still didn't reapper, i tried reset the game, but still the bug.
I'm a Brazillian player, so i'm sorry for any miswrited word. Keep up the work, your game is awesome.

**Comment by DeltaNedas** [comment]
use the template would you
