### ISSUE TITLE
The same thing, Sorry.

### ISSUE THREAD

**Issue by DFAltmann** [Anuken/Mindustry#3123]
![Screenshot_20201025-212754](https://user-images.githubusercontent.com/73451399/97125444-bc3e9400-1712-11eb-996d-021790cf6df7.png)

I took this screenshot after trying to make it reappear. Sorry for not putting it in the previous one.

**Comment by genNAowl** [comment]
You do realize you can edit the previous issue right?

**Comment by DFAltmann** [comment]
I didn't, i just made my account, never used It, but thanks, i'll remember
it next time.

Em dom, 25 de out de 2020 23:18, genNAowl <notifications@github.com>
escreveu:
