### ISSUE TITLE
timePeriod is having an aneurysm 

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3124]
**Platform**: *Android*

**Build**: *Beta 111*

**Issue**: *timePeriod in liquid consuming blocks is there, but the game says it doesnt exist.*

**Steps to reproduce**: *Run the mod provided below.*

**Link(s) to mod(s) used**: *https://github.com/K103908/Exotic-Mod*

**Save file**: *none*

**Crash report:** *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported but I know this issue has not been reported yet due to the recent update.**
![27672022-7E9F-4C62-9D21-EC480C85A0AA](https://user-images.githubusercontent.com/61173114/97130853-3584b980-1708-11eb-8668-da8c2c11cecb.png)

**Comment by Anuken** [comment]
> timePeriod in liquid consuming blocks is there

It's not. There is no such field anymore.
