### ISSUE TITLE
Can't launch a Shard core even though I have enough resources.

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry#3126]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac OS 10.15.7

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
111

**Issue**: *Explain your issue in detail.*

<img width="1434" alt="Screen Shot 2020-10-26 at 12 36 15 PM" src="https://user-images.githubusercontent.com/73286691/97134499-66a4ce80-1788-11eb-94b4-e74d32643d98.png">

Although it costs 0 lead to launch a core, it says I don't have enough lead to launch a core to the Craters (or any other area for that matter). I am unable to continue the game.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Not sure, but this is what I've been doing before.
1. Download build 111 from itch.io from the itch.io app
2. Export and import data from build 109 (downloaded not from itch.io app) to build 111
3. Resume playing on Frozen Fields and wait until I completed it.
4. When I try to go to The Craters, I discover this issue.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
I don't use mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
I can't find the specific game file. Sorry.
[broken game file.zip](https://github.com/Anuken/Mindustry/files/5436851/broken.game.file.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
It costs 1k lead to launch a core

**Comment by BlueWolf3682** [comment]
so you see that +1000 number to the right of the lead? thats how much you need to launch

**Comment by braainsiogame** [comment]
![Uploading intelligence.PNG…]()

**Comment by DeltaNedas** [comment]
[red]128[]/(0 + [stat]1000[]) lead would more sense
