### ISSUE TITLE
Disable data export when on middle campeing game for prevent cheating

### ISSUE THREAD

**Issue by anar4732** [Anuken/Mindustry#3128]
We can cheat with exporting data while middle of game so after death we can restore and contine the game.

**Comment by bsjohnson20** [comment]
I don't believe this matters as you can just use cheat engine to force resources to be a rather large number which is far greater a cheat than this also if you want to cheat its your choice (multiplayer cheating is unfair don't do it only single player).

**Comment by DeltaNedas** [comment]
`Core.app.exit()` in f8
modify settings.bin or a map
use mem editor, see above
etc.

this is also a suggestion get out
