### ISSUE TITLE
shootX show uncorrect shoot coordinates

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry#3131]
**Platform**: *Android*

**Build**: *10809*

**Issue**: *shootX show uncorrect shoot coordinates*

**Steps to reproduce**: *load save. Load saved game, shoot, and see to message*

**Link(s) to mod(s) used**: *No mod used*

**Save file**: *[save.zip](https://drive.google.com/file/d/167yLjg0mKBNKVAOXtfpBtDkITN2KI4mQ/view?usp=drivesdk)*

**Crash report**: *No crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The template asks for a zipped version of the current save you were playing on, not all your game data. Your issue doesn't specify any details on what you're sensing and what's incorrect about the shoot position.
