### ISSUE TITLE
Im sure that's not a reactor

### ISSUE THREAD

**Issue by ricardo1003** [Anuken/Mindustry#3132]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Bleeding-edge Build 10809
**Issue**: *Explain your issue in detail.*
For some reason logic processor selected a conveyor like a thorium reactor
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Idk
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Was on server, here is screenshot
![Screenshot_2020-10-26-09-55-29-742_io anuke mindustry be](https://user-images.githubusercontent.com/67872140/97190214-6fd77080-1773-11eb-8c98-4d96007b97b0.jpg)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ricardo1003** [comment]
I mean bridge

**Comment by Anuken** [comment]
> How you happened across the issue, and what exactly you did to make the bug happen.
Idk

I can't do anything with that information.

**Comment by Legomonster33** [comment]
> > How you happened across the issue, and what exactly you did to make the bug happen.
> > Idk
> 
> I can't do anything with that information.

I know how to replicate this I will report a new issue in a bit
