### ISSUE TITLE
Uncorrect shootX coordinates

### ISSUE THREAD

**Issue by hshsxhsb** [Anuken/Mindustry#3135]
**Platform**: *Android*

**Build**: *BE 10823*

**Issue**: *sensor, shootX shows the wrong coordinate of the shot.  it very much prevents me from doing what I need, namely the touch screen.
[BugVideo.mp4](https://drive.google.com/file/d/16WGQ6NuVv_f8HdR8UKHqb5av1ReUk1xj/view?usp=drivesdk)*

**Steps to reproduce**: *Downloaded and installed version BE 10823. Turned on the game.  Set your favorite settings.  Launched a custom game.  Build message and processor.  Connected the processor to the message and paste this code:

radar player any any distance @this 1 result
sensor x result @shootX
print x
printflush message1*

**Link(s) to mod(s) used**: *imported from github DeltaNedas/rtfm (without mods the coordinates are also incorrect)*

**Save file**: *[bug.msav](https://drive.google.com/file/d/16bGGN1_vCPoTbxtxexep_jaKSJsicVVJ/view?usp=drivesdk)*

**Crash report**: *no crash report*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't see anything wrong there. When the player shoots, the coordinates are correct. When the player doesn't, the results aren't defined, because mobile players do not have a mouse cursor.
