### ISSUE TITLE
big router cannot be controlled

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3137]
**Platform**: Android 9

**Build**: 10802

**Issue**:
Distributor and Colossus (4x4) cannot be controlled.

**Steps to reproduce**:
1. place router, distributor and colossus.
2. jump into router but the others won't work

**Link(s) to mod(s) used**: DeltaNedas/routorio

**Save file**: anuke are you that lazy its 2/3 blocks

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
[I wonder why](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/Router.java#L43)
