### ISSUE TITLE
Bloom setThreshold does not work

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3142]
**Platform**: *Windows*

**Build**: *10830*

**Issue**: *Vars.renderer.bloom.setThreshold() does not seem to function.*

**Steps to reproduce**: *Below are ingame screenshots: first is threshold set to 0.01, second is set to 0.99.*
![image](https://user-images.githubusercontent.com/58885089/97238479-dd93a300-182c-11eb-88b8-58df776248f0.png)
![image](https://user-images.githubusercontent.com/58885089/97238567-0451d980-182d-11eb-8ba0-5926c4bb4964.png)

**Link(s) to mod(s) used**: *I did use sk7725/testing, just to run the code and draw some stuff on the effect layer.*

**Save file**: *Codewise issue.*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GlennFolker** [comment]
ah yes, very sk7725/testing ;)

**Comment by sk7725** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/918

This is what I am trying to achieve; is there a way to do this?
(I expected setting threshold to 0.33 to do the trick but well...)

**Comment by Anuken** [comment]
This is a problem with your usage of an API, not a bug.

**Comment by sk7725** [comment]
> This is a problem with your usage of an API, not a bug.

@Anuken can you elaborate? What API? Why does threshold have seemingly no effect? And how do I achieve something like Anuken/Mindustry-Suggestions#918?

**Comment by Anuken** [comment]
> What API?

The internal bloom API. As long as it doesn't affect the vanilla game, functions not working like you expect are not bugs.

> Why does threshold have seemingly no effect? And how do I achieve something like Anuken/Mindustry-Suggestions#918?

No idea.
