### ISSUE TITLE
(logic) core shard can't be displayed

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry#3144]
**Platform**: Windows 10

**Build**: Bleeding edge 10385

**Issue**: Core shard can't be drawn with the new draw image command.
![image](https://user-images.githubusercontent.com/56274831/97250559-755ca700-17c3-11eb-840c-604a5ce273a2.png)
Core foundation and nucleus both work fine.

**Steps to reproduce**: I was playing around with the new draw image feature, and noticed that trying to draw `@core-shard` drew `oh no`

**Link(s) to mod(s) used**: none

**Save file**: 
[bugreport.zip](https://github.com/Anuken/Mindustry/files/5442623/bugreport.zip)

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 50275** [comment]
I don't really know much but maybe it's because the share core isn't buildable and isn't shown as a building
