### ISSUE TITLE
Undo action for plannings

### ISSUE THREAD

**Issue by datalot-369** [Anuken/Mindustry#3147]
After almost one hour of planning the build for an island, I accidentally pressed `q`

### What happened?

All my work was loose and I can't recover it with `Ctrl + Z`.  
It's the most annoying thing it could happen today.

### What should happen?

The plan should recover its state.
This also should work after every change of the plan, not only for the `q` key, however, this last is the most basic thing the game should have.

---

Really, if this happens again I will not play Mindustry until it's fixed because it means a time-consuming bug. Literally I have spent my time in that plan thinking that I could build it tomorrow because for today I have no more time for it.

I'm so angry.

**Comment by Quezler** [comment]
i've hit q after planning a lot more times than i admit as well, a way to undo that would be welcome, but having an entire island in your build queue is unconventional, i would suggest building small sections, that guarantees little losses if you accidentally press q, and it will ensure you don't run out of building materials halfway through construction since there is no real way to prioritize building when your entire map is a construction site 🤔

**Comment by datalot-369** [comment]
It's not about size. It's about my own sanity. Planning consumes too much time when you need to create complex structures of resource management because you invest time thinking and analyzing the whole map.

For now, I will take a look at the keymap to change it for, I don't know... `F12`.

**Comment by Quezler** [comment]
i understand, a failsafe would be nice 🙂

**Comment by Anuken** [comment]
> a time-consuming bug

No, this is not a bug. Ctrl-Z undoing a clear was never supposed to be a feature. There is absolutely no support for Ctrl-Z/X/Y hotkeys in the game outside of the editor.

**Comment by Legomonster33** [comment]
> > a time-consuming bug
> 
> No, this is not a bug. Ctrl-Z undoing a clear was never supposed to be a feature. There is absolutely no support for Ctrl-Z/X/Y hotkeys in the game outside of the editor.

that would be nice tho

**Comment by Anuken** [comment]
I have a special repository for *"things that would be nice"*.
