### ISSUE TITLE
Multiplayer build tabs unlock not synced properly

### ISSUE THREAD

**Issue by Ansraer** [Anuken/Mindustry#3152]
**Platform**: *Steam Windows/Linux*

**Build**: *v6 111*

**Issue**: *While technology unlocks themself are synced the unlock of new technology build tabs (bottom right) are not synced.*

**Steps to reproduce**: *Was playing a game with my younger brother. While I had already unlocked most things in v6 he had none. When I joined his game only the technologies he had unlocked (so the starter stuff) was available to me as well. Over the course of the round he started unlocking new things and I could build more stuff. However, when he unlocked things that were in a new build category (e.g. electric generator or walls) the tabs for these new unlocks were not added to my ui. The ui only showed me the turrets, miners and conveyor belt tab.*
*After disconnecting and rejoining I could see and use the other categories he had unlocked as well.*

**Link(s) to mod(s) used**: *None. He used a fresh install from steam and I reinstalled only a few days ago.*

**Save file**: *~~Will be uploaded in 5 mins once the other pc is booted.~~ Uploaded his save file*

**Crash report**: *No crash.*

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[SaveFile.zip](https://github.com/Anuken/Mindustry/files/5446651/SaveFile.zip)

**Comment by DeltaNedas** [comment]
sounds like a 4 LOC fix
