### ISSUE TITLE
green lines bug

### ISSUE THREAD

**Issue by rorya01** [Anuken/Mindustry#3157]
**Platform**: Windows

**Build**: 6.0 beta branch

**Issue**:  when booting up the game, green lines appear horizontal across the screen and obscure vision heavily.

**Steps to reproduce**: the issue accoured on my friends Del laptop and it keeps happening when he loads up the beta branch but only the beta branch,

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* he deleted all his mods before starting

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* save fie i cant provide sadly, as far as i know its not tied to save files as he deleted his then it happened again.

**Crash report**: did not crash the game.

---

*Place an X (no spaces)  no i did not read below.. sorry if someone reported this before im new to github and just made an account to report this.

**Comment by DeltaNedas** [comment]
1. duplicate
2. tell your friend to fix his gpu and/or drivers

**Comment by Anuken** [comment]
>  no i did not read below.

consider doing it next time, it's not very hard.

**Comment by Legomonster33** [comment]
Ya didn't even provide a photo 
Or more specific details about the erroneous device
Or see if this has been reported before
Like bruh come on its not that hard

**Comment by rorya01** [comment]
Only image i have, my friend isnt really helping me with this and him
explaining things to me is like trying to get information from a 7 year old.
