### ISSUE TITLE
UI is not rendered properly on 4k display

### ISSUE THREAD

**Issue by Ansraer** [Anuken/Mindustry#3158]
**Platform**: *Steam Windows*

**Build**: *v6 111*

**Issue**: Ok, so for some reason the UI (Main menu and hud) looks pixelated when the game is played on a 4k monitor. The actual game (map, unity, buildings, etc) looks fine, but the UI (which I am assuming is rendered to another buffer) looks like it's 1080p or even 720p.

**Steps to reproduce**:
Start game from steam on a 4k display. Happens both in borderless and fullscreen mode. Interestingly enough the UI looks somewhat better (like some AA was applied) every time I try to take a screenshot with ShareX. Compared e.g. text in chrome it is still pixelated, but not to the extent it was before.

I already tried resetting my graphic settings to default and restarted the game multiple times.

**Link(s) to mod(s) used**: Unmodded

**Save file**: Happens in the main menu already.

**Crash report**: Not crashing

Below are two screenshots I took with my phone, both from the exact same area of my display. One shows how the UI is rendered in the main menu while the other shows how text should actually look like on my display (chrome).
The game looks significantly worse than you can see on the image, but when you compare the text in them the problem should still be easily noticeable.

[Images.zip](https://github.com/Anuken/Mindustry/files/5448242/Images.zip)

EDIT: Forgot to mention it, but the pixelate option is disabled

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
>screenshots
>i took with my phone
[X]

**Comment by Ansraer** [comment]
Don't have an external capture card. And as mentioned in my issue when I use software to take screenshots the problem is not as visible as it actually is.

**Comment by Anuken** [comment]
The UI only has one resolution, it's not designed for 4K screens.
