### ISSUE TITLE
move Core in compaign

### ISSUE THREAD

**Issue by SupinePandora43** [Anuken/Mindustry#3160]
Platform: Android, (probably windows, but i'm too lazy for it)
Build: `111`

Issue: core can be moved

# Steps to reproduce

1. Play compaign survival map.
2. Upgrade core (from **3x3** core, to **4x4**)
3. Loose (core being capped/destroyed)
4. Launch to this map again
5. (result) core is spawned again, but **in 1 block different position**. // **copper ore is spawned too**
---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's fine.

**Comment by SupinePandora43** [comment]
Are you sure about that?
What if i turn whole compaign map to copper source?
It will take ages but it's possible.

**Comment by Anuken** [comment]
That would take an absurd amount of time, and you'd need to spend and absurd amount of copper to do it. Not really a problem.

**Comment by DeltaNedas** [comment]
ok enjoy your copper ore
