### ISSUE TITLE
Very fast trasportation [snek]

### ISSUE THREAD

**Issue by The-yeeter** [Anuken/Mindustry#3161]
**Platform**: *Windows*

**Build**: 10853

**Issue**: *Explain your issue in detail.*
This combination allows very fast item trasport

**Steps to reproduce**: build something like this
![obraz](https://user-images.githubusercontent.com/73578057/97403490-cc15ce00-18f4-11eb-8efb-60160833ec20.png)

**Link(s) to mod(s) used**: none

**Save file**: can do it everywhere

**Crash report**: none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
This is an issue? I don't see why/how

**Comment by QmelZ** [comment]
> This is an issue? I don't see why/how

probably reported because snek is removed

**Comment by Quezler** [comment]
fast != throughput

**Comment by DeltaNedas** [comment]
bruh thats a router chain the throughput is shit cant you see
not a bug

**Comment by MLGTASTICa** [comment]
Not really a bug , its FAST but its capacity to transport is low . Snek could take 3-5 lanes of material , this lane can't even take 1 full lane.

**Comment by Anuken** [comment]
That's less than a titanium conveyor of throughput.
