### ISSUE TITLE
you can place 2x2+ blocks on the map's edge

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3164]
**Platform**: Android 9

**Build**: 10860 i think?

**Issue**:
A 1x1 block cannot be placed on the map edge's shadow, but bigger blocks can.
![bug](https://user-images.githubusercontent.com/39013340/97428819-6e8e7b00-190e-11eb-853d-5454171f9a65.jpg)

**Steps to reproduce**:
1. Try to place small wall
2. Place big wall

**Link(s) to mod(s) used**: routorio

**Save file**: github doesnt allow msav h

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Somewhat related to #3047

**Comment by Anuken** [comment]
This isn't a problem.
