### ISSUE TITLE
Weirdness with armor and health-modifying status effects

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#3166]
**Platform**: *Android/iOS/Mac/Windows/Linux*
All

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
111

**Issue**: *Explain your issue in detail.*
Armor is applied after health multiplier from status effects, making it WAY more efficient (most noticeable in the boss status effect)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
A conversation in the discord mentioning a mace surviving 30 duos undamaged. To spot the exact issue i measured damage done to the mace using the F8 console, including observing that a fuse does 48.5 damage to the mace.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[macetest.zip](https://github.com/Anuken/Mindustry/files/5451447/macetest.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Isn't armor supposed to just make bullets weaker?
