### ISSUE TITLE
Sector instantly lost after checking another Sector

### ISSUE THREAD

**Issue by C4nc3ER** [Anuken/Mindustry#3169]
**Platform**: *Android*

**Build**: *Build 111*

**Issue**: *Went from Sector 222 to Frozen Forest, only for Sector 222 to be lost instantaneously. Never has happened before with any of my other sectors.*

**Steps to reproduce**: *I don't know how to reproduce, nor how it was caused. I only know that I placed some Scorches, Large Copper Walls, and Menders and supplied power near the drop area.*

**Link(s) to mod(s) used**: *No mods were used.*

**Save file**: *https://www.dropbox.com/s/w8ifh7a5mgzw7t4/sector-serpulo-222.msav.zip?dl=0*

**Crash report**: *Not a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
