### ISSUE TITLE
Unit factory

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#3170]
**Platform**: Android

**Build**: Beta 111

**Issue**: Unit limit passed when more than 1 factory working at the same time
![Screenshot_2020-10-29-00-38-44-70](https://user-images.githubusercontent.com/70744599/97475520-f1035300-197f-11eb-9048-0adfbec1d0a6.png)

**Steps to reproduce**: Make more than 1 factory and run them at the same time

**Link(s) to mod(s) used**: -

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[Kek.zip](https://github.com/Anuken/Mindustry/files/5453892/Kek.zip)

**Crash report**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ilya246** [comment]
sad, i can't spawn 15k flares anymore (i have done that)
