### ISSUE TITLE
When you try to shoot as a router, it crashes

### ISSUE THREAD

**Issue by KingKrafty** [Anuken/Mindustry#3171]
**Platform**: *Android

**Build**: 111

**Issue**: When you try to shoot as a router, it crashes

**Steps to reproduce**: posses router and hold on screen

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Crash report: The contents of relevant crash report files. REQUIRED if you are reporting a crash.

This is part of the template. Why did you delete it?

**Comment by DeltaNedas** [comment]
>acknowledge that mindustry crashed
>dont post the crash log

big brain
