### ISSUE TITLE
sandbox items in loadout

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3172]
**Platform**: dunno ask legomaster

**Build**: no idea

**Issue**:
you can put sandbox blocks, other cores, probably blocks you havent researched, maybe ores and enemy spawns in your loadout schematic.

when fixing please consider leaving extra cores in there, they're certainly not cheap so if someone thinks of making a core coresnek let them.

**Steps to reproduce**: 
1. make schem on sandbox with stuff mentioned above
2. try it out when launching (ores and enemy spawn may require changing block ids)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
already fixed

**Comment by DeltaNedas** [comment]
oh good
