### ISSUE TITLE
Infinite Resource from unloading Core bug 6.0

### ISSUE THREAD

**Issue by C0deMonk3y** [Anuken/Mindustry#3173]
Platform: Windows

Build: Steam Build 111

Issue: If you take materials out of your core (with an unloader) and put them back in the subtraction doesnt impact your income score but the income does 

Steps to reproduce: discovered because i noticed i was running out of resources while playing on a map but while i was playing on another map they were increasing rapidly.
Reproduced specifically with an everything (unspecified) unloader that i was sorting out only the materials i needed for drone production and sending the rest back into my core.  
Ive used it to get my income to all materials to over 1k/min with a bunch of unloaders just pulling and dumping back into my base with an overdrive projector to increase the conveyor speeds

Link(s) to mod(s) used: Vanilla (no mods)

Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

Crash report: Not a crash causing issue
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[saves.zip](https://github.com/Anuken/Mindustry/files/5455929/saves.zip)

**Comment by Legomonster33** [comment]
save file?
