### ISSUE TITLE
Region #170: Guardian coming too late

### ISSUE THREAD

**Issue by PenelopeFudd** [Anuken/Mindustry#3176]
**Platform**: Android

**Build**: beta build 111

**Issue**: In hex 170, the game warned me that "The Guardian" is coming in 10 rounds, but there are only eight rounds left (total: 40)

**Steps to reproduce**: Play campaign until you've come to hex #170 for the second time, advance to level 32, see warning box pop up.  Also when there is 5 rounds before the Guardian arrives, and 2 rounds.  I'm now at round 40, and thinking "whew, I'm glad I finished before the Guardian got here!".

**Link(s) to mod(s) used**: none

**Save file**: I have no idea how to find a save file for a campaign level on android.

**Crash report**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
if you are attacked again remember that.

**Comment by Anuken** [comment]
It's still coming, but only if you get attacked.

**Comment by PenelopeFudd** [comment]
I came back to this level, and the warning about the Guardian was again off by 2 levels.
