### ISSUE TITLE
Failed to read remote method 'onInfoToast'!

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#3178]
**Platform**: *Windows*

**Build**: *Release build 104.10*

**Issue**: *It shows an error (Failed to read remote method 'onInfoToast'!) when connecting to my custom build server*

**Steps to reproduce**: *I set `collidesTiles` to `true` and `collidesTeam` to `true` for the `massDriverBolt`, build the server with `gradlew server:dist`, ran it with `gradlew server:run` and loaded a map by typing `host glacier sandbox`*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A*

**Crash report**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by QmelZ** [comment]
kind of unrelated, but you dont need to use server:dist if you will do server:run everytime, server:dist outputs a jar file and dist compiles and runs

**Comment by antonilol** [comment]
![image](https://user-images.githubusercontent.com/49868160/97543931-3435e400-19c9-11eb-8afb-4fa2d9ec28f8.png)
ok maybe i have to specify a version

**Comment by TheSlaylord** [comment]
well, `massDriverBolt` does not exist in v5...

**Comment by antonilol** [comment]
my client is release build 104.10 as a said in the bug report

**Comment by antonilol** [comment]
how do i specify a version when compiling to server?

**Comment by QmelZ** [comment]
-Pbuildversion:
