### ISSUE TITLE
Cannot select custom core schematic in launch menu

### ISSUE THREAD

**Issue by TheSlaylord** [Anuken/Mindustry#3179]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Steam 111

**Issue**: *Explain your issue in detail.* Cannot select a custom core schematic in launch menu

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1) Save any schematic with the core.
2) Try to launch to a vacant sector.
3) When clicking on your own schematic, nothing happens.
![1127400_20201029114948_1](https://user-images.githubusercontent.com/62336673/97546439-7f59f200-19dd-11eb-934a-a38b7ae6c6e9.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* none

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
you cant afford it, see .disabled(() -> )

**Comment by TheSlaylord** [comment]
oj
