### ISSUE TITLE
UI Scale is smaller in v6 Betas

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#3180]
**Platform**: *Windows*

**Build**: *111*

**Issue**: *Both in BE build, V5 and V6; i have UI set to 100%. However, in 111 UI appears like 75% even though it is set to 100% in settings.*

**Steps to reproduce**: *Just open 104 and 111 and compare.*

**Link(s) to mod(s) used**: *none*

**Save file**: *this is a visual change/bug, i dont think save is nesesary.*

**Crash report**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image](https://user-images.githubusercontent.com/62565267/97549150-196f6980-19e1-11eb-8822-267d3b086f41.png)

**Comment by DeltaNedas** [comment]
no

**Comment by Anuken** [comment]
This doesn't happen to me on any platform.
