### ISSUE TITLE
ADD MORE MIND FOR DRONES

### ISSUE THREAD

**Issue by KeyZenD** [Anuken/Mindustry#3183]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Issue**: *When boss crash everything, drones just chill on enemy spawn.*

**Steps to reproduce**: *Every time, they are always very stupid.*

**Link(s) to mod(s) used**: *No use.*

**Comment by rmperkow** [comment]
Build/save file?

**Comment by Quezler** [comment]
command point > retreat
