### ISSUE TITLE
logical operation “not” return a wrong number

### ISSUE THREAD

**Issue by Bell2U** [Anuken/Mindustry#3193]
**Platform**: *Android*

**Build**: *beta build 111*

**Issue**: *i wrote these following code in a microprocessor and built a message block linked to the microprocessor:

set a 1
op not b a b
print b
printflush message1

and i got a negative two printed on the message1 block
 if i change “set a 1” to “set a 0”, i got a negative one.
*

**Steps to reproduce**: *follow the steps i wrote above, the bug occurs*

**Link(s) to mod(s) used**: *i didn't install any mod*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

i'm not sure about this section...if i need to upload the zip file? how?*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
`not` flips bits.
