### ISSUE TITLE
player stuck in the duo

### ISSUE THREAD

**Issue by songsammy** [Anuken/Mindustry#3197]
**Platform**: *Android*

**Build**: *v6*

**Issue**: *After my baby clicking on some objects, i stuck in a duo. Just look at the screenshot*

**Steps to reproduce**: *My baby did it so i don't know why. What i do know is that he was fast, triple clicking on my duo*

**Link(s) to mod(s) used**: *None*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[mindustry stuck in duo .zip](https://github.com/Anuken/Mindustry/files/5468654/mindustry.stuck.in.duo.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by songsammy** [comment]
![Uploading Screenshot_2020-10-31-15-07-04-876_io.anuke.mindustry.jpg…]()

**Comment by songsammy** [comment]
![Screenshot_2020-10-31-15-07-04-876_io anuke mindustry](https://user-images.githubusercontent.com/30046778/97774121-5332a280-1b90-11eb-9049-9763f4035c52.jpg)

**Comment by songsammy** [comment]
![Screenshot_2020-10-31-15-47-34-525_io anuke mindustry](https://user-images.githumarkercontent.com/30046778/97774145-78bfac00-1b90-11eb-9735-9e5208599f88.jpg)
The red mark shows that i am somewhere inside the duo
![Screenshot_2020-10-31-15-47-43-122_io anuke mindustry](https://user-images.githubusercontent.com/30046778/97774157-8b39e580-1b90-11eb-867a-2a73f7f2db3c.jpg)
And i can't build or destroy

**Comment by DayTimer** [comment]
You can't build while you're controlling a turret. Only some units (like core units, support/spider branchers) can build. 

You should respawn from the core or control another unit (double-click it).

**Comment by DayTimer** [comment]
Feature. You can exit the turret by double-tapping another unit, turret, or double-tapping the core. You can manually target & shoot by long-tapping.
Just pan to the core and double-click it
