### ISSUE TITLE
Call.label being glitchy on a server

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#3198]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
111

**Issue**: *Explain your issue in detail.*
When Call.label is done on a server, whatever was the label appears in the center of your screen for 1 frame.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Using Call.label on .pl, other players did indeed confirm this happening

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
i believe this issue has already been reported sometime in the past, just not sure if it was on github or fixed in be 🤔
