### ISSUE TITLE
Crash Report in an unexplored sector (Different Crash Report from the already reported one)

### ISSUE THREAD

**Issue by BonzieC5303** [Anuken/Mindustry#3199]
**Platform**: *Windows 7*

**Build**: *10931*

**Issue**: *Entering Sector 64 will crash the game. This affected my resources in other sectors.*

**Steps to reproduce**: 
*1. Go to Campaign
2. Launch my core to Sector 64.
3. ...
4. Crash... Not stonks*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A, it's a campaign sector*

**Crash report**: 
[crash-report-10_31_2020_15_50_30.txt](https://github.com/Anuken/Mindustry/files/5468743/crash-report-10_31_2020_15_50_30.txt)

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, it's the same crash.
