### ISSUE TITLE
Unable to run new release 

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#32]
Clicking on the EXE doesn't work. Ran the .jar and found this 
![image](https://user-images.githubusercontent.com/30189017/34329156-acde9554-e8c2-11e7-9290-d7941b3d50b6.png)
I have the right Java versions installed... what did i do wrong?

**Comment by Anuken** [comment]
Should be fixed now: tested and runs on a Windows laptop. Feel free to re-open if you still have issues.
