### ISSUE TITLE
Multiplayer campaign issues

### ISSUE THREAD

**Issue by emorrp1** [Anuken/Mindustry#3203]
**Platform**: Linux

**Build**: v111

**Issue**: (feel free to tell me to open separate reports)

1. Because clients cannot research on their own, they're also unable to access the Core Database
2. ~Clients can't use the Host's new research if it needs a new "tab" in the bottom right~
3. At the end of a sector, the Clients' wave counter doesn't disappear like the Host's does
4. This could be intentional, but when Launching to a new sector the resources spent are not transferred, making the beginning *very* slow going as you have to wait for every little bit of copper to build the copper mines.
5. When the Host launches to the next map a) it doesn't automatically Host b) the Clients don't automatically try to reconnect
6. On clients, when left-click dragging to build "sometimes" the dragging effect is ignored i.e. it doesn't show the ghost buildings which still held down and only builds one. This is not due to an accidental middle-click and *never* happens with conveyors, just buildings.

**Steps to reproduce**:

1. Client -> Research -> "Only the host can research items" -> ok; Expect a Core Database button and ideally a read-only view of the research tree.
2. Host -> Research -> Copper Wall; Expect a wall section to appear without disconnecting/reconnecting after the notification
3. Survive wave 10
4. Launch to Frozen Forest -> Click on core, observe <10 items; Expect c. 1000 copper
5. Planet Map -> new sector -> Launch -> Launch; Expect the clients to automatically join the new map
6. Cannot reliably replicate, sorry

**Link(s) to mod(s) used**: No mods

**Save file**: [campaign.zip](https://github.com/Anuken/Mindustry/files/5469101/campaign.zip)

**Crash report**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by YellOw139** [comment]
2 is known and fixed https://github.com/Anuken/Mindustry/issues/3152

**Comment by Anuken** [comment]
1. Not supposed to be able to.
3. Will fix.
4. What resources spent? Sounds like you're confusing core schematics costs and loadouts.
5. That's not how the game is supposed to work. Once you stop hosting or exit a game, that's it. There is no leftover state.
6. I've never had this happen, it not occurring *with conveyors* doesn't make any sense (there isn't any conveyor-specific code for building) and I've never seen anyone report this. Won't fix.

**Comment by emorrp1** [comment]
Thanks for the quick response.

@Anuken for 4, quite possibly we aren't far enough into the campaign to get new schematics/loadouts, but even with the most basic one, I would expect to launch with something - For example, from Clear Game Data launching Ground Zero starts with 200 copper, why don't other new sectors start with that instead of 0?

**Comment by Anuken** [comment]
You need to specify what you want to launch with. 

![image](https://user-images.githubusercontent.com/10100000/97781258-6cbbf600-1b60-11eb-9ae8-fec783bd663a.png)

These are all 0 by default.

**Comment by emorrp1** [comment]
Ohhhhh, well that's actually quite obvious in retrospect, thanks, explains the X + Y, you can edit the launch Resources for X but Y is fixed by the schematic.
