### ISSUE TITLE
Graphite and Titanium are easily confused unless zoomed in

### ISSUE THREAD

**Issue by emorrp1** [Anuken/Mindustry#3205]
**Platform**: Linux

**Build**: v111

**Issue**: Graphite and Titanium are different shapes, but approximately the same colour, and when you have a full 10/s conveyor of each, the shape is harder to distinguish. Also happens to a lesser extent with titanium/lead, but lead's at least a darker shade.

**Steps to reproduce**: Have a mess of fast conveyors each individually isolated to a single item type, then zoom out to a more overview-like level and start building a new mine, accidentally connect it to a conveyor of the other type and notice the conveyor is no longer a uniform item stream.

I don't think we get confused with any other combination of items, and it's at least partially mitigated now that the Core acts as an incinerator at max capacity, rather than blocking everything.

**Link(s) to mod(s) used**: No mods

**Save file**: https://github.com/Anuken/Mindustry/files/5469101/campaign.zip

**Crash report**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by UltraBlackLinux** [comment]
That's not a bug. That's textures.

**Comment by Anuken** [comment]
This is not a bug.

**Comment by emorrp1** [comment]
@UltraBlackLinux not sure what you mean, are you saying it's deliberately confusing? Or that I should rephrase it as a feature request in Mindustry-Suggestions?

**Comment by DeltaNedas** [comment]
bruh just zoom in and/or pause
