### ISSUE TITLE
Red player unit factories have unit limit 2,147,483,647; and Gray has 0

### ISSUE THREAD

**Issue by varicium** [Anuken/Mindustry#3210]
**Platform**: Mac

**Build**: steam build 111

**Issue**:
(1) Red player unit factories have a unit limit of 2,147,483,647 (Integer.MAX_VALUE).
(2) Gray player unit factories have a unit limit of 0.

Happens to all the ground, air, naval factories.
Does not happen to players in other colors.

**Steps to reproduce**: 

_In-game editor view being the red player:_
<img width="1792" alt="Red player in in-game editor" src="https://user-images.githubusercontent.com/72651061/97784311-88fb7980-1bd8-11eb-9c42-82724b50b165.png">
_In-game editor view being the gray player:_
<img width="1792" alt="Gray player in in-game editor" src="https://user-images.githubusercontent.com/72651061/97784312-8a2ca680-1bd8-11eb-9d4d-fd17292ea399.png">

_In the game in sandbox mode:_
<img width="1792" alt="Red player in game" src="https://user-images.githubusercontent.com/72651061/97784318-9c0e4980-1bd8-11eb-834b-8d65d9af3df3.png">
_In the game in sandbox mode:_
<img width="1792" alt="Gray player in game" src="https://user-images.githubusercontent.com/72651061/97784305-8436c580-1bd8-11eb-9d87-8671eebf254e.png">

**Link(s) to mod(s) used**: N/A

**Save file**: [Flat World.msav.zip](https://github.com/Anuken/Mindustry/files/5469441/Flat.World.msav.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The red team is the wave team, so it has no unit limit.

**Comment by MEEPofFaith** [comment]
ohno
