### ISSUE TITLE
Plastanium Conveyor Manual Item Placement Bug

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#3218]
**Platform**: *Windows*

**Build**: *BE10931*

**Issue**: *Manually putting items onto a Plastanium Conveyor doesn't create a Quezler and really messes up the conveyor's capabilities.*
![image](https://user-images.githubusercontent.com/54301439/97793376-50dc4280-1ba8-11eb-9334-b30fdf945780.png)
[video](https://youtu.be/4MgjwYpz-ig)

**Steps to reproduce**: *Just try to put items on whatever you're controlling onto a Plastanium Conveyor.*

**Link(s) to mod(s) used**: *I was using [Progressed Materials](https://github.com/MEEPofFaith/progressed-materials/tree/6.0), but I don't think that really matters.*

**Save file**: *[Quelzohno.zip](https://github.com/Anuken/Mindustry/files/5470072/Quelzohno.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
roomba(s)*

**Comment by MEEPofFaith** [comment]
Saving and exiting allows you to release one set of items.
![image](https://user-images.githubusercontent.com/54301439/97795116-79236b80-1bbf-11eb-8633-4b6cc2c2aa9f.png)
![image](https://user-images.githubusercontent.com/54301439/97795118-7aed2f00-1bbf-11eb-8d3f-7047a1161bfd.png)
![image](https://user-images.githubusercontent.com/54301439/97795121-7d4f8900-1bbf-11eb-8efb-ecbbae87e27f.png)

Once you get back to the original item, in this case, Metaglass, it'll release it on its own.
