### ISSUE TITLE
When launching from a sector it forces you to launch from the nearest nearby sector

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3220]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* be build 10967

**Issue**: *Explain your issue in detail.*
when launching from a random sector to a different sector it forces you to launch from an adjacent sector

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. attempt to launch from sector to non adjacent sector
2. it makes you launch from adjacent sector

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
non save file specific

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is exactly what it's supposed to do.

**Comment by Legomonster33** [comment]
> This is exactly what it's supposed to do.

But it's annoying and just makes launching from any sector more complicated as instead of it being
1. Launch
Its
1.launch pad all you items to the adjacent sector
2.launch

**Comment by Anuken** [comment]
Sectors can only launch to adjacent locations, unless it's a preset. That's just how it works.

> launch pad all you items to the adjacent sector

Or just launch pad your items to the sector you're launching to?

**Comment by Legomonster33** [comment]
> Or just launch pad your items to the sector you're launching to?

you have to launch your items to an adjacent sector if you want to launch with a loadout / resources

**Comment by Legomonster33** [comment]
thank u

**Comment by GruveXp2** [comment]
Maybe it would be cool if you could choose which adjacent sector to launch from, instead of it automatically selecting

**Comment by ChazWinterYT** [comment]
I like how there is no issue launching halfway across the planet if it's a sPeShUL sector, but not for the numbered ones. As if we are walking to the next sector or taking the bus.
Why bother with the launch into the air animation, then? 
If we can launch supplies into the sector NEXT TO the one we want from anywhere, then what's the point of the random restriction on just launching straight to the sector in question?
"That's just the way it is" is not an explanation, it's a cop out.

**Comment by kullre** [comment]
are you stupid? it fits inline with the narrative with the fact you can't just go anywhere, and named sectors aid to let you explore the planet faster because most are spread out on vastly different regions instead of all just being in a tiny group. 
would you rather go back to the old mindustry where its just the named sectors and nothing else? 
this isn't a custom game its the campaign, there are going to be arbitrary restrictions like with any videogame campaign.
also by the logic you're giving, i should just be able to go to the final mission of clash of clans "because i want to" just think about that for a second.

**Comment by ChazWinterYT** [comment]
It's amusing how mad you are about this

**Comment by kullre** [comment]
Uhh huh... i'm a highschooler and i frankley don't care that you think your are smarter than me
