### ISSUE TITLE
Core Launch loadout can delete terrain blocks

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3222]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 111

**Issue**: *Explain your issue in detail.*
when launching with a loadout it can delete terrain blocks

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. launch to sector with terrain near core with a bigger loadout (image shows sector 258)
2. terrain = gone
3. shadow land= stay

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
sorry am noob idk how to export a campain map
![image](https://user-images.githubusercontent.com/54417042/97797763-aedf4900-1bed-11eb-9d74-4010f33be502.png)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
> **Platform**: _Android/iOS/Mac/Windows/Linux_ windows 10 64 bit
> 
> **Build**: _The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME._ beta 111
> 
> **Issue**: _Explain your issue in detail._
> when launching with a loadout it can delete terrain blocks
> 
> **Steps to reproduce**: _How you happened across the issue, and what exactly you did to make the bug happen._
> 
> 1. launch to sector with terrain near core with a bigger loadout
> 2. terrain = gone
> 3. shadow land= stay
> 
> **Link(s) to mod(s) used**: _The mod repositories or zip files that are related to the issue, if applicable._
> none
> 
> **Save file**: _The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME._
> sorry am noob idk how to export a campain map
> ![image](https://user-images.githubusercontent.com/54417042/97797763-aedf4900-1bed-11eb-9d74-4010f33be502.png)
> 
> ## **Crash report**: _The contents of relevant crash report files. REQUIRED if you are reporting a crash._
> not a crash
> _Place an X (no spaces) between the brackets to confirm that you have read the line below._
> 
> * [x]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
a heck

**Comment by DeltaNedas** [comment]
cp saves/sectornumhere\t somewhere/save.msav.txt
