### ISSUE TITLE
[new features discuss]Add ways to analyse the power

### ISSUE THREAD

**Issue by VXF2016** [Anuken/Mindustry#323]
It is hard to analyse the power especially you cannot see the power that Generators really perduced, and the power consumers really costs.I think it is nessary to add ways analyzing the power.

To add blocks to see the power in game or simplely see the power by touch blocks? or other ways. Is there any technical difficulty?

**Comment by ValentinHacker** [comment]
There are several times when i had 3 nuclear/thorium generators feeding just 1 silicon smelter and for some reason even though my batteries were full and power nodes plenty, the smelters did not operate at all, i had to delete the smelter and rebuild.

A feature like this would be really useful in debugging...

**Comment by islq** [comment]
I have add a power graph info when tap battery. I'm not sure where to display it, so I created a new fragment, but it worked at least.
#348

**Comment by Jayshua** [comment]
Another thing that could be useful is seeing the power status of an entire power network. Just an overall number like +15 power or -5. That way it's super easy to tell if you need more generators.

**Comment by Anuken** [comment]
Implemented in 8c6c4c2630b8188ec13388f61fbb647225710ec8.
