### ISSUE TITLE
Logic can Ban ppl [Not really a bug, but needs to get fixed}

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry#3231]
**Issue**
There is a way to ban ppl by using logic, so that the server thinks, the player is interacting with stuff too quickly, and you get banned for 1 hour.
![Screenshot_20201101_142556](https://user-images.githubusercontent.com/62404294/97804276-082b9480-1c4f-11eb-8f7e-d45c9b3b0b95.png)
Those suckers didn't want to give me the logic thingy, so I don't have and evidence, but please try to fix that!
Thanks alot!

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
So... what is the method, what's the save, what's the build?

**Comment by UltraBlackLinux** [comment]
@Anuken I already said, I can't provide it, because the guys online were too stupid to have me copy that.

**Comment by Anuken** [comment]
That shouldn't have prevented you from looking at the build number in your main menu, or saving the game through Esc -> Save Game (*yes, it works in multiplayer*).
