### ISSUE TITLE
Game stopping after trying to add a command into a processor 

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry#3235]
**Platform**: iOS

**Build**: 111.2

**Issue**: After tapping the “add” button in a processor the game stops.

**Steps to reproduce**: 
1. Place and open a processor
2. Tap the “add” button.

A video of the process: https://youtu.be/o7A_SWVf4Ng

**Link(s) to mod(s) used**: N/A

**Save file**: 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5471606/mindustry-data-export.zip)

**Crash report**: For some reason there isn’t any crash reports 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already reported.
