### ISSUE TITLE
instructions list is not cleared on restart

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3237]
**Platform**: Android 9

**Build**: 10986

**Issue**:
When restarting mindustry without swiping it away, modded instructions are duplicated.
![bug](https://user-images.githubusercontent.com/39013340/97815761-59a44580-1c88-11eb-9610-ff4142c1c743.jpg)

**Steps to reproduce**:
1. routorio.
2. open processor, click add.
3. note 2 extra instructions, normal.
4. restart by clicking exit then starting it.
5. go to step 2 and see the 4 extra instructions!

**Link(s) to mod(s) used**: deltanedas/routorio

**Save file**: issue is in a dialog

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix. That's how statics work on Android.
