### ISSUE TITLE
Segment says "H"

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3238]
**Platform**: Windows 10

**Build**: Steam Build 111

**Issue**: java.lang.ClassCastException: mindustry.world.blocks.ConstructBlock$ConstructBuild cannot be cast to mindustry.world.blocks.defense.turrets.PointDefenseTurret$PointDefenseBuild
Wave 24 of Sector 250; Reign destroys a Segment mid-fire causing a crash.

**Steps to reproduce**: 
![20201101174150_1](https://user-images.githubusercontent.com/19158169/97817331-a9bfdf80-1c69-11eb-9b2d-3502489b01af.jpg)

**Link(s) to mod(s) used**: None related to issue. 

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5471888/saves.zip)

**Crash report**: 
[crash-report-11_01_2020_17_35_20.txt](https://github.com/Anuken/Mindustry/files/5471890/crash-report-11_01_2020_17_35_20.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
