### ISSUE TITLE
East (Right) Side map crash issue

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3240]
**Platform**: *iOS, but it has only 1GB RAM*

**Build**: *beta 111*

**Issue**: *Every time i panned my camera over to the east (right) side of any larger map the game would unexpectedly freeze and crash.*

**Steps to reproduce:** *Load a larger map and pan your camera to the east side. My exact two encountered issues were with Sector 175 and Debris Field.*

**Link(s) to mod(s) used**: *no*

**Save file**: *not sure how one exports saves on iOS.*

**Crash report**: *no (iOS 12.4.8 doesnt do that last time i checked)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported. Of course, it wouldn't because nobody knows how to use iOS TestFlight.**

**Comment by Anuken** [comment]
I have no problems with panning the camera over to the right on a simulator or a real device, and with so little information I can't do anything.

**Comment by D-player1** [comment]
~~pretty sure that's because of your 1 GB RAM~~

Large maps need larger RAM

**Comment by Anuken** [comment]
Changes of position on the map should not require additional memory.
