### ISSUE TITLE
Payload conveyor + payload router display issue

### ISSUE THREAD

**Issue by Kyllingene** [Anuken/Mindustry#3242]
**Platform**: *Windows*

**Build**: *bleeding-edge build 10990 (running on dedicated server, same version # for client and server.)*

**Issue**: *When placing payload routers beside payload conveyors, the conveyors display an effect as if
the routers were connected, even when offset or 1 tile away. Gif linked for clarification.*
![Betabug](https://user-images.githubusercontent.com/69094702/97825962-22786900-1c75-11eb-9fa8-9112e294cdf1.gif)

**Steps to reproduce**: *Place payload conveyor line. Place payload routers facing into the line offset by a tile, or a tile away from the line.*

**Link(s) to mod(s) used**: *None*

**Save file**: *https://drive.google.com/file/d/1gtkYdYmsWoUd8_QS2LqOh7dUctm9I9aY/view?usp=sharing*

**Crash report**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
