### ISSUE TITLE
When controlling a weapon you have an aneurysm

### ISSUE THREAD

**Issue by the-kido** [Anuken/Mindustry#3244]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Build #111 

**Issue**: *Explain your issue in detail.*
When I hop into a weapon by double-tapping it shakes around weirdly. Oddly it fixes once I shoot with it.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Fly to a weapon, double-tap it, it'll shake as if having an aneurysm.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://drive.google.com/file/d/1iUH0AfXMqK4HU6GFCNSbDSmd12UMrxRe/view?usp=sharing

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No Crash

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen on my device(s), won't fix.
