### ISSUE TITLE
Procedural generation issue

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3245]
**Platform**: *All*

**Build**: *Beta 111*

**Issue**: *The "procedurally generated" sectors each are generated the exact same for everyone. The same sector will always be the same for everyone.*

**Steps to reproduce**: *Load a sector (i suggest 175 because its next to ground zero and its easy), clear campaign saves, and reload/regenerate the sector.*

**Link(s) to mod(s) used**: *no*

**Save file**: *None necessary or able to be provided because multiple from separate clients would be needed. Anyways, if this is a legitimate glitch in procedural generation one will not be necessary. Either you will see it for yourself or it won't happen.*

**Crash report**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported because I am at school at this moment.**

**Comment by Anuken** [comment]
They're supposed to be.

**Comment by BlueWolf3682** [comment]
that defeats the entire purpose of "procedurally generated campaign" but okay.

**Comment by Anuken** [comment]
I don't see why that's the case. Were you planning on playing the campaign twice? Have you explored every single one of the 200+ sectors and want more?

**Comment by BlueWolf3682** [comment]
i was honestly planning on doing both and i think many people agree with me on that.

**Comment by Anuken** [comment]
That's an absolutely bizzare concept to me and I don't see how anyone would be interested in that.

**Comment by sample-text-here** [comment]
Maybe there should be a "seed" input when you start so that you can get a different campaign every time.

**Comment by Anuken** [comment]
No. The campaign and its preset locations are designed with a one seed in mind. It's not supposed to change.

**Comment by BlueWolf3682** [comment]
here, ill give a pov: 
  you love the campaign because its fun and challenging, without other players to slow you down and get you killed. but the campaign is just the same every time, no difference and nothing new after youre done with run 1. now, you have to play on either maps that are created by users, which usually arent that good, or you have to play on the servers with other players, who waste your resources and kill your braincells with the worst designs one has ever seen.

**Comment by D-player1** [comment]
Play your own map, done

**Comment by BlueWolf3682** [comment]
would you want to manually make over 200 maps?

**Comment by Anuken** [comment]
> but the campaign is just the same every time, no difference and nothing new after youre done with run 1

Sure, but the campaign isn't designed for *"runs"* at all, it's not a roguelike! I honestly don't understand how someone could complete the whole 272 (often very similar) sectors on the planet and still somehow want more. Even if you take 15 minutes to capture each one (*very unlikely, considering how long waves last and how sector attacks happen*), that's... 68 hours spent capturing sectors. Very few people are going to go that far, let alone *do it again*.

**Comment by D-player1** [comment]
Because launch pad and loadout

**Comment by BlueWolf3682** [comment]
what about the large amount of people who have spent over a thousand hours playing the game? i play more than 68 hours in 14 days, and im a casual mindustry player, who plays other games too

**Comment by itcannotbe** [comment]
> Even if you take 15 minutes to capture each one (very unlikely, considering how long waves last and how sector attacks happen), that's... 68 hours spent capturing sectors. Very few people are going to go that far, let alone do it again.

I think some didn't read this part.

**Comment by BlueWolf3682** [comment]
i absolutely did, if you didnt notice i showed that i would definitely go that far already because mindustry is FUN

**Comment by Anuken** [comment]
> what about the large amount of people who have spent over a thousand hours playing the game

Then you'll have to wait for more planets, more content and more interesting enemy dynamics (*i.e. enemies that don't just sit around while their planet gets captured*).  I'm not going to randomize the campaign just for a tiny niche population; having a new planet each time would cause all sorts of nasty side effects (harder debugging, plenty of possible edge cases for bad spawns, bad locations for presets, bugs related to certain permutations, etc).

**Comment by BlueWolf3682** [comment]
well since youve already coded it to procedurally generate based on sector number with a valid method, why not just have each sector have its seed be sector number * time based random number, with the sector number determining what terrain blocks will be used and the time randomising the layout of the terrain?

**Comment by Anuken** [comment]
> having a new planet each time would cause all sorts of nasty side effects (harder debugging, plenty of possible edge cases for bad spawns, bad locations for presets, bugs related to certain permutations, etc)

**Comment by BlueWolf3682** [comment]
fair point, well made

**Comment by itcannotbe** [comment]
I would like to take this opportunity to point out that anuke's last reply is just qouted from one of his previous replys.

**Comment by DeltaNedas** [comment]
id also like to mention that mods exist

**Comment by Bohaska** [comment]
An idea I have that can fix this is that after you beat the 272 sectors, you gain access to make your own Custom Campaigns in which you can either use the default seeds, choose your own maps, seeds or pick random ones. However, the devs wouldn't fix the nasty side affects associated with it.

**Comment by nichrosia** [comment]
> id also like to mention that mods exist

One possible solution is that somebody could make a mod that can create an entirely new campaign, which could have a link to it in the official game after completing all of the sectors, or we could wait for 7.0 to inevitably come out, and with it, new planets

**Comment by nichrosia** [comment]
#1384

**Comment by XxsuperdeadlysniperxX** [comment]
> here, ill give a pov: 
>   you love the campaign because its fun and challenging, without other players to slow you down and get you killed. but the campaign is just the same every time, no difference and nothing new after youre done with run 1. now, you have to play on either maps that are created by users, which usually arent that good, or you have to play on the servers with other players, who waste your resources and kill your braincells with the worst designs one has ever seen.

Not every bodies schematics are that bad tho
