### ISSUE TITLE
Unit bounded to a removed processor

### ISSUE THREAD

**Issue by Khanx** [Anuken/Mindustry#3246]
This is a **MINOR INTERFACE** (visual) BUG

**Platform**: Windows

**Build**: Steam build 111

**Issue**: After removing a processor, the units continued appearing like linked when hovering the mouse over them BUT they have a common behaviour, not the processor behaviour.

It is a **visual problem** because it shows that the unit is linked to a processor, but it is not

![Bug](https://user-images.githubusercontent.com/2260108/97914319-f978d680-1d4f-11eb-823c-4a8b30f57e45.png)

**Steps to reproduce**:
1- Create a processor
2- Bind Units
3- Remove the processor

Note: There was lag on the server 

**Link(s) to mod(s) used**: Unknown

**Save file**: The problem happened in a server, so I had no access to the save file

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
