### ISSUE TITLE
Black Water

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry#3248]
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Beta build 111, the latest build currently.

**Issue**: *Explain your issue in detail.* This water is black. 
![image](https://user-images.githubusercontent.com/68676339/97930392-41403380-1d39-11eb-964c-ef67f14191c2.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* Literally just play the map.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* Map file
[Cores.zip](https://github.com/Anuken/Mindustry/files/5478590/Cores.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* Game behaves normally otherwise without crashing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/97930538-9c722600-1d39-11eb-8ca3-3c1692f4accc.png)

Your save has no space or water in it.

**Comment by QmelZ** [comment]
posting a 111 bug report just before 112 comes out :D

**Comment by BlueWolf3682** [comment]
can i mention that this "black water" is called oil?

**Comment by 50275** [comment]
Very sorry, must've been some issue with naming
[B.zip](https://github.com/Anuken/Mindustry/files/5478604/B.zip)
I just made this one with a different random name and exported it, it *should* have what I want

**Comment by 50275** [comment]
also @BlueWolf3682 I'm able to pump water from it
