### ISSUE TITLE
Core Launch Loadouts dont overwrite buildings that survived

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3250]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 112

**Issue**: *Explain your issue in detail.*
launching with a core to a previously lost sector doesnt overwrite blocks in the way of your loadout (likely due to the checks preventing terrain replacment)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. go to sector
2. build stuff near core
3. lose sector
4. launch to sector with a loudout
5. buildings in the way dont get overwritten

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
non

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
nah its ok

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 50275** [comment]
> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE

**Comment by Legomonster33** [comment]
> > THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE

this is an elaborate one time setup that cannot be accurately reflected or demonstrated in a save file
