### ISSUE TITLE
(Campain) Sector controled by enemy remove wave cap.

### ISSUE THREAD

**Issue by GamyGamer** [Anuken/Mindustry#3254]
**Platform**: *Windows*

**Build**: *beta build 112.1*

**Issue**: *As title, if sector is controlled by enemy and launched there for first time wave limit is present, but reloadnig map/save will remove cap*

**Steps to reproduce**: *1. Launch core to red zone
2. leave/change map
3. go back to sector
4. done*

**Link(s) to mod(s) used**: *None*

**Save file**: *[saves.zip](https://github.com/Anuken/Mindustry/files/5481478/saves.zip)*

**Crash report**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image](https://user-images.githubusercontent.com/49346764/97990643-8b302480-1de0-11eb-9530-a18bf09fb31b.png)
![image](https://user-images.githubusercontent.com/49346764/97990629-88cdca80-1de0-11eb-966b-24caf82b03b4.png)

**Comment by Anuken** [comment]
It's not supposed to have a cap in the first place.

**Comment by Legomonster33** [comment]
> It's not supposed to have a cap in the first place.

so then the first image is a bug, showing it having a wave cap
