### ISSUE TITLE
Base was erased.

### ISSUE THREAD

**Issue by EricKnaak** [Anuken/Mindustry#3255]
**Platform**: Android

**Build**: 111

**Issue**: base 219 got erased. I beat sector 219, started sending stuff to other sectors via launchpad. jumped to different sectors and upgraded stuff. found out frozen forest was invaded, fixed frozen forest till lvl10. for some reason wanted 219 to launchpad resources from 219 to frozen forest and noticed everything was gone. no debris markers no ghost's in construction mode marking where stuff used to be. Just blank. maybe I built too many large batteries??

more info: https://discord.com/channels/391020510269669376/391020510269669378/773036091233927172

**Steps to reproduce**: No clue. beat 219 after losing frozen forest or during or before. switch sectors. and see 219 wiped....

**Link(s) to mod(s) used**: no mods

**Save file**: https://drive.google.com/file/d/12F9VYYKs67OfCRYjSVuTz2OvgQkjlxZh/view?usp=sharing

I launched back onto the sector before realizing it was wiped. 

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [
[not_useful_save.zip](https://github.com/Anuken/Mindustry/files/5481822/not_useful_save.zip)
X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Probably completely destroyed by the damage calculation bugs, or corrupted. Update.
