### ISSUE TITLE
Game crash and less fps

### ISSUE THREAD

**Issue by Patryk434** [Anuken/Mindustry#3257]
**Platform**: Android

**Build**: Bleeding-Edge 11032

**Issue**: I have less fps. Game crashing when i want to start custom game. 

**Steps to reproduce**: Start custom game on android. 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No log.

**Comment by Patryk434** [comment]
Where is log i cant find it

**Comment by Patryk434** [comment]
> No log.

Where is log i cant find it

**Comment by Anuken** [comment]
Android/data/io.anuke.mindustry(.be)/files/crashes
