### ISSUE TITLE
Game crash and les fps

### ISSUE THREAD

**Issue by Patryk434** [Anuken/Mindustry#3258]
**Platform**: Android

**Build**: Bleeding-Edge 11032

**Issue**: I have less fps. Game crashes when i want to start custom game. 

**Steps to reproduce**: Start custom game

**Crash report**: 
[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 505
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] Loaded mod 'dev-mode' in 24.989376ms
[I] Loaded mod 'ui-lib' in 8.514375ms
[I] Total time to load: 6561
[I] Time to generate menu: 443.65753
[I] Fetched 6 global servers.
[I] [AndroidGraphics] paused
[I] [AndroidGraphics] Managed meshes/app: { }
[I] [AndroidGraphics] Managed textures/app: { }
[I] [AndroidGraphics] Managed cubemap/app: { }
[I] [AndroidGraphics] Managed shaders/app: { }
[I] [AndroidGraphics] Managed buffers/app: { }
[I] [AndroidGraphics] destroyed
[I] [AndroidGraphics] OGL renderer: Adreno (TM) 505
[I] [AndroidGraphics] OGL vendor: Qualcomm
[I] [AndroidGraphics] OGL version: OpenGL ES 3.2 V@415.0 (GIT@004e992, Ibb60c3fdb8, 1575049228) (Date:11/29/19)
[I] [AndroidGraphics] OGL extensions: GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather 
[I] [AndroidGraphics] framebuffer: (5, 6, 5, 0)
[I] [AndroidGraphics] depthbuffer: (24)
[I] [AndroidGraphics] stencilbuffer: (8)
[I] [AndroidGraphics] samples: (0)
[I] [AndroidGraphics] coverage sampling: (false)
[I] [AndroidGraphics] Managed meshes/app: { }
[I] [AndroidGraphics] Managed textures/app: { }
[I] [AndroidGraphics] Managed cubemap/app: { }
[I] [AndroidGraphics] Managed shaders/app: { }
[I] [AndroidGraphics] Managed buffers/app: { }
[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 505
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] Total time to load: 4645
[I] Time to generate menu: 116.27062
[I] Fetched 6 global servers.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's not a crash log.

**Comment by Patryk434** [comment]
> That's not a crash log.

I dont have "crash" folder

**Comment by Anuken** [comment]
Then I can't fix your issue.
