### ISSUE TITLE
Can launch with sandbox blocks

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3263]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 112

**Issue**: *Explain your issue in detail.*
launching a loadout that includes inf sources crashes the game but upon returning to the sector it will have the inf sources around your core.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. have launch schem with inf sources
2. attempt to launch with it
3. game crash
4. go back to where you attempted to launch to
5. item sources now in your campaign map

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

https://drive.google.com/file/d/1RcWkp9fB_anM0vm_3GfFad6-XIx1HlXG/view?usp=sharing

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
no crash report generated

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. I can make a schematic with item/power sources, but it doesn't show up in my launch schematics.
2. Your data doesn't have the schematics or campaign data used, so I can't test this. Saves by themselves are useless.
3. I can't fix a crash without a log.

**Comment by Legomonster33** [comment]
> 1. I can make a schematic with item/power sources, but it doesn't show up in my launch schematics.
> 2. Your data doesn't have the schematics or campaign data used, so I can't test this. Saves by themselves are useless.
> 3. I can't fix a crash without a log.

i uploaded the zip file you get when clicking "export game data" so it should include my schematics and campaign saves (this is also why i used google as it is more than 10mb)

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/98125864-ed416600-1e82-11eb-8113-36538118835e.png)

You literally have a mod that unlocks everything and makes every block visible in sandbox.

**Comment by QmelZ** [comment]
~~yay, anuke called hackustry hack***d***ustry~~
