### ISSUE TITLE
Power node connections dont get saved when launching

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3264]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 112

**Issue**: *Explain your issue in detail.*
when launching with certain core loadouts power nodes that are part of the loadout dont save all/some of their connections

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. launch with this schematic 
![image](https://user-images.githubusercontent.com/54417042/98122399-89b53980-1e7e-11eb-812b-dc027b6820be.png)
2. observe some of the nodes fail to connect the same as they do in the preview image.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://drive.google.com/file/d/1RcWkp9fB_anM0vm_3GfFad6-XIx1HlXG/view?usp=sharing
(this is a game data file from "export game data")

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Even with your exact saves, I can't reproduce this, and honestly with that many mods installed I'm not willing to give your issue the benefit of the doubt.
