### ISSUE TITLE
Routers cannot pass items to overflows if the item just came from there

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3266]
**Platform**: *Tested on Android and PC*

**Build**: *Build 110, also works in 5.0*

**Issue**: *If an overflow passes an item into a router, the router is unable to pass the item back to the overflow. This is in contrast to every other block that supports 2-way transit, such as sorters, routers, and junctions.*

**Steps to reproduce**: *1. Build this: 
![image](https://user-images.githubusercontent.com/70031658/98163283-2e566c00-1ebd-11eb-9352-636b6908b5c3.png)
2. Drop 2 items into the top conveyor (not at the same time).
3. Observe as one goes through (normal router behavior), and the other gets stuck, when it should go back through.
4. Add a second router on the right, and watch as the item goes back.
5. Remove the second router, and replace the overflow with any other block that supports 2 way movement (junction, sorter, etc.), and watch as things work perfectly fine
*

**Link(s) to mod(s) used**: *None*

**Save file**: *[i mean if you really need a save for this.zip](https://github.com/Anuken/Mindustry/files/5490330/i.mean.if.you.really.need.a.save.for.this.zip)*

**Crash report**: *.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
good

**Comment by BlueWolf3682** [comment]
overflows do not have passback and are not meant to allow items to pass back from other blocks. it is why the v5 snek worked.

**Comment by genNAowl** [comment]
Add passback to router-overflow chains and you just forced everyone to use router chains for their duos

Pretty uncool dude.

**Comment by Erisfiregamer1** [comment]
I mean, they deserved it. 
The sneks were too strong to last.
They had to die, one day.
And when v6 came...
Their time had come.
