### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by TheDarkSlasher0013** [Anuken/Mindustry#3270]
**Platform**: *Windows 7 x32*

**Build**: *beta 112.1*

**Issue**: *Game crashed in loading screen.*

**Steps to reproduce**: *Game crashed in loading screen.*

**Link(s) to mod(s) used**: *None.*

**Save file**: *[mindustry_saveFIles.zip](https://github.com/Anuken/Mindustry/files/5492834/mindustry_saveFIles.zip)*

**Crash report**: *[crash-report-11_05_2020_14_18_42.txt](https://github.com/Anuken/Mindustry/files/5492792/crash-report-11_05_2020_14_18_42.txt)
.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your PC doesn't have enough memory.

**Comment by DeltaNedas** [comment]
lol install debian and/or buy more ram
if your cpu is 32 bit maybe its time to stop living in 2003
