### ISSUE TITLE
Meltdowns can set EVERYTHING in front of them on fire

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#3272]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Most likely all of them.
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Bleeding edge. Possibly works in build 112.
**Issue**: *Explain your issue in detail.*
Meltdowns now have the ability to burn things in front of them. This applies to EVERYTHING, even cores.
This opens up worse griefing opportunities than exploding because waves aren't fast enough to stop it. Only tsunamis can stop the fire fast enough, and even then if low build times factor in, the core may be doomed.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Place meltdown by the core.

2, Give power, and water/cryo.

3. Fire at the core. The core will set alight.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
I'm not on the PC with mindustry, so I can't access a save of it.
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
none.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
First of all, maybe this could be a thing IF the meltdown isn't cooled. So you can use them without coolant, but you would have to deal with fire.

**Comment by Anuken** [comment]
update

**Comment by DeltaNedas** [comment]
"bleeding edge" is not a version number
