### ISSUE TITLE
Oh No

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3283]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 112

**Issue**: *Explain your issue in detail.*
crash on launch

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. launch game
2. oh no

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
crash log has a list

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

[crash-report-11_06_2020_20_37_14.txt](https://github.com/Anuken/Mindustry/files/5504120/crash-report-11_06_2020_20_37_14.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this. The error makes no sense, and I suspect mods are part of the cause.

**Comment by BlueWolf3682** [comment]
oh no
