### ISSUE TITLE
Shooting sound echoing

### ISSUE THREAD

**Issue by BonzieC5303** [Anuken/Mindustry#3287]
**Platform**: *Windows 7*

**Build**: *11107*

**Issue**: *So I was messing around the campaign map "Tar Fields". I commanded some Atraxes and shooting randomly because I have no other stuff to do. Shooting too much, I hear some sound effects echo back. I tested it with other units shooting rapidly like Megas, Zeniths, and Spirocts. It seems that it works with other rapid shooting units and blocks.*

**Steps to reproduce**: 
*1. Produce too much sound effects. Can be achieved with rapid shooting units/blocks.
2. Stop shooting.
3. Sound echoes back.
Optional step: Save and Exit to reset sounds*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A, Campaign map*

**Crash report**: *N/A*

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
