### ISSUE TITLE
corebot is out of ink

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3293]
**Platform**: `discord`

**Build**: `?`

**Issue**: `corebot isn't responding to any commands`

**Steps to reproduce**: `try to warn rulebreakers`

**Link(s) to mod(s) used**: `myself`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

> trying to grab @Anuken's attention here since he hasn't visibly been seen on discord for a while*

**Comment by summetdev** [comment]
> Link(s) to mod(s) used: `myself`

*Gonna install `Quezler/Quezler`*

**Comment by Anuken** [comment]
How about now?

**Comment by Quezler** [comment]
corebot stays silent:
<img width="200" alt="Screen Shot 2020-11-08 at 15 24 29" src="https://user-images.githubusercontent.com/3179271/98467588-83a0bf00-21d6-11eb-80bd-6be06eefb654.png">

**Comment by Anuken** [comment]
I think Discord isn't letting me use the old version of the API. It's probably time to update the Discord library I'm using, add support for 6.0 and fix any permission issues related to the upgrade.

**Comment by Anuken** [comment]
Alright, I updated the library and the bot seems to be up. I'll get on Discord tomorrow and fix any possible issues with the commands.

**Comment by MEEPofFaith** [comment]
Core bot responds now, so that's nice.

**Comment by Quezler** [comment]
aaaaand it's dead again

**Comment by Sanya2907** [comment]
F

**Comment by Legomonster33** [comment]
rip corebot 20[number] - 2020

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/98577206-9a541e00-2289-11eb-8d9c-92454e7fab9d.png)

It does this every time I restart.
