### ISSUE TITLE
omniMovement with non-navals

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#3295]
**Platform**: *Android/iOS/Mac/Windows/Linux*
All

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
112

**Issue**: *Explain your issue in detail.*
Non-naval units with omniMovement set to false can't rotate when player controlled, but the AI can still use omnidirectional movement.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Set the omniMovement of flare to false, then try controlling it, then place a rally command center and observe the flare brake without rotating.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
AI are not supposed to follow player movement restrictions.

**Comment by Ilya246** [comment]
But what about the fact that non-navals with omniMovement set to false can't rotate when player controlled?

**Comment by Anuken** [comment]
Don't set it to false if it doesn't work for you. That value is only designed to work with naval units.
