### ISSUE TITLE
Sound bugging on server

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3296]
**Platform**: Windows, and Android

**Build**: 11122

**Issue**: On serpulo testing server, or Surrealment server, sound started scratching like ckckckckck for no apparent reason. It didnt happen just for me, it was for everyone on server. It happened this day before, and now again. There is no such an issue in campaign, or custom maps. 

**Steps to reproduce**: Play on Procedual testing server, or Surrealment and you'll hear it sooner or later. There is no clear reason why it happened, but I assume its bescause many players build conveyors at same time, gliching out sound. After about 2 minutes, it stopped. It happens on Surrealment as well, but I am not sure. It might happen in LAN games, it is still untested.

**Link(s) to mod(s) used**: No mods, but someone on server might have a plugin causing that. Many troling systems exist these days. No same players were present, except for me.

**Save file**: It happens to everyone on the server, two times in a row. It has nothing to do with save files. And I cant literally strap 15 save files to it, for every player on server.

**Additional note:** It fades slightly when paused, like all other sounds. Might have somethning to do with multiple ambient sounds playing at same time.

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not much I can do with this information. I've been on different servers and tested many different sound effects, and it doesn't happen to me. Unless someone figures out a specific cause, this won't be fixed.

**Comment by BorisA11** [comment]
It sometimes just wont happen. I tried 10 times, and only got the bug 2 times.

**Comment by 50275** [comment]
why don't you just record it
if you can reproduce it 20% of the time then just get some footage with trial and error and give both files (recording + save file) to anuke
