### ISSUE TITLE
can't use semicolons in strings with logic

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3297]
**Platform**: Android 9

**Build**: 11106

**Issue**:
; parser doesnt check if its in a string

**Steps to reproduce**:
`print ";"`
->
`Invalid`
`Invalid`

**Save file**: dont think its needed g, logic can be used in f8 so its technically not in-game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'll remove the concept of splitting lines by semicolons. I haven't seen anyone use it anyway.

**Comment by summetdev** [comment]
> I'll remove the concept of splitting lines by semicolons. I haven't seen anyone use it anyway.

So...
```
set foo 1;
set bar 2;
```
...will not work?

**Comment by Anuken** [comment]
No, `set foo 1;set bar 2` won't.

**Comment by DeltaNedas** [comment]
yeah compact assembly into one line isnt really used ever and shouldnt
