### ISSUE TITLE
Game not recognizing my Xbox One controller's axes/buttons 

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#33]
I own an Xbox One controller which I've been itching to use for Mindustry for ages now. Thankfully, there came the new controller update. But even when i select my controller in the options, i still can't do actions with it in the game. When i rebind, it registers the controller axes/buttons as this: 
![image](https://user-images.githubusercontent.com/30189017/34329299-0eb2fa80-e8c9-11e7-84e2-e740c9f5ca0c.png)

If it helps, my controller is connected via wired micro-usb connection to my pc.

**Comment by Anuken** [comment]
Just tested with a normal Xbox controller on Windows, and it doesn't work either. In fact, the only OS with which controllers _do_ work is Linux. This has been a huge mess and a waste of time; I'm just going to disable controller support altogether until I have time to figure out what the deal is.
