### ISSUE TITLE
When Launching you can overfill a core

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3300]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
bleeding edge release 11137

**Issue**: *Explain your issue in detail.*
you can have a core shard with 10k of each resource in it, via launching with lots of resources

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. launch with more resources than the default capacity of a core shard
2. you now have more than 4k of a resource in a core shard.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
happens without mods

![image](https://user-images.githubusercontent.com/54417042/98488511-a2fc1400-21f7-11eb-96c7-b0bffbe5e3d4.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by HaphLife** [comment]
Neat! That shouldn’t be too hard to patch, or very game breaking, but it’s still a neat bug to find.
