### ISSUE TITLE
nani

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3304]
**Platform**: *iOS*

**Build**: *beta 112.3*

**Issue**: *Health/Ammo bar is not displaying any drop when damage is taken.*

**Steps to reproduce**: 
*1. open the game
2. open a new game or load up a save
3. make a unit or use your default core unit
4. take damage
5. profit*

**Link(s) to mod(s) used**: *no*

**Save file**: *no (it happens everywhere for me)*

**Crash report**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported but I do not need to, as no iOS related bugs have been reported recently.**

Edit: video is not supported, but i can send it on discord.

**Comment by GlennFolker** [comment]
get ready for triggered cat to speak here

**Comment by BlueWolf3682** [comment]
(secretly i always do a very quick check of #github to make sure nothings been reported but dont tell anyone)

**Comment by Anuken** [comment]
fixed
