### ISSUE TITLE
Sorters Broken on Multiplayer Campaign

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry#3305]
**Platform**: Android and Windows

**Build**: Beta 112.1

**Issue**: When playing the campaign, host the game. When someone joins, they will be unable to program sorter correctly, as the top row of the UI is not present.

**Steps to reproduce**: Was playing with between 1 and 4 friends on Android and Windows over the past several days and this issue has come up many times while playing the campaign. This issue only happens on the joiners, not the host, and only on campaign maps, not on regular/custom maps. I was able to reproduce it three times in a row by:
1. Start any campaign map.
2. Join with another device.
3. Place sorter.
4. Host can use sorter normally, other players cannot.

**Link(s) to mod(s) used**: No mods used.

**Save file**: I don't know how to navigate the saves folder to find specific saves in the campaign. I tested the issue on Stained Mountains, but it happened frequently during all the campaign maps. Here is my complete saves folder which I think holds the campaign: [saves.zip](https://drive.google.com/file/d/1VO9zvFo8uIxEQaN2qz52qCdocNTAnRbH/view?usp=sharing)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
