### ISSUE TITLE
Spotify music problem when joining serveds

### ISSUE THREAD

**Issue by joesdesignfacility** [Anuken/Mindustry#3306]
**Platform**: Android

**Build**: 112.1 and below

**Issue**: sometimes when joining a server, spotify which I'm listening to in the background closes the moment I join the server.

**Steps to reproduce**: joining some servers with spotify playing in the background and it will randomly close

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Tell them to fix their application, then. I'm not responsible for Spotify randomly closing.

**Comment by potatoisagender** [comment]
lmfao. Completely different application? must be correlated to game, duh

**Comment by DeltaNedas** [comment]
yes https://github.com/Anuken/SpotifyNativeDesktopAppPoweredByElectronKodedWithLuvFrom<WestCoastShithole>

**Comment by joesdesignfacility** [comment]
It happens exactly when I fully join
