### ISSUE TITLE
Title Screen Bug

### ISSUE THREAD

**Issue by Naoko-gg** [Anuken/Mindustry#3308]
Windows 10 64 Bit

6.0 Build 112.1 - Beta

Basically, i wanted to play the new V6 version of the game for its features etc..
When i started the game i went through the loading screen, but then this happens [See Photo]

![bug](https://user-images.githubusercontent.com/74176914/98517869-e3e33f80-226e-11eb-87f3-5bc390d7d190.PNG)

It is also animated and its doing a spiral thing

I downloaded the version from GitHub, firstly i opened the .jar same bug/error, then i replaced the old "desktop.jar" (In the game folder) with the new Mindustry.jar renamed desktop.jar.

I still had my saves from my old campaign so idk.

[saves.zip](https://github.com/Anuken/Mindustry/files/5509055/saves.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Naoko-gg** [comment]
Ok i fixxed this by deleting the old version completly

**Comment by Quezler** [comment]
@Naoko-gg if you say so, you can close this 🙂

**Comment by DeltaNedas** [comment]
bruh thats a mod (deltanedas/hell i recommend v good)

**Comment by Anuken** [comment]
This is the second or third time someone has reported this as a bug.
