### ISSUE TITLE
Turrets don't prioritize cryofluid over water

### ISSUE THREAD

**Issue by adri326** [Anuken/Mindustry#3309]
**Platform**: *Linux*, also noticed on servers

**Build**: *1:6.0_112-1* from the AUR

**Issue**:

Some of the turrets who would get a better boost from cryofluid over water will only accept water should they choose between both.
Turrets will switch over to water if water is ever put at a later stage in them, even if they were still getting cryofluid.
Likewise, turrets will switch over to cryofluid if they are given a new influx of cryofluid.

Moreover, I have seen instances where the turret will simply reject any fluid that is different from what they used to have, even after removing the initial input.
This tends to happen after they make use of the initial fluid type.
On the Meltdown, the droplet indicator will show the new fluid type while the fluid bar remains empty and reads "Liquid".

Quickly breaking and replacing such a turret resets them and they will then happily accept the new fluid type.

The turrets affected by this include:

- Duo
- Scatter
- Lancer
- Arc
- Salvo
- Swarmer
- Fuse 
- Ripple
- Cyclone
- Spectre
- Meltdown

Following is a screenshot of a Meltdown in the "glitched" state where it will reject any water input after it received and used cryofluid:

![Screenshot of a meltdown in such a glitched state.](https://user-images.githubusercontent.com/18118053/98526002-87395200-2279-11eb-9965-7897aa9bbd9b.png)

Following is a screenshot of a Cyclone that has prioritized water over cryofluid:

![Screenshot_2020-11-09_11-29-40](https://user-images.githubusercontent.com/18118053/98530327-0b420880-227f-11eb-86e6-1dba5ab55a00.png)

**Steps to reproduce**:

I noticed this issue on a server, where I was placing a turret next to my cryofluid blueprint and it was receiving both cryofluid and water but chose water over cryofluid. Doing anything but removing the water input and replacing the turret didn't fix it.

Here are the different scenarios:

- Place the turret down, then give it cryofluid and then water
- Place the turret down next to a cryofluid and a water source
- Place the turret down, give it water and then cryofluid; start shooting with the turret, then remove the cryofluid input. The turret now won't accept the water.

**Link(s) to mod(s) used**: None

**Save file**: 

[fluid-priority-bug.zip](https://github.com/Anuken/Mindustry/files/5509721/fluid-priority-bug.zip)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Turrets can only receive one fluid at a time, there is no "prioritizing". If you put in water, they will only accept more water until the water runs out.
