### ISSUE TITLE
Megas attacking enemy while command center is set to rally

### ISSUE THREAD

**Issue by YellOw139** [Anuken/Mindustry#3310]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: BE 11141

**Issue**: Megas are attacking enemy structures while the closest command center is set to rally.

**Steps to reproduce**: 
AKA how to get megas triggered.
1. Have the command center closest to a mega set to rally.
2. Build/have few megas.
3. Build an allied block in range of enemy turrets. Build it close enough to some enemy blocks so that enemy blocks are within mega's range. Just build it really close to the enemy base.
4. The allied block gets damaged, which means the megas step in and shoot to repair it.
5. Once the allied block's health is back at 100%, there's nothing else for megas to repair.
6. Megas start attacking enemy blocks, which makes sense. Keep the allied block defended at all costs.
7. Repeat 4-6 for a while. They are useful behaviors and seem to be intended.
8. Once the allied block is at 100% health and nothing is attacking it anymore, megas keep attacking stuff around them. Which contradicts with the command centers and makes no sense. They are not made for attack. They are meant to defend your base and they don't attack by default unless the enemy is in one mega's range. The player should be able to get them to retreat whenever he wants (to deliberately save them from getting killed).

I know they don't gather around rally points by default, I can see where that comes from, but at least give them a place to retreat. Repair points? The core? Nearby friendly turrets? Heck, even the nearest rally point works and makes most sense, provided they only retreat after they've finished repairing everything and attacking all the enemies which are damaging blocks and then after retreat they stay alert for new blocks that get damaged.

**Link(s) to mod(s) used**: None

**Save file**: 
[Attack_Megas.zip](https://github.com/Anuken/Mindustry/files/5509767/Attack_Megas.zip)

![image](https://user-images.githubusercontent.com/70975516/98538465-7695d580-2293-11eb-813f-b2971c506b44.png)

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
As you said, megas are not supposed to follow command centers. They're not standard attack units, and they're not supposed to move anywhere when they're idle. This isn't a bug.

**Comment by YellOw139** [comment]
> Yes, they _could_ fly back to a rally command center every time they're idle, but that seems very annoying and worse than the alternatives. Megas would waste a lot of time flying back and forth between command centers and damaged blocks for no good reason.

@Anuken They would waste less time if they went to the nearest friendly block, and it would be less annoying having them waste time rather than having them get killed. I will open a suggestion.
