### ISSUE TITLE
Sound bug (update)

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3311]
**Platform**: Windows

**Build**: 11122-11141, in 11144 it is fixed. 
**Issue**: Sound just starts randomly clicking. It happened on servers, and it was already reported. It has something to do with ambient, if i set ambient to 0% it will stop. On the given save file, it is on 20%. I was sorounded by miner drones at the time. There were tons of conveyors as well. It happened 3 times in a row, at the sector that is already selected. 

**Steps to reproduce**: It has something to do with ambient sound. It may not happen every time, but I got it 3 times in a row first time. After a reload, it stopped. After I reloaded it again, it started clicking harder, and it was beeping as well. I tried reinstalling the file, but nothing happens. 

**Note:** You might have to reload it multiple times to get it right. My speaker is just fine, it happened to other people as well. Its a quite inconsistent bug, but very annoying.

**Link(s) to mod(s) used**: Nope

**Save file**:
[Sound bug file.zip](https://github.com/Anuken/Mindustry/files/5510046/Sound.bug.file.zip)

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
*Well I did report it once before, but I had less data then*

**Comment by Luxray5474** [comment]
Same with me, I use Debian Linux and it clicks after each "placing" sound, and if enough are played at the same time it starts clicking very loudly. (Build 11141)

https://www.youtube.com/watch?v=ldoAVWg83n8

**Comment by BorisA11** [comment]
I'll try.

**Comment by Luxray5474** [comment]
I installed the mod and ran said commands. Here is footage of the result:

https://www.youtube.com/watch?v=PtRSdrJwKA8

**Comment by Anuken** [comment]
Alright, so it appears that the conveyor loop is the problem (*or, at least, one of the causes*), and it's an issue that **doesn't** occur on my machine.

@Luxray5474 See if the same clicking occurs with other sounds, like `Sounds.smelter` or `Sounds.shoot`. Does the clicking begin when you play/loop them?

**Comment by Luxray5474** [comment]
I have heard the (various) shooting sounds produce the same clicking at the end of the sound. Footage:

https://youtu.be/u63nVhG5y9c

**Comment by Anuken** [comment]
Tested on my phone, and the conveyor sound doesn't click there either. I can't reproduce this at all.

**Comment by Erisfiregamer1** [comment]
It happenes with tsumanis and waves too.

**Comment by BorisA11** [comment]
> It happenes with tsumanis and waves too.

Yep. I've seen it before, but I tought it was fixed

**Comment by BorisA11** [comment]
@Anuken , It happens, both with loop and standard conveyor sound. It does not beep or scratch on other loops, as weather, tractorbeam, shield, or laser. It's probably due to all conveyors making sound, not just amplifiying intensity of one. So it might not work on your machine since it doesnt lag, as lag probably sets apart the sound starts, leading to 100 sounds being played with minimum delay. Thats why on servers its even stronger, due to lag. I hope this gets fixed soon, as new SFX are great and its a shame to hear ckckck all the time

**Comment by BorisA11** [comment]
As I move further from conveyors, sound fades. This means it definetly has something to do with conveyor spam.

I started a custom game, sandbox. I put 3 conveyors. Nothing. 4, 5, 6, minor clicking. As I started making rows of them, it was even stronger. Filling the map results in super powerful clicking. So yeah, its probably as I said before

**Comment by BorisA11** [comment]
It gets amplified when they point different way as well.

**Comment by Anuken** [comment]
> It's probably due to all conveyors making sound, not just amplifiying intensity of one. So it might not work on your machine since it doesnt lag, as lag probably sets apart the sound starts, leading to 100 sounds being played with minimum delay.

No, this can't be the case. I can play *10,000* conveyor loops on my (weak) phone every time I tap, and there isn't any clicking of other sounds. Furthermore, the way conveyors play sound shouldn't allow for multiple loops to play at once, and I think it would be quite obvious if that happened (*as you would hear overlapping conveyor sounds*).

As @Luxray5474 demonstrated in the video, the issue can happen even when ambient sounds are completely absent. There's something wrong with the sound itself.

**Comment by Luxray5474** [comment]
Maybe this is an issue specifically with OpenJDK?

**Comment by Anuken** [comment]
Unlikely. The sound library is C++, not Java, and I'm using OpenJDK on my machine.

@BorisA11 Have you tried running the very latest BE? Does the problem still occur with the new conveyor sound?

**Comment by Luxray5474** [comment]
Okay I tested it out and it seems like PulseEffects is exaggerating the issue. I thought it was what was causing the issue when I was recording it but I look back and hear that it was still clicking without PulseEffects on. Footage (on Streamable now because YT takes way too long to upload) https://streamable.com/zry13i

**Comment by Luxray5474** [comment]
Additional test with PulseEffects on (no effects activated) https://streamable.com/gdm0zr

There is no more consistent loud clicking but there are some audio clipping issues.

**Comment by Anuken** [comment]
Some things I could do:

- Change the format from *ogg* to *mp3* (which is better supported, actually, and gives me a slightly smaller file size)
- Mess around with library settings, like sample rates
- Switch Soloud audio backends (*although this issue occurs across multiple backends so I'm not sure if it's a good idea*)

**Comment by BorisA11** [comment]
I haven't yet tried latest version, updating now. I'll report if it continues.

**Comment by BorisA11** [comment]
@Anuken , Its now fine. No clicking, or beeping. Maybe I just got lucky, but I think its fixed.

**Comment by BorisA11** [comment]
I tried the mod console, nothing, it works fine. I even loaded 3 over each other, and it worked just fine.

**Comment by BorisA11** [comment]
So yeah, I assume this is fixed. If it continues, I'll report

**Comment by Anuken** [comment]
Nice. I'll keep this issue open until @Luxray5474's problem is resolved. I highly suspect that OGG decoding is the problem here, as I've seen other libraries have issues with it before.

**Comment by Luxray5474** [comment]
My problem is *mostly* fixed; right now it's just a matter of slight clicking at the starts/ends of audio bits.

**Comment by Anuken** [comment]
@Luxray5474 Compile the very latest commit and see if using mp3 fixes the problem.

**Comment by Luxray5474** [comment]
We're chugging along at 4mbps, already 1 GB in. slowly ever so slowly

**Comment by Anuken** [comment]
Why not use `--depth 1`?

**Comment by Luxray5474** [comment]
Already running. It works perfectly. 👍🏽 Thank you!

**Comment by Anuken** [comment]
Now we know: ogg is terrible. *At least, where decoding is concerned.*

**Comment by Anuken** [comment]
I don't know nobody could have noticed this before, but with mp3 files used instead of OGGs, the loops are completely broken. Instead of clicking, there's now silence on both ends of the track, which means seamless loops are impossible. [This cannot be fixed.](https://sound.stackexchange.com/questions/25846/is-it-possible-to-loop-mp3-without-gaps)

I'm switching back to OGG.

**Comment by Luxray5474** [comment]
oof. Hopefully you find a better decoder that doesn't make clicking noises.

**Comment by Anuken** [comment]
Unlikely. The issue is with your system, not the decoder - none of my devices click with OGG, and neither does Boris' setup.

**Comment by atkka** [comment]
Hello, my friend and I are having these issues on our Linux boxes with the latest versions:

**Platform**: Linux, Kubuntu 20.04 - 5.4.0-54

**Build**: 114/114.1.

**Issue**: Distorted audio as soon as the game is launched. Sounds very bitcrushed, some static and pops as well, both the music and sound effects, both in the menu and in-game. Some sound effects in-game appear to be missing, no hover sound when flying around among others.

**Steps to reproduce**: Run either of the above versions and the audio is this way. 104.10 sounds fine.

**Comment by Anuken** [comment]
Someone else had this, and it appear to be a PulseAudio configuration bug. As this (still) doesn't happen on my machine, it's very unlikely to be fixed.

**Comment by atkka** [comment]
Ok, I just tested with the Kubuntu 20.10 Live ISO and Mindustry 114.1 and the distortions are gone.

Are there some sounds not implemented in the beta yet?

**Comment by OneToThreeCreator** [comment]
I have the same problem with audio (some weird clicks in sound), but on later versions (probably mp3 does not solve the problem). But some rituals about the game (like converting pre-cached menu sound from mp3 to ogg vorbis (and not converting anything else), entering the campaign/returning to title screen, running game directly by java -jar (I'm installed a package with shell script for mindustry running), setting music volume to 1% sound volume to 10% ambient volume to 10% and revert; fixed the problem. I'm not understand what I did (because all my attempts was different, I tried about 3 times), **but problem looks like have several solutions**.

**Platform**: Arch Linux

**Build**: latest available (The package says r9076.962d0729d, installed mindustry-git from AUR). Problem appears also on build 119, build 118, and even in steam build. Also tried wine version (steam build) - music not playing, but sounds are fine.

**Steps to reproduce**: Sadly, I don't know. Just do something weird with game until sound fix. 
This problem could appear after a system update! (I'm not had this problem before). Probably, another update will completely fix this (or do this worse, I don't know).
Reinstalling the game returns the problem (sometimes).

**Comment by OneToThreeCreator** [comment]
After reboot problem returns, but now I probably found the solution.
Enter a campaign, then on any map.
Exit to title screen.
Restart game.
Set music to 1%, sound and ambient volume to 10% (you can increase volume by your speakers to hear anything)
Enter a campaign, then on any map.
Exit to title screen.
Set sound to percent when you not hearing this weird clicks, but hear sound (for me it was 4%), music and ambient volume to 0%
Restart game.
Problem fixed (at least for me, with my converted menuXXXXX.mp3 to .ogg and symlinked, and yes, I hear music).
Maybe, some of the steps are not required for fixing, I don't know. This fix anyway may not work again (It will be removed if so).
