### ISSUE TITLE
Error running java

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#3312]
Ok, so. 
I was playing mindustry, and accidentaly opened 2 tabs.
When I tried to close the other, Java threw an error.
I could not screenshot it, but I did manage to get a log.
Here it is:
[hs_err_pid5448.log](https://github.com/Anuken/Mindustry/files/5511737/hs_err_pid5448.log)
Anything that could fix whatever happened in there?
This was on Bleeding edge, 11141

**Comment by Anuken** [comment]
1. Use the template.
2. I can't fix that.
