### ISSUE TITLE
Unable to compile.

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#3313]
**Platform**: Windows 10; OpenJDK version "14.0.2".

**Build**:  112.1.

**Issue**: Executing `desktop:dist` fails with error "use --enable-preview to enable pattern matching in instanceof".

**Steps to reproduce**:
1. Run `desktop:dist` task.
2. See the crash log.

**Link(s) to mod(s) used**: None.

**Save file**: Not need.

**Crash report**:
```
> Task :desktop:compileJava
mindustry\desktop\steam\SStats.java:108: warning: as of release 10, 'var' is a restricted type name and cannot be used for type declarations or as the element type of an array
                        for(var v : sec.info.production.values()){
                                ^
D:\Mindustry\desktop\src\mindustry\desktop\steam\SStats.java:184: error: pattern matching in instanceof is a preview feature and is disabled by default.
            if(e.unit instanceof BlockUnitc block && block.tile().block == Blocks.router){
                                            ^
  (use --enable-preview to enable pattern matching in instanceof)
1 error
1 warning
```

---
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

~~P.S: Please don't tell me "Works for me."~~

**Comment by Anuken** [comment]
> P.S: Please don't tell me "Works for me."

Well...

![image](https://user-images.githubusercontent.com/10100000/98576227-439a1480-2288-11eb-9ced-885f3206edf1.png)

**Comment by summetdev** [comment]
Uh, what could be causing my problem?

**Comment by Anuken** [comment]
I don't know, the gradle file looks fine to me. I'm running `14.0.1` instead of `14.0.2`, however.

**Comment by summetdev** [comment]
Solved: I've deleted Gradle's cache (`.gradle`) and it worked.
