### ISSUE TITLE
Corebot = Rip

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3314]
**Platform**: *Android/iOS/Mac/Windows/Linux* discord

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
"latest"

**Issue**: *Explain your issue in detail.*
corebot = rip

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. try to use corebot
2. no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
it has been reported but it was closed.

**Comment by rmperkow** [comment]
[#3293](https://github.com/Anuken/Mindustry/issues/3293#issue-738470254)

**Comment by Anuken** [comment]
yes I know
