### ISSUE TITLE
mindustry ignores trackpoint middle click

### ISSUE THREAD

**Issue by l29ah** [Anuken/Mindustry#3318]
**Platform**: Xorg on Linux

**Build**: 112.1

**Issue**: When i press the middle mouse button on an USB mouse, i can copy the building under cursor. When i click it on a trackpoint, nothing happens, even though in other apps it works just the same. `xev` says `button 2` when i click it so it should be just the same behavior. Compare it for left and middle clicks:
```
ButtonPress event, serial 34, synthetic NO, window 0x7800001,
    root 0x1c2, subw 0x0, time 325746740, (590,29), root:(591,630),
    state 0x0, button 1, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x7800001,
    root 0x1c2, subw 0x0, time 325746840, (590,29), root:(591,630),
    state 0x100, button 1, same_screen YES

ButtonPress event, serial 34, synthetic NO, window 0x7800001,
    root 0x1c2, subw 0x0, time 325747395, (590,29), root:(591,630),
    state 0x0, button 2, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x7800001,
    root 0x1c2, subw 0x0, time 325747395, (590,29), root:(591,630),
    state 0x200, button 2, same_screen YES
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
If you want a fix, find out what's wrong in the [input code](https://github.com/Anuken/Arc/blob/master/backends/backend-sdl/src/main/java/arc/backend/sdl/SdlInput.java#L41) and submit a PR. I don't have your hardware.
