### ISSUE TITLE
launch requirements have no item icons

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3322]
**Platform**: Android 9

**Build**: 11141

**Issue**:
![Screenshot_20201110-081348_Mindustry BE](https://user-images.githubusercontent.com/39013340/98649181-33894000-232f-11eb-80c7-2a16e6254822.jpg)

**Steps to reproduce**:
1. launch core
2. look at requirements

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen on my phone or PC, won't fix.
