### ISSUE TITLE
Upon Further Review I Have come to the conclusion that #3220 should be locked until you unlock launchpads

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3324]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 112

**Issue**: *Explain your issue in detail.*
you can launch to any sector without penalty to find a perfect farming location, before you have launchpads, which is kind of op and eliminates the need to properly explore prior to getting launchpad.
"universal launching" should be locked behind either, launchpads or, higher tier cores. possibly both.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. start fresh save
2. capture ground zero
3. find a good farming sector
4. research everything
5. you just were bored because you didn't have to play the game the way it was meant to be enjoyed.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
uwu.png

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
nah its ok

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
well sort of

**Comment by DeltaNedas** [comment]
new issue -> suggestion

**Comment by Anuken** [comment]
How is this a bug?
