### ISSUE TITLE
Sector 174 exits my mindustry

### ISSUE THREAD

**Issue by DatOnePlayer** [Anuken/Mindustry#3325]
Android

V6 112.1

So I was messing around with Ground Zero and moving to the next one to collect my resource and update the building (next sector is 174, lower right of Ground Zero) and when it loads it just froze and immediately exit by itself

I don't know what happened I just haven't check that map for a long time, and it just like that

The mods are doing just fine in other sectors
But here it is : 

- Braindustry by Pixaxeofpixie

- Gold Mod by TheSlaylord

- Larger cores by z0mbiesrock

- Heavy Armaments industries by Eschatalounge (if I spell that correctly)

- Vanilla enhanced by HolyHades

- Progressed Materials by MeepOfFaith

[crash_1604997526477.txt](https://github.com/Anuken/Mindustry/files/5516002/crash_1604997526477.txt)

**save file too big** *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS  OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's not a valid crash report.
