### ISSUE TITLE
Save File Mixing

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3327]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 112

**Issue**: *Explain your issue in detail.*
when wiping the campaign research and saves data, following some steps can cause your new fresh save to mix into your old save that has more progress

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. have capped a large amount of sectors (https://drive.google.com/file/d/13qM_gAwEU5_zkZ2f-T_gL4MExucKb-_P/view?usp=sharing)
2. export game data (note that this may be unrellated)
3. use both of these buttons 
![image](https://user-images.githubusercontent.com/54417042/98696183-7b18c780-2341-11eb-8760-e3f8910e250a.png)
4. start fresh
5. capture a sector or two
6. save and exit
6. load back in to find an odd mix of both you old and new saves.(https://drive.google.com/file/d/12e2PlcXfBf8OfIKJ7JdQfhI3M9ydleuP/view?usp=sharing)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
happens without mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
save files included above.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed, probably
