### ISSUE TITLE
music still playing after exit

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3328]
**Platform**: Android 9

**Build**: 11159

**Issue**:
Music still playing for a few minutes after pressing exit.
Activity is not in recents, not sure why audio thread still alive.

**Steps to reproduce**:
1. play new spooky music
2. exit
3. spooky music still playing O.o

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
probably fixed

**Comment by DeltaNedas** [comment]
probably

**Comment by DeltaNedas** [comment]
@Anuken still occurs in 103 for me, xusk, ilya (pc) and the other guy who reported

**Comment by Anuken** [comment]
~~works on my machine~~

**Comment by DeltaNedas** [comment]
1 vs 4

**Comment by DeltaNedas** [comment]
is your phone on android 9

**Comment by Anuken** [comment]
no

**Comment by DeltaNedas** [comment]
epic

**Comment by DeltaNedas** [comment]
please reopen, you cant just `apt install android=4.4` and sidestep the bug.
it has not been fixed.
