### ISSUE TITLE
cant compile with debian sid jdk

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3329]
**Platform**: Debian Sid

**Build**: DeltaNedas:files
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Debian-1.1)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Debian-1.1, mixed mode, sharing)
```

**Issue**:
Silly gradle decides to do a thread dump and exit when i try to compile mindustry.

**Steps to reproduce**:
1. `apt install openjdk-14-jdk-headless`
2. `./gradlew core:build --no-daemon > rabbit.log`
3. gradle kills itself after a minute
4. no mention of why the thread dump was created very yes

**"Crash" report**: 
[rabbit.log](https://github.com/Anuken/Mindustry/files/5519292/rabbit.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix Gradle killing itself. There isn't anything meaningful in the report aside from the thread dump, which I can't reasonably look through.

**Comment by DeltaNedas** [comment]
yes thats the problem, if gradle gave me a shred of information itd help

**Comment by Anuken** [comment]
Nobody else has this problem. It's likely something wrong with your java version (use 15?) or cache.

**Comment by DeltaNedas** [comment]
deleted ~/.gradle and `apt install openjdk-15-jdk-headless`'ed, nothing new.
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-Debian-3)
OpenJDK 64-Bit Server VM (build 15.0.1+9-Debian-3, mixed mode, sharing)

**Comment by Shawak** [comment]
Works for me:
docker-compose.yml
```yaml
version: "3.7"

services:
  sid:
    image: debian:sid
    tty: true
```

Output:
```bash
apt update
apt install -y git openjdk-14-jdk-headless
git clone https://github.com/Anuken/Mindustry.git
cd Mindustry
./gradlew core:build --no-daemon
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
No Android SDK found. Skipping Android module.

> Configure project :
Compiling with build: 'custom build'

> Task :annotations:clearCache
> Task :annotations:compileJava UP-TO-DATE
> Task :annotations:processResources UP-TO-DATE
> Task :annotations:classes UP-TO-DATE
> Task :annotations:jar UP-TO-DATE
> Task :core:clearCache
> Task :core:preGen UP-TO-DATE
> Task :core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :core:processResources NO-SOURCE
> Task :core:classes
> Task :core:jar
> Task :core:assemble
> Task :core:compileTestJava NO-SOURCE
> Task :core:processTestResources NO-SOURCE
> Task :core:testClasses UP-TO-DATE
> Task :core:test NO-SOURCE
> Task :core:check UP-TO-DATE
> Task :core:build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 33s
7 actionable tasks: 4 executed, 3 up-to-date
```

**Comment by DeltaNedas** [comment]
h
