### ISSUE TITLE
Mindustry not properly starting

### ISSUE THREAD

**Issue by NotACliche** [Anuken/Mindustry#3330]
Mindustry does not seem to start up correctly. It shows up as the basic starting screen, but then nothing happens. Images below depict stable and beta versions, and 64 and 33 bit are the same. 
![uuZJb_](https://user-images.githubusercontent.com/67478786/98712732-81a44080-233b-11eb-97be-f8473a744e68.png)
![BigtGi](https://user-images.githubusercontent.com/67478786/98712733-823cd700-233b-11eb-992b-2562c2ac93bf.png)

**Comment by Anuken** [comment]
No template, no log, no data.

**Comment by DeltaNedas** [comment]
33 bit yes
the good ol 8387

**Comment by NotACliche** [comment]
Anuken, what do you mean by no template, no log, no data???

**Comment by Anuken** [comment]
You have not posted your game version (no, *latest* is not a version), your OS, or any logs. If there *are* no logs, I can do nothing.
