### ISSUE TITLE
Can’t interact with modded blocks in 6.0

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry#3331]
**Platform**: iOS 

**Build**: 112 (probably any)

**Issue**: Can’t interact with any modded blocks.

**Steps to reproduce**: I downloaded some mods, tried to use a block from it, but Mindustry won’t even count it as a block and will not show its hp, also you can’t use the block and can’t delete it 

**Link(s) to mod(s) used**: Coppermod (any mod that adds blocks)

**Save file**: 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5519540/mindustry-data-export.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
This is an issue with mods with invalid blocks, it causes the game to slightly break.

**Comment by Sanya2907** [comment]
Sorry for not giving the link on the coppermod: https://github.com/SnakkiZXZ/coppermod-BE

**Comment by Sanya2907** [comment]
> This is an issue with mods with invalid blocks, it causes the game to slightly break.

Hm, maybe. But why does it happen on all mods instead of coppermod only?

**Comment by BlueWolf3682** [comment]
i dont have enough ram to run a mod .-.

**Comment by Anuken** [comment]
> Can’t interact with any modded blocks.

This is false. On iOS, I *can* interact with some blocks, but only those that are properly implemented. Most of the blocks in that mod are not.

**Comment by BlueWolf3682** [comment]
so after waiting a few minutes to reinstall mindustry (crash loop due to an unrelated bug with loading mods

**Comment by DeltaNedas** [comment]
also anything with scripts wont work because theyre not supported on ios
simple solution
1. use good platform
2. use good mods (like routorio)
