### ISSUE TITLE
Frozen forest keeps getting attacked with 0 waves

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3336]
**Platform**: *Windows*

**Build**: *110*

**Issue**: Any time frozen forest gets attacked, it gets captured immediately. The same happens for Fungal Pass. I originally wasn't going to report this, but apparently someone else on reddit is also getting this bug.

**Steps to reproduce**: *1. Load the save
2. Wait for Frozen Forest or Fungal Pass to get attacked
3. Switch to the sector to find it instantly recaptured*

**Save file**: *
[Save Data.zip](https://github.com/Anuken/Mindustry/files/5520634/Save.Data.zip)

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
i had this with other sectors, no idea how to reproduce
then it didnt happen one day and i had a base with router chains (no turrets, just routers) as a defense holding off against wave ~218

**Comment by Anuken** [comment]
Update your game, 110 is a very old version. Many changes have been made since then.
