### ISSUE TITLE
Frozen forest keeps getting attacked with 0 waves

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3337]
**Platform**: *Windows*

**Build**: *112.1*

**Issue**: Any time frozen forest gets attacked, it gets captured immediately. The same happens for Fungal Pass. I originally wasn't going to report this, but apparently someone else on reddit is also getting this bug.

**Steps to reproduce**: *1. Load the save
2. Wait for Frozen Forest or Fungal Pass to get attacked
3. Switch to the sector to find it instantly recaptured*

**Save file**: *
[Save Data.zip](https://github.com/Anuken/Mindustry/files/5520634/Save.Data.zip)

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
lol

**Comment by potatoisagender** [comment]
you... you literally copy pasted your previous issue...

**Comment by Esnardo** [comment]
> you... you literally copy pasted your previous issue...

Look at the reason the last one got closed and you'll get the joke

**Comment by Bohaska** [comment]
This time, the issue happens on version 112.

**Comment by DeltaNedas** [comment]
i havent had that happen in a while

**Comment by Anuken** [comment]
Duplicate, this was already fixed.
