### ISSUE TITLE
When starting Mindustry, I always have the tutorial shown

### ISSUE THREAD

**Issue by Riduidel** [Anuken/Mindustry#3338]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Platform : Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Build: Strangely enough, I never have the build number shown as I always get the tutorial started.
The `MANIFEST.MF` file doesn't contains the version

Hopefully, I've found at project root a `version.properties` file which contains a version string:

```
#Thu Apr 02 10:45:54 EDT 2020
modifier=release
androidBuildCode=29644
type=official
number=5
build=104.10
```

**Issue**: *Explain your issue in detail.*

Each time I start the mindustry, even if I have completed the tutorial, the tutorial screen shows up and I have to achieve the tutorial to start playing.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Nothing particular to do, as bug is systematic.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mod was used.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Doesn't happen in game

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Maybe the problem was already reported, I don't know, i've searched issues with "windows save", but didn't found anything meaningful. Please don't hesitate to close that issue if bug is in fact a known feature.

**Comment by Anuken** [comment]
6.0 doesn't have a tutorial, this isn't relevant.

**Comment by Riduidel** [comment]
@Anuken I don't understand, i've downloaded it fresh from itch.io STABLE channel. So it's an old 5 version ?

**Comment by Legomonster33** [comment]
> @Anuken I don't understand, i've downloaded it fresh from itch.io STABLE channel. So it's an old 5 version ?

the current version that is being worked on is 6.0.
v5 is just the latest stable release.

**Comment by Legomonster33** [comment]
> > @Anuken I don't understand, i've downloaded it fresh from itch.io STABLE channel. So it's an old 5 version ?
> 
> the current version that is being worked on is 6.0.
> v5 is just the latest stable release.
@Riduidel
