### ISSUE TITLE
Player Controlled unit slow down when not moving forwards, commanded / logic controlled units do not

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3340]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 112
(has been a thing for a while now)

**Issue**: *Explain your issue in detail.*
whilst controlling a unit you will be slowed down when not moving directly forward, but other means of controlling units do not see this same downfall.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. control unit (works in core mech too)
2. shoot so you don't move directly forward
3. your now slower than if you had logic/commanding to do this

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
happens without mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
nah

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
nop
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
intentional

**Comment by Legomonster33** [comment]
> intentional

but its annoying and pointless??

**Comment by Anuken** [comment]
It makes kiting harder, feels better and makes sense.

**Comment by Legomonster33** [comment]
> It makes kiting harder, feels better and makes sense.

if anything it makes kiting easier because they slow down when not shooting the same way thier moving. allowing you more time to spam blocks for them to chew on.

**Comment by Anuken** [comment]
What does spamming blocks have to do with kiting?

> because they slow down when not shooting the same way thier moving

Yes, and that's exactly what you do when you kite. You aren't able to easily attack the enemy and move away at the same time.

**Comment by Legomonster33** [comment]
> What does spamming blocks have to do with kiting?

when kiting an antumbra, they have a tendency to stay an amount of distance away from the thing their attacking, so you can spam blocks to have them go where you want, kind of like herding sheep.

**Comment by Anuken** [comment]
And how is that remotely relevant to this issue?

**Comment by Legomonster33** [comment]
> And how is that remotely relevant to this issue?

idk you brought up kiting

**Comment by Legomonster33** [comment]
> Yes, and that's exactly what you do when you kite. You aren't able to easily attack the enemy and move away at the same time.

units can still move and attack separately its just exclusive to logic controlling.

**Comment by Anuken** [comment]
> idk you brought up kiting

If you want to kite as a flying unit, you must be (1) moving away from the enemy and (2) dealing damage to it. This has **nothing** to do with building. *When you can't move backwards effectively, you can't kite as easily.*

> units can still move and attack separately its just exclusive to logic controlling.

I don't care about this, because AI and logic usually isn't smart enough to take advantage of it. Players *are*.
