### ISSUE TITLE
Certain units with opposable weapons face what their shooting even if they have no reason to.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3341]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 112

**Issue**: *Explain your issue in detail.*
certain units, notably the zenith, rotate the body of the craft to shoot their fully opposable weapons. helping to slow you down #3340

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. control zenith
2. shoot
3. you rotate?

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
nop

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
nah im lazy

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
nop

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.

**Comment by Legomonster33** [comment]
> Intentional.

with #3340  it just makes controlling certain units have pointless downsides. and makes using them effectively annoying.

**Comment by Anuken** [comment]
I don't agree.
