### ISSUE TITLE
Music playing

### ISSUE THREAD

**Issue by dragonMau** [Anuken/Mindustry#3346]
**Platform**: *Android 9*

**Build**: *beta build 113*

**Issue**: *Is this mindustry's bug, or android 9's?
That music from mindastry play when im writing to discord?*

**Steps to reproduce**: *Start mindustry and go to another program.*

**Link(s) to mod(s) used**: *Nothing.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
1. already reported
2. also occurs when the activity has been finishAndRemoveTask'ed i suspect messy thread stuff

**Comment by Anuken** [comment]
Known, could be fixed.
