### ISSUE TITLE
All music does not play

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#3348]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
113

**Issue**: *Explain your issue in detail.*
No music, not even menu music plays - even after checking all settings, then unpacking and launching the game from a new folder. Clearing game data didn't help either. All other sounds play.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Updating to b113 - seems like the issue does not happen for other players.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Post your logs.

**Comment by Ilya246** [comment]
[last_log.txt](https://github.com/Anuken/Mindustry/files/5526337/last_log.txt)

**Comment by Ilya246** [comment]
music files exist in mindustryfolder/cache, one such file is game9__3601368.mp3

**Comment by Anuken** [comment]
Try running the latest commit, reopen if not fixed.

**Comment by Ilya246** [comment]
Tried compiling the latest commit - music worked
