### ISSUE TITLE
Processor: "power related" options for sensor block code don't work

### ISSUE THREAD

**Issue by ThatTwisteesGuy** [Anuken/Mindustry#3349]
**Platform**: *Windows*

**Build**: *112.1*

**Issue**: *Power related sensor options such as PowerCapacity etc. don't seem to work.*

**Steps to reproduce**: *I used a micro processor and connected said micro processor to a Message and a Thorium Reactor, I set a sensor block code to "text = @ powerCapacity in reactor1" then I simply printed the variable text and flushed it into message1 by doing "Print text" and "Print Flush to message1" the result is 0 when it should be 900. Other power related sensor options such as TotalPower also didn't work with similar methods and are consistently and easily reproduced, I then used "powerNetIn" to check the outputted power of the thorium reactor as all the other options simply returned a 0*

**Link(s) to mod(s) used**: *No Mods*

**Save file**: *File of save with described demo attached: 
[Bug.zip](https://github.com/Anuken/Mindustry/files/5526290/Bug.zip)*

**Crash report**: *No Crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
They useThisCase, NotThisCase.
post the exported code.

**Comment by ThatTwisteesGuy** [comment]
> They useThisCase, NotThisCase.
> post the exported code.

sensor text reactor1 @powerCapacity
print text
printflush message1

**Comment by Anuken** [comment]
Reactors don't store power, and your reactor isn't outputting any power.

**Comment by Esnardo** [comment]
Power capacity is for batteries.

**Comment by ThatTwisteesGuy** [comment]
> Power capacity is for batteries.

that's my bad.. I thought it was also intended to be used for generators and reactors.

**Comment by ThatTwisteesGuy** [comment]
> Reactors don't store power, and your reactor isn't outputting any power.

since this wasn't their intended use, may I put is up as a separate suggestion?
