### ISSUE TITLE
desktop:run SUCCESSFUL fail on RPi (32bit Linux)

### ISSUE THREAD

**Issue by paulwratt** [Anuken/Mindustry#3356]
**Platform**: *Linux*

**Build**: *repository - Nov  7 15:35 *

**Issue**: *last block/function in build.gradle is missing desktop:packrLinux32 - is this related?*
`arc.util.ArcRuntimeException: Couldn't load shared library 'libarcarm.so' for target: Linux, 32-bit`

**Steps to reproduce**: *Install AdoptOpenJDK from their repo, under Linux RPM/DEB instructions (see link), then use desktop:run option (see 1st line below)*
https://adoptopenjdk.net/installation.html

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

```
pi@raspberrypi:~/Desktop/Apps/Mindustry $ ./gradlew desktop:run
Downloading https://services.gradle.org/distributions/gradle-6.6-bin.zip
.................................................................................................

Welcome to Gradle 6.6!

Here are the highlights of this release:
 - Experimental build configuration caching
 - Built-in conventions for handling credentials
 - Java compilation supports --release flag

For more details see https://docs.gradle.org/6.6/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
No Android SDK found. Skipping Android module.

> Configure project :
Compiling with build: 'custom build'

> Task :annotations:compileJava
> Task :annotations:processResources
> Task :annotations:classes
> Task :annotations:jar
> Task :core:preGen UP-TO-DATE
> Task :core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :core:processResources NO-SOURCE
> Task :core:classes
> Task :core:jar
> Task :desktop:compileJava
> Task :desktop:processResources NO-SOURCE
> Task :desktop:classes

> Task :desktop:run
arc.util.ArcRuntimeException: Couldn't load shared library 'libarcarm.so' for target: Linux, 32-bit
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:15)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:77)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Unable to read file for extraction: libarcarm.so
	at arc.util.SharedLibraryLoader.readFile(SharedLibraryLoader.java:93)
	at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:253)
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
	... 4 more

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 9m 19s
7 actionable tasks: 7 executed
```

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Arm and RPI is not supported.

**Comment by paulwratt** [comment]
why not? It is Java after all.

  Gradle may take up to several minutes to download files. Be patient.  After building, the output .JAR file should be in /desktop/build/libs/Mindustry.jar for desktop builds, and in /server/build/libs/server-release.jar for server builds.

There is no `libs` directory.

It seems to me that it is only this `arc.util.Arc` module that is not running/installed, everything else seems OK. If it were to fail after running, yeah I might agree. You can easily spin up a Qemu if you dont have a RPi handy.

**Comment by Anuken** [comment]
> why not? It is Java after all.

Much of the code is *not* Java. The native libraries are not compiled for ARM.

> There is no libs directory.

Because you didn't build the game, you just ran it.

> It seems to me that it is only this arc.util.Arc module that is not running/installed, everything else seems OK.

Arc is "only" the framework behind the whole game.

> Has no one tested this on a 32bit (x86) Linux before (this is my suspicion).

Of course they have - there have been issues about it, which you should have searched for before opening this one. I've already answered questions like these several times.
