### ISSUE TITLE
plasmadrop.ogg sounds bad

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3357]
it sounds better without plasmadrop playing as plasmaboom.ogg sounds good standalone.

**Comment by HaphLife** [comment]
plasmadrop.ogg or plasmadrop.oog?

**Comment by Legomonster33** [comment]
> plasmadrop.ogg or plasmadrop.oog?

fk

**Comment by Anuken** [comment]
I don't agree, and this isn't a bug.
