### ISSUE TITLE
Sound file "land" for when you land in a sector doesnt play when music volume is set to zero.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3359]
see title

**Comment by BlueWolf3682** [comment]
whered the template/template information go?

**Comment by Legomonster33** [comment]
> whered the template/template information go?

it wasn't necessary

**Comment by MEEPofFaith** [comment]
land is music though...

**Comment by Legomonster33** [comment]
> land is music though...

its 4 seconds long...

**Comment by MEEPofFaith** [comment]
It's still in the music folder

**Comment by Legomonster33** [comment]
> It's in the music folder, and is an mp4 like other music files

yes i am aware its classified as a music, but it shouldn't be as its more of a sound effect

**Comment by Anuken** [comment]
Because it's music.

**Comment by Legomonster33** [comment]
> Because it's music.

but its a 4 second long sound effect

**Comment by Anuken** [comment]
It's in the music folder, it was made in LMMS, and it's an instance of the `Music` class.

If I'm listening to my own music and have Mindustry's set to 0% with sound effects on, **then I wouldn't want to hear it**. You can disagree, but I don't care.
