### ISSUE TITLE
Unloader stops unloading items from specific block, when a type of item cannot be outputed.

### ISSUE THREAD

**Issue by LeggedMacQueen** [Anuken/Mindustry#3362]
**Platform**: Tried on Android and Windows. Should be at every platfrom.

**Build**: Tested on Bleeding edge v 11200 and 11228. 

**Issue**: When an unloader, without specified item, on an storage block with more than 1 type of resources cannot output one of the resources, it stops outputing items from that specific storage block.

**Steps to reproduce**: I found this bug while shrinking a pre-existing Impact reactor schematic.

![image](https://user-images.githubusercontent.com/69767174/98917776-d5e72600-24dd-11eb-9fc5-40712018fafc.png)

I tried to make the unloader get items from both the blast compound mixer and the overdrive at the same time. The unloader stopped outputing items from blast mixer, while I expected it to only output blast.

![image](https://user-images.githubusercontent.com/69767174/98918220-67ef2e80-24de-11eb-8030-733f546d1770.png)

The best way to reproduce is by using an unloader to output 2 different items to different places. Once one fills up, both stop.

**Link(s) to mod(s) used**: none

**Save file**: [For Anuke.zip](https://github.com/Anuken/Mindustry/files/5529383/For.Anuke.zip) This is my testing world if you wish. I have pointed everything with arrows.

**Crash report**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

I was confused when I saw it was never reported.

**Comment by Bohaska** [comment]
Is there an easily testable shematic I can place using your save file to test this? I would like to try it on my Mac.
