### ISSUE TITLE
113.2 is broken with apulse

### ISSUE THREAD

**Issue by l29ah** [Anuken/Mindustry#3363]
**Platform**: Linux

**Build**: 113.2

**Issue**: 
```
$ java -jar Mindustry-113.2.jar 
[I] Initialized Discord rich presence.
[apulse] [error] do_connect_pcm: actual sample rate, 4000 Hz, differs from required 0 Hz
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
gdb hangs trying to open the core dump.
Is there a way to ask Mindustry to use ALSA (like it used to work on v112?)?

**Steps to reproduce**: Run Mindustry.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I use SoLoud with the miniaudio backend, which should support ALSA. I can't find *anything* about this issue online, so this won't be fixed.
