### ISSUE TITLE
Mindustry cannot export anything

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry#3364]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
113.2
**Issue**: *Explain your issue in detail.*
Mindustry is unable to find my Desktop folder. I made Mindustry go back several folders, but when I try to go back, after I get to the specific user folder, Mindustry is unable to find anything in that folder, even though there are tons of folders in it.
What it looks like
<img width="1429" alt="Screen Shot 2020-11-12 at 6 28 39 PM" src="https://user-images.githubusercontent.com/73286691/98931026-69d5e380-2518-11eb-8363-46dc0dc0acc3.png">
What is actually in the folder (sensitive parts cropped out)
<img width="618" alt="Screen Shot 2020-11-12 at 6 30 12 PM" src="https://user-images.githubusercontent.com/73286691/98930979-5e82b800-2518-11eb-8ab2-604cbe13b631.png">
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Mentioned above
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None used
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
The problem is that I can't export anything, so...
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Nope
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bohaska** [comment]
maybe I formatted this wrong...

**Comment by Bohaska** [comment]
Sort of related to an older issue about the same thing, however the platform is on linux and the cause seems to be different. I even  allowed full disk access for mindustry, but it still didn't work.

**Comment by Quezler** [comment]
which version is your mac? catalina by any chance?

![Screen Shot 2020-11-12 at 13 26 51](https://user-images.githubusercontent.com/3179271/98940097-bdc9d380-24ea-11eb-8661-f2fc527bfbcb.png)

**Comment by Bohaska** [comment]
yep

**Comment by hackdustry** [comment]
how did you install mindustry?

**Comment by Anuken** [comment]
Won't fix, your OS is most likely not allowing Mindustry access to your files.

**Comment by Bohaska** [comment]
Is there any way to fix this though?
