### ISSUE TITLE
Very loud sound

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#3366]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
113.2

**Issue**: *Explain your issue in detail.*
When a lot of block explosion sounds are played at once, they aren't limited, and stack together into a very loud sound

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Shoot a bunch of conveyors on multiplayer with toxopid - the sounds will all occur at the same time and stack together. Does not happen in pre-113.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Yes, that's what's supposed to happen.

**Comment by BlueWolf3682** [comment]
now i could imagine playing mindustry at 2am and destroying my speaker and waking up my family with a giant explosion
