### ISSUE TITLE
Logic: Empty line causes "Invalid"

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#3368]
**Platform**: Windows

**Build**: 113.2

**Issue**: When importing logic code via "Edit -> Import from clipboard", every *empty* line turns into "Invalid".

**Steps to reproduce**:
1. Import logic code with empty lines, ex.

    ```
    set foo "foo"

    set bar "bar"
    ```
2. See "Invalid" logic blocks.

**Link(s) to mod(s) used**: None.

**Save file**: [World.zip](https://github.com/Anuken/Mindustry/files/5532205/World.zip)

**Crash report**: None.

---
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Because an empty lines *is* invalid.

**Comment by summetdev** [comment]
Can you add an option to allow empty lines?

**Comment by DeltaNedas** [comment]
bruh anuke what if someone wants to have their code be somewhat clean
