### ISSUE TITLE
Latest version of Mindustry for Android doesn't open

### ISSUE THREAD

**Issue by LeggedMacQueen** [Anuken/Mindustry#3369]
**Platform**: Android

**Build**: 11234

**Issue**: Should be quite self explanatory. I will post the crash report right below 

**Steps to reproduce**: Open Mindustry BE 11234 in an android phone. Mine is Xiaomi Note 9.

**Link(s) to mod(s) used**: I should have routorio downloaded, but not active.

 IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
![Screenshot_2020-11-12-19-45-11-870_com miui bugreport](https://user-images.githubusercontent.com/69767174/98976498-18315700-2520-11eb-8b21-2aa6a33a7629.jpg)
![Screenshot_2020-11-12-19-45-14-578_com miui bugreport](https://user-images.githubusercontent.com/69767174/98976505-19fb1a80-2520-11eb-9a07-46f88e425832.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
> Xiaomi Note 9

**Comment by Anuken** [comment]
Wait until the next commit, this is related to incomplete sound system changes.

**Comment by LeggedMacQueen** [comment]
Oh. Ok. Thanks Anuken.
