### ISSUE TITLE
Able To Place Sandbox Blocks In Campaign

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3373]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 113.2

**Issue**: *Explain your issue in detail.*
On sector 6 "farming base" i am able to place sandbox blocks.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. load my save data
2. go to sector 6 "faming base" directly north of ground zero
3. place item source??????

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
it first occurred while mods were active none that should have done this tho, I disabled them and the issue persisted.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://drive.google.com/file/d/1VegttsqsNfasgoXFWlapD1NFZMx6Aytu/view?usp=sharing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
it has but this time its not because I have a mod that lets me build them. (sorry about that.)

**Comment by Legomonster33** [comment]
do note it only happens on the one specific sector.

**Comment by Esnardo** [comment]
Excuse me, I need to """test""" this bug

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/99013541-bae8d600-251e-11eb-881b-15ce02e00bba.png)
![image](https://user-images.githubusercontent.com/10100000/99013569-c9cf8880-251e-11eb-80e3-5929425c76c9.png)

If only you had a mod **that permanently enabled sandbox mode on every loaded map.**

**Comment by Legomonster33** [comment]
why do u do dis @QmelZ

**Comment by hackdustry** [comment]
unintentional :D

**Comment by QmelZ** [comment]
~~unintentional :D~~

**Comment by DeltaNedas** [comment]
i fucking knee you had a cheat mod but thought it wasnt important to mention it
then lo and behold anuke did it to em

**Comment by Bohaska** [comment]
not again...
