### ISSUE TITLE
Old damaged buildings are not recognized as being damaged upon launching a new core to an area

### ISSUE THREAD

**Issue by VarroWayland** [Anuken/Mindustry#3375]
**Platform**: Android but likely the same on other platforms

**Build**: Beta 113.2

**Issue**: Old damaged buildings are not recognized as damaged upon launching a new core to an area

**Steps to reproduce**: I lost Sector 221, launched a new core there, got to the point where I had Polys and set up some logic so that I could tell them to repair damaged buildings. They repaired some buildings, but didn’t try to repair the buildings that were the remains of my base from before I lost the sector. I manually controlled some of them and tried healing some of the buildings, and it worked no problem. ~~In the save file I have left most of the old buildings unrepaired.~~ Can't upload save file

**Link(s) to mod(s) used**: N/A, non modded

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* Rip the zipped file's too big
And I can't upload to google drive from this old kindle. Great.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.* N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
