### ISSUE TITLE
during the construction of conveyors, every 10th

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry#3376]
**Platform**: Windows

there are several bugs.
during the construction of conveyors, every 10th corner conveyor is not completed. perhaps this is due to the failure to continue construction when the block is removed from the fur.

when randomly generating maps, there is no generation of ore, scrap metal or sand, or titanium or thorium. Which makes many maps unplayable in the map test server.

This problem can be solved by introducing a scan of the map for unusability into the game. For example, the generator generates a map. and scans it for resources. If there are no important resources on the map. then a new map is generated.

or you can reduce the cost of the disassembler by removing the kinetic alloy from its crafting and replacing it with plastian, making it possible to turn any resources into slag.

idea for bots
bot overflow
Tier 1: can water burning buildings and fly for a set of new water
Tier 2: cannot fly, crawls over buildings. can become stationary and increase its firepower
Tier 3: repairs buildings, collects water and carries it to the weapon; it is permanently installed on it and equips it with water for some time. Cannot attack but can extinguish everything around
Tier 4: repairs buildings and puts out fires. accelerates allied bots. equips them with ammo. cannot attack enemies
Tier 5: can carry ships of Tier 4 and 5 + can everything that Tier 4 and 3

**Comment by YellOw139** [comment]
What happened to the template?
Why does https://github.com/Anuken/Mindustry-Suggestions/issues even exist?

**Comment by DeltaNedas** [comment]
why does poor anuke have to wake up to *this*
