### ISSUE TITLE
AI base units crash when killed

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry#3378]
**Platform**: Windows

**Build**: 6.0, 113.2 Beta

**Issue**: Although Player base units [alpha-beta-gamma] don't crash [like fall down and damage areas around them] upon death, AI on Attack maps do.

**Steps to reproduce**: I came across this while playing an online attack map, and you just need to kill a base AI unit to recreate this.

**Link(s) to mod(s) used**: none.

**Save file**: Unneeded. This bug occurs in every Attack map.

**Crash report**: none.

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Why wouldn't they crash? Player units don't crash because they are deconstructed when the player leaves them.

**Comment by Legomonster33** [comment]
> Not a bug. Why wouldn't they crash? Player units don't crash because they are deconstructed when the player leaves them.

the same should occur for the enemy core units aswell.
