### ISSUE TITLE
Scatter damages ground unit

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3381]
**Platform**: *Any*

**Build**: *113.3*

**Issue**: *For whatever reason Scatter projectiles affect ground units*

**Steps to reproduce**: *Try to shoot with scatter in some ground units via logic or direct control*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by QmelZ** [comment]
~~is it possible that you are using hackustry for some reason?~~

**Comment by Slava0135** [comment]
> ~is it possible that you are using hackustry for some reason?~

idk i was just playing on random pvp server

**Comment by QmelZ** [comment]
> > ~is it possible that you are using hackustry for some reason?~
> 
> idk i was just playing on random pvp server

oh okay then, i thought it might be something related to hackustry and i wrote that because someone apparently has opened 2 bug reports because of hackustry
