### ISSUE TITLE
Polys being ultra stupid

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3382]
**Platform**: *Any*

**Build**: *113.2*

**Issue**: *You can often see Polys being retarded. The issue is that they rebuild EVERY DAMN BLOCK. In PVP they are likely will be shot somewhere cos some nerd built a wall on enemy base. Or they would like to rebuild something in range of turrets. Or they would fly over entire map for a single router being constructed. In other words I hate them... Ok, I know you can fix this with processors, but this is for "advanced" players only - not an average player ~~and especially not for an average pvp player~~*

*please end their suffering...*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
So, what do you want them to do? Magically read your mind to figure out which blocks should be rebuilt, and which shouldn't? There's no good heuristic for that. **They're only as stupid as the people who built those blocks.**

**Comment by YellOw139** [comment]
At least someone is seeing that logic is not an excuse for stuff to not be working by default.
In this particular case though, there really is no fix (there are other units which could still be adjusted though).

**Comment by BlueWolf3682** [comment]
the only issue with poly rebuild is that in v6 theyre rebuilding thors, which results in explosions

**Comment by Anuken** [comment]
> the only issue with poly rebuild is that in v6 theyre rebuilding thors

*As usual...*

![2020-11-13 18-48-51](https://user-images.githubusercontent.com/10100000/99131403-0ebbf380-25e1-11eb-8b04-6a8e2c27b8a0.gif)

![2020-11-13 18-49-42](https://user-images.githubusercontent.com/10100000/99131432-1ed3d300-25e1-11eb-93c8-62cdb93d29a2.gif)

**Comment by Legomonster33** [comment]
> So, what do you want them to do? Magically read your mind to figure out which blocks should be rebuilt, and which shouldn't? There's no good heuristic for that. **They're only as stupid as the people who built those blocks.**

have them prioritize blocks by distance from the player core, and ignore blocks that cannot be rebuilt because that would have the poly be in range of an enemy turret (capable of harming the poly)?

**Comment by YellOw139** [comment]
> have them prioritize blocks by distance from the player core, and ignore blocks that cannot be rebuilt because that would have the poly be in range of an enemy turret (capable of harming the poly)?

That doesn't work. Then they won't be repairing my defense lines automatically. They already seem to prioritize the core when conveyors around it got destroyed, which is good enough, but I have to rebuild walls myself before they start rebuilding turrets themselves while I do other stuff.

In attack maps, the enemy could build turrets around your defense. Now would you rather not have polys rebuild your turrets that need to attack the enemy's stuff just because there is a tiny chance the enemy's bullets won't hit your turrets, won't hit your other units, but will hit the polys?

**Comment by Scorppoison** [comment]
There needs to simply be added an Area toggle.
You'd hold a button, drag an area and your Poly would only rebuild things inside that area.
We already have the "F" toggle, so it'd be a clone of that for the Poly.

**Comment by YellOw139** [comment]
@Scorppoison Go to suggestions.

**Comment by xyzzy529** [comment]
Or just build from the Core out. Closest to the core first.
The problem is they go in some strange order and want to build the farthest away that is newly covered by the enemy... before building anything closer.
