### ISSUE TITLE
Multiple unknown crashes

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3389]
**Platform**: *iOS*

**Build**: *beta 113.2*

**Issue**: *Game crashes unexpectedly quite often. I am entirely unsure as to why, whether its due to continuing issues with my GPU or its a legitimate crash.*

**Steps to reproduce**: *I don't know, it seems to be with larger maps but it has happened on smaller maps.*

**Link(s) to mod(s) used**: *null*

**Save file**: *null*

**Crash report**:  *These are all the crash logs on my iPod. Unsure what applies as "relevant".*
[logs.txt](https://github.com/Anuken/Mindustry/files/5540268/logs.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I might've searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
On looking at the logs, the crashes in them seem to be due to the fixed issue of app switching caused unexpected crashes, so by my guess its my GPU dying again.

**Comment by Bohaska** [comment]
@BlueWolf3682 If that is the case, what can Anuke do about it?

**Comment by Anuken** [comment]
This isn't relevant in newer versions. Wait for next release.
