### ISSUE TITLE
Mindustry stucks at loading screen

### ISSUE THREAD

**Issue by 5382Ander2** [Anuken/Mindustry#3390]
OS:Windows 7 Ultimate

**Build**: 113.2

**Issue**: Every time I start mindustry, it stucks at loading screen, i have tried both 64 and 32 bit version of mindustry, I reinstalled both the game and Java, restarted my PC, and it still fails to load. I use unit-factory mod and its dependencies. I tried to load mindustry without mods, same problem.

**Reproduce Steps**:

1)Game worked normally
2)I updated the game to 113.2
3)This issue happened

**Link(s) to mod(s) used**:Tried without mods too.
**Crash report**:   [hs_err_pid7684.log](https://github.com/Anuken/Mindustry/files/5540428/hs_err_pid7684.log)

**Save file**: *I started with a fresh install, no save files*

---
  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 5382Ander2** [comment]
I forgot to attach screenshots, here:

![mindustry](https://user-images.githubusercontent.com/57288843/99144289-f4c3f480-2664-11eb-9ae3-e35c36d20284.png)

**Comment by Anuken** [comment]
fixed

**Comment by 5382Ander2** [comment]
How

**Comment by Anuken** [comment]
The next commit.

**Comment by 5382Ander2** [comment]
Next release

**Comment by Esnardo** [comment]
I had this same problem, but didn't want to report it without a bug report

**Comment by 5382Ander2** [comment]
**It will be fixed in the next release**

**Comment by DeltaNedas** [comment]
if mindustry freezes, kill it and run it from a terminal to get stdout.

**Comment by 5382Ander2** [comment]
I do not understand

**Comment by 5382Ander2** [comment]
It is not fixed!!!
