### ISSUE TITLE
Falling units are rendered behind the "darkness" that appears on wall tiles.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3391]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 113.2

**Issue**: *Explain your issue in detail.*
falling unit sprites get drawn below the black wall void

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. have unit fall whilst above the "void"

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
n/a

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
graphical issue so heres a photo that shows the unit (you can see its smoke but not the actual unit) 
![image](https://user-images.githubusercontent.com/54417042/99144444-ef9a8180-2633-11eb-97f8-d9c338a6fdd5.png)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.

**Comment by Legomonster33** [comment]
> Intentional.

oh? might i ask why?

**Comment by Anuken** [comment]
Falling units lose elevation, which makes them get rendered at the ground layer, which is below darkness.

**Comment by Legomonster33** [comment]
> Falling units lose elevation, which makes them get rendered at the ground layer, which is below darkness.

if thats the case then why dont artillery bullets also go underneath the darkness, as they presumably go in an arc before hitting the ground exploding, at some point being lower than the darkness.?

**Comment by Anuken** [comment]
Bullets aren't units and don't vary their Z layer.

**Comment by Legomonster33** [comment]
> Bullets aren't units and don't vary their Z layer.

im aware they dont currently, but in theory they should. artillery bullets at least as they typically go in an arc.

**Comment by Anuken** [comment]
That's not supported by the rendering system, is completely irrelevant to this issue, and would make practically no visible difference. In fact, it would look *worse* when noticed, because then you'd have artillery appearing over/under flying units as it moves, giving it a glitchy appearance.

**Comment by Legomonster33** [comment]
Artillery should never go over flying units, but 
![image](https://user-images.githubusercontent.com/54417042/99151939-a7e41c00-266c-11eb-8279-164c953d2e16.png)
it doesn't really make sense that flying units can pass through the darkness but artillery bullets cannot, 
(left is unit, right is artillery gun)

**Comment by Anuken** [comment]
I have no idea what you're talking about. Where are you getting this information?  Since when are artillery bullets blocked by darkness? What does this have to do with the issue?

**Comment by Legomonster33** [comment]
> What does this have to do with the issue? 
rendering things behind/infront of the darkness

> Since when are artillery bullets blocked by darkness?
they visually explode above the darkness, never going underneath it to to hit the supposed ground that they would typically explode on.

**Comment by Anuken** [comment]
> they visually explode above the darkness, never going underneath it to to hit the supposed ground that they would typically explode on.

Why should they go underneath it? The explosion being seen *above* the darkness does not mean it does not occur below the darkness too. There is absolutely no reason to do this.

**Comment by Legomonster33** [comment]
> Why should they go underneath it?

so that they can "hit" the ground causing them to explode.

**Comment by Anuken** [comment]
>  The explosion being seen above the darkness does not mean it does not hit objects visually below the darkness too.

**Comment by Legomonster33** [comment]
> The explosion being seen above the darkness does not mean it does not hit objects visually below the darkness too.

the projectile stays visibly above the darkness making it seem as though it doesnt ever collide with the ground underneath of it.

**Comment by Anuken** [comment]
> the projectile stays visibly above the darkness making it seem as though it doesnt ever collide with the ground underneath of it.

To you, maybe. I don't agree.

**Comment by Legomonster33** [comment]
its more of a matter of consistency, units falling go below the darkness and impact the ground, but projectiles stay above it, but still impact something.

**Comment by Anuken** [comment]
That doesn't matter. Flying units look fine when they fall into the edge of darkness and go under it, and projectiles would just look *wrong* if they went under the darkness layer.

**Comment by Legomonster33** [comment]
> That doesn't matter. Flying units look fine when they fall into the edge of darkness and go under it, and projectiles would just look _wrong_ if they went under the darkness layer.

maybe have it so that projectiles that can only hit ground units (hail ripple etc) are always below the darkness, but projectiles that can hit air units are above it? then the aspect of height and ground vs air would be more consistent?

**Comment by Anuken** [comment]
No, that would look terrible, and would be far too much effort to implement.

**Comment by Legomonster33** [comment]
> that would look terrible

as of now units falling through the darkness looks terrible (mainly because its inconsistent)

**Comment by Anuken** [comment]
I don't agree.

**Comment by DeltaNedas** [comment]
what should happen is the unit loses opacity as it falls, into the shadow, eventually blowing up at the current elevation and transparency.

**Comment by Legomonster33** [comment]
> what should happen is the unit loses opacity as it falls, into the shadow, eventually blowing up at the current elevation and transparency.

pr time?

**Comment by Bohaska** [comment]
this is getting complicated...
