### ISSUE TITLE
Keyboard WASD moving dont work on mobile 

### ISSUE THREAD

**Issue by EtichBruh** [Anuken/Mindustry#3392]
**Platform**: *Android*

**Build**: *BETA 113.2 v6*

**Issue**: *I connected keyboard to mobile and set controls on keyboard+mouse ,but when i entered server/game the WASD moving dont work ,but the chat typing with number block choosing work fine. All buttons set up are defaul.*

**Steps to reproduce**: *Connect keyboard to mobile with wired mouse to mobile and set controls to keyboard+mouse and enter game.*

**Link(s) to mod(s) used**: *no mods used*

**Save file**: *[mindustry1132.zip](https://github.com/Anuken/Mindustry/files/5540662/mindustry1132.zip)*

**Crash report**: *No crashes happened.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
-[X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix.

**Comment by JakoDel** [comment]
> Won't fix.

did you ever revisit this issue? just got my s23 ultra and tbh it would be a blast to play mindustry both on the go and on my monitor w/dex and keyboard+mouse. 

I understand that people playing this way may be very little though, no worries if you don't want to waste time on this

**Comment by Anuken** [comment]
Keyboard controls work fine for me when I test them on my phone; if they don't work for you, there's something going wrong with your device in particular.
