### ISSUE TITLE
Maybe its a bug.

### ISSUE THREAD

**Issue by Shiningdark0930** [Anuken/Mindustry#3398]
I am not very good at English, so I use a translator to speak.
It's a feature that's been around since version 6.0, but it's a bit weird.
Maybe it's a bug.
For example, let's say you are going to sort out from Zone 1 to Zone 2.
Then resources are consumed, right?
But it is not. The resources in Zone 1 are still there.
For reference, I am Korean, so if you can speak Korean, please answer in Korean..!

**Comment by Anuken** [comment]
Template.

**Comment by Esnardo** [comment]
To clarify what he said, you need to use the template with the "Version number" and the "Explain your issue in detail". If you don't, Anuke will close the issue.
