### ISSUE TITLE
Microsoft VisualC++ Runtime "Assertion Failed!"

### ISSUE THREAD

**Issue by Bedsurfer** [Anuken/Mindustry#3399]
**Platform**: Windows

**Build**: 11286

**Issue**: Was editing a map when suddenly my game crashed with this error.
![image](https://user-images.githubusercontent.com/72096570/99158871-c6f6a400-2694-11eb-97c6-542f68f2ccdb.png)
Now the game refuses to open regardless of which of the recent BE builds i use.

**Steps to reproduce**:

1. Was editing a map (file below)
2. Game crashed suddenly
3. Gives error every time I try to relaunch

**Link(s) to mod(s) used**: None

**Save file**: 
[map_25.zip](https://github.com/Anuken/Mindustry/files/5541570/map_25.zip)
No save file, but i think i was editing this map (I think)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No crash report was produced, looked in the crash report folder. Pressing any of the options did not produce a crash report.
***Update: I didn't know debugging it would send a log outside of the file, here it is.***
[hs_err_pid52800.log](https://github.com/Anuken/Mindustry/files/5541590/hs_err_pid52800.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't really fix this.
