### ISSUE TITLE
Contributions welcome?

### ISSUE THREAD

**Issue by BeefEX** [Anuken/Mindustry#34]
Hi, are you open to receiving contributions? I would love to help, maybe work on some of the new features.

**Comment by wade-fs** [comment]
I want submit core/assets/bundles/bundle_zh_TW.properties
How can I do?

**Comment by Anuken** [comment]
@wade-fs The bundle already exists, but if you want to edit it, see https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md
