### ISSUE TITLE
When opening the research screen I lose 1.1k Silicon

### ISSUE THREAD

**Issue by steelphoenix4** [Anuken/Mindustry#3401]
**Platform**: *Windows*

**Build**: *112.1*

**Issue**: *When opening the research screen the core of the world I am in loses 1.1k silicon*

**Steps to reproduce**: *Open the research screen*

**Link(s) to mod(s) used**: *n/a*

**Save file**: *[World2.zip](https://github.com/Anuken/Mindustry/files/5541942/World2.zip)*

**Crash report**: *n/a*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 5382Ander2** [comment]
Have you used launch pads, the same issue happened to me, when opening research I lose all my titanium, thorium and plastanium. After you loose a certain amount of materials, this glitch will stop.
