### ISSUE TITLE
@shooting always returns 0 for uncontrolled units

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3404]
**Platform**: *Any*

**Build**: *113.2*

**Issue**: *You can't check if bound unit is shooting at the moment (while not being controlled)*

**Steps to reproduce**: *Try to read @shooting field when bound unit is actually shooting*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
oh so you tested on every supported platform cool
nice code you posted

**Comment by Slava0135** [comment]
nvm before you can check vars from bound unit you need to give him some command...

**Comment by Slava0135** [comment]
nvm it's not right

```ubind @dagger
set fraction 0.8
sensor health @unit @health
sensor max @unit @maxHealth
op mul limit fraction max
jump 12 lessThan health limit
sensor ammo @unit @ammo
jump 12 lessThanEq ammo 1
sensor shooting @unit @shooting
jump 11 notEqual shooting true
ucontrol stop 0 0 0 0 0
end
sensor x @this @x
sensor y @this @y
ucontrol approach x y 4 0 0
```

**Comment by Slava0135** [comment]
basically a retreat system, if unit is low on either ammo or health it retreats. ***But I can't check if it is shooting, it's always 0...***

**Comment by DeltaNedas** [comment]
sense shooting before jump, i guarantee it will work

**Comment by Slava0135** [comment]
![Uploading Peek 2020-11-15 15-24.gif…]()

**Comment by DeltaNedas** [comment]
ok yes i replicate too
**Build**: 11289
**Platform**: Android 9
**Issue**:
Display does not turn green when mega shoots enemies
**Steps to reproduce**:
1. load schem
2. spawn mega
3. spawn enemy sexy routers or make a cage that enemies cant harm the processor in
4. display is still red
5. manually shooting makes it green

**Schematic**: `bXNjaAF4nGPgYGBjYmDJS8xNZeBQBIKS1OISBu6U1OLkosyCksz8PAYGJgbhnMSi9FTdnPz0zGTdlMzigpzESgb+3MzkonzdgqL85NTi4vwiBpBKIAISjAzsDEx8QIGOijmufd58zQY8LmfXndKsYXFImu/LP8lMzcWI76x7qP4V77KLQqs6WnXP7vl4QpZhz+mz3a57JxlrTVwiYKirmKLPVyo4P9B87aG27MSSiR7nrlj4TvU4cd3dsGfiG872spC7Vqa5iysfzT155PCv719F3+62/3BGVTej9taNPWxb628dXHryPfsD9rWb7KIZABhoWAs=`

**Comment by Slava0135** [comment]
![Peek 2020-11-15 15-30](https://user-images.githubusercontent.com/40753025/99184939-aba09d00-2757-11eb-9e68-fffedebd0f56.gif)
***you can check health, but not shooting...***

**Comment by DeltaNedas** [comment]
some extra info:
- crawlers never set @shooting (tested on micro)
- healers like mega will set @shooting when healing blocks

**Comment by DeltaNedas** [comment]
also works when units are being controlled in a formation
