### ISSUE TITLE
On sector 195 the player treats the friendly units as enemies?

### ISSUE THREAD

**Issue by LambdaVoid** [Anuken/Mindustry#3405]
**Platform**: *Android*

**Build**: *113.2*

**Issue**: *In sector 195, there (near the landing area) are some laser drills, fuse turrets, some titanium conveyor belts, and a large solar panel, they look like friendly buildings (no red triangles in the corners) yet the player starts to shoot them when i get nearby. Also i could pick up titanium from the drills and use a nearby large power connector. I later tried if turrets (duo) also shoot them and yes they did*

**Steps to reproduce**: *I went to sector 195*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *
[weird sector 195 bug save.zip](https://github.com/Anuken/Mindustry/files/5542319/weird.sector.195.bug.save.zip)
*

**Crash report**: *It didn't crash the game, it was just an inconvenience*

- 

> [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
they are derelict, salvage them for resources.

**Comment by LambdaVoid** [comment]
But usually when there are derelict structures, the player doesn't star shooting them randomly. And since the game kind of treats them as enemy structures, conveyor belts just don't function.

**Comment by AdvanceContent** [comment]
Fix: dont make team derelict be a target of the autotarget of mobile

**Comment by LambdaVoid** [comment]
There's really no point in a separate team that just doesn't do anything.

**Comment by QmelZ** [comment]
> There's really no point in a separate team that just doesn't do anything.

you should go check what "derelict" means, google explains it very good.

**Comment by LambdaVoid** [comment]
Oh ok, i thought it was just a synonym for abandoned.

**Comment by QmelZ** [comment]
> Oh ok, i thought it was just a synonym for abandoned.

yes, that's the point

**Comment by DeltaNedas** [comment]
its fixed anyways

**Comment by QmelZ** [comment]
yeah, no autotargeting of derelict blocks anymore
