### ISSUE TITLE
Cannot export<-> import file between devices

### ISSUE THREAD

**Issue by ck-pgtrebacz** [Anuken/Mindustry#3409]
**Platform**: *Android*

**Build**: 104.6 (both)

**Issue**: Importing data to new device crashes application.

**Steps to reproduce**: 
deviceA->Mindustry->Export Data->GDrive->OK
deviceB->Mindustry->Import Data->Returning to home screen->No data imported

**Save file**: 
[mindustry_save.zip](https://github.com/Anuken/Mindustry/files/5542415/mindustry_save.zip)

**Crash report**: Crash happened, but no report was shown.

---
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Crash report: Crash happened, but no report was shown.

Then I can't help you.

**Comment by DeltaNedas** [comment]
did you not read the message saying it will exit
this is a duplicate

**Comment by ck-pgtrebacz** [comment]
As I have written the data is **not** imported.
