### ISSUE TITLE
can't use uradar on players

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3415]
**Platform**: Android 9

**Build**: 11295, betting its still "latest" in the morning

**Issue**:
`uradar` does nothing for player-controlled units.
I think it's fine as it doesn't let logic control players like `ucontrol` would.

**Steps to reproduce**:
1. Import code and link a message
2. Look in message block
3. null every time h

**Code**: ```
ubind @gamma
uradar any any any distance turret1 1 result
print result
printflush message1
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Players cannot be bound, controlled or radar-ed from.

**Comment by DeltaNedas** [comment]
controlled i get, but why not radar'd?
