### ISSUE TITLE
The enemy AI is able to block the path of enemy units

### ISSUE THREAD

**Issue by santiagocezar** [Anuken/Mindustry#3416]
**Platform**: *Android*

**Build**: *112*

**Issue**: *When playing on an enemy sector on campaign mode, the enemy starts building schematics all over the map. Sometimes a build fits perfectly the terrain and blocks the path to the player's core, which causes ground units to stay in the same place and they start accumulating in front of the enemy core*

![Screenshot_2020-11-15-18-42-07](https://user-images.githubusercontent.com/48573316/99198712-2f1eb600-2779-11eb-803d-9d347f491036.png)

I think making sure the build leaves a 1 block gap around it could fix this

**Steps to reproduce**: *Happened while playing on sector 214, on a previous attempt this didn't happen, it probably depends on RNG*

**Save file**: *https://send.vis.ee/download/3e58e9e12eaa1628/#96MWJCGZ9pQko3-ALWqYCA*

---

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
duplicate
