### ISSUE TITLE
Already finished sector is getting "under attack"

### ISSUE THREAD

**Issue by vgaming** [Anuken/Mindustry#3417]
**Platform**: *ArchLinux*

**Build**: *v6 beta build 112*

**Issue**: *Already "finished" sector with destroyed enemy base became under attack after I was doodling in it*

**Steps to reproduce**:
* Start sector 101 (Salt Flats)
* Win the sector by destroying enemy base
* Wait
* ... After some time, I got a "pop-up"-like message saying that "Salt Flats" sector (my current sector) is under attack. When I re-joined Salt Flats, it was indeed under attack from future airplane waves, spawn from where the enemy base was

**Link(s) to mod(s) used**: *None*

**Save file**: *attached* 
[sector-serpulo-101.zip](https://github.com/Anuken/Mindustry/files/5544910/sector-serpulo-101.zip)

**Crash report**: *Not a crash*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by vgaming** [comment]
Furthermore, when I reloaded the game again, it was again no waves. For 5-10 minutes, the situation stayed the same,there were no waves. After that, I got "under attack" thing again, and now I have to defend against *27* waves. I don't know what 27 means exactly, I had wave 100+ when I first destroyed enemy base and the bug first occurred.

Attaching screenshot of the "27 waves" situation
![2020 11 16_11:41:41](https://user-images.githubusercontent.com/33452702/99243546-207be180-2801-11eb-85a7-47403c31af99.png)

**Comment by Khaezar** [comment]
I think that's a new functionality of V6

**Comment by LeggedMacQueen** [comment]
Nect to your secyor should be a red sector. It is the sector attacking you. If you capture it, it will stop attacking all toghether.

**Comment by DockedSiamang22** [comment]
Yea, in v6, sectors will come back under attack if an attack sector(red border) is directly adjacent to a captured sector

**Comment by LeggedMacQueen** [comment]
Wow, I typed it very fast, and... well... made a lot of typos.

**Comment by Anuken** [comment]
All of that is already documented. Red sectors have "enemy base" in their description, there's a red arc toward nearby sectors and any sectors near it as marked "vulnerable."

**Comment by vgaming** [comment]
@Anuken where is the vulnerability marking though? :thinking:  (screenshot attached)
![2020 11 16_14:53:03](https://user-images.githubusercontent.com/33452702/99260448-ae64c600-281b-11eb-8aa5-e912c2ed8457.png)

Also, I acknowledge I did mess up with savegames, but it feels strange to me that first "attack" on my sector was done with wave strength 100+, but later it was clearly wave1..27 again. I can watch carefully on sectors where I don't mess with savegames I guess.

**Comment by Anuken** [comment]
> where is the vulnerability marking though?

You're running an older version that doesn't display it.

**Comment by vgaming** [comment]
@Anuken thanks for the explanations!
