### ISSUE TITLE
Units cast shadow on space background.

### ISSUE THREAD

**Issue by LeggedMacQueen** [Anuken/Mindustry#3418]
**Platform**: All

**Build**: 11312

**Issue**:  Units cast shadow on space background.

**Steps to reproduce**: Fly over space background

--

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by YellOw139** [comment]
Duplicate, won't be fixed. See #3101

**Comment by LeggedMacQueen** [comment]
I searched for it in the past 3 pages. Didn't see it. Sorry for wasting time bruh
