### ISSUE TITLE
Core starts damaged in custom maps (sandbox)

### ISSUE THREAD

**Issue by GoldGuy64-GD** [Anuken/Mindustry#3420]
I made a custom map to create some shechematics (it doesn't have spawning points), but when opening a new custom game in my map, the core starts with half the normal live.

**Comment by BlueWolf3682** [comment]
maps save the state of blocks exactly, and the foundation and nucleus both have more halth in v6. also, template

**Comment by D-player1** [comment]
You're on an old version

**Comment by Gdeft** [comment]
template
