### ISSUE TITLE
Units in Editor

### ISSUE THREAD

**Issue by SkinH** [Anuken/Mindustry#3423]
**Platform**: *Linux*

**Build**: *114*

**Issue**: *In Editor units ATTACK. Editor...*

**Steps to reproduce**: *java -jar server.jar  ->  host map editor*

**Crash report**:
![изображение](https://user-images.githubusercontent.com/62944380/99318387-a4bd7b80-2878-11eb-9217-9ce3d170b3fa.png)
*

---
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Yes, all units update in the editor.
