### ISSUE TITLE
Bug thing

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#3424]
**Platform**: Android

**Build**: 114

**Issue**: I stopped the time

**Steps to reproduce**: Almost captured Ruinous Shores when importing my save and when i skipped on wave 30/30 timer got stuck in 1:59

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
I can't because when i tried to update my save the game crashed

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I can't because when i tried to update my save the game crashed

I can't do anything without a save. If you got a crash, why didn't you post it here?

**Comment by D-player1** [comment]
The game didn't give a crash, it just suddenly quit

**Comment by D-player1** [comment]
But here's the save file before the bug happened
[Uploading Kek.zip…]()

**Comment by Anuken** [comment]
That's not a save file.

**Comment by D-player1** [comment]
Wait nvm i found the crash log
[crash_1605569462768.txt](https://github.com/Anuken/Mindustry/files/5550351/crash_1605569462768.txt)

**Comment by Esnardo** [comment]
sigh....

**Comment by D-player1** [comment]
And save file just takes too long to load
[Kek.zip](https://github.com/Anuken/Mindustry/files/5550358/Kek.zip)
