### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by SkinH** [Anuken/Mindustry#3425]
**Platform**: *Linux*

**Build**: *114*

**Issue**: *В режиме Editor на сервере из источников предметов выдаются предметы. А в Editor в клиенте нет. И это вызывает недоразумение в виде спавна юнитов в Эдиторе на сервере и нарушает его предназначение.*

**Steps to reproduce**: *java -jar server.jar   -->   host map editor*

**Crash report**: *https://yadi.sk/i/u958EneljyFHJA*

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
