### ISSUE TITLE
Incorrect "Insufficient Core Resources" preventing launch

### ISSUE THREAD

**Issue by q00u** [Anuken/Mindustry#3427]
**Platform**: *Windows*

**Build**: *steam build 114.1*

**Issue**: *Trying to launch from 219 to 97.  Can't launch due to insufficient core resources. Only 770 sand. Except... the core here has 9000 sand. Where is this 770 number coming from?*

**Steps to reproduce**: *It just happened randomly.*

**Link(s) to mod(s) used**: *None.*

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5551294/saves.zip)

**Crash report**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
i have the same issue and can provide steps to reproduce
1. be in sector
2. attempt to launch with a schematic for core shard
3. exit and reopen the menu
4. you cannot switch to other schematics as it limits the resources to 4k (for shard)

**Comment by lINSTINCTl** [comment]
I think reason of this is the system automatically changes what sector resources location that you will use and change it to the nearest sector to where you wany to lauch

**Comment by q00u** [comment]
lINSTINCTl is correct, that's exactly what's happening. I didn't realize this was changed in the most recent update.
