### ISSUE TITLE
#3220 is back

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3428]
#3324 for a possible fix

**Comment by Anuken** [comment]
I intentionally added it back after coming to the conclusion that player should not be able to camp at a location and send cores anywhere. Your suggestion makes no sense.

**Comment by Legomonster33** [comment]
> I intentionally added it back after coming to the conclusion that player should not be able to camp at a location and send cores anywhere. Your suggestion makes no sense.

you can still send resources anywhere it just makes doing so much more painful

instead of it being
1. launch to sector
2. play sector

its
1. launch resources to adjacent sector
2. wait 5-10 mins for enough resources to be launched
3. switch to adjacent sector
4. launch to sector
5. play sector

having the ability to launch anywhere would make sense to be researched or unlocked after getting launchpads, as they are what allow you to this.

**Comment by Anuken** [comment]
> you can still send resources anywhere it just makes doing so much more painful

Yes, so *don't.* Expand your effective range instead. Build up other bases.

> having the ability to launch anywhere would make sense to be researched or unlocked after getting launchpads, as they are what allow you to this.

They're not, and this doesn't make sense. Launch pads have nothing to do with cores.

**Comment by Legomonster33** [comment]
> Yes, so don't. Expand your effective range instead. Build up other bases.

that's not the point, even though that would be faster, its not the *optimal* strategy and as such nearly nobody will actually do that.

> Launch pads have nothing to do with cores.

launch pads have the ability to extend your effective operating area to the whole planet, which allows you to launch from anywhere to anywhere (with pain).

**Comment by Anuken** [comment]
> that's not the point, even though that would be faster, its not the optimal strategy and as such nearly nobody will actually do that.

Then don't do it.

> launch pads have the ability to extend your effective operating area to the whole planet, which allows you to launch from anywhere to anywhere (with pain).

Again, that has nothing to do with cores and I don't see how it's related to launching anywhere. You're simply repeating the same point over again.

**Comment by Legomonster33** [comment]
> Again, that has nothing to do with cores and I don't see how it's related to launching anywhere. You're simply repeating the same point over again.

it has to do with cores as they are your means of launching to new sectors, and launch pads allow you to extend the ability of launching to new sectors with resources from elsewhere. launch pads are the only means of getting resources from point a to point b, which is a very important step in launching from point a to point c.

**Comment by Legomonster33** [comment]
you are still very

> able to camp at a location and send cores anywhere.

it just is a bit slower and a lot more boring

**Comment by Anuken** [comment]
> it just is a bit slower and a lot more boring

**Exactly**, so don't do it.

> [...] launch pads allow you to extend the ability of launching to **new sectors** with resources from elsewhere

That's exactly what they *don't* do.

Launch pads launch resources. Cores launch other cores. Unlocking a launch pad should not magically give your core infinite range. If you want your launch pads to send continuous resources *to a sector you just launched to*, you can do that. End of discussion.
