### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [Anuken/Mindustry#3429]
**Platform**: *Windows*

**Build**: *114.1*

**Issue**: *If you are on campaigan, you can spend items without losing them on tech tree.*

**Steps to reproduce**: *Only very unconciuous people can do this, if you spent a item and quickly go to a different area on the planet, the items will be 0 when spent but if you check tech tree again the materials are back.*

**Link(s) to mod(s) used**: *None*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. i dont know what is the zipped folder, but it happens on campaigan*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dr4coDragon** [comment]
I can confirm, had similiar issue. I just want to add that to reproduce this you just need to open tech tree, research something, close it while playing on some map and return to tech tree, and you will see same state of resources before spending resources

**Comment by ThisIsACoolBoy** [comment]
this issue is closed, but in this new version, this issue still persists

**Comment by ThisIsACoolBoy** [comment]
> 
> 
> I can confirm, had similiar issue. I just want to add that to reproduce this you just need to open tech tree, research something, close it while playing on some map and return to tech tree, and you will see same state of resources before spending resources

thats right
