### ISSUE TITLE
Strange light

### ISSUE THREAD

**Issue by grimsoul10** [Anuken/Mindustry#3430]
**Platform**: *Android*

**Build**: *beta build 114.1*

**Issue**: *so when i play campaign in salt flat iam place one parallax to defense my core,but when i go to destroy enemies core that thing happened.*

![Uploading Screenshot_2020-11-17-13-34-44-441_io.anuke.mindustry.jpg…]()

[](url)
![Uploading Screenshot_2020-11-17-13-34-59-844_io.anuke.mindustry.jpg…]()

**Steps to reproduce**: *just place parallax somewhere and yes this bug will gone when u close and open mindustry again .*

**Link(s) to mod(s) used**: *nope.*

**Save file**: *nope.*

**Crash report**: *nope.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul7** [comment]
![Uploading Screenshot_2020-11-17-13-34-59-844_io.anuke.mindustry.jpg…]()
![Uploading Screenshot_2020-11-17-13-34-44-441_io.anuke.mindustry.jpg…]()

**Comment by grimsoul7** [comment]
![Uploading Screenshot_2020-11-17-13-34-59-844_io.anuke.mindustry.jpg…]()

**Comment by q00u** [comment]
> Uploading Screenshot_2020-11-17-13-34-59-844_io.anuke.mindustry.jpg…

I can't see any of these screenshots

**Comment by grimsoul10** [comment]
Me too

**Comment by QmelZ** [comment]
well you have to wait for them to upload before you post the issue

**Comment by Anuken** [comment]
> Save file: nope.
