### ISSUE TITLE
Bug with opening content, and bug with the core

### ISSUE THREAD

**Issue by DandomMolt** [Anuken/Mindustry#3434]
**Platform**: Windows

**Build**: Beta build 114.1

**Issue**: I played in sandbox mode on the map. My game was just downloaded and I didn't have any saves. In sandbox mode, I extracted resources. And as soon as I got the coal, I saw the message "New content unlocked!". After that, I opened Tech Tree, and I had coal open. I don't think it should have opened while playing in sandbox mode. And when I launched the map in sandbox mode, initially my core was half broken

**Steps to reproduce**: I just downloaded the game and launched the map in survival and sandbox mode. In the nucleus core, when I go to the map, the core doesn't have about 40% health. To unlock content, I just got any resource that I would like to open (for example, coal)

**Link(s) to mod(s) used**: **Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: [mysave.zip](https://github.com/Anuken/Mindustry/files/5553115/mysave.zip)

**Crash report**: The game didn't crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by QmelZ** [comment]
just happened to me, i can provide some steps tto reproduce too.

1. enter a sandbox map
2. place and break some titanium walls
3. see the content unlocked! popup

**Comment by rmperkow** [comment]
This happened with liquids. I placed a source and it said unlocked even though it was already unlocked. (because sandbox)
