### ISSUE TITLE
#3428

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3436]
> > it just is a bit slower and a lot more boring

> Exactly, so don't do it.

you just saying to not do it has effectively 0 influence on whether or not the people who are playing the game are going to do it. you cant just say to not do something.

> > [...] launch pads allow you to extend the ability of launching to new sectors with resources from elsewhere

> That's exactly what they don't do.

that is literally one of their main uses, to launch resources in preparation for a core launch.

> Launch pads launch resources. Cores launch other cores. Unlocking a launch pad should not magically give your core infinite 
range.

launch pads extend your range, indirectly upgrading your core, so it would make sense if you could also unlock "better thrusters (so you can launch anywhere)" for your core. to do the same thing, with less pain

> If you want your launch pads to send continuous resources to a sector you just launched to, you can do that. End of discussion.

that works, but what if you want to launch with resources? so that you can have a kickstart for your base? yaknow, the main purpose of being able to launch with loadouts + resources.

**Comment by Anuken** [comment]
> you just saying to not do it has effectively 0 influence on whether or not the people who are playing the game are going to do it. you cant just say to not do something.

I can make it horrible and annoying, which has the same effect.

> that is literally one of their main uses, to launch resources in preparation for a core launch.

No, they don't launch to new sectors. They only launch once you've landed at that sector.

> launch pads extend your range, indirectly upgrading your core, so it would make sense if you could also unlock "better thrusters (so you can launch anywhere)" for your core. to do the same thing, with less pain

No, it wouldn't make sense. No matter how many times you tell me "it makes sense", it's not going to. I don't want people to do this thing. I want it to be painful. That's the point.

> that works, but what if you want to launch with resources? so that you can have a kickstart for your base? yaknow, the main purpose of being able to launch with loadouts + resources.

**Then capture the sector next to it, and launch from there.**

None of your points are relevant. I closed the previous issue for a reason. Stop.

**Comment by Legomonster33** [comment]
> Then capture the sector next to it, and launch from there.

That is what you do!!!
except you have to launch pad resources if you want to have resources.

> No, they don't launch to new sectors. They only launch once you've landed at that sector.

I am aware!!!
they launch to the sector adjacent to the new sector, so you can then launch to it.

**Comment by Erisfiregamer1** [comment]
Legomonster stop.
Not how the game is gonna be played, now get OVER it.

**Comment by GlennFolker** [comment]
Are tou seriously telling the game OWNER how to fricking play his OWN game??

**Comment by Legomonster33** [comment]
> Are you seriously telling the game OWNER how to fricking play his OWN game??

im telling the creator of the game how ***people play*** the game,
not telling him how to play the game, telling him how others will play the game.

**Comment by Legomonster33** [comment]
> Legomonster stop.
> Not how the game is gonna be played, now get OVER it.

it is literally how the game is played
