### ISSUE TITLE
[Modding]Custom bases not functioning

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3437]
**Platform**: *Windows, 32bit*

**Build**: *beta 114.1*

**Issue**: *Recently a pull request was merged that allowed custom turret bases to be set. However, after trying to use the new custom base code, I found it to be nonfunctional. Uploading a sprite with `base-[turret]` or `[turret]-base` did not function.*

**Steps to reproduce**: *Try to give a turret a custom base.*

**Link(s) to mod(s) used**: *https://github.com/K103908/Exotic-Mod*

**Save file**: *null*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have bothered to search ONLY the open issues to make sure that this problem has not already been reported, as well as checked #github.**
![image](https://user-images.githubusercontent.com/61173114/99422056-5631d080-28bc-11eb-9488-b375bc2ce4e8.png)

**Comment by Anuken** [comment]
The PR was broken, you need to place the sprite in the override folder and give it a different name.

**Comment by BlueWolf3682** [comment]
seriously?! i tried it in the override folder too
