### ISSUE TITLE
schematics on multiplayer failed to build

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry#3438]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: bleeding edge **11344**
**Issue**: schematics on multiplayer failed to build onto map. kicked my player when trying

**Steps to reproduce**: 

1. get logic schematic with lots of logic code
2. attempt to build schematic (copy with "F" key and paste in world)
3. be unable to build any part of schematic
4. remove micro-controller and all other objects are built

**Link(s) to mod(s) used**: none

**Save file**: [29.msav.zip](https://github.com/Anuken/Mindustry/files/5555504/29.msav.zip) save of multiplayer map

**Crash report**: 
[I] Initialized Discord rich presence.
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 96 samples / 2 channels
[I] [GL] Version: OpenGL 3.0.0 / Intel Open Source Technology Center / Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 11.0.7
[I] Total time to load: 17651
[I] Time to generate menu: 314.89056

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> get logic schematic with lots of logic code

Post the actual schematic you're using.

**Comment by Anuken** [comment]
Testing with multiple 1000-line processors, I have no issues on servers. Closing until usable information is given.

**Comment by BlueWolf3682** [comment]
i see nothing wrong about the technical things, that looks to me just like how it would on a normal startup of the game

**Comment by Anuken** [comment]
(That's just the standard log you get when you launch the game and don't play anything.)
