### ISSUE TITLE
FPS drops (Very BAD drops)

### ISSUE THREAD

**Issue by Matitron** [Anuken/Mindustry#3439]
**Platform**: *Mac Os X (10.14.6)*

**Build**: *release build 104.6*

**Issue**: *The game will drop the fps level from 700 (on the non beta version (the itch io version)) to 2-5 ish.*

**Steps to reproduce**: *Open the game with the ".command".*

**Link(s) to mod(s) used**: *N/A.*

**Save file**: *it happens in and out game so not shure what to put here.*

**Crash report**: *N/A.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix.

**Comment by Quezler** [comment]
any idea what it is though?

**Comment by Anuken** [comment]
I don't have a clue what it could be, it doesn't (didn't?) happen on my mac, and I'm just not interested in teasing out every necessary detail from this person when so little information is provided here.

**Comment by Legomonster33** [comment]
I have the same issue and I have come to the conclusion that my pc is a potato.
