### ISSUE TITLE
Grey Team on Attack Sector Makes It Unbeatable

### ISSUE THREAD

**Issue by FireWingLead** [Anuken/Mindustry#3440]
**Platform**: Windows/Steam

**Build**: 114.1

**Issue**: After steam updated the game to version 114.1, I continued the campaign and attempted a takeover of sector 75. As I began fighting/building my way toward the enemy core, I noticed that My turrets would not shoot at the enemy structures automatically except for the one that got rebuilt by the AI. Then I realized that only the rebuilt structures were on the red team. All starting enemy structures were on the grey team, and I could capture them by starting to deconstruct them and then canceling the deconstruction and rebuilding them. I then realized that even the enemy core was a grey team core. I was not able to capture it like the rest when I tried, so I simply blew it up with an Antumbra I had built.

Problem: There were no enemy cores left to destroy, and the sector was not captured, since I had not destroyed any red core. Waves kept coming indefinitely.

**Mods Used**: Only one. I have uploaded the zip file with this report, since I have not uploaded the version I was using anywhere yet. It is a mod that I developed myself called Scrapless Slag. It is unlikely to have anything to do with this issue though.
[ScraplessSlag.zip](https://github.com/Anuken/Mindustry/files/5556221/ScraplessSlag.zip)

**Save file**: I am unsure where and how campaign games are saved. I'm guessing  in "C:\Program Files (x86)\Steam\steamapps\common\Mindustry\saves\saves", and I'm guessing that the relevant save file is the one titled sector-serpulo-75.msav. Here it is:
[sector-serpulo-75.zip](https://github.com/Anuken/Mindustry/files/5556252/sector-serpulo-75.zip)

**Crash report**: No crash was caused.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Searching returns no results, and nothing comes up when I go to the issues tab under Anuken/Mindustry. I assume I am doing something wrong, but I can't figure out what. I am reporting this anyway.

**Comment by Anuken** [comment]
Update your game.
