### ISSUE TITLE
Derelict Team

### ISSUE THREAD

**Issue by SkinH** [Anuken/Mindustry#3441]
**Platform**: *Linux*

**Build**: *114.2*

**Issue**: *Серая команда в режиме Атака неподвижна, буры не работают, конвееры не работают*

**Steps to reproduce**: *java -jar server.jar  --> host map attack*

**Crash report**: *Video*
[Video.zip](https://github.com/Anuken/Mindustry/files/5556536/Video.zip)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by summetdev** [comment]
(моё мнение) Фактически, derelict - это "брошенный". По идее, у этой команды нет игроков, и поэтому в игре она имеет более декоратический характер. Из за этого у неё не должно ничего работать и служит она в основном утилитной командой.

**Comment by ThatOneBepis** [comment]
this also happens to me, kinda unfair that i have captured 2 "extreme", 2 "hard" and "1 eradication" difficulty attack maps because of this

**Comment by ThatOneBepis** [comment]
(in singleplayer, and with some custom mods)

**Comment by Legomonster33** [comment]
они не должны функционировать, так как они заброшены
