### ISSUE TITLE
Salt Flats not capturing immediately when enemy core destroyed.

### ISSUE THREAD

**Issue by a3skales** [Anuken/Mindustry#3442]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Beta built 114

**Issue**: *Explain your issue in detail.*
Even though I destroyed the only core I could find, it continues as if the core was still there. Both the enemies and main enemy unit respawned at the location of the destroyed core. However, immediately after going back into the sector after getting my core destroyed, it said "Sector Captured".

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I simply went to the core with 3 Zeniths, and destroyed it.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods used.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[Mindustry Save.zip](https://github.com/Anuken/Mindustry/files/5557281/Mindustry.Save.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by grimsoul10** [comment]
Use quasar

**Comment by Anuken** [comment]
> Beta built 114

Update your game to 114.2.
