### ISSUE TITLE
Some achievements cannot be completed

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry#3444]
**Platform**: Windows

**Build**: 114.2 (v6 beta)

**Issue**: Some steam achievements cannot be completed in the V6 beta, such as "It Begins" "Flock" and "Volatile Army".

**Steps to reproduce**: Attempt to complete one of the example achievements.

**Link(s) to mod(s) used**: None

**Save file**: 
[sector-serpulo-175.zip](https://github.com/Anuken/Mindustry/files/5558970/sector-serpulo-175.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Those achievements were removed from the system, and are only visible because I haven't released the update to stable yet.
