### ISSUE TITLE
bag or conveers

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry#3445]
![2020-11-18_16-36-49](https://user-images.githubusercontent.com/71027210/99512847-8a8cb600-29bc-11eb-8f00-324c752b60d7.png)
![2020-11-18_16-36-38](https://user-images.githubusercontent.com/71027210/99512851-8bbde300-29bc-11eb-9ad6-71f208949343.png)

**Comment by TheSlaylord** [comment]
I.. I don't exactly understand what's happening here. Anyways, this should be closed immediately

**Comment by Remint32** [comment]
мешок или конвейер
~~конфеты или жизнь~~

**Comment by TheSlaylord** [comment]
> мешок или конвейер
> ~конфеты или жизнь~

~конвейеры*~

**Comment by Anuken** [comment]
*which will you choose?*
