### ISSUE TITLE
bag in generator map

### ISSUE THREAD

**Issue by ziszlo** [Anuken/Mindustry#3446]
bag in generator map
in map 0 torium and c
![2020-11-18_17-15-53](https://user-images.githubusercontent.com/71027210/99517657-3389df80-29c2-11eb-9269-29273feb9437.png)
oal

**Comment by DayTimer** [comment]
1. Not a bug. Some sectors may not contain coal/sand/tita/thorium.
2. Template

**Comment by TheSlaylord** [comment]
This should be closed immediately
