### ISSUE TITLE
Velas burning themselves

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#3447]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Happens on Linux, Windows and Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

114.2

**Issue**: *Explain your issue in detail.*

Vela firing and its laser beam damaging any enemy building will burn the vela.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. Make a vela
2. Take control of the vela
3. Attack an enemy building
4. See that not only the enemy buildings are burning, but the vela too.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[vela burn.zip](https://github.com/Anuken/Mindustry/files/5560314/vela.burn.zip) (this is from one of the devices used for testing)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
@genNAow *you did this*

**Comment by QmelZ** [comment]
also just figured out, (probably related), meltdowns burn themselves too

**Comment by genNAowl** [comment]
Sorry
