### ISSUE TITLE
Notification bar covers ui at top of screen

### ISSUE THREAD

**Issue by camerondeano** [Anuken/Mindustry#3450]
**Platform**: Android

**Build**: 104.6
**Issue**: notification bar persists at the top of the screen covering the user interface.

**Steps to reproduce**: any notification causes this to happen. If the notification bar appears it just doesn't go away. I don't really have to do anything to make it happen

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: happens on the main menu before have starts.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen on any of my Android devices. Won't fix.

**Comment by Legomonster33** [comment]
sounds like a issue with your device. @camerondeano

**Comment by camerondeano** [comment]
Yeah. I tried going to Google support but you know how it goes. They blame you, you blame them. Oh well. I'll just keep resetting my game I guess.

**Comment by DeltaNedas** [comment]
thank you android the biggest cuck licensed, standardless operating system
