### ISSUE TITLE
Load proving too much for older GPUs

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3457]
**Platform**: *Anything old*

**Build**: *105+ (current 114.2)*

**Issue**: *Mindustry relies quite heavily on GPU, and I have so far experienced multiple issues, crashes, etc. related to the 6.0 load on GPUs.*

**Steps to reproduce**: *Try to play large, heavily developed maps/load mods on an older device.* **DO NOT ATTEMPT THIS ON YOUR SNAZZY NEW DEVICES, AS THIS ONLY APPLIES TO OLDER/CHEAPER/LOWER QUALITY DEVICES.** (shows more on iOS due to the painfully weak GPUs in them)

**Testing Device(s)**: *Apple iPod Touch 6, Samsung Galaxy Tab 4 7.0*

**Link(s) to mod(s) used**: *how do I link all the 6.0 mods in existence again...? Optional, and an important thing to test.*

**Save file**: *null*

**Crash report**: *The crashes leave no logs.*

**Possible fix**: *Make Mindustry visually render in chunks or only in the range of the players' view but make the entire map handled (invisibly) by the CPU. Or optimize graphics for the game, though both these options may be impossible to implement.*
  come to think of it, the first option would make fire less laggy 🤔 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not really searched the closed and open issues to make sure that this problem has not already been reported, but I have made previous issues like this one that did not fix this issue.**

**Comment by Anuken** [comment]
> Make Mindustry visually render in chunks

Already does.

> or only in the range of the players' view

Already does.

> but make the entire map handled (invisibly) by the CPU

Already is, where graphics aren't concerned.

> Or optimize graphics for the game

Already did.

---

Look at the source code before you make optimization tips. Nearly every single person who has suggested optimizations to me has had *no idea what they're talking about*, and that includes you. "Optimize the game" is an incredibly vague statement that cannot be acted upon.

---

Quite frankly, expecting a massive factory-simulation game with so many different mechanics to run on weak **mobile devices** is unreasonable. I'm not a AAA developer (*or even a small indie studio*), I'm not an expert in any of the numerous topics that are needed for this level of optimization, I can't afford to support every single crappy device out there, and the game is written ***in Java***. Fix it yourself, or get a better device.
