### ISSUE TITLE
Fungal pass gets attacked with 0 waves

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3459]
**Platform**: *Windows*

**Build**: *114.1*

**Issue**: *Fungal pass will occasionally get attacked, but when you enter the sector it says "sector captured" next to the health bar*

**Steps to reproduce**: *Play campaign, wait for fungal pass to get attacked, and enter it. Alternatively, load the save I conveniently made just a few seconds after fungal pass got attacked, where it still says "under attack" until you enter it.*

**Save file**: *[Data.zip](https://github.com/Anuken/Mindustry/files/5563546/Data.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

It is ***NOT*** fixed like you said last time I tried to report this. Just load the damn save and see for yourself.

**Comment by Anuken** [comment]
Can't fix this. Your save doesn't have any enemy spawners, so there are no waves. Why? Probably because of a bug in 114.1. When I defeat the sector myself, it *has* spawners. Update your game to 114.2.
