### ISSUE TITLE
App keeps running and playing music in background on Android

### ISSUE THREAD

**Issue by 6zow** [Anuken/Mindustry#3460]
**Platform**: Android

**Build**: Beta 114.2

**Issue**: When the game is in background, it keeps playing music.

**Steps to reproduce**: Open the game (main menu screen), put the app in background or even "exit" by pressing the "back" button. The music keeps playing in both cases, sometimes distorted. Pressing the "Quit" button in the main menu stops the music.

**Link(s) to mod(s) used**: No mods

**Save file**: The issue happens even on the menu screen without starting the campaign or custom game.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

Right, so you found the other 3-5 times It was reported?

**Comment by 6zow** [comment]
> > I have searched the closed and open issues to make sure that this problem has not already been reported.
> 
> Right, so you found the other 3-5 times It was reported?

Your sarcastic replies are not helpful. Links to duplicates would be.

I could find only 2 similar reports. Both contain less details than mine and were closed as "likely fixed" about a week before build 114, yet the issue is still there (assuming it's the same issue). Am I missing something obvious?

**Comment by Anuken** [comment]
Doesn't happen on my devices, won't fix.

**Comment by RogueRedHawk** [comment]
It happens to me on beta 114.2. My Android game continues to run in the background, and the music persists, sometimes distorted. It goes on indefinitely. This is a new issue with 114 that I haven't experienced before. It happens everytime I exit the game while on the menu screen, as well as in game. To be clear, all game audio continues to play.
