### ISSUE TITLE
Modded sector icons are oh no

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3464]
**Platform**: Android 9

**Build**: 11373

**Issue**:
Routorio's "router" icon is oh no when selected.
This worked before #3453 was tested

**Steps to reproduce**:
1. edit icon for sector
2. select router icon
![2](https://user-images.githubusercontent.com/39013340/99698264-7adaa380-2a88-11eb-8a01-5fa2331579dd.jpg)
3. oh no
![3](https://user-images.githubusercontent.com/39013340/99698280-8037ee00-2a88-11eb-9ecb-97c0bfec1273.jpg)

**Link(s) to mod(s) used**: deltanedas/routorio
```js
Events.on(ClientLoadEvent, () => {
    const router = Core.atlas.find("routorio-white-router");
    Icon.icons.put("router", new TextureRegionDrawable(router));
});
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Frankly, I don't care, this is not supported modding API.

**Comment by DeltaNedas** [comment]
oh dont tell me its because it needs routerSmall or something

**Comment by Anuken** [comment]
No, it uses a special font & glyphs for icons now, so putting images in `Icons.icons` doesn't work.

**Comment by DeltaNedas** [comment]
should i Fonts.iconLarge.data.setGlyph(Iconc.whatever + 1, coolGlyph)

**Comment by Anuken** [comment]
that sounds unlikely to work

**Comment by sk7725** [comment]
Just PR a router icon, the game needs more routers
