### ISSUE TITLE
double-tapping player icon does nothing

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3465]
**Platform**: Android 9

**Build**: 11373

**Issue**:
Double-tapping player icon doesn't make me respawn.

**Steps to reproduce**:
Above, tried:
- in campaign
- in sandbox
while paused and not.

**Save file**: ui bug

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have to be controlling something that isn't the default unit to respawn.
Double-tapping is unnecessary, you only need to do it once.

**Comment by Legomonster33** [comment]
> You have to be controlling something that isn't the default unit to respawn.

would be cool if you could respawn at anytime (the popup saying press v to respawn wouldn't need to show all the time tho)

~~#suggestions~~
