### ISSUE TITLE
package name error

### ISSUE THREAD

**Issue by arakido** [Anuken/Mindustry#347]
I can't find the package“io.anuke.mindustry.gen”

![5tdb 2uqmjbt9kw5d2u cf7](https://user-images.githubusercontent.com/38557531/48820932-0d5ce500-ed92-11e8-8431-23d8efda0a22.png)

**Comment by TheChosenEvilOne** [comment]
gen stands for generated and is only generated during compiling or if you set your IDE to do annotation processing

**Comment by Timmeey86** [comment]
Follow this guide in order to successfully run/debug the game. The compile button won't work, but the 
Run and debug one will.
https://www.github.com/Timmeey86/Mindustry/wiki/How-to-compile-Mindustry-step-by-step#compiling-the-code

**Comment by Anuken** [comment]
As mentioned above, these are generated packages. Follow the guide to get them to work.
