### ISSUE TITLE
Currently, the v6 campaign is uncompletable.

### ISSUE THREAD

**Issue by Cobbet2** [Anuken/Mindustry#3478]
**Platform**: Windows

**Build**: 11414

**Issue**: Campaign is uncompletable because of a bug preventing from researching the final sectors and the overdrive projectors. To unlock impact 0078 you need to research overdrive projector. But to research the overdrvie projector, you need to capture impact 0078. Infinite loop.

**Steps to reproduce**: Attempt to complete campaign. Capture tar fields and this will happen.

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by QmelZ** [comment]
You don't have to unlock impact 0078 to capture it, doesn't seem like a bug to me. Not sure though.

**Comment by Cobbet2** [comment]
> You don't have to unlock impact 0078 to capture it, doesn't seem like a bug to me. Not sure though.

how... are you going to capture it without unlocking it?

**Comment by BasedUser** [comment]
by launching to every sector leading up to it

**Comment by Cobbet2** [comment]
Well it is completable, but the loop still exists.

**Comment by QmelZ** [comment]
> Well it is completable, but the loop still exists.

loop still exists so it might be a bug, that's why i said "not sure though"

**Comment by qwerturt** [comment]
Well I researched literally everything in earlier versions so idk if this really matters the gameplay
