### ISSUE TITLE
fix the recognition of waves you are in when you enter a sector under attack.

### ISSUE THREAD

**Issue by Muffin-Afk** [Anuken/Mindustry#3479]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
steam build 115
**Issue**: *Explain your issue in detail.*
Basically I entered the low sector at tack in round 137/140 and at that moment this bug was made in the game, something that would not have to happen but it happened, and half a laugh because you are in round 140/140 and the boss comes out in 142 in a few words it is as if it were something similar to real life XD.

![Sin título](https://user-images.githubusercontent.com/74759015/99768631-dc7c2b80-2ae3-11eb-8190-43bb47d7b9d3.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
