### ISSUE TITLE
Having no audio devices on your PC causes the game to close during startup.

### ISSUE THREAD

**Issue by FlamesWillLive** [Anuken/Mindustry#3480]
**Platform**: Windows

**Build**: Steam Build 115

**Issue**: Having no audio devices on your PC causes the game to close during startup.

**Steps to reproduce**: Have no Audio Devices enabled on your PC. Boot game. Plugging in headphones fixes the issue, and the game continues as normal.

**Save file**: Irrelevant I believe. The only saves I'd have is campaign, and It happens during start up.

**Crash report**: https://pastebin.com/gBeRi77J

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed

**Comment by e673** [comment]
Same problem appears on Linux.

```
[E] Failed to initialize audio, disabling sound: arc.util.ArcRuntimeException: Other error
        at arc.audio.Soloud.init(Native Method)
        at arc.audio.Audio.initialize(Audio.java:33)
        at arc.audio.Audio.<init>(Audio.java:23)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:36)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

In my case, installing package `pulseaudio-alsa` solves the problem.
But without reading release notes (switching to ALSA) it is not obvious.

**Comment by l29ah** [comment]
I get this error message and no sound even though my system is using ALSA.
