### ISSUE TITLE
latest bleeding edge version is 9

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3481]
**Platform**: `*`

**Build**: [`latest`](https://api.github.com/repos/Anuken/MindustryBuilds/releases/latest)

**Issue**: `the latest link currently doesn't return the latest release listed visually`

**Steps to reproduce**: `try to use & debug autoupdate and notice it returns one lower from the list`

![Screen Shot 2020-11-20 at 10 44 45](https://user-images.githubusercontent.com/3179271/99785435-701e1e00-2b1d-11eb-85f3-e4cd13f20c8b.png)

![Screen Shot 2020-11-20 at 10 43 22](https://user-images.githubusercontent.com/3179271/99785261-3a793500-2b1d-11eb-8bfe-f4fa61663ba2.png)

> probably fixable by releasing a new bleeding edge build, but still worth giving some attention ^

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this pwoblem has not already been reported.**

**Comment by Anuken** [comment]
I can't really fix this; with the new CI builds reset their IDs.
