### ISSUE TITLE
squashed unit emojis in reconstructors

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3484]
**Platform**: `mac`

**Build**: `11414`

**Issue**: `the icons of some units in the reconstructor bar look squised`

**Steps to reproduce**: `try to make a corvus`

![Screen Shot 2020-11-20 at 10 59 40](https://user-images.githubusercontent.com/3179271/99787249-cc823d00-2b1f-11eb-8f3f-736130926d23.png)
![Screen Shot 2020-11-20 at 10 59 47](https://user-images.githubusercontent.com/3179271/99787252-ce4c0080-2b1f-11eb-9fb6-75dbb09ac3ae.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this feature has not already been reported.**

**Comment by Bohaska** [comment]
Wrong problem. The icons in reconstructors are stretched, not that the icons in core database are squashed.
