### ISSUE TITLE
tile.setFloorNet(<liquid>) not updating visually

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3488]
**Platform**: `mac`

**Build**: `11414`

**Issue**: `the tar floor doesn't show until the user uses /sync:`

(doesn't seem to work when replacing both ground & other liquids)

**Steps to reproduce**: `tried to make server sided oil spills in the puddle class:`

```
                p.lastRipple(Time.time());

//                if(tile.floor().liquidDrop == Liquids.water){
                    tile.setFloorNet(Blocks.tar);
//                }
```

(minimap does in fact show the update, so is at least received by the clients, its just not re-rendering the floor)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this pr oil blem has not already been refined.**

**Comment by Anuken** [comment]
Automatic updating of floors is disabled indefinitely. It cause massive memory usage problems on low-end devices even when updates didn't occur.

**Comment by Quezler** [comment]
ah, unfortunate to hear, gotta scrap some ideas then 😓 

should/shall i make a pull request to remove all references to `setFloorNet` since you've mentioned `indefinitely` ?
