### ISSUE TITLE
[Android] Could add Instruction for build android apk?

### ISSUE THREAD

**Issue by wade-fs** [Anuken/Mindustry#349]
In my construction process for building apk....
1) add local.properties in project root dir as following:
ndk.dir=WHERE-Android-Ndk/                                                                                                                                
sdk.dir=WHERE-Android-Sdk
2) modified android/build.gradle, patch as:
<PRE>
@@ -1,3 +1,10 @@                                                                                                                                                         
+ext {                                                                                                                                                                   
+    RELEASE_STORE_FILE = "WHERE-ANDROID-APK-KEYSTORE-FILE"
+    RELEASE_STORE_PASSWORD = "WHAT THE PASSWORD FOR KEYSTORE"
+    RELEASE_KEY_ALIAS = "WHAT THE KEY ALIAS"
+    RELEASE_KEY_PASSWORD = "WHAT THE PASSWORD FOR KEY"
+}
+
</PRE>
3) and then run following cmd to see task for android:
./gradlew :android:tasks
4) pick up a build task, such as "build' or "bundleGoogle" as:
./gradlew :android:build
./gradlew :android:bundleGoogle

**Comment by islq** [comment]
don't need to modifiy android/build.gradle

**Comment by Anuken** [comment]
The manifest info variables should be defined in your `local.properties`, not edited into the Gradle file.

e.g. `RELEASE_STORE_PASSWORD=password`
