### ISSUE TITLE
Payload conveyors carrying scepters

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#3492]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Linux and Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Beta 115

**Issue**: *Explain your issue in detail.*

Payload conveyors can carry scepters. (Only happens with scepters, no other t4 units.)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. Construct a scepter
2. While constructing, put a payload conveyor on the output part of the exponential reconstructor
3. See the payload conveyor carrying the scepter
![16-11_1](https://user-images.githubusercontent.com/59574967/99812379-7204d300-2b57-11eb-9c17-b35f57e10cb6.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

Used a clean save, reproduced the bug after a data reset. I don't think this is needed.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

No crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Their hitbox is small enough for that.

**Comment by QmelZ** [comment]
fair enough, i thought anything above tier 3 couldn't be carried.
