### ISSUE TITLE
Data export crash

### ISSUE THREAD

**Issue by Vensere** [Anuken/Mindustry#3495]
Platform: Android 9

Build: beta 114

Issue: Game crashes when i try to export save/crash log data (file r/w permission is given to app)

No mods used

Crash report: I cant export crash data aswell

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Update.
