### ISSUE TITLE
Overgrowth not captureable after attacked for the second time?

### ISSUE THREAD

**Issue by Cobbet2** [Anuken/Mindustry#3496]
**Platform**: Windows

**Build**: 11414

**Issue**: After Overgrowth is captured for the first time by destroying the core, and attacked after that, there is no "x out of y waves" at top left, only the number of the current wave (like before v6)

**Steps to reproduce**: Capture overgrowth by destroying the core. Wait for it to be attacked again.

**Link(s) to mod(s) used**: No mods.

**Save file**: Sorry, no save file.

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen to me, and you haven't attached a save.
