### ISSUE TITLE
unit does not use modded constructor when loading save

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3497]
**Platform**: Android 9

**Build**: 11414

**Issue**:
For some reason `unit.warp` (function defined in constructor) is undefined when loading a save.
When an ability is updated it has a stroke and uses a vanilla entity class, causing it to crash.

**Steps to reproduce**:
1. install mod
2. load save
3. crash

**Link(s) to mod(s) used**: deltanedas/anuke-logic
Script is at **scripts/units/messenger.js**.
`warp` is clearly defined, but the constructor doesnt appear to be used.

**Save file**: [sector-serpulo-75.msav.txt](https://github.com/Anuken/Mindustry/files/5575990/sector-serpulo-75.msav.txt)

**Crash report**: 
[crash_1605904758887.txt](https://github.com/Anuken/Mindustry/files/5575994/crash_1605904758887.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Because you need to register unit types.

**Comment by DeltaNedas** [comment]
yes how

**Comment by Anuken** [comment]
Don't.

**Comment by DeltaNedas** [comment]
aaannnuuukkkeee

**Comment by Anuken** [comment]
Trying to do it now would mean using unsupported API and generated code, which is guaranteed to break in the future.

**Comment by DeltaNedas** [comment]
that's fine by me
does it involve `EntityMapping.nameMap.put("anuke-logic-messenger", mess.constructor);` ?

**Comment by sk7725** [comment]
I managed to pull it off, but it must be outdated by now

**Comment by GlennFolker** [comment]
Yes, I use EntityMapping.put blah blah and stuff

**Comment by DeltaNedas** [comment]
please reopen, "dont use units lol" isn't a fix

**Comment by Anuken** [comment]
Just don't. It doesn't work and it's not supposed to work.

**Comment by DeltaNedas** [comment]
Here's my registry script from routorio:
```js
/* Registers a unit's class for I/O stuff (saves and net)
   Requires unit.constructor.get() to have classId: () => unit.classId */
module.exports = unit => {
	// Register unit's name
	EntityMapping.nameMap.put(unit.name, unit.constructor);

	// Find available class id and register it
	unit.classId = -1;
	for (var i in EntityMapping.idMap) {
		if (!EntityMapping.idMap[i]) {
			EntityMapping.idMap[i] = unit.constructor;
			unit.classId = i;
			return;
		}
	}

	// Incase you used up all 256 class ids; use the same code for ~250 units you idiot.
	throw new IllegalArgumentException(unit.name + " has no class ID");
};
```

**Comment by Anuken** [comment]
If you install a mod that uses unit ID 100, then install another mod that happens to add units before that one, your new unit ID will become 101+, breaking previous saves permanently. Adding, removing or changing initialization order of units will have the same effect.

**Comment by DeltaNedas** [comment]
geez anuke i guess you could add a unit registry for saves so that this isnt needed
