### ISSUE TITLE
player rubber banding

### ISSUE THREAD

**Issue by Nhimanss** [Anuken/Mindustry#3498]
**Platform**: linux
**Build**:20017

**Issue**: player will teleport back into place when trying to move
occurs in v5 when ping is low
occurs now even at 100ms ping
**Steps to reproduce**: attempt to fly forward

**Link(s) to mod(s) used**: none
**Save file**: happens in any multiplayer game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen to me, even with 100ms+ servers.

**Comment by Nhimanss** [comment]
it might be platform specific

**Comment by Anuken** [comment]
Unlikely, and I'm using Linux.

**Comment by Nhimanss** [comment]
nvm it seems to accur at 200 ping

**Comment by Nhimanss** [comment]
@Anuken it only started happening with recent versions

**Comment by Anuken** [comment]
Previous versions had a bug where the server didn't send clients their correct positions. The problem wasn't as visible, but it was still there.

**Comment by Nhimanss** [comment]
the issue seems to be back from the old versions

**Comment by Nhimanss** [comment]
my player will fly forward and teleport back to where they were in a loop

**Comment by Nhimanss** [comment]
causing a jittering effect

**Comment by Nhimanss** [comment]
seems to start and stop happening randomly

**Comment by Quezler** [comment]
have also had this happen in the recent builds of the last few days, not sure before that since i took a long break

**Comment by Nhimanss** [comment]
would it be good to locate the exact build number the change occured

**Comment by Nhimanss** [comment]
it happened somewhere between 11365-11414

**Comment by Nhimanss** [comment]
@Quezler what can I do now?

**Comment by Nhimanss** [comment]
* what do i do

**Comment by Quezler** [comment]
letting me sleep

**Comment by Nhimanss** [comment]
ok
