### ISSUE TITLE
Joining someone's multiplayer campaign overwrites personal campaign progress (v6)

### ISSUE THREAD

**Issue by Admiral-Billy** [Anuken/Mindustry#3499]
**Platform**: Windows

**Build**: 115

**Issue**: If you join a multiplayer campaign game in 6.0, your campaign's sectors will be replaced by the host's; i.e. I go to ground zero and build something, then join a friend who builds something else, my singleplayer campaign's ground zero will *also* be whatever my friend's sector is. I think a related issue here is that when you view the sector map as a client, it shows your own sectors instead of the host's, as if it never changed.

**Steps to reproduce**: Simply join any multiplayer campaign game after making singleplayer progress in the same sector.

**Link(s) to mod(s) used**: N/A

**Save file**: [backup.zip](https://github.com/Anuken/Mindustry/files/5576931/backup.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.

> I think a related issue here is that when you view the sector map as a client, it shows your own sectors instead of the host's, as if it never changed.

That's not an issue. The host does not send their maps to clients, they are completely separate.

**Comment by Admiral-Billy** [comment]
Thanks for the fast response! You're awesome!

> That's not an issue. The host does not send their maps to clients, they are completely separate.

Fair enough, I wasn't sure what *is* and *isn't* supposed to be sent in multiplayer.
