### ISSUE TITLE
Core never gets full (sorta)

### ISSUE THREAD

**Issue by Draco18s** [Anuken/Mindustry#3500]
**Platform**: Windows

**Build**: 115

**Issue**: When conveyors push resources into the core, if the core is full, the resources just sort of evaporate. This makes *overflow gates* completely useless for detecting if the core is full to capacity on a given line. This changed sometime between 110 and 115 (I did not play all versions between those two and know that 110 things were fine and then later--after 112? by 114?--they weren't).

If this was an *intentional* change, it wasn't in the changelog.

**Steps to reproduce**: Make core full. Then push more resources in.

**Link(s) to mod(s) used**: None

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5577074/saves.zip)

Should be able to load into any (conquered) sector and find a core that's full to capacity (of at least one resource) and resources will still flow into it giving off little puffs of smoke. The smoke effect makes me think the change was intentional, but undocumented.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
I did search but "core gets full and resources evaporate" has a bunch of false positives.

**Comment by ThisIsACoolBoy** [comment]
i don't know if this is necessarily a bug but this is kinda normal, it's used maybe for not overloading the core

**Comment by D-player1** [comment]
This is already a feature from the game itself

**Comment by D-player1** [comment]
Plus
> If this was an intentional change, it wasn't in the changelog.

![IMG_20201121_124210](https://user-images.githubusercontent.com/70744599/99868671-0eca7d80-2bf7-11eb-9d06-206ef3f1c6da.jpg)
Already exists since build 108

**Comment by sk7725** [comment]
While it is a feature, overflow filters *should* be able to detect whether a core is full.

Still, you can hook up a processor to the core to do that.

**Comment by Draco18s** [comment]
@D-player1 huh, the change is older than I thought it was. Thanks for locating that.

**Comment by DeltaNedas** [comment]
yes so close it

**Comment by Esnardo** [comment]
This is an intentional change. It's so that the game can accurately determine how many resources a sector is making while afk. If you need overflowing for something, use a processor. The code to make a "smart" overflow gate is something you should always learn, it's just so useful.

**Comment by Draco18s** [comment]
@Esnardo Processors are great, the problem with a smart-overflow program is that you need to know what resource is flowing down a given line (because 'total items' in the core is insufficient, so you have to ask "how much glass is there?" and then turn off the line that brings in your glass. Oops you reconfigured your lines and now your processors are turning off the wrong line).
