### ISSUE TITLE
Joining a multiplayer campaign game messes up your personal campaign progress

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3501]
**Platform**: *Android/iOS/Mac/Windows/Linux* widnows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 115

**Issue**: *Explain your issue in detail.*
when joining a multiplayer camapgin game then going back to your personal one, the global items stick around from the multiplayer.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. join multiplayer campaign game
2. do stuff
3. leave
4. go to your own campaign
5. you now have items that you didnt make.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
n/a

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
(holdup its like 500 mb and taking forever to upload i will add when its uploaded)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
n/a
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
i will add save file when it finishes uploading

**Comment by Gdeft** [comment]
Similar to #3499?

**Comment by Legomonster33** [comment]
> Similar to #3499?

simmilar but a bit different

**Comment by Legomonster33** [comment]
ok nvm upon further review its the same issue
