### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by CecilakCZ** [Anuken/Mindustry#3505]
i cant see the map it just disapeard and now i cant do stuff there

![Screenshot_20201121_110957_io anuke mindustry](https://user-images.githubusercontent.com/74816806/99874909-b80b7680-2beb-11eb-99eb-5b41a03f9b56.jpg)

**Comment by l-Luna** [comment]
which map is this? what version?

**Comment by CecilakCZ** [comment]
The new version and craters

**Comment by Anuken** [comment]
Template.
