### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vertix8** [Anuken/Mindustry#3509]
**Platform**: Android

**Build**: 115

**Issue**: when I put pipelines sometimes message blocks are put fix this bug please

**Steps to reproduce**:I just build titans conveyor

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
sounds like you need to update since a new block got added, it messes up communication between client and server

**Comment by DeltaNedas** [comment]
doesnt matter, he was executed by the cia while filling out the template.
