### ISSUE TITLE
Plastianium conveyors have multiple visual errors when next to other conveyors

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry#3512]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
BE 20018

**Issue**: *Explain your issue in detail.*
When placing plastanium conveyors next to other conveyors, the plast conveyor texture appears to connect but no items are transferred.
![image](https://user-images.githubusercontent.com/57631841/99880996-38939c80-2c17-11eb-8eef-d2117427a1d8.png)
Once with titanium and once with armoured, and then the whole thing with items to show that no items are being transferred.
Here's a video showing how to make the 2nd from the right, as that seems to be lost whenever you reload the save (sorry for bad quality):
[video.zip](https://github.com/Anuken/Mindustry/files/5577883/video.zip)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I saw the issue on a server, to reproduce just place the conveyors as shown in the screenshot and video (or load the save and see the video).

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The save file you were playing on when the bug happened. 
[save.zip](https://github.com/Anuken/Mindustry/files/5577886/save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not fixing this. The code is already a mess.

**Comment by Quezler** [comment]
related: https://github.com/Anuken/Mindustry-Suggestions/issues/1274
