### ISSUE TITLE
Bullets moving too fast to actually hit anything

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3514]
**Platform**: Windows

**Build**: Steam 115

**Issue**: Bullets that travel really fast, such as Omura's railgun bullets, tend to "skip over" smaller units/blocks, passing through them without dealing damage. A single Toxopid could be completely safe from the fast projectiles even if targeted.

**Steps to reproduce**: As I was defending Planetary Launch Terminal after capturing it, I noticed that the Omuras I built aren't hitting units they were firing at; even smaller units like Spirocts were completely unaffected by the bullets. This eventually led to me losing the sector to the Guardian Toxopid that spawned in, as the Omuras constantly whiffed against it as the bullets flew "through" the Guardian as if "hopping over" it. The Toxopid proceeded to crawl past my defenses and made it all the way to my core.

**Link(s) to mod(s) used**: None apply

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/5577958/saves.zip)

**Crash report**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen to me. Even at 30FPS, I can consistently hit a Toxopid while moving. Every block I shoot at gets hit, even if it's 1x1 and has a pattern of 1-block spacing in the line of fire. Bullets already sweep their hitboxes when checking for collisions, so speed shouldn't matter.

**Comment by z0mbiesrock** [comment]
> Bullets already sweep their hitboxes when checking for collisions, so speed shouldn't matter.

_bruh_
Apparently it doesn't happen when the bullet is visibly on screen...

**Comment by z0mbiesrock** [comment]
![image](https://user-images.githubusercontent.com/19158169/99884301-39b6d080-2bfb-11eb-92e9-c231870ce24a.png)

**Comment by Anuken** [comment]
That doesn't happen to me, but that bullet type is bad [for plenty of other reasons](https://github.com/Anuken/Mindustry/blob/1ef264d5607023436ae79c0621822c26f6962905/core/src/mindustry/entities/bullet/RailBulletType.java#L7), so I might as well replace it.
