### ISSUE TITLE
sound problem

### ISSUE THREAD

**Issue by Maxter-1** [Anuken/Mindustry#3515]
On Android, the game sound is heard after the game is played. You have to either completely turn off the game or turn off the sound. 
P. S version of the game beta 150.

**Comment by Anuken** [comment]
There is no such version.

**Comment by Maxter-1** [comment]
that is beta 115

**Comment by DeltaNedas** [comment]
use the template
in it it asks you to check for duplicates, which exist

**Comment by Maxter-1** [comment]
What do you mean by "duplicates"?

**Comment by Legomonster33** [comment]
> What do you mean by "duplicates"?

reports of the same issue

**Comment by Maxter-1** [comment]
that is, to make a new issue on the same topic?
