### ISSUE TITLE
You can re-enter a lost sector without launching

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3517]
**Platform**: *Windows*

**Build**: *115*

**Issue**: *If you lose a sector, you can re-enter it. Time will be frozen, and you can't unpause it, but you can look around and edit configurable blocks like unloaders and sorters.*

**Steps to reproduce**: 
*1. Lose a sector
2. Immediately click the button to "launch" back to that sector*

**Save file**: *[Data.zip](https://github.com/Anuken/Mindustry/files/5578130/Data.zip) (bug is in the red sector above ruinous shores, IIRC*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
