### ISSUE TITLE
Long item requirements of a block break the build menu

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#3518]
**Platform**: *Android/iOS/Mac/Windows/Linux*
linux
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 115
**Issue**: *Explain your issue in detail.*
#3422 but it happens with the item requirements of a block
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. put down a block which needs huge amounts of more than 3 items (interplanetary accelerator as a vanilla example)
2. hover over it
3. see how it seperates the build menu
![21-11_1](https://user-images.githubusercontent.com/59574967/99884822-f9c70c00-2c41-11eb-9dc0-aecef2e40d82.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

i dont think this is needed

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

no crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
