### ISSUE TITLE
pvp mode for headless server not work

### ISSUE THREAD

**Issue by islq** [Anuken/Mindustry#352]
only the first player can move

**Comment by islq** [comment]
When playerGroup.count called more than 1 time in isWaitingForPlayers(), it will overwrite the iterator of the for loop in Entities.update(playerGroup)
Is this change reasonable?
https://github.com/Anuken/uCore/pull/19

**Comment by Anuken** [comment]
Fixed in 942eed402ab35b467cf884140560aa4e0f4256f6
