### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by ZelenBr** [Anuken/Mindustry#3520]
Platform: Windows

Build: 115

Issue: I'm played on server and game crashed. Before this i tried to contorol arkyid many times but always back to the own ship.

No mods used

Save file: 
[save.zip](https://github.com/Anuken/Mindustry/files/5578310/save.zip)

Crash report:
[crash-report-11_21_2020_22_46_06.txt](https://github.com/Anuken/Mindustry/files/5578291/crash-report-11_21_2020_22_46_06.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ILiekMelons** [comment]
you say no mods used but your logs say 4 mods 👀

**Comment by ZelenBr** [comment]
> you say no mods used but your logs say 4 mods 👀

this mods don't used because *Not compatible with V6*

**Comment by Anuken** [comment]
You are playing on an incompatible server.
