### ISSUE TITLE
interplanetary accelerator item bar.

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3521]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
beta 115

**Issue**: *Explain your issue in detail.*
the item fill bar will reach the end long before it is full of material

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. make an accelerator
2. fill it up
3. bar reaches end before its full

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
n/a

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
graphical issue so here are some photos
![image](https://user-images.githubusercontent.com/54417042/99897033-f47ab900-2c63-11eb-82d9-2df5c5e98976.png)
![image](https://user-images.githubusercontent.com/54417042/99897043-0a887980-2c64-11eb-9761-b410ea226e3b.png)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
n/a
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have ~~'nt~~ searched the closed and open issues to make sure that this problem has not already been reported.**

I would presume this happens with modded things that store large amounts of items aswell.

**Comment by BlueWolf3682** [comment]
this is due to blocks having a default 2x buffer, and items not displaying over/beside each other in layers
