### ISSUE TITLE
Blocked enemy ground unit paths

### ISSUE THREAD

**Issue by a3skales** [Anuken/Mindustry#3523]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 64-bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Beta 115

**Issue**: *Explain your issue in detail.*
In the enemy base adjacent to Frozen Forest, the enemy ground units can't make their way to my base, so crowd right beside the enemy cores. I got to the point where there was over 1,000 enemies all just waiting beside the enemy cores. They do this because the AI builds in such a way that their paths end up completely blocked. This has happened a couple times.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Simply go into the enemy base sector adjacent to Frozen Forest (Sector 214), then wait. You'll eventually see that the ground enemies don't come towards the core because their paths are blocked.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods used.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[Mindustry Save.zip](https://github.com/Anuken/Mindustry/files/5579499/Mindustry.Save.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
