### ISSUE TITLE
Plastanium conveyors bug

### ISSUE THREAD

**Issue by ZelenBr** [Anuken/Mindustry#3525]
Platform: Windows

Build: 115

Issue: Half of resources in a batch on plast conveyors can't pass through sorters

Steps to reproduce: Place vault, sorters, plast conveyors like on screenshot and some input things.
![image](https://user-images.githubusercontent.com/60311526/99906098-19b00b80-2ce6-11eb-9537-0de3b2369feb.png)

Link(s) to mod(s) used: no mods

Save file:
[save.zip](https://github.com/Anuken/Mindustry/files/5579617/save.zip)

Crash report: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
remove the one with graphite by hand and replace it, since it likely occurred during building or deconstruction

**Comment by ZelenBr** [comment]
also batches can't enter the vault
![image](https://user-images.githubusercontent.com/60311526/99906720-af996580-2ce9-11eb-9186-84431e3ae209.png)

**Comment by Quezler** [comment]
rotate the conveyor from facing `upwards` to facing to the `left`: https://github.com/Anuken/Mindustry-Suggestions/issues/1274

**Comment by Anuken** [comment]
> Save file:

What do you expect me to do with your entire data folder? The issue template asks for **the save you were playing on**.

> Half of resources in a batch on plast conveyors can't pass through sorters

They can, you just haven't read the conveyor description and don't understand how they work.

> also batches can't enter the vault

Because it's not an unloading dock.
