### ISSUE TITLE
Pick Block should trigger only on keydown

### ISSUE THREAD

**Issue by SomeKittens** [Anuken/Mindustry#3528]
**Platform**: Windows

**Build**: Steam Build 104.10

**Issue**: The "Pick Block" functionality triggers on both keydown and keyup.

**Steps to reproduce**: Rebind Pick Block to a key on the keyboard (I used `Q`).  Pressing the key does pick the block under the cursor!  But it _also_ triggers again on keyup, which is a problem when I've already started moving the mouse cursor to where I wanted to place the block I've picked.  This means I often pick the block adjacent to the block I wanted to pick.

**Link(s) to mod(s) used**: N/A (running vanilla version)

**Save file**: Happens consistently regardless of level or save.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
