### ISSUE TITLE
Campaign sector progress deleted

### ISSUE THREAD

**Issue by Liftyee** [Anuken/Mindustry#3529]
**Platform**: *Linux*
Ubuntu 18.04

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
alpha build 1-5

**Issue**: *Explain your issue in detail.*
I played in a sector bottom left of Ground Zero and captured it. At some point (I don't remember exactly when) the 'Saving...' text appeared at the bottom of the screen and stayed there. After afking for a while and unlocking some of the tech tree I clicked 'save and quit' to leave the game, and after I come back it was as if I had never visited that sector before. Ground Zero still looked the same, and my tech tree progress was still there but that sector appeared locked.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Play sector
If 'saving...' text appears on bottom screen and doesn't leave 
'Save and quit'
progress in that sector is deleted but tech tree is still kept

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[broken.zip](https://github.com/Anuken/Mindustry/files/5579759/broken.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Can't reproduce. Your save file doesn't have any helpful information, and without logs or output I can't tell what went wrong.

> alpha build 1-5

No such build exists. There is a *build 115*, but it's not an *alpha* build.

**Comment by Liftyee** [comment]
rip, i'll do it again i guess
also if this helps a savefile for that sector exists in the /snap/mindustry/saves directory

and I meant build 105

**Comment by Anuken** [comment]
Don't play build 105, that's almost a month old and extremely outdated.

**Comment by DeltaNedas** [comment]
also dont use snap, thats why your progress isnt saving.
only compile mindustry or get it from itch.io/github/steam, not amazon spyware store.
