### ISSUE TITLE
Can't access servers

### ISSUE THREAD

**Issue by nicowo-621** [Anuken/Mindustry#3530]
**Platform**: android

**Build**: beta 112

**Issue**: For some reason I can't access any servers, and I just lived with this issue For a long time (don't ask me why I didn't report the bug earlier) the servers just straight up don't show even if they are online

**Steps to reproduce**: I don't know

**Link(s) to mod(s) used**: none

**Save file**: unavailable, sorry about that

**Comment by Anuken** [comment]
Update your game.
