### ISSUE TITLE
crash with cyclone and phase wall

### ISSUE THREAD

**Issue by kotok9** [Anuken/Mindustry#3534]
OS: Windows 10 x64

Version: beta build 115

Game crashes when cyclone is shooting phase wall and cyclone breaks from phase wall when builder units try to rebuild cyclone
[crash-report-11_22_2020_23_59_19.txt](https://github.com/Anuken/Mindustry/files/5580099/crash-report-11_22_2020_23_59_19.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
