### ISSUE TITLE
insane difficulty

### ISSUE THREAD

**Issue by suprainfinite** [Anuken/Mindustry#3543]
**Platform**: *Windows*

**Build**: *6.0 116*

**Issue**: *the diffculty was quite hight at thebegin, but at with the 116, the difficulty is insane, some sector have a guardian at wave 5, and the guardian is not a T4, it's a T5, so even by abusing with pause and have infinite resource with pad, well I was not able to hold for long, so by paying fairly with no pause or stuff like that it's almost impossible to get twrew this wave.*

**Steps to reproduce**: */*

**Link(s) to mod(s) used**: */*
**Save file**: */.*

**Crash report**: */.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 5382Ander2** [comment]
Use unit factory lol 
DeltaNedas/unit-factory
dependencies:
DeltaNedas/ui-lib

**Comment by D-player1** [comment]
Not even telling which sector is it and doesn't even have a save file.
Amazing

**Comment by suprainfinite** [comment]
hello and sorry, it's my first report ever, so yeah, well the sector is
226, and for the save file, I apologize but I don't know where I can grab
it. Again sorry for the misunderstanding and my lack of knowledge about
that.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Legomonster33** [comment]
1. fuse spam
2. dont go to hard sectors if your not prepared

**Comment by suprainfinite** [comment]
don't be prepare? I have lauch with max resource + my pad redirect to this
sector.
I have span cyclonus, with thorium wall + at my base 20 phantom for rebuild
+ full unlock tech tree.
and the point is desolate rift is 20 more easier, cuz you have around 10
minut for prepare your defence and for only T4, here we have only 5 min for
T5.
I mean if that would have been a T4 that would be fair, but that just a
difficulty 6, if that was a difficulty 8 again that would be fair, but for
difficulty 6 get a T5 round 5 that quite insane.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 23 nov. 2020 à 13:20, Legomonster33 <notifications@github.com> a
écrit :

**Comment by Legomonster33** [comment]
Fuses are much better than cyclones if used properly,
Phase walls + lots of Menders
I just captured the sector, yes it wasnt bit hard but it wasn't impossible or unreasonable.
Desolate rift isn't hard and never has been

**Comment by suprainfinite** [comment]
ok, ok well if you have succeed, that mean it's possible, yet the number of
difficulty should be more  precise. Like it's not a difficulty 6, and why
not use the impair number, like what not make this sector with 7 or 8.
because yeah again, it's normal to have difficulty but have a warning
before should be good.
well sorry to have disturb you, have a great day.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 23 nov. 2020 à 14:15, Legomonster33 <notifications@github.com> a
écrit :

**Comment by Anuken** [comment]
The sector difficulty is literally displayed as "**eradication**". Of course the difficulty is insane.
