### ISSUE TITLE
Mindustry causes driver stop responding

### ISSUE THREAD

**Issue by aviegdown** [Anuken/Mindustry#3546]
**Platform**: Windows 7

**Build**: Beta Build 115

**Issue**: At startup, the game causes 100% CPU usage and display driver stops responding. then game will end blank _(black/white screen)_.

**Steps to reproduce**: 

1. Open mindustry 
2. Exit (if works normal)
3. Open mindustry again

(I tested it and happened randomly)

**Crash report**: [crashlog.txt](https://github.com/Anuken/Mindustry/files/5583314/crashlog.txt)

![mindustry4](https://user-images.githubusercontent.com/72583750/99969018-7a197880-2dcc-11eb-908c-e1be1c561391.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Then your driver is broken.
