### ISSUE TITLE
[Modding] Custom bases partially not working

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3550]
**Platform**: *Windows*

**Build**: *beta 116*

**Issue**: *Modded custom bases don't work if the turret has a "-" in the name, such as* `dragons-roar`

**Steps to reproduce**: *Make a turret with a minus sign in the name and try to hand it a custom base.*

**Link(s) to mod(s) used**: *https://github.com/K103908/Exotic-Mod*

**Save file**: *enslaved for uses relating to taking over the government* (jk not available)

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have enslaved the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't see a base sprite in the sprites folder. The new system doesn't require the sprite to be in the override folder.

**Comment by BlueWolf3682** [comment]
I tried with a different turret, the one named `galaxy-edge` @Anuken

**Comment by BlueWolf3682** [comment]
so apparently for some reason it spontaneously decided to work, i didnt change any files related to it
