### ISSUE TITLE
Wave survive estimates being easier than real

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3555]
**Platform**: Any

**Build**: Any build that has wave survival estimates. In my case, its 2045

**Issue**: So, wave surviving estimate is unrealistic. I landed in inpact 0078. Thats a hard sector. I ran out of graphite, so I went to extraction outpoust to send some. I saw 30+ wave surviving. All i built was a large thorium wall wall, with fuses behind it. I had 0 menders or any other turret. I saved progress at the estimate, and played from it, without doing anything. I lasted for 12 waves only. So, that is too easy. I can see someone easily pass all waves, by only periodic repairs and a fuse wall. Land there and see it for yourself
[Survival estimate issue (see Impact 0078).zip](https://github.com/Anuken/Mindustry/files/5584981/Survival.estimate.issue.see.Impact.0078.zip)

**Steps to reproduce**: See survival estimates. I suppose it has something with fuses, maybe rating them as too OP, I dont know. You dont have to do anything really, but build fuses. My save also might be broken,

**Link(s) to mod(s) used**: 

**Save file**: Its up there

**Crash report**: Not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BorisA11** [comment]
I dont know how to remove the "bug" label. This isnt a bug, just to note

**Comment by Anuken** [comment]
Wave estimates can never be exact. It is only an approximation.

**Comment by BorisA11** [comment]
Maybe make them a bit harder? Since now you can get out of a sector, like Impact 0078 and evade all waves. You can use this method to avoid guardians as well, sooner or later someone will post this "cheat strategy", effectivly ruining the game

**Comment by Anuken** [comment]
Then I run the risk of making it too hard, which it already is in some situations. I would rather it be too easy than too difficult.
