### ISSUE TITLE
launch pads still launching when disabled

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry#3557]
**Platform**: *Any*

**Build**: *20045*

**Issue**: *launch pads still launching even if they are disabled by processors, this may be caused by the time to update the sector production and exporting*

**Steps to reproduce**: *capture a sector in campaign, make a launch pad, put some resources, launch, wait the production/exportation update, disable the launch pad, quit, when back they launch and show the animation*

**Link(s) to mod(s) used**: *none*

**Save file**: *[sector-serpulo-192.zip](https://github.com/Anuken/Mindustry/files/5585182/sector-serpulo-192.zip)*

**Crash report**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Launch pads can't actually be disabled.

**Comment by Legomonster33** [comment]
> Launch pads can't actually be disabled.

wait what why

**Comment by Anuken** [comment]
Disabling a launch pad on a sector and leaving won't actually stop the simulation.

**Comment by 50275** [comment]
So... you have to disable everything around the launch pad, such as its access to power?

**Comment by HTMLPhoton** [comment]
Disconnecting the launch pad will stop it from launching, alternatively you can just delete the launch pad altogether (though not very logic-friendly)

**Comment by pyokken** [comment]
I agree with this issue. I think the expected behavior is that disabling a launchpad should stop it from launching, almost as it it was disconnected from power. This would make it much more easier to disable launchpads with logic. I know it can already be done (with diodes, for example) but these seem like workarounds to a much easier method.
