### ISSUE TITLE
units without weapons can send shoot packets

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3558]
**Platform**: *Unknown*

**Build**: *probably 115*

**Issue**:
Units without weapons (e.g. mono) still send shoot packets when you "shoot" with them.
If a client adds weapons to mono then theyll see shooting. (desync ofc but still, the packets are sent)

**Steps to reproduce**:
```js
UnitTypes.mono.weapons.add(UnitTypes.mace.weapons.first());
```
Then, have someone try to shoot in a mono.

**Link(s) to mod(s) used**: on a modless server

**Save file**: i dont have

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [?] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. There is no such thing as a shoot packet.
2. Why is this a problem? It's easy to cause problems with mods or the console. Don't.

**Comment by DeltaNedas** [comment]
1. oh
2. the server is sending packets when an unarmed unit "shoots" which wastes a tiny bit of data, if ever done
