### ISSUE TITLE
buggy pathfinding when controlling a group of ground/naval units (intended?)

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry#3559]
**Platform**: *Any*

**Build**: *20048*

**Issue**: *ground and naval units following a player get easily stuck in walls, they simply try to walk in the same direction, if this is intended, should be implemented some pathfinding because this is certainly annoying*

*demonstration in Overgrowth*
![image](https://user-images.githubusercontent.com/62845905/100028742-5a834f80-2dce-11eb-922d-7fadaf74dd4f.png)

**Steps to reproduce**: *press **G** to control a bunch of ground units and pass through some obstacles*

**Link(s) to mod(s) used**: *none*

**Save file**: *[testing map](https://github.com/Anuken/Mindustry/files/5586595/path.zip)*

**Crash report**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There *is* no pathfinding, and there isn't supposed to be.

**Comment by Legomonster33** [comment]
> There _is_ no pathfinding, and there isn't supposed to be.

they should have pathfinding, because otherwise commanding units becomes painful.

~~#suggestions~~

**Comment by hadron13** [comment]
> > There _is_ no pathfinding, and there isn't supposed to be.
> 
> they should have pathfinding, because otherwise commanding units becomes painful.
> 
> ~#suggestions~

*they are already painful to move, specially slow units like mace*
