### ISSUE TITLE
Units with SapBulletType as a fragBullet for a weapon's bulletType randomly go to brazil when attacking

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3560]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: While testing my mod, I noticed that the Scyllas are dying even though their artillery bullets frag into SapBulletType bullets. They usually steal health when units are hit by the sapping frags, but sometimes the Scyllas actually lose health or even outright die.

**Steps to reproduce**: Make a unit that fires a bullet that frags into SapBulletType bullets. unit sometimes goes to brazil

**Link(s) to mod(s) used**: https://github.com/z0mbiesrock/Diamond-Ore/tree/6.0

**Save file**: 
[7.zip](https://github.com/Anuken/Mindustry/files/5586918/7.zip)
this save sets up the issue.

**Crash report**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
SapBulletTypes are only intended to be shot directly. Won't fix.

**Comment by z0mbiesrock** [comment]
> SapBulletTypes are only intended to be shot directly. Won't fix.

And I just justified that? And apparently it's not possible to fix?

**Comment by DeltaNedas** [comment]
template

**Comment by z0mbiesrock** [comment]
> SapBulletTypes are only intended to be shot directly. Won't fix.

Well, at least I can set sapStrength to 0 and keep the cool effect SapBulletType frags make. The effect is too cool to remove tbh

**Comment by z0mbiesrock** [comment]
>Won't fix.

https://www.youtube.com/watch?v=EzWNBmjyv7Y
