### ISSUE TITLE
Broken surface shader

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#3564]
**Platform**: Linux

**Build**: 116

**Issue**: Atmosphere shader makes planet surface transparent, in contrast to the base spheroid. This makes it look like the planet is a perfect sphere, which it is not: see image.
![image](https://user-images.githubusercontent.com/21104932/100086353-5c94ef00-2e5e-11eb-85bb-953687c4016f.png)

**Steps to reproduce**: Enter the launch view (universe).

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.

**Comment by BasedUser** [comment]
glass hills, okay
