### ISSUE TITLE
Scheme replacement causing h

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#3565]
**Platform**: Android

**Build**: 116

**Issue**: You can place any core scheme in campaign by replacing it

**Steps to reproduce**: 
-Place a core in sandbox custom game
-Make it a scheme
-Go to campaign to check if it appears there
-Go back to sandbox
-Place anything near the core
-replace the scheme before with this
-You can launch anything with core

**Save file**: 
[Kek.zip](https://github.com/Anuken/Mindustry/files/5589865/Kek.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
> 116

> I have updated to the latest release
