### ISSUE TITLE
Empty generators produce sounds

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3568]
**Platform**: *Linux*

**Build**: *116*

**Issue**: *Some generators are making sound while being empty.*

**Steps to reproduce**: *Place combustion/differential generator and listen...*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
