### ISSUE TITLE
Community servers are gone

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3569]
**Platform**: *Ubuntu 20*

**Build**: *116 steam*

**Issue**: *For whatever reason community servers are gone but LAN is working via Steam, not sure if it's a bug or I am the only one having the issue. I've tried to reinstall the game but this didn't solve the problem. ~~help me~~*

**Steps to reproduce**: *idk*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They can't be fetched for whatever reason. Something is wrong with your network.

**Comment by Legomonster33** [comment]
firewall maybe?

**Comment by Slava0135** [comment]
> firewall maybe?

i didn't change anything. It was working fine yesterday

**Comment by Slava0135** [comment]
yeah, everything works via my mobile internet not on wi-fi

**Comment by Anuken** [comment]
Check logs.
