### ISSUE TITLE
Salt flats, and other built in attack sectors have certain issues

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3571]
**Platform**: Any

**Build**: 116

**Issue**: Multiple issues with these sectors:
Salt flats:
-Landing with a Nucleus destroys the walls in front of core, also goes out of the metal floor zone
-Silicon smelters distribute silicon to nothing, in v5 there were dagger factories. Add a lead line and change to ground factories
Overgrowth
-An empty spot lies above the enemy core, there were draug factories. Same in fungal pass

**Steps to reproduce**: Just land in specified sectors, with Nucleus in Salt flats.

**Link(s) to mod(s) used**: Nope

**Save file**: Its not about game, but about maps

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
can you check in the latest bleeding edge these issues still persist? a few changes got made to this map hours ago and thus some or all off your might have been solved thanks to that

**Comment by BorisA11** [comment]
Sure, updating now

**Comment by BorisA11** [comment]
But actually, I cant know, since I already landed to all attack sectors, and conquered them, so they wont "update"

**Comment by Legomonster33** [comment]
> But actually, I cant know, since I already landed to all attack sectors, and conquered them, so they wont "update"

you can go to your files and find the msavs, delete them, and then you can go back fresh

**Comment by Anuken** [comment]
This was already fixed.

> Landing with a Nucleus destroys the walls in front of core, also goes out of the metal floor zone

Why is this a problem?
