### ISSUE TITLE
cache directory bloatware

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3572]
**Platform**: `mac`

**Build**: `20049`

**Issue**: a cache directory containing audio files gets created from wherever bleeding edge is launched.

**Steps to reproduce**: `java -XstartOnFirstThread -jar /path/to/actual/jar` in any directory of choice.

![Screen Shot 2020-11-24 at 21 07 46](https://user-images.githubusercontent.com/3179271/100145780-2163e180-2e99-11eb-823b-b316b20cf954.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I haven't searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Music files can't be played from the JAR, so they have to be extracted somewhere. In a normal installation, this isn't a problem.

**Comment by Quezler** [comment]
could this not ideally be moved to the `%appdata%` / `application support` folder based on the platform though?

**Comment by Quezler** [comment]
linking what fixed it for reference: https://github.com/Anuken/Arc/commit/f99aa02b0def1951452b67263439977d1d485ae7
