### ISSUE TITLE
Issue : phantom distroyed biuildings prevent placing new ones on top of them.

### ISSUE THREAD

**Issue by LoneWolfGmer** [Anuken/Mindustry#3574]
**Platform**: *Android/iOS/Mac/Windows/Linux* 
windows/android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 
steam build  117 also seems to happen on beta for the phone as well

**Issue**: *Explain your issue in detail.* 
it appears that at times when things are blown up it will leave a phantom image of the destroyed building but it prevents me from building onto blown-up buildings. unless I delete the phantom building first it happens sometimes.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
blown up a building and try to place on the phantom buildings. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X
[test.zip](https://github.com/Anuken/Mindustry/files/5594357/test.zip)
] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![2020-11-25 09-15-27](https://user-images.githubusercontent.com/10100000/100238967-d1b80100-2efe-11eb-811b-0ef75f52f878.gif)

No problems here. Your linked save file **is not what you were playing on when the issue happened**, and contains absolutely no usable information. I can't do anything with a single ground zero save.
