### ISSUE TITLE
Sector damage system counts scatter damage towards ground units

### ISSUE THREAD

**Issue by Zagrox11** [Anuken/Mindustry#3576]
**Platform**: Android

**Build**: 117

**Issue**: Scatters counted as both anti air and anti ground turret by the sector damage system. It could possible count ripples as anti air, don't know haven't tested those.

**Steps to reproduce**: 
1. Enter ground zero or any similar difficulty sector under attack(with ground enemies).
2. Deconstruct all the turrets
3. Build some scatters and put lead in them.
4. Check how much waves a sector will survive.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
All damage types are pooled as one.
