### ISSUE TITLE
ci tried to trigger bleeding edge on forked commit

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3580]
**Platform**: `web`

**Build**: `latest`

**Issue**: the full ci runs even for commits on forks, great for code checks but the upload for it fails.

**Steps to reproduce**: make a small change on a fork.

![Screen Shot 2020-11-25 at 09 41 19](https://user-images.githubusercontent.com/3179271/100203283-adf6ba00-2f02-11eb-9863-abb5a11f0f17.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has already been reported.**

**Comment by Anuken** [comment]
fixed
