### ISSUE TITLE
Mindustry crash on beta 116

### ISSUE THREAD

**Issue by ruggi99** [Anuken/Mindustry#3581]
**Platform**: Windows

**Build**: 116

**Issue**: Mindustry crashed while I was playing onto the "best-survival server". I wasn't doing anything special when it crashed. Reported as suggested in the file.

**Steps to reproduce**: None

**Link(s) to mod(s) used**: No mods used

**Save file**: No save file, as I was playing on a remote server?

**Crash report**: [crash-report-11_24_2020_19_13_47.txt](https://github.com/Anuken/Mindustry/files/5595664/crash-report-11_24_2020_19_13_47.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This report doesn't make any sense. The server is likely modded or you're using an incompatible client.

**Comment by ruggi99** [comment]
The client is downloaded from here on GitHub (beta 116).
I don't know if the server is modded (I thought you knew)
I reported it because I was advised to do so
