### ISSUE TITLE
server error loses colour after @

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3585]
**Platform**: `linux`

**Build**: `20059`

**Issue**: the red style of `err` seems to reset where `@` gets used to insert stuff into strings.

**Steps to reproduce**: the most notable example is the no map found error:

<img width="418" alt="Screen Shot 2020-11-25 at 11 09 17" src="https://user-images.githubusercontent.com/3179271/100213432-e43a3680-2f0e-11eb-9360-8853982690a9.png">

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been deported.**

**Comment by Anuken** [comment]
This can't really be fixed.
