### ISSUE TITLE
stopped a SoloudSound: null crashes without report

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3586]
**Platform**: Android 9

**Build**: 20059

**Issue**:
`loadSound("pew")` returns `SoloudSound: null`
When stopped, mindustry crashes **without creating a crash report**.
If print debugging didnt work it would be much harder to find out the cause of the crash.

**Issue 2**:
Sounds cannot be loaded post load-time.
`Sounds.pew` exists, but `loadSound("pew")` is natively null.

**Steps to reproduce**:
1. `loadSound("pew").stop();`
2. Crashes, check crashes folder (empty).

**Crash report**: *that's the problem*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
what the heck is a SoloudSound

**Comment by GlennFolker** [comment]
> **Issue 2:**
> Sounds cannot be loaded post load-time.
> `Sounds.pew` exists, but `loadSound("pew")` is natively null.

Have you tried `loadSound("few")`, then wait for a little moment for it to finish loading and _then_ interact with it?

**Comment by Anuken** [comment]
1. You can't stop uninitialized sounds.
2. Sounds are not loaded immediately. You need to wait until assets finish loading.
