### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by LigandMT** [Anuken/Mindustry#3587]
**Platform**: *Android*

**Build**: *117*

**Issue**: *When trying to build in nuclear complex the game freezes and then automatically closes. This is not an issue in other sectors. *

**Steps to reproduce**: *Loading to nuclear complex takes very long if it loads.. when it loads it runs ok  it you do not attempt to build any structures.*

**Link(s) to mod(s) used**: *no mods*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x
[data mindustry.zip](https://github.com/Anuken/Mindustry/files/5596594/data.mindustry.zip)
[data mindustry.zip](https://github.com/Anuken/Mindustry/files/5596598/data.mindustry.zip)

] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Nikolass1000** [comment]
Thats gamebreaking bug, thanks you described every detail.
I hope anuke will fix it

**Comment by LigandMT** [comment]
Added exported data

**Comment by Anuken** [comment]
On my crappiest phone (low-end 2014, 1GB ram), Nuclear Complex loads in a reasonable amount of time and doesn't use any more RAM than any other map. I have no issues placing or breaking there. Won't fix.

**Comment by LigandMT** [comment]
The data originated from a 2014 phone, a moto g5s I am currently using a
moto g9pro with 4gb of ram. I do understand that some games require more
ram than or even others even some sections of the game. This issue began
with following yesterdays update. Even sector 1 was laggy where it was not
yesterday.

Many thanks for your honest feedback 😅

**Comment by Anuken** [comment]
After looking at some other reports and testing maps, I've determined that this has nothing to do with NPC or low-end Android devices, but rather the presence of broken blocks. Should be fixed next release.
