### ISSUE TITLE
Unit command getting lost after leaving a sector

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3592]
**Platform**: Windows

**Build**: Literraly any beta build, for this instance its 117

**Issue**: As you leave a sector, and command some units, and come back, units will no longer be commanded. This is bad, in cases you have already, for example dragged flares out of air unit swarm to command only those, and they get reset so you have to do it again

**Steps to reproduce**: Here:
1) Enter a sector
2) Command some units by G key
3) Leave sector
4) Come back

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: Its not about save file, I've seen it on various other devices

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional. Command status is not saved.

**Comment by BorisA11** [comment]
But why its not saved? Its kinda annoying to have to find units again, especially with rally command center.
