### ISSUE TITLE
Проблема со сохранениями й

### ISSUE THREAD

**Issue by kenorr11** [Anuken/Mindustry#3593]
**Platform**: *Android*

**Build**: *117.*

**Issue**: *сектор выдаёт ресурсы но фабрик там нет как и стартовых площадок.*

**Steps to reproduce**: *я играл с другим по локальной на его вайфай . Я помогал ему захватить сектор который у меня уже захвачен и там у меня был производства ресурсов так вот после того как мы закончили играть я обнаружил что у меня сохранились его сектора а мои исщезли 
Сектора которые исщезли у друга были не захвачены после захвата возникла это проблема на моем сохранение.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *https://yadi.sk/d/XKYmfSyapnzsMA*цу

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Просьба отправить ответ на почту :
denis.ponomorew@gmail.com
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by summetdev** [comment]
**English version:**
I played with my friend by wifi. I helped him to capture the sector that I had already captured with a lot of resources, so after we finished playing I found that I mine sector was replaced by my friend's sector. Sectors that have disappeared from a friend were not captured after capture, this is a problem with my saves.

**Comment by DeltaNedas** [comment]
crash report: email
hahahaha what the fuck

**Comment by Anuken** [comment]
Duplicate.

**Comment by kenorr11** [comment]
https://yadi.sk/d/FPqaNHnnEgbe6w
bug list
