### ISSUE TITLE
Zip Export from Android won't open in Windows

### ISSUE THREAD

**Issue by oborsha** [Anuken/Mindustry#3594]
**Platform**:  *Android/Windows*

**Build**: *104.6 on Android. 1.4.10 on Windows (64-bit).*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *I exported my game (save) on Android.  This created a ZIP file on my phone that I transferred to Windows (emailing it to myself).  On Windows, I am unable to UNZIP the file using Windows Zip nor 7-Zip.  It says Windows cannot complete the extraction.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oborsha** [comment]
I should add, I'm a proud paying supporter of the game.   :)   I love it.   But if I can't switch between my phone and laptop, I'll be less likely to be able to play it over the long haul.  I hope we can get this working.   :)

**Comment by DeltaNedas** [comment]
you use the in-game import data button
this is not the binbows issue tracker

**Comment by Anuken** [comment]
You're not supposed to unzip it manually. Import it in the game.
