### ISSUE TITLE
Kringe Bugs: Episode 1

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/Mindustry#3595]
**Platform**: *Android, Other platforms may be*

**Build**: *105.117.1 (//Mindustry Version 6)*

**Issue**: *A common bug with a resource computation in the core*

**Steps to reproduce**: *To do this, it is enough to collect 1.9 thousand, then with any block with this resource to follow the resources in his table and icon on the core(to be sure) and looking at the number in both frameworks*

**Link(s) to mod(s) used**: * Not one *

**Save file**: * He's going to be here for all this stuff, but you can make this bug yourself.*
[Nom-Nom, delicious Mindustry.zip](https://github.com/Anuken/Mindustry/files/5598747/Nom-Nom.delicious.Mindustry.zip)

**Crash report**: *No*

![Screenshot_20201125-212643](https://user-images.githubusercontent.com/72934248/100269834-378ca300-2f68-11eb-8d12-d8070142f08e.jpg)

**Comment by Anuken** [comment]
Not a bug. In the core, 1960 is rounded down to `1k`, while for the item display it is rounded to `1960` -> `1.96` -> `2`. If the amount were `1940`, it would be displayed as `1.9k`.

**Comment by DeltaNedas** [comment]
> 105.117.1 (//Mindustry version 6)
i seriously doubt that's shown in the main menu
