### ISSUE TITLE
"New Content Unlocked" appears every time you become a Beta

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#3597]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows, with an android phone hosting the game

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

117.1 Beta

**Issue**: *Explain your issue in detail.*

Whenever you go into the core, by pressing V as a unit, or Ctrl + clicking the core, you see the "New Content Unlocked", even if you already have unlocked it

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Host a game on a mobile android phone, get to a sector with a Foundation core, join the game with a Windows computer, and go into the core. New Content Unlocked should appear every time you go into the core

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods, vanilla.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

Unneccesary, because this issue can be replicated on any save file, not any specific ones

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.

**Comment by nichrosia** [comment]
Nice
