### ISSUE TITLE
Android not displaying names of blocks linked to processors

### ISSUE THREAD

**Issue by stoneRdev** [Anuken/Mindustry#3602]
Platform: Android

Build: beta build 117.1

Issue: So, I'm trying to use the new processor blocks, and in all the video tutorials I've seen (which are pc), when they link a block to the processor, a name for that block displays (like `container1` or `conveyor1`) that they use to work with the block. On Android, the name doesn't show up, making it petty much impossible to use the processor blocks for anything other than spinning triangles.

Steps to reproduce: Launch game on android, go to any game location, place any processor block and another block, connect processor block to other block, and observe no name appear

Link(s) to mod(s) used: No mods

Save file: Not relevant, can re reproduced on new game or sandbox

Crash report: Not relevant

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
nice screenshot you posted

**Comment by Anuken** [comment]
> Not relevant, can re reproduced on new game or sandbox

Nope:

![image](https://user-images.githubusercontent.com/10100000/100288878-aad0ed80-2f45-11eb-8d08-413644d37ed2.png)

You're likely using pixelation. Disable it. Text is unreadable when that is enabled.

**Comment by stoneRdev** [comment]
Sorry for lack of screenshot, I use github on my PC, mindustry on my phone. And @Anuken Much appreciated, I had checked the settings to make sure but I wasn't aware that pixelation had that side effect. Issue fixed, thank you :)

**Comment by stoneRdev** [comment]
@DeltaNedas Nice consideration for people that can't easily post a screenshot. You could have asked

**Comment by DeltaNedas** [comment]
1. take  screenshot
2. upload it
i fail to see the difficulty

**Comment by GreyMario** [comment]
Let me just casually mention that I am posting this comment from my phone. There are also many ways of transferring data back and forth between PC and mobile device.

**Comment by stoneRdev** [comment]
Cool beans that its easy for you. I don't feel like taking a screenshot on
a game, copying it to my computer, then uploading it, It's a hassle, my
port on my phone sucks. Why does it matter when the point was clear anyway?
Sir anuken knew what the issue was from my description, and the issue is
resolved, so why troll around on it? why nag at people for their choices?

**Comment by GreyMario** [comment]
Because it's fun to make people like you squirm.

**Comment by stoneRdev** [comment]
@GreyMario haha ya, nice way to interact with your peers. You should seriously reconsider how you handle yourself if you hope to get anywhere, otherwise you'll be going nowhere and blaming everyone else for it. Anyway, great show on this game @Anuken, I love how its grown over the 3 or so years I've been playing. Let me know if you need any help, I can help out with anything Java or Cpp repated, on the house :)
Dec 1, 2020 3:28:30 AM GreyMario <notifications@github.com>:

Because it's fun to make people like you squirm.

**Comment by GreyMario** [comment]
Oh, _sweetie._

You know what goes nowhere? Having to pull teeth just to get the entire context out of someone.

Provide the screenshot the first time you make the first post next time and maybe you won't end up being the butt of the entire thread. It's two minutes max out of your life.

**Comment by stoneRdev** [comment]
If you don't like it then that's fine. There's a right way to handle a situation and a wrong way. I've gone plenty in my life and I know for a fact where your attitude will get you, and the funny thing about it is you will blame everyone but yourself. But that's fine, I got better things to do than try and help kids before their attitude dead ends their life. Have a good day, I hope the best for you, but if you think I'm continuing this conversation, then you got me mistaken for someone who cares
