### ISSUE TITLE
Fungal Pass invasions spawn enemies inside forward base circle

### ISSUE THREAD

**Issue by Jorerlol** [Anuken/Mindustry#3605]
**Platform**: *Windows*

**Build**: *Steam Build 117.1*

**Issue**: *After capturing Fungal Pass, I moved onto other sectors. An invasion triggered on Fungal Pass, where the forward base's spawning circle spawned over the top of the coal patch in the sandbar. The first wave immediately destroyed all buildings in the area (tied to the Core: Shard that was previously here) and effectively cripples manufacturing for defenses.*

**Steps to reproduce**: *1. Capture Fungal Pass
2. Wait for Fungal Pass to be invaded
3. Return and encounter circle of destruction over the coal patch*

**Link(s) to mod(s) used**: *Beta - mods not loaded.*

**Save file**: *[Data.zip](https://github.com/Anuken/Mindustry/files/5600118/Data.zip) This contains all files within the Mindustry saves folder. Fungal Pass is sector 21. This save was made before the wave was triggered - accelerate the wave to see effects.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.
