### ISSUE TITLE
Able to research sector specific research before capturing it

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#3606]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

117.1

**Issue**: *Explain your issue in detail.*

On Overgrowth, for example, you can launch there, and instantly research the multiplicative reconstructor, without ever having to actually take over the base

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Launch to an attack sector, research the technologies there, and you don't need to capture the base

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

Unneccesary, can be replicated on any save

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The multiplicative reconstructor doesn't require capture of anything.

**Comment by nichrosia** [comment]
Sorry, I thought this was a bug
