### ISSUE TITLE
Meltdown power use issue

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#3607]
**Platform**: Windows 7

**Build**: 20089

**Issue**: The 7 player controlled meltdowns make bugs in power grid. Sometimes, power minus comes with a delay, sometimes it wont happen at all. Sometimes they take power even when cooling down. I have a logic proccessor asigned to them, so they fire where I fire.

**Steps to reproduce**: Try to do these (on given save file)
-Just shoot by holding down mouse until power is depleted. Something might happen
-Turn them sharply
-Rapid clicking
-Try doing it when commanding some units (I had them assigned during testing)
-Replace cryo with water and see if they do the same
-Overdrive them (youll have to launch plast from impact 0078 though, as nuclear has none)
-Just mess around until something happens with power. You have a large power node so you can track it here.

**Note:** I got these results:
-Power use coming with a delay
-Power use not coming at all
-Power use lasting longer

**Link(s) to mod(s) used**: DeltaNedas/Developer Mode (I had it on all the time, for needs of sound bugs testing, none occured after the conveyor thing, so mp3 files seem to be better)

**Save file**: 
[Meltdown power bug (land in Nuclear Complex).zip](https://github.com/Anuken/Mindustry/files/5601431/Meltdown.power.bug.land.in.Nuclear.Complex.zip)

**Crash report**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Sometimes they take power even when cooling down. 

This is intentional. Laser turret use is continuous. As long as the turret is reloading or actively firing its beam, it should consume power.

The other cases have been fixed.

**Comment by BorisA11** [comment]
Good. Also, I've seen some beam wobbling in latest build, is that intentional, as the beam is pulsing or is it another bug?
