### ISSUE TITLE
the application seems corrupt

### ISSUE THREAD

**Issue by cyphercollider** [Anuken/Mindustry#3611]
**Platform**: *Android

**Build**: ***20083 - 20089***

**Issue**: *when i try to install it after being downloaded by my browser it says application not installed, application seems to be corrupt.*

Heres a link https://drive.google.com/file/d/1oCDjwqXi9_eHXx_9h4Xlm5FnnO_Hjc-9/view?usp=drivesdk

**Comment by NgLamVN** [comment]
Uninstall old Mindustry before you install this... may be it will work.

**Comment by cyphercollider** [comment]
If i would do it then would it cost my game save?

**Comment by cyphercollider** [comment]
Last time i used my game save it my level just got overriden than being continued

**Comment by DeltaNedas** [comment]
`mv io.anuke.mindustry.be h`
<uninstall and update>
`mv h io.anuke.mindustry.be`

**Comment by cyphercollider** [comment]
I cant install the versions posted by github actions bot

**Comment by cyphercollider** [comment]
Its corrupted

**Comment by Anuken** [comment]
No, it's not. Read the comments above, again.
