### ISSUE TITLE
Client crashed, and liquid source block is somehow involved

### ISSUE THREAD

**Issue by FeyFre** [Anuken/Mindustry#3614]
**Platform**: *Windows*

**Build**: v5 104.10

**Issue**: . I was just playing mutiplayer game, and suddenly crash. First time it happened 1-2 weeks ago, next time few days ago. I do not play daily, but it looks repeatable enough. I lost crash report of first crash, but crash report of second one pretty much match (top of stack trace looks the same).
As far as I remember server didn't update anything between crashes.
As far as I can remember it was different maps where crash happened.
Liquid sources that caused crash belong to AI enemy (a ton of sources in fact), ordinary human players do not have access to them, so it doesn't sound like player action caused crash.

If it can help, server I played is mindustry.ru:9992 (attack mode)

**Steps to reproduce**: Just play map with liquid source, and if you (un)lucky catch crash.

**Link(s) to mod(s) used**: None

**Save file**: None. Multiplayer game.

**Crash report**: Attached [crash-report-11_24_2020_23_19_49.txt](https://github.com/Anuken/Mindustry/files/5603865/crash-report-11_24_2020_23_19_49.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
![image](https://user-images.githubusercontent.com/54417042/100370090-c1258a80-2fd3-11eb-8cec-02b6a46037f1.png)
are you sure about that

**Comment by Anuken** [comment]
Not the latest version,.

**Comment by FeyFre** [comment]
Excuse me, but it is latest released version v5.0. v6.0 is not released yet, and I know it is planned to be released in 5 days or so. In any case I, and probably much more players, are going to stick to 5.0 for a while. Honestly we do not have much choice, versions are not compatible at all. Want you it or not, you ought to support 5.0 for a while.
Also, who said this bug didn't reproduce on 6 as well?

**Comment by FeyFre** [comment]
> ![image](https://user-images.githubusercontent.com/54417042/100370090-c1258a80-2fd3-11eb-8cec-02b6a46037f1.png)
> are you sure about that

Yes, latest release is 5.0. 6.0 is no released yet

**Comment by Anuken** [comment]
> Want you it or not, you ought to support 5.0 for a while.

I'm *not* supporting 5.0, and it hasn't seen any updates for 7 months now. That version is long dead.

> Also, who said this bug didn't reproduce on 6 as well?

The crash report you posted doesn't apply to the 6.0 structure and can't be used. You have not posted a save or any specific reproduction steps, so it can't be investigated further.

**Comment by FeyFre** [comment]
Sorry to hear that.
Good we are in Github
