### ISSUE TITLE
server list not showing automatically

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3617]
**Platform**: Android 9

**Build**: 117 and 117.1

**Issue**:
Global server list is hidden by default, **resetting on restart**.

**Steps to reproduce**:
1. Open default server list, it's empty
2. Toggle eye
3. It shows

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
Ah, the eye must be toggled to show servers, theyre l hidden by default for some reason (i think)

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/100382888-4f0c7000-2fea-11eb-81da-47432fc02a5b.png)

Doesn't happen for me. This is a fresh save folder. I don't see any code that would cause hide-by-default behavior.

**Comment by DeltaNedas** [comment]
my settings.bin is probably messed up then
