### ISSUE TITLE
Segments broken when shooting ontop of enemy block

### ISSUE THREAD

**Issue by UltraBlackLinux** [Anuken/Mindustry#3619]
**Platform**: Linux

**Build**: 117.1

**Issue**: This: https://streamable.com/nztq9t

**Steps to reproduce**: Obvious
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
its not broken, the bullets are just instantly hitting the enemy structure

close this.

**Comment by Anuken** [comment]
yep
