### ISSUE TITLE
Editor Bug

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#3621]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
V6 Builds 20096 to 20102

**Issue**: *Explain your issue in detail.*
In the editor, the pencil defaults to a radius of 2 tiles but it's stuck at that setting. All other tools besides the pencil work fine.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Open the editor, and right away you'll notice it's stuck at 2 tiles. No matter what you move the slider to or how many times you switch tools the pencil is stuck at a radius of 2 tiles.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Happens only in the editor.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No crashes reported, just a bug.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Select a different block. Multiblocks do not support a different radius.
