### ISSUE TITLE
Pixmap errors.

### ISSUE THREAD

**Issue by coolrouter123** [Anuken/Mindustry#3623]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Build 115.1

**Issue**: *Explain your issue in detail.* Out of memory and corrupted jpeg.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* Open up mindustry and wait in loading. (for both crashes)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Vanilla mindustry (github version)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* Happens during loading

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Out of memory: [crash-report-11_27_2020_16_14_36.txt](https://github.com/Anuken/Mindustry/files/5606723/crash-report-11_27_2020_16_14_36.txt) Corrupted jpeg;
[crash-report-11_27_2020_20_47_30.txt](https://github.com/Anuken/Mindustry/files/5607903/crash-report-11_27_2020_20_47_30.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate. Use a different computer.
