### ISSUE TITLE
Something wrong with the tech tree

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry#3625]
**Platform**: Windows 10

**Build**: beta build 117

**Issue**: If you want to unlock Salt Flats, you need to research the Water Extractor; However, you need to research the Water Extractor to unlock Salt Flats. That makes me fell amusing, and without the Water Extractor I cannot get water in no-water sectors and  the drills cannot dig fast. It's wierd nobody noticed it.

**Steps to reproduce**: It’s just a bug. Everyone can reproduce it by capturing Windswept Islands and find that Salt Flats has gone.

**Link(s) to mod(s) used**: No mods.

**Save file**: I think it happens in every single gameplay, but I’ll export my save file.

**Crash report**: Nope.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SoMall-dumpling** [comment]
[simply just named sectors and enemy bases near them.zip](https://github.com/Anuken/Mindustry/files/5608504/simply.just.named.sectors.and.enemy.bases.near.them.zip)

**Comment by Anuken** [comment]
Already fixed.
