### ISSUE TITLE
Play/pause button

### ISSUE THREAD

**Issue by Sponticus** [Anuken/Mindustry#3626]
Please move the play/pause button on mobile. It's very frustrating to accidentally pull up the tech tree while everything is still moving in the background. Put it off to the other side by itself and maybe a little bigger than the other buttons.

**Comment by summetdev** [comment]
1. Template
2. This is for bug reports only, if you want to suggest/improve something, open an issue [here](https://github.com/Anuken/MindustrySuggestions)
