### ISSUE TITLE
Game Crashes On Update

### ISSUE THREAD

**Issue by SystemRyker** [Anuken/Mindustry#3627]
**Platform**: *Windows*

**Build**: *20017*

**Issue**: *When attempting to update from version 20017 the game crashed after the restart and will no longer work.*

**Steps to reproduce**: *Update any version to the bleeding edge version, then wait until it restarts. It will crash during the loading stage and will render that copy of the game unusable.*

**Link(s) to mod(s) used**: *None*

**Save file**: *Not ingame*

**Crash report**: *There were no crash reports, just the windows "not responding" indefinitely*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SystemRyker** [comment]
New to github, so hope I formatted this right :)

**Comment by Anuken** [comment]
> Crash report: There were no crash reports, just the windows "not responding" indefinitely

I can't fix crashes with no report.

**Comment by SystemRyker** [comment]
Well, it wont generate one, so how do I get one @Anuken ?

**Comment by Anuken** [comment]
Run it through the command line.

**Comment by SystemRyker** [comment]
Ah :)
