### ISSUE TITLE
Tech Tree Intersection

### ISSUE THREAD

**Issue by yaboichris0** [Anuken/Mindustry#3630]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Beta-117.1

**Issue**: *Explain your issue in detail.*
In the tech tree, there is an intersection. This is at the top left of the laser drill with a locked item blocking the line of the rotary pump.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was playing campaign on Biomass Synthesis Factory, when I noticed that there was

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[mysave.zip](https://github.com/Anuken/Mindustry/files/5609703/mysave.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is known.
