### ISSUE TITLE
Mining Bug

### ISSUE THREAD

**Issue by OinkyPlayz** [Anuken/Mindustry#3632]
**Platform**: *iOS*

**Build**: * beta build 118*

**Issue**: *When having an item in your mech, you can only mine the type of item that you are holding, and doing so near the core will still mine the ore and deposit it into the core, but the items you were holding will slowly get deleted as you mine.*

**Steps to reproduce**: *I wanted to test if coal bombing was gone, (which it is) and while I was holding some coal, I wanted more, and so I started mining (near the core) and realized that the coal in my mech slowly drained away as I mined. I tested this again with copper and it yields the same result. To reproduce it, just grab some copper from the core, find a copper vein near the core and mine the copper vein while holding the copper in your mech, the copper should start disappearing from your mech.*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *Again, not sure how to retrieve this info. (But pretty sure it works on any safe file :P)

**Crash report**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Violet-Scarelli** [comment]
almost was gonna say that this wasn't a bug but it sounds like it might be.
