### ISSUE TITLE
Mining within auto-deposit range can delete a different held cargo

### ISSUE THREAD

**Issue by GreyMario** [Anuken/Mindustry#3633]
**Platform**: Windows

**Build**: 118

**Issue**: When the player enters a mining state while carrying a cargo different from the resource being mined, and the player is within automatic deposit range of the Core, the cargo the player is carrying will be erased one unit at a time.

The situations in which this occur are somewhat unlikely, but not _impossible_ in normal gameplay. Not major in the slightest, just turned out to be inconvenient when it happened.

**Steps to reproduce**: 
1. While within auto-deposit range of the Core, begin mining any material.
2. While mining, retrieve any other material from the Core.
3. Watch as the material you have in your cargo vanishes without a trace, one item at a time.

[GIF of the bug in action](https://puu.sh/GRZzH.gif)

This _might_ be because there's no check for `acceptsItem` made [if the core is within range](https://github.com/Anuken/Mindustry/blob/2a6b0fd0cedc0a34bbcd3f8f6601d6abf90bf3d5/core/src/mindustry/entities/comp/MinerComp.java#L79) so it doesn't auto-cancel the mining attempt because of a mismatched inventory.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
Looks like #3632 beats me to this one. I've only been writing this issue report for the last twenty minutes... 💦

**Comment by GreyMario** [comment]
Huh. The gif isn't... working...? God damn it. Eugh, whatever. It's still an easy replication.

**Comment by OinkyPlayz** [comment]
I think this explains better than mine, 👍
