### ISSUE TITLE
Not all the enemy's structures changing into neutral

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry#3634]
**Platform**: Windows 10

**Build**: beta build 118

**Issue**: Yeah, me again. 
                When I finally found Salt Flats is back again, I captured it in 10 minutes with 15 horizons.( maybe you can change the 
difficulty to 'medium'?)
                That is not the main issue. Just after the enemy's core exploded, I wanted to relax and closed the game. In just a few minutes I reloaded the game and went to Salt Flats. Some of the Duos, Scatters, conveyors, etc. were still enemy's, not changing into neutral. This made it difficult to clean up the sector.

**Steps to reproduce**: Destroy the enemy base and close the game at once. Then you can do it.
**Link(s) to mod(s) used**: No mods.

**Save file**: Here it is.
[simply just named sectors and enemy bases near them.zip](https://github.com/Anuken/Mindustry/files/5610050/simply.just.named.sectors.and.enemy.bases.near.them.zip)

**Crash report**: There was no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** to the issue, if applicable.*

**Comment by SoMall-dumpling** [comment]
![Beautiful](https://user-images.githubusercontent.com/57857764/100516299-d958fd80-31bd-11eb-84b0-31756ad51f20.PNG)
Somehow looks beautiful, isn't it?

**Comment by Anuken** [comment]
> Destroy the enemy base and close the game at once. 

Don't? The game doesn't convert every block to the neutral team at once, to prevent a lag spike. If you leave immediately while this is happening, it won't be able to complete.

**Comment by SoMall-dumpling** [comment]
So can you continue converting the blocks to neutral after the game is re-opened?

**Comment by Anuken** [comment]
No.
