### ISSUE TITLE
manufactured but not released units ignore team color 

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3636]
**Platform**: *Any*

**Build**: *118*

**Issue**: *Manufactured units are always colored yellow*

**Steps to reproduce**: *Just see units changing color when they are being released from an unit factory or a payload conveyor*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're supposed to be.

**Comment by Slava0135** [comment]
@Anuken then make them at least derelict (gray). This will make more sense.

**Comment by Anuken** [comment]
No.
