### ISSUE TITLE
118 build shows as custom build

### ISSUE THREAD

**Issue by Nikolass1000** [Anuken/Mindustry#3637]
**Platform**: *Windows*

**Build**: *118, but shows custom build*

**Issue**: *When i download newest release, it showas me it is custom build, happens after doownloading again*

**Steps to reproduce**: *Download minustry, run*

**Link(s) to mod(s) used**: *none*

**Save file**: *none*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X

] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Where did you download it?

**Comment by Nikolass1000** [comment]
https://github.com/Anuken/Mindustry/releases/tag/v118

**Comment by DeltaNedas** [comment]
use itch.io until anuke fixes ci

**Comment by Anuken** [comment]
fixed
