### ISSUE TITLE
Lost ressources

### ISSUE THREAD

**Issue by DarkSinss** [Anuken/Mindustry#3638]
**Platform**: *Android*

**Build**: *Beta build 117.1*

**Issue**: *If you launch your core with some ressources, left the game (which closes the app without saving) then come back, the game registered the fact that you lanched the core in that location, yet didn't register the amount of ressources lauched with it and you start with nothing*

**Steps to reproduce**: *Lauch core with extra ressources to new sector, close app, open app, go to sector you launched into, seemais result*

**Link(s) to mod(s) used**: *none*

**Save file**: *Can't find it, was in Campaign mode*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
this also happens if you `killall java -9`, not a bug as mindustry cant save data from a different thread when finishing

**Comment by DarkSinss** [comment]
I thought it may be this, but thanks for teaching me something about the game, you're all doing great
