### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry#3640]
**Platform**: *Android*

**Build**: *v117.1*

**Issue**: *When I'm playing on a Community Server, I got bounced back to main menu and got this message.
I can rejoin the server so I'm sure that I'm not kicked/banned by admin.*
![Screenshot_2020-11-27-13-48-03-558_io anuke mindustry](https://user-images.githubusercontent.com/26910478/100517474-44560480-31bd-11eb-9407-af0b6cb1dc4c.jpg)

**Steps to reproduce**: *I don't know how to reproduce this because it happens randomly when I'm playing on Community Servers.*

**Link(s) to mod(s) used**: *No mod.*

**Save file**: *No save file available.* 

**Crash report**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your device cannot handle the map.

**Comment by mangblekok** [comment]
Still happen on stable release v120
![Screenshot_2020-12-01-22-26-44-673_io anuke mindustry](https://user-images.githubusercontent.com/26910478/100760601-82089680-3424-11eb-90ea-6457c74aa158.jpg)

**Comment by Anuken** [comment]
My answer has not changed.
