### ISSUE TITLE
payload units getting vaporised when a block they are standing on is being deconstructed

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3641]
**Platform**: *Any*

**Build**: *118*

**Issue**: *The thing is that when you deconstruct a payload conveyor with unit on it, the latter go to Brazil. This is quite upsetting if you do it by accident especially for high tier units. However idk what to do about naval units laying on the ground*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The units aren't "standing" on anything, they're part of the block.

**Comment by DeltaNedas** [comment]
why not make payload units spawn when parent block is destroyed?

**Comment by Anuken** [comment]
You can do that. This tracker is for bugs, not feature requests.
