### ISSUE TITLE
Import yields:  Invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by oborsha** [Anuken/Mindustry#3643]
**Platform**: Android to Windows*

**Build**: *104.6 on Android. 1.4.10 on Windows (64-bit).*

**Issue**: *I export game data from Android to ZIP.  Then I run Import in Windows version of Mindustry and it says:

Invalid LOC header (bad signature)

And although I can't copy-n-paste the details, here are the start of the details:

ArcRuntime:  'Error copying source file: \saves\-1.msav-backup.msav (absolute)
To destination: ..........
.
.
ArcRuntime:  'Error stream writing to file: C:........\Mindustry\saves\-1.msav-backup.msav (absolute)

 *

**Steps to reproduce**: *Export from Android, Import with Windows version of Mindustry.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oborsha** [comment]
I have a screenshot of the error if it helps.

**Comment by DeltaNedas** [comment]
imagine posting the exported data or screenshot

**Comment by Anuken** [comment]
104.10 issue, won't fix.

**Comment by Anuken** [comment]
You're running a very old version, and the fact that you have not provided the data or the whole log makes it very unlikely that it will ever be fixed.

**Comment by oborsha** [comment]
I'm running the latest stable version...   104.10.

I'm happy to post whatever information is helpful.  Here is the screenshot.
![error-mindustry](https://user-images.githubusercontent.com/64018544/100520745-11802200-3165-11eb-8bab-e616317598f4.png)

**Comment by DayTimer** [comment]
> Im running the latest version. 104.10.

Is same as

> I'm using the newest smartphone in the world. Nokia 3310.

**Comment by oborsha** [comment]
These comments aren't really helpful.  I paid for the game voluntarily because I think it's great.  I got the app initially from Google Store and it was version 104.6 (that was two weeks ago).  Then I went to download online for my PC, and it said the latest stable build was 104.10.     So could someone please help me understand where I'm supposed to get the latest version of the game if what I'm finding, isn't it?

The site I downloaded it from, and also used to donate money to the project was this:
https://anuke.itch.io/mindustry

Thanks ahead of time.

**Comment by Anuken** [comment]
- The latest stable version may be 104.10, but that version has not been touched in 9 months and is very different from the latest *beta* version. Use the beta, or wait until it's released tomorrow.
- I can't use the log you posted because it's cut off and corresponds to code that doesn't exist in the beta version anymore.
- I can't test the problem because you haven't sent the data zip file here.

**Comment by oborsha** [comment]
Thank you Anuken.  That comment was way more helpful than @DayTimer.  The fact is @DayTimer misquoted me intentionally (removed the word 'stable' which is the key there) in their response.

I didn't realize that the recommendation was to be using the Beta.  I look forward to its release tomorrow!  Thank you so much.  I will stop responding here now.
