### ISSUE TITLE
Eternal 'Atom' core fire

### ISSUE THREAD

**Issue by Muxanuk** [Anuken/Mindustry#3649]
Android

Beta Build 118

My "Atom" core caught fire that both cryo Tsunamy and Wave couldn't put, so it burned down xO

I've launched my core to a new location and started a little energy production via basic combustion gens, but accidentally chosen Explosive Mix(i use russian leng in my game)  and it blew up, so my core caught fire. Any attempts to put it were fatile so i left it to burn down :c. 

No mods

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
dont put flammable items in your core

**Comment by Muxanuk** [comment]
> dont put flammable items in your core

oh gosh, i got it all wrong..... 13k of both pyrotit and explosive mix in each core........

**Comment by Quick-korkc** [comment]
> dont put flammable items in your core

some sector has no coal sometimes
and once a core full with flammable items, its really hard to extinguish the fire

**Comment by DeltaNedas** [comment]
a wave will do once you empty the core
close this issue @Muxanuk
