### ISSUE TITLE
"found" variable not updated when using unit locate if no unit is bound

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#3658]
**Platform**: *Windows*

**Build**: *119*

**Issue**: *When using the (terribly named) "unit locate" instruction without a unit bound, the "found" variable doesn't get set*

**Steps to reproduce**: 
`set x 5`  
`ulocate building core false @copper dx dy x dam`  
`print x`  
`printflush message1`
Connect to a message block and notice that x is whatever it was set to in the first line.
I looked at the code and RTFM to make sure i wasn't misunderstanding something and based on this comment https://github.com/Anuken/Mindustry/blob/c41dfa46aa99a59748a31ad6752497f2cd6ba5a0/core/src/mindustry/logic/LExecutor.java#L216 i'm 99% sure the processor is supposed to at least try to find a building with no unit bound. Even if it will always fail with no unit, it should still be set to "false" because nothing is found.

**Save file**: [Once again it happened on several saves but i don't want my soul reaped so here.zip](https://github.com/Anuken/Mindustry/files/5613207/Once.again.it.happened.on.several.saves.but.i.don.t.want.my.soul.reaped.so.here.zip)  

Although just copying the code will work.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** This may be the only reason I ever update my game
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> i'm 99% sure the processor is supposed to at least try to find a building with no unit bound

It's not. When no unit is bound, the instruction doesn't even try executing.

**Comment by DeltaNedas** [comment]
if it didnt need a unit it wouldnt be in ucontrol
