### ISSUE TITLE
sector exportation bug

### ISSUE THREAD

**Issue by hadron13** [Anuken/Mindustry#3659]
**Platform**: *Windows (probably all)*

**Build**: *BE 20141*

**Issue**: *I have many bases producing specific resources and sending them to my main base, last versions launch pad exportation just disappear sometimes, when I go to the sector the exportation magically reappears without even needing time to calculate*

**Steps to reproduce**: *enter a sector, export to some other sector, go to that other sector and wait about 3 minutes and look at the exportation of the first sector*

**Link(s) to mod(s) used**: *none*

**Save file**: *[tar fields.zip](https://github.com/Anuken/Mindustry/files/5613329/tar.fields.zip) tar fields where I produce plastanium but also happens on all my sectors*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not enough information given to reproduce issue. The given save exports fine when I'm in other sectors.

**Comment by hadron13** [comment]
happens after the first 'background' launch, then simply stops the exportation

**Comment by Anuken** [comment]
Again, doesn't happen to me. I can sit around for ~10 minutes and keeping getting resources, while the sector still has a positive export when viewed.

**Comment by hadron13** [comment]
entering campaign:
![gif1](https://user-images.githubusercontent.com/62845905/100627607-f6004d00-3305-11eb-98cd-2e74016d5c5e.gif)

after the first baground lauch:
![gif2](https://user-images.githubusercontent.com/62845905/100627625-fac50100-3305-11eb-8f78-dce5e94cf3e9.gif)

**Comment by Anuken** [comment]
Send me your game data. Not the save, the entire data zip.

**Comment by hadron13** [comment]
[data.zip](https://github.com/Anuken/Mindustry/files/5617237/data.zip)

**Comment by Anuken** [comment]
I have no issues with your save. Watching exports on Tar Fields, moving to the destination sector, waiting a few minutes for an export and checking Tar Fields again gives me positive exports. Nothing changes, and items keep coming.

![2020-11-30 12-00-09](https://user-images.githubusercontent.com/10100000/100639976-dbc56f80-3303-11eb-9b19-61b9f6b5d1ac.gif)

**Comment by hadron13** [comment]
in BE 20144 I didn't had the issue again, I don't know how but it's fixed now
