### ISSUE TITLE
Blocks with quickRotate = false still quick-rotates when a new block with a different rotation is placed on top of it.

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3661]
**Platform**: *Windows*

**Build**: *20141*

**Issue**: *Blocks with `quickRotate = false` quick-rotates when the same block with a different rotation is placed on top. This is the updated behavior, but it shouldn't do so for blocks with quickRotate disabled, since the point of that field is to make the building's rotation persist and be constant until it is broken(Reasons were given on my PR at that time). A suggested solution is to revert the behavior to what it was like before for blocks that has !`quickRotate`.*

**Steps to reproduce**: *Make a block with `quickRotate = false`. Easiest way is to just open console and type `Blocks.conveyor.quickRotate = false;`.*

**Link(s) to mod(s) used**: *null*

**Save file**: *codewise issue*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.   
*I doubt I have a soul inside me. Besides, what happens at (supposedly) InputHandler.java surely doesn't require a save file(or I hope so).*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
In the future, please make your own PRs to maintain features *you* have added. Since I don't have any use for this myself, and it's not a useful feature for the overwhelming majority of mods, it won't be maintained by me.
