### ISSUE TITLE
Tutorial omission - how to unload

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3666]
Build 119 beta

The mini in-game tutorial tells you how to mine stuff by clicking on a resource but doesn't tell you how to unload it (necessary if the player is mining away from the core).

**Comment by Anuken** [comment]
Wrong.

![image](https://user-images.githubusercontent.com/10100000/100643593-424c8c80-3308-11eb-86ef-6dd3c143d4c5.png)

**Comment by CitrusWire** [comment]
Yep, you're right; I only checked upt to the weapons thing and assumed it wasn't going to tell me. But it turns out it's the item right after that; figures.

I'd suggest that drop-items text should be the thing it tells you to do immediately after how-to-mine text.

**Comment by CitrusWire** [comment]
Actually I'm right.
It's more nuanced than that... if you're mining near the core the ship auto unloads. This means the player then never sees the "this is how to unload items" text - for me it doesn't show, I assume because the "player has done this thing" trigger is instantly activated by the auto unloading.

**Comment by Anuken** [comment]
No, you're not. It only shows that text if you have something to unload in the first place. This triggers even if you unload automatically.

**Comment by CitrusWire** [comment]
Ah. Now I see. That tutorial tip only shows up when you have something loaded; auto-unloading never triggers it because there's nothing loaded. Cheers.
