### ISSUE TITLE
Language = Router

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3670]
Build 119 beta - windows 7

There's a language called "router" on the languages list at the bottom. All the words become "router" if you enable it. Possibly meant to be there given it's "beta", but figured I'd report it just in case.

**Comment by Pietro303HD** [comment]
you're disrespecting people who speak router. isn't that right? router router router

**Comment by BlueWolf3682** [comment]
router

**Comment by CitrusWire** [comment]
I figure if you're going for a joke language, at least use one of these: https://en.wikipedia.org/wiki/Esoteric_programming_languages

🤓

**Comment by Anuken** [comment]
> I figure if you're going for a joke language, at least use one of these

This statement is a very strange joke.
