### ISSUE TITLE
2 Mindustrys running

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#3678]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
It happened when updating 20111 -> 20141 and 20141 -> 20148

**Issue**: *Explain your issue in detail.*
Updating to the latest build causes the old Mindustry build to freeze and launch the new build. So I have 2 running Mindustrys, but the old one never closes itself. If you exit the game its window disappears but it still runs in the background. Waited 10 minutes and the old Mindustry never closed itself. This started happening recently within the last few days. I tested this with older builds and this does not occur, only in recent builds.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Update Mindustry. When it finishes updating it will freeze. You cannot even click the cancel button. Next, press ctrl + alt + delete then open your task manager and you'll see 2 Mindustrys open, but only 1 window open. Click on that window and you'll see it's the new Mindustry. The old Mindustry window disappeared but the application is still running strong in the background consuming ram and cpu. The old Mindustry will not close unless you end task it in the task manager.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
NA

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
The game never crashed and no crash reports were generated :(

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not going to fix this.
