### ISSUE TITLE
Tech tree oddities - industry but no raw materials.

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3679]
Beta 119
Playing the campaign, the tech tree has some oddities in. I've completed Ground Zero and Frozen Forest, along with a couple extra non-named zones.

* I've got the spore press but no ability to create spores. Same for Blast Mixer.
* Coal Centrifuge but no oil
* Multipress but no water.

I'm guessing water/oil/spores are behind one of the red locked items which requires a named level to be completed.

**Comment by Anuken** [comment]
> Coal Centrifuge but no oil

You don't need oil to use the coal centrifuge.

> Multipress but no water.

Water comes unlocked.

> I've got the spore press but no ability to create spores. Same for Blast Mixer.

Fixed.

**Comment by Engaming-dev** [comment]
Can you research e.g the spore press before spore cultivators themselves?

**Comment by CitrusWire** [comment]
> 
> 
> > Multipress but no water.
> 
> Water comes unlocked.

I should have been clearer - yes "water"'s unlocked, but no pipes/pumps, so no ability to use anything that uses any liquids.

**Comment by CitrusWire** [comment]
Yep, doesn't look like you get metaglass (and thus plumbing) until completing The Craters. So anything using liquid before then can't be used.

**Comment by joshuaptfan** [comment]
You can use liquids without pipes by placing liquid-consuming buildings in direct contact with pumps/water extractors.
