### ISSUE TITLE
bugs.

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry#3684]
linux, all builds

i cant play any part of the game that requires onlineness. there are others with this issue.
i dont think i used anything. or did anything out of the ordinary.
i deleted the game files in a attempt to fix it.

**Comment by qqitjh233** [comment]
nooooo that means we can't play v6 stable today or tomorrow!!!!

**Comment by Engaming-dev** [comment]
I can join v6 online servers on my phone, maybe Linux is the only platform affected.

**Comment by Anuken** [comment]
your soul, hand it over
