### ISSUE TITLE
Tar Fields

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3685]
Build 119

This may be me misunderstanding the new campaign structure, but it seems named maps need to be unlocked.

However, I have access to "Tar Fields", without it being unlocked/shown in the tech tree. 
[sector-serpulo-193.zip](https://github.com/Anuken/Mindustry/files/5622478/sector-serpulo-193.zip)

---

Second, related bug with the same save - I've played it and lost to the guardian (took out my core). But if you click on the "Stats", it implies that there is still production, as it's listing production rates per minute for all the resources that were still producing at the end.

**Comment by Anuken** [comment]
This was already fixed.
