### ISSUE TITLE
Borderless setting misalignment 

### ISSUE THREAD

**Issue by DerpyMoa** [Anuken/Mindustry#3690]
**Platform**: Windows

**Build**: 120

**Issue**: Borderless setting isn't properly aligned compared to fullscreen.
Fullscreen: https://i.imgur.com/OcI0uMN.png
Borderless: https://i.imgur.com/ndQg2Yr.png

**Steps to reproduce**: Compare borderless setting to fullscreen.

**Link(s) to mod(s) used**: None.

**Save file**: It's a setting from main menu so no save.

**Crash report**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's the Steam FPS display, which is not part of the game. Comparing both screenshots, there are no problems with the game itself.

**Comment by LeoSko** [comment]
It seems to be related to previous issue I reported #2110 - same symptoms.
