### ISSUE TITLE
Problems with video graphics

### ISSUE THREAD

**Issue by VloBoo** [Anuken/Mindustry#3692]
**Platform**: *Windows*

**Build**: *120( релиз 6.0)*

**Issue**: *При заходе в миндустри неправильно идет изображение, при это игра полностью рабочая, видимо проблема с драйверами. Похожий эффект я встречал в программе для видеомонтажа, но там все легко исправилось , когда я переключил режим работы ноутбука на максимальную производительность( в миндустри все осталось также). Могу скинуть всю необходимую информацию об ноутбуке и файлах(драйверах) на нем.*
 
**Steps to reproduce**: *Скачал новую версию, запустил*

**Link(s) to mod(s) used**: *не использую*

**Save file**: *не играл в игровом мире*

**Crash report**: *игра не крашится*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image](https://user-images.githubusercontent.com/60321021/100758768-f03b6200-3400-11eb-8a6e-1753e9dafbe7.png)

**Comment by Anuken** [comment]
Duplicate. Use a different video card/drivers. I can't reproduce or fix this.
