### ISSUE TITLE
LAUNCH PADS NOT LAUNCHING BETWEEN SECTORS AS I PLAY

### ISSUE THREAD

**Issue by Sentinel28** [Anuken/Mindustry#3694]
**Platform**: *Android/iOS/Mac/Windows/Linux* Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Build 120

**Issue**: *Explain your issue in detail* The resources are not launching between sectors using launchpads even when playing on a sector.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* I have this sector 101 that has a plane logo, this sector is modded with hackustry back in beta days but it is turned off while I am playing when I encountered this bug since I used it once, while the other sectors are completely clean. Lately, I updated my game to build 120 and started a new sector to capture. What I always do as I capture a sector is, I start the sector > I go to the sector 101 > I click the launch pad the select the sector destination > I go back to that sector destination and wait for resources to go to core and fill it, so I can jumpstart my progress. But it didn't go as I expected, because before I updated to 120, it is working fine, but it is now stopped working and I assume it is a bug of the new update. The bugged sector is 153, near planetary launch terminal.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* https://github.com/QmelZ/Hackustry

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[DEC_1_2020.zip](https://github.com/Anuken/Mindustry/files/5623683/DEC_1_2020.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/100768912-691ec780-33c9-11eb-9066-52c166703ff8.png)

This counts and cheating and doesn't work anymore. You don't have any actual production in this sector.
