### ISSUE TITLE
Visual bug that nukes the screen

### ISSUE THREAD

**Issue by RedDragonMZ** [Anuken/Mindustry#3696]
**Platform**: *Windows 64-bit*

**Build**: *6.0 Build 120*

**Issue**: *The screen is nuked and green stripes flash across the screen. https://www.reddit.com/r/Mindustry/comments/k4nffo/pic_for_my_bug_that_has_green_line_across_the/
(the post is not mine)
![screen 1](https://user-images.githubusercontent.com/56732705/100765347-b2860b80-33f7-11eb-92cc-9e03b04baccd.PNG)

*

**Steps to reproduce**: *Everytime i start the game*

**Save file**: *the bug happens at the start of the game even after when there is no save file*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you haven't.
