### ISSUE TITLE
Captured a sector when I wasn't there

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3697]
Build 119 beta.
I started on Ruinous Shores, but by wave 10 or so it was clear I wasn't going to win it so I went to the planet map and started a new named map. When I left Ruinous Shores, there were some (~5?) small land enemies coming from the NW to the core and they had a straight route with 0 defenses between them.

I'm now on wave 10 on Stained Mountain and I've just had "new content unlocked" and "Ruinous Shores Complete" pop up. Sure enough, I go to the map and that sector is now secure. Huh? There's no possible way that I could have defeated the land units that were there when I left, let alone whatever else was to come.

This contains the saves for today. I'm not sure what the save scheme is, so included all of them.
[saves.zip](https://github.com/Anuken/Mindustry/files/5623824/saves.zip)

**Comment by Anuken** [comment]
You have loads of turrets with ammo set up on the shore. That counts.

**Comment by CitrusWire** [comment]
> 
> 
> You have loads of turrets with ammo set up on the shore. That counts.

I appreciate that you like to close tickets ASAP, but the downside to that is that bug reports get erroneously closed.

Those 5 units were PAST those turrets. See the gap between the turrets and the wall above them? Yeah, that's not meant to be a hole, they (and their predecessors) made it. They were past that hole when I wast last in that sector.

So:
a) How did those 5 units get killed when they were already past the defences and had a clear run to the core? And I know it was a clear run because the previous wave two land enemies got to the core through that route, and I never had time to rebuild anything.
b) How come later land waves from the NW didn't get through that big hole?

I assume you have dev tools in mindustry. I'll bet if you use them spawn a wave in the top left you'll see them get to the core an crush it.

**Comment by Anuken** [comment]
> a) How did those 5 units get killed when they were already past the defences and had a clear run to the core? 

The simulation is not advanced enough to take into account positions of all **living** units and whether they will cross turrets.

> b) How come later land waves from the NW didn't get through that big hole?

You have a massive row of turrets at the bottom of the map. The simulation doesn't care if there are multiple paths to the core - as long as the **whole** defense on **all** the paths to the core can take on **all** the enemies spawned, then it will survive. Ruinous Shores is more or less the only map where the spawn points are far enough apart for this detail to matter.

**Comment by CitrusWire** [comment]
Thanks for the clarification, that explains it.
