### ISSUE TITLE
mac os big sur mindustry v6 not opening

### ISSUE THREAD

**Issue by 420gang** [Anuken/Mindustry#3698]
Platfrom: mac os big sur 11.01

issue: the game saying that it is damaged and needs to be put in the bin

reproduce: download the game then open it
![Screenshot 2020-12-01 at 16 03 17](https://user-images.githubusercontent.com/75326635/100767815-19082b00-33f2-11eb-8f44-2d4eabc62a21.png)

**Comment by Anuken** [comment]
Your security system is being paranoid, there's nothing wrong with the application and nothing I can do about it.

**Comment by 420gang** [comment]
anyway to bypass it?

**Comment by 420gang** [comment]
ill attempt with out firewall

**Comment by Anuken** [comment]
You could attempt https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

**Comment by 420gang** [comment]
ok

**Comment by clarkedb** [comment]
> You could attempt https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

This worked for me on MacOS 11.4 (Big Sur). It comes down to manually removing the quarantine attribute:

```zsh
sudo xattr -r -d com.apple.quarantine /path/to/Mindustry.app
```
