### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry#3701]
**Platform**: *Android*

**Build**: *Release v120*

**Issue**: 
![Screenshot_2020-12-01-23-39-05-475_io anuke mindustry](https://user-images.githubusercontent.com/26910478/100769467-a79a9d80-342e-11eb-8bf4-383ee6d7cc81.jpg)

**Steps to reproduce**: *It happens on a Community Server with less than 10 players online, no enemies in sight.*

**Link(s) to mod(s) used**: *None*

**Save file**: *None*

**Crash report**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is likely a problem with a modded server.
