### ISSUE TITLE
Importing zip mods doesn't work

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#3703]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

build 120

**Issue**: *Explain your issue in detail.*

Pressing "import file" and selecting a zip file, then restarting the game to reload removes the mod.
Importing from github works.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. get a zip mod
2. open mindustry
3. press mods
4. press import
5. press import file
6. locate and select the zip
7. see that the mod is imported
8. press back
9. say "ok" to the "game will quit to reload mods" dialog
10. open the game
11. open the mods menu
12. see that the mod is nowhere to be seen
13. look at the mods folder and see nothing there

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

any mod will do the same thing, i tried with a couple of mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

happens on a fresh save

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

no crashes happening

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Android

This has been reported a million times on Android already.

**Comment by QmelZ** [comment]
> > Android
> 
> This has been reported a million times on Android already.
> 
> (it still doesn't happen on my devices or simulators)

i have searched for different key words in issue search, couldn't find anything similar actually
