### ISSUE TITLE
Game Crashes Randomly

### ISSUE THREAD

**Issue by RogerioPiatek** [Anuken/Mindustry#3704]
**Platform**: *Windows*

**Build**: *Release Build 120*

**Issue**: Crash when open some game mode, like campaign or custom.

**Steps to reproduce**: Sometimes when I click on campaign and choose where I want to go and click "Launch" the game crashes. Can happen in custom mode too, not that often.

**Link(s) to mod(s) used**: No mods, fresh install.

**Save file**: No saves when crash.

**Crash report**: A hs_pid_error (one appears when I close normally for some reason) 
[hs_err_pid7596.log](https://github.com/Anuken/Mindustry/files/5624794/hs_err_pid7596.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

*Edit: Explained with more details*

**Comment by Anuken** [comment]
This is an internal Java error, I can't fix this.
