### ISSUE TITLE
Terrain rendering with hard edges on certain maps

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#3705]
**Platform**: Windows

**Build**: 120

**Issue**: Rendering of edges of some terrain types can break on certain maps with long straight edges, causing them to be rendered as hard lines.

**Steps to reproduce**: Create a large map with large rectangular patches of terrain. When playing it, some terrain boundaries may render as hard lines.

Interrupting the affected straight edges, to make them not straight, causes them to render correctly.

**Link(s) to mod(s) used**: No mods

**Save file**: [Test map.zip](https://github.com/Anuken/Mindustry/files/5624883/Test.map.zip) [Test save.zip](https://github.com/Anuken/Mindustry/files/5624994/Test.save.zip)

![terrain hard edges](https://user-images.githubusercontent.com/15149002/100786871-a1250b00-33c7-11eb-8bd6-3f7014cbc878.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Happens due to issues related to large meshes and layers. Not something I can fix without breaking things right now.
