### ISSUE TITLE
Upgrading to 6.0 deletes global items

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#3713]
**Platform**: Linux

**Build**:  6.0 Build 120.2

**Issue**: I played Mindustry in one of previous versions and I wanted to play again without pointless grinding. So on the first launch of 6.0 I selected importing tech tree.

Tech tree got imported (though there are some oddities like "Capture XYZ" marked as unfulfilled).

Exported item count is lost, "global items" is empty

**Steps to reproduce**: Play 5, launch resources, play 6?

**Link(s) to mod(s) used**: not applicable

**Save file**: not applicable

**Crash report**: not applicable

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+global+items+is%3Aclosed https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+launcher+resources+is%3Aclosed+ https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+items+lost+ https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+reset+campaign+6

**Comment by Quezler** [comment]
only the unlocked tech nodes carry over when you import the tech tree, not any items:

https://github.com/Anuken/Mindustry/blob/c00228f960bef6bab9499f8b26a014bf62a7384a/core/src/mindustry/io/legacy/LegacyIO.java#L54

**Comment by matkoniecz** [comment]
> only the unlocked tech nodes carry over when you import the tech tree, not any items:

I hope that it is not intentional.

**Comment by Quezler** [comment]
the way items are calculated/handled/stored is unlike how the launched items in v5 worked, hence they weren't compatible & thus didn't get carried over to v6

**Comment by matkoniecz** [comment]
Is it impossible to simply copy values of launched items into global items counters?

**Comment by Blockguy24** [comment]
Global items don't exist in the same way they did in 5.0

**Comment by matkoniecz** [comment]
I will reopen if I will play 6.0 and see an obvious way to handle this.

**Comment by DeltaNedas** [comment]
you can have 2 billion copper in global items in 5.0, items are per-core in 6.0
