### ISSUE TITLE
iOS UI inside screen notch

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#3719]
**Platform**: iOS

**Build**: release build 120 (6.0.120)

**Issue**: UI elements in game are at the top edge of the screen.  iPhones with a notch on the top (such as the 11 pro max I use) cut off these elements, making them impossible to see and difficult to tap.  I think searching the internet for “iOS safe area inset” might yield a solution.  I suggest moving all elements in by the amount of the rounded corners/notch in the vertical/long dimension.

**Steps to reproduce**: Launch a new game and try to access the tech menu.  Also, the information and discord buttons on the main menu are cut off from rounded corners and the “Mindustry” logo is partially cut off by the notch.

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

**Comment by Anuken** [comment]
fixed

**Comment by willis936** [comment]
I can confirm that this is fixed in 6.120.3 (available to me on the app store ~6 hours ago).
