### ISSUE TITLE
Mono's don't mine in Ground Zero

### ISSUE THREAD

**Issue by JesseFlorizone** [Anuken/Mindustry#3720]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**:  Steam Build 120.2

**Issue**: Mono's do not mine Copper or Lead on Ground Zero

**Steps to reproduce**: Launch resources needed to build mono's to Ground Zero, go back to ground zero and build monos and make sure that there is space for copper and lead in the core, observe as they do not mine. I tried restarting the game and re-entering the sector but it still did not work

**Save file**: (url) https://easyupload.io/ji58bj
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They are trying to mine lead, but you have none available.

**Comment by JesseFlorizone** [comment]
But shouldn't they still mine Copper at that point if there is no lead available instead of doing nothing?

**Comment by BlueWolf3682** [comment]
uncover a single lead tile and they should function fine

**Comment by JesseFlorizone** [comment]
> uncover a single lead tile and they should function fine

I am aware of this, however wouldn't it be **cleaner** to make it so that they can mine copper even if all lead is covered? Unless it is something that would be difficult to alter of course.
