### ISSUE TITLE
Existing structures not usable

### ISSUE THREAD

**Issue by spirritus** [Anuken/Mindustry#3721]
Windows 7 x64

6.0
Steam build 120.2

On some maps there are existing buildings. Those are somehow deactivated and do nothing, e.g. bottom left in ruinus shores has an electrical pump water tanks and some other stuff. All of this isnot working.
Even the tank doesnot fill up even if the pipes are repaired.
[120.2.zip](https://github.com/Anuken/Mindustry/files/5630293/120.2.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not supposed to do anything.

**Comment by spirritus** [comment]
Good to know. They worked in the previous version (5)
