### ISSUE TITLE
sillicon crucible hidden slag affinity

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3724]
**Platform**: `mac`

**Build**: `20198`

**Issue**: silicon crucible doesn't list slag as an affinity:

![Screen Shot 2020-12-02 at 18 59 33](https://user-images.githubusercontent.com/3179271/100912394-b043b000-34d0-11eb-9018-5d57b647aca0.png)
![Screen Shot 2020-12-02 at 18 59 39](https://user-images.githubusercontent.com/3179271/100912402-b20d7380-34d0-11eb-8317-3755d92cc835.png)

the liquid check here is probably to blame: (possibly for water extractors?)
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/meta/Stats.java#L71

though it does show for the thermal:

![Screen Shot 2020-12-02 at 19 02 36](https://user-images.githubusercontent.com/3179271/100912612-ff89e080-34d0-11eb-89af-f986a621e854.png)

**Steps to reproduce**: hover a silicon crucible over a slag pool

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's intentionally not shown, because the crucible can't be placed on liquids. Displaying it would be misleading.

**Comment by Quezler** [comment]
then maybe don't count the tiles it can't be placed on from the efficiency hover?

**Comment by Anuken** [comment]
That doesn't seem like an important detail to me, because it can't be placed on them anyway.

**Comment by Quezler** [comment]
very well
