### ISSUE TITLE
Importing Research from pre-6.0 has UI issues

### ISSUE THREAD

**Issue by ajoy39** [Anuken/Mindustry#3725]
**Platform**: Ubuntu 20.04 and Windows 10, latest build

**Build**:  120.2

**Issue**: I get the menu to import my research progress from 5.0 every single time I go to the planet view. I selected to keep the progress the first time but have since also tried saying to start fresh, it did not clear my research and I still get the dialog. 

Conversely, my wife was never shown the option to carry over her research and had to start from scratch. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: None

**Save file**:  [mindustry_data.zip](https://github.com/Anuken/Mindustry/files/5631457/mindustry_data.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X]  **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
im gonna take a wild guess and say that youre using snap, dont.

**Comment by ajoy39** [comment]
> im gonna take a wild guess and say that youre using snap, dont.

I have snap running on my machine but Mindustry is installed through Steam.
