### ISSUE TITLE
Mine rate error

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry#3729]
**Platform**: *Android*

**Build**: *6-official-120 *

**Issue**: *If I activate the graphic setting "pixelate", the drills doesn't show the mine rate, they just show what are mining*

**Steps to reproduce**: *Activating Graphic setting "pixelate"*

**Link(s) to mod(s) used**: *I didn't use any mod*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Because the mining rate would look like a garbled mess with pixelation on.

**Comment by GreyMario** [comment]
Then it, along with other tooltip-like drawings, should probably be drawn in a separate layer, but that would require some changes.

To-do-eventually, I'm sure.
