### ISSUE TITLE
Core Database/Block Info discrepancies b120

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry#3730]
**Platform**: Android

**Build**: 120

**Issue**: Core database shows certain blocks' liquid consumption 0.1 less per second than they actually are

**Steps to reproduce**: Check core database/block info

**Link(s) to mod(s) used**: N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Does not a save, as you can access the database without starting to play.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'll guess that this is a side-effect of that the fact that it rounds down now.
