### ISSUE TITLE
User Interface 

### ISSUE THREAD

**Issue by GreenGradientMan** [Anuken/Mindustry#3731]
**Platform**: iOS

**Build**: 120

**Issue**: The interface for mindustry doesn’t take the notch for x models into account, and clips off the screen on the edges. 

**Steps to reproduce**: Boot up the game normally 

**Link(s) to mod(s) used**: None

**Save file**: Happens everywhere, including main screen

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
I mean.. is it really our fault that hardware developers are eating into screen space?

**Comment by Anuken** [comment]
Already reported, fixed and pushed, wait for Apple to approve the update.

**Comment by itcannotbe** [comment]
If only people made an effort to actually search for duplicates, we won't be having this conversation.
