### ISSUE TITLE
Game went black

### ISSUE THREAD

**Issue by stoneRdev** [Anuken/Mindustry#3732]
So, i was playing on ruinous shores, and the game started zooming out, like all the way out until the whole screen was black, minus the UI

**Comment by stoneRdev** [comment]
![Uploading Screenshot_20201202-204522.png…]()

**Comment by stoneRdev** [comment]
Frozen forest looks the same, and that one didn't even zoom out, but the rest are still  normal

**Comment by Anuken** [comment]
Template.

**Comment by stoneRdev** [comment]
on mobile, cant really do that. if i use my computer, i dont have the screenshots or the save files

**Comment by Anuken** [comment]
All of that is required to debug the problem.

**Comment by stoneRdev** [comment]
I will try. I got you
