### ISSUE TITLE
Game went black

### ISSUE THREAD

**Issue by stoneRdev** [Anuken/Mindustry#3733]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
release build 120.3

**Issue**: *Explain your issue in detail.*
While playing Ruinous Shores, the screen zoomed out until everything was black, but the UI was present. This also affected Frozen Forest, which didn't even zoom, it just loaded in like that. All other areas are still normal. I tried exporting my game data, resetting the game data, then importing the data back in, but the issue persisted. Resetting the game data and starting a new game does not have this issue, it seems to only be with my save file. I've also tried reinstalling the game and clearing the data in the app settings but the issue persisted when I reimported my game data.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was playing Ruinous Shores, just finished wave 3 and this happened. Not sure if this is reproducible, but I can provide my game data as I'm sure the issue will be present when the data is imported.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[x0hUppaDusHU.zip](https://github.com/Anuken/Mindustry/files/5633790/x0hUppaDusHU.zip)
![bEHM3OC7KHKU](https://user-images.githubusercontent.com/16456386/100967280-c2e8d400-3526-11eb-84d4-dc6beaeb8348.png)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your player's position is at NaN. Seeing as nobody else has reported a problem like this, it's possible that it may be caused by the mod you installed. I can't reproduce this.

**Comment by stoneRdev** [comment]
Dude, if you read the issue, I don't have any mods installed. But since my players position is at NaN, do you have a way I can correct that? A command in game? Unzipping a save file and editing the position?

**Comment by stoneRdev** [comment]
Also, I can completely relate to the satisfaction of an empty issue list, but this issue is not 'closed'. You stated it was from a mod and closed it, but I also clearly stated in the template that there are no mods. I love this game, but I've already lost Ruinous Shores to this bug and also Frozen Forest. If this keeps happening, then my hundreds of hours of play time (just on this campaign) is basically trash. Please be more open to help the people that enjoy your work (and also paid for it)

**Comment by angrychalenge** [comment]
Hey, this just happened to me on ground zero. I don't want this to happen on other sectors so I'm saying it here. Only mod I had installed was "pictologic" and I don't think it's the cause of this problem as it only makes images into logic. If I need to post any save file here I'll do it.

**Comment by liuxilu** [comment]
Mod `DeltaNedas/dev-mode`: type `Vars.player.set(0, 0);`

**Comment by angrychalenge** [comment]
> Mod `DeltaNedas/dev-mode`: type `Vars.player.set(0, 0);`

I'm guessing this will teleport me to 0, 0. Thanks for sharing this but it still doesn't solve why this bug happens.

**Comment by liuxilu** [comment]
How can this be fixed without reproduce 🤷

**Comment by angrychalenge** [comment]
> How can this be fixed without reproduce 🤷

I don't know, since now I know how to go back once the bug happens, I'll probably try to reproduce it
