### ISSUE TITLE
Very high ram usage

### ISSUE THREAD

**Issue by MichaelTrudeau** [Anuken/Mindustry#3736]
**Platform**: *Android 9*

**Build**: *6-official-120.3*

**Platform Model**: *Samsung Galaxy S8+/ 4GB RAM*

**Issue**: *Whenever I play multiplayer for some time, this issue arises. Such issue was never present on the previous version no matter how big the map was and no matter how long I played on the map. However, on this version, this issue arises on very average maps when I barely play for 20 minutes. Also, Such issue never arose with my custom map.*

**Steps to reproduce**: *Playing on any PVP multiplayer map for minimum 20minutes.*

**Link(s) to mod(s) used**: https://github.com/DeltaNedas/rtfm

**Save file**: [https://drive.google.com/file/d/1Ka8IF7nIs5fGGKadtZulVRcmkffVtjx9/view?usp=drivesdk](Download) 

**Crash report**: 
![Screenshot_20201203-133243_Mindustry](https://user-images.githubusercontent.com/20300736/101013685-59d87f00-356d-11eb-8ea9-c2f74e87e0b8.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The memory usage is coming from sync packets of blocks that *should not be synced*. You may be playing on a modified server, or there may be a bug with syncing constructing blocks. I can't fix this (or even find out what the problem is) without knowing which specific servers you were playing.

**Comment by itcannotbe** [comment]
Just to point out that mods are usually disabled while playing multiplayer unless the server actually requires you to have a mod.

**Comment by Anuken** [comment]
There are servers that mess with sync packets, which is what I'm referring to.

**Comment by DeltaNedas** [comment]
(nydus)

**Comment by MichaelTrudeau** [comment]
The server I was playing was Very Good PvP from Mindustry.pl
