### ISSUE TITLE
Display on iOS iPhone X

### ISSUE THREAD

**Issue by greenhor** [Anuken/Mindustry#3738]
**Platform**: iOS *Android/iOS/Mac/Windows/Linux*

**Build**: 120
*The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: *Explain your issue in detail.*

The display is slightly higher than the real size of the screen => can’t access to all buttons top left of the screen + we don’t see hours and battery charge anymore. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
much better, thank you, but i believe this issue has already been reported (check closed issues, its fixed and waiting for an update)

**Comment by greenhor** [comment]
Thanks for the answer.I look for it and only 2 have been posted less than 3 days ago, so before your last update...so I couldn't find the same issue than mine...sorry.Just hope you'll be able to fix this as the worst is that I can't access to the button "pause" anymore...quite difficult then...I discovered the game a few days ago and I am already addict...you did a GREAT game !!! Congrats and thanks !I downloaded for both, my iPhone and my iMac (but on iMac, it's a 2018 version and it crashes often...so I only play on iPhone. Bit a pity because the usage of the mouse would help a lot but ok :-)All the best and great job again !Cédric
    Le jeudi 3 décembre 2020 à 13:11:27 UTC+1, BlueWolf <notifications@github.com> a écrit :  
 
 


much better, thank you, but i believe this issue has already been reported (check closed issues, its fixed and waiting for an update)

**Comment by willis936** [comment]
https://github.com/Anuken/Mindustry/issues/3719
