### ISSUE TITLE
Coal on Plastanium Conveyor use Copper texture

### ISSUE THREAD

**Issue by TerraStalker** [Anuken/Mindustry#3739]
**Platform**: Windows

**Build**: Steam build 120.3
**Issue**: Coal on Plastanium Conveyor using Copper texture

**Steps to reproduce**: Place Coal on Plastanium Conveyor

**Link(s) to mod(s) used**: No mods

**Save file**: 
[Coal in Copper.zip](https://github.com/Anuken/Mindustry/files/5636081/Coal.in.Copper.zip) 

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
**Screenshot** 
![Coal in copper](https://user-images.githubusercontent.com/75429002/101019860-a4162c00-357e-11eb-90fa-1e9949cb682c.PNG)
![Coal in Copper1](https://user-images.githubusercontent.com/75429002/101019876-a8dae000-357e-11eb-95a9-ae2cbc82b3b6.PNG)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/101042502-43b9c700-354b-11eb-829a-33a25224886f.png)

Cannot reproduce.
