### ISSUE TITLE
Overriding ore position.

### ISSUE THREAD

**Issue by MichaelTrudeau** [Anuken/Mindustry#3740]
**Platform**: *Android 9*

**Build**: *6-official-120.3*

**Issue**: *The game is overriding ores I personally placed on custom maps with random ores. Most of the time, it overrides sand with any other ore. This happens whenever I load my custom map.*

**Steps to reproduce**: *1-Create a custom map. 2. Press the Three Lines. 3.Generate. 4. Random. 5 -Place ores and place sand on the map.*

**Link(s) to mod(s) used**: *No mods used.*

**Save file**: [https://drive.google.com/file/d/1aqq1RlCMxflxricbA5WosOfg4RvnnMkn/view?usp=drivesdk](Download) NOTE: Load it as a custom map.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
do you want to disable custom ores, or just prevent them from being near/over already existing ores?

**Comment by MichaelTrudeau** [comment]
I want to prevent the game from overriding player-placed ores

**Comment by Anuken** [comment]
This is not a bug, remove the ore generation from the map settings.

**Comment by joshuaptfan** [comment]
The ore generation settings are in Map Info > Generation.
