### ISSUE TITLE
Error kicked my out of a server

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#3741]
![Screenshot_20201203-153131_Mindustry](https://user-images.githubusercontent.com/49868160/101041637-c1e29180-357c-11eb-8c7b-7ea5beb92131.jpg)
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
120
**Issue**: *Explain your issue in detail.*
Got an error see screenshot
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Was at random don't know how to reproduce
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

Don't know how to upload a file on mobile github

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
How do I get crash report
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.

**Comment by antonilol** [comment]
Hope you fix it soon

**Comment by Anuken** [comment]
This is a problem with a modded server, and I already did.
