### ISSUE TITLE
My chash

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry#3742]
@Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 120
OS: Linux x32
Java Version: 0
Java Architecture: null
0 Mods

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.modules.ItemModule.get(mindustry.type.Item)' on a null object reference'
Building.acceptItem: 1245
Conveyor$ConveyorBuild.pass: 258
Conveyor$ConveyorBuild.updateTile: 235
Building.update: 1092
-$$Lambda$YLG6AvmE6BBi-QxdrWn0CEMuwAo.get: 2
EntityGroup.each: 68
EntityGroup.update: 58
Groups.update: 71
Logic.update: 359
ApplicationCore.update: 36
ClientLauncher.update: 153
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1581
GLSurfaceView$GLThread.run: 1280

**Comment by Anuken** [comment]
Template.
