### ISSUE TITLE
Kaviaki. Crash

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry#3746]
**Platform**: *Android*

**Build**: *6-official-120.3*

**Issue**: *I cant enter to a map of the campain, the games crashes*

**Steps to reproduce** *I cant remember how I did it, but I just playing the campain like everyone does*

**Link(s) to mod(s) used**: *0*

**Save file**: *I cant, my crash happens in the campain, in Overgrowth*

**(Crash) logs**: *Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 120
OS: Linux x32
Java Version: 0
Java Architecture: null
0 Mods

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.modules.ItemModule.get(mindustry.type.Item)' on a null object reference'
Building.acceptItem: 1245
Conveyor$ConveyorBuild.pass: 258
Conveyor$ConveyorBuild.updateTile: 235
Building.update: 1092
-$$Lambda$YLG6AvmE6BBi-QxdrWn0CEMuwAo.get: 2
EntityGroup.each: 68
EntityGroup.update: 58
Groups.update: 71
Logic.update: 359
ApplicationCore.update: 36
ClientLauncher.update: 153
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1581
GLSurfaceView$GLThread.run: 1280*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.

**Comment by Kaviaki** [comment]
I don't understand how to use this, sorry
