### ISSUE TITLE
Game went black - Not solved by previous issue closure

### ISSUE THREAD

**Issue by stoneRdev** [Anuken/Mindustry#3750]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
release build 120.3

**Issue**: *Explain your issue in detail.*
While playing Ruinous Shores, the screen zoomed out until everything was black, but the UI was present. This also affected Frozen Forest, which didn't even zoom, it just loaded in like that. All other areas are still normal. I tried exporting my game data, resetting the game data, then importing the data back in, but the issue persisted. Resetting the game data and starting a new game does not have this issue, it seems to only be with my save file. I've also tried reinstalling the game and clearing the data in the app settings but the issue persisted when I reimported my game data.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was playing Ruinous Shores, just finished wave 3 and this happened. Not sure if this is reproducible, but I can provide my game data as I'm sure the issue will be present when the data is imported.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[x0hUppaDusHU.zip](https://github.com/Anuken/Mindustry/files/5633790/x0hUppaDusHU.zip)
![bEHM3OC7KHKU](https://user-images.githubusercontent.com/16456386/100967280-c2e8d400-3526-11eb-84d4-dc6beaeb8348.png)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stoneRdev** [comment]
So I had to remake this issue, because on the previous one, anuken closed it saying it was due to a mod, but I have clearly stated in the template that there are no mods installed

**Comment by stoneRdev** [comment]
Anuken has also stated that my players position in the erroneous maps is NaN, so maybe we can work from there

**Comment by stoneRdev** [comment]
Anuken, is there any debug terminal in the game I can manually set the players position with? or can I unzip a save file and manually fix the position?

**Comment by itcannotbe** [comment]
Well to be honest, no fix was made with your.previous close issue.
The dev just stated what he sees from the save file.you.sent.
And since nobody else has reported this issue, the dev dismissed this issue as only affecting the device you are playing on.

**Comment by stoneRdev** [comment]
Thats why I remade it, there was no attempt at a fix. And I also stated that the dev stated it was from a mod when I had stated I have no mods

**Comment by stoneRdev** [comment]
It doesn't seem like a device issue if I can import my save to another device and have the same issue. That seems like the new update (based on what anuken said) somehow allowed the players position to be set to NaN. This could even be fixed by having a check like  `if(player.position == NaN) player.position = core.position;`. clean, simple, prevents unplayability, and is backwards compatable

**Comment by stoneRdev** [comment]
I have played this game for years, I even still have the original mindustry (What I guess is now classic) on my old tablet. Since the player's ship was added to the game, I've never had this happen until now.

**Comment by stoneRdev** [comment]
![20aF6MEwlrOU](https://user-images.githubusercontent.com/16456386/101074622-dfbdef80-3598-11eb-818d-e813987bd9f2.png)
So this doesn't get closed and blamed on a mod again

**Comment by BlueWolf3682** [comment]
well, are you in posession of a unit? by the location, i would guess not.

**Comment by stoneRdev** [comment]
Well, if you look at the other screenshot, you'll see I'm in possession of the player's ship.

**Comment by Anuken** [comment]
> It doesn't seem like a device issue if I can import my save to another device and have the same issue. 

The position is stored on the save, so of course it would be the same *once imported*. The **cause** of the issue is still something that only seems to happen on your device. Sure, I can load your saves and verify that the position is NaN, but when I launch to the maps you mention *on a phone* and move around/scale the screen, nothing interesting happens.

> You stated it was from a mod and closed it, but I also clearly stated in the template that there are no mods.

The reason I said this is because I was importing saves consecutively to test other reports, and (apparently) one of them came with mods, which were carried over to your save once I imported it.

> This could even be fixed by having a check like 

I already added such a check, but it does not address the real problem.

**Comment by stoneRdev** [comment]
If there is a check for player position being NaN, then it's obviously not working since this happened.

**Comment by Anuken** [comment]
Your version doesn't have it.

**Comment by stoneRdev** [comment]
What version has it? I have already updated to the latest version on google play

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/commit/9fa2691b02a38416f4672a5e6d007faa5bc72a26

**Comment by stoneRdev** [comment]
And I'm even on the beta channel for google play, so I'm assuming I should have the most recent version

**Comment by stoneRdev** [comment]
Ahh, 4 hours ago, gotcha. Do you know how long this will take to make it to Google play beta testers?

**Comment by itcannotbe** [comment]
He added a check in the source, which is not published yet.

Also constantly respawning/teleporting to the core position will be annoying, so better find out why is it turning to NaN than just making a fix that doesn't fixes anything.

**Comment by stoneRdev** [comment]
I'd rather be stuck at the core than stuck at a black screen

**Comment by stoneRdev** [comment]
Atleast being at the core, you can see if there's any other behavior happening alongside, at the black screen you cant see anything or test anything else

**Comment by stoneRdev** [comment]
And I don't know why it went NaN, like I said in the issue, I was playing the level, just finished wave 3, was flying back to the core from the top spawn point on Ruinous Shores, and while I was looking at the core waiting for the ship to catch up, the game starting zooming out, waay out until everything was black. I spent all wave 4 trying to zoom back in, then went to check my other sectors, and Frozen Forest looked the same even though it didn't zoom out, but all the other sectors are normal

**Comment by Anuken** [comment]
As I said before, it doesn't happen to me, and I don't see any obvious causes. Unless I get more reports that give more of an insight into what happens, there is no way for me to conclusively fix anything.

The beta has been around for months with many, many people on Android playing it. I haven't seen a single report (formal or informal) about this. If it were a common problem, we would know already.

**Comment by stoneRdev** [comment]
Gotcha. Any options for me fixing this myself? Is there a format I could load the save data in? Or could I maybe make a mod to set my player position to the core?

**Comment by Anuken** [comment]
import `DeltaNedas/dev-mode`, run `Core.camera.position.setZero(); Vars.player.set(0, 0)`

**Comment by stoneRdev** [comment]
Run that as a mod? If so I can figure the rest out
