### ISSUE TITLE
discord stream + dragged router = game crash

### ISSUE THREAD

**Issue by frogman85978** [Anuken/Mindustry#3752]
**Platform**: Windows

**Build**: 120.3

**Issue**: game instantly crashes when I place sorters set to anything in a line while streaming the game on discord.

**Steps to reproduce**: start streaming the game on discord then place a row of sorters set to anything

**Save file**: 
[save.zip](https://github.com/Anuken/Mindustry/files/5638265/save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: it says "no crash logs found" 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> it says "no crash logs found"

Then I can't debug this issue. This sounds like a Discord issue.
