### ISSUE TITLE
Unit Pathfinding bug with router offloading

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3753]
Build 120

As you can see below (Overgrowth map), there are a number of units that have clustered together on the first router in my unit production complex. They keep trying to walk over the payload router and then bouncing backwards. They're trying to get the rallying command centre (top right)

If I remove the Payload Router they then walk on to the command centre. Only issue is, there seem to be any number of other paths to the command centre that don't entail going over the router.

![image](https://user-images.githubusercontent.com/72134064/101076099-cfa70f80-359a-11eb-9b21-4e2c97cb1336.png)

(Save is from after removing then replacing the router. Build more units to see the bug again.
[sector-serpulo-134.zip](https://github.com/Anuken/Mindustry/files/5638400/sector-serpulo-134.zip)

**Comment by Anuken** [comment]
The pathfinding system doesn't take into account things like specific directions of routers and what direction they would move units in. That's far too specific.

**Comment by CitrusWire** [comment]
> 
> 
> The pathfinding system doesn't take into account things like specific directions of routers and what direction they would move units in. That's far too specific.

Maybe I'm misunderstanding your reply, but the router direction itself isn't the problem. The units are correctly offloaded from it as far as I can tell. The problem is that the units are then trying to walk over it to get to the CC.

Unless you're telling me that there's a legitimate path for any land unit to walk over a router from anywhere to anywhere via a router that has an arrow in the correct direction, I'm not sure I follow your reasoning. I would have expected that routers are marked as "not navigable" to any free-roaming unit irrespective of the arrow direction.

**Comment by Anuken** [comment]
> Unless you're telling me that there's a legitimate path for any land unit to walk over a router from anywhere to anywhere via a router that has an arrow in the correct direction

There is.

![2020-12-03 14-22-53](https://user-images.githubusercontent.com/10100000/101077625-15e87880-3573-11eb-957b-ac362d92c942.gif)

Unless routers are pointing in the opposite direction, there's little reason to avoid them. In fact, players may even *expect* units to go over them, as that speeds things up.

**Comment by CitrusWire** [comment]
Thanks for the clarification. Interesting.

In that case I'd suggest either:
a) Pathfinding to take into account the router arrow direction. (But you kind of dismissed that already)
b) Allow units to walk over routers irrespective of the direction the arrow is pointing.
c) Don't allow pathing over routers.

I don't think (a) is a good solution anyway because the router arrow can change direction effectively randomly (probably controllable via the logic stuff I guess, but that's beyond the scope of this ticket).

Without doing one of those things I anticipate quite a few players are going to hit this bug when they start discovering unit payloads.

I guess the optimal solution to go beyond just bug fixing and into feature request spectrum would be to make the pathfinder take into account payload arrow directions, and proactively use them for pathing, thus getting the aforementioned speed-boost.

(Great work on 6.0 btw)

**Comment by Anuken** [comment]
> I guess the optimal solution to go beyond just bug fixing and into feature request spectrum would be to make the pathfinder take into account payload arrow directions, and proactively use them for pathing.

That's not viable. Pathfinding cannot update often, and routers can rotate very frequently.

> Without doing one of those things I anticipate quite a few players are going to hit this bug when they start discovering unit payloads.

It's not really a bug. Units simply aren't smart enough to know whether they are strong enough to move past conveyors/routers. Keep in mind that it isn't that simple - some larger units may be able to walk past the conveyors depending on their mass. I'm not going to be creating a special pathfinding field just for that case.

If you have your own mass conveyors set up in the opposite direction, you would run into the same problem. Avoiding them would be counterproductive in most cases. Players will simply need to rotate the conveyors/routers to allow their units to pass.
