### ISSUE TITLE
More waves with no enemy bases

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry#3754]
**Platform**: *Windows*

**Build**: *Version 120*

**Issue**: *you just get 20 more waves in a sector without an enemy base nearby when you leave and come back.*

**Steps to reproduce**: *go into campaign and hop into a sector without an enemy base, for me, it's sector 175, and leave and come back, and you'll get 20 more waves.*

**Link(s) to mod(s) used**: *never used any mods*

**Save file**: 
[lol mehgame.zip](https://github.com/Anuken/Mindustry/files/5638597/lol.mehgame.zip)
**

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no crashes.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That sector isn't captured. If you *lose the sector*, of course you'll get 20 more waves, because you failed to capture it.

If I capture the sector, leave and come back, nothing interesting happens.

**Comment by Neil2101** [comment]
but I didn't lose the sector, instead I was in the process of capturing it, but let's say I need to do other stuff, so I leave the sector to not get destroyed when I was gone, but when I cone back, there's a penalty of 20 more waves on my head!

**Comment by Anuken** [comment]
That did not happen to me when I played it.
