### ISSUE TITLE
Cannot Create T5 Units in Campaign

### ISSUE THREAD

**Issue by LauSto** [Anuken/Mindustry#3760]
**Platform**: *Windows*

**Build**: 120.3
**Issue**: When producing T4 units in the exponential reconstructor in the campaign, the finished units are only moved onto an empty tile. Placing a payload conveyor, router or tetrative reconstructor will cause the unit to get stuck and no new units will be produced. Removing the conveyor causes the unit to exit normally. As a consequence it is impossible to create T5 units.

**Steps to reproduce**: Create a unit in the exponential reconstructor in the campaign and place a payload conveyor adjacent to the output. Such a setup is found in sector 148 in the save. 

**Link(s) to mod(s) used**: No mods were used.

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5640360/saves.zip)

**(Crash) logs**: The game does not crash from this issue.

![T4_no_exit](https://user-images.githubusercontent.com/47387922/101117168-bdeb5980-35e6-11eb-8453-1321c58a3d0c.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
This is intentional, what do yoy expect when putting a big unit to a small conveyor

**Comment by Bohaska** [comment]
This is not a bug. You must put the tetrative reconstructor next to the exponential reconstructor

**Comment by LauSto** [comment]
Thanks for the info. Originally it also got stuck when putting the tetrative reconstructor adjacent, but I am unable to reproduce that now. Everything is working as it should then.
