### ISSUE TITLE
Sorter and overflow class transportation blocks still practically instantly move items.

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry#3763]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
120.3
**Issue**: *Explain your issue in detail.*
Sorters and overflows practically instantly sort items
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Go to sandbox and put anything through a sorter/overflow class transportation block

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.
I am 100% sure that other people have this glitch. Just look at your own game if you don't believe me
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
Search terms: Sorter, Sorter instant, Overflow instant

**Comment by itcannotbe** [comment]
Not a bug.

Also overflows don't move items instantly.

**Comment by Bohaska** [comment]
> Also overflows don't move items instantly.
1/60 of a second is practically instant, as there is no conveyor that can do 60 per second.

**Comment by Anuken** [comment]
Intentional.

**Comment by Sp3rw3r** [comment]
I thought sneks were dead, but someone managed to still build one. WB sneks?
