### ISSUE TITLE
Multiplayer lan worlds issue

### ISSUE THREAD

**Issue by TastyGold** [Anuken/Mindustry#3768]
**Platform**: *Mac*

**Build**: *120.3*

**Issue**: *The game cannot find a local server in the lan world list. The only way I have found to connect is by direct IP using the remote servers. That does work sometimes, we can join the world, but then are stuck, and cannot move or see other player. The host can see them, but they are unable to move.*

**Steps to reproduce**: *Two devices on the same wifi. One creates game and hosts. The other puts the IP of the host into add server. Can join, but from there are stuck.*

**Link(s) to mod(s) used**: *n/a*

**Save file*: *Attempted hosting from custom and default maps, and campaign, all the same issue. Tried hosting and joining from 4 difference devices, half couldnt join, the others were stuck when they did.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *n/a*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The game tries every approach it can to find local games; if it doesn't work, your network is preventing it.
