### ISSUE TITLE
Enemy land Guardians units cause stuck any other land units on enemy base

### ISSUE THREAD

**Issue by quanium** [Anuken/Mindustry#3769]
**Platform**: *Windows 10 x64*

**Build**:  20210

**Issue**: Enemy land Guardians units cause stuck any other land units on enemy base

**Steps to reproduce**: 
1. starting sector 69 
2. play until Guardian appears
3. see how High tier unit stuck in enemy wall preventing any other ground units to move.
pro: enjoy only avia units
contra: on waves 60+ there are more 300+ units waiting on enemy bases
**Link(s) to mod(s) used**: ----

**Save file**: 
[saves+settingsMindustry.zip](https://github.com/Anuken/Mindustry/files/5641874/saves%2BsettingsMindustry.zip)

They stopped on yellow rectangle
![screenshot-69](https://user-images.githubusercontent.com/738857/101149140-92d92800-362f-11eb-92e8-2f8cf7f82008.png)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/101181919-73380480-361b-11eb-9e2c-112541de0aa5.png)
![image](https://user-images.githubusercontent.com/10100000/101182217-cd38ca00-361b-11eb-9cbe-aae6f91033f1.png)


[Cannot reproduce.](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#i-cannot-reproduce-your-issue)
- Your screenshot has no units in it. 
- There is a clear path to the player core, and ground units are able to make it to the player core with no blockage.
- When I play it, the guardians are Toxopid units, which do not cause any problems.

**Comment by quanium** [comment]
Reproduced

There is a 5 attempt to capture sector 69

[saves.zip](https://github.com/Anuken/Mindustry/files/5644916/saves.zip)


![screenshot-1607108811401](https://user-images.githubusercontent.com/738857/101204607-88de1600-367d-11eb-9f18-64da5da8cbd7.png)
