### ISSUE TITLE
Random black stuff appearing in editor

### ISSUE THREAD

**Issue by BruhderBoi** [Anuken/Mindustry#3770]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
120.3
**Issue**: *Explain your issue in detail.*
A random black stuff appear in editor when placing a core then pressing undo
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
![Screenshot_2020-12-04-17-59-22-04](https://user-images.githubusercontent.com/73068966/101150608-7226c780-365b-11eb-84e2-083d532d3b8b.jpg)
It happens when you place any core block then pressing undo button it only happens if you place the core between blocks and in empty space
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The editor has many such bugs, and they're practically impossible to fix. I'm not gong to touch it until a rewrite.
