### ISSUE TITLE
Green stripes on the screen

### ISSUE THREAD

**Issue by Jaujahuil** [Anuken/Mindustry#3771]
**Platform**: *Windows*

**Build**: *6.0 build 120.3*

**Issue**: *When I launch the game, green stripes appear all over the screen (linked a screen from the game). I already tried to update my graphic pilot but the bug to come from the game itself*

**Steps to reproduce**: *I just launched the game.*

**Link(s) to mod(s) used**: *No mods.*

**(Crash) logs**: *Not a crash so no crash log.*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image_2020-12-04_114244](https://user-images.githubusercontent.com/75478144/101154286-d333a880-3625-11eb-928d-32c658e54e40.png)

**Comment by Quezler** [comment]
check the pins in the #development channel on the mindustry discord

**Comment by Legomonster33** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

this has already been reported like 5 times,
this isnt anukes fault.
your device is just acting up, try updating your drivers.

**Comment by DeltaNedas** [comment]
to update drivers `apt install libgl1-mesa-glx`
