### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by CxZxRainzzz** [Anuken/Mindustry#3774]
Android
Game Crashes

By logging in on v6
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
rip boxes 
![image](https://user-images.githubusercontent.com/54417042/101176181-21d84700-3614-11eb-89b0-af22c13f01cd.png)
bruh
![image](https://user-images.githubusercontent.com/54417042/101176217-2ef53600-3614-11eb-890e-b284b58693f4.png)
also bruh 
![image](https://user-images.githubusercontent.com/54417042/101176255-3ae0f800-3614-11eb-987d-7be8b2d8dde8.png)

**Comment by Legomonster33** [comment]
also also bruh 
![image](https://user-images.githubusercontent.com/54417042/101176341-56e49980-3614-11eb-803f-5b3fa3bab5eb.png)

**Comment by CxZxRainzzz** [comment]
Haha, thanks!  It was V6 am 120

**Comment by CxZxRainzzz** [comment]
And I'm on mobile can't find that

**Comment by Anuken** [comment]
[Missing template.](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#you-did-not-fill-in-the-template)
