### ISSUE TITLE
Scripts don’t work on IOS

### ISSUE THREAD

**Issue by WHITED4WN** [Anuken/Mindustry#3775]
**Platform**: *iOS*

**Build**: *release build 120.3, however i am sure it has been an issue since V5.*

**Issue**: *any scripts in a mod do not work, if a mod is meant to activate dev mode, it cannot. If a mod has turrets that use scripts, the turrets break.*

**Steps to reproduce**: *download or create a mod that uses scripts and play with it on IOS version of mindustry, deltanades/dev-mode and deltanades/iu-lib both are moss I know that use scripts.*

**Link(s) to mod(s) used**: *deltanades/dev-mode deltanades/ui-lib.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
 **I have read the line above however iOS is preventing me from pasting the file in the issue report box, yes I have read it, please don’t reap my soul**

**(Crash) logs**: *N/A.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not supposed to.
