### ISSUE TITLE
Enemy waves getting stuck in their base.

### ISSUE THREAD

**Issue by CitrusWire** [Anuken/Mindustry#3779]
Build 120.3 - Windows

May or may not be the same as - https://github.com/Anuken/Mindustry/issues/3769

Enemy waves have got themselves stuck one or two waves ago. There's a guardian in there somewhere too. They're now just building up numbers, with other the "can walk over things" units coming at me.

[sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/5645552/sector-serpulo-15.zip)

![image](https://user-images.githubusercontent.com/72134064/101216293-2bdf6180-3677-11eb-8972-abf42a337fa2.png)

**Comment by CitrusWire** [comment]
They all decided to come at me about 5 waves later...

**Comment by Anuken** [comment]
> They all decided to come at me about 5 waves later...

That means there still was a path to the core, and there's nothing I can do about temporary jams.

> sector-serpulo-15.zip

That save is just Ground Zero, not what you have in the image.

**Comment by CitrusWire** [comment]
Yep, there was definitely a path, they took it for the first ~59 waves after all. I think the issue is that the path is only one tile wide (per the screenshot, the path is up right side). Maybe make a minimum width of two?

> > sector-serpulo-15.zip
> 
> That save is just Ground Zero, not what you have in the image.

Is there any way to know what save is what? These are all just auto-saves and I assume the most recent save is the one for the current map.
