### ISSUE TITLE
Locked after I cleared the sector

### ISSUE THREAD

**Issue by Someone-3** [Anuken/Mindustry#3780]
**Platform**: Windows

**Build**: Steam Build 120
**Issue**: I need to go into tar fields for resources but its "Locked" for some reason

**Steps to reproduce**: Don't entirely know how I did it but it might have something to do with the cloud saves. I cleared the tar fields sector and then a while later I wanted to return to it (on a different computer) to launch items to a other sector and it was "Locked".

**Link(s) to mod(s) used**: I only play vanilla

**Save file**: https://ufile.io/6alv8juq

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't debug this without all your game data, the save file is just a map.

**Comment by q00u** [comment]
[saves.zip](https://github.com/Anuken/Mindustry/files/5648069/saves.zip)

The same thing happened to me, also on Tar Fields.

Now it says "Capture Windswept Islands"

(This is very frustrating, because Tar Fields had become my main sector, and to suddenly lose access to all those resources without warning...)

**Comment by Anuken** [comment]
> [saves.zip](https://github.com/Anuken/Mindustry/files/5648069/saves.zip)
> 
> The same thing happened to me, also on Tar Fields.
> 
> Now it says "Capture Windswept Islands"
> 
> (This is very frustrating, because Tar Fields had become my main sector, and to suddenly lose access to all those resources without warning...)

Again, I can't test it with just the saves. They're just maps, they don't contain unlocks or campaign progress.

**Comment by q00u** [comment]
I believe you are correct.

For future reference, what game data would you have needed? Where is it stored, if not the `saves` folder?

**Comment by Anuken** [comment]
The whole Mindustry data folder.
