### ISSUE TITLE
UUID duplication

### ISSUE THREAD

**Issue by WTF919** [Anuken/Mindustry#3782]
**Platform**: Windows

**Build**: 120.3

**Issue**: I got a ban on a server and the evidence provided was someone else, but according to mods the UUID matches. IDK if the specific ID being released publicly can be abused in some way, but if I needed I can provide it.

**Steps to reproduce**: It's just what my UUID is

**Link(s) to mod(s) used**: Not applicable

**Save file**: Not applicable

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by pyronie** [comment]
probably isn't a duped uuid, but you getting unlucky and sharing a uuid with someone who is banned

**Comment by Anuken** [comment]
There's not much I can do with this information. UUIDs are randomly generated, and it seems extremely unlikely that there would be conflicts. It's possible someone stole your UUID, or you imported it from someone else.

**Comment by WTF919** [comment]
Can getting a single player save file from another player change your ID in multiplayer?

**Comment by DeltaNedas** [comment]
change your uuid and hope that you dont get unlucky
