### ISSUE TITLE
Using Logic Processor to Disable Surge Tower does nothing.

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry#3783]
**Platform**: *Windows*

**Build**: 120.4   Installed 2020/12/4.

**Issue**:  Using Logic Processor to Disable Surge Tower does nothing.  The Surge Tower continues to receive and transmit power even when it has a red 'x' on it.

**Steps to reproduce**:

Create a Surge Tower and hook it up to something that generates power (producer) and something that needs power to function (consumer).

Confirm that the Surge Tower is the only thing powering the consumer.  Disconnect the Surge Tower: confirm that the consumer turns off; Connect the Surge Tower: confirm that the consumer turns on.

Use a Logic Processor to set the "enabled" property on a Surge Tower to 0.  Confirm that a red 'x' appears when doing a mouse-over on the Surge Tower.

The consumer should be off because it should no longer have power.  However, it remains on.

In other words, setting the Surge Tower's "enabled" property to 0 has no effect.

My assembly code successfully disables multiple "weaver" (Phase Weaver) blocks, so I know it's working properly.

A description of confirming the repro using my Save File is also below.

**Link(s) to mod(s) used**: None.

**Save file**: 

[SurgeTowerDisable.zip](https://github.com/Anuken/Mindustry/files/5645860/SurgeTowerDisable.zip)

In my repro save game (zip attached), you can see the issue as follows.

I'm in the Tar Fields map.

My Core Nucleus is near the lower-left corner.

There are two Logic Processors near the Core Nucleus.  The one you want has a Message right next to it which is displaying "phase = 13000".

If you click on that Logic Processor, it's hooked up to several things.

Its logic is actively disabling the three Phase Weaver blocks (weaver1/2/3) and they are not producing Phase Fabric.  Mouseover on them shows a red 'x'.  This is expected.

Its logic is also disabling the Surge Tower (tower1).  Mouseover on the tower shows a red 'x'.

That Surge Tower is hooked up through a couple other Surge Towers to power a few Illuminator blocks and two more Phase Weaver blocks.  Those consumers are straight up and a bit to the right.

Expected behavior:  The Illuminator blocks and Phase Weaver blocks should NOT be powered because the Surge Tower is disabled.  Therefore, they should not operate.
Observed behavior:  They continue to operate and output Phase Fabric.

You can make this super obvious as follows.
Zoom out all the way and move so you can see tower1 and the two Phase Weavers it is connected to.
Manually disconnect tower1 from the Power Node really close to it: The Illuminator blocks near the two Phase Weavers go out.
Reconnect tower1 to that Power Node: The Illuminator blocks near the two Phase Weavers go back on.

But tower1 is disabled (as shown by the red 'x')!  Its connections shouldn't matter.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Power nodes cannot be disabled. Power networks do not "route" power through nodes.

**Comment by swenkeratmicrosoft** [comment]
> Power nodes cannot be disabled. Power networks do not "route" power through nodes.

If a Power Node cannot be disabled, then it should not show a red 'x' when its Enabled Property is set to 0.  The red 'x' indicates that it IS disabled.

**Comment by swenkeratmicrosoft** [comment]
@Anuken  - This issue should be reactivated and say "Power Node should not display a red 'x' when Enabled Property is set to 0."

**Comment by Anuken** [comment]
The "X" doesn't mean anything; going through and removing that visual from all the blocks that don't support it would be a waste of time. You can disable a wall, and it'll display an X as well.

**Comment by swenkeratmicrosoft** [comment]
@Anuken - Or would you rather I open a new issue specifically for that?

**Comment by swenkeratmicrosoft** [comment]
@Anuken  - Then why can't power nodes be disabled, exactly?  If I disconnect the Surge Tower, it stops powering things.  If I reconnect it, it starts powering things.  Why doesn't disabling it simply treat it has having no connections?

**Comment by Anuken** [comment]
Because:

> Power networks do not "route" power through nodes.

They do not count as part of the network. Re-calculating the entire power network every time state is changed would be very expensive. Use diodes instead.

**Comment by swenkeratmicrosoft** [comment]
A diode doesn't do what I want.  A Batter Diode says "Moves battery power in one direction, but only if the other side has less power stored."

There are no batteries involved in my situation.  I want to send power based on an arbitrary condition.

**Comment by Anuken** [comment]
Then use batteries and disable/enable diodes.

**Comment by swenkeratmicrosoft** [comment]
@Anuken 

Ah, I see the following existing suggestion - it would do everything I need.

https://github.com/Anuken/Mindustry-Suggestions/issues/684

I don't actually need to disable power.  What I need is to disable a component over a long distance.  I only just tried disabling power because there's nothing like that suggestion available.  :)

**Comment by DeltaNedas** [comment]
then use 2 diodes silly
