### ISSUE TITLE
Not showing any community servers

### ISSUE THREAD

**Issue by saxenification** [Anuken/Mindustry#3784]
**Platform**: *Linux (POP!_OS)*

**Build**: *120.4 Steam*

**Issue**: *No community servers listed when running Mindustry on Linux via Steam. Community servers listed when using files from github and starting the game with Terminal.*
_Steam_
```
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce GTX 1080/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_131
[I] Total time to load: 3429
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Time to generate menu: 80.72931
[I] Received steam stats.
[I] found 5 matches mindustry.desktop.steam.SNet$$Lambda$1542/636782475@7ceb3185
[I] found 4 matches mindustry.desktop.steam.SNet$$Lambda$1542/636782475@2d778add
```
_Terminal_
```
saxenborn@pop-os:~/Downloads/mindustry-linux-64-bit/jre$ java -jar desktop.jar
[I] Initialized Discord rich presence.
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 128 samples / 2 channels
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce GTX 1080/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 11.0.9.1
[I] Total time to load: 2650
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Time to generate menu: 113.56684
[I] Fetched 12 community servers.
```

**Steps to reproduce**: *Start game using steam -> Play -> Join game -> List is empty*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A*

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by T-Yeller** [comment]
I have 126.2 and 136.1. I can't get any servers to show up on my end (except for local games) I have the game passed through the firewall, I'm running windows 11, it used to work for about a month, then they disappeared. I have all mods off. is there something wrong on my end?
