### ISSUE TITLE
Cultivators gain benefit from Tainted Water, but can't be placed on it

### ISSUE THREAD

**Issue by GreyMario** [Anuken/Mindustry#3788]
**Platform**: All

**Build**: 120.2

**Issue**: The Cultivator gains 15% bonus efficiency per tile for being placed on `Tainted Water` tiles, but cannot actually be placed on these tiles., rendering this tile affinity completely useless.

The Cultivator _is_ able to use its lesser 10% bonus efficiency when placed on `Dark Sand Tainted Water`, its shallow-water cousin. So I'm not certain if the better fix is to set Dark Sand Tainted Water's bonus to 15% or to make it so that Cultivators can be placed on deep Tainted Water.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have ~~updated to the latest release~~ skimmed the source code to make sure the issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't think this is a problem. It's similar to the Silicon Crucible, which technically gains affinity from slag but cannot be placed on it. 
- Making it placeable on deep water wouldn't make sense - it's not a pump, after all
- There may be other applications to spore attributes in the future, so I don't see why the affinity should be removed
- Removing the affinity from tainted water would make it inconsistent with other tainted-type blocks

**Comment by GreyMario** [comment]
Hm, then maybe tile affinities shouldn't appear in the Core Database if the block can't be placed on them? Or do you feel that would be "inconsistent" by your third bullet point?
