### ISSUE TITLE
Exporting and importing dont work

### ISSUE THREAD

**Issue by Patryk368** [Anuken/Mindustry#3790]
**Platform**: Android

**Build**: 120.4

**Issue**: Game restarts when i export or import something. 

**Steps to reproduce** export or import

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Game restarts when i export or import something.

Yes, that's what it's supposed to do.

**Comment by Patryk368** [comment]
> > Game restarts when i export or import something.
> 
> Yes, that's what it's supposed to do.

But this dont work. When im exporting map this dont work. I have 0B empty file. Importing game data, mods dont work too.

**Comment by Anuken** [comment]
You haven't posted any logs or save files, which is required.

**Comment by Patryk368** [comment]
I don't have scrash logs I have only last_log.txt.
Exporting crash logs and saves don't work too.

[last_log.txt](https://github.com/Anuken/Mindustry/files/5647239/last_log.txt)
