### ISSUE TITLE
When explosions happen other players get kicked from the game

### ISSUE THREAD

**Issue by Essnato** [Anuken/Mindustry#3795]
[**Platform**:]Mac

**Build**: has happened since 118 all the way to 120.4

**Issue**: When playing on LAN with friends while I am hosting if there is ever a very large amount of destruction happening at once such as a thorium reactor exploding or a bunch of powerful units firing (or sometimes just one powerful unit firing such as the tier 4 green air units) everyone gets removed from the game except me (the host) and we have to rejoin, we do not know why this happens and it has happened with and without mods

**Steps to reproduce**: Just playing normally on a pvp map, then someone's thorium reactor exploded and everyone got removed, some time later with a mod that added powerful air units every single time they dropped a bomb it happened again and everyone gets kicked out.

**Link(s) to mod(s) used**: Braindustry (but I do not believe it is the mods fault as it happened without it too)

**Save file**: This is just one of the saves where it happened, but its happened without fail on every map I've played with friends on LAN (not in singleplayer or servers however)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: There were no Crashes 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[24.msav.zip](https://github.com/Anuken/Mindustry/files/5646971/24.msav.zip)

**Comment by Slava0135** [comment]
Happened to me too, however I can't tell why it happens.
