### ISSUE TITLE
After opening and closing the Logic interface a unit binding is destroyed

### ISSUE THREAD

**Issue by kotomaran** [Anuken/Mindustry#3796]
It doesn't seem to be documented anywhere, but after playing around with Logic for some time I've found that when I write some code, close Logic interface to observe my results, reopen the interface to make some corrections and then close it again, three things are happening:
- processor's set variables are preserved
- the number of line of code that the processor was at is preserved
- previously bound unit is now unbound

This behaviour seems inconsistent and breaks the proper code loop, sometimes forcing the processor into the frozen state when it hangs in one of internal loops where reaction from a unit is required. I think it would be better if the processor would "reboot" after accessing it's interface, clearing variables and current operation along with unit binding; or at least if there would be a button to do such a "reboot" or some pointer showing current running instruction and a binding indicator.

**Comment by DeltaNedas** [comment]
1. template
2. this is not for suggestions
3. no it isnt, units are unbound if not controlled for a few seconds, `set h @unit` if you need to sense it for a while

**Comment by kotomaran** [comment]
>     1. template
>     2. this is not for suggestions
>     3. no it isnt, units are unbound if not controlled for a few seconds, `set h @unit` if you need to sense it for a while

3. This is not the case.
- when the Logic interface is opened the game is on pause -- not a second passes in-game.
- why is a unit even becomes "not controlled" merely by opening the Logic interface?

**Comment by Anuken** [comment]
> somehow I wasn't offered one when I was creating the issue. 

How did you manage to do that? The issue choosing UI should not allow you to open issues without a template, it's explicitly configured that way.

You're missing all the necessary template fields (specific save for reproduction, game version, platform) - open a new issue.
