### ISSUE TITLE
Crash on MacOS Big Sur (Intel CPU)

### ISSUE THREAD

**Issue by TheEmrio** [Anuken/Mindustry#3797]
**Platform**: MacOS Big Sur v11.0.1 (Intel-based CPU)

**Build**: Mindustry 6.0 Build 120.4
Java version: 
```
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

**Issue**: When starting the game, it instantly crashes

Note: The last version I played Mindustry was Build 104.10, so I already had a Mindustry data folder. Removing it didn't solve the issue.

**Steps to reproduce**: 
- Download Mindustry from the GitHub release page
- Double click on it
- Authorize app in System Preferences, under Privacy
- Reopen the app
- It launches and then crashes immediately afterward

**Link(s) to mod(s) used**: No mods used

**Save file**: Not applicable

**Crash logs**: [Java Crash log](https://hasteb.in/robowiya.rb)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
you need to use the java arguments to not crash, see BeControl.java or use the launcher on itch.io

**Comment by TheEmrio** [comment]
> you need to use the java arguments to not crash, see BeControl.java or use the launcher on itch.io

Which arguments?

**Comment by Anuken** [comment]
Raw jars on Mac must be run with `-XstartOnFirstThread`.

**Comment by TheEmrio** [comment]
It works, thanks!
However, I feel like this is very user-unfriendly, especially considering that this manipulation was not necessary for previous versions and people may not know about the command-line.
Do you plan on "fixing" this issue?

**Comment by Anuken** [comment]
> this manipulation was not necessary for previous versions

It was **always** necessary. You may not have noticed it before because the itch.io version comes with an executable launcher that adds in the arguments for you.

**Comment by TheEmrio** [comment]
Oh my bad!
