### ISSUE TITLE
Core on fire, won't go out

### ISSUE THREAD

**Issue by colinmarc** [Anuken/Mindustry#3799]
**Platform**: Mac

**Build**: steam build 120.4

**Issue**: My core was set on fire by the evil robots. Now it's still on fire, several minutes later. I have a wave turret spraying water on it, to no avail.

**Save file**: 
[mindustry.zip](https://github.com/Anuken/Mindustry/files/5647182/mindustry.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** I didn't do this because I can't get the jars to run.
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by colinmarc** [comment]
I upgraded to a Tsunami turret and the fire did go out. Not sure if this is working as intended.

**Comment by Quick-korkc** [comment]
dont put any flammable item in the core except you need them

**Comment by DeltaNedas** [comment]
>have coal in core
>complain that its on fire
this is not a bug

**Comment by colinmarc** [comment]
I don't believe I have any coal in my core.

**Comment by DeltaNedas** [comment]
ok post a screenshot of your cores items

**Comment by Quick-korkc** [comment]
plastanium is flammable too

**Comment by colinmarc** [comment]
<img width="324" alt="Screenshot 2020-12-05 at 15 27 30" src="https://user-images.githubusercontent.com/821775/101245624-65af7700-370e-11eb-9c13-71b4f03e01ba.png">

**Comment by Quick-korkc** [comment]
yeah its because plasta

**Comment by colinmarc** [comment]
> plastanium is flammable too

Huh, I had no idea!

Happy for the maintainer to close this if it's not a bug. I think it's confusing to have your core be on fire and not know why.
