### ISSUE TITLE
Infinite first wave on Planetary Launch Whatever map

### ISSUE THREAD

**Issue by colinmarc** [Anuken/Mindustry#3800]
**Platform**: Mac

**Build**: 120.4

**Issue**: On the Planetary Launch Thing map, the first wave seems to have infinite numbers of little boats. Whenever I kill one, another one spawns.

**Save file**: 
[mindustry.zip](https://github.com/Anuken/Mindustry/files/5647182/mindustry.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** I didn't do this because I can't get the jars to run.
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quick-korkc** [comment]
that because the spawner next to enemy core, this is not a bug

**Comment by Quick-korkc** [comment]
i mean the factory

**Comment by DeltaNedas** [comment]
how are naval factories a bug

**Comment by colinmarc** [comment]
Ah! I was confused because
 - the map didn't have a factory when I played it on the beta branch
 - I haven't seen the enemy bases have factories before
