### ISSUE TITLE
Atroxes can walk through/on deep water

### ISSUE THREAD

**Issue by colinmarc** [Anuken/Mindustry#3801]
<img width="193" alt="Screenshot 2020-12-05 at 15 50 16" src="https://user-images.githubusercontent.com/821775/101246158-cab89c00-3711-11eb-94cf-0689930323f6.png">

**Platform**: Mac

**Build**: steam build 120.4

**Issue**: I'm getting attacked by Atroxes walking in deep water, something I haven't seen before in the game. Sorry if that's intended.

**Save file**: 
[mindustry.zip](https://github.com/Anuken/Mindustry/files/5647245/mindustry.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by z0mbiesrock** [comment]
Yes I am sure that is intended

**Comment by Quezler** [comment]
^
