### ISSUE TITLE
Invisible window bug

### ISSUE THREAD

**Issue by rmperkow** [Anuken/Mindustry#3802]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
120.4
**Issue**: *Explain your issue in detail.*
Sometimes when you launch the game it does not appear. You will have to kill the process to make it go away.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Launch the game.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
N/A
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
[No logs, cannot reproduce.](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#i-cannot-reproduce-your-issue)
