### ISSUE TITLE
Not seeing players

### ISSUE THREAD

**Issue by SomeGuyNoOneKnows** [Anuken/Mindustry#3803]
**Platform**: *Mac

**Build**: *V6 mac OS stable

**Issue**: *When joining a game on Mac OS [multiplayer] I cannot see players, or Look at them in Player tab, only use of communication is Chat

**Steps to reproduce**: *Joining a Multiplayer game on Mac OS

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *Cant get File, Mac OS is way to secure

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't have a functional Mac, you haven't posted any logs and I can't reproduce this.

**Comment by DeltaNedas** [comment]
"a multiplayer game"
