### ISSUE TITLE
Mouse cursor disappears when near ship

### ISSUE THREAD

**Issue by acidduk** [Anuken/Mindustry#3807]
**Platform**: Windows

**Build**: Steam build 120.4

**Issue**: Playing on 2560x1440 (desktop resolution) borderless fullscreen mode, with UI scaling set to 150%. When I move my mouse cursor near my ship, the cursor disappears. The same happens on non-borderless fullscreen. When playing in windowed mode, the cursor changes when near my ship to a much bigger and different cursor (that looks big and pixellated).

**Steps to reproduce**: Play in fullscreen mode, started the campaign, immediately saw the issue.

**Link(s) to mod(s) used**: None

**Save file**: [sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/5647729/sector-serpulo-15.zip)

**(Crash) logs**: N/A Game does not crash

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** I have tried to search issues for cursor related issues but can't immediately see anything similar.

**Comment by Anuken** [comment]
Cannot reproduce on a Windows 10 VM with 150% scaling. The cursor does not disappear.

**Comment by acidduk** [comment]
I did a bit more digging and it seems to be more subtle than I originally thought. If I fly my ship away from the copper field at the start it doesnt happen - it's only when my ship is on top of a copper (or other resource?) field, that moving the mouse near the ship causes the cursor to vanish.

**Comment by acidduk** [comment]
I also just checked if the issue occurs at 100% UI scale, and it doesn't disappear, so the issue is somehow related to the scaled non-default cursor.

**Comment by Anuken** [comment]
I can't reproduce it in those conditions either. Even when I am above copper and the ship, the drill icon appears.

**Comment by acidduk** [comment]
Ok, I'll just play on 100% UI scale, it seems fine that way :). I did notice when playing windowed, with scale at 150% the drill cursor icon isn't smoothed in the same way the default cursor is, so I guess there's something different my PC doesn't like about it.

**Comment by acidduk** [comment]
P.S. Thanks for looking so quickly and thanks for the fun game :-)
