### ISSUE TITLE
Crash in Fungal Pass MacOS 120.4

### ISSUE THREAD

**Issue by cprince** [Anuken/Mindustry#3808]
**Platform**: MacOS 10.15.7 Catalina

**Build**: 120.4

**Issue**: I was building a router I think in Fungal Pass and I got the crash
[Archive4.zip](https://github.com/Anuken/Mindustry/files/5647846/Archive4.zip)

**Steps to reproduce**: Now when I open Fungal Pass it crashes every time now

**Link(s) to mod(s) used**: none

**Save file**: 

These four files all had the latest date and time:
sector-serpulo-20.msav
sector-serpulo-21.msav
sector-serpulo-23.msav
sector-serpulo-213.msav

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 120.4
OS: Mac OS X x64
Java Version: 1.8.0_222
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.core.Logic.updateWeather(Logic.java:252)
	at mindustry.core.Logic.update(Logic.java:336)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
[crash-report-12_05_2020_15_33_56.txt](https://github.com/Anuken/Mindustry/files/5647847/crash-report-12_05_2020_15_33_56.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by cprince** [comment]
Archive4.zip contains the 4 save files

**Comment by DeltaNedas** [comment]
i was placing router when the phone ring
"weather is kil"
"no"

**Comment by cprince** [comment]
So how do I continue?

**Comment by Anuken** [comment]
Wait until the next update.

**Comment by cprince** [comment]
@Anuken thanks man works great now. Awesome new version btw. deeply appreciate it.
