### ISSUE TITLE
Community servers missing on Linux?

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3809]
**Platform**: *Linux*

**Build**: *120.4*

**Issue**: *Community servers are missing again... Perhaps it's my shitty internet connection but the thing is that everything works fine on my phone. However if I connect my laptop via phone it won't work. 
I met at least 1 person with the same problem. 
Please write if you are playing on Linux based OS and having the issues (or not)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by QmelZ** [comment]
works fine on my machine

**Comment by DeltaNedas** [comment]
nice you removed half of the template that asks you to post your log

**Comment by Slava0135** [comment]
To be more precise it's Steam version

**Comment by Slava0135** [comment]
> nice you removed half of the template that asks you to post your log

What log. How can I detect the problem this way.

**Comment by QmelZ** [comment]
> What log.

last_log.txt

**Comment by Slava0135** [comment]
It's too late for me... I will do it tomorrow.

**Comment by Anuken** [comment]
This was already reported.
