### ISSUE TITLE
Generation of Terrain Broken

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry#3810]
**Platform**: Windows

**Build**: steam build 120.4

**Issue**: Generation of terrain is broken in many ways when it is put into the "Generation" rules.

Here is the preview of what the game SHOULD generate. (In the Editor, Menu>Map Info>Generation)
![image](https://user-images.githubusercontent.com/57609258/101265814-c1760200-3706-11eb-8fd4-c0fbb7664509.png)
vs what is actually generated. (Minimap in-game)
![image](https://user-images.githubusercontent.com/57609258/101265831-ea969280-3706-11eb-8aff-ab2881e03916.png)

Here is another example
![image](https://user-images.githubusercontent.com/57609258/101265855-3b0df000-3707-11eb-88b8-123bd821ee93.png)
![image](https://user-images.githubusercontent.com/57609258/101265869-5973eb80-3707-11eb-89a0-91677147fbb6.png)

There is also lots of weird artifacting, and functions such as 'mirror' and 'path to spawn' do not work properly.

![image](https://user-images.githubusercontent.com/57609258/101265883-714b6f80-3707-11eb-9960-de12caa5cf35.png)
![image](https://user-images.githubusercontent.com/57609258/101265914-cedfbc00-3707-11eb-86f9-f47bbb0eb52c.png)
*Core can get buried despite the 'path to spawn' function coming after the 'generation' function, which should guarantee the core is clear.*
![image](https://user-images.githubusercontent.com/57609258/101265927-0189b480-3708-11eb-9646-fac7bd7af1da.png)
![image](https://user-images.githubusercontent.com/57609258/101265943-22520a00-3708-11eb-8509-bbb16784408a.png)
*Abnormal right angles.*

**Steps to reproduce**: 
1. Make any world.
2. Use the "Terrain" tool inside of Menu>Map Info>Generation.
3. Go to Play>Custom Game and select the world.
4. Start a game in any mode (I tested PvP, Survival, and Sandbox).
5. All of the issues I mentioned above will be present.

**Link(s) to mod(s) used**: I didn't use any mods while doing this, but I had deltanedas/rtfm and deltanedas/cliff enabled. I disabled cliff to see if that was the cause of this bug(s) and the bug(s) persisted.

**Save file**:
The first pair of screenshots are from this file.
https://drive.google.com/file/d/1mvSt4rsf7vOSoLRXzcOYAfnsa2u0___A/view?usp=sharing
The second pair of screenshots are from this file.
https://drive.google.com/file/d/1pVdHSnXhONdJ-MlWAWFDFnNex6MkWINu/view?usp=sharing
The rest of the screenshots come from one of those two.

Those aren't the saves, they are the maps I made (exported from the menu in the editor), but every time you generate a map based on those it bugs in the same or similar way. Let me know if you need me to upload my exact saves.
 
**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.** I searched for "terrain" and "generation" separately and read all the issues with those two keywords.

**Comment by Anuken** [comment]
> Here is the preview of what the game SHOULD generate. (In the Editor, Menu>Map Info>Generation)

And it *does* look like that. You have a bunch of stone in the middle of the map, which does not get removed - the result is a few random empty patches. The terrain filter doesn't turn rock into air anymore.

> the 'path to spawn' function coming after the 'generation' function

It's **not** after the terrain function.

![image](https://user-images.githubusercontent.com/10100000/101266894-5ede2f80-3721-11eb-9395-a4fdb56d0e04.png)

> Here is another example

> There is also lots of weird artifacting, and functions such as 'mirror' and 'path to spawn' do not work properly.

Most of the map isn't mirrored because you distort it and add noise afterwards, and the mirror plane is at a strange angle. Your map doesn't have any spawns, so "path to spawn" does nothing.

> weird artifacting

Fixed.

**Comment by RogueRedHawk** [comment]
>And it does look like that. You have a bunch of stone in the middle of the map, which does not get removed - the result is a few random empty patches. The terrain filter doesn't turn rock into air anymore.

You are right. I forgot to remove all that rock from a previous test, and ended up conflating the artifacting issue with my poor testing.. thanks for fixing the one that actually WAS a bug though.
