### ISSUE TITLE
Core storage reset

### ISSUE THREAD

**Issue by AbyssalSans** [Anuken/Mindustry#3812]
**Platform**: Windows

**Build**: Steam build 120.4

**Issue**: My core resources reset to 1k

**Steps to reproduce**: place a vault or container next to a full core, start deconstructing the vault/container and start reconstructing it before it breaks 

**Link(s) to mod(s) used**: I have no mods installed or enabled

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5648068/saves.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
What do you expect from deconstructing a vault full with materials

**Comment by AbyssalSans** [comment]
> What do you expect from deconstructing a vault full with materials

i would expect maybe losing 1k materials but it took away 12k

**Comment by AbyssalSans** [comment]
so partially breaking a vault then fixing it should reset my core resources to 1k???

**Comment by Anuken** [comment]
No, if it mentions a specific commit that means it's fixed.

**Comment by AbyssalSans** [comment]
ok alright thanks
