### ISSUE TITLE
Alpha's, Beta's, and Gamma's damage stat incorrect

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#3814]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
120.2

**Issue**: *Explain your issue in detail.*
In the core database it says Alpha, Beta, and Gamma's weapons do 11 damage, but upon further testing this appears to be incorrect. They do much much less damage. It should only take 5 shots to knock out a regular conveyor but upon testing it took over 70 shots just for a single conveyor and it still didn't break. Testing with other mechs and the damage stat seems accurate, but it's way off for regular player ships. I even checked to make sure the player damage multiplier in the map rules was 1x and it was.

This is either intentional and it's a bug in the core database displaying incorrect information, or the database is correct and the players are outputting too little damage. This is frustrating because this whole time I thought player ships were mildly useful in combat but they are completely useless in practice.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
During PVP I noticed I couldn't destroy any opponents conveyors. Conveyors are the weakest block in the game. It says players do 11 damage so I knew something was off. Setup a custom map with some enemy blocks strewn about and counted how many shots it takes to destroy each block. If you do the math it does not add up for what the core database says Alpha, Beta, Gamma ships do. It says they do 11 damage each but it should say they do more like 1 damage each or whatever it actually is.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
NA

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
NA
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That damage refers to *unit* damage, not block damage. They deal <1% block damage.

**Comment by Esnardo** [comment]
> They deal <1% block damage.

That explains a lot

**Comment by RedstonerKBC** [comment]
I don't think I understand? That's the damage they do to other units? Then how is block damage calculated and shouldn't that be documented in the core?

**Comment by Anuken** [comment]
> Then how is block damage calculated

As I said, it's ~1% of the damage they do to units.

> shouldn't that be documented in the core?

Nobody has asked, so it hasn't been implemented.

**Comment by SabreRunner** [comment]
Why do they do so little block damage?
