### ISSUE TITLE
scripts: blacklist problems

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#3818]
**Platform**: `Windows`

**Build**: `v120` (doesn't work on `v120.5` too)

**Issue**:
Unable to interact with a mod whose name contains blacklisted strings. *But actually it is not vulnerable at all.*

**Steps to reproduce**:
1. Create any Java (not sure about js) mod with a name containing blacklisted string (in my case `solar-system`)
2. Type in console `Vars.mods.locateMod("mod-name").main;`
3. See the error that the mod class is prohibited because there is a `system` string that is blacklisted.

![image](https://user-images.githubusercontent.com/55251897/101281054-e9c43600-37c4-11eb-9fa7-d7e58deee723.png)

**Link(s) to mod(s) used**:
Java mod - [SolarSystem-Desktop-1.0.zip](https://github.com/Anuken/Mindustry/files/5648794/SolarSystem-Desktop-1.0.zip)

**Logs**: 
Image above.

---

- [X] **I have updated to the latest release to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't really fix this.

**Comment by DeltaNedas** [comment]
`public class SolarSistem extends Mod`
