### ISSUE TITLE
Multiplayer Problem

### ISSUE THREAD

**Issue by johnc6209** [Anuken/Mindustry#3819]
**Platform**: *Windows*

**Build**: *steam build 120.5 and also 121*

**Issue**: *My friend and I played together by Steam invite before 6.0 update. But after the update, my friend can't invite me. And when I invite him and he accept it, nothing happens. I think my friend's Mindustry client is not the Steam version, because he doesn't have some settings in Settings-Game-Player Limit and Public Game Visibility. He bought and play Mindustry in Steam, and he can find 'steam build 120.5' below his Mindustry Logo. How can we solve this problem?*

**Steps to reproduce**: *I downloaded free version of Mindustry, and I found that it doesn't have some settings in Settings-Game-Player Limit and Public Game Visibility. Also I and my friend uninstall the game and reinstall the game. I updated to 121 and nothing changed.*

**Link(s) to mod(s) used**: *I don't use mods.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
uncheck the first checkbox 👀

**Comment by Anuken** [comment]
Both of you must be running Steam Build 121 to play multiplayer with each other through Steam. Update your games and make sure both of you are launching through Steam. If that doesn't work, post images of **both** main menus here.
