### ISSUE TITLE
bugs with big node

### ISSUE THREAD

**Issue by mhanzel** [Anuken/Mindustry#3821]
**Platform**: *Windows

**Build**: *steam build 121*

**Issue**: *when u double nick on node to connect all electrical builds*

**Steps to reproduce**: *i just defense and when u did it, i was surpris*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[bugs.zip](https://github.com/Anuken/Mindustry/files/5649008/bugs.zip)

**Comment by Quezler** [comment]
what exactly is the issue?

**Comment by Anuken** [comment]
????

**Comment by DeltaNedas** [comment]
why does anuke have to wake up to this
