### ISSUE TITLE
Small text area

### ISSUE THREAD

**Issue by GioIacca9** [Anuken/Mindustry#3822]
**Platform**: *Mac/Windows/Linux* (probably also on mobile)

**Build**: All v6 builds

**Issue**: It seems like the text area for the block description ("Scopo" in the screenshots) doesn't resize properly: the text go new line even if it has lot of space.

![immagine](https://user-images.githubusercontent.com/39232448/101286686-33744700-37ec-11eb-8f4b-56295a6d34bc.png)
![immagine](https://user-images.githubusercontent.com/39232448/101286871-5521fe00-37ed-11eb-8055-c8bcb7468d1f.png)
![immagine](https://user-images.githubusercontent.com/39232448/101286889-708d0900-37ed-11eb-8c6c-cc557fec92fa.png)

**Steps to reproduce**: -

**Link(s) to mod(s) used**: -

**Save file**: -

**(Crash) logs**: -

**Language used**: Italian

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** *I hope I have searched well*

Edit: added more screenshots

**Comment by Anuken** [comment]
Intentional.

**Comment by DeltaNedas** [comment]
related, i think the list of possible fuels should be wrapped like description is to produce a more vertical stats dialog
