### ISSUE TITLE
fdroid not getting updates past b109

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3823]
**Platform**: Android

**Build**: 121

**Issue**:
F-Droid isn't:
1. Detecting v6 releases after b109
2. Starting to compile mindustry, it came up with a cryptic error instead: "could not bring up vm 'builder_default'"

**Steps to reproduce**:
1. Wait for new update to be released.
2. No changes to lastbuild, still stuck on v109.

**Link(s) to mod(s) used**: no

**Save file**: not in game

**(Crash) logs**: https://f-droid.org/wiki/page/io.anuke.mindustry/lastbuild - last tried to build b109

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this.

**Comment by XxsuperdeadlysniperxX** [comment]
@DeltaNedas are you on a virtual machine?

**Comment by XxsuperdeadlysniperxX** [comment]
Aka a vm

**Comment by licaon-kter** [comment]
No joy for F-Droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2230#note_611789337 :(

**Comment by Anuken** [comment]
@licaon-kter As of the latest release made a few minutes ago, Mindustry supports Java 16 for compilation. However, this is an alpha version - will that be a problem?

**Comment by licaon-kter** [comment]
We're on Debian so we have 8 (stretch aka old-stable, aka curent server), 11 (stable soon to be old-stable), 15 (unstable) and something called 17~19 (testing future stable) (dunno why it's called like this but surely it's the fault of Oracle lol)

Anyway, as my link shows if we stray too much away with packages from newer versions we're getting deps hell or symptoms. 

That 16 is...again not much of an improvement, it was 14 in the past? Oh we didn't use that either and it went byebye.

Not sure what's the solution atm.
