### ISSUE TITLE
units still repath to the core

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#3825]
**Platform**: `mac`

**Build**: `20259`

**Issue**: units still alternate between the 2 paths to the core despite one being walled off and one path being free.

**Steps to reproduce**: load the save and notice the units above the base constantly walking left-right-left-right.

**Save file**: [leftright.msav.zip](https://github.com/Anuken/Mindustry/files/5649420/leftright.msav.zip)

(i'm aware that this issue has been reported & fixed several times in the past, but it still seems to happen)

![Screen Shot 2020-12-06 at 20 42 14](https://user-images.githubusercontent.com/3179271/101290579-8dccd200-3803-11eb-88f5-83dad6d584f0.png)

> there don't seem to be any logic controlled doors prompting for this behavior along the route (server map save)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I won't fix this. There are two different paths on each side, and one of them takes longer to get to the enemies depending on which side it's on. The longer path takes more time to traverse, but has fewer player blocks to traverse, making enemies seem "indecisive" when the update from the left path reaches them first, then the cheaper right path hints.
