### ISSUE TITLE
Large schematics causing a bug that kicks everyone on a steam server

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry#3827]
**Platform**: *Windows*

**Build**: *Steam build 121.*

**Issue**: *When placing a schematic, such as something like a schematic that contains a lot of logic, or is just a huge schematic in general, everyone but the server admin gets kicked, causing things like pvp games to be screwed up and become very irritating*

**Steps to reproduce**: *The issue happens when I'm hosting my own games, and I go to place large schematics, or just schematics that contain a lot of logic, Everyone playing, no matter what, gets kicked*

**Link(s) to mod(s) used**: *(No mods active/being used when happens)*

**Save file**: *Was having trouble uploading a save, so I've checked on multiple computers on different internet connections, bug has occurred in all cases, no matter what the map is as long as the host places a big schematic*

**(Crash) logs**: *None for the host.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.** *- it has been somewhat, but I have more information stating that its large schematics and not just processors*

**Comment by Jornker** [comment]
#3813

**Comment by Catmaniscatlord** [comment]
I think he fixed this in a commit earlier this morning in [#3284](https://github.com/Anuken/Mindustry/issues/3824)

**Comment by Anuken** [comment]
Duplicate ^
