### ISSUE TITLE
Rebuild drone rebuilds cancelled buildings

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#3829]
**Platform**: Linux

**Build**: 6.0 121

**Issue**: Rebuild drone rebuilds what I want to demolish as it is a lost area, overtaken by enemy. Rebuild drones waste resources endlessly.

Cancelling building is ignored by drones - I would expect that I can cancel rebuilds (for bonus points - also not yet started rebuilds)

**Steps to reproduce**: Get object within enemy, have rebuild drones

**Link(s) to mod(s) used**: Not applicable, but server may be modded

**Save file**:  [0.msav.zip](https://github.com/Anuken/Mindustry/files/5649742/0.msav.zip)

**(Crash) logs**: Not applicable
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+rebuild+drone+is%3Aclosed https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+rebuild+cancelled+is%3Aclosed+ https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+reconstructed+building+is%3Aclosed+ https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+unable+cancel+is%3Aclosed+

![Peek 2020-12-07 00-13](https://user-images.githubusercontent.com/899988/101296071-b4016a80-3821-11eb-96c1-45526acce9b9.gif)

**Comment by GreyMario** [comment]
While I agree that a building in the process of being _deconstructed_ shouldn't leave a phantom if destroyed, you should probably erase the phantoms directly when you want Polys to not rebud them, instead of slating construction for destruction.

**Comment by Anuken** [comment]
Building drones don't see players as special, and don't follow their orders when it comes to deconstructing broken blocks. There simply is no implementation of this.

**Comment by matkoniecz** [comment]
>  you should probably erase the phantoms directly

How this can be done? I see nothing obvious in controls.

**Comment by GreyMario** [comment]
You can see the phantoms of destroyed blocks by holding right-click, or by being in build mode (with a block selected for placement).

**Comment by matkoniecz** [comment]
> You can see the phantoms of destroyed blocks by holding right-click, or by being in build mode (with a block selected for placement).

Apparently only in single player. Is it supposed to be available also in multiplayer?
