### ISSUE TITLE
Crash when Importing Data

### ISSUE THREAD

**Issue by YourMom11** [Anuken/Mindustry#3831]
**Platform**: Mac and iOS

**Build**: 121

**Issue**: Loading "game data" from a previous build instantly crashes app.

**Steps to reproduce**: Settings -> Game Data -> Import Data -> game data.zip -> CRASH
This was happening pre-6.x
[crashdata.txt](https://github.com/Anuken/Mindustry/files/5650014/crashdata.txt)
[gamedata.zip](https://github.com/Anuken/Mindustry/files/5650016/gamedata.zip)

**Link(s) to mod(s) used**: N/A

**Save file**: See attached

**(Crash) logs**: See attached

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by YourMom11** [comment]
Imported data is still not present after relaunching

**Comment by YourMom11** [comment]
Ok, had to do it a few more times and it worked. Suggest you fix this and the stupid Exit on load UX. Thanks for the arrogant reply.

**Comment by Anuken** [comment]
> (Crash) logs: See attached

That log does not contain a crash that I can debug.

This does not happen on any of my devices, so I can't fix it.

**Comment by What42Pizza** [comment]
I've just spent 15 minutes also thinking this was a bug, I just completely skipped over the warning and didn't realize it was supposed to close. There should really be some sort of second message that pops up before it closes, or maybe make that text more clear
