### ISSUE TITLE
Question answer MINDUSTRY.RU

### ISSUE THREAD

**Issue by MindustryRu** [Anuken/Mindustry#3832]
**[ENG]**
And so, in connection with the huge messages that something is wrong, we open the question-answer topic here, you write that you do not like it, we are fixing it.  You write a question, we answer it.  I will clarify right away that I will answer everyone if possible, since I work, and I cannot answer the question / proposal at the same moment.  Let's just not make a mess here, all in fact without unnecessary things.  Let's take this more than seriously.

**[RUS]**
И так, в связи с огромными сообщениями о том что что-то не так, открываем тут тему Вопрос-Ответ, вы пишите что не устраивает, мы это исправляем. Вы пишите вопрос, мы на него отвечаем. Уточню сразу что отвечу всем по возможности, так как работаю, и ответить в ту же минуту на поставленный вопрос/предложение не смогу. Давайте только тут не будем устраивать бордак, все по факту без лишнего. Отнесемся к этому более чем серьезно.

_P.s Anuke please do not close it!  We are trying to improve the project, and fix all the shortcomings / mistakes_

**Comment by GreyMario** [comment]
🍿

**Comment by BlueWolf3682** [comment]
- fix the fact that youre pay to win
- fix bad moderation and toxic playerbase 
- fix your existence
mission complete

**Comment by MindustryRu** [comment]
> * зафиксируйте тот факт, что вы платите, чтобы выиграть
> * исправить плохую модерацию и токсичную базу игроков
> * исправить свою 
>   миссию существования завершена

Донат полностью закрыт и более не приемлим на нашем проекте.

Если вы по советуете/поможете "избавится" от "токсичных" игроков, мы только ЗА.

3-й пункт не особо понятен.

Donat is completely closed and is no longer acceptable on our project.

 If you advise / help "get rid" of "toxic" players, we are only FOR.

 The 3rd point is not very clear.

**Comment by BlueWolf3682** [comment]
- i will request verification of no more pay to win (including any pay to unmute/unban) from trusted sources
- simple, clean out your entire admin group and start fresh using a trustworthy promotion system.
- nobody really likes you being around, and though i harbour no personal hatred towards you or your server, i dislike the money gouging and how you have handled moderation of the playerbase. 

also, three PRs and a Q&A? you brave child, it alone won't get you on the server list.

**Comment by MindustryRu** [comment]
> * i will request verification of no more pay to win (including any pay to unmute/unban) from trusted sources
> * simple, clean out your entire admin group and start fresh using a trustworthy promotion system.
> * nobody really likes you being around, and though i harbour no personal hatred towards you or your server, i dislike the money gouging and how you have handled moderation of the playerbase.
> 
> also, three PRs and a Q&A? you brave child, it alone won't get you on the server list.

We did not have a donation that gave advantages.
У нас не было доната который давал преимуществ.

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101311062-7f29fd80-388b-11eb-87c1-8fccd33c6769.jpg)

![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101310974-425e0680-388b-11eb-8ccd-77a07315ea36.jpg)

**Comment by Slava0135** [comment]
I just report this issue as spam. By opening it you just make Anuke more angry. Go away.

**Comment by iLagSoUhax** [comment]
This is unneeded. Anuke explicitly stated that he will NOT change his mind. Just the fact that you don't respect it shows that you are insincere.

**Comment by Nikolass1000** [comment]
> > * i will request verification of no more pay to win (including any pay to unmute/unban) from trusted sources
> > * simple, clean out your entire admin group and start fresh using a trustworthy promotion system.
> > * nobody really likes you being around, and though i harbour no personal hatred towards you or your server, i dislike the money gouging and how you have handled moderation of the playerbase.
> > 
> > also, three PRs and a Q&A? you brave child, it alone won't get you on the server list.
> 
> We did not have a donation that gave advantages.
> У нас не было доната который давал преимуществ.

You deleted it saying "This funcion temporarily does not work" and you think this will fix anything?

**Comment by MrByars** [comment]
P2W is bad, what the hell is buying unmute,unban ? 

Some player in off-topic channel asked me something about y maps, I answered nicely, and I got muted, I'm 100% sure I didnt break any rule, if I did just show me.

Some Admins thinks they can do whatever they want, leaking the entire teams IP, banning random people, watching griefers and just let them grief, and many other things. I once get banned just for upgrading normal conveyors to titanium conveyors, hilarious.

Some Admins are too damn toxic I mean really really toxic, insulting everyone who says something, kicking for no reason, deleting people's schemes , and many other things,

One of my friend got muted on discord, he doesn't have any message at all, he was - just exist in discord, he was have nitro, I guess one of the admins thinked he was money source, or is existing illegal?

**Comment by DeltaNedas** [comment]
since anuke doesnt want to vet *a* copy of the source for your malware launcher, release it so everyone can

**Comment by DeltaNedas** [comment]
so you seriously expect this to change anukes mind

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

**To everyone:**
Can everyone stop adding more to this thread.

If anuke is done with this. Everyone should follow suit.

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by Vandomas** [comment]
mindustry.ru, stop spamming 🙂

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

**To everyone:**
Can everyone stop adding more to this thread.

If anuke is done with this. Everyone should follow suit.

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by iutisteli** [comment]
@Anuken please close this issue. At this point, they are already spamming, even though you **explicitly** told them that you won't change your mind.

**Comment by exterminator1836** [comment]
The funny thing is that they didn't listen to the community at all and only started making changes when their server was removed from the list.

Please stop.

**Comment by VitLogArx** [comment]
I just got banned for "inappropriate nick", but there are was no swears. In DM admin agreed, that he need to unban me, but he haven't "privileges". So, when unban?

**Comment by exterminator1836** [comment]
> I just got banned for "inappropriate nick", but there are was no swears. In DM admin agreed, that he need to unban me, but he haven't "privileges". So, when unban?

Don't play on this corrupt server

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

**To everyone:**
Can everyone stop adding more to this thread.

If anuke is done with this. Everyone should follow suit.

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by C0D3Giant** [comment]
not even anuke likes your p2w server

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

**To everyone:**
Can everyone stop adding more to this thread.

If anuke is done with this. Everyone should follow suit.

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by Volas171** [comment]
not only that

**Comment by Volas171** [comment]
![image](https://user-images.githubusercontent.com/60143910/101353879-52adbb80-3862-11eb-9d74-ef022181b582.png)
they dont want to talk about this, they are using mindustry game under mindustry.ru copyright wich means technically they are claiming they own mindustry.

**Comment by Volas171** [comment]
but well this guys dont have any future left so imma just 🍿

**Comment by Volas171** [comment]
but just as last request , give us the assembly of the client lol

**Comment by MindustryRu** [comment]
> P2W - это плохо, что, черт возьми, покупает unmute, unban все равно?
> 
> Какой-то игрок на канале не по теме спросил меня что-то о моих картах, я хорошо ответил, и меня отключили, я на 100% уверен, что не нарушил ни одного правила, если бы я просто показал мне.
> 
> Некоторые админы думают, что могут делать все, что захотят: утечка IP всей команды, бан случайных людей, наблюдение за гриферами и многое другое. Однажды меня забанили только за то, что я модернизировал обычные конвейеры до титановых, это весело.
> 
> Некоторые админы чертовски токсичны, я имею в виду, действительно очень токсичны, оскорбляют всех, кто что-то говорит, пинают без причины, удаляют чужие схемы и многое другое
> 
> Один из моих друзей отключился из-за разногласий, у него вообще нет сообщений, он просто существовал в разногласиях, у него было нитро, я думаю, один из админов думал, что он был источником денег, или существует незаконно?

I need more evidence to deal with it.
In particular, who from the Dmitry did this do? Why do you complain about it here and not me in the drug in the Discird or on our server?

You probably did not see, but P2W is not in our part. We did not have any privileges that would have made the advantage.

**Comment by MindustryRu** [comment]
> ![образ](https://user-images.githubusercontent.com/60143910/101353879-52adbb80-3862-11eb-9d74-ef022181b582.png)
> они не хотят об этом говорить, они используют интеллектуальную игру под авторским правом mindustry.ru, что технически означает, что они заявляют, что они владеют интеллектуальным искусством.

Прочтите лицензию внимательно и привидите примеры нарушающие делать лаунчер под эту игру.
Read the license carefully and make examples of violating the launcher under this game.

**Comment by iutisteli** [comment]
> > P2W - это плохо, что, черт возьми, покупает unmute, unban все равно?
> 
> > 
> 
> > Какой-то игрок на канале не по теме спросил меня что-то о моих картах, я хорошо ответил, и меня отключили, я на 100% уверен, что не нарушил ни одного правила, если бы я просто показал мне.
> 
> > 
> 
> > Некоторые админы думают, что могут делать все, что захотят: утечка IP всей команды, бан случайных людей, наблюдение за гриферами и многое другое. Однажды меня забанили только за то, что я модернизировал обычные конвейеры до титановых, это весело.
> 
> > 
> 
> > Некоторые админы чертовски токсичны, я имею в виду, действительно очень токсичны, оскорбляют всех, кто что-то говорит, пинают без причины, удаляют чужие схемы и многое другое
> 
> > 
> 
> > Один из моих друзей отключился из-за разногласий, у него вообще нет сообщений, он просто существовал в разногласиях, у него было нитро, я думаю, один из админов думал, что он был источником денег, или существует незаконно?
> 
> 
> 
> I need more evidence to deal with it.
> 
> In particular, who from the Dmitry did this do? Why do you complain about it here and not me in the drug in the Discird or on our server?
> 
> 
> 
> You probably did not see, but P2W is not in our part. We did not have any privileges that would have made the advantage.

Dude, just close the issue, Anuke already said he won't change his mind. If you keep spamming, he will do nothing but hate you even more. It's for your own good.

**Comment by Volas171** [comment]
just close this

**Comment by MindustryRu** [comment]
> Самое смешное, что они вообще не прислушались к сообществу и начали вносить изменения только после того, как их сервер был удален из списка.
> 
> Пожалуйста остановись.

А не было толком предложений что-то исправить, Для этого я и создал эту тему.
And it was not a clear proposals to fix something, for this I created this topic.

**Comment by iutisteli** [comment]
If you don't close the issue, you will do nothing but harm your reputation even more. Anuke said he won't change his mind, no matter what you do. What is it so hard to understand? Just close this. It is this simple.

**Comment by MindustryRu** [comment]
> так что вы серьезно ожидаете, что это изменит мнение anukes

Мы ожидаем что это поможет на исправится.
We expect that it will help to improve.

**Comment by Volas171** [comment]
нет, просто закрой этого ануке, не изменит его мнение об этом

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

### *To everyone:*

**Can everyone stop adding more to this thread.
If anuke is done with this. Everyone should follow suit.**

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by Volas171** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)
 
 ### _To everyone:_
 **Can everyone stop adding more to this thread. If anuke is done with this. Everyone should follow suit.**
 
 **Also to the person who opened this issue:**
 
нет, просто закрой этого ануке, не изменит его мнение об этом

**Comment by Remint32** [comment]
*Ануке просто так не закрыть* )

**Comment by summetdev** [comment]
@Volas171, "Просто закройте это, Anuke не изменит своё мнение."

**Comment by max2007-69** [comment]
> > * i will request verification of no more pay to win (including any pay to unmute/unban) from trusted sources
> > * simple, clean out your entire admin group and start fresh using a trustworthy promotion system.
> > * nobody really likes you being around, and though i harbour no personal hatred towards you or your server, i dislike the money gouging and how you have handled moderation of the playerbase.
> > 
> > also, three PRs and a Q&A? you brave child, it alone won't get you on the server list.
> 
> We did not have a donation that gave advantages.
> У нас не было доната который давал преимуществ.

Разве источник и трезубец со старта для тех, кто задонатил это были не преимущества?

**Comment by max2007-69** [comment]
> > так что вы серьезно ожидаете, что это изменит мнение anukes
> 
> Мы ожидаем что это поможет нам исправится.
> We expect that it will help us will be corrected.

Да, вы возможно станете лучше, но анюк выдвинул окончательное решение о добавлении вас в глобальный список 6.0, будет круто, если вы станете лучше в глазах коммьюнити(моих в том числе)

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

### *To everyone:*

**Can everyone stop adding more to this thread.
If anuke is done with this. Everyone should follow suit.**

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by Volas171** [comment]
@itcannotbe stop spamming please, we know but let these kids lecture themselves while they don't see they are harming themselves lul.

**Comment by itcannotbe** [comment]
What spam?

**Comment by itcannotbe** [comment]
![Screenshot_20201207_125518](https://user-images.githubusercontent.com/45280919/101320753-3bd98a00-389f-11eb-9ebb-5c720f59ad76.jpg)
![Screenshot_20201207_125320](https://user-images.githubusercontent.com/45280919/101320767-3f6d1100-389f-11eb-8a10-144312d57692.jpg)

### *To everyone:*

**Can everyone stop adding more to this thread.
If anuke is done with this. Everyone should follow suit.**

**Also to the person who opened this issue:**

Close this and 🐝gone.

**Comment by kiVts** [comment]
did I missed a scandal about it? wow, were I was. Gang of a family. I can tell you how admin are 'chosen' 'Wow I like you, want to be head of project?'

**Comment by Anuken** [comment]
As I said, I don't want to deal with this anymore. One of the reasons I closed that request is that *I get forced to deal with every problem that comes up with this server*. 

The issue tracker is for Mindustry-specific issues. If you wish to discuss this, take it elsewhere.
