### ISSUE TITLE
Units's property "controlled" doesn't become true when the unit is commanded into a player's squad.

### ISSUE THREAD

**Issue by Arcafanetiz** [Anuken/Mindustry#3833]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: 121

**Issue**: Units's property "controlled" doesn't become true when the unit is commanded into a player's squad.

**Steps to reproduce**: Make a processor to bind a unit, output the controlled property into a message, then command said bound unit.

**Link(s) to mod(s) used**: -

**Save file**: -

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That property only refers to player or logic control.
