### ISSUE TITLE
Interplanetary crash

### ISSUE THREAD

**Issue by Mythicavenger** [Anuken/Mindustry#3834]
Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Steam build 121

**Issue**: After completing the Interplanetary accelerator on any captured zone game will crash
[crash-report-12_06_2020_23_19_38.txt](https://github.com/Anuken/Mindustry/files/5651058/crash-report-12_06_2020_23_19_38.txt)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
**Save file**: *  [saves.zip](https://github.com/Anuken/Mindustry/files/5651085/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**mods**
[MEEPofFaithprogressed-materials.zip](https://github.com/Anuken/Mindustry/files/5651067/MEEPofFaithprogressed-materials.zip)
[MesokrixVanilla-Upgraded.zip](https://github.com/Anuken/Mindustry/files/5651069/MesokrixVanilla-Upgraded.zip)
[SMIPE444Infinity-Cheat.zip](https://github.com/Anuken/Mindustry/files/5651070/SMIPE444Infinity-Cheat.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
my guess is that https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/campaign/Accelerator.java#L24 gets triggered before any mods get their item content loaded 🤔
