### ISSUE TITLE
Power node visual bug

### ISSUE THREAD

**Issue by reddraegon** [Anuken/Mindustry#3835]
**Platform**: *Windows*

**Build**: *121*

**Issue**: *The issue is about those orange lines (idk how they are called)
![image](https://user-images.githubusercontent.com/56732705/101324507-ab815200-386a-11eb-9206-970d17491f76.png)
 that disappear after you double click the  node *

**Steps to reproduce**: *
1. Hover on a node:
![image](https://user-images.githubusercontent.com/56732705/101324967-4c700d00-386b-11eb-830a-bdb9e06fb9dc.png)
2. Double click on the node (when you dont have a mouse on the node the power display resets)
![image](https://user-images.githubusercontent.com/56732705/101325252-bbe5fc80-386b-11eb-88b2-8797d2ad5470.png)
3. Hover off the node:
![image](https://user-images.githubusercontent.com/56732705/101325686-7544d200-386c-11eb-98cb-020ac3bdeac2.png)
4. Hover on the node and double click it:
![image](https://user-images.githubusercontent.com/56732705/101325759-94436400-386c-11eb-9bf6-d1d9e7c76b53.png)

The orange bar doesnt display:
![image](https://user-images.githubusercontent.com/56732705/101325868-bd63f480-386c-11eb-88ab-c015faad5074.png)

I saw the issue posted earlier but the user didnt give much info about it*

**Link(s) to mod(s) used**: *None*

**Save file**: *[saves.zip](https://github.com/Anuken/Mindustry/files/5651354/saves.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Issue not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
double clicking a power node removes all connections, or connects to all available in range, its not a bug

**Comment by RedDragonMZ** [comment]
Update: Tested it again on a normal node and realised that the bug happens on both large and normal nodes

**Comment by Quick-korkc** [comment]
just a visual bug

**Comment by RedDragonMZ** [comment]
yes but still 


> just a visual bug

yes but still
