### ISSUE TITLE
I have the same issue. I loved v104, worked great. updated today to latest and the graphics have horizontal green stripes and is unreadable.  ( i can make out where the menu is and exit :-) )

### ISSUE THREAD

**Issue by HerrBach2001** [Anuken/Mindustry#3842]
I have the same issue. I loved v104, worked great. updated today to latest and the graphics have horizontal green stripes and is unreadable.  ( i can make out where the menu is and exit :-) )
Also Windows 10, 64 bit.
I updated my graphics driver for my graphics card: NVIDIA GeForce 940MX to no avail.
I tried going back versions, and the first version with this issue is v106.
Would a screen shot help?
I see this is closed today, is there a solution posted that I am missing? 
Would love to play the new version!
Thanks,
Chris

_Originally posted by @magicc22 in https://github.com/Anuken/Mindustry/issues/3820#issuecomment-739585469_

did you use winrar to open the mindustry file or did you open it with Windows?

**Comment by Erisfiregamer1** [comment]
Template, please

**Comment by BlueWolf3682** [comment]
@Erisfiregamer1 they didnt open it as a bug report, so it did not give a template

**Comment by Erisfiregamer1** [comment]
How do you NOT open something as a bug report? The only option IS to open a bug report.

**Comment by HerrBach2001** [comment]
> How do you NOT open something as a bug report? The only option IS to open a bug report.

I didn't understand your question.

**Comment by BlueWolf3682** [comment]
> How do you NOT open something as a bug report? The only option IS to open a bug report.

by removing the bug label

**Comment by DeltaNedas** [comment]
woah imagine if you checked for the 10 duplicate reports  or updated your gpu drivers
`apt install libgl1-mesa-glx`

**Comment by Anuken** [comment]
1. stop telling that to people that don't even use linux
2. this happens even with seemingly up-to-date graphics drivers

**Comment by Adri-15** [comment]
@Anuken I don't know if it's useful or not, but I can reproduce the problem by opening the * .exe. However, the problem disappears if I open desktop.jar (inside the jre folder) and modify the settings: disabling vsync and enabling full screen.

**Comment by Anuken** [comment]
Yes, I know that fullscreen fixes it in certain situations, but nothing I've tried on *my* end can fix it.
