### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by HerrBach2001** [Anuken/Mindustry#3845]
https://github.com/Anuken/Mindustry/issues/3820#issue-757945444

**Comment by BlueWolf3682** [comment]
*stop opening new issues, there is a COMMENT feature for speaking in github issues.*

**Comment by HerrBach2001** [comment]
> _stop opening new issues, there is a COMMENT feature for speaking in github issues._

Sorrry I'm new on Github.

**Comment by BlueWolf3682** [comment]
thats a good boy
