### ISSUE TITLE
bug mindustry 07/12/2020

### ISSUE THREAD

**Issue by ammv** [Anuken/Mindustry#3847]
**Platform**:Windows

**Build**: "LATEST"

**Issue**: *I was just playing on a PVP server, and I got an error window, it says something about c++, and there were 2 errors. I clicked 2 times skip

**Steps to reproduce**: Possible: go to the pvp server and wait for the moment X

**Link(s) to mod(s) used**: No use

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**(Crash) logs**: https://cloud.mail.ru/public/2eHX/5953inpzs
I do not know how to attach the .log file
. I saved it to the cloud mail.ru and left a link
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this.

**Comment by DeltaNedas** [comment]
"LATEST"
