### ISSUE TITLE
Logic processor string compare is broken

### ISSUE THREAD

**Issue by Bindernews** [Anuken/Mindustry#3848]
**Platform**: Windows 10 x64

**Build**: Steam build 121

**Issue**: Logic processor comparisons don't compare strings properly (I believe you're using `==` and `!=` in the code, and Strings should use `.equals`).

**Steps to reproduce**: 

I was using logic processors to try to make lancers shoot where I'm shooting. I also have a message block attached for debugging, so I tried to check the type of the link, and see if the link is a lancer (turns out it's unnecessary because messages will just ignore the "shoot" command, but the bug is still there). The issue is that `if typ not "lancer"` always returns true, even when the message output clearly says "lancer". 

To see this in-game, create a logic processor and connect it to a lancer and a message box, then use this script:
```
radar player any any distance @this 1 ply
sensor ax ply @shootX
sensor ay ply @shootY
sensor shooting ply @shooting
set i 0
getlink lnk i
sensor typ lnk @type
print typ
printflush message1
jump 11 notEqual typ "lancer"
control shoot lnk ax ay shooting 0
op add i i 1
jump 5 lessThan i @links
```

**Link(s) to mod(s) used**: No mods

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5654771/saves.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
`@type` does not return a string. Messages may display 'lancer', but that is irrelevant. Similarly, `"1"` != `1`, even if they are displayed the same in message blocks.
