### ISSUE TITLE
Junction storage

### ISSUE THREAD

**Issue by mockwriter7772** [Anuken/Mindustry#3849]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
122
**Issue**: *Explain your issue in detail.*
Junctions do not have a consistant storage amount based on an experiment i did
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I set up 2 different storage schemes
1.) Junction junction junction
2.) Router junction router
The first one gives 36 storage and 36 divided by 3 is 12
The second one only gives 22 when it should give 26
(26 - 2) / 2 is 12
(22 - 2) / 2 is 10
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Idk how to do a save but i have the map i was doing
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a problem.

**Comment by mockwriter7772** [comment]
Why does it do that

**Comment by Anuken** [comment]
I don't care. Don't store items in junctions.
