### ISSUE TITLE
Units being killed when dropped by an Oct

### ISSUE THREAD

**Issue by nodevlfrb** [Anuken/Mindustry#3850]
**Platform**: Windows

**Build**: Release 121
**Issue**: When picking up t4 or t5 units with an Oct, once picked up, they die instantly when dropped, causing the loss of them.

**Steps to reproduce**: Pick a Toxopid or a Scepter with a Oct; drop them and they'll die.
**Link(s) to mod(s) used**: N/A
**Save file**:  file at https://we.tl/t-uAfp6kUM4S

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

_i screenshotted but i can't find the screenshot bruh_

**Comment by Anuken** [comment]
You're hitting the unit cap. Any units above the cap will die once dropped.

**Comment by Legomonster33** [comment]
> You're hitting the unit cap. Any units above the cap will die once dropped.

shouldn't carried units be counted towards the cap so this doesn't happen?

**Comment by Legomonster33** [comment]
> You're hitting the unit cap. Any units above the cap will die once dropped.

shouldn't carried units be counted towards the cap so this doesn't happen?

**Comment by nodevlfrb** [comment]
I 

> You're hitting the unit cap. Any units above the cap will die once dropped.

This is not the main reason I am doing this issue.  Carried units should be counted in the cap so you can't indefinitely kill your units by picking them and droppping them, it would cause the loss of many resources, given that they are T5 units. I repeated the steps, and for someone who don't know how it works, maybe that wouldn't be very pleasant. 
Of course i know what is the unit cap :)
