### ISSUE TITLE
Wrong keys being displayed by the tutorial/menus

### ISSUE THREAD

**Issue by el-Basketo** [Anuken/Mindustry#3853]
**Platform**: *Windows*

**Build**: *121*

**Issue**: *Wrong keys being displayed by the tutorial/menu.*

The game indicates the keys "[" and "]" to pick up and lay down blocks and units.

![Capture d’écran 2020-12-07 232140](https://user-images.githubusercontent.com/75644848/101412506-048ccc80-38e3-11eb-97cc-fe3f37dfd265.png)

There's a TL,DR below, this is spaghetti sentences :
The characters "[" and "]" are located on the "5" and "°" number keys in my layout (not numpad, top row of numbers).
They are accessed using "altgr+5" and "altgr+°".
However, pressing "altgr+°" in game has the same effect as pressing "5" (opens electrical blocks menu). Same goes for "altgr+°".
The keys I have to press are "^" and "$" on my keyboard, which are located where "[" and "]" are on an american keyboard.

![IMG_20201207_225200 1](https://user-images.githubusercontent.com/75644848/101411774-d2c73600-38e1-11eb-8912-f21b21343837.jpg)
TL,DR : Game indicates red, I actually have to press green.
No so confusing when its only about wasd being zqsd, but more exotic characters like these really need to be indicated more clearly to the player.

I think a similar issue has already been reported (https://github.com/Anuken/Mindustry/issues/1151) and closed.

Is there really no way for the game to obtain layout information and display keys accordingly? From my experience, games usually read characters and not scancodes.

Thank you for your work, please don't reap my soul Anuken god, your game is genius.

**Steps to reproduce**: *Play with a french keyboard which scancodes actually correspond to american characters?*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A*

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
You are mistaking parentheses (round brackets, "(" and ")") with square brackets ("[" and "]").

**Comment by el-Basketo** [comment]
No, I am actually not. My "5" key has 3 characters on it : 

- primary "("

- shift "5"

- altgr "[" (it is a bit small, but definitely visible on the picture)

Yes I know I can rebind keys, this is not the issue I'm describing.
I'm trying to point out that the current input system makes it really confusing to play with a non-american layout.
Trying to input "[", the character that **the game pretends it's expecting** doesn't work. (on my keyboard, this is done by pressing "altgr+5", or "altgr+(" however you want to call it. This stroke sends "[" to windows)
I have to press "^" instead, which isn't what the game tells me.

If you took the time to read https://github.com/Anuken/Mindustry/issues/1151, you know this comes from the game reading scancodes instead of characters.

**Comment by Anuken** [comment]
> I'm trying to point out that the current input system makes it really confusing to play with a non-american layout.

I am aware. My reply is the same as it was before: https://github.com/Anuken/Mindustry/issues/1151#issuecomment-560613884

> Is there really no way for the game to obtain layout information and display keys accordingly?

It's probably possible, but there is quite a lot of (boring) work required to do so. I'm not interested in implementing it.
