### ISSUE TITLE
Sound is not always playing at the right time/inconsistent

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#3856]
**Platform**: *Android/iOS/Mac/Windows/Linux*

 Steam/Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Release 121

**Issue**: *Explain your issue in detail.*

Continuous sounds tend to misplay, often play at slightly delayed or offset times of when they should. This bug has been around for awhile with the new sound system and I guess no one really realized it. It occurs when firing turrets or even your T3 gamma core ship.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Fire a cryo fuse, a spectre, a cyclone, or just continually shoot the Gamma ship (im sure there are other ships too) and listen closely. You will hear the sound being inconsistent with the actual firing of the weapons

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[sound issue.zip](https://github.com/Anuken/Mindustry/files/5656477/sound.issue.zip)

_please dont take my existence_ 👀 

~~at least its not a bug with mega like my last 3 or 4 reports~~

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Soham-maiti** [comment]
It happens in campaign while shooting in level 30

**Comment by TNT331** [comment]
Still not fixed? I thought he fix when he did V5 -> V6

**Comment by Anuken** [comment]
Cannot reproduce - no sync or latency problems on my Linux machine. Sound is somewhat laggy on my Windows VM, but *everything* is laggy there, so it's impossible to test properly.
