### ISSUE TITLE
Bugged "player" AI

### ISSUE THREAD

**Issue by TNT331** [Anuken/Mindustry#3861]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
V 121

**Issue**: *Explain your issue in detail.*
AI, or red. When build is enabled, they will try to build buildings and when something is broken they try to rebuild it. HOWEVER, when they build something on the other side of a defence, the build will get damaged/destroyed making the AI constantly want to go build the building. And the result is AI stuck there forever trying to build the same thing. Another possibility is that sometimes it wants to finish a build so it keep trying to cross an area with Anti Air defence but it fails to make it across and what it does is try again and again and again... This effects all the "player" AI since they will all do only one build at a time(schematics) 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
make an attack map, start it, have enemy AI build on, now wait until they build something close to your base. GO AROUND THAT BUILD and put anti-air to block any air units from getting close to the build. Break something in that build. AND THE LOOP BEGINS! The AI will only ever try to repair, they will never give up which should be added (after failing to build the schematic a # of times, it will stop and go build something else).

REAP MY SOUL! BTW I DON'T HAVE MY PC HERE >:)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug.
