### ISSUE TITLE
Fungal Pass

### ISSUE THREAD

**Issue by AndromedaFallen** [Anuken/Mindustry#3864]
**Platform**: *Android*

**Build**: 121

**Issue**: So I had captured fungal pass, and was attacking the enemy base next to it. Whilst I was in the process of attacking the enemy base, I lost fungal pass to that exact same enemy base that I was currently attacking. If it's a feature, sorry.

**Steps to reproduce**: Capture fungal pass in campaign, defend yourself in the tile right between it and overgrowth for as long as possible. Eventually lose fungal pass.
**Link(s) to mod(s) used**: https://github.com/K103908/Exotic-Mod

**Save file**: I can give you a save file from before me going in to capture fungal pass, but because Infinitodustry prevented the game from loading, I lost most of my progress.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by AndromedaFallen** [comment]
whoops forgot the save file[

https://drive.google.com/file/d/1bBFp4rgD6-jWALaqMoH4-9hxitCzctK_/view?usp=sharing

**Comment by Anuken** [comment]
Not a bug.
