### ISSUE TITLE
Windswept islands crashes my game

### ISSUE THREAD

**Issue by thesupertechno** [Anuken/Mindustry#3867]
**Platform**: Android 4, on Samsung galaxy S3

**Build**: 121

**Issue**: Boots me to home screen when I try to go to Windswept Islands

**Steps to reproduce**: 1. Open mindustry on a S3. 2. Try to go to Windswept Islands

**Link(s) to mod(s) used**: No mods, just the vanilla game

**Save file**: 
[My save.zip](https://github.com/Anuken/Mindustry/files/5660427/My.save.zip)

**(Crash) logs**: [Oof.txt](https://github.com/Anuken/Mindustry/files/5660434/Oof.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That crash log has nothing to do with what you're reporting, and was already fixed.
