### ISSUE TITLE
Mods that add Base Parts are not being registered (and modded Boulder blocks *are* generating on Serpulo)

### ISSUE THREAD

**Issue by z0mbiesrock** [Anuken/Mindustry#3872]
**Platform**: *Android/iOS/Mac/**Windows**/Linux*

**Build**: Steam 121

**Issue**: 
_A 2 in 1 issue:_ 
A mod I am making has base part schematics, but the game does not register them. I tried looking in the source code for a connection, but nothing.

On the other hand, centain environmental blocks I added in the mod also generate in sectors.
![20201208153329_1](https://user-images.githubusercontent.com/19158169/101538269-d3f07580-396a-11eb-8ab4-a08884124b4e.jpg)

**Steps to reproduce**: https://github.com/z0mbiesrock/Diamond-Ore/tree/6.0/baseparts

**Link(s) to mod(s) used**: https://github.com/z0mbiesrock/Diamond-Ore/tree/6.0

**Save file**:
For the base parts issue, idk. But for the modded Boulder blocks:
[sector-serpulo-173.zip](https://github.com/Anuken/Mindustry/files/5661784/sector-serpulo-173.zip)
.zip of sector 173, freshly generated

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> A mod I am making has base part schematics, but the game does not register them.

They don't get registered automatically, and there is no built-in mechanism for doing so. Why do you assume it is supported?

> Certain environmental blocks I added in the mod also generate in sectors.

This... isn't really a bug. Floors automatically pick the most color-appropriate block to use for decoration. I can disable it for mods completely, but that may not always be desirable.

**Comment by z0mbiesrock** [comment]
> This... isn't really a bug. Floors automatically pick the most color-appropriate block to use for decoration. I can disable it for mods completely, but that may not always be desirable.

You don't need to. Maybe there's  another way...

> They don't get registered automatically, and there is no built-in mechanism for doing so. Why do you assume it is supported?

Because there's a "baseparts" folder
