### ISSUE TITLE
Mods are unable to add hints

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3874]
**Platform**: *Windows*

**Build**: *Steam 121*

**Issue**: *NullPointerError when I try to add a custom Hint, using the JavaAdapter, new or extend() to create my own hint and sticking it in the HintsFragment.*

**Steps to reproduce**: 
I tested all inside functions(no matter how weird they may seem, its part of a library so the code is valid). Also tested with them just returning true or false, no luck either.
```
var ahint = new HintsFragment.Hint({ //tried extend() too, both crashes the same way
  name(){
    return "activeskilltest1";
  },
  text(){
    return !Vars.mobile ? "$hint.activeskill.text" : "$hint.activeskill.text.mobile";
  },
  order(){
    return 0;
  },
  valid(){
    return true;
  },
  complete(){
    return false;
    //return Vars.player.unit().useSkills && Vars.player.unit().getCool(0) > 0;//tmp
  },
  show(){
    return true;
    //return Vars.player.unit().type.abilities.find(a => typeof a.isActiveSkill == "function") != null;
  }
});
Vars.ui.hints.hints.add(ahint);
```

**Link(s) to mod(s) used**: *I used sk7725/Testers to run the js above, you can just use the console too.*

**Save file**: *codewise, insta-crash issue*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
```
Mindustry has crashed. How unfortunate.
Version: steam build 121
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
6 Mods: pictologic:1.5.3, testers:0.25, time-control:0.2, ui-lib:2.16.6, unity:0.3, commandblocks:0.8289 [accent]Beta 12[]

java.lang.NullPointerException
	at arc.struct.Seq.find(Seq.java:346)
	at mindustry.ui.fragments.HintsFragment.lambda$build$2(HintsFragment.java:52)
	at arc.scene.Element.act(Element.java:79)
	at arc.scene.Group.act(Group.java:37)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Group.act(Group.java:41)
	at arc.scene.Scene.act(Scene.java:185)
	at arc.scene.Scene.act(Scene.java:133)
	at mindustry.core.UI.update(UI.java:140)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Esnardo** [comment]
Sk: Encounters a bug while using a function that doesn't even exist to simulate mindustry in mindustry
Anuke 5 minutes later: Fixed



~~I ship it~~
