### ISSUE TITLE
Mod translation has problem on the official Android release by default

### ISSUE THREAD

**Issue by abomb4** [Anuken/Mindustry#3875]
By default, the mod content is displayed in English, but the game display language has been set to Simplified Chinese by default (I'm using Simplified Chinese Android system).
When I switch the game display language to another language and then switch back to Simplified Chinese, the mod content will be displayed correctly.
This problem not produced on Windows, Android beta version and Android custom builds, only the release version on itch.io and Google Play has this problem

**Comment by Anuken** [comment]
[Template.](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#you-did-not-fill-in-the-template)
