### ISSUE TITLE
Mods bugados

### ISSUE THREAD

**Issue by kibuika-gif** [Anuken/Mindustry#3877]
**Android**

**V6 121

**When any mod is connected the game does not open

**I just tried to connect a mod remembering that I did it with several mods

**This happens with all mods available for v6

**https://drive.google.com/file/d/1-0MJ8X6VarWF9LlcNlb873aotsD-2pX3/view?usp=drivesdk

**(Crash) logs** it is not possible to do this on mobile I think

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by kiVts** [comment]
it is possible to get crash logs
look in obb and then anuken

**Comment by Anuken** [comment]
No logs.
