### ISSUE TITLE
Crash when playing multiplayer

### ISSUE THREAD

**Issue by Quick-korkc** [Anuken/Mindustry#3878]
**Platform**: Windows

**Build**: release build 121

**Issue**: The game crashed in server io

**Steps to reproduce**: The game crashed when playing multiplayer in server io, idk what happen

**Link(s) to mod(s) used**: None mods are active

**Save file**: the game crashed

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crash-report-12_09_2020_12_14_48.txt](https://github.com/Anuken/Mindustry/files/5663645/crash-report-12_09_2020_12_14_48.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DarkBrick** [comment]
RIP your soul in that case

**Comment by kiVts** [comment]
RIP

**Comment by Anuken** [comment]
> Save file: the game crashed

Doesn't matter, I still need the save file to debug this. You are still able to join the server again and save if necessary.
