### ISSUE TITLE
Some achievements appears to be buggy

### ISSUE THREAD

**Issue by Tidus797979** [Anuken/Mindustry#3881]
Platform: Windows

Build: 121

Issue: There might be some bugs with a few achievements :

- Escalation : construct a Tier 5 unit -> I created a T5 Eclipse and it did not unlock. 

- Production I & Production II : Reach 5000/50000 items/min total production in the campaign -> the count looks wrong to me, it displays 838 items/min when just one of my sector produces at least 4000 items/minutes

Link(s) to mod(s) used: No mod used

Save file: None

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Place an X (no spaces) between the brackets to confirm that you have read the line below.

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by D-player1** [comment]
How is Anuke going to see that you actually have 4000 items/s if you don't include the save file

**Comment by Tidus797979** [comment]
Here is the save file : 
[saves.zip](https://github.com/Anuken/Mindustry/files/5665253/saves.zip)
