### ISSUE TITLE
Ores' priority over sand is hardcoded

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#3882]
**Platform**: *Any*

**Build**: *121*

**Issue**: *The problem might occur in modded game. E.g. you added some floor like sand that can be mined. But if there is an ore this "floor ore" will still count as ore making getting "real" ore hard.*

![image](https://user-images.githubusercontent.com/40753025/101625726-e501bb00-3a2c-11eb-87b5-d6c6a51a14e1.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Should be a suggestion + PR instead of a bug report to be honest.

**Comment by Anuken** [comment]
Not a bug.
