### ISSUE TITLE
oof

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [Anuken/Mindustry#3883]
**Platform**: *Windows*

**Build**: *121*

**Issue**: *if you finish opening mindustry, it crashes*

**Steps to reproduce**: *download every mod from https://github.com/topics/mindustry-mod-v6 and put them onto mindustry and bam*

**Link(s) to mod(s) used**: *
too many, but every mod in https://github.com/topics/mindustry-mod-v6
*

**Save file**: *none, came when finished loading*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *
[crash-report-11_03_2020_09_45_40.txt](https://github.com/Anuken/Mindustry/files/5666037/crash-report-11_03_2020_09_45_40.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** (crash logs say its 111 for some lmfaoing reason)
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
To be expected that EVERY MOD IN THE LIST will crash your game. That's kinda not gonna be fixed?

**Comment by Quick-korkc** [comment]
wrong crash log lmao
this one is beta 111

**Comment by ThisIsACoolBoy** [comment]
but it shows the date
which matches mine and im running 121

**Comment by Anuken** [comment]
> Version: beta build 111

**Comment by ThisIsACoolBoy** [comment]
i guess i'd reinstall mindustry because its saying 121 when joining

**Comment by ThisIsACoolBoy** [comment]
![image](https://user-images.githubusercontent.com/48828036/101652127-4cccfb80-3a57-11eb-8622-8428f155a5f6.png)
tried testing both modded and un modded, unmodded returned 121 but modded returned 111
i might check the crash log again

**Comment by Anuken** [comment]
Even if you manage to get the right version in the report, this is still an issue with the mods, not with vanilla Mindustry.
