### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by 1233413** [Anuken/Mindustry#3884]
**Platform**: windows 7

**Build**: *The build number under the title in the main menu. 
 itch.io build 121

**Issue**: *Explain your issue in detail.* crash

**Steps to reproduce**: i don't know sorry

**Link(s) to mod(s) used**:  no mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. uhh i didn't saved it sorry 
**(Crash) logs**: 
[crash-report-12_09_2020_15_06_34.txt](https://github.com/Anuken/Mindustry/files/5666476/crash-report-12_09_2020_15_06_34.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by kiVts** [comment]
You do have mods

**Comment by kiVts** [comment]
Mindustry has crashed. How unfortunate.
Version: release build 121
OS: Windows 7 x64
Java Version: 1.8.0_72
Java Architecture: 64
**17 Mods:** [#460096]shadow[#ffffff]dustry:3.9.2, [purple]better[]-blocks-mod:1.2, [white]lead-industri[pink]es:1.3, advancecontent:1.9.1 Final Major Update, diamond-ore:[#9cb6f4]1.27[], example-mod:3.2, extended-unit-arsenal:1, inverted-machines:1.3, mechanical-warfare:1.6, multi-smeltermod:1.0, overdriven:0.3-Release, routorio:1.22.2, thorge-ex:1, vanilla-enhanced:1.6, youtube-cannon:1, goldmod:2.0 alpha b10, heavy-armaments:2.0

**Comment by kiVts** [comment]
Yes it could be not active...
