### ISSUE TITLE
oof [FIXED]

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [Anuken/Mindustry#3887]
**Platform**: *Windows*

**Build**: *121*

**Issue**: *if you finish opening mindustry, it crashes*

**Steps to reproduce**: *download every mod from https://github.com/topics/mindustry-mod-v6 and put them onto mindustry and bam*

**Link(s) to mod(s) used**: *
too many, but every mod in https://github.com/topics/mindustry-mod-v6
*

**Save file**: *none, came when finished loading*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *
[crash-report-12_09_2020_19_50_02.txt](https://github.com/Anuken/Mindustry/files/5667035/crash-report-12_09_2020_19_50_02.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] finally i found the correct crash report

**Comment by Anuken** [comment]
This is a mod error, not a Mindustry error.

**Comment by ThisIsACoolBoy** [comment]
well, now what, i cant see what mod is making the error

**Comment by RogueRedHawk** [comment]
@ThisIsACoolBoy Don't use every single mod at once. Or, test them one by one to see which one is causing the problem. This is not Anuke's problem.

**Comment by ThisIsACoolBoy** [comment]
> 
> 
> @ThisIsACoolBoy Don't use every single mod at once. Or, test them one by one to see which one is causing the problem. This is not Anuke's problem.

ok
