### ISSUE TITLE
Double click issue: Campaign 

### ISSUE THREAD

**Issue by FatalS117** [Anuken/Mindustry#3890]
**Platform**: *Windows 10 64bits*

**Build**: *121.1 Steam*

**Issue**: the game crashes and displays an error window

**Steps to reproduce**: Double clicking around the campaign planet but clicking twice on the planet will not do anything special.

**Save File**: [Save File.zip](https://github.com/Anuken/Mindustry/files/5667951/Save.File.zip)

**(Crash) logs**: [crash-report-12_09_2020_15_15_20.txt](https://github.com/Anuken/Mindustry/files/5667890/crash-report-12_09_2020_15_15_20.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
This crash happens if, in the planet map, you double-click outside the planet. How did I not test for this 😣
