### ISSUE TITLE
Ground units not rallying to a new command center.

### ISSUE THREAD

**Issue by Spyrox17** [Anuken/Mindustry#3893]
**Platform**: Windows

**Build**: 121.1

**Issue**: Ground units **sometimes** do not go to a new command center, unlike air units, and will stay back at a non-existing command center when tasked to rally.
Lower left is the deletion/deleted of the command center, and top right is the new one.
![1](https://user-images.githubusercontent.com/35882822/101677615-c8648380-3a2a-11eb-8453-59d4708674f8.png)

It doesn't seem to happen all the time though so I'm unsure what the exact perquisites are for it. Could be mod related as I haven't had the issue with vanilla yet (although I haven't made Tier 3 units in vanilla either yet).
**Steps to reproduce**: 
1. Have ground units on the map. (this may or may not be required, but nearly all the times I've had the issue was when there was pre-existing units on the map).
2. Build a command center and then rally.
3. Build another command center in a different spot. 
4. Delete the previous command center. 
Ground units will persist to stay there and will not go to the new one to rally, even if you have them attack and come within proximity of the new one.

**Link(s) to mod(s) used**: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1908598970
https://steamcommunity.com/sharedfiles/filedetails/?id=1917262516
https://steamcommunity.com/sharedfiles/filedetails/?id=1899036328
https://steamcommunity.com/sharedfiles/filedetails/?id=1905709851
https://steamcommunity.com/sharedfiles/filedetails/?id=2014689433

**Save file**: 
[sector-serpulo-124.zip](https://github.com/Anuken/Mindustry/files/5668183/sector-serpulo-124.zip)

**(Crash) logs**: [N/A]

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
something potentially related, crux wave units getting stuck in clusters, didn't happen before, be build can be time traced:

![Screen Shot 2020-12-08 at 11 10 19](https://user-images.githubusercontent.com/3179271/101678127-cff15000-3a5d-11eb-8ec1-05454369db61.png)

**Comment by Anuken** [comment]
Cannot reproduce. Your save cannot be used, as it is modded.

**Comment by Spyrox17** [comment]
then why ask for mods in the first place on the template if we can't use them -_-
