### ISSUE TITLE
Client research not unlocked for host

### ISSUE THREAD

**Issue by Reznoriam** [Anuken/Mindustry#3895]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
121

**Issue**: *Explain your issue in detail.*
When a client connected to my multiplayer game completed a research it both used the resources from my host map and did not give the host the research. It was necessary to complete the research again as the host to unlock the technology.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Client completes research while connected to multiplayer host.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

[asdfasdfasdf.zip](https://github.com/Anuken/Mindustry/files/5668262/asdfasdfasdf.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
Have not tested in 121.2 since that was just released
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> did not give the host the research

The host is not supposed to get the research.
