### ISSUE TITLE
Cancel bug 

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry#3897]
**Platform**: *iOS*

**Build**: *121 release, there isn’t any new version yet for me*

**Issue**: *after tapping “cancel” button while editing something in a processor the keyboard pops up again.*

**Steps to reproduce**: *1. Open a processor and add a command 2. Edit a field 3. Tap “cancel” 4. Keyboard pops up again*

**Link(s) to mod(s) used**: *doesn’t matter, checked it without the mods.*

**Save file**: 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5668571/mindustry-data-export.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no need*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed

**Comment by Sanya2907** [comment]
Is fixed version still not out? On 121.2 it still exists

**Comment by Sanya2907** [comment]
Version 121.3, still not fixed. Why?

**Comment by Sanya2907** [comment]
Version 121.4: not fixed
