### ISSUE TITLE
Unloader will slow down or stop pulling 1 or 2 items from vault.

### ISSUE THREAD

**Issue by Volatile111** [Anuken/Mindustry#3899]
**Platform**: Windows

**Build**: 120-121.2

**Issue**: The issue I'm having is I'm using 2 Unspecified item unloaders to pull from one vault to one pyratite for the 3 resources that it needs. Doing this works fine for a bit and doesn't always mess up but sometimes it will stop pulling one of said resources from the vault and or slow down pulling 1 or 2 resources. In the image my top left impact reactor is shut down because of this issue.
<img width="371" alt="mindustry2" src="https://user-images.githubusercontent.com/75761168/101702292-336f8380-3a46-11eb-977f-2240c29c74df.png">

**Steps to reproduce**: Place 2 Unspecified item unloaders on the vault then place 1 pryatite mixer right in front of the 2 unloaders on vault.
<img width="715" alt="mindustry1" src="https://user-images.githubusercontent.com/75761168/101702194-04591200-3a46-11eb-8cbf-7442f620d4fb.png">

**Link(s) to mod(s) used**: This issue happens with mods and without

**Save file**: 
[unloaderbug.zip](https://github.com/Anuken/Mindustry/files/5669325/unloaderbug.zip)

**(Crash) logs**: no crashes

**Extra**: The images used in this report were taken from linked saved file. The only way I have found to keep it from stopping or slowing down the items is to place another unloader on the vault right next to one of the other 2 unloaders but this only works for a bit then it goes back to not working properly.

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by D-player1** [comment]
Your schematic needs more spore

**Comment by GreyMario** [comment]
I'd like to mention that I have also experienced this, so this isn't isolated.

**Comment by Volatile111** [comment]
> Your schematic needs more spore

It does not. it works just fine as is other than said bug
