### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#3903]
Android

121.2

There a stuttering for unknown reasons and its always right after the sector is captured and you get surge up

I placed an impact and made a surge defense and then it started stuttering it doesn't always happen but i crash sometimes cuz of it

0 mods used

I can't access campaign save files and i can't post a file into an issue so i may have to send my mindustry data

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

I didn't crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
your soul. Hand it over. N O W .

**Comment by Anuken** [comment]
> i crash sometimes cuz of it
> I didn't crash

Do you, or do you not crash? If you do, **post the crash report.**

> I can't access campaign save files and i can't post a file into an issue

*required*

**Comment by DeltaNedas** [comment]
why do you think poor anuke made the template

**Comment by XxsuperdeadlysniperxX** [comment]
What template dude?

**Comment by Sky4ce09** [comment]
> What template dude?

the issue template, of course
it should give you a good example of what requirements your issues must meet

**Comment by XxsuperdeadlysniperxX** [comment]
So should i not replace the templet words then?
