### ISSUE TITLE
Sounds don't work

### ISSUE THREAD

**Issue by Yarjk32** [Anuken/Mindustry#3907]
Platform: *Android*

Device: Meizu M3s; Android 5.1 (Flyme 6.3.2.0G)

Build: *121.2 from Google Play and BE 20287 from [here](https://github.com/Anuken/MindustryBuilds/releases).*

Issue: *When I launched Mindustry, sounds and music wasn't working. I tried 12 times and only the 4th launch was successful. I checked settings in game and in my phone, but all sounds were 100%. Also, I rebooted the phone and reinstalled the game, but it hadn't helped.*
*But, my friend doesn't complain about it.*

Steps to reproduce: *Launch the app*

Link(s) to mod(s) used: *Nothing*

Save file: [data.zip](https://github.com/Anuken/Mindustry/files/5673963/data.zip)

###### If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

(~Crash~) logs: [log.txt](https://github.com/Anuken/Mindustry/files/5673967/log.txt)

##### *Either crash reports from the crash folder or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Logs don't have any relevant information, and sound works correctly on my phone/emulator/test devices. Won't fix.

**Comment by FlamingArr** [comment]
This issue is present on one of my devices too, it happens if the media volume is not at 100% during mindustry launch.
*I think* it is an old android bug.
