### ISSUE TITLE
Random Serialization Exception On Startup

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#3909]
**Platform**: Windows

**Build**: 121.1 (Has been happening with each build for months at this point)

**Issue**: Every time I start my game (whether it be on steam or through a file from github) this same exception is logged, it doesn't crash the game but its pretty annoying.

**Steps to reproduce**: I open the game

**Save file**: This happens before the menu even loads

**(Crash) logs**: Well there's no crash but this is logged to the console ![](https://xenon.is-ne.at/UlJd3l.png) (RTFM is disabled)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not important.

**Comment by DeltaNedas** [comment]
it means some map you have references missing content

**Comment by buthed010203** [comment]
> it means some map you have references missing content

Come to think of it, that makes a lot of sense considering I have a bunch of old maps one of which is from a mod
