### ISSUE TITLE
lunchpad doesnt work

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3911]
**Platform**: Android 9

**Build**: 20210 h

**Issue**:
Massive lunchpad relay sector not giving any passive resources to its target sector.

**Steps to reproduce**:
1. Wait in relay sector for a few minutes
2. Visit target, resources have gone up.
3. Wait there and receive nothing

**Link(s) to mod(s) used**: deltanedas/routorio

**Save file**: [sector-serpulo-10.msav.txt](https://github.com/Anuken/Mindustry/files/5674939/sector-serpulo-10.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> relay sector 

Unless it has active production, launching will not work passively.

**Comment by DeltaNedas** [comment]
oh god oh fuck

**Comment by Anuken** [comment]
(and even if I wanted to debug this, I can't, because I don't have your campaign saves)

**Comment by DeltaNedas** [comment]
honestly its a good change but there should be a way to coordinate lunchpads across an entire planet besides going in to every one

**Comment by RogueRedHawk** [comment]
@DeltaNedas #suggestions
