### ISSUE TITLE
Launchpad continues launching resources even after belts no longer supply it AND even after it is deleted entirely

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [Anuken/Mindustry#3913]
**Platform**: Windows

**Build**: 6.0 Build 121.2

**Issue**: 
After launching some thorium from sector 85 to sector 146,  The latter produces no thorium.  I stopped belting thorium to the launchpad, but it continued to be received by the target sector (several hundred).  I tried deleting the launchpad entirely, but that still didn't work - thorium continued to be received by the target.  (I am uncertain as to whether it continues taking thorium from the source, but the target definitely continues to receive it.)

**Steps to reproduce**:

I created a launchpad at sector 85.
I powered it and belted thorium to it.
I targeted it at sector 146 that does not product thorium.
I confirmed that the target sector received thorium and built some stuff that requires thorium.
I stopped belting resources to the launchpad.  Target sector continues to receive thorium.
I really wanted the thorium to stop, so I deleted the launchpad entirely.  Target sector STILL continues to receive thorium.

From the attached save file, if you enter sector 146 and wait less than a minute, it will gain thorium.  If you wait another minute or two, it will gain more thorium.  It does not produce thorium, and no zone has a launch pad targeting it.  Sector 85 previously had a launchpad, but that launchpad no longer exists.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[LaunchPadNeverStops.zip](https://github.com/Anuken/Mindustry/files/5675189/LaunchPadNeverStops.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Exports are averaged over about a minute. Deleting a launch pad and immediately leaving will not stop export.

**Comment by swenkeratmicrosoft** [comment]
@Anuken 
I'm still receiving thorium.  It's been an HOUR.

**Comment by swenkeratmicrosoft** [comment]
Or do you mean that I have to stay at the source planet for a minute or two?

**Comment by Anuken** [comment]
Yes, the simulation collects data *on the source sector*.

**Comment by swenkeratmicrosoft** [comment]
Confirmed.  Thanks for the info!
