### ISSUE TITLE
No compiled .jar files for the 121.2 release on GitHub

### ISSUE THREAD

**Issue by Tynach** [Anuken/Mindustry#3914]
**Platform**: Desktop/Java

**Build**: 121.2

**Issue**: There is no Mindustry.jar, nor server-release.jar, for the 121.2 release on Github.

**Steps to reproduce**: Attempt to download the .jar file for the most recent release.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** I literally can't, so I had to use itch.io and extract the package :P
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DarkBrick** [comment]
![image](https://user-images.githubusercontent.com/63005558/101830522-ed451d80-3b34-11eb-9583-37aba0ed62ab.png)

**Comment by DeltaNedas** [comment]
?

**Comment by DarkBrick** [comment]
He fixed it, neat
