### ISSUE TITLE
UI pixel gaps

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#3915]
**Platform**: iOS 14.2 (iPhone 11 Pro Max)

**Build**: 6.121.0

**Issue**: Gaps in some UI elements when UI scale is set to >100%.
![2020-12-10 15 11 52](https://user-images.githubusercontent.com/13720625/101830573-53f91580-3afa-11eb-9720-a0d286fa277b.jpg)

**Steps to reproduce**: Set UI to 150%, relaunch, load a game, observe the upper left UI window.

**Link(s) to mod(s) used**: N/A

**Save file**: [mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5675634/mindustry-data-export.zip)

**(Crash) logs**: N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Related issue:
https://github.com/Anuken/Mindustry/issues/2465

**Comment by Anuken** [comment]
This happens randomly depending on UI scale and device; there's no solution.

**Comment by DeltaNedas** [comment]
your Core.graphics.width/height are weird
if you werent on ios you could use a mod to manually correct the gaps

**Comment by willis936** [comment]
iOS has mod support.  I saw your fix (https://github.com/Anuken/Mindustry/issues/2465#issuecomment-683431618) to a similar issue, but decided to make an issue since the symptom wasn't identical and there have been changes since your issue.

**Comment by Anuken** [comment]
iOS doesn't support *scripts*, so that wouldn't work. Any fix that changes padding between elements just leads to gaps on other devices.

**Comment by willis936** [comment]
I packaged the script-based fix (https://github.com/Anuken/Mindustry/issues/2465#issuecomment-683431618).  Sure enough, it doesn’t run on iOS.  The mod gives this error “Not compatible with V6 (no minGameVersion: 105)”.  Here is an importable zip (mod) of the script for future searchers.

[ui-fix.zip](https://github.com/Anuken/Mindustry/files/5676547/ui-fix.zip)
