### ISSUE TITLE
Weather effects obscure schematics

### ISSUE THREAD

**Issue by limb-trimmer** [Anuken/Mindustry#3916]
**Platform**: Mac & Windows confirmed.  Probably all platforms.

**Build**: 121

**Issue**:  Weather effects even obscure schematics, which are part of the UI.  

**Steps to reproduce**: Have weather effects on screen.  Try to build from a schematic.  Sandstorms are especially annoying.

**Link(s) to mod(s) used**: N/A

**Save file**: I'm using Steam to manage all this.  The internet seems to think you need the attached file.
[sector-serpulo-23.zip](https://github.com/Anuken/Mindustry/files/5676710/sector-serpulo-23.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**  Steam obscures this.
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> which are part of the UI.

They are not.
