### ISSUE TITLE
procedurally generated sectors can have ground enemy spawn points in deep water, killing all or most of them

### ISSUE THREAD

**Issue by uDMBK** [Anuken/Mindustry#3918]
**Platform**: *Windows*

**Build**: *steam build 121.2*

**Issue**: *sectors produced by procedural generation can have the enemy spawn point in deep water, resulting in most or all ground-based enemies dying each wave .*

**Steps to reproduce**: *not really applicable; based purely upon the procedural generation system.*

**Link(s) to mod(s) used**: *none*

**Save file**: *[mindustrysave.zip](https://github.com/Anuken/Mindustry/files/5677213/mindustrysave.zip) issue can be found on sector 220.*

**(Crash) logs**: *issue does not result in a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
Why not... tell us WHICH sector is doing this?

**Comment by Anuken** [comment]
Known and already fixed.
