### ISSUE TITLE
Sudden Draw.draw crash

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3919]
**Platform**: *Windows*

**Build**: *Steam 121.2*

**Issue**: *The code below, in a "Draw Tester"(which eval()s the text within its own draw()) crashes the game with NO CRASH LOGS. No crash files dating to Dec.11, the export logs says that there is none, and last_log.txt is empty(it just says saved on exit), and also the game just closes, as if you did a Core.app.exit(), with no crash popup or anything. However, removing the commented out code(the try{}catch in the Draw.draw) makes everything run fine, with no errors reported in F8, which means that in theory the error is never catch()ed, which should mean that I don't need the try{}catch, but the game grashes without it.*

**Steps to reproduce**: 
```
var time = Time.time % 300;
var progress = time / 300;

var heat = 1.1;
Draw.color(Pal.darkMetal);
Lines.stroke(2 * heat);
Fill.poly(this.x, this.y, 4, 10 * heat);
Draw.reset();
var region = UnitTypes.dagger.icon(Cicon.full);
var from = UnitTypes.alpha.icon(Cicon.full);

Draw.color(0, 0, 0, 0.4 * progress);
Draw.rect("circle-shadow", this.x, this.y, region.width / 3, region.width / 3);
Draw.color();
Draw.draw(Layer.blockOver, () => {
//try{ <- THE COMMENTED LINES MENTIONED EARLIER STARTS HERE
  Drawf.construct(this.x, this.y, region, 0, progress, 1, time);
  Lines.stroke(2 * heat, Pal.accentBack);
  var pos = Mathf.sin(time, 6, 8);
  Lines.lineAngleCenter(this.x + pos, this.y, 90, 16 - Math.abs(pos) * 2);
  Draw.color();
//}
//catch(err){
//  print(err);
//}
});

Lines.stroke(2 * heat);

Draw.color(Pal.accentBack);
Lines.poly(this.x, this.y, 4, 8 * heat);
Draw.reset();
```

**Link(s) to mod(s) used**: *sk7725/tester for the draw tester.*

**Save file**: *Insta-crash, graphics is the h here*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *REQUIRED if you are reporting a crash. THERE IS NONE, FOR SOME REASON.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
I .... found the crash...log? It was on the steam mindustry directory(normally, crash logs go to the itch.io directory), and it looks....weird. The time matches, so it must be that crash log, but....this is really weird.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc1bf74da2, pid=12780, tid=12228
#
# JRE version: OpenJDK Runtime Environment (8.0_72-b15) (build 1.8.0_72-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.72-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [MSCTF.dll+0x64da2]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by sk7725** [comment]
This is my first time encountering this situation, but there are more log files that were created throughout yesterday(according to my computer) with the same content, for some reason. The logs dating todays are simultaneous to the crashes I got to Draw.draw, though.

**Comment by Anuken** [comment]
How should I reproduce this? It's not code that I can simply paste into the console. I can't use your mod, because there's quite a lot of code and you haven't specified where exactly I should put what you posted. When I run the code you posted *in the main loop* on a keypress with a custom mod created for the purpose, I get this log:

> Can't find method arc.graphics.g2d.Fill.poly(rhino.Undefined,rhino.Undefined,number,number). (main.js#10)

Since you *already had a functional mod* when this problem occurred, why not send me the zipped version of that mod with instructions on how to reproduce this issue instead of sending me a random snippet of code that I have to insert into my own mod?
