### ISSUE TITLE
Mindustry does not crash AT ALL

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#3922]
**Platform**: *Windows*

**Build**: *Steam 121.2*

**Issue**: *When encountered with an issue what would normally make mindustry crash with an "oh no" popup window and crash log txt file now just closes mindustry, as if you ran Core.app.exit(). This is a serious problem because you cannot fix stuff if you have no idea what is wrong. Crash logs are empty, export logs is also empty(no crashes found), and last_log.txt is also void of errors.*
This is likely the actual description of what happened in #3919, but worse. I'm leaving #3919 open because Draw.draw is weird anyways.

**Steps to reproduce**: 
```
configTapped(){
      bbebeb;
        if(!this.consValid() || !this.inRange(Vars.player)) return false;
        this.configure(null);
        Sounds.click.at(this);
        return false;
    },
```
This should crash because bbebeb is not defined.
Also there is one more example in #3919.

**Link(s) to mod(s) used**: *unrelated, tested in multiple mods that to deliberately cause crashes.*

**Save file**: *unrelated.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *PLEASE GIVE ME ONE I AM BEGGING YOU PLEASE*
I found something weird in the Steam's directory instead: `hs_err_pid13952.log`
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc1bf74da2, pid=13952, tid=3244
#
# JRE version: OpenJDK Runtime Environment (8.0_72-b15) (build 1.8.0_72-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.72-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [MSCTF.dll+0x64da2]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
i believe this is a return of the good ol 'not creating crash report for ui thread errors' bug

**Comment by sk7725** [comment]
> i believe this is a return of the good ol 'not creating crash report for ui thread errors' bug

But the process thread, graphic thread and ui thread all refuse to give me the logs, and just 2 days before it did log the crashes...

**Comment by Anuken** [comment]
```js
configTapped(){
      bbebeb;
        if(!this.consValid() || !this.inRange(Vars.player)) return false;
        this.configure(null);
        Sounds.click.at(this);
        return false;
    },
```

...is not runnable code, I can't test this. See https://github.com/Anuken/Mindustry/issues/3919#issuecomment-743262194

**Comment by BlueWolf3682** [comment]
that fatal error resembles the ones i encountered when mindustry unexpectedly crashed without a log on school laptops

**Comment by BlueWolf3682** [comment]
@Anuken somethings still wrong here and we all should really figure out what it is, as i found this issue reproducable

**Comment by DeltaNedas** [comment]
ok make a minimal mod that crashes without a log

**Comment by Anuken** [comment]
> somethings still wrong here and we all should really figure out what it is, as i found this issue reproducable

Then give me something I can reproduce it with.

**Comment by BlueWolf3682** [comment]
i do not know the exact circumstances, as it was almost random, but i was playing with K103908/Exotic-Mod and it would randomly crash with a fatal error instead of a log. it did this three times, and i even dmed anuke one of the logs to ask whats going on

**Comment by BlueWolf3682** [comment]
probably the best method to reproduce is just to crash the game

**Comment by Anuken** [comment]
> probably the best method to reproduce is just to crash the game

That's equivalent to saying "the best method to reproduce it is to reproduce it".

> i even dmed anuke one of the logs to ask whats going on

The logs were internal JVM errors, nothing I can fix.

**Comment by BlueWolf3682** [comment]
well we found out these fatal errors by crashing the game, so its only logical that you should try crashing the game too

**Comment by Anuken** [comment]
> you should try crashing the game too

*And there are no clear steps to do so.* Considering the code shown in the linked issue does not crash me, I don't see why playing that mod would either. I will only attempt it if I see usable mod code that **consistently** crashes someone's game without a log.

**Comment by sk7725** [comment]
@Anuken 
F8
```
Events.run(Trigger.update, () => {
aaaaaaaaa;
});```

**Comment by sk7725** [comment]
I am thinking that its the updated steam client that is somehow working againdt crash logging & alerting. That code above should crash.

**Comment by sk7725** [comment]
same as in #3919, it shouldve crashed with a crash log(which should have told me about the Fill), but it just exited.

**Comment by Anuken** [comment]
Compiled from source:

![image](https://user-images.githubusercontent.com/10100000/101925172-9294db80-3b9f-11eb-9237-0ca171ff3a11.png)

Steam (Linux):

![image](https://user-images.githubusercontent.com/10100000/101925351-c2dc7a00-3b9f-11eb-90cc-95b74cdc4647.png)

Steam (Windows VM):

![image](https://user-images.githubusercontent.com/10100000/101925692-2797d480-3ba0-11eb-8781-b083110432ea.png)

**Comment by sk7725** [comment]
what the -
I will record my entire screen tomorrow for proof(sorry, its 1 am and i am on my phone), and besides, why would I lie about this?

**Comment by sk7725** [comment]
I can tell you the things I know:
1. It crashed fine in steam 121(remember my hint issue?), but this is happens in steam 121.2
2. My steam client also updated during that timespan.
So it is unclear which of these two did it, but it must be one of these two.

**Comment by Anuken** [comment]
It's probably something to do with your Steam client, then.

**Comment by sk7725** [comment]
Got it, I'll PM the log tomorrow(= 6 hours later)

**Comment by Anuken** [comment]
(Just double checked, and I'm running the latest Steam client + 121.2 on my VM, and it still crashes properly)

**Comment by sk7725** [comment]
![image](https://user-images.githubusercontent.com/58885089/101960726-56b75000-3c4b-11eb-9cf7-c7acb6c810b9.png)
Um what? What should I do?

**Comment by sk7725** [comment]
Some more info: "Enable steam overlay" and "turn on VR something" in the steam's properties does not affect this, I tried turning those options off. Steam also says my game file state is a-ok, nothing damaged.

**Comment by sk7725** [comment]
Crash crashes normally in BE 20210.

**Comment by sk7725** [comment]
> It's probably something to do with your Steam client, then.

Wrong, just tested on itch.io release 121.2, it still is reproduced there.

**Comment by sk7725** [comment]
I found out the exact version: 121.1
release 121 works fine(jar from github), but 121.1 and 121.2 does not.

**Comment by sk7725** [comment]
@Anuken , now since I found out that it wasn't my client going brrrr, can I reopen this issue?
