### ISSUE TITLE
`control shootp` doesnt change turret direction

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3923]
**Platform**: Android 9

**Build**: 10288

**Issue**:
spectres are being told to shoot at MechUnit#<number> but dont actually turn towards it.
![a](https://user-images.githubusercontent.com/39013340/101906663-3c309880-3bb1-11eb-810a-c02163549579.jpg)

**Steps to reproduce**:
1. link foreshadow and some spectres to a processor with code below
2. spawn enemies
3. spectres shoot **but dont turn towards the enemy** (also happens when shootp'ing the player)

**Code**:
```
radar enemy any any distance foreshadow1 1 enemy
set i 1
getlink turret i
control shootp turret enemy enemy
op add i i 1
jump 2 lessThan i @links
``

**Save file**: github no upload msav :(

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
> github no upload msav :(

zip it 🤐

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/101919531-af79e080-3b98-11eb-8787-572a30be7bd2.png)

No problems testing this locally.

> github no upload msav

You known perfectly well how to send a save here.

**Comment by DeltaNedas** [comment]
> > github no upload msav :(
> 
> zip it

`mv h.msav{,.txt}` is better as theres basically no i/o needed

**Comment by DeltaNedas** [comment]
@Anuken addendum
**Save file**: [228.msav.txt](https://github.com/Anuken/Mindustry/files/5679948/228.msav.txt)

**Comment by Anuken** [comment]
Unmodded? If it's not vanilla, I can't test it.

**Comment by DeltaNedas** [comment]
has routorio and anuke-logic maybe

**Comment by DeltaNedas** [comment]
i assure you i would never break logic like that

**Comment by Anuken** [comment]
Remove your mods, test it without them.

**Comment by DeltaNedas** [comment]
ok anuke

**Comment by DeltaNedas** [comment]
ok it appears that one of my ~30 mods did it or it was just a fluke

**Comment by claw4oo** [comment]
Issue has appeared in steam build 122.1



**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Steam build 122.1

**Issue**: 
Using logic control shootp does not work in singleplayer unless an enemy of some type is in range of the turret
In multiplayer, it partially works. 

Turret shoots at where it was last aiming at, and then the enemy takes damage/dies, despite the turret shooting in a different direction.

Attempting to use targetp to shoot yourself/allies will not work unless it's already in range of an enemy.

I shared this information with other people in the #logic discord to confirm, and they said it wasn't working as intended/to report it.

**Steps to reproduce**: 
Code used, also in save file.

radar ally any any distance duo1 1 result
control shootp duo1 result result 0 0
sensor x result @x
sensor y result @y
print x
print ","
print y
print "\n"
print result
printflush message1

**Link(s) to mod(s) used**: N/A

**Save file**: 
[logicTargetPBug.zip](https://github.com/Anuken/Mindustry/files/5762463/logicTargetPBug.zip)


If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
(I just searched and here it is actually, copy pasted from a new issue)
