### ISSUE TITLE
If the core adds a warehouse, the capacity will be problematic

### ISSUE THREAD

**Issue by Harriser** [Anuken/Mindustry#3924]
Platform: Windows

Build: Steam 121.2

Issue: 
    If the core adds warehouse, the capacity will have problems.
    Multiple warehouse and Multiple core, After stacking, there is a problem with the quantity.

Steps to reproduce: Create multiple cores and warehouses.

Save file: unrelated.

![Mindustry_201211_1607694541f](https://user-images.githubusercontent.com/13331604/101911049-cd782d00-3bfa-11eb-837a-5089a5c46ee2.jpg)

![Mindustry_201211_1607694550p](https://user-images.githubusercontent.com/13331604/101911062-d10bb400-3bfa-11eb-94ce-36fd81c55e62.jpg)

**Comment by Quezler** [comment]
> "LATEST" IS NOT A VERSIPlatform:

**Comment by Harriser** [comment]
> > "LATEST" IS NOT A VERSIPlatform:

Sorry, edit error, The modified.
This quertion for windows.

**Comment by Anuken** [comment]
> Save file: unrelated.

No.
