### ISSUE TITLE
Unexpected shutdown puts campaign data in an awkward state

### ISSUE THREAD

**Issue by StellarGamez** [Anuken/Mindustry#3935]
**Platform**: Windows

**Build**: steam build 121.2

**Issue**: Power went out, and my computer immediately shut off. Later, after I started the game I was greeted by every single one of my sectors under attack and my research tree reset. All of the structures and units in each sector were still there though.

**Steps to reproduce**: Load into a sector, then unplug your computer

**Link(s) to mod(s) used**: None

**Save file**: I'll attach my saves directory in a .zip here:
[saves.zip](https://github.com/Anuken/Mindustry/files/5682626/saves.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
if youre on an ssd a power cut can even kill your drive, what else do you expect
go buy one of those server emergency capacitor things that let you cleanly shut down when losing power

**Comment by joshuaptfan** [comment]
@DeltaNedas That's true, but regardless, every game's auto-save system should be robust enough to handle unexpected termination due to Alt+F4, crash, power loss, etc., perhaps by keeping the previous auto-save around and falling back to it if the latest one is corrupted.

**Comment by Anuken** [comment]
Your game data was corrupted. There already is a backup system, but for whatever reason it didn't trigger.
