### ISSUE TITLE
CPU can't compare "string" values

### ISSUE THREAD

**Issue by gmnenad** [Anuken/Mindustry#3937]
When obtaining string value from objects with sensor command ( like 'type' ), it is not possible to compare that string value to normal string, even if it can be printed out.

*For example:
getlink a 0 // this get whatever is first link (in my case it was 'vault1')
sensor aType a @type // this put type of that in variable aType ( in my case, that was 'vault' )
print aType // this correctly print out "vault" ( without parentheses )
op equal cmpType aType "vault" // this should have put 1 in cmpType but it does NOT !
print " eq: "
print cmpType // this prints 0 instead of expected 1
printflush message1

*On the other hand, setting string literal directly to variable works for comparison:
set b "vault" // set variable directly to string literal, instead of reading with sensor
op equal cmpB b "vault" // comparint that variable to same literal now works
print cmpB // this prints '1' as expected

Some additional informations:

JUMP command is also not able to compare aType to string literal "vault" ( same error as op equal)
string addition (op add ) does not work either - adding two strings result in number 2 , so I would guess that game treat each string as integer value 1
sensor reading 'name' property of links does not work from some reason ( empty result, I would have expected 'vault1' in above example)
My guess is that using sensor to obtain string property of some object ( like type or name) does not in fact return string but some complex type - and game did not overload that type to compare to strings.

**Comment by DeltaNedas** [comment]
you are correct
processors do compare strings, but they don't call Object#toString or anything

**Comment by gmnenad** [comment]
Using Object#toString for any object when compared to string would be nice, but if not already implemented it could be considered more of a feature request than a bug.

Bug in this case is not treating string fields (read by 'sensor' command) as strings. For example, "sensor res someVault @type " command  should return string 'vault' into variable res - and that variable res should be of type <string> and comparable to literal string "vault".

**Comment by Anuken** [comment]
` @type` does not return strings. This issue is a duplicate.

**Comment by gmnenad** [comment]
I already suspected that @type does not contain string, as mentioned in my post.

But I'm obviously not only one to consider that as a bug - if we are not able to compare type of an object to predefined string value, what is the use case of having @type in the first place?
