### ISSUE TITLE
Building with poly without the needed resources

### ISSUE THREAD

**Issue by Canardou** [Anuken/Mindustry#3942]
**Platform**: Android

**Build**: release build 121.2

**Issue**: Cancelling a building without enough resources while being help by polys and then starting to build it again (using pause) will finish it even if you don't have enough resources.

**Steps to reproduce**: Start a building without the needed resources, polys come to help. Cancel the building, then immediately pause, cancel the current action and tap again on the building to build. Unpause and the building finish immediately.

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Your soul. Hand it over.
