### ISSUE TITLE
When playing multiplayer campaign, client-side research doesn't use resources

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#3944]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.2

**Issue**: *Explain your issue in detail.*

If you are playing multiplayer campaign with another player, when you research something, it spends the resources, but exiting and reopening the menu will show that the resources were never spent, but research progress is made

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Host a multiplayer campaign game on a device, connect to the game with another device, and research something. It will show resources being spent, and progress being made, but reopening the menu will restore the resources, but not revert the progress

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[savefile.zip](https://github.com/Anuken/Mindustry/files/5683586/savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is known and fixed.
