### ISSUE TITLE
Bug launch pads on vanilla campaing

### ISSUE THREAD

**Issue by M-TTI** [Anuken/Mindustry#3945]
**Platform**: Windows

**Build**: 121.2

**Issue**: Issues with launch pads in campaign vanilla : i've got 20+ sectors which are producing a lot of all ressources (exemple : in desolate rift, i've made 4 silicon crucibles which are perfectly working and with each one a launch pad.) but they're not working well when i use it. it doesnt display the 'export' section when i go to stats.

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
soul reaping time 🔪

**Comment by DeltaNedas** [comment]
where did template go

**Comment by z0mbiesrock** [comment]
> where did template go

to brazil

**Comment by nichrosia** [comment]
Also, a save file is kinda required for this issue, as we have no idea what the problem is without it.

**Comment by M-TTI** [comment]
> 
> 
> Also, a save file is kinda required for this issue, as we have no idea what the problem is without it.

but where are the campaign files ?

**Comment by nichrosia** [comment]
Settings -> Game Data -> Export Data, then save the file, and then upload it here

**Comment by nichrosia** [comment]
to upload just drag the file onto the comment box

**Comment by M-TTI** [comment]
yeah ik but idk where the campaign saves are

**Comment by nichrosia** [comment]
They are wherever you saved them

**Comment by M-TTI** [comment]
found it but it doesnt support .msav

**Comment by nichrosia** [comment]
What?

**Comment by nichrosia** [comment]
.msav is a map file, the save file is a .zip

**Comment by nichrosia** [comment]
![first](https://user-images.githubusercontent.com/57579569/101994486-61440a80-3c88-11eb-9bba-50e47202745e.png)
![middle](https://user-images.githubusercontent.com/57579569/101994488-63a66480-3c88-11eb-915f-913af95c0a87.png)
![final](https://user-images.githubusercontent.com/57579569/101994489-65702800-3c88-11eb-81ea-3675c81a057c.png)
