### ISSUE TITLE
The resource count does not get updated in realtime on the research tree screen.

### ISSUE THREAD

**Issue by noncom** [Anuken/Mindustry#3946]
**Platform**: Windows

**Build**: Steam build 121.2

**Issue**: The resource count table does not get updated on the research screen. It literally freezes with the amount of resources that was effective at the moment of entering the screen. Similarly, the tooltips on particular researches keep thinking that these amounts are still ever effective.

So for example if you have 1.5k silicon when entering the screen and spend it all on something, the count is going to drop to 0 and never change, forcing you to exit and enter the research screen again to take into account the amount that might have accumulated in the seconds since the last research. You must do this each time to make the system update the effective amount of stored resources.

It would have been very nice if these values were updated in realtime.

Though this issue seems so obvious, I did not find any mention of an existing case among the closed ones.

**Steps to reproduce**: Play the game, open the research tree screen, observe the behavior

**Link(s) to mod(s) used**: None

**Save file**: not related

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by noncom** [comment]
(facepalm) 

The game pauses in singleplayer...

**Comment by rodrigolitzius** [comment]
H.
