### ISSUE TITLE
Moving units have terrible aim

### ISSUE THREAD

**Issue by Auswaschbar** [Anuken/Mindustry#3949]
**Platform**: *Linux

**Build**: *121.2

**Issue**: Moving units can't aim sideways and constantly shoot off the mark, in the opposite of the direction they are walking. It is most noticable in units with longer range, like daggers, but all units that can shoot bullets sideways are affected by it.

**Steps to reproduce**: Simply start a new game in survival mode, and build any smaller building next to where the units walk.

**Link(s) to mod(s) used**: No mods where used

**Save file**: 
[bug.msav.zip](https://github.com/Anuken/Mindustry/files/5683712/bug.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
This would require completely reworking the unit AI. For one, this would be a major addition to 6.0, two, Anuke has said to a Discord message that said "***smart ai when***", replying, "never"
