### ISSUE TITLE
No audio bug

### ISSUE THREAD

**Issue by TrueBlueFlare** [Anuken/Mindustry#3954]
Android

121.2

A majority of the time upon loading the game, there is no sound. I checked my devices volume and my in game sound settings, both were on and still, nothing.

Not really anything, just opening the game. Occasionally this doesn't happen though, but I'm not sure what causes it.

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't happen on any of my devices, won't fix.

**Comment by GaiaB0t** [comment]
happens to me, on an older fire tablet that has google play(I got this from google play)
