### ISSUE TITLE
Naval AI is indecisive on which way to go in map with multiple Red and Blue enemy cores.

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#3961]
**Platform**: Windows

**Build**: steam build 121.2

**Issue**: The Omura AI (which is on the player's team) is indecisive and switches between going left and right in this map with many cores including Red and Blue ones.

![20201213124906_1](https://user-images.githubusercontent.com/75215867/102010978-c0b22100-3d41-11eb-93ec-f975ca8a7f88.jpg)

**Steps to reproduce**: Load the save file and observe the Omura.

**Link(s) to mod(s) used**: No mods

**Save file**:  [265.zip](https://github.com/Anuken/Mindustry/files/5684527/265.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
possibly related to #3825

**Comment by Anuken** [comment]
Won't fix, see issue above.
