### ISSUE TITLE
CPU can't add two strings

### ISSUE THREAD

**Issue by gmnenad** [Anuken/Mindustry#3963]
Adding two strings result in number 2.

I guess that any non-numeric value is treated in operations as 1 if it has value (exists/true) or treated as 0 if it does not have value (null/false).

While "aaa"+"bbb"=2 can be considered as a bug, adding two literal strings could be avoided in many cases. What could be more useful is adding numbers and/or other types with strings - with automatic cast to string result.  For example:  if operation is addition and one of the operands is literal string, call #toString of the other operand. Or even better: if operations is addition and any of the operands is not a number, call #toString on both operands.

That would allow us to:
- only once calculate string message and store it in single variable for later use, eg:  sX= shootX floor, sY=shootY floor, msgXY= sX + ", ", msgXY=msgXY+sY ... and later just use print msgXY, without need to remember shootX/Y variables
- compare complex AND conditions with one jump, eg:  tmp= @link + @type ), jump if tmp=="2vault" would be single jump to compare if cpu has vault as second link. Or in previous example, jump if msgXY=="10,20" is single comparison to test both X and Y coordinate
- use operations as workaround way if we want to compare @values to literal string, eg: tmp= @value + "",  jump if tmp=="value" ... would be dynamic version of static if @value==@vault

**Comment by Ruichka** [comment]
1. This is wrong repository, suggestions go [here](https://github.com/Anuken/Mindustry-Suggestions)
2. This will not be added, use DeltaNedas/anuke-logic if you want string ops

**Comment by Anuken** [comment]
String operations are not supported, and will never be supported. Operators are for numbers only.
