### ISSUE TITLE
Pressing Undo in the Editor after deleting blocks does not restore the configuration

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#3965]
**Platform**: Windows

**Build**: steam build 121.2

**Issue**: When you delete something and then you press the "Undo" icon, it does not restore the configuration of blocks.
This includes:
- Power connections
- Bridge connections
- Mass Driver connections
- The selected Item/Liquid Source
- The selected Sorter Configuration
- The selected Unloader resource
- The selected Unit type in the Factories
- Processor instructions
- Processor links

Before Deleting +Undo:
![20201213182413_1](https://user-images.githubusercontent.com/75215867/102018933-b6f3e200-3d70-11eb-8219-960680c4e2db.jpg)

After Deleting + Undo;
![20201213182531_1](https://user-images.githubusercontent.com/75215867/102018937-beb38680-3d70-11eb-8377-59fdb2840b85.jpg)

**Steps to reproduce**:
1) Open the following map in the editor (It is named "test")
[map_60_UndoBug.zip](https://github.com/Anuken/Mindustry/files/5685044/map_60_UndoBug.zip)
2) Go to "Edit In-Game" and observe the configuration of the blocks. Note that the mass driver are connected, that the factories have a unit type selected, and that the processors have code and a link.
3) Return to the editor (Escape => Quit)
3) Select the "Eraser" tool
4) Set the size to maximum
5) Delete all the blocks with 1 mouse click
6) Press the "Undo" button so the blocks come back
7) Go back to "Edit In-Game" and observe that all the configurations have been reset to the default.

**Link(s) to mod(s) used**: None

**Save file**:  See the .zip in "Steps to reproduce"

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.
