### ISSUE TITLE
Bridge conveyors

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#3966]
**Platform**: *Android and other platforms too*

**Build**: *20303.*

**Issue**: *[this.](https://1drv.ms/v/s!AnYf7oxSZjN8gUEU7O5ZlArVI7Zx)*

**Steps to reproduce**: *h.*

**Link(s) to mod(s) used**: *h.*

**Save file**: *i don't think that's required, because you can reproduce on any map easily.*

**(Crash) logs**: *h.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
"bridge doesn't link in the way it gets shown during planning if it gets build in reverse due to distance or other causes"

**Comment by rodrigolitzius** [comment]
That means what?
