### ISSUE TITLE
Inconsistent damage on units under effects.

### ISSUE THREAD

**Issue by NeviNovat** [Anuken/Mindustry#3968]
**Platform**: Windows 10

**Build**: release build 121

**Issue**: Units that are tared/oiled then hit with slag receive extra damage, that is to be expected. But the order matters, for example a unit that is first slag-ed then hit with tar won't receive extra damage but will keep burning. And if a unit steps on slag then on tar/oil nothing happens, its as if they where still on slag, but if they step on tar/oil then slag they get extra damage and if then they get back on tar/oil they receive even more damage making their life drain even faster they it already was.
This applies even with the tsunami turret where if a unit is hit by slag then tar/oil they won't receive extra damage but if they get hit by tar/oil then slag they do receive extra damage.

**Steps to reproduce**: 
There are 2 cases where this can be seen:
1. When a unit steps on tar or slag in a specific order without touching normal unaffected gorund
- the unit first steps on slag then tar/oil they don't receive any extra damage and die at the same rate as if they where to stand on slag only,
- the unit first steps on tar/oil and waits for the effect to take place then it steps on slag, by doing so it will die faster then normal but if it goes and steps on tar/oil again after it steps on slag it will start to receive even more damage then normal making it die very fast. ( This example might produce extra particles that are seen better in the test with the air unit! )
![image](https://user-images.githubusercontent.com/51816321/102022992-211d7e80-3d93-11eb-90c1-e50509b08915.png)
This is the set-up its included in the .zip
2. When a air unit gets hit by slag then oil it will not receive extra damage, but if you first hit it with oil then slag it will receive extra damage.
![image](https://user-images.githubusercontent.com/51816321/102023056-82dde880-3d93-11eb-9f25-de09fcb5f097.png)
See that the **slag** tsunami is closer so it hits first then the oil one, this set-up needs **4** foreshadow shots to kill the unit
![image](https://user-images.githubusercontent.com/51816321/102023117-ef58e780-3d93-11eb-91af-1f754a574c4a.png)
See that the **oil** tsunami is closer so it hits first, this set-up needs **3** foreshadow shots to kill the unit
**Please observe the extra particles that are round the unit! They do not appear in the first slag then oil test!**
![image](https://user-images.githubusercontent.com/51816321/102023087-b91b6800-3d93-11eb-9fab-38c3589f5599.png)
This is the control test it take **4** foreshadow shots to kill the unit that is only hit by slag, _same as when it got hit by slag then oil_ .

**Save file**: 
All 3 situations are here:
[All-3-situations.zip](https://github.com/Anuken/Mindustry/files/5685365/All-3-situations.zip)

**Extra**:
- There are also some small thing that I observe like the lack of slowdown when in tar if the unit is on fire this might be a limitation of how the game uses and assigns effects but I think its still worth mentioning here.
- The effort and risk for placing oil and slag wave/tsunami turrets in your defense is big, I think that the intended behavior is to add more damage if a unit is hit by slag and oil no matter the order they are hit in.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> There are also some small thing that I observe like the lack of slowdown when in tar if the unit is on fire this might be a limitation of how the game uses and assigns effects but I think its still worth mentioning here.

How can a unit be slowed down by oil if the oil is burning on contact with the unit?

**Comment by NeviNovat** [comment]
> 
> 
> > There are also some small thing that I observe like the lack of slowdown when in tar if the unit is on fire this might be a limitation of how the game uses and assigns effects but I think its still worth mentioning here.
> 
> How can a unit be slowed down by oil if the oil is burning on contact with the unit?

That's a good point, it won't have time to spread on the unit if it contributes to the fire, I am removing that now since it seams to be working as intended
