### ISSUE TITLE
units that can boost under command will glitch out when landing on wall

### ISSUE THREAD

**Issue by notrealn** [Anuken/Mindustry#3969]
**Platform**: *Android/iOS/Mac/Windows/Linux*

i use epic linucks

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 

121.2

**Issue**: *Explain your issue in detail.*

the quasar (pretty sure it works with anything that can boost) starts trying to land on the wall and teleporting up. looks pretty wacky.
[video](https://drive.google.com/file/d/14EgczfYhK2jLiFnK97IRamlFk6UiKoba/view?usp=sharing)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. take control of many quasar
2. press G
3. fly on wall and land

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* 
not applicable

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* 
not applicable

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
not applicable
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XxsuperdeadlysniperxX** [comment]
The biggest text in the world

**Comment by Anuken** [comment]
@XxsuperdeadlysniperxX Stop commenting on closed issues. I get a notification for **every single comment you make** - you are adding nothing of value. This is not a forum or social network.

**Comment by XxsuperdeadlysniperxX** [comment]
Sorry
