### ISSUE TITLE
Move the data directory to $XDG_DATA_HOME

### ISSUE THREAD

**Issue by linkmauve** [Anuken/Mindustry#397]
This will let users save their mindustry state as part of their standard backup procedure, as well as not litter their home directory with random dotfiles.

See the [XDG basedir specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for more information about `$XDG_DATA_HOME`, the fallback when this environment variable isn’t set is `~/.local/share`. You can just move the `$HOME/.mindustry` directory there if it exists, and remove the leading dot.

**Comment by Anuken** [comment]
Fixed in f7aa58e385ada66840293401573c362201642b9f
