### ISSUE TITLE
Sound/Music for bosses(Campaign) 

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry#3970]
**Platform**: *Windows*
**Build**: *Steam 121.2*

**Issue**: *The boss music will keep playing after you kill the boss, this continues even upon moving to another sector, and in another case, boss music wont even play is some other music is playing, (I get it might be because of avoiding overlapping tracks or something along those lines, but I really like the boss music and it adds to the mood a lot, so to have it play only sometimes is a bummer, Maybe could the music being played before boss fade out, boss music fades in)*

**Steps to reproduce**: *Campaign-Any sector-Kill guardian-Go to another sector while music is still playing, for other problem, have a guardian spawn while some other in game music is playing*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *Not save specific*

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
