### ISSUE TITLE
Crash on selecting launch pad location

### ISSUE THREAD

**Issue by RadiantInferno** [Anuken/Mindustry#3972]
**Platform**: *Windows*

**Build**: *121.2*

**Issue**: *When selecting the destination for a launch pad, if another pad has been set, opening the selection screen will display as if the previously selected location is selected, so clicking the Set Destination button should select it, but instead crashes the game. For example, I was on Tar Fields, and set one of three launch pads to send materials to Overgrowth. I then selected another launch pad, and when opening the selection screen it, the sector to target was Overgrowth. When I clicked the set destination button, the game crashed.*

**Steps to reproduce**: *Open the select sector UI of a launch pad, and select any sector. Open the UI again, and click the select sector button again, without first clicking a sector, and the game will crash*

**Link(s) to mod(s) used**: *N/A*

**Save file**: 
[MindustrySaveBackup4.zip](https://github.com/Anuken/Mindustry/files/5686296/MindustrySaveBackup4.zip)

**(Crash) logs**: 
[crash-report-12_14_2020_14_19_41.txt](https://github.com/Anuken/Mindustry/files/5686292/crash-report-12_14_2020_14_19_41.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed.
