### ISSUE TITLE
Steam achievement obtained potentially wrongly

### ISSUE THREAD

**Issue by LottieVixen** [Anuken/Mindustry#3973]
**Platform**: Windows 10

**Build**: Steam 121.2

**Issue**: triggered an achievement (The Spiral) when I don't believe it should have given the icon for the achievement on steam is a circle and the name is circle* in the check

**Steps to reproduce**: 
![image](https://user-images.githubusercontent.com/495512/102038281-c4d05400-3dbe-11eb-9f58-6917bbce50d2.png)
build the miners, then the conveyors going left first, then the ones going down, then the two going up, this immediately triggered the achievement when I don't believe that was the intent

**Link(s) to mod(s) used**: [Xeloboyo/Factoriodustry](https://github.com/Xeloboyo/Factoriodustry)

**Save file**: 
[sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/5686352/sector-serpulo-15.zip)

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LottieVixen** [comment]
I have looked around the codebase to see where the issue might lie and I believe it is somewhere around [mindustry,desktop.steam.SStats#L138-L155](https://github.com/Anuken/Mindustry/blob/master/desktop/src/mindustry/desktop/steam/SStats.java#L138-L155)

**Comment by GreyMario** [comment]
Briefly skimming that section of the code makes me think that the achievement will be completed if you so much as point two conveyors directly at each other. It goes forward, back, forward, back, completing a four-block check that ends at the start.
