### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry#3975]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
121.2
**Issue**: *Explain your issue in detail.*
My game crashed, apparently while loading a dialog
*Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Apparently, I came across this issue while Mindustry was at mindustry.ui.dialogs.PlanetDialog.playSelected(PlanetDialog.java:800)
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
3 Mods: dev-mode:2.3.1, rtfm:2.12.2, ui-lib:2.16.4
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[save.zip](https://github.com/Anuken/Mindustry/files/5687944/save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-12_14_2020_16_57_29.txt](https://github.com/Anuken/Mindustry/files/5687930/crash-report-12_14_2020_16_57_29.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Nice reproductions steps. No wonder if this gets closed with the comment: "Can't reproduce, can't fix"

**Comment by Anuken** [comment]
Duplicate.

**Comment by Bohaska** [comment]
> Nice reproductions steps. No wonder if this gets closed with the comment: "Can't reproduce, can't fix"

It literally crashed mid-game...
