### ISSUE TITLE
Sprites of research items smaller than usual

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#3976]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.2

**Issue**: *Explain your issue in detail.*

When you unlock something new that you can research on the campaign, the sprite is smaller than usual, and is only fixed by a restart

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Open up a campaign, research something and observe the sprite of any new researchable blocks/units

EDIT: It appears to only work with units

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[savefile.zip](https://github.com/Anuken/Mindustry/files/5689485/savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
This might actually be fixed, doing a little more testing to confirm

**Comment by nichrosia** [comment]
It appears to still apply to units, but not to blocks, unsure of why

**Comment by Anuken** [comment]
Screenshot?

**Comment by Anuken** [comment]
(closing until more info is provided, because "unit icons" can mean anything)

**Comment by nichrosia** [comment]
I'll work on a second campaign save to reproduce this issue, I'll reopen if I'm able to

**Comment by nichrosia** [comment]
Am unable to reproduce, I guess the issue was with a previous build and it was fixed

**Comment by nichrosia** [comment]
Platform: Android/iOS/Mac/Windows/Linux

Windows

Build: The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.

124.1

Issue: Explain your issue in detail.

When you unlock something new that you can research on the campaign, the sprite is smaller than usual (in some cases, have not found any pattern so far), and is only fixed by a restart

<img width="406" alt="Graphite" src="https://user-images.githubusercontent.com/57579569/107724333-3f2b3080-6ca9-11eb-8e12-a3fd63b4b473.PNG">
<img width="787" alt="Scorch and Combustion" src="https://user-images.githubusercontent.com/57579569/107724347-43574e00-6ca9-11eb-8797-9f0fb9a4e02e.PNG">


Steps to reproduce: How you happened across the issue, and what exactly you did to make the bug happen.

Open up a campaign, research something and observe the sprite of any new researchable blocks/units

Link(s) to mod(s) used: The mod repositories or zip files that are related to the issue, if applicable.

DeltaNedas/cliff
DeltaNedas/dev-mode
abomb4/dimension-shard
Eschatologue/Heavy-Armaments-Industries
younggam/multi-lib
MEEPofFaith/progressed-materials
genNAowl/upgraded-factories

(However, since I thought this issue happened in the past, I doubt the  issue is related to these mods.)

Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

[savefile.zip](https://github.com/Anuken/Mindustry/files/5969412/savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

(Crash) logs: Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.

N/A
