### ISSUE TITLE
poly buildn't

### ISSUE THREAD

**Issue by karma999-taken** [Anuken/Mindustry#3979]
**Platform**: *Android/iOS/Mac/Windows/Linux*
smart fridge
(android)
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 121.2

**Issue**: *Explain your issue in detail.*
Poly is not building a block when it's bound to a logic processor that tells it to build there.
I only have 1 (one) poly.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* I placed a logic schematic that simply builds a conveyor in a specific location. the location was completely unblocked. maybe I'm just bad at logic ok
the logic i made was
ubind @poly
ucontrol build 136 34 @conveyor 1 0
**no mods**

**Save file**: *  The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE 
[bug_report.zip](https://github.com/Anuken/Mindustry/files/5690971/bug_report.zip)
I made the logic on Ancient Caldera

If you remove the line above without reading it properly and understanding what it means, I will force you to eat a roomba. Even if you're a gamer like Karma999 is you still have to eat a roomba whole.

**(Crash) logs**: *Either the logs from a crash or logs you're supposed to crash into

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have NOT searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
bruh you need to move it too
nab

**Comment by karma999-taken** [comment]
> bruh you need to move it too
> nab

![Screenshot_20201214-193126](https://user-images.githubusercontent.com/76007654/102195780-5626ef80-3ebf-11eb-9825-0b6dd5f50a21.png)
i forgot to attach this

**Comment by WilloIzCitron** [comment]
yes poly buildn't
