### ISSUE TITLE
[question] Was wondering, why don't you just make arc-port a submodule?

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#398]
...or maybe it's too tied into the main code to be considered a module..

**Comment by Anuken** [comment]
By arc-port, do you mean the Arc repository?

If you have it in the same folder as Mindustry, it automatically makes it a _gradle_ submodule.  It's not a folder in the Mindustry repository because it's a large separate library that may be used for different projects. It's not specific to Mindustry.
