### ISSUE TITLE
3 == null

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#3980]
**Platform**: Debian stable

**Build**: 121.2

**Issue**:
![Screenshot_20:29:18](https://user-images.githubusercontent.com/39013340/102132185-2ccc7c00-3e4b-11eb-9de7-2f4e43497402.png)
this prints `1` instead of `0`

**Steps to reproduce**: that

**Link(s) to mod(s) used**: none

**Save file**: is LogicOp issue

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
wait i had a stroke

**Comment by DeltaNedas** [comment]
wait i did but im right

its using object operator instead of number operator

**Comment by DeltaNedas** [comment]
honestly comparing an object to a number at all should return null

**Comment by Anuken** [comment]
3 -> coercion to object -> null == null

**Comment by DeltaNedas** [comment]
yes but why are they coerced to objects at all
thats like using string ops on a number or class
