### ISSUE TITLE
The build menu goes wide

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#3981]
**Platform**: *Android/iOS/Mac/Windows/Linux*

windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.2

**Issue**: *Explain your issue in detail.*

the build menu breaks when block consumes a lot of items

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. make mod
2. make new block
3. make it consume a lot of items
4. hover over it
5. report this absolutely gamebreaking bug
![javaw_6uKil9Uslp](https://user-images.githubusercontent.com/59574967/102141499-f5bd9100-3e71-11eb-9032-73c188ef436b.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

here is an example mod: 
[h.zip](https://github.com/Anuken/Mindustry/files/5691890/h.zip)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

(do i really have to put this, it's an ui bug and not something related to the save)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

no crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't make blocks that consume so many resources. If you do, it's your responsibility to fix the UI. There is no automatic row behavior.
