### ISSUE TITLE
Flares and Horizons Using Zenith AI

### ISSUE THREAD

**Issue by RogueRedHawk** [Anuken/Mindustry#3988]
**Platform**: Windows

**Build**: steam build 121.3

**Issue**: Flares and Horizons use Zenith AI when attacking. I first noticed it on campaign, but I was able to reproduce it easily on sandbox. Normal Flare and Horizon AI dictates that they should swoop down on enemies and deal damage, but they are standing back and firing like Zeniths do. This is weird/wrong for flares (see #3050) and does not work for Horizons (since they are bombers).

![image](https://user-images.githubusercontent.com/57609258/102261263-a8234180-3ece-11eb-9f22-7772891aa6dd.png) 

**Steps to reproduce**: 

1. Encounter an enemy Horizon or Flare.
2.  They will stay away from your buildings and try to shoot at them.

Using my provided map, the first wave is only flares and horizons, and you can observe this behavior.

**Link(s) to mod(s) used**: I was using deltanedas/cliffs and deltanedas/rtfm, but I don't they they cause this bug.

**Save file**: 

https://drive.google.com/file/d/1NJs-RFMBMlfc4xjMMvjz1chX23xztJh3/view?usp=sharing

This is not the save file but it is the map file that I tested on.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** I searched "Horizon" and did not find any issues like what I describe except #3050 (which was not a bug anyways).

**Comment by Anuken** [comment]
Duplicate.

**Comment by RogueRedHawk** [comment]
Sorry, it was reported and fixed while I was writing the report.
