### ISSUE TITLE
Archipelago poly enemy units

### ISSUE THREAD

**Issue by Marwan-magdy2211** [Anuken/Mindustry#3989]
![Screenshot_2020-12-15-21-18-38-18_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/76068913/102262029-33c2bf80-3f1b-11eb-97e0-c071e6ca1b69.jpg)
**Platform**: *Android*

**Build**: *121.2.*

**Issue**: *while playing in Archipelago map I noticed that poly enemy units doesn't move and I have to destroy them by myself to skip wave timer*

**Steps to reproduce**: *just a bunch of scared poly enemy units just shoots me when I go to enemy spawn*

**Link(s) to mod(s) used**: *no mods used*

**Save file**: *
[save data.zip](https://github.com/Anuken/Mindustry/files/5698123/save.data.zip)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:  *

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/102267843-78813300-3ee8-11eb-9368-5ff95ab776e2.png)

Cannot reproduce; the polys in the save attack me immediately.
