### ISSUE TITLE
Duplicate sector icons

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#3990]
**Platform**: Windows

**Build**: 121.4

**Issue**: In the sector custom icons selection, the "mountains" icon appears twice. One of them has a slightly thicker border.

Also, it would be nice if icons were grouped together by theme, e.g. all the arrows were next to each other, as well as locked/unlocked, file icons, media playback icons, social media icons, etc. Trying to find any icon right now is headache-inducing.

![Sector icons bug](https://user-images.githubusercontent.com/15149002/102266916-f552e380-3ecd-11eb-8de5-c869a92889e5.png)
**Steps to reproduce**:
1. Go to the campaign map screen.
2. Select a sector.
3. Customize its icon.

**Link(s) to mod(s) used**: None

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Those are still different icons.
