### ISSUE TITLE
the thing about passive zone winning

### ISSUE THREAD

**Issue by Megaboto** [Anuken/Mindustry#3994]
**Platform**:Windows

**Build**: steam build 121.4

**Issue**: so i was in the stained mountains and did pretty well, then suddently the guardian came. having only removed half it's health and it having reached my core, i pretty much lost so i launched most of my resources to another map to set up a base there. the preview showed "0/2 waves will be defeated", and yet after some time on the new (side) map i got the notification about how the zone was captured. I do not know how the calculations work, but for one i wouldn't have defeated the guardian wave that apparently wasn't even considered in the calculations, but i also should not have "captured2 it after it was bombing my core with artilery and me being on another map, while it even shows none will be won

**Steps to reproduce**: pretty much play the map with lots of defenses, including heavy anti air everywhere and some support units built(the tier after miner, as in ugrade). get trough each wave with ease, get crushed by the guardian but before the core dies go to another location. possibly make a backup save in one of which it shows that you will win and then you actually play it to see if it wins against the guardian, using not enough defences to actually defeat it but for the game to still show that you will.

**Link(s) to mod(s) used**: none, purely vanilla

**Save file**:  for some reason i have a zip file but it just tells me "we don't support that file type" even if this is all i can do with 7zip and it shows the zip file icon

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: none, it's a bug not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save.
