### ISSUE TITLE
Game says that you were votekicked, even if you are not. 

### ISSUE THREAD

**Issue by TheUzbek** [Anuken/Mindustry#4005]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Release 120.4

**Issue**: *Explain your issue in detail.*

The message "You have been kicked from the game recently. Wait before reconnecting again" appears,it usually appears if you were votekicked from the server. It appears even if you haven't joined the server in the past hour. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. Enable any mod (used sk7725/Testers in my case) 
2. Join any server. The game will say that your mod is incompatible with the server. 
3. Turn off the mod. 
4. The game will say that you need to exit to reload mods, press "OK". 
5. Return to the game
6. Join the server you joined in step 2.

To remove the message and join the server, you need to close the app. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

sk7725/Testers (works with every other mod, incompatible with the server) 

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

N/A

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

No crash logs. 

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce on my phone. Sounds like a problem with the server.

> To remove the message and join the server, you need to close the app.

The app already closes when you reload mods.

> 120.4

There is no such version.

**Comment by TheUzbek** [comment]
> Cannot reproduce on my phone. Sounds like a problem with the server.
> 
> > To remove the message and join the server, you need to close the app.
> 
> The app already closes when you reload mods.
> 
> > 120.4
> 
> This is not the latest version.

Wait, did I write 120.4? Sorry, I meant 121.4 lol. Also, it is problem with all the servers, because I tried the bug on 5 different servers, always getting the same message. It is not a critical bug, just a really weird one.

**Comment by sk7725** [comment]
This is intended behavior. Joining with unneccesary mods is treated as an instant kick. So, even if the game told you that you had incompatible mods, you were insta-kicked, too. Servers have a cooldown time(I do not know if this varies across servers), so you need to wait before trying to join again, since you just got kicked.
