### ISSUE TITLE
Wave Turret fails to hit stationary unit

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#4009]
**Platform**: Windows 

**Build**: steam build 121.4

**Issue**: The enemy Wave turret shoots at a stationary unit, but fails to hit it.
The unit is controlled by the player and doesn't move. Also visually the fire doesn't reach the unit.

![20201216234036_1](https://user-images.githubusercontent.com/75215867/102416635-7a3b1b80-3ffa-11eb-946b-5e029d83bc49.jpg)

If the player decides to move closer, the Wave turret does hit the unit.

**Steps to reproduce**:
1) Load the save file
2) Don't move
3) Observe the Wave Turret shooting at you but not hitting you

**Link(s) to mod(s) used**: No mods were used

**Save file**: [275 Wave Bug.zip](https://github.com/Anuken/Mindustry/files/5705899/275.Wave.Bug.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
