### ISSUE TITLE
hs_err_pid.log overrides crash

### ISSUE THREAD

**Issue by younggam** [Anuken/Mindustry#4013]
**Platform**: *Windows10*

**Build**: *121.4*

**Issue**: *When I exit mindustry for any reason(includes crashes, pressing exit button). It leaves hs_err_pid<nums>.log in it's directory. And it overrides crash log. Crash logs are cut off from 12/10 (cannot specify window's build) when I migrated v121 to v121.2*
![제목 없음270](https://user-images.githubusercontent.com/61054554/102477087-3ea65d00-409f-11eb-8841-8a4c9d8decd2.png)
![제목 없음271](https://user-images.githubusercontent.com/61054554/102477088-40702080-409f-11eb-99f4-550b5113a299.png)
![제목 없음272](https://user-images.githubusercontent.com/61054554/102477091-41a14d80-409f-11eb-9e61-c3670d969fab.png)

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff12b34592, pid=25884, tid=13600
#
# JRE version: Java(TM) SE Runtime Environment (15.0.1+9) (build 15.0.1+9-18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (15.0.1+9-18, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [MSCTF.dll+0x74592]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Steps to reproduce**: *I just used jar from release. I've heard you can't reproduce in windows VM.*

**Link(s) to mod(s) used**: *mod that can occur crashes. or vanilla can create hs_err_pid.log with just exiting*

**Save file**: *h*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *recent hs_err_pid*
[hs_err_pid25884.log](https://github.com/Anuken/Mindustry/files/5708722/hs_err_pid25884.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
...wait why is the pid bug report link diferent

**Comment by Anuken** [comment]
> I've heard you can't reproduce in windows VM.

And thus I cannot fix it.

**Comment by Anuken** [comment]
(Note: The crash occurs when SDL quits, in [MSCTF.dll](https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework). This handles "advanced text input", which explains why I can't reproduce it.)
