### ISSUE TITLE
There are still damaged blocks on fungal pass.

### ISSUE THREAD

**Issue by NeviNovat** [Anuken/Mindustry#4018]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: release build 121.4

**Issue**: At first i figured out that block health was increased and that's why blocks where damaged on all sides, but after a campaign reset most maps that I have seen have undamaged blocks. Fungal pass is still one still has missing and damaged blocks but only on the enemy side.
![image](https://user-images.githubusercontent.com/51816321/102501661-59b8a300-4086-11eb-8110-c343e45159d7.png)
![image](https://user-images.githubusercontent.com/51816321/102501691-62a97480-4086-11eb-911d-b50867d7440c.png)
The graphite factory/big core is damaged and there is a missing enemy factory building.
![image](https://user-images.githubusercontent.com/51816321/102501845-8d93c880-4086-11eb-9184-a673b6a7dbcc.png)
The building on your team are fine all repaired and updated at the start you even get a factory for units, that's why I think this is worth reporting.

**Steps to reproduce**: Play fungal pass map in campaign.

**Save file**: 
This in this save I played for a bit so its not a new start, and I don't want to reset the campaign again.
[sector-serpulo-21.zip](https://github.com/Anuken/Mindustry/files/5710122/sector-serpulo-21.zip)

---

I did research for this bug and it has been reported around and it said it was fixed but for me after the reset that I did 4 days ago there is still this issue.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug. Block health was increased. Your side doesn't have damaged blocks because the map was changed.

**Comment by joshuaptfan** [comment]
The enemy setup to feed what used to be a spirit repair drone factory is... an intentional memorial?

**Comment by Anuken** [comment]
The base doesn't need spirit drones, since repair is done by megas now. I could *remove* everything around it, but that wouldn't change much.

**Comment by NeviNovat** [comment]
It's just weird to have a campaign map be in this state. Can other people change it so it doesn't look so bad? maybe add some mining drones and repair the core and graphite factories?
