### ISSUE TITLE
mobile users can shoot and build

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#4020]
**Platform**: mobile

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* yes

**Issue**: *Explain your issue in detail.*
when a mobile player is building, autoshoot can still have them shoot at things. it may only occur when they are unable to build but still have the build beams.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. join multiplayer game (i joined from pc)
2. mobile player build thing
3. mobile player also shoots things
4. crime

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
no

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
uWu

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
already fixed

**Comment by Legomonster33** [comment]
> already fixed

oh oops
