### ISSUE TITLE
Hang on Image when updating

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#4021]
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

started in some BE build, cant find which because after the first load it stops, but does affect all prior builds.

**Issue**: *Explain your issue in detail.* WHen first installing a new build, the age hangs when loading on Image. No crash is filed, Java entirely hangs with no log afterward.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* LOad a new build of industry, and watch it hang.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Happened before I messed with mods, so none.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Umm, not applicable? also **no stealing my soul**
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
Not a crash?
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
I have reported this issue before without much detail, this is my second atempt

**Comment by Anuken** [comment]
(No version, no log, cannot reproduce. If it's related to BE updating, I don't care, I'm not maintaining that system right now.)
