### ISSUE TITLE
I found bug about UI, broken scheme

### ISSUE THREAD

**Issue by CoCuCka-XD** [Anuken/Mindustry#4025]
![ВЫА](https://user-images.githubusercontent.com/70099291/102586949-9a272800-413d-11eb-8970-f0d28c4788dd.jpg)
**Platform**: `Windows 10 x64`

**Build**: `steam build 121.4`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slava0135** [comment]
Understandable have a nice day

**Comment by Erisfiregamer1** [comment]
Use the template correctly. Also, hand over your soul. NOW.

**Comment by TheSlaylord** [comment]
your soul's gonna be reaped for this

P.S.
![unknown-18](https://user-images.githubusercontent.com/62336673/102624772-8d163300-4155-11eb-8b97-08673a8330ce.png)
