### ISSUE TITLE
Intelligence + 4025

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4029]
linked with #4025.
**Platform**: *Windows 10 64bit*

**Build**: *Most likely 121.4.*

**Issue**: *Base schematics sometimes do not work/are terrible.*

**Steps to reproduce**: *attack sector.*

**Link(s) to mod(s) used**: *unavailable*

**Save file**: *procedurally-generated-attack-sector-69.zip*

**(Crash) logs**: *unavailable*

**Possible fix**: *get better base schematic designers and overhaul the base schems. Preferably choose people with a brain that has a better performance rating than my tablet's GPU.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** no but why would it have been? ive been watching the commits
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug. The issue tracker is not a place to complain.

> Save file: procedurally-generated-attack-sector-69.zip

No screenshots, no details, no save. I don't even know which specific structures you're talking about.

**Comment by BlueWolf3682** [comment]
@Anuken i cant tell you *what* structures on *what* procedural attack maps, cause the structures in question are numerous and widespread. this is a reminder to check *all* of your baseparts before uploading them because some of your "base schematic designer" crew are not fit for their jobs.

**Comment by Anuken** [comment]
> i cant tell you what structures on what procedural attack maps, cause the structures in question are numerous and widespread

You are capable of providing *some* screenshots. It should be as simple as pressing the Windows (?) screenshot hotkeys in the game, selecting an area and pasting it into your report.

**Comment by BlueWolf3682** [comment]
ill do that once i bring my iOS devices far enough in campaign.
