### ISSUE TITLE
Schematics start searching unintentionally

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4031]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20358`

**Issue**: if you open the schematics while still using wasd to move [the search bar](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/dialogs/SchematicsDialog.java#L289) gets filled with it, not allowing you to pick.

**Steps to reproduce**: move around on desktop while opening the schematic menu.

![Screen Shot 2020-12-18 at 16 45 12](https://user-images.githubusercontent.com/3179271/102633223-6c97aa00-4150-11eb-91e9-fae1f49910c3.png)

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

> not a bug but feels like one, this happens to often 👀

**Comment by Anuken** [comment]
It intentionally focuses the schematics menu when you open it, so you can start searching immediately. I don't think that should change.

**Comment by joshuaptfan** [comment]
Well... don't move using the keyboard when you open the search bar then. You can use mouse movement to prevent this. Also, I tested holding a movement key while opening the schematic menu, and it doesn't start typing (only types on key down), so the fix I would have suggested is already there.

The search bar being auto focused is too important of a QoL to dump over this.

**Comment by Quezler** [comment]
> It intentionally focuses the schematics menu when you open it

yea the "the search bar" links linked to that bit, noticed it was intentional but its just annoying when it triggers @ move keys 😅
