### ISSUE TITLE
poly vs phase wall = ???

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#4032]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
121

**Issue**: *Explain your issue in detail.*
![изображение](https://user-images.githubusercontent.com/57039557/102646847-2fe2a780-417e-11eb-8155-26903613344e.png)
0 damage

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
get poly to attack hostile phase wall

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[polytest.zip](https://github.com/Anuken/Mindustry/files/5717389/polytest.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Bullet hits wall, bullet gets deflected, bullet hits wall, wall gets healed.

**Comment by ThatOneBepis** [comment]
Big brain move @Ilya246 
now work on fixing god-factory.json

**Comment by Yell245** [comment]
On my way to build phase walls so enemy supports will heal it
