### ISSUE TITLE
Sector Names Immutable When Planet Map Accessed from Minimap View

### ISSUE THREAD

**Issue by dudecon** [Anuken/Mindustry#4035]
**Platform**: `Windows 10 x64`

**Build**: `steam build 121.4`

**Issue**: The Rename Sector text field does not accept input when the Planet Map view is entered directly from the Minimap view.

**Steps to reproduce**: Enter any sector (Launch, Go, or Resume). Press "M" to bring up the fullscreen Minimap . Press "N" to bring up the Planet Map. Select any sector. Click on the edit name pencil near the bottom of the screen to bring up the Rename Sector overlay. The text cursor does not appear and the text of the sector name is not editable.

**Link(s) to mod(s) used**: `none`

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5718608/saves.zip)

**Crash report**: `none`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix. The minimap has keyboard focus, don't use it when renaming sectors.
