### ISSUE TITLE
Plastanium conveyor bug

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#4036]
**Platform**: *Android/PC*

**Build**: *121.4*

**Issue**: *are these things supposed to happen? I don't know if this is a bug.
![h](https://user-images.githubusercontent.com/60452545/102681630-c4123600-41a1-11eb-8a7c-ba26ef4fa00a.png)

![anook](https://user-images.githubusercontent.com/60452545/102683523-997ba980-41b0-11eb-8839-431f45a183ef.png)
.*

**Steps to reproduce**: *repeat what is on the image or just download the save file.*

**Link(s) to mod(s) used**: *none.*

**Save file**: *[oh no](https://1drv.ms/u/s!AnYf7oxSZjN8gUKvkmCYC5tLKJ6X).*

**(Crash) logs**: *none.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
![additional image](https://user-images.githubusercontent.com/60452545/102683185-d98d5d00-41ad-11eb-990f-993f9d010848.png)

**Comment by GreyMario** [comment]
I believe a gif is worth more than stills in this bug report.
![2020-12-18_23-58-57](https://user-images.githubusercontent.com/502797/102684419-2d3b7e80-418d-11eb-9683-16c488624e95.gif)

**Comment by Quezler** [comment]
related: https://github.com/Anuken/Mindustry-Suggestions/issues/1274
