### ISSUE TITLE
Soloud Game Freeze

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4038]
**Platform**: *Windows*

**Build**: *steam 121.4*

**Issue**: *I downloaded https://github.com/pankiwi/MindHorition from github(in the mods dialog). Naturally, the game told me to restart. I pressed ok. A popup came up, and when I hit Ignore(I), Mindustry became (Not Responding) and died.*
![image](https://user-images.githubusercontent.com/58885089/102684516-9fa76f80-421c-11eb-9eda-a30b7dcf4abf.png)

**Steps to reproduce**: *Download a mod via import from github (idk if it has to be MindHorition) and press ok to restart.*

**Link(s) to mod(s) used**: *https://github.com/pankiwi/MindHorition*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *...None, but I don't know if this don't generate crash logs or it is #4019 coming into play.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by claw4oo** [comment]
This may be an issue with the mod itself, I haven't downloaded the mod myself to try it out to be sure

**Comment by ThatOneBepis** [comment]
see last_log.txt?

**Comment by Anuken** [comment]
Duplicate.
