### ISSUE TITLE
Ripple Minimum range

### ISSUE THREAD

**Issue by HTMLPhoton** [Anuken/Mindustry#4041]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.4

**Issue**: *Explain your issue in detail.*

Ripple cannot fire at spots less than around 5 tiles away from itself (though it's bullet spread and splash can allow it to damage spots closer). Ripples will try to shoot at enemies which it can't damage even through splash damage.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Minimum range:
1. Manually control a Ripple with ammo
2. try to shoot at yourself (the ripple you are currently controlling)
3. the bullets will travel around 5 blocks out before exploding

Targeting a enemy that is too close
1. bring an enemy unit (I used a dagger) right up against a ripple
2. the ripple will try to shoot at the unit. but cannot damage it
(Blast compound has enough splash radius to still damage the dagger while plastanium's frags can also it the dagger.)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[145.zip](https://github.com/Anuken/Mindustry/files/5719263/145.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
It's...

A ranged artillery turret...

You don't fire mortar shells at your own feet, that's just beyond stupid.

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java#L1726
