### ISSUE TITLE
Fungal pass research text

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#4045]
**Platform**: iOS

**Build**: 121.4

**Issue**: Fungal Pass research text refers to two enemy cores.  There is only one as far as I can tell.

**Steps to reproduce**: Check the research entry for Fungal Pass.

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, it has two.
