### ISSUE TITLE
I can select sector

### ISSUE THREAD

**Issue by Prosta4okua** [Anuken/Mindustry#4047]
**Platform**: *Windows 10*

**Build**: *121.4.*

**Issue**: *I can highlight sector in Core Databae*

**Steps to reproduce**: *open planet menu -> researches->database.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

https://user-images.githubusercontent.com/31485341/102699503-fb3e2100-424d-11eb-8854-518990f5be69.mp4

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
