### ISSUE TITLE
Game freezes up when missusing diagonal conveyor belts in straight lines

### ISSUE THREAD

**Issue by Xyzair** [Anuken/Mindustry#4049]
**Platform**: `Windows 10 x64`

**Build**: `release build 121.4`

**Issue**: `While using the diagonal place, if you go up and down a couple of times over previously placed conveyors it will freeze (infinite loop?) and won't unfreeze.`

**Steps to reproduce**: `Hold left ctrl the entire time. place some conveyors in one direction then in the opposite direction over top (needs to be more than 1 conveyor placed) this is specifically in the horizontal and vertical direction and appears to happen on any map`

https://user-images.githubusercontent.com/13341174/102703285-cddb7e00-4221-11eb-8346-8fb1dafa9bda.mp4

**Link(s) to mod(s) used**: `none`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
