### ISSUE TITLE
Game sounds die randomly 

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#4050]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.4

**Issue**: *Explain your issue in detail.*

Game sounds die randomly

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

It happens when you first enter the sector i have no idea when it happens aka random

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

0 mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[saves.zip](https://github.com/Anuken/Mindustry/files/5720417/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from 
the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

No crashs

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to  sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XxsuperdeadlysniperxX** [comment]
im going to reopen once my file uploads

**Comment by XxsuperdeadlysniperxX** [comment]
HAHA on android to upload a file you must be on the browser version for it to work

**Comment by Anuken** [comment]
> the sector

I don't know what "the sector" is; you've just sent me a bunch of save files without specifying.

**Comment by XxsuperdeadlysniperxX** [comment]
@Anuken if i new i would have just posted it the entire campaigns sound dies so im sorry for any confusion also because its the entire campaign i didn't exactly have a clue where the save was that had it because everything and i do mean _everything_ in the saves be looking the same and confused me when i opened it also took a me good 5 hours to figure out how to upload a .zip file and if you ever do come across some guy thats confused can you tell him the only way he can upload said file? It would be appropriated but if you don't want to thats fine too just wanted to ask

**Comment by XxsuperdeadlysniperxX** [comment]
Wow i meant to put any sector kind accidentally posted it prematurely and was trying to get it edied before someone looked at it
