### ISSUE TITLE
Omura Aims incorrectly

### ISSUE THREAD

**Issue by HTMLPhoton** [Anuken/Mindustry#4051]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

121.4

**Issue**: *Explain your issue in detail.*

Omura Aims at incorrect spots. I do not know the full extend of this bug but I do know:
 - A non-moving Omura MOST OF THE TIME WILL NOT aim correctly at a moving Unit
 - A non-moving Omura WILL aim correctly at a non-moving Unit (I would assume also buildings, But I haven't tested that)
 - A moving Omura WILL NOT aim correctly at a non-moving Unit or building
 - A moving Omura WILL aim correctly at a moving unit
(I haven't tested with all units)
When Omura doesn't aim correctly it shoots in front of the target like it's trying to lead the target when it shouldn't.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Have an AI-controlled (not player controlled or logic-controlled) Omura try to shoot at enemy stuff. see the cases above for what it would aim correctly at and what it would not.

You can also use the save files where I tested Omura's aim

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

NONE

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[non-moving Omura vs moving target.zip](https://github.com/Anuken/Mindustry/files/5720424/non-moving.Omura.vs.moving.target.zip)
(The waves alternate between Toxopod and Risso. Omura will never hit the toxopod but will start hiting the risso consistently after and only after 2-3 shots)
[non-moving omura vs non-moving target.zip](https://github.com/Anuken/Mindustry/files/5720425/non-moving.omura.vs.non-moving.target.zip)
(The waves also Alternate between Risso and Toxopod. The Risso is bugged and still moves but the Toxopod dosn't)
(Also I think the Risso being bugged to not being effected by the unmoving effect is intentional and can't be fixed)
[moving Omura vs moving and non-moving target.zip](https://github.com/Anuken/Mindustry/files/5720423/moving.Omura.vs.moving.and.non-moving.target.zip)
(Omura is spawned by starting the wave. Use your gamma to test the enemy omura against moving and non-moving units. There is a specter in the path of the omura to test buildings)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
can confirm, had this happen on the nydus bleeding edge server as well 👍

**Comment by XxsuperdeadlysniperxX** [comment]
@Quezler i've noticed like every uit shoots incorrectly except for the rail gun on the boat of course so if that issue is on omura its also on a whole bunch of units mostly boats tho that i've found of course
