### ISSUE TITLE
Mobile naval controls are still bad in lag

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4059]
#3657 was not fixed. Naval units still fail to turn in low FPS on my iPod.

(yeeted template cause everything is in #3657, no need for extra clutter)

**Comment by itcannotbe** [comment]
You should probably continued in 3657 XD

**Comment by BlueWolf3682** [comment]
> You should probably continued in 3657 XD

why mention an active bug where anuke wont see it?

**Comment by Anuken** [comment]
Either you're running an old version or you're omitting relevant information, because I can't reproduce it.

**Comment by BlueWolf3682** [comment]
@Anuken <15FPS, found issue at about 10-5FPS

**Comment by Anuken** [comment]
Rotates fine at 5FPS for me.

**Comment by XxsuperdeadlysniperxX** [comment]
@Anuken the navel units ai does repath backwards tho
