### ISSUE TITLE
Numeric keypad keys not recognised as keypad key, only as number key

### ISSUE THREAD

**Issue by halfheart-games** [Anuken/Mindustry#4060]
**Platform**: `Linux x64`

**Build**: `release build 121.4`

**Issue**: *I noticed this when I couldn't access schematics and thought there was a much more serious issue. Friends could still access schematics, so I checked the key binds and found that my previous binding was displaying as '6' instead of 'Numpad 6'. I tried downloading some older versions from GitHub and found that the behaviour changed between 121.2 and 121.3*

**Steps to reproduce**: *Try to rebind a control to a numeric keypad key.*

**Link(s) to mod(s) used**: `none`

**Save file**: *
[keypad.zip](https://github.com/Anuken/Mindustry/files/5724032/keypad.zip) contains a saved game from v121.3 and settings.bin from v121.2 and 121.3. Both settings files were created from a fresh install with Keypad keys 8, 2, 4, and 6 used to replace the movement keys.*

**Crash report**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is an intentional change.

**Comment by joshuaptfan** [comment]
I submitted [this change](https://github.com/Anuken/Arc/pull/36) based on this [QoL suggestion](https://github.com/Anuken/Mindustry-Suggestions/issues/1483), and at the time I guessed that there would be no complaints, so why not. So, you're the first.

**Comment by halfheart-games** [comment]
> I submitted [this change](https://github.com/Anuken/Arc/pull/36) based on [this QoL suggestion](https://github.com/Anuken/Mindustry-Suggestions/issues/1483), and at the time I guessed that there would be no complaints, so why not. As it turns out, you're the first.

I'll probably be the only one. Having read the suggestions, I can see this will be much more useful for more people as it currently works.

**Comment by Shadow8472** [comment]
> I'll probably be the only one. Having read the suggestions, I can see this will be much more useful for more people as it currently works.

You are not alone. I'm a bit miffed about finishing my bug report -- only to find this issue and that the change was intentional. Thankfully, I only had to re-write about half of it to shift focus. Thanks for caring enough to check in ~3 years ago.

**Comment by tkossak** [comment]
Yes, you are not alone and it breaks my game controls that I use in all games. I use mouse that has 12 buttons on the side (mapped to Num1-0 and other keys) and this game makes them useless. It doesn't seem like it will be fixed (since it's intentional), so I'm returning the game.
It is the first game in hundreds that I played, that can't recognize Num keys properly.
