### ISSUE TITLE
Router + Junction + Router decreased throughput

### ISSUE THREAD

**Issue by ruggi99** [Anuken/Mindustry#4061]
**Platform**: Windows

**Build**: 121.4

**Issue**: If I have Router + Junction + Router the throughput is decreased. Works well in other cases (like Junction + Router + Junction). Vertical conveyors are directed to external

**Steps to reproduce**: See video.

https://user-images.githubusercontent.com/25064808/102775803-de106c00-438d-11eb-95af-ccf65f346970.mp4

I know that Junction throughput has been decreased in a old version, but this breaks some of my schematics. Is there any other solution to decrease Junction throuhput without affecting Router + Junction + Router line?

**Link(s) to mod(s) used**: No mods used.

**Save file**: [World.zip](https://github.com/Anuken/Mindustry/files/5724198/World.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment]
Ah yes. Now actually try that with 2 routers with out the junction.

**Comment by ruggi99** [comment]
@itcannotbe Yes I see, with 2 routers the throuhgput is not efficient, but I know that since I started playing Mindustry.
Instead I'm pretty sure router + junction + router worked fine before.

**Comment by Yell245** [comment]
It's because of the flowback. You see, router sends resources in all directions

**Comment by ruggi99** [comment]
@Yell245 you're wrong.
Try to reproduce, replace junction with a conveyor and see. It works as expected.

**Comment by Slava0135** [comment]
go away noob

**Comment by ruggi99** [comment]
With v120 it works as expected, there's no flowback, or at least not as in v121.4.
If v121.4 behavior is correct then I will close.

**Comment by Slava0135** [comment]
Everything works as expected go away
