### ISSUE TITLE
Blocks that makes liquids from items and liquids voids liquid if there is no space for the cycle's output in the production block

### ISSUE THREAD

**Issue by itcannotbe** [Anuken/Mindustry#4062]
**Platform**: Android + Linux + Windows

**Build**: 121.4

**Issue**: Title

**Steps to reproduce**: 
See Image comparison.

![Screenshot_20201221_194533_io anuke mindustry](https://user-images.githubusercontent.com/45280919/102781242-4e40e100-43d2-11eb-9026-46b6e7b8164f.jpg)
![Screenshot_20201221_194529_io anuke mindustry](https://user-images.githubusercontent.com/45280919/102781252-54cf5880-43d2-11eb-9b1a-2c3890a2da2f.jpg)
![Screenshot_20201221_194525_io anuke mindustry](https://user-images.githubusercontent.com/45280919/102781259-5731b280-43d2-11eb-9c3a-9f60e1cc996a.jpg)

**Link(s) to mod(s) used**: N/A

**Save file**: Easily Reproducable

[test_sand.zip](https://github.com/Anuken/Mindustry/files/5724553/test_sand.zip)

**(Crash) logs**: Not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
> Easily Reproducable

then include a save file for anuke

**Comment by itcannotbe** [comment]
> > Easily Reproducable
> 
> then include a save file for anuke

Working on it. Currently even the image is a placeholder tungsten.

**Comment by Absolute359** [comment]
The same issue might also apply for Cryomixers
this would at least explain why water expires in an example ratio of 1 water extractor - 1 cryo mixer - 1 thorium reactor.
even tho the reactor needs only 2.4 cryo/s and the water extractor produces 6.6 water/s it doesnt fill up with water.
So if the reactor consumes 2.4 cryo in 1sec the cryomixer starts a full production cycle and consumes the full 12 water/s even tho only 2.4 cryo was used

**Comment by Anuken** [comment]
There isn't really anything I can do about this with the current system.
