### ISSUE TITLE
logic schematic + vault label bug

### ISSUE THREAD

**Issue by MattMills** [Anuken/Mindustry#4064]
**Platform**: Windows

**Build**: 121.4 steam

**Issue**:  Vault switches between Vault2 and Vault3 rather than labeled and unlabeled in CPU logic selection
![recording](https://user-images.githubusercontent.com/1988797/102793053-90ccd400-4366-11eb-99d7-62a71962746f.gif)

**Steps to reproduce**:

Placed a schematic (attached) of a CPU that must have had some things selected near the core, the CPU is the only thing in the schematic, The CPU selected a bunch of misc conveyors and vaults and a nucleus. One of the vaults is not de-selectable, it just switches between vault 2 and 3 when you click it.

After re-loading the game after grabbing the save the vault was labeled "Vault1" and could be deselected as normal. I am able to reproduce by deleting the logic processor and re-placing it from the schematic in the same spot, bottom right vault is labeled "vault3" but when clicked changes to vault2.

[core_item_throttle.zip](https://github.com/Anuken/Mindustry/files/5725098/core_item_throttle.zip)

**Link(s) to mod(s) used**: None
**Save file**: [sector-serpulo-131.zip](https://github.com/Anuken/Mindustry/files/5725085/sector-serpulo-131.zip)

**(Crash) logs**: N/A no crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by scarf-generic** [comment]
i do not think this is a bug, the vault is just linked multiple times. if you place a processor that was linked to 1x1 blocks and place a larger block on top of both spaces this happens, or if you move the processor. to prevent this from happening, remove all links from your processor before copying it.

**Comment by MattMills** [comment]
I think it's pretty clearly a bug as evidenced by the fact that it doesn't happen after the map gets reloaded and something within the links corrects itself... Why would/should it be possible to link a vault "twice" when that isn't a thing that can be done or makes any sense or works within the UI?

**Comment by joshuaptfan** [comment]
To fix this on your end, you need to copy the logic code from your processor, place a fresh processor, and paste the code into it, then overwrite your old schematic with the fresh processor that has no links.
