### ISSUE TITLE
Bridge conveyor storage doesn't seems to be work correct

### ISSUE THREAD

**Issue by serdarakkilic** [Anuken/Mindustry#4066]
**Platform**: *Mac*

**Build**: *steam build 121.4*

**Issue**: *Bridge conveyor storage doesn't seems to be work correct and item storage capacity information is wrong.*

**Steps to reproduce**: 
![bridge-conveyor-bug](https://user-images.githubusercontent.com/12392315/102803278-0ff2f400-43c9-11eb-882d-5101e46094c1.gif)

**Link(s) to mod(s) used**: *none*

**Save file**: *[bridge-conveyor-bug.msav.zip](https://github.com/Anuken/Mindustry/files/5725566/bridge-conveyor-bug.msav.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug; bridges have *items* and *intermediate buffers* that store items between bridges.
