### ISSUE TITLE
sapping lasers aren't sticky

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#4067]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 121.4

**Issue**: *Explain your issue in detail.*
sapper beams can seperate from the unit that fires them when the unit is moving.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. control spiroct
2. `UnitTypes.spiroct.speed=10` (happens at all speeds just more speed = more noticable)
3. ram into space tiles  / shadow
4. beams will seperate

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
n/a

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[sapper_beams.zip](https://github.com/Anuken/Mindustry/files/5726212/sapper_beams.zip

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
![image](https://user-images.githubusercontent.com/54417042/102816610-53833900-439c-11eb-82a6-e4d424475f5e.png)

**Comment by Anuken** [comment]
I don't care.

**Comment by Legomonster33** [comment]
> I don't care.

ok lol
