### ISSUE TITLE
Fire DoT still tied to FPS for units with Armor stat

### ISSUE THREAD

**Issue by GreyMario** [Anuken/Mindustry#4071]
**Platform**: *Windows*, but affects all

**Build**: 121.4

**Issue**: Fire damage over time is still based on FPS due to the armor stat being added to the final damage value _every frame_.

[Video evidence.](https://cdn.discordapp.com/attachments/663853133587546138/790812986926432266/2020-12-21_21-27-18.mp4)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
To clarify, it's after `damageContinuousPierce` distributes the DoT across delta time [and passes it to `damagePierce`](https://github.com/Anuken/Mindustry/blob/eda134a18c0c88415368ff2803d3fe028a070ca6/core/src/mindustry/entities/comp/HealthComp.java#L53), which ends up called every frame.

The cause is that armor is being bypassed _twice_ for pierce damage: the damage is increased by the armor stat, and then it decides to not care and instead applies damage directly to health anyway.

**Comment by GreyMario** [comment]
(What's the intent here, anyway? Piercing armor is one thing, but the currently written code does **bonus** damage to an armored unit's health. Where is the balance intended to sit for damage over time?)

**Comment by Anuken** [comment]
> The cause is that armor is being bypassed twice for pierce damage

No, it's not. 

> the damage is increased by the armor stat, and then it decides to not care and instead applies damage directly to health anyway

It may look like it, but that method is overridden by the class that handles armor. The real issue here is that when I add the armor to the damage, it counts it as "standard" damage and **applies the 90% absorption rule to it**, which means that very low damage numbers coupled with very high (relative) armor end up dealing more damage.
