### ISSUE TITLE
Drill textures are "oh no"

### ISSUE THREAD

**Issue by francois** [Anuken/Mindustry#4075]
**Platform**: Mac 10.14.6 (18G6032)

**Build**: commit ac06fa8f96f2b20dcb6c99e0f24e299ea04e678c

**Issue**: All drills have a texture of "oh no"

**Steps to reproduce**: I follow HEAD. I bisected and Git told me that 118ae8e87deb0be4a90a660e273755958c7fe888 is the first bad commit. Once I found this commit, I `rm -r desktop/build` and rebuilt using `./gradlew desktop:run`.

**Link(s) to mod(s) used**: none

**Save file**:
[save.zip](https://github.com/Anuken/Mindustry/files/5731098/save.zip)

![ohno](https://user-images.githubusercontent.com/247/102913436-bb915800-444c-11eb-8bad-ed354c85af21.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Re-pack your sprites.
