### ISSUE TITLE
Small misnomer with regards to power in documentation

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#4076]
**Platform**: *Linux*

**Build**: *121.4*

**Issue**:
In the block description under the power section there is small misnomer how the word power is used,
e.g. "Base Power Generation = 330  power units/second".

However since power itself is already a unit per time (see [1]), ie. energy/time, this statement doesn't make sense.
Instead it should read
"Base Power Generation | 330  energy units/second"
or just
"Base Power Generation | 330  power"

hth

1: https://en.wikipedia.org/wiki/Electric_power

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> However since power itself is already a unit per time (see [1]), ie. energy/time, this statement doesn't make sense.

Mindustry doesn't use real-life conventions. Power units are like units of liquids or items; they are stored in batteries ("100 power units stored") and can have "/s" tacked on if necessary.

**Comment by MayeulC** [comment]
I was confused by this today, while trying to figure if I wanted powernetin or powernetout for a microprocessor.

The most confusing part to me was "power stored" where I would expect energy; this made no sense to me for a couple seconds.

![image](https://user-images.githubusercontent.com/3952726/118376378-ecbf2000-b5c7-11eb-943e-3fb7c027bd9b.png)

I guess that the words that contain "capacity" and "stored" on the screenshot actually refer to energy. Thinking more about this, mindustry refers more to energy units than power units, even "total power" is the quantity of energy stored in a structure.

**Comment by liuxilu** [comment]
Power here refers to "power of unit electricity" as in "power of the president", I think.
