### ISSUE TITLE
Documentation Oil Extractor: wrong affinities percentages 

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#4077]
**Platform**: *Linux*

**Build**: *121.4*

**Issue**:
In the description of the oil extractor under required tiles the following numbers are given:
block-salt-medium +30% block-sand-medium +70% block-shale-medium +100% block-darksand-medium +150%

However the numbers in game are actually:
block-salt-medium -70% block-sand-medium -30% block-shale-medium +/- 0% block-darksand-medium +50%

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Base efficiency is 0%. 0% + 30% (salt) = 30%.

**Comment by famo** [comment]
Well, for a user it is not possible to deduce the correct numbers from the documentation. Because what you say is not written there. Also see documentation for water extractor.

**Comment by Anuken** [comment]
> Well, for a user it is not possible to deduce the correct numbers from the documentation.

Sand displays as "+70% efficiency". Therefore, when I place an oil extractor on sand, it runs at 70% efficiency. Is that an impossible deduction?

> Also see documentation for water extractor.

The water extractor does not **require** any tiles to run, so its base efficiency is 100%. The oil extractor **requires** certain tiles to operate.

**Comment by famo** [comment]
I guess the problem is the "+" (plus) then. Because if 

> > Well, for a user it is not possible to deduce the correct numbers from the documentation.
> 
> Sand displays as "+70% efficiency". Therefore, when I place an oil extractor on sand, it runs at 70% efficiency. Is that an impossible deduction?
> 
Yes, because in the documentation its says "**+**70%", which means base values times 1.7. If you leave "+" (plus) sign away it becomes much clearer.

> > Also see documentation for water extractor.
> 
> The water extractor does not **require** any tiles to run, so its base efficiency is 100%. The oil extractor **requires** certain tiles to operate.

I know and there might be internal differences, but its really not clear from a user perspective. It would be really helpful from a user perspective if tiles which reduce base production would be signed with a negative percentage.

**Comment by itcannotbe** [comment]
That's the point. There is no tile that can affect the oil extractor negatively since the block only works on certain tiles.

**Comment by catatagun** [comment]
What about water extracter on mud +100% but its 200%

**Comment by itcannotbe** [comment]
Base Efficiency:
Oil Extractors: 0%
Water Extractors: 100%

**Comment by famo** [comment]
> That's the point. There is no tile that can affect the oil extractor negatively since the block only works on certain tiles.

No. The point is that in one part of the documentation +70% means base value times 1.7, whereas in another part of the documentation +70% is meant to be interpreted as base value times 0.7.
Since there is no explanation in the documentation when to use which interpretation, it is impossible for the user to correctly determine the numbers (except guessing with 50/50 chance).

IRL nomenclature with percentages is:
base +70% = base value times 1.7
70% of base = base value times 0.7

**Comment by Anuken** [comment]
> Since there is no explanation in the documentation when to use which interpretation, it is impossible for the user to correctly determine the numbers (except guessing with 50/50 chance).

There is. When a tile is labeled as **required**, base efficiency is 0%; otherwise, it is 100%. When you hover an oil extractor over any non-required tile, it displays its efficiency as 0%, which makes the difference obvious. The water extractor doesn't do this.

**Comment by famo** [comment]
> There is. When a tile is labeled as **required**, base efficiency is 0%; if there are _no required tiles_, it is 100%. When you hover an oil extractor over any non-required tile, it displays its efficiency as 0%, which makes the difference obvious. 

Yes, there are ways to deduce how the documentation is meant. I myself simply found out by comparing the numbers. However **just from the documentation** it isn't possible.

> The water extractor doesn't do this.

The water extractor does do it:
![Screenshot_20201223_194526](https://user-images.githubusercontent.com/692646/103028266-b40aa580-4557-11eb-9bb2-71c76cd28d35.png)
:smile:

**Comment by Anuken** [comment]
> However just from the documentation it isn't possible.

Again, it *is*. For any given block:
- If it **requires** tiles, it has a base efficiency of 0%.
- If it doesn't, the base efficiency is 100%.

> The water extractor does do it:

No, it doesn't. It's only displayed at 0% for blocks that it **cannot** be placed on, which is a tiny subset. If you try placing it on stone, dacite, etc - *none of which are listed in the affinities* - it runs at 100%.

**Comment by famo** [comment]
> Again, it _is_. For any given block:
> 
>     * If it **requires** tiles, it has a base efficiency of 0%.
> 
>     * If it doesn't, the base efficiency is 100%.

Where do I find this in the documentation?
And would it be possible to link this information to the water and oil extractor sections for a better user understanding?

**Comment by Anuken** [comment]
> Where do I find this in the documentation?

There is no other documentation, aside from the source code. That's just how blocks work. 

> However just from the documentation it isn't possible.

I don't expect players to be able to make meaningful decisions based **only** on block stats in the database.
