### ISSUE TITLE
Small inconsisteny regarding build and reseach cost display

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#4078]
**Platform**: *Linux*

**Build**: *121.4*

**Issue**:
In game the costs to build something are displayed as:
"res available" / "cost"
whereas in the tech tree the research costs are displayed as:
"cost" / "res available"
I think this small inconsistency should be avoided.

Furthermore, and I don't know if this is a cultural thing, but I found the display as "res available" / "cost" always quite awkward and hard to read. I very much prefer the style "cost" / "res available".

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> whereas in the tech tree the research costs are displayed as: "cost" / "res available"

It's not.

![image](https://user-images.githubusercontent.com/10100000/102921678-c357f900-445a-11eb-919e-062af6b6a262.png)

**Comment by famo** [comment]
Right, my bad. I probably got confused ...
