### ISSUE TITLE
Is it possible to create keyboard shortcuts for use blocks?

### ISSUE THREAD

**Issue by danielpcampagna** [Anuken/Mindustry#408]
Is it possible to create keyboard shortcuts to select blocks? Starcraft 2 offers an option to create buildings using grade keyboard shortcuts.

Some thing like this:

![mindustry-grade-blocks](https://user-images.githubusercontent.com/7855757/52711355-c2a9ce00-2f78-11e9-9f39-103a73c06b89.png)

**Comment by Prosta4okua** [comment]
You can, but only in bleeding edge v4. 3.5 is very old.
Join the community in the discord for for more information.

**Comment by Anuken** [comment]
This feature was implemented in a PR by Desktop/indielm, although it has not been released in the stable version yet.

**Comment by danielpcampagna** [comment]
I'm waiting excitedly.

**Comment by Luxray5474** [comment]
IIRC, there is a Mindustry Desktop Edition or something to that effect that he released on the MML Server.
