### ISSUE TITLE
construction pause doesn't seem to sync

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4080]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20386`

**Issue**: while trying to record some screenshots for #4079 something weird occurred: 

https://user-images.githubusercontent.com/3179271/102921751-2ebabe80-448d-11eb-9ec6-44ead35d9b1e.mp4

**Steps to reproduce**: try to recreate the other issue and have the other person pause construction without canceling.

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

**Save file**: again, you just need a buddy on any survival map with enough materials in the core for the blocks you're testing.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.

**Comment by Quezler** [comment]
still makes for one ugly desync bug though 🤔

**Comment by Anuken** [comment]
True.
