### ISSUE TITLE
Can't relaunch into Planetary Launch Terminal after losing it

### ISSUE THREAD

**Issue by tadforever** [Anuken/Mindustry#4082]
**Platform**: *Windows 10 x64*

**Build**: *steam build 121.4*

**Issue**: *Can't relaunch into Planetary Launch Terminal after losing it*

**Steps to reproduce**: *lose Planetary Launch Terminal offscreen, when you go to retake it, first time crash, when trying again, it worked but did not give the option to choose core type, defaults to smallest core*

**Link(s) to mod(s) used**: *No Mods*

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5732648/saves.zip)

**(Crash) logs**: [crash-report-12_22_2020_19_24_29.zip](https://github.com/Anuken/Mindustry/files/5732651/crash-report-12_22_2020_19_24_29.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by tadforever** [comment]
remembered how i lost the map, it was to the final guardian and not lost offscreen

**Comment by Rickcreate** [comment]
I also have the same problem on mobile.

**Comment by zethnest** [comment]
@Rickcreate Please wait until next release. This issue has already been patched as shows in the message above.
