### ISSUE TITLE
Repeatable "Player cannot configure a tile" multiplayer crash reentering sector after defeat in campaign

### ISSUE THREAD

**Issue by LionsPhil** [Anuken/Mindustry#4092]
**Platform**: Windows

**Build**: steam build 121.4

**Issue**: Crash: `mindustry.net.ValidateException: Player cannot configure a tile.` (full log/trace below)

**Steps to reproduce**:

1. (From the attached campaign save)
2. Go to Sector 124 (a resource-pooling launch sector; it's right near the starting location).
3. Open for multiplayer. **I cannot reproduce this in singleplayer.** I was playing with a friend, and this *was* repeatable upon relaunching and rejoining. I'll find out later if getting it to load/save again OK in singleplayer has fixed multiplayer.
4. Launch for Overgrowth, which at this point in the campaign has *just* been lost to the boss at wave 30. (Argh, it heals so *fast!*)
5. Crash.

**Link(s) to mod(s) used**: No mods. This campaign save *was* migrated from v5, if that matters.

**Save file**: I believe these are the right files for the campaign save: [saves.zip](https://github.com/Anuken/Mindustry/files/5736318/saves.zip)

**(Crash) logs**: From the original crash, and the retry:

- [crash-report-12_23_2020_03_21_57.txt](https://github.com/Anuken/Mindustry/files/5736321/crash-report-12_23_2020_03_21_57.txt)
- [crash-report-12_23_2020_03_20_14.txt](https://github.com/Anuken/Mindustry/files/5736322/crash-report-12_23_2020_03_20_14.txt)

(They're both the same stack trace, eyeballing it.)

Random hypothesis: I think my buddy was controlling a unit at the time we lost. Could it be trying to reattach them on load to a unit that's now dead?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
  - Can't, I don't have Java installed, and it doesn't look like you have a beta branch on Steam or anything.
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - Closest I can find is #2222, which was closed as being caused by mods. I've never used mods.

**Comment by Anuken** [comment]
Already reported and fixed.

**Comment by LionsPhil** [comment]
Ah, in https://github.com/Anuken/Mindustry/commit/71488313e1eaedcaa5e0daab25b542a5732266ee ? Cheers, sorry for the dup!
