### ISSUE TITLE
After re-entering a map, cryofluid and water sometimes get mixed in junction

### ISSUE THREAD

**Issue by vincentsels** [Anuken/Mindustry#4096]
**Platform**: Windows

**Build**: 6.0 Build 122

**Issue**: When a cryofluid mixer has a junction straight next to it, from one side feeding water and the other cryofluid, then, upon reloading the map, sometimes, the water 'entrance' gets flooded with cryofluid, 'against the direction' of the water conveyers, preventing water entering the cryofluid mixers. Needless to say, that typically either explodes the thorium reactors or puts the impact reactors without cryofluid; and the map is basically lost...

I can see why this is happening - I guess the liquid in the junctions is not saved, whereas the cryofluid in the mixer is, which runs into the junction somehow before the water (I guess at random, because it seems to happen randomly), blocking the water. If it were the case that the junction actually was empty for some reason it would make sense, but in this case it doesn't. You leave the map when everything is ok, you re-enter the map and the fluids are mixed.

**Steps to reproduce**: See attached screenshot.

**Save file**: Attached

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[save.zip](https://github.com/Anuken/Mindustry/files/5737346/save.zip)

![2020-12-23_214035](https://user-images.githubusercontent.com/1068863/103041583-158e3c80-4577-11eb-9443-9df2e4cbb055.jpg)

**Comment by Anuken** [comment]
Two notes:

1. You've sent me your entire save data, which is not what the template asks for. The sector you were playing on wasn't even selected - how do you expect me to test your map - look through every sector? I eventually figured out which map and location was screenshotted, but it still took far too long.
2. I cannot reproduce the issue, neither in your save nor in sandbox. What is likely happening here is you had some leftover cryofluid in the pipe that is blocking flow. I see no way for cryofluid to "backflow" into conduits, looking at the code.

**Comment by vincentsels** [comment]
1 - sorry! :( Didn't know the map selection was stored/exported. You mention this isn't the correct format of the save, but I can't seem to find a description of how to take it properly? Maybe describe it [here](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#your-issue-is-missing-saves-or-screenshots) and include a link to it in the template?

I got a new export where you can see the bug in action; I'm hovering right next to the mixer, on sector Impact 0078. I exited/reloaded twice to make sure it persists. Hope this will help you find it!

[impact0078_cryofluid_water_bug.zip](https://github.com/Anuken/Mindustry/files/5739805/impact0078_cryofluid_water_bug.zip)

![2020-12-24_145831](https://user-images.githubusercontent.com/1068863/103092888-0bad1d80-45f9-11eb-9a50-36de9a0c4faa.png)

**Comment by Anuken** [comment]
> You mention this isn't the correct format of the save, but I can't seem to find a description of how to take it properly?

The template asks for "the save you are currently playing on", which is not your game data. If you were playing on the Impact sector map, I need the save file for that map.

**Comment by vincentsels** [comment]
Is it this maybe, from `C:\Program Files (x86)\Steam\steamapps\common\Mindustry\saves\saves`, zipped?

[sector-serpulo-227.zip](https://github.com/Anuken/Mindustry/files/5742199/sector-serpulo-227.zip)

**Comment by Anuken** [comment]
The conduits at the bottom do have cryofluid in them, but once I replace the contamination, everything works correctly. Reloading the save doesn't affect output.

I also tried the following things:
- Letting all water drain out, reloading the save and looking for cryofluid
- Cutting off water, replacing every block involved and reloading the save with cryofluid still being present in the mixers

Neither of these resulted in backflow.
