### ISSUE TITLE
[Android] Process machines blocked if  internal inventory is full

### ISSUE THREAD

**Issue by Naheulf** [Anuken/Mindustry#41]
On android version, process machines (smelter, crucible, ...) stop working if their inventory is full. I has no test on others versions.

Possible fix:
Add reserved minimal input and output to be able to craft.

Example with titanium extractor (I see bug with it) :
Craft : X water + 6 irons --> 1 titanium.
reserve X "slots" for water.
reserve 6 slots for iron.
reserve 1 slot for titanium.
use 83 slots for unreserved items (irons and titanium)

**Comment by BeefEX** [comment]
I tried replicating the issue on build 105 but it works fine, I assume it's already fixed @Anuken ?

**Comment by Anuken** [comment]
The thing is, both the smelter and the crucible have infinite inventory space. There is no code that checks for capacity at all. I can't reproduce it at all, even with extractors.

**Comment by Naheulf** [comment]
It's my fault. I had not understand how input and outputs work.
I would use an item router to split input conveyor flow in multiple machine and use conveyors to extract items. But router also extract output coal... See example below:
![mindustry_routerandmachines](https://user-images.githubusercontent.com/14990967/34465064-9a6ac20e-ee9d-11e7-8fc6-22730a5faa9e.png)
