### ISSUE TITLE
Units act weird in enemy spawn zone and outside of the map

### ISSUE THREAD

**Issue by SilentOwl476** [Anuken/Mindustry#4102]
**Platform**: Android

**Build**: 122

**Issue**: The unit stays in enemy spawn zone/outside of the map and shakes instead of being pushed out.

**Steps to reproduce**: 1. Go to the enemy spawn zone or outside of the map
                                       2. See how the unit shakes

https://user-images.githubusercontent.com/73083866/103085211-1ca66080-45f2-11eb-8772-87c11b8a97ce.mp4

[save-file.zip](https://github.com/Anuken/Mindustry/files/5739489/save-file.zip)

---
  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
include a save file

**Comment by SilentOwl476** [comment]
happens on every save

**Comment by Anuken** [comment]
Not a bug.
