### ISSUE TITLE
The Disabling of Flying of a unit in servers

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#4103]
**Platform**: *Windows*

**Build**: *v122*

**Issue**: *When i got hit by a spectre while flying as gamma, my health regen and when it got lower than 0 and instantly regen, my flying ability got disabled. When i synced, it was fixed.*

**Steps to reproduce**: *Be gamma, get hit by a spectre and escape just after your health drops to 0*

**Link(s) to mod(s) used**: *None

**Save file**: *

*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *No crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X
[save.zip](https://github.com/Anuken/Mindustry/files/5739450/save.zip)

https://user-images.githubusercontent.com/62565267/103086664-3c3f8800-45f6-11eb-8dcf-8ed4cba5839a.mp4

] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RebornTrack970** [comment]
I dont think the vid works, here is the discord link for it...
https://cdn.discordapp.com/attachments/663853133587546138/791634945067188244/2020-12-24-14-33-27.mp4

**Comment by Anuken** [comment]
Cannot reproduce.
