### ISSUE TITLE
Combustion generator keeps showing burning animation when disabled

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry#4104]
**Platform**: *Windows 10*

**Build**: *122*

**Issue**: *Combustion generator keeps showing burning animation when disabled.*

**Steps to reproduce**: *Place a combustion generator down, feed it fuel, then disable it via logic processor. Optionally you can remove fuel from it when it's disabled.*

**Save file**: *[ZippedSave.zip](https://github.com/Anuken/Mindustry/files/5739591/ZippedSave.zip)*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
+ steam generator
+ differential generator
+ possibly more
