### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by Blacksail-1** [Anuken/Mindustry#4107]
![Screenshot_20201224-144857](https://user-images.githubusercontent.com/73030706/103095706-7b230d00-45f9-11eb-9e2b-71c716de23b3.png)

**Platform**: *Android/iOS/Mac/Windows/Linux* android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* build is 122  V6 (in beta program as well) 

**Issue**: *Explain your issue in detail.* I completed the map and went to the pause menu and hit save and quit. Game then took me back to the main screen and then an error came up (in screenshot above). When it first happened I thought it was a one off thing (was on the last campaign map for the electromagnetic railgun) but when I cleared this sector and then saved and quit I got the same error with the same code about some dictionary. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* cleared a sector (seems to happen on any) either by surviving a set amount of waves or destroying the core/cores. Go to pause menu and hit save and quit and error should pop up saying it can't be saved. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

https://github.com/QmelZ/Hackustry  

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*  

/storage/emulated/0/Android/data/io.anuke.mindustry/files/saves/sector-serpulo-69.msav

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
None since game was still running after bug was found and didn't boot me to home screen of my device. 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're using a mod that historically caused a lot of problems + no logs + cannot reproduce.
