### ISSUE TITLE
malformed block inventory gui

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4108]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20408`

**Issue**: this can occur:

![Screen Shot 2020-12-24 at 14 36 26](https://user-images.githubusercontent.com/3179271/103098664-e4138080-460b-11eb-80e8-625c62773d6e.png)

**Steps to reproduce**: 

1. put some of any item in a block
2. open the inventory drawer
3. take the items out
4. notice it says 0
5. after a second or so it becomes the above pic
6. and shortly after that it closes entirely

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
verified - have reproduced this bug on multiple occasions
