### ISSUE TITLE
Mass Drivers lose items when save/reload

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4111]
**Platform**: *Windows*

**Build**: *steam 122*

**Issue**: *Mass Drivers lose items when save/reload, if the bullets are airborne, as the bullets do not save. In a map where lots of them are being used, this problem can chip away massive amounts of items. Even one is a lot, since 120 surge alloy is a lot, and for mods with much more valuable items, losing 120 of them is a big yikes.*

*Ideally, make some bullets be able to be saved when `read(Reads read, byte revision, Bullet bullet)` and `write(Writes write, BulletType bullet)` in BulletType is overwritten, so other modded/crucial bullets can also be saved. Why not also a `saves` field?*

**Steps to reproduce**: *Place down 2 mass drivers, and save and load the game as soon as it shoots.*

**Link(s) to mod(s) used**: *null*

**Save file**: *Codewise issue of all bullets being unable to be saved.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
*I am surprised that this was unnoticed. Searching via "mass driver" gave me no identical issues.*

**Comment by Anuken** [comment]
This is intentional and won't be fixed.

**Comment by SMOLKEYS** [comment]
> This is intentional and won't be fixed.

oof
