### ISSUE TITLE
logic rotation sensor and logic draw image rotation input are 90 degrees offset

### ISSUE THREAD

**Issue by MattMills** [Anuken/Mindustry#4113]
**Platform**: Windows

**Build**: 122

**Issue**: 
```radar player any any distance wave1 1 result
sensor rotation result @rotation
op sub rotation_fixed rotation 90
jump 5 greaterThan rotation_fixed 0
op add rotation_fixed rotation_fixed 360
draw clear 0 0 0 0 0 0
draw image 32 32 @gamma 32 rotation_fixed 0
drawflush display1
```

The rotation angle output from the @rotation sensor is 90 degrees different from the draw image rotation input, which seems funky. 

**Steps to reproduce**: Put above logic in processor, attach display and turret, rotate in radar range.

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional. Sprites face up, not right, and are drawn with a 90-degree offset in the unit rendering code as well.
