### ISSUE TITLE
Lost sound after call

### ISSUE THREAD

**Issue by Surviavlist** [Anuken/Mindustry#4114]
**Platform**: Android, HUAWEI Y6 Prime 2018*

**Build**: *122*

**Issue**: *No sounds/music after call.*

**Steps to reproduce**: *Play and get income call, answer the call and back to game. When you will continue you will notice there is no sound and music in game. After this I'm just restarting the game and all is ok.*

**Link(s) to mod(s) used**: *No*

**Save file**: *Everywhere*

**(Crash) logs**: *No crashes.*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix.

**Comment by SMOLKEYS** [comment]
This happens to me but i think i do that because of the handful of sound files running when im overusing something.
