### ISSUE TITLE
Random Loss Of Data

### ISSUE THREAD

**Issue by hwein2** [Anuken/Mindustry#4116]
**Platform**:Windows

**Build**: 121.4 Windows 64-Bit

**Issue**: *When i first opened the game, i went into campaign, all of my secured sectors were under attack, despite there being no enemy bases nearby. They all had 30 waves each, and i had lost all of my tech and progress. I had all of my secured bases still there, everything was still there, but i had nothing unlocked.
![image](https://user-images.githubusercontent.com/76588035/103135053-98191800-46ad-11eb-883d-b2ba2d633bf9.png)
![image](https://user-images.githubusercontent.com/76588035/103135365-c566c580-46af-11eb-9220-09d75de6cf2f.png)

Some of the sectors which i have not yet secured when i spawn in instantly die to 6 daggers on the first wave who are right outside my base .
![image](https://user-images.githubusercontent.com/76588035/103135193-90a63e80-46ae-11eb-8062-47ae9876d69a.png)
![image](https://user-images.githubusercontent.com/76588035/103135335-80429380-46af-11eb-8ea7-bb2db8885a93.png)

**Steps to reproduce**: I don't know. The day before my wifi randomly went out a few times but i don't think that is the cause of it.

**Link(s) to mod(s) used**: No Mods Were Used.
**Save file**: 
[Mindustryzip.zip](https://github.com/Anuken/Mindustry/files/5741971/Mindustryzip.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce this.

**Comment by SMOLKEYS** [comment]
This could be caused by low memory, not enough memory, saves corrupt.
