### ISSUE TITLE
item cost multiplier not applying

### ISSUE THREAD

**Issue by bar0nch** [Anuken/Mindustry#4117]
**Platform**: */Windows*

**Build**: *121.3*

**Issue**: *I made an hard map where i set the build cost multiplier to 3.0 and although the cost display in game was 3x i could still build the blocks at the normal cost.*

**Steps to reproduce**: *I entered the game and tried to build some graphite drills at the cost of 30 graphite and i had 40, despite that i managed to build 12 drills.*

**Link(s) to mod(s) used**: *Vanilla.*

**Save file**: *
[bug.zip](https://github.com/Anuken/Mindustry/files/5742054/bug.zip)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
A build speed multiplier of "9999" is far outside of the accepted range. Requirements do not work properly with such values.
