### ISSUE TITLE
121.2 > 122

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#4118]
**Platform**: *Android/iOS/Mac/Windows/Linux*

windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

122

**Issue**: *Explain your issue in detail.*

i can not use a mod which requires minimum 121.2 on 122
![image](https://user-images.githubusercontent.com/59574967/103136650-35d30e00-46d3-11eb-909a-0d32a78c0213.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. download build 122 jar from releases
2. open the game
3. import the given example mod
4. let the game restart
5. see that the mod got disabled and you cant use it
6. doubt your math knowledge

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

https://github.com/tcookiem/yeeter-mod

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

it happens in the menu

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by zethnest** [comment]
This issue has been fixed by #4100

**Comment by QmelZ** [comment]
cool
