### ISSUE TITLE
construction lines not showing for long range sandbox

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4122]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20419`

**Issue**: when you're outside of normal build range while `infiniteResources` is true the lines don't render: (still builds)

![Screen Shot 2020-12-25 at 20 12 43](https://user-images.githubusercontent.com/3179271/103140959-af77f580-46ed-11eb-8a0e-f4746bb1c729.png)

**Steps to reproduce**: build or deconstruct some stuff outside normal range on a sandbox world.

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
Similar to this issue,
Building lasers don't render if the unit that is building is off screen.
How to replicate
1. Build thing that takes long time
2. Pan cam away from your unit so only the block that your building is on screen
3. haha no more laser for u

**Comment by Quezler** [comment]
or zoom in a lot ^

**Comment by Anuken** [comment]
> Building lasers don't render if the unit that is building is off screen.

This is intentional and won't be changed.

**Comment by Legomonster33** [comment]
> > Building lasers don't render if the unit that is building is off screen.
> 
> This is intentional and won't be changed.

ok fair but

1. it looks bad
2. it doesn't make much sense
