### ISSUE TITLE
plastic belt Roomba loading copper sprite instead of plastanium

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry#4123]
**Platform**: *Win 10

**Build**: 122

**Issue**: dropping plastanium to plastanium belt creates a roomba with copper sprite

**Steps to reproduce**: 
1) make plastic belt
2) grab plastic
3) drop it in plastic belt
4) tadah: https://discord.com/channels/391020510269669376/391020510269669378/792115969924923492

**Link(s) to mod(s) used**: N/A, multiplayer on v122 servers

**Save file**: [evidence.zip](https://github.com/Anuken/Mindustry/files/5742329/evidence.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
ok

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Every conveyor in that save displays the correct sprite, and every conveyor I dump plastanium into also displays the correct sprite.
