### ISSUE TITLE
Rebuilding a processer does not restore the script

### ISSUE THREAD

**Issue by Vlexa** [Anuken/Mindustry#4124]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam 122
**Issue**: *Explain your issue in detail.*
A processer with a script , after destroyed and rebuild by ( poly ) forgets his script. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Microprocessor with a script 
2. Have it destroyed
3. Rebuild automatically with a poly
4. Check logic
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
all mods disabled
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[LogicMissingBug.zip](https://github.com/Anuken/Mindustry/files/5742473/LogicMissingBug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no crashs
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. When the processor is destroyed by an explosion in your map, the contents are saved when a poly rebuilds it.

**Comment by Vlexa** [comment]
it does happen. maybe its related to repeated destruction? or its a race condition? I have tried about ten times to reproduce it. the second time the script stayed. but then it keep disappearing constantly. 

https://youtu.be/UY0u58yiYDY
