### ISSUE TITLE
Adding a sorter to a router slows it down

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#4125]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Steam build 122

**Issue**: Adding a sorter to a router slows it down, this does not apply to overflow/underflow gates, I am not sure if this is intentional or not

**Steps to reproduce**: https://cdn.discordapp.com/attachments/741710209902444554/792175519159812136/unknown.png
Picture of layout

**Link(s) to mod(s) used**: N/A

**Save file**: [
[router sorter slowdown.zip](https://github.com/Anuken/Mindustry/files/5742506/router.sorter.slowdown.zip)
](url)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.
