### ISSUE TITLE
Destruction of a reconstruction in progress loses logic processors script 

### ISSUE THREAD

**Issue by Vlexa** [Anuken/Mindustry#4126]
Platform: Android/iOS/Mac/Windows/Linux
Windows 10
Build: The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.
Steam 122
Issue: Explain your issue in detail.
A processer with a script , after destroyed, started to rebuild  ( poly ) and destroyed  again in progress( poly ) forgets his script.
Not only the script but also the links. 

Steps to reproduce: How you happened across the issue, and what exactly you did to make the bug happen.

1. Microprocessor with a script
2. Have it destroyed
3. Start rebuild automatically with a poly
4. Have it destroyed before its finished.
5. Script lost. 

I got this confirmed by a volunteer. 

Link(s) to mod(s) used: The mod repositories or zip files that are related to the issue, if applicable.
all mods disabled ( rtfm , debugger and debugger support lib ) 
Save file: The (zipped) save file you were playing on when the bug happened. 
LogicMissingBug.zip

Video of its happen on my machine
https://youtu.be/UY0u58yiYDY

**Comment by Anuken** [comment]
fixed

**Comment by SMOLKEYS** [comment]
Anuke just talks so casually lmao 🤣
