### ISSUE TITLE
Maces can get burned while it should be immune from it said from the source code.

### ISSUE THREAD

**Issue by rly4498** [Anuken/Mindustry#4130]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
"release build 122"

**Issue**: *Explain your issue in detail.*
Maces can be set on fire while it should be immune from it said in the source code.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Make a mace, then make it step on a slag tile or be targeted by a slag wave to get burned.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[MaceBug.zip](https://github.com/Anuken/Mindustry/files/5743071/MaceBug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SMOLKEYS** [comment]
> **Platform**: *Android/iOS/Mac/Windows/Linux*
> Android
> 
> **Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
> "release build 122"
> 
> **Issue**: *Explain your issue in detail.*
> Maces can be set on fire while it should be immune from it said in the source code.
> 
> **Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
> Make a mace, then make it step on a slag tile or be targeted by a slag wave to get burned.
> 
> **Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
> 
> **Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
> [MaceBug.zip](https://github.com/Anuken/Mindustry/files/5743071/MaceBug.zip)
> 
> If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
> 
> **(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
> 
> ---
> 
> *Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
> - [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
> - [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
> 

_How does a Mace survive drowning or getting attacked with slag, which is DRASTICALLY hotter than it_

**Comment by rly4498** [comment]
![20201226_211931](https://user-images.githubusercontent.com/68048803/103152157-2382ce00-47c0-11eb-855e-c4f9e339dd24.jpg)

Idk, but it is said in the source code so it should do it.

**Comment by Quezler** [comment]
it probably means the effect won't last when not in direct contact

**Comment by Anuken** [comment]
Slag doesn't burn, it melts. Maces are not immune to melting.
