### ISSUE TITLE
core shard absent in database

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4136]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20427`

**Issue**: core shard doesn't show in core database

**Steps to reproduce**: gaze upon the core database:

![Screen Shot 2020-12-27 at 11 12 08](https://user-images.githubusercontent.com/3179271/103168557-6e3e2d80-4834-11eb-9b9e-dec0d13c4ba0.png)

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by catatagun** [comment]
Thruster needs a core database as wtf is its stats

**Comment by catatagun** [comment]
Same with scrap walls and the sandbox stuff
