### ISSUE TITLE
Multiple ubind statements don't work

### ISSUE THREAD

**Issue by FreelancePoliceman** [Anuken/Mindustry#4137]
**Platform**: Linux

**Build**: Release Build 122

**Issue**: It seems that when "ubind" is called twice in the same processor loop, the second call either fails, or "@unit" still refers to the first bound unit. 

**Steps to reproduce**:

1. Create more than 1 flares.

2. Use this code in a processor (not the most efficient -- a jump could be eliminated, but it seems to be correct) with a message block attached.
```
set u_type @flare
ubind u_type
set unit_id @unit
set num_of_u 1
ubind u_type
jump 8 equal unit_id @unit
op add num_of_u num_of_u 1
jump 4 always x false
print num_of_u
printflush message1 
```

The message will always display "1". The intended purpose is to display the number of units on the map. I'm 99% sure the logic is 'correct' -- I had #logic in Discord look over it before I posted it here, but a thousand apologies if the problem is that my programming is just stupid.

No mods were used.

**Save file**: [bugged_save.zip](https://github.com/Anuken/Mindustry/files/5744403/bugged_save.zip) The processor I used is the one on the right.

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Bind instructions loop counters are not global. Each instruction has its own next bind index.
