### ISSUE TITLE
iOS: Why is ios a paid game when on android it's free!?

### ISSUE THREAD

**Issue by kathool** [Anuken/Mindustry#414]
I am only asking why, do not take it as I don't respect that it isn't free for iOS. Possible Beta? Dev uses Android and doesn't like iOS? Please explain!

**Comment by Anuken** [comment]
Apple charges $100/year to be a developer, and requires buying a $300+ minimum Mac device to publish apps. Publishing to Android is a one-time $20 fee. Thus, I made it non-free to cover my costs and provide a replacement for the donations I get on Android (which don't work on iOS).

**Comment by BLucky-gh** [comment]
Regarding the donations: I've seen an app incorporate donations as in-app purchases to buy "A coffee for the developer."

**Comment by Arkanic** [comment]
@BLucky-gh nobody pays for that kind of stuff tho

**Comment by BLucky-gh** [comment]
That's a point
