### ISSUE TITLE
Game crashes on opening ItemSource config.

### ISSUE THREAD

**Issue by FireWingLead** [Anuken/Mindustry#4140]
**Platform**: Windows

**Build**: steam build 122

**Issue**: Happened while playing a custom sandbox game. Every time I start such a game and attempt to use the Item Source block, as soon as I click on the block to configure it, the game crashes with the following error:
> A crash has occurred. It has been saved in:
> C:\Users\perri_000\AppData\Roaming\Mindustry\crashes\crash-report-12_27_2020_06_02_44.txt
> Null Pointer

**Steps to reproduce**: Start a custom sandbox game, place an Item Source, Click the Item Source. Crash.
This started happening after attempting several tests on a mod in an effort to figure out how to make the game show icons for custom items and liquids in the configuration of a custom block. Methods attempted included `ItemSelection.buildTable(...)` and `myLiquid.icon(Cicon.size)`, as well as `myLiquid.emoji()`. `myItem.icon` and `myItem.emoji` were also tried.
I have uploaded the zip files for the two mods involved. The file/block being tested was "liquid-tanking-depot.js" in the packaging mod.

**Link(s) to mod(s) used**: 
[Gasoline Mod.zip](https://github.com/Anuken/Mindustry/files/5744535/Gasoline.Mod.zip)
[Packaging Mod.zip](https://github.com/Anuken/Mindustry/files/5744536/Packaging.Mod.zip)

**Save file**: Unable to upload a save file. The game crashes before it can be saved.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crash-report-12_27_2020_06_02_44.txt](https://github.com/Anuken/Mindustry/files/5744539/crash-report-12_27_2020_06_02_44.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
22 mods, but only two zips?

**Comment by FireWingLead** [comment]
@Quezler Most of those mods are turned off, and only the two zipped ones are likely to be involved, as this error didn't occur before with any of the current mods active. It only started during the testing mentioned of the packaging mod. The gasoline mod is included since the packaging mod was attempting to display one of the gas mod's custom items and/or liquids as a config option.

**Comment by Anuken** [comment]
One of your mods is broken.

**Comment by FireWingLead** [comment]
@Anuken Can you explain how? If I'm using the API wrong somewhere, I'd like to know.

**Comment by FireWingLead** [comment]
@Anuken Also, as described, it's not a mod item that is broken. It is the vanilla Item Source block. And the game crashes, even when not attempting to use anything from any mod.

**Comment by Anuken** [comment]
> Can you explain how?

No, because you haven't posted specific code.

> Also, as described, it's not a mod item that is broken.

That doesn't matter. It crashes when trying to get an icon from an item. This doesn't happen in vanilla, thus it is a mod problem.

**Comment by FireWingLead** [comment]
@Anuken 

> No, because you haven't posted specific code.

Lol, wut? Yes I did. I said that the mod block being tested before this happened was liquid-tanking-depot.js in the packaging mod. If you want me to be even _more_ specific, it all centers around the method `buildConfiguration(table)` in the extended build type.

**Comment by FireWingLead** [comment]
You'll also find lots of commented out stuff from previous attempts that didn't work there. The current attempt works... kind of. But it double-creates the gasoline Liquid, once properly, and once with some properties being null that shouldn't be, including an "oh no" for its icon.

**Comment by Anuken** [comment]
>  I said that the mod block being tested before this happened was liquid-tanking-depot.js in the packaging mod.

220 lines of code isn't very specific. There's a lot going in that file. Find out **exactly** what makes it happen and what changes you did that lead to a crash.

**Comment by FireWingLead** [comment]
@Anuken Yeah, I wouldn't be posting about a bug if I hadn't already been very **VERY** thorough about that. And you _are_ familiar enough with common-basic modding code structure of your own game to easily find the overridden `buildConfiguration(table)` method in the custom buildType of a block, yes?

**Comment by FireWingLead** [comment]
@Anuken Let me just say, it pains me to be an annoying little prick like this, but I love your game, and i want to learn it inside and out, so as to better contribute to it and its community, and it looks like I need your help with that here if I'm going to get over this wall.

**Comment by Anuken** [comment]
I'm asking for specifics on **what you changed** right before the bug started happening. Not entire files.

> This started happening after attempting several tests on a mod in an effort to figure out how to make the game show icons for custom items and liquids in the configuration of a custom block. Methods attempted included [...]

I'm not going to debug this for you. Show me **the specific line** that, when added, makes the item source crash. If you don't know what that line, undo your changes until you pinpoint it.

**Comment by DeltaNedas** [comment]
please just fix your mod and leave anuke alone

**Comment by FireWingLead** [comment]
He/You say "Do it". I say "I've already done it. Thoroughly". You/He says "Do it. I won't help.".
Did you not hear me? "I'VE ALREADY DONE IT. AND IT DOESN"T WORK."
So fine. I'll do it AGAIN. for the UMPTEENTH time. If it fails (as it will) I'll have to find another pursuit. Maybe even another game. That would be very sad, as I love this game and was having fun with this project, but if that's what happens, then so be it.

**Comment by FireWingLead** [comment]
@DeltaNedas @Anuken OK, let me try explaining my thoughts a little more nicely.
Yes, something in the mod, SOMETHING, is happening that the game can't handle. BUT, it has very clearly become something on the game's side that the game SHOULD be able to check for and handle. I know my mod. You game? Not so much. And even if I did, I don't get to edit or debug your code.
Even if it IS something that needs to be changed in the mod to fix the game, I need help figuring out the weakness in the game, as I've already worked very hard attempting to do this myself from both ends (game to mod and mod to game). So I need help.
Much thanks for making your code visible on github btw. You guys are great for that.

**Comment by FireWingLead** [comment]
I'll keep doing my best to figure things out from this end. I'm just trying to bring this problem to your attention from your end so that you can shore up this weakness and prevent others from having the same issue.

**Comment by Quezler** [comment]
you're not initializing the item(s) correctly since cicon is somehow null, also you should look into this error:
`Two content objects cannot have the same name! (issue: 'packaging-water-drums')`

**Comment by FireWingLead** [comment]
@Quezler Thank you ever so much. I'll look those things in minute detail. There's got to be something there. I'll probably need to find more resources on the proper way to initialize whatever I'm doing wrong. If it turns out to be something that the game could error check for and correct (or notify with a more informative error message) in order to make life easier for modders, I'll let you know.

**Comment by Quezler** [comment]
asking around in the #modding-general channel on discord might also be of some help

**Comment by Anuken** [comment]
>  I say "I've already done it. Thoroughly"

Yet you **have not done what I asked**. 

> Did you not hear me?

This is rather ironic, as I have already told you:

> Show me the specific line that, when added, makes the item source crash. If you don't know what that line is, undo your changes until you pinpoint it.

Waving your hands in the general direction of the `buildConfiguration` function and saying "the problem is somewhere there, figure it out" is ***not what I'm asking for***.

> BUT, it has very clearly become something on the game's side that the game SHOULD be able to check for and handle

*How do you know this?* I can easily crash the game by doing `Vars.control = null` or `Items.copper.color = null`. Yet, neither of those are things that the game should be handling.

> Even if it IS something that needs to be changed in the mod to fix the game, I need help figuring out the weakness in the game

This issue tracker is for game bugs, not modding help.

---

Since you seem intent on bothering us until you get an answer, I loaded up the mods, and was immediately met with the "`Two content objects cannot have the same name! (issue: 'packaging-water-drums')`" error that Quezler posted above. This means that an item **failed to initialize**, making many of its fields `null` and thus unusable by most game code. You're requiring `packaging-water-drums` twice in two different files.

This had **absolutely nothing** to do with the `buildConfiguration` function you kept lecturing me about. In fact, I can remove its whole definition, and the crash still occurs. If you had simply opened the console or checked the program's output, the issue would have become clear. 

Alternatively, you could have gone through your changes and determined whether or not `buildConfiguration` was the real cause of the crash. Instead, you chose to be "*very VERY thorough*" and repeat the same nonsense over and over, wasting everyone's time.
