### ISSUE TITLE
Consumer information UI is w i d e

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4141]
**Platform**: *Windows*

**Build**: *steam 122*

**Issue**: *Consumer information UI is w i d e and breaks everything. See below; this is very likely to happen in modded crafters or modded blocks in block forges or modded forges,*
![image](https://user-images.githubusercontent.com/58885089/103172315-f1dc3680-4895-11eb-9a33-a98883aead63.png)

**Steps to reproduce**: *I encountered this in 2 ways.*
1. make a factory that consumes more than 6 types of items.
2. a java mod(link below) that adds T2 block forge that requires cryofluid

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy*

**Save file**: *UI issue*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
*^ I did not know exactly what keyword to search, so I might have missed a dupe*

**Comment by Quezler** [comment]
block workshop sounds cute

**Comment by sk7725** [comment]
thank you ❤️
