### ISSUE TITLE
Block loader/unloader accelerates payloads at v = 0.9c

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4149]
**Platform**: *Windows*

**Build**: *steam 122*

**Issue**: *When payload is already full, block loader zooms the payload forward. Same is true for unloaders.*

**Steps to reproduce**: *Example setup below:*
![녹화_2020_12_28_16_00_53_687](https://user-images.githubusercontent.com/58885089/103195633-0405b580-4926-11eb-8b6e-d783c8cc71e4.gif)

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy for unlocking the loaders.*

**Save file**: 
[container_accelerator.msav.txt](https://github.com/Anuken/Mindustry/files/5746231/container_accelerator.msav.txt)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
(sorry, wrong button click)

**Comment by Quezler** [comment]
payload goes brr

**Comment by DeltaNedas** [comment]
snek 2.0

**Comment by Quezler** [comment]
fixed in linked pr:


https://user-images.githubusercontent.com/3179271/103205652-516c2d80-48fa-11eb-89b2-f58199748645.mp4

**Comment by Anuken** [comment]
> Block loader/unloader

*These blocks are hidden for a reason.* Any problems you encounter while using them are yours to fix.

**Comment by sk7725** [comment]
> > Block loader/unloader
> 
> _These blocks are hidden for a reason._ Any problems you encounter while using them are yours to fix.

I know, it made it to the issues because I failed to fix it.

**Comment by XxsuperdeadlysniperxX** [comment]
> > > Block loader/unloader
> > 
> > _These blocks are hidden for a reason._ Any problems you encounter while using them are yours to fix.
> 
> I know, it made it to the issues because I failed to fix it.

Big oof

**Comment by Quezler** [comment]
i'm slowly working on a fix, not to worry 👀
