### ISSUE TITLE
crash: bigInteger would overflow supported range

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#4151]
**Platform**: Windows 10

**Build**: 122

**Issue**: 
![image](https://user-images.githubusercontent.com/45698812/103207123-62914c00-48b2-11eb-9dbe-c88387c4ab89.png)

game crashed while I was messing with logic

**Steps to reproduce**: Honestly not sure, I exited out of a processor and then the game crashed

**Link(s) to mod(s) used**: RFTM & Logic Debugger

**Save file**: [sandbox h.zip](https://github.com/Anuken/Mindustry/files/5746776/sandbox.h.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:  [crash-report-12_28_2020_01_54_37.txt](https://github.com/Anuken/Mindustry/files/5746782/crash-report-12_28_2020_01_54_37.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
what code did you try to compile before crashing???

**Comment by Anuken** [comment]
This is a mod problem.
