### ISSUE TITLE
import/export schematics on linux

### ISSUE THREAD

**Issue by bapageGIT** [Anuken/Mindustry#4154]
**Platform**: *Linux  (Mint)*

**Build**: *122*

**Issue**: *Importing a schematic (that i download from discord to my home folder) isn't simple.   if i go to import, i can see my home folder, but it's empty.  What i've found is that it's browsing /proc/cwd/#### and not my home folder.   whenever i launch my game, i have to first export a schematic as something unique, then run a filesystem search for that unique.msch file.   this will tell me the game's working /proc folder.   i then have to copy my downloaded schematics to there, then i can import them into the game. I've attached a screenshot showing how my game sees this /proc/cwd folder, and not my home drive like it claims to.*

**Steps to reproduce**: *I found the issue when my game wouldn't see any of the schematics i downloaded to my home folder.  i've fully patched my system, and it persists after reboot.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

![Screenshot from 2020-12-28 13-50-31](https://user-images.githubusercontent.com/76701544/103234262-9782ba80-4915-11eb-981c-a7d4ae34b3dd.png)

[game-date-export.zip](https://github.com/Anuken/Mindustry/files/5748352/game-date-export.zip)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works on my machine. Mindustry's environment is likely being sandboxed by some other application.

**Comment by DeltaNedas** [comment]
do not use amazon spyware
linux mint 20 explicitly forbids using snap by default, for good reasons.
