### ISSUE TITLE
Sector 103 scrap pile

### ISSUE THREAD

**Issue by catatagun** [Anuken/Mindustry#4159]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
122 build
**Issue**: *Explain your issue in detail.*   scrap in water
![Screenshot_2020-12-28-19-41-14](https://user-images.githubusercontent.com/76461235/103254856-acc70b80-494c-11eb-98c9-0e1e2fd4f7a0.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* go to sector 103 in the campaign

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* cant save a campaign save file without sending data just saves the entire campaign

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.  Anuke no bad anuke. Anuke it is illegal to reap someones soul

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
-  #[x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by catatagun** [comment]
Scrap water = oh no

**Comment by DeltaNedas** [comment]
scrap in water
