### ISSUE TITLE
UI rescale gets triggered too often

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4161]
**Platform**: *Windows*

**Build**: *steam 122*

**Issue**: *The "UI scale has changed, exiting in 15 seconds" is popping up about 1 in 3 times when I start Mindustry.*
Recently this issue arose.
I play with a laptop connected to a monitor via HDMI cable, display setting set to "2nd monitor only", in full screen.

**Steps to reproduce**: *Launch mindustry. Chances are, you will be told that you UI scale has changed, and it will restart automatically. However, even when I press yes or cancel, it keeps doing that too often.*

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy*
I do not think anything is wrong with my mod, except one thing:
```
Core.settings.defaults("slimeeffect", true, "correctview", false);
```
Would this remove all other vanilla defaults, or just work fine without causing harm?

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
Edit: I think this happens when you minimize the window while booting up the game.

**Comment by Anuken** [comment]
Cannot reproduce this. Changed my UI scale, restarted the game multiple times while minimizing a few times - the dialog doesn't pop up.

**Comment by Anuken** [comment]
*Potential cause*: You could be rebuilding the settings UI, triggering a refresh of the UI scale.
