### ISSUE TITLE
[Modding]Painful drill ore indication sprite

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4162]
![Screenshot_20201229-011602](https://user-images.githubusercontent.com/61173114/103270501-4f938000-4975-11eb-8635-7f65b2092a75.png)
**Platform**: *current Android, issue is on all.*

**Build**: *stable 122*

**Issue**: *Drill mining item indicators are only set for 2, 3, and 4 size drills. They display as an oh no on any other size, and they may not be able to override with a custom sprite like turret bases.*

**Steps to reproduce**: 
*Load up K103908/Exotic-Mod* 
*place the giant 7x7 drill*
*profit*

**Link(s) to mod(s) used**: *see above.*

**Save file**: *happens on all clients that can load the mod.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no crashes.*

**Possible fixes**:
*1. make drill item indicator not display if there isnt any set sprite, like unit weapons.*
*2. add custom item indicator overrides like those on turret bases.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I think I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

Screenshot edited in.

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/production/Drill.java#L60

does a `drill-item-7.png` or `giantdrill-item.png` not work?

**Comment by BlueWolf3682** [comment]
drill-item-7 didnt work a bunch of times, due to that old v5 glitch, honestly didnt test custom sprites cause i couldnt find that line

**Comment by BlueWolf3682** [comment]
The sprite has been fixed, but do note that overriding blocks that the basegame calls sometimes is very janky

**Comment by catatagun** [comment]
Oh no
