### ISSUE TITLE
core order in editor wrong

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4165]
**Platform**: `Mac OS X x64`

**Build**: `custom build`

**Issue**: the order of the cores in the editor is reversed from what you'd expect:

![Screen Shot 2020-12-29 at 10 40 24](https://user-images.githubusercontent.com/3179271/103274618-614f4480-49c2-11eb-818e-99ea587c558d.png)

**Steps to reproduce**: open the editor.

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Regression caused by #4084, reverting.
