### ISSUE TITLE
Permanent weather persists even after weather setting is removed in editor

### ISSUE THREAD

**Issue by Fish-Noises** [Anuken/Mindustry#4167]
**Platform**: Windows

**Build**: 122

**Issue**:  In the editor, I set a permanent sporestorm and sandstorm on a map.  I went in-game to edit and the weathers functioned as intended. I then removed the two kinds of weather and went back to edit in-game. I expected the weather to be clear, but they were still ongoing.
When I started a custom game on that map, despite the weather setting being completely clear, the storms were still showing and didn't leave.

**Steps to reproduce**:

1. Enter the Editor and create a new map.
2. Add a sporestorm and sandstorm into the weather settings. Set them to permanent.
3. Enter in-game and exit back to the map's editor interface.
4. Remove both kinds of weather.
5. Enter in-game again. You should see that the weather is still there.
6. Save the map.

**Link(s) to mod(s) used**: 

- DaGamerFiles/classic-music
- DeltaNedas/cliff
- DeltaNedas/pictologic
- DeltaNedas/rtfm
- DeltaNedas/ui-lib
- DeltaNedas/unit-factory

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN [IN-GAME.*]
[Bugged Save.zip](https://github.com/Anuken/Mindustry/files/5750509/Bugged.Save.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Once permanent weather begins, it never ends.
