### ISSUE TITLE
Bug with the electrical system (disappearing)

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/Mindustry#4168]
**Platform**: *android, ((not know working it for Windows))*

**Build**: *122.*

**Issue**: *Abnormal operation of electricity. If you charge this circuit and then turn it off, the electricity supply will stop, although the battery has it*

**Steps to reproduce**: *When I made the scheme, I decided to test its action, as a result, after charging the battery and turning it off, I found a bug. - Random*

**Link(s) to mod(s) used**: **

**Save file**: *I do not consider it necessary, since the bug disappeared after re-entering the game, and I tried the scheme a lot of times, it works as it should*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![8khbU8fNvwk](https://user-images.githubusercontent.com/72934248/103281165-32959600-49e3-11eb-8d95-7957673932f7.jpg)
![YyrOwtiEf2I](https://user-images.githubusercontent.com/72934248/103281222-56f17280-49e3-11eb-902f-c37b9b45dce3.jpg)

**Comment by Quezler** [comment]
maybe link the schematic?

**Comment by DeltaNedas** [comment]
99% sure it reloads the network after a second or so

**Comment by Void-Syrex** [comment]
> 99% sure it reloads the network after a second or so

Lol, how do you do it on your phone?

**Comment by Void-Syrex** [comment]
> maybe link the schematic?

it completely has a connection.

**Comment by Anuken** [comment]
> Save file: I do not consider it necessary, since the bug disappeared after re-entering the game, and I tried the scheme a lot of times, it works as it should

**Save files are required.**

**Comment by DeltaNedas** [comment]
if the bug stopped after reloading and didnt happen again what is the problem, mindustry bugfix ai fixed itself

**Comment by Void-Syrex** [comment]
> if the bug stopped after reloading and didnt happen again what is the problem, mindustry bugfix ai fixed itself

oh, I not know it. Ok, thanks
