### ISSUE TITLE
server list bug

### ISSUE THREAD

**Issue by laok233** [Anuken/Mindustry#4172]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
122
**Issue**: *Explain your issue in detail.*
![image](https://user-images.githubusercontent.com/72604018/103308369-984d4680-4a12-11eb-8a1d-503fc9f3bb5f.png)
![image](https://user-images.githubusercontent.com/72604018/103308661-3e994c00-4a13-11eb-801b-2af6fb066b38.png)

same server shows many times
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i clicked this button and no thing else.
![image](https://user-images.githubusercontent.com/72604018/103308773-8a4bf580-4a13-11eb-9d42-ac2ab3b1b850.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Clicked the button, nothing interesting happened.

**Comment by laok233** [comment]
yes...
