### ISSUE TITLE
Logic cell writes to cell incorrect.

### ISSUE THREAD

**Issue by Vlexa** [Anuken/Mindustry#4174]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam 122
**Issue**: 
While shooting and moving recording the coordinates of the player ship into a cell. The data in the logic cell is corrupted.

**Steps to reproduce**: 
1. Load the savegame. 
2. Click the logic button to switch recording to standby. 
3. Start shooting and keep shooting ( and move if need more coordinates ) to record coordinates
4. Stop shooting ( release mousebutton ) Not moving gives 2 pairs and shows the bug. Moving gives more and shows the pattern better
5. Check the message boxes.  The left one lists the contents of the cell1 in pairs. the other messagebox show a printout of the x,y pairs collected and written to the cell by the right microprocessor
6.See that the outputs dont match! See the corrupted data in the cell. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
all mods disabled
**Save file**: 
[CellWriteIssue.zip](https://github.com/Anuken/Mindustry/files/5752245/CellWriteIssue.zip)

**(Crash) logs**: no crash

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't debug people's logic schematics. Unless you have something more specific than "data is corrupted" to report, this won't be investigated further. Countless schematics have used cells without issues.

**Comment by Vlexa** [comment]
glad i found it. sorry for your inconvenience.
