### ISSUE TITLE
Logic Flag on Unit Missing in UI after Taking Manual Control of Unit

### ISSUE THREAD

**Issue by wongjos1** [Anuken/Mindustry#4175]
**Platform**: `Windows 10 x64`

**Build**: `steam build 122`

**Issue**: If you have a logic processor that assigns flags to units, the flag stops showing in the UI if you take and release control of the unit. Other processors are still able to read the flag value from the unit. 

**Steps to reproduce**: Set up one logic processor using the following code after spawning one dagger on the map
```
ubind @dagger
sensor flagVar @unit @flag
jump 0 greaterThan flagVar 100
ucontrol flag 101 0 0 0 0
```

Hover over the dagger, note that the flag value shows under the dagger's health bar.

Take manual control of the dagger by using control+click. 

Release control of the dagger by respawning in the core. 

Hover over the dagger, note that the flag value is no longer shown.

Build a second logic processor with this code:
```
ubind @dagger
sensor flagVar @unit @flag
print flagVar
printflush message1
```
This processor is able to read the flag value from the dagger and print it to the message output but the UI doesn't show the flag value of the Dagger anymore. 

I'm not sure if it's better to just show the flag or to clear the flag if control of the unit is taken over by something other than the custom logic system, like the player or a command center. 

**Link(s) to mod(s) used**: `[DeltaNedas/rtfm:2.14.6]`

**Save file**: *[logic_bug_save.zip](https://github.com/Anuken/Mindustry/files/5752343/logic_bug_save.zip)*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Hover over the dagger, note that the flag value is no longer shown.

That's not a bug. The dagger is no longer under control by the processor, so the flag stops being shown.
