### ISSUE TITLE
Can't zoom in or out while holding an item to place

### ISSUE THREAD

**Issue by SReject** [Anuken/Mindustry#4177]
**Platform**: Windows 10, steam build

**Build**: Steam Build 122.1 but issue existed in the previous steam release

**Issue**: Zooming in/out doesn't work while holding an item to be placed

**Steps to reproduce**:
1. Rebind zoom in/out keys to +/-
2. Enter any map
3. Grab a conveyor as though you would place it
4. Attempt to zoom in and out using the bound keys

**Link(s) to mod(s) used**: Not applicable

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/5752828/mindustry.bug.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by catsz** [comment]
you don't need to say which keys you binded it to.

**Comment by joshuaptfan** [comment]
The mouse scroll wheel both zooms, and rotates rotatable blocks, with block rotation taking priority. If you wish to zoom while holding a rotatable block, hold Ctrl.

[Details in PR that implemented this](https://github.com/Anuken/Mindustry/pull/1206)

**Comment by SReject** [comment]
> [Details in PR that implemented this](https://github.com/Anuken/Mindustry/pull/1206)

The PR is related to scroll wheel behavior, where it conflicted with rotating & zoom

**Comment by joshuaptfan** [comment]
That PR modified the behavior of the rotate bindings, which default to the scroll wheel. It did not hardcode certain behavior to only the scroll wheel.
