### ISSUE TITLE
Enemy Quad Bombs follow you between zones

### ISSUE THREAD

**Issue by sevenyearsdungeon** [Anuken/Mindustry#4178]
Windows

**Build**: Steam build 122.1

**Issue**: I was in one of my zones being attacked by several Quads (Tier 4 air support, large bomber).  I was flying around near the Quads watching them destroy my base and switched over to one of the other zones.  I believe I had switched after an attack was initiated by one of the Quads, but before the bomb exploded.  As a result in the new zone I just went into, there was an explosion right after loading the zone which destroyed several buildings.  I assume this is the attack from the Quad because of the size and damage of the attack and because there was no other reasonable explaination for the buildings to take damage or be destroyed.

**Steps to reproduce**: I believe the best way to reproduce this would be to have some targets for enemy quads to attack in one zone, then as they are attacking buildings near the player, switch to another zone and see if the bomb explodes in the new zone.

**Link(s) to mod(s) used**: none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[saves.zip](https://github.com/Anuken/Mindustry/files/5753333/saves.zip)

Rebuilding the blast zone (the sector was cleared and not vulnerable to attack so no other explanation for the damage)
![Aftermath](https://user-images.githubusercontent.com/13883137/103336077-dd31a700-4a2b-11eb-92ce-a4403a293bf4.PNG)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Won't fix. This requires incredibly specific circumstances to happen, and there's no simple way to prevent it.
