### ISSUE TITLE
powernode schematic not deploying correctly

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4179]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20449`

**Issue**: when using this schematic the powernodes tend to not connect to (all of) the launchpads:

`bXNjaAF4nC2MCwrDIBBEJ6tNTELJSTyUUSGCUcmH9OyF0rqkLLxhYd5gQk+Qyaweas4vt4UYMTq/2y2UI+QESAzRnMkuuhiHcY5mP/RdnFZvF5OCNVGXcy0YSr78plN2HsAINFUnRnNHC6IKCUHoICBEDana74cPBPrzXf0W3O7wgGjQ8wRBsctfXQKePP8DfaUm4g==`

![Screen Shot 2020-12-30 at 09 03 00](https://user-images.githubusercontent.com/3179271/103338282-290d3c00-4a7e-11eb-9f83-5d36f43370d1.png)
![Screen Shot 2020-12-30 at 09 03 14](https://user-images.githubusercontent.com/3179271/103338285-2b6f9600-4a7e-11eb-8528-63faea7aa6b7.png)

**Steps to reproduce**: 

1. import the above schematic
2. launch wastelands in sandbox mode (has a lot of sand tiles where the drills can be placed on)
3. ensure the launchpad is placable (e.g. via the f8 console or compiling with it visible)
4. place the schematic somewhere (the 8 pumps on the edges aren't important)
5. notice the power nodes aren't connected to the launchpad as they are in the schematic

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> when using this schematic the powernodes tend to not connect to (all of) the launchpads:

The schematic you sent doesn't match the screenshot, and places correctly. Adding redundant connections doesn't change results.

![image](https://user-images.githubusercontent.com/10100000/103358973-eac74b00-4a84-11eb-937a-0e9ef59dfc92.png)

**Comment by Quezler** [comment]
0,o must have copied the wrong one by accident, even though im sure i didn't 👀
