### ISSUE TITLE
Sector "Resources: " info not showing on sectors initiated or conquered after recent update

### ISSUE THREAD

**Issue by Kyrros** [Anuken/Mindustry#4182]
**Platform**: Windows [via Steam]

**Build**: 122.1

**Issue**:  After obtaining a Steam update today (Dec 30, 2020), I added an additional 5 sectors (#97, #173, #215, #216, #221) to my 'conquered' list.  None of those 5 sectors are showing the native 'Resources: ' information either during the assault, or after it has concluded.  The 'Resources: ' information for all the sectors I conquered before the update are still displaying normally.
Deleting and reloading an exported version of the same player profile does not seem to fix this.

**Steps to reproduce**: Initiate an assault or wholly conquer any previously unexplored sector after obtaining Steam game version update to 122.1

**Link(s) to mod(s) used**: N/A

**Save file**:  Only appears to affect overworld map, attaching Player Profile Export instead

**(Crash) logs**: [Game runs normally otherwise]
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kyrros** [comment]
Corrections to above:
1.) Unable to edit issue to remove 'autoformating' of sector numbers into 'issues'
2.) Unable to attach exported player profile to issue as initially planned.

**Comment by Anuken** [comment]
> Unable to attach exported player profile to issue as initially planned.

With no save, I can't debug this. Resource information for newly captured sectors displays fine for me.

**Comment by Kyrros** [comment]
> With no save, I can't debug this. Resource information for newly captured sectors displays fine for me.

File limit is 10MBs - what is the best way to submit a 60MB exported player profile?  What files can I remove to pare it down to a smaller size without removing necessary information?

**Comment by Anuken** [comment]
Remove all screenshots and mods from the folder before exporting data.

**Comment by Kyrros** [comment]
Done, thank you.

**Comment by Anuken** [comment]
The sectors you point out indeed have no resources, but anything I capture myself *in your save* has them.

![image](https://user-images.githubusercontent.com/10100000/103386434-cbeca700-4acc-11eb-9a65-87972111cf42.png)

Resources aren't calculated after the initial launch, so there's no way to debug this.

**Comment by Kyrros** [comment]
Thank you for taking a look at it, and appreciate all you've done with the game!
