### ISSUE TITLE
UI bug due to iOS notch

### ISSUE THREAD

**Issue by KazumaIgarashi** [Anuken/Mindustry#4183]
**Platform**: *iOS14.1/iPhoneXS Max*

**Build**: 122

**Issue**: 
When the iPhone is turned sideways during gameplay, the notch hides part of the UI. It may be a bug that occurs on the entire iPhone with a notch.I will attach an image for easy understanding.
I'm sorry, my English is not good.

I checked "iOS UI inside screen notch #3719", but it still has a bug.

- Confirmation of build number
![1](https://user-images.githubusercontent.com/13061659/103353163-6eb41e00-4aeb-11eb-890a-faa05ede8e5b.jpg)
- The right side of the UI is hidden by a notch.
![2](https://user-images.githubusercontent.com/13061659/103353170-7378d200-4aeb-11eb-9cc4-10487f529a9c.jpg)
- The left side of the UI is hidden by a notch.
![3](https://user-images.githubusercontent.com/13061659/103353171-74a9ff00-4aeb-11eb-869d-9997a3e6f068.jpg)

**Steps to reproduce**: 
1. Launch the game
2. Select a campaign
3. Enter one of the maps
4. Part of the UI is hidden when the iPhone is turned sideways

**Link(s) to mod(s) used**: 
I'm not using mods.

**Save file**: 
Currently, it is not due to save data, so I think it is not necessary, but I will attach it if necessary.

**(Crash) logs**: 
Will not crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
playing with it on the left side seems the least intrusive though 🤔

**Comment by KazumaIgarashi** [comment]
Quezler Thank you for your reply.
That's true, but in the iPhone XS Max environment, the UI scale is small, so I play with a UI size of 125%, but on the tech tree screen it is greatly hidden.
![IMG_0394](https://user-images.githubusercontent.com/13061659/103354306-91940180-4aee-11eb-993c-3537d6b8fd95.jpg)

**Comment by Quezler** [comment]
it appears to have been fixed in the past, not sure if this issue is different or if it has returned: #3719
