### ISSUE TITLE
Resources for Planet Map Launch missing?!

### ISSUE THREAD

**Issue by pkuppens** [Anuken/Mindustry#4185]
**Platform**: *Windows*

**Build**: *steam build 122.1*

**Issue**: *I want to launch from 162 to 158 on Campaign. In the top of the screen, I have about 7k titanium, but upon launch, I can only bring about 762. (This is closer to the amount I have in zone 13 that is in between the two.)*

**Steps to reproduce**: *Occurs also after restarting the game, or even the computer.*

**Link(s) to mod(s) used**: *Does not seem to relate to mods, I had the problem before using any mods.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE 
[mindustry_launch_missing_resources.zip](https://github.com/Anuken/Mindustry/files/5754690/mindustry_launch_missing_resources.zip)
HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** (I let steam do this?!)
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- might be 4182 related, but this report has a savefile

**Comment by Anuken** [comment]
> I want to launch from 162 to 158

You *can't*. It's not an adjacent sector. Only 13 can be launched from:

![image](https://user-images.githubusercontent.com/10100000/103363946-6f689800-4a8a-11eb-813d-e84880be128b.png)
