### ISSUE TITLE
Importing code from clipboard into processor does not reset all state

### ISSUE THREAD

**Issue by Lonami** [Anuken/Mindustry#4189]
**Platform**: Windows

**Build**: steam build 122.1

**Issue**:

1. Place a new empty micro processor (or any of its upgraded variants).
2. Place a message.
3. Connect the two.
4. With the processor selected, click on the "Edit" icon, then the "Edit..." button, then the "Import from Clipboard" button with the following contents:

```
set x 10
print x
printflush
```

5. Observe how the `message1` now displays "10".
6. Now, repeat step 4 again but with the following contents instead:

```
print x
printflush
```

7. Observe how the `message1` still displays "10" and not "null".

I would expect all variables to be cleared after importing a new program, **specially** the `@counter` variable. I believe I'm running into issues because of this (if I paste a small program into a new processor, all is good. Large program into new, all is good. Moving from small to large causes issues, presumably because some variables were left in between).

**Link(s) to mod(s) used**: No mods are used.

**Save file**: To trigger the issue, some interaction is needed (pasting different things); the save file is a static snapshot and won't really showcase the bug. Please let me know if you would still like it  though.

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I would expect all variables to be cleared after importing a new program,

They're not supposed to be. In many cases, you will be making incremental changes to a program, and in that case, I see no reason to clear variables.

> specially the @counter variable

It **is** cleared.

**Comment by Lonami** [comment]
> In many cases, you will be making incremental changes to a program, and in that case, I see no reason to clear variables.

With the UI editor, I can understand it, as it's kind of a REPL. But if I'm using the clipboard import (the closest equivalent to running code from a local script file), no state is preserved between runs. I do not know of any programming language that preserves the state of in-memory variables across restarts by default.

Would you consider this change a feature request instead? Maybe we could gather more feedback before closing this so promptly?

> It **is** cleared.

Not from what I'm experiencing? I will try to provide an example at a later time. Do you consider this a different bug or should I update about it here?

**Comment by Lonami** [comment]
> In many cases, you will be making incremental changes to a program, and in that case, I see no reason to clear variables.

Another argument against this, I see this as making the incremental changes worse, not better. With this behaviour, when pasting a new program, I need to **also** consider the old program, how far it ran, and what values it stored up to that point, which is really difficult given the speed at which instructions are executed, and near impossible as soon as you add conditional jumps.

On the other hand, if I make incremental changes *to my code* (as I would with any other programming language) and have it start from scratch, I know exactly what it will do. If I want to persist something between runs, I will use a memory cell, much like I would use a disk file with other languages.

**Comment by Anuken** [comment]
> But if I'm using the clipboard import (the closest equivalent to running code from a local script file), no state is preserved between runs.

If you're editing a script and importing it multiple times in-between edits, I don't see how that's any different from preserving variables in the UI editor.

Regardless of whether it's useful for you or not, this was an intentional feature. It's not a bug. Resetting all the state every time you import a script isn't necessarily the best solution.

> It is cleared.

...nevermind, I double-checked and it's not.

**Comment by Lonami** [comment]
> If you're editing a script and importing it multiple times in-between edits, I don't see how that's any different from preserving variables in the UI editor.

Our opinions differ here, but I can respect that.

> Regardless of whether it's useful for you or not, this was an intentional feature. It's not a bug. Resetting all the state every time you import a script isn't necessarily the best solution.

Do you think it would be a good idea to create a "Reset" or "Clear" button? I was surprised to see it didn't exist, so unless I'm missing something obvious, I could open a feature request in the other repository for this if there isn't one yet.

> ...nevermind, I double-checked and it's not.

Should this bug be reopened and repurposed to track that or should I open a new report (assuming you consider it a bug)?

**Comment by Faith001** [comment]
Could adding a new instruction that resets state fully between runs be good middle ground? 
That way you can start your program with it and not worry about it, while keeping the default intended behavior and not impacting anything else.

**Comment by Anuken** [comment]
> Should this bug be reopened and repurposed to track that or should I open a new report (assuming you consider it a bug)?

Not sure if that should be "fixed" either. The same code is used for both importing code and editing it in the UI, so removing counter persistence would partially reset any edits of code in the UI, which is undesirable.

**Comment by joshuaptfan** [comment]
> Could adding a new instruction that resets state fully between runs be good middle ground?
> That way you can start your program with it and not worry about it, while keeping the default intended behavior and not impacting anything else.

Since @counter is currently not reset on clipboard import, that would pointless, since it's unlikely that @counter would happen to be at wherever you chose to put the reset instruction.

**Comment by DeltaNedas** [comment]
simple solution is to add a reset button, if you want to reset it then you can

**Comment by Lonami** [comment]
> The same code is used for both importing code and editing it in the UI, so removing counter persistence would partially reset the state after any edits of code in the UI, which is undesirable.

Do people in the UI really rely on `@counter` persisting? I can't imagine how one would be capable of keeping track of how many instructions have run so far after closing the UI for a split second to have the processor run before editing it again.

Could someone provide an example use case where persisting `@counter` is useful or desirable?

Storing `@counter` in a variable or cell and later reusing it makes it basically impossible to edit a program without having to rebuild the entire processor.

> Since `@counter` is currently not reset on clipboard import, that would pointless

Faith's suggestion was under the assumption `@counter` was reset, which we later found out is not. If `@counter` is reset, this is the best option for those oḟ us who want pristine state every run.

> simple solution is to add a reset button

See my previous post https://github.com/Anuken/Mindustry/issues/4189#issuecomment-752788868. I think this would be a good addition, but not necessary was `@counter` reset.

**Comment by Lonami** [comment]
If I'm understanding the code correctly, this is where the counter would need to be reset, right?

https://github.com/Anuken/Mindustry/blob/5b163d78432bffdf5d5b67679305203519231065/core/src/mindustry/world/blocks/logic/LogicBlock.java#L288

Would you accept a patch if I were to fix this issue (counter not reset)?

**Comment by Anuken** [comment]
> Could someone provide an example use case where persisting @counter is useful or desirable?

1. Open the logic processor UI.
2. Close it.
3. The counter is now reset, which will force a re-run of any code in the processor. Not good.

**Comment by Lonami** [comment]
Thanks, that covers the case of viewing the code, but not editing it. If you edit it, how are you supposed to know where it will resume, or at which point it is currently?

What if state is reset on any code changes but kept if no changes are made?

**Comment by Anuken** [comment]
I made the logic editor skip configuring the processor when no changes are made. I *could* go ahead and remove the processor variable persistence code so it is cleared every edit or import.

**Comment by Lonami** [comment]
I see, the relevant commit seems to be https://github.com/Anuken/Mindustry/commit/c4d72eef39db34cff6931a585e529c75dae700b7 along with a few drive-by changes.

> I *could* go ahead and remove the processor variable persistence code so it is cleared every edit or import.

I would very much appreciate this, and would make the linked suggestion unnecessary as well. If the change is made, please let me know so that I can close https://github.com/Anuken/Mindustry-Suggestions/issues/1702 too.

**Comment by Lonami** [comment]
https://github.com/Anuken/Mindustry/commit/2ae864f4d385f032f79424c3d0c44c960b693332 (properly) closes this and the suggestion. Thanks for the change!
