### ISSUE TITLE
Plastanium conveyor ends visually connect to armoured conveyor sides despite not being able to load into them

### ISSUE THREAD

**Issue by Axzye** [Anuken/Mindustry#4191]
**Platform**: Windows

**Build**: 122.1

**Issue**: The end of plastanium conveyors visually connect to the side of armoured conveyors, but they cannot unload into them.

**Save file**: 
(https://github.com/Anuken/Mindustry/files/5756151/flat.zip)
example
(https://user-images.githubusercontent.com/74650047/103388944-09e6db00-4b60-11eb-82c3-6172d7ef8ee5.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
this wont be fixed - StackConveyor is a mess already trying to account for existing and anuke has said it wont be fixed a couple times already

**Comment by Anuken** [comment]
duplicate
