### ISSUE TITLE
Game crashes and closes while or after loading and steam says it is still running.

### ISSUE THREAD

**Issue by Smartasskilling** [Anuken/Mindustry#4193]
**Platform**: *Windows (Steam)*

**Build**: *6.0 Build 122.1.*

**Issue**: *Game crashes just after launch. Game crashed while loading the moment it went trough full screen. I bought and played the game trough steam for about 40 minutes. I was in the first level when the game suddenly crashed after 40 minutes of play. I tried various fixes and got the game to go into title screen and it immediately crashed. I think it has something to do with full screen play. I have a weird problem where steam says the game is still active and pressing stop through steam doesn't do anything. I can resolve this by restarting my pc, but the moment the game crashes again it gives the same error. The game doesn't show up in my task manager either and I think it isn't running like steams says it is.*

**Steps to reproduce**: *Every time I start the game it crashes and steam shows it's still active and can't close it. It crashed on full screen, I then disabled steam full screen community and it crashes at the title screen now.*

**Link(s) to mod(s) used**: *None.*

**Save file**: [sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/5757195/sector-serpulo-15.zip)

**(Crash) logs**: [last_log.txt](https://github.com/Anuken/Mindustry/files/5757197/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
"assing", why do i see "assing"

**Comment by Smartasskilling** [comment]
Please elaborate on "assing". Where did you see "assing"?

**Comment by Anuken** [comment]
That's not a **crash** log. It contains no relevant information.
