### ISSUE TITLE
Can’t place drill in the tutorial

### ISSUE THREAD

**Issue by mrblackhayate** [Anuken/Mindustry#4197]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *I Can’t place a drill on Map in the tutorial*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
tutorial?

**Comment by mrblackhayate** [comment]
When you start the campagn

**Comment by itcannotbe** [comment]
Is it me imagining things or OP didn't even bother attaching the save file nor providing the steps to reproduce the bug.

Heck there isn't even a screenshot of the alleged bug.

**Comment by DeltaNedas** [comment]
poor anuke

**Comment by willis936** [comment]
It’s the same issue as this:

https://github.com/Anuken/Mindustry/issues/4199

No save file needed.  Issue is reproducible without a save file.

**Comment by mrblackhayate** [comment]
> It’s the same issue as this:
> 
> #4199
> 
> No save file needed. Issue is reproducible without a save file.

And what can i do ??

**Comment by willis936** [comment]
Open an issue describing the issue (done as soon as the update went up) and wait for another update that fixes the issue.

Anuke’s usually fast about important fixes, but Apple is slow.  I’d expect 1/2 or 1/3.

**Comment by Anuken** [comment]
This was fixed a while ago, but something happened to the deployment system, and a broken version was released.

Submitted a new version. Wait a few days for approval.
