### ISSUE TITLE
Diagonal mirror doesn't mirror properly.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry#4198]
**Platform**: *Windows*

**Build**: *build 122.*

**Issue**: *The editor does not mirror correctly on diagonals with rectangular maps. Minor bug but I assume its easy to fix.*

**Steps to reproduce**: 
*Step 1:* Make a small rectangular map.
*Step 2:* Put something on the map.
*Step 3:* Go into generation and use a diagonal mirror.
*Step 4:* Observe that the mirror isn't correct, and is off by one tile in both the x and y direction. Picture provided for reference.
![image](https://user-images.githubusercontent.com/62061444/103415737-5274b780-4ba5-11eb-9640-4e80dc5f2a03.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That is not a valid map.

**Comment by TranquillyUnpleasant** [comment]
The bug occurs on base vanilla clients as well and has been around for about half a year, no one noticed since its so minor but i just checked an old v5 client and it still has it.

**Comment by TranquillyUnpleasant** [comment]
And i just downloaded the base vanilla client and made a map, still has the same issue, it lets you go down to whatever size so you cant say the map is not valid, its literally made in a vanilla client.
![image](https://user-images.githubusercontent.com/62061444/103483645-7edd3d80-4e0a-11eb-8bb0-a34f2e31b902.png)

**Comment by Anuken** [comment]
> it lets you go down to whatever size

No, it doesn't.  *My* vanilla client doesn't let you go down to anything below 50x50. 

Second of all, **I can see that you are using a mod in that screenshot.** The cliff button is not a vanilla feature. How about you go and check your list of mods before wasting my time these claims?
