### ISSUE TITLE
I can't interact with anything on the map

### ISSUE THREAD

**Issue by mrblackhayate** [Anuken/Mindustry#4199]
**Platform**: `iOS x32` iPhone11 iOS 14.3

**Build**: `6.122.1

**Issue**: When i start campagn, I can't interact with anything on the map, just with menus 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**:

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by willis936** [comment]
Same issue in iOS 122.2.  I tried with an existing campaign and fresh sandbox map.

**Comment by GingerWrangler** [comment]
I am also having this issue,  this morning I updated from 6.121.4 to 6.122.1 on iOS. As stated above, you cannot interact with anything on the map. This includes campaign , custom and sandbox. I noticed that you could build in the editor but not when you try and edit in game.

**Comment by rootrezben** [comment]
> **Platform**: `iOS x32` iPhone11 iOS 14.3
> 
> **Build**: `6.122.1
> 
> **Issue**: When i start campagn, I can't interact with anything on the map, just with menus
> 
> **Steps to reproduce**: _How you happened across the issue, and what exactly you did to make the bug happen._
> 
> **Link(s) to mod(s) used**: `none`
> 
> **Save file**:
> 
> **Crash report**: _The contents of relevant crash report files. REQUIRED if you are reporting a crash._
> 
> _Place an X (no spaces) between the brackets to confirm that you have read the line below._
> 
> * [x]  **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
> * [ ]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

This error started right after updating to the latest version. Changing control scheme had no effect. Starting new game had no effect. No config changes had any effect.

**Comment by Matthew-McRaven** [comment]
Encountered the same issue. I can't place items, nor can I mine manually.

**Comment by Sanya2907** [comment]
Same. Why did anuke close this?

**Comment by Quezler** [comment]
because its a duplicate.

**Comment by rkduke** [comment]
Same problem here on ios
