### ISSUE TITLE
[Android] Conveyor tunnel don't work

### ISSUE THREAD

**Issue by Naheulf** [Anuken/Mindustry#42]
In Android version, item don't enter into conveyor tunnel.

**Comment by Luxray5474** [comment]
Are you sure you placed them in the correct orientation? Please send a screenshot.

**Comment by Tener** [comment]
Works for me on Android, but demonstrates an issue: it is non-obvious how
to connect them. Perhaps extending the tutorial would work.

**Comment by Naheulf** [comment]
I place it like conveyor: orange line pointing to the next element.
![mindustry_2](https://user-images.githubusercontent.com/14990967/34464185-f51301b2-ee75-11e7-82cb-08950003cef7.png)
![mindustry_1](https://user-images.githubusercontent.com/14990967/34464186-f5348152-ee75-11e7-89bb-7fc9a7ad5d49.png)

**Comment by Naheulf** [comment]
After read yours posts I understand:
- Conveyor tunnel "input" must point to the opposite direction of "output" :dizzy_face:.
- Conveyor tunnel "input" and "output" only depends if other side can extract item.

Can you change preview overlay like this:
![mindustry_idea](https://user-images.githubusercontent.com/14990967/34464333-af2a2626-ee7a-11e7-9ce3-daa530334b30.png)
