### ISSUE TITLE
Launch to sector didn't send resources

### ISSUE THREAD

**Issue by whio** [Anuken/Mindustry#4202]
**Platform**: Android

**Build**: 122.1

**Issue**: I started the game and launched to sector 75, from Ruinous Shores. I checked the storage on Ruinous Shores and it had 12k copper and lead, the maximum for the core in that sector (Foundation surrounded by 10 containers). I selected 4000 copper and 4000 lead as resource load out. When sector 75 loaded up, there was no animation of the core landing, instead it was already present with the ship out as if I was continuing an existing sector, and I had no copper or lead. I checked the storage on Ruinous Shores and it was now at 7k/7.1k, matching the resources I tried to launch.

Possibly relevant is that I had previously launched to that sector with only a core and no extra resources, just to explore. It seems like that map was saved somehow and wasn't deleted when the sector was lost.

**Steps to reproduce**: Unknown

**Link(s) to mod(s) used**: None

**Save file**: #
[resources missing.zip](https://github.com/Anuken/Mindustry/files/5758098/resources.missing.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. Launching to a sector preserves resources, as does losing the sector and launching to it again.

**Comment by Yell245** [comment]
I have this bug too. I lost on Mushroom hills (1st enemy base) and Overgrowth. Then I launched and there was no resources with lower-tier core. I think it's because game somehow doesn't save map after losing on it

**Comment by Wantechfan** [comment]
Hold up, Mushroom hills? Earliest enemy base is known is Fungal Pass and 210 (or Infested Canyons in V8)
