### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by wwyatt2112** [Anuken/Mindustry#4205]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *Explain your issue in detail.*
I can’t place anything when trying to build. I’ve deleted and redox loaded the app, deleted all game data, and started my phone. 
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by CodeSturgeon** [comment]
I think I am experiencing the same issue. After the most recent iOS update, all touches on the map lead to panning the map. This masks all other touch based interactions, like placing buildings, interacting with structures, or dragging select boxes.

This is happening on campaign as well as custom maps.

**Comment by WiryFireFlame** [comment]
Had this too I was playing in 122.1 before before I realized there was a new update, and since I’ve done it I can’t play anymore

**Comment by XEN0PHIL** [comment]
![image](https://user-images.githubusercontent.com/55051135/103437325-50f3cf80-4c37-11eb-8c82-2e09f7185bf1.png)

**Comment by Sanya2907** [comment]
Yes! It happens to me too.

**Comment by Sanya2907** [comment]
Anuke messed up something on 122.2

**Comment by skelitonlord** [comment]
https://drive.google.com/file/d/1LqQCkpoEAcgePSSAJOhUnkn3GYTgdj21/view?usp=drivesdk

Here's a link to a save with said issue. iPad won't allow me to upload the file

**Comment by Anuken** [comment]
Already report twice, wait for Apple to approve the update.
