### ISSUE TITLE
Incorrect behavior for jump "==" and "not" instructions involving one null input.

### ISSUE THREAD

**Issue by InvalidError404** [Anuken/Mindustry#4206]
Whenever a null and a non-zero numeric value are involved in a jump "==" and "not" operation, the behaviors are inconsistent with the correct behavior of op "==" and "not".

printflush message1
set a 1
op equal result a b
print "a="
print a
print ", b="
print b
print "\nop a == b : "
print result
jump 12 equal a b
print "\njump a == b : 0"
end
print "\njump a == b : 1"

![Mindustry Jump Bug](https://user-images.githubusercontent.com/60593448/103432625-0f6c1180-4bb0-11eb-8086-0e71784ca8cd.png)

Expected result: jump "==" and "not" should have the same correct outcome as op "==" and "not".

**Comment by Anuken** [comment]
Template.
