### ISSUE TITLE
English to PT-BR does not change the language of the tutorial.

### ISSUE THREAD

**Issue by Prynpo** [Anuken/Mindustry#4208]
**Platform**: `Android 27`

**Build**: `release build 122.1`

**Issue**: *When I start a new game, even though the language is set to PT-BR, the tutorial keeps in English.*

**Steps to reproduce**: *Start a new game in campaign mode.*

**Link(s) to mod(s) used**: `none`

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
The [tutorial localization text](https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle.properties#L1261) has moved in 6.0, but [the PT-BR localization](https://github.com/Anuken/Mindustry/blob/044fb30b1b7ab26bf9e9ea97c9152ed4d68e08f0/core/assets/bundles/bundle_pt_PT.properties#L1181) has not been updated.

**Comment by Quick-korkc** [comment]
This is not bug
The bundle for hint still not completed yet
Close this issue
