### ISSUE TITLE
Не нападают воздушные войска во время игры и при этом командный центр в режыме атаки, как решыть?

### ISSUE THREAD

**Issue by Creater3d** [Anuken/Mindustry#4209]
**Platform**: `Windows 7 x64`

**Build**: `release build 122`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheSlaylord** [comment]
Лучше закрой это сам, либо за тебя это сделает Анюк.

**Comment by Yell245** [comment]
Пиши на английском, Господи. Какой у тебя режим игры? Атака? Если да, уничтожил ли ты вражеское ядро? Если да, то серая команда - нейтральная. На неё нельзя нападать

**Comment by XxsuperdeadlysniperxX** [comment]
Bruh legit nothing in the request
