### ISSUE TITLE
Diagonal mirror doesnt really work

### ISSUE THREAD

**Issue by MrByars** [Anuken/Mindustry#4212]
Platform : Android

Release Build 122.1

When you try to mirror something diagonal, it mirrors it to up 

![Screenshot_20210101-161312_Mindustry.jpg](https://user-images.githubusercontent.com/69898246/103439319-ecdc0600-4c4c-11eb-8796-10b54ab15395.jpg)

I put that black thing on bottom of  the map, and then I tried to mirror it to right, mirror tool mirrored it to up, I tried every mirror position, there is no way its mirrors diagonal.

I was using DeltaNedas/cliff mod, but this issue still happens when I turn the mod off or delete it, so it's not about the mos

Issue happens in Map Editor

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional behavior.
