### ISSUE TITLE
Logic processor enabling linked blocks it shouldn't be

### ISSUE THREAD

**Issue by ksf** [Anuken/Mindustry#4213]
**Platform**: Steam/Linux

**Build**: Steam build 122.1

**Issue**: In the following semi-minimal example (seriously, I reduced it), what should happen is all linked blocks but the cryo mixer being disabled, while what happens (after some time) is everything but the message box being enabled. I can't for the life of me imagine how that could be the right behaviour under any remotely sane semantics. The code, for quick reference:

```
set iter 0
getlink block iter
control enabled block 0 0 0 0
op add iter iter 1
jump 1 lessThan iter @links
set state 0
print "init"
printflush message1
print "setstage 1"
set state 1
control enabled mixer1 1 0 0 0
jump 7 always x false
```

**Steps to reproduce**: I came across this designing an auto-starting impact reactor schematic, when trying to bootstrap a differential reactor / cryo mixer from battery/solar panel all the impacts and their cryos also got enabled, defeating the purpose.

As the original print is unwieldy (it's in the save, though, one of those with two differentials) I minimised things a bit. Thus,

Paste the following blueprint:
```
bXNjaAF4nGPgYGBnYmDJS8xNZWBLKk1PT01h4E5JLU4uyiwoyczPY2DgYuAvTyxJLdJNrSgpSkwuyS9i4E8uqsxPyynNTNHNzaxILWIQS8lMS0stSs0ryUzM0U1PzUstSgQp5CrILwfqzMtPSWXgKM3LyU9MAarmLs7PSSzSLUjMS81h4E7KSSwugZrDnpRYArSqkoE9N7W4ODE9lYE/NzO5KF+3oCg/GSgCNJKBQQCIGRgZwIAVxGJkYGZgZgISQAaQxcDCwfT/L5DD9P8/EwsDCwMzUBU/I4jFAmaxArUxMTCwASlmBiZ2BhAfKMnGwASk+RhBLFYwCxg2DEwsjAxcxaklxSVA5ygYAtWxww1kBxvIy8gJZLHyAZ1zpWJO6oTAvEMGPG2HuWcVca1WV9jz4ZRiGePlXaoT1EIfZd2dW864rC9BSsAjeInH/vr6b/PXTAmy75TQCW7pfdcx92u6xY6A+dMXrWt+LiEz4Xjz4meJuacuJjLkzGrSn35x+Ub5Aw2Lp9j1v/CurJef/aU2NClFqKTjmnHIteh1XRl3Z/Rd4O6QnZnebNBUwrKs6vHZ/Ql752pI3YyZpGtY1vCOe7+wz4VF3kue7s3eqrf2p3n81GWdytdkXOKP1L7M3fck8uT0iq4dPza/OJT3OfRGf3rI0k/3eXs3lJ9mBADujrDJ
```

Then wait a bit, the behaviour described in "Issue" should arise. Note that during waiting things actually are disabled so this isn't a race condition based on links not being established yet while the disable loop is running, or something of the sort.

Gazing into my crystal ball: I noticed that in that particular print, the message box is the only thing not connected to the power grid. At least when eyeballing things.

**Link(s) to mod(s) used**: N/A

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/5758966/save.zip)

---

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
If you don't actively disable a block, it will enable itself after a while.

**Comment by ksf** [comment]
I see the point of that when it comes to blocks which aren't linked to any processor to avoid things getting stuck, not so much when it comes to blocks which *are* connected, but won't belabour the point it's your game.

However, this *definitely* should be documented somewhere. Heading over to DeltaNedas/rtfm for a bit...
