### ISSUE TITLE
Parallax Does No Damage

### ISSUE THREAD

**Issue by gonglinyuan** [Anuken/Mindustry#4214]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam build 122.1

**Issue**: *Explain your issue in detail.*
I built five Parallaxes in Stained Mountains map of the campaign. They are supposed to do 18dps * 5 that can easily kill enemy air units around wave 10. However, I saw the tractor beams of Parallaxes hit the enemy bombers but those enemy air units kept bombing me for minutes. After I built another Scatter around that place, the enemy bombers were shot down immediately.  

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Build Parallaxes in the Stained Mountains map of the campaign and wait until wave 10.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[saves.zip](https://github.com/Anuken/Mindustry/files/5758994/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
parallaxes dont work like meltdowns, they deal 18 damage per second not per 5 ticks

**Comment by Anuken** [comment]
Parallaxes are useless against armored enemies.
