### ISSUE TITLE
Can’t build 

### ISSUE THREAD

**Issue by frisk5653** [Anuken/Mindustry#4217]
**Platform**: iOS

**Build**: *The build number under the title in the main menu. Required. 122.2

**Issue**: every time I go into a game I can not build or interact with the environment of the game 

**Steps to reproduce**: *How you happened across the issue: I think it was an update but I just loaded it up one day and it happened 

**Link(s) to mod(s) used**: none

**Save file**: *[https://drive.google.com/file/d/1ioJR_8Y492Pm_ULbn_EvQayNVjRiSnHn/view?usp=drivesdk](https://drive.google.com/file/d/1ioJR_8Y492Pm_ULbn_EvQayNVjRiSnHn/view?usp=drivesdk) 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by KazumaIgarashi** [comment]
#4205
