### ISSUE TITLE
I can’t do anything. I can’t build, I can’t destroy and I can’t even click structures to check the status. 

### ISSUE THREAD

**Issue by godoen** [Anuken/Mindustry#4219]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
#4205 #4215 #4216 #4217

Please do a search to see if your issue has been reported before submitting a new issue.

**Comment by godoen** [comment]
I don’t see any of same issue reported on the internet

2021년 1월 1일 (금) 오후 8:28, Joshua Fan <notifications@github.com>님이 작성:
