### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by josst28** [Anuken/Mindustry#4220]
**Platform**: `iOS`

**Build**: `release build 122.2`

**Issue**: *I can’t build or touch anything ingame except for the menu button.*

**Steps to reproduce**: *I am not sure at all how it happened, but it didn’t get fixed even if I save and quit or leave game.*

**Link(s) to mod(s) used**: `none`

**Save file**: * https://www.dropbox.com/s/6xmixt6edncbr2z/mindustry-data-export.zip?dl=0*

**Crash report**: * I can’t build or touch anything ingame except for the menu button.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
#4197 #4199 #4205 #4215 #4216 #4217 #4219

Please do a search to see if your issue has been reported before submitting a new issue.

**Comment by joshuacook** [comment]
If the issue remained open until the App Store accepts the fix it is likely that you would receive less bug reports.

**Comment by josst28** [comment]
After I searched I didn’t found anything, except for “wait until Apple
approves the update”. You or anuken said that the problem has been fixed,
but if some people continue to reply it maybe it’s because you or anuken
did something wrong. Well, I say that but I don’t know what you’ve done or
not. Just trying to get sure that it will be fixed because I love play
Mindustry.

**Comment by joshuaptfan** [comment]
You're having trouble searching because most people who submit an issue name them poorly. However, I am still able to find plenty of relevant reports by searching for "is:issue ios" and "is:issue build", after removing "is:open" of course since no issues are open.

**Comment by Lorindal** [comment]
> Let's see how long this conga line can keep going...

Having an open issue on this since the resolution isn’t available on iOS would likely prevent continued bug reports.

**Comment by DeltaNedas** [comment]
if apple really cared they wouldnt take a week to approve a hotfix for a gpl app

**Comment by markozajc** [comment]
if apple really cared they wouldn't charge people to publish foss software
