### ISSUE TITLE
Prb

### ISSUE THREAD

**Issue by latruitede1850** [Anuken/Mindustry#4221]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *[FR] je n’arrive pas à toucher la zone de jeu. Je ne peux plus miner en manuel ou toucher une ressource pour savoir se que c’est. Je peux sélectionner un bâtiment à construire mais je ne peux pas le poser sur le sol.*

**Steps to  : cela fait 2 jours que c’est devenu anormal. Avant tous marchait bien et lorsque j’ai voulu lancer une nouvelle partie, le problème est apparue.
Redémarrer l’application et le téléphone ne change rien

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
#4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220
