### ISSUE TITLE
Game is not working

### ISSUE THREAD

**Issue by godoen** [Anuken/Mindustry#4224]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *Explain your issue in detail.*
I can’t build, destroy and check the status of the structures. My unit is following when I move my screen but except that, I can’t do anything. Sorry for the previous issue report, I didn’t know how to do it.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I restarted my iphone already and shut down the app and turned it back on again already too. But still not working. 

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE 
Please understand me, I don’t know how to upload the file directly. So I shared the link of the data in my google drive.
https://drive.google.com/file/d/1lNYtLUtHiWt85ufkBXPk4P-hu_sTNpQG/view?usp=drivesdk
> HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
Sorry, I can’t find the crash report file in my mindustry app. 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by godoen** [comment]
https://drive.google.com/file/d/1MwIFh5ZM40roO4s5hqvE-ljOpBbl_hmo/view?usp=drivesdk
I found the issue report!

**Comment by Anuken** [comment]
> I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
 I have searched the closed and open issues to make sure that this problem has not already been reported.

You have done neither of these things.

**Comment by joshuaptfan** [comment]
#4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220 #4221 #4223

Please do a search to see if your issue has been reported before submitting a new issue.

**Comment by godoen** [comment]
Thanks!
