### ISSUE TITLE
I can’t build anything in my game:(

### ISSUE THREAD

**Issue by LAURENT12345** [Anuken/Mindustry#4228]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: I open my game and it won’t let me build anything

**Steps to reproduce**:I didn’t do anything,i just open my game and it’s happens 

**Link(s) to mod(s) used**: `none`

**Save file**: *Glacier Jan 01 12:57

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quick-korkc** [comment]
>[x] I have searched the closed and open issues to make sure that this problem has not already been reported

There already lot of report about this, close this

**Comment by joshuaptfan** [comment]
#4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220 #4221 #4223 #4224

**Comment by markozajc** [comment]
another person opened the same issue three goddamn hours before you you silly man

**Comment by Lonami** [comment]
> another person opened the same issue three goddamn hours before you you silly man

GitHub lets you pin issues in repositories. Maybe it would be a good idea to pin those that produce a high volume, like "can't build" ones.

**Comment by Zip-Zap10545** [comment]
في الأحد، ٣ يناير ٢٠٢١ ١٠:٥٨ م Lonami <notifications@github.com> كتب:

**Comment by markozajc** [comment]
@Lonami note both of the ticks at the footer of the issue body

**Comment by Lonami** [comment]
Yes, but note how people ignore the template. The pinned issue is more visible. In any case it was just an additional suggestion that may help control the flood of issues.

**Comment by markozajc** [comment]
yeah something makes me doubt that the same people who take their time to tick the two checkboxes while not even doing what they're supposed to do would notice the pinned issues
