### ISSUE TITLE
Spectre doesn't hit flying bosses

### ISSUE THREAD

**Issue by FruitcakeElemental** [Anuken/Mindustry#4229]
**Platform**: Windows

**Build**: 122.1

**Issue**: Spectre turrets don't appear to be able to hit flying bosses. It shoots at them but either it does no damage to the boss or the projectile doesn't actually detect a hit on the boss.

**Steps to reproduce**: 
1. Play campaign (nuclear production complex is a good example)
2. Build a spectre defensive line
3. Get to flying boss wave

Expected: Spectre is able to damage the boss.
Actual: Spectre shoots but doesn't appear to do any damage.

**Link(s) to mod(s) used**: No mods.

**Save file**: 
[sector-serpulo-227.zip](https://github.com/Anuken/Mindustry/files/5759922/sector-serpulo-227.zip)

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I have no problems killing flying bosses with spectres on your save.
