### ISSUE TITLE
Inconsistent behavior setting unloader config using getlink links vs wall-of-config

### ISSUE THREAD

**Issue by InvalidError404** [Anuken/Mindustry#4233]
**Platform**: `Windows 10 x64`

**Build**: `steam build 122.1`

**Issue**: When using getlink loop to walk the list of linked blocks and bulk-set unloaders, only the first unloader re-configured is able to change state per script iteration, all others fail. When using a mean ol' wall of configure commands to unloader1 through unloader19 by name, all blocks change state the first time every time.

**Steps to reproduce**: Load the map, change the sorter filter located between the two cores and circled with a plastanium belt  used to control what the mass unloader scripts will set all linked unloaders to for both cores, observe that only about two unloaders per second change state on the getlink loop side (left) despite the message box confirming that the loop did walk through the whole links list and attempted to configure all unloaders that aren't already in the currently desired state (marked with an asterisk) on every iteration. In my tests, it takes an average of 160 attempts to set 19 unloaders over a span of about 10 seconds on my barren test map. On actual game maps where I rarely have more than six core unloaders, there were times where some unloaders could remain stuck for minutes at a time so I simply hard-coded link names instead of using getlink.

On the the wall-of-configure side (right) all unloaders instantaneously switch the first time every time.

For some reason, using getlink to walk through the list of linked unloaders makes controlling unloaders extremely unreliable and slow, the only fully repeatable way of doing so in one pass is to sense the unloader state and re-configure it until it changes, which typically takes 50+ attempts in my tests.

![Unloader Test](https://user-images.githubusercontent.com/60593448/103462006-52350300-4cf0-11eb-9341-66f156527779.jpg)
In this image, the sorter got changed from copper to graphite and the game got paused as soon as the loop's message box updated with loop execution results. By the time the first getlink loop completed, only one unloader successfully changed state (the second belt is the next script iteration at work in the sub-second before pause) whereas the wall-of-text switched so much longer ago that its belts are almost purged.

Looks like there may be a limit of one unloader change from getlink per script iteration or per ~500ms vs no apparent limit for configuring unloaders by name. One of these behaviors must not be intentional since if there is a rate limit for getlink for whatever reason, then someone could just use a wall of configures to bypass whatever that limit was intended for. Even if there was an intentional per-script per second unloader reconfigure limit for whatever reason, it could be bypassed by using slave controllers linked by sorters, memory cells, sensing a "master" unloader and likely other means.

Expected outcome: the getlink loop should succeed in setting all unloaders in one iteration just like the wall-of-configs does instead of succeeding in setting only one per script execution, albeit slightly slower due to more instructions involved in the loop.

Suggestion: if there is some sort of game balance motive behind the unloader config rate limit, then make unloader.configure cost something like 20 pseudo-cycles instead of making it silently fail, then it will affect getlink loops and hard-coded links equally.

**Link(s) to mod(s) used**: `none`

**Save file**: ![Unloader Test.zip](https://github.com/Anuken/Mindustry/files/5760538/Unloader.Test.zip)

**Crash report**: N/A, not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> When using getlink loop to walk the list of linked blocks and bulk-set unloaders, only the first unloader re-configured is able to change state per script iteration, all others fail. 

Configuration instructions only work several times a second to prevent packet spam. Timeout is saved per instruction.

**Comment by InvalidError404** [comment]
> Configuration instructions only work several times a second to prevent packet spam. Timeout is saved per instruction.

Since

control configure unloader1 maxitem 0 0 0
control configure unloader2 maxitem 0 0 0
control configure unloader3 maxitem 0 0 0
etc.
control configure unloader19 maxitem 0 0 0

works just fine, what you must have meant by "timeout per instruction" is actually timeout per line number, not the configure instruction itself.

In any case, the huge discrepancy between the two methods (loop vs unrolled loop) still looks like something is broken to me: same 19 initial configures going out either way, unrolled gets all of them through fine, loop only gets one through.

**Comment by Anuken** [comment]
> works just fine, what you must have meant by "timeout per instruction" is actually timeout per line number, not the configure instruction itself.

Each line is an `Instruction` instance, so no, I meant exactly what I said.

**Comment by joshuaptfan** [comment]
> works just fine, what you must have meant by "timeout per instruction" is actually timeout per line number, not the configure instruction itself.

He might be talking about individual instances of `control configure`. That said, you can still use links, but you could improve responsiveness by using multiple identical configure instructions and using `mod` to cycle through them.

**Comment by InvalidError404** [comment]
> That said, you can still use links, but you could improve responsiveness by using multiple identical configure instructions and using `mod` on your link iterator to cycle through them.
Yup, that is exactly the work-around I was about to test (currently looking into doing it using counter manipulation instead of a heap of jumps) when I saw the email notification: rotate through a setters bank.

Having a limit tied to a code line instead of the instruction/operation itself is a bit silly when it can be easily bypassed by either a wall of unrolled commands or a case-switch. Guess it sort of works in case of rogue endless loops.
