### ISSUE TITLE
Enemy oil extractors not placed properly

### ISSUE THREAD

**Issue by CaeciliusInHorto** [Anuken/Mindustry#4234]
**Platform**: `Mac OS X x64`

**Build**: `release build 122`

**Issue**: *Explain your issue in detail.*
Enemy oil extractors are built where they do not normally function
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Enter campaign sector 71, they are already in enemy base
**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[Mindustry for bug report.zip](https://github.com/Anuken/Mindustry/files/5760668/Mindustry.for.bug.report.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Those schematics *can't* be placed properly in that map, as they require both scrap and sand. Won't fix.
