### ISSUE TITLE
Radar logic from[] gets reseted every time I edit it

### ISSUE THREAD

**Issue by Ciberbot111** [Anuken/Mindustry#4237]
**Platform**: *Windows*

**Build**: *20466.*

**Issue**: *Whenever I enter the logic processor the radar logic gets reseted.*

**Steps to reproduce**: *Write anything other than turret1 in from exit and enter again it will have reset to turret1, it also happens in sandbox.*

**Link(s) to mod(s) used**: *None*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[Bug file.zip](https://github.com/Anuken/Mindustry/files/5760948/Bug.file.zip)

**Comment by Anuken** [comment]
#4236
