### ISSUE TITLE
Not able to build in iOS

### ISSUE THREAD

**Issue by jumpjet908** [Anuken/Mindustry#4239]
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *Explain your issue in detail.*
There is no way to build anything.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
delete game data, start new game.
Thee is no way to build anything, you can only fly around.

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Place an X (no spaces) between the brackets to confirm that you have read the line below.

You have not.

**Comment by joshuaptfan** [comment]
#4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220 #4221 #4223 #4224 #4226

**Comment by DeltaNedas** [comment]
how are you guys able to breathe on your own

**Comment by Erisfiregamer1** [comment]
who else thinks its one guy just alting
seriously look at their history

**Comment by jumpjet908** [comment]
Jesus Christ.
You guys don't have to be absolute elitist dicks.
I couldn't find the closed issues on the phone and after the first reply I found them.

So I'm sorry for asking a question that was already asked. Now let it go.

**Comment by XxsuperdeadlysniperxX** [comment]
@jumpjet908 anuke is not the elitist dick tho deltanedas might be though erisfire is one to be sus about you tho and joshuas sayinf straight fact i recommend _don't use alts becausepeople don't appreciate that_ aka they think you might a troll btw i just came in this so im going to say nothing more _no offense tho_
