### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by HapKoTuKoMaH** [Anuken/Mindustry#4249]
**Platform**: `Android 29`

**Build**: `release build 122.1`

**Issue**: *After finishing the game, sometimes all sounds disappear. restart helps *

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Honestly, I don't care about Android sound bugs anymore.

**Comment by XxsuperdeadlysniperxX** [comment]
-_- anuke sound breaks on android a lot

**Comment by XxsuperdeadlysniperxX** [comment]
But if its hard to fix then i respect that
