### ISSUE TITLE
Clashes between bridge placement UIs

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4251]
**Platform**: *Android*

**Build**: *122.1*

**Issue**: *Anuke, why can you accidentally lineplace bridges on conveyors? And why do new ones that were not lineplaced not configure with end ones if you place more than one?*

**Steps to reproduce**: *become the bridge fanatic*

**Link(s) to mod(s) used**: *irrelevant*

**Save file**: *its in the ui, not a save specific thing.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

just take it already

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I may have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> why can you accidentally lineplace bridges on conveyors?

Because bridges can (*and have always been able to*) replace conveyors? Why is this surprising?

> Steps to reproduce: become the bridge fanatic

If you're going to post unhelpful meme bug reports, don't report anything at all. This is not a "step to reproduce". This is useless.

> And why do new ones that were not lineplaced not configure with end ones if you place more than one?

![2021-01-03 19-16-25](https://user-images.githubusercontent.com/10100000/103492342-3026a800-4df8-11eb-8adb-36461a48dac6.gif)

**Comment by BlueWolf3682** [comment]
![Screenshot_20210103-183105](https://user-images.githubusercontent.com/61173114/103493999-ec30a480-4df1-11eb-8d0a-e0fbdc60284d.png)
@Anuken this is what i meant, the existing bridges do not autolink with the queued ones when placed

**Comment by BlueWolf3682** [comment]
also to describe how to reenact all the little issues i encounter takes too much time, so i simply stated what i normally do when i encounter them

**Comment by Anuken** [comment]
> this is what i meant, the existing bridges do not autolink with the queued ones when placed

Intentional. You will notice that the link stops displaying once the bridges get switched into line mode, as that's how the configuration system works.

**Comment by BlueWolf3682** [comment]
*why in the world would this be intentional?!* also to mention that bridges will randomly double link if placed right (i.e. two bridges will input to one output)

**Comment by XxsuperdeadlysniperxX** [comment]
That issue is so f***ing annoying i don't like how when it says its not going to attach to the adjacent block yet i does anyway it makes me go UHHHHHHHHHHHHHHHHHHHHH
