### ISSUE TITLE
Kamikaze achievement may possibly be unachieveable

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#4254]
**Platform**: Windows

**Build**: 122.1

**Issue**: [Multiple recent reports on Steam](https://steamcommunity.com/app/1127400/discussions/0/1738883005311921632/) of players unable to unlock the achievement.

**Steps to reproduce**: I cannot as I already unlocked it in 5.0.

**Link(s) to mod(s) used**: Unknown

**Save file**: Not available

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
they need a certain explosiveness before it triggers, maybe their units didn't have enough itemcapacity?

**Comment by Anuken** [comment]
No, it works as intended. Tested by filling up a crawler with blast compound on the Steam version.

Since core units no longer explode, it won't trigger for them. This makes the achievement icon misleading; may change that later.

**Comment by joshuaptfan** [comment]
Could you test air units as well?

> oooh good to know it works with land units, but i can guarantee it does not work with any of the flying ones, tried all factory flyers up to tier 3, none of them unlock kamikaze when dying with blast and taking out a unity or building

**Comment by Anuken** [comment]
Looks like player immediately leave air units as soon as they die, so when they actually hit the ground, they aren't considered player-controlled anymore.
