### ISSUE TITLE
Player alignment issues

### ISSUE THREAD

**Issue by CaeciliusInHorto** [Anuken/Mindustry#4257]
**Platform**: `Mac OS X x64`

**Build**: `release build 122`

**Issue**: *Explain your issue in detail.*
When the player respawns at the core (ctrl click) while in the exact center from either never moving or from respawning at the core from outside the core, the player will spawn slightly below the center of the core. If repeated while in this position, the player will spawn slightly above the core.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Enter game. Respawn immediately after, without moving.
**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[Bug report (Contains map).zip](https://github.com/Anuken/Mindustry/files/5764514/Bug.report.Contains.map.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't matter.
