### ISSUE TITLE
plastanium conveyor incorrectly blends with the armored one

### ISSUE THREAD

**Issue by summetdev** [Anuken/Mindustry#4259]
**Platform**: Windows

**Build**: 122.1

**Issue**:
![#4259](https://user-images.githubusercontent.com/55251897/103549187-0a60d800-4eb8-11eb-941f-b21e619c0b0c.png)
The plastanium conveyor next to the vault draws its edges incorrectly. There is an armored conveyor near it, which doesn't accept items from the side, so an edge should be drawn next to it.

**Steps to reproduce**:
- place this schematic:
`bXNjaAF4nEXNQQqEMAwF0N9olWE2Ax5h1rMRXXicYLso2FZqFby9qS6GLF7+hxC00IQ6sLfQ36EfJ7yN3ebk1uxiACrog/clo1sX3jIHt/vfHMNhz5jw4eRjsubfAC9AyRkpQdaCDIFKKtypkkTy+UE/NIULiM4YZQ==`

**Link(s) to mod(s) used**: none.

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/5765350/save.zip)

---

- [X] **I have updated to the latest release to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
known issue, won't be fixed by anuke

**Comment by summetdev** [comment]
> known issue, won't be fixed by anuke

maybe someone else can fix it

**Comment by Quezler** [comment]
but until then its better to close this issue

**Comment by DeltaNedas** [comment]
> someone else

hint hint
