### ISSUE TITLE
Build with only 1 ressource (others are enough), when Build Speed is 10.000

### ISSUE THREAD

**Issue by VersedSG** [Anuken/Mindustry#4260]
**Platform**: Windows

**Build**: 122.1

**Issue**: First experienced it with "Thermal Generators" on custom Map, then tested it with mechanical drills and copper.

When I build the buildings "Combustion Generator" and "Thermal Generators" then I can build them with only one ressource of copper (for Combustion) and one ressource of meta glass (for Thermal) instead of the required 25 copper / 40 meta. (Other ressources were plentiful.) Tested it with Ripple too, there is the behaviour even stranger... If I build the Ripple with 5, it is build instantly, if I build it below 5, the build process will be some part finished, and the rest seems to be calculated normally.

When Build Speed is 100, than the behaviour can be experienced for mechanical drills too.

**Steps to reproduce**: New Custom Game on a map with copper with following settings:
- Survival
- Build Speed Multiplier: 100+ (tested it with 1, 2, 10, 100, 500, 1000, 10000)

Then you build ONE drill for copper, put a conveyor lane directly to the core.
Deplete your copper resources by building lots of drills until you have zero copper.
Then build some more (10 or so), and you will see, that for each copper one drill is built instantly.

**Link(s) to mod(s) used**: No Mods!

**Save file**: 
[CopperBug.zip](https://github.com/Anuken/Mindustry/files/5766238/CopperBug.zip)

**(Crash) logs**: 
last log:
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce GTX 1060 6GB/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_72
[I] Total time to load: 2462
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Time to generate menu: 61.246
[I] Fetched 15 community servers.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
I tried my best to look for this specific bug.

**Comment by Anuken** [comment]
Build speed cannot be set to 100+ in the rules dialog.

**Comment by VersedSG** [comment]
OK, but even with 100 I experience that behaviour.
