### ISSUE TITLE
server depot on steam out of date

### ISSUE THREAD

**Issue by h3o66** [Anuken/Mindustry#4262]
**Platform**: Linux/Windows

**Issue**: version for the server is outdated in the steam server depot.
Depot on Steam: https://steamdb.info/app/1183370/

**Steps to reproduce**: Download the server depot via steam and check the version after the  start:
`Version: Mindustry 4-steam official / build 97`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

I modified the template here, as this does not have anything to do with the latest version or a bug in the game itself.

Edit: i got the link to this in the issue for LGSM:
https://github.com/GameServerManagers/LinuxGSM/issues/3123

**Comment by Anuken** [comment]
It's not being updated.

**Comment by h3o66** [comment]
Then It might be better to delete/close it.

**Comment by Anuken** [comment]
Someday, perhaps.
