### ISSUE TITLE
Resource gui

### ISSUE THREAD

**Issue by mohawk-uncanceable** [Anuken/Mindustry#4266]
**Platform**: *Android stylo 5

**Build**: 122.1

**Issue**: thorium shows on ruinous shores where there is none

**Steps to reproduce**: open game? I guess I beat shores before v6 so maybe that had something. Idfk man

**Link(s) to mod(s) used**: there's mods?

**Save file**: I don't know how to add an attachment. So reap my soul if you must, you won't get much

**(Crash) logs**: crashed once like a week ago

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I beat shores before v6

That's your problem. Reset the data to get an accurate representation of resources.

**Comment by mohawk-uncanceable** [comment]
Like reinstall?

**Comment by Anuken** [comment]
No, clear your campaign and save data.

**Comment by mohawk-uncanceable** [comment]
Thanks bub. Appreciate it
