### ISSUE TITLE
Black square appears over schematics

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#4274]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

122.1

**Issue**: *Explain your issue in detail.*

My schematics lose there texture some how and popup as a black box

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Just open you schematics idk how it is caused but its when the schematics menu is opened once or more

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[example of schematics going dark on mobile.zip](https://github.com/Anuken/Mindustry/files/5776817/example.of.schematics.going.dark.on.mobile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
some screenshots perhaps?

**Comment by joshuaptfan** [comment]
What model of phone do you have? Specs?

**Comment by Anuken** [comment]
No screenshots, and this is likely an Android-specific bug that I'm not interested in fixing.

**Comment by XxsuperdeadlysniperxX** [comment]
Here
![Screenshot_20210106-095420_Mindustry](https://user-images.githubusercontent.com/63037076/103800073-8cb0df80-5011-11eb-90a8-251abec948c9.jpg)
