### ISSUE TITLE
Chonker shrapnel bullet

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4275]
**Platform**: *All*

**Build**: *122.1*

**Issue**: *Sometimes when firing the fuse type bullets, a much larger one appears.*
![image](https://user-images.githubusercontent.com/61173114/103790942-10150580-4fff-11eb-8f86-91f2ef537387.png)

**Steps to reproduce**: *I was testing with K103908/Exotic-Mod in the Shockwave unit. moving and then firing the first shot seems to reproduce this.*

**Link(s) to mod(s) used**: *See above.*

**Save file**: *Game froze upon trying to export save file. School laptop is extremely buggy.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

just stop saying it and take it already

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues (#bugs) to make sure that this problem has not already been reported.**

edit: Testing reveals this can be reproduced by firing anything with ShrapnelBulletType for the first time.
![image](https://user-images.githubusercontent.com/61173114/103795459-3c328580-5003-11eb-97ad-9a1c0431d8d4.png)

**Comment by BlueWolf3682** [comment]
the games still frozen

**Comment by Anuken** [comment]
Cannot reproduce; the first bullet fired on a **vanilla** client from a Fuse has a standard length/shape. Probably something to do with the mod.

**Comment by BlueWolf3682** [comment]
that also seems to be the case, though the mod is JSON only and there are no overrides for ShrapnelBulletType, or fuse. I'll test with other mods and see if its just how the bullet is reacting to mods...
![image](https://user-images.githubusercontent.com/61173114/103802476-6b99c000-500c-11eb-8b44-ca98c7be7f5f.png)
...once I get back home and onto my phone.
I'm really starting to dislike this buggy laptop.

**Comment by BlueWolf3682** [comment]
@Anuken yeah about that, i disabled all mods
![image](https://user-images.githubusercontent.com/61173114/103803115-5f623280-500d-11eb-9f6f-1c4aa53168b4.png)

**Comment by Anuken** [comment]
What exactly is wrong with that screenshot?

**Comment by BlueWolf3682** [comment]
two of the fuse beams are much larger than they should be. you can see the normal sized one at the top, almost completely faded away.

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/103805333-6d21b300-5021-11eb-9a89-4089ac9f3eb0.png)

Works fine for me. This is the first shot.

**Comment by BlueWolf3682** [comment]
respawn in core, shoot a few times, wait for your unit bullets to despawn, hop in fuse, fire fuse. doesnt happen *every* time, unsure the precise 100% reproduction method.

**Comment by BlueWolf3682** [comment]
Successful android client reproduction:
![Screenshot_20210106-115750](https://user-images.githubusercontent.com/61173114/103809406-b1f41c80-5016-11eb-8b0d-44336cc8dbcc.png)
iOS client... unable to interact with the map.

**Comment by joshuaptfan** [comment]
I was able to consistently reproduce the bug this way:
* Respawn in core
* Fire **once** from your gamma (2 bullets are fired)
* Control fuse
* Fire
  * For your first shot, the first beam in the counterclockwise direction will be larger
  * All shots afterward are normal

**Comment by QmelZ** [comment]
https://user-images.githubusercontent.com/59574967/104095466-fe09c000-52a7-11eb-8bd6-16436437a3c2.mp4

here is a video of the bug happening, used @joshuaptfan's method to recreate.

**Comment by joshuaptfan** [comment]
Appears to have been fixed [here](https://github.com/Anuken/Mindustry/commit/21fd20ea5bad59218547b85a47e28c2ff9027262#diff-cb29bab299a93ab4f50cb8be2d51d04184d8481a890070a93df3356ef84673b0R36), just tested in bleeding edge.

**Comment by BlueWolf3682** [comment]
ok good
