### ISSUE TITLE
Steam version display quality is low

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#4276]
**Platform**: *Android/iOS/Mac/Windows/Linux*

windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

steam 122.1

**Issue**: *Explain your issue in detail.*

The steam build has a very low display quality, while release 122.1 has high quality.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. launch the non-steam jar, see the visual quality
2. launch the steam version
3. get absolutely irritated from the low quality and the blurry main menu

here are screenshots taken from both versions
![javaw_e78D7FjjxQ](https://user-images.githubusercontent.com/59574967/103808318-d973d500-5068-11eb-909d-5c83e025b41f.png)
![Mindustry_guFQJAbc3p](https://user-images.githubusercontent.com/59574967/103808333-ded11f80-5068-11eb-9ad9-8f8b9216180a.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

this is a clean install from steam

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

this is not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
smells of ui scale

**Comment by QmelZ** [comment]
both screenshots were taken with no windows settings changed, and both are at %100 ui scaling

**Comment by joshuaptfan** [comment]
Unlikely to be an issue with Mindustry, check Nvidia/AMD graphics control panel.

**Comment by Anuken** [comment]
This is not a Mindustry issue; both versions have exactly the same base code. Steam ships its own SDL version, which is the likely cause of the problem.
