### ISSUE TITLE
Comparisons with null cause incorrect jumps

### ISSUE THREAD

**Issue by thunkk** [Anuken/Mindustry#4277]
**Platform**: Windows

**Build**: 122.1

**Issue**: Comparisons with null cause incorrect jumps

**Steps to reproduce**: Build a processor and a message block. Connect them together and paste the following snippet:
```
jump 3 equal 1 null
print "not null"
jump 4 always x false
print "null"
printflush message1
```
Seems that a previous report was closed due to template issues #4206 without a fix.

**Save file**: 
[Jump null comparison bug update.zip](https://github.com/Anuken/Mindustry/files/5778252/Jump.null.comparison.bug.update.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
numbers are always casted to null, not a bug

**Comment by thunkk** [comment]
I feel like that is at least a bit inconsistent with operator, as
```
op equal result 1 null
print result
printflush message1
```
results in 0 being printed
