### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by SorterBoi** [Anuken/Mindustry#4279]
oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no oh no

**Comment by SorterBoi** [comment]
hapi sorter spam da "Oh no"

**Comment by SorterBoi** [comment]
liek it or **DIE**

**Comment by notrealn** [comment]
you realize anuke gets his notifs spammed by useless comments/issues like these

you might want to stop

**Comment by itcannotbe** [comment]
Can someone ban that troll account.

**Comment by FFX1234** [comment]
why

**Comment by DeltaNedas** [comment]
low effort troll go away

**Comment by laok233** [comment]
should add ''a disgrace'' label for this issue.
