### ISSUE TITLE
shootP in turrets does not work in certain scenerios

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#4280]
**Platform**: Windows 10

**Build**: Steam build 122.1

**Issue**: 
Using logic control shootp does not work in singleplayer unless an enemy of some type is in range of the turret

In multiplayer, it partially works:
Turret shoots at where it was last aiming at, and then the enemy takes damage/dies, despite the turret shooting in a different direction.

Attempting to use targetp to shoot yourself/allies will not work unless it's already in range of an enemy.

I shared this information with other people in the #logic discord to confirm, and they said it wasn't working as intended/to report it.

**Steps to reproduce**: 
Code used, also in save file.

radar ally any any distance duo1 1 result
control shootp duo1 result result 0 0
sensor x result @x
sensor y result @y
print x
print ","
print y
print "\n"
print result
printflush message1

**Link(s) to mod(s) used**: N/A

**Save file**: 
[logicTargetPBug.zip](https://github.com/Anuken/Mindustry/files/5762463/logicTargetPBug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
#3923 is a similiar issue in previous version, but is already closed. Posted this incase it was missed

**Comment by Anuken** [comment]
Duplicate.

**Comment by joshuaptfan** [comment]
Linking duplicate just FYI: #3923
