### ISSUE TITLE
Changing the waves custom rules to default, when it is not needed

### ISSUE THREAD

**Issue by Yarjk32** [Anuken/Mindustry#4283]
**Platform**: `Windows 10 x32`, `Windows 10 x64`, *Android 5.1*

**Build**: `bleeding-edge build 20489`, `release build 122.1`

**Issue**: *I changed custom rules for my new map and saved it. Then I tried to play on it. I chose attack gamemode and checked custom rules. I saw, that game changed waves settings to default. It turned on waves and changed wave spacing to 60 sec.*

![ohno](https://user-images.githubusercontent.com/65510612/103899766-89941d00-50ff-11eb-89cd-4fb0378c1f95.png)

*If I choose sandbox gamemode, then wave spacing will be 120 sec.*
*Then I tested this problem in BE build and on my phone. I noticed, that this problem occurs not only with my map.*

This issue is annoying because I don't want to have waves on my attack map. I can make pseudo-empty waves but then will appear waves timer instead of the number of enemy cores. Or I can disable waves before playing, but I should often do it while testing the map.

**Steps to reproduce**: 
1. Check (and edit) the waves custom rules of a map in the editor. 
2. Save the map.
3. Choose the map for a custom game.
4. Check the custom rules of a map there.

https://user-images.githubusercontent.com/65510612/103903391-818aac00-5104-11eb-9cc1-cc3ed2897bd2.mp4

**Link(s) to mod(s) used**: `none`

**Save files**: [map.zip](https://github.com/Anuken/Mindustry/files/5781940/map.zip) [data.zip](https://github.com/Anuken/Mindustry/files/5781948/data.zip)

##### If I remove the line above without reading it properly and understanding what it means, Anuke will reap my soul. Even if I'm playing on someone's server, I can still save the game to a slot.

**(~~Crash~~) logs**:  [log.txt](https://github.com/Anuken/Mindustry/files/5781960/log.txt)

---

*Place an X (no spaces) between the brackets to confirm that I have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug. The attack mode preset enables waves, the wave timer and short wave spacing be default. If you want more control, set it up yourself in the rules.
