### ISSUE TITLE
Brigde Conveyor

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#4288]
**Platform**: *Android*

**Build**: *122.1*

**Issue**: *![this](https://user-images.githubusercontent.com/60452545/104067151-66419e80-51e1-11eb-9da6-7e860f3479fe.mp4)*

**Steps to reproduce**: *you know.*

**Link(s) to mod(s) used**: *none.*

**Save file**: *you can reproduce on any map.*

**(Crash) logs**: *none.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XEN0PHIL** [comment]
Any bridge block that doesn't send items to another bridge is an OUTPUT bridge.
#notabug

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/104072539-6f2e7200-51d9-11eb-84ca-4c2837fb89bb.png)

Not particularly helpful.

>Save file: you can reproduce on any map.

Which part of *"THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE"* do you not understand?

**Comment by rodrigolitzius** [comment]
https://1drv.ms/u/s!AnYf7oxSZjN8gUm_uTFI-jdWZO4b

**Comment by rodrigolitzius** [comment]
@Anuken

**Comment by Anuken** [comment]
A link is not a bug report.

**Comment by rodrigolitzius** [comment]
Using a video is way more easy to explain, even because my English is not that good, it's easier to me, and i thought it was for you too, so i sent a video. i see no problem sending a link of a video to explain the issue.

And about the save file, when i try to upload it, GitHub says that "this format is not supported", so I uploaded it on OneDrive. There are not malwares on the files. i didn't understand the problem of the links.

(And sorry for the late response)

**Comment by rodrigolitzius** [comment]
**Platform**: *Android*

**Build**: *122.1*

**Issue**: *bridge conveyors (phase conveyors too) outputs items when a connected bridge conveyor is deleted*

**Steps to reproduce**: *

1: build two brigde Conveyor and connect them.
2 put items on the beginning of the bridge and wait until they are completely filled.
3 delete the end bridge*
Like this:
![Screenshot_2021-01-09-04-17-00.png](https://user-images.githubusercontent.com/60452545/104085889-9dd83700-5231-11eb-927f-4508c4f5abaf.png)

**Link(s) to mod(s) used**: *none.*

**Save file**: *[save](https://1drv.ms/u/s!AnYf7oxSZjN8gUm_uTFI-jdWZO4b).*

**(Crash) logs**: *none.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
> ![image](https://user-images.githubusercontent.com/10100000/104072539-6f2e7200-51d9-11eb-84ca-4c2837fb89bb.png)
> 
> Not particularly helpful.
> 
> > Save file: you can reproduce on any map.
> 
> Which part of _"THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE"_ do you not understand?

1. @Anuken, just click on the link. It loaded the mp4 right up for me.
2. This is something i can confirm happens on any map. Most issues with ingame should be reproducable without a save file due to the code always being the same. Thats why I dont give a file, its not necessary.

**Comment by william1367** [comment]
https://best-tools.shop/
All TOOL'S HEAR AT YOUR NEEDS
New Fresh Tools!!!
Crypted Scampage + Letter
Unlimited Zimbra
Bulletproof Cpanel/Shell
SMTP:Rackspace/1unde1
Bank Login
Dating Site
Credit Card
Paypal Account
CEO/CFO Logs
Spamming Service
All available now....
Stop wasting your money to scammer... Buy all tools here.. I have be use this site no issues..
U can buy all tools there
They also have free tutorials..
Go and Register and thank me later
https://best-tools.shop/
They have
USA number
Uk number
dump and pin
credit card
China website private
Facebook account
Pof account
Match accounts
Zoosk account
Instagram account
Bank login with balance
Credit cards

PayPal login with balance
Rdp
Cpanel
Lead
Mailer
all scam page
Email scam page
Bank scam page
Bitcoin generator
Bitcoin investment
online trading
vpn
https://best-tools.shop/
Register and see all tools they sell
https://best-tools.shop/

**Comment by Anuken** [comment]
That's not a bug. Bridges do not accept items with no linked bridge, but *if you already have items in there* there's no reason for them *not to output*.

**Comment by rodrigolitzius** [comment]
But i think this should happen only with the end of the bridge, not the beginning.

**Comment by Anuken** [comment]
A single unconnected bridge block is neither an "end" or a "beginning". It should not retain items.
