### ISSUE TITLE
Bullets only perform splash damage on despawn

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#4289]
**Platform**: *Windows*

**Build**: *BE 20491*

**Issue**: *Similarly to lightning in v5, splash damage on bullets only occurs on despawn.*

**Steps to reproduce**: *I noticed it while creating a modded turret (check `pixel-i.js` in `MEEPofFaith/progressed-materials`). When the bullet hit, only the block hit would take damage. When it despawned next to a block, it would cause splash damage. A similar effect is really noticeable with Quad bombs, land on a block and not much happens. Land on the floor _all your conveyors are gone_*
**Over blocks:**
![Inside](https://user-images.githubusercontent.com/54301439/104078666-29bb7600-51d4-11eb-878d-acab8bc35de6.gif)
**Next to bocks:**
![Next to](https://user-images.githubusercontent.com/54301439/104078795-ae0df900-51d4-11eb-834c-4bbd76a49aaf.gif)
**It's even more noticeable when the blocks heal:**
![Healing](https://user-images.githubusercontent.com/54301439/104078804-bcf4ab80-51d4-11eb-930b-bd2fcd9d6342.gif)

**Link(s) to mod(s) used**: [Mods.zip](https://github.com/Anuken/Mindustry/files/5789946/Mods.zip)

**Save file**: [Mononuke.zip](https://github.com/Anuken/Mindustry/files/5789945/Mononuke.zip)
**Console commands ran:**
`UnitTypes.mono.weapons.add(UnitTypes.quad.weapons.get(0))`
`UnitTypes.mono.faceTarget = false`
`UnitTypes.mono.weapons.get(0).reload = 2`
`UnitTypes.mono.weapons.get(0).shots = 5`
`UnitTypes.mono.weapons.get(0).inaccuracy = 360`
`UnitTypes.mono.weapons.get(0).velocityRnd = 1`
`UnitTypes.mono.weapons.get(0).bullet.speed = 1`
`UnitTypes.mono.weapons.get(0).bullet.collidesAir = true`
(I am a frequent console abuser)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
(Considering my history of pull requests I should try fixing this myself.)

**Comment by Anuken** [comment]
This has nothing to do with despawning. The bullets you are showing **cannot** hit anything, they *only* do splash damage. When it's dropped on a block, all the damage is absorbed immediately; that's just how the system works right now.

**Comment by MEEPofFaith** [comment]
What about the bit turret in the 3rd gif? That one can collide. Or is it still the case that the splash damage just all focused into the block that's hit?

**Comment by Anuken** [comment]
Same thing. Damage only propagates through empty tiles.

**Comment by MEEPofFaith** [comment]
I never knew that lol.
