### ISSUE TITLE
Unit "Mega" can't be used to heal buildings with a logic unit

### ISSUE THREAD

**Issue by itday** [Anuken/Mindustry#4291]
**Platform**: *Windows*

**Build**: *steam build 122.1*

**Issue**: *The unit "Mega" won't heal/shoot when controlled by a logic unit.*
![MindustryA](https://user-images.githubusercontent.com/22928478/104085811-865d7600-5252-11eb-916d-757500c8bde8.png)

Used code:
![Code](https://user-images.githubusercontent.com/22928478/104085741-0b945b00-5252-11eb-96ff-7212f732635e.png)

**Steps to reproduce**: *Use the code above to heal/shoot on a tower with a logic unit (the unit type need to be changed to the corresponding unit type). Other units shoot at the target, the "Mega" unit does not.*

**Nodes:**

- The unit "Horizon" needs to fly over a target to shoot/throw bomps. Example code (with a message field):
```ubind @horizon
ulocate building turret false @copper outx outy found building
sensor unitX @unit @x
op add pointA outx 2
op sub pointB outx 2
jump 7 greaterThan unitX pointB
set movingToB false
jump 13 equal movingToB true
jump 13 greaterThanEq unitX pointA
print "Move to A"
op add resultX unitX 2
ucontrol move resultX outy 0 0 0
jump 17 always
print "Move to B"
set movingToB true
op sub resultX unitX 2
ucontrol move resultX outy 0 0 0
ucontrol targetp building 1 0 0 0
printflush message1
```
- The antumbra and the eclipse don't shoot either.

**Link(s) to mod(s) used**: *No mods used.*

**Save file**: [Map.zip](https://github.com/Anuken/Mindustry/files/5790278/Map.zip)

**(Crash) logs**: *No crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
- The map you linked doesn't have any quads in it, and does not match your screenshot.
- Was the quad moving when you tested it? Bombers can't shoot unless they're moving.
- I have no issues making a quad shoot when I test it. Either your code is broken or the above condition is not met.

**Comment by DeltaNedas** [comment]
what about megas

**Comment by Anuken** [comment]
> what about megas

Strange, I misread that as "quad" after I saw the screenshot.
There still isn't any code in the save to test it, but I would assume the problem is that `shootp` doesn't support allied blocks.

**Comment by itday** [comment]
Thank you very much for the fast fix @Anuken. Excuse me for uploading the wrong map.
