### ISSUE TITLE
A couple of logic issues when reloading the map.

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry#4293]
**Platform**: *Windows*

**Build**: *122.1*

**Issue**: *When reloading the map disabled blocks enable themselves, processors forget blocks that were assigned to a variable via getlink and displays forget their image.*

**Steps to reproduce**: *I've linked a map where I've reproduced the issues, processors that reproduce this and message blocks with further detail are present there.*

**Link(s) to mod(s) used**: *None.*

**Save file**: *[logic_bugs.zip](https://github.com/Anuken/Mindustry/files/5791487/logic_bugs.zip)*

**(Crash) logs**: *No crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> When reloading the map disabled blocks enable themselves

Intentional. Blocks do not store enable/disabled state.

> displays forget their image.

Intentional. Screen buffers are not saved.

> processors forget blocks that were assigned to a variable via getlink

Processors cannot save link objects in most situations.

**Comment by Nester23** [comment]
Would you change these behaviors in the later updates? 
>When reloading the map disabled blocks enable themselves
This point in particular creates problems for me, since processors can't disable unloaders immediately, and they leak some items.

**Comment by Nester23** [comment]
@Anuken would you change these behaviors in the later updates? 
>When reloading the map disabled blocks enable themselves

This point in particular creates problems for me, since processors can't disable unloaders immediately, so they leak items. In the worst case scenario I imagine it would cause a thorium reactor to explode.

**Comment by Anuken** [comment]
Perhaps.

**Comment by claw4oo** [comment]
Processors also forget their bound unit on a load.

**Comment by DeltaNedas** [comment]
saving an image with every display is a great way to prevent anyone from joining servers, or to eat lots of disk

saving enabled in every building doesnt sound too bad
