### ISSUE TITLE
All crawlers explode at once under player control

### ISSUE THREAD

**Issue by claw4oo** [Anuken/Mindustry#4294]
**Platform**: Windows 10

**Build**: Steam 122.1

**Issue**: It appears as all crawlers explode when you manually blow them up, with what appears to be no range limit.
Aka, all the crawlers on the map explode
Probably not in the way of anything, or really matter much.

**Steps to reproduce**: Create some crawlers, control a single one, then attack. All of them explode.

**Link(s) to mod(s) used**: N/A

**Save file**: [crawlertest.zip](https://github.com/Anuken/Mindustry/files/5791774/crawlertest.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Player controls crawler -> shoots -> dies -> possesses next crawler -> mouse is still down -> repeat. Not a bug.

**Comment by claw4oo** [comment]
I see, that makes sense then, just didn't realize it was changing units since the camera wasn't changed.

**Comment by BlueWolf3682** [comment]
this is still outstandingly annoying on mobile, as theres no detonation ratelimit and multiple can be exploded by the shortest of manual firings.

**Comment by Anuken** [comment]
> is still outstandingly annoying on mobile

Most things are.

**Comment by BlueWolf3682** [comment]
actually mobile isnt annoying overall, its just where you haven't made the game account for mobile's problems that actually are annoying.

on that note, i strongly suggest adding a crawler ratelimit
