### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Void-Syrex** [Anuken/Mindustry#4296]
**Platform**: *Windows*

**Build**: *122.1*

**Issue**: *Unknown to the collapse of the system, mods unloaded.*

**Steps to reproduce**: *Play a game*

**Link(s) to mod(s) used**: *cheat:1.8.5, hacker-tools:3.0.0 (offline mods)*

**Save file**: *nope*

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-01_10_2021_00_02_07.txt](https://github.com/Anuken/Mindustry/files/5791826/crash-report-01_10_2021_00_02_07.txt)
[last_log.txt](https://github.com/Anuken/Mindustry/files/5791827/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is caused by an invalid modded save.
