### ISSUE TITLE
Nearby enemy base count not taken into consideration correctly for invasion probability

### ISSUE THREAD

**Issue by juliand665** [Anuken/Mindustry#4297]
In order to calculate the probability of an invasion, you calculate the number of nearby bases (`sector.near().count(Sector::hasEnemyBase)`), but then you all but discard those results by taking their minimum with 1, yielding the same number (1) for a sector with _any_ adjacent enemy bases.

https://github.com/Anuken/Mindustry/blob/0a5a301573302dda466327717a0d664a4fe49f20/core/src/mindustry/game/Universe.java#L221

For the record, i don't think it should be `max` either, since that way sectors without nearby enemy bases could get invaded too. I'm honestly not sure why you'd want to apply any such transformation here.

This explains why people would have sectors with tons of nearby bases without any invasions for hours.

**Comment by Anuken** [comment]
This is completely intentional. In older versions, the cap was higher (than 1), and bases near the poles (NPC, Impact) got invaded constantly. This was undesirable, so I gradually decreased the cap until it reached 1.

> I'm honestly not sure why you'd want to apply any such transformation here.

Players are already annoyed by invasions. Is it really hard to imagine why making those invasions occur 4x more often is a bad idea?

**Comment by juliand665** [comment]
Huh, I didn't expect that. In that case, I'd want to update the code to reflect this intention (not using `count` at all), though I feel like the game's depiction with the individual lines going from enemy base tiles to yours definitely leads you to believe invasion chance or difficulty would be proportional to the number of nearby enemy bases.

I do think it would be a really interesting strategic element to have invasion chance depend on the number of nearby bases, so that it makes sense to capture some in order to reduce your chances for specific tiles. Perhaps you could just tweak the base invasion chance or grace period to make them less of a nuisance—that makes more sense to me than this flat system.

If you were looking for a way to tweak more precisely how much of an effect additional bases have on invasion chance, you could consider special casing the zero-base case to have more flexibility in how you scale the chance, e.g.

```java
int nearbyEnemyBases = sector.near().count(Sector::hasEnemyBase);
float invasionChance = baseInvasionChance + additionalScalingFactor * (nearbyEnemyBases - 1);
if (nearbyEnemyBases > 0 && Mathf.chance(invasionChance) {
	// invade
}
```

That way, if `additionalScalingFactor` were, say, 0.25, invasion chance would be doubled (+100%) for tiles with 5 neighboring enemy bases but only increased by 25% for 2, compared to the base case of 1.

**Comment by DeltaNedas** [comment]
youre already more likely to be invaded with multiple bases as you cant reliably take them all out at once
