### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by Khanaaan** [Anuken/Mindustry#4300]
**Platform**: `Android 28`

**Build**: `release build 122.1`

**Issue**: *found a typo in the german language. located at the description of the overflow gate. it says: '..., wenn der fordere Ausgang blockiert ist.'
but in correct german it should be: '..., wenn der vordere Ausgang blockiert ist.' *

**Steps to reproduce**: * look at te description of the overflow gate in german langurage. *

**Link(s) to mod(s) used**: `none`

**Save file**: *None*

**Crash report**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
then make a pull request, you have a github account 👀
