### ISSUE TITLE
Unit Locate doesn't output on outx, outy, and found if located a building.

### ISSUE THREAD

**Issue by Nikolay-Sitnikov** [Anuken/Mindustry#4304]
When using the "Unit Locate" command, and selecting option "Building" or "Damaged", there are 4 outputs shown on the block: outx, outy, found, and building. The first three are always null for those two options, even if a building is found.

**Comment by joshuaptfan** [comment]
I have no problems with using `ulocate`. The problem is likely your other logic surrounding it, and your understanding of logic.

You also deleted the template, and have not posted your logic code, or a save file. You will get no help here if you do not rectify these things.

**Comment by laok233** [comment]
no version, no screenshot, no map file or code.
nothing helpful

**Comment by BAXENdev** [comment]
Here are two helpful tips for this issue. 
1. Hover over the commands in the processors to read their description.
2. You need a bounded unit for your processor to locate stuff with unit locate.
