### ISSUE TITLE
Random errors at online servers.

### ISSUE THREAD

**Issue by Matias123321** [Anuken/Mindustry#4306]
**Platform**: *Android 6.0*

**Build**: *122.1*

**Issue**: *sometimes at random I get this error (attached image) does not usually appear much and the truth has only happened to me twice on the same public server (Alex turbo pvp).*

**Steps to reproduce**:*It just happens at any time, there are no steps xD.*

**Link(s) to mod(s) used**: *No mods were used.*

**Save file**: *The map doesn't matter, it happens anytime.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *(Attached file).*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_2021-01-11-00-02-27](https://user-images.githubusercontent.com/77257959/104146887-19112880-53ab-11eb-9b6d-7fc7d83dc7c9.png)
![Screenshot_2021-01-11-00-19-48](https://user-images.githubusercontent.com/77257959/104146933-35ad6080-53ab-11eb-8f2e-4ba82af1c107.png)
![Screenshot_2021-01-11-00-19-48](https://user-images.githubusercontent.com/77257959/104146969-4f4ea800-53ab-11eb-852f-9514777aa5ae.png)
[Mindustry crash logs.txt](https://github.com/Anuken/Mindustry/files/5793980/Mindustry.crash.logs.txt)
PD:sorry for having some things in the images in another language xD

**Comment by BlueWolf3682** [comment]
it worries me that some crashes have "unknown build 0" instead of a release build

**Comment by alexpvpmindustry** [comment]
Matias123321 told me about the bug, but i have no idea on how to solve it/ where it originates from.

**Comment by unjown** [comment]
I never got this error actually.
But i think its device/internet can't handle since this is turbo pvp it spawns random blocks

**Comment by DeltaNedas** [comment]
how is a broken plugin mindustrys fault

**Comment by Anuken** [comment]
Likely caused by a plugin.

**Comment by joshuaptfan** [comment]
To explain to the newbs, servers can use plugins to enable custom features. The server you are playing on is breaking your game, don't play on that server.

**Comment by alexpvpmindustry** [comment]
yeah... sorry. his case seem to be the odd one out. ill try to optimize the plugin then.. thanks for the help!
