### ISSUE TITLE
Parallax ray is not visible if the turret is out of screen

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#4309]
**Platform**: *Linux*

**Build**: *Bleeding Edge*

https://user-images.githubusercontent.com/40753025/104159798-088b9d00-5401-11eb-8716-257dcbcb346d.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
this is due to how mindustry renders graphics. Very large unit explosions are great for seeing this.

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/Block.java#L116

**Comment by Slava0135** [comment]
> https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/Block.java#L116

Make a PR then?
