### ISSUE TITLE
[4.0 b65] Conveyors displayed speed doesn't reflect the real speed

### ISSUE THREAD

**Issue by NemoStein** [Anuken/Mindustry#431]
Conveyors and Titanium Conveyors seems to move twice as fast as the displayed in the tooltip.

Conveyors stated speed is `1.8 i/s` so it should be able to carry the output of 5.25 Mechanical Drills over 4 tiles of coal (each drill outputs `0.34 i/s`.) or 21 coal tiles drilled by Mechanical Drills.
But I was able to supply around 11 drills before hitting the limit.

The Titanium Conveyors (`4.2 i/s`) should be limited at 12.25 Mechanical Drills over 4 tiles of coal, or  49 tiles of coal drilled by Mechanical Drills.
But, once again, I was able to feed the conveyor with 25 drills.

It seems that the displayed values are half the actual values.

**Comment by indielm** [comment]
https://discordapp.com/channels/391020510269669376/396416151032299521/523681107791577108
https://imgur.com/a/9hwvBXa
