### ISSUE TITLE
Triangle Draw Issue: Negative Coordinates -> Max Value

### ISSUE THREAD

**Issue by Mindustry-Bug-Temp** [Anuken/Mindustry#4316]
**Platform**:

iOS

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

122.3

**Issue**: *Explain your issue in detail.*

Triangle Draw Function errors corners to maximum value if a coordinate lies in the negative domain, resulting in broken functionality for some applications.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Using logic, draw a triangle with at least one coordinate inside the visible region and at least one with a negative value.

When the error occurs, you should observe the coordinate that is negative being looped to the highest value, making the triangle draw well off-screen.

(The attached save contains a logic machine that demonstrates this, using the controls to rotate the image until a corner is offscreen or incr

**Mods active**:

No mods active.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[save-tmp.zip](https://github.com/Anuken/Mindustry/files/5804884/save-tmp.zip)

First time uploading a zip to here so am unsure if it worked, as a backup I have included a schematic that can demonstrate this issue, since I have observed it on all my saves and on servers. Simply use the controls to rotate a corner off either the left or bottom (negative coordinates) and the issue will occur.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Mindustry-Bug-Temp** [comment]
bXNjaAF4nGNgZWBlYmDJS8xNZWApSc0tYOBOSS1OLsosKMnMz2NgYGPgzk3NzS+q1E1Ozclh4M3JT89M1k3JLC7ISaxk4M/NTC7K1y0oyk9OLS7OL2JgzwXSiempDGzF5ZklyRkM/BANCBUMDFwMCMAIQowMzAwMTCA2H5ArVDFn6aX3fs0GAgwfDqfO+qKp93tfyz/Hm+byh8RfPCiZwXVj2puP6pOn5SjMPPaFuXzntp93L7IkbC0L2X1s0dMXfVP1+WTmr7xW7axa/d4u6sxEO+vcc9JxWwuP6LwU0t15rkLnhETfyw3Gzs7n9sqUyJ7ePcXyk+Fp42tbVpz+WPIj5U2Gtv9l6+5l37YZSpgo68uKdRcIaiUxPe8P1Ms7ufPI9n0vTsa92n79z9sH5Xf/2dcZfj4dMFF4f8BFffE/Sr9Y5/fOe379R/G/2y+7XffOeRm6YkVnXNeKcPOvu+WXn5+/6TTfD/lj++80SEln5IZW35ni6yvNxvD9g0CcxJ2v2iqL+BXVhMImHHH5msj0+v3+WqujAV8Uaxi/PhD5BwwfYCixMDJIRyubg0Gsc0BodGJycmpeSax6sUJyaRIw+kBhCAxcFlBwQmkmIM0KpJlBIXu8Ys7Vqb7+hxwE2rJ7jv3QVrtjepvJUKbX6cuCCQcYq7RzWX1+nhB7lPff+tGZPO/tSzvYk5Nutc0ttyuz4udOn1ZaedpZn0HvAP/iE2xla3NX5rC/tYhhbt8Vx7NwobhylE64wHkxgWSze8mb/qby7EvM3r+kqc1+a3jNtgjntdffOv9/udN4ReCRGuFGjg1MR1ObXBoZT59x+fn4jj5TpcaF4uTpom/M1mtdNVNav/q0CEvViqkN1fL5F9XmORl0h09Uz1VtlG+VW/5uk3b1+occC4r/X1i3tPB0xsmDmWahIb88pSsfS7Dp7/3bs0eBoXFx2kzFwjtvftUaxzdebuIUimqvMfgqprX26BkVmd6ZbWdnvy2xnlsXfX6mUk10wqQTwTXRTVKX4wpOCZ5zbLmySPGqZudTtaUz/rldvK9gfzk46vPM7TNcFr7qvbWQ74pchIi2bPehSSHq3afuz+Q4kPxd1HDJouijqspJBQv1HU4dtTu69CTfDpENHUpiE5ML+xM9T0VMMpq2pEf1p3rEHS0d5+1C3W5Bra5zjhWl1/e7im30eLxlx/5m14yP7EtcZk6ZGaI/f9d+a6d1J09tWlP82ulv+Jttu/33lhTs3Lpu03zXKWv1fR2/6gJjlgUc0wBPupkY

**Comment by Anuken** [comment]
Negative coordinates are not supported.
