### ISSUE TITLE
Losing progress from repetitive save file corruption

### ISSUE THREAD

**Issue by Nanosuitwitdaboomboxwhatsongwillhepla** [Anuken/Mindustry#4318]
**Platform**: Windows

**Build**: release build 122.1 64- bit

**Issue**: Everytime I play the game, save and quit, then come back to the sector I was playing on, it says  "An error has occurred save file corrupted or invalid". While this sounds normal, this is the third time it has happened

**Steps to reproduce**: 1. open the game  2. Play it for a while  3. Save and quit   4. Return to sector.

**Link(s) to mod(s) used**: no mods used
**Save file**: 
[save file.zip](https://github.com/Anuken/Mindustry/files/5808664/save.file.zip)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ]X **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I cannot reproduce this on any device.
