### ISSUE TITLE
Importing game data fails to replace save.

### ISSUE THREAD

**Issue by whio** [Anuken/Mindustry#4321]
**Platform**: Android

**Build**: 122.1

**Issue**: Maps load up with old saves. I think this may be related to #4202, but that one didn't have an easy reproduction case, and it may be a different root cause despite similar symptoms.

**Steps to reproduce**: I created an export of my campaign data. Once the export was created, I performed the following steps:
-Clear campaign saves from menu
-Import game data
-(Mindustry exits)
-Launch mindustry
-Play campaign
-Launch to an uncaptured sector
-Clear campaign saves
-Launch to windswept island
(This gives the starting shard and drills.)

-Import game data
(Mindustry exits.)
-Launch Mindustry
-Play campaign
-Go to Windswept Islands

Observe that Windswept Islands is the save with the starting shard, not the save from within the campaign data.

**Link(s) to mod(s) used**: None

**Save file**: 
[campaign.zip](https://github.com/Anuken/Mindustry/files/5811465/campaign.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. 

> Observe that Windswept Islands is the save with the starting shard, not the save from within the campaign data.

I followed your steps, and this did not happen. This could be an Android-specific zip bug, in which case I am not interested in fixing it.

**Comment by whio** [comment]
I tested it some more, and it appears that importing data doesn't overwrite the sector currently being played. Clearing data first, or doing it from the main menu with no map active, and it loads successfully.

This is true even if the campaign save doesn't include the currently played sector, which produces odd results.

**Comment by whio** [comment]
![Screenshot_20210113-220323764](https://user-images.githubusercontent.com/9060036/104740151-3593c480-570d-11eb-91f2-ae91c72e505a.jpg)

**Comment by Anuken** [comment]
> it appears that importing data doesn't overwrite the sector currently being played

Obviously...? If you're *currently playing on the save*, anything you import gets overwritten as soon as you save&exit. This isn't a bug.

**Comment by whio** [comment]
I can do neither of those things - importing causes the game to immediately exit, I don't get the chance to save. If the import step is saving the current data instead of what you just instructed it to import, that behavior seems unexpected.

**Comment by jasekiw** [comment]
> > it appears that importing data doesn't overwrite the sector currently being played
> 
> Obviously...? If you're _currently playing on the save_, anything you import gets overwritten as soon as you autosave or save&exit. This isn't a bug.

Why do you provide a feature in a context where it won't work in? When you import saved data the game immediately closes. No one would assume the game saved your current state over the data file your just imported. This is most definitely a bug.

**Comment by Supereor** [comment]
If this isn't a bug, then I think it should be more clearly indicated that the game still uses the imported file after it's created and it doesn't just save a snapshot of everything as it was when you clicked the button.  Lost a ton of progress today because I mistakenly believed this didn't save game progress when I saw my save didn't change after importing, and I tried to back up progress by manually backing up and replacing files instead.

**Comment by Anuken** [comment]
(This was fixed)

**Comment by Supereor** [comment]
Oh, it is fixed; I didn't even try it again after the first time, thank you!
