### ISSUE TITLE
Mass Driver pointing wrong direction / Foreshadow ray not rendering offscreen 

### ISSUE THREAD

**Issue by vb0t** [Anuken/Mindustry#4325]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 122.1

**Issue**: *Explain your issue in detail.*
2 issues: 1 - mass driver pointing in the wrong direction when receiving items from multiple mass drivers.
2 - foreshadow ray not rendering when you scroll out

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1 - Play multiplayer sandbox, have another player place the mass drivers (issue visible for both players)
2 - place a foreshadow and scroll in. once it shoots, scroll your view out

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
(see attached)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- 
[attached.zip](https://github.com/Anuken/Mindustry/files/5814438/attached.zip)

**Comment by laok233** [comment]
if u have this kind of issue u can do /sync, it may resolve the problem

**Comment by Anuken** [comment]
> Foreshadow ray not rendering offscreen

This isn't a bug - effects are not created off-screen. You have to go out of your way to make this happen anyway.
