### ISSUE TITLE
Liquid tank bug?

### ISSUE THREAD

**Issue by catatagun** [Anuken/Mindustry#4328]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android 
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*122.1

**Issue**: *Explain your issue in detail.*
Liquid tank no dispense liquid fast in multiplayer
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*make thor reacter see thor reacter cryo go down after liquid tank might be a multiplayer issue

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* cant find butten to file thing. help might be a mobile issue for git will upload in comment if possible if not @my discord or something its @guncat trust me i readed it

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> make thor reacter see thor reacter cryo go down after liquid tank might be a multiplayer issue

This is completely incomprehensible and cannot be tested without a save or screenshot.

**Comment by catatagun** [comment]
[bugwithliquidtank.zip](https://github.com/Anuken/Mindustry/files/5817637/bugwithliquidtank.zip)

Yay i found the zip and found how to upload it

**Comment by iLagSoUhax** [comment]
me when

me when english is kil
