### ISSUE TITLE
Navals dont like velocity based things

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4329]
**Platform**: *Android*

**Build**: *122.1*

**Issue**: *If you stick something based on velocity on a naval unit, it will break if you hit a wall.*

**Steps to reproduce**: *Run a naval into a wall while firing a weapon that either requires a min velocity to fire or use a sapper laser.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod for the sapper naval, though all mods are irrelevant because they do not affect this.*

**Save file**: *I explained why I don't include saves before. Either you willl be able to reproduce on your own file or its a client specific bug and doesn't matter.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

all threats and no action

**(Crash) logs**: *no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_20210114-230815](https://user-images.githubusercontent.com/61173114/104689103-2e45ca00-56bf-11eb-9647-31934d0b604b.png)
![Screenshot_20210114-230743](https://user-images.githubusercontent.com/61173114/104689108-2ede6080-56bf-11eb-90f9-83cc722a6eef.png)

**Comment by iLagSoUhax** [comment]
interesting

**Comment by Anuken** [comment]
This is not specific to naval units, and I'm not interested in fixing it. minVelocity is intended for use with flying units only, and velocity does not decrease even when you hit something.

**Comment by BlueWolf3682** [comment]
...i reenacted the sapper laser thing with arkyid and spiroct. at least fix sapper lasers.
