### ISSUE TITLE
Megas cannot heal unfinished buildings

### ISSUE THREAD

**Issue by Mangahfold** [Anuken/Mindustry#4330]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
122
**Issue**: *Explain your issue in detail.*
Megas do not heal in construction or not finisihed constructed buildings like menders. megas are somewhat like menders.
if you have a not finished and abit damaged building itll take away the megas attention
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
simply enough i was testing my map and watching how the polys rebuild then i saw that it did not heal the building
i started testing and yes if a enemy gets a hit on the building megas cannot heal unlike menders which are capable of doing that.
1 control a mega 2 build a building but dont finish it 3 get a unit to get a hit on the building 4 attempt to heal with the mega youre controlling, or any mega.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
unit factory mod was only used to check if the bug was real.
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

i have no idea how to get a zip file from le game. but i can asure you it works on any game. just do the steps 

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional.

**Comment by joshuaptfan** [comment]
I've noticed if you lose a campaign sector and come back, megas will not automatically heal the damaged buildings that are leftover from your previous game, even though they are owned by you.
