### ISSUE TITLE
Game does not save state sometimes

### ISSUE THREAD

**Issue by Soham-maiti** [Anuken/Mindustry#4331]
**Platform**: Android

**Build**: 122.1

**Issue**: So each time i press save and quit it should save but it seems to save to its liking of which time it shall save the gameplay.

**Steps to reproduce**: first time it occurred when i was in middle of destroying another sector and i saved but next day it seems i never went to the sector at all.

**Link(s) to mod(s) used**: N/A

**Save file**: Could not find it.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save, cannot reproduce.

**Comment by Soham-maiti** [comment]
How do i get the save file?
