### ISSUE TITLE
sorter cross doesn't render for schematics

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4334]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20521`

**Issue**: empty sorters don't show a cross in schematics

**Steps to reproduce**: try to save a schematic containing a sorter with no item filter set:

![Screen Shot 2021-01-15 at 13 24 17](https://user-images.githubusercontent.com/3179271/104727207-3b050500-5735-11eb-8c32-48707dd28263.png)
![Screen Shot 2021-01-15 at 13 24 25](https://user-images.githubusercontent.com/3179271/104727212-3c363200-5735-11eb-845f-f8b97a86494b.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
as are their ghosts:

![Screen Shot 2021-01-15 at 13 33 39](https://user-images.githubusercontent.com/3179271/104727845-54f31780-5736-11eb-9a3a-6faf334fb372.png)
![Screen Shot 2021-01-15 at 13 33 55](https://user-images.githubusercontent.com/3179271/104727849-56244480-5736-11eb-983b-b355545355f1.png)

**Comment by XEN0PHIL** [comment]
![image](https://user-images.githubusercontent.com/55051135/104735228-69dda400-5752-11eb-87a4-b91db6ae7c94.png)
Do you like how it looks? :thinking:

**Comment by Quezler** [comment]
item icons were outside the scope of this issue, but i guess that would make sense

**Comment by XEN0PHIL** [comment]
Don't forget about item/liquid sources.
![image](https://user-images.githubusercontent.com/55051135/104736565-3734ab00-5754-11eb-92cc-8cc46b6150c0.png)

If it's possible, I'd apply the fix to ghosts and schematics, but will leave building menu sprites unchanged.
