### ISSUE TITLE
10 of each items on a roomba conveyor

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#4335]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
release 122.1 and bleeding edge 20525 (worked in both versions)

**Issue**: *Explain your issue in detail.*
you can put 10 *of each* item on a roomba conveyor (for noobs: plastanium conveyor)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
watch attached video

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[video.zip](https://github.com/Anuken/Mindustry/files/5821957/video.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
The zip has a save file in it, correct? If not, hand over your soul.

**Comment by antonilol** [comment]
the video is enough

**Comment by antonilol** [comment]
there is no save file in there by the way

**Comment by Quezler** [comment]
yes, i've noticed, its part of the code that always allows players to dump their items in it, though it should probably check against which item is already in there yet infront of the cooldown checks and such, here's the related line:
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/StackConveyor.java#L301

**Comment by Erisfiregamer1** [comment]
I was about to say to hand over your soul. However, I still request a save file so Anuke doesn't just instantly close this.

**Comment by antonilol** [comment]
if anuke instantly closes it its his problem i only try to help

**Comment by Erisfiregamer1** [comment]
Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

Look above, and please listen. Too many issues were closed because of this. Hence, the REQUIRED part.

**Comment by antonilol** [comment]
ok you like rules
Quezler already found where the problem is

**Comment by antonilol** [comment]
he can make a nice pull request or edit and its all solved

**Comment by Quezler** [comment]
now stop commenting on this before everyone's mailbox overflows:
(only react to this with a thumbs up emoji for acknowledgement)
<img width="1119" alt="Screen Shot 2021-01-15 at 18 18 47" src="https://user-images.githubusercontent.com/3179271/104758087-2ab55000-575e-11eb-88e6-fe25525b104f.png">

**Comment by catatagun** [comment]
> now stop commenting on this before everyone's mailbox overflows:
> (only react to this with a thumbs up emoji for acknowledgement)
> <img alt="Screen Shot 2021-01-15 at 18 18 47" width="1119" src="https://user-images.githubusercontent.com/3179271/104758087-2ab55000-575e-11eb-88e6-fe25525b104f.png">

Gun cat says no
