### ISSUE TITLE
Sector Lost After Crash

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#4339]
**Platform**: *Android*

**Build**: *122.1.*

**Issue**: *when going to a captured Sector, the game crashes and when you go back, you lost the sector."

**Steps to reproduce**: *i really don't know how to reproduce this bug.*

**Link(s) to mod(s) used**: *
deltanedas/dev-mode
deltanedas/ui-lib
Deltanedas/pictologic
(The rest are disabled)
.*

**Save file**: *none.*

**(Crash) logs**: *[crash_1610761211336.txt](https://github.com/Anuken/Mindustry/files/5823681/crash_1610761211336.txt)

It happened two times, this was with ground zero and the another was Biomass synthesis facility but i didn't find the crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce, likely caused by mods.
