### ISSUE TITLE
Multiple liquid routers/bridge conduits in series can significantly reduce line throughput 

### ISSUE THREAD

**Issue by Halfeclipse** [Anuken/Mindustry#4340]
**Platform**: Windows 

**Build**: Steam Build 122.1

**Issue**: Bridge conduits in series with each other or with routers will deeply throttle water throughput, often well below 200/s. This more or less makes bridge conduits unusable if you want to move more than one thermal pump or similar output. It's possible slag/oil/cyro are also effected but I've not tested that. Sufficient distance between them mitigates the issue and the effect seems to reduce over distance

**Steps to reproduce**: Place a bridge conduit or router in series with bridge conduits or liquid routers in relatively close proximity and run water through them. They do not need to be directly adjacent.  I've not tested the falloff distance for the issue, but will comfortable occur within a dozen pipe pieces. The issue occurs most consistently with 2+ bridge conduits or a bridge conduit followed by a router. Possibly related to part of the line being at maximum throughput? See this imgur album for screenshots: https://imgur.com/a/KM2mn9v. 

**Link(s) to mod(s) used**: Only mod installed is RTFM: https://github.com/DeltaNedas/rtfm

**Save file**: 
[sector-serpulo-162.zip](https://github.com/Anuken/Mindustry/files/5823719/sector-serpulo-162.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) because Steam**. 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. These blocks have very low throughput, as well as backflow.

**Comment by scarf-generic** [comment]
they arent overdriveable either. i reccomend avoiding liquid bridges/routers as much as possible and using liquid tanks instead to split liquids, as to not drastically reduce throughput.

**Comment by Halfeclipse** [comment]
> Not a bug. These blocks have very low throughput, as well as backflow.

To be clear, you're aware I'm not saying it has less than a pulse conduits throughput yes?

A bridge conduit should be able to move 300 water per second.  More than one bridge conduit even vaguely near each other in series will throttle the line to less than *half* that. You mean this is intentional behavior? Like components that aren't adjacent or otherwise directly connected to one another  are intended to interact in a severely negative way? This makes bridge conduits, as scarf-generic notes, something to avoid using all together since they move far less than even a regular conduit.  That's the actual intention here? 

Bridge conduits are directional, take input and output from directional conduits, have specific inputs and outputs, and they can't output from the input nor can they take input at the output. If they can backflow at all that's problematic behavior.

**Comment by Anuken** [comment]
> To be clear, you're aware I'm not saying it has less than a pulse conduits throughput yes?

Yes.

> A bridge conduit should be able to move 300 water per second. More than one bridge conduit even vaguely near each other in series will throttle the line to less than half that. You mean this is intentional behavior? Like components that aren't adjacent or otherwise directly connected to one another are intended to interact in a severely negative way? This makes bridge conduits, as scarf-generic notes, something to avoid using all together since they move far less than even a regular conduit. That's the actual intention here?

Yes.

> Bridge conduits are directional, take input and output from directional conduits, have specific inputs and outputs, and they can't output from the input nor can they take input at the output. If they can backflow at all that's problematic behavior.

*Bridges* cannot backflow, but as they use the same flow system as routers do, they have significantly lower throughput than normal conduits. This may be changed some day, but as of right now, I don't expect them to have particularly good throughput.
