### ISSUE TITLE
Bridges don't remember their connections when using a scheme/copy

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#4343]
**Platform**: Windows

**Build**: BE 20528
**Issue**: When building bridges from a schematic or copying them, bridges do not keep their previous connections.

**Steps to reproduce**: 
1. Save a schematic of bridges with custom connections (example in a video);
2. Build it;
3. Observe their wrong connections.
[Video demo:](https://user-images.githubusercontent.com/55051135/104812692-11230f80-5815-11eb-819d-c282246d8cf9.mp4)

**Link(s) to mod(s) used**: DeltaNedas/dev-mode

**Save file**: [20528_bridge_report.zip](https://github.com/Anuken/Mindustry/files/5824420/20258_bridge_report.zip) (made a typo in a file's name, 258 instead of 528)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
rotating a schematic from its initial position seems to play a role

**Comment by Catchears** [comment]
can happen with phase conveyors as well
