### ISSUE TITLE
"Disabled" launchpads do not use any power but function properly

### ISSUE THREAD

**Issue by BlueCapacitor** [Anuken/Mindustry#4345]
**Platform**: *Android*

**Build**: *12.2.1*

**Issue**: *According to #3557, launchpads can not be disabled. If they are disabled with a processor, they continue to function normally. However, if they have been disabled by a processor, they no longer use any power.*

**Steps to reproduce**: *Capture a sector in campaign, make a launch pad, make a processor, disable the launch pad using the processor, fill the launch pad with items, the launch pad will launch not using any power*

**Link(s) to mod(s) used**: *None*

**Save file**: *[save C7.zip](https://github.com/Anuken/Mindustry/files/5824545/save.C7.zip)*

**(Crash) logs**: *N/A*

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by catatagun** [comment]
NOOOOO MY SECRET WEAPON
