### ISSUE TITLE
Sappers don't render when AI or autotarget is used to fire

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4349]
**Platform**: *Android*

**Build**: *122.1*

**Issue**: *Sapper lasers are only visually showing when manually firing. AI and autotarget do not show the visuals.*

**Steps to reproduce**: *Duel an arkyid.*

**Link(s) to mod(s) used**: *Irrelevant. I found this out originally with Exotic Mod's navals but then reproduced it with vanilla units.*

**Save file**: *Reproduced on multiple maps, save does not matter.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

i am still waiting

**(Crash) logs**: *no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the most recent closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_20210116-130758](https://user-images.githubusercontent.com/61173114/104821972-d0b79780-57fc-11eb-9308-502b6e5dd319.png)

**Comment by joshuaptfan** [comment]
You should still include a save in a test sandbox map to save Anuke time.

**Comment by BlueWolf3682** [comment]
its literally just spawning two arkyids and letting them fire at each other without possessing either of them, or possessing one and using mobile autotarget

**Comment by blool22** [comment]
that doesn't happen with auto-target, it doesn't render if it hits an enemy but renders if it hits a wall or a building
