### ISSUE TITLE
Doors cannot be toggled if attached to a door that will be built

### ISSUE THREAD

**Issue by vb0t** [Anuken/Mindustry#4351]
**Platform**: Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 122.1

**Issue**: *Explain your issue in detail.*
When constructing a large amount of connected doors from a schematic or copy/paste, it will force the doors into the state they were originally if you try to open/close, until the blueprint is done building.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
put down a lot of touching doors, using F copy and paste, when building, try to toggle the already built ones.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
See the attached

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[attach'd.zip](https://github.com/Anuken/Mindustry/files/5825241/attach.d.zip)
I'm not sure if this is a bug, so apologies if it isn't.

**Comment by Anuken** [comment]
Not a bug. When you place a new door, it is automatically configured, which makes all nearby blocks match its configuration.
