### ISSUE TITLE
Chained overflow gates not working

### ISSUE THREAD

**Issue by rMuchan** [Anuken/Mindustry#4359]
**Platform**: Mac

**Build**: Steam 122.1

**Issue**: An overflow gate treats another as blocked. (If this is the expected behavior, please remove "Max Consecutive: 2" from its description.)

![image](https://user-images.githubusercontent.com/13314764/104846122-f7b4bd00-5913-11eb-883b-032e9fe63bb8.png)

**Steps to reproduce**: Build the following schematic in a sandbox world, and observe.

> bXNjaAF4nD2OfQ7CIAzFH5TNmMU/NB5gF9ihlq0aEkcNMIy3lw+VpvT15UcLehw0jJs3xkUS+9tDXmMKYxAf2WNYOSzePqMVB3QYbORtCrL7hXGONs7O7tu0iEv8Fo/+++5YuSR2xek3drrPkQFcUU6XUxVhqlKtKcUAOkclcquLSdVSJl85i9k1s4fSoD9MDaYGU4OpwVTgOh51SxbUvlGKgfoAVsclnA==

**Link(s) to mod(s) used**: None

**Save file**: Just use the schematic. It's kind of easier than importing a save.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
`instantTransfer = true` blocks have max consecutive stat hardcoded as 2, this should just be made a field

**Comment by Anuken** [comment]
Not a bug.

**Comment by DeltaNedas** [comment]
but anuke the stat says it can have 2 overflows consecutively, yet only 1 works.
how is that not a bug?

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/issues/1657#issuecomment-593747420
https://github.com/Anuken/Mindustry/issues/1178#issuecomment-562861329

> but anuke the stat says it can have 2 overflows consecutively

No, it doesn't. That refers to other 'instant transfer' blocks.

**Comment by rMuchan** [comment]
> That refers to other 'instant transfer' blocks.

It's explicitly stated under Overflow Gate.

![image](https://user-images.githubusercontent.com/13314764/104888189-5f681800-59a7-11eb-82da-f21819125bb7.png)
