### ISSUE TITLE
Payload.write is not public static in Android

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4361]
**Platform**: *Android vs Windows*

**Build**: *Android: release build 122.1, Windows: steam 122.1*

**Issue**: *Payload.write is not public static only in Android.*
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/payloads/Payload.java
```java
static void write(@Nullable Payload payload, Writes write){
        if(payload == null){
            write.bool(false);
        }else{
            write.bool(true);
            payload.write(write);
        }
    }
```

https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/production/PayloadAcceptor.java (vanilla implementation)
```java
@Override
        public void write(Writes write){
            super.write(write);

            write.f(payVector.x);
            write.f(payVector.y);
            write.f(payRotation);
            Payload.write(payload, write);
        }
```
However, the function write() will be unavailable to use for mods, only in Android.
Windows (works normally):
![image](https://user-images.githubusercontent.com/58885089/104863938-e81c8f00-597a-11eb-9768-85ee24f36d0f.png)
Android:
![image](https://user-images.githubusercontent.com/58885089/104863964-f9659b80-597a-11eb-993c-e52a0fb93ce5.png)

**Steps to reproduce**: *`Payload.write` in console.*
I would like to know exactly what causes this and what other functions will also be affected in this manner, if this issue is unfixable.

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null, the IOException caught it anyways:*
![image](https://user-images.githubusercontent.com/58885089/104864035-2fa31b00-597b-11eb-9ac4-4016256baff1.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Likely caused by Java 8 desugaring of static interface methods. Workaround: Just inline the method body, it's only 6 lines.

**Comment by Anuken** [comment]
(honestly, the payload type mapping system code really needs an update; it would be nice if types were registered dynamically somewhere)

**Comment by sk7725** [comment]
I definitely agree, I gave up trying to mod in PlayerPayloads(payloads you can control to hitch a fun ride) because of that.
(Also are you hinting new payload types? 👀)
