### ISSUE TITLE
Naval unit path finding 

### ISSUE THREAD

**Issue by PrinceofhellAzazel** [Anuken/Mindustry#4362]
**Platform**: `Android 28`

**Build**: `release build 122.1`

`the naval units are having trouble path finding i believe it is connected to the unit controller specifically when it is set to rally though the glitch would happen with both mine and the enemy's units i have a screen capture of it happening and the save file but i cant figure out how to post them here i can be reached at thorthegodofthunder709@gmail.com for both`

**Steps to reproduce**: *i was on windswept isles with both tier one and two navel units with the controller*

**Link(s) to mod(s) used**: `none`

**Save file***`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quick-korkc** [comment]
just attach the file here bruh
or Anuke will just close this
