### ISSUE TITLE
Game crashed c++ runtime library assertion failed

### ISSUE THREAD

**Issue by eric15342335** [Anuken/Mindustry#4364]
**Platform**: *Windows 10 1909*

**Build**: *v6 122.1*

**Issue**:
![image](https://user-images.githubusercontent.com/70310617/104899376-bc6aca80-59b5-11eb-9c27-b0877094c4ed.png)

**Steps to reproduce**: *Idk*

**Link(s) to mod(s) used**: *no*

**Save file**: [game.zip](https://github.com/Anuken/Mindustry/files/5829394/game.zip)

**(Crash) logs**: *Idk*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
> Steps to reproduce: Idk

if anuke cant reproduce this by starting mindustry do you think he can fix it

**Comment by BlueWolf3682** [comment]
this smells familliar and i dont know why

**Comment by Anuken** [comment]
Duplicate.

**Comment by DeltaNedas** [comment]
not exactly, its a different assertion
but thats all thats different
