### ISSUE TITLE
distributor limited

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#4366]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
release build 122.1

**Issue**: *Explain your issue in detail.*
the distributor cant handle 4 overdriven titanium conveyors full of items

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
build the schematic in the zip and watch

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[distributor.zip](https://github.com/Anuken/Mindustry/files/5830315/distributor.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
it technically can but its limited by your fps.

**Comment by antonilol** [comment]
no, server tps
speed is exactly 60 items/sec

**Comment by antonilol** [comment]
4 overdriven titanium conveyors is 4 * 10 * 2.5 = 100 items/sec

**Comment by itcannotbe** [comment]
So it's not a bug, but a game limitation. End of story.

**Comment by DeltaNedas** [comment]
speed could be doubled to increase throughput
but then distributor chain would be h

**Comment by GreyMario** [comment]
It's not going to be changed. If you need to distribute four overdriven titanium belts, use two distributors (not touching).

_One item per tick is more than enough._ And stop trying to maximize item _speed_.

**Comment by Anuken** [comment]
> the distributor cant handle 4 overdriven titanium conveyors full of items

It's not supposed to be able to.
