### ISSUE TITLE
bleeding edge update progress bar doesnt show up under 6 MB

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#4367]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
be 20528

**Issue**: *Explain your issue in detail.*
bleeding edge update progress bar doesnt show up under 6 MB

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
update your bleeding edge mindustry and watch

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[be_update.zip](https://github.com/Anuken/Mindustry/files/5831257/be_update.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by antonilol** [comment]
corresponding line of code
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/net/BeControl.java#L124

**Comment by Anuken** [comment]
I don't care about the BE update system.

**Comment by DeltaNedas** [comment]
(make a pr and fix it yourself, you even have the code)

**Comment by antonilol** [comment]
i just found out that when `progress[0] < 0.1f` the bar doesn't show up
(or `<=` don't know exactly)
