### ISSUE TITLE
Game Audio Doesn’t Play Through Phone Speakers

### ISSUE THREAD

**Issue by DJ2638** [Anuken/Mindustry#4369]
**Platform**: `iOS x32`

**Build**: `release build 122.3`

**Issue**: ‘The game audio, like the music and sound effects, does not play through my phone speakers even with volume all the way up. The only time that the audio ever plays is if I have headphones connected. Because I have an iPhone I only use Bluetooth earbuds, so I don’t know if it works with wired earbuds, but I imagine it would. I do not believe this has anything to do with my particular game.’

**Steps to reproduce**: ‘I am using an iPhone SE second GEN. I first noticed the issue after the most recent major update. When I opened the game after the update, I immediately noticed the lack of music. I tried adjusting volume on my phone, adjusting game settings, but ultimately found that the audio only plays through headphones.’

**Link(s) to mod(s) used**: `none`

**Save file**: 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/5831478/mindustry-data-export.zip)

**Crash report**: 
[logs.txt](https://github.com/Anuken/Mindustry/files/5831486/logs.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works on my one and only iOS device. This cannot be reproduced or fixed.

**Comment by BlueWolf3682** [comment]
Unable to reproduce, iPod Touch 6 tested.
