### ISSUE TITLE
OverFlow Gate Crashing the game.

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#4376]
**Platform**: *Windows*

**Build**: *20541*

**Issue**: *I was just placing overflow and sorters, a lot of them, while items were flowing through them. Suddenly, the game crashed with an error.*

**Steps to reproduce**I couldnt reproduce.**

**Link(s) to mod(s) used**: *None*

**Save file**: *The (zipped) sa

[crash-report-01_19_2021_10_01_50.txt](https://github.com/Anuken/Mindustry/files/5834197/crash-report-01_19_2021_10_01_50.txt)

ve file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by catatagun** [comment]
BUILD 20541

do you mean bleeding edge

**Comment by BlueWolf3682** [comment]
WOW thats a fricking long crash report

**Comment by RebornTrack970** [comment]
The save file was about 54mb without any content mods and screenshots. i had to remove some saves so i can upload.
[savedata.zip](https://github.com/Anuken/Mindustry/files/5834251/savedata.zip)

**Comment by itcannotbe** [comment]
Not the whole thing just the map where the crash happened.....

**Comment by RebornTrack970** [comment]
[252.zip](https://github.com/Anuken/Mindustry/files/5834272/252.zip)
oh

**Comment by QmelZ** [comment]
i am failing to recreate this, the data and the last save works fine.

**Comment by antonilol** [comment]
@RebornTrack970 i suggest removing your savedata. Others who import the data can play on servers on your behalf.

**Comment by Quezler** [comment]
i've managed to reproduce it, just place a conveyor here:

![Screen Shot 2021-01-19 at 10 39 25](https://user-images.githubusercontent.com/3179271/105016216-a9520c00-5a42-11eb-8f13-58e4b1786fa9.png)

**Comment by itcannotbe** [comment]
Also Crashes with anuke.

bXNjaAF4nDXL7U6DMBSA4UOhLRM3NsH/3gAXYXYlZFYlCjV8zHj30r7pEvak57xHnuWgpJj60Un1Om1f7uU698unVG9uuc3Dzzr4SSSXaljd2C1+m29OLuuw9tOwjd3NT3f352c5+rub37/9b/fRr05ErhJ+ev+yLPxBLpnaKUQU24ABC2UgY5jxUhwoDhQ7xYEiyUmKhAYDFmKpwVAaSkNpKA2JJSkTGgxYiOWB5CGhwYCFWFYkjwkNBizE8sjwRHJKr5jUnNfs6jSMd2d2Z14XXk87WUCDAQtloCFp2DUMW4YtwzYM/wHZkiAt

**Comment by Quezler** [comment]
basically any looping circle out of overflow gates ^

**Comment by itcannotbe** [comment]
[The piece if code that stops this from happening to sorters](https://github.com/Anuken/Mindustry/blob/8fab335b9dc79e5ce15d23762d3855da507fa8c0/core/src/mindustry/world/blocks/distribution/Sorter.java#L102)
