### ISSUE TITLE
Efficiency information inconsistency

### ISSUE THREAD

**Issue by CaeciliusInHorto** [Anuken/Mindustry#4380]
**Platform**: `Mac OS X x64`

**Build**: `release build 122`

**Issue**: *Explain your issue in detail.*

In the core database, most tile efficiency changes are listed by the per tile change (e.g. the silicon crucible lists the efficiency change from magma as 11%, this is per tile the crucible is on) but the Oil Extractor lists efficiency changes for the whole block (e.g. it lists 150% on dark sand, this is for the whole block).

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Look at various efficiency changes in the core database
Look at oil extractor
Compare

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[empty.msav.zip](https://github.com/Anuken/Mindustry/files/5837756/empty.msav.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a problem.

**Comment by DeltaNedas** [comment]
what if oil extractor is actually multiplied by 2.5x, or the smelter by 0.11x? it's ambiguous.
a +50%/+11% should be used, or if its actually multiplying a *n*x thing

**Comment by HaphLife** [comment]
This really annoys me. Please actually fix this Anuke. Consistency is actually pretty important. Also it’s not that hard to fix. Just change one of the numbers to be formatted like the other. (I recommend +n%/tile, out of the two it’s more useful)

**Comment by Anuken** [comment]
> This really annoys me. 

No. Unlike water extractors, oil extractors have a base efficiency of 0. If I see a patch of sand and look at the stats, I can immediately figure out what efficiency it will have. I don't want to multiply some number *9 in my head to figure it out.

**Comment by HaphLife** [comment]
Then change the silicon numbers if you like the way the extractor is better. Just make them use the same numbering system.

**Comment by HaphLife** [comment]
*oil extractors, not silicon crucibles.

**Comment by HaphLife** [comment]
tho they are also different.
