### ISSUE TITLE
Map upload to steam workshop not working 

### ISSUE THREAD

**Issue by Jornker** [Anuken/Mindustry#4381]
**Platform**: `Windows 10 x64`

**Build**: `steam build 122.1`

**Issue**: *I've recently finished a map that I've spent 20+ hours on, it won't let me upload to workshop*

**Steps to reproduce**: *Made a map, 500x500 size, filled it with stuff, try to upload - link of issue https://youtu.be/cRU-9G3SPB0 *

**Link(s) to mod(s) used**: *N/A*

**Save file**: *Map Save that is not working - 
https://drive.google.com/file/d/1gKKWKc8eCv-R2JtBfuvMxsNh0d9QDlY1/view?usp=sharing*

**Crash report**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't find any specific information about this, but it may be caused by large Steam cloud saves, e.g. excessive amounts of saves/mods/screenshots/maps. Try clearing some of your game data and trying again. If that doesn't work, there's not much I can do.
