### ISSUE TITLE
Broken campaign

### ISSUE THREAD

**Issue by powerneek** [Anuken/Mindustry#4387]
**Platform**: android

**Build**: 122.1

**Issue**: my campaign is broken for some reason

**Steps to reproduce**: reseting your campaign safe file for alot of time

**Link(s) to mod(s) used**: non

**Save file**: idk how to send it

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not usable information.
