### ISSUE TITLE
Power nodes

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#4390]
**Platform**: *Android/pc*

**Build**: *123*

**Issue**: *power nodes connects on things it shouldn't*

**Steps to reproduce**: *
1: make 2 power nodes and connect them.
2: copy them.
3: remove one of the nodes.
4: put anything on the place the removed node was.*

https://1drv.ms/u/s!AnYf7oxSZjN8gUpHbtxOL05BCOKP
(I couldn't upload the file on github because it sucks)

**Link(s) to mod(s) used**: *none.*

**Save file**: *is it REALLY necessary in cases like this? The bug is easy to reproduce, it can be done on any map, at any time. (Answer please)"

**(Crash) logs**: *h.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
![Screenshot_01:30:25](https://user-images.githubusercontent.com/39013340/105263415-479bba00-5b88-11eb-9527-ad91dd39cb80.png)

**Comment by Anuken** [comment]
Not a bug. Nodes remember connection positions.

**Comment by rodrigolitzius** [comment]
> Not a bug. Nodes remember connection positions.

But... They shouldn't connect to other blocks right?

**Comment by Anuken** [comment]
They should.

**Comment by antonilol** [comment]
They also connect over plastanium walls
