### ISSUE TITLE
unitHealthMultiplier didn`t take effect

### ISSUE THREAD

**Issue by linglan512572354** [Anuken/Mindustry#4395]
**Platform**: *All*

**Build**: *v123*

**Issue**: *the unitHealthMultiplier in rules didn`t take effect.*

**Steps to reproduce**: *search unitHealthMultiplier in the source code, it only displays in the edit dialog and translates files.*

**Link(s) to mod(s) used**: *no mods.*

**Save file**: *didn`t need.*

**(Crash) logs**: *no crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'll remove it, as PvP has had it as 3x for a long time. Making it functional now would break balance.
