### ISSUE TITLE
Research tree

### ISSUE THREAD

**Issue by BeefEX** [Anuken/Mindustry#44]
Draft for a research system.

Ideas for getting research points (RP):
 - Material to RP
 - RPs for beating waves

Ideas for research effects:
 - Unlock machines
 - Upgrade machines

Ideas for the UI:
- ![By Trollex on Discord](https://cdn.discordapp.com/attachments/396416151032299521/397789607560740864/Mindustry_tech_tree_1.png)

Feel free to comment more ideas.

**Comment by Epowerj** [comment]
Personally, I don't think that Mindustry needs a tech tree. Firstly, this adds some complexity to the game. Second, I think that the game will have a naturally occurring tech tree. You will need to build certain things to be able to get resources required to build the next better thing. A lot of games with crafting, such as Terraria or modded Minecraft, use this kind of system. To get the next best pick, you need to have the previous tier pick to be able to mine the resources needed to craft the better one.

**Comment by Luxray5474** [comment]
I completely agree with @Epowerj. Mindustry has absolutely no need for a tech tree. It makes things more complicated and subtracts from the fun of the game. It is also another **cliche** feature, and really, the game should be different and unique.

**Comment by Epowerj** [comment]
I think it's best to wait until we start working on the RTS aspects before we spend more time on something like this.

**Comment by Anuken** [comment]
Moved to #87.
