### ISSUE TITLE
cultivator uses power while requirements aren't met

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4403]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20594`

**Issue**: cultivator uses power even if it has no water:

![Screen Shot 2021-01-21 at 20 49 29](https://user-images.githubusercontent.com/3179271/105404388-2f7c7700-5c2a-11eb-8241-9720f36eca8c.png)

**Steps to reproduce**: create a power that includes the blocks from the screenshot, or use this schematic:

`bXNjaAF4nFWLQQ7CMAwElzi0qLyljzKtD5FCHLkGxN9BhooTexrNaDFiSMiNr4JpuVUvd3Y1nFfZFivdizYg/7dNK9vcuUnF1PUhNjddBeOF3cWe2B/fJaQD6EcZdKKIeO82XhFEGHAEPjbGIrM=`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XEN0PHIL** [comment]
Blocks that also drain power:
- Mass driver (no targeting, no resources);
- Block forge (no selection, no resources).
