### ISSUE TITLE
Logic max string length causes issues with mods

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4405]
**Platform**: Windows

**Build**: 123.1

**Issue**: The unit named `real-life-mindustry-mod-winged-demon` cant be bound in logic as its name is so long that it's truncated. It ends up as `@real-life-mindustry-mod-winged-demo`

**Steps to reproduce**: Literally just try binding the unit in a logic block

**Link(s) to mod(s) used**: https://steamcommunity.com/sharedfiles/filedetails/?id=1993262831

**Save file**: 
[601.zip](https://github.com/Anuken/Mindustry/files/5852248/601.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This won't be changed. Use a shorter mod or unit name.

**Comment by DeltaNedas** [comment]
rlmm-demon
