### ISSUE TITLE
Workshop's schematics are not available offline

### ISSUE THREAD

**Issue by Khanx** [Anuken/Mindustry#4406]
**Platform**: Windows (Steam version)

**Build**: Steam build 123.1

**Issue**: 
Steam's schematics (from **workshop**) are not available while playing **offline**.

Yesterday I was playing the campaign and lost internet.
After restarting the game I noticed that I didn't have access to the workshop's schematics.

**Steps to reproduce**:
1- Subscribe one schematic in the workshop (Steam)
2- Download the schematic
3- Disconnect internet or start steam in offline mode
4- Start the game and try to place the subscribed schematic (It won't appear)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not easily fixable. Workshop files are stored in a different location, which is not available when Steam fails to initialize.

**Comment by Khanx** [comment]
Are the workshop files not stored in ... \Steam\steamapps\workshop\content\1127400\ ... ?
