### ISSUE TITLE
Mindustry Android doesn't load classes.dex on jar

### ISSUE THREAD

**Issue by Volas171** [Anuken/Mindustry#4408]
**Platform**: *Android  SDK Version 24*

**Build**: *123*

**Issue**: *its search for .class file instead using classloader to find 
![image](https://user-images.githubusercontent.com/49940811/105441450-ea2b6a00-5c68-11eb-84d3-583a07d28039.png)
while Platform.loadJar capable for searching on dexed jar
![image](https://user-images.githubusercontent.com/49940811/105441551-1cd56280-5c69-11eb-9ac0-01602d59b7b5.png)
result: it can't find class to load while the class is inside classes.dex\
mods structure
![image](https://user-images.githubusercontent.com/49940811/105441672-5908c300-5c69-11eb-8912-fab1d2cc84d2.png)

**Steps to reproduce**: *Get android phone, copy dexxed jar mods to mods folder, open mindustry, nothing loaded despite being detected*

**Link(s) to mod(s) used**: *https://cdn.discordapp.com/attachments/708815862664134678/801767865543426048/Ozone-Android.jar*

**Save file**: *no*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**logs**: 
![victim](https://cdn.discordapp.com/attachments/708815862664134678/801768837829754890/unknown.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
BetaMindy(dexed jar mod) works in Android. Maybe you got something wrong with your mod's dx or d8?

**Comment by sk7725** [comment]
Maybe your mod used some different method that was deprecated or something. BetaMindy managed this, try checking it out(or sonnicon's template) to see how it was managed.
Also, I'm pretty sure doing some modloader changes *will* break the mods that did the dex this way, please let that not happen.

**Comment by Anuken** [comment]
Dexed jars without corresponding classes are not supported.

**Comment by DeltaNedas** [comment]
whats the reasoning behind that? it would make android-only builds a lot smaller

**Comment by Anuken** [comment]
> android-only builds

"Android-only" builds should not exist.

> it would make android-only builds a lot smaller

You need a *lot* of code for that to make a significant difference.

> whats the reasoning behind that?

Class file existence is used to detect Java mods.

**Comment by Volas171** [comment]
nvm, I added dummyPremain/EntryPoint.class to make it load

**Comment by Volas171** [comment]
> it would make android builds a lot smaller
indeed
![BB12EEF8-B29C-4245-A92A-C5D2D0AA87FC](https://user-images.githubusercontent.com/60143910/105516947-714a0380-5ca4-11eb-8f64-7b16a807da77.jpeg)

**Comment by Volas171** [comment]
and just for the archive
![04DB6258-9772-4D74-9E72-CFDD8A5A3317](https://user-images.githubusercontent.com/60143910/105621592-2ed51380-5dd7-11eb-9438-610c4a70f933.png)
