### ISSUE TITLE
Crash on server while using payload

### ISSUE THREAD

**Issue by Slava0135** [Anuken/Mindustry#4410]
**Platform**: *Linux*

**Build**: *123.1*

**Issue**: *Crash...*

**Steps to reproduce**: *Was playing on server. Some nerd was picking up stuff and for whatever reason my game crashed*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crash-report-01_22_2021_12_17_59.txt](https://github.com/Anuken/Mindustry/files/5854754/crash-report-01_22_2021_12_17_59.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
soul reaping time

**Comment by Erisfiregamer1** [comment]
slava run anuke is coming for you

**Comment by Anuken** [comment]
*no save, cannot reproduce*
