### ISSUE TITLE
Crawlers don't explode next to core

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#4416]
**Platform**: Windows/Linux, not checked others

**Build**: 123.1, broken since 123

**Issue**: Crawlers don't explode despite standing next to the enemy target core. If I place a wall next to them, they do, but I don't think enemy core is unimportant building to be ignored by crawlers. They also used to explode until 123 build, so I believe something is broken here.

**Steps to reproduce**: Make enemy crawler factory, wait for them to reach your core.

**Link(s) to mod(s) used**: no mods

**Save file**: 
![image](https://user-images.githubusercontent.com/4199082/105573343-820e7e00-5d65-11eb-899d-ea5cff6a890a.png)
Not a save, but maps to reproduce. Just start them in sandbox mode.
[crawler1.zip](https://github.com/Anuken/Mindustry/files/5859935/crawler1.zip)
[crawler2.zip](https://github.com/Anuken/Mindustry/files/5859936/crawler2.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. **please don't**

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
can confirm, its been happening for 1-2 weeks on nydus bleeding edge as well

**Comment by Erisfiregamer1** [comment]
this didnt patch it, my testing map on BE had the issue still

**Comment by Anuken** [comment]
No issues here.

![2021-02-01 09-26-28](https://user-images.githubusercontent.com/10100000/106471418-98a48b80-646f-11eb-80ce-788c0f566bfc.gif)
![2021-02-01 09-26-02](https://user-images.githubusercontent.com/10100000/106471421-9a6e4f00-646f-11eb-971e-33ca7b4f2ce6.gif)
