### ISSUE TITLE
StatusEffect speedMultipliern't

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#4420]
**Platform**: *Windows*

**Build**: *Steam 123.1*

**Issue**: *`speedMultiplier` does not work. It has no effect on a unit's speed.*

**Steps to reproduce**: 
Since the `speedMultiplier` of `StatusEffects` do not downright work at all, there are a lot of ways to reproduce this.
1. In console: `Vars.player.unit().apply(StatusEffects.freezing, 600);` Notice that you are not slown down.
2. Do 1 but for overdriven/overclocked. Notice that you do not have faster speed.
3. With mods with dramatic `speedMultipliers` such as 2f or -1f, you can more clearly see this issue.
I know that it worked before (how far in the past? I don't know sadly) but it suddenly does not work and I am bamboozled.

**Link(s) to mod(s) used**: *sk7725/BetaMindy (is this relevant?)*

**Save file**: *codewise issue*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
speed multiplier effects haven't worked properly for player controlled unit since the dawn of v5

**Comment by sk7725** [comment]
> speed multiplier effects haven't worked properly for player controlled unit since the dawn of v5

no, for all units; I have also bothered some daggers, alphas and reigns which are not player-controlled, and even player-controlled units worked fine before

**Comment by Anuken** [comment]
> speedMultiplier does not work. It has no effect on a unit's speed.

It does. Try setting the speed multiplier of freezing to 0.0001 or some other positive low number. It's very noticeable. 

It seems that only speed multipliers > 1 do not work.

**Comment by sk7725** [comment]
I did not notice the slowing down in StatusEffects.freezing, but guess that means I'm just blind...

**Comment by bvcbvc** [comment]
programming is funny, but yea unit speed multiplier is kinda buggy
