### ISSUE TITLE
corrupted campaign sectors (previously oppened in release 123.1) after opening release 122.1 by mistake

### ISSUE THREAD

**Issue by benji78** [Anuken/Mindustry#4421]
**Platform**: `Windows 10 x64`

**Build**: `release build 123.1 & 122.1`

**Issue**:
I recently downloaded itch.io, to have release 123.1 and easier updates, because I wasn't able to join servers on 122.1. However I created a save, and kept 122.1 on my computer. But when I started  the game today from a shortcut I created earlyer on, the 122.1 release launched (which I din't realise), and, **without warnings**, I was able to open a sectors giving me a corrupted save popup that I dismissed without thinking. I saw that I didn't have the proper core launched and that all my progress on this sector had been reset. So I naively went to ground zero and did the same thing. Fortunately I stopped there, closed the game oppened release 123.1 from its file location and created a save with the two corrupted sectors. I did a bunch of tests and came to the conclusion that I had just lost more than 5 hours worth of progress.
The only thing that was saved was the amount of resources I used to last launch to a new sector meaning I have thoses resources in the cores of the two corrupted sectors.
This could have been avoided if, when the save is from a higher version than the current game release, there were a popup, when opening mindustry, warning that a backup should be made and that this ation can corrupt the game save.

**Steps to reproduce**:
Play on release 123.1, close mindustry, open release 122.1 and open a sector to see it get erased.

**Link(s) to mod(s) used**: `none`

**Save file**:
[corrupted save.zip](https://github.com/Anuken/Mindustry/files/5860038/corrupted.save.zip)

**Crash report**: `Not a crash`

---
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
why dont you make a backup before playing on an old version?

**Comment by Anuken** [comment]
This is not a bug. Don't open new saves with old versions.

**Comment by benji78** [comment]
This is indeed an issue not a bug.
I just wanted to let you know that if there were:
- a warning saying that the save is from a newer version than the game
- or an "exit without saving" button on the "corrupted save" pop-up
It could potentially save future players from getting their progress erased.

**Comment by Anuken** [comment]
The issue tracker is for bugs only. Feature requests (such as a warning dialog) go in the linked suggestions tracker.

**Comment by benji78** [comment]
Ok thanks, I didn't know that.
Shall I create a feature request then ?
