### ISSUE TITLE
Double-check your JSON adapters

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4422]
**Platform**: *Android, affects all*

**Build**: *123.1*

**Issue**: *JSON can crash the game in multiple ways.*

*My first discovery was that a PowerTurret can lack a shootType and the reader wont catch it until the turret fires, causing a crash.*

*Second was that when loading more than four colours into a ContinuousLaserBulletType, if you did not change the strokes array to compensate the reader again wouldn't catch it, causing an array index out of bounds crash when firing.*

*Third and most recent was that you could put `null` in any field and it would crash on startup.*

**Steps to reproduce**: *Replicate above.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod used in testing but it is not specific to the mod.*

**Save file**: *ancient treasures.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

cmon wuss

**(Crash) logs**: *This platform does not allow me to use the application I use for accessing crash logs. Ping me in discord for the most recent crash log. (yes, despite being android the system does not allow access to the app files via the default file managers)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

After a couple minutes of further testing I found I could use my third party file manager but again, it isn't allowed to send sensitive files to this platform.

**Comment by sk7725** [comment]
> PowerTurret can lack a shootType

you should know better.

> if you did not change the strokes array

change it.

> you could put null in any field and it would crash on startup.

then don't put a null there.

Why don't you take a step further and whine about JS or even Java mods crashing? Nothing you do does make sense in the first place. Double-check your """code""", and make sure there are no bugs. Json should crash when you do something stupid that makes it crash, nothing wrong with that.

**Comment by DeltaNedas** [comment]
help i type `Core.app.exit()` and it crash help

see above

**Comment by BlueWolf3682** [comment]
> > PowerTurret can lack a shootType
> 
> you should know better.
> 
> > if you did not change the strokes array
> 
> change it.
> 
> > you could put null in any field and it would crash on startup.
> 
> then don't put a null there.
> 
> Why don't you take a step further and whine about JS or even Java mods crashing? Nothing you do does make sense in the first place. Double-check your """code""", and make sure there are no bugs. Json should crash when you do something stupid that makes it crash, nothing wrong with that.

i find these crashes by actually looking, my code runs fine. However, it should check for these errors (array maybe not) and definitely shouldnt react to null by crashing.

**Comment by sk7725** [comment]
> it should check for these errors 

Make a java mod, with a decent IDE.

**Comment by Jorgilin** [comment]
I had this problem yesterday.
I was playing the serpulo campaign and it crashed and it doesn't work anymore
Even after i updated it to the most recent version
