### ISSUE TITLE
Cloud saves are not cross-platform

### ISSUE THREAD

**Issue by redwarp** [Anuken/Mindustry#4430]
**Platform**: `Mac OS X x64`

**Build**: `steam build 123.1`

**Issue**: Mindustry cloud saves are not shared between Windows and Mac. I'm playing **mindustry** on both a PC and a mac. I play on my gaming PC at home, and mac laptop when I'm on the go. The cloud saves, though, are specific to each platform, which is not the greatest. Meaning I have two separated campaign. I need to manually downloads and replace files to keep my progression.

**Steps to reproduce**: Start a game on a windows machine. Make sure that when you quit the game, the saves are uploaded to the cloud. Then start the game on a mac: you won't find your progress and campaign, as it's not shared.
You can check the content of the cloud saves by going to https://store.steampowered.com/account/remotestorageapp/?appid=1127400

**Content of cloud saves**:
Going to https://store.steampowered.com/account/remotestorage, I took a screenshots of all the files that are contained in the mindustry cloud saves:
![screencapture-store-steampowered-account-remotestorageapp-2021-01-24-15_30_18](https://user-images.githubusercontent.com/1741661/105633565-97fd6b00-5e59-11eb-8da6-1a8cdc53e96a.png)
![screencapture-store-steampowered-account-remotestorageapp-2021-01-24-15_30_30](https://user-images.githubusercontent.com/1741661/105633567-99c72e80-5e59-11eb-8109-e2945ef69225.png)

As we can see here, both structures, for the mac app and the windows, are present in the cloud saves. All the mac files are under `Mindustry.app/Contents/Resources/saves`, while the windows content is directly under `saves`

**Link(s) to mod(s) used**: `none`

**Possible fix**:
The `root override` section of the [cloud documentation](https://partner.steamgames.com/doc/features/cloud) describes this situation.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
