### ISSUE TITLE
Wave Skipping and Disappearing enemies

### ISSUE THREAD

**Issue by YhuanDebeste** [Anuken/Mindustry#4443]
**Platform**: `Windows 7 x64`

**Build**: `release build 123`

**Issue**: Bug that makes you able to skip waves and kill enemies before spawning. This bug was actually in v5 I didn't know it was not patched yet

**Steps to reproduce**: V5 (with step-by-step): https://youtu.be/G7xbQVs4zFY starts at 6:20
                                     V6 Proof : https://www.youtube.com/watch?v=3EIA-70aw7s
                                     Text step by step : https://www.speedrun.com/mindustry/guide/tpzof

**Link(s) to mod(s) used**: none

**Save file**: File size too big, compressors won't accept it either. Can this be an exception?

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed; all enemies spawn without delays as of the latest commit.
