### ISSUE TITLE
Save file problem

### ISSUE THREAD

**Issue by Nanosuitwitdaboomboxwhatsongwillhepla** [Anuken/Mindustry#4445]
**Platform**: Windows

**Build**: 123.1

**Issue**: I capture sector 158 and leave, export save to keep progress, load previous save to see how the enemy made power, import most recent save and see that sector 158 is now not captured and not an enemy base, I send a  core there and see my progress is there but half destroyed along with the enemy base being half-destroyed, not only that but now there are 30 waves, acting as if it was a survival mission in the first place.
**Steps to reproduce**: 1. capture sector 158 2. export save 3. import previous save 4. import most recent save 

**Link(s) to mod(s) used**: * https://github.com/QmelZ/Hackustry ( I had  it disabled but installed)

**Save file**: 
[Save number 7 with extra cheese.zip](https://github.com/Anuken/Mindustry/files/5876863/Save.number.7.with.extra.cheese.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I captured sector 158, exported a save, loaded an older save file, then loaded the exported save and nothing out of the ordinary happened. 158 remained captured.

**Comment by Nanosuitwitdaboomboxwhatsongwillhepla** [comment]
Could it have been corruption?

**Comment by Nanosuitwitdaboomboxwhatsongwillhepla** [comment]
> I captured sector 158, exported a save, loaded an older save file, then loaded the exported save and nothing out of the ordinary happened. 158 remained captured.

Could it have been corruption?
