### ISSUE TITLE
Modded units in waves not saving

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4448]
**Platform**: *Android 11*

**Build**: *123.1*

**Issue**: *Maps with modded units in the waves aren't saving the modded units when the map is exported.*

**Steps to reproduce**: *I made a map for Exotic Mod ("Overgrown Battleground") and then exported it and uploaded it to the github repository of the mod. Tried playing it after and the unit wasn't in the waves, and was replaced by a dagger.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod*

**Save file**: *Get the map file from the GitHub repository. .msav isn't supported and I tried re-uploading the msav file.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

well?

**Important note**: *This may be due to how Android 11 handles files, or be related to the uncommon issue that some android users had with importing .zip files directly.*

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Pathogen (the modded unit):
![Screenshot_20210126-223314](https://user-images.githubusercontent.com/61173114/105948308-f4ae8080-6027-11eb-900b-10694901b025.png)

Waves: 
![Screenshot_20210126-223428](https://user-images.githubusercontent.com/61173114/105948336-fed07f00-6027-11eb-81ab-be80923abfe5.png)

(before you ask, yes I know how to upload modded maps. I've done it before on other platforms with success.)

**Comment by sk7725** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

#3497 dupe~

**Comment by BlueWolf3682** [comment]
this isnt a dupe of that, thats a save and a constructor and this is just a unit and a map. 

as well as, this isnt in js. its in json.

**Comment by TheRealIvyX** [comment]
one of the maps in my mod (specifically titanium extraction site) uses mostly modded units in its waves, with the only vanilla unit in its waves being an arkyid at wave 30 and it works fine for me

**Comment by Anuken** [comment]
Works fine for me. Adding the custom unit to the map, exporting it and importing as a new map keeps the waves.

**Comment by BlueWolf3682** [comment]
***did you make sure it works even with the wierd glitches that exist with certain android devices?***

**Comment by Anuken** [comment]
No, I don't care about that.
