### ISSUE TITLE
Inconsistent lines

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4454]
**Platform**: Windows

**Build**: 123.1

**Issue**: The custom game dialog has a line that doesn't fill the screen horizontally. This fills the screen in every other dialog and it makes the game absolutely 100% unplayable when it doesn't. Please fix this game breaking bug ASAP.
![](https://yagpdb.is-ne.at/DLjDlQ.png) ![](https://aethex.is-a.fail/DhKgwd.png)

**Steps to reproduce**: Open custom game dialog, notice that the separator doesn't fill the screen.

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No.

**Comment by bvcbvc** [comment]
lol agreed
