### ISSUE TITLE
Fresh Install of game, Crashes while in loading screen

### ISSUE THREAD

**Issue by Waffz** [Anuken/Mindustry#4456]
[crash-report-01_27_2021_20_00_59.txt](https://github.com/Anuken/Mindustry/files/5884604/crash-report-01_27_2021_20_00_59.txt)

**Comment by PolloUsami** [comment]
that looks like a graphic error maybe try updating your pc drivers or installing a more recent version of directx

i think has seen this before in my pc

**Comment by DeltaNedas** [comment]
1. use the template
2. `apt install libgl1-mesa-glx`

**Comment by Anuken** [comment]
Something is wrong with your graphics drivers.
