### ISSUE TITLE
Core.net is accessible by scripts

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#4459]
**Platform**: Debian GNU/Linux

**Build**: 123

**Issue**: Core.net can be used by scripts

**Steps to reproduce**:
1. Core.net.httpGet
2. it doesnt error out

**Link(s) to mod(s) used**: https://github.com/Sh1penfire/pixelcraft/blob/main/scripts/autoupdate.js

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'll keep it off the blacklist for now.

**Comment by DeltaNedas** [comment]
ohno routorio spyware when

**Comment by markozajc** [comment]
create a permission system easy fix
