### ISSUE TITLE
Gameplay Ideas

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Anuken/Mindustry#446]
Hi @Anuken,

thank you for this great game, it is awesome! 

After playing it for quite some hours, I could imagine a few things, that would make it (maybe) even more cool - just for your consideration or to be ignored:

1. **Automatic rebuild of destroyed infrastructure**: After wave 100 the destroyer wave is always killing halfe of the dirium walls and towers. It would be great, not to have to rebuild it manually all the time, as it is already the best possible defense, the game allows ;)
1. **Make the enemies less aggressive and more keen on reaching the core?** An idea - other tower defense  games have their beauty in the possibility of building long and extensive mazes - this is not possible here, as the enemies attack the first corner they encounter and kind of get stuck. It could make the game less hard in the beginning and more fun in the long run, if the enemies would prioritize finding a way to the core over destroying your defense.
1. **Research Center**: Feed resources to improve stats (attack radius, attack speed, HP) of the defense and economic blocks into the research center block(s).
1. **Electricity**: At the moment it is handled like conveyors and liquit transporters, but electricity works actually different. I would like it more, if it just works like a real-life electric network and in case of overload the wires burn through, something explodes or there is simply a power outage.

Alright, there are of course many many more ideas, but I'm sure you got plenty enough yourself.

As said already: an amazingly fun game, cheer mate!
Andreas

**Comment by Milinai** [comment]
Hello @Andreas-Schoenefeldt, build 40 is an outdated version that is not being worked on anymore.

**Comment by Math2128** [comment]
Hi @Andreas-Schoenefeldt 
I assume you are playing the version 3.5 as you are talking about dirium walls.
Anuken is already working on beta 4.0 with a lot of new content.
You can check Mindustry Discord for more info :)

**Comment by Andreas-Schoenefeldt** [comment]
Thx guys, I'm looking forward for the next Android release then :)

**Comment by Math2128** [comment]
You can access the Beta directly on the Play Store. There should be an icon for joining the beta.
It is really amazing and add a whole bunch of new items, building, ect.
Try it out!

I don't have the discord link right now and can't access it, but I am sure you can find it if you download the beta. :)

**Comment by Andreas-Schoenefeldt** [comment]
Ah I see! Let me give it shot :)

**Comment by Math2128** [comment]
@Andreas-Schoenefeldt Don't forget it is April Fools Day though.
There may be some dramatic changes and absolutely crazy stuff. Just warning :)

**Comment by Luxray5474** [comment]
One of the changes being no precompiled game or changelog in the first place lol. I don't think Anuke will exit his 'serious zone' today :P

**Comment by BasedUser** [comment]
router

**Comment by Anuken** [comment]
Closing as most of this is no longer relevant in the latest version.
