### ISSUE TITLE
Mindustry crashes while loading sounds

### ISSUE THREAD

**Issue by TheGamer1002** [Anuken/Mindustry#4460]
**Platform**: *Mac*

**Build**: *123.1*

**Issue**: *When starting Mindustry, it loads everything fine, then crashed while loading sounds.

**Steps to reproduce**: 

1. Start game with mods from Terminal (it says the file is damaged if I open it from Finder, I'm using the .app file)
2. Wait
3. It crashes

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
[abomb4super-cheat.zip](https://github.com/Anuken/Mindustry/files/5887733/abomb4super-cheat.zip)
[AeronGrevaAeroMindustry.zip](https://github.com/Anuken/Mindustry/files/5887734/AeronGrevaAeroMindustry.zip)
[PetruCHIOruslead_ind.zip](https://github.com/Anuken/Mindustry/files/5887777/PetruCHIOruslead_ind.zip)
[pixaxeofpixieBraindustry-Mod.zip](https://github.com/Anuken/Mindustry/files/5887778/pixaxeofpixieBraindustry-Mod.zip)
[QmelZHackustry.zip](https://github.com/Anuken/Mindustry/files/5887779/QmelZHackustry.zip)
[Sh1penfirepixelcraft.zip](https://github.com/Anuken/Mindustry/files/5887780/Sh1penfirepixelcraft.zip)
[sharlotte-mobileExampleMod.zip](https://github.com/Anuken/Mindustry/files/5887781/sharlotte-mobileExampleMod.zip)
[sk7725Commands.zip](https://github.com/Anuken/Mindustry/files/5887782/sk7725Commands.zip)
[sk7725EXP-lib.zip](https://github.com/Anuken/Mindustry/files/5887783/sk7725EXP-lib.zip)
[sk7725Testers.zip](https://github.com/Anuken/Mindustry/files/5887784/sk7725Testers.zip)
[sk7725TimeControl.zip](https://github.com/Anuken/Mindustry/files/5887785/sk7725TimeControl.zip)
[Slava0135reVision.zip](https://github.com/Anuken/Mindustry/files/5887786/Slava0135reVision.zip)
[SMOLKEYSbundles.zip](https://github.com/Anuken/Mindustry/files/5887787/SMOLKEYSbundles.zip)
[tcookiemyeeter-mod.zip](https://github.com/Anuken/Mindustry/files/5887788/tcookiemyeeter-mod.zip)
[theangelurdAdditional-Content.zip](https://github.com/Anuken/Mindustry/files/5887789/theangelurdAdditional-Content.zip)
[TheSkyFatherMinerals.zip](https://github.com/Anuken/Mindustry/files/5887790/TheSkyFatherMinerals.zip)
[TheSlaylordGoldMod.zip](https://github.com/Anuken/Mindustry/files/5887791/TheSlaylordGoldMod.zip)
[Vanilla-Upgraded.zip](https://github.com/Anuken/Mindustry/files/5887792/Vanilla-Upgraded.zip)
[w1-BeyeKrl_mindustry.zip](https://github.com/Anuken/Mindustry/files/5887793/w1-BeyeKrl_mindustry.zip)
[xamionexOpore-Mod.zip](https://github.com/Anuken/Mindustry/files/5887796/xamionexOpore-Mod.zip)
[younggammulti-lib.zip](https://github.com/Anuken/Mindustry/files/5887800/younggammulti-lib.zip)
[ballgamer56VanillaExtended.zip](https://github.com/Anuken/Mindustry/files/5887802/ballgamer56VanillaExtended.zip)
**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-01_28_2021_08_42_11.txt](https://github.com/Anuken/Mindustry/files/5887696/crash-report-01_28_2021_08_42_11.txt)
[last_log.txt](https://github.com/Anuken/Mindustry/files/5887827/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a problem with your giant list of mods, not Mindustry.
