### ISSUE TITLE
lag when placing large solar panels over smaller ones

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4461]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20618`

**Issue**: found this a few days ago but failed to save a file to reproduce it with, major lag spikes when building em.
(lag seems to spike when placement of the next one is about to start)

**Steps to reproduce**: 
- load the save
- command some megas (though this seems optional)
- place several large solar panels in one drag

(picture taken in the left center of the map)
![Screen Shot 2021-01-28 at 15 40 33](https://user-images.githubusercontent.com/3179271/106154033-75cc5b80-617f-11eb-82c2-eb77a2c711a7.png)

**Save file**: 
[solar-hmm.msav.zip](https://github.com/Anuken/Mindustry/files/5888057/solar-hmm.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Unable to reproduce, tested 123.1 and latest BE on android 11.

**Comment by Quezler** [comment]
then i guess only desktop is affected?

ingame vid of it, fps counter stays high since that's not refreshing while its frozen, but you can see the build lag:

https://user-images.githubusercontent.com/3179271/106155268-c42e2a00-6180-11eb-8533-6e3d0c862174.mp4

**Comment by Quezler** [comment]
update from #general-programming:

- bluewolf has the same error when tries my save
- in case the save file is corrupted, there is an .msav there
