### ISSUE TITLE
Mindustry crashes 

### ISSUE THREAD

**Issue by Bluemeh** [Anuken/Mindustry#4468]
Platform: Windows-Steam

Build: Steam Build 123.1

Issue: Mindustry crashes (CTD) when placing a schematic in sandbox mode while streaming the game through Discord. 
Additionally, tested using a slightly smaller schematic (instead of T4 the schematic makes T3 units) that also causes the game to crash.

Steps to reproduce: Reproduced multiple times using this schematic: https://steamcommunity.com/sharedfiles/filedetails/?id=2377811298

1. Open Mindustry
2. Stream Mindustry through the Discord desktop application Build: [Stable 75395 (e4061ca)] - The symbol that appears above the call disconnect button when in a voice chat channel (Res: 720p & Frame rate 30/s)
2. Start a sandbox game - Only confirmed to crash on Fortress and Islands maps
3. Place the blueprint above
4. Observe the crash

**Link(s) to mod(s) used**: None

**Save file**: 
[Crash Save.zip](https://github.com/Anuken/Mindustry/files/5896070/Crash.Save.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*  

No crash report found when attempting to export the logs nor was a designated "Crash" folder found in the [steamapps -> common -> Mindustry] file pathway.

![No Crash Report Found](https://user-images.githubusercontent.com/78232668/106321562-737f0580-6242-11eb-8b67-abb1378fb041.PNG)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is related to Discord and not something I can fix. You also haven't attached any logs.

**Comment by Catchears** [comment]
Try disabling hardware acceleration on discord.

**Comment by buthed010203** [comment]
Hey @Anuken I found that it does actually produce a log ![](https://extremely.questionable.link/i2kv4k.png) Here are a couple of logs from my testing just now:
[hs_err_pid27664.log](https://github.com/Anuken/Mindustry/files/5896234/hs_err_pid27664.log)
[hs_err_pid58360.log](https://github.com/Anuken/Mindustry/files/5896235/hs_err_pid58360.log)

**Comment by Anuken** [comment]
@buthed010203 That's a crash caused by NVIDIA drivers. It's outside of my control.

**Comment by buthed010203** [comment]
Then apparently its nvidia and not discord lol, bet it is actually hardware acceleration.

**Comment by buthed010203** [comment]
its not hardware accel
