### ISSUE TITLE
Не игровой Альфа

### ISSUE THREAD

**Issue by DrPeeper228** [Anuken/Mindustry#4474]
> `**Platform**:` `Android 28`

**Build**: `bleeding-edge build 20625`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.
Если в редакторе карт нажать редактировать в игре не ставя ядро а потом зайти на карту то будет не игровой Альфа, я наврал что он не игровой, в него можно вселятся, его можно подогнать двойным нажатием по себе, он стреляет по врагам.

**Link(s) to mod(s) used**: `none`

**https://drive.google.com/file/d/1QylGBsUbnkkVDfBfBnV1GFZOcRAtQeAN/view?usp=drivesdk**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---Это баг но не краш

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- 

- [X]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
I faced the same issue yesterday when making maps. In my case though I did place some cores and what I did was started the "In-game edit" and quickly exited this mode, then saved the map and started pvp custom game. I haven't tried reproducing it, so can't give 100% on steps.
