### ISSUE TITLE
oct has range in the core database

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4476]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20625`

**Issue**: oct range shows up in the core database, and a none other than the maximum integer:

![Screen Shot 2021-01-30 at 11 16 27](https://user-images.githubusercontent.com/3179271/106362656-53277780-6324-11eb-8b76-ac10597fc199.png)

**Steps to reproduce**: 
- open up the core database
- gaze upon the core database

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
It does have a large range that is only used for logic unit radar (it's "vision range"), but it shouldn't be MAX_INT.

**Comment by catatagun** [comment]
Qeuzler where is the X

**Comment by Volas171** [comment]
- [ ] x
