### ISSUE TITLE
BUG: Ghost Enemies

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#448]
(sorry I did not submit it the conventioanl way, thorugh Discord. I have left the server for personal reasons and while I find ways to 'bridge the gap', primarily through th35leeper, I am submitting bugs in issues)

![](https://i.imgur.com/qDWW0Hb.png)

DESCRIPTION: Ghost enemies; enemies which are said to exist but do not. The enemy indicator will point to the said location of the enemy, but the enemy itself does not appear.

REPRODUCTION: Exit the game (esc->quit) while enemies exist and are being shot at. Possibly also caused by enemies being damaged/killed while game saves.

**Comment by Anuken** [comment]
Doesn't happen to me. I can spawn ~100 enemies under fire from turrets, exit, re-play or load the save and no invisible enemies. Multiple attempts don't change things. Can you consistently reproduce it, and if so, what are the *exact* actions you take?

**Comment by Luxray5474** [comment]
Sorry for my late reply :/

I have stated them. I will try to attach a keylogger or screencap and record it, if I can reproduce it. Expect it to come this weekend because I am very busy this week.

**Comment by Luxray5474** [comment]
- **Which map are you playing?** Nuclear Production Zone.
-  **Is it singleplayer?** Yes.
- **Do you play the same map after quitting?** Yes.
- **Do you load a save or start a new game?** This is the Campaign mode
- **Which part of the map do the enemies appear on?** SSW of the drop point
- **Are they present on the minimap?** This is the desktop version; no minimaps.
- **How did the enemies die?** I used all artillery turrets so either by a Hail or Ripple.
- **Which enemies were killed?** Those three in that location, plus the rest.
- **Do the turrets point towards the enemies or try to shoot at them?** No
- **Can I hit them with my own mech's bullets?** No.
- **Do the ghost enemies move around?** They stay stationary.
- **Can you still access the save/game?** No. I lost the sector two days after as a result of unexpected enemy routes. 
- **Was the UNIX Epoch Time an even number?** No.

## SETTINGS ACTIVE: 

**all settings still the same as of today*

### Game

- Screen Shake: 0.5x
- [x] Display Effects
- [ ] Always Diagonal Placement
- Autosave Inteval: 60 Seconds
- [x] Send Anonymous Crash Reports

**the game did not crash*

### Graphics 

- Max FPS: None
- Antialias: 0x
- [x] VSync
- [ ] Fullscreen
- [x] Show FPS
- [x] Enemy/Ally Indicators
- [x] Animated Water
- [x] Show Power Lasers

### Controls

All default except for: 
- Pick Block: Delete
- Zoom Hold: Mouse Middle

### Language

English

## GAME INFORMATION

Ran **Mindustry v4 beta-official-build 68** at the time.

**Comment by Anuken** [comment]
Probably fixed by c3c609e7b9b20be5ad8c403658cbaa21a508cec9, let me know if it happens again.
