### ISSUE TITLE
link with processors not overwrite

### ISSUE THREAD

**Issue by PolloUsami** [Anuken/Mindustry#4482]
**Platform**: * Windows *

**Build**: * Steam build 123.1 *

**Issue**: *Explain your issue in detail.*

when you replace a gun that was connected via logic procesors and replace it it conserv it link name

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

specters in a 8x8 formation
conect every specter to a hyperprocesor
replace the specters with meltdowns withouth deleting them first

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[Bug map.zip](https://github.com/Anuken/Mindustry/files/5900306/Bug.map.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not something I'm interested in fixing. The link validation code is already a mess.
