### ISSUE TITLE
coredatbase flikering

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry#4486]
**Platform**: *Android/iOS/Mac/Windows/Linux* any

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*123.1

**Issue**: *Explain your issue in detail.* when you open core database near the frontline (top of map) it flickers 
![image](https://user-images.githubusercontent.com/73048252/106399632-bbcb2e80-63ce-11eb-9d9d-c33e5641bc20.png)
![image](https://user-images.githubusercontent.com/73048252/106399634-bcfc5b80-63ce-11eb-9c27-82ebb7ae9dac.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* opening coredata base at the frontline defense (multiplayer) also may need corvus to fire, not sure

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a [crash.*]
[bug.msav.zip](https://github.com/Anuken/Mindustry/files/5900793/bug.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RouterChainsSuckk** [comment]
oops i accidentally put the mapfile in the wrong slot, sorry anuke

**Comment by Anuken** [comment]
Invalid zip, can't reproduce.
