### ISSUE TITLE
Material_ steam achievements unobtainable for older players without restarting progress

### ISSUE THREAD

**Issue by Kiinae** [Anuken/Mindustry#4490]
**Platform**:  Windows

**Build**: Steam Build 123.1

**Issue**: I can't get any of the "Material _" achievements because I had the game roughly a year ago and got all of the tech I have in this photo (except roughly 5-6 things that I've unlocked recently) when (I assume) the achievements didn't exist. Now I could probably just restart my save but I had already started to conquer areas before I realized this was an issue and would rather not.

![image](https://user-images.githubusercontent.com/78333775/106413123-e9d06300-640e-11eb-89e9-9f39a259a733.png)

**Steps to reproduce**: This isn't super reproducible, yes you could have people such as myself who had the game before the achievement was a thing so they would have the same issue but other than that I doubt it can be reproduced.

**Link(s) to mod(s) used**: N/A

**Save file**:  I'm including all my save files because I'm not sure how the campaign saves (it looks like different saves per map however idk where tech is saved then)

[All Save Files.zip](https://github.com/Anuken/Mindustry/files/5901750/All.Save.Files.zip)

**(Crash) logs**: N/A

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [-] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
(after reading through the start of January I kindof gave up and started just searching the key words "steam" and "achievement" through the start of December (~20 pages in and it started to kill me so I'm sorry if this is a duplicate) 

Side note, this may be fully intended so that you don't get these achievements by simply joining a multiplayer world that already has it unlocked, but I figured I'd still bring it up anyways.

**Comment by PolloUsami** [comment]
why you only try saving your progress
reseting the tech tree
go to a sector where you have titanium/torium
get the adchievment
reload your progress

**Comment by Kiinae** [comment]
ngl I didn't think of that, though I also am not certain how to reset my tech tree.

Side note I went to the discord help section first but didn't get any help so I thought here was my next best place since I didn't know how to fix it.

**Comment by PolloUsami** [comment]
in the configuration game data there is the option
