### ISSUE TITLE
Error connected with mono

### ISSUE THREAD

**Issue by Wencelsav** [Anuken/Mindustry#4492]
**Platform**: `Windows 10 x64`

**Build**: `bleeding-edge build 20631`

**Issue**: *mono too close to each other and because they are not mining  and not unloading in core. 
![изображение](https://user-images.githubusercontent.com/31541176/106427681-d4901e80-6478-11eb-8c02-5cab386099d9.png)
*

**Steps to reproduce**: *I just reset all data and build mono
[saves.zip](https://github.com/Anuken/Mindustry/files/5902506/saves.zip)

*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
the culprit from 3d201f7042b462ec0d73a906295bf82df1213fbd:
(since units use their range as mining range, instead of the mining range from vars)

https://github.com/Anuken/Mindustry/blob/3d201f7042b462ec0d73a906295bf82df1213fbd/core/src/mindustry/type/UnitType.java#L302-L304
