### ISSUE TITLE
About to lose two days worth of progress

### ISSUE THREAD

**Issue by Nanosuitwitdaboomboxwhatsongwillhepla** [Anuken/Mindustry#4495]
**Platform**: Windows

**Build**: 123.1

**Issue**: Exported the game, tried to import to see if everything is ok since my recent luck with this game and says it can't, made another export, tried to import it, gives me an error.

**Steps to reproduce**:
 1. export save1
 2. import save1
 3. problem happened, 
 4. 4. export save 2
 5. try to import save 2 
 6. another problem happened

**Link(s) to mod(s) used**: Hackustry by QmelZ https://github.com/QmelZ/Hackustry (was disabled)

**Save file**: 
[progress.zip](https://github.com/Anuken/Mindustry/files/5907355/progress.zip) **(Save number 1)**

[progression.zip](https://github.com/Anuken/Mindustry/files/5907354/progression.zip)  **(Save number 2)**

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Those are not valid zip files. Exporting saves works fine on my machine.

**Comment by Nanosuitwitdaboomboxwhatsongwillhepla** [comment]
> Those are not valid zip files. Exporting saves works fine on my machine.

Did you try importing my zip files

**Comment by Anuken** [comment]
> Did you try importing my zip files

Yes, and they're not valid.

**Comment by Nanosuitwitdaboomboxwhatsongwillhepla** [comment]
> > Did you try importing my zip files
> 
> Yes, and they're not valid 
I just got fucked by luck didn't I

**Comment by DeltaNedas** [comment]
if theyre not zip files then youll have to yknow `cd Mindustry; zip ** yes.zip`

**Comment by Nanosuitwitdaboomboxwhatsongwillhepla** [comment]
> if theyre not zip files then youll have to yknow `cd Mindustry; zip ** yes.zip`

They are .zip files 
Could you follow up with the intsructions on how to fix the problem?

**Comment by notrealn** [comment]
![image](https://user-images.githubusercontent.com/56411504/106544965-7134d980-64d6-11eb-90ce-2818ac185864.png)
only file is settings.bin and its empty
vim says its 0 bytes somehow

**Comment by ConfuSomu** [comment]
Could it be a problem related to save data export? File system inconsistencies? Disk drive slowly dying?
