### ISSUE TITLE
CRASH report.

### ISSUE THREAD

**Issue by frenchiveruti** [Anuken/Mindustry#450]
I built a conveyor belt into a wall, then scrolled to rotate it while it had copper on top, and as soon as I placed it, it crashed to desktop.

LOG: 
[crash-report-04_04_2019_21_04_27.txt](https://github.com/Anuken/Mindustry/files/3045868/crash-report-04_04_2019_21_04_27.txt)

**Comment by Anuken** [comment]
fixed in 2dee221861916d197bdf4cde0b95565405758cca
