### ISSUE TITLE
Bugged map editor

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#4500]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
123.1

**Issue**: *Explain your issue in detail.*
![](https://cdn.discordapp.com/attachments/391020510269669378/806197920146784327/unknown.png)
Team marker broken:
![](https://cdn.discordapp.com/attachments/391020510269669378/806198187504697424/unknown.png)
Size of the core looks 1x1 because i could place anything in it except in the middle (example with boulders):
![](https://cdn.discordapp.com/attachments/391020510269669378/806198387959398410/unknown.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. set editor size to 1x1 (possible with mod DeltaNedas/cliff)
2. place a core
3. set map size to 5x5

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
DeltaNedas/cliff v1.1.0

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
not in game (editor)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

not crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
Something similar happened to me when I opened map created by someone else from pre-121 build in 123.1 editor and issue only affected core builds. Workaround is to simply replace cores.

**Comment by antonilol** [comment]
we don't want workarounds. bugs are there to be fixed

**Comment by Cherriodude** [comment]
You're using a mod that enables an unsupported part of the editor. This is like reporting q bug for an unreleased map.

**Comment by Anuken** [comment]
> DeltaNedas/cliff v1.1.0

That mod changes how the editor works. 5x5 maps are not permitted in vanilla.
