### ISSUE TITLE
Inverted sorters doesn't work as expected

### ISSUE THREAD

**Issue by itday** [Anuken/Mindustry#4505]
**Platform**: *Windows 10*

**Build**: *123.1*

**Issue**: *Three inverted sorters in a row doesn't work as expected. The output flow is interrupted.*
![InvertedSorterBug](https://user-images.githubusercontent.com/22928478/106685185-2abfa780-65c8-11eb-8c6b-ed541d0dad64.jpg)

**Steps to reproduce**: *See image above.*

**Link(s) to mod(s) used**: *Hackustry v3.3 from the mod browser*

**Save file**: *[InvertedSorters.zip](https://github.com/Anuken/Mindustry/files/5915487/invertedSortersBug.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
1. what is the description that says they cant be used consecutively
2. thats terrible use of roombas

**Comment by BlueWolf3682** [comment]
Intentional.

**Comment by itday** [comment]
Thank you for your quick response.
1) I checked the description and only found: "Similar to the standard sorter, but instead outputs selected items to the sides". I can't see a note there that they can't be changed together.
2) Oh my bad. How can I use them better? I'm still very new to the game.

**Comment by catsz** [comment]
put everything into a container and use unloaders

**Comment by GreyMario** [comment]
![](https://puu.sh/Hd7J7.png)

Read this Core Database entry _very carefully._

**Comment by itday** [comment]
I'm blind thanks.

Also thanks @catsz for the container idea.
