### ISSUE TITLE
Power pole connections aren't saved in blueprints 

### ISSUE THREAD

**Issue by itday** [Anuken/Mindustry#4506]
**Platform**: Windows 10

**Build**: 123.1

**Issue**: *Power pole connections aren't saved in blueprints. This leads to unintentionally power flows.*
![PowerPoles](https://user-images.githubusercontent.com/22928478/106685994-db7a7680-65c9-11eb-8c05-6caf9316ddbe.jpg)
*Left side: original; right side: copy*

**Steps to reproduce**: *See image above.*

**Link(s) to mod(s) used**: *Hackustry v3.3 from the mod browser*

**Save file**: *[PowerPoles.zip](https://github.com/Anuken/Mindustry/files/5915531/PowerPoles.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
They are saved, but power nodes will still make automatic connections, so you can't save a schematic with a deliberately disconnected power connection and expect it to stay disconnected when you build that schematic.

There is currently an issue with power nodes filling up on automatic connections during construction, leaving no room for saved connections, but #4414 has already fixed this issue. Wait till the next update to see this fix, or play on bleeding edge builds.

**Comment by itday** [comment]
Thank you for your quick response. Thats' great.

**Comment by buthed010203** [comment]
Funnily enough, it turns out #4414 was the cause of the problem mentioned here lmao
