### ISSUE TITLE
Power transfer with diodes doesn't work as expected

### ISSUE THREAD

**Issue by itday** [Anuken/Mindustry#4507]
**Platform**: *Windows 10*

**Build**: *123.1*

**Issue**: *The power is not transmitted across multiple diodes as expected. The battery power level drains from left to right. In the end, there isn't enough power for the force projectors. But the last battery still has 144 power -> should be empty if there isn't enough power?*
![20210203025820_1](https://user-images.githubusercontent.com/22928478/106688632-c3f1bc80-65ce-11eb-8006-0916cfb001f0.jpg)
**Steps to reproduce**: *See image above.*

**Link(s) to mod(s) used**: *Hackustry v3.3 from the mod browser.*

**Save file**: *[PowerTransfer.zip](https://github.com/Anuken/Mindustry/files/5915653/PowerTransfer.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported (I checked also the initial PR: https://github.com/Anuken/Mindustry/pull/964).**

**Comment by Quezler** [comment]
the diode transmits up to the size of the battery per tick, 4000 isn't enough for all your forcefields

**Comment by itday** [comment]
Thank you for your reply. A small battery should then be able to transmit 4000 * 60 ticks/s = 240k power. There are 77 force field projectors in the preview image. You only need 18,480 power per second (77 * 240 power/s).

I created a new test setup to simplify the calculation. In the figure below, 11 diodes and 100 force projectors projectors are included. In theory, the required power of 240k should be transferred. However, the power poles displays that -16k/s power is missing and 158 power is stored (the blue arrow indicates the position of the cursor).
![NotEmpty](https://user-images.githubusercontent.com/22928478/106753326-d3ebb980-662b-11eb-80dc-f12c1fde892d.jpg)

60 power projectors are still too many (14,400 power). If you remove another projector, the energy balance is positive.
![60](https://user-images.githubusercontent.com/22928478/106752801-2678a600-662b-11eb-9f11-80c9b7d5bfee.jpg)

Testing showed that 240k/s power can be transfered over 3 diodes.

*Side node: During testing, I noticed that the automatic wiring only works for the nearest power pole.*

**Comment by Anuken** [comment]
Diodes *equalize* power balance. They do not have high throughput.

> the diode transmits up to the size of the battery per tick

This... isn't true. If you have two batteries, with one at 4k and the other at 0, it will transfer 2k power at most. The next frame, even less power will be sent, making the true throughput of chained diodes variable and much less than 120k/s.
