### ISSUE TITLE
Minimap Unit Icon Drawing

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4508]
**Platform**: *Android*

**Build**: *123.1*

**Issue**: This is an omura and corvus.
![Screenshot_20210202-193704](https://user-images.githubusercontent.com/61173114/106690106-650c5300-658e-11eb-9735-eefe72adce3b.png)
normal, right?

what are these abominations?
![Screenshot_20210202-193712](https://user-images.githubusercontent.com/61173114/106690120-7190ab80-658e-11eb-8fd5-76aff7818b3f.png)

**Steps to reproduce**: *Look at the minimap.*

**Link(s) to mod(s) used**: *irrelevant*

**Save file**: *brazil.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

just do it already

**(Crash) logs**: *brazil*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
