### ISSUE TITLE
Landing in the location of Mushroom Pass

### ISSUE THREAD

**Issue by STAPLER0** [Anuken/Mindustry#4509]
**Platform**: `Android 28`

**Build**: `release build 123.1`

**Issue**: *When you try to land in the location of Mushroom Pass, the game immediately closes*

**Steps to reproduce**: *After the first landing and defeat in the location of Mushroom Pass is not possible to land again. When you try to land, the game immediately closes*

**Link(s) to mod(s) used**: `none`

**Save file**: *https://drive.google.com/file/d/12_WEjl6oXp6JUzK5ViWYkWoAnqgGAwKP/view?usp=drivesdk*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
try to find a crash log

**Comment by Anuken** [comment]
No log.

**Comment by DeltaNedas** [comment]
now anuke has to add an "i will real your soul" clause to logs, nice
