### ISSUE TITLE
Tsunami Liquid Storage

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry#4524]
**Platform**: *Windoof*

**Build**: *SteamBuild 123.1*

**Issue**: 
Switching different liquids in a (e.g.) Tsunami is not nulling the liquid that was used before.
This leaves a tiny rest inside the turret wich can still be senored by logic.
This however can cause errors in my simple logic of alternating liquids in Tsunamis.
Probably same with Waves.

![image](https://user-images.githubusercontent.com/66265700/106789218-44a5cc80-6652-11eb-9f77-8271ec625822.png)

**Steps to reproduce**: *^*

**Link(s) to mod(s) used**: ---

**Save file**: 
[Tsunami Test.zip](https://github.com/Anuken/Mindustry/files/5920541/Tsunami.Test.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug. The liquid doesn't disappear.
