### ISSUE TITLE
Rounding when building with logic

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry#4584]
**Platform**: *Windows*

**Build**: *123.1*

**Issue**: *When you sensor 2x2 blocks you get halved coordinates, so when you try to build at the same coordinates, the block gets built with an offset.*
![Mega builds](https://user-images.githubusercontent.com/66305483/106847689-d6e8b780-66c8-11eb-88c4-bcbf51329d9e.png)
*In the screenshot the Mega is ordered to build a container at x: 28.5, y: 40.5 but it tries to place the block at x: 29, y: 41 instead.*

**Steps to reproduce**: *I've used sensor to find the position of a container and wanted the mega to build one at the found coordinates, but it tries to build it in the wrong place.*

**Link(s) to mod(s) used**:
*DeltaNedas/override-lib
DeltaNedas/ldb*

**Save file**: *[Logic test map.zip](https://github.com/Anuken/Mindustry/files/5923372/Logic.test.map.zip)*

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
That's a rounding issue you can resolve in your logic yourself.

**Comment by Nester23** [comment]
I know that I can fix it in my logic, but this rounding is unnecessary in my opinion. ucontrol build should choose where to place the block in the same manner that manual placement does.

**Comment by Nester23** [comment]
![Manual container](https://user-images.githubusercontent.com/66305483/106904131-37e9ad00-6714-11eb-8d3c-5bfcb98f7b42.gif)
![ubuild container](https://user-images.githubusercontent.com/66305483/106905387-ae3adf00-6715-11eb-8164-82a6031be76b.gif)
*Here's some GIFs of this.*
