### ISSUE TITLE
Mindustry stuck at loading than it not responding

### ISSUE THREAD

**Issue by CSknight0389** [Anuken/Mindustry#4585]
OS: Windows 7 Build 7601 (6.1.7601.24545) 32bit     Intel(R)Core(TM)i7 CPU M620  2.67Ghz    Support open gl 2.0
                                                                       3.43 RAM                      

CPU:total 4 (initial active 4) (2 cores per cpu, 2 threads per core) family 6 model 37 stepping 2, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, aes, clmul, ht, tsc, tscinvbit

Memory: 4k page, physical 3594068k(1224676k free), swap 7186468k(4772064k free)

vm_info: OpenJDK Server VM (25.201-b09) for windows-x86 JRE (1.8.0_201-1-ojdkbuild-b09), built on Jan 24 2019 11:41:11 by "Administrator" with MS VC++ 10.0 (VS2010)

 ----------------------------------------------------------------
When i Open the Mindustry, It will loading until almost finish than it not responding , when i quit the game it will appear Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 i can open it twice times only, it just not loading than crash
-------------------------------------------------------------------
 JRE version: OpenJDK Runtime Environment (8.0_201-b09) (build 1.8.0_201-1-ojdkbuild-b09)
Java VM: OpenJDK Server VM (25.201-b09 mixed mode windows-x86 )
 Problematic frame:
 C  [MSCTF.dll+0x2c1fb]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x01ff2400):  JavaThread "main" [_thread_in_native, id=7276, stack(0x00350000,0x00820000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x65c52634

Registers:
EAX=0x0093fd80, EBX=0x45ee6170, ECX=0x65c5262c, EDX=0x00020000
ESP=0x0081f1f8, EBP=0x0081f230, ESI=0x45ee6170, EDI=0x00000000
EIP=0x760bc1fb, EFLAGS=0x00210202

Top of Stack: (sp=0x0081f1f8)
0x0081f1f8:   0093fd80 00000000 45ff5978 760b7006
0x0081f208:   00000000 80000000 45ff5978 00000001
0x0081f218:   00000000 00000000 00000000 00000000
0x0081f228:   45e26580 00000000 0081f248 760a4ee4
0x0081f238:   01ff2400 408ece98 01a5efc8 00000000
0x0081f248:   0081f2e4 518b5ce3 00000000 07000000
0x0081f258:   0081f25c 00000000 0093f360 518ba838
0x0081f268:   0093f360 408ece98 518a3c40 0093f360 

Instructions: (pc=0x760bc1fb)
0x760bc1db:   ff 8b 08 50 ff 51 08 89 7e 0c e9 26 a8 ff ff 8b
0x760bc1eb:   08 50 ff 51 08 89 7e 10 e9 23 a8 ff ff 8b 08 50
0x760bc1fb:   ff 51 08 89 7e 04 e9 20 a8 ff ff 50 e8 55 4b 03
0x760bc20b:   00 89 7e 2c e9 2b a8 ff ff ff 75 10 8b 49 04 ff 

Register to memory mapping:

EAX=0x0093fd80 is an unknown value
EBX=0x45ee6170 is an unknown value
ECX=0x65c5262c is an unknown value
EDX=0x00020000 is an unknown value
ESP=0x0081f1f8 is pointing into the stack for thread: 0x01ff2400
EBP=0x0081f230 is pointing into the stack for thread: 0x01ff2400
ESI=0x45ee6170 is an unknown value
EDI=0x00000000 is an unknown value

Stack: [0x00350000,0x00820000],  sp=0x0081f1f8,  free space=4924k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [MSCTF.dll+0x2c1fb]
C  [MSCTF.dll+0x14ee4]
C  [sdl-arc.dll+0x75ce3]
j  arc.backend.sdl.SdlApplication.cleanup()V+20
j  arc.backend.sdl.SdlApplication.<init>(Larc/ApplicationListener;Larc/backend/sdl/SdlConfig;)V+172
j  mindustry.desktop.DesktopLauncher.main([Ljava/lang/String;)V+22
v  ~StubRoutines::call_stub
V  [jvm.dll+0x161865]
V  [jvm.dll+0x2316ee]
V  [jvm.dll+0x1618fe]
V  [jvm.dll+0xdb0a7]
V  [jvm.dll+0xe3793]
C  [Mindustry.exe+0x725b]
C  [Mindustry.exe+0x69db]
C  [Mindustry.exe+0x7380]
C  [Mindustry.exe+0xcf46]
C  [Mindustry.exe+0x203f]
C  [Mindustry.exe+0xcbfa]
C  [Mindustry.exe+0x10af5]
C  [kernel32.dll+0x4ef3c]
C  [ntdll.dll+0x6360c]
C  [ntdll.dll+0x635df]
C  0x00000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  arc.backend.sdl.jni.SDL.SDL_Quit()V+0
j  arc.backend.sdl.SdlApplication.cleanup()V+20
j  arc.backend.sdl.SdlApplication.<init>(Larc/ApplicationListener;Larc/backend/sdl/SdlConfig;)V+172
j  mindustry.desktop.DesktopLauncher.main([Ljava/lang/String;)V+22
v  ~StubRoutines::call_stub
-----------------------------------------------------------------------------------------------

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have upated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
that is clearly a windows dll and not mindustry which is crashing the jvm.
how can anuke fix that?

**Comment by Slava0135** [comment]
Install Debian
