### ISSUE TITLE
Community Server List Errors

### ISSUE THREAD

**Issue by ROBLOX2ENTITY** [Anuken/Mindustry#4587]
**Platform**: `Android 4.4.4`

**Build**: `release build 123.1`

**Issue**: `I tried everything that was in my mind. Resseting app, clicking the eye icon and arrow icon in different patterns. Nothing worked, i can only play mindustry official servers with an IP Address because i used the remote server mechanic, i only get to play on two servers which I noticed, it gets griefed oftenly, by a known hacker starting from january he said he gets money from doing so and stuff, the other ones are just ones that find griefing somehow entertaining. Anyways i cant play on sandbox because my android cant run it, it says connection error all the time except other servers that dont have much content (less lag) so now i have only attack and survival servers, which means if i get stuck on two i just have to mindlessly scroll through youtube finding some content, and afterwards i just get bored and go back to mindustry, but the problem (griefers, laggy map,) stays, it takes a long time for rounds to finish i sometimes do get bored because i have only two servers as well. I see no servers on that list..
![Screenshot_2021-02-04-21-48-38](https://user-images.githubusercontent.com/78553935/106926365-d71d9d00-6732-11eb-801d-e240cccaef3a.png)
. `

**Steps to reproduce**: `im not sure, but i just remember deleting my data for a fresh start but nothing else, i dont think thats the problem.`

**Link(s) to mod(s) used**: `none`

**Save file**:`none`

**Crash report**: `the crashing thing happens in a specific map called attack on japan v6.0 NOT SURE IF ITS (v6 OR v6.0) but all i know is that its my androids fault :/ its pretty old.`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The server list is not supported on certain (older) Android devices due to an Android bug.
