### ISSUE TITLE
Can't join Discord

### ISSUE THREAD

**Issue by ProteinPig** [Anuken/Mindustry#459]
When I click the link, Discord frozen.

**Comment by Anuken** [comment]
The Discord link in build 40 doesn't work anymore. Use the one in the beta, or on this GitHub page.

*if you're already in the beta and the link doesn't open, it must be an issue on Discord's end, as it works fine for me.

**Comment by ProteinPig** [comment]
Yes, you are right. I join the server with browser instead of app.
