### ISSUE TITLE
Logic bug: some cpu's restart after sector reload

### ISSUE THREAD

**Issue by 1am-now** [Anuken/Mindustry#4591]
**Platform**: `Linux x64`

**Build**: `release build 123.1`

**Issue**:
Some combinations of Logic cpu + program restart after sector reload, some don't.
Generally, any cpu's placed in some map row continue executing their programs, and any cpu's placed in next map row restarting, if you go to other sector and return. If this behavior were stable, this could be treated as semi-feature to detect map reload. This could prevent hangs in loops waiting unit approach without additional checks for @unit = null for example. But it is unstable, some changes in program may switch on/off this cpu behavior, for example adding 3 blocks with simple debug print causes previously running cpu to begin restarting:

```
print 000
printflush message1
```

I can provide additional testing, if required.

**Steps to reproduce**: 
In campaign map build two micro processors, one under another, link them to corresponding messages. Insert this code:

```
set i 0
op add i i 1
print i
printflush message1
jump 1 always 0 0
```

Wait 10 seconds for loop counter to accumulate. Go to other sector. Return. One message will reset to 0, other will continue from last number.

**Link(s) to mod(s) used**: `none`

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5928733/saves.zip)
(2 rows of 6 cpu's near player, right side of screen)

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Save file: saves.zip

That is not a valid save file. That is 24 different saves.

> Generally, any cpu's placed in some map row continue executing their programs, and any cpu's placed in next map row restarting, if you go to other sector and return.

This doesn't happen to me.

**Comment by 1am-now** [comment]
A little too much saves (and backups), sorry.
This issue is a bit trickier to reproduce, than I expected. Exact program and position of messages also counts.
Use program from "Steps to reproduce".
Let processors be #, messages be =, processor is connected to nearest message.
This configuration works without restarts:
```
=#
=#
```
And there one of the processors restarts after sector reload:
```
=
#
#
=
```
