### ISSUE TITLE
T4 reconstructor rejecting T3 unit

### ISSUE THREAD

**Issue by aushafer06** [Anuken/Mindustry#4592]
**Platform**: `Mac OS X x64`

**Build**: `steam build 123.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
_sad template noises_

**Comment by GreyMario** [comment]
Not that there's any need for it, because, _just like with the T2 and T3 reconstructors,_ you need to have **researched the T4 unit in question** before you can make it.

**Comment by Quezler** [comment]
ah, that explains the other issue from a few weeks ago where anuke had a one word response, maybe some sort of "tech tree icon" should show when trying to insert a unit into a reconstructor that can't upgrade it yet, similar to the "unit cap full" warning?

**Comment by stuffyAI** [comment]
>  maybe some sort of "tech tree icon" should show when trying to insert a unit into a reconstructor that can't upgrade it yet

God bless if there is a 'user-proof' way to intuitively convey them to research an upgraded unit before being able to utilize them.

**Comment by BlueWolf3682** [comment]
> ah, that explains the other issue from a few weeks ago where anuke had a one word response, maybe some sort of "tech tree icon" should show when trying to insert a unit into a reconstructor that can't upgrade it yet, similar to the "unit cap full" warning?

how about the research tree button icon?

**Comment by joshuaptfan** [comment]
> how about the research tree button icon on the reconstructor?

I think a full on hint is in order, one that is never saved as "seen" even if skipped but always appears in these situations. Sure, it requires localization, but it would be much clearer than some ambiguous icon.
