### ISSUE TITLE
core database flickering (repost)

### ISSUE THREAD

**Issue by RouterChainsSuckk** [Anuken/Mindustry#4596]
**Platform**: *Android/iOS/Mac/Windows/Linux* all pc (havent tested mobile)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*123.1

**Issue**: *Explain your issue in detail.* coredatabase flickers (can get really bad)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* open core database on the map, I think It has something do to with a lot of units on the map as i haven't reproduced it outside of unit spam 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* you said my zip was invalid so here's a link to the download that should 100% work https://discord.com/channels/391020510269669376/393111111853146112/807385533448847421

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
> all pc

so you tested on a mac, linux and windows machines?

at least give a video clip of the issue

**Comment by RouterChainsSuckk** [comment]
> > all pc
> 
> so you tested on a mac, linux and windows machines?
> 
> at least give a video clip of the issue

obs doesn't work also, this happened in a multiplayer server so i know for a fact this is a issue with all 3 of those

**Comment by Anuken** [comment]
This was already fixed.
