### ISSUE TITLE
MacOS In Game FPS Stuttering

### ISSUE THREAD

**Issue by MrBacon470** [Anuken/Mindustry#4597]
**Platform**: *MacOS Catalina*

**Build**: *Steam Build 123.1*

**Issue**: *On maps and Loading Screen there is significant stuttering and FPS drop when playing or just in title screen, FPS counter will on stutter drop from 60 to around 40 or less*

**Steps to reproduce**: *To reproduce this bug it is noticeable on the title screen not the opening animation but the main menu after leaving a game or starting the game, this also was occurring on the first level.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

(I am Unable to successfully Export Data to my computer or open them)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
are you sure your GPU doesnt just suck?

**Comment by MEEPofFaith** [comment]
are you sure your computer isn't a toaster?

**Comment by MrBacon470** [comment]
No it is not my computer because I have run mindustry from the itch.io downloadable before with no performance issues at all

**Comment by MrBacon470** [comment]
Closing Bug Report:
Reason: Issue seemed to resolve itself after reloading game after a while of down time
