### ISSUE TITLE
Windows10 Pro 64

### ISSUE THREAD

**Issue by a54008808** [Anuken/Mindustry#4598]
![Game Error Bug](https://user-images.githubusercontent.com/78575479/107109839-5ec3f280-687e-11eb-985a-284b18c26176.PNG)

**Comment by BlueWolf3682** [comment]
what?

**Comment by a54008808** [comment]
bug

**Comment by a54008808** [comment]
me in the china

**Comment by a54008808** [comment]
my home in the _china_

**Comment by joshuaptfan** [comment]
Have you tried... reading that error message and taking the suggested actions?

**Comment by MEEPofFaith** [comment]
Have you attempted reading and following instructions?

**Comment by a54008808** [comment]
> 你试过...阅读该错误消息并采取建议的操作？

The error report has no recommended actions and no error messages

**Comment by a54008808** [comment]
> Have you tried... reading that error message and taking the suggested actions?

The error report has no recommended actions and no error messages

**Comment by GreyMario** [comment]
Have you tried...

Thinking about what the message says?

**Comment by Meltdown-Altair** [comment]
hmmm
yes the error is made out of error

**Comment by Meltdown-Altair** [comment]
very funny of you
im disappointed at how i said it was funny

**Comment by a54008808** [comment]
The server is the same as the game client version 6-123

**Comment by a54008808** [comment]
After playing well, it suddenly prompted a server data packet error. I thought there was a problem with the game, so I reinstalled the game, but it still didn't solve it.

**Comment by Meltdown-Altair** [comment]
aeugh

**Comment by Meltdown-Altair** [comment]
look at server yet?

**Comment by Meltdown-Altair** [comment]
im no IT support , but i know what's telling you to do

**Comment by a54008808** [comment]
> look at server yet?
The server is normal, but each server will have this problem

**Comment by Meltdown-Altair** [comment]
hmm
your phone or PC might be the cause

**Comment by Meltdown-Altair** [comment]
Ask Blue

**Comment by BlueWolf3682** [comment]
why the dingus do you recommend me to ask?
