### ISSUE TITLE
Rewards. (for completing set number of waves ect. - long term)

### ISSUE THREAD

**Issue by Greenfoot5** [Anuken/Mindustry#46]
- Bosses
After you reach a certain wave you have to kill a boss. This boss could just be a stronger original enemy or a new one with abilities. Add a nice sense of achievement once you defeat it.
- Leaderboard (Credit: $impleFails)
An online leaderboard showing off top waves. Everyone is a little bit competitive right?
- Daily challenge (Credit: $impleFails)
A challenge that updates daily. (Custom maps, custom waves ect.)
- Secret maps (Credit: Trollex)
Unlock some extra maps when you reach certain wave ect.

**Comment by Anuken** [comment]
- Unlockable gamemodes. After reaching specific waves, you get access to modes with special modifiers, like "self-destruct enemies only" or "2x damage but 50% health for enemies and blocks".
