### ISSUE TITLE
Logic bug: some cpu's restart after sector reload (updated)

### ISSUE THREAD

**Issue by 1am-now** [Anuken/Mindustry#4601]
**Platform**: `Linux x64`

**Build**: `release build 123.1`

**Issue**: Some processors restart after saving and loading, some don't. If a processor is linked to some building (message and button for sure, presumably any building), positioned up or right from this processor, it restarts his program after saving and loading.

**Steps to reproduce**:
Load any sector or create new sandbox game.
Build this:
```
     =
# =# # #=
=
```
Here # are processors, = are messages, processors are connected to nearest message.
Pause game. Enter this program in all processors.
```
set i 0
op add i i 1
print i
printflush message1
jump 1 always 0 0
```
Resume game, wait 10 seconds for counter to accumulate.
Save game or go to other sector. Load game. Processors # 1 and # 2 from left continue their program, processors # 3 and # 4 restart and drop counter to 0.

**Link(s) to mod(s) used**: `none`

**Save file**: Not needed, 100% reproducable in any game. But here are some: 0 - empty processors, 1 - ~10s running programs, 2 - some program reset
[saves.zip](https://github.com/Anuken/Mindustry/files/5936760/saves.zip)

**Crash report**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was fixed.
