### ISSUE TITLE
Leg pathfinding breaks if solid unbreakable is above space floor

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#4605]
**Platform**: Any, I believe. Tested on windows/linux server

**Build**: 123.1

**Issue**: If on the map you place space as the floor and then some solid unbreakable wall on top of that, Legs pathfinding gets crazy and tries to ~~swim in lava~~ cross the block, but can't succeed. This is demostrated on two following images:
![2021-02-06 18_20_22-Mindustry](https://user-images.githubusercontent.com/4199082/107123893-fcccb280-68a8-11eb-8257-4c4dcb2fcc70.png)
![2021-02-06 18_25_51-Mindustry](https://user-images.githubusercontent.com/4199082/107123894-00603980-68a9-11eb-92db-069b79a8b333.png)

**Steps to reproduce**: Load map from attachment, launch in sandbox mode.

**Link(s) to mod(s) used**: No mods

**Save file**: Not a save, but map. 
[legtest.zip](https://github.com/Anuken/Mindustry/files/5937197/legtest.zip)

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
Just to mention, it is probably not a good idea to build a map like this. But the whole point of figuring out why exactly units behave strangely seem quite unnessesary if this can be fixed.

**Comment by Anuken** [comment]
This is not an issue with pathfinding, but with collisions. Legged units *should* be able to cross solid blocks that are on space. Fixed.
