### ISSUE TITLE
PhysicsProcess NPE

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#4611]
**Platform**: Windows 10 (Linux server)

**Build**: 123.1

**Issue**: Crash client when playing kr server

**Steps to reproduce**: Unknown. It's random and hard to debug/reproduce.
This's presumed to be a server plugin problem, but I haven't found any reason why this's happening.
Not all players are crashed out, but about 60-90% of the server's people get this error at the same time.

**Link(s) to mod(s) used**: No mods but server using plugin

**Save file**: Not required.

**(Crash) logs**
```
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: steam build 123.1
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.async.PhysicsProcess.begin(PhysicsProcess.java:60)
	at mindustry.async.AsyncCore.begin(AsyncCore.java:47)
	at mindustry.ClientLauncher.update(ClientLauncher.java:151)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/async/PhysicsProcess.java#L60

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
Same issue (closed): https://github.com/Anuken/Mindustry/issues/3868

**Comment by Anuken** [comment]
Somehow, a unit that was spawned has a null type. I can't reproduce this, and even if the specific NPE shown here is fixed, it will cause issues down the line.

**Comment by DeltaNedas** [comment]
cant you just desync and ignore null unit spawns which is a lot better than crashing the client?
