### ISSUE TITLE
sound error (Android)

### ISSUE THREAD

**Issue by DjVicthor** [Anuken/Mindustry#4614]
**Platform**: `Android 29`

**Build**: `release build 123.1`

**Issue**: *when I minimize the game and then you come back there is no sound .*

**Steps to reproduce**: *. the solution is by restarting the game and it happens when you exit the application without closing it.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not interested in fixing Android sound bugs.
