### ISSUE TITLE
Core upgrade from server syncs only once, consequent upgrades cause desync

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#4617]
**Platform**: Linux/Windows

**Build**: 123.1

**Issue**: This is another stable desync issue I found - when you upgrade core from server it upgrades on client-side only once, the first time. After that any upgrades are not being received by client (unless the client is the one making upgrade).
Video demonstrating the issue:
server: https://youtu.be/i-J3CpfNq28
client: https://youtu.be/8W467wCZ4uY

As usual, `/sync` always fixes that.

**Steps to reproduce**:
1. Start attached map in PvP mode.
2. Upgrade the core from server-side.
3. Observe client getting this update
4. Upgrade another core from server-side
5. Observe client doesn't receive this update.

**Link(s) to mod(s) used**: no mods

**Save file**: test map attached.
[test_desync.zip](https://github.com/Anuken/Mindustry/files/5939338/test_desync.zip)

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> - when you upgrade core from server

What do you mean by this? There is no vanilla way to upgrade cores from the server, as far as I know.

**Comment by LeoSko** [comment]
> > * when you upgrade core from server
> 
> What do you mean by this? There is no vanilla way to upgrade cores from the server, as far as I know.

Well, I'm using vanilla 123.1 build on the video from server-side and I do have such option.

**Comment by Anuken** [comment]
Nevermind, I thought you meant as a *headless* server, not as a server player.

**Comment by LeoSko** [comment]
> Nevermind, I thought you meant as a _headless_ server, not as a server player.

Anyway, headless server also can upgrade the core by itself via BaseAI (which I extended recently quite a lot) and proper BuildPlans.

**Comment by Anuken** [comment]
Cannot reproduce. I loaded the exact same map in the exact same configuration, and the client was able to see every upgrade I made to the core from the server. I also tried another map with different gamemodes, and got similar results. This may be related to changes made in 124/`master`.

**Comment by Quezler** [comment]
ive had it happen like twice so far in all of v6, one time on anukes sector testing server and another time somewhere else, haven't been able to reproduce it yet but i recall on the anuke server that it might have been the first upgrade

**Comment by LeoSko** [comment]
Indeed I tested the scenario on latest BE and wasn't able to reproduce. Will have to remember to try things on BE as well.
