### ISSUE TITLE
Start screen is broken

### ISSUE THREAD

**Issue by RusselPlayz3422** [Anuken/Mindustry#4619]
Device Model: SM-T110
Android Version: 4.1.1
Application Version: release build 122.1
No mods installed

Extra:
Currently running with root permissions.

Report: The start-up screen is broken like the game is having a bug. This does not affect the game though but it affected my experience in playing it. Please fix

**Comment by Anuken** [comment]
No screenshots, no description of what exactly is broken, template is not filled in.

**Comment by RusselPlayz3422** [comment]
The screen is broken maybe it is because of the resulotion? The same thing also happend in landscape mode. The rest of the game is working just the loading scree![received_340095887272764.jpeg](https://user-images.githubusercontent.com/75307177/107165889-50491880-69ef-11eb-828d-829445109dd2.jpeg)
