### ISSUE TITLE
steam version crashing when opening mod folder

### ISSUE THREAD

**Issue by sup3r87** [Anuken/Mindustry#4620]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
steam build 124
**Issue**: *Explain your issue in detail.*
opening up my mod list on the steam version instantly crashes the game and gives me an error message.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i had many mods installed, some were outdated, none were malware, and none crashed the game by themselves
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods were in use during crashes.
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
this issue happens in the main menu, not ingame.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
oh dear.
**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-02_07_2021_19_47_50.txt](https://github.com/Anuken/Mindustry/files/5940798/crash-report-02_07_2021_19_47_50.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MasterNo2** [comment]
I had the same thing happen on Mac.

**Comment by driver1748** [comment]
草，好显眼的机械军团四个字

**Comment by abomb4** [comment]
See `collos:null` in your log:
If some mod forgets to write a version, it will crash the mod dialog.
