### ISSUE TITLE
Start screen broken

### ISSUE THREAD

**Issue by RusselPlayz3422** [Anuken/Mindustry#4623]
Device Model: SM-T110
Android Version: 4.1.1
Application Version: release build 122.1
No mods installed

Extra:
Currently running with root permissions.

Report: The start screen in mindustry is broken. I think this is because of the resolution. Thr samething also happens in landscape mode. It does not affect the whole game just the screen.![received_340095887272764.jpeg](https://user-images.githubusercontent.com/75307177/107181864-a41b2800-6a16-11eb-948f-b25ccaa841c0.jpeg)

**Comment by joshuaptfan** [comment]
122.1 is an old version, 124 is current. Please update your game to see if the problem hasn't already been fixed.

**Comment by Anuken** [comment]
Your screen resolution or UI scale is too high. Won't fix.

**Comment by RusselPlayz3422** [comment]
I updated it but it's stillcthe same
