### ISSUE TITLE
Errors since 124

### ISSUE THREAD

**Issue by ROBLOX2ENTITY** [Anuken/Mindustry#4625]
**Platform**: `Android 4.4.4`

**Build**: `release build 124`

**Issue**: `After updating the mindustry app to version 124, i seem to be getting this error everytime i open the app, what could it be? (start from bottom to top to check screenshots in order)I have screenshots so we know whats wrong here:`

![Screenshot_2021-02-08-13-00-26](https://user-images.githubusercontent.com/78553935/107191437-fc016100-6a0d-11eb-82bd-47c7ebc7ff00.png)
 
![Screenshot_2021-02-08-13-00-12](https://user-images.githubusercontent.com/78553935/107191502-11768b00-6a0e-11eb-9068-33f83bbd3df3.png)

![Screenshot_2021-02-08-13-00-05](https://user-images.githubusercontent.com/78553935/107191559-25ba8800-6a0e-11eb-8972-97281ee55add.png)

**Steps to reproduce**: `Happened as soon as i updated to 124`

**Link(s) to mod(s) used**: `none`

**Save file**: `The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.`

**Crash report**: `The contents of relevant crash report files. REQUIRED if you are reporting a crash.* (no crashes)`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
iirc it just means your android version is so old that https support is way out of date

**Comment by Positron832** [comment]
I also had the same problem but it is fixed in 124.1 for me.
