### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by niguandezhao** [Anuken/Mindustry#4627]
Platform: Android

Designation vivo Y70s 
Model V2002A 
vivo ROM Funtouch OS_10 
Android version 10 
Processors 2.0 GHz 880 octa-core

release build 124

Issue: Re-entering the game after importing a save or mod will flash.But when I reinstall version 123.1 and repeat the above steps, it does not flash back.

Crash Log: I can't get the crash log because I have to erase the data to get into the game again.

**Comment by BlueWolf3682** [comment]
Template.

**Comment by niguandezhao** [comment]
> 平台：Android
> 
> 名称vivo Y70s
> 型号V2002A
> vivo ROM Funtouch OS_10
> Android版本10
> 处理器2.0 GHz 880八核
> 
> 发布版本124
> 
> 问题：导入保存或修改后重新进入游戏将会闪烁。但是当我重新安装版本123.1并重复上述步骤时，它不会闪回。
> 
> 崩溃日志：我无法获取崩溃日志，因为我必须擦除数据才能再次进入游戏。
