### ISSUE TITLE
Bullets dodge targets instead of hitting them ;-;

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4630]
**Platform**: Windows (Steam)

**Build**:  124.1

**Issue**: Gamma really likes to not hit stuff when shooting at any angle that isn't a cardinal direction.

**Steps to reproduce**: Placed a duo on the crux team, decided to shoot it and found the problem. The problem can be seen here: https://i-dont.go-outsi.de/HVkhEj.webm

**Save file**: [330.zip](https://github.com/Anuken/Mindustry/files/5944977/330.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![2021-02-08 11-25-39](https://user-images.githubusercontent.com/10100000/107248552-67443680-6a00-11eb-9d35-f7018f1929dc.gif)

Doesn't happen to me on any save, including the one you sent. Tested various orientations.

**Comment by buthed010203** [comment]
Very odd, this is a completely vanilla 124.1 build

**Comment by buthed010203** [comment]
@Anuken oh its apparently tied to fps 🤔
