### ISSUE TITLE
SAND AND SORTERS

### ISSUE THREAD

**Issue by Stupider666** [Anuken/Mindustry#4632]
**Platform**: `Windows 10 x64`

**Build**: `steam build 124.1`

**Issue**: *Explain your issue in detail.*
i was trying to sort sand out of a titanium belt while set to scrap on ground zero map, and it passed threw the sorter like it didn't exist. inverted sorter didn't work either
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
We need a save file at least.

**Comment by Anuken** [comment]
This is incredibly unlikely to be a real bug. No save, no screenshots.

**Comment by Stupider666** [comment]
trying to finde the save file

**Comment by Stupider666** [comment]
[save file.zip](https://github.com/Anuken/Mindustry/files/5946350/save.file.zip)

**Comment by Stupider666** [comment]
nvm i figured it out it was a router backlog

**Comment by DeltaNedas** [comment]
tws quiz before report bugs when

do you router chain
[yes]
no

autoclosed
