### ISSUE TITLE
Flare/horizon/others secret buff

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#4638]
**Platform**: Windows 10

**Build**: 124.1

**Issue**: Flare & Horizon have a range of 17 in the core database (previously 14 & 3 in v123)

**Steps to reproduce**: Core Database -> Flare

**Link(s) to mod(s) used**: rftm/logic debugger/cliff/ui-lib

**Save file**: [sandbox.zip](https://github.com/Anuken/Mindustry/files/5947185/sandbox.zip)

**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is correct. Maximum/target range is now displayed.
