### ISSUE TITLE
Resource requirements are in brazil

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4639]
**Platform**: *Android*

**Build**: *124.1*

**Issue**: *I think the image is mostly self-explanatory.*
![Screenshot_20210207-101939](https://user-images.githubusercontent.com/61173114/107312099-e8c1b600-6a4c-11eb-8d7d-102b9a60fc06.png)

**Steps to reproduce**: *Launch with a large loadout.*

**Link(s) to mod(s) used**: *none*

**Save file**: *This isn't save specific.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

im getting impatient

**(Crash) logs**: *none*

**Possible fix**: *Move the shematic ui a bit up and put a scrollable list of materials, with this arrangement:*

copper icon: total (cost + loadout)
lead icon: total (cost + loadout)
silicon icon: total (cost + loadout)

*etc*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest official release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
If memory serves, you can actually swipe to scroll that left and right...

**Comment by MEEPofFaith** [comment]
~~Don't play in portrait mode.~~

**Comment by BlueWolf3682** [comment]
> If memory serves, you can actually swipe to scroll that left and right...
this is true, but im still keeping this open cause theres no visual indicators for that and it looks messy as hell.

**Comment by Anuken** [comment]
Scroll the resources.
