### ISSUE TITLE
Armor stat is broken.....

### ISSUE THREAD

**Issue by UnionofSovietSocialistRepublics** [Anuken/Mindustry#4641]
**Platform**: *Windows

**Build**: *124.1

**Issue**: *The armor stat somehow broke while I looking at mono stat

**Steps to reproduce**: *Idk, it just happens while I looking at mono stat

**Link(s) to mod(s) used**: *No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---
![unknown](https://user-images.githubusercontent.com/71920146/107330476-2f162400-6ae4-11eb-9261-559f8f279b3c.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheMrAlbert** [comment]
It looks fine to me. Try relaunch the game and check if it fixes.

**Comment by Anuken** [comment]
You are likely using an external translation bundle. Works for me.
