### ISSUE TITLE
"[E] to enable building" appears over "[V] to respawn in core"

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry#4642]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Self compiled as of https://github.com/Anuken/Mindustry/commit/852b0a97fe8fa41e7460be21b9db898a84c5cd05 

**Issue**: *Explain your issue in detail.*
"[E] to enable building" appears over "[V] to respawn in core"
![image](https://user-images.githubusercontent.com/57631841/107345233-a7b8b880-6ac3-11eb-808c-542855fb3fa1.png)
(yes I know the [v] to respawn in core is german)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. change unit
2. press e

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[bug_report.zip](https://github.com/Anuken/Mindustry/files/5950338/bug_report.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Caused by #3857. Reverting.

**Comment by joshuaptfan** [comment]
Even with #3857 reverted, a similar bug occurs with the original "[E] to resume building, [Q to clear plan, [F] to select+copy" if building is paused and a building plan exists. I will look for a solution to allow these UI elements to coexist.
