### ISSUE TITLE
Naval Unit Steering Problems

### ISSUE THREAD

**Issue by ROBLOX2ENTITY** [Anuken/Mindustry#4644]
**Platform**: `Android 4.4.4`

**Build**: `release build 124.1`

**Issue**: `I cannot seem to steer any naval units in intense lag EXCEPT for risso. Especially in servers. When players progress a lot, the entities in game (moving items, units, etc) make me lose FPS. And when i ride a bryde for example i just go straight and get stuck to a wall when the lag level gets high.`

**Steps to reproduce**: `When players progress all the way to alloy, it starts to lag because of the amount of entities, power, effects, etc. I know i can disable the effects with settings but i dont think it does much, not blaming the app for the lag. Oh and your new update (124.1) fixed the errors everytime i open the app, thanks.`

**Link(s) to mod(s) used**: `none`

**Save file**: `The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.`

**Crash report**: `The contents of relevant crash report files. REQUIRED if you are reporting a crash.`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
confirmed reproduction, google pixel 2, ipad 4, ipod touch 6, samsung galaxy tab 4 7.0. must be below 15 fps.

**Comment by Anuken** [comment]
This won't be fixed. <15FPS gameplay is not supported.
