### ISSUE TITLE
Steam achievement Explorer is not triggered

### ISSUE THREAD

**Issue by crides** [Anuken/Mindustry#4645]
**Platform**: Linux (Arch 5.9.14)

**Build**: `Steam build 124.1`
**Issue**: All zones are unlocked (not all are captured) on Serpulo, but the "Explorer" achievement on Steam is not triggered.

**Steps to reproduce**: Capture all zones on Serpulo that's near a grayed out/locked zone, and capture any enemy bases nearby.

**Link(s) to mod(s) used**: None

**Save file**: [explorer.zip](https://github.com/Anuken/Mindustry/files/5953501/explorer.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
