### ISSUE TITLE
Turrets (not always) targeting multiblocks

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4651]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20702`

**Issue**: turrets discriminate against attacking larger blocks that dance on the edge of their range:

**exhibit a** - showing a line of ripples with a bunch of blocks right on the edge:
![Screen Shot 2021-02-10 at 20 38 04](https://user-images.githubusercontent.com/3179271/107562650-6538ce00-6be0-11eb-82be-f491e08ca629.png)

**exhibit b** - when unpaused (above screenshot was in editor mode) only the mender gets attacked:
![Screen Shot 2021-02-10 at 20 39 19](https://user-images.githubusercontent.com/3179271/107562653-6669fb00-6be0-11eb-82da-3247be89b6d1.png)

the shown block sizes of 2, 3 & 4 do not get targeted, in the 2nd picture i have even moved the size 4 block one tile up and it still does not get attacked by the ripples.

while this issue has existed for a long time and is probably part of many attacking strategies, it just feels wrong to have charted out a "safety line" only for it to change based on what blocks you build next to it.

the cause? well probably that the distance is calculated on the build(ing) center instead the multiblock tiles that are actually in range, i could probably suggest some fixes but i'm sure whatever you have in mind of how to solve this will be far superior.

**Steps to reproduce**: build roughly what i've shown on the two exhibits, or just download the map file below:

**Save file**: [range_discriminator.msav.zip](https://github.com/Anuken/Mindustry/files/5961071/range_discriminator.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The entire targeting system (units, turrets) uses the distance from the center of the *targeter* to the center of a *target* for validation. Hitbox size is not used. That's how the game has worked since the start, and it's not really a bug. Changing the system when it's implemented as such in many files is far from trivial.

**Comment by joshuaptfan** [comment]
Perhaps don't have to worry about detecting the corners of large blocks, but at least account for the "radius" of blocks. Why not subtract half the width of blocks from the distance calculation?

**Comment by BlueWolf3682** [comment]
this happens with units too and its annoying cause its difficult to heal larger units with higher health

**Comment by Quezler** [comment]
> linking for reference: 27c8efc672fa91d6e885606466a17e5a8f9af5c8 & 0350e6bbf4bf7bd7596322ba598d5dd1b989cc94

![Screen Shot 2021-02-11 at 18 43 25](https://user-images.githubusercontent.com/3179271/107676155-1c911b80-6c99-11eb-9b77-6ff147d3fa99.png)
