### ISSUE TITLE
mod.hjson ignored

### ISSUE THREAD

**Issue by Newguy-ish** [Anuken/Mindustry#4653]
**Platform**: Linux

**Build**: 124.1

**Issue**: I tried modding Mindustry using other mods and the wiki guide as a reference, but Mindustry ignores the mod.hjson for unknown reasons. MEEPofFaith tried to help but didn't see any problems.
![conlog](https://user-images.githubusercontent.com/78880071/107581776-dc7a5c00-6bf8-11eb-8dc8-17891c2a4681.png)
![mainfolder](https://user-images.githubusercontent.com/78880071/107581798-e3a16a00-6bf8-11eb-9cd3-ac38bb86d95e.png)

**Steps to reproduce**: Download the attached mod and check console logs.

**Link(s) to mod(s) used**: 
[throwers.zip](https://github.com/Anuken/Mindustry/files/5962008/throwers.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Newguy-ish** [comment]
mod.hjson
```name: "throw"
displayName "Yeet Industries"
author: "Newguy"
description: "Help."
version: "v-255"
minGameVersion: 122```

**Comment by BlueWolf3682** [comment]
You don't have a name field. Bring modding issues to the modding community, not to here.

**Comment by Newguy-ish** [comment]
mod name was included, just didnt select it on the copy-paste

**Comment by Newguy-ish** [comment]
I'm not seeing any issues with the grammar, nor did MEEP.

**Comment by Newguy-ish** [comment]
honestly i don't really care anymore

**Comment by BlueWolf3682** [comment]
![Screenshot_20210210-163136](https://user-images.githubusercontent.com/61173114/107588816-dd43cb80-6bc1-11eb-9266-4284796c37d2.png)
h

**Comment by DeltaNedas** [comment]
why are you using a zip at all
