### ISSUE TITLE
Infinite power without factory

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry#4657]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 124.1

**Issue**: *Explain your issue in detail.*
![{)V)9P G0FMYH@%WVWQ_T2P](https://user-images.githubusercontent.com/15688938/107662247-0dc05e00-6cc5-11eb-8d93-4ca7de1c6e84.png)
There are not power factory, but infinite power.(position 209,6 in following save)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
See position 209,6 in following save

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[save.zip](https://github.com/Anuken/Mindustry/files/5966665/save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* No Crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's using battery power, which is depleting.

**Comment by way-zer** [comment]
No ,the battery power not decrese

**Comment by Anuken** [comment]
It *is* decreasing for me.

![image](https://user-images.githubusercontent.com/10100000/107663540-7b36a500-6c59-11eb-9ac8-a66249ac2043.png)

**Comment by way-zer** [comment]
See other places? Or can you join the server to find it (ip mdt.wayzer.cf version 124)

**Comment by way-zer** [comment]
> It _is_ decreasing for me.
> 
> ![image](https://user-images.githubusercontent.com/10100000/107663540-7b36a500-6c59-11eb-9ac8-a66249ac2043.png)

Oh, I load the save, it is decreasing in given postion.
But, i connect that to the main net and disconnect from the main net. The battery is not decresing

**Comment by Anuken** [comment]
I'm not sure how, but in your save, the power grid got connected to the enemy, leading to infinite power from their sources. This has never happened before, so I'm guessing it either happened due to a plugin or something related to editor team changes.

**Comment by way-zer** [comment]
> This has never happened before,  

I have not encounter this bug before. But one player said he encountered it many times in plague mode. 
> so I'm guessing it either happened due to a plugin or something related to editor team changes.

There is no plugin having something to do with the power node or even modifing building. And this happened in game.

**Comment by way-zer** [comment]
I found the reason. It is editor resize don't clear old power grid.
More specific, the outer is emery bases, then resize the map bigger and place block on old places, the block connects to the emery power grid.

**Comment by way-zer** [comment]
The deeper reason is PowerModule.links save the pos, which doesn't fix after resize

**Comment by sk7725** [comment]
I think it depleted because judging by your screenshots, the mass cannon bullet did not save thus cutting the perpetual chain.
