### ISSUE TITLE
Some sprites are smaller than usual when researching technology in the tech tree

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#4659]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

124.1

**Issue**: *Explain your issue in detail.*

When you unlock something new that you can research on the campaign, the sprite is smaller than usual (in some cases, have not found any pattern so far), and is only fixed by a restart
<img width="406" alt="Graphite" src="https://user-images.githubusercontent.com/57579569/107724469-8d403400-6ca9-11eb-8740-e2821b8fad0f.PNG">
<img width="787" alt="Scorch and Combustion" src="https://user-images.githubusercontent.com/57579569/107724474-8fa28e00-6ca9-11eb-85bb-c42496030429.PNG">

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Create a new campaign save, play for a little until you research graphite/scorch/combustion generator (Only ones that were smaller for me)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

DeltaNedas/cliff
DeltaNedas/dev-mode
abomb4/dimension-shard
Eschatologue/Heavy-Armaments-Industries
younggam/multi-lib
MEEPofFaith/progressed-materials
genNAowl/upgraded-factories

(However, since I thought this issue happened in the past, I doubt the issue is related to these mods.)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[savefile.zip](https://github.com/Anuken/Mindustry/files/5969416/savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
I am reopening [this issue](https://github.com/Anuken/Mindustry/issues/3976) due to screenshots being available, unlike before.

**Comment by joshuaptfan** [comment]
You do not need to create a new duplicate issue. Even though the old issue is "closed", you can still provide Anuke with info by commenting there.

**Comment by nichrosia** [comment]
Oh, sorry about that, I *did* provide more information on the other one, but since it didn't reopen itself I made this.

**Comment by Anuken** [comment]
I've done a nearly-complete campaign playthrough and researched countless blocks, with no issue like this ever appearing. This won't be fixed.
