### ISSUE TITLE
Curvature of text in Russian translation

### ISSUE THREAD

**Issue by baobabbab** [Anuken/Mindustry#4664]
Platform: Android

Build: 124.1

In Russian translation, while you looking at unit health (poly in my case) the *health* text slightly curved

select Russian language at settings, then tap at unit to see its health

Mods not used

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Screenshot
![Screenshot_2021_0212_221043](https://user-images.githubusercontent.com/78983258/107821828-c9e15d80-6d85-11eb-8c61-6cb036e787b7.png)
Save
[sector-serpulo-145.zip](https://github.com/Anuken/Mindustry/files/5974252/sector-serpulo-145.zip)

**Comment by Anuken** [comment]
Font issue, won't fix.
