### ISSUE TITLE
Bug with shoot

### ISSUE THREAD

**Issue by pawlick228** [Anuken/Mindustry#4670]
**Platform**: `Windows 7 x64`

**Build**: `release build 124.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [x] Im find the bug!!!
- [x] Im not use plugins.
- [x] This bug view in velocity and shooting oneway, the bullet velocity to and fly so far.
- [x] Good night )
- [ ] Im love your game and company))))))))))))))))
- [x] Your bests)

https://user-images.githubusercontent.com/79018905/107859237-b5ae6680-6e40-11eb-9041-e2c9841c3291.mp4

**Comment by Anuken** [comment]
No save, no description of the actual bug, video doesn't play.

**Comment by pawlick228** [comment]
Sorry im di it in soon.
Im where busy.

With best wishes. Pawlick)
