### ISSUE TITLE
Too high base damage cause it does not damage.

### ISSUE THREAD

**Issue by shugen002** [Anuken/Mindustry#4672]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: 124.1

**Issue**: Too high base damage cause it damage calculate overflow.

**Steps to reproduce**: start below map in sandbox and start the explosion , it will stop chain explode strangly.
(make sure your computer can handle the fire and explosion in 60 tps , or can't trigger the bug)

**Link(s) to mod(s) used**: none.

**Save file**: 
[放鞭炮.zip](https://github.com/Anuken/Mindustry/files/5977000/default.zip)

Personally , I believe is too high base Damage in `mindustry.entities.Damage#tileDamage` cause `PropCell.get` calculate out a minus damage.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
![Screenshot_20210213-214859](https://user-images.githubusercontent.com/61173114/107868911-abdb3200-6e45-11eb-98e5-39ee74b6d20c.png)
it all went fine, though i found out that detonating a core when theres a lot lags the game hard.

**Comment by shugen002** [comment]
> ![Screenshot_20210213-214859](https://user-images.githubusercontent.com/61173114/107868911-abdb3200-6e45-11eb-98e5-39ee74b6d20c.png)
> it all went fine, though i found out that detonating a core when theres a lot lags the game hard.

Because the item source speed is related to tps , bad device may not trigger the bug . It need a certain num range of Pyratite to make it happen.

**Comment by shugen002** [comment]
You can add this code:
``` java

                if(damage<0){
                    Log.info("minus damage @,@ @ @",x,y,baseDamage,damage);
                }

```

between L396-L398

https://github.com/Anuken/Mindustry/blob/092d152bdc1ab1393409acdcbc5e35a21fabdcd4/core/src/mindustry/entities/Damage.java#L396-L398

to help catch this bug.

**Comment by XxsuperdeadlysniperxX** [comment]
@shugen002 your missing a part of the checkboxs (and noone else bothers to point this out lol)

**Comment by XxsuperdeadlysniperxX** [comment]
The edit above is cuz i made a stupid and didn't check if there was a different template on anuken/mindustry

**Comment by shugen002** [comment]
> @shugen002 who would ever place cores on slag anyways?

i replace all slag into stone , this still happen.

**Comment by shugen002** [comment]
I found the reason:

```java
    public static void tileDamage(Team team, int startx, int starty, int baseRadius, float baseDamage){
```

```java
    @Struct
    static class PropCellStruct{
        byte x;
        byte y;
        short damage;
    }
```
|type|data range|
|---|--|
|short|-32,768 to 32,767|
|float|approximately ±3.40282347E+38F (6-7 significant decimal digits) Java implements IEEE 754 standard|

**Comment by Anuken** [comment]
That won't be fixed. The current damage algorithm is broken in many other ways that don't involve propagation storage. Wait until a better one is implemented.

**Comment by shugen002** [comment]
> That won't be fixed. The current damage algorithm is broken in many other ways that don't involve propagation storage. Wait until a better one is implemented.
but at least we can limit the max explosiveness to avoid this overflow and behavir more normaly.

**Comment by shugen002** [comment]
> That won't be fixed. The current damage algorithm is broken in many other ways that don't involve propagation storage. Wait until a better one is implemented.

but at least we can limit the max explosiveness to avoid this overflow and behavir more normaly.
