### ISSUE TITLE
bug with schematics, and processors 

### ISSUE THREAD

**Issue by sebasom2** [Anuken/Mindustry#4679]
**Platform**: `Windows 10 x64`

**Build**: `release build 124.1`

**Issue**:  "when I put a schematic with more than two processors while one or more android users are connected they are instantly expelled "

**Steps to reproduce**: "The steps to make it happen are simple, you just have to put a schematic with several processors full of information (it happened to me with drawings only) "

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save + no schematics linked.
