### ISSUE TITLE
Crawler got stuck on a wall

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#4680]
**Platform**: Windows 10

**Build**: 124.1 Steam

**Issue**: I was playing Tar Fields as normal, and on wave 3, a crawler got stuck on a wall, unable to move to the thing it was targeting
![image](https://user-images.githubusercontent.com/34169172/107908907-5752b800-6f14-11eb-908f-c1cf67c27507.png)

**Steps to reproduce**: Go to tar fields, place stuff in this formation
![image](https://user-images.githubusercontent.com/34169172/107908948-72bdc300-6f14-11eb-8435-a79d40bac431.png)

**Link(s) to mod(s) used**: No mods used

**Save file**: 
[bruhcrawler.zip](https://github.com/Anuken/Mindustry/files/5979654/bruhcrawler.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by WilloIzCitron** [comment]
hmm Anuke needs improve a Unit Pathfinding?
