### ISSUE TITLE
Turrets don't update liquids

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#4684]
**Platform**: *Android*

**Build**: *124.1*

**Issue**: *Liquid and laser turrets show the wrong liquid after a second is inputted.*
![Screenshot_20210215-024718](https://user-images.githubusercontent.com/61173114/107935057-1c657a00-6f3e-11eb-9161-a494a2dc38db.png)

**Steps to reproduce**: *Feed a turret one liquid, and then feed it another.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod.*

**Save file**: *Unable to provide due to an issue with zip file export and import.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *none.*

**Possible fix**: *make the turret display what liquid is taking the most capacity instead of which liquid was first.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem is a duplicate but is not fixed.**

**Comment by Anuken** [comment]
Cannot reproduce - turrets correctly display their current liquid when liquids are switched.

**Comment by Quezler** [comment]
@Anuken steps to reproduce:

- build tsunami
- build liquid source
- set to slag
- set to oil
- enter the turret and fire out all the oil
- notice the display now displaying this:

![Screen Shot 2021-02-15 at 15 29 34](https://user-images.githubusercontent.com/3179271/107958747-c4ad2a00-6fa2-11eb-80d8-4bce35b418c3.png)

(lower liquid id's take priority, slag droplet can show under the oil bar but not the other way around)

**Comment by Anuken** [comment]
I managed to reproduce it with slag->oil, but not other combinations. *(this is why I ask for a save)*

**Comment by Quezler** [comment]
~~reap his soul~~

**Comment by BlueWolf3682** [comment]
This phone has an issue with zip files, I could not get a save because the zip always has 0 bytes.
