### ISSUE TITLE
Units vanish

### ISSUE THREAD

**Issue by Sp3rw3r** [Anuken/Mindustry#4685]
**Platform**: Windows

**Build**: 124,1

**Issue**: umove with extremely large numbers makes units disappear. It seems they cannot be brought back to the battlefield after

**Steps to reproduce**: Someone else reported the issue after he (I guess)  made a bug in his logic:
bXNjaAF4nG1QW0hTYRz/jlO7qiOvFNJXVBS6oRNCezF68MFsFd0skZhr6UnmbBOVKHJbXkKbIhnhLQW1fOq4dvB4NrdCAiHC/wcGPgyp6MFBGpVkF8P+5xTWQ+fjfOd//r/L/0I0hIsi0VUmq4VkwAMQWQNrBoG5QAaBwhgmnBgGYRKjZryDzImgRLZcsjjMdr66hrdVcaegC2l+kCjiLgixBhDACxJzsTbKPCjDkIL3v4YUfMgPIjTJWkGkKhrElA8kxLEX1ppJ0RaZKKPo5USlCOOqh0tPsw9QGERsHCUCTCAVXSbXK/lZm/LF+pgIsVbWgmJZTw0o60TEzzzoJ/2WyUpLEAKZufU0Bxl9aDmmcP41F5CFQ8ETfP2snTWh3LM+KRp49YoSmV6lK+aGwF/xOIYh5la7E9QVKZtROg1gYUE1lnZpyAarxeEwlVtIgpU32226arvNjBmbncQ66vgacwUhREOUJ5ojOSXldoulqhQX4cPx/H+c2W3lB8cLgkxVd9wGtitgLYlweEg8Gvyo77V2HDNOZWkL0g8O9JbNJu7JmC394JSru/kd73Kfefi55BQ61NLPGSGmS5u/mHzZeLp3yNSoq1x+z1YK4m9t1Jd2RpL2OfbGNaWIuq1zZ86+vPdw21S0WJQ08kZ8cTRNM5872jSyP7NQ0Du3lz0qme77dGKqvniwJ1k2NLoC0vMl3ZW64u6ic1my4b4xcqe2ZiD98QQ3TxYjTytvrizNpNq+xhwKX6tYaP5yfSYh3Pa9Y8JeuynvQkZq2oq7gL4qnD8/fXhtNCX25PGI2D5s7eFWw3n9gc+Jq9o+984bP0fa1+KOtORczX79ceHb6vLF3dq3qXz+3U4ShYdsJuQX57Wxxw==

**Link(s) to mod(s) used**: No mods

**Save file**:
[170.zip](https://github.com/Anuken/Mindustry/files/5982454/170.zip)

[removed]
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Neither the program or the involved units seem to have crashed.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
Could you maybe remove the schematic and description and dm this issue to Anuke instead, as this is incredibly bad for servers.
