### ISSUE TITLE
sprites-override only changing battery build plan sprite

### ISSUE THREAD

**Issue by Newguy-ish** [Anuken/Mindustry#4687]
**Platform**: *ubuntu Linux*

**Build**: *124.1*

**Issue**: *When trying to retexture the battery through sprites overide this happens:
![spritenotoverriden](https://user-images.githubusercontent.com/78880071/107986343-259d2800-6fcc-11eb-959e-6a09c682f964.png)
This does not seem to be an issue with other blocks.
*

**Steps to reproduce**: *Install the mod and place a battery, then compare it to the placement preview.*

**Link(s) to mod(s) used**: *
[mess.zip](https://github.com/Anuken/Mindustry/files/5983751/mess.zip)
*

**Save file**: *
[savefile.zip](https://github.com/Anuken/Mindustry/files/5983757/savefile.zip)
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You're not overriding the battery bottom or light.

**Comment by Newguy-ish** [comment]
oh.
