### ISSUE TITLE
Invincible guardian in tar fields

### ISSUE THREAD

**Issue by MrFlubber** [Anuken/Mindustry#4690]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: Steam Build 124.1

**Issue**: I got to the last wave on tar fields and the guardian took no damage from anything, I've been told the shield is not strong enough to survive 20 lancers with 4 salvos. Even tanked a foreshadow shot and took no damage

**Steps to reproduce**: All I did was get to the last wave on tar fields

**Link(s) to mod(s) used**: no mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[save.zip](https://github.com/Anuken/Mindustry/files/5984565/save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Not applicable

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It isn't invincible, it just has a lot of shields. I can decrease this amount, but it won't change your save.

**Comment by AnOreo1** [comment]
question, it is meant to be nigh unbeatable? the stupidly high amount of shields seems unfair, given the old difficulty

**Comment by Anuken** [comment]
It was supposed to be harder than before, but not unbeatable.
