### ISSUE TITLE
Changing GUI problem

### ISSUE THREAD

**Issue by Laggyboi0701** [Anuken/Mindustry#4692]
**Platform**: *Windows 10*

**Build**: *124.1.*

**Issue**: *when i changed my gui to 75% and restarted, the mindustry app just dissapeared. i tried to open it, and the gui changed into normal (100%), i tried it without mods, and its still the same.there was no crash message.

**Steps to reproduce**: *open the settings and change the gui in any size*

**Link(s) to mod(s) used**: *Proggressed Materials,Pixelcraft,Chaos Arranity,Missing Category Units,Betamindy,Mindhorition,Braindustry,The Better Turrets,Dimension Shard,Gold Mod, Diamond Ore Mod, Larger Cores,Exotic Mod,Gravasillo Mod,Heavy Armaments Industries,Infintodustry, V6 Invincible Cheat,Vanilla Enhanced,Sh*t*ss mod by Goober.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by notrealn** [comment]
ok but what if you included the crash log
![image](https://user-images.githubusercontent.com/56411504/108010751-97c53b00-6fd3-11eb-8204-36524a82f911.png)

**Comment by Laggyboi0701** [comment]
> ok but what if you included the crash log
> ![image](https://user-images.githubusercontent.com/56411504/108010751-97c53b00-6fd3-11eb-8204-36524a82f911.png)

there was no crash log, and no crash message had appeared when it closed the app

**Comment by Laggyboi0701** [comment]
> > ok but what if you included the crash log
> > ![image](https://user-images.githubusercontent.com/56411504/108010751-97c53b00-6fd3-11eb-8204-36524a82f911.png)
> 
> there was no crash log, and no crash message had appeared when it closed the app

**Comment by Laggyboi0701** [comment]
i accidentally closed it, sorry  about that

**Comment by Cherriodude** [comment]
May I ask what exactly do you mean by disappear?

**Comment by Laggyboi0701** [comment]
> May I ask what exactly do you mean by disappear?
when my mindustry was loading with 75% gui size,the app suddenly closed

**Comment by Anuken** [comment]
No log.
