### ISSUE TITLE
Grass cliff/obstacles flicker when next to conveyor

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#4694]
**Platform**: Windows 10

**Build**: 124.1

**Issue**:

https://user-images.githubusercontent.com/45698812/108030642-699c2700-6fe4-11eb-87d0-0cf4f46080a7.mp4

**Steps to reproduce**: Have map with grass and conveyors

**Link(s) to mod(s) used**: cliff, ui-lib, logic-debugger, rftm

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/5986784/bug.zip)

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
Looks like Z-fighting.

**Comment by BlueWolf3682** [comment]
i dont think using cliffs is supported anymore.
