### ISSUE TITLE
Уже же сказали, что mindustry.ru не впустят в глобал ни под каким предлогом. Анюк ясно дал понять это, так зачем опять пытаться? Однажды совершенная ошибка может полностью всё поломать и её уже никак не исправить. Так что просто не стремитесь в глобал, а живите как Петручио.

### ISSUE THREAD

**Issue by UglyBugly** [Anuken/Mindustry#4700]
> Уже же сказали, что mindustry.ru не впустят в глобал ни под каким предлогом. Анюк ясно дал понять это, так зачем опять пытаться? Однажды совершенная ошибка может полностью всё поломать и её уже никак не исправить. Так что просто не стремитесь в глобал, а живите как Петручио.

>
Не стоит принимать за истину ваше мнение которое вы же и навязали анюкену путем многочисленных жалоб, он просто не хотел больше слышать про сервер из-за вас

**Comment by kiVts** [comment]
Согласен
