### ISSUE TITLE
Red is not red anymore

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#4702]
**Platform**: Windows

**Build**: 125

**Issue**: Look at two screenshots for the same phrase into chat: `[red]Hello` from prior to 125 and in 125

before 125 (example from v5)
![image](https://user-images.githubusercontent.com/4199082/108115345-a7f81b80-70a2-11eb-913f-1f4078767c17.png)
in 125
![2021-02-16 22_00_08-Mindustry](https://user-images.githubusercontent.com/4199082/108115374-b6463780-70a2-11eb-9bb8-2eefc022aa76.png)

Seems like color scheme has completely changed and red is not vibrant and I believe placing non-true red instead of plain red is an issue.

**Steps to reproduce**: type `[red]Hello` into chat

**Link(s) to mod(s) used**: no mods

**Save file**: not needed

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
not a bug, intended change to make the server list less of an eyesore.

**Comment by LeoSko** [comment]
Server list is one point, but there are countless plugins using `[red]` as a sign for warnings, which I believe is significant. Replacing red *with basically pink* can't be expected and can break visibility in other places (and already did on my server).

**Comment by Quezler** [comment]
i do agree that it messes up a lot of other stuff outside of the server list.

**Comment by LeoSko** [comment]
Also, it takes no effort to bring back **true red** into server list by replacing `[red]` with `[#f00]`, so if that is what it meant to do - it failed.

**Comment by Quezler** [comment]
true, i am in favor of reverting the color change in arc, and adding new guidelines to the server list regarding colors.

**Comment by Anuken** [comment]
> Also, it takes no effort to bring back true red into server list by replacing [red] with [#f00]

You are free to do that if you wish.

> so if that is what it meant to do - it failed.

People generally do not use `[red]` because they specifically want full-saturation eye-bleeding red, they use it because they want something that looks red-ish. I prefer this new red color to the old one.

> I believe placing non-true red instead of plain red is an issue.

I do not.

**Comment by joshuaptfan** [comment]
> Replacing red _with basically pink_

["It's not pink, it's lightish red."](https://www.youtube.com/watch?v=hgi_YPxE5Kk)
