### ISSUE TITLE
Bullet homing is still weird at high fps

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4704]
**Platform**: Windows

**Build**: 125.0

**Issue**: The issue from #4630 still exists in the latest update

**Steps to reproduce**: Same steps as last time, place a block on the crux team and try shooting at it from any odd angle. It does seem like this is way better though as it isn't noticeable at 240 fps and it's not that bad at 1000, it starts to get really bad around 1500.
https://aethex.is-a.fail/R37t5g.webm 1000 fps
https://extremely.questionable.link/nLIGsQ.webm 60 fps (vsync)

**Save file**: [332.zip](https://github.com/Anuken/Mindustry/files/5992364/332.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is absolutely no good reason to play at 1000+ FPS. Don't.
