### ISSUE TITLE
logic hints `lenum.xxx` mixed up

### ISSUE THREAD

**Issue by liuxilu** [Anuken/Mindustry#4706]
**Platform**: Windows/JAR

**Build**: 6.0 release 125

**Issue**: Currently, the only buggy behavior found is `Draw color`'s tooltip shown as `Illuminator color.`. May have more in the future.

**Steps to reproduce**:
- Open one processor's logic editor
- Add `draw` command
- Click subcommand selector
- Hover on `color`

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by liuxilu** [comment]
https://github.com/Anuken/Mindustry/blob/080fe8c3c4893ee2df3fc2f5bfb84b936e5ae35b/core/src/mindustry/logic/LStatement.java#L75-L78
Enum name: `p.getClass().getSimpleName()`

**Comment by Anuken** [comment]
I'll remove the enum.
