### ISSUE TITLE
Blindshoot mouse tracking

### ISSUE THREAD

**Issue by Endermancat** [Anuken/Mindustry#4707]
**Platform**: `Android 26`

**Build**: `release build 125`

**Issue**: *i buyed keyboard and mouse for android but main broblem that mindustry don't have full mouse tracking for example i trying to put cheme but it's literally blind shoot*

**Steps to reproduce**: **

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Catchears** [comment]
See https://github.com/Anuken/Mindustry/pull/4284#issuecomment-756899495.
