### ISSUE TITLE
Use say command in console may cause connection disconnect.

### ISSUE THREAD

**Issue by shugen002** [Anuken/Mindustry#4709]
**Platform**: Windows

**Build**: 125

**Issue**: I set up a cron task to use say command as a server broadcast. and sometimes this cause all player in my server disconnect and with an error.

I check the log on the server , no error showed just a lot of disconnect with reason `closed` and `disappeared`.

**Steps to reproduce**: use say command in server console.

**Link(s) to mod(s) used**: none

**Save file**: i don't think this related to specify map or saves and happen in multiple maps.

**(Crash) logs**: 

![image](https://user-images.githubusercontent.com/10257291/108191316-f0b8de80-714d-11eb-8830-df96b02f1928.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
could you show the cron task? (although i'm fairly sure what it is already, happened on v5 as well with /js shenannigans)

**Comment by shugen002** [comment]
![image](https://user-images.githubusercontent.com/10257291/108192550-5eb1d580-714f-11eb-9313-6f372267c4df.png)
(I am using pterodactyl panel)

**Comment by Quezler** [comment]
i'm guessing it might have something to do with those special characters, or just that the string isn't sent as utf8 somehow 🤔

**Comment by shugen002** [comment]
> i'm guessing it might have something to do with those special characters, or just that the string isn't sent as utf8 somehow 🤔

they all work must of time.  i think maybe is a race condition happen in sending packet.

**Comment by driver1748** [comment]
估计控制台不支持中文？

**Comment by shugen002** [comment]
> 估计控制台不支持中文？

都说了大部分时候没问题，就是莫名触发

**Comment by LeoSko** [comment]
Had exactly the same thing when I was not aware of internal schedulers via Timer class and used my own Java threads executors which indeed could intercept the packet sending.

**Comment by Anuken** [comment]
You're likely sending messages incorrectly.
