### ISSUE TITLE
The logic to know if it's a phone or a tablet isn't reliable

### ISSUE THREAD

**Issue by rocboronat** [Anuken/Mindustry#4710]
**Platform**: *Android*

The code that says if the device is a phone or a tablet just checks if the device is able to make phone calls. There are tablets that are able to do it. What should be done is to check the screen size.

This is the piece of code:

```
private boolean isTablet(Context context){
        TelephonyManager manager = (TelephonyManager)context.getSystemService(Context.TELEPHONY_SERVICE);
        return manager != null && manager.getPhoneType() == TelephonyManager.PHONE_TYPE_NONE;
}
```

I could open a PR but as there are a lot of open ones, I prefer to ask first 😄

**Comment by Quezler** [comment]
the amount of open pr's doesn't matter, go for it 🙂

**Comment by rocboronat** [comment]
Cool! I will :·)

**Comment by Anuken** [comment]
It's not supposed to be particularly reliable, and frankly I don't care. Differentiating between what is and isn't a tablet based on *screen sized* is also unreliable, and if it's incorrect users can just change the UI scale themselves.

**Comment by rocboronat** [comment]
@Anuken I almost have it. And well, taking in account the display size to say a device is a tablet or not is the standard in the Android app industry.

Your approach fails with tablets that have phone connectivity that are treated as phones, and phones big enough to be considered tablets that are using the small scale.

Tell me if you want to have that PR opened please 😊

**Comment by Anuken** [comment]
> taking in account the display size to say a device is a tablet or not is the standard in the Android app industry.

In this case, whether or not the device is a tablet shouldn't really matter - ideally, `Core.graphics.getDensity()` should return the right scaling factor based on device screen size and density. 

If you have a specific case where the scaling is wildly incorrect, you could submit a PR - but at the same time, it's been working (mostly) fine for a very long time now, and I don't have the capability to test your changes - I don't have a tablet or working emulator anymore, and I haven't tested that code for a very long time now.

It's also worth noting that much of the existing playerbase will likely have adjusted their UI scale setting to best fit their device, and with this scale being dependent upon the *baseline* scale, any significant change in the baseline scale may brick the game for them. I'm not sure that this change would be worth it.

**Comment by rocboronat** [comment]
Well, honestly, I didn't look outside the method `isTablet()`. Just found a method that didn't do what it claimed and went to fix it.

If you can't test it and don't rely on collaborators, it's fine. Thanks for taking the time to answer this issue.

Great game, by the way! Congratulations on it! 👏
