### ISSUE TITLE
strange lines on orange metal tiles on android 11

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry#4711]
**Platform**: *Android/iOS/Mac/Windows/Linux*
s20fe exynos on android 11 (might be important, i honestly don't know)
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
125
**Issue**: *Explain your issue in detail.*

![](https://cdn.discordapp.com/attachments/748526684512321579/811552773710938142/unknown.jpeg)
I've only seen it on the orange floor.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
place orange floor
look

**Save file**: 
[bug.zip](https://github.com/Anuken/Mindustry/files/5995129/bug.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
(I can see evidence of it on the sand tiles, so.)

**Comment by BlueWolf3682** [comment]
i cannot reproduce on my phone, which is running android 11 ( google pixel 2)
![Screenshot_20210217-042613](https://user-images.githubusercontent.com/61173114/108198237-9f223c80-70d8-11eb-9809-b60a2b4cf580.png)

**Comment by Catchears** [comment]
Do you have linear filtering enabled? I can only see it while it's on.

**Comment by LeoSko** [comment]
> i cannot reproduce on my phone, which is running android 11 ( google pixel 2)
@BlueWolf3682 

I can clearly see tiles are shifted 1 pixel here and there on your screenshot.

**Comment by BlueWolf3682** [comment]
thats due to how the sprites are drawn. 

linear filtering is enabled in that screenshot.

**Comment by Catchears** [comment]
(I don't really understand graphics stuff, just thought I'd report the bug)

**Comment by Anuken** [comment]
Disable linear filtering.
