### ISSUE TITLE
health/shield rendered negative value (?) when killed by foreshadow in v125

### ISSUE THREAD

**Issue by mayli** [Anuken/Mindustry#4716]
**Platform**: Android/Windows

**Build**: v125

**Issue**: health/shield rendered negative value (?) when killed by foreshadow

**Steps to reproduce**: get killed by foreshadow

**Link(s) to mod(s) used**: no mod

https://user-images.githubusercontent.com/822628/108273049-ee438e00-7127-11eb-9f47-7eb237811ecd.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
