### ISSUE TITLE
Game closes at startup

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#4721]
**Platform**: 

Windows 10

**Build**: 

125

**Issue**: 

The game closes at startup.

**Steps to reproduce**:

Run the jar downloaded from the releases

**Link(s) to mod(s) used**:

no mods

**Save file**:

none

**(Crash) logs**: 

there is no crash and no crash log. here is my last_log
[last_log.txt](https://github.com/Anuken/Mindustry/files/6001502/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
please replace the italic parts with the answers instead of replying below it

**Comment by Anuken** [comment]
Cannot reproduce, works fine for me.
