### ISSUE TITLE
Java or js mods not working

### ISSUE THREAD

**Issue by DrPeeper228** [Anuken/Mindustry#4722]
**Platform**: `Android 28`

**Build**: `release build 125`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
In up
**Link(s) to mod(s) used**: `[Devs: K103908, BlueWolf, MEEP Of Faith, AndromedaFallen
Contributors: Quezler, VozDuh/exotic-mod:0.03 Alpha, DeltaNedas, Router and another guy/pictologic:1.5.7, DeltaNedas/ui-lib:2.16.6, DeltaNedas/unit-factory:2.4.2, Dr.Peeper/unit-update:0.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [√] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ✓] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
bruh

**Comment by DrPeeper228** [comment]
> bruh

What?

**Comment by ILiekMelons** [comment]
> > bruh
> 
> What?

bruh

**Comment by Anuken** [comment]
> Explain your issue in detail.

Ah yes, an incredible amount of detail.
