### ISSUE TITLE
Game doesn't run on `musl` libc distros

### ISSUE THREAD

**Issue by violetastcs** [Anuken/Mindustry#4731]
**Platform**: *Linux*

**Build**: *Specific version unknown, though was on git commit `d5448b59a2bb91e7d749931cc8f031516fa981bd`*

**Issue**: *Due to how Arc is packaged, and I would presume potentially other libraries used, the game cannot be run on Linux distros that use alternative libcs to glibc.*

**Steps to reproduce**: *Clone game and run `gradlew desktop:run` on a distro that uses musl libc*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
nice logs you posted that were not required at all

use gnu/linux

**Comment by Anuken** [comment]
This is the first time I've hearing of the existence of such distros. If you're interested in fixing this, submit a PR to Arc.

**Comment by violetastcs** [comment]
> This is the first time I've hearing of the existence of such distros. If you're interested in fixing this, submit a PR to Arc.

I'll look into it

**Comment by violetastcs** [comment]
> nice logs you posted that were not required at all
> 
> use gnu/linux

I didn't post logs because the issue is somewhat self explanatory, and I'd prefer to have a choice in the software I use and still be able to pick and choose with games, I shouldn't have to be locked into GNU/Linux in order to play Mindustry while I can run Steam perfectly fine.

 I do intend to see if I can fix this myself.

**Comment by Jackojc** [comment]
@DeltaNedas That was just super unhelpful.

**Comment by DeltaNedas** [comment]
so was not posting any logs whatsoever

**Comment by violetastcs** [comment]
@DeltaNedas logs where not needed for the issue, as it is abundandly clear what the issue is; binaries that link with Glibc without alternatives for Musl.

**Comment by Anuken** [comment]
@DeltaNedas Please go away - if I have a need for additional logs or there's missing information, I'll ask for it. There's no need to make up problems on my behalf.
