### ISSUE TITLE
EMFILE issue on iOS 

### ISSUE THREAD

**Issue by Sanya2907** [Anuken/Mindustry#4733]
**Platform**: *Android/iOS/Mac/Windows/Linux*
iOS
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 
Build 125
**Issue**: *Explain your issue in detail.*
Can’t export anything from settings, crash reports, saves.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Settings > game data > export (anything), this issue happens.
![EF0D8F0A-E533-484B-AFCD-2BD339757BA9](https://user-images.githubusercontent.com/57323951/108515400-140e9580-72d6-11eb-98ab-8f23c7c29410.png)
![DBD9B2B6-8A6C-4A1B-98F6-49E12BE474F3](https://user-images.githubusercontent.com/57323951/108515408-1670ef80-72d6-11eb-8d37-a081d4a02c0e.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
No need.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
Doesn’t matter
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
have you tried turning it off and on again?

**Comment by Anuken** [comment]
Cannot reproduce on my (iPhone 8) device or find any other information about this issue. This cannot even be debugged without access to the game data, which you cannot export in the first place. Possible solution: Delete some maps/saves, or restart your device.
