### ISSUE TITLE
gradlew builds and prebuild jars fail on FreeBSD

### ISSUE THREAD

**Issue by jake-87** [Anuken/Mindustry#4740]
**Platform**: *FreeBSD*

**Build**: *6_125.1 and the source code for the beta i guess for 6_126.2*

**Issue**: *When running the prebuild jar, it fails with a java NullPointerExeption, and when compiling from source, it fails when running :tools:pack*

**Steps to reproduce**: *Install FreeBSD 12.2, upgrade from source to 14-CURRENT, install openjdk14, download source code or 6_125 prebuild, either run ./gradlew desktop:dist or ./gradlew desktop:run (They fail at the same points) or run java -jar Mindustry.jar*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *
[faillog-source.txt](https://github.com/Anuken/Mindustry/files/6014186/faillog-source.txt)
[faillog-prebuilt.txt](https://github.com/Anuken/Mindustry/files/6014187/faillog-prebuilt.txt)

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by jake-87** [comment]
After a bit of digging, it appears the error occurs on line 347 of this function?
```
345         //run generation task; generate all needed sprites
346         file(genFolder).mkdirs()
347         javaexec{
348             main = "mindustry.tools.ImagePacker"
349             classpath = sourceSets.main.runtimeClasspath
350             workingDir = genFolder
351         }
``` in tools/build.gradle

**Comment by jake-87** [comment]
It looks to me like the JVM cannot find the name "javaexec", but i don't have that much java knowledge, so don't assume i'm correct. I do not know if a `UnsatifiedLinkError` would be thrown for the function name, or if it would be thrown within the function, with the link error line being set as the function definition (Assuming this is the java equivalent of a function)

**Comment by jake-87** [comment]
I managed to get desktop:dist to throw a different error:
```
/home/freebsd/coding/building-from-src/Mindustry/desktop/src/mindustry/desktop/steam/SStats.java:181: error: pattern matching in instanceof is a preview feature and is disabled by default.
            if(e.unit instanceof BlockUnitc block && block.tile().block == Blocks.router){
                                            ^
  (use --enable-preview to enable pattern matching in instanceof)
1 error
```
How would i enable this? I have tried to throw in as an argument into gradlew, but that doesnt work, and I cant find what calls this java instance.

**Comment by jake-87** [comment]
So, to sum up at this point: 
Prebuilt binarys fail with a null pointer exeption;
gradlew desktop:run fails with an unsatified link error while building desktop:compileJava
gradlew desktop:dist fails with a unsatified link error while building :tools:pack

**Comment by jake-87** [comment]
I think if I could pass --enable-preview to SStats.java, it would run, but I cant figure that out, as i cannot figure out where SStats is run from.

**Comment by jake-87** [comment]
Now everything is back to failling at a Unsatified Link Error in `ImagePacker.main`, in this line of code:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.nio.ByteBuffer arc.graphics.Pixmap.load(long[], byte[], int, int)'`

**Comment by jake-87** [comment]
Full log of `./gradlew desktop:run --args="--enable-preview"` :
[faillog-stdout.txt](https://github.com/Anuken/Mindustry/files/6014542/faillog-stdout.txt)
[faillog-stderr.txt](https://github.com/Anuken/Mindustry/files/6014543/faillog-stderr.txt)

**Comment by jake-87** [comment]
Looks to me like it's back to tools/build.gradle not being able to find `mindustry.tools.ImagePacker`. Honestly not sure how to procede, seeing as I cannot find that file myself.

**Comment by liuxilu** [comment]
Funny to thumbs down on every comment.

**Comment by jake-87** [comment]
i disliked a troll bug report, i thinks they must have disliked this chain in return.

**Comment by Anuken** [comment]
FreeBSD isn't detected as a supported OS, which causes it to fail loading native libraries. I've added some extra code to OS detection so FreeBSD is treated as Linux (as of 2df2a0971ad7b222d1b95e537f3bc343ce67e24f), but I have no idea if that will work for you. If it doesn't, submit a PR.

Note that only the `amd64` architecture is supported for Linux. There are no natives for `i386`.
