### ISSUE TITLE
I can believe, i just can made i... WHAT

### ISSUE THREAD

**Issue by DrPeeper228** [Anuken/Mindustry#4752]
**Platform**: `Android 28`

**Build**: `bleeding-edge build 20799`

**Issue**: *Explain your issue in detail.*
Watch: https://drive.google.com/file/d/1ZXUKIRJO2SN19nsC_Uvt53zzM_zt-8BL/view?usp=drivesdk
Save: https://drive.google.com/file/d/1Z_lotb8n6frMZP_pvmmiRqWLJv3774Dp/view?usp=drivesdk

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[Devs: K103908, BlueWolf, MEEP Of Faith, AndromedaFallen
Contributors: Quezler, VozDuh/exotic-mod:0.05 Alpha, DeltaNedas/ui-lib:2.16.6, DeltaNedas/unit-factory:2.4.2, Dr.Peeper/unit-update:0.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Please send the screenshot as a PNG file directly here, and the save file as a zip directly here. We cannot access your google drive.

**Comment by DeltaNedas** [comment]
https://streamable.com

**Comment by Anuken** [comment]
No description of what's happening or why it's a bug.
