### ISSUE TITLE
logic ItemDrop to incinerator doesn't work

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#4760]
**Platform**: Windows 10
**Build**:      125.1
**Issue**:  
units refuse to itemdrop to an incinerator
(if this isn't a bug, can we get a surefire way to clear a units items, plzthx)

**Steps to reproduce**:
1) Put below code (also in map file) in processor, connect it to an incinerator, build flares
set out incinerator1
sensor x out @x
sensor y out @y
ubind @flare
ucontrol move x y 0 0 0
ucontrol itemDrop out 100 0 0 0
2) Unit moves to position but doesn't lose items

**Link(s) to mod(s) used**: cliff, l-debugger, rftm

**Save file**:  [test_map.zip](https://github.com/Anuken/Mindustry/files/6027360/test_map.zip)

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This has nothing to do with logic - incinerators don't accept items from units. This is because incinerators don't have storage.

> can we get a surefire way to clear a units items

Drop items into the core.
