### ISSUE TITLE
Router inputs are not balanced

### ISSUE THREAD

**Issue by red-led** [Anuken/Mindustry#4764]
**Platform**: *Linux*

**Build**: steam build 125.1

**Issue**: 
Router (and distributer) inputs are not balanced.
I'm not shure if it's a bug or intended behaviour. But it's certainly annoying. 

**Steps to reproduce**:
![mind_1](https://user-images.githubusercontent.com/1540305/108821694-0d7e6780-75cf-11eb-9097-0551bfd9f98a.gif)

It leads to jams in more realistic setups like this:
![mind_2](https://user-images.githubusercontent.com/1540305/108821783-30a91700-75cf-11eb-92a7-740bf8f98d65.gif)

I was expecting to behave it more like in this setup:
![mind_3](https://user-images.githubusercontent.com/1540305/108822641-6995bb80-75d0-11eb-991a-ed6303b9e7c8.gif)

**Link(s) to mod(s) used**: *none*

**Save file**: [test_mind.msav.zip](https://github.com/Anuken/Mindustry/files/6027820/test_mind.msav.zip)

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stuffyAI** [comment]
I guess it is not precisely mentioned that there are actually straight-line priorities for such blocks, but I believe this is intended.
In realistic-realistic setups it shouldn't matter since you wouldn't route multiple resources over one, and in case you actually use logic to minmax such thing you would simply have to do it like in your 3rd gif

**Comment by red-led** [comment]
> there are actually straight-line priorities for such blocks

I's a luck, that middle lane is working on first gif. It can switch to any lane:
![mind_4](https://user-images.githubusercontent.com/1540305/108825860-9946c280-75d4-11eb-8e23-982f04d678b8.gif)

**Comment by GreyMario** [comment]
There are no "priorities" of any sort for distribution and flow-control blocks. When multiple lines meet, it's a crapshoot which one gets the priority transfer, and sometimes it lets another item through anyway.

> more realistic setups

You should never be mixing belts. That's as unrealistic as it gets.

**Comment by Anuken** [comment]
Merging priority is undefined, and will always be.
