### ISSUE TITLE
Copper conveyors have speed like titanium

### ISSUE THREAD

**Issue by yharonsoup** [Anuken/Mindustry#4765]
**Platform**: *Windows*

**Build**: *125.1*

**Issue**: *Copper conveyors have speed like titanium.*

**Steps to reproduce**: *I just was test conveyor autoreplacing. First I just make curvy titanium conveyor and then I replaced it*

**Link(s) to mod(s) used**: *I wasn't using mods*

**Save file**: [file](https://drive.google.com/file/d/1hVhRc39c9EaU4-inNc58qJGkSW9Y8-Z9/view?usp=sharing)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/108864078-d9e81100-75bf-11eb-91af-c530d6b1f698.png)

really?

**Comment by yharonsoup** [comment]
Im stupid
Sorry
