### ISSUE TITLE
Sector 243 places core on deep water

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry#4766]
**Platform**: Android

**Build**: 125.1

**Issue**: Sector 243 places the core on deep water, making it impossible to place conveyors next to the core.

**Steps to reproduce**:
1. Launch to 243

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: N/A
 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
This is one where your save file would be very useful.

**Comment by MEEPofFaith** [comment]
Wet core wet core
