### ISSUE TITLE
Possible stroke tool inaccuracy

### ISSUE THREAD

**Issue by Sky4ce09** [Anuken/Mindustry#4770]
**Platform**: *Windows*

**Build**: *125.1*

**Issue**: *Not that much to explain here; while trying to draw a diagonal stroke the observation was made that if the stroke is angled 45+n*90 degrees and it is 2 tiles long it'll produce inaccurately placed tiles

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1) go to the map editor
2) attempt drawing a diagonal stroke that is two tiles long
3) see the results
if they match up with the results in the video below then it'll be a successful reproduction

https://user-images.githubusercontent.com/44333723/108910351-03d41e80-7626-11eb-82f9-f6ee1a86bfa6.mp4

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Only possibly relevant mod: deltanedas/ui-lib. Highly doubtful about the mod being involved in this, though.

**Save file**: *Editor issue.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
Does not cause crashes.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
