### ISSUE TITLE
bridges pointing down don't link when rotated

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4772]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20812`

**Issue**: if you have a bridge pointing down in a schematic and rotate it (or not) in any way it doesn't link.

**Steps to reproduce**: 

- place a bridge block
- place another bridge block below it
- make a schematic of it
- paste it in any of the 4 axis
- notice none of them linking as intended

![Screen Shot 2021-02-24 at 11 21 51](https://user-images.githubusercontent.com/3179271/108986823-da051100-7692-11eb-814a-44dac01d16c0.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
right to left also seems affected

**Comment by joshuaptfan** [comment]
Doing a quick test on BE 20812, it is only the left-to-right facing bridge that doesn't link when rotated.

![Bridge bug](https://user-images.githubusercontent.com/15149002/109016048-9eeee780-766a-11eb-933b-a962ced34675.png)
