### ISSUE TITLE
No create units

### ISSUE THREAD

**Issue by DrPeeper228** [Anuken/Mindustry#4773]
**Platform**: *Android 28

**Build**: release 125.1

**Issue**: *Explain your issue in detail.*
Watch: https://drive.google.com/file/d/1aNHu6rAGrlBwcmJGCZFTDzsqILV20-Xo/view?usp=drivesdk

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Watch: https://drive.google.com/file/d/1aNHu6rAGrlBwcmJGCZFTDzsqILV20-Xo/view?usp=drivesdk

**Link(s) to mod(s) used**: не помню

**https://drive.google.com/file/d/1aOgcjVT-LY0lgGKxrKNrXwA7AX_u2dE4/view?usp=drivesdk**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
have you not realised why anuke closed any of your previous issues

**Comment by Quezler** [comment]
but it **is** creating units?

**Comment by GreyMario** [comment]
Bot that auto-closes issues when a Google Drive link is detected when

PEBKAC isn't a bug, either.

**Comment by DrPeeper228** [comment]
> have you not realised why anuke closed any of your previous issues

No

**Comment by joshuaptfan** [comment]
You need to actually explain your problem, using full sentences.

And upload files by zipping (compressing) them, then drag and drop directly into the issue where you're typing to upload them directly to GitHub. Don't use Google Drive.

**Comment by Erisfiregamer1** [comment]
android 28 isnt even a damn android os the latest ALPHA is 12

**Comment by liuxilu** [comment]
Android 9.0, API Level 28
