### ISSUE TITLE
Deconstructing a breakable terrain block halfway and then rebuilding it takes control of the block

### ISSUE THREAD

**Issue by Cra1gTucker** [Anuken/Mindustry#4774]
**Platform**: `Windows 10 x64`

**Build**: `release build 125.1`

**Issue**: If you try to break a neutral block by pressing `mouse right` and stop before the block got completely removed, then press `mouse left` on that block to continue building, it will be successfully rebuilt and the controller of the block becomes you. **I've noticed that this is the expected behavior in Issue 3757.** But this even happened on breakable terrain blocks (snow boulders for example) though I can't finish rebuilding a terrain block, but it switched controller and acquired a health bar and took damage and got destroyed by the enemy. Is taking control of these blocks also expected behavior? Also I didn't test if polys will try to rebuild terrain blocks taken this way and destroyed.

**Steps to reproduce**: For terrain blocks you can't rebuild, you can try to deconstruct and rebuild it and it will become yours but you won't be able to make it return to its original state. After this it will be considered your block, it will be targeted by enemy and it has finite health. This could be the expected behavior though, I just thought that it might be somewhat strange. You should be able to see some buggy snow boulders in Impact 0078 of the attached save file.

**Link(s) to mod(s) used**: `none`

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/6035806/saves.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GreyMario** [comment]
Didn't... Didn't we change it so that deconstructable decorations deconstruct instantly..?

**Comment by Cra1gTucker** [comment]
If you build something over the decorations it will be deconstructed instantly. But if you only do deconstruct on the decoration and act fast, the deconstruction can be stopped halfway.
See this screenshot.
![screenshot](https://user-images.githubusercontent.com/44919935/109000257-6d176880-76de-11eb-969c-37f20116b9e6.PNG)

**Comment by Anuken** [comment]
This isn't a bug.
