### ISSUE TITLE
Cultivator shallow water bonus

### ISSUE THREAD

**Issue by Willzile1** [Anuken/Mindustry#4779]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Build 125.1
**Issue**: *Explain your issue in detail.*
When a cultivator is placed on shallow water with dark sand it gets a 10% bonus. Doesn't work with other shallow water types
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Place a cultivator on shallow water with dark sand 
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[Mindustry save.zip](https://github.com/Anuken/Mindustry/files/6038525/Mindustry.save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
No crash but have them anyway
[Mindustry crash logs.txt](https://github.com/Anuken/Mindustry/files/6038528/Mindustry.crash.logs.txt)

If more information is needed my discord is Willzile1#1191, E-Mail is Willzile1@gmail.com
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Only works on tainted water. This is not a bug.
