### ISSUE TITLE
Scatter Bullet and Air Unit HP Glitch

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry#4780]
**Platform**: `Android 7.1.1`

**Build**: `Release build 125.1`

**Issue**: *Scatter + Metaglass shot is not killing air units which flies by. When the unit got hit by bullets, the HP bar decreased, but when the unit stopped moving, the HP bar fills up again. I haven't checked with other unit/bullet/turret types yet.*
![Screenshot_2021-02-25-02-55-34-142_io anuke mindustry](https://user-images.githubusercontent.com/26910478/109058744-f39b6c80-7715-11eb-9382-c318f9f1bf69.jpg)

**Steps to reproduce**: *Just fly by over scatter turrets and got hit by some bullets, then stop on somewhere safe.*

**Link(s) to mod(s) used**: `None`

**Save file**: `None`

**Crash report**: `None`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Save file: None

Template:

> **THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.**
