### ISSUE TITLE
Cant join local hosted games on mobile

### ISSUE THREAD

**Issue by snakefangz** [Anuken/Mindustry#4783]
samsung galaxy s9 Android

125.1

I cant join local games my friends host, but they can join me when i do, they are on pc, this didnt occur before 125.1

**

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
125.1 did not change anything related to network discovery. Your network is misconfigured.

**Comment by snakefangz** [comment]
> 125.1 did not change anything related to network discovery. Your network is misconfigured.

I never said that the update contained network changes, i might have worded it wrong, its not that i cant join their games, i cant FIND them, it has to be some sort of bug on mobile.

**Comment by liuxilu** [comment]
> 125.1 did not change anything related to 
## network
# discovery
Your network is misconfigured.
