### ISSUE TITLE
Visual Bug: Repair Point

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry#4784]
**Platform**: iOS

**Build**: 125.1

**Issue**: Repair Points offscreen healing units onscreen do not have their lazar/beam that indicates they are being healed. 

**Steps to reproduce**: Spawn unit. Heal unit. Get Repair Point offscreen...

**Link(s) to mod(s) used**: None active at the moment

**Save file**: [save-T35t1nG m4p B3C4U53 wHy NoT Feb 24 10:13.zip](https://github.com/Anuken/Mindustry/files/6040332/save-T35t1nG.m4p.B3C4U53.wHy.NoT.Feb.24.10.13.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
someone should just pr `expanded = true` in the constructor of `RepairPoint.java`, im currently using the github mobile app so i can't do it myself 🙃
