### ISSUE TITLE
Units forget their logic orders when the game is restarted.

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry#4785]
**Platform**: *Windows*

**Build**: *125.1*

**Issue**: *When you save and reload the game, the units stop following their orders given to them by logic.*

**Steps to reproduce**: *Spawn 20 units, then place a micro processor that gives them an order. Save & reload and you'll witness how they forgot their order and started following their default AI instead until the processor regains control.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
Please attach a save file.

**Comment by catsz** [comment]
a while ago the unit flag got reset for me each time I went in and out of a sector although that might be fixed

**Comment by Nester23** [comment]
> Please attach a save file if you want this bug to be properly addressed instead of just closed for not fulfilling the reporting requirements.

This issue takes a micro processor with two instructions to reproduce, is a world save file that necessary?

**Comment by joshuaptfan** [comment]
I have experienced this bug myself, and I attempted to reproduce it using simpler logic to narrow down the cause, and I was not able to reproduce.

So yes.

**Comment by Nester23** [comment]
```
ubind @flare
ucontrol approach @thisx @thisy 6 0 0
```
Here.

**Comment by Nester23** [comment]
Hmm.. It appears to be too short, the processor catches them too quickly for this issue to become very evident. Place a rally point, so the flares would try to fly away to it when the default AI is on, then here's an artificially slowed down code:
```
ubind @flare
ucontrol approach @thisx @thisy 6 0 0
op add waitUntil @time 400
jump 3 lessThan @time waitUntil
```

**Comment by Anuken** [comment]
Not a bug. Units do not save logic orders.
