### ISSUE TITLE
Объекты на карте 

### ISSUE THREAD

**Issue by Dxstreed** [Anuken/Mindustry#4786]
На карте есть объекты, не принадлежащие врагам, каким образом их присвоить себе?

**Comment by Qvertyes** [comment]
Начни разбирать, а затем восстанови. И да, это тема с багами, а не вопросами.

**Comment by Dioo0** [comment]
> Начни разбирать, а затем восстанови

разве это работает?

**Comment by TheMrAlbert** [comment]
Please report bugs using English and do not ignore the template.

**Comment by GreyMario** [comment]
> There are objects on the map that do not belong to the enemies, how do you assign them to yourself?

This isn't even a bug. Can't you go ask basic gameplay questions in the Mindustry Discord?
