### ISSUE TITLE
Mechanism images problem

### ISSUE THREAD

**Issue by XNoireCode** [Anuken/Mindustry#4789]
**Platform**: *PC/Windows*

**Build**: Steam Build 125.1*

**Issue**: *When i done 1st stage i collected items for next one, after i travelled to the next zone all mechanisms (player drone too) just gone, but i was able to see their status | sometimes this bug gones after i join game multiple times *

**Steps to reproduce**: *I did 1st stage, then moved to the next, all mechanism images gone*

**Link(s) to mod(s) used**: *https://steamcommunity.com/sharedfiles/filedetails/?id=2406760691*

**Save file**: *https://steamcommunity.com/sharedfiles/filedetails/?id=2406760691 THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *No crash reports*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce, no save file attached.
