### ISSUE TITLE
Auto bridge doesn't respect conveyor rotation

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4791]
**Platform**: Windows

**Build**: BE build 20820

**Issue**: The newly added auto bridge doesn't rotate the bridge links when the conveyor is rotated with the scroll wheel.

**Steps to reproduce**: Just try placing a conveyor and rotating it, the bridges will link backwards: https://aethex.is-a.fail/Dw8vEZ.webm

**Link(s) to mod(s) used**: NA

**Save file**: [338.zip](https://github.com/Anuken/Mindustry/files/6046280/338.zip)

**(Crash) logs**: NA

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The bridges are not supposed to rotate with conveyors.

**Comment by buthed010203** [comment]
🤔 they dont face the same way as the conveyors though

**Comment by Anuken** [comment]
Because you rotated the conveyors after they were dragged.

**Comment by buthed010203** [comment]
> Because you rotated the conveyors after they were dragged.

@Anuken one would think that they would rotate with conveyors while dragging though..

**Comment by Anuken** [comment]
I don't.
