### ISSUE TITLE
Cursed bridges

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4792]
**Platform**: Windows

**Build**: BE build 20820

**Issue**: I dont even know how to explain this

**Steps to reproduce**: Just hold ctrl and move the cursor around... https://yagpdb.is-ne.at/cg5uTs.webm

**Link(s) to mod(s) used**: NA

**Save file**: [338.zip](https://github.com/Anuken/Mindustry/files/6046280/338.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by kapzduke** [comment]
wow, do you realize the potential it would have
