### ISSUE TITLE
Can't read directories Linux Mint

### ISSUE THREAD

**Issue by LuanHimmlisch** [Anuken/Mindustry#4793]
I've been enjoying the new campaign but I found a bug. When I try to import schematics it seems Mindustry can't read the directories even when is running with root level permissions. This also happens when I try to use mods that import files  like PicToLogic.

I'm using the flatpak version from the software center on a **Linux Mint 20.1 Ulyssa**.

![imagen](https://user-images.githubusercontent.com/46875694/109249868-27c26c00-77ae-11eb-8736-fb2254334070.png)

**Comment by BlueWolf3682** [comment]
how the hell do you people open issues without a bug tag

**Comment by Anuken** [comment]
This is an issue with flatpak, not Mindustry. I don't maintain that version.
