### ISSUE TITLE
Attack Sectors Locked

### ISSUE THREAD

**Issue by bl0ckchat** [Anuken/Mindustry#4795]
**Platform**: Windows

**Build**: 125.1

**Issue**: every attack sector is locked (with lock, not just red.  can't select it), even next to unnamed sectors

**Steps to reproduce**: None

**Save file**: 
[-1.msav-backup.zip](https://github.com/Anuken/Mindustry/files/6049832/-1.msav-backup.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Research campaign sectors. You can't see them until you meet the requirements.

**Comment by bl0ckchat** [comment]
oh i didnt notice, sorry
