### ISSUE TITLE
Mindustry server - plugin error - java.lang.ClassNotFoundExeption:

### ISSUE THREAD

**Issue by Susideur** [Anuken/Mindustry#4796]
**Platform**: Windows

**Build**: v125.1

**Issue**: When I run my server with plugins, this error occurs, like a class is missing, then the plugin does not load 

**Steps to reproduce**: I just turned on the server and while loading plugins this error occurs

**Link(s) to mod(s) used**: admin-tools , exampleplugin

**Save file**: 
[mindustry Server.zip](https://github.com/Anuken/Mindustry/files/6050369/mindustry.Server.zip)

(Translate by Google Translate)
![error_Java ClassNotFoundException](https://user-images.githubusercontent.com/56844734/109313194-3c534280-7848-11eb-90c6-e758442f9b08.png)
![error_Java ClassNotFoundException - 2](https://user-images.githubusercontent.com/56844734/109313216-41b08d00-7848-11eb-8707-764a706603a4.png)

**Comment by Anuken** [comment]
The plugin is outdated.
