### ISSUE TITLE
Block Interface bug

### ISSUE THREAD

**Issue by Susideur** [Anuken/Mindustry#4797]
**Platform**: Windows

**Build**: v125.1

**Issue**: When a unit is controlled by a processor, the blocks interface bug a bit. This bug occurs in all platforms and all types of units, on the French version of the game. 

**Steps to reproduce**: Just by controlling a unit by a processor

(Translate by Google Translate)
![interface not bug](https://user-images.githubusercontent.com/56844734/109317687-3f9cfd00-784d-11eb-9f10-bce8c5da14a5.png)
![interface bug](https://user-images.githubusercontent.com/56844734/109317707-4592de00-784d-11eb-96dd-f3b052dc0d12.png)

**Comment by Anuken** [comment]
The 'processor controlled' text is too long in French - it should be shortened in the translation bundle.
