### ISSUE TITLE
Logic fails to reliably configure item sources

### ISSUE THREAD

**Issue by polymeshop** [Anuken/Mindustry#4805]
**Platform**: Linux

**Build**:  125.1

**Issue**: Logic fails to reliably configure item sources

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

I wrote some mlogic code to configure item sources that are placed next to core, but ```control configure``` fails to properly configure item sources most of the time. The code in the processor should in theory configure all linked item sources to the same items, but that's not what happens in-game.

**Link(s) to mod(s) used**: No mods.

**Save file**: *The (zipped) save file you were playing on when the bug happened. 
[0.zip](https://github.com/Anuken/Mindustry/files/6053923/0.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by liuxilu** [comment]
The code's too long, please provide a minimized code.

**Comment by DeltaNedas** [comment]
`control configure source1 @sand` doesnt work?

**Comment by liuxilu** [comment]
`@sand` doesn't appear in the code.

**Comment by Anuken** [comment]
Configuration control has cooldowns to prevent packet spam.
