### ISSUE TITLE
Spawning when opening a new zone from a long time ago. Behavior of enemy units.

### ISSUE THREAD

**Issue by nodevlfrb** [Anuken/Mindustry#4806]
**Platform**: Windows 10
**Build**: 6.0 Build 125.1

**Issue**: When I spawned in a new zone after opening Mindustry from a long time (even though I updated it when build 125.1 went public), I didn't built anything before. But when I arrived, the camera, instead of following the core animation landing, spawned my ship near to the enemy spawn point. What was _bizarre_ was that I spawned with other enemy units, at the same place. One of them was in low health. And even more _bizarre_ they were ground units, more precisely Pulsars. They were all flying, and they didn't interact at all with me, not even shot at me. They couldn't fly to attack my core, and they were just here hanging out. Is it an AI problem?

Other major problem, as you can see, when I updated to 125.1, all my tech tree progress was erased, but not the maps and zones. I think it's rather an **important problem** to lose _all_ progression on tech tree but **not on the planet**...
**Steps to reproduce**: Open zone 170, at wave 1; there is as I seen 5 pulsars spawning. I think that it is impossible to recreate because they were flying out of the map.

**Link(s) to mod(s) used**: No mods were used at this time.

**Save file**: How do I save the map of a Campaign map on a file? Sorry, but I have a screenshot instead if it can help you.
![image](https://user-images.githubusercontent.com/67834068/109383447-dbc71280-78e6-11eb-89a8-160b5ef630a6.png)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: It is not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save file, cannot reproduce.

**Comment by nodevlfrb** [comment]
[Bugalpha.zip](https://github.com/Anuken/Mindustry/files/6090017/Bugalpha.zip)

Here you have the file I just transferred from Mindustry. Tell me if you have further questions or requirements. @Anuken 
(I tag you to make sure that you see this reply even though the issue is closed)
