### ISSUE TITLE
Connecting block bug

### ISSUE THREAD

**Issue by Usser8** [Anuken/Mindustry#4809]
I found one bug related to connecting blocks with a processor, when I connect a block to a processor, sometimes block2, but I didn't have a previously selected block, please fix this bug!

**Comment by Anuken** [comment]
Template.

**Comment by Newguy-ish** [comment]
Also not really a bug

**Comment by Usser8** [comment]
Ok, sorry, i found how to to fix this, but thanks for the answer!

сб, 27 февр. 2021 г., 17:39 Newguy-ish <notifications@github.com>:

**Comment by Usser8** [comment]
Ok, sorry :(

сб, 27 февр. 2021 г., 17:39 Newguy-ish <notifications@github.com>:
