### ISSUE TITLE
Logic Block - Operation UI Bug

### ISSUE THREAD

**Issue by mangblekok** [Anuken/Mindustry#4812]
**Platform**: `Android 7.1.1`

**Build**: `release build 125.1`

**Issue**: *There's a bug on Logic UI for Operation menu, specifically the `max`, `min`, `angle`, `len`, `noise`*

**Steps to reproduce**:
*1) Build a Logic block and open the editor
2) Add Operation, then choose any of these 5 commands
3) While still in Operation, change to other command
4) Can be repeated indefinitely*
![Screenshot_2021-02-28-04-41-52-172_io anuke mindustry](https://user-images.githubusercontent.com/26910478/109401304-745da100-7980-11eb-94cc-a91624103f63.jpg)
![Screenshot_2021-02-28-04-42-08-068_io anuke mindustry](https://user-images.githubusercontent.com/26910478/109401313-80496300-7980-11eb-986b-fb342a421f31.jpg)
![Screenshot_2021-02-28-04-42-21-408_io anuke mindustry](https://user-images.githubusercontent.com/26910478/109401316-85a6ad80-7980-11eb-8ca6-bf40c317147e.jpg)

**Link(s) to mod(s) used**: `None`

**Save file**: *`None`*

**Crash report**: *`None`*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed.
