### ISSUE TITLE
server crash upon placing power consuming/producing/storing blocks

### ISSUE THREAD

**Issue by walksanatora** [Anuken/Mindustry#4824]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux Mint:server
(what ever quezler uses to host nydus)
**Build**:20836
**Issue**:placing anything which consumes/produces/stores power crashes the server
**Steps to reproduce**:
make a headless server
join the server
build something which consumes/stores/produces power (except power nodes and diodes)
server crash when finished
**Link(s) to mod(s) used**:none
**Save file**:
[no.msav.txt](https://github.com/Anuken/Mindustry/files/6059413/no.msav.txt)
**(Crash) logs**:
![crash](https://cdn.discordapp.com/attachments/663854113418641429/815821513763717151/unknown.png)

**Extra**:
quezler identified the problem line to be [here](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/power/PowerNode.java#L261)

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
another one i came across trying to make nydus habitable today:
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/power/PowerNode.java#L248
