### ISSUE TITLE
Unit cell not rendering while reconstructing

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4828]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20836`

**Issue**: Units show their team while on payload capable blocks, not not while the upgrade animation is playing:

![Screen Shot 2021-03-01 at 12 36 09](https://user-images.githubusercontent.com/3179271/109492368-2d100700-7a8b-11eb-9166-0fc46b4f171e.png)
![Screen Shot 2021-03-01 at 12 36 12](https://user-images.githubusercontent.com/3179271/109492370-2f726100-7a8b-11eb-9d58-1195be1ff68e.png)

**Steps to reproduce**: Use reconstructors while on a team with an obvious enough color to spot the difference.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Reproduced, release build 125.1

**Comment by Anuken** [comment]
Not a bug. It's not supposed to render.

**Comment by Quezler** [comment]
> Not a bug. It's not supposed to render.

what about this commit tho? https://github.com/Anuken/Mindustry/commit/76dbdb59ce879a72569e386a7178af0910e14ca5

**Comment by Anuken** [comment]
They're not unit payloads until the upgrade is finished. The unit is not "activated" until the upgrade is done.

**Comment by Quezler** [comment]
and the region can't simply be added between one of these 4 lines?

https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/units/Reconstructor.java#L145-L148

**Comment by Anuken** [comment]
Not really, because it would be drawn at partial transparency on top of another sprite with partial transparency, which would result in awkward blending and higher transparency at the cell region.
