### ISSUE TITLE
liquid tanks providing infinite throughput 

### ISSUE THREAD

**Issue by Sukhoi-s25-sunday** [Anuken/Mindustry#4832]
**Platform**: *All paltforms*

**Build**: *125.1.*

**Issue**: *Liquid tanks provide infinite flow rate should they act similar to a container or vault  .*

**Steps to reproduce**: *4 liquid tanks placed in tandem and liquid sources placed on the width and fill it to full the place a conduit on the other side to begin draining the tanks and there seems to be inf output*

**Link(s) to mod(s) used**: *None.*

**Save file**: *cannot  attach as of right now*

**(Crash) logs**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
not a bug really 🙄
