### ISSUE TITLE
Steam cloud bug

### ISSUE THREAD

**Issue by Qvertyes** [Anuken/Mindustry#4833]
Platform: Windows 10 x64`

Build: steam build 125.1`

Issue: Steam cloud trouble. I deleted all saved campaign progress and researches in game interface. After it, i started play campaign, but after reload all new progress has been deleted and old campaign saves replace to the game and all sectors were under attack.

https://media.discordapp.net/attachments/784768116886077460/815643811161047050/unknown.png?width=958&height=754 - screenshot
https://disk.yandex.ru/d/K9MFnW2iOjhppA - after steam cloud
https://disk.yandex.ru/d/Y_BjZkVlb6YJIw - old

New campaign lost and i think it not important.

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug with Mindustry.
