### ISSUE TITLE
saving never (seems to) goes away

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4845]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20848`

**Issue**: started noticing a few days ago that saving in my custom games tends to stay on screen indefinitely:
(also returns on screen instantly when you start a new game)

![Screen Shot 2021-03-03 at 16 30 47](https://user-images.githubusercontent.com/3179271/109829724-1827a500-7c3e-11eb-8ad6-addb1ef7a096.png)

**Steps to reproduce**: 
- start custom game in sandbox (e.g. molten lake)
- wait till saving appears (possibly with unfocus autopause off and actively busy on another window for a minute or so)
- notice it not going away

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Newguy-ish** [comment]
Template [ ] are there to be checked, you know?

**Comment by BlueWolf3682** [comment]
Reproduced, Windows 10 school computer does it too.

**Comment by Quezler** [comment]
> Template [ ] are there to be checked, you know?

well i haven't heard anuke complain about my checkboxes before 🙄 

besides, i am not on the "latest release" that is linked there, and no i have not searched through all the issues 😄

**Comment by Anuken** [comment]
Fixed.
