### ISSUE TITLE
powernode preview inaccurate

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4846]
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20849`

**Issue**: only a few connections preview when taking a schematic of this setup:

![Screen Shot 2021-03-03 at 18 31 33](https://user-images.githubusercontent.com/3179271/109847285-4cf02800-7c4f-11eb-94cb-ba48dcb0f2a5.png)

**Steps to reproduce**: place a large power node under this schematic, then try to replicate the screenshot above: `bXNjaAF4nCWM/QrCMAzEbx+WyQR9C//qQ8U2aCF2I4vo45tuJOQuuR/BhEuPsdKbMWUtIvVumDNvSctqZanAgPkhtFncc1y/ZKyRf6aUbFHchD41veJKOQrpkwGcgc6rNUYMTYI/8t2T3t3JLz66Q3Y8HGRo5B/mlhq+`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
try placing the power node first, and then the drills, that seems to matter apparently:

![Screen Shot 2021-03-03 at 18 49 57](https://user-images.githubusercontent.com/3179271/109849099-4498ec80-7c51-11eb-986c-1ccbc5242ab7.png)

**Comment by Quezler** [comment]
(aka it only previews connections if the connection was formed when the power node was placed, doesn't update)

**Comment by Anuken** [comment]
> try placing the power node first

Unless the connections are saved as one beforehand, potential connections to *planned blocks* are not supposed to be shown.

**Comment by Quezler** [comment]
for reference, fixed by: d73cf9fcff026a581b06c0aaab89a9c3231d3310
