### ISSUE TITLE
Are there classes needed to refactoring or testing part on this repo?

### ISSUE THREAD

**Issue by tucan9389** [Anuken/Mindustry#485]
I'm looking for the refactoring or testing part on this repo, and analyze the project now.
But if you already have any good parts for my first PR you think, please give me pieces of advice.

I want to contribute to this repo. 

Thank you.

**Comment by BasedUser** [comment]
The conveyor code is extremely unoptimized, you could give it a swing

**Comment by Anuken** [comment]
> The conveyor code is extremely unoptimized, you could give it a swing

Don't do that. Rewriting the entire conveyor system is not a good first PR.

---

I would suggest looking at the editor code [here](https://github.com/Anuken/Mindustry/tree/master/core/src/io/anuke/mindustry/editor) and seeing if there's anything to fix. Points of interest include the main dialog class, as well as the view and tool logic; all of these are rather messy.

**Comment by tucan9389** [comment]
@Anuken 
Awesome! I'll check the editor code out later. 😁

I have one more question. 
Are there any functions needed to test on this repo?
I think the testing part is somewhat small compared with the project scale. 
(If my guess is incorrect, please tell me.)

**Comment by Anuken** [comment]
> Are there any functions needed to test on this repo?

Not really. There's tests for launching the game and basic gameplay elements, but it's hard to design real tests when most things involve a GUI.

**Comment by tucan9389** [comment]
Thanks a lot.
