### ISSUE TITLE
The back and press sound effects are incredibly quiet.

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4852]
**Platform**: Windows

**Build**: 125.1

**Issue**: I noticed this a few months ago and its quite annoying, these two sounds are so quiet that I can still only barely hear them with my computer at max volume (which is 5x louder than I normally keep it). The menus are super quiet without these effects being audible and I assume that no one else reported this as they haven't realized that it is gone by accident

**Steps to reproduce**: I wondered if the sudden lack of sound in the menus was intentional, it's clearly not as the sound effect is still being played but its just so damn quiet that no one can hear it. Try clicking around the menus and see for yourself

**Save file**: This happens on the main menu but here are the two audio files [back.ogg](https://raw.githubusercontent.com/Anuken/Mindustry/master/core/assets/sounds/ui/back.ogg) [press.ogg](https://raw.githubusercontent.com/Anuken/Mindustry/master/core/assets/sounds/ui/press.ogg)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
take 1 of testing: game crashed

take 2 of testing: yes, they seem to be gone from the main menu

**Comment by buthed010203** [comment]
> take 1 of testing: game crashed 
> take 2 of testing: yes, they seem to be gone from the main menu

They aren't actually gone, they are still played but the sound files just have incredibly low volume

**Comment by Anuken** [comment]
They are supposed to be.

**Comment by buthed010203** [comment]
@Anuken So quiet that no one can even hear them? Why do they even exist then?

**Comment by Anuken** [comment]
I can hear them just fine, even when volume is adjusted with shooting sounds in mind. They're not supposed to be obvious. I don't see the problem.

**Comment by BlueWolf3682** [comment]
I literally cannot hear them on windows. That's the problem.
