### ISSUE TITLE
Through The Shadows

### ISSUE THREAD

**Issue by ROBLOX2ENTITY** [Anuken/Mindustry#4853]
**Platform**: `Android 4.4.4

**Build**: `release build 125.1`

**Issue**: `Okay, seriously i had to find out a bug that happens to EVERYONE and not only me, so i accidentally found one while having the thought, i knew that nobody knew about the bug since its been more than 3 months (yes i still checked the updates and cases), i first noticed this in the map called 'desert canyon' im pretty sure, the map wasn't made with walls placed around it like how most maps are made. So the enemies can just go through the shadowed area which is the edge of the map (without walls) if some player made walls are blocking them, i noticed you can block these shadowed areas in sandbox with 4×4 blocks but not in any other mode whatsoever. It seems in these kinds of maps, making walls are useless since you cannot place any in the shadowed area.`

**Steps to reproduce**: `Simply be lucky or unlucky enough to get a map that doesnt have walls around it COMPLETELY, and when you build walls and prepare for defenses the walls seems to be useless depending on how much of less "natural" walls there are around the map. Here in 'desert canyon' it seems that walls are not useful unless you want to make defenses that are staying really close to your base, which takes a lot of space. 

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> enemies can just go through the shadowed area which is the edge of the map (without walls)

Not a bug.

> Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

How did you not read this?
