### ISSUE TITLE
mindustry lacks libarcarm64

### ISSUE THREAD

**Issue by bvcbvc** [Anuken/Mindustry#4854]
**Platform**: linux, aarch64

**Build**: 125.1

**Issue**:it lacks libarcarm64.so
**Steps to reproduce**: attempt to run the jar file on aarch64

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**(Crash) logs**: it did not create a log text file, but i got an image of the console logs
![image](https://user-images.githubusercontent.com/42185819/110019541-351bb100-7cee-11eb-8a3b-57f770a3e1cd.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mindustry does not support ARM.

**Comment by bvcbvc** [comment]
is there any reason it dont support it?

**Comment by Anuken** [comment]
Compiling for ARM is tedious, very few people use it and I don't care to support it.

**Comment by bvcbvc** [comment]
good to know

**Comment by Stephen-Herobrine** [comment]
Then please just remove the aarch option in flathub

**Comment by Anuken** [comment]
I have no involvement in flathub, and do not maintain anything related to it.

**Comment by egfthomas** [comment]
> Mindustry does not support ARM.

It runs fine on my Galaxy Note 10 (snapdragon), but won't run on my arm64 laptop.  I was about to create an issue until I saw this.
