### ISSUE TITLE
Dos attack style bug in online multiplayer.

### ISSUE THREAD

**Issue by Spidroxide** [Anuken/Mindustry#4855]
Platform: affects all with access to online multiplayer, as far as I am aware.

Build: 125.1

Issue: a new DOS style bug has been discovered and players are able to effectively halt an entire server for a seemingly unlimited about of time. I imagine you already know about this bug, given the splash it is making on one of the most popular servers (.io), but I am reporting here just in case you don't know, and also to inform you of the rumours that I have heard from players. During the DOS attack, all activity on a server is essentially halted, with even chat messages taking minutes to go through, as ping steadily climbs up to several hundred thousand (highest I have seen was approximately 560000ms, although I dont know if ping is really a useful measurement once you reach numbers that high. It took about 20 minutes of continuous DOS attack to reach that point). Once the attack stops, ping will start falling at a rate of about 2000ms per second and server activity will only properly resume once this number falls back to below 1000. This affects all players as far as I am aware.

During the attack I have sometimes seen spam in chat. I do not know if this is a required part of the DOS since most of the time there is no visible spam, but when it does occur it is either a message from the DOS attacker to the players, or complex character spam made up of mostly Chinese and Japanese style symbols (I believe these are chosen to cause additional lag due to them being more complex than the western alphabet, but I couldn't say for sure). Either way whenever it appears, there is no name shown with the message, and the only other time I have seen this is when a player sends a message but disconnects or is lost before it is seen by other players (generally it happens during a map change, but also is exemplified during the dos itself when players send a message, then leaves, where it shows up minutes later due to the lag). This lends credence to what I have heard from players, who say that this bug is caused by a player repeatedly connecting and disconnecting from the server, because if they are connection cycling rapidly then most likely their messages will appear in chat long after they have left and relogged. Another alternative is that the connection is being performed by a "decoy" account that has no name, but I don't know nearly enough about the code or how the join system works to say whether this is actually possible.

Lastly what I have heard from players. According to people in the .io flood gamemode (a server that got hit hard by this DOS bug), you already know about this bug and have said it is unsolvable. They also said about how this bug is being performed via the use of an open source client that cannot, legally, be taken down. In short, they say we are stuck with this bug and that almost anyone can DOS attack a server since the client is easy to use. Now, I don't know how much of this is just rumours and Chinese whispers, since I couldn't find any discussions about this bug on either the reddit, discord, or github (bearing in mind I don't use the last two much so i could have easily missed something), but this is just the information I've heard from players, and only a small sample of said players. If this information is false and you aren't trying to keep this bug under the radar for as long as possible, then it might be wise to release an official statement about this bug (assuming you haven't already). The way I see it it is better to have players spreading the right information around rather than the wrong information, although I'm no game developer and I don't doubt that you're more experienced with handling this sort of situation than myself. Its just my opinion, as someone who has a lot of experience of vanilla multiplayer but knows nothing about the underlying mechanisms that run the game.

Steps to reproduce: join the .io attack or flood server after around 12:00pm GMT, which is when the DOSer seems to be most active. Alternately you could speak to the .io staff as I am sure they know more than me about this, so that might be a better source of information.

Mods: no mods used, at least none client-side. According to players the DOSers abusing this glitch are using a mod or custom client (not sure which) , but I have no knowledge of this.

Save file: Im not _exactly_ sure what files you want here, but here is the zipped saves folder from C:\Program Files (x86)\Steam\steamapps\common\Mindustry\saves
[saves (2).zip](https://github.com/Anuken/Mindustry/files/6086213/saves.2.zip)
. If this is not the right data then I can get you the right files, if you tell me what im looking for. 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Crash logs: Not applicable unless you count receiving timeouts when trying to connect to the server, during such an attack.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bvcbvc** [comment]
btw is ddos, dos

**Comment by Spidroxide** [comment]
Apologies, I always make this mistake. I can't get it out of my head that DDOS stands for "Digital Denial Of Service" rather than "Distributed Denial Of Service". Please mentally append as you see fit.

**Comment by BlueWolf3682** [comment]
I just checked, and it seems like this is happening right now. Both attack and the flood have 0 players and i cannot join them.

**Comment by Spidroxide** [comment]
Yes it is very frequent on those servers. The attacker is incessant and has been doing this for hours over a period of several days. They may have automated accounts doing the attacks, I couldn't say for sure. Either way I'm just trying to raise awareness of this, I know little about what is going on, although that is not to say i would be opposed to learning.

**Comment by Anuken** [comment]
This really doesn't sound like a bug/glitch in the game. Users repeatedly connecting, changing IDs and sending chat messages is not something that can reasonably be handled by Mindustry servers - packet spam like this should be handled by external programs or services.

**Comment by Spidroxide** [comment]
Regardless of whether this is a problem with mindustry, the servers plugins, or anything else, this seems, to me at least, to be a serious problem that is affecting and damaging multiplayer, regardless of where the problem truly lies. Considering the impact and damaging potential of the attacks, is it not worth giving it a little more attention?

**Comment by HelperGoslin67** [comment]
> This really doesn't sound like a bug/glitch in the game. Users repeatedly connecting, changing IDs and sending chat messages is not something that can reasonably be handled by Mindustry servers - packet spam like this should be handled by external programs or services.

Actually take a look and do some digging into this before you just dismiss it. It is your game, take pride in it.

**Comment by Anuken** [comment]
> Actually take a look and do some digging into this before you just dismiss it. It is your game, take pride in it.

I've seen the source code for the spambot, and my opinion hasn't changed - this is not something the game can should be dealing with it on its own. It may be possible to write plugins/tools that block IPs from connecting too quickly in certain scenarios, but the details of how that should be implemented should be discussed on Discord, not here.
