### ISSUE TITLE
Option for "Camera Follows Unit" or "Unit Follows Camera" for desktop

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#486]
What if there was an option that toggles the camera between following the unit like normal and the camera controlling the unit like in mobile? That would be useful for quickly glancing at a particular area in advance before a slow ground mech reaches it.

**Comment by Terrarch** [comment]
I know i just appeared out of nowhere, with no explanation, but i agree.
what if there could also be options to "glance at enemies" or "glance at enemy core"?

**Comment by Anuken** [comment]
Moved to "ideas" issue.
