### ISSUE TITLE
[JSON modding] Oil extractor won't accept attributes of shallow liquids

### ISSUE THREAD

**Issue by Austin5003** [Anuken/Mindustry#4866]
**Platform**: *Windows*

**Build**: *126*

**Issue**: *Despite attributes being correctly changed, the oil extractor still won't accept shallow liquids that have them.*

**Steps to reproduce**: *Add required attribute, try to place machine.*

**Link(s) to mod(s) used**: *github.com/Austin5003/mohole OR https://steamcommunity.com/sharedfiles/filedetails/?id=2311429012

**Save file**: 
[6.zip](https://github.com/Anuken/Mindustry/files/6093883/6.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Oil extractors and similar blocks do not work on any liquids.

**Comment by BlueWolf3682** [comment]
![Screenshot_20210305-144211](https://user-images.githubusercontent.com/61173114/110182900-f0197c80-7dca-11eb-9147-46ef9b91309a.png)
:eyes:

**Comment by Austin5003** [comment]
> 
> 
> ![Screenshot_20210305-144211](https://user-images.githubusercontent.com/61173114/110182900-f0197c80-7dca-11eb-9147-46ef9b91309a.png)
> 👀

It will work when touching that liquid, but that affinity won't be calculated for

**Comment by Austin5003** [comment]
Not sure about why this limitation is in place
