### ISSUE TITLE
tooltip "leak"

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#4867]
**Platform**: Debian GNU/Linux

**Build**: 124 :)

**Issue**:
When editing a text field, if it has a visible tooltip then the tooltip is "leaked", requiring a restart (probably) to go away.
![Screenshot_23:43:48](https://user-images.githubusercontent.com/39013340/110186352-dac54200-7e0c-11eb-9d84-2cb8d0b4f3d6.png)

**Steps to reproduce**:
1. hover field
2. edit it
3. unhover, tooltip is leaked
4. repeat
https://user-images.githubusercontent.com/39013340/110186394-ffb9b500-7e0c-11eb-8412-9c5fbbe0c917.mp4

**Link(s) to mod(s) used**: deltanedas/ldb memory editor used

**Save file**: ui bug

**(Crash) logs**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [_] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** todo
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not interested in fixing super specific UI bugs that don't occur in vanilla - don't put tooltips on text fields, or add an extra listener to make sure they get disposed later.

**Comment by liuxilu** [comment]
It's my fault, I 'remove' the tooltip improperly.
