### ISSUE TITLE
Game crashes when loaded with mods

### ISSUE THREAD

**Issue by DatOnePlayer** [Anuken/Mindustry#4872]
After updating to 126.1 I cannot launch the game because of the mods, the mods I used are stable ones

Also I disabled the option for "disabling mods on startup crash" and now it's just on a crash loop

**Comment by TheMrAlbert** [comment]
Please follow the issue template. Not like this.

**Comment by Quezler** [comment]
> Also I disabled the option for "disabling mods on startup crash" and now it's just on a crash loop

![outstanding move](https://i.kym-cdn.com/entries/icons/original/000/027/838/Untitled-1.jpg)

**Comment by DeltaNedas** [comment]
did the thought of the mods being the issue not cross your mind?
