### ISSUE TITLE
Building Bridges without unlocking them

### ISSUE THREAD

**Issue by Fred-Free** [Anuken/Mindustry#4875]
**Platform**: Windows & Android (pretty shure the bug applies to all platforms)
**Build**: Windows: steam build 126.1
                Android: release build 126.1
**Issue**: Due to the new Feature that dragging a belt over an obstacle automaticaly builds a bridge conveyor . The Problem is you can even do this without having bridge conveyors researched. 
**Steps to reproduce**: Clear you research data. Build a conveyor over an obstacle. 
**Save file**: [Bridge Bug.zip](https://github.com/Anuken/Mindustry/files/6095448/Bridge.Bug.zip) (Its not a save file my gamedata because i dont know how to upload my campain.)
---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Fred-Free** [comment]
pls dont ask me why the text is so big. i dont get it.

**Comment by liuxilu** [comment]
A wrong `!` on `bridge.unlockedNow`:
https://github.com/Anuken/Mindustry/blob/0d3be917b2ae7c73ad9f3b2c026b25d35856608f/core/src/mindustry/input/Placement.java#L113

**Comment by liuxilu** [comment]
A wrong `!` on `bridge.unlockedNow`: https://github.com/Anuken/Mindustry/blob/0d3be917b2ae7c73ad9f3b2c026b25d35856608f/core/src/mindustry/input/Placement.java#L113

**Comment by Quezler** [comment]
feel free to pr it ^

**Comment by vooxal** [comment]
This also happens with Bridge Conduits.
