### ISSUE TITLE
mindustry closes when trying to export/import

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry#4878]
**Note**: also applies to exporting/importing schematics.
 
**Platform**: Android (Redmi 9A)

**Build**: 126.1

**Issue**: i tried to export one of my maps, but when i finished exporting, the game restarted (it took me back to the loading screen). the exported .msav file was there, but it was empty (0 b).

**Steps to reproduce**:
1. go to editor
2. attempt to export/import map

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: not found.
 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
I actually reproduced the 0 bytes zip file issue, and lost my campaign research in the process.

**Comment by Anuken** [comment]
No crash log, cannot reproduce.
