### ISSUE TITLE
Player's speed is not limited to speed of formation

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#4879]
**Platform**: Windows

**Build**: 126

**Issue**: If you control unit with slower speed than yours in multiplayer and you are client, then you have no limit in speed but on server you do have the limit and after a while of flying you get reconciled back to your real position.

**Steps to reproduce**: simple example:
1. connect to server
2. take gamma
3. make horizons
4. make formation (but stay as gamma)
5. fly far
6. you get reconciled back after a while like your speed is too fast

**Link(s) to mod(s) used**: no mods

**Save file**: I don't think this is needed, but I'll attach gif
![formation_desync](https://user-images.githubusercontent.com/4199082/110217000-6e088100-7eba-11eb-9417-68c31df84683.gif)

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
I noticed this a while back and found that the `minFormationSpeed` isn't actually set on the client at all
