### ISSUE TITLE
IOException during multiplayer game. Client returned back to main menu, not crashed fully

### ISSUE THREAD

**Issue by FeyFre** [Anuken/Mindustry#4881]
**Platform**Windows

**Build**: 126

**Issue**: Crashed during multiplayer game session (IOException). Client kept working, just throw exception (will be attached)

**Steps to reproduce**: I just played on mindustry io attack server

**Link(s) to mod(s) used**: None

**Save file**: 
[IOException.zip](https://github.com/Anuken/Mindustry/files/6095992/IOException.zip)

**(Crash) logs**: It is not crash that generated such crash log, but there is Exception stack in other file last_log.txt, attaching
[last_log.zip](https://github.com/Anuken/Mindustry/files/6095996/last_log.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. This is not a crash, but a network error.

**Comment by FeyFre** [comment]
> This is not a crash, but a network error.
That is what I want to see, message "Network error" not useless exception stack trace! I even could not copy it into clipboard, only take a screenshot! What use it has besides annoying users?

**Comment by Anuken** [comment]
> That is what I want to see, message "Network error" not useless exception stack trace!

![image](https://user-images.githubusercontent.com/10100000/110243006-89a97100-7f26-11eb-868e-08e88d353968.png)

I recreated the error in the same place, and that's *literally* what it displays unless you explicitly click to view the stack trace. Why are you complaining about a stack trace being shown *when you clicked a button to show it?*

> useless exception stack trace

How is it useless, exactly?

> I even could not copy it into clipboard

And why do you need to do this when the log already saves it?

> What use it has besides annoying users?

It displays *where the error happened*, which is extremely important.

**Comment by FeyFre** [comment]
> How is it useless, exactly?
Assume I am 12yo player, not 35yo developer. What does it tell me? Nothing that I can understand. You already dumped it into log file, no reason to have it in UI, even hidden behind button. Believe me, I also like to have such detailed error messages. It is not easy to admit, but I have to agree that those should be hidden behind a ton of switches, and user must explicitly enable them to be displayed, like 'Debug mode' or something similar.
Again, it is about UX, and judging by behavior of user in game, anything more complex that single 3 words sentence will be overwhelming for them ;)

**Comment by Anuken** [comment]
> Assume I am 12yo player, not 35yo developer. What does it tell me? Nothing that I can understand.

That is absolutely not my problem. It gives details for people that want them, without any additional setup needed. 12-year-olds  don't care about the details, so they have **no reason to click it in the first place.** The obvious choice is to press 'ok' or ESC. You are going out of your way to cause problems for yourself.

> Again, it is about UX, and judging by behavior of user in game, anything more complex that single 3 words sentence will be overwhelming for them ;)

Users incapable of reading sentences longer than 3 words should not be playing this game, and I could not care less about whether they feel "overwhlemed" or not.
