### ISSUE TITLE
Logic Processor: move command ignores pathfinding

### ISSUE THREAD

**Issue by Artalus** [Anuken/Mindustry#4887]
**Build**: *Steam 126.1*

**Issue**: When units follow `ucontrol move` command in Logic Processor, they simply run a straight line instead of using pathfinding to navigate around obstacles and dangers. While it's OK for flying units, it can often prove fatal for naval and land ones. Ships can stuck in land formations, land robots can do so too, as well as drown in water or lava.

**Steps to reproduce**:
- Place unit factory on one side of a wall / water / lava lake
- Place Processor on another side with code like
```
ubind @dagger
ucontrol move @thisx @thisy
```
- Watch units move over straight line, getting stuck or dying

**Save file**: [pathfinding.zip](https://github.com/Anuken/Mindustry/files/6097454/pathfinding.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The *only* command that does pathfinding is `pathfinding`. All other commands are supposed to move in a straight line.

**Comment by Artalus** [comment]
Then shouldn't `pathfind` have passable coordinates? Right now it simply moves units to the "front line" - but for example, I would like to move them *away* from the battle to a repair point. This currently seems unachievable, since they will likely get stuck on the way.

**Comment by Anuken** [comment]
> Then shouldn't pathfind have passable coordinates?

No. There is no support for pathfinding to arbitrary positions anywhere in the codebase.
