### ISSUE TITLE
Payload Conveyor Animation when disabled

### ISSUE THREAD

**Issue by That-Guy977** [Anuken/Mindustry#4889]
**Platform**: *Android* (I think it applies to all platforms, though) 

**Build**: *126.1*

**Issue**: *When disabling payload conveyors, sometimes the animation with freeze in a frame with the arrow highlighted/offset, leading to some instances seeming very out of place. I think that completing the animation and freezing on a deactivated frame would be better.*

**Steps to reproduce**: *Place a payload conveyor, a processor, and a switch. Code the processor to set enable of the conveyor to the switch. Turn the switch on/off until the payload conveyor freezes on an "activated" frame.*

**Link(s) to mod(s) used**: *None*

**Save file**: *(This is my first time making anything on github, so I'm not sure if it'll end up on the right line.)

*

**(Crash) logs**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.

**Comment by That-Guy977** [comment]
Alright sorry for wasting your time, have a great day
