### ISSUE TITLE
Logic Block "Get Link" sometimes doesn't work properly after saving and loading

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#4891]
**Platform**: Windows

**Build**: Steam build 126.1

**Issue**: This is a follow-up of issue #4888.

When saving a map and loading a map, A Logic "Get Link" command can sometimes return null.

This is tested with this code:
![20210307211247_1](https://user-images.githubusercontent.com/75215867/110253846-b7290580-7f8c-11eb-8b6a-e14194355c2a.jpg)

When starting the map, all factories are disabled.
![20210307211500_1](https://user-images.githubusercontent.com/75215867/110253942-269ef500-7f8d-11eb-847c-c22d5600b28f.jpg)

After loading a couple of times, they all become active.
![20210307211231_1](https://user-images.githubusercontent.com/75215867/110253952-2b63a900-7f8d-11eb-8524-c2f20aef3549.jpg)

I copied the schematic a bunch of times in the hope I could reproduce the bug quicker. It didn't help a lot as it seems to be consistent when the code is the same. Different code does have an impact on when it happens.

**Steps to reproduce**:
- Load the following map named BugHunt:
[map_92.zip](https://github.com/Anuken/Mindustry/files/6097873/map_92.zip)
- Observe that the Factories are idle.
- Save and Quit + Load the game until the factories are no longer idle.

It took me 8 - 9 - 2 times to load before it happened so you may need to do it a couple of times.

**Link(s) to mod(s) used**: None
**Save file**: This is a save file where all the factories are active in case you cannot reproduce the bug.
[428.zip](https://github.com/Anuken/Mindustry/files/6097887/428.zip) For the actual map, see "Steps to Reproduce".

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by NoExit4U** [comment]
After more testing I found that this code also has the bug:
![20210307224053_1](https://user-images.githubusercontent.com/75215867/110255877-4c7cc780-7f96-11eb-9521-bbe396544413.jpg)

This code did NOT trigger the issue even though it has the same amount of lines:
![20210307224624_1](https://user-images.githubusercontent.com/75215867/110256036-fbb99e80-7f96-11eb-9645-a8138c9d4c65.jpg)

This code has the bug but it didn't enable the factory instantly. It enabled it a couple of seconds later instead.
![20210307231332_1](https://user-images.githubusercontent.com/75215867/110256765-ed6d8180-7f9a-11eb-9aa2-8fedcc6e8d5d.jpg)

So it seems like the variable "block" is sometimes not properly restored.

**Comment by Johnson-2003** [comment]
What language
