### ISSUE TITLE
Android: App crashes when setting name

### ISSUE THREAD

**Issue by dave7895** [Anuken/Mindustry#4893]
**Platform**: *Android*

**Build**: *release build 126.1*

**Issue**: *The app crashes when trying to create a in-game username.*

**Steps to reproduce**: *Open the game, go to join game, tap on the text field labeled `Name`. I get returned to my home screen, like exiting by pressing the back key.*

**Link(s) to mod(s) used**: *None used.*

**(Crash) logs**: *Empty log.*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** 
Bleeding edge works fine
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. Crash logs are **required.**
2. This does not occur on my device/emulator. Won't fix.

**Comment by GreyMario** [comment]
(this is probably because it's not _crashing_ and instead the device doesn't like being asked to use its native text input dialog)

**Comment by dave7895** [comment]
I understand crash logs are required and that you can't fix anything that doesn't occur elsewhere.

I agree that it could be the phone not liking the input, but strangely it works in the Bleeding edge version.
In release the keyboard and a cursor appear, then the app just closes.

**Comment by itcannotbe** [comment]
If it works in the bleeding edge but not the release it kinda means the "bug" is not present in the BE anymore... Soooooo. Yeah.

**Comment by dave7895** [comment]
I updated to 126.2 and it still occurs.

Is there any way to read the user name from a config file or something similar?

What are the differences between the daily builds and the release build, if any?

**Comment by Anuken** [comment]
> Is there any way to read the user name from a config file or something similar?

Not without tedious hex editing, which I have never done.

> What are the differences between the daily builds and the release build, if any?

A different package/application identifier, but otherwise nothing. This is very likely to be an issue with your system and/or application-specific cache.

**Comment by dave7895** [comment]
Would it be possible to hardcode it into the code and build it myself?

I think it's an issue of my system as in some other apps, mostly games, the keyboard just doesn't appear. What is even stranger is that mindustry is the only app that spontaneously closes and that the Bleeding Edge versions let me pick a username without a problem: What I think is a native dialog pops up and I can enter a nickname and press OK and it works...
