### ISSUE TITLE
In a logic block, when a block died, the dead sensor returns "null" instead of "1"

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#4894]
**Platform**: Windows

**Build**: steam build 126.1

**Issue**: In a logic block, when a block dies, the dead sensor returns "null" instead of "1"
This means that something like "jump if dead == true" or "jump if dead == 1" doesn't work as expected.

**Steps to reproduce**:
- Open the save file
- Hover your mouse over the message
- Notice that is says "0"
- Once the wall dies, notice that it says "null"
![20210308014302_1](https://user-images.githubusercontent.com/75215867/110261297-ec931a80-7faf-11eb-85cd-88dcc4e87457.jpg)

Code in logic block:
![20210308014309_1](https://user-images.githubusercontent.com/75215867/110261438-8955b800-7fb0-11eb-9ec2-19b5385cc35e.jpg)

**Link(s) to mod(s) used**: None

**Save file**: [452.zip](https://github.com/Anuken/Mindustry/files/6098297/452.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
If a block is `null`, it cannot be sensed, which means any sensor returns `null`.

**Comment by NoExit4U** [comment]
That's really counter-intuitive.

I would expect that this dead sensor is to have a clean way to be able to see if a unit is dead as that is its sole purpose.

If you do wish to keep it this way then I would highly recommend you to change the tooltip to mention this behavior.
Currently it says:
"Whether a unit/building is dead or no longer valid."
which kind of implies that it will return "true" if a building is "dead or no longer valid".

**Comment by NoExit4U** [comment]
Another possible solution could be to add an "Alive" Sensor and remove the "Dead" Sensor. In this context "1" and "null" as results for an "Alive" sensor make a lot more sense.

**Comment by PolloUsami** [comment]
> Another possible solution could be to add an "Alive" Sensor and remove the "Dead" Sensor. In this context "1" and "null" as results for an "Alive" sensor make a lot more sense.

for making a 'Alive' sensor just invert the dead value, even when null, use ( Alive = @dead xor 1)

**Comment by liuxilu** [comment]
Another solution is to save `wall1` to a variable: link `wall1` is `null` when it died, but a variable will keep the object.

**Comment by Anuken** [comment]
Checking for `dead` on a `null` variable is essentially asking the question, "is null dead?". Fundamentally, it's a question that doesn't make any sense - `null` can't be anything, it *doesn't exist.* It's like trying to invoke a method on `null` in Java.

However, I recognize that people will be using `dead` to check for missing units/blocks, and returning `null` will force logic programs to perform two checks (one for `dead`, one for `null`). As such, I am willing to make a special case for `dead` to work differently for null variables.

**Comment by NoExit4U** [comment]
> Checking for `dead` on a `null` variable is essentially asking the question, "is null dead?". Fundamentally, it's a question that doesn't make any sense - `null` can't be anything, it _doesn't exist._ It's like trying to invoke a method on `null` in Java.

True, but it's only true because you chose for a "dead unit" to become "nothing" and not a "dead unit". Having persistent dead units isn't crazy as "corpses", "broken down mechs", and "building ruins" exist in real life too and they can actually have benefits in Mindustry too:
- You can ask the location of the "corpse" to know where it died so you can send units there to defend.
- You can ask the location, type, and configuration of the "ruin" so you can send a builder there to rebuild it.
- Heck you could even create a minigame scoreboard where players try and crash their air unit as close to a bullseye as possible.

I'm not saying you should implement this (obviously a horrible idea for memory useage) but I'm giving you these examples to show why it can be counter intuitive for those that do not know the underlying code of what exactly happens to dead units.

And thanks for changing the dead sensor :).

**Comment by Anuken** [comment]
> True, but it's only true because you chose for a "dead unit" to become "nothing" and not a "dead unit".

That is not the case. If you assign a unit to something and that unit dies, the unit *will still exist*. Buildings work similarly.

This only occurs for **link variables**, because dead buildings are not valid and thus immediately get unlinked, making their variables null.

**Comment by NoExit4U** [comment]
oh I see, then the unexpected behaviour for me was that dead buildings get unlinked.
