### ISSUE TITLE
[logic] Inconsistant unit bind behaviour when binding order is changed

### ISSUE THREAD

**Issue by Nester23** [Anuken/Mindustry#4896]
**Platform**: *Windows*

**Build**: *126.1*

**Issue**:
*When units get destroyed the unit binding order changes, this causes unit bind to sometimes skip a unit or bind the same unit twice in a row.*

*Initially when I was making my unit counter logic, I thought that the counter bound and counted the units that were destroyed moments later, then new units entered the binding order behind the counter's saved unit, therefore the unit counter counted dead units as well as the newly made ones, so it returned unit count that was higher than the unit limit on the map.*

**But, when I got into way more advanced unit control logic, I found that the problem is that unit bind order is unstable;**

 * It counts completely safe flagged units that cannot die multiple times;
  * It double binds the saved unit and returns the count of 0 or 1;
  * It skips the saved unit, counting all the units twice or even thrice;
  
![Unstable ubind](https://user-images.githubusercontent.com/66305483/110289615-1d506f80-8003-11eb-970b-32deb29628a2.gif)

**This is my unit counter logic. I am pretty certain that it is foolproof:**
```py
ubind @flare
sensor uXDead uX @dead
jump 10 strictEqual uXDead false      #If the saved unit is dead, save a new one;
jump 7 notEqual @unit null      #If no units are found, return a special message;
print "[stat]Flare count: [coral]0"
printflush message1
end
set uX @unit
set uCounter 0      #Reset the previous counter, since the saved unit was replaced;
jump 16 always 0 0      #Skip returning the unit count, since nothing is counted yet;
jump 16 notEqual @unit uX      #If the current unit is the saved unit, return the counted units;
print "[stat]Flare count: [orange]"
set uCount uCounter
set uCounter 0
print uCount
printflush message1
op add uCounter uCounter 1      #Increment the unit counter by 1;
```
**Steps to reproduce**:
 * Go to a highly dangerous world;
 * Place down a lot of flare factories;
 * Setup my logic and watch what it returns;

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by liuxilu** [comment]
Your steps is not enough, you'd get a save: [4896.zip](https://github.com/Anuken/Mindustry/files/6100186/4896.zip)

**Comment by Nester23** [comment]
Faster processors are more resistant to miscounts and you used an overdrive domed hyper processor. 
The bug does show up on the save with a micro processor.

**Comment by liuxilu** [comment]
So you just use a fast processor to get the correct count.

**Comment by Nester23** [comment]
Switching to a more expensive processor to mitigate a bug doesn't fix it.

**Comment by liuxilu** [comment]
Essentially the same? https://github.com/Anuken/Mindustry/issues/4785 "logic orders"

**Comment by Nester23** [comment]
Not even close; The unit counter logic doesn't even have a ucontrol instruction.
Did you even read what I wrote other than how to reproduce it?

**Comment by liuxilu** [comment]
I did.
> unit binding order

**Comment by liuxilu** [comment]
Oh, they are not the same "order:.

**Comment by Nester23** [comment]
> 
> 
> Not even close; The unit counter logic doesn't even have a ucontrol instruction.
> Did you even read what I wrote other than how to reproduce it?

**_ok_**, @liuxilu 
I'm starting to overreact because of you trying to dismiss this report for non-valid reasons.
> So you just use a fast processor to get the correct count.
 * **First off, no, if there's a way to avoid a bug, it doesn't mean it's not there**:
 _You can apply this terrible logic to pretty much everything in the game and reason that the gameplay should be a pixel perfect execution of moves in order to achieve something without any issues._
 > Essentially the same? #4785 "logic orders"
  * **Second point is**: 
  _The orders given to units being cleared when you save & reload, is not the same as, the order in which units are bound being unstable._
  
  **With that out of the way.**
  
  ---
  What I think is supposed to happen, is that the counter would output the correct data, making only small and tolerable mistakes that might as well stay my problem.
  > Initially when I was making my unit counter logic, I thought that the counter bound and counted the units that were destroyed moments later, then new units entered the binding order behind the counter's saved unit, therefore the unit counter counted dead units as well as the newly made ones, so it returned unit count that was higher than the unit limit on the map.
  
  If you watch the attached GIF proof, then you might notice most of the mentioned problems happen.
> * It counts completely safe flagged units that cannot die multiple times;
> * It double binds the saved unit and returns the count of 0 or 1;
> * It skips the saved unit, counting all the units twice or even thrice;

_If everything were to be correct, then it should mostly return the result of 24, and only miscount between somewhere from 23 to 26 no less, no more._

**Comment by liuxilu** [comment]
I do not attemp to dismiss your report. Instead, I made a save to help download-and-reproduce. You could think my other words are just disordered complains.

**Comment by Anuken** [comment]
Unit bindings read from a list of units. When a unit dies, the order of that list changes, meaning the next binding is not defined. Not a bug.
