### ISSUE TITLE
Game froze after attempting to quit in fullscreen, required manual termination of Java process from secondary terminal

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#4899]
**Platform**: *GalliumOS 3.1*

**Build**: *126.1*

**Issue**: *After playing for a bit in fullscreen, I went to quit, and the game froze.  I had to manually terminate the Java process from a secondary terminal.*

**Steps to reproduce**: *Unknown―have not been able to reproduce.  Orignally caused after attempting to quit after playing for a bit in fullscreen.*

**Link(s) to mod(s) used**: *Not applicable*

**Save file**: *Not applicable*

**(Crash) logs**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No logs, cannot reproduce.
