### ISSUE TITLE
Cannot invoke "arc.graphics.gl.FrameBuffer.dispose()" because "this.shadowBuffer" is null

### ISSUE THREAD

**Issue by Mindavi** [Anuken/Mindustry#4902]
**Platform**: Linux
**Build**: Release build 125.1 and 126.1

**Issue**: When closing the game before it's fully started, a java.lang.NullPointerException is thrown.

**Context**: I'm trying to update the mindustry 125.1 package to 126.1 in the nixpkgs repository. See https://github.com/NixOS/nixpkgs/pull/115442. @petabyteboy is having issues starting the application, and I've reproduced the issue at least partially (there's probably another bug lurking behind this error).

**Steps to reproduce**:

1. Start game.
2. Close game before the main screen is loaded.

**Link(s) to mod(s) used**: No mods used, vanilla.

**(Crash) logs**: 

<details><summary>Crash log</summary>

```
rick@nixos-asus:~/nixpkgs$ ./result/bin/mindustry
[I] Initialized Discord rich presence.
[I] [Audio] Initialized SoLoud 202002 using MiniAudio at 44100hz / 2048 samples / 2 channels
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) HD Graphics 530 (SKL GT2)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 15.0.1
java.lang.NullPointerException: Cannot invoke "arc.graphics.gl.FrameBuffer.dispose()" because "this.shadowBuffer" is null
        at mindustry.game.Schematics.lambda$new$1(Schematics.java:69)
        at arc.Events.lambda$fire$2(Events.java:30)
        at arc.struct.Seq.each(Seq.java:200)
        at arc.Events.fire(Events.java:30)
        at arc.Events.fire(Events.java:25)
        at mindustry.core.Renderer.dispose(Renderer.java:129)
        at arc.ApplicationCore.dispose(ApplicationCore.java:57)
        at arc.backend.sdl.SdlApplication.lambda$cleanup$13(SdlApplication.java:169)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
        at arc.backend.sdl.SdlApplication.cleanup(SdlApplication.java:166)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:48)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

</details>

For the issues @petabyteboy is having I'd like to refer you to the pull request linked above (the first exception is the same, but some extra exceptions are shown: `arc.util.ArcRuntimeException: java.lang.IllegalArgumentException: No glyph`), they've posted a log there. I've looked at the issue tracker and while ArcRuntimeException is something that's listed more often, the `No glyph` part does not seem to be mentioned anywhere else. Please let me know if a new issue should be opened or if it's okay to group them here.

I'm pretty positive that fixing this might not fix all the issues @petabyteboy is having with starting the game, but it's a good starting point and might point to some other latent issues.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

I have tried patching the game to prevent that particular error, and it seems to prevent it. However, since I'm not familiar with the codebase I'm not sure if it's the correct way to do it. See https://github.com/NixOS/nixpkgs/pull/115442#issuecomment-793036123 (basically, adding a null check for the `shadowBuffer`).

Please let me know if there's anything else with regard to versions you need.

**Comment by Anuken** [comment]
I don't see any reason to fix this - the error doesn't result in a *crash*, and is completely harmless.
