### ISSUE TITLE
Maces drowned themselves after capturing Ruinous Shores (potential spoilers?)

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#4903]
**Platform**: *GalliumOS 3.1*

**Build**: *126.1*

**Issue**: *After I captured Ruinous Shores, a bunch of my maces drowned themselves.  As seen below, the maces were at the pumps for the duos, then a bunch of them crowded together and drowned themselves near the bottom of that copper wall thing.
![They went from near the pumps for the duos to the bottom of that big copper wall.](https://user-images.githubusercontent.com/50188776/110377759-c9ee1980-8022-11eb-84ba-1bf0a91ed228.png)*

**Steps to reproduce**: *Capture ruinous shores, I think?*

**Link(s) to mod(s) used**: *Not applicable.*

**Save file**: *This seems like a really big privacy invasion, especially on a public forum.*

**(Crash) logs**: *Not applicable.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueManedHawk** [comment]
That seems like a pretty big invasion of privacy.

**Comment by Anuken** [comment]
Yes, you've already said that. This report is useless without a save - either post one, or don't open an issue.

I'm not even sure what kind of private information you expect your save file to contain.

**Comment by BlueManedHawk** [comment]
It's mostly just the fact that save file will almost certainly contain things which I don't want anybody to see.  I can't think of anything in particular, but I'm certain it will be there.  I'm also somewhat concerned that the file will contain information about my computer.

**Comment by nichrosia** [comment]
Something else you could do, is upload `sector-serpulo-213.msav` in the `saves/` folder in your Mindustry directory. This is just the file for Ruinous shores.

**Comment by BlueManedHawk** [comment]
That still seems potentially problematic.

**Comment by liuxilu** [comment]
Repuduced! [rep4903.zip](https://github.com/Anuken/Mindustry/files/6106062/rep4903.zip)

**Comment by Bohaska** [comment]
> That still seems potentially problematic.

... Maps  and saves DO NOT contain any personally identifying information. They only store the information of every tile in the map and the location of every building on the map.
