### ISSUE TITLE
Crash on startup: No glyph:  (59420)

### ISSUE THREAD

**Issue by petabyteboy** [Anuken/Mindustry#4904]
I have not had the chance to try with the prebuilt binaries, as they do not run on my system without lots of tricks. Arc and Mindustry were built from source as described in the Nix package.

**Platform**: *Android/iOS/Mac/Windows/Linux*

Linux (NixOS)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

126.1

**Issue**: *Explain your issue in detail.*

I start the game. It shows the loading screen, but before the title menu is shown it crashes.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Unclear, it happens to me every time I start Mindustry on one machine. On another machine the same files work, so the issue must be in some cache directory like `/home` or `/tmp`.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

N/A

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

```
[E] arc.util.ArcRuntimeException: java.lang.IllegalArgumentException: No glyph:  (59420)
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:143)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.lang.IllegalArgumentException: No glyph:  (59420)
	at mindustry.ui.Fonts.getGlyph(Fonts.java:238)
	at mindustry.gen.Icon.load(Icon.java:676)
	at mindustry.core.UI.loadSync(UI.java:102)
	at arc.assets.AssetManager$2.loadSync(AssetManager.java:358)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:125)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There are several possibilities here:
- You have a local file `fonts/icon.ttf` or `fonts/font.woff` in the working directory of the game, which is loaded instead of the classpath one.
- Freetype is broken on your machine.
- Something else specific to your OS.

**Comment by petabyteboy** [comment]
Thanks for the quick answer.

> * You have a local file `fonts/icon.ttf` or `fonts/font.woff` in the working directory of the game, which is loaded instead of the classpath one.

Indeed! `fonts/font.ttf` `fonts/icon.ttf` exist in my home directory, which was also the working directory I ran Mindustry from.
However I don't remember putting them there. Does Mindustry extract/copy these files to the working directory?

**Comment by Anuken** [comment]
No, aside from music (*which is placed in /tmp/*), nothing should be extracted. This is the first time I've heard of something like this happening.
