### ISSUE TITLE
Mod Reinstall Issue

### ISSUE THREAD

**Issue by Volas171** [Anuken/Mindustry#4906]
**Platform**: *Windows and Linux*

**Build**: 
126.1

**Issue**: 

when a mod gets disabled when opening 2 mindustry tabs, next time when trying to reinstall it doesn't delete the old mod file.

**Steps to reproduce**:

open 2 mindustry .jars while the other is in loading mode, it will tell you that all mods have been disabled , close mindustry
open it again and reinstall the mod , it doesn't delete the old file

**Link(s) to mod(s) used**: *
can be any mod actually

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

- [X]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> open 2 mindustry .jars

Don't. This is not supported.
