### ISSUE TITLE
future of the .ru

### ISSUE THREAD

**Issue by Dark-Diamond** [Anuken/Mindustry#4907]
I understand perfectly well how these disputes have already got you, I myself do not like it.  but nevertheless I would like to ask for the last time, is it possible to add our server to the global list?  
for so much time, we tried with all our might to correct all our past mistakes, we wanted to believe that all was not lost for us.  so much effort and nerves was spent on it that it is difficult to imagine. 
so I want to know, preferably from Anuken himself, if our server will live?  or all efforts are in vain.  
I admit the server was not perfect and had many reasons for deletion.  but I assure you these reasons were noticed and corrected, albeit a little late 
I ask you to give us one last chance to exist, I do not want to lose this server.  we have corrected and we want you to be convinced of this
hope for understanding and prompt answers

**Comment by itcannotbe** [comment]
[Part 1](https://user-images.githubusercontent.com/45280919/101311062-7f29fd80-388b-11eb-87c1-8fccd33c6769.jpg)

[Part 2](https://user-images.githubusercontent.com/45280919/101310974-425e0680-388b-11eb-8ccd-77a07315ea36.jpg)

**Comment by Quezler** [comment]
@itcannotbe use `![part #](image url)`

**Comment by itcannotbe** [comment]
I was in the middle of fixing it.

**Comment by joshuaptfan** [comment]
[Link to the comment above](https://github.com/Anuken/Mindustry/pull/3793#issuecomment-739560478)

**Comment by 1ARC1** [comment]
wait this is a bug?

**Comment by 1ARC1** [comment]
no offense but I don't think this is a game bug, why not just talk to Anuke on discord about this instead of opening a game bug report

**Comment by Dark-Diamond** [comment]
> no offense but I don't think this is a game bug, why not just talk to Anuke on discord about this instead of opening a game bug report?

I am being ignored. But I didn't want to create a pr for this, so I wrote here :/

**Comment by parkuristt** [comment]
Instead of using the repository's issue tab, you can simply DM Anuke on Discord: Anuke#4986

**Comment by itcannotbe** [comment]
> ![Part 1](https://user-images.githubusercontent.com/45280919/101311062-7f29fd80-388b-11eb-87c1-8fccd33c6769.jpg)
> 
> ![Part 2](https://user-images.githubusercontent.com/45280919/101310974-425e0680-388b-11eb-8ccd-77a07315ea36.jpg)



> > no offense but I don't think this is a game bug, why not just talk to Anuke on discord about this instead of opening a game bug report?
> 
> I am being ignored. But I didn't want to create a pr for this, so I wrote here :/

I wonder why.........

**Comment by Dark-Diamond** [comment]
> Instead of using the repository's issue tab, you can simply DM Anuke on Discord: Anuke#4986

How do you think I wrote to him? pigeon mail?

**Comment by 1ARC1** [comment]
ok you need to talk to him via getting his attention to end this

**Comment by Dark-Diamond** [comment]
In any case, I don't think your comments are needed here. My post was not written for you and not for you to answer it. And you think I haven't seen the "verdict"?

**Comment by 1ARC1** [comment]
but this isn't a game issue. Anuke will ignore it, and probably close it, which is justified.

**Comment by Dark-Diamond** [comment]
Am I going to get it if he does the same thing in discord? He will just block me and continue to ignore me.

**Comment by 1ARC1** [comment]
because, he seems to be done with this whole server nonsense with the .ru server. if the cat does not want your server in the server list, chances are you aren't gonna change the cat's mind. end of story.

**Comment by Dark-Diamond** [comment]
He personally said that he would consider my proposal, but a lot of time has passed since then and he will simply ignore me

**Comment by 1ARC1** [comment]
then there is nothing you can do but hope that the cat has mercy on your server then.

**Comment by Bohaska** [comment]
At least try adding some proof that you changed, please

**Comment by Dark-Diamond** [comment]
I don’t remember exactly, but baseduser told what had changed.  If, in short, the donate is removed, some of the admins are replaced, some minor mistakes are also fixed also partially changed the rules.Well, about the server, I don't think that the community will agree with this if they see that the previous admins want to create a new server

**Comment by Dark-Diamond** [comment]
New account because the old one was with a false nickname. I didn't see if it was possible to change the nickname, and just created a new account

**Comment by Bohaska** [comment]
> you blew your chance.

Please, if you really want to be in the server list and all that, start over with a complete refresh.i

**Comment by SupremeTurtle** [comment]
How hard headed can you be to not understand that "This decision is final" and "Please don't try to contact me or try to change my mind", you already did horrible with .ru, no one likes it, let it die.

**Comment by Bohaska** [comment]
@UtoECat  Why did you upvote this suggestion?

**Comment by Bohaska** [comment]
Yay anuke closed this

**Comment by Newguy-ish** [comment]
Looks like his opinion is not changing for a long time.

**Comment by Volas171** [comment]
> > for so much time, we tried with all our might to correct all our past mistakes, we wanted to believe that all was not lost for us. so much effort and nerves was spent on it that it is difficult to imagine.
> > I admit the server was not perfect and had many reasons for deletion. but I assure you these reasons were noticed and corrected, albeit a little late
> > I ask you to give us one last chance to exist, I do not want to lose this server. we have corrected and we want you to be convinced of this
> 
> @Dark-Diamond At least try adding some proof that you changed, please. Also, why the new account?
> 
> If it still fails, I suggest that you abandon [mindustry.ru](http://mindustry.ru) and start a new server, one which is dedicated to preventing the catastrophic mistakes of [mindustry.ru](http://mindustry.ru)

for the record that happened, it is now named easyplay.su and ran by router (very suspicious)
