### ISSUE TITLE
Mindustry screen recorder silent bug

### ISSUE THREAD

**Issue by Electric100** [Anuken/Mindustry#4916]
*Platform**: *Android*

**Build**: *126.1*

**Issue**: *Cannot record a Mindustry video with sounds using a recorder with internal audio enabled (Android 10 exclusive). Mindustry becomes silent as soon as I press record, and stays silent until I reboot the game, even after cancelling the recording. Happens anywhere in Mindustry (main menu, in-game, multiplayer etc).
In short, recording the game using an internal audio screen recorder turns off all the sounds and music; no sound gets recorded at all. This only happens in Mindustry, and does not happen when recording external audio.
Bug occurs even on different Android devices*

**Steps to reproduce**: 
*1. Open Mindustry
2. Record using a screen recorder with internal audio enabled.
3. The music and sounds will be disabled a split second after pressing record, even with 100% volume in the settings and device. No sound will be played on the recorded video.*

**Link(s) to mod(s) used**: *No mods were used*

**Save file**: 
*[mindustry save 10 march 2021.zip]*(https://github.com/Anuken/Mindustry/files/6115864/mindustry.save.10.march.2021.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Use a different recorder. I'm not interested in fixing bugs that occur with use of external programs.

**Comment by SupremeTurtle** [comment]
Seems to happen with multiple people with different video recorders.
