### ISSUE TITLE
Bridges build out of order in the build queue link incorrectly

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#4919]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.1

**Issue**: *Explain your issue in detail.*
When you put things into the build queue and run out of material, the player will build things out of order. This is normal. Sometimes though when it decides to build bridges out of order the bridges don't remember which direction they're linked to and link randomly. I've never had this occur with schematics or click+hold placing to build a line of bridges. It only occurs when placing bridges down manually one-by-one. The order they link is determined solely by the order they get built. It happens rarely and is difficult to figure out exactly how to recreate.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Make sure the core has enough copper/lead.
2. Make sure you have a source of copper/lead going into the core. For best results, make the sources slow.
3. Start building a ton of scatters, enough to exhaust all of your copper or lead.
4. Immediately start placing bridges (one at a time, not click+hold) and take note of the order you placed them. Make sure every bridge can link up to a nearby bridge.
5. At some point the copper will run out and the player will go through the normal process of building 1 item per scatter to keep them on the map to be finished later.
6. It will then get to the bridges and do the same process (because we're out of copper or lead).
7. At this point I get different results depending on how fast the sources are and when I placed the bridges in comparison to the scatters. Sometimes the bridges will link in the correct order and sometimes they won't. The order they link is determined solely by the order they get built.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://ufile.io/xmy6gah4

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
NA
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug. Bridges built out of order do not have a set configuration and will link in the order they are built.
