### ISSUE TITLE
NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by xiaoxiaobingdxb** [Anuken/Mindustry#4920]
**Platform**: *Mac*

**Build**: *the master branch*

**Issue**: *I run the command "java -jar Mindustry.jar that I build, and the terminal show the error "*

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/issues/1378#issue-549501425

**Comment by xiaoxiaobingdxb** [comment]
> [#1378 (comment)](https://github.com/Anuken/Mindustry/issues/1378#issue-549501425)

yes, run with the jvm option params then it can work well, thank you very much!!!
