### ISSUE TITLE
Auto-bridge+ctrl drag=

### ISSUE THREAD

**Issue by Lele567** [Anuken/Mindustry#4922]
**Platform**: *Windows*

**Build**: *126.1*

**Issue**: *The new auto-bridge feature doesn't work with ctrl drag*

**Steps to reproduce**: *While testing the auto-bridge feature, I enclosed the starting point within a wall, While ctrl dragging outside the box, the conveyer heads in a straight line and doesn't curve*

**Link(s) to mod(s) used**: *deltanedasldb, deltanedasoverride-lib, deltanedasui-lib, deltanedasunit-factory, rftm-master*

**Save file**: *[save.zip](https://github.com/Anuken/Mindustry/files/6124839/save.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to.
