### ISSUE TITLE
Unit Locate Inconsistencies

### ISSUE THREAD

**Issue by FlippingPotatoes** [Anuken/Mindustry#4930]
**Platform**: Tested on both windows 10 and iOS 14.4

**Build**: 126.1 (I've also tested this on bleeding edge 20917 with the same results)

**Issue**: With regards to unit locating ore, later iterations of the command output the values of previous iterations. This can lead to missing ores depicting a found value of true, and incorrect outX and outY coordinates. Additionally, it does not solely output the incorrect values, it will occasionally output the intended values, or a mix of incorrect and correct values. I at first thought it could be due to processes happening on the same frame, but regardless of delay these problems occur, and with a wide variety of logic setups.

**Steps to reproduce**: This occurs in numerous ways, with slight variance as to the results. The world file attached shows the fail cases I could find side by side, though the more notable schematics will be added here. Tests were done with 1 existing flare, and all ores present. All schematics have a small note on the side stating what's happening and the results for quick viewing, as well as live data (with a counting number to show they are changing, and it is happening sequentially)

First using a unit locate ore with a variable setting the ore, on the first run, the correct results are given. Changing the ore variable to null with a set command and rerunning the unit locate command does one of two things; If the variable is not changed back, and the process jumps back to the unit locate line causes the x,y coordinate to not change, but the found variable appears to work normally. schematic: 
bXNjaAF4nGNgYWBkYmDJS8xNZZAOzcssUfDJT04sSVUoTi1RyC9KVSjJV8grzclh4E5JLU4uyiwoyczPY2BgYmDPTS0uTkxPZeDPzUwuytctKMpPBorkFzEwMDAzgAALI8MF/7LUoqLMlMy8dLBhZYlFmYlJOXBTubgqdCoVkvPzi1KKFfJSgYoVilKBNusopOWX5qUopOSnFnNx+aek5FTqKJRnpOYpVOaXAtUXVCoUJBYDXVmSkVmskJiTDzS/ODMFxE9VyAcSRQpw9xTrQFSBzFLIywf6Kjm5tEhBoyAnMRnkLqCXQQakQhRkJJZBTMksKkpNL80BOrgkEyxeUJCap8nEyMDIwMAH9N3yijmpE2z5mg14Wp3VpwRHnIl9wRlRNWGChIfoHJNO1R22mYwrF3XX2/1+eXJdy4qsd7qSL9iWK51qkVQqudXeEPiL4ZTEhcmLLl7ysPkusT5X23nLFP0fDbwmk+Ze11L+0bHAXtH92KNNB7ianyfd21y6zIP/4vqK9fuy60ssT/5VeT2P/Xhmk2RwkPK244FHzp0UP88o52Bnf3+NTImP2XvlwHmKr4JV8pxyTpnHc0KiAxgXDAwAKnK0GQ==

However, as demonstrated in this schematic, this same series of code actually outputs found to be 1 on a varying number of the first iterations still using null as the ore, when placing, occasionally found does function correctly, multiple places may be necessary. schematic: 
bXNjaAF4nGNgYWBiYmDJS8xNZZAPzcssUfDJT04sSVXIK83JUUjLL81LUSgoyk/KSc0tZuBOSS1OLsosKMnMz2NgYGJgz00tLk5MT2Xgz81MLsrXBSpMBorkFzEwMLAwgAALI8N8/7LUoqLMlMy8dIX8olSFssSizESgeQol+WBLdBSSSkuAdmTmlYCUlGSkKiQnFqcqlGekFqUmVULdkFmsYAhWCDICyAHp5OIKSi3ISUwGaQM6PDkxTyE5IzEvPVUhI79cITcxr1KhKLUgNbGkWCEpNQ2kEW5WXr5CTj5QZZGCIQMjEDLwAR27u2LO0QmOfM0KAq4bV7cF++x6t2hWyftl7I6SU9kamSa/sKx6GHRU7wvD3QN/zH/WT4o3CNuzMtDN6W7mw4nsPQ8W5q0tfrGzVGFJS5nAsvBl5iZmL75verIkV1up6SvH2++d8wyO+hg4p2suNV+yxUfs35KLjpXsNRMvVFY+PqctXL5TMu7BpOXKkW/YrXKf7JpY+dfaN7FB0FnANuy/RdSzOt7MvWGBjRs/bpwSODmwMNbwmN+bPTMvnalb5bXqB4P61omeQOczg4ObAcxiBLGYAalwskg=

If instead of never alternating back to the previous variable, you instead switch between two variables constantly, the null ore alternates between giving 0,0 and the value of the previous unit locate, excluding found which is zero. schem:
bXNjaAF4nGNgYWBkYmDJS8xNZZAJzcssUcjJT04sSVUoSi1IBdIpCskZiXnpqcUM3CmpxclFmQUlmfl5DAxMDOy5qcXFiempDPy5mclF+boFRfnJQJH8IgYGBmYGEGBhZAgMKs3Ly8xLh5laUp6ZnKpQnlmSoZAIMRkkmV+UqlCWWJSZmJSTysVVoVOpkAgUyS9LLSrKTEnNU8hPTk4sBlqbmJNTycTIwMjAwAc0fkHFnKsTHbkOKwi4+oYfDeaJLJ8s/UThroSs8MGeRXwq6a9Us29zqNo6mh/+c7zGbv7LlhdyNpZGBlHrhU71sAr1WB3p8GzjOCVxoXvRzYs+e/xmnCuaYGippV5zQK7qpF1GqICT04X1gULJvjcT2KV3tPm/2bPy2uEvuf9y3m+W32ValJ2S/8Tv78XWG7/36ybZPmcNOxN51sIj8L/qOt+ubgF/843TfSEBAQwFBgYARHWC6A==

There is also a difference between using variables or new command lines, how it impacts things varies as well, the world includes a side by side, but the most notable difference occurs when using more than two ores. Namely, when using a third ore check it can be seen that things are scrambled even further. In the case of a ore variable swap, found for normal ores sometimes became 0 when null ore checks were done on top of the x,y coordinates being incorrect (when not using variables, the found problems did not occur, but coordinate problems did) additionally, this example sets the initial variables to zero prior to each unit locate command, but whether it was there or not, the wrong coordinates and found values were printed. When none were null, the problems remained. schema (both the example with a null and the one without): 
bXNjaAF4nGNgYWBiYmDJS8xNZZAPzcssUcjJT04sSVUwVkjOSMxLz8xLV8gvSlUoSyzKZOBOSS1OLsosKMnMz2NgYGJgz00tLk5MT2Xgz81MLsrXLSjKTwaK5BcxMDCwMYAACyPDVGRTyzNLMhRyS3NKMgtyUuEGJyblpOooJJWWKOTl56UqJAKF80pzcvS4uCp0KnUUEvNSYPpBUsWpJQol+QpVqUX5CkmpaSBDUhOTM6BKIJoUkvPzi1Iy84ACxQrFJZk5OQrpQG1A1yfmAi1L0WMEuY4R6LwrGM7D8DfEeRCng8TywQFQrAC0GqymBOQOPQV/oNPz0xRKMlKLEWoyi2FecUxJyQSJJebkVCqAnAjyVlp+KZAE+QooDPOZAcxbRaV5eSCHQFwH8RiqrtzMilQgCxj4xcUgmxWS8hOLUvSYGBmAHuQDevFNxZzaid5+Rwx42ozXBPgllp5NOuWxJv0wb8QmT+ntwlOsFHuXnjO1FFTzZZFikbavq61TsdMo/VHxWPUQp8aT5+Vmcud89Jg3fp/F7i52brI5p+mkq4pNGxf1NGom/+JrOey7fsbCDsOkX9J2phcW/1yefn/Dm02Kx71PmluI1a+tE7rlFXO7R9x58+KZFZJLjvveej1D5qn0zi7Zklm1Er5uHJyJf4wsDU/xzT5zW533zZ6pl6K+bK7o5/rmfXfWpwtTsqN3/ond2s9bvdTv+umKmOvikTuU/J/erK658/Hk56pGVwvj5PVT54Te3R5yV/MrZ/3/xSYMIG8zgrz9CuRt27zDBjytU/1a/Rwr3gmYOzzX2et4XG+Tq7VWStRE1wOWKe9E3KZdUHLdHeDPL1+v8m7Krdj9FVwFDLMu/57Z26482dvhzd5n5ya2Pn7g69Kb8lXmQEThr5maiX/EDj1cJe4z4ayAwT9eea0XF/8Eb9aNkHuqF37j+eegc44O2rtCXvi3ubkrf7zi+evw1quKVl78ZYbSGSa/d5pzJvZx/LVdckLjbfjL7aWvblRqr1R9mf5pmdG307GrPwfN9Za1rI/uXC/6e4nb9KUVMdP4JXco5P+8Ofte/o8HlZYHVeZIbrzqZbZq3utQW81S5ncJC+2BvmUGZzQGMIsRzAIANCeB/A==

**Link(s) to mod(s) used**: None

**Save file**: 
[Unit Locate Bug Demonstration.zip](https://github.com/Anuken/Mindustry/files/6133775/Unit.Locate.Bug.Demonstration.zip)

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The UnitLocate instruction caches its results and only refreshes the output a few times a second, to prevent lag - regardless of input. All radar-type instructions work similarly.

If you are changing parameters to the instruction rapidly, use multiple instructions.

**Comment by FlippingPotatoes** [comment]
> Use multiple instructions

In cases where parameters were not changed for a single instruction, but instead more instructions were done, x,y coordinates were still mixed. (By more instructions are you referring to more processors, or in regards to other radars different configs?)

Either way I understand it won’t be changed, and thank you for your time :D

**Comment by joshuaptfan** [comment]
> (By more instructions are you referring to more processors, or in regards to other radars different configs?)

He probably means using multiple instances of the same instruction, as each instance of that instruction has its own cache. See #4233.

**Comment by FlippingPotatoes** [comment]
>Multiple instances
I appreciate the clarification, in the context of caching I believe my mixed results specifically that confused me was that of the case of multiple instructions 1 of which is null. (Null is likely skipped entirely for efficiency, returning false for found, though I believe it should set the x,y to zero as well, but I digress)

Thanks for the help :D
