### ISSUE TITLE
Ship "Beta" Not Looking at Mouse Position When Firing

### ISSUE THREAD

**Issue by MustacheLincoln** [Anuken/Mindustry#4932]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.1`

**Issue**: The ship "Beta" has a visual bug where it does not look at the mouse position while firing like it's supposed to, instead the gun sprites rotate to look at mouse position all the time.

**Steps to reproduce**: Build the Foundation Core and enter the "Beta" ship

**Link(s) to mod(s) used**: `none`

**Save file**: [BetaShipBug.zip](https://github.com/Anuken/Mindustry/files/6134481/BetaShipBug.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
i don't think this is a bug

**Comment by MustacheLincoln** [comment]
It would be bizarre if it wasn't, it's inconsistent with every other ship.

**Comment by TheRealIvyX** [comment]
that is not a bug. horizon, quad and mega also do this

**Comment by MustacheLincoln** [comment]
It makes sense for the bombers (Horizon and Quad), but it looks very awkward for the Beta and is especially strange that it's inconsistent with the Alpha and Gamma. I'm not convinced that rotateShooting is intended to be false for the Beta (and perhaps Mega too).

**Comment by BlueWolf3682** [comment]
That's because their weapons rotate and they can build and mine. Otherwise, it would look really wierd.

**Comment by TheRealIvyX** [comment]
rotateShooting is intended to be false for beta and mega

**Comment by MustacheLincoln** [comment]
From an in-lore perspective, if the Alpha, Beta, and Gamma are supposed to represent a linear progression, it seems wrong to me that the Beta would gain rotating weapons only to have them revert back to static for the Gamma.

**Comment by MustacheLincoln** [comment]
I apologize for putting this here instead of in Suggestions if Anuken closes as intentional. I legitimately believed this to be a bug. I appreciate the responses though!
