### ISSUE TITLE
Ball of energy temporarily stabilized

### ISSUE THREAD

**Issue by Lele567** [Anuken/Mindustry#4934]
**Platform**: *Windows*

**Build**: *126.1*

**Issue**: *I was messing around in sandbox, and I saw this bug. I summoned and killed a corvus before it had a chance to fire, but it managed to start charging its beam. The charging particle didn't vanish however. May be related to this https://github.com/Anuken/Mindustry/issues/2679. [Video](https://user-images.githubusercontent.com/48808663/111053546-a36d1b80-8432-11eb-9586-972d2c13cb7a.mp4)*

**Steps to reproduce**: *16 fuses surrounding a hollow square of large thorium walls, all with thorium ammo, cryofluid, and overdrive dome. Summon a corvus in the thorium square. Move around the square if necessary.*

**Link(s) to mod(s) used**: *deltanedasldb, deltanedasoverride-lib, deltanedasui-lib, deltanedasunit-factory, rftm-master*

**Save file**: *[save.zip](https://github.com/Anuken/Mindustry/files/6135905/save.zip)*

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The corvus started firing, and died before it could shoot. You saw the residual shooting effect.
