### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by imsorryza2015** [Anuken/Mindustry#4936]
**Platform**: `iOS x32`

**Build**: `release build 126.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**.    
![9D093B52-9536-44DB-83A4-47CCB112089B](https://user-images.githubusercontent.com/52307494/111103262-9eb67d80-8580-11eb-9732-d26232d13f70.png)
 WTF

**Comment by joshuaptfan** [comment]
Spilling water from pipes cannot put out fires. You must build wave or tsunami turrets, and give water to them.

Not a bug.

**Comment by RebornTrack970** [comment]
Turn this into a suggestion.
