### ISSUE TITLE
Proposal for renaming variables on `editor` (minor changes)

### ISSUE THREAD

**Issue by tucan9389** [Anuken/Mindustry#494]
Could I refactoring PR for renaming on the `editor`(located on [here](https://github.com/Anuken/Mindustry/tree/master/core/src/io/anuke/mindustry/editor))? I think it's minor changes.

**Comment by Anuken** [comment]
Renaming what, exactly?

**Comment by tucan9389** [comment]
@Anuken please check the pr #495 
Thanks :-)

**Comment by tucan9389** [comment]
@Anuken  Thanks for accepting #496. 
Here is one more PR #495. Please check this out when you have time. Thanks.
