### ISSUE TITLE
having phase fabric without the machine

### ISSUE THREAD

**Issue by beepboopc** [Anuken/Mindustry#4942]
**Platform**: Windows

**Build**: 126.1

**Issue**: I have phase fabric with out the machine

**Steps to reproduce**: I don't know

**Link to mods used**: none

**Save [file]**:[bug 1.zip](https://github.com/Anuken/Mindustry/files/6151990/bug.1.zip)

![Capture](https://user-images.githubusercontent.com/80787882/111374487-caaa2f80-8662-11eb-8973-001f5e1b0ad0.PNG)

**(Crash) logs**: none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Lele567** [comment]
Did you disassemble any buildings from the map? That's one way to get early titanium, thorium, phase fabric, ect. If so, then it's not a bug, but intended behavior.

**Comment by beepboopc** [comment]
> Did you disassemble any buildings from the map? That's one way to get early titanium, thorium, phase fabric, ect. If so, then it's not a bug, but intended behavior.

no i did not

**Comment by Lele567** [comment]
I would say that your save file got edited or mixed up with another one somehow.

**Comment by Anuken** [comment]
> no i did not

I don't believe you.
