### ISSUE TITLE
Simulation when not in sector calculated incorrectly.

### ISSUE THREAD

**Issue by numer99** [Anuken/Mindustry#4944]
Platform: Android
Build: 126.1

Issue: I entered ruinous shores placed some factories, ABOUT 16 turrets with supply, some walls and then the AI went around the defenses and I ran out of resources so I left to capture another sector, but after awhile the sector captured and I went to ruinous shores and it was barley damaged (21 waves of not being there btw)

Steps to reproduce: Trick the game into thinking the sector is safe by placing turrets and walls in the correct positions

Save file: I cannot send it from my android device, because nothing that is not a game will load.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

(Sorry if I did anything wrong)

**Comment by Anuken** [comment]
1. No save file. **Save files are absolutely required.**
2. The simulation will always be inaccurate.
