### ISSUE TITLE
Saved pvp game stuck in pvp mode even after importing in editor

### ISSUE THREAD

**Issue by Lightforger** [Anuken/Mindustry#4953]
**Platform**: *Windows*

**Build**: *126.1*

**Issue**: A saved game from a pvp server is stuck in pvp mode even after importing it in the editor, editing, and then then starting it as non-pvp

**Steps to reproduce**:
- go on a pvp server, save the game
- go to the editor, 'Import Map', select the saved game (or 'New Map > Import > Import Map')
- in the editor, pick 'edit in-game' -> stuck on 'waiting for players'
- alternatively, save the game in the editor
- Play > Custom game > select saved game, sandbox mode
- upon joining it is not sandbox mode but pvp mode -> stuck on 'waiting for players'

**Link(s) to mod(s) used**: none

**Save file**: [not pvp.zip](https://github.com/Anuken/Mindustry/files/6160565/not.pvp.zip)
attached file was started in sandbox mode.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The editor is not supposed to remove the PvP rule from map saves.

**Comment by Lightforger** [comment]
So, if there is a cool map on a pvp server it cannot be edited to become a singleplayer map?
This would be rather useful to do test-attacks on a neutral wall, solo-conquer a large base in a long-running game or make schematics for that map.

**Comment by Anuken** [comment]
Yes.
