### ISSUE TITLE
PlayerBanEvent doesnt trigger when an admin bans in game.

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Anuken/Mindustry#4956]
**Platform**: *Linux (server)*

**Build**: *126.1*

**Issue**: It doesnt trigger on player bans when you do:
`
Events.on(PlayerBanEvent.class, event -> {
            // insert code
        });
`

**Steps to reproduce**: 
- Run a server with the modified example plugin
- Ban a player in game
- Look at console
- The message doesnt show up in console.

**Link(s) to mod(s) used**: 
*https://github.com/TranquillyUnpleasant/ExamplePlugin variant of the example plugin with the PlayerBanEvent*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
In-game player bans are IP-based; ID-based bans don't trigger, as the ID is already implicitly banned. Listen to `PlayerIpBanEvent`.

**Comment by TranquillyUnpleasant** [comment]
Shouldnt the event still trigger? Since the id is being banned, even if implicitly.

**Comment by Anuken** [comment]
After the IP ban, the player is already considered banned, so no further events are fired. 

I can reorder the in-game ban order to make ID-ban events slightly more reliable, but that doesn't really change how the events work for other cases.
