### ISSUE TITLE
Puzzle "router" option in language settings

### ISSUE THREAD

**Issue by PlotNarrater** [Anuken/Mindustry#4963]
I run the latest stable game purchased in steam, and find a puzzle option in language setting, named "router"

After chosen, all text in game was changed into "router", including "exit game"

I guess it was some testing codes? Or something with special usage? But it seems should not including in stable builds.

I check the code, it seems to be added by some init process of Vars.java

https://github.com/Anuken/Mindustry/blob/afd6570ceda5f63c0007642e6b743bf535ed5fe7/core/src/mindustry/Vars.java#L244

Thanks for checking it.

**Comment by Quezler** [comment]
its more of an easter egg if anything

**Comment by PlotNarrater** [comment]
yeah.

But I notice that language setting should be aproved after restart the game. Then if someone try this, he will loose the position for language selection. In that case, it is not fun.

So I just not think it as a easter egg at first.

Maybe make language option in setting menu not be replaced by "router" is a better idea?

**Comment by BlueWolf3682** [comment]
router

**Comment by PolloUsami** [comment]
router

**Comment by PlotNarrater** [comment]
I checked some more and find this is add in [this commit](https://github.com/Anuken/Mindustry/commit/c95872e9929cce685ca6b4fcad4e4f2de3def359#diff-edc9fcb969a6fc91db869b7bae26f0e1df24f737edc8901db44d438348465a38) 
Guess is used for a debug output for Core.bundle class init process

**Comment by joshuaptfan** [comment]
Same as if you are trying out another language you don't know for fun, memorize the menu button positions to change language before changing language.
