### ISSUE TITLE
@ tick gets reset when X-ing out of the game

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#4969]
**Platform**: Windows 10

**Build**: 126.1

**Issue**: If you exit the game with the [x] at top right, when reloading the map @ tick resets to 0.

**Steps to reproduce**:
- open a map
- place a processor with some code
- exit the game with x
- reopen save and check @ tick

**Link(s) to mod(s) used**: rftm, ldb, cliff

**Save file**: [sandbox.zip](https://github.com/Anuken/Mindustry/files/6176135/sandbox.zip)

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
![yes](https://i.kym-cdn.com/photos/images/newsfeed/001/628/719/085.jpg)

**Comment by Anuken** [comment]
> when reloading the map @ tick resets to 0.

that's exactly what it's supposed to do.

**Comment by Highfire1** [comment]
But @ tick doesn't reset when you save + exit ;-;

*I guess technically its slightly different but they're both exiting/reentering the map thus ought do the same thing imo*
