### ISSUE TITLE
Titanium Conveyors not Boosted by x2.5 from Overdrive Domes

### ISSUE THREAD

**Issue by 348joey** [Anuken/Mindustry#4970]
**Platform**: Windows

**Build**: steam build 126.1

**Issue**: Titanium conveyor belts do not move 2.5 times as fast under an overdrive dome

**Steps to reproduce**: I initially went into a lot more detail about the slight differences in speed for conveyors, bridges, junctions, phase conveyors, etc., but I realized that that was a bit extraneous and you probably already know all that, so I won't go into detail about it here.
Although this happens in a number of designs, I'll be using the one that gave me one of the closest actual measurement and also acts as a practical example of this bug affecting the game. I'll also be writing this report as I perform the test in-game at the same time to ensure all steps are written down.
I do the first two steps at the start of any bug test. They don't really affect anything here, but I figured I should mention them anyway.
Step one: I started a new map to ensure a clean slate. There are no extra resources or drills at the start; only a number of spaced out Core: Nucleus.
Step two: I drain my Core of any existing resources using item voids and unloaders. Once drained, I delete the unloaders and voids.
Step three: I build a Ground factory (set to Dagger), Additive, Multiplacative, and Exponential Reconstructors adjacent to each other and outputting to the next in the series. I then add item source blocks and a power source to supply the factory and the Additive and Multiplicative Reconstructors. I place silicon and plastanium item source blocks next to the Exponential Reconstructor and let it fill. This leaves the Exponential Reconstructor needing only titanium and cryofluid.
Step four: Once the Fortress mech is built and waiting in the Exponential Reconstructor, I add this:
bXNjaAF4nFWQW27DIBBFL+bhR17qKvrlj+6lG3BtEiHZxiWmafZeNR2YplVAzHA1nDsjsIURUHM3WehXOy0vNTZutVN79jH0FrvRvUc33OXT6tZudnFqez9/2KsP2C1xPNukh+hW7OM82HAc/aU9davFoQ9XfxyTx+Q+bfhzDD6uJPdvwQ2nf367+IsN937AMx0IDZhC0E1rRbKAoA1JgSoKWWtKtCUFBWkoacgiP0JJSZVIb2lJSTKDiopSZwcCFYOKaiLRGdSPoE5gBUOBDorbN7e9feW+BWpqqqhOsEaagnoZNjZsXLJx+Whc8kQVT1QxWDFYMVgzWDNY/II1gw3/QcNgk8CU8h9sGNwwKDL4Az9kPGQ=
(This is just a titanium belt line from a titanium source block connected to five Cryofluid Mixers with the excess running forward into the Exponential Reconstructor.) This ensures that it won't start out with any extra titanium.

Given an Exponential Reconstructor needs 750 titanium every 90 seconds, and the five Cryofluid Mixers together need 2.5 titanium/second, in total, the titanium belt here needs to supply 10.8333… titanium/second* (The extra second or two it takes to move the newly upgrade unit out and the next unit in makes it closer to, at best, ~10.65 titanium/second, which isn't enough to explain the discrepancy shown later on.)

**The Control Test** (No Overdrive Dome)

Once the Exponential Reconstructor has enough titanium to start upgrading, the control test begins. When the first upgrade finishes, there is  738 titanium left over in the machine. By the time the upgraded unit moves out out of the machine and the next unit moves in, this amount has passed the needed 750 allowing continuous production. This is more evident by the time the second upgrade has finished and the machine now has 740 titanium left at the exact point of completion. The amount left over will continue to increase with each upgrade finished. This excess can also be noticed if the Reconstructor starts with a full supply of titanium, as the belt will  stop for a split second before the next unit is in place and starts upgrading.

Result: A single titanium conveyor is more than capable of supplying five Cryotherium Mixers and an Exponential Reconsctructor enough titanium to allow continuous production, if only just barely. This makes sense, given its reported speed of 11 items/second.

**The Overdrive Test**
To show that an Overdrive Dome does not boost a titanium conveyor by as much as it does production buildings, I repeat steps three and four in a new area. I then add an Overdrive Dome with a power source and silicon and phaseweave item source blocks. I make sure to place it within range of all of the buildings in this test. Once the Exponential Reconstructor reaches 750, the test begins. This time, by the time the upgrade unit is out and the next unit is in place, there is only 637 titanium left in the machine, more than 100 titanium short. The extra second or two it gains from the time it takes to output the previous unit only raises this amount to 641, and it will continue to fluctuate by about 10 or so each upgrade cycle after that. As a result, it spends about five seconds idle waiting for titanium to fill up.

Result: A single titanium conveyor cannot supply the needed 27.08333… titanium/second to run five Cryofluid Mixers and an Exponential Reconstructor under an Overdrive Dome. Its speed is not increased from 11 items/second to 27.5 items/second.

Conclusion: This discrepancy has resulted in many builds that work without a dome, but don't worth with one. Conveyor bridges _are_ able to output about 27.5 items/second under an overdrive dome, and there's little in-game to lead me to believe that bridges are meant to be faster.

I suppose you could've also just placed an item source and item void on either end of a titanium belt under an Overdrive Dome and hovered over it to get an approximate item/second rating, but those fluctuate a bit, and I wanted to be more accurate.

**Link(s) to mod(s) used**: Vanilla Mindustry; no mods

**Save file**: 
[Overdrive Bug Report Save.zip](https://github.com/Anuken/Mindustry/files/6178690/Overdrive.Bug.Report.Save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. (I moved the map's save location to a new file and then sent it into a zip file before using the "Attach files by dragging & dropping, selecting or pasting them." thing at the bottom of this box.

**(Crash) logs**: Not Applicable

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** (Yes, I ran the game to recreate this. It said it was build 126.1 under the title)
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** (My search for "Overdrive" didn't yield any related results. The closest three were about how it affects the mass driver output, phase bridges, and conduits.)

**Comment by joshuaptfan** [comment]
FPS may be the culprit in the discrepancy, so reproducibility may depend on it. Overdrive domes may be (occasionally, briefly) driving titanium conveyors slightly beyond [their technical speed limit of 1 item/frame](https://discord.com/channels/391020510269669376/663853133587546138/808123670542155816).

**Comment by Anuken** [comment]
This won't be fixed. Your FPS is too low to update the conveyors with enough precision for perfect 250% speed.
