### ISSUE TITLE
I can't join a server yet i have good internet

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#4972]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

126.1

**Issue**: *Explain your issue in detail.*

I attempt to enter a server and it doesn't even try to enter the server i was able to enter servers before 126.1 so idk what happened

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Its not a reproducible bug something happened with the update and it just broke my ability to join servers

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods and no relevant zip files

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

This happened in the server menu not in game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 1ARC1** [comment]
*if its not reproducible Anuke will most likely close it.*

**Comment by Anuken** [comment]
Nobody else has this issue. Likely a problem with your device/internet/server.
