### ISSUE TITLE
Wall press = bullets with odd velocity

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry#4974]
**Platform**: *Windows*

**Build**: *126.1.*

**Issue**: *Bullets inherit nonexistent velocity if a unit is pressing itself against a wall.*

**Steps to reproduce**: *Get a unit to press itself against a wall. Make it shoot. The bullet will be affected by the movement, but the unit itself will not be moving.*

**Link(s) to mod(s) used**: 
*[DeltaNedasldb.zip](https://github.com/Anuken/Mindustry/files/6184547/DeltaNedasldb.zip)
[DeltaNedasoverride-lib.zip](https://github.com/Anuken/Mindustry/files/6184549/DeltaNedasoverride-lib.zip)
[deltanedasui-lib.zip](https://github.com/Anuken/Mindustry/files/6184550/deltanedasui-lib.zip)
[deltanedasunit-factory.zip](https://github.com/Anuken/Mindustry/files/6184551/deltanedasunit-factory.zip)
[Homebrew.zip](https://github.com/Anuken/Mindustry/files/6184552/Homebrew.zip)
[rtfm-master.zip](https://github.com/Anuken/Mindustry/files/6184553/rtfm-master.zip)
[WaterUnits+.zip](https://github.com/Anuken/Mindustry/files/6184554/WaterUnits%2B.zip)*

**Save file**: *[save.zip](https://github.com/Anuken/Mindustry/files/6184570/save.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate + not a bug.
