### ISSUE TITLE
Crash when trying to use Angles.randLenVectors in an effect

### ISSUE THREAD

**Issue by QmelZ** [Anuken/Mindustry#4975]
**Platform**: Windows 10

**Build**: 126.1

**Issue**: The game crashes when using `randLenVectors` in an effect

**Steps to reproduce**:
1. Make any mod with an effect that uses `randLenVectors` (or download the one i provided below)
2. Trigger the effect in game

**The mod and the save file**: [mod+save.zip](https://github.com/Anuken/Mindustry/files/6185229/mod%2Bsave.zip) (shoot with a duo to trigger the effect)

**(Crash) logs**: [crashlog.txt](https://github.com/Anuken/Mindustry/files/6185232/crashlog.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Use Java 8.
