### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by Skilifer** [Anuken/Mindustry#4984]
Windows 10
Build 126.1
Connected to the server and after a short time I got this error
Just go to the server "2R2T"
0 Mods
[data.zip](https://github.com/Anuken/Mindustry/files/6199515/data.zip)

![Снимок экрана 2021-03-24 195320](https://user-images.githubusercontent.com/66203563/112360221-20c24700-8ce3-11eb-9728-dbc419a707b2.png)

**Comment by Anuken** [comment]
Cannot reproduce, likely caused by a plugin.
