### ISSUE TITLE
Mac OS Version reporting as "Damaged"

### ISSUE THREAD

**Issue by Mesi1010** [Anuken/Mindustry#499]
Mac OS reports the issue as either modified or damaged, citing that it does not match the original signed code.

**Comment by Anuken** [comment]
I have no package issues on my Mac laptop. Which version of OSX are you using?

**Comment by Mesi1010** [comment]
High Sierra 10.13.6, I should have specified that! Sorry!

**Comment by Mesi1010** [comment]
I figured it out! It's a problem with the Unix executable. I used the Unix executable from an earlier version of the game (V4, build 63), and it booted up just fine, so something is up with it in the latest version.

**Comment by ritzip** [comment]
You should close this now...
