### ISSUE TITLE
Giving a unit multiple ForceFieldAbility s causes issues.

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#4992]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

126.1

**Issue**: *Explain your issue in detail.*

Giving a unit multiple ForceFieldAbilities will make the shields regenerate at the same time, regardless of different cooldown times.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Open Mindustry, add multiple ForceFieldAbilities with different cooldowns to a unit, and have enemy turrets fire at you. When your shield regenerates, instead of just the one with the shortest cooldown regenerating, all of them regenerate. Example code: `UnitTypes.gamma.abilities.add(new ForceFieldAbility(10, 1, 1000, 60*5))` `UnitTypes.gamma.abilities.add(new ForceFieldAbility(50, 1, 1000, 60*20))` `UnitTypes.gamma.health = Infinity`

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

Not applicable, this issue happens with vanilla.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[savefile.zip](https://github.com/Anuken/Mindustry/files/6205688/savefile.zip)
(Latest saved custom game)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Multiple abilities of the same type are not supported.

**Comment by BlueWolf3682** [comment]
This is because the force field all overrides the same thing (unit shield)
*this causes an issue with units with ShieldRegenFieldAbility to cause a force restart of unit force fields*
