### ISSUE TITLE
I was in multiplayer when my friend researched the last item I needed to get the Researcher achievement and now I can't get it. Love this game, btw! Keep it up!

### ISSUE THREAD

**Issue by JesseMeiring** [Anuken/Mindustry#4997]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GlennFolker** [comment]
✨

**Comment by Bohaska** [comment]
... the issue creator seems to be absurdly lazy
