### ISSUE TITLE
Maps in campaign do not update when they are changed in later updates and have been launched to before the update was applied

### ISSUE THREAD

**Issue by Bohaska** [Anuken/Mindustry#4999]
**Platform**: *Android/iOS/Mac/Windows/Linux*
MacOS (Big Sur)
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.1
**Issue**: *Explain your issue in detail.*
When a sector is updated or changed in any way, the game doesn't update the map accordingly
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Download a beta v6 version of mindustry through itch.io client
2. Launch to sector 214 (At that version, it was an enemy base next to frozen forest)
3. Update to latest version
4. You would see that the enemy bases nearby haven't disappeared, they just have not been labeled as an enemy base on the planet (Because of this, I launched to what I thought was a easy sector and failed to capture this sector)
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
All mods were disabled. The mods were https://github.com/deltanedas/rtfm, https://github.com/deltanedas/dev-mode and https://github.com/DeltaNedas/ui-lib
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE HAPPENS IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[campaign.zip](https://github.com/Anuken/Mindustry/files/6209411/campaign.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

Not needed
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **This is issue 4999, which happens to be an issue with a prime number.**

**Comment by Bohaska** [comment]
Note: This bug isn't easily reproducible, for mostly obvious reasons.

**Comment by Anuken** [comment]
Not a bug. Sectors don't magically delete their own saves and recreated themselves with new data.

**Comment by joshuaptfan** [comment]
You can delete individual campaign sector saves to force them to be regenerated, but it requires save file manipulation.

**Comment by Bohaska** [comment]
> Sectors don't magically delete their own saves and recreate themselves with new data.

Small question: Would they be better if sectors did this?

**Comment by Anuken** [comment]
> Would they be better if sectors did this?

They *can't* do that, so the question is irrelevant.
