### ISSUE TITLE
can't spawn on multiplayer mode

### ISSUE THREAD

**Issue by MrZoid** [Anuken/Mindustry#5005]
**Platform**: Windows

**Build**: 126.1

**Issue**:  i recently join my friend but i can't see where is my drone, my friend's drone and the enemy, i also can't build. it's like iam in pause mode but i can see my friend building something.

**Steps to reproduce**: after a long time ago i played with my friend then i come back to play it again then it happen.

**Link(s) to mod(s) used**: -

**Save file**: 
[Uploading bruh.zip…]()

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Catchears** [comment]
That's not a save file.

**Comment by Anuken** [comment]
No save, no screenshot, no data.
