### ISSUE TITLE
Discord ping sound

### ISSUE THREAD

**Issue by HerrBach2001** [Anuken/Mindustry#5007]
platform: Window s64 bit

build: 126.1

Issue: When the countdown to the enemies appearing reaches 0, I hear every time many Discord pings.

I think the problem is that I installed Mindustry on my USB Drive.

[zipdata.zip](https://github.com/Anuken/Mindustry/files/6215975/zipdata.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nichrosia** [comment]
What mods do you have installed?

**Comment by HerrBach2001** [comment]
I play without any mods

**Comment by nichrosia** [comment]
Can you send a screenshot of your `%APPDATA%/Mindustry/mods` directory just to confirm this?

**Comment by Anuken** [comment]
Won't fix.

**Comment by Laggyboi0701** [comment]
> I play without any mods

are you sure?

**Comment by Laggyboi0701** [comment]
"do not the anuke" mod has discord pings

**Comment by HerrBach2001** [comment]
I found the Issue I forgot to delete the old Mindustry file in Appdata (there was the "do not the anuke"  mod)
