### ISSUE TITLE
In Logic processors, using "Unit Locate" on enemy blocks returns null for "building", even when "found" is 1.

### ISSUE THREAD

**Issue by NoExit4U** [Anuken/Mindustry#5015]
**Platform**: Windows

**Build**: steam build 126.1

**Issue**: Unit Locate on enemy blocks returns null for "building", even when found returned "1".

**Why I think this is a bug**: It's restricting what is possible with a Logic Block and is counter-intuitive.

As an example: I'm making a patrolling AI Horizon that will bomb nearby enemy turrets until the turret is dead.

Using a new "Unit Locate" to see if it is still alive is a workaround but can sometimes return a different turret because it's a Horizon and it's moving around the target.

There may also be other use cases for this, for example when wanting to know what type of turret the block is or if it is shooting or where it is aiming.

**How I tested the issue**:
This is tested with the following Logic code:
![20210328172717_1](https://user-images.githubusercontent.com/75215867/112757983-53728500-8fec-11eb-99cb-721ad304a643.jpg)

The message: (there are 6 enemy Cyclones above)
![20210328171911_1](https://user-images.githubusercontent.com/75215867/112757997-64bb9180-8fec-11eb-8150-3d0fa5fe8021.jpg)

When changing the "enemy" to "false", it can find the Duo turret:
![20210328172107_1](https://user-images.githubusercontent.com/75215867/112758039-87e64100-8fec-11eb-974a-1050a7ce8022.jpg)

**Steps to reproduce**: Open the save file and look at the message block.

**Link(s) to mod(s) used**: None were used.

**Save file**: [591.zip](https://github.com/Anuken/Mindustry/files/6217567/591.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug. The logic block intentionally prevents you from getting enemy buildings; otherwise, you would be able to remotely read arbitrary enemy structure information across the map.

**Comment by NoExit4U** [comment]
Reading arbitrary enemy (and friendly) structure information across the map is exactly what I'm trying to do as a map maker.

Except for the content of a Core and maybe Power related sensors, I don't see a lot of reasons why sensors like Health, Team, Name, and Type should not be possible.

**Comment by Anuken** [comment]
> Except for the content of a Core and maybe Power related sensors, I don't see a lot of reasons why sensors like Health, Team, Name, and Type should not be possible.

There is no way to prevent using "overpowered" sensors like items and power without being even more un-intuitive and arbitrary.

Even reading health of the enemy core *across the map* is overpowered. I would rather not have any building returned at all.

**Comment by joshuaptfan** [comment]
IMO enemy building presence (basic "exists and is alive") should be detectable, just not any stats, like health.
