### ISSUE TITLE
Auto save error

### ISSUE THREAD

**Issue by NEON-XZR** [Anuken/Mindustry#5017]
**Platform**: *Android
**Build**: *Release build 126.1

**Issue**: *Auto save still not saving automatic even though it was turned on.*

**Steps to reproduce**: *Just playing Mindustry like usual until release build 125*

**Link(s) to mod(s) used**: *None*

**Save file**: *
[export[1].zip](https://github.com/Anuken/Mindustry/files/6218634/export.1.zip) (im just renew it)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *None*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works fine for me, can't reproduce.
