### ISSUE TITLE
Mod Doesnt delete

### ISSUE THREAD

**Issue by Hot-Sausage07** [Anuken/Mindustry#5019]
So mods doesnt delete
i download many mods then i play again
so the game freezes for a long time
i exit it and i go and play mindustry again
it shows that mindustry disable all mods
now i tried to delete them but it said "file may in use, unable to delete"
now i enable 1 mod and restart
then i tried to delete, it doesnt anymore work all mods cant be deleted so a big problem
i enable and disable, not anymore it doesnt delete the mods

**Comment by Quezler** [comment]
use the format, we have no idea what platform you're on 🙄

**Comment by DeltaNedas** [comment]
windows users be like
