### ISSUE TITLE
About TileOp on editor/DrawOperation.java

### ISSUE THREAD

**Issue by tucan9389** [Anuken/Mindustry#502]
Hi again! I have a question on `editor` module.
The DrawOperation class uses `TileOp` but It isn't defined anywhere. I think `TileOp` could be `TileOpStruct` located on the bottom of [`editor/DrawOperation.java`](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/editor/DrawOperation.java). Could you give me some advice?
In addition, `gen.TileOp` module couldn't be found on [`editor/DrawOperation.java`](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/editor/DrawOperation.java). 

<img src=https://user-images.githubusercontent.com/37643248/58453639-e1faee80-8156-11e9-9b43-25011d7b185c.png width="50%">

<img src=https://user-images.githubusercontent.com/37643248/58453634-d9a2b380-8156-11e9-8cc0-7f6223cedd37.png width="100%">

**Comment by Anuken** [comment]
Everything in the `gen` package is autogenerated code produced by annotation processors. `TileOpStruct` is the struct definition for the `TileOp` class.

**Comment by tucan9389** [comment]
I see! 😎
When the annotation processors are run? In compile time?

**Comment by Anuken** [comment]
Yes.

**Comment by tucan9389** [comment]
Thanks a lot
