### ISSUE TITLE
Logic display wrong alpha color

### ISSUE THREAD

**Issue by Alstin112** [Anuken/Mindustry#5022]
**Platform**: *Windows*

**Build**: *126.2*

**Issue**: *I went to draw a transparent triangle with the **logic-processor**, it started to flickering, I tested some more combinations and saw that the `clear 0 0 0` made the colors of the drawings flickering , in that I tried to use the
```
color 0 0 0
rect 0 0 176 176
```
but I found another bug, the colors of the object are wrong, white when transparent is very light and even transparent black is lighter than black
![image](https://user-images.githubusercontent.com/42156649/112900264-a2d2b700-90b9-11eb-93bd-e6751984bd46.png)
*

**Steps to reproduce**: *Build a Logic Processor, connect with large display, and write
```
draw clear 0 0 0 0 0 0
draw color 255 255 255 128 0 0
draw triangle 0 0 176 0 0 176
drawflush display1
```
and the triangle will start to blink or write
```
draw color 0 0 0 255 0 0
draw rect 0 0 176 176 0 0
draw color 0 0 0 128 0 0
draw triangle 0 0 176 0 0 176
drawflush display1
```
and the triangle will appear
*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: [map.zip](https://github.com/Anuken/Mindustry/files/6224548/map.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> saw that the clear 0 0 0 made the colors of the drawings flickering

This doesn't happen to me. You were likely writing to the display with two processors.

> transparent black is lighter than black

It's not. Drawing with transparency makes the image transparent, which allows the lighter display background to shine through.

**Comment by Alstin112** [comment]
Sorry for the late response, but this bug still occurs in build 146.
And all that i said depends of fps.

The alpha colors are 1, 64, 128, 196, 255. All for the same white.
https://github.com/Anuken/Mindustry/assets/108550823/8519bd95-bdd6-4098-aac2-0d673a3e01eb
https://github.com/Anuken/Mindustry/assets/108550823/31d3118c-19a7-4a92-b118-cfaf70542262
(i can't record the mindustry with 60fps)
![image](https://github.com/Anuken/Mindustry/assets/108550823/7aff6613-9cf4-4236-8fc0-2622d8a81f1b)
![image](https://github.com/Anuken/Mindustry/assets/108550823/2167cc71-9b8b-46a4-87cf-7a1353ea870f)

as you see, the colors at same alpha still are diferente depending of the processor. 
I am sending the map if you still wanna try.
[ColorBug.zip](https://github.com/Anuken/Mindustry/files/13762869/ColorBug.zip)

**Comment by mahdoosh1** [comment]
hey if you are flushing multple times, layers will overlay and brighten previous screen color

for example if you color a black screen with white 50% alpha value twice, it will be multiplied and screen will be 75% white

here is formula if alpha is from 0 to 255:

color = (prevcolor*(255-alpha)+new*alpha) ÷ 255


and over laying 50% twice is (after simplification):

`color = prevcolor*0.25+new*0.75`

**Comment by Alstin112** [comment]
i know this, but i clear between the two flushes, it shouldn't behave like this.
If you wanna try, this is the code.
```asm
draw clear 0 0 0 128 0 0
draw color 255 255 255 128 0 0
draw triangle 0 0 0 80 80 0
drawflush display1
```
