### ISSUE TITLE
Steam generator light persistence without water

### ISSUE THREAD

**Issue by RusLeonid** [Anuken/Mindustry#5025]
**Platform**: Android

**Build**: 126.2

**Issue**: Steam generators light up surroundings if fuel is provided and water input is cut off

**Steps to reproduce**:
-Place the steam generator and connect fuel and external water inputs to it
-Disconnect the water input, and wait until water level in the generator reaches its minimum
-The bug happens with fuel in the generator's inventory, you may disconnect the fuel input
![Screenshot_20210330-104353](https://user-images.githubusercontent.com/81614288/112957533-2f2cba80-914a-11eb-9bf8-aed99f7dfff6.jpg)

**Link(s) to mod(s) used**: None

**Save file**: 
[steamlightbug.msav (1).zip](https://github.com/Anuken/Mindustry/files/6227466/steamlightbug.msav.1.zip)
 *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RusLeonid** [comment]
Consistently happens when set up, inconsistently persists through saves

**Comment by liuxilu** [comment]
And differential generator.
