### ISSUE TITLE
Carried node bug

### ISSUE THREAD

**Issue by srtubaki** [Anuken/Mindustry#5030]
**Platform**: *Android/Windows*

**Build**: *126.2*

**Issue**: *After connected and then disconnected by the transport of a node by Mega, Disconnected nodes behave as if they are still connected.*

**Steps to reproduce**: *Place the two nodes that are not connected to each other, one block apart.
Step 1: Drop a node between the two nodes by Mega
Step 2: Take the dropped node

The power network is now divided into two, but the addition of batteries, power supplies, and power consumption blocks affects both sides.
If blocks that are connected on one side are removed or destroyed, only that side will seem to be back to normal.

After Step 2.
Step 3: Add a power source and a battery to one side.
Step 4: Disconnect the battery from the power source.
Step 5: Connect the battery to a power void and then disconnect it.

The battery will behave as if it is connected to the power source and will be fully charged immediately.*

**Link(s) to mod(s) used**: *None*

**Save file**: *[carriedNodeBug.zip](https://github.com/Anuken/Mindustry/files/6233247/carriedNodeBug.zip)*

Translated with www.DeepL.com/Translator (free version)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. Running the exact steps specified does not lead to any anomalies, and neither do other variants.

![image](https://user-images.githubusercontent.com/10100000/113078935-13550300-91a2-11eb-8b50-b06d916cdf12.png)

After a node was dropped and removed from the middle, the power graphs were still distinct. Tested several times.

**Comment by srtubaki** [comment]
Can't reproduce the bug using this schematic?
[node-bug-reproduser.zip](https://github.com/Anuken/Mindustry/files/6240165/node-bug-reproduser.zip)
