### ISSUE TITLE
iOS update from App Store treated as custom build

### ISSUE THREAD

**Issue by ChooTingFeng** [Anuken/Mindustry#5034]
**Platform**: *iOS*

**Build**: *126.2(?)*

**Issue**: *The latest (as of this report) download from the iOS App Store, which says it's 126.2, when launched, says its a custom build under the title in orange text.

Attempting to join a server gets denied due to the server not support custom versions and tells you to download an official version. But this is an official version.*

**Steps to reproduce**: *Download Mindustry from the Apple App Store*

**Link(s) to mod(s) used**: *None.*

**Save file**: *Not Applicable.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Not Applicable.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
@BlueWolf3682 can you confirm?

**Comment by Anuken** [comment]
iOS build script was broken; this has been fixed, but you'll need to wait for the new version to pass review again.

**Comment by BlueWolf3682** [comment]
> @BlueWolf3682 can you confirm?

My iPod is dead, I haven't used it in a while
