### ISSUE TITLE
Can't spawn on steam invite multiplayer game

### ISSUE THREAD

**Issue by MrZoid** [Anuken/Mindustry#5035]
**Platform**: Windows

**Build**: 126.2

**Issue**: my drone or my friend's drone can't spawn, the only one can play it is the host. the problem only happen if ur a client. it's like iam in spectating mode, i can't see my friend's drone, my drone and the enemy, and also i can't build, but i can see what was my friend building
![20210331172546_1](https://user-images.githubusercontent.com/52745539/113130726-962f9980-9246-11eb-9b51-b80a00d362dd.jpg)

**Steps to reproduce**: it happen only if i joined my friend through steam invites, the problem only occur on the client and it's also happening on my friend when my friend joined me

**Link(s) to mod(s) used**: -

**Save file**: 
[prob.zip](https://github.com/Anuken/Mindustry/files/6235896/prob.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Tried connecting to some people through Steam, and it worked fine. Likely a temporary issue with Steam.
