### ISSUE TITLE
Please show a warning if more than 1000 Script-Lines are imported into a processor Block

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry#5037]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: If you import more than 1000 lines into a script block, all lines after the 1000th line are silently deleted. 
**Please display a warning**, so that one still can vier the generated script in the Game itself.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. Place a Micro Processor on the Map
2. Edit the Script
3. Import from Clipboard: **more** than 1000 Lines
4. Mindusty silently 😞 deletes all lines after the 1000th line 

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[4.zip](https://github.com/Anuken/Mindustry/files/6238966/4.zip)

**Crash report**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug.

**Comment by schittli** [comment]
Hello @Anuken 

thank you for your answer. 
While I'm already in contact: congratulations on your source code, it's great written and structured.

But: Of course it is a bug, because the game offers the "Import Script from Clipboard" command - but it does not do so reliably / without errors. If it's not a bug, then you should call it "Import max. 1000 Lines from the Clipboard", so everything is clear :-)

For your users, this error is extremely annoying because they search for logic errors for a long time until they realise that Mindustry does not do what it claims to do.

**Comment by Anuken** [comment]
> But: Of course it is a bug

Of course it's not. This behavior was never supposed to be in the game. It is entirely expected behavior to me, and as the developer, I am the one who decides what is and isn't a bug.

> this error is extremely annoying because they search for logic errors for a long time until they realise that Mindustry does not do what it claims to do.

It's not an error, and Mindustry doesn't claim *anything* about the "import to clipboard" feature. It is **not** reasonable to assume that processors have unlimited code blocks. A feature not living up to your expectations isn't a bug.

There is absolutely no requirement for me to explicitly disclose every limitation of the game.

**Comment by sample-text-here** [comment]
have you considered making a [feature request](https://github.com/Anuken/Mindustry-Suggestions/issues/new?assignees=&labels=feature+request&template=feature-request.md&title=please%20show%20a%20warning%20if%20more%20than%201000%20script-lines%20are%20imported%20into%20a%20processor%20block )?
