### ISSUE TITLE
Processors can alter the draw color of other separate processors

### ISSUE THREAD

**Issue by FlippingPotatoes** [Anuken/Mindustry#5044]
**Platform**:

Windows and iOS tested

**Build**: 126.3 (iOS) & 126.2 (windows)

**Issue**: Given 2 processors connected to the same display, processor 1 draws a circle, but doesn’t set its color, processor 2 draws a square and sets its color to green, the end result is that both the circle and the square end up green.

Effectively, once a processor encounters a draw flush line, it’s fair game to overwrite its color unless it specified it again (and of course it will overwrite other processors)

I apologize if for whatever reason this is intended behavior, but it seems unintuitive and contradictory to the established notion of being unable to alter the internal values of another processor (without said processor directly reading values from a third party, but these processors aren’t intentionally grabbing these colors from a display, it’s forced onto them)

Especially because the in game description says that it will “set color for next drawing operation” which doesn’t hint that this would exist.

**Steps to reproduce**: draw color and draw flush in one processor, draw anything else and draw flush in another processor (to the same display)

**Link(s) to mod(s) used**: none

**Save file**: My apologies, I created this on my phone, which won’t let me easily link this file, instead here’s a schematic which I had another user test to confirm it’s function

bXNjaAF4nGNgZ2BjYmDJS8xNZeBxzs/JL1LwzazIzEtn4E5JLU4uyiwoyczPY2BgYuDPzUwuytctKMpPTi0uzi9iEM5JLEpP1c3JT89M1k3JLC7ISaxkYGBgZgABPiC2q5iTnJKQcMFX00snXOPE+ZUhBqYMisrMrMnMrApPmE4ueTpFLF1jSYqY+BOVMKkiRlMDo4IDO3jO8PgwuKoKXACbwwoyyB9i0AcfsEFevnqBGwwCDEyMAgzMAwzMAhic9DaEFNX51QlOyE7J4lJXDMq0XHpUkktz5lFWy86pbTEOhyUkLRJi2J79r2cs3yi5lYER6EomBgYAWA1KTw==

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
this might have been fixed a few days ago, could you test this on bleeding edge?

**Comment by FlippingPotatoes** [comment]
Can confirm that the bleeding edge still has this issue (build 20996)

![image](https://user-images.githubusercontent.com/75582921/113411092-ef044c80-9382-11eb-80b1-03d9b4dd9e6a.png)

(color operation only happening in top processor, both shapes printed green)

Also, cuz I'm now on pc, here's the world download (not that it really helps in this case)

[DisplayDemo.zip](https://github.com/Anuken/Mindustry/files/6249244/DisplayDemo.zip)

**Comment by Anuken** [comment]
Color is set *for the display*, not the processor. Don't use multiple processors with one display.

**Comment by hsaturn** [comment]
As Anuken said, I find this fair. Color is an atrribute of a screen, not a processor.
It is a chance that two processors can render in a single display. I'm using this for rendering a graph (history of power). Each processor renders the half of the graph.
--> But this could change in future and this 'multi threading rendering' could be broken a day, even if its cool.
