### ISSUE TITLE
Mass driver issue

### ISSUE THREAD

**Issue by Dioo0** [Anuken/Mindustry#5045]
*Platform*: android

*Build*: 126.2 

*Issue*: Mass driver has item capacity 120. but sometimes it has more than 120

*Steps to reproduce*: ![Screenshot_20210402-093705_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/78714307/113379348-0fd89c00-939b-11eb-9c73-1ebe9cd7ddd6.jpg)
make same thing then click one of central mass drivers and spectate(this is not only way to reproduce, sometimes it happens in casual game)
![massdriverissue](https://user-images.githubusercontent.com/78714307/113380293-a312d100-939d-11eb-9339-1b751785d075.jpg)

*Link(s) to mod(s) used*:https://github.com/sk7725/TimeControl
https://github.com/DeltaNedas/ui-lib

*Save file*:[mass driver.zip](https://github.com/Anuken/Mindustry/files/6247648/mass.driver.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.(plsno)

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.  
- [X] *I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.*
- [X] *I have searched the closed and open issues to make sure that this problem has not already been reported.*

**Comment by Anuken** [comment]
Not a bug. Item drivers can store extra items when accepting.

**Comment by Dioo0** [comment]
but-
this is awkward
max=120, but they can have more
