### ISSUE TITLE
A different mass driver issue

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#5048]
**Platform**: *Android/iOS/Mac/Windows/Linux*
 
 Windows/steam
 
**Build**: *The build number under the title in the main menu. Required. 

126.3 of steam 

**Issue**: *Explain your issue in detail.*

If there are multiple mass drivers shooting in a chain into one receiver and for whatever reason one of the drivers gets depowered the entire chain stops shooting. In the image below (and save file) if you disconnect the middle mass driver the chain will continue shooting. I deleted and rebuilt the chain and now if I disconnect the far rightmost driver the chain will still continue shooting. It is very inconsistent, but the majority of the time the drivers all just stop shooting.

![20210402130553_1](https://user-images.githubusercontent.com/31638088/113446039-322ae380-93b4-11eb-8492-bf87318e9eee.jpg)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Setup multiple mass drivers shooting into one driver with incinerators/voids. Once everything is running depower one mass driver and watch all the drivers stop shooting. If it continues shooting repower that driver and DC a different one. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

https://github.com/MEEPofFaith/testing-utilities
https://github.com/MEEPofFaith/TimeControl
https://github.com/MEEPofFaith/unit-factory

**Save file**: *The (zipped) save file you were playing on when the bug happened.

[mass driver.zip](https://github.com/Anuken/Mindustry/files/6250926/mass.driver.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

It hath been removethed.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

crash.exe i dunno
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Once everything is running depower one mass driver and watch all the drivers stop shooting.

Sounds like the destination driver keeps waiting for the unpowered driver to shoot, which never happens. This isn't a bug - there is no system to "time out" mass drivers, or change the queue order. Keep your drivers powered, or deal with the consequences.

**Comment by the-red-soul** [comment]
the wierd thing is that its inconsistent, you can depower one of them at random and the entire chain is still shooting

**Comment by Anuken** [comment]
If the mass driver is not in the queue to shoot when disconnected, the destination driver never waits for it, because unpowered drivers don't request alignment.
