### ISSUE TITLE
Enemy units not working properly in latest build.

### ISSUE THREAD

**Issue by DevChrome** [Anuken/Mindustry#505]
Enemy bots are broken in the latest bleeding edge build on Android.

In campaign levels, the enemy bots spawn each wave, but don't move at all.

To reproduce:
1) Start a campaign level.
2) Wait for, or skip to, the first wave.
3) Go to the enemy drop point.
4) Enemies shoot at you but don't move.

![](https://i.imgur.com/LST57VF.png)
![](https://i.imgur.com/or4WHpV.png)

In free play maps, the enemies don't spawn in the waves.

To reproduce:
1) Start a free play level.
2) Wait for, or skip to, the first wave.
3) Go to the enemy drop point.
4) Enemies are not there or anywhere else on the map. Even the red markers showing enemies are absent.

![](https://i.imgur.com/8nZY52b.png)
![](https://i.imgur.com/XMKt9TY.png)

I've only checked this on Android. Not sure about other platforms.

**Comment by Anuken** [comment]
Are you running the **very** latest commit?

**Comment by Anuken** [comment]
This was already fixed in an earlier commit.
