### ISSUE TITLE
Can't zoom in/out when holding a schematic

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#5051]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.2, but this has been going on for a long time. I just keep forgetting.

**Issue**: *Explain your issue in detail.*
You can zoom in/out with the middle-mouse wheel. However you can't do this when you're holding a schematic or you copy blocks for a schematic. You can however still zoom in/out when holding a building that isn't for a schematic. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Click on a building on the right GUI but don't place it.
Move the middle-mouse button and you'll see you can zoom in/out.

Middle-click a building on the map.
Again move the middle-mouse button and you'll see you can zoom in/out.

The above steps were for clarification. Now for the actual bug:

1a. Either select a region containing buildings with the "select region" key. The save schematic button will now be visible. OR
1b. Open the saved schematics menu a click a schematic as if you intend to place it down (but don't place it).
2. You should see a schematic highlight ready to place and build. Don't place it!
3. Move the middle-mouse wheel to zoom. You can't zoom. This is the bug.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
https://ufile.io/z2lbw8xj
This bug affects everywhere. It doesn't matter the save file.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RusLeonid** [comment]
inb4 someone reports this to happen with conveyors

**Comment by Bohaska** [comment]
I also have the same bug

**Comment by Wh4tev3r** [comment]
Try scroll while pressing **Ctrl**

**Comment by Anuken** [comment]
Not a bug.

**Comment by RedstonerKBC** [comment]
Bruh, at least tell me why not...

**Comment by Anuken** [comment]
That has already been explained.

> inb4 someone reports this to happen with conveyors
> Try scroll while pressing Ctrl
