### ISSUE TITLE
Notification Center causes game to crash

### ISSUE THREAD

**Issue by yetyeeter1337** [Anuken/Mindustry#5053]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: the game crashes when you pull down the Notification Center during a game in campaign, only happens with mods installed

**Steps to reproduce**: go into campaign or a game and quickly pull down the Notification Center and the game will quit

**Link(s) to mod(s) used**: `[Aureus/exogenesis:[blue]1.0, Devs: K103908, BlueWolf, MEEP Of Faith, AndromedaFallen
Contributors: Quezler, VozDuh/exotic-mod:0.1 Alpha, SlugCat/heavy-arsenal:1.0.1 alpha, ColdAnkles/trade-terminals:2.0]`

**Save file**: I am unable to get the save file due to the limited file access on IOS

**Crash report**: I am unable to supply this file for the same reason

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DeltaNedas** [comment]
if anuke cant replicate this you are out of luck.
pretty sure you can get logs in-game.

**Comment by yetyeeter1337** [comment]
> if anuke cant replicate this you are out of luck.
> pretty sure you can get logs in-game.

It’s easy to replicate this on mobile

**Comment by Anuken** [comment]
> only happens with mods

This is an issue with your mods, won't fix.

**Comment by yetyeeter1337** [comment]
> > only happens with mods
> 
> This is an issue with your mods, won't fix.

Okie, just making sure, thanks (:
