### ISSUE TITLE
Autosave doesn't work on Android

### ISSUE THREAD

**Issue by RandomEngy** [Anuken/Mindustry#506]
I looked in the settings and it says my autosave is set to 90 seconds. But I've never seen it actually do an autosave. I start a map, place a bunch of turrets, then turn the phone to sleep to go do something. I come back and my progress is wiped and when I go to "Load" there are no entries.

Ideally it should be saving when the game is suspended so no progress is lost. Kind of a crippling issue for me.

**Comment by ritzip** [comment]
Have you turned on autosave?

**Comment by RandomEngy** [comment]
I have not changed the autosave setting. When I go to Settings -> Game it tells me the current Autosave interval is 90 seconds.

**Comment by ritzip** [comment]
Well, you have to save it, then turn autosave on.

**Comment by ritzip** [comment]
![image](https://user-images.githubusercontent.com/49394064/58562636-33d96c80-825c-11e9-88a1-11ea69eb9536.png)

**Comment by RandomEngy** [comment]
Okay, thanks. I've never seen a game require an initial manual save before starting autosaves.

**Comment by ritzip** [comment]
No problem, you can close this now...

**Comment by CKHammer** [comment]
isn't it always turned on when first saved in a new slot?

**Comment by RandomEngy** [comment]
Yep. I was just starting a new game and playing without making a save slot. I was expecting it to work like most other games and let you continue from where you left off.

**Comment by CKHammer** [comment]
oh lol

**Comment by RandomEngy** [comment]
I have to agree, preventable data loss is pretty funny.
