### ISSUE TITLE
Logic link weirdness

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#5063]
**Platform**: Windows

**Build**: 126.2

**Issue**: Logic link ids don't persist through reloads, this can cause issues when changing around links and desyncs on servers.

**Steps to reproduce**: Link both switches to the processor, unlink switch1 and reload the world, notice that switch2 is now switch1 [seen here](https://yagpdb.is-ne.at/Fs62g4.webm)

**Save file**: [352.zip](https://github.com/Anuken/Mindustry/files/6259927/352.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0 branch
