### ISSUE TITLE
Memory leak MP

### ISSUE THREAD

**Issue by jixxed** [Anuken/Mindustry#5064]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Game freezes after some time of gameplay. Game using 16GB ram. PC runs out of memory. Task manager unable to kill the process. hard reset of PC required.*

**Steps to reproduce**: *Play the game with a friend. I am the client, other player host. Game freezes after sometime. Game using 16GB ram. PC runs out of memory. Happened twice. map: Nuclear Production Complex.
Also noticed game state is different on both client and host, specifically items in pipes and belts. had a couple of mixups, and after cleaning for 1 client it all looks good, while the other client still sees mixed item on belts or liquids in pipes. (might be related)
*

**Link(s) to mod(s) used**: *no mods*

**Save file**: *[sector-serpulo-130.msav-backup.zip](https://github.com/Anuken/Mindustry/files/6260699/sector-serpulo-130.msav-backup.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *NO crash logs available*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. Joined random servers through Steam, did not experience any memory leaks after a while. If this were a general issue, I would likely see other posts on the Steam community (or Github) discussing it, but there are none. Without a memory dump, I can't investigate this further.

> Also noticed game state is different on both client and host, specifically items in pipes and belts. had a couple of mixups

This is normal - conveyor items are not synced, so you may have to do `/sync` occasionally when managing items.
