### ISSUE TITLE
Placing a logic with lots of lines causes the schematic not to be built until that processor is removed

### ISSUE THREAD

**Issue by Freakzarer** [Anuken/Mindustry#5065]
**Platform**: Windows

**Build**: v6.0 Build 126.2

**Issue**: Building a processor with a lot of lines can cause it not to be able to be built, from my testing, it only happens when on a multiplayer server, was able to reproduce it consistently on .io survival server, some of the members of the server also experienced such problems, this has the same symptoms to issue https://github.com/Anuken/Mindustry/issues/3438 but without getting kicked, does not happen on singleplayer

**Steps to reproduce**: Join a server, for my test, I use .io's survival server, then build the logic schematic
Tested on :
.io (Survival) 
nydus 
.pl (Attack) 
AA (Campaign) 
CN (Survival) 
ALEX (Survival) 
Omega (Rush) 
MinDurka (Attack) 

Tested on same machine vanilla server with no plugins : can build, default configuration

**Link(s) to mod(s) used**:
dev mode : https://github.com/DeltaNedas/dev-mode 
pictologic : https://github.com/DeltaNedas/pictologic
timecontrol : https://github.com/sk7725/TimeControl
ui lib : https://github.com/DeltaNedas/ui-lib

**Save file**: 
[SaveFile.zip](https://github.com/Anuken/Mindustry/files/6261280/SaveFile.zip)
[Schematic.zip](https://github.com/Anuken/Mindustry/files/6261282/Schematic.zip)

https://user-images.githubusercontent.com/59116912/113643980-d14e2480-96ad-11eb-91e9-b1814bb08020.mp4

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No Crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The processor has too much data associated with it, so nothing gets built. There is currently no solution for this, other than to decrease the maximum number of lines.

**Comment by Kieaer** [comment]
How to place lots of lines processor now

**Comment by HKalbasi** [comment]
What is the maximum possible lines of logic code? Or is it dependent on the actual instructions?

**Comment by Matita008** [comment]
> What is the maximum possible lines of logic code? Or is it dependent on the actual instructions?

1) don't use old resolved issue, almost no one watches them
2) iirc the limit of instruction per processor is 1000

**Comment by Matita008** [comment]
> How to place lots of lines processor now

Don't use old closed issue
