### ISSUE TITLE
Refactoring and testing `editor`

### ISSUE THREAD

**Issue by tucan9389** [Anuken/Mindustry#507]
I'm on refactoring and testing for [editor](https://github.com/Anuken/Mindustry/tree/master/core/src/io/anuke/mindustry/editor).
Could you check this PR #503 and #504?
- Fix some mistyping and refactoring (#503)
- Decoupling editor/MapEditor from editor/OperationStack (#504)
I'll PR for testing OperationStack later.

> This(not now, but I'll PR later) could be my first test code in this project, but I seek the part needed test and want to contribute. If you have any advice please tell me.

Thanks 👍

**Comment by Anuken** [comment]
Since the PRs have been merged, I think it's safe to close this now.
