### ISSUE TITLE
Flying AI rotate issues

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5072]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *When an enemy unit is too close to a flying unit, it will not turn to face the enemy unit, instead backing up without rotating.*

**Steps to reproduce**: 
![Screenshot_20210406-173945](https://user-images.githubusercontent.com/61173114/113790767-61688a00-96ff-11eb-80c0-1ade8a3b985c.png)

**Link(s) to mod(s) used**: *K103908/Exotic-Mod for the units in the screenshot. Can re-enact with units like Eclipse.*

**Save file**: *AI issue, not save specific.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

deal with it (also on mobile campaign I cannot export the sector saves.)

**(Crash) logs**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest official release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> it will not turn to face the enemy unit, instead backing up without rotating.

Why should it?

**Comment by BlueWolf3682** [comment]
> > it will not turn to face the enemy unit, instead backing up without rotating.
> 
> Why should it?

I dunno, so it can *fight back*? if not, it should retreat.

**Comment by buthed010203** [comment]
> I dunno, so it can _fight back_? if not, it should retreat.

It cant fight back due to how close it is, theres a bit of code that specifically prevents units from shooting things that are close to them ![](https://mee6.is-terrible.com/NVsr5S.png)

**Comment by BlueWolf3682** [comment]
Good to know, but *why* isn't it allowed? It doesn't make sense.

**Comment by MrDuck557** [comment]
> I dunno, so it can _fight back_? if not, it should retreat.
Only two air units have to face the target to aim (flare and poly). The rest have independently rotating weapons.
> It cant fight back due to how close it is, theres a bit of code that specifically prevents units from shooting things that are close to them, it is still weird that it doesn't rotate either towards or away from the enemy.
This renders the rotation invalid

**Comment by buthed010203** [comment]
> Good to know, but _why_ isn't it allowed? It doesn't make sense.

It doesnt make much sense for weapons to rotate that far either though

**Comment by BlueWolf3682** [comment]
> > I dunno, so it can _fight back_? if not, it should retreat.
> 
> Only two air units have to face the target to aim (flare and poly). The rest have independently rotating weapons.

This is true, but it also renders modded units like Exotic's Fearless and Maliase units either ineffective or unable to deal their full damage.
> 
> > It cant fight back due to how close it is, theres a bit of code that specifically prevents units from shooting things that are close to them, it is still weird that it doesn't rotate either towards or away from the enemy.
> 
> This renders the rotation invalid

*why?*

**Comment by MrDuck557** [comment]
> *why?*

It physically can't shoot, no matter if they're facing the target or not
