### ISSUE TITLE
Legged units do not project shadows

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#5076]
**Platform**: Any

**Build**: 122.6

**Issue**: Legged units' shadows have only appear for the top part. Not the legs. This ends up looking very silly, shadow under the foot, yet the leg has none.

**Steps to reproduce**: Acquire a legged unit. Best seen on Toxopids

**Link(s) to mod(s) used**: Nah

**Save file**: Any save file. (proceeds to get soul reaped) Seriously, I tested on some other saves, old imported saves, new saves, essentially 10 of them.

**(Crash) logs**: No crashin'
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** (probably, there are _many_)

**Comment by MrDuck557** [comment]
update to 126.1 plz

**Comment by Anuken** [comment]
Not a bug.
