### ISSUE TITLE
Crash While Playing Level 234

### ISSUE THREAD

**Issue by Nebabon** [Anuken/Mindustry#5083]
**Platform**: Windows (Steam)

**Build**: *Steam Build 126.3*

**Issue**: Playing _Level 234_ and got a crash. Was building when it happened.
Direct error window is:
"A crash has occurred. It has been saved....
Byte write length exceeded: 37808 > 32767"
Unsure if the byte write length is related or not.

**Steps to reproduce**: Unable to reproduce currently

**Link(s) to mod(s) used**: [DeltaNedasrtfm.zip](https://github.com/Anuken/Mindustry/files/6279727/DeltaNedasrtfm.zip)
[DeltaNedasui-lib.zip](https://github.com/Anuken/Mindustry/files/6279728/DeltaNedasui-lib.zip)

**Save file**: [sector-serpulo-25.zip](https://github.com/Anuken/Mindustry/files/6279704/sector-serpulo-25.zip) 

>I will reap your soul.

Best warning I have ever seen

**(Crash) logs**: 
Crash Log: [crash-report-04_08_2021_11_05_47.txt](https://github.com/Anuken/Mindustry/files/6279673/crash-report-04_08_2021_11_05_47.txt)

Last Log: [last_log.txt](https://github.com/Anuken/Mindustry/files/6279675/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
I've dealt with this error when I build too big schematics.
It probably happened because you made too much and the game attempted an autosave.

**Comment by Anuken** [comment]
Fixed in 7.0.

**Comment by Erisfiregamer1** [comment]
wait a second.
7.0 release soon leaked?

**Comment by Anuken** [comment]
no

**Comment by Nebabon** [comment]
Cool, thanks!
