### ISSUE TITLE
Can't download mods.

### ISSUE THREAD

**Issue by Laggyboi0701** [Anuken/Mindustry#5085]
**Platform**: Windows 10

**Build**: 126.2

**Issue**: I can't download any mods, even though i have a strong wifi connection. here's the picture 
![aaaaaaaaaaa](https://user-images.githubusercontent.com/77478972/114112603-8987f280-9891-11eb-8b94-7d73f08d4465.png)

**Steps to reproduce**: Step:1 Download any mods from the mod browser.

**Link(s) to mod(s) used**: No mods were used.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works fine for me. It's possible Github may be blocked for you, which is the case in China.
