### ISSUE TITLE
Wave turrets cannot put out fires after capturing sector, but fire still damages core.

### ISSUE THREAD

**Issue by hrinn** [Anuken/Mindustry#5089]
**Platform**: Windows

**Build**: 126.3

**Issue**: My core was lit on fire right as I defeated the final boss. The 'sector captured' message appeared, after which my turrets stopped working. This prevented a nearby wave turret with water from putting out the fire, and the core was destroyed.

**Steps to reproduce**:
- Play Tar Fields
- Nearly get destroyed by the final boss
- Defeat the boss as it lights the core on fire
- Attempt to put out the fire with a water wave turret
- Turret doesn't do anything

**Link(s) to mod(s) used**: N/A

**Save file**: [Link](https://www.dropbox.com/s/f1hnoa9zrqh3492/saves.zip?dl=0)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dioo0** [comment]
you sure they didnt work?
![Screenshot_20210410-085632_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/78714307/114256374-ac71ee00-99da-11eb-8c73-873b79efe0c1.jpg)

**Comment by hrinn** [comment]
Pretty sure. I constructed the turret after the sector was captured. I put it within range of the core and saw it fill with water. But nothing happened before the core was destroyed.

**Comment by Dioo0** [comment]
strange

**Comment by Anuken** [comment]
You linked an entire save folder, which is unusable. I need the specific save, not the entire folder.

I cannot reproduce this myself.

**Comment by joshuaptfan** [comment]
@hrinn You can still upload the correct save file within this bug report and continue the discussion, even though it has been closed.

**Comment by hrinn** [comment]
I'm pretty sure [this](https://github.com/Anuken/Mindustry/files/6290809/sector-serpulo-23.zip) is the correct save file. They're all autosaves.

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/114287867-94c95280-9a38-11eb-8218-7b5f950f66c0.png)

Unless you swapped out the blocks before sending the save to confuse me, that's... the wrong turret.

**Comment by hrinn** [comment]
Well... looks like I placed the wrong turret in a panic. I guess I saw the water filling as coolant. Sorry for wasting your time.
