### ISSUE TITLE
Continuous lasers in unit weapons can get suddenly despawned

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5090]
***IMPORTANT NOTE: This bug may be difficult to reproduce, do not close this issue without confirming that it cannot be reproduced!***

**Platform**: *Android*

**Build**: *126.2*

**Issue**: *Continuous lasers on unit weapons can be made to despawn by killing ground units.*
![Screenshot_20210410-005723](https://user-images.githubusercontent.com/61173114/114261521-39478800-9998-11eb-8525-2504396f91cb.png)

**Steps to reproduce**: 
*1. Get shot by something like a nova.
2. Hit it with a continuous laser (I used one that dealt enough damage to instantly kill the nova)
3. the laser will despawn immediately.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod for the unit.*

**Save file**: *Bullet, not save, specific.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

cmon do it

**(Crash) logs**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Bullet, not save, specific.

I don't care. You have a specific setup necessary for this to be reproduced. I don't know the name of the unit(s) in the screenshot, and I'm not going to blindly go through all the content in your mod to find out. Provide the save.

**Comment by BlueWolf3682** [comment]
> > Bullet, not save, specific.
> 
> I don't care. You have a specific setup necessary for this to be reproduced. I don't know the name of the unit(s) in the screenshot, and I'm not going to blindly go through all the content in your mod to find out. Provide the save.

Please specify that this is necessary.
[aaaaaaaaaa](https://github.com/Anuken/Mindustry/files/6290538/test.zip)

**Comment by Anuken** [comment]
> Please specify that this is necessary.

Is this sarcasm? I can't tell. Template:

> DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by BlueWolf3682** [comment]
It was not save specific. Specifying that you need a testing ground for this would be a lot better.

Also good, its a bit of a nuisance.

**Comment by Anuken** [comment]
> It was not save specific. Specifying that you need a testing ground for this would be a lot better.

It **doesn't matter**. Stop trying to justify yourself and actually read the template:

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, **REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.**

Lasers are fired in-game, so you need to specify a save. **End of story.** Whether or not you think it happens everywhere is irrelevant.
