### ISSUE TITLE
When hitting a building, the frag bullets double

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5091]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *When hitting a building, the frags from the bullet double.*
![Screenshot_20210410-033212](https://user-images.githubusercontent.com/61173114/114265435-fe504f00-99ad-11eb-9462-ad90b8422e36.png)
![Screenshot_20210410-032811](https://user-images.githubusercontent.com/61173114/114265438-ff817c00-99ad-11eb-862a-9c7f77a537d4.png)
(This unit's bullet has only 6 frag bullets in its code.)

**Steps to reproduce**: 
*1. Fire at any structure with a bullet with frags. (I hit some walls.)
2. Watch the frags double.
3. ~~scream in pain if you did this with wildfire because theres now 75 swords flying everywhere~~*

**Link(s) to mod(s) used**: *Same as my last bug report.*

**Save file**: *Bullet issue, not save specific.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

aaaaaaaaa

**(Crash) logs**: *no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
