### ISSUE TITLE
Weird core landing bug

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#5092]
**Platform**: Windows

**Build**: 126.2

**Issue**: Landing cores on custom maps with multiple team cores leads to enemy core having fall animation, which starts at the center and slowly moves away to the core's position (talking about red core). During the landing animation, core has yellow marks. After landing, shockwave is emited from your core, which did not land at all.

**Steps to reproduce**: Load the save file, go in custom game, then "test map". Chose sandbox, and there you go!

**Link(s) to mod(s) used**: No mods active.

**Save file**: Unable to load, it is 50MB in size, while the cap is 10MB. Any way I can bypass this? Here is how the map looked like:
Anyway, put a red core, then a yellow core. Try it. Then try with 2 cores of each type. My map has 3 yellow cores, one of each type, and I put 8 enemy cores. Some enemy walls (thorium) are present as well. No other components for Crux. Sharded had each reconstructor.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
>  it is 50MB in size

I don't see how a single map could possibly be 50mb unless you're intentionally messing around with the format. I'm not asking for your game data.

**Comment by Anuken** [comment]
Cannot reproduce on own map with two types of cores.

**Comment by BorisA11** [comment]
[Issue map.zip](https://github.com/Anuken/Mindustry/files/6290110/Issue.map.zip)
There it is

**Comment by BorisA11** [comment]
Try the map, took me a while to zip and export

**Comment by Anuken** [comment]
Fixed in 7.0.
