### ISSUE TITLE
Saved file was corrupted when i started a game

### ISSUE THREAD

**Issue by TheMaither** [Anuken/Mindustry#5096]
**Platform**: *Windows*

**Build**: *126.2*

**Issue**: *On the next day when i open mindustry all my campaign sectors was attacked for some reason, thankfully yesterday i exported save file of my progress, but when i try to open the save file it was corrupted, and i cant load it*

**Steps to reproduce**: 
- Build some factories on salt flats
- Exit campaign
- Export save
- Go sleep
- Open mindustry
- Try to import save*

**Link(s) to mod(s) used**: *Anuken/ExampleJavaMod (was disabled)*

**Save file**: 
- *[save6.zip](https://github.com/Anuken/Mindustry/files/6291719/save6.zip)* (corrupted), 
- *[save5.zip](https://github.com/Anuken/Mindustry/files/6291727/save5.zip)* (previous)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Save export works for me, and there's nothing I can say about the corrupted file except for the fact that it is not a valid zip. Won't fix.

**Comment by Dioo0** [comment]
pretty sure u just didnt sleep
