### ISSUE TITLE
"water" in "Sand water" is not capitalized

### ISSUE THREAD

**Issue by nichrosia** [Anuken/Mindustry#5099]
**Platform**: *Android/iOS/Mac/Windows/Linux*

N/A, this is an issue with the bundles

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Latest look at the source code shows that the issue still exists https://github.com/Anuken/Mindustry/blob/24c8d6e040258b196010ac8601afbdc137f42020/core/assets/bundles/bundle.properties#L1119

**Issue**: *Explain your issue in detail.*

"water" in "Sand water" is not capitalized, which is an inconsistency with the rest of the floor/water tiles.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Open Editor, look at the name of Sand water

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

N/A, this is an issue with the base game.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

N/A, this is an issue with game bundles, which aren't saved in save files.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
~~this has been making me cry inside for months~~

**Comment by Anuken** [comment]
If you care, submit a PR. You could have done an edit in the time it took to write this issue.

**Comment by BlueWolf3682** [comment]
ok
