### ISSUE TITLE
Unable to cargo containers/units from payload conveyors using Mega on android

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry#5106]
**Platform**: *Android*

**Build**: 126.2

**Issue**: While controling Mega, player is unable to pick up things transported by payload conveyors. However it works with usage of quad. I've tested cargo with logic, and picking up with usage of processors still works. Only player-controlled mega is unable to do the thing.

**Steps to reproduce**: Control Mega. Put the container/unit on payload conveyor (it is possible), but trying to tap-hold to pick up moving container is impossible.

**Link(s) to mod(s) used**: *None.*

**Save file**: 
[mega bug report.zip](https://github.com/Anuken/Mindustry/files/6309673/mega.bug.report.zip)
I've been testing it on **Lab** custom map.

**(Crash) logs**: This bug doesn't crash the game.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kubek0212** [comment]
https://user-images.githubusercontent.com/33349024/114686384-03493180-9d13-11eb-9199-eb2eefd2c65a.mp4

That's how it looks

**Comment by Anuken** [comment]
Fixed in 7.0.

**Comment by Erisfiregamer1** [comment]
but when does 7.0 come out?

**Comment by Anuken** [comment]
`#faq`
