### ISSUE TITLE
Unloaders can't fill a Titanium conveyor.

### ISSUE THREAD

**Issue by Dr-Ico** [Anuken/Mindustry#5107]
**Platform**: *Windows*

**Build**: *V6 - Release Build 126.1*

**Issue**: *I check how much sand it takes for a Phase Weaver, one need 5 sand/s, so two need 10 sand/s... A titanium conveyor can bring this (10<11), so I unload it from my core to Phase Weavers, but the titanium conveyor isn't enough for two Phase Weavers. I try this in a sandbox world, one side with a Titanium conveyor bringind sand from a source and the other from a container using an unloader. The first one work perfectly, the second one need more sand. We have the exact same problem on three alloy smelter, they take 9.6 lead/s.*

**Steps to reproduce**: *Just open a sandbox world, paste this shematic and wait 20 second:
bXNjaAF4nHVUTU/bQBAdf8TrjwRcaAkhoBj1DG0vlXpsTz1WKlXPVrIiaRMb2QkR/6aX/kmKlM7bB+YEUfw8O7vLzJv3Iuey50tYlSsre5dfNteXxY9qWZcz20g2s+20WdysF3UlMpBssbari7beNFMredms6sbOLqZ1dWvv6kYG5XJZ3120K7tc62mzsm1bXlt5tV6sy2qxWT1vjZp6gz3xr001ddcn7u7bejGT/k29tc3T/0n00LpcVNi9eaps72Zetvb5vj7jrS1vNSvyV/DXE0kCvHj6Frk3X9/EvQVdNuyyvS4bdVnTZWOX9cRzV7qPe/iEgBASeoSIYAixFqD7dC8gJBgJAl3uh568vZo31hafwWPxnTwW6/K3LT5dfiyWtpy9a93BVDcff7WNLba2mGvTha3qzfXc7dE8KvVRhJaIKGAUMooYGXHvWlqkoH2EyICYCEViMeRij4sRFw0XYwkACSElZIQ+2IhkABZ8tO+oMiTHkI4YlAB8QkAICT1CRDCEmJCIZxRStJGgcICWikwv1qp3O4SKD7v73W53L77ig9umxScKffSeukkrOJZS9p6y9JRkpew9BTNYNFx0vafsPcURPDJ0qwsZ9ZGR0ozCyMhlRkVkJDFTU/m+PpwiBlTEgIrouyEfPQ25snZWwHAcsWh+8KixfQ57n0zsaxsOAkJI6BEigiGAe8k7o+SdUfLOKHlnlLwzSt4ZJe+MkndGyR+NEsoBtgBCXHLAmR5AXYgMIwxeIdEzxs/kUALjuqPXDmmkQxAfKMAlk6ttXXyD4YufzvC0yIf3RVtWcEhfXmNsAEflm5f9ghNa3hH5OcJ0EBlGMagZou5IIWJkGMXYOaQEhpT/kPIfUv5DNyCVsxxz6Mc4E8tIwjja/XM/FZ6i+yGATiXSr6d5J/oRCRpR9COKfgTNenLCOZ5ggImCU/OYdY5Z5xiMIXJ1jlnnmFIdO6mGunBKek9xHyLDKGak4uzLGak8I5VnL6nSESmaZ9OZTHSQ6r1z/f7RSydkeELhF3A7IITkCiqjQOOItIr/adauxA==*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *[Bug Unloader.zip](https://github.com/Anuken/Mindustry/files/6311022/Bug.Unloader.zip)*

**(Crash) logs**: *The game don't crash on this bug.*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not supposed to.
