### ISSUE TITLE
I can't join any multiplayer servers every time i try it says it can't connect

### ISSUE THREAD

**Issue by awesom-shark** [Anuken/Mindustry#5108]
**Platform**: `Windows 10 x64`

*can*Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment]
Please edit your post to fill out the template. There's not enough here to help you.

**Comment by itcannotbe** [comment]
A screenshot of the actual error might be useful.

**Comment by itcannotbe** [comment]
Also 99.999999% I'm certain that you're having internet issues preventing you from connecting to servers.

**Comment by Dioo0** [comment]
> Also 99.999999% I'm certain that you're having internet issues preventing you from connecting to servers.

_how he sent this bug issue then_

**Comment by awesom-shark** [comment]
sorry for the late reply 

[bug.zip](https://github.com/Anuken/Mindustry/files/6323562/bug.zip)
