### ISSUE TITLE
Impact Reactor Not Properly Working

### ISSUE THREAD

**Issue by MrBubz1** [Anuken/Mindustry#5111]
**Platform**: *Windows*

**Build**: *Steam Build 126.3*

**Issue**: *Reactors just stop and get stuck in a start/stop loops as they reset what appears to be randomly, even if provided with all the fuel needed. Video to help understand, if necessary:*

https://user-images.githubusercontent.com/82620312/114951868-7f4b9280-9e55-11eb-9446-844b036d51e3.mp4

**Steps to reproduce**: *Be on a multiplayer server, and have a functioning impact reactor setup. I cannot provide additional steps as this happened while the impact reactors were running fine and suddenly stopped working.*

**Link(s) to mod(s) used**: *Vanilla*

**Save file**: 
[Multiplayer Save.zip](https://github.com/Anuken/Mindustry/files/6321621/Multiplayer.Save.zip)

**(Crash) logs**: *None*
---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
see comment above

**Comment by BlueWolf3682** [comment]
*I will take a moment to mention that 126.3 does not exist, either*

**Comment by joshuaptfan** [comment]
It does on Steam.
