### ISSUE TITLE
Builds error

### ISSUE THREAD

**Issue by 70178637** [Anuken/Mindustry#5113]
**Platform**: *Android*

**Build**: *21022*

**Issue**: *Error reading file: sprites/sprites.atlas (internal)
Please fix this error as soon as possible. This error makes the game completely unplayable now.*

**Steps to reproduce**: *nothing*

**Link(s) to mod(s) used**: *nothing*

**Save file**: *nothing*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Wait a moment*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 70178637** [comment]
[Uploading crash_1618557073295.txt…]()

**Comment by 70178637** [comment]
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 21022
OS: Linux x32
Java Version: 0
Java Architecture: null
0 Mods

> ArcRuntime: 'arc.util.ArcRuntimeException: Error reading file: sprites/sprites.atlas (internal)'
AssetManager.handleTaskError: 670
AssetManager.update: 442
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1609
GLSurfaceView$GLThread.run: 1293
> ArcRuntime: 'Error reading file: sprites/sprites.atlas (internal)'
AndroidFi.read: 62
TextureAtlas$TextureAtlasData.<init>: 350
TextureAtlasLoader.getDependencies: 45
TextureAtlasLoader.getDependencies: 20
AssetLoadingTask.handleSyncLoader: 83
AssetLoadingTask.update: 72
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1609
GLSurfaceView$GLThread.run: 1293
> FileNotFound: 'sprites/sprites.atlas'
AssetManager.nativeOpenAsset: -2
AssetManager.open: 865
AssetManager.open: 842
AndroidFi.read: 60
TextureAtlas$TextureAtlasData.<init>: 350
TextureAtlasLoader.getDependencies: 45
TextureAtlasLoader.getDependencies: 20
AssetLoadingTask.handleSyncLoader: 83
AssetLoadingTask.update: 72
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1609
GLSurfaceView$GLThread.run: 1293

**Comment by ThebestkillerTBK** [comment]
Please check your game is fully downloaded

**Comment by 70178637** [comment]
> Please check your game is fully downloaded

I confirm.

**Comment by Anuken** [comment]
Don't use bleeding edge builds, there's nothing new anyway.
