### ISSUE TITLE
enabling pc controls on mobile does not disable the message box popup

### ISSUE THREAD

**Issue by bvcbvc** [Anuken/Mindustry#5116]
**Platform**: android, this might effect ios too im unsure

**Build**: 126.2
**Issue**: whenever keyboard and mouse controls are enabled, one would expect the text box to stop popping up, it does not

**Steps to reproduce**: simply try to chat with mouse and keyboard controls

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

if you dont plan on fixing, let me know, its a minor issue, so im not gonna expect you to fix it

**Comment by Anuken** [comment]
It's not supposed to.

**Comment by bvcbvc** [comment]
so its supposed to show no matter what
hecc
