### ISSUE TITLE
Weird liquid overflow

### ISSUE THREAD

**Issue by driver1748** [Anuken/Mindustry#5122]
**Platform**: *Android* _Have not tested on other platforms_

**Build**: *126.1*

**Issue**: *The liquid does not come out of the pipe.*
![13B058D9-8FF6-4FCD-9C2E-7D446546DA26](https://user-images.githubusercontent.com/62016462/115137101-8097dd80-a056-11eb-9578-0203abf92a9a.jpeg)
![10D05EF8-2600-4533-86B5-ECF87F84599D](https://user-images.githubusercontent.com/62016462/115137109-8db4cc80-a056-11eb-83cb-11d2a0730b86.jpeg)

**Steps to reproduce**: *Just build like this*

**Save file**: * bXNjaAF4nE1TSXLbQAwEORzupMShFWV5g9+R5BmOxEqxSpEULT9wVR6QWw6++Z5bDn5Pok+4IncTojwHqdnAoNHAkPJBbkKJ1nffOpmcHh/+Pv44/bo/Pf3893AvxbLbL3b99tBv1iKxVKv++7Ff3u43x92ik2SxWS+P/eEa322Oh24n9Zddv/za3Y7peru6O3TLK6+2x9X+NS3Cnxgb4S+QQIzgLyQIoLrEDZ4DRoe0kUiDFVmEXBgypAycgJwRK2FyPp+fzuf/nwNSk0A3kqEnaDRmPyJgJb20s1KyndUGVmoGY0nJYuTQLtZcjBzaJcwZQOm3S6Ty2yVS++0ScZd2KZ7RLtUGqWQadCzKdIJnSgSkhvQPND4N2eiaRWkGIXjLVChjMcGR5bqmnLskw5oMIPEN55L6hnPJXg2zpqHNfNRrabNQ2UJlC5UtdA+j6QJ78EwXuofRdAHZQcEpa6lQ+jcVgA5LL7H0kKzWM41vvhTnmy+l9c1XqlCpQqUKtY4/+qwxvuez1vGfL4K1f5uBTHTXE+w6JMOuI5nyJAFvpwXglTWA4c5+UzYIQIfCqRZOWcgzje9kilk8J1OdRZ1Y7MvQUOPfVgA67LHBHkOyloYcjxJy+nK8Jwso6cvptYy+nNY7rXda37LeAobPqfVXHMkNo5HM+F0RYorPMB7EZ7pLFWeyos4bvpmRzEeYsHDODVlAw8K5jj4WvuVRC3CseKfwnvAC4AXMOQ==* (Blueprint)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Armored conduits aren't supposed to leak.

**Comment by Awesomespore** [comment]
I-

_t h e   s o l e   p u r p o s e   o f   p l a t e d   c o n d u i t s   i s   t h a t   t h e y   d o n ' t   a c c e p t   s i d e   i n p u t   a n d  
 d o n ' t   l e a k . . ._

**Comment by SMOLKEYS** [comment]
c    l   o   s   e   i   t   n  o  w   o   r   s   o   u   l   r   e   a   p

**Comment by Erisfiregamer1** [comment]
@Awesomespore wait- you play mindustry???

**Comment by Awesomespore** [comment]
> @Awesomespore wait- you play mindustry???

yeah, why?...
