### ISSUE TITLE
Cannot Click Anything

### ISSUE THREAD

**Issue by Abstrusle** [Anuken/Mindustry#5123]
**Platform**: Windows 64-bit

**Build**: Release 126.2

**Issue**: I possess an issue rendering the game unplayable: I must click every menu option multiple times within a specific area for anything to occur. I can scroll by dragging in options, and select sliders normally, however. I downloaded both via Steam and Itch.io, but to no avail.

**Steps to reproduce**: Play the game.

**Link(s) to mod(s) used**: N/A

**Save file**: I have never begun a game. The issue initiates immediately upon opening and loading the main menu.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't happen to me. Won't fix.
