### ISSUE TITLE
Two bit volume lol

### ISSUE THREAD

**Issue by robotiq-coder** [Anuken/Mindustry#5124]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: My phone is a little bad. All sounds are sizzling, except for the music. How can I say ... It looks like the quality has decreased a little. So I deleted and installed the game several times. However, it has not been resolved. aNuKe

**Steps to reproduce**: *when the game is overloaded, when there are too many elements on the map, in short, when the using RAM rises*

**Link(s) to mod(s) used**: *no*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by robotiq-coder** [comment]
WHY?

**Comment by Anuken** [comment]
I have nothing to say to people who are incapable of reading all-caps text stating the issue requirements.

**Comment by BlueWolf3682** [comment]
I can confirm a part-time preproduction of this issue on my Google Pixel 2. 
Also, it is not save specific, it is client specific. Stop preaching about save files for sounds.

**Comment by Anuken** [comment]
It happens only in-game, and the issue clearly states:

> when the game is overloaded, when there are too many elements on the map

...which **heavily** implies that it is save specific.

**Comment by BlueWolf3682** [comment]
> It happens only in-game, and the issue clearly states:
> 
> > when the game is overloaded, when there are too many elements on the map
> 
> ...which **heavily** implies that it is save specific.

No, it does not. I have had this happen on empty maps while testing some of my modded units or blocks, or even just designing new core launch schematics for vanilla campaign. It *just happens* every now and then.

**Comment by Anuken** [comment]
> No, it does not. I have had this happen on empty maps while testing some of my modded units or blocks, or even just designing new core launch schematics for vanilla campaign.

Except it very much does - even if the issue **you're** experiencing is the same/similar, the person who reported this issue claims that it happens on maps with "many things happening at once". This is not **your** bug report, and I was asking for the save based on the information **provided in the original issue**.
