### ISSUE TITLE
Fatal error when launching the game

### ISSUE THREAD

**Issue by ErPyrex** [Anuken/Mindustry#5126]
** Platform **: * Windows *

** Build **: * 126.2. *

** Problem **: * When executing the .exe the game opens with a glitch on the screen blocking access to the menu making it unreadable and unplayable *

** Steps to reproduce **: * at the moment I have not been able to solve it, this is a new pc so download the game from itch.io and when executing it step. *

** Link (s) to mod (s) used **: * none. *

** Save file **: * I will skip this part as it is the complete base game without mods. *

** (Crash) logs **: * I can't see them or even open the game at that. *

** Additional **: * my pc is an Intel (R) Celeron (R) CPU 847 1.10GHz, 2Gb Ram, Intel Powered Classmate PC, Windows 7 (32-bit system)
---

* Place an X (without spaces) between the brackets to confirm that you have read the line below. *
- [x] ** I have updated to the latest version (https://github.com/Anuken/Mindustry/releases) to make sure my problem has not been fixed. **
- [X] ** I have looked for the closed and open issues to make sure this issue has yet to be reported. ** 
![bug](https://user-images.githubusercontent.com/74994780/115184262-fb9bdb00-a0cc-11eb-9f1d-c3b2e42e543a.PNG)

**Comment by joshuaptfan** [comment]
Please fetch your crash log from here and upload it:

```
C:\Users\<username>\AppData\Roaming\Mindustry\crashes
```

**Comment by Anuken** [comment]
Your graphics drivers are broken. I can't fix this.
