### ISSUE TITLE
Blocks with transparency (non-full blocks) don't render right in map editor

### ISSUE THREAD

**Issue by Liftyee** [Anuken/Mindustry#5128]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Tested on steam version

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
steam build 126.3

**Issue**: *Explain your issue in detail.*
_**Blocks**_ that have transparency that don't fill the entire square area that they take up (e.g. shock mine, power node, microprocessor) have their backgrounds shown as black instead of as the block under them as it is in the normal game. (Most noticeable with shock mines) Terrain blocks such as pines and boulders work as expected. 

![image](https://user-images.githubusercontent.com/64788399/115282303-fc228900-a141-11eb-9474-5c4e3d1d9a3a.png)
You can see that the coal, titanium, and boulders have their transparent areas showing the ground underneath. The other blocks have black replacing their transparent areas instead of the ground underneath, like the boulders. 

![image](https://user-images.githubusercontent.com/64788399/115282625-51f73100-a142-11eb-981c-018706407cb2.png)
Reference image: In the 'Edit in-game' option the blocks render as expected.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I found it when making an attack map. 
1. Enter a map in the editor
2. Place a block with transparent areas (use shock mine for most obvious effect)
3. Notice that the normally transparent areas of the block are black instead of showing the ground. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[brokentransp.zip](https://github.com/Anuken/Mindustry/files/6338077/brokentransp.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.
