### ISSUE TITLE
High probability that the liquid will not flow

### ISSUE THREAD

**Issue by 70178637** [Anuken/Mindustry#5130]
**Platform**: *Android/*

**Build**: *126.2*

**Issue**: *To correct the previous wrong   problem, #5122 the actual test should look like this.
![Screenshot_20210420_115124_io anuke mindustry bf](https://user-images.githubusercontent.com/72331352/115335558-0d2fc200-a163-11eb-9773-af6418f53466.jpg)
*

**Steps to reproduce**: *bXNjaAF4nEWQ3W6CQBCFZ3eRpawK2Ocw6evoXQViNrFgQbzoA3jRB2lf0oTOmTF2k83hY87OH23o1VLSvX+05A7TkULTjvUQz5fYd0SOVufpNLbbuu+aKV5ofRhic/zn1Sl+TrHZjv001C0RvfGlQBayhBglo2SVLMhw+tyzL4FZMAC/+O4sisuTBeGTxahYFQdJNZZqLEXMsDg/z/MvUgl6ZCX+dXeWMVskUs6zj/QkDujx7IfxKii9XfnuxRwQvUurljIKksXSC/lHvlwLyTQEzPDiW3ICZbg9fhlg8ezKYCv5I0tQn3RlgOLbse9msNmSRCqVDWRJhUqpUqlIbI0dGRYZ7iZ7AWbPafgUskgWqVwqlUqVUgX6AwjXTFQ=*

**Link(s) to mod(s) used**: *no*

**Save file**: *no*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by liuxilu** [comment]
#4764
> Merging priority is undefined, and will always be.
