### ISSUE TITLE
Lancer fires without dealing any damage if placed at 90-degrees angle relative to target

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#5131]
**Platform**: Windows/Linux server

**Build**: 126.2

**Issue**: Lancer does no damage if it fires at specific angle relative to the wall that protects target

**Steps to reproduce**: Launch the attached map (or see gif below).

**Link(s) to mod(s) used**: no mods

**Save file**: map: [lancer_test.zip](https://github.com/Anuken/Mindustry/files/6340552/lancer_test.zip)

![lancer_no_damage](https://user-images.githubusercontent.com/4199082/115335963-e8f5d480-a1a6-11eb-8d8e-96d7f934ae36.gif)

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
