### ISSUE TITLE
Mass Driver receives items without power

### ISSUE THREAD

**Issue by Weathercold** [Anuken/Mindustry#5133]
**Platform**: iOS

**Build**: 126.3

**Issue**:
![image](https://user-images.githubusercontent.com/49368953/115475264-3c027280-a20d-11eb-8f73-13151ae80975.png)
The receiver Mass Driver does not need power to function when it should. It just needs to be aligned to the sender Mass Driver. 

**Steps to reproduce**:
1. Build two Mass Drivers, one surrounded by item voids and the other surrounded by item sources.
2. Set the item sources to any item.
3. Connect the second to the first.
4. Build a power source that connects to the Mass Drivers and wait for them to align.
5. Disconnect the first Mass Driver from the power source.

**Link(s) to mod(s) used**: [Mindustry Schematics](https://github.com/pixecoz/MindustrySchematics)

**Save file**: 
[save-Bug Report.zip](https://github.com/Anuken/Mindustry/files/6347188/save-Bug.Report.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Why should it need power to accept items?

**Comment by Weathercold** [comment]
> Why should it need power to accept items?

Because the block status says that the block isn't functioning.
Also the animation of receiving items stops playing, so I thought it was a bug.
Maybe at least make the block status yellow like phase conveyor?

**Comment by Anuken** [comment]
> Because the block status says that the block isn't functioning.

And it isn't. It can't turn, and it can't shoot. Receiving items requires nothing from the block.

> Maybe at least make the block status yellow like phase conveyor?

Yellow means output bottleneck, which is not the problem.
