### ISSUE TITLE
blacked out schematics

### ISSUE THREAD

**Issue by wingmaker77** [Anuken/Mindustry#5135]
**Platform**: `Android 30`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*
When scrolling through schematics on Amdroid phone and tablet they will randomly show as black instead of the design. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- I did see an issue like this reported last year. Not sure if it was still pending or not though.

**Comment by RusLeonid** [comment]
This happens to me as well, usually it's triggered when creating a new schematic

**Comment by RusLeonid** [comment]
https://user-images.githubusercontent.com/81614288/115548698-6fe2a400-a2b0-11eb-9a2a-f958ab40c1dd.mp4

**Comment by Anuken** [comment]
Cannot reproduce, no saves shown.

**Comment by joshuaptfan** [comment]
Even though the issue has been closed, you can still upload a save to get this issue addressed.

**Comment by wingmaker77** [comment]
[black schematics .zip](https://github.com/Anuken/Mindustry/files/6353568/black.schematics.zip)

**Comment by Anuken** [comment]
Fixed. The issue only occurred when a large amount of schematics were loaded at once.
