### ISSUE TITLE
Bug on sei and omura

### ISSUE THREAD

**Issue by Slawmee** [Anuken/Mindustry#5137]
**Platform**: *Android*

**Build**: *The build number under the title in the main menu. Required. *v6*

**Issue**: *I cant control the Sei and Omura*

**Steps to reproduce**:I just double tap on it and when I try to move, its just making its own way to enemy its not even move where I want but I can shoot.*

**Link(s) to mod(s) used**: *nothing.*

**Save file**: *
Dont have

**Comment by MrDuck557** [comment]
1. You can include a save file by exporting save, if on campaign, %appdata% --> industry --> saves --> serpulo (sector number). The sector numbers can be found [here](https://docs.google.com/spreadsheets/d/1whF_xrWFtacE69dFuqXlv_RKTrxPq8GwWfj5FKqMet0/edit#gid=0) (sector list, scroll down)
2. You didn't include the version number, Anuke can't know if he fixed this issue or not (build number 126.1 for example, seen in menu under logo)
3. Exactly how do you reproduce it? If Anuke can't reproduce the bug, he can't know what's causing the bug and can't fix it
