### ISSUE TITLE
My logic code correctly counts Crawlers, Flares but not Horizons

### ISSUE THREAD

**Issue by Nakilon** [Anuken/Mindustry#5139]
**Platform**: Windows

**Build**: Steam build 126.3

**Issue**: The code is supposed to gather the units until they are 8 and then command them to `pathfind` until they have a loss and so should retreat. It displays the current amount of them in a Message.  
While this code works for Crawlers and Flares counting them from 0 to 8 **it counts 1406 of Horizons** and so always sends it to attack.

**Steps to reproduce**:

```
set tick @tick
set n 0
ubind @crawler
sensor j @unit @flag
ucontrol flag tick 0 0 0 0
op notEqual e tick j
op add n n e
jump 2 notEqual e false
print n
printflush message1
jump 16 lessThan n 8
ubind @crawler
ucontrol pathfind 0 0 0 0 0
op sub n n 1
jump 11 notEqual n 0
end
ubind @crawler
ucontrol move 119 53 3 0 0
op sub n n 1
jump 16 notEqual n 0
```

Replace the unit type in three lines.

**Save file**: current save folder -- [saves.zip](https://github.com/Anuken/Mindustry/files/6357824/saves.zip)  
Sector "Salt Flats". In the middle of the base there are two processors -- for Crawlers on the right and Horizons on the left.

---

- [X] **I have updated to the latest release (Steam, autoupdated) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't debug arbitrary logic code. Show me **which instruction** is producing incorrect outputs with specific inputs and what the expected outputs should be.

**Comment by MrDuck557** [comment]
Cannot import save

**Comment by Nakilon** [comment]
Nevermind. My mistake was in not checking the `ubind` for `null`. Since empty unit's flag isn't equal to `tick` it was incrementing the `n`.

**Comment by joshuaptfan** [comment]
In the future, you can ask in the #logic channel on Discord for help. If you're logic doesn't work, it's more likely to be a problem with your code than a bug in the game.

**Comment by Nakilon** [comment]
> In the future, you can ask for logic help in the #logic channel on Discord. If you're logic doesn't work, it's more likely to be a problem with your code than a bug in the game.

I just thought it's a bug in `ubind` that it was iterating over something else rather than Horizons.

Why not IRC?
