### ISSUE TITLE
(Logic) drawn geometry / imagery angles are off by +90° when given an angle between ~270° and 360°

### ISSUE THREAD

**Issue by Sky4ce09** [Anuken/Mindustry#5142]
**Platform**: Windows

**Build**: 126.2

**Issue**: when attempting to draw anything that can be given an angle on a display the angle of the result will be +90 degrees off if it is supposed to be drawn with an angle that is in the 269.99999...° - 360° range

**Steps to reproduce**: 0) open mindustry
1) make a processor try drawing a dagger with an angle of 280° (for example) and flushing that to a display
2) observe that the dagger is indeed drawn with an angle of 10° (for example) instead

**Link(s) to mod(s) used**: no mods required

**Save file**: [loopback.zip](https://github.com/Anuken/Mindustry/files/6360598/loopback.zip)

**(Crash) logs**: no crashes

additional material: 

https://user-images.githubusercontent.com/44333723/115770481-0dbb9900-a3ad-11eb-9c31-aaccc0d47588.mp4

(note that this was recorded with a bunch of mods active, but they do not have an impact on this)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
