### ISSUE TITLE
Doesn't recording in-game sounds by using video recording with system sounds

### ISSUE THREAD

**Issue by Mak992** [Anuken/Mindustry#5144]
**Platform**: `Android 29`

**Build**: `release build 126.2`

**Issue**: Don't recording in-game sounds by recorder. I tried different system-sound recorders and found out, what a problem in Mindustry. Idk what to do

**Steps to reproduce**: I just tried to record a video of game

**Link(s) to mod(s) used**: `none`

**Save file**: Doesn't matter in this case

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 1ARC1** [comment]
same as #4916, please close
