### ISSUE TITLE
Exiting in-game causes Steam to think Mindustry is still open

### ISSUE THREAD

**Issue by pyDebugger** [Anuken/Mindustry#5146]
**Platform**: Windows - Steam

**Build**: v6 - 126.2

**Issue**: When i was downloading mods on Steam, the game (obviously) exited to reload mods. Afterwards, i tried starting it again to play, but Steam seemed to think Mindustry was still open, yet i could find it nowhere in the Task-Manager. The same happened with regularly exiting through the main menu.

**Steps to reproduce**: First, i quit the game. Steam thinks Mindustry is open.

**Link(s) to mod(s) used**: 
[DeltaNedasunit-factory.zip](https://github.com/Anuken/Mindustry/files/6366707/DeltaNedasunit-factory.zip)
[XeloboyoFactoriodustry.zip](https://github.com/Anuken/Mindustry/files/6366708/XeloboyoFactoriodustry.zip)
[DeltaNedasui-lib.zip](https://github.com/Anuken/Mindustry/files/6366709/DeltaNedasui-lib.zip)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. The game exits correctly on Windows, and Steam doesn't have any issues registering it as not running. If **the process itself** is gone, this may be a Steam bug.

**Comment by Legomonster33** [comment]
> Cannot reproduce. The game exits correctly on Windows, and Steam doesn't have any issues registering it as not running. If **the process itself** is gone, this may be a Steam bug.

this is a common issue with steam, that has (nearly) nothing to do with the game

**Comment by the-red-soul** [comment]
If you cannot find the Mindustry process out in the open, make sure you expand the steam process to view all the sub processes. I have frequently found my steam games inside of there.
