### ISSUE TITLE
Waves Reset on captured sector when core dies

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#5149]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam Release 126.2

**Issue**: *Explain your issue in detail.*
When the core dies on a captured sector, waves reset

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. capture sector
2. kill your own core (thorium reactor explosion etc.)
3. launch there again
4. waves are back??

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Tested on multiple sectors, issue persists.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
🙃 

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
This occurs whether or not an enemy base is nearby

**Comment by Anuken** [comment]
> waves are back??

*Why wouldn't they be back?* You lost the sector, you have to capture it back again.

**Comment by Legomonster33** [comment]
> > waves are back??
> 
> _Why wouldn't they be back?_ You lost the sector, you have to capture it back again.

yeah but you already killed all the enemies, so why are they back???

**Comment by Anuken** [comment]
You're gone, they invade again. That's how it works.

**Comment by Legomonster33** [comment]
> You're gone, they invade again. That's how it works.

but you already got rid of them, it would make sense if this happened when an enemy base was nearby, but it doesn't make sense on isolated sectors. especially if they are surrounded by captured sectors.

**Comment by Anuken** [comment]
Every single sector on the map has waves on it, regardless of whether there are enemy bases near it. The enemy **does not care** if you have everything captured around it, that doesn't stop them from sending units everywhere. Go away and stop wasting my time.

**Comment by Legomonster33** [comment]
so the enemy can launch anywhere but we cant 🤔

**Comment by Anuken** [comment]
wow it's almost as if they have more advanced technology
