### ISSUE TITLE
Stable desync of units, producing ghosts

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#5150]
**Platform**: Windows/Linux server

**Build**: 126.2

**Issue**: There is a specific case when units get destroyed only on client-side and it obviously produces a lot of confusion. In normal circumstances it is rare (still, not an impossible case, especially if ping spikes or [I guess] gets higher than 200ms), but now I have a stable way to reproduce it with a slight modification of server-side.

**Steps to reproduce**:
1. Modify `mindustry.entities.comp.ShieldComp#rawDamage` **server-side only** to replace incoming damage with something small (say, `amount = 0.001f;`)
2. Make default flare's health **server-side only** to 10.
3. Launch attached map on server in sandbox mode.
4. Connect via client. Network between server and client should have ability to lag, or server should be able to lag. I "shake" server's window on windows to get this effect in local network.
5. Flare gets produced, flies up.
6. Produce lag, observe flare gets killed on client.
7. Type `/sync` and flare is still alive flying around.
Here is a video of how it looks if I connect from phone via local Wi-Fi network and produce a little "lag" via shaking server's window: https://www.youtube.com/watch?v=mptzC1KkFow

It is obvious that due to randomness of other places we can get pseudorandom-generated bullet (either produced by player or by turret) to "kill" unit client-side only in even more cases other than that and later see half of the base being destroyed by a ghost.

I believe this is due to the fact that client-side proceeds with `destroy()` here without noticing that the unit may still be alive:
https://github.com/Anuken/Mindustry/blob/02e68d27a3e4a045a174223e158a7b76dd5cc454/core/src/mindustry/entities/comp/UnitComp.java#L370

Fun note:
https://github.com/Anuken/Mindustry/blob/02e68d27a3e4a045a174223e158a7b76dd5cc454/core/src/mindustry/entities/comp/UnitComp.java#L514

**Link(s) to mod(s) used**: no mods

**Save file**: A simple map to test this out: 

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** - I can't find them now, but I believe I saw countless amounts of related issues with answer `/sync`.
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
Here is the map that I used: 
[unit_desync_test.zip](https://github.com/Anuken/Mindustry/files/6370213/unit_desync_test.zip)

**Comment by Anuken** [comment]
Fixed in 7.0, unit *crash* destruction is now synced.
