### ISSUE TITLE
`isHidden()` does not fully hide things.

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#5151]
**Platform**: Windows

**Build**: release build 126.2

**Issue**: Content that is hidden can still be viewed

**Steps to reproduce**: There are some things I want hidden in my mod, so I overrode `isHidden()` in them. However, there are some places where it still shows up anyways, like in the mod content list:
![content list](https://user-images.githubusercontent.com/54301439/115979166-31134f00-a539-11eb-9889-648e8a5bf626.png)
or in sources:
![liquid source](https://user-images.githubusercontent.com/54301439/115979296-ee05ab80-a539-11eb-99d1-543532e7615e.png)
![code](https://user-images.githubusercontent.com/54301439/115979302-f5c55000-a539-11eb-84e2-bcb00262d5e6.png)

**Link(s) to mod(s) used**: `MEEPofFaith/prog-mats-java`

~~oh no I didn't include a save Anuke is gonna reap my soul~~

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
For most content, `isHidden` is only used for the content database dialog.

- Liquid/item sources are for debugging, so I don't see much need to hide stuff there.
- The mod content dialog is for seeing everything the mod has, not for reference in-game.

**Comment by MEEPofFaith** [comment]
oh  ok
