### ISSUE TITLE
Distribute mod to android phone

### ISSUE THREAD

**Issue by Vortetty** [Anuken/Mindustry#516]
How can I package an Android APK file from a Linux terminal (will be using termux if you are interested) so I can package my modded game on the go.

**Comment by Anuken** [comment]
See [the libGDX documentation on packaging](https://libgdx.badlogicgames.com/documentation/gettingstarted/Packaging.html), specifically the Android section.

**Comment by Vortetty** [comment]
@Anuken anuken what would i have to do for a windows pc? would like to know so i can package the first apk with my pc to test the  mod n an emulator.

**Comment by Anuken** [comment]
It's the same command, only [without the ./ prefix.](https://github.com/libgdx/libgdx/wiki/Gradle-on-the-Commandline#packaging-for-android).

**Comment by Vortetty** [comment]
@Anuken Ok. So i tried this and it has not worked, this is what i did:

> C:\Users\ ____\mindustrypc\v4mod\Mindustry> gradlew android:assembleDebug


and this was the result of running it:

> Starting a Gradle Daemon (subsequent builds will be faster)
> No local.properties found. Not loading Android module.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Project 'android' not found in root project 'Mindustry'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 12s
> 
> C:\Users\ ___\mindustrypc\v5mod\Mindustry>

**Comment by Anuken** [comment]
When using the Android module, you need to define the location of your Android SDK by making a `local.properties` file in the Mindustry folder for Gradle to locate your SDK properly.

The contents should look like [this](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/local.properties), but with `%ANDROID_SDK%` replaced with the location of your Android SDK folder.

**Comment by Vortetty** [comment]
@Anuken i have done this with this error:

> C:\Users\ ___\mindustrypc\v5mod\Mindustry>gradlew android:assembleDebug
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> Configure project :android
> No keystore info property found!
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':android'.
> The SDK directory 'C:\Users\ ___\mindustrypc\v5mod\Mindustry\C:      ools' does not exist.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 6s

and my local.properties having:

> #Location of the android SDK
> sdk.dir=C:\tools

**Comment by Anuken** [comment]
It should be `C:\\tools`. `\` is a special character that needs to be escaped.

**Comment by Vortetty** [comment]
this has worked, than you @Anuken! i just need to set up all sdk's and accept the license agreements.
