### ISSUE TITLE
Conveyors Blend With Middle Bridges

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#5162]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
steam

**Issue**: *Explain your issue in detail.*
![image](https://user-images.githubusercontent.com/54417042/116325178-8779cb00-a78f-11eb-8396-0ec4594cdcf2.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

bXNjaAF4nE2LzQqDMBCEJ6l/pQfxQXyoqEvZg5sSY0F8dXGbmkN7GD6YbwZ3WItC3EwoB3Ky4DHRMgZ+RfYCWLRD4OlJ/ejlTZsP6CJHJ7zOvwpoUmBqVd1Vz8Oa9Exvg1tG8QUSrs1xrQ3KLKssm3/5AXeuJWM=

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
no

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [sortof] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Conveyors blend with all bridges regardless of whether they happen to be the middle or not.

**Comment by Legomonster33** [comment]
> Not a bug. Conveyors blend with all bridges regardless of whether they happen to be the middle or not.

ok but it still looks wrong

**Comment by Anuken** [comment]
no

**Comment by SheepCommander** [comment]
no
