### ISSUE TITLE
Remote connections denied, only local connections are allowed

### ISSUE THREAD

**Issue by uAliFurkanY** [Anuken/Mindustry#5163]
**Platform**: Linux

**Build**: 126.2 Client/Server

**Issue**:  
The built in server and the standalone server both only accept local connections (from interfaces that can be reached with `::` or `0.0.0.0`)  
Tried ngrok. It receives the initial message but still does not connect or ping in server list.  
($IP in the screenshot is my remote IP, but I blame that on my router since it's kinda... broken.)  
![Using netcat to check ports](https://user-images.githubusercontent.com/57134217/116432044-fc610980-a850-11eb-9f33-45d0b1857e4c.png)
![I did not include it, but my remote ip also shows the same thing as ngrok](https://user-images.githubusercontent.com/57134217/116432058-0125bd80-a851-11eb-81c7-cce52966c02e.png)  
This used to work back in v5. And I did not change my operating system since then.  
My ufw rules are empty and I disabled the firewall (which also had no rules) of my router.  
I'm using Linux Mint 20.1 with kernel linux-5.12.0-xanmod1-cacule  
I even used socat and wrote an [one-liner proxy in node](https://paste.mozilla.org/3LxVXjtJ#L1,1) to spoof the ip (as 127.0.0.1)  
Nothing worked. The server will **only** accept local connections.

**Steps to reproduce**: Just start a server. Does not matter if standalone or "Host Multiplayer Game".

**Save file**: [h.zip on mega.nz](https://mega.nz/file/lTIGiRTS#Knzc5TlK-Xjx3x2OSZ8C5I7v3jiDAVyjExjnZ6qho7A)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Judging by the fact that there is [an entire list](https://github.com/Anuken/Mindustry/blob/master/servers_v6.json) of servers that work fine with remote connections, this is a problem on your end, not Mindustry's.

**Comment by uAliFurkanY** [comment]
Well, it magically broke in v6

I guess you're too busy. Understandablle :)

**Comment by Anuken** [comment]
This can only be debugged on your end.

**Comment by RegenJacob** [comment]
i think it's maybe because Mindustry uses udp and not tcp

**Comment by Anuken** [comment]
That is false. Mindustry uses both.

**Comment by RegenJacob** [comment]
yeah right but ngrok only supports tcp
