### ISSUE TITLE
Electric-based turrets consume power when disabled

### ISSUE THREAD

**Issue by Kubek0212** [Anuken/Mindustry#5167]
**Platform**: *Android, Windows*

**Build**: 126.3

**Issue**: *Assuming turrets were already disabled by processor*: Meltdown, arc, lancer and foreshadow, when enemy reaches their range, despite not shooting, still consume power. Foreshadow doesn't consume surge thought.

**Steps to reproduce**: Disable turret by processor. Connect to power source (of any kind). When enemy enters its range player can notice power drain as if turret was shooting. Once enemy leaves, turret stops consuming power.

**Screenshot**:
![image](https://user-images.githubusercontent.com/33349024/116601529-e758a900-a92a-11eb-9669-0451d67173f4.png)

**Link(s) to mod(s) used**: Works with vanilla.  Once I used *deltanedas/unit-factory* to spawn units for testing.

**Save file**:  https://github.com/Anuken/Mindustry/files/6309673/mega.bug.report.zip

**(Crash) logs**: Bug doesn't crash the game.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kubek0212** [comment]
I've just noticed I didn't provide foreshadow with surge. Once I added item source, the power level decreased even more:
![image](https://user-images.githubusercontent.com/33349024/116601843-3b638d80-a92b-11eb-80b1-f5b735bf0624.png)

**Comment by Anuken** [comment]
Fixed in 7.0.
