### ISSUE TITLE
Wierd hit behaviour

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5168]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *This is Stellar, one of my turrets.*

![Screenshot_20210429-173942](https://user-images.githubusercontent.com/61173114/116632144-b3be5480-a913-11eb-90ff-a9c2929e9b5d.png)
*Now, Stellar is very happy about her life, but doesn't understand why her bullets don't spawn a frag on despawn if they pierce a unit (or multiple units) first.*
![Screenshot_20210429-174052](https://user-images.githubusercontent.com/61173114/116631617-9ccb3280-a912-11eb-9860-db008d4b0ad4.png)

**Steps to reproduce**: *Let Stellar rain hell on the antumbra, then manually control her and fire at something she won't be able to hit.*

**Link(s) to mod(s) used**: *K103908/Exotic-Mod.*

**Save file**: 
[aaaaaaaaaaaaaa](https://github.com/Anuken/Mindustry/files/6402231/a.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

i did it, are you happy now

**(Crash) logs**: *b*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

edit: github keeps bugging out about image uploads.

**Comment by Anuken** [comment]
In 6.0, bullets that have already hit something do not spawn frag bullets/extra effects when they despawn. 7.0 has different bullet logic.
