### ISSUE TITLE
Turret liquid consumption does not always match description

### ISSUE THREAD

**Issue by Lightforger** [Anuken/Mindustry#5169]
**Platform**: Windows

**Build**: 126.2

**Issue**: Some turrets use less liquid than the description says, examples being:
cyclone / scorch: 10/s (instead of 12)
spectre: 50/s (instead of 60/s)
meltdown: 12/s (instead of 30) -- only for water, and only when not currently firing

Additionally, while under an overdrive dome, almost all turrets use 10~20% less liquid somehow.

**Steps to reproduce**: As measured by hovering over the conduit in the test map

**Save file**: 
[liquid test.zip](https://github.com/Anuken/Mindustry/files/6402355/liquid.test.zip) (note, loud)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
