### ISSUE TITLE
iOS sound bugged when interrupted

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry#5171]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: If there are any interruptions to Mindustry while it is open, mainly just Siri, but anything else that pauses sound causes the sound, from the entire game to disappear until the app is restarted. Menu sound and in-game sound are both affected

**Steps to reproduce**: I dunno, the simplest way to reproduce this is to access Siri, from within the app, this just completely eradicates the sound, regardless of what the settings are for sound

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this.
