### ISSUE TITLE
On attack maps, wave timer is halved if wave spacing is 120 seconds

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#5172]
**Platform**: Windows (Steam)

**Build**: 126.3

**Issue**: On attack maps, wave timer is halved if wave spacing is set to 120 seconds.

This bug is not present in survival.

**Steps to reproduce**:
1. Create a custom attack map.
2. Set wave spacing to 120 seconds.
3. Start a custom attack game on that map.

| Wave spacing | First wave timer | Wave 2+ timer |
| - | - | - |
| 119 | 3:58 | 1:59 |
| 120 | 2:00 | 1:00 |
| 121 | 4:02 | 2:01 |

**Link(s) to mod(s) used**: None

**Save file**: [test_map.zip](https://github.com/Anuken/Mindustry/files/6403310/test_map.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
