### ISSUE TITLE
Copying bridge conveyors doesn't always copy the bridge.

### ISSUE THREAD

**Issue by pyokken** [Anuken/Mindustry#5183]
**Platform**: Linux

**Build**: steam build 126.3

**Issue**:

When copying two bridge conveyors connected by a bridge, the bridge between them is occasionally not copied. This was reported in #4343 and closed, but there seems to still be an issue.

**Steps to reproduce**:

Follow the exactly what is done in the attached video. The first three connect successfully but the fourth doesn't.
1. Open the attached map.
2. Copy a pair of bridges.
3. Build them in the spot shown in the video.

**Link(s) to mod(s) used**: None

**Save file**: [bridge_bug_map.zip](https://github.com/Anuken/Mindustry/files/6411913/bridge_bug_map.zip)

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/83549256/116821451-ebaddd80-ab47-11eb-8c56-fb3ec4252ff6.mp4

**Comment by Anuken** [comment]
Fixed in 7.0.
