### ISSUE TITLE
Megas (and possibly other units) sometimes shake when following the player.

### ISSUE THREAD

**Issue by pyokken** [Anuken/Mindustry#5184]
**Platform**: Linux

**Build**: steam build 126.3

**Issue**: When megas are controlled by the player, they sometimes shake back and forth when the player turns. This happens for a short time before they settle down. This may happen with other units, but I've only noticed it with megas.

**Steps to reproduce**:

See the attached video for an example.
1. Control a mega.
2. Command other megas to follow you.
3. Turn by tapping a directional key. Diagonal directions seem to reproduce this behavior more often.

**Link(s) to mod(s) used**: None

**Save file**: [mega_bug_map.zip](https://github.com/Anuken/Mindustry/files/6411957/mega_bug_map.zip)

**(Crash) logs**: None

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/83549256/116822366-755faa00-ab4c-11eb-8297-8ed7e8bc8189.mp4

**Comment by Anuken** [comment]
Won't fix.

**Comment by pyokken** [comment]
@Anuken Because it's low priority? If so, I can try fixing it myself and submit a pull request.
