### ISSUE TITLE
Meltdown sound continues playing while paused

### ISSUE THREAD

**Issue by pyokken** [Anuken/Mindustry#5190]
**Platform**: Linux

**Build**: steam build 126.3

**Issue**: If the game is paused while meltdown is firing, the sound will continue playing (indefinitely?).

**Steps to reproduce**:

1. Get meltdown to fire.
2. Pause game.

**Link(s) to mod(s) used**: None

**Save file**: [meltdown_sound_bug_map.zip](https://github.com/Anuken/Mindustry/files/6418486/meltdown_sound_bug_map.zip)

**(Crash) logs**: None

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/83549256/116948595-c5726580-ac4d-11eb-89ff-73728cbe58a8.mp4

**Comment by MrDuck557** [comment]
Game thinks:
If meltdown firing, play sound
it sadly doesn't take into account pausing the game, but it wouldn't be hard to implement

**Comment by Anuken** [comment]
Not a bug. All continuous sounds keep playing while the game is paused.

**Comment by pyokken** [comment]
Is this the desired behavior? I don't expect sounds (except music) to continue playing when paused in any game

**Comment by Anuken** [comment]
I suppose not, but the audio engine never really supported pausing sounds well, so it was never implemented. I'll look into it.

**Comment by oinkymoo** [comment]
probably not that important, but also happens with vela laser
