### ISSUE TITLE
Power nodes don't immediately update the displayed power

### ISSUE THREAD

**Issue by pyokken** [Anuken/Mindustry#5191]
**Platform**: Linux

**Build**: steam build 126.3

**Issue**: When a power node is created or newly connected to a power grid, it won't update its displayed power for about a second (more or less). This happens even though power consuming blocks update their behavior and displays immediately.

**Steps to reproduce**:

1. Build a power source and disconnected power consumer.
2. Connect the two with a node and pause the game shortly after.
3. Mouse over the node and it will likely display "+0/s" as the total power of the network.

**Link(s) to mod(s) used**: None

**Save file**: [power_bug_map.zip](https://github.com/Anuken/Mindustry/files/6418527/power_bug_map.zip)

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/83549256/116949389-04091f80-ac50-11eb-8a99-96079b0ba0e1.mp4

**Comment by BlueWolf3682** [comment]
This is because the node has to read the entire power network its on, which may take a while due to calculations

**Comment by pyokken** [comment]
Hmmm, but power consuming blocks seem to know immediately if they have power or not.

If this is the problem, it seems like the calculations could be sped up by storing each network in a graph data structure and then taking a union of those graphs when the networks are joined together. This is a pretty simple operation.

**Comment by Anuken** [comment]
> This is a pretty simple operation.

Feel free to implement a PR for it, then. This isn't a bug.
