### ISSUE TITLE
Plastsnium conveyor bug report

### ISSUE THREAD

**Issue by HelpMy2** [Anuken/Mindustry#5195]
**Platform**: `Android 26`

**Build**: `release build 126.2`

**Issue**: *plastsnium conveyor end was "opened" to armored conveyor's closed side*

**Steps to reproduce**: *I was building conveyors*

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *[bug_report_save.zip](https://github.com/Anuken/Mindustry/files/6419447/bug_report_save.zip)*

**Crash report**: *no crash report*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Fixed in 7.0.

**Comment by Quezler** [comment]
in bleeding edge actually ^

**Comment by OnyxFinger** [comment]
There isn't just that. same issues happen with belts having being "opened" to input bridges and plast conveyors being "closed" to cores and other type of stuff that aren't conveyors.
