### ISSUE TITLE
Multiplayer servers list lag when local server online

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#5198]
**Platform**: Windows 10

**Build**: Steam build 126.3

**Issue**: same as the title.

**Steps to reproduce**:
1. Open server using ``server-release.jar`` and host.
2. Now, go to Play -> Join Game. then you can see server list load lags.
![image](https://user-images.githubusercontent.com/44261958/117088758-5ea89580-ad8e-11eb-8ed8-36602482aea1.png)
Steam server, Local server, Remote server, same remote server.

**Link(s) to mod(s) used**: Vanilla.

**Save file**: None.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works fine for me.

**Comment by Kieaer** [comment]
@Anuken 
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/44261958/117132558-f4b7dc80-addd-11eb-9fb2-4b629dc68d63.gif)

**Comment by Anuken** [comment]
Again, it works fine for me. The server shows up in the list, and nothing lags.

**Comment by Kieaer** [comment]
This issue only appears in Steam builds.

**Comment by Anuken** [comment]
I was testing on Steam as well.

**Comment by way-zer** [comment]
![Snipaste_2022-11-14_17-21-08](https://user-images.githubusercontent.com/15688938/201623125-0e5c1d6c-1f52-4ab2-905f-02fc869404a9.png)
I get this in Windows. Stuck about 10 seconds
![image](https://user-images.githubusercontent.com/15688938/201623235-5155fc2a-f8bb-4a9c-8da8-d84c810c0b6b.png)

**Comment by Kieaer** [comment]
@Anuken

**Comment by Kieaer** [comment]
@Anuken

**Comment by Kieaer** [comment]
@Anuken
