### ISSUE TITLE
Resources stay red after being acquired in tech tree

### ISSUE THREAD

**Issue by ElishaAz** [Anuken/Mindustry#5199]
**Platform**: *Android*

**Build**: *126.2, from itch.io*

**Issue**: *In the tech tree, if a resource in the selected upgrade is empty, it doesn't go back to white after the resource was acquired*

**Steps to reproduce**: 
- *Open the tech tree in the campaign.*
- *Click on a upgrade that needs a resource that you do not have. The resource will be red*
- *Keep playing in the campaign to acquire the resource.*
- *Go back to the tech tree*
- *The resource will still be red, even if you have enough for the upgrade*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *[mindustry[1].zip](https://github.com/Anuken/Mindustry/files/6425471/mindustry.1.zip)*

![Screenshot_20210505-094403045](https://user-images.githubusercontent.com/26592879/117107083-b09aec80-ad89-11eb-833c-dd5f03efa204.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Reproduced successfully, Google Pixel 2.

**Comment by Darkness6030** [comment]
Oh no

**Comment by Anuken** [comment]
Fixed in 7.0.
