### ISSUE TITLE
Funding options

### ISSUE THREAD

**Issue by BeefEX** [Anuken/Mindustry#52]
There seems to be a lot of people asking for features that requier servers. That means we need a way to pay the bills for them.

Poll where people can vote:
http://poll.lab.io/XBTDep9mzxavlTkw7zjNlg

**Comment by Epowerj** [comment]
I did some math and figured out that a $25/month server should be more than enough to handle a server browser and map hosting for several thousand users. I've seen other free games have donation goals where you could see exactly how much money they need to stay afloat, and you can see the month's donation progress. I think this could work.

**Comment by cktang88** [comment]
@BeefEX would in-game purchases be mostly cosmetics?

**Comment by Luxray5474** [comment]
In-game purchases aren't the best idea, and makes the game inequal across different people. Just note that **I am completely with donations and funding for Anuke.** I'm simply saying that in-game purchases aren't the greastest of ideas.

Instead, we should focus on...
1. ...Making the content that's _already_ in the game _better_ and adding more of it. We have to give players a reason to donate to fund development and support the game other than having them buy stuff within the game. The only way to do that is to improve and add more free, but quality content inside the game.

2. ...Aquiring a larger audience. The larger the amount of players we have, the greater amount of people deciding to donate there would be. This could be done by making content related to the game on a large platform, like YouTube, where it's already being done.

3. ...Very lightly encouraging the players to donate. Not a prompt that pops up every 5 minutes telling the player to donate, but a little message that peeks out of the donate button every time the player opens the game. It's enough to incline the player to donate, but not too much that it annoys them.

But just to be safe, let's not do these, though:
1. Let's not make the game a P2P where you play to get stronger weapons. This may be far from anyone's minds right now but just a reminder for the future. Let's not get too desperate. 😉 

2. Let's not include ads. That should be the absolute last thing on anyone's minds right now and would outright be a plain degradation of the game.

Hopefully you agree with me on this. Again, I don't mean to say that Anuke shouldn't be given funds to pay for maintaining and developing the game. I'm just expressing my opinion on how I think people could donate to the development of the game, while keeping it a good game as it has always been.

**Comment by Anuken** [comment]
I'm definitely not planning on having ads, and after thinking about it, there's no good way to add cosmetics to the game either.

Increasing donations might work, but at the same time I don't think it's going to increase profits by much. We'll see. I'm hoping that I might be able to get most of my profits by selling the game on Steam, while keeping it free on itch.io/Google Play, like some other indie games have done in the past.

**Comment by Anuken** [comment]
Closing, as the core funding methods have been decided (Steam, iOS store, Mac store, possibly UWP as well).
