### ISSUE TITLE
Some little bugs ;-:

### ISSUE THREAD

**Issue by CrismonWolf** [Anuken/Mindustry#5200]
**Platform**: `Android 29`

**Build**: `release build 126.2`

**Issue**: *So.... These days I played a lot of Mindustry and noticed two little bugs, which bother some players and other not. But to explain better, sometimes when I play Mindustry and out of app for a few moments to watch some video or do something else, I usually left it open in background, but, when I return, sometimes the game became mute, then I restart the game to it come back to normal. I don't know if this one is really a bug, or just a problem with my phone, but if it's a bug, I'm happy to help reporting it. The second one is about the waves, when you're the planet map, it shows to you some details of the sectors you captured or is fighting to capture, the times I noticed the wave counter was showing something very different from the real waves in the sector, to exemplify, yesterday I capture de Tar Fields, when I was looking on map I saw the wave counter of the sector showing something very aleatory like 4/14, and this sector have 40 waves, and this happened in other sectors too. And sorry if I wrote something wrong or I made a grammatical mistake, I'm from Brazil and still learning english.*

**Steps to reproduce**: *To be more exactly, about the game become suddenly mute, it occurred in two situations, some days ago and a ago. Before I start to written this I was playing Mindustry and my mother called me by cell phone, to ask something, and when I came back, the game was mute. And about leaving the game running in background while I was doing other things, I think it was about an 30 minutes to a hour.*

**Link(s) to mod(s) used**: `none`

**Save file**: *Well... I don't know how put it here by cell phone, so please use this link to access my save files: https://drive.google.com/file/d/1QGQzIAjq9I6LbY2XDxqGbfb0UpFSJxSR/view?usp=drivesdk*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> when I was looking on map I saw the wave counter of the sector showing something very aleatory like 4/14, and this sector have 40 waves,

Sectors do not display a wave counter, they display survival stats.

> sometimes the game became mute

Duplicate.
