### ISSUE TITLE
Random crash in middle of the game. happened twice now

### ISSUE THREAD

**Issue by wojtekpolska** [Anuken/Mindustry#5211]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: *Random crash in middle of the game. happened twice now*

**Steps to reproduce**: *Just played the game long enough*

**Link(s) to mod(s) used**: `none`

**Save file**: *Online server, happened twice on different maps*

**Crash report**: *I dont know where to find it, below is what i've got*

![image](https://user-images.githubusercontent.com/58272360/117364326-0bcdfb80-aebe-11eb-8b74-b235ce7c59e2.png)
[last_log.txt](https://github.com/Anuken/Mindustry/files/6437618/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, cannot be fixed.

**Comment by wojtekpolska** [comment]
> Duplicate, cannot be fixed.

?

**Comment by BlueWolf3682** [comment]
https://github.com/Anuken/Mindustry/issues/4364

**Comment by wojtekpolska** [comment]
> #4364
> oh wait wrong one

also no explanation here 
what do i do to fix this?

**Comment by wojtekpolska** [comment]
> You don't.

so the game is supposed to randomly crash?

**Comment by BlueWolf3682** [comment]
No, but it isn't something Anuke can fix. 
Your best option is to use a different OS.

**Comment by wojtekpolska** [comment]
> No, but it isn't something Anuke can fix.
> Your best option is to use a different OS.

I use Windows 10, what do u mean different OS?

**Comment by Aernan1** [comment]
Yeah I have same issue just don't worry about it
