### ISSUE TITLE
When targeting a core, a unit's weapons will fire at the rate of its slowest reloading weapon.

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5213]
**Platform**: *Android*

**Build**: *126.2.*

**Issue**: *Title.*

**Steps to reproduce**: *Watch.*

**Link(s) to mod(s) used**: *Irrelevant. Exotic Mod is enabled so make sure you have it for corruption reasons.*

**Save file**: 
[the the](https://github.com/Anuken/Mindustry/files/6439011/amazing.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

doo dee doo

**(Crash) logs**: *b*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

most descriptive bug report of 2021

**Comment by MEEPofFaith** [comment]
"Fixed in 7.0"

**Comment by Erisfiregamer1** [comment]
fixed in 7.0 is not the answer, **when 7.0** is the true question

**Comment by Anuken** [comment]
The Toxopid's other weapons aren't in range of the core, so they don't fire.

**Comment by BlueWolf3682** [comment]
> The Toxopid's other weapons aren't in range of the core, so they don't fire.

Then why don't they target the safes that are in range? Also:
![Screenshot_20210507-114532](https://user-images.githubusercontent.com/61173114/117488572-d101ad00-af29-11eb-896c-ad4504ecf3f9.png)
Moving the toxopid closer confirms this.

**Comment by MEEPofFaith** [comment]
Yea, I don't see it either.

https://user-images.githubusercontent.com/54301439/117496660-3787ca80-af2c-11eb-9572-8a1c838d8f48.mp4

**Comment by BlueWolf3682** [comment]
> > Then why don't they target the safes that are in range?
> 
> The target is the core, which is only in range with the cannon.

...Aren't units supposed to be able to have multiple tagrets?

> 
> > Moving the toxopid closer confirms this.
> 
> Confirms what, exactly? When moved closer, the toxopid fires with all weapons at exactly the same rate as a player-controlled one in any other situation.

Strange, I've noticed that the fuses were firing slower for some reason. Maybe the secondary weapons were targeting my unit instead? I don't know, all I know is I've reproduced this with two different units (other one being the mod's Ghost unit.

**Comment by Anuken** [comment]
> ...Aren't units supposed to be able to have multiple tagrets?

Only some of them, and only when not near the core.
