### ISSUE TITLE
Launch schematics don't properly connect power

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry#5216]
**Platform**: Mac

**Build**: 126.2

**Issue**: when launching with attached schematic, no power reaches one of the reconstructors
<img width="1280" alt="Screen Shot 2021-05-07 at 11 16 55 AM" src="https://user-images.githubusercontent.com/75851043/117471191-9ac22e80-af25-11eb-8df1-6742cb4eb0df.png">

**Steps to reproduce**: launch with the schematic. power connects fine if the schematic is placed manually. doubt its relevant, because this happens every time I've launched with this schematic or the previous iteration, but the materials I brought were 9000 of every material in the screenshot, except for coal, of which I brought 1000

**Link(s) to mod(s) used**: none

**Save file**: 
sorry if this is too much this is my first bug report
[saves.zip](https://github.com/Anuken/Mindustry/files/6442788/saves.zip)

schematic mentioned above
[buggySchem.msch.zip](https://github.com/Anuken/Mindustry/files/6442817/buggySchem.msch.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
