### ISSUE TITLE
Schematic disappears when clearing space

### ISSUE THREAD

**Issue by midmm5** [Anuken/Mindustry#5217]
**Platform**: *mac and maybe others*

**Build**: *build 126.2.*

**Issue**: *schematic delete when clearing space*

**Steps to reproduce**: *try to place schematic then delete some blocks that are already placed and part of schematic is removed*

**Link(s) to mod(s) used**: *none.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No screenshots, no save, no schematic files linked. I have no idea what you mean.

**Comment by oinkymoo** [comment]
as i understand it, this isn't even a bug either. deleting blocks that are planned or, in your case, deleting blocks that already exist in the same place as the plan will clear those blocks from the plan, meaning they never get built.

**Comment by midmm5** [comment]
Uploading Untitled.mov…



> as i understand it, this isn't even a bug either. deleting blocks that are planned or, in your case, deleting blocks that already exist in the same place as the plan will clear those blocks from the plan, meaning they never get built.

i dont think its that

**Comment by midmm5** [comment]
> No screenshots, no save, no schematic files linked. I have no idea what you mean.


Uploading 2021-05-07 10-28-05.mp4…

its for all schematics

**Comment by oinkymoo** [comment]
buildings will only be added to the plan anyway if there is already space for them. the reactor, for example, isn't getting added to the plan because there is wall in the way. you then delete the obstructing wall, and it doesn't get build because it's not in the plan
