### ISSUE TITLE
part of schematic disappears when clearing space (video)

### ISSUE THREAD

**Issue by midmm5** [Anuken/Mindustry#5218]
**Platform**: *Mac and maybe more*

**Build**: *126.2

**Issue**: *when i place schematic over things and delete the things blocking it but it removes part of schematic*

**Steps to reproduce**: *place something then try to place schematic over it and try to clear the things block it but then it will make the schematic disappear.*

**Link(s) to mod(s) used**: *none*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** ( i put a closed report tho) 

https://user-images.githubusercontent.com/83832266/117480955-867b3300-af1f-11eb-84da-fc7008f3e150.mp4

- [ ]

**Comment by Anuken** [comment]
I see no bugs in that video.
