### ISSUE TITLE
Non sharded fortress cannot shoot over blocks

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#5219]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Steam/windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

126.2

**Issue**: *Explain your issue in detail.*

When commanding fortress units that are not on sharded team and attempting to fire over walls, the projectiles explode on the nearest wall, conveyor, etc instead of going over it and acting like an artillery shot.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Have a wall or obstruction, be commanding a fortress unit that is NOT on sharded team and attempt to fire past the wall.

Either be in a pvp match or use the mods below to switch teams *if you cant do it yourself already*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

https://github.com/MEEPofFaith/testing-utilities
https://github.com/MEEPofFaith/TimeControl
https://github.com/MEEPofFaith/unit-factory
https://github.com/DeltaNedas/ui-lib

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[fortress.zip](https://github.com/Anuken/Mindustry/files/6443352/fortress.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

much crashing evry tiem ;-;
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment]
Reproduced

**Comment by Anuken** [comment]
Fortresses on *any* team hit enemy blocks on contact. This is intentional.

**Comment by the-red-soul** [comment]
sharded bullets can go over when you are commanding the units. this is also the behaviour in pvp where sharded controlled fortress go over walls, but no other team can

**Comment by Anuken** [comment]
> sharded bullets can go over

No.

![2021-05-07-14-15-29](https://user-images.githubusercontent.com/10100000/117491809-b128b400-af3e-11eb-8ae6-6c113d86a708.gif)
