### ISSUE TITLE
Craters enemy wave glitch

### ISSUE THREAD

**Issue by HiImBlahh** [Anuken/Mindustry#5223]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*
Crater kept going on after wave 20
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was playing the game normally, until i noticed that the wave# was above 20
**Link(s) to mod(s) used**: `[Slava0135/revision:10.1, MaxSMoke/smoa-n:2, Xelo/xelos-pixel-texturepack:0.4.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[mindustry save 2.zip](https://github.com/Anuken/Mindustry/files/6446621/mindustry.save.2.zip)
this is not the exact save, but it is pretty close
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by HiImBlahh** [comment]
> Craters isn't even unlocked in that save.

ok i will just make a new save of what i have now

**Comment by HiImBlahh** [comment]
here: 
[mindustry save 3.zip](https://github.com/Anuken/Mindustry/files/6446753/mindustry.save.3.zip)

**Comment by HiImBlahh** [comment]
> here:
> [mindustry save 3.zip](https://github.com/Anuken/Mindustry/files/6446753/mindustry.save.3.zip)

craters is unlocked in this save. i thought the save i listed before had craters unlocked. sorry

**Comment by Anuken** [comment]
That save doesn't even base in the craters map either.

**Comment by HiImBlahh** [comment]
> That save doesn't have a base in the craters map either.

because i lost the game

**Comment by Anuken** [comment]
How do you expect me to test it then? There's no indication of anything wrong with the waves when I land there.

**Comment by HiImBlahh** [comment]
> How do you expect me to test it then? There's no indication of anything wrong with the waves when I land there.

ok i will replay craters and once it is in wave 21 i will give the save to you

the only reason I waited until I lost is that I thought I had to research a kiln to capture the sector since the database says to smelt metaglass.
