### ISSUE TITLE
Black terrain graphic glitch

### ISSUE THREAD

**Issue by Prime4212** [Anuken/Mindustry#5234]
Platform: Windows

Build: release build 126.2

Issue: when i play campaign game, when i look aroung some terrain not loaded or black
![gambar](https://user-images.githubusercontent.com/84029684/117842914-90e35700-b2a8-11eb-8753-5991bfdec94a.png)

Steps to reproduce: i just play the campaign game(first play), and when i look around i found some terrain still black.

Link(s) to mod(s) used : no mod used

Save file :  
[Save file campaign.zip](https://github.com/Anuken/Mindustry/files/6460386/Save.file.campaign.zip)

(Crash) logs: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Prime4212** [comment]
Can i fix this without fixing my graphic card/driver? because intel not suport my graphic card anymore or end of life.

**Comment by Anuken** [comment]
I have no experience with such cards or their drivers, so I can't say.

**Comment by Prime4212** [comment]
I have a new issue should i make new report or comment and add the crash log here?
