### ISSUE TITLE
Units weapons stay behind

### ISSUE THREAD

**Issue by 3Snake3** [Anuken/Mindustry#5237]
Platform: Android

Build: 126.2

Issue: The air units lost their weapons

Steps to reproduce: When building units flying to build or deconstruct building, their weapons stay behind.

Links to mods used: 
3Snake3/ADC
SnakkiZXZ/Coppermod

Save file: [Save file bug.zip](https://github.com/3Snake3/Pictures/blob/master/bug.zip) 

Crash log: -

![Screenshot_2021-05-13-14-27-10-175_io anuke mindustry](https://user-images.githubusercontent.com/83782383/118106548-4da3f800-b410-11eb-8a2a-3798bd91990e.jpg)
![Screenshot_2021-05-13-16-34-37-122_io anuke mindustry](https://user-images.githubusercontent.com/83782383/118106583-54cb0600-b410-11eb-8d30-d75c3498630b.jpg)
![Screenshot_2021-05-13-16-38-35-734_io anuke mindustry](https://user-images.githubusercontent.com/83782383/118106609-5a285080-b410-11eb-952e-9458601f74e9.jpg)

**Comment by Dinistor** [comment]
I was trying to recreate this issue (mobile version, installed ADC v6.3 and Copper Mod v2.4.1) and didn't find it in single player game. Next, i tried this in campaign, and again, no results. Also i think this is more mod's problem, than game itself.
![pic1](https://user-images.githubusercontent.com/73835049/118122712-e54b1b80-b3fb-11eb-8df5-d559f2351d37.png)
![pic2](https://user-images.githubusercontent.com/73835049/118122966-3fe47780-b3fc-11eb-853a-c1dda80c2901.png)

**Comment by 3Snake3** [comment]
> I was trying to recreate this issue (mobile version, installed ADC v6.3 and Copper Mod v2.4.1) and didn't find it in single player game. Next, i tried this in campaign, and again, no results. Also i think this is more mod's problem, than game itself.
> ![pic1](https://user-images.githubusercontent.com/73835049/118122712-e54b1b80-b3fb-11eb-8df5-d559f2351d37.png)
> ![pic2](https://user-images.githubusercontent.com/73835049/118122966-3fe47780-b3fc-11eb-853a-c1dda80c2901.png)
> 
> 

Ok, this problem did not appear again, but if it happens again, I will try to understand in more details what is it.
