### ISSUE TITLE
"Join Game" window resizing causes remote servers list to refresh

### ISSUE THREAD

**Issue by Hypoon** [Anuken/Mindustry#5241]
**Platform**: Linux

**Build**: 126.2

**Issue**: Remote servers list refreshes whenever you change the window size. This might not be too serious, but it's definitely unexpected behavior. If all the servers are being pinged every time you resize the window, that could be a problem, too.

**Steps to reproduce**: Connect to a remote server by IP address, then turn off that server (in my case, it was a hosted multiplayer game, not a dedicated server). The "Remote Servers" list in the "Join Game" menu will list the IP address and say "Can't connect to host." Whenever you adjust the window size, it changes to "Refreshing server...", sometimes just for an instant before switching back to "Can't connect to host.". I have not checked to see whether this is just a GUI bug or whether it actually does reach out to the server again every time the window size changes.

**Link(s) to mod(s) used**: None

**Save file**: This is not an in-game bug.

**(Crash) logs**: This is not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hypoon** [comment]
Also, the community servers list disappears after resizing the window a few times, too.

**Comment by Anuken** [comment]
Intentional.
