### ISSUE TITLE
Launch Pad bug

### ISSUE THREAD

**Issue by SAMBUYYA** [Anuken/Mindustry#5243]
**Platform**: *Windows*

**Build**: *126.2*

**Issue**: *Maybe for the launch pad have a bug.*

**Steps to reproduce**: *Maybe the bug begin after i send a resource with launch pad and after this i turn off the power. And the target destination get more resource if i wait in destination sector for a minutes.*

**Link(s) to mod(s) used**: *Nothing.*

**Comment by Dioo0** [comment]
where save file?

**Comment by Anuken** [comment]
Not a bug.
