### ISSUE TITLE
[Bug] Mindustry doesn't track mouse cursor location (android)

### ISSUE THREAD

**Issue by DayatXD** [Anuken/Mindustry#5250]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.2

**Issue**: *Explain your issue in detail.*
The game didn't track the mouse cursor location, but if hold left click now the location its follow the cursor, its should be follow the cursor without clicking button!

I know anuken will doens't want to fix this, but maybe someone will, idk, the only problem playing with mouse and keyboards on mindustry is just this one issue...

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just try place building, it will not follow the mouse cursoe

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
https://github.com/DeltaNedas/mobile-ui

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DayatXD** [comment]
https://user-images.githubusercontent.com/47524544/118386405-e2456a80-b649-11eb-814b-b5e234e73eba.mp4

There is the video when i trying to select deleting something

**Comment by MrDuck557** [comment]
Probably messiness from assuming that you're using touchscreen rather than mouse

**Comment by Anuken** [comment]
Mindustry doesn't support mouse cursors on Android.

**Comment by DayatXD** [comment]
> Mindustry doesn't support mouse cursors on Android.
then remove that option
![Screenshot_2021-05-20-17-37-49-743_io anuke mindustry](https://user-images.githubusercontent.com/47524544/119103588-ec9ea480-ba4d-11eb-8434-40484da06a25.jpg)

**Comment by Anuken** [comment]
> then remove that option

No. It works on Chromebooks, and on certain devices.
