### ISSUE TITLE
Building schematics / cloning by the `f` key: please always construct processors as the last elements

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry#5251]
**Platform**: `Windows 10 x32`
**Build**: `custom build`
**Issue**:

If a schematic is cloned using the `f` key or constructed from the schematics list, 
then it would be great if processors are always constructed as the last elements.

**If this is not done, the processor starts the script before the blocks are constructed, which are referenced by the script.** Then, scripts can behave strangely or even are blocked.

At the moment, we must use a workaround in each script to prevent this issue:

- Either the initialization has to be done at the beginning of each iteration, which costs unnecessary performance each time.
- Or the script must wait for a referenced block until it is no longer null which needs 3 instead of only 1 line of code 😞 :

```
jump 2 notEqual message1 null
jump 0 always 0 0
set LinkedMsgBlock message1
print "\nHello world"
printflush LinkedMsgBlock
end
```

**Steps to reproduce**: 
1. Build a structure from a schematic
2. Processor-Blocks are not constructed as the last Blocks

**Link(s) to mod(s) used**: (I think it's not necessary)
**Save file**: (I think it's not necessary)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug.
