### ISSUE TITLE
Glitch Export

### ISSUE THREAD

**Issue by Aernan1** [Anuken/Mindustry#5253]
**Platform**: Windows

**Build**: 126.1
**Issue**: I made some launch pads in my base to export surge alloy to impact 0078, removed the launch pads, and the suge kept getting exported

**Steps to reproduce**: I just made a export in campaign from my hub to impact 0078 and then removed the launch pad. (My hub is Tar Fields)

**Link(s) to mod(s) used**: I used braindustry, chaos arannity and diamond ore mod. But I don't think it was that.

**Save file**: 
[Save.zip](https://github.com/Anuken/Mindustry/files/6490637/Save.zip)
I think this is what you want?

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** no I am on 126.1 not 126.2
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, this has been explained many times.

**Comment by Aernan1** [comment]
well how do I stop the export?

**Comment by Anuken** [comment]
Stay at the exporting sector for a minute to normalize export rates.
