### ISSUE TITLE
Bridge Conveyor stops transporting resources

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry#5256]
Good morning

**Platform**: `Windows 10 x64`
**Build**: `release build 126.2`

**Issue**: 
A Script controls two Bridge Conveyor (which are next to each other) and therefore, the Bridge Conveyors are often switched on and off. Now it happens every day that these two bridge conveyors suddenly stop transporting resources, even though the conditions are right: 
- the source Container has resources
- the unloader unloads an existing or all resources
- the target Container has free space for the transported resource
- All components are enabled :-)

*Explain your issue in detail.*
In the attached Zip-File I have a Sandbox in which I test Mindustry Scripts.
The script controls the deployment of resources from Containers to the following structure, therefore, the two Bridge Conveyor in the red rectangle are often switched on and off.

![image](https://user-images.githubusercontent.com/8282673/118457623-3c056d80-b6fa-11eb-9deb-e873db689159.png)

#### To debug it...

I have started to remove all blocks around the two Bridge Conveyor until I had: (see the following picture)
(1) The Bridge Conveyor which does not wand to transport resources
(2) The two switches sets the enabled Property of each Bridge Conveyor 
(3) Those message-boxes just counts and displays the number of units in the game

bwt: I also have disconnected the Bridge Conveyors and reconnected them again. Did not solved the issue.

![image](https://user-images.githubusercontent.com/8282673/118458879-758aa880-b6fb-11eb-85d9-9d8868449014.png)

#### Debug-Result
* Unfortunately, removing all unnecessary blocks did not solved the issue: the Bridge Conveyor do not wand to transport resources
* Because I had two Bridge Conveyor which stopped working, I have deleted the left one and recreated it afterwards. Now, the resources were transported again. **This means that the problem is almost certainly in the Bridge Conveyor source code itself.**

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
It's hard to reproduce, I just debug my script and suddenly, the Bridge Conveyor stops transporting resources.

**» Please let me know if I can do something to help to find this issue.**
Because I will continue to debug my script, this issue will happen again.

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened.
Here, I have an overview of the Map. In the red box there is the Bridge Conveyor which is not willing to do it's work:
![image](https://user-images.githubusercontent.com/8282673/118461050-8b00d200-b6fd-11eb-8ddd-92f50328afd1.png)

[Tom, Bridge Conveyor is dead.zip](https://github.com/Anuken/Mindustry/files/6492311/Tom.Bridge.Conveyor.is.dead.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by schittli** [comment]
### I've just tested one more idea: **I have replaced the source Bridge Conveyor:**

**(1)** and **(2)** are the original, not working Bridge Conveyors.
Therefore I've tried to feed the **(2)** Bridge Conveyor from a newly created Bridge Conveyor **(3)**:
![image](https://user-images.githubusercontent.com/8282673/118462321-d667b000-b6fe-11eb-8528-6133f05dcc54.png)

#### The result: 
1. The **(3)** Bridge Conveyor is filled with resources until its stock of 10 Items is full.
2. But the **(2)** Bridge Conveyor does not transfer the resources. 😞

**Comment by schittli** [comment]
I've tested it the other way around, too - without success:
* The defective Bridge Conveyor **(1)** no longer deliver Resources to the defective Bridge Conveyor **(2)** 
* but the defective Bridge Conveyor **(1)** deliver Resources to the newly created Bridge Conveyor **(3)** 

![image](https://user-images.githubusercontent.com/8282673/118468926-88a27600-b705-11eb-94e6-d5fbaff3735f.png)

Unfortunately, the resources are not transported.
Therefore, the issue of the defective Bridge Conveyor is in both parts, the sender and receiver Bridge Conveyors.

**Comment by MrDuck557** [comment]
this goes in #logic

**Comment by schittli** [comment]
Hello @Anuken and @MrDuck557 

I would be **very** surprised if this is a script problem because a script must be able to switch a Bridge Conveyor on and off endless. In the end, if the Bridge Conveyor is enabled, it must always transport resources.

That's why I would bet that Bridge Conveyors can get jammed every now and then. 

The future will probably show :-)

**Comment by BlueWolf3682** [comment]
I may have a save on my phone with the exact same issue. 
I'm not sure if it's still working - I have used the save since the issue and fixed it by replacing the bridges.
