### ISSUE TITLE
Hyperspeed transfer bug

### ISSUE THREAD

**Issue by ThebestkillerTBK** [Anuken/Mindustry#5258]
**Platform**: *All*

**Build**: *v126.2.*

**Issue**: *Like the old overflow gate/sorter bug, hyperspeed transfer.*

**Steps to reproduce**: *Build an item source and the schematic down below. The game will output items instantly.*

**Link(s) to mod(s) used**: *None.*

**Schematic file**: 
[schematic.zip](https://github.com/Anuken/Mindustry/files/6493513/1621251737835.zip)

**(Crash) logs**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
![Screenshot_20210517-055430](https://user-images.githubusercontent.com/61173114/118484375-617f8080-b6d4-11eb-9dea-4b562a1afcbb.png)
I don't think it matters. The throughput is less than a titanium conveyor.

**Comment by ThebestkillerTBK** [comment]
> I don't think it matters. The throughput is less than a titanium conveyor.

But it can do hyperspeed transfer

**Comment by BlueWolf3682** [comment]
Throughput matters, not speed. There's already another known instant
transfer option known that is also less throughput than a titanium conveyor.

**Comment by ThebestkillerTBK** [comment]
Yes. The unloader slows it down. Throughput is also slowing the machine.
