### ISSUE TITLE
When rally points can't be reached, units don't move, but once path found, they don't need it

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#5260]
**Platform**: Windows/Linux server

**Build**: 126.2 or BE 21068

**Issue**: This can be intentional, but I haven't found any reference in older issues (except something similar from #3893) and that issue confuses me, so: depending on order of placement of walls OR command center (CC) I can get both ground units that are stuck next to payload OR on place of old rally point OR somewhere in between.

**Steps to reproduce**: Here is what I mean by that:
- below: Units "remember" the place of the old rally point and use old blocks' center to group later, which looks weird and (obviously) resets after save load.
![pathfinding_rally_field3](https://user-images.githubusercontent.com/4199082/118520696-ef925000-b742-11eb-9e55-57a4cf37626d.gif)

- below: Units can't reach the bottom CC because the way is blocked.
- below: Units can reach the middle CC (built later), but once I block the path they *still* try to reach it (*why? the point is not reachable, like for the bottom CC*).
![pathfinding_rally_field](https://user-images.githubusercontent.com/4199082/118518196-8dd0e680-b740-11eb-8f42-cde8f56ab241.gif)

- below, more like a side note: Units don't seem to prioritize reachable rallypoint to unreachable.
![pathfinding_rally_field2](https://user-images.githubusercontent.com/4199082/118519058-6f1f1f80-b741-11eb-9a0b-09dc46b3cd73.gif)

So, the general idea which confuses me here: for the same *state* I (as a player) get different *results*.

**Link(s) to mod(s) used**: no mods

**Save file**: [suicide_ai_test.zip](https://github.com/Anuken/Mindustry/files/6495146/suicide_ai_test.zip)

**(Crash) logs**: not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Units "remember" the place of the old rally point and use old blocks' center to group later, which looks weird and (obviously) resets after save load.

There is no valid route to the rally point, and with no path, nothing gets updated, which means the last path stays around.

> below: Units can reach the middle CC (built later), but once I block the path they still try to reach it

...because it's the last valid path.

> below, more like a side note: Units don't seem to prioritize reachable rallypoint to unreachable.

There is no concept of 'reachability' - if they're near a command center, that's good enough. There's no particular reason for them to stop moving once they reach it.
