### ISSUE TITLE
A way to consistently crash the game. 

### ISSUE THREAD

**Issue by wojtekpolska** [Anuken/Mindustry#5267]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: *Trying to copy half-deleted Spore Cluster (and some other decoration objects) will crash the game*

**Steps to reproduce**: *[Make sure you are NOT in "Sandbox" mode, because it has instant block deletion.]
find a spore cluster(few other objects also work), start deleting it, before the deletion finishes pause it (E default), and click on it to try to rebuild. now try to copy this object (F default) - the game crashes 100% of the time. You can follow this video if you need help reproducing: https://youtu.be/QwzY5t-Al1M *

**Link(s) to mod(s) used**: `none`

**Save file**: *I have tested this many times, it can be reproduced on *ANY* map, including all official ones that include the Spore Cluster*

**Crash report**: [crash-report-05_18_2021_20_52_01.txt](https://github.com/Anuken/Mindustry/files/6503641/crash-report-05_18_2021_20_52_01.txt)
![Crash](https://user-images.githubusercontent.com/58272360/118708973-b62e1300-b81c-11eb-998c-d85b4465e923.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed in 7.0.
