### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by abdallah362** [Anuken/Mindustry#5268]
**Platform**: *Windows*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.
126.2*

**Issue**: *crash*

**Steps to reproduce**: * i was just in logic processor and the game crash*

**Link(s) to mod(s) used**: *DeltaNedasdev-mode deltanedasldb deltanedasoverride-lib DeltaNedasui-lib DeltaNedasunit-factory Redstonneur1256Mindustry-RedUtilities*

**Save file**: 
[map_16.zip](https://github.com/Anuken/Mindustry/files/6504583/map_16.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *
[crash-report-05_19_2021_00_28_32.txt](https://github.com/Anuken/Mindustry/files/6504591/crash-report-05_19_2021_00_28_32.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed.

**Comment by abdallah362** [comment]
oh really ok then sorry
