### ISSUE TITLE
item re-write?

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#527]
I was thinking of re-writing some of the item descriptions with more lengthy ones.
then I realised that would mean re-translating everything

I meekly request  for someone to sample my work
to see if i should continue or not

Surge alloy:
> a high capacity electrolytic cell based on silicon  with a titanium shell, used for high voltage applications such as energy shielding and heavy electrical based defences.

Cyclone:
> A heavy rotary cannon with a high fire rate. can accept explosive ammunition, as well as electrolytic type ammunition like surge alloy.

Slag: (i noticed this doesn't have a desc.)
> Molten ferrous scrap, consisting of many usable materials that can be seperated from unusable  substances.

Differential generator:
> a large semiconductor based TEG generator that transforms heat flux into electrical power. requires a heat source and a ground coolant source.

oof (I can make these longer, i just haven't spent much time on them.)

**Comment by johnnieboye** [comment]
My translations for my first language would heavily simplify and lose much of the details and adjectives you include. Apologies.

**Comment by Arkanic** [comment]
@johnnieboye that was what i kinda meant with the whole translating thing.
sorry

**Comment by Prosta4okua** [comment]
He did not create descriptions. Descriptions were created by players. If you want to change descriptions, you can create pull request.

**Comment by Arkanic** [comment]
@Prosta4okua i know, i was just thinking about translation issues that could be a problem later on.
Thanks, tho
ill start now

**Comment by Arkanic** [comment]
@Prosta4okua do you think i would be able to slowly edit the items desc. bit by bit?
it's pretty large for one commit, so i might make a txt document on my laptop, then once it's done, ill ctrl-c ctrl-v it over.
sound good?

**Comment by Arkanic** [comment]
okay, i think everything's been resolved.
