### ISSUE TITLE
Multiplayer desync of logic blocks

### ISSUE THREAD

**Issue by atenfyr** [Anuken/Mindustry#5270]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Steam build 126.3

**Issue**: *Explain your issue in detail.*

When a logic display is connected to a processor and drawn on continually, the logic display seems to desync in multiplayer along with any messages that the processor is printing to.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

I came across this issue while implementing a version of Pong. I wrote a logic program for use with a Hyper Processor that clears a Large Logic Display and draws several rectangles and polygons onto the display nearly every cycle of the processor. When I attempt to run my program in multiplayer, the position of the "ball" (a small 20-sided polygon drawn and flushed onto the display at different locations nearly every cycle) differs wildly after maybe 30 seconds of active play between the host and the client, along with the values of the two linked messages that indicate score. I would expect the pixels that display on the logic display as well as the messages that the processor is printing to to be synchronized between clients.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

In this save file, the switch controls whether or not the processor is active and flushing to the display. I have also attached a zipped copy of a text file with the logic that led to the desync if you need it: [0.zip](https://github.com/Anuken/Mindustry/files/6504929/0.zip), [Pong.txt](https://github.com/Anuken/Mindustry/files/6504937/Pong.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This will never be fixed.

>  I would expect the pixels that display on the logic display [...]

The server doesn't even have the *capability* of drawing graphics, let alone syncing **entire bitmaps** across the network.

> as well as the messages that the processor is printing to to be synchronized between clients.

This would cause severe packet spam.

**Comment by atenfyr** [comment]
Hi @Anuken,

I don't mean to suggest one particular implementation to resolve this issue; I wouldn't expect the whole bitmap for all logic displays to be drawn on the server and synced to the client, although I'm obviously not experienced with Mindustry's netcode, so I can't come up with a good alternate solution for you as I write this.

Take what I say here as an inquiry from lack of experience: overall, I would think that it is a significant problem if what is being executed or stored within logic blocks desyncs so quickly. If you are operating on more than one person's input, but what is processed and displayed varies greatly between clients, are logic blocks really functional at all in multiplayer, since the game is accepting the same input and spitting out wildly different outputs (when part of the purpose of networking code is to ensure that changes made on one client show up properly on another)? In a technical respect, if you were to write a program to use multiple player inputs for controlling one unit and the unit appeared in completely different locations or with completely different rotations for different people, what is the tangible difference between that and the current desyncing of logic displays/messages?

Yours,
adolescent

**Comment by Anuken** [comment]
> if you were to write a program to use multiple player inputs for controlling one unit and the unit appeared in completely different locations

This can't happen, because all unit positions/state are synced.

> what is the tangible difference between that and the current desyncing of logic displays/messages?

The difference is that unit positions are orders of magnitude more important than some circle on a display.

> are logic blocks really functional at all in multiplayer

As long as you don't play time-sensitive minigames on them, yes, they are. I have not seen a single functional schematic of this kind that actually influences gameplay.
