### ISSUE TITLE
Insufficient resources on blowing up core and going back.

### ISSUE THREAD

**Issue by GitBobCat** [Anuken/Mindustry#5274]
Platform: Linux

Build: 126.2

Issue: I enter Impact 0078 for the first time with a fully loaded 13K core. I build a set of Monos(24), Polys(24) and Megas(24) and set up my defences they play through the waves. Once the sector is captured I take everything down except the Core. The Monos, Polys and Megas remain. I update the tech tree to grab the goodies. I place an unloader on the Core to take out thorium and place a Thorium rector against it to blow up the core.

When I try to return to, restart, the sector launching from Tar Fields irrespective of the core size I use or the amount of resources I assign I am told I have insufficient resources to launch. It consistently moans about lead but depending on core size other resources may be flagged as insufficient.

Steps to reproduce: As described above.

Link(s) to mod(s) used: No mods used

Save file: [insuffresources.zip](https://github.com/Anuken/Mindustry/files/6510926/insuffresources.zip)

(Crash) logs: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment]
please check your lead

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/118866553-1de16e00-b8b0-11eb-9169-5733e11d8060.png)

I don't see the problem. You don't have *any* lead in the closest launch sector (Tar Fields), so it is insufficient.

**Comment by GitBobCat** [comment]
Thanks. I am now officially an idiot but I'll try to remember.
