### ISSUE TITLE
Copy & remove bug

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#5283]
**Platform**: Android

**Build**: 126.2

**Issue**: remove mode corners appear on empty floors

**Steps to reproduce**:
1) copy a building
2) select a building on remove mode
3) rotate/mirror

**Link(s) to mod(s) used**: no

**Save file**: campaign, custom game, multiplayer, same results.

**(Crash) logs**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
