### ISSUE TITLE
Important traduction error

### ISSUE THREAD

**Issue by Fabri2906** [Anuken/Mindustry#5286]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: The problem isn't really a game bug, in the spanish traduction, there's is a trophy that you need to build the three surge-needed turrets but there says "Build the meltdown and the spectre" (Construye el meltdown y el espectro) when you really need to build the Foreshadow too.

**Steps to reproduce**: *is how it is*

**Link(s) to mod(s) used**: `[]`

**Save file**: **

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Phinner** [comment]
1. Traduction issues have nothing to do with bugs, please, keep this holy place clean.

2. If this error is so important, you can pull request a fix yourself. See [TRANSLATING.md](https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md)
