### ISSUE TITLE
Steam Multiplayer not working

### ISSUE THREAD

**Issue by Emeralddragon323** [Anuken/Mindustry#5288]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dioo0** [comment]
_what about save file_

**Comment by IIINSTINCT** [comment]
Incomplete issue just close this or edit this with more information anuke cant just guess how that thing happened

**Comment by oinkymoo** [comment]
a title is not sufficient for posting a bug report. close this
