### ISSUE TITLE
Overdrive Projector/Conveyor/Crucible bug

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#5290]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.2

**Issue**: *Explain your issue in detail.*
I noticed something odd when messing with crucibles and hot tiles. Overdrive projectors overdrive everything except other overdrive projectors, right? This means they also speedup conveyors by their respective amounts too, right?

A single titanium conveyor is enough to empty out a crucible, even when that crucible is heated by tiles. However, when the crucible is placed on hot tiles for some reason it gets clogged with silicon when overdriven, even if the titanium conveyor is also overdriven by the same amount. Theoretically it shouldn't get clogged since both the crucible and the titanium conveyor emptying the silicon out are overdriven by the same amount.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

-Place a crucible on some non-heat tiles and another crucible on some heat tiles. The more heat tiles boost the easier this bug is to reproduce.
-Max out both crucibles with item sources for sand, coal, and pyratite. Keep them full of what they need.
-Place a single titanium conveyor, one for each crucible, to empty out the silicon (preferably into an item void).
-Make sure to empty the heat boosted crucible's silicon manually until it consistently drops to 0. Notice how it never gets full of silicon even though it's boosted by heat and only has 1 titanium conveyor emptying its silicon.
-Place any overdrive projector. It doesn't matter if you use regular, regular phase-boosted, or dome. Power it. Make sure it overdrives both the crucible and the titanium conveyor (that empties the silicon from the crucible).
-The unboosted crucible on the cool tiles acts normally. It produces faster and the titanium conveyor moves faster. Because they're overdriven at the same speed the crucible never gets full of silicon because the single conveyor is enough to empty it out.
-The boosted crucible on the heated tiles gets clogged fairly quickly even though it and the titanium conveyor are boosted by the same amount.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
https://ufile.io/cbxeem6u

I have a setup for you to play with. Power only 1 of the overdrivers at a time. After each test, manually remove silicon from all crucibles until they read 0 silicon. Then pick your favorite overdrive, they all produce the bug, but only 1 at a time. The unheated crucible acts normally boosted or not while the heated crucibles fill up with silicon. They shouldn't fill up.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
NA
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ToasterLLC** [comment]
That is probably because the unboosted conveyors are slower and hence bottleneck.

**Comment by oinkymoo** [comment]
i tested this and even if the full line of conveyors is boosted i still get clogs

**Comment by Erisfiregamer1** [comment]
There is 1 simple reason this is happening.
1. Both the crucible AND conveyors are being boosted, causing the crucible to still make more silicon than 1 tita conveyor can handle.
This is not an issue. I recommend you close it before Anuke does it for you.

**Comment by MrDuck557** [comment]
For some reason, ODed titanium conveyors are not faster than displayed percentage

**Comment by Anuken** [comment]
Overdrive or not, there is a speed limit at which items can be outputted from crafting blocks.

**Comment by RedstonerKBC** [comment]
> There is 1 simple reason this is happening.
> 
> 1. Both the crucible AND conveyors are being boosted, causing the crucible to still make more silicon than 1 tita conveyor can handle.
>    This is not an issue. I recommend you close it before Anuke does it for you.

Yeah that's what I was wondering if my math was correct and it wasn't. I even asked to double-check in the discord before posting this report but got no response.

> Overdrive or not, there is a speed limit at which items can be outputted from crafting blocks: 12 items/sec per side.

That sucks. Wish I would've known that.

**Comment by oinkymoo** [comment]
> Overdrive or not, there is a speed limit at which items can be outputted from crafting blocks: 12 items/sec per side.

i assume this only applies to items being placed onto belts? because when i moved my crucible next to the sandbox core i was testing with, it worked fine without clogging

**Comment by Anuken** [comment]
> next to the sandbox core i was testing with, it worked fine without clogging

The output speed is **per side**, so a directly adjacent crucible would have 3x the max output speed.

I'll consider making the output rate overdriveable in 7.0.

**Comment by oinkymoo** [comment]
it was only bordering on one tile though?
<img width="219" alt="Screen Shot 2021-05-25 at 12 46 11 PM" src="https://user-images.githubusercontent.com/75851043/119534528-05ac9b80-bd55-11eb-9133-802f8057672d.png">

**Comment by oinkymoo** [comment]
this doesn't clog at all (until the core fills, of course)

**Comment by itcannotbe** [comment]
> this doesn't clog at all (until the core fills, of course)

Because the output isn't being placed into a conveyor, the bottleneck happens because there is a definite time to place something on a conveyor.
