### ISSUE TITLE
Issues with borderless window

### ISSUE THREAD

**Issue by MichaelKolaski123** [Anuken/Mindustry#5291]
**Platform**: *Windows*

**Build**: *Steam 126.3*

**Issue**: *When you click on the borderless window in the settings menu while having fullscreen on, it will not switch to borderless window, even if you restart the game. I had to turn off fullscreen and re-enable borderless window for it to work.*

**Steps to reproduce**: *I enabled borderless window.*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *
[Export.zip](https://github.com/Anuken/Mindustry/files/6537865/Export.zip)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. **Sir yes sir** Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Of course. You can't have fullscreen and borderless windowed on at once, that doesn't make any sense.
