### ISSUE TITLE
Drill not sending the other type of ores out if it is mining a different type of ore other than in inventory

### ISSUE THREAD

**Issue by Freakzarer** [Anuken/Mindustry#5295]
**Platform**: Windows

**Build**: 126.2

**Issue**:  Picking drills with ores and placing it on other than the one being mined will result in it not sending the ores other than the one being mined out

**Steps to reproduce**:  
1. Place a drill on an ore
2. wait until maxed with the ore
3. pick the drill
4. place it on other ore type, no items from the other type of ores other than the one being mined shall go out
5. replacing it on the same type of ore it has fixes it, reproduceable on single player and multiplayer

If the drill has a slot left, it will mine like it normally would, but still won't send the other types of ore

https://user-images.githubusercontent.com/59116912/119613957-ea5e9080-be27-11eb-8008-46e53e225f7f.mp4

**Link(s) to mod(s) used**:
dev mode : https://github.com/DeltaNedas/dev-mode
pictologic : https://github.com/DeltaNedas/pictologic
timecontrol : https://github.com/sk7725/TimeControl
ui lib : https://github.com/DeltaNedas/ui-lib

**Save file**:  
[Test_Map.zip](https://github.com/Anuken/Mindustry/files/6544305/Test_Map.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in 7.0.
