### ISSUE TITLE
[RTS] [4.0] Fog of War

### ISSUE THREAD

**Issue by BeefEX** [Anuken/Mindustry#53]
Cradit: alessboy on Discord

You don't see the whole map, any building you place creates an area of vision around it.

Toy can only build in areas of vision.

**Comment by Alessboy** [comment]
This is supposed to be for the rts version, but would help slow the main version, the rts versions sends should not give vision, as you could send early and use cheese tactics early on, the placement should come later as you expand it is easy to deal with, the use of fog of war would allow the whole map to be open to both players, which would reduce camping.

**Comment by Anuken** [comment]
Moved to #87.
