### ISSUE TITLE
Player-side server crash when enemies spawn?

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#531]
I was playing in mindustry.indielm.com:9001 and i kept on getting disconnected with a crash message whenever enemies spawn. 
![Screenshot 2019-06-22 at 07 09 56](https://user-images.githubusercontent.com/50847107/59946126-c1a42280-94bd-11e9-8797-5a39fcf11145.png)
![Screenshot 2019-06-22 at 07 09 44](https://user-images.githubusercontent.com/50847107/59946128-c1a42280-94bd-11e9-976e-894d5f00267d.png)
i don't know wether this is a server side issue or a bug
**If this issue is completely irrelevant, feel free to delete it without commenting.**

**Comment by Prosta4okua** [comment]
Download from itch.io v4b80.2

**Comment by Arkanic** [comment]
> Download from itch.io v4b80.2

using android
(Touchscreen Chromebook)

**Comment by Anuken** [comment]
This was already fixed with 80.2. Google Play already has the update, although they seem to be taking a while to distribute it.

**Comment by Arkanic** [comment]
> This was already fixed with 80.2. Google Play already has the update, although they seem to be taking a while to distribute it.
@Anuken 
thanks dude
