### ISSUE TITLE
Mindustry logic: `ulocate building core …`: does nor work if bound unit is @alpha / @beta / @gamma

### ISSUE THREAD

**Issue by schittli** [Anuken/Mindustry#5310]
**Platform**: `Windows 10 x32`
**Build**: `release build 126.2`

**Issue**:
This logic perfectly works :
```
ubind @mono
ulocate building core false @copper foundCoreX foundCoreY __tmp75 oFoundCore
```
But if we bind the player unit, the core is not found 😞:
```
ubind @alpha (or: @beta, @gamma)
ulocate building core false @copper foundCoreX foundCoreY __tmp75 oFoundCore
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by schittli** [comment]
It would be great if the core will be found with any unit.

Or even better: if it's not necessary to bind a unit to find the core 😀

**Comment by MrDuck557** [comment]
Any unit statement calls a function on the unit
If it is already controlled, those functions are disabled, including ulocate

**Comment by Anuken** [comment]
You can't use player units with logic.
