### ISSUE TITLE
Contrast Sensitivity and in-game menus

### ISSUE THREAD

**Issue by mryellow** [Anuken/Mindustry#5317]
**Platform**: All

**Build**: All

**Issue**: Text is painful to view and may result in migraine.

**Steps to reproduce**: Play the game with some form of contrast sensitivity.

**Link(s) to mod(s) used**: N/A

**Save file**: N/A

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [-] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- I'm not downloading again, I've had a poor experience with your suggestions "issue tracker" and don't feel like investing any more time than I already have.
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://github.com/Anuken/Mindustry-Suggestions/issues/1705

**Comment by Anuken** [comment]
As you are well aware, this is a suggestion, not a bug report.

> They remain valid until at the least properly reviewed.

[Read the suggestions README.](https://github.com/Anuken/Mindustry-Suggestions#how-do-i-know-if-youve-read-my-suggestion)

I have no plans to change the contrast in Mindustry's UI.

**Comment by mryellow** [comment]
> I have no plans to change the contrast in Mindustry's UI.

I have plans to refund.

**Comment by Anuken** [comment]
> I have plans to refund.

Sure, go ahead. I'm not going to spend hours/days of my time implementing & maintaining a feature requested by a single person just because of a threatened refund. 

I'm *definitely* not going to do it for someone with such a self-important attitude, especially when they call those they disagree with ["random idiots"](https://github.com/Anuken/Mindustry-Suggestions/issues/1705#issuecomment-753581572).

For someone who ["doesn't care"](https://github.com/Anuken/Mindustry-Suggestions/issues/1705#issuecomment-753580566), you sure seem to be making fuss about this.

**Comment by itcannotbe** [comment]
> > I have no plans to change the contrast in Mindustry's UI.
> 
> I have plans to refund.

Good
Luck
With
That.

Initiating a refund request has certain pre requisites, and if you went over their threshold, you'll be a sad boi.

**Comment by mryellow** [comment]
> a single person

I'm the 1 in 1000 who complains. You can be assured I'm not the only person who finds your title inaccessible. 

There is a reason why dark themes feature greys and why games no longer look like they did in the 80s.

p.s. Games in the 80s were more accessible.

> especially when they call those they disagree with "random idiots".

You seem to have some forum warriors on your suggestions issue tracker. It made engaging there very unpleasant. Instant dismissal of serious accessibility issues.

> For someone who "doesn't care", you sure seem to be making fuss about this.

Your inability to take an accessibly issue seriously shows you are not willing to fix this serious fault in your product.

**Comment by mryellow** [comment]
> Initiating a refund request has certain pre requisites

Defects included.

Inaccessibility of a title is a defect.

> you bough the game without any promises about accessibility support

Offering a product such as this for sale accessibility is implicit. The author is liable.

**Comment by mryellow** [comment]
> threatened refund.

Just to be clear that wasn't a threat and I didn't imagine you reversing your position.

It was a response to that position and your dismissive attitude to what are issues which should never be so easily dismissed without any thought or investigation.

**Comment by mryellow** [comment]
To be succinct.

There is no threat here and I didn't imagine you reversing your position upon hearing.

You dismissed without thought an accessibility issue. 

Defects are refundable. Your product is not fit for purpose. Consumer law applies.

From beginning to end, from dealing with your forum warriors to dealing with yourself. This purchase have been unpleasant.

**Comment by Anuken** [comment]
> You can be assured I'm not the only person who finds your title inaccessible.

Undoubtedly, but I would rather spend my time working on features that the majority of the community is interested in. Or, at least, are being asked for *politely.*

> Your inability to take an accessibly issue seriously shows you are not willing to fix this serious fault in your product.

Yeah, I'm not. You can call it a "serious fault" if you want, but the fact is that the vast majority of people don't care.

Mindustry doesn't *hide* any of its UI, and Steam refunds are a quick and easy process. There's even a screenshot of the editor, with its white-on-black style on full display. Surely you would have noticed this "serious fault" within minutes of launching the game, and issued a refund if it was a significant problem?

> Offering a product such as this for sale accessibility is implicit. 

Oh, is it really? From what I've seen, the only thing that is "implicit" in a Steam release is that it doesn't come with a virus. Probably. But considering the fact that several released (and paid) games on there have been found to contain bitcoin miners, I'm not sure if even *that* applies.

**Comment by mryellow** [comment]
>  I would rather spend my time working

What legal jurisdiction you operating under? I'm sure many would like to ignore accessibility defects.

> vast majority of people don't care.

Vast majority of people aren't wheelchair bound either, but you'll notice ramps in most places you go. 

Be dismissive all you like.

>Steam refunds are a quick and easy process.

I really wasn't interested in a refund until you replied in a dismissive manner and not only failed to that the issue seriously but  rubbished the very concept that it might be a thing.

> Surely you would have noticed this "serious fault" within minutes of launching the game

I did. I spent the following 5 hours in bed trying to recover.

> requested a refund if it was a significant problem?

I contacted your issue tracker, which turned out to be a hive of forum warriors with no response from yourself.

When that issue was closed, I escalated to here and discovered you are likely the reason for such a culture existing. 

> Steam release

This is not where your obligations end.

**Comment by itcannotbe** [comment]
@mryellow before you say another word, kindly cite your legal basis on the developer's obligation based on actual laws or it's implementing rules and regulations that would compel anyone making a game to add in comprehensively accessibility features.

**Comment by mryellow** [comment]
> kindly cite

How would I know without knowing the jurisdiction? 

You are not contributing.

**Comment by itcannotbe** [comment]
Try USA

**Comment by mryellow** [comment]
On USA this article was interesting.

Seems there would be room for a new case under Americans with Disability Act. Something like this situation is a little different to the Sony case which was an onerous imposition. Here we're talking simply about colour scheme and no major functionality.

https://dsq-sds.org/article/view/4513/3833

>  In a civilized nation that values the equal access and participation of its citizens, the answer is an unequivocal yes.

**Comment by itcannotbe** [comment]
> @mryellow before you say another word, kindly cite your legal basis on the developer's obligation based on actual laws or it's implementing rules and regulations that would compel anyone making a game to add in comprehensive accessibility features.
> 
> If can't find any, you just lost your right to complain further.

Your point being? You can't find any? I guess so.

**Comment by Anuken** [comment]
> I did. I spent the following 5 hours in bed trying to recover.

> I really wasn't interested in a refund

So, why are you still here, months after the initial incident? How were you content with **not** refunding a product with such a "serious fault"? Either the game was broken & inaccessible, or it wasn't. **Pick one.**

> How would I know without knowing the jurisdiction?

USA. Some quick searching leads me to articles that the most consumer laws give you is the right to "*[...] a full refund for up to 30 days after the purchase*", which you don't seem to have taken advantage of. Why?

> https://dsq-sds.org/article/view/4513/3833

This doesn't seem to mention that accessibility is mandated by law. At most, it mentions that:

> A lone exception in the United States is the application of the CVAA to the "the communications functions offered via gaming" [...]

...which is not relevant to high-contrast UI.

> Vast majority of people aren't wheelchair bound either, but you'll notice ramps in most places you go.

I am a solo indie developer, not building designer or construction worker. There is no obligation for me to implement these features.

> This is not where your obligations end.

It is.

**Comment by Anuken** [comment]
> Be dismissive all you like.

I'm not dismissing this as a problem. It *is* a problem, albeit one that affects a small group of people. Realize that:

- I have limited time to work on the game, and your problem is just one of many.
- Listening to a loud minority leads to issues further down the line.
- Nothing about your tone or behavior makes me willing to implement features you propose.

Consider doing any of the following in the future:

- *Not* taking a haughty attitude when faced with criticism, and avoiding calling people "idiots"
- At least re-posting the suggestion instead of putting it in the (obviously) wrong issue tracker.
- Providing more details on what you actually need. Okay, "*hard white text on hard black backgrounds*" are bad, what do you want me to do about it? The template is there for a reason, you should have **told me exactly what you wanted changed**.
- Changing the colors to something better yourself, or at least making an attempt to do so. The game is open-source, after all - you can build, edit the assets/source code and run it free of charge.
- Not actively antagonizing me & other people present here. How do you expect me to do *anything* for someone who's handing out insults, saying "I don't care" and waving around refunds in the air?

**Comment by mryellow** [comment]
> How were you content with not refunding a product with such a "serious fault"?

I figured it's developers would understand the issue.

I was willing to give you the benefit of the doubt, until you responded.

Your response, after already dealing with similar from your forum warriors was an indication that I was wrong to not refund immediately.

> I am a solo indie developer,

I hope you're able to progress and better yourself as a developer.

**Comment by itcannotbe** [comment]
> > @mryellow before you say another word, kindly cite your legal basis on the developer's obligation based on actual laws or it's implementing rules and regulations that would compel anyone making a game to add in comprehensive accessibility features.
> > If can't find any, you just lost your right to complain further.
> 
> Your point being? You can't find any? I guess so.

@mryellow you lost your right to complain further, remember?

**Comment by mryellow** [comment]
You're a fantastic representative. Once again making it clear that I should have refunded without bothering to make contact with either your suggestions "forum" or this issue tracker. Have a nice day.

**Comment by mryellow** [comment]
Just a quick note. Turns out Australian Consumer Law does apply.

**Comment by Anuken** [comment]
> I figured it's developers would understand the issue.

That's a strange thing to expect when you've broken several rules (*no template, wrong tracker*), insulted the competence of the developer ("*simply* take more care, time and effort with design choices") and generally acted very unpleasant towards the community. 

You seem unable to grasp the fact that **being rude and entitled will not make people do things for you**.

> I hope you're able to progress and better yourself as a developer.

Yes, someday I hope I'll be able to immediately lock demands made by self-centered users before they turn into massive arguments.
