### ISSUE TITLE
how to download

### ISSUE THREAD

**Issue by fionn132** [Anuken/Mindustry#532]

**Comment by fionn132** [comment]
i just.....how do i getty the spaghetti

**Comment by Milinai** [comment]
You have the [releases page](https://github.com/Anuken/Mindustry/releases) and [Itch](https://anuke.itch.io/mindustry/purchase) to download the game from at any time.

**Comment by Anuken** [comment]
If you can make an issue, you should also be able to figure out how to scroll down to the text labeled "Downloads" in the readme.
