### ISSUE TITLE
Disappearing Servers

### ISSUE THREAD

**Issue by PickAPlayerNameFirst** [Anuken/Mindustry#5326]
**Platform**: *Android/iOS/Mac/Windows/Linux* 

- Windows 

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
- 126.1 to 126.2

**Issue**: *Explain your issue in detail.*

The servers are deleted on my PC. 

They just vanished to thin air. 
It happened once I installed 126.1. At first it was completely okay, the servers are showing up in the multiplayer tab, but now everything's gone. 

I was worried I got banned from those servers because when I looked at my phone, I see all of them showing good ping. So I just ignored it because I got punished by the law (I do not grief). 

It took long before I got bored playing .io server multiple times. Then I saw one member of the ALEX server (one server that just vanished in my pc) in discord. We had a DM and explained why was ALEX missing in my multiplayer tab, and redirected me to the admin. 

He said I wasn't banned, even if I was, then I should still see it, but can't join on it because of the long timer yhey give to banned ppl. 

Many servers were gone on my PC, but in my phone all of the servers are showing up and with good ping (100-300 ms) 

I've also seen ppl complaining some of their servers are missing, please help us. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

I don't know, it just happened unconsciously. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods are used. 

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

I could send screenshots in the comments tab to prove the bug. 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
All the servers display fine on my end. Sounds like you may have accidentally hidden the servers by clicking the hide button - click the "display hidden servers" eye to show them again, if that's the case.

If they're still missing, then then it's likely a network problem and I can't help you.

**Comment by PickAPlayerNameFirst** [comment]
> All the servers display fine on my end. Sounds like you may have accidentally hidden the servers by clicking the hide button - click the "display hidden servers" eye to show them again, if that's the case.
> 
> If they're still missing, then it's likely a network problem and I can't help you.

They're not hidden, my network is super fine because my phone actually shows it with 100 ms ping, I play with the same location where I use my phone so idk what actually the problem is

**Comment by WilloIzCitron** [comment]
but the server down its disappear
