### ISSUE TITLE
Changing sectors in a co-op campain while sending a message fails to let the new sector load

### ISSUE THREAD

**Issue by fadedmax** [Anuken/Mindustry#5330]
**Platform**: Mac

**Build**: 126.2

**Issue**: I play a co-op campain with my friend, who will be referred to as friend. When my friend changes sectors while i am typing a message, whenever i press "enter" to send it, it fails to send world data and throws me to main menu. Fair enough why it's happening, i am simply requesting that it be fixed(send the message once the new sector is loaded) or there is a better error message(Sorry, we can't sent messages while switching sectors)

**Steps to reproduce**: Join a co-op campaign, have the host change sectors, have the other person type a message, when you press enter it fails

**Link(s) to mod(s) used**: None.

**Save file**: https://www.mediafire.com/file/ogwm2mejcid523f/mindustryExport1.zip/file
*I think this is it, if it's something else pLEASE let me know*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Does not crash, simply goes to main menu.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ (i have not done) ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X {i searched, not gonna go through all 2000} ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce - typing/pressing enter a message while the world is switching does not lead to a disconnection on my end, attempted several times.
