### ISSUE TITLE
Bug with calling

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry#5331]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android 

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.2

**Issue**: *Explain your issue in detail.*
When you are playing and on a phone call, when you or your friend hangs up, the audio completely cuts

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Open game, call a friend, hang up while game is open, glitch happens

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
DeltaNedas/BoostControl
VladTheEvilCat/ExtendedZoom
DeltaNedas/PicToLogic
DeltaNedas/UILib
DeltaNedas/WAISA

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
No crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
You forgot the save, and removed the line saying it's required.
It's a requirement, so please add it.

**Comment by Anuken** [comment]
Duplicate.
