### ISSUE TITLE
Everything black in compangin

### ISSUE THREAD

**Issue by koVKi-Kostravi** [Anuken/Mindustry#5332]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*
The planet and space is black in compangin
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Close mindustry with home button an then open it again
**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
  [пофиг.zip](https://github.com/Anuken/Mindustry/files/6591515/default.zip)
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
Did- Did you not put a save file AND delete the warning that to adding it will cause Anuke to reap your soul?!?
PLEASE add a save! It's a requirement!

**Comment by koVKi-Kostravi** [comment]
Sorry

**Comment by Anuken** [comment]
Cannot reproduce.

**Comment by SMOLKEYS** [comment]
> compangin

what
