### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KotMilkMeoW** [Anuken/Mindustry#5334]
**Platform**: `Android   

> 10`

**Build**: `dev build 126.2`

**Issue**: *Broken oct textures.*

**Steps to reproduce**: *1. using the payload-source, I create a lot of octs. 2. Using the processor, I send them to x0 y0. 3. When they reach and start pushing, this happens*

**Link(s) to mod(s) used**: `none`

**Save:** failed to add  (I have paws) (у меня лапки)

**Crash report**: *none.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [✓ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ✓] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_20210603-113053](https://user-images.githubusercontent.com/81019712/120615342-d8e93a00-c460-11eb-9b22-54b29c901217.jpg)
![Screenshot_20210603-113103](https://user-images.githubusercontent.com/81019712/120615371-e43c6580-c460-11eb-8bf4-a7a1982a54fe.jpg)
`![Screenshot_20210603-113053](https://user-images.githubusercontent.com/81019712/120615412-ec94a080-c460-11eb-908c-7fa7c9605a58.jpg)

`

P.s. if the translation is crooked, then Yandex. Translate is to blame

**Comment by BlueWolf3682** [comment]
Yes, we all know the oct/eclipse/omura textures are broken. Anuke is trying to find a fix.

**Comment by KotMilkMeoW** [comment]
Okay

**Comment by Anuken** [comment]
> Yes, we all know the oct/eclipse/omura textures are broken. Anuke is trying to find a fix.

What?

![image](https://user-images.githubusercontent.com/10100000/120649929-4a1df280-c44b-11eb-815d-5894b519a1b5.png)

Same results on a phone.

> Save: failed to add

Which part of "IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE" *did you not understand?*

**Comment by BlueWolf3682** [comment]
> > Yes, we all know the oct/eclipse/omura textures are broken. Anuke is trying to find a fix.
> 
> What?

![Screenshot_20210602-181908](https://user-images.githubusercontent.com/61173114/120677130-011e6c00-c454-11eb-9819-d2ac4daa9a42.png)
BE 21112

> ![image](https://user-images.githubusercontent.com/10100000/120649929-4a1df280-c44b-11eb-815d-5894b519a1b5.png)
> 
> Same results on a phone.
> 
> > Save: failed to add
> 
> Which part of "IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE" _did you not understand?_

This was not save specific, please don't berate people on that.

**Comment by Anuken** [comment]
> This was not save specific, please don't berate people on that.

**It doesn't matter.** I *need* to know whether the problem is save-specific or client specific, and loading a save on my client is the best way to do that. 

It doesn't help that the steps to reproduce on this issue were *extremely* misleading, and pointed towards save-specific behavior:

> When they reach and start pushing, this happens

If a save was provided, *I would have known that this is not the cause of the bug.* There is no good excuse to exclude a save from your bug report.
