### ISSUE TITLE
Bug related to air unit's death effect

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#5335]
**Platform**: Windows

**Build**: This bug has been there since first v6 release, and is there in the latest, 126.2. It is also there in the new dev versions.

**Issue**: When an air unit is destroyed over high terrain (the black part of it), as soon as it starts falling it becomes invisible, then after the falling animation ends, the explosion occurs normaly.

**Steps to reproduce**: 
1) Make the air unit hover over the black part of the high terrain.
2) Kill it in any way
3) See the bug.

**Link(s) to mod(s) used**: No mods.

**Save file**: 
[Bugged file.zip](https://github.com/Anuken/Mindustry/files/6590499/Bugged.file.zip)
_When I played this particular map, sound was all distorted and messed up. This didnt happen anytime before, and might continue. Version used dev21112 bleeding edge build. Just randomly found out this bug._

**(Crash) logs**: None
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a not a bug + duplicate.

**Comment by BorisA11** [comment]
So... it purposely does that? Why?

**Comment by Anuken** [comment]
there's a very long discussion on that topic, look it up.

**Comment by BorisA11** [comment]
I agree, it should probably fade out instead of instantly disappear.
