### ISSUE TITLE
Sprites are a jumbled mess

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#5343]
**Platform**: Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Bleeding Edge 21130

**Issue**: *Explain your issue in detail.*
Sprites are all jumbled, as shown in the attached picture, I'm aware that the sprites are supposed to be purple, but not like this to my knowledge.
![image](https://user-images.githubusercontent.com/75080541/120695484-d5b27600-c481-11eb-9f42-2869908510bb.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Open the game
Observe

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

[SaveFile.zip](https://github.com/Anuken/Mindustry/files/6593637/SaveFile.zip)
(I don't think this is nessesary, but better be safe than sorry)
**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
x

**Comment by Anuken** [comment]
A fresh copy of 21130 looks fine to me, as does 21132.

> I'm aware that the sprites are supposed to be purple

Not anymore.
