### ISSUE TITLE
Payload Propulsion Tower instant transport + no animation line thing

### ISSUE THREAD

**Issue by ArifDaniel** [Anuken/Mindustry#5356]
**Platform**: *Android*

**Build**: *Bleeding-edge builds 21152*

**Issue**: *i just saw Payload Propulsion Tower(PPT)just instantly teleport payload onto another PPT and this happen in multiplayer also PPT just launch payload fast without delay animation (the line thing)*

**Steps to reproduce**: *idk, this happen in nydus server*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *None for some reason*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Save file: None for some reason
