### ISSUE TITLE
More payload propulsion tower bugs

### ISSUE THREAD

**Issue by ArifDaniel** [Anuken/Mindustry#5358]
**Platform**: *Android*

**Build**: *bleeding-edge build 21152*

**Issue**: *payload in payload propulsion tower just disappear and it also duplicate.*

**Steps to reproduce**: *place two payload propulsion tower(make sure they close to each other with no gap) and make sure the output in facing at each other then put in one payload. Chance of bug occuring are little low, you can increase this by overdriving them. Screenshot will show it
![Screenshot_2021-06-04-22-53-16](https://user-images.githubusercontent.com/64296945/120825342-e222f580-c58b-11eb-9d96-85c0caab3f4d.png)

*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *
[save_where_bug_occur.zip](https://github.com/Anuken/Mindustry/files/6599552/save_where_bug_occur.zip)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Loaded the save, waited for a few minutes, no duplication or deletion occurred.

**Comment by ArifDaniel** [comment]
> Loaded the save, waited for a few minutes, no duplication or deletion occurred.

This only work in multiplayer
I recommend nydus server (and make sure it's in sandbox map)
can you disguise?

**Comment by Anuken** [comment]
Then it's desync, and will fix itself anyway.
