### ISSUE TITLE
Bug with blueprints and maps

### ISSUE THREAD

**Issue by koVKi-Kostravi** [Anuken/Mindustry#5359]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

Blueprints and maps appear on save without these blueprints and maps

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Go from one save to another

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[bug.zip](https://github.com/Anuken/Mindustry/files/6600705/bug.zip)
[bad.zip](https://github.com/Anuken/Mindustry/files/6600712/bad.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> without these blueprints and maps

This statement doesn't make any sense. Schematics have nothing to do with maps. Maps are independent of saves.

**Comment by koVKi-Kostravi** [comment]
But if I go from one save to another I have a lot of similar blueprints

**Comment by Anuken** [comment]
Schematics are *global*, they have nothing to do with individual saves. 

> similar blueprints

They are the *same*.

**Comment by koVKi-Kostravi** [comment]
if they are global why they disappear when i clear game data? and they different in these saves
[пофиг.zip](https://github.com/Anuken/Mindustry/files/6600846/default.zip)
[bad.zip](https://github.com/Anuken/Mindustry/files/6600847/bad.zip)

or I am idiot

**Comment by Anuken** [comment]
> if they are global why they disappear when i clear game data?

Clearing game data deletes **everything** the game ever saved, including schematics and settings. What do you expect it to do?

> and they different in these saves

No.

**Comment by koVKi-Kostravi** [comment]
but they different...

in "bad" save there 7 shematics
in another save more than 7
