### ISSUE TITLE
Duct Bridge Bug

### ISSUE THREAD

**Issue by pnpm52b** [Anuken/Mindustry#5373]
**Platform**: *Windows*

**Build**: *BE 21177.*

**Issue**: *Duct Bridge output beside factories would not accept items from the right side. Found this bug on build 21164. Even after flipping and copy pasting, it appears only on the same sets.*
![image](https://user-images.githubusercontent.com/80879579/120915048-bae83780-c6f5-11eb-8c34-dcdc8c8370e2.png)

**Steps to reproduce**: *place blocks like above.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[duct bridge bug build 21177.zip](https://github.com/Anuken/Mindustry/files/6603744/duct.bridge.bug.build.21177.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
schematic version:

`bXNjaAF4nEWQ0W6DMAxFnQQQCtAg9h38wf5k2gOFaEKipQvQaZ8+aVJmc1v2gK5DzDk29ELOUHLtLp7qfpvW8d6tc2iHrV8XKga/9GG8reN8JaJs6s5+Wki/vadU3uYvH9pl3kLvqZrGz20cnkf7j6K6C5c5+KHt5+vdf/ObQujtOYzDh2fsKz+kc0UZkVFcmzR5VIVUUlAp9zEqzUdNRqIgZchIv4Qik3BoRIbISUmU6KwQJyGmbNTxV7baXelhTQ8rLyk9MT7MGcwZzDnMuZgldnPO/D0yxD5A/vygRFSIk4QFxYJiQbGgWFAsKBYUC4oFxQpF880+WSEtxDfyN82+TXXsVR17VbIXmRjjD+9lyGEGh3/oMIOD3EHuYHWwOlhrWGtYG7aKpzmMzWFs2EjqDwUXP4Q=`

**Comment by oinkymoo** [comment]
if duct bridges work the same as normal bridges, the output bridge shouldn't accept items at all

**Comment by pnpm52b** [comment]
bug seem to only happen on 2x2 factories, and all of the 2x2 factories have the bug, including separator, 1x1 and 3x3 seems fine
