### ISSUE TITLE
all captured sector have a warn 

### ISSUE THREAD

**Issue by Ludo-code** [Anuken/Mindustry#5377]
**Platform**: *Windows*

**Build**: *126.3*

**Issue**: *when i go to the tech tree all is empty, so as if I had just started the game for the first time, and the campaign have all sector with a warning, i have an error in debug.log :  [1231/235630.940:ERROR:settings.cc(325)] Settings version is not 1*

**Steps to reproduce**: *Just started the game*

**Link(s) to mod(s) used**: *0 mods are used*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.* [https://fromsmash.com/SavesMindustry](https://fromsmash.com/SavesMindustry)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment]
Most likely the settings.bin file got deleted or corrupted
Known bug

**Comment by Ludo-code** [comment]
and i can make nothing to repair it ?
