### ISSUE TITLE
Google Play version on Chromebook

### ISSUE THREAD

**Issue by SmolGreenBuggo** [Anuken/Mindustry#538]
I've got the Google Play version on a Dell Chromebook. It feels like I'm playing a game that is not supposed to be played on the computer, the controls are rather hard to use for me. I enjoyed the web version far better, is there any way to fix that?

Maybe it's just because I'm using build 40, maybe not. But bleh, it's an issue.

**Comment by Anuken** [comment]
That's because it's *not* designed to be played on a Chromebook. This is already [on the Trello.](https://trello.com/c/zPLAlunH/451-android-chromeos-mousekeyboard-support)

**Comment by Arkanic** [comment]
@SmolGreenBuggo I use a touchscreen chromebook to, but I have to agree with Anuken; The current version is not designed for chromebook use.
(I just use mine in flipped tablet mode)

**Comment by Luxray5474** [comment]
Sorry for necropost; but the *Play Store* is meant for *Android* versions of games. Even if you're on a Chromebook, It will still install the Android version of the game which has mobile controls. IF you still wish to play this on your Chromebook, you can try out Crostini or Crouton and install Java on it to run the game.
