### ISSUE TITLE
Some feature ideas

### ISSUE THREAD

**Issue by xslendix** [Anuken/Mindustry#539]
Here are some stuff that i wanna see in mindustry (please read it took me a lomg time to make):
* Material counter
  * When clicked, a GUI will appear where it allows you to set how many materials you want, what type of material you want, the operation (<, >, =<, =>, ==). 
  * If the condition is met, the materials are sent forward and the rest are either checked again or sent on the side (option in the GUI). 
  * The delay between checks is a minimum of 1 material(s) per second and the maximum of like idk 10 maybe? 
  * Creates power when condition is met (needs to be powered, can act like a power node i guess)
  * This sounds like a bad idea but at least try it. Would make us able to create advanced stuff
* LEDs. Yes.
  * The color can be chosen from a GUI
  * Will lit up if has power
  * Brightness is determined by the amount of power it receives
* Material blocker
  * It can be powered (toggle or minecraft door mode, this can be changed from a GUI) or toggled by a player.
* Electricity power level changer (change the name is more or less like a resistor)
  * When fed power, the nearest node will get that power that has been received reduced my an amount set in a GUI
* Inverters
  * Kinda like redstone torches in mintcraft is fed power, it outputs no power, it gets no power, emits a small amount of power.
* Power amplifier
  * Has GUI to have a slider to change hoe much to amplify the power
  * Has 1 input: power
  * Has 1 output: power (but wait that isnt possible to code, right? WRONG! The power amplifier can be 2x2 tile big, each tile having separate connections)
* There are too many GUIs i know
* I should probably sleep now
* Help

Here are some minor changes I would make to the game:
* The energy light beams must be at least a little bit transparent (Because LEDs)
* Be able to get an exact amount of items out of player's inventory.

**Comment by BasedUser** [comment]
Suggestions are closed until 4.0 release.

**Comment by xslendix** [comment]
I legit spent 30 minutes writing that

**Comment by kcomain** [comment]
wait for that :)

**Comment by Arkanic** [comment]
@xslendix sounds good! but I think that mindustry power networks are not required to be so complex. While things like inverters could be useful, resistors would not have much purpose seeing as units   only take the power that they need. however, all of your ideas seem to be really usable if implemented.
~~nice work, mate~~

**Comment by XieYongcheng** [comment]
Here are some stuff more
* Signal (requires energy (electricity) support)
  * Detection circuit: Detect the remaining capacity of the container (can set the value, such as 80%)
  * Control circuit: start (stop) device (such as conveyor belt)
  * Logic gates: AND, OR, NOT, XOR

The input and output of the signal cannot be distinguished, so it may be necessary to distinguish the direction.

**Comment by kcomain** [comment]
Now we need to get the attention of Anuke

**Comment by Arkanic** [comment]
@kcomain you do realise that everybody here is working on other things at the moment, like translations, description extensions, and bugfixes. there are lots of contributors as well.

**Comment by Arkanic** [comment]
@xslendix can you please put your ideas in the new <ideas here> issue? i'm just trying to clean things up because there are suddenly about 5 issues on new ideas. thanks!

**Comment by Anuken** [comment]
> Now we need to get the attention of Anuke

That's not very hard, considering I get emails *and* notifications for every issue and comment posted here.

--- 

I don't think there's much I can say that hasn't already been said; there's already a large backlog of suggestions and issues, so I'm not going to be implementing new player content suggestions anytime soon. It's worth noting that logic systems are [already on the Trello](https://trello.com/c/jonIx24W/90-logic-systems), and they will probably work differently than you expect.

For now, you should move to Arkanic's [issue](https://github.com/Anuken/Mindustry/issues/545).
