### ISSUE TITLE
i can't write in logic processor 

### ISSUE THREAD

**Issue by abdallah362** [Anuken/Mindustry#5393]
**Platform**: *Android/Huawei only*

**Build**: *21112*

**Issue**: * I can't write anything in a processor because the screen when I write anything it will resize the screen because of these buttons in Huawei
![IMG_20210607_132445](https://user-images.githubusercontent.com/81780902/121001881-68118d00-c794-11eb-9fa6-251ceacd4776.jpg)*

**Steps to reproduce**: *have phone or tablet and should have these buttons or anything that disappear and resize the screen when disappearing
 open any processor try to write anything it will resize the screen when you complete the writing it will forget what you write when the screen resize I was having this also in 126.2 and 126.1 but it had a low chance of it, but in the mindustry BE the chance of that happen is 100% so now I can't code in mindustry BE using Huawei
these some photos of it 
![Screenshot_2021-06-07-13-42-46](https://user-images.githubusercontent.com/81780902/121004599-8cbb3400-c797-11eb-80b5-6473acbf1a80.jpeg)
![Screenshot_2021-06-07-13-42-51](https://user-images.githubusercontent.com/81780902/121004627-95ac0580-c797-11eb-9cf9-5aa8c3b95111.jpeg)
look its disappear and the screen resize and it forgets what I write the "block1" should be "test"
*

**Link(s) to mod(s) used**: *noun*

**Save file**: *any processor*
**(Crash) logs**: *noun the game don't crash it just don't write*
---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by IIINSTINCT** [comment]
Update to the lastest BE this is already fixed close this

**Comment by abdallah362** [comment]
> Update to the lastest BE this is already fixed close this

what really?

**Comment by abdallah362** [comment]
let me test the latest BE

**Comment by IIINSTINCT** [comment]
https://github.com/Anuken/Mindustry/issues/5362
Someone already reported this and it was fixed

**Comment by abdallah362** [comment]
ok it fixed for me

**Comment by abdallah362** [comment]
I didn't close it until i test it because i was thinking it will not work for me
