### ISSUE TITLE
Processors don't update a linked building when replaced with a similar type

### ISSUE THREAD

**Issue by xC-5x** [Anuken/Mindustry#5406]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Release build 126.2

**Issue**: *Explain your issue in detail.*
(Not sure if this is reported before new to github) Replacing a building with a similar type (placing a ground factory on an air factory or an overdrive projector on a merger) does not update any logic processor that has a link to that building, keeping the data of the previous building. Unlinking and relinking the building fixes this.
Demonstration video:
https://user-images.githubusercontent.com/85666120/121474927-c4420000-c992-11eb-9376-234ff53389bd.mp4

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Came across the issue while making logic-based unit factories
Reproduce steps:
The video has the steps but here's a written guide:
Link any processor to any block that can be replaced by a different type of block(ie. a copper wall can be replaced with a titanium wall, etc.)
Use any sensor block that detects details about the linked block, the example video detects the configuration of a T1 factory, printing this to a message block helps.
Code used in example video, with 1 message block and unit factory:
```
sensor result factory1 @config
print result
printflush message1
```

Replace the block with a different type of block, demonstration video replaces ground factory with air factory.
Check the output of the code, in this case, the message block, it will print the data of the previous block.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods were used.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
Zipped world File:
[TestWorldBugReport.zip](https://github.com/Anuken/Mindustry/files/6628852/TestWorldBugReport.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
DNE
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
An interesting thing to note here is that this fixes the piston bug with the processors
@ThePythonGuy3

**Comment by ThePythonGuy3** [comment]
huh why me @sk7725
