### ISSUE TITLE
versionCode in version_fdroid.txt broken

### ISSUE THREAD

**Issue by jspricke** [Anuken/Mindustry#5408]
Hi,

you are providing https://raw.githubusercontent.com/Anuken/MindustryBuilds/master/version_fdroid.txt for F-Droid to check for updates, thanks for that! Sadly currently it contains:
```
versionName=6-fdroid-126.2
versionCode=126.2
```
versionCode can't contain a dot, can you please fix this?

**Comment by Anuken** [comment]
Fixed; CI will now use the Actions run number for version codes instead of the displayed build number.
