### ISSUE TITLE
Failed to load main.js in any scripted mods

### ISSUE THREAD

**Issue by iarkn** [Anuken/Mindustry#5412]
**Platform**: Android 10

**Build**: Bleeding Edge 21230

**Issue**: Mindustry fails to load the main.js file in scripted mods that are enabled (shown at the log below). To make sure that this doesn't have anything to do with my code, I created a dummy mod that just prints "a" when it is loaded.

Other "supposed-to-be-bleeding-edge-compatible" mods that have scripts don't work as well, e.g., `MEEPofFaith/testing-utilities`. I assume this issue only happens on Android.

**Steps to reproduce**:
1. Install a scripted mod (that is supposed to be compatible with the BE version).
2. Load the mod.
3. Open `last-log.txt` and see the loader error.

**Link(s) to mod(s) used**:
- https://github.com/receptea/mind-util/tree/dev-7.0
- [a.zip](https://cdn.discordapp.com/attachments/851065277348446208/852792173169737738/a.zip)

**Save file**: This does not happen in-game.

**(Crash) logs**: [last-log.txt](https://cdn.discordapp.com/attachments/851065277348446208/852791511794843708/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by welepi** [comment]
but that happens to me in PC

**Comment by welepi** [comment]
and mostly wile loading java mods
