### ISSUE TITLE
Can't load saved games

### ISSUE THREAD

**Issue by Ikriva** [Anuken/Mindustry#5413]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Explain your issue in detail.*
The game claims to be saving games, but saved game cannot be loaded. The saved games doesn't appear in load game window. I was able to find the actual files, but importing them results in nothing. No crash or anything, just the saved game won't appear. The game starts to create copies of the files with filenames such as "0.msav"

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Try load a saved game. Try import saved game

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN
-GAME.*
[saves.zip](https://github.com/Anuken/Mindustry/files/6638145/saves.zip)
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
No crash report file created
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The saves linked are *campaign* saves, which cannot be imported. They are hidden.
