### ISSUE TITLE
A mod crashes like never before; why is a js mod doing the gen

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#5417]
**Platform**: *Windows*

**Build**: *21177*

**Issue**: *sk7725/testers crashes with a reason that does not make sense; this is what Intellij's Code Coverage(Run log) outputs:*
```
[I] Loaded mod 'testers' in 6.3643ms
[2021.06.13 13:07:26] (Coverage): Error during class instrumentation: rhino.gen.testerblocks_5: java.lang.RuntimeException: java.io.IOException: Class rhino/gen/testerblocks_5 not found
```

**Steps to reproduce**: *download sk7725/testers*

**Link(s) to mod(s) used**: *sk7725/testers*

**Save file**: *I didn't get to open one, crash at load*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *I WISH I HAD ONE*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sk7725** [comment]
full log below:
```
[I] Loaded mod 'testers' in 6.3643ms
[2021.06.13 13:07:26] (Coverage): Error during class instrumentation: rhino.gen.testerblocks_5: java.lang.RuntimeException: java.io.IOException: Class rhino/gen/testerblocks_5 not found
[I] [testers/main.js]: Load Complete!
[I] Time to initialize modded scripts: 2642.0461
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa24634902, pid=11772, tid=15100
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.2+12) (build 14.0.2+12)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.2+12, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [MSCTF.dll+0x64902]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\starw\Documents\GitHub\BetaMindy\hs_err_pid11772.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 1
```

**Comment by Anuken** [comment]
> why is a js mod doing the gen

*Any* JS mod generates classes; this has always been the case. IntelliJ "code coverage" is just confused, it's not a problem.

![image](https://user-images.githubusercontent.com/10100000/121808902-ab527c80-cc28-11eb-9563-642eef28edf2.png)

> Cannot invoke "arc.scene.Scene.getStyle(java.lang.Class)" because "arc.Core.scene" is null (testerblocks#245)

The mod is crashing because you're trying to create a dialog instance at *content-load* time, which isn't possible because `Core.scene` is null at this point. Create the dialog when it's needed instead.
