### ISSUE TITLE
units can walk pass payload source/void.

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry#5424]
**Platform**: `Windows 10`

**Build**: `BE Build 21255`

**Issue**: *Explain your issue in detail.*
units can walk pass payload source/void like it's not there, even if it is intentional, it's still inconsistent with reconstructor.
insert pics:

![Fortress sus](https://user-images.githubusercontent.com/85090668/122012766-b99ac700-cde7-11eb-980b-f36dd87af1c5.png)
this looks normal, right?
![Cyerce very sus](https://user-images.githubusercontent.com/85090668/122013106-0e3e4200-cde8-11eb-9977-dbf8452e30f5.png)
Not anymore. (Cyerce can sail pass it like it's not even there)

Also, I've found out that naval units can sail pass the conveyor. maybe it(the bug) was intentional? If it is, then I'm sorry for wasting your time.
![Risso not sus](https://user-images.githubusercontent.com/85090668/122014839-c4eef200-cde9-11eb-8e69-916e27567a80.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Place down a payload source, spawn a naval unit or ground attack unit. walk pass the payload source. and yeah.

**Link(s) to mod(s) used**: No mod used.

**Save file**: I don't want Anuke to reap my soul, so here we go: [The map from previous issue.](https://github.com/Anuken/Mindustry/files/6653882/Gate_Of_Antumbra.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: -

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
looks like both blocks are set to size 3, possibly a mistake (payload size limits) or simply copied over from other payload-able blocks, according to this it might even allow blocks to be placed over each other visually, but i haven't seen that yet 🤔 

https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/payloads/PayloadSource.java#L24
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/payloads/PayloadVoid.java#L21

**Comment by Anuken** [comment]
Intentional.
