### ISSUE TITLE
Leg And Ship Type Bug

### ISSUE THREAD

**Issue by ItsBUESCTime** [Anuken/Mindustry#5429]
**Platform**: Android

**Build**: Release Build 126.2

**Issue**: Some of Leg Type Units can Skip it through to the Solid and especially they can walk the deep liquid sources, like slag
![Screenshot_2021-06-16-20-52-28-1](https://user-images.githubusercontent.com/84010229/122314116-229a5000-cf4a-11eb-9632-0ebcb7067c67.jpg)
The Ship Type unit with shield can be across the slag. This can't be beatable... with Slag on liquid sources
**Please look at right one of Ship Units**
![Screenshot_2021-06-17-08-39-28](https://user-images.githubusercontent.com/84010229/122314201-4f4e6780-cf4a-11eb-9fbb-6523c9ab0eab.jpg)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Create new custom map, fill up a slag in a whole map and make a path but no connected to core... make a custom waves with ship type w/shields and leg type units. Set ship type units's shield to 1K+. Play and see what happened.
I recommend to place Enemy Spawn at Top Right and Your core must be with Ground Blocks not Liquids onto Bottom Left

**Link(s) to mod(s) used**: No mod Used

**Save file**: Well I made one of TD Map test... here we go [TD Map Test]( https://drive.google.com/file/d/1qWROHNEHMx3M2LmWLZ7ZItneSH6ytkXJ/view?usp=sharing)
**Sorry for Redirected to Drive, So you can download it**

**(Crash) logs**: No Crashes 

----------------

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
all of this is intended. also, boats float on liquids, and the slag can only deal damage so fast, such that even if it didn't have a shield, omura would still be able to just tank the melting/burning (i forget which) damage

**Comment by JrTRinny** [comment]
Spider have long legs so it floats on water. It also can climb walls, but only the light part. try to make the walls thicker, so those spiders can't climb.

**Comment by IIINSTINCT** [comment]
._. Close this issue

**Comment by ItsBUESCTime** [comment]
Aight

**Comment by ItsBUESCTime** [comment]
Then why?

**Comment by BlueWolf3682** [comment]
This isn't a bug, everything here is entirely intentional. Close this issue, as it is unwarranted and not going to be fixed.

**Comment by Anuken** [comment]
Neither of these are bugs.

**Comment by ItsBUESCTime** [comment]
Okay Thanks
