### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Olo123pl** [Anuken/Mindustry#543]
I would like to propose changing the name of the "Scorch" weapon to "Płomień" (flame in polish)

**Comment by Natchuz** [comment]
@Olo123pl czy mógłbyś zagdać do mnie na discordzie: Natchuz#7585 to wypiszesz mi wszystkie nazwy do zmiany

Eng:
Could you please talk to me on discord: Natchuz#7585 so we can list all the names to be changed?

**Comment by Anuken** [comment]
If you would like to propose a translation change, consult with the other translators and submit a pull request when you decide on a result. Or you could simply create a pull request and have the discussion there.
