### ISSUE TITLE
my data always is  getting corrupted for no reason

### ISSUE THREAD

**Issue by iwantmyaccountback** [Anuken/Mindustry#5433]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**:when i play mindustry and then when i turn off my pc and go play more in next day my account data is gone from public servers.

**Steps to reproduce**: i was just casually playing the game in pvp servers.

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> my account data is gone from public servers.

Mindustry does not handle data for other servers.

**Comment by Somka000** [comment]
> **Issue**:when i play mindustry and then when i turn off my pc and go play more in next day my account data is gone from public servers.
> 
> **Steps to reproduce**: i was just casually playing the game in pvp servers.

About what servers are you talking?
