### ISSUE TITLE
Mindustry 32bit not working

### ISSUE THREAD

**Issue by DrDarling** [Anuken/Mindustry#5436]
![32bitMindistry](https://user-images.githubusercontent.com/86157167/122644375-92146900-d11d-11eb-9747-d1a75e4cf1b2.jpg)
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: *I want to play Mindustry on an old 32bit laptop, but even though I downloaded the 32bit version it keeps giving me the "mindustry.exe is not a valid Win32 application" error message as seen in the picture*

**Steps to reproduce**: *I downloaded the 32bit version of Mindustry from the itch.io website onto a flash drive and I plugged said flash drive into the 32bit laptop, a Sony Vaio VGN-FS195 VP with an Intel Pentium processor, running Windows XP Professional . After that I ran the Mindustry.exe file and I got that error message. I've repeated this process 3 times now and nothing's changed.
*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Windows XP

Windows XP is not supported. Mindustry runs on 32-bit Windows 7 or above.

**Comment by SMOLKEYS** [comment]
my guy tryna run mindustry on a XP lmao

**Comment by DrDarling** [comment]
> my guy tryna run mindustry on a XP lmao
Yeah my bad

**Comment by abdallah362** [comment]
this is also happen to me but in windows 10 64Bit
