### ISSUE TITLE
Music and sound does not available on Android 10

### ISSUE THREAD

**Issue by Hibari233** [Anuken/Mindustry#5437]
I need to open Single Channel Sound(Change dual channel sound into a single one) to make the sound of the game available.
I played it normally a few months ago.
But the latest version have this bug.
Even the Fdroid custom build does not have this bug.
Device: Mi Mix2 
Rom: Pixel Experience (Android 10)

**Comment by Anuken** [comment]
Cannot reproduce.

**Comment by Hibari233** [comment]
I played Genshin Impact. It had this bug too. But they fixed it in the latest build.

**Comment by Anuken** [comment]
If even a well-tested game like that has this "bug", it's likely a problem with your device. None of the phones or emulators I've used have this problem, and ***you did not fill out the template***.

**Comment by SMOLKEYS** [comment]
> you did not fill out the template.

oh no

**Comment by Somka000** [comment]
> I played Genshin Impact.

oh no @Dexapnow
