### ISSUE TITLE
launchpad rate bug

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry#5439]
**Platform**: mac

**Build**: 126.2

**Issue**: I have salt flats set up as my export sector, with 8 launchpads per material, and set it up to launch all materials except for pyratite, scrap, and spore pods, as usual, to sector 208. however, after waiting for multiple minutes, the export rates never changed from these values: 
<img width="1280" alt="Screen Shot 2021-06-20 at 9 40 11 AM" src="https://user-images.githubusercontent.com/75851043/122676204-0517f100-d1ab-11eb-8b4d-1c7b979f9cbc.png">
(lead and coal are being mined by monos and logic-controlled polys, respectively)

**Steps to reproduce**: configure salt flats as usual, wait several minutes, checking export stats every 30ish seconds

**Link(s) to mod(s) used**: I have RTFM and DaGamerFiles' classic music mod but i doubt those are related, though it never happened before i installed the classic music mod.

**Save file**: 
[saves 2.zip](https://github.com/Anuken/Mindustry/files/6682471/saves.2.zip)
for some reason i can't upload the zip created by hitting the export game data button

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> the export rates never changed from these values

Why would they?

> wait several minutes

Export rates only update when you are in the exporting sector.

> for some reason i can't upload the zip created by hitting the export game data button

Save files without game data cannot be used for testing this.

**Comment by oinkymoo** [comment]
i was waiting in salt flats, i probably should have clarified. those export rates, except for lead, don't even remotely resemble the rates for 8 launchpads

**Comment by Anuken** [comment]
Looking at the save, the problem is that you *cannot* continuously launch more resources than you are producing or losing.

All your materials are stored in a massive buffer, so they are not actively being extracted from the core, nor are they being actively produced.

**Comment by oinkymoo** [comment]
even so, they are still going into the launchpads

**Comment by Anuken** [comment]
That doesn't matter.

**Comment by oinkymoo** [comment]
oh ok
