### ISSUE TITLE
Craters map: kilns are not interactible

### ISSUE THREAD

**Issue by lf-** [Anuken/Mindustry#5441]
**Platform**: Linux: Arch Linux with openjdk 16.0.1

**Build**: "bleeding-edge build 21272", but I was previously using a locally built commit d6566830a. 

**Issue**: On the craters map, I can't figure out how to use the kilns. They seem to not be interactable, putting resources in with belts does nothing, and which makes progression impossible (as I understand it) as I can't make metaglass. It's possible that I am missing some claim button, in which case, I couldn't find it.

After hitting this I grabbed an official build, then I tried deleting the relevant sav file to the map and restarting the map, to no change.

This is what they look like:

![image](https://user-images.githubusercontent.com/6652840/122723128-70070d80-d227-11eb-82dc-df3d0a433c54.png)

**Steps to reproduce**:  I got to the Craters map from the previous one and the kilns did not work.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/6684872/saves.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dioo0** [comment]
Not a bug

**Comment by BlueWolf3682** [comment]
This isn't a bug. Derelict (black team) things are not supposed to be interactable.

**Comment by lf-** [comment]
Then, how do I make metaglass?

 The [wiki page here](https://mindustry-unofficial.fandom.com/wiki/The_Craters) says this:

> Fire up the two abandoned Kilns to start producing Metaglass and research the Mechanical Pump and Conduit to increase the power of your drills

Which implies that they should be usable! Or am I misunderstanding how I'm actually supposed to do this?

**Comment by BlueWolf3682** [comment]
That wiki is incorrect. Though you *can* start the kilns up, it's easier to defeat the map, then proceed to research the kiln and use it in another sector.

**Comment by lf-** [comment]
> That wiki is incorrect. Though you _can_ start the kilns up, it's easier to defeat the map, then proceed to research the kiln and use it in another sector.
> To use the kilns, deconstruct them a bit and reconstruct them to place them on your team.

How do I actually do that if I don't have them researched, given they unlock when the map is defeated?
