### ISSUE TITLE
Black lines on tiles 

### ISSUE THREAD

**Issue by Blubvis725** [Anuken/Mindustry#5451]
**Platform**: *iOS*

**Build**: *Release build 126.3*

**Issue**: *When playing, the textures of certain tiles on the map have black lines of them, which can be annoying*

**Steps to reproduce**: *I hopped into the game, and almost immediately I saw black lines on some of the tiles, it also happens in the menu, where you can see black lines om certain tiles in the background*

**Link(s) to mod(s) used**: *I do not use mods*

**Save file**: *Not needed, happens on all of my iOS devices. Also happens in the main menu*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *-*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

2 photos of the issue:

![6AE20B3C-1B23-4E8D-A56C-E2426D06AC2D](https://user-images.githubusercontent.com/62372520/123125185-95bf2d00-d448-11eb-9d1b-b88fd43c0a0a.png)

![2C6F1D80-92C5-42C0-A263-54E1FE23F36A](https://user-images.githubusercontent.com/62372520/123125210-9952b400-d448-11eb-8c5f-bc3a79e38bc6.jpeg)

**Comment by Anuken** [comment]
Disable linear filtering.

**Comment by Blubvis725** [comment]
I see, thanks. Didn’t know that was the issue
