### ISSUE TITLE
Broken sounds

### ISSUE THREAD

**Issue by Ksawi999** [Anuken/Mindustry#5452]
**Platform**: `Android`

**Build**: `release build 126.2`

**Issue**: Sounds are from time to time making unpleasant 'pop' sound. Sometimes it bugs as much as the music sounds like a helicopter. After every maximize of minimized game, sounds are much more bugged. It even happens on title screen so it can't be problem with too many sounds or data (not like in #5124). I can't attach screen record because all sounds are disabled on it (bug #4916). By the way the theme music sounds better (like a remix).

**Steps to reproduce**: launch game

**Link(s) to mod(s) used**: `none`

**Save file**: [Game-save.zip](https://github.com/Anuken/Mindustry/files/6692156/Game-save.zip)

**Crash report**: `none`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce any of these problems.
