### ISSUE TITLE
Screen burn-in countermeasures for mobile users with OLED displays?

### ISSUE THREAD

**Issue by PalatinatePotatoFarmer** [Anuken/Mindustry#5456]
Hi,

I have been playing Mindustry quite intensively (2-3 hrs a day) for the last ~3-4 months and I absolutely love it!
Easy to get started with, yet hard to master (and I am still far from mastering it).

I have a bit of a special issue with the game, though.

I am playing this on my mobile, a rather ancient Samsung Galaxy S7 which I have since early 2017. 
I am quite familiar with burn-in problems with OLED displays. It was really bad on my first Android (Galaxy S2), newer devices still show the effect, but not as badly as older ones. My S4 was already much better than the S2, the S7 again improved over the S4. 
For example, I have a simple puzzle game that I had been playing excessively on all of these devices since the S2. It displays the score in white on dark green. After a while this led to a noticeable burn-in on all three devices (worst on the S2, of course). But that was after playing this game for _years_, sometimes for hours on end every day. With Mindustry, I now notice strong burn-in after just a few months.
Check the attached image of the lower-right screen corner, which clearly shows Mindustry "scorch marks" ;-). 
Also check the attached image of the upper-left corner, where you can see the traces the aforementioned "puzzle game" left on my screen. But as you can see, the burn in is much less severe, despite I clocked in a lot more playtime over the last four years with this game compared to Mindustry.

I can live with this on my old S7, which has been banged up a lot over the years anyway. But now I got a new phone, again with an OLED display, and I am now slightly hesitant to play Mindustry on it, fearing the same thing is going to happen to my shiny new device. Of course I can turn down screen brightness to some degree, but I wonder if it would be possible to add some simple burn-in mitigation functionality, e.g.
- adding a simple "UI color scheme" functionality that allow users to select a less contrasty scheme for the menu elements
- since I am generally playing in portrait orientation it would also help if I could use the device "top-down". All it would take is that Mindustry would need to adjust its UI rotation also when I hold the device in portrait orientation but upside down, which it doesn't. I started doing that with "the other game" (which supports this) as mitigation in order to distribute OLED wear more evenly. 
- slightly shifting the UI elements over time by a few pixels would cause softer contrast of the burn-in marks, which would make them less distracting

I also wonder why the effect is so pronounced with Mindustry - there are other apps that I use regularly which also have hard black-white contrasts in their UI, but I see barely any marks. Or take the Android system tray, which displays all the time when using a non-fullscreen app - no traces at all.

Regards

PalatinatePotatoFarmer

![Lower_right_corner](https://user-images.githubusercontent.com/72497613/123285102-0e87bd00-d50d-11eb-8a11-1f49748bc847.jpg)
![Upper_left_corner](https://user-images.githubusercontent.com/72497613/123285106-0f205380-d50d-11eb-9098-d9470edd41f8.jpg)

**Comment by BlueWolf3682** [comment]
If your screen is burning in like this, turn down your screen brightness. Though my old iPad 4 does suffer from this issue on most apps, the screen burning is common to OLED displays and does not damage the screen permanently. You may see this on other apps or games that use pure white icons or UI, even if you say you haven't it does occur often.

**Comment by Anuken** [comment]
> adding a simple "UI color scheme" functionality that allow users to select a less contrasty scheme for the menu elements

This is not simple to implement; every single UI sprite and icon would have to be re-drawn, tinted and tested in combination with other elements.

> it would also help if I could use the device "top-down"

I don't think this would help much. Unless you're flipping your phone constantly, it would still display the UI on one side of the screen for extended periods of time.

Android also makes it difficult to implement this while preserving backwards compatibility, "fullUser" orientation was added in API 18, while Mindustry supports down to API 14.

> slightly shifting the UI elements over time by a few pixels would cause softer contrast of the burn-in marks, which would make them less distracting

I don't see how this would be accomplished without breaking the UI completely... or at all.

---

This is an issue tracker for bug reports, not feature requests - customizing UI style or other "mitigation features" are considered features, and [should be posted here instead](https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose). I don't know how you managed to skip the issue template here.
