### ISSUE TITLE
Sector view error message piles up.

### ISSUE THREAD

**Issue by Henry0804** [Anuken/Mindustry#5457]
**Platform**: Windows 10

**Build**: 126.2

**Issue**: While in multiplayer campaign, pressing n many times in the map view causes the same message to be printed over and over.

**Steps to reproduce**: You need two mindustry clients to reproduce this effect. First, take one client and host a campaign server. Then connect to that server with the other client. Using the other client, press m and then spam n a couple times. The message "Only the host can view sectors" should appear. But if you reproduced this effect correctly, you will have to click the ok button as many times as you pressed n to escape the message box.

**Link(s) to mod(s) used**: No mods used.

**Save file**: I am 100% sure that this issue has nothing to do with a save file.

**(Crash) logs**: This is not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
I wasn't 100% sure what to search, for since I don't know if the planet view thing is called planet map, or sector view, or something else. Sorry if I have wasted your time.

**Comment by Anuken** [comment]
Every time you try to open the planet dialog, a new message appears. I don't see this as a bug.
