### ISSUE TITLE
help i just loaded a mod and any mod it always says error in mindustry pls Anuken helpp.

### ISSUE THREAD

**Issue by Your-mindustry-soup** [Anuken/Mindustry#5463]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android samsung tab 4.4.4
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
my tablet is samsung 4.4.4 and mindustry version v6.0.126.2
**Issue**: *Explain your issue in detail.*
i cant use mod because it errors
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
 i just imported this mod

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
https://github.com/Eschatologue/Heavy-Armaments-Industries.git

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
https://github.com/Eschatologue/Heavy-Armaments-Industries.git
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
that is not an appropriate way to title a bug report. it should be a short description of the bug _and nothing else_
