### ISSUE TITLE
Launch pad destination sync in coop campaign

### ISSUE THREAD

**Issue by Zaflis** [Anuken/Mindustry#5464]
**Platform**: Windows

**Build**: Steam build 126.3

**Issue**: Launch pad destination name isn't synced in cooperative campaign for the joining player. This would be good for the other player when verifying that hoster isn't forgetting something vital...

**Steps to reproduce**: As a joining player you can't edit the destination yourself, observe as hoster places one down and says he changed the destination. You probably see it as "Ground zero" all the time.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It can't be synced; the destination only matters for the host, not the client. The only "fix" for this would be to remove the destination display for clients altogether.
