### ISSUE TITLE
Player can spawn use other team core

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry#5467]
**Platform**: *Android/iOS/Mac/Windows/Linux*
All

**Build**: 126.2

**Issue**: *Explain your issue in detail.*
Use this code in client, can spawn using green core, there is no team check in server.
```js
Call.unitControl(Vars.player,Team.green.core().unit)
```

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
```js
Call.unitControl(Vars.player,Team.green.core().unit)
```

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
---
I see the code in master https://github.com/Anuken/Mindustry/blob/0cd4ef575de24ea57b426445f7639a9dc1cee71d/core/src/mindustry/input/InputHandler.java#L381, may fix in 7.0

**Comment by Anuken** [comment]
7.0 doesn't handle core respawning this way.
