### ISSUE TITLE
area 173 resources outside of playable area

### ISSUE THREAD

**Issue by rix117** [Anuken/Mindustry#5472]
not really sure if this is an issue
 probably not but i figured i'd bring it up just in case it causes other issues.
there is two locations where this are 2 spots of lead minerals outside the playable area(that i can find)
![20210625150832_1](https://user-images.githubusercontent.com/38912600/123474221-a34ef100-d5c7-11eb-99aa-686140161e3e.jpg)
i'm still in the area if needed to stream whats going on.

**Comment by Quezler** [comment]
~~i actually use hovering drills over terrain on nydus to figure out where to nuke terrain in order to get to them~~ 😗

**Comment by Anuken** [comment]
I see no inaccessible ore on that map locally, and you have not attached a save.

**Comment by oinkymoo** [comment]
not only that but you managed to bypass the template entirely
