### ISSUE TITLE
Crash when joining steam servers

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#5474]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
steam build 127
**Issue**: *Explain your issue in detail.*
When joining a server hosted by a steam user, the player joining crashes
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
one player hosts a server via Steam and invites another player, the second player crashes
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Doesn't seem applicable, tried many saves and all of them crashed, as well as different hosts.
But anyways, here's the save file I tried playing on.
[SaveFiles.zip](https://github.com/Anuken/Mindustry/files/6719036/SaveFiles.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-06_25_2021_18_17_49.txt](https://github.com/Anuken/Mindustry/files/6718898/crash-report-06_25_2021_18_17_49.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by AtobaAzul** [comment]
Hope I did it correctly.

**Comment by oinkymoo** [comment]
> REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE

are you sure about that?

**Comment by AtobaAzul** [comment]
If you insist...
