### ISSUE TITLE
Broken window scaling

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry#5476]
**Platform**: *Android/iOS/Mac/Windows/Linux* Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 127

**Issue**: *Explain your issue in detail.* game looks like this when i opened it
<img width="1280" alt="Screen Shot 2021-06-25 at 10 19 24 PM" src="https://user-images.githubusercontent.com/75851043/123499019-aff03b00-d601-11eb-9fea-77a71c8f9e62.png">

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
downloaded the new version from the itch.io app. open it up and the screen is small while it loads. i thought it would fix itself when it finished loading but nope

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.* NA

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
i will also mention that the button hitboxes are still in the right places, which makes menus very awkward to navigate

**Comment by oinkymoo** [comment]
as far as i can tell the only thing that has been scaled down are the visuals

**Comment by Anuken** [comment]
I cannot reproduce this on a Mac VM.

**Comment by oinkymoo** [comment]
is there any possibility that its an itch-specific bug?

**Comment by oinkymoo** [comment]
update: tried downloading on a different mac, works fine, am now even more confused

**Comment by oinkymoo** [comment]
update 2: updating macos on the problem computer fixed it

**Comment by Anuken** [comment]
Sounds like a MacOS bug - I didn't change any display code in the 127 release.

**Comment by kakuhen** [comment]
Regression on OS X v10.15 with alpha 129.1. Scaling issue and text fails to render in dialogs (such as the "join server" one).

<img width="1904" alt="スクリーンショット 2021-08-02 15 02 10" src="https://user-images.githubusercontent.com/77321650/127929489-493e6475-1cc0-4dcb-b4fa-36e91fef2f2b.png">

The scaling issue goes away on resizing the window, but returns once you join a game.

<img width="1904" alt="スクリーンショット 2021-08-02 15 03 17" src="https://user-images.githubusercontent.com/77321650/127929581-ecf4d587-b74c-42e9-86d1-5b60fc4d9612.png">

126 and all prior versions rendered just fine, but I will notice they unnecessarily turned on the discrete graphics cards on 16-inch MacBooks. This has a simple fix by setting NSSupportsAutomaticGraphicsSwitching to true (or "YES") in the app bundle's Info.plist file. As for the issue I am currently reporting, I'm not sure what'd be the first step to finding the problem.

**Comment by Anuken** [comment]
I have no idea why either of those are happening, and I don't have a retina screen to debug. I did not change any `plist` properties or any of the window libraries. The only major change was a Java update, which should not cause these sorts of problems.

**Comment by Anuken** [comment]
The [latest BE](https://github.com/Anuken/MindustryBuilds/releases) creates the window with a `SDL_WINDOW_ALLOW_HIGHDPI` flag, which *theoretically* means it might support retina screen better? I don't see how that would fix the problems above or why it wasn't necessary before, but it's worth a shot.

Note that Mindustry jar files on Mac must be run with `-XstartOnFirstThread` as an argument.

**Comment by kakuhen** [comment]
Thank you for responding. This seems to have fixed the issue on my end, which I find strange, too. I still haven't found what exact changes between 126.2 and 129.1 (or 127 in OP's situation) would have caused this bug in the first place.

<img width="1904" alt="スクリーンショット 2021-08-02 19 08 31" src="https://user-images.githubusercontent.com/77321650/127946460-ef3af264-ae5f-48a9-a64f-6a730c88b358.png">

**Comment by Anuken** [comment]
Hold on, but is the issue present in earlier (e.g. 21591) BE versions? It might be the case that the macOS application bundle's Java version or plist is messing with the window, while the BE builds aren't.

**Comment by kakuhen** [comment]
What I am doing to test the BE builds is to swap the desktop.jar files in the 129.1 app bundle.

I have just tested 21590 and 21591, and neither have the scaling problem (nor the text rendering problem) described earlier. The problem returns when I use the desktop.jar from the pre-alpha build 129.1, however.

**Comment by Anuken** [comment]
> I have just tested 21590 and 21591, and neither have the scaling problem (nor the text rendering problem) described earlier.

Wait, but those versions *definitely* don't have the high-dpi window flag, and the only difference between 129.1 and those versions (window-wise) is a slightly different borderless windowed & fullscreen implementation. Are you using either of those? Judging by your screenshot, it doesn't look like that is the case.

**Comment by kakuhen** [comment]
Correct. I am just running the game in windowed mode. For some reason, if you swap the desktop.jar file in pre-alpha build 129.1 with the BE 21590, 21591, or 21593 builds, the problem goes away. 

For reference, here's the rather ugly setup in my 129.1 app bundle
<img width="882" alt="スクリーンショット 2021-08-02 19 43 40" src="https://user-images.githubusercontent.com/77321650/127949576-e14b15d9-1eaf-48c2-a76b-bb7c8a59b362.png">

The desktop.jar in the picture is precisely the one from the pre-alpha 129.1 build. If any of the desktop.jar.x files are used in place of the desktop.jar, then the problem goes away. I'm not sure what to make of this.

**Comment by Anuken** [comment]
This makes about as much sense as Mindustry's [borderless fullscreen behavior on Windows](https://github.com/Anuken/Mindustry/commit/a7cc6185ad31cd27810705fa777528f286462521#commitcomment-54210557) - I suppose we'll see the issue is really fixed in the next release?

**Comment by kakuhen** [comment]
Sorry to bother again, but it seems that the High DPI flag in SDL_Window does more harm than good. Here is my GPU usage with a 60 fps cap and vsync enabled.

<img width="605" alt="スクリーンショット 2021-08-02 20 15 59" src="https://user-images.githubusercontent.com/77321650/127952282-d816d4fb-928f-4104-bac1-107c149dd088.png">

The topmost peak where you see nearly 100% GPU usage is with BE 21593. The smaller peak afterwards is me testing BE 21591 with the exact same settings. Although in both cases I am achieving exactly 60 fps, BE 21593 seems to cause thermal throttling or some other issue that makes the entire graphics stack on Mac OS lag (i.e. other windows, dock animations, and so on have a noticeable stutter).

On my external GPU, I obtain similar results: unusually high GPU usage, but no thermal throttling (unless I disable vsync and let it render as fast it can, which in case GPU usage spikes to 100%). The graphics stack will not stutter or suffer from any lag, however (that is, other windows, dock animations, etc. will remain smooth and not stutter). 

<img width="336" alt="スクリーンショット 2021-08-02 20 23 54" src="https://user-images.githubusercontent.com/77321650/127952787-ad6b0dd5-d119-4b78-abc8-86eef27f5950.png">

My guess on why this is happens is that Retina displays are very large in resolution (the one on my MacBook is 3K!), and rendering with High DPI enabled just overwhelms the graphics card. I expect a similar issue to occur for those using 13-inch MacBook.

**Comment by Anuken** [comment]
I wonder what the point of using the flag at all is, then...?
