### ISSUE TITLE
iOS Editor - Map moving out of borders

### ISSUE THREAD

**Issue by Ghost-Ship-Supreme** [Anuken/Mindustry#5477]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: *When moving the map in editor, the map will move outside the border, and cover the left hand side, covering important options like the magnifying glass.*

**Steps to reproduce**: *When in map editor, simply select the magnifying glass and zoom in the map or move it around. The left border allows the map to “pass through” and move over the icons for several options, such as the magnifying glass and eraser.*

**Link(s) to mod(s) used**: `none`

**Save file**:   *https://www.icloud.com/iclouddrive/0TbugnpMz6uHYl6Lscc7QouDg#mindustry-data-export*

**Crash report**: *N/A*

![B8F74C08-C86E-4988-ACB7-B51FD58CBBD8](https://user-images.githubusercontent.com/86503850/123499402-107c7980-d5fc-11eb-85ee-ae1813c59b48.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
an image might be helpful here

**Comment by Ghost-Ship-Supreme** [comment]
> an image might be helpful here

Oh! I almost forgot. Photo added.

**Comment by Anuken** [comment]
This was fixed in 127.
