### ISSUE TITLE
Game sound output error

### ISSUE THREAD

**Issue by xz-dev** [Anuken/Mindustry#5479]
**Platform**:
ArchLinux

**Build**:
127 pre-alpha

**Issue**:
In the KDE desktop environment, the game sound of version 127 is forced to output from the default onboard sound card

**Steps to reproduce**:
Upgrade game to 127.(126 version is ok)

**Link(s) to mod(s) used**: 
no mod

**Save file**: 
Nope

**(Crash) logs**: 
Not crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I won't be fixing this.

**Comment by xz-dev** [comment]
> I won't be fixing this.

But why

**Comment by Anuken** [comment]
Audio on Linux has been a constant source of problems on every backend I've tried; it works on my machine, and I'm not interested in further changes.
