### ISSUE TITLE
crash on a server

### ISSUE THREAD

**Issue by abdallah362** [Anuken/Mindustry#5492]
**Platform**: *windows*

**Build**: *21339*

**Issue**: *game crash on a server*

**Steps to reproduce**: *the game randomly crash*

**Link(s) to mod(s) used**: *override-lib, logicDebugger, developer-mod*

**Save file**: *
[bug'.zip](https://github.com/Anuken/Mindustry/files/6721738/bug.zip)

**(Crash) logs**: *
[crash-report-05_31_2021_23_32_05.txt](https://github.com/Anuken/Mindustry/files/6721740/crash-report-05_31_2021_23_32_05.txt)
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
That's a mod bug, Rhino JS isn't used in the basegame.

**Comment by abdallah362** [comment]
i don't know i was just playing now should i close the bug report?
