### ISSUE TITLE
Save messing when the game is stoped due to a forced shutdown

### ISSUE THREAD

**Issue by JayTheD3veloper** [Anuken/Mindustry#5496]
**Platform**: *Windows 10*

**Build**: *build 126.2*

**Issue**: *i'm playing mindusty normally and my pc start lagging (because of a python program that is running on background i guess) to try ride of this i pressed the shutdown button until the computer shutdown, when i come back, all my saves are completly messed up. All caputred sectors under attack, Sectors that i never captured just tried under attack too, and my search tree reseted*

**Steps to reproduce**: *open the game, play for a while (campaing), force shutdown by holding the power button, boot again, look to your progress in the campaing*

**Link(s) to mod(s) used**: *Not applicable.*

**Save file**:*,[save.zip](https://cdn.discordapp.com/attachments/391020510269669378/858880435887145020/saves.zip) i deleted main saves and rolled back to the backup on the folder, but brfore that is already messed up (i can resotre the deleted files becuase it is on my bin)*

**(Crash) logs**: *Not applicable. (i think)*

---
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Search the closed and open issues to make sure that this problem has not already been reported.
