### ISSUE TITLE
Player formation is forgotten on sync

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#5499]
**Platform**: Windows

**Build**: 21349

**Issue**: If the player has a formation and runs /sync, the client forgets that they have a formation and thus their movement isnt capped correctly, this causes desync and is annoying. It then caps your speed when you stop commanding the formation as it thinks you have just commanded it.

**Steps to reproduce**: Grab yourself a formation and run /sync, works best if the formation contains slower units like monos on a server with strict mode enabled where this can be best seen. https://extremely.questionable.link/xTPyEV.webm

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/6726712/save.zip) This doesn't work in single player though

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Syncing formations is problematic and I'm simply not going to implement it.
