### ISSUE TITLE
Orange Corrosion too op

### ISSUE THREAD

**Issue by davidmather** [Anuken/Mindustry#550]
Hey, I have noticed that at high rounds the orange corrosion effects left by the enemies remain into the next round. As a result it just continues to stack and get more powerful to the point where menders couldn't heal it anymore and it destroyed the entire base.

**Comment by ritzip** [comment]
Do you mean slag left by eruptors? Or fire from blast daggers?

**Comment by davidmather** [comment]
Fire from blast daggers I think. They are the flying ones right? They get annoying because it tends to spread by destroying conveyer belts way too easily. Maybe armoured conveyer belts would help.

**Comment by Anuken** [comment]
If you have issues with fire, use Wave turrets to put it out. It's not a problem if you have the right defense.
