### ISSUE TITLE
Payload source not transferring units to the propulsion tower

### ISSUE THREAD

**Issue by rodrigolitzius** [Anuken/Mindustry#5501]
**Platform**: *Android*

**Build**: *21353*

**Issue**: *idk, i was testing the payload propulsion tower and then i tried to replace it with a payload void, but suddenly the payload propulsion tower stopped transferring the units to the other propulsion tower.*
![Screenshot_2021-06-28-13-08-56](https://user-images.githubusercontent.com/60452545/123672131-624c1c00-d815-11eb-952c-5a229d26f0b1.png)

**Steps to reproduce**: *Try what i said above.*

**Link(s) to mod(s) used**: *None.*

**Save file**: [h](https://1drv.ms/u/s!AnYf7oxSZjN8gwHw_cXCGq8I9RcO) 

**(Crash) logs**: *.hsarc a toN*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rodrigolitzius** [comment]
🤦‍♂️

**Comment by Dioo0** [comment]
no
