### ISSUE TITLE
Some changes in setting.bin cause error wipe

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry#5506]
### _NOTE:_ I already know that this problem got reported a lot, I just come here to give Anuke extra informations, if there is.

**Platform**: `Window 10 x64`

**Build**: _First Tested on **127.1**, Then load again in **126.2**, same problem._

**Issue**: *Explain your issue in detail.*
I was editing the setting.bin *(let's call it necromancy)* in the save file, and try to load it in Mindustry *127.1*, what happen is, uhhh, let the pictures speak for themselves.
![Screenshot (9)](https://user-images.githubusercontent.com/85090668/123778001-e926f480-d8fa-11eb-8869-3e3c6508ed59.png)
Every sector in Serpulo got resetted, all items, waves, research, all gone. only building were remained, that's why in the research below tells that I got all the material
![Screenshot (10)](https://user-images.githubusercontent.com/85090668/123778035-ef1cd580-d8fa-11eb-9b0c-e390f41bc7d9.png)
In the background is Tar Fields, as you can see, the building are still there, but waves got resetted and material got automatically research when it enters the core.

_**Another Note:**_ setting.bin looks fine. but I'm **sure** that the problem is the setting.bin itself
and the 'necromancy' that I do is changing UUID **_(Don't ask why)_**

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
change something in setting.bin (or in this case _uuid_) then load the save in Mindustry (make sure to click "Clear Game Data" first to make it pure save) see the problem.

**Link(s) to mod(s) used**: No mod used (while having the problem)

**Save file**: [MS-G2-TEST.zip](https://github.com/Anuken/Mindustry/files/6732577/MS-G2-TEST.zip)
 (it will tell that I have [BetaMindy](https://github.com/sk7725/BetaMindy) in setting.bin, but as noted above. I disabled all mod when I do the _necromancy_)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.** 
_this got reported many times, as I said._

**Comment by Anuken** [comment]
This is unrelated to the data wipe problem. I provide no support for external edits to the settings data - what you've done here is likely just corrupted the settings.

> make sure to click "Clear Game Data" first to make it pure save

Of course your data is going to get wiped if you delete the backup.

**Comment by JrTRinny** [comment]
hmmm nevermind.
now I know the real _necromancy_ now
