### ISSUE TITLE
Button lock on Android

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry#5509]
**Platform**: `Android 10`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*
In Android, when you click too fast or click with two/three fingers simultaneously, the button got locked, and you can click it unless get out of the sector or restart the game.
this also happens in v5, and with different phone (the same brand; OPPO)

Pics below: _Note that each pics was taken in different days from **April - June**, so it means that this bug is quite common to reproduce._

![bug1](https://user-images.githubusercontent.com/85090668/123836400-de3c8600-d933-11eb-9c4f-d27aeffd872e.jpg)
![bug2](https://user-images.githubusercontent.com/85090668/123836413-e268a380-d933-11eb-93b0-d203c44de87b.jpg)
![bug6](https://user-images.githubusercontent.com/85090668/123840674-d3382480-d938-11eb-9679-ff1f244cf4de.jpg)
These _**three**_ pictures here are having the same problem in the same position; _cancel_ button, which unfortunately, need to restart the game again to clear the bug. And while you're having this bug, you can't click on the cancel button that got locked, _that means you can't cancel plans unless restart or cancel each building manually_

![bug3](https://user-images.githubusercontent.com/85090668/123837172-ba2d7480-d934-11eb-82d3-8f20b644204e.jpg)
In this one, Category 9 (_or whatever you called_) got locked, as you can see I'm selecting 2 categories in the same time, and that is **obviously** a bug. _but this one is easy to fix, just get out from world and enter again_
_Note:_ This one is quite often in v5, but it's more rare now in v6, the cancel one is more common now.

![bug4](https://user-images.githubusercontent.com/85090668/123837589-3c1d9d80-d935-11eb-8f7f-abfb9aa1f407.jpg)
This one is the same as above, just with different category

![bug5](https://user-images.githubusercontent.com/85090668/123842269-c7e5f880-d93a-11eb-8f73-c825a3218060.jpg)
This pics is different than the other; the _schematic_ button got locked. That means all of the UI can have this bug?

### **I tried to give as much detail as possible, as this bug has been annoying me for a long time.**

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Try click any button very fast or click with two/three fingers simultaneously. the UI will be locked.

**Link(s) to mod(s) used**: No mod used

**Save file**: The issue is the UI, so this is not necessary. _please don't reap my soul_

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: - 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
 _although 127 is out and it is even more **stable** than the "release" version, but 127 is **still** a pre-release, so I'd still count this as **updated** (but I'll try reproducing it in 127)_
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
 _searched with the keyword "lock" and "button", didn't find anything close to this._

**Comment by Anuken** [comment]
I spent about 10 minutes on my phone trying to get the buttons to lock, but no combination of actions worked.

> click with two/three fingers simultaneously

For the categories at 200% UI scale, it's nearly impossible to tap a button with 2 fingers simultaneously, let alone 3. I tried spam-tapping each category as well, with no results.

Results for the cancel button were similar - even with 3 simultaneous presses and various combinations of releases.

**Comment by JrTRinny** [comment]
pretty weird, I just got a **bizarre** bug just 15 sec of testing it. maybe it's just my device?

![Screenshot_2021-06-30-01-40-13-71_13f989b68d7412e5a177fb13b36ac66f.jpg](https://user-images.githubusercontent.com/85090668/123850652-7b071f80-d944-11eb-9dbd-b78581df19c1.jpg)

**Comment by Anuken** [comment]
If it were that easy to reproduce on every device, I would have heard about it earlier.
