### ISSUE TITLE
Cannot use petrol to produce energy

### ISSUE THREAD

**Issue by guyomen** [Anuken/Mindustry#551]
Android version 9 
Mindustry version beta build 82
Basic electricity production plant (small one and the one with water) cannot use black liquid as source.
In the tips of the electricity production plant it's say that petrol can be used. (And it's was the case on V3)
(Sorry I have the French version of the game, then I have not the name of items)

**Comment by Anuken** [comment]
The description is outdated. Those blocks can no longer use oil as fuel.
