### ISSUE TITLE
Unit shield conflicts with the shield of force field ability

### ISSUE THREAD

**Issue by LawrenceLin2333** [Anuken/Mindustry#5510]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
127.1

**Issue**: *Explain your issue in detail.*
The shield of a unit from the spawn group data will overwrite the shield from the force field ability. This will make the shield of force field ability be determined by the shield from spawn group data.

After searching the source code, I found that an unit is assigned a shield on Line 86 in SpawnGroup.java, and the code in ForceFieldAbility.java use the same attribute.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Make a map which will spawn a Otc with 1 million shield, then its force shield will also have 1 million health.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Use this map for test
[shield.zip](https://github.com/Anuken/Mindustry/files/6735579/shield.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
This could be useful for custom waves on maps tho

**Comment by Anuken** [comment]
> The shield of a unit from the spawn group data will overwrite the shield from the force field ability.

Yes, because they use the same value. 

> Make a map which will spawn a Otc with 1 million shield, then its force shield will also have 1 million health.

Why shouldn't it? The alternative is a unit having 2 separate shield layers, which is undesirable.

**Comment by LawrenceLin2333** [comment]
> Yes, because they use the same value.

Why they use the same value? In my opinion, the shield from spawn group data should be treated as the other type of health that improve the difficulty. While the shield from force field ability is an ability that an unit has.

It is very counter-intuitive that they are same.
