### ISSUE TITLE
Put a comma in a print operation deletes all commands

### ISSUE THREAD

**Issue by knacko** [Anuken/Mindustry#5511]
**Platform**: *Windows*

**Build**: 126.3

**Issue**: In a processor, if you put in a comma in a print command outside the quotation marks, it will delete all commands within the processor

**Steps to reproduce**: 
Build a processor
Add a print command and any other random commands
Add a comma to the end of the print line (should read as: `print "frog",` if you copy to clipboard)
Close the interface
Re-open the interface
All commands will be deleted

**Link(s) to mod(s) used**: None

**Save file**: [broken save.zip](https://github.com/Anuken/Mindustry/files/6735956/broken.save.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
