### ISSUE TITLE
processors can control Blocks outrange of the processor by GetBlock

### ISSUE THREAD

**Issue by abdallah362** [Anuken/Mindustry#5523]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *21376*

**Issue**: *you can control things using GetBlock as shown in the video

https://user-images.githubusercontent.com/81780902/124190809-8c2e6880-dacb-11eb-8727-7188551ae4ba.mp4

Note: you can only do these things {draw, read, write, print}
or anything in this picture
![image](https://user-images.githubusercontent.com/81780902/124190973-c566d880-dacb-11eb-89d3-46e7f2516817.png)
*

**Steps to reproduce**: *bind any unit and use GetBlock and save the Block as a variable like this 
![image](https://user-images.githubusercontent.com/81780902/124191116-fcd58500-dacb-11eb-9b3e-ef0ee1102793.png)
and use it like this
![image](https://user-images.githubusercontent.com/81780902/124191172-12e34580-dacc-11eb-8fb8-b1e13edf3b10.png)
and it will work
![image](https://user-images.githubusercontent.com/81780902/124191225-2b536000-dacc-11eb-9fb1-4c84b795baf3.png)
*

**Link(s) to mod(s) used**: *noun*

**Save file**: *noun*
**(Crash) logs**: *noun*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.

**Comment by abdallah362** [comment]
what

**Comment by luihum** [comment]
Probably works as intended.

**Comment by Anuken** [comment]
Those are all fairly inconsequential operations in terms of gameplay, and considering how often they may be called per frame I didn't see a significant reason to add range/link checks.
