### ISSUE TITLE
Unstable Alpha for Linux on Itch can't be unzipped.

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#5524]
**Platform**: *Linux*

**Build**: *The one available via Itch as of 2021-07-02, which I _think_ is 127.2.*

**Issue**: *I cannot unzip the Unstable Alpha for Linux on Itch.  I was trying to get this version because I couldn't find OpenJDK 16 with `apt`.  I am using XArchiver, if that's relevant.*

**Steps to reproduce**: *I downloaded the unstable alpha for Linux on Itch and tried to unzip the file with XArchiver.  It didn't work.*

**Link(s) to mod(s) used**: *Unrelated to mods.*

**Save file**: *Unrelated to in-game things.*

**(Crash) logs**: *This is not a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Either your archive tool is broken, or your download was corrupted. After downloading a fresh copy from itch:
- `file mindustry.zip` correctly reports it as a zip file
- `unzip mindustry.zip` works
- The standard graphical archive manager on Ubuntu extracts without errors

**Comment by BlueManedHawk** [comment]
Huh.  `unzip` _did_ work.  This is very strange.  Thank you!
