### ISSUE TITLE
Flying DAGGER

### ISSUE THREAD

**Issue by GymeyYA** [Anuken/Mindustry#5529]
**Platform**: `Android`

**Build**: `release build 126.2`

**Issue**: *flying DAGGER*

**Steps to reproduce**: *Im just return to my save in MAZE (survival)*

**Link(s) to mod(s) used**: `none`

**Save file**:  * [Save.zip](https://github.com/Anuken/Mindustry/files/6758201/Save.zip) *

**Crash report**: *Its no crash, but i have a screen: 
![Uploading Screenshot_20210703-135103_Mindustry.jpg…]() *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [×?] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [×] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
screenshot upload failed, please retry.

**Comment by BlueManedHawk** [comment]
I'm very confused about several things about this issue.  What is this issue reporting?  Why is the screenshot link just a link to here?  Why is the elipsis spaced out weirdly?  Why are the checkboxes filled with the multiplication sign(?) instead of a capital latin letter X?

**Comment by Quezler** [comment]
>  Why is the screenshot link just a link to here?

it happens if you submit the issue or switch to markdown preview before the image has finished uploading

**Comment by Anuken** [comment]
You likely unloaded a mod that had a flying unit it.

**Comment by abdallah362** [comment]
> You likely unloaded a mod that had a flying unit it.

yes that also happens with me after install a flying dagger mod and open the world again without the mod and see the daggers flying
