### ISSUE TITLE
Game doesn't open

### ISSUE THREAD

**Issue by Mygale5** [Anuken/Mindustry#5535]
**Platform**: *Windows / Steam*

**Build**: *127.2*

**Issue**: *I was playing on the 126 version and I wanted to try the 127.2 versions but the game doesn't open but if i download the 127.1 version on itch.io i can play normaly*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No logs provided.

**Comment by Mygale5** [comment]
[last_log.txt](https://github.com/Anuken/Mindustry/files/6759040/last_log.txt)

**Comment by Anuken** [comment]
That's not a crash log.

**Comment by Mygale5** [comment]
My game doesn't crash it just doesn't open at all.
here is a little screen record : https://we.tl/t-I7xrwpqaFy

**Comment by Anuken** [comment]
I can't fix issues without some sort of crash log. If none is generated, there's nothing I can do.

**Comment by Mygale5** [comment]
Am I the first who have this problem ?
