### ISSUE TITLE
Crash (When shooting and aim to enemy)

### ISSUE THREAD

**Issue by ProDustry** [Anuken/Mindustry#5543]
**Platform**: *Windows*

**Build**: *127.1*

**Issue**: *When i aim to enemy and click on it i get crash*

**Steps to reproduce**: *When i aimed to enemy i got crash so i thinked its client problem*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *Its works on every my save.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---
[crash-report-07_05_2021_13_09_18.txt](https://github.com/Anuken/Mindustry/files/6762453/crash-report-07_05_2021_13_09_18.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Judging by the error (a Rhino issue according to stack trace, and Rhino handles Javascript which is used by some mods), and the fact that 104 mods are installed, I think this might actually be a mod problem.

**Comment by Anuken** [comment]
Not only are 104 mods installed, but this is using *a different Mindustry client*, and the file even tells you to report the crash elsewhere. Don't do that, though - this is absolutely a problem with your mods.
