### ISSUE TITLE
Payload driver units begone

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry#5549]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Mac 

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

127.2

**Issue**: *Explain your issue in detail.*

When a unit is shot with a payload driver and the game is paused while the unit is still in the air it remains in place, all normal. However, when the unit is past halfway to the receiving driver a visual bug occurs when you zoom into the unit, it disappears. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1.Set us a payload driver system
2. Pause the game with the units halfway to the receiving driver
3. Zoom in
4. Watch

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[Driver Bug.msav.zip](https://github.com/Anuken/Mindustry/files/6779041/Driver.Bug.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
-  x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Nils101** [comment]
Incredible find!
