### ISSUE TITLE
Cant zoom in Map-Editor

### ISSUE THREAD

**Issue by xXMuffinXx** [Anuken/Mindustry#555]
After resizing the map you arent able to zoom anymore.

**Comment by Aaron2550** [comment]
can confirm

**Comment by Aaron2550** [comment]
lkvbnbfxnnvm,yxc nm vjhxkvxjkhvjkxdvxhsudfhjkezuirhjffhjhjfsdjksdfhusdfjkb453862357862347865cdjhbsdjhvc78346fdsb72358

**Comment by xXMuffinXx** [comment]
> lkvbnbfxnnvm,yxc nm vjhxkvxjkhvjkxdvxhsudfhjkezuirhjffhjhjfsdjksdfhusdfjkb453862357862347865cdjhbsdjhvc78346fdsb72358

this does not seem helpful

**Comment by Aaron2550** [comment]
> > lkvbnbfxnnvm,yxc nm vjhxkvxjkhvjkxdvxhsudfhjkezuirhjffhjhjfsdjksdfhusdfjkb453862357862347865cdjhbsdjhvc78346fdsb72358
> 
> this does not seem helpful

you dont seem helpful

**Comment by xXMuffinXx** [comment]
> > > lkvbnbfxnnvm,yxc nm vjhxkvxjkhvjkxdvxhsudfhjkezuirhjffhjhjfsdjksdfhusdfjkb453862357862347865cdjhbsdjhvc78346fdsb72358
> > 
> > 
> > this does not seem helpful
> 
> you dont seem helpful

**Comment by Aaron2550** [comment]
YEEEEEEEEET

**Comment by xXMuffinXx** [comment]
> YEEEEEEEEET

**Comment by Anuken** [comment]
I have no issues with zooming after resizing a map, regardless of the way it's resized or what platform I'm on.

**Comment by Aaron2550** [comment]
win64, after resizing the map to 500x500 i cnat zoom in, i fixed this by going into the ingame editor and then leaving it. works again, im outta here

**Comment by xXMuffinXx** [comment]
i will gather some information and try to reproduce this on other platforms

**Comment by Anuken** [comment]
Fixed in 63e1311656d981d8981091b4a930b96a36cfbb2c.
