### ISSUE TITLE
mindustry don't display anything after minimizing it 

### ISSUE THREAD

**Issue by abdallah362** [Anuken/Mindustry#5550]
**Platform**: *```windows 64Bit```*

**Build**: *`21388`*

**Issue**: *mindustry don't display anything after minimizing it as shown in the video (turn the sound on)

https://user-images.githubusercontent.com/81780902/124832398-4d922580-df85-11eb-8dee-ac7a3450e2ae.mp4

it still running and there is a sound and there is a menu and I can even use it to close the game but it doesn't display
and it works fine when I restart the game 
*

**Steps to reproduce**: *see the video*

**Link(s) to mod(s) used**: *noun*

**Save file**: *noun*

**(Crash) logs**: *noun*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce on a Windows VM.
