### ISSUE TITLE
Unable to Export Game Data and Save Files

### ISSUE THREAD

**Issue by EclipsePlays** [Anuken/Mindustry#5552]
**Platform**: *Android/iOS/Mac/Windows/Linux*
- Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

- Bleeding Edge 21396

**Issue**: *Explain your issue in detail.*

- I was trying to export saves to my device so I can post a separate bug report, but  this happened. 

![IMG_20210708_205429.jpg](https://user-images.githubusercontent.com/85320516/124925321-e5981980-e02e-11eb-8fc2-53abcad0c19a.jpg)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

- You can't export save files and game  data.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

- No mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

- I can't save the game data so... 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

- No crash happened. 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are exporting to a directory that does not exist. Use a proper directory.
