### ISSUE TITLE
powergrid turns off with combustion generators if 0 consumption, even with batteries connected

### ISSUE THREAD

**Issue by Timolsen** [Anuken/Mindustry#5555]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam build 126.3

**Issue**: *Explain your issue in detail.*
in the rare instant you have 0 powerdraw on your grid, you'll see the whole grid turning on and off if you cant supply enough coal to the generators, even though your batteries are full, and all the nodes are connected to the battery rather than directly to the combustion generators.
See gif: https://gyazo.com/fec0f85b19f03334e745aa38e6424759
It happens regardless if it's connected to a building (Mixer, graphene press, etc) as long as the buildings aren't consuming power.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
at map 173 (or maybe any map).
1. place drill on coal.
2. convey coal into combustion generator.
3. make sure the generator is undersupplied with coal, so it will turn off due to lack of coal (very important)
3. place battery immediately next to generator so it gets charged.
4. place power node.
5. connect node to battery, rather than directly to the generator.
6. wait for the battery to get fully charged.
7. watch the power node turn on and off in sync of the generator running out of coal.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None, total clean game. just started it today and experienced this 1.5 hours in.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
I think I uploaded a sivefile zip to this report, but cant see it anywhere. I'll double check right are submitting this :)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
No crash :)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Related to #4168 but I provided all the details you need to test this bug using a very simple setup, easy to reproduce.**

**Comment by Anuken** [comment]
I don't see the problem. No power is being produced, so power production is 0, and there's no reason for any power to flow through the grid.

**Comment by Timolsen** [comment]
I'm going nuts over I can't upload the savefile to this post:
![image](https://user-images.githubusercontent.com/5243532/124978924-aec40280-e032-11eb-91c9-b00f5c3df91f.png)

Here's a link to the savefile instead: https://www.dropbox.com/s/ojp0b6b3y9ejd63/saves.zip?dl=0
(I know it's a dropbox link and you'll kill me if I move the file =P)

**Comment by Timolsen** [comment]
> I don't see the problem. No power is being produced, so power production is 0, and there's no reason for any power to flow through the grid.

But it's annoying light show =_=

Jr[TH]inny on discord suggested I reported it as a bug.

**Comment by Timolsen** [comment]
But then again, it's a very rare occasion, so the impact is close to none.

**Comment by Quezler** [comment]
> I don't see the problem. No power is being produced, so power production is 0, and there's no reason for any power to flow through the grid.

well if batteries still contain a(ny) charge it can still be used, would be weird if the wires stayed dark 🤔

**Comment by Timolsen** [comment]
Oh, I get it now. the bar jumping up and down is showing SURPLUS power. And because the batteries are all full, it gives a surplus which can be seen on the nodes. And the batteries won't emit power before there's actually a need for it.

clever, but looks weird at first.
