### ISSUE TITLE
handshake failure when loading mod browser

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry#5561]
**Platform**: mac. 
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 127-127.2

**Issue**: *Explain your issue in detail.* this happens whenever i open the mod browser since 127 
<img width="707" alt="Screen Shot 2021-07-10 at 12 04 59 PM" src="https://user-images.githubusercontent.com/75851043/125169351-bfca5c00-e177-11eb-8a27-71bf92a0c697.png">

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

download pre-alpha from itch, open mod browser. error also pops up again every time i type a letter into the search bar in the browser or hit ok when trying to import from github directly

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

NA

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

doesn't happen in-game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ineedause** [comment]
I got the same exact thing
Turns out you need to delete and reinstall the game
This is because the computer thinks it is a malware

**Comment by oinkymoo** [comment]
> Can I also ask if you are having issues connecting to multiplayer servers?

i am, community servers aren't showing up

**Comment by Ineedause** [comment]
Ya, something with Macs is up, plz fix this Anuke, the suffering is to much.
