### ISSUE TITLE
Multiplayer connection closed

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry#5562]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

127.2

**Issue**: *Explain your issue in detail.*

Every attempt made by me and some others on Macs to join any sort of Multiplayer server has resulted in a Connection Closed pop-up that occurs when you turn off your computer when on a multiplayer server.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. Attempt to join a Multiplayer Server
2.Suffer
 
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

Not in game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> when you turn off your computer when on a multiplayer server.

I don't understand what you mean by this. You turned off your computer, how could there be any sort of pop-up? Disconnecting is exactly what should happen.

> Attempt to join a Multiplayer Server
> 2.Suffer

Ran Mindustry on a Mac, connected to server, no suffering occurred.

**Comment by Ineedause** [comment]
I am a little late (very late) to respond to this
What I am talking about is the game disconnecting me every single time I try to join a server no matter what server I join. 
I ran a terminal to see what will happen and this is what occurred 
<img width="582" alt="Screen Shot 2021-07-12 at 9 20 39 AM" src="https://user-images.githubusercontent.com/82851415/125301537-13b07e80-e2f9-11eb-8db1-01388f1f8a4e.png">
Every single time an attempt to join a server occurs the game auto closes the connection despite there being no prompts to do so.

**Comment by Anuken** [comment]
I can't reproduce the problem, and that log doesn't contain any useful information.
