### ISSUE TITLE
reconstructors eats every 20 glass w/o effect and reset to 0

### ISSUE THREAD

**Issue by findoff** [Anuken/Mindustry#5566]
**Platform**: *Windows*

**Build**: 127.1

**Issue**: 3th reconstructor accumulate 20glass and reset to 0, sometimes begin building and reset.
* No other resources resets
* Some times(with other reconstructor) titanium disappeared instead of glass
* Sometimes reconstructor with only glass belt got some titanium when glass disappeared.
* Rebuilding reconstructor don't fix a problem, but building new reconstructor without destroying old make new functional.
* Seve+load fix problem.

**Steps to reproduce**:
Play multiplayer (bug detected only from second player, non server)
But i can't just reproduce, it's randomly happening...

**Link(s) to mod(s) used**: none

**Save file**: [t.msav.gz](https://github.com/Anuken/Mindustry/files/6797550/t.msav.gz)
Troubles with right base.

**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
Yes, i don't updated to latest release(i can't just reproduce, and get it with 127.1), but i found no issues like that and think it worth to be reported.
Sorry if i just waste your time.

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are desynced. `/sync`
