### ISSUE TITLE
why are public servers dissapearing

### ISSUE THREAD

**Issue by iwantmyaccountback** [Anuken/Mindustry#5570]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: When I got my new pc I had .io and mindustry.pl servers now they are gone, but why?

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by JrTRinny** [comment]
they moved to 7.0 pre-alpha

**Comment by iwantmyaccountback** [comment]
so that means when in my release they can't be accessed?

**Comment by Anuken** [comment]
> so that means when in my release they can't be accessed?

yes, they are no longer playable on your version.
