### ISSUE TITLE
affinities and required tiles broke

### ISSUE THREAD

**Issue by oinkymoo** [Anuken/Mindustry#5571]
**Platform**: *Android/iOS/Mac/Windows/Linux* Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 128

**Issue**: *Explain your issue in detail.* affinities and required tiles don't show up in block info pages. all variations i could find: 
<img width="1280" alt="Screen Shot 2021-07-12 at 4 17 29 PM" src="https://user-images.githubusercontent.com/75851043/125352685-93594000-e32f-11eb-8558-ad50c6b36822.png">
none found
<img width="1280" alt="Screen Shot 2021-07-12 at 4 17 34 PM" src="https://user-images.githubusercontent.com/75851043/125352688-948a6d00-e32f-11eb-8d4f-282e338988e8.png">
required tiles aren't even mentioned
<img width="1280" alt="Screen Shot 2021-07-12 at 4 17 47 PM" src="https://user-images.githubusercontent.com/75851043/125352693-95bb9a00-e32f-11eb-92fa-44620dd541c0.png">
same as spore press, but with required tiles this time

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* open info pages for above blocks, as well as silicon crucibles and watex, cuz those are the only other blocks i can think of with affinities.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.* [infopanel.msav.zip](https://github.com/Anuken/Mindustry/files/6804274/infopanel.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
crucibles and watex behave identicaly to cultivator btw

**Comment by Anuken** [comment]
Those are all correct. There are no affinity tiles in your map.

**Comment by oinkymoo** [comment]
ah i must have missed the fact that they now update with what's actually on the map
