### ISSUE TITLE
Screen sometimes freezes completely for no particular reason

### ISSUE THREAD

**Issue by KnightGabriel** [Anuken/Mindustry#5575]
Platform: Linux, Pop!_OS version 20.10

Build: Release build 126.2

Issue: I got this game relatively recently, but I've already gotten addicted, so I often end up playing for a couple hours or more. However, sometimes(Usually just once per gaming session, or a couple hours), while I'm building in a campaign map, the screen on my laptop will suddenly freeze without warning, and in the middle of me placing something down. The game still goes on, but I can't see what I'm doing, and the only way to fix it is to force shut down and restart using the power button. Before I do that I press esc and use my memory to visualize where the menu buttons are, and start waving my cursor in that area until it turns from a standard mouse pointer to a finger, and from there I try to press "Save and Quit" to the best of my ability to remember where the button is located, then press "yes" which is on the right(I think). After that I hold the power button to shut it off and then hold it again to turn it back on. It's very annoying since it's often when I've made significant progress on the level, meaning it can result in me losing all that work if I mess up trying to press the invisible "Save and Quit" button in the menu.

Steps to reproduce: It's very difficult to reproduce because it usually takes an hour or longer to appear and it's impossible to predict when it happens. All I know is that each time it happened while I was placing down something, the screen would suddenly freeze once I clicked with my mouse to put it down. Just play a campaign map for a while and keep placing down items until it happens, then try with the best of your ability to press esc, then find the save and quit button(It's the first button from the bottom up, so just move your mouse upwards from the bottom middle of the screen until the cursor changes), then click the "yes" button(which again, should be on the right, at least in my case).

Save file: x-special/nautilus-clipboard
file:///home/knightgabriel/.var/app/com.github.Anuken.Mindustry/data/Mindustry/saves/sector-serpulo-171.msav
That's all I could find, I couldn't figure out a way to open it since it says "Archive not supported"

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** I just updated and it's still 126.2, I don't think v7 has come out for my platform yet
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I use Ubuntu 20+, and I've never had the problem you're describing even during long play sessions in the campaign. Considering nobody else has ever reported anything similar, this is likely an issue specific to your system and cannot be fixed.

**Comment by KnightGabriel** [comment]
Anuken please it now happened to me twice today, but this time IT COMPLETELY FUCKING WIPED THE DATA FROM THE 2 CAMPAIGN WORLDS I WAS ON. I HAVE TO DO THOSE WORLDS ALL FUCKING OVER AGAIN BECAUSE OF THIS STUPID FUCKING GLITCH. CAN YOU AT LEAST FIX THE DATA LOSS WITH IT? I looked it up and it seems that people using Pop os have similar issues, but they said it's a hardware issue when there isn't even a way to lower graphics and my computer's hardware isn't even that bad. How am I supposed to get my worlds back? Why did they get completely wiped when I have autosave enabled and I made sure to save and quit?

**Comment by Anuken** [comment]
> CAN YOU AT LEAST FIX THE DATA LOSS WITH IT?

If *all* your game data was wiped (including research & settings), then it could be something that was already fixed in the [latest version](https://github.com/Anuken/Mindustry/releases). Otherwise, I haven't heard of such a thing happening. Mindustry already makes backups for saves.

> I looked it up and it seems that people using Pop os have similar issues, but they said it's a hardware issue when there isn't even a way to lower graphics and my computer's hardware isn't even that bad.

What do you expect me to do? Mindustry uses a well-known, well-tested window library (SDL) that runs just fine on 3 different operating systems and countless distros. If this were a bug in *my* code, or SDL's, you would not be the only person to report (or even *mention*) such a problem.

**Comment by KnightGabriel** [comment]
I was just hoping you could at least help me pinpoint it, I'm sorry I was really upset at the loss of my data and hoped you could do something since you were the game developer
