### ISSUE TITLE
about idle logic command

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry#5579]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Window 7
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
released v7b128 (also happen in other version)
**Issue**: *Explain your issue in detail.*
the Logic command:Unit,Idle didn't do that they need to do, it say "don't move but keep mining, building" but it actually didn't do anything
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i used a bind and a logic control: Idle to polys (and also monos) and they didn't do anythings (no mining no building) it happen in survival and sandbox mode
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
auto updater (prob not related}
cliff (prob not related}
developer mode (prob not related, i didn't execute any commands}
item grabber (prob not related}
Logic Debugger v1.3.1
mind-util - Utility mod (prob not related}
Override Lib v1.0.1 (used to run Logic debugger)
PicToLogic
Radar
RTFM
TimeControl (not using while testing bug)
UI lib
Unit Factory
WAISA v2.3.3
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[https://drive.google.com/file/d/1PiSNOt-yTqkEp07yUdcyv0_KTq5x62wj/view?usp=sharing](url)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---<none>

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
issuing any command to a unit will cause it to stop doing its normal behavior. this only allows it to continue building or mining in locations where it was already doing so

**Comment by vinhsad** [comment]
> issuing any command to a unit will cause it to stop doing its normal behavior. this only allows it to continue building or mining in locations where it was already doing so

i make it nearby a ore and a damaged building, and they doing nothing (checked with polys and mono)

**Comment by oinkymoo** [comment]
i mean polys dont repair damaged buildings automatically, only replace destroyed
