### ISSUE TITLE
Deprecated methods/classes stripped

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#5580]
**Platform**: *Android?*

**Build**: *v128*

**Issue**: *Cicon, which was supposed to be deprecated (warns the compiler but definitely not crash) is actually stripped leading to a crash. I have no idea if it is my d8 or your r8 that is doing that.*
Reported by SMOLKEYS (discord)

**Steps to reproduce**: *Try using a clear pipe/spinner/claw(with blocks), basically any block that uses icon()*

**Link(s) to mod(s) used**: *sk7725/BetaMindy*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
```
Mindustry has crashed. How unfortunate. Version: pre-alpha build 128 OS: Linux x32 Java Version: 0 Java Architecture: null 17 Mods: betamindy:1.0 [#b59e72]Demo of Chaos Itself[], dev-mode:2.3.2, hackustry:4, ldb:1.3.2, notepad:2.0.0, override-lib:1.0.1, pictologic:1.5.7, radar:2.10.5, test-utils:0.14, time-control:0.2, ui-lib:2.16.6, unit-factory:2.4.2, bundles:13, exogenesis:[blue]1.3.1, exotic-mod:0.5 Alpha, ground-vehicles:0.2, unitinfo:1.2 > NoSuchMethodError: 'No virtual method icon(Lmindustry/ui/Cicon;)Larc/graphics/g2d/TextureRegion; in class Lmindustry/world/blocks/payloads/BuildPayload; or its super classes (declaration of 'mindustry.world.blocks.payloads.BuildPayload' appears in base.apk)' Claw$ClawBuild.drawClaw: 327 Claw$ClawBuild.draw: 339 Block.drawBase: 269 BlockRenderer.drawBlocks: 327 Renderer.draw: 266 Renderer.update: 119 ApplicationCore.update: 37 ClientLauncher.update: 174 AndroidGraphics.onDrawFrame: 374 GLSurfaceView$GLThread.guardedRun: 1571 GLSurfaceView$GLThread.run: 1270
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not stripped; the `Payload#icon(Cicon)` method was removed.

**Comment by sk7725** [comment]
uh damn android and its newline stripper whenever you copy & paste
will fix when I get home

**Comment by sk7725** [comment]
> It's not stripped; the `Payload#icon(Cicon)` method was removed.

oh i thought you just deprecated that ... why was it removed?

**Comment by sk7725** [comment]
iirc you just deprecated other icon(Cicon) methods, why remove this one?

**Comment by Anuken** [comment]
> why remove this one?

It wasn't in the main content class, and I didn't think anyone used it.

**Comment by SMOLKEYS** [comment]
Can confirm, platform is android. But i feel like this would apply for all platforms.


Crash causes:

- Unit Pipes, whenever you enter them, game crashes.
- Spinners, if you try to spin any block, game crashes.
- Claws, if you try to pick up a block with it, game crashes.
