### ISSUE TITLE
Bug in processor

### ISSUE THREAD

**Issue by GGG1414** [Anuken/Mindustry#5586]
Hello, I just found an error related to the processor. When setting the color of an object, the display shows the opposite color that I set to another object, please fix this problem, thank you in advance.

**Comment by Nils101** [comment]
RIP template

**Comment by jumps-are-op** [comment]
> Hello, I just found an error related to the processor. When setting the color of an object, the display shows the opposite color that I set to another object, please fix this problem, thank you in advance.

dude that normal just recolor the new object
