### ISSUE TITLE
Polys won't stop trying to rebuild blocks deleted by player

### ISSUE THREAD

**Issue by ArchStanton14** [Anuken/Mindustry#5588]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Explain your issue in detail.*

Polys keep trying to rebuild certain friendly blocks deconstructed or deleted as ghost blocks by the player. It seems to have something to do with the objects being destroyed before the player can fully deconstruct them, but it could be that I only notice the issue when it's in range of an enemy turret. If this issue occurs the polys will fly to their deaths over and over, no matter how many times the player deletes the block or ghost block they're trying to rebuild.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

This has happened several times in the course of normal gameplay, when polys attempt to rebuild under fire. I can't figure out why it happens sometimes and not other, but it did not happen before the last update.

I've isolated such a glitched block: the titanium conveyor in sector 70 at  ~297,244. Deconstructing the block or deleting the ghost block will not stop the polys trying to rebuild it.

**Link(s) to mod(s) used**: `[DeltaNedas/rtfm:2.14.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN [IN-GAME.*]

[Mindustrysave.zip](https://github.com/Anuken/Mindustry/files/6826713/Mindustrysave.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by jumps-are-op** [comment]
there is a way to stop the poly is by controlling it the ghost block will update when you control the poly
