### ISSUE TITLE
loading screen don't work for me

### ISSUE THREAD

**Issue by jumps-are-op** [Anuken/Mindustry#5592]
**Platform**: *Windows 10 64xbit *

**Build**: *21451 it also happen to me before in 21112 and anything between I don't know in what bleeding edge it started
and it doesn't happen to me in V6* 
**Issue**: *loading screen is wrong
![image](https://user-images.githubusercontent.com/87120277/125904518-4b0a48f2-005d-4ab8-834c-20cd9758d8c7.png)
but it's ok after the loading screen 
![image](https://user-images.githubusercontent.com/87120277/125904612-ea428f9a-8f2e-4da4-abdf-765663bca90a.png)
*

**Steps to reproduce**: *i don't know*

**Link(s) to mod(s) used**: *noun*

**Save file**: *noun*

**(Crash) logs**: *noun*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce.
