### ISSUE TITLE
campaign sector : 170's spawn point bug

### ISSUE THREAD

**Issue by ROKuser** [Anuken/Mindustry#5593]
**Platform**: `Windows 10 x64`

**Build**: `pre-alpha build 128`

**Issue**: *Explain your issue in detail.*

1. Second attempt to occupy. Core's position moved. The position of the core has a significant impact on gameplay.
2. Wave initialization not achieved in case of attack failure.
![bug1](https://user-images.githubusercontent.com/77824588/125906876-7e5a4841-b7a1-4b9f-9ff9-ee44ab0693a4.PNG)
![bug2](https://user-images.githubusercontent.com/77824588/125906886-534869a5-68a0-41be-871c-8092cd1c09c2.PNG)
![bug3](https://user-images.githubusercontent.com/77824588/125906891-9f42114e-6b7e-488e-8687-ea989019f700.PNG)
![bug4](https://user-images.githubusercontent.com/77824588/125906895-9f75782e-9dec-43a2-9b2d-bec436e7aa41.PNG)

**Steps to reproduce**: sorry, i dont know. i just trying occupy zones.

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, sk7725/time-control:0.2, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
It's intended for cores not always be in the same spot upon launching pretty sure. But I don't think it's intended for a core to be in a wall like that...

I think the core decided to spawn in a bit of space surrounded by walls?

**Comment by Anuken** [comment]
No save provided, cannot reproduce.
