### ISSUE TITLE
Core Capture and the console command to kill all builds combined can stop the game from running.

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry#5595]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
128
**Issue**: *Explain your issue in detail.*
I think the title explains it all.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Turn on Core Capture, then enter the command line below:
`Groups.build.each(b=>b.kill())`
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Only the dev console is needed, I'm sure.
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Game stops responding no matter what map I play on, therefore not save specific.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[myCrashLog.txt](https://github.com/Anuken/Mindustry/files/6833883/myCrashLog.txt)
Note: Mindustry always grants the last log every time I try to export a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> then enter the command line below:

I provide no support for running arbitrary javascript. Your script will loop infinitely, because each core will immediately replace itself upon being destroyed.
