### ISSUE TITLE
jvm crash

### ISSUE THREAD

**Issue by AmateurPotion** [Anuken/Mindustry#5596]
**Platform**: *Windows*

**Build**: *v128*

**Issue**: *When I quit mindustry under any circumstances, the jvm crashes.(I tested it even with all mods removed.)*

**Steps to reproduce**: *After running mindustry v128 or later, exit. This will cause the jvm to crash, creating a hs_err_pid****.log file in the same mindustry data folder as the \SteamLibrary\steamapps\common\Mindustry folder.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *[hs_err_pid10888.log](https://github.com/Anuken/Mindustry/files/6834498/hs_err_pid10888.log)*

**JVM version**: *[AdoptOpenJDK 16](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.

**Comment by Bottinator22** [comment]
What's it a duplicate of?

**Comment by Anuken** [comment]
#5337
