### ISSUE TITLE
Continuous sounds sometimes end abruptly

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry#5600]
**Platform**: Linux (Kubuntu)

**Build**: 128.1

**Issue**: Continuous sounds are broken for units in general. They fail to loop.

**Steps to reproduce**: Spawn a Vela or Navanax and have them fire a laser.

**Link(s) to mod(s) used**: DeltaNedas/ldb
(Seems to be unrelated, as this is a logic-related mod)

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/6835457/bug.zip)
(Save file seems completely unrelated)
*THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
I figured out why this might be happening, the sounds are being interrupted by other sounds.

**Comment by Anuken** [comment]
Cannot reproduce. If you have many sounds happening at once, older sounds will get killed by newer ones. This is not new behavior.

> 128.1

Are you actually running 128.1? The newest one that was released less than an hour ago? Loops in 128 don't work at all.

**Comment by Bottinator22** [comment]
rip issue, I just launched 128.1 to check out the new sounds, went on a rather chaotic map, and it seems at first the Vela's continuous sound started and was interrupted. I will make a better issue when I figure out what's happening here, but it's rather strange.

**Comment by Anuken** [comment]
> a rather chaotic map

> interrupted

Again, if you have more than 16 or so sounds playing at once, old ones will stop. This is how it's supposed to work
