### ISSUE TITLE
daggers not shoooting right

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry#5603]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
bleeding edge 21467
**Issue**: *Explain your issue in detail.*
while i was commanding, some daggers were shooting straight, while i wasnt
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i dont know
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
i used time control and testing utilities, i dont know how to get the zip file for them

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
this is it but the map is done
[(invalid).zip](https://github.com/Anuken/Mindustry/files/6835796/invalid.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

also i have a video showing the bug
https://user-images.githubusercontent.com/87596406/126059172-9a5d049b-f69b-422a-9220-f7f5271a746f.mp4

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (x) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
this report is very confusing, and I doubt this is even a bug. I believe you meant that the daggers were not shooting in the same exact angle you were shooting. When commanding units, and shooting with them, they all shoot at the mouse, they don't all face the same direction as your unit.

**Comment by begginerr** [comment]
sorry man, but plx watch the video, you will understand what i mean

**Comment by begginerr** [comment]
also sorry for the confusion, it was really late when i posted it, i meant that some daggers were shooting straight, away from my finger, but others were shooting at the finger, sorry for the confusion

**Comment by Anuken** [comment]
I don't see daggers shooting 'not at the finger' in the video.

**Comment by begginerr** [comment]
i can tell its hard to see, but i am shooting at the battery, 2 daggers aren't
when i aim right, it dosent show.
when i aim up, it happens, but the inaccuracy of daggers obcures the daggers not shooting at the finger
i will send an edited video showing it clearer

**Comment by begginerr** [comment]
hopefully this works! :)
https://user-images.githubusercontent.com/87596406/126739257-18b4dd25-b822-49bc-90fc-2a7e49ca1c85.mp4

**Comment by begginerr** [comment]
here it is, hopefully it works :) 

https://user-images.githubusercontent.com/87596406/126739571-7efcff00-44b4-447c-a76a-cef3a9a756d7.mp4
