### ISSUE TITLE
Neutral structures are not usable by player

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#5606]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Linux

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

126.2

**Issue**: *Explain your issue in detail.*

Neutral structures on the map cannot be used, only dismantled

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Play campaign, try to use existing structures (it used to be possible and it was a nice feature!)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[sector-serpulo-213.msav.zip](https://github.com/Anuken/Mindustry/files/6836032/sector-serpulo-213.msav.zip)

I am not sure, hopefully, `~/.local/share/Mindustry/saves` save is good enough

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** - is it going to trash my campaign status? Or is it enough to backup `~/.local/share/Mindustry/saves`?
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** https://github.com/Anuken/Mindustry/issues?q=neutral+structures https://github.com/Anuken/Mindustry/issues?q=campaign+structures

**Comment by Dioo0** [comment]
#5441

**Comment by matkoniecz** [comment]
> Derelict (black team) things are not supposed to be interactable.

So it is not a bug? :(

I always though that it was not changing much but a nice touch...

**Comment by GamerMoment69** [comment]
Partially deconstruct the neutral buildings, the fully reconstruct them to put them on your team. Not a bug.
