### ISSUE TITLE
b o o m

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry#5610]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
bleeding edge 24167
**Issue**: *Explain your issue in detail.*
i was at impact 0078, saving up thor and sil for nucleus when.. *BOOM* everything died. i had beaten the sector too :(
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i dunno what i did
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
time control and testing utilities, i dont know how to get zip file

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
sorry man, i lost the sector so no save ;(

but i have evidence that i cleared it, here
![cleared](https://user-images.githubusercontent.com/87596406/126081302-15c9c397-6dcb-4878-807f-d8ee1ee9335a.jpg)
and here is evidence that i died there
![dead](https://user-images.githubusercontent.com/87596406/126081312-12b71250-142f-470d-8995-4b9ccfebd267.jpg)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (x) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Insufficient information provided. There's no way for me to reproduce this.

**Comment by begginerr** [comment]
sorry, but the sector just... DIED. i understand that you need the save, but i cant get it. i remember that i had thorium salvo defense with cryofluid, i will recreate the defense and where i was when death happened, sorry for the lack of info

**Comment by begginerr** [comment]
oh wait, i CAN get the save! here it is!
[death happened.zip](https://github.com/Anuken/Mindustry/files/6836910/death.happened.zip)

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/126082407-6bcdb8e9-8271-4986-a3d5-aaf631d10bf4.png)

There's nothing usable left in the save; nearly everything is destroyed due to the way sector invasions work.

**Comment by Bottinator22** [comment]
Impact 0078 is one of the sectors that can be invaded, which means the sector will have to survive a few more waves. You probably weren't there when the sector was invaded and was destroyed. (The thing that estimates how many waves the sector will survive, and if the sector will survive, isn't very accurate, and the best way to deal with an under attack sector is to actually be there)
