### ISSUE TITLE
Editor Undo/Redo Bug

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry#5616]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
128.1

**Issue**: *Explain your issue in detail.*
Undoing, then redoing placing a block in editor turns the block derelict.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Place any block in editor(eg. any core, plastanium wall, duo).
2. Undo.
3. Redo and look at the block's team.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None needed.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Editor bug, save not required.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
This isn't a crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The editor has countless bugs with undo/redo like this, and I'm not going to fix any of them until a potential editor rework.
