### ISSUE TITLE
A very not serious issue that can be closed and may or may not be a feeble attempt made by my lacking social skills

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#562]
Google play

"Don't look at the in-game changelog, it doesn't exist anymore."

~~RIP changelog~~

**Comment by Luxray5474** [comment]
Please provide a more detailed title. The contents of your post could have been completely covered in your title alone. Please edit it. Thank s in advance.

**Comment by Arkanic** [comment]
@Luxray5474 
.... it wasn't meant to be serious ...
This really shows the state of my social skills, doesn't it?
