### ISSUE TITLE
table.background(Tex.inventory) causes NoSuchFieldError

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#5622]
**Platform**: *Android*

**Build**: *128.1*

**Issue**: *Yet another case of 6.0 crashing in 7.0, but this time I have no idea what is wrong at all, what I am doing wrong, or how to fix. Wrong Deprecation or compiler issues?*

**Steps to reproduce**: *Install latest BetaMindy's github action, game crashes on startup.*
The code lines of the crash log stacktrace:
```java
parent.fill(table -> {
            table.name = "hardmodebar";
            table.left();
            table.table(t -> {
                t.background(Tex.inventory); //<<Line 32
                t.top();
                t.add("Invasion", Styles.techLabel).color(Pal2.portal).pad(4f);
                t.row();
```

**Link(s) to mod(s) used**: *sk7725/BetaMindy*

**Save file**: *crash on startup*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 128.1
OS: Linux xnull (aarch64)
Java Version: 0
19 Mods: betamindy:1.0
[#b59e72]Demo of Chaos Itself[], commandustry:0.5, dev-mode:2.3.2, diversetech:0.1.0, hackustry:4, largeunits:0.1, ldb:1.3.2, new-horizon:1.8.7.1 Fix, notepad:2.0.0, override-lib:1.0.1, rtfm:2.14.10, test-utils:0.14, time-control:0.2, uaw:0.4, ui-lib:2.16.6, unit-factory:2.4.2, aeromindustry:1, bundles:13, classicified:1.4

> NoSuchFieldError: 'No static field inventory of type Larc/scene/style/NinePatchDrawable; in class Lmindustry/gen/Tex; or its superclasses (declaration of 'mindustry.gen.Tex' appears in base.apk)'
HardmodeFragment.lambda$null$5$HardmodeFragment: 32
-$$Lambda$HardmodeFragment$NV6NlXenFiI2maVLlRkza6WjMe4.get: 4
Table.table: 264
HardmodeFragment.lambda$build$7$HardmodeFragment: 31
-$$Lambda$HardmodeFragment$qobycLahpAB-aXSXPcuKzmwp6DQ.get: 4
Group.fill: 241
Group.fill: 233
HardmodeFragment.build: 28
MindyUILoader.lambda$init$0$MindyUILoader: 19
-$$Lambda$MindyUILoader$EUI6BBjU75xgqkOBB7cRQhKTIks.run: 2
AndroidGraphics.onDrawFrame: 364
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are trying to reference `Tex.background` as a `NinePatchDrawable`, but it's a `Drawable` now.

**Comment by sk7725** [comment]
> You are trying to reference `Tex.background` as a `NinePatchDrawable`, but it's a `Drawable` now.

how do i fix it then?

**Comment by Anuken** [comment]
Reflection, or just don't add the background.
