### ISSUE TITLE
229 crash

### ISSUE THREAD

**Issue by SpectralSen** [Anuken/Mindustry#5623]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *Sector 229 keeps crashing after i failed to retake it. 

**Steps to reproduce**: * N/A.*

**Link(s) to mod(s) used**: **

**Save file**: *https://mega.nz/file/USgEVajb#NViloS3htqsDFVfXa4_FApNA4AirTu3sbrnawN-LmC8*

**(Crash) logs**: *https://mega.nz/file/NexEAQyL#GPi-QGSVkeWRrYK-B1WWL83A9fOR4Xw9t30Bmj5vdVE

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
