### ISSUE TITLE
(Junction)block

### ISSUE THREAD

**Issue by Awfulchunk** [Anuken/Mindustry#5624]
**Platform**: `Android 29`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
It's a problem with junction block,every time I exit and enter my game the junction block will start too divert other material into the same conveyor,example;have lead crossing over coal,I would save my game come back to find the coal being mixed with lead,and also the conveyors will sometimes switch direction..thanks for you 
the good work. awsome game love you all,keep up
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a valid issue.
