### ISSUE TITLE
Can't use drawBlock fields in GenericCrafters right

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5627]
**Platform**: *Android*

**Build**: *128.1.*

**Issue**: *yeah cool*
![Screenshot_20210720-235031](https://user-images.githubusercontent.com/61173114/126438258-64b65a07-f519-4991-acc8-fb482075f07a.png)
![Screenshot_20210720-234956](https://user-images.githubusercontent.com/61173114/126438268-3818cbf6-5c99-497e-befe-1fa1e0203b52.png)

**Steps to reproduce**: *Give any JSON GenericCrafter a DrawSmelter/DrawArcSmelter and try to change the drawer's fields.*

**Link(s) to mod(s) used**: *[unavailable for testing, was done on local files. Blame android 11 for me being unable to rip it out.]*

**Save file**: *Cannot provide because I cannot export the mod zip i am using for this - if I provided the save, it would remove the block on world load due to invalid size and fields.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Don't matter this time

**(Crash) logs**: *none.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> unavailable for testing, was done on local files

Why can't you include the *text* of the json you're using, at least? Copy-paste should still work, right?

> Give any JSON GenericCrafter a DrawSmelter/DrawArcSmelter and try to change the drawer's fields.

```
name: Test Block
requirements: [copper/2]
type: GenericCrafter
size: 3
drawer: {
	type: DrawArcSmelter
	flameColor: "ff00ff"
	midColor: "00ff00"
	particleRad: 30
}
```

![2021-07-21-07-39-39](https://user-images.githubusercontent.com/10100000/126483012-a8626d60-1636-4771-af07-7f2d6f910f42.gif)

![image](https://user-images.githubusercontent.com/10100000/126483138-2ba98114-4d99-4f59-abc8-4a13c9ffd404.png)

You are likely trying to set the fields of the wrong object, but since *you didn't include the JSON* I can't say for sure.

**Comment by BlueWolf3682** [comment]
So now the JSON for the drawer is contained by itself? No wonder nothing works, this isn't the case in 6.0.

**Comment by Anuken** [comment]
It was always a separate object; you just couldn't change its fields because the serializer didn't support it.

*Smelters* didn't use a drawer at all, they had their own fields - this was bad design, as having everything separate was the entire point of a `Drawer` in the first place.

**Comment by ChensingML** [comment]
![image](https://user-images.githubusercontent.com/56194613/183578630-fbc80f3e-9aec-41b1-ba6b-bcd33f8ec04c.png)
![image](https://user-images.githubusercontent.com/56194613/183578674-bd33543c-8ead-4eb5-a065-e018d81f018d.png)
![image](https://user-images.githubusercontent.com/56194613/183578974-579f1fb5-74b3-4bc8-8433-70f3f3c7cad3.png)

I tried, but it doesn't work.

**Comment by Anuken** [comment]
This issue is a year old, it's called DrawArcSmelt now.

**Comment by ChensingML** [comment]
![image](https://user-images.githubusercontent.com/56194613/184069577-f5fd01de-daf3-4001-af2b-5616e620e409.png)
![image](https://user-images.githubusercontent.com/56194613/184069208-e08891a8-090c-46b4-b22b-d472dd5ccafa.png)
I've changed DrawArcSmelter to DrawArcSmelt, but it still doesn't work.
(My version of game is 126.2, should I update?)

**Comment by RomanKridd** [comment]
Where do you get all these settings for drawer?
