### ISSUE TITLE
b o o m... reposted (with new info)

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry#5628]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android
i dont think i can tell you how much i hate to repost a bug, but i have new info and i dont want someone to go insane over losing a sector like i did
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
bleeding edge 21467
**Issue**: *Explain your issue in detail.*
i was saving up for nucleus when almost everything died, the only things that survived where some walls and 2 vaults i placed and the sector was cleared, i had to clear it again

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
there are only 3 things i can think of that could have caused it.
1. the overdrives i spammed to get more thorium
2. the 1 extreme and 1 eradication base next to it
3. the defense (it was cryofluid salvo)
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
testing utilities and time control
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[death happened.zip](https://github.com/Anuken/Mindustry/files/6857142/death.happened.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
That's the entire game files - Please send the specific sector save in the saves folder.

**Comment by Anuken** [comment]
I [already looked](https://github.com/Anuken/Mindustry/issues/5610#issuecomment-882117716) at your save file, and there was nothing usable in it. Unless you are able to *consistently* reproduce sectors being lost *with a clear, observed lack of any threat near the core at the time of death*, I can't do anything.

**Comment by Bottinator22** [comment]
This is an intended game mechanic. If your base happens to be next to an enemy base, it will be periodically invaded. The only way to stop this is to capture those zones.

**Comment by begginerr** [comment]
but look, it just died, it didnt have more waves, it just.. d i e d.
also anuken, sorry for the lack of info, but i guess i sorta helped??
at least i tried
