### ISSUE TITLE
Block status not showing

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry#5630]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
128.1

**Issue**: *Explain your issue in detail.*
Block status won't show when the setting is on

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just turn the setting then go in a game and place a block that would normally show the status.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None needed.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
An issue with graphics, not the game.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
this is not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> An issue with graphics, not the game.

And where are these graphics displayed? *In the game.*

>  THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.

Is this not clear enough? That requirement is there for a reason. I experience no such issue myself, and *there's no way for me to know if the problem was caused by a specific save*, since you have not attached one. It could very well be that you're just looking at blocks of a different team.

![image](https://user-images.githubusercontent.com/10100000/126556609-ef0933ad-886e-4f19-a2d2-1228900d51db.png)

**Comment by GamerMoment69** [comment]
at this rate i'm being dumb with bug reports...
