### ISSUE TITLE
Unable item unblocking

### ISSUE THREAD

**Issue by akairasu** [Anuken/Mindustry#5632]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: in Tech tree: Use of resources for searches without unblocking the item.

**Steps to reproduce**: Have attempted to search her during the game (in a map and not in the map of the world)

**Link(s) to mod(s) used**: `none`

**Save file**: The bug is produced in campaign mode, I don’t (or don’t know) send the file to it. Sorry.

**Crash report**: The game doesn't crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't understand what you're trying to say, but if what you mean is that *spending items towards research* doesn't immediately unlock the block, that's an intentional mechanic.
