### ISSUE TITLE
mega control.exe has stopped working

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry#5633]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
128.1
**Issue**: *Explain your issue in detail.*
i tried to control mega, but it turned weirdly and woudnt move. when i left it looked like the game thought i never controlled it in the first place, it would move extremely fast to go to the spot it would be as if i didnt control it

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i just controlled mega, thats it
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
time control and testing utilities, neither used when it happened

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[mega bug.zip](https://github.com/Anuken/Mindustry/files/6866589/mega.bug.zip)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. You linked your entire save folder, which is not usable.

**Comment by begginerr** [comment]
sorry, i didnt know you coudnt use it, i guess i tried tho

**Comment by begginerr** [comment]
i remember how to see it actually
1. go to tower defense in darkdustry server
2. try to control an unit
then you see the bug

**Comment by begginerr** [comment]
maybe its intended, but who knows

**Comment by begginerr** [comment]
oh k
