### ISSUE TITLE
Launch Pad Launching To Nothing

### ISSUE THREAD

**Issue by Migzzz831** [Anuken/Mindustry#5638]
**Platform**: *Android*

**Build**: 126.2

**Issue**: Well, i was launching silicon to Overgrowth using Launch pad, and then later on it got defeated, but the silicon/launch pad was still launching to overgrowth even tho it's gone

**Steps to reproduce**: 
1.Use Launch Pad
2.Direct The Launch Pad To A Sector
3.When That Sector Is Lost It's Still Launching Rather Than Stoping

**Link(s) to mod(s) used**: *None*

**Save file**: No Save File, only Campaign 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![Screenshot_2021-07-24-19-04-30-21_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/87899024/126866862-5d74be28-7ca9-4611-9cee-c6d1ca1a5939.png)
![Screenshot_2021-07-24-19-04-37-46_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/87899024/126866864-c4fecdc7-3caf-455c-811b-41f0bec3b73d.png)

**Comment by Anuken** [comment]
This isn't really a bug - launch pads *always* accept items, and there's nothing stopping them from launching to a lost sector - the items will get deleted/destroyed anyway. I can make it display as if it's launching into the sun when the destination has no base, but that has no effect on gameplay whatsoever.

**Comment by begginerr** [comment]
i remember i saw another launch pad bug, where launch pads dont launch anything, like i was launching plas to the map with vela boos and it never arrived until i went to stained mountains (where i was launching plas to vela map) and then it started launching plas to vela well
