### ISSUE TITLE
Question (not issue) about draug miner drone factory

### ISSUE THREAD

**Issue by chuhanuman** [Anuken/Mindustry#564]
How does the draug miner drone factory work? I gave it power and it says it built 2 out of 2 but nothing seems to be happening. No drones are coming out, no ore is either. This could be because I didnt place it on ore just near it. Also what is the ore output of the factory?

**Comment by Anuken** [comment]
The factory should produce 2 drones that automatically mine resources and place them into the closest core. Only copper and lead are mined. The factory itself does not output anything.

There is a bug where the drones don't do anything, but I haven't reproduced it yet (and nobody has reported specific steps to trigger it, as far as I'm aware).
