### ISSUE TITLE
Keyboard mode doesn't work on iPad

### ISSUE THREAD

**Issue by bruno-robert** [Anuken/Mindustry#5643]
**Platform**: iPadOS
iPad pro 3rd gen 12inch
iPadOS 14.6

**Build**: 126.3

**Issue**: When going to Menu > Settings > Game and checking the "Mouse+Keyboard Controls" option, the game changes to mouse and keyboard mode but the keyboard is unresponsive.
Dragging with the mouse

 results in objects being placed (so the setting does do something), but the keyboard does nothing.

**Steps to reproduce**: Open up a game, and turn on the setting by navigating to Menu > Settings > Game and checking the "Mouse+Keyboard Controls" option

**Link(s) to mod(s) used**: No Mods used.

**Save file**: [mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/6873356/mindustry-data-export.zip)

**(Crash) logs**: The game doesn't crash, I don't have any crash logs to post (please don't reap my soul)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by begginerr** [comment]
when you say 126.3, you mean 127, right?

**Comment by joshuaptfan** [comment]
[Quote from Anuke](https://github.com/Anuken/Mindustry/pull/4284#issuecomment-756899495):

> Mindustry's mobile mouse/keyboard support is basically dead. I don't play Mindustry on mobile, and I definitely don't test it with keyboards or mice. It's only functional because libGDX had some code to support it.

**Comment by oinkymoo** [comment]
> when you say 126.3, you mean 127, right?

some platforms got a 126.3, others stayed on 126.2

**Comment by Anuken** [comment]
Keyboard support was never implemented on iOS, and I have no adapters to even test it. The setting will be removed.

**Comment by begginerr** [comment]
> > when you say 126.3, you mean 127, right?
> 
> some platforms got a 126.3, others stayed on 126.2

thanks, i didnt know that!
