### ISSUE TITLE
Conduit bridge visual bug

### ISSUE THREAD

**Issue by Nils101** [Anuken/Mindustry#5646]
**Platform**: Android

**Build**: BE 21528

**Issue**: When a bride conduit is disabled with logic and you connect it with another bridge conduit, there is a weird visual glitch. 

**Steps to reproduce**:
-Place 2 conduit bridges
-Disable one of them with logic
-Connect disabled one to 2nd one.

**Save file**:
https://mega.nz/file/aexlxApS#TvYmQ_8y-VI4NvzQSjoQKqAWePwJPFIERS6HSY1JncA
(also contains screenshot)

no crash log and no mods used.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment]
That is what happens when the extending bridge doesn't extend

**Comment by Anuken** [comment]
It's not extended.

**Comment by Nils101** [comment]
If I may ask-
Why is there such a drastic difference between conveyor bridge and conduit bridge in this case?
The first one acts smooth and the conduit looks super weird
