### ISSUE TITLE
I can't go into multiplayer servers anymore nor

### ISSUE THREAD

**Issue by Nopeymopey** [Anuken/Mindustry#5649]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[LottieVixen/1-tile-drills:0.0.1, Tom Petrou/[#25f12f]vanilla-extended[]:1.7, Tayros/theangelurd/additional-content:0.4.0, DylanC/advanced-warfare:0.1, [royal]sk7725[]/betamindy:1.0
[#b59e72]Demo of Chaos Itself[], DeltaNedas/boost-control:2.2.0, The Slaylord/crazy-militaries:1.1, z0mbiesrock/diamond-ore:[#9cb6f4]2.6.0[], LokeYourC3PH/extremely-efficient-structures:1.5, The Slaylord/goldmod:2.0 alpha b14, Darknes Tech Mods inc./gun-mod:2.3.2.1, [#386dff]Eschatologue[]/heavy-armaments:2.6, Zen/heavymachinery:1.0, xJamix/infiniteprogram:1.2.2 alpha, SMIPE444/infinity-cheat:2.1.444, Nuclear_Bomb/inverse:1.0, DeltaNedas/item-grabber:1.0.2, gamerredx/killer-drill:3, z0mbiesrock/larger-cores:1.0, Developer:
    Fresh791
    
    
Contributers:
    Boopas172 (Balance Playtesting / Ideas)
    
    Rem-Armiger (Balance Playtesting / Ideas / Spike and Strike Platform Strahl Sprites / HIVE Sprites)
    
    Hairy Nugget (Spanish Translations)
    
    DeCell (Balance Playtesting)

    coco (Balance Playtesting / French Translations)

    migmag789 (French Translations)
/me:1.08, IvyX/more-defences-ivyx:1.0, younggam/multi-lib:1.0.7, amione#0663/opore-mod:69, Sh1penfire and pankiwi/pixelcraft:0.9.85, Slava0135/revision:12.1, RTOmega/sandboxmode:1, aden8r/saphatax:0.1.5 test build 1/3, pixecoz/schematics-pack:8, CyberneticSquid/self-destruct:1.0, [#D4F0FC]0verchargedBattery/synth_tech:1.1.6.5, Deletron247/technology:1.3, sk7725/time-control:0.2, ColdAnkles/trade-terminals:2.0, DeltaNedas/ui-lib:2.16.6, Scolar Iron Fist/unit-cap-modifier:1, NeutrO_/unit-turrets:0.5, Snake/units-mod:1.0, Drullkus/unnerf_core_units:1.1, genNAowl/upgraded-factories:2.0.1, HolyHades/vanilla-enhanced:2.1, MountLava/volcanicmod:6.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**.                                                 I can't into multiplayer servers anymore, I have disabled all mods that aren't multiplayer compatible and disabled those mods too, I restarted the game, redo what I said before, and restart my device (phone), and even erased all data, but now it got rid of all my servers permanently

**Comment by Hyrotrioskjan** [comment]
disable the mods first. multiplayer servers wont work if you have mods that add new content such as blocks, units, and turrets.

**Comment by Nopeymopey** [comment]
I managed to fix it
