### ISSUE TITLE
Derelict air units still attack

### ISSUE THREAD

**Issue by GamerMoment69** [Anuken/Mindustry#5650]
**Platform**: *Android/iOS/Mac/Windows/Linux*
WIndows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
128.1
**Issue**: *Explain your issue in detail.*
Derelict air units still attack.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
In any way possible, spawn derelict air units, I used a derelict payload source(fixed in bleeding edge or build>=128.2).
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None needed
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Screenshot and save:
<img width="159" alt="Bug2" src="https://user-images.githubusercontent.com/87551951/126977505-770cc000-79d6-45e0-bef9-fa404f1b7986.png">
[bug2.zip](https://github.com/Anuken/Mindustry/files/6877570/bug2.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
do I have to even tell you at this point
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There's no way to spawn derelict units in vanilla anymore.
