### ISSUE TITLE
Appearing invisible when playing multiplayer

### ISSUE THREAD

**Issue by gamereapere** [Anuken/Mindustry#5658]
When I play on steam with my friends either them or I appear invisible and not able to do anything

**Comment by Anuken** [comment]
Cannot reproduce + no template.

**Comment by Bottinator22** [comment]
should probably start using forms for bug reports too

**Comment by Anuken** [comment]
I started working on one, but it wouldn't help in this case (mobile), where templates & forms can be bypassed.

**Comment by itcannotbe** [comment]
> I started working on one, but it wouldn't help in this case (mobile), where templates & forms can be bypassed.

You can't bypass it, unless you use the github app which strangely sucks.

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/127364092-fa4d78ce-7680-49b2-bd05-32980517ee5d.png)

![image](https://user-images.githubusercontent.com/10100000/127364147-7941ee68-c72e-4d53-b636-0a80316760ce.png)

It's disabled. There's no way to open a blank issue on desktop.
