### ISSUE TITLE
Incorrect display of water visual bug 

### ISSUE THREAD

**Issue by Zelaux** [Anuken/Mindustry#5662]
**Platform**: Windows

**Build**: 128.8

**Issue**: Near StaticWall under which there is no water animated water is displayed with black waves
![image](https://user-images.githubusercontent.com/58040045/127366751-7dc72289-c855-4270-9be7-a01152a6fac1.png)

**Steps to reproduce**: Start saving the map and fly to coordinates (173; 150).

**Link(s) to mod(s) used**: none

**Save file**:
[BUG_MAP.zip](https://github.com/Anuken/Mindustry/files/6895322/BUG_MAP.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Zelaux** [comment]
no mods were used when saving the map

**Comment by Anuken** [comment]
This bug is so specific to your map and so hard to notice that I don't care.
