### ISSUE TITLE
"Borderless Window" setting only makes game fullscreen

### ISSUE THREAD

**Issue by joshuaptfan** [Anuken/Mindustry#5672]
**Platform**: Windows

**Build**: 129.1

**Issue**: In graphics settings, both the "Fullscreen" and "Borderless Window" settings make the game fullscreen, when enabled individually or together. "Borderless Window" works correctly in build 126.3.

**Steps to reproduce**: Disable "Fullscreen" and enable "Borderless Window". Press the Windows key and observe that the screen blinks which indicates that Mindustry was actually fullscreen.

**Link(s) to mod(s) used**: None

**Save file**: Irrelevant

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a change of behavior in SDL, possibly a bug. I maximize the window after enabling borderless fullscreen, but apparently that just enables fullscreen now.

Without the maximization, it just looks like this:

![image](https://user-images.githubusercontent.com/10100000/127681133-e82b985a-6cbc-468f-97a3-3182da47dfda.png)

**Comment by Anuken** [comment]
Appears to fix #4360, #2110 as well.

**Comment by joshuaptfan** [comment]
Testing this build, it results in a different bug. "Borderless Window" no longer expands the window to cover the taskbar. (The game window used to cover the whole screen like "borderless fullscreen" in other games.)

![Borderless bug](https://user-images.githubusercontent.com/15149002/127691778-61373434-3272-4654-a9e2-f7462e723387.png)

**Comment by Anuken** [comment]
> "Borderless Window" no longer expands the window to cover the taskbar. 

It was not supposed to do that, and never did in my version. Borderless windowed is not supposed to be borderless *fullscreen*.

**Comment by Anuken** [comment]
If borderless *fullscreen* is what people need, then the setting should be named accordingly on Windows. On Linux (and possibly Mac), that setting does not (cannot?) make the window fullscreen.
