### ISSUE TITLE
kaspersky game ban

### ISSUE THREAD

**Issue by Domaman202** [Anuken/Mindustry#5673]
**Platform**: Windows

**Build**: 7.0 Build 129.1 - Pre-Alpha

**Issue**: this version of the game is blocked by antivirus and recognized as a trojan (((

**Comment by Anuken** [comment]
It's wrong.

**Comment by Domaman202** [comment]
and what to do?

**Comment by Anuken** [comment]
Unlock it, or use a better antivirus.
