### ISSUE TITLE
GZ captured at beginning

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry#5678]
**Platform**: *Windows*

**Build**: Custom build, FPSUncapped based off of 129. Issue still exists in official release 129.1

**Issue**: Resetting campaign saves does not reset sector captured

**Steps to reproduce**: Capture GZ. Reset campaign saves. (I also reset research.) Then launch back to GZ. The sector should be captured

**Link(s) to mod(s) used**: I was using [Betamindy](https://github.com/sk7725/BetaMindy), [Exogenesis](https://github.com/AureusStratus/ExoGenesis) and several js mods, but I doubt they would affect something like this

**Save file**: [Here it is](https://github.com/Anuken/Mindustry/files/6911678/GroundZeroAlreadyCaptured.zip)

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce, clearing saves clears all GZ data.

> Capture GZ. Reset campaign saves. 

If you reset campaign saves *while sitting in the ground zero save*, you will still save the game once you quit ground zero.
