### ISSUE TITLE
spontaneous disconnects in multiplayer at high unit counts

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#5679]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
129.1

**Issue**: *Explain your issue in detail.*
when playing crawler arena at .pl *and there's a lot (1000+) of units* i (and apparently not only i) periodically get disconnected with an `Unknown network error` saying either `Malformed input at <number>` or `Incorrect number of bytes (<number> remaining) used to deserialize object: mindustry.gen.EntitySnapshotCallPacket@<number>`, i think this is likely related to internet connection problems but still making this issue in case it's possible to prevent this

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
play the crawler arena gamemode on .pl on late (23+) waves

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[crsave.zip](https://github.com/Anuken/Mindustry/files/6911754/crsave.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by begginerr** [comment]
i remember seeing this in crawler arena too, after wave 23 one player kept trying to join and kept disconecting, we (legit) kicked him and he kept joining... somehow.

**Comment by Anuken** [comment]
There's not much I can do with this information as-is.
- Hosting a server with 10k flares and 4 local connected clients does not lead to any network errors, which makes it unlikely to be a thread-related bug.
- I have not seen this reported for any other gamemodes.
- Even if I observe this happening on a server, there's no way for me to tell what actually caused it.
- It's possible the crawler arena plugin (*or another installed plugin*) may be causing issues by running game functions in another thread.

**Comment by Bottinator22** [comment]
Issues like this seem to actually happen with amounts of 20k-30k crawler-branch units
With enough units, things start happening, such as the obvious 1 FPS and extremely high memory consumption, but also people being trapped in a black void, and anyone trying to join the server being unable to do so due to the game being unable to load world data

**Comment by Somka000** [comment]
Dexapnow broke server...

**Comment by SukkaW** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/40715044/160242950-6e18fec4-090d-4bd7-924a-c2d2cd1b1fdc.png">

The issue is still there...

**Comment by Anuken** [comment]
No netcode has changed on my end, so that's not surprising. As I wrote above, there's nothing I can do about it.
