### ISSUE TITLE
Cannot use config to change the command of the unit command center

### ISSUE THREAD

**Issue by ROKuser** [Anuken/Mindustry#5681]
**Platform**: *Android/iOS/Mac/Windows/Linux*

windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

129.1

**Issue**: *Explain your issue in detail.*

I wanted to create logic to change the command of the command center.

The status of the command center was detected, but it was not possible to change commands using config.

All other blocks are possible, but only command center is impossible.

![report2](https://user-images.githubusercontent.com/77824588/127762044-879aa6b6-dcf0-40af-b92b-c8837a18484d.PNG)
![report1](https://user-images.githubusercontent.com/77824588/127762045-5a6a0d8d-fb2c-4fcd-8b24-cbfc8a186e24.PNG)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

maybe always in build 129.1

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

It is not affected by mod.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
`@rally` is not a valid config for the command center, the correct name is `@commandRally`.
