### ISSUE TITLE
Destroyed buildings appear again

### ISSUE THREAD

**Issue by pphotography** [Anuken/Mindustry#5682]
**Platform**: Xubuntu 18.04 with XFCE desktop

**Build**: pre-alpha build 129.1

**Issue**: When I enter a turret to shoot manually and a previously destroyed building is near to it the destroyed building partially appears again with low hitpoints.

**Steps to reproduce**: 
Build something (a wall for example) in range of enemy turrets
![20210801_09-28-32_screenshot](https://user-images.githubusercontent.com/49001045/127766581-2689a915-cdd5-4929-bf02-8ad888800454.png)

Let enemy turrets destroy that building
![20210801_09-28-36_screenshot](https://user-images.githubusercontent.com/49001045/127766601-76e218ab-6077-4fc9-b000-f56daf960a8e.png)

Enter turret near to that area
![20210801_09-28-42_screenshot](https://user-images.githubusercontent.com/49001045/127766621-6d7d68f3-245d-49a7-8fc4-378e87c7daca.png)

Building appears again with low hp
![20210801_09-28-43_screenshot](https://user-images.githubusercontent.com/49001045/127766629-d62dc527-007b-4c21-a0f9-49518cd4fb07.png)

**Link(s) to mod(s) used**: none

**Save file**: 
[Savegame.zip](https://github.com/Anuken/Mindustry/files/6912449/Savegame.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
might be polys rebuilding. do u have any of those?

**Comment by pphotography** [comment]
No polys in the game

**Comment by Anuken** [comment]
Your save does not have the setup shown intact anymore. When I follow the instructions, no buildings "reappear".
