### ISSUE TITLE
Steam Workshop not working

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry#5684]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux (Kubuntu 20.04 LTS)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam 129.1

**Issue**: *Explain your issue in detail.*
Steam Workshop is not working. I sub to an item on the Workshop, Steam doesn't even try to download it. In-game, the Workshop option is missing, and I cannot see workshop schematics or maps.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I don't quite know why this is happening. It might be a Steam issue, but I don't know, since Steam Workshop works just fine for other games.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
I don't think these are related, but the only mod I have enabled is Logic Debugger.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
This is visible immediately in the title screen, which I cannot save.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
This isn't a crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Steam is not initialized on your client.

There are several potential reasons for this:
- You are in offline mode.
- The Steam native libraries can't be loaded.
- There is an error loading workshop content.

I don't know which one is happening, and as you have not attached any logs there's no way for me to solve the problem. For more information, check your game's local data folder for `steam-error-log` / `saves/last_log.txt` files, or attach `.local/share/Mindustry/last_log.txt`.

**Comment by Bottinator22** [comment]
[last_log.txt](https://github.com/Anuken/Mindustry/files/6913329/last_log.txt)
This is the only log file I could find (besides /saves/last_log.txt, which is an old log that won't help)

**Comment by Anuken** [comment]
There is no Steam error in that file - did you check game's **steam local files** for `steam-error-log`s?

**Comment by Bottinator22** [comment]
The game is labeled as "steam" in the menu, and the game's local files in SteamApps does not contain steam-error-log

**Comment by Bottinator22** [comment]
I have also tried clearing Steam's download cache and deleting all installed workshop items

**Comment by Anuken** [comment]
Run Steam through the command line and check the log that appears when Mindustry is launched.

**Comment by Bottinator22** [comment]
I have also tried deleting the Steam APIs and then validating to reinstall them, going into offline mode and back into online mode

**Comment by Bottinator22** [comment]
The log that appears shows "Running in offline mode" as the second thing it logs, after initializing Discord Rich Presence

**Comment by Anuken** [comment]
Switch to the internal-testing beta branch on Steam, and try running through the command line again, once the update is downloaded.

**Comment by Bottinator22** [comment]
I am already running the publicbeta version of Steam btw

**Comment by Anuken** [comment]
No, that's different from the internal-testing branch.

**Comment by Bottinator22** [comment]
How do I switch to internal-testing branch?

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/127784762-7e5d3844-bfea-46b3-b681-71c925a3c70a.png)

A Steam restart may be required to see this.

**Comment by Bottinator22** [comment]
alright

**Comment by Bottinator22** [comment]
![Screenshot_20210801_134749](https://user-images.githubusercontent.com/59987380/127784932-1eb72b91-34e7-48b9-b321-65594c4a1ff4.png)
This is the error that pops up.

**Comment by Bottinator22** [comment]
[steam-error-log-15381488242456.txt](https://github.com/Anuken/Mindustry/files/6913399/steam-error-log-15381488242456.txt)
It also made this log

**Comment by Anuken** [comment]
Updated the internal-testing branch again with fixes to that crash, update it again and let me know if works. This may require a Steam restart to fetch the update.

If this does work, the fix will be released in the v7 branch later.

**Comment by Bottinator22** [comment]
It works. The workshop option appears again.

**Comment by Bottinator22** [comment]
Although, while the workshop option appears again, maps and schematics don't work. I think this might be a Steam problem though, since Steam refuses to try to download anything.

**Comment by Anuken** [comment]
The error was caused by Steam failing to initialize in the game because certain workshop content was "invalid", which, according to the documentation, means it was either not installed or had no content.

**Comment by Bottinator22** [comment]
Steam seems to be broken then
