### ISSUE TITLE
Apple AppStore preview photos 

### ISSUE THREAD

**Issue by yay998** [Anuken/Mindustry#5686]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: Photos on apple AppStore are wrong, are not v6 mindustry 

**Steps to reproduce**: *search mindustry on AppStore 

**Link(s) to mod(s) used**: `none`

**Save file**: not ingame

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by begginerr** [comment]
same thing on android, its v5 there too

**Comment by Anuken** [comment]
This is not a Mindustry bug.
