### ISSUE TITLE
hard to explain (check the detailed bug description)

### ISSUE THREAD

**Issue by begginerr** [Anuken/Mindustry#5691]
**Platform**: *Android/iOS/Mac/Windows/Linux*
android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
129.1
**Issue**: *Explain your issue in detail.*

bassicaly, if you click on the impact (to see how much power its making,etc.) and quickly switch to an enemy team and tap it again, the game thinks you are on the team (ex: if the impact was made by sharded and you are crux, you still see the info),
 then if you destroy it, let polies immediately rebuild (with sandbox or with reborn mindustry anarchy server) and switch back, it thinks you are not its team, even if you are. here is a video if its too confusing

https://user-images.githubusercontent.com/87596406/128063799-6bb50551-79c3-4e1f-99ea-a9486dbc792e.mp4

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i sorta already explained how, but see the video if you dont understand

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
testing utilities, only to switch teams
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

i dont think you need it, but here it is anyway
[save.zip](https://github.com/Anuken/Mindustry/files/6926192/save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> and quickly switch to an enemy team

Vanilla Mindustry does not support switching to other teams in the same game.

**Comment by begginerr** [comment]
oh, well with testing utilities you can switch to enemy teams in sandbox
