### ISSUE TITLE
Sector sprite icon glitch in attacked sector

### ISSUE THREAD

**Issue by JrTRinny** [Anuken/Mindustry#5695]
**Platform**: `Windows x64`

**Build**:  `BE 21598`

**Issue**: *Explain your issue in detail.*
when you set any attacked sector's icon to an in-game sprite icon, the icon will be shown in menu as "blank" icon, and we can't click the blank icon to change it back to normal unless changing the icon to a UI icon (not in-game sprite)
screenshots shown below

![icon](https://user-images.githubusercontent.com/85090668/128152898-ee5652b8-8515-43f8-8a49-0c9883a8768b.png)
change any attacked sector's icon to an in-game sprite icon (in this case, Memory Bank)

![bug](https://user-images.githubusercontent.com/85090668/128153076-cd7df9eb-d698-40d8-a710-32e6456ab24d.png)
the icon will be shown as "blank" icon, and we can't click the blank icon to remove the icon

![fixing](https://user-images.githubusercontent.com/85090668/128153234-26b26568-7d40-41de-969a-64445a44af88.png)
change the icon to not in-game sprite icon (in this case, Liquid Category icon)

![fixed](https://user-images.githubusercontent.com/85090668/128153334-7b73aa3b-1904-4ad6-9ed9-fd250da89d83.png)
back to normal.

### Note: don't mind the white bars and screen glitch, I don't know what and why it glitched like this, maybe it's because I'm using fullscreen? idk.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Select any attack sector, set the icon to any in-game sprite, like Foreshadow, click the icon menu again, see the bug

**Link(s) to mod(s) used**: No mod used
**Save file**: unnecessary.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: null

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Engaming-dev** [comment]
I cant reproduce the problem...

**Comment by Engaming-dev** [comment]
I wasnt able to reproduce this, it doesnt seem like a problem with the game

**Comment by Engaming-dev** [comment]
**So:**
This does happen.
**But** i do think that this is intentional and helpful, since this could help players who launch an attack not forget that they did so, especially when they dont play for some time. **This could be the case.**

**Comment by JrTRinny** [comment]
I mean I know that the icon not showing is intentional, the bug I'm talking is about changing icons, it glitches, even in captured sector (see update comment)
