### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IAmFeder** [Anuken/Mindustry#5700]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Game audio and music stopped reproducing after starting the game for a second time*

**Steps to reproduce**: *I started the game and while playing i noticed the audio wasn't reproducing even when it was at 100% on both the game and the device. It happened after i disconnected my Bluetooth headphones*

**Link(s) to mod(s) used**: `[z0mbiesrock/diamond-ore:[#9cb6f4]2.6.0[], Slava0135/revision:12.2]`

**Save file**: *It happens on both in game and home screen*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by IIINSTINCT** [comment]
As from my experience this sound problems on android are already fixed on the pre alpha v7 branch well aleast it doesn't happen to me anymore on v7 pre alpha

**Comment by Anuken** [comment]
> It happened after i disconnected my Bluetooth headphones

This is most likely fixed, use the alpha.
