### ISSUE TITLE
Enemies in sector 224 not spawning

### ISSUE THREAD

**Issue by Sch1st** [Anuken/Mindustry#5701]
**Platform**: Android

**Build**: 126.2

**Issue**: Enemies do not spawn in sector 224 until wave 12, wave 13 spawned a flare

**Steps to reproduce**: Launch in sector 224, wait or skip waves.

**Link(s) to mod(s) used**: None

**Save file**: 
[Sector224notspawning.zip](https://github.com/Anuken/Mindustry/files/6943305/Sector224notspawning.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This doesn't happen in v7.
