### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by FranLamark** [Anuken/Mindustry#5713]
**Platform**: *Android*

**Build**: *release build 126.2.*

**Issue**: *I was clearing certain attack zones until i reached "5". When i launched into it, and then changed zone for go and export to that one, somehow the zone shown me like if i didnt launch, and the side one somehow it lost the resources when launched, like if i've got stolen. This happened on an instant and i had 3 minutes for build myself up... "5" is an pentagonal zone btw. This happened on campaign so idk where's the save or how to send you all the progress i have*

**Steps to reproduce**: *Like stated above. Launched and changed to certain zones classified as export ones. Tried to export from them to "5" where i was, but couldn't anymore like if i didn't launch when i did.*

**Link(s) to mod(s) used**: *No mods used.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* (No crash report)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save.
