### ISSUE TITLE
You cannot actually export a campaign save on mobile

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5714]
**Platform**: *Android/iOS*

**Build**: *129.2.*

**Issue**: *You cannot export a specific campaign sector save on mobile without a third party app. The button does not exist in the menu.*

**Steps to reproduce**: 
*Go to campaign sector.
Check menu.*
![Screenshot_20210807-112142](https://user-images.githubusercontent.com/61173114/128608711-cd8e6ce7-5d4a-49dc-a249-3c94822840ed.png)

**Link(s) to mod(s) used**: *unrelated.*

**Save file**: *I can't export it :)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> You cannot export a specific campaign sector save

...and you're not supposed to, the campaign doesn't operate on a "slot" system, and imported saves wouldn't function properly anyway. I don't understand why you would expect this feature to be here.

**Comment by BlueWolf3682** [comment]
1. *You have mentioned before you need saves from campaign bugs to reproduce them easily.*
2. I can say this right now - the save still can be imported, as I just successfully did via renaming it.
![Screenshot_20210807-113939](https://user-images.githubusercontent.com/61173114/128609293-9347bd7e-11ab-4d72-b966-4990b4732b87.png)

**Comment by Anuken** [comment]
> You have mentioned before you need saves from campaign bugs to reproduce them easily.

For the campaign, I need *all* their campaign data, not individual saves, because individual saves don't contain enough information.

> the save still can be imported,

...as an editor map. If someone else tried to import that *as a save*, they (1) wouldn't see the save in their list of *slots* and (2) would not get any of the associated campaign metadata, like launch destination, **capture status**, waves survived, etc. This is clearly not "functioning properly".
