### ISSUE TITLE
Gradle ZipFile error

### ISSUE THREAD

**Issue by Se-Lyan** [Anuken/Mindustry#5721]
**Platform**: *Windows 10 Android Studio*

**Build**: *Not a game problem.*

**Issue**: when i compiled it on Android Studio, i received the following error : 

**Unable to find method ''void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)''
'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'**

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

a another android studio project does not give this error

**Steps to reproduce**: *i don't know exactly but you have to initialize the project and compile it, and i got the error*

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't fix this. Don't use Android Studio.

**Comment by Se-Lyan** [comment]
why ?

**Comment by Anuken** [comment]
Because it clearly doesn't work.

**Comment by Se-Lyan** [comment]
Its android studio or Mindustry project ? (I think its your project because its its not based on android studio, so a lots of things its not compatible with Android studio)

**Comment by SomeTroglodyte** [comment]
FWIW, I've seen the same, and in a seemingly arbitrary manner (a windoze AS balked, the same AS level and same branch on Linux was fine). For me, looking at the sync log, I found it was trying to use SDK tools 30.0.2 while I had prepared the box to use 31. Manually downloading the 30.0.2 tools and doing the usual Invalidate Cache/restart fixed the issue. Btw - the linux box was prepped with tools 31 only, too, and had no issue. So - go Linux! At least for AS in a VM, could save headaches. Regarding JDK hell, too.

And - definitely nothing to do with Mindustry specifically.

**Comment by yairm210** [comment]
I can confirm - this can be solved by going to Android SDK settings (double-shift-click, 'android sdk') > click 'SDK tools' > click 'show package details' on the bottom right - select 30.0.2

**Comment by ericytsang** [comment]
I am not sure which Android SDK I downloaded to make my project work....

but seems like need to download the one that the project requires as specified in your `build.gradle` file as per SO post https://stackoverflow.com/a/71997907/2898715:

> For example, if your project has `compileSdkVersion` 31 value, then download `Android SDK 31` and `build tools 31.0.0`. In `Tools/SDK Manager/Show Package Details` you can find appropriate versions for your case.
