### ISSUE TITLE
Je n'arrive plus a me connecter au server , je vous demande de l'aide -matypo

### ISSUE THREAD

**Issue by Matypo** [Anuken/Mindustry#5733]
**Platform**: `Android 23`

**Build**: `pre-alpha build 129.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The issue tracker is not the place to ask for help.

**Comment by begginerr** [comment]
he IS french and this IS english, maybe he just dosent understand how this works

**Comment by begginerr** [comment]
but because he gave 0 info, well... yeah
