### ISSUE TITLE
Duplicated rotateMove in DesktopInput.updateMovement(Unit)

### ISSUE THREAD

**Issue by Zelaux** [Anuken/Mindustry#5736]
first use is in ```unit.rotateMove``` method
![image](https://user-images.githubusercontent.com/58040045/128948493-d65ad46a-2f5c-4b54-9bdc-2d1e4168239d.png)

and the second right after it but already in ```DesktopInput```
![image](https://user-images.githubusercontent.com/58040045/128948470-4cce26f1-8a8a-4f62-9716-e933593b953f.png)

**Comment by Anuken** [comment]
This is not a bug.
