### ISSUE TITLE
Cant Load Campaign Sectors In Android 4.4

### ISSUE THREAD

**Issue by ben0753** [Anuken/Mindustry#5737]
**Platform**: *Android*

**Build**: *6.0 Build 126.2.*

**Issue**: *Cant Load Campaign Sectors In Android 4.4 Stucks in Loading... Page.*

**Steps to reproduce**: *To Launch To A New Sector*

**Link(s) to mod(s) used**: *No Mod Used
[Ben Latest Data.zip](https://github.com/Anuken/Mindustry/files/6966038/Ben.Latest.Data.zip)
.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X
[Ben Latest Data.zip](https://github.com/Anuken/Mindustry/files/6966046/Ben.Latest.Data.zip)
] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce.

**Comment by ben0753** [comment]
I mean Solve the issue of campaign sectors not loading getting stuck on the same loading screen

**Comment by Anuken** [comment]
Please explain how I should do that when it loads correctly on every device I have, and for every person that I have ever talked to.

**Comment by begginerr** [comment]
it IS android 4.4, maybe code error?

**Comment by begginerr** [comment]
but unless somehow we get a 4.4 android device, anuken cant fix it. sorry man.
