### ISSUE TITLE
muzzle flash?

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#574]
yeh or neh?

(maybe only on smaller guns)

**Comment by Anuken** [comment]
But there already is muzzle flash for nearly all guns.

**Comment by Arkanic** [comment]
@Anuken like an actual f l a s h rather than smoke?

**Comment by Anuken** [comment]
Also, didn't you make a issue specifically for suggestions like this..?

**Comment by Arkanic** [comment]
@anuken this was more of an opinion thing

**Comment by Arkanic** [comment]
but yeah

sorry

**Comment by Anuken** [comment]
And yes, there is an actual, angular flash on most guns.

**Comment by Arkanic** [comment]
@Anuken okie
