### ISSUE TITLE
Launch pad ui glitch 129.2

### ISSUE THREAD

**Issue by Ohloan** [Anuken/Mindustry#5740]
I went onto extraction outpost (havent completed it yet) and i saw that the launch pads were aiming for the placed i launched my core to extraction outpost from
(the image below is just the launchpads because i couldnt get a picture of the place it was launching to)

![image](https://user-images.githubusercontent.com/88750219/129037595-b4cf65ed-814a-4bda-a5b9-ee816856eb8d.png)
I cannot tell if this is a glitch or intended

Conditions i was in = 
Campaign 129.2 Extraction Outpost

**Comment by Anuken** [comment]
Template.

**Comment by Ohloan** [comment]
> Template.

what?

**Comment by Anuken** [comment]
You did not follow the mandatory issue template. If you are using the Github mobile app for issues, do not, it is broken.

**Comment by Ohloan** [comment]
ohh
okay should i edit this post or make anothe

**Comment by Ohloan** [comment]
oh and it wasnt modded
just normal campaign

**Comment by Anuken** [comment]
> it will show that the launch pads on the enemy team are launching items to your other sector you just launched your core from

How can it show where *the launch pads on the enemy team* are launching? There is no such indicator for individual launch pads, and I see no such indicator in your screenshot. You can see a launch curve on the map for *your team* only.

**Comment by oinkymoo** [comment]
if i had to guess you are seeing the vulnerability indicator arc

**Comment by Anuken** [comment]
I later figured out that it was the sector name that you see when you hover over a launch pad in the bottom right, which shouldn't have been displayed for other teams.
