### ISSUE TITLE
Sounds in game are getting wierd

### ISSUE THREAD

**Issue by Bugowskii** [Anuken/Mindustry#5742]
**Platform**: Windows

**Build**:  129.2

**Issue**:  sometimes sounds from game are getting vomuled down like in menu

**Steps to reproduce**: Entering to the campaing then leaving, then going into custom game and then getting back to  campaing

**Save file**: 
[Data.zip](https://github.com/Anuken/Mindustry/files/6970061/Data.zip)
. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bugowskii** [comment]
Check out this https://youtu.be/QRhvxt1LdRg

**Comment by LeoSko** [comment]
Just a note, this issue is also present in 126.2 build (steps are unknown, though).

**Comment by Anuken** [comment]
> Check out this

It looks like this only happens when you launch to a new map and exit *immediately*. Starting on a campaign map is not necessary.
