### ISSUE TITLE
Redundant Pump/Conduit Placement Possible on the Edge of Space Tiles

### ISSUE THREAD

**Issue by 50275** [Anuken/Mindustry#5746]
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Pre-Alpha build 129.2 

**Issue**: *Explain your issue in detail.* I can place pumps and conduits on the edge of the water which generally should not be possible. (Additionally, phase bridge/conduit exits show idle status no matter what.)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* Accidental conduit placement in a sandbox map on the edge of space tiles. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* None.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.* 
[redundant.zip](https://github.com/Anuken/Mindustry/files/6972034/redundant.zip) 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* Game works fine.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** Unfortunately, I am not using the latest BE edition. This was on Pre-Alpha 129.2. 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Not a bug - conduits and pumps float on the edges of deep liquid tiles.
The phase ends don't require power or any other input, so idle makes sense.
