### ISSUE TITLE
Cyclone heatmap doesn't show up if a cyclone fires

### ISSUE THREAD

**Issue by Xaphironius** [Anuken/Mindustry#5747]
**Platform**: Android

**Build**: 21654

**Issue**: Cyclone heatmap doesn't show up when a cyclone fires

**Steps to reproduce**: 
1.Play a custom game.
2. Build a cyclone.
3. Control and fire it.

**Link(s) to mod(s) used:**
DeltaNedas/ui-lib:
https://github.com/DeltaNedas/ui-lib

DeltaNedas/dev-mode:
https://github.com/DeltaNedas/dev-mode

**Save file**: https://drive.google.com/file/d/1rCUqpJRRP8zSt8skh5I5yIY6TeyLUpvO/view?usp=sharing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Abilene/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cyclone doesn't *have* a heat sprite. Not all turrets do.

**Comment by begginerr** [comment]
true, scatter, tsunami and wave etc dont have heat sprite
