### ISSUE TITLE
Spawning in any team except sharded results in an instant gameover

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry#5749]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android (Probably happens in all platforms)
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
21655
**Issue**: *Explain your issue in detail.*
Whenever i try to enter a map with a different player team, it results in an instant gameover.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Open up Mindustry BE 21655
2. Go to a custom game, then change your default player team to any team(except Sharded)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None.
**Save file**:
Also none, as this happens everywhere.
**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No other team has a core, what did you expect? Changing the player team doesn't change the map.
