### ISSUE TITLE
[b84] "Tech tree" is "Core database" in Multiplayer Mode.

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#575]
The *Tech Tree* button is called *Core Database* in multiplayer mode. 

*On a local game*

![On a local game](https://user-images.githubusercontent.com/30189017/62585309-38d32180-b886-11e9-9dd4-e2c6413da4e8.PNG)

*On 9001*

![On 9001](https://user-images.githubusercontent.com/30189017/62585353-661fcf80-b886-11e9-84db-de5ae980e31d.PNG)

**Comment by Anuken** [comment]
Yes, as it should be. What is the problem?

**Comment by Luxray5474** [comment]
Ah, I didn't know 😅 I checked the changelog and couldn't find any changes relating to this. I tohught It was an inconsistency. Apologies.

**Comment by Anuken** [comment]
It's been around since the tech tree was introduced. The button change isn't related to multiplayer at all; it only changes from "tech tree" to "core database" when you're playing a custom game, since you have everything unlocked in custom games anyway.

**Comment by Luxray5474** [comment]
Ohh, thank you for clarifying.
