### ISSUE TITLE
Game load fails and closes app before reaching main menu - iOS 9.3.5

### ISSUE THREAD

**Issue by RiCkYB-667** [Anuken/Mindustry#5751]
**Platform**: *iOS 9.3.5 (13G36)*

**Build**: *6.126.3*

**Issue**: *I know it's an old OS, but i'm stuck with it on a device, can't update any further (iPad mini Gen1). The game starts, inicializes all the things (which are a bit hard to read for me) and before hitting the main menu it just crashes and exits. When i check the running apps in the background, it's there with white screen, and if i switch to it it restarts itself from the beginning to crash again. I restarted the whole device, checked for errors wherever i can, updated to latest for everything i could.*

**Steps to reproduce**: *Simply starting the game*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *N/A - can't start the game at all*

**(Crash) logs**: *If i can produce any on iPad please let me know how and i will do so.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (from AppStore) (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RiCkYB-667** [comment]
Yes i have a newer iPad as well, on which the game runs perfectly, but that has been "hijacked" by my girlfriend for drawing purposes.
I tried TestFlight but it's not compatible with the device...
I will do a full reset on the device maybe that will help something.
Otherwise i have to jailbreak it, as it seems i have no other alternatives to provide more information.
Allow me to get beck to you soon!
Thanks!

**Comment by RiCkYB-667** [comment]
Full factory reset did no good, so i did the jailbreak. I'm in the game folder. What should i look for?

**Comment by Anuken** [comment]
If the crash was in Java code, look for a `crashes` folder, or the `last_log` file. If it was native... I don't think there would be any logs at all.
