### ISSUE TITLE
Unit following player outline is behind the edge of map black layer

### ISSUE THREAD

**Issue by NoodlesOfWraith** [Anuken/Mindustry#5753]
resulting in player-controlled units not appearing as such.

**Comment by Anuken** [comment]
Invalid issue, no template. I do not know what you mean.

**Comment by Bottinator22** [comment]
I believe he means that if you take some flying units in formation, then go over the area of a map that goes black from being an inaccessible area, the coloured square that identifies a unit as one being commanded appears behind the blackness
a little hard to describe
