### ISSUE TITLE
Unit cap error

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5756]
**Platform**: Android
**Build**: 21647
**Issue**: When I launch from map154 to map "Planetary Launch Terminal", the unit cap got to 48, but I just had one core. When I reopened the map, it turned to 24. I deleted the map save<code>/sdcard/Android/data/io.anuke.mindustry.be/files/saves/sector-serpulo-93.msav</code> for test several times and this error always happened. I also tested in map24 but it didn't happen.
![Screenshot_2021-08-13-17-02-28](https://user-images.githubusercontent.com/45112661/129337216-1e430bf5-366a-486d-b9d4-a95aaff6c18a.png)
![Screenshot_2021-08-13-16-53-17](https://user-images.githubusercontent.com/45112661/129337250-6e4c8bd5-7646-4cb7-a6d8-fbfb0d43d2b6.png)

**Steps to reproduce**: Launch core from map154 to map "Planetary Launch Terminal" and you may find it.
**Link(s) to mod(s) used**: None
**Save file**: [reportsave.zip](https://github.com/Anuken/Mindustry/files/6982071/reportsave.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/129359385-36f1767f-7f9a-493c-8814-a1694d11bb39.png)

Cannot reproduce. Every time I launch to the sector, the unit cap is correct, regardless of how the sector is lost or which schematic I use.

**Comment by Hexrotor** [comment]
> ![image](https://user-images.githubusercontent.com/10100000/129359385-36f1767f-7f9a-493c-8814-a1694d11bb39.png)
> 
> Cannot reproduce. Every time I launch to the sector, the unit cap is correct, regardless of how the sector is lost or which schematic I use.

Well, I'll try to figure out how to trigger the error. Maybe it's related to my device.

**Comment by Hexrotor** [comment]
I tested many times, this error only occurred in the first three times and never happens again. At once I thought it only happened on some specific maps, but it doesn't happen again, so I can't find the reason.
The error made the unit cap double, see these pictures.
Frozen Forest:
![Screenshot_2021-08-13-21-32-11](https://user-images.githubusercontent.com/45112661/129393166-239f8189-1785-4fd5-816b-35a91120d923.png)
![Screenshot_2021-08-13-21-43-49](https://user-images.githubusercontent.com/45112661/129393200-c6c588ae-1fd0-4784-88c1-054e0487cedb.png)
