### ISSUE TITLE
Multiplayer via Steam can´t start

### ISSUE THREAD

**Issue by GeoServer1** [Anuken/Mindustry#5757]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *I start Minedustry after a few months agian, and want to play multiplayer with a steam friend, but the button "Steam" dont appear in the menü, the friend showed me that there is usally this button. i reinstaled the game several times*

**Steps to reproduce**: *Start Game wiht steam, steam knows im playing the game, but i can´t invite people and no one can invite me*

**Link(s) to mod(s) used**: `none`

**Save file**: **

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Steam is likely failing to initialize. Use the beta/alpha version (Properties -> Betas -> Select v7 branch).
