### ISSUE TITLE
Control unit in servers

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5775]
**Platform**: Maybe any

**Build**: 129.2

**Issue**: If someone is trying to control a unit and another one is trying this too at the same time, they may control the same unit.

**Steps to reproduce**: Try to control a unit and another player tries to control the same one at the same time in servers. Maybe only happens when high PING or server overloading.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Can also happen if there are no cores, someone dies as a unit, the server spawns a new one of that unit, and assigns someone to use that unit (this can happen in Crawler Arena)

**Comment by LeoSko** [comment]
Small 126.2 note: Users with poor connection also whine that they can't **escape** controlling unit and sometimes have to spam V button for several seconds. Seems like state just gets synced back to client regardless their intention to escape.

**Comment by Ineedause** [comment]
I have had this issue multiple times, it often occurs when someone has a mod that auto controls a unit and you are speedy mc. speedy and so you get the same unit, very annoying, although it can be used as a dupe glitch :o

**Comment by buthed010203** [comment]
Seems like this may have been fixed [here](https://github.com/Anuken/Mindustry/commit/1a55f19ab2d1915d2588029efbe551344a373b37) but anuke seemingly referenced the incorrect issue?

**Comment by Anuken** [comment]
wrong copy paste
