### ISSUE TITLE
Unit Formation Bug

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry#5777]
**Platform**: Android

**Build**: BE 21686

**Issue**: When double clicking to create a squadron, units don't surround the player controlled unit, but clash together to the right.

**Steps to reproduce**: Stumbled upon this in BE 21671 and confirmed it's still in latest BE.

https://user-images.githubusercontent.com/88634312/129509145-5e9fa5a9-692c-487d-a705-7ca9c6c11991.mp4

https://user-images.githubusercontent.com/88634312/129509155-4f77fc60-d8d6-498f-b8cb-0b90ed95be71.mp4

https://user-images.githubusercontent.com/88634312/129509166-e3d1c568-7265-4033-b004-ad745d95155f.mp4

I didn't test it with every unit type, but there you can see three different air unit types showing the behavior.

**Link(s) to mod(s) used**: None, vanilla is used.

**Save file**: 
[MindustryFormationBug.zip](https://github.com/Anuken/Mindustry/files/6989667/MindustryFormationBug.zip)
It's just an empty save as I confirmed it's existence through custom map via sandbox mode.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hexrotor** [comment]
same

**Comment by Odin580** [comment]
Also, Guardian health no longer shows.  

BE 21686

https://user-images.githubusercontent.com/88634312/129516014-790e5cb1-24f9-44c9-b47f-a52c198ba042.mp4

This save is from right before the Guardians attack, sector 199.

[MindustryGuardianHealth.zip](https://github.com/Anuken/Mindustry/files/6990020/MindustryGuardianHealth.zip)

**Comment by Odin580** [comment]
Apologies, it appears Guardian health shows up when phone is in landscape orientation.  In the past Guardian health would show up with phone vertical as well.  I don't know if that's a design change or unintended.

**Comment by LeoSko** [comment]
Maybe related to commit 74468855c2e4a66898f1463643badf3d02acb410 ?

**Comment by buthed010203** [comment]
> Must be related to commit [7446885](https://github.com/Anuken/Mindustry/commit/74468855c2e4a66898f1463643badf3d02acb410) which removed offset.

The offset was always 0 and absolutely nothing when changed
