### ISSUE TITLE
Corrupted .zip exported from android 

### ISSUE THREAD

**Issue by AlexandrPavlovski** [Anuken/Mindustry#5786]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *Exported game data .zip file cannot be opened on windows and cannot be imported on windows*

**Steps to reproduce**: *1. On android export game data. 2. Copy .zip file to windows. 3. Try to open the file using any zip reader*

**Link(s) to mod(s) used**: *No mods used*

**Game data file**: *[mindustry.zip](https://github.com/Anuken/Mindustry/files/6995057/mindustry.zip) please don't reap my soul*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce. Exported data is a valid zip on all my Android devices.

**Comment by AlexandrPavlovski** [comment]
thanks for a quick response. 
is there another way to transfer progress from one device to the other?

**Comment by Anuken** [comment]
You can copy-paste the game data folder manually, `Android/data/io.anuke.mindustry/files`
