### ISSUE TITLE
Pricing issue

### ISSUE THREAD

**Issue by TJCgames** [Anuken/Mindustry#5794]
The game is free on itch.io, but costs six pounds on steam.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TJCgames** [comment]
Edit: It's also free on mobile

**Comment by Phinner** [comment]
It's intentional

**Comment by Phinner** [comment]
In a nutshell, any build of Mindustry is free: Linux, Android, PC and iOS.
The Steam version only exists for convenience, I mean the friend system, Steam multiplayer and the workshop.
Just keep in mind it has nothing different from the other versions apart the advantages I told earlier.

**Comment by buthed010203** [comment]
> In a nutshell, any build of Mindustry is free: Linux, Android, PC and iOS.
Its $1 on ios but close enough

**Comment by TJCgames** [comment]
ok, but why do you have to pay for the steam version when all those other versions are free
you don't have to answer the question for iOS, i already know why

**Comment by TJCgames** [comment]
also please unclose

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/129902602-777faa5c-b532-4e4e-a9d5-d5516ff6dafd.png)

Side note: This does not belong on the issue tracker. It is a question, not a bug.

**Comment by Shawak** [comment]
The question should be why the game is so cheap, could easily charge 20 or more bucks for this :gem:

**Comment by TJCgames** [comment]
> ![image](https://user-images.githubusercontent.com/10100000/129902602-777faa5c-b532-4e4e-a9d5-d5516ff6dafd.png)
> 
> Side note: This does not belong on the issue tracker. It is a question, not a bug.

- Android and itch versions have that
- That isn't too big of a deal
- Android and itch versions have that
- So what, we don't have that?
- What the actual fuck is that
- Just copy your stuff to google drive
- Just send them on the discord

**Comment by Anuken** [comment]
If you don't care for any of that, don't buy it, where's the problem? What are you trying to prove?

**Comment by USMP-lancer** [comment]
what is he trying to prove, the game is free if you look for it, steam adds conveince but costs 6 dollars, most games of this quality cost more then 6 dollah
