### ISSUE TITLE
The server crashed during play

### ISSUE THREAD

**Issue by LTHPKBTE** [Anuken/Mindustry#5796]
**Platform**: *Linux server*

**Hardware**: *Raspberry Pi 3 Model B Plus Rev 1.3*

**Build**: *Version: Mindustry 7-pre-alpha official / build 130*

**Issue**: *The server cashed*

**Steps to reproduce**: *Play a game in any mode.*
*The problem appears irregularly.*

**(Crash) logs**: [hs_err_pid2765.log](https://github.com/Anuken/Mindustry/files/7008300/hs_err_pid2765.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The crash occurs in:

> v  ~BufferBlob::vtable chunks
> j  mindustry.world.blocks.defense.Wall$WallBuild.collision(Lmindustry/gen/Bullet;)Z+77

...which is native JVM code. This is a bug in the JVM on your platform, can't fix.

**Comment by LTHPKBTE** [comment]
Possible solution: use openjdk16 instead of openjdk8
