### ISSUE TITLE
Mining tier 0 and tier 1 have a ridiculous difference

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5799]
**Platform**: *Android*

**Build**: *130.*

**Issue**: *Sand and scrap, drill tier 0, have a much, MUCH higher drill rate than tier 1, copper and lead.*

minor secondary bug: drill-item is not included in the white shader of the build queue.
Figure 1: a drill that I am trying to make into an upgrade to Airblast.
![Screenshot_20210818-110825](https://user-images.githubusercontent.com/61173114/129942581-b1ffda13-a52e-47b9-8644-23497bfebc34.png)
![Screenshot_20210818-110811](https://user-images.githubusercontent.com/61173114/129942583-d60d0fb7-9124-47d8-9952-6a3fb041e219.png)
Figure 2: the drill it is replacing, which really emphasizes this (yes, it is imbalanced.)
![Screenshot_20210818-110900](https://user-images.githubusercontent.com/61173114/129942666-f5a46e79-7eab-41b8-bf35-4e5f5288a586.png)
![Screenshot_20210818-110847](https://user-images.githubusercontent.com/61173114/129942677-3d3a8f53-a438-48d1-a82c-6f0db8c708d3.png)

**Steps to reproduce**: *Drill sand and then copper with a more powerful drill.*

**Link(s) to mod(s) used**: *Exotic has some overpowered drills but you can just incrase the drillTime of any drill in console.*

**Save file**: 
[aaaa](https://github.com/Anuken/Mindustry/files/7009021/aaaa.zip)
Cannot include the green drill - not in the public mod as of right now, still balancing it.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have not searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no bug. Adjust `hardnessDrillMultiplier` to fit your drill, or just set it to 0 if you don't care about hardness-specific speeds.

If you drill time is 1 and the default `hardnessDrillMultiplier = 50` is used, the drill calculations will look like this:

- Hardness 0: `60 / (1 + 50 * 0)` = **60** i/s/t
- Hardness 1: `60 / (1 + 50 * 1)` = **~1.177** i/s/t

**Comment by Anuken** [comment]
> minor secondary bug: drill-item is not included in the white shader of the build queue.

I'm not sure if it should be, because it's a minor element that makes distinguishing drill items easier. Sorters & sources don't have the white tint on their middle color either.

**Comment by BlueWolf3682** [comment]
aaaaaaaa
thanks for the tip on how to yeet the multiplier
also I kinda feel like it should, just because you can still easily see it and it looks quite off without any overlay white, kinda like an off-coloured particle in an effect
