### ISSUE TITLE
Multiplayer Administration

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#58]
- View all online players and their names
- Kick players
- Ban players
- Assign password to session (push to 4.0?)

**Comment by Anuken** [comment]
Banning/Passwords pushed to a later release.

**Comment by Luxray5474** [comment]
Also set perms for shooting and build/break.

**Comment by Anuken** [comment]
No longer planning to add passwords, as 'public' servers are not planned, and banning should take care of any extra uninvited players.
