### ISSUE TITLE
Shocked effect is not applied properly

### ISSUE THREAD

**Issue by AiviriX** [Anuken/Mindustry#5804]
**Platform**: Windows

**Build**: pre-alpha build 130 

**Issue**: Using an arc against an enemy unit does not apply the shocked effect. The issue is also present when using surge ammunition from a cyclone & swarmer, and attacking an enemy unit using a pulsar. 

**Steps to reproduce**: Shoot enemy units with turrets that use surge ammunition (Swarmer, cyclone), using an arc, or a pulsar.
              

**Link(s) to mod(s) used**: Not Modded

**Save file**: 
[shocked.zip](https://github.com/Anuken/Mindustry/files/7011527/shocked.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
The status effects `shocked` and `blasted` do not last for a duration, but instead of instant.
Every time a unit that has the `wet` effect gets hit with `shocked` takes some extra damage. Same with `freezing` and  `blasted`.

Not a bug.
