### ISSUE TITLE
Cant fix controls after importing data

### ISSUE THREAD

**Issue by NeonSupernova** [Anuken/Mindustry#5812]
**Platform**: *iOS*

**Build**: *pre-alpha 130*

**Issue**: *No keyboard + mouse controls toggle*
![image](https://user-images.githubusercontent.com/78397254/130147453-de71b0d5-13a4-4384-a757-b07db4aabe65.png)
**Steps to reproduce**:  *Exported data from my PC. Then imported that data to my Iphone.
Everything loaded fine, except now my controls are all for keyboard and mouse, and there is no toggle in settings like there used to be for keyboard and mouse controls.*

**Link(s) to mod(s) used**: *None*

**Save file**: *no save file as this is a bug with the menu*

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Exported data from my PC. Then imported that data to my Iphone.

How did you get the setting to be checked in the first place? There is no way to 'enable' it on desktop, as far as I'm aware.

> here is no toggle in settings like there used to be for keyboard and mouse controls.

Keyboard controls never worked on iOS; having a checkbox there is misleading.

**Comment by NeonSupernova** [comment]
![image](https://user-images.githubusercontent.com/78397254/130155128-43910bd1-7f2e-4026-a54e-893fc9add201.png)
This what it looks like
