### ISSUE TITLE
Path to spawn targeting a single core

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry#5816]
**Platform**: iOS 

**Build**: v7.130

**Issue**: Path to spawn disregards all other cores for no apparent reason, targets one core only

**Steps to reproduce**: Use *generation* and *path to spawn* with a couple of boxed cores. Upon launching the world, only one box would be breached and land units become unable to target/attack all other cores

**Save file**: Included world file, though any world can reproduce it
[path to spawn.zip](https://github.com/Anuken/Mindustry/files/7019099/path.to.spawn.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [  ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The path to spawn filter targets *all* spawns from *one* core, it is not supposed to make paths between every single spawn/core combination.
