### ISSUE TITLE
Mod browser bug (Probably)

### ISSUE THREAD

**Issue by King-Silicon** [Anuken/Mindustry#5818]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows, Android 

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

130, 129.1. 

**Issue**: *Explain your issue in detail.*

Wrong search for my modification in the mod browser.Correcting the repository, the problem could be in the old name.  I changed the name to a new one, but my mod identifies it by the keyword "sil" (it should be "music")

important:  I am not a programmer! 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Created my own modification XD

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

![Screenshot_20210820_200214_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/80191234/130269778-88c823a3-4c1b-4668-a81b-3278bdbce934.jpg)

![Screenshot_20210820_200203_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/80191234/130269812-f17ee324-2a1a-4770-8976-62a09b9df04e.jpg)

https://github.com/King-Silicon/mindustryremix

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

The bug does not depend on the save file. 
I Reinstalled the game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

No, it is a bug

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Did you ever think it checks the author name too?

**Comment by King-Silicon** [comment]
> Did you ever think it checks the author name too?

No.  Then why isn't the mod being searched for with a different keyword?

**Comment by Anuken** [comment]
The mod browser currently searches for the repo name, not the mod *display* name. Your repo is `King-Silicon/mindustryremix`, which does not contain "music".
