### ISSUE TITLE
Agries/flying units overlay issues 

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry#5826]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Pre alpha: 130

**Issue**: *Explain your issue in detail.*

Simple overlay issues between flying units and agries with the agries reactor, please note that even though other units are not contained in the bug file, this does apply to other flying units. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

I flew an eclipse over an agries, then tested with other flying units
<img width="981" alt="Screen Shot 2021-08-21 at 1 19 01 PM" src="https://user-images.githubusercontent.com/82851415/130330329-c9b99e76-ddbd-43b6-89ed-23a8c3774523.png">

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods 

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[bug.msav.zip](https://github.com/Anuken/Mindustry/files/7025923/bug.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The circle must display in the bloom layer, which is above low-altitude flying units.
