### ISSUE TITLE
Wave range is over listed amount

### ISSUE THREAD

**Issue by pheonminum** [Anuken/Mindustry#5827]
Windows

Build 130

Wave range is over listed amount

I used logic and did appoarch at 15 blocks but the wave still hit it but the wave range is 13.5

None

 I got banned from the server

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The approach command is not exact. You have not provided a save.
