### ISSUE TITLE
Squadron Desync

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry#5832]
**Platform**: Android

**Build**: BE 21730

**Issue**: When player controlled unit is destroyed and a new unit is selected as player controlled, instead of following the player the rest of the units follow the Command Center mode.

**Steps to reproduce**: This might be intentional, but I wanted to report it just in case.  [If intentional: I'd suggest having the squadron reform around the new player controlled unit, imo that's preferable as opposed to having to chase down the rest of the Squadron or them getting destroyed backtracking through enemy territory]

I stumbled upon this while attacking an extreme base with a squadron of Quads.  While attacking the first core, somehow my unit gets destroyed first and the rest of the Quads start travelling back to base, preventing me from destroying the core.  Had to chase them down in order to re-form the squadron.  The new player controlled unit comes from the nearest Quad (aka one of the other Squadron units), so it would make sense to me that the other Quads automatically form a new Squadron around it.

This clip I got later, clearest I could get but I'll upload two more.  You can see the player controlled unit health reach zero and the remaining Quads zip off to the southeastern part of the map.

https://user-images.githubusercontent.com/88634312/130338742-8c621557-09ec-4c13-906c-2e58aae43cb2.mp4

https://user-images.githubusercontent.com/88634312/130338842-cddb383e-503b-42d3-947f-60fe28934248.mp4

https://user-images.githubusercontent.com/88634312/130338845-1f38e100-646e-475e-80ff-4686666d7748.mp4

**Link(s) to mod(s) used**: None, vanilla used.

**Save file**: 
[MindustrySquadronDemo.zip](https://github.com/Anuken/Mindustry/files/7026420/MindustrySquadronDemo.zip)

If you want to test it on my save, I'd suggest switching Command Center to middle option to more easily see the behavior.  

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional.
