### ISSUE TITLE
Microprocessors, Draw image, rotation param.

### ISSUE THREAD

**Issue by Kariamba** [Anuken/Mindustry#5833]
**Platform**: *Windows 64bit*

**Build**: *126.2*

**Issue**: Rotation param in Draw image command is unsigned 1 byte (probably), so it takes values in [0,255]. But roatation should be in [0, 360]. Or in [0, 360) but it's not so important.

**Steps to reproduce**: Set small display (display1) and controller. Program:
Draw: clear, 0, 0, 0
Operation: angle = angle + 1 (just for demo, for test I set angle manually: 0, 255 and 256)
Draw: image, 40, 40, @copper, 40, angle
Draw flush: display1

**Link(s) to mod(s) used**: no mods

**Save file**: rotation_bug.zip
[rotation_bug.zip](https://github.com/Anuken/Mindustry/files/7026763/rotation_bug.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
("image rotation" search string )

**Comment by oinkymoo** [comment]
this has been reported many times before. [including about 9 hours before your report](https://github.com/Anuken/Mindustry/issues/5831). has also been fixed in latest release
