### ISSUE TITLE
Steam Multiplayer Glitch

### ISSUE THREAD

**Issue by Auseawesome** [Anuken/Mindustry#5836]
**Platform**: *Steam/Windows*

**Build**: *Steam 130*

**Issue**: *Sometimes when a friend's ship doesnt load when they join the game and they can't see andy other ships but blocks works fine*

**Steps to reproduce**: *A steam friend joins the game*

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy
https://github.com/pixaxeofpixie/Braindustry-Mod
https://github.com/Eschatologue/Unlimited-Armament-Works
https://github.com/MEEPofFaith/missing-category-units
https://github.com/Auseawesome/MindustryPlus
https://github.com/MEEPofFaith/prog-mats-java
https://github.com/Slava0135/reVision*

**Save file**: Linked below as a .log file as github doesnt want me to link a msav
[sector-serpulo-15.log](https://github.com/Anuken/Mindustry/files/7027641/sector-serpulo-15.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I cannot reproduce this, and you have a very large list of mods, some of which are known to cause significant problems when combined.

**Comment by buthed010203** [comment]
Ive seen this multiple times playing on steam without mods, still no clue what causes it though

**Comment by Auseawesome** [comment]
> Ive seen this multiple times playing on steam without mods, still no clue what causes it though

I have too just forgot to report it and have lost the log files since

**Comment by Anuken** [comment]
The log files or saves are very unlikely to give any useful information.

**Comment by Auseawesome** [comment]
Also it only happens when its a steam friend joining not local as that still works fine on steam, the message to say the other person has joined also doesnt appear im saying this just in case its useful info
