### ISSUE TITLE
Crashing on launching to recently lost Fungal Pass

### ISSUE THREAD

**Issue by Mkroets** [Anuken/Mindustry#5838]
**Platform**: Android

**Build**: 126.2

**Issue**: After a series of losing and retaking Fungal Pass, trying to launch to fungal pass causes the game to crash.

**Steps to reproduce**: 
Roughly as follows
1. Launch to Fungal Pass from Windswept Islands
2. Capture Fungal Pass
3. Launch to 210 (left side sector)
4. Win attacks on Fungal Pass
5. Lose attack on Fungal Pass
6. Launch from 210
7. Win back Fungal Pass
8. Lose Fungal Pass
9. Lose 210
10. Attempt to launch from Stained Mountains to Fungal Pass, causes crash.
11. After each crash, the resources are used.

**Link(s) to mod(s) used**: None.

**Save file**: export.zip https://drive.google.com/drive/folders/11HakQ5_Vi4nk-z0jD_veR_HDFyobtEfE?usp=sharing (directly from export data)

**(Crash) logs**: crashes.txt in https://drive.google.com/drive/folders/11HakQ5_Vi4nk-z0jD_veR_HDFyobtEfE?usp=sharing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate; this was already reported and fixed in v7.
