### ISSUE TITLE
Unify info format

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5840]
**Platform**: Any

**Build**: 130

**Issue**: We found these problems while translating. 
1. Optional enhancements: The water extractor, its info shows efficiency +40% on ice tile. Yes, if you put it on full ice tiles(2x2), efficiency is 140%. But silicon crucible is different, it shows efficiency +7% on 1x1 hot rock tile. If you put it on full hot rock tiles,(3x3) efficiency is 167%(idk 100%+9×7%=167% :P). And cultivator is the same, it shows 1x1 affinities, it seems that only water extractor shows 2x2.
![2021-08-23 10 18 49](https://user-images.githubusercontent.com/45112661/130399277-49d68116-8567-42d1-86a3-8d0a9cc77c0d.jpg)
![2021-08-23 14 11 57](https://user-images.githubusercontent.com/45112661/130399320-1531a126-caa2-4813-a137-11a6276b51c6.jpg)
![2021-08-23 14 11 02](https://user-images.githubusercontent.com/45112661/130399338-e04179f2-9ec8-40a0-8c3e-1306df68cf24.jpg)

2. Required Tiles: For example, the oil extractor required dark sand tiles and it shows "150%" directly, yes it's not for a 1x1 area, you need put it on full dark sand tiles(3x3) and you will see efficiency is 150%. 
![2021-08-23 14 13 52](https://user-images.githubusercontent.com/45112661/130399394-a1af9e82-980f-4bae-b188-11269cb3c471.jpg)

Now let's see thermal generator, it shows "+50%"(note the "+") for 1x1 hot rock tile. Put it on full hot rock tiles(2x2), efficiency is 200%.
![2021-08-23 14 17 40](https://user-images.githubusercontent.com/45112661/130400022-e71a8d8b-41d5-4dce-b8cc-184ef051530a.jpg)

Yeah that's right, but the oil extractor?
![2021-08-23 14 13 16](https://user-images.githubusercontent.com/45112661/130399418-f0c0b4d9-d4c1-4b46-b6dd-003632f42997.jpg)

3. "Boost" & "Speed increase" #5809 : 
When you see 'boost: 150%'
It can be 'increase the speed to 150%' or 'increase the speed to 1+150%, which is 250% in total'. Boost can either be verb or be noun.
Maybe you will say that the colon has already avoided this ambiguity, but you know there's always someone who ignores those things, **and translating 'boost' is hard with nothing to avoid ambiguity.**
My suggestion: Show "boost: +50%" instead of 150%, and if its power is not enough, show "+0%".
![](https://user-images.githubusercontent.com/57857764/130355046-1376f79b-7d01-4d3d-962d-260485d38dbc.PNG)
![](https://user-images.githubusercontent.com/57857764/130355048-547d78e0-be6b-400a-9eaf-c42dd79298b0.PNG)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
While the tile display inconsistency is a valid problem, boost ambiguity is not a bug and should not be discussed here.

**Comment by Hexrotor** [comment]
> While the tile display inconsistency is a valid problem, boost ambiguity is not a bug and should not be discussed here.

OK, thanks =)
