### ISSUE TITLE
About java mod dependence load order error

### ISSUE THREAD

**Issue by EB-wilson** [Anuken/Mindustry#5841]
the mod main class load order often be unexpectation, It causes a `ClassNotFoundException`.
So, I hope the dependence .jar load precedence over the mod .jar load.
![-71990587fdffb5e9](https://user-images.githubusercontent.com/77141581/130410183-896349cf-35c7-4c3e-acbb-4efa35dcf7a5.png)

**Comment by Anuken** [comment]
Template not filled in, no mod info or source provided.

**Comment by EB-wilson** [comment]
No, you don't consider .jar file load,
After I reading your code, I discover sequence of class `Mods` loading mods is NameSort, because it use method `.list()` in class `Fi`.
That means load order of .jar file and class files inside them is NameSort. Then I try to change the Librarian name by "A" first, this question was solved.
Please load dependence mod .jar file before use dependence mod.

> 
> 
> Template not filled in, no mod info or source provided.

**Comment by Anuken** [comment]
If you want your issue fixed, fill in the mandatory issue template and provide source files for all mods involved so I can reproduce it.
