### ISSUE TITLE
Mass Drivers don't automatically link after building

### ISSUE THREAD

**Issue by RedstonerKBC** [Anuken/Mindustry#5846]
**Platform**: *Windows*

**Build**: 126.2

**Issue**: You know how when you place bridge conveyors/pumps or phase conveyors/pumps they automatically link to each other? They'll show a ghost link indicating which one they'll link up with? Mass Drivers also show a dashed line indicating which driver they'll link up to, but Mass Driver's don't link. You still have to link them manually after placing them.

**Steps to reproduce**:
1. Build a mass driver.
2. Click on the mass driver. It will show it's range.
3. Somewhere within that range, grab another mass driver but don't place yet. You should see a dashed line connecting the two.
4. Build the 2nd mass driver within range of the first. The dotted line will disappear. Notice how they did not automatically link up? This is the bug.

**Link(s) to mod(s) used**: NA

**Save file**: https://ufile.io/jc4nwv0z

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: NA

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They were never supposed to automatically link, the line is just a guide.
