### ISSUE TITLE
AI building don't working

### ISSUE THREAD

**Issue by Kaviaki** [Anuken/Mindustry#5855]
**Platform**: Android

**Build**: `pre-alpha build 130.1`

**Issue**: The AI building don't work if there's more than 1 enemy team.

**Steps to reproduce**: I enabled a crux team and a green team, then I enable the option to make them have a AI building and the Infinity resources too.
When I enter the game, the ships don't move, they're just there in their cores doing nothing.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Template:

> IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by BlueWolf3682** [comment]
Confirmed reproduction, build 130.1, Google Pixel 2
Save: 
[ae.zip](https://github.com/Anuken/Mindustry/files/7043168/ae.zip)
Mods: Exotic as always, other mods enabled aren't relevant

**Comment by NeonSupernova** [comment]
Also confirmed this: 
Ios pre-alpha 130.
[O.zip](https://www.dropbox.com/s/8ioqm4a0iumqgz2/O.zip?dl=0)

**Comment by Anuken** [comment]
> O.zip

This was not reproducible with my AI test map, but it does happen here... which is why I always ask for a save.

**Comment by NeonSupernova** [comment]
I think the problem is the ai is buggy when having infinite resources, or the ai can't seem to fight each other. In my test, the ai only works when I have one enemy core. ![image](https://user-images.githubusercontent.com/78397254/130801926-5b26a541-3a79-4948-b855-e9fc64f0eba7.png)
Any more cores with ai and they don't work
