### ISSUE TITLE
Broken Logic

### ISSUE THREAD

**Issue by MistahStealYoGril** [Anuken/Mindustry#5857]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number is under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
130+ happened in all.
**Issue**: *Explain your issue in detail.*
The logic likes to break when I switch sectors in the campaign. I would have bots on turrets and leave to handle something else then when I come back, the logic would be broken then flares would be either at the command center or connected to multiple logic projectors.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I didn't do anything to it but move sectors.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MistahStealYoGril** [comment]
Oh no. Sorry I forgot to add the file

**Comment by MistahStealYoGril** [comment]
https://drive.google.com/file/d/1EEVEyQ8JFjc5y_TZJQmgd78Rqgww8Vvl/view?usp=sharing

**Comment by MistahStealYoGril** [comment]
Do you guys want me to redo the entire bugs post? I honestly do not know how to do this.

**Comment by Anuken** [comment]
1. You have linked your entire game data zip, which can't be used for testing; I don't know which sectors are broken and you have not specified which ones.
2. I don't debug logic programs unless you can specify what is wrong with them; more often than not, it is user error. "Logic is broken" is not a valid issue, specify which exact operation you are performing, what you expect to happen and what actually happens.

**Comment by Bottinator22** [comment]
I believe this issue is due to logic processors resetting their variables when you leave and come back to the sector. I've had a similar issue with the "Wireless Surge" schematic.
