### ISSUE TITLE
Обновление и пропажа.

### ISSUE THREAD

**Issue by DemonActor** [Anuken/Mindustry#5859]
**Platform**: `Android 27`

**Build**: `release build 126.2`

**Issue**:*Надеюсь вы сможете это перевести. Проблема в следующем: после обновления в сохранённой игре пропали орудия ПВО. Я не смог восстановить систему ПВО из-за удачно появившихся летающих врагов. Игра (которая длилась не один час-5-10) проиграна. Ничего, скажете вы, можно начать новую игру...итак: у меня пропали ВСЕ ресурсы. Медь, свинец, метастекло, кинетичесский сплав и др....осталось только 400 ед. меди, чего не хватает для начала игры. Просто не запускается даже отправная точка. Я не знаю как начать компанию...Прошу возместить хотя-бы по 5 тысяч всех видов ресурсов. Можно просто 10 тысяч меди.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by wdmvv** [comment]
>Прошу возместить хотя-бы по 5 тысяч всех видов ресурсов. Можно просто 10 тысяч меди.
Curious how he will do it

**Comment by DemonActor** [comment]
Did not understand. "Curious how he will do it". I translated it like this: "I wonder how he will do it." I ask you to answer the question: "It's a mistake on your part. What do I have to do with it?" Or do you mean how you should do something? Can't you identify the player's account by the player's ID and transfer the "reward" to it? Usually, in other games they do something like this. I apologize for the resourcefulness.
Или я не туда обращаюсь? Но в игре ясно обозначено, что при нахождении ошибки, а мой случай и есть ошибка, обратиться сюда...ну, то есть к вам.
>
>Среда, 25 августа 2021, 9:08 +03:00 от wdmvv ***@***.***>:
> 
> 
>Прошу возместить хотя-бы по 5 тысяч всех видов ресурсов. Можно просто 10 тысяч меди.
>Curious how he will do it
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS or  Android .
 
 
--
Андрей Трутнев

**Comment by VladBlad3** [comment]
В крайнем случае можно зайти в настройки, там в настройках игры сбрось данные, на ПК так такая проблема решается. м.б. конечно тебе разрабы как-то твой ущерб смогут компенсировать, но я не уверен что сейчас в коде игры у разработчиков есть для этого инструменты.

**Comment by VladBlad3** [comment]
Translation of an issue: after last update this guy's anti air defense systems had suddenly vanished, so his game that he had played for several hours was ruined. All his cores got destroyed and he don't have enough resources to drop even to the starting location. He would like to get some of his resources back (5k of each) or at least some copper so he would be able to start his campaign over

**Comment by Anuken** [comment]
> осталось только 400 ед. меди, чего не хватает для начала игры.

You don't need any resources to start the game. Launching to Ground Zero is free.

> Прошу возместить хотя-бы по 5 тысяч всех видов ресурсов.

I don't "restore" resources; if you need something, install a cheat mod or something like dev-mode.

**Comment by DemonActor** [comment]
1-Я играю на смартфоне. 
2-Вышло обновление на игру. Я его установил. Оружия ПВО исчезли. У меня нет защиты от воздушных врагов. Я проиграл. 
3-Хотел начать новую игру. Понял что ресурсов нет. Они ДОЛЖНЫ были быть. В начальной точке требуется 1 тысяча меди и 800 свинца. Они НЕ изменяются. 

.
  
>Среда, 25 августа 2021, 12:21 +03:00 от VladBlad3 ***@***.***>:
> 
> 
>Translation of an issue: after last update this guy's anti air defense systems had suddenly vanished, so his game that he had played for several hours was ruined. All his cores got destroyed and he don't have enough resources to drop even to the starting location. He would like to get some of his resources back (5k of each) or at least some copper so he would be able to start his campaign over
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
--
Андрей Трутнев

**Comment by DemonActor** [comment]
Хорошо. Повторю. Я НЕ могу начать игру в Ground Zero т.к. у меня нет ресурсов. У меня 404 меди. Нужно 1226 меди и 800 свинца. 
Нажимаю «ресурсы»- «сбросить по умолчанию»- «назад»
Ничего не меняется. Вообще. 
Вы не можете мне помочь, спасибо. Удачи!
буду сам решать ваши...то есть мои проблемы... 
>Среда, 25 августа 2021, 15:39 +03:00 от Anuken ***@***.***>:
> 
> 
>осталось только 400 ед. меди, чего не хватает для начала игры.
You don't need any resources to start the game. Launching to Ground Zero is free.
>Прошу возместить хотя-бы по 5 тысяч всех видов ресурсов.
I don't "restore" resources; if you need something, install a cheat mod or something like dev-mode.
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS or  Android .
 
 
--
Андрей Трутнев

**Comment by DemonActor** [comment]
Да. Они мне сказали установить читы...короче, они вообще никак не могут помочь. Спасибо!

  
>Среда, 25 августа 2021, 12:15 +03:00 от VladBlad3 ***@***.***>:
> 
> 
>В крайнем случае можно зайти в настройки, там в настройках игры сбрось данные, на ПК так такая проблема решается. м.б. конечно тебе разрабы как-то твой ущерб смогут компенсировать, но я не уверен что сейчас в коде игры у разработчиков есть для этого инструменты.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
--
Андрей Трутнев
