### ISSUE TITLE
Unit locate damaged

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5889]
**Platform**: Android

**Build**: 21786

**Issue**: When the logic run `Unit locate damaged` normally(short interval between last and next time), it will output the building which already be fixed and output "found=0". If the interval isn't too short (use "wait" etc), it works fine.
**Steps to reproduce**: Watch the video.

https://user-images.githubusercontent.com/45112661/131235855-1e7d0bdd-ff83-4571-8c61-66643ec5158f.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
All locate/radar commands have a cache. Results do not update every invocation.

**Comment by Hexrotor** [comment]
> All locate/radar commands have a cache. Results do not update every invocation.

Well, maybe clean the cache immediately when not found ?:o

**Comment by Anuken** [comment]
No.

**Comment by Hexrotor** [comment]
Oh, OK 😳
