### ISSUE TITLE
Add screenshots to the repository

### ISSUE THREAD

**Issue by rnauber** [Anuken/Mindustry#589]
Hi,
I suggest adding screenshots and localized descriptions of this game to the repository in the fastlane format. This would be automatically picked up by F-Droid and the play store, thus reducing the load maintaining two app stores: 
https://gitlab.com/fdroid/fdroiddata/merge_requests/5146#note_198644881 

Thanks for considering,
Richard

**Comment by Anuken** [comment]
How would the Play Store pick up the screenshots? As far as I know, it isn't linked to this repository in any direct way. Does it somehow extract the screenshots from an asset directory from within the APK?

**Comment by qaws** [comment]
You are right,  it is not automatically fetched from Google play. But the fastlane tool seems to make it easy to push it:
https://docs.fastlane.tools/getting-started/android/release-deployment/

**Comment by Anuken** [comment]
Should be fixed as part of fb84b4b7c1b3115a62fcffea6f6cd477e79fa417.
