### ISSUE TITLE
Laser turret charging.

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5895]
**Platform**: *Android*

**Build**: *130.1*

**Issue**: *Laser turrets can fire multiple times while charging.*
![Screenshot_20210829-075034](https://user-images.githubusercontent.com/61173114/131253069-1f4866b8-6d21-4d8f-a2fc-4c4f19d6e7e3.png)

**Steps to reproduce**: *Fire a Rainstorm with supercoolant.*

**Link(s) to mod(s) used**: *Exotic as always.*

**Save file**: 
*[The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.](https://github.com/Anuken/Mindustry/files/7072633/dingus.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment]
let me test for latest release

**Comment by MrDuck557** [comment]
or not
