### ISSUE TITLE
Logic op addition error

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5902]
**Platform**: Android

**Build**: 21786

**Issue**: op 0.1+0.2=0.30000000000000004

**Steps to reproduce**: op 0.1+0.2=result , print result

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
this is just floating point math error, which cant be fixed
