### ISSUE TITLE
Import Info Bug

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry#5907]
**Platform**: Android

**Build**: 21792

**Issue**: Info page shows imports coming in from sector/s that aren't sending resources.  No resources are sent.

**Steps to reproduce**: I don't know what causes this, but here are screenshots + clip, etc:

Sector 60 isn't exporting anything, and never has.
![Screenshot_20210830-155158](https://user-images.githubusercontent.com/88634312/131404370-5d75b622-36c9-42bb-abde-cdabb95df15b.png)

No export lines from 60 to 265 on planet screen.  60 is the the sector directly to the right of 265.
![Screenshot_20210830-154922](https://user-images.githubusercontent.com/88634312/131404441-b7bb703b-3f24-4ac3-a63c-c3b7cf6538e5.png)

No export values mentioned here, you can check the sector as well; it has no payload drivers, never has.
![Screenshot_20210830-153122](https://user-images.githubusercontent.com/88634312/131404506-374ba969-c98d-4001-b7ab-a069fe3d5109.png)

GZ to 265, the values all add up, so 60 is sending 0 exports, despite being named as source for imports.
![Screenshot_20210830-155209](https://user-images.githubusercontent.com/88634312/131404620-d74a0a0e-9a85-4d03-a51e-6bace9118d8b.png)

I likewise clicked GZ after loading my file so that the exporting completely resets.  Then immediately clicked planet map, and sector 60 is no longer listed as an export source for 265.  I then let GZ get going for a few seconds and once again sector 60 is listed as an export source for 265.

https://user-images.githubusercontent.com/88634312/131405521-daad4bbc-e319-4540-9b04-32e2bbc65eb0.mp4

https://user-images.githubusercontent.com/88634312/131405528-4fdf385b-03c8-4a65-90c2-1d217769754f.mp4

**Link(s) to mod(s) used**: None, vanilla is used.

**Save file**: 
[MindustryImportInfoBug.zip](https://github.com/Anuken/Mindustry/files/7079600/MindustryImportInfoBug.zip)

**(Crash) logs**: N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Odin580** [comment]
Tested a little further.  I directed GZ at Planetary Launch Terminal, and it then lists the 4 adjacent sectors as sources for resources.

![Uploading Screenshot_20210830-162510.png…]()

**Comment by Odin580** [comment]
This might help.  The sectors that are labelled as exporting to the given sector, are all sectors that I captured from that sector.

![Screenshot_20210830-173024](https://user-images.githubusercontent.com/88634312/131414312-a31292ff-93aa-45d6-9774-429ac6cf9993.png)

Example above, I took Planetary Launch Terminal from Desolate Rift, as well as those adjacent sectors.  I noticed this because in sector 265, it didn't list the sector above it as a source.  Which meant it wasn't based on adjacent sectors.  But I realized sector 60 was attacked from 265, but the one above wasn't.

Then I checked Desolate, and it shows PLT as a source, along with other sectors I attacked from it.  So that seems to be the relationship.

**Comment by begginerr** [comment]
is this issue so hard to fix? i am surprised that anuke didnt fix this yet

**Comment by Hexrotor** [comment]
> is this issue so hard to fix? i am surprised that anuke didnt fix this yet

dont worry, maybe he just has no time to do this

**Comment by begginerr** [comment]
> > is this issue so hard to fix? i am surprised that anuke didnt fix this yet
> 
> dont worry, maybe he just has no time to do this

maybe thats why, there are like 5 open bugs right now, also a bug that has been closed but says that its open

**Comment by bugreporterboris445** [comment]
I tried repeat your issue, and dont get same result, but I see, Your strategic is using core as transport hub (relay). In my expierence using core/stroage to transport for launchpads can get a lot of, hgm, side effects with the calculations and starting/stopping intercontinental ballistic transport system. Most likely result, that I've recieve is stopping the transport  after couple of minuetes, when one supply factory feed to container, second feed by chain core->unloader->container, then both unloaded to launchpad. Another is starting transport, recalculating capasity, then stoping transportation when I unload my resources from core-to-another-sector, if not stay in this two sectors.

**Comment by bugreporterboris445** [comment]
Gotcha! I get same bug on Windows 10 x64, now I saved campaign progres. If it will be needen, I'll drop it here
