### ISSUE TITLE
incorrect (strange?) behavior of flying units in logic (pathfind)

### ISSUE THREAD

**Issue by ilya034** [Anuken/Mindustry#5910]
**Platform**: *Windows 10 64bit*

**Build**: *130.1*

**Issue**: *when the pathfind command is applied in the processor to flying units (Oct.), they begin to behave as if they were not flying, but were on the ground (flying around obstacles from the side, not flying over them)*

**Steps to reproduce**: *build flying units and use the pathfind command to them through the processor (in this case, the map must have a difficult terrain)*

**Link(s) to mod(s) used**: *None*

**Save file**: *[octs.zip](https://github.com/Anuken/Mindustry/files/7083497/octs.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ilya034** [comment]
we also need to improve the "move" and "approach" commands for ground units (so that they avoid obstacles in their path).

**Comment by begginerr** [comment]
> we also need to improve the "move" and "approach" commands for ground units (so that they avoid obstacles in their path).

thats true, they just go from point a to point b without looking for obstacles and avoiding them

**Comment by oinkymoo** [comment]
> we also need to improve the "move" and "approach" commands for ground units (so that they avoid obstacles in their path).

i believe that it was discussed previously that it is far too resource-intensive to calculate the pathfind route from anywhere to anywhere, and simply calculating the path from anywhere to just 2 points (player core and enemy core) is hard enough

**Comment by ilya034** [comment]
> > we also need to improve the "move" and "approach" commands for ground units (so that they avoid obstacles in their path).
> 
> i believe that it was discussed previously that it is far too resource-intensive to calculate the pathfind route from anywhere to anywhere, and simply calculating the path from anywhere to just 2 points (player core and enemy core) is hard enough

**Comment by Anuken** [comment]
Pathfinding simply makes units avoid obstacles as if they are ground units. "Pathfinding" for flying units does not make sense; they can simply move in a straight line. This isn't a bug.
