### ISSUE TITLE
Incorrect display of the oil extractor efficiency value.

### ISSUE THREAD

**Issue by KirillAldashkin** [Anuken/Mindustry#5914]
**Platform**: *Windows*

**Build**: *130.1*

**Issue**: *Incorrect display of the oil separator efficiency value before installing it in any acceptable place.*

**Steps to reproduce**: *Try to place oil extractor.*
 
 An integer was expected
![699](https://user-images.githubusercontent.com/52224930/131621598-0c7176cb-4af8-4a26-8a31-56dc87416d3a.png)
---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

 (I will fix this issue myself soon)

**Comment by begginerr** [comment]
i

**Comment by SMOLKEYS** [comment]
~~*nice*~~

![SmartSelect_20210905-191713_GitHub.jpg](https://user-images.githubusercontent.com/75618732/132124822-a0dc288b-9f4a-4c95-8886-5c2c4fbb2921.jpg)
