### ISSUE TITLE
AI builds Banned Blocks

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#5919]
**Platform**: *All*

**Build**: *v130.1*

**Issue**: *AI can build Banned Blocks.*

**Steps to reproduce**: *Make a map with ai, ban a block ai uses, open custom game and watch in super fast speed.*

**Save file**: 
[save.zip](https://github.com/Anuken/Mindustry/files/7092165/save.zip)

![image](https://user-images.githubusercontent.com/62565267/131693622-689f3350-d13d-4171-92a4-121c389c92de.png)
![image](https://user-images.githubusercontent.com/62565267/131694398-632907f2-24b4-4aca-a918-74969f975389.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by USMP-lancer** [comment]
this brings more questions, is it only when all parts of a structure are banned does it not build it

**Comment by RebornTrack970** [comment]
> this brings more questions, is it only when all parts of a structure are banned does it not build it

No, it builds even if every single block is banned.

**Comment by USMP-lancer** [comment]
~~good info that can prove useful in debuging~~

**Comment by Anuken** [comment]
Banned blocks do not apply to builder AI.

![image](https://user-images.githubusercontent.com/10100000/132097058-853abed9-87d1-47c4-a32d-89dcc5d3f3ef.png)
