### ISSUE TITLE
nova series BUG: no se nada de esto así que lo hare aquí, la serie nova falla a veces al salir de la maquina de drones

### ISSUE THREAD

**Issue by HikkiTTGL** [Anuken/Mindustry#5920]
**Platform**: `Windo
<img width="960" alt="2021-09-01 (5)" src="https://user-images.githubusercontent.com/89932054/131710408-891208a5-8a1c-4c12-a66d-6882c5846617.png">
ws 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[sk7725/time-control:0.2, Xelo/xelos-pixel-texturepack:0.4.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

--- 

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
-

**Comment by Bottinator22** [comment]
For one, template

For another, I doubt Anuke can even understand that title

**Comment by Bottinator22** [comment]
I believe the bug you're trying to report here is the fact that there's a flying Pulsar in the (improperly linked) picture that isn't pathfinding.

**Comment by HikkiTTGL** [comment]
Hi ... I don't know how to speak English or use the templates, so I did as
I could and I haven't been able to test version 7 either, sorry for the
inconvenience I just wanted to report a bug from the nova series, thank you
for reading.

**Comment by Bottinator22** [comment]
> 1- Use English
> 2- Please use template correctly
> 3- The pic doesnt even render
> 4- You didnt check the boxes
> 5- You didnt test on V7
> 6- Didnt even explain the issue nor told how to reproduce
> 7- Why would you say SERIOUS BUG in a bug report?
> 8- The mods you gave dont even effect the game
> 9- You didnt even tag this issue as Bug

By "nova series BUG" he meant a bug with the nova line, not a nova serious bug
