### ISSUE TITLE
Logic rader can't find enemy

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5922]
**Platform**: Android

**Build**: 21792

**Issue**: When the logic rader filter config is `any any any`, it can't find enemy, only ally.

**Steps to reproduce**: Make a logic `rader`or `unit rader`, print result to message block.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by begginerr** [comment]
i am starting to get worried about all the open bugs ._.

**Comment by Hexrotor** [comment]
> i am starting to get worried about all the open bugs ._.

hope Anuke will come back soon
