### ISSUE TITLE
Bridge Conduits unaffected by overdrive boosters (expected affected)

### ISSUE THREAD

**Issue by cigarmemr** [Anuken/Mindustry#5925]
**Platform**: Windows

**Build**: steam build 130.1

**Issue**: Bridge Conduits are unaffected by overdrive boosters, thus it is "slower" than Pulse Conduits in a liquid transferring matrix under the effect of overdriving, causing the liquids get stuck at the point where Pulse Conduits connect to Bridge Conduits.

**Steps to reproduce**: 
1. Enter a sandbox map.
2. Paste and build a schematic based on the code below:
bXNjaAF4nGPgYGBjZmDJS8xNZWApSc0tYOBOSS1OLsosKMnMz2NgYGDLSUxKzSlmYIqO5WAQzi9LLUopyixL1S0oys9KTS7JL2IQLMksSczLLM3VTc7PK0utBArxFpTmFKeC+CmlmSUMPAX55alFusX5pUXJqQz8SUWZKempCNV8CAGwcv7czOSifJANyanFxUAF7LlAOjE9FegcPgYIYARCZgYGJiDFygBkMTEwcDAwsABpZnYGEAMEWIFcVgSXDQjBBgRXzElOSUjYoOV3VvucfpBGkMe589rea8/oG4UUaJw846vr53fG86mWxqkz2oEaTRcyLZceleRyWPnoyJcQZ70FeWpsfjvMFKbPbGRWO33gxAEGhrNdMlVg0xlBpgdBTddBMt1b86yOITGGp6mx8c3QU+hvBRp+Emx43TfpaqAH2IAe+///fyIQ1wI9xgb0GJRbzcAOhAwswAAx1DMFcxiBHEZDYNiwQwKJHRRIAJHNkKE=
It should appears like this:
![image](https://user-images.githubusercontent.com/26317456/131946147-2b679efb-41f4-4246-94b3-3b58624cf78c.png)
3. Check the orange rendering colour to confirm the boost states of each block.
(Alternative) Check the displayed "timescale" on the Message blocks.
4. No boosters applied on the Bridge Conduits.

**Link(s) to mod(s) used**: None.

**Save file**: Not related.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Not related.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by cigarmemr** [comment]
Here we may confirm this issue by doing more test:
![image](https://user-images.githubusercontent.com/26317456/131947786-3ad6e823-57da-4391-b9ea-27e08fbf0f20.png)
In each group of blocks, Water generated by the 3 Rotary Pumps are 48/s times 3 to a total of 144/s. Water consumed by the 8 Cultivators are 18/s times 8 to a total of 144/s. The spored ground is not related as in current 130.1 version water consumption of Cultivators are constant (if you insists, all the Cultivators are on the spored ground, no difference).
The only difference between the two groups of blocks are the Overdrive Dome lies on the left. Its position is causiously picked so it affects the left group only.
As we can see, the Cultivators of the left group stops working periodly for the insufficiency of water. However, the Rotary Pumps stops working periodly too, as water accumulates at the junction point between the Pulse Conduit and the Bridge Conduit.
Hopefully this is not what it supposed to be, as it may cause a well-working liquid transferring network to glitch after applying overdrive to it.

Here is the test schematic:
bXNjaAF4nIWS7Y7SQBSGTz/oB5/LalTsDIMXwBV4AV6Bv4w/WNqYJkCxtJi9CW943cUzPBqzMUZI++SdOXNoOY+8k1Uk8WGzryTuqv1RRmV12rb1saubg4gku81dtTtJ+OnzUEa1lqxPTd9uK5k256ot2/pcrctGj4+Pzbeq/b077+puc6j7/XrbHM7VfdNKfj19bupShtt+19XnTafLk2O/O1W+rOzrTkZt023a+/Wx14eZ7OqvfV2u26bvqlamd21dfvlTK/JdL5kMREZBIIHMJBKFX8iDUEKZZBJEuqwfj0AijxBEIAYDkIAUZCAHQ4liufG9IkUAQhCBGAxAAlKQgRwMJfQYkcZgAqZgBrT5QOb+hzxikIAMDMEYTIGeSxQLnaLiLakABliw9Lj1lalCKz0MuO690PcLM0VM0vfzKSGlpIyUk4akEWlMmpCmpBnphjSXKFfcppfL5YNeH6/xVeqHp/HHteg1tW/AQqJQXkqaJZdHLXmUQKlfifT+oByEfn+Wxc/3Lw/X9UUWXZ507Uk8B/pnF5hSMNyC4RYMt2C4BcMtGG7BcAuGWzDcAlMMphiaGZoZmhmaGZoZmhmaGZoZmhlMMZhiMMVgisEUgykGUyymWEyxmGIxxWKKxRSLKZYJWEyxmGIxxWKKxRSLDUtMWWLKElOW7DlMcZjiMMVhisMUhykOUxymOExxmOIwxWGKwxTHczpMcZjy/pcp7rkpDlMcpjhMWf3HlNU/TFn9ZcpPyna39w==
If you'd like to test this on your own map, please make sure the Rotary Pumps are all on shallow waters so that the production and consumption of water are equal.

**Comment by bugreporterboris445** [comment]
MAX flow in 130.1 for impulse conduit is 600/sec. Its a small funny secret - liquids and conduitcs not realy boosted by projectors. In second schema the cultivators on the left side is boosted, another no, thats why water consumption rises. Conduit can transport 600/sec, thats all.

**Comment by bugreporterboris445** [comment]
Bridge conduits dont cause the problem, actualy liquid router is cause
![Screenshot_2](https://user-images.githubusercontent.com/86530346/132025870-c3004718-9d27-437c-aabb-9a71628d3583.jpg)
is

**Comment by begginerr** [comment]
i guess second example is because liquid router has s*** throughput right?

**Comment by bugreporterboris445** [comment]
I think yes, router divide stream at half, many schemes work bad on it. It looks like it just slows down during the switching time

**Comment by Anuken** [comment]
> expected affected

This is not a reasonable expectation. Bridge conduits cannot be overdriven.

**Comment by cigarmemr** [comment]
> MAX flow in 130.1 for impulse conduit is 600/sec. Its a small funny secret - liquids and conduitcs not realy boosted by projectors. In second schema the cultivators on the left side is boosted, another no, thats why water consumption rises. Conduit can transport 600/sec, thats all.

The pumps are boosted too, I see there are no difference between the production and consumption in water in either groups.
And I've got a different test result for your schematic:
![image](https://user-images.githubusercontent.com/26317456/132099669-522497c1-d5cc-49f3-aec5-21372139415f.png)

**Comment by bugreporterboris445** [comment]
> The pumps are boosted too, I see there are no difference between the production and consumption in water in either groups.

I think you'we got same result, see you sreenshot intently
![Screenshot_3](https://user-images.githubusercontent.com/86530346/132100577-f112ab02-138c-4669-a183-305df131bcfb.jpg)

My first conclusion was wrong too, because increased consumption is not the reason. Liquid router is.

**Comment by cigarmemr** [comment]
Hmm, oddly enough, the build works well on the test save, but the same thing as you mentioned happens on other maps.
Please check this save for more info:
[17.zip](https://github.com/Anuken/Mindustry/files/7110168/17.zip)

**Comment by bugreporterboris445** [comment]
I loaded it, the same. Last cultivators suffer from lack of water. I remember Anuke wrote in the comments to version 6 that he was trying to make liquids work propertly. I think its not the easiest thing, thats why. One day we'll all comprehend Java and be able to fix it. Or not, not so important, I think

**Comment by cigarmemr** [comment]
Fine. I'm looking forward to that day :)
