### ISSUE TITLE
Game insta dies when i capture zone 142 in 130.1

### ISSUE THREAD

**Issue by sa1672ndo** [Anuken/Mindustry#5928]
**Platform**: *Android,windows

**Build**: *130.1 pre-alpha

**Issue**: *mindustry dies when i capture sector 142 near frozen forest+ game crash if i export crash report on android

**Steps to reproduce**: *try to capture sector 142 on my save and it will crash

**Link(s) to mod(s) used**: *extra utilities mod,heavy armament industries,
mindustry-extended,new horizons,
ReVision,unit information,vanilla enchanced.

**Save file**: *https://drive.google.com/file/d/1jhIPOZcCfeHTVaUTUTsYL8OzwUhGmWh5/view?usp=drivesdk

K.

**(Crash) logs**: *[crash.txt](https://github.com/Anuken/Mindustry/files/7107333/crash.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by sa1672ndo** [comment]
i kinda fixed the bug by playing on windows version

**Comment by sa1672ndo** [comment]
game still crashed when last enemy was killed but this time it actualy captured the sector

**Comment by Bottinator22** [comment]
might be due to all those mods tho

**Comment by sa1672ndo** [comment]
I guess
