### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by NeonSupernova** [Anuken/Mindustry#5941]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Server 130.1
**Issue**: *Explain your issue in detail.*
I get this error: java -jar server.jar

[09-05-2021 16:39:14] [E] java.lang.IllegalArgumentException
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
        at arc.util.async.AsyncExecutor.<init>(AsyncExecutor.java:25)
        at arc.util.async.AsyncExecutor.<init>(AsyncExecutor.java:20)
        at mindustry.mod.Mods.<init>(Mods.java:33)
        at mindustry.Vars.init(Vars.java:279)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:47)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:65)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I ran java -jar server.jar
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[Save file](https://drive.google.com/file/d/1reT_CFOKBBiqFUNYupnSgIepwq5bHLa6/view?usp=drivesdk)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
See **Issues** section
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce, works on my machine.

**Comment by NeonSupernova** [comment]
Issue with my java?

**Comment by Anuken** [comment]
Most likely. Nobody else has this problem, as far as I'm aware.

**Comment by NeonSupernova** [comment]
Whats the minimal java version required to run the server?

**Comment by Anuken** [comment]
8

**Comment by NeonSupernova** [comment]
Hmm, just reinstalled openjdk8 and jre. Are there any known incompatibilities with alpine linux?
I ran it again and got the same error. ![image](https://user-images.githubusercontent.com/78397254/132135434-dfe47c28-666b-4bd0-a16a-18164f957f70.jpeg)

**Comment by Anuken** [comment]
I don't know of anyone running the server on Alpine. 

Unless your JRE implementation is significantly different, the only way for that to happen is for `Runtime.getRuntime().availableProcessors()` to return 0, which:

1) doesn't make any sense, and 
2) is inconsistent with its official Javadoc (*"never smaller than one"*), meaning your JVM is broken.

**Comment by NeonSupernova** [comment]
Im going to try getting without using my package manager, and maybe i can get a more up-to-date version than openjdk8
