### ISSUE TITLE
Inactive sector defense calculations do not match outcome when active

### ISSUE THREAD

**Issue by EricD112** [Anuken/Mindustry#5944]
**Platform**: Windows

**Build**: release build 126.2

**Issue**: Currently, when a sector is under attack while you are in a different sector, the calculations do not necessarily represent your defenses. While this is not really noticeable when fighting low-level waves, it can be really problematic later on.

In my save game, I have lost both the "Nuclear Production Complex" and the "Impact 0078" to the enemy repeatedly while concentrating on other sectors. In both cases I had reached wave 200 without any issues, but I lost them while being away at much earlier waves (e.g. wave 135). So the calculations seem to be grossly underestimating my defensive power.

This isn't game breaking, but can be really annoying when having multiple sectors under attack, as you have to keep cycling which sector you play actively.

**Steps to reproduce**: In my save file, the "Impact 0078" is in a state where it should fall with the next set of waves (might take longer, hard to say), but would hold if viewed actively.

**Link(s) to mod(s) used**: This is a vanilla save.

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/7112353/saves.zip)—I saw a few issues like mine which never included a save file, so I hope this helps.

**(Crash) logs**: No crash.

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Passive wave calculations will always be more or less inaccurate, based on the situation.

**Comment by oinkymoo** [comment]
my suggestion is to read up on how the system works and take advantage of that to gain extra defensive power

**Comment by EricD112** [comment]
Would it be possible to give players the option to have sectors which are under attack be calculated actively, as if the player was present? Keeping it off by default would have no negative effect on low end machines, yet allow people with high end machines to get the accuracy they desire. The current system makes it frustrating to keep losing sectors you *should* keep.

**Comment by Anuken** [comment]
No, that is impossible. Mindustry is fundamentally incapable of running two worlds at once.

**Comment by begginerr** [comment]
i guess even if it could, it would use too much info just to fix this 1 problem
