### ISSUE TITLE
factory bug

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5945]
**Platform**: any

**Build**: 130.1

**Issue**: Use unloader and overdrive projector, the last one raw item in the factory won't be consumed. The factories that require 1 item have this bug, such as cryofluid mixer, blast mixer(1spore 1pyratite), spore press, melter.

**Steps to reproduce**: Watch the video.

https://user-images.githubusercontent.com/45112661/132165274-908bfd62-fca5-40e0-8fc7-500705f247e8.mp4

--

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed in the BE.
