### ISSUE TITLE
The animation of mender?

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5946]
**Platform**: Android

**Build**: 130.1

**Issue**: Add items to mender, the color of the rectangle animation won't be yellow. Is this a bug?
v6:
![2021-09-06 19 55 13](https://user-images.githubusercontent.com/45112661/132214209-dbbe077c-3f2a-43e8-a76c-e4b2a2a3193c.jpg)

**Steps to reproduce**: Build a mender and add enhancement item to it.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LtMZ1** [comment]
![image](https://user-images.githubusercontent.com/87947799/132215761-6f31f32a-7cdb-470e-b129-d6d1f419ebae.png)

**Comment by Hexrotor** [comment]
ok
