### ISSUE TITLE
Maybe should hide these UI

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5952]
**Platform**: android

**Build**: 130.1

**Issue**: I think these ui should be hidden when launching the core.
![e3b004b926974b278ec30c9a6d02b247](https://user-images.githubusercontent.com/45112661/132351544-59c409a3-e46a-44ad-b138-4cbafdf75306.jpg)
![f4b691e383c64f6f8f6f16e7933df290](https://user-images.githubusercontent.com/45112661/132351602-ce23d617-49eb-4696-8ec1-f3fde1cd6c7d.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not really a bug, no other UI is hidden.

**Comment by Hexrotor** [comment]
> Not really a bug, no other UI is hidden.

what, I just mean this, this doesn't look good ._.
![1631022043960](https://user-images.githubusercontent.com/45112661/132355867-11eed994-d9ab-42c5-818d-c8df36ceae40.jpg)

**Comment by Hexrotor** [comment]
Oh no :(
![GIF-210907_221156](https://user-images.githubusercontent.com/45112661/132360278-6eeda9a7-03fc-47d4-8f35-a6c53f4cde8e.gif)
