### ISSUE TITLE
Turrets suddenly stopped shooting despite having ammo

### ISSUE THREAD

**Issue by KnightGabriel** [Anuken/Mindustry#5955]
Platform: Windows 10

Version: Alpha Build 130.1

Issue: After the technical issues I had with the linux version of the game, I decided to get the game for windows, and so far I haven't had the glitch. But now there's another issue: My turrets have all of a sudden stopped shooting entirely. They have full ammo and everything, but they won't work at all. The only 2 mods I have are "Hackustry" and "Unit information", but I don't have any hackustry cheats enabled. And everything was working fine for a while no matter what hackustry cheats I had enabled. they just suddenly stopped shooting.

Steps to recreate: I don't know how to deliberately cause this, just go into a game and put some turrets down, then wait 

Mod links: https://github.com/QmelZ/hackustry, https://github.com/Sharlottes/UnitInfo

Save: sector-serpulo-170.msav

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Saves are mandatory, and you have not attached one.

**Comment by KnightGabriel** [comment]
@Anuken oh I'm sorry I didn't know you meant attach the file, lemme figure out how to do it. Also a temporary fix is to sell the turrets and put them down again, but still.

**Comment by KnightGabriel** [comment]
@Anuken there

**Comment by Anuken** [comment]
Your turrets have reload set to NaN. This is very likely to be [an issue with Hackustry](https://github.com/QmelZ/hackustry/blob/master/scripts/features/v3.js#L42), as it directly assigns turret reload to 0 here, which is not a valid value. Don't use this mod.

**Comment by KnightGabriel** [comment]
What's NaN? How do I disable it

**Comment by Anuken** [comment]
Disable the mod and rebuild the turrets.

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose

**Comment by begginerr** [comment]
> What's NaN? How do I disable it

i know it has been 11 days, but if you wanna know, NaN means Not a Number
