### ISSUE TITLE
Inexplicable interpolation crashes

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5958]
**Platform**: *Android*

**Build**: *BE 21828.*

**Issue**: *My Fearless unit crashes upon death. I have checked, and my HJSON is proper. The only cause I can find is the new sizeInterp field.*

**Steps to reproduce**: *Kill a Fearless.*

**Link(s) to mod(s) used**: 
[exotic free no virus](https://github.com/Anuken/Mindustry/files/7125697/BlueWolf3682Exotic-Mod1.zip)
***THIS SPECIFIC MOD FILE IS REQUIRED.***

**Save file**: *[aaa.zip](https://github.com/Anuken/Mindustry/files/7125705/aaa.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *[crash_1631072499238.txt](https://github.com/Anuken/Mindustry/files/7125714/crash_1631072499238.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
The issue is 
https://github.com/Anuken/Mindustry/blob/dd7062f0f798845c5e4c2b468bee5e4cea0a33b5/core/src/mindustry/entities/effect/ParticleEffect.java#L24
You put a @Nullable where it cannot be null.

**Comment by Anuken** [comment]
> You put a @ Nullable where it cannot be null.

It *can* be, check the documentation above. The real problem is that `init()` is not called for particle effects when they are part of a MultiEffect.
