### ISSUE TITLE
Continuous lasers don't have lighting support

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5959]
**Platform**: *Android*

**Build**: *same as last issue.*

**Issue**: *Comically large continuous lasers don't have enough lightRadius.*
![Screenshot_20210908-000324](https://user-images.githubusercontent.com/61173114/132457319-28ab3db3-3229-40ac-bafd-6fd4fc12b75b.png)

**Steps to reproduce**: *Fire Fearless' main weapon.*

**Link(s) to mod(s) used**: 
*[exotic free no virus fearless working](https://github.com/Anuken/Mindustry/files/7126395/BlueWolf3682Exotic-Mod1.zip)*
***THIS IS, AGAIN, REQUIRED. DO NOT TEST THE PREVIOUS ISSUE WITH THIS ZIP, AS I MANUALLY FIXED THE FEARLESS UNIT.***

**Save file**: *Use the same save as last issue.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
~~Modify `lightStroke`. Or does that not work?~~
![image](https://user-images.githubusercontent.com/54301439/132458138-f24396ac-4ea8-4ab2-ae44-0c83f9457388.png)

**Comment by BlueWolf3682** [comment]
I'm an idiot. 
Though it's strange that it's not like non-continuous lasers, where it just defaults to the width * an amount.

**Comment by MEEPofFaith** [comment]
¯\_(ツ)_/¯
