### ISSUE TITLE
really

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#5960]
**Platform**: *Android*

**Build**: *21831*

**Issue**: 
![Screenshot_20210908-103501](https://user-images.githubusercontent.com/61173114/132549494-68d8af43-f7ed-49de-bb20-796efa515f99.png)
I swear if you say my team sprite colours are incorrect... They are correct as of a couple months ago and if they aren't anymore, I don't want to bother fixing them.

**Steps to reproduce**: *n*

**Link(s) to mod(s) used**: *Use the same file from last issue.*

**Save file**: *
[really](https://github.com/Anuken/Mindustry/files/7130446/really.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *n*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> I swear if you say my team sprite colours are incorrect... They are correct as of a couple months ago

Actually, they were always incorrect. Here's why: A few months ago, all "colored" teams did not have generated palette regions. This means that every team region was just rendered with a tint - nothing was generated. Incorrect colors did not show up, because only two teams had palettes, and you already have override regions for those.

When I added palettes for colored teams, this palette issue became obvious, because you don't have overrides for those.

If you examine the color hex codes, you'll see that they do not match vanilla core sprite colors.

**Comment by BlueWolf3682** [comment]
After examining the two darker colours on the team sprites that my blocks use, I can confirm that the base team sprite for my blocks uses the *exact* same hex colours.
(ffffff, dbc5c5, 9e8080)
Failure to generate the team sprites off of this is not caused by the base team sprite's colours being incorrect, because they are not.

**Comment by Anuken** [comment]
> After examining the two darker colours on the team sprites that my blocks use, I can confirm that the base team sprite for my blocks uses the exact same hex colours.

> 9e8080

Aseprite doesn't agree:

![image](https://user-images.githubusercontent.com/10100000/132568866-b31beb92-d5da-4506-9a3f-ab9d79635c28.png)

It's 1-off, possibly due to loss of precision or floating point rounding error in the editor you're using.

**Comment by BlueWolf3682** [comment]
I can't fix that.
Implementing a manual fix, but leaving this issue open.
![Screenshot_20210908-130823](https://user-images.githubusercontent.com/61173114/132570212-7775af73-e187-491b-b640-dc77c5abe1cd.png)

**Comment by Anuken** [comment]
It's faster for me to allow for the "wrong" color to be used in the palette, so I'll add it.
