### ISSUE TITLE
Searching in Core Database causes unwanted scroll bar to appear.

### ISSUE THREAD

**Issue by cigarmemr** [Anuken/Mindustry#5965]
**Platform**: Windows

**Build**: steam build 130.1

**Issue**: A scroll bar shows up when searching by keywords in Core Database, even if there are no necessity to use them. Check the screenshot below:
![image](https://user-images.githubusercontent.com/26317456/132606332-08642e21-9d91-4096-b292-4aff390bd3f4.png)
The scroll bar also relocates after typing or deleting characters in the textbox.

**Steps to reproduce**: 
1. Enter the Core Database by clicking Database - Core Database from the main menu.
2. Filter the items by enter some characters. In this case, "swi" to find Switch.
(Note: Not all searching keywords are responsible. Based on some test, only the keywords resulting few number of items may result the issue.)
3. Check the appearance of the searching result.

**Link(s) to mod(s) used**: None.

**Save file**: Not related.

**(Crash) logs**: Not related.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/132608762-52724889-1ad5-43b6-8ec9-3d37379e7663.png)


Cannot reproduce. In any case, this is a problem of no practical significance, as the block is still very much clickable.
