### ISSUE TITLE
Color in menu

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#5966]
**Platform**: *Any*

**Build**: *130.1*

**Issue**: *[accent] color in menu header and the same color in text looks different.*

**Steps to reproduce**: *Make a plugin with Call.menu().*

Just look on this screenshot. The same bug happens with any colors.
![IMG_20210909_141546](https://user-images.githubusercontent.com/79508138/132686095-d9741ce8-2650-49ed-ac08-9593d842b9fa.jpg)

**Comment by Darkness6030** [comment]
If it isn't a bug, just close my issue

**Comment by Anuken** [comment]
The menu header is already colored with [accent, you're applying the color twice.]
