### ISSUE TITLE
Core launch animation caused export speed decrease

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#5974]
**Platform**: any

**Build**: 130.1

**Issue**: If I launch from an unloaded sector A to a new sector B, the game will load A first then play the launch animation and exit to load sector B. The time in sector A is very short, so if this sector is exporting rescources, the game will record a very low export speed, even zero. I think this time does not calculate the export speed will be better.(or other way to solve this, i don't know)

**Steps to reproduce**: Open the campaign and do what I described.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by Hexrotor** [comment]
OK, Im so sorry Anuke, I just think this problem is caused by the game animation mechanism, and I don't realize that it needs a save, sorry.
[save.zip](https://github.com/Anuken/Mindustry/files/7148112/save.zip)

Example: Use my save. First, don't go to any sector, find the sector Extraction Outpost in planet map(don't enter it, just see its infos), it shows:
![Screenshot_2021-09-11-23-51-09-1](https://user-images.githubusercontent.com/45112661/132954080-64f39695-7419-4cf2-aec2-05a62723b5ce.jpg)

After that, find the sector 14, click the launch button directly, then game will load sector Extraction Outpost first to play the launch animation, then load sector 14. When the core lands, open planet map again, find the sector Extraction Outpost, it shows:
![2021-09-11 23 53 44](https://user-images.githubusercontent.com/45112661/132954257-2a2efd69-f77d-4334-9f8a-84859a739f89.jpg)

So you will see that the export and production speed decreased.(even to 0)

**Comment by Anuken** [comment]
> save.zip

That's not a valid link, it's 404.

> I don't realize that it needs a save, sorry.

It happens in-game, so it is required. I cannot reproduce this issue with my own sector exports.

**Comment by cigarmemr** [comment]
Based on some discussion, we've got a proper procedure that might be able to stably reproduce the issue:
1. Make sure the Disable the Core Launch Animation option is disabled (Allow the animation to play).
2. Enter the Campaign freshly before loading any one of the sectors.
3. Pick a sector A and a suitable sector B which can be launched directly from A.
4. Record the item export rate of sector A by check the sector detail information.
5. Launch from A to B, there is a small time window for the game to load and play the animation inside A.
(Alternative: Enter sector A and exit quickly.)
6. Repeat step 4 to check again the new export rate data.

**Comment by Hexrotor** [comment]
aaaaa sorry, by the way I'm using Android BE build 21848, and my friend successfully reproduced this problem. The root of this problem is the staying time on the map, it is too short, so you know...
[save.zip](https://github.com/Anuken/Mindustry/files/7148181/save.zip)

**Comment by Hexrotor** [comment]
> The root of this problem is the staying time on the map, it is too short,

See my play time in my pictures, only 2 sec I stayed in the sector last time, just because the game loaded this sector to play the core launch animation, and exited quickly :(
