### ISSUE TITLE
Game data loss

### ISSUE THREAD

**Issue by Nghongzhan** [Anuken/Mindustry#5983]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: Game data loss due to computer system crash.

**Steps to reproduce**: On yesterday evening,I'm still playing the mindustry.And in the sudden, my computer crash due to unexpected reason.

**Link(s) to mod(s) used**: `none`

**Save file**: 
[sector-serpulo-227.zip](https://github.com/Anuken/Mindustry/files/7150706/sector-serpulo-227.zip)

**Crash report**: 'none' *(did not receive any crash report in game)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Use v7.

**Comment by Nghongzhan** [comment]
emmm,I'm sorry that I did not really know what do you mean by v7. May you explain a bit more?

**Comment by Anuken** [comment]
Use Mindustry v7, and read the issue template.

**Comment by Nghongzhan** [comment]
I have updated to v7, and the data is still not fix. So is assume that the issue is unable to fix is it?

**Comment by Anuken** [comment]
v7 will not bring back your data, as it was already overwritten, but it will make it very unlikely that your data will be lost again.

**Comment by Nghongzhan** [comment]
ok,thanks for the help~

**Comment by SMOLKEYS** [comment]
> ~

*very heavy breathing*

**Comment by Rex-Hm** [comment]
lol
