### ISSUE TITLE
package android.annotation does not exist

### ISSUE THREAD

**Issue by linsui** [Anuken/Mindustry#5995]
**Platform**: *Android*

```
> Task :android:compileStandardReleaseJavaWithJavac
/home/vagrant/build/io.anuke.mindustry/android/src/mindustry/android/AndroidRhinoContext.java:3: error: package android.annotation does not exist
import android.annotation.*;
^
```

The log is in https://gitlab.com/linsui/fdroiddata/-/jobs/1588849871. Could you please take a look? Thanks!

**Comment by linsui** [comment]
Thanks for you quick fix! But I'm afraid that F-Droid can't build it since it downloads jars from github. :(

**Comment by licaon-kter** [comment]
Where's the source for this

**Comment by licaon-kter** [comment]
F-Droid builds from source, in the commit above you mention some magic `.jar` files coming from a mysterious land? Where's their source... :)

**Comment by Anuken** [comment]
> you mention some magic .jar files

That's the Android API jar, taken from the Android SDK platform directory.

Does it really matter where the source is, when the JAR is not included in the output? It's marked as `compileOnly` in Gradle. All the Android SDK classes are stubs.

**Comment by linsui** [comment]
I thought we can copy the android.jar from SDK when building it. But that's a weird workaround. Why that's needed? We need to build Anuken:robovm:robovm-gradle-plugin-2.3.14-SNAPSHOT.

**Comment by Anuken** [comment]
> But that's a weird workaround. Why that's needed?

Downloading a specific JAR is more reliable, since it won't break when I change the target platform version, and a misconfigured SDK won't cause problems. But if it's really necessary, I can change it to the specific SDK platform directory.

> We need to build Anuken:robovm:robovm-gradle-plugin-2.3.14-SNAPSHOT.

Why? That's not even related to the Android submodule, and as of the latest commit, I don't need it anymore, since RoboVM made a release with the patch.

**Comment by linsui** [comment]
> Downloading a specific JAR is more reliable, since it won't break when I change the target platform version, and a misconfigured SDK won't cause problems. But if it's really necessary, I can change it to the specific SDK platform directory.

We can patch that for F-Droid only, e.g. a flavor. But I still wonder why the jar is needed.

> Why? That's not even related to the Android submodule, and as of the latest commit, I don't need it anymore, since RoboVM made a release with the patch.

That's great! Then we can just remove it before building.

**Comment by linsui** [comment]
Well, the apk builds fine but we don't allow debugable build...

**Comment by Anuken** [comment]
> we don't allow debugable build

That is necessary for mods to work properly. `debuggable = false` breaks default interface desugaring.

**Comment by linsui** [comment]
I know it's a workaround. Maybe this should be reported to Google to fix it properly.

**Comment by Anuken** [comment]
Update: I am now able to remove `r8` shrinking from the build process entirely, so `debuggable = true` will no longer be necessary next release. (These changes have not been pushed yet.)

> Maybe this should be reported to Google to fix it properly.

~~Note that I did try to consult the r8 docs and tweaks the properties, but I got the impression that this just wasn't a supported use case. A lot of stuff r8 does isn't very configurable.~~
