### ISSUE TITLE
Falling wrecks don't seem to be killable.

### ISSUE THREAD

**Issue by konstantys** [Anuken/Mindustry#5996]
**Platform**: Windows

**Build**: 131

**Issue**: The change introduced in build 127.2 which made falling wrecks killable either doesn't seem to be working or it isn't working properly. I have conducted a test that most likely proves that this is the case, inspired by the fact that i have never observed this change to actually apply to my game experience.

**Steps to reproduce**: Open the map I attached to this bug report in sandbox mode. Make a zenith with the payload source and approach the structure at top (without shooting). The junctions in the structure do get destroyed, even though the amount of firepower provided should be way more than enough to prevent this.

**Link(s) to mod(s) used**: I used foo's client. Also tested the issue with the Time Control mod https://github.com/sk7725/TimeControl in order to confirm that what i thought to happen was actually the case, but same thing happens without the mod installed.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[bugreport.zip](https://github.com/Anuken/Mindustry/files/7162619/bugreport.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![2021-09-14-10-26-36](https://user-images.githubusercontent.com/10100000/133276265-2c520f23-8873-4cca-9ca1-7070a4df4784.gif)

The wreck never gets destroyed, because turrets do not target dead units. It never gets damaged. I have seen wrecks killed by turrets countless times, so it is definitely working correctly.

**Comment by Anuken** [comment]
It's not intended for use with logic. The idea is to immediately destroy small unit wrecks as they are falling on active defenses attacking other units.

**Comment by konstantys** [comment]
> It's not intended for use with logic. The idea is to immediately destroy small unit wrecks as they are falling on active defenses attacking other units.

Waaait. "Small" unit wrecks? It doesn't apply to zeniths? Also, by not intended, do you mean that it's made so that it isn't possible or that this wasn't the inspiration for this feature?

**Comment by Anuken** [comment]
> It doesn't apply to zeniths?

Zenith wrecks have more health and appear in smaller numbers, and are thus less likely to be killed.

> do you mean that it's made so that it isn't possible or that this wasn't the inspiration for this feature?

The latter.
