### ISSUE TITLE
Community servers dont show up

### ISSUE THREAD

**Issue by logicminimal** [Anuken/Mindustry#5998]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

6.0 Build 126.2 (Probably) (got from itch.io)

**Issue**: *Explain your issue in detail.*

Community servers tab being blank while it has to contain some servers, it works on androıd, one thing that might change stuff is that im currently using usb tethering with mobile data to connect to the internet, but i highly doubt

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i literally just installed & started the game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
yes but it seems to have been solved in that issue through a commit but im still experincing this problem? #3784

**Comment by Anuken** [comment]
Cannot reproduce, there's very likely something wrong with your connection.

**Comment by logicminimal** [comment]
ok i tried it again and it works

**Comment by SMOLKEYS** [comment]
> ok i tried it again and it works

Common issue. Sometimes the community servers refuse to show up.
