### ISSUE TITLE
Can't view building info if Deselect is bound to Mouse Left

### ISSUE THREAD

**Issue by FnControlOption** [Anuken/Mindustry#6002]
**Platform**: Windows

**Build**: 7.0 Build 131

**Issue**: Can't view building info if <kbd>Deselect</kbd> is bound to <kbd>Mouse Left</kbd>

**Steps to reproduce**:

1. Open `Settings > Controls` and rebind <kbd>Deselect</kbd> to <kbd>Mouse Left</kbd>
2. Select a building and try clicking <kbd>?</kbd> (doesn't work)
3. Reset <kbd>Deselect</kbd> to default binding, <kbd>Mouse Right</kbd>
4. Select a building and try clicking <kbd>?</kbd> (works)

**Link(s) to mod(s) used**: n/a

**Save file**: I think you can reproduce this on any save file, but if not, please tell me. (I don't know how to find my save file)

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by FnControlOption** [comment]
This is the button I'm trying to click:

![mindustryCapture](https://user-images.githubusercontent.com/70830482/133358428-3429c865-a651-446f-929d-bb9be4a184a1.png)

**Comment by firstcreator48** [comment]
> This is the button I'm trying to click:
> 
> ![mindustryCapture](https://user-images.githubusercontent.com/70830482/133358428-3429c865-a651-446f-929d-bb9be4a184a1.png)

ok but ur making the task (clicking the info button) impossible yourself by rebinding deselect to mouseLeft not leaving it as mouseRight

**Comment by Anuken** [comment]
See comment above.
