### ISSUE TITLE
I don't know why, I don't know how.

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#6005]
Template is gone due to the fact that this crash log was sent to me without any information myself. I cannot provide a save file.

Apparently leaving a SolidPump attribute field as null crashes the game. 

My best guess is the person placed the block(which is Exotic's Energia Borer) or loaded it in a save that I don't have, and the game crashed.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

I understand but can't provide one 

**(Crash) logs**: 
[unidentified flying crash log](https://github.com/Anuken/Mindustry/files/7173735/crash-report-09_16_2021_06_49_09.txt)

If you need a save or a solid means of reproduction, notify me and I'll try to reproduce it myself.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is actually a crash in UnitInfo, not Mindustry. [It doesn't check for null attributes.](https://github.com/Sharlottes/UnitInfo/blob/master/src/UnitInfo/core/BarInfo.java#L209)
