### ISSUE TITLE
Console error color

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#6006]
**Platform**: *Server*

**Build**: *131*

**Issue**: *The error color is broken.*

**Steps to reproduce**: *Use **nextmap "incorrectmap"** command in console.*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Here is the screenshot:
![IMG_20210916_114518](https://user-images.githubusercontent.com/79508138/133581533-ec76a8ff-f5b1-4372-bd21-a24554589f85.jpg)

**Comment by Darkness6030** [comment]
I think is is an error in arc.util.Log formatter

**Comment by Quezler** [comment]
https://github.com/Anuken/Mindustry/issues/3585

**Comment by Darkness6030** [comment]
Uh

**Comment by Darkness6030** [comment]
Bunwhynit can't be fixed? 👀

**Comment by begginerr** [comment]
> But why it can't be fixed? 👀

good question
