### ISSUE TITLE
No audio output on Linux

### ISSUE THREAD

**Issue by Magolor44** [Anuken/Mindustry#6015]
**Platform**: Arch Linux

**Build**: Steam build 126.3

**Issue**: I don't have any sound output and pulse audio seems to not recognise Mindustry as a program with sound output.

**Steps to reproduce**: Well it happened directly after I opened the game for the first time and there was no sound so there are none.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce or fix this. Audio works correctly on my Ubuntu system. I've tried many different audio backend configurations, and the current one is the most stable - audio is just problematic on Linux in general.
