### ISSUE TITLE
cant play "naval fortress" sector

### ISSUE THREAD

**Issue by OverHeaven439** [Anuken/Mindustry#6024]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 8.1

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
21903

**Issue**: *Explain your issue in detail.*
i cant play the naval fortress sector beacuse it was created on a sector i had already conquered

what can i do to play the intended naval sector?

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
today i wanted to conquer some campaign sectors and noticed that there were 2 named sectors i hadn't beaten yet (coastline and then naval fortress).
i cleared the first one but when i exited the sector to look at the map it didn't show me where the second sector was
so i looked the sector up in the sector list and i realized it spawned on a sector i conquered before v7 (or maybe before those 2 sectors were added), sector #216 (difficulty: easy - resources: copper lead scrap sand water).
then i loaded the sector that naval fortress was supposed to be (not launched to it, just went to it) and it was just like i left it, a few drills, some duos and walls.
so i destroyed my base using the console with the command "Groups.build.each(b=>b.kill())" hoping that by re-launching to the sector in question the map would change and i could play on it.
the sector loss sector popped up as usual and i created a backup save just in case anything weird could happen.
i launched the sector but the map didnt change, and it certainly didnt look like a extreme threat sector with naval units since there werent even coal, titanium or thorium ores and just a few water pools here and there.

the sector after i destroyed the base using the console
![](https://cdn.discordapp.com/attachments/477494303061442571/889118797246640129/unknown.png)

the sector when i re-launched to it
![image](https://user-images.githubusercontent.com/85291222/133933311-35ffa9a5-e036-4ba9-82df-d6dc3acbb123.png)

sector map
![image](https://user-images.githubusercontent.com/85291222/133933325-11be8a4c-ab95-4836-9d7e-8aaa60c2a573.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
i dont think mods are related to this issue, but here are the ones i use
![image](https://user-images.githubusercontent.com/85291222/133934037-f5786c01-3043-4b65-838a-9518726c6879.png)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
my save file is too big (47103 KB) and github doesnt let me upload it so please tell me how can i send it

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
not needed
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> i cant play the naval fortress sector beacuse it was created on a sector i had already conquered

The map is already there, the save exists, you can't play it anymore. This isn't a bug. If you really want to play it, delete your save for that sector.

**Comment by OverHeaven439** [comment]
How do i delete the save for that sector?

**Comment by Anuken** [comment]
Open your save folder and delete the files with the right sector IDs (108, 216).
