### ISSUE TITLE
Modded Message Block text getting limited when print using processor

### ISSUE THREAD

**Issue by vinhsad** [Anuken/Mindustry#6025]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Window 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
v7 build 131
**Issue**: *Explain your issue in detail.*

https://user-images.githubusercontent.com/43229798/133944513-9ca96150-a83f-466f-878f-18d3364ef1f8.mp4
as you can see, the left message block is writed in by hand
and the right one is writed by a processor, it getting limited to the normal message text size
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1.use a modded message that have more text than a normal message
2.use logic print command on the message
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---<none>

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Template.
