### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Victoirepointthree** [Anuken/Mindustry#6048]
**Platform**: Windows
**Build** : 126.2
**The problem is that every time you go to the first map or the ones next to it, the whole tutorial restarts, which is not a big deal in itself, but it's very annoying...
**I'm not sure if I'm going to be able to do this, but I'm sure I'll be able to do it again and again.
**Link(s) to the mod(s) used ** : none
**I'm not sure if it's the same one or not, but I'm sure it's the same one, so who cares?
- I updated to the latest version (https://github.com/Anuken/Mindustry/releases) to make sure my problem hasn't been solved .X

Sorry for my bad english...

**Comment by oinkymoo** [comment]
you need a save file

**Comment by oinkymoo** [comment]
also the latest version is the 131 pre-alpha

**Comment by Anuken** [comment]
Save not attached, cannot reproduce.
