### ISSUE TITLE
mass driver doesnt rotate correctly

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#6049]
**Platform**: android

**Build**: 21925

**Issue**: mass driver doesnt rotate correctly, notice the right one.

https://user-images.githubusercontent.com/45112661/134789396-50c37bd8-54ff-49b4-a1ea-50d4cb762926.mp4

**Steps to reproduce**: I tried but I cant reproduce it in other maps, it only happens in my campaign sector 223 at (172,157)

**Save file**: 
[save_be.zip](https://github.com/Anuken/Mindustry/files/7230538/save_be.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
It probably isn't a bug

**Comment by Darkness6030** [comment]
Mass driver is kinda cursed

**Comment by Anuken** [comment]
I don't care about minor visual problems like this.
