### ISSUE TITLE
Android build error:Could not resolve all files for configuration ':android:androidApis'. Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}. Execution failed for MockableJarTransform: D:\DevSoftwares\android-sdk-windows\platforms\android-30\android.jar.

### ISSUE THREAD

**Issue by wangchezheng** [Anuken/Mindustry#6056]
**Platform**: *Android/*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: *Explain your issue in detail.*
Could not resolve all files for configuration ':android:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: D:\DevSoftwares\android-sdk-windows\platforms\android-30\android.jar.

**Comment by Anuken** [comment]
I can't reproduce this.

**Comment by wangchezheng** [comment]
Thanks for you reply, I resolve it
It's AGP with gradle version issue.
Happen issue, AGP version:7.0.2,gradle version:7.2
Fix version, AGP version:7.1.0-alpha01, gralde version:7.2

**Comment by sdancer75** [comment]
> 

Does this depend on the JSDK version? How can possibly should I know the AGP version versus Gradle Version?

I am on Android Studio 2022 and JSDK version 19.

**Comment by wangchezheng** [comment]
You can find this link and see which perfect.
https://developer.android.com/studio/releases/gradle-plugin
JSDK verison 19 is Ok

**Comment by sdancer75** [comment]
> You can find this link and see which perfect. https://developer.android.com/studio/releases/gradle-plugin JSDK verison 19 is Ok

Hi,

Thank you for your answer. Although I had the latest versions of AGP and Grandle which were compatible with JDK 19 it could compile in any way. I spent more than 12 hours trying to balance among AGP, Grandle, and JDK.

The solution was to install JDK 11 and make it JAVA_HOME setting AGP version 7.4.2 , Grandle version 7.5 and Compile SDK Version 33 Tiramisu
