### ISSUE TITLE
Steam version doesn't launch, leaves no crash logs.

### ISSUE THREAD

**Issue by cerega000** [Anuken/Mindustry#6067]
**Platform**: *Windows*

**Build**: Can't get to the menu to see a build number, but it happens in both stable v6 and beta v7 Steam builds

**Issue**: Steam version refuses to launch for me (shows playing for a second then stops). Game creates _/crashlogs_ folder but not crash logs themselves. _Weirdly enough build downloaded from Itch.io works with no problems._

What I tried:

- Verifying game files
- Replacing steam files with itch.io files
- Redownloading the game
- Switching to v7 beta version

Switching to v7 beta leads to the same result, except this time **game actually creates a crash log**. 

**Steps to reproduce**: Launch the game through Steam.

**Save file**: There's only a steam_autocloud.vdf file inside saves folder which is probably used for cloud saving, so most likely game didn't create any save files.

**Crash log from v7 beta**: 
```
Mindustry has crashed. How unfortunate.
Version: unknown build 0
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
<no mod init>

arc.util.ArcRuntimeException: File not found: version.properties (internal)
	at arc.files.Fi.read(Fi.java:199)
	at arc.files.Fi.reader(Fi.java:232)
	at arc.files.Fi.reader(Fi.java:224)
	at mindustry.core.Version.init(Version.java:30)
	at mindustry.desktop.DesktopLauncher.<init>(DesktopLauncher.java:59)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Verifying game files
> Replacing steam files with itch.io files
> Redownloading the game

If none of those steps worked, then something is *very* wrong on your system. `version.properties` is a core file needed for game initialization; there's no way it is missing from the game. I've never seen anyone else with this problem, and I can't reproduce it. Could be related to the way Steam launches the game, but I have no way of testing or fixing it.

**Comment by cerega000** [comment]
I actually figured it out!!! My steam folder has an exclamation mark in its name ("steam!!!") and it seems like java has problems with this particular character in the path..

**Comment by Anuken** [comment]
Looks like Java treats `!` as a special character when it comes to getting resources from the jar file.
