### ISSUE TITLE
sound glitching

### ISSUE THREAD

**Issue by memepeoples** [Anuken/Mindustry#6070]
**Platform**: *Android/iOS/Mac/Windows/Linux*
windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
version 131
**Issue**: *Explain your issue in detail.*
sound keeps randomly glitching out and playing the sound for removing or placing block and when i leave the server it goes away but it comes back again the second i rejoin.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
randomly keeps happening when i build/ delete stuff
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
haven't updated the mods that i use in a few months

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by memepeoples** [comment]
sorry forgot to mention that when the glitch happens i cant change how load it is in settings.

**Comment by Anuken** [comment]
I cannot reproduce this, and **you have not provided the required template information.**

**Comment by memepeoples** [comment]
the reason you didnt reproduce this could because sometimes it takes an hour or so to happen sometimes it happens after 5 mins of playing
