### ISSUE TITLE
Mechanical Pump problem

### ISSUE THREAD

**Issue by Satoshi-Yoda** [Anuken/Mindustry#6080]
**Platform**: Windows 10 x64

**Build**: Steam version 126.3

**Issue**: I completed several chained named missions ending with Fungal Pass. And now I stuck. No other named missions are open. Ruinous Shores need me to research Mechanical Pump, and I can not do it. I researched all available techs in Tech Tree, there is no Mechanical Pump available, checked twice. No, like 5 times =)

- As I remember from previous builds (back when the map was flat, couple years ago) at this moment I already had Mechanical Pump (maybe after The Craters? I am not sure), so this looks like a bug.
- And in Fungal Pass I have 2 working pre-build Mechanical Pumps, but after destroying enemy base no Mechanical Pump tech appeared, so looks like a bug.
- And I saw one question about "How to research Mechanical Pump?" somewhere in the internet, so, maybe it is not only my problem."

**Link(s) to mod(s) used**: No mods, plain steam version, restarted from scratch, no previous tech imported.

**Save file**: [mindustry-saves.zip](https://github.com/Anuken/Mindustry/files/7259490/mindustry-saves.zip)
That is zipped content of my `C:\_steam\steamapps\common\Mindustry\saves\saves`
If there is some other "saves" or something, I will happily provide them =)

**(Crash) logs**: No crash.

---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** No I did not, I used latest at the moment steam version 126.3
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** I did.

**Comment by Anuken** [comment]
You have attached your saves, which are not useful for solving the problem. I need your exported game data, which contains research.

**Comment by Satoshi-Yoda** [comment]
[mindustry-export-data.zip](https://github.com/Anuken/Mindustry/files/7259819/mindustry-export-data.zip)
That is zip generated from game when I click Export Data from menu. But it does not contains lot more useful except previous saves folder, settings.bin and some steam_autocloud.vdf

But, yes, you are correct about Metaglass from a Kiln, thanks =)
