### ISSUE TITLE
Couldn't open the mod browser thing.

### ISSUE THREAD

**Issue by xXSalimcuteyXxYT** [Anuken/Mindustry#6087]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3 and 131`

**Issue**: `One day, i was trying to play a mod with my friend when suddenly we encountered this, we tried closing and opening the game, it couldn't get off our sight.`

**Steps to reproduce**: `Don't know how, just found it by going into mod browser`

**Link(s) to mod(s) used**: `[[royal]sk7725[]/betamindy:1.05
[#b59e72]Demo of Chaos Itself[], dj king silicon, Saigo no-nozomi/music:1.2, DeltaNedas, Router and another guy/pictologic:1.5.7, pixecoz/schematics-pack:8, DeltaNedas/ui-lib:2.16.6]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure 
![unknown (39)](https://user-images.githubusercontent.com/66871785/135630195-c651cad6-5bcf-408e-bb2b-a04d39fd6ae7.png)
that this problem has not already been reported.**

**Comment by Anuken** [comment]
As it says, the request timed out. Your network can't connect properly.
