### ISSUE TITLE
crash to desktop after random amount of time

### ISSUE THREAD

**Issue by AlligatorScrublord** [Anuken/Mindustry#6088]
**Platform**: windows

**Build**: steam 126.3

**Issue**: any time i join my friend's multiplayer game, it goes just fine for a few minutes before crashing to desktop.

**Steps to reproduce**: just play for a few minutes apparently. the game was working fine yesterday, but today i joined my friend, hosting through steam from a few states away, and this is happening.

**Link(s) to mod(s) used**:

**Save file**: 
[crashreport.zip](https://github.com/Anuken/Mindustry/files/7270509/crashreport.zip)
my friend named the save crashreport before sending it to me

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
i read the line above before deleting, don't worry

**(Crash) logs**: [crash-report-10_01_2021_17_39_51.txt](https://github.com/Anuken/Mindustry/files/7270510/crash-report-10_01_2021_17_39_51.txt)
[crash-report-10_01_2021_17_41_16.txt](https://github.com/Anuken/Mindustry/files/7270511/crash-report-10_01_2021_17_41_16.txt)
[crash-report-10_01_2021_17_43_59.txt](https://github.com/Anuken/Mindustry/files/7270512/crash-report-10_01_2021_17_43_59.txt)
[crash-report-10_01_2021_17_49_31.txt](https://github.com/Anuken/Mindustry/files/7270513/crash-report-10_01_2021_17_49_31.txt)
[crash-report-10_01_2021_18_09_07.txt](https://github.com/Anuken/Mindustry/files/7270514/crash-report-10_01_2021_18_09_07.txt)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This issue is not relevant in v7.
