### ISSUE TITLE
Game randomly ends for no appearent reason

### ISSUE THREAD

**Issue by RussiaBo1** [Anuken/Mindustry#6091]
**Platform**: Android

**Build**: release build 126.2

**Issue**: My game keeps ending by showing the "Game Over" screen. I was playing a custom game and was able to reload multiple times to check if my cores were destroyed in any way (the map has 3 cores) and not a single one of them was destroyed by enemies or a thorium reactor (even though all 3 cores need to be destroyed in order to lose). 

**Steps to reproduce**: I was playing a custom game on a map I adapted personally for vanilla purposes from the Opore mod (name PvE Castle Defence). It may matter that, to balance the fact that I had no flying enemies I doubled enemy initial spawns and spawn rate increase, so I had more enemies than usual but I did have >1000 enemies another time on a modified Molten Lake and it worked just fine. The bug occured after wave 31 was beat but waves don't seem to matter as whenever I reload, it appears that there's an exact ammount of time until the game ends this not depending on wether you skip to wave 32 or not, it seems to be the same ammount of time until the game ends. I was also using Vanilla Enchanced, and on the map I had placed "Force Dome", "Mending Dome" and "Mini Overdrive". The mod adds no new materials or liquids. Speaking of the fixed ammount of time it takes to show the "Game Over" screen it does not count to this "Death Countdown" if the game is paused.  

**Link(s) to mod(s) used**: https://github.com/HolyHades/VanillaEnhanced , https://github.com/xamionex/Opore-Mod

**Save file**:https://github.com/Anuken/Mindustry/files/7271829/MindustryGameOverBug.zip

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I will not investigate bugs unless you can consistently reproduce them *without mods*.

**Comment by MEEPofFaith** [comment]
Please make sure that this is a bug with Mindustry and not related to a mod you have installed before creating an issue.

**Comment by BlueWolf3682** [comment]
That specific map has a thorium reactor next to a Core: Shard in the top center, next to the enemy spawn locations. This ends the map after a certain amount of time. This is not a bug, just Opore's map design.

**Comment by MEEPofFaith** [comment]
*w h e e z e*
