### ISSUE TITLE
Turret liquid boost issue

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#6094]
**Platform**: android

**Build**: 21967

**Issue**: Although water is exhausted, the turret does not use a cryofluid.

**Steps to reproduce**: Build a cryofluid mixer beside a turret, do this:

https://user-images.githubusercontent.com/45112661/135748804-e0d01023-eeaf-4dd9-9be3-f0e64aa62527.mp4

**Save file**: 
[save_be.zip](https://github.com/Anuken/Mindustry/files/7273093/save_be.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have a water extractor right next to it.

**Comment by Hexrotor** [comment]
> You have a water extractor right next to it.

I deconstructed it, see the end of the video

**Comment by Hexrotor** [comment]
> > You have a water extractor right next to it.
> 
> I deconstructed it

In the video about 24sec, the water ran out, but the cryofluid still not be charged into the turret until I built a duct

**Comment by begginerr** [comment]
the only reason that i can think of that can make this happen is that it says there is 0 water, but there is juuuuuust a bit of water still in there that can only be deleted by a conduit, not the cryo mixer

**Comment by Hexrotor** [comment]
> can only be deleted by a conduit, not the cryo mixer.

Not only the mixer, see this video

https://user-images.githubusercontent.com/45112661/135777664-585780be-0dbf-4d8b-8e7d-92882f19d3b9.mp4

Anuke how do you think about this

**Comment by begginerr** [comment]
now that plays with my brain, maybe same thing but with cryofluid??
