### ISSUE TITLE
Discord rich presence dosent work on Linux/Portable app version

### ISSUE THREAD

**Issue by lele92007** [Anuken/Mindustry#6097]
**Platform**: Linux

**Build**: Pre alpha 131

**Issue**:Discord Rich presence dosent work on linux

**Steps to reproduce**: i opened the game and checked dicord to see if it automatically added it. I also checked in a campaign map

**Link(s) to mod(s) used**: NA

**Additional insights** : https://discord.com/developers/docs/rich-presence/how-to , and i am using the Linux portable build on Ubuntu 20.04 LTS

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already fixed in BE, as far as I'm aware.

**Comment by buthed010203** [comment]
> This was already fixed in BE, as far as I'm aware.

Yeah, I introduced a bug a few months back and didn't notice I had done so until about a week ago lol
