### ISSUE TITLE
Inconsistencies in unloaders

### ISSUE THREAD

**Issue by seung882** [Anuken/Mindustry#6111]
**Platform**: MacOS, Windows, Android

**Build**: pre-alpha 131

**Issue**: Unloaders are not distributing correctly in certain conditions even though I don't think it is intended (as far as I know). It is also inconsistent and random, with some people in #designs getting the bug and other not. Reloading the map sometime fixes/breaks it. I first encountered it when attempting to unload sand into the kiln, and coal into the graphite press from the crucible while making a schematic in sandbox
**Steps to reproduce**: 
use certain null unloader setup
![image](https://user-images.githubusercontent.com/67698926/136170884-34acdb23-2f51-45a2-b940-2b934af4ab1b.png)
the unloader is only supplying sand to kiln, which is using 2 sand per second, leaving the unloader to have 9 coal per second to the graphite press, yet no coal gets into the graphite press. Sometimes, it works again after the kiln idles, even though unloader speeds are 11/s and the kiln was using 2/s.

Changing the unloader configuration from something else back to null fixes the issue, but sometimes it stops working again.
replacing the bridge on top of the unloader with an item source (or vice versa), sometimes fixes the issue (even though it has absolutely nothing to do with the coal transport).

video showing random stuff fixing the bug:

https://user-images.githubusercontent.com/67698926/136175022-db07d36c-a021-4d0d-8fba-72539f210479.mp4

It is very inconsistent, with some people having it, and other not and doing random stuff sometimes fixing the issue, because of this I doubt it's an intended feature.

**Link(s) to mod(s) used**: 
[time control](https://github.com/sk7725/TimeControl)
[max rate calculator](https://github.com/L0615T1C5-216AC-9437/MaxRateCalculator)
(both QoL mods)
although i doubt mods are relevant as it was tested on multiple devices with different mods and it still bugged out.

**Save file**: [map save](https://cdn.discordapp.com/attachments/754304267413880832/895229917061586964/unloaderarebugged.msav)

No crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by hortiSquash** [comment]
we all know unloaders are extremely broken
im still trying to change their code to make them load balance and fix some stuff but ... yeah.. issues

**Comment by Anuken** [comment]
Don't place unloaders next to multiple producers like this, they're not designed to magically balance all inputs and outputs across blocks. Unloaders have been "fixed" so many times that I'm not willing to do any further changes to their behavior.
