### ISSUE TITLE
Constant surges in the Fungal Pass sector

### ISSUE THREAD

**Issue by MegaInk** [Anuken/Mindustry#6119]
**Platform**: Windows

**Build**: Mindustry Pre-Alpha Build 131

**Issue**: Last night I wanted to capture the Fungal Pass sector and I did it without problems, I destroyed and the 2 cores and everything else and I stayed afk on my farm.
About 2 hours later it appears to me that they are invading me fungal pass and I thought it was only 1 time but it was a wave and I also did it without problems, then I continued afk but they invaded me again and it seemed something strange then in the Spanish discord they told me that it was a bug and to report it

**Steps to reproduce**: I don't have the slightest idea why it happened

**Link(s) to mod(s) used**: None

**Save file**: [MegaInk.zip](https://github.com/Anuken/Mindustry/files/7311598/MegaInk.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: [Errores.txt](https://github.com/Anuken/Mindustry/files/7311596/Errores.txt)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.*
*

**Comment by Anuken** [comment]
> I stayed afk on my farm.

As long as there is an enemy sector near your base, you will be attacked. This is not a bug. Do not AFK in sectors, it is a waste of time.
