### ISSUE TITLE
Core DB won't show effect entries

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry#6124]
**Platform**: *Windows*

**Build**: *131 (itch.io, latest)*

**Issue**: **

**Steps to reproduce**: *Play campaign , open core DB, try clicking on status effects*

**Link(s) to mod(s) used**: *None*

**Save file**: *Not required, because universal*

**(Crash) logs**: *Not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** (Itch.io release)
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Also please don't reap my soul

**Comment by Anuken** [comment]
![2021-10-09-08-53-53](https://user-images.githubusercontent.com/10100000/136658659-5e232f12-0b38-4589-b911-fd19e449a3c2.gif)

Unable to reproduce.
