### ISSUE TITLE
Jitpack builds h'd.

### ISSUE THREAD

**Issue by GglLfr** [Anuken/Mindustry#6132]
***Doesn't require any template since it's unrelated to gameplay***, just wanted to point this out real quick since I couldn't use the newer Mindustry binaries.

Checked on my [latest commit](https://github.com/Anuken/Mindustry/commit/758921c0777ecc5c0988c3a5001c728863c8b662), tried to update my Mindustry and Arc, but my Gradle stated that there were no artifacts found. At all.

When I looked up in the JitPack site, I found this:
![image](https://user-images.githubusercontent.com/63218676/136698640-fe1655a3-5c00-48dc-b2d4-0d13577ec5c4.png)

Went on a [random commit](https://github.com/Anuken/Mindustry/commit/603c871e6e51e31e5fd078af41eb5bcf222bc550), same thing:
![image](https://user-images.githubusercontent.com/63218676/136698850-a8e588c5-dd8d-4ba6-8c07-de8da26eb8e3.png)

Reading the error report, I looked up the history for `gradle.properties`, then went to [this commit](https://github.com/Anuken/Mindustry/commit/9dfb5888ec117ced14e82eb6c70bbe2b722dd2df) that's right before [this particular commit whose GitHub actions failed](https://github.com/Anuken/Mindustry/commit/4377eacfd53b64cfcfc86bac0a68842ca3ce40d5), and found this:
![image](https://user-images.githubusercontent.com/63218676/136698896-33b763bf-9e81-4f73-bd81-3018f59a8e21.png)

It was *(most likely, couldn't bother myself to test other commits since JitPack builds takes forever)* the last commit whose artifacts are successfully uploaded.
Hope you can fix this soon, and have fun.

**Comment by Anuken** [comment]
Fixed. JITPack appears to start another Gradle process *after the build* in the same folder with some outdated Java version, which incorrectly picks up the main build's `gradle.properties` that uses arguments Java 8 doesn't understand.
