### ISSUE TITLE
Boom due to large config object in buildPlan

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry#6138]
This issue is due to design, and the Template is hard to fill, use custom.
Version 131.
Cause: The `config` object in buildPlan transfer when sync snapshot.
But the `config` may be very large (like processor), which larger than the network can handle.
And its sync waste lots of bandwidth.
Snapshots about this:
![@3~595S%FIY6{BEGJJS8 _O](https://user-images.githubusercontent.com/15688938/136758114-915dfe2a-f183-4162-836d-7a592041a7b2.png)
As the snapshot shows, the sync data for one entity reaches 2000+ Byte. (Normally, it is about 100).
And cause client NetworkError like this.
![29BE6E52C10FB110827D342237FB2550](https://user-images.githubusercontent.com/15688938/136758360-97a185d9-2661-4262-b8a6-736ebcc35104.png)

Solution: Move out large `config` from snapshot, may create one packet and use it as reference.

**Comment by Anuken** [comment]
> As the snapshot shows, the sync data for one entity reaches 2000+ Byte. (Normally, it is about 100).

I am aware of this, but large sync packets rarely appear to cause problems on their own.

> And cause client NetworkError like this.

I've never been able to reproduce this; logging onto a server and putting a logic block with 2000 lines of code into your build queue doesn't trigger it.

> Solution: Move out large config from snapshot, may create one packet and use it as reference.

This is much easier said than done.

**Comment by way-zer** [comment]
Try this schemic, place in server all clientSnapshot will lost.
<details>
<summary>Code</summary>
bXNjaAF4nCWVPdOyiBWGfZ/dZGeSJn2aMChRaBABoUMQFAWRD0HYWRi+BAFRRBEsrFIls1XS5KtIl5+w1f6SlLub/Iw8z76nP8V1X3Pu0/tF7+2L3pelf4p7v/n6GkffcH75+9vvLoUfxr1fR3EdXo+X2/Fc9n770z++/fGP//rxr//+6S/f//Ddtz9896f//u0P//vzP3/8+/e9XxZ+EBd17+3rbz71vjrFde0nca/X+1XvY7781PsParyGnZjxTzExAE1+UQ6Ijc9KA6cOPVyUOwyPzls93t49o+bI8zPZTkuL5/U9NSXTY56rVTe050VQpsiUw6YvOGopvtW4XTzmziXr8nn/Sa8aE9/eBQlCyIKrqFQW1SCLoZP2mGbprrKmFHQGFF9qTlIodaCvJug2TeeFMSzOeVUWnfcKZj5zk7rlBJ0g2L7mB3Y2SRzMwa8siOWgjNT79eO2s7IX3xr8Xdov1sXbB+SnD8o8G9Fog710YtxBTQFFCm5u4Em+zD23mj7A8cWUtFSVlAbMi+wCVB4GbfbwHK2tweg4TQmWC0ZLLyYsY0rBM0fqGrCxnL2mNkBXYZe4sqorO+ujgWfvxVTLGQnmxopF1KUYOiO2iZztzsilaEjKxgOiuJiWCg8S6d3qAZBzF9VP+wGfUnC2sUhuqxnjkdW/JstZOxpZa9Iq9gOsfYLbqprylLFM3dUzuPBega6Z4IPxs0ulHszGLBfFZrLGokM5u88a/wpdYg9GrkrUDol6O6nVxdjOXn3KJAGfggTZvx3dChPVSbPAwvWUxPZtIcr9/DEuZ/0D/76BEkFhAXvxjCvL+iFRCo/DfVqbuNhublyCY781Vq3qdpyOuQPFekD8cDqfYfNFdOBRNH+NlI1KIM1x4z4wzs5pvHRGCUl3W0LjOMRGCjBwUdM2Ue0BHMKBMEABRBGQ2SS5sblz5GQ50t4+KH92uT88Za1IwCd3FcT41CdDcoKjeQFdNpcQvfAyO/YFXySUl33WOsNdOMfGExduwBfWwu/T8BaQuDO6ovUh62gD011zGDhShIwc5fhdVMzBqVrN7dAuryu2vr/GTxVlMnUhZa/9AFX7y1vlmYqhb2YyWWZCFktJEZyV4yK5bJ6Sx/SPeZnVyk5kEitZWcjSpx+6lpHgfYqAS/YwKyNXB9e+FaG7ojSd5F6v4JN9H/rd/d3l22eXt7hYOftMBnNYnYqgVcv8NN9S81tlbyCcRw2zuudnnSJ1behV3ABcHUDZr31lRWL1sbvJ47pkpcsY0fctNKCoelaI8fRVHlmjmNf3bPXoo1eCaEVqcW+v7yHHL69sYZPBNxLA6WIxW1DR4hL7pDfNPKZQ8NqeW0LQtuLIfx46YMgMI2K1efePh8fSGA2B9mwGacPurlPB1CG1w+uTfixC76GkydAIZ8daGHqnNqDfPig/3+V1DMdUJokbZQYCURcJOijTCBhsRI0CormJbmg4vlerdKhd1aUzAP0Rj+DZOAsleYlQmypc90+3skYuM6YGE3PKNp4vIpMJKrvtVUBHx8sxVGi7SSSo2qoaEE3qY0lHJTuvRntCPxuFGyanOwNZrXNYN4aVz57dMonrM4OyJ3MojQSWkYW5G6yL92j2qDoX5lPNpFu9gbIII2JNz7mWztG1WOD1go60AzALmpx+d/nFZ5cPlot5pbEXFfzc9sNYGOgJBmlDJerQyob8aLS5+Ka+z6cBEZ63/DXxi0wOxic2U4b6i7VYLztY0NYwlF3bkf7msRsSSeDgrUHCjKTjfarvE3XrUA/JpbO6j2FrGHKBsFTdapBKakF1bDjqRDsgswpMDdVYLAf0LdbP7eM4ADyRDAsneCQHMo19HVy6QB5rFwo7b507iWFSnY9xaUwRBzSqxurdXQ1SEEyT6YZz3z4of3ZJHez+WRvzwPtNnOaRN8iDandejUwx8bs8qqVQPi6gazkRinLVPYZt38eZssReAuryNl4STJaMVUVx4YqKBRT3L1YjvjzDh4iHYrEBVzsiye5GlWHoCmhqrPJaagNvW3DpQVBMVNXmiEYNr851viMjQD3vSG78ZNaQHafGqhTlYolsKIc6F7nJCK85nVjMte54G+BIbX1wC6NLLvfs0d9ex26jUK+J3YczhyZlTvt4lp9dTrLt8HnEkDLaeeWNoMBnfBZxXmv5BIG2nLPTizDRbnK2DXjEI5Cbsi9EJG5Cfjo7b/cscZOCHIYjyYdQg/Ejfr+4vI72e2GfB/fqOrDtrBQQ61LnWaVQ5YVjjXqtwyGhgcYkQD2AkZOSkV/kgddc+Xmnu11+QKT48P6tB+VsZQi23ViFGdXyqdrXz4b0BU1yr+RF5iFf4wSHe/B70U+711qanMHqPibFwmzd9z76qJ7PLudrZv6CJkHAoH3SSjMIIqJpchov1zimqGSnVpvnlr4zS7RM4ZQQ6lCd8EpirvLt/nmavQz6FEeeNggkWsrxFgEm4NN12XkNZzyg10LDUE7OmQl86jPZIbP3nHrjBff1LFPsIppX2wq72QidqiMleeDHxwFTWu2KHa26SEZtKPp4RLc7qx2W0MahmNuhoU6mCB+YJ2H4yHr5tMae7cGh2D5HtUDshbSmgYE9Rai26P0fOB/sfw==
</detail>

**Comment by Anuken** [comment]
Works locally... and on the IO servers. In any case, that's 1) trivial to fix if it's a problem (just take into account string size when truncating snapshots) and 2) is unlikely to be much of a problem in the real world, because nobody is going to accidentally go around pasting around chunks of message blocks with *random, hard-to-compress data*.

**Comment by way-zer** [comment]
message block is mare, but logic block is easy to come up with more than 100 lines

**Comment by way-zer** [comment]
I can't place in IO servers, Client is v134.1 steam version
Syetem is windows 10
![image](https://user-images.githubusercontent.com/15688938/140514714-42419864-8ab5-49eb-8ae3-c84cbf012716.png)

**Comment by Anuken** [comment]
It's probably something to do with different network configuration/hardware on your end.

**Comment by way-zer** [comment]
I try different servers and send this code to others, who said can't place.

**Comment by Anuken** [comment]
Yes, but again, see https://github.com/Anuken/Mindustry/issues/6138#issuecomment-961870883

**Comment by way-zer** [comment]
For big config (may larger than 100KB), may using another TCP packet to transfer?
