### ISSUE TITLE
Planet Constructor Params swaped

### ISSUE THREAD

**Issue by Sh1penfire** [Anuken/Mindustry#6155]
**Platform**: *Windows*

**Build**: *Mindustry-BE-Desktop-22038*

**Issue**: *
Planet Constructor Params have changed in order, causing a crash due to no such method error on mod content loading
*
![image](https://user-images.githubusercontent.com/73347888/137422395-f559c7ce-f2f3-4022-ac31-b8f9b435ce56.png)

**Steps to reproduce**: *
-install a mod which uses old planet constructor to create a new planet
-start up the game.
*

**Link(s) to mod(s) used**: **
https://github.com/Sh1penfire/Endless-rusting

**Save file**: *Unable to produce, crash happens the instant content loading gets to a mod's planet

**(Crash) logs**: 
[Uploading crash-report-10_15_2021_13_17_12.txt…]()
**

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug; I have made clear many times that the planet system **should not be used in mods** and will break in v7. Even if this is fixed, there are numerous other API changes that would make planets explode anyway.

**Comment by MEEPofFaith** [comment]
Planets be like:
***SPONTANIUM-COMBUSTUM!** That's s spell that makes the person to said it **e x p l o d e**.*

**Comment by Sh1penfire** [comment]
they didn't work so I forced them to work anyways
_proceeds to use planets-_
