### ISSUE TITLE
Copying a instruction with """ crashes the game 

### ISSUE THREAD

**Issue by luihum** [Anuken/Mindustry#6167]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
release v126.2

**Issue**: *Explain your issue in detail.*
Trying to copy a instruction with three double quotes crashes the game.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

On a processor:
1. add a print instruction 
2. type `"""`
3. copy instruction 
4. Mindustry.exe has stopped working

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* *None*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

*I'm on GitHub Mobile, so I'll just base64 the files and put them here.*

https://pastebin.com/8xfqfiNe I think
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
*in base64 pastebin*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** 
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Edit: apparently pastebin stupid so https://hastebin.com/raw/jopucovada

**Comment by Anuken** [comment]
Duplicate; already fixed in v7.
