### ISSUE TITLE
Payload Loader Inconsistency

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry#6168]
**Platform**: Android

**Build**: BE 22050

**Issue**: Payload Loader works on 3 x 3 liquid tank, but not 3 x 3 vault.

**Steps to reproduce**: 

Working with 3 x 3 liquid tank.
https://user-images.githubusercontent.com/88634312/137570692-5ea49dcd-8d47-4289-96a2-2feb0887b471.mp4

Not working with 3 x 3 vault.
https://user-images.githubusercontent.com/88634312/137570729-d4581fff-11df-42d1-aff1-dd5644dd0dd1.mp4

It would seem to me it should either work for both or work for neither.  Otherwise it's inconsistent since both are 3 x 3 blocks.

**Link(s) to mod(s) used**: Vanilla, no mods used.

**Save file**: 
[LoaderInconsistency.zip](https://github.com/Anuken/Mindustry/files/7356618/LoaderInconsistency.zip)

Did this in editor map, save is empty otherwise.

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hexrotor** [comment]
Actually payload loader/unloader can be even used for 4x4 block now.
![Screenshot_20211016-110354057_1](https://user-images.githubusercontent.com/45112661/137571442-462decde-3e89-491e-985f-fa4d5bbed90a.jpg)

**Comment by Odin580** [comment]
![Screenshot_20211015-220335](https://user-images.githubusercontent.com/88634312/137571437-51ea3424-a0e7-4c19-9814-f5848cec5028.png)

In case it wasn't obvious, same behavior with the Payload Unloader.  Works with the liquid tank, but not with the vault.

**Comment by Odin580** [comment]
@Hexrotor seems so.  Just tested it on thorium reactor, pushes it through too.  The difference is it doesn't try to load them up, it just immediately pushes it through.  On mine the loader gets 8 thorium into it and a little bit of cyro, before it ends up in the unloader (immediately after).

So I don't know what the intended behavior is here.  Didn't check if the same is happening with Impact.
