### ISSUE TITLE
Can’t find community server

### ISSUE THREAD

**Issue by jiahe2004** [Anuken/Mindustry#6175]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: *Can’t find community server*
![5681BD82-2562-43F6-871F-F47D518454CC](https://user-images.githubusercontent.com/71360856/137614112-042c9dae-19eb-419e-9faa-1198e6874aac.png)*

**Steps to reproduce**: *I didn’t do anything*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
@Mindusplayer778 this is a known bug. Please update to v7 pre-alpha build 132. It is fixed in v7.

**Comment by Anuken** [comment]
This isn't a bug; either Github is blocked in your country/network or your device is unable to fetch the list.
