### ISSUE TITLE
Conveyor Animation in modding is broken

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry#6223]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Window 10 
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
v7 pre-release build 133
**Issue**: *Explain your issue in detail.*
so i make a conveyor that require power in my mod
when it doesn't have anypower and no item on it, the animation still play
but when it doesn't have any power and (at least 1) item on it, it stopped the animation.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
make a modded conveyor that consume power in hjson
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
https://github.com/EclipseTheOldOne/Project-Scrap
https://github.com/EclipseTheOldOne/Industrial-Processing
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
https://drive.google.com/file/d/16L0UmJwdRGJ5GMpXmyf5n-Q22MvNNgBx/view?usp=sharing
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
okay.
**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---<none>

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> so i make a conveyor that require power in my mod

Powered conveyors are not supported.
