### ISSUE TITLE
Cross platform multiplayer "desync"

### ISSUE THREAD

**Issue by Rapidgame7** [Anuken/Mindustry#623]
Quote on quote desync because I couldn't find the right word.

I've got a 64 bit desktop computer and a tablet, both with Mindustry build 91.
The problem happens when both clients are in a server hosted by the computer.

From the computer's screen, everything's normal, with tablet's drone doing... drone things, but in the tablet's screen, the computer's drone is frozen in place.
That is to say, if I moved the computer's drone elsewhere, the tablet would not update its position for whatever reason.
The tablet's game seems to get when the computer's player places stuff around or shoots anywhere (bullets originate from wherever the tablet thinks the other drone is at, towards the right angle), and even when being attacked by the computer's drone (health just depletes with no effects), except for the computer's drone moving around or changing, er, forms.
Rejoining the server does update positions and whatever weird mech is the computer piloting, but only once.

**Comment by Anuken** [comment]
This is a very well-known bug; your tablet (probably) isn't receiving any UDP packets from the server. What is the exact version and make of the tablet?

**Comment by Rapidgame7** [comment]
My tablet's an Archos 70 Oxygen, using Android 6.0
The Kernel version is 3.18.22

**Comment by Anuken** [comment]
What happens if clear Mindustry from the app list completely (swipe it out-- **don't** just press quit), then try connecting to the server again? Does the desync persist?

**Comment by Rapidgame7** [comment]
I just opened the game on both devices and the server to test that out, and it started working properly all of a sudden?
I don't know what changed between 16 hours ago to now, but it seems to be working now.

Gonna see if I can make it die again though

**Comment by Anuken** [comment]
Yep, that's what I expected. It will only occur if you exit through the exit button and try to connect to a server after opening it again.
