### ISSUE TITLE
Several issues with updating block payloads(draw layers, power and more!)

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#6264]
**Platform**: *Windows*

**Build**: *134*

**Issue**: 
*Bonus points if you guess what this is*
![image](https://user-images.githubusercontent.com/58885089/139516619-88c4bf2d-9869-4bb5-93f3-7003d2d3c346.png)

1. "Special" layers are ignored, such as Layer.effect, bullet, shields and buildBeam. Thes layers should be processed as exceptions.
2. Non-turret power block keep their status in payloads; if it was powered when picked up by units/stuff, it keeps being powered on them.
3. some layers get squashed because of floating point imprecision when you map the `Draw.z`, as things like
```
Draw.z(Layer.effect);
//stuff
Draw.z(Layer + 0.001f);
//stuff
```
get drawn on the same exact layer due to floating point imprecision

**Steps to reproduce**: Place a force projector, powered, with a quad and yeet it on a payload conveyor.

**Link(s) to mod(s) used**: *null (Well, sk7725/BetaMindy is shown in the screenshot but it doesnt matter)*

**Save file**: *(Mostly) graphic bug*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
"yep this is fine"
