### ISSUE TITLE
Mindustry won't start on Windows 11.

### ISSUE THREAD

**Issue by Samiyellow** [Anuken/Mindustry#6270]
- [ ] Seen.
- [ ] Started.
- [ ] Made progress.
- [ ] Fixed.

**Platform**: Windows 11 64 bit Build 22000.282

**Build**: 126.2 (Windows-64 bit)

**Issue**: Mindustry won't start on Windows 11.

**Steps to reproduce**: On Windows 10, everything is normal but, on Windows 11, Mindustry won't start. I reinstalled it to the latest build so no mods and no save file.

**Link(s) to mod(s) used**: None

**Save file**: None

**(Crash) logs**: None 

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Samiyellow** [comment]
Help!

**Comment by Anuken** [comment]
> (Crash) logs: None

As the template says, crash logs are **required**.

**Comment by nlguerra2003** [comment]
Release build 126.2 runs perfectly on my side and my environment is the same: Windows 11 64 bit Build 22000.282

**Comment by Samiyellow** [comment]
> > (Crash) logs: None
> 
> As the template says, crash logs are **required**. If you don't have any, I can't help you.

Ok then how do I get crash logs when it won't open?

**Comment by Anuken** [comment]
Check the `%appdata%/Mindustry` folder.
