### ISSUE TITLE
Omura exploding in 1x1 spaces

### ISSUE THREAD

**Issue by BorisA11** [Anuken/Mindustry#6277]
**Platform**: Windows

**Build**: 134 

**Issue**: Omura will explode instantly if pushed in a 1x1 space while at an angle. In the screenshot below, it is shown where you should do it. Hold W and D to make it move diagonally, then enter in the 1x1 gap like that. The ship should explode. If not, try again, it worked almost every time for me. It is important that the moment you enter the gap, you are moving perfectly diagonally.

**Steps to reproduce**: As said. Make the unit enter a 1x1 gap while moving diagonally, and it will explode.
Note: It will sometimes move over the hole as if it doesnt exist, in that case, just move back and retry.

**Link(s) to mod(s) used**: None.

**Save file**: 
[Bugged map save.zip](https://github.com/Anuken/Mindustry/files/7449373/Bugged.map.save.zip)

**(Crash) logs**: No.

---
![image](https://user-images.githubusercontent.com/53085797/139595119-b9fa4687-9ef0-4c4a-bf19-506e5b3c192b.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![2021-10-31-14-01-43](https://user-images.githubusercontent.com/10100000/139596145-97ad3e5c-545b-467b-bea6-cb14f0da79b8.gif)

Attempted many times, cannot reproduce. Setting the FPS cap to 10 doesn't change the outcome. Sometimes, it gets in the hole, but an explosion never occurs. Tried a few different variants/directions, same result.

**Comment by begginerr** [comment]
> Platform: Windows

i wonder, what windows version? maybe that influences stuff?

**Comment by SMOLKEYS** [comment]
I feel like the unit moves to a non-water block causing it to explode.

This feels like a movement issue that can happen on certain devices. 

(this could probably happen more commonly on older devices, because from my general experience, older devices dont really handle game movement really well)

**Comment by BorisA11** [comment]
> I feel like the unit moves to a non-water block (for perhaps, a tick?) causing it to explode.
> 
> This looks like a movement issue that can happen on certain devices.
> 
> (this could probably happen more commonly on older devices, because from my general experience, older devices dont really handle game movement really well)

This was ran on a computer with i7-9700 and rtx2070 at 240fps, I seriously doubt that was the issue
