### ISSUE TITLE
Random Crux Blocks do not convert to derelict after beating a base

### ISSUE THREAD

**Issue by Cleanup-Crew-From-Discord** [Anuken/Mindustry#6278]
**Platform**: Windows

**Build**: 134 steam

**Issue**: After beating attack maps, sometimes random blocks fail to become derelict and stay as crux.

**Steps to reproduce**: Beat the bases on the north pole of the campaign map. This specific map was sector 69 in the bottom right side

![image](https://user-images.githubusercontent.com/92687025/139595933-94c51f93-4dcf-4a48-9bbf-d6ba7df915e6.png)

**Link(s) to mod(s) used**: none

**Save file**: Very sadly on both times this bug happened the horde of polies following me destroyed the blocks before I could get a copy of the map file :(

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: nope

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
This issue also exists in 126.2 and 105+

**Comment by Anuken** [comment]
Tried destroying several cores across several north pole bases, could not reproduce. You have not attached a save, so I cannot test further.

What may be happening is that the blocks are build after core destruction by lingering units, which isn't really a bug.

**Comment by Cleanup-Crew-From-Discord** [comment]
> Tried destroying several cores across several north pole bases, could not reproduce. You have not attached a save, so I cannot test further.
> 
> What may be happening is that the blocks are built after core destruction by lingering units, which isn't really a bug.

never thought of that, good point. There was a core unit still flying around in that general area so i bet that's what it was

**Comment by Cleanup-Crew-From-Discord** [comment]
![image](https://user-images.githubusercontent.com/92687025/139597580-e56e4f1b-eb9a-4f30-b4a5-984dc81e274c.png)
100% confirmed it with my own eyes, it is in fact caused by lingering units.
