### ISSUE TITLE
Bug with unit cap

### ISSUE THREAD

**Issue by JwMango** [Anuken/Mindustry#6281]
[Bug with ground factories.zip](https://github.com/Anuken/Mindustry/files/7454439/Bug.with.ground.factories.zip)
**Platform**: Windows

**Build**: 134

**Issue**: Max unit cap completely messed up

**Steps to reproduce**: Well i checked and its bc  changed the enemy team to the same color as the player team like: Player team:sharded , enemy team:sharded and then this happened
![bug](https://user-images.githubusercontent.com/92264519/139700907-3db21478-9d54-4c69-87f2-8618c5f69343.png)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: [Bug with ground factories.zip](https://github.com/Anuken/Mindustry/files/7454439/Bug.with.ground.factories.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not messed up. The crux team has no unit cap.
