### ISSUE TITLE
SpawnPoint

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#6287]
**Platform**: Any

**Build**: 134.1

**Issue**: When running a new wave, all units inside SpawnPoint are killed, but all buildings are not.

**Steps to reproduce**: Build any block inside of SpawnPoint. Run a wave.

**Link(s) to mod(s) used**: No mods

**Save file**: No save file because it happens on any map/server.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Did you try buildings in the middle of the spawn point? iirc those do get destroyed
