### ISSUE TITLE
partial incompatibility bettween Cliffs and mirror generator in map editor

### ISSUE THREAD

**Issue by breadbug23** [Anuken/Mindustry#6288]
**Platform**: *any*

**Build**: 134

**Issue**: 
*partial incompatibility bettween Cliffs and mirror generator in map editor*

**Steps to reproduce** : 
*The quickest way to reproduce it is :
generate terrain (magnitude 0)
walls to cliff
generate mirror*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cliffs just don't support mirroring.
