### ISSUE TITLE
Report#1

### ISSUE THREAD

**Issue by SansStars** [Anuken/Mindustry#6296]
**Platform**: `Android 30`

**Build**: `release build 126.2`

**Issue**: The issue is the game can't even handle a community sever for an hour. I've tried on computer too, servers need to be fixed.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You did not fill in the template, and this is not a usable report. I cannot read minds - there is no way for me to know what "cannot handle means" (game crash? freeze? timeout? network error? lag?) or what you want me to "fix".

**Comment by Bottinator22** [comment]
Anuken being able to reap your soul does not mean that Anuken can read your mind

**Comment by begginerr** [comment]
the issue is that 1. you deleted like half the template and 2. you arent specific enough. again, what does cannot handle mean?
