### ISSUE TITLE
maps/derelict-battlefield.msav

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#6297]
**Platform**: *Not Android*

**Build**: *134/134.1*

**Issue**: 
![c6361fb91b243f56](https://user-images.githubusercontent.com/61173114/140235494-0a73a086-33e5-490f-b902-89455908dc46.png)
Encountered only by PC users (2 reports). Mod has the map file in maps/.

**Steps to reproduce**: *step 1: "f-ck if i know".*

**Link(s) to mod(s) used**: *Exotic.*

**Save file**: *n.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *n.*

I have no further information on this issue, because I cannot personally reproduce it.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
(nope, doesn't look like a foo's-specific issue, I can't reproduce it with a client either)

**Comment by BlueWolf3682** [comment]
The only further information I can give is that Derelict Battlefield cannot be launched to on my client and shows up as a low threat enemy base.

**Comment by Anuken** [comment]
That loads correctly for me, actually:

![image](https://user-images.githubusercontent.com/10100000/140409228-72fb32f1-8bb5-408c-a4ca-29f6b141a643.png)

**Comment by Anuken** [comment]
Also loads & displays correctly on my phone, so whatever you're experiencing is not related to Android.
