### ISSUE TITLE
Certain UI elements missing on Android when played in portrait mode. 

### ISSUE THREAD

**Issue by Monster-Gaming-Studios** [Anuken/Mindustry#6299]
**Platform**: *Android*

**Build**: *134*

**Issue**: *Certain UI elements like Guardian Health Bar, Sector List/Search Bar on Planet Screen and Planet Selector when playing with mods that add planets are not visible when playing in portrait mode.*

**Steps to reproduce**: *Open the planet screen or have a Guardian spwan in a wave while playing in portrait mode.*

**Link(s) to mod(s) used**: *Planet Selector is not visible with any mod that adds Planets. Sector List and Guardian Health Bar is not visible with or without any mods installed.*

**Save file**:
[0.msav.zip](https://github.com/Anuken/Mindustry/files/7474654/0.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

![Screenshot_2021-11-04-16-52-53-962_io anuke mindustry](https://user-images.githubusercontent.com/55491103/140311504-1f73e9ef-c432-4691-9181-4720089530dd.png)
![Screenshot_2021-11-04-16-46-32-598_io anuke mindustry](https://user-images.githubusercontent.com/55491103/140311524-57725628-9036-4a58-9a4c-cf34365570ea.png)
![Screenshot_2021-11-04-16-52-42-959_io anuke mindustry](https://user-images.githubusercontent.com/55491103/140311532-f038f81f-5d25-48f6-becb-f3947f2c856d.png)
![Screenshot_2021-11-04-16-47-00-984_io anuke mindustry](https://user-images.githubusercontent.com/55491103/140311537-c490796f-3310-4c2f-b617-ceae0f149c06.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by oinkymoo** [comment]
this is intentional

**Comment by Monster-Gaming-Studios** [comment]
Why?

**Comment by oinkymoo** [comment]
Anuke thought that there wouldn’t be enough screen space otherwise

**Comment by Monster-Gaming-Studios** [comment]
> Ok. Thank you.
