### ISSUE TITLE
Adding modded attribute wipes vanilla attributes

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#6304]
**Platform**: *Windows*

**Build**: *134*

**Issue**: *When you add attributes, it wipes all attributes from vanilla blocks such as cultivators*

**Steps to reproduce**: *Download latest betamindy action, and then test a water extractor on grass.*
Current custom attribute implementation:
```
public class MindyAttribute {
    public static final Attribute
    /** Heavy metal content. Used for blocks that make lead from scratch. */
    metallic = Attribute.add("metallic"),
    /** Magnetic coverage. Used for dynamo generators. */
    magnetic = Attribute.add("magnetic"),
    /** Blocks flagged with this attribute (>= 0.5f) cannot be pushed by pistons. */
    pushless = Attribute.add("pushless");
}
```

**Link(s) to mod(s) used**: *https://github.com/sk7725/BetaMindy*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GlennFolker** [comment]
Did you make sure your `MindyAttribute` class was loaded before client load?

**Comment by sk7725** [comment]
> Did you make sure your `MindyAttribute` class was loaded before client load?

....its static. It loads asap afaik.

**Comment by GlennFolker** [comment]
It does not.
