### ISSUE TITLE
Mouse cursor drawn at wrong position

### ISSUE THREAD

**Issue by slash128gnr** [Anuken/Mindustry#6316]
**Platform**: Windows

**Build**: 126.3 Steam and standalone.

**Issue**: The mouse cursor is drawn about 100 pixels too far down and to the right.

**Steps to reproduce**:  It's observable at the main menu. Running at 1440p if I position the mouse in the furthest top left position the graphic for the pointer is pointing two blocks down and two blocks to the right.

**Link(s) to mod(s) used**: None

**Save file**: Happens on fresh startup.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce on any platform.
