### ISSUE TITLE
Units get stuck in deadly spawnzone

### ISSUE THREAD

**Issue by MarcusTU** [Anuken/Mindustry#6319]
**Platform**: Tested on Win10 but I assume thats not relevant.

**Build**: 7.0: 134.1, jar

**Issue**: 
- Capture a map that has en enemy base on it. It will have no spawnzone after capture, so units can walk everywhere.
- build lots of units
- after the map is attacked, units (set on "attack") will surround the now existing spawnzone.
- defeat everyone (spawnzone vanishes after victory), play another map for some time until the next attack
- now the units stand right in the center of the again existing spawnzone. They try to spread out but may be blocked by walls.

It is impossible to rescue these units because even manually controlling them wont help because movement in spawnzones is strongly limited.

**Link(s) to mod(s) used**: No mods

**Save file**: Pretty sure the screenshot is more helpful.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![unnamed](https://user-images.githubusercontent.com/51535493/140773536-38acbbdb-33ba-4b6d-a432-4af0c2d552f6.png)

**Comment by MrDuck557** [comment]
how do you suggest a fix

**Comment by MarcusTU** [comment]
> 
> 
> how do you suggest a fix

Lower or remove the force that drives player controlled units out of the spawnzone. AI controlled units get still repelled (so they cannot enter). That would allow the player to manouver his units out of there.

**Comment by Anuken** [comment]
This is not a bug.
