### ISSUE TITLE
MultiEffect overrides children

### ISSUE THREAD

**Issue by MrDuck557** [Anuken/Mindustry#6324]
**Platform**: *Windows*

**Build**: *Custom build, [this pr](https://github.com/Anuken/Mindustry/pull/6323)*

**Issue**: *MultiEffect overrides its children's fields, at least in hjson*

**Steps to reproduce**: *Make a MultiEffect, add a child, set `baseRotation` or `startDelay`. Double check that MultiEffect is the issue by removing the MultiEffect and using the child directly*

**Link(s) to mod(s) used**: *I was testing using my own test mod but I believe you can reproduce using any hjson*

**Save file**: *it has my **inaccessible** mod but ok*
[bap.zip](https://github.com/Anuken/Mindustry/files/7515645/bap.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It does not "override" those fields, they are completely irrelevant in children, which are only used for rendering. Only the parent can have a delay or baseRotation. For similar reasons, it's impossible (and makes no sense) for certain children to follow the parent and others not.
