### ISSUE TITLE
macOS Monterey Crashing

### ISSUE THREAD

**Issue by Yittria** [Anuken/Mindustry#6325]
macOS Monterey 12.0.1, build 6469836

Issue: Game crashes immediately on startup of app.  It has not opened since I have updated my OS.  It happens every time.

No Mods

Don't think you need a save file as I'm not even playing yet, but let me know if you an I will see what I can do to get one.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.*

[text.txt](https://github.com/Anuken/Mindustry/files/7517309/text.txt)
*

**Comment by Anuken** [comment]
You have not specified your game version, so I am forced to guess here. If you haven't already tried it, this is likely to not be an issue in the v7 pre-alpha version (game properties -> betas -> v7).

I do not own a device with that operating system, and none of the code in the crash appears to be mine, so if that doesn't work, I don't have any other solutions.

**Comment by Yittria** [comment]
Apologies.  I was not running on the beta.  I just booted the game up this morning with the Beta version 7.  Haven't opened up a game in it yet, but the game loaded, so that's better than what was happening.  Thanks a bunch.
