### ISSUE TITLE
Fullscreen / Borderless Fullscreen acting weird

### ISSUE THREAD

**Issue by 4DchessPlayer** [Anuken/Mindustry#6329]
**Platform**: *MacOS/Windows*

**Build**: 133-133.4
**Issue**: CMD + Tab / SHIFT + CMD + 4 not working on MacOS (AltTab and Region Screenshot of MacOS), Screenshot function of Windows creates a black picture instead of whatever is happening in-game, as well as Windows' ScreenCap function not being able to record despite Borderless Fullscreen being enabled.
**Steps to reproduce**: Enable Fullscreen/Borderless Fullscreen.

**Link(s) to mod(s) used**: None.
**Save file**: Ain't happening in-game.

**(Crash) logs**: None.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Halt-alt** [comment]
I think that happens in a lot of games (am sure it happens in terraria, idk about others), but i am unsure whether it's the engine's fault or can it be fixed by anuke

**Comment by Anuken** [comment]
If the OS screenshot/recording function doesn't work, that's a bug with the OS, not the game. I am not doing anything special to prevent screenshots from being taken.

> it's the engine's fault

I don't use an engine.

**Comment by Ccode-lang** [comment]
I have a workaround, install snip and use it.
