### ISSUE TITLE
Attempted to make my own ForceProjector which crashes on placement

### ISSUE THREAD

**Issue by Beanzilla** [Anuken/Mindustry#6333]
**Platform**: Linux

**Build**: 126.2 (But just upgraded to 134.1 pre-release)

**Issue**: I have been attempting to make my own mod, which mostly follows pre-built structures just modified to give me a slight advantage. (The mod doesn't override but rather makes separate items)

I wanted to make my own Force Projector with slightly larger range and less downtime for when it goes down, but it appears the wiki isn't clear enough for me to follow it to make my own. (Or quite simply, I missed something that may be obvious)

**Steps to reproduce**: The quickest way that I have found is to make sure my mod (which is currently not released but may soon be released via a git repo) is enabled, then enter any map in sandbox mode then go to the Defense tab (The one will walls) to select the Hex Field (my remake of the Force Projector) place it and watch your client blow up.

**Link(s) to mod(s) used**:  Both of the mods that I currently have installed along with the current version of my mod mindustry-hacked will be added.

[mindustry-hacked.tar.gz](https://github.com/Anuken/Mindustry/files/7533309/mindustry-hacked.tar.gz)
[MindustryInsideAutoUpdater.zip](https://github.com/Anuken/Mindustry/files/7533310/MindustryInsideAutoUpdater.zip)

**Save file**: 

[test_case.tar.gz](https://github.com/Anuken/Mindustry/files/7533337/test_case.tar.gz) (At this time I was still using 126.1, but now upgraded to 134.1 pre-rel)

**(Crash) logs**: 

[crash-report-11_14_2021_01_50_57.txt](https://github.com/Anuken/Mindustry/files/7533340/crash-report-11_14_2021_01_50_57.txt)

(At this time I was still using 126.1, but now upgraded to 134.1 pre-rel)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

I have searched thru closed issues up to page 8 then quite simply gave up, since not many of them are related much to custom modding.

I see on the wiki [ForceProjector](https://mindustrygame.github.io/wiki-testing/modding/5-types/#forceprojector) but I have all those fields on the Hex Field (as defined in mindustry-hacked/content/blocks/defense/hex-field.hjson), or at least I think I do.

I feel as though a solution, though it would take a while to complete, would be to add .hjson files that depict or even define the games built-in stuff (weapons, walls, power generators, battery, and what not) as a way to show how to mod that item. (But this is just someone lost and confused)

**Comment by Anuken** [comment]
Force projectors must consume boost items, but yours does not have one.

**Comment by Beanzilla** [comment]
Ok, I have tried to add a consume boost items but it appears I don't understand how to add one.

Could I get an example or link showing how to add this?

**Comment by Anuken** [comment]
`consume` is not a valid field, it's named `consumes`.

You also have other invalid fields in the block; check the log (backtick key on desktop, local files on Android):
```
[W] test-hexfield: Ignoring unknown field: breakage (mindustry.world.blocks.defense.ForceProjector)
[W] test-hexfield: Ignoring unknown field: basePowerDraw (mindustry.world.blocks.defense.ForceProjector)
```

**Comment by Beanzilla** [comment]
Thank you very much, I see now that the real wiki not only describes the valid fields but also includes some examples.

> I thought I was doing something wrong... now I know it was me looking in the wrong area.
