### ISSUE TITLE
Wrongly layered rendering

### ISSUE THREAD

**Issue by haltalt** [Anuken/Mindustry#6334]
**Platform**: *Windows*

**Build**: 22198

**Issue**: Payloads "slip in" between turret bases and actual turrets.

**Steps to reproduce**: Place a payload source and select a block. Place a turret in front of it. Observe.

**Link(s) to mod(s) used**: Tested both with foo and without.

**Save file**: 
[bugreport2.zip](https://github.com/Anuken/Mindustry/files/7533482/bugreport2.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. The payloads are above standard blocks (standard elevation), but below turrets (higher elevation).
