### ISSUE TITLE
Research data and Wave progress not synced on steam cloud

### ISSUE THREAD

**Issue by dbfoxtw** [Anuken/Mindustry#6336]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: 
Research data and Wave progress seems not properly synced on steam cloud if played on different PC.
I used to play campaign on my Desktop PC. But these two days, I played on Notebook and captured 4 sectors.
When I back to Desktop PC, I found the 4 sectors I captured under attack by unknown source. 
And the wave progress of latest sector: Nuclear Production complex is messed up, it reset to 1/30 waves, not 50 waves.
Research is rollbacked too, back to progress 4 sectors before.
Although all buildings are intact.

**Steps to reproduce**: 
1. On Desktop PC, play campaign and save on Stained Mountains.
2. Play on Notebook, capture Stained Mountains, Windswept Islands, Salt Flats, Fungal Pass, then save on Nuclear Production complex.
3. Back to Desktop PC. The campaign is on Stained Mountains and is under attack.
4. Thought save is not synced, so I turn on Notebook, found that campaign is on Stained Mountains too.

**Link(s) to mod(s) used**: `none`

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/7533737/save.zip)

**Crash report**: Not crashed.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.

**

**Comment by Anuken** [comment]
Cannot reproduce, cloud sync works on my machine(s).
