### ISSUE TITLE
Wrong texture folder for mindustry sprites

### ISSUE THREAD

**Issue by Zelaux** [Anuken/Mindustry#6343]
**Platform**: *Windows*

**Build**: *134.1*

**Issue**: *I installed 2 mods with a large number of textures, and when I enter the map, the environment blocks from mindustry are drawn with the "env-error" texture. It's not just me who gets it.(It's not because of Braindustry)*
![image](https://user-images.githubusercontent.com/58040045/141840283-e4a45ea4-114b-4704-a7ec-0d51b751cc33.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *Braindustry and another mod by my authorship, which is still in development.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There are two possibilities here:
- You have too many environment block sprites, which fill up the spritesheet. Reduce your sprite count and size.
- You are performing some action in your mod that breaks vanilla blocks. I'm not going to go through your code, especially considering I don't have access to one of the mods mentioned.

**Comment by Zelaux** [comment]
>You have too many environment block sprites, which fill up the spritesheet. Reduce your sprite count and size.

I have sprites generated as in mindustry. I can't reduce the number of sprites, what should I do?

**Comment by Anuken** [comment]
There's currently nothing you can do besides reduce the number of sprites. Environment sprites must all fit on one texture for technical reasons, and the current maximum safe texture size is 2048x2048.

Even with all the generated cliff sprites and a bunch of v7 environment blocks, there's plenty of space left in the vanilla spritesheet. You shouldn't need that many sprites. Make sure that folder only contains **static environment blocks**, such as floors or indestructible walls. Trees and other props do not belong there.
