### ISSUE TITLE
Chrash build 52 ArrayIndexOutOfBoundsExeption''-1''

### ISSUE THREAD

**Issue by NLinCH** [Anuken/Mindustry#636]
Error ocured whilst starting up. I got some space issues but just deletet some things (also from the trash bin) 

![Chrash build 52 ArrayIndexOutOfBoundsExeption''-1''](https://user-images.githubusercontent.com/43685452/64371076-00a73600-d020-11e9-82bd-d8fbc2c42246.PNG)
[crash-report-05-09-19 8.55.39.txt](https://github.com/Anuken/Mindustry/files/3580826/crash-report-05-09-19.8.55.39.txt)

hope it can help you cause this might be the 5.th version of the game i downloaded 
Though I like that it is free since I am just a 15 Jear old that knows a lot of quantum stuff . 
I think it would be worth at least 25 € with all your development time and this great game. Thanks for giving so much time to such a geat game you created.

**Comment by J-VdS** [comment]
update to the newest version

**Comment by Anuken** [comment]
Yep, you're running a version of the game that's more than a year old. Update to the latest.
