### ISSUE TITLE
Error with installing game

### ISSUE THREAD

**Issue by Sanek3400** [Anuken/Mindustry#6364]
Platform: Android

Build: 134.1

Issue: Game not installing
![Screenshot_20211123-190915](https://user-images.githubusercontent.com/79786089/143071524-5f6146c1-6c96-4d62-b37a-b3bf904a307c.jpg)

---

- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Where are you trying to install the game from?

**Comment by Bottinator22** [comment]
Just in case you couldn't tell, in the image they're trying to install Mindustry V7 via downloaded apk

**Comment by Bottinator22** [comment]
Have you tried using Google Play Store beta program?

**Comment by MHeMoTexHuK** [comment]
you didn't even provide any additional info. There's like 10 different reasons for the installation to fail, and most of them aren't anukes responsibility

If you already have mindus installed, you should try to uninstall it first (don't forget to create a backup of your data, h)

**Comment by Anuken** [comment]
You likely have another version of Mindustry already installed. If that's not the case, it's some issue with your device, which I can't even diagnose due to the ridiculously-unhelpful Android error messages.

**Comment by begginerr** [comment]
![image](https://user-images.githubusercontent.com/87596406/143286232-9b79bf76-a92a-4966-b2f1-dc3170ca85a2.png)
anyone noticed this

**Comment by Bottinator22** [comment]
> ridiculously-unhelpful Android error messages.

**Comment by begginerr** [comment]
> > ridiculously-unhelpful Android error messages.

yep but i meant the mindustry 134.1 above it
