### ISSUE TITLE
hi so basically there is no option to make an account im finding it hard plus when evr i verified it says im not verified the next day.

### ISSUE THREAD

**Issue by GREATWHITEWOLF1** [Anuken/Mindustry#6366]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mindustry has no account or verification system, and as you are told before you join a server, I do not own or control any servers.

**Comment by GREATWHITEWOLF1** [comment]
Question what is a cn-account

**Comment by GREATWHITEWOLF1** [comment]
And so do i verify cause it said that u need to verify to be rank 001.
How does the ranking system work?

**Comment by GREATWHITEWOLF1** [comment]
And do i have to keep on verifying

**Comment by Anuken** [comment]
Again, I do not own or control any servers. This is the wrong place to ask; I don't know anything about it.
