### ISSUE TITLE
APK from Itch does not work

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#6369]
Sorry for not following the template exactly—I'm on mobile and it's not loading.  I've tried to remember it as best I can.

Platform:  Android.

Build:  135, trying to install it over 134.1.

Save file:  Not applicable.

Mods used:  None.

Description:  When attempting to upgrade build 134.1 to build 135 via the APK from Itch, the package installer fails instantly once I confirm that I want to install it.  (Build 134.1 was also installed from Itch.)

Reproduction:  Have 134.1 installed from Itch and attempt to upgrade it to 135 via Itch.

**Comment by Anuken** [comment]
Installing 135 works fine on my device, as does upgrading from 126.2 to 135. There's no way for me to debug this, and the easiest solution for you would be export/back up your data, uninstall the old version and install 135.

**Comment by BlueManedHawk** [comment]
Damn.  Alright, thanks for your help.

**Comment by BlueManedHawk** [comment]
Well, that didn't work either.  Now it just won't install it.

**Comment by BlueManedHawk** [comment]
Okay, nevermind, it _is_ working now.  ???????

**Comment by Anuken** [comment]
It sure would be great if Android **told you why installation failed**, for situations like these.

**Comment by Bottinator22** [comment]
> ridiculously unhelpful Android error messages
if only OSes weren't so focused on being friendly to users that don't know a thing about how the installation might go wrong

**Comment by begginerr** [comment]
> It sure would be great if Android **told you why installation failed**, for situations like these.

yep that sure would be nice
