### ISSUE TITLE
titanium conveyor missing

### ISSUE THREAD

**Issue by Johnonamansion** [Anuken/Mindustry#6372]
**Platform**:Windows

**Build**: 126.2

**Issue**:The titanium Conveyor doesn´t appear in my research and it was blocked by the reseach on the right of it 

**Steps to reproduce**:No Idea sadly 
**Link(s) to mod(s) used**: no mods used
**Save file**: discord tag:johnonamansion#6182

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: n.a.
![image](https://user-images.githubusercontent.com/95052675/143498496-61920ec4-e8b8-4487-9508-991d87613c3e.png)

![image](https://user-images.githubusercontent.com/95052675/143498537-30f1a3af-3e1b-4342-acb6-814419b39023.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This report doesn't make any sense; I can't reproduce this and neither can anyone else. Are you sure your game isn't modded? There's no way to test this *as you have not attached your game data*.

**Comment by Bottinator22** [comment]
Your Discord tag is not a save file

**Comment by Anuken** [comment]
> Your Discord tag is not a save file

He sent me the saves in PM, but saves aren't game data - they don't contain research.

**Comment by Bottinator22** [comment]
> > Your Discord tag is not a save file
> 
> He sent me the saves in PM, but saves aren't game data - they don't contain research.

ah

**Comment by Johnonamansion** [comment]
> This report doesn't make any sense; I can't reproduce this and neither can anyone else. Are you sure your game isn't modded? There's no way to test this _as you have not attached your game data_.

Not modded at all
I think it can be recreated by researching the stuff on right to it first then on left of the bridge conveyor but anyhow what do i do?

**Comment by Johnonamansion** [comment]
> > Your Discord tag is not a save file
> 
> He sent me the saves in PM, but saves aren't game data - they don't contain research.

Which folder do you need

**Comment by Hexrotor** [comment]
> Which folder do you need?

Just export the data in game's settings

**Comment by Johnonamansion** [comment]
> > Which folder do you need?
> 
> Just export the data in game's settings

done 
look in to your dms

**Comment by Johnonamansion** [comment]
well the real life mod was installed and i did not know that i installed this 
sorry for wasting your time
