### ISSUE TITLE
liquids in full liquid producers have reaction particles to reacting liquids in conduits

### ISSUE THREAD

**Issue by yetyeeter1337** [Anuken/Mindustry#6374]
**Platform**: Windows

**Build**: 126.2

**Issue**:  conduits that are directly connected to crafters that output reactive liquids or connecting a reactive liquid to a full liquid producer that are full show reaction particles on the side where the conduit is attached, works with non-leaking conduits. originally discovered in a mod I was making but I disabled the mod and tested it in vanilla with a full cryofluid mixer with a pipe of slag attached and it still happened. not fatal but very annoying.

**Steps to reproduce**: attach a conduit to a full liquid producer (ex cryofluid mixer, melter) and fill the conduit with a fluid that will react with the output of the producer.

**Link(s) to mod(s) used**:  the bug works in vanilla but just in case my mod is attached, the chaos mixer's output would react with the oxygen input.
[mod-testing.zip](https://github.com/Anuken/Mindustry/files/7605584/mod-testing.zip)

**Save file**: [34.zip](https://github.com/Anuken/Mindustry/files/7605590/34.zip) with mod
[35.zip](https://github.com/Anuken/Mindustry/files/7605591/35.zip) without mod

**(Crash) logs**: none, no crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't a bug. Do the same thing with slag and oil, and the crafter/conduit would explode. You're trying to mix reactive liquids, so they *react*.

**Comment by yetyeeter1337** [comment]
oh. im just stupid then. thanks :P
