### ISSUE TITLE
Unit bind state not included in save file data

### ISSUE THREAD

**Issue by Afdill** [Anuken/Mindustry#6379]
**Platform**: *Linux*

**Build**: *135*

**Issue**: *The bind state for any given unit on a map is not included in save info.  On the the other hand, a given processor's current instruction step _is_ stored in save state data.  This means that whenever a save is loaded up, processors need to run dead instructions until they wrap around to unit bind again to re-bind a unit to work with.  While this is not much of an issue for instruction set types oriented towards mass unit control, this means you can create scenarios where a processor which relies on loops to complete a given unit's behavior set becomes broken if a game is saved in the middle of that behavior set and then reloaded.  I would also expect this to be a source of desyncs in multiplayer games, but have not tested.  I consider this a bug because it requires extra processor instructions to work around unexpected game behavior.*

**Steps to reproduce**: *Create a unit behavioral script that requires a while loop to complete a given set of behaviors.  For example, telling a bound unit to move to a location and drop an item off, looping that instruction set with a conditional check until that item is successfully delivered.  If the game is saved while that unit is in transit, you will get its associated processor stuck in an infinitely-looping state after reloading from the save.  The attached map save has many Flares configured to continuously move phase fabric from the core to projectors when they need some.  If it is saved and reloaded several more times, more and more of the processors will become stuck in infinite loops leading to broken delivery systems.*

**Link(s) to mod(s) used**: *None relevant.*

**Save file**: *[save.zip](https://github.com/Anuken/Mindustry/files/7608528/save.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This can't be saved.

**Comment by Bottinator22** [comment]
Not even a special reference to the specific unit in the save that later gets converted to a proper one?

**Comment by Anuken** [comment]
Unit IDs don't get saved, so no.

**Comment by Bottinator22** [comment]
In what order do the units get loaded?

**Comment by Anuken** [comment]
There is no defined order.

**Comment by Anuken** [comment]
FYI unit IDs are now saved in the 7.0 development branch, so saving units variables becomes viable.
