### ISSUE TITLE
Can't export game data on Android 10

### ISSUE THREAD

**Issue by micahdg** [Anuken/Mindustry#638]
I get a stack trace with Permission Denied when I try to save exported data on my Pixel 3a running Android 10. I confirmed Mindustry as Storage permissions. I also can't see any folders or files when attempting to choose where to export data to.
![Screenshot_20190906-163220](https://user-images.githubusercontent.com/3386311/64462056-c774d180-d0c4-11e9-9535-b13577a30ab7.png)
![Screenshot_20190906-163238](https://user-images.githubusercontent.com/3386311/64462057-c774d180-d0c4-11e9-9403-1d63814be111.png)

**Comment by Anuken** [comment]
Did you allow Mindustry to access local storage when exporting the data?

**Comment by micahdg** [comment]
Yes, the first time I exported a few days ago while still on android 9. I was not prompted again this time (as expected I think). I did also tried revoking the permission and reallowing it. No joy.

**Comment by Anuken** [comment]
I can reproduce the issue on an emulator, but don't know of a solution. On every other Android version, this works perfectly fine. Yet another thing that Android 10 has broken, for seemingly no reason. What a mess.

**Comment by micahdg** [comment]
Yep, I lost a few OS features I liked, too. I don't know what came over me upgrading to 10 right away... I'll keep playing on the phone till you figure it out. I only use my PC to play when there are 50+ enemies on the map and I get .02 FPS :)

**Comment by Anuken** [comment]
Actually, the .02 FPS issue is also an Android 10 bug; playing sounds on that version causes significant lag. See if it goes away when SFX volume is set to 0.

**Comment by micahdg** [comment]
Oh man, you really made my day. I've been suffering with that lag for the past few weeks. It was present on android 9.? as well. Thank you!

**Comment by Anuken** [comment]
Export should be fixed as of the latest commit; apparently Google forces you to use their file choosing API now.
