### ISSUE TITLE
Bug and saves my territory

### ISSUE THREAD

**Issue by CredO0** [Anuken/Mindustry#6382]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
useless bug report, part 4

**Comment by CredO0** [comment]
how to write a correct report? I find it difficult, I sit with a translator

**Comment by Anuken** [comment]
Fill in the required fields in the report; you have not even explained what the problem is here.

**Comment by CredO0** [comment]
The problem is that when I gave the base, I flew out of the game, after I went back from the base, there was nothing left, but at the same time the tree branches were preserved @Anuken  i can provide screenshots, but i don't know how

**Comment by Anuken** [comment]
That was already reported and fixed in v7. Wait for the update.

**Comment by CredO0** [comment]
Thank you for your work. But will my gameplay return to me in V7? @Anuken

**Comment by CredO0** [comment]
I'm a beginner and don't understand, but V 7.0 is already out on android? @Anuken

**Comment by Anuken** [comment]
> will my gameplay return to me in V7?

No.

> but V 7.0 is already out on android?

Not the stable version.
