### ISSUE TITLE
Modded attributes crash with attribute weather

### ISSUE THREAD

**Issue by sk7725** [Anuken/Mindustry#6389]
**Platform**: *Linux/Android (reported to me on both)*

**Build**: *134.1/135(see above)*

**Issue**: *Modded attributes crash when it spores. Crash traced down, and I found that the Attribute length of `envAttrs` is still 4 while the weather's array length is more than 4.*

**Steps to reproduce**: 
*1. Spore floats on BetaMindy*
*2. Cover yourself in BetaMindy*
*3. Wait for it to Spore(storm)*
*4.*

**Link(s) to mod(s) used**: *sk7725/BetaMindy*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 134.1
OS: Linux xnull (aarch64)
Java Version: 0
Mods: betamindy:1.07
[#b59e72]Demo of Chaos Itself[], betamindy-music:1.0, dev-mode:2.3.2, exogenesis:[blue]1.4, ldb:1.3.2, override-lib:1.0.1, revision:12.2, test-utils:0.1, uaw:0.7.4, ui-lib:2.16.6, waisa:2.3.3

ArrayIndexOutOfBounds: 'length=5; index=5'
Attributes.add: 36
Logic.lambda$update$16: 411
Logic.$r8$lambda$2AYXZ6is5zKaTl820N3CZYFqJmc: 0
Logic$$ExternalSyntheticLambda14.get: 2
EntityGroup.each: 70
Logic.update: 411
ApplicationCore.update: 37
ClientLauncher.update: 177
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SMOLKEYS** [comment]
ive

had this crash

over 120 times now
