### ISSUE TITLE
Allow proprietary stuff to be separate build options

### ISSUE THREAD

**Issue by throwaway1037** [Anuken/Mindustry#6408]
Is Mindustry 100% libre?

As far as I can tell, it might have proprietary dependencies, fonts, and integration with other proprietary software, like Steam and Discord.

Please may all the proprietary stuff be pointed out to me, and in the case of optional integration with proprietary software, like Steam and Discord, be made into separate build options?

**Comment by Anuken** [comment]
This is a *feature request* / question, please only use this tracker for bug reports.

As far as I'm aware, there is no proprietary code (or assets) here outside of the Steam integration DLLs, which are not packaged with the game outside of the Steam version. If you don't want that in your game, just don't use / buy the Steam version. The Discord integration [uses no outside libraries](https://github.com/Anuken/Arc/blob/master/extensions/discord/src/arc/discord/DiscordRPC.java), and should not do anything if you don't have a Discord client running.

**Comment by throwaway1037** [comment]
Thank you

**Comment by Anuken** [comment]
> which are not packaged with the game outside of the Steam version

Correction: They actually *are* included with the normal version due to an oversight, but that will be fixed in future releases, and they're not used anywhere (basically just a waste of space).

**Comment by throwaway1037** [comment]
I think it would be wise to quickly audit there are no other such oversights, as this undermines the trustworthiness of sites like the [Libre Game Wiki](https://libregamewiki.org), although I assume good faith and assume packaging proprietary Steam binaries was an honest mistake.
