### ISSUE TITLE
BlockFlag.resupply doesn't exist?

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#6411]
**Platform**: *Headless server*

**Build**: *Any v7 pre-alpha build*

**Issue**: *Strange exception is thrown on different servers 2-3 times per day. The server doesn't crash but please fix it.*

**Steps to reproduce**: *I don't know ;-;*

**Link(s) to mod(s) used**: *No mods.*

**(Crash) logs**: *See my screenshot.*

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![IMG_20211208_082427](https://user-images.githubusercontent.com/79508138/145153525-e7fbc3bc-0f9b-4389-abae-5c290378257f.jpg)

**Comment by Anuken** [comment]
This isn't a bug; someone is using a schematic with a flag that doesn't exist anymore.
