### ISSUE TITLE
BannedUnits isn't working correctly

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#6412]
**Platform**: *any*

**Build**: *135.*

**Issue**: *If bannedUnits rule is enabled, you can't upgrade a unit (screenshot 2). But you can put it in the reconstructor directly and it will upgrade (screenshot 1).*

**Steps to reproduce**: *See screenshots.*

**Link(s) to mod(s) used**: *No mods.*

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![IMG_20211208_083716](https://user-images.githubusercontent.com/79508138/145155417-1669359c-8e44-483a-b9f5-39a45d96f84a.jpg)
![IMG_20211208_083741](https://user-images.githubusercontent.com/79508138/145155432-9c6d5329-654f-4c09-985b-4fd6ef5bde7e.jpg)

**Comment by Anuken** [comment]
Fixed in dev branch.
