### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#6413]
**Platform**: *Any*

**Build**: *135*

**Issue**: *When you launch to the sector and then exit, you will see one water icon. But if you restart the game, icon will change to another*

**Steps to reproduce**: *Launch to Ground Zero. Exit to the main menu. Check icon. Restart the game. Check icon again.*

**Link(s) to mod(s) used**: *No mods.*

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![IMG_20211208_122351](https://user-images.githubusercontent.com/79508138/145183771-863b43d9-dfb8-4f3f-ace0-040e0fef35ad.jpg)
![IMG_20211208_122532](https://user-images.githubusercontent.com/79508138/145183799-837a879b-5cfc-4ba2-93d1-e1d89297d885.jpg)

**Comment by Hexrotor** [comment]
Probably already fixed
#6370

**Comment by Darkness6030** [comment]
I searched and didn't find :-(

**Comment by Darkness6030** [comment]
Closing
