### ISSUE TITLE
Modded Error on Read of units

### ISSUE THREAD

**Issue by pankiwi** [Anuken/Mindustry#6417]
**Platform**: *Android/Linux*

**Build**: *135.*

**Issue**: *I was testing and that the units can use the read() and write() but the read in the units is broken but the write works.*

**Steps to reproduce**: 
*step 1: open map*
*step 2: spawn unit*
*step 3: exit map*
*step 4: open map*

**Link(s) to mod(s) used**: *
[testUnit.zip](https://github.com/Anuken/Mindustry/files/7678198/testUnit.zip)
*

**Save file**: *null*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *not crash game but corruption file*
**last log**: 

*[I] arc.util.io.Writes@151680a
[E] mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "entities".*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You cannot have an empty write method. All write methods must also write the revision as a short.

**Comment by pankiwi** [comment]
[testUnit.zip](https://github.com/Anuken/Mindustry/files/7678347/testUnit.zip)
I did what it tells me, try to save a number, how can I clarify the read in units is broken

**Comment by Anuken** [comment]
If it were broken, it wouldn't work for vanilla units. Your *code* is broken. 

As I said earlier:

> All write methods must also write the revision as a short.

You are not doing this in your code.
