### ISSUE TITLE
Implement achievements for non-Steam versions of the game

### ISSUE THREAD

**Issue by throwaway1037** [Anuken/Mindustry#6418]
There are achievements, but they only work via Steam integration on desktop platforms AFAICT; it would be great to have these work without forcing the player to use proprietary software.

**Comment by Anuken** [comment]
Once again, this is a feature request, not a bug. I believe I make this clear in the issue selector, which should be appearing every time you create a new issue.

![image](https://user-images.githubusercontent.com/10100000/145314103-ca25d5b3-48c7-43e2-ab9f-71c7ab10b823.png)

**Comment by throwaway1037** [comment]
Requiring proprietary software in order to gain access to features of the game is a bug.

**Comment by Bottinator22** [comment]
No, it's not

It is only a bug if it's not intended

**Comment by Anuken** [comment]
(this user was blocked, please don't feed the trolls)
