### ISSUE TITLE
Mindustry main save file is now creative

### ISSUE THREAD

**Issue by G-3-K-Y** [Anuken/Mindustry#6419]
**Platform**: **Windows**

sorry for bad english

**Build**: *Pre-Alpha build 135.*

**Issue**: *After playing for 3-4 days I decided to mess around in custom mode to try and find new schematics, after that i went back to my main campaign but it was changed to creative mode and i cannot make it back to survival*

**Steps to reproduce**: *I opened the editor, created a custom sandbox map and then played it on a creative custom game, I later went back to my main save and found it on creative mode.*

**Link(s) to mod(s) used**: *I deleted a mod i tried to use, but I found it browsing "Sandbox mode" on the game browse thing*

**Save file**: [salvataggio 2.zip](https://github.com/Anuken/Mindustry/files/7684711/salvataggio.2.zip)

**(Crash) logs**: *last log:
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 1.8.0_281
[I] [RAM] Available: 3.0 GB
[I] Total time to load: 4056ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 20 community servers..*

---

- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.** (Kind of found other people with my problem but i can't solve it in any way)

**Comment by Anuken** [comment]
> I deleted a mod i tried to use, but I found it browsing "Sandbox mode" on the game browse thing

The *entire point* of this mod is to make all save you load sandbox / "creative" mode. This is exactly what happened to your save. Why would it be a bug?

**Comment by SwitchLikesMlog** [comment]
is there a way for them to get their non-sandbox save back?

**Comment by Anuken** [comment]
No, not in vanilla.

**Comment by G-3-K-Y** [comment]
Can't i like export the save on another device while keeping it on
vanilla/survival?

Il gio 9 dic 2021, 15:55 Anuken ***@***.***> ha scritto:

**Comment by Anuken** [comment]
No.

**Comment by G-3-K-Y** [comment]
Ok thanks anyway

Il gio 9 dic 2021, 16:36 Anuken ***@***.***> ha scritto:

**Comment by Quezler** [comment]
@G-3-K-Y you _could_ re-install [the mod](https://github.com/RebornTrack970/Sandbox-Mode) and then go to your mods folder to unzip(?) the mod and edit this file, simply set infinite resources on the 2nd line to false & save, then afterwards your campaign should turn back to normal.

(you might have to delete the zip or re-zip to prevent 2 versions of the mod from useless-machining eachother, and any sandbox games you make may switch mode as well, so i suggest only turning the patched mod on when playing the campaign)
