### ISSUE TITLE
Ground Units not pathfinding to a command center

### ISSUE THREAD

**Issue by TonkyBoi** [Anuken/Mindustry#6421]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *Ground Units not pathfinding to command center set to rally*

**Steps to reproduce**: *I was playing on an attack map I made, and I had produced some dagger mechs. I had a command center placed and set it to rally and the daggers were not pathfinding to it. I made sure that they had a path to the command center, but they still were not pathfinding to it. The daggers have no problem pathfinding when the command center is set to attack, but they just stand in place when it is set to rally. I have figured out a way to make them pathfind to the command center but it is tedious to do and it involves completely removing the command center and placing another in a different location, and it sometimes doesn't work. Also, when I completely deconstruct the command center when it is set to rally, the ground units all assemble at where the command center was. I don't think my map is causing the problem because this also happens in other single player saves and sometimes in multiplayer. The map I was playing on is the most recent "train attack v7" save.*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *[https://drive.google.com/drive/folders/1lPMxPuz8jPfhS8z7l83yzdfNyWdWCLn5?usp=sharing]*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have uploaded your entire save data, which is 243mb and unusable. I can only test individual saves. I'm also unable to download from Google Drive - you should send saves as zipped files uploaded on Github, as instructed here.

---

I cannot reproduce this problem across several maps, so the problem likely lies with your setup.

**Comment by TonkyBoi** [comment]
I added the individual map save into the google drive folder

**Comment by Anuken** [comment]
I am unable to use Google Drive, as mentioned above. It's not functional in my browser.
