### ISSUE TITLE
Incoming phone calls disable the sound until I restart the game.

### ISSUE THREAD

**Issue by Inglonias** [Anuken/Mindustry#6424]
**Platform**: *Android 12 on a Pixel 5A*

**Build**: *Release 126.2*

**Issue**: *Incoming phone calls disable the sound until I restart the game. Not sure if this is something that is in your power to fix, but I figured I would report it anyhow*

**Steps to reproduce**: *Play normally, then receive a phonecall while the game is unpaused and running. Regardless of whether or not I answer the call, the game's sound is disabled until I restart the game.*

**Link(s) to mod(s) used**: *No mods*

**Save file**: [mindustry120921-1.zip](https://github.com/Anuken/Mindustry/files/7693855/mindustry120921-1.zip)

**(Crash) logs**: *Not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate issue.

**Comment by Inglonias** [comment]
Ah. #4114. And it's marked as "Won't Fix". Fair enough. Sorry to waste your time.

**Comment by Anuken** [comment]
I believe it was fixed upstream in the sound library I use at some point, but I haven't tested if that's actually the case.
