### ISSUE TITLE
Export calculation 

### ISSUE THREAD

**Issue by BaseModMaker** [Anuken/Mindustry#6429]
**Platform**: `Android 29`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*
If you export items from one sector to another the game calculates an average and uses it to export that amount of items to the selected sector. Execpt that that average just sometimes dissappears and then you get nothing anymore. And then you have to go back to the launch sector and wait for a minute or two for the average to come back to normal. This is horribly annoying if you have factories that span over multiple sectors. 
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just export a large amount of items to anothe sector and continue playing, the export will diminish or stop
**Link(s) to mod(s) used**: `none`
None
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
https://drive.google.com/file/d/1XSH-QTkZtOEBTNAN13yZegnwofCMy2h5/view?usp=drivesdk
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

-X-

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. You are **not** using the latest version.
2. This is likely a duplicate.

**Comment by RebelXl** [comment]
My game crashes when I try to build silicone factory I enabled many moss and I'm playing on an android phone version 135 help
