### ISSUE TITLE
Editor Bug iOS

### ISSUE THREAD

**Issue by TurkeyTray** [Anuken/Mindustry#6436]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: There is a bug with the editor on iOS. The tools for it get cutoff while using it. I use an iphone 10

**Steps to reproduce**: To reproduce this open the editor on an iphone 10  and zoom in to the map so it fills the screen. 

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is most likely related to a bug fixed in the v7 TestFlight version, but as you have not attached a screenshot, I can't tell for sure.

**Comment by TurkeyTray** [comment]
sorry. here is the screnshot
![09DDA172-5DBF-436C-ABD2-473D1BC00D2D](https://user-images.githubusercontent.com/45246713/146294831-aa6d2c7c-c3f0-45bd-9982-99afd9cf2d04.png)

**Comment by Anuken** [comment]
To be certain, you could try joining the [TestFlight](https://testflight.apple.com/join/79Azm1hZ) and seeing if that version fixes the problem.

**Comment by TurkeyTray** [comment]
Yes. Thank you! This does fix the problem and it makes me more excited for the next update!

**Comment by TurkeyTray** [comment]
Greetings,

I am the one who was having trouble with the Mindustry editor. I’m
wondering if you want me to keep the beta as I am not an official beta
tester nor have the qualifications. If you don’t, would you please help me
uninstall the beta without removing all game data.

Sincerely,
Turkeytray

**Comment by Anuken** [comment]
You don't need any qualifications or obligations to use the beta/alpha version. I've never actually tried downgrading from a beta version, but if you export your game data to your files (Settings -> Game Data), it should be safe, since you'll be able to re-import it in the same place even if your data gets lost after re-installation.
