### ISSUE TITLE
unable to build on armhf

### ISSUE THREAD

**Issue by oxmc** [Anuken/Mindustry#6437]
**Platform**: *Raspbian GNU/Linux 10 (buster)*

**Build**: *22261*

**Issue**: *Unable to build build: 135 on armhf raspberry pi 4 4GB*

**Steps to reproduce**: *run git clone https://github.com/Anuken/Mindustry && cd Mindustry && ./gradlew desktop:dist*

**Link(s) to mod(s) used**: *none*

**Save file**: *none, unable to even run the game*

**(Crash) logs**: *pi@raspberrypi:~/Mindustry $ ./gradlew desktop:dist
Downloading https://services.gradle.org/distributions/gradle-7.3-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
No Android SDK found. Skipping Android module.

> Configure project :
Compiling with build: 'custom build'

> Configure project :desktop
Scheduling sprite packing.

> Task :annotations:clearCache

> Task :annotations:compileJava
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens
WARNING: Unknown module: jdk.compiler specified to --add-opens

> Task :annotations:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':annotations:compileJava'.
> Java compiler is not available. Please check that /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-armhf contains a valid JDK installation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 9s
2 actionable tasks: 2 executed*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
How about
>check that /usr/lib/jvm/adoptopenjdk-16-hotspot-jre-armhf contains a valid JDK installation
?

**Comment by Hexrotor** [comment]
Mindustry doesn't support arm platform

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

You have not; this was reported countless times. Mindustry doesn't support ARM - I have already explained why in those issues.
