### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ilya034** [Anuken/Mindustry#6445]
**Platform**: *Windows*

**Build**: *problem while building the game, commit 24d3054bac5daf9c41a4331982a1903bf9ca6ba7, JDK 16.0.2, gradle7.3, android sdk command line tools 7583922, sdk platform/buiding tools I didn't install it myself*

**Issue**: *when assembling (command: **gradlew android:assembleDebug** or **desktop:dist**) an error occurs:*

      > Configure project :android
      No keystore property found. Releases will be unsigned.
      Checking the license for package Android SDK Platform-Tools in C:\Users\Home\Downloads\android-sdk\licenses
      License for package Android SDK Platform-Tools accepted.
      Preparing "Install Android SDK Platform-Tools (revision: 31.0.3)"
      
      FAILURE: Build failed with an exception.

      * What went wrong:
      A problem occurred configuring project ':android'.
      > Failed to notify project evaluation listener.
         > 'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'*

with *--stacktrace*: **Caused by: java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'**

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate; this was already reported and cannot be reproduced.
