### ISSUE TITLE
Game opens when running in v6, not in v7

### ISSUE THREAD

**Issue by TRMuhittin** [Anuken/Mindustry#6446]
**Platform**: *Linux Mint*

**Build**: *135*

**Issue**: *The game does not open in v7, I believe the reason is due to the linux distributor or the java system.*

**Steps to reproduce**: *I downloaded the new versions, I downloaded them to different folders in case there was a file error.*

**Link(s) to mod(s) used**: *none*

**Save file**: *problem in game system.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
As the template says:

> Crash logs: REQUIRED if you are reporting a crash.

There is nothing I can do with the information you have provided.

**Comment by Bottinator22** [comment]
This isn't a crash

Also, why the hecc would installing v7 open v6 instead? You're not installing the game properly
