### ISSUE TITLE
Modded router ca only carry 1 item

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry#6447]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Window 10 (sorry linux)
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
pre-alpha build 135
**Issue**: *Explain your issue in detail.*
modded router can only carry one item at once
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
add a router with itemCapacity higher than 1
go to a custom game, place and try to use it
-> it wont carry more than 1 item
(i fixed it in my scripted router by changing acceptItem(source, item))
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
EclipseTheOldOne/Project-Eclipse (my mod)
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
mmm yes it happen everywhere i guess
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

--- none, router isn't that dangerous

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Routers are designed to carry only one item.

**Comment by EclipseTheOldOne** [comment]
![Screenshot_73](https://user-images.githubusercontent.com/43229798/146876095-ac628d50-dade-4303-97ed-129609f08976.png)
~~how about no~~
