### ISSUE TITLE
Every sector is attacked

### ISSUE THREAD

**Issue by Dugger1** [Anuken/Mindustry#6450]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *I turned on the game and for no reason they were all under attack. I didn't do anything and I don't know why this is happening to me. I may be the only one but I'm sure not.*

---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SwitchLikesMlog** [comment]
you should provide your save file btw

**Comment by wdmvv** [comment]
also crashlog?

**Comment by Anuken** [comment]
No save or crash provided.
