### ISSUE TITLE
a server bug

### ISSUE THREAD

**Issue by aawwaaa** [Anuken/Mindustry#6453]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Steps to reproduce**: *

build it in a mindustry server

bXNjaAF4nGNgZGBkYmDJS8xNZeAoSS0uKSjKT2bgTkktTi7KLCjJzM9jYGBk4M/NTC7K1wXJpRYX5xcxgARBgI+Bgcm2Yk7q1Ot5wY4iroeFJ+1/pHBxdfq7uW7v934XizIQMNAt45h7/tF3C+vbNinW/Bel3KPSM8+53NuyYcPP97dOfSpJcY6W6j1+8FDCY8tTOycX6z9Xea7zXOm51nO15wZX+LcYZCRdOLZgoqN2cxrbWx4pqS0mWZlzdnvr9kZJbQUyr1xasTTQe/G0sqhbmZnm28t0327ZcvmSn7c1hBHnXa37duuW+dULo25lZ65funfaNxDj0qUlSz29J09btrNeTdc3atYWk0yg2Jqlkd6bpz37v7Tw28ECA0nfs9fq8w8+ZljTo7b68cs3+dJ80R8lGG5/4GC4vbHmAJ+O7Abh02xvDk1i3L0x5oCcjugG8dMsbw4LMf7eaHOAUYfX4MgmhtfeTC467BcSNRvkTjOo6DBOKPzZ0OTNHhJjtuDhJEb2wp0NzjtCDiTGqD3g0BMsEJnObtHmzSyz3ecz52mT+Vt8PmsCqW0+nyWB1Fanz5baJvO3O31m1TaJ3+L0WRVIbXP6LAqkgHKmQGq712fe1Sb3t3h91gVS27w+ywKprV6fbYEUUI55tYn9FrfPytkm9tvcPi8ynTU/YvHPlUAqcvHPnaaz4iMWV56UOqv/N7vh1UThu+vnaNS/dfktrf5q+twX9a+PML6fY5H45ojg+7kWj5vrNxccc1c/9+PJEcn5c9PW3+k0VvOb87Bft+DYKuH0msJHPaZAyVfxYXM+nu003mddeIwfyH95RHL/HIvH24XT/xRqNbP+/8luO1tVmhkAW/YsKQ==

*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Place an X (no spaces) between the brackets to confirm that you have read the line below.

You have not done this, and if you did either of them, you would know that this has already been reported fixed.
