### ISSUE TITLE
Schematic bugs

### ISSUE THREAD

**Issue by KODON234** [Anuken/Mindustry#6458]
**Platform**: *Android*

**Build**: *126.2*

**Issue**: *schematic display/picture often didnt show up on schematic menu/section whenever i access it.*

**Steps to reproduce**: *happen sometimes to times whenever accessing the menu.*

**Link(s) to mod(s) used**: **

**Save file**: *i dont know since i play it on android and also the save mode is automatic and i play it with campaign mode *

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are not using the latest version; this is unlikely to be an issue in v7.
