### ISSUE TITLE
Export/Import Filepath stuck on C:/

### ISSUE THREAD

**Issue by apocist** [Anuken/Mindustry#646]
**Release: 4.0 Build 92, Desktop JAR, Windows 10**

When attempting to Export or Import a file in the system, the Mindustry file browser is unable to move out of the C:/ drive to access the saves stored in D:/.

Can be in the root directory of C:/ and click on `../`, but nothing happens.

Note that Mindustry is currently saved and running  on D:/Games/Mindustry

**Comment by Anuken** [comment]
Fixed.
