### ISSUE TITLE
[Question] Is there a way to choose what a GenericCrafter produces?

### ISSUE THREAD

**Issue by Beanzilla** [Anuken/Mindustry#6460]
**Platform**: *Linux*

**Build**: *134.1*

**Issue**: I am a mod developer who has developed [M1NEDU5TRY H4CK3D](https://github.com/Beanzilla/mindustry-hacked).

In my content, I have a `Item Replicator (*)` (Where \* is a number of resources), Is there a way I could make a crafter which takes power and provides a list of items to produce then produces selected item? (I really don't like Java, but I am just about to take up learning it, just to get this one thing implemented)

> Or I might just leave it the way it is and let players complain and not do anything about it. (Since it looks more like it's not possible, but rather just a random choice of items list, which is not what I want)

> Put it in different light, a `Item Replicator (*)` is essentially a `Item Source` just takes power and doesn't produce as fast as it can. ( For those not understanding my question)

**Steps to reproduce**: N/A

**Link(s) to mod(s) used**: [M1NEDU5TRY H4CK3D](https://github.com/Beanzilla/mindustry-hacked)

**Save file**: N/A (Not needed, since this is mod content)

> No soul reaping needed. ( :) )

**(Crash) logs**: N/A (Not reporting a crash)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

---

Further Notes:

1. Yes I am aware "Questions are supposed to be placed on Discord" (However I do not use Discord, and NEVER will, just don't ask)
2. I have looked at [Types](https://mindustrygame.github.io/wiki/modding/5-types/#genericcrafter) searching for `GenericCrafter` shows the current item/machine I am using for Item Replicators. (So one way to solve this is to point me towards a better machine that could do what I want it to do)

- [ ] Some Resolution Found

**Comment by GlennFolker** [comment]
You know "question" isn't an "issue report," right?

**Comment by Anuken** [comment]
> Is there a way I could make a crafter which takes power and provides a list of items to produce then produces selected item?

This is *possible*, but there is no built-in mechanism for it. Closing, as this is an **issue tracker**, not a forum for discussion - ask on the Discord if you need help with modding.

**Comment by GlennFolker** [comment]
> However I do not use Discord, and never will
Well, there goes your chance of getting answers.

**Comment by Beanzilla** [comment]
I think I found a way to make it work.

Hijack Item Source so it requires/consumes power. (Not sure if this will stop producing items if it doesn't have power but at least it should allow me to have a choice menu to choose what gets produced, just like bye bye to making it produce at a timed rate)

> TBO I really could care less if I get answers. (It puts negative light on those who won't work with folks who won't use Discord, not those who fail to use Discord because they don't want too / for various reasons)
