### ISSUE TITLE
Poly Rebuilding Loop when Destroyed (even when attempting demolish)

### ISSUE THREAD

**Issue by PlanetOrca** [Anuken/Mindustry#6461]
**Platform**: *iOS*

**Build**: *126.3*

**Issue**: *Buildings created within range of many enemy turrets, namely enough to where it can be destroyed faster than it can ever be manually demolished, and having polys working on it will cause an endless loop of the plots attempting to rebuild it even when you try to demolish it. The problem can be generalized as "If building is being destroyed by enemy before you can demolish it, polys will not stop rebuilding it"*

**Steps to reproduce**: *Steps explained exactly as necessary in previous *

**Link(s) to mod(s) used**:*Just factoriodustry, a non-content changing textures mod*

**Save file**: * https://ufile.io/ubf8fjeb*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hexrotor** [comment]
To tell the truth this is not a bug. You can just select the destroyed blocks to delete them without deconstructing.

**Comment by Anuken** [comment]
This is not a bug.

**Comment by LocalLegend517** [comment]
https://github.com/Anuken/Mindustry/issues/6461#
