### ISSUE TITLE
Crash when host attempts to occupy the same turret as another player

### ISSUE THREAD

**Issue by emorrp1** [Anuken/Mindustry#6462]
**Platform**: Linux

**Build**: pre-alpha build 135

**Issue**: Crash, but only when the *host* does it

**Steps to reproduce**:

1. Open Ground Zero and Host
2. Join as a guest player (see command below)
3. Guest occupies duo turret with ctrl-click
4. Host attempts to occupy the same duo

```
dir=$(mktemp -d); java -Djava.io.tmpdir=$dir -Duser.home=$dir -jar ~/downloads/Mindustry.jar &
```

**Link(s) to mod(s) used**: unmodded

**Save file**: [occupy-crash.zip](https://github.com/Anuken/Mindustry/files/7796353/occupy-crash.zip) This was created by resetting game data and just launching the campaign.

**(Crash) logs**: [occupy-crash.txt](https://github.com/Anuken/Mindustry/files/7796354/occupy-crash.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in dev branch.
