### ISSUE TITLE
Logic unit control sensor/within instruction output unit that are not binded by the logic.

### ISSUE THREAD

**Issue by nekoma0** [Anuken/Mindustry#6467]
**Platform**: Windows

**Build**: Tested on both V6 Build 126.2 and V7 Build 135

**Issue**: ucontrol within/sensor(i only tested ucontrol within and sensor xy position) 
Bug only happen in multiplayer, i've /sync every 1~2minutes or so, to make sure double/triple confirm that it's not a sync issue.
![ShareX_2022-01-04_08-09-45](https://user-images.githubusercontent.com/21262949/148034991-d8382ba7-b63f-411b-b5af-2e3bd0259b9b.png)
the image above is where my mouse hover above the logic, which shows the mono is currently undercontrol by the logic(diamond shape on the mono), which spins around the logic.
the location of the logic processor is 113,309
![ShareX_2022-01-04_08-10-00](https://user-images.githubusercontent.com/21262949/148035256-60afd33c-a927-4dec-89e8-2aa5c472a43a.png)
this image is where my mouse hovers on the message block to show the message, i've added sensor x and y of the binded unit, to output the position of the unit to the message block. and i've make sure to /sync a couple of times to makesure it's not desync.

the output of the X and Y location is not the unit that the logic is controlling. 248,255

the image above is the tested in mindustry.ddns.net public sandbox server.

**Steps to reproduce**: Join a public multiplayer server, make logic, bind unit and test ucontrol within or sensor feature. there's a chance that it this bug will happen.(Depending on how busy is the server? possibly? not sure)
I've also tested in multiple community public sandbox server to make sure about this.
Server tested are. Korea Sandbox(V7), Omega Sandbox(V7),DarkDustry Sandbox(V7), Chaotic Neutral Sandbox(V6), mindustry.ddns.net Sandbox(V6), Sakura sandbox(V6)
I suggest go to public sandbox multiplayer for convenience sake.
I'll also be attaching a schematic here(please use pastebin if you felt the file is not safe) and posting a link to pastebin that contains the schem for testing, convenience sake that is.
https://pastebin.com/cAkkN5YB
[ucontrolwithintestset.zip](https://github.com/Anuken/Mindustry/files/7806529/ucontrolwithintestset.zip)

**Link(s) to mod(s) used**: the only mod that i use is logic debugger.

**Save file**: i've chosen to not submit a save file, i've tested this issue for a few day, and have completely confirm that this issue does not happen in single player, i also went to public multiplayer sandbox, recreate the bug. then saves the map. then load the game in singleplayer, and the bug went away. You can reap my soul if i`m in any offending way.

**(Crash) logs**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nekoma0** [comment]
Adding additional info:
while i am not sure about another players viewpoint in game, but when this bug occurs, if your mouse hover above the logic, it will shows 2 units of the same type is binded by the logic(provided if you manage to have 2 of the unit within your view screen.)

**Comment by nekoma0** [comment]
> If you use any ucontrol whatsoever, the unit counts as controlled this includes ucontrol within

May i ask what are you trying to point out?

**Comment by Anuken** [comment]
There is a significant amount of code and unit setup at play here - I don't see anything wrong happening when I try this myself. I don't debug logic bugs unless you can specify *exactly* what is going wrong and why some logic output is incorrect.

If the problem is:

> the output of the X and Y location is not the unit that the logic is controlling.

...then it could be caused by outside factors, like other processors interfering with a bound unit.

**Comment by nekoma0** [comment]
> ...then it could be caused by outside factors, like other processors interfering with a bound unit.

i've tested it on a fresh new map where, and i even double confirm with foo client, find block feature to make sure there's no logic on map before i make mine, so im pretty sure its not other processor is interfering with a bound unit.

plus, do you mind to elaborate how another processor would be possible to interfering with the bound unit that causes sensor to output data that is not bounded by the unit?

from my brain, what i could understand is.
LOGIC A, Bound "Unit01"
if LOGIC B, Bound "Unit01" as well, then what will only happen is they fight control over the same unit, but that does not influence sensor if they both are running sensor on "Unit01"

I could make videos about this bug happening on public server, i need time to find a empty sandbox public server, so i do a recording where, i /rtv to force gameover and start anew map, then proceed to scrap everything possible on map. and build build the schem to test.

i'll post a full video when i manage do it when sandbox server is empty.

**Comment by nekoma0** [comment]
sorry, i can't find a empty sandbox to do this, so i'll post one where i tried to find processor using foo's client feature to make sure there's no other logic is conflicting with my logic.
https://youtu.be/7mutiFmY-w4
