### ISSUE TITLE
The buildings of the derelict team are displayed on the minimap as the buildings of my team

### ISSUE THREAD

**Issue by NullReferenceExc** [Anuken/Mindustry#6468]
**Platform**: Android

**Build**: 135

**Issue**: The buildings of the derelict team are displayed on the minimap as the buildings of my team when I start destroy them
![Screenshot_20220105-124325.png](https://user-images.githubusercontent.com/65529860/148208297-caf4d9da-67ab-4c6e-8d6b-5cce211f5187.png)

**Steps to reproduce**: I destroy building of derelict teram, and it is displayed on the minimap as the buildings of my team.I was playing in the company when I found this bug

**Link(s) to mod(s) used**: Destroy any building of derelict team

**Save file**: https://disk.yandex.ru/d/8BVftbRFx_D5Fg

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: It is not crash

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Arcanilius** [comment]
If You start destroing an derelect building, and then right after starting to destroy you start to rebuild it it will be your building, even If you didn't reserched it.
Should i post it as another Bug?

**Comment by Bottinator22** [comment]
Deconstructing derelict buildings makes them yours. This might not be a bug

**Comment by Arcanilius** [comment]
Really? I just delete everything with some help from a poly for resourses.

**Comment by Bottinator22** [comment]
V7 disables rebuilding them if you don't have them researched

**Comment by BlueWolf3682** [comment]
This is not a bug - deconstructing derelict buildings puts them on your team intentionallyand reclaiming them is a valid option.
