### ISSUE TITLE
"Clear game data" deletes all screenshots and other files too

### ISSUE THREAD

**Issue by Vallkyr1** [Anuken/Mindustry#647]
It empties the entire folder, including the screenshots folder and any save backup you have stored there. Would be better if it only deletes the actual save file

**Comment by Anuken** [comment]
I disagree. If you want to keep your screenshots and backup data, copy it out of the folder manually. The option is there so users can do a complete wipe of their data, clearing the disk space used by screenshots and (potentially problematic) cache as well.
