### ISSUE TITLE
Привет Антон, Hello anuke

### ISSUE THREAD

**Issue by VladIsLover** [Anuken/Mindustry#6472]
У меня есть проблема на платформе андроид версии 7 билд 135
Дело в том что когда я ставлю кремниевую плавильную игра просто напросто вылетает и так каждый раз, пожалуйста не игнорируйте и пофиксите этот баг 

I have a problem on android platform version 7 build 135
The fact is that when I put a silicon melting game, it simply crashes and so on every time, please do not ignore and fix this bug.

**Comment by SwitchLikesMlog** [comment]
crash log? how to reproduce? rip template

**Comment by Anuken** [comment]
Это проблема с модами, не с Mindustry. Выключите все ваши моды.
