### ISSUE TITLE
Using GenericCrafter to outputLiquid causes crash

### ISSUE THREAD

**Issue by Beanzilla** [Anuken/Mindustry#6473]
**Platform**: *Linux*

**Build**: *pre-alpha 134.1*

**Issue**: I added an mod building which takes power and should produce a liquid, instead I got crashes talking about NullPointer.

> Or is it just another user error using [GenericCrafter](https://mindustrygame.github.io/wiki/modding/5-types/#genericcrafter).

**Steps to reproduce**: I went to place `Liquid Replicator (Water)` in which the game immediately crashes, up on further investigation on if I did serious damage I caused it to crash again when I loaded the save with the original settings (I changed them around back to producing an item just to verify everything else works, which it did)

**Link(s) to mod(s) used**: 
[BlueWolf3682Exotic-Mod.zip](https://github.com/Anuken/Mindustry/files/7832751/BlueWolf3682Exotic-Mod.zip) 0.7 Alpha
[mindustry-hacked](https://github.com/Beanzilla/mindustry-hacked/releases/tag/v0.3.1) v0.3.1

**Save file**: 
[sector-serpulo-86.zip](https://github.com/Anuken/Mindustry/files/7832757/sector-serpulo-86.zip)

No soul reaping needed.

**Crash logs**: 
1. [crash-report-01_08_2022_01_30_00.txt](https://github.com/Anuken/Mindustry/files/7832758/crash-report-01_08_2022_01_30_00.txt)
2. [crash-report-01_08_2022_01_35_59.txt](https://github.com/Anuken/Mindustry/files/7832760/crash-report-01_08_2022_01_35_59.txt)
3. [crash-report-01_08_2022_01_57_54.txt](https://github.com/Anuken/Mindustry/files/7832770/crash-report-01_08_2022_01_57_54.txt)

> The third crash is from me moving from pre-alpha 134.1 to the lastest afbac48 (Release 6.0 Build 126.2) release
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You did not set `hasLiquids` to `true` on your block.

**Comment by Beanzilla** [comment]
Thank you for the help. (Now to just update the mod so it works with the correct information in it)
