### ISSUE TITLE
Small typo 

### ISSUE THREAD

**Issue by Axlii50** [Anuken/Mindustry#6491]
https://github.com/Anuken/Mindustry/blob/f5701ba3c42ca4be5b4b2e8b1037389cb73e716a/core/assets/bundles/bundle_pl.properties#L1021

Small typo with "Rdzeń Spala Nadmarowe Przedmioty" and should be "Rdzeń Spala Nadmiarowe Przedmioty"

**Comment by Anuken** [comment]
I do not write any of the translations myself; if you see a typo, make a PR.
