### ISSUE TITLE
if you fly away from the illuminator, it will go out sharply; if you fly up, it will light up sharply

### ISSUE THREAD

**Issue by Kurai-zu** [Anuken/Mindustry#6494]
**Platform**: `Android 29`

**Build**: `pre-alpha build 135`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, Hydroabyss/sporepod:0.9, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![2022-01-14-11-14-35](https://user-images.githubusercontent.com/10100000/149548338-9d327b12-39da-49ba-be48-710fe034db03.gif)

**You have not filled in the template.**

**Comment by Bottinator22** [comment]
I experience this bug too

**Comment by SMOLKEYS** [comment]
~~@Anuken perhaps use issue forms? Issue forms can't be submitted unless fully filled out.~~

**Comment by itcannotbe** [comment]
> perhaps use issue forms? Issue forms can't be submitted unless fully filled out.~

There legitimate reasons to ignore some parts of the template though.

**Comment by Anuken** [comment]
> perhaps use issue forms

I started working on one, but it doesn't really stop people from omitting crash reports or saves, since those do not apply to all issues.

**Comment by Bottinator22** [comment]
The bug still happens with other blocks, but it seems to have already been fixed for the Illuminator

https://user-images.githubusercontent.com/59987380/149639051-e6cfbf00-0166-459b-b981-24240cca6fa8.mp4

**Comment by Anuken** [comment]
I can't tell which block that is.

**Comment by Bottinator22** [comment]
Nor can I.
