### ISSUE TITLE
Why do daggers fly and shoot? (version 135)

### ISSUE THREAD

**Issue by StalkerSerega** [Anuken/Mindustry#6499]
https://user-images.githubusercontent.com/97840260/149665073-ff0f2768-2e10-4af5-b854-0e5f8dd21d62.mp4

**Platform**: `Windows 10 x64`

**Build**: `pre-alpha build 135`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[[#ff0][#fff]paulieg626/admintool:1.0, Slotterleet/distributor:1.0.1, AureusStratus/exogenesis:[blue]1.4]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mods.
