### ISSUE TITLE
Way too approximative calculation of sector defense when player isn't in it

### ISSUE THREAD

**Issue by CreebotTheGreat** [Anuken/Mindustry#6504]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: V7 135

**Issue**: I was doing things in Biomass Synthesis Facility when one of my vulnerable sectors (Which is in this case Nuclear production complex) went under attack. The defenses are overkill, as stated by many people to whom i showed them. Yet, in litterally 8 to 10 seconds, and i kid you not, at most 10 seconds, the sector was lost.
And no, it couldn't have been the guardian, no guardian comes 10 seconds into the attack, even if you're not there.
IMPORTANT - I get that the simulations are incorrect to an extent, but my defenses were litterally about 20 tiles thick, all-around, and filled with turret of various types including foreshadows, as well as decoys for bosses (such as 4 INACTIVE thorium reactors. I insist that they were inactive so that you won't tell me that the enemy broke the cooling system and exploded the defenses). The calculation algorythm should at least take into account the number and type of walls, enemies and turrets into the mix. Plus, in 10 seconds, i refuse to believe that so many efforts can be ruined to bits.
And, also, even if by some dark magic the enemy DID breach the defenses, the placement of the core would've taken more than 10 seconds to reach, even for fast troops in this sector such as crawlers.

NOTE - The save file could be a bit late, i don't know if they're generated upon leaving or entering the sector.  as i couldn't predict when would the attack happen and i don't know if providing a save file from before would cut it anyways since it's random. Though if i am wrong an that the attacks are planned in advance, i can provide one. Just let me know. 

Also... If you open the save file... pardon the horrible base there. I know, it's terribad. my apologies again.

**Steps to reproduce**: Capture a vulnerable sector, make overkill defenses, wait for an attack, and be unlucky enough that the algorythm decides to low-roll so deep in hell that you lose in 10 seconds.

**Link(s) to mod(s) used**: None

**Save file**: 
[sector-serpulo-81.zip](https://github.com/Anuken/Mindustry/files/7887083/sector-serpulo-81.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You haven't even sent the save for the sector that was lost, so I can't test this.

**Comment by Bottinator22** [comment]
what's sector-serpulo-81.zip?

might be new

**Comment by Anuken** [comment]
That is not the sector in which the waves were taking place.

**Comment by BlueWolf3682** [comment]
This is a confirmed issue - I have lost 3 sectors in seconds despite having extremely overkill defenses. The issue seems to be the pathfinding kinda chooses a path instead of following generic ground unit pathfinding or, for air, using the air units path. This may be very difficult to fix, as it requires the games code checking for bait *and* checking all unit pathfinding paths.
