### ISSUE TITLE
Processor inconsistent behaviour

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry#6508]
**Platform**: *Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam 135

**Issue**: *Explain your issue in detail.*
I made a logic thing that makes units patrol. For whatever reason, the units seem to be "leaking" their radar findings to others.
The program checks the unit radar every processor loop for targets, and the units that find targets should stop patrolling and immediately start attacking and maintaining a distance from the target. Units that do not have enemies in their radar range should not find targets, and should continue moving around the predefined waypoints.

For whatever reason though, the radar, or whatever else that's broken and is causing this, has some pretty inconsistent behaviour. It works most of the time, but sometimes it seems to spread its findings to other units, resulting in units losing track of their targets for a processor loop, or units twitching towards the target.
This is more visible with an overdrive dome.

**Steps to reproduce**: 
Make a logic program that makes units patrol, and individually attack units they find.
Here's my code, I couldn't find anything related to this problem in it:

```
set patrolType @zenith
set waypointReachDis 4
set attackDisOffset 4
ubind patrolType
uradar enemy any any distance 0 1 target
jump 16 notEqual target null
ucontrol targetp null false 0 0 0
sensor curWaypoint @unit @flag
op mul xloc 2 curWaypoint
op add yloc xloc 1
read x bank1 xloc
read y bank1 yloc
ucontrol move x y 0 0 0
ucontrol within x y waypointReachDis waypointReached 0
jump 23 notEqual waypointReached false
end
sensor x target @x
sensor y target @y
sensor range @unit @range
op sub dis range attackDisOffset
ucontrol approach x y dis 0 0
ucontrol targetp target true 0 0 0
end
op add newflag curWaypoint 1
op mul xloc 2 newflag
op add yloc xloc 1
read x bank1 xloc
read y bank1 yloc
op add sum x y
jump 31 notEqual sum 0
set newflag 0
ucontrol flag newflag 0 0 0 0
```
(There's a nearby memory bank containing the coords of the waypoints)

**Link(s) to mod(s) used**: logic-debugger, though I doubt it's the cause.

**Save file**:  [logicbug.zip](https://github.com/Anuken/Mindustry/files/7901306/logicbug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
This isn't a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
hang on, forgot to submit a video, was gonna

**Comment by Bottinator22** [comment]
https://user-images.githubusercontent.com/59987380/150239873-7046526c-44bf-43a1-8349-ff965a6a53eb.mp4

**Comment by Anuken** [comment]
The radar instruction caches its results; this is a duplicate, see https://github.com/Anuken/Mindustry/issues/4930#issuecomment-797836560

**Comment by Bottinator22** [comment]
hm

well, guess I'll have to add in some sort of instruction cycling system then

**Comment by Bottinator22** [comment]
Why does it cache the same results for all units though?

**Comment by Anuken** [comment]
The cache depends on the instruction object itself, not the parameters.
