### ISSUE TITLE
Banned units are able to be made using logic

### ISSUE THREAD

**Issue by WMF-Industries** [Anuken/Mindustry#6516]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 11 64bit
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
v135 pre-alpha
**Issue**: *Explain your issue in detail.*
Banned units can be made by using logic to force an lower tier unit into reconstructor.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
- open the game
- edit a map, banning horizon or any other unit
- play the map
- use logic (payEnter function)
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[bug.zip](https://github.com/Anuken/Mindustry/files/7918161/bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
Fixed in v7 private branch. Wait until 136 build

**Comment by SwitchLikesMlog** [comment]
👀
