### ISSUE TITLE
deconstructor abuse

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#6518]
**Platform**: *Android/iOS/Mac/Windows/Linux*
all

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
135

**Issue**: *Explain your issue in detail.*
(de)constructors ignore build cost multiplier, which allows you to dupe items by building blocks normally then deconstructing them

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
set buildCostMultiplier to 0.1, make block via unit, carrry via payload into deconstructor

**Save file**
probably not needed since it's kind of obvious how to find/fix it even without one

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in private branch.
