### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by NeonSupernova** [Anuken/Mindustry#6519]
**Platform**:
 Chromebook (Not from playstore) Though technically Linux

**Build**:
 **135 pre-alpha**

**Issue**: 
Missing a shared library libsdl-arc64.so

**Steps to reproduce**:
`java -jar Mindustry.jar`
with jdk > 16

**Link(s) to mod(s) used**:
**NA**

**(Crash) logs**:
[crash-report.txt](https://github.com/Anuken/Mindustry/files/7919024/crash-report.txt)

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[[Anuken/Mindustry/issues/5783]]
^ similar issue reported here, but for a previous version. Not sure if it still applies.

**Comment by Anuken** [comment]
Mindustry extract shared libraries to `/tmp/`, and in your case it can't use them: "file not located on exec mount". This doesn't happen to me on any Linux system, and it's almost certainly a problem with your filesystem. Won't fix.

**Comment by NeonSupernova** [comment]
Any chance I can change the path to `/usr/tmp/`?

**Comment by Anuken** [comment]
You might be able to change Java's temporary directory with a launch argument: `java -Djava.io.tmpdir=/usr/tmp -jar Mindustry.jar`
