### ISSUE TITLE
Unit rendering is kinda broken

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry#6520]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *Units in-game lack that border around them and the core database makes the units look cursed as they're missing their weapons too*

**Steps to reproduce**: *Load into the save, load up core database*

**Link(s) to mod(s) used**: *Foos client*

**Save file**: *[Sandbox Map.zip](https://github.com/Anuken/Mindustry/files/7919389/Sandbox.Map.zip) Note: This occurred on a separate PC while playing an attack map, but I deleted the save upon completion bcus I thought it was just the old PC messing with Mindustry, then it happened on my 7-month-old laptop so here we are*

**(Crash) logs**: *N O*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Foo's Client bugs should not be reported here. This is not a vanilla bug.

**Comment by buthed010203** [comment]
For the record, it looks perfectly fine to me.
![](https://vexera.is-ne.at/5lXPqtSRa.png)
Create an issue on the client github or discord or something if you have any more info @3Circle.

**Comment by Anuken** [comment]
Could be related to another mod they haven't listed; I haven't even changed the unit code recently, and v135 has been out for a long time with no similar reports.

**Comment by buthed010203** [comment]
Fun, the CI packs sprites on each build so thats why I couldn't reproduce it... Forgot a null check and that caused some code to throw an exception which somehow caused weapons and outlines to not exist (kinda looks like v5 when theres no outlines lol). Either way, that's been fixed now.
![](https://vexera.is-ne.at/5m2ImGl2Y.png)
