### ISSUE TITLE
Controlling crawler on mobile is easy to cause chain explosion

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#6521]
**Platform**: Android

**Build**: 135

**Issue**: I know it's not a bug but on mobile you need hold the screen to control unit to fire, and there is no frequency limit in changing unit, which easily causes chain explosion when controlling crawler.
See this video, it's almost "uncontrollable", maybe add some code to aviod this.

https://user-images.githubusercontent.com/45112661/150659814-1b1121cf-6feb-4cc5-afb3-3274a4857a68.mp4

**Steps to reproduce**: Play on mobile and spawn some crawlers, control to explode

**Save file**: Not related

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Annoying or not, this isn't a bug, and should be posted in the suggestions repo instead.

**Comment by BlueWolf3682** [comment]
~~I have to mention that this was mitigated on the PC controls of the game - as far as I know, a feature that works properly only on a sinlge platform counts as a bug.~~

**Comment by Anuken** [comment]
The mobile version uses a different control scheme and is missing a lot of PC features, so not really.
