### ISSUE TITLE
gamma AI 

### ISSUE THREAD

**Issue by twos98** [Anuken/Mindustry#6524]
Platform : Linux

Build : 135

issue : when AI building is on and infinite resources is off it will try to place say a phase wall before it has phase fabric i would like to ask if you can make it where it will build factory's (like a phase weaver to be able to build phase walls) in order to get the correct items and so the AI dosent get stuck trying to build a phase wall or something high leveled

Steps to reproduce : make world with crux and sharded core => enable AI building for crux => disable infinite resources for crux => open world and let the AI build for a while until it builds a wall then you will see

Save file : 
[save file.msav.zip](https://github.com/Anuken/Mindustry/files/7921744/save.file.msav.zip)

**Comment by Anuken** [comment]
This is not a bug. Building a true functional base is immensely complicated for an AI; they are not supposed to build production structures.
