### ISSUE TITLE
smol pneumatic drill icon in research tree

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#6538]
**Platform**: Windows 10

**Build**: v135

**Issue**: the pneumatic drill is tiny in the research tab for some reason

**Steps to reproduce**: go onto campaign, look at research

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SwitchLikesMlog** [comment]
can you provide a screenshot if possible

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/151641529-0b6a83ed-7b51-44bf-a549-5ee6ede1629b.png)

Not on my end. You have not filled in the template or posted a screenshot of the problem.

**Comment by mse-k** [comment]
![image](https://user-images.githubusercontent.com/37938606/151668628-03c870d1-3751-4ad5-8980-ebbd7571427e.png)
it actually seems to be any content youve unlocked since your last game start, i just got slag and metaglass and both are small, as well as stuff that they unlock such as separators or logic displays, i have an idea of whats causing it but im not sure

**Comment by Anuken** [comment]
That doesn't happen to me either.
