### ISSUE TITLE
Unloader prioritisation funni

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry#6540]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *I have 2 pairs of 2 mixers, the mixers in each pair are connected by an unloader and the 2 pairs are connected by phase bridges. The pair that isn't directly receiving titanium will have low titanium levels until you remove the outbound phase bridge from that pair.*

**Steps to reproduce**: *Load the schempack map, find the 3 Impact SLT [it's just above the bottom left corner], and watch the tit levels of the two right cryo mixers. They'll have enough titanium to feed the impact but the tit levels are super low until you remove the phase bridge.*

**Link(s) to mod(s) used**: *Foo Client [My last bug report was just foo being sus and not loading properly but fairly sure this one extends to the vanilla game]*

**Save file**: *[Intervection's Schempack.zip](https://github.com/Anuken/Mindustry/files/7965298/Intervection.s.Schempack.zip) This setup here is essentially a recreation but has the same bug: bXNjaAF4nEVQy1LDIBQ9EAhpU3W6ct0PyBd1XKQJKjNJiCSp7Se68YO6wXtpVAa4r3POvYAd8gxqqHsLfTicljeUrZ2a4MbZ+QFA3tUn202Qx5cCpZttX01+CY3FfnZzPbilrxo/nO3VBzw14epfu8W1Ve8uNqDs3AdHZ+9aPKzByt+N/tOG36hYhs7XLXEex/d6sv+iwDN4aRpGCnIEBBsJIclkkFmqSkUVqRUBKEBWZAmUM3C1KmkY8rTht7GsUCyRaERi39ClTYzxm85e0P+wugTnaRueRKFYSYa8hP5KaI0Nt44RPJyMN2LmlEutibu5g29r6+1f6+1dvWT1H0jATDw=*

I will reap your soul.
*Please no I have a family.*

**(Crash) logs**: *Never gonna give you up~*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
:eyes:  @hortiSquash

**Comment by Anuken** [comment]
My guess is that phase bridges need `highUnloadPriority = true`.

**Comment by hortiSquash** [comment]
> My guess is that phase bridges need `highUnloadPriority = true`.

You cant unload from bridges, they are phase not ducts. Also it wouldnt change anything here

**Comment by hortiSquash** [comment]
@3Circle 
![image](https://user-images.githubusercontent.com/45213805/151695557-1317cb50-741b-4109-b590-426469d6a6bc.png)

its definitely a design issue in the first place, you shouldnt backflow so hard
@Anuken its about inputs in buildings, not unloaders

its the very same example as here:
![image](https://user-images.githubusercontent.com/45213805/151695776-0107f3b2-7f81-451b-9063-02358ccfa5a1.png)

(cross mark the belts that arent moving)

belts/bridges/unloaders being out of sync, thats all

**Comment by Anuken** [comment]
> You cant unload from bridges, they are phase not ducts. Also it wouldnt change anything here

Fair enough ~~probably should have loaded the schematic in-game before guessing.~~

**Comment by Ander292** [comment]
H m
