### ISSUE TITLE
Sound quality and core landing unsync

### ISSUE THREAD

**Issue by Vitoybed** [Anuken/Mindustry#6544]
**Platform**: `Android 25`

**Build**: `pre-alpha build 135`

**Issue**: *game sound make "ting" noise.*

**Steps to reproduce**: *when building and game music.*

**Link(s) to mod(s) used**: `[DeltaNedas, Router and another guy/pictologic:1.5.7, pixecoz/schematics-pack:8, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce.

**Comment by Ander292** [comment]
You need to say what did you do when the bug happened. It isn't clear
