### ISSUE TITLE
Allowing unloader to pick items from PowerBlock or CraftBlocks

### ISSUE THREAD

**Issue by mayli** [Anuken/Mindustry#655]
![ezgif-4-bacd8102f2e2](https://user-images.githubusercontent.com/822628/64832368-8716c700-d58e-11e9-85af-2608074404ce.gif)

This would enable some compact design of chaining power/craft blocks.

**Comment by ZkyLB** [comment]
That sounds like an **egg**celent idea!

**Comment by Milinai** [comment]
Why aren't the conveyors connecting to the alloy smelters? Do you need unloaders to output from every single block now?

**Comment by Anuken** [comment]
That's because the implementation shown uses `extends StorageBlock` to apply unloadability, which makes them inherit the trait of not linking to conveyors. My implementation uses a different approach, which doesn't have that issue.
