### ISSUE TITLE
Processor instruction to set the color of lights is actually Alpha Red Green not Red Green Blue

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#6550]
**Platform**: Windows 10

**Build**: v135

**Issue**: Unsure if the first argument is alpha as it has no effect, however it clearly isnt red, the next one is red, and then green, and you cant set blue

**Steps to reproduce**: use the set color instruction

**Save file**: [set color bug.zip](https://github.com/Anuken/Mindustry/files/7988404/set.color.bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Illuminator colors are in the range `0-1`, not `0-255`. You're causing a RGBA color overflow by setting the G to 255, which is a separate problem.
