### ISSUE TITLE
Phase/bridge conveyors/conduits do not function when being fed from opposite direction

### ISSUE THREAD

**Issue by null-dev** [Anuken/Mindustry#656]
I'm just going to start off by saying this game is amazing!

Now, about the issue at hand:
**This works:**
![works](https://user-images.githubusercontent.com/9571936/64838450-41bfbd00-d5c1-11e9-883c-587aa30cfe9a.png)

**This doesn't work:**
![not-work](https://user-images.githubusercontent.com/9571936/64838471-59974100-d5c1-11e9-8895-1b38d987be37.png)

Not sure if this is intended behavior.

**Comment by Anuken** [comment]
This is intentional; the whole point of bridges is that they don't contaminate the flow with whatever they're going across.
