### ISSUE TITLE
Corrupt JPEG

### ISSUE THREAD

**Issue by kaianimatez** [Anuken/Mindustry#6560]
**Platform**: windows

**Build**: steam version 126.3

**Issue**: game crashes as soon as i start it up 

**Steps to reproduce**: i believe i changed the pagefile size on windows it gives me an error saying corrupt jpg
![image](https://user-images.githubusercontent.com/74247695/152846506-08e3cb80-e498-4eaf-acfc-73adaa656aa0.png)

**(Crash) logs**: 
[crash-report-02_07_2022_23_36_56.txt](https://github.com/Anuken/Mindustry/files/8017681/crash-report-02_07_2022_23_36_56.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.

**Comment by kaianimatez** [comment]
can you link me to it please

**Comment by Anuken** [comment]
#3723 #3623 #2588, possibly others.

There is no known solution other than (1) un-doing whatever you did to make it crash, (2) using a different computer, or (3) trying the Steam beta in the (unlikely) event it fixes the problem.

**Comment by Ander292** [comment]
Wait, why not reinstall

**Comment by kaianimatez** [comment]
> Wait, why not reinstall

i did reinstall mindustry but it still didnt work so i tried reinstalling steam but that didnt fix it eitehr so i increased the pagefile size again and it somehow seemed to stop the issue.
my guess is that the system was running out of memory because other apps were also crashing on my system
