### ISSUE TITLE
Game crash when trying to view the amount of resources in a sector.

### ISSUE THREAD

**Issue by Makc-Carbon** [Anuken/Mindustry#6567]
**Platform**: *Windows 10*

**Build**: *steam build 135*

**Issue**: *The game crashes when trying to view all the resources in the sector (in this case, it happened at the Ground Zero).*

**Steps to reproduce**: *I don’t know how exactly I got such an error, but the crash itself happens when you try to look at the resources on the sector.*

**Link(s) to mod(s) used**: *no modifications*

**Save file**: *[Ground Zero.zip](https://github.com/Anuken/Mindustry/files/8050416/Ground.Zero.zip)*

**(Crash) logs**: *[crash-report-02_11_2022_18_40_18.txt](https://github.com/Anuken/Mindustry/files/8050351/crash-report-02_11_2022_18_40_18.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in dev branch.

**Comment by Ander292** [comment]
Hm
