### ISSUE TITLE
Unit restriction bypass

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry#6573]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Pre alpha 135

**Issue**: *Explain your issue in detail.*

Units put into reconstructors via logic or manual control can bypass unit restrictions.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Ban a certain unit, like a quad in this case. Use logic or put in the unit yourself, wait 1 min 30 sec and enjoy your illegal unit.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

no mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

<img width="649" alt="Screen Shot 2022-02-14 at 1 56 26 PM" src="https://user-images.githubusercontent.com/88537252/153929122-aba8e01b-1d91-466d-b91d-442f208f160a.png">

<img width="900" alt="Screen Shot 2022-02-14 at 1 56 50 PM" src="https://user-images.githubusercontent.com/88537252/153929111-5cd2db00-1456-40a6-806c-84343e97480d.png">

[bug.msav.zip](https://github.com/Anuken/Mindustry/files/8063272/bug.msav.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

not a crash

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate.
