### ISSUE TITLE
Two Gammas in my single player game

### ISSUE THREAD

**Issue by Arcanilius** [Anuken/Mindustry#6578]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
135
**Issue**: *Explain your issue in detail.*
I have another Gamma in my team, and tried to build without any resourses, its annoying, i want to somehow stop it but i can't, or its a bug, or i am just stupid
(There was an issue like this, but that was a bit different, i can't stop it, he could)
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1)Custom rules
2)Player team:Crux
   Enemy team:Sharded
3)AI builds-on
4) Player team:Sharded
    Enemy team:Crux
5)Infinite resourses-off
6)AI Builds-off

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

I don't know how to import files on mobile on github :/

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

Zero,none,nada

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> AI builds-on

AI building makes gamma builders spawn. 

You have not provided a save.

**Comment by Arcanilius** [comment]
The AI building was turned off later, but it doesn't matter anymore, i found an solution
