### ISSUE TITLE
fps bad why im playing terraia 60fps but if im playing this game 5 - 29 fps??????

### ISSUE THREAD

**Issue by Pum2526** [Anuken/Mindustry#6579]
**Platform**: `Windows 10 x64`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Are you using a 64 bit Java version? Not sure if it makes a difference tho

**Comment by Anuken** [comment]
I get higher FPS on my **7-year-old low-end phone**. This is problem with your device.

**Comment by Pum2526** [comment]
I did im download it not work :/

ในวันที่ พ. 16 ก.พ. 2022 เวลา 21:31 end-me-please ***@***.***>
เขียนว่า:

**Comment by Pum2526** [comment]
My pc is bad and low end pc

ในวันที่ พ. 16 ก.พ. 2022 เวลา 22:40 Anuken ***@***.***>
เขียนว่า:

**Comment by Pum2526** [comment]
oh yes how im know game is  64 bit ?

ในวันที่ พ. 16 ก.พ. 2022 เวลา 21:31 end-me-please ***@***.***>
เขียนว่า:

**Comment by EclipseTheOldOne** [comment]
reinstall your ass java


bottom text
