### ISSUE TITLE
Able to permanently overwrite noise results for numbers

### ISSUE THREAD

**Issue by knzconnor** [Anuken/Mindustry#6580]
**Platform**: `iOS xnull`

**Build**: `pre-alpha build 135`

**Issue**: I am able to permanently overwrite the noise results for a pair of numbers to zero

**Steps to reproduce**: I used a variable named noise for the result of a noise calculation and noticed it was zero. After renaming the variable and deleting the processor that pair still returns zero. Even after a reload.

**Link(s) to mod(s) used**: `none`

**Save file**:
[Overwriting noise .zip](https://github.com/Anuken/Mindustry/files/8083129/Overwriting.noise.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** (since I’m on TestFlight it’s whatever version that gives me)
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by knzconnor** [comment]
![9996B225-4832-4510-8A1E-2B0DC6904FD1](https://user-images.githubusercontent.com/53/154345446-67922d5f-cc2d-4f91-b969-5d689e7eb3c8.jpeg)
![251697C6-421B-49CC-9E09-43A8106E7D91](https://user-images.githubusercontent.com/53/154345455-556d9087-5b42-4e98-bab5-7895b63325c8.png)

**Comment by knzconnor** [comment]
It actually does it across saves even. I made a new save file and the result was still zero. This means this save file may actually not return zero if it’s saved into the game engine storage somewhere. So I’m adding another file that is a minimal reproduce from nothing.

**Comment by knzconnor** [comment]
[save-Ancient Caldera Feb 16 12:04.zip](https://github.com/Anuken/Mindustry/files/8083199/save-Ancient.Caldera.Feb.16.12.04.zip)

**Comment by Anuken** [comment]
That pair *always* returns zero, it's just the output of the noise function at those coordinates. There is no cross-save storage relating to logic.

> After renaming the variable and deleting the processor that pair still returns zero.

I don't understand why you would expect it to **not** be the same value. Simplex noise is a deterministic function - same inputs, same results.

![image](https://user-images.githubusercontent.com/10100000/154352457-8a586f1c-2552-4c2b-bc20-edd3173e2dd2.png)

**Comment by knzconnor** [comment]
Ah I see, sorry. I did test with 122, 83 also and got zero but didn’t realize zero results were common
