### ISSUE TITLE
Frozen forest crash

### ISSUE THREAD

**Issue by Thirdsmash** [Anuken/Mindustry#6589]
**Platform**: `Android 28`

**Build**: `release build 126.2`

Issue: Exactly when I land on the sector, the game crash and I have to grind resources again only for it to crash again.
How to reproduce: Have only ground zero and the frozen forest unlocksd. Then die in the frozen forest on WAve eight. Then launch to dozen forest again

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Crash report: The contents of relevant crash report files. REQUIRED if you are reporting a crash.

> I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
