### ISSUE TITLE
Controls page scrolls all the way up if you reset a keybind or change it

### ISSUE THREAD

**Issue by Ciliane** [Anuken/Mindustry#6592]
**Platform**: Linux and windows (happens on both)

**Build**: 126.2 and 135

**Issue**: In the controls page when you change a keybind or click the reset button for it the page scrolls all the way up. It makes editing multiple keybinds that are not on the top of the page extremely annoying, I would even say it's barely bearable and only the fact that you won't edit keybinds gives gives some "it's not that bad" energy.

**Steps to reproduce**: Launch mindustry, open controls settings, scroll to edit or reset a keybind like Minimap and the page will be scrolled up

**Link(s) to mod(s) used**: None

**Save file**: not in-game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in private branch.
