### ISSUE TITLE
IOS - Open failed: EMFILE (Too many open files) - Plus how to resolve error

### ISSUE THREAD

**Issue by keithaw** [Anuken/Mindustry#6597]
**Platform**: *iOS*

**Build**: *135*

**Issue**: *An error appears when trying to Export Data reading "An error has occured (open failed: EMFILE (Too many open files)) [Details...] [ OK ]"*

**Steps to reproduce**: *From the main screen: Settings / Game Data / Export Data*.  If successful, move the file to another folder. Repeat.  Error message should appear without presenting any menu of where to save to.  Replace file. Save succeeds.  

**Link(s) to mod(s) used**: *None*

**Save file**: *Attached*

Some quick notes:
"Documents" in the file path is likely the app name of a 3rd party iOS file management application.  I have done some house cleaning in that app and moved files around.  At no point in the save process leading up to the crash does mindustry ask where I want to save, it must be assuming "same as last time" and that file is no longer there.  Replacing the file resolves the error, but is not how mindustry should behave at a moved or deleted back-up file

**(Crash) logs**: *Doesn't create a crash log, but there is info under "Details"  Typing out in part:*

> ArcRuntime: 'Error copying source file: mindustry-data-export.zip (local)
To destination: /var/mobile/Containers/Data/Application/395E0969-549B-4094-9311-47905B609E87/Documents/mindustry-data-export.zip (absolute)
Fi.copyFile: 112
Fi.copyTo: 835
IOSLaucher$1.shareFile: 145
SettingsMenuDialog.lambda$new$12: 164
SettingsMenuDialog$$Lambda$39.run: -1
Element.lambda$clicked$2: 893
Element$$Lambda$5.get: -1
Element$4.clicked: 902
...
> ArcRuntime: 'Error stream writing to file: /var/mobile/Containers/Data/Application/395E0969-549B-4094-9311-47905B609E87/Documents/mindustry-data-export.zip (absolute)'
Fi.write: 440
fi.copyFile: 110
Fi.copyTo: 835
IOSLauncher$1.shareFile:145
SettingsMenuDialog.lambda$new$12:164
....
> ArcRuntime: 'Error writing file: /var/mobile/Containers/Data/Application/395E0969-549B-4094-9311-47905B609E87/Documents/mindustry-data-export.zip (absolute)'
Fi.write: 411
Fi.write: 437
Fi.copyFile: 110
Fi.copyTo: 835
IOSLauncher$1.shareFile: 145
...
> FileNotFound: 'var/mobile/Containers/Data/Application/395E0969-549B-4094-9311-47905B609E87/Documents/mindustry-data-export.zip: open failed: EMFILE (Too many open files)'
IoBridge.open: 409
FileOutputStream.<init>: 88
Fi.wright:408
Fi.write:437
Fi.copyFile: 110
Fi.copyTo: 835
IOSLauncher$1.shareFile:145
...
>Errno: 'open failed: EMFILE (Too many open files)'
Posix.open: -2
BlockGuardOs.open: 110
IoBridge.open: 393
FileOutputStream.<init>: 88
Fi.write: 408

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [] **I have searched the closed and open issues to make sure that this problem has not already been reported.** Definitely the same as issue #473, but with more information about cause and workaround.
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/8120885/mindustry-data-export.zip)

**Comment by Anuken** [comment]
(Probably) fixed in private branch - switched to sharing without intermediate files.

> "Documents" in the file path is likely the app name of a 3rd party iOS file management application.

No, it is the [application sandbox documents directory](https://stackoverflow.com/a/6907432).

> At no point in the save process leading up to the crash does mindustry ask where I want to save, it must be assuming "same as last time" and that file is no longer there.

No, Mindustry does not do this. Data is exported to an internal (inaccessible) file, *which is then shown to the user* for choosing an export directory. For whatever reason, iOS does not allow it to do this, so the choice can never even be presented to the user.
