### ISSUE TITLE
Keyboard+mouse not working properly on mobile version.

### ISSUE THREAD

**Issue by gabrielbr1802gcc** [Anuken/Mindustry#6599]
**Platform**: Android

**Build**: *pre alpha build 135.*

**Issue**: the issue is that when using a keyboard plus the keyboard controls activated, it's extremely hard to use a schematic, because I can't drag it to the correct position

**Steps to reproduce**: to replicate is to use a schematic with a mouse (keyboard+mouse control on).

**Link(s) to mod(s) used**: no mods used...

**Save file**: i don't think that needs a save file, since it happens in whatever map, offline or online.

**(Crash) logs**: No crash happens :)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I provide no support for this feature.

**Comment by gabrielbr1802gcc** [comment]
Expected answer lol
