### ISSUE TITLE
All logic erased if processor closed with cursor in open string

### ISSUE THREAD

**Issue by knzconnor** [Anuken/Mindustry#6600]
**Platform**: *iOS*

**Build**: *12.6*

**Issue**: Sometimes all my logic is erased when I close a processor

**Steps to reproduce**:
1) Open proc with a string literal (print for sure, maybe set also)
2) Edit string and delete closing quote"
3) Hit "OK" leaving the cursor at the end of the string still missing a close quote
4) Hit back.
5) Open proc, code gone.

Likely something with the "underscore all spaces for a variable if string not closed" logic, that chokes when the cursor is there?

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

- Save file: 
[save-Molten Lake Feb 23 1:57.zip](https://github.com/Anuken/Mindustry/files/8128132/save-Molten.Lake.Feb.23.1.57.zip) (btw, GitHub ios mobile won’t let be get to files other than photos, but the web will. Huh.)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by knzconnor** [comment]
![F7F5721B-747C-46F3-9BB8-DBE60DDB43AB](https://user-images.githubusercontent.com/53/155417900-280169a6-9927-4269-bd5f-c676fecbb2b7.png)

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

This has already been reported several times.

**Comment by knzconnor** [comment]
Sorry! I did try multiple variations of logic, erased, string, etc


![Uploading 0AAB6481-B380-4BF3-AF9B-73D1D3C79BAF.png…]()

**Comment by Anuken** [comment]
It's an issue that comes up under several different terms, e.g. "wipe" - #5861. (I don't really expect people to find every similar issue when searching)

**Comment by knzconnor** [comment]
Given "Use v130" as the solution isn't out on iOS... any chance you'd be willing to drop another alpha of v7 on TestFlight? 🥺😂

**Comment by mse-k** [comment]
build 12.6? this man playing mindustry back in caveman times
