### ISSUE TITLE
Quads not shooting when commanded with logic in v7

### ISSUE THREAD

**Issue by JoeyKimKoreaSub** [Anuken/Mindustry#6601]
**Platform:** Android

**Build:** pre-alpha build 135

**Issue:** It seems like quads won't shoot (drop their bombs) when commanded with logic. Have tested the same code for horizon to make sure the code isn't wrong.

**Steps to reproduce:** I came across this issue by finding out the code I have been using for v6 suddenly stopped working when I updated to v7. It seems like the target option in ucontrol does nothing.

This is a code that shows the issue. The quads won't shoot. Same code works well with horizon just to make sure that the code isn't wrong.

sensor on switch1 @enabled
jump 0 notEqual on true
ubind @quad
ulocate building core true @copper ecorex1 ecorey found ecore
op sub ecorex2 ecorex1 5
op add ecorex3 ecorex1 5
ucontrol move ecorex2 ecorey 0 0 0
ucontrol target ecorex1 ecorey 1 0 0
wait 1
ucontrol move ecorex3 ecorey 0 0 0
ucontrol target ecorex1 ecorey 1 0 0
wait 1

**Link(s) to mod(s) used:** No mods have been used.

**Save file:** [Mindustry quad bug report.zip](https://github.com/Anuken/Mindustry/files/8145699/Mindustry.quad.bug.report.zip)

**(Crash) logs:** This report is not related to crashing.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and ope
n issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/155825385-c14c1a88-c3cb-4eb6-8fa3-4563055782dc.png)

Works for me - cannot reproduce.

**Comment by JoeyKimKoreaSub** [comment]
Maybe it only works on pc?

**Comment by mse-k** [comment]
if you have more than 1 quad they will probably be too far away to think they should fire, bomber units only fire when their bombs would be able to damage where the target is set afik
