### ISSUE TITLE
Crash when automatic nightlight is changing

### ISSUE THREAD

**Issue by q2wyx** [Anuken/Mindustry#6605]
**Platform**: *Android 9*

**Build**: *126.2*

**Issue**: *Game crashes when automatic nightlight is changing on or off.*

**Steps to reproduce**: *Turn the option on, start game. When the screen color is about to change the game crashes.*

**Link(s) to mod(s) used**:  *Vanilla*

**Save file**: *(https://github.com/Anuken/Mindustry/files/8148520/log.txt)*

**(Crash) logs**: *(https://github.com/Anuken/Mindustry/files/8148521/save1.zip)*

---

- [x] **I have updated to the latest release using Google play store (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
Log is empty.

**Comment by q2wyx** [comment]
Sorry for that. When it happens the app closes and I have to restart and
load the game. It is not anymore in the ram. Maybe it it not a crash?

BlueWolf ***@***.***> schrieb am So., 27. Feb. 2022, 13:44:

**Comment by end-me-please** [comment]
You have, in fact, not updated to the latest version. The latest version is 135, many of the old bugs from 126.2 are fixed there.

**Comment by q2wyx** [comment]
Ok, I play on Android and there is no update, then i wait, sorry if I
concern you.

end-me-please ***@***.***> schrieb am So., 27. Feb. 2022,
14:30:

**Comment by end-me-please** [comment]
You can get the latest version on the itch.io page, you can download the .APK file there

**Comment by SwitchLikesMlog** [comment]
Download V7 from [here](https://anuke.itch.io/mindustry).
