### ISSUE TITLE
no annotations jar on jitpack

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#6606]
**Platform**: jitpack
**Build**: v135

**Issue**:
annotations jar isnt on jitpack, I dont know why but I cant make unit types because of it

**Steps to reproduce**:
```
$ curl https://jitpack.io/com/github/Anuken/Mindustry/annotations/v135/
$ <no output>
```

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not *supposed* to be on jitpack, and it doesn't work outside of the Mindustry codebase. None of the codegen systems can be used in mods.
