### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by Poiltris** [Anuken/Mindustry#6608]
hi, i was playing mindustry and while i was playing i realized that
in Spanish the phase wall is called large phase wall, thank you for your attention
![Screenshot_2022-02-28-16-11-11](https://user-images.githubusercontent.com/100622458/156047537-50fa81b2-e739-4467-aa6a-1ab49383d470.jpg)
 
![Screenshot_2022-02-28-16-11-11](https://user-images.githubusercontent.com/100622458/156047613-83e76ed2-373f-4dc1-a2e1-b533f87b573f.jpg)

**Comment by end-me-please** [comment]
This looks like a translation problem. 

Here is how you can help to fix it: https://github.com/Anuken/Mindustry/blob/master/TRANSLATING.md

**Comment by Anuken** [comment]
This issue tracker is for game bugs, not translation problems - I do not handle localization.
