### ISSUE TITLE
Wrong count in title of block's constant in default bundle

### ISSUE THREAD

**Issue by Remint32** [Anuken/Mindustry#661]
https://github.com/Anuken/Mindustry/blob/44842d322119412f588ec214097c8a8dd60b3c89/core/assets/bundles/bundle.properties#L762
![изображение](https://user-images.githubusercontent.com/13190430/64907198-f5c36400-d6f7-11e9-96ee-d4d62975aefc.png)

**Comment by Remint32** [comment]
just tiny issue

**Comment by Anuken** [comment]
That's not a bug. When making metal floors, I ended up removing some before release, leaving gaps in the numbers. To prevent confusion, I named them sequentially instead of by their internal names.

**Comment by Remint32** [comment]
> 
> 
> That's not a bug. When making metal floors, I ended up removing some before release, leaving gaps in the numbers. To prevent confusion, I named them sequentially instead of by their internal names.

Should I translate the same way?

**Comment by Anuken** [comment]
Yes. Nobody can see the internal names in-game anyway.
