### ISSUE TITLE
Ores in images imported as maps is buggy

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6620]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Win10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
135
**Issue**: *Explain your issue in detail.*
Importing images as maps is a little buggy with ores.

https://user-images.githubusercontent.com/94794129/156858196-38cd7a4b-c429-4e17-96f7-4e9ebfb59911.mp4

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Import a map that has ores.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
Not exactly a save file but map file.
[Bug Report.zip](https://github.com/Anuken/Mindustry/files/8189372/Bug.Report.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by AtobaAzul** [comment]
Oh, and here's the image too
![map_61_v2](https://user-images.githubusercontent.com/94794129/156858509-44f354a9-9593-4fe7-99c1-9a8292d933fb.png)

**Comment by end-me-please** [comment]
doesnt this only exist for legacy reasons?

**Comment by Anuken** [comment]
This is not a bug. Images can only have one color per pixel, and as such there is nothing to put under ores. Don't use ores in map imags.
