### ISSUE TITLE
Help I cannot download or view any of my mods

### ISSUE THREAD

**Issue by gamereapere** [Anuken/Mindustry#6621]
I and my friend were trying to do mindustry mods but sadly I wasn't able to view or browse any mods with the error "your device doesn't support this feature" I haven't updated it at all and it's still running like this please help me out

**Comment by oinkymoo** [comment]
you need to use the template if you want anuke to deal with this issue. if you don't know what i'm talking about, don't use the github mobile app. also on that topic, this may be intentional if you are on mobile

**Comment by gamereapere** [comment]
Im not on the mobile app but I still do not know what you are talking about
