### ISSUE TITLE
Help, my friend is not able to view or download mods

### ISSUE THREAD

**Issue by gamereapere** [Anuken/Mindustry#6622]
**Platform**: Windows 11

**Build**: * Steam build 135

**Issue**: "When I open the mod browser, I get an error message saying "your device does not support this feature" with the only answer saying "ok" therefore I can't use any mods at all nor let me disable any"

**Steps to reproduce**: "I only downloaded mods from the workshop, but now all of a sudden it won't work"

**Comment by gamereapere** [comment]
the other one posted wasn't completed so im here trying to complete it

**Comment by Anuken** [comment]
This is not enough information to debug the issue; you have not attached any logs or screenshots. If you are seeing an error, provide the error message in the popup dialog. "I am not able to" and/or "It doesn't work" does not describe the problem - what exactly are you trying to do (which mods dialog? there are several), what do you expect to happen, and what actually happens?

**Comment by gamereapere** [comment]
Ok im going to edit it to say what is happening specifically

**Comment by gamereapere** [comment]
Also note: tho I realize I am referring to myself my friend is having this problem, maybe I should put that in the title

**Comment by Anuken** [comment]
Unless you have access to your friend's computer (or they provide the necessary information here themselves), I won't be able to help you with this problem.
