### ISSUE TITLE
Plastanium conveyors look weird in payload (uses the default icon) and dont show items inside

### ISSUE THREAD

**Issue by mse-k** [Anuken/Mindustry#6625]
**Platform**: Windows 10

**Build**: v135

**Issue**: When inside payload, plastanium conveyors use the default icon (the one seen in the core database), and also do not show items inside. this was probably caused by #6295, I would suggest marking the conveyors as having no links on any side when picked up instead, as it allows items to be seen and doesnt have the ugly open ends. 

**Steps to reproduce**:
1. Place a plastanium conveyor (with or without items), a payload conveyor, and then spawn a mega and control it
2. Pick up the plastanium conveyor with the mega and put it on the payload conveyor
3. Plastanium conveyor now has open ends and the crater is invisible

**Link(s) to mod(s) used**: none

[**Save file**](https://github.com/Anuken/Mindustry/files/8193301/bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: who is joe

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is consistent with how standard conveyors draw as payloads. Not a bug.
