### ISSUE TITLE
m1 mac crashing

### ISSUE THREAD

**Issue by bwennn** [Anuken/Mindustry#6629]
**Platform**: *mac*

**Build**: *idk what this is.*

**Issue**: *Constant crashing, my discord is bwennn#3423, ill send u the crash report thru there*

**Steps to reproduce**: *get the game with an m1 computer.*

**Link(s) to mod(s) used**: *no mods*

**Save file**: *i cant open the game*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheMrAlbert** [comment]
This bug report might be a duplicate of #6456.

**Comment by end-me-please** [comment]
so it crashes on startup?
did you install through steam, itch.io or github?

did you download the "unstable alpha"? if you didnt, maybe try the alpha from itch.io.

**Comment by bwennn** [comment]
thru steam

**Comment by bwennn** [comment]
@TheMrAlbert the reason why i made this is bc my CPU is way different than the older computers.  i have m1 and m1 has a known record of not being able to run games

**Comment by Anuken** [comment]
Mindustry does not have m1 support.
