### ISSUE TITLE
How to even start

### ISSUE THREAD

**Issue by firdacz** [Anuken/Mindustry#663]
So I downloaded it, started it and I feel like an idiot:
Tutorial sais: You have entered the **Mindustry Tutorial** _Tap to continue_
Tap? I have a mouse, ok, click, probably. I can click anywhere in the box, I can click on that red **Mindustry Tutorial** that appears to be important, like that clicking on it could do something else, but no, does not matter:
Begin by *mining copper*. Tap copper ore vein near your core to do this. _Tap to continue_

Ok, tap = click, there is different color this time on *mining copper*, orange? Not sure, I cannot see colors as most folks do, but I see it is different than the rest of the text. Ctrl+Click? Shift+Click? Alt+Click? Middle Click? No, nothing, why the hell is it different color then?!

Ok, tap = 0/18 copper. Ok, click... oh it shoots. Click, left, right, oh yes, there is copper ("Měď" - nice, somebody translated it to my language), but what am I supposed to do? I click, left, right, middle, cltr, shift, alt, all the combinations I can think of and... **the ship just shoots there or some box flickers!! What the hell am I supposed to do?!**

I am not so stupid, I will figure this out. I did figure out UFO1: Enemy Unknown on my first 386 before I even knew how to speak english! I can handle that!! Ok, bottom-right, I can switch to drill and select mechanical drill (I see *Mechanický vrt*), ok, that is building, that is why I am here, I wanted building, maybe tower-defense, acceptable, I want to build things. I click and place three of them... but... nothing!! WTF? Am I in some suspended time the tutorial will keep me until I do what the programmer of this want me to do? And what exactly is that? I cannot get any further!

I can shoot, but those drills are just there as an outline, which reminds me of Total Anihilation - somebody has to pour the energy/material to build it! Is that time stop before I do something? What is it to continue?

ESC: Oh, menu, yes, that was expected, ok, settings... "Ovládání" (Controls) Pause (pauza) = space... ESC, space, ...no, we are not paused, but we actually somehow are! WTF?!

Ok, I will build that conveyor belt ("Dopravník") that will transport the goods from the drill or mines or whatever it is... but NO, **BIG FAT NO! DOES NOT WORK!**

Left-top: "Vlna 1\nČekám" (Wave 1 ... Waiting) ... yes, **I AM WAITING FOR SOMETHING TO HAPPEN, CLICKING LIKE MAD, BUT NOTHING**. Oh, BTW, why is it not full-screen but windowed?

I am a programmer myself and I wrote this to give you what I, as a programmer, would like to hear. I was honest and hope you get something from it. I would also like to play the game, but am trully unable to do so, it just does not work.

**Comment by Kieaer** [comment]
(Tutorial has smail bugs and not enough)

**Comment by firdacz** [comment]
OK, how to even play it? Middle mouse button does not work for scrolling (hold middle and move), arrows does not work either (standard camera move in most games). I can escape and start campaign but how the hell to even play the game? Right button drag appears to do delete. But again: how the hell even play it?

**Comment by Spicy0903** [comment]
If your pressing wasd and nothing working most likely your problem

**Comment by firdacz** [comment]
Ok, WASD works for moving the ship. Should have figured that out, quite standard almost as arrows are.

**Comment by amrsoll** [comment]
How could you mistake the controls after looking in the controls menu?
Also, the constructions of buildings will pause while waiting for material in the core. That might need explaining in the tutorial I guess.

**Comment by Arkanic** [comment]
i don't even remember how i managed to start playing

**Comment by Spicy0903** [comment]
Depends on the games, I would say wasd is more standard
