### ISSUE TITLE
Bug(Button click)

### ISSUE THREAD

**Issue by LordTimofeus** [Anuken/Mindustry#6633]
**Platform**: *Windows*

**Build**: *126.6(If i remember wright).*

**Issue**: *Buttons Don't working like one click didn't work and need spam or long press(i hear from someone in by playerinput).*

**Steps to reproduce**: *Just download game in 8th september(from steam) and played.*

**Link(s) to mod(s) used**: *No mods.*

**Save file**: *Didn't have for this time save.*

**(Crash) logs**: *No crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LordTimofeus** [comment]
I have vid for show, but can upload it on only server(Paragon!Sans#7781).

**Comment by Anuken** [comment]
This is an issue with your specific system; I have never seen or heard of anything similar occurring on anyone else's computer.
