### ISSUE TITLE
Scuffed Music Files

### ISSUE THREAD

**Issue by ParticularGuy** [Anuken/Mindustry#6634]
**Platform**: Linux, Mac

**Build**: 126.2

**Issue**: I wouldn't exactly describe this as a bug, but it seems that the two files in core/assets/music "game 7" and "game 9" share the same music (I think). Maybe it's my ears that are scuffed, not the folder. It's worth the time, I assure you

**Steps to reproduce**: I just downloaded the music and listened to it

**Save file**: Has no affect in game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
no:label

**Comment by ParticularGuy** [comment]
This probably belongs in pull requests

**Comment by Anuken** [comment]
They're completely different files with completely different melodies.

[game7](https://github.com/Anuken/Mindustry/blob/master/core/assets/music/game7.ogg)
[game9](https://github.com/Anuken/Mindustry/blob/master/core/assets/music/game9.ogg)
