### ISSUE TITLE
Liquid capacity not reached with liquid routers

### ISSUE THREAD

**Issue by Arcluigi** [Anuken/Mindustry#6637]
**Platform**: *Windows*

**Build**: *Pre-Alpha Build 135*

**Issue**: *The liquid capacity is not fully filled in buildings that are fueled via a liquid router (appends on few buildings like fluid tank /impact reactor/tsunami/...)*

**Steps to reproduce**: *Place a building that accept liquid and fuel it via a liquid router, when checking with aprocessor and a message bloc it shows that the tower has not exactly reached his full capacity (dont work with buildings that have 10 unit max capacity)*

**Link(s) to mod(s) used**: *none*

**Save file**: *[Issue_map.zip](https://github.com/Anuken/Mindustry/files/8244797/Issue_map.zip)*
**Screenshots**:
![Capture d’écran 2022-03-14 133949](https://user-images.githubusercontent.com/44820103/158174122-3ff11afa-22df-4f33-b15f-3133ff0f6aa2.png)
![Capture d’écran 2022-03-14 134020](https://user-images.githubusercontent.com/44820103/158174160-9037a258-001d-4401-b751-b089ffbe8e67.png)
![Capture d’écran 2022-03-14 134044](https://user-images.githubusercontent.com/44820103/158174182-35b055b5-dce2-4b03-8836-d332a81fb686.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Blocks aren't supposed to reach exactly 100% capacity, that's not how the system works. Routers distribute based on difference in liquid, conduits do not.
