### ISSUE TITLE
Zoom dont work if unloader item menu selection is opened

### ISSUE THREAD

**Issue by MekBoss** [Anuken/Mindustry#6642]
**Platform**: Windows 10

**Build**: *pre alpha 135

**Issue**: Zoom dont work

**Steps to reproduce**: 
Build unloader.
Scroll a wheel to make sure zooming IS works.
Click on unloader to open its item filtering menu. 
Move cursor away from unloader and scroll a wheel to make sure zooming IS works.
Move mouse cursor inside unloader 'item type selection' window WITHOUT clicking on any item.
Scroll a wheel to make sure zooming ISNT works.
Move cursor away from unloader 'item type selection' window.
Scroll a wheel to make sure zooming ISNT works.
Select any item in unloader window, or click away from it to close if.
Scroll a wheel to make sure zooming IS works.

**Link(s) to mod(s) used**: none

**Save file**: unimportant? Happens everywhere, both in single- and multiplayer and 'fresh' copy. Didnt tested current master.

**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug. You're focused on the scrollpane on the unloader.

**Comment by LeoSko** [comment]
But zooming usually is expected to focus the pointer's current location. :(
