### ISSUE TITLE
polygonal borders crash when no cores are on the map

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#6645]
**Platform**: Android 10, also tested on Linux x64

**Build**: 135

**Issue**: which team's space should fill a voronoi diagram with no nodes on it? the answer is an arrayindexoutofbounds exception, because you need at least one core to tell

**Steps to reproduce**: 
1. go into editor
2. turn on polygonal no build radius
3. test ingame
4. (?) select a block

**(Crash) logs**:
```
Mindustry has crashed. How unfortunate.
Version: pre-alpha build 135
OS: Linux xnull (aarch64)
Java Version: 0
Mods: cliff:1.1.0, dev-mode:2.3.2, ldb:1.3.3, override-lib:1.0.1, pictologic:1.5.7, rtfm:2.15.0, test-utils:0.11, ui-lib:2.16.6, unit-factory:2.5.0

> ArrayIndexOutOfBounds: 'length=0; index=0'
Voronoi.generateVoronoi: 45
Voronoi.generate: 33
OverlayRenderer.updateCoreEdges: 61
OverlayRenderer.drawTop: 161
Renderer$$ExternalSyntheticLambda21.run: 2
SortedSpriteBatch.flushRequests: 117
SortedSpriteBatch.flush: 97
Draw.flush: 362
Renderer.draw: 323
Renderer.update: 183
ApplicationCore.update: 37
ClientLauncher.update: 177
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BasedUser** [comment]
this is like a 2 line fix i swear to god

**Comment by Anuken** [comment]
Someone reported this in PM a few weeks ago, it's fixed in the private branch.
