### ISSUE TITLE
steam version has crashed on Mac m1

### ISSUE THREAD

**Issue by elMepox** [Anuken/Mindustry#6647]
**Platform**: `Mac OS X x64`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---
[mindustry_crash_report.txt](https://github.com/Anuken/Mindustry/files/8309182/mindustry_crash_report.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mindustry does not have support for m1 Mac devices.

**Comment by CooperBills** [comment]
Leaving this note for people who find this issue: I see the same crash when using the steam version of Mindustry. However, the version from Mindustry's website (itch.io) works fine on my M1 Mac.

**Comment by Anuken** [comment]
You might be download the pre-alpha version, which might happen to support m1 devices better.
