### ISSUE TITLE
Titanium conveyors disappeared

### ISSUE THREAD

**Issue by MoonSolo** [Anuken/Mindustry#6650]
**Platform**: `Windows 10 x64`

**Build**: `pre-alpha build 135`

**Issue**: The block known as titanium conveyor does not exist anymore ? I can't research it and that's a bit annoying. Idk if this is coming from a mod ?

**Steps to reproduce**: I went to the tech tree. thought that I could have the conveyor later, but still not showing. installed cheats to complete the tree to be sure, but still nothing.

**Link(s) to mod(s) used**: `[ArZar/42:[beta]6.0, Tom Petrou/[#25f12f]vanilla-extended[]:1.82, [green]Snake[white] & [red]Super[green]Jaba[red]2000/adc:12.0, Tayros/theangelurd/additional-content:0.4.1, AeronGreva/aeromindustry:1, Goober/amogus:ery sus, martycagas/armored-basic-conveyor:1.0, genNAowl/extra-walls:1.0, 呵呵哒/free-campaign:0.2, NewJumper/futurdustry:0.2.3, qweryt/infinite-units:0.1, SMIPE444/infinity-cheat:2.1.444, pixecoz/maps-pack:1, Developer:
    Fresh791
    
    
Contributers:
    Many, many people! Check Discord for more information!/me:1.09, Staticalliam7/mindustry-plus-plus:0.1 Alpha, SakuraLilly/powered-by-nature:2.0, Hellfire_NL (Content), 
SakuraLilly (Art, content),
Deserate (Content), 
Verty (Testing)/real-life-mindustry-mod:2.0, BlueTechno/test-3:2.4, sk7725/time-control:0.2, lev43/turretsmod:3, Solokil/underground-adventure-v6:1.1]`

**Save file**: T:\mindustry\dataMoonSolo.zip

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Idk if this is coming from a mod ?

Yes. This ""bug"" has been reported before, and it's caused by a mod, most likely `real-life-mindustry-mod`.

**Comment by MoonSolo** [comment]
Thanks so much for replying and fixing !
Have a good day and keep it up for the game, i was here since a long time,
the old times when mindustry didn't have the classic version because it was
the classic version. I really like how the game evolves. You're a good guy,
Seeya maybe !
