### ISSUE TITLE
Mindustry crashes on macOS Monterey 

### ISSUE THREAD

**Issue by Solvedegiggi** [Anuken/Mindustry#6654]
**Platform**: `Mac OS X x64`

**Build**: `release build 126.2`

**Issue**: *Crash on start*

**Steps to reproduce**: *I opened the game and it crashes.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *[crash log.txt](https://github.com/Anuken/Mindustry/files/8324794/crash.log.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are not using the latest version - If on Steam, use the v7 beta/alpha branch (Game properties -> betas -> v7-testing dropdown box).

**Comment by Solvedegiggi** [comment]
oh! it works. thank you very much
