### ISSUE TITLE
Invalid Save

### ISSUE THREAD

**Issue by Raif1** [Anuken/Mindustry#6659]
**Platform**: *Android*

**Build**Version 6-official-126.2 (29841) **

**Issue**: *Produces an invalid save when i try export game data. And names it (invalid) and have 0b 

**Steps to reproduce**: Settings -> Game Data -> Export Game Data.*
The exported save file 

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**(i have the play store version.) Which is the latest one.)
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hexrotor** [comment]
> * [x]  **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**(i have the play store version.) Which is the latest one.)

You didn't, the latest version is v135. Update and check if it works fine

**Comment by Anuken** [comment]
You likely have not provided a save file name in the file browser.

**Comment by Raif1** [comment]
> > * [x]  **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**(i have the play store version.) Which is the latest one.)
> 
> You didn't, the latest version is v135. Update and check if it works fine

Aa ur talking about the prereleases

**Comment by Hexrotor** [comment]
> how can get the apk one?

You can download the unstable version from [itch](https://anuke.itch.io/mindustry)

**Comment by Raif1** [comment]
> > how can get the apk one?
> 
> You can download the unstable version from [itch](https://anuke.itch.io/mindustry)

Still cant export game data

**Comment by Anuken** [comment]
I can't reproduce that problem. Exporting works without issues on my phone.
