### ISSUE TITLE
router chain router chain router chain

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#666]
![retuor](https://user-images.githubusercontent.com/21104932/64927370-c6554a00-d812-11e9-9822-555a658437c4.png)
passback time

**Comment by Arkanic** [comment]
oh yes

**Comment by laohuaji233** [comment]
faster than conveyor？that's impossible.

**Comment by Anuken** [comment]
ok

**Comment by ZkyLB** [comment]
egg
