### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [Anuken/Mindustry#6661]
In the double screen rotation test to detect data loss, an application failure was identified: the object in the center of the screen changes position (small rotation).

A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values. This issue is related to the activity's lifecycle (1). When a screen rotation occurs, the activity is destroyed and resumed. Data loss will happen if the developer does not save the variables before the destruction and restore them after creation. To avoid this, the developers have to implement both the logic necessary to save the activity state in the onSaveInstanceState() callback method and the logic to resume its state in the onRestoreInstanceState() callback method.
Another way to avoid data loss problems is to use the view model, designed to store and manage UI-related data in a lifecycle-conscious way (2).

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159798617-ca887761-2027-4c93-9d47-8f28a508ee25.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159798612-c391bb84-72ca-4622-959e-a85ffc5b0072.png" width=20% height=20%>
</figure>

</div> 

Device:

- Device: Moto G30 with OS: Android 11
- Device language: English 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

1. https://developer.android.com/guide/components/activities/activity-lifecycle
2. https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by BlueWolf3682** [comment]
...whats the difference
also consider updating from 5.0 release build 104.6 to either:
  6.0 release build 126.2
  7.0 alpha build 135
and then confirm if the issue (whatever it is) still persists

**Comment by Anuken** [comment]
Account exhibits extremely bot-like behavior:

![image](https://user-images.githubusercontent.com/10100000/159805565-29e2772d-a6e6-45ad-9b4f-b1323ca19faa.png)

...but also appears to be (at least partially) operated by a human, based on comments. This raises some questions:

- What is the purpose of opening all these issues?
- How did this individual get a hold of a massively outdated version of the game?
- Why was the issue template ignored?
- How in the world is a clearly-animated ship in the middle of the screen moving several pixels considered "data loss"?

**Comment by BlueWolf3682** [comment]
oh no

**Comment by BlueWolf3682** [comment]
https://github.com/davirec/artigos
I have found the source

**Comment by mse-k** [comment]
![image](https://user-images.githubusercontent.com/37938606/159817362-66d91058-3cfb-450c-a215-bc33ec41af4e.png)
yeah seems like its a bot for some sort of experiment, honestly im not sure how to feel about bots auto creating issue on repos because of "bugs"  it found, however its kinda cool, and i honestly wouldnt mind it if it was more advanced than take screenshot, rotate screen, take another screenshot, compare, but actually searched for like memory leaks or something

**Comment by buthed010203** [comment]
I assume it rotates into landscape and back into portrait and compares the frames before and compares the frames before and after the rotations and assumes data loss if they're not exactly the same?

**Comment by davirec** [comment]
Hi guys, I'm not a bot.
I'm doing scientific research in software engineering involving robotics and automated testing tools. We use DLD (Data Loss Detector) to generate computerized tests to find data loss on Android devices. The main idea of the DLD is to interact with the smartphone, capture the application state, perform the double rotation, capture the application state again, and then compare these captures. If this capture has a difference, a data loss has occurred. DLD uses double rotation to force Android to destroy activity and then resume. It is executed twice to reach a state that should be precisely the same as the screen before if no data loss occurred.

This first part is performed automatically by the tool. Then I analyze the generated data and classify it as True bug and False alarm. The apps that have True bugs I install on the smartphone and reproduce the failure to report to the developers.


1- Data Loss Detector: Automatically Revealing Data Loss Bugs in Android Apps" https://dl.acm.org/doi/10.1145/3395363.3397379

2- https://github.com/datalossdetector/DLD

**Comment by BlueWolf3682** [comment]
Mindustry is a more complex game than you expect. I recommend playing it fully before making random issue reports on it.
