### ISSUE TITLE
Lagging mindustry to get all steam achievements

### ISSUE THREAD

**Issue by Peteydog** [Anuken/Mindustry#6665]
**Platform**: *Mac Steam*

**Build**: *135*

**Issue**: *In the campaign (i haven't tested this elsewhere) when I slowed my computer down by overloading it with 9 extra instances of mindustry, the game obviously froze. When it froze, I unlocked all of the remaining achievements
(this is my second campaign. i reset after doing global domination but i kept the tech tree)*

**Steps to reproduce**: 
*Open a server on a steam version of the game, then go to overgrowth
Launch 9 more (or however many instances it takes to freeze the steam instance) instances of mindustry from the itch.io versions
Connect the itch.io instances to the steam instance
Wait for the game to freeze
All of the achievements are unlocked*

**Link(s) to mod(s) used**: *No mods used*
[Buggy? save.zip](https://github.com/Anuken/Mindustry/files/8349208/Buggy.save.zip)

**(Crash) logs**: *Surprisingly not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There's no code in Mindustry that even loops through all the achievements, so I don't see how this is possible on Mindustry's end. Either it's a specific bug related to the Steam achievement API relating to Java, or it's a bug in the achievement wrapper, or you're doing something else that's causing it.
