### ISSUE TITLE
Sounds static problem

### ISSUE THREAD

**Issue by Valoneu** [Anuken/Mindustry#6667]
Windows 10

135 and 126.2, i would suspect other versions too but didnt try more

Static noise in game even when muted and its only when playing mindustry and my headphones are completely fine. Its mainly in main menu.

Reproduce: launch mindustry 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by EclipseTheOldOne** [comment]
i don't this this is detailed enough, kys

**Comment by Valoneu** [comment]
dafuq

**Comment by Anuken** [comment]
Cannot reproduce this issue - no static is heard on Windows.

@EclipseTheOldOne Any further comments of that sort will get you blocked from this repository.
