### ISSUE TITLE
Incremental Compilation Solution (Finally)

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#6669]
After many months of being bothered by having to wait 40s to change a java file, I have finally located the reasoning behind the slowness. As it turns out, the annotation processors don't preserve the order of imports or `implements`. If you sort them alphabetically, the order stays consistent and the annotation processor doesn't end up changing the file which results in gradle being able to compile incrementally.

I'm not PRing my solution as it is absolutely disgusting but this should result in significant improvements to compilation speed when editing a java file (wont on CI as you aren't using a gradle cache but there is an action for that), it's as fast as it is when changing only kotlin files.

On this windows pc it normally takes about 40s to compile, with the changes I mentioned it's down to ~5s: https://mee6.is-terrible.com/5rOh2_MMN.webm The code is here if you want it (though I'm not sure why you would as I wrote it really quick and dirty... its horrible) https://pastie.io/zrgqoi.java

I'm not sure if this solution is truly viable though as namespace collisions could happen and non wildcards might be below the other ones but hopefully it works fine? It seems to...

**Comment by Anuken** [comment]
Are those the only changes? Adding your changes to BaseProcessor doesn't seem to make a difference; I see the logged code, but changing even a single line in ClientLauncher forces a full 30-second recompilation.

**Comment by buthed010203** [comment]
I believe that is probably because you have build caching off, try again with `--build-cache`

**Comment by Anuken** [comment]
Did some more experimenting, and it looks like the reason is that your changes don't appear to cover all the cases. Diffing a class between compilations (*without your modifications*), the following things were out of order:
- fields
- methods
- implements
- blocks inside methods
- imports

Maybe your compiler/machine setup happens to put some of these in the same order, I don't know.

After sorting all of these (*I can show a diff, but it's spread out across two files...*), IC works, with about 8 seconds for a recompile - not quite sure why it's not 5, but still much better than before. Thanks.

**Comment by buthed010203** [comment]
Yeah I just noticed that apparently even my implements sorting broke even though it was working earlier... Whats really strange is that I still get compiles in just a handful of seconds

**Comment by Anuken** [comment]
BaseProcessor basic sorting (self-explanatory):

```java
    public static void write(TypeSpec.Builder builder, Seq<String> imports) throws Exception{
        builder.superinterfaces.sort(Structs.comparing(t -> t.toString()));
        builder.methodSpecs.sort(Structs.comparing(m -> m.toString()));
        builder.fieldSpecs.sort(Structs.comparing(f -> f.name));

        JavaFile file = JavaFile.builder(packageName, builder.build()).skipJavaLangImports(true).build();

        if(imports != null){
            imports = imports.map(m -> Seq.with(m.split("\n")).sort().toString("\n"));
            imports.sort();
            String rawSource = file.toString();
            Seq<String> result = new Seq<>();
            for(String s : rawSource.split("\n", -1)){
                result.add(s);
                if(s.startsWith("package ")){
                    result.add("");
                    for (String i : imports){
                        result.add(i);
                    }
                }
            }

            String out = result.toString("\n");
            JavaFileObject object = filer.createSourceFile(file.packageName + "." + file.typeSpec.name, file.typeSpec.originatingElements.toArray(new Element[0]));
            OutputStream stream = object.openOutputStream();
            stream.write(out.getBytes());
            stream.close();
        }else{
            file.writeTo(filer);
        }
    }
```

EntityProcess.java:

`allFieldSpecs.sortComparing(s -> s.name);`

![image](https://user-images.githubusercontent.com/10100000/160292255-1eaa10e9-ed62-4246-8f09-e06720563c52.png)

and replace line 412 with:

`                    entry.value.sort(Structs.comps(Structs.comparingFloat(m -> m.has(MethodPriority.class) ? m.annotation(MethodPriority.class).value() : 0), Structs.comparing(s -> s.up().getSimpleName().toString())));
`

Note: I tried adding --build-cache, but it doesn't seem to affect anything.

**Comment by buthed010203** [comment]
I figured out why it still takes so long, `ContentRegions` and `NullUnit` still aren't sorted

**Comment by buthed010203** [comment]
In order to use build cache, you have to let it build once with caching enabled so that it actually caches and then change something and build again with caching enabled so it can load from the cache. When I have cache off, I end up with a lot more time spent building than I do with it on (perhaps its because I also have a lot of kotlin files though which the base game doesn't?)

Caching Disabled (first compile where kotlin compile isnt incremental, second compile where it is, kapt is incremental by default):
![](https://xenon.is-ne.at/5rOzrtkBq.png)
![](https://yagpdb.is-ne.at/5rOAaxf6m.png)

Caching Enabled (first with cache that is a little outdated, second with cache that is correct everywhere except a missing . in a comment):
![](https://extremely.questionable.link/5rOBaUtoO.png)
![](https://i-dont.go-outsi.de/5rOBwJXcD.png)

**Comment by buthed010203** [comment]
Now the problem is jabel I think

![](https://vexera.is-ne.at/5rOIoWlnQ.png)
![](https://extremely.questionable.link/5rOIBrJnM.png) It doesn't seem to care about order for whatever reason...

**Comment by Anuken** [comment]
> In order to use build cache, you have to let it build once with caching enabled so that it actually caches and then change something and build again with caching enabled so it can load from the cache.

I did try that - several times in a row. What's the argument to show the list of changed classes? ~~I don't want to bother reading the docs right now~~

**Comment by buthed010203** [comment]
--info

**Comment by buthed010203** [comment]
> I did try that - several times in a row. What's the argument to show the list of changed classes? ~I don't want to bother reading the docs right now~

Perhaps I only see a difference as all the kotlin stuff is skipped when a java file is changed instead of it being fully recompiled

**Comment by buthed010203** [comment]
As far as I know, its recommended to split the annotations and processors into their own modules (which is what popular tools like dagger do). This allows the processors to be added to the annotationprocessor classpath without having to add them to the compile classpath which gradle says specifically not to do..

**Comment by buthed010203** [comment]
"[When a source file is recompiled, Gradle will recompile all files generated from it. When a source file is deleted, the files generated from it are deleted.](https://docs.gradle.org/7.4/userguide/java_plugin.html#sec:incremental_annotation_processing)" You know, marking the annotation processors as incremental isolating ones would probably help

**Comment by Anuken** [comment]
> This allows the processors to be added to the annotationprocessor classpath without having to add them to the compile classpath

Why is that discouraged? Will "fixing" it really speed up compile times?

> Perhaps it could also be worth it to move to the [Kotlin Symbol Processing](https://kotlinlang.org/docs/ksp-incremental.html) api instead of annotation processors

But as far as I can tell, that requires processing and outputting Kotlin, and I don't want to move to Kotlin, for reasons I've explained in the Discord at some point (not sure if you've read them). I've been dealing with 35sec compile durations this entire time, 8 seconds is fine by comparison.

**Comment by buthed010203** [comment]
> Why is that discouraged? Will "fixing" it really speed up compile times?




> But as far as I can tell, that requires processing and outputting Kotlin, and I don't want to move to Kotlin, for reasons I've explained in the Discord at some point (not sure if you've read them). I've been dealing with 35sec compile durations this entire time, 8 seconds is fine by comparison.

**Comment by buthed010203** [comment]
Ok I looked into it a bit, looks like KSP [does support java input](https://kotlinlang.org/docs/ksp-faq.html#is-ksp-kotlin-specific) but I still think its just Kotlin output

**Comment by buthed010203** [comment]
Strangely enough, the "change" in `NullUnit` is just an arg not being properly renamed...
![](https://mee6.is-terrible.com/5rPYYICFi.png)

**Comment by Anuken** [comment]
It shouldn't need to be renamed at all; it looks like parameter name info is just lost every other compilation - I'm not even providing these names directly. Easy fix is to make them all `argX` by default.

 I fixed the two changing classes, and compilation still takes about 8 seconds, it seems.

**Comment by buthed010203** [comment]
I tried creating the `incremental.annotation.processors` as specified in gradle's docs and kapt doesn't seem to like it... Unsure if I configured it wrong or if kapt just hates it or what...

**Comment by Anuken** [comment]
I think it does that regardless, there's no extra work being done since I only handle the first round, and there's nothing being passed to the processors:

![image](https://user-images.githubusercontent.com/10100000/160307679-6d3fc8c2-04d3-4e0d-93cf-3caa902b2f65.png)

**Comment by Anuken** [comment]
The best way to decrease compilation time now would be to optimize EntityProcess, I think, as it's taking up the bulk of the annotation processing time. I haven't benchmarked or optimized it at all.

**Comment by buthed010203** [comment]
> The best way to decrease compilation time now would be to optimize EntityProcess, I think, as it's taking up the bulk of the annotation processing time. I haven't benchmarked or optimized it at all.

Yeah, ~2800 of the ~3000ms are spent in the `//create component interfaces` loop

**Comment by buthed010203** [comment]
The slowdown is actually all just caused by the write method...
![](https://extremely.questionable.link/5rQJ1sOme.png)

**Comment by Anuken** [comment]
I wonder if the writer can be used in parallel.

**Comment by buthed010203** [comment]
Funny story, you dont even need one

**Comment by buthed010203** [comment]
Just change the outputstream to a writer and it instantly performs 100x better
![](https://mee6.is-terrible.com/5rQQ7eGBo.png)

**Comment by Anuken** [comment]
but why

**Comment by buthed010203** [comment]
That's a better tagline than the lie that is "write once run anywhere"

**Comment by buthed010203** [comment]
Its also faster for the bottom branch as well apparently

**Comment by buthed010203** [comment]
In total, its about 20x faster at writing than it was previously
![](https://i-dont.go-outsi.de/5rQUMEHFg.png)

**Comment by Anuken** [comment]
> Its faster for the bottom branch as well apparently

But that should use `openWriter` internally as well?

**Comment by buthed010203** [comment]
> But that should use `openWriter` internally as well?

It does a lot of extra stuff that apparently wasn't useful at all

**Comment by Anuken** [comment]
honestly quite incredible

**Comment by buthed010203** [comment]
Now back to trying to fix power node links not being saved in schematics, this isn't going to end well for me.

**Comment by Anuken** [comment]
~~links were a mistake, embrace the upcoming config-less nodes~~

Anyway this seems to be solved now so I'll be closing it (again)

I'd like to get on Discord but it's still about 4-5 days until April 1st, so you won't be seeing me online there until then.

**Comment by buthed010203** [comment]
~~Links are fine, I blame these~~
![](https://yagpdb.is-ne.at/5rQYo1KM9.png)
![](https://xenon.is-ne.at/5rQYEgYuE.png)

**Comment by Shawak** [comment]
@[buthed010203](https://github.com/buthed010203) Did you check the timings for `getBytes()`? Probably that was bottleneck

**Comment by buthed010203** [comment]
> @[buthed010203](https://github.com/buthed010203) Did you check the timings for `getBytes()`? Probably that was bottleneck

It took like 4ms total

**Comment by buthed010203** [comment]
Maybe its a windows thing or something, it takes 3ms with the stream on mac, 2ms with the writer

**Comment by Anuken** [comment]
The stream was slower on Linux as well.

**Comment by buthed010203** [comment]
Maybe its related to the M1 not flushing disk writes or whatever

**Comment by Anuken** [comment]
wait, does that mean the stream you get is actually writing one byte at a time? is that why it's so slow?

**Comment by buthed010203** [comment]
I dont know, all I know is that there are a lot of classes so even if it wrote the whole thing at once it would be slow. I also tried wrapping it in a bufferedoutputstream and that made 0 difference so meh
