### ISSUE TITLE
BlockIndexer not unmarking damaged blocks client side

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#6679]
**Platform**: Mac (everything else too)

**Build**: 135

**Issue**: BlockIndexer isn't properly removing blocks from the damaged list despite the block being full hp.
Is contained in the team's damage blocks:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/26940575/160897146-19f124bc-16c0-49fe-88e6-3cc9f909a628.png">
Bullet does not collide with the block as its full health:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/26940575/160897246-773a75aa-304a-416f-b1c2-279a8f5d9153.png">
Damaged returns false and health is actually full:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/26940575/160897728-82c36df8-60cf-4e7c-8da5-d7ebf7494c3c.png">
wasDamaged remains true:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/26940575/160898881-a6a5bc64-f7dc-4c0d-89dd-40fc395d4599.png">

**Steps to reproduce**: Heal some blocks with a unit, probably easiest to see on mobile with autotarget.

**Link(s) to mod(s) used**: Foo's (this could be a bug that i somehow introduced but i dont think thats the case)

**Save file**: A save file isn't going to be helpful as this only happens as a client and syncing fixes it (its probably a packet loss problem or smth?) but here it is anyways, i dont want my soul reaped [h.msav.zip](https://github.com/Anuken/Mindustry/files/8382888/h.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
The other thing thats annoying is when you heal something client side but it doesnt heal on the server

**Comment by Anuken** [comment]
This isn't hard to fix clientside (removeAll from the damaged buildings every return), but I don't think you should be getting the damaged blocks clientside anyway - indexing doesn't really work when the server can just send different data at any time.

**Comment by Anuken** [comment]
Fixed in private branch. Still won't be fully accurate in regards to newly synced damaged blocks, I think.

**Comment by buthed010203** [comment]
Not that anyone would really need that.

What about the healing client side but not server side?

**Comment by Anuken** [comment]
That isn't synced at all, needs its own Call method, like damage does. I'm too busy right now to implement it.

**Comment by buthed010203** [comment]
Fair enough, isnt the build health synced though?

**Comment by Anuken** [comment]
Only certain blocks are synced, things like conveyors or walls are not.

**Comment by buthed010203** [comment]
ah
