### ISSUE TITLE
sdgjkhgjskgdf doesn't work

### ISSUE THREAD

**Issue by liplum** [Anuken/Mindustry#6686]
**Platform**: *Windows 10*

**Build**: *v135.1*

**Issue**: *When I want to start THE EVENT by hitting the button. A white window flashed and vanished into the air, but the only left were "oserr.nim(95) raiseOSError Error: unhandled exception: Access is denied. Additional info: C:\Users\Liplum [OSError]" and 
lonely me. Bad joke ;( *

**Steps to reproduce**: *Just hit "The Event" on main menu*

**Link(s) to mod(s) used**: *None*

**Save file**: *No save*

**(Crash) logs**: *[I] Attempting E:\PlumUserTemp\absurd\windows64.exe*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Do you have an antivirus? I can't reproduce it on any machines.

**Comment by Anuken** [comment]
You could also try running the Windows exe [directly](https://github.com/Anuken/Mindustry/releases/tag/v135.1)...

**Comment by liplum** [comment]
Yes, I have an anti-virus. After closing it, I can eventually enjoy my joke XD. I know you, this is a part of the April Fool, right?

**Comment by Falling10fruit** [comment]
Why does my computer think it's unsafe?
