### ISSUE TITLE
Game crashes under certain circumstance

### ISSUE THREAD

**Issue by cigarmemr** [Anuken/Mindustry#6687]
**Platform**: *Windows 10 x64*

**Build**: *steam 135.1*

**Issue**: *Game crash*
![image](https://user-images.githubusercontent.com/26317456/161304010-2445370a-3627-4f35-ae70-55cab9997be5.png)

**Steps to reproduce**: 
*1 Start a custom game with the built-in map Glacier, choose the gamemode Sandbox. Keep other settings as defaults.*
*2 Train a unit and use it to destroy the hostile (red) core. The game continues.*
*3 Place a thorium reactor near your (yellow) core. Fill it with thorium. It explodes and destroy your core.*
*4 The crash should happen at this moment.*

**Link(s) to mod(s) used**: *None.*

**Save file**: 
[save.zip](https://github.com/Anuken/Mindustry/files/8399495/save.zip)

**(Crash) logs**: 
[crash log.zip](https://github.com/Anuken/Mindustry/files/8399519/crash.log.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was reported/fixed in the private branch.
