### ISSUE TITLE
UNKILLABLE BOSS OH GOD 

### ISSUE THREAD

**Issue by erw1nromme1** [Anuken/Mindustry#6691]
**Platform**: *Android/iOS/Mac/Windows/Linux*          [Android]

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*             [Build 126.2]

**Issue**: *Explain your issue in detail.* "Bug where a boss is impossible to kill, i have no idea how this happened, I was just stressing in the forgotten shores sector, saw my desert sector being ruined by enemies, went there, it was already wave 59 / 60 on the invasion thing, i fixed a couple of stuff in my base, but after this, my base had the final wave, so i eagerly waited, then the boss appeared after i killed the goons with my turrets, but somehow i was feeling like this was a fight thats gonna end quick since i had alot of anti air in that sector, but it had no health so you can see where im going, it killed all of my sector defenses in that area, You see, that sector had an abundance of resources so i had a struggle to initially conquer that location in my first time, its become my pride in that location as its my very first super industry location, if that sector falls, My progress will  be on setback by quite alot so you can see why im worried sick and struggling, help me with the boss please, literally no hitpoints, it would have died very quick since i had alot of aa in that area, thank you and heres the zip for mindustry
[Apocalypse is nigh .zip](https://github.com/Anuken/Mindustry/files/8402654/Apocalypse.is.nigh.zip)
"

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*                                        "i dont even know how, it just appeared with no health at my final wave there, i just arrived late after finishing the Forgotten shores sector fight and saw the industry sector was being invaded, it was already wave 59 out of 60 so i never worried until the boss came and wrecked my stuff"

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.* "None"

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.     "Uhhhhhhhh I, yes sir"

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*   "no crashes, just bug"

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by erw1nromme1** [comment]
![Screenshot_20220402-213114_Mindustry](https://user-images.githubusercontent.com/102864456/161386828-8fe99909-02cd-41ba-a664-9a85ecab2178.jpg)
![Screenshot_20220402-210816_Mindustry](https://user-images.githubusercontent.com/102864456/161386839-03de72e5-5865-405a-b47a-ab69953494e6.jpg)
![Screenshot_20220402-204530_Mindustry](https://user-images.githubusercontent.com/102864456/161386852-f7c98b39-ea99-47b1-988e-aeb805ca3ff1.jpg)
Heres all the imgs as proof

**Comment by Anuken** [comment]
I loaded the save, and that's not a boss - just a T4 unit, which is why it doesn't have a guardian health bar. It's not unkillable, as you've already damaged it in the save. You just don't have the right defenses to deal with it - scatters are not effective against units with armor, like that one.

**Comment by buthed010203** [comment]
~~at least hes not using metaglass cyclones~~

**Comment by bendnuts** [comment]
~~did he really expect to beat a antumbra with lead scatts~~

**Comment by EclipseTheOldOne** [comment]
> ~did he really expect to beat a antumbra with lead scatts~

~actually did that before and it work~

**Comment by guncatt** [comment]
> ~~did he really expect to beat a antumbra with lead scatts~~

I mean in v5 if the scatters had metaglass totally.

**Comment by EclipseTheOldOne** [comment]
> > ~did he really expect to beat a antumbra with lead scatts~
> 
> I mean in v5 if the scatters had metaglass totally.

~~lead used~~
