### ISSUE TITLE
Sector export to lost sector still displayed

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry#6692]
**Platform**: Linux

**Build**: Steam 135.1

**Issue**: 
The resource export of one of my sectors is still shown to be exporting to sector 129, despite the fact that I've lost sector 129.
In the sector, the launchpads correctly display that it's being launched to the sun.

**Steps to reproduce**:
Start launching resources to a sector.
Lose the sector.
Check the stats of the sector that's exporting resources, where it says where it's exporting to.
Then check the launchpads inside the sector.
The launchpads will say "the sun" while the sector stats will say the name of the sector you lost.

**Link(s) to mod(s) used**: None applicable

**Save file**: This is not related to a single sector, but rather to my whole campaign.

**(Crash) logs**: Not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in private branch.
