### ISSUE TITLE
Damaged units get stuck on unpowered Repair Points.

### ISSUE THREAD

**Issue by SimonWoodburyForget** [Anuken/Mindustry#670]
System info:
- Mindustry v93
- Ubuntu 18.04

If a flying unit (Repair, Miner, Phantom, ...) gets damaged, he goes to the nearest Repair Point regardless of whether it's powered or not, and will get stuck on it forever, until it's eventually removed or powered.

**Comment by Anuken** [comment]
This is intentional. Units will retreat to these points when damaged to avoid dying, even if they are not currently operational.
