### ISSUE TITLE
Missing item textures

### ISSUE THREAD

**Issue by NeonSupernova** [Anuken/Mindustry#6700]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**:135.1 pre alpha

**Issue**: Missing item textures when they are in the mod

**Steps to reproduce**: load the mod, opn he editor, and look at the conveyors and ores

**Link(s) to mod(s) used**: https://github.com/NeonSupernova/Masterdustry/tree/master

**Save file**:NA/Any game will work

**(Crash) logs**:No crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Issues with mods should not be filed here.

**Comment by NeonSupernova** [comment]
then where can I get some help?

**Comment by Anuken** [comment]
Ask in `#modding-general` and/or look at some similar mods to see how they name conveyors and ores.
