### ISSUE TITLE
OS.exec("read") freezes game

### ISSUE THREAD

**Issue by bendnuts** [Anuken/Mindustry#6702]
**Platform**: *Arch Linux*

**Build**: 135.2

**Issue**: When running `OS.exec("read")` game freezes

**Steps to reproduce**: Am making mod, tried to use OS.exec. To reproduce, open mindustry, run `OS.exec("read")` in terminal

**mod used**: *https://github.com/DeltaNedas/dev-mode*

I have no soul

**logs**: *it doesnt crash, theres no log, and it just freezes.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
> game crashes



> it doesn't crash

wh-

**Comment by LeoSko** [comment]
What would you expect though?

**Comment by Bottinator22** [comment]
The game always produces logs btw

**Comment by bendnuts** [comment]
> The game always produces logs btw
> 
> Even if there isn't a crash

Actually.... It can crash silently, AND it can freeze silently. What you mean is it always produces normal logs, such as 
`JAVAVERSION : 16`
and such. What i mean is it creates no logs DURING THE FREEZE.

**Comment by bendnuts** [comment]
> What would you expect though?

🤔 i would expect it to either time out, or to disable read-like functions.

**Comment by Anuken** [comment]
> i would expect it to either time out, or to disable read-like functions.

That is not a reasonable expectation. OS.exec calls `Runtime.getRuntime.exec`, *which blocks the thread*. Why would it time out? There is no mention of anything like that.

> What i mean is it creates no logs DURING THE FREEZE.

Of course, because you've frozen the main thread.

**Comment by bendnuts** [comment]
> > i would expect it to either time out, or to disable read-like functions.
> 
> That is not a reasonable expectation. OS.exec calls `Runtime.getRuntime().exec`, _which blocks the thread_. Why would it time out? There is no mention of anything like that.
> 
> > What i mean is it creates no logs DURING THE FREEZE.
> 
> Of course, because you've frozen the main thread.

How does one run `OS.exec` in a different thread?

**Comment by Anuken** [comment]
Look up "Java run code in new thread" or something similar, it's not very simple and there are different approaches depending on performance requirements.
