### ISSUE TITLE
Sector 7 spawn bug

### ISSUE THREAD

**Issue by mvrak** [Anuken/Mindustry#6703]
![image](https://user-images.githubusercontent.com/1041875/162614477-3c9e2aec-5712-491f-bf0e-21562ae3b8d4.png)

**Platform**: Windows/all

**Build**: 135

**Issue**: Ground units at left spawn are stuck. oil patch in the way, see picture, needed to build a foreshadow to reach them

**Steps to reproduce**: play in sector 7

**Link(s) to mod(s) used**: 0

**Save file**: 
[sector-serpulo-7.zip](https://github.com/Anuken/Mindustry/files/8458784/sector-serpulo-7.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The private branch happens to have different generation for this sector, so the issue doesn't occur.
