### ISSUE TITLE
water triangles

### ISSUE THREAD

**Issue by Radio-Silence-1** [Anuken/Mindustry#6707]
![Screenshot 2022-04-13 7 36 21 PM](https://user-images.githubusercontent.com/98431859/163291681-f3290833-06c0-4783-a166-57fd97c01ac5.png)

**Platform**: *Android/Linux*

**Build**: *pre-alpha build 135*

**Issue**: *water has werid triangle flowing next to it*

**Steps to reproduce**: *as far as I know just placing water, maybe it has to have the floor type and an ore on top (sorry for not knowing the floor type used, it is a server, 2r2t) i could not get a video to work, but the triangles are moving down at a slightly faster speed than the water animation*

**Link(s) to mod(s) used**: *none.*

**Save file**: *I cant make a save of a server, it says no permission but I have given all permissions possible...*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *non.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Save files are required for these kinds of bug reports.

**Comment by Radio-Silence-1** [comment]
[11.zip](https://github.com/Anuken/Mindustry/files/8485430/11.zip)
i got it to work... .msav did not work on github so I had to zip it... sorry about not having the file in the first one

**Comment by Radio-Silence-1** [comment]
does that help at all?

**Comment by Anuken** [comment]
Yes, I have fixed it in the private branch now, thanks.
