### ISSUE TITLE
Relocation to another zone

### ISSUE THREAD

**Issue by Loginpls** [Anuken/Mindustry#6710]
**Platform**: `Android 30`

**Build**: `release build 126.2`

**Issue**: *When I wont to go to another zone but it came from a differend zone than I wanted.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[Xelo/xelos-pixel-texturepack:0.4.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
No steps to reproduce, no save file, and not the latest version

**Comment by DeltaNedas** [comment]
marko zajc

**Comment by Loginpls** [comment]
Please make it so that if you want to go to a zone, it will be from the zone are in and not from other zones.

**Comment by Bottinator22** [comment]
I believe he's mentioning the fact that you can't launch to optional sectors from non-adjacent sectors, thinking that's a bug

it's not
