### ISSUE TITLE
Steam Workshop (Name & Description) overwrite

### ISSUE THREAD

**Issue by NickName73** [Anuken/Mindustry#6715]
**Platform**: `Windows`

**Build**: `135.2`

**Issue**: Mindustry rewrite name and desc of mod in steam workshop every time when mod update

**Steps to reproduce**: Mod List > Select Mod > Upload (Steam) > Update > Ok

**Link(s) to mod(s) used**: [GRavillaso](https://github.com/NickName73/Gravillaso) (For uploading)

**Save file**: NOT REQUIRED

Its 100% bug, cause its not logical
May add choice menu `Do you want to change current name and description?` (YES) (NO)

---
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I dont use mods that changing UI**

**Comment by Anuken** [comment]
It overwrites the name/description with what?

**Comment by NickName73** [comment]
Scange name & desc on steam to the id & description from mod

**Comment by Anuken** [comment]
Why is that illogical or unexpected? You're updating the mod, and that information is part of the mod.

**Comment by NickName73** [comment]
If i change mod description on steam page, he anyway replace it (and doesnt ask)

**Comment by Anuken** [comment]
I don't see how that's a bug. Steam mod descriptions should match their in-game descriptions; just change the mod description instead. It might be nice if it asked in certain situations, but that's not an implemented feature.

**Comment by NickName73** [comment]
Why should?
Github description and Mod description not same, but why steam should be same?
If you want to i realize this feature, i can (probably)

**Comment by Anuken** [comment]
> Github description and Mod description not same, but why steam should be same?

It doesn't *need* to be, but I don't think it's unreasonable. It's the same mod, after all.

> If you want to i realize this feature, i can (probably)

It's not very difficult to add, I can do it myself.

**Comment by NickName73** [comment]
Thnks, its very annoying thing (I should change description every time)
