### ISSUE TITLE
Issue in exporting data to steam version mindustry from snap installed version

### ISSUE THREAD

**Issue by Ridhwanluthra** [Anuken/Mindustry#6719]
**Platform**: *Linux*

**Build**: *steam build 126.3 and pre alpha build 135*

**Issue**: *I am trying to export my data from the 135(which was installed on ubuntu from the snap store) build to the steam version since I recently bought it. All of my research and schematics seem to be there but no campaign progress.*

**Steps to reproduce**: *export data from 135 to 126.3*

**Save file**: *https://drive.google.com/file/d/1QvPKZ67e7GOPwbckhfJSLL2CfE1YZI5P/view?usp=sharing*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Update the steam version to 135

**Comment by bendnuts** [comment]
mfw snap

**Comment by Anuken** [comment]
> Steps to reproduce: export data from 135 to 126.3

You can't do this. Older versions cannot know about the formats of newer versions. Use the beta branch on Steam.

**Comment by Ridhwanluthra** [comment]
Thanks that solved it.
