### ISSUE TITLE
Long startup, lag spikes, high cpu usage, etc

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry#6721]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows 10 64 (both 21H1 and 21H2)
CPU: R5 3500x (has no multi-threading)
RAM: 2x8 2666 jedec base timings
GPU: GTX750 (1GB GDDR5)
sata SSD

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
doesnt matter, i tested both 126.2, 135 and around 3 months worth of BE versions. I believe i even tried v5 104.6 at some point

**Issue**: *Explain your issue in detail.*
(100% reproduceability, both at every single game startup and during playing)
Simply starting the game takes 30s up to 1min, instead of like 5s (and the CPU usage goes to 100% during the entire duration). Logs dont show anything unusual.
Lag spikes and freezes every 5-10 seconds during gameplay (even on an empty map)
Overall high VRAM usage (750-800MB) and high CPU usage (80-90% on 1 or 2 threads). High ram usage (1.7-1.8GB instead of barely 500MB on another computer with the same save)
Almost clean Windows install, no weird process or service running in the background. Nothing unusual i was able to detect from HWInfo, very low temperatures and normal clocks on everything.

Maybe its tied to some windows update somehow affecting the CPU scheduler? But like no other game has these kinds of issues, even intensive AAA titles or CPU intensive tasks. I got no clue. Im lost

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
if only i knew :/
One day i woke up and the game went from running smooth to *that*. That was like 3-4 months ago but this PC is at my other house so its not that annoying or i would have filled that report a lot earlier

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
vanilla

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
literally doesnt matter, i tried on a whole new save, as well as a used one, on empty or filled maps, its the exact same thing

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
rather annoying but it doesnt even crash. I could get some info from logs but... no.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not sure what you expect me to do. I test regularly on VMs and other devices, and I've never had this problem; it takes far less than 30 seconds to boot up even on my phone or a VM with *software rendering*. It's almost certainly something wrong with your system, as:

- it doesn't seem associated with version (or anything I did) at all
- it isn't associated with game data
- it wasn't caused by any specific update
- it doesn't occur anywhere else

You could try any of the following:

- reinstalling Windows
- disabling any antivirus you have to see if it's affecting the game somehow
- checking your hardware
- ~~installing Linux instead~~

**Comment by buthed010203** [comment]
Based on the fact that you author [this](https://github.com/hortiSquash/hortiDefinition) I'm gonna assume you use it. Have you run the game with debug logging on on startup? Theres a very good chance its the sprite packing and bleeding causing that (not to mention that fps in game will probably die too)
