### ISSUE TITLE
yo?

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#6722]
![a](https://user-images.githubusercontent.com/61173114/163861842-bc6e9aab-bcbe-4af5-96f1-94e935f5a7cb.png)

did you forget the change the changelog or just accidentally re-sent it

**Comment by Anuken** [comment]
Neither. The bot is flipping out for no reason; I thought I fixed this.

**Comment by BlueWolf3682** [comment]
ah i see

**Comment by Anuken** [comment]
Actually it's not even the bot, it's almost certainly Github API not returning the latest version. Fixed now.
