### ISSUE TITLE
Frozen screen of Core drop on new multiplayer pvp steam server

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Anuken/Mindustry#6728]
**Platform**: Windows

**Build**: Steam Build 135

**Issue**: I recently gifted my friends Mindustry to play PvP, and I got them to use the Beta since it has some nice features. I attempted to start a Multiplayer PvP server on Glaciers, but was greeting with a frozen screen of the Core falling. I attempted to use one of my custom made maps but was also greeted with the same issue.

**Steps to reproduce**:
1. Enable the Steam Beta
2. Start a new pvp multiplayer server on Glaciers

**Link(s) to mod(s) used**: No mods were used

**Save file**: https://mega.nz/file/tnhmCAAb#C-dY_HdfQt-7_cwIiXS_4C9ClPIXaqAQEtgt6gIjMrY

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Refer to above

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
This is not a bug - get the other player to join
(bad mobile crop) The game begins paused, waiting for a second player to join.
![Screenshot_20220422-014529](https://user-images.githubusercontent.com/61173114/164638986-05a7f8e7-7bc2-492d-b66a-ae6948b876c1.png)

**Comment by Just-a-Unity-Dev** [comment]
Well it seems really wonky and looks like a bug. Perhaps a contributor could replace the frozen core drop with a screen that says something along the lines of "Get the other player to join to play"? But thanks for the information

**Comment by Anuken** [comment]
I think the "waiting for players" text should just be moved back into the center of the screen instead, that looks awful on mobile.

**Comment by BlueWolf3682** [comment]
~~yes, it very much does.~~
