### ISSUE TITLE
Weird bug in micro processor?

### ISSUE THREAD

**Issue by Inventor4life** [Anuken/Mindustry#6730]
There seems to be a weird glitch with the processor and bit shifting. When using the bit-shift operator command (>>), it stops working after so many numbers.

Given the example:
//
set r 0
op shr result -6148914691236517206 r
op mod result result 2
print result
printflush message1
op add r r 1
jump 1 lessThan r 64
//

With -6148914691236517206 being the decimal representation of 10101010101…101

After attaching a message block it is possible to see the input switching between -1 and 0 rapidly before pausing on zero for a few seconds. The zero pause happens at r ≈ 54 and continues until r=63

The processor can handle up to 64 bit variables, meaning the largest/smallest values can be 2^64 and -(2^64) - 1. -6148914691236517206 falls between these two numbers.

**Comment by Anuken** [comment]
> The processor can handle up to 64 bit variables, meaning the largest/smallest values can be 2^64 and -(2^64) - 1.

No. All values in the processor are stored as 64-bit floating point values. `-6148914691236517206` cannot be accurately stored as a `double`, so you get strange results. All bitshift operations involve casting the double into a `long`, shifting, and casting back.
