### ISSUE TITLE
Bullet#88 Warning causes LiquidTurret to crash mod

### ISSUE THREAD

**Issue by Beanzilla** [Anuken/Mindustry#6732]
**Platform**: Linux

**Build**: 6.0 build 126.2

**Issue**: 

**Steps to reproduce**: I downloaded the latest version from the github releases (the jar to be exact) executed it and then downloaded 1 mod, gone to play and got error.

**Link(s) to mod(s) used**: [mindustry-hacked](https://github.com/Beanzilla/mindustry-hacked/tree/d54f63037657264a9fbb11a2abbec7c369cc7363) Use d54f630 branch (should be latest on that mod)

**Save file**: This occurs on startup no save needed.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

> Again, occurs on startup the mod gets claimed as failing to load because of issue with cryofluid

**(Crash) logs**: [tmp.txt](https://github.com/Anuken/Mindustry/files/8559817/tmp.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You cannot refer to custom status effects as strings in v6. Define the whole effect with `{name; "Name", etc}`, use vanilla status effects, or upgrade to v7.

**Comment by Beanzilla** [comment]
Will referring to custom status effects as strings be dependable on v7 and above?

**Comment by Anuken** [comment]
It should be in the private branch.
