### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Peugeot205GTI** [Anuken/Mindustry#6733]
is there a way to connect to game servers using a proxy in the game?

**Comment by Phinner** [comment]
1. If you mean a something like a VPN, yes, but it will most likely get you banned from the server.
2. This isn't the place for asking questions, it happens in the [discord](https://discord.gg/mindustry), specifically in the #multiplayer channel.

**Comment by end-me-please** [comment]
You can use a proxy, but some servers don’t allow you to connect with a proxy because they can be used to evade IP bans.

**Comment by Anuken** [comment]
The issue tracker is for bugs, not questions.
