### ISSUE TITLE
On planet view, water-resource icon becomes a water-tile icon upon relaunching the game

### ISSUE THREAD

**Issue by YellowAfterlife** [Anuken/Mindustry#6737]
**Platform**: Windows

**Build**: steam build 135 (v7-testing)

**Issue**: Both water icon in Resources list and water icon as a custom sector icon turn into a water tile upon relaunching the game.

Before:  
![jpg](https://user-images.githubusercontent.com/731492/166045490-69b283de-7b2f-4705-9705-6c7e9bf3e8b8.jpg)

After:  
![jpg2](https://user-images.githubusercontent.com/731492/166045641-a4ab9ecb-d7e4-4260-aa1a-51190caa4b4f.jpg)

**Steps to reproduce**:

- Encounter a sector with a water resource, such as by capturing a sector next to it for the first time
- Capture the sector
- Set the sector's custom icon to water resource ("water drop") one
- Relaunch the game
- Note how both the sector's icon and the icon in resource list are now the water tile ("water square")

**Link(s) to mod(s) used**: none

**Save file**: [minbug.zip](https://github.com/Anuken/Mindustry/files/8593200/minbug.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed in private branch.
