### ISSUE TITLE
Colors get parsed in filenames in the in-game FS dialog

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#6738]
**Platform**: Linux

**Build**: 135

**Issue**: .

**Steps to reproduce**: Have a file called `[].msav`. Open the import map dialog box.

**Link(s) to mod(s) used**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed in private branch
