### ISSUE TITLE
Crash when moving into a busy router

### ISSUE THREAD

**Issue by 1dNDN** [Anuken/Mindustry#6739]
**Platform**: *Windows*

**Build**: *135.2*

**Issue**: *Crash when moving into a busy router*

**Steps to reproduce**: *1. Install the router
2. Let your friend inhabit it
3. Move into it yourself
4. Watch the deadly crash*

**Link(s) to mod(s) used**: *Nothing*

**Save file**: *1dndn.ru/files/sector-serpulo-86.zip*

**(Crash) logs**: *1dndn.ru/files/crash-report-04_29_2022_23_09_57.zip*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have not attached a crash log or a save.

**Comment by 1dNDN** [comment]
> You have not attached a crash log or a save.

But 
![image](https://user-images.githubusercontent.com/42769281/166064646-66955f5e-08ca-436d-adb7-d819e8e97ec5.png)

**Comment by Anuken** [comment]
That is not accessible and doesn't show up as a URL - upload the file to Github, there's no reason to link anything.

**Comment by 1dNDN** [comment]
> That is not accessible and doesn't show up as a link - upload the file to Github, there's no reason to link anything.

Fixed

**Comment by Anuken** [comment]
Should be fixed in the private branch.

**Comment by 1dNDN** [comment]
> Should be fixed in the private branch.
Thanks
