### ISSUE TITLE
Can't open Ground Zero's Stat (In Campaign)

### ISSUE THREAD

**Issue by Nunting** [Anuken/Mindustry#6740]
**Platform**: `Windows 10 x64`

**Build**: `steam build 135.1`

**Issue**: Game forced to exit when trying to view stat of ground zero.

**Steps to reproduce**: Perhaps, there is a problem with the launch pad connected by ground zero in various regions. I'm not sure.

**Link(s) to mod(s) used**: `[sk7725/time-control:0.2]`

**Save file**: 

**Crash report**: 
[hs_err_pid32.log](https://github.com/Anuken/Mindustry/files/8595546/hs_err_pid32.log)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The error log is not the actual crash, it's a Window (?) bug that occurs when the game *exits*. The actual crash is almost certainly fixed in the private branch (already reported).

**Comment by Nunting** [comment]
> The error log is not the actual crash, it's a Window (?) bug that occurs when the game _exits_. The actual crash is almost certainly fixed in the private branch (already reported).

Is this phenomenon related to window? Will it be resolved in the next release? Or should I reset the game data?

**Comment by hortiSquash** [comment]
> > The error log is not the actual crash, it's a Window (?) bug that occurs when the game _exits_. The actual crash is almost certainly fixed in the private branch (already reported).
> 
> Is this phenomenon related to window? Will it be resolved in the next release? Or should I reset the game data?

yes
probably yes
no

**Comment by Anuken** [comment]
> Will it be resolved in the next release?

No. It is a native crash in the Windows API for text input. I don't know how I would even begin trying to fix it.
