### ISSUE TITLE
Factories release crawlers only on top base

### ISSUE THREAD

**Issue by Somka000** [Anuken/Mindustry#6745]
**Platform**: Windows/Linux

**Build**: 135.2

**Issue**: I put on my map 4 factories of crawlers, all producing crawlers, but only 2 factories on top map release crawlers. Situation was on server. Unit cap was set to 2, blue team dont have cores. Even when all crawlers was destoyed and on top factories still producing units (these not realsing because they dont have produced), factories under dont realesing finish units, so only top team, crux was attacked by blue team. If you need more information you can ping too Ilya246, he see it too. In singleplayer, everything was fine, but it is definitely not the plugin's fault

**Steps to reproduce**: Playing on this map, i dont have this map because i remove factories and update old map. I dont make save when this map was played on server.

**Link(s) to mod(s) used**: Plugins: JSEval, mapChange, teamChangeMod

**Save file**: If you really need old map i can restore map's most faithful appearance, but it will take some time. 

 
![bug11111111111111](https://user-images.githubusercontent.com/51973243/166464882-0d9b2761-72f9-4b67-892c-de9d36622e07.png)

![bug2222222222222222](https://user-images.githubusercontent.com/51973243/166464925-a98a74d6-577c-4f36-a2ef-d95bd41fca05.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
~~this has to be a troll.
somka you know what unit cap is~~

**Comment by Anuken** [comment]
> Steps to reproduce: Playing on this map, i dont have this map because i remove factories and update old map. I dont make save when this map was played on server.

Saves are required for a reason, how do you expect me to test this without a map...?

**Comment by Somka000** [comment]
[catfish.zip](https://github.com/Anuken/Mindustry/files/8611006/catfish.zip)

**Comment by Anuken** [comment]
> unit cap was set to 2 so that's still a bug
> but only 2 factories on top map release crawlers

The update order of buildings is non-deterministic. With a unit cap of *2* and all 4 factories having units ready, there is no defined order in which units will be released. Sometimes it will be only the bottom ones, sometimes only the top ones, sometimes a combination of the two sides. I loaded the map, and only the *bottom* two factories outputted anything, because the buildings there happened to be loaded first. 

Removing the bottom two factories and killing all units let the top factories release theirs, so there is no bug here.

**Comment by Somka000** [comment]
ok, good to know
