### ISSUE TITLE
Routers don't pass back

### ISSUE THREAD

**Issue by Milinai** [Anuken/Mindustry#675]
Seriously. I've been using passback in the correct way: passing an item through it, for example [like so](https://cdn.discordapp.com/attachments/558240383134334997/623514261213413376/IMG_20190917_075413.png). The fact that routers don't pass back upsets me a lot. I would rather see routers and distributors being unable to be placed next to other routers and distributors. I haven't thought much about how useful the passback is before, but now that it is gone, I really miss it. ~~Router junction blocks will start working again if routers pass back again. Please do something about them instead.~~

**Comment by Anuken** [comment]
See changelog.
