### ISSUE TITLE
Visual bug in-game editor maps

### ISSUE THREAD

**Issue by Somka000** [Anuken/Mindustry#6752]
**Platform**: Windows

**Build**: 135.2

**Issue**: In-game editor map after removing placed blocks near mend projector, still is showed healing range effect on 1x1 blocks. Overdrive effect is too bugged.

**Steps to reproduce**: 
1. Remove blocks near mend projector
2. Move cursor on mend projector
![image](https://user-images.githubusercontent.com/51973243/167034691-a8f1bda1-b03e-4361-9a3d-9bb77cc98820.png)
![image](https://user-images.githubusercontent.com/51973243/167034774-9a53c749-a4fd-4af1-8eab-20a596bf61d0.png)

**Link(s) to mod(s) used**: None

**Save file**: 
[bug.zip](https://github.com/Anuken/Mindustry/files/8636393/bug.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce this in the private branch, and considering relevant code was definitely changed, this is most likely fixed.
