### ISSUE TITLE
Community Servers Not Showing Up Mac

### ISSUE THREAD

**Issue by Naginat4** [Anuken/Mindustry#6755]
**Platform**: Mac

**Build**:  v126.2

**Issue**: When i open up mindustry, hit play, join game, nothing appears in the server list, and if i attempt to put in the ip of a server it says not connecting to server.

**Steps to reproduce**: I found this issue after wanting to join a server,  steps to reproduce are open/play/join game

**Link(s) to mod(s) used**:  none

**Save file**:  this is not an in game issue

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.    "fair enough, ive attempted game development and i respect the pain you go through. However, this isnt an in game issue"

**(Crash) logs**:  not crashing
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
Found someone who used steam-linux and had this issue, this is itch-mac

**Comment by end-me-please** [comment]
Usually when people have this kind of issue, they just have to press the button to un-hide the player list.
But since you mentioned that it doesn’t work when adding an address manually, maybe it’s a firewall problem on your side?

**Comment by Anuken** [comment]
The server list is either blocked in your country (unlikely, considering you are on Github) or you have some sort of other connection issue to github. This is unfixable without a log.

**Comment by Bottinator22** [comment]
> This is unfixable without a log.

suggestion: update template so that connection issues at least get logs to help
