### ISSUE TITLE
idInUse error not reporting ID

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#6761]
**Platform**: Server

**Build**: Erekir

**Issue**: `[05-07-2022 05:43:33] [I] Kicking connection 1.2.3.4 / AAAAAAAA; Reason: idInUse`

**Steps to reproduce**: Connected with the same UUID to a server.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
