### ISSUE TITLE
Attacks impossible to fend off due to active sectors always surviving 0 waves

### ISSUE THREAD

**Issue by stacktrace-error** [Anuken/Mindustry#6765]
**Platform**: Windows

**Build**: 136 """"custom build""""

**Issue**: Because Serpulo sectors cannot survive any waves without the player being present in them in v7 (tested on both versions with the same defenses on the same maps), when an attack occurs you always lose one of the current sectors unless you rapidly swap between them and the wave times do not coincide.

**Steps to reproduce**: 
1. Reach craters
2. Capture and move to another map
3. Wait for it to crawler
4. **Sector lost!**

**Save file**: 
[yes.zip](https://github.com/Anuken/Mindustry/files/8644946/yes.zip)

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
_Somehow reimporting the save worked with exactly the same defense as before???????_

**Comment by guncatt** [comment]
This doesn't feel fixed.

**Comment by stacktrace-error** [comment]
should I reopen it?

**Comment by stacktrace-error** [comment]
note: before I reimported the data this bug applied to each and every single one of the sectors on serpulo

**Comment by Anuken** [comment]
Fixed, turrets were registering as 0 DPS.
