### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by renguoa** [Anuken/Mindustry#6769]
![qw](https://user-images.githubusercontent.com/105117045/167258643-47f69b2b-408d-47f7-9a54-8c13663db87f.PNG)
### the bug appeared this afternoon ,as nu can see,this composition will make something go alone  the arrow into the classifiter in the circle
![qs](https://user-images.githubusercontent.com/105117045/167258853-038b7ca1-fe50-4a37-ae80-6a35fc85aeb2.PNG)
then they will just disappear 

thanks for providing this game ,and hope you to fix this bug
thanks again

**Platform**: `Windows 7 x64`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't see a bug here, this is just how sorters work. No save provided either.
