### ISSUE TITLE
Importing save files not working.

### ISSUE THREAD

**Issue by guncatt** [Anuken/Mindustry#6770]
**android**: *Android/iOS/Mac/Windows/Linux*

**custom build and v135.2**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* make a v135.2 save and try to import it to the custom build also works on other versions.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

I did remove it because save file not involved. (Wait it's saving the game data I think and something)
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
- You have not attached a log or error message, "not working" is not a log.
- There is no official Android build for the Erekir branch and I've made it clear that it should not be used.
- "Custom build" is not a version.
- You have not attached the save, and you have not made clear what you mean by save (game data? a specific map?)

**Comment by guncatt** [comment]
> - You have not attached a log or error message, "not working" is not a log.
> - There is no official Android build for the Erekir branch and I've made it clear that it should not be used.
> - "Custom build" is not a version.
> - You have not attached the save, and you have not made clear what you mean by save (game data? a specific map?)

The error log ![Screenshot_20220507-161600_Mindustry.jpg](https://user-images.githubusercontent.com/76461235/167273561-d2ae3f20-906f-4a56-91e4-5432608f7ff9.jpg)
![Screenshot_20220507-161553_Mindustry.jpg](https://user-images.githubusercontent.com/76461235/167273565-4af09bc2-081c-4b79-bc4d-25a3781d3bcd.jpg)
After testing I have discovered that even trying to export a savefile in v135.2 and then importing it (same version) still causes errors

I mean the game data as well. Dm me if it doesn't work I'll send the game data (don't want people to have it but I trust you with it.)

**Comment by Anuken** [comment]
That means it's just not a valid zip file; I can't fix that.

**Comment by guncatt** [comment]
Ok but when I exported it I got that zip file
