### ISSUE TITLE
Poly units heal boss crawler

### ISSUE THREAD

**Issue by cub28** [Anuken/Mindustry#6771]
**Platform**: *Windows*

**Build**: *135*

**Issue**: *just like the title says: i have Polys run around restoring things back up that get destroyed. when the boss finally shows up, the Polys shoot at it and end up healing it, effectively killing my whole mission.*

**Steps to reproduce**: *If you want to reproduce it, play planet 36, build Poly Units and advance to the boss wave at level 40.*

**Save file**: *Uploaded*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[game_save.zip](https://github.com/Anuken/Mindustry/files/8645776/game_save.zip)

**Comment by Anuken** [comment]
You are mistaken. Poly units cannot heal enemies; the boss is not a *crawler*, it is an Arkyid that heals by stealing enemies from units.

**Comment by Bottinator22** [comment]
health*
