### ISSUE TITLE
Erekier- Swarmer firerate with multipliers

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#6773]
**Platform**: *Android/iOS/Mac/Windows/Linux*

windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

the version says "custom game"   if it helps its the jar i got from (https://mindustry.dev/erekir)

**Issue**: *Explain your issue in detail.*

When giving a swarmer that already has cryo an overdrive dome, it does not fire any faster. Likewise if you give a swarmer under overdrive dome cryo, it does not fire faster. Other turrets like cyclone do not seem to have this issue. Assuming its due to how swarmer fires in set bursts of four, however salvo does not seem to have this issue to the extent that swarmer does. 

Lancer is also affected by this but that is understandable due to it having to charge up each shot

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Build swarmer. give it cryo and odd, watch as it does not fire faster than just a swarmer with cryo or a swarmer with just odd.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[swarmer.zip](https://github.com/Anuken/Mindustry/files/8646131/swarmer.zip)

nice turret demo i setup.

_fuse is meta, calling it now_

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

i am soul. soul is mine and only me

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

error no crash

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
