### ISSUE TITLE
World processor (explosion) does not damage air units even when it was set to true

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry#6774]
**Platform**: *Android*

**Build**: *Custom Build (Erekir)*

**Issue**: *The world processor's instruction named "explosion" does not damage air units even when it was set to true*

**Steps to reproduce**: *Just make a simple logic code with an explosion instruction with air set to true, playtest it and let your core unit get a direct contant to the explosion, you will not get damaged regardless.*

**Link(s) to mod(s) used**: *none*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Firstly:

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.

Since you have not attached a save I can only guess that you are trying to damage Erekir core units, which fundamentally do not take damage.

**Comment by BlueWolf3682** [comment]
I have confirmed this. (save has since been deleted) I also noted that the flying units shields (if it has any) flash as if in response to damage but take none.
