### ISSUE TITLE
[Erekir] Enemy base sectors have shifted

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry#6778]
**Platform**: *Windows*

**Build**: c8f81bd9b04e24dad3b2f81e5430632339b1c9ca

**Issue**:
Sectors that were survival maps in v135.2 are now enemy bases.
This will cause issues for anyone who has not captured them, as all of a sudden half your sectors are vulnerable, and then 5 minutes later a quarter of your sectors are gon.

**Steps to reproduce**: Played campain in bleeding edge build(erekir branch), previously played on v135.2

**Link(s) to mod(s) used**: none

**Save file**: 
[1H.zip](https://github.com/Anuken/Mindustry/files/8646340/1H.zip)

**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have not updated to the latest release (https://github.com/Anuken/Mindustry/releases) because the issue would not exist.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BalaM314** [comment]
After looking at the code, it seems like this was done because you wanted more enemy bases on Serpulo(455e3188).
Fix suggestion: On saves that are updating from v6 to v7, check if the enemy base would have existed in v6 if the sector is adjacent to a captured one.

**Comment by Anuken** [comment]
Fixed.

>  it seems like this was done because you wanted more enemy bases on Serpulo

Unrelated, that's a very old (2020) commit, it's not an exclusive part of the Erekir branch.

**Comment by BalaM314** [comment]
o h
yay my first ever issue, and it was fixed in 5 minutes

**Comment by BalaM314** [comment]
also tip, you can put something like "fix #6788" in the commit message and it'll close the issue automatically

**Comment by Anuken** [comment]
I am aware of that and have used it before, I've just been avoiding it for the Erekir branch in case it causes double-pings on merge or something.

**Comment by BalaM314** [comment]
https://github.com/BalaM314/BalaM314/issues/1
It does :/

**Comment by BalaM314** [comment]
...not?

**Comment by Anuken** [comment]
I tested and it doesn't actually close the issue from non-main branches, so it's not very useful.
