### ISSUE TITLE
Unit selection rect for command mode is glitched

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry#6779]
**Platform**: Windows

**Build**: aaccb36d934f21a563cbb5d06787ceb4161319ee

**Issue**: The unit selection rect for command mode is glitched

**Steps to reproduce**: Press shift to enter command mode, hold left mouse button and drag, release shift without releasing left mouse button, release left mouse button. Press shift again and you'll be in commandRect mode without holding lmb.

**Link(s) to mod(s) used**: none

\[insert anti soul reap shield here]: [1h.zip](https://github.com/Anuken/Mindustry/files/8646340/1H.zip)

**PR to fix**: #6780 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest commit (https://github.com/Anuken/Mindustry/commits/erekir) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
having this issue too
