### ISSUE TITLE
Entering Edit in-game without cores on erekir results in instant death

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6785]
**Platform**:Windows

**Build**: Erekir Custom

**Issue**:  Entering Edit In-game mode on erekir maps without a core results in the player immediately exploding.

**Steps to reproduce**:  https://cdn.discordapp.com/attachments/396416151032299521/972924428587528382/Mindustry_2022-05-08_15-11-06.mp4
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed.
