### ISSUE TITLE
Multiple steam accounts overwrite saves and schematics

### ISSUE THREAD

**Issue by Jammo2000** [Anuken/Mindustry#6786]
**Platform**: Windows 11 / Steam

**Build**: Steam Build 126.3

**Issue**:  If multiple steam accounts have the game on the same computer, their saves and schematics overwrite each other, and the overwritten saves will be synced with steam cloud. This is because saves and schematics are stored next to the executable in C:\Program Files (x86)\Steam\steamapps\common\Mindustry\. This directory is shared between user accounts (both steam users and windows users). 
This gets even more problematic if you have other computers that Steam syncs between.
Other games that don't have this issue store saves/data in %AppData%\\\<Game name\> or \<Steam-folder\>\\userdata\\\<user-id\>\\\<Numbers that I think are the game ID\>

[Relevant Steam docs](https://partner.steamgames.com/doc/features/cloud) (section heading "save file paths")

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Have 2 Windows user accounts, both of which have Steam set up with different Steam users
2. Play campaign as one user, than the other. Create a few saves and schematics
3. Observe that both users will have the same saves and schematics.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
I dont have any mods that impact saves, only time control and sandbox unit spawning

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
Issue does not happen in game. All the save files are valid, there's no corruption, just overwriting.

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I will not be changing this behavior.
