### ISSUE TITLE
Sharded reveals FoW for all teams

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6787]
**Platform**: Windows

**Build**: Custom (Erekir)

**Issue**: Sharded team reveals for all teams: 

https://user-images.githubusercontent.com/94794129/167313227-666e34c2-3cca-44b4-a877-41ed03cd9110.mp4

**Steps to reproduce**: 
Set player team to something that's not sharded and add a core of said team. 
Add some sharded turrets. Observe

**Save file**: 
[Bug-Report-Save.zip](https://github.com/Anuken/Mindustry/files/8647673/Bug-Report-Save.zip)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce issue in save or map form.

![image](https://user-images.githubusercontent.com/10100000/167315683-a566c4f2-5afd-4c12-96b4-a5454ba8dbf7.png)

**Comment by AtobaAzul** [comment]
Might've been related to something else that got fixed, regardless, nice.
