### ISSUE TITLE
Erekir "update" freeze

### ISSUE THREAD

**Issue by DUOsoul** [Anuken/Mindustry#6792]
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* "custom", or the erekir build

**Issue**: *Explain your issue in detail.* Game freezes upon trying to update

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* I played through the tutorial stage normally up until the 2nd time you build defenses on a time limit. I was abruptly given a pop-up notifying me of a newly released update. I clicked on it and started the download, and then the game froze. After restarting my PC and attempting to update again from the main menu, the game still froze the instant the download progress bar filled completely.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[saves.zip](https://github.com/Anuken/Mindustry/files/8648177/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* The game does not produce a crash log upon freezing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
>  I was abruptly given a pop-up notifying me of a newly released update. 

This is part of an unofficial client. I do not distribute any builds or updates for this branch.
