### ISSUE TITLE
can't playtest on built-in maps

### ISSUE THREAD

**Issue by JniTrRny** [Anuken/Mindustry#6794]
**Platform**: Win11

**Build**: Erekir

**Issue**: can't playtest on built-in map, see vid

**Steps to reproduce**: open editor on any built-in map, click playtest, boom.

**Link(s) to mod(s) used**: no

https://user-images.githubusercontent.com/85090668/167378597-0a22d3a1-7be9-4595-8a75-c5c71aae173b.mp4

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have ascended beyond the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I won't be changing this behavior; save the map as a custom one if you want to playtest it.
