### ISSUE TITLE
Rain severly drops fps

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry#6796]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Custom Erekir Build (cannot get *exact* build)

**Issue**: *Explain your issue in detail.*
Rain, just by simply existing, drops the fps to 1.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Create a world
2. Wait for it to rain
3. 

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
Happens ***literally everywhere.***

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Rain still runs at 1000+ FPS for me, not interested in testing on mobile as I can't even tell what build you have here.

**Comment by SMOLKEYS** [comment]
> Rain still runs at 1000+ FPS for me, not interested in testing on mobile as I can't even tell what build you have here.

I saw why the fps just dies: The rain intensity is set to maximum for some reason.
