### ISSUE TITLE
spawning with a Shard instead of a Bastion when launching from map4 to any uncaptured/abandoned sector

### ISSUE THREAD

**Issue by crazybim2** [Anuken/Mindustry#6797]
**Platform**: Windows 10

**Build**: Custom Erekir build

**Issue**: launching from map4 to any uncaptured or abandoned sector spawns a shard instead of a bastion

**Steps to reproduce**:
1. have copper and lead in map4 (launchpads)
2. launch from map4 to any uncaptured/abandoned sector
examples (below, below is map3):
![beta](https://user-images.githubusercontent.com/98325419/167427869-d80f1f66-f56a-43e5-9f46-5f402433538a.PNG)
![Capture8](https://user-images.githubusercontent.com/98325419/167427927-bbab7173-8408-41d4-933a-ed9fd3def2a1.PNG)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[erekir330912.zip](https://github.com/Anuken/Mindustry/files/8652352/erekir330912.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
