### ISSUE TITLE
Payload source unit output cannot be commanded?

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6798]
**Platform**: Windows

**Build**: Erekir 

**Issue**: I don't really know how to explain it with words.

https://user-images.githubusercontent.com/94794129/167443906-e9808409-441c-44c2-b692-5de95aab5e71.mp4

Intentional?

**Steps to reproduce**: Enable RTS control, attempt to control payload source.

**Save file**: 
[BugReportQuestionMark.zip](https://github.com/Anuken/Mindustry/files/8653073/BugReportQuestionMark.zip)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional.
