### ISSUE TITLE
Problems with World Processors

### ISSUE THREAD

**Issue by SpaceEarthEX** [Anuken/Mindustry#6799]
**Platform**: Windows 10

**Build**: Custom Erekir build

**Issue**: You can place Logic-related blocks on top of World Processors(?)

**Steps to reproduce**: There's only one step, place Logic-related blocks on top of World Processors.
(Video was too big so im sending a link)
https://cdn.discordapp.com/attachments/391020510269669378/973182173148479528/Mindustry_2022-05-09_18-17-24.mp4

**Link(s) to mod(s) used**: None

**Save file**: None

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
