### ISSUE TITLE
Double draw on surge tower beams.

### ISSUE THREAD

**Issue by SimonWoodburyForget** [Anuken/Mindustry#680]
If a surge tower is connected to another surge tower, and one of the tower goes off screen, a double beam sometimes occurs: http://i.imgur.com/bJNgymA.png, the power beam offset always occurs if the "point" is offset: http://i.imgur.com/XSc0ari.png 

System info:
- Mindustry v93 and v94.1
- Ubuntu 18.04

**Comment by ZkyLB** [comment]
pretty sure that's how it works.

**Comment by Norrica** [comment]
> pretty sure that's how it works.

Look closer. Beam and end point of the beam is not aligned as they should be.

**Comment by Remint32** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/13190430/65685324-5e9ccb80-e06a-11e9-8dda-26a41679c131.png)
