### ISSUE TITLE
jitpack doesn't work

### ISSUE THREAD

**Issue by liplum** [Anuken/Mindustry#6800]
When I tried to import mindustry v136 as a dependency in my repo using jitpack instead of a local jar, I got `Git error. Max repo size 500MB exceeded` on jitpack with the last commit package.
After researching, I got https://github.com/polarofficial/polar-ble-sdk/issues/243.
It may indicate that the history of Mindustry repo is too large, overthan 500MB -- maybe it's due to textures Idk.
Although this contribution is just a snapshot, but it's possible that we couldn't get the real v136 from release package on jitpack.
I think the jitpack.yml in Mindustry should be updated. For example, https://github.com/polarofficial/polar-ble-sdk/blob/master/jitpack.yml, which comes from that issue.

**Comment by Anuken** [comment]
I am aware of this, but 1) I think the error might change once I merge, and 2) this looks like something unrelated to actual repo size, because Mindustry is <100mb when cloned directly, but has been >1GB with its git folder for a very long time. It's not as simple as removing assets, I think.

**Comment by liplum** [comment]
1. The size is based on the full history of this repository.
2. I just guess every packing textures will add some new picture files, which might lead to be exhausted prematurely.
3. In that issue, it provides a way to tell jitpack to only access the latest commit. But too large repo is rare, I can't guarantee it works for Mindustry or for now.

**Comment by Anuken** [comment]
Unless the log is wrong, I don't think it could be based on the full repo history. Not only would that be very stupid from JITPack's end, but Mindustry's history is (as mentioned earlier) much larger than 500mb even in the master branch.

**Comment by liplum** [comment]
And now, I try to make a mirror of Mindustry for jitpack on [this repo](https://github.com/liplum/MindustryShadow) with [my tool] (https://github.com/liplum/MindustryShadowUtil). But I (the jitpack and CI) can't build it because of annotation processer while compiling.

**Comment by Phinner** [comment]
What about hosting your own maven repo Anuke ? You could make a very simple one with [Reposilite](https://github.com/dzikoysk/reposilite).

**Comment by Anuken** [comment]
Got it working by setting up a "mirror" repository. [Use this for builds now.](https://jitpack.io/#anuken/mindustryjitpack/935b478139)

example:
```gradle
compileOnly "com.github.Anuken.MindustryJitpack:core:935b478139"
```
The commit hash is obviously different, but you can still look them up or use the latest one.
