### ISSUE TITLE
infinite waves on sector 'Three'

### ISSUE THREAD

**Issue by crazybim2** [Anuken/Mindustry#6807]
**Platform**: Win10

**Build**: Custom Erekir

**Issue**: campaign sector 'Three' can become a custom game if you save and quit then reenter it

**Steps to reproduce**:
1. launch to 'Three' on campaign
2. save and quit
3. reenter 'Three'
![Capture](https://user-images.githubusercontent.com/98325419/167609317-2cda4d36-00d3-44be-8db2-342df7a257e8.PNG)
![beta](https://user-images.githubusercontent.com/98325419/167607866-91367dbd-d8f6-4edc-98dd-8857dd5a0093.PNG)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no

**Save file**: 
[erekir6807.zip](https://github.com/Anuken/Mindustry/files/8660716/erekir6807.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
