### ISSUE TITLE
Ship fabricator is building Meruis

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6809]
**Platform**:Windows

**Build**: Erekir

**Issue**: ![image](https://user-images.githubusercontent.com/94794129/167694227-535a4d53-7757-4ac2-a1c7-f1d1f2948263.png)

**Steps to reproduce**: Use a ship fabricator

**Save file**: 
[BugReport.zip](https://github.com/Anuken/Mindustry/files/8663947/BugReport.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works correctly for me, probably fixed already.
