### ISSUE TITLE
Rally beacon

### ISSUE THREAD

**Issue by dheld** [Anuken/Mindustry#681]
I get that mindustry is trying to avoid micro for units, and I appreciate that.  However, I find the current mech management to be difficult and tedious, in a not-fun way.  I think a few small tweaks can improve mech gameplay considerably.  First, let's review the current commands:

1. Attack.  As far as I know, this just causes all units to move towards the nearest enemy core, attacking everything on the way.  So far, so good.
2. Retreat.  From what I can tell, this causes ground mechs to flee to the core, and air mechs to flee to their home factory, and to avoid engaging any enemy units (presumably, because enemy units will ignore them if they aren't being shot at).
3. Patrol.  Not really sure what this does.  It appears to make ground mechs wander aimlessly around the core, engaging hostiles in range.  It looks like air mechs fly around their home factory, also engaging nearby hostiles.

I'm fine with Attack, but Retreat should be changed to be consistent between air and ground.  I think it should mean "defend the core at all costs", which means that it should be an attack-move towards the core for both air and ground units.

I would like to change the third command to "Rally".  This instructs ground mechs to attack-move to the nearest ground-rally point, and air mechs to attack-move to the nearest air-rally point, and to engage all hostiles which enter the rally point radius, but without chasing outside of it.

A Rally Point is just a 2x2 building like a Power Node, which consumes power to activate (say, 18/s or so, similar to Phase Conveyors).  There are two kinds of RPs: Ground RP and Air RP, which attract the respective classes of units, for the obvious reason that sometimes you want ground units to attack different targets than air units.  Each RP has a radius, similar to a Large Power Node, where mechs will try to gather.  A mech will consider itself "rallied" if it is inside the radius, causing it to rest.  However, it will attack-move towards any hostiles which enter the rally radius.

This would make mechs a lot more useful in Campaign by making it easy for players to stage their army off to the side of their main defense, but near the front lines.  Then, after a wave has passed, they can Attack without suiciding their army on a big wave.  I'm sure it would have a major impact on PvP as well, but hopefully players would agree that it's a good change.

If, for some reason, players still want a "do not attack" mode, there could be a fourth command: Stand Down.  This would work like Rally, except that mechs would not engage any hostiles in this mode.  I guess Stand Down could cause mechs to retreat to the core instead, but I'm not really sure when players would want this kind of behavior in the first place.

Rally Points would also make it feasible to use units to help defend new expansion areas before ammo lines and turrets are constructed.  Doing this with doors and walls is possible today for ground mechs, but very painful and pretty much not worth it.  Doing it for air mechs is outright impossible, unless you count building air mech factories where you want to expand and putting them on patrol.

Making the Rally Point consume power is both a reasonable cost for the feature, as well as a nice control system.  You can move your army around by enabling and disabling various RPs.  If no RPs are enabled, then units will treat their home factory as their personal RP for the purposes of the Rally command.

**Comment by Anuken** [comment]
While this *is* a good idea, please keep feature suggestions in #545.
