### ISSUE TITLE
Master Build Plan

### ISSUE THREAD

**Issue by dheld** [Anuken/Mindustry#682]
I understand that coding the AI to build on the map like a player is quite challenging to do well.  However, I think there is a nice shortcut we can take which improves the AI quite a lot without much complexity.  Basically, you fake it till you make it via a human-crafted Master Build Plan (MBP).  

Basically, the map creator defines a fully functional base, as if they played the map as the AI.  They define the placement of every building, as well as the *build order*.  The AI starts off in the same state as a player, and executes the commands in the MBP one-by-one.  You can now introduce a "difficulty" level, which is the maximum APM (actions per minute) you allow the AI, so that it can build as slowly as a noob or as quickly as an expert.

The AI won't respond to players dynamically, by shifting resources or units around the map, but at least it can build in an intelligent way, without having to solve combinatorial explosions of building placement and conveyor routing. 

When players attack and destroy infrastructure, the AI will need to go repair things, especially because the player may have denied it critical resources.  However, if you make the AI repair breaks as soon as they happen, it might be too powerful.  So instead, the default mode is to follow the MBP wherever it happens to be, and to periodically make a "repair pass" where it checks for buildings that should be present according to the MBP but which are missing because they got destroyed.  This could be triggered on a timer (like, once a minute) or whenever the AI is out of a critical resource (the MBP is blocked because it ran out of titanium, etc.).  If it can simply replace the building, it does.  If a human has blocked it, then it attacks the human at each location that is blocked, in MBP order.

This is where Rally Points synergize well.  They could be considered a hard pre-req to make this strategy work.  You want the AI to be able to marshal units towards an intrusion without having to build factories in a particular location just so units will run past an enemy mine slapped on its ore vein.

Now, just placing RPs could itself be difficult.  It could use simple heuristics like: "If we have Solar Panels, build enough to power this RP" so that it could place near the intrusion.  But really, it's also up to the map designer to make sure there are turrets covering every square inch of the base.  If the turret coverage is solid, then the AI should be able to deter most cheese building, forcing the player to really devastate the front lines.

The nice thing about a human-created MBP is that you can literally cover the entire map with a plan, so that it appears that the AI is intentionally building towards contested ore nodes, building defensive areas, and generally encroaching on the player all the way to their core.  It can also be iterated in complexity by adding optional branches.  For instance, there could be a "core plan" which builds up the economy and basic defense, and then "attack options" which cause it to grow towards one side of the map or another depending on which areas are free of enemy buildings/units.  This way, it wouldn't play the same way every time, even on the same map.

For beginner mode, the AI could stop expanding once it controls half the map, giving newbie players breathing room.  Intermediate levels could make expansion pushes in timed waves, and the most advanced would be relentless, building as fast as resources come in and factories can churn out products.

Also, the MBP would be a nice transition towards a "smarter" AI.  Instead of spelling out how to place every mine and factory, the map maker could say: "Create titanium mine here and route conveyor through these waypoints I have defined on the map.  Place Kiln cluster over here." and the AI could fill in the details and use build templates to make efficient layouts.  The AI could then be evolved in sophistication by layers, until it is able to play all aspects of the game by itself.

**Comment by Anuken** [comment]
See other comment; keep feature suggestions in #545.
