### ISSUE TITLE
God Mode bug.

### ISSUE THREAD

**Issue by Gradass** [Anuken/Mindustry#6820]
**Platform**: `Android 30`

**Build**: `pre-alpha build 135.2`

**Issue**: *God Mode bug in Multiplayer*

**Steps to reproduce**: *i don't know for sure the reason or what i did, but i'll explain anyway: i was playing mindustry multiplayer, i turned off my phone for around ten minutes and when i opened again i was Immortal, i wasn't disconnected because i could see people playing and everything was working. The game then ended and i Lost immortality*

**Link(s) to mod(s) used**: `[none]`

**Save file**: i don't have any save files of the thing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save file provided, can't really reproduce this.
