### ISSUE TITLE
Naval and some other pathfinding doesn't work if the pathfinding is initiated by logic proc.

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry#6830]
**Platform**: *Windows*

**Build**: *v135.2 [idk if the erekir "release" counts as latest version]*

**Issue**: *Pathfinding with logic doesn't work with naval and some other units to a lesser extent*

**Steps to reproduce**: *Load up map and wait [or in my testing force online] the naval factories at the top. They'll do all sorts of weird jank but strangely enough it works for Intervection, although he's on mobile. The novas down at the bottom of the base also suffer the same issue to a lesser extent.*

**Link(s) to mod(s) used**: *[Foos Client](https://github.com/mindustry-antigrief/mindustry-client)*

**Save file**: *[The Aviator.zip](https://github.com/Anuken/Mindustry/files/8673474/The.Aviator.zip) [Note that this version of the map was modified slightly to fix minor bugs on the map, the bug is still present in the version located in the map channel.]*

**(Crash) logs**: *Never gonna give you up~*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The pathfinding logic command was removed entirely.

**Comment by Bottinator22** [comment]
I presume the regular logic unit move now uses pathfinding since command mode uses pathfinding?

haven't tested

**Comment by Anuken** [comment]
No. The only change was its removal.
