### ISSUE TITLE
Maps won't import

### ISSUE THREAD

**Issue by Nipern1per** [Anuken/Mindustry#6835]
**Platform**: `Android 30`

**Build**: `release build 126.2`

**Issue**: most of the custom community maps won't import into the game no matter what I try

**Steps to reproduce**: when I went into the editor some of the maps I downloaded from the discord and the yt mindustry films channels when I taped to import it would say an error message where it would say "attempt to invoke virtual message void.

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You are not using the latest version. Those maps are for v7, which is not available on Google Play.
