### ISSUE TITLE
Reinforced Bridge Conduit

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry#6842]
**Platform**: Windows

**Build**: Custom Build. Which was built 9:03 a.m. on May 12th.

**Issue**: Reinforced bridge conduit is kinda broken.

Unlike serpulo's bridge conduit, the reinforced bridge conduit can be used single.
![RBC1](https://user-images.githubusercontent.com/57857764/167981346-b74429ef-7a6b-4b81-89b3-36e50aea4d0b.PNG)

The output bridge can receive input.
![RBC2](https://user-images.githubusercontent.com/57857764/167981555-a7c39762-2c2b-4f6a-9376-70aa92325e37.PNG)

The middle bridge does not receive input from the side which there is bridge input. (feature?)
![RBC3](https://user-images.githubusercontent.com/57857764/167981823-b490edc9-c71d-441c-95a1-e688683e6f44.PNG)

It can input the plated conduit from side. Any other non-conduit building cannot do this.
![RBC4](https://user-images.githubusercontent.com/57857764/167982140-6cc1e85c-62f8-45ba-9b07-0a2cf0a7a06a.PNG)

**Steps to reproduce**: Don't know if you can reproduce it. Try it in the editor?

**Link(s) to mod(s) used**:  No

**Save file**: NO

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The last two are not bugs, the top two are. Fixed. It is not equivalent to the old bridge.
