### ISSUE TITLE
Mods Won't Play Music

### ISSUE THREAD

**Issue by JinxCade** [Anuken/Mindustry#6867]
**Platform**: *Android*

**Build**: *bleeding-edge 22373*

**Issue**: *Songs Game1-9, launch, menu and editor songs from mods won't play*

**Steps to reproduce**: *Install A Mod With Songs In It And Restart*

**Link(s) to mod(s) used**: *[classic-music-master.zip](https://github.com/Anuken/Mindustry/files/8686419/classic-music-master.zip)*

**Save file**: *I Tested On 3 Fresh New Saves, Issue Still Occurs*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
Man really using a mod with min game version 105 and expecting it to work in 136
