### ISSUE TITLE
World cell default value on some slots having issues

### ISSUE THREAD

**Issue by Intervection** [Anuken/Mindustry#6871]
**Platform**: *Android*

**Build**: *Bleeding Edge 22549*

**Issue**: *When i was making unit logic with the world processors, i noticed that the world cell seems to have some of its slot having 1 as its default value and not 0. This is exclusively for sharded, the other teams worked fine.*

**Steps to reproduce**: *How the bug works 101

- Place this schem in malis team, the processor will spawn units in Citadel cores and without it, they will not spawn.

- Kill the Disrupt and when you do, a big explosion appears on its death dealing vast damage at a large area.

- Now, do the steps all over again but this time, the world processor schem is on the sharded team.

- Kill the Distrupt again but this time, you won't be able to experience a high damaging explosion.

The reason is because the death explosion wasn't triggered, the trigger is also linked to the world cell and it doesn't work if the default value of the world cell is 1 and not 0 unlike the other teams. I always thought that insides of the cells are all 0, but when i took a look at it in the world processor, it was 1. It happened in the 14th slot of the world cell which has 128 slots in total iirc.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *bXNjaAF4nAGfCWD2AAIAAwMABG5hbWUAHeKAolZhc3RsYW5kcyBQYXRyb2wgR3VhcmRz4oCiAAtkZXNjcmlwdGlvbgAAAAZsYWJlbHMABVvvm4JdAgAPd29ybGQtcHJvY2Vzc29yAAp3b3JsZC1jZWxsAAAABQAAAAAADgAAAiZ4nHVUS3LiMBB1piobn0IXSJU9QAg7V00lF5gsYClsAZ4Ii+gDeJZz8mmpW5YSEijk9tPrj163uCuK+39GDEZpZgU/ssYeegMr2OUfdzyxGePywkfDrmzHpRGlEVZzK1hd7oRtD6xVWvxSbrCZFUJVrGnVcBaj0hjqJxPvjsuMV6Voi6rcCyv74Y21QkrY0oJ3TPOhe5F8j2BdYaS6ZoOyzyHaxKhKdQpvCVrFD9uWF91Dnpt4UABzQ29fx5NgzbsDGDObE78MoiNiTUdY0hniLuH1MsrkD4exvPXQ9pZ3QvrSeAfBSCi/1h48qo/gpE2mLi5BUyQlXal1U9LAbCyYVNciCfVNZVmINflfc3BD4FiGMyexkseGrSqs73VeGsutMzgsTJ2F7nR/FrCTunHLaaVq3z5xoDFJZeze1z1ZpTM2vjo2OGii2/YwCrHaeCJ8hAlAbrMDm0Z9FpubSHFeKNVTSpWRqtJBR6xWku1yJ7gC4YsDJQxoZddY/CzHNojNafAOSkXaIoOI9ZhBiCzpqoizkqB0wJ7y+L/7vwSvog5Q4l5ECcJL3PFQcKBNA3YcX28nQgqO6swfo36htjDfxm2nwuJzTrd4vvz830JpvnDwV8XJm50HTNIP/ree4K1HW+Vvo9l8RH2UwKUFD+fRwA1LRH3x16lv3iGiY+ocOKT2H2GYwWWkvk+45Xrv5xlbS+1EmTyvKIq74t53qAbzx3+Q2ujLAAAAAAABDgAAAHB4nGNkYGDoS08tycnMy1ZITs3JUTDgKkpNTFEoycxNhQlkleYWKJgopAMlSlKLQjIS8yDSBlzFqSVgJoh2ADG48gsUikuTIPJgEZg8SCYls0wBLqZgaGBgwFVelFmSimIb0EWMDKwgjiGICQDPUzJuAAEAAAACAAAAAAEAAA4AAAIqeJx1VNty2jAQdTqTF3+FfiAzdoAQ3jzTaX+geYBHYQtwIyyiC+A+97/TlXZlKSGFQV4fnb3o7Iq7orj/a8RglGZW8CNr7KE3sIJd/nbHE5sxLi98NOzKdlwaURphNbeC1eVO2PbAWqXFd+UGm1khVMWaVg1nMSqNoR6ZeHNcZrwqRVtU5V5Y2Q+vrBVSwpYWvGOaD91PyfcI1o8Yqa7ZoOyPEG1iVKU6hbcEreKHbcuL7iHPTTwogLmhty/jSbDmzQGMmc2JXwbREXFGR1jSGeJuTQUto0z+cBjLWw9tb3knpC+NdxCMhPJr7cGj+ghO2mTq4hI0RVLSlVo3JQ3MxoJJdS2SUP+pLAuxJv9rDm4IHMtw5iRW8tiwVYX1vcxLY7l1BoeFqbPQne7PAnZSN245rVTt6ycONCapjN37uierdMbGV8cGB0102x5GIVYbT4SPMAHIbXZg06jPYnMTKc4LpXpOqTJSVTroiNVKsl3uBFcgfHGghAGt7BqLn+XYBrE5Dd5BqUhbZBCxnjIIkSVdFXFWEpQO2HMe/1f/h+BV1AFK3IsoQXiJOx4KDrRpwI7j6+1ESMFRnflT1C/UFubbuO1UWHzW84oclp//XCjPVx7+sjh5s/WAafrB/9YTvPVoq/x9NJuPqI8SuLTg8TwauGGJqC//OnXOO0R0TL0DhzQARxhncBmp8xNuud77icbmUkNRKM8riuKuuPc9qt/fi2//AEx26zUAAAABAAEOAAAEQniclVfNcts2EJYPvfCQZ8ALNBVtKbZuGrd2eunF8YE8QiQksYZIBgQtMS+fLLD4WVpUZmTPwOTu9y0W+0f4Zjb79Fcn6q5RTAt+YGu9rzpY4Tn5vz+07I5xeeRDx05sy2Unkk5oxbVgabIVutizolHi76avNXmypuZsXTT1uxgahaZumfjec0lw82QntKzqN1YIKeHVG7+bzxMleMkUr8tnyXcISNFQmrK60U/WWADMk6a1b1G08j9skxxVBXY/moP9WF9X+nVoBVuXVaf6VuPOXcuPtSgReetOcO+O4JXeoXsfJXM2NGae/iwqzUshjWu8BFsuTmZNjfDQjIUhNCS4uNiQIiiG1WUubGqRaw2Pzq9lDNQFz4iJzPFPVJg74ZDYM8doRUbOVnP073WZdJrrvsNaYc27UKWq3gVoYjbOMYVsircPGMhMjDJmbzIlq3jEtXGO1b2USb+poBK8s/5A+McWAGLXW3j2WnFqZdP9Y7oAlQd++ldwqfeuFRY++9GMLyjnzEN0hoDmSQ8p06qRbEtJ0CL2FwuuFFzvHyXvtKvOhXesNGrnk3nGzRa+nwgxPVeVrm9NtfWSbWRzfOFlBfHvqh+CLRI8dtXUxrgUqiqwJzK75pQRI6RVL3AJU2HsB2bs8plwB3eoE5XmXjqEtO2bJoLxbaTLR7p8pBupqjpkWzVQhfbUqPfvgWyi47nw7E6EftvD3BFRjqKFr1T02MqWVOZwX6gMRfd+RHm/rPTBA403VrJKesVLDuVai8PAuNa8eBOK8XpgoWChqlIEJD30lhmpm76SJZyf6V4pyJZNHsyCtgUyyDKz5F7r0ed0qNVCm88F5YMwM0se1JcN7MAvGPIfTYA4M0tOAJeNbO0uw9gECDOz5EF92UAHer4TYwMgzMySB/Xv4tDy6iwMrQlDm3vtZfoGEic+HgCEmVnyoA4GfNXyehfK0r6E6WWynbmqiB1l33MvHswYKKt3VguuXqwttJh+XsYhdazgFlCPLOaEgeonOtYcI5aRIsjXCSQpGIJ8mUDGuqDIrxPImH6KfJ5AxjxT5LdJP0NGqZ+incDG7FHsIyDtUIZrCA5lzIVJPCruvcL1Hk5U/IDPF+CnGcn4UfEBjeSH1JF9443YXybYL5R959ix50b8hwn+V8pfOr5vOMpO5xPsZ8oO1ynXbSP27QT7G2Wvwsltr43IU2EzWYv0lQ+cbzXCX03t/UjJywnAf/FLa++hBw61A5eI9gj3TyLMrXCPQtOMFmiX27Oi8rocrs9+G1J6B7g+EQxeJ4JWcwUX7NbNC3/bEHV5DsGiTB3EpX8qDE8kDGm8+Pp/D4Jh3raq4XCHHY8RbI0LbpABEkZH8OY3ezl2HCphnFzBjoMmjJgr2HH4hLFzBTsOpDCKrjq3H1JkPF3Bj4MrjCxaRVUphS8ekM9ms5vZH+Yukv78Obv5Bcd4AZkAFbSPnA==

This is the world processor schem that i was making and encountering the bug from it.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
World cells are identical to standard cells in terms of behavior; it is extremely likely that the bug is in your code (or, at least, somewhere else in the game). There is nothing that could set world cell contents to 1 instead of 0 at startup. I will not debug logic unless you can show me the exact Mindustry code that is wrong.
