### ISSUE TITLE
`config` of payload is bugged

### ISSUE THREAD

**Issue by Why-not-now** [Anuken/Mindustry#6874]
**Platform**: windows

**Build**: pre-alpha build 135.2.

**Issue**: changing `config` of the payload router makes it such that the direction of the payload is sent is only 1 direction and instead of spreading it nor in the configuration that is set

**Steps to reproduce**: 
1: create a payload with 2 conveyors for it to go to
2: put a processor to control `config` of payload router

**Save file**: [payload router bug.zip](https://github.com/Anuken/Mindustry/files/8692307/payload.router.bug.zip) (location: 305, 436)

**Schematic**: ```bXNjaAF4nGNgZ+BjZmDJS8xNZWBJKk23Z+BOSS1OLsosKMnMz2NgYGDLSUxKzSlmYIqOZWXgK0iszMlPTNEtzi8tSk5lEIDxk/PzylIr84sQKoryS0tSixj4czOTi/J1C4ryk1OLi4EK2IrLM0uSM4AmszMwMDEwsbIxMDEyAllsDIxALgMnAwOIx8MAFGQF8ZiBFBsfUH1TxZzSc4Z8hwx4WAPE27zsWv0bbjVu2lQwYYIUBxenxbYqjnM9CkKJLvU/fl2SrmNnOH9oZYriw6TAlTqOf1OX2KqX99g8vppXfisokDOOn7/4o3toz8XnSyYpX7VrNfY0S5XM/MEmLj6l7azJ2wmX//ib9389x/WrbGEf3y+3e/oR9QyHT5hdY2QBOoadi4ERAFLCYds=```

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
Based on what you've said, you've just described a feature... I don't see how this is a bug. https://github.com/Anuken/Mindustry/blob/c24c5c6196cd89bdc17a079a2a8acd372cc260d9/core/src/mindustry/world/blocks/distribution/PayloadRouter.java#L59-L63
