### ISSUE TITLE
Units "elude" will slam into doors and explode

### ISSUE THREAD

**Issue by LTHPKBTE** [Anuken/Mindustry#6882]
**Platform**: *Android*

**Build**: *7-bleeding-edge-22552*

**Issue**: *When many units pass through an automatic door at the same time, it is possible for a unit to hit the door and explode.*

**Steps to reproduce**: *Placing three doors together and having units pass through it at an angle can trigger this issue.*

**Save file**: [Sharepoint](https://82pmlj-my.sharepoint.com/:u:/g/personal/java8ver64_82pmlj_onmicrosoft_com/EdlCwCyTvxVIho_Q04SP42EBzRk0KxHJ94T5JvV3yo_9fw?e=cYZu9c)

**Screen record**: [Sharepoint](https://82pmlj-my.sharepoint.com/:v:/g/personal/java8ver64_82pmlj_onmicrosoft_com/EeehlwaaxvJDiFrG2cEvotgBpcsPszgzVieHoEzYO-blVQ?e=Q2NT97) 
Video recorded on Erekir Planet's Two block.

*I'm sorry but I can't upload files to github because of firewall.*

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Tried for several minutes to get this to happen as shown in the video, but nothing happened. I can increase the detection margin slightly, but the code *looks* correct and I don't see any obvious cause. Unlikely to be fixed.
