### ISSUE TITLE
Wave Spawn Location does not support enemy cores

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#6886]
**Platform**: Windows

**Build**: 22555

**Issue**: In the wave menu, you can define where a unit will spawn. However, it does not support cores, which also spawn wave enemies.
Intentional?

![image](https://user-images.githubusercontent.com/94794129/168486786-1786728f-7440-4409-8101-a95fd818d33a.png)

**Steps to reproduce**: Place enemy cores, enable attack mode, try to change the spawn location.

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 00001H** [comment]
Place "enemy spawn" as ground block in level editor

**Comment by 00001H** [comment]
enemy cores don't default as enemy spawn unless explicitly indicated with an "enemy spawn" ground block

**Comment by Anuken** [comment]
Intentional. Cores are not actual spawn positions, the unit creation point is calculated dynamically and thus is not applicable to that menu.
