### ISSUE TITLE
Game progress corruption (Steam version)

### ISSUE THREAD

**Issue by Abelardo0503** [Anuken/Mindustry#6900]
**Platform**: `Windows 8.1 x64`

**Build**: `steam build 126.3`

**Issue**: *The game bugged me and now all my progress is a kind of mix between moderately advanced worlds with first level technologies, luckily all the blocks I placed are still there, but I can't do practically anything due to my lack of technologies. The maps and templates I created (and the ones from the workshop) are intact. (If I write wrong it's because of the translator :P)*
![20220517181637_1](https://user-images.githubusercontent.com/87998594/168933605-7dbad0cf-00c3-4cdd-a28e-b9ee2101582d.jpg)
![20220517185919_1](https://user-images.githubusercontent.com/87998594/168933619-8e5b7e34-0853-4de1-aba6-65461f9df1d7.jpg)

**Steps to reproduce**: *This happened while I was attacking this enemy base (the one highlighted in red) and my computer suddenly shut down (it was accidentally disconnected), and when I turned it back on and entered the game, everything went like this, by the way, when I entered the mode campaign, the map was positioned in the impact zone.*
![20220517181603_1](https://user-images.githubusercontent.com/87998594/168933587-6401dc5e-81fd-4194-a3e1-1c60c8a1cbe2.jpg)

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[saves.zip](https://github.com/Anuken/Mindustry/files/8712390/saves.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash. I can't find any file called "crash report file"*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GaviTSRA** [comment]
Happened to me too (on the itch.io version 126.2)

**Comment by buthed010203** [comment]
If your computer powered off while the game was saving, that's probably why its so cursed. V7 has extra redundancy for stuff like this already

**Comment by Abelardo0503** [comment]
After overcoming all the waves and re-investigating everything... well, it seems to be normal, although the areas I lost are still half bugged, they appear empty when I enter, but as if I were invading them even though I haven't, and if I was building something at the moment of losing it, when I re-enter I appear building it while the core falls.

But otherwise, everything is normal, I think I'll close it, if it happens again, I think I'll wait for them to update the version of Steam where the error has been fixed.
