### ISSUE TITLE
Updating causes game crash after restart

### ISSUE THREAD

**Issue by robtech21** [Anuken/Mindustry#6903]
**Platform**: Windows

**Build**: BE 22556
**Issue**: Trying to update the game to a new BE version causes

**Steps to reproduce**: Either let it automatically detect or click `Check for Updates` and then let it download and restart. The game will lock up.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: 
[bugsave.zip](https://github.com/Anuken/Mindustry/files/8717066/bugsave.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crashlog.txt](https://github.com/Anuken/Mindustry/files/8717103/crashlog.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no crash log in that file, and frankly I don't care about the BE update system much. If it works, great, if it doesn't, wait until official release.
