### ISSUE TITLE
Other types of parts in mindustry.entities.part (except RegionPart) cannot be used in JSON

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry#6912]
**Platform**: *Android/iOS/Mac/Windows/Linux*
All (tried on: Android)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
22556 (Snake#2132)
to
22560 (SMOLKEYS#4156)

**Issue**: *Explain your issue in detail.*
Other types of parts in `mindustry.entities.part` (except RegionPart) cannot be used in JSON.

If attempted to do so, an error gets thrown saying that `<part type>` cannot be casted to `RegionPart`.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Create a block/unit that has a field that accepts draw parts in JSON
2. Use any part type (eg. `FlarePart`, `ShapePart`, etc)
3. 
---
https://cdn.discordapp.com/attachments/653293028869537843/977164632210939924/Screenshot_2022-05-20-19-01-16-520_io.anuke.mindustry.be.jpg

https://discord.com/channels/391020510269669376/653293028869537843/977164632840077322

---

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Happens right at client load.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] ? **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Was fixed
