### ISSUE TITLE
Calling Vars.state.set(GameState.State.paused) does nothing in server

### ISSUE THREAD

**Issue by mmis1000** [Anuken/Mindustry#692]
It looks like the `isPaused()` check hardcoded in the server to be always playing.

Instead of only makes those should be always executed execute in server.

So, using plugin to pause it does not work at all.

https://github.com/mmis1000/Mindustry-GameCTL/blob/fa048f758e3c180d925a94696cc3b4809446a0d4/src/main/java/me/mmis1000/mindustryGameCTL/Main.java#L44-L51

I personally tweak the Logic.java to makes it works as is in server, but I feel it is not the right way to do so.

https://github.com/mmis1000/Mindustry/blob/aea3279e1837d0db9d40b65083adca7b260a3dcc/core/src/io/anuke/mindustry/core/Logic.java#L179-L232

**Comment by Anuken** [comment]
The server doesn't support pausing, so it does nothing. This is intentional.

**Comment by Anuken** [comment]
Either way, I'm not interested in implementing pausing for the server, as it serves no purpose for the vanilla game, and could lead to many bugs. If you want to submit a well-tested pull request with a correct implementation, you are free to do so.
