### ISSUE TITLE
Multiplying Resources

### ISSUE THREAD

**Issue by VVhale-1** [Anuken/Mindustry#6920]
**Platform**:Mac/Windows

**Build**: 22563 BE

**Issue**:In pvp for some reason a while after getting a new resource into the core it multiplies either to be the max amount or it gets bigger by a few thousands

**Steps to reproduce**:enter pvp with someone and get a new resource into the core, then wait for the resource value to jump up

**Save file**:[Game_Erekir.zip](https://github.com/Anuken/Mindustry/files/8749248/Game_Erekir.zip)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce any issues on my end.
