### ISSUE TITLE
Game freezes when updating from BE 22563 to BE 22564

### ISSUE THREAD

**Issue by Falling10fruit** [Anuken/Mindustry#6923]
**Platform**: *Windows* 

**Build**: *BE 22563*

**Issue**: *Updating to BE 22563 crashes the game*

**Steps to reproduce**: *A pop-up appeared and I let it download the update automatically.*

**Link(s) to mod(s) used**: *No mods are activated and they were for V6 anyway*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.* I was not playing anything, I was trying to let the pop up update automatically

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* No crashes, it just froze

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.** This is an BE version, I am trying to automatically update
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DkurowithA** [comment]
yeah this has been happening for me for awhile, it only happens when it is in Fullscreen for some reason.

**Comment by Falling10fruit** [comment]
Also, it seems like there are no changes when comparing the two versions on GitHub, so I ignore them most of the time.

**Comment by Anuken** [comment]
Same response as https://github.com/Anuken/Mindustry/issues/6903#issuecomment-1149945266
