### ISSUE TITLE
Can't sensor sand using processor

### ISSUE THREAD

**Issue by MrRichPoor** [Anuken/Mindustry#6926]
**Platform**: *Android/Windows*

**Build**: *build 22566 BE*

**Issue**: *sensoring sand results to null.*

**Steps to reproduce**: *
     1.place a processor, message and container with sand
     2.link the processor to container and message
     3.import this code
     sensor Sand container1 @sand
     print Sand
     printflush message1
.*

**Link(s) to mod(s) used**: *no mods.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[Sand Bug.zip](https://github.com/Anuken/Mindustry/files/8752004/Sand.Bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
This also happens when, with units, trying to take sand out of containers or detecting how much sand you have

**Comment by Error-In-Code** [comment]
PR #6910 fixes this

**Comment by buthed010203** [comment]
Also included in [my patched fork](https://github.com/mindustry-antigrief/mindustry-client/tree/erekir-patches)
