### ISSUE TITLE
Cannot play campaign after running out of launched copper.

### ISSUE THREAD

**Issue by TheJSHuA** [Anuken/Mindustry#693]
After you spend enough copper researching things, you can no longer launch ground zero or any other levels, meaning you can no longer play campaign. I'm running Android 9.0 for anyone wondering. Have not tried to reproduce on anything but mobile yet and this is on build 94.

**Comment by Quezler** [comment]
if you happen to have reached lv 15 on ground zero you might be able to adjust the copper requirement down 🤔

**Comment by Anuken** [comment]
![Screenshot from 2019-09-22 10-58-01](https://user-images.githubusercontent.com/10100000/65389825-e495db00-dd27-11e9-8807-74d4fbd3d9f1.png)

I can launch just fine with 0 copper and an unedited loadout.

**Comment by TheJSHuA** [comment]
I haven't unlocked loadout configuration on Ground Zero yet (this is a new file I'm on), but they might be from an old version. 
![image](https://user-images.githubusercontent.com/22226164/65391755-71459680-dd32-11e9-8935-c405c9991c29.png)

**Comment by Anuken** [comment]
Yes, you're using the loadouts from an old version, which cost 100 copper.

There's currently no simple way to detect this, as it appears like any other layout. I recommend exporting your data, clearing it, then importing any important things like maps or saves.
