### ISSUE TITLE
I cant enter the first level to the 3rd planet

### ISSUE THREAD

**Issue by Deathwisher1** [Anuken/Mindustry#6937]
**Platform**: `Android 31`

**Build**: `release build 126.2`

**Issue**: *Explain your issue in detail.*

I did nothing but get the mod but it says there's a bug

**Link(s) to mod(s) used**: `[QByte, Superman/adamantium-mod:2.0, z0mbiesrock/diamond-ore:[#9cb6f4]2.6.0[], sisit135 + passive engineer/extendedgroundunit:1.0.0, The Slaylord/goldmod:2.0 alpha b19, Darknes Tech Mods inc./gun-mod:2.3.2.1, 滞人/invincible-cheat-mod-v6:2.8.4, Developer:
    Fresh791
    
    
Contributers:
    Many, many people! Check Discord for more information!/me:1.09, choobyshroom/moreuints:1.0, [Error_in_Code]/nuclear-mines:0.1, amione#0663/opore-mod:69, Shimyytrov Modding Team/turret-expansion:0.0.2 Beta, lev43/turretsmod:3, NeutrO_/unit-turrets:0.5]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
This is a mod issue, not an issue with the game itself...

**Comment by end-me-please** [comment]
1. *not* the latest game version
2. this problem is definitely caused by a mod. Without any logs we can’t even tell you which mod to blame.

> Crash report: The contents of relevant crash report files. REQUIRED if you are reporting a crash.
