### ISSUE TITLE
Chinese translation for steam introduction 

### ISSUE THREAD

**Issue by laohuaji233** [Anuken/Mindustry#694]
An open-ended tower-defense game with a focus on resource management.
一款以资源管理为核心的无尽塔防游戏。

Create elaborate supply chains of conveyor belts to feed ammo into your turrets, produce materials to use for building, and defend your structures from waves of enemies. Play with your friends in cross-platform multiplayer co-op games, or challenge them in team-based PvP matches
建造精密的传送带供应链，提供炮塔弹药，生产建筑材料，保护你的建筑并抵御敌人。在跨平台多人合作游戏中与朋友一起玩，或在基于团队的PVP比赛中向他们挑战。

Gameplay
Create drills and conveyors to move resources into your Core. 
Use production blocks to create advanced materials.
Build drones for automatically mining resources, assisting in building and protecting your base.
Distribute liquids and fight outbreaks of fire.
Boost production by supplying optional coolant and lubricant to your defense and production blocks.
游戏操作
建造钻头和传送带来将资源转移到核心
建造无人机以自动采矿，协助建造和保卫核心
分配液体并扑灭突发火灾
用特定物品冷却炮塔和提高生产

Campaign
Advance through 12 replayable built-in zones with randomized spawn points
Collect and launch resources
Research new blocks to fuel progress
Configure launch loadouts to bring resources to each zone
Variety of mission objectives and goals
Invite your friends to complete missions together
120+ technology blocks to master
19 different types of drones, mechs and ships
50+ achievements to complete
战役模式
在12张可重复游玩的内建区域中前进
收集并发射资源
研究科技以进步
携带资源进入每个区域
多样的任务与目标
研究120+科技
19种不同类型的无人机、机甲及飞船
达成50+成就

Gamemodes
Survival: Build turrets to defend from enemies in tower-defense based gameplay. Survive as long as possible, optionally launching your core to use your collected resources for research. Prepare your base for intermittent attacks from airborne bosses.
Attack: Build factories for units to destroy the enemy cores, while simultaneously defending your base from waves of enemy units. Create a variety of different types of support and offensive unit to assist you in your goals.
PvP: Compete with other players on up to 4 different teams to destroy each other's cores. Create units, or attack other bases directly with your mechs.
Sandbox: Play around with infinite resources and no enemy threat. Use sandbox-specific item and liquid source blocks to test out designs, and spawn in enemies on request.
游戏模式
生存：建造炮塔来防御敌人。尽可能长的生存下来，发射你的核心来使用你收集的资源进行研究。为Boss的到来做好准备。
攻击：为建造工厂生产机甲来摧毁敌人的核心，同时保护你的基地，抵御敌人的攻击。创建各种不同类型的支援和进攻单位，以协助你实现目标。
PVP：与最多4个不同团队的其他玩家互相伤害。创建单位，或者直接用你的飞船攻击他人基地。
沙盒：无限的资源，没有敌人的威胁。使用只限于沙盒的物品源和液体源来测试设计，和根据需要生成敌人。

Custom Games & Cross-Platform Multiplayer
12 built in maps for custom games, in addition to campaign
Play Co-op, PvP or sandbox
Join a public dedicated server, or invite friends to your own private session
Customizable game rules: Change block costs, enemy stats, starting items, wave timing and more
Mix&match gamemodes: Combine PvP and PvE gamemodes together
自定义游戏和跨平台多人游戏
用于自定义的12个内置地图
游玩合作，PvP或沙盒模式
加入公共专用服务器，或邀请朋友参加您自己的私人服务器
可定制的游戏规则
混合和匹配游戏模式：结合PvP和PvE游戏模式

Custom Map Editor
Paint terrain with an editor UI
Edit and preview structures in-game
Configurable tool modes: Change how each tool functions
Powerful map generation system, with many different types of filters for procedural manipulation of terrain
Apply noise, distortion, smoothing, erosion, symmetry, ore generation and random terrain to your maps
Randomize and configure ore generation, as well as placement of river and resource tiles
Configure enemy wave layouts
Share exported maps on the Steam Workshop
Customize base map rules
Use 75+ different environmental blocks
自定义地图编辑器
使用编辑器绘制地图
在游戏中编辑和预览
可更改的工具模式
具有多种不同类型的地形处理过滤器的强大的地图生成系统
将随机地形应用于地图
随机配置和生成矿石，以及放置河流和资源
配置敌方波次布局
在Steam创意工坊上共享导出的地图
自定义地图的基础规则
使用75+个不同的环境块

**Comment by Anuken** [comment]
Is this traditional or simplified Chinese? Steam requires me to specify.

**Comment by laohuaji233** [comment]
this is simplified Chinese

**Comment by Anuken** [comment]
Published, thanks.
