### ISSUE TITLE
Scrollwheel not zooming even with no conflicting bindings.

### ISSUE THREAD

**Issue by Rartrin** [Anuken/Mindustry#6941]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**:
I have rotate bound to V/B. Nothing should be conflicting with the scrollwheel being able to zoom, however, scrolling with a rotatable block selected does not zoom.
As a side note, I am aware of the zoom key override, however that would only make sense to apply in cases where there is a conflict. In this case, there is no conflict.

**Steps to reproduce**: 
Rebind rotate to other keys/buttons.
Select a rotatable block.
Observe that the scrollwheel does not zoom despite the lack of conflicting bindings.

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Have you tried it in the latest version (135)?

**Comment by Rartrin** [comment]
Yep, exact same behavior.
