### ISSUE TITLE
Bug Prosesador 

### ISSUE THREAD

**Issue by evildoor13** [Anuken/Mindustry#6948]
Platform: Android 

Latest version available in the store 

Bug summary: 

When I program units to take items, They do nothing, But if I use the same code but from a microprosesator Of those saved in templates If it works 

Code:
ubind @mono
ulocate building core false  coreX coreY found core
ucontrol approach coreX coreY 5 0 0
ucontrol boost 1 
ucontrol itemTake core @lead 9999 0 0
ucontrol itemDrop core 9999 9999 0 0

That code works only if I use the prosesser of a template

But if I write the same code in a new prosessator it doesn't work.

ItemTake y itemDrop Work only on objects connected to the processor but do not work on the core

Photo of the poly doing nothing 

![Screenshot_2022-05-30-05-22-57-640_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/84751150/170972947-21e02484-6915-4af1-a11c-f0f1ea694b5a.jpg)

Photo of the mono doing everything correctly 

![Screenshot_2022-05-30-05-22-38-506_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/84751150/170973105-31f10c61-a12c-42f4-9df2-3cfaad2c974d.jpg)

It is the same code just change the unit {poly} but it is written in a newly placed prosesator

**Comment by Anuken** [comment]
"Latest" is not a version, no save provided, and I do not debug logic programs unless you specify *exactly* what the game is doing wrong.
