### ISSUE TITLE
Release Build

### ISSUE THREAD

**Issue by RitBulb** [Anuken/Mindustry#6950]
PLATFORM: ANIDROID

BUILD:126.6

ISSUE: I'm stuck I'm version 126.6 how do I get to the latest.

STEPS RO REPRODUCE: so one day (past) Im full on storage and I sadly had to uninstall mindustry so a couple of months later I redownload mindustry (present) after I redownload I go to the mods section to redownload my old mods and so I do. During that I realized that release Build isn't as high as it used to be so I can't download two of my old mods :( I was confused on why my release Build was lower than usual. So that's when I came up with a theory. The theory was that release Builds get lower as more update are released. But as you guessed it that is incorrect. So how do I fix this?

**Link(s) to mod(s) used**:  1. Hackustry 2. Mindustry Extended 3. Dimension Shard

Save file: idk how access these 🤷

**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RitBulb** [comment]
#6950 nice

**Comment by end-me-please** [comment]
126.2 is the latest version in the play store. 
download the pre-alpha from itch.io

~~try asking in #help on discord before writing a bug report~~

**Comment by laok233** [comment]
Now u can close the issue
