### ISSUE TITLE
CPU/GPU utilization on heavy loaded maps.

### ISSUE THREAD

**Issue by tatzio** [Anuken/Mindustry#6972]
**Platform**: *Windows*

**Build**: *Mindustry-BE-Desktop-22570*

**Issue**: 
Probably not a bug but I did not get any reply on Discord. I was testing when my komp. will start dropping frames while adding Conveyors all over the map.
Finally the frames started dropping below 60fps.
When I checked CPU and GPU load:
CPU: 25%
GPU: 15%

Is this JAVA thing that the game can not utilize more CPU/GPU?

```
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / Quadro M1000M/PCIe/SSE2
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.3
[I] [RAM] Available: 3.9 GB
[I] Total time to load: 4022ms
```

***Steps to reproduce**: *Place multiple objects until FPS drop.*

**Link(s) to mod(s) used**: *N\A*

**Save file**: *N\A*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *N\A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by deltanedas** [comment]
if you have 4 threads then 25% is full usage

**Comment by buthed010203** [comment]
Just use more cores 4head

**Comment by tatzio** [comment]
![image](https://user-images.githubusercontent.com/106803609/172035424-c1dc7da3-9626-4440-ab8a-43b09f62a1d9.png)

**Comment by buthed010203** [comment]
Mindustry is largely single threaded so it can only really take advantage of a single core, I'm curious if you would get better results with [this jar](https://github.com/mindustry-antigrief/mindustry-client/releases/download/v8.0.0/erekir-patched-optimized.jar) which has rendering that should be significantly faster thanks to @zxtej

**Comment by tatzio** [comment]
Yes, the difference is noticeable for sure, but still very little use of GPU...

![image](https://user-images.githubusercontent.com/106803609/172057968-ab2e2ed4-a215-4430-893e-d1ba70de0739.png)

**Comment by buthed010203** [comment]
That would be because the game is cpu bound.

**Comment by buthed010203** [comment]
> Скинь пж ссылку на другое зеркало https://github.com/mindustry-antigrief/mindustry-client/releases/download/v8.0.0/erekir-patched-optimized.jar я про это<

This is an issue from years ago, there's no longer a need for that jar as the changes have been included in vanilla for ages

**Comment by nikitaetsa** [comment]
> > Скинь пж ссылку на другое зеркало https://github.com/mindustry-antigrief/mindustry-client/releases/download/v8.0.0/erekir-patched-optimized.jar я про это<
> 
> Это проблема многолетней давности, в этом jar больше нет необходимости, поскольку изменения были включены в vanilla целую вечность
Есть возможность или мод какой, чтобы юзалось больше ядер у проца ?

**Comment by nikitaetsa** [comment]
> > > Скинь пж ссылку на другое зеркало https://github.com/mindustry-antigrief/mindustry-client/releases/download/v8.0.0/erekir-patched-optimized.jar я про это<
> > 
> > 
> > Это проблема многолетней давности, в этом jar больше нет необходимости, поскольку изменения были включены в vanilla целую вечность Есть возможность или мод какой, чтобы юзалось больше ядер у проца ?

ПРосто я выживаю на карте где очень много построек сама карт огромная , и фпс 40-50 проц 12400 , т.е напр в майнкрафт такая же проблема примерно связанная с использованием игрой не всех ядер процессора . Но вот в майнкрафте есть мод которые перебрасывает часть нагрузки процессора на видеокарту . Есть ли возможность подумать примерно о таком улучшении?
