### ISSUE TITLE
Phase conveyor order of operation

### ISSUE THREAD

**Issue by cosmo5001** [Anuken/Mindustry#6973]
**Platform**: `Windows 10 x64`

**Build**: `pre-alpha build 135.2`

**Issue**: Phase conveyors don't output items in the same order they received them

**Steps to reproduce**: place a plastanium belt with multiple item types feeding into it and feed that into a phase conveyor and feed the phase conveyor into another plastanium belt

**Link(s) to mod(s) used**: `none`

**Save file**: 
[save.zip](https://github.com/Anuken/Mindustry/files/8837308/save.zip)

**Crash report**: `none`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They aren't supposed to.
