### ISSUE TITLE
Migration from v125 to v126 caused to reset most of the sectors because they're "corrupted"

### ISSUE THREAD

**Issue by TheAirBlow** [Anuken/Mindustry#6975]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *v136*

**Issue**: *I got most of my sectors reset when I was trying to access them with a mod that I widely used. I reset ~5 sectors until I realized what I've done. It is not the best way to handle unknown items/blocks... I lost a a week of progress because of this.*

**Steps to reproduce**: *Capture a sector, use a lot of modded stuff. Then disable them and try to join, "Save file corrupted", fuck yeah!*

**Link(s) to mod(s) used**: *Irrelevant.*

**Save file**: *Irrelevant.*

**(Crash) logs**: *Irrelevant.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheAirBlow** [comment]
Nah, it seems that it resets ALL sectors, even if you get the mods back and try to join to another sector that was not reset.
Migration from v135 to v136... gone wrong.

**Comment by end-me-please** [comment]
What are you reporting here? 125 to 126? Do you mean build 135 to bleeding edge?

you say that it happened when using a mod, but you don’t tell us what mods you used?

Worst of all, reporting a corrupted save file, **without giving us the save file?**

Also not making a Backup before updating to a version that everyone told you was unstable.

**Comment by deltanedas** [comment]
idior swore in mindustry bug report, banned for life

**Comment by buthed010203** [comment]
>Complain about things breaking when loading them with a mod
>Not linking the mod since its "irrelevant"

**Comment by pl0xyelit** [comment]
he just like me fr

**Comment by TheAirBlow** [comment]
lazy to complete

**Comment by TheAirBlow** [comment]
I reset everything lel
