### ISSUE TITLE
version changing partial progress reset

### ISSUE THREAD

**Issue by Comodo17** [Anuken/Mindustry#6976]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: going from the regular release build, to a test flight build, then back to the release build, causes your progress to be partially reset. Research, including map completion “research” is kept, so are certain sectors, however the campaign sectors, as well as most other non-campaign sectors, are lost. Resources in non-lost cores are kept. Sector icons are kept. Launch pad destinations are kept, though sending them to sectors you haven’t claimed results in the resources being lost. 

(https://user-images.githubusercontent.com/106919547/172056995-d3a30c13-d3bd-449b-86bc-304a2b6f4351.png)

**Steps to reproduce**: download Mindustry from the App Store, then download the test flight version over it, then re-download Mindustry from the App Store. Any campaign progress done during either the original App Store download, or test flight version, will be partially reset 

**Link(s) to mod(s) used**: `[Turtle /zooooooooom:1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/8840193/mindustry-data-export.zip)![C3175585-61B1-4BBC-A309-E0BC81ED940F]

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
This is to be expected, the new save formats and such aren't backwards compatible

**Comment by Comodo17** [comment]
Yea, I suspected that, just making sure it wasn’t something that should be made aware of

**Comment by buthed010203** [comment]
![69E641DB-BD81-42BA-9D15-52A99B7735AF](https://user-images.githubusercontent.com/26940575/172057632-1c6cd63c-3213-4e27-bd70-b0a018ca79ba.jpeg)
He's already aware of it

**Comment by Comodo17** [comment]
Alright
