### ISSUE TITLE
Lack of drone control

### ISSUE THREAD

**Issue by MKSO4KA** [Anuken/Mindustry#6977]
**Platform**: *Windows*

**Build**: *beta 22572 and beta 22573*

**Issue**: *You have replaced drone control with something else. But when choosing a target (where to attack), the drones stand in the place of their respawn and do not move. I will say in advance that I chose them, they were displayed from the bottom right.This bug does not depend on the save, as it was tested on a clean build without saves.*

**Steps to reproduce**: *Select Drones (default button shift and holding the mouse, select the ones you need) then go to the enemy building, click on shift and the drones will stay put.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
~~are you sure you are right-clicking and not left-clicking for targetting~~
