### ISSUE TITLE
iOS needs a new beta

### ISSUE THREAD

**Issue by NeonSupernova** [Anuken/Mindustry#6979]
**Platform**: iOS

**Build**: /dev/null

**Issue**: The iOS Testflight builds have all expired. 

**Steps to reproduce**: open testfligt and look at Mindustry 

**Link(s) to mod(s) used**: NA

**Save file**: *Null*

**(Crash) logs**: *No crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

^ This is kinda my issue

- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by NeonSupernova** [comment]
Regardless, needs an ios beta

**Comment by TheAirBlow** [comment]
> > to make a checkbox not checked, do `[ ]`
> > 
> > * [ ]  checked
> > * [x]  not checked
> 
> [#6975 (comment)](https://github.com/Anuken/Mindustry/issues/6975#issue-1261066080) [#6975 (comment)](https://github.com/Anuken/Mindustry/issues/6975#issuecomment-1147201621) this you bro? @TheAirBlow

[#6975 (commend)](https://github.com/Anuken/Mindustry/issues/6975#issuecomment-1146831867) this you bro? @pl0xyelit
