### ISSUE TITLE
[Feature] Transportation Drones

### ISSUE THREAD

**Issue by zicklag** [Anuken/Mindustry#698]
Me and @tekhnaeraav have just had an idea for a new kind of drone pad that allows relatively slow but long range transportation of materials using drones.

The idea is that you can create a transportation drone pad that will build drones that are similar to miner drones, but instead of mining materials, transportation drones will transport any materials loaded into their pad to any other block that can take materials such as a turret, a container, or the core. The pad would produce 2 drones per pad.

Transportation drones are similar in some ways to the function of mass drivers, but they have several different aspects that would effect your choice to use one or the other:

&nbsp; | Mass Driver | Transportation Drone
----  | ----- | -----
**Throughput** | High throughput from point A to point B | Throughput depends on distance between points and drones move relatively slowly.
**Distance** | Mass drivers must be within range of eachother. | Drones can bring material any distance across the map
**Power Consumption** | Mass drivers take 105 power/second | Drone pads will proabably take 66 power/second like miner drone pads
**Cost** | More expensive — Lead: 125, Titanium: 125, Thorium: 50, Silicon: 75 | Less expensive — ( speculated ) Lead: 55, Metaglass: 45, Silicon: 75, Titanium: 45
**Reliability** | Reliable until pad ( 360 health ) is destroyed | Reliable only if drones and pad remain in-tact. ( drones will be rebuilt if pad has power ) — Pad life: 160, Drone life: 60
**Surface Area** | 3x3 block — Easy to load and unload, but take extra space. | 2x2 — Smaller, but not as much surface to load. 
**Diversity** | Can handle any number of different materials efficiently. | Can handle any number of different materials, but individual drones can only transport one kind of material at a time. 
**Distribution** | Mass drivers unload only into another mass driver | Drones can unload into any block that accepts materials: containers, the core, turrets, routers, etc.
**Capacity** | 120 items | 75 items

### Distribution

If multiple different materials are being loaded into a transportation drone's pad, the the drones, which can only transport one material at a time, would have to have some logic used to determine which material they grab.

They could grab the material that there is the most of in the pad, but that could definitely lead to drones only ever transporting one material from a pad that has multiple materials in it. This could just be part of the way that the pads are disadvantaged from alternatives like the mass driver.

Another option is, when there are two drones active, one drone will take the most abundant resource in the pad and the other will take the second-most abundant resource in the pad.

**Comment by DeltaRays** [comment]
Or maybe make it so you can choose the priorities of each item in some kind of menu (or you can make it so you can assign one drone per resource)

**Comment by zicklag** [comment]
That would be a good idea. I don't know exactly how that would work, though, because clicking on the pad would need to go into the "connection" mode where you can select where the drones bring the materials to. Bringing up a menu at the same time may not work very well.

**Comment by Arkanic** [comment]
@zicklag Nice! this would simplify transportation, but can you please put this in #545 ?

**Comment by zicklag** [comment]
Ah, yes. Sorry about that, I didn't realize that we were consolidating everything on to that issue.
