### ISSUE TITLE
Itch 135.2 will not launch

### ISSUE THREAD

**Issue by theSignSaysDie** [Anuken/Mindustry#6987]
**Platform**: *Windows*

**Build**: *135.2 (itch.io)*

**Issue**: *After downloading the game and launching it from the File Explorer, the process appears in Task Manager, but the game does not run and no window appears.*

**Steps to reproduce**: 
*1. Download [UNSTABLE ALPHA][Windows-64bit]Mindustry.zip from Mindustry's itch.io page*
*2. Extract the zip file into a new folder*
*3. Open the folder and launch the game*
*4. Open task manager*
*5. Wait for nothing to happen*

**Link(s) to mod(s) used**: *None*

**Save file**: *None*

**(Crash) logs**: *Surprisingly, none. I can't find a crash folder anywhere.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Add'l comment: [This](https://github.com/Anuken/Mindustry/issues/6533) issue is the most relevant previously closed issue I could find. I read that the issue was upstream and that an update to Mindustry had conclusively fixed the problem; nevertheless I have the same issue. 
The same thing happens when I try to download the v7 beta through Steam.

**Comment by end-me-please** [comment]
You are downloading/launching a .jar file, right?

**Comment by Anuken** [comment]
Crash logs are required, and if you cannot find one, there is nothing I can do.
