### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by TihonTre** [Anuken/Mindustry#6990]
![Screenshot_2022-06-08-12-14-40-562_io anuke mindustry](https://user-images.githubusercontent.com/107109294/172581654-c77c0f7b-2684-4c4f-b7a0-5abed6d5d5cb.jpg)

**Comment by WilloIzCitron** [comment]
~~funny, but anuke forgot to fix this~~

**Comment by Anuken** [comment]
Invalid report.
