### ISSUE TITLE
map editor unknowingly turning off canGameOver

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#6996]
**Platform**: all

**Build**: BE

**Issue**: *Explain your issue in detail.*
presumably, selecting tantros as a generation option turns off canGameOver (TantrosPlanetGenerator.java#92) which can cause issues if you make it into a proper map afterwards, there's also probably a need to automatically toggle canGameOver to true for some number of BE builds since maps on servers (and likely in map folders of players) are currently corrupted with this, and the only reliable way i found to revert this manually uses relatively complex js

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
mentioned above

**Save file**: affected map provided, though the most you'd do here is just check that canGameOver is indeed false
[attack_map_erekir.zip](https://github.com/Anuken/Mindustry/files/8864547/attack_map_erekir.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> there's also probably a need to automatically toggle canGameOver to true for some number of BE builds since maps on servers (and likely in map folders of players) are currently corrupted with this

But this is reset when you make a new map, so the only way to "corrupt" something is to generate a tantros map, generate something else, then make a map out of it. Tantros was never supposed to be used for maps anyway, and this is BE, so I won't be doing anything about it. Make a new map, or use JS to fix it.

**Comment by Ilya246** [comment]
alright, then i guess i will have to make an autofix js command and distribute it to everyone

**Comment by SMOLKEYS** [comment]
six nine nine six
