### ISSUE TITLE
RTS AI crashes game when attempting to make naval units go to the nearest core.

### ISSUE THREAD

**Issue by yesC48** [Anuken/Mindustry#6997]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
BE 22572

**Issue**: *Explain your issue in detail.*
Game crashes whenever there are sufficient units to attack the core. (RTS AI exclusive)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
- Activate RTS AI
- Do that on a replica of Planetary Launch Terminal
- Use a naval map with naval factories if you're far too lazy to consult the source code and locate the following:
> Planetary Launch Terminal

- Wait for a bit
- Profit

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Testing Utilities. That's it. I use it to mess with stuff.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
chill dude, just try to replicate the bug and voilà

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash_1654776657806.txt](https://github.com/Anuken/Mindustry/files/8870197/crash_1654776657806.txt)
this ^

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> BE 22572

That is a very outdated build.

**Comment by yesC48** [comment]
i legitimately didn't see it
fuck
correction: BE 22675

**Comment by yesC48** [comment]
im high rn. im leaving it be. bye
