### ISSUE TITLE
Lost a sector (not vulnerable) when relogging?

### ISSUE THREAD

**Issue by gedeknepper** [Anuken/Mindustry#7007]
Platform: Linux (Ubuntu)

Build: Mindustry-BE-Desktop-22637.jar

After Ground Zero, I took sector 174, then 41, then continued with the campaign. Last time I played, I was working in sector 174. I might have force-shut-down my computer because it was getting too laggy to properly close. Now that I relog, this sector, and only this one, seems to have been reset. I don't own it anymore, and when I click on it in the planetary view, it doesn't tell me what resources it has, as if I'd never even been in it. It's not adjacent to any enemy base, either.

No mods used, pure vanilla.

Save file: Attached.
[save-data.zip](https://github.com/Anuken/Mindustry/files/8885750/save-data.zip)

No crash log, because no crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
> I might have force-shut-down my computer

do other programs/games save progress if you suddenly shut the computer down

**Comment by Anuken** [comment]
Probable data corruption, I would guess a backup was loaded. Not something I can debug or fix properly.
