### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by ShadowFoxy34** [Anuken/Mindustry#7024]
**Platform**: *Android*

**Build**: *bleeding edge 22671

**Issue**: *Hello, I have a bug on the mobile version of Mindustry (Version: 22671).  When I am in some location for a long time, for example: Painted Mountains or another, then my game hangs, I tried to restart the game, tried this bug, but it appeared again, this method did not help.  Tried reinstalling the game didn't help either.  I saved the game data on the phone (Suddenly I will lose the data).  And switched to another version: 22663. P.S: There may be errors in the text, because I do not know English very well.  But I am learning.*

**Steps to reproduce**: *I was just playing and suddenly this bug appeared.  He won't let me play*

**Link(s) to mod(s) using**: *I played without mods*

**Save file**: * Can I send the save file to Your discord?*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Can I send the save file to your discord?*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Unless this happens on desktop or you are able to provide more specific steps to reproduce, I won't be investigating or fixing this.
