### ISSUE TITLE
game crash on launch

### ISSUE THREAD

**Issue by CreepyQuin** [Anuken/Mindustry#7025]
platform: Windows 11

build: 135.2

issue: crash on launch

how to repeat: launch the game

mods used: none

save file: i think it isn't related to any save files because the glitch happens while loading the game

[crash-report-06_15_2022_19_28_19.txt](https://github.com/Anuken/Mindustry/files/8912202/crash-report-06_15_2022_19_28_19.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Can't reproduce this issue, and the log makes no sense.
