### ISSUE TITLE
Unable to place down Interplanetary Accelerator

### ISSUE THREAD

**Issue by DrPHDCat** [Anuken/Mindustry#7029]
**Platform**:Windows

**Build**: 22674

**Issue**: Unable to place down Interplanetary accelerator. Not just cant place, but it doesnt show up in the interface at all!
![image](https://user-images.githubusercontent.com/107643253/174138049-800a566b-8517-409d-9317-22c5f7f6d321.png)
![image](https://user-images.githubusercontent.com/107643253/174139014-30643b8a-3f59-45f1-addf-dbb57759ae9c.png)

**Steps to reproduce**: 1.Capture Planetary Launch Terminal
2.Research Interplanetary accelerator
3. Start dissassembling the Interplanetary accelerator at the enemy base
4. Notice you cant fix it back up
5. Completely disassemble
6. Notice it isnt in the building interface.(thats the bug)
(Note: Placing down a schematic with just planetary accelerator doesnt work neither)

**Link(s) to mod(s) used**: No mods were used

**Save file**: 
[error.zip](https://github.com/Anuken/Mindustry/files/8921467/error.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, the accelerator is hidden until it is decided what to do with it. It may be removed as a block altogether, since it serves no actual purpose.

**Comment by Bottinator22** [comment]
It's still completely functional tho

**Comment by Anuken** [comment]
It can't be considered "functional" when it has no defined function. It was supposed to be used for cross-planet launches, but there are no other valid locations that it should be launching to. The only thing you're seeing is leftover code from back when the Erekir campaign was supposed to be after Serpulo, and that's no longer relevant.
