### ISSUE TITLE
Game crashing with local server

### ISSUE THREAD

**Issue by complay11** [Anuken/Mindustry#7035]
**Platform**: *Windows*

**Build**: *126.2*

**Issue**: *When I host a dedicated server and connect to it, my game crashes and my screen start to turn on and off.*

**Steps to reproduce**: Joined local server.

**Link(s) to mod(s) used**: No mods used.

**Save file**: *Im sorry, but i dont have any save file, no file was created.*

**(Crash) logs**: *Attached file*

---X

[crash.txt](https://github.com/Anuken/Mindustry/files/8928802/crash.txt)

**Comment by Anuken** [comment]
> Link(s) to mod(s) used: No mods used.

The crash logs you have sent contain crashes caused by mods. There are no other crashes listed. In any case, 126.2 is not the latest version.
