### ISSUE TITLE
Silicon Smelter Building Crash

### ISSUE THREAD

**Issue by TereZa0** [Anuken/Mindustry#7039]
**Platform**: *Windows*

**Build**: *pre-alpha build 135*

**Issue**: *when i try to build Silicon Smelter the game crash*
![image](https://user-images.githubusercontent.com/73412887/174428758-b6de6f6f-fb8d-4806-92dc-6797dfd45b8d.png)

**Steps to reproduce**: *Build the Silicon Smelter (also works in sandbox mode)*

**Link(s) to mod(s) used**: 
   **-Sapphirium:** *https://github.com/3snake3/sapphirium*
   **-NEWHORIZON MOD:** *https://github.com/yuria-shikibe/newhorizonmod*
   **-UNLIMITED ARMAMENT WORKS:** *https://github.com/eschatologue/unlimited-armament-works*
   **-Units-mod:** *https://github.com/3snake3/units-mod*
   **-Pixel Texturepack Mindustry:** *https://github.com/xeloboyo/factoriodustry*

**Save file**: *[saves.zip](https://github.com/Anuken/Mindustry/files/8933180/saves.zip)*

First Crash Appear in **Camping The Craters** and i've try in other map and it keep crashing after the build progress started.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: [crash-report-06_18_2022_14_22_40.txt](https://github.com/Anuken/Mindustry/files/8933186/crash-report-06_18_2022_14_22_40.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a mod bug.
