### ISSUE TITLE
Unit Limit of salt flats first time launch is bugged

### ISSUE THREAD

**Issue by hublylol** [Anuken/Mindustry#7040]
**Platform**: Windows

**Build**: 135.2

**Issue**: When i first launched I had a unit capacity of 24 units even thought i have a core shard. upon quitting and reloading the game, it was reduced back to 8 but the first launch having 24 units was bugged

**Steps to reproduce**: make a new campaign, beat tar fields, and launch to salt flats from tar fields

**Link(s) to mod(s) used**: N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without readi
[salt flats bugged data.zip](https://github.com/Anuken/Mindustry/files/8933319/salt.flats.bugged.data.zip)
ng it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This was already reported/changed.
