### ISSUE TITLE
Translation error in french.

### ISSUE THREAD

**Issue by LOICVAL42** [Anuken/Mindustry#7059]
**Platform**: *Linux*

**Build**: *126.3*

**Issue**: *Translation error in french. In the options it is written "language" instead of "langage" as it should be in french.*

**Steps to reproduce**: *Game in french, open the settings*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Translation errors are not bugs; they should not be reported on the issue tracker.
