### ISSUE TITLE
Want to add Unit level Stats, where should these properties / methods live?

### ISSUE THREAD

**Issue by 1RedOne** [Anuken/Mindustry#706]
Hi,

 Interested in helping to add unit level stats (to track how many units a turret kills, which would appear when you hover over a unit and maybe have badge or aura appearance for 'Hero Level' units)

  Could @Anuken offer input as to where would be good place to add this functionality in the repository (still looking through the repo layout and not sure)

Thanks!

**Comment by Anuken** [comment]
This sounds a lot like the leveling system that Warzone 2100 used. The issue, however, is that in the current game state, units are extremely cheap, stupid and expendable, to the point that no unit is likely to get more than 1-2 kills in its entire lifetime unless it is a _fortress_ or _boss_-type unit. I was planning on implementing something to improve this [on the Trello](https://trello.com/c/KdXqVREk/516-reduce-unit-count), but it's not fleshed out right now.

Another issue is that there is no tracking done of who kills what; while it is _possible_ to implement such a thing, a unit doesn't even know whether its bullet hit something or not. Internal changes need to be made before some sort of level system can be implemented.

**Comment by 1RedOne** [comment]
When I said unit, I was thinking more of turrets.  I know some of my longer
range mortar units have definitely hit hundreds of units over their
lifespan.

You're right of course, there would have to be tracking on each bullet, who
the shooter was and whether they got the killing blow or just contributed.

Sounds like a lot of work to make it happen.
