### ISSUE TITLE
rebuild targeting bug

### ISSUE THREAD

**Issue by RusLeonid** [Anuken/Mindustry#7061]
**Platform**: *Linux*

**Build**: *foo's client version 4059b1a, jun 22 (equivalent to b22695)*

**Issue**: *unit targeting resets if targeted block has been rebuilt*

https://user-images.githubusercontent.com/81614288/175163478-cddcbf24-a9c5-4183-b493-000c39dba66c.mp4

**Steps to reproduce**: *- be attacking a block that is in build tower radius*
                                      *- target that block while it is being rebuilt*
                                      *- upon completion, the targeting for the units that were attacking that block resets*
**Link(s) to mod(s) used**: *https://github.com/mindustry-antigrief/mindustry-client/releases/tag/v8.0.0*

**Save file**: forgor to save state, was on this map, block was an atmospheric concentrator on tile (196, 168)
[Manhattan1.6.msav.zip](https://github.com/Anuken/Mindustry/files/8962145/Manhattan1.6.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, once it's been built, it's a different block and a different target.
