### ISSUE TITLE
Start the game bug

### ISSUE THREAD

**Issue by SandFogaz** [Anuken/Mindustry#7063]
Hi,
I have a problema entering in map where I've already player. The map Is "Windy Islands" and this map is important to unlock new features in the research tree.
The problem is about the fact that when I try to play that map the game tell me that I have not enough resources (particulary it tells me that I have zero "lead"). But that thing isn't correct Aldo because in other games I can play.

Thanks, I'm not english so if there are some problems in the understanding tell me.

---

*Place an X (X) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This issue is invalid; you did not fill in the template.

**Comment by SMOLKEYS** [comment]
> The problem is about the fact that when I try to play that map the game tell me that I have not enough resources (particulary it tells me that I have zero "lead")

You need enough resources to land on different sectors. A Shard core needs 4000 copper and lead, and the core in the current sector you're on does not have any lead inside of it.
