### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Corsh** [Anuken/Mindustry#7064]
**Platform**: Window

**Build**: same with current 
**Issue**:  game crashed 

**Steps to reproduce**: * the game crashed when my unit attack enemy defense turret. it say defense tutter 274 cannot cast

**Link(s) to mod(s) used**: no issue with mod

**Save file**: I don't know lol

**(Crash) logs**: [crash-report-06_23_2022_09_09_24.txt](https://github.com/Anuken/Mindustry/files/8963055/crash-report-06_23_2022_09_09_24.txt)
![080980](https://user-images.githubusercontent.com/107997369/175191603-e44c3f63-2000-4ae2-9279-367fb6bb37c6.png)

- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That is a mod bug, not a Mindustry bug.
