### ISSUE TITLE
can't find public server and mods

### ISSUE THREAD

**Issue by dintomin** [Anuken/Mindustry#7069]
Windows

**Build**: 135.2

**Issue**: can't find public server and mods

**Steps to reproduce**: I don't know why it happened

**Save file**: 

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
![image](https://user-images.githubusercontent.com/108140547/175561591-4f467b7b-1404-4f18-bc02-516219bddff8.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SMOLKEYS** [comment]
~~Please, check your internet connection.~~

**Comment by Anuken** [comment]
Connection issue, can't fix on my end.
