### ISSUE TITLE
specific AI types not working with modded units on non-wave teams

### ISSUE THREAD

**Issue by stacktrace-error** [Anuken/Mindustry#7074]
**Platform**: Windows

**Build**: 22684, 22709, (unsure of J.Ws build, they're offline)

**Issue**: The last few weeks many people (including me) noticed some strange issues with AI like Missile, Repair and EffectDroneAI that caused it to only work on the map's current wave team if it was a modded unit.
MissileAI:
***https://user-images.githubusercontent.com/89076920/175763203-9eaeb1be-4dfd-48e1-a8ad-9cb735bad1ab.mp4***
RepairAI:
![image](https://user-images.githubusercontent.com/89076920/175763364-4d1bc0c1-1a4b-45f5-af38-6f066f7ac723.png)
EffectDroneAI:
![image](https://user-images.githubusercontent.com/89076920/175763443-eaea9fca-70a2-45e1-b9bc-35bdc90b69da.png)

**Steps to reproduce**: 
- Make any unit that does not have a generic AI in hjson
- Spawn it on all teams of the current map
- cucumber

**Link(s) to mod(s) used**: [Missile example](https://github.com/Anuken/Mindustry/files/8984114/Mindustry_mod_take_2.zip)
(can't get the other ones, this should be enough to show that something's wrong though.)

**Save file**: 
[missile.zip](https://github.com/Anuken/Mindustry/files/8984132/missile.zip)
---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
- Your mod doesn't work because you are not even assigning an AI to the missile unit itself. It's just a normal unit that has the `missile` timed destroy functionality, but that doesn't give it any other missile properties.
- EffectDroneAI is cut content and will be removed, don't use it.
- You are likely assigning `controller` / `aiController`, **which do not override player RTS AI behavior**. If you want that, assign `defaultController` instead.

**Comment by stacktrace-error** [comment]
question?
![image](https://user-images.githubusercontent.com/89076920/175775942-3377a2a1-edeb-470e-985c-9831621c2ff5.png)

**Comment by Anuken** [comment]
That is probably correct, but there is a (resolved) bug that makes controllers crash when the unit is actually created.

**Comment by stacktrace-error** [comment]
it seems to work now that we've updated to the fixed build, thank you

**Comment by Anuken** [comment]
Note: For missiles, you may also want to add `template: MissileUnitType`, which gives missiles all the properties of a standard missile ('move forward' AI, can't control, no physics, hidden, etc)
