### ISSUE TITLE
Unit clutch into walls and die

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry#7081]
**Platform**: `Windows 10 x64`

**Build**: `bleeding-edge build 22721`

**Issue**: *Explain your issue in detail.*
When units moved to a specific angle of a wall prop, it clutch into the wall and die instantly

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
command the unit into near the wall prop.

https://user-images.githubusercontent.com/43229798/175853957-7516050c-16e7-46b9-94b9-871f454edfaf.mp4

**Link(s) to mod(s) used**: `[[#FCC21B]MEEP of Faith/test-utils:41]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SMOLKEYS** [comment]
"*Unit tried to no-clip, got isekai'd to the backrooms.*"
