### ISSUE TITLE
Sorter not transferring to base

### ISSUE THREAD

**Issue by ICrowleyI** [Anuken/Mindustry#71]
Sorters do not transfer items to Base.
In the gif, stone should be added to the ressource pool through the sorter to the left of the base.
![sorter not transferring items to base](https://user-images.githubusercontent.com/30113543/34896664-edb13456-f7ea-11e7-8ad3-c9f2a4ce89db.gif)

**Comment by Anuken** [comment]
Fixed as of 5e2173fc54145d28241981a7648a73d825302363.
