### ISSUE TITLE
Game crashed on first run

### ISSUE THREAD

**Issue by Scawaffle** [Anuken/Mindustry#710]
Platform: # Windows

Build: # 95.1

Issue: # The Game crash on first launch

Notes: # ~

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=5872, tid=1524
#
# JRE version: OpenJDK Runtime Environment (8.0_72-b15) (build 1.8.0_72-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.72-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000000000218d000):  JavaThread "main" [_thread_in_native, id=1524, stack(0x0000000000030000,0x0000000000500000)]

siginfo: ExceptionCode=0xc0000005, ExceptionInformation=0x0000000000000008 0x0000000000000000

Registers:
RAX=0x0000000070a96e70, RBX=0x0000000013d90650, RCX=0x0000000000000001, RDX=0x00000000004ff01c
RSP=0x00000000004fefe8, RBP=0x00000000004ff098, RSI=0x0000000010200020, RDI=0x00000000000000d2
R8 =0x0000000000000004, R9 =0x000000000204f610, R10=0x00000000028f3868, R11=0x0000000070cb2110
R12=0x0000000000000000, R13=0x0000000013d90650, R14=0x00000000004ff0b0, R15=0x000000000218d000
RIP=0x0000000000000000, EFLAGS=0x0000000000210206

Top of Stack: (sp=0x00000000004fefe8)
0x00000000004fefe8:   00000000708e3b47 00000000000000d2
0x00000000004feff8:   00000000028f3726 00000000004ff800
0x00000000004ff008:   000000000218d000 0000000013d90650
0x00000000004ff018:   0000000010200020 00000000000000d2
0x00000000004ff028:   00000000028f3894 000000000218d000
0x00000000004ff038:   0000000013d90650 0000000010200020
0x00000000004ff048:   000000000218d000 00000000028f35c2
0x00000000004ff058:   00000000004ff058 0000000013d90650
0x00000000004ff068:   00000000004ff0b0 0000000013d93768
0x00000000004ff078:   0000000000000000 0000000013d90650
0x00000000004ff088:   0000000000000000 00000000004ff0b8
0x00000000004ff098:   00000000004ff0f8 00000000028e7470
0x00000000004ff0a8:   00000000f5eb2f88 00000000028ef6b6
0x00000000004ff0b8:   00000000004ff0b8 0000000013d87bb8
0x00000000004ff0c8:   00000000004ff108 0000000013d8bc08
0x00000000004ff0d8:   0000000000000000 0000000013d87bd0 

Instructions: (pc=0x0000000000000000)
0xffffffffffffffe0:   

Register to memory mapping:

RAX=0x0000000070a96e70 is an unknown value
RBX={method} {0x0000000013d90658} 'glGenFramebuffer' '()I' in 'io/anuke/arc/backends/sdl/jni/SDLGL'
RCX=0x0000000000000001 is an unknown value
RDX=0x00000000004ff01c is pointing into the stack for thread: 0x000000000218d000
RSP=0x00000000004fefe8 is pointing into the stack for thread: 0x000000000218d000
RBP=0x00000000004ff098 is pointing into the stack for thread: 0x000000000218d000
RSI=0x0000000010200020 is an unknown value
RDI=0x00000000000000d2 is an unknown value
R8 =0x0000000000000004 is an unknown value
R9 =0x000000000204f610 is an unknown value
R10=0x00000000028f3868 is at code_begin+840 in an Interpreter codelet
method entry point (kind = native)  [0x00000000028f3520, 0x00000000028f3e80]  2400 bytes
R11=0x0000000070cb2110 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x0000000013d90658} 'glGenFramebuffer' '()I' in 'io/anuke/arc/backends/sdl/jni/SDLGL'
R14=0x00000000004ff0b0 is pointing into the stack for thread: 0x000000000218d000
R15=0x000000000218d000 is a thread

Stack: [0x0000000000030000,0x0000000000500000],  sp=0x00000000004fefe8,  free space=4923k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.anuke.arc.backends.sdl.jni.SDLGL.glGenFramebuffer()I+0
j  io.anuke.arc.backends.sdl.SdlGL20.glGenFramebuffer()I+0
j  io.anuke.arc.graphics.glutils.GLFrameBuffer.build()V+73
j  io.anuke.arc.graphics.glutils.FrameBuffer.<init>(Lio/anuke/arc/graphics/Pixmap$Format;IIZZ)V+68
j  io.anuke.arc.graphics.glutils.FrameBuffer.<init>(II)V+8
j  io.anuke.mindustry.graphics.BlockRenderer.<init>()V+49
j  io.anuke.mindustry.core.Renderer.<init>()V+9
j  io.anuke.mindustry.ClientLauncher.setup()V+213
j  io.anuke.mindustry.ClientLauncher.init()V+1
j  io.anuke.arc.backends.sdl.SdlApplication$$Lambda$17.accept(Ljava/lang/Object;)V+4
j  io.anuke.arc.backends.sdl.SdlApplication.listen(Lio/anuke/arc/function/Consumer;)V+38
j  io.anuke.arc.backends.sdl.SdlApplication.loop()V+27
j  io.anuke.arc.backends.sdl.SdlApplication.<init>(Lio/anuke/arc/ApplicationListener;Lio/anuke/arc/backends/sdl/SdlConfig;)V+204
j  io.anuke.mindustry.desktop.DesktopLauncher.main([Ljava/lang/String;)V+19
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x000000001421e000 JavaThread "Service Thread" daemon [_thread_blocked, id=3820, stack(0x0000000016e30000,0x0000000017300000)]
  0x00000000141ae000 JavaThread "C1 CompilerThread1" daemon [_thread_blocked, id=2588, stack(0x0000000016960000,0x0000000016e30000)]
  0x00000000141a4000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=3724, stack(0x0000000016490000,0x0000000016960000)]
  0x00000000141a3000 JavaThread "Attach Listener" daemon [_thread_blocked, id=748, stack(0x0000000015fc0000,0x0000000016490000)]
  0x00000000141a1800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=6240, stack(0x0000000015af0000,0x0000000015fc0000)]
  0x0000000014189000 JavaThread "Finalizer" daemon [_thread_blocked, id=4144, stack(0x0000000015560000,0x0000000015a30000)]
  0x0000000014140000 JavaThread "Reference Handler" daemon [_thread_blocked, id=2440, stack(0x0000000015090000,0x0000000015560000)]
=>0x000000000218d000 JavaThread "main" [_thread_in_native, id=1524, stack(0x0000000000030000,0x0000000000500000)]

Other Threads:
  0x0000000014134800 VMThread [stack: 0x0000000014bc0000,0x0000000015090000] [id=3200]
  0x000000000212d800 WatcherThread [stack: 0x0000000017300000,0x00000000177d0000] [id=6764]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 9728K, used 7495K [0x00000000f5600000, 0x00000000f6080000, 0x0000000100000000)
  eden space 8704K, 74% used [0x00000000f5600000,0x00000000f5c547f0,0x00000000f5e80000)
  from space 1024K, 98% used [0x00000000f5e80000,0x00000000f5f7d4c0,0x00000000f5f80000)
  to   space 1024K, 0% used [0x00000000f5f80000,0x00000000f5f80000,0x00000000f6080000)
 ParOldGen       total 22016K, used 1088K [0x00000000e0200000, 0x00000000e1780000, 0x00000000f5600000)
  object space 22016K, 4% used [0x00000000e0200000,0x00000000e0310260,0x00000000e1780000)
 Metaspace       used 8799K, capacity 9140K, committed 9344K, reserved 1056768K
  class space    used 984K, capacity 1128K, committed 1152K, reserved 1048576K

Card table byte_map: [0x0000000011ca0000,0x0000000011da0000] byte_map_base: 0x000000001159f000

Marking Bits: (ParMarkBitMap*) 0x0000000071269c30
 Begin Bits: [0x0000000012740000, 0x0000000012f38000)
 End Bits:   [0x0000000012f38000, 0x0000000013730000)

Polling page: 0x00000000005c0000

CodeCache: size=245760Kb used=2706Kb max_used=2706Kb free=243053Kb
 bounds [0x00000000028e0000, 0x0000000002b90000, 0x00000000118e0000]
 total_blobs=1077 nmethods=694 adapters=298
 compilation: enabled

Compilation events (10 events):
Event: 2.182 Thread 0x00000000141ae000  690       3       sun.misc.URLClassPath$JarLoader$2::getCodeSourceURL (8 bytes)
Event: 2.183 Thread 0x00000000141ae000 nmethod 690 0x0000000002b81050 code [0x0000000002b811a0, 0x0000000002b81310]
Event: 2.183 Thread 0x00000000141ae000  691       3       sun.misc.URLClassPath$JarLoader$2::getManifest (11 bytes)
Event: 2.183 Thread 0x00000000141ae000 nmethod 691 0x0000000002b813d0 code [0x0000000002b81540, 0x0000000002b81768]
Event: 2.183 Thread 0x00000000141ae000  692       3       java.util.jar.JarFile::getManifest (5 bytes)
Event: 2.183 Thread 0x00000000141ae000 nmethod 692 0x0000000002b81850 code [0x0000000002b819c0, 0x0000000002b81b48]
Event: 2.183 Thread 0x00000000141ae000  693   !   3       java.net.URLClassLoader::definePackageInternal (81 bytes)
Event: 2.185 Thread 0x00000000141ae000 nmethod 693 0x0000000002b81bd0 code [0x0000000002b81e00, 0x0000000002b829b8]
Event: 2.185 Thread 0x00000000141ae000  694       3       java.net.URLClassLoader::getAndVerifyPackage (109 bytes)
Event: 2.187 Thread 0x00000000141ae000 nmethod 694 0x0000000002b82ed0 code [0x0000000002b831c0, 0x0000000002b84968]

GC Heap History (2 events):
Event: 1.756 GC heap before
{Heap before GC invocations=1 (full 0):
 PSYoungGen      total 9728K, used 8643K [0x00000000f5600000, 0x00000000f6080000, 0x0000000100000000)
  eden space 8704K, 99% used [0x00000000f5600000,0x00000000f5e70c88,0x00000000f5e80000)
  from space 1024K, 0% used [0x00000000f5f80000,0x00000000f5f80000,0x00000000f6080000)
  to   space 1024K, 0% used [0x00000000f5e80000,0x00000000f5e80000,0x00000000f5f80000)
 ParOldGen       total 22016K, used 0K [0x00000000e0200000, 0x00000000e1780000, 0x00000000f5600000)
  object space 22016K, 0% used [0x00000000e0200000,0x00000000e0200000,0x00000000e1780000)
 Metaspace       used 6746K, capacity 6968K, committed 7296K, reserved 1056768K
  class space    used 719K, capacity 816K, committed 896K, reserved 1048576K
Event: 1.762 GC heap after
Heap after GC invocations=1 (full 0):
 PSYoungGen      total 9728K, used 1013K [0x00000000f5600000, 0x00000000f6080000, 0x0000000100000000)
  eden space 8704K, 0% used [0x00000000f5600000,0x00000000f5600000,0x00000000f5e80000)
  from space 1024K, 98% used [0x00000000f5e80000,0x00000000f5f7d4c0,0x00000000f5f80000)
  to   space 1024K, 0% used [0x00000000f5f80000,0x00000000f5f80000,0x00000000f6080000)
 ParOldGen       total 22016K, used 1088K [0x00000000e0200000, 0x00000000e1780000, 0x00000000f5600000)
  object space 22016K, 4% used [0x00000000e0200000,0x00000000e0310260,0x00000000e1780000)
 Metaspace       used 6746K, capacity 6968K, committed 7296K, reserved 1056768K
  class space    used 719K, capacity 816K, committed 896K, reserved 1048576K
}

Deoptimization events (1 events):
Event: 1.048 Thread 0x000000000218d000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000000002a633a8 method=java.lang.String.startsWith(Ljava/lang/String;I)Z @ 25

Internal exceptions (10 events):
Event: 0.558 Thread 0x000000000218d000 Exception <a 'java/io/FileNotFoundException'> (0x00000000f58a29d8) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.995 Thread 0x000000000218d000 Exception <a 'java/lang/UnsatisfiedLinkError': The specified module could not be found.

> (0x00000000f5a02d28) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 0.997 Thread 0x000000000218d000 Exception <a 'java/lang/UnsatisfiedLinkError': The specified module could not be found.

> (0x00000000f5a13260) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 1.000 Thread 0x000000000218d000 Exception <a 'java/lang/UnsatisfiedLinkError': The specified module could not be found.

> (0x00000000f5a13678) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 735]
Event: 1.110 Thread 0x000000000218d000 Exception <a 'java/io/IOException'> (0x00000000f5a8d298) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.110 Thread 0x000000000218d000 Exception <a 'java/io/IOException'> (0x00000000f5a8d5a8) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.110 Thread 0x000000000218d000 Exception <a 'java/io/IOException'> (0x00000000f5a8d808) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 1.232 Thread 0x000000000218d000 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000f5b5b628) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 1.251 Thread 0x000000000218d000 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000f5b68978) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 1.725 Thread 0x000000000218d000 Exception <a 'java/lang/IncompatibleClassChangeError': Found class java.lang.Object, but interface was expected> (0x00000000f5ddc168) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\interpreter\linkResolver.cpp, line 
`尜�?

Events (10 events):
Event: 2.185 loading class io/anuke/arc/graphics/glutils/FrameBuffer
Event: 2.185 loading class io/anuke/arc/graphics/glutils/FrameBuffer done
Event: 2.186 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer
Event: 2.186 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer done
Event: 2.188 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$GLFrameBufferBuilder
Event: 2.188 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$GLFrameBufferBuilder done
Event: 2.189 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$FrameBufferBuilder
Event: 2.189 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$FrameBufferBuilder done
Event: 2.190 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$FrameBufferTextureAttachmentSpec
Event: 2.190 loading class io/anuke/arc/graphics/glutils/GLFrameBuffer$FrameBufferTextureAttachmentSpec done

Dynamic libraries:
0x0000000140000000 - 0x000000014005d000 	D:\Asriel\Games\Mindustry\Mindustry.exe
0x0000000077c50000 - 0x0000000077dfa000 	C:\Windows\SYSTEM32\ntdll.dll
0x0000000077a30000 - 0x0000000077b4f000 	C:\Windows\system32\kernel32.dll
0x000007fefdb00000 - 0x000007fefdb6a000 	C:\Windows\system32\KERNELBASE.dll
0x0000000070ab0000 - 0x00000000712e4000 	D:\Asriel\Games\Mindustry\jre\bin\server\jvm.dll
0x0000000077b50000 - 0x0000000077c4a000 	C:\Windows\system32\USER32.dll
0x000007fefe260000 - 0x000007fefe2c7000 	C:\Windows\system32\GDI32.dll
0x000007feffae0000 - 0x000007feffaee000 	C:\Windows\system32\LPK.dll
0x000007fefe8f0000 - 0x000007fefe9ba000 	C:\Windows\system32\USP10.dll
0x000007feffec0000 - 0x000007fefff5f000 	C:\Windows\system32\msvcrt.dll
0x000007feffde0000 - 0x000007feffebb000 	C:\Windows\system32\ADVAPI32.dll
0x000007fefe730000 - 0x000007fefe74f000 	C:\Windows\SYSTEM32\sechost.dll
0x000007fefe580000 - 0x000007fefe6ad000 	C:\Windows\system32\RPCRT4.dll
0x000007fef9770000 - 0x000007fef9779000 	C:\Windows\system32\WSOCK32.dll
0x000007fefeaa0000 - 0x000007fefeaed000 	C:\Windows\system32\WS2_32.dll
0x000007feffd30000 - 0x000007feffd38000 	C:\Windows\system32\NSI.dll
0x000007fefb5e0000 - 0x000007fefb61b000 	C:\Windows\system32\WINMM.dll
0x000007fefcb50000 - 0x000007fefcb5c000 	C:\Windows\system32\VERSION.dll
0x0000000077e10000 - 0x0000000077e17000 	C:\Windows\system32\PSAPI.DLL
0x00000000729a0000 - 0x0000000072a72000 	D:\Asriel\Games\Mindustry\MSVCR100.dll
0x000007fefe750000 - 0x000007fefe77e000 	C:\Windows\system32\IMM32.DLL
0x000007fefe030000 - 0x000007fefe139000 	C:\Windows\system32\MSCTF.dll
0x000007fefb000000 - 0x000007fefb00f000 	D:\Asriel\Games\Mindustry\jre\bin\verify.dll
0x000007fefaf60000 - 0x000007fefaf89000 	D:\Asriel\Games\Mindustry\jre\bin\java.dll
0x000007fefaa30000 - 0x000007fefaa46000 	D:\Asriel\Games\Mindustry\jre\bin\zip.dll
0x000007fefed50000 - 0x000007feffada000 	C:\Windows\system32\SHELL32.dll
0x000007fefe1e0000 - 0x000007fefe251000 	C:\Windows\system32\SHLWAPI.dll
0x000007fefde20000 - 0x000007fefe023000 	C:\Windows\system32\ole32.dll
0x000007fefda60000 - 0x000007fefda6f000 	C:\Windows\system32\profapi.dll
0x000007fefd2c0000 - 0x000007fefd2d8000 	C:\Windows\system32\CRYPTSP.dll
0x000007fefcfc0000 - 0x000007fefd007000 	C:\Windows\system32\rsaenh.dll
0x000007fefda80000 - 0x000007fefda9e000 	C:\Windows\system32\USERENV.dll
0x000007fefd900000 - 0x000007fefd90f000 	C:\Windows\system32\CRYPTBASE.dll
0x000007fef87b0000 - 0x000007fef87ca000 	D:\Asriel\Games\Mindustry\jre\bin\net.dll
0x000007fefd260000 - 0x000007fefd2b5000 	C:\Windows\system32\mswsock.dll
0x000007fefd250000 - 0x000007fefd257000 	C:\Windows\System32\wship6.dll
0x000007fefae00000 - 0x000007fefae27000 	C:\Windows\system32\IPHLPAPI.DLL
0x000007fefad70000 - 0x000007fefad7b000 	C:\Windows\system32\WINNSI.DLL
0x000007fefa910000 - 0x000007fefa928000 	C:\Windows\system32\dhcpcsvc.DLL
0x000007fefa8f0000 - 0x000007fefa901000 	C:\Windows\system32\dhcpcsvc6.DLL
0x000007feee310000 - 0x000007feee321000 	D:\Asriel\Games\Mindustry\jre\bin\nio.dll
0x000007feedf60000 - 0x000007feedfa2000 	C:\Users\Compaq\AppData\Local\Temp\jna-2024021919\jna6956244853330714100.dll
0x000007fef6de0000 - 0x000007fef6de3000 	C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
0x000007feedad0000 - 0x000007feedb6c000 	C:\Users\Compaq\AppData\Local\Temp\jna-2024021919\jna6788325526274677294.dll
0x0000000065ac0000 - 0x0000000065b0b000 	C:\Users\Compaq\AppData\Local\Temp\arcCompaq\7d76f548\gdx64.dll
0x000007fee9980000 - 0x000007fee9a94000 	C:\Users\Compaq\AppData\Local\Temp\arcCompaq\da5eb935\OpenAL32.dll
0x00000000708e0000 - 0x0000000070aaf000 	C:\Users\Compaq\AppData\Local\Temp\arcCompaq\edae4c97\sdl-arc64.dll
0x000007fefe9c0000 - 0x000007fefea9a000 	C:\Windows\system32\OLEAUT32.dll
0x000007fee9bc0000 - 0x000007fee9cdd000 	C:\Windows\system32\OPENGL32.dll
0x000007feee2e0000 - 0x000007feee30d000 	C:\Windows\system32\GLU32.dll
0x000007fee9fa0000 - 0x000007feea091000 	C:\Windows\system32\DDRAW.dll
0x000007fef8540000 - 0x000007fef8548000 	C:\Windows\system32\DCIMAN32.dll
0x000007fefeb70000 - 0x000007fefed47000 	C:\Windows\system32\SETUPAPI.dll
0x000007fefdaa0000 - 0x000007fefdad6000 	C:\Windows\system32\CFGMGR32.dll
0x000007fefdd20000 - 0x000007fefdd3a000 	C:\Windows\system32\DEVOBJ.dll
0x000007fefbeb0000 - 0x000007fefbec8000 	C:\Windows\system32\dwmapi.dll
0x000007fefc2e0000 - 0x000007fefc336000 	C:\Windows\system32\uxtheme.dll
0x000007fef7270000 - 0x000007fef72ef000 	C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
0x000007feffd40000 - 0x000007feffdd9000 	C:\Windows\system32\CLBCatQ.DLL
0x000007fefbed0000 - 0x000007fefbf1b000 	C:\Windows\System32\MMDevApi.dll
0x000007fefc4e0000 - 0x000007fefc60c000 	C:\Windows\System32\PROPSYS.dll
0x000007fefbc10000 - 0x000007fefbc19000 	C:\Windows\system32\avrt.dll
0x0000000180000000 - 0x000000018062f000 	C:\Windows\system32\ig4icd64.dll
0x0000000019880000 - 0x0000000019ccd000 	C:\Windows\system32\ig4dev64.dll
0x000007fefb760000 - 0x000007fefb7b4000 	C:\Windows\system32\oleacc.dll
0x000007fefb210000 - 0x000007fefb25f000 	C:\Windows\system32\AUDIOSES.DLL
0x000007fef7b10000 - 0x000007fef7bac000 	C:\Windows\system32\mscms.dll
0x000007fef8490000 - 0x000007fef84d2000 	C:\Windows\system32\icm32.dll
0x000007fef6cb0000 - 0x000007fef6dd5000 	C:\Windows\system32\dbghelp.dll

VM Arguments:
java_command: <unknown>
java_class_path (initial): <not set>
Launcher Type: generic

Environment Variables:
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Users\Compaq\AppData\Roaming\npm;C:\adb;C:\Users\Compaq\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
USERNAME=Compaq
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 15 Stepping 13, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7601 (6.1.7601.23677)

CPU:total 2 (2 cores per cpu, 1 threads per core) family 6 model 15 stepping 13, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, tsc

Memory: 4k page, physical 2088248k(1279600k free), swap 4176496k(2682528k free)

vm_info: OpenJDK 64-Bit Server VM (25.72-b15) for windows-amd64 JRE (1.8.0_72-b15), built on Jan 28 2016 11:10:06 by "tester" with MS VC++ 10.0 (VS2010)

time: Wed Sep 25 15:03:38 2019
elapsed time: 2 seconds (0d 0h 0m 2s)

**Comment by Kieaer** [comment]
```
Event: 0.558 Thread 0x000000000218d000 Exception <a 'java/io/FileNotFoundException'> (0x00000000f58a29d8) thrown at [C:\jenkins\workspace\zulu8-silver-build-win64\zulu-src\hotspot\src\share\vm\prims\jni.cpp, line 709]
```

Don't run mindustry in Jenkins server

**Comment by Anuken** [comment]
Your computer doesn't support OpenGL 2; you can't run the game.

**Comment by Scawaffle** [comment]
I don't see that's the problem, I already check it that my computer graphic card are on version OpenGL 2, by OpenGL extension Viewer.. 
or should I try use the 32 bit version instead?

**Comment by Scawaffle** [comment]
how do you change the server ?

**Comment by Anuken** [comment]
I can't help you. If that error happens, then your system doesn't support the correct OpenGL 2 extensions. Changing versions won't fix this.

**Comment by Kieaer** [comment]
@Scawaffle Your PC using zulu OpenJDK (using Jenkins)
Please install __Oracle java__ or __vanilla OpenJDK__ or Reset path in command prompt.
