### ISSUE TITLE
Mindustry crashes when switching to system dark mode and vice versa 

### ISSUE THREAD

**Issue by SergSel2006** [Anuken/Mindustry#7139]
**Platform**: *Android*

**Build**: *135.2*, though, I first found this bug in 126

**Issue**: in menu, or in game, when you decided to switch to system dark or white mode, game will crash

**Steps to reproduce**: step 1) enter into the game. Step 2) switch to dark/white mode and game will crash

**Link(s) to mod(s) used**: I was playing with [ExoGenesis mod](https://github.com/AureusStratus/ExoGenesis) while I found this bug.

**Save file**: First found this problem while was in menu, so, it is happening everywhere 

**(Crash) logs**: were somehow lost, I've just tired to export crash logs and they're empty, 0 bytes long.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Have you tried without the mod?

and does it happen in bleeding edge (https:/github.com/anuken/mindustrybuilds/releases/latest) too?

**Comment by Anuken** [comment]
If there is no log, I can't fix this.
