### ISSUE TITLE
@dead status is bugged

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#7144]
**Platform**: android

**Build**: 22796

**Issue**: In v7 you made the @dead variable be true when the block is carried, but they actually not be destroyed. For example they still work on payload conveyor.
And this change caused the logic lost its binding of remote blocks when you reopen the game, because their @dead is true.

**Steps to reproduce**: 

https://user-images.githubusercontent.com/45112661/177809548-81f4bcc0-e57c-4882-8f63-bc660e63bc21.mp4

**Save file**: I think it's not related?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> And this change caused the logic lost its binding of remote blocks when you reopen the game, because their @dead is true.

No, buildings in conveyors/payloads cannot be loaded because they are not in the world anymore. All *building* variables are only saved by tile position. This is a very niche use case and I won't be changing how it works.
