### ISSUE TITLE
Payload Loader can't load multiple items

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry#7153]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Window 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
22804
**Issue**: *Explain your issue in detail.*
Payload Loader can only load container with one kind of item
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. place 2 payload loader continiously
2. load each of them with 2 different items
3. place container in
4. the second loader will be ignored

https://user-images.githubusercontent.com/43229798/178093965-e8f0988a-72a1-4d25-a5d8-e882e0c3a0c5.mp4

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
Testing Utils
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

https://drive.google.com/file/d/1NcG2E6IHPHs_tTUsJY49WF9-5NlNQdQ5/view?usp=sharing

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Payload Loader CAN actually load multiple items, last time I used it

load all the items in the _same_ loader, don't use 2 different loaders

**Comment by EclipseTheOldOne** [comment]
> Payload Loader CAN actually load multiple items, last time I used it
> 
> load all the items in the _same_ loader, don't use 2 different loaders

i know, but sometime one item can be off

**Comment by Anuken** [comment]
Not a bug. You're not supposed to be able to load multiple item types.
