### ISSUE TITLE
Vents

### ISSUE THREAD

**Issue by IvanDem2009** [Anuken/Mindustry#7154]
![зображення_2022-07-09_095637137](https://user-images.githubusercontent.com/84869683/178095330-637a427a-8641-4bab-b748-ac08d3b5064d.png)
Platform: Windows 64 bit

Build: 22804

Issue: I can see vents in editor, but I can`t see them in playtest or edit in game.
Steps to reproduce: Create a map. Place a vent. Open the map in edit in game. 

Link to mods used: https://github.com/MEEPofFaith/testing-utilities-java
https://github.com/IvanDem2009/KIKIMICI
https://github.com/BlueWolf3682/Exotic-Mod
https://github.com/sk7725/TimeControl

Save file: [mydata.zip](https://github.com/Anuken/Mindustry/files/9076022/mydata.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

Crash logs: none

---![зображення_2022-07-09_095629697](https://user-images.githubusercontent.com/84869683/178095323-34332f43-f14e-4be6-b9eb-0aa62cd71ee9.png)
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ruichka** [comment]
Vents must be 3x3

**Comment by IvanDem2009** [comment]
there`s a 3 x 3 hole

**Comment by Ruichka** [comment]
> there`s a 3 x 3 hole

You still have to make the vent 3x3

**Comment by SergSel2006** [comment]
Vents must be 3x3, but in editor it is 1x1 tile, It is confusing thing. This requires fixing in my opinion.
