### ISSUE TITLE
1 enemy core remaining but I destroyed all the cores?

### ISSUE THREAD

**Issue by fl215** [Anuken/Mindustry#7161]
**Platform**: *Windows*

**Build**: *22810 BE*

**Issue**: *Apparently, there is 1 enemy core left but I already destroyed the enemy core.*

**Steps to reproduce**: *I don't even know how I managed to do this, I just destroyed 2 turrets and somehow managed to destroy the core from above. (lake sector)*

**Link(s) to mod(s) used**: *No mods.*

**Save file**: *I can't seem to be able to upload it*

**(Crash) logs**: *no crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by fl215** [comment]
[sector-erekir-41.zip](https://github.com/Anuken/Mindustry/files/9079391/sector-erekir-41.zip)

**Comment by Anuken** [comment]
Lake sector is not supposed to be played yet.

**Comment by Bottinator22** [comment]
~~probably should've left it ununlockable~~
