### ISSUE TITLE
Crash with packet error in multiplayer when putting down logic schematics

### ISSUE THREAD

**Issue by damonsmith** [Anuken/Mindustry#7166]
**Platform**: *Linux*

**Build**: *126.2*

**Issue**: *Multiplayer has been working well for ages but recently started failing in multiplayer games when putting schematics with logic down. It shows a dialog saying "packet error" and "mismatch" and the console prints:

[E] java.io.IOException: mismatch
	at mindustry.net.Net.lambda$handleException$0(Net.java:42)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
*

**Steps to reproduce**: *join Ranked 1v1 server, play against someone, put down any schematic with logic in it. It's intermittent though, I can put down the same schematic five times and then it will fail on the sixth.*

**Link(s) to mod(s) used**: *no mods installed*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[min-crash-logs.txt](https://github.com/Anuken/Mindustry/files/9093024/min-crash-logs.txt)
[ranked-1v1-save.zip](https://github.com/Anuken/Mindustry/files/9093035/ranked-1v1-save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
126.2 is extremely outdated and has significantly different code from the alpha/master branch builds.

**Comment by LeoSko** [comment]
Also, if that happens only on one particular server (only ranked?), consider contacting owners instead (me).
