### ISSUE TITLE
OCT&DISRUPT protects each other

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry#7169]
**Platform**: Server-build

**Build**: 22823

**Issue**: The oct and disrupt would protect each other, which leads to they are stucked in the spawning point.
![image](https://user-images.githubusercontent.com/55009845/178713464-135fd7bd-c658-4156-b535-31f43aefcc40.png)

**Steps to reproduce**: Have a wave containing oct and disrupt(but without the other T5 units)

**Link(s) to mod(s) used**: None

**Save file**: 
[oct & disrupt.zip](https://github.com/Anuken/Mindustry/files/9101262/oct.disrupt.zip)

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Or if you just can't be helped, spawn other T5s in the wave
