### ISSUE TITLE
Objectives UI Map update Bug.

### ISSUE THREAD

**Issue by siede2010** [Anuken/Mindustry#7176]
**Platform**: *Windows*

**Build**: *BE-22839*

**Issue**: *New Objectives UI is not Compatible with older Maps that used Old Objectives UI.*

**Steps to reproduce**: 
1. *Make a map with an older version that didnt have the new Objectives UI that also uses it,*
2. *Save the map*
3. *Go to newest version and try to load map*

**Link(s) to mod(s) used**: *None*

**Save file**: *Singleplayer (not needed)*

**(Crash) logs**: [crash-report-07_15_2022_21_56_27.txt](https://github.com/Anuken/Mindustry/files/9123660/crash-report-07_15_2022_21_56_27.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by siede2010** [comment]
When trying to load a map that has a Old Objectives system it will crash. cant it have a backsave where it removes all Objectives or smthing like that?

**Comment by Anuken** [comment]
> When trying to load a map that has a Old Objectives system it will crash. 

If it is save/map specific then ***why did you not attach a save file when the template specifically asks for it? How do you expect me to reproduce this without your save file?***
