### ISSUE TITLE
Tech Tree Instant Completion

### ISSUE THREAD

**Issue by nak-attak** [Anuken/Mindustry#7183]
**Platform**: Windows 10 x64

**Build**: 136

**Issue**: All tech tree items that were previously partially unlocked are all fully unlocked upon updating.

**Steps to reproduce**: Updated the game from the previous alpha version to this one, and all my t5 units in the tech tree were unlocked.

**Link(s) to mod(s) used**: None

**Save file**: [3.zip](https://github.com/Anuken/Mindustry/files/9126377/3.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Unless this happens with a clean campaign save from v136, I will not be investigating this. Cross-version campaign compatibility is not very important as both campaigns have had/will have significant changes.
