### ISSUE TITLE
Entering a turret another player is inside of crashes the game

### ISSUE THREAD

**Issue by PineaFan** [Anuken/Mindustry#7184]
**Platform**: *Linux*

**Build**: *pre-alpha build 135.1*

**Issue**: *When a player (in multiplayer) is inside of a turret (e.g. Lancer), if another player tries to enter it the game crashes for the host and kicks all players*

**Steps to reproduce**: 
- Enter a block by control clicking
- Get another player to control click on the same block
- Game crashes

**Link(s) to mod(s) used**: *None*

**Save file**: [mindustry_save_07162022.zip](https://github.com/Anuken/Mindustry/files/9126408/mindustry_save_07162022.zip)

**(Crash) logs**: [crash-report-07_16_2022_14_53_16.txt](https://github.com/Anuken/Mindustry/files/9126411/crash-report-07_16_2022_14_53_16.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
135.1 is not the latest version.
