### ISSUE TITLE
Bridge Conduit Issue

### ISSUE THREAD

**Issue by SpookyCTT** [Anuken/Mindustry#7187]
Platform: Android

Build: bleeding-edge build 22823

Issue:  A few years ago and again today I have had a bit of a pickle with one of my schematics. Im not exactly sure how to reproduce it. It happens randomly in game and deleating the bridge conuits and replacing them with the same schematic fixis it but during a game it cuts off my spore supply.

Steps To reproduce: I have a image of the scamatic working and bugged in the same image. Again im not exactly sure what causes the glitch to happen but I hope you figure it out.

Save File: 🤔

Reap my soul? You use a bladed stick or a lawn mower? XD Ether way the tool turns to pudding uppon swing at me.
![Screenshot_20220716-230432_Mindustry BE](https://user-images.githubusercontent.com/109456311/179389029-b1ac5b2f-a491-4632-a65c-362e4a6a7d33.jpg)
[Logs I didnt hit with a car.zip](https://github.com/Anuken/Mindustry/files/9127202/Logs.I.didnt.hit.with.a.car.zip)

---tried uploading a log :/  'gethub'  didnt find the filetype acceptable. not sure why.  so i zipped it

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [n ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

 Anyway if you need any more info let me know.

Your game is nothing short of an art masterpeace streaching from here across thousands of lighyears of night sky on the darkest most clear night in the middle of nowhere with a Celestron telescope. (not the whole thing obviously so don't get too big a head)

Dont really feel like going into the details but your game saved my life and kepped me sane through some of the most difficult years of my life.

Thank you Anuken for this gift of unparalleled signifacance to my life and I hope you have a fantastic rest of your year. 😸

**Comment by Anuken** [comment]
> Save File

>  Template: THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME

I'm not sure how I could possibly make this any clearer at this point... You haven't specified the exact issue and I have no idea what you actually expect me to do to reproduce this issue. Even you do provide that, I need more specific details than "this schematic doesn't work sometimes".

**Comment by SpookyCTT** [comment]
^-^ Apologies for not following strictly to your template.

I don't normally get on the gethub. You have a fantastic 2 years now and because you are awesome I'll say hi every once and a while. I guess I was mistaken on how thoroughly I explained the issue.

I haven't finished standardizing my campaign yet and I wouldn't want you to see the horrors anyway.

From one to another, have a good one.

![Tar feilds](https://user-images.githubusercontent.com/109456311/179421721-5a6f7582-61b9-454e-88e3-a88bbcf8e2bb.jpg)
