### ISSUE TITLE
Glidge vulnerable

### ISSUE THREAD

**Issue by RealWetter** [Anuken/Mindustry#7194]
This glidge is op or not
Its on phone (idk on other versions)
Its in v6 126.2
Its that wan you just make an defence and you defetet an rine and you disconect and later an base attacks they sector its gone repeat they last round on some hih speed or somting 
But if you look in they sector they rounds will update agen
Thats how i got whit 3 spectres to round 173 
And i cant defeat they round 173 whit even 50 spectres so its sometimes handy and somtimes not
(Maybe i make an vid about it)
And is it an fature that someone that is admin in your compain and you send items away he will get items too and got spreat over all they cores?
Becuz maybe thats to op.
-realwetter
(I hope you cout understand this)
Sorry if not
[I dont have any mods]

**Comment by Anuken** [comment]
You deleted the template; this is not a valid bug report.

**Comment by RealWetter** [comment]
Oh i dond know how this ting/side work
