### ISSUE TITLE
The game sometimes stuck for a long period of time

### ISSUE THREAD

**Issue by Piano23** [Anuken/Mindustry#7199]
**Platform**: *Android

**Build**: 136.1

**Issue**: whenever a unit deconstruct like pulsar and poly(idk about the other units because i just started again) can make your game stuck for a long period of time

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Just deconstruct a building using a pulsar or deconstruct with the help of poly

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

Time Control

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

https://user-images.githubusercontent.com/109595655/179744210-64314890-3f22-4549-8a8a-03c6e36c2110.mp4

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

> 

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Piano23** [comment]
The poly version btwhttps://user-images.githubusercontent.com/109595655/179747129-f9f78472-8367-4db6-8dba-87754ffba8e3.mp4

**Comment by Anuken** [comment]
> The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. 

![2022-07-19-08-41-04](https://user-images.githubusercontent.com/10100000/179752708-8dc730ae-f269-4ecc-b939-01fa61ab5ae1.gif)

Cannot reproduce issue.

**Comment by BlueWolf3682** [comment]
Look closer at the video - the pulsar appears to be... getting stuck in a wierd state of boosting on the node? I'm not sure how it affects building (and it may not at all) but it's interesting behaviour.

**Comment by Anuken** [comment]
I could reproduce that, but it looks unrelated.
