### ISSUE TITLE
Units Stuck

### ISSUE THREAD

**Issue by tomoeuehara** [Anuken/Mindustry#720]
**Platform**: Android

**Build**: Rev95

**Issue**: Map name: Overgrowth.
The enemies came in bulk and started shooting my walls, but as soon as more enemy waves come and collide, they don't go anywhere, just swarming on a spot and do nothing. They could still attack, but did not advance to my home base.
And also, the FPS drops from 50-60 to just 1-2 FPS...

**Screenshot**: https://ibb.co/D4n59bC

**Steps to reproduce**: Just wait for enemies to came in large number on 1 wave, and as soon as the numbers high enough, the bug happens.

**Comment by Anuken** [comment]
Have you upgrades to 95.4?

**Comment by tomoeuehara** [comment]
I downloaded from Google Play Store, on the intro screen it only says "release build 95" without the .4
So I'm not quite sure on which version now.

**Comment by Anuken** [comment]
Check Google Play and the application info, it should display the version.

**Comment by Famous5000** [comment]
I have this issue as well on my laptop. They get stuck at random times with doors if that helps at all. Sent from my T-Mobile 4G LTE Device
null

**Comment by Anuken** [comment]
Again, I need to know the exact number of release you have.

**Comment by Anuken** [comment]
I'll assume this is fixed, unless someone else reports it for 96.
