### ISSUE TITLE
区块波次出现问题

### ISSUE THREAD

**Issue by chenyning** [Anuken/Mindustry#7212]
**Platform**: *Android*

**Build**: *136.1*

**Issue**: *战役模式，233区块229区块波次出现发生了问题*

**Steps to reproduce**: *当我选择这两个区块的时候第一波就会把全部的敌怪放出来*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by PCX-LK** [comment]
同志，在这里反馈问题需要使用英文🤔

**Comment by PCX-LK** [comment]
Anuke不会中文）
建议机翻）

**Comment by chenyning** [comment]
行
