### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by LIXEROGE** [Anuken/Mindustry#7214]
**Platform**: `Windows 7 x64`

**Build**: `alpha build 136.1`

**Issue**: *I captured Overgrowth and 133 on 135.1 2 weeks ago. Today  I updated my Mindustry to 136.2 and went  into Overgrowth and 133 and created some buildings.Then I returned to 135.1 (didn't close 136.2) but I found that 133 and  Overgrowth becomes uncaptured. I tried go into 135.1 and 136.2 some times ,but it doesn't work.*

**Steps to reproduce**: *emm...(~~looks like i wrote it on Issue~~)*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened.?~~I don't understand~~
I'm only playing Mindustry.
*

**Crash report**: *It havn't any crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Then I returned to 135.1

This is not supported. Don't do that.
