### ISSUE TITLE
Roboticist achievement not being granted if units are built over multiple sessions

### ISSUE THREAD

**Issue by madmagic007** [Anuken/Mindustry#7217]
**Platform**: *Windows 11*

**Build**: *126.3.*

**Issue**: *Building all the units across multiple sessions doesnt grant the achievement and will sometimes even decrease the achievement progress counter on steam. The Achievement name / description makes it sound like it is overall so either the name / description should be changed or this is a bug*

Edit: Reading the discord it looks like many people had this issue in the past but has just been ignored, i dont know if for them this is across multiple sessions too tho

Using a bit of code i printed the unit counts on the current map to show all 30 types are present (planetary launch terminal): 
![image](https://user-images.githubusercontent.com/51405665/180220381-0ef10822-a405-467f-b20c-532b09ec09f3.png)

**Steps to reproduce**: *Kinda hard to explain how to reproduce like this but this is how it happened to me: 
Play game with achievement not unlocked, build all land and air units on a map without water over multiple sessions (some of the units were not unlocked so i unlocked them in that session while building others), in a different session go to a map with water and built all water units, it only showed 18/30. Went to to planetary launch terminal in another session and captured it having built only 2 types of units (poly and corvus). Next session it said 20/30, build all units except the 2 already present on the map, stuck at 28/30, building the already built 2 units it stays at 28/30*

**Link(s) to mod(s) used**: *N/A*

**Save file**: Map with all 30 units being present, same map as the screenshot:
[sector-serpulo-93.zip](https://github.com/Anuken/Mindustry/files/9159608/sector-serpulo-93.zip)

**(Crash) logs**: *N/A*

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> 126.3.

This is an extremely outdated version (released over a year ago). The beta/alpha versions have different code that may affect this.

**Comment by Anuken** [comment]
I only care about the latest version *because that's the version I am developing.* It doesn't matter to me if *only* the latest stable version has some bug, because the *unstable* version will replace it anyway. That's why the template has a checkmark for it - you did not, in fact, use the latest version here. **Reports for older versions are not useful.**
