### ISSUE TITLE
All power nodes, bridges, and conveyors disconnected after losing sector

### ISSUE THREAD

**Issue by richlalsingh** [Anuken/Mindustry#7219]
**Platform**: Windows

**Build**: steam build 136.1

**Issue**: When returning to a lost sector. All the power nodes, bridges, and phase conveyors that were not destroyed are disconnected. Bridge and phase conveyors that are rebuilt by polys are also disconnected. 

**Steps to reproduce**: Lose a sector, then return to it

**Link(s) to mod(s) used**: No mods

**Save file**: [serpulo-70.zip](https://github.com/Anuken/Mindustry/files/9163218/serpulo-70.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This mechanic may not remain at all, so I won't be changing anything about it.
