### ISSUE TITLE
Surge Router

### ISSUE THREAD

**Issue by SoMall-dumpling** [Anuken/Mindustry#7223]
**Platform**: W

**Build**: 136.1

**Issue**: Surge Router sometimes does not equally distribute items.

**Steps to reproduce**: ![image](https://user-images.githubusercontent.com/57857764/180403789-06c991f5-d23a-4146-95d0-d092d28db759.png)
Don't know why. Sometimes it works fine, but sometimes it won't.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.
