### ISSUE TITLE
JS errors in ContentInitEvent crash the game

### ISSUE THREAD

**Issue by Fabizocker456** [Anuken/Mindustry#7224]
**Platform**: *Android + Windows (others untested)*

**Build**: *BE build 22871 (and some others before)*

**Issue**: *When loading a mod that generates an ECMAError in a function registered for ContentInitEvent, the game crashed (and displays the ECMAError in the popup on windows). This also triggers auto mod disabling, which is quite annoying, as I like to play with >5 utility mods loaded.*

**Steps to reproduce**: *Simply start a game with a mod loaded that generates a ECMAError in a function registered for a ContentInitEvent (not invalid syntax, as that simply prevents the mod from loading). Example:* `{"not":"valid"}["function"]()`

**Link(s) to mod(s) used**: *Private mod which has since been lost to time*

**Save file**: *not applicable here*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *(with testing mod which contains `"yeet"()` on android) https://www.toptal.com/developers/hastebin/itucuvijic.yaml*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed. (using BE)**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Mod bug, not game bug.
