### ISSUE TITLE
Hidden building in the onset campaign

### ISSUE THREAD

**Issue by Piano23** [Anuken/Mindustry#7228]
**Platform**: Android

**Build**: 136.1

**Issue**: while i was clearing some buildings in onset i encounter a hidden building in the other side of the final core 

**Steps to reproduce**: I just deconstructing and the hidden buildings on the other side got viewed

**Link(s) to mod(s) used**: 
Time Control

**Save file**: 

https://user-images.githubusercontent.com/109595655/180589865-79f816bf-2c77-4340-baf4-74eb38e391ab.mp4

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SoMall-dumpling** [comment]
Because there are actually some other buildings there.
You can download the map to see them. There are actually two more enemy bases, anuke delete them. But he didn't delete the facilities. So you can capture the sector by destroying the two bases in sight, but there are still some other buildings.

**Comment by Piano23** [comment]
Oh
