### ISSUE TITLE
Conveyor connection between `tetrative reconstructor` and `exponential reconstructor` not always working

### ISSUE THREAD

**Issue by shangjiaxuan** [Anuken/Mindustry#7231]
**Platform**: Windows

**Build**: 136.1

**Issue**: Conveyor connection between `tetrative reconstructor` and `exponential reconstructor` not always working (seems not to happen with land units).

**Steps to reproduce**: creative mode, empty map, use payload source for reproducing simplicity. Create two upgrade factories and connect them with payload conveyor. Use payload source to give `Mega` units

**Link(s) to mod(s) used**: No mod.

**Save file**:  https://github.com/shangjiaxuan/SmallFileShares/blob/master/minimal.msav?raw=true
---
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
This isn't a bug
T4 and especially T5 units tend to be too big for payload conveyors
Connect exponential reconstructors to tetrative reconstructors directly by placing them next to eachother

**Comment by shangjiaxuan** [comment]
T4 factory output way faster than T5 factory (90s vs 240s), directly connecting them will practically rule out the possibility of releasing overflow units into the field, not really automatic if you have to manually change output direction of T4 factory. (Does logic have a command for changing output direction?)

**Comment by SoMall-dumpling** [comment]
![image](https://user-images.githubusercontent.com/57857764/180634531-adc40e4c-65ed-4c9b-83aa-19625a406022.png)
![image](https://user-images.githubusercontent.com/57857764/180634542-0ef890d4-131e-4ff0-910e-ba825eca9262.png)
Quad is bigger than 3x3, so the conveyor can't hold it.

**Comment by shangjiaxuan** [comment]
Here is a logic processor that should work. Change the rotation as needed.
```
sensor working reconstructor2 @payloadCount
sensor rot1 reconstructor1 @rotation
op equal is_linked rot1 2
op land need_unlink is_linked working
jump 12 notEqual need_unlink true
sensor rec1_type reconstructor1 @type
sensor rec1x reconstructor1 @x
sensor rec1y reconstructor1 @y
ubind @poly
ucontrol build rec1x rec1y rec1_type 1 0
ucontrol unbind 0 0 0 0 0
jump 22 always x false
op notEqual not_linked is_linked true
op notEqual not_working working true
op land need_link not_linked not_working
jump 22 notEqual need_link true
sensor rec1_type reconstructor1 @type
sensor rec1x reconstructor1 @x
sensor rec1y reconstructor1 @y
ubind @poly
ucontrol build rec1x rec1y rec1_type 2 0
ucontrol unbind 0 0 0 0 0
end

```
