### ISSUE TITLE
Having mono being freeze 

### ISSUE THREAD

**Issue by Kevinindo02** [Anuken/Mindustry#7233]
**Platform**: Android/Ram 2 GB

**Build**: 22891

**Issue**: having many poly being freeze

**Steps to reproduce**: just having many poly and destroy some block being freeze (for building i don't tested yet)

**(Crash) logs**: i don't have it it freeze not crash

**Comment by BlueWolf3682** [comment]
you have made a grave mistake

**Comment by Mythril382** [comment]
in games, having many entities lag or even freeze a game, especially with 2gb of ram
