### ISSUE TITLE
not an in-game bug

### ISSUE THREAD

**Issue by misaga15** [Anuken/Mindustry#7237]
I have attempted to join your discord server many times but I can't.
I know it's not a bug and I'm sorry for using this platform but I didn't where else could I go, as I did not find a way to communicate through discord.

**Comment by Rex-Hm** [comment]
Send your discord id.

to get it you must go to UserSettings>Advanced and enable Developer Mode, then send a message in any channel/group/md and right-click on your profile picture, select "Copy ID" and send it here.

**Comment by end-me-please** [comment]
@Ilya246 @BasedUser
