### ISSUE TITLE
Erekir liquid tank bug

### ISSUE THREAD

**Issue by ashybashy22** [Anuken/Mindustry#7238]
**Platform**: *Windows*

**Build**: *22891*

**Issue**: *when you pick up a liquid tank with a unit it dupes the liquid tank when you put it down, however the liquid inside is duducted from the tank you picked up from*

**Steps to reproduce**: *just pick up the smaller of the liquid tanks and place it down, bam you now have 2*

**Link(s) to mod(s) used**: *i did have the time control mod on but i doubt thats a culprit*

**Save file**: *
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by FredsMedia** [comment]
3 things, 1 no save file, 2no crash log and 3 you added a space between the brackets.

**Comment by Anuken** [comment]
![2022-07-28-09-21-47](https://user-images.githubusercontent.com/10100000/181515596-09a2c913-1f95-41f4-84ea-28bd5feb9b8a.gif)

No issues here.

**Comment by ashybashy22** [comment]
Just realized it was because I  was in a multiplayer server that had the tank not supposed to be moved and preplaced. The server was an attack one and the map was like a plague that kept growing. The tank I was picking up was part of a way to get the latum when you filled it with cyanogen. So my mistake for not being more clear. I don’t know if there is a way to fix it but that’s how I found it.
