### ISSUE TITLE
Multiplayer error in android 

### ISSUE THREAD

**Issue by Orange1118** [Anuken/Mindustry#7245]
**Platform**: *Android*

**Build**: *22819*

**Issue**: *Attempt to invoke interface method 'java.lang.Object arc.func.Prov.get()'on a null object reference
**Steps to reproduce**: *i exited the game, opened google, opened the game again and join 
ed the nydus server then loading failed then the error occured.*

**Link(s) to mod(s) used**: *none.*

**Save file**: *None.*

**(Crash) logs**: *The error did not crash the game.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Template not filled in, entire log not provided.
