### ISSUE TITLE
[MacOS] Random crash multiplayer 126.2

### ISSUE THREAD

**Issue by FredsMedia** [Anuken/Mindustry#7246]
**Platform**: *Mac*

**Build**: *126.2.*

**Issue**: *Mindustry just crashed randomly while playing multiplayer, thought I would share the log just in case.*

**Steps to reproduce**: *Playing multiplayer with friend and crashed.*

**Link(s) to mod(s) used**: *Im not linking all but I was using advanced-dev-mode:1.2, pictologic:1.5.8, simplistic:0.8.1, testmod:1, time-control:0.2, ui-lib:2.16.6, pictocanvas:2.5.8, vanilla-extended:1.82, goldmod:2.0 alpha b19, hackforall:0.1, infinity-cheat:2.1.444, invincible-cheat-mod-v6:2.8.4, moardustry:0.10, revision:12.5 (Only testmod, pictologic, ui-lib and simplistic were activated at the time. testmod is something my friend made).*

**Save file**:
[saves.zip](https://github.com/Anuken/Mindustry/files/9204265/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. (noted)

**(Crash) logs**:
[crash-report-07_28_2022_09_48_33.txt](https://github.com/Anuken/Mindustry/files/9204270/crash-report-07_28_2022_09_48_33.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported. *(I think)***

Sorry if something is wrong my end or I waste your time I'm new to GitHub reporting

**Comment by end-me-please** [comment]
You don’t have the latest version (136.1)

**Comment by FredsMedia** [comment]
whoops... sorry.
