### ISSUE TITLE
Emptiness

### ISSUE THREAD

**Issue by Prosphyte** [Anuken/Mindustry#7255]
**Platform**: `Android `

**Build**: `alpha build 136.1`

**Issue**: *sound will eventually disappear.*

**Steps to reproduce**: *wear earphone (propably wear any bluetooth sounds) and I click settings , mod, "i", (main menu) propably there's more.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *I, in my exalted wisdom, That I indeed sure it does not happend ingame.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Frankly, I'm just not going to fix this. Sounds like another super-specific Android sound bug, and that version is of very little priority anyway.

**Comment by Prosphyte** [comment]
> Frankly, I'm just not going to fix this. Sounds like another super-specific Android sound bug, and that version is of very little priority anyway.

Only happens in beta do, and save doest seem to work. Game shows file but when i look on ZArchiver nothing shows.
