### ISSUE TITLE
Briges and Power nodes not linking

### ISSUE THREAD

**Issue by Neil2101** [Anuken/Mindustry#7259]
**Platform**: *Windows*

**Build**: BE build 22902

**Issue**: Bridges and power nodes don't link up when rebuilt by polys or via base schematic

**Steps to reproduce**: deploy into a sector with a base schematic with bridges or power nodes in it or recapture a sector that has power nodes destroyed, and see that the bridges aren't linked properly
**Link(s) to mod(s) used**: vanilla

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/9227160/bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. (sheesh anuke, we know)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Everything links up correctly on my end. Are you really using vanilla?

![image](https://user-images.githubusercontent.com/10100000/182007192-b1d1d01c-f729-4051-abc6-f64ed81b7fed.png)

**Comment by Neil2101** [comment]
and I meant that they don't link up automaticly after bieng rebuilt by polys like this
![image](https://user-images.githubusercontent.com/66876298/182030752-2f279dc3-ac68-4bb4-8f5e-a7a07425230c.png)

**Comment by Anuken** [comment]
I don't have such an issue, they link up correctly as shown in my screenshot.
