### ISSUE TITLE
Fastlane files incomplete

### ISSUE THREAD

**Issue by rnauber** [Anuken/Mindustry#726]
**Platform**: Android
**Build**: v95
**Issue**: 
I was asking at F-Droid why Mindustry does not show up on their curated "latest apps" list:
https://forum.f-droid.org/t/mindustry-not-showing-up-in-latest-apps/7378

It was mentioned that:

1. there is no summary.txt at https://github.com/Anuken/Mindustry/tree/master/fastlane/metadata/android/en-US
2. The changelogs corresponding to the build codes are missing, e.g. "89.txt" at  https://github.com/Anuken/Mindustry/tree/master/fastlane/metadata/android/en-US/changelogs 

If this is fixed, Mindustry might gain some visibility in the F-Droid store...

Thank you,
Richard

**Comment by Anuken** [comment]
Is the summary F-Droid specific? Fastlane didn't grab it from Play, and as far as I know it's not needed there.

Do the changelogs need to be retroactive? I could set up a changelog copy system.

**Comment by rnauber** [comment]
> Is the summary F-Droid specific? Fastlane didn't grab it from Play, and as far as I know it's not needed there.
Reading https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/update.py#L964 makes me think that 'short_description.txt' is equivalent to 'summary.txt'. So I think this is ok, as is.

> Do the changelogs need to be retroactive? I could set up a changelog copy system.

Well, I  guess a changelog for all versions on F-Droid would suffice. So we need v89, v93 and v94...
I think that this is the last missing piece for getting onto the "latest apps" list!

**Comment by Anuken** [comment]
Added.

**Comment by rnauber** [comment]
Hi @Anuken,
for some reason Mindustry is still not listed in F-Droids "latest apps" and the discussion here is inconclusive:
https://forum.f-droid.org/t/mindustry-not-showing-up-in-latest-apps/7378/10

I suspect that the changelog for the latest release has to be present in the fastlane folder **before** the commit is tagged. So could you please add a 100.txt **before** tagging the v100 release?
Then Mindustry will be visible on the front page of F-Droid.

Thank you very much,
Richard
