### ISSUE TITLE
Scathe shooting both ground and air units

### ISSUE THREAD

**Issue by renebrucknerjnr** [Anuken/Mindustry#7268]
**Platform**: *Windows*

**Build**: *136.1*

**Issue**: *Scathe shooting both ground and air units while the description says it only targets ground units.*

**Steps to reproduce**: *Had a power source next to it, two item sources one with Tungsten and the other with Carbide and two liquid sources, both with water.   On a custom map I made in the editor.*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *Sorry I don't understand what I should do here.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *No crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Scathe shooting both ground and air units while the description says it only targets ground units.

![image](https://user-images.githubusercontent.com/10100000/182048332-83f96349-911f-4eb9-a482-c168eb3fad88.png)

It does not target air units. I am an air unit, and it is not shooting me.

> Had a power source next to it, two item sources one with Tungsten and the other with Carbide and two liquid sources, both with water. On a custom map I made in the editor.

Those are not the steps to reproduce. You do not mention what units you used, or what made you think it targeted them.
