### ISSUE TITLE
Crash When joining server

### ISSUE THREAD

**Issue by xicscon** [Anuken/Mindustry#7272]
**Platform**: *Android*

**Build**: *Alpha build 136.1*

**Issue**: *When I joining to server Mindustry crashing*

**Steps to reproduce**: *Find server "DarkDustry Castle Wars and join*

**Link(s) to mod(s) used**:

**Save file**: 
[02.08.zip](https://github.com/Anuken/Mindustry/files/9241474/02.08.zip)

**(Crash) logs**: 
[02.08.txt](https://github.com/Anuken/Mindustry/files/9241481/02.08.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already reported/fixed.
