### ISSUE TITLE
i dont know wat is it

### ISSUE THREAD

**Issue by MontraguExolum** [Anuken/Mindustry#7275]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[The Slaylord/basic-schematics:1, wizer/extended-ui:0.63, QmelZ/hackustry:4, pixecoz/maps-pack:1, Pietro/modding-tools:0.1, RTOmega/more-servers:1.0, DeltaNedas/override-lib:1.0.1, SpaceEarthEX/zenith-gaming:0.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.*
[crash-report-08_02_2022_21_29_52.txt](https://github.com/Anuken/Mindustry/files/9245159/crash-report-08_02_2022_21_29_52.txt)
*

**Comment by end-me-please** [comment]
Outdated version, no steps to reproduce, probably a mod issue anyways
