### ISSUE TITLE
After game crash all sectors in campaign are under attack!

### ISSUE THREAD

**Issue by CellTaur** [Anuken/Mindustry#7276]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *Problem 1: Game crashes and brings my whole computer down with it!
Problem 2: All of my sectors in campaign are now under attack! + all the names and icons are reset for every sector.
As if that wasn't enough, the tech tree was also reset.*

**Steps to reproduce**: *Problem 1: Cause of crash is unknown. Usually to fix this I simply unplug the computer from the power source. This does not happen anywhere else, only when playing this game specifically and has never ever happened to me before.
Problem 2: After I rebooted my computer and launched the game, suddenly all sectors became under attack! This has happened before, but just once and at the time I have not thought much of it. Now I can clearly see that this is an often occurring problem, please fix!
Other than that, great job devs for making such a fun game I really enjoy it, even if it crashes.*

**Link(s) to mod(s) used**: `none`

**Save file**: *I don't know the sector's number since it only gives me the name: "Stained Mountains". Therefore I will send all the sectors in my campaign I have.
[saves.zip](https://github.com/Anuken/Mindustry/files/9246325/saves.zip)*

**Crash report**: *When game crashes (and my pc with it) no logs are being given/saved. Therefore I can't give any.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
126.3 is not the latest version, so I cannot use this report. Your game data has been wiped; this is a known issue, and there is no way to get it back.
