### ISSUE TITLE
Tutorial text in Erekir are pixelated by a setting

### ISSUE THREAD

**Issue by TheMrAlbert** [Anuken/Mindustry#7278]
**Platform**: iOS, this also affects Windows and Android

**Build**: 136.1

**Issue**: Tutorial texts in The Onset (Erekir) are pixelated when Pixelated is on. Requiring to turn off pixelated to view them.

**Steps to reproduce**: Start campaign from The Onset (Erekir), turn on pixelated in Settings > Graphics

**Link(s) to mod(s) used**: None

**Save file**: 
I knew this was mandatory...
[Mindustry 03 August 2022.zip](https://github.com/Anuken/Mindustry/files/9247903/Mindustry.03.August.2022.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I'm not going to fix this. If you want to read the text, stop using that setting. If more people complain, I'll just remove that setting, because it has always looked horrible anyway.

**Comment by Moth-Tolias** [comment]
happens on serpulo as well, not just erekir.

> I'm not going to fix this. If you want to read the text, stop using that setting. If more people complain, I'll just remove that setting, because it has always looked horrible anyway.

😞

my computer isn't powerful enough to run mindustry at a decent fps without the pixelate setting enabled. i have no earthly idea as to why adding an effect would speed it up so much, but it means that i have to choose between the game running well and being able to read text. switching all the time is tiresome.
