### ISSUE TITLE
serpulo's turret won't attack some erekir's blocks and core units

### ISSUE THREAD

**Issue by Linnnnnna** [Anuken/Mindustry#7294]
**Platform**: *windows*

**Build**: *137*

**Issue**: 
![a](https://user-images.githubusercontent.com/63439268/182983676-5bb8393e-8230-472f-ab68-5644a3f33e9b.png)

**Save file**: *[a.zip](https://github.com/Anuken/Mindustry/files/9264598/a.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
These blocks are seen as "under" units, so you need to specifically aim at them to hit them
Turrets likely don't aim at them to avoid wasting ammo on them

**Comment by Jackson11500** [comment]
feature not bug
