### ISSUE TITLE
Random crashes.

### ISSUE THREAD

**Issue by Plastel** [Anuken/Mindustry#7295]
**Platform**: `Android 29`

**Build**: `bleeding-edge build 22942`

**Issue**: When i play mindustry the game randomly freezes OR crashes

**Steps to reproduce**:you literally do nothing special, just play the game normally and in some moment the game will crash or freeze**

**Link(s) to mod(s) used**: `[[green]Snake[white] & [red]Super[green]Jaba[red]2000/adc:15.0, Tayros/theangelurd/additional-content:0.4.1, Eclipse & Liplum/avkott:0.1, [brick]paulieg626/cheat:2.3, deltanedas/dev-mode:3.3.2, KayAyeAre/dusted-lands:0.22, Emanuel G/erekir-expansion:0.65 Pre-Alpha, [#42a5f5]Liplum[]/multi-crafter:1.0, [#fed27f]S[][#fed27f]t[][#a9aabf]a[][#7e96df]B[][#7090ea]U[]

[#7f7f7f]Сontributors:[] 
[#735384]Dj-Silin, [#e4b400]MissionaryPoseBest, [#3498db]SUS[], yesC48./ol:0.5, pixecoz/schematics-pack:9, Evo04Taser/super-cheat:1.2.7, [#FCC21B]MEEP of Faith/test-utils:42, sk7725/time-control:0.2, deltanedas/ui-lib:3.16.6, deltanedas/unit-factory:3.5.0]`

**Save file**: 
[crash export .zip](https://github.com/Anuken/Mindustry/files/9265082/crash.export.zip)

**Crash report**: attached file 
[crash_1659201949287.txt](https://github.com/Anuken/Mindustry/files/9265075/crash_1659201949287.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You have far too many mods enabled. Not a vanilla bug.

**Comment by liplum** [comment]
It's because the function head, `private void githubImportMod(String repo, boolean isJava, @Nullable String release)`, has changed  in v136.
But I don't know the mod whose name has `Mindy`.
