### ISSUE TITLE
Flux Reactors can work when they are disabled and without any cyanogen

### ISSUE THREAD

**Issue by squi2rel** [Anuken/Mindustry#7296]
**Platform**: Windows

**Build**: 137

**Issue**: flux reactor can gene power when it is disabled and without any cyanogen

**Steps to reproduce**: place a flux reactor and disabled it with processor,then give it heat

**Link(s) to mod(s) used**: nope

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/9265078/bug.zip)

![image](https://user-images.githubusercontent.com/102400902/182998500-6af68f75-80d7-4242-9734-bee74f27ca86.png)
![image](https://user-images.githubusercontent.com/102400902/182998515-61c908fa-08f7-496c-888b-b769ed036f2d.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Erekir content is not designed to be used with Serpulo, this isn't as likely to get fixed. Then again, world processor disabling flux reactors might be used in maps eventually.

**Comment by SoMall-dumpling** [comment]
Serious bug. I think it must be fixed.

**Comment by Bottinator22** [comment]
In Erekir it isn't even possible to disable flux reactors

**Comment by Cry0flu1d** [comment]
> Erekir content is not designed to be used with Serpulo, this isn't as likely to get fixed. Then again, world processor disabling flux reactors might be used in maps eventually.

although this bug will **not** affect campaign or single-tech custom map , but this will heavily affect power generation in double-tech custom map.
if you consider this as a feature , it will be truly imbalanced, just like source blocks in non-sandbox maps.
