### ISSUE TITLE
Duct bridges wont automatically getting placed when its on a reinforced conduit or bridge sometimes

### ISSUE THREAD

**Issue by FunkyPotao** [Anuken/Mindustry#7298]
**Platform**: Windows

**Build**: 137

**Issue**: when i try to make ducts over reinforced conduit it sometimes doesnt create a bridge

**Steps to reproduce**: i just played some erekir and it happend wich annoyed me

**Link(s) to mod(s) used**: sheme size

**Save file**: https://drive.google.com/file/d/1sEdd7S3Ijyzsg0gzw_mprOATHbdGI7-a/view?usp=drivesdk

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works for me. Provide an actual screenshot and/or vanilla client.

![image](https://user-images.githubusercontent.com/10100000/183088943-4c928cf7-701d-4682-9bb8-7c5067184a53.png)
