### ISSUE TITLE
Orange iron

### ISSUE THREAD

**Issue by subchannel13** [Anuken/Mindustry#73]
When it comes to resources traveling on conveyor belt there a lot of shades of grey: dark grey stone, light grey iron, very light grey steel. It would help a bit if one those items had more distinguishing colors. Iron is good candidate, deposit is orange it would be perfectly intuitive for a player if mined iron ore was of the same orange color.

**Comment by Anuken** [comment]
Already implemented in the latest beta.
![screenshot from 2018-01-16 12-44-50](https://user-images.githubusercontent.com/10100000/35070757-5c6e4ec8-fbac-11e7-871e-4da61de18639.png)

**Comment by Luxray5474** [comment]
Nice
