### ISSUE TITLE
Game freezes when destroying blocks

### ISSUE THREAD

**Issue by NIK3O3** [Anuken/Mindustry#7300]
**Platform**: *Android*

**Build**: *137*

**Issue**: *Game freezes and don't response on touches when destroying block with resources in it. It may be a drill, vault, etc*

**Steps to reproduce**: *You can start with sector 70 from my savefile and try to destroy magnetic cannon. Game may freeze.*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *
[mindustrysaves17.zip](https://github.com/Anuken/Mindustry/files/9268263/mindustrysaves17.zip)
*

**(Crash) logs**: **

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 3Snake3** [comment]
You mean mass driver? Electromagnetic catapult on the Russian

пт, 5 авг. 2022 г., 19:53 NIK3O3 ***@***.***>:

**Comment by Anuken** [comment]
Duplicate. Still can't reproduce.
