### ISSUE TITLE
Objectives not available on mobile

### ISSUE THREAD

**Issue by Nunting** [Anuken/Mindustry#7306]
**Platform**: *Android/iOS/Mac/Windows/Linux*

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Be 22960

**Issue**: *Explain your issue in detail.*

![Screenshot_20220806-102822_Mindustry BE](https://user-images.githubusercontent.com/77824588/183228286-44485fdf-711d-4e16-bee9-e88955af6130.jpg)

If i add something from objectives, I can't see anything. Like the picture.
I can add someting. Next, All I can do is cancel and back.
확인(Check or yes... something) is not pressed.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

There was the same problem with BE, which came out a few weeks ago. This is a pretty old problem.

And this problem will only happen on mobile. In the past, it was confirmed that it can be seen normally on the PC screen.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Nunting** [comment]
I don't see what I added.

**Comment by Anuken** [comment]
@GlennFolker  ?

**Comment by Anuken** [comment]
Tested; it looks like you just aren't using the system correctly. You must tap a location to add something, it works on my phone. Another matter is that the scaling of UI is completely broken (Scl.scl is not respected).
