### ISSUE TITLE
Elecom mouse button remapping does not function in menu or gameplay

### ISSUE THREAD

**Issue by jweather** [Anuken/Mindustry#7308]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: Elecom mouse button remapping does not function in Mindustry

**Steps to reproduce**: I have an Elecom Deft trackball, and I use ELECOM Mouse Assistant 5 to remap the left-click button to one I can reach with my finger, Button 5.  Mindustry is the only application or game I have encountered that ignores the remapping.  It only works with the original left mouse button.

I did try the Settings/Controls to remap left click, but it doesn't even detect when I click button 5, whether ELECOM Mouse Assistant is running or not.

**Link(s) to mod(s) used**: `none`

**Save file**: Happens in the menu on a fresh start...

**Crash report**: 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/116757/183231826-907a19dc-532c-4414-969c-127f3eecc96e.png)

**Comment by Anuken** [comment]
This is far too specific of an issue for me to fix. I do not have this mouse and I do not support it.
