### ISSUE TITLE
Game lags heavily during an attack

### ISSUE THREAD

**Issue by liorabel** [Anuken/Mindustry#731]
**Platform**:
Android 10

**Build**:
build 95

**Issue**:
I am playing the campaign and this happens in every map so far. Whenever the enemy starts attacking during a wave, the game slows down considerably. The slowest I've seen was about 1 frame every 3 seconds or so. This lag seems to get worse the more enemies are involved in an attack.
I do not know if my own defences make a difference here, but my suspicion is that the shots themselves are what is causing the severe lag. Quite possibly something related to target and hit calculations?
Once all enemies are killed, the game returns to its regular smoothness.
I'm playing on a Pixel 3 phone with Android 10, so this is definitely not a hardware, CPU, or GPU issue.

**Steps to reproduce**:

1. Start a new campaign map. Even the first Ground Zero one will do.
2. Wait for the first enemy wave and go fight them with your mech/drone.
3. Behold as you start to lose frames and the game lags considerably until they are all dead.
4. Kill all enemies and watch the framerate return to normal.

**Comment by Anuken** [comment]
This is a known bug with Android 10's sound system. A workaround is to turn off sound effects in the settings.

The Android team has confirmed this as an issue; see [this.](https://github.com/libgdx/libgdx/issues/5786).

**Comment by ZkyLB** [comment]
~~what do i do if the game lags for no reason while doing nothing without anything happening on the background~~

**Comment by Anuken** [comment]
perish

**Comment by Lucas559-noob** [comment]
for me it starts lagging when there are over 150 enemies on the map, but I think it's a lot of shooting and particles
