### ISSUE TITLE
Units can carry items without cooling time

### ISSUE THREAD

**Issue by squi2rel** [Anuken/Mindustry#7310]
**Platform**: *Windows*

**Build**: *137*

**Issue**: *use processor can let units carry items without cooling time*

**Steps to reproduce**: ![image](https://user-images.githubusercontent.com/102400902/183233963-59101660-a9aa-432e-901f-33e7dcccb1f5.png)

**Link(s) to mod(s) used**: none

**Save file**:  [bug.zip](https://github.com/Anuken/Mindustry/files/9274395/bug.zip)

![1659760651719 00_00_00-00_00_30](https://user-images.githubusercontent.com/102400902/183234244-b6ba8d96-d027-461c-adef-ab193e428b50.gif)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Jackson11500** [comment]
**The smallest 9 silicon-arc factory!!!**
![image](https://user-images.githubusercontent.com/55009845/183235106-ec6935cd-973c-4b97-a234-cb4936296067.png)

**Comment by bend-n** [comment]
By the way you can put units into a payload conveyor, then their cooldown gets reset
