### ISSUE TITLE
Where is efficiency?

### ISSUE THREAD

**Issue by NIK3O3** [Anuken/Mindustry#7315]
**Platform**: *Android*

**Build**: *137*

**Issue**: *I can't see efficiency of cultivator when building. Although of water extractor*

**Steps to reproduce**: *I wanted to build some high-efficiency cultivators, but I can't. You can start any custom map and try to build cultivator*

**Link(s) to mod(s) used**: *Vanila*

**Save file**: *
[Uploading mindustrysaves17.zip…]()
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by NIK3O3** [comment]
Here is a screenshot:
![Uploading Screenshot_2022-08-06-13-35-14-205_io.anuke.mindustry.jpg…]()

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/183259307-be939a17-5ad1-4477-ab8e-6a42682d0cbd.png)

I can see it. You have not uploaded a screenshot.
