### ISSUE TITLE
Bug with Exporting Saves

### ISSUE THREAD

**Issue by xlPekkalx** [Anuken/Mindustry#7316]
**Platform**: `iOS x32`
IOS 15.6
**Build**: `release build 126.3`
Release build 126.3
**Issue**: *Explain your issue in detail.*
I can't export files, it says this (open failed: EMFILE (too many open files) and I don't know how to fix this or if I even can fix it
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
By attempting to export my progress 
**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
I never imported or exported my current progress
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by xlPekkalx** [comment]
Do you know how to fix this? If so, please send me an email

**Comment by Anuken** [comment]
126.3 is an extremely outdated version, either wait for the update or use the [TestFlight](https://testflight.apple.com/join/79Azm1hZ) version.
