### ISSUE TITLE
not router

### ISSUE THREAD

**Issue by squi2rel** [Anuken/Mindustry#7321]
**Platform**: *Windows*

**Build**: *137*

**Issue**: *The schematics and settings button isn't router in router language*
![image](https://user-images.githubusercontent.com/102400902/183316269-72f530cc-76ee-4ddc-9187-48c9325fcd30.png)

**Steps to reproduce**: *switch language to router*

**Link(s) to mod(s) used**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **router**

**Comment by SoMall-dumpling** [comment]
router router. router router router

**Comment by Anuken** [comment]
Too bad.
