### ISSUE TITLE
Can't bootstrap after BE auto update.

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry#7324]
**Platform**: Windows 11 with openjdk11

**Build**: BE around v137

**Issue**: Can't boostrap after using BE auto update.

**Steps to reproduce**: In win11, after update(auto restart or using old jar), the program keep no reaction. And i try get thread dump.

![Snipaste_2022-08-08_14-04-08](https://user-images.githubusercontent.com/15688938/183350071-6ff59329-2a2b-4866-96ba-35e3273f85fa.png)
![Snipaste_2022-08-08_14-02-56](https://user-images.githubusercontent.com/15688938/183349887-800afaa5-d79d-44e6-8cb9-4ab4286941ae.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, my response is the same as https://github.com/Anuken/Mindustry/issues/6903#issuecomment-1149945266 - The problem doesn't happen on my end, and I don't care about the BE update system. If you know how to fix it, submit a PR.

**Comment by way-zer** [comment]
seems
 it is the parent process open the log file, and not close.
