### ISSUE TITLE
heat increase liquid conversion rate

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry#7328]
**Platform**: Window

**Build**: 137

**Issue**: 
Please refer the image below while read the following statement.
Background: As we know, phase-synthesizer consumes 2 ozone and consume 8 heat to reach 100% eff, while electrolyzer produce 4 ozone. 
Situation A:
9 heat(112%), 1 electrolyzer can perfectly pair with 2 phase-synthesizer
Situation B:
45 heat(400%), 1 electrolyzer can still perfectly pair with 2 phase-synthesizer(liquid consumption doesnt increase)
Situation C:
45 heat(400%), 2 electrolyzer can still perfectly pair with 1 phase-synthesizer(liquid consumption does increase or extra **unnecessary** liquid consumption)

Here are two ideas to fix this problem
1. increase liquid consumption accord with eff increased with heat, which are correspond the eff increased by overdrive(liquid conversion rate doesnt not increase)
2. fix liquid consumption regardless of eff increased with heat, which would be a new eff system(liquid conversion rate would increase)
![image](https://user-images.githubusercontent.com/55009845/183477451-925b974f-68fc-4f3d-a7e5-b3ed11fce308.png)

**Steps to reproduce**: As viewed above.

**Link(s) to mod(s) used**: vanilla problema

**Save file**: easy reproduce

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
See #7288
