### ISSUE TITLE
Something like a crash

### ISSUE THREAD

**Issue by Trepcilonk** [Anuken/Mindustry#7334]
**Platform**: `Android 26`

**Build**: `alpha build 137`

**Issue**: *Explain your issue in detail.*
Sometimes the game suddenly stops when I'm gonna build or destroy something, both mine or abandoned 
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I have around 24 polys in a map (ex. Interplanetary area - I don't remember the name exactly -) and when I try to destroy abandoned buildings, when the polys get close enough the game suddenly stops, but doesn't give a crash report (or I don't know how te get one). It's quite annoying as it happens in many maps and multiple times in the same situation. I have to quit the game and enter again and it happens again. 
**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[mindustry 8 10 22.zip](https://github.com/Anuken/Mindustry/files/9295189/mindustry.8.10.22.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, still unable to reproduce on desktop.
