### ISSUE TITLE
Unable to Import from GitHub

### ISSUE THREAD

**Issue by LordDoge** [Anuken/Mindustry#7335]
**Platform**: *Windows 10*

**Build**: *Alpha 137*

**Issue**: *Unable to access and import mods from GitHub. *

**Steps to reproduce**: *Enter into mods, mod browser, select any mod, hit install.*

**Link(s) to mod(s) used**: *None.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Additional screenshot of ERROR.
![image](https://user-images.githubusercontent.com/44487173/183781157-88e033c0-1d0b-414d-a9c3-0ac2f3db743e.png)

**Comment by Anuken** [comment]
Works for me, likely an issue with your network or a mod.
