### ISSUE TITLE
Strange Item Void & Conveyor interaction

### ISSUE THREAD

**Issue by AESIR-Foopy** [Anuken/Mindustry#7336]
**Platform**: iOS

**Build**: Alpha 137, TestFlight version

**Issue**: Strange bug with Item Voids and Sources: [https://bit.ly/3Qyrs5D] 

**Steps to reproduce**: An Item source is placed next to a conveyor leading directly into a void. It takes priority over everything else. 

**Link(s) to mod(s) used**: None

**Save file**: [save-untitled.zip](https://github.com/Anuken/Mindustry/files/9295522/save-untitled.zip)

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Merging behavior is nondeterministic. Not a bug.
