### ISSUE TITLE
Coal and titanium not social distancing properly

### ISSUE THREAD

**Issue by RealYeet** [Anuken/Mindustry#7344]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

Mac

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

137

**Issue**: *Explain your issue in detail.*

Upon opening the menu for an airblast drill, coal and titanium text/photos are right next to each other while other resources are spaced apart.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Hop into a map with coal and titanium
Open the airblast drill ui 
Observe
<img width="1792" alt="Screen Shot 2022-08-10 at 4 06 28 PM" src="https://user-images.githubusercontent.com/88537252/184011115-2c63845d-938a-4eb0-a6d2-ac5d5b8d91e7.png">

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[Bug.msav.zip](https://github.com/Anuken/Mindustry/files/9303735/Bug.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
