### ISSUE TITLE
V7 kep crash help

### ISSUE THREAD

**Issue by Bafalutinm** [Anuken/Mindustry#7352]
**Platform**: `Android 29`

**Build**: `bleeding-edge build 23003`
**Issue**: game crashes when interact with anything

**Steps to reproduce**: open game interact with block

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[savestabe3.zip](https://github.com/Anuken/Mindustry/files/9328605/savestabe3.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
> Crash report: The contents of relevant crash report files. REQUIRED if you are reporting a crash.
