### ISSUE TITLE
unitCount counts player as 2 units when returning to core

### ISSUE THREAD

**Issue by 24110802** [Anuken/Mindustry#7357]
**Platform**: Windows 10

**Build**: 23012

**Issue**: World processor command fetch unitCount briefly counts a player as 2 units when returning core with the respawn button.

**Steps to reproduce**: Load the code below into a world processor. Start a new game and spam the respawn button (must be sharded)

fetch unitCount ucount @sharded 0 @conveyor
print "unitCount: "
print ucount
message mission 3

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

twas in playtest

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Player units don't despawn immediately (core creates new unit -> old one disappears after a while), and I won't be changing this. If you want accurate player counts, use playerCount.
