### ISSUE TITLE
Bug on the enemy base

### ISSUE THREAD

**Issue by FateMaga3** [Anuken/Mindustry#7358]
**Platform**: *`Android`*

**Build**: *`Alpha build 137`*
**Issue**: *When I attack an enemy base at maximum difficulty, I have 300+ enemies on the first/second waves 
![Screenshot_20220813-182054_Mindustry](https://user-images.githubusercontent.com/111190799/184516069-2b70a99e-7e5c-40e9-bfe3-9d5197195885.jpg)
![Screenshot_20220813-182106_Mindustry](https://user-images.githubusercontent.com/111190799/184516073-b585ea5b-25e5-4c3a-8b74-f155abfcefb9.jpg)*

**Steps to reproduce**: *I was just capturing enemy bases until such an error appeared*

**Link(s) to mod(s) used**: *`none`*

**Save file**: *[bugfile.zip](https://github.com/Anuken/Mindustry/files/9332394/bugfile.zip)*

*If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.*

**(Crash) logs**: *`none`*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Consider it a challenge sector.

**Comment by FateMaga3** [comment]
> 

It's unreal sector :/, but ok
