### ISSUE TITLE
Binding keys ignore "Mouse Back" inputs on macOS

### ISSUE THREAD

**Issue by Banyc** [Anuken/Mindustry#7363]
**Platform**: Mac

**Build**: steam build 137

**Issue**: The game does not seem to recognize the input of the side buttons of the mouse when it's running on Mac.

**Steps to reproduce**:

1. Settings
2. Controls
3. "Follow Mouse" > Rebind
4. Click any of the side buttons of the mouse
5. No response
6. Left click the mouse (as comparison)
7. The key bind is set

In comparison:

1. Open chrome
2. Google whatever keywords
3. Click one of the side buttons of the mouse
4. It goes back to the home page

**Link(s) to mod(s) used**: none

**Save file**: unrelated to key binding but more of a system-specific issue

**(Crash) logs**: no crashes

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works fine for me on Linux (forward/back), I have no real Mac to test this on, sounds like a bug with SDL. Won't be fixing.
