### ISSUE TITLE
Logic Processors allow units to build blocks even if they are not currently researched in campaign

### ISSUE THREAD

**Issue by RealHifumi** [Anuken/Mindustry#7382]
**Platform**: PC (but likely applies to other platforms too

**Build**: build 137

**Issue**: Units can build unresearched blocks on campaign by using unit control build command in a logic processor

**Steps to reproduce**: reset mindustry campaign save, research the logic processor and switch, place a logic processor and switch down, link the switch to the processor and paste the following into the processor.

ubind @alpha
sensor x @unit @x
sensor y @unit @y
sensor x2 @unit @shootX
sensor y2 @unit @shootY
sensor a @unit @shooting
ubind @nova
ucontrol boost 1 0 0 0 0
ucontrol approach x y 5 0 0
jump 0 equal a false
sensor b switch1 @enabled
jump 0 equal b false
ucontrol build x2 y2 @tetrative-reconstructor 1 0

afterwards spawn in a nova unit, go into an alpha unit, and shoot at the place you want the block to be placed.
the unit will place a block (Tetrative reconstructor with the above logic) at the tile you shot at.

**Link(s) to mod(s) used**: NewConsole was used to speed up testing process. 
https://github.com/Mnemotechnician/new-console

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[bug.zip](https://github.com/Anuken/Mindustry/files/9363504/bug.zip)
hopefully I uploaded it right
this is a whole game save file

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Search keywords : Logic research, logic campaign

**Comment by BlueWolf3682** [comment]
i feel so bad for the crowd that just got pinged by the logic instructions
