### ISSUE TITLE
0fps bug

### ISSUE THREAD

**Issue by xicscon** [Anuken/Mindustry#7388]
**Platform**: *Android*

**Build**: *alpha build 137 *

**Issue**: *When I start mindustry ~10 minutes pass and the game gives 0 fps *

**Steps to reproduce* *Just play ~10 minutes on my save and server DarkDustry*

**Link(s) to mod(s) used**: *none*

**Save file**: https://drive.google.com/file/d/1X266rUV6pT7j0K3QXMRUauR11g-HVZRX/view?usp=drivesdk link because  I can't download save on Github

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not even going to investigate unless you can give more specific instructions and someone else can reproduce, this sounds like the same building freeze.
