### ISSUE TITLE
itemtake (singular) doesn't work :(

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#7389]
**Platform**: Windows 10

**Build**: BE 23030

**Issue**: If a unit gets one and only one itemtake instruction, it won't take any items (2+ instructions works)  
~~yes this is a really niche bug but i need to hyperoptimize this very specific logic program ok :p~~

**Steps to reproduce**: 
1) bind a unit, 
2) tell it to itemtake from something in range, then go into an infinite loop
3) unit decides to unionize and not take any items :(

**Link(s) to mod(s) used**: None

**Save file**: [dome testing.zip](https://github.com/Anuken/Mindustry/files/9373719/dome.testing.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Something is wrong with your code.

![image](https://user-images.githubusercontent.com/10100000/185450899-71a46fbf-ff91-45bd-89a6-c3f301410428.png)

This works just fine.

![image](https://user-images.githubusercontent.com/10100000/185450930-f18e2540-8ff8-4944-9b1a-959fa3f0e5e3.png)
