### ISSUE TITLE
File permission issue when importing game data on iOS

### ISSUE THREAD

**Issue by DeX3** [Anuken/Mindustry#739]
Hey!

Thanks for this awesome game! I really loved it on android so now I got it on iPad too. I wanted to share my progress, and was delighted to see an import/export game data feature.

However, I can’t import the exported zip-file on iOS. No matter how I select the file, I always get the following error screen:

![permission error screen](https://i.imgur.com/onomBXCr.png)

Note that it’s not even possible to import files exported by the same app on the same device - I always get the same error.

**Comment by Anuken** [comment]
I *think* I've fixed this in the last few commits, but I don't own an iOS device and the files app on my simulator doesn't work properly, so I can't test it.

**Comment by DeX3** [comment]
Happy to help in testing this, do you already know when the supposed fix is going to be available through the app store?

**Comment by Anuken** [comment]
Probably not very soon, as I want to make a few significant changes first. I've been pushing out updates very frequently recently, so I'd rather wait a bit before making any more.

**Comment by kevbost** [comment]
Confirmed going from android to ipad. Love the game!

**Comment by Anuken** [comment]
Closing, discussion should be moved to a newer issue with a similar name.
