### ISSUE TITLE
Sublimates do not attack Beam Nodes

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#7393]
**Platform**: MacOS

**Build**: v137

**Issue**: The Erekir turret, the Sublimate, does not attack beam nodes.

**Steps to reproduce**: Place a sublimate. Supply it with ozone or cyanogen. Place a beam node within range. The Sublimate will attack for 1 frame and then cease.

**Link(s) to mod(s) used**: None.

**Save file**: Can not convert to ZIP file. Played on the map "Project Manhattan" on the server io, with the first accessible northwest sublimate being the culprit.

**(Crash) logs**: Not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
Please let me know how to convert .msav to .zip.

**Comment by Anuken** [comment]
Turrets don't waste ammo on transportation infrastructure.
