### ISSUE TITLE
disabled blocks are disabled....PERMANENTLY!

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#7395]
**Platform**: Windows 10

**Build**: BE 23032

**Issue**: I don't know if this is a bug or new intended behavior but a disabled block will now not turn itself back on

**Steps to reproduce**: 
![image](https://user-images.githubusercontent.com/45698812/185595465-88e4ff4d-ab36-4276-a5e4-7454d413dd95.png)
![image](https://user-images.githubusercontent.com/45698812/185595503-b16896ee-5841-4a2d-ab76-c59bff479a40.png)
(you can even delete the processor)

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: 
[more t4 test.zip](https://github.com/Anuken/Mindustry/files/9381178/more.t4.test.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by gorodmi** [comment]
intended? dont know why you would need buildings to turn enabled automatically

**Comment by end-me-please** [comment]
That’s intended. disabled buildings turning on by themselves is unintuitive

**Comment by Anuken** [comment]
Not a bug.
