### ISSUE TITLE
vSync Issue [Linux]

### ISSUE THREAD

**Issue by NWJ9PB** [Anuken/Mindustry#7404]
**Platform**: `LINUX 5.15.61-1-lts KDE Plasma 5.25.4 QT 5.15.5`

**Build**: Version 126.2

**Issue**: Game crashes along with DE/WM when `VSYNC` is `OFF`

**Steps to reproduce**: Turn off `VSYNC` 

**Link(s) to mod(s) used**: `NO MODS USED`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
Umm, I can't, as I can't even open settings after turning off `VSYNC`, (a setting reset might help me)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
The build you are using is over a year outdated, update to the latest alpha

**Comment by Anuken** [comment]
> Game crashes along with DE/WM

If your WM crashes, that is not my bug. I don't fix obscure problems that occur outside of standard Linux setups.
