### ISSUE TITLE
Game crashes in main menu with noSuchFieldError

### ISSUE THREAD

**Issue by 5UP3R-D1N** [Anuken/Mindustry#7412]
**Platform**: Windows

**Build**: 135

**Issue**: It always crash after 2 minutes in the main menu

**Steps to reproduce**: I don't know how it happen it just work fine then 2 days ago this happen

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: Not in a save or multiplayer

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: ![image](https://user-images.githubusercontent.com/42496449/185931065-dba6cf30-291a-4caa-8d15-15e7677c0515.png)
[crash-report-08_22_2022_20_15_49.txt](https://github.com/Anuken/Mindustry/files/9394666/crash-report-08_22_2022_20_15_49.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Update to the latest version (137)

**Comment by Anuken** [comment]
135 is outdated, and this is a mod crash.
