### ISSUE TITLE
Changed settings to 5 FPS and is no longer responsive to input

### ISSUE THREAD

**Issue by azekeil** [Anuken/Mindustry#742]
Hi, pretty much as the title says. I'm playing the steam release on Windows and I changed the settings to 5FPS (trying to pull it down to 60 but overshot). Now the game won't respond to any input (including Alt-F4!) so I have to kill it with Task Manager.

I found a settings file but it's in binary so I can't edit it outside the game, and I want to preserve my progress.

Any way to resolve this?

**Comment by azekeil** [comment]
I tried moving the settings.bin and settings-backup.bin out of the way. It didn't resolve the problem :(

**Comment by Anuken** [comment]
For whatever reason, I can't reproduce this issue on Linux or Windows. Even when it's stuck on 5 FPS, I don't experience any issues.

**Comment by Anuken** [comment]
As a possible fix, I've moved the cap up to 15 from 5. Since I can't actually reproduce a problem, you'll need to see whether this will work for you next update.

**Comment by azekeil** [comment]
Nice, thanks! Here's hoping...

**Comment by azekeil** [comment]
Couple of other things - I have multiple monitors, and my main monitor is 4k. I just thought that perhaps it was something to do with that, so I disabled my 4k monitor to leave just my 1920x1080 monitor, but it was still unresponsive on that.

In my experimenting, I found I could sometimes unmaximise the window as it was loading, before the menu screen comes up with the ships in the background.

None of this seems to accept any input though unfortunately :(

**Comment by azekeil** [comment]
@ToyDragon contacted me through Steam and I sent him my [saves.zip](https://github.com/Anuken/Mindustry/files/3694541/saves.zip). He was able to recreate the problem! He said if I hover my mouse over settings and keep it stationary for like 15 seconds, then click, then wait another 10 seconds or so the settings menu does come up.

Following his advice, I was far more patient but was able to move my slider up to 60FPS and the game is back to normal responsiveness!

I wonder if it's the combination of other settings I had in there that caused the lack of responsiveness. I'm on build 96 right now - not sure which build the issue started on (probably also 96?)

Many thanks to @ToyDragon for having the patience I didn't have!

**Comment by inxaneninja** [comment]
Maybe someone else could send you their settings file and you could replace it in the game's files, not sure if it is user specific so don't quote me on this

**Comment by azekeil** [comment]
@inxaneninja - @ToyDragon guided me to fix the issue myself. While the original issue is fixed, I'm leaving this open as it may affect others...

**Comment by WhiteSp1rit** [comment]
Having exact same issue, Steam build 96

Tried waiting a long time between mouse clicks, I was able to get to the settings menu, but can't do anything there, even waiting for more than half a minute

**Comment by mathieulajoienoel** [comment]
I've had this issue on the Steam version of the game. I was able to fix it by deleting the 2 settings files in \Steam\steamapps\common\Mindustry\saves.

The game on itch.io seems to save its settings in %appdata%/Mindustry.

Restarting the game after generates new clean setting files.

Hope it helps someone.
