### ISSUE TITLE
Using "Check for updates" causes last frame to be continuously drawn above all

### ISSUE THREAD

**Issue by Gerdathlete** [Anuken/Mindustry#7420]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

**Windows 10**

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**BE - 23053** (I had the issue in previous versions as well)

**Issue**: *Explain your issue in detail.*
When using the "check for updates" button on the main menu or updating with the new update prompt during the game, the last frame of the downloading stays on screen and draws over everything, including the windows start menu and task bar. Taking a screenshot with snipping tool actually reveals the updated version of Mindustry running behind the last frame, though this is not actually visible to the user:

![image](https://user-images.githubusercontent.com/25123577/186045280-ba2873b9-87a8-467d-bae7-aa3616690feb.png)

In order to get rid of the issue you must kill a hidden java process through task manager (this is done on a second monitor):

![image](https://user-images.githubusercontent.com/25123577/186045380-3901e097-75bf-43e7-b4c4-02df3ccb5076.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Download a recent version of Mindustry that is not the latest build (this issue occurred with 23041, and 23053) from https://github.com/Anuken/MindustryBuilds/releases.
2. Load the game by launching the .jar file with Java (I'm using Java version "17.0.1" 2021-10-19 LTS; Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)).
3. Click the check for updates button, and start updating to the latest version.
4. Upon completion, the last frame of the updating should stay on screen, and block your view.
5. Use task manager to kill the process drawing the frame over everything else.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This has been reported many times, I can't reproduce it and I'm not interested in fixing it (use the alpha, or another OS)

**Comment by Gerdathlete** [comment]
> This has been reported many times, I can't reproduce it and I'm not interested in fixing it (use the alpha, or another OS)

It was happening consistently then didn't happen when I updated from BE 23066 to BE 23075. ¯\_(ツ)_/¯
