### ISSUE TITLE
Liquid Junction and Basic Conduit act weird under load. 

### ISSUE THREAD

**Issue by CVex2150J** [Anuken/Mindustry#745]
**Platform**: Window 7 (64bits)

**Build**: Steam Build 96

**Issue**: Liquid Junction and Conduit(basic) act weird under load. 
(in the following images, Slag and Separator are used but all block that require liquid have the same issue)
- **Image 1** Leaks are ok.
- **Image 2** When a liquid line is attached to a block, the last junction act like a wall with basic conduit 
- **Image 3** When the next conduit to the last junction is upgraded to Pulse Conduit, fluids act ok

**Steps to reproduce**: See images

**Notes**: 
All my tests were done in sandbox with Liquid sources as I was learning how every block in the game works in pratice.
 
The same problem occurs with :
- Water and Multi-Press
- Oil and Coal Centrifuge
- Oil and Plastanium Compressor

I'm pretty sure, just by looking at the source code, that the issue lies in this block. 
https://github.com/Anuken/Mindustry/blob/a1da82a173e1fd280371cd963d07f592f77517af/core/src/io/anuke/mindustry/world/BlockStorage.java#L142

I'll leave it to you. Thx for this nice game.

![Junction_Conduit_Issue_Spill](https://user-images.githubusercontent.com/7817285/65828237-a4be7e80-e266-11e9-9def-f8d71851c111.PNG)
![Junction_Conduit_Issue2](https://user-images.githubusercontent.com/7817285/65828200-3b3e7000-e266-11e9-8d7a-7e6d15b6d113.PNG)
![Junction_Conduit_Issue3_hack](https://user-images.githubusercontent.com/7817285/65828201-3ed1f700-e266-11e9-9dd9-affc14de366e.PNG)

**Comment by Anuken** [comment]
I haven't touched the liquid code in a very long time, but my guess is that this could be related to the fact that flow rate is tied into the difference between liquid stored in adjacent conduits. Since junctions don't actually store liquids, but rather proxy the conduit they are passing to, the flow isn't calculated properly.

**Comment by Saucistophe** [comment]
Oooooh that explains the inexplicable lack of cooling fluid when I added a reactor in a recent run.
I couldn't document it because it, you know, turned into tiny little specks of molten glass, metal, thorium and sadness. :disappointed:

**Comment by Ali-C-Ila** [comment]
This is an issue. I suggest using bridges before this is fixed.

**Comment by Gkkiux** [comment]
This explains why my reactors blew up unexpectedly with an overabundance of cryofluid production. I'm not getting any benefit from pulse conduits, so for the time being I'm just replacing the outputs with more junctions
![Screenshot_20191031-130830_Mindustry](https://user-images.githubusercontent.com/9932878/67942068-ac63a100-fbdf-11e9-9808-d278672655c0.jpg)

**Comment by Anuken** [comment]
New behavior:

![image](https://user-images.githubusercontent.com/10100000/68431111-69757080-017f-11ea-8327-a84c41836778.png)
