### ISSUE TITLE
Game doesn't show loading screen and instantly shows an unloaded menu

### ISSUE THREAD

**Issue by fede0009000** [Anuken/Mindustry#7452]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!) Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Alpha Build 137

**Issue**: *Explain your issue in detail.*
It isn't really an issue, gamebreaking or anything. Just a visual bug. I left the game opened while I did other stuff on my phone, when I opened it back, it didn't show the load screen, but the standard menu: without the image behind the buttons, so everything black, a white square where the symbols should be, the words in the buttons were normal.
i tried clicking on "campaign" and all I could see was a small lock (a campaign sector I haven't unlocked yet) and I couldn't move, same in erekir. After some seconds it just showed the loading screen as usual.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was in the menu, then changed app without closing the game. When I opened it again, it did this.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Doesn't occur on my device.
