### ISSUE TITLE
Aegires will attack evoke, incite, emanate without payload

### ISSUE THREAD

**Issue by PCX-LK** [Anuken/Mindustry#7457]
**Platform**: Any

**Build**: v137

**Issue**: Aegires will proactively attack evoke, incite and emanate that are not effectively payloaded within the attack range

**Steps to reproduce**: 

**Link(s) to mod(s) used**: 

**Save file**: 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already fixed.
