### ISSUE TITLE
Bug or inconsistency with armored conveyors

### ISSUE THREAD

**Issue by KSKNico** [Anuken/Mindustry#746]
**Windows 10**

**Build 96**

Armored conveyors don't accept items from phase conveyors even though it is stated in the description. This is because phase conveyors act as ItemBridges and not as Conveyors.

![armored_conveyor_bug](https://user-images.githubusercontent.com/35336087/65835313-13422180-e2e5-11e9-9114-f06262ef9a26.png)

It could be fixed

- by explicitly stating that only conveyor **belts** can transfer items from the side by changing this line: https://github.com/Anuken/Mindustry/blob/4210070d07e571f56acc000508d2c1fbb6e9c5bb/core/assets/bundles/bundle.properties#L814
- or by changing these and the following lines https://github.com/Anuken/Mindustry/blob/4210070d07e571f56acc000508d2c1fbb6e9c5bb/core/src/io/anuke/mindustry/world/blocks/distribution/ArmoredConveyor.java#L14-L16 and then maybe adding `source.block().name == "phase-conveyor"` into the OR-condition. It works fine then but the rendering also needs to be adjusted because it doesn't look like it is adjacent to the phase conveyor.

It's up to you I think but perhaps I'm missing something.

**Comment by Kieaer** [comment]
It's not bug.

**Comment by Anuken** [comment]
`Other conveyors` refers only to belts. A bridge is not the same type/class of conveyor as an armored one.
I'll change the description anyway, but it doesn't seem inconsistent to me.
