### ISSUE TITLE
Mindustry refuses to provide a crash log.... ever

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#7468]
**Platform**: Linux (Arch Linux)

**Build**: v137.1 Steam

**Issue**: Any Mindustry crash does not produce an error window or log. No file, no popup, the process just dies.

**Steps to reproduce**: Be on linux, do something to make the game crash (Mod error, bad settings)

**Link(s) to mod(s) used**: None.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

Save file is irrelevant; tested crashes occur *without a save.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

I understand.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

The entire issue here is that I can't get a crash log in any way.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [?] **I have searched the closed and open issues to make sure that this problem has not already been reported.** (similar to "Mindustry crashes in SQL_QUIT() with Korean IME", except I haven't changed the IME??? Also I don't get a java crash log either)

**Comment by Anuken** [comment]
I don't have this issue on Linux and it's obviously not something I can "debug" with an absence of any information.

**Comment by Erisfiregamer1** [comment]
What information can I provide? I'd like to be able to provide crash logs when a mod is being strange.

**Comment by Anuken** [comment]
Nothing, aside from stdout. Your phrasing suggests that isn't being produced either.

**Comment by Erisfiregamer1** [comment]
We might as well check. How do I get the output of STDOUT?

**Comment by Anuken** [comment]
Just run the game through a terminal.

**Comment by Erisfiregamer1** [comment]
After an update to v138, something you did fixed it. I'm getting crash logs again.
Whatever you did, thank you??
