### ISSUE TITLE
Objective improvement/expansion Suggestion

### ISSUE THREAD

**Issue by mActUx06** [Anuken/Mindustry#747]
Add more Objectives like on tutorial.
 * e.g. create a number of this building, defeat the boss, rescue mission.
Expand the Campaign.
 * Get the idea of giving strategy and combinations during running a campaign.
 * Randomly generated map but still having objectives to maintain the 'Thrill' of the game.

*Sandbox partly describes the second bullet of the second suggestion. That however, mainly focus on tower defense...

**Comment by Anuken** [comment]
Don't bypass the issue template! Suggestions go in the suggestions issue.

**Comment by mActUx06** [comment]
Sorry. I don't know where to say this... :P
