### ISSUE TITLE
Campaign sectors from previous save are unlocked and shown as "under attack" after wiping save data on a different computer

### ISSUE THREAD

**Issue by theperspectiv** [Anuken/Mindustry#7479]
**Platform**: PC (Steam)

**Build**: 138.1

**Issue**: I play Mindustry on 2 computers, and have never had a problem with syncing saves. However, I wiped my save data on PC 2, played a few maps and unlocked some tech, then got home and opened Mindustry on PC 1. All unlocked sectors from my previous save were accessible and "under attack". Tried it multiple times on both computers, and the issue always appears on the other one.
I was able to get around this issue by exporting the new save from the computer I'd wiped my save data on, then manually importing it on the other computer.

**Steps to reproduce**: Wipe save with the "Clear game data" option, play a map, save & quit, give Steam Cloud a second to sync, open Mindustry on second computer.

**Link(s) to mod(s) used**: [None](https://github.com/warcry98/speedcontrol)

**Save file**: https://www.dropbox.com/sh/xwgjqp7s6vaw26f/AACKJubK07dUYZcm8q8UsxQma?dl=0

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- 
![Mindustry_i3wkl791KE](https://user-images.githubusercontent.com/63799613/187355667-2a094c2a-2526-4908-8985-ec429586b771.png)

**Comment by Anuken** [comment]
If you wipe your game settings/data file, the saves will remain. This is a sync issue.
