### ISSUE TITLE
Pathfinding issues

### ISSUE THREAD

**Issue by Funny132** [Anuken/Mindustry#7484]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam build 138.1

**Issue**: *Explain your issue in detail.*
Units don't even try to go to the point they're commanded to go to if there's not a clear direct path to get there or getting there would require breaking an enemy building.
![and as for the first one](https://user-images.githubusercontent.com/85383565/187557521-4c04ad58-a068-48b4-9bdb-894cea34b2b4.PNG)

As a sidenote, they'll also not even try if the pathfinding is too complicated.
![there is a path](https://user-images.githubusercontent.com/85383565/187557544-158b9896-d73c-47fe-ad48-ce1df0d118a6.png)
![so stop complaining](https://user-images.githubusercontent.com/85383565/187557553-e06f18f0-10a4-4566-86f6-f2eb5e8f9301.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
This .zip file isn't a game data save, it just contains a .msav file of a map that I can consistently recreate the "complicated pathfinding not working" bug on. Import the map, open a custom game on the map in any compatible gamemode as the Sharded, and command the Maces, Crawler, or any Serpulo ground unit of your choice that can't fly or step over walls, to attack the Blue core on the other side of the map. The reason I've uploaded this in a .zip file is because Github doesn't accept direct .msav file uploads.
 [Bug Report Map.zip](https://github.com/Anuken/Mindustry/files/9457066/Bug.Report.Map.zip)

For the other one, look in the **Save file**  section, open it up, go to The Onset on Erekir, and look at the Malis Stells that've just straight up not even tried to go towards my core like they're supposed to due to me having blocked them off using walls before they spawned.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
The only mod I used was [this mod here](https://github.com/xzxADIxzx/Scheme-Size), but this bug has been happening since before I installed that mod so I doubt that it's affecting anything. I had a bunch of other mods downloaded, but they weren't enabled. Turning Darkness off in the Render Settings menu of that mod allows you to see the bug more clearly with the tanks not... well, moving. At all.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
This is the save file - use Import Data to open this one, and go to The Onset on Erekir. They aren't visible through the black part, but if you turn Darkness off, you can see that the three tanks are just... sat there.
[bug report save file.zip](https://github.com/Anuken/Mindustry/files/9457060/bug.report.save.file.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
Not a crash

Also, regarding the bottom checkbox of the checklist thingo at the bottom, I did see someone reporting a [similar issue](https://github.com/Anuken/Mindustry/issues/5260), but it isn't quite the same one and is also from an older version.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bokunodev** [comment]
Units doesn't path find correctly sometimes and some other times they prefer to take a detour through acid lake (Erekir, Stronghold).

version 155.4 beta

mods:
1. https://github.com/smolkeys/new-console-hardline version 2.3
2. https://github.com/warcry98/speedcontrol version 0.1
3. https://github.com/samielxd/zoomplus version 1.0

screenshot from Erekir, Siege map. 

<img width="1124" height="899" alt="Image" src="https://github.com/user-attachments/assets/945a1327-fb82-4b77-85a8-e45dfd47efb5" />


save files and settings and mods
[exported data.zip](https://github.com/user-attachments/files/25805105/exported.data.zip)

**Comment by bokunodev** [comment]
the bug is inconsistent without the any mods. but its sometimes there. i'll try to replicate it again
