### ISSUE TITLE
Screenshotting with Shift+Windows+S doesn't take the present frame 

### ISSUE THREAD

**Issue by Balefirex** [Anuken/Mindustry#7486]
**Platform**: Windows 10

**Build**: Alpha 138.1

**Issue**: Trying to screenshot with shift+windows+s while the program is in focus takes frames from roughly 15 seconds ago instead of what's currently happening

**Steps to reproduce**: 
Step 1: Start playing the game
Step 2: Move to a different location
Step 3: Do shift+windows+s to try and screenshot
Step 4: See that the game "rewinds" to previous location rather than the one you were trying to capture

**Link(s) to mod(s) used**: *N/A

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/9458272/saves.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I did not write the Windows screenshot program. This is not a bug with the game.
