### ISSUE TITLE
Frequent game crash / freeze 

### ISSUE THREAD

**Issue by darwin1501** [Anuken/Mindustry#7490]
**Platform**: `Android 29`

**Build**: `alpha build 138.1`

**Issue**: *Explain your issue in detail.*
----The game freezes everytime, and I can't do anything other than force closing the app 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
---- when I deconstruct multiple buildings like defenses, miners

**Link(s) to mod(s) used**: `[]`
--None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Has been reported many times, cannot reproduce on my phone or PC.
