### ISSUE TITLE
Failed to load world data on steam multiplayer

### ISSUE THREAD

**Issue by Ramiels** [Anuken/Mindustry#7498]
**Platform**:
Windows 10

**Build**:
Steam Build 138.1

**Issue**: Upon trying to join host in steam multiplayer the game will pause loading at about 2-15% then give a nondescriptive "Failed to load world data" error. 
After opening console and repeating the following is outputted:
![50532638 20000005_image](https://user-images.githubusercontent.com/54731850/188001564-3e96bc84-e249-4f3b-8311-a75d31708329.png)
This occurs both ways from me hosting or the other player hosting.
Error doesn't occur when joining servers (both clients can connect at the same time just fine)
Both players are on Steam Build 138.1
Happens regardless of map

**Steps to reproduce**:
Open any map on singleplayer mode -> press "HOST" in pause menu -> invite other player to join
Wait for other player to host -> accept invite -> wait until error message

**Link(s) to mod(s) used**:
N/A

**Save file**:
[v7save.zip](https://github.com/Anuken/Mindustry/files/9472913/v7save.zip)
*issue happens regardless of which one of us is hosting, but this is my save*

**(Crash) logs**:
N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
*any* mods?

tried reinstalling?

**Comment by Ramiels** [comment]
No mods, hence the N/A.
Will try reinstalling when the other player is available due to timezone issues

**Comment by Anuken** [comment]
Is your friend in a different/far-away country? I've noticed the Steam networking system can take an absurdly long time to connect or send any data sometimes what that is the case, so long that Mindustry times out. I can increase said timeout to something like 25 seconds, but I'm not aware of anything I can do to otherwise solve the underlying issue.
