### ISSUE TITLE
2 buttons "enable console" 

### ISSUE THREAD

**Issue by ilya034** [Anuken/Mindustry#7502]
**Platform**: *Windows 10*

**Build**: *BE 23123*

**Issue**: *go to settings -> game:* 
![image](https://user-images.githubusercontent.com/68101303/188202609-01fe2e4d-2fe3-4384-a5fc-a38682c4d3f4.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
**You did not fill out the template.** *Why do you think I ask whether you are running mods or not?*
