### ISSUE TITLE
Bug about conduit.

### ISSUE THREAD

**Issue by TyTxexebe** [Anuken/Mindustry#7503]
**Platform**: *The type of device Android*

**Build**: *Alpha 138*

**Issue**: *Water doesn't want to go through the conduit, even though they are empty and do not occupy another liquid / gas*

**Steps to reproduce**: *When you break these empty conduit and put them back, the water starts flowing again, but after a while this bug appears again*

**Save file**: 
[29022_mind_save2.zip](https://cdn.discordapp.com/attachments/982900879533436938/1015322163726798879/292022_mind_save2.zip)

**Comment by end-me-please** [comment]
can you make a screenshot/video?

**Comment by Anuken** [comment]
You specified your entire game data, not a save.

When I search through the second save, I see conduits with a tiny amount of hydrogen in them blocking water. This is not a bug.
