### ISSUE TITLE
Movement speed boost while upgrading conveyors

### ISSUE THREAD

**Issue by TonkyBoi** [Anuken/Mindustry#7507]
**Platform**: *PC Windows 10 64 bit*

**Build**: *138*

**Issue**: *Large speed boost when building plastanium conveyors sometimes*

**Steps to reproduce**: *I was upgrading a string of titanium conveyors to plastanium conveyors on sector 260 and bridge conveyors to phase conveyors. The conveyor was for output of some kilns. When I unpaused the game to start building it all, I got a massive movement speed boost as I moved upward as I built the conveyor. I am unsure to why it happened, but I tested it in sandbox mode and for some reason it doesn't work unless there are mega and poly helping build, and it still isn't consistent then.*

**Link(s) to mod(s) used**: *none*

**Save file**: (https://www.dropbox.com/s/e5jw3vqculudmw9/v7%20campaign%206.zip?dl=0)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I cannot reproduce any speed boosts while building on that map.
