### ISSUE TITLE
World Processor gets Health data from Get Block incorrectly

### ISSUE THREAD

**Issue by skipydog** [Anuken/Mindustry#7509]
**Platform**: Windows

**Build**: 7.0 Build 138 - Alpha

**Issue**: World processor unable to get health of blocks required by Get Block; only max health returned

**Steps to reproduce**: Attempting to get health of a block from Get Block, placed by the world processor. Monitor the variables as the block is being shot at by a Duo, the received health data will always stay at max. This also happens if the block is on the Sharded Team. 
Operations around this are found at line 14 - 17 in the world processor instructions

**Save file**: [buggy.zip](https://github.com/Anuken/Mindustry/files/9481939/buggy.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
A **block** is a type, it does not contain state. Getting health of a block type always gives you the same result. **Buildings** have health, blocks only have max health.
