### ISSUE TITLE
Using sector generation in map editor (then playtest) causes my respective campaign sector get attacked

### ISSUE THREAD

**Issue by theoallen** [Anuken/Mindustry#7526]
**Platform**: *Windows (Steam)*

**Build**: *138.1*

**Issue**: *When I try map editor using Serpulo sector generation, my campaign map somehow got attacked*.

**Preview:**
![Screenshot_70](https://user-images.githubusercontent.com/6810856/188833326-15936b08-ef3b-4561-beb6-5e8dc0f70274.jpg)

In this screenshot, sector 1 isn't even adjacent to the enemy base. Some sectors get unlimited waves, some don't. The one that got unlimited waves reset/recaptured when you reboot the game and then enter/load the sector.

**Steps to reproduce**:

1. Open the map editor, create a new map
2. Use sector generation (Serpulo), pick the sector number that you have captured in the campaign (let's say, sector 223)
3. Prepare everything for survival (put core, wave spawn, etc)
4. Playtest -> Manually spawn waves -> Quit
5. Continue the campaign, sector 223 should be under attack.

**Link(s) to mod(s) used**: *n/a*

**Save file**: [Save File](https://cdn.discordapp.com/attachments/796595862629253143/1016993788268380200/SectorAttackBug.zip)

**(Crash) logs**: *n/a*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
well this is one of the more exciting bugs
