### ISSUE TITLE
Level "Marsh" is locked, but has no requirement to unlock

### ISSUE THREAD

**Issue by SevenBlocks** [Anuken/Mindustry#7531]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Linux Ubuntu 22.04

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Mindustry 7, 138

**Issue**: *Explain your issue in detail.*
Level "Marsh" is locked, but there is no requirement to unlock it. When clicked on, it says "Complete:" and "Enemy Base", but nothing else.
![Screenshot](https://user-images.githubusercontent.com/8278755/189200082-e4164426-12fb-4b7f-8647-3f69cf6b1ac9.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I completed all of the available Erikir levels with release 136. When I downloaded 138, Marsh is locked.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
RTFM
https://github.com/deltanedas/rtfm

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[sector-erekir-88.zip](https://github.com/Anuken/Mindustry/files/9529759/sector-erekir-88.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash_logs.txt](https://github.com/Anuken/Mindustry/files/9529775/crash_logs.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Check your tech tree. You have to research it if you already had the requirements for it when you updated.

**Comment by SevenBlocks** [comment]
Tech tree updates fixed it. Thanks.
