### ISSUE TITLE
MapIO.generatePreview() crashes the server

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#7538]
**Platform**: *headless*

**Build**: *Mindustry v138 alpha*

**Issue**: Calling MapIO.generatePreview on a headless server while playing a map causes random errors and sometimes crashes the server .

**Steps to reproduce**: Launch a server, host it on any map, then call MapIO.generatePreview() for some of the attached maps.
[Mapping.msav](https://cdn.discordapp.com/attachments/903266656841777242/1018162001777791169/ATTACK_Mapping.msav)
[V6_Attack_Map.msav](https://cdn.discordapp.com/attachments/903266656841777242/1018161967292239892/ATTACK_COOP_Attack_Map_v6.msav)

**Link(s) to mod(s) used**: *<none, only JS script which tries to invoke MapIO.generatePreview>*

**(Crash) logs**: 
[crashes.txt](https://github.com/Anuken/Mindustry/files/9540534/crashes.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
Wait i didn't attach any maps. Pls wait, i'll download them first

**Comment by Darkness6030** [comment]
[https://cdn.discordapp.com/attachments/903266656841777242/1018162001777791169/ATTACK_Mapping.msav](Mapping)
[https://cdn.discordapp.com/attachments/903266656841777242/1018161967292239892/ATTACK_COOP_Attack_Map_v6.msav](Attack Map)

**Comment by end-me-please** [comment]
I thought the server doesn’t have any of the graphic assets?

**Comment by Darkness6030** [comment]
The method doesn't need them, it requires only the color of block which can be set manually

**Comment by Anuken** [comment]
If a method causes crashes, you shouldn't using it, especially when you don't know how it works. **generatePreview loads a new map**, you can't simply use it while a map is being played.
