### ISSUE TITLE
erekir ships dont pathfinding over tar

### ISSUE THREAD

**Issue by Maffialnor** [Anuken/Mindustry#7539]
**Platform**: `Android`

**Build**: `138.1 alpha`

**Issue**: `T1 erekir ships doesnt going over tar floor, and just staying on it, if somehow appeared/step on.`

**Steps to reproduce**: `1. Create map with tar floor 2. Place enemy spawn over the tar 3. Add erekir ships in wave list 4. Test out this map`

**Link(s) to mod(s) used**: `No mods`

**Save file**: `This bug happens on every map you can play on`

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: `No crashes`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Saves are **mandatory**, and Erekir content should not be mixed with Serpulo content.
