### ISSUE TITLE
Placing conveyors belts in pause mode doesn't generate the correct corners tiles

### ISSUE THREAD

**Issue by KurzedMetal** [Anuken/Mindustry#754]
**Platform**: Windows

**Build**: steam build 86

**Issue**: When I place conveyor belts in pause in a sequence, I expect the game to create the proper corner tiles, but it doesn't. It does work as expected when I do it without pause.

I played pretty much the whole campaign and this is the only frustrating thing I've come across in the UI so far.

With pause:
![20191001_021952](https://user-images.githubusercontent.com/1426680/65936156-00694300-e3f2-11e9-8226-6d138079149f.gif)

Without pause:
![20191001_022137](https://user-images.githubusercontent.com/1426680/65936208-41f9ee00-e3f2-11e9-89bf-ed1f0c40504b.gif)

**Comment by Anuken** [comment]
This isn't a bug. The previews are just the block sprite, they don't possess all the special auto-tiling intricacies of the block itself.

**Comment by sur0g** [comment]
Actually proper chaining of belt placement commands in any situation would be great. Especially on mobile where placing long distance belts with many corners is a pain in the neck.

**Comment by KurzedMetal** [comment]
If you don't consider this as a bug, please consider it as a feature request.
I'm pretty sure a lot of players would love not having to fiddle with the corners when working in Pause (saving precious time between waves).
