### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Mincis1233** [Anuken/Mindustry#7542]
So, I started deleting stones and I paused the deletion. Then I pressed the thing where you drag and copy. I copied the stone and game crashed. Sorry I could not find the crash log.

**Comment by Mincis1233** [comment]
Sorry that my post has no labels and stuff I rarely use github.

**Comment by Mincis1233** [comment]
Sorry that I closed and opened the post and did not label It I rarely use Github.

**Comment by Bottinator22** [comment]
1. Template (need logs for a crash)
2. pretty sure this is already fixed in V7

**Comment by Mincis1233** [comment]
[crash-report-09_11_2022_09_42_35.txt](https://github.com/Anuken/Mindustry/files/9542012/crash-report-09_11_2022_09_42_35.txt)

**Comment by Mincis1233** [comment]
Found the report

**Comment by Mincis1233** [comment]
I can replicate it.

**Comment by Bottinator22** [comment]
You're on version 126.2, which is severely outdated
