### ISSUE TITLE
Game freezes and make screen glitching

### ISSUE THREAD

**Issue by phbice** [Anuken/Mindustry#7543]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *The game sometimes freezes,  the graphics freezes but the music not. It won't respond to any key/mouse input. Sometimes just restart the game  will be fine (annoying though), but other time it will make screen blink and scroll like ancient TV which lost synchronization. If the latter happen, I have to reboot my laptop to fix the glitching screen. This become much more serious when I head to the Windswept Islands. The game freezes multiple times in an hour that I can't play normally. The only good thing is that I have not lost my saves yet.*

**Steps to reproduce**: *Not sure.  Maybe it happens when/after I make massive building plans? Just play loog enough (need not to be very long in the Windswept Islands), and it will occur anytime. That happens both in github builds and steam builds. I played the github builds first, then I managed to migrant the save file to steam. In steam builds, I've tried to install the rtfm mod (https://github.com/DeltaNedas/rtfm) and uninstalled it because it won't work.*

**Link(s) to mod(s) used**: `[rtfm](https://github.com/DeltaNedas/rtfm)`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[saves.zip](https://github.com/Anuken/Mindustry/files/9542712/saves.zip)

**Comment by end-me-please** [comment]
126.3 is a very old version, try updating to the latest one

**Comment by Anuken** [comment]
Very likely system/driver issue, 126.3 is ancient and nobody else has reported anything remotely similar.
