### ISSUE TITLE
Crashes cause stages to be reset

### ISSUE THREAD

**Issue by harbinger0x7c0** [Anuken/Mindustry#7545]
**Platform**: `Android 28`

**Build**: `release build 126.2`

**Issue**: A couple of times now I've seen a crash that caused my device to reboot, and when I loaded the game some sectors had been reset, as if I had never been there. I think the sectors in question have been either the one I was playing in at the time of the crash, or actively under attack at that time. I don't think I've seen more than two sectors at a time affected in this way.

**Steps to reproduce**: I'm not sure what is causing the crash, but I have attached crash logs. 

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[save.zip](https://github.com/Anuken/Mindustry/files/9543593/save.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
[crash.txt](https://github.com/Anuken/Mindustry/files/9543589/crash.txt)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
126.2 is not the latest version and this has been reported countless times with no known cause.

**Comment by harbinger0x7c0** [comment]
Not the latest version? It's the release on your itch.io page, and the version in the app store. If 'latest version' doesn't mean the one that your downloads point to, what exactly does it mean?

**Comment by Bottinator22** [comment]
the "[UNSTABLE ALPHA]" release

despite its name it's actually stabler

**Comment by Anuken** [comment]
> what exactly does it mean?

There is a link right next to that checkbox that explains what it means, which you should have clicked. If you are **not** using the version named there, it is not the latest version.

**Comment by harbinger0x7c0** [comment]
You mean [this link](https://github.com/Anuken/Mindustry/releases)?

The one where you find two pages of builds marked "pre-release" and then this?
![Releases · Anuken_Mindustry](https://user-images.githubusercontent.com/911543/189575359-625c90af-ee07-480f-a580-24a7cddac5e5.png)
Where 126.2 is flagged _latest_? I should have looked at that and thought anything other than "126.2 is the latest release"?

Look dude, I didn't come here to be a jerk, I'm trying to help out what I think is a cool project. But what's going on right now is not cool. You've got literally thousands of closed issues on this repo, and I searched several different keywords before I submitted just to have you turn around and say it's already been submitted "countless times" and that I'm not even running the latest version even though according to all the signs you provide I am doing exactly that. Now, I believe you when you say it's already submitted, because I know that people trying to report a problem they don't understand can use all kinds of ways to describe it, and it is frankly nobody's fault that that results in duplication. But if the problem still exists and all the reports are getting closed that is somebody's problem. According to you it's actually "countless" somebodys' problem.

I'm also willing to believe @Bottinator22 that the UNSTABLE ALPHA release actually is stabler, although I do have to say that means it's very badly named. Unfortunately, it's also no help to me because I can't sideload apps without doing a factory reset on the device I play on. So I guess there's just no support for the folks that can't, or don't know they should, be running a build named UNSTABLE.

So I guess that means it's time for me to do something else, because losing progress faster than I can rebuild it is decidedly not fun, especially when it's in a game from a developer that refuses to document that there is a problem.

**Comment by Bottinator22** [comment]
Literally the first thing I see when I click the link is build 138, not 126.2

**Comment by Anuken** [comment]
> The one where you find two pages of builds marked "pre-release" and then this?

Github (incorrectly) flags things as it wants because of the pre-release system, but it really seems like you're bending over backwards to find the wrong version here. You click that link, and **the very first thing you see** is 138. You are not using that version. That is all. Why you would scroll through so many releases just to find the "wrong" latest version is beyond me.

> Unfortunately, it's also no help to me because I can't sideload apps 

You don't need to, there's a beta program for that, which can easily be joined by tapping the big green "beta program" button on the play store.

> So I guess there's just no support for the folks that can't, or don't know they should, be running a build named UNSTABLE.

Indeed, there isn't.

> UNSTABLE ALPHA release actually is stabler

It isn't particularly stable, with serious issues and rough edges still, but that's irrelevant. I ask for the latest version because *126.2's codebase is a year old, with countless changes* and any reports from it are useless to me.
