### ISSUE TITLE
Fly building units bug

### ISSUE THREAD

**Issue by AdLeGeR** [Anuken/Mindustry#7551]
**Platform**: `Android 28`

**Build**: `alpha build 138.1`

**Issue**: *Game freezing when fly units buld something. It Take place then i go to location at first time*

**Steps to reproduce**: *Build the fly building units and try to build something like thorium walls in the large distance of units*

**Link(s) to mod(s) used**: `[deltanedas/rtfm:3.15.0]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.
[errors.txt](https://github.com/Anuken/Mindustry/files/9550848/errors.txt)
[  minProgress.zip](https://github.com/Anuken/Mindustry/files/9550863/minProgress.zip)

*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Already reported many times, still no known cause or steps to reproduce.
