### ISSUE TITLE
Crash and corruption 

### ISSUE THREAD

**Issue by Jotunheim12** [Anuken/Mindustry#7558]
**Platform**: mobile. iOS to be specific

**Build**: release build 126.3

**Issue**: game has randomly started to crash on the map “windswept islands”. This weird crash that has completely wiped all sector progress, has happened twice so far since the last one less than 10mins ago as I’m writing this.

**Steps to reproduce**: I haven’t got the slightest clue. All I’ve done is import a shit ton of building resources and build up everything as needed. And that’s when the crash and corruption happened

**Link(s) to mod(s) used**: (I haven’t actually placed any of the items in any of these mods so they might not be very useful as to finding this annoying problems source. But hey coding is weird so it might anyway)

vanilla extended: v1.82
Production mod: vA4.4.1
Opore mod: v69 (nice)
Unit turrets: v0.5

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

( I AM UNABLE TO SEND ANY SAVES BECAUSE I AM PLAYING ON IOS. Apple is a cunt. I would if I were able to)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
126.3 is quite outdated

**Comment by Anuken** [comment]
126.3 is more than a year old, and you have not attached any crash logs. The latest version is only available on [TestFlight](https://testflight.apple.com/join/79Azm1hZ).

**Comment by BlueWolf3682** [comment]
You can upload files from iOS if you have version 12 or later. the Files app is a neat thing to exist.

**Comment by Gift-505** [comment]
You can export via Settings->Game Data
