### ISSUE TITLE
I meet a bug?

### ISSUE THREAD

**Issue by some-one-of-men** [Anuken/Mindustry#7560]
**Platform**: `Windows 7 x64`

**Build**: `release build 126.2`

**Issue**: *我在初代核心附近建了一个指挥中心并调至“O”按钮(集合)，战机很快飞过来了，机甲们在后头。我了解指挥中心用法后拆了上面的指挥中心并在地图下方建了一个并让机甲们集结，但机甲在上方指挥中心拆后的空地挤在一起不下来，在下方建第二个指挥中心让他们集结才下来。
I build a Command Center nearby Core:Shard and turn the "O" botton(Rally) ,the Flares (plane) reach here quikly, the robots are in back. When I know waht can Command Center do, I break it and build another one to let robots get down the map. But robots stay the last Command Center disappear place and not move until I build second Command Center can let robot get down rally*

**Steps to reproduce**: *我不擅长英语，所以我希望你能理解我说的意思。我是新手，我在战役模式的173地区研究指挥中心的用处，在初代核心附近建了一个指挥中心，把按钮摁来摁去想知道这有什么作用，出现的文字和光圈让我以为控制中心只能控制范围的机甲。一会后，更换至“O”按钮(集合)时，我在工厂制造的星辉/曳光战机飞了过来，因为我的把机甲停放在地图下方，我明白控制中心应该能控制整个地图的机甲。在我打开地图寻找尖牙/匕首和爬虫/四条腿的爬行机甲有没来集合时，看到他们过来了，便拆了指挥中心，在下面重建了一个，让机甲们下来。切换“O”按钮时，战机先来到并围着指挥中心，但机甲几分钟还没下来，发现他们还在上去。跟他们上去，控制一个并指挥8个，V键回家后，他们还在往上走，最后挤在指挥中心消失后的空地中，我在下方的指挥中心把命令多次更改，他们就是不下来，直到我又建了第二个指挥中心并调至集合按钮时，机甲终于肯下来了。
I am not good at English, so I hope you can understand my said mean. I am new player, I played in Campain 173 for use Command Center, so I built a Command Center nearby Core:Shard, and want to know how this center can do, I changed and changed all botton , appeared text and shine round light let me think Command Center just can command area robot. later, when I turned the “O” botton(Rally), my Flares made by factory are flying here quikly, I stopped robot move at map down before, so I knew Command Center can command all robots of the map. When I opened map for finded Dagger and has four legs Crawler did them come rally, I saw them were coming now, so breaked Command Center, built another one under map, for robots get down. When I turned the “O” botton, Flares reach fast and around the Command center, but robots not get down in some minutes. I finded them still move up, so I followed them , control some one and Commanded 8 roborts, try let they run right. I hit the “V” on keybroad to back home, they are still move up. Last,they huddle togher in last Command Center disappeared place. I changed the commands on Command Center many a time, but they are not get down, untill I built the second Command Center and turned mean Rally botton, robots came down in the end.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.I forget save a picture. 
[Game Date.zip](https://github.com/Anuken/Mindustry/files/9558209/Game.Date.zip)
*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash. 
[Game Crash Log.txt](https://github.com/Anuken/Mindustry/files/9558203/Game.Crash.Log.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
126.2 is not the latest version. The command center no longer exists.

**Comment by some-one-of-men** [comment]
ok
