### ISSUE TITLE
Some questions about politics

### ISSUE THREAD

**Issue by laohuaji233** [Anuken/Mindustry#757]
I think Chinese (china)should be simplified Chinese and Chinese (taiwan)should be traditional Chinese.You knou,taiwan is part of china,and HongKong,Macao use traditional chinese too

**Comment by Anuken** [comment]
Are you referring to the names used in the language menu? I didn't come up with those; they're the translations provided by the Java locale library.

**Comment by laohuaji233** [comment]
yes,But I don't think it's appropriate.A steam player also gave this comment.

**Comment by Anuken** [comment]
What do you think it should be called, in Chinese? Which specific locale bundle does this need to be for? I can add a manual override of the locale display name.

**Comment by Schallfalke** [comment]
I made multilingual mods (including Chinese) in other game, so I could provide info.
Don't know you want the english name or localized name, so here I provide both:
Chinese (Taiwan) should be named as Traditional Chinese / 正體中文
Chinese (China) should be named as Simplified Chinese / 简体中文
