### ISSUE TITLE
Beam node Bug

### ISSUE THREAD

**Issue by NTPC2932** [Anuken/Mindustry#7573]
**Platform**: Windows
**Build**: 138.1

**Issue**: Beam-node Has negative power even though power voids are not connected to it, to fix the bug I have to place down a new beam node just to make it have power

**Steps to reproduce**: No idea, all I did was try to make a attack map in map editor, and this is the 2nd time I have encountered it.

https://user-images.githubusercontent.com/113569102/190306084-77fa0c5b-cf4c-4831-9cd8-2a4dfedc3d9d.mp4
 (a vid of me replacing the beam node with a new beam node, the power will come back afterwards)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Saves are mandatory.
