### ISSUE TITLE
(Player-indusable) softlock on level 2 (Aegis) (Ekir)

### ISSUE THREAD

**Issue by User-green** [Anuken/Mindustry#7581]
**Platform**: Android (but defenetly applies to all)

**Build**: `alpa build 138.1`

**Issue**: Softlock on level 2 (Aegis) (Ekir). If shildbraker nutral structure gets destryed, you can not progress any further without reseting campain data

**Steps to reproduce**: Just let enemy destry the structure. Optionaly you may try to destroy it youself.

**Link(s) to mod(s) used**: N/A

**Save file**: https://storage.tslp.tk/index.php/s/C4gnCNKpaBKQ8s6

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The shield breaker was removed in later versions.
