### ISSUE TITLE
Game Freeze When Destroying Building 

### ISSUE THREAD

**Issue by Ternesio** [Anuken/Mindustry#7584]
**Platform**: *Android 8*

**Build**: *138.1*

**Issue**: *First I entered campaign mode, then I entered sector 162, then because the sector was already in control, I tried to clear the remaining enemy buildings, but in the middle of the destruction, the game suddenly crashes and can't do anything. This bug does not only occur in sector 162, in other sectors the same bug occurs*

**Steps to reproduce**: *The bug can't be fixed, the only thing that can be done is exit the game and back in, I've tried to disable the mod, but it's the same, the game keeps crashing and freezing*

**Link(s) to mod(s) used**: *Since I've tried without the mod and it still fails too, so I'm not listing it*

**Save file**: [BackUp Save Game](https://drive.google.com/file/d/1s4VwxZiJRc8BNtaClu4htB0ld4ySBySA/view?usp=drivesdk) 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: [Crash Log](https://drive.google.com/file/d/1rxwYy-tU0AE7R1QRDq3dJ0QVk2E3-RDj/view?usp=drivesdk) 

Sorry for my English, I use translate.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Been reported many times, still cannot reproduce the issue.
