### ISSUE TITLE
Server only binding to IPv6

### ISSUE THREAD

**Issue by ZorudaRinku** [Anuken/Mindustry#7597]
**Platform**: Ubuntu 20.04.3 LTS aarch64
(Oracle Cloud Compute)
Linux instance-20220108-1634 5.11.0-1025-oracle #27~20.04.1-Ubuntu SMP Fri Jan 7 18:58:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Build**: 7.0 Build 138 - Alpha

**Issue**: Server is only binding on port :::6567 (IPv6) and not 0.0.0.0:6567
No logs or error is reported to the console
netstat (omitted other irrelevant port/server information):
```
ubuntu@instance-*****-****:~/mindustry/config$ sudo netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name       
tcp6       0      0 :::6567                 :::*                    LISTEN      2386428/java
```
So we see it is binding to ipv6 on :::6567 successfully but not ipv4 on 0.0.0.0:6567
Yes, this was done after the `host` command
Yes, I did open the port on the software firewall (though it shouldn't matter as it wont even bind so not a problem with UFW)
Yes, I did open the port on the virtual firewall in Oracles portal (though, again, shouldn't matter)

**Steps to reproduce**:
1. `wget https://github.com/Anuken/Mindustry/releases/download/v138/server-release.jar`
2. `java -jar server-realase.jar`
3. Check `netstat -tnlp`

**Save file**: Does not happen in-game

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. - lol k

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
My ISP doesn't even have IPv6 and frankly I know nothing about it, so if you have an issue with how the server works, you'll need to fix it yourself by digging through source.

**Comment by ZorudaRinku** [comment]
My server is not running on IPv6. This isn't an IPv6 problem. This is a.. server is not binding to an IPv4 interface problem. IPv6 is not required to find a resolution for this problem...

**Comment by Anuken** [comment]
I still have no idea what any of that means, how IPv6 binding is involved at all when many networks don't support it (while multiplayer still works fine), or what I'm supposed to do to fix it. 

I'm simply opening a socket/server on the specified port with Java's standard network library, and that has been working fine for years. This is the first time I've heard anyone mention the concept of something "not binding to a IPv4 interface"... so I cannot be of any help on the matter.

**Comment by Kropatz** [comment]
Hi, ran into the same issue and I think I found the cause. In `arc.net.Server#bind`  `new InetSocketAddress(tcpPort)` is used.
The implementation of that constructor uses `InetAddress.anyLocalAddress()` to select the local ip. This returns an IPv6 address (::) if IPv6 is supported, else it returns an IPv4 address (0.0.0.0)

Would be nice to have a server config option to disable IPv6, or an option to select the local address to listen to, or to listen on both addresses (if supported). 

My ISP also doesn't support IPv6, so I can't host a server for my friends right now.
