### ISSUE TITLE
Cultivator on 160% affinity tiles seem to overproduce based on expected values.

### ISSUE THREAD

**Issue by Yo0o0o** [Anuken/Mindustry#7607]
windows / v138 and BE

![image](https://user-images.githubusercontent.com/110904476/191708332-453a198f-a53c-4ff0-b6af-6fb0584b3326.png)

cultivator x (spore per second x boost) = total spores 

3 x (0.6x1.6) = 2.88

spore press need 3/s yet there's buildup in the cultivators even though it's supposed (?) to be lacking (2.88 out of 3)

edit: Cocktale on discord mentioned that it could possibly be efficiency squared, which seems to check out after some testing.

**Comment by Yo0o0o** [comment]
wait, how did the template get removed ? I'm sorry.

**Comment by end-me-please** [comment]
#designs when cultivator mechanics are mentioned on GitHub:

**Comment by end-me-please** [comment]
did some testing, and it looks like output on spore moss is pretty much *exactly* 2.2 times higher than expected. 

(expected: 0,6*2.2=1.32/s, observation: 2.9/s, 1.32*2.2=2.9)

looks like the multiplier is applied twice?

**Comment by end-me-please** [comment]
![image](https://user-images.githubusercontent.com/90796271/191761074-efc56e88-ad4d-40b3-a290-1c27cdbef918.png)
me when

maybe next time
