### ISSUE TITLE
add back command center

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry#7608]
**Platform**: pc windows 10

**Build**: 138 foo's client

**Issue**: i need command center for making a cinematic film or whatever

**Steps to reproduce**: you search for command center, but its not there

**Link(s) to mod(s) used**: none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No.

**Comment by rylid-umil** [comment]
> No.

reason

**Comment by Anuken** [comment]
nope

**Comment by rylid-umil** [comment]
why would removing the command center be a good change
like in campaign, for example like having the units rally up next to the attack spawn, whats the problem with that?

**Comment by rylid-umil** [comment]
the new command system, when controlling a unit will ovveride it's command center behavior
