### ISSUE TITLE
Multiplayer client does not receive Campaign Zone Requirement credit

### ISSUE THREAD

**Issue by abaines** [Anuken/Mindustry#762]
**Platform**: Windows (multiplayer client and server)

**Build**: 96 (multiplayer client and server)

**Issue**: Multiplayer client does not receive Campaign Zone Requirement credit

**Steps to reproduce**:
1. Start server player and client player with no campaign game data.
1. Play multiplayer map like Ground Zero (or any map that is required for a future map ( https://github.com/Anuken/Mindustry/blob/16f6b5185784148cb9a27266b971bfec4ebf0b67/core/src/io/anuke/mindustry/content/Zones.java#L97 suggests that in order to unlock Frozen Forest, player must get to at least wave 10 in Ground Zero).
1. Server starts the map (Ground Zero), and client joins a few second later (and otherwise never leaves the map)
1. During multiplayer, get to wave needed for map unlock (in this example, wave 10 of Ground Zero) (in single player, win or loss the player appears to get credit needed to unlock Frozen Forest) Also note that during this time the client _does_ see the popup message suggesting that they have completed the requirements to unlock a new map. https://github.com/Anuken/Mindustry/blob/cb929a72398ead43060bee236491b11e18e75c53/core/src/io/anuke/mindustry/core/Control.java#L148
1. End (issue reproduces in Win, not sure about loss) game 
1. (Not sure if important step, but listing anyways) have the server exit the victory (or defeat?) summary before client (this will cause the client to get a server disconnected message)
1. Now the client player does not have access to unlocked map (in this example Frozen ground)

And just in case it is important, I haven't specifically reproduced this with Ground Zero and Frozen Forest, but have seen it multiple times for future maps. For example Frozen Forest unlocking craters, and Frozen Forest unlocking Stained Mountains.

**Comment by abaines** [comment]
This also might happen for zone configuration requirements too.
https://github.com/Anuken/Mindustry/blob/2db3060a038af097010b9f9745500eafb8341f86/core/src/io/anuke/mindustry/type/Zone.java#L121

**Comment by Anuken** [comment]
This was fixed in the Steam version's latest release.

**Comment by abaines** [comment]
Thanks!
