### ISSUE TITLE
[IOS] Mod produces errors on mobile but fine on desktop

### ISSUE THREAD

**Issue by FredsMedia** [Anuken/Mindustry#7621]
**Platform**: `iOS x32`

**Build**: `release build 126.3`

**Issue**: *I got Mindustry for mobile today and I imported my desktop save (1 release apart). On mobile I got thrown many errors stating that an item wasn’t in the tech tree but gold mod needed it to be*

**Steps to reproduce**: *Export Mac save, import to mobile, launch mobile game.*

**Link(s) to mod(s) used**: `[Tom Petrou/[#25f12f]vanilla-extended[]:1.82, The Slaylord/goldmod:2.0 alpha b19, zeroCore/hackforall:0.1, qweryt/infinite-units:0.1, SMIPE444/infinity-cheat:2.1.444, 滞人/invincible-cheat-mod-v6:2.8.4, Jhrushbe/moardustry:0.10, deltanedas, Router and another guy/pictologic:1.5.8, EchoVespy/simplistic:0.8.1, sk7725/time-control:0.2, DeltaNedas/ui-lib:2.16.6]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.* (file is 30mb but limit is 25mb.) https://drive.google.com/file/d/1EQGYjwPXCmsqDCUH6fcaS08lPDoy-XCo/view?usp=drivesdk

**Crash report**: *N/A

**Screenshots**: 
![72396A56-3394-4CD8-B664-4A5F006D962F](https://user-images.githubusercontent.com/106362296/192136804-486fb465-898c-4dda-8b0c-eb62674cc45f.png)
![1EFC6976-F9D8-4F7A-86AD-FE1E4B6DA064](https://user-images.githubusercontent.com/106362296/192136811-76fb5c7e-6750-4969-95c6-87dfcfe0e7c1.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Apple doesn’t allow mods that contain executable code, maybe the mod isn’t a pure json mod

**Comment by FredsMedia** [comment]
I use the mod on a MacBook if that would help

**Comment by FredsMedia** [comment]
Link is up!

**Comment by FredsMedia** [comment]
Screenshots uploaded!

**Comment by Anuken** [comment]
As mentioned above, scripts are not supported on iOS (and you reported the issue on iOS), and you are running a version that is more than a year old.

**Comment by FredsMedia** [comment]
> As mentioned above, scripts are not supported on iOS (and you reported the issue on iOS), and you are running a version that is more than a year old.

How would I update further, nothing in the App Store.

**Comment by FredsMedia** [comment]
Apple am i right. Dropping/blocking basically everything and making everything difficult for devs.

**Comment by thesmal** [comment]
So that’s why I can’t find my mod (it’s a hjson and one js file)
