### ISSUE TITLE
Averts can not fly over cliffs, they burn in slag, drown in arkycite, and are not targeted by anti-air

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#7626]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

**Build**: Bleeding Edge 23234

**Issue**: Averts can not fly over any wall, cliff, or other obstruction. They drown in arkycite and burn in slag. They are not targeted by anti-air turrets. They pathfind around slag and arkycite.

**Steps to reproduce**: Build an Avert. Instruct it using command mode (shift) to fly over a wall, cliff, or otherwise, such as those in Peaks.

**Link(s) to mod(s) used**: None.

**Save file**: None needed. Tested in campaign and custom maps.

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
I have seen that this has been reported and supposedly fixed, but I am still having this issue.

**Comment by Anuken** [comment]
Units that spawned with the bug will remain on the ground. Make new ones.
