### ISSUE TITLE
Horizon does not automatically attack blocks or units

### ISSUE THREAD

**Issue by Mythril382** [Anuken/Mindustry#7630]
**Platform**: *Android*

**Build**: *BE 23239*

**Issue**: *Horizon does not automatically attack units or blocks when idle (not commanded to do anything) unlike other units, I'm guessing quad does the same since they both do the circle behavior*

**Steps to reproduce**: *Spawn horizon. Place enemy blocks. Spawn ground enemies. Horizon does not attack.*

**Link(s) to mod(s) used**: *Testing Utilities, Time Control*

**Save file**: [the save (zipped).zip](https://github.com/Anuken/Mindustry/files/9650429/the.save.zipped.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Horizon/Quad need to move to attack, other units don't.
