### ISSUE TITLE
Missing available languages in the Steam store page

### ISSUE THREAD

**Issue by galaipa** [Anuken/Mindustry#7635]
Recently Steam [added](https://store.steampowered.com/news/group/4145017/view/3325361214990632478) a bunch of new languages to select when indicating which languages do the games support.  The updated list of available languages can be found [here](https://partner.steamgames.com/doc/store/localization/languages). 

It might sound like a small thing, but this is very important for languages like Basque were only a few games are available. That's why I would like to kindly ask you to update the supported languages list.

Currently Mindustry has the following languages listed in the Steam page:  English, Spanish-Spain, Japanese, Portoguese-Portugal, Simplified Chinese, Traditional Chinese, French, German, Korean, Polish, Portuguese-Brazil, Russian, Ukranian, Italian, Czech, Romanian, Swedish, Vietnamese

By checking Mindustry's [source code](https://github.com/Anuken/Mindustry/tree/master/core/assets/bundles) (I might be looking in the wrong place?) I assume the following are missing: Belarusian, Bulgarian, Catalan, Basque, Danish, Estonian, Finnish, Filipino, Hungarian, Dutch, Serbian, Thai, Turkmen and Turkish

Thank you in advance

**Comment by Anuken** [comment]
Would it be completely accurate to list *all* of those languages on the page when some of them have not been updated by the community in a very long time? The extra languages you list may be severely outdated and adding them to the page may be misleading. Some, like the Basque bundle, have not seen in contributions in 2-3 years, and seem to be missing a fair bit of text.

**Comment by galaipa** [comment]
Fair enough. Didn't think on that. Do you have any method to calculate how much of each language is missing? Maybe defining a threshold could be a good compromise...

Anyway, being a bit selfish, my concern was specifically about the Basque language. Would you list the language if we get the translation back to 100% ? I would first contact the initial contributor to know hes plans (We are a small community, so I can get to him quite easily). If he doesn't plan to update the translation, or he needs help I would ping my colleagues at the basque gamer community [Game Erauntsia](https://gamerauntsia.eus/) or the [Librezale](https://librezale.eus/) free software basque localization group.

**Comment by Anuken** [comment]
If someone cares to update the language (now or in the future), I can add it without issue - I just want to make sure I'm listing languages that someone has an interest in, that aren't <50% complete.

**Comment by Anuken** [comment]
(Added.)

**Comment by galaipa** [comment]
Already talked with the original contributor, and decided that we will take care of updating the translation. Can't promise an ETA at the moment, but will ping you when it's ready.

Thank you!
