### ISSUE TITLE
Electrolyzers stop producing one liquid when another fills up.

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#7637]
**Platform**: M1 Mac

**Build**: BE build 23258

**Issue**: Electrolyzers stop producing a liquid, say, ozone, when the other liquid, say, hydrogen, fills up. This fucks up most automatic bases on Erekir, such as that on Caldera, and mandates that you keep incinerating or spilling your hydrogen to make sure your entire power grid doesn't shut down.

**Steps to reproduce**: Place an Electrolyzer. Fill it with water. Supply it with power. Allow hydrogen to fill. See how ozone stops being produced.

**Link(s) to mod(s) used**: None.

**Save file**: Not needed. It happens everywhere.

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
This can also shut down the power grids of Malis bases, rendering sectors trivial if you use vent power.

**Comment by Anuken** [comment]
Fixed.
