### ISSUE TITLE
Bundle in world processor returns null

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#7649]
**Platform**: Windows/Android (didn't test on other)

**Build**: v138.1

**Issue**: "Flush Message" command in world processor should get text from bundle if the key starts with "@", but it always returns null. Just look at the screenshots.
![image](https://user-images.githubusercontent.com/79508138/193447794-fb36b8de-455d-4d37-983f-7a8e57696eb2.png)
![image](https://user-images.githubusercontent.com/79508138/193447758-ad41dcdd-e558-4404-a62c-d9fcd709a3e0.png)
![image](https://user-images.githubusercontent.com/79508138/193447773-73cde18e-cd63-41f7-af45-39e9a5c8b217.png)

But if i try to get a value by this key from Core.bundle:
![image](https://user-images.githubusercontent.com/79508138/193447830-7730d5d0-34a5-417a-b92b-f9c5b3ca4287.png)

**Steps to reproduce**: Place a world processor in editor. Find any key in Core.bundle and use "Print @key" command in the processor. Then use "Flush Message" command and test the map.

**Link(s) to mod(s) used**: No mods, only my script to execute JS.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
`@maps.none` is a variable, not a string.
