### ISSUE TITLE
My air units on serpulo is acting weird

### ISSUE THREAD

**Issue by Minneapolis109** [Anuken/Mindustry#7653]
**Platform**: *Android

**Build**: *23293*
 
**Issue**: *Today i was playing mindustry 23293 when i discover a weird bug happening on my air units first time i noticed it when i was playing on desolate rifts with my megas and quad ( tier 3 and tier 4 support air units ) at first they were just doing their thing like building broken stuff but then i notice it all of my air units isn't showing the circle yellow thing on their back ( thruster or rocket effect ) they are also not moving their body while moving into other places like ( just the body frozen why moving ) they also appears to have a ground units pathfinding when i try to command them to go to a certain place . I also see them drown on water after making them go over it on sandbox.*

**Steps to reproduce**: *it sometimes happens when i try to use the "command" button on them. *

**Link(s) to mod(s) used**: *i have mods but i check it and they weren't on.*

**Save file**: *couldnt send a save file due to it being 64.56 mb.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *[bruhdustry.crashlogs.zip](https://github.com/Anuken/Mindustry/files/9695581/bruhdustry.crashlogs.zip)*

---

*Place an X (no spaces) between the bracke

ts to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, already fixed.
