### ISSUE TITLE
Units get stuck on blast doors

### ISSUE THREAD

**Issue by mcsper** [Anuken/Mindustry#7655]
**Platform**: MAC

**Build**: Alpha build 138.1

**Issue**: Units get stuck on blast doors when moving as a group and had one stell that couldn't go through by himself until i changed his destination a lot of times.
<img width="335" alt="image" src="https://user-images.githubusercontent.com/12717798/193599605-f0c6d3ff-2c71-40a8-b914-cf76190b6dce.png">

**Steps to reproduce**: Select units and tell them to move somewhere that requires moving through a blast door.
**Link(s) to mod(s) used**: None

**Save file**: 
[sector-erekir-88.msav.zip](https://github.com/Anuken/Mindustry/files/9698218/sector-erekir-88.msav.zip)

*The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Units get stuck sometimes, this is known. Most recalculate eventually.

**Comment by Lamby777** [comment]
I mean regular doors
