### ISSUE TITLE
ui crash

### ISSUE THREAD

**Issue by littlekatter330** [Anuken/Mindustry#7660]
windows

139

some mods have ui that crashes the game 

[crash-report-10_04_2022_18_32_24.txt](https://github.com/Anuken/Mindustry/files/9711587/crash-report-10_04_2022_18_32_24.txt)

please fix in 139.1

**Comment by end-me-please** [comment]
..pretty sure that the mod authors have to fix this, not anuke

**Comment by Anuken** [comment]
You have a ridiculous amount of mods, this is not a vanilla bug.

**Comment by littlekatter330** [comment]
@Anuken 2 mods were causing this issue unit factory and ui lib
