### ISSUE TITLE
bug with the command mode

### ISSUE THREAD

**Issue by Slate-FM** [Anuken/Mindustry#7661]
Steam

Steam Build 139

Poly and Mega units start repairing buildings with-out having damage (I didn´t tested with other units yet)

updating from build 126.2 to the build 139 then enter to campaing mod to a captured sector (doesn't matter what sector it is) where you have mega or poly units, select them and put it in the repair mode from the command mode and they will start to repair not damaged buildings (repair damaged buildings too)

[saves.zip](https://github.com/Anuken/Mindustry/files/9712397/saves.zip)

pd: i speak spanish so I did my best writing this, so truly sorry if it is not understandable 

---

- [X] I have updated to the latest release to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce any issues, loading random saves and spawning megas has them correctly repair *damaged* blocks.
