### ISSUE TITLE
mindustry b139 crashes on startup

### ISSUE THREAD

**Issue by RisenFalcon** [Anuken/Mindustry#7665]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows 10

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
139

**Issue**: *Explain your issue in detail.*
Crash upon startup

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Open mindustry. Game crashes with IndexOutOfBounds index can't be >= size: 1 >= 1

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
unsure

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash-report-10_05_2022_14_48_09.txt](https://github.com/Anuken/Mindustry/files/9719199/crash-report-10_05_2022_14_48_09.txt)
[crash-report-10_05_2022_14_48_56.txt](https://github.com/Anuken/Mindustry/files/9719200/crash-report-10_05_2022_14_48_56.txt)
[crash-report-10_05_2022_14_51_05.txt](https://github.com/Anuken/Mindustry/files/9719201/crash-report-10_05_2022_14_51_05.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is caused by a mod, not vanilla.

**Comment by Bottinator22** [comment]
> @Anuken there are more mods that crash the game like that

Then it's a mod problem

**Comment by littlekatter330** [comment]
@Bottinator22  and a game problem

**Comment by Anuken** [comment]
Mods crashing the game because they can't handle UI changes is very much a mod-only problem. This is not something I will be doing anything about.
