### ISSUE TITLE
Enemies invisible on The Onset map

### ISSUE THREAD

**Issue by SearAgate** [Anuken/Mindustry#7674]
**Platform**: Windows 10

**Build**: Steam Build 139, Beta v7-testing

**Issue 1**: On map The Onset, I can see the first wave of enemies but afterwards both enemies and their buildings/cores are invisible to me. I can see them firing, my tanks and turrets attack them like normal. (After Saving and quitting and going back they showed right back up)

**Steps to reproduce**: Switched to Beta version on steam, continued an old campaign on the new world. Started The Onset, play until first wave of enemies.

Not sure if I should add another bug report for this one but it's not that big so I'll just put it here.

**Issue 2**: I don't think this is intended but on map Aegis the tutorial text is hidden by the fog of war when starting the map. 
![20221007221246_1](https://user-images.githubusercontent.com/115334217/194688860-d74026c6-ef86-429a-8cf0-85ebc1b08d8f.jpg)

**Link(s) to mod(s) used**: None used

**Save file**:  [Save.zip](https://github.com/Anuken/Mindustry/files/9738401/Save.zip)

Not sure if I put this in a separate bug report for this one but it's not that big so I'll just put it here.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce first issue (no image provided, I don't know what yo mean), second one is **not** a bug.
