### ISSUE TITLE
envEnabled does not work

### ISSUE THREAD

**Issue by Ribbons0121R121** [Anuken/Mindustry#7678]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
139
**Issue**: *Explain your issue in detail.*
EnvEnabled wants a number, and 0 should be any. 0 instead causes the unit to simply vanish in any environment.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Make any unit be envEnabled=0
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
any mod
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
litterally any save, not save specific whatsoever
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, 0 is not 'any'.

![image](https://user-images.githubusercontent.com/10100000/194732311-5fb13489-b582-4b0d-b692-588fd6abcc4a.png)
