### ISSUE TITLE
*building* in unit locate always *null*

### ISSUE THREAD

**Issue by ilya034** [Anuken/Mindustry#7682]
**Platform**: *Windows 10*

**Build**: *BE build 23337*

**Issue**: *when searching an enemy building(turret) using unit locate, the field "building" is always "null"*
![image](https://user-images.githubusercontent.com/68101303/194765493-2ccae905-3b88-41e3-9ebc-b65313797eb4.png)
![image](https://user-images.githubusercontent.com/68101303/194765500-0575ea28-f0dd-426a-bf32-2fd56d9ae665.png)
![image](https://user-images.githubusercontent.com/68101303/194765600-bd9cfc0d-5d24-40bd-96e6-651c3cc91405.png)

**Save file**: *[bug-rep.zip](https://github.com/Anuken/Mindustry/files/9741903/bug-rep.zip)*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Intentional, you can only locate allied buildings.
