### ISSUE TITLE
Colors in menu header

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#7689]
**Platform**: *Any. *

**Build**: *v139*

**Issue**: The menu header gets an additional [accent] color which breaks all color-codes

**Steps to reproduce**: Use Call.menu method and add any color-codes in the title.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Just see the difference. And this is really annoying.
![image](https://user-images.githubusercontent.com/79508138/194884532-73556318-87a0-49ae-b363-ec69a0dd15aa.png)
![image](https://user-images.githubusercontent.com/79508138/194884549-3d258f03-6995-4d6e-bbc1-0cedb1a012b5.png)

May you add a new DialogStyle only for server-side menus? Or just do something with it ;-;
![image](https://user-images.githubusercontent.com/79508138/194885074-1ab03b4a-3e52-468a-83f3-44c8a3361637.png)

*And yes, i remember [https://github.com/Anuken/Mindustry/issues/5966](#5966)*

**Comment by Anuken** [comment]
It's still not a bug as per last response, you weren't supposed to tint it, so this is more of a suggestion... but if you really want the tint gone, I can remove it.
