### ISSUE TITLE
Erekir The Split uncompletable

### ISSUE THREAD

**Issue by SmirkyCat** [Anuken/Mindustry#7691]
**Platform**: *Windows*

**Build**: *steam build 139*

**Issue**: *Erekir > the split (map) does not have a restart button, and accidentally deleting the container leaves you with not enough tungsten to rebuild the one container*

**Suggested fix**: *Make it so you cannot delete the container if there is 1 or less on this map, or at least keep this restriction until it's been moved. I still don't know how to move containers because I wasn't given another chance to try it. Or add a button to the menu to restart the sector if the tutorialization isn't done.*

**Steps to reproduce**: *delete the container instead of picking it up*

**Link(s) to mod(s) used**: *nun*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is an Abandon button in the sector info menu.

**Comment by SmirkyCat** [comment]
OK thats fine, but just as a note i don't think its good for a level to become impossible in the first 3 minutes before anything attacked... or just add a note there on how to restart? idk

**Comment by KayyAyeAre** [comment]
you can still drag tungsten to the core using your unit
