### ISSUE TITLE
Logic Displays not functioning

### ISSUE THREAD

**Issue by EnglishDotpl** [Anuken/Mindustry#7695]
This may be a straightforward issue, yet it disables  me- and perhaps other people- from quite a selection of games, helpful indicators, or *other functions*. It is irrelevant of whether the logic was before loading or just being built. If it's on single campaign or multiplayer servers. Making an alt save or opening the app on another device does not appear to resolve it! 

Reference screenshot; neither the tic-tac-toe in the middle, nor the logic to the far right are displaying it:
![Screenshot_20220918-233727](https://user-images.githubusercontent.com/77670664/195129518-bd490463-e8f8-45a7-90d5-5602a47b3ada.png)

**Comment by Anuken** [comment]
Invalid issue, template not used. I don't know how you bypassed it, but if you are using the Github app - don't.

**Comment by Anuken** [comment]
Even if you delete the template, the "bug" tag remains, so there's probably something else going on here.
