### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by somebody4269** [Anuken/Mindustry#7696]
Android

V7,build 139

Game crashed while I was trying to launch to sector 124.I thought,it happened because of my schematic for core,but game crashed again when I launched only with core "foundation".

I play without mods.

[sector-serpulo-180.zip](https://github.com/Anuken/Mindustry/files/9758716/sector-serpulo-180.zip)

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 139
OS: Linux xnull (aarch64)
Android API level: 29
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: none (vanilla)

> OutOfMemoryError: 'OutOfMemoryError thrown while trying to throw an exception; no stack trace available'

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No log generated due to lack of memory; you likely need a better device with more RAM.
