### ISSUE TITLE
game crashes in ingame editor

### ISSUE THREAD

**Issue by Redmountain0** [Anuken/Mindustry#7699]
**Platform**: Windows

**Build**: v139

**Issue**: game crashes in ingame editor

**Steps to reproduce**: Editor -> open any map -> remove all core -> open ingame editor -> select anything in power tab

**Link(s) to mod(s) used**: Nothing

**Save file**: 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[last_log.txt](https://github.com/Anuken/Mindustry/files/9764600/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, already reported.
