### ISSUE TITLE
The Basin is bugged :(

### ISSUE THREAD

**Issue by SmirkyCat** [Anuken/Mindustry#7707]
**Platform**: *Windows*

**Build**: *steam 139*

**Issue**: *So this dumb map nuked my previous base without warning, so I restarted with the idea to pre-prepare for the nuke. I know the AI starts having a fit once your base is nuked, so in 10 minutes I destroyed both the enemy cores. Uh oh, the game still thinks there's 2 cores left. Nothing I can do about that! Sure I can abandon but this should probably be fixed in some way (maybe stop people from raiding before the nuke?).*

**Steps to reproduce**: *1) destroy all enemy content before the 1 core that triggers the nuke
2) set up your base and establish tier 2 spiders (which is possible)
3) blast them across the great wall to the minimal available space you're given access to (which i dont think is possible in time if step 1 is fixed)
4) once the roster of spiders is full, destroy the core that triggers the nuke (which is definitely not possible in time if step 1 is fixed)
5) Before the nuke goes off,  simply pile up tier 2 hydrogen tungsten spiders and ramrod the enemies to near-extinction 🗡️ (displayed in the file)
6) Shell base blows up, losing virtually no important stuff, and cores are already gone. but the game still wants me to blow up 2 enemy cores!*

**Link(s) to mod(s) used**: *no mods, just the erekir vanilla*

**Save file**: *https://mega.nz/file/IlQXSRDA#nPMy1m37j5DlNuObDsRrkJ0djnZhQpCiA-RsUcd8Hz8*

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by traincrisis** [comment]
interesting............
