### ISSUE TITLE
Missing Vent on Seige Campaign Map?

### ISSUE THREAD

**Issue by mercury19** [Anuken/Mindustry#7708]
**Platform**: Windows and Android

**Build**: Bleeding Edge 23373

**Issue**: It's not exactly a major bug or anything, but there is a chemical combustion generator setup by the first enemy core on Seige that has a Vent Condenser on top of a spot with no vent. Presumably does not hinder the enemy, but could hinder the player in setting up that area as their own base.

**Steps to reproduce**: After beating Seige, I downloaded the map by itself from the github to see how the enemy bases were setup. I found that I could switch the player and enemy teams in the custom game rules, so I went into sandbox that way and found that there was a weird power void around the first core. I noticed the condenser producing no water despite having power from a power source, so I de-constructed the setup and found that there was no vent. Upon going back to my campaign save, I found that there was no vent in the equivalent spot. Initially found on Android, but confirmed on Windows as well.

**Link(s) to mod(s) used**: N/A

**Save file**: [23373SeigeBug.zip](https://github.com/Anuken/Mindustry/files/9781639/23373SeigeBug.zip) (Android Save)

**(Crash) logs**: No Crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Can't find it, the map is huge, at least provide a screenshot.
