### ISSUE TITLE
modded turret construct blocks

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#7710]
**Platform**: *doors*

**Build**: *"latest"*

**Issue**: *modded turret construct blocks*
![image](https://user-images.githubusercontent.com/61173114/195773266-f7cd8fa6-c03e-4734-b88b-f549188f6d15.png)

**Steps to reproduce**: *modded turret construct blocks*

**Link(s) to mod(s) used**: *modded turret construct blocks*

**Save file**: *modded turret construct blocks*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

(i tested this with many mods and saves, just go ham)

**(Crash) logs**: *modded turret construct blocks*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [modded turret construct blocks] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [modded turret construct blocks] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by littlekatter330** [comment]
@BlueWolf3682 what mod is that

**Comment by end-me-please** [comment]
modded turret construct blocks
