### ISSUE TITLE
Game stuck at loading screen

### ISSUE THREAD

**Issue by kapzduke** [Anuken/Mindustry#7712]
**Platform**: Windows

**Build**: 23374

**Issue**:  see title. i tried externally deleting some mods and screenshots but it doesn't fix. reinstalling the client doesn't work either.

**Steps to reproduce**: install the mod, reload the game and the bug will ensue.

**Link(s) to mod(s) used**: https://github.com/KayyAyeAre/Dusted-Lands

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Works on my machine.

**Comment by kapzduke** [comment]
@Anuken here's [last_log.txt](https://github.com/Anuken/Mindustry/files/9785724/last_log.txt) if that helps

**Comment by Anuken** [comment]
According to the log, the game loaded successfully, there's nothing aside from some random noise from some invalid saves (which is normal).
