### ISSUE TITLE
Broken UI.

### ISSUE THREAD

**Issue by Ivan452s** [Anuken/Mindustry#7714]
The UI disappears and the screen seems to move up and to the right when you Alt-Tab. It's hard to hit the buttons with the mouse. It is repaired by changing the full-screen mode off and back on. Found it on v7 Beta Mindustry, Steam.
![image](https://user-images.githubusercontent.com/74957731/195922910-b4459a83-dcbb-421f-a3cc-02453ff94e95.png)

**Comment by Anuken** [comment]
Template not filled in (how did you bypass it?), invalid issue + cannot reproduce.

**Comment by Ivan452s** [comment]
> Template not filled in (how did you bypass it?), invalid issue + cannot reproduce.

Idk, I just Alt-Tabbed from the game.

**Comment by Catchears** [comment]
Does pressing c get the UI back?

**Comment by Ivan452s** [comment]
> Does pressing c get the UI back?

No.
Btw sorry for late answer, been busy and couldn't check mail or github.
