### ISSUE TITLE
Shared tech trees

### ISSUE THREAD

**Issue by throwitthefuckaway** [Anuken/Mindustry#7716]
**Platform**: *Android*

**Build**: *139, 7V BETA*

**Issue**: *Remember that time Anuken said "_The tech tree of Serpulo and Erekir shouldn't really be together in a normal survival run_"?

If you set these settings in the map editor to <any> instead of <Serputo> or <Erekir> in previous builds, you can still by pass the message saying no to <any> in survival, it just let you go, nothing is said and the all the features work just as normal

I really didn't want to see this feature go, but if it is Anuken choose, then it only fells right to help them with this*

**Steps to reproduce**:
*1. Go to "Edit" in previous builds
1½. Go to your map, "Map info" > "Rules" > "Planet"
1⅖.Put it to the state of whatever thing it was to <any>
1⅗.Save it
1⅘.Load it up with the new map file in the newest building (139)
2.Enjoy survival and all tech trees*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *https://drive.google.com/file/d/1wx6ay0NfzTGoHkX4xDw0omEL9V5dY4Dv*

**(Crash) logs**: *_No_*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug, I even explicitly stated when changing it that "older maps/saves will be unaffected".
