### ISSUE TITLE
Mod update doesn't apply directly

### ISSUE THREAD

**Issue by Redmountain0** [Anuken/Mindustry#7717]
**Platform**: Windows

**Build**: v139 beta

**Issue**: when update mod with "Import Mod", after reloading, changes don't apply, and it applies at next reload
(I only tested on java mod; idk it happens another mod type)

**Steps to reproduce**: import mod and reload -> update mod (import mod with same id) and reload -> changes don't apply -> reload more -> changes applied

**Link(s) to mod(s) used**: I don't think it's important, but I'll upload it
https://github.com/Redmountain0/Zephirum

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce issue. Importing a jar mod, then importing it again later immediately applies the changes on next restart.
