### ISSUE TITLE
bundle entry not used / part of tutorial not shown

### ISSUE THREAD

**Issue by Catchears** [Anuken/Mindustry#7718]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
latest - 23381 - [commit](https://github.com/Anuken/Mindustry/commit/8a2e7af49ea484b808268ca3f7504f1e5141eeca)

**Issue**: *Explain your issue in detail.*
The bundle entry `onset.research2` (`Begin researching [accent]factories[].\nResearch the \uf74d [accent]cliff crusher[] and \uf779 [accent]silicon arc furnace[].`) is never used. I find it unclear if the player is meant to figure that out alone or if it's just not shown, would've opened a PR otherwise.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
play tutorial / search code

**Save file**: *The (zipped) save file you were playing on when the bug happened.*
N/A, found in editor

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's in the list of objectives, which may be skipped if you already researched the relevant block.

![image](https://user-images.githubusercontent.com/10100000/195989724-0ae6a75f-ae6d-48e3-8050-0a0b64217623.png)

**Comment by Catchears** [comment]
Ah - completely correct, didn't even consider that as an option.
