### ISSUE TITLE
Sector Generate doesn't show cliffs properly

### ISSUE THREAD

**Issue by Slotterleet** [Anuken/Mindustry#7722]
**Platform**: Windows & Android. Probably affects other platforms but I cannot test that.

**Build**: beta build 139

**Issue**:
Sector Generate option in editor mode does not work with cliffs properly. Even though the cliffs themselves _do_ generate, you cannot see them for whatever reason.
Here's how it looks like from Sector Generate:
![20221015215306_1](https://user-images.githubusercontent.com/62336673/196003828-db2fb24c-b12d-4471-bf87-fc82e1e08e40.jpg)
And here's a screenshot from campaign mode for comparison.
![20221015215358_1](https://user-images.githubusercontent.com/62336673/196003856-b55c1d1c-a31b-402c-ab1e-87406a3029a2.jpg)

**Steps to reproduce**:
- Open the editor and press Sector Generate in the menu.
- Pick any planet that uses cliffs in its generator (here I used our own asteroids.)
- Even though the cliffs _did_ generate, you cannot see them neither in-editor nor in-game.

**Link(s) to mod(s) used**: https://github.com/TeamOct/fictional-octo-system/tree/1.1

**Save file**: https://drive.google.com/file/d/1GdMqmwGmVTNt254eFb5g7wcuTVVAcm15

**(Crash) logs**: Not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not interested in fixing issues like this unless they occur with vanilla planets. Cliffs in generators are not really a supported feature.
