### ISSUE TITLE
Used save file from 138.1 then updated game to 139.0 and later to be 23382 and this happened

### ISSUE THREAD

**Issue by Karyl256** [Anuken/Mindustry#7724]
![Screenshot_20221015-221323_Mindustry BE](https://user-images.githubusercontent.com/115658627/196005928-51ad8f2d-54db-4f90-8a38-f77b3483297a.jpg)
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
BE 23382

**Issue**: *Explain your issue in detail.*
I cant explain it

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Imported (build)139.0 file on BE 23382

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[idk what happened.zip](https://github.com/Anuken/Mindustry/files/9793013/idk.what.happened.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. You need to research it now.

**Comment by littlekatter330** [comment]
nice one @Anuken
