### ISSUE TITLE
hey its the same issue again

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#7728]
**Platform**: *doors*

**Build**: *"latest"*

**Issue**: *woooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo (planet is being read as null)*
![image](https://user-images.githubusercontent.com/61173114/196028537-adfd6b63-0b8f-4bb7-96e7-c5d9a17bf636.png)
![image](https://user-images.githubusercontent.com/61173114/196028549-5c1a8f1e-137d-4d6f-9b88-693cb4940e4b.png)

**Steps to reproduce**: *wait a second as i push to exotic, then update*

**Link(s) to mod(s) used**: *what do you think*

**Save file**: *h*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

h

**(Crash) logs**: *read upper screenshot - the full log is horrendous*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by woodjecket** [comment]
It might come when the sector loads earlier than planet. I fixed it by editing the file name to make sure that the sector is loaded later.
