### ISSUE TITLE
Bridges/Land Fill on Liquid Blocks

### ISSUE THREAD

**Issue by mActUx06** [Anuken/Mindustry#773]
Is this still an option? Just asking. I mean it's for the units path since AI script sometimes doesn't let them drown to their destruction. They recognize the the path near deep water block as a go and will still continue from that direction where the water is. Due to their movement speed, going away from the water is too late and resulting to their destruction. I saw this as a solution. If ever this is necessary.

 Also, this implemented, players can also change some pathways for incoming waves (e.g. tar fields' open area just below the wave spawn is kind of lacking of use; similar same concepts)

If so, this might be the first buildable thing (that can be built into)/(that is absorbed with the map, meaning it would be permanent.)

**Comment by Anuken** [comment]
Follow the issue template. And no, I'm not planning on implementing this.
