### ISSUE TITLE
BuildVisibility admin

### ISSUE THREAD

**Issue by Xarond12** [Anuken/Mindustry#7731]
**Platform**: *Windows* 

**Build**: *139*

**Issue**: *when modding i wanted to use new BuildVisibility(() => Vars.player.admin) to make blocks from mod visible to only admins *

**Steps to reproduce**: *download mod, place it to server mod folder and mindustry mod folder and then join server give yourself admin, and try to build anything from mod*

**Link(s) to mod(s) used** [mod.ZIP](https://github.com/Anuken/Mindustry/files/9794922/mod.ZIP) 

**Save file** [save.ZIP](https://github.com/Anuken/Mindustry/files/9794931/save.ZIP) 

**(Crash) logs**: *.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[mod.ZIP](https://github.com/Anuken/Mindustry/files/9794922/mod.ZIP)

**Comment by Anuken** [comment]
You are not reporting a problem here. This is a modding question. The issue tracker is not a place to ask for mod help.

**Comment by Xarond12** [comment]
i forgot to add that blocks building infinitely
