### ISSUE TITLE
BuildVisibility i think bug

### ISSUE THREAD

**Issue by Xarond12** [Anuken/Mindustry#7732]
**Platform**: *Windows*

**Build**: *139*

**Issue**: *sorry for opening another issue but i forgot to add some thing, when modding i wanted to use new BuildVisibility(() => Vars.player.admin) to make blocks from mod visible to only admins but after joining my server with this mod and placing modded block it starting building but it takes infinity time, on server hosted through game it working normally and building with time 0 s

**Steps to reproduce**: * download mod, place it to server mod folder and mindustry mod folder and then join server give yourself admin, and try to build anything from mod*

**Link(s) to mod(s) used**: *[save.ZIP](https://github.com/Anuken/Mindustry/files/9795175/save.ZIP)*

**Save file**: *[save.ZIP](https://github.com/Anuken/Mindustry/files/9795177/save.ZIP)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is not a bug, and **this is not the place** to report issues with your mod not working.`Vars.player.admin` doesn't make sense - it only checks for *local* player being admin, which doesn't even exist on headless servers (-> crash) and will fail to work for anyone aside from the server host.
