### ISSUE TITLE
random wave generator doesnt add tier 5 units 

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#7734]
**Platform**: *"        "*

**Build**: *"                "*
**Issue**: *the wave generator refuses to generate any tier 5 units into the waves - is this intended? if so, why?*
![image](https://user-images.githubusercontent.com/61173114/196062717-91ef3d09-90c7-4423-b927-554ce1288831.png)
*(i have hit this button at least four times now)*

**Steps to reproduce**: *create a map, go to waves, and smack "random"*

**Link(s) to mod(s) used**: *.*

**Save file**: *.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
T5 units are bosses
