### ISSUE TITLE
Full Screen glitch?

### ISSUE THREAD

**Issue by SocksThePirate** [Anuken/Mindustry#7737]
![Screenshot_20221017-100116](https://user-images.githubusercontent.com/115984106/196136542-32a83e05-dc7f-4153-be67-f7a0a583b2b1.png)
**Platform**: `Android 33`

**Build**: `release build 126.2`

**Issue**: *Pixel 7 causes the game to not go to full screen*

**Steps to reproduce**: *every time you start the application*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
(Not the latest version)

**Comment by SocksThePirate** [comment]
> (Not the latest version)

Latest version available on the google play store

**Comment by Anuken** [comment]
I don't have such a phone and I'm not interested in supporting it.

**Comment by SocksThePirate** [comment]
> I don't have such a phone and I'm not interested in supporting it.

Why are you not interested in supporting the Pixel phone lineups? Alot of people have their devices and its a pain it doesn't fit the screen properly :(

**Comment by Anuken** [comment]
I simply don't care. Android support is of the lowest priority, and if some new phone comes out that suddenly breaks my game despite it working fine on every *other* phone, that's not something I want to deal with.

**Comment by SocksThePirate** [comment]
> I simply don't care. Android support is of the lowest priority, and if some new phone comes out that suddenly breaks my game despite it working fine on every _other_ phone, that's not something I want to deal with.

Fair enough have a good day
