### ISSUE TITLE
Unable to set the default core of new planet

### ISSUE THREAD

**Issue by woodjecket** [Anuken/Mindustry#7739]
**Platform**: 

**Build**: 139

**Issue**: The return of the method 'getDefaultLoadout' is unable to be configured as other cores instead of coreNucleus so the default core is unable to be changed with JSON.

**Steps to reproduce**: With this mods. I forgot this yesterday.

**Link(s) to mod(s) used**: [json-planet.zip](https://github.com/Anuken/Mindustry/files/9809982/json-planet.zip)

**Save file**: None

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no bug here, it's simply a feature never implemented for JSON.
