### ISSUE TITLE
Poly doesn't assist building once unselected in command mode

### ISSUE THREAD

**Issue by t1k2y** [Anuken/Mindustry#7748]
**Platform**: `Mac OS X x64`

**Build**: `beta build 139`

**Issue**: *Poly no longer assist in building once binded and unbinded in command mode*

**Steps to reproduce**: 
*While pressing shift, highlight and bind some Poly. Then, left-click an arbitrary position to unbind the Poly. Issue is present when player starts building new blocks.
Notes:
-Tested on Windswept Island and Overgrowth, no processors binding Poly
-Fixed by using a processor to bind and unbind them
-Not tested with other units*

**Link(s) to mod(s) used**: `[sk7725/time-control:0.2]`

**Save file**: *[bugreport.zip](https://github.com/Anuken/Mindustry/files/9843466/bugreport.zip)*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce the issue, I do not know what  you mean by "bind". "Highlight and *bind*"? Bind with what, a processor? How is that related to selection? Selecting and deselecting poly units does not change their behavior. Did you mean *right*-click?

The save you provided cannot be used; I need **map** saves, not your entire campaign data.

**Comment by t1k2y** [comment]
By bind, I meant controlling the units using command mode.
I'm not really sure how to export map saves but I assume this is it? 
[Maps.zip](https://github.com/Anuken/Mindustry/files/9843526/Maps.zip)

**Comment by Anuken** [comment]
That's not a bug. When you command a unit to a position, *you are telling it to stay there.* If you want it to build again, you need to switch them back to assist/rebuild mode.

**Comment by t1k2y** [comment]
Ah, I assumed the units will go back to their usual behaviour after deselecting. Sorry to have wasted your time
