### ISSUE TITLE
Potential Bug found-Research related

### ISSUE THREAD

**Issue by Endless7777** [Anuken/Mindustry#7749]
**Platform**: *The type of device you were playing on - Windows

**Build**: *The build number under the title in the main menu. Required. 
Steam Build 139 the V7 Beta mentioned in your last post.

**Issue**: Directly after finishing "Basin" with all available research done and all previous maps captured, I started the map "Marsh" and the first objective is to research the oxidation chamber, when I looked at the research tree it was nowhere to be found and there was no way to progress further, I assume it is a bug.

I must capture Marsh to unlock Revine and Peaks next. but I'm stuck on the research Oxidation chamber.

**Steps to reproduce**: i played all maps in order as they were unlocked from lowest threat to highest, and researched all research as it became available, when Basin was the last map to beat, I had all research done, once it was captured I then went directly into Marsh and was unable to progress because I could not see the research for Oxidation chamber-the requirement to progress further. I explored Marsh, and built up a base a bit, but nothing changed.

**Link(s) to mod(s) used**: no mods used

**Save file**: 
[Mindustry V7 BETA.zip](https://github.com/Anuken/Mindustry/files/9843726/Mindustry.V7.BETA.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: not a crash issue

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You never used the electrolyzer, and as such, ozone and hydrogen were never researched.
