### ISSUE TITLE
Game doesn't close properly

### ISSUE THREAD

**Issue by Damgam** [Anuken/Mindustry#775]
**Platform**: Windows 10, Steam

**Build**: Steam 96

**Issue**: When i close the game, it's still "running" on steam without any Mindustry process in task manager

**Steps to reproduce**: Just turn off the game on steam

Additional Details:
Running Steam Beta (with new library)

**Comment by Damgam** [comment]
It "closed" itself when i've turned on another game. Steam bug i guess.

**Comment by Anuken** [comment]
Should be fixed next release, in the case that it isn't a Steam bug.
