### ISSUE TITLE
Scathe Range

### ISSUE THREAD

**Issue by Rajarshi393** [Anuken/Mindustry#7750]
**Platform**: Android

**Build**: 23437

**Issue**: Scathe range is not 162 tiles in campaign 
![Screenshot_2022-10-22-19-35-11-445_io anuke mindustry be](https://user-images.githubusercontent.com/85704301/197343910-a664a003-8ee3-43e6-bf33-3ec2e24dadd2.jpg)

**Steps to reproduce**:  I didn't do anything this is how i completed seige and crossroad map

**Link(s) to mod(s) used**: none

**Save file**: 

---

*Place an X (X) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No, it is.
