### ISSUE TITLE
Died before being able to finish the tutorial

### ISSUE THREAD

**Issue by UnderSampled** [Anuken/Mindustry#7754]
**Platform**: `Android 32`

**Build**: `fdroid build 139`

**Issue**: *Died before being able to finish the tutorial.*

**Steps to reproduce**: 
  - Build the beryllium walls before powering the turrets, accidentally setting off the first wave.
  - Frantically try to find a way to bring resources to the turrets
  - Watch helplessly as the enemy forces ignore your two tanks and destroy your constructor drone (and other things)
  - Successfully destroy the enemy tanks with your own
  - Wonder why you can't build anything to recover
  - Realize that you are controlling a tank and cannot construct anything.
  - Wonder why it didn't say game over
  - Realize that the objective is to destroy the enemy core
  - Send your other tank up to attack it, losing it to an enemy turret
  - Go the other way and wait a forever for your remaining tank to plink away at the enemy core confidently knowing that once it's destroyed the match will be over and you can get a new constructor.
  - Destroy the enemy core!
  - Be given the next task, to construct a new core...
  - Write a bug ticket in frustration, wondering why there isn't a "game over" screen when you lose all ability to construct anything ever again. Or maybe some protection to at least let you finish the tutorial!

**Link(s) to mod(s) used**: `none`

**Save file**: 
[dead-tutorial.zip](https://github.com/Anuken/Mindustry/files/9846798/dead-tutorial.zip)

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
#

**Comment by Anuken** [comment]
> Realize that you are controlling a tank and cannot construct anything.
> when you lose all ability to construct anything ever again.

There's a control hint for this at the bottom of the screen. Unless I'm missing something, there is no possible way for you to get locked in a state of "not being able to construct anything ever again".

![image](https://user-images.githubusercontent.com/10100000/197399358-2dcfe0af-f5ec-4b47-b50b-0fdd79d1882f.png)

**Comment by UnderSampled** [comment]
Nope.

![Screenshot_20221023_110259_Mindustry](https://user-images.githubusercontent.com/328009/197399597-6d323349-4483-4aa2-91d6-01c5a5da55da.jpg)

Perhaps it's because I'm not dead, as I'm controlling a tank somehow? It follows my screen around.

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/197400270-6f128ce7-a80d-476c-a6cd-b9a01ae92ff7.png)

I see it in the latest version, which means that:

- You've skipped it without noticing (unlikely), or
- You're not running the very latest (BE) version, so that hint doesn't show up yet.

Either way, there is no bug here - you simply need to respawn.

**Comment by UnderSampled** [comment]
I have no idea how to respawn!

I'm on mobile, so I can't press v.

Also, I'm using the latest Fdroid version, which is pretty recent and why I was playing again (I played several years ago. A lot has changed!)

On October 23, 2022 11:18:10 AM EDT, Anuken ***@***.***> wrote:
>![image](https://user-images.githubusercontent.com/10100000/197400270-6f128ce7-a80d-476c-a6cd-b9a01ae92ff7.png)
>
>I see it in the latest version, which means that:
>
>- You've skipped it without noticing (unlikely), or
>- You're not running the very latest (BE) version, so that hint doesn't show up yet.
>
>Either way, there is no bug here - you simply need to respawn.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Anuken/Mindustry/issues/7754#issuecomment-1288136070
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Sincerely,
Stephen Christie

**Comment by Anuken** [comment]
It tells you how to respawn in the screenshot I posted.

> which is pretty recent

Not recent enough; things change quickly in the beta version.

**Comment by UnderSampled** [comment]
Okay. Sorry I didn't see your second screenshot, replying from email.

**Comment by Plastel** [comment]
two words




skill issue

**Comment by UnderSampled** [comment]
For the tutorial, any skill issue is a bug.

On October 23, 2022 8:26:27 PM EDT, Plastel ***@***.***> wrote:
>two words
>
>
>
>
>skill issue
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Anuken/Mindustry/issues/7754#issuecomment-1288246493
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Sincerely,
Stephen Christie

**Comment by Plastel** [comment]
> Sincerely, Stephen Christie



Anyway, some tips to kickstart:

Core does not accept sand

Do not try to spend all your energy on one thing, try to distribute all your available energy beetwen these things

Silicon
Tank production
Drills.

**Comment by UnderSampled** [comment]
Haha! I learned it didn't accept sand, so that's just a corner. The power probably got destroyed in the fight.
