### ISSUE TITLE
Fog in the Basin map does not recede when ships brought near

### ISSUE THREAD

**Issue by Johngi5** [Anuken/Mindustry#7756]
**Platform**: *Windows*

  **Build**: *Beta build 139*

**Issue**: *The fog in the southern part of the Basin map (in Erekir) does not recede when units (or at least Eludes) are brought near it. There are clearly walls and turrets on the other side of the wall, which can be seen by hovering over them and by the fact that friendly units will shoot at them, but they do not shoot back.*

**Steps to reproduce**: *I started playing the Basin map, expanded the silicon production given by the default base, made some ships, and then attempted to scout the area around the base. Upon trying to fly south, my units just hit the fog as if it was a border wall, but they still kept shooting.*

**Link(s) to mod(s) used**: *None.*

**Save file**:  [basinbug.zip](https://github.com/Anuken/Mindustry/files/9847054/basinbug.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional, the map is not uncovered yet.
