### ISSUE TITLE
a mod crashes my game and i cant delete the mod

### ISSUE THREAD

**Issue by Lolypopiwi** [Anuken/Mindustry#7757]
windows

steam build 139

my game crashes

i downloaded 3 mods, ui lib unit factory and time control , i restarted the game and it crashes when i enter to the game after the loading screen, i cant delete the mods, i tried opening the mods folder but theres nothing

i dont have the links, names: ui lib, unit factory, time control.
all mods are in the mod browser

[crash-report-10_23_2022_13_36_22.txt](https://github.com/Anuken/Mindustry/files/9847436/crash-report-10_23_2022_13_36_22.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
ui-lib is blacklisted now, either wait for the update or find the correct mod folder for it.

>  i tried opening the mods folder but theres nothing

If the mods are being loaded, they are either subscribed to on the workshop, or in the mod folder. You must be looking in the wrong place (did you browse local files from Steam properties?)

**Comment by Lolypopiwi** [comment]
i searched in the wrong folder, thx
