### ISSUE TITLE
Issues related to Serpulo T4 Air Support Unit (Quad)

### ISSUE THREAD

**Issue by MuMingWYH** [Anuken/Mindustry#7758]
**Platform**:
Android

**Build**:
beta build 139
bleeding-edge build 23443

**Issue**:

- Quad's status effect(s) are hidden behind the unit itself. They can only be seen when the Quad is moving.

Normally, most status effects (such as burning, freezing, melting, etc.) are visible on units whether they are idling or moving.

- Quad do not have the "appearance" effect (the white color) when it is spawned. (tested by using world-processor, not payload source)

**Steps to reproduce**:
Apply status(es) to the Quad, whether using in-game mechanics or world-processors.

**Link(s) to mod(s) used**:
Vanilla, no mod is used.

**Save file**:
bleeding-edge build 23443
[Quad Test.zip](https://github.com/Anuken/Mindustry/files/9848856/Quad.Test.zip)

**(Crash) logs**:
No crash logs

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MuMingWYH** [comment]
Since the Quad is relatively old unit, is this a bug or a hidden feature?

**Comment by MuMingWYH** [comment]
Updated with one more issue

**Comment by Anuken** [comment]
Not a bug, it's rendered above the effect layer. The alternative would be making it under the layer, which would make bombs it drops spawn on *top* of it.
