### ISSUE TITLE
Units Require Ammo cannot be turned off if it was already on

### ISSUE THREAD

**Issue by Funny132** [Anuken/Mindustry#7761]
**Platform**: Windows

**Build**: Steam Build 139

**Issue**: Maps that had Units Require Ammo turned on before the setting got removed still have it turned on, and cannot (to my knowledge) have it turned off anymore.

**Steps to reproduce**: Find a map that had Units Require Ammo turned on before the setting got removed.

**Link(s) to mod(s) used**: [This one.](https://github.com/xzxADIxzx/Scheme-Size)

**Save file**: 
[Bug Report Save File 2_.zip](https://github.com/Anuken/Mindustry/files/9857216/Bug.Report.Save.File.2_.zip)
As for a specific map, if you want to know the one I found the issue on, it's the [Boxfort PvP map](https://github.com/Anuken/Mindustry/files/9857273/Boxfort.PvP.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Once again, regarding the bottom one, I found [an issue](https://github.com/Anuken/Mindustry/issues/5762) that seems _related_, but it isn't the bug I'm reporting here.

**Comment by Anuken** [comment]
Yes, you cannot turn it off. I'm not planning on changing this; either make a new map, or load it in an older version and turn it off there.

**Comment by Darkness6030** [comment]
why didn't you remove it completely?

**Comment by Anuken** [comment]
It would break mods.
