### ISSUE TITLE
Could not find com.github.Anuken.Mindustry:core:v139.

### ISSUE THREAD

**Issue by CREAsTIVE** [Anuken/Mindustry#7764]
i m can't install mindustry core using MindustryModTemplate
```
ModName:main: Could not find com.github.Anuken.Mindustry:core:v139.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/Anuken/Mindustry/core/v139/core-v139.pom
  - https://www.jitpack.io/com/github/Anuken/Mindustry/core/v139/core-v139.pom
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Anuken** [comment]
This has nothing to do with the game itself - JITpack randomly stops working, use MindustryJitpack as the repo instead.

**Comment by Chi-Re** [comment]
如果你出现了MindustryJitpack的错误
`CrimsonStar:main: Could not find com.github.Anuken.MindustryJitpack:core:v146.
Searched in the following locations:
  - https://maven.aliyun.com/repository/google/com/github/Anuken/MindustryJitpack/core/v146/core-v146.pom
  - https://maven.aliyun.com/repository/central/com/github/Anuken/MindustryJitpack/core/v146/core-v146.pom
  - https://maven.aliyun.com/repository/public/com/github/Anuken/MindustryJitpack/core/v146/core-v146.pom
  - https://repo.maven.apache.org/maven2/com/github/Anuken/MindustryJitpack/core/v146/core-v146.pom
  - https://www.jitpack.io/com/github/Anuken/MindustryJitpack/core/v146/core-v146.pom
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

你可以将MindustryJitpack改为Mindustry

**Comment by Anuken** [comment]
Copy-pasting from Discord:

> # PSA to everyone experiencing build errors with dependencies!
> 
> JITPack is broken. To fix it, you need to do several things to your `build.gradle` script:
> 
> 1. Add the new repository:
> Insert `maven{ url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }` [before the JITPack repostiory](<https://github.com/Anuken/MindustryJavaModTemplate/blob/master/build.gradle#L9>).
> 
> 2. Make sure you have the right dependencies:
> `compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"`
> `compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"`
> 
> **DO NOT** use `MindustryJitpack` here, it's broken now. These repositories are **case sensitive**. See [this line](<https://github.com/Anuken/MindustryJavaModTemplate/blob/master/build.gradle#L32>).
> 
> 3. Make sure you're depending on the right version:
> `mindustryVersion = 'v145'` or `mindustryVersion = 'v145.1'` - **the v is important.** See [this line](<https://github.com/Anuken/MindustryJavaModTemplate/blob/master/build.gradle#L20C5-L20C30>).
> 
> If you have an unmodified build script, simply replace the contents of your `build.gradle` with [this](<https://github.com/Anuken/MindustryJavaModTemplate/blob/master/build.gradle>).
