### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Bamnaman** [Anuken/Mindustry#7769]
**Platform**: `Android 31`

**Build**: `release build 126.2`

**Issue**: `Strange bug related to changing the direction of a titanium conveyor after picking it up and dropping it using a mega`

**Steps to reproduce**: `1: Possess a Mega and start commanding a group of Megas.
2: Pick up a conveyor belt (I only tried with a titanium conveyor, but it may work with others)
3: Drop it back in the same spot (it should change direction)
4: Attempt to change its direction in any way by building over it.`

**Link(s) to mod(s) used**: `none`

**Save file**: [mindustry save.zip](https://github.com/Anuken/Mindustry/files/9864763/mindustry.save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
(not the latest version)

**Comment by Anuken** [comment]
126.2 is not the latest version.
