### ISSUE TITLE
App Store version doesn't work on macOS

### ISSUE THREAD

**Issue by markomitranic** [Anuken/Mindustry#7770]
**Platform**: macOS 13.0 (22A380) Ventura | Macbook Pro M1 Pro 32G

**Build**: N/A, game won't start. Fresh off the AppStore.

**Issue**: The game, as downloaded from App Store, does not start (see screenshots). There has been a 1* review about this for 3 years now.

**Steps to reproduce**: Download game. Click icon.

**Link(s) to mod(s) used**: []

**Save file**: {}

**(Crash) logs**: N/A, menu can't be started.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

<img width="372" alt="Screenshot 2022-10-26 at 13 16 45" src="https://user-images.githubusercontent.com/10811624/198013278-006f5c48-2f12-42d0-8ca5-df424043308e.png">
<img width="565" alt="Screenshot 2022-10-26 at 13 16 39" src="https://user-images.githubusercontent.com/10811624/198013288-f0edc99a-7e80-4675-848d-5a28230c015f.png">
<img width="1302" alt="Screenshot 2022-10-26 at 13 16 33" src="https://user-images.githubusercontent.com/10811624/198013292-97dd22e2-a9e6-4e9a-83ce-f0429709232c.png">

**Comment by end-me-please** [comment]
Is that the classic version? i don’t think that’s supported anymore..

 try downloading the game from itch.io

(also i don’t think m1 is supported)

**Comment by Anuken** [comment]
It worked on my machine at the time - I don't have a functional mac to even test it on, and that's a *prehistoric* version, so I recommend refunding. I'll remove it from the store.

**Comment by Anuken** [comment]
![Снимок экрана от 2022-10-26 08-16-37](https://user-images.githubusercontent.com/10100000/198024145-8e6cb90e-9f21-4308-b07d-2dd441053f64.png)

Nope, I can't even remove it from the store, so the only thing I can say is "don't buy it."

**Comment by markomitranic** [comment]
Just for fun, I skipped the Gatekeeper and ran the binary and it works just fine. In fact it seems to be running without Rosetta, unless I'm missing something.

In any case, this is a simple developer certificate issue, regardless of if it's downloaded through the App Store, or from itch.io :)

**Comment by Anuken** [comment]
> P.P.S. When can we expect a real M1 native version? Its obviously doable, since it works just fine on iOS, and its the exact same APIs and build system.

Probably never, because I don't have an M1 machine to test or build on, and I have no use for one outside of this specific task; they are also very expensive.

> I have downloaded the itch.io version 6. 

Unlike the one of the app store, the itch version is not signed at all, and I do not plan to have it signed, as it is a massive undertaking for bundled Java programs. You'll need to remove the quarantine the flag there to make it work.
