### ISSUE TITLE
Game Crash on Poly Repair Action

### ISSUE THREAD

**Issue by Madelyn-of-Hell** [Anuken/Mindustry#7772]
**Platform**: macOS

**Build**: *Bleeding Edge Build 23439*

**Issue**: *Entering sector 219 causes the game to crash with error message 
"oh no
A crash has occured. It has been
saved in:
/Users/________/Library/Application
Support/Mindustry/crashes/crash-
report-10_27_2022 13 05 25.txt
NullPointer:
Cannot invoke
"mindustry.game.Team.isAl()" because
"team" is null, and cannot be reopened without restarting*

**Steps to reproduce**: *sector 219 Between waves 13 and 14 -- repair a large copper wall with some polys, Game Crashes*

**Link(s) to mod(s) used**: *https://github.com/sk7725/TimeControl*

**Save file**: 
[sector-serpulo-219.msav.zip](https://github.com/Anuken/Mindustry/files/9875253/sector-serpulo-219.msav.zip)
(I'm pretty sure this is what you're referring to. If not, please tell me and i'll find it)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crash-report-10_27_2022_10_48_57.txt](https://github.com/Anuken/Mindustry/files/9875262/crash-report-10_27_2022_10_48_57.txt)
[crash-report-10_27_2022_10_50_36.txt](https://github.com/Anuken/Mindustry/files/9875263/crash-report-10_27_2022_10_50_36.txt)
[crash-report-10_27_2022_13_05_25.txt](https://github.com/Anuken/Mindustry/files/9875264/crash-report-10_27_2022_13_05_25.txt)
(3 Uploaded to demonstrate that this happens every time I open the sector, not just the initial time I triggered the glitch

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
23439 is not the latest BE version.

**Comment by Madelyn-of-Hell** [comment]
My apologies; I originally found the glitch in 23439 and then replicated it int he latest version. I assumed that was what the 'latest version' box at the bottom was. very sorry about this...
