### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by Jotunheim12** [Anuken/Mindustry#7779]
Whenever I attempt load into the erekir sector “basin” the game crashes when the new sector starts to load in. It’s always at then end of the animation 
I’m on iOS using v7 with TestFlight on an iPhone 7

**Comment by Anuken** [comment]
Cannot reproduce any crashes on that map on an iPhone simulator. **You have not filled in the template or provided any crash logs**, which are required. Do not use the Github mobile app for submitting issues, I am told it doesn't show templates.

**Comment by Jotunheim12** [comment]
I’m new to the bug report stuff my bad. I did figure out what the problem was though. It was the classic mod error loop I think
