### ISSUE TITLE
Bug"inv waves"

### ISSUE THREAD

**Issue by Animedesd** [Anuken/Mindustry#7789]
**Platform**: `Android 12`

**Build**: `beta build 139`

**Issue**: *Atlas,enemies spawn in wall and it inv. We capture all cores and now i cant leave from atlas and waves inv.*

**Steps to reproduce**: capture all cores and rejoin. Was in co-op.*

**Link(s) to mod(s) used**: `none`

**Save file**: *i cant it was in campain. *

**Comment by Anuken** [comment]
I don't understand what you mean, and you have not provided a save.

**Comment by Animedesd** [comment]
> Я не понимаю, что вы имеете в виду, и вы не предоставили сохранение.

How i can give save file?
