### ISSUE TITLE
research not unlocking

### ISSUE THREAD

**Issue by vencorduser** [Anuken/Mindustry#7797]
**Platform**: *Windows

**Build**: *build  v139

**Issue**: i cannot research the steam generator, its locked and it says research ??? i have researched silicon,graphite and completed the craters. 

**Steps to reproduce**: *unknown

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: 
[save data.zip](https://github.com/Anuken/Mindustry/files/9912907/save.data.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by vencorduser** [comment]
(the mods are not related to research and the mod zip files are in the save folder)

**Comment by Anuken** [comment]
Pump water first.
