### ISSUE TITLE
My main bot stuck and disappeared

### ISSUE THREAD

**Issue by Mannshoch** [Anuken/Mindustry#7798]
**Platform**: Android Tablet

**Build**: 139

**Issue**: *My main bot stuck and disappeared*

**Steps to reproduce**: i collected wrong materials from distributors

**Save file**: [(invalid) (1).zip](https://github.com/Anuken/Mindustry/files/9913156/invalid.1.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
(the latest version is 140)

**Comment by Anuken** [comment]
That is an entire game save, not a save file.

**Comment by Mannshoch** [comment]
what's the difference and where do I find the other save button?

**Comment by Anuken** [comment]
The entire game save is *all* your saves. I don't know which save to load.

Saves can be exported individually as files in the save/load dialog.

**Comment by Mannshoch** [comment]
![Screenshot_20221102-234645_Mindustry](https://user-images.githubusercontent.com/7795891/199617065-1c89b40f-78b4-4519-a193-6cb56b0b164f.jpg)
ther is no entry.

@end-me-please 139 is the latest release on fdroid

**Comment by Mannshoch** [comment]
![Screenshot_20221102-234645_Mindustry](https://user-images.githubusercontent.com/7795891/199617065-1c89b40f-78b4-4519-a193-6cb56b0b164f.jpg)
there is no entry.

@end-me-please 139 is the latest release on fdroid

here the screenshot if i start the campaign
![Screenshot_20221102-235842_Mindustry](https://user-images.githubusercontent.com/7795891/199618410-51cb5e04-1ded-471f-a4a2-c9cd9c40435e.jpg)

**Comment by Anuken** [comment]
That is not a bug. You are controlling a router. Tap your icon in the top left.

**Comment by Mannshoch** [comment]
ah strange. Is that a new function?
never used this until now. What could i do with that?
