### ISSUE TITLE
Transport visuals

### ISSUE THREAD

**Issue by 24110802** [Anuken/Mindustry#7803]
**Platform**: Windows 10

**Build**: BE 23525

**Issue**: small visual bugs - ducts tangent to unload points and reinforced conduits tangent to junctions
![image](https://user-images.githubusercontent.com/40762980/199661122-7d2cfd48-b074-4164-a675-da367f678643.png)

**Steps to reproduce**:

**Link(s) to mod(s) used**: 

**Save file**:

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RandomInsultedCoder** [comment]
UNPLAYABLE!!!
