### ISSUE TITLE
Units & turrets are not attacking enemy's structures automatically

### ISSUE THREAD

**Issue by Sector171** [Anuken/Mindustry#7804]
**Platform**:

Android

**Build**: 

V140

**Issue**: *Explain your issue in detail.*

As in the title, you need to order the units/turrets to attack enemy's structures only Serpolu units(Erekir units are fine), they though attack enemy's units automatically

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Just play using Serpolu units, first I thought it was new change till I realized that the game is literally unplayable and sure you will not make a thing like this, you have to order the units to attack everything every belts ...etc it is just unplayable.

**Link(s) to mod(s) used**:

NA/ I disabled all mods

**Save file**:

NA

**(Crash) logs**:

NA

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
Intended. Maybe anuke could just make turrets shoot those things when the stuff it normally shoots is gone.

**Comment by commiedic** [comment]
Surely this is t as intended if one sides tech works and the other doesn't like it did in v139.

Plus it is very annoying on mobile to have to manually select and shoot each individual block.

Unless the idea is to make us use logic?

**Comment by Anuken** [comment]
~~It's very surprising that something this game-breaking took two days to report~~

**Comment by Erisfiregamer1** [comment]
~~Multiple days actually, they've always done that. Huge annoyance.~~

**Comment by Anuken** [comment]
> Huge annoyance.

So if you're here on Github and you've known about it for days, why didn't you say anything? Strange thing to complain about after it's fixed now. It takes less than 5 minutes to open an issue ~~especially if you don't attach a save~~.

**Comment by Erisfiregamer1** [comment]
> > Huge annoyance.
> 
> So if you're here on Github and you've known about it for days, why didn't you say anything? Strange thing to complain about after it's fixed now. It takes less than 5 minutes to open an issue ~especially if you don't attach a save~.

- I just assumed it was an intended feature and suffered with it.
- If I had KNOWN it wasn't intended, I'd probably have reported it ~~with a fucking save~~.
