### ISSUE TITLE
Serpulo Completion achievement failing to function

### ISSUE THREAD

**Issue by Bottinator22** [Anuken/Mindustry#7811]
**Platform**: Linux

**Build**: Steam 140.1

**Issue**: Despite me having Planetary Launch Terminal, and even forcing it to have waves again via console, I still don't have the Serpulo Completion achievement from it for whatever reason.

**Steps to reproduce**: 
Have an older save that already had the Planetary Launch Terminal captured, go to Campaign

**Link(s) to mod(s) used**: None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[bug.zip](https://github.com/Anuken/Mindustry/files/9933568/bug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed (on the Steam end, no update or code changes necessary)
