### ISSUE TITLE
addition

### ISSUE THREAD

**Issue by OMEGA6403** [Anuken/Mindustry#7812]
Is there anyway for you to make an online version of this because i love this game but im on Crome OS (Sorry discord is blocked)

**Comment by OMEGA6403** [comment]
also Linux is blocked

**Comment by Anuken** [comment]
This is not a bug report.

**Comment by Bottinator22** [comment]
(ChromeOS _is_ Linux, it just restricts you from using certain Linux features)

(we also will not and probably cannot help you with this)
