### ISSUE TITLE
Sublimate bought weed from the gas station (Sublimates look odd on payload conveyors)

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#7813]
**Platform**: M1 Mac

**Build**: Unstable Alpha 140.1

**Issue**: Sublimates look wacky and aren't colored with their ammo type when in a payload state.

**Steps to reproduce**: Make a sublimate with a payload source, large constructor, or otherwise. Put it on a payload conveyor. Fill it with something if you want. It looks wacky!

**Link(s) to mod(s) used**: None

**Save file**: None.

**(Crash) logs**: None.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
<img width="923" alt="image" src="https://user-images.githubusercontent.com/108166075/199868807-2087dc86-ffc5-46c6-93b3-1cedd8483d94.png">

**Comment by Anuken** [comment]
Not fixing.
