### ISSUE TITLE
Material dropper not working anymore

### ISSUE THREAD

**Issue by Cookiemagination** [Anuken/Mindustry#7816]
Platform: Windows 11 - 64 bit

Build: `steam build 126.3`

Issue: When playing in the mapeditor, I wanted to try out my new researched unit, so I build the construction chain for it. But the material dropper doesn't deliver any materials anymore, no matter which one I select.

Steps to reproduce: Build the material dropper (don't know the exact name, as I'm playing in german, but one of the farthest down blocks in the menue with the conveyer belts etc.
Select any material you want, place conveyer belts close to it so the dropper knows where to deliver the materials out to, but then nothing comes out of it.

Mods used: none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

Sorry but I didn't find any save files, when only playing in the mapeditor.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- as there are no open issues currently and I have the latest version, I assume I don't have to look through already closed incidents.

**Comment by Anuken** [comment]
> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME,

**Comment by Cookiemagination** [comment]
This issue is not closed and it would be very kind of you to not close something right away, instead ask a question if something is unclear..

I forgot to mention I build the blocks in the editor but then chose the option "Edit ingame" but there the material dropper is still not working.

**Comment by Cookiemagination** [comment]
Also I would gladly deliver a save file but after the "edit ingame" option there is only the option to leave, instead of saving and leave, so I'm pretty sure there is no save file for that. If there is, feel free to enlighten me.

I just want to help make this game better...

**Comment by end-me-please** [comment]
no blocks will work correctly when you use in-game editing. you have to save the map + create a custom game using the map
