### ISSUE TITLE
Fog of war isn't finished.

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#7819]
Numerous effects show through dynamic fog such as bullets, explosions, beams, and the rubble from destroyed buildings.

The minimap updating of changes to visibility is incomplete. Changing teams, capturing or gaining cores from a setNet, or units revealing terrain far away from the player camera show empty space in the minimap when there are actually structures present. The minimap successfully updates when panning the player camera over the space with missing map information.

If bullets are being displayed in fog areas, that means the clients are being sent hidden information, which means client mods can be written to cheat by revealing fog of war.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Numerous effects show through dynamic fog such as bullets, explosions, beams, and the rubble from destroyed buildings.

This is intentional, and I've seen other RTS games do this. Bullets and "fighting effects" get sent/displayed even in fogged areas. I don't see it as a problem and I don't plan to change it.

> If bullets are being displayed in fog areas, that means the clients are being sent hidden information, which means client mods can be written to cheat by revealing fog of war.

Yes. There is no good workaround for this, especially as far as buildings are concerned. I am aware. That being said, clients seeing *bullets* is intentional. If a unit shoots from a fogged area, that information needs to be synced, so the bullet is visible properly if it ever reaches a non-fogged area.

> The minimap updating of changes to visibility is incomplete. Changing teams, capturing or gaining cores from a setNet, or units revealing terrain far away from the player camera show empty space in the minimap when there are actually structures present. The minimap successfully updates when panning the player camera over the space with missing map information.

Known, but there is no (performant) way to fix this yet, and I've never noticed it throughout testing.

**Comment by Larofeticus** [comment]
Welp. Can't use a broken feature. Too bad as I really liked the way it added uncertainty to my server.

**Comment by Anuken** [comment]
And for what it's worth...

> Changing teams

...does not reproduce the issue on my end at all (both in survival and PvP on a local server... new structures appear despite me not moving my camera in range of any of them)

> units revealing terrain far away from the player camera show empty space in the minimap when there are actually structures present.

...does not reproduce the issue either, with units commanded to a far away location in complete darkness while my camera is at minimum zoom and starting at the minimap. **This is why I ask for a save and steps to reproduce, which you have ignored.**

> Welp. Can't use a broken feature. 

Sure, if you find that "broken".

**Comment by Larofeticus** [comment]
Sure the conditions that cause it seem to be narrower than I said.

A save doesn't capture it because it's a process effect, have a video instead. https://youtu.be/8h8Tg8AaRbo

Not being about to secure a feature against cheat-mods is already 100% reason enough for me to discard it.

**Comment by Anuken** [comment]
> Not being about to secure a feature against cheat-mods is already 100% reason enough for me to discard it.

Reasonable, but I'm afraid it's going to stay that way. While units in fog are not sent *unless they're shooting*, buildings are always there internally. It's not viable to simulate anything about an enemy base or their logistics network when the client literally doesn't know half of it is there - where do the items of a conveyor leading into fog go? The client doesn't *know* anything about its end destination, so everything would desync immediately, and that's just a trivial example.

**Comment by Garen7** [comment]
Wouldn't it be best for servers that want to use fog of war to disable mods in that case if possible?

From what I've seen theres a lot of mods out there that could already be considered cheating such as automatically placing optimal drill formations or automatically feeding factories by telling the player controlled unit to pick up and drop materials for the factories.

**Comment by Anuken** [comment]
Servers can't force clients to disable mods - and in the end, anyone can make a client that simply ignores that request, or a custom client altogether. There is no way to detect "genuine" clients either (yes, I've heard a million suggestions for detection schemes).

**Comment by Garen7** [comment]
dang, unfortunate 😦
