### ISSUE TITLE
Idle units no longer auto fire on enemy cores in range.

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#7823]
Server/client environment is the same as i've described #7685 though now i'm bumping both client and server up to v140.1

Units placed within firing range of an enemy core do nothing. They used to shoot at it. Possibly also true with other enemy buildings. Units _do_ still automatically fire at enemy units. Effect is present on erekir and serpulo. 

Saw it happening on my server, saved the game, loaded it, and units went back to acquiring targets normally.

Went onto another v140 (dunno if .1 or .0 since that isn't displayed) server and saw the same problem. The other server i tried it on was a lazy map that mixed planets (so i don't know which planet it was supposed to be, or an "any" map) I had a dagger standing near an enemy bastion and it wouldn't shoot unless directly ordered to.

I see there is #7804 and well this feels related to that, but this is still present. It couldn't be intended with the save/loaded game behaving differently from the live server version.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> though now i'm bumping both client and server up to v140.1

So did you change the version before or after this report? How about actually filling in the template so I know what you're running exactly and the save it happens on?

> Went onto another v140 (dunno if .1 or .0 since that isn't displayed) server

> I see there is https://github.com/Anuken/Mindustry/issues/7804 and well this feels related to that, but this is still present. It couldn't be intended with the save/loaded game behaving differently from the live server version.

But the server version is **extremely important**, and the only thing that matters. 140.1 is the update that fixed it, and unit targeting is server-side, so it doesn't matter what client you have.

> but this is still present

![image](https://user-images.githubusercontent.com/10100000/200078408-fe951c4b-a197-4a35-9195-c6d0369e542b.png)

No, it isn't. This is on a local dedicated server. Based on previous reports I'd guess you didn't update your server properly. 

However, I can't even test the scenario properly to compare - because, once again, **where is your save?** Do you think the rules don't apply to you for some reason? I have it in all caps for a reason. It doesn't *matter* whether you think it's an issue with the client only, I could still have tested it on a server.

**Comment by Larofeticus** [comment]
status
[11-04-2022 21:56:26] [I] Status:
[11-04-2022 21:56:26] [I]   Playing on map Evict / Wave 1
[11-04-2022 21:56:26] [I]   2 units / 0 enemies
[11-04-2022 21:56:26] [I]   60 FPS, 222 MB used.
[11-04-2022 21:56:26] [I]   No players connected.
version
[11-04-2022 21:56:29] [I] Version: Mindustry 7-beta official / build 140.1
[11-04-2022 21:56:29] [I] Java Version: 17.0.1

**Comment by Larofeticus** [comment]
ugh this is gonna be "you can't build a new version in place you have to start over from scratch every time" again

**Comment by Anuken** [comment]
Works on my end, it seems. Unless the unit in question was already targeting the core manually...

![image](https://user-images.githubusercontent.com/10100000/200082015-494bd434-ac12-4774-b409-feb0390480d9.png)

> annoying that the save file name is just a number 

You can specify a file name when saving (e.g. `save blarg`)

**Comment by Larofeticus** [comment]
Yeah, i just built from a fresh clone and loaded it onto both servers, 15 minutes ago or so and that took care of it. Annoying that building in place is dysfunctional enough to act normal and report the correct version, but not have changed things under the hood.

Is there some sort of gradlew clean option that i can use to get rid of whatever lingering artifacts it isn't overwriting, or am I stuck doing symlink monkeying to move a completely separate install into place every time there is a version upgrade?

I did save the file as "units_dont_shoot" but when i go into the filesystem to copy it over it's just 6.msav beside 1 through 5 msav

**Comment by Anuken** [comment]
> Annoying that building in place is dysfunctional enough to act normal and report the correct version, but not have changed things under the hood.

I don't understand what you're doing here... how are you building and pulling? I've never had an issue with pulling and rebuilding, and neither has anyone else, as far as I know. Cleaning has only historically been necessary in very, very specific scenarios.

> I did save the file as "units_dont_shoot" but when i go into the filesystem to copy it over it's just 6.msav beside 1 through 5 msav

I tested the feature before using it, and it worked fine on my end. Were you saving on the client...?

**Comment by Larofeticus** [comment]
so i started with in the past: 

git clone https://github.com/Anuken/Mindustry.git
cd Mindustry
git checkout v140
./gradlew server:dist -Pbuildversion=140

Some of this is redundant, I think? Does the Pbuildversion argument care at all what tag is checked out when it runs? Anyway, with the limited information I could find, that was the first process i found that i could reliably use to set things up, i'm sure there is a better true way to do it.

My instinct is that I should be able to checkout/PbuildVersion newer updates in the same folder and not have to mess with anything else. I found when upgrading 126 to 139 that checking out v139 and running "./gradlew server:dist -Pbuildversion=139" in a folder that had a 126 build results in a completely broken and unusable server, and that needed a fresh clone and install to correct.

For 140.1 I presumed that a minor version wouldn't have the same problem. I don't know what git tag goes with v140.1 so I couldn't do the checkout part, but a gradlew with Pbuildversion=140.1 worked without any problems and made a server with a version command that claims to be 140.1

That was the version where I became aware of this issue.

Yeah I was saving on the client. Just now had a moment of "...you can save on the server? why? _check help list_ oh there it is. good to know i suppose."

**Comment by Anuken** [comment]
> ./gradlew server:dist -Pbuildversion=140

**Do not** do this when reporting bugs! Download the latest jar instead. You reported this build as "140.1", but in fact it was a custom build, which greatly confused things. Unless you are modifying the code, just use official versions.

> git checkout v140

I don't see why this would leave outdated artifacts...  I would use `./run-server 140.1` in the server folder instead and see if it helps.

**Comment by Larofeticus** [comment]
I'll try "just get the new server jar file" for the next upgrade cycle. I'm guessing the best download location is the last link on the itch.io downloads?

Ah I didn't know run server was there. I see its got a gradlew Pbuildversion in it. I've reinvented several wheels, apparently.

The custom build process did come in handy to fix for a v126 unit behavior bug that i backported a fix from what was the bleeding edge at the time.
