### ISSUE TITLE
Half-built blocks not being destroyed on core destruction.

### ISSUE THREAD

**Issue by haltalt** [Anuken/Mindustry#7828]
**Platform**: Windows

**Build**: 140.

**Issue**: If a core gets destroyed, it's supposed to eradicate all buildings of its team in the radius (campaign). However, half-built buildings don't follow that rule (the half-built conduit is a malice one):
![image](https://user-images.githubusercontent.com/91082490/200125286-b3605fe5-6208-407d-9d15-7e288a14a7ad.png)

**Steps to reproduce**: This was encountered in erekir campaign, but probably is the case on serpulo as well. Evokes sometimes try to rebuild what you destroyed. If you kill the core while they are doing so, the half-built thing (in this case, conduit) preserves.
**Link(s) to mod(s) used**: None

**Save file**: I have no idea how to download a campaign map with the thing preserving, and it's hard to try to reproduce in sandbox. I believe that as long as this hasn't been fixed in the dev builds or 140.1 (didn't find it being fixed), it's pretty straightforward.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I believe what actually happens here is the block is built *after* core destruction, which is different.

**Comment by haltalt** [comment]
> I believe what actually happens here is the block is built _after_ core destruction, which is different.

That is very much possible. Would make sense since the thing is a conduit and not a bigger building
