### ISSUE TITLE
A slight mistake in the Ukrainian translation 

### ISSUE THREAD

**Issue by BUSH48228** [Anuken/Mindustry#7830]
**Platform**: `Android 29`

**Build**: `beta build 140.1`

**Issue**: *In factory blocks (for example, Graphite Press or Silicon Smelter) there's no space in the description of how many items go in/out per second (in the `Input/Output` section of the description). For example, in the screenshot below it says `6за сек` and `4за сек`. That's the same as writing `6per second` in English. Please add a space so that it says `6 за сек`
![Screenshot](https://user-images.githubusercontent.com/116722214/200135036-ce5202c6-6ee3-455b-9f31-e913ba6c485d.jpg)
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Translation issues are not bugs, and I do not manage translation issues directly. Open a PR.

**Comment by Prosta4okua** [comment]
Вітаю, @BUSH48228. Я український перекладач. Для виправлення помилки треба відредагувати код і всі бандли, а це для мене поки важко.
