### ISSUE TITLE
Erekir: assembler module works even without being provided power

### ISSUE THREAD

**Issue by xalexalex** [Anuken/Mindustry#7835]
**Platform**: Linux

**Build**: beta v140.1

**Issue**:  The assembler module, when placed next to the construction area, raises the tier of the produced unit even if it is not connected to the power grid. If payloads are supplied, the unit is built.

**Steps to reproduce**: in sandbox, build an assembler + module setup, but don't wire the module to power.

**Link(s) to mod(s) used**: none

**Save file**: 
[20221106.zip](https://github.com/Anuken/Mindustry/files/9945994/20221106.zip)

Screenshot:
![maim_2022-11-06_15:03:39 156812087](https://user-images.githubusercontent.com/16612842/200175270-9a0b4b65-7876-4308-bf9f-788a5e5d71d9.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. It doesn't need power to actually do anything, only to shoot out payloads.

**Comment by Bottinator22** [comment]
(The module can be inputted payloads too)
