### ISSUE TITLE
Server command `admin add <uuid>` does not work for offline players

### ISSUE THREAD

**Issue by pschichtel** [Anuken/Mindustry#7836]
**Platform**: Linux, dockerized

**Build**: Mindustry 6-release official / build 126.2

**Issue**:

I'm trying to initialized a server from scratch inside a container and I'd like to make myself admin right from the start. The `admin add ...` command suggests, that admins can be added offline using the UUID, but the code doesn't look like it supports this. Not sure if this is a feature request or a bug.

**Steps to reproduce**:

1. start a fresh server
2. run `admin add <uuid>` with `<uuid>` set to your UUID

**Link(s) to mod(s) used**: no mods

**Save file**: it's not in-game.

**(Crash) logs**: no crashes

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by pschichtel** [comment]
If this is indeed not a bug, but a missing feature, then I'd like to request some form of "initial admins list", so that I can make certain users to admins automatically.

**Comment by Anuken** [comment]
This is not possible, because UUIDs can easily be spoofed (have an admin join a different server, grab their UUID, copy it, bam, you're admin on another server). Clients have USIDs that they send, specific to each server, which is why online status is required.

**Comment by pschichtel** [comment]
@Anuken would it be possible to have an option to make the first player that joins admin ?

**Comment by Anuken** [comment]
That's extremely specific and I don't think any other server would use it. You could probably make a plugin... or, heck, a very long line of JS executed with `js` to implement such a feature.

**Comment by pschichtel** [comment]
My original plan was to have the server running as a non-interactive container. But I guess I can keep stdin open and attach to it once initially.
