### ISSUE TITLE
Show enemy HP on mouse hover, good idea? 

### ISSUE THREAD

**Issue by 1RedOne** [Anuken/Mindustry#784]
Do not make a new issue for feature requests. Instead, post it in #545.

Looking for feedback if I should write this

Always wanted to hover over an enemy unit, especially the very strong final enemy types, and see their HP just like you can see for your own units.

Let me know what you think

**Comment by Prezombie** [comment]
The HP is shown by the red light, the faster it's flashing, the closer it is to death. For the bigger enemies, having multiple hp lights to act like an hp bar would be nice though.

**Comment by 1RedOne** [comment]
Hm I just noticed I'm on an older build, build 87, maybe the red light is a newer feature?  I'll check it out!

**Comment by Anuken** [comment]
Even if it's feedback on potential feedback, it should still go in the feedback issue.

Regarding health bars, I don't think they should be shown on hover, but the 'flashing light system' can be confusing sometimes, and the way it looks on bosses definitely needs some work.
