### ISSUE TITLE
Water spills instead of boiling in erekir enviorment.

### ISSUE THREAD

**Issue by Mechanicalfish** [Anuken/Mindustry#7841]
Windows 10

bleeding-edge build 23557 

Water spills instead of boiling in erekir enviorment

Let water leave conduits. This seems to only happen on custom maps made after 140.1

[waterbug.zip](https://github.com/Anuken/Mindustry/files/9954960/waterbug.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> This seems to only happen on custom maps made after 140.1

...No, I believe this happens in every map that doesn't use sector generation and isn't in the campaign. I tested, and maps before 140 have it too.

**Comment by Mechanicalfish** [comment]
is there any way to make water boil without using sector generate

**Comment by Anuken** [comment]
Wait for the new build, then re-set the Erekir environment again.
