### ISSUE TITLE
Distributed Erekir map replaced with a played version

### ISSUE THREAD

**Issue by laserman367** [Anuken/Mindustry#7851]
**Platform**:  Windows

**Build**:  140.2

**Issue**:  Map previously known as "Erekir Wave Map" is now labeled "Unknown" and has preexisting buildings/units and is at wave 109.

**Steps to reproduce**: Launch the game, open the map labeled Unknown in either Custom Game or Map Editor.

**Link(s) to mod(s) used**: None

**Save file**: [Can't imagine it helps but don't want my soul reaped](https://github.com/Anuken/Mindustry/files/9970646/saves.zip)

Here you can see how it used to be and what it is now.
![Example of the differences](https://i.imgur.com/0ymJnzr.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Guess I should test PRs properly.
