### ISSUE TITLE
Duplication of players

### ISSUE THREAD

**Issue by Dark-Diamond** [Anuken/Mindustry#7874]
**Platform**: Windows. Maybe others 

**Build**: 126.2 - 140.x

**Issue**:  Duplication of players

**Steps to reproduce**: people can multiply connections by simply logging in from multiple running apps at the same time. Its not a server problem bc its working on ohter community servers.
Server logs of connection event and default status result
![20221111_203913](https://user-images.githubusercontent.com/79577330/201388641-da15b195-c0df-49ff-8349-42e96ec251eb.png)
![20221111_203944](https://user-images.githubusercontent.com/79577330/201388644-a1507d02-697f-4b43-aac7-2ef9275c0690.png)

**Link(s) to mod(s) used**: Not applicable.

**Save file**: Not applicable.

**(Crash) logs**: Not applicable.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/201407957-7f063c04-47f4-4c20-b0fd-fce30c1a0a96.png)


Cannot reproduce issue. Do you have strict mode off?

**Comment by ienov** [comment]
ok
![image](https://user-images.githubusercontent.com/60543121/201411604-3e1f5e10-30b6-471d-9d7f-bd7c698b3d98.png)

**Comment by Dark-Diamond** [comment]
![image](https://user-images.githubusercontent.com/79577330/201412499-d744ea1d-9b95-434c-acd8-7cffe81b3595.png)

**Comment by Anuken** [comment]
It still doesn't happen to me, neither on my own hosted server nor on other people's community servers.

**Comment by ienov** [comment]
apparently with the help of some program or script, he simultaneously duplicates the actions, tk. all connections occur at the same time, and the server does not have time to check 🤷

**Comment by Dark-Diamond** [comment]
> It still doesn't happen to me, neither on my own hosted server nor on other people's community servers.

it is enough to take any autoclicker with a code editor to experience this. You can also use more advanced scripts to fully duplicate all actions between windows

https://user-images.githubusercontent.com/79577330/201420361-e61f2e24-c671-4a40-aef6-389049d7f479.mp4
