### ISSUE TITLE
Latest Version Mod Issue

### ISSUE THREAD

**Issue by FatalThrust** [Anuken/Mindustry#788]
**Platform**: (Android/iOS/Mac/Windows/Linux)
Windows
**Build**: (The build number under the title in the main menu. Required.)
Latest
**Issue**: (Explain your issue in detail.)
Game doesn't recognize mods and doesn't build with a "mods" folder
**Steps to reproduce**: (How you happened across the issue, and what you were doing at the time.)

I downloaded both steam and itch version and neither had a mods folder and I even made my own along with a .json metadata file  (for making mods and the repository format) and mods were still unrecognized etc

**Comment by Anuken** [comment]
1. Use the issue template, it's there for a reason.
2. Mods are not implemented in the itch.io *or* Steam versions yet; what made you think they were released?
