### ISSUE TITLE
Ship not spawning on Erekir sandbox

### ISSUE THREAD

**Issue by cd1213** [Anuken/Mindustry#7881]
**Platform**: *Windows*

**Build**: *Steam build 140.3*

**Issue**: *When trying to play any Sandbox map with Erekir tech, the player ship does not spawn, making it impossible to build anything*

**Steps to reproduce**: 
*1. Play > Custom game > select any map.
2. Select sandbox.
3. In "customize rules", select Erekir as the planet.
4. Click play.
Expected behavior: the player ship spawns after the core landing animation.
Actual behavior: the player ship does not spawn. It is possible to move the camera, but not to build structures or interact with the map.*

**Save file**: [Saved.zip](https://github.com/Anuken/Mindustry/files/9992965/Saved.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. Serpulo cores aren't supported in the Erekir environment. Any ships spawned would explode instantly. Don't play Serpulo maps with the Erekir environment, they're unplayable anyway.
