### ISSUE TITLE
RTS controlling an army causes that interacting too quickly message

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#7882]
**Platform**: Windows

**Build**: * 140.3

**Issue**: Issuing commands to units above a certain rate causes "You are interacting with blocks too quickly." warning message. 

**Steps to reproduce**: Join a multiplayer server. Command mode. Select a unit. Go clicking crazy all over the place; like it's a cookie. Or like you are playing an RTS game.

**Link(s) to mod(s) used**: N/A

**Save file**: 
[bug.zip](https://github.com/Anuken/Mindustry/files/9993235/bug.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't do that?

**Comment by Lazaro797** [comment]
> Don't do that?

But when you need to intensively micromanage units, you'll get spammed the message and we need to micromanage units a lot.

**Comment by Larofeticus** [comment]
How about changing the warning message to something that makes sense in the context?

**Comment by Tree-0** [comment]
Now that Mindustry has turned into an RTS, that sometimes means micromanaging units rapidly in order to be competitive. Rate-limiting other things I understand, but this doesn’t make much sense, it primarily just stops competitive players from challenging each other after a skirmish has gone on too long.
