### ISSUE TITLE
Erekir "The Onset" bug

### ISSUE THREAD

**Issue by Bamnaman** [Anuken/Mindustry#7884]
**Platform**: *Android* ("All" is NOT a platform!)

**Build**: *140.3*

**Issue**: *Two "Evoke" units on the campaign sector "The Onset" remained behind after the final core was destroyed.*

**Steps to reproduce**: *I came across it during a normal playthrough, after destroying the cores & setting up basic infrastructure*

**Link(s) to mod(s) used**: *No mods used*

**Save file**: *
[save data - Nov. 11, 2022 - 1_34 PM AKDT.zip](https://github.com/Anuken/Mindustry/files/9993477/save.data.-.Nov.11.2022.-.1_34.PM.AKDT.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *No crash report necessary*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Larofeticus** [comment]
Don't do that?

**Comment by Lazaro797** [comment]
Just don't do that? what's the issue

**Comment by Bamnaman** [comment]
wdym "dont do that", it's part of the tutorial

**Comment by Bamnaman** [comment]
> 
well normally the units owned by an enemy core disappear after the core dies, sooo.....

**Comment by Larofeticus** [comment]
I agree, it's not a good response to a bug report.
