### ISSUE TITLE
OBS causing Mindustry to crash.

### ISSUE THREAD

**Issue by jvaler1** [Anuken/Mindustry#7886]
**Platform**: Windows

**Build**: Steam Build 140.3

**Issue**: Setting OBS to record a game capture of Mindustry and then recording will cause Mindustry to crash. See attached videos.

**Steps to reproduce**:
Open Mindustry
Open OBS
Add a Game Capture to the recording sources and set it to Mindustry
Start recording

Game will either crash instantly or within a few seconds

**Link(s) to mod(s) used**: https://obsproject.com/

**Save file**: N/A, occurs everywhere

**(Crash) logs**: Followed the instructions written here and it says "No crash logs found." I don't know where the crash logs folder is either.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/51203862/201452465-fb76302f-6b5b-48ad-bf93-08d6a8a2ae56.mp4

https://user-images.githubusercontent.com/51203862/201452470-56723dfc-7fb6-44b0-a9f3-d91b67d26536.mp4

**Comment by Larofeticus** [comment]
Don't do that?

But other than that, I use obs to record, and I'm not seeing a bug. I don't use it for streaming, so if this is from streaming my statement is not relevant.
Running 140.3 delivered by steam in fullscreen mode, obs version 28.0.3 which is not the most recent version by a few patch versions. (and now i'm _less_ inclined to update it!)

Maybe include more of the obs recording configuration? There might be something useful in the video settings. I'm also using "capture specific window" pointed at Mindustry.exe

Looks like you're on windows 10, so take a windows explorer and put %APPDATA% into the address bar. Then check either roaming or local folders for a mindustry folder, and that will have the "crashes" folder in it.

**Comment by jvaler1** [comment]
> Don't do that?
> 
> But other than that, I use obs to record, and I'm not seeing a bug. I don't use it for streaming, so if this is from streaming my statement is not relevant. Running 140.3 delivered by steam in fullscreen mode, obs version 28.0.3 which is not the most recent version by a few patch versions. (and now i'm _less_ inclined to update it!)
> 
> **OH, edit, i see your obs is 27.01! You should try updating that and then come back if it's still broken.**
> 
> Maybe include more of the obs recording configuration? There might be something useful in the video settings. I'm also using "capture specific window" pointed at Mindustry.exe
> 
> Looks like you're on windows 10, so take a windows explorer and put %APPDATA% into the address bar. Then check either roaming or local folders for a mindustry folder, and that will have the "crashes" folder in it.

I can't believe I didn't think about my OBS version being outdated that immediately fixed the issue. Thanks so much and is there a way to close this bug report myself?

**Comment by Larofeticus** [comment]
Oh, cool! Happy to help. 

Below the box to add a new comment, left of the green "comment" button is another button to close issue.

**Comment by Anuken** [comment]
> Followed the instructions written here and it says "No crash logs found." I don't know where the crash logs folder is either.

Regardless of whether the issue is with the game or not, I cannot fix crashes unless they produce a log.
