### ISSUE TITLE
I unlocked tungsten for no reason when using a melter

### ISSUE THREAD

**Issue by Buddermario7** [Anuken/Mindustry#7887]
**Platform**: Windows (steam)

**Build**: steam 140.3

**Issue**: ok so I was playing with a friend who was new and I put some scrap in a melter to unlock slag for his tech tree but then suddenly I unlocked tungsten for no reason (I previously only played the first erikir level so I had no reason to unlock tungsten)

**Steps to reproduce**: idk might work if you make slag or could be more specific like only if you are in steam and join someone else in steam and you already have slag unlocked on your save and they don't and you don't have tungsten but have started erikir and you've also played the v7 beta a bit (I listed the most general and most specific possibilities so I think that covered everything)

**Link(s) to mod(s) used**: none

**Save file**: h

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[h.zip](https://github.com/Anuken/Mindustry/files/9993956/h.zip)

**Comment by Buddermario7** [comment]
upon closer inspection it seems that I also unlocked thorium, surge alloy, and slag on erikir which makes even less sense (though I only saw tungsten for new content unlocked so idk if I unlocked them for no reason before or just now either way it seems things are unlocking for no reason though)

**Comment by Bottinator22** [comment]
unlocking resources used by both planets makes more sense than randomly unlocking one planet's resources

**Comment by Buddermario7** [comment]
> unlocking resources used by both planets makes more sense than randomly unlocking one planet's resources

I only used slag though; it doesn't make sense that surge alloy and thorium would also be unlocked (and tugsten too since it's not even in serpulo)
also you shouldn't unlock resources for both planets because they're completely separate

**Comment by Bottinator22** [comment]
Did your friend have those resources unlocked?

**Comment by Anuken** [comment]
I can fix the "tungsten" part of that, but other resources have the same "unlock" state, and are shared between planets.
