### ISSUE TITLE
Mining resources close to the core in PvP doesn't work as intended

### ISSUE THREAD

**Issue by Veraghin** [Anuken/Mindustry#789]
**Platform**: Linux
**Build**: Steam build 96

**Issue**: 
In PvP, it seems that only the host can mine properly. 
**Steps to reproduce**: 
When someone who is not the host mines close to their core, the resource animation where resources are deposited straight into the core plays, however the resource amount in the core doesn't actually increase.
Mining further away, where resources aren't deposited into the core straight away, works, and the collected resources can be deposited into the core from the player drone as usual.

**Comment by Anuken** [comment]
Already fixed.
