### ISSUE TITLE
Getting kicked from a server for spamming in chat when antispam is false and packetlimit is not exceeded (and pardon does not unban you)

### ISSUE THREAD

**Issue by TheRadioactiveBanana** [Anuken/Mindustry#7894]
**Platform**: Windows 10 64 Bit (my client) Linux (ubuntu 22.10 on server)

just for some extra information, my client is a computer with an amd ryzen 5 3600 and a gtx 1650 (overclocked), with 16 gigabytes of ddr4 3200mhz ram. the server is an oracle cloud infrastructure compute instance (vps) with 24 gigabytes of ram (i do not know the speed) 8 threads of an Ampere Altra CPU and no graphics processor.

**Build**: 140.3

**Issue**: If you spam in chat on a server very fast (this was achieved in my case using mods) it will kick you for the normal kick reason "You have been kicked from the server!" and in console it says "kicking connection [ip]/[uuid]; Reason: kick
I am also unable to un-kick the person using pardon, or unban. only a full server restart can un-kick the person and allow them to join again. my main problem with this is that this is happening even when the server is set not to kick for spam. config antiSpam is clearly false and packet limit is set so high to test this and it still kicks me (packet limit in question i have set to 1000000000.

**Steps to reproduce**: Spam in the chat quite fast. this is almost impossible to reproduce when normally chatting, but when using a mod/macro to run a command or say something in chat it will kick you within seconds. (if you keep clicking the macro and spam several messages in chat in one go). 

**Link(s) to mod(s) used**: There are no mods or plugins used in this case. i have tested it with my normal server plugin and without any mods or plugins and the issue persists.

**Save file**: [savefile.zip](https://github.com/Anuken/Mindustry/files/9995111/savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Not applicable since neither my client, nor the server crashed during the entire time.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Additional info:  

i was using the mod scheme-size to spam /js commands in the chat to reproduce this, and i am able to reliably reproduce it.
it also works with regular messages if i set up a macro to spam anything in chat at 20cps or so.

the command(s) in question went along like this: 

[11-12-2022 13:54:49] [I] <Eradicator: /js player.unit(unit); unit.spawnedByCore = spawned>
[11-12-2022 13:54:49] [I] <Eradicator: /js var player = Groups.player.getByID(1407)>
[11-12-2022 13:54:49] [I] <Eradicator: /js var spawned = player.unit().spawnedByCore; var unit = player.unit(); unit.spawnedByCore = false; player.clearUnit()>
[11-12-2022 13:54:49] [I] <Eradicator: /js unit.set(1118.1617,178.67719); Call.setPosition(player.con, 1118.1617,178.67719); Call.setCameraPosition(player.con, 1118.1617,178.67719)>

(Eradicator is my mindustry username)

The server in question is in the public server list as Eradicationdustry testing (i use this to test plugins and other stuff, people can come here to leave feedback about new plugins when im testing them)

**Comment by TheRadioactiveBanana** [comment]
if you need any further information like a video of the thing in action, please ask me. i will provide any info you need.

**Comment by Anuken** [comment]
This is not a bug, as there is a "foul play detection" separate chat rate limit that does the same as the packet rate limit, except it's not configurable. (why do you even need this?)
