### ISSUE TITLE
Novas not correctly pathfinding with RTS controlls

### ISSUE THREAD

**Issue by falkanson** [Anuken/Mindustry#7895]
**Platform**: Linux

**Build**: steam build 140.3

**Issue**: Nova units do not use flying ability to reach spots on the other side of walls/terrain

**Steps to reproduce**: Command novas to move to a spot that can only be reached by flying"

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug. This was never implemented for novas.

**Comment by Imanoob14** [comment]
So you are going to implement it?
