### ISSUE TITLE
Auto-aim bullets problem on erekir 

### ISSUE THREAD

**Issue by Olweant** [Anuken/Mindustry#7896]
**Platform**: *Windows x64 10*

**Build**: *140.3*

**Issue**: *Auto-aim of some troops can never touch a 1x1 block (beam node) on Erekir*

**Steps to reproduce**: *Unit of a wave getting close to a 1x1 block*

**Link(s) to mod(s) used**: *Vanilla*

**Save file**: *attached*

---
[Main Mindusrty v7 Vanilla.zip](https://github.com/Anuken/Mindustry/files/9995256/Main.Mindusrty.v7.Vanilla.zip)

https://user-images.githubusercontent.com/71179992/201481292-e9e1169a-8a83-4fe4-90ab-c52e909c839d.mp4

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Move the unit away. The elude literally cannot hit blocks that close to itself - this has nothing to do with auto-aim, it can't "home in" fast enough either way.
