### ISSUE TITLE
Monos constantly mining the same ore, even though I have a max core amount

### ISSUE THREAD

**Issue by DraLUSAD** [Anuken/Mindustry#7898]
**Platform**: Windows 10 64x

**Build**: Version 7-140.3

**Issue**: Automatic mono ore mining has a tendency to not acquire the least amount of ore, shown in the image below.

**Steps to reproduce**: Appears to be a code issue and/or multiplayer, there is no way to reproduce this.

**Link(s) to mod(s) used**: 100% Vanilla

**Save file**: Would have no effect

![mono](https://user-images.githubusercontent.com/57923958/201486436-a1511bdd-260a-4c6a-8313-9cad3287cd1a.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DraLUSAD** [comment]
Oooops my Fault, I was force mining with Processors, here's my Fix

![mono](https://user-images.githubusercontent.com/57923958/201486766-87baea2f-2c71-4171-b20e-3c4365d390b6.png)

Save: https://1drv.ms/u/s!AtTdLp-2fl4fko0Rr-iGXNzmqlRXZA?e=GzpsZg

**Comment by Anuken** [comment]
>  was force mining with Processors, here's my Fix

...so, does that means it's not a game bug?

**Comment by DraLUSAD** [comment]
the force mining was something I forgot to remove, so the 2nd image this time pro

> > was force mining with Processors, here's my Fix
> 
> ...so, does that means it's not a game bug?

the force mining with processors? no, that was my mistake, but the 2nd image I removed all processors, looking at the ore storage above, the monoes kept mining copper, even though lead was less, from what I've seen monos mine a node which is the least in storage, but here, they kept mining copper, constantly, so in away, yes, this IS a bug.
