### ISSUE TITLE
Liquid System Re-write

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#79]
- Maximum pressure limit for blocks, possibly with explosions if that pressure gets too high
- More realistic uniform "flow"
- Support for more liquid flowing through a single pipe
- Better visuals in general

**Comment by Luxray5474** [comment]
Make the pipe shake or have a '!' on it when it approaches pressure overload, too. ~~Generally any block that explodes should have an ! on it when it's about to explode~~

**Comment by Anuken** [comment]
Moved to #87
