### ISSUE TITLE
(In Code) w/ Github <Critical for Modding for new users>

### ISSUE THREAD

**Issue by FatalThrust** [Anuken/Mindustry#790]
**Platform**: (Android/iOS/Mac/Windows/Linux)
n/a

**Build**: (The build number under the title in the main menu. Required.)
<github src>

**Issue**: (Explain your issue in detail.)
import io.anuke.mindustry.gen.*; -> gen doesn't exist and causes compilation errors
resulting in Sounds to become a unresolved symbol
and causes other issues with other code

**Comment by Anuken** [comment]
`io.anuke.mindustry.gen.*` is generated code. Either use a decent IDE like IntelliJ to make it show up automatically, or use the gradle command line to run it. None of the imports cause real compilation issues if you're running through gradle.

**Comment by FatalThrust** [comment]
Ah understood, I will no longer disturb you, if anyone has the same experience as me I will show them this 👍
