### ISSUE TITLE
Setting the rally for a large number of factories will cause a rate limit

### ISSUE THREAD

**Issue by Garen7** [Anuken/Mindustry#7906]
**Platform**: Windows

**Build**: 140.3

**Issue**: Selecting a large number of unit factories and setting a rally can cause you to instantly get rate limited. It seems like each individual factory you are controlling contributes to the rate limit.

**Steps to reproduce**: Go on a server that you are not hosting, then place a large number of unit factories and try to rally them somewhere. The default setting for antispam is that non headless servers have it disabled so its easiest to just connect to a random public sandbox server and try it there.

**Save file**: [Factory Rate Limit Bug.zip](https://github.com/Anuken/Mindustry/files/9996589/Factory.Rate.Limit.Bug.zip)

Here is a simple schematic to reproduce it with also: 
> bXNjaAF4nE3T4U4aQRSG4WEXlONopcOIoseBXoBX1PQH0G1DqmBgTW+rt9dfdLHyngMh+XbfXbLJA2EevtShv1m8NGG4fPs5b5t9G+L3Zr/arV/b9XYTQjh7Xiyb532ovn6rQ1y3zcvTfvu2WzXh8nX7u9mdjq7bxebX04/FcrdeLdrtrrv1Tzi+BiFI7zh63Rr1jrMa9kIVqvp4tqb36QPXz+jn9KHrQr+gR9cv6Vf0T65f00f0z64n+pieXb+hT+i3rt/Rp/R71x/oSn90vdBn9PlH7z7h/UQ4Hoa+zXObFzavbI5sjm1ObE5tqs3Z/9k9ErACrHSw1eHv4fDx8AKugCsOV8AVcMXhCrgCrjhcAVfAFYcr4Aq44nAFXAFXHK6AK+CKwxVwBVxxuAKugCsOV8AVcMXhRsONhhsNNxpuNNxouNFwo+FGw42GGw03gZvATe5fm4BNwCYHm4BNwCYHm4BNwCYHm4BNwCYHm4BNwKYOtj79+Lr34P26xHVjrsvue27oE/qt63f0Kf3e9Qe60h9dL/QZ3YCzAWcDzgacDTgbcDbgbMDZgLMBZwPOBqwAK8DqgBVgBVgdsAKsAKsDVoAVYHXACrACrA5YAVaAtQOuHK6Cq+Cqw1VwFVx1uAqugqsOV8FVcNXhKrgKrjrcYrjFcIvhFsMthlsMtxhuMdxiuMVwywn3H/BrQ7E=

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Larofeticus** [comment]
Don't do that?

**Comment by Anuken** [comment]
@Larofeticus

I'm only going to say this once.

I'm not going to tolerate you polluting random unrelated issues with your passive-aggressive comments. If I see even a single one of these *outside of the issue where it belongs*, you are simply getting blocked.

Your choice.
