### ISSUE TITLE
Minimize on start, unable to restore. Possible eGPU problem.

### ISSUE THREAD

**Issue by radistmorse** [Anuken/Mindustry#7910]
**Platform**: Windows 11

**Build**: 140.4 steam

**Issue**: Fails to start. The loading splash is shown in window, then the game starts in fullscreen, audio starts playing, and after a couple of seconds of black screen the game minimizes. If you try to restore the window - the result will always be the same, couple of seconds of black screen, then minimize.

**Steps to reproduce**: The problem may be related to my eGPU setup. Other than that no special steps required. Launch the game, enjoy.

**(Crash) logs**: 
```
[I] [GL] Version: OpenGL 4.6.0 / ATI Technologies Inc. / Radeon RX Vega
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 3.9 GB
[I] [Mindustry] Version: 140.4
[I] Total time to load: 2553ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Received steam stats.
[I] Fetched 26 community servers.
```

Once in a while the game does start. Who knows why. The same problem may occur on alt-tab, or when changing the graphics mode to "fullscreen". With "borderless fullscreen" the problem never happens, but the problem is you can't switch it to "borderless fullscreen" without launching the game first. There is no command line argument for that, and the config file is binary.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce the issue, likely related to whatever your setup is. Log has no relevant info.
