### ISSUE TITLE
Bro the 7.0 isnt letting me research anything it doesnt say any material it just says ???

### ISSUE THREAD

**Issue by Spavys** [Anuken/Mindustry#7912]
**Platform**: `Android 29`

**Build**: `release build 140.4`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[null/speed-control:0.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
don’t you have to "manually" discover materials?

**Comment by xtreemtm** [comment]
You think somebody will help you? You did not even fill the issue.

**Comment by SpaceEarthEX** [comment]
You must fill the issue

**Comment by Leo-MathGuy** [comment]
That means required research is not complete

**Comment by Leo-MathGuy** [comment]
Also read the issue template. Anuken has a new soul to reap
