### ISSUE TITLE
Beam Node & Beam Tower blocks don't show up in menu while using "edit in game" function; Beam Link block doesn't show up in menu while playing a save (outside the map editor)

### ISSUE THREAD

**Issue by Redoneter593** [Anuken/Mindustry#7914]
**Platform**: windows 11

**Build**: steam 140.4

**Issue**: When using using the map editor via the "edit in game" function/mode, the Beam Node & Beam Tower blocks don't show up in the build menu. Additionally, the Beam Link block doesn't show up in build menu menu while playing a save (outside the map editor).

**Steps to reproduce**: I was trying to get a screenshot of some blocks using the the but the Beam Node & Beam Tower blocks didn't show up in build menu at all during such. I tried checking if it also occurs while playing on the map after saving it, and instead the Beam Link block doesn't appear in the build menu, while the Beam Node & Beam Tower blocks *do* appear in the build menu. I tried all three selectable options for planets when starting the save (not map editor) and it makes no difference. 

Despite this, if the "edit in game" function is not active while still in the map editor, the three mentioned blocks will still appear for selection in the block menu. I understand this might be confusing to correctly comprehend due to circumstances, so I hope I have clarified enough.

**Save file**: [Bug.zip](https://github.com/Anuken/Mindustry/files/9999316/Bug.zip) Includes saves for both the map via the editor and during a play, with (cropped) screenshots for the differences between the two in their respective folders. 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. You have serpulo tech in the editor. Switch to Erekir.
2. Beam links are **not buildable**, they are enemy-only campaign blocks.
