### ISSUE TITLE
Cannot swap to other Windows in Mac

### ISSUE THREAD

**Issue by Potato-Da-Potata** [Anuken/Mindustry#7916]
**Platform**: *Mac*

**Build**: *Steam 140.4

**Issue**: *You cannot swap to other windows when Mindustry opens*

**Steps to reproduce**: *Open the game*

**Comment by Anuken** [comment]
Cannot reproduce the issue on a Mac VM.

**Comment by Potato-Da-Potata** [comment]
Dear Anuken,

I can try recording the issue and send it to you, but the problem could
also be on my end.

Best Regards,
Potato Potata

**Comment by Anuken** [comment]
I don't think that would help very much. I don't actually use Mac devices and I have not implemented anything that should prevent changing windows. It could be a device-specific issue.
