### ISSUE TITLE
Keybind settings does not support key combination (in spanish keyboard [ is Alt Gr + ` )

### ISSUE THREAD

**Issue by mdtrooper** [Anuken/Mindustry#7919]
**Platform**: Linux

**Build**: *140.3

**Issue**:  Some keyboards (spanish for example) has not a key for <kbd>[</kbd>, it is <kbd>Alt Gr</kbd> + <kbd>`</kbd>.
![image](https://user-images.githubusercontent.com/1285451/201652973-bcb75467-5a63-4985-8686-e0e7a8357fe6.png)

And the mindustry keybind settings screen catchs only first press key, and when I tryed to set the key <kbd>[</kbd> (yes I can press reset button) the screen catchs <kbd>R-Alt</kbd>

![image](https://user-images.githubusercontent.com/1285451/201653553-b5c01b5d-d71e-47f0-b37b-62563925f09b.png)

**Steps to reproduce**: Use any [mod key](https://en.wikipedia.org/wiki/Modifier_key) to keybind

**Link(s) to mod(s) used**: 

**Save file**:

**(Crash) logs**: 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Issue: Some keyboards (spanish for example) has not a key for [

Mindustry does not support such keyboards.
