### ISSUE TITLE
140.4 exception crash

### ISSUE THREAD

**Issue by dhrvalkyr** [Anuken/Mindustry#7923]
**Platform**: Windows

**Build**: steam build 140.4

**Issue**: Game crashes on block placement/destruction

**Steps to reproduce**: unknown

**Link(s) to mod(s) used**: N/A

**Save file**: https://drive.google.com/file/d/1jmSVNVzQ677f72DpOH0e5T4wQUY9w0uR/view?usp=sharing

**(Crash) logs**: https://drive.google.com/file/d/1jZLA8gKvKSjYlAs8-f5E00YLEnfW-j_Y/view?usp=sharing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
You must update NVIDIA Graphics Driver

**Comment by dhrvalkyr** [comment]
Having updated the NVIDIA graphics driver, I am still experiencing periodic crashes

**Comment by Anuken** [comment]
Driver bug, cannot fix.
