### ISSUE TITLE
Erekir unloader loads a loader.

### ISSUE THREAD

**Issue by Edwardl256** [Anuken/Mindustry#7930]
**Platform**: Linux

**Build**: bleeding-edge build 23631

**Issue**:
In Erekir I place a payload circuit so that liquid containers go between islands and exchange liquids. To island B I send Water, and on its return trip I send Slag. Being a tight fit I put the Unloader next to the Loader. However, it seems the Unloader puts some of the content into the Loader which means a container is halted with a bit of Water in it hoping for more but the input is Slag, and visa-versa with a bit of Slag but the input is Water. Is this a bug, or do I have to separate the Unload and the Loader by at least one conveyor?

**Steps to reproduce**:
- With Erekir tech only, place a Constructor and have it create Reinforced Liquid Container.
- Place a couple of Reinforced Payload Conveyors after the Constructor.
- Place a Payload Unloader after the Conveyors.
- Connect some Reinforced Conduits to this Unloader, possibly to a tank.
- Place a Payload Loader right after the Unloader.
- Fill this Loader with Water.
- Place some Reinforced Payload Conveyors to make it form a large U-turn.
- Place a Payload Unloader after the Conveyors.
- Connect some Reinforced Conduits to this Unloader, possibly to a tank.
- Place a Payload Loader right after the Unloader.
- Fill this Loader with Slag.
- Place some Reinforced Payload Conveyors to make come back and connect to the Conveyors just after the Constructor.

**Link(s) to mod(s) used**: N/A

**Save file**: https://www.edwardleuf.org/x/213.zip

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> do I have to separate the Unload and the Loader by at least one conveyor?

Yes.
