### ISSUE TITLE
Reconstruction can be deducted in the fog of war due to duct items showing as moving

### ISSUE THREAD

**Issue by rissson** [Anuken/Mindustry#7931]
**Platform**: Linux

**Build**: Steam build 140.4

**Issue**:

Ducts still show items moving inside them in the fog of war. That means that if they were broken, and the reconstructed, said reconstruction can be induced by the fact that the items are still moving.

![image](https://user-images.githubusercontent.com/18313093/202306240-4ce0125e-b895-40e8-874e-740b8dfb6ae9.png)

**Steps to reproduce**:

Happened on a map on Erekir, can't remember and the power went out for the person who was hosting the server before I could get the map name (we are playing on the same steam build btw).

**Link(s) to mod(s) used**: None

**Save file**: I would, but server is dead for now. I will upload it asap.

**(Crash) logs**: No crash

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rissson** [comment]
This also happens with reconstruction animations (the little yellow growing square around a building). They are so fast I wasn't able to get a screenshot.

**Comment by ASMaksimov2007** [comment]
Can confirm that enemy units building in FoW are also shown (the lines and the contours of the buildings/conveyors).

**Comment by Anuken** [comment]
Not a bug.
