### ISSUE TITLE
No enemy cores but not gameover

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#7936]
**Platform**: Windows 11

**Build**: Build 140.4

**Issue**: No enemy cores in attack mode but server says still alive 1 core.

**Steps to reproduce**: i don't know how to this.

**Link(s) to mod(s) used**: None.

**Save file**: [1.zip](https://github.com/Anuken/Mindustry/files/10030996/1.zip)

**(Crash) logs**: None.

**Screenshots**
![image](https://user-images.githubusercontent.com/44261958/202435005-37dd3415-bc5b-43d2-bf29-f3eda2a5acf6.png)
Enemy team (malis)

![image](https://user-images.githubusercontent.com/44261958/202435380-4e37c008-e9b9-43fa-844d-e232dd9d5422.png)
Player team (sharded)

**This is a problem with this map only.**

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
see response
