### ISSUE TITLE
Cant trigger an achievement "browser" 

### ISSUE THREAD

**Issue by pixelv999** [Anuken/Mindustry#7939]
Platform: Windows/Mac

Build: 140.4 (steam)

Issue* can’t trigger an achievement browser, tried to do it on windows and mac (steam achievement system)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. - sure that its not related to the game but still uploaded it

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.
- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.**
File - https://drive.google.com/file/d/1KIfsg8RvO34_Wr2Pej4BDEjxpFvqrK0X/view?usp=sharing

**Comment by end-me-please** [comment]
consider following the template

**Comment by Leo-MathGuy** [comment]
Lol didnt even check the boxes.

Looks like anuken has a new soul to reap
