### ISSUE TITLE
Target editor does not save targets

### ISSUE THREAD

**Issue by RedMatrix1** [Anuken/Mindustry#7940]
OS And Version:Android 12

Build: Release 140.4

Issue: Editor "targets" will not be saved if you exit it

What I've done?:Added a target to the map. Exited the target editor. I go again and it’s empty there, I needed to delete the target, but it wasn’t in the editor. And it's in the game!

MODS:i dont have mod

Log And Save: https://drive.google.com/file/d/1TGIolCO0ZW7jpQxiLBvdXK60Oo2ktHzY-/view?usp=drivesdk

**Comment by Anuken** [comment]
I don't know what you are referring to.
