### ISSUE TITLE
Sector error (bug)

### ISSUE THREAD

**Issue by Machine047** [Anuken/Mindustry#7941]
**Platform**: `Windows 10 x64`

**Build**: `release build 140.4`

**Issue**: A sector in Serpulo is locked and i cant do nothing about it for now

**Steps to reproduce**:  In the planet Serpulo there was a sector in specific that was an enemy base, it was not part of the sector campaing and i around it as much a posible but still the sector was locked and attacking my sectors

**Link(s) to mod(s) used**: `none`

**Save file**: [campaign .zip](https://github.com/Anuken/Mindustry/files/10037067/campaign.zip)

**Crash report**: none
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
that's probably a non-optional sector you haven't unlocked yet

also, 140.3 is not latest, 140.4 is latest

**Comment by Machine047** [comment]
> that's probably a non-optional sector you haven't unlocked yet
> 
> also, 140.3 is not latest, 140.4 is latest

1. it's not a campaing sector i said it before in my quote
2. I forget to edit that, i was in 140.4
