### ISSUE TITLE
Ravine sector in Erekir cannot launch

### ISSUE THREAD

**Issue by rayinfinite** [Anuken/Mindustry#7945]
**Platform**: `Windows 10 x64`

**Build**: `steam build 140.4`

**Issue**: *After capturing Lake sector in Erekir, Ravine would launch from Lake instead of Atlas. However, Tungsten is not available in Lake so there is no way to launch Ravine unless abandoning Ravine*

**Steps to reproduce**: *Launching Ravine when Lake sector is captured*
![ravine](https://i.imgur.com/8sEFy9u.png)
![insufficient resources](https://i.imgur.com/rRqj6iH.png)

**Save file**: *[saves.zip](https://github.com/Anuken/Mindustry/files/10041482/saves.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
Just launch from a different sector with tungsten by simply entering it.
