### ISSUE TITLE
Hint from Serpulo showing on Erekir

### ISSUE THREAD

**Issue by kacperwyczawski** [Anuken/Mindustry#7946]
**Platform**: Windows

**Build**: 140.3

**Issue**: Hint about using ammo other than Copper and Lead (which do not exist on Erekir) is showing when fighting first guardian

here is screenshot:

![screenshot](https://user-images.githubusercontent.com/97523625/202727210-0cb9ea91-ae23-4b1c-9050-cb970588cbbc.png)

**Steps to reproduce**:
1. Wait for last wave in crevice sector
2. Hint should show

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/10042071/saves.zip)

---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 00001H** [comment]
I experienced this too. :(

**Comment by amaank404** [comment]
Experiencing same, came here to write a bug report but found yours instead

**Comment by amaank404** [comment]
![image](https://user-images.githubusercontent.com/71920621/210488036-97df5db7-0405-4d07-a9a4-1d7aa0df546b.png)
A code search resulted in this files and many others with similar names in that folder.
