### ISSUE TITLE
missing "d" "Buildings Deconstructe" in the Sector Lost screen

### ISSUE THREAD

**Issue by Shadow3276** [Anuken/Mindustry#7948]
**Platform**: Windows (Steam)

**Build**: 140.4

**Issue**: A typo in the Sector Lost screen, ie. the stats that pop up when your core gets destroyed.

**Steps to reproduce**: (see image below) Previously secured attack sector on Serpulo (sector 124) that I fully cleared of all crux/derelict buildings, lost because of an attack due to neighboring attack sector. Seems to be due to the large number as testing on a different (defense) sector where the number of buildings destroyed is 0 the text appears fully.
![Mindustry 18 11 2022 17_18_03](https://user-images.githubusercontent.com/118554426/202758642-8b9b90b7-0ced-4219-9884-b9a26765eb80.png)

**Link(s) to mod(s) used**: vanilla, no mods used

**Save file**:  [sector-serpulo-124.zip](https://github.com/Anuken/Mindustry/files/10043127/sector-serpulo-124.zip) (bugged)
[sector-serpulo-63.zip](https://github.com/Anuken/Mindustry/files/10043372/sector-serpulo-63.zip) (no bug)

**(Crash) logs**: No crash logs found

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
whered my d go

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/211166771-88c2c687-7cd2-484f-b5ff-a1306d6bd21e.png)

Can't reproduce with my (bigger) screen, honestly too minor to bother fixing, it's probably something complicated related to word wrap.
