### ISSUE TITLE
Erekir tech tree bug

### ISSUE THREAD

**Issue by gamemaster235** [Anuken/Mindustry#7951]
**Platform**: Android

**Build**: 140.4

**Issue**: thorium, surge alloy, phase and slag is in erekir tech tree and items that require said items to research (e.g surge conveyor, surge wall, reinforced vault)  even if you hadn't unlocked/researched said items in erekir itself

**Steps to reproduce**: the bug will happen if you researched/produced surge alloy, phase, thorium and slag in serpulo. i dont know if this can happen vise versa because i started on serpulo

**Link(s) to mod(s) used**: N/A

**Save file**: *
[bug.zip](https://github.com/Anuken/Mindustry/files/10046208/bug.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 00001H** [comment]
Same here. but I played erekir first and it affected serpulo.

**Comment by Anuken** [comment]
not a bug
