### ISSUE TITLE
opening map bug and sector genrate crash

### ISSUE THREAD

**Issue by rylid-umil** [Anuken/Mindustry#7955]
**Platform**: windows 11
**Build**: 140.4

**Issue**: the thing happenned when i open any map, it says map file is corrupted. another issue is when generating a new sector for a map in the editor , it crashed.

**Steps to reproduce**: first issue: try to open a map. Second Issue, go into editor, create a new map (everything is black) and click sector generate, and click ok, it crashed

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**:https://www.mediafire.com/file/gqav075f2j9tzjt/crash-report-11_19_2022_09_05_22.txt/file)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a mod bug.
