### ISSUE TITLE
Ability to placed banned blocks on map

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry#7958]
**Platform**: Windows

**Build**: 140.3 (client & headless)

**Issue**: Able to place banned blocks from map rules in addition to banned blocks from server side rule

**Steps to reproduce**:
* Download map from [here](https://cdn.discordapp.com/attachments/661636805128486922/1043677587085459507/GrasslandsCoreV7Fix.msav).
* Host map either as client custom game or through headless server
* attempt to place any banned block
* bug reveals itself

**Link(s) to mod(s) used**: N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: Bug does not cause a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by L0615T1C5-216AC-9437** [comment]
[msavNvideo.zip](https://github.com/Anuken/Mindustry/files/10050139/msavNvideo.zip)

**Comment by Anuken** [comment]
> attempt to place any banned block

![2023-01-07-14-04-00](https://user-images.githubusercontent.com/10100000/211166594-9fb2b5b4-a947-4c15-9922-0fd67adb1459.gif)

I cannot.
