### ISSUE TITLE
Switching to Windows and back to the game brakes the game

### ISSUE THREAD

**Issue by mathiasbader** [Anuken/Mindustry#7963]
**Platform**: Windows

**Build**: steam build 140.4

**Issue**: After the last update I experience this very annoying error, that was not there before: When I switch to windows and switch back, the game is broken in a way, that the mouse is moved vertically up. I see the mouse at a position, but when I click, the click is applied like 10 centimeters above. The game is not playable anymore like this.

**Steps to reproduce**: Start the game under windows 11. Switch to Windows with Alt + Tab. Go back to the game, it's now broken

**Link(s) to mod(s) used**: No mod used

**Save file**: -

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I don't have Windows 11 and this doesn't seem like something I can fix.

**Comment by mathiasbader** [comment]
That's unfortunate, but understandable. Thank you
