### ISSUE TITLE
Crash first gameplay

### ISSUE THREAD

**Issue by GFX993** [Anuken/Mindustry#7964]
**Platform**: `Android 25`

**Build**: `release build 140.4`

**Issue**: *Game is crashing after i click start the game in first time gameplay.*

**Steps to reproduce**: *game crash after clicking start button.*

**Link(s) to mod(s) used**: `none`

**Save file**: *
[CrashMindustry.zip](https://github.com/Anuken/Mindustry/files/10049253/CrashMindustry.zip)
.*

**Crash report**: *None crash report from game.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Crash reports are required.
