### ISSUE TITLE
Zooming keybinds do not work everywhere

### ISSUE THREAD

**Issue by Rusomati** [Anuken/Mindustry#7965]
**Platform**: at least linux //all exept andriod and ios

**Build**: 140.2 //this bug existed forever

**Issue**: zooming using  a keybind in tech trees and other places does not work

**Steps to reproduce**: 1-make a keybind for zooming 2.1- open the tech tree, 2.2- the objective-creating menu in the editor or 2.3 the planet menu

**Link(s) to mod(s) used**: none

**Save file**: nah.. (plz don't reap my soul)

**(Crashes)**: none.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
-        ^
-   jk  |
//#||~~can you unban me lol~~||

**Comment by 00001H** [comment]
why *should* it work in menus anyway?

**Comment by Rusomati** [comment]
to increase convenience

**Comment by Anuken** [comment]
Not a bug.
