### ISSUE TITLE
Показан блок меди вместо бериллия в обучающей подсказке

### ISSUE THREAD

**Issue by DushaDuh** [Anuken/Mindustry#7970]
**Platform**: `Android 29`

**Build**: `release build 140.4`

**Issue**: *Показан блок меди вместо бериллия в обучающей подсказке*
![Screenshot_20221121_170418_io anuke mindustry](https://user-images.githubusercontent.com/118737384/203055468-7420ad10-6488-45d3-a4c1-ee602a563957.jpg)

**Steps to reproduce**: *Просто играл следуя подсаазкам*

**Link(s) to mod(s) used**: `[Zelaux/byte-logic-mod:v1.0.1, z0mbiesrock/larger-cores:1.0, genNAowl/upgraded-factories:null]`

**Save file**: *   
[sector-erekir-10.zip](https://github.com/Anuken/Mindustry/files/10056513/sector-erekir-10.zip)
   *

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [Х ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ Х] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
@DushaDuh я один из переводчиков на русский язык. Это, вероятнее всего, ошибка в переводе, которую я скорее всего и допустил. Постараюсь исправить как можно быстрее.
