### ISSUE TITLE
Extraction Outpost won't capture?

### ISSUE THREAD

**Issue by Voldzz** [Anuken/Mindustry#7975]
Windows 10

Version 7 Build 140.4
I destroyed the core and first boss of Extraction Outpost, but the sector hasn't been captured, nor have I unlocked the launch pad.

1. Launch to Extraction Outpost from Sector 85
2. Destroy the Core and beat wave 39

No Mods were used

I believe this is the save file, but I'm not sure:
[11.zip]
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
X
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
X

**Comment by Anuken** [comment]
No save.
