### ISSUE TITLE
Error multiplayer game

### ISSUE THREAD

**Issue by Keifwer** [Anuken/Mindustry#7979]
**Platform**: `Windows 7 x32`

**Build**: `release build 140.4`

**Issue**: * When trying to play an online game, the error "OutOfMemoryError: unable to create new native thread".*

**Steps to reproduce**: *Сlicking the "network game" button*

**Link(s) to mod(s) used**: `[Vanilla game without mods]`

**Save file**: *I doubt that a game file is required here.*

**Crash report**: *[crash_report.zip](https://github.com/Anuken/Mindustry/files/10067072/crash_report.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
Using something like java 17 should help fix this issue as threads allocate less memory there.

**Comment by Keifwer** [comment]
> Using something like java 17 should help fix this issue as threads allocate less memory there.

I solved the problem

**Comment by buthed010203** [comment]
Then close the issue...
