### ISSUE TITLE
No Unit Cap Bug

### ISSUE THREAD

**Issue by JasonP-01** [Anuken/Mindustry#7986]
**Platform**: Windows 10

**Build**: 140.4(custom client and headless server)

**Issue**: Map Unit Cap is bugged to have integer limit as the cap. In map rules it is stated as 30 but ingame it is integer limit, multiple attempts have been made to correct this including `Vars.state.rules.unitCap = 30` that had no effect

**Steps to reproduce**: Download the map [here](https://cdn.discordapp.com/attachments/661636805128486922/1043677587085459507/GrasslandsCoreV7Fix.msav) 
Host the map - place unit factory and observe

**Link(s) to mod(s) used**:none

**Save file**: https://cdn.discordapp.com/attachments/661636805128486922/1043677587085459507/GrasslandsCoreV7Fix.msav

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ruichka** [comment]
Enemy team gets infinite units no matter what, and you set both player and enemy team to sharded.
