### ISSUE TITLE
Game crashes on steam instantly on start up

### ISSUE THREAD

**Issue by rafcioxx** [Anuken/Mindustry#7995]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
pc 
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Build: steam build 140.4
**Issue**: *Explain your issue in detail.*
I press the play button on steam to launch mindustry black app window that has an smaller error window pop up that the game has crashed.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Just pressed play on steam account to lunch mindustry
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---[crash-report-11_25_2022_18_05_50.txt](https://github.com/Anuken/Mindustry/files/10094458/crash-report-11_25_2022_18_05_50.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by rafcioxx** [comment]
Ok i found the fix by messing around. 1.Download letiest version of mindustry from git hub. 2. go to the steam right click mindustry manage browse local files. 3. delete EVERYTHING. 4. make steam check files bu seting check file integrety. its not going to find any files then it will down load every thing and it shoud be done.

**Comment by Anuken** [comment]
Cannot reproduce.
