### ISSUE TITLE
Launch Pad menu icon and build texture don't match the new Launch Pad texture

### ISSUE THREAD

**Issue by Shadow3276** [Anuken/Mindustry#7996]
**Platform**: Windows - Steam

**Build**: 140.4

**Issue**: The build menu icon for Serpulo Launch Pad and the texture while being built don't correspond to the new Launch Pad texture and instead still use the V6 texture. Not much else to say.
Happens in every sector at all times but save file linked below just in case, I don't want to get my soul reaped.
No mods, no crashes.

**Save file**: [sector-serpulo-10.zip](https://github.com/Anuken/Mindustry/files/10094704/sector-serpulo-10.zip)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
I see no bug

It's just the pod

**Comment by Shadow3276** [comment]
It's not a bug but I don't know where else to report it

**Comment by Shadow3276** [comment]
Ooh I see what you mean now, it should've been a pull request instead, my bad. Should I delete this one and put it there or do I keep this here?

**Comment by Bottinator22** [comment]
A pull request is requesting that something you did be included in the game

~~are you sure you can do that~~

**Comment by Anuken** [comment]
The pod isn't supposed to be part of the texture.
