### ISSUE TITLE
Enemy turrets have infinite ammo

### ISSUE THREAD

**Issue by Ultrakekskanone** [Anuken/Mindustry#7997]
**Platform**: Windows
**Build**: steam build 140.4

**Issue**: Enemy turrets don't draw ammo anymore from their attached conveyer belts or similar blocks. They just shoot infinitely.

**Steps to reproduce**: In my replay you can see an example of that, shortly before the end. I am at the northern side of the enemy base and trigger one of their anti-air turrets. You can see perfectly, that no ammo is used from the supply chain and the turret keeps shooting.

**Link(s) to mod(s) used**: none

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the lat
[sector-serpulo-101.zip](https://github.com/Anuken/Mindustry/files/10096251/sector-serpulo-101.zip)
est release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ultrakekskanone** [comment]
Sorry in advance, the attached save file is down between the two confirmations. "sector-serpulo-101.zip"

**Comment by Bottinator22** [comment]
Mindustry doesn't have a replay feature, we can't see your exact actions or which turret it is

**Comment by Ultrakekskanone** [comment]
Oh, I didn't know that but as far as I've played so far, every turret has this issue. So you can try any preplaced turret on any sector you like to test it out.

**Comment by Splarkszter** [comment]
Turrets have ammo storage inside them you know?

**Comment by Splarkszter** [comment]
Just rush at them, cut the convenior first and then destroy the turret.

**Comment by Splarkszter** [comment]
If you need no more help please close this issue.

**Comment by Ultrakekskanone** [comment]
I am aware that turrets have an ammo storage inside them but I was trying single enemy turrets for **minutes** and it didn't went out of amo, while no conveyer belt was connected to it.

Can't you just please look into the code if through some update the ammo capacity in enemy turrets are bugged for some reason?

**Comment by Anuken** [comment]
The turrets in that particular map have a large amount of "extra" ammo, if I recall correctly.
