### ISSUE TITLE
OpenGL error when opening the game even with the latest available OpenGL update higher than 2.1

### ISSUE THREAD

**Issue by ErPyrex** [Anuken/Mindustry#7999]
**Platform**: Windows 10 (Not Steam)

**Build**: GitHub Version 7.0 Built 140.4 (.jar) 

**Issue**: When trying to open the game, it throws me an error: **_"Your graphics card does not support the right OpenGL features._**

**_Try to update your graphics drivers. If this doesn't work, your computer may not support Mindustry._**

**_Full message: GLEW failed to initialize: Missing framebuffer_object extension._"**

![Crash](https://user-images.githubusercontent.com/74994780/204113275-146fbfb8-815c-43fa-99a8-b867b7565be5.png)

Previously, this did not happen, it should be noted that before I used Windows 7 x64, and I also used Linux Mint 20 x64, in both it did not give an error.

I tried updating my graphics driver, but it didn't work either when updating it or going back to previous versions.

![Driver info](https://user-images.githubusercontent.com/74994780/204113446-688ea553-edd4-4aac-8fe7-60b0ce0fa49d.png)

I tried different games to see if it would happen, but no, it only happens with Mindustry.
I use Windows 10 22H2

![winver](https://user-images.githubusercontent.com/74994780/204113568-0fce0f5a-3a05-42ea-a884-f529f5a3e6ab.png)

**Steps to reproduce**: Open the game 👍 😎 (xD)

**Link(s) to mod(s) used**: Not Applicable

**Save file**: Not Applicable (I can't open the game)

**(Crash) logs**: Log in C:\Users\$USER$\AppData\Roaming\Mindustry\crashes

[crash-report-11_26_2022_20_13_15.txt](https://github.com/Anuken/Mindustry/files/10097256/crash-report-11_26_2022_20_13_15.txt)

---

- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by ErPyrex** [comment]
**Observation** : The Itch.io version (current one that is available in Itch.io) does work for me, but the GitHub version (.jar) does not.

![Itch io version](https://user-images.githubusercontent.com/74994780/204115722-016a0e70-5f50-41a2-b68d-d6e0ca815875.png)

**Comment by Erisfiregamer1** [comment]
**Mindustry uses OpenGL 3.3.**
At least that I'm aware of. What Intel HD Graphics do you have, 3000?

**Comment by ErPyrex** [comment]
**There is no information on what it is.**

I couldn't tell you if it's the 3000, even if you look in the device manager or in the driver panel it doesn't say which one it is.

The only information I could get was with GPU-Z and the photo is in the first post

**Comment by Erisfiregamer1** [comment]
What's your CPU?

**Comment by ErPyrex** [comment]
**Processor**: Intel(R) Celeron(R) CPU 847
**Cores**: 2 (1.10GHz)

![imagen](https://user-images.githubusercontent.com/74994780/204375555-4715f1dd-5c64-4dab-ac0d-95ed7d68e607.png)

**Comment by Erisfiregamer1** [comment]
Looks like you have normal (generic) HD graphics. Those only support OpenGL 3.3 (non-github builds use 3.1??) on Linux, particularly with the MesaGL driver. Look it up. Sorry :(

**Comment by Splarkszter** [comment]
.jar files require Java installed. Make sure you java the required version of Java before trying to run a .jar file.

If you need no more help please close this issue.

**Comment by Erisfiregamer1** [comment]
> .jar files require Java installed. Make sure you have the required version of Java before trying to run a .jar file.
> 
> If you need no more help please close this issue.

Someone's got ~~brain damage~~ no knowledge on how .jars work. You need Java to run them.
Considering they got that error (an error thrown by mindustry itself), it tells you they probably already DO have Java...

**Comment by Splarkszter** [comment]
> Considering they got that error (an error thrown by mindustry itself), it tells you they probably already DO have Java...

Then explain how he can run the .exe no problem.
Probably a mismatched Java version or no java at all.

**Comment by Erisfiregamer1** [comment]
The ***exact same thing*** happened to me. I had the needed Java version for Mindustry.

The solution was Linux, as usual.

**Comment by Anuken** [comment]
If the exe version works for you, use that one.

**Comment by Erisfiregamer1** [comment]
Why not fix it on the .jar then?

**Comment by Anuken** [comment]
There is absolutely no difference in code between the .jar and Steam, I can't "fix" a problem that is not on my end.
