### ISSUE TITLE
Unable to play multiplayer games using either hamachi or portforwarding

### ISSUE THREAD

**Issue by TheChosenEvilOne** [Anuken/Mindustry#80]

**Comment by Anuken** [comment]
Make sure Hamachi/port forwarding is set up correctly, and that nothing is interfering.
I know it works for many _other_ people just fine, so it's most likely a problem with your system or setup.

**Comment by TheChosenEvilOne** [comment]
so, the player who tried to join had to portforward to join

**Comment by Anuken** [comment]
That doesn't make much sense, as many people have joined my servers without needing to portforward.. but whatever works, I guess.

**Comment by jukben** [comment]
Unfortunately we get `idInUse` in case we try to play via Hamachi, any idea why is that happening?
