### ISSUE TITLE
the lake is broken (nvm fixed itself)

### ISSUE THREAD

**Issue by Theguywithsomesoup** [Anuken/Mindustry#8000]
on ipad kinda old ios
 `release build 140.4`

i broke the enemy core and it says 1 enemy core help also theres a purple version of my drone im controlling and its invincible

idk it just broke

i dont even know how to mod

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

i dont understand what the text above is

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---
Not a crash the game is broken

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [im not sure ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [no i havent ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Theguywithsomesoup** [comment]
halp

**Comment by Theguywithsomesoup** [comment]
Nvm it fixed itself

**Comment by Splarkszter** [comment]
Please close the issue when you don't need more help.

**Comment by Theguywithsomesoup** [comment]
how do i close it that was the first time ive been on github

**Comment by Theguywithsomesoup** [comment]
Thank you!
