### ISSUE TITLE
Multiplayer campaign Erekir - Repeated crashing, sometimes minutes apart

### ISSUE THREAD

**Issue by mrendleman** [Anuken/Mindustry#8007]
**Platform**:  Windows 10

**Build**: Steam Build 140.4

**Issue**: Have played around 6 hours, entirely in multiplayer campaign (2P, Erekir, I am hosting). Experiencing sudden crashes without an error message or a crash log. Sometimes crashes when destroying final core, sometimes when we're both removing a lot of structures. Most recently crashed three times in a row on Basin, during the countdown to the nuclear launch. Another thing to note is that when loading back after a crash, sometimes the mission objective bugs out, saying "Wave 1: waiting...". I click the play button, and it changes to "Wave 2: waiting...". One of these times I clicked through to Wave 20+. Prevents sector capture, the only way to continue the campaign was to abandon.

**Steps to reproduce**: I wish I knew. May be related to destroying the final core, may be related to lots of map changes happening quickly.

**Link(s) to mod(s) used**: I am not using mods.

**Save file**: Since there were multiple crashes, here's the contents of my saves folder: 
[saves.zip](https://github.com/Anuken/Mindustry/files/10109132/saves.zip)
The most recent couple are from the Basin crashes.

**(Crash) logs**: "No crash logs found." I even looked in %appdata%/Mindustry/ and all it has is last_log.txt: 
[last_log.txt](https://github.com/Anuken/Mindustry/files/10109142/last_log.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by loganb1089** [comment]
im having the same issue

**Comment by MrEevee** [comment]
Experiencing the same issue, playing with 3 people including me. Crashes happen on Core kills and deconstructing/constructing large amounts at one. Strangely only Host crashes with no logs. Resources reset annoyingly to after crash.

**Comment by Anuken** [comment]
Cannot fix without a log.

**Comment by mrendleman** [comment]
> Cannot fix without a log.

Seriously? A big part of this issue is that the crashes don't leave any logs.

**Comment by Anuken** [comment]
There is nothing I can do with no information.

**Comment by mrendleman** [comment]
You could try to recreate the bug? Maybe even with the save files I provided.

**Comment by Anuken** [comment]
I've already played quite a lot of multiplayer on and off Steam, and never encountered it. Neither have most other people, clearly. 

The closest issue it could be is apparent graphics driver bugs that have occurred to some people while streaming the game through Discord under similar conditions, but those **do** leave crash logs of a different kind in the game local files - so either you have not looked for those, or it's something completely different.
