### ISSUE TITLE
Guardians Don't Show Up

### ISSUE THREAD

**Issue by Jammo2000** [Anuken/Mindustry#8010]
**Platform**: Mac

**Build**: Steam 140.4

**Issue**: No guardians spawn on some attack sectors. The "Guardian in X waves" popup happens, but the wave that should have the guardian has no units in it and ends as soon as it starts. Other waves happen as normal, although on one sector (229) some non-guardian waves were empty.

**Steps to reproduce**: Launch to some attack sectors (I've found the bug on serpulo 24, 229, and one other that I can't remember). It might happen on all, I haven't checked. Play as normal, until the guardian is supposed to appear. When the wave with the guardian starts, observe that no units spawn and the timer for the next wave starts.

**Link(s) to mod(s) used**: I have [Time Control](https://github.com/sk7725/TimeControl) and [RTFM](https://github.com/DeltaNedas/rtfm) installed, but I don't think they are relevant here.

**Save file**: 
[sector-serpulo-229.msav.zip](https://github.com/Anuken/Mindustry/files/10118128/sector-serpulo-229.msav.zip)
[sector-serpulo-24.msav.zip](https://github.com/Anuken/Mindustry/files/10118129/sector-serpulo-24.msav.zip)

**(Crash) logs**: N/A, no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 00001H** [comment]
It is probably because in v7 numbered sectors are randomly generated and some waves are broken.
There was an attack sector with NO WAVES AT ALL. Free sector :)
Pay attention to the guardian unit. Can it spawn on your map?(I am not on steam ver can't load your files)(e.g. naval units without river connecting spawnpoint and your core)

**Comment by Jammo2000** [comment]
Yes they could spawn. It was a corvus twice and a reign once, and they all
had a path. Probably that sector generation bug.

**Comment by Anuken** [comment]
Bug seems to have been fixed with other commits.
