### ISSUE TITLE
Bug with poly/mega (RU)

### ISSUE THREAD

**Issue by Industrial15** [Anuken/Mindustry#8012]
**Platform**: Windows 

**Build**:  release build 140.4

**Issue**: во время волны с массой противников заметил что на моей базе появились странные Поли и Мега. Они имели уничтоженую текстурку, были уязвимы к любому урону (даже аннигиляция им ни по чем) не слушались комманд, и самое главное имели свойство тонуть... 

**Steps to reproduce**: Это произошло самостоятелтно, во время волны Мега и Поли решили починить стенку, получили куча урона от врагов и взорвались на ториевом реакторе, и не умерли!

**Link(s) to mod(s) used**: Без модов

**Save file**:  [Here](https://drive.google.com/file/d/1VwdnGDlEsQxq1HRR-AXLPYJFjHigVg7u/view?usp=drivesdk) 

Dont eat me pls)

**(Crash) logs**: Nope, its not crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Industrial15** [comment]
Неуязвимы* im sorry

**Comment by Anuken** [comment]
I see no issue in the save.
