### ISSUE TITLE
Borderless Fullscreen not working as intended

### ISSUE THREAD

**Issue by Splarkszter** [Anuken/Mindustry#8014]
**Platform**: Desktop-Windows10

**Build**: 140.4

**Issue**: When selecting Borderless Fullscreen the game acts like if it was on Fullscreen.

**Steps to reproduce**:
- Have the Fullscreen setting turned off.

- Turn on the Borderless Fullscreen setting.
[Game will keep itself on top of everything, even if you bring the Home menu of windows it will open but you won't be able to see it or click on it].

- Turn off the Borderless Fullscreen setting.
[Game will behave like a normal Borderless Fullscreen window. You can bring the Home menu and you will see it and the game won't minimize].

**Notes**: The program/game keeps itself on top of everything, unable of having other windows on top of the game window or even the Home menu itself. I have the autohide-taskbar setting on, and in the top position.

Borderless Fullscreen should mean the same as Borderless Windowed, meaning it acts as a window but takes the whole screen.
Yes i restarted the game as it says when hovering over the option and the problem is still the same.

... Disabling the setting after enabling it one time seems to solve the issue(when leaving disabled, yes, it keeps itself on Borderless Fullscreen), that's strange.

If you don't toggle the setting, the problem above starts to happen so maybe some funky line of code not clearing the Fullscreen behaviour.

Here's a video if more clearance it's needed, playing at half speed could be needed if what i do is too fast. Just mute the audio though:
https://youtu.be/5B0zL-hci_w

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Edit: Added steps to reproduce (sorry).

**Comment by Splarkszter** [comment]
Also... i downloaded the game from the itch.io page posted on this GitHub but the .ico of the game is missing(?)

**Comment by BlueWolf3682** [comment]
i cant reproduce this - with most games, my graphics drivers crash on attempting a complete fullscreen so i have to use borderless
in my experience, *none* of the games (mc, terraria, forts, mindustry, starbound, borderlands 2) actually acted completely like a window, but all act the same and dont cause a crash
if the .ico is missing, you likely have a flawed download

**Comment by Splarkszter** [comment]
> 

Yeah, in my side it's not driver issue, it's on the code of the game. When enabling Borderless Fullscreen it seems to enable Fullscreen and Borderless Window at the same time(not referring to menu). Which is something that should not happen.
And when i disable it it keeps itself on Borderless Fullscreen, acting like a normal Borderless Windowed Fullscreen Window.

If i minimize the game and maximize it, it opens as a normal window (probably because it does some check and realizes the Borderless Fullscreen option is not on).

Also, a tip for you: Try disabling Fullscreen Optimizations. A windows setting.

**Comment by Anuken** [comment]
I've messed with the fullscreen/borderless settings so many times and the result is so inconsistent across devices that I simply don't care to do anything about it anymore.

**Comment by Splarkszter** [comment]
Ok, well. At least i know how to fix it on my case.
