### ISSUE TITLE
V7 bridges display bug + fix

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry#8015]
126.6
![image](https://user-images.githubusercontent.com/45213805/205204895-e58e913f-88c3-4a88-a60d-19fdbe7f6804.png)
140
![image](https://user-images.githubusercontent.com/45213805/205204924-6e2c8841-7499-450b-96c8-6337b805e059.png)

The bridge is stretched vertically and it covers the whole block and its horrible

![image](https://user-images.githubusercontent.com/45213805/205204806-fe28dcb0-2c2b-49aa-89b3-a948c9905bbf.png)
as you can see, the problem does not come from the code but from the crop applied to the sprites
![image](https://user-images.githubusercontent.com/45213805/205205427-420e0345-76a5-421d-ad9f-1bf5f7d93f0d.png)

Fix : add all bridge sprites as exception to the cropping algorithm

While youre at it, you can search through all uses of the `draw.scl()` method and add the sprites affected to the exception list since they are most likely affected as well

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by 00001H** [comment]
try making a PR if you can...?

**Comment by LeahLuong** [comment]
I agree. It's horrible. It's. "Its" is the possessive use of this noun & should be used thusly: _**its**_ horribleness cannot be countenanced for longer than the span of a few milliseconds before 1 realizes _**it's**_ not going to get better unless something drastic is done!

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/211168183-46280771-86c8-4317-9949-7bfa84ed6626.png)

~~this is actually the wrong bridge code, completely unrelated~~
