### ISSUE TITLE
Auto path don't worok

### ISSUE THREAD

**Issue by NazarikCH** [Anuken/Mindustry#8024]
**Platform**: Android 10

**Build**: 140.4

**Issue**: *when i place the conveyor and try to travel some wall or a hill, the auto path don't work.

**Steps to reproduce**: you know how to place a line of conveyor in a wall right😳?

**Save file**: https://drive.google.com/file/d/1PFaJyGSTU2eEpz75PnK4J_jTXrUMGnxc/view?usp=drivesdk

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
Have you tried pressing this button?
![Screenshot_20221204_141827](https://user-images.githubusercontent.com/62336673/205487505-0275a6a8-c442-44d4-9ac9-6c568ca3d335.jpg)

**Comment by NazarikCH** [comment]
sorry for the inconvenience
I misunderstood that sentence
"Automatic block suggestions"
It was turned off

automatic block suggestions is not very intuitive.
