### ISSUE TITLE
iOS word document from Files opens mindustry if installed

### ISSUE THREAD

**Issue by Maxime90Rigaud** [Anuken/Mindustry#8026]
**Platform**: iOS

**Build**: latest, but bug was present before

**Issue**: when Mindustry is installed on my iPhone (11), any word document I try to open in Files will try to load mindustry and Crash. I can’t have mindustry installed or it systematically does this.

**Steps to reproduce**: open a word document in Files

**Link(s) to mod(s) used**: No mod

**Save file**: N 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: no crash report on iOS ?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [C] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't debug this without a crash report. As for the word document thing... I have no idea why your device would make that association, Mindustry should only register as handling map files.
