### ISSUE TITLE
Surge alloy unlocked before (Nitrogen!?) in Erekir

### ISSUE THREAD

**Issue by Priyantha-IT21021534** [Anuken/Mindustry#8028]
Android

Release Build 140.4

As I go through the Erekir sectors, when I get to Ravine sector I unlocked Surge Alloy and then unit cargo loader. But the cargo loader needs Nitrogen to activate. When I look in the tech tree, There is a locked item immediately before surge alloy which I assume must be Nitrogen!? I don't know if unlocking Surge alloy before Nitrogen was intended. But skipping a locked item to unlock something below it sure feels wrong and weird 

I didn't do anything special to come to this assumed bug. Just went through the Erekir sectors in the unlocking order. This happens when reaching Ravine.

No mods were used

I'm so sorry But I can't find how to upload a zip file into this log from my android phone. Hope the bug description is clear enough.

~~Sorry if I attached the wrong file. I haven't done this before from my phone. I took this zip file from menu > settings > Game data > Export data.~~

Game did not crash

![Screenshot_20221206_145202_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/87350551/205880709-13079e99-4eb1-4dd7-972d-98312085d20b.jpg)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DanUnderscore** [comment]
You dont have atmospheric concentrator researched.

**Comment by Priyantha-IT21021534** [comment]
I see that I need to unlock the atmospheric concentrator to make Nitrogen. But that is only available on the research tree after starting the next sector. I suppose "making atmospheric concentrator available after completing Ravine" or "making unit cargo loader available only when starting next sector" would be a solution to this?

**Comment by overdramaticpanromantic** [comment]
That item is Thorium, unlocked in Stronghold. Research the atmospheric concentrator.

**Comment by Nataly171** [comment]
Why is this closed as completed? The Cargo Unit Loader and Unload Point become available in the Research tree before the player has access to Nitrogen, which is the subject of the issue.

The layout bug with Surge Alloy appearing after Nitrogen is fixed, but not the actual mixup in progression.
