### ISSUE TITLE
데이터 가져오기가 안됨

### ISSUE THREAD

**Issue by Skyhero011** [Anuken/Mindustry#8030]
저는 데이터를 가져오기를 하는데 안된다 모바일이여서 그런가요?

**Comment by AshesKaiser-KR** [comment]
써져있는 버그 신고 양식은 장식일까요
그리고 왜 한국어로 적으셨나요 설마 게임 제작자가 한국인이라고 생각하신 건가요?

**Comment by SpaceEarthEX** [comment]
scolded by Ashe
(Close this Anuke)

**Comment by Skyhero011** [comment]
Sorry. I didn't know English very well. I'm a Korean user, but l tired to
import data to another device, but it didn't work, so l sent a message
sorry once again.

2022년 12월 8일 (목) 오후 4:57, SpaceEarthEX ***@***.***>님이 작성:
