### ISSUE TITLE
Multiplayer: No units visible on client if server is connected via several network interfaces

### ISSUE THREAD

**Issue by westnordost** [Anuken/Mindustry#8036]
**Platform**: 
- Server: Linux
- Client: Tested with Mac and Android (same outcome)

**Build**: 140.4

**Issue**: 
Joining a game hosted by a friend of mine (@themad on Linux) does not work correctly.
1. The remote server is listed with the error "Can't connect to host"
![Screenshot 2022-12-07 at 20 21 04](https://user-images.githubusercontent.com/4661658/206277023-cce6c0bd-d584-4f44-b5a9-71b1c0c7dd87.png)

2. However, when clicking on the server, the client **does** join the game successfully. However, no unit is visible on the client (on the server, the unit **is** visible) and all units moving around are invisible to the client. When units destroy or build buildings however, the change to the buildings (created building, destroyed building) is visible too.
![Screenshot 2022-12-07 at 20 21 41](https://user-images.githubusercontent.com/4661658/206277647-2c08969a-26e5-429a-9cf5-dcd17fc10bdd.png)

**Steps to reproduce**: 
We actually found out what the problem was: The server is connected to the router via both wifi and ethernet. This seemed to somewhat confuse the game in this regard.

**Save file**:
The save file is indeed irrelevant to reproduce the issue, see above. It is reproducible with a fresh campaign start. However, since I don't want my soul reaped, the zip from Settings -> Game Data -> Export Data while being connected to that server is attached. :-)

[gamedata.zip](https://github.com/Anuken/Mindustry/files/10179494/gamedata.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoSko** [comment]
AFAIK this a known problem in Linux, not a game - by default, any responses from **any** server service don't guarantee to use the interface. There are several solutions to it, starting from iptables custom routing down to patching network drivers, but I guess you'll have to DYOR.

**Comment by buthed010203** [comment]
Hmm this may be the culprit behind a very similar problem that some steam lobbies have had for years

**Comment by overdramaticpanromantic** [comment]
I've had this issue too, Anuke is unlikely to fix it as buying devices to try and find a workaround is expensive.

**Comment by Anuken** [comment]
This looks like a weird issue with UDP packets, as pinging uses UDP, as does unit sync.

If even **pinging** doesn't work... it's probably a linux problem.
