### ISSUE TITLE
Conservative Generators

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#804]
- [ ] Make generators stop consuming resources when no power is being requested. Somehow.

**Comment by 231ACR** [comment]
If possible create a ,boolean full, propose is that when the thing is full or clogged or over it will turn true which causes power consumption disabled but redundant power continue (Simply it will act as relay)(Silly approach I know)

**Comment by azureblue** [comment]
Considering a connected graph, I think that the biggest problem is to choose the generator(s) to shut down, like what would be the criterion for that? In general If we consider only their output power then it looks like a _change-making problem_. But considering that some generators consume more resources per unit power it gets complicated (let alone considering different value or resources :)).

**Comment by Tazshelby2016** [comment]
It will require changing how power works, from the source giving power to the users, to the users requesting power from the source.

**Comment by azureblue** [comment]
Maybe.. but I think it doesn't matter. The current approach (having a power pool being created at every update and then distributed) seems just fine. 

Anyway, it won't significantly help to solve any of the challenges I've mention in the previous comment.

**Comment by 231ACR** [comment]
New Approach, (working on factories rather than powers system)
Make factories to detach to node on clog or full and automatically connect when something happens. Your own choice how to set this stimulation.

**Comment by LionelBergen** [comment]
@Anuken 
I'm new to this game, what do you mean by 'no power is being requested'? 
Only things I can think are if their is no attached batteries, or the batteries attached are full

**Comment by Anuken** [comment]
I'm referring to situations where you have a generator running on its own with no outputs, or a group of generators producing 100 power/sec while the grid only consumes 50 power/sec.

**Comment by LionelBergen** [comment]
@Anuken 
Working on this now. Looking at code it looks like power is given fully to every consumer. Is that correct? 
For example if a tile is producing '50 power' and there are 2 units that need '50 power', will each one get 50? Or will they both get 25?

**Comment by Anuken** [comment]
Each will receive 25.

**Comment by LionelBergen** [comment]
@Anuken  PR #825 should do the trick. Let me know if theirs any issues or suggestions relating to it

**Comment by runiArnsbjornson** [comment]
might be "naive" but why not act like the factories ? make a small reserve of power inside every generator (even a hidden one) then if power is not consumed (ie : the power grid is already in a positive state) the reserve will fill, at full capacity, stop production, as soon as reserve decrease, restart production ?

**Comment by LionelBergen** [comment]
@runiArnsbjornson Yep, this is what I am working on now. A hidden 'overflow', used when power is short, or when it can count for an entire input

**Comment by LionelBergen** [comment]
Not sure how to move this back to draft, will be a while before I continue it

**Comment by 1RedOne** [comment]
@LionelBergen , just close the pr but dont delete the branch. You can make a new PR whenever you want.

@Anuken don't power relays and nodes consume power themselves?  If they do, then we'd have to think of a concept like 'is a customer connected to a node' and inherit that back up to the generator.

Another fun wrinkel, what to do about Thorium reactors, which can explode if you're not careful in disconnecting their resources.

**Comment by Anuken** [comment]
> don't power relays and nodes consume power themselves?

Nope.

I was thinking about this recently, and I believe a simple solution involves the following:
- Calculate surplus power, after all batteries are charged and satisfaction is distributed
- Calculate this number as a fraction of total power produced
- Pass the result to all generators
- Make all generators consume resources at a speed equivalent to this fraction (clamped to [0-1])

This would make the power output continue to be the same (visually), but resources would only be consumed proportionally to how much power is actually used. For example, if only 50% of power is used from a combustion generator, then coal would be consumed at half rate.

**Comment by 231ACR** [comment]
Make building pause
if not possible to cut power at being full.

**Comment by ado1928** [comment]
Make it work like in Factorio. Every generator has a performance variable that changes according to demand. Prioritize renewable energy (solar panels) over other energy. Every power grid has "avaiable performance" - sum of all maximum power outputs of every battery, "power consumption" - sum of all power consumptions of each consumer and "satisfaction" - how much power you consume vs max performance.
Batteries will act as power consumers with excess power and as generators when theres a lack of power.

**Comment by Quezler** [comment]
Hmm, just had a thought, won't this trick users into a false positive?

> "oh wow, this 1 grey belt of coal can feed 40 steam engines!"

**Comment by RogueRedHawk** [comment]
One thing that would be interesting and would encourage building and design from the players is an indicator and logic gate/switch gate. An indicator could determines when power is positive or negative. It could be an LED so the player could also use it to monitor the power graph, perhaps green when <+1000W/s, yellow when +100-+1000W/s, flashing yellow when >+100, slowly flashing red when >0 and consuming reserve power, and rapidly flashing red when no reserve power and production is less than 0. This could be placed next to a toggleable gate of some kind ("Power Gate" or something) that would open when the indicator is a certain color/state or when a player taps/clicks on it. I could choose to only produce more power when I'm low and produce graphite or silicon when I have reserves back. That would be two whole new blocks but they would be useful in other situations as well.

**Comment by thomas-spriggs** [comment]
I have raised a PR for this here - https://github.com/Anuken/Mindustry/pull/1137

**Comment by joe8448** [comment]
This isn't working for me. The combustion generators still use coal even when the generators aren't connected to anything. I'm on android, and I updated the version from the play store a few hours ago.

**Comment by Anuken** [comment]
Of course not - this was never actually implemented, and isn't supposed to be in the game.
