### ISSUE TITLE
Where sand in sector 219

### ISSUE THREAD

**Issue by CallMeDutch2141** [Anuken/Mindustry#8042]
**Platform**: `Windows 10 x64`

**Build**: `steam build 140.4`

**Issue**: Sector 219 resources list sand among them. I've looked around the sector 35 times now, and I don't see a single sand tile. Am I missing it? The texture of sand and snow is pretty similar, so I guess I might be looking over it. I looked for someone with the same issue but found nothing.

**Steps to reproduce**: just play.

**Link(s) to mod(s) used**: `none`

**Save file**: [sector-serpulo-219.msav+backup.zip](https://github.com/Anuken/Mindustry/files/10190510/sector-serpulo-219.msav%2Bbackup.zip)

**Crash report**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Agzam-Ar** [comment]
# You can use ![](https://mindustrygame.github.io/wiki/images/item-scrap.png)[Scrap](https://mindustrygame.github.io/wiki/items/8-scrap/) and `30 power units/second` to create ![](https://mindustrygame.github.io/wiki/images/item-sand.png)[Sand](https://mindustrygame.github.io/wiki/items/4-sand/) in ![](https://mindustrygame.github.io/wiki/images/block-pulverizer-ui.png) [Pulverizer](https://mindustrygame.github.io/wiki/blocks/169-pulverizer/)

![image](https://user-images.githubusercontent.com/90514725/208286687-1a0b8a32-e875-4f5b-8bfe-0dae43e47def.png)
