### ISSUE TITLE
Titans can only hit one building at a time

### ISSUE THREAD

**Issue by Garen7** [Anuken/Mindustry#8043]
**Platform**: Windows

**Build**: 140.4

**Issue**: If a Titan shoots a block directly it will only hit that block. According to MeepOfFaith this is because building splash damage is handled with raycasts. Easy fix is to add shrapnel or etc but maybe it would look ugly or you dont think its needed so Im just posting here. Video [here](https://streamable.com/e1y1vb) if you want to see it.

![image](https://user-images.githubusercontent.com/22408776/206618719-9569a7d6-747b-4ba9-9ef5-a57b252bdd4e.png)

**Steps to reproduce**: 
1. build some ducts as the enemy
2. shoot the ducts with a titan
3. only 1 duct dies

**Save file**: [TitanSplashDamage.zip](https://github.com/Anuken/Mindustry/files/10191597/TitanSplashDamage.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug.
