### ISSUE TITLE
What happen in sectors 229 ??? (playing on android)

### ISSUE THREAD

**Issue by sandXI** [Anuken/Mindustry#8046]
![Screenshot_2022-12-09-22-47-33-80_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/120228140/206814803-65ab85f7-fba5-4d99-8802-62a178914705.jpg)

![Screenshot_2022-12-09-22-47-45-75_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/120228140/206814790-dc8ed6ee-5d71-410a-8279-4f49dadf5503.jpg)

![Screenshot_2022-12-09-22-47-58-84_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/120228140/206814783-7e8916aa-988b-41a6-8fa9-2bef4a450be7.jpg)
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
pov crux decides theyve waited long enough

**Comment by Breadyboi69** [comment]
I don't see any problems here

**Comment by matkoniecz** [comment]
> Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
