### ISSUE TITLE
Bug on Serpulo sector 47

### ISSUE THREAD

**Issue by Serzhmmm** [Anuken/Mindustry#8047]
Platform: Android, Xiaomi

Build: 140.4

Issue: After caprure the "Coastline" sector (Serpulo) I move to the neighboring sector "47". A threat emanates from it. Sector has a medium threat, but 104 enemies attack immediately on the first wave. Most of the enemies are level four. Others are the second or third level. It's too much and impossible to pass. 

Steps to reproduce. I just landed in sector 47 and waited for the first wave. This bug is always repeated after every land. 

No mode, original. 

Save file: 
[file.zip](https://github.com/Anuken/Mindustry/files/10200198/file.zip)

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Breadyboi69** [comment]
This phones name is xiao ling
