### ISSUE TITLE
Sector 47, Too much enemies

### ISSUE THREAD

**Issue by Serzhmmm** [Anuken/Mindustry#8048]
Platform: Android

Build: 140.4

Issue: After caprure the "Coastline" sector (Serpulo) I move to the neighboring sector "47". A threat emanates from it. Sector has a medium threat, but 104 enemies attack immediately on the first wave. Most of the enemies are level four. Others are the second or third level. It's too much and impossible to pass. 

Steps to reproduce. I just landed in sector 47 and waited for the first wave. This bug is always repeated after every land. 

No mode, original. 

Save file: 
[file.zip](https://github.com/Anuken/Mindustry/files/10200198/file.zip)

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeahLuong** [comment]
Have you tried setting up a couple of duos supplied w/ copper & waiting it out??

**Comment by Serzhmmm** [comment]
> Have you tried setting up a couple of duos supplied w/ copper & waiting it out??

By the way, I built various factoeies and deposits at the first time. It wasthe first time I saw the bug

**Comment by LeahLuong** [comment]
IDK, that's just what I'd try. Maybe the defenses can handle the attack if you aren't watching it.

**Comment by Serzhmmm** [comment]
> IDK, that's just what I'd try. Maybe the defenses can handle the attack if you aren't watching it.

This problem doesnt depends on it. There are always 104

**Comment by Serzhmmm** [comment]
There are 104 always, even if you build a good base
