### ISSUE TITLE
Better Team Indication

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#805]
Brainstorm ways to make the team indicator on blocks/units look better **without** incurring expensive performance costs on color shaders or outlines.

**Comment by 231ACR** [comment]
use thickened markers with black borders.

**Comment by ThatOneBepis** [comment]
For arcs, change default color of blue bits to gray, which could be used for Gray team. In other teams, change the color of said bits to the color of the team (if you understand what i tried to say)

**Comment by Tazshelby2016** [comment]
It seems that the art for the blocks/units needs to be redesigned. As @ThatOneBepis said, this can be done by recoloring the sprites to the team's color, or by using an overlay sprite colored in the team colors.

**Comment by 231ACR** [comment]
How this is can be more effective?
changing colors only lessens it memory wise, which will not lessen any burdens on GPU's processor.

**Comment by Tazshelby2016** [comment]
@231ACR  It will add nothing to the GPU, as it is simply making the colors different.

**Comment by LionelBergen** [comment]
What is currently done to indicate team?
We could check how expensive shaders/outliners are, if we ensure they are done once per sprite.
I agree with above comments about simply changing the colors to the teams color.

**Comment by ThatOneBepis** [comment]
Current indication on the team is quite unoriginal considering every building has it (stripe of color in the bottom right)

**Comment by Arkanic** [comment]
either a simple kind of "hovering" icon over the block/area in question, or have the "default" (background) block colour change to that specific team
e.g. the core's background "grey" colour changes to red

**Comment by ThatOneBepis** [comment]
Concerning custom blocks from modding, how would they behave? background color, while it may seem something straight outta b63, is something what may solve this issue

**Comment by Luxray5474** [comment]
Personally really loved the nice ***t h i c c*** outlines back when the game had pixelated graphics. I wish those would come back, but I recognize the performance implications.

* Are shadows a class that is applied to blocks or chunks of blocks individually? If they are then tint the shadow of a team member with their color. 
* The good old method, which is editing the sprites to match the color of the player's team, is probably the easiest. That includes their bullets too! However that just doubles the amount of player sprites in the spritesheet.
* Place a circle around the player with their team color. 
* For blocks I agree with Arkanic. However it would look really ugly with the current art style. Any direct modification to the blocks' sprites might result in an almost doubling of the size of the spritesheet. I think the best way would to make a realtime outline, the same way that blocks have an outline when you are choosing what to drop your items into.

**Comment by Arkanic** [comment]
I definitely agree with @Luxray5474 in the fact that whatever is done, it'll have to be done in realtime. another possibility is a subtle team colour bloomshader kind of haloing the enemy objects every time you fly over them or fire.

**Comment by Lilleahy** [comment]
You can make a default pixel color for the sprites that can be changed to the color of the team in real time like in Rusted Warfare. This will keep from having to make multiple sprites and will make it work on items added by mods.

**Comment by NomadicVoxel** [comment]
Two ideas here. 
One, the art would have to be redesigned for this, but maybe the sprites could have a 'shell' that changes color depending on the team. Is the art done with vectors? Maybe do this with a palette swap? Maybe make one of the colors a variable? 
Two, maybe add a flag block that you can place on the corner of your walls. Maybe in the campaign enemies use them liberally, have a HUGE ego. Maybe there can be a way to incentivize players to use flags to mark their turf too, perhaps a defense mode for bots that orders them to stay on the inside of the line marked by the flags?

**Comment by marky0470** [comment]
Maybe we could have the general region where team blocks are be outlined by a non-specific border, it has to make sure that every block is within one of these boundaries. It only draws lines that either along the cardinal directions or 45 degree diagonals to make it nice. It does not affect gameplay in anyway, just graphical indication of where teams are positioned. Serves an extra challenge to know where your blocks are when borders begin to close down.

**Comment by Vortetty** [comment]
add team layers to blocks, by default a colored border unless an image file is provided, this team layer will be all white and just rendered over the block in question then tinted to the color of that team.

**Comment by MEEPofFaith** [comment]
change bullet colors?

**Comment by MEEPofFaith** [comment]
![color](https://user-images.githubusercontent.com/54301439/73722761-22ded600-46dc-11ea-9776-18148eb35e45.png)
Add a tint? (The color you are won't have the tint.)

**Comment by MEEPofFaith** [comment]
![Team Tinting](https://user-images.githubusercontent.com/54301439/73722991-bfa17380-46dc-11ea-9168-c8daf04caa94.png)
actually, 180/255 looks nicer

**Comment by MEEPofFaith** [comment]
_Maybe I should read above comments first._

**Comment by MEEPofFaith** [comment]
> One, the art would have to be redesigned for this, but maybe the sprites could have a 'shell' that changes color depending on the team. Is the art done with vectors? Maybe do this with a palette swap? Maybe make one of the colors a variable?

No, it's not vector art. Every tile is a 32x32 image, and 32px being the length of one tile is global. effects though are separate, though I think might still be subject to the 32x32 "rule".

**Comment by Anuken** [comment]
I think I've collected enough suggestions now. Any further progress requires actually coding these and testing them in-game.
