### ISSUE TITLE
strange error with JSON parser causes canGameOver problems

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#8050]
**Platform**: *Windows/Android*

**Build**: *140.4/"latest"*

**Issue**: *Somehow, on loading Exotic Mod's 0.8 branch, sectors that the mod DOESN'T EVEN TOUCH just suddenly cannot game over.*
![Screenshot_20221210-103527](https://user-images.githubusercontent.com/61173114/206868036-5a470817-4698-45f1-89c5-acf3d86aaa1e.png)
![Screenshot_20221210-103508](https://user-images.githubusercontent.com/61173114/206868038-31d015f8-6bd2-4005-90ee-c7b452f58008.png)
*this consistently happened for me with the mod's Crash Site map personally.*

**Steps to reproduce**: *Unknown - it appears simply loading the mod and attempting to play vanilla randomly causes the bug. HOWEVER, in this case even lacking a solid reproduction method, this bug report should not be immediately closed. It's really a major issue.*

**Link(s) to mod(s) used**: *https://github.com/BlueWolf3682/Exotic-mod/tree/0.8*

**Save file**: *this was reproduced on an Android client and a Windows client. Neither of the clients have significant save states either. If it happens only to specific users, I am honestly rather concerned what you did to the parser.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *h*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
As expected, I can't reproduce the issue above... and funnily enough, I can't even test the sector in the mod, as it is unsupported/broken and crashes the game due to invalid map data.

**Comment by BlueWolf3682** [comment]
im sorry what, i can load crash site just fine???
also it appears this is something of a larger issue, ive noticed others have been getting it randomly without mods

**Comment by Anuken** [comment]
Oh wait, wrong map, I was used to testing the battlefield one. But it's the same issue: canGameOver is false.

Here's the problem: **There is no code in the game that can possibly set canGameOver to false.** Or any other value, really. There are only 3 occurrences of that word - one is the variable declaration, one is a check for it, and the last is in a unit test (completely irrelevant).

Are you maybe using some sort of utility/testing mod that disables it? If this were an inherent issue with the game, I would have expected to see it more often. Until more people come forward with saves, there is nothing I can do. It really seems like an issue with some other mod.

**Comment by BlueWolf3682** [comment]
the best guess of another mod changing it is that TU and schem size have a bit of code *somehow* setting it to false after the API updates in v7. that being said, *these should not affect the rule either*
ill check with meep about it, but testing utilities has *no* reference to canGameOver at all in its code
my ultimate uneducated guess is something to do with either the map/planet data itself (which would make the most sense since after v7 theres been wierd other occurrences of sector tomfoolery)
