### ISSUE TITLE
Core upgrades can be shifted by 1 tile on Erekir

### ISSUE THREAD

**Issue by Goontnt** [Anuken/Mindustry#8052]
**Platform**: *Windows*

**Build**: *140.4*

**Issue**: *placing a new core on top of a old core Eg. Citadel onto a Bastion on an edge can shift the core off of the core zone. Note, this happened on stronghold, starting core (i built a Bastion then upgraded after it got exploded)*

**Steps to reproduce**: *1. find a 5x5 core zone 2. build a Bastion 3. place a Citadel 1 tile off of the core zone*

**Link(s) to mod(s) used**: *none*

**Save file**: *[save.zip](https://github.com/Anuken/Mindustry/files/10200896/save.zip)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
not a bug, intended feature
