### ISSUE TITLE
ContentParser Conflicts with IllegalAccessException for some types of blocks

### ISSUE THREAD

**Issue by FatalThrust** [Anuken/Mindustry#806]
**Platform**: (Android/iOS/Mac/Windows/Linux)
Windows
**Build**: (The build number under the title in the main menu. Required.)
Master Build 
**Issue**: (Explain your issue in detail.)
The classes for some of the blocks such as conveyors have the protected keyword
this conflicts with the content parser and will throw errors/exceptions when you try to load the jar/ or run with gradlew desktop:run

I fixed this by making the conveyor class public (just to see if it would work after) and it did
no other issues occured after this change
**Steps to reproduce**: (How you happened across the issue, and what you were doing at the time.)

make a mod with a new content block with type "Conveyor" in json
**IllegalAccessException**:
https://media.discordapp.net/attachments/396416151032299521/631632886373679114/unknown.png

- credit to OfficialDJPatchyIce

**Comment by Anuken** [comment]
Fixed.
