### ISSUE TITLE
Confusing results of playing campaign online - ahead of local state

### ISSUE THREAD

**Issue by matkoniecz** [Anuken/Mindustry#8060]
**Platform**: Linux

**Build**: 140.4

**Issue**: tech tree and 3D planet map are inconsistent - Peaks, Ravine, Caldera were unlocked by playing online but they remain inaccessible and I cannot land there.

**Steps to reproduce**: I played campaign locally (reached Basin). Then I played with friends, ahead of what I have reached and completed Marsh, Peaks, Ravine. This unlocked Caldera and some tech in the tech tree.

But I cannot land on Caldera! I completed Basin what unlocked Marsh but I do not really want to play it again.

I would expect them to be selectable in 3D rendering of sector selector. Though making impossible to unlock content by playing online and making mandatory to redo it locally and have tech tree reflecting this could also work, I guess, to remove bug even if that would be irritating - at least to me.

BTW, eheater and nitrogen remain locked and are not even appearing in my tech tree.

Some people on Discord suggested

> try running Vars.content.sectors().each(b=>b.unlock()) in console

as workaround. I guess that similar may be needed for tech. And also proposed

> I mean just ask your friend for the campaign saves
> And import it into your planet

but not sure is it going to unlock things

**Link(s) to mod(s) used**:  None

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/10240429/saves.zip) (entire `~/.local/share/Mindustry/saves` as it was unclear to me which file should be uploaded given that I played only campaign)

**(Crash) logs**: not applicable

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.** (I also asked on Discord whether I am making some blatant mistake, see https://discord.com/channels/391020510269669376/477494303061442571/1053040143730212925 )

**Comment by matkoniecz** [comment]
Possible solutions:

- unlocks in multiplayer are not lasting beyond the game, except for game owner. All players have the same unlocks as host.
- the same as above but only for maps (force players to replay)
- declare that it is too weird and unusual and anyone doing this should solve this with console commands rather than bothering Anuken
- unlocking something recursively unlocks prerequisites and prerequisites of them and so on - note what I have right now:
 
![screen03](https://user-images.githubusercontent.com/899988/207969983-4707e5a6-88ad-42d4-9df0-e946fd835b29.png)

**Comment by Anuken** [comment]
Frankly, I'm just going to disable **all** research syncing for multiplayer campaigns. Keep them entirely separate.
