### ISSUE TITLE
Shielded wall doesnt accept power after being picked up and placed back down

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#8062]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

Pc

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Steam build 140.4

**Issue**: *Explain your issue in detail.*

after picking up a shielded wall and putting it back down it no longer accepts power or makes a shield

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

1. build shielded wall
2. give power to wall
3. wall makes shield 
4. pick up wall
5. put down wall
6. give power to wall
7. wall no longer makes sheild

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

None

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

Happens on multiple different pcs

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [Y] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [Y] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Legomonster33** [comment]
<img width="114" alt="image" src="https://user-images.githubusercontent.com/54417042/208020133-49e001d9-506b-49d7-9cc4-178b66204024.png">

**Comment by matkoniecz** [comment]
> IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

please post save

**Comment by Anuken** [comment]
![2023-01-07-14-07-48](https://user-images.githubusercontent.com/10100000/211166667-27d8360f-16a5-4470-aaf7-061c59c34f6a.gif)

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
