### ISSUE TITLE
Help i am in much pain my mod browser is not working 

### ISSUE THREAD

**Issue by Guyyyyyyyy** [Anuken/Mindustry#8066]
**Platform**: `Android 29`

**Build**: `bleeding-edge build 23633`

**Issue**: *my mod browser is not working .*

**Steps to reproduce**: *i just clicked on mod browser and it showed error.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
[X] **I have NOT updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

**Comment by buthed010203** [comment]
Unfortunately no one here is a telepath so we can't know what error you get unless you provide it.
