### ISSUE TITLE
Bug with stores and tank

### ISSUE THREAD

**Issue by Vognezir** [Anuken/Mindustry#8069]
**Platform**: Windows 10

**Build**: 140.4
**Issue**:  I found an error, it consists in the fact that the items in the research tree are in the wrong order, namely the containers (tank and cistern) for gases/liquids. first, we examine the tank in which the description: stores a HUGE amount of liquid, in its characteristics we see that it stores 1000 units.
the next in this branch is a tank in the characteristics of which we see that it stores 2700 units and in its description it is written: stores a SMALL number of natives.

**Steps to reproduce**: i was just playing Mindustry and researching new technologies
**Link(s) to mod(s) used**: i dont use mods

**Save file**: 
[sector-erekir-14.msav-backup.zip](https://github.com/Anuken/Mindustry/files/10253645/sector-erekir-14.msav-backup.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: its not crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> in its description it is written: stores a SMALL number of natives.

Looks like a translation error. It does not say that in the english version.
