### ISSUE TITLE
Compilation error, possibly outdated modding guide

### ISSUE THREAD

**Issue by TsarF** [Anuken/Mindustry#807]
**Platform**: Windows 10

**Build**: Source/master/current

**Issue**: When I tried cloning and building the repo, gradlew was spitting out the issue. It said that it could not find files in the assets/sounds directory. I checked the directory is not empty. When taking a look at the logs, it was saying that on line 121 in AssetsAnnotationProcessor was crashing the program. The error comes from the list function that is called, apparently, it is unable to list all the files in assets/sound directory. The full Compilation report is attached.
[BuildFailLog.txt](https://github.com/Anuken/Mindustry/files/3710667/BuildFailLog.txt)
[Pastebin](https://pastebin.com/dGu8y0sp)

**Steps to reproduce**: Clone the git repository, ``cd`` into the cloned directory. Run ``gradlew desktop:dist`` or ``gradlew desktop:run``

**Comment by DE3000** [comment]
I have the same issue. Do you have a space/(non standard characters) in the path to your local repo?

Basically with my setup the space is being encoded as %20 which is great for Web resources but not for a filesystem.

**Comment by TsarF** [comment]
@DE3000 
> I have the same issue. Do you have a space/(non standard characters) in the path to your local repo?
> Basically with my setup the space is being encoded as %20 which is great for Web resources but not for a filesystem.

Yes, as a matter of fact, I do, but it does not work even if I clone the whole repo to a spaceless directory.

**Comment by Anuken** [comment]
Show me the log that appears when all the directories that Mindustry are in do not have a space.

**Comment by TsarF** [comment]
@Anuken Ah yes, my bad when I said that I was trying to build in a directory with no spaces, I did not notice one of the top directories had one. All good now.
