### ISSUE TITLE
The IA is bugged

### ISSUE THREAD

**Issue by Eliviastoregame** [Anuken/Mindustry#8073]
The IA on the personalised Games Dosen't build anything and I've tried evrything to fix it but its not doing anything.

**Comment by matkoniecz** [comment]
> Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE
