### ISSUE TITLE
High Tier tanks dealing damage not based on unit damage.

### ISSUE THREAD

**Issue by Plazma909** [Anuken/Mindustry#8075]
Steam version, PC

Build 140.4

The high tier tanks that are able to damage and destroy buildings by rolling into or over them will still deal damage to buildings even when unit damage is set to 0.

I was running some experiments with AI when I decided to control a _Conquer_.  The player faction's unit damage was set to 0, and I controlled my tank when, to my surprise, one of the cores I ran into turned into my own. (Core capture was on, player building health was maxed out.

No mods were used.

[Save File.zip](https://github.com/Anuken/Mindustry/files/10265527/Save.File.zip)

The above save is in a separate sandbox world where unit damage is set to 0. The bug was replicated there and can still be.

The game did not crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Garen7** [comment]
Hey just a heads up fire damage can still cause damage after that change but you can disable fires in the map rules
