### ISSUE TITLE
Hello, after the update, when I left to mine the kinetic alloy for the night in the morning, the soybean base was destroyed, but before the update, I captured the crash of 078 and now it shows in the technology tree that I captured the sector, but I can’t get to it. help solve the problem if possible. thank you in advance.

### ISSUE THREAD

**Issue by lyelik237** [Anuken/Mindustry#8080]
**Platform**: `Android 29`

**Build**: `release build 140.4`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by lyelik237** [comment]
Hello, after the update, when I left to mine the kinetic alloy for the night in the morning, the soybean base was destroyed, but before the update, I captured the crash of 078 and now it shows in the technology tree that I captured the sector, but I can’t get to it. help solve the problem if possible. thank you in advance.

**Comment by Slotterleet** [comment]
~~I can assume your game is in Russian, and you've used google translate or similar, because it's surge alloy, not kinetic alloy, and it's Impact 0078, not crash of 078. And what the heck do you mean by "soybean base"?~~

No details about the issue provided whatsoever. The issue is pretty much invalid by this point.

**Comment by Breadyboi69** [comment]
Soybean base should be added

**Comment by LeahLuong** [comment]
HOW ARE YOU GENTLEMEN!!

ALL YOUR SOYBEAN BASE ARE BELONG TO US.

YOU ARE ON THE WAY TO DESTRUCTION.

YOU HAVE NO CHANCE TO SURVIVE MAKE YOUR TIME.

**Comment by matkoniecz** [comment]
> Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE
