### ISSUE TITLE
Invalid Character in Editor > World Processor > Cutscene

### ISSUE THREAD

**Issue by CheshireC4t** [Anuken/Mindustry#8086]
![SS22-12-25_3119](https://user-images.githubusercontent.com/49579987/209505201-017b711e-a187-4585-949b-913597f14904.png)

**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam Build 140.4

**Issue**: *Explain your issue in detail.*
There is an invalid character in the default value of the "Cutscene" option in the "World Processor" (For the "speed" setting).

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Open Editor
Click ESC and select Edit In-Game
Place a World Processor
Open World Processor and add a "Cutscene"
Take note that the speed is " 0.06" (There's a space at the beginning of the number)
(Required) Before exiting the menu, change ONLY the speed number "6" to "8", so it reads " 0.08"
Exit out of the World Processor, then go back into it again.
The value of the Cutscene is now "_0.08", which fails to work in the game due to the invalid character.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
No save file, this happens in the editor. If you realllllyyyyyyyyyy need a save file, let me know. It's really easy to reproduce this bug.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
None.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by traincrisis** [comment]
yes this bug works im reproduced it
