### ISSUE TITLE
Modding Guide

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#809]
Modding, even only with JSON, is a complex subject, and I don't have enough time myself to write many guides. Help would be appreciated.

*[Link to modding guide file on wiki](https://github.com/MindustryGame/wiki/blob/master/docs/modding.md)*

- [ ] Explain what types of content there are
- [ ] Explain how you can use existing blocks as an example, like in [Blocks.java](https://github.com/Anuken/Mindustry/tree/master/core/src/io/anuke/mindustry/content)
- [ ] Explain how types are selected and how you can view the class file of a type
- [ ] Auto-generate documentation on the wiki
  - [ ] Each block/bullet 'type' should be its own page, with a list of properties generated from javadoc comments and a top-level class comment explaining what the type *is*
- [ ] Explain how to do more complex things like custom bullet types
- [ ] Create more example mod content to show various features
- [ ] Explain how block variants and such work
- [ ] Explain that standard game content can be replaced, while inheriting properties of the old content. Type cannot be changed, however.

**Comment by TsarF** [comment]
I can help, I myself have read over a lot of your code, and I somewhat understand where things are.

**Comment by Naxos84** [comment]
i really like to try to help with this issue. But before I have to understand the game better and how everything works.

is there a way to get in contact with you (maybe Discord) so that you could give me a good starting point?

**Comment by Anuken** [comment]
Discord is the best way to contact me, yes.

**Comment by Anuken** [comment]
Currently being worked on by [simon](https://github.com/SimonWoodburyForget/mindustry-modding). Closing to prevent confusion.

**Comment by valtsu41** [comment]
Is there still no auto-generation?

**Comment by Anuken** [comment]
I don't think so.

**Comment by wolfy9011** [comment]
e
