### ISSUE TITLE
Canʼt build anything on ancient caldera map when planet is set to Erekir

### ISSUE THREAD

**Issue by traincrisis** [Anuken/Mindustry#8091]
Platform: Linux

Build: Build 140.4

Issue:  On the map Ancient Caldera there is an bug, when you will set the planet to the Erekir, it will type "Unit cant build", and when waves are spawned the enemy units destroyed instantly.

Steps to reproduce: Create a new singleplayer game and select map ancient caldera, then in rules select planet erekir. then you will see text "Unit canʼt build"

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
Is this even a bug? Ancient Caldera isn't an Erekir map, it won't work with Erekir

It has a Nucleus core. Nucleus is a Serpulo block, and the Gamma can't spawn on Erekir, and nor can any of the enemy units, because if you switch to Erekir, all Serpulo units will just die when spawned.

**Comment by traincrisis** [comment]
> Is this even a bug? Ancient Caldera isn't an Erekir map, it won't work with Erekir
> 
> It has a Nucleus core. Nucleus is a Serpulo block, and the Gamma can't spawn on Erekir, and nor can any of the enemy units, because if you switch to Erekir, all Serpulo units will just die when spawned.

No, ancient caldera has shard core

**Comment by Bottinator22** [comment]
Still, it's not an Erekir map, and putting it on Erekir stops it from working correctly

Even if the units didn't die, it would be impossible anyway as you can't place anything

**Comment by Breadyboi69** [comment]
You can't call something that works fine a bug when you mess with the settings.
