### ISSUE TITLE
"Jump always" hides its variables but must not have

### ISSUE THREAD

**Issue by VladisS-Vostok2000** [Anuken/Mindustry#8093]
**Platform**: Android

**Build**: 140.4

**Issue**:  "jump always" hides its variables instead deconstructing it. It is very annoin see these variables in explorer.

**Steps to reproduce*:
1. open processor visual editor
2. adding "jump" command
3. input any names in fields
4. collapse "jump" to "always"
5. close processor editor
6. open processor editor
7. open processor variables explorer

**Save file**: [satisfied?](https://1drv.ms/u/s!AolqNCPP7Zv0rUHnRFH9Ke087ZO4)

---

- [ X ] **I have updated to the latest release
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
Did you even understand what this operator does? It jumps to an another operator under a certain condition. And `jump always` has no condition, it JUST JUMPS.
