### ISSUE TITLE
How to make flag be true when objective ends in editor? (Question, written as bug because cant use discord)

### ISSUE THREAD

**Issue by traincrisis** [Anuken/Mindustry#8094]
**Platform**: *Linux*

**Build**: *build 140.4*

**Question**: *I want to make when an objective finishes, it sets flag for world processors, because world processor must create explosions when atomic bomb timer will finish.*

**Steps to reproduce**: *Impossible to reproduce, because its a question. questions cannot be reproduced.*

**Link(s) to mod(s) used**: *Fading revelations*

**Save file**: *This is question, questions cannot be saved into file..*

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
There’s also a subreddit
