### ISSUE TITLE
[Steam] minor issue: "Roboticist" achievement affected by addition of Erekir units in 7.0

### ISSUE THREAD

**Issue by Stone-Dog-Millionaire** [Anuken/Mindustry#8095]
**Platform**: Steam | Windows 11

**Build**: steam build 140.4

**Issue**: The "Roboticist" achievement is for building "every unit" and the counter is x / 30.  However, with 7.0, there are more than 30 units in the game, if you count both Serpulo and Erekir types.  I had not built every type of unit on Serpulo (only about 20-ish) when I started playing the Erekir campaign.  The new units count toward the achievement, so now I have achieved it by producing 30 types of units total, the sum of both planets, even though I haven't produced all of the available ones on either planet.

I figure either the text of the achievement might be changed to say "Build _30 types_ of unit." in order to match the current functionality, or, probably better, it could say "Build every type of unit _on Serpulo_." and Erekir units would have to be disabled from counting toward it.  This would match nicely with the current icon, since it shows only Serpulo units.  Perhaps in that case another achievement could be added down the line, the same thing but for only Erekir units.

Obviously this is very minor and doesn't cause any practical problems, so I'm not much worried about it.  I would like to add that I am having an incredible amount of fun playing the Erekir campaign.  It's challenging, the graphics are beautiful, the map design is great, the gameplay feels balanced.  I feel like I got the sequel to an already great game for free—Merry Christmas to me.  I just wanted my little nitpicks to be cast in that light; it's only because I love this game that I am in here noticing a couple minor details to complain about.

**Steps to reproduce**: Play both Serpulo and Erekir campaigns, and build 30 types of unit, using some from each planet.

**Link(s) to mod(s) used**: No mods used.

**Save file**: [2022_12_29_mindustrysave_bugreport_roboticistachievement.zip](https://github.com/Anuken/Mindustry/files/10320964/2022_12_29_mindustrysave_bugreport_roboticistachievement.zip)

**(Crash) logs**: No crash.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
...there's also the naval support branch, which means Serpulo has 35 unit types

**Comment by Anuken** [comment]
Fixed.
