### ISSUE TITLE
Some players not being able to connect to a set of servers.

### ISSUE THREAD

**Issue by Xasmedy** [Anuken/Mindustry#8102]
I'm the `mindustry.ddns.net` server manager, and a lot of players report to me that they can't connect to our servers while other players can. Unfortunately I have never had the problems on my devices (Linux 64 / Android) and can't debug. For this reason I'm going to use the help of a player that had the problem.

**Platform**: Windows 10 x64 and Android

**Build**: 140.4

**Issue**: Players can't find servers (on the public list) or connect to them by inserting the address directly, they are just welcomed by a `"Timed out"` message, even if other players can connect. But this doesn't apply to all servers, since with some, the player has no problems.
It's not a network problem since the players having the problem can issue a ping and get a reply (and get the right IP from the dns).
To be sure I checked with a plugin-less server and there's the same problem.
Then I decided to test the version: the player can connect to v6 (126.2) just fine, but can't on v7 (140.4).  

**Steps to reproduce**: I have no clue, as said I can't test it on my devices. And what makes it harder to debug is that the current player that reported me the issue said that he could connect just fine yesterday but today he can't. (I verified it with logs)

**Link(s) to mod(s) used**: None

**Save file**: Not an in-game issue, since the player can't even open a connection with the server. 

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
Check if all UDP/TCP ports of the corresponding server are open.
The server is open but not showing up due to network issues.

**Comment by Xasmedy** [comment]
> Check if all UDP/TCP ports of the corresponding server are open.
> The server is open but not showing up due to network issues.

As I mentioned, other players can connect fine, including myself, and if it was a ports problem, the problem would occur to all players.

**Comment by Kieaer** [comment]
You must open the same udp/tcp port in v7 servers.
This game uses a mix of UDP and TCP.
If either of port is not open, you may not see a list of servers, or you may have connect to the server, but you may not see players, or you may not be able to synchronize.

**Comment by Xasmedy** [comment]
> You must open the same udp/tcp port in v7 servers.

**They are.**

Now the player that had problems can connect with mobile data but not via wifi/router. It's either mindustry or he has some messed up windows settings (he can reach the server via console but not via mindustry).

**Comment by Anuken** [comment]
I'm not sure what you want me to do about this. There's almost no information here and it doesn't even seem consistent on the player's end. Sounds like some network issue.
