### ISSUE TITLE
Map and wave state are not saved atomically

### ISSUE THREAD

**Issue by chrysn** [Anuken/Mindustry#8103]
There appears to be some time between when autosaves store which wave a map is in, and when they store the state of that map. A situation I've observed is the following (on Android, with Mindustry from fdroid, "fdroid build 140.1" as per start screen):

* On Nuclear Production Complex, the last wave comes in. A flying guardian, was not prepared. I take it down in the last moment, while it takes down the salvaged derelict Thorium plant, along with all buildings around it. Close call.
* I'm glad, take a screenshot of "sector captured", the damage that has been done to my base and the satisfying smudge of a downed guardian, and send the device to suspend.
* The device powers off, as not only was I on my last turrets, but also my last percent of battery.
* Later, I power it back on, and resume on that map. It's showing some time (1:45 maybe) into the last wave, and all the damage of before is there.
* I rush to rebuild everything that's been lost, and complete it just in time for the wave to come. It's the flying guardian again. Fortunately, this time my ground fortifications west of the drop zone are more to its taste (maybe because I didn't rebuild the Thorium plant, it went for the thermal generators instead), and goes down there.

Sadly, given I didn't export campaign state, I can't offer an easy way to reproduce this. (Even if I had campaign exports, I have a hunch this needs a well timed shutdown).

My guess as someone unfamiliar with the code base is that the saves of the map state (buildings, unit positions) are done without atomic coupling to the saves of the campaign state (which wave was defended against). This odd kind of glitches could be addressed if an autosave of a campaign world were only accepted on startup if there were an accompanying save of the campaign state (or whatever it is the waves are stored in), which would then require that the old map save is kept around until the campaign state is flushed to "disk".

Severity-wise, this is probably all not too bad (quite honestly, if saves as I suggest had been implemented, I'd have been thrown back to a minute or so before the last wave came, and had I made a mistake in what I still had to prepare, things might have gone badly for me), but it might also be a good opportunity to look into what goes wrong when saves are interrupted by a device crash or shutdown, in case another player can't recover well.

(And, by the way, Big Thank You for developing this game, it is awesome!)

**Comment by Anuken** [comment]
These are what I would consider "extremely abnormal conditions", and while somewhat annoying, I don't think it's worth the effort to implement and verify such syncing of wave state with actual saves. Don't let your device die on you.

**Comment by chrysn** [comment]
Thanks for responding -- it's a fine resolution for me, my priority was ensuring it is known.

("Don't let your device die on you" is hard though -- "ah, 15%, I won't keep playing for much longer anyway" never turned out as anticipated :-) )
