### ISSUE TITLE
Serious bug: Clients and server crashes

### ISSUE THREAD

**Issue by romanin-rf** [Anuken/Mindustry#8104]
**Platform**: *Windows Client (offical)/Ubuntu Server (offical)*

**Build**: *[7.0 Build 140.4](https://github.com/Anuken/Mindustry/releases/tag/v140.4)*

**Issue**: *I decided to check the operation of this bug and as it turned out the problem either came back or went nowhere. Result of this bug: crash of all players connected to the server and the server itself.*

**Steps to reproduce**: *[Here](https://github.com/Anuken/Mindustry/pull/8089)*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *I run a clean server in sandbox mode on the Maze map.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
- *Client (Windows)*: [crash_logs.txt](https://github.com/Anuken/Mindustry/files/10325456/crash_logs.txt)
- *Server (Ubuntu)*: [logs_0.txt](https://github.com/Anuken/Mindustry/files/10325472/logs_0.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

---

This problem has been shouted about for a long time:
- [Pull #8089](https://github.com/Anuken/Mindustry/pull/8089)
- [Issues #8098](https://github.com/Anuken/Mindustry/issues/8098)
- [Issues #8092](https://github.com/Anuken/Mindustry/issues/8092)

**Comment by Anuken** [comment]
fixed
