### ISSUE TITLE
Is it possible to speed up Mods loading process?

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8105]
**Platform**: Linux Server

**Build**: v140.4

**Issue**: Sorry, but how long do I have to wait for one plugin to load? and i'm not kidding I have a plugin that weighs 40.9 megabytes, but the server is trying to analyze, as I understand it, all folders for the presence of plugins, is it possible to remove this? or somehow speed it up a bit

![image](https://user-images.githubusercontent.com/91948148/210113845-c77f94d5-ef75-4f06-a87e-f1b4ad6b546e.png)

**Steps to reproduce**: Take a plugin weighing 40.9 megabytes and throw it on the server (loading on a 32-core processor, 59.7 GiB RAM, 3 TiB NVMe without debuggers and VisualVM took me 25 seconds)

**Link(s) to mod(s) used**: Private mods with scala runtime

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SSTentacleSS** [comment]
Well, now this is just funny
![image](https://user-images.githubusercontent.com/91948148/210114531-c64b8eed-4c28-497a-9c21-36238ab373e4.png)

**Comment by SSTentacleSS** [comment]
It would be beneficial to scan for dependency plugins that are described in plugin.json instead of manually iterating through huge amounts of data

**Comment by SSTentacleSS** [comment]
Stopped at
![image](https://user-images.githubusercontent.com/91948148/210114688-817c2f2a-292c-4605-9594-410490c607c0.png)
With this plugin
![image](https://user-images.githubusercontent.com/91948148/210114739-ce578ac3-28e7-410d-bfa5-bfcaf20e4a02.png)

**Comment by Kieaer** [comment]
What's plugin name?
May be it caused by Plugin. Even my 38MB plugin loads in under 3 seconds.

**Comment by SSTentacleSS** [comment]
> Do you have the plugin source? May be it caused by Plugin. Even my 38MB plugin loads in under 3 seconds.

I am developing this plugin, the sources are all mine, the problem is that this script, due to the complexity of the structure, Jar has to go through 800 thousand directories in a cycle 100 times, which makes it simply unbearable, you can simply remove the dependency search by plugin.json, specifying the necessary dependencies manually, in json

and I think with your plugin the same problem with download speed caused by the search for dependencies
VisualVM clearly showed that the plugin takes only 40 milliseconds of CPU time

**Comment by Kieaer** [comment]
VisualVM seems to have omitted some elements.
The corresponding plugin/mod source is required to determine the cause.

**Comment by SSTentacleSS** [comment]
@Kieaer
I analyzed the byte code in more detail - my conclusion is that ZipFi needs to be redone, since ZipFi in the current version, I assume it analyzes all folders in the jar file, which is very bad for performance, I think it might make sense to limit the ZipFi scan or do all the calculations sub-folders "lazy"
thank you for your advice!

![image](https://user-images.githubusercontent.com/91948148/210185977-4d0508a0-2dbc-4af4-862d-094b62104383.png)

**Comment by SSTentacleSS** [comment]
(I also optimized the size of the plugin to 12 megabytes, so now it loads in 2-3 seconds)

**Comment by SSTentacleSS** [comment]
@Kieaer @Anuken [#136](https://github.com/Anuken/Arc/issues/136)

**Comment by Anuken** [comment]
For performance optimizations, make a PR.
