### ISSUE TITLE
my console doesn't work

### ISSUE THREAD

**Issue by Sasuke99o9** [Anuken/Mindustry#8110]
I have a problem with the console when I type a command in it it doesn't work then it says this
ecmaerror:referenceerror:"planets"is not defined. (console.js#1)
this is what it says when i type a command
do you know what is happening

**Comment by Slotterleet** [comment]
I'm 99.99% sure your script has errors. Also there's no such class as `planets`, maybe you want [Planets](https://github.com/anuken/mindustry/tree/v140.4/core/src/mindustry/content/Planets.java)?
