### ISSUE TITLE
Keybinding keys do not match the keyboard layout

### ISSUE THREAD

**Issue by muesli4** [Anuken/Mindustry#8111]
**Platform**: Linux (Steam)

**Build**: 140.4

**Issue**: Keybinding keys do not match the keyboard layout.  The name displayed for a key is wrong in the current keyboard layout.  I do not know whether it affects the use of those keybindings (for some reason I cannot use _pick up item_, but that may be unrelated).  I'm using German but the issue is also present in other languages.  (Semi-related issue with Spanish keyboard layout: https://github.com/Anuken/Mindustry/issues/7919)

**Steps to reproduce**: Set keyboard language to something else and try to set keybindings.

**Save file**: Not provided as it is independent of game state.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is an ancient issue, and it will not be fixed.

**Comment by muesli4** [comment]
Is it being ancient the reason for it not being fixed or because it is fixed already (i.e. duplicate)?

**Comment by Anuken** [comment]
It's a large amount of effort and the framework was never made to support it.

**Comment by muesli4** [comment]
But is it really?  I obviously don't have the same understanding of your architecture but it should be as simple as applying a mapping somewhere.  And at least for the SDL backend that should be a piece of cake because all of these functions are provided.

For example, why not replace the `KeyCode` enum with a backend-specific instance of a class that has a method for each key, and there you can return an abstract key that implements everything you need.  This key could have a backend-specific implementation for mapping the scan codes to key codes.  If you want to match on the key you can provide a method to return the scan code.  It seems like a doable refactoring.
