### ISSUE TITLE
Possible Error w/ Bldg. Production Values

### ISSUE THREAD

**Issue by LeahLuong** [Anuken/Mindustry#8115]
**Platform**: Android

**Build**: 140.4, DL'd from itch.io recently

**Issue**: Below, in **Steps to reproduce**, you'll find a pic of 2 scrapact builds operating on just 1 cultivator. From my understanding, this shouldn't be possible but the schems are actually banking blast compound rather than running out & shutting down the reactors.

Impacts alone require 4/7 blast/sec to run; this breaks down to reqs for both 4/7 pyratite/sec & 4/7 spore/sec (i.e., 1 of ea.). A single cultivator running @ 100% eff makes 3/5 spore/sec, just 1/35 above what's needed for the spore side of the blast production. Allegedly, that 1/35 is being converted to oil, then coal, then pyratite, & finally added to the blast compound mentioned earlier. By my calc, this whole process SHOULD req 6/7 spore/sec but my experiments w/ the following builds demonstrate 3/5 is more than enough to run the impact.

My hunch is something funky is going on w/ the oil conversion numbers. Liquids in this game have always been difficult & I think the coal centrifuge may be much more efficient than its description box would lead you to believe. In any case, the numbers aren't adding up based on what's shown to players IG.

**Steps to reproduce**:

![Screenshot_20230102-150005](https://user-images.githubusercontent.com/91638992/210301558-5f2c210b-08b0-4dea-83cd-61fb5773d2ae.png)

Micro processors are unnecessary for the builds but greatly expedite what is, even w/ logic, a slow startup process. i recommend using 1 to simply keep the reactor deactivated until the centrifuge fills w/ oil. W/out logic, the builds do eventually start spinning & banking blast. An alternative is to wait on placing the reactor until the centrifuge is oiled up.

Once the reactors start producing, the builds can be disconnected from power sources & they should remain indefinitely self-sufficient w/ material inputs, as they are in the pic above.

**Link(s) to mod(s) used**: N/A

**Save file**: Please don't reap my soul. You can build the schem yourself or maybe I can upload the schem if you let me know how.

**(Crash) logs**: N/A

---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I haven't marked both of the preceding boxes but understand the 1st box is somewhat silly considering info given earlier in this form.**

**Comment by Anuken** [comment]
> You can build the schem yourself

No.

**Comment by LeahLuong** [comment]
@Anuken Can you @ least let me know how to upload a schem file here?? It might be helpful to supply that info in the reporting form for others as well. This is why I pointed to my ignorance of this info in the OP, right after the statement of mine you quoted (the "or").

I'm pretty sure something's wrong w/ bldg. production values & thought you might be better positioned to track it down than I. You seem to care about your game & correcting mistakes you've made in other issues but dismiss this 1 w/ a 1-word denial. Care to reconsider??

**Comment by Anuken** [comment]
This is a rather large and complicated schematic, and unless you can specify which specific block is under/over-producing I'd rather not spend hours trying to figure out what's wrong or what your assumptions are. In my experience this is frequently user error.

I close issues without saves because, as the template says, **do not open issues unless you have a save file.** It's part of the instructions. Saves should be exported from the in-game menu, zipped and dragged into github.

**Comment by LeahLuong** [comment]
@Anuken I've edited the OP to include a .zip. There, you should find my final, compacted version of the scrapacts depicted previously as well as a separator version to its left functioning after startup & detachment from a power source.

Strangely, the disassembler version died out after a time for lack of blast & needed a restart by connection to a power source; this hadn't happened before during fairly lengthy tests (allowed to run for hours while working on other designs nearby). After restart, the disassembler version started banking blast.

Observing the schems during startup, I think it may be possible that oil is somehow being duped because the spore press & coal centrifuge are next to each other; they seem to fill up simultaneously & @ nearly the same rate although the press has 6x the liquid capacity as the centrifuge. IDK how these schems can function as they do but the math seems to indicate 2 cultivators should be the min req to keep ea. running. You should be able to dupe the schems, plunk them them down elsewhere, & give them a temp power source to observe their startup process.

**Comment by LeahLuong** [comment]
@Anuken It seems these schems work as expected on higher FPS than I built them in; as in, they don't. Both versions are unable to generate blast faster than they burn it @ 60 FPS. I'll try to keep this in mind if I bring this sort of issue in the future.
