### ISSUE TITLE
No sound on bluetooth headphones

### ISSUE THREAD

**Issue by Cyrex242** [Anuken/Mindustry#8116]
**Platform**: `Android 24`

**Build**: `release build 140.4`

**Issue**: The game doesn't reproduce sounds or music when my bluetooth headphones are connected, but they work with wired headphones

**Steps to reproduce**: I just connect the device and open the game, i can listen to other apps but mindustry seems muted, however the phone's speaker and wired headphones work

**Link(s) to mod(s) used**: None

**Save file**: 
[Mindustry saves.zip](https://github.com/Anuken/Mindustry/files/10334911/Mindustry.saves.zip)

> 

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
[X]

**Comment by Anuken** [comment]
Not interested in fixing.

**Comment by SunkyMP3G** [comment]
This means your bluetooth headphones are broken

**Comment by Otamamori917** [comment]
This is hilarious 
💀💀
