### ISSUE TITLE
Sound does not function

### ISSUE THREAD

**Issue by novellus** [Anuken/Mindustry#8120]
**Platform**: *Linux Mint 21.1 (Vera)*

**Build**: *140.4*

**Issue**: *Sound does not function, either in the main menu, or after launching a campaign. There is no sound anywhere.*

**Steps to reproduce**: *Install Linux Mint 21.1 (Vera). Install Mindustry. Launch game to main menu. Observe audio.*

**Link(s) to mod(s) used**: *No Mods.*

**Save file**: *No game saved.*

**(Crash) logs**: *N/A*

**Similar Issues**: *A similar issue was reported here https://github.com/Anuken/Mindustry/issues/6349 for users of Arch Linux. However the reported workaround does not function in Linux Mint (ie: install ```pulseaudio-alsa```).*

**Notes**: *Oddly, the pulseaudio volume control (PAVU) reports that Mindustry is producing sound (via decibel meter) both in main menu and after launching a campaign, and shows obvious sound-spikes when firing main weapon in a campaign. However, there is no audible sound. Sound volume is maxed everywhere (game, system), and for comparison, other programs reporting similar sound decibel levels are very loud.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce this issue on Ubuntu, sounds system-specific.
