### ISSUE TITLE
malformd input

### ISSUE THREAD

**Issue by Mahzy88** [Anuken/Mindustry#8123]
**Android**

**140.4**
**malformd input. i have to use vpn to acces network because normally i cant connect to multiplayer part from iran but the game says malformd input at ... please let me know which thing of vpn make that happend so i can ask my vpn provider to fix that**

**using vpn**
  **
[ game save for report.zip](https://github.com/Anuken/Mindustry/files/10362709/game.save.for.report.zip)
**: *The (zipped) save file you were playing on when 
**
![Screenshot_2023-01-06-23-16-17-705_io anuke mindustry](https://user-images.githubusercontent.com/104689886/211089917-664696d1-2711-41f2-8f7f-5e817a65be7f.jpg)
**

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
-   [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![Screenshot_2023-01-06-23-16-20-381_io anuke mindustry](https://user-images.githubusercontent.com/104689886/211089855-feec9e17-c0c6-437c-bf72-c03a48d7e9a4.jpg)

**Comment by Anuken** [comment]
Can't fix, your VPN is screwing up packets somehow and there is nowhere near enough info here to figure out why.
