### ISSUE TITLE
(old bug bump)

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8126]
https://github.com/Anuken/Mindustry/issues/5198

**Comment by Anuken** [comment]
Best I can do is put it in a synchronized block instead, but I don't use Windows so I can't test this well.

**Comment by Kieaer** [comment]
@Anuken So, is the method proposed by way-zer unusable?

**Comment by Anuken** [comment]
I kind of did what was proposed - that is, I made the localhost check occur on the ping thread.
