### ISSUE TITLE
SMoke of Anarchy is not avaible from globallist

### ISSUE THREAD

**Issue by MaxSMokeSkaarj** [Anuken/Mindustry#8141]
**Platform**: *andoid/linux* ("All" is NOT a platform!)

**Build**: *140.4*

**Issue**: *SMoke of Anarchy is not avaible from globallist, but avaible from my home internet, i recheck a server settings, and everyone is wornikg propetly*

**Steps to reproduce**: *nothing, i just enter a multiplayer, and catch that error*

**Link(s) to mod(s) used**: *no mods yet*

**Save file**: *no reason bc not ingame issue*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *haven't*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/211451455-747e9a28-dcf4-4a2e-a5f1-26cdeb4cd03e.png)

You didn't type the address correctly. Both are in the same set of quotes.

**Comment by MaxSMokeSkaarj** [comment]
> ![image](https://user-images.githubusercontent.com/10100000/211451455-747e9a28-dcf4-4a2e-a5f1-26cdeb4cd03e.png)
> 
> You didn't type the address correctly. Both are in the same set of quotes.

everythings right, SMokeOfAnarchy.ru.

**Comment by MaxSMokeSkaarj** [comment]
how to delete issue? :)
