### ISSUE TITLE
*Some* java mod icons only show in browser, not in mod list

### ISSUE THREAD

**Issue by stacktrace-error** [Anuken/Mindustry#8148]
**Platform**: windös

**Build**: BE 23633/23711

**Issue**: the the
![Screenshot 2023-01-10 203537](https://user-images.githubusercontent.com/89076920/211645207-bc65007e-41bb-495e-b718-81c27173c9c7.png)

reproduced:
![Screenshot 2023-01-10 203714](https://user-images.githubusercontent.com/89076920/211645582-ce993b80-e5f4-4c96-bd75-9da2f50ae12f.png)
![Screenshot 2023-01-10 203738](https://user-images.githubusercontent.com/89076920/211645587-4048a87a-99b1-4cb6-b8f2-835c327b56c9.png)

~~he has an icon.png in every folder of his mod now, even the code ones~~
![Screenshot 2023-01-10 210257](https://user-images.githubusercontent.com/89076920/211650790-a3ec6f34-0ed3-4456-8e21-f1ee9998d5b8.png)
![Screenshot 2023-01-10 205955](https://user-images.githubusercontent.com/89076920/211650286-755efc75-3c8f-40ef-b6f9-83cec528157a.png)

**Steps to reproduce**: 
- look at java mod on the browser
- download
- look at java mod in mod list

**Link(s) to mod(s) used**: https://github.com/ThomasThings/xenacia

**Save file**: a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **None of the above.**

**Comment by stacktrace-error** [comment]
death

**Comment by stacktrace-error** [comment]
kill me

**Comment by stacktrace-error** [comment]
evidence properly provided 
3rd open because unsure until now

**Comment by Anuken** [comment]
The mod is not packaged correctly. Look in the jar, there's no icon.png in it. The mod browser grabs it from the repo, not the jar.
