### ISSUE TITLE
'jitpack' might be down, or the dependency no longer exists. Maybe try a different version.

### ISSUE THREAD

**Issue by LionelBergen** [Anuken/Mindustry#815]
**Issue**:
Build failed due to the following link leading to not working:
https://jitpack.io/club/minnced/discord-rpc-release/v3.4.0/discord-rpc-release-v3.4.0.pom

Note:
A dependencies.gradle file would make this a lot easier to resolve/debug.
Is discord-rpc really required?

**Steps to reproduce**: 
Try cloning the project and following the build steps for desktop

**Comment by Anuken** [comment]
JITPack says:
> There seems to be an issue connecting to our servers. Please try again in a few minutes.

In the event that this error message is not a mistake, I would assume you just need to wait for the problem to resolve itself. This has happened before. If it turns out to be a long-term issue, you can re-open this.

> A dependencies.gradle file would make this a lot easier to resolve/debug.  

Nearly the dependencies are already listed in `build.gradle`, so I don't see why finding it should be difficult.
 
> Is discord-rpc really required?  

Yes.

**Comment by LionelBergen** [comment]
using a dependencies.gradle file is easier since it keeps the dependencies separate from everything else.
The fix (switching from version 2.0.2 to 2.0.1) works, are there features you need from 2.0.2?

**Comment by LionelBergen** [comment]
> I would assume you just need to wait for the problem to resolve itself. This has happened before
That sounds like a more serious issue than a version typo!
Have you considered using reliable download source? Is this the only dependency that has caused issue?

**Comment by Anuken** [comment]
> are there features you need from 2.0.2?

There was a fix related to encoding that was added in the late versions, but looking at the library, it's probably safe to assume that 2.0.1 also has that fix, and should work for my purposes.

> Have you considered using reliable download source? Is this the only dependency that has caused issue?

No, other dependency sources (most notably the one for packr) randomly go offline - with much higher frequency, in fact. I don't believe that there are any other services that do what JITPack does with the same set of features.
