### ISSUE TITLE
UnitRadar always return @unit.

### ISSUE THREAD

**Issue by RICCJ** [Anuken/Mindustry#8152]
**Platform**: Android

**Build**: v140.4

**Issue**: UnitRadar always return @unit.

**Steps to reproduce**: 
logic:
![IMG_20230111_174949](https://user-images.githubusercontent.com/85016284/211775004-9cc14d5a-fe95-4dfb-9596-a123b51e0064.jpg)
result:
![IMG_20230111_174928](https://user-images.githubusercontent.com/85016284/211775067-3fd1d6b6-99bf-4308-bd5e-40637d4442ff.jpg)

**Link(s) to mod(s) used**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Save not provided.
