### ISSUE TITLE
控制台输入框问题

### ISSUE THREAD

**Issue by twhice** [Anuken/Mindustry#8155]
Linux 最新版

在游戏设置中启用"启用控制台"选项后

打开控制台会出现一个输入框

如果不回车来消除输入框,并再次按f8(默认绑定的按键)来隐藏控制台

会导致所有控制按键(除了f8)全部失效

用鼠标点击任意UI或者打开控制台并回车消除输入框即可恢复

**Comment by Anuken** [comment]
I don't accept reports in languages other than English, and you have not filled in the template.
