### ISSUE TITLE
keys bind on console input box after closed console

### ISSUE THREAD

**Issue by twhice** [Anuken/Mindustry#8156]
**Platform**: Linux
**Build**: 140.4

**Issue**: *i can't control the game by using  keyboard after i close the console*

**Steps to reproduce**: open the console and close it (double press f8)

**Link(s) to mod(s) used**: None

**Save file**: any save that enabled console

**(Crash) logs**: None

(i do not know whether the grammar in this report is correct or not)

open the console by type f8 and do nothing

then type f8 again to close the console

control buttons like WASD FGH ... will not work until click ui by using mouse or  press enter to close the input line before close
 the console

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
not a bug, click on the world again
