### ISSUE TITLE
campagne erekir

### ISSUE THREAD

**Issue by Kokoutsou** [Anuken/Mindustry#8157]
Lors de la campagne d'erekir, lorsque j'arrive au niveau de ravine, je ne peux décoller car il y a marqué 0 tungstène/400. Or j'ai bien les 400, et je n'en ai encore moins 0.

Je pense qu'il y a un petit problème de compteur

Bon courage,

**Platform**: `Android 31`

**Build**: `release build 140.4`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by JojoFR1** [comment]
Tu dois aller sur un autre secteur avec du tungstène, retourner sur la carte de la planète et aller sur le nouveau secteur.

La prochaine fois essaye également d'écrire en anglais.

For Anuke: it's not a bug, he just don't know how to launch from another sector.
