### ISSUE TITLE
v141 | Erekir buildings on Serpulo after playing on Erekir 

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8163]
**Platform**: Windows 10

**Build**: v141
**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: after playing on erekir map on servers all next serpulo maps (the bug will not disappear when join to another server) was with erekir buildings (only client side) 

![image](https://user-images.githubusercontent.com/90514725/212148768-5e3c0848-932b-403d-9876-f8ceef1b977a.png)

**Link(s) to mod(s) used**: vanilla
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save provided, cannot reproduce issue.

**Comment by Agzam-Ar** [comment]
Hm.. now im too cannot reproduce bug. But i don't think that save can help because:
> The bug will not disappear when join to another server

Maybe this bug was create because you add new rule? Or bug was reproduce only on changing version from 140.4 to 141

**Comment by Agzam-Ar** [comment]
In discor Trinari had the same bug
![image](https://user-images.githubusercontent.com/90514725/212349978-01e86e80-2a07-4b0b-94e1-3b6c53808bac.png)

**Comment by Anuken** [comment]
Unless the person specifies the game version they were using when they entered that map, it's not very helpful.
