### ISSUE TITLE
Cannot complete sector lake on erekir due to map bug

### ISSUE THREAD

**Issue by FrostStormwind** [Anuken/Mindustry#8164]
**Platform**: Windows

**Build**: Steam Build 141

**Issue**: Map tile named lake on Erekir does not generate the full map and cannot be completed

![image](https://user-images.githubusercontent.com/122560985/212151999-3c44bc8f-c131-41ec-9015-497e59f0a5b9.png)

**Steps to reproduce**: Launched lake from the campaign menu, after unlocking tech upgrades from the tech screen prior to launching lake. Not sure if reproducible but added save file 

**Link(s) to mod(s) used**: No mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash encountered

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

[sector-erekir-41.zip](https://github.com/Anuken/Mindustry/files/10405060/sector-erekir-41.zip)

**Comment by Anuken** [comment]
Can't reproduce, but suspected cause has been dealt with.
