### ISSUE TITLE
Wrong many text colors

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8166]
**Platform**: Windows 11

**Build**: Build 141

**Issue**: Same title

**Steps to reproduce**: Join any multiplayer server.
I tried restart game but still wrong colors.

**Link(s) to mod(s) used**: No mods.

**Save file**: [save.txt](https://github.com/Anuken/Mindustry/files/10404897/save.txt)

**(Crash) logs**: No crash bug.

![1](https://user-images.githubusercontent.com/44261958/212164660-f73f4b9d-155e-4cfc-918e-0f648c20efb9.png)
![2](https://user-images.githubusercontent.com/44261958/212164681-8a4f187f-36c4-4bd1-8351-c3cf64188c75.png)
<br><br><br>
![image](https://user-images.githubusercontent.com/44261958/212165307-4c0ebf4a-c759-4796-9a4d-a9f46110e785.png)
It's orignal colors.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **_I have searched the closed and open issues to make sure that this problem has not already been reported._**

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/212165471-d2154a5d-ca63-46b1-9b36-d268e1523090.png)


Cannot reproduce issue, likely same cause as previously reported issue.
