### ISSUE TITLE
Spanish bundle issue

### ISSUE THREAD

**Issue by Vect0r0** [Anuken/Mindustry#8169]
**Platform**: Windows

**Build**: Build 141.1

**Issue**: All the special characters of the Spanish bundle are missing ( ´ ¡ ¿ ñ ) 

**Steps to reproduce**: Change your game language to Spanish and watch
![image](https://user-images.githubusercontent.com/106137239/212226118-cea39541-6d5b-42e2-8747-a9d36c13b865.png)
(Campaña)

![image](https://user-images.githubusercontent.com/106137239/212226207-d85b613c-ae93-4204-af0e-2bb593655b57.png)
(Récord de puntuación)

![image](https://user-images.githubusercontent.com/106137239/212227369-287d3390-9b02-4d2e-958b-ef227b1cf05b.png)

  ( https://github.com/Anuken/Mindustry/commit/33a57b11f6b41f8c4eb55c0012ef8b6189f2e264   )

**Link(s) to mod(s) used**: None

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed
