### ISSUE TITLE
The option to lunch resources from core during the game

### ISSUE THREAD

**Issue by idodoroz4** [Anuken/Mindustry#817]
**Platform**: (Android/iOS/Mac/Windows/Linux)
Android
**Build**: (The build number under the title in the main menu. Required.)
96
**Issue**: (Explain your issue in detail.)
I bumped into a situation when you can lunch your collected resources from the Core without finish the game (pressing LUNCH). 
If you put a lunch pad that is touching the core all the resources you have in the core are transfferd immediately to the lunch pad and then lunched during an active game. 
**Steps to reproduce**: (How you happened across the issue, and what you were doing at the time.)
Explained. 
![Screenshot_20191012-113840_Mindustry](https://user-images.githubusercontent.com/15835088/66698483-2ee6f800-ece7-11e9-8dd3-a5b7e598c4c6.jpg)

**Comment by Anuken** [comment]
This is intentional.

**Comment by ZkyLB** [comment]
But first of all, let's have a lunch with Anuke.
