### ISSUE TITLE
Zombie Poly

### ISSUE THREAD

**Issue by TraktorHead** [Anuken/Mindustry#8172]
I played campaing mode in my mobile version and by some reason, one of my Poly damaged and destroyed, or just I tought that. The ship was fully low, hoewer my repair point and turret wanted to heal but nothing changed. There was some smoke too what was came out of the ship and also the light blinked so fast. It destroyed fully when I quit the game and go back.

**Comment by stacktrace-error** [comment]
congrats, you removed the entire template without even reading it
