### ISSUE TITLE
v141 | Sandbox on Survival after playing in Sandbox

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8174]
**Platform**: Windows 10

**Build**: v141

**Issue**: i think this bug from this issue https://github.com/Anuken/Mindustry/issues/8163

**Steps to reproduce**: I am playing in sandbox on localhost server (server-release.jar `v141`) and than I'm join to SynapseOS server but all sandbox buildings been in build select menu, `/sync` not helping
PS: joining to others servers not helping, only client restart

![image](https://user-images.githubusercontent.com/90514725/212337558-2f941804-0532-4ef7-b910-713712483e33.png)

**Link(s) to mod(s) used**: vanilla (on client)

**Save file**:  [42.zip](https://github.com/Anuken/Mindustry/files/10412094/42.zip) (do not think that this can help)

If need i can send video with bug
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Update your game.
