### ISSUE TITLE
Serpulo and Erekir broken maps

### ISSUE THREAD

**Issue by SemGame02** [Anuken/Mindustry#8178]
**Platform**: Windows10

**Build**: 141.2

**Issue**: Map expansion and boundary setting broken entirely. Stuck in the void beyond map boundaries.

**Steps to reproduce**: I run 141 load the world and black borders. Updated to 141.2 does not fix black borders.

**Link(s) to mod(s) used**: No mods. Vanilla

**Save file**: [Saves maps.zip](https://github.com/Anuken/Mindustry/files/10417038/Saves.maps.zip)

**(Crash) logs**: No crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Updated to 141.2 does not fix black borders.

It's not supposed to. Delete the map file and load it in 141.2.

**Comment by SemGame02** [comment]
Thank you helped.

**Comment by overdramaticpanromantic** [comment]
I'm still experiencing this in 141.2.
