### ISSUE TITLE
Main menu gpu leak(?)

### ISSUE THREAD

**Issue by knightnibor** [Anuken/Mindustry#8180]
Platform: Windows

Build: Steam build 141.2

Issue: Left my game on the main menu for a couple of hours. Came back to it soaking up 90% of my gpu (geforce gtx 1660)

Replication (Dont know if its replicatible or a 1 off): Leave the game on the main menu for an extended period of time.

No mods

No save, main menu

No crash, no logs.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This could be caused by any number of things (Windows being weird, graphics drivers, ...), and unless it starts to cause real problems relating to performance, I'm not going to investigate further. The menu doesn't do anything time-dependent and I don't see what could cause this.

**Comment by Bottinator22** [comment]
Are the background ships properly cleaned up or reused?

**Comment by Anuken** [comment]
They don't exist. They're not objects. I'm just drawing N sprites at dynamic positions based on time.
