### ISSUE TITLE
Descync in multiplayer - cannot research

### ISSUE THREAD

**Issue by qcrist** [Anuken/Mindustry#8184]
**Platform**: *Windows* ("All" is NOT a platform!)

**Build**: *Steam 141.2*

**Issue**: *In multiplayer (steam multiplayer), tech tree is not properly syncing to non-host. When I research something, it shows as researched for them, but it isn't in the build menu. They cannot research anything on the tree, it always says 0 resources. If they type "/sync" it will fix it, but when the host next research another "/sync" will be required.*

**Steps to reproduce**: *New campaign on Erekir. Research first item while non-host is connected. They cannot build it even though it is researched on their tree.*

**Link(s) to mod(s) used**: *N/A*

**Save file**: *[BrokenSave.zip](https://github.com/Anuken/Mindustry/files/10421024/BrokenSave.zip)
I suspect it may not be useful, as when the save is loaded it works. its only after research that it breaks.*

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) t

o make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> They cannot research anything on the tree,

Clients shouldn't be able to even *view* the tree, only the host can control research.

**Comment by annitya** [comment]
> Clients shouldn't be able to even view the tree, only the host can control research.

Sorry for necroing the issue, but why not?

I'm new to the game and was playing with my friend who has a little experience. We were trying to decide on what to research.
The water-pump wasn't showing up and he couldn't quite fathom why. I actually ended up streaming my view of the game to him through discord. The tree being read-only for him would've been a little hiccup, but hiding the whole thing?

Sidenote: Why is the most interesting thing in the tree - *new stuff* - grayed out and kind of hard to see? I already know what I've researched. Flash the goods damnit! :P

**Comment by Anuken** [comment]
> why not?

Clients have their own research locally, which can differ from what the host has. There is also absolutely no mechanism for the server to send clients all their research info - there would need to be new systems for displaying remote item counts, an exact copy of the tech tree, and research progress / objectives achieved for every single item there. This is very far from simple to implement and sync correctly.

**Comment by annitya** [comment]
Thanks for your swift reply :)

Not sure I agree that it's a minor thing. All clients are effectively denied taking part in a major part of the game - progression. Do I remember correctly that they can't see the map either? Coming from single player, I think my friend felt a little like a second citizen. Participating in choosing the tech, and seeing what may come next is an important motivator.

Regarding the work involved I definitely take your word for it. The devil is in the details and things are always more complex than they seem. Would you be open to a PR if it was made in a sensible, maintainable way? I'm thinking something basic at first. A readonly view with no additional information.

There may also be a few other roads to Rome. 

What if local tech tree could be enabled, but all players had to share the cost? It might also help with balancing.
Does the enemies in coop-campaign scale alongside the number of players? This would probably also cause players to choose different directions and responsibilities.

**Comment by Anuken** [comment]
> All clients are effectively denied taking part in a major part of the game - progression.

That's just how the campaign is designed; you are not "doing the campaign together" so much as you are helping someone out on *their* campaign. Changing this would require significant refactoring of everything campaign-related, as the system simply operates on "your" global campaign (or doesn't operate on anything at all when you're playing with someone).

> Would you be open to a PR if it was made in a sensible, maintainable way?

That's a pretty big "if"; I myself don't know exactly how such a system would work. The current unlock system is implemented with a hack based on game rules, and there is no real precedent for sending this kind of data.

> What if local tech tree could be enabled, but all players had to share the cost?

This contaminates campaigns of multiple people, which has been tried and deemed a bad idea. If you play on someone else's campaign, yours should not be affected - they are separate.

> Does the enemies in coop-campaign scale alongside the number of players? 

No, and that doesn't make any sense. Erekir doesn't even *have* waves on most maps, and additional players don't increase your available resources. The Serpulo preset maps have fixed enemy counts.

**Comment by annitya** [comment]
I see! I'll leave it be for now then. Thank you for the game and your time :)
