### ISSUE TITLE
Ground Zero impossible

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#8188]
**Platform**: MacOS

**Build**: 141.2

**Issue**: Ground Zero has no map objectives, and so can't be completed.

**Steps to reproduce**: Launch to Ground Zero. That is it. No map objectives appear, rendering advancement impossible.

**Link(s) to mod(s) used**: Scheme Size, Time Control, & Extended UI v7. Tested without, too.

**Save file**: [sector-serpulo-15.msav.zip](https://github.com/Anuken/Mindustry/files/10430010/sector-serpulo-15.msav.zip)

**(Crash) logs**: No crash.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
This is with ALL sectors that use map limiting objectives except for The Onset, by the way. Ground Zero, Aegis, Basin, Marsh, Crossroads, Origin, etcetera.

**Comment by overdramaticpanromantic** [comment]
Like, c'mon, I just wanna play the campaign again.

**Comment by overdramaticpanromantic** [comment]
(Itch 141.2 by the way. Not steam, but also tested on steam and the same thing happened.)

**Comment by Anuken** [comment]
![image](https://user-images.githubusercontent.com/10100000/212808182-9a5f50b5-df49-4d23-8248-6ccad08bcf87.png)

Works fine on a new save for me. If a mod (or previous update) messed up your objectives, they're not going to return just by disabling the mods/updating. As the other issue says, clear your campaign data (or the specific saves) and play it again. If it still happens, it's probably your mods.

**Comment by overdramaticpanromantic** [comment]
I tried all of the above, without mods too. Still broken.

**Comment by Anuken** [comment]
Are you **sure** you deleted all game data and are actually running 141.2? If this were a simple bug I'd imagine I would be seeing more than one report about it in 141.2, since it's very obviously broken...

**Comment by overdramaticpanromantic** [comment]
Yes, I am sure. I tried deleting the entire game's data, disabling all mods, re-importing data, everything. I'm experiencing this on both my school laptop (which runs Windows 10) and my personal computer (which runs MacOS) so this is not device-exclusive.

**Comment by Anuken** [comment]
I can't reproduce anything like this on my computer (Steam version, development build) or a completely isolated Windows VM (Steam).

> re-importing data

**Re-importing** data would not fix anything. As I said above, **clear your campaign/save data** completely, and start from scratch. Or delete the specific saves. Importing anything at all would just give you the broken saves again.

**Comment by overdramaticpanromantic** [comment]
I meant re-importing my schematics, because I had to completely reset game data, which means redoing my settings as well as re-importing my schematics.

**Comment by Anuken** [comment]
So to be clear: You **clear all game data** on 141.2, launch to Ground Zero, and there are no objectives at all?

**Comment by overdramaticpanromantic** [comment]
Yes. This also happens on most Erekir sectors, with the sole exception of The Onset.

**Comment by overdramaticpanromantic** [comment]
I finally got it to work - turns out my fucking DRIVE was messing something up somehow. It's fixed now.
