### ISSUE TITLE
"allow-custom-clients" not working?

### ISSUE THREAD

**Issue by inxaneninja** [Anuken/Mindustry#819]
**Platform**: Server on linux, custom build on windows

**Build**: custom build

**Issue**: I turned on custom clients on my server, but when i try to connect with a custom build compiled on my windows machine, it disconnects me with a "Connection closed." message.

**Steps to reproduce**: Run a server, allow custom clients, make a custom client, try to connect.

**Comment by Anuken** [comment]
Build 96 is not network-compatible with master. You just can't connect to it.
