### ISSUE TITLE
Add Catalan as available language on Steam

### ISSUE THREAD

**Issue by J0anJosep** [Anuken/Mindustry#8191]
First of all, sorry, as it may not be the best place for the request. But I am not sure where I should ask for this.

Could Catalan be marked as an available language for Mindustry on the Steam platform? Some other languages are listed, but Catalan is missing.

I do not know if more languages are also missing.

Thank you anyway!

**Comment by TheGamer1002** [comment]
This is a great issue! Is Catalan in the game already, or does it need to be translated? Is it in the standalone Java version?

**Comment by Anuken** [comment]
Added.
