### ISSUE TITLE
PvP pausing bug

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8192]
**Platform**: Headless server

**Build**: Latest

**Issue**: When all cores are destroyed, the server sometimes doesn't end the game, it just pauses.

**Steps to reproduce**: Try to play on any PvP server, idk

**Link(s) to mod(s) used**: No mods

**Save file**: No save files found, sorry

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

This issue seems to be caused by this code. 
![image](https://user-images.githubusercontent.com/79508138/212945784-41072d5c-98b6-4b7b-994e-277244f8261f.png)

**Comment by Darkness6030** [comment]
Happens once in ~20-30 games

**Comment by L0615T1C5-216AC-9437** [comment]
would like to add that its been happening in CN survival and attack seemingly randomly
