### ISSUE TITLE
Issues with map editor settings

### ISSUE THREAD

**Issue by Doommenensbs** [Anuken/Mindustry#8193]
**Platform**: Android

**Build**: release build 141.2

**Issue**: the ai in the map editor doesnt attack. Like when i turn on the ai in the crux (my enemy) and turn attack mode on. Then proceed to go in attack mode. The ai doesn't build. Nor it attacks.

**Steps to reproduce**:  map editor > my map > map info > rules > turn on enemy ai > turn on attack mode > boot up a test game with the game mode attack > and then the ai does nothing

**Link(s) to mod(s) used** : 
https://github.com/eschatologue/unlimited-armament-works

**Save file**: it does it on every save file. So not needed

**Crash report**: There is no crash report

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Save file: it does it on every save file. So not needed

**No.** Saves are required.

> The ai doesn't build. Nor it attacks.

It's not supposed to do either of those things.
