### ISSUE TITLE
"Mindustry.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by lvdo** [Anuken/Mindustry#8195]
**Platform**: MacOS Ventura 13.1

**Build**: [MacOS]Mindustry.zip version 141.2

**Issue**: I can't start the latest Mindustry build on MacOS.

**Steps to reproduce**: 

1. Download **[MacOS]Mindustry.zip version 141.2**
2. Extract the zip archive (either using Finder or The Unarchiver)
3. Double click **Mindustry.app**

I get this error:
<img width="253" alt="Screenshot 2023-01-18 at 14 07 22" src="https://user-images.githubusercontent.com/3787102/213180679-7742ea6f-d92e-4c02-b6f3-6e06893c8d2c.png">

4. Control + Click **Mindustry.app**

<img width="253" alt="Screenshot 2023-01-18 at 14 07 44" src="https://user-images.githubusercontent.com/3787102/213181636-cfb0a7e7-6781-46d4-bd8d-462087238f2e.png">

5. Click **Open** 

The same error occurs.

6. Click **Show Package Contents**

I can see the package contents:
<img width="207" alt="Screenshot 2023-01-18 at 14 08 35" src="https://user-images.githubusercontent.com/3787102/213181975-b295a6ab-f0ae-424c-8568-853ea8795844.png">

So this seems an app signing issue.

Thanks for all your amazing work!

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The app is not signed, and I have no plans to do so. [Remove the quarantine](https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/) on the app if it fails to work on your device.
