### ISSUE TITLE
Multi items Surge Router lock/stuck

### ISSUE THREAD

**Issue by 1000i100** [Anuken/Mindustry#8200]
**Platform**: *Linux Mint (via Steam FlatPak)*

**Build**: *steam build 141.2*

**Issue**: *I use Surge router to load balance an item filter and it stuck very often*

**Steps to reproduce**:
1. add a Surge Conveyor line with at least 2 items types input in it (i had 4 in my case)
2. add a Surge Router with 2 Surge Conveyor output an nothing in the 3 output.

If an odd number of stack of one kind of item going through the Surge Router, then a stack of another item come, it stuck.
There are 2 half stacks on each output waiting to be completed, but the input items are not the same, so it never completes.

Behavior fix suggested : Instead of dividing stack in individual item to send them in each output, it should act like Reinforced Payload Router show well : alternate the destination of the stack and not of individual item. If there is hybrid output (some Surge and some not), it should act like if there was on surge Conveyor before the no-Surge output, so the stack go on the router output and only then is divided, but other output aren't lock.

Actual Workaround : Not using Surge Router, instead use Reinforced Container or Vault, as router with as many filtering Duct Unloaders as needed, outputting on Surge Conveyor. This way i can filter, load balance, and having big bandwith (Duct Unloader number ×15)

**Link(s) to mod(s) used**: *no mod used*

**Save file**: *I will edit this message to include it in less than an hour*

**(Crash) logs**: *Not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
There are other issue about Surge Router, but not about the same bug/misbehavior. #7223 is the nearest

**Comment by Anuken** [comment]
This is not a bug. Do not mix item types in stacked distribution blocks.

**Comment by 1000i100** [comment]
Why should'nt I do it it's usefull to save space !
But ok to not see this as a bug ;)

**Comment by 1000i100** [comment]
In case you change your mind, here is a screenshot and the savefile (edited in the initial issue message)

**Comment by Rovstam** [comment]
It is just like phase bridge.
Broken as fuck.
