### ISSUE TITLE
Liquid Router ≠ =

### ISSUE THREAD

**Issue by LeahLuong** [Anuken/Mindustry#8209]
Android
141.2, via Play Store update
Vanilla

![Screenshot_20230122-181021](https://user-images.githubusercontent.com/91638992/213956438-60823df4-8fc5-43bd-92bf-c5be92481726.png)
Liquid router's description says it outputs equally but this isn't reflected in my simple experimental setup:

![Screenshot_20230122-181051](https://user-images.githubusercontent.com/91638992/213956582-5f944d38-bb75-4533-83c1-5eb3d4ae4244.png)
N conduit doing ~400.

![Screenshot_20230122-181120](https://user-images.githubusercontent.com/91638992/213956650-d02ae91d-88e3-453f-af89-0e2e38b5fd26.png)
E conduit doing ~200.

![Screenshot_20230122-181206](https://user-images.githubusercontent.com/91638992/213956714-c57bbbc7-801d-4cdc-96d7-397e9743d807.png)
S conduit doing ~100.

Close examination of the pics reflects these differences in the different shades of blue shown by ea. conduit. It's possible this issue is related to the fact I'm running a potato so I've included a .zip below & you can check the values for yourself. This may be related to the issues raised in #4340.

[lr.msav.zip](https://github.com/Anuken/Mindustry/files/10476333/lr.msav.zip)

---
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
While liquid routers ""should"" output equally, in practice this is influenced by all sorts of irrelevant details like update order, FPS and capacity, which cannot be fixed without a complete rewrite of the liquid system. There are many similar issues of this sort, and they are known.
