### ISSUE TITLE
Research of the same material carries over to Surpulo

### ISSUE THREAD

**Issue by RealTaCo201** [Anuken/Mindustry#8213]
**Platform**: Steam (Windows and Linux), Android, iOS

**Build**: 141.3

**Issue**: When getting materials unlocked in Erekir, they will be unlocked in Surpulo (I have not yet confirmed it works both ways).

**Steps to reproduce**: Research thorium, phase fabric, or surge alloy in Erekir, and look in your Surpulo tech tree. Those materials will be unlocked

**Save file**: [Mindustry Bug.zip](https://github.com/Anuken/Mindustry/files/10485776/Mindustry.Bug.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
intended, not a bug
