### ISSUE TITLE
Mindustry141.2数据导出再导入发生崩溃，游戏数据全部消失，本人用的是安卓平台

### ISSUE THREAD

**Issue by znhhhhhhhhh** [Anuken/Mindustry#8216]
**平台* *:` Android 31 ` n n * * Build * *:` release Build 141.2 ` n n * * Issue * *:*详细解释您的问题。* n n * *重现的步骤* *:*您是如何遇到该问题的，以及您具体做了什么导致了该错误的发生。* n n * *链接到使用的mod * *:` none ` n n * *保存文件* *:*发生错误时您正在播放的(压缩)保存文件。这是游戏中发生的任何问题所必需的，不管你是否认为它在任何地方都会发生。不要删除或省略这一行，除非你确定这个问题不会发生在游戏中。* n n * *崩溃报告* *:*相关崩溃报告文件的内容。如果您报告崩溃，则需要此项。* n n-n n *在括号之间打个X(无空格)，确认你已经阅读了下面一行。* n-[]* *我已更新到最新版本(https://github.com/Anuken/Mindustry/releases)，以确保我的问题尚未得到解决。* * n-[]* *我已经搜索了已关闭和未关闭的问题，以确保尚未报告此问题。**
![Screenshot_2023-01-24-11-59-07-50_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/123446527/214239815-3f1136f0-4cea-4ca0-b71d-eacab862d10e.jpg)
![Screenshot_2023-01-24-11-57-40-32_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/123446527/214239821-ea220158-1f73-4151-9633-22cde005eb32.jpg)
![Screenshot_2023-01-24-11-58-06-97_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/123446527/214239830-2197259d-567b-49d2-b5c2-826d7a1ca242.jpg)
![Screenshot_2023-01-24-11-57-56-03_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/123446527/214239835-bdb95ce6-ec95-4e40-874f-3b9a72f77925.jpg)
![Screenshot_2023-01-24-11-58-13-51_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/123446527/214239843-94bf93a6-e561-4ce8-aad1-ee3970c788d7.jpg)

**Comment by JojoFR1** [comment]
It's not a bug, just a schematics is causing the issues. Delete the schematic file wich is mentioned
