### ISSUE TITLE
Map editor toolbar flickers when Discord Streaming is active

### ISSUE THREAD

**Issue by TheRealA77** [Anuken/Mindustry#8217]
**Platform**: Windows 11 Steam version
**Build**: 141.3

**Issue**: When enabling Discord screen share function, the editor bar starts to randomly flicker

**Steps to reproduce**: Open the map editor on Mindustry and screenshare the game on Discord 

https://user-images.githubusercontent.com/72188131/214340258-ab376a51-6bcf-4f40-9f5f-29cf90e13758.mp4
(it's a video of the issue)

**Link(s) to mod(s) used**: https://github.com/sk7725/timecontrol https://github.com/meepoffaith/testing-utilities-java https://github.com/sharlottes/informatis

**Save file**: [Save file.zip](https://github.com/Anuken/Mindustry/files/10491643/Save.file.zip) I've included my whole save file, because it's not really a specific problem with a map

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
(i saw it happened before, but it was in build 127.1 so i don't think it's the same problem at all)

**Comment by Anuken** [comment]
I am aware of this, this is a Discord issue. I cannot fix it.
