### ISSUE TITLE
Toggling battery saver on Android closes Mindustry

### ISSUE THREAD

**Issue by TheFuryBumblebee** [Anuken/Mindustry#8218]
**Platform**: Android

**Build**: 141.3

**Issue**: When turning battery saver on or off, Mindustry completely closes.

**Steps to reproduce**:
1. Open Mindustry
2. Turn on Battery Saver

**Link(s) to mod(s) used**: None

**(Crash) logs**: Does not produce a crash log

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Kieaer** [comment]
It's not game bug. Please read what's battery saver in your android settings menu.

**Comment by Itsfadixx** [comment]
not a bug, Android just closes the ram usage sometimes when batter saver is on

**Comment by TheFuryBumblebee** [comment]
> not a bug, Android just closes the ram usage sometimes when batter saver is on

Ah, makes sense.
