### ISSUE TITLE
tank refabricator image

### ISSUE THREAD

**Issue by Bob90** [Anuken/Mindustry#8226]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
141.3

**Issue**: *Explain your issue in detail.*
Tank refabricator images do not rotate correctly.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Place 4 tank refabricators, each facing a different direction. Play a game of spot the difference with the top/bottom and left/right ones.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
In sandbox.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bob90** [comment]
![Screenshot_20230126_232341](https://user-images.githubusercontent.com/1275124/215026199-273e2761-9f5f-4dd0-83ec-e4da3a3a5d83.jpg)

**Comment by stacktrace-error** [comment]
they're all rotated just fine
the construction preview has issues but noone should really care

**Comment by Rovstam** [comment]
True!

**Comment by Anuken** [comment]
Not a bug.
