### ISSUE TITLE
Sector problem.

### ISSUE THREAD

**Issue by MrDaykii** [Anuken/Mindustry#8228]
**Platform**: `Android 29`

**Build**: `release build 141.3`

**Issue**: *500+ enemies on first wave sector 70.*

**Steps to reproduce**: *Nothing. Only play the game.*

**Link(s) to mod(s) used**: `none`

**Save**: 

> *
[sector 70 problems.zip](https://github.com/Anuken/Mindustry/files/10519875/sector.70.problems.zip)
.*

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
random sectors sometimes spawn 36 novemtrigintillion enemies. no biggie

**Comment by Rovstam** [comment]
> random sectors sometimes spawn 36 novemtrigintillion enemies. no biggie

36 :o

**Comment by Anuken** [comment]
Cannot reproduce the issue, sector spawns a reasonable amount of enemies on my end.

![image](https://user-images.githubusercontent.com/10100000/216141894-9baebdff-1d6b-4a23-85e6-9306ef0a9825.png)
![image](https://user-images.githubusercontent.com/10100000/216141938-dbde284e-58d9-4375-96dc-4ab6804ae46b.png)

**Comment by MrDaykii** [comment]
![Screenshot_20230204-030025](https://user-images.githubusercontent.com/73408830/216736915-a855a9b4-4d81-43f9-9b11-c89d31328a2c.png)

How -_- i have this problem.
