### ISSUE TITLE
The game seems to be not rendering Color.black

### ISSUE THREAD

**Issue by SMOLKEYS** [Anuken/Mindustry#8230]
**Platform**:
```
Version: release build 141.3
OS: Windows 11 x64 (amd64)
Java Version: 17.0.5
Runtime Available Memory: 1960mb
Cores: 8
```

**Build**: 141.3

**Issue**: The game, for some reason, seems to not want to draw/render Color.black.

[logs.](https://github.com/Anuken/Mindustry/files/10526755/last_log.txt)

**Steps to reproduce**: Draw anything with Color.black.

**Link(s) to mod(s) used**: extra-logging:2.0.0-alpha, new-horizon:0.2.7, newconsole:1.8.1, scheme-size:2.7.26hf, test-utils:49, testers:0.25, yellow-java:0.6

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SMOLKEYS** [comment]
more info:

![image](https://user-images.githubusercontent.com/75618732/215268509-b8cbda22-ecbb-4130-a735-4bc708e63b71.png)

**Comment by Anuken** [comment]
No code provided? I use Color.black everywhere, seems to work just fine.
