### ISSUE TITLE
The error

### ISSUE THREAD

**Issue by Commander2746** [Anuken/Mindustry#8231]
**Platform**: ` redmi9`

**Build**: `bleeding-edge build 23633`

**Issue**: *the error make to leave and it was someting to do with the code i cant updated it due toe no new build *

**Steps to reproduce**: * it happend but no clue to  @help *

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
incomprehensible
