### ISSUE TITLE
Mono Don't Mine

### ISSUE THREAD

**Issue by IcyIsTechnology** [Anuken/Mindustry#8233]
This bug was found in the 135 version. The produced Mono will not actively mine, but must use logic to mine. It is said that it has been going to a place to mine, but that place was blocked by squares, so Mono has not been mining and stayed still.

**Comment by stacktrace-error** [comment]
thanks for completely ignoring that template and not providing a save

**Comment by TheFuryBumblebee** [comment]
Have you tried updating to the latest version (141.3)?

**Comment by IcyIsTechnology** [comment]
no,i was 141.1
![Screenshot_20230130_141228_io anuke mindustry arc2 icy](https://user-images.githubusercontent.com/120733201/215401193-0a0b3f92-edf9-45d9-82d5-0cd7d28ebbce.jpg)
