### ISSUE TITLE
Heat turrets can't shoot when cheating

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8236]
**Platform**: all

**Build**: v141.3

**Issue**: Heat turrets don't get any heat when cheating is enabled

**Steps to reproduce**:

- Team.sharded.rules().cheat = true
- place Afflict
- behold

**Link(s) to mod(s) used**: no mods

**Save file**: no save

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Btw you broke it when you commited this
![image](https://user-images.githubusercontent.com/79508138/215485777-46eec068-5a8c-48b2-894a-c2c3e096e15f.png)

**Comment by nanmenyangde** [comment]
yeah, now heat is required even when cheating
