### ISSUE TITLE
No core database button on mobile platforms on multiplayer servers.

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8239]
**Platform**: Android

**Build**: 141.3

**Issue**: Core database menu missing on Mobile platform

**Steps to reproduce**: Join multiplayer server -> Find core database menu

**Link(s) to mod(s) used**: Vanilla.

**Save file**: Not required.

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There isn't supposed to be one.
