### ISSUE TITLE
Modded gasses have different texture then built-in

### ISSUE THREAD

**Issue by MeiNanziiii** [Anuken/Mindustry#8241]
**Platform**: Windows 

**Build**: 7.0 Build 141.3

**Issue**: modded gasses have different texture then built-in, not anti-aliased

**Steps to reproduce**: Create java mod with gas(or use my mod), start game, and check gas texture

*don't think about mod name or textures, in my plans change it and add content to Tantros planet*
**Link(s) to mod(s) used**: [MOD.zip](https://github.com/Anuken/Mindustry/files/10548248/MOD.zip)

**Save file**: [sanbox_save.zip](https://github.com/Anuken/Mindustry/files/10548292/sanbox_save.zip)

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

1. Game texture
2. Mod texture

![image](https://user-images.githubusercontent.com/106649669/215814702-198ce2ac-3978-4a6c-ac68-ed0e0effb60d.png)

**Comment by Slotterleet** [comment]
Vanilla sprites actually have anti-aliasing for some reason.

**Comment by MeiNanziiii** [comment]
> Vanilla sprites actually have anti-aliasing for some reason.

for base texture i use in-game textures, and they don't have anti-aliasing

**Comment by Slotterleet** [comment]
I get it, the sprite files are basically the same, but anti-aliasing is actually applied in the code.

**Comment by MeiNanziiii** [comment]
> I get it, the sprite files are basically the same, but anti-aliasing is actually applied in the code (I think), and it does not apply to any modded sprites.

in Liquids.java i don't find anything like this

**Comment by Anuken** [comment]
Not a bug, you need to manually antialias your sprites if you want them to look like the real game. This is not done in mods as it takes a lot of time.
