### ISSUE TITLE
Insane lag (freezing) in erekir (sector: Basin)

### ISSUE THREAD

**Issue by Rovstam** [Anuken/Mindustry#8244]
**Platform**: Android

**Build**: 141.3

**Issue**: Game freezes and crashes

**Steps to reproduce**: After receiving the "nuclear strike" the sector said, my game started to suddenly freeze every some time, and over time that waiting time became shorter and the freezing longer up until the game freezed completely and it just crashed.

**Link(s) to mod(s) used**: https://github.com/Ferlern/extended-UI-v7

**Save file**: https://1drv.ms/u/s!AkjX7CdOJJmvhkSzvKMgJ4Jnm9Kt
I am unable to save a campaign game so i give you my entire campaign save instead.

**(Crash) logs**: https://1drv.ms/u/s!AkjX7CdOJJmvhkVluDz76dIJCQ86

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://googleplay.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by overdramaticpanromantic** [comment]
to save a specific campaign game all you need to do is to check what the sector id for that sector is then check the sector-erekir-__.msav file

**Comment by Kieaer** [comment]
Not game bug. Your Android device spec too **very low**.
It's amazing that the game is playable.

**Comment by Anuken** [comment]
Logs:

> Runtime Available Memory: 128mb

Mindustry is a rather resource-intensive game, it will not run on such a phone. You need a better device.
