### ISSUE TITLE
It is impossible to land on the "gorge" sector.

### ISSUE THREAD

**Issue by LDASGC** [Anuken/Mindustry#8245]
**Platform**: `Android 31`

**Build**: `release build 141.3`

**Issue**: *On Erekir, landing on the "gorge" sector is made from the "lake" sector, BUT in sector "lake" absent tungsten!*

**Steps to reproduce**: *I just played.I improved the production of resources in the "spikes" sector, in the "hollows" sector improved two cores. This problem is not only mine!(sorry for mistakes, this is google translator)*

**Link(s) to mod(s) used**: `none`

**Save file**: *
[9sectors+.zip](https://github.com/Anuken/Mindustry/files/10554683/9sectors%2B.zip)
*
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SoMall-dumpling** [comment]
You can choose where to land from. Just enter the sector you want to land from(maybe a sector which has tungsten), then go back to the planet map.
