### ISSUE TITLE
Question about the error in players' clients

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8247]
**Platform**: *Multiplayer server*

**Build**: v141.3

Hello!
This is not really an Issue, I would like to make sure what the problem is?
very often on our servers people just kick with errors, I personally met them extremely rarely, only twice, but for some reason others are thrown out very often, should I think that this is because of our plugin? Or is this a Mindustry bug? what could cause such damage?

our plugin overrides the behavior of GameOverEvent, but in fact it makes the same code, absolutely identical to that in the original server

---

![image](https://user-images.githubusercontent.com/91948148/216181204-64598725-788d-4517-b254-1ed0b69fc973.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There's basically no information in the error besides "the packet was probably not written properly", and it's impossible to say whether this is a plugin issue or game bug. Make sure you aren't doing **anything** in other threads. Without specific steps to consistently reproduce it, there's nothing I can do.

**Comment by Anuken** [comment]
> but how can this affect this error? 

*Nothing* in Mindustry is thread safe. *Any* game API accessed from the non-main thread (sending packets, changing entities, placing blocks...) will lead to all sorts of undefined errors.

**Comment by SSTentacleSS** [comment]
> > but how can this affect this error?
> 
> _Nothing_ in Mindustry is thread safe. _Any_ game API accessed from the non-main thread (sending packets, changing entities, placing blocks...) will lead to all sorts of undefined errors.

ah, then I understand you, we need to specify Core.app.post explicitly to access the API in the main thread?
