### ISSUE TITLE
New research tech isn't synced for clients.

### ISSUE THREAD

**Issue by TqLxQuanZ** [Anuken/Mindustry#8251]
**Platform**: *Windows 10*

**Build**: *steam build 141.3*

**Issue**: *Client side does not receive the updated research tech after the host research new tech, client has to rejoin the game in order to see the new research tech. I understand that only the host can see the research tree but this one is different, the client is missing the new research building from the bottom right tab.*

**Steps to reproduce**: *
1. Host creates a new campaign and allows the client to join.
2. Client joins the host.
3. Host research new tech.
4. Notice that client doesn't receive any new tech on their bottom right building tabs until they rejoin the game.*

**Link(s) to mod(s) used**: *N/A*

**Save file**: [sector-erekir-10.zip](https://github.com/Anuken/Mindustry/files/10578584/sector-erekir-10.zip)

Additional information from Steam Discussion: https://steamcommunity.com/app/1127400/discussions/0/3770110614224798352/
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Heargo** [comment]
I had the same problem with the window-64 itch.io build version 141.3
