### ISSUE TITLE
Poly and Mega will be unable to be controlled by any logic processor after exiting the reconstructor

### ISSUE THREAD

**Issue by SomeonesShade** [Anuken/Mindustry#8259]
**Platform**: Windows 10
**Build**: 141.3

**Issue**: Poly and Mega will be unable to be controlled by any logic processor after exiting the reconstructor
Only reverts if the poly or mega affected by the bugis given any command.
**Steps to reproduce**: Set the reconstructor, making the mega or poly, rts waypoint (the yellow diamond thing) to any position

**Link(s) to mod(s) used**: None

**Save file**: [bug.zip](https://github.com/Anuken/Mindustry/files/10610790/bug.zip)

**(Crash) logs**: *non

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nanmenyangde** [comment]
yes it is. units can only be controlled by logic processor when there's no other command

**Comment by SomeonesShade** [comment]
Here is the thing
Polys and Megas automatically go into Build/Repair Mode ignoring the move to state

Which blocks them from being controlled at all unless being interfered manually with other rts commands

feels buggy since on the surface there is no difference between a unit from a recon without a waypoint and one with a waypoint

**Comment by Anuken** [comment]
not a bug
