### ISSUE TITLE
Prov.get()

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8264]
**Platform**: *Desktop Mindustry v141.3 Linux x64_86*

**Build**: *v141.3 server/client*

**Issue**: 
Today we blew up a lot of oil sources on the server and noticed such a bug that occurs at random moments during the explosion (before that, this error also occurred, but it was not very clear why)

![image](https://user-images.githubusercontent.com/91948148/217024965-fe0752e2-03f3-4e2d-8167-88aabc8b6bfa.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SSTentacleSS** [comment]
![image](https://user-images.githubusercontent.com/91948148/217025516-1f864d0f-549c-419d-a417-0c3838531c75.png)

**Comment by inflexibledark** [comment]
@SSTentacleSS проблема в асинхронном коде.
Ты видимо не понял совет Анюка в первый раз - НЕ ИСПОЛЬЗОВАТЬ асинхронность в плагинах.

Тут, скорее всего, из-за нее неверно отправляется пакет, точнее айди сущности в нем. Из-за этого она неверно читается на клиенте.

**Comment by SSTentacleSS** [comment]
@inflexibledark мы не используем асинхронный код для пересылки пакетов, мы запретили взаимодействие с API mindustry в других потоках, кроме главного
