### ISSUE TITLE
data exporter "drops" pseudo-file extensions

### ISSUE THREAD

**Issue by macks2008** [Anuken/Mindustry#8265]
**Platform**: `Windows 10 x64`

**Build**: `steam build 141.3`

**Issue**: First of all, thank you very much for having a data exporter in the first place (backups backups backups)... But I found a (minor?) problem with it. When naming the file I'm exporting, you have a parser that seemingly looks for file extensions, with the intent of using them for something, but instead it drops them. If I try to name my data file "Mindustry6.0-7.0data", taking the file extension to be implicitly ".zip" rather than specifying it, the file name ends up being "Mindustry6.0-7.zip" (including the extension). The ".0data" completely disappeared. I didn't mean for it to be treated as the file extension, but I would've preferred that to losing the text completely (or, I suppose, having to type a buffer extension or something).

**Steps to reproduce**: 

1. Load up the stated version of the game.
2. When the main menu appears, choose "Settings > Game Data > Export Data"
3. choose a suitable location for your test export
4. for the file name field, use a name that contains a ".", such as the one given in my example.
5. After saving, look at the file name in your file manager (e.g. File Explorer for Windows).

**Link(s) to mod(s) used**: `none`

**Save file**: `none`, as the issue happens in the main menu

**Crash report**: `none`, issue is not a crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This isn't really a bug; don't specify filenames with periods, I think it's bad practice in general. Not dropping the extension might lead to files being saved as e.g. "a.msav.msav" or "image.jpeg.png" if the user erroneously types in an extension with the name. I believe it might also fix some issues with funny export names on some platforms... but it's been a while since I tested how Android does that, I'd rather not touch it.

**Comment by macks2008** [comment]
But you drop ANY extension, not just the extension that matches the export format. That's a little aggressive
