### ISSUE TITLE
Cursor alignment after task switching [ Windows 10 ] 

### ISSUE THREAD

**Issue by nktice** [Anuken/Mindustry#8267]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows 10 [ Edition : Pro / Version : 22H2 / OS Build :19045_24086 ]

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam : Build ID : 10378095
Inside game under title on title screen : steam build 141.3

**Issue**: *Explain your issue in detail.*
After task switching, alt+tab to get out of game, then back into game - the cursor mapping doesn't match the location of the mouse cursor.  It is clear the screen isn't at the same settings for resolution, before and after, tabbing back into the game, so that may be the cause.  It gets difficult, because there's no key controls on the title screen.  

I'd like to suggest supporting the arrow keys and the escape key for title menus, so the settings can be changed without use of mouse.  Including escape, in lots of common software, opens up a prompt, asking the user, if they'd like to quit the game, with a yes or no.  

I have tested this, and it only applies to the game in "Fullscreen".  
Changing the settings to use "Borderless Fullscreen" resolves this issue - 
alas the settings are impractical to change while it is active,
hence the suggestion to allow use of keyboard for menus / settings. 

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Adjust game settings to display using "Fullscreen", then alt+tab task switch, when you alt+tab back, then you will see the issue, of broken mapping.  

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
None...

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

No save file needed.  This is the outer menus before starting game. [ Although this issue, could happen during game-play, causing frustration... ] 

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

This is not a crash... game seems to be quite stable and enjoyable. 
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce this issue, and it doesn't really make sense (Mindustry doesn't do *anything* special with the mouse cursor or its position, I don't even see what could cause this)
