### ISSUE TITLE
Spore deep water

### ISSUE THREAD

**Issue by Hyasabaru** [Anuken/Mindustry#8270]
**Platform**: `Android 5.1.1`
**Build**: `release build 141.3`

**Issue**: You can't build on a `Deep water` tile but `Spore deep water` can, how?

Well, I realize about this when I played in Sector 190 (Serpulo)
![Screenshot_2023-02-07-09-29-25-71-n2](https://user-images.githubusercontent.com/89514487/217730246-7f77df83-25fd-4429-b15e-c302c6afc5af.png)

**Comment by TheEt1234** [comment]
in map making i find that useful

**Comment by TheEt1234** [comment]
in map making i find that useful and changing it would break TONS of maps

**Comment by BlueWolf3682** [comment]
shallower spore water like not deep water exists, this is specifically referring to the deep variant of tainted water

**Comment by Anuken** [comment]
Not going to change this behavior as it breaks maps.
