### ISSUE TITLE
Popping sound on mobile version

### ISSUE THREAD

**Issue by spacecowboy2999** [Anuken/Mindustry#8272]
I'm actually playing on a Huawei P30 Pro with android 10.

The build number is 141.3

While playing i can hear this heavy popping/crackling sound, much like the game is lagging even tho it's full on FPS. I can hear it every time, even in the main menù. 

The bug happens basically every time i play the game. 

I'm playing vanilla, no mod used. 

[(invalid).zip](https://github.com/Anuken/Mindustry/files/10695532/invalid.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce issue, device problem.
