### ISSUE TITLE
The power nodes don't show a line when connected

### ISSUE THREAD

**Issue by Atreew** [Anuken/Mindustry#8282]
Windows

v141.3

Line of power nodes cannot be seen when connected in every gamemode

I downloaded the new 141.3 version of the game and joined a community server and I couldn't see any lines from the power nodes. I clicked on the power nodes and could see that they were connected by a blue diamond. 

I'm so sorry u can reap my soul.i didn't save the game lmao. It was in eviction erekir

Btw no crash
Oh fuck are you not supposed clear the lines
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
press F5

**Comment by MEEPofFaith** [comment]
and also check your graphics settings

**Comment by Atreew** [comment]
Ok
