### ISSUE TITLE
Mistake of a titanium belt speed.

### ISSUE THREAD

**Issue by Creater3d** [Anuken/Mindustry#8286]
Need fix a speed of titanium belt from 9-9,5, sometimes 10 item/second to 11.

![Screenshot_2023-02-11-10-48-50](https://user-images.githubusercontent.com/73776761/218249518-cffe0758-448a-4c03-ada1-c3c90d7fe521.png)

![Screenshot_2023-02-11-10-47-40](https://user-images.githubusercontent.com/73776761/218249524-15cc9272-86ec-4d4c-a3a7-c738b0a1f5e4.png)

**Comment by nanmenyangde** [comment]
because there's space between items on the belt. putting a router next to the source will works.
