### ISSUE TITLE
BuildSelectEvent

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8295]
Recently, I had the task of tracking all actions that occur with blocks, and therefore I needed a state for such purposes, but when I studied all the available Events, I did not find a single event suitable for my tasks, some did not return the previous state, admins for some reason for some strange reason if n>3 => n^2 was called on placeBlock,
now I settled on EventType.BuildSelectEvent, but this event is called through Core.app.post and sometimes it works, and sometimes, as for example with pipelines, it doesn’t work (does not give the previous state), is it possible to make EventType.BuildSelectEvent synchronously executed, so like Core.app.post(() -> Events.fire(new BuildSelectEvent (...))) interferes a lot or tell me how to implement it better (I also need a player, so TileChangeEvent won't work either)

```scala
historyFactory(BlockPlaced, player) // Block Placed handler called when block.isInstanceOf[ConstructBlock]
```

https://user-images.githubusercontent.com/91948148/218570368-7fc71ecf-f223-474d-9346-aa3f9af94f4f.mp4

**Comment by SSTentacleSS** [comment]
Same with
![image](https://user-images.githubusercontent.com/91948148/218577198-0a7c2386-76ec-481e-a6cd-8efd9291daa8.png)

**Comment by SSTentacleSS** [comment]
The problem is that there is no single way to catch a block like a pipeline (which is created in one cycle), since there is only one stable state - the block is built, and Core.app.post causes the plugin to enter a race condition ahead of the curve and therefore more often even where it was supposed to
the complete absence or presence of ConstructBuild - the code will behave completely differently (I suggest removing Core.app.post for those tasks that really require Core.app.post, and not for the entire event)

**Comment by SSTentacleSS** [comment]
*I made an example with modified bytecode without Core.app.post*

https://user-images.githubusercontent.com/91948148/218587480-b9b09dfa-0aee-49dd-93e2-0fdac1b6a0bf.mp4

**Comment by SSTentacleSS** [comment]
Well, this happens with almost all events, at least with blocks, links change faster than any events are called

**Comment by Darkness6030** [comment]
Проблема в твоём коде. В моем плагине все отлично работает через BlockBuildEndEvent. Правда пришлось сделать пару костылей, но зато никаких ошибок / багов не обнаружалось

**Comment by Darkness6030** [comment]
Core.app.post() здесь необходимо, чтобы ивент вызывался в главном потоке приложения, а не где попало

**Comment by SSTentacleSS** [comment]
> 



> Проблема в твоём коде. В моем плагине все отлично работает через BlockBuildEndEvent. Правда пришлось сделать пару костылей, но зато никаких ошибок / багов не обнаружалось

Ты не понимаешь, что ивенты работают как попало из-за этого? и так НЕ должно быть, тем более, что у тебя весь твой плагин через одно место работает это во первых
Во вторых, читай внимательно

> Я предлагаю убрать асинхронный вызов ивента, так как это вызывает дополнительные проблемы, было бы лучше оставить асинхронность за самим обработчиком on, перенеся ответственность с .fire

**Comment by Darkness6030** [comment]
Ивент НЕ вызывается асинхронно. Core.app.post() выполняет таск в следующем тике обновления сервера в главном потоке. Хватит создавать бессмысленные issue, которые не несут в себе никакого смысла. Не понимаешь, как работает код - не лезь в него.

**Comment by SSTentacleSS** [comment]
> Ивент НЕ вызывается асинхронно. Core.app.post() выполняет таск в следующем тике обновления сервера в главном потоке. Хватит создавать бессмысленные issue, которые не несут в себе никакого смысла. Не понимаешь, как работает код - не лезь в него.

Тебя никто не просил лезть в этот Issue, особенно когда не понимаешь проблемы, код относительно потока в котором вызывается Core.app.post выполняется асинхронно, а для тебя специально первые же определения скопирую

**Асинхронность (Асинхронизм) (от греч. α — отрицание, συν — вместе, χρονος — время) — не совпадение с чем-либо во времени; неодномоментность, неодновременность, несинхронность — характеризует процессы, не совпадающие во времени.**

**Асинхронность в программировании — выполнение процесса в неблокирующем режиме системного вызова, что позволяет потоку программы продолжить обработку**

Не понимаешь, как работает код - не лезь в него

**Comment by SSTentacleSS** [comment]
Anuken, and take a look in the direction of this [issue](https://github.com/Anuken/Arc/issues/137), 
I find them more convenient to use, so that you don’t have to constantly write Core.app.post, you can add some function or delete it, (I think imon (imidiate on) could close this problem)

**Comment by Anuken** [comment]
I don't know how you've bypassed the template here, but this issue tracker is for reporting bugs, not asking for general support.

There just isn't any event that stores previous block state. I'm not sure why you need access to this information for logging, when you can just store what happened (player placed/broke block X/Y).

I can remove some of the posts for building events, as those were irrelevant added for legacy reasons, and the selection event isn't even used in the game itself anymore.

I don't see a good reason to rework the event system when your problem problem appears to just be a lack of specific events or information.

**Comment by SSTentacleSS** [comment]
thx, @Anuken 

![image](https://user-images.githubusercontent.com/91948148/219242558-834ed34c-d09b-41d6-bfb2-c77f07a8fd7c.png)
