### ISSUE TITLE
Power Issue

### ISSUE THREAD

**Issue by CIVPro1949** [Anuken/Mindustry#8302]
**Platform**: `Windows 10 x32`

**Build**: `release build 141.2`

**Issue**: *Explain your issue in detail.*
Deselecting an item for power causes all power to temporarily go to 0 while paused
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
I was playing around and I was trying to improve power on planetary launch terminal i then paused to make sure the reactors didn't explode I then played around with a power node I deselected a thermal generator and all power on the map went to 0
**Link(s) to mod(s) used**: `[[#42a5f5]Liplum[]/multi-crafter:1.0]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
file too big i think it is in every game tho
**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, the power becomes "undefined" once the power network updates, and you need to unpause for it to update again.
