### ISSUE TITLE
Scaled Health not calculating correctly

### ISSUE THREAD

**Issue by FredyJabe** [Anuken/Mindustry#8304]
**Platform**: Windows, but i'm pretty sure the issue is on every version

**Build**: 141.3

**Issue**: While modding, im trying to use the Block scaledHealth parameters, but the engine dont take the values I set.
The fix is in this [Pull Request](https://github.com/Anuken/Mindustry/pull/8303).

**Steps to reproduce**: Simply by modding a block using scaledHealth and healthScaling from items.
If using Aeyama mod, build a Wood Wall, should be ((5*lumber) + (10*stone) health points.

**Link(s) to mod(s) used**: [Aeyama](https://www.github.com/fredyjabe/aeyama) (use the repo code, not the release)

**Save file**: No savefile needed.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: No crash, hence no log.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
scaled health uses only block size to determine health
if small wall has 32, large wall has 128

**Comment by Anuken** [comment]
Not a bug.
