### ISSUE TITLE
Basin does not unlock

### ISSUE THREAD

**Issue by ExistingProgrammer** [Anuken/Mindustry#8311]
**Platform**: Linux

**Build**: 141.3

**Issue**: Just captured Split in erekir, but the next sector is still locked (cannot select it)
![image](https://user-images.githubusercontent.com/71560815/219869928-e14b35b5-30f2-4f7e-bd56-5cf143a702c4.png)
![image](https://user-images.githubusercontent.com/71560815/219869957-76a95aab-ddb4-4eab-9f2f-12798434a051.png)
![image](https://user-images.githubusercontent.com/71560815/219869996-06fa8c94-d0e4-42cf-9161-24787e683d98.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: none

**Save file**: 
[basin_bug.zip](https://github.com/Anuken/Mindustry/files/10774442/basin_bug.zip)

**(Crash) logs**: no crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DX-36** [comment]
that is marsh
basin is on the other side of erekir

**Comment by ExistingProgrammer** [comment]
Sry my bad. I couldn't see it an assumed the only locked area I saw was the next sector
