### ISSUE TITLE
Connection closed issue

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8314]
**Platform**: *All, but okay, PC-linux-64*

**Build**: *v141.3*

**Issue**: *the connection with the players just closes (in most cases) this time we kicked 9 players, this happened after we demolished the core for another team, in general, that's all, the console did not show anything useful*

![image](https://user-images.githubusercontent.com/91948148/219882038-7780bce4-f8d5-4a4d-91da-47b78b46f389.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [+-] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SSTentacleSS** [comment]
![image](https://user-images.githubusercontent.com/91948148/219882244-76c578fa-0cf0-41d3-a149-e58f7735c31f.png)

**Comment by Anuken** [comment]
No meaningful information on the reason of the close.

**Comment by SSTentacleSS** [comment]
@Anuken Can you please help me, how can I catch this error?

![image](https://user-images.githubusercontent.com/91948148/219935274-8cfd24a9-2d51-454f-bf62-525e2123c54e.png)

and this happens to everyone at one moment, under different conditions, but in most cases - when something massive happens, like breaking bushes or destroying a team

**Comment by Anuken** [comment]
The warning is normal and occurs every now and then, but the "disconnecting" message provides no information on the cause.
