### ISSUE TITLE
Add a verify progress option in settings PLEASE

### ISSUE THREAD

**Issue by ChanSweetCS** [Anuken/Mindustry#8321]
Dear,
Mindustry Devs

One day,

I go to Mindustry on my Android Account and my progress is gone. Please Mindustry Devs make a verifying option in the settings so I can enter my important stuff and get all of my Edited maps, Downloaded Mods, Etc. I would be thankful if you would do that.

Best Regards,
ChanSweetCS

**Comment by Anuken** [comment]
The issue tracker is for bugs, not feature requests.

**Comment by ChanSweetCS** [comment]
@Anuken im sorry it was my first time being in this GitHub website so when i was trying my hardest to get my mindustry progress back i didnt understand about this tracker thing which also means i panicked. I hope you accept my apology and add a verify progress option in settings, it would help me a ton.

Best Regards,
ChanSweetCS
