### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8328]
**Platform**: *Linux server*

**Build**: *Server v143*

**Issue**: **ALERT, no mods resolution!!!**

![image](https://user-images.githubusercontent.com/91948148/220476457-9316650f-e666-44bb-ab65-d11f9a169544.png)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
What is the bug? What is not being resolved? Steps to reproduce?

**Comment by SSTentacleSS** [comment]
> What is the bug? What is not being resolved? Steps to reproduce?

Mod is initialized but register Server Commands are not called, not sure about registerClientCommands yet

**Comment by SSTentacleSS** [comment]
![image](https://user-images.githubusercontent.com/91948148/220477537-e9b1b36e-ae2f-4196-9ec0-3d24757d761c.png)

**Comment by SSTentacleSS** [comment]
*Your example plugin for example*

**Comment by SSTentacleSS** [comment]
It looks like none of the importMods are ever called.

**Comment by SSTentacleSS** [comment]
![image](https://user-images.githubusercontent.com/91948148/220478549-2e81c861-5d6f-4b16-a04c-ff5821204f81.png)

**Comment by Anuken** [comment]
The bug is that #7972 broke mods by marking the plugins unsupported and having `eachClass()` not iterate through unsupported mods.

**Comment by SSTentacleSS** [comment]
oh, truthly

![image](https://user-images.githubusercontent.com/91948148/220479462-2804e744-aec0-41a8-8f2b-ac74192bf9ce.png)


is there a way to fix this quickly? a patch? otherwise the servers don't work at all

**Comment by L0615T1C5-216AC-9437** [comment]
> oh, truthly
> 
> ![image](https://user-images.githubusercontent.com/91948148/220479462-2804e744-aec0-41a8-8f2b-ac74192bf9ce.png)
> 
> is there a way to fix this quickly? a patch? otherwise the servers don't work at all

set minGameVersion = 136 or above on plugin.json to fix plugin loading error

**Comment by Anuken** [comment]
Updated the server jar on Github and itch individually, since this only affects servers *and* plugins that don't have a minGameVersion (which is most of them, admittedly)

**Comment by SSTentacleSS** [comment]
@Anuken and there is no way to update JitPack?

**Comment by Anuken** [comment]
I don't know why you'd want a JITPack update for this fix, it doesn't change any API.
