### ISSUE TITLE
Mindustry crashs on random

### ISSUE THREAD

**Issue by gaster2411** [Anuken/Mindustry#8335]
**Platform**: *The type of device you were playing on - Windows
**Build**: *The build number under the title in the main menu- Build 142

**Issue**: *Explain your issue in detail.* Mindustry randomly crashes on random on any gamemode. It happens entirely on random, and when it happens, the game freezes, and after around 30 seconds the music cuts out.

**Steps to reproduce**: I have no clue, but it seems it often happens on water, but not always.

**Link(s) to mod(s) used**: https://github.com/ereHyddeS/NeonNights_v7, https://github.com/mindustry-antigrief
**Save file**: All of them,
[saves.zip](https://github.com/Anuken/Mindustry/files/10819332/saves.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

last log:
[I] [GL] Version: OpenGL 4.3.0 / Intel / Intel(R) HD Graphics 4400
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 16.0.1
[I] [RAM] Available: 1.4 GB
[I] [CLIENT] Version: 311ece2, Feb. 23, 2023 Unstable
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:12: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:15: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/fog.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:13: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:12: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/unitarmor.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:12: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:12: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:19: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:14: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:14: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:17: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:17: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:14: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/caustics.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:14: '' :  #version directive missing

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/clouds.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[I] [Mindustry] Version: 142
[I] Loaded mod 'schematics-pack' in 7.7781ms
[I] Loaded mod 'NeonNights 2' in 18.9524ms
[I] [schematics-pack/main.js]: SCHEMATICS-PACK Settings contains settingsKey: 'scheme-pack-v'
[I] [schematics-pack/main.js]: SCHEMATICS-PACK previous version:1, current version:1
[I] [schematics-pack/main.js]: SCHEMATICS-PACK loaded 0 deleted schematics
[I] Time to initialize modded scripts: 1498.6268
[W] No icon found for glyph:  (59443)
[W] The icon stuff took 192.3064
[I] Total time to load: 26570ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
WARNING: 0:8: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_bloom.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:10: '' :  #version directive missing

[W] Shader bloomshaders/screenspace.vert | bloomshaders/alpha_threshold.frag:
Vertex shader
WARNING: 0:7: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[W] Shader bloomshaders/blurspace.vert | bloomshaders/alpha_gaussian.frag:
Vertex shader
WARNING: 0:8: '' :  #version directive missing

Fragment shader:
WARNING: 0:11: '' :  #version directive missing

[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Initialized Discord rich presence.
[I] Fetched 42 community servers.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
[mindustry-antigrief](https://github.com/mindustry-antigrief) is an unofficial client, this is the wrong place to report bugs for it.
