### ISSUE TITLE
Techtrees are linked

### ISSUE THREAD

**Issue by 4ugu5tu5Kl31n** [Anuken/Mindustry#8344]
**Platform**: `Android 31`

**Build**: `release build 142`

**Issue**: Same-name resources on Serpulo and Erekir are linked on techtree.

**Steps to reproduce**: Play simultaneously on Serpulo and Erekir. Unlock thorium and surge alloy on 
Serpulo. They'll get unlocked on Erekir too.

**Link(s) to mod(s) used**: `none`

**Save file**: 
[saves.zip](https://github.com/Anuken/Mindustry/files/10831887/saves.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DX-36** [comment]
that's not exactly a bug, but what you should expect is that the **amounts** of resources are not linked

**Comment by Erisfiregamer1** [comment]
> **Platform**: `Android 31`

What year are you in? The highest Android version is 14 🤔

**Comment by uujuju1** [comment]
to me, it would make more sense this way instead of having to discover the same resource twice

**Comment by camelStyleUser** [comment]
Android 12 is (drum roll please) api version 31

**Comment by uujuju1** [comment]
then why not just put android 12

**Comment by Anuken** [comment]
Not a bug.
