### ISSUE TITLE
Боты появляются в воде. Я зашол в мир и сразу начались проблемы. Модов небыло. (x)

### ISSUE THREAD

**Issue by 1stol2** [Anuken/Mindustry#8346]
@**Platform**: `Android 29`

**Build**: `release build 142`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Erisfiregamer1** [comment]
> @**Platform**: `Android 29`

Another case of someone being too many years ahead... The highest Android version is 14. If your device states it is Android 29, then you may have a problem...

**Comment by camelStyleUser** [comment]
Maybe he meant api version 29

**Comment by camelStyleUser** [comment]
Thats android 10 api version

**Comment by camelStyleUser** [comment]
Yeah you normally write android version not api version but whatever

**Comment by camelStyleUser** [comment]
You forgot to do anything that template says

**Comment by camelStyleUser** [comment]
No logs no saves no checkmarks nothing

**Comment by camelStyleUser** [comment]
No steps to reproduce even
