### ISSUE TITLE
Basin: destroy 2 core not accepted and i cant finish this sector

### ISSUE THREAD

**Issue by CoCuCoH41k** [Anuken/Mindustry#8348]
**Platform**: *Windows*

**Build**: *Steam build 142 V7*

**Issue**: *Ekir sector got bug. i need destroy 2 enemy cores and after that i Should got something. But nothing happend! Sector name is Basin (Котловина)*

**Steps to reproduce**: *I just complete little quest to destroy 2 cores but nothing happend. i mean it should unlock area under my start core*

**Link(s) to mod(s) used**: *No mods*

**Save file**: *Yo [SectorStuckBug.zip](https://github.com/Anuken/Mindustry/files/10833620/SectorStuckBug.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. -- **You made a very good joke, I laugh for 10 minutes at the time of sending the Bug report**

**(Crash) logs**: *No logs cuz i have no crash game*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by uujuju1** [comment]
please provide the .msav map that the issue occurred, instead of your whole save file

**Comment by uujuju1** [comment]
like, Malis can rebuild lost cores, its possible that before you took down both cores, the enemy could've just rebuilt it

**Comment by CoCuCoH41k** [comment]
I solve this problem by restarting sector
