### ISSUE TITLE
I go to a friend's card and this is bullshit, I'm like there, but I'm not there

### ISSUE THREAD

**Issue by nabi132321321** [Anuken/Mindustry#8350]
**Platform**: `Windows 10 x64`

**Build**: `steam build 142`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
![20230226232639_1](https://user-images.githubusercontent.com/126415611/221429765-a41ff328-63f9-421a-a7f6-494629ec3e87.jpg)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---when I connect to a friend, I have something that I am and I am not at the same time, I don't understand, I just don't see him, but I see that he puts something

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by samntt** [comment]
Save file: The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

**Comment by uujuju1** [comment]
what did you do to cause this?
because you seem to have your unit dead, or completely gone

**Comment by TheEt1234** [comment]
hey man can you like, describe this in slightly more detail yknow, maaybe fill in the issue template too, just saying
