### ISSUE TITLE
Bug in Mindustry

### ISSUE THREAD

**Issue by BemutViero** [Anuken/Mindustry#8351]
**Platform**: `Android 30`

**Build**: `release build 141.3`

**Issue**: *Explain your issue in detail.*

I played, kept a nuclear production complex, and left without saving. The next day I go to this game, it was written there 
24+/24 waves 
I clicked continue and a "splinter" core landed on this sector. I don't like bugs!

**Comment by stacktrace-error** [comment]
use the template properly and add a save/mod list you dingus

**Comment by AxoCat** [comment]
[X] You have not read the template

**Comment by Kirik228** [comment]
There aren't servers at online
