### ISSUE TITLE
when I connect to a friend, I have something that I am and I am not at the same time, I don't understand, I just don't see him, but I see that he puts something 

### ISSUE THREAD

**Issue by nabi132321321** [Anuken/Mindustry#8352]
[hs_err_pid8820.log](https://github.com/Anuken/Mindustry/files/10843077/hs_err_pid8820.log)
**Platform**: *The type of device you were playing on - Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: when I connect to a friend, I have something that I am and I am not at the same time, I don't understand, I just don't see him, but I see that he puts something

**Steps to reproduce**: I go to a friend's server, but for some reason I'm not there, but I am, and there's just nothing I can do

**Link(s) to mod(s) used**: mods are not what have not been used I am a game without mods my friend too

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues 

https://user-images.githubusercontent.com/126415611/221656190-ff5bc754-b7fa-45aa-8ece-7c13bda5d4a6.mp4

to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
no version number provided
check main menu for the number under the logo

**Comment by uujuju1** [comment]
I think this exact sam issue has been reported
But both issues do lack some details
This bug happens on build 142 if i remember correctly

**Comment by nabi132321321** [comment]
> Я думаю, что именно об этой проблеме с Сэмом сообщалось. Но в обеих проблемах отсутствуют некоторые подробности. Эта ошибка возникает в сборке 142, если я правильно помню.

I don't know myself, we play on the newest version of the game, and when we go to the old ones everything works fine

**Comment by nabi132321321** [comment]
> номер платформы и версии не указан. Проверьте главное меню на наличие номера под логотипом.

we are playing on the newest build

**Comment by camelStyleUser** [comment]
platform

**Comment by camelStyleUser** [comment]
on which version

**Comment by nabi132321321** [comment]
> на какой версии

on the newest
