### ISSUE TITLE
Is this Bug?

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8357]
**Platform**: *Server Linux x64_86*

**Build**: *v142*

**Issue**:
![image](https://user-images.githubusercontent.com/91948148/222755593-28e3455f-b1ec-466e-ad5a-ad24a8b641ee.png)

**Steps to reproduce**: *idk?*

**Link(s) to mod(s) used**: *Not in mods error*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Either something is wrong with your game, or someone is sending you garbage packets. Unless other servers have this for normal clients, not a bug.
