### ISSUE TITLE
#545 Feature Idea

### ISSUE THREAD

**Issue by TheMeltdown201** [Anuken/Mindustry#836]
1) If possible, adding Wood and Stone for new blocks.
2) If possible too, adding new ores like iron, diamond, gold, uranium and his isotopes, plastic and carbon for new blocks/mechs
3) New Terrain Generation : infinite world like minecraft
4) Wind Turbines
5) If possible, natural disasters (Tornadoes / Volcanoes/ Wind Disasters)
6) New liquid : Molten version of ores.

**Comment by TheMeltdown201** [comment]
New question : I download the Mindustry-Master, opened an IDE and press build, (My IDE is : IntelijIDEA), but i don't know where the file is, and if i want to build a jar, the gradlew build fails, can you help me, again... ?

**Comment by Anuken** [comment]
Don't make separate issues for feature suggestions, there's a dedicated issue for it. Read the README if you want to know how to build the game.
