### ISSUE TITLE
Ghost wave 💀 (Sector 229)

### ISSUE THREAD

**Issue by Hyasabaru** [Anuken/Mindustry#8363]
**Platform**: `Android 22 (5.1.1)`

**Build**: `release build 142`

**Issue**: *There's no enemy wave coming in Sector 229 Serpulo after destroying the South-East Nucleus*

**Steps to reproduce**: *If you destroyed the less-defensive enemy Nucleus (there's 2 Nucleus), there's no enemy wave coming anymore, probably... Try to skip wave and you'll see.*

**Save file**: 
[sector-229.zip](https://github.com/Anuken/Mindustry/files/10890440/sector-229.zip)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Hyasabaru** [comment]
I've already cleared the Sector in my current progress, not sure about exporting my Game Data.

**Comment by Anuken** [comment]
In this map, there are two cores, and only the east one can spawn ground units. Once you destroy it, ground units can no longer spawn, and thus you get some empty waves at the start. Since waves are global, there isn't an obvious fix for this, so I'll leave it as-is.
