### ISSUE TITLE
Bug in campaign

### ISSUE THREAD

**Issue by Haruu987** [Anuken/Mindustry#8367]
**Platform**: `Android 11`

**Build**: `release build 142`

**Issue**: *In the level Peaks, at Erekir, i had a bug were the two enemy base have a big amount of avert units, i couldn't count how much, but at least 70, they also respawn immediately and i can't even attack anything without getting crushed by dozens of averts, I'm sure it's a bug, they do respawn so fast and are an insane number of units*

**Steps to reproduce**: *I just started the level like a normal one, made my turrets and defenses, builded my averts, and tried to attack like in a normal level*

**Link(s) to mod(s) used**: `none`

**Save file**: 
[(invalid) (2).zip](https://github.com/Anuken/Mindustry/files/10892374/invalid.2.zip)

> IN-GAME.*

**Crash report**: 
[(invalid) (2).zip](https://github.com/Anuken/Mindustry/files/10892376/invalid.2.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Haruu987** [comment]
sorry about the invalid files, i really don't know why they appear like that, guess it's because they're not campaign save files.

**Comment by Anuken** [comment]
The save files are invalid, I can't test this.
