### ISSUE TITLE
Crashes in mindustry

### ISSUE THREAD

**Issue by shahribek** [Anuken/Mindustry#8371]
**Platform**: android8.1.0

**Build**: 142

**Issue**: at first the game crashes to the lock screen, then after a while again and again, then the game crashed to the lock screen again but this time the game closed

**Steps to reproduce**: I just played

**Link(s) to mod(s) used**: no mods

**Save file**: [https://drive.google.com/file/d/1-VLGfSYmV7vzTbYxQYRcaFe5X9xPPlKn/view?usp=drivesdk](click here)

**(Crash) logs**: [https://drive.google.com/file/d/1-rzWqIPHmD7YZS6d75sxCYMKQhtpuebO/view?usp=drivesdk](here)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment]
Your crash log link is broken. Instead of the actual google drive link, it opens [this](https://github.com/Anuken/Mindustry/issues/here).

**Comment by shahribek** [comment]
> Your crash log link is broken. Instead of the actual google drive link, it opens [this](https://github.com/Anuken/Mindustry/issues/here).

I edited, please check again
