### ISSUE TITLE
Crash during campaign with LAN. I have the error logs that I will attach

### ISSUE THREAD

**Issue by WillComesBack** [Anuken/Mindustry#8376]
**Platform**: Windows 10 Pro

**Build**: steam build 142

**Issue**: In the middle of the game I would crash while LAN hosting with 2 friends. This only happened 3 times. I feel like it only happens after having capped out on many resources and having Core Foundation upgraded and used on the map.
The one time I was doing an 'Enemy Base' section, we almost killed the last section of the base and it crashed. We got back on and it became a Medium Wave 1/30. The old enemy base is still there but dead. I thought it was funny. Also the other sectors that were originally under attack were now fine.

**Steps to reproduce**: Try to bring a Core Foundation (the one with like 9k or 10k cap per resource) to a new sector. Then try to cap out on all resources. If it helps, I was also playing LAN with 2 other friends

**Link(s) to mod(s) used**: No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

I'm not sure how saves work so I'll zip the whole saves folder and send it. I'm running a campaign and I just click campaign to start where I last started.
Here is the [google link](https://drive.google.com/file/d/1OsaSFaYrKv2Aqqvhbi_Y8HOfosQEgq11/view?usp=sharing)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
The crash logs instructions says there's none. But I have the 3 files where I crashed here
[hs_err_pid17108.log](https://drive.google.com/file/d/11JQxzN40wFg1NDHbvIa8v_idgmwWFyTC/view?usp=share_link)
[hs_err_pid21968.log](https://drive.google.com/file/d/1Q8t9bFxYcCQvBVQmsTGtkmgexeEfm8s1/view?usp=share_link)
[hs_err_pid29284.log](https://drive.google.com/file/d/1PUiB-RmrecJViwyHIlFKiud9swvxS3zr/view?usp=share_link)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a GPU driver bug that tends to occur while streaming the game through Discord. I can't fix this.

**Comment by WillComesBack** [comment]
Ok. Thanks for letting me know!
