### ISSUE TITLE
Launch pad & Logic not working properly during campaign.

### ISSUE THREAD

**Issue by davidchenxx** [Anuken/Mindustry#8378]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
WINDOWS 11 Desktop PC.

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
BUILD 142

**Issue**: *Explain your issue in detail.*
Issue happened during : Campaigning between sectors.

_Example NO 1:_
In sector no.1, 
0 : The first time I start playing sector one, it already has 20k titanium at start.
1 : I built a (one) logic module to do titanium transport between core to a (one) small vault with item cap of 300 units.
2 : Sector no.1 did not have any production of any item, including titanium. ( titanium input = 0 ). Sector no.1 was not next to any active enemy sector ( who in certain amount of time will eventually attack sector no.1 )
3: I left sector no.1 for sector no.2, playing in sector no.2 for sometime ( I did not count the exact time, but I believe it was probably more than an hour. )
4 : I then came back to sector no.1, only to find out that the 20k titanium was fully drained out to less than 1000 units or maybe less.

_Example NO 2:_
Same as sector no.1, change the logic module to Launch pad with a target sector to transport items to had been chosen.
Only that the launch pad had also been disabled the time I left sector no.1 . ( either using logic switch on/off, or by cutting the power it was connected to, or by cutting the supply line to the Launch pad )

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
See example no 1 and 2, it happened more than twice at random, however, strangely it also has a good chance that the bug did not happen during the course. Chances that the bug occurs is around 20-30%.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no link, no mod.

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[https://drive.google.com/file/d/1nuXhGDEfb9GTGdiIfurtlpXDyeScZfQC/view?usp=sharing](url)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
similar issues :
#5243
#5253 
#5772
#5875
#6314
#7031

**Comment by Anuken** [comment]
Your language makes it difficult to figure out what the problem is, but all I will say here is that the sector simulation is all "fake" and does not take into account any active logic. If you have something that disables/enables launch pads, it will not play well with idle sector calculations *at all*. I recommend not using logic with launch pads.
