### ISSUE TITLE
Problems with spawning unit in training, after powering the diffuser

### ISSUE THREAD

**Issue by EbanyCCajs** [Anuken/Mindustry#8386]
![1678482144580](https://user-images.githubusercontent.com/121081074/224468111-7cc92510-d1cf-4f15-8322-4c35faeb1ca9.jpg)
В обучении на моменте запитывания рассеивателя не спавнится вторая боевая единица,в следствии обучение пройти нельзя и открыть территории/начать волну тоже./In the tutorial, at the moment the scatterer is powered up, the second combat unit will not spawn, as a result, the training cannot be completed and you cannot open territories / start a wave either.

**Comment by 3Snake3** [comment]
> ![1678482144580](https://user-images.githubusercontent.com/121081074/224468111-7cc92510-d1cf-4f15-8322-4c35faeb1ca9.jpg)
> В обучении на моменте запитывания рассеивателя не спавнится вторая боевая единица,в следствии обучение пройти нельзя и открыть территории/начать волну тоже./In the tutorial, at the moment the scatterer is powered up, the second combat unit will not spawn, as a result, the training cannot be completed and you cannot open territories / start a wave either.

You didn't create issue according to a template.
