### ISSUE TITLE
Nova tree unit's fly button not appearing.

### ISSUE THREAD

**Issue by ZenTheProtogenOfficial** [Anuken/Mindustry#8391]
**Platform**: `iOS xnull`

**Build**: `release build 142`

**Issue**: *When trying to command the nova unit or any of the units in it's tree the fly/shift button does not appear.*
![1FDB6489-6BA8-4B8B-B8EA-5954032C3DE3](https://user-images.githubusercontent.com/127707548/224807513-d20fc1a6-c1fa-4bb6-9297-0eac5218c7b4.png)

**Steps to reproduce**: *Open Mindustry, command a nova unit, the fly button wont be there.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. 
[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/10960954/mindustry-data-export.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce, shows up correctly on my end.
