### ISSUE TITLE
Неправильное распространение жидкости в жидкостных мостах 

### ISSUE THREAD

**Issue by Yep-Nope1** [Anuken/Mindustry#8392]
**Platform**: `Android 33`

**Build**: `release build 142`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[Pointifix/auto-drill:1, Flin/auto-research:Algorithm 1.2, wizer/extended-ui:0.75, [#0096FF]xzxADIxzx/scheme-size:2.7.44, null/speed-control:0.1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to 
- [ ] 
- [ make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
Короче жидкость не распространяется как нужно 
![Mindustry_2023-03-13-09-18-19](https://user-images.githubusercontent.com/127719462/224622636-dcd8c507-02ed-4edf-9405-6f41e3ca403c.jpg)
![Mindustry_2023-03-13-09-18-12](https://user-images.githubusercontent.com/127719462/224622641-83c5472c-4cc3-4975-9e37-ffaa71076559.jpg)
![Mindustry_2023-03-13-09-18-00](https://user-images.githubusercontent.com/127719462/224622643-a7ce995e-dae2-4aae-a7ab-87c3e517fa79.jpg)
![Mindustry_2023-03-13-09-17-44](https://user-images.githubusercontent.com/127719462/224622646-16ba51b4-85cd-4ca3-bc6f-cca3302a2cac.jpg)
Это скрины, если ставить выход с моста на трубу, то в трубе нет воды. А если добавить трубу с другой стороны то вода есть ,но только в 1 направлении

**Comment by camelStyleUser** [comment]
I assume it is related to update order.
The one that is built last outputs liquid.

**Comment by camelStyleUser** [comment]
Interesting

**Comment by camelStyleUser** [comment]
I reloaded from the save and the issye was almost gone.but the last liquid bridge outputs signifantly more to upper conduit.other conduits connected to last bridge output 4.3 and 1.3
