### ISSUE TITLE
pierced bullet hits unexpected underBullet buildings

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry#8394]
**Platform**: windows

**Build**: 142

**Issue**: the picture shows

![K$I72E@G_4~8{A47 F~3SHV](https://user-images.githubusercontent.com/66559840/225067059-c8c04d92-1d75-4509-9697-50243573e7a8.png)

**Link(s) to mod(s) used**: no mod

**Save file**: [save.zip](https://github.com/Anuken/Mindustry/files/10970869/save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
Cause found.
https://github.com/Anuken/Mindustry/blob/ca2b51d4fed26e55bf3b138d85dbc97fb98648e6/core/src/mindustry/entities/comp/BulletComp.java#L168

It properly handles when shooting aiming at a block, but not when aiming at a unit.

**Comment by MEEPofFaith** [comment]
And I don't think calling `PointBulletType`'s targeting to see if the aim is on a unit every tick is a very good idea.

**Comment by MEEPofFaith** [comment]
...strange, the problem persists even if I change it to using the aim position instead of the aim tile

**Comment by Anuken** [comment]
The attached zip file contains only one save, which is just an empty map, completely different from the image.
