### ISSUE TITLE
Resource Preview UI (Launching)

### ISSUE THREAD

**Issue by Hyasabaru** [Anuken/Mindustry#8397]
**Platform**: `Android 22 (5.1.1)`

**Build**: `release build 142`

**Issue**: *My UI ain't big enough to fit, you have to hover in order to see the hole content.*
![Screenshot_2023-03-16-10-33-43-37](https://user-images.githubusercontent.com/89514487/225553073-1690cac4-8418-4b56-9e67-95c6c3f4e0ac.png)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, there is a scroll bar there.
