### ISSUE TITLE
Malis Remnant(s)

### ISSUE THREAD

**Issue by Hyasabaru** [Anuken/Mindustry#8398]
**Platform**: `Android 22 (5.1.1)`

**Build**: `release build 142`

**Issue**: *I was just reclaiming the derelicts then suddenly a crab got out from the fabricator.*

**Steps to reproduce**: *Just reclaim a derelict fabricator while it has unit inside, that's all.*

**Suggestion**: *Probably the unit should self-destruct upon Sector Clear while inside, or change team instead*
![Screenshot_2023-03-15-16-04-49-33-2](https://user-images.githubusercontent.com/89514487/225557785-0bba2c77-684d-4e2e-8db5-336164183785.png)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate / not a bug.
