### ISSUE TITLE
Trigger.unitCommandChange not fire on Type (de)selection

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#8402]
No unit command event fire on type select/deselect on `commandTable` of `PlacementFragment.java`, please add `Events.fire(Trigger.unitCommandChange);`
https://github.com/Anuken/Mindustry/blob/ca2b51d4fed26e55bf3b138d85dbc97fb98648e6/core/src/mindustry/ui/fragments/PlacementFragment.java#L465

Created PR #8406

**Comment by tyagi-data-wizard** [comment]
Hi @SITUVNgcd ,
Is this issue open?
If yes I would like to work on it.

**Comment by SITUVNgcd** [comment]
> Hi @SITUVNgcd , Is this issue open? If yes I would like to work on it.
I did it and pull a request. #8406

**Comment by tyagi-data-wizard** [comment]
Got it, thanks!
