### ISSUE TITLE
Sandbox Mode while in Campaign

### ISSUE THREAD

**Issue by MindustryPlay** [Anuken/Mindustry#8403]
**Platform**:  *Windows 10*

**Build**: *141*

**Issue**: Hello Anuken, if you can solve this issue that would be amazing. So I was playing Mindustry, and then while placing conveyors I saw the "Item Source" and "Item Void" blocks. I, umm, placed some of them definitely not to cheat, but later I saw that the items kept coming and it didn't disappear. I also noticed that it was as if I was in sandbox mode. When I placed or destroyed blocks it was instant. and when built blocks no resources were used at all. If you know to issue and how to fix it, that would be great.

**Steps to reproduce**:  *I did not do anything, I just noticed it. I also played sandbox mode a bit earlier, but that shouldn't affect anything.*

**Link(s) to mod(s) used**:  *I don't have any mods*

**Save file**:  *I have the zip file ready and I can give it, I'm not sure how though because GitHub says 20mb max.*

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Bottinator22** [comment]
are you sure you were in campaign?
also, were you playing multiplayer?
furthermore, are you sure you don't have mods?
are you sure you haven't messed with the console at all?

sandbox mode is triggered by enabling the Infinite Resources rule
possible causes I can think of:
- thinking you're in campaign when you're actually just in regular sandbox
- multiplayer, host's been messing around
- you have a mod that enables it
- you turned it on through console
- world processor malfunction
- random cosmic ray

**Comment by Bottinator22** [comment]
also, you are outdated, latest build is not 141

**Comment by MindustryPlay** [comment]
Hi Bottinator22, thanks for your reply. You I'm sure that I was in campaign, because all the sectors and the research and I was on a sector I captured. And I don't have any mods, I got the gave less than a week ago. And it was single player (campaign). If you know what it is any help would be appreciated :)

**Comment by Anuken** [comment]
Outdated game, you may need to reset your campaign and use the latest version.
