### ISSUE TITLE
Mono doesn't mine LEAD !

### ISSUE THREAD

**Issue by Yep-Nope1** [Anuken/Mindustry#8404]
![Screenshot_20230318_161823_Mindustry](https://user-images.githubusercontent.com/127719462/226108787-a539cb9a-9f48-4e66-80ff-dfcc43a745a1.jpg)
![Screenshot_20230318_161624_Mindustry](https://user-images.githubusercontent.com/127719462/226108789-b7245d0e-74de-487a-b5ef-0625421fa816.jpg)
**Platform**: `Android 33`

**Build**: `release build 142`

**Issue**: *Mono doesn't mine lead !*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[wizer/extended-ui:0.75, [#0096FF]xzxADIxzx/scheme-size:2.7.47, | VI |/schemepack:1]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Mono doesn't mine lead !

**Comment by Anuken** [comment]
> The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.
