### ISSUE TITLE
Exception in connection

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8408]
**Platform**: *Manjaro Linux x64*

**Build**: *v142*

**Issue**:
![image](https://user-images.githubusercontent.com/91948148/226175788-fd5a15dd-d034-4698-b72f-363c75f2de96.png)

![image](https://user-images.githubusercontent.com/91948148/226176059-7795f636-2d35-45a2-b2bd-02daa2daccff.png)

**Steps to reproduce**:

https://user-images.githubusercontent.com/91948148/226176516-bcc7e4ca-011d-4c46-b1b6-f98b83dc0fa0.mp4

**Save file**:
[4.msav.zip](https://github.com/Anuken/Mindustry/files/11011033/4.msav.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce any issues or network errors on a locally hosted server:

![image](https://user-images.githubusercontent.com/10100000/227731853-3a4b07d4-c2b4-4470-815a-26e6c52f6a22.png)
