### ISSUE TITLE
The Game is randomly crashing

### ISSUE THREAD

**Issue by dadodasyra** [Anuken/Mindustry#8409]
**Platform**: *Windows*

**Build**: *Steam build 142*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *I don't really know, I'm playing in multiplayer with my friends, when starting on a new area the host (me) is randomly crashing, the game closes without any warn and everyone get disconnected.*

**Link(s) to mod(s) used**: *None*

**Save file**: *Here is all the saves, I was on coastline when it crashed, I dont really know what's file is for this specific map...*
[saves.zip](https://github.com/Anuken/Mindustry/files/11011500/saves.zip)

**(Crash) logs**: *The in game button says that there's no crash, the last_log file doesn't contain any information (only people connecting to the host). And I dont find any crash folder.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases), **i'm up to date on steam** to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Contact me for any informations, I've been playing for 3 days and it crashed something like 8 times, it mostly happens at the beginning of the construction of a sector and it's really anoying, the map is saved but all resources are gone and the waves reseted.

**Comment by SSTentacleSS** [comment]
> **Platform**: _Windows_
> 
> **Build**: _Steam build 142_
> 
> **Issue**: _Explain your issue in detail._
> 
> **Steps to reproduce**: _I don't really know, I'm playing in multiplayer with my friends, when starting on a new area the host (me) is randomly crashing, the game closes without any warn and everyone get disconnected._
> 
> **Link(s) to mod(s) used**: _None_
> 
> **Save file**: _Here is all the saves, I was on coastline when it crashed, I dont really know what's file is for this specific map..._ [saves.zip](https://github.com/Anuken/Mindustry/files/11011500/saves.zip)
> 
> **(Crash) logs**: _The in game button says that there's no crash, the last_log file doesn't contain any information (only people connecting to the host). And I dont find any crash folder._
> 
> _Place an X (no spaces) between the brackets to confirm that you have read the line below._
> 
> * [x]  **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases), **i'm up to date on steam** to make sure my issue has not been fixed.**
> * [x]  **I have searched the closed and open issues to make sure that this problem has not already been reported.**
> 
> Contact me for any informations, I've been playing for 3 days and it crashed something like 8 times, it mostly happens at the beginning of the construction of a sector and it's really anoying, the map is saved but all resources are gone and the waves reseted.

What server do you play on?

**Comment by SSTentacleSS** [comment]
I have the same error in global multiplayer now (as technical administrator), they often crash players with a wide range of errors (or sometimes with Connection Closed)

**Comment by dadodasyra** [comment]
Happened 3 times today, I'm going to change to a dedicated server it's really annoying.

**Comment by Kieaer** [comment]
@SSTentacleSS @dadodasyra Have you tried on another server?

**Comment by dadodasyra** [comment]
Wdym by another server ? In fact I just gave up. I tried to setup a dedicaed server by it seems we cant play the campaign on it..

**Comment by Anuken** [comment]
Without logs, there is nothing that can be done.

There is a known issue where the game crashes under Nvidia drivers with Discord streaming active, which I cannot fix, as it is a driver bug.
