### ISSUE TITLE
Tutorial language not changing after selecting another

### ISSUE THREAD

**Issue by pozibrothers** [Anuken/Mindustry#841]
**Platform**: Android

**Build**: Release build 96

**Issue**: With the device language set to Spanish, boot up the game and change the language of it in the settings to English. Then restart the tutorial. The tutorial messages should be in English but they still show up in Spanish.

**Steps to reproduce**:
1. Download game.
2. Skip initial tutorial.
3. Change language.
4. Restart game.
5. Start game again and navigate to restart tutorial option.

The top right messages are shown in Spanish while the rest of the UI shows in English.

**Comment by Anuken** [comment]
Fixed.
