### ISSUE TITLE
enemies that spawn in pvp mode don't move

### ISSUE THREAD

**Issue by Inkboo** [Anuken/Mindustry#8410]
PC/Windows

142 steam

enemies that spawn in pvp mode do not move but attack enemies spawned by guardian do move though

steps to replicate
1. open up a map that supports pvp and has a enemy spawn
2. choose pvp and enter the map
3. send a wave or wait for a wave to spawn and the enemies will not move

no mods

[save data.zip](https://github.com/Anuken/Mindustry/files/11012856/save.data.zip)

not a crash

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They are not supposed to. PvP is for players against players, there must be a team controlling the units.
