### ISSUE TITLE
Pinning the game to the taskbar removes the icon.

### ISSUE THREAD

**Issue by Daconus** [Anuken/Mindustry#8412]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Windows 11
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
142
**Issue**: *Explain your issue in detail.*
When using the itch.io version, pinning the game to the taskbar removes the icon, replacing it with the default .exe icon.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Downloaded the itch.io version, ran it, then pinned it to the taskbar, which removes the icon.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I am not interested in changing this; the executable does not have a resource icon for antivirus reasons.
