### ISSUE TITLE
Auto reload after changing settings?

### ISSUE THREAD

**Issue by Farras-Fadhil** [Anuken/Mindustry#8420]
**Platform**:  *Android*

**Build**: *142*

**Issue**: *Auto reload after changing settings*

**Steps to reproduce**: *Has the auto reload feature been removed after changing the in-game settings? if so, please re-add the feature because I have to enter and exit manually to see changes from the settings that I changed, (sorry if my writing is wrong because I can not speak English) indo~*

**Comment by Anuken** [comment]
I don't understand what you are talking about, there was never any auto-reload feature.
