### ISSUE TITLE
Problem with screen on linux

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8424]
**Platform**: *PC, KDE Manjaro Linux x64, x11 server*

**Build**: *v142*

**Issue**:
Mindustry breaks my desktop, icons don't work, browser tabs don't switch, time suffers

https://user-images.githubusercontent.com/91948148/227444907-93036e9a-4524-45fa-9f12-f5cc41306267.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Mindustry breaks my desktop

Then that is an issue with your desktop, file the issue there. Mindustry does not do anything special with its windows. Applications should not be able to unintentionally break things like that, and this does not happen on any Linux distro I have tried.
