### ISSUE TITLE
Black background but units and buildings visible.

### ISSUE THREAD

**Issue by SgtSarros** [Anuken/Mindustry#8427]
**Platform**: Windows

**Build**: Steam Build 142

**Issue**: When I load any map I see the buildings and units but the background is black. It only started doing this today.  I included a screenshot of the issue:
![20230324162131_1](https://user-images.githubusercontent.com/128879909/227696029-a99605e3-8a10-4879-88fb-9dc6899f9bcc.jpg)

**Steps to reproduce**: *I start he game, and I click load game or continue campaign.

**Link(s) to mod(s) used**: I do not use mods

**Save file**: [mindustry.zip](https://github.com/Anuken/Mindustry/files/11067982/mindustry.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Something is wrong with your GPU or drivers, cannot reproduce this issue on any device.
