### ISSUE TITLE
Help meee😭

### ISSUE THREAD

**Issue by Junyan228** [Anuken/Mindustry#8434]
**Platform**: `Windows 10 x64`

**Build**: `steam build 142`

**Issue**: *I can see only units and buildongs.I cant play mindustry... Here's screenshot.:![20230327112248_1](https://user-images.githubusercontent.com/93854197/227826454-14b3df08-2ce6-429b-ac88-afa483ea48f5.jpg)
*

**Steps to reproduce**: *Just enter to map.That's it.*

**Link(s) to mod(s) used**: `[[#0096FF]xzxADIxzx/scheme-size:2.7.51]`

**Save file**: *Sorry,I can't upload*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
No save file provided, cannot reproduce issue. Try disabling your mods.

**Comment by Junyan228** [comment]
uh... ok.Here is file.I wanna play Mindustry!
[pls-fix.zip](https://github.com/Anuken/Mindustry/files/11075381/pls-fix.zip)
