### ISSUE TITLE
Server list is weird

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8435]
**Platform**: *Android.*

**Build**: *Last Bleeding Edge build.*

**Issue**: *The server list looks weird when you're not in compact mode.*
![Screenshot_2023-03-27-08-11-26-001_io anuke mindustry be](https://user-images.githubusercontent.com/79508138/227846924-740a7167-a10b-4101-a803-e921d6c259d5.jpg)

**Steps to reproduce**: *Use any Android smartphone.*

**Link(s) to mod(s) used**: *No mods.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MichaAI** [comment]
ААХАХАХ
