### ISSUE TITLE
Bans & Votekick not working | PlayerInfo fields is empty or unknown

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8448]
**Platform**: Windows & Linux (test on both)

**Build**: server-release.jar | Version: Mindustry 7-release official / build 142

**Issue**: Vote kicks not working: "You already voted" says servers to all players when thy try to vote 
I searched a little bit for the problem in the code and this is what I found out:
the `currentlyKicking[0].voted.contains(admins.getInfo(player.uuid()).lastIP)` is always `true`, because `lastIP` is `<unknown>`
then I went to explore `PlayerInfo`:
I found, that `ips` & `names` is empty,  `lastName` & `lastIP`, is `<unknown>` for all players, but player.con.address is not `null` or `<unknown>`
Then I tried to set them manually, and and then restarted server: now all players have the same ip (the one I set manually)

**Steps to reproduce**: Just start votekicks

**Link(s) to mod(s) used**: <vanilla>

**(Crash) logs**: Log err stream is empty

PS: tested on SynapseOS (0nera.ru:7777) server and localhost
PS: Bans to now working
---
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Agzam-Ar** [comment]
> Bro you're literally using `Vars.netServer.admins = new Administration()` in your plugin code 💀

I'm testing on vanilla

**Comment by Anuken** [comment]
> Clear server (sever-realise dropped in new folder):

That code is incorrect, uuid is a function, it should be called with uuid(). You're getting player info from the name of a function, which for obvious reasons returns the same empty info for all players. Use getInfo() instead.

> I'm testing on vanilla

I think it is unlikely that you are running into these problems in pure vanilla, as everything works fine when I test it. Sounds like your plugin is doing something wrong.

**Comment by Agzam-Ar** [comment]
If get PlayerInfo not from `Groups.player`, `ips` is same on all players 
An error appeared in the logs:
```
[D] java.net.SocketException: Connection is closed.
	at arc.net.TcpConnection.send(TcpConnection.java:180)
	at arc.net.Connection.sendTCP(Connection.java:75)
	at mindustry.net.ArcNetProvider$ArcConnection.send(ArcNetProvider.java:364)
	at mindustry.net.Net.send(Net.java:227)
	at mindustry.gen.Call.sendMessage(Call.java:1092)
	at mindustry.core.NetServer.onDisconnect(NetServer.java:568)
	at mindustry.core.NetServer.lambda$new$5(NetServer.java:125)
	at mindustry.net.Net.handleServerReceived(Net.java:310)
	at mindustry.net.ArcNetProvider$2.lambda$disconnected$1(ArcNetProvider.java:132)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
	
```
