### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8454]
**Platform**: linux

**Build**: v143

**Issue**:
Is this a bug or a new change in the API?

https://user-images.githubusercontent.com/91948148/229278588-0ff64658-2c4f-465a-8a11-60307309507b.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Xasmedy** [comment]
Fixed [here](https://github.com/Anuken/Mindustry/pull/8455)
