### ISSUE TITLE
Merui's weapon is not displayed.

### ISSUE THREAD

**Issue by Ivan452s** [Anuken/Mindustry#8459]
**Platform**:  Windows 10

**Build**: Steam build 143

**Issue**: Merui's icon weapon is not shown or missing.
https://user-images.githubusercontent.com/74957731/229313725-9fc3d921-d3c3-4a10-9074-6cd061af187c.png

**Steps to reproduce**: When you go into the core database and click on a "Merui" unit, it doesn't show the weapon window at the bottom.

**Link(s) to mod(s) used**: No mods used.

**Save file**: https://drive.google.com/drive/folders/1v370yuVOgpzViJOHnlUimSI49YGCX0rd?usp=sharing

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot. 
noo dont reap my soul пжлст
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This does look odd, but meruis don't *have* a weapon sprite to show to begin with, it's just the unit.

**Comment by Ivan452s** [comment]
> This does look odd, but meruis don't _have_ a weapon sprite to show to begin with, it's just the unit.

Yeah, i know but maybe you could make something great from this. You are good developer and you're answering so fast on these bug reports.

**Comment by DX-36** [comment]
this ended up becoming a feature 🤣
