### ISSUE TITLE
Export data crash

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#846]
**Platform**: iOS

**Build**: release build 96 (v4.3.1)

**Issue**: Exporting the game data causes the game to crash.

**Steps to reproduce**: Main menu > Settings > Game Data > Export Data.
When “Export Data” button is hit, the app crashes.

**Comment by Anuken** [comment]
Which version of iOS are you using, and on what device? I could not reproduce any issues on the latest version, and there are no visible crash logs related to this.

**Comment by willis936** [comment]
It happens to me on both a 6S plus on iOS 13.1.3 and an 11 pro max on iOS 13.1.3.

**Comment by willis936** [comment]
If it is any help: the app crash consists of the  screen immediately going to the home screen.  The app still shows up in the iOS multitasking view.  When entered again, without clearing the app out of the multitasking view, it shows the 0-100% loading launch screen.

**Comment by Anuken** [comment]
So, I can't reproduce a crash on a simulator, but what *does* happen is that the choosing UI either doesn't respond or freezes when I try to do any action on it. Could be yet another quirk of the simulator in regards to how badly it handles native file/sharing dialogs.

**Comment by hawkrives** [comment]
I can reproduce this crash on my phone (iOS 13.1.3, iPhone X), but _not_ on my iPad (13.1.2, iPad Pro 10.5", A1709).

I am upgrading my iPad to iOS 13.1.3 to see if it starts crashing.

(On my iPad currently, the export feature works correctly and doesn't freeze.)

Update: My iPad can still export data after upgrading to iOS 13.1.3,

**Comment by willis936** [comment]
I can no longer recreate this issue in v5.0.

**Comment by emlynmac** [comment]
This is still an issue for me on an iPad Pro, but not on the iPhone 10.
@Anuken would you like a fresh issue raised? I'll also be looking into fixing it too....

**Comment by emlynmac** [comment]
I have a fix for the iPad issue. Creating a PR
