### ISSUE TITLE
Repair aircraft are grossly underestimated in unattended sector defense, causing otherwise excellent defenses to collapse quickly.

### ISSUE THREAD

**Issue by blake-sc** [Anuken/Mindustry#8462]
This is something I mainly understood by looking at the source code.

In attended defense the Mega is an extremely good for keeping the defenses in tip-top shape, but not in unattended sector defense. In maps/SectorDamage.java here is the contribution from units to sumRps:
```
if(unit.team == state.rules.defaultTeam){
                sumHealth += unit.health*healthMult + unit.shield;
                sumDps += unit.type.dpsEstimate;
                if(Structs.find(unit.abilities, a -> a instanceof RepairFieldAbility) instanceof RepairFieldAbility h){
                    sumRps += h.amount / h.reload * 60f;
                }
            }
```
This code only considers a unit to contribute to repair if it has the RepairFieldAbility, and only three units have this ability, the Nova, Poly and Oct.

The Mega in fact contributes nothing to sumRps, **despite being the default repair aircraft**. If a player reasonably relies mostly on Megas for repairing their defenses, they'll lose nearly instantly in unattended sector defense and not understand why. While it is to be understood that unattended sector defense won't be perfectly representative of active defense, this disconnect is particularly jarring and "unfair".

If my calculations are correct the Mega would contribute only 4.7 Rps with its repair guns, which is probably quite low compared with contribution from a basic small mender, which if my calculations are correct would be 5-ish. This is a problem for the obvious reason that a mender is quite possibly nowhere near where it needs to be while a Mega can fly around and focus-fire healing, hence if unit healing guns are to be considered they should be given a nice multiplier if the unit also has repair/rebuild AI. Not to mention a Mega is far more expensive than a small mender.

The other issue is rebuild not being taken into account. Many defenses rely on very cheaply replaced walls, some of which might be destroyed, they are then rebuilt automatically and at totally negligible cost. The ability of Poly and Mega to rebuild effectively gives them a higher Rps independently of their repair abilities, this is mostly a matter of their AI rather than their abilities, many units technically can build but the player typically won't be relying on this in any way. Rebuild gets quite tricky to account for accurately, there is a huge difference between 0 and 1 rebuilder and not much different between having 1 rebuilder and 48 rebuilders. Anyway, it seems like it should be straightforward to add a rebuild factor for unit with repair/rebuild AI, possibly with diminishing returns, something like "rebuild 10 blocks if there is any rebuilder, +1 more block per rebuilder" or something, based on the average block health.

**Comment by Anuken** [comment]
> rebuild 10 blocks if there is any rebuilder

There is no concept of blocks at all, it's a flat regen + health vs damage situation.

> can fly around and focus-fire healing, hence if unit healing guns are to be considered they should be given a nice multiplier if the unit also has repair/rebuild AI

But unlike menders, they can only hit one target. It's not that simple.

---

I've frankly given up on making the sector simulation remotely accurate, so the changes there are likely not going to help much.

A simplified model can never accurate simulate all the complexities of a real factory, and the whole system is a mistake. I can make minor changes to it, but at this point it's best that people avoid relying on it at all. I would remove the whole simulation aspect if I could.
