### ISSUE TITLE
ItemBridge crash

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8463]
**Platform**: *Windows/Server*

**Build**: *v143.*

**Issue**: *My game crashed when i picked up an ItemBridge. The server crashed with the same crash log.*
![image](https://user-images.githubusercontent.com/79508138/229339849-21808e9d-9c90-4645-aa73-1d6581edd2d1.png)

**Link(s) to mod(s) used**: *No mods.*

**Save file**: *Game crashed so i wasn't able to save it.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SITUVNgcd** [comment]
Calling to `Edges.getFacingEdge(source, this)` on L426 return a `null` value.
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/distribution/ItemBridge.java#L426

So mean `world.tile` in `Edges.java` also return `null`.
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/Edges.java#L60

Thus, `world.tile` only return `null` when `x` and `y` are outside of map boundary.
