### ISSUE TITLE
Server Exception with item consumer

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8470]
**Platform**: *Linux*

**Build**: *Server 143*

**Issue**:

![image](https://user-images.githubusercontent.com/91948148/229582863-505f0754-96f7-4331-a10d-6bff2432e483.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

This log doesn't make any sense and implies an improperly initialized block. Save required.
