### ISSUE TITLE
Core not correctly launching resources.

### ISSUE THREAD

**Issue by CrazyGG3r** [Anuken/Mindustry#8474]
On my first launch to Fungal pass, copper lead silicon titanium meta glasss were launched correctly. I lost the sector and now when i tried to launch again, it doesnot launch with basic resources that are required but only launch with additional resources (i.e titanium metaglass graphite). I tried changing core to basic but the issue reproduced. I tried launching resource to salt flats and extraction outpost but same bug. I tried launching to new sectors with low threat and not enemy base, same issue

**Comment by Anuken** [comment]
Invalid issue, no screenshot/save/template provided. Whatever you're using to submit this issue does not include the template.
