### ISSUE TITLE
Core is not launching resources to new sectors

### ISSUE THREAD

**Issue by CrazyGG3r** [Anuken/Mindustry#8475]
Device: Android
Build : 7-official-143
Issue: Core is no longer launching required resources for a new sector into that sector.
Steps to reproduce: wait for resources in another sector, then launch to another sector. 
Mods: none
Attachments: attached ss showing launch attempts from stained mountains to fungal pass and sector 40 to extraction post.
And a save zip file. By exporting data with steps( settings>Game data > exportdata
Found this problem was reported in 2021 xD
And is occuring now 😞😞
Xxxxxxxxx 

![Screenshot_20230405-065113](https://user-images.githubusercontent.com/54592666/229962881-7aea8cb5-e8d6-401a-affa-c2138fdcd14d.jpg)
![Screenshot_20230405-065143](https://user-images.githubusercontent.com/54592666/229962897-f6be5e29-665d-4d67-8a36-76fcff91be5f.jpg)
![Screenshot_20230405-065146](https://user-images.githubusercontent.com/54592666/229962912-1c674970-4abb-4465-a103-726add129de5.jpg)
![Screenshot_20230405-065409](https://user-images.githubusercontent.com/54592666/229962917-e55891b4-ba16-459b-b684-d83d68c9bf7a.jpg)
![Screenshot_20230405-065428](https://user-images.githubusercontent.com/54592666/229962921-c92f7d5a-b0c5-45f1-bda2-d3d43c44e588.jpg)
![Screenshot_20230405-065435](https://user-images.githubusercontent.com/54592666/229962930-0efd4b58-2952-4db9-974e-6a7ef02dec68.jpg)
![Screenshot_20230405-065553](https://user-images.githubusercontent.com/54592666/229962941-f9b4cefc-3cea-45d9-9292-ca51492417e8.jpg)
![Screenshot_20230405-065505](https://user-images.githubusercontent.com/54592666/229962945-a850e52f-a9b1-4c69-9474-5e5106a007e1.jpg)
![Screenshot_20230405-065453](https://user-images.githubusercontent.com/54592666/229962950-881784b7-535d-4e3f-83fe-0bd40402d588.jpg)
![Screenshot_20230405-065613](https://user-images.githubusercontent.com/54592666/229962958-29bb0984-230e-4c49-a5fa-60a96ec143b6.jpg)
![Screenshot_20230405-065631](https://user-images.githubusercontent.com/54592666/229962963-4b1e04ee-c7db-4458-ac9f-73dc7b8c4e3d.jpg)
![Screenshot_20230405-065636](https://user-images.githubusercontent.com/54592666/229962971-d4e59510-1395-4986-9d45-759402c209e4.jpg)

[corelaunch.zip](https://github.com/Anuken/Mindustry/files/11154541/corelaunch.zip)

**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
As displayed in the UI, you don't have any extra resources selected.

![image](https://user-images.githubusercontent.com/10100000/229964999-b99fb63c-9b57-42f0-8610-5ec32a68f97e.png)

You are not launching with anything. The 0+ shows that you have nothing in the loadout. This is not a bug.
