### ISSUE TITLE
481 enemies in 1st wave

### ISSUE THREAD

**Issue by JARAWA** [Anuken/Mindustry#8476]
![Screenshot_2023-04-05-07-30-56-76_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/129917912/229963709-509a17da-27a2-45bf-ade2-f5a150c1233b.jpg)
**Platform**:  Android* 

**Build**: *143.*

**Issue**: *I started playing sector 31 and 38 in serpulo and there were 481 enemies in the first wave itself. I suppose this is a bug.*

**Comment by Anuken** [comment]
Invalid report.
