### ISSUE TITLE
Graphic

### ISSUE THREAD

**Issue by hehname** [Anuken/Mindustry#8477]
Android
Release build 143
I try my defense and this bug was occurred
I'm kill 400 zenith
No crash 
![Screenshot_2023-04-05-10-42-07-226_io anuke mindustry](https://user-images.githubusercontent.com/124525436/230016391-a3117912-bfa2-4bf6-bfa6-341a5ef01a3b.jpg)
![Screenshot_2023-04-05-10-42-10-768_io anuke mindustry](https://user-images.githubusercontent.com/124525436/230016423-22f90fec-5f14-4139-944c-532f19315dfd.jpg)
![Screenshot_2023-04-05-10-26-42-435_io anuke mindustry](https://user-images.githubusercontent.com/124525436/230016439-092ebcf4-62fd-42bc-b30b-bb2b46e2b6ab.jpg)

**Comment by go-na-svidanie-benry** [comment]
![report](https://user-images.githubusercontent.com/124525436/230016874-73c24575-f56a-473a-b439-e4f572f04c66.jpg)
It's not jpg

**Comment by Slotterleet** [comment]
Probably the zenithes are targeting containers and/or vaults. If that's the case, then it's not a bug.

**Comment by BlueWolf3682** [comment]
ive reproduced this bug (ghost, unkillable units that are already "dead") and im not sure what causes them
sometimes it just fixes itself

**Comment by Anuken** [comment]
No save attached + you have loads of mods enabled.
