### ISSUE TITLE
Problems with downloading from mod browser

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#8481]
Note: I am not the one with the issue. Another user in #modding-general has been having issues attempting to download Progression Ministry from the mod browser. I've urged them to make and issue report multiple times however they have not done anything, so I decided "fine I'll do it myself." It's a bit scuffed with not enough information to do anything about it, but at least it's in here now for recognition.
https://canary.discord.com/channels/391020510269669376/653293028869537843/1093582874613121074

**Platform**: Windows 10, judging by the screenshot

**Build**: unkown

**Issue**: Cannot download PM from the mod browser.
![](https://cdn.discordapp.com/attachments/653293028869537843/1093582969559580732/image.png)

**Steps to reproduce**: Attempted download of PM from the mod browser I assume?

**Link(s) to mod(s) used**: unkown

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] ***Anuke is about to reap my soul.***

**Comment by MEEPofFaith** [comment]
\# 1 least useful issue report

**Comment by Anuken** [comment]
Works fine for me, user is either doing something dumb (using foos? maybe it screws up HTTP with its security libraries? or maybe another JVM?) or it's some other issue I can't even begin to test because the user can't provide any useful information.
