### ISSUE TITLE
Mindustry bug "destroy 1x units" On surpulo in campaign mode

### ISSUE THREAD

**Issue by INDxSOMESH** [Anuken/Mindustry#8486]
**Platform**: `Android 28`

**Build**: `release build 143`

**Issue**: *on the campaign mode in the surpulo map in the first area after i built the scatter and waited for the countdown for enemy spawn. After the countdown was over it said "destroy 1x units" But there were no units spawned. *

**Steps to reproduce**: *I was new to this game so i was just following the tutorial and after i build the scatter the enemy didn't spawned.*

**Link(s) to mod(s) used**: `none`

**Save file**: *I dont know how to add the save file *

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce this myself, and as the template says, saves are required. I cannot test anything without one.

**Comment by INDxSOMESH** [comment]
If you tell me how to post the save file i will do it so you can check.
Also i tried the same thing on a different phone and the bug did not occur
it was working fine so i think it was caused by that phone

**Comment by rienheuver** [comment]
I'm having this same problem just now on Serpulo. I attached my save files. Can you re-open this issue therefore please @Anuken ?
[mindustry-bugged.zip](https://github.com/user-attachments/files/16761759/mindustry-bugged.zip)

**Comment by rienheuver** [comment]
Workaround: I deleted my campaign save data since it was the first mission anyways and I was fed up with the other campaign :P second attempt at the campaign worked so I'm good now. Can imagine you'll still want to look into this though
