### ISSUE TITLE
Unloader crash

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8495]
**Platform**: *Server*

**Build**: *v143.1*

**Issue**: *Unloader crashed the server.*
![image](https://user-images.githubusercontent.com/79508138/230783017-c5792455-72d0-4358-b316-0280bd1ac3ff.png)

**Steps to reproduce**: *idk i was in console.*

**Link(s) to mod(s) used**: *No mods.*

**Save file**: *No save because it crashed.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheEt1234** [comment]
HAPPENED IN FISH TOO
