### ISSUE TITLE
Plastanium conveyors do not accept items correctly

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8496]
**Platform**: Windows 10

**Build**:  v143.1

**Issue**: Plastanium conveyors do not accept items correctly in this situation:

![image](https://user-images.githubusercontent.com/90514725/230784232-9ada38b8-aa19-4274-95f1-105e79df2354.png)
![image](https://user-images.githubusercontent.com/90514725/230783533-5f9f61bd-9110-4f6a-98e4-9d1d97283b54.png)

The red cross means that the items do not go
A check mark means that items are moving
Cyan arrows are the direction of conveyor belts

**Link(s) to mod(s) used**: vanilla

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by Agzam-Ar** [comment]
It works everywhere, but if it's necessary, then here's a recreated bug in the sandbox:

[Plastanium_conveyors_bug.zip](https://github.com/Anuken/Mindustry/files/11186383/Plastanium_conveyors_bug.zip)
