### ISSUE TITLE
Flame's visibility bug.

### ISSUE THREAD

**Issue by Ivan452s** [Anuken/Mindustry#8497]
**Platform**: Windows 10

**Build**: Steam Build 143.1

**Issue**: The visibility of the Flame is not updated when cyan enters it. 
![image](https://user-images.githubusercontent.com/74957731/230787663-c2e802f9-378a-4df7-9b90-7a17e6df99fe.png)

**Steps to reproduce**: I put the Flame next to the fog of war, connected the cyan, the firing range was updated, but visibility wasn't.

**Link(s) to mod(s) used**: No mods used.

**Save file**: https://drive.google.com/drive/folders/1v370yuVOgpzViJOHnlUimSI49YGCX0rd?usp=share_link

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's not supposed to be.
