### ISSUE TITLE
Game crashed/closed itself mid game with no crash log or error during crash

### ISSUE THREAD

**Issue by DuckersMcQuack** [Anuken/Mindustry#8505]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

Windows 11 home

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

143.1

**Issue**: *Explain your issue in detail.*

I expanded my current map run, had enemies rush in, and game just closed. No error or anything.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Stand at the most south base and repair as new waves comes in, IIRC i was repairing as the last bunch walked past the walls they destroyed.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
No mods used

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

game generated no crash log.

---
[saves.zip](https://github.com/Anuken/Mindustry/files/11216516/saves.zip)
![Mindustry_zhXUYEDmFc](https://user-images.githubusercontent.com/9039370/231601382-49ff2449-0e47-44c9-a335-3691dd7bc32d.png)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by DuckersMcQuack** [comment]
[saves.zip](https://github.com/Anuken/Mindustry/files/11226965/saves.zip)

Second crash so far. This time i held shift to command my bots, then game just closed itself. Same as last time.

**Comment by MEEPofFaith** [comment]
Since the game isn't leaving a crash report for some reason, could you send the `last_log.txt` instead?
It's located in `C:\Users\<user>\AppData\Roaming\Mindustry`.

It logs some data from the last time you open the game and is cleared upon opening the game again, so you'll have to experience this crash a third time to be able to post it with potential crash details.

**Comment by Anuken** [comment]
I cannot help with crashes that don't leave logs.
