### ISSUE TITLE
Nova unit getting stuck in sector 7 on Serpulo

### ISSUE THREAD

**Issue by Ivan452s** [Anuken/Mindustry#8509]
**Platform**: Windows 10

**Build**: Steam build 143.1

**Issue**: Nova unit can't reach player's core in sector 7.
![image](https://user-images.githubusercontent.com/74957731/232073756-817f38d3-14a8-4e24-a69b-a17d7c59529a.png)
![image](https://user-images.githubusercontent.com/74957731/232074585-24f77656-b476-45b2-89ae-d52fc216420e.png)

**Steps to reproduce**: Go to sector 7 on Serpulo and summon first wave. Nova unit can't reach player's core.

**Link(s) to mod(s) used**: No mods used.

**Save file**: https://drive.google.com/drive/folders/1v370yuVOgpzViJOHnlUimSI49YGCX0rd?usp=share_link

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MEEPofFaith** [comment]
amazing random generation
