### ISSUE TITLE
what

### ISSUE THREAD

**Issue by Arkanic** [Anuken/Mindustry#851]
![Screenshot 2019-10-22 at 08 13 56](https://user-images.githubusercontent.com/50847107/67235645-ffcd4500-f4a3-11e9-9e4c-66d00606c2e4.png)

**Comment by Anuken** [comment]
what are you whatting about

**Comment by Tazshelby2016** [comment]
It's probably the `asd asd asd asd asdagagasasjakbgeah;jwrej 23424234`

**Comment by Arkanic** [comment]
it was actually because you forgot to insert the ```f```

**Comment by Anuken** [comment]
ok

**Comment by ZkyLB** [comment]
hes just having lunch
