### ISSUE TITLE
Damage of some bullets is NaN

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8513]
**Platform**: *server*

**Build**: *v143 and v143.1*

**Issue**: *Lustre bullet damage is NaN*
I used this simple code to test it
![image](https://user-images.githubusercontent.com/79508138/232498991-c8f899ed-bd4d-4d96-b44e-30548cf5fb01.png)

The code prints this
![image](https://user-images.githubusercontent.com/79508138/232499281-6c4a769d-f0b3-4c19-bcde-818debfc5c54.png)

I tried this
![image](https://user-images.githubusercontent.com/79508138/232499454-2a903b1a-0645-466d-8d86-1e18c35a3169.png)

And this is the output
![image](https://user-images.githubusercontent.com/79508138/232499542-1eae946b-3291-454c-a1b4-8845bce9d768.png)

Also the issue applies to ```bullet#11```, ```bullet#155``` and ```bullet#156```.
Maybe it's because they have ```pierce: true```

If this bullet hits a core or a unit, it's HP also becomes NaN

**Steps to reproduce**: *No idea*

**Link(s) to mod(s) used**: *https://github.com/Darkdustry-Coders/CastleWars*

**Save file**: *sorry, no save, I was in console*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
This commit broke it:
https://github.com/Anuken/Mindustry/commit/0122b735a04058b76eca561092bdc32d05edfdc0

**Comment by Anuken** [comment]
*meep does it again*
