### ISSUE TITLE
World Proc explosion radius bug

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#8515]
**Platform**: *The type of device you were playing on - Windows 10 (most likely all platforms)

**Build**: v143.1

**Issue**: World proc explosion radius capped to 100 tiles even tho it lets you enter higher number

**Steps to reproduce**: get world proc, set explosion radius with high damage and greater than 100 explosion radius, set it off and observe only blocks within 100 tiles of the explosion get destroyed (expected all tiles within the specified radius)

**Link(s) to mod(s) used**: none

**Save file**: *will be given in comment* 

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by JasonP01** [comment]
[AnukeBugReport.zip](https://github.com/Anuken/Mindustry/files/11256877/AnukeBugReport.zip)
just change it to .msav (no clue if it will work)

**Comment by Anuken** [comment]
Not a bug, intentional.
