### ISSUE TITLE
Mindustry is a trojan?

### ISSUE THREAD

**Issue by tiger223** [Anuken/Mindustry#8518]
Platform: windows 10

Build: 143.1

Issue: mindustry is detected as a trojan by malwarebites and when I put that in it blocked into a ip address locator it says China.

Steps to reproduce: install malwarebites and set it up and open the game and go to join game and you should get a notification saying trojan blocked.

Link(s) to mod(s) used: none where installed

**Save file: none because i just hit join game on the menu and it got blocked

(Crash) logs: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheEt1234** [comment]
real

**Comment by genialnos** [comment]
dude...

**Comment by tiger223** [comment]
> Platform: windows 10
> 
> Build: 143.1
> 
> Issue: mindustry is detected as a trojan by malwarebites and when I put that in it blocked into a ip address locator it says China.
> 
> Steps to reproduce: install malwarebites and set it up and open the game and go to join game and you should get a notification saying trojan blocked.
> 
> Link(s) to mod(s) used: none where installed
> 
> **Save file: none because i just hit join game on the menu and it got blocked
> 
> (Crash) logs: N/A
> 
> ---
> 
> *Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
> - [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
> - [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
> 

Here are some photos to prove it. 

![Screenshot_2023-04-18_180205.png](https://user-images.githubusercontent.com/131218667/233155979-bcd84e07-1bc6-4a6a-8ce8-8a381368a421.png)

![Screenshot_2023-04-18_180200.png](https://user-images.githubusercontent.com/131218667/233155998-65367367-7ce6-4ce1-bbe7-847869a55e69.png)

![Screenshot_2023-04-18_175958.png](https://user-images.githubusercontent.com/131218667/233156012-afd4befb-d221-4df4-8f66-f29eea1f72ea.png)

![Screenshot_2023-04-18_175934.png](https://user-images.githubusercontent.com/131218667/233156019-d7cb5a60-032d-4593-a5c0-afb9179dbb22.png)

**Comment by nanmenyangde** [comment]
it's clear that 43.248.188.231 is a server located in china

**Comment by DreamOneX** [comment]
![img](https://user-images.githubusercontent.com/83908457/233265463-fa84d4c3-3e81-4c7a-b352-5c7c38a6d071.png)

> Obviously, it is a game server hosted by Chinese, located in China

lol

before you commit this issue, it is better to think about features that need internet connection, like "community server"

unrelated, why did you create a new account for this

**Comment by Bottinator22** [comment]
~~it's less of a Mindustry issue and more of a... why are antiviruses flagging that random domain as malware issue~~

**Comment by osp54** [comment]
You are smart!

**Comment by Def-Try** [comment]
bro, are you serious?
ofc this is a virus, because 6 out of 88 aniviruses detected new version of java in it, that can be false detected
ofc this is a virus, because mindustry tried to connect to community servers because you asked it to
ofc this is a virus, because it is an open source game and you can't check code or build the game by yourself

**Comment by tiger223** [comment]
> bro, are you serious?
> ofc this is a virus, because 6 out of 88 aniviruses detected new version of java in it, that can be false detected
> ofc this is a virus, because mindustry tried to connect to community servers because you asked it to
> ofc this is a virus, because it is an open source game and you can't check code or build the game by yourself

Ok great but you don't need to be a rude person i am a cyber security kid and I take stuff like that pretty seriously to protect myself and friends and family.

**Comment by Def-Try** [comment]
sorry if my previous response sounded rude, but this issue sounds like "i am a paranoid is this game a virus".

**Comment by tiger223** [comment]
Yes thats whats going on cus I have never had this happen to me before on any games

**Comment by Def-Try** [comment]
mkay. now, please, close issue
