### ISSUE TITLE
Can bypass character limit on text input menus

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Anuken/Mindustry#8523]
**Platform**: Windows 10 Pro Build 10.0.19045

**Build**: 143.1

**Issue**: You can bypass the character limit of text inputs by pasting a string, rather than typing it.

**Steps to reproduce**: 
1) receive a text input
2) paste a string larger than 20 characters
3) bug.

**Link(s) to mod(s) used**: None

**Save file**: Not Applicable

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by L0615T1C5-216AC-9437** [comment]
Anuke if you read this please allow the server to set character limit. I'm planning to use text inputs for custom kick reasons and the 20 character limit is an unnecessary limitation.

**Comment by Darkness6030** [comment]
@L0615T1C5-216AC-9437 there is a possibility to set limit. Just look at Call.textInput method params

**Comment by Anuken** [comment]
> Anuke if you read this please allow the server to set character limit.

![image](https://user-images.githubusercontent.com/10100000/233754731-622998e3-c916-4023-acb3-6a6e8ba797d2.png)

????????

**Comment by L0615T1C5-216AC-9437** [comment]
oh mb, didnt see that...
