### ISSUE TITLE
Liquid not consuming when controlled by logic

### ISSUE THREAD

**Issue by liuxirui02** [Anuken/Mindustry#8533]
**Platform**: Android

**Build**: 143.1

**Issue**: Liquid consuming not working properly when disabled and enabled by logic at high speed. In extreme cases when building state is changed every frame, liquid bar barely decrease. 

The issue is probably caused by `prevValid` variable in `updateConsumption()` located in `BuildingComp.java`. Consumer updating seems to be skipped if the building is disabled in last frame.

**Steps to reproduce**: 
1. Place a building consumes liquid (e.g. cultivator)
2. Use logic to enable the building and disable it every other frame

**Save file**: [liquidconsume_save.zip](https://github.com/Anuken/Mindustry/files/11306079/liquidconsume_save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by genialnos** [comment]
is that even possible in real (not sandbox) game?
