### ISSUE TITLE
problem in the game 

### ISSUE THREAD

**Issue by Maks3310** [Anuken/Mindustry#8535]
Android 13

7-official-143.1

when you start training in the first sector, everything is fine, but if you completely close the game, then the next time you enter the game, the training tips disappear and an endless waiting for the next wave appears, this can be done at any time during training and on any map, including custom (I tried play without mods but did not help) 

start playing in the very first server (mandatory with training) on any map, exit the game and close all windows,enter the game.

**Comment by Anuken** [comment]
No save attached, cannot reproduce issue. Starting the Serpulo tutorial, quitting and restarting does not lead to issues.
