### ISSUE TITLE
I can't use the 'any' environment in custom games

### ISSUE THREAD

**Issue by Weptlogdotzip1** [Anuken/Mindustry#8537]
**Platform**: *Android*

**Build**: *143.1*

**Issue**: *when I try to select the 'any' environment in custom games, it just switches back to serpulo*

**Steps to reproduce**: *just try to select the 'any' environment on android*

**Link(s) to mod(s) used**: *none*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Duplicate, already reported.

**Comment by Weptlogdotzip1** [comment]
> It's probably not a bug, the "Any" environment is only for Sandbox 
I tried doing it in sandbox and it didn't work, that's the reason I made this bug report
