### ISSUE TITLE
1st time Game Crash

### ISSUE THREAD

**Issue by kmanwar89** [Anuken/Mindustry#8539]
**Platform**: *Windows*

**Build**: *steam build 143.1*

**Issue**: *Game crashed, first time since purchasing it.  I was on a multiplayer sandbox server and had clicked into another window. Through no external action of my own, the game suddenly crashed. Screenshot of the error message & crashlog are attached.*

**Steps to reproduce**: *Unsure, this is the first and only crash I've ever experienced.*

**Link(s) to mod(s) used**: *None - all mods had to be uninstalled before I joined the server*

**Save file**: *[Save.zip](https://github.com/Anuken/Mindustry/files/11334146/Save.zip)  The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *[crash-report-04_26_2023_10_04_10.txt](https://github.com/Anuken/Mindustry/files/11334108/crash-report-04_26_2023_10_04_10.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by kmanwar89** [comment]
![2023-04-26 10_04_19-Settings](https://user-images.githubusercontent.com/11323060/234611892-971c8a32-cf9d-4bc6-8c14-6fe3dd209682.jpg)

**Comment by Anuken** [comment]
Bug already fixed/reported.

**Comment by kmanwar89** [comment]
Thank you Anuken - mind sharing the Issue # where this is being tracked?

**Comment by Anuken** [comment]
https://github.com/Anuken/Mindustry/issues/8495
