### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Quiark** [Anuken/Mindustry#8546]
**Platform**: Android
**Build**:  143.1

**Issue**: Crash when playing mission (map Crevice), sometimes even on main menu just after start

**Steps to reproduce**: No particular action triggers it, sometimes I can play for 20 minutes

**Link(s) to mod(s) used**: Still happens after game disabled all mods or even after I deleted all

**Save file**: 
[apr29.zip](https://github.com/Anuken/Mindustry/files/11360483/apr29.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 

---
[crash2.txt](https://github.com/Anuken/Mindustry/files/11360484/crash2.txt)
[crash3.txt](https://github.com/Anuken/Mindustry/files/11360485/crash3.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BalaM314** [comment]
This is an issue with a mod, specifically [deltanedas/ldb](https://github.com/deltanedas/ldb).
https://github.com/deltanedas/ldb/blob/000b01a0300b68daf50f81f3101b7857d3428b3f/scripts/proc.js#LL15C39-L15C39

**Comment by 3Snake3** [comment]
This is not a game problems

**Comment by Quiark** [comment]
Thanks ... in that case the problem is that the mod can't be removed and is not disabled by the game's crash detector either. 

I will be reinstalling the game on my phone.

![Screenshot_20230502_091422_Mindustry](https://user-images.githubusercontent.com/59075/235558788-ead23911-b87e-4eef-b63a-568c6d59fd2a.jpg)

**Comment by Anuken** [comment]
Both attached crash logs are from v126.2, which is not relevant. They're not the real crash logs relating to this issue.
