### ISSUE TITLE
World Processors do not execute at all (With "Disable World Processors" disabled)

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#8554]
**Platform**: MacOS

**Build**: 143.1

**Issue**: World processors do not fire their instructions at all, be it in editor or in campaign. I have tried setting block data, reading tile data, disabling buildings, none works.

**Steps to reproduce**: Place a World Processor. Put code in it, for example, setting block data or enabling/disabling a building. It does not fire its instructions.

**Link(s) to mod(s) used**: Fresh791/Fading-Revelations. Tried when disabled - still happens.

**Save file**: Not applicable. Happens regardless of save being used - tried.

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
...this is not an issue i can reproduce *at all* on my win10 client, so i would say at least hand a save

**Comment by overdramaticpanromantic** [comment]
![image](https://user-images.githubusercontent.com/108166075/236016793-75ff4826-8080-4cf9-821a-220981c6f05a.png)
![image](https://user-images.githubusercontent.com/108166075/236016837-56e6f2a0-932a-4ce0-896c-8f30d94266c1.png)

Doesn't work. At all. World procs are not disabled.

**Comment by overdramaticpanromantic** [comment]
Nevermind. I am an idiot on multiple fronts
