### ISSUE TITLE
error map desing

### ISSUE THREAD

**Issue by Putiodas** [Anuken/Mindustry#8569]
X
I have found a design error in the decline map (Erekir), the error is that there is a crater in one of the areas where you can not do it in the early game, thanks to that you get tugsten before that by getting things when you shouldn't have it at the beginning of the game.

And I'm not talking about an old version, but I'm talking about the most recent
![imagen_2023-05-08_153952295](https://user-images.githubusercontent.com/132945789/236917369-5afb532b-b023-482b-8a01-e887f84b28ed.png)

Place an X (no spaces) between the brackets to confirm that you have read the line below.

Place an X (no spaces) between the brackets to confirm that you have read the line below.

[ X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.

**Comment by Anuken** [comment]
No save attached, and I can't figure out what you are trying to say.
