### ISSUE TITLE
Large Plasma Bore show Nitrogen usage as 0.5/sec instead of 3/sec

### ISSUE THREAD

**Issue by kritsr** [Anuken/Mindustry#8571]
**Platform**: *Windows 10 22H2 + openjdk 17.0.6 2023-01-17 LTS*

**Build**: *Release build 143.1*

**Issue**: *Large Plasma Bore show Nitrogen usage as 0.5/sec instead of 3/sec*

**Steps to reproduce**: *Using core database on main menu or click ? when building Large Plasma Bore to see info*

**Link(s) to mod(s) used**: *No mod*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
![image](https://user-images.githubusercontent.com/16793758/236973630-a06d572d-1efa-42de-88e6-7e062e6c8c3e.png)

**Comment by Anuken** [comment]
Already reported/fixed.
