### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Afee888** [Anuken/Mindustry#8576]
**Platform**: `Android 31`

**Build**: `release build 143.1`

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[[#ff0][#fff]paulieg626/cheat:2.7]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Hello!
I've got the bug.
I should got tory at the level on screen, but i cant got tory on this level because tory not at this level.
Sorry for my English 
![Screenshot_2023-05-10-17-24-44-85_13f989b68d7412e5a177fb13b36ac66f](https://github.com/Anuken/Mindustry/assets/133131511/cccc10b7-22ef-47b5-a2b7-1e82705bdd6b)
![Screenshot_2023-05-10-17-24-30-40_13f989b68d7412e5a177fb13b36ac66f](https://github.com/Anuken/Mindustry/assets/133131511/b536f9be-d969-40b6-801d-e238cd803c92)

**Comment by Anuken** [comment]
You're launching from the wrong map.
