### ISSUE TITLE
Frozen Forest Fog Of War making enemies completely invisible

### ISSUE THREAD

**Issue by dragonion123** [Anuken/Mindustry#8588]
**Platform**: Windows 11, Steam

**Build**: Steam build 144.1

**Issue**: Enemies coming out of fog of war are completely invisible and not targetable by turrets. this means that it is almost impossible to beat Frozen Forests, unless im doing something wrong.

**Steps to reproduce**: this happened just by existing. this carries across both Foo's client and after reinstalling minedustry to get rid of Foo's.

**Link(s) to mod(s) used**: https://github.com/EmanuelG-Gaming/mindustry-raycaster

**Save file**: [Dragonion's Bug Report Save.zip](https://github.com/Anuken/Mindustry/files/11465940/Dragonion.s.Bug.Report.Save.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---no crash logs found / not a crash

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Frozen Forest is not supposed to have fog of war.

> Link(s) to mod(s) used:

You have a mod that changes the way fog works. This has nothing to do with vanilla.

**Comment by dragonion123** [comment]
oh, yeah. i see that now. i got rid of the raycaster and now it works perfectly. thank you!
