### ISSUE TITLE
The game crashs when you have any mod installed the moment you press the join button

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#8589]
**Platform**: android

**Build**: 144.1

**Issue**: this happens to everyone but if you have any mod enabled and you press the join button the game crashs 

**Steps to reproduce**: have any mod installed and press the join button

**Link(s) to mod(s) used**: 
https://github.com/deltanedas/pictocanvas
https://github.com/Pointifix/AutoDrill
https://github.com/RICCJ/ItemBridgeX
https://github.com/ApsZoldat/mindustry-mapping-utilities
https://github.com/xzxADIxzx/Scheme-Size-Lite
https://github.com/MEEPofFaith/testing-utilities-java
https://github.com/yaddrx2/yr2-logic-debugger

**Save file**: ![v144.1 zip.zip](https://github.com/Anuken/Mindustry/files/11466406/v144.1.zip.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: ![crashlog.txt](https://github.com/Anuken/Mindustry/files/11466538/crashlog.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> any mod enabled

It's not "any" mod, it's a bug with scheme-size (and possibly other mods). Not a vanilla issue, disable your mods.

**Comment by Slotterleet** [comment]
yr2-logic-debugger is probably broken. Try disabling it first.

**Comment by XxsuperdeadlysniperxX** [comment]
> yr2-logic-debugger is probably broken. Try disabling it first.

Its scheme size lite i guess the mod(s) just needed min version update

**Comment by XxsuperdeadlysniperxX** [comment]
> > any mod enabled
> 
> It's not "any" mod, it's a bug with scheme-size (and possibly other mods). Not a vanilla issue, disable your mods.

Just scheme size lite
