### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Amirka0101** [Anuken/Mindustry#8591]
**Platform**: `Android 33`

**Build**: `release build 144.1`

**Issue**: *Game crashes .*

**Steps to reproduce**: *I just go into the game and it crashes when it wants to. Maybe in the first 5 seconds, maybe after an hour .*

**Link(s) to mod(s) used**: `I don't use mods `

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*⁷

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
[Erorr.zip](https://github.com/Anuken/Mindustry/files/11466650/Erorr.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no valid crash log attached.
