### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Amirka0101** [Anuken/Mindustry#8592]
**Platform**: `Android 33`

**Build**: `release build 144.1`

**Issue**: *I just play and the game crashes. I don't use mods. I didn't mess with the game code. I downloaded it from Play Market. All my friends don't get this error. Please help me I really like this game. .*

**Steps to reproduce**: *I'm just playing the game. It doesn't matter, I went to the planet in the sector. The game just crashes when it wants to. .*

**Link(s) to mod(s) used**: `none`

**Save file**: *
[save.zip](https://github.com/Anuken/Mindustry/files/11466803/save.zip)
.*

**Crash report**: *
[save (1).zip](https://github.com/Anuken/Mindustry/files/11466804/save.1.zip)
.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
There is no valid crash report in the attached file. I cannot help you.

**Comment by Amirka0101** [comment]
Vsmysle just does not show failure? Or am I sending the wrong file

**Comment by Amirka0101** [comment]
*Does not show departure?

**Comment by Anuken** [comment]
There is no crash log attached.

You have 192.0 MB available RAM to run the game, which is not enough. The likely cause is that a better device is required to play Mindustry.
