### ISSUE TITLE
Problem with Intersect level

### ISSUE THREAD

**Issue by korsarer** [Anuken/Mindustry#8593]
**Platform**: `Android 29`

**Build**: `release build 143.1`

**Issue**:  Hello! Sorry if my English is bad. I have problems with 4th level named Intersect. After all waves of enemies, the final goal is to destroy Enemy Core. The problem is that there is the rocks and walls around my base. I can't flight over them. I need a Mech units, that can fly over the mountains. But to build Mech units i need a Tungsten. But on this level there is no Tungsten Ore. I tried to build Mech on all map. And there is no place where i can build it. So this level is impossible. Please, tell me what to do

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> But on this level there is no Tungsten Ore. 

There is, below the core. You have not attached a save.

**Comment by korsarer** [comment]
SOLVED: I'm sorry, im stupid 🤣 I just understood that i need to build another one Core Bastion to mine Tungsten Ore
