### ISSUE TITLE
Wave graph bug

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#8594]
**Platform**: Windows 10 (but most likely its on every platform)

**Build**: 144.1

**Issue**: When looking at the wave graph, if a wave is set to be sent every 2 waves (could be also with more) the graph line shows the unit amount per wave get more and more out of hand, the line starts zig-zaging way past what its supposed to and says the unit would spawn negative units one wave and 1000 the next, while the unit cap for that unit is 100 in this case.

**Steps to reproduce**: make a wave with units spaced every 2 waves thats never ends, make sure the units increase to a high amount of unit cap (100) and then just enlarge the wave/unit graph
(see image for reference of what i had and the bugged graph line) ![image](https://github.com/Anuken/Mindustry/assets/131086642/a13fc8cd-f461-45e2-8cee-cedf62beed92)

**Link(s) to mod(s) used**: Foos Client - 37af8d0, Mapping utilities

**Save file**: not save related

**(Crash) logs**: not crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by JasonP01** [comment]
ok well unit cap was 200 but i dont think it mattered very much

**Comment by Anuken** [comment]
Not interested in fixing, there's no comprehensible way to display that kind of information at that kind of zoom with the current wave graph implementation anyway. What you're seeing is sharp lines at such high angles that the joints peek out very far.
