### ISSUE TITLE
Mindustry has crashed. How unfortunate.

### ISSUE THREAD

**Issue by rouvwhqk** [Anuken/Mindustry#8596]
**Platform**: `Windows 10 x64`

**Build**: `steam build 144.1`

**Issue**: *Mindustry has crashed. How unfortunate.*
[crash-report-05_13_2023_11_02_58.txt](https://github.com/Anuken/Mindustry/files/11468750/crash-report-05_13_2023_11_02_58.txt)

**Comment by Anuken** [comment]
No save/information provided, cannot properly fix the crash without circumstances. The template is there for a reason.
