### ISSUE TITLE
Big modded enveroment blocks

### ISSUE THREAD

**Issue by xStaBUx** [Anuken/Mindustry#8601]
**Platform**: *Android/Windows*

**Build**: *v144.1*

**Issue**: *The environment blocks from the mods are larger than the vanilla ones. 
![зображення](https://github.com/Anuken/Mindustry/assets/96493687/f68ec1ad-8880-446b-8dd2-5e558301f01d)
It also causes problems with mod shaders like black lines on block joints:
![зображення](https://github.com/Anuken/Mindustry/assets/96493687/ad543fe4-006a-4c5f-96a2-2f5bd4ba55cd)*

**Steps to reproduce**: *Put a enveronment block from any mod.*

**Link(s) to mod(s) used**: *[Omaloon](https://github.com/xStaBUx/Omaloon/tree/v0.6.1) and [BetaMindy](https://github.com/sk7725/BetaMindy)*

**Save file**: *[0.zip](https://github.com/Anuken/Mindustry/files/11469686/0.zip)*

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not  bug, they blend over other blocks.
