### ISSUE TITLE
NullPointExc

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8604]
**Platform**: *Linux, Mindustry Server*

**Build**: v144.1

![image](https://github.com/Anuken/Mindustry/assets/91948148/55e7783c-bbbe-4fcc-a6fe-bae7bf2ad257)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Agzam-Ar** [comment]
A little bit of information I got trying to reproduce this:
It doesn't crush server or client
I can get this, then write `Call.sendChatMessage(null);` in client console

To copy:
```
[E] java.lang.NullPointerException: Cannot invoke "String.length()" because "message" is null
        at mindustry.core.NetClient.sendChatMessage(NetClient.java:236)
        at mindustry.gen.SendChatMessageCallPacket.handleServer(SendChatMessageCallPacket.java:37)
        at mindustry.net.Net.handleServerReceived(Net.java:312)
        at mindustry.net.ArcNetProvider$2.lambda$received$2(ArcNetProvider.java:151)
        at arc.util.TaskQueue.run(TaskQueue.java:17)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
```

**Comment by Agzam-Ar** [comment]
I think problem in [this line]
(https://github.com/Anuken/Mindustry/blob/151743021bb06de2ab2776fd4120f20d69ef6e2f/core/src/mindustry/ui/fragments/ChatFragment.java#L195)
`trim()` can return `null`
```
/* Java default code */
 public String trim() {
        String ret = isLatin1() ? StringLatin1.trim(value)
                                : StringUTF16.trim(value);
        return ret == null ? this : ret;
    }
 ```

**Comment by Anuken** [comment]
> I can get this, then write Call.sendChatMessage(null); in client console

Why do this? You're sending invalid information to the server, so it logs it. I don't see a bug here (unless this can happen in vanilla without a console).

**Comment by Agzam-Ar** [comment]
> > I can get this, then write Call.sendChatMessage(null); in client console
> 
> Why do this? You're sending invalid information to the server, so it logs it. I don't see a bug here (unless this can happen in vanilla without a console).

I was just trying to find a way to recreate the error. Because the author sent it with a screenshot

**Comment by Anuken** [comment]
@SSTentacleSS Next time actually fill in the template and provide circumstances/steps like the report asks you to, those fields are there for a reason and I can't fix issues properly without them.

**Comment by Darkness6030** [comment]
> Why do this? You're sending invalid information to the server, so it logs it. I don't see a bug here (unless this can happen in vanilla without a console).

Некоторые игроки заходят на сервер и спамят сообщениями из null-ов. Их невозможно отследить, т.к. ошибка вылезает до логгирования сообщения. И это очень сильно мешает администрированию сервера, т.к. ошибки засоряют консоль.

**Comment by Anuken** [comment]
If the issue is "malicious users can intentionally spam errors in console", then it makes sense to change. This is why I ask for details, and not just a stack trace with no relevant information.
