### ISSUE TITLE
An error in a network game

### ISSUE THREAD

**Issue by HeroOFGorres** [Anuken/Mindustry#8607]
Platform: Windows
[errors.txt](https://github.com/Anuken/Mindustry/files/11475747/errors.txt)

Build: 144.1

Issue: When there are a lot of buildings and units on the map, the game crashes to the main screen with an error.
![image](https://github.com/Anuken/Mindustry/assets/133537793/20842682-d040-4e0f-b3ce-fb11555312dc)
![image](https://github.com/Anuken/Mindustry/assets/133537793/6d6cbb07-2352-498a-85d3-039c99e925f8)
it happens that it crashes into the main menu without an error.

Steps to reproduce: 
I go to the map, which has a lot of units and buildings.
![image](https://github.com/Anuken/Mindustry/assets/133537793/facb9ad1-e604-45fd-8710-92bb445bf183)
After 3 - 20 seconds, the flight takes place. The more units, buildings on the map, the faster the departure.
Also, if I play from the very beginning of the game, then when there are a lot of buildings and units, then there is a departure. I reconnect to the server and play for +- 5 minutes, then fly out again. The more units / buildings, the faster the departure.

Save file: 
The file with the map on which the flight took place.
https://drive.google.com/file/d/1vfxWXB5F38VO218g93UDZqo7JotoKxCZ/view?usp=sharing
But the departure takes place on any fairly large map, where there are a lot of units and buildings.

(Crash) logs: 
![image](https://github.com/Anuken/Mindustry/assets/133537793/20842682-d040-4e0f-b3ce-fb11555312dc)
![image](https://github.com/Anuken/Mindustry/assets/133537793/6d6cbb07-2352-498a-85d3-039c99e925f8)
https://drive.google.com/file/d/1Bqhkyuu3UdNMESyXZD0yZRVmtmSgliiq/view?usp=sharing

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce the issue on my end, it's possible the server is doing something wrong with threads that cause serialization errors.

**Comment by HeroOFGorres** [comment]
@Darkness6030 this error appears on any servers.

**Comment by HeroOFGorres** [comment]
@Anuken I think it's all about the Internet. I have a weak internet connection.
![image](https://github.com/Anuken/Mindustry/assets/133537793/9c8a74fb-35f7-4f8b-8861-7efdee693308)

How to solve this problem with departures?
