### ISSUE TITLE
Error with texture mapping.

### ISSUE THREAD

**Issue by middle1** [Anuken/Mindustry#8612]
**Platform**: *Windows 7 x32*

**Build**: *release build 144.1 from github*

**Issue**: *The game works fine, but when you enter the map (company or multiplayer), the player's model itself is shown and that's it, the whole map is black (as if the textures have not loaded). It's the same with the world map.*

**Steps to reproduce**: 
- Start game
- Сlick on "Play" button
- Сlick on "Company" button
- Launching the starting location.

**Link(s) to mod(s) used**: *Without mods.*

**Save file**: *No server.*

**(Crash) logs**: *The application does not crash.*

**Screenshots with the problem:**
![Скриншот 15-05-2023 183851](https://github.com/Anuken/Mindustry/assets/62933036/d827288c-9e87-42a5-954a-736740f52038)
![Скриншот 15-05-2023 183937](https://github.com/Anuken/Mindustry/assets/62933036/0a29f271-7f40-4dac-9b64-d77551184cb7)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
**I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Cannot reproduce this issue, likely an issue with the graphics drivers.

32-bit support is on its way out, and I recommend you use a newer computer/OSS if possible. Mindustry may drop 32-bit support in the future.
