### ISSUE TITLE
Bugged campain enemy bases

### ISSUE THREAD

**Issue by mblazike** [Anuken/Mindustry#8613]
**Platform**: android 

**Build**: 144.1

**Issue**: I was playing the game in campaign mode, and I was about to destroy the enemy core for a base I was taking over (on surpulo btw), and right as I was about to deliver the final blow, the game crashed. Now normally, I would just re open the game and carry on. But it crashed again when I tried to destroy it. And again. And again. So by this point, I wanted to save the game about 10 seconds before it crashed so I could try to find a workaround. But then I got a save error message. So by this point, I'm pretty confused. I try to destory the core in every way possible, with rockets, with normal guns, with troops, and I even used my own ship. All of them crashed the game as soon as I destroyed the core. Now I'm kind of screwed, so I tried to download the crash logs to see what happened. They are gibberish to me, so I wanted to see if somebody else could help me

**Steps to reproduce**: it happened when I controlled the rocket launcher, shot at the enemy base until it destroyed, and then it crashed. It also happened when I wasn't controlling the rocket launcher. The save error happened when I shot at the base, not destroying it but leaving it low and then trying to save. (Msg me on discord at mblazike#4920 to see videos of it)

**Link(s) to mod(s) used**: https://github.com/meepoffaith/prog-mats-java progression Mindustry 

**Save file**: 
[Mindustry save data.zip](https://github.com/Anuken/Mindustry/files/11481732/Mindustry.save.data.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[message.txt](https://github.com/Anuken/Mindustry/files/11481746/message.txt)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It is a bug with your mods, not vanilla. Disable or uninstall them.
