### ISSUE TITLE
Unable to browse Community servers and Mod Browser is giving Connection Timed Out error

### ISSUE THREAD

**Issue by BhushanDive** [Anuken/Mindustry#8617]
**Platform**: `Windows 10 x64`

**Build**: `steam build 144.1`
**Issue**: *Whenever I try to use the mod browser it gives me the connection timed-out error. Before this latest update,
I was able to access the mod browser and also able to access the Community servers other than the steam ones but Now I am unable to access these servers.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
**Error Image**: ![image_2023-05-17_151122118](https://github.com/Anuken/Mindustry/assets/87260992/e6ec3bfb-3850-430c-992c-4db40bdc3425)
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Unable to reproduce the issue; you likely have network issues. Absolutely no relevant netcode was changed between the last two releases.
