### ISSUE TITLE
Can not cast Puddle to Player

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8619]
**Platform**: Linux x64

**Build**: v144.1

**Issue**:
![image](https://github.com/Anuken/Mindustry/assets/91948148/e45e7412-0d83-43ef-b722-0d46fce34d24)

**Steps to reproduce**: I can't describe how it happened, it happened on the server

I will reap your soul. Even if you're playing on someone's server.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I've never seen an error like this, I can't fix it without extra information or steps to reproduce.
