### ISSUE TITLE
Game crashes on join game tab

### ISSUE THREAD

**Issue by Ninjdai1** [Anuken/Mindustry#8623]
**Platform**: `Linux x64`

**Build**: `release build 144.1`

**Issue**: When clicking on Join Game in the main menu, the whole window freezes (except the music) and RAM (and swap) usage goes up to 100%, then either the game/the computer crashes or the window shows up after a few minutes of waiting.

**Steps to reproduce**: Click on the join game tab
![image](https://github.com/Anuken/Mindustry/assets/65647523/4e792bb2-eaba-4ccc-8c4f-444716ad2ce1)

**Link(s) to mod(s) used**: `None`

**Crash report**: *There are no crash reports*
**Logs**:
```
[I] [GL] Version: OpenGL 4.6.0 / Intel / Mesa Intel(R) UHD Graphics 605 (GLK 3)
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 17.0.6
[I] [RAM] Available: 932.0 MB
[I] [Mindustry] Version: 144.1
[I] Total time to load: 6316ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 44 community servers.
```

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

EDIT: No logs shows up when or after clicking the join game button

EDIT: It only takes a long time the first time loading the tab every time after launching the game. It loads instantly after that, if the game was not closed

**Comment by Anuken** [comment]
Cannot reproduce the issue on any device. Logs show no errors.
