### ISSUE TITLE
Disperse not firing anymore

### ISSUE THREAD

**Issue by pk27734** [Anuken/Mindustry#8625]
**Platform**: *Mac*

**Build**: *144*

**Issue**: *I've completed the campaign for Erekir once (started on v7) and now I'd like to replay Origin. I abandoned my base, collected resources in one of the previous maps and started it again from scratch. After some tries I've built a lot of Disperse to protect from air attacks, but none of them are firing...! They all have enough ammo and even water, so they should work. What's wrong? The Breaches and Diffuses do work. Note that I did encounter something similar on a custom map when trying to defend using Sublimate's, they didn't fire neither, only rotated a little bit.*

**Steps to reproduce**: *Nothing specific, just play the game..?*

**Link(s) to mod(s) used**: *None.*

**Save file**: *[mindustry-data.zip](https://github.com/Anuken/Mindustry/files/11515659/mindustry-data.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *None available*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by pk27734** [comment]
Check out this screenshot, they aren't doing anything.
![Screenshot 2023-05-20 at 10 21 30](https://github.com/Anuken/Mindustry/assets/70482/a7e96244-d30b-4ab1-954e-d607dc0ade46)

**Comment by 3Snake3** [comment]
> Check out this screenshot, they aren't doing anything.
> ![Screenshot 2023-05-20 at 10 21 30](https://github.com/Anuken/Mindustry/assets/70482/a7e96244-d30b-4ab1-954e-d607dc0ade46)
> 

Elude isn't a flying unit, that's why turret don't shoot.

**Comment by 3Snake3** [comment]
Use ground or multi target turrets against these enemies

**Comment by pk27734** [comment]
Ah I didn't know that, I thought all air units are air... Didn't know one of them is more of a hovercraft. Is that explained somewhere?

**Comment by 3Snake3** [comment]
> Ah I didn't know that, I thought all air units are air... Didn't know one of them is more of a hovercraft. Is that explained somewhere?

In Elude's information sheet, flying: no, can boost: no. And also if you play for it and look at his behavior.
