### ISSUE TITLE
Loading custom maps fails on server builds

### ISSUE THREAD

**Issue by bend-n** [Anuken/Mindustry#8630]
**Platform**: Server

**Build**: 144.2

**Issue**:
Running `server-release.jar` produces this error, but normal client loads it fine.
```java
[E] Failed to load custom map file 'config/maps/flower.msav'!
[05-22-2023 16:30:31] [E] java.lang.NullPointerException: Cannot invoke "mindustry.io.SaveVersion.region(String, java.io.DataInput, arc.util.io.CounterInputStream, mindustry.io.SaveFileReader$IORunner)" because "ver" is null
	at mindustry.io.MapIO.createMap(MapIO.java:45)
	at mindustry.maps.Maps.loadMap(Maps.java:458)
	at mindustry.maps.Maps.load(Maps.java:122)
	at mindustry.Vars.init(Vars.java:288)
	at mindustry.server.ServerLauncher.init(ServerLauncher.java:57)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
```

**Steps to reproduce**:
- put map in config/maps
- run server-release.jar
- observe

**Link(s) to mod(s) used**: N/A

**Map file**: [flower.zip](https://github.com/Anuken/Mindustry/files/11529499/flower.zip)

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by bend-n** [comment]
Maybe im placing the map in the wrong place? I never get the `Loading map...` output. Am i supposed to put it in `config/maps/flower.zip`? is there something I need to change in the `settings.bin` file?

**Comment by Anuken** [comment]
> Am i supposed to put it in config/maps/flower.zip

Maps are not supposed to be zipped. You just put the msav in the config/maps folder and host with it.

**Comment by bend-n** [comment]
Sorry, `config/maps/flower.msav`. But thats all there is to it? hmm.... I dont see why it fails then.

**Comment by bend-n** [comment]
This issue doesnt occur on v144.

**Comment by Anuken** [comment]
> at mindustry.io.MapIO.createMap(MapIO.java:45)

![image](https://github.com/Anuken/Mindustry/assets/10100000/3da2b904-88d2-4919-a443-3c44a2ad1132)

Line 45 in MapIO is a curly brace. You're likely not using an official build.

**Comment by bend-n** [comment]
I dont have a copy of the mindustry source code on hand; I downloaded it from the github release. The sha256sum is `f4d04f81a54645adb376034848639d0179e5854284b34ee94cb1f2319426e6b8`. Is that wrong?

**Comment by Anuken** [comment]
Yes, it is wrong. I get `4290cac45b8bea6e72348c7778435c144c380f86572367a27bcb42d1eb5f25e2`

**Comment by bend-n** [comment]
Oh, how curious. I wonder how that happened. It seems to work on the official-build-i-thought-i-downloaded-but-somehow-didnt.
