### ISSUE TITLE
A small graphic bug | not critical

### ISSUE THREAD

**Issue by Agzam-Ar** [Anuken/Mindustry#8632]
**Platform**: Windows 10

**Build**: v144.3

**Issue**: 
the new textures are too "thick" and get out of the edges, especially when the turrets are firing, as well as the blur is cut off at the edges

![image](https://github.com/Anuken/Mindustry/assets/90514725/1f5e320c-1b7d-4054-afe9-a0660dccb18b)

**Link(s) to mod(s) used**: none

**Save file**:  this is graphic bug, save file not need 

**(Crash) logs**: none

_PS: I do not know whether it is worth creating an issue because of such trifles (if it is trifles)
If such an issue does not need to be created, then I apologize in advance_

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by stacktrace-error** [comment]
this is not a bug, turrets are not limited to their base

**Comment by Agzam-Ar** [comment]
> this is not a bug, turrets aren't limited to their bases and linear filtering breaks the edges of textures a lot (not very noticably)

in any case, the fact that the turrets overlap each other looks unnatural

**Comment by Agzam-Ar** [comment]
> \[img\]

I didn't say that it's better with old textures, I just thought that since you've already started working on textures, then why not fix it
