### ISSUE TITLE
Sector 264 being incredibly easy

### ISSUE THREAD

**Issue by maksiksking** [Anuken/Mindustry#8642]
**Platform**: Android

**Build**: Release 144.3

**Issue**: Despite being on the south pole and having extreme difficulty the sector only has 1 core and the enemy progression is more like the tutorial sector, not swarms of t1 flying enemies like in sectors around it.

**Steps to reproduce**: Literally just played sector 264 noticed I beat it too fast despite anticipation.

**Link(s) to mod(s) used**: No related mods (Only Ukrainizator if else)

**Save file**: Herech u go  https://drive.google.com/file/d/1yNeRJIv7UFKeNyCM3IdrcaPb2UdAACSs/view?usp=drivesdk

**(Crash) logs**: nah

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That's procedural generation for you; not interested in changing.
