### ISSUE TITLE
Maps that are toooooo huge for multiplayer

### ISSUE THREAD

**Issue by Rimakari** [Anuken/Mindustry#8645]
**Platform**: Windows (Also on phones, i tried it)

**Build**: 144 and 143.1

**Issue**: On huge maps you cannot build because it says "Unit can't build" and your character doesnt show's up

**Steps to reproduce**: Load a bigger map onto a server and start it (On singleplayer it works fine)

**Save file**: Create a map that's bigger than 2000x2000 and load it onto a server, (I hope that you have a map that's bigger than 2000 otherwise i know what happens!) 
But just in case, i have added a map in zip format
[Desert (2).zip](https://github.com/Anuken/Mindustry/files/11582955/Desert.2.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> Create a map that's bigger than 2000x2000

This is not supported. Don't.

**Comment by Anuken** [comment]
Follow-up: I loaded this map on a server to double-check, and there is no bug here, the map is just broken. You have Serpulo cores on an Erekir environment. They can't spawn anything.

**Comment by Rimakari** [comment]
I've tried different settings, and why is it working on singleplayer then?

**Comment by Anuken** [comment]
Set the planet to Serpulo.
