### ISSUE TITLE
Audio does not work after switching back from Bluetooth

### ISSUE THREAD

**Issue by vladtepesch** [Anuken/Mindustry#8648]
**Platform**: Windows

**Build**: 144.3

**Issue**: If I switch to bluetooth head phones the sound is correctly transfered to the headphones but on disconnect the sound does not switch back correctly. Normally this is not a problem with other games - so I think its not a global configuration problem 

**Steps to reproduce**: see above

**Link(s) to mod(s) used**: n.a.

**Save file**: n.a.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.
-- understood, I think 😬

**(Crash) logs**:  n.a.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is a bug in the underlying audio library, which I did not write. Unable to fix.
