### ISSUE TITLE
Unit select dialog is sus

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8658]
**Platform**: *Windows 11*

**Build**: *Latest BE build.*

**Issue**: *The unit select dialog in wave editor is broken.*
![image](https://github.com/Anuken/Mindustry/assets/79508138/b9dc6c5d-d88e-4d1c-a50d-3efa15006baf)

Before:
![image](https://github.com/Anuken/Mindustry/assets/79508138/0fb3ebbf-d2ab-49d2-95cb-5c60eec15193)

After:
![image](https://github.com/Anuken/Mindustry/assets/79508138/695147fd-dc23-4eb7-ac86-2f19c8a6a098)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Broken by #8605

@JniTrRny
