### ISSUE TITLE
Erikir tech tree issues

### ISSUE THREAD

**Issue by Illuminaty666** [Anuken/Mindustry#8661]
Platform -Android
V144.3

In the erikir tech tree, materials such as thorium, surge alloy and phase fabric appear, even though they have not been produced yet. Ever since sector atlas, there have been things in the research tree that require thorium to research, even though thorium is only available for the first time much later in stronghold.

 I noticed it early game and it has been really annoying because things like the large payload mass driver and shielded wall are sitting in the tech tree, unable to be researched, because thorium is not accessible yet. I downloaded the game off google play store, not off of any website.

![save1.zip](https://github.com/Anuken/Mindustry/files/11641684/save1.zip)

 - Save file attached -

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm you have read the line below.*  
- [X]**I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Serpulo and Erekir tech trees share unlock states between items. Not a bug.
