### ISSUE TITLE
Pixmap caused game freeze

### ISSUE THREAD

**Issue by squi2rel** [Anuken/Mindustry#8665]
**Platform**: Windows

**Build**: 144.3

**Issue**: *A invaild Pixmap will freeze the game*

**Steps to reproduce**: f8, new Pixmap([]), and wait for a while, the game will freeze

it returned NULL and didn't release. GetPrimitiveArrayCritical will block all existing garbage collectors. Blocking the garbage collector will prevent all object allocations (once garbage accumulates).

(https://docs.oracle.com/en/java/javase/16/docs/specs/jni/functions.html#getprimitivearraycritical-releaseprimitivearraycritical)

![image](https://github.com/Anuken/Mindustry/assets/102400902/7b0ee16a-fdeb-43ef-a0b2-edfe42f09bc6)
![image](https://github.com/Anuken/Mindustry/assets/102400902/47804ebd-76d7-4491-b8ac-0fa0dd13f60d)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> new Pixmap([]),

Then don't do that? The game doesn't, and I see no reason to...
