### ISSUE TITLE
Env blocks decided to vanish

### ISSUE THREAD

**Issue by JniTrRny** [Anuken/Mindustry#8668]
**Platform**: Win10

**Build**: BE 24134

**Issue**: all blocks related to environment just decided to not appear/load at all.

![image](https://github.com/Anuken/Mindustry/assets/85090668/41cd7775-d98a-47d1-88ac-982e2347732d)

(no env blocks on the right menu)

**Steps to reproduce**: It's quite random actually, I was able to replicate it only 2 times on BE (but seems to be more common when in custom build though)
Open map editor and maybe if you're (un)lucky enough the bug will happen.

**Link(s) to mod(s) used**: No mod used.

**Save file**: Did not happen in-game. I could provide a save file of a corrupted map though if I could replicate it again.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
When you tried to place an environment block (by picking the existing one and place them)
[crash-report-06_03_2023_18_27_27.txt](https://github.com/Anuken/Mindustry/files/11642700/crash-report-06_03_2023_18_27_27.txt)

When you tried to edit in-game. (BE 24134)
[crash-report-06_03_2023_18_33_30.txt](https://github.com/Anuken/Mindustry/files/11642701/crash-report-06_03_2023_18_33_30.txt)

Also trying to place an env block, but this is from a custom build though.
[crash-report-06_02_2023_16_55_34.txt](https://github.com/Anuken/Mindustry/files/11642705/crash-report-06_02_2023_16_55_34.txt)

Another crash from custom build. Can't remember what I did, but it's related.
[crash-report-05_14_2023_20_49_46.txt](https://github.com/Anuken/Mindustry/files/11642710/crash-report-05_14_2023_20_49_46.txt)

Also from custom build, trying to do something to a... map with no tile? (This map is corrupted from the effect of this bug, probably not related idk)
[crash-report-05_14_2023_21_20_03.txt](https://github.com/Anuken/Mindustry/files/11642713/crash-report-05_14_2023_21_20_03.txt)

And also from custom build, trying to place a non-existing env block.
[crash-report-05_14_2023_21_21_07.txt](https://github.com/Anuken/Mindustry/files/11642714/crash-report-05_14_2023_21_21_07.txt)

Noteworthy: when this bug happened, the sandbox source blocks seems to be vanished too.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I've never been able to replicate this, and it makes no sense. Some of the crash logs you provide are complete nonsense, too - the last one in particular seems practically impossible unless you modified that exact code, or ran some weird script to mess up block ID order.
