### ISSUE TITLE
"whitelist remove" not removing player off of the whitelist

### ISSUE THREAD

**Issue by Weebed-Coder** [Anuken/Mindustry#8671]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)
Linux
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Server 144.3 on Java 11.0.18
**Issue**: *Explain your issue in detail.*
When running `whitelist remove`, it does not remove a UUID from the whitelist. Below is an image showing the issue.
![image](https://github.com/Anuken/Mindustry/assets/73402249/3e3ae1a1-99b2-4b96-a6fb-03082ae86c7d)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Download Mindustry server version 144.3 from https://anuke.itch.io/mindustry
2. Run server
3. Add a UUID to whitelist
4. Try to remove UUID from whitelist
5. Check whitelist

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
[mods.zip](https://github.com/Anuken/Mindustry/files/11645420/mods.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Weebed-Coder** [comment]
After some tinkering, I had realized that it is dependent on whether or not the whitelist config is enabled to begin with.

**Comment by Gadgetroch** [comment]
Hi,

I want to add something.
When whitelist is set to true, i can remove player from whitelist and empty the list.

But when i set whitelist to false, all the player list come back.
