### ISSUE TITLE
Crash at launch with offline mode in Steam

### ISSUE THREAD

**Issue by xtophyr** [Anuken/Mindustry#868]
**Platform**: macOS (10.14.6)

**Build**: Steam build 96

**Issue**: When steam is in offline mode, Mindustry seems to reliably crash on launch.

**Steps to reproduce**: launch steam in offline mode, launch Mindustry.  It crashes shortly after the window comes up.
[crash-report-10_24_2019_16_27_26.txt](https://github.com/Anuken/Mindustry/files/3769349/crash-report-10_24_2019_16_27_26.txt)
[crash-report-10_23_2019_17_53_51.txt](https://github.com/Anuken/Mindustry/files/3769350/crash-report-10_23_2019_17_53_51.txt)
[crash-report-10_23_2019_17_53_30.txt](https://github.com/Anuken/Mindustry/files/3769351/crash-report-10_23_2019_17_53_30.txt)
[crash-report-10_23_2019_17_50_29.txt](https://github.com/Anuken/Mindustry/files/3769352/crash-report-10_23_2019_17_50_29.txt)

The Arc stuff seems to line up with the backtrace, but the Mindustry stuff doesn't, so this may already be resolved.

**Comment by Anuken** [comment]
Fixed in master a while ago.
