### ISSUE TITLE
Can you add an option to hide the mouse pointer while hovering over any sort of message block.

### ISSUE THREAD

**Issue by stoltzld** [Anuken/Mindustry#8684]
When I'm trying to read data in message blocks, the mouse pointer often gets in the way of the first few lines.  Can there be an option to hide the mouse pointer when hovering over message blocks?

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/4309349e-227f-4cb7-996c-02f457f9f500)

**Comment by stoltzld** [comment]
A link would have been handy.  https://github.com/Anuken/Mindustry-Suggestions/issues
