### ISSUE TITLE
IOS cant type nextlines

### ISSUE THREAD

**Issue by Xaocsoul** [Anuken/Mindustry#8689]
Device
Device is IOS

build
Build is 144.2

issue
I’m on IOS and I can’t type nextlines in message blocks on multiplayer and single player and when I try to edit a message with them they get erased

Replication instructions
Just go on a multiplayer server on iOS and try to type next lines in a message block or edit messages with nextlines in 

Save
I tried uploading a save file im not sure if it actually uploaded though I’m sorry if it didn’t 

 

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
-  #[X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Xaocsoul** [comment]
Tried sending the save file again here

**Comment by Anuken** [comment]
Fixed
