### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by Desconhecidoz2** [Anuken/Mindustry#869]
**Android, LG K9**

**Build96**
**Issue: Estou tentando entrar em um servidor mas só da "Connection Closed", o mesmo acontece quando tento entrar em um jogo VIA LAN, ja tentei de tudo mas não sai esse BUG, um amigo meu está jogando comigo VIA LAN sendo que eu que estou hospedando, pois eu não consigo entrar em nenhum servidor mas meu amigo consegue**

**Steps to reproduce: estava tentando entrar no servidor do meu amigo VIA LAN quando isso ocorreu uns dias atrás, hoje tentei entrar em um servidor (mindustry.kr.) e ocorreu o problema de Connection Closed**

**Comment by Anuken** [comment]
I can't reproduce this issue. You most likely have some sort of problem with your network that prevents the game from connecting properly, or the servers don't like your connection. There isn't enough information to tell what exactly is going wrong, and too many possible issues that could be occurring.
