### ISSUE TITLE
Power Node Autolink

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8693]
**Platform**: *Windows 11/Windows server*

**Build**: *v144.3*

**Issue**: *Power node autolink isn't related to a player which has built the power node.*

**Steps to reproduce**: 
- Place a power node. A BlockBuildEndEvent will be fired where the builder is your unit.
- Place one more power node near the first. A BlockBuildEndEvent will be fired where the builder is again your unit. Also, if the power node was autolinked, a ConfigEvent will be fired, but the player in ConfigEvent will be null. Why?

**Link(s) to mod(s) used**: *Scheme-Size, but I don't think it matters.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Autolink is part of power node logic, that's just how the game works. The player never manually configures anything, they just place the block.
