### ISSUE TITLE
4.0 Plans

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#87]
This issue will be used to discuss and plan the feature to be added for 4.0.

*This is a general outline of planned features and should not be taken completely seriously.
Many features listed here are very over-scoped, and may very well be removed or pushed to a later release.*

Note: *The changes in this release will be major. All saves __will__ be wiped.*

## Core Gameplay
- Retire waves, sandbox and freebuild into one 'classic' mode with configurable options. Core mechanics stay (mostly) the same while in classic mode.
- New 'normal' mode (name not decided)
- This mode has a different map set, with two different sides to the map, with AI on one side and the player on the other
- AI is a collection of ships like the default Android ship, and builds structures and unit factories to destroy the player
- Game is won by destroying AI core(s)
- Core has very limited space and cannot accept ammo materials anymore
- Core has limited build range around it
- Multiple storage blocks can be built to transfer items to the core. They work like normal routers, but only transfer items to other storage blocks or the core.
- Multiple cores can be built, but require a lot of resources, more than the core can store at one time. These will extend the default build range.
- Different placing system: some (very high level) blocks can take a few seconds to build up, and they take resources from the core as time goes on. These can be built even if resources are initially lacking. Resources will be automatically refilled by storage blocks if you have them near your core.
- Possible fog-of-war

## Maps
- Terraforming blocks, destruction of terrain
- Save all normal map data as well as player blocks
- Chunk loading
- Extra large procedural maps?

## Environment
- Change water to be a separate layer and be animated w/ a shader
- Make shallow water passable but slow (with ripple effects)
- Change oil and lava to be passable as well, but with negative effects
- Lava should deal massive damage to a player when walking in it
- Oil should slow down the player and enemies walking through it
- Different variants for oil and lava blocks, as well as animations like for water
- More environmental block variants
- Skidding on ice floor, if possible
- Smoother block blending
- 'taller' blocks to fake elevation increase in certain areas
- Ice blocks
- Red stone block and floor
- Mossy stone block
- More grass types (burnt, brown, etc)
- Generally better environmental effects
- Random environmental events that affect the map, like meteorites or volcanoes (?)
- Prevent blocks from being placed in deep water

## Upgrades/equipment
- More weapons
- Weapon upgrade system
- Make weapons consume ammo
- Make players have an ammo or energy bar for weapons
- Mech and ship types: Android can only be flying types, PC can be both
- Add extra functionality to Android ship
- Make Android ship be visible
- Better flying animations and physics (e.g VTOL animations, hovering effect, better thrusters)
- Better sprites for current default bodies
- Different classes of bodies with different capabilities: powersuppliers, healers, mine-launchers, bomb-droppers, extra-heavy mechs, lava-resistant mechs, amphibious mechs, artillery mechs...

## Enemies
- Amphibious or lava-resistant units
- Floating (boat?) units
- Flying units that spawn off-map in swarms and bomb important structures, not necessarily focusing the core
- Dynamic spawnpoints that change often (not for 'classic' wave mode)
- Drop scrap resources that can be salvaged by drones and brought to storage

## Units
- Created by a wide variety of unit factories
- Not available in 'classic' mode
- Cannot get upgraded
- Drones that fly around and repair damaged blocks anywhere
- Standard 'grunt' ground units that attack enemy buildings
- Standard bomber flying units

## UI
- Minimap
- Advanced block info tool

## Turrets
- Completely remake turret tiers so that no two turrets are just 'direct upgrades': e.g. the two flamethowers, gattling, normal, double turret, shotgun
- Add knockback to higher tier turrets
- Many turrets should support different ammo types that modify how they shoot: basic stone turrets could be viable throughout the game for this reason
- Possible 'upgrading' of turrets through supplied items
- Change basic laser turret to either pierce enemies or shoot one energy orb _[targeting one enemy doesn't make sense]_
- Change gattling turret to slower burst-fire turret, change visuals on it
- Change or remove shotgun turret, make it shoot different types of bullets with more speed
- Guided missile launcher turret
- *Actual* railgun turret that looks nice
- Wide medium-range burst laser turret, similar to the beam weapon
- Long-range piercing laser turret
- Molten glass/iron turret
- Very high-knockback giant piercing shotgun that uses large shells and titanium
- Cryofluid turret to slow down enemies
- Lava turret to slow down enemies and set the ground on fire, can explode volatile materials

## Resources
- Silicon: used for electronics, lasers, any sort of unit production, advanced blocks
- Sand: intermediate material, used to extract silicon and make glass
- Glass: lasers, <???>
- Cryofluid: light blue artificial coolant liquid
- Plant matter mined from grass, used for oil production
- Many new optional ammo types for turrets

## Blocks
- Make reactor accept any form of coolant, including lava and oil: these will make it heat up instantly or blow up
- Fusion reactor multiblock
- Another form of unstable reactor, if possible
- Some form of sand digger to get sand from sand floor
- Grinder to turn stone into sand, uses power
- Cryofluid production block, creates cryofluid from water, sand and small amounts of titanium
- Rename crucible to 'alloy smelter' and make it 2x2
- Advanced version of smelter and alloy smelter that runs on power and smelts faster [2x2], uses sand to speed up process
- Rename dirium to something more fun to pronounce
- Oil drill: 2x2 or 3x3, mines dirt/sand blocks for oil, uses power
- Magma former: 2x2, converts stone to lava, uses power
- Melter: 1x1, extracts water from ice and stone, uses power
- Uranium centrifuge: extracts uranium from massive amounts of stone, uses power and water
- Item extractor: takes resources out of the core or storage units
- 2x2 routers (?) 
- Logic system
- Splitters
- Player/unit teleporter
- Dedicated spawnpoint block

## Block Function
- Items can be flammable and/or explosive
- If a block containing flammable/explosive items is destroyed or damaged, it may explode or catch fire depending on the volatility and amount of the materials inside it
- Some fluids can also be flammable. Oil reservoirs can be set on fire.
- Lava conduits set oil containers on fire
- Liquid system rewrite to allow for max pressure, after which the blocks explode
- Better liquid flow
- Liquid leakage effects: unsealed conduits will leak onto the ground
- Autotiling for blocks that rotate, like conduits and conveyors

## Optimization
- Multithreading using up multiple cores to handle entity updates
- Load only part of whole map into memory
- Stop clearing pathfinding cache every time it updates
- Have power blocks cache their target instead of calculating each frame

**Comment by dangranos** [comment]
Perhaps those closed issues could be reopened and combined under a single GitHub "Milestone" or "Project"?

**Comment by Anuken** [comment]
Moved to a [Trello](https://trello.com/b/aE2tcUwF/mindustry-40-plans) board.
