### ISSUE TITLE
File in wrong Folder

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#8701]
**Platform**:
Browser
**Issue**:
The phase conduit end is in another folder than the other parts of it.
![Image](https://github.com/Anuken/Mindustry/assets/108625654/4f2bed9f-e261-47e8-90a3-afd0e4a89f1f)
---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Please don't make issues for pointless nitpicks.
