### ISSUE TITLE
Drill Speed label is unreadable underneath Assember drone making it hard to find best spot

### ISSUE THREAD

**Issue by cmaas** [Anuken/Mindustry#8703]
**Platform**: `macOS 13.3.1`

**Build**: `144.3`

**Issue**: Text "Drill Speed X" is behind small drones of Ship Assembler and thus unreadable making it hard to find the spot with the best resource gathering. See screenshot:

![eruption-drill-label](https://github.com/Anuken/Mindustry/assets/6094364/937ab6be-d8ed-426c-a493-a3b729536454)

**Steps to reproduce**: Build a Ship Assembler, select Eruption Drill and try to find the best spot by moving it around a bit.

**Link(s) to mod(s) used**: None.

**Save file**: [eruption-drill-label.zip](https://github.com/Anuken/Mindustry/files/11718806/eruption-drill-label.zip)

**(Crash) logs**: Doesn't crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Planned block text is drawn as part of the planned blocks themselves, which are under units. Intentional.
