### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Estebiu** [Anuken/Mindustry#8705]
**Platform**: Linux
**Build**: 144.2
**Issue**: Doesn't work with wayland. 
**Steps to reproduce**: SDL_VIDEODRIVER=wayland, run the game
**Link(s) to mod(s) used**: None
**(Crash) logs**: 
´´´❯ mindustry
[W] Failed to initialize Discord RPC - you are likely using a JVM <16.
[E] arc.backend.sdl.SdlApplication$SdlError: wayland not available
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:226)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:111)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:35)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39) 
´´´

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

It's been already reported 2 years ago (#1393) but nothing has been done to address this issue.

**Comment by Anuken** [comment]
I have no plans to implement wayland support.

---

Update (18/2/2026): I have *attempted* an upgrade to SDL3, which was supposed to bring wayland support out of the box, but that [failed horribly](https://github.com/Anuken/Mindustry/issues/11657#issuecomment-3892489405). I will not be wasting any more time trying to implement support for Wayland; use XWayland.

**Comment by SachaTending** [comment]
just recompile sdl with wayland support

пн, 12 июн. 2023 г. в 20:38, Anuken ***@***.***>:

**Comment by tryedandcatched** [comment]
same

**Comment by dkgamer02ai** [comment]
> I have no plans to implement wayland support.

What is needed for wayland support , I am a developer and might be able to PR a fix or change, If known
