### ISSUE TITLE
1st wave contain 966 unit

### ISSUE THREAD

**Issue by kencingdisurga** [Anuken/Mindustry#8706]
**Platform**: `Android 29`

**Build**: `release build 144.3`

**Issue**: *Explain your issue in detail.* attacking sector, 1st wave contain 966 units of enemies from all tier (including 100+ tier 4 air units and 10+ guardians)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* run mindustry, attack sector 69

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/a4b41e0e-d75d-447e-9290-4285f09728e9)

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.

**Comment by kencingdisurga** [comment]
![Screenshot_20230613-101358_Mindustry](https://github.com/Anuken/Mindustry/assets/136408029/729b9ed1-f8ca-4442-a39a-8fcd3866e986)
![Screenshot_20230613-101409_Mindustry](https://github.com/Anuken/Mindustry/assets/136408029/a5389563-5a95-4a5e-b92c-24b299f358e7)

**Comment by Anuken** [comment]
Screenshots don't help. As the template says, attach the save/game data.
