### ISSUE TITLE
didn't unlock Exponential Reconstuctor after capturing Overgrowth 

### ISSUE THREAD

**Issue by k0vl** [Anuken/Mindustry#8708]
**Platform**: *The type of device you were playing on - Android/iOS/Mac/Windows/Linux* ("All" is NOT a platform!)

Android

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

144.3

**Issue**: *Explain your issue in detail.*

Exponential Reconstuctor should be unlocked after capturing Overgrowth, but it's still locked even though Overgrowth has been captured, abandoned, and recaptured.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Not sure. Failed to take Overgrowth several times, Fungal Pass was also attacked in the middle of it. I don't recall if anything was unlocked right after capturing Overgrowth, but it's currently locked and shown as (???) In tech tree.

I tried abandoning and recapturing Overgrowth, but it's still locked, so you may be able to reproduce the issue this way.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

[no-exponential.zip](https://github.com/Anuken/Mindustry/files/11735216/no-exponential.zip)

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
You don't have phase fabric researched or produced. Not a bug.
