### ISSUE TITLE
Canvas crash

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#8710]
**Platform**: *Android*

**Build**: *v144.3*

**Issue**: *Mindustry crashes on my android smartphone when I build 40+ canvases. Most of my friends have the same bug.

**Steps to reproduce**: *Join to any sandbox server. Build 40+ canvases with some images. Enjoy.*

**(Crash) logs**: 

Mindustry has crashed. How unfortunate.
Version: release build 144.1
OS: Linux xnull (aarch64)
Android API level: 31
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: newconsole:1.9

> Runtime: 'android.os.DeadSystemException'
ActivityClient.activityResumed: 55
ResumeActivityItem.postExecute: 63
TransactionExecutor.executeLifecycleState: 177
TransactionExecutor.execute: 97
ActivityThread$H.handleMessage: 2323
Handler.dispatchMessage: 106
Looper.loopOnce: 211
Looper.loop: 300
ActivityThread.main: 8279
RuntimeInit$MethodAndArgsCaller.run: 576
ZygoteInit.main: 1074
> DeadSystem
ActivityClient.activityResumed: 55
ResumeActivityItem.postExecute: 63
TransactionExecutor.executeLifecycleState: 177
TransactionExecutor.execute: 97
ActivityThread$H.handleMessage: 2323
Handler.dispatchMessage: 106
Looper.loopOnce: 211
Looper.loop: 300
ActivityThread.main: 8279
RuntimeInit$MethodAndArgsCaller.run: 576
ZygoteInit.main: 1074

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Darkness6030** [comment]
(We use Xiaomi with MediaTek and 4-6 GB ram. First the game freezes, then it crashes)

**Comment by Slotterleet** [comment]
~~dead system xd~~
