### ISSUE TITLE
Cursor Disappearance

### ISSUE THREAD

**Issue by Thebenjiball** [Anuken/Mindustry#8711]
Windows 10

Steam build 144.3

Cursor disappears, like, just becomes invisible. I have to re-load the game every time this happens.

It seems to just happen every time I go afk with the window opened. (just leave the cursor holding still onscreen for a while)

No mods.

This happens even in the main menu.

---

[X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**

[X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I can't reproduce this issue, and I see nothing that could cause it.
