### ISSUE TITLE
V145 crash while placing blocks

### ISSUE THREAD

**Issue by nekit508** [Anuken/Mindustry#8718]
**Platform**: Android
**Build**: 145
**Issue**: Error while placing conveyor bridge
**Steps to reproduce**: Place some conveyor bridges
**Link(s) to mod(s) used**: none
**Save file**: [sector-serpulo-86.zip](https://github.com/Anuken/Mindustry/files/11780979/sector-serpulo-86.zip)

**(Crash) logs**: 
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 145
OS: Linux xnull (armv8l)
Android API level: 30
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: 14
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: 2
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1581
GLSurfaceView$GLThread.run: 1280
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by camelStyleUser** [comment]
platform android which?

**Comment by mangblekok** [comment]
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 31
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: 14
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: 2
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1577
GLSurfaceView$GLThread.run: 1272


last log:
[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 640
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 31
