### ISSUE TITLE
Mindustry crashed when playing multiplayer.

### ISSUE THREAD

**Issue by Giahungdepzdaizdalai** [Anuken/Mindustry#8721]
**Platform**: Windowsx64

**Build**: v145

**Issue**: i just joined a server and it crashed

**Steps to reproduce**: I joined a server, placed some mender-projector, deleted it and it crashed.

**Link(s) to mod(s) used**: no mod

**Save file**: 
[crashreport_savefile.zip](https://github.com/Anuken/Mindustry/files/11781262/crashreport_savefile.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[crashreport.txt](https://github.com/Anuken/Mindustry/files/11781265/crashreport.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Giahungdepzdaizdalai** [comment]
my platform is windows11x64

**Comment by Anuken** [comment]
Likely same cause as #8724, crash log doesn't make sense. You're likely connected to an outdated server.
