### ISSUE TITLE
Unexpected crash issues

### ISSUE THREAD

**Issue by Illuminaty666** [Anuken/Mindustry#8722]
Platform - v145 Mobile Android

Issue
Mindustry is unexpectedly closing when the COPY button is tapped while there is structures planned out, but the tick hasn't been tapped yet. 

Steps to reproduce -
1. On mobile, place any block, but do not click the confirm button 

2. Press the copy button

3. Mindustry will close immediately 

Savefile not attached - (files will not attach for some reason idk why)

Crash logs also not attached - (files won't attach)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BalaM314** [comment]
Possibly the same issue as #8718 , cant tell for sure without the crash log

**Comment by Anuken** [comment]
Crash log required.
