### ISSUE TITLE
mindustry show weird thing.

### ISSUE THREAD

**Issue by Giahungdepzdaizdalai** [Anuken/Mindustry#8724]
**Platform**: Windows11x64

**Build**: version145

**Issue**: player name are broken[it show that: java.expection{player: name}=timothy(JS)] and some strange massage on the chat in multiplayer[it show that: Unknow config type: mindustry.Ai.UnitCommand$1; Unknow config type: mindustry.Ai.UnitCommand$2; Unknow config type: mindustry.Ai.UnitCommand$3]

**Steps to reproduce**: just build some air-factory

**Link(s) to mod(s) used**: no mods used
**Save file**: 
[report_2.zip](https://github.com/Anuken/Mindustry/files/11781515/report_2.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: 
[report_2.txt](https://github.com/Anuken/Mindustry/files/11781517/report_2.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Sounds like you're connecting to an outdated server. Not enough information to fix this issue.
