### ISSUE TITLE
Bug deselect

### ISSUE THREAD

**Issue by XgitsX** [Anuken/Mindustry#8725]
**Platform**: `Android 25`

**Build**: `release build 145`

**Issue**: *Explain your issue in detail.*
--- Deselecting after marking buildings = crash game. Any mobile device.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by XgitsX** [comment]
crash_1681055224670.txt

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 143
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: none (vanilla)

> NullPointer: 'Attempt to read from field 'mindustry.gen.Building mindustry.world.Tile.build' on a null object reference'
MinimapRenderer.realBlock: -1
MinimapRenderer.colorFor: 5
MinimapRenderer.updatePixel: 1
MinimapRenderer.update: 4
MinimapRenderer.lambda$new$3: -1
MinimapRenderer.$r8$lambda$7-D_-rxS3voJpgQeGXTxrZ4gJO8: -1
Settings$$ExternalSyntheticLambda1.run: -1
AndroidGraphics.onDrawFrame: 15
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1682611525016.txt

Mindustry has crashed. How unfortunate.
Version: release build 143
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5, multiplayernt:1.0, multiplayerntnt:1.0, test-utils:51

> NullPointer: 'Attempt to read from field 'mindustry.gen.Building mindustry.world.Tile.build' on a null object reference'
MinimapRenderer.realBlock: -1
MinimapRenderer.colorFor: 5
MinimapRenderer.updatePixel: 1
MinimapRenderer.update: 4
MinimapRenderer.lambda$new$3: -1
MinimapRenderer.$r8$lambda$7-D_-rxS3voJpgQeGXTxrZ4gJO8: -1
Settings$$ExternalSyntheticLambda1.run: -1
AndroidGraphics.onDrawFrame: 15
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1683635460321.txt

Mindustry has crashed. How unfortunate.
Version: release build 143
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: aimclient:1.0.0, extended-ui:0.76, miner-tools:1.7.5

> EcmaError: 'TypeError: Cannot call method "toString" of null (PluginBrowser#36)'
ScriptRuntime.constructError: 5
ScriptRuntime.constructError: 2
ScriptRuntime.typeError: -1
ScriptRuntime.typeError2: 2
ScriptRuntime.undefCallError: -1
ScriptRuntime.getPropFunctionAndThisHelper: 10
ScriptRuntime.getPropFunctionAndThis: 2
OptRuntime.callProp0: 1
PluginBrowser_46._c_anonymous_2: 36
PluginBrowser_46.call: -1
ArrowFunction.call: 2
OptRuntime.callName0: 3
Web_44._c_anonymous_3: 24
Web_44.call: -1
ArrowFunction.call: 2
OptRuntime.callProp0: 3
MainWindow_8._c_anonymous_40: 235
MainWindow_8.call: -1
OptRuntime.call1: -1
MainWindow_8._c_anonymous_27: 223
MainWindow_8.call: -1
OptRuntime.call1: -1
MainWindow_8._c_anonymous_31: 201
MainWindow_8.call: -1
ContextFactory.doTopCall: 1
ScriptRuntime.doTopCall: 7
MainWindow_8.call: -1
ArrowFunction.call: 2
InterfaceAdapter.invokeImpl: 20
InterfaceAdapter.lambda$invoke$0: -1
InterfaceAdapter.$r8$lambda$eCbvUJKud9uRuKkOr-KOpaMfYY8: -1
InterfaceAdapter$$ExternalSyntheticLambda0.run: -1
Context.call: 4
ContextFactory.call: -1
InterfaceAdapter.invoke: -1
VMBridge.lambda$newInterfaceProxy$0: 11
VMBridge.$r8$lambda$2rbCXLLvnIIB7GRsWozxBZ9kMPs: -1
VMBridge$$ExternalSyntheticLambda0.invoke: -1
Proxy.invoke: 813
$Proxy2.run: -1
Element.lambda$clicked$2: -1
Element.$r8$lambda$HTGgyzI_sft57MMc4a-IcKQNKts: -1
Events$$ExternalSyntheticLambda0.get: -1
Element$4.clicked: -1
ClickListener.touchUp: 10
InputListener.handle: 11
Scene.touchUp: 20
InputMultiplexer.touchUp: 3
AndroidInput.processEvents: 19
AndroidGraphics.onDrawFrame: 16
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687090654120.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687093937458.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687094533853.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687095396678.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687095814805.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: extended-ui:0.76, miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687106403556.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687106432187.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: miner-tools:1.7.5

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687106489501.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: none (vanilla)

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259

crash_1687106947000.txt

Mindustry has crashed. How unfortunate.
Version: release build 145
OS: Linux xnull (aarch64)
Android API level: 25
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: none (vanilla)

> NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference'
MobileInput.drawOverSelect: 16
OverlayRenderer.drawTop: 69
Renderer$$ExternalSyntheticLambda5.run: -1
SortedSpriteBatch.flushRequests: 12
SortedSpriteBatch.flush: 1
Draw.flush: -1
Renderer.draw: 46
Renderer.update: 44
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259


last log:
[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 505
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 25
[I] [RAM] Available: 192.0 MB
[I] [Mindustry] Version: 145
[I] Total time to load: 11435ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 44 community servers.
[I] [AndroidGraphics] [pause]

**Comment by Anuken** [comment]
Duplicate, already reported.
