### ISSUE TITLE
Conduit Bottom Texture Not Working Right

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#8726]
**Platform**:
Android
**Build**:
145
**Issue**:
When I try to change the conduit bottom 1 texture, it won't show it as it should be. I checked 4 times that it is the right size and also tried to increase the size but it results in the same error.
![bug.png](https://github.com/Anuken/Mindustry/assets/108625654/f2c2b974-678a-4480-829a-cb41e7c90b15)
**Steps to reproduce**:
- Create a new mod
- Put a "conduit-bottom-1" file in the "sprites-override" folder that matches the "conduit-top-1" texture
- Run the game

**Link(s) to mod(s) used**:
[mod.zip](https://github.com/Anuken/Mindustry/files/11782317/Simpledustry.DevBuild.zip)
**Save file**:
[save.zip](https://github.com/Anuken/Mindustry/files/11782328/save.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Not a bug, they are padded that way to avoid the liquid sprite sticking out for curved vanilla conduits.

**Comment by Yoru-Kitsune** [comment]
Is there a way to remove that in a mod? @Anuken

**Comment by Anuken** [comment]
Not without rewriting the conduit drawing code, but I can add a field for it.

**Comment by Yoru-Kitsune** [comment]
So what exactly do I need to do?
What folders do I need? what file do I need to change? what line?
(sorry for bothering you but else I would have to change 109 sprites because of 1 line ._.)
@Anuken

**Comment by Anuken** [comment]
Set padCorners = false for conduits you resprite

**Comment by Yoru-Kitsune** [comment]
@Anuken it got kind of worse...
![Screenshot_20230619_164528_Mindustry BE](https://github.com/Anuken/Mindustry/assets/108625654/5fb04724-beff-4f8c-a6f9-aed3b2b4ee4d)

**Comment by Yoru-Kitsune** [comment]
I saw it and it is fixed now.
Thanks you for taking time to fix it.
I also wanted to mention thanks for that awsome game!
