### ISSUE TITLE
Build makes my game close

### ISSUE THREAD

**Issue by BelicusBr** [Anuken/Mindustry#8730]
**Platform**: Android

**Build** :145

**bug description**
when I was building a mining company on top of a sand plot, at the time I had it selected I didn't even confirm it to build and when I went to deselect it the game closed by itself, this happens with any construction.

**Crash log(crash_1687194319186.txt)**
Mindustry has crashed. How unfortunate. Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md Version: release build 145 OS: Linux xnull (armv7l) Android API level: 28 Java Version: 0 Runtime Available Memory: 128mb Cores: 4 Mods: none (vanilla) > NullPointer: 'Attempt to invoke virtual method 'int mindustry.world.Block.planRotation(int)' on a null object reference' MobileInput.drawOverSelect: 16 OverlayRenderer.drawTop: 69 Renderer$$ExternalSyntheticLambda5.run: 14 SortedSpriteBatch.flushRequests: 12 SortedSpriteBatch.flush: 1 Draw.flush: 2 Renderer.draw: 46 Renderer.update: 44 ApplicationCore.update: 2 ClientLauncher.update: 17 AndroidGraphics.onDrawFrame: 22 GLSurfaceView$GLThread.guardedRun: 1575 GLSurfaceView$GLThread.run: 1270

**Comment by Anuken** [comment]
Duplicate, already fixed.
