### ISSUE TITLE
1st wave sector 69 966 enemies (with save file zip)

### ISSUE THREAD

**Issue by kencingdisurga** [Anuken/Mindustry#8733]
**Platform**: `Android 30`

**Build**: `release build 145.1`

**Issue**: *Explain your issue in detail.* attacking sector 69, 1st wave contain 966 enemies from tier 1 to 5, there is 100+ guardian attacking on 1st wave
![Screenshot_20230613-090840_Mindustry](https://github.com/Anuken/Mindustry/assets/136408029/ae9cd967-4450-4aef-8a4c-275b48b7dea4)
The last time i forgot to upload save file sorry

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* attack sector 69, wait till 1st wave arrive

**Link(s) to mod(s) used**: `none`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
[966 unit wave 1.zip](https://github.com/Anuken/Mindustry/files/11802388/966.unit.wave.1.zip)

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
(The root cause is not really fixed, but at least it should be consistently reproducible if it happens in another sector)

**Comment by kencingdisurga** [comment]
Wow thank u anuke, the problem has been solve 👍
