### ISSUE TITLE
BOSD results in loss of resorceis and round progress

### ISSUE THREAD

**Issue by Goontnt** [Anuken/Mindustry#8737]
### Platforms

Windows

### Build

145.1

### Issue

My computer blue screaned and on the secter i was captureing all my resorces were set to 0 and the round number was reset to 1, but the buildings stayed intacted

### Steps to reproduce

1. go to a secter thats uncaptured
2. triger a BOSD
3. all resorces and round number reset

### Mods used

frozen farlands https://github.com/zielonytrojkat/frozen-farlands

### Save file

file too big, goog drive link
https://drive.google.com/file/d/1avvg7t58WRb5WtmXu7gWENPEydKM1lbE/view?usp=sharing

### (Crash) logs

"no crash logs found" - game

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Slotterleet** [comment]
A BSOD appears whenever an issue with the OS/computer appears, it probably doesn't have to do anything with the game itself.
In short, BSOD = an OS crash, the game just had no time to save.
Could've at least, I dunno, show a BSOD code next time?

**Comment by TagGamer555** [comment]
How the heck the game is supposed to save something when system triggers BSOD?

**Comment by Anuken** [comment]
Won't fix - it's an issue with your computer.
