### ISSUE TITLE
Json Planets ignore defaultCore and launch loadout.

### ISSUE THREAD

**Issue by Fresh791** [Anuken/Mindustry#8738]
### Platforms

Windows

### Build

145.1

### Issue

Json planets/sectors ignore the defaultCore set and also the launch loadout chosen by the player.

For example, if the planet has the defaultCore set to Core: Shard and the player launches to the first sector on said planet, the launch happens with a Core: Nucleus instead.

Likewise, if the player has finished a sector on a json planet and choose, say, Core: Foundation and a launch loadout of, say, 1200 copper, they launch with a Shard and 200 copper instead.

I am guessing that the launch information doesn't get stored so it defaults back to Shard and 200 copper. 

This ruins json planet mods since it also means that for mods like my Asthosus, the player launches with a Nucleus to the first map instead with the designated core from the mod. 

### Steps to reproduce

Install a mod that has a json planet and at least one sector preset on said planet. Launch to it and it will launch with a Nucleus core instead of the designated defaultCore set in the planet's json file.

### Mods used

[Asthosus](https://github.com/Fresh791/asthosus/tree/main)
[Fading Revelations](https://github.com/Fresh791/Fading-Revelations)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by 3Snake3** [comment]
You must create a schematic with your own core, then you'll be able to launch to sectors with mod's core

**Comment by Fresh791** [comment]
I did that.

**Comment by Fresh791** [comment]
I have found the issue though.
