### ISSUE TITLE
The loaded mod cannot be deleted. Specifically, after clicking the delete, you are prompted to delete successfully, but when you return to the main interface, you enter the module and find that the mod still exists.

### ISSUE THREAD

**Issue by chancy7** [Anuken/Mindustry#874]
**Platform**: (Android/iOS/Mac/Windows/Linux)

**Build**: (The build number under the title in the main menu. Required.)

**Issue**: (Explain your issue in detail.)

**Steps to reproduce**: (How you happened across the issue, and what you were doing at the time.)

**Comment by Anuken** [comment]
Use the issue template.
