### ISSUE TITLE
Connection terminated when trying to control too many units on a multiplayer server

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8742]
### Platforms

Windows, Android

### Build

145.1

### Issue

Same title.

### Steps to reproduce

https://github.com/Anuken/Mindustry/assets/44261958/799c5cd6-7646-4e70-a3cf-cb908380fc4e

1. Spawn too many units
2. Select units
3. try to move

### Mods used

Vanilla.

### Save file

Not required because it can reproduce any platform.

### (Crash) logs

No errors. server, client too.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Kieaer** [comment]
The video is just an __extreme__ example.
This often occurs in attack maps that require a lot of units.

**Comment by camelStyleUser** [comment]
~~save file saves the map youre playing on with full game state and is required if its in-game~~

**Comment by camelStyleUser** [comment]
and did you see that crash is in brackets?that means you also can and should send non-crash logs

**Comment by Kieaer** [comment]
> and did you see that crash is in brackets?that means you also can and should send non-crash logs

No errors. see video

**Comment by camelStyleUser** [comment]
no errors doesnt mean "i wont send logs"

**Comment by rekokoro** [comment]
Isn't that just a "too many interactions"
