### ISSUE TITLE
Game crashes when attempting to edit Message block

### ISSUE THREAD

**Issue by VictorysHerald** [Anuken/Mindustry#8745]
### Platforms

iOS

### Build

145.1

### Issue

Whenever I attempt to edit the text in Message block, game crashes (however there is no pop up about crash when opening the game again). The Message block can be empty or already with text. This bug occurs both in campaign and custom games. I didn't find any specific dependency.

### Steps to reproduce

1. Place or find an already existing Message block
2. Click on the block
3. Click edit button

### Save file

[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/11835392/mindustry-data-export.zip)

### (Crash) logs

[logs.txt](https://github.com/Anuken/Mindustry/files/11835408/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I can't reproduce this on my devices, and the log doesn't contain any crashes. This will force me to revert the multiline text field changes.
