### ISSUE TITLE
Servers not working on my device

### ISSUE THREAD

**Issue by CallMeSirEntertainment** [Anuken/Mindustry#8750]
### Platforms

Android

### Build

145.1

### Issue

I am an Android user and I can not join any servers. I tried uninstalling, but it didn't work. 

### Steps to reproduce

It seemed to happen after I completed a sandbox match. 

### Mods used

I did have the "AutoTranslate" mod installed, but I do not think it caused this issue. 

### Save file

[my game i guess.zip](https://github.com/Anuken/Mindustry/files/11854313/my.game.i.guess.zip)

### (Crash) logs

I am not reporting a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
do you see that (Crash) is in brackets?you can and should give last_log.txt

**Comment by Anuken** [comment]
No logs or screenshots attached. "I cannot" does not give any insight on the issue whatsoever.

**Comment by CallMeSirEntertainmentYT** [comment]
Bro this man really took my username.
