### ISSUE TITLE
Unable to change core shard team sprite

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#8751]
### Platforms

Android

### Build

145.1

### Issue

Unable to change the "core shard team" file with mods
![screenshot](https://github.com/Anuken/Mindustry/assets/108625654/1bcfef81-443d-4cf0-bb3f-389237401582)

### Steps to reproduce

1. Create a mod
2. Add a core-shard-team file
3. Run the game with the mod

### Mods used

[mod.zip](https://github.com/Anuken/Mindustry/files/11858288/Simpledustry.DevBuild.zip)

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/11858303/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You need team-specific sprites.

![image](https://github.com/Anuken/Mindustry/assets/10100000/30e1603f-a22c-4851-8381-ade24e7b9eba)

---

For mod help, you should be using the Discord. This is generally not the right place to report "my mod does not work"-type problems, unless you are absolutely certain that the game is doing something wrong.

**Comment by Slotterleet** [comment]
> You need team-specific sprites.
> 
> ![image](https://user-images.githubusercontent.com/10100000/248515501-30e1603f-a22c-4851-8381-ade24e7b9eba.png)

This sounds pretty stupid IMHO, since there are 256 whole teams in the game, and this means just copypaste the same sprite 255 more times in a texture pack.

**Comment by Yoru-Kitsune** [comment]
> This sounds pretty stupid IMHO, since there are 256 whole teams in the game, and this means just copypaste the same sprite 255 more times in a texture pack.

Not just that... there are 6 or 7 cores and that are around 2000 different images...

**Comment by Anuken** [comment]
> This sounds pretty stupid IMHO, since there are 256 whole teams in the game, and this means just copypaste the same sprite 255 more times in a texture pack.

There are 4 sprites in that screenshot, not 256. There's no good alternative to this; the standard team sprites look awful when simply tinted (they are separate for a reason, look at the shading), using a palette shader is expensive, and splitting it into 3 colored sprites is 3x the drawing and annoying to manage.
