### ISSUE TITLE
Fps dropped severely after a certain number of blocks when planning to place

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#8752]
### Platforms

Windows

### Build

145.1

### Issue

https://github.com/Anuken/Mindustry/assets/44261958/8afe433e-3e50-45da-9f64-c8aca48650e7

### Steps to reproduce

See video.

### Mods used

Vanilla

### Save file

Not required

### (Crash) logs

No crash issue.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug. Conveyor autotiling is just slow, and there's absolutely no reason to have that many conveyors planned.
