### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FR1782** [Anuken/Mindustry#8758]
### Platforms

Windows

### Build

145.1

### Issue

In a campaign, I couldn't enter my sector (**crashed immediately**), after I copied data from android

### Steps to reproduce

initially, I wanted to move my game data from **Android to Windows**, and when it was done I couldn't enter my sector (**crashed immediately**), I don't think it's because I'm using a mods

### Mods used

informatis:1.8.1, shemepacbyobsidian:1.2, time-control:0.2, ui_lib:4.18.0

### Save file

[MindV3.zip](https://github.com/Anuken/Mindustry/files/11861423/MindV3.zip)
![Cuplikan layar 2023-06-26 073459](https://github.com/Anuken/Mindustry/assets/54733993/f1a5db87-00d9-4468-b2e0-dcf030c088cb)

### (Crash) logs

[crash-report-06_26_2023_07_17_12.txt](https://github.com/Anuken/Mindustry/files/11861425/crash-report-06_26_2023_07_17_12.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash is caused by informatis.

**Comment by FR1782** [comment]
how do I fix it?

**Comment by Anuken** [comment]
Disable informatis in your mods.
