### ISSUE TITLE
Mods sprite and material mixup

### ISSUE THREAD

**Issue by Yoloskeet** [Anuken/Mindustry#876]
**Platform**: (Android)

**Build**: (5.0 b97)

**Issue**: (When loading a save with mods the materials get swapped and sprites seem to change)

**Steps to reproduce**: (I was playing a mod and saved it, then returned later and it happened. Not sure how you could reproduce however, I do have screenshots.)

**Comment by Anuken** [comment]
Can't reproduce this.
