### ISSUE TITLE
Ugly Loading bar with small bug

### ISSUE THREAD

**Issue by mahdiyadiilavi1** [Anuken/Mindustry#8769]
### Platforms

Windows

### Build

From V6 to 145.1

### Issue

there is bug in [here](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/fragments/LoadingFragment.java)
that make game ugly. because when you load something, loading bar starts at 5% and ends at 100%
but it should start at 0% right?
this can be solved by moving starting position to left a little bit, and fixing visibility of it ofc.

### Steps to reproduce

nothing, it's in game a while

### Mods used

none of mods interact with this issue

### Save file

![test](https://github.com/Anuken/Mindustry/assets/83725163/b0c7ade2-beec-490f-885f-8b1c07af9b52)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by mahdiyadiilavi1** [comment]
Sorry this also is in v145.2

**Comment by Anuken** [comment]
> Steps to reproduce
nothing, it's in game a while

Not useful. "Nothing" is not a step to reproduce. The code linked is generic and related to loading screens in general, while the images you linked look like the BE update dialog, which is unrelated.
