### ISSUE TITLE
Mod loading problem

### ISSUE THREAD

**Issue by chancy7** [Anuken/Mindustry#877]
**Platform**:Windows

**Build**:steam build 97

**Issue**: I tried to delete the loaded mod, but failed.
When I clicked the delete key, the mod was gone, but after I quit the mod project, I reentered the mod project and found that the mod still existed, and when I went to the folder to delete it, it disappeared.

**Steps to reproduce**: When I was going to test my modified mod, to delete the original mod and load the new mod, I was prompted cannot to load the same mod. My English is not good, the original meaning may refer to this.
Error:A mod with the name 'example-mod' is already imported.

**Comment by Anuken** [comment]
How did you get the mod?

**Comment by chancy7** [comment]
I get it from mindustry:V97-mods-Import Github Mod.
I just changed the name of the item, the unit, etc.




------------------ 原始邮件 ------------------
发件人: "Anuken"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 晚上9:31
收件人: "Anuken/Mindustry"<Mindustry@noreply.github.com>;
抄送: "chancy"<1620048417@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Anuken/Mindustry] Mod loading problem (#877)




How did you get the mod?

**Comment by chancy7** [comment]
I get it from mindustry:V97-mods-Import Github Mod.
I just changed the name of the item, the unit, etc
