### ISSUE TITLE
Split empty planet

### ISSUE THREAD

**Issue by Titanssin1** [Anuken/Mindustry#8773]
### Platforms

Android

### Build

Release 145.1

### Issue

Entered on Split and as soon as the animation finished I quit the game. Hours later I came back to find a red planet with black minimap and only the HUB available 

![Screenshot_20230628_092441_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/77973678/98378cdc-3f70-4b64-a867-a5a0097854ed)

### Steps to reproduce

Quit the game as soon as the animation is finished in Split 

### Mods used

None

### Save file

Split 
[uo.zip](https://github.com/Anuken/Mindustry/files/11895566/uo.zip)

### (Crash) logs

GitHub won't let me copy the file but this is the whole log:

last log:
[I] [GL] Version: GLES 3.2.0 / ARM / Mali-G76
[I] [GL] Max texture size: 8192
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 29
[I] [RAM] Available: 384.0 MB
[I] [Mindustry] Version: 145.1
[I] Total time to load: 1652ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 45 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You panned  your camera away. Pan back to the middle.
