### ISSUE TITLE
i get a black screen and it kicks me out read description i use chrome book so android correct me if i am wrong 

### ISSUE THREAD

**Issue by 2125879** [Anuken/Mindustry#8775]
### Platforms

Android

### Build

143.1 i belive its not clear or i am blind 

### Issue

i play on a Chromebook and i have had this issue before but when i reinstall a mod it duplicates the mod and dosen't allow me to play it happned once before with the mode sapphirum but now with fading revlations. the game relods after the mod is reinstalled but it freezes at the loading screen and stops it will evevtully kick me out with a black screen. I tried 8 times and no luck. 
------Also it may be just to many mods but the loading screen freezes for a little bit. hitting f5 fixes it most of the time or it will unfreee after about two minutes 
   I would like mod optimizing on android or just somthing to fix this I am no a coder but would like to learn. so if some gae recoding on my end is required i would like instructions on how todo so.  but if the optimizer fo mods is no somthing you can do i just ask you fix this issue as of currently i cant play and may delete and restart game. please fix this 

### Steps to reproduce

1/2 issues 
dowload these mods 
relod the game and wait it will freeze and stop for about a minute 
to get it to lead one of two options can fix it or it goes black and kicks you out 
1 you press f5 a couple time's and the game loads 
2 you wait about two minutes and with luck it unfrezzez and loads 
3 the sreen unfreezez and goes black 
       2nd issue 
1 reinstall mod 
2it reloads 
3reopen game 
4game freezes 
![Screenshot 2023-06-28 4 38 06 PM](https://github.com/Anuken/Mindustry/assets/138069888/f6c5ca1a-bc42-4c5e-b3f9-bd3699155397)

### Mods used

i have downloaded the fading Revelations, mindustrinity, unlimited armaments, Sapphirium, MultiCrafterLib, project-oblivion, autodrill, Compress-this, Nucleardustry, Mindustrinity, spore-biomechs

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is not a vanilla issue, and there are way too many mods involved there for me to reasonably test individually. This is either a bug with the mods, or you simply have too many mods.

**Comment by 2125879** [comment]
thankyou
