### ISSUE TITLE
Unable to unload a tank/mech from the Payload conveyor (after transporting via Payload Mass Driver)

### ISSUE THREAD

**Issue by crysman** [Anuken/Mindustry#8781]
### Platforms

Linux

### Build

145.1

### Issue

Mechs are just stuck there :(

![image](https://github.com/Anuken/Mindustry/assets/5269350/a3d35db5-ee95-4c34-8c39-93c2afac2811)

I have tried both the Unloader and/or the Payload Conveyor, no luck.

### Steps to reproduce

transfer a unit via the payload and try to unload it somehow

### Save file

[unloaderbug.zip](https://github.com/Anuken/Mindustry/files/11916337/unloaderbug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug, you reached the unit cap.

**Comment by Anuken** [comment]
You don't unload them and there is no bug, *you have reached the unit cap.* If you mistakenly built too many units on one side, abandon and restart the mission.

**Comment by crysman** [comment]
I really enjoy your work and the game, but this is not a proper solution. It is against logic - why could you not unload already built units just because unit cap is reached? What is the logic behind this?
You might say "_I will not consider fixing this bug_", OK, fair enough, your project. But do not say it is not a bug without actually explaining the logic behind it @Anuken - please reconsider this. I would rather call it **_known issue_** rather than "not a bug".
Is there a way to kill some of my units?

**Comment by Anuken** [comment]
Yes, use a deconstructor - which you probably have not unlocked yet.

This is **not** in any way a "bug" or "known issue", and you are the first one to consider it as such despite it being in the game for *years*.

Cores have a unit cap. You may continue building units past that cap **for use in upgrading or as materials**, *but you cannot release them*, because that would make the active unit count go over the cap. There's nothing else to explain, that's just how it works and I have no intention of changing it.

**Comment by crysman** [comment]
OK, I got the point. If you were able to have units on conveyors and then unload them, you would effectively cheat, having a "conveyor buffer" full of units. I would suggest changing the mechanics in such a way that the cap would limit **producing** a unit (so it would not pop out anywhere in the first place) - but...
Then you wrote you may use units as materials... whoops, OK, I have not known that (its maybe later in campaign) - so now it's clear why you were so resistant. Thanks for the dialogue.

Anyways, this mission should be fixed somehow, here are some ideas:

a) make the hints (instrucions text) clear so the player should avoid producing units in the first (left) base, or
b) include a way to destroy own units in this mission, or
c) <some other idea?>
