### ISSUE TITLE
Animated PNG glitching

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#8788]
### Platforms

Android

### Build

BE 24233

### Issue

When you try to upload an animated png file in mods the texture is weirdly shown
![Screenshot](https://github.com/Anuken/Mindustry/assets/108625654/d7a40196-7b40-4181-b9b9-f71e69d9bf6e)

### Steps to reproduce

1. Create a mod
2. Put in an animated PNG file in it
3. Run the game

### Mods used

[mod.zip](https://github.com/Anuken/Mindustry/files/11934450/Craftdustry.DevBuild.zip)

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/11934464/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BasedUser** [comment]
This issue is related with your textures themselves. Mindustry textures are 32x32 per tile, whereas for example, the texture for `molten-slag` is 250x250.

**Comment by Yoru-Kitsune** [comment]
Ohh thanks I forgot about that... sr
