### ISSUE TITLE
Siege turbine runs without vent issue

### ISSUE THREAD

**Issue by bluegreensea** [Anuken/Mindustry#8789]
### Platforms

Linux

### Build

BE 24236

### Issue

In Siege, at the first outpost base, some machines run without vents

https://github.com/Anuken/Mindustry/assets/35960465/75da3f88-0a7c-4a33-829e-275fa3dec519

### Steps to reproduce

1. Open Siege map
2. Goto nearest enemy base
3. Break some machines and it doesn't have a needed vent

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by stacktrace-error** [comment]
they're probably not even functional despite the spinning

![IMG_20230703_103644](https://github.com/Anuken/Mindustry/assets/89076920/72cbc178-904a-4ab0-8df0-83a0eff92b74)
placed on regular tiles, still spins, but doesn't produce
