### ISSUE TITLE
In ground zero,one of mission is build 6 copper wall,but no wall to make it!

### ISSUE THREAD

**Issue by Aminpro001** [Anuken/Mindustry#8791]
### Platforms

Android

### Build

Last version on 3 junevri 2023

### Issue

I'm in training ground!

### Steps to reproduce

I'm new player

### Save file

![Screenshot_۲۰۲۳۰۷۰۳-۲۰۵۸۳۲](https://github.com/Anuken/Mindustry/assets/138518292/b870384a-f2e2-4312-9d4a-e3e6df44cf49)
，These is bug!

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
this is not a bug. rather this is a you problem.
# research the copper wall you stoo-

**Comment by camelStyleUser** [comment]
~~since when stupidity of the people is considered a bug?~~

**Comment by camelStyleUser** [comment]
> ## Steps to reproduce
> I'm new player

\*dies of death\*

**Comment by camelStyleUser** [comment]
people cant even get version of their game now even

**Comment by Lime712** [comment]
this isn't a bug, this a skill issue
