### ISSUE TITLE
i cant launch on the next sector

### ISSUE THREAD

**Issue by 1Gvand** [Anuken/Mindustry#8793]
### Platforms

Windows

### Build

145.1

### Issue

idk what it is bug or question. how can i launch sector on Ravine from Lake on Erekir planet . it need Tungsten but it's not on the lake sector

### Steps to reproduce

![image](https://github.com/Anuken/Mindustry/assets/95881832/9da65693-c142-4613-889a-d0804317f7d2)
I just went through the available levels

### Mods used

nothing

### Save file

![image](https://github.com/Anuken/Mindustry/assets/95881832/2b78512c-a738-4fdb-8f47-6fe1bd6e1ff6)
![image](https://github.com/Anuken/Mindustry/assets/95881832/0869d4a8-5ddb-4bb8-b93f-f2961acca1a1)
![image](https://github.com/Anuken/Mindustry/assets/95881832/c2a475f3-2a28-4852-8ce1-c0631f3a92e7)
![image](https://github.com/Anuken/Mindustry/assets/95881832/9fa502f3-67af-4ec7-a148-17e75f605eec)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by 1Gvand** [comment]
i know 2 languages RU and EN

**Comment by BalaM314** [comment]
Lake doesn't have any tungsten, so launch from a different sector. (Go to one with tungsten, then try to launch)

**Comment by 1Gvand** [comment]
HOW

**Comment by 1Gvand** [comment]
> Lake doesn't have any tungsten, so launch from a different sector. (Go to one with tungsten, then try to launch)

WHERE IS THE BUTTON

**Comment by 3Snake3** [comment]
> > Lake doesn't have any tungsten, so launch from a different sector. (Go to one with tungsten, then try to launch)
> 
> WHERE IS THE BUTTON
> 

You have to go to the sector with tungsten and from there start landing on another sector that requires tungsten.

**Comment by 3Snake3** [comment]
You don't know how to switch between sectors?._.

**Comment by 1Gvand** [comment]
> You don't know how to switch between sectors?._.

YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES

**Comment by camelStyleUser** [comment]
HOW DID YOU LAND ON LAKE THEN?

**Comment by 1Gvand** [comment]
> HOW DID YOU LAND ON LAKE THEN?

pls explain, i only see that it automatically choose sector

**Comment by 3Snake3** [comment]
> 
> 
> > HOW DID YOU LAND ON LAKE THEN?
> 
> pls explain, i only see that it automatically choose sector, PLEASE PLEASE PLEASE PLEASE

Go to the sector where tungsten is present, then click on this button (the first screen), then on the Planet Map, then you have to select the sector where you are going to land, press Launch, then Launch again and that's it...![Screenshot_2023-07-09-11-09-56-167_com.miui.gallery.jpg](https://github.com/Anuken/Mindustry/assets/83782383/49cf699a-5c51-458b-a619-ddc654045d30)

![Screenshot_2023-07-09-11-05-06-016_io.anuke.mindustry.jpg](https://github.com/Anuken/Mindustry/assets/83782383/f351181a-1d69-4bad-8910-9e454d7089a8)

![Screenshot_2023-07-09-11-05-28-099_io.anuke.mindustry.jpg](https://github.com/Anuken/Mindustry/assets/83782383/6212910a-55a3-4b6b-9ad0-03ca35442c46)

![Screenshot_2023-07-09-11-05-31-747_io.anuke.mindustry.jpg](https://github.com/Anuken/Mindustry/assets/83782383/1befe75e-ba48-42d7-8d85-74dc61fd257f)

**Comment by 1Gvand** [comment]
WTF WOW THX YOU

> > > HOW DID YOU LAND ON LAKE THEN?
> > 
> > 
> > pls explain, i only see that it automatically choose sector, PLEASE PLEASE PLEASE PLEASE
> 
> Go to the sector where tungsten is present, then click on this button (the first screen), then on the Planet Map, then you have to select the sector where you are going to land, press Launch, then Launch again and that's it...![Screenshot_2023-07-09-11-09-56-167_com.miui.gallery.jpg](https://user-images.githubusercontent.com/83782383/252123763-49cf699a-5c51-458b-a619-ddc654045d30.jpg)
> 
> ![Screenshot_2023-07-09-11-05-06-016_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/83782383/252123769-f351181a-1d69-4bad-8910-9e454d7089a8.jpg)
> 
> ![Screenshot_2023-07-09-11-05-28-099_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/83782383/252123780-6212910a-55a3-4b6b-9ad0-03ca35442c46.jpg)
> 
> ![Screenshot_2023-07-09-11-05-31-747_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/83782383/252123782-1befe75e-ba48-42d7-8d85-74dc61fd257f.jpg)
