### ISSUE TITLE
Naval pathfinding with logic still has the same bug as the old one

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry#8794]
### Platforms

Windows

### Build

Foos Client 145.1

### Issue

Using the pathfind function on naval units still causes them to freak out, just like with the old pathfind function
May or may not be the same bug

### Steps to reproduce

[Load up map (Has to be .ZIP bcus github is gay)](https://github.com/Anuken/Mindustry/files/11941282/naval.pathfind.stroke.zip)

Let risso build, 
risso has massive stroke and can't pathfind to the selected coordinates even though there's a very obvious path to it

### Mods used

Foos Client

### Save file

[Custom Map (Has to be .ZIP bcus github is gay)](https://github.com/Anuken/Mindustry/files/11941282/naval.pathfind.stroke.zip)

### (Crash) logs

(Crash) logs

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
~~shouldnt you be reporting this in Foo(l)'s client discord?~~

**Comment by 3Circle** [comment]
Foos client is just vanilla mindustry but with a bunch of QOL features, I very highly doubt the issue is just foos client

**Comment by BalaM314** [comment]
I assume you mean the vanilla pathfinding(command mode) and not foos pathing(green and blue line). If so, yes, this is a vanilla issue.

**Comment by 3Circle** [comment]
Yeah, the vanilla logic pathfinding (from logic, not command mode)
