### ISSUE TITLE
"Swish" Breaks All Game Sounds

### ISSUE THREAD

**Issue by Otamamori917** [Anuken/Mindustry#8797]
### Platforms

Windows

### Build

145.1

### Issue

The [Swish](https://github.com/Anuken/Mindustry/blob/master/core/assets/sounds/swish.ogg) Sound breaks all Other Mindustry Sounds when placed as a `despawnSound`
All sound break until you go back to main menu and it back to normal unless you fire the bullet with 
`despawnSound: swish`/`despawnSound = Sound.swish;`

### Steps to reproduce

I set a bullet's `despawnSound` to swish and it breaks all sounds

Test yourself with [Axthrix-Modded2-main.zip](https://github.com/Anuken/Mindustry/files/11963598/Axthrix-Modded2-main.zip)
Spawn Argyros _(in save file below the core in map aka Lucid will spawn Argyros)_ and shoot for awhile it will break all sound until you leave to main menu

### Mods used

https://github.com/Otamamori917/Axthrix-Modded2 _(mod file containing bug is above this!)_
https://github.com/liplum/MultiCrafterLib _(axthrix requires it)_

### Save file

[bug-map.zip](https://github.com/Anuken/Mindustry/files/11963672/bug-map.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Mythril382** [comment]
Happens. Don't use it at all.

**Comment by stacktrace-error** [comment]
the sound engine seems to not like short sounds
the malign shot does something similar

**Comment by Anuken** [comment]
Don't use that sound. I didn't write the sound library and I don't even know where I would begin to debug the problem.
