### ISSUE TITLE
Sudden closure

### ISSUE THREAD

**Issue by Gab304** [Anuken/Mindustry#8803]
### Platforms

iOS

### Build

145.2

### Issue

I installed a mod on Mindustry(Exogenis), but when I restart the app it crashes, closes and when I reopen it it says that the mods are interfering with the game and it blocks them automatically (I use Ipad at last version of IOS)
![IMG_0442](https://github.com/Anuken/Mindustry/assets/119765082/6e727938-7c7c-4869-8f55-1b7d51bc8569)

### Steps to reproduce

Trying  install Exogenis mod on mobile and then reopen the game

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by NemesisTheory** [comment]
An issue with the mods, not Mindustry.

Exogenesis is a very demanding mod, so even just loading it in mobile is quite a challenge (especially if your device isn't powerful enough).

**Comment by stacktrace-error** [comment]
in short: you need more RAM

**Comment by Anuken** [comment]
Crash logs are **required.**

Mod issue. Don't use it if it does not work on your device.
