### ISSUE TITLE
Alt Tab - Windows free version

### ISSUE THREAD

**Issue by unikur1570** [Anuken/Mindustry#8804]
### Platforms

Windows

### Build

7.0 Build 145.1

### Issue

I have laggy Alt + Tab in mindustry (if full screen mode is enabled).  It is not clear why the full-screen mode was made if Alt + Tab lags in full-screen mode, in contrast to the non-full-screen mode, in which everything is the same. Maybe it's just that I don't understand something, or it's just bugs with the free version, I can't guess, but I'll be glad if someone explains to me what's wrong)

### Steps to reproduce

idk

### Mods used

-

### (Crash) logs

-

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by buthed010203** [comment]
Windows' exclusive fullscreen tends to do this a lot hence the existence of borderless windowed mode. I still recommend fullscreen though as performance will be better.
