### ISSUE TITLE
circleTarget ignores omniMovement

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#8809]
### Platforms

Mac

### Build

145.1

### Issue

When a unit has circleTarget enabled and omniMovement disabled, the circular targeting ignores the "must be facing somewhere to move there" requirement of omniMovement. Video attached here: [](https://gyazo.com/60631ab9dd50d71c8142a9ba57cf8833)

### Steps to reproduce

Step 1. Make a unit.
Step 2. Enable circleTarget.
Step 3. Disable omniMovement.
Step 4. Go in-game and make the unit target something via RTS controls.
Step 5. Witness it.

### Mods used

overdramaticpanromantic/frankies-stuff-and-things

### Save file

[circleTarget_and_omniMovement_conflict.msav.zip](https://github.com/Anuken/Mindustry/files/11996941/circleTarget_and_omniMovement_conflict.msav.zip)
I think this should work. If it doesn't, let me know.

### (Crash) logs

Non-crash.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by overdramaticpanromantic** [comment]
Edited a bit. Realized I mixed up enable and disable when typing this.

**Comment by buthed010203** [comment]
(video was in fact not attached here)

**Comment by overdramaticpanromantic** [comment]
Tragic. GitHub fuckery gets the best of me once more.

**Comment by Anuken** [comment]
Those two options are not supposed to be used together in that way. If you want this implemented, write your own AI.
