### ISSUE TITLE
I can't download mods

### ISSUE THREAD

**Issue by Graphixal** [Anuken/Mindustry#8818]
### Platforms

Android

### Build

145.1

### Issue

Everytime I try to download a mod, it says "Connection error: forbidden."
This is the first time this has happened to me.

### Steps to reproduce

Tried to download a mod regularly.

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
as expected, no screenshots or logs

**Comment by 3Snake3** [comment]
Check your internet connection

**Comment by Cong0707** [comment]
if your country has some problem in connect github or something(like china), this is normal

**Comment by Anuken** [comment]
Your country or ISP probably has Github blocked.
