### ISSUE TITLE
Can't import a mod from a directory with "é" in it's name

### ISSUE THREAD

**Issue by Enderteck** [Anuken/Mindustry#8819]
### Platforms

Linux

### Build

145.1 [Steam Linux 64bit]

### Issue

When I try to import a .jar mod from a directory with "é" in it like the French word for downlads "Téléchargements" it crashes with this error message :

![Capture d’écran du 2023-07-15 19-01-23](https://github.com/Anuken/Mindustry/assets/123917079/5e62ca4d-a234-4e89-a0fa-8e0a47e1d867)

I think the game deosn't understand thoses characters. I haven't tested yet but it might not work with "à", "ù" and "ç"

### Steps to reproduce

Import a .jar mod frome a folder with "é" in it.

### Mods used

Tested it with the last version of Extra Utilities: https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod

### Save file

Doesn't happen in game

### (Crash) logs

[crash-report-07_15_2023_19_01_11.txt](https://github.com/Anuken/Mindustry/files/12062248/crash-report-07_15_2023_19_01_11.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> is there any reason why Linux builds don't use the custom FileChooser GUI?

Because it's terrible.
