### ISSUE TITLE
Mindustry sound output won't change to another channel

### ISSUE THREAD

**Issue by KiloLiuton** [Anuken/Mindustry#882]
**Platform**: (Linux)

**Build**: (steam build 98)

**Issue**: (After launching the game, I try changing the sound output channel for Mindustry to a channel other than the default but nothing happens, sound continues to play from default channel and the option is back to default next time I open the sound settings. Since there is no sound output choice in the game menu, it has to be done through the OS I think)

**Steps to reproduce**: (Launch game, try changing sound output channel on OS)

**Comment by Anuken** [comment]
Why would you want to change the sound output channel? I've never heard of a feature like that.

**Comment by KiloLiuton** [comment]
When I use my laptop I regularly use headphones or a bluetooth speaker instead of the default built-in speaker. KDE plasma can change de sound output channel for other applications fine, such as firefox or other games, but mindustry for some reason always stays assigned to the default channel.

**Comment by davidstrauss** [comment]
I experience this issue, too. I suspect that Mindustry is doing something like looking up the default audio sink at startup and directly attaching to that. It suggests that the audio abstractions aren't implemented in quite the right way.

Given that I don't have this issue with other apps (my use case is the same as @KiloLiuton's), I think this is a bug.
