### ISSUE TITLE
Can not load server and mods

### ISSUE THREAD

**Issue by Charlie-xiax** [Anuken/Mindustry#8820]
### Platforms

Windows

### Build

145.1

### Issue

It seems can not connect to the internet. I tried both the servers and mods, nothing was loading. This my game log and screenshot.
<img width="731" alt="屏幕截图 2023-07-16 184745" src="https://github.com/Anuken/Mindustry/assets/116860590/4952c235-74f6-4a95-9c93-62dfd0e8f38a">
<img width="1222" alt="屏幕截图 2023-07-04 123951" src="https://github.com/Anuken/Mindustry/assets/116860590/39bc2240-c96b-4bd2-b125-82f8c1f23678">
This is not the firewall's problem, I have tried. It did not work. But I found a really strange case, if I use my phone's hotspot to share the internet, and my phone is connecting to WiFi, it can load the servers and mods again sometimes(my phone must connect to WiFi). Sometimes it would said "connect time out".
<img width="704" alt="屏幕截图 2023-07-16 184802" src="https://github.com/Anuken/Mindustry/assets/116860590/f399b776-2fd3-4413-b756-785e520036cc">
<img width="732" alt="屏幕截图 2023-07-16 184738" src="https://github.com/Anuken/Mindustry/assets/116860590/e735f527-43ca-43a3-9ee1-8b01690bb152">
---------------------------------------
This only happens to my windows version, my andriod version is fine.

### Steps to reproduce

1. open mindustry
2. open mods
3. open mod browser
4. cannot load mods
-------------------------------------
1. open mindustry
2. open join game
3. cannot load servers
----------------------------------------
1. connect my phone to WiFi
2. open my phone's hotspot
3. connect my computer to this hotspot
4. open mindustry
5. open join game
6. can load servers again sometimes

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SSTentacleSS** [comment]
@Charlie-xiax Can you pls run this command in terminal and then send does the command run successfully?
Better cover up the IP addresses of the servers that happen on every hop

(in any case, if tracert works, then this is already a problem with Mindustri, if it doesn’t work, with your Internet)

```ps
tracert https://raw.githubusercontent.com
```

**Comment by Charlie-xiax** [comment]
> @Charlie-xiax Can you plsyourself go to https://raw.githubusercontent.com/ page in internet browser? You should be redirected to github.com, otherwise it's a problem with your internet

It shows this page
<img width="1230" alt="image" src="https://github.com/Anuken/Mindustry/assets/116860590/8f34e6c2-c952-4a0a-8ee7-d9f67e635234">

**Comment by Charlie-xiax** [comment]
> @Charlie-xiax Can you plsyourself go to https://raw.githubusercontent.com/ page in internet browser? You should be redirected to github.com, otherwise it's a problem with your internet

It shows this
<img width="1230" alt="image" src="https://github.com/Anuken/Mindustry/assets/116860590/5565a489-2abd-48c4-961d-62e656bd178b">

**Comment by Charlie-xiax** [comment]
It says “Unable to resolve target system name”.

从 Windows 版邮件发送

发件人: Tentyanuk
发送时间: 2023年7月18日 14:06
收件人: Anuken/Mindustry
抄送: Charlie; Mention
主题: Re: [Anuken/Mindustry] Can not load server and mods (Issue #8820)

@Charlie-xiax Can you pls run this command in terminal and then send does the command run successfully?
Better cover up the IP addresses of the servers that happen on every hop
(in any case, if tracert works, then this is already a problem with Mindustri, if it doesn’t work, with your Internet)
tracert https://raw.githubusercontent.com

**Comment by Charlie-xiax** [comment]
Actually, I still haven't found the cause of this problem since it worked well before. Maybe it's my DNS's problem. But I find a way to solve it recently, which is using the TUN mode in Clash, then it can load the servers again. I don't know the principles behind this, maybe it is because it changes my DNS server. Hoping this will be helpful.

**Comment by Charlie-xiax** [comment]
close.
