### ISSUE TITLE
Ground zero, stuck with "supply turret" task (android)

### ISSUE THREAD

**Issue by bernardozan** [Anuken/Mindustry#8821]
### Platforms

Android

### Build

7-official-145.1

### Issue

In ground zero, I am stuck at the supply turret task, even though i have done that already

### Steps to reproduce

First mission ground zero, follow the tasks until one gets the task "supply the Duo turrets with copper, using conveyors". Then nothing seems to work
![photo_2023-07-16_10-59-25](https://github.com/Anuken/Mindustry/assets/138227407/edbfb2d8-434f-4ade-89b2-bb122eb884cf)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
A save file is required.

**Comment by skeddles** [comment]
I just downloaded the game for the first time and am having the exact same problem. Can't tell if it's a bug or I'm missing something major. 

[minedustry.zip](https://github.com/Anuken/Mindustry/files/14107785/minedustry.zip)

**Comment by Anuken** [comment]
There is a a flaw in the logic for that map; you have a single turret near your core with no ammo, and that is the turret being checked for ammo. Delete it to fix the issue.

**Comment by jones77** [comment]
*(It wasn't obvious to me and I ended up here because...)*

You have to supply the turrets with copper and lead directly.
