### ISSUE TITLE
120fps on Ipad Pro

### ISSUE THREAD

**Issue by JZ6** [Anuken/Mindustry#8822]
### Platforms

iOS

### Build

7.125.2

### Issue

Even after setting fps to 120 on ipad pro, it still runs the game at 60fps

### Steps to reproduce

Setting fps to 120 on ipad pro, turn on fps counter and game still runs at 60fps.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
this isnt a bug.mobile mindustry has vsync always on. your screens Hz is probably 60 and because mindustry has vsync on it wont go above 60 fps

**Comment by camelStyleUser** [comment]
This isnt an issue and is an intended feature. Please close this issue.

**Comment by Anuken** [comment]
120FPS is not supported. The in-game settings are a **cap**, they do not increase your framerate.

**Comment by JZ6** [comment]
yes but ipad pros do run at 120fps, some other games like brawl stars and doom do run at 120 fps
https://www.ytechb.com/list-of-games-with-120hz-support-for-ipad-pro/

**Comment by Anuken** [comment]
That doesn't change the fact that Mindustry doesn't support it on iOS, and was never programmed to.

**Comment by JZ6** [comment]
anychance we can support it? or is it a limitation of the engine
