### ISSUE TITLE
Problem with processors

### ISSUE THREAD

**Issue by Vlad-Igroman2022** [Anuken/Mindustry#8826]
### Platforms

Android

### Build

145.1

### Issue

If you use the "Sensor" function on one of the guns and check any resource in the same gun, then it gives the number 0, even if the gun is loaded with this resource

### Steps to reproduce

My friend and I are learning to program (more precisely, I'm teaching him to program) in this game. Yesterday a friend wrote to me saying that he is going to check the amount of a certain resource / liquid in the gun, but he is given a number: "0". I wanted to know what kind of script he had, and what devices are connected to the processor. He sent. He also sent a screenshot of what comes out in the end (in the output). And there was the same number: 0. Then I asked to "copy your building and go to some server", then we went to him and he showed his building. I started looping through the script, but it still doesn't work, still that damn number 0! We decided that this is a bug and decided to write to you, the developers, I hope you will solve this problem or explain what is wrong. I wish you a good day and less problems :3

 (We had such a script: Sensor: x = @thorium to fuse1)

### Save file

[The file won't load for some reason, sorry :( ]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
because resources in the turret are a lie and just are removed and just added to ammo.
expected behaviour

**Comment by camelStyleUser** [comment]
(also there is only single dev:Anuken)

**Comment by Vlad-Igroman2022** [comment]
> because resources in the turret are a lie and just are removed and just added to ammo.
> expected behaviour

My friend just wanted to do this and check if the given resource exists or not, but I don't want to retell: too lazy :/

**Comment by Vlad-Igroman2022** [comment]
> because resources in the turret are a lie and just are removed and just added to ammo.
> expected behaviour

My friend just wanted to do this and check if the given resource exists or not, but I don't want to retell: too lazy :/

**Comment by SunkyMP3G** [comment]
You pinged random person

**Comment by Anuken** [comment]
Turrets don't store items, they just have ammo.
