### ISSUE TITLE
Un bug sur la campagne.

### ISSUE THREAD

**Issue by soloseul** [Anuken/Mindustry#8829]
### Platforms

Windows

### Build

143.1

### Issue

Sur le niveau Ruinous Shores (enfin je pense que ça doit être sur tous les niveaux), à la dernière vague, le boss a tiré avec des boules de feux sur mon noyau et je l'ai tué avec des tourelles électriques au moment où il a tiré sa dernière boule de feu, et elle a détruit mon noyau. Donc il était affiché en haut de l'écran ''secteur perdu'' et en haut à gauche ''secteur capturé''. Je n'avais plus de noyau (ma base n'avait pas explosé) mais je pouvais continuer à me déplacer sans rien pouvoir construire. J'ai finalement fermé puis réouvert le jeu, et quand je suis retourné sur le niveau, j'avais finalement perdu et ma base avait explosé.

### Steps to reproduce

Tuer le dernier ennemi de la dernière vague au moment où tire sa dernier balle (ou autre moyen de destruction). Il faut que cette balle détruise le noyau.

IMPORTANT !
Je n'ai pas réussi à reproduire le problème sur la dernière version : la probabilité que tous ces éléments soient réunis au même moment est très faible.
(J'ai quand même coché la case pour vous faire parvenir ce bug. Et je ne sais pas vraiment comment vérifier que ce problème n'a pas déjà été signalé.)

### Save file

[campagne.zip](https://github.com/Anuken/Mindustry/files/12110327/campagne.zip)

### (Crash) logs

[bug.txt](https://github.com/Anuken/Mindustry/files/12110331/bug.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JojoFR1** [comment]
En anglais, Anuke ne va pas lire si c'est pas en anglais

**Comment by JojoFR1** [comment]
Translation in English for Anuke:


Title: Bug on the campaign

## Platforms
Windows

## Build
143.1

## Issue
On the Ruinous Shores level (well, I think it must be on all levels), on the last wave, the boss fired fireballs at my core and I killed him with electric turrets just as he fired his last fireball, and it destroyed my core. So at the top of the screen it said "sector lost" and at the top left "sector captured". I no longer had a core (my base hadn't exploded), but I could still move around without being able to build anything. I finally closed and reopened the game, and when I returned to the level, I had finally lost and my base had exploded.

## Steps to reproduce
Kill the last enemy in the last wave as he fires his last bullet (or other means of destruction). This bullet must destroy the core.

IMPORTANT!
I haven't managed to reproduce the problem on the latest version: the probability of all these elements being present at the same time is very low.
(I did check the box to send you this bug, though. And I don't really know how to check that this problem hasn't already been reported).

**Comment by Anuken** [comment]
I don't really see a bug here, you lost the sector.

**Comment by BalaM314** [comment]
I think the issue is that it didn't kick them out of the sector when they lost it

**Comment by Anuken** [comment]
You can pan around the map even if you've lost the sector.
