### ISSUE TITLE
Huawei y9s

### ISSUE THREAD

**Issue by Alol555n** [Anuken/Mindustry#8831]
### Platforms

Android

### Build

145.1-7

### Issue

There are error in files I guess make the secrene dos'nt fet
![Screenshot_20230722_150353_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/75747063/920d722e-36cf-45be-8b3b-46f386c47be8)
![Screenshot_20230722_150356_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/75747063/b47545ab-5da0-4374-95eb-32dbce3632b2)

### Steps to reproduce

I didn't do any thing 

### Save file

I dont know if it's happend to anther people because it's file erorr i guess 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by KhaledHawwas** [comment]
Are you sure you didn't change the games' Ui scaling?

**Comment by SITUVNgcd** [comment]
1. You changed **__UI Scaling__** in game's settings.
2. You changed **__Min width__** in __Developer options__** in phone's settings.

**Comment by camelStyleUser** [comment]
~~where do you people even get versions after 145.1~~
