### ISSUE TITLE
monos deposit to the core even if they are controlled by processors

### ISSUE THREAD

**Issue by Rusomati** [Anuken/Mindustry#8832]
### Platforms

Linux

### Build

145.1

### Issue

if monos reach their item capacity they will deposit to the core even if they are controlled by logic

### Steps to reproduce

1-download the save file
2-rename it
3-import it

### Save file

[test.txt](https://github.com/Anuken/Mindustry/files/12142654/test.txt)
uploading msav files does not work for some reason.. so you have to rename test.txt to test.msav

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug.
