### ISSUE TITLE
the map preview gets its edges overdrawn by ui elements

### ISSUE THREAD

**Issue by Rusomati** [Anuken/Mindustry#8833]
### Platforms

Linux

### Build

145.1

### Issue

the very edges of the map do not show up in the map preview
example: 
![2023-07-24_749x766](https://github.com/Anuken/Mindustry/assets/96618008/4d3b25df-bdda-4d1c-ae2d-15e4aaf6f2b0)
![2023-07-24_613x766](https://github.com/Anuken/Mindustry/assets/96618008/31e3e36a-17ba-42db-964a-945d17cf1f39)

### Steps to reproduce

use any map that does not use cliffs

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rusomati** [comment]
ifgnore the upper circle in the second image as is confusing

**Comment by Anuken** [comment]
Intentional.
