### ISSUE TITLE
Map background disappears if water tiles in view

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry#8837]
### Platforms

Windows

### Build

145.1

### Issue

Map background stop rendering if there's water tiles in view. 

### Steps to reproduce

Set up map background and place water tiles - as soon as they appear at player screen background turns black. Tar, slag and other tiles with liquids are working without issues.

On save press the button to swap the tile between empty and water.

### Mods used

Mapping utilities to enable the background for save. 

### Save file

[bug1.zip](https://github.com/Anuken/Mindustry/files/12160593/bug1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is only possible with mods, so I won't be fixing it. Water doesn't make sense in space anyway.

**Comment by rekokoro** [comment]
Mod are used to enable background in the editor, map save displays the background without the mod.
And also having space as background doesn't mean the map set exactly in open space with no water. Space station or some cross-world setup can have both space background and water tiles in it.
