### ISSUE TITLE
Make @air a proper floor tile

### ISSUE THREAD

**Issue by rekokoro** [Anuken/Mindustry#8838]
### Platforms

Windows

### Build

145.1

### Issue

Setting a floor tile with wrong type results in replacing tile with @air floor that behaviors as @empty but with ability to place at top. But after save-load or resyncing to server the invalid tile is replaced with @stone floor while units still not consider it as a valid tile for pathfinding.

So can we have the @air floor as it is without replacing with stone? It's kinda cool to make some hidden pathways.

### Steps to reproduce

Set up floor to @air or any type of block or ore. The tile will be transparent as @empty but you'll be able to place everything as at the stone. 

On save - enabled switch replaces every tile with @air, disabled - with @empty 

### Mods used

None

### Save file

[bug2.zip](https://github.com/Anuken/Mindustry/files/12160693/bug2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Air should not be a valid floor tile, so the real bug here is that setting floor to air does anything at all.
