### ISSUE TITLE
Game import crash

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#884]
**Platform**: iOS

**Build**: custom build (5.0)

**Issue**: Importing game data causes the game to crash.

**Steps to reproduce**: Export game data to iOS “files” (tested on the “iCloud” folder, “my iPhone” folder, and dropbox), import game data from “files” or dropbox.

**Comment by Anuken** [comment]
That is intentional behavior; the game must exit immediately after importing data. It even tells you this will happen in the dialog.

**Comment by willis936** [comment]
I noticed that in progress games do not get updated with the import data feature.  Is this the expected behavior?

**Comment by willis936** [comment]
I just wiped my save data and imported it.  When I relaunched the game it still had no progress.
