### ISSUE TITLE
custom android icon theming broken

### ISSUE THREAD

**Issue by RustoMCSpit** [Anuken/Mindustry#8843]
### Platforms

Android

### Build

fdroid build 145.1

### Issue

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

the custom icon isnt working (assuming it's implemented)

### Steps to reproduce

downlaod app, look at it

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> assuming it's implemented

It's not.

**Comment by RustoMCSpit** [comment]
> > assuming it's implemented
> 
> It's not.

oh alright, guess this is a feature request to keep in mind then
