### ISSUE TITLE
Interplanetary accelerator 

### ISSUE THREAD

**Issue by Trohten2** [Anuken/Mindustry#8844]
### Platforms

Android

### Build

145.1

### Issue

Cant reconstruct the interplanetary accelerator after deconstructing it for 1 sec, it just dont do anything (i have every ressources)

### Steps to reproduce

Deconstruct it for 1 sec then click it again

### Mods used

It happens without any mod but i first saw it while being with this mods: Fading Révélations,  Frozen Farlands,  MultiCrafter Lib 

### Save file

My file is 58 Mo and github only allow 25 Mo or less so i can't upload it

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Mythril382** [comment]
Interplanetary accelerator is useless. It is no longer required and thus, was removed from the tech tree and the build menu. It only stays in the game for lore purposes.
