### ISSUE TITLE
server breaking

### ISSUE THREAD

**Issue by tech3mi** [Anuken/Mindustry#8848]
### Platforms

Windows

### Build

145

### Issue

Whenever I try to config my 4 servers, all hosted on one machine with a working domain and working port-forwading, the console just says 'open the server first' and then it doesnt open, and my servers go down. I cant fix it

### Steps to reproduce

Literally just trying to config

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There is barely any information here. Literally hundreds of people have gotten the server working, and I'm not sure what you are trying to say with "my servers go down" or what "config my servers" even means. You have not attached any logs.
