### ISSUE TITLE
Copper in campaign

### ISSUE THREAD

**Issue by PSeba-M** [Anuken/Mindustry#885]
**Platform**: *Android*

**Build**: *98.1*

**Issue**: *The game won't let me get into levels because it tells me that I have 2 different types of copper, but there's only one copper. The problem is that I can't get into campaign mode for this one.*

**Steps to reproduce**: *When I try to enter a campaign mode level*

**Comment by Anuken** [comment]
What are these "two types of copper"? Show me a screenshot.

**Comment by PSeba-M** [comment]
Se me arreglo

**Comment by Anuken** [comment]
I'm assuming that means this is no longer an issue.
