### ISSUE TITLE
achievement the spiral

### ISSUE THREAD

**Issue by JasperChaseTOQ** [Anuken/Mindustry#8850]
### Platforms

Android

### Build

steam 145.1

### Issue

on steam you cant get the achievement the spiral on any captured sector for some reason you can only obtain it during a currently attacking sector

### Steps to reproduce

capture a sector, do the steps to achieve the spiral achievement
achievement not obtained

attack a sector, do the steps to achieve the spiral achievement
  

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce this issue.

![image](https://github.com/Anuken/Mindustry/assets/10100000/b2f2ddb3-1c0a-49dd-b0b5-157b3f3696e7)

**Comment by Anuken** [comment]
Maybe your saves were broken? Are you sure you placed it exactly the same way in a completed sector vs incomplete one? It needs to happen in campaign.

**Comment by JasperChaseTOQ** [comment]
almost 100% positive this was back before i downloaded any mods and there hasn't been any updates to the game since so i never touched my saves or could they have broken from updating somehow. and it was 100% on campaign only.

**Comment by Anuken** [comment]
You can try it yourself: Write `Achievement.circleConveyor.uncomplete()` in the console, then place it in a sector again.

**Comment by JasperChaseTOQ** [comment]
![screenshot2](https://github.com/Anuken/Mindustry/assets/103849596/9f832cc6-f601-4efa-b2a2-a5a31782ed8e)
its not popping up and i can confirm i no longer have the achievement

**Comment by JasperChaseTOQ** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3011248904
![Screenshot 2023-07-28 130149](https://github.com/Anuken/Mindustry/assets/103849596/ac3966cb-1911-49b3-b25c-fefbb29a2fa6)

**Comment by Anuken** [comment]
Try running the game without mods or custom clients first.

**Comment by JasperChaseTOQ** [comment]
unfortunately no luck , tried it without mods and i dont use a custom clint.
https://steamuserimages-a.akamaihd.net/ugc/2040744841420336044/956BD2AC91D7C14BD4F789B4162CEC9274DEEEF9/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

as for broken saves that you mentioned earlier is there a way to check and/or debug them?

**Comment by JasperChaseTOQ** [comment]
okay thats so strange it just popped up as i repaired one of the pieces of the spiral that was broken by an enemy unit

**Comment by Anuken** [comment]
I don't know, that still sounds fishy to me. Maybe something is wrong with the detection code and it's completely unrelated to sector status.
