### ISSUE TITLE
airborne achivement 

### ISSUE THREAD

**Issue by JasperChaseTOQ** [Anuken/Mindustry#8852]
### Platforms

Android

### Build

steam 145.1

### Issue

i constructed nova units (while attacking a sector and just now in a captured sector) and choose their airborne option and flew them around the map and at one point even targeting an enemy unit with them to see if that would trigger the achievement but it never triggered

https://steamuserimages-a.akamaihd.net/ugc/2040744841415020074/85B49F98162FFA507CBDA12BA0671BCCE61E8171/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
![screenshot](https://github.com/Anuken/Mindustry/assets/103849596/4d18b8eb-b4ed-48a2-b2c8-d5214b6180f3)

### Steps to reproduce

consturct a nova unit 
select airborne option

### Mods used

time control
betamindy
exogenesis
expanded industries

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You're supposed to control the unit yourself.

**Comment by JasperChaseTOQ** [comment]
oh okay thank you sorry about this report then

**Comment by JasperChaseTOQ** [comment]
yup got the achievement thank you so much and sorry once again
