### ISSUE TITLE
achievement mending 

### ISSUE THREAD

**Issue by JasperChaseTOQ** [Anuken/Mindustry#8853]
### Platforms

Android

### Build

steam 145.1

### Issue

okay not 100% sure this one is an issue or bug however the achievement is mending and says to build a mend projector, and its one of the first achievements i got however its how i got it thats the issue, i got it when i first built a mender the lower tier of a mend projector 

im not sure if its supposed to give it at the lower tier but as it specified the higher tier im inclined to believe its not

side note: last bug report hopefully as aside from these and over prepared (which was reported previously by someone else) im not aware of any other achievements being bugged

### Steps to reproduce

build a mender instead of a mend projector
obtain mending achievement 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
It applies to both types of mend projector.
