### ISSUE TITLE
Build speed

### ISSUE THREAD

**Issue by Tyranton** [Anuken/Mindustry#886]
Android 9 (Samsung S8)

Build 98.1

Slower build speed on Trident ship since recent update (might only affect copper walls)

Loaded a save (in game, not imported. The save existed from before the update) and continued to play as normal and noticed a significant decrease in build speed. Trying to build a wall in front of enemies as soon as they spawn, worked previously but not any more. Either build speed of copper walls is way slower or enemies are faster.

I'm not sure if the build speed on copper walls was intentionally increased...

**Comment by Anuken** [comment]
Walls are intentionally slower to build.
