### ISSUE TITLE
Vanilla weapon sprites don't get drawn on modded units, but modded weapon sprites

### ISSUE THREAD

**Issue by Xaphironius** [Anuken/Mindustry#8863]
### Platforms

Android

### Build

BE 24274

### Issue

Vanilla weapon sprites won't draw on modded units. Modded weapon sprites however, does work.
![Screenshot_20230729_193907_Mindustry BE](https://github.com/Anuken/Mindustry/assets/85978775/1eb68587-8c95-4e78-bb72-78fbb2d11f83)

I managed to get around this issue, by copypasting the vanilla sprite into my mod and renaming it to something else.

### Steps to reproduce

Have a modded unit draw a vanilla weapon sprite.

### Mods used

[Xaphiron-YellowDawnExpansionMod-master.zip](https://github.com/Anuken/Mindustry/files/12207046/Xaphiron-YellowDawnExpansionMod-master.zip)

### Save file

[4.zip](https://github.com/Anuken/Mindustry/files/12207048/4.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
When you create a weapon, it automatically prefixes it with the mod name, and thus only loads the region from the mod. Not really a bug.
