### ISSUE TITLE
Saving map causes crash.

### ISSUE THREAD

**Issue by MinRi2** [Anuken/Mindustry#8865]
### Platforms

Android

### Build

v145.1

### Issue

When I am trying to save a map in map editor, the game got a crashed.

I heared that some android users have the same problem but some other android users don't.

### Steps to reproduce

1. Create a new map in map editor.
2. Save the map. (If the game haven't crashed, try more times)

### Mods used

None.

### (Crash) logs

No crash file was created.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash reports require a crash log. If none was generated, I can't help you.

**Comment by SMOLKEYS** [comment]
Tough assumption, but it could be a native crash, which Mindustry cannot catch and log at all.
