### ISSUE TITLE
Redmi 9

### ISSUE THREAD

**Issue by YaroslavNefedov** [Anuken/Mindustry#8868]
### Platforms

Android

### Build

145.1

### Issue

На планете эрикер я хочу высадится на сектор Ущелье и точка отправление это сектор Озеро чтобы высадится на сектор нужны ресурсы ресурсы у меня есть чтобы высадится но мне нужен Вольфрам чтобы высадится а на секторе Озеро от слова совсем нету там вольфрама и я не могу высадится на сектор Ущелье из за того что у меня нету 400 вольфрама а на секторе Озеро как я уже говорил нету вольфрама пожалуйста решите мой вопрос

### Steps to reproduce

Ничего

### Mods used

Не использую

### Save file

![IMG_20230730_205313](https://github.com/Anuken/Mindustry/assets/140971914/24f2a7ad-0ee4-479a-8613-21b9680b446b)

### (Crash) logs

На планете эрикер я хочу высадится на сектор Ущелье и точка отправление это сектор Озеро чтобы высадится на сектор нужны ресурсы ресурсы у меня есть чтобы высадится но мне нужен Вольфрам чтобы высадится а на секторе Озеро от слова совсем нету там вольфрама и я не могу высадится на сектор Ущелье из за того что у меня нету 400 вольфрама а на секторе Озеро как я уже говорил нету вольфрама пожалуйста решите мой вопрос
![Uploading IMG_20230730_205050.jpg…]()

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You need to launch from a different sector.

**Comment by YaroslavNefedov** [comment]
Будьте добры сказать как это сделать пожалуйста

**Comment by YaroslavNefedov** [comment]
Скажите пожалуйста как это сделать

**Comment by 3Snake3** [comment]
@YaroslavNefedov Figured it out?
