### ISSUE TITLE
pyrolysis generator cost only 49 carbide

### ISSUE THREAD

**Issue by 1Gvand** [Anuken/Mindustry#8870]
### Platforms

Windows

### Build

145.1

### Issue

![image](https://github.com/Anuken/Mindustry/assets/95881832/c6372695-b83f-4417-8494-cf2613d91cb8)
I put two generators, but the carbide decreased only by 98, I always notice this on each sector.
at the beginning it was 100 after I landed on the sector, but now its 2
![image](https://github.com/Anuken/Mindustry/assets/95881832/99ecec16-fcd5-410e-97c9-a47ba7b3fe29)

### Steps to reproduce

obviously put a generator

### Mods used

-

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Save required, cannot reproduce issue.

![image](https://github.com/Anuken/Mindustry/assets/10100000/b49ab36c-d553-4cdb-a5ff-a1bd7ab08e33)

**Comment by 1Gvand** [comment]
> Save required, cannot reproduce issue.
> 
> ![image](https://user-images.githubusercontent.com/10100000/257264423-b49ab36c-d553-4cdb-a5ff-a1bd7ab08e33.png)

OK
