### ISSUE TITLE
Mechanical Drill Bug

### ISSUE THREAD

**Issue by Vioddie** [Anuken/Mindustry#8871]
### Platforms

Android

### Build

145.1

### Issue

Mechanical Drill on Sandbox Mode. 

### Steps to reproduce

I was modifying a world processer about automatically upgrading conveyors, I copied the code and started working on the conduits and mechanical drills.

When I first tested it, the conduit upgraded normally (done by using the world processor's replicated code) then I tested the mechanical drill, it consumed one copper.

At first I thought it was the world logic processor, but when I was fixing it's code, everything seemed normal, I tried to compare it to the other two, but it seemed to be perfectly aligned with the two codes, I tried making it from scratch, it was still somehow perfect.

So I went ahead and done it on a new map, turns out it wasn't the world processors at all. It was the mechanical drill. 

### Mods used

No mods were used. 

### Save file

[Sandbox_v1.zip](https://github.com/Anuken/Mindustry/files/12213487/Sandbox_v1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You haven't specified what the bug actually *is* here. I'm not going to debug your logic code unless you can point to a specific line and tell me what the instruction is doing wrong (and why).

**Comment by Vioddie** [comment]
> You haven't specified what the bug actually _is_ here. I'm not going to debug your logic code unless you can point to a specific line and tell me what the instruction is doing wrong (and why).

The mechanical drill consumes one copper when I place it,
Nothing is wrong with the logic code, I removed my mods before reporting this issue.
