### ISSUE TITLE
pyrolysis generator cost only 49 carbide (reopened)

### ISSUE THREAD

**Issue by 1Gvand** [Anuken/Mindustry#8876]
### Platforms

Windows

### Build

145.1

### Issue

![image](https://github.com/Anuken/Mindustry/assets/95881832/0a7db05d-a75d-471d-8a96-56552f896c08)

I put two generators, but the carbide decreased only by 98, I always notice this on each sector.
at the beginning it was 100 after I landed on the sector, but now its 2
![image](https://github.com/Anuken/Mindustry/assets/95881832/4db47524-955e-4d77-bef4-a4ff4cafa596)

### Steps to reproduce

use save and load from Siege to Crossroads and put generator, or you can also to sector where is the carbide and put there

### Mods used

-

### Save file

[saves.zip](https://github.com/Anuken/Mindustry/files/12221493/saves.zip)
i dont know how export save , mb you need this folder, which is in the main folder

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by 1Gvand** [comment]
how its possible

**Comment by JojoFR1** [comment]
Anuke can't and will not guess the map

Use this button next to the map to export

![Screenshot_2023-07-31-21-48-42-901_io.anuke.mindustry-edit.jpg](https://github.com/Anuken/Mindustry/assets/110781915/5b2a23ce-38ab-40a2-9a60-0414d7fad793)

**Comment by Anuken** [comment]
None of the sectors have carbide on them, so I'm not sure what you expect me to do with that save. I can't launch anywhere with carbide, either.

**Comment by 1Gvand** [comment]
> None of the sectors have carbide on them, so I'm not sure what you expect me to do with that save. I can't launch anywhere with carbide, either.

which folder should I send, I send the one in the game folder, but I probably need to send the one in %appdata% or maybe WHAT I SHOULD SEND i dont understand, please explain what i should seeeeeeeeeeend
