### ISSUE TITLE
After I operated Anukin/ExampleMod in mindustry, the map of custom game was damaged, the system told 'a blue core is not added', and it happened on every map

### ISSUE THREAD

**Issue by morristp6** [Anuken/Mindustry#888]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
Use the issue template to report bugs. Don't paste it in the title.
