### ISSUE TITLE
Could not find com.github.Anuken.Mindustry:core:145.1

### ISSUE THREAD

**Issue by XaskyZ** [Anuken/Mindustry#8880]
### Platforms

Linux

### Build

145.1

### Issue

I'm making plugin for my server, using MindustryPluginTemplate by Anuke. 
And i'm using this dependencies:
dependencies{
    compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
    annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
}
But when i put mindustryVersion = '145.1', i get the error of "Could not find com.github.Anuken.Mindustry:core:145.1"
And when i put mindustryVersion = '130', i'm not getting any errors when building build.gradle.
But i need new features which adding by 145.1, so i wanna ask for help.

### Steps to reproduce

I'm making plugin for my server, using MindustryPluginTemplate by Anuke. 
And i'm using this dependencies:
dependencies{
    compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
    annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
}
But when i put mindustryVersion = '145.1', i get the error of "Could not find com.github.Anuken.Mindustry:core:145.1"
And when i put mindustryVersion = '130', i'm not getting any errors when building build.gradle.
But i need new features which adding by 145.1, so i wanna ask for help.

Btw:
```
-> % java --version
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 16:30:34 UTC
Revision:     <unknown>

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17 (Oracle Corporation 17+35-LTS-2724)
OS:           Linux 6.0.19-4-MANJARO amd64
```

### Mods used

https://github.com/Anuken/MindustryPluginTemplate

### (Crash) logs

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.Anuken.Arc:arc-core:145.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/arc-core/145.1/arc-core-145.1.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/arc-core/145.1/arc-core-145.1.pom
     Required by:
         project :
   > Could not find com.github.Anuken.Mindustry:core:145.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Mindustry/core/145.1/core-145.1.pom
       - https://www.jitpack.io/com/github/Anuken/Mindustry/core/145.1/core-145.1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
1 actionable task: 1 executed

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Slotterleet** [comment]
Try putting `v145` as `mindustryVersion` instead. JITPack probably just doesn't have artifacts for v145.1.

**Comment by XaskyZ** [comment]
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.Anuken.Mindustry:core:v145.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Mindustry/core/v145/core-v145.pom
       - https://www.jitpack.io/com/github/Anuken/Mindustry/core/v145/core-v145.pom
     Required by:
         project :
 ```      
 ```
dependencies{
    compileOnly "com.github.Anuken.Arc:arc-core:v145"
    compileOnly "com.github.Anuken.Mindustry:core:v145"
    annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
}
````
I tried but still getting this error

**Comment by Slotterleet** [comment]
There's also the option of MindustryJitpack instead of Mindustry. JITPack just sucks, you have to deal with that.

**Comment by Anuken** [comment]
You're supposed to use `MindustryJitpack` as the dependency. If it still doesn't work, I can't really help, JITPack is just broken.
