### ISSUE TITLE
flipSprite disables weapons

### ISSUE THREAD

**Issue by Fresh791** [Anuken/Mindustry#8881]
### Platforms

Windows

### Build

145.1

### Issue

When setting flipSprite: true on a units' weapon, that weapon is disabled and can't shoot. It renders normally though.

This has apparently been an issue for a while now.
![Screenshot_20230801_141524_Discord](https://github.com/Anuken/Mindustry/assets/77986574/7af27152-bf7e-424a-b18a-eb7bf9d558a9)

### Steps to reproduce

Make a unit with a weapon that has flipSprite: true. That weapon is disabled.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Do not assign flipSprite, it is for internal use only.
