### ISSUE TITLE
Game kicks me to desktop after loading without crash. (game breaking)

### ISSUE THREAD

**Issue by redshadow3** [Anuken/Mindustry#8883]
### Platforms

Windows

### Build

7.0 Build 145.1

### Issue

disclaimer: english is not my first language so there can be spelling mistakes

Ive played mindustry for a long time but several days ago i tried to play it and when the game loaded i got kicked to desktop and the game went into the taskbar, if i tried to show the window a black completely empty window appeared which seemed to change size several times before going back into the taskbar.
i have reinstalled the game several times, unsubscribed from mods on my workshop nothing fixed or changed it, i have already played version 7 before and it worked fine.

i tried to get tech support for it but i got redirected to the email for anukendev, i got no response after describing the problem,  tried on steam discussions but not much then i found the github for mindustry.

Some info: i play on a laptop with an integrated GPU and i use windows 11 ive never had this problem before or seen it, also when the game hides in the taskbar i can still hear the menu music, ive verified the integrity of installed files and have no other apps/games with such issues, and i bought and use the game on steam, also i have not seen the same exact bug in any closed or open issue.

im *not providing a save file* as all i can actually see before i get kicked is the loading screen then the game goes into the taskbar on its own, i *cant provide any steps for reproduction of the bug as i was just trying to run the game* and thats what happened, ive *removed all mods so i cant provide a list of those either.*

if theres any more info i should provide, please comment that instead of instantly closing the issue like its finished, i cannot play the game when its in this state.

### Steps to reproduce

Unknown, seemingly happened after some update.

### Mods used

all removed, didnt fix it

### Save file

Happened after the start-up loading screen not in a save.

### (Crash) logs

[last_log.txt](https://github.com/Anuken/Mindustry/files/12236077/last_log.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Frankly, there is very little I can do to help. There's absolutely no information that I can use in the logs and I've never heard of this happening before. Nobody else has reported this and there have been no updated that change how the game loads things.

Possible causes:

- There's something in the game data causing issues. Right-click the game on Steam -> browse local files -> delete the saves folder next to the executable. **This will clear all progress, saves and settings.**
- You installed a troll mod that immediately exits the game, and you still have installed despite thinking you don't. See steps above.
- A system/graphics driver update broke the game, and there's nothing anyone can do about it.

**Comment by redshadow3** [comment]
> * A system/graphics driver update broke the game, and there's nothing anyone can do about it.

oh , yeah i did update to win11 recently and havent ran the game since really, but its too late to roll back so i guess im not playing until microsoft fixes it as i assume you cannot...

**Comment by redshadow3** [comment]
update:
solution found, running through not steam but downloading the build from github goes fine, no problems with black screen

**Comment by redshadow3** [comment]
ok ive found the issue, the cloud file seems to have something corrupted, the reason reinstalling fixed it this time was beacause i turned off the cloud files, when i turned those back on again the issue got reproduced

**Comment by redshadow3** [comment]
ughhhhhh its back, now i think fullscreen is the issue as when i did the things i described earlier to fix but later in the settings set full screen to on the game did exactly the same thing as the original bug
in other words full screen is somehow causing the bug not corruption or whatever (steam probably saved the settings with full screen on which would explain why it would bug out with that on)

**Comment by Anuken** [comment]
There's probably something wrong with your system/drivers that breaks fullscreen; if this were a widespread issue I would be seeing more reports on it.
