### ISSUE TITLE
Samsung Galaxy A22 4g

### ISSUE THREAD

**Issue by Fewcristofer** [Anuken/Mindustry#8886]
### Platforms

Android

### Build

Versión 7-official-145.1

### Issue

Estaba construyendo y pasiando por el mapa cundo se me cierra el juego

### Steps to reproduce

Estaba construyendo cintas transportadoras para llevar el mineral para hacer magma cuando se me cerro el juego y volví abrir el juego y cuando termine de construir la magma fui a otro lado yo para construir un taladro láser y cuando lo construí se me cerro y cuando volví a abrir el juego hice para transportar el mineral hacia otro lado del mapa se me cierra el juego y volví a abrirlo cuando estaba pasiando por el mapa para ver que podría construir más y se me cerro el juego y creo que el bug es cuando explorar y construyes algo

### Mods used

No tengo eso

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
Maybe also send crash logs?

**Comment by Anuken** [comment]
Crash logs are required.
