### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by denzil0531** [Anuken/Mindustry#8888]
### Platforms

iOS

### Build

145.2

### Issue

No sound 
iPad Pro 10.5. I have try all the systems settings ,but still no sound output.

### Steps to reproduce

No any sound

### Mods used

No mod

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue in a simulator or real iPad device; with no logs there's nothing I can do.
