### ISSUE TITLE
Some buildings in fog are visible

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry#8889]
### Platforms

Windows

### Build

BE 24295

### Issue

put the buildings of 60-70 teams in the fog of the map, set the rule staticFog to false, then find them visible.

### Steps to reproduce

1.load the map
2.look at (190,190), there're buildings that should be invisible
3.control the beta to go to there
4.a crux core becomes visible - it works fine

### Save file

[test.zip](https://github.com/Anuken/Mindustry/files/12246859/test.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Fog only supports ~64 teams, it's an internal known limitation. (I don't see any reason for you to use team IDs that high anyway, I doubt any server even gets 64 players on it at once)
