### ISSUE TITLE
new silver update problem

### ISSUE THREAD

**Issue by K33RAN** [Anuken/Mindustry#889]
in the new map where you should be able to got silver, you can't where the silver should be it is black and you can't3
![Screen Shot 2019-10-25 at 10 59 28 PM](https://user-images.githubusercontent.com/57026373/67614502-31cbf900-f77b-11e9-87cf-db7846473555.png)
![Screen Shot 2019-10-25 at 10 59 37 PM](https://user-images.githubusercontent.com/57026373/67614503-31cbf900-f77b-11e9-8584-deb0009866ae.png)

 mine it.

**Comment by Anuken** [comment]
Use the issue reporting template for bugs.
