### ISSUE TITLE
Enemy Nova Unkillable

### ISSUE THREAD

**Issue by payangmula** [Anuken/Mindustry#8890]
### Platforms

Android

### Build

Build 145.1

### Issue

Enemy Novas in Sector 133 cannot be killed. I've tried all turrets I currently have, primarily Pyratite Ripples, Plastanium Cyclones, Thorium Fuses even a Meltdown. I've tried nuking them with Thorium Reactors but they survive every attempt. 

### Steps to reproduce

First time I launched to 133 from Overgrowth with Core: Foundation then proceeded as normal until the first wave showed up. My Lancers, Coal Scorches and Copper Salvoes failed to kill the single Nova and managed to reach my core. I decided to detonate a Thorium Reactor out of desperation while using a Mend Projector to outheal the Nova's attacks but I accidentally blew up my core while also destroying the Nova. I closed the game without saving and viewing the "Sector Lost" screen. Second try, I've set up more advanced turrets while using the thorium nuke repeatedly by closing and reloading the game to no avail. I've reached wave 5-6 and still nothing is working.

### Save file

Serpulo, Sector 133

[Nova_133_Bug.zip](https://github.com/Anuken/Mindustry/files/12247120/Nova_133_Bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BlueWolf3682** [comment]
to elaborate, this issue is because ground/naval units rarely dont get destroyed properly
reproduction steps are nil, it happens randomly and it seems to fix upon reload
