### ISSUE TITLE
Water Enemies Not Spawning

### ISSUE THREAD

**Issue by ShivaPrakash-006** [Anuken/Mindustry#8894]
### Platforms

Linux

### Build

145.1

### Issue

In sectors that are supposed to spawn water based enemies, land based enemies spawn and drown in the water. Like 174, 37. The water based enemies don't spawn anymore. They did in the past, before I updated I think.

### Steps to reproduce

Go to a watery sector, wait for a wave. When the wave comes, the land based enemies spawn in the water and drown.

### Mods used

No Mods Were Used

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/12262930/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/31012c48-52b9-4e96-aec8-c8a1da0110b1)

Unable to replicate on a fresh sector. You probably have older, broken waves and need to reset that save for it to work properly.
