### ISSUE TITLE
Abnormal Building Effects Rendering Colors Caused by Solar Panel with Extremely Low Negative Power Generation

### ISSUE THREAD

**Issue by shan-luan** [Anuken/Mindustry#8896]
### Platforms

Android

### Build

145.1

### Issue Overview
When connecting a solar panel to the projection accelerator building (new-horizon-assign-overdrive) in the Mindustry game, the colors of the accelerator's effects are displayed abnormally.

### Environment Information
- Game Version: 145.1
- Server Operating System: Windows10 2016LTSB
- Server Java Version: Java 8
- Server JVM Parameters: 

```
-d64 -Xms16000m -Xmx16000m -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=8 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Dfml.readTimeout=90 -XX:+UseFastAccessorMethods
```
### Additional Information
Other players have observed the same issue. I approached the author of the new horizon mod for clarification, and they mentioned that the building effects in the mod employ the same rendering methods as the original game, but I could not obtain the specific method names.

### Reproduction Steps
1. In the Mindustry game, set the solarMultiplier to an extremely low negative value (e.g., -1000000000) using the world processor.
2. Build a solar panel (solar-panel-large) and ensure that its actual power generation value is negative (e.g., -214748364.7).
3. Connect the solar panel to the projection accelerator building from the new horizon mod using a power node (power-node).
4. Ensure that all other requirements for the projection accelerator, apart from power, are met and connect a power source (power-source) to the power grid.

### Expected Results
The projection accelerator should function properly and display its effects in the correct colors.

### Actual Results
Due to the power source having a lower power output than the negative power generation of the solar panel, the projection accelerator does not work properly. However, when disconnecting the solar panel from the power grid, the projection accelerator starts functioning correctly. The color of the accelerator's effects changes from pure black to red and gradually returns to the normal orange color.

### Mods used

https://github.com/Yuria-Shikibe/NewHorizonMod

### Save file

Because it's simply a rendering issue, the server has not logged any relevant logs or crash records.

### (Crash) logs

Because it's simply a rendering issue, the server has not logged any relevant logs or crash records.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by shan-luan** [comment]
These are the additional images.
![Screenshot_20230806_005522_io anuke mindustry_edit_1930039646201850](https://github.com/Anuken/Mindustry/assets/124038110/59d427cd-af71-4ef5-875a-ebb19253af5f)
![Screenshot_20230806_005510_io anuke mindustry_edit_1930028026433623](https://github.com/Anuken/Mindustry/assets/124038110/1e5864d4-894d-4330-b1f0-1e93ea1d6033)

**Comment by Anuken** [comment]
> In the Mindustry game, set the solarMultiplier to an extremely low negative value (e.g., -1000000000) using the world processor.

This is absurd. Don't do this. The only bug here is you being allowed to set such a negative value at all.

**Comment by shan-luan** [comment]
Maybe you can consider restricting the range of this value in the next update.

**Comment by Anuken** [comment]
This was already done in b7d707e8ba0772e3aedbd7837b8b92ad42614f5e
