### ISSUE TITLE
invisible laser nodes 

### ISSUE THREAD

**Issue by Gab304** [Anuken/Mindustry#8898]
### Platforms

Mac

### Build

145.1

### Issue

I encountered what I think is a bug in version 145.1, the power nodes lasers are not seen. I tried restarting the game, restarting the computer, resetting the display control from the game settings, but nothing, they remain permanently invisible

### Steps to reproduce

I don't know

### Mods used

exogenis
new horizon
expanded industries
advanced factories
spore biomech
multicrafter lib
more conveyors, conduits, batteries, storages and unloaders
resource supply mod

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
press f5

**Comment by Otamamori917** [comment]
You can change their opacity in settings bro

**Comment by camelStyleUser** [comment]
if pressing f5 doesnt work check power laser opacity in graphics settings

**Comment by Gab304** [comment]
> You can change their opacity in settings bro

i don't have this setting, i can only make them visible or invisible, but now they are perpetually invisible

**Comment by camelStyleUser** [comment]
did you press f5

**Comment by Gab304** [comment]
the opacity setting was in "graphics", i went to "commands", thanks

**Comment by camelStyleUser** [comment]
\*changes opacity of power lasers to 0\*
power lasers dont render
\*this is certainly a bug\*
