### ISSUE TITLE
erekir core units carry ozone containers to kill all the enemies

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry#8900]
### Platforms

Windows

### Build

145.1

### Issue

it's easy for erekir core units to kill any enemy, even without any turret or unit. it carries a liquid container full of ozone, and bombing the ground super quickly.even the collaris can only afford once, and dies in the second bomb.

it happens samely on mega and oil.

### Steps to reproduce

1.control a evoke
2.produce some ozone, put them into a container
3.carry the container
4.fly to the center of the enemies
5.drop the container
6.watch fireworks

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Balancing issue, not bug.
