### ISSUE TITLE
Hidden servers show up

### ISSUE THREAD

**Issue by Rovstam** [Anuken/Mindustry#8906]
### Platforms

Windows

### Build

145.1

### Issue

![image](https://github.com/Anuken/Mindustry/assets/124090007/a44faaf5-b9a6-41be-bd7c-b1cc4c5ab110)

### Steps to reproduce

Switch from hidden to non hidden servers.

### Mods used

No.

### Save file

No.

### (Crash) logs

No.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rovstam** [comment]
Wierd...

**Comment by Rovstam** [comment]
![image](https://github.com/Anuken/Mindustry/assets/124090007/5bb5504f-4a28-4e4d-89f2-5ba4e941eebc)

**Comment by Rovstam** [comment]
i mean it works, but sometimes doesnt. It gets fixed by clicking on the 'lupa' (spanish word)
![image](https://github.com/Anuken/Mindustry/assets/124090007/417f93a1-7e42-4c15-9d3d-1d2fe551dfdb)

**Comment by Rovstam** [comment]
"magnifying glass" == Lupa

**Comment by Rovstam** [comment]
![image](https://github.com/Anuken/Mindustry/assets/124090007/e9db6510-d218-496f-9857-afc0bdcdfe75)

**Comment by Anuken** [comment]
> Mods used
No.

You say this, however. I can see in the background:

![image](https://github.com/Anuken/Mindustry/assets/10100000/9740fe27-4f48-4cad-ae25-ca184c59d5c8)

You are using foos. This is not relevant to vanilla.

**Comment by Rovstam** [comment]
Your majesty is right....
I apologize for wasting your PRECIOUS time with my lame actions....

**Comment by Anuken** [comment]
![969375577112993912](https://github.com/Anuken/Mindustry/assets/10100000/c5264e05-9228-4195-8163-a7492ba14fb2)
