### ISSUE TITLE
Mindustry crashes after 5 minutes of playing

### ISSUE THREAD

**Issue by gitmanbloggus** [Anuken/Mindustry#8915]
### Platforms

Android

### Build

release 145.1, Google play

### Issue

after about 5 minutes, mindustry crashes due to using up to 900mb of ram, crashing the entire game. this also happens during menu changes, graphical effects, and waves

### Steps to reproduce

Have a android device without any mods on any map over 400x400

### Mods used

None

### Save file

Can't import due to a save size of 232mb

### (Crash) logs

[crash.txt](https://github.com/Anuken/Mindustry/files/12315714/crash.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This doesn't happen on my device. The only crashes that log has are those caused by mods.

> Save file
Can't import due to a save size of 232mb

This is **required**. I need the map you were playing on, not your entire game data.
