### ISSUE TITLE
crash.

### ISSUE THREAD

**Issue by Rovstam** [Anuken/Mindustry#8916]
### Platforms

Windows

### Build

145.1

### Issue

Game crashes randomly at any point.
I blame my mods, but you should look into it. Might be something.

### Steps to reproduce

Play campaign.

### Mods used

[deltanedasdev-mode.zip](https://github.com/Anuken/Mindustry/files/12317441/deltanedasdev-mode.zip)
[deltanedasui-lib.zip](https://github.com/Anuken/Mindustry/files/12317442/deltanedasui-lib.zip)
[deltanedasunit-factory.zip](https://github.com/Anuken/Mindustry/files/12317443/deltanedasunit-factory.zip)
[ferlernextended-ui-v7.zip](https://github.com/Anuken/Mindustry/files/12317444/ferlernextended-ui-v7.zip)
[flintyxautoresearch.zip](https://github.com/Anuken/Mindustry/files/12317445/flintyxautoresearch.zip)
[meepoffaithtesting-utilities-java.zip](https://github.com/Anuken/Mindustry/files/12317446/meepoffaithtesting-utilities-java.zip)
[xzxadixzxscheme-size.zip](https://github.com/Anuken/Mindustry/files/12317447/xzxadixzxscheme-size.zip)

### Save file

[I love you Anuken.zip](https://github.com/Anuken/Mindustry/files/12317451/I.love.you.Anuken.zip)

### (Crash) logs

[crash-report-08_10_2023_16_09_41.txt](https://github.com/Anuken/Mindustry/files/12317452/crash-report-08_10_2023_16_09_41.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rovstam** [comment]
This popped immediately afterwards the game closed.
![image](https://github.com/Anuken/Mindustry/assets/124090007/ff547105-e1a8-4dd9-973e-0524516a4bea)

**Comment by Anuken** [comment]
It's your mods. Specifically scheme-size.
