### ISSUE TITLE
Mono (draugs) ai breaks, stop mining

### ISSUE THREAD

**Issue by the-red-soul** [Anuken/Mindustry#8917]
### Platforms

Windows

### Build

steam 145.1

### Issue

Seemingly at random monos will just stop mining copper and lead, I have seen it happen in campaign in solo and multiplayer, and custom maps.  The map save I post is from a custom game where apparently they always break ai, and are currently broken.

### Steps to reproduce

I have no idea sorry, It happens randomly from what I can gather. Maybe when something is built ontop of the tile they are currently mining? But only on occasion. Seems to always break when they need to mine lead.

### Save file

[monoaibreak.zip](https://github.com/Anuken/Mindustry/files/12317558/monoaibreak.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I'm not quite sure what I'm supposed to do in the map - I can randomly block off ores for about 10 minutes, or watch them mine different ores, or force them to move/switch constantly, but nothing buggy ever happens. You don't have any screenshots of the behavior or description of what you did before it started happen - for all I know you could be using Foo's (which messes with the AI and ore indexing).

**Comment by overdramaticpanromantic** [comment]
This has happened to me too, without Foo's, with no mods. No idea what causes it.

**Comment by the-red-soul** [comment]
the behavior is they just stop moving and picking new plots to mine. if they were mining something then they continue to mine it forever until pushed out of range, at which they stop moving and hold onto their inventory. i would love to give more info but i dont know. i only notice when i run out of copper or lead because they stopped functioning. and that could take several minutes to do so depending on the map. but it is def a vanilla thing. gotta love intermittent failures.

**Comment by Anuken** [comment]
Do you have a screenshot of what the plots look like when that happens?

**Comment by the-red-soul** [comment]
![example 1 ore](https://github.com/Anuken/Mindustry/assets/31638088/8df41ac4-488a-4b31-a5f0-5b21e47ba4ec)
![ai example 3](https://github.com/Anuken/Mindustry/assets/31638088/090205fd-024c-469a-9ee5-76bfc18cbccf)
![example 2 ore](https://github.com/Anuken/Mindustry/assets/31638088/f217c493-6fd7-44b5-9f3f-b957523ff4bf)

when loading into these maps the ai was working normally despite being broken beforehand, its the same custom map i sent, and then campaign sectors overgrowth and stained mountains. I always leave at least one ore tile open for them to mine.

**Comment by the-red-soul** [comment]
reviving this to post another map, i had the ai break on me twice today, once in a pvp map where i was crux, another in a custom map which i dont have a save for. the crux ai break happened relatively fast, but still unsure what caused it. the draugs just kept mining copper and never switched to lead
[pvp ai break.zip](https://github.com/Anuken/Mindustry/files/12447449/pvp.ai.break.zip)

**Comment by Bob90** [comment]
Same here. 
Only seen on multiplayer, but mono doesn't start mining. Then it will. Then only one of them. Then they don't mine lead, just copper.
This was on Omega skyblocks.

**Comment by Alstin112** [comment]
I know an effective way to reproduce this bug. Here are the steps:

1. This bug can occur with various types of ore, so the first step is to choose 1 type of ore.
2. Count the number of ores of this type exposed to air (i.e., not covered by any buildings) at the moment you loaded the map.
3. Build over half of the uncovered ores of this type. It's not necessary to cover differents ore blocks; you can simply build and break over a single ore block `ceil(N/2)` times, as it works in the same way.

Now we have succesfully triggered the bug for all the mining units for this ore type, and no one else can mine this ore again until the map be reloaded. This can be done with multiples types of ores.

If all ore types for a mining unit are glitched, two things can happen:

1. If a unit has selected block to mine, (after you command to mine, each robot will choose the closest ore block to the core, though not necessary all the same), it will mine forever. If you cover, the robot will stop until you uncover the select block again.
2. If a unit does not has a selected block, the unit simply never mine.

To reset the list of gliched ores, the only way i know is to reload the map. Saving it and loading will resolve the problem. As for servers, I don't know if there is a way to reload a map on servers; if not, simply closing and reopening it will solve the issue.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/b7783a85-b5dc-48be-acf8-a8d78675cb88)

That's actually very helpful, I managed to reproduce it immediately. Will investigate.

**Comment by overdramaticpanromantic** [comment]
swag
