### ISSUE TITLE
Players who join the game in multiplayer mode die repeatedly and do not see enemy units

### ISSUE THREAD

**Issue by westernat** [Anuken/Mindustry#8924]
### Platforms

Windows

### Build

v145.1

### Issue

This happens whether I enter my friend's map or a friend enters my map. After about 15 seconds of entering the map, the joining player starts repeating the following steps: the health drops to zero, the player is judged dead (cannot be built), and the player is resurrected in place full of blood (can build).This process is quite fast, 3 times a second.

### Steps to reproduce

Nothing was doing

### Save file

[issue.zip](https://github.com/Anuken/Mindustry/files/12327524/issue.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I am surprised this has not been reported earlier; this is an extremely nasty bug and ended up being far more complex than it seemed.
