### ISSUE TITLE
Ground units

### ISSUE THREAD

**Issue by unikur1570** [Anuken/Mindustry#8926]
### Platforms

Windows

### Build

release build 145.1

### Issue

Ground units have a pretty good ability to fly and that's cool but after 7.0 there is one small problem. To fly on a ground unit, you can select it by pressing the shift key and select the flight mode, however, in addition to all this, you can sit in this unit and also press the shift key to fly. It turns out that the shift key is used not only to select, but also to fly on a unit, which really interferes (if you are sitting in a ground unit and want to select your army, you will not succeed because the shift key is used not only to select, but also to fly on a ground unit) . It really bothers me especially in pvp, although it's not so significant because you can just sit in an air unit, etc., but it's unpleasant in any way) Thank you for such a game!

### Steps to reproduce

I played pvp with my  friend :)

### Mods used

-

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This isn't a bug.

**Comment by camelStyleUser** [comment]
rebind command key to R-shift for example

**Comment by unikur1570** [comment]
> This isn't a bug.
Ok, sorry I dednt understand). How about binding this button from the very beginning on something else - for example, selecting units not on shift but on ctrl?

**Comment by Anuken** [comment]
> Ok, sorry I dednt understand). How about binding this button from the very beginning on something else - for example, selecting units not on shift but on ctrl?

No, ctrl is already used for many others things, and shift is convenient. People are used to it.
