### ISSUE TITLE
Pathfinder bug

### ISSUE THREAD

**Issue by SSTentacleSS** [Anuken/Mindustry#8927]
### Platforms

Linux

### Build

v145.1

### Issue

![image](https://github.com/Anuken/Mindustry/assets/91948148/a308cd7a-ef6d-455d-a538-2f54ee126339)

Now server spam java.lang.ArrayIndexOutOfBoundsException and don't accept any connection

### Steps to reproduce

don't know the real reason

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
