### ISSUE TITLE
Putting a reinforced liquid tank next to neoplasia reactors prevents reactors from exploding

### ISSUE THREAD

**Issue by noname1066** [Anuken/Mindustry#8935]
### Platforms

Windows

### Build

release build 145.1

### Issue

Same as the issue [issue#8933](https://github.com/Anuken/Mindustry/issues/8933), but I managed to reproduce it in my client and provided a vaild save file.

### Steps to reproduce

1. Put down a neoplasia reactor and make it running.
2. While it's not full of neoplasia, put down a reinforced liquid tank next to it and wait.
3. When the tank is full, you should see the reactor is still running and not exploding.

### Mods used

None

### Save file

[rep.zip](https://github.com/Anuken/Mindustry/files/12336735/rep.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by AwEsOmEyEeTuSmAn** [comment]
This seems to be the case for me as well.

Linux
Build 145.1

**Comment by kJNCwBUq** [comment]
Thanks for your work, really
