### ISSUE TITLE
cant log into midustry

### ISSUE THREAD

**Issue by toasterpp1** [Anuken/Mindustry#8937]
### Platforms

Android

### Build

dont have one

### Issue

i cant log into mindusty as it will keep buging out and close the game after a minute or two

### Steps to reproduce

i was just loging into mindusty when it just kicked me out witch happends but it wouldent let me in

### Mods used

none

### Save file

i dont think i have one

### (Crash) logs

keeps crashing 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JojoFR1** [comment]
No build, no log, no save = no help
