### ISSUE TITLE
Blocks larger than 5x5 crash instantly when damaged

### ISSUE THREAD

**Issue by TechFish3000** [Anuken/Mindustry#894]
**Platform**: All

**Build**: latest (97? 98?)

**Issue**: When any block larger than 5x5 gets damaged, the game crashes because there are 'no "crack" sprites larger than 5x5' (so i'm told)

**Steps to reproduce**: Modding in large blocks, accidentally start wave, modded drill (8x8) gets shot once, game crashes.

**Comment by Anuken** [comment]
Fixed. Larger blocks will not have cracks anymore.
