### ISSUE TITLE
Cannot pause building in Singleplayer

### ISSUE THREAD

**Issue by mahdiyadiilavi1** [Anuken/Mindustry#8941]
### Platforms

Android

### Build

145.1

### Issue

It's impossble to to pause building in mobile,
Only way to do it is by pausing entire game
You can pause build plan on other platforms like in pc you can press E button (default button) to pause a plan

I think the best place for such button would be next to "copy" button on bottom left(the same place as "repair region" button)

Or maybe replace "pause game" button
(Not pause menu)

### Steps to reproduce

It's not a bug, and does not exist in the game.
No way to reproduce.

If you want to force me to tell you:
1. Go to a single player map
2. Start building something
  - then press on ~non-existing~ pause plan button to pause build plan
  - Or just click on _existing_  pause game button(not pause menu)

### Mods used

1. Not related to mods
2. No mods used

### Save file

Save files reqired for in game events, not for something that does not exist. Right?

### (Crash) logs

No, not a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> It's not a bug

This reporting form is for bugs only.

**Comment by camelStyleUser** [comment]
pro suggestions in bugs
