### ISSUE TITLE
Use Blast compound on Steam generator make it damage.

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#8946]
### Platforms

Android

### Build

145.1

### Issue

Use Blast compound on Steam generator make it damage and not fully power output.

https://github.com/Anuken/Mindustry/assets/44901211/dcc338f2-3a53-4cf2-ba8f-736d63c535a2

### Steps to reproduce

1. Build a Steam generator.
2. Input water.
3. Input Blast compound.
4. Wait for it.

### Mods used

None

### Save file

[SteamBlast.zip](https://github.com/Anuken/Mindustry/files/12370364/SteamBlast.zip)
I must zip it, github not allow __msav__ file type. Or something wrong with me.

### (Crash) logs

No crash log

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Otamamori917** [comment]
*puts combustible material in*
Works normally
*puts highly explosive combustible material in* 
Takes damage
*clearly a bug*

**Comment by camelStyleUser** [comment]
it should explode instantly:trolley:

**Comment by SITUVNgcd** [comment]
> What do you think is supposed to happen when you put explosives in a generator?

Ah, i see!
