### ISSUE TITLE
Save file bug

### ISSUE THREAD

**Issue by Blazer2330** [Anuken/Mindustry#8948]
### Platforms

Android

### Build

145.1

### Issue

I made a mistake when trying to capture a sector and tried to load it back and it crashed. I restarted the game and got back on the game again, it was bugged.
I see my sectors i captured from before but when I played the sector I wanted, it was reset, same for the rest of sectors I captured

In other words, it showed them captured but its not

### Steps to reproduce

I save my save file everytime Im about to make a big sector capture and it was only 2 times I did so

### Mods used

FactoryDusty texture pack

### Save file

#
[rebirth, new.zip](https://github.com/Anuken/Mindustry/files/12376633/rebirth.new.zip)

### (Crash) logs

![Screenshot_20230818-022859_Mindustry](https://github.com/Anuken/Mindustry/assets/142574175/b380d112-0202-45be-b530-8f73102d852e)
![Screenshot_20230818-022855_Mindustry](https://github.com/Anuken/Mindustry/assets/142574175/02cbdcc9-ea8c-45a0-b0c2-94f5fd1b19fd)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The save file provided is corrupted. I've never been able to reproduce any issues with creating save files on my devices, so I'm not sure why this is the case. There isn't much I can do about this.

**Comment by Blazer2330** [comment]
> The save file provided is corrupted. I've never been able to reproduce any issues with creating save files on my devices, so I'm not sure why this is the case. There isn't much I can do about this.

**Comment by Blazer2330** [comment]
So I just have to start over again huh. This bug have been here since the new updates. Ever since the new update when the new world <erekri> come in the game for me, the save file bug started even before that, I once completed the world and had to reset due to the save file being corrupted due to the new update. Before the "command" feature was added, the save file bug didn't exist for me. I started in 2020 and this bug didn't even existed for me, and ever since the new updates that finally come in after a long time this bug existed for me, it was so bad I ended up stop playing.
Now 3 years later this bug still existed and now I have to play It over again. I wish you do something about this please, try and fix this
