### ISSUE TITLE
Modded turret parts not overriding existing turrets (that has no parts)

### ISSUE THREAD

**Issue by Xaphironius** [Anuken/Mindustry#8949]
### Platforms

Windows

### Build

145.1

### Issue

Existing turrets doesnt get overriden with custom turret part sprites. I tried putting the sprites in sprites / sprites-override folder but neither way works.
![image](https://github.com/Anuken/Mindustry/assets/85978775/d2e67806-89df-4e3f-8554-c942ad6337ce)
![image](https://github.com/Anuken/Mindustry/assets/85978775/09e06892-5950-4bcb-acf2-ecd691ba460a)

### Steps to reproduce

Override existing turrets (without parts) with custom turret parts.

### Mods used

https://github.com/Xaphironius/Yellow-Dawn-Expansion-Mod

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/12381484/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You can't override sprites that don't exist. This isn't a bug. If you want the new parts from your mod to work in that turret, you need to set the RegionPart name to the full modded region name with the suffix.

**Comment by Otamamori917** [comment]
Lol ![Screenshot_20230818_132423_Discord.jpg](https://github.com/Anuken/Mindustry/assets/117782096/71b77ca5-1b18-4bb6-80f2-3d7dce3cf4c8)

**Comment by Otamamori917** [comment]
Lol @Anuken ![Screenshot_20230818_132423_Discord.jpg](https://github.com/Anuken/Mindustry/assets/117782096/fbc91914-e747-4345-ad55-03ea5c6ce1ab)
