### ISSUE TITLE
bug with the servers

### ISSUE THREAD

**Issue by cooly228** [Anuken/Mindustry#8951]
### Platforms

Android

### Build

145.1

### Issue

I'm trying to play in community servers, but i can't, it doesn't even displayed (also I've seen similar problem, but I'm not sure this is same)

### Steps to reproduce

1. launch the game
2. click the "online game" button
3. wait 10 seconds

### Mods used

no mods being used 

### Save file

[Uploading мои сохры в минде2.zip…]()

### (Crash) logs

not a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
can you go to [here](https://raw.githubusercontent.com)?(checking if firewall blocks raw.githubusercontent.com)

**Comment by Anuken** [comment]
Your device can't fetch the server list, either because your network blocks the server list or you are using an Android device that doesn't support HTTPs properly.
