### ISSUE TITLE
Abandoned sector not having enemy units

### ISSUE THREAD

**Issue by Rovstam** [Anuken/Mindustry#8952]
### Platforms

Windows

### Build

145.1

### Issue

I skipped 30 waves in Windswept Islands
All the enemies that spawned didnt come, or they dissapeared immediately

### Steps to reproduce

Abandon a sector, recapture it, skip all waves.

### Mods used

[ferlernextended-ui-v7.zip](https://github.com/Anuken/Mindustry/files/12386414/ferlernextended-ui-v7.zip)
[xzxadixzxscheme-size.zip](https://github.com/Anuken/Mindustry/files/12386415/xzxadixzxscheme-size.zip)

### Save file

[why my game bug.zip](https://github.com/Anuken/Mindustry/files/12386418/why.my.game.bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> Abandon a sector, recapture it, skip all waves.

This order of operations seems wrong - once you capture a sector, there are no more waves...?

**Comment by Rovstam** [comment]
Then the sector should not show any waves
I thought i had to have more fun, and as i have scheme size i can see enemy units: They sort of spawn, but get despawned immediately as i already said

Either disable the wave counter or enable waves; whatever you please.

**Comment by Rovstam** [comment]
By the way: Foo's client.

**Comment by Anuken** [comment]
> By the way: Foo's client.

I do not deal with any issues found while using Foo's client. It makes many invasive changes to the game's code. Only report bugs that can be reproduced in vanilla with no mods.
