### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by Tobelusi** [Anuken/Mindustry#8953]
### Platforms

Android

### Build

151.1

### Issue

![image](https://github.com/Anuken/Mindustry/assets/138158585/33742d65-ba7b-40df-838b-d62953517ce7)
I cant build something because the map is to large I think it the map is above 700x700 its not possible to build something or to fly around. Is there a way to fix it? (on a server)

### Steps to reproduce

create a map above 1000x1000 and load it into a server and start it

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Tobelusi** [comment]
145.1*

**Comment by Anuken** [comment]
> Save file
THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
