### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by Tobelusi** [Anuken/Mindustry#8954]
### Platforms

Android

### Build

145.1

### Issue

I cant build something because the map is to large I think it the map is above 700x700 its not possible to build something or to fly around. Is there a way to fix it? (on a server)
![image](https://github.com/Anuken/Mindustry/assets/138158585/40ec16cd-8a81-45f6-b8ed-bdb5faf74ce1)

### Steps to reproduce

create a map above 1000x1000 and load it into a server and start it
singelplayer its working only on multiplayer its not working you cant do something only start rounds

### Mods used

no mods

### Save file

[map.zip](https://github.com/Anuken/Mindustry/files/12386897/map.zip)
A MAP WHAT IS BETTER THAN 1000x1000 on multiplayer server!!!! with a core and enemy spawn! on Multiplayer server!

### (Crash) logs

no crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by DX-36** [comment]
the vanilla limit for maps is 600*600 tiles, and that's for a very good reason

**Comment by Anuken** [comment]
Cannot reproduce the issue on desktop. On mobile, it runs out of RAM completely, so I can't even test it properly.

![image](https://github.com/Anuken/Mindustry/assets/10100000/b0387b3c-51e8-4776-b301-e6446dfdc32d)


This map is 6098x6098. The maximum supported map size in the editor (without hacks or mods) is about **ten times** smaller. Don't use such maps, they are not supported.

**Comment by Tobelusi** [comment]
Is there a way to play it with friends on a server?

**Comment by DX-36** [comment]
I would not recommend you play a map with that large of an area

**Comment by Anuken** [comment]
> Is there a way to play it with friends on a server?

No, use a smaller map.

**Comment by rekokoro** [comment]
Well, I hit that "ship despawn" problem in a few days before on PC, in my case game was so busy that it forgot to "respawn" me sometimes when I got out from ships/buildings - so I was the same as author in ship with 0 hp. To appear, I had to manually enter anything and exit again. That happened on 600x500 map with around 1000 erekir units, spamming rockets at each other.

**Comment by Anuken** [comment]
That sounds unrelated, a similar issue was reported and fixed  a few weeks ago.
