### ISSUE TITLE
Bridge conduit not accepting inputs from the side in specific circumstance

### ISSUE THREAD

**Issue by KinForr776** [Anuken/Mindustry#8957]
### Platforms

Windows

### Build

145.1

### Issue

https://github.com/Anuken/Mindustry/assets/75912858/b80ba4ff-0da1-4d3d-9695-a4e40b03c77d

The bridge conduit isn't accepting inputs from its sides when it should be.

### Steps to reproduce

The conduit doesn't accept inputs from the side after connecting a different bridge conduit then disconnecting it by placing another bridge conduit in its way.

### Save file

i cant fit my save file because the file size its over 25mb, so here is the mega link for it
https://mega.nz/file/y7Y1VIhS#5UkAC_sIdOteizxblYSzzfitCBzzdUjkt1e3eydHB1I

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by stacktrace-error** [comment]
bridges do not accept when they are the output
