### ISSUE TITLE
Guardian unit have missing glowing outline

### ISSUE THREAD

**Issue by Cry0flu1d** [Anuken/Mindustry#8961]
### Platforms

Windows

### Build

Steam Build 145.1

### Issue

Guardian unit used to have glowing outline, but it was gone in current version.
![image](https://github.com/Anuken/Mindustry/assets/99197260/dabc6ff1-b597-4522-8001-9a5f7e662b8c)
Is it removed or just bugged?

### Steps to reproduce

spawn a unit with guardian status in waves or by world processor

### Mods used

no mod used

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/12388005/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
It was removed.
