### ISSUE TITLE
Ravine - insufficient core resources

### ISSUE THREAD

**Issue by summoner001** [Anuken/Mindustry#8963]
### Platforms

Android

### Build

Steam v145 version, Android Mindustry Bleeding Edge 24341 

### Issue

Good Day!

Sorry for my english!

I'm new in Mindustry. Today I Play with steam version of the game. I completed a sector on Erekir and I want to start the next level name Ravine but can't launch the core, because Tungsten is missing.

![Screenshot_20230820-213010](https://github.com/Anuken/Mindustry/assets/11212632/d9c305a9-2fa0-42a5-9129-b9afb32bf04e)

Whats wrong with this. I have Tungsten.

I installed the android version of the game. And the problem is same with steam version.

### Steps to reproduce

Start the Ravine Sector

### Mods used

I don't use mods

### Save file

[Mindustry20230820-3.zip](https://github.com/Anuken/Mindustry/files/12389024/Mindustry20230820-3.zip)

### (Crash) logs

I have no crash logs.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> I have Tungsten.

No, you don't have it in that sector. Go in a sector with tungsten in the core, and launch from there instead.

**Comment by summoner001** [comment]
Ahhha. Thank you for your very fast reply! Its working for now. Sorry for my confusion. Have a nive day!

**Comment by Rovstam** [comment]
🤦‍♂️
