### ISSUE TITLE
Arc shield doesn't work

### ISSUE THREAD

**Issue by Antlrr** [Anuken/Mindustry#8964]
### Platforms

Windows

### Build

145.1

### Issue

The ArcShieldAbility seems to not work properly. the shield only works on certain areas, preferably the 45 degree cones on four diagonals
![arc shield](https://github.com/Anuken/Mindustry/assets/81817551/e6763e7a-50ff-4bc9-a798-d2c951ab8c84)

### Steps to reproduce

make a unit with the arc shield ability, and watch enemy bullets pass through and the shield not getting damaged

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rovstam** [comment]
You forgor the savegame
He will not respond this and close it.
# upload the stupid savegame #

**Comment by SpaceEarthEX** [comment]
This sounds like save file required

**Comment by Antlrr** [comment]
how do you edit an issue

**Comment by Anuken** [comment]
Cannot test without a mod example.
