### ISSUE TITLE
Incorrect spelling of "Metalglass"

### ISSUE THREAD

**Issue by BlackenedVoid** [Anuken/Mindustry#8968]
### Platforms

Android

### Build

145.1

### Issue

"Metalglass" is spelled incorrectly as "Metaglass" in Serpulo Tech Tree.

### Steps to reproduce

1. Open Serpulo Tech Tree and find "Metalglass"

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
(no its actually called metaglass)

**Comment by camelStyleUser** [comment]
(also reporting "typos" as bugs is stupid)

**Comment by Slotterleet** [comment]
~~since when has metaglass had a typo, do you mean it was all wrong for all this time~~

**Comment by Otamamori917** [comment]
lol
![image](https://github.com/Anuken/Mindustry/assets/117782096/df40a5f5-89f7-4219-861d-65e9e4b4f6a9)
"meta" is on purpose

**Comment by NazrinNya** [comment]
no comments
