### ISSUE TITLE
Armored ducts accept items from duct bridges

### ISSUE THREAD

**Issue by EndersteveGamer** [Anuken/Mindustry#8971]
### Platforms

Windows

### Build

145.1

### Issue

Duct bridges can input items from the side of armored ducts
![image](https://github.com/Anuken/Mindustry/assets/85014963/e47ee24e-b6ef-4f5f-81c0-a7ff9508c8d0)

### Steps to reproduce

- Place a duct bridge
- Place an armored duct, so the output of the duct bridge is on the side of the armored duct
- Input items in the bridge
- Items can enter the armored duct

### Mods used

None

### Save file

[creative_erekir.zip](https://github.com/Anuken/Mindustry/files/12429366/creative_erekir.zip)

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by stacktrace-error** [comment]
same behavior as with conduits, very likely to be intentional

**Comment by Anuken** [comment]
This is intentional. Bridges have only one output direction, there's no reason to have a bridge output rotated into a conduit and *not* have it accept from that side.
