### ISSUE TITLE
Mindustry not open

### ISSUE THREAD

**Issue by egor0044** [Anuken/Mindustry#8972]
### Platforms

Linux

### Build

145.1 (latest)

### Issue

I have arch linux. And also I have an assistant yay (aur). and i tried to install mindustry through it: yay -S mindustry.

However, I get an error:

[egor@archlinux ~]$ yay -S mindustry
AUR Explicit(1): mindustry-1:7.0_145.1-1
:: PKGBUILD up to date, skipping download: mindustry
   1 mindustry (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
   1 mindustry (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: mindustry 1:7.0_145.1-1 (Fri 25 Aug 2023 2:29:43 PM)
==> Retrieving sources...
   -> Found mindustry-145.1.tar.gz
   -> Found mindustry.desktop
   -> Foundmindstry.sh
   -> Found mindustry-server.desktop
   -> Found mindustry-server.sh
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
     mindustry-145.1.tar.gz ... Passed
     mindustry.desktop ... Passed
     mindustry.sh ... Passed
     mindustry-server.desktop ... Passed
     mindustry-server.sh ... Passed
:: (1/1) Parsing SRCINFO: mindustry
==> Making package: mindustry 1:7.0_145.1-1 (Fri 25 Aug 2023 2:29:44 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
   -> Found mindustry-145.1.tar.gz
   -> Found mindustry.desktop
   -> Foundmindstry.sh
   -> Found mindustry-server.desktop
   -> Found mindustry-server.sh
==> Validating source files with sha256sums...
     mindustry-145.1.tar.gz ... Passed
     mindustry.desktop ... Passed
     mindustry.sh ... Passed
     mindustry-server.desktop ... Passed
     mindustry-server.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
   -> Extracting mindustry-145.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: mindustry 1:7.0_145.1-1 (Fri 25 Aug 2023 2:29:46 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
To honor the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
No Android SDK found. Skipping Android module.

FAILURE: Build failed with an exception.

*What went wrong:
A problem occurred configuring root project 'Mindustry-145.1'.
> Could not resolve all files for configuration ':classpath'.
    > Could not find com.github.Anuken.Arc:packer:b718875065.
      Searched in the following locations:
        - file:/home/egor/.m2/repository/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
        - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
        - https://dl.google.com/dl/android/maven2/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
        - https://oss.sonatype.org/content/repositories/snapshots/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
        - https://jitpack.io/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
        - https://plugins.gradle.org/m2/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.pom
      Required by:
          project :

* try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
==> ERROR: A failure occurred in build().
     Aborting...
  -> error making: mindustry-exit status 4
  -> Failed to install the following packages. Manual intervention is required:
Mindustry - exit status 4
[egor@archlinux ~]$

When compiling code from git clone https://github.com/Anuken/Mindustry.git on your own, the same thing happens.

I decided to download Mindustry from the release:

[egor@archlinux ~]$ cd Games/
[egor@archlinux Games]$ mkdir Mindustry
[egor@archlinux Games]$ cd Mindustry/
[egor@archlinux Mindustry]$ curl -O https://github.com/Anuken/Mindustry/releases/download/v145.1/Mindustry.jar
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
   0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
[egor@archlinux Mindustry]$ java -jar Mindustry.jar
Error: Invalid or corrupt jarfile Mindustry.jar
[egor@archlinux Mindustry]$

Why can't I open your game?

### Steps to reproduce

Just tried to compile the game and open it.

### Mods used

Missing

### Save file

Missing

### (Crash) logs

Missing

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
``` 
$ sha1sum Mindustry.jar
c2a6cc5791ef9b107b7547709c6b274d7f936647  Mindustry.jar
```

whats the sha1 hash on your end?jar on my device works fine

**Comment by camelStyleUser** [comment]
(and yes im using linux)

**Comment by egor0044** [comment]
[egor@archlinux Mindustry]$ sha1sum Mindustry.jar
da39a3ee5e6b4b0d3255bfef95601890afd80709  Mindustry.jar
[egor@archlinux Mindustry]$ da39a3ee5e6b4b0d3255bfef95601890afd80709  Mindustry.jar
bash: da39a3ee5e6b4b0d3255bfef95601890afd80709: command not found
[egor@archlinux Mindustry]$ c2a6cc5791ef9b107b7547709c6b274d7f936647  Mindustry.jar
bash: c2a6cc5791ef9b107b7547709c6b274d7f936647: command not found
[egor@archlinux Mindustry]$

**Comment by egor0044** [comment]
@camelStyleUser, can you help me please?

**Comment by egor0044** [comment]
@camelStyleUser
[egor@archlinux Mindustry]$ java -jar Mindustry.jar 
Error: Invalid or corrupt jarfile Mindustry.jar
[egor@archlinux Mindustry]$ rm Mindustry.jar 
[egor@archlinux Mindustry]$ curl -O https://github.com/Anuken/Mindustry/releases/download/v145.1/Mindustry.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[egor@archlinux Mindustry]$ java -jar Mindustry.jar 
Error: Invalid or corrupt jarfile Mindustry.jar
[egor@archlinux Mindustry]$ sha1sum Mindustry.jar
da39a3ee5e6b4b0d3255bfef95601890afd80709  Mindustry.jar
[egor@archlinux Mindustry]$ java -jar Mindustry.jar
Error: Invalid or corrupt jarfile Mindustry.jar
[egor@archlinux Mindustry]$

**Comment by camelStyleUser** [comment]
> @camelStyleUser [egor@archlinux Mindustry]$ java -jar Mindustry.jar Error: Invalid or corrupt jarfile Mindustry.jar [egor@archlinux Mindustry]$ rm Mindustry.jar [egor@archlinux Mindustry]$ curl -O https://github.com/Anuken/Mindustry/releases/download/v145.1/Mindustry.jar % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 [egor@archlinux Mindustry]$ java -jar Mindustry.jar Error: Invalid or corrupt jarfile Mindustry.jar [egor@archlinux Mindustry]$ sha1sum Mindustry.jar da39a3ee5e6b4b0d3255bfef95601890afd80709 Mindustry.jar [egor@archlinux Mindustry]$ java -jar Mindustry.jar Error: Invalid or corrupt jarfile Mindustry.jar [egor@archlinux Mindustry]$

why does this seem like the download was aborted

**Comment by egor0044** [comment]
@camelStyleUser, я попробую скачать с гитхаба самостоятельно.

**Comment by egor0044** [comment]
@camelStyleUser, Oh, I'm sorry that I wrote in Russian. I got it all, thanks!
