### ISSUE TITLE
Elude Dies to wall

### ISSUE THREAD

**Issue by Jaeyun21** [Anuken/Mindustry#8973]
### Platforms

Android

### Build

145.1

### Issue

Elude dies when hitting a natural wall, only seems to happen with other players and not the host

### Steps to reproduce

Make other player control elude, ram into natural walls until it explodes

### Save file

It wont let me add the file for some reason

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by overdramaticpanromantic** [comment]
It might be a world proc thing on Lake exclusively. Try it in a custom game in the lake map

**Comment by stacktrace-error** [comment]
this is a common thing with colliding units, if I were to guess, it's caused by units moving their speed's distance despite being blocked due to not knowing yet

it's very annoying sometimes because running into a wall with anything faster than a mace can cause it

**Comment by Anuken** [comment]
Save files required.
