### ISSUE TITLE
Issue with using Payload Mass driver with dual liquid setup

### ISSUE THREAD

**Issue by LordofHanover** [Anuken/Mindustry#8976]
### Platforms

Android

### Build

145.1

### Issue

![Screenshot_20230826-142615-122](https://github.com/Anuken/Mindustry/assets/143286718/32a1a3fc-43b3-4ba2-915c-ea7eebb6fc21)

Weird issue that happens when you unload a liquid container then try to fill it with a different liquid, the unloader or container somehow dumps a little bit of the first liquid (in the screenshot slag) and put it into the loader next in the chain, despite it already being full of arkycite.  It would make sense if the loader was empty, but it wasn't.

### Steps to reproduce

1. Create a Payload Mass driver set up with a loader and unloader on each side
2. Have one side load one type of liquid, and the other side a different one, each one receiving the opposite's liquid
3.  Send a liquid container through the system
4. Have it breakdown when it has to unload a liqu

### Save file

https://drive.google.com/file/d/1cyDzTNZMeEoiKqqTeq8Hkj2wsOvfuQj5/view?usp=drivesdk 

(Zipper game file)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by stacktrace-error** [comment]
ah, the joys of float imprecision!

**Comment by Anuken** [comment]
This isn't really a bug; just really bad design. Never place loaders next to unloaders. (Maybe they shouldn't accept liquids from each other for convenience, but that's a separate matter.)

Here's what happens:

1. Container unloads its slag into unloader
2. Container enter loader
3. Loader dumps all its arkycite into tank, becoming empty for a moment
4. The empty loader now has two sources of liquids next to it: the slag from the unloader, and the arkycite. By chance, the slag goes in first.
5. Slag clogs loader.

**Comment by LordofHanover** [comment]
Fair

**Comment by LordofHanover** [comment]
It just breaks my setup in campaign 😔

**Comment by camelStyleUser** [comment]
just add payload conveyor between them
