### ISSUE TITLE
GPU troubleshooting on a older laptop

### ISSUE THREAD

**Issue by KianWalsh** [Anuken/Mindustry#8977]
### Platforms

Windows

### Build

145.1

### Issue

so my old lenovo w520 laptop has 2 GPU's, and the more powerful one died. booting into the other gpu, I cannot launch mindustry, and I'm wondering if its a big, or just the laptop is too old. windows 10 laptop with directx11, opengl 3.3 and no opencl. when I launch the game, I get "GLEW failed to initialize: missing framebuffer_object extension" error.

is there any way to get this working, or is this laptop simply too old?

### Steps to reproduce

kinda hard ... get a old laptop with a Intel® HD Graphics 3000 gpu, update drivers and launch mindustry 

### (Crash) logs

game will not initialize/create logs ... cant provide crash data

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The laptop/drivers are too old.
