### ISSUE TITLE
Game over menu glitch

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#8979]
### Platforms

Android

### Build

BE 24259

### Issue

I made a custom translation mod (bc the standard german one sucks imo) and after experiencing the first game over I saw that the "Wellen besiegt" (eng.: Waves Defeated) text glitches over itself
![Screenshot_20230827_171118_Mindustry BE](https://github.com/Anuken/Mindustry/assets/108625654/9cc8d2f9-9647-4379-b147-c6734b016cd6)

### Steps to reproduce

- Download mod
- Game over

### Mods used

[translation-mod.zip](https://github.com/Anuken/Mindustry/files/12448296/German.Rewritten.zip)

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/12448294/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/36b4de01-819e-4a9f-8a77-7428d0a5f472)

Cannot reproduce the issue.

**Comment by Yoru-Kitsune** [comment]
Now as I tried it on other maps... it only happens on this one save... weird
