### ISSUE TITLE
Error loading erekir data

### ISSUE THREAD

**Issue by mexTERR4** [Anuken/Mindustry#8982]
### Platforms

Windows

### Build

145.1

### Issue

When uploading Erekir data from one device to another, it removes resources from the cores, and restart the tech tree (in this case, from Android to PC)

Android / PC resources:
![Screenshot_20230827-193914_Mindustry](https://github.com/Anuken/Mindustry/assets/76489418/baac1b44-8168-4fac-9cf0-e20ff2f343fa)
![20230827193620_1](https://github.com/Anuken/Mindustry/assets/76489418/a3930a33-2ac4-4b0a-baf4-bf7480e5a2a7)

Android / PC tech tree:
![Screenshot_20230827-193926_Mindustry](https://github.com/Anuken/Mindustry/assets/76489418/265767e0-97a2-44a1-adb8-b95fca285e12)
![20230827194807_1](https://github.com/Anuken/Mindustry/assets/76489418/24412c2f-9c59-454c-b4df-d72bed95eee1)

### Steps to reproduce

Export Android data, and load data to PC version

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There's no way the save file exported in just the wrong way as to decrease the resources and un-unlock some times. Completely corrupted? Entire saves missing? Maybe, but never like this. You almost certainly imported an older save.

**Comment by overdramaticpanromantic** [comment]
I've had this happen too. Exact same circumstances. This happens on Serpulo too.
