### ISSUE TITLE
Ownership stoleing and early unlocking of resources

### ISSUE THREAD

**Issue by Egyember** [Anuken/Mindustry#8985]
### Platforms

Windows

### Build

145.1

### Issue

Me and my friend was able to unlock hydrogen and ozone on the intersect map using the enemy's electronic separator
![image](https://github.com/Anuken/Mindustry/assets/79502228/0a946572-23af-4cc3-a760-6792a9abd678)
![image2](https://github.com/Anuken/Mindustry/assets/79502228/52043c4b-5655-4481-b581-92fdb3fe645b)
(this is not platform dependend)

### Steps to reproduce

Slightly destroy the electronic separator in the enemy's base and rebuild it. The ownership changes and we can use it. This also work for any block.

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/12458539/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug.

**Comment by DX-36** [comment]
you normally unlock those on the next sector anyway...
