### ISSUE TITLE
Mining units attempt to mine nothing

### ISSUE THREAD

**Issue by cabfile** [Anuken/Mindustry#8988]
### Platforms

Windows

### Build

145.1

### Issue

A unit tries to mine something, copper for example. The tile containing the ore is set to water. The unit _still_ tries to mine copper, however its not getting any anymore. Even when pushed away using something like BetaMindy's Drift Panel, it still comes back to try to mine copper.
Apparently this bug goes away upon saving & loading. It seems to happen on Android too, and might as well happen on other platforms.
~~Alternatively, this bug can be made into a feature by making true water-mining units...~~

### Steps to reproduce

I made a small vertical "flood" map. I made a Mono mine some copper. Once the tile its mining is set to water, the Mono keeps mining.

### Save file

Not a save file, but a map that showcases the bug (not the flood map). After the Mono is made and starts mining copper, flip the switch.
[monobug.zip](https://github.com/Anuken/Mindustry/files/12463579/monobug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by overdramaticpanromantic** [comment]
That's because the game doesn't "register" new tiles until the game is reloaded. Hence why vents added with, say, Scheme Size, don't work until a reload.

**Comment by Anuken** [comment]
Duplicate, already reported.
