### ISSUE TITLE
Touchpad stopped working when holding any key on the keyboard

### ISSUE THREAD

**Issue by matematikaadit** [Anuken/Mindustry#899]
**Platform**: Linux

**Build**: 98

**Issue**: I'm playing Mindustry on a laptop using touchpad instead of mouse. When you hold any key on the keyboard, the touchpad stopped working, i.e. you can't move the cursor or use two finger scroll.

**Steps to reproduce**:

Example selecting block using F

1. Hold F key on the keyboard
2. Try move the cursor using the touchpad
3. The cursor didn't move
4. Expected result: the cursor should move to expand the F selection.

Example rotating block using R

1. Hold R key on the keyboard
2. Try two finger scroll using the touchpad
3. The scroll didn't work
4. Expected result: the scroll should work and the block should be rotated

This issue happen with any key actually. At first I thought it just happened on F/R, but trying it out with other key also make the touchpad stopped working (the cursor didn't move).

This issue didn't happen with mouse input. Plugging in mouse and using them for the game is fine.

**Comment by InValidFire** [comment]
From what you describe this sounds like it's Working as Intended from the device's side.

My laptop's touchpad will disable itself when keys are pressed to prevent the wrist from accidentally moving the mouse or clicking while you type.

One thing you can try though. Move the mouse while you press the keys, it may keep it enabled.

**Comment by Anuken** [comment]
This seems like a device specific issue; it works fine on my Mac and there is no touchpad specific code in Mindustry. Either way, I can't test or ""fix"" it.

**Comment by matematikaadit** [comment]
Ah, you're right. Sorry.

Didn't realize that is the case.

For future traveler on linux that stumble this issue, and want to know how enable the touchpad while typing.

If you're on a desktop environment that has "mouse & touchpad" setting. Use that to enable/disable this behaviour. If you're not, you can follow this instruction.

First, find out your input device using:
```
$ xinput list | grep -i touchpad
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=13	[slave  pointer  (2)]
```

You will get that `id=13` or some other number. This is your touchpad device ID.

Then get the props/setting using this command, replace `13` in the invocation below with your device ID.
```
$ xinput list-props 13 | grep -i typing
	libinput Disable While Typing Enabled (288):	1
	libinput Disable While Typing Enabled Default (289):	1
```

Now we see that it has Disable While Typing Enabled sets to 1 (true). To disable it, use the props ID number above (288), and set it to 0 using this command

```
$ xinput set-prop 13 288 0
```

Now you can still use the touchpad while typing.

To revert the setting, replace 0 with 1 in the previous command. Also note, this setting is temporary until you log out and log back in.
