### ISSUE TITLE
Layering issue with tank path and bridge

### ISSUE THREAD

**Issue by Banaanae** [Anuken/Mindustry#8994]
### Platforms

Android

### Build

145.1

### Issue

When the tank path travels under a bridge (at least the first three tiers, haven't tested anything else) the bridge goes over the tank sprite but the bridge (nodes?) don't
![Screenshot_20230902-172856](https://github.com/Anuken/Mindustry/assets/83927639/68cb3ae3-bde7-46b0-a8bb-0830ebe19939)
![Screenshot_20230902-173316](https://github.com/Anuken/Mindustry/assets/83927639/b2d9cc45-44b9-4551-84ba-8a66b2243c40)
![Screenshot_20230902-173031](https://github.com/Anuken/Mindustry/assets/83927639/b8f2ba8d-a5b1-456c-bbd4-141abf04b300)

### Steps to reproduce

1. Make a tank (easiest to reproduce with T2)
2. Make a bridge
3. Command tank under bridge
4. Ram tank against node

### Mods used

https://github.com/stacktrace-error/gas-colorblindness-pack
(Doubt it's part of the issue)

### Save file

[mindustryexport.zip](https://github.com/Anuken/Mindustry/files/12503448/mindustryexport.zip)
Screenshots taken in Stronghold

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug. Other blocks like power nodes do the same.
