### ISSUE TITLE
Too many enemies

### ISSUE THREAD

**Issue by AlcireAetheron** [Anuken/Mindustry#8995]
### Platforms

Android

### Build

145.1

### Issue

At sector 226 of serpulo the enemy sends out 429 units even at wave 3.

### Steps to reproduce

This happened before when I first landed on the sector and it sends hundreds of enemies even at wave 1.

### Mods used

None.

### Save file

 
[bug.zip](https://github.com/Anuken/Mindustry/files/12504169/bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate / already reported.
