### ISSUE TITLE
Bug with the music

### ISSUE THREAD

**Issue by Urbokie** [Anuken/Mindustry#8997]
### Platforms

Windows

### Build

release build145.1

### Issue

the music of the game didn't work.
i don't have any music when i play even if my music setting is on 100%
but i still have all the sound effect.

the problem affect ALL the music in the game.

### Steps to reproduce

i have this bug since i re-install the game

even if i re-install the game the music still don't work

### Mods used

none

### (Crash) logs

never crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce this issue. No log provided, unable to debug.
