### ISSUE TITLE
bug with all the music

### ISSUE THREAD

**Issue by Urbokie** [Anuken/Mindustry#8998]
### Platforms

Windows

### Build

release build145.1

### Issue

hey its me again 

problem with all the music in game and in the menu

### Steps to reproduce

i just re-install the game

### Mods used

none

### (Crash) logs

[last_log.txt](https://github.com/Anuken/Mindustry/files/12504421/last_log.txt)

is that normal that my logs are not in "game data"?

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Your username contains non-ASCII characters (é), which breaks the audio library. Upstream issue, won't fix. You'll need to run the game with a different user, one that doesn't contain any special characters.

**Comment by Urbokie** [comment]
But the problem is that in itch.io my username is Urbokie  wich contain no « é » and in game it’s Loliman  Envoyé à partir de Courrier pour Windows De : AnukenEnvoyé le :samedi 2 septembre 2023 20:25À : Anuken/MindustryCc : Urbokie; AuthorObjet :Re: [Anuken/Mindustry] bug with all the music (Issue #8998) Your username contains non-ASCII characters (é), which breaks the audio library. Upstream issue, won't fix. You'll need to run the game with a different user, one that doesn't contain any special characters.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Anuken** [comment]
You computer username (Clément), not itch or game username.

**Comment by Urbokie** [comment]
Oh ok that’s a really weird bug thx for all Envoyé à partir de Courrier pour Windows De : AnukenEnvoyé le :samedi 2 septembre 2023 23:29À : Anuken/MindustryCc : Urbokie; AuthorObjet :Re: [Anuken/Mindustry] bug with all the music (Issue #8998) You computer username (Clément), not itch or game username.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
