### ISSUE TITLE
Scathe Turret - Missing range circle

### ISSUE THREAD

**Issue by summoner001** [Anuken/Mindustry#8999]
### Platforms

Linux

### Build

Bleeding Edge 24359

### Issue

If I Place the Scathe turret and connected to he water container the turret's range circle has gone.

Yes, I looked all over the map because I thought it had a huge range, but it's not there.

### Steps to reproduce

Build a Scathe Turret.

Connect water and ammo.

### Mods used

Don't use mods.

### (Crash) logs

No crash.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Nope, you just don't see it.

![image](https://github.com/Anuken/Mindustry/assets/10100000/900c7449-dbf1-4ce2-9d12-3b7be9de7257)
