### ISSUE TITLE
Many items clipping on conveyor

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#9]
![bug3](https://user-images.githubusercontent.com/30189017/33801583-9cb30dd6-dd2d-11e7-8b6c-212f0e9e22ea.gif)

**Comment by Anuken** [comment]
Fixed, with proper layering now too.

![](https://i.imgur.com/fFuRfUr.gif)
![](https://i.imgur.com/3HqGNUj.png)
