### ISSUE TITLE
Browser achievement doesn't trigger

### ISSUE THREAD

**Issue by Xaturn44** [Anuken/Mindustry#9001]
### Platforms

Windows

### Build

7.0 Build 145.1

### Issue

The Browser achievement on Steam doesn't trigger in any way. Importing a map directly from the workshop doesn't work. Neither does importing it from files.

### Steps to reproduce

I have tried to get the achievement but I can't complete in any way. I have tried every way possible, even restarting the game, playing the downloaded map but I was unsuccessful 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by MEEPofFaith** [comment]
# ***IT'S OVER 9000***
