### ISSUE TITLE
Scheme pack tags

### ISSUE THREAD

**Issue by Arrayyan-Uzayr** [Anuken/Mindustry#9003]
### Platforms

Android

### Build

145.1

### Issue

When i disabled a schemepack due to it being in russian every tag stayed trying to delete them with the mod off would get you an error where the file for the tag isnt found and deleting it while the mod is on crashes your game

### Steps to reproduce

Download a scheme pack, have it enabled
Enter a game
Disable the mod
Enter the game
(The bug)Tags are still there
Delete tags from the scheme mod(crashes if deleted while mod enabled)

### Mods used

Any scheme packs

### Save file

something.zip im not sure how this works

### (Crash) logs

Cant find the logs in my files

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug, tags stay forever once you import a schematic with them.

> crashes your game

Crash log required.

> Any scheme packs

Specifics required.
