### ISSUE TITLE
platform: windows   build: 98.1   issue: mods don't work     reproduce: i created a mod, it has all the files, but in the actual game it doesn't appear anything which i made in the mod

### ISSUE THREAD

**Issue by Fekus310** [Anuken/Mindustry#901]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
Use the issue template.
