### ISSUE TITLE
Saves are corrupted (game relaunches already captured sectors)

### ISSUE THREAD

**Issue by ketalox** [Anuken/Mindustry#9010]
### Platforms

Windows

### Build

Steam Build 145.1

### Issue

When I revisited an already captured sector, it relaunched and a lot of my build was gone.

### Steps to reproduce

I tested with 3 other sectors, and I think it only happens if I previously captured a sector more than once and it reverts to the first version

### Save file

[game data.zip](https://github.com/Anuken/Mindustry/files/12508310/game.data.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce any issues with the save provided or my own campaign; the saves simply aren't corrupted, I can load sectors just fine.

**Comment by ketalox** [comment]
ok update, so since I play two devices, luckily I got my original save file back and this is how it's supposed to be. I will upload the original save file here and review a sector like Impact 0078 for both save files and you can see the difference.
[most recent.zip](https://github.com/Anuken/Mindustry/files/12508666/most.recent.zip)

**Comment by ketalox** [comment]
And no, I wasn't launching to lost sectors, it was literally already captured and it relaunched
