### ISSUE TITLE
Crashes during normal gameplay

### ISSUE THREAD

**Issue by Rainbowmineblox** [Anuken/Mindustry#9012]
### Platforms

Android

### Build

146

### Issue

During standard gameplay in the campaign, the game will just shut down for no reason. I've tried all the normal fixes and nothing works. I'm not whats causing it to happen, but hopefully it will be fixed soon.

### Steps to reproduce

I just played the game and it crashed.

### (Crash) logs

[(invalid).zip](https://github.com/Anuken/Mindustry/files/12510964/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rainbowmineblox** [comment]
[save game.zip](https://github.com/Anuken/Mindustry/files/12511790/save.game.zip)

**Comment by TheElectronWill** [comment]
not the save, the _logs_ :)

**Comment by Rainbowmineblox** [comment]
[crashlogs.zip](https://github.com/Anuken/Mindustry/files/12512221/crashlogs.zip)

**Comment by Rainbowmineblox** [comment]
[crashlogs.txt](https://github.com/Anuken/Mindustry/files/12512279/crashlogs.txt)

**Comment by SITUVNgcd** [comment]
> [crashlogs.txt](https://github.com/Anuken/Mindustry/files/12512279/crashlogs.txt)

Nooo!!! **Crashlog**, not **~~lastlog~~**

**Comment by Anuken** [comment]
There are no crash logs anywhere here.
