### ISSUE TITLE
units factory "unconfigures" itself in servers

### ISSUE THREAD

**Issue by alexpvpmindustry** [Anuken/Mindustry#9014]
### Platforms

Windows

### Build

v146

### Issue

unit factories resets its configuration after a few seconds.
so units cant be produced.

![image](https://github.com/Anuken/Mindustry/assets/67626131/87366432-feed-4644-9569-e2f5a233823d)

### Steps to reproduce

go to any build v146 server and try making units, the configuration resets after a few seconds.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by alexpvpmindustry** [comment]
mass drivers also resets after 3 seconds or so

**Comment by way-zer** [comment]
May be #9011.
You could wait for new release or build yourself based on master. Or [MDTX v146](https://github.com/TinyLake/MindustryX/releases/tag/v146.001), I merged that bug fix.

**Comment by Anuken** [comment]
duplicate
