### ISSUE TITLE
Monos bugged they do not harves since build 146

### ISSUE THREAD

**Issue by mrvice** [Anuken/Mindustry#9015]
### Platforms

Windows

### Build

146

### Issue

Monos do not harves ressources they just idle

### Steps to reproduce

build mono

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BalaM314** [comment]
Fixed in a4b1ad3b6748fae57c42c07220bb4bc8fbd3c6a7
