### ISSUE TITLE
Plasma Bores/Cliff Crushers not working when quickly picked up and dropped in the same position

### ISSUE THREAD

**Issue by Cy4nnn** [Anuken/Mindustry#9017]
### Platforms

Windows

### Build

146

### Issue

Quickly picking them and dropped in the same position makes them unpowered (and sometimes shows it's being powered but is not working)

### Steps to reproduce

https://youtu.be/A8YhASamjKk

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Wantechfan** [comment]
I got this same issue back in V7.
