### ISSUE TITLE
can't see resources

### ISSUE THREAD

**Issue by PavelSkir** [Anuken/Mindustry#9020]
### Platforms

Windows

### Build

146

### Issue

I have a game for something does not see resources (lead and flint) for transfer. It started after the update. 

### Steps to reproduce

It started after the update. before that I did some digging in the game files but reinstalling the game didn't help.

### Mods used

I installed foo's client, but then I uninstalled it.

### Save file

[Min.zip](https://github.com/Anuken/Mindustry/files/12515234/Min.zip)
![2023-09-04](https://github.com/Anuken/Mindustry/assets/144047987/9377eed5-428f-4799-a3fa-a20bdff22fd3)
![2023-09-04 (2)](https://github.com/Anuken/Mindustry/assets/144047987/e63c1c1b-ecc4-48ca-98dc-32464792e309)
![2023-09-04 (1)](https://github.com/Anuken/Mindustry/assets/144047987/a31714a4-a073-4813-9c84-3561b9f7095d)

### (Crash) logs

![image](https://github.com/Anuken/Mindustry/assets/144047987/7c9cae03-5c32-4f6e-a62f-1868a5147e85)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/279ad0e7-7770-4646-8311-bb835edba177)

The sector doesn't have those resources.
