### ISSUE TITLE
Star does not render in a modded star system

### ISSUE THREAD

**Issue by Slotterleet** [Anuken/Mindustry#9021]
### Platforms

Windows

### Build

146

### Issue

This particular bug report is supposed to reference a pull request #8875. Not really sure if it's a bug in the PR or a mod is broken.
In this screenshot (with a modified menu UI, but in the planet dialog it's the exact same) the solar system is kinda working, except the star does not render. I have also made sure that a star was in fact initialized (i.e. not null). The console also shows that the `parent` value of the star is null, because I'm trying to make an actually brand-new solar system.
![20230904190857_1](https://github.com/Anuken/Mindustry/assets/62336673/63cb8239-e4cc-474e-bcbd-5261be6aca84)

### Steps to reproduce

I've made a star that references itself in the `solarSystem` field and a `null` parent, and two other planet instances with their `parent` values set to a star instance. The mod below has all of this.

### Mods used

[fictional-octo-system-desktop-v1.1-dev.zip](https://github.com/Anuken/Mindustry/files/12515811/fictional-octo-system-desktop-v1.1-dev.zip)
(This is a JAR file with a modified extension cuz github doesn't allow to attach JARs normally.)

### Save file

no

### (Crash) logs

no

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Modded solar systems aren't really tested or supported. I don't see a parent-less star in the fictional-octo-system repo source, so I  can't even verify if your code is correct. Either try to figure out what's going on by looking at PlanetRenderer.java yourself, or send me a minimal reproduction code sample with a star that renders correctly as a child, but not as a solar system center.

The PR linked shouldn't really change anything.

**Comment by Slotterleet** [comment]
Oh, right, sorry for not providing the proper source code. I've just pushed it in a new branch [right here](https://github.com/TeamOct/fictional-octo-system/blob/eb0cb473a100823d26636ac7f9c3533c54084fd4/core/src/fos/content/FOSPlanets.java#L31).

Speaking of a sample code for a planet working correctly as a child, here it is, in all its minimized glory:
```hjson
mesh: {
  type: SunMesh
  divisions: 3
  colors: [
    ffe06f
    ffe790
    ffedae
    fff8c8
    ffe53b
  ]
}
bloom: true
solarSystem: foo #whatever this star's file name is

#now, we just link this to the sun, give it a ridiculous orbit radius and pretend it's a new solar system.
parent: sun
orbitRadius: 12000
drawOrbit: false
```

**Comment by Anuken** [comment]
Works for me.

![image](https://github.com/Anuken/Mindustry/assets/10100000/4ccc45da-a58c-4d4d-83ce-7e5b2309f44e)

(I added JSON support for null parents.)

**Comment by Slotterleet** [comment]
...why did it start working for me today suddenly
did I forget to compile yesterday? :skull:
anyway, I guess the issue is resolved
![20230905175211_1](https://github.com/Anuken/Mindustry/assets/62336673/4978f3de-1608-4e04-9273-6146942f4ea2)
