### ISSUE TITLE
I did not do things in order

### ISSUE THREAD

**Issue by Karagron** [Anuken/Mindustry#9022]
### Platforms

Android

### Build

146

### Issue

While ı was playing on campaign planet Erekir level peaks 
I manage to destroy the enemy core before the enemy attack started now ı am stuck with 1 enemy core on the top left on my screen

### Steps to reproduce

I started building impact drills to mine some tungsten then i decided to build payload mass drivers to carry the tungsten to the core while doing that ı build ship fabricators and ship refabricators when ı build the  beam tower and then enemy attack timer come up ı attacked the enemy base with averts and destroyed the enemy core now ı am stuck with 1 enemy core on the top left of my screen

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Save file required.
