### ISSUE TITLE
Game crashes for no reason

### ISSUE THREAD

**Issue by nikito2223** [Anuken/Mindustry#9023]
### Platforms

Android

### Build

138

### Issue

After version 138, the game Nachila Fly out for no reason 

### Steps to reproduce

Updated the game

### Mods used

No

### Save file

[I] [GL] Version: GLES 3.2.0 / Imagination Technologies / PowerVR Rogue GE8100
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 27
[I] [RAM] Available: 128.0 MB
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
Success.
Fragment shader:
Success.
WARNING: 0:34: Calls to any function that may require a gradient calculation inside a conditional block may return undefined results
WARNING: 1 compilation warnings.

[W] Shader shaders/default.vert | shaders/fog.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/unitarmor.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/caustics.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/clouds.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
Success.
Fragment shader:
Success.

[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
Success.
Fragment shader:
Success.

[I] [Mindustry] Version: 146

### (Crash) logs

No

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> (Crash) logs
No

Crash reports require crash logs.

**Comment by JojoFR1** [comment]
"I have updated to the latest release"

You didn't.

**Comment by Anuken** [comment]
They have, actually; the log says they're on 146 despite them claiming it's 138.

**Comment by JojoFR1** [comment]
Oh I see, my bad

**Comment by nikito2223** [comment]
What is the name of the file
