### ISSUE TITLE
Unable to compare colors in mlog

### ISSUE THREAD

**Issue by SkyeTheFoxyFox** [Anuken/Mindustry#9024]
### Platforms

Linux

### Build

24379

### Issue

Trying to compare packed colors with op or jump doesn't work. 

### Steps to reproduce

put this code into a proc, and check the "vars" menu, they both return 1 despite %ff0000 not being the same as %000000
`op equal a %ff0000 %ff0000`
`op equal b %ff0000 %000000`

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You want to use exact equality checks for these. Colors are technically packed numbers, so you're comparing something like 0.00001 to 0.00002, which are "approximately" equal.
