### ISSUE TITLE
No auto save in campaign games

### ISSUE THREAD

**Issue by OvermindDL1** [Anuken/Mindustry#9025]
### Platforms

Linux

### Build

steam build 146

### Issue

Playing during campaign doesn't appear to make auto saves.  When the game was closed (system suspended due to an emergency that I had to get up to deal with, then ran out of power later) the 1.5 hours of work in the level vanished and there were no save files listed in the load menu.

Interestingly the research I unlocked during that level is still unlocked and the global resources are still consumed the launch.

A cursory search through prior issue titles shows nothing similar.

### Steps to reproduce

Play a campaign level for a few minutes on the current steam build (146), (quickest way to test) unplug computer, notice that the 60 second autosave (as listed in the game settings) is no where to be found and launching back to that level is a fresh new level.

### Mods used

None

### Save file

This is what is missing, there was no auto save file (not does there seem to be a way to make one even in the campaign, don't see a way to even manually save on occasion since the auto save doesn't seem to work without just outright quitting)

### (Crash) logs

No logs, the system was S3 suspended then lost power later.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There *is* autosave, and it works the same way as in normal games. Launching to any sector immediately creates a save, so even if the game died immediately afterwards, it would remain. Whatever happened to your computer corrupted it, *and* the backup.

> there were no save files listed in the load menu.

Campaign saves never show up in the load menu.

**Comment by OvermindDL1** [comment]
> Campaign saves never show up in the load menu.

If they don't show up in the load games then where do they show up at?  How many auto saves are kept at a time?

**Comment by OvermindDL1** [comment]
Also, it is extremely unlikely that corruption would have happened, the steam deck suspends correctly.

**Comment by Anuken** [comment]
> If they don't show up in the load games then where do they show up at? 

Play -> Campaign.

> How many auto saves are kept at a time?

One, they are not saved in a list.
