### ISSUE TITLE
Erekir: The onset impossible

### ISSUE THREAD

**Issue by alexkannes222** [Anuken/Mindustry#9026]
### Platforms

iOS

### Build

146

### Issue

On Erekir Sector The Onset i can‘t get past the point, where you destroy the enemy core, because it doesn‘t unlock the area where the core is after destroying the enemy units

### Steps to reproduce

Clicking Campaign, selecting Erekir, starting The Onset, playing normally until the point of destroying the units, destroying the units, task: Destroy the Enemy Core, area still fogged and core not destroyable

### Mods used

none

### Save file

[bugerekir.zip](https://github.com/Anuken/Mindustry/files/12522535/bugerekir.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by alexkannes222** [comment]
i figured out, that i need to get my units to this position, else it doesn‘t defog the area

**Comment by TimDu38** [comment]
> i figured out, that i need to get my units to this position, else it doesn‘t defog the area

🤦‍♂️

**Comment by alexkannes222** [comment]
I only question why i can’t defog the area with „my“ Ship (that one that i control)

**Comment by mahdoosh1** [comment]
Because your ship doesn't emmit light and for difficulty.
