### ISSUE TITLE
Pyratite ammo bug

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9032]
### Platforms

Windows

### Build

146

### Issue

Turrets with pyratite ammo ignoring damage mutli rule (0x)

### Steps to reproduce

Place any enemy turret with pyratite ammo with damage multi to 0 and watch it still kill you (damage is too high for it to be the cause of burning effect)

### Mods used

none

### Save file

[anukeBugReport.zip](https://github.com/Anuken/Mindustry/files/12548090/anukeBugReport.zip)
Event map so it looks weird xd just go to one of the circles with pyratite ammo

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Otamamori917** [comment]
I wouldn't call it a bug
The status effect deals the damage not the turret

**Comment by Anuken** [comment]
> (damage is too high for it to be the cause of burning effect)

![image](https://github.com/Anuken/Mindustry/assets/10100000/bfc5bb55-acb3-4631-8d1c-43bf39807326)

No, it's not. You've set the unit health multiplier ridiculously low, to the point where any damage kill units instantly.

**Comment by JasonP01** [comment]
I dont even have unitHealth multiplier in my map rules to set it anything besides 1x very strange , dont have unitHealth probably cause of mapping utilities/foos not sure which one
