### ISSUE TITLE
Невозможно пройти 125 сектор

### ISSUE THREAD

**Issue by Playfree1** [Anuken/Mindustry#9034]
### Platforms

Android

### Build

146

### Issue

125 сектор невозможен
![Screenshot_2023-09-08-22-41-55-507_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/137008415/2aed79ef-924d-4424-99ef-1352d2b50763)

### Steps to reproduce

Зайти в кампанию, дойти до 125 сектора

### Mods used

minZoom

### Save file

мой файл весит 140 мб не могу прекрепить сектор:125

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate, already reported.
