### ISSUE TITLE
Samsung A03 

### ISSUE THREAD

**Issue by ChavePhilips** [Anuken/Mindustry#9039]
### Platforms

Android

### Build

146

### Issue

The game will suddenly close itself, independent of the screen. In one of the times it closed a message from my cellphone indicated about a bug involving cash memory. The message only appeared once for now. You open the game, and after some time it closes the app (it appears to be the same amount of time or very similar at least).

### Steps to reproduce

I installed the game and opened it for the first time, once I started playing the tutorial in the newest planet, the game suddenly closed and some minor progress was lost (a few seconds to a minute of gameplay). It keeps happening every time I'm playing.

### Save file

Erekir - The Onset 
[mindustry_data.zip](https://github.com/Anuken/Mindustry/files/12566656/mindustry_data.zip)

### (Crash) logs

I can't upload the file the game provides (BIN)
![Screenshot_20230909_174621_Files](https://github.com/Anuken/Mindustry/assets/144558471/3ce7a504-6e75-49f8-9e2d-6fdf4d4e7b72)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash logs are required.
