### ISSUE TITLE
I can't join your discord! 

### ISSUE THREAD

**Issue by ILoveEmojicats** [Anuken/Mindustry#9041]
### Platforms

Android

### Build

146

### Issue

Just can't join 

### Steps to reproduce

As I tryed to join it said this invite link is invalid or has expired 

### Mods used

None

### Save file

None☠️

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Slotterleet** [comment]
discord.gg/mindustry

**Comment by ILoveEmojicats** [comment]
> https://discord.gg/mindustry

Won't work

**Comment by overdramaticpanromantic** [comment]
you're banned then

**Comment by ILoveEmojicats** [comment]
> you're banned then

Is expired send me new

**Comment by Slotterleet** [comment]
> > you're banned then
> 
> Is expired send me new

/mindustry is permanent :skull:

**Comment by ILoveEmojicats** [comment]
> > > you're banned then
> > 
> > 
> > Is expired send me new
> 
> /mindustry is permanent 💀

Pls

**Comment by ILoveEmojicats** [comment]
![images (3)](https://github.com/Anuken/Mindustry/assets/144035548/04630606-5549-44d9-b860-aed94f436ddb)
Pls
