### ISSUE TITLE
Wrong Translation

### ISSUE THREAD

**Issue by Mike20202** [Anuken/Mindustry#9042]
### Platforms

Windows

### Build

12101994

### Issue

Theres a Steam achievement with a tiny wrong german translation
![image](https://github.com/Anuken/Mindustry/assets/85358029/17733e22-6ea1-4eb4-81ee-554d776e3354)
the "der" should be "dem"

### Steps to reproduce

I saw a friend getting that achievement and saw it

### Mods used

none

### Save file

none

### (Crash) logs

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Incorrect translations aren't bugs and should be PRed, not reported here.
