### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by trankhangtop** [Anuken/Mindustry#9043]
### Platforms

Android

### Build

1

### Issue

When entering the game sometime I was spawned outside the map
![Screenshot_2023-09-10-14-15-08-877_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/144585250/0cc024ec-72da-4c85-97c4-c1c9e16e4e7b)

### Steps to reproduce

Enter to continue playing

### Mods used

Are not

### Save file

![Screenshot_2023-09-10-14-15-08-877_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/144585250/610a63cc-de7e-44f2-834b-b15c0d0b87a8)

### (Crash) logs

I only get errors, not crashes
![Screenshot_2023-09-10-14-15-08-877_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/144585250/2a6c1510-5e65-40f3-8dd4-bdd4eee51c35)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
No save attached.

Pan back to the center.
