### ISSUE TITLE
Bloom Doesn't Always Work

### ISSUE THREAD

**Issue by Darkness6030** [Anuken/Mindustry#9046]
### Platforms

Windows

### Build

v146

### Issue

Bloom doesn't work will all colors on some effects (dynamicSpikes, scatheExplosion, blockLight, etc.)

```Fx.lightBlock .at(Vars.player.x + 40, Vars.player.y, 1, Color.yellow)```
![image](https://github.com/Anuken/Mindustry/assets/79508138/5dcd3f79-9ace-4843-b2d7-d6971d586970)
 
```Fx.lightBlock .at(Vars.player.x + 40, Vars.player.y, 1, Color.red)```
![image](https://github.com/Anuken/Mindustry/assets/79508138/de09b985-d9c6-4d1d-9095-8401a31d2336)

### Steps to reproduce

Settings -> Graphics -> Bloom Intensity: 400%
Settings -> Graphics -> Bloom Blur: 16x

### Mods used

Tested without mods

### Save file

Doesn't matter, happens in any game on any server

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not supposed to. Red isn't bright enough.
