### ISSUE TITLE
Client side heat bug

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9047]
### Platforms

Windows

### Build

146

### Issue

When heat redirectors are placed in a loop and heat is fed into it, it infinitely scales (client side only on servers), but in campaing it is truly infinite

### Steps to reproduce

make a loop of heat redirectors, and place another heat redirector feeding into them (2x3 minimum is needed, cant feed heat into a heat redirector that changes the loop direction), watch it scale infinitely, on servers it scales but you can /sync to fix it

### Mods used

none

### Save file

not save specific

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
![Screenshot_20230911_060526_Mindustry](https://github.com/Anuken/Mindustry/assets/131086642/1c26b1f4-1910-49e3-ad58-730b2a6d1b66)

Screenshot from android (happens on windows to i just dont want to open it to get a ss) ss from server, i dont feel like trying to enables cheats in campaign

**Comment by SITUVNgcd** [comment]
I found this long time ago, but fogot it.

**Comment by Anuken** [comment]
Save files are required.

**Comment by JasonP01** [comment]
? it worked all server maps we had

**Comment by JasonP01** [comment]
also like how tf is a save file required when its a client side bug, and when stated you /sync it fixes itself
