### ISSUE TITLE
TECNO SPARK 10C

### ISSUE THREAD

**Issue by DanilExE2003** [Anuken/Mindustry#9048]
### Platforms

Android

### Build

146

### Issue

Произошло ошибка в браузере модификации, 
Пытаюсь зайти и он мне выдает ошибку

### Steps to reproduce

https://github.com/Anuken/Mindustry/assets/144655607/d5ab76f8-3789-4959-8569-ff5b50dffe3c

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/12572821/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Your network/device is blocking Github.
