### ISSUE TITLE
I Can't download mods

### ISSUE THREAD

**Issue by Haramot** [Anuken/Mindustry#9050]
### Platforms

Android

### Build

146

### Issue

After downloading many mods, the game jut shows a pop up when downloading another one instead of downloading it. It shows "An error has ocurred-Connection error: Forbidden.

### Steps to reproduce

Download as many mods as you can, +50, then it probably will happen.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You're probably being ratelimited by the API, try again later. If it still doesn't work, your network is blocking something.
