### ISSUE TITLE
Unit control not correct with @latum and @renale

### ISSUE THREAD

**Issue by Rafaal1104** [Anuken/Mindustry#9053]
### Platforms

Mac

### Build

146

### Issue

I wrote ai for this units and found this problem (latum and renale)

### Steps to reproduce

wrote processor with @latum control. latum and renale does not turn to move coordinates, they just go ahead

### Mods used

more then 25mb but it utilites mods (and foos client)

### Save file

[saves.zip](https://github.com/Anuken/Mindustry/files/12589537/saves.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I will not debug logic issues unless you specifically point out a flaw in an instruction. Most issues with logic are user error.

**Comment by camelStyleUser** [comment]
also i can move renales with logic on 146 vanilla linux mindustry

**Comment by camelStyleUser** [comment]
also latums can be moved

**Comment by overdramaticpanromantic** [comment]
Renale and Latum are fucked up in general. They don't even work right anymore - it's just old content that hasn't been removed yet. (They wriggle _way_ too fast now, and also don't properly turn each segment.)

**Comment by Mythril382** [comment]
> Renale and Latum are fucked up in general. They don't even work right anymore - it's just old content that hasn't been removed yet. (They wriggle _way_ too fast now, and also don't properly turn each segment.)

They wriggle fast? I thought they wriggled pretty slowly.

**Comment by Rafaal1104** [comment]
> I will not debug logic issues unless you specifically point out a flaw in an instruction. Most issues with logic are user error.

Just try to write code in proc, move x y. They don't turn, just go ahead

**Comment by camelStyleUser** [comment]
> > I will not debug logic issues unless you specifically point out a flaw in an instruction. Most issues with logic are user error.
> 
> Just try to write code in proc, move x y. They don't turn, just go ahead

and how is this a problem anyway?
