### ISSUE TITLE
Mindustry (Stuck In the cloud)

### ISSUE THREAD

**Issue by BugendaiSan** [Anuken/Mindustry#9054]
### Platforms

Android

### Build

146

### Issue

It's been a day since I have played this game and I accidentally went deep into the cloud in the campaign mode. Now I am stuck no Matter how many times drag to the direction I came from I am not able to escape this cloud.

![Screenshot_2023-09-14-08-36-09-276_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/144976258/59533b3c-af39-4abc-9af2-21fcbf8b898a)

### Steps to reproduce

This happened when I went into the cloud. I suggest the dev to make a self destruct button or something for to fix this.

### Save file

This happened in Erekir in Aegis.

[Mindustry Bug.zip](https://github.com/Anuken/Mindustry/files/12603368/Mindustry.Bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I don't really see a bug here. There is a respawn button, it just doesn't affect the camera.

If you want an indicator of which direction you need to pan back to, enable the minimap in the settings.

**Comment by BugendaiSan** [comment]
> I don't really see a bug here. There is a respawn button, it just doesn't affect the camera.
> 
> If you want an indicator of which direction you need to pan back to, enable the minimap in the settings.

Where is the minimap? I can't find it.

**Comment by BugendaiSan** [comment]
> I don't really see a bug here. There is a respawn button, it just doesn't affect the camera.
> 
> If you want an indicator of which direction you need to pan back to, enable the minimap in the settings.

**Comment by BugendaiSan** [comment]
Oh the minimap was in the graphics settings.
