### ISSUE TITLE
Sublimate consumes ammo without shooting

### ISSUE THREAD

**Issue by hosve** [Anuken/Mindustry#9055]
### Platforms

Windows

### Build

146

### Issue

Get a Sublimate to low or no ammo
Supply it less than 10 ammo per second while it tries to shoot
It consumes all ammo without shooting

https://github.com/Anuken/Mindustry/assets/39941745/71a6e534-4aba-455c-a71b-5a2426c6fffd

Happens on my android as well

### Steps to reproduce

Get a Sublimate to low or no ammo
Supply it less than 10 ammo per second while it tries to shoot

### Save file

[happens everywhere.zip](https://github.com/Anuken/Mindustry/files/12611846/happens.everywhere.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Jeamorg** [comment]
I also encountered this bug today, which caused the map of Crossroads to fail after playing for half an hour.
