### ISSUE TITLE
mod browsing and github search feature not working

### ISSUE THREAD

**Issue by Babib3l3l** [Anuken/Mindustry#9056]
### Platforms

Linux

### Build

Release build 146

### Issue

the Mod Browser and Import from github features do not work, bot dispalying "an Error occured : the trustanchors parameters must be non empty" 
![image](https://github.com/Anuken/Mindustry/assets/145063624/21a2ec75-cfa4-4889-8bfb-c6d88961e705)
here are the crash logs
![Screenshot from 2023-09-14 21-52-59](https://github.com/Anuken/Mindustry/assets/145063624/eb835778-ce55-479b-98b6-5833c1f899e1)
![Screenshot from 2023-09-14 21-53-07](https://github.com/Anuken/Mindustry/assets/145063624/1b8507fd-86c8-49fb-83c6-bd6dd5224bdf)
![Screenshot from 2023-09-14 21-53-11](https://github.com/Anuken/Mindustry/assets/145063624/931413bf-0287-4386-a98b-a41068c7964d)

### Steps to reproduce

i have no idea, i guess you have to play on linux and have your "trustanchors non empty"

### Mods used

no mods are used

### Save file

[game data.zip](https://github.com/Anuken/Mindustry/files/12612857/game.data.zip)

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue on Linux.

**Comment by Sectonidse** [comment]
I have the same issue on Ubuntu 24.04
Tried `update-ca-certificates -f`
