### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by MuhammadDwiKrisbiantoro** [Anuken/Mindustry#9057]
### Platforms

Android

### Build

Build release 146

### Issue

I found an issue with the audio in the mindustry game. Like music, sfx, and ambient cannot be played / do not display audio output at all in settings that have been set to 100% everything.

### Steps to reproduce

Since I installed the application from the apps store (play store) 

### Mods used

I don't use mods at all because this happens after being installed from the apps store (play store) 

### (Crash) logs

last log:
[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 530
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 26
[I] [RAM] Available: 192.0 MB
[I] [Mindustry] Version: 146
[I] Total time to load: 19128ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 58 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JojoFR1** [comment]
I had a bug like that too only happening with Bluetooth headphones (don't know for wired) when closing and quickly reopening the game

**Comment by JojoFR1** [comment]
Was able to reproduce it multiple times after a few attempts by quit and really quickly reopening the game

But it doesn't happen when I record for some reason
