### ISSUE TITLE
Latum need in mindustry for creating maps with beta content

### ISSUE THREAD

**Issue by Rafaal1104** [Anuken/Mindustry#9060]
### Platforms

Android

### Build

146

### Issue

Anuken, pls bring the latum and renale back to life, they cant be spawned by world processors on the vanilla version and will not spawn on the server. This is a very big problem for XCore

### Steps to reproduce

i create map with world proc which spawn latum at x y, result is null. it cant spawn @latum
code:
spawn @latum @thisx @thisy 90 @crux result
ITS NOT WORK

### Mods used

null (vanilla vers)

### Save file

[saves 2.zip](https://github.com/Anuken/Mindustry/files/12622428/saves.2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Rafaal1104** [comment]
i can send u this map
<img width="162" alt="image" src="https://github.com/Anuken/Mindustry/assets/104323078/6bf41243-7fc0-4330-bd1c-c5d0e0219b83">
<img width="1347" alt="image" src="https://github.com/Anuken/Mindustry/assets/104323078/2b551cb5-6b10-464e-8c56-154766ed94cd">
ai latum and spawn by world proc:
getblock building Build 91 100
setprop @nitrogen Build 999
fetch core Core @sharded 0 @reinforced-surge-wall
fetch build Launch @sharded 0 @launch-pad
jump 6 strictEqual Launch null
jump 28 always Launch null
sensor res Core @copper
op add res res -350
jump 10 greaterThan res 0
setprop @copper Core 0
setprop @copper Core res
sensor res Core @lead
op add res res -200
jump 15 greaterThan res 0
setprop @lead Core 0
setprop @lead Core res
sensor res Core @titanium
op add res res -150
jump 20 greaterThan res 0
setprop @titanium Core 0
setprop @titanium Core res
sensor res Core @silicon
op add res res -140
jump 25 greaterThan res 0
setprop @silicon Core 0
setprop @silicon Core res
wait 10
setblock block @launch-pad x y @sharded 0
fetch build Object @sharded 0 @reinforced-surge-wall
jump 50 strictEqual Object null
sensor x Object @x
sensor y Object @y
setblock block @air x y @derelict 0
setblock floor @metal-floor-2 x y @derelict 0
op add x x 1
setblock floor @metal-floor-2 x y @derelict 0
op add y y -1
setblock floor @metal-floor-2 x y @derelict 0
op add x x -1
setblock floor @metal-floor-2 x y @derelict 0
op add x x -1
setblock floor @metal-floor-2 x y @derelict 0
op add y y 1
setblock floor @metal-floor-2 x y @derelict 0
op add y y 1
setblock floor @metal-floor-2 x y @derelict 0
op add x x 1
setblock floor @metal-floor-2 x y @derelict 0
op add x x 1
setblock floor @metal-floor-2 x y @derelict 0
end

**Comment by Rafaal1104** [comment]
more then u could trade some items in @launch-pad
<img width="267" alt="image" src="https://github.com/Anuken/Mindustry/assets/104323078/8cf4e263-d7f8-4876-bc8d-995fe02fdb10">

**Comment by Rafaal1104** [comment]
Latum dont attack blocks on @metal-floor-2, they attack some blocks on other floor
Its like a skyblock

**Comment by Anuken** [comment]
There is no bug here. Those units are unreleased content. Don't use them.

**Comment by Rafaal1104** [comment]
> There is no bug here. Those units are unreleased content. Don't use them.

Anuken, I am very sad that there are no such types of units(

**Comment by camelStyleUser** [comment]
> > There is no bug here. Those units are unreleased content. Don't use them.
> 
> Anuken, I am very sad that there are no such types of units(

also last i checked you could make them payload of a payload unit and payload drop them

**Comment by JasonP01** [comment]
Latum and renanle were removed from the game its not possible to spawn them anymore

**Comment by camelStyleUser** [comment]
> Latum and renanle were removed from the game its not possible to spawn them anymore

whats the commit hash of removal(there is no commit that removed latum and renale)

**Comment by camelStyleUser** [comment]
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/UnitTypes.java#L93
