### ISSUE TITLE
Objectives on map do not persist between play sessions

### ISSUE THREAD

**Issue by TheGamer1002** [Anuken/Mindustry#9061]
### Platforms

Mac

### Build

146

### Issue

On The Onset map, players have to complete certain objectives, some of which are necessary to progress in the game.
![Screenshot 2023-09-15 at 2 35 59 PM](https://github.com/Anuken/Mindustry/assets/48131223/4d079540-bf6c-4f96-8fc6-fe904685ea20)

### Steps to reproduce

1. On a new save file, open the starting map on Erekir.
2. Observe the hovering text on the map detailing what to do.
3. Save and quit.
4. Re-open that map.
5. Observe the lack of that text, which is necessary for progression.

### Mods used

None

### Save file

[stuff 2.zip](https://github.com/Anuken/Mindustry/files/12622867/stuff.2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue. While the objectives in your save are indeed empty, repeating your steps does not yield results - the objectives persist. Either your data was corrupted, or you were loading objectives from a very old version of the game/save.
