### ISSUE TITLE
Impact 0078 bug

### ISSUE THREAD

**Issue by FumpFur** [Anuken/Mindustry#9066]
### Platforms

Android

### Build

V7, official,146

### Issue

3 enemy spawn tiles suddenly appeared in the middle of the map Impact0078, it was the third time 0078 was under attack

### Steps to reproduce

i was just afk in Ruinous Shores, then when i returned and got back to impact, i suddenly found that it was under attack for the 3rd time (swcond attack after capture) and it had gained 3 extra enemy spawns, and yes, they do function

### Mods used

Scheme Size
SiriusSchem v7
S.Q.A Schemic
Time Control (disabled)

### Save file

[Bugged0078.zip](https://github.com/Anuken/Mindustry/files/12645313/Bugged0078.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is only possible if an enemy core or spawn was placed and destroyed on the map (with a mod?).

**Comment by Anuken** [comment]
Delete the save and backup file for it (sector-serpulo-227.msav)
