### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by Domaman202** [Anuken/Mindustry#9075]
### Platforms

Linux

### Build

146

### Issue

Crash on use 1 block from mode.

### Steps to reproduce

1. Place "Pressure Boilder"
3. Catch crash

### Save file

https://www.dropbox.com/scl/fi/19utb2maqqrqfb19olqvf/save.zip?rlkey=quns8z08qzyxzhxoa5mxhkum4&dl=0

### (Crash) logs

[last_log.txt](https://github.com/Anuken/Mindustry/files/12667232/last_log.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
You use a ton of mods. "Pressure Boidler" isn't an official content.

**Comment by Anuken** [comment]
Mod issue.
