### ISSUE TITLE
Bug on serpulo with waves

### ISSUE THREAD

**Issue by DALLORDCR** [Anuken/Mindustry#9076]
### Platforms

Android

### Build

146

### Issue

*прикрепил бы видео но гитхаб не дает
На секторе ядерный производительный комплекс при повторном нападении врагов когда враги сравнятся то моментально умирают

### Steps to reproduce

Враги при спане на точке нападения сравнятся и моментально умирают

### Mods used

Time control

### Save file

[баг.zip](https://github.com/Anuken/Mindustry/files/12672121/default.zip)

### (Crash) logs

Не получается(

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by DALLORDCR** [comment]
Не получалось прикрепить отчёт об ошибке

**Comment by Anuken** [comment]
Mod bug. You have three mods installed, disabling them fixes the issue.
