### ISSUE TITLE
MacOS Steam Version

### ISSUE THREAD

**Issue by MrNossiom** [Anuken/Mindustry#908]
**Platform**: *Macintosh*

**Build**: *98.1*

**Issue**: *Steam Cloud doesn't work on MacOS.* When Steam Cloud is enabled on Mac for Mindustry, the files aren't saved. I try on a Windows computer and it works. It will be good to fix it for the mac players.

**Idea**: I think that the files are not correctly parametred for mac systems.

**Message**: Hello Anuke, I just want it to say that the "Steam Cloud" doesn't work on Macintosh.
It is enabled but the files aren't saved correctly.
I try on a Windows computer and it works.
I think you didn't parametred correctly the files on mac Steam Cloud.
It will be good to fix it for the players who are on mac.

***Thanks***
***Mr_Nossiom (#4596)***

**Comment by Anuken** [comment]
I am aware, and this has already been fixed. Stop spamming this everywhere.
