### ISSUE TITLE
Immortal unit

### ISSUE THREAD

**Issue by Hdbdiegc7whd** [Anuken/Mindustry#9083]
### Platforms

Android

### Build

Latest version 

### Issue

Suddenly the unit stopped listening to the command, and then at 0 HP he became immortal, but he could continue to fly 

### Steps to reproduce

I don't know 

### Mods used

No mods used 

### (Crash) logs

No

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Hdbdiegc7whd** [comment]
I took a video, but I don't know how to send it

**Comment by Mythril382** [comment]
![Screenshot_2023-09-22-22-29-03-86](https://github.com/Anuken/Mindustry/assets/77225817/0b76adce-5b1a-4f59-9baf-4c22fc3856cc)

**Comment by Mythril382** [comment]
You should edit the main message, add a save file.

**Comment by Hdbdiegc7whd** [comment]
![Screenshot_2023-09-22-20-35-33-979_com miui gallery](https://github.com/Anuken/Mindustry/assets/145782637/1b15690c-7c2b-4517-bed1-ca64c31aef0e)

**Comment by Hdbdiegc7whd** [comment]
The video is not sending...

**Comment by Mythril382** [comment]
> ![Screenshot_2023-09-22-20-35-33-979_com miui gallery](https://user-images.githubusercontent.com/145782637/269970087-1b15690c-7c2b-4517-bed1-ca64c31aef0e.jpg)

Please send save file.

**Comment by Hdbdiegc7whd** [comment]
Save file is notsending -_-

**Comment by Anuken** [comment]
"Latest" is not a version. Save files mandatory.
