### ISSUE TITLE
Hi Anuke! I have a request, could you add the categories power to give out objects or liquids in the creation of modifications? I think this would be a great solution to expand the possibilities of co-modding. Thank.

### ISSUE THREAD

**Issue by SuperDimoxa** [Anuken/Mindustry#909]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by SuperDimoxa** [comment]
Hi Anuke! I have a request, could you add the categories power to give out objects or liquids in the creation of modifications? I think this would be a great solution to expand the possibilities of co-modding. Thank.

**Comment by Anuken** [comment]
Feature requests should go in the appropriate issue.

**Comment by SuperDimoxa** [comment]
ok, next time I will send there. Did you accept my request?


вс, 27 окт. 2019 г., 22:24 Anuken <notifications@github.com>:
