### ISSUE TITLE
Cultivator Efficiency Bug

### ISSUE THREAD

**Issue by Kenny-Ofc** [Anuken/Mindustry#9098]
### Platforms

Windows

### Build

Release Build 146

### Issue

I'm Trying to add more Oil Production into Plastanium Compressor, then i'd make Three Cultivator to handle one Spore Press. But after i reliaze, The Cultivator Efficiency Number indicator became High, for example 180 Efficiency into 279 Efficiency.
i was on sector 221 Serpulo.
![Cultivator on 180 Efficiency](https://github.com/Anuken/Mindustry/assets/146146416/920bb5aa-dcb7-48a2-976e-a83041c422d2)
![Cultivator on 180 become 279 Efficiency](https://github.com/Anuken/Mindustry/assets/146146416/b43fadec-d7ac-40e5-87e0-26a59599cd09)

### Steps to reproduce

Try making Oil Production. Build Cultivator on Spore field, supply water, then feed Spore Press with Spore Pod.

### Mods used

No Mods

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BlueWolf3682** [comment]
Not a bug. You are in a spore storm.
