### ISSUE TITLE
Random client crashes on server on beta 1.19b

### ISSUE THREAD

**Issue by Chenjox** [Anuken/Mindustry#91]
Simply playing a party with a few and BOOM client crashes.

ArrayIndexOutOfBounds: 16
io.anuke.mindustry.world.blocks.types.distribution.Junction$Buffer.add(Junction.java:94)
io.anuke.mindustry.world.blocks.types.distribution.Junction.handleItem(Junction.java:31)
io.anuke.mindustry.core.NetClient.lambda$new$17(NetClient.java:276)
io.anuke.mindustry.net.Net.handleClientReceived(Net.java:192)
io.anuke.kryonet.KryoClient$2.lambda$received$2(KryoClient.java:79)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:153)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:27)

this is the full crash report.

I hope i can help

**Comment by Anuken** [comment]
Fixed as of latest commit.
