### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by jakiki6** [Anuken/Mindustry#910]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *latest*

**Issue**: *The german translation of "Slag" isn't "Asche". It's "Schlacke". "Asche" is something like ash.*

**Steps to reproduce**: *Set your language to german*

**Comment by Anuken** [comment]
For translation errors, submit a PR instead of making an issue. I am not in charge of specific translations.
