### ISSUE TITLE
Mindustry on arm64 machines

### ISSUE THREAD

**Issue by schooldanlp6** [Anuken/Mindustry#9101]
### Platforms

Linux

### Build

146

### Issue

Assuming you have a linux arm64 (idk if this accounts for 32 as well) machine you wont be able to run the game

### Steps to reproduce

Any  arm64 linux machine eg a switch. 
Java 8 and 11 and 16
Try to run it it will crash 

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Mindustry does not support ARM.

> I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you haven't. There are multiple issues with the same response.
