### ISSUE TITLE
Int values incorrectly adding via operation in logic

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9109]
### Platforms

Windows

### Build

146

### Issue

When adding numbers via operations together it adds extra numbers that are not specified to add (var + 0.1 | outputs 1.1 back to var ;  second time var + 0.1 | outputs 1.2000000000002) (var is being read via a cell, var as well is being set in the cell every time it changes)

Another issue is 1 click is being counted twice sometimes, not very reliable so i cant report that 

### Steps to reproduce

I dont feel like explaining your own logic system to you, so just use the map provided (ive tested it multiple times and its been consistent for me), instructions by core

Just click the dark panels (there is a cooldown due to toast/notify stopping the proc)

### Mods used

none

### Save file

[TiDbugReport.zip](https://github.com/Anuken/Mindustry/files/12755259/TiDbugReport.zip)

### (Crash) logs

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
For comments, ik flooring is a solution to this issue but it shouldn't be the solution, this shouldn't happen in the first place

**Comment by SkyeTheFoxyFox** [comment]
0.1 isn't an int, you're gonna find floating point imprecision, anuke has no real control over that

**Comment by Anuken** [comment]
That is simply how [floating point numbers work](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate) in programming languages.

**Comment by JasonP01** [comment]
annoying, it shouldnt add extra decimals anyway

**Comment by Anuken** [comment]
welcome to programming anything with floating point numbers
