### ISSUE TITLE
Maps don't seem to render correctly on a laptop with Intel Graphics Card.

### ISSUE THREAD

**Issue by CarlJimenez** [Anuken/Mindustry#911]
**Platform**: Windows

**Build**: Release Build 96

**Issue**: I was away at my home and tried to install Mindustry on my relative's old laptop. I thought it only happens on the Ground Zero map but I still continue to play with the broken map and unlocked the two next maps but still got the same broken maps. Some parts of the map are black specifically the ground and walls but some structures render correctly like abandoned drills and conveyors. The laptop I played had a "HSD101PFW4B on PHDGD Newton for Intel Graphics Media Accelerator 3600 Series" graphics card (based on Speccy). Here are some of the map screenshots I took.

![screenshot-1572180286504](https://user-images.githubusercontent.com/22052428/67634759-f2c4b180-f8fa-11e9-9bcc-ab73845fb287.png)
![screenshot-1572180311649](https://user-images.githubusercontent.com/22052428/67634762-f5270b80-f8fa-11e9-8f85-b34908d76a79.png)
![screenshot-1572180333392](https://user-images.githubusercontent.com/22052428/67634764-f7896580-f8fa-11e9-9bde-bdf7c895aee9.png)

**Steps to reproduce**: I've only tried the campaign maps.

**Comment by Anuken** [comment]
This isn't related to low VRAM, as I've tried running it on VMs with the worst graphics setup possible (32MB) and the maps render fine. It's intel-specific, and I don't have any Intel graphics devices to test it on. Unless someone else comes around with a magical solution, I'm never going to fix this. My advice is to get a better computer.

**Comment by CarlJimenez** [comment]
Oh, well I guess I have to wait until I get home until I can play again. Thanks for the quick reply.
