### ISSUE TITLE
Android TV Buttons don't working.

### ISSUE THREAD

**Issue by Junai22** [Anuken/Mindustry#9128]
### Platforms

Android

### Build

Release Build 146, Itch.io Android.

### Issue

When playing Mindustry through an Android TV, the game runs perfectly and loads perfectly but the buttons do not react in any way.

### Steps to reproduce

Just download and open the game from an Android TV.

### Mods used

null.

### (Crash) logs

I cannot send a crash log if I cannot touch any button in the game.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Mindustry doesn't support Android TV. I don't even know what that is or what "buttons" you are referring to.
