### ISSUE TITLE
Editor: Mirror does mirror blocks

### ISSUE THREAD

**Issue by Odepax** [Anuken/Mindustry#9131]
### Platforms

Windows

### Build

146

### Issue

The Mirror generator mirrors terrain tiles, but not blocks. Similar to #6288, which was related to cliffs, but I'd argue that block mirroring is simpler to implement (no lighting to care for), and more useful (e.g. PvP maps featuring anti-rush).

### Steps to reproduce

1. Create a new map in the editor;
2. Paint a few terrain tiles (e.g. grass or ores);
3. Paint a few blocks (e.g. turrets or crafters);
4. Add a Mirror generator;

Expected: terrain tiles and blocks are mirrored.

Actual: terrain tiles are mirrored, but not blocks.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Intentional. Filters aren't supposed to affect synthetic blocks.
