### ISSUE TITLE
very quickly Clicking the show all servers button results in a crash

### ISSUE THREAD

**Issue by Comodo17** [Anuken/Mindustry#9139]
### Platforms

iOS

### Build

v146

### Issue

Very rapidly clicking the show all servers button crashes the game, causing it to exit

### Steps to reproduce

Go to join game, click the show all servers button very quickly (about 2-5 times a second)
![IMG_0209](https://github.com/Anuken/Mindustry/assets/106919547/0feb4240-dc9a-4828-8551-99e792af78a6)

### Mods used

None

### (Crash) logs

[logs.txt](https://github.com/Anuken/Mindustry/files/12822355/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue; crash log doesn't contain any relevant information.
