### ISSUE TITLE
Save scheme

### ISSUE THREAD

**Issue by Arial1102** [Anuken/Mindustry#9146]
### Platforms

Windows

### Build

All

### Issue

Can not save scheme when set an special keybind

### Steps to reproduce

Set keybind as this:
Select/Shoot : M2
Deslect : M1
Break block : M1
And try save a scheme with that.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Yes, your deselect key is the same as the key to press buttons. Don't do that.
