### ISSUE TITLE
Shockwave Tower and Regen Projector doesn't Configure Correctly at Southern Enemy Base. Erekir Sector Origin.

### ISSUE THREAD

**Issue by Kenny-Ofc** [Anuken/Mindustry#9148]
### Platforms

Windows

### Build

Release Build 146

### Issue

![Shockwave Tower and Regen Projector doesn't Configure Correctly](https://github.com/Anuken/Mindustry/assets/146146416/69f0ec93-2de7-46e7-9647-e0e49d96a6f8)

Somehow when i uncover The Southern Enemy Base, I was realizing that regen projector and shockwave tower not supplying with Hydrogen and Cyanogen. also the ducts seems there isn't Phase Fabric goin through. 

### Steps to reproduce

Try Replay Sector Origin on Erekir if u want to see this, just uncover the Southern Enemy Base, where Tier 5 Tank is produce

### Mods used

Time Control Author:sk7725

### Save file

[here.zip](https://github.com/Anuken/Mindustry/files/12842770/here.zip)
in case anuke need it

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by KhaledHawwas** [comment]
they are not connected in the right way

**Comment by Kenny-Ofc** [comment]
actually, there are too many infrastructure that are not connected in the right way,, The Bore, Turret, another Building that doesn't get function. hopefully it gets fixed.
