### ISSUE TITLE
Can't launch to Ravine

### ISSUE THREAD

**Issue by Entreaver** [Anuken/Mindustry#9150]
### Platforms

Android

### Build

146

### Issue

I cannot launch to Ravine in planet Erekir because my launch point is in Lake and you need tungsten in order to launch to Ravine, which Lake doesn't have. I cannot progress the campaign of Erekir due to it, pls fix this , because i dont want to restart my first time playing the Erekir campaign.

### Steps to reproduce

I CONQUERED LAKE FIRST BEFORE RAVINE 

### Mods used

N/A

### Save file

[Mindustry.zip](https://github.com/Anuken/Mindustry/files/12855858/Mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
- this "issue" was reported before
- literally switch to any sector with tungsten before launching, you dont need to launch from lake
