### ISSUE TITLE
Unit depositing breaks progression in Ravine

### ISSUE THREAD

**Issue by endcr** [Anuken/Mindustry#9152]
### Platforms

Android

### Build

146

### Issue

By using the core unit repeatedly to move tungsten into the core, the objective board does not update, and allows the player to build up units way ahead of time, and more importantly, evade enemy unit production. I tried to search for this specific issue and came up with this guy's [youtube video](https://youtu.be/BeXVO6Sufs4?t=1105) that demonstrates how this can be, he does automate the tungsten eventually (and completes the objective), but stills proves my point nonetheless. The save I provided is just my single player world in ravine, with over 50 tungsten in the core, without triggering any objectives.

### Steps to reproduce

Go to Ravine, place a drill on tungsten, water it, power it. Take the items in your core unit, and deposit it into your core, and see that the objective to move 50 tungsten does not update.

### Mods used

none

### Save file

[latest.zip](https://www.mediafire.com/file/736m8t7myuilqh7/latest.zip/file)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
Ha! I did this (trick) before.

**Comment by mahdiyadiilavi1** [comment]
This issue refers to [this line](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/game/MapObjectives.java#353)
