### ISSUE TITLE
#9070 is still in effect

### ISSUE THREAD

**Issue by Unexian** [Anuken/Mindustry#9153]
### Platforms

Android

### Build

146

### Issue

When I unfocus Ministry, say to check my WiFi connection, enter some text, or even leave the map editor, the game stops registering my inputs.

### Steps to reproduce

See above or video in first comment

### Mods used

None

### Save file

It crashed on the join server screen, I'm pretty sure it happens everywhere

### (Crash) logs

I was told there was no relevant crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Unexian** [comment]
Here is the video: [https://drive.google.com/file/d/1tCnLeFBoLnT8s_TBU_2fDJ1KEmOi3eK5/view?usp=drivesdk](https://drive.google.com/file/d/1tCnLeFBoLnT8s_TBU_2fDJ1KEmOi3eK5/view?usp=drivesdk)

**Comment by Unexian** [comment]
Also here's a hyperlink to #9070

**Comment by JojoFR1** [comment]
If you crashed give the log.

Anuke told you there was no relevant crash in the **previous** log

**Comment by Unexian** [comment]
[crash2.log](https://github.com/Anuken/Mindustry/files/12866853/crash2.log)
Took a bit of forcing to get the crash again, but here is my current logs.

**Comment by Unexian** [comment]
After looking at the file, I can safely say that mindustry does not think that this is a crash, probably because the app doesn't close automatically

**Comment by Anuken** [comment]
Just like last time, there is no crash in that log, and I cannot reproduce the issue.
