### ISSUE TITLE
Mobile cannot get message from MessageBlock while configurating (BE)

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry#9156]
### Platforms

Android

### Build

BE 24480

### Issue

Mobile cannot get message from MessageBlock while configurating. It should shows the message in MessageBlock
![image](https://github.com/Anuken/Mindustry/assets/55009845/f7736c3b-be8a-45dd-ae53-42edaaad9eb9)

### Steps to reproduce

As video indicated.
Input some text in messageblock, save.
Click it again, TextInput doesnt show message typed before.

https://github.com/Anuken/Mindustry/assets/55009845/a74c223f-cc53-4dba-949a-c012b6c20e48

### Mods used

None

### Save file

easy to reproduce

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
It *does* save; the message just doesn't display because you are in build mode.

**Comment by Jackson11500** [comment]
> It _does_ save; the message just doesn't display because you are in build mode.

you may misunderstood. Loot at 0:07, the messageblock **has some message in it**, but while you config it, **it should show the messge, but in fact it shows nothing in textfield**. Which means that while mobile players are making maps, they cannot edit exists messageblock because when you open it, it shows nothing. 

For the PC version, while you open messageblock with message in it, it would show the message in textfield, compared to nothing for mobile player
