### ISSUE TITLE
Transferring save data

### ISSUE THREAD

**Issue by Greendragon00** [Anuken/Mindustry#9159]
### Platforms

Android

### Build

Release build 146

### Issue

When exporting save data, the zip file exported is 0kb. This is still the case when transferred between phones, meaning that you cannot transfer save data. 

### Steps to reproduce

Attempt to export save data, it will most likely come out as 0kb, if not I have no idea. 

### Mods used

Build Core Units
https://github.com/992040/mindustry_build_core_units

### Save file

Unable to attach due to nature of bug/problem

### (Crash) logs

I couldn't attach the crash log. However it did download as data not 0kb.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue.
