### ISSUE TITLE
Logic display draw limit

### ISSUE THREAD

**Issue by TopCatTC** [Anuken/Mindustry#9162]
### Platforms

Windows

### Build

146

### Issue

Logic display seems to have a draw cap, I'm making unit logic and the display will not draw all units consistently, leaving many units out, some disappearing and reappearing on the display (No change in number of units on map)

### Steps to reproduce

Go on any map above around 150 unit cap, fill up the unit cap, draw all units on a display as points relative to where they are on the map, and just watch the display.

### Save file

[Save.zip](https://github.com/Anuken/Mindustry/files/12890901/Save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SkyeTheFoxyFox** [comment]
This isn't a bug

**Comment by TopCatTC** [comment]
If its intentional then I suggest increasing the limit to around 400 or something to draw say the vertices of a shape without connecting the points

**Comment by camelStyleUser** [comment]
it **is** intentional and known internally

**Comment by camelStyleUser** [comment]
why would anuke define it in LExecutor.java if it wasnt intentional
