### ISSUE TITLE
Mono rts AI broken

### ISSUE THREAD

**Issue by AFARIUS** [Anuken/Mindustry#9163]
### Platforms

Android

### Build

146

### Issue

While playing in campaigns and on user servers, many players encounter the problem of mono rts AI failure. I uploaded a video of my friend to disk clearly demonstrating this. In the world we played in, there are no processors or plugins that control Mono.
Link:
https://drive.google.com/file/d/1fhikiR2HpwDbGd5aF_a8L_9FaLO3OWGb/view?usp=drivesdk

### Steps to reproduce

Just played and spawned a lot of mono

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by AFARIUS** [comment]
P.P.S: in the world where we played, there is a world processor that imposes negative effects on almost all units. This is a feature of this world.

**Comment by camelStyleUser** [comment]
intentional
![image](https://github.com/Anuken/Mindustry/assets/124447863/be9a37b9-2009-4481-aac4-eed5242fd07a)

**Comment by Anuken** [comment]
> mono rts AI failure

Mono as a unit has nothing to do with RTS AI. They cannot be controlled. I don't understand what you are reporting as a "failure".

> Save file

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.
