### ISSUE TITLE
Computer and fone 

### ISSUE THREAD

**Issue by Kostr8** [Anuken/Mindustry#9164]
### Platforms

Android

### Build

Build 146 and ather with world processors

### Issue

I tried to write doom , end i think i m close to do it, but processors dont work how u wont

They slower skip comands and dont draw at screen at all
It is not drow limit, it can't drow 2 lines or rects

### Steps to reproduce

hrotcort@gmail.com

^ I can give u video of it work here 
write me 

### Mods used

Infinite processor v7

### Save file

I can give file if u want 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There's no information here to work off of. Saves are required, and you're using a logic mod. I don't deal with modded issues.

**Comment by Kostr8** [comment]
It work Same on world processor but slower

And save is to big, i try to load it to Google drive now

It is processor issue or logic display

сб, 14 окт. 2023 г., 01:01 Anuken ***@***.***>:
