### ISSUE TITLE
The game crashes

### ISSUE THREAD

**Issue by Dususkerman** [Anuken/Mindustry#9172]
### Platforms

Android

### Build

Build 146

### Issue

When I enter a sector the game closes after 5-10 min or when I return to the menu, It happens in the normal app and in the beta

### Steps to reproduce

Enter a sector, wait a moment and try return to the menu

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
> Save file

>    THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by Slotterleet** [comment]
Crash log ***REQUIRED.***

**Comment by camelStyleUser** [comment]
and yes also the crashlog
