### ISSUE TITLE
Campaign Mode - Enemy turret seem have infinite resource

### ISSUE THREAD

**Issue by DVD27** [Anuken/Mindustry#9173]
### Platforms

Windows

### Build

7.0 - 146

### Issue

Like say in the title, when I attack an enemy base, turret seem have infinite resource.

For example, if I destroy the convoyer that supply the turret, it continue tu attack again and again until I destroy it.

### Steps to reproduce

Play a game in campaign mode in Serpulo, (a Base attack game ;))

It's seem not affect the new planet Erekir.

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
no if you cut supply to a turret unless the suply is rebuilt it will run out of ammo.

**Comment by DVD27** [comment]
Yes, bug that doesn't work for me... besides now that I think about it the enemy doesn't have any builder

**Comment by Anuken** [comment]
Save files required.
