### ISSUE TITLE
Unable to import mods on iOS

### ISSUE THREAD

**Issue by Firestorm827** [Anuken/Mindustry#918]
**Platform**:
IOS

**Build**: * release build 98

**Issue**: i downloaded a mod file from the official mindustry discord, and when i tried to import it into the game multiple times it sent me back to the home screen, without importing the mod

**Steps to reproduce**: the build 98 was newly introduced and since a few mods were on the discord i tried to import them into my game, but when i clicked “import mod” then tapped on a mod file from the iphone files app, it crashed

**Comment by Anuken** [comment]
This has the same cause as data import issue, so I'll be closing this to prevent redundancies.
