### ISSUE TITLE
Cannot run ./sdkmanager --licenses

### ISSUE THREAD

**Issue by mahdiyadiilavi1** [Anuken/Mindustry#9181]
### Platforms

Android

### Build

Android 13

### Issue

By running this command as said in readme.md, i get error `bash: ./sdkmanager: permission denied`

### Steps to reproduce

1. Do steps in readme.md
2. Run the command said at there "./sdkmanager --licenses" with Termux app

### Mods used

Es file explorer to extract file

### Save file

How do i upload file in mobile?

### (Crash) logs

bash: ./sdkmanager: permission denied

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by mahdiyadiilavi1** [comment]
I think if mindustry can be ran in mobile/arm devices, there is no reason it cant be compiled(bulided) on mobile/arm devices

**Comment by Anuken** [comment]
For this particular problem: `chmod +x sdkmanager`

This is not a bug. Building on Termux isn't supported, and it's up to you to get it working. I do not provide help in the issue tracker.

**Comment by mahdiyadiilavi1** [comment]
Oh youre right! In android 11 and later, i cannot run ot execute commands that need administrator premission or something similer

**Comment by SMOLKEYS** [comment]
> I think if mindustry can be ran in mobile/arm devices, there is no reason it cant be compiled(bulided) on mobile/arm devices

`aapt2`, among other things, does **not** work under the ARM architecture family. Even if you handled the issue with `aapt2`, you still have the other issues. Using a distro with `proot-distro` might work out, but I can't say if it successfully will as I haven't tested it myself.
