### ISSUE TITLE
Unit thrusters break after 15 hours of gameplay

### ISSUE THREAD

**Issue by BasedUser** [Anuken/Mindustry#9184]
### Platforms

Linux

### Build

146

### Issue

Several seconds after tick (`Time.time`) 3294100, unit thrusters will cease to function and will be stuck in a singular size.

### Steps to reproduce

I was playing around with timewarping (running a LOT of ticks in a space normally impossible) and ran against this graphical issue. 
1. Start a map.
2. Paste this code into the developer console:
```js
fps = 60;
fpstime = 1e9/fps;
i=0;
tgt=Math.floor(3294100-Time.time); /* edited for brevity */
timewarp = ()=>{
  Time.setDeltaProvider(()=>1);
  start = Time.nanos();
  starti = i;
  while(i < tgt && (Time.nanos() < start + fpstime)) {
    Vars.logic.update();
    i++;
  };
  end = Time.nanos();
  if(i == tgt) {
    Time.setDeltaProvider(()=>Math.min(Core.graphics.getDeltaTime()*60,3));
    Reflect.get(Events,"events").get(Trigger.draw).pop(); /* TODO delete SPECIFICALLY timewarp handler??? */
    return;
  };
  tps = (i-starti)*(1e9/(end-start));
  Vars.ui.showInfoPopup(java.lang.String.format("Simulating...\n%.0f/%.0f\n%.2f TPS\n%.2fx realtime",i,tgt,tps,tps/60),0,0,0,0,0,0);
  Time.setDeltaProvider(()=>0);
};

Events.run(Trigger.draw,timewarp);
```
, however, the following code should (and does on my machine) work as well:
```js
i = 1;
Time.setDeltaProvider(()=>3294100-Time.time);
Events.run(Trigger.update, () => {
  if(i==0){
    Time.setDeltaProvider(()=>Math.min(Core.graphics.getDeltaTime()*60,3));
    Reflect.get(Events,"events").get(Trigger.update).pop();
  };
  i = 0;
});
```
3. Observe the core unit.

### Mods used

N/A

### Save file

[file](https://github.com/Anuken/Mindustry/files/13060157/9183.msav.zip)

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Inherent issue with the way time works, won't fix.
