### ISSUE TITLE
pixel 4a5g

### ISSUE THREAD

**Issue by delinter** [Anuken/Mindustry#9192]
### Platforms

Android

### Build

f Droid 146

### Issue

For selecting multiple units or creating conduits or conveyor belts, double tap only works inconsistently. To test to see if it was an issue with the phone interface I connected to Bluetooth mouse and the issue persists with that as well. 

### Steps to reproduce

Steps to reproduce our to basically just use the game. Double tap works but is not consistent. It seems like the sensitivity for a double tap is set to too high so that you have to click it too fast or something. Selecting multiple units is possible but only sometimes. Pretty frustrating. 

### Mods used

None

### Save file

https://wormhole.app/A2qd3#-w1wOx5e4VkD96PhN4MTVg

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by delinter** [comment]
Download link expires after 24 hours or after 100 downloads.

**Comment by Anuken** [comment]
You're supposed to hold, not double tap. I have no issues with it.
