### ISSUE TITLE
Camera lag with Pixelate option turned on.

### ISSUE THREAD

**Issue by Aotenshin** [Anuken/Mindustry#9193]
### Platforms

Windows

### Build

146 

### Issue

If i activate the "pixelate" option under settings the camera "stutter" or "lag" when moving or zooming. It get worse the more its zoomed in. Its the most visible when slowing down with the player ship as it will result in "steps" with the camera and not a smooth slow down as expected like in the normal version. Is the feature in wip? I love the "classic" or pixelate version of the game, its just a shame its stuttering. Note that i have a 4k screen. I tested by changing DPI scalling override without better results (all 3 possible settings). 

### Steps to reproduce

1. Start the game
2. Start any map
3. Press ESC
4. Go to Settings
5. Graphics
6. Select Pixelate at the bottom of the list

### Mods used

N/A

### Save file

N/A as its a graphical issue.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
That's just how pixelation works. It's locked to pixels, which makes it stutter.

> Is the feature in wip?

It's only kept because people will complain if I remove it. I don't maintain it, or care for it at all. No issues with it will be fixed.

**Comment by Aotenshin** [comment]
Sad tho, the game look better with it, i just have to pixelize all you sprites then :') i guess you can close the issue. Thank's for the answer.
