### ISSUE TITLE
Galaxy s7

### ISSUE THREAD

**Issue by DracarisRegalis** [Anuken/Mindustry#9196]
### Platforms

Android

### Build

156

### Issue

Sector 133 spawns 500 tier four enemies on the first wave, every time i play it, even when i only brought titanium to the level, it makes it impossible to pass wave one, or develop to even survive 

### Steps to reproduce

It happens every time i start sector 133

### Mods used

None

### Save file

Sector 133
[(invalid).zip](https://github.com/Anuken/Mindustry/files/13078903/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate.
