### ISSUE TITLE
save data lost/switched

### ISSUE THREAD

**Issue by ljnacnud** [Anuken/Mindustry#9197]
### Platforms

Windows

### Build

146

### Issue

i haven't played mindustry for a while, but i got on and my planet was fully different, and it took some examination from my brother to figure out that i was placed onto a pretty old save of his world. nothing is mine, although my schematics and schematic tags travelled with me, and i'm pretty sure that the tech tree is the same too. the different things are just by going onto a sector i was unlocking things like phase fabric, whereas i believe i'm only at surge alloy myself, i have all of my brother's schematics along with my own, and i can't find anything except my schematics and (i think) my tech tree, though i obviously don't remember it exactly. this save file, even though it's old, is still more advanced than i was so i can't even morally play it as i haven't earned it. i am thinking the culprit could have been because between me last playing and now, i upgraded my computer largely, new motherboard, new case, new gpu, new cpu, but i kept my same ssd along with adding a new one. what confuses me is that it is a cloud saved game, so it shouldn't be affected by any of the possible issues that came with the upgrade, plus thinking about it, i think i upgraded before or during my burst of playthrough of the game. and even so, it switched my save with my brother's, which makes no sense. i had played multiplayer with him before, but i had done so with 2 other people as well. i'm not sure if i had played with him while he was at this point of progress, because we stopped playing at similar times. the last time i played btw was sometime after june 25 this year, as that was my last achievement time. there is the new build, which happened after i wasn't playing, maybe it's to do with that.

### Steps to reproduce

i don't know how it could be reproduced, maybe play a campaign on build 145 and then upgrade to 146 after playing multiplayer with someone? i'm not exactly sure what even happened, but my brother confirmed for sure it's his save, just old, he has made more progress and has checked his game.

### Save file

[messed-up-mindustry.zip](https://github.com/Anuken/Mindustry/files/13099237/messed-up-mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There's not enough evidence or steps to show what the bug is here (or if it's one at all). If upgrading versions or playing multiplayer were enough to trigger it, you wouldn't be the only one reporting this issue.

**Comment by ljnacnud** [comment]
> There's not enough evidence or steps to show what the bug is here (or if it's one at all). If upgrading versions or playing multiplayer were enough to trigger it, you wouldn't be the only one reporting this issue.

yeah, that makes sense, but is there a way i can recover my data at least? even just a few instructions on what i should look for in my files or something would be amazing, if there isn't a way that is fine, i just want to know if there is, for a chance at not restarting.

**Comment by Anuken** [comment]
The only thing that could potentially be recoverable is a lost tech tree (in very specific cases), but you say that you already have it. Nothing else can be recovered.

**Comment by ljnacnud** [comment]
hmm. that's funky, but after i looked a bit harder, it looks like it kept (probably) all of my old sectors i think, or at least the ones i care about, and it seems it just added in some sectors i haven't done and things like that, is there a way to delete the data for just specific sectors?

**Comment by ljnacnud** [comment]
> The only thing that could potentially be recoverable is a lost tech tree (in very specific cases), but you say that you already have it. Nothing else can be recovered.

hmm. that's funky, but after i looked a bit harder, it looks like it kept (probably) all of my old sectors i think, or at least the ones i care about, and it seems it just added in some sectors i haven't done and things like that, is there a way to delete the data for just specific sectors? there is a few that were overwritten, would messing with those mess up the ones that came farther in the story too?

**Comment by Anuken** [comment]
You can load into that sector and abandon it, which is close enough to deleting the files.

If you know the number, you can open the Steam local files (properties -> browse local files) -> `go to saves` -> `saves` and delete the file corresponding to the sector number (serpulo-sector-xyz.msav).

**Comment by ljnacnud** [comment]
sick, thanks!

**Comment by ljnacnud** [comment]
> You can load into that sector and abandon it, which is close enough to deleting the files.
> 
> If you know the number, you can open the Steam local files (properties -> browse local files) -> `go to saves` -> `saves` and delete the file corresponding to the sector number (serpulo-sector-xyz.msav).

it's been a second but i want to know, how do i find the number of the named sectors? there are a few with names like impact 0078 that i want to delete the save data for. i can't find much about it but the saves folder only has saves named in sector numbers.
