### ISSUE TITLE
Materials magically turning into stone on server.

### ISSUE THREAD

**Issue by Chenjox** [Anuken/Mindustry#92]
Simply log out and log in and your iron, coal etc have turned into stone.
Also works with freshlyplaced routers, junctions and tunnels.

I hope i can help.

Chenjox

**Comment by dangranos** [comment]
Not even on log in:
- Miners, uranium ones at least, randomly mine things like steel or iron
- There's sometimes uranium on iron or coal only conveyer lines that heavily use routers (that's after being sorted to ensure there's nothing but that material there. Can't be router contamination as well, or having a belt push into it)

**Comment by Anuken** [comment]
@dangranos Update to B19 first. Conveyor contamination was a known bug in b14, which was fixed.

**Comment by Anuken** [comment]
No longer occuring due to block sync changes.
