### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#920]
**Platform**: *Windows*

**Build**: *v99*

**Issue**: *When hovering over the phase generator in the german client the ui  flackers trying to reposition itself all the time. Guess it's because the name "Spannungsstoß-Legierung is too long for the panel.*

![image](https://user-images.githubusercontent.com/3829602/67652440-304e2c80-f945-11e9-85b2-7099fec27088.png)

**Steps to reproduce**: *Set client to german and hover over the phase generaotr ingame.*

**Comment by Anuken** [comment]
Duplicate.
