### ISSUE TITLE
ShallowLiquid not working in (H)JSON

### ISSUE THREAD

**Issue by overdramaticpanromantic** [Anuken/Mindustry#9200]
### Platforms

Mac

### Build

146

### Issue

ShallowLiquids don't render correctly in JSON or HJSON mods. Unit footsteps appear black, the tiles are pitch black on the minimap, and in-editor, the tiles pick a random part of a random sprite. For example, here is a ShallowLiquid from Fresh791/asthosus.
![image](https://github.com/Anuken/Mindustry/assets/108166075/6a414707-6094-4e9f-bda6-482573229752)
![image](https://github.com/Anuken/Mindustry/assets/108166075/d71dc78c-f4fe-49e8-ac9f-b204206c1d2d)
![image](https://github.com/Anuken/Mindustry/assets/108166075/6db69619-c36b-40cf-bb26-c211a78e0e51)

Here's a ShallowLiquid from BlueWolf3682/Allure.
<img width="638" alt="image" src="https://github.com/Anuken/Mindustry/assets/108166075/ae3e1582-044c-4be6-b855-9b6db1e60914">
<img width="327" alt="image" src="https://github.com/Anuken/Mindustry/assets/108166075/06c9f8ee-39ab-4f26-8d76-a46c9f6c1c2c">
<img width="793" alt="image" src="https://github.com/Anuken/Mindustry/assets/108166075/1610909e-eb29-493b-ad57-df9c72ee8c75">

Both tiles are located in their respective mod's content/blocks/environment folder.

If these images fail to load correctly, I'll put them all in a reply to this issue, because GitHub seems to be weird like that.

### Steps to reproduce

1. Create a .json or .hjson file. Name the file whatever you want. Ensure it's located in content/blocks/environment.
2. Put in "type: ShallowLiquid"
3. Set the desired liquidDrop and liquidMultiplier.
4. Set the cacheLayer to the desired value.
5. Set light and attributes, if applicable.
6. Commit changes.
7. Launch Mindustry, create a new map, and place these tiles in the editor.

### Mods used

Fresh791/asthosus
BlueWolf3862/Allure

### Save file

Save requires BlueWolf3862/Allure. Uploading here - if the file fails, I'll upload in a reply.
[ShallowLiquid_bug.msav.zip](https://github.com/Anuken/Mindustry/files/13170285/ShallowLiquid_bug.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by overdramaticpanromantic** [comment]
Miraculously, the files didn't fail to upload.

**Comment by Slotterleet** [comment]
ShallowLiquid is not supposed to be used in mods. I know, I tried. Use the Floor class instead.

**Comment by BlueWolf3682** [comment]
[Using it is entirely unnecessary.](https://github.com/BlueWolf3682/Allure/blob/master/content/blocks/environment/baenara-gravel.hjson) It's a class to just blend the liquid sprite onto the floor, and has no special functionality
