### ISSUE TITLE
Mods unable to be deleted, and mod folder not in expected location

### ISSUE THREAD

**Issue by sean-gribben** [Anuken/Mindustry#921]
**Platform**: *Windows*

**Build**: *99*

**Issue**: Unable to delete mods, and mod directory does not exist in normal location.

**Steps to reproduce**: Import mod. Upon importing, the zip file is added to \Steam\steamapps\common\Mindustry\saves\mods from what I can tell, instead of the \Steam\steamapps\common\Mindustry\mods like is said here: https://mindustrygame.github.io/wiki/modding/ . When trying to delete from inside mindustry, the mod is said to have been deleted, but upon reloading it appears straight back. Checking the mods folder reveals that the zip file is readded even once it is deleted. If the mods folder is manually deleted, it is still readded when mindustry begins. As well as this, subscribing to a mod places it in an unknown location, seemingly not in any mod folder (I have checked in appdata also)

**Comment by sean-gribben** [comment]
Ok after some testing I've found it's specifically an issue with zip files. This issue can actually be solved if you unzip the mod, delete the original zip file, start mindustry, then finally delete the mod from within mindustry. A bit weird, but it works

**Comment by sean-gribben** [comment]
Also in a separate issue, as mindustry doesn't let you import just regular folders the mindustry import shouldn't be used for now, instead it's probably better to manually copy the folder into the saves/mods folder yourself, so you don't have to import a zip

**Comment by Anuken** [comment]
The documentation is incorrect. `\Steam\steamapps\common\Mindustry\saves\mods` is the right location. The import function intentionally does not support folders and will only work with files.

Subscribed mods are placed in a special location by Steam and should not be deleted manually. I can't reproduce any issues with the delete function not working, even after importing a zip and/or restarting the game after deleting it.

**Comment by VaoxMods** [comment]
when you download the file on the git it is zipping the already made file simply extract the file click it drag the file out of the main file and then there you go.

**Comment by XEN0PHIL** [comment]
I see there's a lot of "can't delete mod" issues getting created and you replied to some of them that you cannot reproduce the bug. 
Did you try importing a .zip? I got this issue only with manual importing, Steam mods seem to delete themselves fine.

**Comment by Anuken** [comment]
Yes, I did try importing a zip. I've been planning to try running Steam on a windows VM to see if the issue is somehow OS-specific.

**Comment by Anuken** [comment]
Update: Yep, it seems to be windows-specific. Deleting a mod makes it reappear immediately.

**Comment by Anuken** [comment]
Fixed. Apparently windows doesn't like it when you don't close zip file streams.
