### ISSUE TITLE
Angle operation in processors being inaccurate

### ISSUE THREAD

**Issue by Cxyu629** [Anuken/Mindustry#9212]
### Platforms

Windows

### Build

146

### Issue

As mentioned in the title, the angle op is inaccurate from the fourth decimal place onwards.

[wolfram equation](https://www.wolframalpha.com/input?i=arctan2%280.001%2C+1%29+%2F+pi+*+180)

wolfram answer = 0.05729576...
angle op answer = 0.05736288...

![image](https://github.com/Anuken/Mindustry/assets/52622839/2dd7e074-ea5e-42da-a007-53a9c3e5b4fa)
![image](https://github.com/Anuken/Mindustry/assets/52622839/0849099e-cacc-410b-b889-7c3eeddf65ff)

### Steps to reproduce

Use the angle op in a processor, compare it with any online calculated values.

[wolfram equation](https://www.wolframalpha.com/input?i=arctan2%280.001%2C+1%29+%2F+pi+*+180)

### Save file

[bug.zip](https://github.com/Anuken/Mindustry/files/13197363/bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The angle operation is a faster approximation used for performance reasons; if you want exact values, use atan2 (but why? the approximation is good enough to use everywhere else in the game).
