### ISSUE TITLE
UI bug for anglediff operation 

### ISSUE THREAD

**Issue by Cxyu629** [Anuken/Mindustry#9213]
### Platforms

Windows

### Build

146

### Issue

anglediff overflows operator space in processor

![image](https://github.com/Anuken/Mindustry/assets/52622839/f609a0ee-fae0-4acd-9933-348e8fbfbca2)

### Steps to reproduce

Use anglediff operator in any processor.

### Save file

[bug2.zip](https://github.com/Anuken/Mindustry/files/13197380/bug2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Many instructions are like this, not interested in fixing.
