### ISSUE TITLE
Schematics: Parts are not being Placed/Selected

### ISSUE THREAD

**Issue by Terran-is-Here** [Anuken/Mindustry#922]
Platform: Windows 7 - 32 Bit
Build: 99
Issue: Certain blocks are not placed from schematics/selected items. While not all blocks are affected, Most of them are. When saving the Schematic however, most of the blocks are displayed in the preview picture. But when placing it, some blocks are only placed
 
Steps to Repreduce:
1. Scan something (A Crafter, Conveyor,eta)
2.Save it / Look at scanned amount
(extra): Compare it to original scan/Item

**Comment by Anuken** [comment]
fixed
