### ISSUE TITLE
Crash when destroying an enemy core

### ISSUE THREAD

**Issue by Austincraf1** [Anuken/Mindustry#9220]
### Platforms

Windows

### Build

146

### Issue

When destroying an enemy core the game crashes and shows error java.lang.NullPointerException

### Steps to reproduce

I destroyed any enemy core on erekir

### Mods used

Scheme size, Time control and Definitely balanced conveyors

### Save file

It happens in every sector from erekir

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 2004mb
Cores: 2
Mods: fstrcnvyrs:1.0.4, scheme-size:2.7.71, time-control:0.2

java.lang.NullPointerException: Cannot read field "parent" because the return value of "arc.scene.ui.layout.WidgetGroup.find(String)" is null
	at scheme.ui.HudFragment.lambda$updateBlocks$84(HudFragment.java:303)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash is caused be scheme-size, not Mindustry.

**Comment by Austincraf1** [comment]
thanks

**Comment by Austincraf1** [comment]
discovered that was a incompatibility between scheme size and Definitely balanced conveyors

**Comment by Austincraf1** [comment]
> discovered that it was a incompatibility between scheme size and Definitely balanced conveyors
