### ISSUE TITLE
Schematic builder getting erased with block breaking selector

### ISSUE THREAD

**Issue by Alstin112** [Anuken/Mindustry#9224]
### Platforms

Windows

### Build

146

### Issue

When I select to copy a schematic that is already built, in the transparent schematic that remains after selecting a schematic, I hover the mouse over it with the function to delete the blocks, but when I release the mouse nothing happens, but when I I go through it for the second time, it apparently breaks and does not delete everything that was previously selected with the mouse
![bug](https://github.com/Anuken/Mindustry/assets/108550823/2009f64b-05fc-49b4-8162-5d32dc7570c4)

### Steps to reproduce

1. Create a schematic with a size greater than 2, made with multiples blocks (or simply create a 2x2 small copper wall)
2. Press right-click to activate the breaking selection, (the blocks is marked, i don't think this should happen)
3. When you release the right-click, none of the blocks in the transparent schematic is delete.
4. Do the steps 2 and 3 again, and the blocks marked will be deleted from schematic.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Sounds like a mod issue. In my game, right-clicking instantly removes the schematic selection.

**Comment by Alstin112** [comment]
I'm using no mods.
I tried to investigate more, i downloaded the itch.io versions 32/64 bits, and works as you said.
but on my steam version i deleted the data, verified the files, uninstalled and installed, and still ocurring this bug.

**Comment by Anuken** [comment]
> I'm using no mods.

Are you sure? Check the mods menu.

**Comment by Alstin112** [comment]
I checked and still no mods, and as I said earlier. I tried delete all data of the mindustry, mods, saves, schematics, and still this bug.
https://github.com/Anuken/Mindustry/assets/108550823/1bfa1e95-82b9-4394-9018-c12ac686aff2

**Comment by Anuken** [comment]
Are you right clicking to break blocks?

**Comment by Alstin112** [comment]
yes

**Comment by Anuken** [comment]
Then, I don't have any solutions - it does not happen on my machine.

**Comment by Alstin112** [comment]
I found, my 'deselect' keybind has 'Q' instead of 'right-click', i think this is very usefull to destroy while holding a schematic, but destroying partially the schematic on the second time i use to destroy really bothers me.
