### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by MisiekDP** [Anuken/Mindustry#9225]
### Platforms

Android

### Build

146

### Issue

The game crasch after ~30 seconds when I load the save fie.
When I get Androids popup with sending data I see the OutOfMemoryError.
The game doesn't have mods.

### Steps to reproduce

Load the save file from attachment and wait about 30 - 60 seconds.

### Mods used

Nothing

### Save file

Campaign > Erekir > Basin
The save file attached: https://www.mediafire.com/file/0e7e9k4ycp4twwr/eksport_danych_przed_craschem.zip/file

### (Crash) logs

Logs attached as file: https://www.mediafire.com/file/r0tvg9mq8ykqb0v/log_bledow/file

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You need a better device. Mindustry only has 256mb of RAM to run, which is not sufficient.

**Comment by MisiekDP** [comment]
> You need a better device. Mindustry only has 256mb of RAM to run, which is not sufficient.

I play on Xiaomi Mi Pad 5 which has 6GB of RAM 🤔
I will try on the OnePlus 7 Pro too with 8GB RAM.
It is really not sufficient?

**Comment by MisiekDP** [comment]
@Anuken on the OnePlus 7 Pro 8GB RAM with CrDroid 13 I have this same issue. And this devica has too _I] [RAM] Available: 256.0 MB_.

**Comment by Anuken** [comment]
> And this device has too [I] [RAM] Available: 256.0 MB.

Well, that's how much RAM the application itself is given to run, and I can't do anything about that.

The issue in your save is that the map blocks off off-screen-tanks, which waste memory pathfinding to the destination. A fix is to add blast doors to the enemy side of the map, but it won't fix your crash, since the map is already loaded.

**Comment by MisiekDP** [comment]
And it is not possible to change the RAM value in the save or game? Why on other device I have that same (small) RAM value? Or maybe is it possible to run a game on Windows to repair this?

**Comment by MisiekDP** [comment]
To be sure, I love this game like Factorio but still don't understand how to repair this. And what to do to not met this issue again.

**Comment by Anuken** [comment]
> And it is not possible to change the RAM value in the save or game?

Nope.

> Why on other device I have that same (small) RAM value? 

Ask whoever implemented it. It isn't consuming anywhere near 6GB of RAM on my machine, even in the worst case on that map.

>  And what to do to not met this issue again.

Wait until the next update and restart the map.

> Or maybe is it possible to run a game on Windows to repair this?

Yes, it *might* help if you ran `Vars.world.tile(348, 326).build.kill()` in the console on desktop to open the gap. This would require the PC, or a mobile console mod.
