### ISSUE TITLE
JSON Modded Status effects doesn't reacts with others 

### ISSUE THREAD

**Issue by zeutd** [Anuken/Mindustry#9232]
### Platforms

Android

### Build

146

### Issue

there has two JSON status effects
{
	"name": "status1",
	"color": "FFFFFF",
	"damage": 0,
	"transitionDamage": 10000,
	"affinities": ["status2"]
}

{
	"name": "status2",
	"color": "FFFFFF",
	"damage": 0,
	"transitionDamage": 10000,
	"affinities": ["status1"]
}

and they doesn't reacts with other and cause damage

### Steps to reproduce

i just created two status in JSON that has 0 damage and affinities to each other and transitionDamage is 99999. but when i apply them in game,  it doesn't cause damage.

### Mods used

[just-testing-the-status-effect.zip](https://github.com/Anuken/Mindustry/files/13255422/just-testing-the-status-effect.zip)

### Save file

this is a modding-related issue and issue happend in all games

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Transition damage must be implemented in code. It's a purely stat value. JSON status effects don't support it.
