### ISSUE TITLE
Where is button "Import with GitHub" in version 5-official99??? Please return!

### ISSUE THREAD

**Issue by MrEgor4Ik** [Anuken/Mindustry#924]

**Comment by Quezler** [comment]
Are you on android? if so its disabled due to issues with http(s) 😗

**Comment by willis936** [comment]
https://github.com/Anuken/Mindustry/commit/34db321577d982d01285bb1c4e8d101c071b9b09

**Comment by Anuken** [comment]
It's not coming back on Android. HTTP is completely unreliable there.

**Comment by medpig** [comment]
Анюкен , верни загрузку с гитхаб...
