### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by X1nnh** [Anuken/Mindustry#9242]
### Platforms

Android

### Build

146

### Issue

the southern part of declive (Erekir) doesn't load to me
![Screenshot_20231105_102929](https://github.com/Anuken/Mindustry/assets/149937317/00ac5108-7406-48e1-a8a9-59faccdcf597)

### Steps to reproduce

i resetted the zone 4 times because i didn't know when did they attack

### Mods used

none

### Save file

[bug_mindustry.zip](https://github.com/Anuken/Mindustry/files/13259300/bug_mindustry.zip)

### (Crash) logs

no

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug. Do the rest of the map.
