### ISSUE TITLE
Unit summoning issue

### ISSUE THREAD

**Issue by wang1986one** [Anuken/Mindustry#9246]
### Platforms

Android

### Build

146

### Issue

At sector 133 of serpulo the enemy sends out 559 units  at wave 1.![image](https://github.com/Anuken/Mindustry/assets/11283133/8cb48c60-cdf3-4ee3-9214-c433d03fcd90)![image](https://github.com/Anuken/Mindustry/assets/11283133/e4f10389-a35b-4e0d-9f4f-d1c2c9ebc66b)

### Steps to reproduce

This happened before when I first landed on the sector

### Mods used

None

### Save file

[Bug-sector-133.zip](https://github.com/Anuken/Mindustry/files/13261739/Bug-sector-133.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate.

**Comment by wang1986one** [comment]
I test the BE build ,still have this bug
https://github.com/Anuken/MindustryBuilds/releases/tag/24547

**Comment by wang1986one** [comment]
> Duplicate.

I`m still having issues loading the save file with the daily build version
https://github.com/Anuken/MindustryBuilds/releases/tag/24547

save file:
[bug.zip](https://github.com/Anuken/Mindustry/files/13262268/bug.zip)

**Comment by wang1986one** [comment]
@Anuken Should I start the game over?Can't I use the old save file?

**Comment by Anuken** [comment]
Wait until the new version is released.
It's not clear when or why this bug happens, so for now just avoid that sector.

**Comment by wang1986one** [comment]
> Wait until the new version is released. It's not clear when or why this bug happens, so for now just avoid that sector.

OK, thank you

**Comment by wang1986one** [comment]
> Wait until the new version is released. It's not clear when or why this bug happens, so for now just avoid that sector.

@Anuken  
I circumvented this bug by deleting the sector-serpulo-133.msav and sector-serpulo-133.msav-backup.msav files in the game data folder and re-entering sector 113, everything returned to normal.
I suspect that the bug may have occurred during the generation of the map.
