### ISSUE TITLE
Launch Pad bug

### ISSUE THREAD

**Issue by wang1986one** [Anuken/Mindustry#9250]
### Platforms

Android

### Build

146

### Issue

1,The Launch Pad can even launch without power, only needs the launch cooldown completed (I think this might be a bug)

2,The Launch Pad can be launched even the destination is none, (Destroyed by the enemy)

3,How can I manually set the destination to none? I tried setting it to the current sector but it doesn't work

4,I tried to build a logistics center, so I built many Vaults and Launch Pads, as well as some Large Batteries, I found that it only works when I open the current sector, and it does not update when I open other sectors.  (You can load the save file and open 'Salt Flats')

![image](https://github.com/Anuken/Mindustry/assets/11283133/e3adbc8f-c193-4753-9f17-08cf489098e8)

![image](https://github.com/Anuken/Mindustry/assets/11283133/498d9ba9-8bfe-486b-b4ae-534a3fd88245)

![image](https://github.com/Anuken/Mindustry/assets/11283133/4f117100-2a3e-4765-aa8a-143310b4aa89)

### Steps to reproduce

none

### Save file

[LaunchPad.zip](https://github.com/Anuken/Mindustry/files/13274531/LaunchPad.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
None of these are bugs.
