### ISSUE TITLE
Weird graphical artifacts when I run the game

### ISSUE THREAD

**Issue by poggers16** [Anuken/Mindustry#9252]
### Platforms

Windows

### Build

146

### Issue

GPU's: Intel Graphics HD 4600, Nvidia GeForce 840M
OpenGL Version: 4.6

Just got a new laptop, started Mindustry and got these weird artifacts on my game window. Game is also noticeably laggy when loading the server menu. (Windows says that my graphics drivers are up-to-date btw)

Video:
https://github.com/Anuken/Mindustry/assets/83654349/af7753f5-a11b-4a87-bf0e-8ad41b6604d4

### Steps to reproduce

1. Start the game with the exact GPUs that I have.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
GPU/driver bugs. Never seen this on any device before.

**Comment by poggers16** [comment]
ok i fixed the issue, appearently running 2 gpus at the same time isnt a good idea

**Comment by Slotterleet** [comment]
How are you even running both the _integrated_ and _dedicated_ GPU at the same time? (Dedicated GPU is always better if you have one btw)
