### ISSUE TITLE
bouncing phenomenon

### ISSUE THREAD

**Issue by aajkrvv** [Anuken/Mindustry#9259]
### Platforms

Android

### Build

416

### Issue

Bouncing frequently while playing a game

### Steps to reproduce

Device: Samsung Galaxy A13(Reference: This phone has 32 bits)
There is a bouncing phenomenon regardless of the map during the game
There is no bug during pause, Bug occurs even when viewing without manipulation

### Mods used

None

### (Crash) logs

[Error log](https://github.com/Anuken/Mindustry/files/13305275/Error.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I assume by "bounce" you mean crash, but there is not crash in the log. Also, 416 isn't a build.
