### ISSUE TITLE
Rebind controls not working

### ISSUE THREAD

**Issue by no112358** [Anuken/Mindustry#9265]
### Platforms

Windows

### Build

146

### Issue

I'm playing the campaign and I don't have the [ and ] (default keys set by the game) on my keyboard, AltGR+F and AltGr+G also don't work. I tried to change the default keys, and the game just doesn't use the new key shortcuts I set. I tried setting and restarting the game, still not working.

### Steps to reproduce
trying to do the Split campaign where you're required to pickup a container an place it onto the payload loader. I can't continue with the campaign because the Payload mass drivers don't work, I presume until you do the container bit the game is requiring you to do.

### Mods used

None

### Save file

[gamedata.zip](https://github.com/Anuken/Mindustry/files/13326625/gamedata.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue, rebinding the keys works correctly for me. Sounds like something is wrong with your keyboard, never heard of one missing [/].

**Comment by no112358** [comment]
the keyboard doesn't have the symbols printed on it. I hooked up an older full size keyboard that has the symbols. Still not working.

To pickup I have to press ALTgr+F, and it just doesn't work.

Rebind works in settings, but the actual buttons don't o anything in game.

**Comment by no112358** [comment]
DUDE... you could write that you have to HOVER OVER THE damn box to pick it up... that was an epic waste of time...

**Comment by JasonP01** [comment]
Damn bro... thats the developer of the game 💀

**Comment by Volas171** [comment]
>     * When I bind ALTgr on both my keyboards it gets detected as L-Ctrl???? ALTgr works fine in windows for @ symbol etc...
sounds like a keyboard layout/system locale issue, have you checked if you got those right before opening the issue?
