### ISSUE TITLE
Crash Encounter

### ISSUE THREAD

**Issue by markalbert7** [Anuken/Mindustry#9267]
### Platforms

Android

### Build

Build 146

### Issue

Game crashes. Look furthermore in this crash log

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 146
OS: Linux xnull (aarch64)
Android API level: 31
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

> Runtime: 'android.os.DeadSystemException'
AutofillManager.startSessionLocked: 1914
AutofillManager.notifyViewEnteredLocked: 1088
AutofillManager.notifyViewEntered: 1048
AutofillManager.notifyViewEntered: 1005
View.notifyEnterOrExitForAutoFillIfNeeded: 8226
View.layout: 23549
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
AlertDialogLayout.setChildFrame: 358
AlertDialogLayout.onLayout: 351
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
DecorView.onLayout: 1014
View.layout: 23490
ViewGroup.layout: 6529
ViewRootImpl.performLayout: 4124
ViewRootImpl.performTraversals: 3568
ViewRootImpl.doTraversal: 2431
ViewRootImpl$TraversalRunnable.run: 9435
Choreographer$CallbackRecord.run: 1228
Choreographer.doCallbacks: 1012
Choreographer.doFrame: 922
Choreographer$FrameDisplayEventReceiver.run: 1213
Handler.handleCallback: 938
Handler.dispatchMessage: 99
Looper.loopOnce: 233
Looper.loop: 334
ActivityThread.main: 8501
RuntimeInit$MethodAndArgsCaller.run: 582
ZygoteInit.main: 1068
> DeadSystem
AutofillManager.startSessionLocked: 1914
AutofillManager.notifyViewEnteredLocked: 1088
AutofillManager.notifyViewEntered: 1048
AutofillManager.notifyViewEntered: 1005
View.notifyEnterOrExitForAutoFillIfNeeded: 8226
View.layout: 23549
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
AlertDialogLayout.setChildFrame: 358
AlertDialogLayout.onLayout: 351
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
DecorView.onLayout: 1014
View.layout: 23490
ViewGroup.layout: 6529
ViewRootImpl.performLayout: 4124
ViewRootImpl.performTraversals: 3568
ViewRootImpl.doTraversal: 2431
ViewRootImpl$TraversalRunnable.run: 9435
Choreographer$CallbackRecord.run: 1228
Choreographer.doCallbacks: 1012
Choreographer.doFrame: 922
Choreographer$FrameDisplayEventReceiver.run: 1213
Handler.handleCallback: 938
Handler.dispatchMessage: 99
Looper.loopOnce: 233
Looper.loop: 334
ActivityThread.main: 8501
RuntimeInit$MethodAndArgsCaller.run: 582
ZygoteInit.main: 1068

### Steps to reproduce

Im just playing the game while configuring some micro processors the games suddenly crashed

### Mods used

No mods used

### Save file

[campaign mindustry.zip](https://github.com/Anuken/Mindustry/files/13327088/campaign.mindustry.zip)
Sector Name: FZ TitaniumOmegaDef (in Frozen Forest)

### (Crash) logs

[crash_1699755791842.txt](https://github.com/Anuken/Mindustry/files/13327093/crash_1699755791842.txt)

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 146
OS: Linux xnull (aarch64)
Android API level: 31
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

> Runtime: 'android.os.DeadSystemException'
AutofillManager.startSessionLocked: 1914
AutofillManager.notifyViewEnteredLocked: 1088
AutofillManager.notifyViewEntered: 1048
AutofillManager.notifyViewEntered: 1005
View.notifyEnterOrExitForAutoFillIfNeeded: 8226
View.layout: 23549
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
AlertDialogLayout.setChildFrame: 358
AlertDialogLayout.onLayout: 351
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
DecorView.onLayout: 1014
View.layout: 23490
ViewGroup.layout: 6529
ViewRootImpl.performLayout: 4124
ViewRootImpl.performTraversals: 3568
ViewRootImpl.doTraversal: 2431
ViewRootImpl$TraversalRunnable.run: 9435
Choreographer$CallbackRecord.run: 1228
Choreographer.doCallbacks: 1012
Choreographer.doFrame: 922
Choreographer$FrameDisplayEventReceiver.run: 1213
Handler.handleCallback: 938
Handler.dispatchMessage: 99
Looper.loopOnce: 233
Looper.loop: 334
ActivityThread.main: 8501
RuntimeInit$MethodAndArgsCaller.run: 582
ZygoteInit.main: 1068
> DeadSystem
AutofillManager.startSessionLocked: 1914
AutofillManager.notifyViewEnteredLocked: 1088
AutofillManager.notifyViewEntered: 1048
AutofillManager.notifyViewEntered: 1005
View.notifyEnterOrExitForAutoFillIfNeeded: 8226
View.layout: 23549
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
AlertDialogLayout.setChildFrame: 358
AlertDialogLayout.onLayout: 351
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
View.layout: 23490
ViewGroup.layout: 6529
FrameLayout.layoutChildren: 332
FrameLayout.onLayout: 270
DecorView.onLayout: 1014
View.layout: 23490
ViewGroup.layout: 6529
ViewRootImpl.performLayout: 4124
ViewRootImpl.performTraversals: 3568
ViewRootImpl.doTraversal: 2431
ViewRootImpl$TraversalRunnable.run: 9435
Choreographer$CallbackRecord.run: 1228
Choreographer.doCallbacks: 1012
Choreographer.doFrame: 922
Choreographer$FrameDisplayEventReceiver.run: 1213
Handler.handleCallback: 938
Handler.dispatchMessage: 99
Looper.loopOnce: 233
Looper.loop: 334
ActivityThread.main: 8501
RuntimeInit$MethodAndArgsCaller.run: 582
ZygoteInit.main: 1068

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Documentation says that this particular error happens when the Android system dies, which is not something I can fix. Could be your device simply running out of memory.
