### ISSUE TITLE
Achivement is given for a wrong thing

### ISSUE THREAD

**Issue by SaksefonTM** [Anuken/Mindustry#9269]
### Platforms

Windows

### Build

146.0

### Issue

Achievement "Mending" (which is for building the mend PROJECTOR) Is granted by building a mender (the small one instead of the big one)
![obraz_2023-11-12_122425586](https://github.com/Anuken/Mindustry/assets/150374599/97cd54c7-e567-40d8-a2da-aecff36f701b)

### Steps to reproduce

Just build a mender on the steam version

### Mods used

No mods

### Save file

Just change them back from zip to .msav
[sector-serpulo-15.msav-backup.zip](https://github.com/Anuken/Mindustry/files/13327839/sector-serpulo-15.msav-backup.zip)
[sector-serpulo-15.zip](https://github.com/Anuken/Mindustry/files/13327840/sector-serpulo-15.zip)
[sector-serpulo-175.msav-backup.zip](https://github.com/Anuken/Mindustry/files/13327841/sector-serpulo-175.msav-backup.zip)
[sector-serpulo-175.zip](https://github.com/Anuken/Mindustry/files/13327842/sector-serpulo-175.zip)

### (Crash) logs

Not a crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Slotterleet** [comment]
Both blocks are functionally the same. What's the problem?

**Comment by Anuken** [comment]
Technically intentional, but people seem confused by this, so I'll change it.
