### ISSUE TITLE
Два ядра

### ISSUE THREAD

**Issue by ProstoProlletariy** [Anuken/Mindustry#9275]
### Platforms

Windows

### Build

146

### Issue

Когда игрок пытается захватить новый сектор вместо первого ядра, которое я улучшил, выбирается другое ядро на первом уровне. Если это нормально, извините.

### Steps to reproduce

после каждого захвата сектора я выходил в главное меню из за личных дел. Один из секторов я захватил - 214. После я улучшил ядро и захватил ещё 221 и 222 секторы. Наконец, если я хочу из главного меню отправиться в 215 сектор, то вылетает ядро первого уровня из 214 сектора.

### Mods used

нет модов

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by ProstoProlletariy** [comment]
You can use translater if you dont understand this. For translater - this is russion text

**Comment by NotAntoxa** [comment]
Это происходит из-за того что 214 ближе всех к 215, просто зайди в любой другой сектор с ядром второго уровня. Не думаю что это баг.

**Comment by ProstoProlletariy** [comment]
вероятно ты прав, но это мне получается надо будет сколько ядер до этого прокачивать на 2-й уровень выходит?
