### ISSUE TITLE
Writing error

### ISSUE THREAD

**Issue by Lucas559-noob** [Anuken/Mindustry#928]
Windows 64bits

Build 99
typo, the translation is correct but has digits between
<a href="https://gyazo.com/120e396b9f885a1d13ad1a6c13ddf31e" target="_blank">Image</a>
[Image](https://gyazo.com/11379b669aa93b3e5bcc1459aadb5e70)
Enter the game language in Brazilian Portuguese

Using translator

**Comment by Anuken** [comment]
Issues with translations should not be reported here.
