### ISSUE TITLE
Integers with high value are not printed correctly

### ISSUE THREAD

**Issue by JeanJPNM** [Anuken/Mindustry#9281]
### Platforms

Windows

### Build

146

### Issue

Attempting to print a number that is an integer bigger than `10e10` will result on it not being printed correctly.
![image](https://github.com/Anuken/Mindustry/assets/61994401/0229ad7d-a386-4f79-95ef-55b41c786b16)

### Steps to reproduce

- Create a processor with a message linked to it.
- Paste this code:
```
print 10e10
printflush message1
```
- Check output on the message

### Save file

[long_max_value_exceeded.zip](https://github.com/Anuken/Mindustry/files/13358081/long_max_value_exceeded.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JeanJPNM** [comment]
10e10 is not even close to `Long.MAX_VALUE`. I'll update the issue.

**Comment by Anuken** [comment]
Number parsing issue, not printing issue. Fixed.
