### ISSUE TITLE
｢Save & Quit｣→｢Quit｣

### ISSUE THREAD

**Issue by uygsd** [Anuken/Mindustry#9287]
### Platforms

Android

### Build

146

### Issue

When I am playing custom play and I try to quit the game it just says "Quit" and will not allow me to save.
Also, the "auto save" is off.
This is fatal and I cannot enjoy this game, please improve it!
Finally, I am writing this text using a translation.
Thanks again for a fun game!
:)

![Screenshot_20231118-124045](https://github.com/Anuken/Mindustry/assets/138998133/2b5f5107-1693-4ea5-a877-52d91545c59e)

### Steps to reproduce

I was playing on a map called "A WW2 Attack Map" when it suddenly happened.
Now that you mention it, it may be because of my settings, let me apologize then.

### Mods used

minzoom" and "Time Control.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> Now that you mention it, it may be because of my settings

It is. Enable auto-creation of saves, or save the game manually.

> will not allow me to save.

You have not specified how or why, so I assume you simply have not made a save.
