### ISSUE TITLE
Game Crashes when playing custom sound

### ISSUE THREAD

**Issue by Yoru-Kitsune** [Anuken/Mindustry#9291]
### Platforms

Android

### Build

BE 24579

### Issue

Mindustry crashes when I try to play a custom sound with the attached mod.
I don't know what I do wrong but in other mods it works.
Even if it isn't a bug please say what I need to do to fix it

### Steps to reproduce

- Go on the custom map within the mod
- Mine 9 cobblestone by mining these stone floors
- Mine 1 coal by mining coal ore
- Place 1 "Cobblestone > Stone" furnace
- Put 1 cobblestone and 1 coal in the furnace

### Mods used

[mod.zip](https://github.com/Anuken/Mindustry/files/13400101/Craftdustry.-.Survival.zip)

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/13400105/save.zip)

### (Crash) logs

[crash-logs.zip](https://github.com/Anuken/Mindustry/files/13400107/crash-logs.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash seems unrelated to sound, you have multiple mods installed and one of them is completely screwing up the drawing code by changing batch state. Can't say which one is causing it.

**Comment by Yoru-Kitsune** [comment]
If I run the game without any other mod it still crashes

**Comment by Yoru-Kitsune** [comment]
It only crashes tho since I have put the sound in and only when the sound is supposed to play

**Comment by Anuken** [comment]
The crash log doesn't contain anything relating to sound.

**Comment by Anuken** [comment]
Testing this myself, there appears to be something very, very wrong with the furnace .ogg file you've provided, which causes a crash in the audio engine (which is an external library).

For one thing, it's massive, and for another, it seems to contain video data? Is that even legal for an OGG file? Are you sure it's a proper OGG file? I suggest re-encoding it.

![image](https://github.com/Anuken/Mindustry/assets/10100000/ae296ca7-1966-4c4a-8004-66d9b360c119)

**Comment by Yoru-Kitsune** [comment]
Ohhhh lol
I recorded a video and just changed the file extension
I just tried making changing it with an online converter and now it works
But thanks for the help
