### ISSUE TITLE
Lost sector for no reason at all

### ISSUE THREAD

**Issue by Nghiem-HuyHung-11222608** [Anuken/Mindustry#9292]
### Platforms

Android

### Build

146

### Issue

Lost my tar fields sector which is the only thorium sector i have for no reason at all everthing proof that it exist
![Screenshot_Mindustry_2023-11-18-18-27-36-568](https://github.com/Anuken/Mindustry/assets/66253501/cbcbe4b4-9717-4c07-ae79-b1c6dfd86152)
![Screenshot_Mindustry_2023-11-18-18-28-49-151](https://github.com/Anuken/Mindustry/assets/66253501/559d7564-876f-4bad-95dc-f7f36bc58fdd)

### Steps to reproduce

1 idk how i got the bug

### Mods used

No mod

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/13400187/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not enough information here to go off of.

**Comment by Nghiem-HuyHung-11222608** [comment]
What information do you need ?

**Comment by Anuken** [comment]
A consistent way to reproduce the sector disappearing without good reason. The only thing I can do with your save is see that the sector is gone, with no way to find out why.

**Comment by Nghiem-HuyHung-11222608** [comment]
Because teh sector just disapearred out of no where the only thing i can show you that the evidence i have completed the sectir but then lost it out of nowhere the production on the map also show that i have it before

**Comment by Nghiem-HuyHung-11222608** [comment]
https://discord.com/channels/391020510269669376/477494303061442571/1175471122800713891

**Comment by KhaledHawwas** [comment]
didn't it get attacked and destroyed in the background?

**Comment by ytrytio** [comment]
This can happen if you have previously used kernels from mods and then disabled the mods. Accordingly, all the contents of the mod will disappear, as well as the core. I don't have any other guesses.
