### ISSUE TITLE
Pathfind is broky #2 with the correct video this time

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Anuken/Mindustry#9296]
### Platforms

Android

### Build

V146

### Issue

Pathfind is doing a uno reverse with ghost buildings and not acting like it should by going to the target instead of not refer to the video for the example the video is woth 400 paragraphs ngl

### Steps to reproduce

Make a pathfind to the proc or anything else

https://github.com/Anuken/Mindustry/assets/63037076/0a6274bc-8ec7-44d2-b2be-94dfc0fc8536

### Mods used

None

### Save file

[bug report.zip](https://github.com/Anuken/Mindustry/files/13401949/bug.report.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I already explained this on the last issue, why open it again?

> Units can't pathfind onto solid objects. Not a bug.

**Comment by XxsuperdeadlysniperxX** [comment]
> I already explained this on the last issue, why open it again?
> 
> > Units can't pathfind onto solid objects. Not a bug.

I only re opened it to insert the correct video also the variables wackify with pathfind not sure why
