### ISSUE TITLE
Group intersects are partly broken

### ISSUE THREAD

**Issue by nvcbl** [Anuken/Mindustry#9300]
### Platforms

Windows

### Build

146

### Issue

On groups `all`, `player`, `build`,  `sync` and `draw`, if you try to use the `intersect` method, you get a `NullPointerException` error.

### Steps to reproduce

Use the `intersect` method on one of the affected groups (e.g. `Groups.build.intersect(0, 0, 100, 100);`)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Then don't. Intersects are not supported for any groups outside of units.
