### ISSUE TITLE
15k Resources in the Core

### ISSUE THREAD

**Issue by Rensen242** [Anuken/Mindustry#9301]
### Platforms

Android

### Build

146

### Issue

Core could store more then 13k Res

### Steps to reproduce

Have lost an map, with foundation Core. Beside the Core some Vault storage Had been placed wich we're destroyed with the Core.

After launching again but with Nucleus Core covering part of the space of two previously destroyed Vault i was able to store 15 k in the Core.

Screenshot:

![Screenshot_2023-11-17-11-07-37-633_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/151687657/fa30838a-d459-4f38-a456-4d12c6d242b7)

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Saves are required.

**Comment by Slotterleet** [comment]
That's intentional. Adjacent containers and vaults are actually increasing the core's capacity. The maximum possible capacity Core: Nucleus can have is 21,600 items.

**Comment by Mythril382** [comment]
> That's intentional. Adjacent containers and vaults are actually increasing the core's capacity. The maximum possible capacity Core: Nucleus can have is 21,600 items.

Said they were destroyed along with the core though.
