### ISSUE TITLE
Bug a conveyers

### ISSUE THREAD

**Issue by Durmiendo** [Anuken/Mindustry#9311]
### Platforms

Android

### Build

146

### Issue

The invert gateway is not working properly
![Screenshot_20231124-220556](https://github.com/Anuken/Mindustry/assets/118241307/004ab057-b6e2-4f24-a27f-098bdf80493c)

### Steps to reproduce

Made logical elements on conveyors

### Save file

[data.zip](https://github.com/Anuken/Mindustry/files/13460448/data.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Happens due to instability of FPS and other factors, won't fix.
