### ISSUE TITLE
Hungry hungry ground factory

### ISSUE THREAD

**Issue by odis182** [Anuken/Mindustry#9317]
### Platforms

Android

### Build

146

### Issue

Ground factory is collecting all of 2 resource types and not filling up~ sort of. The number is jumping around but never let's any res pass the underflow gate.

### Steps to reproduce

Not a clue.

### Mods used

None

https://github.com/Anuken/Mindustry/assets/149843844/52d3bf46-a4de-4f2c-b41a-b53fdb69cba7

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/13467839/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by perelllaquairusbrown** [comment]
unloader backflow

**Comment by Anuken** [comment]
Not a bug, you have unloaders next to it.

**Comment by odis182** [comment]
> Not a bug, you have unloaders next to it.

What is unloader backflow? How does the unloader take resources out of the ground factory?

**Comment by rylid-umil** [comment]
I think so. It can do that, and it's happened with any block that store items.

**Comment by odis182** [comment]
But not turrets apparently. Currently the only other use I can see for this function.
