### ISSUE TITLE
MULTIPLAYER AND MOD BROWSER NOT WORKING

### ISSUE THREAD

**Issue by Ayushkiller** [Anuken/Mindustry#9320]
### Platforms

Android

### Build

7-official-146

### Issue

![image](https://github.com/Anuken/Mindustry/assets/152204318/847a130a-042d-467b-a190-8246b5fe7d66)
tHIS ERROR APPEARS AND SEVERS DO NOT SHOWS ANY SERVERS

### Steps to reproduce

I JUST DOWNLOADED IT FROM OFFICAL PLAY STORE

### Save file

[imp.zip](https://github.com/Anuken/Mindustry/files/13478091/imp.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Ayushkiller** [comment]
WAITING FROM LAT 3 DAYS

**Comment by Anuken** [comment]
Something is wrong with your network. GitHub is being blocked on your end.

**Comment by Ayushkiller** [comment]
anuken looks like all jio(internet service provide for country india) as blocked it in india.

**Comment by mahdoosh1** [comment]
> anuken looks like all jio(internet service provide for country india) as blocked it in india.

That's right! Here, at Iran I can download mods and load server list, but I can't join multiplayer servers. due to same reasons (here, ISP has banned outernet connections that are not verified due to country laws)
