### ISSUE TITLE
Bug team building

### ISSUE THREAD

**Issue by ytrytio** [Anuken/Mindustry#9347]
### Platforms

Linux

### Build

v7, build 146

### Issue

![Screenshot_20231204_174003](https://github.com/Anuken/Mindustry/assets/78297142/8aaf722f-d847-4332-b21e-de6d70f7200d)
In the photo, the unit is trying to build/break a block, but nothing works

### Steps to reproduce

When you change a team, but this team does not have a core, you can try to build any block, but only outlines will appear and it will be impossible to break/build it.

### Save file

This happens in multiplayer.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This was already reported. Search the closed issues first, as the template asks.
