### ISSUE TITLE
Official versioning scheme

### ISSUE THREAD

**Issue by fgaz** [Anuken/Mindustry#935]
I'm packaging Mindustry for NixOS, and I have to choose how to represent versions, but the information is conflicting. There are:

* The GitHub release names (5.0 currently), which is similar to a version number but it contains duplicates so it cannot be used
* The build number (99 currently), which is also used in git tags and in the game, which seems like a sensible choice, but will it always exist or will Mindustry switch to the "5.0" scheme and break monotonicity?
* [Repology](https://repology.org/project/mindustry/versions) shows that some custom schemes are in use, like 5.0_99

Which one should I (and other packagers) use?

**Comment by willis936** [comment]
I’m not a contributor, so this is purely informative, but I have noticed that the github issue template says to list the build number.  This seems like the more reliable way to differentiate versions.

**Comment by Anuken** [comment]
The versioning scheme is a bit of a mess.
There's the base release names (`5.0`, etc), which just display the 'major' version (and is of little importance), and the *builds*, which are displayed in the menu and used for server/client compatibility checks. You should only need to use the build number.

**Comment by fgaz** [comment]
Ok, so if I understand correctly "5.0" is a codename, like "Bionic Beaver" is for the 18.04.x Ubuntu series.
Thanks for the info! I'll use the build number then

**Comment by fgaz** [comment]
I also opened a repology report so that wrong versions are ignored: https://repology.org/project/mindustry/report

**Comment by AMDmi3** [comment]
> The versioning scheme is a bit of a mess.
> There's the base release names (`5.0`, etc), which just display the 'major' version (and is of little importance), and the _builds_, which are displayed in the menu and used for server/client compatibility checks. You should only need to use the build number.

Would be nice to only use build numbers in release names too to avoid confusion.
