### ISSUE TITLE
game crashed after destroying enemy core (likely rendering related)

### ISSUE THREAD

**Issue by antonilol** [Anuken/Mindustry#9353]
### Platforms

Linux

### Build

146

### Issue

after destroying the enemy core on salt flats the game crashed

got this stack trace from the console (also in the crash log)
```
[E] java.lang.NullPointerException: Cannot read field "parent" because the return value of "arc.scene.ui.layout.WidgetGroup.find(String)" is null
	at scheme.ui.HudFragment.lambda$updateBlocks$84(HudFragment.java:303)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
```

### Steps to reproduce

destroying the enemy core on salt flats

### Mods used

AutoDrill and SchemeSize, both from mod browser

### Save file

[mindustry_game_data.zip](https://github.com/Anuken/Mindustry/files/13597525/mindustry_game_data.zip)
as said before, campaign salt flats

### (Crash) logs

[crash_logs.txt](https://github.com/Anuken/Mindustry/files/13597530/crash_logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JojoFR1** [comment]
The crash come from the mod `Scheme-size`. Disable it or report the issue to them. Anuke can't do anything

**Comment by Anuken** [comment]
> depends, this is probably caused by the mod, but there could be some missing validation (null checks) in mindustry

No. The line that crashes is from scheme-size.
