### ISSUE TITLE
Naval units pathfinder bug

### ISSUE THREAD

**Issue by Ddobavka** [Anuken/Mindustry#9366]
### Platforms

Android

### Build

146

### Issue

For some reason, naval units often, instead of looking for a clear path to the core and sailing along it, simply run into a wall. This makes it quite difficult to create maps with water units

### Steps to reproduce

 I made a very curved path from the water units' spawn point to the core, which caused a problem for the units.
![Screenshot_2023-12-09-19-57-24-91_13f989b68d7412e5a177fb13b36ac66f](https://github.com/Anuken/Mindustry/assets/143947391/d94619f3-f43e-4321-851f-873f3ed8c29f)

### Mods used

[PlantPlanet.zip](https://github.com/Anuken/Mindustry/files/13625053/PlantPlanet.zip)

### Save file

[59.zip](https://github.com/Anuken/Mindustry/files/13625099/59.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate issue.
