### ISSUE TITLE
Mass Driver Working Without Power 

### ISSUE THREAD

**Issue by Ariancarlos** [Anuken/Mindustry#9368]
### Platforms

Android

### Build

Version 7 Official 146

### Issue

The Mass Driver, the vanilla one, was receiving items just fine but it wasn't connected to any power whatsoever
![Screenshot_20231209-152018](https://github.com/Anuken/Mindustry/assets/80144245/b54e2a80-2d71-4b49-a0ca-c152a8eacbf5)
![Screenshot_20231209-152034](https://github.com/Anuken/Mindustry/assets/80144245/0c363307-fc03-4c2e-98e5-8b5c8f3d53a1)

### Steps to reproduce

I created two mass drivers, very far from each other, the one was connected to two drills mining thorium and one was close to the core, I let it run for a few seconds and later break a few blocks close to it, one was a power node connected to the receiving Mass Driver, and it kept working just fine without power

### Mods used

I was using 3 mods, one I made for funsies using stuff from the second mod, the second one is Fading Revelations and the other is time control, due to heavy size, the songs I changed on the first mod where removed, but I doubt that's gonna affect anything:

[mods.zip](https://github.com/Anuken/Mindustry/files/13625447/mods.zip)

### Save file

It happened on Serpulo Sector 133, right next to overgrowth:
[sector-serpulo-133.zip](https://github.com/Anuken/Mindustry/files/13625456/sector-serpulo-133.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You don't need power to receive items.
