### ISSUE TITLE
Un-Capturing Tar Fields

### ISSUE THREAD

**Issue by 9Two4** [Anuken/Mindustry#9370]
### Platforms

Android

### Build

Version 7, Build 146

### Issue

After a while of being in Tar Fields, it will suddenly become a hostile sector again, deleting everything built in it.

### Steps to reproduce

Have Tar Fields captured for a while, and then it will become un-captured.

### Save file

[Mindustry Data (924).zip](https://github.com/Anuken/Mindustry/files/13629111/Mindustry.Data.924.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Your sector save was corrupted.
