### ISSUE TITLE
Console memory leaks and lags if large amounts of text are displayed

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry#9373]
### Platforms

Windows

### Build

Latest 588732c856ecfc5a560845381b6a9c0a5d5cf6e5, compiled from source

### Issue

The developer console (F8 console) lags heavily and causes memory leaks if a large amount of text is displayed.

This can happen accidentally, eg by running `Vars.maps.all()` to try to see all the maps, but instead getting 200k characters dumped into the console
or intentionally by running something like "E".repeat(500000).
This causes the console to move very slowly, and also causes hundreds of megabytes of heap size increase. The memory usage does not decrease on GC, even after clearing the console which should clear references to the text.

I think this is because the portion of the text that is offscreen is still being displayed?

Diagnostic information (memory profiled through VisualVM):
![image](https://github.com/Anuken/Mindustry/assets/71201189/d8faab4a-8e67-48ea-9b5e-92579a495642)
It seems to be Object[] and float[] that are leaked.

Could be a separate issue but might be easy to fix at the same time:
The scrolling behavior of multi-line outputs is weird, scrolling down by one line to show the next block causes the entire block to be moved on screen, which might move the screen up by a few, or hundreds of lines.

### Steps to reproduce

Press F8 to open console, then run `Vars.maps.all()`
To increase the size of the memory leak so it's easier to notice, spam it or just wait

### Mods used

None
(I was using AutoDrill, Legacy Textures, and Flarogus Texture but those shouldnt affect the console in any way)

### Save file

Issue is reproducible from main menu
please don't reap my soul

### (Crash) logs

[crash-report-12_12_2023_13_15_00.txt](https://github.com/Anuken/Mindustry/files/13645471/crash-report-12_12_2023_13_15_00.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not interested in fixing this. The console is a very simple implementation that displays lines based on index, not based on height. If you don't want lag, don't spam the console. This is a developer-only feature, I expect users to know how to use it properly.

> even after clearing the console which should clear references to the text.

The text is permanently stored in a list, it's not a memory leak. You can scroll up to see older entries.
