### ISSUE TITLE
avoid showing the stacktrace wherever applicable

### ISSUE THREAD

**Issue by Paladynee** [Anuken/Mindustry#9375]
### Platforms

Windows

### Build

release build 146

### Issue

the end use might not want to see the entire stacktrace when a network issue happens when trying to, for example, look up the mod browser.
instead you can show a custom popup dialog stating that the user has connection issues.
also, if the user has connection issues on the server browser, instead of reporting to the user, it quietly ignores the error and shows no servers.

### Steps to reproduce

Have a faulty internet connection

1 - Go into mod browser
2 - Wait until you see a stacktrace containing either a network error or a foreach(?) failure

### Mods used

inapplicable

### Save file

applicable on the main menu only

### (Crash) logs

no crashes

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This isn't a bug. The stack trace is not shown to the user *unless* they press the details window, and the details window is very important for reporting bugs.

**Comment by Paladynee** [comment]
> also, if the user has connection issues on the server browser, instead of reporting to the user, it quietly ignores the error and shows no servers.

**Comment by Anuken** [comment]
That's also intentional. The server list is fetched when you open the join dialog every time, making a consistent error popup annoying, and there's nothing meaningful the user can do about it anyway. Some older devices can't fetch it at all, and I'd rather just have them not display any error. If they care, they can check their logs.
