### ISSUE TITLE
Server issues.

### ISSUE THREAD

**Issue by kill-john-lennon** [Anuken/Mindustry#9380]
### Platforms

iOS

### Build

Release Build 146.

### Issue

I can't join certain servers on my phone, even when I look them up in the server browser. When I tried going to DDNS servers, the gme kicked me out twice and just didn't show any when I tried refreshing.

### Steps to reproduce

Unknown.

### Mods used

None.

### Save file

I was trying to get on a server when this repeatedly happened.

### (Crash) logs

last log:
[I] [GL] Version: GLES 2.0.0 / Apple Inc. / Apple A13 GPU
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 214748364.7 GB
[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Fragment shader:
WARNING: 0:34: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)
WARNING: 0:43: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Fragment shader:
WARNING: 0:30: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Fragment shader:
WARNING: 0:31: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[I] [Mindustry] Version: 146
[I] [IOSApplication] resumed
[I] Total time to load: 1443ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 67 community servers.
[I] [IOSApplication] paused
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] resumed
[I] [IOSApplication] paused
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] Total computed bounds are w=750.0 h=1334.0 nativeScale=2.0 device=IOSDevice{classifier='IPHONE_SE_2G', machineString='iPhone12,8', ppi=326} statusBarHeight=0.0 rawWidth=375.0 rawHeight=667.0
[I] [IOSApplication] Insets: [0, 0, 0, 0]
[I] [IOSApplication] resumed

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There's no meaningful information here. The problem could be anything relating to the client/server network..
