### ISSUE TITLE
Bug when launching to Ground Zero after game is already in progress

### ISSUE THREAD

**Issue by fallowmar** [Anuken/Mindustry#9384]
### Platforms

Windows

### Build

steam build 146 and under

### Issue

When you launch to Ground Zero on Serpulo after having already completed it, from another tile, you will still get the starting resources dialogue box which I assume is hardcoded into the launch window for GZ. It would be cool if you would be allowed to relaunch to GZ with a resource dialogue from your current tile, like on any other tile. Perhaps you can do a check to see if there are any other active factories on the map, and only display the currently hardcoded resource dialogue when there are no other factories?

If we want to relaunch to GZ using the "new game" resources surely we'd start a new game

### Steps to reproduce

1. Abandon GZ in an active game
2. Move to an active factory to launch from
3. Launch to GZ

### Mods used

none

### Save file

[personal.zip](https://github.com/Anuken/Mindustry/files/13693772/personal.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This isn't a bug. The tutorial will play every time you play the sector.
