### ISSUE TITLE
Erekir campaign level "Peaks" bugged

### ISSUE THREAD

**Issue by a3skales** [Anuken/Mindustry#9386]
### Platforms

Windows

### Build

Steam build 146

### Issue

I am on the level named "Peaks", but I am unable to progress. I see the power lines of the enemy base, but I cannot see any of the buildings, and neither me nor my units can fly past the initial confines the level starts with. The stage prevents you from going too far up, so you can't attack the enemy bases early. If you save and quit before completing ALL the objectives you have before the enemy starts attacking and the bases are accessible, then the next time you enter the sector, the objective will be replaced with "2 Enemy Cores". At this point, even if you get the units that are able to fly over the terrain, you cannot pass the initial confines, and the enemy doesn't attack.

### Steps to reproduce

1. Begin the stage
2. Save and Quit before completing the objectives given at the start
3. Re-enter the sector.
4. The objectives will bug out, saying "2 enemy cores" instead of the objective, and you cannot progress.

### Mods used

Advance Lighting
Exogenesis
Galaxustry
Fading Revelations
New Horizon
Sapphirium
Xenacle

### Save file

I cannot attach my save data as it exceeds the 25 MB file limit. But, this should be easy to replicate on any save that has access to the "Peaks" Erekir sector.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
No save attached, and I cannot reproduce this issue. Likely caused by mods, or you have provided insufficient steps to reproduce.

**Comment by a3skales** [comment]
> No save attached, and I cannot reproduce this issue. Likely caused by mods, or you have provided insufficient steps to reproduce.

I just did some testing, and it seems like it happens when you have more than 5 active mods at once.
