### ISSUE TITLE
Frequent crashing when attempting to join servers

### ISSUE THREAD

**Issue by Comodo17** [Anuken/Mindustry#9387]
### Platforms

iOS

### Build

V146

### Issue

When trying to join servers, the game frequently crashes and closes. When reopening the game, it does not produce a “Mindustry previously crashed” dialogue message. This happens on approximately 1/3 of attempts to join a server. While it could be device-related, this does not happen with any other application. On an iPad Pro with iPad os 17.1.2, with fairly good performance and no other tabs open. Has been happening for some time. Examples:
 https://www.dropbox.com/scl/fi/jrefbo9hp94yu8yanzpbi/screensave_2992.mov?rlkey=a2azyt4z8e58mkkqg2fmqfr5s&dl=0 

https://www.dropbox.com/scl/fi/s04d7d1xte3xosw1gdaqd/screensave_2991.mov?rlkey=mopoy9qr1f2a36t45e7jzxo3o&dl=0

(note this is not me intentionally exiting the app)

### Steps to reproduce

Join and leave servers until crash occurs

### Mods used

None

### (Crash) logs

As far I can tell, it does not seem to add a log to crash logs, here they are anyway:
[logs.txt](https://github.com/Anuken/Mindustry/files/13694817/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Tested on a iOS device simulator, could not reproduce any crashes or issues. This could be server or device specific?

The log doesn't contain any recent crashes, and without those, there is nothing I can do.
