### ISSUE TITLE
Megas' movement continuasly interrupted when moving to mining destination

### ISSUE THREAD

**Issue by maxyvisser** [Anuken/Mindustry#9388]
### Platforms

Linux

### Build

146

### Issue

Video showing the bug:

[cut-3M.webm](https://github.com/Anuken/Mindustry/assets/89139059/45c09362-50b1-4879-9b65-804c5caf101c)

Current behavior: When moving to a new place to mine, the Megas appear to be interrupted almost every second, causing them to move extremely slowly.

Expected behavior: Megas move at regular speed without interruption towards their mining destination, just like how they move to the core when depositing.

The video shows Megas, but the same thing happens with lower tier support air units.

### Steps to reproduce

1. Produce a support air unit
2. Task them with mining

I don't believe I did anything special to cause this bug.

### Save file

[Mindustry.zip](https://github.com/Anuken/Mindustry/files/13695506/Mindustry.zip)

The example video was taken on Tar Fields. The exact same behavior occurred on Overgrowth as well (I'm assuming this bug isn't sector-specific)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue. You may be using a Mindustry build from the wrong commit.
