### ISSUE TITLE
Cannot transfer game data from pc to ios

### ISSUE THREAD

**Issue by Ghazzwaq** [Anuken/Mindustry#9391]
### Platforms

iOS

### Build

146

### Issue

Cannot transfer game data from pc to ios.when I try to do so on my iPhone, the game just crashed

### Steps to reproduce

Game crashed whenever I try to Import game data from pc to iPhone

### Mods used

None

### Save file

[231218.zip](https://github.com/Anuken/Mindustry/files/13697139/231218.zip)

### (Crash) logs

[logs.txt](https://github.com/Anuken/Mindustry/files/13697142/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The log doesn't have the error. Your data may be corrupt, or it may be a large data import bug that has been fixed post-146-release.
