### ISSUE TITLE
"Atlas" Sector Glitch, Stuck in it

### ISSUE THREAD

**Issue by Sharpy2349** [Anuken/Mindustry#9393]
### Platforms

Android

### Build

release build 146.

### Issue

Glitch: When  i completed the atlas mission, it just sent me to another objective(specifically survival) but it says waiting on the wave screen, and i couldnt access other maps that are related to atlas thanks to the atlas being "under attack"
![Screenshot_20231218-103224_Mindustry](https://github.com/Anuken/Mindustry/assets/154108321/47b4141d-d329-426b-955f-085a43525fc9)

### Steps to reproduce

Unknown.

### Mods used

Scheme Size lite

### Save file

[deth.zip](https://github.com/Anuken/Mindustry/files/13699107/deth.zip)

### Submission

- [ ] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
That mod is known to break the campaign. You would need to re-do it without the mod.
