### ISSUE TITLE
Shader loading error for me

### ISSUE THREAD

**Issue by arin-prashar** [Anuken/Mindustry#9394]
### Platforms

Windows

### Build

146

### Issue

When ever I launch the game,The server doesnt load for me so when I opened the console to see whats going on, It showed these error

![Screenshot 2023-12-18 223005](https://github.com/Anuken/Mindustry/assets/112185917/6e42c990-a81a-480d-a82a-6cfcb25a83ae)

### Steps to reproduce

Just launch the game and open console

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Those aren't errors, they are warnings that can safely be ignored. They do not affect the game in any way.

**Comment by arin-prashar** [comment]
OK Thanks for clearing that.
