### ISSUE TITLE
Downloading Mod

### ISSUE THREAD

**Issue by Deadly6666** [Anuken/Mindustry#9396]
### Platforms

Android

### Build

146

### Issue

I'm Downloading Some Mod. I Opened App And My App Crashed Because Mod. My Phone Is Copy A Maybe Error Code "@CS-null". 

### Steps to reproduce

I'm downloading And Restarting App And Crashed 

### Mods used

Maybe All Mod

### Save file

None

### (Crash) logs

@CS-null
[crash log](https://github.com/Anuken/Mindustry/files/13716897/crash.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JojoFR1** [comment]
There's no crash in this log.

**Comment by Anuken** [comment]
Sounds like the mod has some code that crashed your device, which is not a vanilla issue.

**Comment by mahdoosh1** [comment]
> Sounds like the mod has some code that crashed your device, which is not a vanilla issue.

Hey anuke, this happened to me without mods, because my phone just simply does not have enough ram for game to run. Please tell players that game requires more than `512 mb free ram` or `more than 1gb total ram` to be ran smooth and be playable
