### ISSUE TITLE
Shuts down my game

### ISSUE THREAD

**Issue by Cloudy2011** [Anuken/Mindustry#9397]
### Platforms

Android

### Build

146

### Issue

Please take care of it 

### Steps to reproduce

Download a bunch of mods

### Mods used

Don't know 

### Save file

It was the mods the game deleted them and then it started to shut me out of the game

### (Crash) logs

Don't know how to do that

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
No
