### ISSUE TITLE
I can't build a project for arm64 ubuntu

### ISSUE THREAD

**Issue by ArtemS2** [Anuken/Mindustry#9398]
### Platforms

Linux

### Build

146

### Issue

When I try to assemble a project during planning, I find the following error

### Steps to reproduce

![Снимок экрана от 2023-12-22 15-28-28](https://github.com/Anuken/Mindustry/assets/69766464/0931dba7-734e-4ac1-a7f2-2bb9a8038fb9)

### (Crash) logs

[build.log](https://github.com/Anuken/Mindustry/files/13752355/build.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
# arm isnt supported by mindustry

port it yourself if you want

**Comment by camelStyleUser** [comment]
and close this issue

**Comment by camelStyleUser** [comment]
you cant run arc(=>mindustry) on arm linux

**Comment by ArtemS2** [comment]
It is sad
