### ISSUE TITLE
Armored Conveyers visual glitch

### ISSUE THREAD

**Issue by Shawak** [Anuken/Mindustry#940]
**Platform**: *Windows*

**Build**: *99.2*

**Issue**: There is a problem with armored conveyers, they don't connect probably. I guess it's related to the last visual glitch I reported here @Quezler

![image](https://user-images.githubusercontent.com/3829602/67799216-43681600-fa85-11e9-8721-56d6b5bc2c17.png)

**Steps to reproduce**: *Just rebuild the pyratit mixer als shown in the picture, it will output to the conveyer (which is correct) but the conveyer isn't connected to the building visually.*

**Comment by Quezler** [comment]
Hmm, maybe i accidentally broke the part that allows connections from behind to visually blend 🙈
