### ISSUE TITLE
Game doesn't load with certain mods for seeminlgy no reason

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry#9400]
### Platforms

Windows

### Build

build 146

### Issue

I have two friends who's mods will cause the game to not be able to load up for whatever reason. I have checked extensivly through both of their mod's files and it did not seem like there were any crash causing issues. 

### Steps to reproduce

Right now i've only come accross this bug for the fork by "angel0doom" of the "erekir liquefied" mod wich the main branch of currently works perfectly fine and with the "twisted mindustry mod" wich was very recently created by 
anartistry earlier today. Putting any one of these two mods in your mod folder, even with no other mod installed, will cause the game to fail to load when you open it with it just ending up gving you a timeout error.

### Mods used

https://github.com/anartistry/Twisted-Mindustry/tree/main
https://github.com/Angel0doom/Erekir-liquefied

### (Crash) logs

uhhh i checked the crash logs however it seems the game doesn't consider a loading failure a crash, wich would ALSO explain why it doesn't disable all mods after this "crash" wich is more of a loading failure. Please do not remove this issue or at least test it before removing it you have to trust me this is an actual issue.
[crash logs.txt](https://github.com/Anuken/Mindustry/files/13757404/crash.logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
gold.png in Twisted-Mindustry isn't a valid image file, it's a webp, which is not supported by Mindustry. Deleting it fixes the issue.

For whatever reason, attempting to read it makes the image reader freeze the game. The code itself is part of an external native library, so there's no simple fix.

**Comment by Haznobrain** [comment]
oooohhhh ok
