### ISSUE TITLE
Screen turns black after multi-monitor focus switching

### ISSUE THREAD

**Issue by a4404z** [Anuken/Mindustry#9402]
### Platforms

Windows

### Build

steam bulid146 

### Issue

After switching multi-monitor focus, the game goes black and freezes for a few seconds.Text translated by Google, sorry my native language is not English

### Steps to reproduce

main monitor（3840 x 2160，use auto hdr）Secondary monitor（2560×1440 ）
Switch focus to the secondary monitor after launching the game。
The game on the main monitor goes black and returns to normal after a few seconds。
Switch focus to main monitor, main monitor goes black again and returns to normal after a few seconds。
After exiting the game, HDR on the main monitor fails

### Mods used

none

### Save file

none

### (Crash) logs

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Sounds like a system issue. Mindustry doesn't do anything special with regards to monitors, I don't know what "auto HDR" is, and I cannot reproduce issues with this. "HDR failing" *especially* sounds like a system issue.
