### ISSUE TITLE
FDroid version is not cross compatible with other platforms.

### ISSUE THREAD

**Issue by nottisa** [Anuken/Mindustry#9403]
### Platforms

Android

### Build

V146 main and V146 Fdroid

### Issue

The V146 FDroid build cannot join any servers other than FDroid servers. This is because of the version is normally "v. X official" but the build for FDroid is "v. X FDroid". I couldn't find another issue that talks about this, maybe I didn't look hard enough...

### Steps to reproduce

Download the FDroid app version and try to join any official build server.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is a bug in the F-Droid build scripts, which I did not set up and do not maintain. They should *not* be setting the version type as "F-Droid". The issue/PR should be filed on F-Droid.

**Comment by licaon-kter** [comment]
looking at the version name set in https://github.com/Anuken/MindustryBuilds/commit/e399fa1b2334ee29acc556a9c1b5ab3a1f23299e not sure what the issues was 😄  or if it was fixed 🤷
