### ISSUE TITLE
Game doesn't render properly on 2008 iMac

### ISSUE THREAD

**Issue by DethDefier** [Anuken/Mindustry#9406]
### Platforms

Mac

### Build

146

### Issue

Game does not render most essential components when playing on a 2008 iMac with macOS 10.13.6

![Screen Shot 2023-12-24 at 11 01 03 PM](https://github.com/Anuken/Mindustry/assets/93689788/0db9293d-033e-457b-b169-17e78bdc1b36)
^Campaign

![Screen Shot 2023-12-24 at 11 01 19 PM](https://github.com/Anuken/Mindustry/assets/93689788/c561be59-7abe-4608-9c3d-0195d383719d)
^Custom

### Steps to reproduce

-install macOS 10.6 from cd on iMac 8,1
-upgrade to macOS 10.11 with apple upgrade to el capitan app
-upgrade to macOS 10.13 with dosdude1's high sierra patcher
-download mindustry from itch.io
-load into custom game (default settings), in which players,enemies,and materials do not show
OR
-load into campaign, in which nothing (not even the tilemap) shows

### Mods used

n/a

### Save file

[mindustrysave-12-24.zip](https://github.com/Anuken/Mindustry/files/13763780/mindustrysave-12-24.zip)

### (Crash) logs

n/a

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Your graphics drivers are broken, won't fix.

**Comment by DethDefier** [comment]
well thanks ig
I'll look into those
