### ISSUE TITLE
Bugs in campaign serpulo mode (sector 124)

### ISSUE THREAD

**Issue by Gvygex74** [Anuken/Mindustry#9407]
### Platforms

Android

### Build

7-official-146

### Issue

I don't know, why units in wave 2 spawning to many strong units and the difficult is "high". its absolutely real. And that's happen in my android device
![Screenshot_2023-12-25-12-19-30-52_13f989b68d7412e5a177fb13b36ac66f](https://github.com/Anuken/Mindustry/assets/146575426/31f88572-b483-46bc-a5db-7610a8aa8b75)
![Screenshot_2023-12-25-12-20-15-39_13f989b68d7412e5a177fb13b36ac66f](https://github.com/Anuken/Mindustry/assets/146575426/96204f47-a4f8-4e52-a9ca-6133b4a207ce)

### Steps to reproduce

Idk how, it appeared suddenly

### Mods used

No one

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/13764171/invalid.zip)

### (Crash) logs

[(invalid)_1.zip](https://github.com/Anuken/Mindustry/files/13764217/invalid._1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate.
