### ISSUE TITLE
Mod browser not working

### ISSUE THREAD

**Issue by SiroG7** [Anuken/Mindustry#9410]
### Platforms

Android

### Build

146

### Issue

Can't connect to mod browser 
![Screenshot_20231228-015922](https://github.com/Anuken/Mindustry/assets/141429454/38893b24-57be-436f-9d5f-5244cdd38406)

### Steps to reproduce

Open mod browser.

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by yawaflua** [comment]
try again, because error taked from github

**Comment by SiroG7** [comment]
I have tried opening the mod browser about 30 times atleast from 2 devices
, re-installing about 9-10 times and downloaded it from atleast 3 websites
.

If you can give me a solution to my problem, I would really appreciate it.

Thank you.

**Comment by MoHuQwQ** [comment]
(Translation software is used, the meaning may not be accurate)。Hello, friend。
This problem may occur because your network operator is blocking GITHUB's network link。
I am in the Chinese Internet environment is often not normal access (MOD browser)。
You can ask your local network operator for help。

**Comment by yawaflua** [comment]
> (Translation software is used, the meaning may not be accurate)。Hello, friend。 This problem may occur because your network operator is blocking GITHUB's network link。 I am in the Chinese Internet environment is often not normal access (MOD browser)。 You can ask your local network operator for help。

yeap, that could be a problem

**Comment by SiroG7** [comment]
Ok, thank you for the help.
