### ISSUE TITLE
Crash (Oh No)

### ISSUE THREAD

**Issue by ogurhd** [Anuken/Mindustry#9412]
### Platforms

Windows

### Build

12101994

### Issue

The game crashes after entering the Destroyed Shores and the Biomass Research Center

### Steps to reproduce

After I get from any sector there

### Mods used

No

### Save file

[Saveeeeee.zip](https://github.com/Anuken/Mindustry/files/13793536/Saveeeeee.zip)

### (Crash) logs

[crash-report-12_27_2023_19_41_08.txt](https://github.com/Anuken/Mindustry/files/13793527/crash-report-12_27_2023_19_41_08.txt)

[last_log.txt](https://github.com/Anuken/Mindustry/files/13793531/last_log.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
> Mods used:
> No

> Mods: exogenesis:[blue]1.9.1, revision:13.3, uaw:v0.8.3, v-scheme-pack:1.0.0, what-this-may-from:1.2, xelos-pixel-texturepack:0.4.1

**Comment by camelStyleUser** [comment]
the last_log.txt still has 2 mods and a texture pack
