### ISSUE TITLE
Tutorial stops progressing

### ISSUE THREAD

**Issue by EvanSucksAtCode** [Anuken/Mindustry#9417]
### Platforms

Windows

### Build

Steam build 146

### Issue

Unable to progress past in the tutorial. Got to the point where the first enemy spawned. My defenses killed the enemy, but the objective still says "Destroy: 1x Units"

### Steps to reproduce

Play the tutorial

### Mods used

None

### Save file

[Mindustry.zip](https://github.com/Anuken/Mindustry/files/13796895/Mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by vivaan-web** [comment]
I'm sure it's a temporary bug. Have you tried bleeding edge builds on Github to replicate the issue? If so, clear your data by deleting the saved file or removing your app data. I've realized that you used Steam. Try this on the standard GitHub version. I haven't seen this bug despite my many playthroughs. To check if it's a problem with the tutorial system itself or just the specific sector you played, test the tutorial on Erekir. Is the bug still present

**Comment by Anuken** [comment]
There's one unit left in the shadows of the top right; for whatever reason, it didn't attack you. Destroy it to continue.
