### ISSUE TITLE
Crashed on loading into map

### ISSUE THREAD

**Issue by Some7hing0riginal** [Anuken/Mindustry#9419]
### Platforms

Windows

### Build

146

### Issue

Crash

### Steps to reproduce

Was loading into a new map in campaign

### Mods used

None

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/13798837/save.zip)

### (Crash) logs

[hs_err_pid4572.log](https://github.com/Anuken/Mindustry/files/13798839/hs_err_pid4572.log)
[hs_err_pid11832.log](https://github.com/Anuken/Mindustry/files/13798840/hs_err_pid11832.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is a bug in Discord:

![image](https://github.com/Anuken/Mindustry/assets/10100000/5539feb4-b45a-4c59-b627-107a770a2fdf)

Stop streaming in Discord, or disable the DLL injection in Discord settings.
