### ISSUE TITLE
world processor don't have some worldrules

### ISSUE THREAD

**Issue by THEENDS8** [Anuken/Mindustry#9421]
### Platforms

Android

### Build

steam build 146

### Issue

![image](https://github.com/Anuken/Mindustry/assets/155299833/8daa427e-4591-4897-b8bc-729a7eb2c2aa)
![image](https://github.com/Anuken/Mindustry/assets/155299833/c7351ad7-bb96-489b-a97c-a3e82429773b)
it dont have the rule "buildcost"  "banunit" "banbuild" and so on 
especially "buildcost" it has unitcost  but no buildcost!

### Steps to reproduce

open a world processor in map editor

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
how is this a bug(and tbh BE added ban and unban for setrule)

**Comment by camelStyleUser** [comment]
and how in the world do you have a steam build on android

**Comment by JasonP01** [comment]
These arent a bug, you are not in the correct game version for these features

**Comment by Anuken** [comment]
Not a bug.
