### ISSUE TITLE
When load a save the autopause don't work

### ISSUE THREAD

**Issue by Alstin112** [Anuken/Mindustry#9422]
### Platforms

Windows

### Build

146

### Issue

When i use the `load <save>` the games don't start paused.
Maybe this happens with `loadautosave` too, but i didn't tested, i only have seen the code.

### Steps to reproduce

Change the config to autopause on.
Load some save.

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by chuanhhnx** [comment]
Environment is a auto generating events item.
