### ISSUE TITLE
Animated units damage effects

### ISSUE THREAD

**Issue by SaigoN0Nozomi** [Anuken/Mindustry#9424]
### Platforms

Windows

### Build

146

### Issue

Damage effect is showed uncorrect on animated unit parts
![image](https://github.com/Anuken/Mindustry/assets/118016432/c19c3d99-a500-4a6c-8aae-729eb4003ab4)

### Steps to reproduce

take damage as (almost) any animated unit

### Mods used

true vanila

### Save file

visual bug 

### (Crash) logs

visual bug

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Won't fix.
