### ISSUE TITLE
Auto-pause not working when leaving in world load

### ISSUE THREAD

**Issue by Alstin112** [Anuken/Mindustry#9425]
### Platforms

Windows

### Build

146

### Issue

In the server, after the world loads the Groups.player is empty, because of that when player leavers in the world load the player is leaving with Groups.player empty, making the condition to autopause false. 

### Steps to reproduce

1. start a server with autoPause true
3. enters only 1 player in the server
4. write `gameover` on console
5. in the mindustry, while the world is loading, press cancel, leaving the server.

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
fixed
