### ISSUE TITLE
Multiplayer lag spike when core enemy core is destroyed off-screen for host

### ISSUE THREAD

**Issue by Douile** [Anuken/Mindustry#9427]
### Platforms

Linux

### Build

Steam build 146

### Issue

While playing multiplayer with one other steam player connected (on windows) in the erekir campaign whenever the connected player destroyed an enemy core that was off-screen the game would freeze for 2-10 seconds. While I believe some freeze is normal when a core is destroyed for the animation, when the core was on-screen during destruction the freeze was noticeably less: seemingly less than a second.

Game launch options:
`SDL_VIDEODRIVER=x11 %command%`

### Steps to reproduce

1. Launch multiplayer session on Erekir
2. Play any level
3. Have the connected player destroy the enemy core while it is not on screen for the host

### Mods used

None

### Save file

[2024-01-01-22-steam.zip](https://github.com/Anuken/Mindustry/files/13806193/2024-01-01-22-steam.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Unable to reproduce any kind of lag spike under these circumstances.

**Comment by Douile** [comment]
Thanks for checking. I was also unable to reproduce (sorry I should've tried that first) even with simulated network latency. So unless it was todo with steam networking it must've been something external to the game.

**Comment by Anuken** [comment]
I can see weaker devices lagging when a core is destroyed due to the amount of effects and blocks being destroyed, but it should lag *less* off-screen, so this doesn't really add up. Networking also shouldn't affect things.

**Comment by Douile** [comment]
I don't think its related to hardware, I have good PC specs that run the game at a solid 144 FPS, and the FPS remains high during the "freeze". Also are still able to move the mouse around just cannot move or do anything in game.

On further investigation it seems unrelated to the core being off-screen, the freeze still happens when the core is on-screen.

While watching my friends stream while playing it seems that freeze is related to the animation when the core is destroyed: his game played the entire animation of the base exploding while mine was "frozen" (I was the host). The animation of the base exploding never played for me.

I am still un-sure how to reproduce this though, it only seems to happen when I'm playing via steam with this friend.

**Comment by Anuken** [comment]
> While watching my friends stream

On Discord, perhaps? Discord (and potentially other software) injects DLLs into applications to stream them, which, in Mindustry's case, leads to flickering, freezes and crashes, due to bugs in their system (changing OpenGL state).
