### ISSUE TITLE
[Feature Request] Change mech 'Dash' to a toggle on PC

### ISSUE THREAD

**Issue by brandonegbert** [Anuken/Mindustry#943]
Issue: I find myself not wanting to use mechs because 95% of the time I want to be in flying mode (better for building, no collision, faster) so I have to hold down shift all the time.  

Solution: Change the current 'Dash' to a 'transform' that toggles on/off.  Or add 'Transform Toggle' as an additional keybinding.  This would allow swapping between 'building mode' and 'combat mode'.

**Comment by Anuken** [comment]
Feature requests go in #545.
