### ISSUE TITLE
Item resolution

### ISSUE THREAD

**Issue by YmStrip** [Anuken/Mindustry#9430]
### Platforms

Windows

### Build

Version: 146 [Core] Initialized SDL v2.0.20

### Issue

High pixel(256*256) items are wrong in Conveyor Bar speed, sector panel, but mostly normal in others
![a](https://github.com/Anuken/Mindustry/assets/60353148/37b8b10d-1af6-4204-988d-93c44e261fa6)
![b](https://github.com/Anuken/Mindustry/assets/60353148/58625662-1009-4601-b680-548bf7843c54)
![c](https://github.com/Anuken/Mindustry/assets/60353148/94bb1e4e-f4f4-48eb-9be0-fcacdd1bb99f)

### Steps to reproduce

item

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Items **must** be 32x32.
