### ISSUE TITLE
Strange "Mismatched Versions," or "Malformed Input," errors preventing multiplayer that I don't host.

### ISSUE THREAD

**Issue by TACO1221** [Anuken/Mindustry#9431]
### Platforms

Windows

### Build

STEAM build 146

### Issue

It is a bug I've had for about 3 years now and I honestly cannot figure out why specifically my Mindustry doesn't let me play dedicated multiplayer server. I can be casually playing on a heavy-load server just to randomly be kicked out by either "Malformed Input," at a location of heavy projectiles or units or "Mismatched Version," even though I am on the latest one. This issue does not occur in singleplayer or servers I host .

![Screenshot 2024-01-02 214840](https://github.com/Anuken/Mindustry/assets/155403565/1c2707b8-3025-4bd6-8437-b3dc5a2d59a7)

### Steps to reproduce

Seems to occur when the game starts to take a lot of resources and that's really all I know.

### Save file

[SvE_Duo.zip](https://github.com/Anuken/Mindustry/files/13815334/SvE_Duo.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
There isn't much I can do about random network errors like this, unless it can be consistently reproduced in certain scenarios. I've never had this myself on public servers, so I can't help you.

**Comment by TACO1221** [comment]
Alrighty and thank you nonetheless.
