### ISSUE TITLE
Can't unlock the planetary launcher

### ISSUE THREAD

**Issue by Guigui74** [Anuken/Mindustry#9432]
### Platforms

Android

### Build

146

### Issue

Hi, I just finished the campaign and I can't find how to unlock the last item in the technology tree The interplanetary launcher... 

### Steps to reproduce

I dont what whay i did but i can't unlock the planetary launcher

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
# you cant.

expected behaviour
anuke made it so you cant unlock it

**Comment by camelStyleUser** [comment]
P.S.:if you read the first message please close this issue
