### ISSUE TITLE
Units with different items can overstuff storage like bridges

### ISSUE THREAD

**Issue by EggleEgg** [Anuken/Mindustry#9433]
### Platforms

Windows

### Build

146

### Issue

Load 2 flares or units with items (preferably one with under the max item amount of the building), the items must be of different material (like surge and silicon) on each unit. Example: Load 9 items with one of the units on a bridge and any amount of items with the other. The bridge will be loaded with more than 10 items in total

### Steps to reproduce

I even made a schematic to show it

bXNjaAF4nGNgYWBhZmDJS8xNZRDNzEvLzMssSVUoLskvSkxPVahMLC5m4E5JLU4uyiwoyczPY2DMYGDLSUxKzSlmYIqOZWbgz8lPz0zWLSjKT04tLs4vYuBPKspMSU/VTc7PK0utBApwAw3M1S3OLy1KTmVgYGBlAAE+BgZGjoo5UwNPB7UYCPBUT14/w19hSlTR4w1ye34zR0qYSBnNOP7uU+W/mYoNSrvZtxV5hPp/L/EvPXTj3W35JesW5kwxmBFV8mBricyph961rrckgxRkt1U7y05xktLgOtE2PU70uXnn4thXoqGHFGX2hGy9kh8w0TGjZRNHqmtsO9u5C87OdhltD+//mtYn0X751tK3q38cKby+R3VX+5pbkzqnGOZaOEm9jmOaUPdjW7P6hSfz9u8JEM6+sj7H+7ve28o/v7p3f5rtrCVi+iEn2a1uP5/li+0ucyTVJRP2PvogeU5tNpNBlU/Bmqf1teKh7A86bCXr1r6vma0w63m/whXPL2WMtjqKxyIOvat7mnN8krzuv0/pDIwMTAyM7AwQwAjmMqFymRFcIIeBCRiKPAwABOKl6Q==

(Make sure to have copper and lead in core, 2 flares needed)

### Mods used

None

### Save file

[0.zip](https://github.com/Anuken/Mindustry/files/13834571/0.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Item bridges have a separate buffer that holds items in transit, like junctions.
