### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by arin-prashar** [Anuken/Mindustry#9439]
### Platforms

Windows

### Build

7.0-146

### Issue

Game Keeps Crashing mid game,
I was afk for a bit and set my self as poly AI using Scheme Size, When i returned, my game had crashed.
[crash-report-01_07_2024_20_50_08.txt](https://github.com/Anuken/Mindustry/files/13853946/crash-report-01_07_2024_20_50_08.txt)
Its 5th time today it happended

### Steps to reproduce

Dont Know

### Mods used

According to me its not due to any mod

### (Crash) logs

[crash-report-01_07_2024_20_50_08.txt](https://github.com/Anuken/Mindustry/files/13853950/crash-report-01_07_2024_20_50_08.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I don't handle crash reports with mods enabled, especially when the mods are known to cause crashes.
