### ISSUE TITLE
i can't delete/remove the mods i downloaded mods

### ISSUE THREAD

**Issue by mindustry-player** [Anuken/Mindustry#944]
**Platform**: im on windows 10

**Build**: release build 99.1

**Issue**: i cant explain it but all i did was, download the mod, used it, and when i wanted to remove it.. IT DIDN'T! i have no idea what caused it

**Steps to reproduce**: *i don't have a clue, all i did was go in and click the trashcan button above the mod and deleted it (in game) and it just... happened*

**Comment by Anuken** [comment]
Duplicate.

**Comment by mindustry-player** [comment]
Wat?
