### ISSUE TITLE
Everyone crashing in Eradication server.(Specifically in rapid gamemode)

### ISSUE THREAD

**Issue by Ayushkiller** [Anuken/Mindustry#9440]
### Platforms

Windows

### Build

7-relasel-146-

### Issue

Well evryone is crashing here and the owner eradicator or others noone knows how to fix it.

### Steps to reproduce

We dont know he updated the server and stuff started happenig?

### Mods used

Foo client, happens in normal client as well

### Save file

[saves.zip](https://github.com/Anuken/Mindustry/files/13854134/saves.zip)

### (Crash) logs

[crashes.zip](https://github.com/Anuken/Mindustry/files/13854138/crashes.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You have 4 mods *and* are running Foo's client. Don't report bugs for Foo's here.

Additionally, if this is server-specific, it is very likely to be a plugin issue.
