### ISSUE TITLE
Creo que es algo que deben arreglar.

### ISSUE THREAD

**Issue by xXSEBASTIXx** [Anuken/Mindustry#9448]
### Platforms

Android

### Build

146

### Issue

El tema que quiero informar es sobre el Ripple. Creo que no apunta bien y debido a eso los proyectiles caen un poco más atrás, lo que provoca que el daño no sea efectivo y el Ripple no sea una torreta de cómodo uso, al menos sin el uso de silicio como munición. 

### Steps to reproduce

Es simple: la torreta detecta al enemigo y le empieza a disparar, como normalmente es. Pero, el problema cae cuando los proyectiles caen un poco más atrás cuando deberían caer directo en el enemigo.

### Mods used

No he usado mods

### Save file

No es en un sector en específico. Sucede en general de cualquier mapa 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
thats how it shoots, no?

**Comment by xXSEBASTIXx** [comment]
yes, and I need at least two or three ripples for them to be effective and
help the other tricks

**Comment by camelStyleUser** [comment]
dont see a bug here.
it works as advertised in core database
