### ISSUE TITLE
The jump command is not displayed correctly

### ISSUE THREAD

**Issue by Zeleniykustik** [Anuken/Mindustry#9450]
### Platforms

Windows

### Build

146

### Issue

The jump command is incorrectly displayed in the internal IDE for mlog programming. That is, if the number of connections is more than 100 (realized from a small test), then further connections are not displayed. Because of this, when writing code with a size of more than 400, it hinders me a lot. This works on all processors

![i](https://github.com/Anuken/Mindustry/assets/126210243/a65f7cf9-6995-4e9a-b7be-50309a28e27f)
![a](https://github.com/Anuken/Mindustry/assets/126210243/9f59d777-2d97-4aaa-89e5-47d7e3bf7ffb)

### Steps to reproduce

Made 100 connections using the jump command

### Save file

[jump error.zip](https://github.com/Anuken/Mindustry/files/13925101/jump.error.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is an intentional measure to reduce lag, and may be changed in the future.
