### ISSUE TITLE
BUG 5mins after playing on Multiplayer

### ISSUE THREAD

**Issue by Lorence12312** [Anuken/Mindustry#9458]
### Platforms

Windows

### Build

16.0.1 

### Issue

It just crash I don't know the reason why because it's not crashing before around 3 hrs 

### Steps to reproduce

Join multiplayer, played for a while then crash
I rejoin 3 times and it's still the same

### Mods used

no mods

### Save file

[SAD.zip](https://github.com/Anuken/Mindustry/files/13954477/SAD.zip)

### (Crash) logs

[crash-report-01_17_2024_02_21_54.txt](https://github.com/Anuken/Mindustry/files/13954440/crash-report-01_17_2024_02_21_54.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is almost certainly caused by the server itself, try a different one. There is not enough information about what server it is (or what plugins it runs), so I can't help you.
