### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by tdpo2** [Anuken/Mindustry#9462]
### Platforms

Linux

### Build

Latest

### Issue

I'd like to donate you some fiat money for your game. But Valve is supporting scam business. Itch.io has no such payment option. 
So GOG is currently the only option for me. Altought they support scams as well. But at least they allow us to run games without invasive and unnecessary spyware(launcher).

### Steps to reproduce

I'd like to donate you some fiat money for your game. But Valve is supporting scam business. Itch.io has no such payment option. 
So GOG is currently the only option for me. Altought they support scams as well. But at least they allow us to run games without invasive and unnecessary spyware(launcher).

### Mods used

All.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
itch.io has no payment option when the predownload screen shows you would you like to donate x dollars to dev

**Comment by tdpo2** [comment]
I know I can download it for free from there. But I'd like to donate anyway. But I can't because Itch.io doesn't support payment option I can only use.

**Comment by GlennFolker** [comment]
> But Valve is supporting scam business.

If you want to support Anuke, you shouldn't even care about this sketchy reasoning without further elaboration.

**Comment by tdpo2** [comment]
Valve gets a cut out of any sale. They will do nothing to prevent scams on their steam store. Gambling 4 kids(FIFA ultimate packs)... DLC on the disk. "expansions," "season pass" etc.

**Comment by tdpo2** [comment]
Lootboxes.

**Comment by Anuken** [comment]
Thank you for the offer, but currently the only option I have for donating is through itch, which should support several payment methods. If none of those work for you, and you wish to avoid Steam, there aren't any viable options left.

Setting up a GoG listing is quite a lot of work, and since they take the same cut as Steam, I haven't had a compelling reason to make one.
