### ISSUE TITLE
Mindustry вылетает с ошибкой

### ISSUE THREAD

**Issue by FunyValentineD4C** [Anuken/Mindustry#9464]
### Platforms

Windows

### Build

версия 146 с github.io

### Issue

При переходе в новую локацию игра вылетает с ошибкой без кода и с путем краш репорта
проходил с другом и у обоих происходит вылет

### Steps to reproduce

вылет при попытке загрузить любую локацию следующую после Кратеров по ветке прокачки

### Mods used

Betamindy
betamindy music
time control
xelos pixel texturepack

### Save file

github не поддерживает формат сохранений msaw

### (Crash) logs

[crash-report-01_16_2024_20_15_41.txt](https://github.com/Anuken/Mindustry/files/13960793/crash-report-01_16_2024_20_15_41.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I don't fix issues with modded games.
