### ISSUE TITLE
НЕ локализировано

### ISSUE THREAD

**Issue by Bobrus10** [Anuken/Mindustry#9465]
### Platforms

Windows

### Build

steam 146

### Issue

На эрекире не локализирована одна волна, (слева сверху на скрине)

### Steps to reproduce

Я просто играл с друзьям на начальной точке и оно не было переведено

### Save file

![Снимок экрана 2024-01-17 131641](https://github.com/Anuken/Mindustry/assets/156904217/4dd84095-d3e6-4c1f-9b7e-a462c6077e20)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
Reported/fixed https://github.com/Anuken/Mindustry/issues/9438
