### ISSUE TITLE
Multi-liquid ammo turret issue.

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#9469]
### Platforms

Android

### Build

7-official-146

### Issue

Multi-liquid ammo turret clogged, prevent contaners/turret accept new liquid ammo type.

### Steps to reproduce

1. Place many turrets with use 2 or more liquid types as ammo. Place some liquid contaner/tank beside them. Some **liquid junctions**, maybe.
2. Fill container/tank with a liquid that turret accept as ammo.
3. Try to fill container/tank with other liquid ammo.
4. Let them fire.
5. Wait for it! A few 1st liquid type remain, __**not enough for turrets to fire, also block 2nd liquid type enter the container/tank**__.

Details in this save file below.

### Mods used

SVN Test mod. I don't think this is mod issue.

### Save file

(This is `.msav` file type, remove `.zip`)
[Multiliquid ammo turret bug.msav.zip](https://github.com/Anuken/Mindustry/files/13977478/Multiliquid.ammo.turret.bug.msav.zip)

### (Crash) logs

Nah! Not crash issue.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
get more conduits

**Comment by Anuken** [comment]
Use conduits here. Not a bug. This is how liquid distribution works, flow rate depends on how full the block is.
