### ISSUE TITLE
Phase conveyors/bridges autobuild pathfinding incorrect

### ISSUE THREAD

**Issue by O-The-D** [Anuken/Mindustry#9476]
### Platforms

Android

### Build

release build 146

### Issue

All the conveyors autobuild pathfinding works fine (regular, titanium, plastanium etc) but bridges and phase conveyors get built according to power node logic and not conbeyor logic (just watch the vid please it's 3 am for me, the English is not englishing)

https://github.com/Anuken/Mindustry/assets/157182440/76748f76-bd6e-4ab8-9287-d722eaa9147c

P.S. It took me 8 fukkin attempts to nake a video under 10 mb

### Steps to reproduce

Enable conveyor pathfinding
Choose phase conveyor/duct/bridge
Drag

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Turn off diagonal placement. There's no reason to use it with bridges.

This *will* be "fixed", but the "fix" is to essentially make the diagonal placement button not do anything with bridges, so you might as well turn it off.
