### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ziron528** [Anuken/Mindustry#9477]
### Platforms

Android

### Build

146

### Issue

I need 400 tungsten to land in the gorge sector, although it is at the nearest location 

### Steps to reproduce

After passing the "Swamp" sector, the "Gorge" sector opens. I have studied the "Core v2" technology. Now I need 400 tungsten to land in the Gorge, although it cannot be obtained at the nearest location.

### Save file

Does not attach

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Lime712** [comment]
Enter a sector with tungsten, then try launching,

**Comment by Ziron528** [comment]
> Enter a sector with tungsten, then try launching,

I cannot select another sector, as the one closest to the landing point is selected.

**Comment by SITUVNgcd** [comment]
> I cannot select another sector

Why?
1. Select sector with Tungsten.
2. Enter (to play it).
3. Return to Planet Map.
4. Luanch to Gorge.
