### ISSUE TITLE
no mod.json found

### ISSUE THREAD

**Issue by edwinvautier** [Anuken/Mindustry#948]
**Platform**: *Mac*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *When I try to import a mod, I get the error _no mod.json found_. If I unzip the mod, the mod.json is still here.*

**Steps to reproduce**: 

- Download github mod example.
- Modify it.
- Zip it.
- Place it in Downloads so you can find it in Mindustry.
- Import it in Mindustry.

**Comment by Anuken** [comment]
Send me the mod zip.

**Comment by Paulao17** [comment]
You might have file extensions disabled. This would make your `mod.json`'s actual name be `mod.json.txt` or similar. Just a hypothesis.

**Comment by ConstantinHrrmn** [comment]
I have exactly the same issue

**Comment by Anuken** [comment]
![IMG_20191102_111456](https://user-images.githubusercontent.com/10100000/68072987-199f3f80-fd62-11e9-9046-da1d973e8448.png)

@edwinvautier @ConstantinHrrmn  You did not zip up the file correctly. As the guide says, the zip should contain the files themselves, **not** a folder with the files. Now, normally this wouldn't be a large problem, but you also have a macOS folder inside the zip (which is automatically added by Macs). Use a different zipping program or zip the files correctly.

**Comment by edwinvautier** [comment]
@Anuken Thanks for your help it was indeed the way of zipping files that was creating this error.
