### ISSUE TITLE
Poco x3 pro

### ISSUE THREAD

**Issue by Barutcu20** [Anuken/Mindustry#9488]
### Platforms

Android

### Build

Yok 

### Issue

https://github.com/Anuken/Mindustry/assets/157739858/8ca9e2c6-35cc-48de-9313-dbb906e3b697

https://github.com/Anuken/Mindustry/assets/157739858/3491095b-2f54-4f95-83dd-943cae79ed31

Göletçikten kanyona fırlartırken. Tungsten olmadığı gerekçesiyle fırlatma olmuyor. Ala göletçikte tungsten yok.  Oyununuz çok güzel çok severek oynuyorum. Ama bu sorun çok can sıkıcı. Erekiri tamamlayamıyorum. Bana barutcu_genc Instagram hesabından ulaşabilirsiniz. Şimdiden teşekkür ederim. 

### Steps to reproduce

Herhangi birşey yapmadım

### Mods used

Yok. 

### Save file

Uploading Screenrecorder-2024-01-25-21-29-09-966.mp4…

### (Crash) logs

Fırlatma hatası 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
why are you not launching from a different sector

**Comment by camelStyleUser** [comment]
what is the problem in doing that

**Comment by Anuken** [comment]
Launch from a sector with tungsten.
