### ISSUE TITLE
Mindustry will use a huge amount of memory at startup

### ISSUE THREAD

**Issue by ZenXSin** [Anuken/Mindustry#9489]
### Platforms

Windows

### Build

146

### Issue

Mindustry will use a huge amount of memory at startup

### Steps to reproduce

start the mindustry

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
absolute banger of a bug report "there is bug, fix" so much info provided 

Also yes the game uses more memory when starting to load everything at once, this is intended behaviour

**Comment by ZenXSin** [comment]
![IMG_20240126_210639.jpg](https://github.com/Anuken/Mindustry/assets/119043044/fd1f2d2e-621a-4ebd-9b75-a8b0e22b6ac6)

Can I interpret what you mean to mean that it's normal for a game to consume a lot of memory when it starts? But my device only has 8GB of RAM, and MINDUSTRY uses more than 6 GB at startup, which makes my computer nearly crash

**Comment by JasonP01** [comment]
i only have 4gb yet i run the game fine on startup, maybe update your drivers to help?

**Comment by ZenXSin** [comment]
ok，I will try to there. Thank you
