### ISSUE TITLE
Erekir / Basin: lower left core does not count towards nuke trigger

### ISSUE THREAD

**Issue by 00001H** [Anuken/Mindustry#9490]
### Platforms

Windows

### Build

r146

### Issue

If you destroy one core on the top and the bottom left core in Basin, the nuke will not come.

![image](https://github.com/Anuken/Mindustry/assets/50442757/41fa0038-e1fb-4b76-b5fd-286a2c133fe6)
![image](https://github.com/Anuken/Mindustry/assets/50442757/106c2ed8-d965-47d2-8193-5c7abee92bcf)

### Steps to reproduce

- Go to Basin
- Destroy one core on the top
- Go down, remove enough FOW with clerois to place down a turbine condensator and a radar
- Use Payload MDs to send clerois down
- Destroy lower core
-> Does not trigger nuke

### Mods used

N/A

### Save file

[save.zip](https://github.com/Anuken/Mindustry/files/14065669/save.zip)

(Navigate to Erekir / Basin)

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The nuke is only supposed to trigger when the top two cores are destroyed.
