### ISSUE TITLE
HELP ME PLEASE!!!

### ISSUE THREAD

**Issue by mindusters** [Anuken/Mindustry#9497]
### Platforms

Windows

### Build

Steam build 146

### Issue

A crash has occured/ It has been saved in:
С:\Users\urako\AppData\Roaming\Mindustry\crashes\crash-01_27_2024_17_29_32.txt
EOF

### Steps to reproduce

I have a problem, I play with 2 mods and launch the destroyed shores sector and it throws an error

### Mods used

Scheme Size и FactoryDustry - TexturePack

### Save file

[данные.zip](https://github.com/Anuken/Mindustry/files/14072877/default.zip)

### (Crash) logs

[crash-report-01_27_2024_17_29_32.txt](https://github.com/Anuken/Mindustry/files/14072887/crash-report-01_27_2024_17_29_32.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Uninstall/disable your mods and try it again. This is likely caused by them.
