### ISSUE TITLE
The objectives are displayed outside the screen

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry#9508]
### Platforms

Windows

### Build

146

### Issue

the objectives goes outside the screen and can't be reached in any way now.
![Image_1706781392165](https://github.com/Anuken/Mindustry/assets/66559840/5cf3ae17-ae09-4ac5-824a-4c16d7df4fe4)
![Image_1706781433827](https://github.com/Anuken/Mindustry/assets/66559840/09d813a2-566f-4809-96e4-cfc1035cd3d2)

### Steps to reproduce

add many objectives and then delete some of them. and some objectives will be found outside

### Mods used

no mod

### (Crash) logs

no crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by nanmenyangde** [comment]
sorry the save file was missing. here it is.
[[#87ceeb][([#bf92f9]O[#ea8878])].zip](https://github.com/Anuken/Mindustry/files/14123565/87ceeb.bf92f9.O.ea8878.zip)

**Comment by JasonP01** [comment]
Just drag the screen, the only thing that could make these inaccessible is forgetting whete you placed them in the abyss

**Comment by nanmenyangde** [comment]
> Just drag the screen, the only thing that could make these inaccessible is forgetting whete you placed them in the abyss

i know it could be dragged but my farthest objective can't be dragged to reached
they are out of the border

**Comment by JasonP01** [comment]
@Anuken i think they mean the thing to link objectives doesnt move the screen view thing to see new objectives?

**Comment by Anuken** [comment]
That wouldn't be a bug, and doesn't sound like the issue description.

**Comment by nanmenyangde** [comment]
> I can't reproduce the issue; each objective is placed manually, so there's no way for me to put them outside the screen.

@Anuken  a way to reproduce: put enough objectives (for example 15), exit the editor and reenter, you will find the objectives replaced in a row with some of them placed out of the border

**Comment by nanmenyangde** [comment]
![image](https://github.com/Anuken/Mindustry/assets/66559840/3ebd5abe-7723-4860-ab36-de6bd500bc81)
![image](https://github.com/Anuken/Mindustry/assets/66559840/34e36c7c-bffe-4003-80c9-bc47d2ca88bb)
![image](https://github.com/Anuken/Mindustry/assets/66559840/8a1a5da2-cb12-4411-ad2f-81e19171d9dc)

**Comment by Anuken** [comment]
I don't have that problem, even after saving and re-opening the objectives dialog, it stays the same:

![image](https://github.com/Anuken/Mindustry/assets/10100000/25d57424-64f1-46da-9414-bb624f432a81)

**Comment by JasonP01** [comment]
@nanmenyangde is it possible you are referring to that yellow line that goes on forever?
Thats just a visual thing... there isnt an objective at the end of the thing
