### ISSUE TITLE
DisposeEvent is not fired server side

### ISSUE THREAD

**Issue by BalaM314** [Anuken/Mindustry#9511]
### Platforms

Windows

### Build

v146

### Issue

DisposeEvent is not fired serverside
this is probably because it is fired from Renderer for some reason...

## Client
![image](https://github.com/Anuken/Mindustry/assets/71201189/c77aea48-0c11-40d1-8c69-38b3df5a0ae3)

![image](https://github.com/Anuken/Mindustry/assets/71201189/ab5fab6a-3dea-41ef-9fbc-b555f1158cbc)

## Server
![image](https://github.com/Anuken/Mindustry/assets/71201189/2dc7b06e-d3d3-423b-8d70-adedc4c3ff8f)

Mods used: none
Save file: N/A please don't reap my soul

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Yes, DisposeEvent is for disposing of client-side resources/rendering stuff. The server doesn't have any of those, so it doesn't fire. You probably want a ApplicationListener -> dispose() instead.
