### ISSUE TITLE
Missles explode on underBullet buildings

### ISSUE THREAD

**Issue by nanmenyangde** [Anuken/Mindustry#9512]
### Platforms

Windows

### Build

146

### Issue

when missle units fire, their missles would explode on any buildings instead of only their targets. it differs from normal bullets. it leads to that even a few build towers or a evoke could defend a great number of anthicus. 

### Steps to reproduce

1. load the map
2. release the first wave, to see 30 anthicus dealing no damage to only 4 build towers
3. reload the map
4. cut off the power of the build towers
5. release the first wave, and keep using the rebuild function to build the conduits, seeing 30 anthicus dealing no damage

### Save file

[1.zip](https://github.com/Anuken/Mindustry/files/14150070/1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Otamamori917** [comment]
Meep of Faith made something for that #8160

**Comment by nanmenyangde** [comment]
so why didn't this pr be merged that time 💢💢

**Comment by nanmenyangde** [comment]
also, the problem about anthucius, quell and disrupt isn't solved in that pr

**Comment by Otamamori917** [comment]
> so why didn't this pr be merged that time 💢💢

Probably because anuke didn't see it as a problem at the time or anuke simply didn't see the the problem
Tho @Anuken you need to add the thing to other unit missiles since it's auto true and Meep didn't put it in the MissileUnitType as false

**Comment by Anuken** [comment]
That PR doesn't solve the problem, and making it false won't solve the problem either. Disabling underBullet collisions would make certain units *entirely unable* to attack ducts and other such buildings, even if ordered to.

**Comment by Otamamori917** [comment]
> That PR doesn't solve the problem, and making it false won't solve the problem either. Disabling underBullet collisions would make certain units *entirely unable* to attack ducts and other such buildings, even if ordered to.

Ah probably why meep only set it for scathe
