### ISSUE TITLE
Making a schematic with a block that is in a mod and disabling that mod will result in a blank schematic.

### ISSUE THREAD

**Issue by justintimetodosmth** [Anuken/Mindustry#9513]
### Platforms

Windows

### Build

release build 146

### Issue

![image](https://github.com/Anuken/Mindustry/assets/147149265/91fe81f3-8d55-4933-be0e-25960769ab0c)
Playing with (maybe) any mod that has blocks in it and making a schematic with the mod blocks inside of it, and disabling the mod after will result in the schematic showing no blocks (and the info will show it saying "0 blocks") in it and does not do anything when used or placed.

### Steps to reproduce

1. Install any mod that has blocks in it. (The ones I used are Tantros-Test and Resource Supply Mod)
2. Place any mod block and save it in a schematic.
3. Disable the mod.
4. See schematics menu.

### Mods used

The mods I used to reproduce this glitch:
[twcashtantros-test.zip](https://github.com/Anuken/Mindustry/files/14150545/twcashtantros-test.zip)
[lord-gravitywavesinfinite-resources.zip](https://github.com/Anuken/Mindustry/files/14150548/lord-gravitywavesinfinite-resources.zip)

### Save file

Here are the schematics: (in text because .msch is not supported)
bXNjaAF4nGNgZ+BkZmDJS8xNZeAOTs5IzU0syUxWMGTgTkktTi7KLCjJzM9jYGBgy0lMSs0pZmCKjmUAAQCCKA2I
bXNjaAF4nGNgZGBkZmDJS8xNZWApSS0uYeBOSS1OLsosKMnMz2NgYGDLSUxKzSlmYIqOZQABABlQC1E=

(My save file is too big (27MB))

### (Crash) logs

Not a crash.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by LixieWulf** [comment]
What did you expect? The mod is disabled, the blocks in it are unloaded. Of course they don't show up.
Re-enable the mods.

**Comment by justintimetodosmth** [comment]
> What did you expect?

Honestly I thought the schematic will disappear and then reappear if you re-enable the mods.

(I am now starting to regret opening an issue again since the first time)
