### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Trsmywhesrmyyntsnytcyjcmyxh6df** [Anuken/Mindustry#9519]
### Platforms

Android

### Build

Release build 146

### Issue

Im playin normaly and trust me the game AUTOMATICALLY CLOSE

### Steps to reproduce

I open the game enter an Server or An planet and she close automatically

### Mods used

No mods

### Save file

.?

### (Crash) logs

.?

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash logs are required.

**Comment by SITUVNgcd** [comment]
AUTOMATICALLY CLOSE = CRASH => CRASH LOG REQUIRED
