### ISSUE TITLE
Campaign solo Missons seemingly reverting to a lose after closing app and other sectors not gathering resources

### ISSUE THREAD

**Issue by Starshawn13** [Anuken/Mindustry#9521]
### Platforms

Android

### Build

146

### Issue

Missons seemingly reverting to a lose after closing app and other sectors not gathering resources. 
When the app either times out or I close it manually my game doesn't seem to save, even if I save and quit manually. It'll revert back to before I launch the mission yet the resources I use to launch will be gone as well.  

### Steps to reproduce

Start a mission on campaign. Play a few rounds, exit app and close it. Reopen app. Issue has happened many times. 

### Mods used

None. 

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/14174693/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue. Something is corrupting your saves in ways that does not occur on other devices.

**Comment by Starshawn13** [comment]
Interesting.  Any idea what could cause it?

**Comment by Anuken** [comment]
Not really. The game should not touch saves after you get to the menu, so I don't see any reason for corruption to occur. The next release will have potentially better handling of backups, but it doesn't solve or answer the question of why your saves are getting corrupted in the first place. That's not normal.

**Comment by Starshawn13** [comment]
I'll try an Uninstall and reinstall and see if that helps.
Unless it's something to do with the pausing but that wouldn't explain the
lack of resources gathering in the other sectors. It also seems to only be
main mission sectors also like impact 0078 and the nuclear production.
