### ISSUE TITLE
PointLaserBulletType does not work properly on units.

### ISSUE THREAD

**Issue by Haznobrain** [Anuken/Mindustry#9522]
### Platforms

Android

### Build

146

### Issue

This is an issue related to the modding api. When an unit uses the "PointLaserBulletType", the laser will go even outside of the assigned range of the specific weapon, and will be impossible to move from the spot that it was first shot at without stopping shooting beforehand.

### Steps to reproduce

Step 1: create a modded unit in hjson limiting its range and assigning it a weapon using the PointLaserBulletType
step 2: start the game and click anywhere on the map while using the unit, you will see that it will shoot the bullet, wich will go on even out of the range of the weapon.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
It is not supported.
