### ISSUE TITLE
scatter not working

### ISSUE THREAD

**Issue by bhimio1** [Anuken/Mindustry#9524]
### Platforms

Windows

### Build

146

### Issue

when I use the scatter it won't shoot nearby enemies no matter how much amo it has. I have no idea why this is happening because the 

### Steps to reproduce

use a scatter on seruplio

### Mods used

none

### Save file

[save2.zip](https://github.com/Anuken/Mindustry/files/14187351/save2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Scatter is an anti-air turret only.
