### ISSUE TITLE
Math Geometry.d8 incorrect ingame (sorry if this belongs in arc instead)

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9525]
### Platforms

Windows

### Build

146 - custom build

### Issue

When BeamNode.java's `Geometry` values are changed to d8 it is displayed and functions incorrectly ingame
![image](https://github.com/Anuken/Mindustry/assets/131086642/baea45f0-b37f-43e7-9805-614b8b4aaa14)

### Steps to reproduce

Compile [custom branch](https://github.com/JasonP01/Mindustry/tree/diagonal-beam-node) as it already changed or just change the `Geometry.d4[i]` to `Geometry.d8[i]` in BeamNode.java [example](https://github.com/JasonP01/Mindustry/blob/diagonal-beam-node/core/src/mindustry/world/blocks/power/BeamNode.java#L70) (every `Geometry.d4[i]` was changed to 8)

### Mods used

custom build

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
every other value seems to work as intended

**Comment by Anuken** [comment]
If you *change code* and it breaks, the bug is in *your* changes, not the original code. It is up to you to make it work correctly.

**Comment by 00001H** [comment]
@JasonP01 `i` probably only went from 0 to 3. Check the upper bounds of the loop on `i`.

**Comment by JasonP01** [comment]
> @JasonP01 `i` probably only went from 0 to 3. Check the upper bounds of the loop on `i`.

kk, thanks
