### ISSUE TITLE
@solid returning null for all walls

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9528]
### Platforms

Windows

### Build

146 

### Issue

When using `getblock block` to get a wall and then using the same variable in an if statement with `@solid` it returns null, even when a valid block like `@salt-wall` 

(Likely caused by the output being content)

### Steps to reproduce

Place a world proc with the following code linked to a message

```
setblock block @salt-wall 1 1 @derelict 0
getblock block wall 1 1
jump 6 equal wall @solid
print "not"
printflush message1
end
print "wall"
printflush message1
```

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
`@solid` is an alias for the stone wall, I'm not sure why you're using it or comparing it in world logic at all.

**Comment by JasonP01** [comment]
@Anuken 
> `@solid` is an alias for the stone wall, I'm not sure why you're using it or comparing it in world logic at all.

Its to compare walls to non-walls, a server gave players the ability to remove walls, so i thought @solid would just say whether it is a wall or not (like the `isStatic` tag but for logic)

(kinda specific, its for revealing parts of a map automatically, tho players can do it manually)
