### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by cassiopc26** [Anuken/Mindustry#9534]
### Platforms

Android

### Build

146

### Issue

When i turn off my screen, If i turn It on again the game reopens, just like if i had just launched it, the same happens if i close the game without removing from the recent tabs

https://github.com/Anuken/Mindustry/assets/159659927/e91d6cce-a605-4884-9a91-cbf813c5ccc0

### Steps to reproduce

I open the game
Do anything on It
I i close It or turn my screen of after a few seconds the game reopens from zero

### Mods used

It happens even If there are no mods active

### (Crash) logs

I cant upload anything, It just says "invalid"

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash logs are required, and I cannot reproduce the issue.
