### ISSUE TITLE
Mod browser gives an error!!!!!!

### ISSUE THREAD

**Issue by Trumbert** [Anuken/Mindustry#9551]
### Platforms

Android

### Build

v7-official-146 build

### Issue

When I go to the mod browser I get this error 
![Screenshot_2024-02-14-12-49-34-610_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/152685403/c9f13319-9661-47dc-be7c-9889dc3aa74d)

### Steps to reproduce

went to the mod browser 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
As the message says, your device does not support this feature.
