### ISSUE TITLE
Language in trace dialog is always English

### ISSUE THREAD

**Issue by phinner** [Anuken/Mindustry#9552]
### Platforms

Linux

### Build

146 and BE 24789

### Issue

> Initially reported by @JasonP01 on https://github.com/xpdustry/imperium/issues/51

The player language in the admin trace dialog is always English, never the language set by the user or the server.

### Steps to reproduce

1. Create and host a server.
2. Join with a admin player.
3. Join with a regular player with language X that is not English.
4. Trace the regular player and see it won't be language X but English instead.

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
:) thought this was a plugin skill issue ngl

**Comment by Anuken** [comment]
The locale is not synced or sent, so there is no way for this to work correctly. I did not add this feature, it appears to have been incorrectly implemented in a PR - #8990, which will be reverted.

**Comment by Darkness6030** [comment]
@Anuken how about sending locale in trace info?

**Comment by Anuken** [comment]
That would be the correct way to do it, yes.
