### ISSUE TITLE
Import/Export bug

### ISSUE THREAD

**Issue by nikitadan4pi** [Anuken/Mindustry#9558]
### Platforms

Android

### Build

7-official-146

### Issue

When in company you want the import work, you need chek all exporting sectors
If you don't chek it, import willn't work

### Steps to reproduce

setting import/export
kill game
start again
start importing map
see nothing

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Incomplete/unhelpful issue, not filled in.
