### ISSUE TITLE
Crash on iOS during start

### ISSUE THREAD

**Issue by Flipp3rrr** [Anuken/Mindustry#956]
**Platform**: *iPhone 6 running iOS 12.1.2*

**Build**: *I built this myself using gradle, I can't see the build number because it doesn't reach the main menu. It was around 22:00 (UTC+1) when I built this build.*

**Issue**: *The game crashes before the main menu. Full crash log: https://pastebin.com/ZfasAtLH
I was able to retrieve this crash log through CrashReporter, a jailbreak tweak.*

**Steps to reproduce**: *I opened the game on my iPhone 6 running iOS 12.1.2*

**Comment by Anuken** [comment]
I can't fix this, there's no usable indication of what went wrong. As I don't own an iPhone (jailbroken or otherwise), versions you compile yourself are completely unsupported.
