### ISSUE TITLE
Turrets with multi-shots don't stop shooting when destroyed

### ISSUE THREAD

**Issue by SunkyMP3G** [Anuken/Mindustry#9561]
### Platforms

Windows

### Build

146

### Issue

If you destroy the turret with multi-shots while it's shooting, it'll continue shooting
Stopping shooting when the turret is destroyed is enough

Code used:
```
consumeAmmoOnce: false
cooldownTime: 300
recoilTime: 300

shoot: {
    shots: 40
    shotDelay: 4
}
```
![image](https://github.com/Anuken/Mindustry/assets/125795960/35204e99-a1f2-4155-935d-a3304aada640)
![image](https://github.com/Anuken/Mindustry/assets/125795960/03db7f20-1538-4eb1-b93a-702e352ae680)
![image](https://github.com/Anuken/Mindustry/assets/125795960/0f95ef60-35cd-4a19-a2af-c12f6ceca75e)
After 3 seconds
![image](https://github.com/Anuken/Mindustry/assets/125795960/7973bfa8-32c2-4380-bc5e-7f0dd90528c8)
2 turrets
![image](https://github.com/Anuken/Mindustry/assets/125795960/f826aa8e-60a5-414b-9496-5f7e6f8b1d08)

### Steps to reproduce

Place the turret (minigun in this case)
Wait ~5 seconds (because my gun doesn't want to shoot right when it's placed)
Shoot with it
Destroy the turret
Now you can see bullets coming from the void

### Mods used

Netronium. I think this thing happens on every turret with multi-shots
[sunkymp3gnetronium.zip](https://github.com/Anuken/Mindustry/files/14308932/sunkymp3gnetronium.zip)

### Save file

It's an issue with the code, it can happen even with vanilla salvo, if you catch the timing

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
https://github.com/Anuken/Mindustry/assets/44901211/fab289de-3922-48cb-8d73-272b231ac57d

**Comment by Otamamori917** [comment]
This bug is also present in units @Anuken 
From when I remember it was awhile ago so might have to recheck it
