### ISSUE TITLE
Processor illegally writes data to the world cell via unit getBlock

### ISSUE THREAD

**Issue by kJNCwBUq** [Anuken/Mindustry#9566]
### Platforms

Windows

### Build

BE24795

### Issue

processor can use unit getBlock get the world cells and write data

### Steps to reproduce

The world cell obtained by unit getBlock can be read and writte, so just need to enter the coordinates and let the unit pass....

### Save file

[testMsav.zip](https://github.com/Anuken/Mindustry/files/14318491/testMsav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by TheEt1234** [comment]
i thought this was intentional lol

**Comment by bend-n** [comment]
Wait this is a feature!

**Comment by kJNCwBUq** [comment]
> Wait this is a feature!
It can be used on the current server, which can be considered a "hack" for some maps at the moment lol
