### ISSUE TITLE
Logic Parser, Jump to EOF Label failed

### ISSUE THREAD

**Issue by A4-Tacks** [Anuken/Mindustry#9569]
### Platforms

Android

### Build

146

### Issue

**source text**
```
set a 1
jump end always 0 0
set a 2
end:
```

**import to logic**
```
set a 1
jump -1 always 0 0
set a 2
```

**expected**
```
set a 1
jump 0 always 0 0
set a 2
```

### Steps to reproduce

1. copy source text to clipboard
2. open logic editor
3. click import from clipboard
4. click export to clipboard

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Jumps must precede valid lines. A label at the end of a program is not valid.
