### ISSUE TITLE
UI respects Windows display scale(125%) when run from exe, but not jar

### ISSUE THREAD

**Issue by 00001H** [Anuken/Mindustry#9571]
### Platforms

Windows

### Build

BE 24765

### Issue

When the game is directly run from the jar, the UI scale does not respect the Windows display scale settings.

### Steps to reproduce

1. Set display scale to >100%(e.g. 125%) in Windows settings
2. Launch from jar
3. Relaunch from exe
--> See difference

### Mods used

N/A

### Save file

N/A

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Darkness6030** [comment]
This is btw an Arc problem, not only Mindustry
