### ISSUE TITLE
Missing sector names when the actual sector is captured

### ISSUE THREAD

**Issue by summoner001** [Anuken/Mindustry#9591]
### Platforms

Linux

### Build

24811

### Issue

The name of the sector is missing from the notice when the sector is captured successfully.
It just write in the note that the "Sector Captured!", but it should also write the name of the sector according to the bundle.

sector.capture = Sector [accent]{0}[white]Captured! 

Does not replace the sector name in the {0} placeholder.

### Steps to reproduce

Capture a random sector.

### Mods used

I use vanilla Mindustry without mods.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is intentional. The `{0}` is there to display names of sectors you're *not* playing on, in the event that you capture one in the background on Serpulo. Otherwise, it is considered redundant and not displayed.

**Comment by summoner001** [comment]
Could these two be separated?

One would apply to the current sector, and another one that write the name of the sector. Because here in Hungarian we have problems with translation. Because we translate the word "The" in two different ways. Translated as "A" if the following word starts with a consonantand translated as "Az" if the following word begins with a vowel.

For example:
The Origin Sector > Az Origin Sector
The Frozen Forest Sector > A frozen Forest Sector

You can only cheat so much when you don't know what's going to be in the placeholder after the "The" word, then just translate it to A(z) and it's relatively nice. Because then you can follow it with a word beginning with a vowel and a word beginning with a consonant. The reader's brain will decide.

But in this case it doesn't look right when the current sector is captured and it says: A(z) Sector Captured. because "z" will never be needed in this case.

I could suggest to make it a bit nicer, if one would refer to the current sector, for example This sector has been captured. And there would be another text for the case when we are not playing in that sector, we could still use the word "A(z)".
