### ISSUE TITLE
Payload radar or beam node bug

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9592]
### Platforms

Windows

### Build

146

### Issue

When a radar is built next to a payload dropped beam node with power it does not activate until it is updated by either rebuilding it or connecting another node to it | i didnt test this much, so it could be a bug with payload dropping a beam node instead, not providing power until updated

### Steps to reproduce

Payload drop a powered beam node and build a radar next to it (or any other block im not sure) and you will notice it does not expand until connected to another node, or deleted and rebuilt

### Save file

I tested this enough to where it should not be save file specific, tho i will attempt to provide if you cannot reproduce

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
![2024-02-24-23-31-01](https://github.com/Anuken/Mindustry/assets/10100000/56c4ffbb-28f4-4165-af57-3413e4cacf2b)

Cannot reproduce issue, no save provided. Similar results when only one node is used.

**Comment by SITUVNgcd** [comment]
@Anuken It happened to me randomly. I will try to reproduce it and record a video.
This issue is for any blocks that use power.

**Comment by SITUVNgcd** [comment]
@Anuken, @JasonP01
https://github.com/Anuken/Mindustry/assets/44901211/69d64973-d9bb-4a2a-aa30-576a7fa755f1

But as tested on BE build (24795), this bug didn't happen. So this issue already fixed, somehow.
