### ISSUE TITLE
Erekir walls are not increasing health properly using Evoke, Incite and Emanate 

### ISSUE THREAD

**Issue by Galahadagent** [Anuken/Mindustry#9595]
### Platforms

Android

### Build

Release build 146

### Issue

https://github.com/Anuken/Mindustry/assets/161305918/9d6ccecc-7b2c-4517-ba72-691cdcfaeb94
The health recover system wasn't working properly when I was restoring the wall's health by going over it to improve its health as which you can see in this video.

### Steps to reproduce

This bug is only happens  when I tried to recover the walls' health by going over it.(though it happens sometimes and sometime the bug not working idk why.)

### Save file

[map(everywhere if the planet is erekir).zip](https://github.com/Anuken/Mindustry/files/14414774/map.everywhere.if.the.planet.is.erekir.zip)
Not only in the map but also everywhere if the planet is erekir like on erekir mapped servers, erekir sectors.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You're too close to the wall, move away from it.

**Comment by Galahadagent** [comment]
😮 means I never recover walls' health by going over it

**Comment by Galahadagent** [comment]
Ok sorry for distributing you
