### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by andy-bunny** [Anuken/Mindustry#9597]
### Platforms

Windows

### Build

release build 126.2

### Issue

so my issue is when i go to update mindustry to its latest version. i am using a mad called auto updator so that i dont have to remember to update it. it goes to download 69 MB of something and when it does that it finishes with an error (image provided) does any one know a way that i can update it without this error. i dont have acess to the itch.io page to download the latest version right now hence when i am updating it from the verison i have.  

### Steps to reproduce

to reproduce it go to https://github.com/MindustryInside/AutoUpdater and get and install the mod. then from rlease build 126.2 try to update it they way the mod does. 

### Mods used

[https://github.com/MindustryInside/AutoUpdater](url)

### Submission

- [ ] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
where image?

**Comment by andy-bunny** [comment]
for some reason i oculd not attach the image. basicaly it said CreateProcess error=2 The system cannot find the file specified

**Comment by JasonP01** [comment]
why use mod to update from v6 to v7 just download the game again 💀

**Comment by JasonP01** [comment]
Also like number 1 rule is dont make a bug report about mods, literally nothing anuke can do to fix a mod issue

**Comment by andy-bunny** [comment]
i am using this on a school computer and they block the itch.io web page. i actulay had this exe and everyhting in my google drive

**Comment by JasonP01** [comment]
> i am using this on a school computer and they block the itch.io web page. i actulay had this exe and everyhting in my google drive

Anuke cant do anything about v6 💀 bro your version is so old

**Comment by andy-bunny** [comment]
well then what should i do? is there a way to get the newest version with out using the itch io website because I would use that website but I cant so idk

**Comment by JasonP01** [comment]
anyway just install foos client mod, idk (its the only way i know of how to update the game version) (does make ur bug reports invalid since foos is not vanilla)

**Comment by JasonP01** [comment]
bro your literally on github.com

**Comment by JasonP01** [comment]
just download the game from here

**Comment by andy-bunny** [comment]
how do i install that mod

**Comment by andy-bunny** [comment]
i cant install it from here because I don't know how to install a game with out it being a .exe file

**Comment by JasonP01** [comment]
https://github.com/Anuken/Mindustry/releases/latest

**Comment by JasonP01** [comment]
download the .jar and double click it, it should start the game (if not just install something to run a .jar)

**Comment by Anuken** [comment]
If a mod doesn't work, that is an issue with the mod, not the game. I provide no support for other people's code.

**Comment by andy-bunny** [comment]
i would use the jar file but I run into problems. i need Java Runtime Environment or something like  on my computer. when I go to https://www.java.com/en/download/ and downlod the 64 bit one that works but when I go to install it my school blocked it. so I cant install java so I cant open the .jar file so what should I do from here

**Comment by mahdoosh1** [comment]
> i would use the jar file but I run into problems. i need Java Runtime Environment or something like  on my computer. when I go to https://www.java.com/en/download/ and downlod the 64 bit one that works but when I go to install it my school blocked it. so I cant install java so I cant open the .jar file so what should I do from here
> 

1. download the version from here at github
2. rename it to desktop.jar
3. move it to mindustry install folder in a folder called 'jre'
4. if asked to rename or overwrite, press overwrite
5. run mindustry
