### ISSUE TITLE
GPU BUG

### ISSUE THREAD

**Issue by DeadPig99520** [Anuken/Mindustry#9605]
### Platforms

Android

### Build

146

### Issue

 In the server, the GPU will lock the lowest gear to render the game, but not in the single-player archive.

### Steps to reproduce

I always realized that there was a puzzling jam in the server until I found out in the server that if I downloaded the archive to the local area, the number of frames on the server was different from that of the local area, and the local area had an obvious increase in the number of frames, so I discussed this matter with others. I asked him to follow my steps and found this problem, using GPU monitoring software, and my friend's mobile phone and I had already obtained advanced permissions. So we think there is something wrong with the game. These screenshots are my gpu performance in the game. We can see that my gpu can operate normally in the local area and can call high-end and mid-range, while in the server, obviously, the gpu only calls low-end, which is a very bad optimization bug. We use measurement software, which is the scene in China.
test server：mindustry.top
![Screenshot_2024-03-02-16-36-36-643_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161853820/e5c747ee-3a5c-4064-9c12-eb2ef364c1fa)
![Screenshot_2024-03-02-16-36-21-066_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161853820/980377c2-4a10-46dd-97f9-56b7b92bfcc4)
![Screenshot_2024-03-02-16-16-20-527_io anuke mindustry arc2](https://github.com/Anuken/Mindustry/assets/161853820/c6b43cae-787e-4eac-a2ba-b63b34bbbfe0)
![Screenshot_2024-03-02-16-27-44-446_io anuke mindustry arc2](https://github.com/Anuken/Mindustry/assets/161853820/bb636565-9c2b-400a-8bee-76bfa50d83c1)
![Image_1709368630955](https://github.com/Anuken/Mindustry/assets/161853820/3916844e-5136-4c35-a11a-ec1c6a406f02)
![Image_1709368633069](https://github.com/Anuken/Mindustry/assets/161853820/7011d280-b6f6-4d74-9acf-698f430860ae)
Of course, there are screenshots of my friends.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This report isn't well translated, but I assume what you're trying to say is that Mindustry doesn't use 100% of the GPU? This is completely expected - Mindustry is CPU-bound, and most of the logic runs on one CPU core. You're never going to see high GPU utilization unless you're playing on an empty map with vsync off.
