### ISSUE TITLE
Telekinetic Mass Drivrs

### ISSUE THREAD

**Issue by Twcash** [Anuken/Mindustry#9611]
### Platforms

Windows

### Build

146

### Issue

2 by 2 mass drivers telekinetically output at times

### Steps to reproduce

make a 2 by 2 mass driver then when mass driver is facing west or south place a payload conveyor 1 block away from the output

https://github.com/Anuken/Mindustry/assets/131608563/2819a27e-7fd4-4b5c-a3f8-dad7601cb42c

### Mods used

Tantros-test

### Save file

[tkpmds.zip](https://github.com/Anuken/Mindustry/files/14471288/tkpmds.zip)

### (Crash) logs

No crash just a bug

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Twcash** [comment]
Just tested and this works with other payload blocks too
I think payload blocks think they are 3 by 3

https://github.com/Anuken/Mindustry/assets/131608563/900c8b6b-2165-4976-a897-e4c2456407c4

**Comment by Anuken** [comment]
Payload blocks of different sizes (*especially* uneven ones) aren't really supported. Use 3x3.
