### ISSUE TITLE
Game not launching if not connect to the internet.

### ISSUE THREAD

**Issue by dextruax** [Anuken/Mindustry#9618]
### Platforms

Windows

### Build

Steam Build 146

### Issue

When launching the game without an internet connection, nothing happens. Steam says running, however there is nothing in task manager besides a background process called Mindustry, and there isn't even a loading screen. 

### Steps to reproduce

Disconnect PC from the internet and launch the game.

### Mods used

n/a

### Save file

[mindsave.zip](https://github.com/Anuken/Mindustry/files/14473713/mindsave.zip)

### (Crash) logs

no crash logs appear after connecting and relaunching.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Crash logs are required.

**Comment by dextruax** [comment]
@Anuken there are no crash logs created because the game cannot launch

**Comment by Anuken** [comment]
I cannot help you without logs. The issue does not occur on my device. If the game could not launch, you would not see a process for it.

**Comment by SITUVNgcd** [comment]
@dextruax Or atleast `last_log.txt`.

**Comment by mahdoosh1** [comment]
you say there is a background process named Mindustry, so wait until it turns into foreground process. after 2 minutes if it did launch, then there is no issue
