### ISSUE TITLE
Missing texts from the bundle.properties for translation in the settings > controls menu

### ISSUE THREAD

**Issue by summoner001** [Anuken/Mindustry#9622]
### Platforms

Linux

### Build

Bleeding Edge 24829

### Issue

![Képernyőkép 2024-03-04 16-36-48](https://github.com/Anuken/Mindustry/assets/11212632/61fa4479-085c-4c4f-9f48-c791df4da3e4)
![Képernyőkép 2024-03-04 17-07-36](https://github.com/Anuken/Mindustry/assets/11212632/647f8334-97ee-4ff6-9c6b-ac6fcb71ded1)
![Képernyőkép 2024-03-04 17-07-10](https://github.com/Anuken/Mindustry/assets/11212632/ce9ec5e6-19d1-472a-9733-7ec6ab7de5bf)
![Képernyőkép 2024-03-04 17-06-52](https://github.com/Anuken/Mindustry/assets/11212632/77b796e4-16e3-434e-a4f6-1f524632fb74)
![Képernyőkép 2024-03-04 17-06-30](https://github.com/Anuken/Mindustry/assets/11212632/85e66c72-b80f-49ce-81ca-89e61c65be91)
![Képernyőkép 2024-03-04 17-05-59](https://github.com/Anuken/Mindustry/assets/11212632/cfb467b8-7ba5-4561-b2e6-609b7d1035a3)

plus

Left Shift
Left CTRL
Right Shift
Right CTRL

### Steps to reproduce

Take a look at the bundle.properties

### Mods used

I don't use mods only vanilla mindustry

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Keys cannot be translated. I have no plans to change this, currently.
