### ISSUE TITLE
App closes

### ISSUE THREAD

**Issue by M0v0** [Anuken/Mindustry#9623]
### Platforms

Android

### Build

146

### Issue

When I open the app, it ALWAYS closes after a short time and the unsaved progress is gone. After about 5 minutes it always closes and I get a report that the app has an error.

### Steps to reproduce

Open the app?
Idk

### Save file

It happens everywhere -> Main menu too

### (Crash) logs

last log:
[I] [GL] Version: GLES 3.2.0 / ARM / Mali-G57 MC2
[I] [GL] Max texture size: 16383
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 33
[I] [RAM] Available: 256.0 MB
[I] [Mindustry] Version: 146
[I] Total time to load: 2966ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 72 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
sounds like a ram issue

**Comment by Slotterleet** [comment]
256M available RAM... definitely get yourself a new device. Or play in PC instead, that's the option too.

**Comment by M0v0** [comment]
This is a new and good Samsung Galaxy.

**Comment by Anuken** [comment]
There is no crash log attached; that is a normal startup log. I cannot help you.

**Comment by M0v0** [comment]
The text in the crash log field is exactly what was in the crash log.

**Comment by SITUVNgcd** [comment]
> The text in the crash log field is exactly what was in the crash log

That is `last_log.txt` not `crash_log.txt`.

**Comment by Anuken** [comment]
The crash log includes the last log in it - if there is *only* a `last log`, then no crashes were handled the application, meaning the issue is related to native code or memory. I cannot help with that.
