### ISSUE TITLE
这个游戏代码写的太好了，可惜没有中文文档

### ISSUE THREAD

**Issue by houxieyu** [Anuken/Mindustry#963]
**Do not make a new issue for feature requests!** Instead, post it on FeatHub: https://feathub.com/Anuken/Mindustry
被这个游戏震惊了，一个场景里面数万个对象实时计算，性能太强悍了，非常想知道算法怎么设计的，但是看不懂英文介绍和文档，希望能提供中文的代码介绍和分析文档

**Comment by Quezler** [comment]
> Shocked by this game, tens of thousands of objects in a scene are calculated in real time. The performance is too strong. I really want to know how the algorithm is designed, but I can't read the English introduction and documentation. I hope I can write an English code introduction and analysis document.

**Comment by player20033** [comment]
He says this game amazing, a game could contains so many machines and monsters runs without lag, then want to know how the game implement it did that, but he don't understand english, wants the documentation in chinese, about the game and how it implements.

For me, not quite. this game still has lags on big map and sometimes with out of sync the game state on multplayer.

**Comment by Ali-C-Ila** [comment]
看不懂英文還想讀代碼? 老兄你該醒醒了

**Comment by 12358abc** [comment]
看不懂英文还想读代码？丢人丢到国外去了？

**Comment by laohuaji233** [comment]
emmmmm
可以的老哥

**Comment by github-yxb** [comment]
> 看不懂英文还想读代码？丢人丢到国外去了？

你怎么这么贱呢?

**Comment by 12358abc** [comment]
哈哈 你就是不会英文的那个人？

**Comment by 12358abc** [comment]
> > 看不懂英文还想读代码？丢人丢到国外去了？
> 
> 你怎么这么贱呢?

哈哈 你就是不会英文的那个人？

**Comment by github-yxb** [comment]
> > > 看不懂英文还想读代码？丢人丢到国外去了？
> > 
> > 
> > 你怎么这么贱呢?
> 
> 哈哈 你就是不会英文的那个人？

人表达一下对游戏的钦佩，又感叹一下自己不会英语，就丢人到国外？打击一下他就为满足你这无用的虚荣心？？损人不利己 你说你贱不贱？？
