### ISSUE TITLE
Logic Radar command can't detect Erekir core unit

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#9632]
### Platforms

Android

### Build

7-official-146

### Issue

While use Block Radar to retrive player unit, Erekir core units is undetectable, no issue on Serpurlo core units.

This issue cause by `Unit::targetable(Team)` return `false` on https://github.com/Anuken/Mindustry/blob/332d3af893de74e1685e32c8c3014dd13a2299da/core/src/mindustry/logic/LExecutor.java#L846
If player pickup any block, it will return `true`. Wha?

---
See video for details:

https://github.com/Anuken/Mindustry/assets/44901211/c1c49902-65d1-4980-a8c7-13cc25047cf2

Yeah! I known! Mix tech is not recommended. But some time, Erekir map use World processor, and i'm doing this.

### Steps to reproduce

1. Game! With mix tech.
2. Any logic block.
3. Radar player unit.
4. Player from Erekir core.
5. 404 - Not found!

### Mods used

SVN Test mod
Tested with non-modded, same issue.

### Save file

[Logic Radar Erekir core unit bug.zip](https://github.com/Anuken/Mindustry/files/14550987/Logic.Radar.Erekir.core.unit.bug.zip)

### (Crash) logs

No crash here, game logic issue.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I'm not sure what to tell you - erekir core units aren't targetable, for the same reason you can't target them with units. Logic can't detect them.

**Comment by SITUVNgcd** [comment]
Understood! Thanks.

I forgot that Erekir core units can't be targeted (shoting).
