### ISSUE TITLE
Mindustry, Bug whit level

### ISSUE THREAD

**Issue by zaky1122** [Anuken/Mindustry#9634]
### Platforms

Android

### Build

146

### Issue

Hello, I can't continue with playing on planet Erekir. I'm stuck on the Ravine level. The reason is that this level requires tungsten from the Lake map, where it is unfortunately not found. Please ask, thank you in advance. 

### Steps to reproduce

I don't know, I just wanted to go play the next level. 

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Switch to a different sector with tungsten on it, and launch from there.
