### ISSUE TITLE
Erekir sector Basin event bug

### ISSUE THREAD

**Issue by Karl-Markkus** [Anuken/Mindustry#9637]
### Platforms

Windows

### Build

Release build 146

### Issue

I started re-playing the Erekir campaign. I reached Basin sector. This sector has multiple objectives. 1. objective is to destroy the 2 enemy bastion cores which triggers a nuclear launch event. I destroyed only 1 core, then started producing an army of T2 units before destroying the 2. enemy core.

I closed the game after destroying 1 enemy core, and the next day, I continued the mission, but to my dismay, the objective now said: Destroy 5 enemy cores. This means that the nuclear launch cutscene does not happen, and the impenetrable fog of war will not lift, thus soft-locking the player, needing to restart the sector.

![image](https://github.com/Anuken/Mindustry/assets/34920334/2980fcf5-5a10-4e56-b047-cc5bab9d1563)

### Steps to reproduce

1. Start the Basin sector
2. Destroy 1 enemy core
3. Close game
4. Re-open game

### Mods used

https://github.com/64-tesseract/erekir-logic-improved
https://github.com/aureusstratus/exogenesis
https://github.com/yuria-shikibe/newhorizonmod
https://github.com/sk7725/timecontrol

### Save file

[sector-erekir-29.msav.zip](https://github.com/Anuken/Mindustry/files/14564150/sector-erekir-29.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
You have a lot of mods that may very well affect how this map functioned; I will not investigate issues unless they are confirmed to occur in vanilla.
