### ISSUE TITLE
Ravine Ləunching From mistake

### ISSUE THREAD

**Issue by KILE9966** [Anuken/Mindustry#9638]
### Platforms

Android

### Build

7-official-146 

### Issue

Tungsten of the resources needed to enter Ravine But  Lake  which is the launch site, does not.

### Steps to reproduce

Play the game according to the normal process.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This was reported countless times already.
