### ISSUE TITLE
Crash when load zip save 

### ISSUE THREAD

**Issue by GORECKIPL** [Anuken/Mindustry#9640]
### Platforms

Android

### Build

Build 146

### Issue

Po wybraniu pliku zip gra wyłącza się. 

last log:
[I] [GL] Version: GLES 3.2.0 / Samsung Electronics Co., Ltd. / ANGLE (Samsung Xclipse 920) on Vulkan 1.3.231
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 34
[I] [RAM] Available: 256.0 MB
[I] [Mindustry] Version: 146
[I] Total time to load: 1513ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 73 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]

### Steps to reproduce

https://github.com/Anuken/Mindustry/assets/86680035/a0ba2a24-c97f-4a72-8b44-a1a1c9ab2f47

### Save file

[mindustry.zip](https://github.com/Anuken/Mindustry/files/14598122/mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
sounds like an OOM considering the log doesnt contain any exceptions

**Comment by Anuken** [comment]
Crash logs required.
