### ISSUE TITLE
Dependencies are Not Properly Checked For

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#9641]
### Platforms

Windows

### Build

146

### Issue

Mods are staying enabled despite missing dependencies.

### Steps to reproduce

Install Meepscellanious Concepts, Extra Sand Redux, and Black Hole Renderer (mods included in zip), then disable BHR. MC and ESR depend on BHR with `compileOnly` in compilation.

When booting the game up again, the game will crash with a `NoClassDefFoundError`. MC and ESR are still trying to load despite BHR being disabled and having BHR in their dependencies.

If BHR is *deleted* instead of simply being disabled, then it'll properly disable MC and ESR with a missing dependencies error.

### Mods used

[mods used.zip](https://github.com/Anuken/Mindustry/files/14605489/mods.used.zip)

[MEEPofFaith/prog-mats-java](https://github.com/MEEPofFaith/prog-mats-java/tree/turret-reworks-part-2
)
[MEEPofFaith/extra-sand-redux](https://github.com/MEEPofFaith/extra-sand-redux)
[MEEPofFaith/MindustryBlackHoleRenderer](https://github.com/MEEPofFaith/MindustryBlackHoleRenderer/releases/tag/v7)

### Save file

N/A

### (Crash) logs

v146
[crash-report-03_14_2024_09_46_17.txt](https://github.com/Anuken/Mindustry/files/14605578/crash-report-03_14_2024_09_46_17.txt)

---

I did some testing in a custom build where I logged some info in dependency updates.
![image](https://github.com/Anuken/Mindustry/assets/54301439/9c367c8c-3bd0-44e5-a2b4-4f00b5430307)
[last_log.txt](https://github.com/Anuken/Mindustry/files/14605588/last_log.txt)
For some reason, BHR is considered enabled at this point.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Might be fixed with the latest commit, have not tested.

**Comment by MEEPofFaith** [comment]
Just tested, game no longer crashes and properly displays the missing dependency text in the mod browser.
