### ISSUE TITLE
Huawei Honor 10x late 

### ISSUE THREAD

**Issue by Kazbek08** [Anuken/Mindustry#9643]
### Platforms

Android

### Build

Версия 7-fdroid-146 (1070)

### Issue

Не вижу сервера сообщества, хочу к ним подключиться но их просто нет, они у меня не показываются

https://github.com/Anuken/Mindustry/assets/163567730/af4ed77d-67d7-400b-b5ff-6bd13c9ab7f8

### Steps to reproduce

Я не чего не делал я как зашел в сетевую игру так она и была

### Mods used

Модов нету, но потом дней так 1-2 после захвачивание секторов, я скачал файл по именем Last_version_mod_v2_86.apk.
Потом я добавил этот файл ко всем другим файлом "mindustry.anuken" но нечего не поменялось

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
either an internet issue or your isp/firewall is blocking requests to raw.githubusercontent.com

**Comment by Kazbek08** [comment]
Если у меня брандмауэр блокирует запросы к raw.githbusercontent.com, то как сделать так чтобы он не блокировал запрос?  пятница, 15 марта 2024г., 19:51 +03:00 от camelStyleUser  ***@***.*** :

**Comment by Kazbek08** [comment]
If my firewall blocks requests to raw.githbusercontent.com then how do I make it so that it doesn't block the request?  пятница, 15 марта 2024г., 19:51 +03:00 от camelStyleUser  ***@***.*** :

**Comment by mahdoosh1** [comment]
> 
> If my firewall blocks requests to raw.githbusercontent.com then how do I make it so that it doesn't block the request?  пятница, 15 марта 2024г., 19:51 +03:00 от camelStyleUser  ***@***.*** :
> 
> >either an internet issue or your isp/firewall is blocking requests to raw.githubusercontent.com


test it while using a vpn, if it didn't work then report it here
