### ISSUE TITLE
Animated shield bug

### ISSUE THREAD

**Issue by noashie** [Anuken/Mindustry#9645]
### Platforms

Android

### Build

release build 146

### Issue

When an shielded enemy dies or a shielded wall goes of screen, the shield(s) stick to the screen. After building or destroying some thing, the shield vanishes again. For some reason it also canishes when the shield and my ship align at the edg of the map? (only happend when 'animated shields' was turned on)
![Screenshot_20240312_124410_Mindustry](https://github.com/Anuken/Mindustry/assets/163635867/68069294-d597-4ada-9023-3687baca6b31)
![Screenshot_20240313_133054_Mindustry](https://github.com/Anuken/Mindustry/assets/163635867/90ebc7a0-971a-400d-a85c-b541bd1f0934)

### Steps to reproduce

I truned on animated shield and played as usual (trying to beat every wave in sandbox) until i got to the shielded enemys, after the last on dies, it leaves the shield at the spot on the screen where it died.

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Save required.

**Comment by noashie** [comment]
> Save required.

I may need clarification on how to do that on mobile.

**Comment by SITUVNgcd** [comment]
> > Save required.
> 
> I may need clarification on how to do that on mobile.

Save that game > Click on export button > Choise save location.

**Comment by noashie** [comment]
> > > Save required.
> > 
> > I may need clarification on how to do that on mobile.
> 
> Save that game > Click on export button > Choise save location.

And then? Because if I try to insert the file it just tells me that it doesn't support that file type.
