### ISSUE TITLE
Endless heat duplication

### ISSUE THREAD

**Issue by Remenod** [Anuken/Mindustry#9648]
### Platforms

Android

### Build

146

### Issue

When you build a heat router or redirector that is closed to itself, it duplicates the heat. Schematic example: bXNjaAF4nCWLUQ7CIBAFH9CIog0n4UTGD6SbSIKlWTAevy72580kk4cLvMG0xjfBlFpwXaglzlvPdQVwKvFJpUHfHwb+RbEHpiUzpV4ZnooI5xRGIcZtq1/i0OqHE8ndAQpWROBgBmYYJTaJytgD7sAMrQU4q30flPwvdpQfWy4emQ==
![Screenshot_20240317-200947_Mindustry](https://github.com/Anuken/Mindustry/assets/117807650/b2ada376-2f3a-4a4d-b47b-1c9bbdeb19aa)
![Screenshot_20240317-200932_Mindustry](https://github.com/Anuken/Mindustry/assets/117807650/965a2b4c-31fa-46cd-8085-11a929a5b935)
![Screenshot_20240317-202633_Mindustry](https://github.com/Anuken/Mindustry/assets/117807650/029eec9e-63d2-461e-8a6d-132b488c7dbb)

### Steps to reproduce

Build something like this
 bXNjaAF4nCWLUQ7CIBAFH9CIog0n4UTGD6SbSIKlWTAevy72580kk4cLvMG0xjfBlFpwXaglzlvPdQVwKvFJpUHfHwb+RbEHpiUzpV4ZnooI5xRGIcZtq1/i0OqHE8ndAQpWROBgBmYYJTaJytgD7sAMrQU4q30flPwvdpQfWy4emQ==

### Mods used

I checked it works with mods disabled

### Save file

[bug.zip](https://github.com/Anuken/Mindustry/files/14628482/bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Already reported/fixed.
