### ISSUE TITLE
Modding - "Stuck" Mods

### ISSUE THREAD

**Issue by Squidy-Boi** [Anuken/Mindustry#965]
**Platform**: *Windows*

**Build**: *Steam Build 99.4*

**Issue**: *Hello, I'm working on a mod for the game, as many people are but sometimes when I got to load up the mod file there's always an old version of the mod there and I am unable to delete it, at first when I delete it it disappears but then when I go back to the main menu and click the mod tab again it's still there, I've tried everything for reinstalling to clearing game data and deleting the mod from the folder it just doesn't seem to go away, I know that creating this game and maintaining it must be difficult and I may seem like i'm being a little aggressive but I just wanted to let you know so it can get sorted out in the future!*

**Steps to reproduce**: *I was just importing a mod, it crashed I launched the game again and it just stayed there and didn't delete.*

**Comment by Anuken** [comment]
Yet another duplicate.
