### ISSUE TITLE
Text extending off screen (text formatting issue in portrait screen orientation)

### ISSUE THREAD

**Issue by GolfingCentaur** [Anuken/Mindustry#9659]
### Platforms

Android

### Build

146

### Issue

During the tutorial at the beginning of Ground Zero on Serpulo (I haven't touched Erekir, yet), there are several blocks of text that appear consecutively at the start of the players first game. Each block is about 2 to 3 lines of text — except one that is one looooooooooong line of text where the beginning and the ending of the sentence extend beyond the width of the phone screen. I assume it's a small text formatting issue that got missed while the game was being converted from a horizontal desktop screen to a vertical phone screen. (and while this is a bug report for Android, it might be worth double checking to see if the issue is duplicated on the iOS game).

It's at the very start of the game, so you'll be able to find it in less time than it takes to read all this.

### Steps to reproduce

Open freshly downloaded virgin app > Campaign > Serpulid > Ground Zero > tap through the start up tutorial until the text tries to give your phone screen    a    very    wide   bear    hug    > **_tada!_** 🎉

### Mods used

None

### Save file

[looooong_text.zip](https://github.com/Anuken/Mindustry/files/14662364/looooong_text.zip)

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by mahdoosh1** [comment]
screenshots would be very helpful

**Comment by broganeuquoixe** [comment]
Just checked ground zero's markers, all of them don't autoscale… You can just move your unit to see the full text. I wish you a 
>  very wide bear hug 

to you too

**Comment by Anuken** [comment]
I'm not sure which lines you are referring to - the text markers? The hints in the UI? Markers can be viewed by zooming out or panning the camera. Hints don't seem long enough to go off the screen to me, and without screenshots I can't say for certain what the problem is or how to fix it.

**Comment by GolfingCentaur** [comment]
Hello, sorry to get back to this so late.

I'm not talking about the typical hint system, but specifically the *new
user first campaign game tutorial text.* The hint system text is always
flush to the left edge of the screen, no problem with the hints.

The text for the tutorial is center-align in the middle of the screen. Each
successive text block in the tutorial is about ± three lines of text with
maybe 3-5 words per line. Until the one text block which has not been
broken up into separate lines.

To get screenshots I think I would have to clear and restart my campaign
again. Regardless, it should be easy to find.

Start as a *New Player*: Campaign > Serpulo > tap-tap-tap through cute
petite tutorial text, until one of them hugs your screen so hard that you
can neither see the beginning, nor the end of the sentence.

It's just missing a couple soft line breaks. It might even be quicker to
glance at the tutorial text in the game code to see which one's missing the
line breaks.
