### ISSUE TITLE
Items can merge from sources onto bends in armored conveyor belts

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#966]
**Platform**: *Windows*

**Build**: *99*

**Issue**: *If an armored conveyor belt makes a bend any materials from can merge onto the lane. Just look at the picture I don't know if this behavior is intended but I personally don't like it*
![leaking belt](https://user-images.githubusercontent.com/57239116/67992197-1873f280-fc3c-11e9-90c4-a509169fd69a.png)

**Comment by Anuken** [comment]
Not a bug. It's equivalent to this situation:

![image](https://user-images.githubusercontent.com/10100000/67992423-ff0a8080-fc12-11e9-99a8-6e0b50866534.png)

The drill is behind the conveyor, so items get accepted.
Note that the autotiling is probably incorrect because you're using an older build.
