### ISSUE TITLE
Incorrect build number on startup screen

### ISSUE THREAD

**Issue by Mattilego** [Anuken/Mindustry#9670]
### Platforms

Linux

### Build

146

### Issue

The loading screen that appears when starting the game still has the text: "Release 145" even though it is build 146.
![Release 145, Build 146](https://github.com/Anuken/Mindustry/assets/150939590/7539466d-e486-4987-ae99-5eba373f6575)

### Steps to reproduce

Start the game and take a screenshot before it loads the menu.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by broganeuquoixe** [comment]
that *is* a 6
![image](https://github.com/Anuken/Mindustry/assets/161990992/7fd6aff3-c056-48c2-af16-ea220c78c2cd)
the 5 looks like this
![image](https://github.com/Anuken/Mindustry/assets/161990992/149b5b93-af84-4884-beaf-e82cae717028)

**Comment by Anuken** [comment]
Indeed, that's not a 5.

I'm not sure why you're even trying to read that text, considering it's pretty much made to be unreadable, and you only see it for a few seconds. There's the main menu for build info.

**Comment by SITUVNgcd** [comment]
Hehe, you got tricked by TECH font.
