### ISSUE TITLE
Crashes on ios ( quits app whenever i join community servers)

### ISSUE THREAD

**Issue by darchon30704** [Anuken/Mindustry#9677]
### Platforms

iOS

### Build

Build 146

### Issue

Hi!

Sorry but on mobile ios, mindustry crashes on any fish ( community) server. Tried other alex and eviction servers and works, but on fish crashes for some reason.  NO MODS installed.

I tried reinstalling, updating ios, but just quits app whenever i try to join a fish server. Not a problem with other servers for some reason… was there a server update?

Im on phone12promax btw( i know… but the only way i can work and childcare is with my stup phone.)

If it doesnt work on ios now, might be the end of mindustry journey for me 😦

If its an end of a great journey for me on,its been a tremendous honor and i hope to see u in near future!

Otherwise, pls let me know if theres something that can be reasonably fixed!

### Steps to reproduce

Open Mindustry-> join game on server-> crashes game and quits app

### Mods used

No mods.

### (Crash) logs

No crash log. Just quits app on ios.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I can't help fix crashes without a log. The server could be doing something wrong to crash your game, or not. It's impossible to tell.

> No crash log. Just quits app on ios.

A quitting app doesn't mean there isn't a log. Crash logs are required for issues involving crashes (Settings -> Game Data -> Export Crash Logs).
