### ISSUE TITLE
Crashes on ios ( whenever join community server)

### ISSUE THREAD

**Issue by darchon30704** [Anuken/Mindustry#9679]
### Platforms

iOS

### Build

Build 146

### Issue

Hi! Reposting with log

Sorry but on mobile ios, mindustry crashes on any fish ( community) server. Tried other alex and eviction servers and works, but on fish crashes for some reason. NO MODS installed.

I tried reinstalling, updating ios, but just quits app whenever i try to join a fish server. Not a problem with other servers for some reason… was there a server update?

Im on phone12promax btw( i know… but the only way i can work and childcare is with my stup phone.)

If it doesnt work on ios now, might be the end of mindustry journey for me 😦

If its an end of a great journey for me on,its been a tremendous honor and i hope to see u in near future!

Otherwise, pls let me know if theres something that can be reasonably fixed!

### Steps to reproduce

Open Mindustry-> join game on server-> crashes game and quits app

### Mods used

No mods

### (Crash) logs

last log:
[I] [GL] Version: GLES 2.0.0 / Apple Inc. / Apple A14 GPU
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 214748364.7 GB
[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Fragment shader:
WARNING: 0:34: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)
WARNING: 0:43: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Fragment shader:
WARNING: 0:30: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Fragment shader:
WARNING: 0:31: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[I] [Mindustry] Version: 146
[I] [IOSApplication] resumed
[I] Total time to load: 1306ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 75 community servers.
[I] [IOSApplication] paused
[I] [IOSApplication] resumed
[I] [IOSApplication] paused
[I] [IOSApplication] resumed
[I] Attempting to share file mindustry-data-export.zip
[I] Success! Presented mindustry-data-export.zip
[I] Attempting to share file /private/var/mobile/Containers/Data/Application/C3D325C4-9804-4735-AC4A-2578B7A6FD15/Library/local/tmp/logs.txt
[I] Success! Presented /private/var/mobile/Containers/Data/Application/C3D325C4-9804-4735-AC4A-2578B7A6FD15/Library/local/tmp/logs.txt
[I] [IOSApplication] paused
[I] [IOSApplication] Total computed bounds are w=1170.0 h=2532.0 nativeScale=3.0 device=null statusBarHeight=0.0 rawWidth=390.0 rawHeight=844.0
[I] [IOSApplication] Insets: [0, 0, 141, 102]
[I] [IOSApplication] Total computed bounds are w=1170.0 h=2532.0 nativeScale=3.0 device=null statusBarHeight=0.0 rawWidth=390.0 rawHeight=844.0
[I] [IOSApplication] Insets: [0, 0, 141, 102]
[I] [IOSApplication] Total computed bounds are w=1170.0 h=2532.0 nativeScale=3.0 device=null statusBarHeight=0.0 rawWidth=390.0 rawHeight=844.0
[I] [IOSApplication] Insets: [0, 0, 141, 102]
[I] [IOSApplication] Total computed bounds are w=1170.0 h=2532.0 nativeScale=3.0 device=null statusBarHeight=0.0 rawWidth=390.0 rawHeight=844.0
[I] [IOSApplication] Insets: [0, 0, 141, 102]
[I] [IOSApplication] resumed

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by darchon30704** [comment]
Now crashing whenever loading app


last log:
[I] [GL] Version: GLES 2.0.0 / Apple Inc. / Apple A14 GPU
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 214748364.7 GB
[W] Shader shaders/screenspace.vert | shaders/arkycite.frag:
Fragment shader:
WARNING: 0:34: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)
WARNING: 0:43: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Fragment shader:
WARNING: 0:30: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/cryofluid.frag:
Fragment shader:
WARNING: 0:31: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[I] [Mindustry] Version: 146
[I] [IOSApplication] resumed
[I] Total time to load: 1306ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 75 community servers.

**Comment by Anuken** [comment]
The log doesn't seem to contain a crash, and I cannot reproduce any issues when connecting to Fish on an iPhone 8 test device. Consider playing another server?

**Comment by darchon30704** [comment]
Connecting with fish admin for troubleshooting

**Comment by darchon30704** [comment]
Sry, but this ios app crash issue is not just a fish server issue but prevalent on every communnity server. @Anuken

**Comment by Darthscion55** [comment]
Hello, Darthscion here, a Manager of Fish. I just would like to add some information, and see if we can't get this fixed for a valued player who has been with us for a long time. Thank you for any more help you do provide us Anuke, we do appreciate it. 

> The log doesn't seem to contain a crash, and I cannot reproduce any issues when connecting to Fish on an iPhone 8 test device. Consider playing another server?

The log indicates there is and issue that is related the way shaders handle floating point numbers, especially when the values exceed the range that can be represented. 
https://forum.arduino.cc/t/having-trouble-warning-overflow-in-implicit-constant-conversion-woverflow/538875


> on an iPhone 8 test device.
An Iphone 8 is pretty outdated from todays devices, not sure if the error would show up with all the differences.  darchon is using an Iphone 12 Pro running IOS 17.4.1. They said they used to play on fish (im assuming others as well) before with no issues. They have 1,088 joins on the Fish attack server alone, and they are now having issues.

**Comment by Anuken** [comment]
> The log indicates there is and issue that is related the way shaders handle floating point numbers, especially when the values exceed the range that can be represented.
https://forum.arduino.cc/t/having-trouble-warning-overflow-in-implicit-constant-conversion-woverflow/538875

No, it does not. That is a completely unrelated *warning*, not a crash, and occurs on all sorts of devices upon shader compilation. It can be ignored. You're linking to a forum thread *for Arduino*, which is not even in the same ballpark as GLSL shaders.

> An Iphone 8 is pretty outdated from todays devices, not sure if the error would show up with all the differences. 

I am aware, but I have no other physical iOS devices to test on.
