### ISSUE TITLE
Tutorial : Tell the player he has to move at the start

### ISSUE THREAD

**Issue by matheod** [Anuken/Mindustry#968]
**Platform**: Windows

**Build**: 99.4

**Issue**: I launched the game, it told me i have to click on the copper vein. I clicked and it started shooting at it but didn't damage the copper. I was confused at first, and though it was a bug a relaunched the game. Same issue, I though that maybe it wasn't the copper vein and started hovering other tiles of the map to see if it was copper.

Until I though that maybe I have to move ... and was able to continue the tutorial.

The tutorial should precisly tell the player he has to move to mine the copper.

**Comment by Anuken** [comment]
The tutorial already mentions that:

![image](https://user-images.githubusercontent.com/10100000/68041053-15155100-fca6-11e9-8e82-8eb8ed2c08e3.png)

It also mentions that you need to use WASD to move.

**Comment by matheod** [comment]
I checked and it's an issue with the french translation.

I will make a PR to fix it.
