### ISSUE TITLE
Crashes on ios ( whenever join community server) 

### ISSUE THREAD

**Issue by darchon30704** [Anuken/Mindustry#9681]
### Platforms

iOS

### Build

Build 146

### Issue

Hi this is issue with joining any community servers on ios. Whenever i join game, quits app. 

Consulted with server admins and they discussed id it was shader issues, which im not convinced is the source of why game would just crash when joining online server. Please see previous log wirh same issue that i posted.

I contacted fish, eviction, and alex and they commented that this is a core game issue that prevents ios users from playing online.

### Steps to reproduce

Open app-> join game -> quits app.
Open app-> see/unsee community servers -> quits app

The icon on mindustry on iphone appears as some empty app.

My iphone 12 pro is on latest 17.4.1, tried reinstalling mindustry, clearing app cache data and still persists.

### Mods used

NO MODS installed.

### Save file

[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/14781251/mindustry-data-export.zip)

### (Crash) logs

Crash log posted previously. Does not contain apps crash issue.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
[I have already responded to this report](https://github.com/Anuken/Mindustry/issues/9679#issuecomment-2020249454). Please do not open any new issues.

**Comment by SITUVNgcd** [comment]
In all these your bug report, NOT HAVE A SINGLE CRASH LOG. That is last log.
And in this report, you sent a `setting.bin` file in the zip file.
