### ISSUE TITLE
Nova units are slowed down when the first unit attacks

### ISSUE THREAD

**Issue by limonovthesecond2** [Anuken/Mindustry#9686]
### Platforms

Windows

### Build

bleeding-edge build 24880

### Issue

If you order flying Nova-tree units to attack something, all units will change their speed from flight to attack when at least one unit reaches the target. Video: 
https://github.com/Anuken/Mindustry/assets/118817903/40c28e47-dbfe-4dea-92fc-89ec21500f6e

### Steps to reproduce

- Order a group of at least 2 flying Nova-tree units to attack something
- All units are slowed down when the first unit lands

### Save file

[export.zip](https://github.com/Anuken/Mindustry/files/14811355/export.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
Seem like new formation speed in BE version. All units will have speed of slowest unit. I don't know should call it bug or not.

**Comment by limonovthesecond2** [comment]
May be. By the way, Nova's group of flying and walking units move at different speeds. All of them change speed only if there is an order to attack, which is why this issue is opened

**Comment by Anuken** [comment]
Not a bug, units have the speed of the slowest unit. 

At the same time, I'm considering removing that feature altogether, considering it is not always desirable, and adding controls to change it would be too complicated.
