### ISSUE TITLE
Assembler Module

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9707]
### Platforms

Windows

### Build

146

### Issue

The assembler module which needs to exist for an erekir T5 to be built is not possible to have in schematics, this is due to you not being able to have the build plan down without a assembler already placed.

This breaks schematics and in general is just a nuisance to build with as you cant preplan it or have it already there in schematics

### Steps to reproduce

Place a schematic with a assembler module in it, or try and place it when the unit assembler is not fully built yet

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is know, but not a bug. There isn't a way for the assembler to know that you might place an assembler after it.
