### ISSUE TITLE
Exception when trying to update rules

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#971]
**Platform**: *Android/iOS/Mac/Windows/Linux*
`Mac`

**Build**: *The build number under the title in the main menu. Required.*
`custom build (91dc25f6)`

**Issue**: *Explain your issue in detail.*
i tried to edit state rules on the fly, but it does not seem to work.
(not sure if this is intended or not, but i saw that `Call` had a method for it so i gave it a try)

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

compiled a server jar with the following command, and then joined with a client compiled from the same code, then used the command in the console.
![Screen Shot 2019-11-01 at 15 49 28](https://user-images.githubusercontent.com/3179271/68033313-b4930d80-fcbf-11e9-85aa-48c213332584.png)
![Screen Shot 2019-11-01 at 15 50 56](https://user-images.githubusercontent.com/3179271/68033314-b52ba400-fcbf-11e9-8075-e6a7c160b899.png)

**Comment by CA6** [comment]
i have a suggestion to the fly rule thing bud if false get rid of it
