### ISSUE TITLE
Inconsistent Block Info for Erekir

### ISSUE THREAD

**Issue by xXredeem34Xx** [Anuken/Mindustry#9714]
### Platforms

Android

### Build

7.0 Build 146

### Issue

This happens in all version I'm aware of, but officially submitting this for Android. Erekir block info is inconsistent

Payload Loaders and Unloaders:

Despite the Payload Loader info screen not including that it requires power, it still has a power bar and will not function unless it has power. The opposite is also true for the unloader. The unloader info screen says it needs power, and it will use power when provided, however it will function with or without power.

Unit Fabricators: 

The T2 and T3 refabricators tell the player exactly how much of x resource is needed per second, meanwhile the T1 fabricators do not. This means players have to manually calculate how much silicon, graphite, or beryllium each unit fabricator requires a second, however they do not have to for the refabricators. It is inconsistent and should be fixed. If this is labeled as "intentional design," then here are the reasons you should change it.
  - It makes it easier for less experienced players who do not want to sit down and add a calculator to their list of things to play the game, reducing the skill floor and making schem designing more approachable
  - It is much more convenient for all players. The existence of schematics is indicative that quality of life features and convenience is already important to the game
  - It makes significantly more sense to do this and have everything uniform. Anyone who notices the inconsistency will likely chalk it up as a bug or something that was forgotten, rather then seen as intentional design (that's what I did)

After looking into it a little further I noticed the same thing is true with the serpulo unit fabricators. T2, t3, t4 and t5 all give the player the exact amount of resources used/second, but t1 does not. Serpulo is a little different since you can construct multiple units from the same t1 fabricator, so I understand it might be cluttered to add all the info for each individual unit. Perhaps consider adding a drop down menu for each unit or something similar. Even if you decide to leave the serpulo info screen alone, the consistency among all the Erekir info screens should be prioritized over the consistency of all T1 fabricators, as Erekir is its own planet independent of Serpulo tech

### Steps to reproduce

Open any sandbox level and check the block info screens

### Save file

[Erekir_Info_Screen_Inconsistency.zip](https://github.com/Anuken/Mindustry/files/14894927/Erekir_Info_Screen_Inconsistency.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by broganeuquoixe** [comment]
The payload unloader not using power is only true for liquids, unloading power or items requires it

**Comment by xXredeem34Xx** [comment]
Why would that even be a thing? This just strengthens my argument about inconsistency
