### ISSUE TITLE
Cannot complete Aegis normally

### ISSUE THREAD

**Issue by yuhaaonan** [Anuken/Mindustry#9719]
### Platforms

Android

### Build

7-offcial-146

### Issue

cannot broke the shield without cheat

### Steps to reproduce

launch to aegis

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BlueTheCube** [comment]
reload your sector (abandon and replay)
