### ISSUE TITLE
Anuken

### ISSUE THREAD

**Issue by nizamroblox** [Anuken/Mindustry#9720]
### Platforms

Android

### Build

Anuken

### Issue

@Anuken

### Steps to reproduce

Ui

### Mods used

Ii

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
Anuken

**Comment by SITUVNgcd** [comment]
@Anuken

**Comment by camelStyleUser** [comment]
`@Anuken`

**Comment by nizamroblox** [comment]
![noFilter (1)](https://github.com/Anuken/Mindustry/assets/164882258/f7f13a9d-09d4-46d9-a15b-c8b27bf8cded)
You
🏂
@Anuken 
![icon](https://github.com/Anuken/Mindustry/assets/164882258/d202285c-378e-4bb3-8237-54fad3d4fa7c)

**Comment by camelStyleUser** [comment]
`@Anuken` do it

**Comment by TheMrAlbert** [comment]
Sigh...

A disgrace
