### ISSUE TITLE
Unit Cargo Loader Build Cost

### ISSUE THREAD

**Issue by endcr** [Anuken/Mindustry#9726]
### Platforms

Windows

### Build

24908

### Issue

Tested in Caldera, building a unit cargo loader consumes 49 surge alloy, despite block info stating that it costs 50.

### Steps to reproduce

Build a unit cargo loader.

### Mods used

na

### Save file

[caldera.zip](https://github.com/Anuken/Mindustry/files/14904608/caldera.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by broganeuquoixe** [comment]
almost all blocks of the game are affected by this, try for example running `Vars.player.team().core().items.clear(); Blocks.swarmer.requirements.forEach(i=>Vars.player.team().core().items.set(i.item,i.amount))` and then building a swarmer. It won't get built until you get 1 more silicon and then it will use 1 graphite, 1 titanium and 1 plastanium but not the silicon to complete the building process
