### ISSUE TITLE
Invalid LOC Header... Can't import Data game

### ISSUE THREAD

**Issue by Miyaguisensei** [Anuken/Mindustry#9727]
### Platforms

Android

### Build

Build 146

### Issue

Can't Import Data game. 
Error: Invalid LOC Header
![Screenshot_20240408_153108_Mindustry](https://github.com/Anuken/Mindustry/assets/38086000/644da4c1-c15e-43dd-bcbe-1e0fe92f3466)
![Screenshot_20240408_153057_Mindustry](https://github.com/Anuken/Mindustry/assets/38086000/8cf4a650-7eb0-49c6-9403-bf3bf09c4af8)

### Steps to reproduce

Reinstall the game

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
The data file is corrupt.

**Comment by Miyaguisensei** [comment]
Sooooo, nothing can be done to extract that zip file, to get only the files
that are need it to run the Campaing??

**Comment by broganeuquoixe** [comment]
Could you send us the zip file please?

**Comment by Miyaguisensei** [comment]
There it is

**Comment by Miyaguisensei** [comment]
https://drive.google.com/file/d/1_M7f-N8rcUpWhqbbPZZAnOBR1LYmWQS0/view?usp=drive_link

**Comment by SITUVNgcd** [comment]
No sharing permision on Google Drive, turn it on on upload to GitHub.

**Comment by Miyaguisensei** [comment]
Alright. Now i have change it. And My bad for missing that detail and
wasting your time like that.

**Comment by broganeuquoixe** [comment]
Yeah sorry… nothing i can do.

**Comment by Miyaguisensei** [comment]
No problem. Appreciate the help.

**Comment by SITUVNgcd** [comment]
Your zip file is damaged/corrupted, game can't extract data from it.
