### ISSUE TITLE
Powered Block Bug

### ISSUE THREAD

**Issue by endcr** [Anuken/Mindustry#9730]
### Platforms

Windows

### Build

v146

### Issue

[This issue](https://github.com/Anuken/Mindustry/issues/9592) basically. I've just experienced this bug, and have experimented further. The problem is, you have to connect power AFTER placing down a block, otherwise, it doesn't seem to trigger.

### Steps to reproduce

1. Pick up a chargeable block. (e.g. unit repair tower)
2. Place it down.
3. Place a node, so that it connects with the repair tower with available power.
4. Tadaa!

### Mods used

na

### Save file

This bug will disappear after saving and reloading.

### (Crash) logs

na

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
I don't see how that's different from the issue already reported, which didn't happen in BE. You seem to be reporting this for v146 - reopen only if you know it still happens in the latest BE.
