### ISSUE TITLE
Various minor issues

### ISSUE THREAD

**Issue by broganeuquoixe** [Anuken/Mindustry#9731]
### Platforms

Windows

### Build

24916

### Issue

- `heatSource` is missing `alwaysUnlocked = true;`
- `heatSource` has item capacity (of 10) (because of [HeatProducer](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/heat/HeatProducer.java)? idk)
- `ventCondenser` has item capacity (of 10) (because of [AttributeCrafter](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/production/AttributeCrafter.java)? idk)
- `unitSelectControl` hint disappears when selecting units just as its name implies but in the [bundles](https://github.com/Anuken/Mindustry/blob/master/core/assets/bundles/bundle.properties#L1902) it explains how to do such thing *and* tells the player to command units to go to a location. Thus i think it'd be better for it to disappear once the players actually issues a movement and not just upon selecting them.
- "ghost" roombas get created upon placing item-filled `plastaniumConveyor`/`surgeConveyor`s payloads (see video in steps to reproduce)
- speaking of payloads, `payloadLoader`s are able to accept seemingly illegal buildings just because they have some sort of item/liquid/power capacity (and for that reason)? makes these blocks unable to leave the loader (some of them shouldn't have been able to enter it in the first place) the list is in the steps to reproduce
- `liquidSource` and `liquidVoid` (the first when configured with neoplasm and the ladder when filled with neoplasm), due to their very big `liquidCapacity` ~(they used to not have it, i don't get this change)~ create 20000 ([BuildingComp.java#L1351](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/entities/comp/BuildingComp.java#L1351) `10000 / (1 * 1) * 2`) neoplasm liquid puddles that take a lot of time to remove and could be used for griefing
- `payloadConveyor` and `reinforcedPayloadConveyor` almost never sync with each other because of their moveTime https://github.com/Anuken/Mindustry-Suggestions/issues/4934

### Steps to reproduce

- heatSource: [Blocks.java#L5786](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java#L5786) play a campaign map without any blocks unlocked and turn `infiniteResources` to true to *not* see it unlocked like the other sources. For the item capacity issue just click [?] or run `Blocks.heatSource.itemCapacity`
![image](https://github.com/Anuken/Mindustry/assets/161990992/0f82e0cd-68e5-458f-a676-4e7814b4577c)
- ventCondenser: [Blocks.java#L2770](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/content/Blocks.java#L2770) press [?] or run `Blocks.ventCondenser.itemCapacity`
![image](https://github.com/Anuken/Mindustry/assets/161990992/4dbd751b-6906-47de-82c6-710b655d4d96)
- unitSelectControl: [HintsFragment.java#L172](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/ui/fragments/HintsFragment.java#L172) have the hint not be done yet and meet the conditions to show it (`isSerpulo() && state.rules.defaultTeam.data().units.size > 3 && !net.active() && !player.dead()`) and follow the hint instructions
- ghost roombas: [I'm not sure if this is the function that gets called](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/world/blocks/payloads/BuildPayload.java#L36)

https://github.com/Anuken/Mindustry/assets/161990992/4e46aa2d-0dda-49c7-b2f6-fc054a906390

- payloadLoader: the ones that shouldn't be allowed in the first place to enter a `payloadLoader` are all the ones with a red source (blast compound or neoplasm). On the right are the ones that should technically work but get stuck for some reason
![image](https://github.com/Anuken/Mindustry/assets/161990992/f6476293-ffe8-4a52-9a29-02d6ab6b6019)

- liquid source: place one down configured with neoplasm and destroy it
- liquid void: put one inside of a payload loader and fill it with neoplasm (~funny how you can do that~) and then pick it up with a unit, place it down and destroy it
- payload conveyors: alternate in a line `payloadConveyor`s and `reinforcedPayloadConveyor`s and put a payload onto it. Otherwise just watch the video in the linked suggestion

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by broganeuquoixe** [comment]
I should mention: this probably isn't the full list of blocks that shouldn't go into the `payloadLoader` but do anyways. The blocks I tested are all the ones accessible by the `payloadSource` by default

**Comment by Anuken** [comment]
`payloadConveyor` and `reinforcedPayloadConveyor`: This is why I did not want to allow mixtech, and I refuse to provide any support for interaction between the two tech trees. Don't use mixtech.

Payload loading: I fundamentally disagree with many of the "invalid" acceptance cases you've shown. Many of those blocks *can* accept items or liquids in some circumstances. Even if that is not the case, the payload loader can't know what *shouldn't* go in without a hardcoded whitelist/blacklist - as long as it has items or liquid storage, the input *might* be able to accept something, so it is allowed in. There's no reason for the player to put, say, a pump into a loader in the first place.

Fundamentally, the problem is that the loader doesn't know what the user's intentions are - what are they trying to load in? When is a block considered full? Is a turret "full" when it can't accept any more coolant, or when it can't accept any more ammo? How about a unit factory? I *can* make the loader guess based on its liquid/item content, but that guess may be incorrect.

**Comment by broganeuquoixe** [comment]
ok! thank you as always
