### ISSUE TITLE
Can't properly import Github version's game data from the Steam version

### ISSUE THREAD

**Issue by IProgramWell** [Anuken/Mindustry#9735]
### Platforms

Linux

### Build

Steam build 146

### Issue

I bought the Steam version and tried to import the game data I exported from a build of the latest Github version (commit Anuken/Mindustry@7f30cd8703f500a619357872a87df1773819b97d at the time of writing this).
Up until this point, I only played on Erekir, and recently completed Caldera. When I imported the data, I saw that my schematics and research tree were imported, but strangely enough, only very few sectors got marked as completed (Only Aegis and Intersect, to be exact), and a few others (Lake, Atlas, and The Onset) are marked as being unlocked.
I'm just wondering why this is.

### Steps to reproduce

1. Download [Java 17](https://www.oracle.com/java/technologies/downloads/#java17) from Oracle
2. Clone the Git repository at the specified commit (Anuken/Mindustry@7f30cd8703f500a619357872a87df1773819b97d)
3. Run `gradlew desktop:dist` with java version 17
4. Launch the jar file from "desktop/build/libs/Mindustry.jar"
5. Go to "Settings" > "Game Data" > "Export Data"
6. Pick location and save
7. Launch the Steam version of the game
8. Go to "Settings" > "Game Data" > "Import Data"
9. Select the same file that was just created
10. Relaunch the game (Steam version)
11. Go to "Play" > "Campaign"

### Mods used

None

### Save file

[MindustrySave.zip](https://github.com/Anuken/Mindustry/files/14959494/MindustrySave.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
the save is made in a new version.why would it work in an old one

**Comment by Anuken** [comment]
>  from a build of the latest Github version

You cannot import data from a newer version of the game into an older version of the game.

**Comment by SITUVNgcd** [comment]
You can't import from new to old.
Try import from Steam 146 to BE. That will works.

**Comment by mahdoosh1** [comment]
> You can't import from new to old.


another way of saying this is:

Mimdustry is not backwards compatible.
