### ISSUE TITLE
Turret inconsistencies 

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9739]
### Platforms

Windows

### Build

146

### Issue

Units can sit on the very edge of turret ranges and drain their ammo taking 0 damage due to the bullet not registering properly.

Breach, disperse and diffuse all suffer from this making campaign being cheesed 10x easier

I have not tested to see if this was fixed in BE, but dont recall seeing a commit made to fix it anyway 

Only breach, diffuse and disperse are effected, every other turret has some element of aoe that kills the unit

### Steps to reproduce

Place a unit directly on the range end (being able to see the turrets range helps), can be done manually or with command mode, on either breach, diffuse or disperse turrets

You will notice that the turrets fire, and the bullet sometimes visually touch the units hitboxes but the unit never dies

### Mods used

Foos was used to view turret ranges and unit hitboxes but behaviour is vanilla

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Save file:

>  THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

![image](https://github.com/Anuken/Mindustry/assets/10100000/7013706f-eded-476e-b312-39f7a16d66c6)
![image](https://github.com/Anuken/Mindustry/assets/10100000/cd8c2a0c-7b18-4bd4-8043-bd2122fb0e23)
![image](https://github.com/Anuken/Mindustry/assets/10100000/ad7b7523-39b8-4e71-8f6d-cb610de8c7f1)

All three turrets tested are able to hit units at the very edge of their range. **This is why I ask for a save.** I do not know which units you were using or what circumstances this was under. I can increase the range slightly and *hope* it fixes the problem, but as I cannot reproduce this in the first place, it can't be tested.

> Foos was used to view turret ranges and unit hitboxes but behaviour is vanilla

How do you know?
