### ISSUE TITLE
Number Lock State is Ignored

### ISSUE THREAD

**Issue by Shadow8472** [Anuken/Mindustry#9740]
### Platforms

Linux

### Build

146

### Issue

Bug affects Windows as well.

I am a left-handed player who rebinds keys for most games I play. I've really enjoyed the Android version for years off and on, but Mindustry desktop is disappointing in the following ways:
- Num-Lock is not respected.
- ~~Num_pad and top row are not distinguished.~~ (Just before posting, I was disappointed to find #4060 and a comment about this being intentional behavior.)

I will note that I've experienced a similar bug in MineTest where num_6 is confused with 6 or right-arrow (depending on number lock status) despite the engine demonstrating an understanding of the difference when a manually written config file specifies the number pad version of a key -- just something to watch out for in case ignoring numLock isn't also a Mindustry design decision.

### Steps to reproduce

1. Rebind a control to the number pad.
2. Toggle Num Lock and repeat step 1 with another control.

### Mods used

None.

### Save file

I _am_ sure this bug has nothing to do with the game itself or with the fact I was hosting multiplayer (with my sister in a Windows client experiencing the same bug), but for three lines of all caps, I can include a fresh map with Ground Zero completed.

[MindustryBugReportSave.zip](https://github.com/Anuken/Mindustry/files/14965197/MindustryBugReportSave.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Frankly, I've never even heard of anyone using numlock before, so I had to look it up to know what it's supposed to do, but it sounds like you want different detected keys when numlock is toggled. This is not supported, and I have no plans to support it - Mindustry gets keyboard input based on scancode only, and scancodes are unaffected by numlock state.

**Comment by Shadow8472** [comment]
Thank you for getting back so quickly. Is there any chance of a future compromise between having the quality of life enhancement most users enjoy while being inclusive of people like me in the left-handed minority? Perhaps an in-game toggle? Can the API handle reversing the quality of life change that makes this version of the game unplayable for me?

**Comment by Anuken** [comment]
I have no plans to do that, sorry.

I'm not going to say that modding API *can't* change this - it's technically possible somehow, I'm sure - but there is no straightforward way to change something so low-level. Your best bet is changing the source code and recompiling the game.
