### ISSUE TITLE
Unit maintenance towers do not work

### ISSUE THREAD

**Issue by median109** [Anuken/Mindustry#9742]
### Platforms

Windows

### Build

steam build 146

### Issue

![屏幕截图 2024-04-13 172727](https://github.com/Anuken/Mindustry/assets/166916068/81ab52ed-9ccf-42af-b0b0-3aa76a7a51bb)
The first time I encountered a bug about the unit maintenance tower was in the battle of Eric, but at that time, the unit maintenance tower had enough power and ozone, and there were units with less health next to it, but it just didn't work. When I tried to reproduce it in sandbox mode, I got another bug like this.

If there are no bugs, try a few more times

### Steps to reproduce

This bug occurs when using "[" to pick up and then use "]" on a unit maintenance tower and putting the unit maintenance tower down
![屏幕截图 2024-04-13 172727](https://github.com/Anuken/Mindustry/assets/166916068/2dff450a-2c09-4277-82d8-f6978b5864bd)

### Mods used

No mods are used

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
This bug already report in:
https://github.com/Anuken/Mindustry/issues/9730
https://github.com/Anuken/Mindustry/issues/9592#issuecomment-1962878489

Fixed in BE build.
