### ISSUE TITLE
mindustry  overgrowth and naval fortress map bug on campagin

### ISSUE THREAD

**Issue by Igor17122** [Anuken/Mindustry#9745]
### Platforms

Android

### Build

146

### Issue

on overgrowth and naval fortress I heave bug where on crux core is enemy spawn that big circle where on survival maps is it and even when I destroy my core and land there again its that same

### Steps to reproduce

I dont know

### Mods used

I didn't have any mods turned on

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by broganeuquoixe** [comment]
save file needed (Settings > Game Data > Export Data)

**Comment by Igor17122** [comment]
how I can send that save file from telephone

**Comment by broganeuquoixe** [comment]
![image](https://github.com/Anuken/Mindustry/assets/161990992/51156203-3483-40b6-856e-f46022f13cd2)

**Comment by Igor17122** [comment]
I'm trying to log in on my phone but I don't get the code sent to my email

**Comment by Anuken** [comment]
Save required.
