### ISSUE TITLE
Mods???? Fix this please.

### ISSUE THREAD

**Issue by Br647** [Anuken/Mindustry#975]
**Platform**: *Android*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *unable to mod*

**Steps to reproduce**: *As I went to access it was not there*

**Comment by Anuken** [comment]
I have no idea what you're trying to say, and you've not even filled out the template.

**Comment by Br647** [comment]
Sorry I tried to fill out the template what I meant was as I went into the
files looking for the area that the guide says to go it did not say
anything,and the directions don't make sense.
