### ISSUE TITLE
Disabled blocks still functioning

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9750]
### Platforms

Windows

### Build

146

### Issue

Assemblers make assembly drones even when disabled (the units die instantly when the assembler is on derelict however), and turbine condensor animation also doesnt stop when disabled (both seen in campaign), as well as power source still providing power even when on derelict team

### Steps to reproduce

Disable a turbine condensor via either logic or placing it on derelict team, spawn power source on derelict team and then place a beam link in line with it (the beam should connect and it will have power), and disable an assembler by logic still spawns the assembly drones, and derelict assemblers spawn the drones but they die instantly 

Derelict beam nodes also still function perfectly fine (as a fix for the beam nodes, force it to not link to anything if disabled)

### Mods used

Visible on a server

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> Derelict beam nodes also still function perfectly fine

As with standard power nodes, disabling is not and will never be supported.
