### ISSUE TITLE
Logic @speed inaccurate

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9767]
### Platforms

Windows

### Build

146

### Issue

Sensor @speed does not take status effects into account, making its speed be inaccurate all the time

### Steps to reproduce

Give yourself overdrive/overclock and use logic to sense your speed

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Save required.
