### ISSUE TITLE
Control keybind issue

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9771]
### Platforms

Windows

### Build

146 || BE 24964

### Issue

When trying to assign an option to escape key it closes the menu instead of assigning the key, as well as the "press any key" dialogue stays open while you are no longer in the controls menu, pressing a key in that instance does not assign a key to anything

found this out by rebinding menu key, i fixed it by resetting it anyway

### Steps to reproduce

Try rebind a key to escape

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by mahdoosh1** [comment]
finally a true issue.
what would you expect to happen when pressing escape?
would you want the game to bind escape key to whatever you clicked on?
or would you want the game to stop trying to bind a key? (making it say "Not bound")
