### ISSUE TITLE
Bitwise operation error

### ISSUE THREAD

**Issue by Zeleniykustik** [Anuken/Mindustry#9781]
### Platforms

Windows

### Build

146

### Issue

For some reason when I want to get a certain bit from a 64 bit number I get the bit multiplied by -1, so it needs to be multiplied by -1 to make the bit normal.

### Steps to reproduce

I was writing code to visualize a 64 bit numbe

### Save file

[Bitwise operation error.zip](https://github.com/Anuken/Mindustry/files/15108276/Bitwise.operation.error.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
ok so you know how signed longs work
