### ISSUE TITLE
Lose connection after the screen is turned off

### ISSUE THREAD

**Issue by adhu2018** [Anuken/Mindustry#9782]
### Platforms

Android

### Build

146

### Issue

Host a server on Android, enter the game on other devices, and if the Android phone screen is off, the other devices will lose connection

### Steps to reproduce

1. Host a server on Android
2. Enter the game on other devices
3. Turn off the phone screen
4. Wait a moment

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
did your phone not kill the process because it can do that

**Comment by camelStyleUser** [comment]
did the game reload

**Comment by adhu2018** [comment]
After opening the screen, the game runs normally and the process is not killed

**Comment by adhu2018** [comment]
[042621.txt](https://github.com/Anuken/Mindustry/files/15131019/042621.txt)

Because there is no useful information in the logs

**Comment by Anuken** [comment]
Mindustry does not run in the background. If the app can't run, clients will time out.
