### ISSUE TITLE
Crash when attempting to change rules in a map

### ISSUE THREAD

**Issue by Novanox4** [Anuken/Mindustry#9787]
### Platforms

Android

### Build

Bleeding Edge 24977

### Issue

When attempting to access the rules section in the map editor, it crashes the game

### Steps to reproduce

1.Make a map
2.Go to map info screen
3:Tap the 'rules' button

### Mods used

Shown in crash log

### Save file

Not applicable

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 24977
OS: Linux xnull (aarch64)
Android API level: 30
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: biotech:0.2, bl-ui-lib:7, mapfilterext:1.7.6b, mapping-utilities:1.6, mindustry-mapping-utilities:0.15, mitour-lib:0.2.1, multi-crafter:1.8, newconsole:1.9, scheme-size:2.7.79, test-utils:65, time-control:0.2

> NullPointer: 'Attempt to invoke virtual method 'arc.scene.ui.layout.Cell arc.scene.ui.layout.Table.check(java.lang.String, arc.func.Boolc)' on a null object reference'
OCustomRulesDialog.check: 440
OCustomRulesDialog.check: 436
CustomRulesDialog.setup: 10
CustomRulesDialog$$ExternalSyntheticLambda18.run: 56
Dialog$5.shown: 2
VisibilityListener.handle: 4
Element.notify: 9
Element.fire: 15
Dialog.show: 4
Dialog.show: 20
Dialog.show: 19
CustomRulesDialog.show: 3
OCustomRulesDialog.show: 68
OMapInfoDialog.lambda$setup$6$OMapInfoDialog: 85
-$$Lambda$OMapInfoDialog$oIxC2WDGcWVjyfGU-P_FIG2VgRw.run: 2
Element.lambda$clicked$2: 0
Element.$r8$lambda$HTGgyzI_sft57MMc4a-IcKQNKts: 0
Events$$ExternalSyntheticLambda0.get: 34
Element$4.clicked: 20
ClickListener.touchUp: 10
InputListener.handle: 11
Scene.touchUp: 20
InputMultiplexer.touchUp: 3
AndroidInput.processEvents: 19
AndroidGraphics.onDrawFrame: 16
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by ApsZoldat** [comment]
Disable mod named Mapping Utilities. This crash is my fault. And also you're using an old version of the mod, you can find the new one in mod browser if you want to have at least **something** on BE

**Comment by camelStyleUser** [comment]
before trying to report something in the mindustry repo always disable mods and try again

**Comment by Novanox4** [comment]
> Disable mod named Mapping Utilities. This crash is my fault. And also you're using an old version of the mod, you can find the new one in mod browser if you want to have at least **something** on BE

Ah, ok
