### ISSUE TITLE
OutOfMemory error

### ISSUE THREAD

**Issue by LeRandom3676** [Anuken/Mindustry#9788]
### Platforms

Android

### Build

146

### Issue

Every time that i try to load a big mod like Exogenesis or New horizons, it crash and says in the logs that is a OutOfMemory problem.

### Steps to reproduce

Open the game, load Exogenesis or New horizons, reload it.

### Mods used

https://github.com/yuria-shikibe/newhorizonmod
https://github.com/aureusstratus/exogenesis

### (Crash) logs

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Linux xnull (armv7l)
Android API level: 27
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: exogenesis:[blue]1.9.1, fos:1.1 beta build-2, fosost:1.0.2, multi-crafter:1.8, new-horizon:0.4.8, revision:13.3, scheme-size:2.7.79, tiered:2, tmi:1.5

> ArcRuntime: 'java.lang.OutOfMemoryError: Failed to allocate a 67108883 byte allocation with 25165824 free bytes and 153MB until OOM, max allowed footprint 65014616, growth limit 201326592'
AssetManager.handleTaskError: 12
AssetManager.update: 6
AssetManager.update: 9
ClientLauncher.update: 7
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
> OutOfMemoryError: 'Failed to allocate a 67108883 byte allocation with 25165824 free bytes and 153MB until OOM, max allowed footprint 65014616, growth limit 201326592'
VMRuntime.newNonMovableArray: -2
DirectByteBuffer$MemoryRef.<init>: 71
ByteBuffer.allocateDirect: 240
PixmapIO$PngReader.read: 3
Pixmap.loadJava: 2
Pixmap.load: 9
Pixmap.<init>: 9
FileTextureData.prepare: 3
TextureData$-CC.$default$getPixmap: 2
FileTextureData.getPixmap: 0
TextureAtlas.lambda$getPixmap$0: 6
TextureAtlas.$r8$lambda$RutyzXs-lN1xd3Y6yEP2vMWz87s: 0
TextureAtlas$$ExternalSyntheticLambda0.get: 2
ObjectMap.get: 2
TextureAtlas.getPixmap: 3
Mods.loadSync: 18
AssetManager$2.loadSync: 1
AssetLoadingTask.handleAsyncLoader: 9
AssetLoadingTask.update: 4
AssetManager.updateTask: 2
AssetManager.update: 5
AssetManager.update: 9
ClientLauncher.update: 7
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Slotterleet** [comment]
Get a better device.

**Comment by mahdoosh1** [comment]
don't load mods

**Comment by camelStyleUser** [comment]
get a better device

**Comment by camelStyleUser** [comment]
it quite literally says "out of memory"

**Comment by Leo-MathGuy** [comment]
That’s Java for you

**Comment by rylid-umil** [comment]
get a better device
