### ISSUE TITLE
L-alt Bug

### ISSUE THREAD

**Issue by lazizjon212** [Anuken/Mindustry#9791]
### Platforms

Windows

### Build

Release build 146

### Issue

Hello anuke or anybody else i found a bug were i press L-Alt and Move My mouse the unit turns to the mouse really fast and when i pressed and wasd key it followed my mouse and when i move my mouse the same thing happens and i can turn really fast so fix this 

### Steps to reproduce

L-alt + Mouse move or L-alt + wasd + mouse move

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Left-alt isn't used anywhere aside from the editor pick tool. Sounds like a mod.

**Comment by JasonP01** [comment]
Very high chance this is foos client, instant turn, l-alt freecam
