### ISSUE TITLE
Thorium in Erekir before you actually unlock it

### ISSUE THREAD

**Issue by whatthel** [Anuken/Mindustry#9793]
### Platforms

Windows

### Build

146

### Issue

You can get thorium by deconstructing base leftovers in the Basin sector of Erekir because there is a Reinforced Vault.

### Steps to reproduce

1. Launch to Basin in Erekir
2. Clear the sector
3. Deconstruct the Reinforced Vault (do not destroy it)

### Mods used

[multicrafter lib](https://github.com/Anuken/Mindustry/files/15143099/liplummulticrafterlib.zip)
[new console](https://github.com/Anuken/Mindustry/files/15143101/mnemotechniciannew-console.zip)
[schematics pack](https://github.com/Anuken/Mindustry/files/15143103/pixecozmindustryschematics.zip)
[time control](https://github.com/Anuken/Mindustry/files/15143105/sk7725timecontrol.zip)
[scheme size](https://github.com/Anuken/Mindustry/files/15143106/xzxADIxzxScheme-Size.zip)

### Save file

[mindustry2.zip](https://github.com/Anuken/Mindustry/files/15143162/mindustry2.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Not a bug.
