### ISSUE TITLE
Mindustry crash when i go online

### ISSUE THREAD

**Issue by GergiiA** [Anuken/Mindustry#9795]
### Platforms

iOS

### Build

146

### Issue

Mindustry crash when i go online or when i press search or if i join server. I can’t upload video to github so here is link to google drive https://drive.google.com/file/d/1WDMfzPh3IH_GUPoaXXP7bXcUkzDS-ADg/view?usp=drivesdk

### Steps to reproduce

On ios go in mindustry and press online then it crashes maybe it is because of language because i cant make this bug happen when on english 

### Mods used

No mods

### Save file

[mindustry-data-export.zip](https://github.com/Anuken/Mindustry/files/15145515/mindustry-data-export.zip)

### (Crash) logs

[logs.txt](https://github.com/Anuken/Mindustry/files/15145518/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
Need crash log, not (last) log.

**Comment by Anuken** [comment]
There is no crash in the log, and I cannot reproduce a crash on my iOS device.
