### ISSUE TITLE
servers and modifications are not working

### ISSUE THREAD

**Issue by kirill97513131** [Anuken/Mindustry#9799]
### Platforms

Android

### Build

7-official-146

### Issue

it does not find a server and it is not possible to download modifications in the application itself only on GitHub

### Steps to reproduce

The problem came by itself

### (Crash) logs

[(invalid).zip](https://github.com/Anuken/Mindustry/files/15178843/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This is an issue with your network.

**Comment by kirill97513131** [comment]
thanks, I turned on the Wi-Fi and everything worked
