### ISSUE TITLE
Multiplayer Invalid Client Id

### ISSUE THREAD

**Issue by s21825** [Anuken/Mindustry#98]
When trying to connect to a multiplayer server I am getting the following error:

An error has occured Invalid Client ID! Submit a bug report.

So I am able to see the server listed in the join game screen but when I select the server I get that message.

The server shows the following:

Recieved connection: 8 / 192.168.0.12. Kryonet ID: 8
Lost kryonet connection 8
Lost connection: 8
Unknown client has disconnected (ID=8)

The client I'm connecting with is an older Android device running Mindustry 3.4 release build 33. Samsung Galaxy Tab 10.1 GT-P7510. Android version 4.0.4.

The server:
version
Version: Mindustry 3.4 release / build 33

Other clients can connect to the server (Android phone, Web version) and I can play the single player game on the problem device without any issue. Just the multiplayer issue described here.

If you need any other info let me know.

**Comment by Anuken** [comment]
Should be fixed as of build 34.

**Comment by s21825** [comment]
Yep! Works great now. Thanks for the sweet game!
