### ISSUE TITLE
Shield fail to absorb the bullet with a high speed

### ISSUE THREAD

**Issue by DSFdsfWxp** [Anuken/Mindustry#9804]
### Platforms

Android

### Build

146

### Issue

If a absorbable bullet enter a unit's shield, normally, it will be absorbed, but if it is too fast or it is spawned too close to the unit, it will hit the unit directly instead of being absorbed. And then it'll finally call `rawDamage(...)` to apply the damage to the unit, in which it only draw shield breaking effect but not apply cool down to the shield if the shield of a entity is broken. Thus if that kind of bullet broke the unit's shield, the shield takes no time to cool down.

### Steps to reproduce

Spawn an enemy oct, place a foreshadow close to it in it's shield. Or you can use other turrets that shot fast bullets. Place it close to or far from the oct and inside or outside the oct's shield to make comparison.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Foreshadow bullets don't move. Shields don't absorb point blank damage.

Saves are **required**.

**Comment by DSFdsfWxp** [comment]
Cyclone with surge alloy and water can also reproduce the problem. Since it could happen everywhere, it is not necessary to provide a save.

**Comment by Anuken** [comment]
The issue template states:

> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.

**Comment by DSFdsfWxp** [comment]
The problem is it make shield taking no time to cool down after being broken.  
Under the oct is a cyclone with surge alloy and water.
[save.zip](https://github.com/Anuken/Mindustry/files/15204107/save.zip)

https://github.com/Anuken/Mindustry/assets/102459686/d3a83092-5cdd-419c-88d8-f723d44ce9e5
