### ISSUE TITLE
Баг в модификациях

### ISSUE THREAD

**Issue by Returi3** [Anuken/Mindustry#9812]
### Platforms

Android

### Build

Версия последняя на это время когда был отправлена эта заявка

### Issue

![Screenshot_20240505_111841_Mindustry](https://github.com/Anuken/Mindustry/assets/168959239/faaef8f5-47d3-41f3-9c36-2329ce60113c)

### Steps to reproduce

![Screenshot_20240505_111841_Mindustry](https://github.com/Anuken/Mindustry/assets/168959239/1b22c89a-5266-479c-aa05-299b0fdc00cd)

### Mods used

У меня нет установленных модов

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Duplicate, reported countless times before.
