### ISSUE TITLE
Sound but

### ISSUE THREAD

**Issue by Enmanuelol123** [Anuken/Mindustry#9813]
### Platforms

Android

### Build

146

### Issue

Sometimes when I open the game and enter the menu out will load and everything but the game will be completely silent, no music or sound effects at all, even if all volume sliders are at 100%, generally I need to close the game and restart for the chance of the game make some noise, generally the game will open with no audio until like the third or fourth restart, I think it will probably be related to my phone, a moto g 60 with 128 gigabytes of space.

### Steps to reproduce

Just open the game and it will have no sound at all

### Mods used

I have some music mods and also use scheme size but the bug happen even with all mods off 

### Save file

[saveduatry.zip](https://github.com/Anuken/Mindustry/files/15213482/saveduatry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce the issue on my phone.
