### ISSUE TITLE
Enemy builder units in RTS AI do not rebuild blocks

### ISSUE THREAD

**Issue by BlueTheCube** [Anuken/Mindustry#9819]
### Platforms

Windows

### Build

bleeding-edge build 24996

### Issue

When RTS AI is enabled, builder units on non-player teams do not rebuild destroyed blocks.

### Steps to reproduce

* Before entering a map, it must have a builder unit factory/core and another random building on a non-player team. 
* Enable RTS AI on that team.
* Destroy the non-player team's random building.
* The builder units do not rebuild it

### Save file

[malis team.zip](https://github.com/Anuken/Mindustry/files/15231942/malis.team.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by BlueTheCube** [comment]
it used to work on release 146

**Comment by Anuken** [comment]
![2024-05-07-07-53-14](https://github.com/Anuken/Mindustry/assets/10100000/18281fd8-cdb9-45ac-b87b-f293e80fde3e)

They do...?

**Comment by BlueTheCube** [comment]
speed up the building speed next time

**Comment by BlueTheCube** [comment]
set malis to waveteam; they won't build

**Comment by BlueTheCube** [comment]
I get it; the blocks are not rebuilt because there are opposing team's units. maybe speed up the building speed
