### ISSUE TITLE
Обнулился сектор "Штурмовой архипелаг"

### ISSUE THREAD

**Issue by Legioner8369** [Anuken/Mindustry#9826]
### Platforms

Android

### Build

7-official-146

### Issue

Я отошёл от телефона на несколько минут, а когда вернулся увидел, что игра вылетела, после того, как я зашёл в игру Я увидел, что сектор "Штурмовой архипелаг" обнулился, про этом, все пройденные и открытые после него секторы остались.

### Steps to reproduce

Я просто зашёл в игру после её вылета.

### Mods used

Ничего не использовал

### Save file

[(invalid) (1).zip](https://github.com/Anuken/Mindustry/files/15249700/invalid.1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Legioner8369** [comment]
Подскажите пожалуйста что в этом случае делать

**Comment by Anuken** [comment]
You have not attached a crash log or any means of consistently reproducing the problem, so I can't help you.
