### ISSUE TITLE
Handshake failure error

### ISSUE THREAD

**Issue by ClownGolimyi** [Anuken/Mindustry#9833]
### Platforms

Windows

### Build

Steam build 146

### Issue

When I tried to download mods on Mindustry, the game displayed the error "Handshake Failure", I don't know how to fix it

### Steps to reproduce

Just try downloading mods directly in the mod browser

### Mods used

-

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by camelStyleUser** [comment]
network issue

**Comment by mahdoosh1** [comment]
bad internet connection,
if that isnt the case try using a vpn
