### ISSUE TITLE
My copper is lost 😭

### ISSUE THREAD

**Issue by I-Tfar** [Anuken/Mindustry#9834]
### Platforms

Android

### Build

7-official-146

### Issue

_Здравствуйте, простите что на русском, я не смог бы описать проблему на английском(только сдаю на B1) из-за этого немного запутался в форме отчета_

**Проблема:**
Из ядра базы стала пропадать медь (её не использовали для крафта, я играю 1, к ядру подведены конвееры по добыче меди), на глазах мои 2 тысячи запасов скоратили до 600 едениц(буквально на глазах, она пропадал)

### Steps to reproduce

Я завоевывал сектор "разрушенные берега" и во время стройки увидел что медь стала пропадать без моей активности, я пробовал только "включить/выключить игру" и решил написать сюда 

### Mods used

-

### Save file

[save .zip](https://github.com/Anuken/Mindustry/files/15277988/save.zip)

### (Crash) logs

[logs.zip](https://github.com/Anuken/Mindustry/files/15277993/logs.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This issue doesn't make sense, and I've never seen anything like it. Sounds like a problem with your mods (perhaps an auto-research feature?)
