### ISSUE TITLE
No russian translation when tungsten is introduced????

### ISSUE THREAD

**Issue by UserMax1** [Anuken/Mindustry#9837]
### Platforms

Android

### Build

release build 146

### Issue

when tungsten is introduced on russian localization its written in english

### Steps to reproduce

just get to tungsten

### Mods used

Scheme Size

### Save file

im boutta say smth bad: ITS EVERYWHERE!!!!!!!!!!

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Lack of translation or translation errors are not bugs. If a translation is missing, make a pull request.
