### ISSUE TITLE
Нету серверов и ошибки при входе в браузер модификаций.

### ISSUE THREAD

**Issue by sedruh** [Anuken/Mindustry#9838]
### Platforms

Android

### Build

7-official-146

### Issue

Нету серверов и ошибки при входе в браузер модификаций.

### Steps to reproduce

Я просто хочу открыть браузер модификаций и куча ошибок, а также при поиске серверов они отсутствуют.

### Mods used

Я не могу их использовать так как не могу их установить.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
This has been reported countless times, it's an issue with your network.
