### ISSUE TITLE
How do i make a mod în mindustry i want to know how

### ISSUE THREAD

**Issue by General-1** [Anuken/Mindustry#984]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by ZkyLB** [comment]
:facepalm:

**Comment by General-1** [comment]
Thx

**Comment by Anuken** [comment]
Issues are not for asking questions. Glance at the guide linked in the game.
