### ISSUE TITLE
Sorry for changing the value of a data in memory without authorization, which resulted in an array out-of-bounds issue, causing only one level in the game to be damaged. Wondering if there's any repair method available?

### ISSUE THREAD

**Issue by 1zx1120** [Anuken/Mindustry#9840]
### Platforms

Windows

### Build

146

### Issue

Sorry for changing the value of a data in memory without authorization, which resulted in an array out-of-bounds issue, causing only one level in the game to be damaged. Wondering if there's any repair method available?
This error is an ArrayIndexOutOfBoundsException, occurring within the mindustry.world.ItemBuffer.accept method. 
It attempts to access an array with a negative index of -56 while its length is 14, leading to the exception being thrown.

How can I make up for this mistake? In which file is the *itemBuffer* more likely to appear?

### Steps to reproduce

I...used the CheatEngine to changed a data with a value of 2 to 12999, in the zone 133 ion the purple planet.
And.. the consequence is extremely regrettable.

### Mods used

None

### Save file

[Save_120524_17_12.zip](https://github.com/Anuken/Mindustry/files/15285672/Save_120524_17_12.zip)

### (Crash) logs

[crash-report-05_12_2024_16_46_04.txt](https://github.com/Anuken/Mindustry/files/15285622/crash-report-05_12_2024_16_46_04.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by SITUVNgcd** [comment]
Well!
https://github.com/Anuken/Mindustry/blob/f5d550af4afbdd085169b6221ae6f8756faa6c44/core/src/mindustry/world/ItemBuffer.java#L24

**Comment by camelStyleUser** [comment]
> ### Platforms
> Windows
> 
> ### Build
> 146
> 
> ### Issue
> Sorry for changing the value of a data in memory without authorization, which resulted in an array out-of-bounds issue, causing only one level in the game to be damaged. Wondering if there's any repair method available? This error is an ArrayIndexOutOfBoundsException, occurring within the mindustry.world.ItemBuffer.accept method. It attempts to access an array with a negative index of -56 while its length is 14, leading to the exception being thrown.
> 
> How can I make up for this mistake? In which file is the _itemBuffer_ more likely to appear?
> 
> ### Steps to reproduce
> I...used the CheatEngine to changed a data with a value of 2 to 12999, in the zone 133 ion the purple planet. And.. the consequence is extremely regrettable.
> 
> ### Mods used
> None
> 
> ### Save file
> [Save_120524_17_12.zip](https://github.com/Anuken/Mindustry/files/15285672/Save_120524_17_12.zip)
> 
> ### (Crash) logs
> [crash-report-05_12_2024_16_46_04.txt](https://github.com/Anuken/Mindustry/files/15285622/crash-report-05_12_2024_16_46_04.txt)
> 
> ### Submission
> * [x]  I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
> * [x]  I have searched the closed and open issues to make sure that this problem has not already been reported.

dont change that value ez

**Comment by camelStyleUser** [comment]
abandon from stats while in a nother sector to delete your save and make it use the map file

**Comment by mahdoosh1** [comment]
Cheat Engine? why?

**Comment by 1zx1120** [comment]
> abandon from stats while in another sector to delete your save and make it use the map file

Oh my, you're a genius! This simple and direct action worked like a charm, no need for VSCode at all. Now I can get back to my game. Thank you so much for your help, once again!

**Comment by 1zx1120** [comment]
> Cheat Engine? why?

I know it's not good to do this... I attempted cheating after dying several times. Then, because it was only my second time using CheatEngine, I ended up getting the numbers wrong, resulting in this error. Changing the numbers is too troublesome, so I'll try my best not to manipulate them anymore.

**Comment by camelStyleUser** [comment]
> > Cheat Engine? why?
> 
> I know it's not good to do this... I attempted cheating after dying several times. Then, because it was only my second time using CheatEngine, I ended up getting the numbers wrong, resulting in this error. Changing the numbers is too troublesome, so I'll try my best not to manipulate them anymore.

why cheat engine when console exists

**Comment by camelStyleUser** [comment]
and you cant mess up random memory

**Comment by camelStyleUser** [comment]
win-win

**Comment by 1zx1120** [comment]
> > > Cheat Engine? why?
> > 
> > 
> > I know it's not good to do this... I attempted cheating after dying several times. Then, because it was only my second time using CheatEngine, I ended up getting the numbers wrong, resulting in this error. Changing the numbers is too troublesome, so I'll try my best not to manipulate them anymore.
> 
> why cheat engine when console exists

Wow, I had no idea this feature even existed, but now I do. As a newcomer to the game, I don't yet have a deep understanding of it. I finished Erekir first before starting Serpulo. Maybe because I found the orange planet too easy, the difficulty curve on the purple planet felt a bit challenging, leading to this series of events. Anyway, thank you!
