### ISSUE TITLE
Сервера сообщества пропали и  при удалении игры сервера не появляются

### ISSUE THREAD

**Issue by Scofard771** [Anuken/Mindustry#9841]
### Platforms

Android

### Build

146

### Issue

Нету серверов сообщества

### Steps to reproduce

Не появились сервера сообщества

### Mods used

Нетспользую

### Save file

Нету серверов сообщества

### (Crash) logs

Небыло

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

No you haven't.
