### ISSUE TITLE
bug in server list

### ISSUE THREAD

**Issue by zxsrxtrepo** [Anuken/Mindustry#9842]
### Platforms

Windows

### Build

release build 144

### Issue

founed a bug, im sure that u know about it
короче, когда альт табаешься, находясь в сервер листе все найденные сервера пропадают и не находятся до перезахода

### Steps to reproduce

альт таб в сервер листе

### Mods used

scheme pack, scheme size, foo client

### Save file

слишком много весит гугл диск -> (https://drive.google.com/file/d/1x9tcxYiWGcGBVLkZ0kQBGZ5j49pbcN2-/view?usp=sharing)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by zxsrxtrepo** [comment]
видосик https://drive.google.com/file/d/1wgm_IINZqpUDr46ZW3Jy9-iUikq94NcQ/view?usp=sharing

**Comment by camelStyleUser** [comment]
> release build 144


> [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.

you certainly did not

**Comment by camelStyleUser** [comment]
and youre using foos
