### ISSUE TITLE
Опробывал карту

### ISSUE THREAD

**Issue by COOKIE-184** [Anuken/Mindustry#9843]
### Platforms

Windows

### Build

146

### Issue

Нажал на "Опробовать карту" игра вылетела, появился блокнот и больше не могу зайти в игру (крашится при загрузки игры)

### Steps to reproduce

Нажал на "Опробовать карту", попытался удалить моды

### Mods used

scheme size, foo client, scheme pack, sapphirium, shaders, schemepack 400+, virtual scheme pack. extended ui, mapping utilities, autodrill, timecontrol

### (Crash) logs

[hs_err_pid9616.log](https://github.com/Anuken/Mindustry/files/15286239/hs_err_pid9616.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Foo's client/modded bugs should not be reported here.
