### ISSUE TITLE
the problem is in the mods

### ISSUE THREAD

**Issue by Uesjsgisbsh** [Anuken/Mindustry#9844]
### Platforms

Android

### Build

У меня последняя версия я это проверял (я просто не понял что сюда писать)

### Issue

Здравствуйте. Когда я захожу в раздел модификаций чтобы скачать у меня не заходит и через пару секунд вылезает табличка с надписью *Read timed out* я пытался исправить и переустановить но не помогло помогите пожалуйста добрая поддержка!

### Steps to reproduce

Я хотел установить мод но у меня вышла табличка read timed out я пытался что-то сделать но не получилось

### Mods used

На тот момент у меня был установлен только один мод Autodrill 

### (Crash) logs

При заходе в раздел модификаций вылезает табличка *Read timed out
*

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
- "LATEST IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME."
- network issue

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

No you haven't.

**Comment by S0meM** [comment]
This is a firewall issue. This is not part of the game.
