### ISSUE TITLE
Duct contents network desynchronization

### ISSUE THREAD

**Issue by jordan-woyak** [Anuken/Mindustry#9845]
### Platforms

Linux

### Build

bleeding-edge build 25008

### Issue

Accidentally temporary duct contamination can cause a significant network desynchronization of duct contents.
Resource production can appear working perfectly for a client but mysteriously not increasing resource counts, presumably because of host authority on resources.

I've first noticed this issue accidentally while playing campaign cooperatively in the current steam build 146 (Windows host + Linux client).
In my attached video I reproduce the issue in "bleeding-edge build 25008" (Linux host + client) connected via `localhost`.

### Steps to reproduce

The attached video demonstrates the issue more clearly than I can explain in text.
Host game is on the left. Client game is on the right.
A duct is accidentally quickly contaminated with both Water and Ozone and then fed to an Oxidation Chamber.

From the client's perspective: The duct contains only Ozone. Oxide appears to be successfully produced and the Beryllium container contents go down, however, Oxide resource counts "mysteriously" are not increasing.

From the host's perspective: Water is stuck in the duct immediately to the left of the Oxidation Chamber which permanently halts production.

Video:
https://github.com/Anuken/Mindustry/assets/1768214/90effb6c-eb4f-4f81-ad8d-06ad2e367fb6

Instructions:
I've attached a save however the issue is easily reproducible in Campaign or Sandbox.
Clear Game Data / Play / Custom Game / Map: `Domain` / Gamemode: `Sandbox` / Customize Rules: Disable `Waves` / Erekir
"Host Multiplayer Game". Have another instance of the game join.
Temporarily mix Water/Ozone and then feed the should-be Ozone to an Oxidation Chamber.
It may not happen every time, but fairly consistently it is possible for water to be contained in the duct, but only from one game's perspective.

### Mods used

None.

### Save file

[pipe-desync-bug-save.zip](https://github.com/Anuken/Mindustry/files/15287886/pipe-desync-bug-save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
Yep! I faced this many times while playing on Community servers.
Sometime, conduit can't transfer liquid fast enough to feed factories even use 2 or 3 lines of conduits. I must use liquid junction + liquid container trick to make them move faster on server side.

**Comment by Anuken** [comment]
All transportation blocks can easily get desynced with just a single item or fluid cell being deposited/moved a few frames too late, or any difference related to update order. There's no solution to this other than using the `/sync` command.

**Comment by jordan-woyak** [comment]
> All transportation blocks can easily get desynced with just a single item or fluid cell being deposited/moved a few frames too late, or any difference related to update order. There's no solution to this other than using the `/sync` command.

Yes. *That* is the issue. :P

**Comment by camelStyleUser** [comment]
> > All transportation blocks can easily get desynced with just a single item or fluid cell being deposited/moved a few frames too late, or any difference related to update order. There's no solution to this other than using the `/sync` command.
> 
> Yes. _That_ is the issue. :P

and you cant solve it without increasing network bandwidth used by quite a lot

**Comment by jordan-woyak** [comment]
> and you cant solve it without increasing network bandwidth used by quite a lot

Synchronizing block creation, transport block states, etc. does not need to use significant bandwidth.
Even if this was the reason blocks are not synchronized, which it isn't, the average user would prefer increased bandwidth and consistent game states.

Anyways, the network code is flawed, and I'm not saying that network code is easy, but improving it is certainly possible.

If the work doesn't want to be done, then fine, leave it broken, but blaming it on network bandwidth requirements is silly.

**Comment by Anuken** [comment]
> Anyways, the network code is flawed, and I'm not saying that network code is easy, but improving it is certainly possible.

Yes, I am aware that it is flawed. You're welcome to give it a try if you like; I've attempted many different approaches, and none of them lead to usable results. It doesn't help that every client has a different framerate, leading to slightly (or wildly) different simulations of the game.

Giving suggestions is easy, implementing them is not.
