### ISSUE TITLE
Inverted sorter can be used to make all in one conveyor

### ISSUE THREAD

**Issue by MageDelfador** [Anuken/Mindustry#985]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *99.8*

**Issue**: *Inverted sorter can be used to make all in one conveyor
![test](https://user-images.githubusercontent.com/9780339/68083480-df1dcb80-fe63-11e9-8b82-1d3a6b45cc44.png)

[1572774831278.zip](https://github.com/Anuken/Mindustry/files/3801420/1572774831278.zip)

*

**Comment by BasedUser** [comment]
Fixed by #936.

**Comment by Anuken** [comment]
This is known, there's already a pull request for it. Discussion should go there.
