### ISSUE TITLE
Stuck at loading screen on sector 210, near fungal pass, serpulo.

### ISSUE THREAD

**Issue by Mrbruhhh** [Anuken/Mindustry#9854]
### Platforms

Android

### Build

Version 7-official- 146

### Issue

When i want to go to sector 210 from fungal pass, serpulo but it's always stuck at loading screen until it force closed itself on my phone when i want to go again to that sector, its says my core resources is wasted / not sufficient like i was already played there before but it's not.

### Steps to reproduce

I simply click launch from fungal pass, select my core and stuck at loading screen

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
No save file attached.
