### ISSUE TITLE
game crashes when clicking , or . without items

### ISSUE THREAD

**Issue by acheesethatsblue** [Anuken/Mindustry#9855]
### Platforms

Windows

### Build

v7.0 build 146

### Issue

a nooke!11!1!1!! ok but really, when all buildings are disabled in a custom map, categories don't exist, yea? i was playing some rvsb, but, i clicked the , key (it changes categories, building is disabled in rvsb) and the game crashed with the "mindustry.executeable has stopped working". (there's no crashlog because this is a windows crash, also be sure to turn on "hide banned blocks" or whatever its called for this to work!!!)

### Steps to reproduce

1. ban all items in a custom map/play a gamemode with all buildings banned
2. click the , or . keys on your keyboard
3. enjoy your crash screen

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
doesnt crash on BE

**Comment by camelStyleUser** [comment]
always check your crashes on BE since it contains all the bugfixes

**Comment by JasonP01** [comment]
Since i dont doubt anuke would still want to test this, rsvb is Red vs Blue gamemode for the Xcore community server in the server list

**Comment by Anuken** [comment]
> there's no crashlog because this is a windows crash

Crash logs should get generated on every operating system. You also have not attached a save.

**Comment by S0meM** [comment]
I also had this error when on a server without any blocks.

**Comment by S0meM** [comment]
Crash logs are in C:\Users\YourUserName\AppData\Roaming\Mindustry\crashes

**Comment by mahdoosh1** [comment]
> Crash logs are in C:\Users\YourUserName\AppData\Roaming\Mindustry\crashes


Are in %APPDATA%\Roaming\Mindustry\crashes
