### ISSUE TITLE
Bug on sector 210

### ISSUE THREAD

**Issue by XenXL** [Anuken/Mindustry#9856]
### Platforms

Android

### Build

164

### Issue

_This happened recently (since the creation of the report) when I had just finished capturing the thickets and set up the production of silicon and graphite in five minutes and went to sector 210 on the first wave I was greeted by... 338 UNITS! And everyone was either T4 and T3, if there is something I didn’t capture such bases as tar fields, mining base and the like, please correct it if possible _

### Steps to reproduce

The first thing I did was take a screenshot of the bug and left the sector, then I went to the industry server (official) and found your github,

### Mods used

Not used
![Screenshot_2024-05-16-23-36-19-082_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/170050733/54a5931b-f66e-4b3f-b6a7-ec09f4857ea2)

### Save file

Campaign, Sector 210
[Uploading test.zip…]()

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This has been reported many times already.
