### ISSUE TITLE
crash after time

### ISSUE THREAD

**Issue by theshizik** [Anuken/Mindustry#9858]
### Platforms

Android

### Build

realese build 146

### Issue

after some time of playing after downloading mod "mobile-controls" game crashes.

### Steps to reproduce

i dont really know but i downloaded then deleted mod mobile controls.

### (Crash) logs

[crash_logs.txt](https://github.com/Anuken/Mindustry/files/15367593/crash_logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [ ] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
>  I am not using Foo's Client, and have made sure the bug **is not caused by mods I have installed.**

**Comment by SITUVNgcd** [comment]
Any issues caused by mod will (can) not be fixed in vanilla.

Report mod's issue to mod onwer (repo on github).
