### ISSUE TITLE
featHub certificate invalid

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#986]
**Platform**: N/A

**Build**: *N/A

**Issue**: The SSL certificate that the feature request site, feathub, uses is expired.  This breaks the readme.md feathub display and poses a potential security risk for people who sign into accounts on feathub.

**Steps to reproduce**: Look at the readme.md on github.  Click the feature requests link.

**Comment by Anuken** [comment]
There's nothing I can do about that. Just don't use Feathub until they fix it.
