### ISSUE TITLE
Network bug

### ISSUE THREAD

**Issue by RandomsongV2** [Anuken/Mindustry#9863]
### Platforms

Android

### Build

146

### Issue

Mod browser does not load mods
Also multiplayer is not work too
(Network issue)
(i have normal internet and earlier all works)

### Steps to reproduce

Just go to the mod list and then mod browser

### (Crash) logs

[Crash log](https://github.com/Anuken/Mindustry/files/15370561/Crash.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.
