### ISSUE TITLE
Wrong key in control menu with azerty layout but work fine in game

### ISSUE THREAD

**Issue by Neoz30** [Anuken/Mindustry#9867]
### Platforms

Windows

### Build

146

### Issue

My keyboard is azerty. In control menu, the key it show isn't the right ones. But when I play it work correctly

### Steps to reproduce

Nothing just my keyboard is azerty, the language and the layout keyboard don't change the key show

### Save file

[mindustry save.zip](https://github.com/Anuken/Mindustry/files/15374724/mindustry.save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
This is known and has been reported before, but won't be fixed. Key names displayed are based on position.
