### ISSUE TITLE
I downloaded the mod Better blocks more when I enter a server says I don't have the mod my mindustry is updated mi build is 99.6

### ISSUE THREAD

**Issue by leonardoBRASILERO** [Anuken/Mindustry#987]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required.*

**Issue**: *Explain your issue in detail.*

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

**Comment by Anuken** [comment]
1. Use the issue template.
2. You can't enter servers with a mod installed if the server doesn't have it.
3. Update your game.
