### ISSUE TITLE
Chinese website steals mindustry bgm

### ISSUE THREAD

**Issue by xianquu** [Anuken/Mindustry#9870]
### Platforms

Linux

### Build

0

### Issue

A Chinese "self-developed" operating system launch site steals mindustry bgm

https://v.eqxiu.com/s/H6TVUeRy?bt=yxy&eip=true

https://github.com/Anuken/Mindustry/assets/160004827/1ef268e8-1f57-45fe-9b39-eb905d7093ac

### Steps to reproduce

0

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Otamamori917** [comment]
I don't think that's mindustry bgm
Maybe you got the wrong game?
But I've never heard that in the music files

**Comment by xianquu** [comment]
> Maybe also put which music file you think it is? [Music files](https://github.com/Anuken/Mindustry/tree/master/core%2Fassets%2Fmusic)

https://github.com/Anuken/Mindustry/blob/master/core/assets/music/menu.ogg

It seems to be a variant version of this music

**Comment by Otamamori917** [comment]
Hmm I see a slight similarities 
But idk anuke can figure out if they are the same or not if they think it's a problem

**Comment by Anuken** [comment]
It doesn't sound like the menu theme to me at all. It's certainly not the exact track from the game.
