### ISSUE TITLE
Suddenly i got attacked by over 100 units

### ISSUE THREAD

**Issue by Vldtzzz** [Anuken/Mindustry#9871]
### Platforms

Android

### Build

release build 146

### Issue

Launched the game, continued the campaign on Atlas and suddenly i got attacked from everywhere by over 100 units.

### Steps to reproduce

I just launched the game, continued the campaign on Atlas and boom I got stormed. I'm sorry that I can't tell you much more.

### Mods used

None

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/15405149/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Otamamori917** [comment]
Yea that's the game what did you expect?
Campaign gets harder so more enemy units spawn

**Comment by Otamamori917** [comment]
Also you can look on the top left corner to see how much time you got before a wave spawns :)

**Comment by Galahadagent** [comment]
1. Try to build the T2 units and use them.
2. Try to destroy the enemy turrets' duct , armoured duct to stop them refill their ammo.
3. Also I think this isn't a bug.

**Comment by Anuken** [comment]
Don't let them produce 100 units to attack you.
