### ISSUE TITLE
Ошибка при скачивание модификаторы и не нахождения сервера

### ISSUE THREAD

**Issue by Oti180** [Anuken/Mindustry#9872]
### Platforms

Android

### Build

7-official-146

### Issue

Когда я хочу скачать модификаторы но, у меня вылазит ошибка
![Screenshot_20240522-181243](https://github.com/Anuken/Mindustry/assets/170454192/dc372df6-27af-46e9-a749-6a58cf61abb1)
И не могу найти онлайн сервера

### Steps to reproduce

Ошибка выдаёт когда если долго ждёшь чтобы появились таблица с модификаторы
![Screenshot_20240522-181243](https://github.com/Anuken/Mindustry/assets/170454192/04d0d919-5755-4d81-8f27-347c448f436c)

### Mods used

![Screenshot_20240522-184047](https://github.com/Anuken/Mindustry/assets/170454192/1823b5a0-d2f7-4019-a4f7-3228dbc0b964)
![Screenshot_20240522-184057](https://github.com/Anuken/Mindustry/assets/170454192/bdca2c1e-168e-4b13-9385-02c9433e027d)

### Save file

Но у меня нет проблем по этому поводу, но я всякий случай сделать это всё что сказано(я выбрал 1 вариант исправления) но в итоге, нечего этого результата не дало вообще тоже самое ошибка где скачивать модификаторы и сервера не показываются

### (Crash) logs

У меня нет «Данные игры» и «Экспорт журналов сбоев»

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.
