### ISSUE TITLE
Different wave information at the same time in the sector 205

### ISSUE THREAD

**Issue by Galahadagent** [Anuken/Mindustry#9873]
### Platforms

Android

### Build

release build 146

### Issue

I survived 6 out of 20 waves in the sector 205 , I saved and quited. After that when I was seeing the serpulo planet in landscape view the under attack sector 205 says, "survives 11/14 waves" but actually in game (in the sector 205 while playing) it says wave 6/20. The waves information are different at the same time.
Please See the difference in this short video 
Thank you!

https://github.com/Anuken/Mindustry/assets/161305918/47b99825-3221-4d20-84bb-524a8face0c4

### Steps to reproduce

The game was launched for the sector 205 by me, I survived the 6th no. wave, saved and quited the game. Thereafter I was looking at the planet serpulo and noticed the under attack status for the sector 205 says that I survived 11/14 waves but in game it says wave 6/20. 
Also yes I was playing it in landscape but I had disabled lock landscape.
That all it is.

### Save file

[Please don't play with my gamedata in multiplayer.zip](https://github.com/Anuken/Mindustry/files/15407557/Please.don.t.play.with.my.gamedata.in.multiplayer.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
There are 14 (20-6) waves left in that sector, and it will survive 11 of them if you play on another sector.

**Comment by Galahadagent** [comment]
Oh i understand the first one but can you explain this sentence 
> and it will survive 11 of them if you play on another sector.

With example ?

**Comment by Galahadagent** [comment]
And thank you
