### ISSUE TITLE
Modded map exporting or importing exits the game on mobile

### ISSUE THREAD

**Issue by iRatzeyMezeri** [Anuken/Mindustry#9874]
### Platforms

Android

### Build

146

### Issue

When i try to export or import a modded map, the game just exits itself and hands me a 0 Byte file, i dont remember if that issue happens with non-modded maps too but iirc not.
This also sometimes happens with schematics too, both Export and Import.

Schematics all and Map import definetely apply to vanilla maps too

 might be a Mapping Utils issue but it happens with schematics  too so

### Steps to reproduce

1. Make a modded map
2. Export
3. Export as file
4. give it a name, save
5. **profit**

### Mods used

Psammos Mod; Mapping Utilities; Testing Utilities

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
I do not debug issues caused by mods.

**Comment by ApsZoldat** [comment]
Again MU mhm

Can you at least get the crash log for me though? In case this is an issue with mapping utilities
