### ISSUE TITLE
Very bugged map, idek

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#9875]
### Platforms

Windows

### Build

146

### Issue

There are a couple issues here

1, Erekir mech tree cannot be spawned, why? idk, there is no map rule, no wproc, no nothing denying them to spawn

2, Power is bugged on the yellow base, near the bottom of the yellow circle on enemy team there are menders enabled (animation, and working) however there is no power source to them, absolutely no reason they should be powered

Map saved from Chaotic Neutral server, @phinner has also noted the issues and as far as i can tell couldnt figure it out either

### Steps to reproduce

Try spawn any of the erekir mech tree units (all other units work)

Observe yellow base being enabled without a power source, where one is needed (i theorize it is because of the surge conveyors)

### Mods used

Vanilla

### Save file

[VeryBuggedMap.zip](https://github.com/Anuken/Mindustry/files/15409899/VeryBuggedMap.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
All issues were witnessed in vanilla, in singeplayer, just to be sure

**Comment by phinner** [comment]
Your file is not a zip, its a msav file with a zip extension :monocle_face:

**Comment by JasonP01** [comment]
very true, but counter arguement just change the extension i couldnt be asked to open a proper file explorer to properly zip it

**Comment by Anuken** [comment]
> 1, Erekir mech tree cannot be spawned, why? idk, there is no map rule, no wproc, no nothing denying them to spawn

The environment in the map rules doesn't support them.

![image](https://github.com/Anuken/Mindustry/assets/10100000/fbc3cb50-8f7d-4233-b9d4-67638d6bff22)

> 2, Power is bugged on the yellow base

Shielded walls and surge conveyors conduct power, not a bug.

**Comment by JasonP01** [comment]
oh and also this issue has been observed on 1 more map, same predicament

**Comment by JasonP01** [comment]
ok mb ig, i didnt even change the env ig. thx tho anuke
