### ISSUE TITLE
Серпуло не работает

### ISSUE THREAD

**Issue by KirBo111111** [Anuken/Mindustry#9877]
### Platforms

Android

### Build

146

### Issue

У нас нет кремния поэтому мы не может лететь на сектора если что у сектор на серпуло отправная точка

### Steps to reproduce

Мы не знаем

### Mods used

Мы не используем моды

### Save file

[(invalid).zip](https://github.com/Anuken/Mindustry/files/15416028/invalid.zip)

### (Crash) logs

Мы не знаем в листе об ошибках ничего нет

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
send the shard core

**Comment by camelStyleUser** [comment]
no silicon needed
