### ISSUE TITLE
Mindustry won't load

### ISSUE THREAD

**Issue by cheburashka777** [Anuken/Mindustry#9878]
### Platforms

Windows

### Build

146

### Issue

When starting the game, the loading reaches the Content or Image stage and either the game takes forever to load or freezes. Updating drivers and reinstalling Java does not help. Mindustry does not start from either the exe file or the jar file. If download the build from https://github.com/Anuken/MindustryBuilds, the error will also not disappear.

### Steps to reproduce

Just started the game.

### Save file

[0.zip](https://github.com/Anuken/Mindustry/files/15416059/0.zip)
I couldn’t enter the game, so I took out the latest file from the saves folder.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
console logs or last_log.txt?

**Comment by cheburashka777** [comment]
[last_log.txt](https://github.com/Anuken/Mindustry/files/15416132/last_log.txt)

**Comment by cheburashka777** [comment]
I removed the files that were described in the log, tried to launch the game and now there are even more files in the log!
[last_log.txt](https://github.com/Anuken/Mindustry/files/15416229/last_log.txt)

**Comment by cheburashka777** [comment]
In general, cleaning the Mindusry folder in AppData helped, now everything is fine!!!!!!!!!!!!!!!!!
