### ISSUE TITLE
Не отображаются глобальные сервера. 

### ISSUE THREAD

**Issue by Hlorit** [Anuken/Mindustry#9879]
### Platforms

Android

### Build

146

### Issue

Я захожу в сетевую игру, но глобальные сервера не видны. Если добавлю сервер по айпи, то спокойно захожу и могу играть. 

### Steps to reproduce

Я раньше играл в миндастри, но забросил, и вот недавно решил вернуться, но произошёл такой баг:(

### Mods used

Я не использую моды

### Save file

Я ужалил игру и скачал заново без импорта файлов, самую чистую с офиц. сайта. 

### (Crash) logs

Отсутствуют 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.
