### ISSUE TITLE
Игра стала баговаться

### ISSUE THREAD

**Issue by KirBo111111** [Anuken/Mindustry#9881]
### Platforms

Android

### Build

146

### Issue

Игра стала приближаться до невозможности играть

### Steps to reproduce

Я ни знаю всë началось со вчерашнего дня я думал что это просто так игра работает , но сейчас она уже не запускается

### Mods used

Я не использую моды

### Save file

[files mindustry.zip](https://github.com/Anuken/Mindustry/files/15442082/files.mindustry.zip)

### (Crash) logs

[files mindustry.zip](https://github.com/Anuken/Mindustry/files/15442083/files.mindustry.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Crash logs are required.
