### ISSUE TITLE
a client can build unresearched blocks in Champaign

### ISSUE THREAD

**Issue by mahdoosh1** [Anuken/Mindustry#9884]
### Platforms

Android

### Build

for a long time untill and even 146

### Issue

When a client joins to hosting person's campaign. client can build blocks not researched by host

issue tracker was too big and couldn't find similar issue in it for like 4 pages (even with search)

### Steps to reproduce

Host:

1. go to campaign and host (atleast one block not unlocked)
2. wait for client to join

Client:

1. have all of tech tree unlucked (unsure if required)
2. join host
3. place an unresearched block

### Mods used

Unreleated, Happens on Vanilla

### Save file

Unreleated to sectors, idk how to export campaign data

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mahdoosh1** [comment]
EDIT: version was incorrect so i fixed it

**Comment by Anuken** [comment]
Intentional.

**Comment by mahdoosh1** [comment]
> Intentional.

but that's bad, my friends join me in a lan party but they cheat by using blocks not researched :(

isn't there a way to prevent? i can't just moderate my friends and ban them.
