### ISSUE TITLE
OOM issues encountered while playing sector.stronghold

### ISSUE THREAD

**Issue by A4-Tacks** [Anuken/Mindustry#9885]
### Platforms

Android

### Build

7-official-146

### Issue

Problem encountered while playing sector.stronghold

### Steps to reproduce

Unknown

### Mods used

NONE

### (Crash) logs

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 224416 free bytes and 219KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:98)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:122)
	at mindustry.async.AsyncCore.begin(AsyncCore.java:9)
	at mindustry.ClientLauncher.update(ClientLauncher.java:19)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:22)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
OOM=need better device

**Comment by A4-Tacks** [comment]
12G, I think this should be enough

**Comment by camelStyleUser** [comment]
> 12G, I think this should be enough

how much memory did you allocate to java

**Comment by A4-Tacks** [comment]
> how much memory did you allocate to java

I am not familiar with the behavior of Android, but there are very few other software in use

**Comment by SITUVNgcd** [comment]
May be this error casued by save file, try abandon this sector and replay it.
You can make data backup before abandon it.

**Comment by Anuken** [comment]
This was already reported and fixed.
