### ISSUE TITLE
issues with launching the game

### ISSUE THREAD

**Issue by PigpoleEnjoer** [Anuken/Mindustry#9890]
### Platforms

Windows

### Build

build 146

### Issue

the game freezes and takes forever to load
![photo_5377432388012987813_w](https://github.com/Anuken/Mindustry/assets/170888603/64b9a135-07e1-4519-969a-a6f77d5de187)

### Steps to reproduce

idk

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
With no log and no other information, I can't help you.

**Comment by mahdoosh1** [comment]
Most likely a system issue, buy a better pc or be patient, if a crash happens go to %APPDATA%\roaming\mindustry
and look for the latest crash log
