### ISSUE TITLE
Mindustry

### ISSUE THREAD

**Issue by ganchek9957** [Anuken/Mindustry#9894]
### Platforms

Android

### Build

146

### Issue

Проблема я захожу в игру а у меня вот это что делать
![Screenshot_2024-05-28-12-41-52-200_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/171022871/e125e6e4-e195-43cd-ad4a-e36c8738c35f)
![Screenshot_2024-05-28-12-41-36-705_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/171022871/441b24e3-1db0-4316-a220-f8650bb6777e)

### Steps to reproduce

Я вышел покнобпке выйти в главном меню

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [ ] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
dont change your ui scale to ungodly values simple

**Comment by SITUVNgcd** [comment]
Wow! You changed UI scale to 100x?

**Comment by mahdoosh1** [comment]
Oh hell i see a glitch thats not discord icon
