### ISSUE TITLE
No units and players in multiplayer

### ISSUE THREAD

**Issue by sharpenedblade** [Anuken/Mindustry#9896]
### Platforms

Mac

### Build

146

### Issue

When I join a (it doesnt matter which one) server, I can load in without any errors and see buildings and items and stuff, but I cant see units, other players, or my core unit. Pressing tab to view players also only shows me. When I save the game and open it in single player, I can see all of the missing units and "I" spawn in too. Other players on the server say they can see me moving my unit around.

I have checked on multiple different networks and cleared my game data but it doesn't help. The game does work on a linux VM running on the same host, so it probably is not my network.

### Steps to reproduce

1. Open mindustry
2. Join a server
3. Try to move or build
4. Press tab
5. Use `/sync`
6. Disconnect and try again

The bug still occurs

### Mods used

N/A (I have no mods installed)

### Save file

[bug_report_save.msav.zip](https://github.com/Anuken/Mindustry/files/15478278/bug_report_save.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by sharpenedblade** [comment]
I just checked again and I can posses turrets and they work, but when I press `v` to respawn the game shows me as still inside the turret, but then when I try to move I can. Also I see a warrning "unit cant build" in the build menu when I spawn in so I cant build.

**Comment by Anuken** [comment]
Cannot reproduce this issue on any device. It is likely related to your network or OS; something is blocking UDP packets, I can't help you.

**Comment by sharpenedblade** [comment]
> Cannot reproduce this issue on any device. It is likely related to your network or OS; something is blocking UDP packets, I can't help you.

My network is not dropping UPD (or TCP) packets, I checked in wireshark and the client and the server are receiving packets from each other. I checked other UDP connections and they all work, so if there is a problem then it is in mindustry. 

It is not working fresh macos install with only mindustry installed, but it is working in a linux VM so it probably a mindustry bug.

I attached a packet dump.
[join_world.pcapng.zip](https://github.com/Anuken/Mindustry/files/15478809/join_world.pcapng.zip)

**Comment by JasonP01** [comment]
Server is rejecting your packets, refusing to spawn you in

**Comment by Anuken** [comment]
> but it is working in a linux VM so it probably a mindustry bug.

Mindustry doesn't have any MacOS/linux-specific netcode. If it's a bug anywhere, then it's likely a bug in the Java standard library UDP networking classes. I've used multiple MacOS devices, however, and the problem does not occur there.

Either way, if I can't reliably reproduce it myself, I can't fix it.
