### ISSUE TITLE
The dark side of the moon

### ISSUE THREAD

**Issue by SITUVNgcd** [Anuken/Mindustry#9897]
### Platforms

Android

### Build

7-official-146 / 7-bleeding-edge-25023

### Issue

1x1 and 2x2 blocks can't be build on border of the map that has __**Border darkness**__ turning on.

https://github.com/Anuken/Mindustry/assets/44901211/048e33ef-e3df-452c-ba1f-f9cc1cf2325b

### Steps to reproduce

1. Mindustry!
2. Game with a map that has border darkness.
3. Build any 1x1 or 2x2 block on border.
4. See!

### Mods used

situvngcd-test-mod
Tested on both v146 and be build 25023 (vanilla)

### Save file

Ok! this is empty map i made for report a bug. If you can't find a map that has border darkness on your devices, use it.
[Empty bug report map.msav.zip](https://github.com/Anuken/Mindustry/files/15486889/Empty.bug.report.map.msav.zip)
Remove `.zip` extesion.

### (Crash) logs

Not crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Not a bug.
