### ISSUE TITLE
Chat doesn't exist

### ISSUE THREAD

**Issue by eclipse1408** [Anuken/Mindustry#9898]
### Platforms

Windows

### Build

146

### Issue

Chat literally doesn't exist. I think this may have something to do with Steam. Messages appear on unit as usual. 

### Steps to reproduce

1. Join server
2. Send message
3. See error

### Mods used

None

### Save file

[192.zip](https://github.com/Anuken/Mindustry/files/15491761/192.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by eclipse1408** [comment]
![image](https://github.com/Anuken/Mindustry/assets/121835599/96eaf411-db5e-495f-afb9-c00a32ddea93)

**Comment by eclipse1408** [comment]
Oh shit i typed the wrong build its 146

**Comment by JasonP01** [comment]
You have chat turned off in graphics

**Comment by Anuken** [comment]
It's either a mod, or you turned it off in your settings.

**Comment by eclipse1408** [comment]
bruh im sped ;-;
