### ISSUE TITLE
Game takes almost a minute to boot up when there is no internet

### ISSUE THREAD

**Issue by PosionFox** [Anuken/Mindustry#9899]
### Platforms

Windows

### Build

146

### Issue

After working on my mod, closing and opening the game repeatedly, i noticed that sometimes the game would take forever to boot up(loading screen is not affected) and other times it boots up almost immediately, after some testing i realized that having no internet was causing the delayed boot up, i disabled all mods, cleared all game data, and yet it keeps happening.

### Steps to reproduce

Unplug your ethernet cable or disconnect from the wifi

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by PosionFox** [comment]
oops, just found out theres a similar issue: https://github.com/Anuken/Mindustry/issues/9899

**Comment by PosionFox** [comment]
[last_log.txt](https://github.com/Anuken/Mindustry/files/15492379/last_log.txt)

**Comment by Anuken** [comment]
I cannot reproduce this issue, and I have never heard of anything similar. The only type of network request that is done on startup is fetching community servers, but that is asynchronous. last_log has nothing notable.
