### ISSUE TITLE
Campaign save issue on mobile

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#990]
**Platform**: iOS 13.2

**Build**: release build 99.1

**Issue**: Game progress lost on app close.  I think this was from the game being cleared from memory or manually closed.  I can’t recall if I hit “save & exit” from the menu or if I relied on the autosave.  I can see the campaign game listed in the “load game” screen, which is odd.  It shows the wave number as 1 even though I was several waves in.  When that game is loaded, structures I built are present but no wave timer is present and it isn’t possible to manually advance to the next wave.

**Steps to reproduce**: Launch ground zero, make some progress, close the app, try to re open the in progress game.

Edit: Actually I think I launched at wave 20 when this issue happened.  The campaign menu shows the resources pulled away to start the mission but not the extracted resources.  It also shows the highest wave as “9” instead of “20”.

**Comment by HagRetek** [comment]
Did you pull the autosave interval slider really up in the settings so it autosaves very rarely?

**Comment by willis936** [comment]
The autosave has been kept at default: 60 seconds.

**Comment by willis936** [comment]
I think this is an iOS 13.2 issue.  I noticed in progress edit boxes get wiped in safari when multitasking.  Also the first item of the iOS 13.2.2 changelog is this:

```Fixes an issue that could cause apps to quit unexpectedly when running in the background```

**Comment by willis936** [comment]
Yep.  This issue exists only on iOS 13.2.
