### ISSUE TITLE
World processor spawning ghost units

### ISSUE THREAD

**Issue by Pixelstormer** [Anuken/Mindustry#9900]
### Platforms

Linux

### Build

steam build 146

### Issue

On custom maps, the 'Spawn Unit' instruction for the world processor fails to properly spawn any units. Inspecting the vars visualiser for the processor shows that the instruction seemingly successfully executed, as the result variable is set to a non-null value of type 'unit', and you can even read valid data from this variable with sensor instructions, but the unit is not actually physically present anywhere on the map.

### Steps to reproduce

1. Create custom map in map editor with a world processor
2. Add a spawn unit instruction to world processor
3. Play the map and observe that no unit actually spawns

### Mods used

Vanilla, no mods or steam workshop content

### Save file

[testy.zip](https://github.com/Anuken/Mindustry/files/15500505/testy.zip)

The world processor is to the right of spawn, and is activated by the switch

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/c0b2ef2a-f714-4646-90b1-ba763f301051)

This is out of bounds. The unit dies immediately.

**Comment by Pixelstormer** [comment]
Oh, I understand now. I incorrectly assumed the coordinates you specify in the instruction to spawn units are the same as the coordinates actually used by units to specify their position (e.g. what you get from entering `Vars.player.unit().x/y` in the console), but instead the instruction uses tile coordinates, which have a drastically different scale.
Specifying tile coordinates in the instruction works perfectly and the units spawn just fine now.
