### ISSUE TITLE
Beryllium on Serpulo 

### ISSUE THREAD

**Issue by Deiteriy2** [Anuken/Mindustry#9901]
### Platforms

Android

### Build

146

### Issue

Why can Mega(Serpulo unit) mine beryllium if it is Erekir resource?

### Steps to reproduce

I opened Serpulo Tech Tree Selektion and viewed Mega info
![Screenshot_20240530_210954_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/171280874/92f39486-1331-4179-9751-c3787a0286c9)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
where is the issue

**Comment by Anuken** [comment]
Nothing stopping it from mining that resource.

**Comment by mahdoosh1** [comment]
> the game doesnt store all the ores a unit can mine


that would be convenient for modding.
