### ISSUE TITLE
Mindustry background music can't be loaded(played)

### ISSUE THREAD

**Issue by Galahadagent** [Anuken/Mindustry#9905]
### Platforms

Android

### Build

Release build 146

### Issue

Normally: when mindustry is fully opened(i mean when the Main menu is loaded) it's background music(bgm) is also started playing.

But some days I have noticed that when mindustry is fully opened, it's bgm isn't started playing.
It happens in both offline and online.
Though I don't know is it happened for my device or not 😐 .

### Steps to reproduce

It's impossible to say how this issue can be reproduced.
I had tried to capture a video about this issue for 20 times 😞 but I failed everytime. So I don't know when this issue will happen.
But really,
the issue: bgm isn't started playing when mindustry  is fully opened, really exists in game ;-;!

### Save file

It doesn't need any save file to be reproduced because it's also happened when mindustry is opened for the first time.

### (Crash) logs

My game hadn't crashed when it happened.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
With no clear steps to reproduce it and no logs, I can't fix this.
