### ISSUE TITLE
-x^0=1 (must be = -1)

### ISSUE THREAD

**Issue by lukanin12** [Anuken/Mindustry#9907]
### Platforms

Android

### Build

146

### Issue

Negative number to the zero is not equel to one. It is equel to minus one, isn't it?

 P.s. I was codding Logic Displays and wanted to use ^0 instead of boolean check (to shorten the code for further operations) in variable showing increasing or decreasing of the function. But operation suddenly returned 1 instead of -1.

### Steps to reproduce

Paste any Logic Processor. Add operation. Choose: 
> operation sign ^
> a = (any negative number);
> b = 0.
Check result in variables.

### Mods used

No mods.

### Save file

[Bug_ -x^0=1.zip](https://github.com/user-attachments/files/15518909/Bug_.-x.0.1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
![image](https://github.com/Anuken/Mindustry/assets/10100000/f99a3a59-bec1-41ca-89ec-b1dabdcd9003)
