### ISSUE TITLE
không thể tăng ram cho mndustry để cài mod

### ISSUE THREAD

**Issue by phamdung3** [Anuken/Mindustry#9908]
### Platforms

Windows

### Build

xây dựng là gì tôi không biết

### Issue

khi cài mod thì báo đầy memory trong khi máy còn thừa

### Steps to reproduce

không biết cách làm

### Mods used

các mod abe-ischarlieop-mod.zip và mod freezemandupowersources1.zip

### Save file

nó không sảy ra trong chiến dịch vì tôi không vào được mindustry khi cài mod

### (Crash) logs

tôi không biết nũa

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Issue caused by mods.

>  and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
Mod bị lỗi nên đã ngốn sạch ram dẫn đến trò chơi thoát ngay lập tức. Bạn nên báo lỗi với người làm ra mod, cái này không liên quan đến trò chơi Mindutry gốc.
