### ISSUE TITLE
Deconstruct overlay stays on already deconstructed blocks 

### ISSUE THREAD

**Issue by Brandanvimi** [Anuken/Mindustry#9911]
### Platforms

Android

### Build

146

### Issue

When you select a block to deconstruct a small overlay appears on the block, if the block is selected multiple times the overlay stays after deconstruction.

### Steps to reproduce

1. join a game of Mindustry (preferably not on sandbox).
2. get some blocks to deconstruct.
3. select the blocks to deconstruct (preferably enough so it takes some time).
4. accept their deconstruction.
5. select them again before they are deconstructed.
6. the overlay stays after deconstruction and can be removed by again accepting deconstruction.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Already reported/fixed.
