### ISSUE TITLE
Mindustry bug

### ISSUE THREAD

**Issue by Derekelpapu** [Anuken/Mindustry#9913]
### Platforms

Android

### Build

146

### Issue

The game crashes when i want to go to overgrowth

https://github.com/Anuken/Mindustry/assets/171459017/b0b5edde-a875-4222-a9ab-7fe8c8bae46f

### Steps to reproduce

Nothing, I capture that sector, the it was atacked, the i try to launch back and crashes 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Otamamori917** [comment]
Gotta drop its save file

**Comment by SITUVNgcd** [comment]
Abandon that sector then replay may be fix this.

**Comment by Anuken** [comment]
Crash log required.
