### ISSUE TITLE
unknown error during gameplay 

### ISSUE THREAD

**Issue by Staropanethy** [Anuken/Mindustry#9917]
### Platforms

Android

### Build

Android 12 galaxy a32

### Issue

Any game process crashes, this has nothing to do with my performance 

### Steps to reproduce

not available  

### Mods used

game without modifications 

### Save file

Can't access game saves 

### (Crash) logs

does not grant access 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
if there are no reproduction steps,no saves,and no logs

**Comment by camelStyleUser** [comment]
anuke cant do anything about it

**Comment by Anuken** [comment]
Crash logs are required.
