### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ray34245** [Anuken/Mindustry#9919]
### Platforms

Windows

### Build

steam build 146

### Issue

It is not visible what the nodes are connected to 

### Steps to reproduce

![WNduneZKuck](https://github.com/Anuken/Mindustry/assets/171570849/0b64f756-79c3-4f8d-8f34-ebb0135108bf)

### Mods used

none

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
node connections are hidden

**Comment by Ray34245** [comment]
А как их обратно включить?

**Comment by Ray34245** [comment]
And how to turn them back on?

**Comment by Ray34245** [comment]
That's it, I found it, thanks

**Comment by Otamamori917** [comment]
Pro tip
Usually check settings before you just make a bug report
