### ISSUE TITLE
Firing while flying in opposite direction

### ISSUE THREAD

**Issue by EwlKirill** [Anuken/Mindustry#9923]
### Platforms

Windows

### Build

146

### Issue

While you are flying in one direction and firing bullets in another direction bullets slow down. And it also seams that it happens on beta and alpha unit from what I tested. I just don't have the technologies to test further.

### Steps to reproduce

Fly in one direction and fire bullets in another.

### Mods used

Schematic size lite.

### Save file

[Bug.zip](https://github.com/user-attachments/files/15605819/Bug.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by azekillDIABLO** [comment]
Huh ain't that just a feature cause that's just the bullet using it's initial velocity like IRL ?

**Comment by mahdoosh1** [comment]
he/she hasnt touched grass enough or hass failed physics

**Comment by azekillDIABLO** [comment]
> That's not how relative velocity works. You, the player, are seeing the world from the alpha/beta/gamma unit's perspective. No matter what _your_ velocity is, the bullets should _seem_ to fly off with exactly the same speed no matter if you're moving in the same or opposite direction, because _their_ relative velocity compared to _you_ has to be constant.

Air resistance is at play too. The trajectory doesn't look too bad at all.

**Comment by mahdoosh1** [comment]
> The ship doesn't stay in the centre, it moves around in a small radius depending on its velocity. Also, it slows down when reverse-firing. Both are likely contributing factors.

it is called smooth camera, you can disable it in settings >> graphics

**Comment by Otamamori917** [comment]
> Thanks! It's pretty clear after toggling this off that the bullet speed isn't changing.

Yea it's feature not a bug
The pure stupidity of some issue reports just gives me a grin
