### ISSUE TITLE
bugs?

### ISSUE THREAD

**Issue by Everlost065** [Anuken/Mindustry#9928]
### Platforms

Android

### Build

7-official-146

### Issue

hello, I do not show the lists of servers and mods in the mod manager, I do not understand what this is related to (the Internet is on and everything is working properly)

### Steps to reproduce

I am facing this error right now and have not done anything to make it appear.

### Mods used

1) autoDrill
2) virtual sheme pack
3) sheme size

### Save file

[миндастри.zip]
sorry, I do not know how to send the required file:3

### (Crash) logs

![Screenshot_20240608-234038](https://github.com/Anuken/Mindustry/assets/168256363/18bcc475-8ce5-4321-a1c1-864c4b5eeddd)
![Screenshot_20240608-234034](https://github.com/Anuken/Mindustry/assets/168256363/e45f2884-e11d-4879-8bcb-a965582777b1)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by rd-zf-zfy** [comment]
After pulling the code, I found that it was missing the code in the mindustry/gen directory. How did you develop and test the submission?
