### ISSUE TITLE
Turning off "Auto-create saves" doesn't seem to work?

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry#9929]
### Platforms

Windows

### Build

146

### Issue

There is a "Save interval" setting, and an "Auto-create saves" setting. The game seems to completely ignore the toggle, and obeys whatever value is set for the save interval. Thus, there is no way to actually turn off auto-saving in favour of doing it manually.

Unless I'm mistaking the purpose of the auto-create saves setting, in which case there should probably be tooltips available on mouse hover.

### Steps to reproduce

1. Turn off Auto-create saves.
2. Set Save interval to 10 (for testing purposes only; it can be any value).
3. Wait.
4. Game keeps auto-saving every 10 seconds.

### Mods used

None.

### Save file

N/A

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mahdoosh1** [comment]
No, they are not related.

**Comment by mahdoosh1** [comment]
Auto-create saves,

it means that every time you open a `Custom game`, the save will be available in the `Load game` menu
