### ISSUE TITLE
Drill Speed blocked by fog

### ISSUE THREAD

**Issue by Juliosh422** [Anuken/Mindustry#9930]
### Platforms

Linux

### Build

steam build 146

### Issue

The drill speed indicator that shows up when you place a drill gets covered by the fog of war.

#### Example
- Open Ravine map in Erekir campaign
- Try to place a new Impact drill on the ground, next to the other impact drill at the north
- If you hover the drill just below the Fog of War, drill speed can´t be seen
![image](https://github.com/Anuken/Mindustry/assets/72360696/fddb9062-971a-4f22-b149-bb10b690c4e2)

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Not a bug.
