### ISSUE TITLE
Game randomly crashes

### ISSUE THREAD

**Issue by Untiled-infinity** [Anuken/Mindustry#9931]
### Platforms

iOS

### Build

146

### Issue

Whenever I try to refresh the server list or join a server, there is a certain chance that the game crashes.

Probably a ram issue.

### Steps to reproduce

Click the search icon -> sometimes crashes
Join a server -> sometimes crashes

### (Crash) logs

[logs.txt](https://github.com/user-attachments/files/15756385/logs.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mahdoosh1** [comment]
> Sussy log file

No, really its my first time seeing
`Runtime Available Memory: 8796093022207mb`

**Comment by Anuken** [comment]
This has been reported before, and without crash logs or way to reproduce it consistently on my own device I can't help you.
