### ISSUE TITLE
Import figures in Stats screen only updated if hanging around in exporting sector for that resource

### ISSUE THREAD

**Issue by opusforlife2** [Anuken/Mindustry#9934]
### Platforms

Windows

### Build

146

### Issue

The import rate for a resource in the Stats screen of an importing sector is only updated if you hang around in the exporting sector for that resource.

So if you're sending Thorium from A to B, you have to hang around for at least one minute in A in order to see an accurate figure for the import rate in B.

### Steps to reproduce

1. Set up the export of some resource from Sector A to Sector B.
2. Hang around in Sector B and see that the resource is being accumulated over time. Wait as long as you like.
3. Go to the Planet Map and check the Stats for B. No import figure to be found.
4. Hang around in Sector A for at least one minute.
5. Go to the Planet Map and check the Stats for B. Correct import figure now found.

For bonus points:
6. Set up exports of multiple resources, each from a different sector, to the same importing sector.
7. Check the stats of the importing sector after hanging around in each exporting sector for at least one minute.
8. Only that corresponding resource's figure is updated next time you check the Stats screen.

### Mods used

None.

### Save file

N/A

### (Crash) logs

N/A

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
almost like because the game just uses the last 1 minute of stuff sent

**Comment by camelStyleUser** [comment]
its not a bug

**Comment by Anuken** [comment]
See comments above, exporting sectors aren't loaded in the background.
