### ISSUE TITLE
Spawn sector bug

### ISSUE THREAD

**Issue by Gordost33** [Anuken/Mindustry#9939]
### Platforms

Android

### Build

146

### Issue

Spawn issue sector
![Screenshot_2024-06-12-16-52-48-416_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/172512034/64a944c2-4bc1-4065-97a6-4bdadbe994b2)
![Screenshot_2024-06-12-16-57-25-920_io anuke mindustry]

This sector
(https://github.com/Anuken/Mindustry/assets/172512034/10e5e6ec-8120-46a6-a231-00e4a361d066)

### Steps to reproduce

Land on sector

### Mods used

No mods active

### Save file

[save.zip](https://github.com/user-attachments/files/15806326/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
>  I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.

No, you havent.
