### ISSUE TITLE
Проблема с сохранениями

### ISSUE THREAD

**Issue by Makaim20** [Anuken/Mindustry#9941]
### Platforms

Android

### Build

Release build 141.3

### Issue

После того как захватил сектор,и вышел забыв сохраниться,то в тот момент когда снова заходишь в тот же сектор,он становится не захваченным,но проблема не в этом,проблема в том,что когда ты зашёл в этот сектор то те действия которые были сделаны тобою ПОСЛЕ ЗАХВАТА сектора остаются (уничтожение,установка блоков и т.д.)!
И получается такая картина: я захватил сектор,уничтожил ненужные мне блоки (для того чтобы захватить сектор:турели,стены),вышел не 
сохранившись,захожу снова туда и 
мне осталось пройти ещё несколько волн,а стены и турели я уже уничтожил 😐 

(Если кратко,выйдя не сохранившись,твои действия-сохраняются,а то что ты захватил сектор-нет)

### Steps to reproduce

Я просто играл и захватывал сектор 

### Mods used

Отсутствуют 

### Save file

Цент исследования биомассы 
[(invalid).zip](https://github.com/user-attachments/files/15812337/invalid.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Sounds like your sector was attacked, which adds waves to the counter.

>  141.3

This is NOT the latest version.
