### ISSUE TITLE
Processors get enabled when changing "map area" rule

### ISSUE THREAD

**Issue by Redo11** [Anuken/Mindustry#9942]
### Platforms

Linux

### Build

146 steam

### Issue

In my map, i have one processor that disables a bunch of processors at start and waits.
When another processors changes the rule "map area", all the processors get enabled.

### Steps to reproduce

Put a processor that makes something (like a particle effect).
Put a processor that disables the particle processor and halts execution.
Put a processor that changes "map area" rule.
The particle processor gets enabled.

### Mods used

Vanilla

### Save file

[Bug Report.msav.zip](https://github.com/user-attachments/files/15812951/Bug.Report.msav.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
Fixed in private branch
