### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Vato8090** [Anuken/Mindustry#9944]
### Platforms

Windows

### Build

release build 146

### Issue

Hello, hi I have a big problem to play the precipice map because I would need to have 400 tugnesium on the lake map but I have searched all over the map and I couldn't find it, I don't know if it is a problem or an error or a bug. I need you to help me. please

### Steps to reproduce

I was finishing the summit map and when I looked at the requirements to land on the precipice I saw that I was missing 400 tugnesium on the lake map so I went to see if there were any but no. I checked the entire map but there was no

### Mods used

i dont used mods

### (Crash) logs

I don't think they have

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by SITUVNgcd** [comment]
Change to the map which you can mine Tungsten, then launch from it. Not a bug.
