### ISSUE TITLE
While using pixelated graphics messages aren't shown

### ISSUE THREAD

**Issue by Galahadagent** [Anuken/Mindustry#9945]
### Platforms

Android

### Build

Release build 146

### Issue

# issue
While using the pixelated graphics in surpulo and erekir planet or in multiplayers the World messages, messages and Reinforced messages aren't shown.
### Why did I report?
Ans. When I was playing multiplayer using pixelated graphics there was a world message but I couldn't see it due to I was using the pixelated graphics. That's why I reported.
## as you can see in these screenshots

![Screenshot_2024-06-14-00-09-25-947_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/218c9da2-4dfa-4d4f-8016-a69f86bdb6b7)
![Screenshot_2024-06-14-00-09-30-728_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/ea44da47-0623-4f1a-a907-e78bf7f35fa0)
![Screenshot_2024-06-14-00-09-38-050_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/34e62b0f-1ac1-4ac2-b64b-d97bdad74003)
![Screenshot_2024-06-14-00-09-42-937_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/a0de76eb-5b06-4451-90f7-4cdf260176da)
![Screenshot_2024-06-14-00-10-18-716_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/1641cbaf-d3f3-44f3-8c2c-2bdee25b4b44)
![Screenshot_2024-06-14-00-10-27-729_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/5178cd1d-3b86-4b26-8715-478d2525aac1)
![Screenshot_2024-06-14-00-10-39-555_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/91da67db-a0f6-4d87-a965-bc2e132fe3b3)
![Screenshot_2024-06-14-00-10-44-160_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/8dbdf813-23a8-4c61-87e8-0bbe98e4615d)
![Screenshot_2024-06-14-00-16-47-021_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/943b2329-be40-474d-95fe-ce97b44f50e4)
![Screenshot_2024-06-14-00-16-53-547_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/5e6a2e45-a17d-4197-a9ed-51d26ec1bd26)
![Screenshot_2024-06-14-00-16-59-361_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/80a5ae83-63a2-44b2-b739-e6c3980d1756)
![Screenshot_2024-06-14-00-17-07-264_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/161305918/fdd4861e-e879-4fa2-be45-0d94fb860da6)

### Steps to reproduce

Go to Settings -> Graphics -> enable pixelate.
Go to editor or play a custom map where must be a world message, a message and a Reinforced message block available there with some messages, tap on it while using pixelated graphics, then the messages will not be shown (don't click the pencil icon)

### Save file

[Experiment maps.zip](https://github.com/user-attachments/files/15827550/Experiment.maps.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by rylid-umil** [comment]
This was most likely intentional or at least half-intentional, as it would be hard to pixelate text and have it readable at the same time. Though it may still be a bug

**Comment by camelStyleUser** [comment]
https://github.com/Anuken/Mindustry/blob/2d4d38990dd33a02f156056125da8c3cb74f87f1/core/src/mindustry/world/blocks/logic/MessageBlock.java#L74

**Comment by Galahadagent** [comment]
@rylid-umil  @camelStyleUser what should I do?
Should I close this issue as not planned?
Or Anuke is working on it...?

**Comment by Anuken** [comment]
It is intentional.

Pixelation is a legacy feature kept around for the few people who still want it; **I recommend you do not use it**. It will not be improved.
