### ISSUE TITLE
Pressing right click when copying a structure (destroy action) moves the bottom left of the copy selection to the bottom left corner of the map

### ISSUE THREAD

**Issue by Lishouuu** [Anuken/Mindustry#9957]
### Platforms

Windows

### Build

146

### Issue

Pressing right click when copying a structure (destroy action) moves the bottom left of the copy selection to the bottom left corner of the map (title)

Video for bug example

https://github.com/Anuken/Mindustry/assets/61601267/dc24040f-af82-4049-9208-cc67949c4c7f

### Steps to reproduce

1. Press F to copy
2. Drag the selection box
3. Press right click **while holding the F key**
4. Release right click **while holding the F key**

### Mods used

None

### Save file

[save1.zip](https://github.com/user-attachments/files/15858760/save1.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Lishouuu** [comment]
Additional information: If you release the F key, nothing gets copied.

Here's another clip
https://github.com/Anuken/Mindustry/assets/61601267/fda25557-079a-4bcb-9129-c83deafd71b1

**Comment by camelStyleUser** [comment]
seems like its something to do with 
https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/input/DesktopInput.java#L724-L728

**Comment by camelStyleUser** [comment]
seems like it, cant reproduce with that if commented out
