### ISSUE TITLE
Хз шо написати

### ISSUE THREAD

**Issue by Ky2735** [Anuken/Mindustry#9958]
### Platforms

Android

### Build

A32 коштував 10к

### Issue

Граю 100 волна починається жесть вилітає якщо і пройшов її нажимаю зберегти і вийти вилітає 

### Steps to reproduce

Построїв 700 юніту і 100 з них почали мене дефати потім коли зявилася проблема всіх унічтожив торієвиками залишилося 50 далі грав проблема зявлялася але нетак часто 

### Mods used

Схемпак на 400+ схем

### Save file

Термінал планетарного запуску 
[влвот.zip](https://github.com/user-attachments/files/15859065/default.zip)

### (Crash) logs

Пише шо непідтримує тип файлу а я хз як зробити інший

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
a32 the paid mindustry version real

**Comment by Anuken** [comment]
Report is not in English and the translated version is not comprehensible.
