### ISSUE TITLE
Discrepancies across Mac and Windows clients when playing on server

### ISSUE THREAD

**Issue by brettfazio** [Anuken/Mindustry#996]
**Platform**: *Mac/Windows*

**Build**: *99.4 on one and 99.8 on the other*

**Issue**: *As you can see in the screenshots there are massive differences between the Mac and Windows clients when playing on a Linux hosted server. In one screenshot there is proper output of Silicon and improper on the other. And on one screenshot the power/cryofluid is shown as being maximum (wrong) but on another it is producing no power (correct). The screenshots are the exact same game at the exact same time on two different clients.*

*If the problem is that one client was 99.4 and the other is 99.8 shouldn’t we just have been disallowed to connect?*

![unknown](https://user-images.githubusercontent.com/11671691/68174951-a2c69a00-ff4d-11e9-908c-1b82353bba08.png)
<img width="1225" alt="Screen Shot 2019-11-04 at 9 50 44 PM" src="https://user-images.githubusercontent.com/11671691/68174979-b4a83d00-ff4d-11e9-97d6-1595e0497c42.png">

<img width="1225" alt="Screen Shot 2019-11-04 at 9 49 18 PM" src="https://user-images.githubusercontent.com/11671691/68174996-c38eef80-ff4d-11e9-9957-5feccc375eb9.png">
![unknown-2](https://user-images.githubusercontent.com/11671691/68175045-ecaf8000-ff4d-11e9-8b8a-a869c7ed360b.png)

**Steps to reproduce**: *Just play across clients/versions.*

**Comment by Anuken** [comment]
This is well-know; desynchroniation can occur for many different reasons. There is no simple way fix to this problem, although some attempts may be made in the future. Use /sync to synchronize state between clients reliably.
