### ISSUE TITLE
Block saving state while transfering

### ISSUE THREAD

**Issue by DarkOperation** [Anuken/Mindustry#9961]
### Platforms

Android

### Build

146, BE 25073

### Issue

When transfer stopped(by processor) block on unit, the block save his state. 

https://github.com/Anuken/Mindustry/assets/153753809/f2f1d479-6813-4863-80b1-a1b7972f0827

### Steps to reproduce

1. Stop block by processor
2. Using any unit that can carry blocks and with its help move the block to any other place
3. Block save his state

### Mods used

None

### (Crash) logs

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
I don't think it's a bug, it's intended

**Comment by Anuken** [comment]
Not a bug.
