### ISSUE TITLE
Проблема с волнами на секторе

### ISSUE THREAD

**Issue by Cetlol8** [Anuken/Mindustry#9962]
### Platforms

Android

### Build

Release build 146

### Issue

Когда я начинаю захватывать сектор на второй волне на меня идёт 1001 врагов
![Screenshot_2024-06-17-15-42-53-663_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/173063478/f7b5bd26-3acd-47c0-958d-a89c061ea889)

### Steps to reproduce

Высадился на сектор для захвата

### Mods used

Нету модов

### Save file

Файл весит больше чем разрешено на сайте (44 мб) .Сектор номер 24

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Cetlol8** [comment]
Пошол нахуй чорт
