### ISSUE TITLE
Op error

### ISSUE THREAD

**Issue by ZeleniyKustik** [Anuken/Mindustry#9963]
### Platforms

Windows

### Build

146

### Issue

When I subtract a relatively small number from numbers that occupy 54 to 63 bits, the number doesn't change.
![i1](https://github.com/Anuken/Mindustry/assets/126210243/f698bd6e-6a34-4c6d-93d3-da4c6b5c4d77)
![i2](https://github.com/Anuken/Mindustry/assets/126210243/cf892e8a-6fac-4db9-a7a9-de2a82f26ed4)
|
|
![i3](https://github.com/Anuken/Mindustry/assets/126210243/09b9fd1a-c874-4f3a-8d59-e34cb29acf65)
![i4](https://github.com/Anuken/Mindustry/assets/126210243/e8bda356-75c7-451c-8ec4-4a1e99c06cf0)
|
|
With 53 bits, everything works fine
![i5](https://github.com/Anuken/Mindustry/assets/126210243/13ed48d2-ac18-4e2a-b459-41ad98bee9ad)
![i6](https://github.com/Anuken/Mindustry/assets/126210243/2abf60c4-9ac7-4f17-b14e-d0bf144d36d8)

### Steps to reproduce

Entered this code into the processor
op shl result 1 54
op sub q result 1

### Save file

[Op Error.zip](https://github.com/user-attachments/files/15880381/Op.Error.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
thats what float64s do

**Comment by camelStyleUser** [comment]
where is the bug

**Comment by ZeleniyKustik** [comment]
Okay, so it's not a bug. It's just that I used it to generate the bitmask. I got around it, but since I don't know much about it. I filed a report because I thought it was a bug.
