### ISSUE TITLE
Unidades presas

### ISSUE THREAD

**Issue by T34ago** [Anuken/Mindustry#9968]
### Platforms

Android

### Build

146

### Issue

Eu criei algumas unidades para explorar o mapa,mas quando fui explorar,descobri que a área que criei as unidades era fechada,agora me resta apenas algumas unidades,pois as outras estão presas em um lugar fechado.Eu não tenho certeza se isso é um bug,mas preciso de ajuda.

### Steps to reproduce

Crie uma fabrica de nave ou alguma outra fabrica de unidades que não passem por paredes em um lugar fechado,o limite de unidades é 30,se todas estiverem presas,não dá mais para invocar outras unidades.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
if you have 30 units of a type your unit cap is reached
