### ISSUE TITLE
Desynchronization of variables consisting of value from random operation inside of processors.

### ISSUE THREAD

**Issue by Redo11** [Anuken/Mindustry#9970]
### Platforms

Linux

### Build

146 steam

### Issue

When a processor assigns a random value to a variable, there is an automatic desynchronization between the server and client. 
I am making a gimmick map, heavily dependent on logic that uses randomized variables in multiple places. It works absolutely fine in single player, but in multiplayer, it causes problems, as effects are spawning in wrong places, resources get added and removed when client synchronizes them back and fake values inside of storage cells being presented client side.

### Steps to reproduce

Make a processor, put code that randomizes two values with @mapw and @maph being saved as x and y
Next put some code that shows a visual effect at the random positions. 
Start another instance and join the game.
The effect will be spawned in 2 different locations for each client 

### Mods used

Vanilla

### Save file

[minedustry 4.msav.zip](https://github.com/user-attachments/files/15904946/minedustry.4.msav.zip)
my map.
The boulders spawn effect is played at a wrong place on a separate client and "mined boulders" variable at the top is wrong/fake.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
thats like what rand does

**Comment by camelStyleUser** [comment]
where is da bug

**Comment by camelStyleUser** [comment]
use `sync`

**Comment by Redo11** [comment]
i am using sync

**Comment by Redo11** [comment]
the problem still persists

**Comment by Redo11** [comment]
> thats like what rand does

I don't think it's intended to cause desynchronization between clients.
I have a use case for rand that requires it to be synchronized to be properly playable.

**Comment by camelStyleUser** [comment]
> the problem still persists

how often are you using sync
and are you waiting at least a little bit

**Comment by Redo11** [comment]
> > the problem still persists
> 
> how often are you using sync and are you waiting at least a little bit

i am using the function constantly. The whole gameplay of my map depends on it.

**Comment by camelStyleUser** [comment]
> > > the problem still persists
> > 
> > 
> > how often are you using sync and are you waiting at least a little bit
> 
> i am using the function constantly. The whole gameplay of my map depends on it.

it has a delay

**Comment by camelStyleUser** [comment]
certainly you can wait a tick

**Comment by Redo11** [comment]
What do you mean wait a tick? Where? When? And why is that required and not specified?

**Comment by camelStyleUser** [comment]
> What do you mean wait a tick? Where? When? And why is that required and not specified?

its 3 ticks my bad
![image](https://github.com/Anuken/Mindustry/assets/124447863/b094886a-0b8f-4c7a-8e4e-8394c04ee4ce)

**Comment by Redo11** [comment]
Since it's per variable, it should be fine. I already have 0.03 wait, I will bump it to 0.05, but it shouldn't be the main cause either.

**Comment by Redo11** [comment]
![image](https://github.com/Anuken/Mindustry/assets/49594490/5e0d124f-2dec-4a43-bdcd-7bb85c334922)
Spawning visual effects appear on the client side, where on the host/server side they do not exist, since nothing is spawning. The client thinks the X and Y variables as well as random wait time are absolutely different variables from the truth of host.

**Comment by Redo11** [comment]
![image](https://github.com/Anuken/Mindustry/assets/49594490/80198ce6-5cf2-453c-88e3-20e93462a79c)
↑Client
![image](https://github.com/Anuken/Mindustry/assets/49594490/38c91b89-e00f-4c4b-a5eb-62c552dee10c)
↑ host

**Comment by camelStyleUser** [comment]
> ![image](https://private-user-images.githubusercontent.com/49594490/341185905-5e0d124f-2dec-4a43-bdcd-7bb85c334922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTc0MDgsIm5iZiI6MTcxODg1NzEwOCwicGF0aCI6Ii80OTU5NDQ5MC8zNDExODU5MDUtNWUwZDEyNGYtMmRlYy00YTQzLWJkY2QtN2JiODVjMzM0OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA0MTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MGMwMjQ0Mjk0MWEzMTU4MWQyY2EzZDQ1OGNlY2M5MGJhZWZhMmIxZjEwN2RiMzAxM2M5MzE4ZDY2OWM3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUPd4KwA_0oA0FZochuaaJESSqb4wX-1zA_v_vbA3jQ) Spawning visual effects appear on the client side, where on the host/server side they do not exist, since nothing is spawning. The client thinks the X and Y variables as well as random wait time are absolutely different variables from the truth of host.

do you expect every single double to be synced over the network?

**Comment by Anuken** [comment]
Attempts are made to synchronize the random value, but it's not reliable, and never will be. Don't use random when synchronization matters.
