### ISSUE TITLE
Breach not revealing full range

### ISSUE THREAD

**Issue by MicMara256** [Anuken/Mindustry#9971]
### Platforms

Mac

### Build

146

### Issue

I was playing the Erekir campaign, and I put tungsten ammo into a breach. I noticed that the turret was not revealing its entire range, but it was instead revealing the range it would have if it had had beryllium ammo.

### Steps to reproduce

on a map with fog of war enabled, build a breach near the edge of the area you can see and supply it with tungsten. You will see that the dashed yellow border goes outside of your viewing distance.

### Mods used

I did not use any mods

### Save file

I recreated it on a custom game because my save file was too big. [turrets not revealing full range.msav.zip](https://github.com/user-attachments/files/15905309/turrets.not.revealing.full.range.msav.zip)

### (Crash) logs

My game did not crash

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
It's intended behavior, it will to it to any ammo type that has a increase/decrease in range

**Comment by Anuken** [comment]
Fog revealing range does not change based on ammo type.
