### ISSUE TITLE
Problem with enemy base unit factories

### ISSUE THREAD

**Issue by RiptheBlood** [Anuken/Mindustry#9976]
### Platforms

Windows

### Build

Steam Build 146

### Issue

While playing through the map, working on the grind to conquer all of Serpulo, I noticed a couple problems with some unit factories. Specifically, the Medium threat level bases with Titanium walls. There seems to be a nice setup for T1 and 2 units utilizing scrap to melters and separators. But there just isn't a proper coal input. There is a Coal Centrifuge, but no Oil Extractor so this entire factory does nothing. (Which is funny because the picture provided has a coal deposit below it for turret ammo instead)

To be honest the main reason I noticed was when I started copying some of these buildings as schematics. There are a couple variations, but specifically in Medium threat level enemy bases they are all the same with a nice, compact factory but a useless coal centrifuge. Not sure if this is intentional for exactly what I am doing, copy/paste and fix the design for myself, but it just seems pointless to have in an enemy base rather than as derelict ruins to try to repair.

This is an image in Sector 49, but I have noticed this on similar sectors (I cannot remember exact numbers but the threat level was the same)
![image_2024-06-21_171401413](https://github.com/Anuken/Mindustry/assets/160272195/8071b8af-2785-4160-9a96-3eb949790763)

### Steps to reproduce

- Start a new game
- Enter a Medium-threat level enemy base sector
- Look for unit factories and observe

### Mods used

None

### Save file

[FunStuff.zip](https://github.com/user-attachments/files/15933940/FunStuff.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
base generation is stupid, who could have thought

**Comment by Anuken** [comment]
The base generation has since been changed, and I cannot reproduce the same problem in sector 49.
