### ISSUE TITLE
Java Modding Bug

### ISSUE THREAD

**Issue by Benny0Li** [Anuken/Mindustry#9977]
### Platforms

Linux

### Build

146

### Issue

If I made a bug in my Mod, and Mindustry will

`[E] Failed to load mod file /home/benny/.local/share/Mindustry/mods/originalBetaVersion1.zip. Skipping.
[E] java.lang.ExceptionInInitializerError`

That's all right but my Mod won't be seen in ```Mods```, what mean I must open the folder and delete it.

### Steps to reproduce

1. I found a bug and debugged it.
2. When I reload my Mod,it doesn't work.
3. After a long time, when I open the Mods folder, there are about eight clone of my Mod
4. I delete all the bug Mod and reload.
5. Now it works well.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
What even is bozo reporting

**Comment by JasonP01** [comment]
> I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

Also liar

**Comment by Benny0Li** [comment]
It should be an advice

**Comment by SMOLKEYS** [comment]
If your mod's main class throws an error during initialization, Mindustry will skip it.

**Comment by Benny0Li** [comment]
> If your mod's main class throws an error during initialization, Mindustry will skip it.

In fact, because of "Mindustry will skip it", the Mod won't be delete or be rewrite when I reload the bug-fixed mod, so there will be lots of fixed mod and a wrong mod, and Mindustry will load the wrong one.
