### ISSUE TITLE
проблема браузера модификаций

### ISSUE THREAD

**Issue by Arte2r2** [Anuken/Mindustry#9978]
### Platforms

Android

### Build

146

### Issue

при попытке поиска модификации в браузере модификаций возникает ошибка
![Screenshot_2024-06-22-19-18-26-536_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/173562202/5fe4909b-fe5f-43c5-b6b6-e9c76bbfc1ce)

### Steps to reproduce

возможно это появилось после установки мода Hard mode, сейчас я его удалил но ошибка не пропала.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
bad internet issue

**Comment by Arte2r2** [comment]
> плохая проблема с интернетом

я тоже так подумал, на пару дней назад всë было хорошо
