### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by Ultra6131** [Anuken/Mindustry#9984]
### Platforms

Android

### Build

146

### Issue

the game does not see the Internet, but the Internet is present on the phone, and everything is fine on the computer. The problem is that Mindastri doesn't want to use Wi-Fi

### Steps to reproduce

I wasn't doing anything special, I was just playing and everything was fine, but why did mindastri stop connecting to the network

### Mods used

Scheme size

### Save file

[ащащащащащщс.zip](https://github.com/user-attachments/files/15990816/default.zip)

### (Crash) logs

[abobus. zip](https://github.com/user-attachments/files/15990910/abobus.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment]
> Mindastri(sic) doesnt want to use wifi

your source for "it doesnt want to use wifi"?because the game doesnt care about if you use mobile internet or wifi

**Comment by Ultra6131** [comment]
there is Internet on the phone, but mindastri does not perceive it, although the phone works fine

**Comment by Matita008** [comment]
> there is Internet on the phone, but mindastri does not perceive it, although the phone works fine

Can you send an image?
