### ISSUE TITLE
Cannot connect to servers - trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by sdsquire** [Anuken/Mindustry#9991]
### Platforms

Linux

### Build

146

### Issue

For the first time, I tried to get on the public servers. However, when I opened the servers list, nothing appears. I tried manually putting in the IP, I still couldn't connect.
![image](https://github.com/Anuken/Mindustry/assets/78835259/c7ea12bb-e13b-4b8d-b09f-5e6d3118ac80)

To troubleshoot, I examined the following:

- I was connected to the internet, and it was working for all other applications
- I restarted my computer
- I confirmed that all other parts of the game were working. One was broken (described below).
- I uninstalled / reinstalled the Java Virtual machine. I tried both versions I had - 8 and 11 - activating and reinstalling both.
- I updated certificates and alternatives (`sudo update-ca-certificates -f`, `sudo dpkg-reconfigure ca-certificates-java`, `sudo update-alternatives --config java`

I investigated the _Mods_ section to see if I could stream them. I encountered the following errors as seen below.
![image](https://github.com/Anuken/Mindustry/assets/78835259/f4848ea2-4e97-4686-8f96-0f9cb117c058)
![image](https://github.com/Anuken/Mindustry/assets/78835259/0c0ca800-9ca8-43c9-9e2a-4328ce72af20)
![image](https://github.com/Anuken/Mindustry/assets/78835259/62298483-6cb6-461e-a7e0-e3e29298a464)

### Steps to reproduce

Do any action that accesses the internet. If trying to stream mods, you can see the error.

### Mods used

None

### Save file

I tried to reinstall the game while troubleshooting to see if that would fix the problem. Unfortunately, it wiped my save.  I confirmed that it still doesn't work with a clean install.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment]
> I uninstalled / reinstalled the Java Virtual machine. I tried both versions I had - 8 and 11 - activating and reinstalling both.

Do not use either of those versions. Use the version that is packaged with the game on Steam/itch - this is directly caused by your Java version.

**Comment by sdsquire** [comment]
I installed Mindustry via the snap package, `sudo snap install mindustry`. I have tried reinstalling it, but the issue persists. Is this not a supported installation method?

**Comment by Matita008** [comment]
> I installed Mindustry via the snap package, `sudo snap install mindustry`. I have tried reinstalling it, but the issue persists. Is this not a supported installation method?

Have you tried to launch mindustry while having JDK 16-17?

**Comment by Anuken** [comment]
> Is this not a supported installation method?

I don't maintain the Snap version and I have no idea what Java version it uses. Steam/itch are the only officially supported desktop versions.

**Comment by sdsquire** [comment]
Good to know. Thank you. I will try to install it while running JDK 16/17
