### ISSUE TITLE
Attack mode, infinity resources

### ISSUE THREAD

**Issue by OhnoTim** [Anuken/Mindustry#9992]
### Platforms

Android

### Build

release build 146

### Issue

If I play a map with attack, the enemy AI, has infinity resources even if I disable infinity resources in the settings of this map

### Steps to reproduce

I just played the game and it happens on all maps even self made maps

### Save file

[Data.zip](https://github.com/user-attachments/files/16044683/Data.zip)

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by JasonP01** [comment]
Enemy team is hardcoded to have infinite resources, this is intentional behaviour

**Comment by OhnoTim** [comment]
> Enemy team is hardcoded to have infinite resources, this is intentional behaviour
But they build everything back before I can even destroy it

**Comment by mahdoosh1** [comment]
> Enemy team is hardcoded to have infinite resources, this is intentional behaviour 

So this becomes a suggestion to add ability to disable enemy infinite resources

**Comment by JasonP01** [comment]
> So this becomes a suggestion to add ability to disable enemy infinite resources

Wrong repository for suggestions, anuke doesnt do suggestions in bug reports, he only fixes bugs

**Comment by OhnoTim** [comment]
Okay, sorry and thanks

**Comment by Matita008** [comment]
> Okay, sorry and thanks

So close this
