### ISSUE TITLE
Integrated map seemingly disappeared 

### ISSUE THREAD

**Issue by JojoFR1** [Anuken/Mindustry#9996]
### Platforms

Android

### Build

b146

### Issue

When going in the Custom Game or Editor menu the integrated maps are gone and leaving an empty menu (except if there's custom map).
![Screenshot_2024-07-02-01-40-28-164_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/110781915/ce8d2613-36ad-4b75-841b-9dc68810531a)
![Screenshot_2024-07-02-01-40-25-848_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/110781915/d93e3d13-fb52-49ff-a503-cc45ae89f0bc)

I don't know how or when this happened. I tried many different things which didn't worked.
I first tried to clean the save and importing it again, hopping it would've kept the integrated map but they also got deleted, hinting the map being deleted is caused by something in the exported save.
I then compared a clean and current exported save, with the only difference being the `settings.bin` file, the clean save having nothing else.
I also directly compared the file in `Android/data/io.anuke.mindustry` and there is no noticeable differences between them.

I tried, on a clean save, to export a map and, after importing my save, importing that map which gave me an error: it had the "Same name as an integrated map", so the map do exist internally but they're not available for some reason.

### Steps to reproduce

- Clear your data
  - The integrated maps are presents in Custom Game and Editor
- Import save (linked under)
  - The integrated map are gone, leaving an empty menu (first save) or one custom map (second save)

### Mods used

None. Tried with and without mods.

### Save file

First save, with none of the maps:
[mindu.zip](https://github.com/user-attachments/files/16059833/mindu.zip)

Second save, with none of the maps + one custom map (an attempt when I was comparing the saves):
[mindusave.zip](https://github.com/user-attachments/files/16059832/mindusave.zip)

### (Crash) logs

The logs were checked and they're plain empty, the normal output.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by mahdoosh1** [comment]
wait what? i thought internal maps are stored in the game's apk file. but i see those are deleted somehow.

**Comment by JasonP01** [comment]
You disabled built in maps via the filter on the top right, re-enable them

**Comment by JojoFR1** [comment]
> You disabled built in maps via the filter on the top right, re-enable them

Yep that was that, I didn't know you could do that.
Thanks!
